### ISSUE TITLE
undefined symbol: cuDevicePrimaryCtxRetain

### ISSUE THREAD

**Issue by dahangli** [tensorflow/tensorflow#10020]
Ubuntu 14.04    / NVIDIA GTX 1060

I try nvidia 710 with Ubuntu 14.04,s ok!
I try nvidia 1060 with Ubuntu 14.04, Fault! -- undefined symbol: cuDevicePrimaryCtxRetain！

NVIDIA-Linux-x86_64-375.66.run
cuda_8.0.61_375.26_linux.run
CuDNN5.1
Anaconda3-4.3.1-Linux-x86_64.sh （Python3.6）
TensorflowGPU1.1.0

I have install this profile in one computer( not the same hardware) success.
But, today, another computer.
I get that:

import tensorflow as tf
Traceback (most recent call last):
File "/home/student/miniconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 41, in 
from tensorflow.python.pywrap_tensorflow_internal import *
File "/home/student/miniconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in 
_pywrap_tensorflow_internal = swig_import_helper()
File "/home/student/miniconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
_mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
File "/home/student/miniconda3/lib/python3.6/imp.py", line 242, in load_module
return load_dynamic(name, filename, file)
File "/home/student/miniconda3/lib/python3.6/imp.py", line 342, in load_dynamic
return _load(spec)
ImportError: /home/student/miniconda3/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: cuDevicePrimaryCtxRetain

**Comment by gunan** [comment]
Please provide the full information required by the issue template.
Also, just searching through issues with your error, I see some related issues.
Did you search and try the suggestions in those issues?
https://github.com/NVIDIA/nvidia-docker/issues/262

**Comment by log0ymxm** [comment]
This looks like it was previously reported in https://github.com/tensorflow/tensorflow/issues/9866

**Comment by gunan** [comment]
Closing due to inactivity, and possible duplicate.
