### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by elijahFTL** [tensorflow/tensorflow#10033]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **TensorFlow installed from (source or binary)**: Binary
- **TensorFlow version (use command below)**: unknown, command fails (this is the problem)
- **Bazel version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: 8.0/5.1
- **GPU model and memory**: GeForce GTX 970, 4 GB
- **Exact command to reproduce**: import tensorflow as tf

### Problem
This is something I've seen in a [previous issue report](https://github.com/tensorflow/tensorflow/issues/5949) added as a comment, but no one responded to it (except to say that you should be using cuDNN 5.1 instead of 6.0, which I am doing). I cannot even import tensorflow because it leads to the string of errors below. Someone in the linked issue suggested that this was caused by a missing MSVCP140.DLL, but this file is present in both my System32 and SysWOW64 folders (I have seen both mentioned). I have also installed the suggested Visual C++ Redistributable Update 3 with no luck.

### Log

Traceback (most recent call last):
  File "C:\Users\Elijah\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Users\Elijah\AppData\Local\Programs\Python\Python35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 577, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 906, in create_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Elijah\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Elijah\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 21, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Elijah\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 20, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow_internal')
  File "C:\Users\Elijah\AppData\Local\Programs\Python\Python35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Elijah\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "C:\Users\Elijah\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\__init__.py", line 51, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Elijah\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 52, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Elijah\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Users\Elijah\AppData\Local\Programs\Python\Python35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 577, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 906, in create_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Elijah\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Elijah\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 21, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Elijah\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 20, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow_internal')
  File "C:\Users\Elijah\AppData\Local\Programs\Python\Python35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: No module named '_pywrap_tensorflow_internal'

**Comment by ali01** [comment]
Hey @mrry, any thoughts about this Windows build?

**Comment by mrry** [comment]
It's almost certainly a missing directory from the `%PATH%` environment variable. The most common error is that the directory containing the cuDNN DLL is not in `%PATH%`, as it's different from where the rest of the CUDA DLLs are installed.

**Comment by elijahFTL** [comment]
@mrry, my `%PATH%` includes the directory I extracted my cuDNN download into (it contains nothing but the `cuda` folder at the root of the archive). I have also tried changing `%PATH%` to be this `cuda` subdirectory, but this produced the same result. Do I need to go even further and add the `cuda\bin` subdirectory because that's what the DLL is in? Going to try that soon.

**Comment by mrry** [comment]
Yes, you'll need to add the `cuda\bin` subdirectory to get Windows to find the DLL (the DLL loading code doesn't search subdirectories, unfortunately).

**Comment by prateekgv** [comment]
I got the same error too. Was anyone able to fix this?

**Comment by mlghost** [comment]
I  have same problem . My %PATH% directory includes cuda\bin and cuDNN dll file copied there 
What is solution for my problem ?

**Comment by elijahFTL** [comment]
Apologies for the late response, but what @mrry posted 8 days ago completely solved my issue. Thanks! Closing this now.

**Comment by mlghost** [comment]
:|

**Comment by mikler** [comment]
5.1 instead of 6 worked for me as well. But what pisses me off big time is that it doesn't say which exact DLL didn't it find!

**Comment by mrry** [comment]
Yes, it's unfortunate that the Win32 `LoadLibrary()` call doesn't produce a better error message! I've been mentioning this on some other issue threads, but I uploaded a script that can help to check common installation issues for TensorFlow on Windows. You can get it here:

https://gist.github.com/mrry/ee5dbcfdd045fa48a27d56664411d41c

**Comment by jingyibo123** [comment]
Same problem here, worked after changing to cuDNN5.1 instead of 6.0.
win10 x64
Python 3.5
Tensorflow-gpu 1.1.0

**Comment by jianglai** [comment]
You do not need to downgrade from cuDNN 6.0 to 5.1. Making a symlink of cudnn64_6.dll, named as cudnn64_5.dll works just fine. It seems that TensorFlow hardcoded the dll file name.

**Comment by byronyi** [comment]
@jianglai Or how about keeping both versions? Symlink trick may be dangerous and misleading.

**Comment by jianglai** [comment]
@byronyi Sure I was just pointing out that 6.0 itself works. TensorFlow is hardcoded looking for the filename for 5.1.

**Comment by QROST** [comment]
I solved this problem by duplicate a `cudnn64_6.dll` into `cudnn64_5.dll` in the `cuda\bin` dictionary. Thx @jianglai

**Comment by byronyi** [comment]
@QROST @jianglai Please be careful. You could download cuDNN v5.1 and place it in the same folder of cuDNN v6.0. Making alias of different versions is generally not considered as a good practice.

**Comment by sidshetye** [comment]
[NVidia's instructions](http://developer2.download.nvidia.com/compute/machine-learning/cudnn/secure/v5.1/prod/doc/cudnn_install.txt) are wrong

```
ALL PLATFORMS

    Extract the cuDNN archive to a directory of your choice, referred to below as <installpath>.
    Then follow the platform-specific instructions as follows.
```
## Wrong
```
WINDOWS

    Add <installpath> to the PATH environment variable.
```

## Correct
```
WINDOWS

    Add <installpath>\bin to the PATH environment variable.
```

**Comment by mhyipa** [comment]
I have the same problem too. I have done all the followings, but still does not work......

Installed Python 3.5.3
Installed CUDA 8.0
Installed cuDNN v5.1 (copied the cudnn64_5.dll into CUDA/bin)
Have msvcp140.dll in both system32 and sysWOW64
Add the CUDA/bin path into %PATH%
Both dll files can be located using "where" in command prompt

What do I miss?

**Comment by mrry** [comment]
@mhyipa Assuming you just installed TensorFlow 1.3, you'll need to upgrade to cuDNN v6, and put `cudnn64_6.dll` in your `%PATH%`.

**Comment by charlie5y** [comment]
@mrry Great thanks! I just struggled hard with the same issue.
Upgraded TensorFlow (1.3) should go with cuDNN v6.0!

**Comment by bhatiaabhinav** [comment]
Yes ... Tensorflow (1.3) does not go with cuDNN v7.

**Comment by mishra-arjun** [comment]
@mrry Thank you so much for all the help and the self-check script!

**Comment by gauravk97** [comment]
I have the same problem too. 
My setup is as follows:

Installed Python 3.6.0
Installed CUDA 9.0 RC
Installed cuDNN v7
And Installed TensorFlow version 1.3

**Comment by gauravk97** [comment]
I did downgrade to CUDA 8.0.61 and cuDNN v6.0, tf 1.3

**Comment by arieltci** [comment]
Windows 10
Python 3.6.3
CUDA 8
cuDNN v6
Tensorflow 1.3.0
Added CUDA/bin to path
Still does not work.

**Comment by FangliangBai** [comment]
@gauravk97 I saw the solution for CUDA 9 and cuDNN 7 on the internet. Please have a search if interested

**Comment by Chrisinger** [comment]
Currently this problem comes up whan not using the latest version of tensorflow. Using 1.4.0rc0 fixed it for me.

**Comment by bopeton** [comment]
Hey @mrry I ran your script and got the following output:

C:\Users\___\Desktop>python tensorcheck.py
ERROR: Failed to import the TensorFlow module.

- Python version is 3.6.

- TensorFlow is installed at: C:\Program Files\Python36\lib\site-packages\tensorflow

- All required DLLs appear to be present. Please open an issue on the
  TensorFlow GitHub page: https://github.com/tensorflow/tensorflow/issues

It says to open a new issue, but it's the same error as in this thread when I try to do import tensorflow.

I have TF 1.3, CuDNN 5, 6, and 7 all on the path, and CUDA 8.0

installed TF with pip instead of anaconda.

**Comment by mrry** [comment]
@bopeton Can you try upgrading to the TF 1.4.0 release candidate and see if that fixes the problem (or gives a more useful error message)?

**Comment by bopeton** [comment]
@mrry 

Thank you for responding!

I solved the problem and it was much dumber than I thought. My SSD had run out of space while CUDA 8.0 was installing so there were problems with that. I re-installed CUDA and everything is fine now.

**Comment by AdnanBoota** [comment]
I am beginner with tensorflow, having same problem. Can we run webcam detection with opencv without cuDNN?

Let me know please

**Comment by npeirson** [comment]
I had this problem and solved it thusly:
Anaconda3 was installing tensorflow-gpu 1.1, while the latest version (with cuDNN 7 support) is 1.6. I had to manually update it and all of its dependencies, and that fixed it.

**Comment by rakibulhaq** [comment]
i am facing the same issue, but i have installed the tensorflow without GPU using:
pip3 install --upgrade tensorflow
python version 3.6.5 64bit [amd64]
i did not install GPU version,so do i need the cuDNN ?

**Comment by akhil30garg** [comment]
just downgrade tensorflow version to 1.5...............wasted 4 days to get this right...................rest all worked fine automatically.
use command "pip install tensorflow==1.5"

**Comment by sydjameer** [comment]
I had similar issue when trying to run executable file built using pyinsatller. I resolved it pasting the dll file and folder in the directory of the executable and it worked, I found which dll file inside ibm_db.py which was showing dll load failed: the specific module could not be found. Good luck

**Comment by AloshkaD** [comment]
Reinstalling nvidia driver fix this issue for me.

**Comment by Amitarawat05** [comment]
tensorflow has some issues with python 3.6.
Try installing using
pip install tensorflow in python 3.5.2.
Worked for me

**Comment by ambakick** [comment]
Download and install numpy+mkl file. Currently you might have installed only the numpy file.

1. Go to : https://www.lfd.uci.edu/~gohlke/pythonlibs/#numpy

2. Download the corresponding wheel file in which is suitable for your python installation

3. pip install "/path_to_thefile/numpy-1.14.6+mkl-cp36-cp36m-win_amd64.whl"

This should help you

**Comment by greerviau** [comment]
I had this exact problem. I went to the TensorFlow GPU Support page and noticed that there is a required path variable I was missing `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin` After adding that path it worked perfectly for me.

**Comment by vishwasmehra** [comment]
Hello I am also facing same issues. For the first time the issue was of py_wrap module missing. I resolved it by installing visual c++ 2015. 
Now i am getting a different error "
  File "C:\Users\vishw\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)"  

and in the last this is what i got "ImportError: DLL load failed: The specified module could not be found.
Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors" . 
My laptop has 1050gtx for which looked on nvidia supported cuda version and for my machine it was cuda 9.2 and cuDNN 7.4 version. Please help me out here. My nvidia driver version is 398.35. Any help will be appreciated.

**Comment by gargisri68** [comment]
(TenKer) C:\Users\DELL7810>python
Python 3.6.8 |Anaconda, Inc.| (default, Feb 21 2019, 18:30:04) [MSC v.1916 64 bi
t (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
Traceback (most recent call last):
  File "C:\Users\DELL7810\Anaconda3\envs\TenKer\lib\site-packages\tensorflow\pyt
hon\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\DELL7810\Anaconda3\envs\TenKer\lib\site-packages\tensorflow\pyt
hon\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\DELL7810\Anaconda3\envs\TenKer\lib\site-packages\tensorflow\pyt
hon\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, descript
ion)
  File "C:\Users\DELL7810\Anaconda3\envs\TenKer\lib\imp.py", line 243, in load_m
odule
    return load_dynamic(name, filename, file)
  File "C:\Users\DELL7810\Anaconda3\envs\TenKer\lib\imp.py", line 343, in load_d
ynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\DELL7810\Anaconda3\envs\TenKer\lib\site-packages\tensorflow\__i
nit__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-im
port
  File "C:\Users\DELL7810\Anaconda3\envs\TenKer\lib\site-packages\tensorflow\pyt
hon\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\DELL7810\Anaconda3\envs\TenKer\lib\site-packages\tensorflow\pyt
hon\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\DELL7810\Anaconda3\envs\TenKer\lib\site-packages\tensorflow\pyt
hon\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\DELL7810\Anaconda3\envs\TenKer\lib\site-packages\tensorflow\pyt
hon\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\DELL7810\Anaconda3\envs\TenKer\lib\site-packages\tensorflow\pyt
hon\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, descript
ion)
  File "C:\Users\DELL7810\Anaconda3\envs\TenKer\lib\imp.py", line 243, in load_m
odule
    return load_dynamic(name, filename, file)
  File "C:\Users\DELL7810\Anaconda3\envs\TenKer\lib\imp.py", line 343, in load_d
ynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
>>>

please tell what is the issue...

**Comment by luminouspoint47** [comment]
runfile('C:/Users/MG_14/Desktop/shiba kumar/MainEEGLearn/cnn_lstn_lib_eeg.py', wdir='C:/Users/MG_14/Desktop/shiba kumar/MainEEGLearn')
Traceback (most recent call last):

  File "<ipython-input-1-d0d50d859070>", line 1, in <module>
    runfile('C:/Users/MG_14/Desktop/shiba kumar/MainEEGLearn/cnn_lstn_lib_eeg.py', wdir='C:/Users/MG_14/Desktop/shiba kumar/MainEEGLearn')

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 786, in runfile
    execfile(filename, namespace)

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/MG_14/Desktop/shiba kumar/MainEEGLearn/cnn_lstn_lib_eeg.py", line 4, in <module>
    import matplotlib.pyplot as plt

  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\pyplot.py", line 31, in <module>
    import matplotlib.colorbar

  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\colorbar.py", line 32, in <module>
    import matplotlib.artist as martist

  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\artist.py", line 16, in <module>
    from .path import Path

  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\path.py", line 21, in <module>
    from . import _path, rcParams

ImportError: DLL load failed: The specified module could not be found.

**Comment by rishabhbhatt009** [comment]
> In my case, `cudnn64_5.dll` wasn't found in the path. I did RTFM but TFM was wrong. i.e. [NVidia's instructions](http://developer2.download.nvidia.com/compute/machine-learning/cudnn/secure/v5.1/prod/doc/cudnn_install.txt) to install cuDNN are wrong (nvidia please fix if you see this)
> 
> So download cuDNN v5.1 (Jan 20, 2017), for CUDA 8.0 at https://developer.nvidia.com/rdp/cudnn-download
> 
> Then do this:
> 
> ```
> ALL PLATFORMS
> 
>     Extract the cuDNN archive to a directory of your choice, referred to below as <installpath>.
>     Then follow the platform-specific instructions as follows.
> ```
> But then it's ...
> 
> ## Wrong
> ```
> WINDOWS
> 
>     Add <installpath> to the PATH environment variable.
> ```
> ## Correct
> ```
> WINDOWS
> 
>     Add <installpath>\bin to the PATH environment variable.
> ```

I have done this still i am getting the following error 

Python 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 03:37:03) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
Traceback (most recent call last):
  File "D:\SETUP\VISUAL STDS\Python36_64\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "D:\SETUP\VISUAL STDS\Python36_64\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "D:\SETUP\VISUAL STDS\Python36_64\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "D:\SETUP\VISUAL STDS\Python36_64\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "D:\SETUP\VISUAL STDS\Python36_64\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\SETUP\VISUAL STDS\Python36_64\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "D:\SETUP\VISUAL STDS\Python36_64\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "D:\SETUP\VISUAL STDS\Python36_64\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "D:\SETUP\VISUAL STDS\Python36_64\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "D:\SETUP\VISUAL STDS\Python36_64\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "D:\SETUP\VISUAL STDS\Python36_64\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "D:\SETUP\VISUAL STDS\Python36_64\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "D:\SETUP\VISUAL STDS\Python36_64\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by bavincen** [comment]
DLL Import Error can be resolved by installing latest c++
[https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads)

**Comment by mihaimaruseac** [comment]
Since the above is the solution, and to prevent future messages hiding it, I'm going to go ahead and lock the converstation.
