### ISSUE TITLE
Tensorboard problem with pandas

### ISSUE THREAD

**Issue by soartseng** [tensorflow/tensorflow#10067]
This is my first time to practice the tensorflow and tensorboard function.
My code below:
`import tensorflow as tf
a = tf.constant(10,name='a')
b = tf.constant(90,name='b')
y=tf.Variable(a+b*2, name = 'y')
model = tf.global_variables_initializer()
with tf.Session() as session:
    merged = tf.summary.merge_all()
    file_writer = tf.summary.FileWriter("/temp/to/logs",session.graph)
    session.run(model)
    print(session.run(y))`
Then I open the terminal and enter the following:
`tensorboard --logdir=/tmp/tensorflowlogs`
But tensorboar no work, and show the error as below:
c:\anaconda3\lib\site-packages\dask\dataframe\hashing.py:8: FutureWarning: The pandas.lib module is deprecated and will be removed in a future version. These are private functions and can be accessed from pandas._libs.lib instead
  from pandas.lib import is_bool_array
Traceback (most recent call last):
  File "c:\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda3\Scripts\tensorboard.exe\__main__.py", line 5, in <module>
  File "c:\anaconda3\lib\site-packages\tensorflow\tensorboard\tensorboard.py", line 33, in <module>
    from tensorflow.tensorboard.backend import application
  File "c:\anaconda3\lib\site-packages\tensorflow\tensorboard\backend\application.py", line 47, in <module>
    from tensorflow.tensorboard.plugins.projector import projector_plugin
  File "c:\anaconda3\lib\site-packages\tensorflow\tensorboard\plugins\projector\projector_plugin.py", line 28, in <module>
    from tensorflow.contrib.tensorboard.plugins.projector import PROJECTOR_FILENAME
  File "c:\anaconda3\lib\site-packages\tensorflow\contrib\__init__.py", line 30, in <module>
    from tensorflow.contrib import factorization
  File "c:\anaconda3\lib\site-packages\tensorflow\contrib\factorization\__init__.py", line 24, in <module>
    from tensorflow.contrib.factorization.python.ops.gmm import *
  File "c:\anaconda3\lib\site-packages\tensorflow\contrib\factorization\python\ops\gmm.py", line 27, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import estimator
  File "c:\anaconda3\lib\site-packages\tensorflow\contrib\learn\__init__.py", line 87, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "c:\anaconda3\lib\site-packages\tensorflow\contrib\learn\python\__init__.py", line 23, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "c:\anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\__init__.py", line 25, in <module>
    from tensorflow.contrib.learn.python.learn import estimators
  File "c:\anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\__init__.py", line 297, in <module>
    from tensorflow.contrib.learn.python.learn.estimators.dnn import DNNClassifier
  File "c:\anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\dnn.py", line 29, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import dnn_linear_combined
  File "c:\anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\dnn_linear_combined.py", line 31, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import estimator
  File "c:\anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\estimator.py", line 49, in <module>
    from tensorflow.contrib.learn.python.learn.learn_io import data_feeder
  File "c:\anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\learn_io\__init__.py", line 21, in <module>
    from tensorflow.contrib.learn.python.learn.learn_io.dask_io import extract_dask_data
  File "c:\anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\learn_io\dask_io.py", line 26, in <module>
    import dask.dataframe as dd
  File "c:\anaconda3\lib\site-packages\dask\dataframe\__init__.py", line 3, in <module>
    from .core import (DataFrame, Series, Index, _Frame, map_partitions,
  File "c:\anaconda3\lib\site-packages\dask\dataframe\core.py", line 40, in <module>
    pd.computation.expressions.set_use_numexpr(False)
AttributeError: module 'pandas' has no attribute 'computation'

C:\Users\Soars>tensorboard --logdir=/tmp/to/logs
c:\anaconda3\lib\site-packages\dask\dataframe\hashing.py:8: FutureWarning: The pandas.lib module is deprecated and will be removed in a future version. These are private functions and can be accessed from pandas._libs.lib instead
  from pandas.lib import is_bool_array
Traceback (most recent call last):
  File "c:\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda3\Scripts\tensorboard.exe\__main__.py", line 5, in <module>
  File "c:\anaconda3\lib\site-packages\tensorflow\tensorboard\tensorboard.py", line 33, in <module>
    from tensorflow.tensorboard.backend import application
  File "c:\anaconda3\lib\site-packages\tensorflow\tensorboard\backend\application.py", line 47, in <module>
    from tensorflow.tensorboard.plugins.projector import projector_plugin
  File "c:\anaconda3\lib\site-packages\tensorflow\tensorboard\plugins\projector\projector_plugin.py", line 28, in <module>
    from tensorflow.contrib.tensorboard.plugins.projector import PROJECTOR_FILENAME
  File "c:\anaconda3\lib\site-packages\tensorflow\contrib\__init__.py", line 30, in <module>
    from tensorflow.contrib import factorization
  File "c:\anaconda3\lib\site-packages\tensorflow\contrib\factorization\__init__.py", line 24, in <module>
    from tensorflow.contrib.factorization.python.ops.gmm import *
  File "c:\anaconda3\lib\site-packages\tensorflow\contrib\factorization\python\ops\gmm.py", line 27, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import estimator
  File "c:\anaconda3\lib\site-packages\tensorflow\contrib\learn\__init__.py", line 87, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "c:\anaconda3\lib\site-packages\tensorflow\contrib\learn\python\__init__.py", line 23, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "c:\anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\__init__.py", line 25, in <module>
    from tensorflow.contrib.learn.python.learn import estimators
  File "c:\anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\__init__.py", line 297, in <module>
    from tensorflow.contrib.learn.python.learn.estimators.dnn import DNNClassifier
  File "c:\anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\dnn.py", line 29, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import dnn_linear_combined
  File "c:\anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\dnn_linear_combined.py", line 31, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import estimator
  File "c:\anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\estimator.py", line 49, in <module>
    from tensorflow.contrib.learn.python.learn.learn_io import data_feeder
  File "c:\anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\learn_io\__init__.py", line 21, in <module>
    from tensorflow.contrib.learn.python.learn.learn_io.dask_io import extract_dask_data
  File "c:\anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\learn_io\dask_io.py", line 26, in <module>
    import dask.dataframe as dd
  File "c:\anaconda3\lib\site-packages\dask\dataframe\__init__.py", line 3, in <module>
    from .core import (DataFrame, Series, Index, _Frame, map_partitions,
  File "c:\anaconda3\lib\site-packages\dask\dataframe\core.py", line 40, in <module>
    pd.computation.expressions.set_use_numexpr(False)
AttributeError: module 'pandas' has no attribute 'computation'

What's wrong with me?

My environment:
OS: windows 10
IDE: Visual studio 2015
Package version:
1) tensorflow: .1.1.0
2) pandas: 0.20.1
3) matplotlib: 2.0.0
Please help me, thank you.

**Comment by soartseng** [comment]
I solved this problem.
Downgrade pandas version to 0.19.2, and it worked.
