### ISSUE TITLE
ZeroDivisionError: integer division or modulo by zero

### ISSUE THREAD

**Issue by datomnurdin** [tensorflow/tensorflow#10129]
I got this error messsage when trying to train the images. FYI my images is more than 20.

My command

```
sudo python retrain.py --bottleneck_dir=tf_files/bottlenecks --how_many_training_steps=500 --model_dir=tf_files/inception --output_graph=tf_files/retrained_graph.pb --output_labels=tf_files/retrained_labels.txt --image_dir /Users/ZERO/Documents/Github/tensorflow-python/tf_files/images/..
```

Error message

```
Looking for images in 'bottlenecks'
No files found
Looking for images in 'images'
Looking for images in 'inception'
WARNING: Folder has less than 20 images, which may cause issues.
Looking for images in 'images'
Looking for images in 'inception'
WARNING: Folder has less than 20 images, which may cause issues.
2017-05-23 13:00:12.940135: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-05-23 13:00:12.940170: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-05-23 13:00:12.940177: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-05-23 13:00:12.940184: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-05-23 13:00:12.940190: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
2017-05-23 13:00:21.462092: Step 0: Train accuracy = 100.0%
2017-05-23 13:00:21.462469: Step 0: Cross entropy = 0.427569
CRITICAL:tensorflow:Label inception has no images in the category validation.
Traceback (most recent call last):
  File "retrain.py", line 1107, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "retrain.py", line 910, in main
    bottleneck_tensor))
  File "retrain.py", line 515, in get_random_cached_bottlenecks
    image_dir, category)
  File "retrain.py", line 227, in get_image_path
    mod_index = index % len(category_list)
ZeroDivisionError: integer division or modulo by zero
```

![screenshot 2017-05-23 13 39 48](https://cloud.githubusercontent.com/assets/5416242/26339821/52177d42-3fbd-11e7-88a2-17e6df781d52.png)

Please advice. Thank you.

**Comment by shitian-ni** [comment]
`CRITICAL:tensorflow:Label inception has no images in the category validation.` 
and warning says you need more images in inception.
So instead of "images" folder, can you share what's in "inception" folder?

**Comment by datomnurdin** [comment]
Here is the inception folder.

![screenshot 2017-05-23 15 18 47](https://cloud.githubusercontent.com/assets/5416242/26342595/56176534-3fcb-11e7-8a50-f7bdda4eb3e7.png)

**Comment by shitian-ni** [comment]
See if this link helps
https://stackoverflow.com/questions/41542706/tensorflow-label-inception-has-no-images-in-the-category-training?rq=1

**Comment by jart** [comment]
Thank you for supporting our friend @shitian-ni.

**Comment by shitian-ni** [comment]
@jart You are welcome.

@datomnurdin I think the actual error reason is in your command argument `--image_dir /Users/ZERO/Documents/Github/tensorflow-python/tf_files/images/..`.
The `..` in the end means the parent folder of images folder. So it also find images in folder bottlenecks and inception.
You should delete `..` from the argument.
Another point is that I think you should put images in folder "images" in subfolders with folder name as category names

**Comment by datomnurdin** [comment]
@shitian-ni The problem still occur even I already put more than 2++ images. Still generate this error message

```
2017-05-27 19:52:29.487781: Step 0: Train accuracy = 100.0%
2017-05-27 19:52:29.489798: Step 0: Cross entropy = 0.440165
CRITICAL:tensorflow:Label inception has no images in the category validation.
Traceback (most recent call last):
  File "retrain.py", line 1107, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "retrain.py", line 910, in main
    bottleneck_tensor))
  File "retrain.py", line 515, in get_random_cached_bottlenecks
    image_dir, category)
  File "retrain.py", line 227, in get_image_path
    mod_index = index % len(category_list)
ZeroDivisionError: integer division or modulo by zero
```

Please advice.

**Comment by shitian-ni** [comment]
Did you remove `..` from `--image_dir ` argument?

**Comment by datomnurdin** [comment]
@shitian-ni yeah, its fixed. worked now. thanks.

**Comment by wider2** [comment]
good day for datomnurdin 
finally... can you write the working list of params?
because I have the same problem with the "Label inception has no images in the category validation"

**Comment by sachaanu** [comment]
Hello datomnurdin ,

Can you please highlight what worked, Im facing same issue.

Thank You

**Comment by sachaanu** [comment]
It worked, pls ignore.

Thanks

**Comment by get2abhi** [comment]
Instead of using 

`--image_dir=fruits`

use 

`--image_dir=./fruits`
