### ISSUE TITLE
Support python3 on Docker image tensorflow/tensorflow:latest

### ISSUE THREAD

**Issue by campoy** [tensorflow/tensorflow#10179]
### System information

I'm running the `tensorflow/tensorflow:latest` Docker image

```bash
$ docker run -it --rm tensorflow/tensorflow python3
Python 3.5.2 (default, Nov 17 2016, 17:05:23)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'tensorflow'
```

Note that the same works perfectly for Python 2:

```bash
✗ docker run -it --rm tensorflow/tensorflow python
Python 2.7.12 (default, Nov 19 2016, 06:48:10)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
>>>
```

### Describe the problem

Importing tensorflow from python3 fails for the tensorflow/tensorflow Docker image
This is surprising because python3 itself is installed, so the solution is:

a) make tensorflow be importable from python3
b) remote python3 so it's obvious you need to use a different tag (point at it, maybe)

**Comment by campoy** [comment]
I understand there is a different tag, but this is confusing no matter how much you document it.

Why isn't tensorflow supported for Python3 on `latest`?
If it's for image size concerns, shouldn't we also remove `python3` completely from `latest`?

Thanks

**Comment by jart** [comment]
@gunan our friend wants to know why the `python3` command exists on our docker tag `latest` if you need to install `latest-py3` for it to work.

**Comment by gunan** [comment]
The reason not having both py3 and py2 TF installed on latest is exactly image size.
I think having python3 installed on latest is simply an oversight.
@caisq maybe we missed some of the image size optimizations?

**Comment by ruthyaneth** [comment]
Aqui esta como instalar python, docker, tensorflow, virtualbox
https://youtu.be/OiPjSnKAmSI

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assigneee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by developius** [comment]
Hey I've got a problem relating to this. When I run `tensorflow/tensorflow` and invoke `python`, the tensorflow python module appears to not be installed. Am I missing something here?

```
$ docker image ls --no-trunc | grep tensorflow/tensorflow
REPOSITORY                         TAG                 IMAGE ID                                                                  CREATED             SIZE
tensorflow/tensorflow              latest              sha256:a2d1671e8a9373d617402e49124b78bf4c73ad9171d4cd4aaf272a035c4993d6   9 days ago          1.25GB

$ docker run --rm -ti tensorflow/tensorflow python
Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named tensorflow
```

**Comment by tensorflowbutler** [comment]
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by gunan** [comment]
@developius could you try:
```
docker pull tensorflow/tensorflow
docker run --rm -ti tensorflow/tensorflow python
```
The image works ok for me.

**Comment by developius** [comment]
That is really weird. The image checksums are the same yet the new one works.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @gunan: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @gunan: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by gunan** [comment]
One more data point.
It looks  like no matter which python version you try to use, bazel requires us to have python to be able to run any python program, because it inserts the shebang line "/usr/bin/env python".

This means on python2 image, we do not need python3, but on python3 image we need both python2 and python 3.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @gunan: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @gunan: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @gunan: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @gunan: It has been 63 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by gunan** [comment]
Reassigning to @angersson as he will work on restructuring some of our docker files.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @angersson: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @angersson: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @angersson: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @angersson: It has been 59 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by angersson** [comment]
This should go away when https://github.com/tensorflow/community/pull/8 gets implemented.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @angersson: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @angersson: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @angersson: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @angersson: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by angersson** [comment]
I don't think we're going to be changing anything in the current Dockerfiles for this, but anyone is welcome to make further changes to the Dockerfiles to improve documentation, etc.

@ddragosd We probably are limited to this version. See https://github.com/tensorflow/tensorflow/pull/23066.
