### ISSUE TITLE
[Tensorboard] AssertionError: Cannot find .runfiles directory for /usr/bin/tensorboard

### ISSUE THREAD

**Issue by FloThinksPi** [tensorflow/tensorflow#10189]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Fedora 25
- **PIP Version**: 9.0.1
- **Tensorboard Version**: 1.0.0a7

### Describe the problem
When installing Tensorboard with pip, it is not executeable and producing following error.
I could reproduce this on my laptop and Tower both running Fedora 25.
Is there some issue with the tensorboard whl?

### Install

```
$ sudo pip3 install tensorboard
Collecting tensorboard
  Using cached tensorboard-1.0.0a7-cp35-cp35m-manylinux1_x86_64.whl
Requirement already satisfied: protobuf>=3.1.0 in /usr/lib64/python3.5/site-packages (from tensorboard)
Requirement already satisfied: six>=1.10.0 in /usr/lib/python3.5/site-packages (from tensorboard)
Requirement already satisfied: Pillow>=4.0.0 in /usr/lib64/python3.5/site-packages (from tensorboard)
Requirement already satisfied: numpy>=1.11.0 in /usr/lib64/python3.5/site-packages (from tensorboard)
Requirement already satisfied: wheel>=0.26 in /usr/lib/python3.5/site-packages (from tensorboard)
Requirement already satisfied: werkzeug>=0.11.10 in /usr/lib64/python3.5/site-packages (from tensorboard)
Requirement already satisfied: setuptools in /usr/lib/python3.5/site-packages (from protobuf>=3.1.0->tensorboard)
Requirement already satisfied: olefile in /usr/lib/python3.5/site-packages (from Pillow>=4.0.0->tensorboard)
Requirement already satisfied: packaging>=16.8 in /usr/lib/python3.5/site-packages (from setuptools->protobuf>=3.1.0->tensorboard)
Requirement already satisfied: appdirs>=1.4.0 in /usr/lib/python3.5/site-packages (from setuptools->protobuf>=3.1.0->tensorboard)
Requirement already satisfied: pyparsing in /usr/lib/python3.5/site-packages (from packaging>=16.8->setuptools->protobuf>=3.1.0->tensorboard)
Installing collected packages: tensorboard
Successfully installed tensorboard-1.0.0a7
```

### Starting tensorboard

Starting by just running ```tesorboard``` in terminal:

```
Traceback (most recent call last):
  File "/usr/bin/tensorboard", line 160, in <module>
    Main()
  File "/usr/bin/tensorboard", line 110, in Main
    module_space = FindModuleSpace()
  File "/usr/bin/tensorboard", line 91, in FindModuleSpace
    sys.argv[0])
AssertionError: Cannot find .runfiles directory for /usr/bin/tensorboard
```

**Comment by Androbin** [comment]
Similar issues with `freeze_graph`

**Comment by lvzhaoyang** [comment]
Same issue with pip version 9.0.1, with the same Tensorboard Version .

**Comment by jart** [comment]
Please do not `pip install tensorboard`. We didn't create that package. TensorBoard comes included with `pip install tensorflow`.

**Comment by Amitayus** [comment]
@jart But how could I update/reinstall the tensorboard. I have uninstall tensorboard just now.

**Comment by jart** [comment]
You can `pip install tensorflow-tensorboard` or `pip install tb-nightly`.
