### ISSUE TITLE
tf.nn.dynamic_rnn seems not working when given sequence_length

### ISSUE THREAD

**Issue by czy941030** [tensorflow/tensorflow#10183]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04.1
- **TensorFlow installed from (source or binary)**: pip
- **TensorFlow version (use command below)**: 1.2.0rc0
- **CUDA/cuDNN version**: CUDA: 8.0 cuDNN: 5.1
- **GPU model and memory**: GTX 1080 8GB

### Describe the problem
I tried to migrate my code from tensorflow r1.1.0 to tensorflow r1.2.0rc0.
When using tf.nn.dynamic_rnn, if sequence_length is not None, It got an error(traceback pasted below).
However, if I set sequence_length to None, it works properly as before.
Is this a bug or I got something wrong?

### Source code / logs
Source code:
``` python
tf.nn.dynamic_rnn(
    cell,
    inputs,
    dtype=tf.float32,
    sequence_length=lens)
```
where lens is a Tensor:
```
Tensor("Gather_DequeueMany:0", shape=(256,), dtype=int32)
```

Traceback:
```
Traceback (most recent call last):
  File "/home/carbon/py3-tensorflow-1.2/lib/python3.5/site-packages/tensorflow/python/framework/common_shapes.py", line 671, in _call_cpp_shape_fn_impl
    input_tensors_as_shapes, status)
  File "/usr/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/home/carbon/py3-tensorflow-1.2/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Shapes must be equal rank, but are 0 and 1 for 'rnn/while/Select_4' (op: 'Select') with input shapes: [256], [], [].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 74, in <module>
    tf.app.run()
  File "/home/carbon/py3-tensorflow-1.2/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "main.py", line 70, in main
    trainer = ModelTrainer(config)
  File "/home/carbon/Codes/seq2seqmapmatching/model_trainer.py", line 25, in __init__
    self.model.construct(self.train_reader.queue, self.valid_reader.queue, self.global_step)
  File "/home/carbon/Codes/seq2seqmapmatching/seq2seq_model.py", line 35, in construct
    global_step=global_step)
  File "/home/carbon/Codes/seq2seqmapmatching/seq2seq_model.py", line 118, in build_model
    outputs, decoder_state = self.build_decoder(encoder_outputs, inputs, per_h, lens, pts_lens)
  File "/home/carbon/Codes/seq2seqmapmatching/seq2seq_model.py", line 185, in build_decoder
    sequence_length=lens)
  File "/home/carbon/py3-tensorflow-1.2/lib/python3.5/site-packages/tensorflow/python/ops/rnn.py", line 566, in dynamic_rnn
    dtype=dtype)
  File "/home/carbon/py3-tensorflow-1.2/lib/python3.5/site-packages/tensorflow/python/ops/rnn.py", line 729, in _dynamic_rnn_loop
    swap_memory=swap_memory)
  File "/home/carbon/py3-tensorflow-1.2/lib/python3.5/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2766, in while_loop
    result = context.BuildLoop(cond, body, loop_vars, shape_invariants)
  File "/home/carbon/py3-tensorflow-1.2/lib/python3.5/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2595, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/home/carbon/py3-tensorflow-1.2/lib/python3.5/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2545, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/home/carbon/py3-tensorflow-1.2/lib/python3.5/site-packages/tensorflow/python/ops/rnn.py", line 712, in _time_step
    skip_conditionals=True)
  File "/home/carbon/py3-tensorflow-1.2/lib/python3.5/site-packages/tensorflow/python/ops/rnn.py", line 202, in _rnn_step
    final_output_and_state = _copy_some_through(new_output, new_state)
  File "/home/carbon/py3-tensorflow-1.2/lib/python3.5/site-packages/tensorflow/python/ops/rnn.py", line 174, in _copy_some_through
    for state, new_state in zip(flat_state, flat_new_state)]
  File "/home/carbon/py3-tensorflow-1.2/lib/python3.5/site-packages/tensorflow/python/ops/rnn.py", line 174, in <listcomp>
    for state, new_state in zip(flat_state, flat_new_state)]
  File "/home/carbon/py3-tensorflow-1.2/lib/python3.5/site-packages/tensorflow/python/ops/rnn.py", line 163, in _copy_one_through
    return array_ops.where(copy_cond, output, new_output)
  File "/home/carbon/py3-tensorflow-1.2/lib/python3.5/site-packages/tensorflow/python/ops/array_ops.py", line 2328, in where
    return gen_math_ops._select(condition=condition, t=x, e=y, name=name)
  File "/home/carbon/py3-tensorflow-1.2/lib/python3.5/site-packages/tensorflow/python/ops/gen_math_ops.py", line 2145, in _select
    name=name)
  File "/home/carbon/py3-tensorflow-1.2/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/home/carbon/py3-tensorflow-1.2/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2508, in create_op
    set_shapes_for_outputs(ret)
  File "/home/carbon/py3-tensorflow-1.2/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1873, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/home/carbon/py3-tensorflow-1.2/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1823, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/home/carbon/py3-tensorflow-1.2/lib/python3.5/site-packages/tensorflow/python/framework/common_shapes.py", line 610, in call_cpp_shape_fn
    debug_python_shape_fn, require_shape_fn)
  File "/home/carbon/py3-tensorflow-1.2/lib/python3.5/site-packages/tensorflow/python/framework/common_shapes.py", line 676, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Shapes must be equal rank, but are 0 and 1 for 'rnn/while/Select_4' (op: 'Select') with input shapes: [256], [], [].
```

**Comment by jart** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
