### ISSUE TITLE
Error on importing metagraph that uses unbound input multiple times

### ISSUE THREAD

**Issue by freitmi** [tensorflow/tensorflow#10250]
If I export a scoped metagraph which has multiple references to a tensor which will be unbound after exporting, I cannot re-import the metagraph. This problem can be reproduced with the following MWE.

```python
import tensorflow as tf

graph = tf.Graph()

with graph.as_default():
    inputs = tf.placeholder(shape=[], dtype=tf.float32, name="inputs")

    with tf.name_scope("scope"):
        output = inputs + inputs

    tf.train.export_meta_graph("./mwe.meta",
                               export_scope="scope",
                               as_text=True)

graph = tf.Graph()

with graph.as_default():
    inputs = tf.constant(shape=[], value=1.0)

    tf.train.import_meta_graph("./mwe.meta",
                               import_scope="scope",
                               input_map={
                                   "$unbound_inputs_inputs": inputs
                               })

```
Running this code results in the following error.
```
Traceback (most recent call last):
  File "<snip>\metagraph_bug_mwe.py", line 23, in <module>
    "$unbound_inputs_inputs": inputs
  File "<snip>\Python35\lib\site-packages\tensorflow\python\training\saver.py", line 1595, in import_meta_graph
    **kwargs)
  File "<snip>\Python35\lib\site-packages\tensorflow\python\framework\meta_graph.py", line 479, in import_scoped_meta_graph
    ",".join([compat.as_str(v) for v in field.value
ValueError: Graph contains unbound inputs: $unbound_inputs_inputs,$unbound_inputs_inputs. Must provide these inputs through input_map.
```
Upon inspection of the generated metagraph file (see [mwe.meta](https://github.com/tensorflow/tensorflow/files/1033570/mwe.meta.txt), lines 67 - 75), I noticed that the `inputs` tensor actually has two entries in the `unbound_inputs` collection. Since the `import_scoped_meta_graph` function compares the full collection read from the proto to the `input_map` parameter, they do not match and the error is raised.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes, see above
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.1.0
- **Bazel version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: 8.0/5.1.10
- **GPU model and memory**: Nvidia GeForce GTX 860M with 2GB VRAM + 4GB shared
- **Exact command to reproduce**: See MWE above

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by michaelisard** [comment]
Is this still an issue?

**Comment by freitmi** [comment]
Yes, the MWE provided above still breaks with the same exception in 1.4.

**Comment by tensorflowbutler** [comment]
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
The original poster has replied to this issue after the stat:awaiting response label was applied.

**Comment by drpngx** [comment]
Looks like this is not expected behavior. Are you in a position to send a fix?

**Comment by freitmi** [comment]
I am currently working on a PR to fix this issue

**Comment by crisnv** [comment]
Any news on this topic?
I am getting a list of unbound inputs:
if not input_map or v not in input_map]))
ValueError: Graph contains unbound inputs: $unbound_inputs_tower_0/IteratorGetNext,$unbound_inputs_cnn/conv_1/kernel/read,$unbound_inputs_cnn/conv_1/bias/read,$unbound_inputs_cnn/conv_2/kernel/read,$unbound_inputs_cnn/conv_2/bias/read,$unbound_inputs_linear_layer/linear_cnn/kernel/read,$unbound_inputs_linear_layer/linear_cnn/bias/read,$unbound_inputs_tower_0/seq_real_size_slice,$unbound_inputs_lstm/rnn/multi_rnn_cell/cell_0/lstm_cell_0/kernel/read,$unbound_inputs_lstm/rnn/multi_rnn_cell/cell_0/lstm_cell_0/bias/read,$unbound_inputs_lstm/rnn/multi_rnn_cell/cell_0/lstm_cell_0/projection/kernel/read,$unbound_inputs_lstm/rnn/multi_rnn_cell/cell_1/lstm_cell_1/kernel/read,$unbound_inputs_lstm/rnn/multi_rnn_cell/cell_1/lstm_cell_1/bias/read,$unbound_inputs_lstm/rnn/multi_rnn_cell/cell_1/lstm_cell_1/projection/kernel/read,$unbound_inputs_fully_connected/fc_1/kernel/read,$unbound_inputs_fully_connected/fc_1/bias/read,$unbound_inputs_fully_connected/fc_2/kernel/read,$unbound_inputs_fully_connected/fc_2/bias/read,$unbound_inputs_fully_connected/output_layer/kernel/read,$unbound_inputs_fully_connected/output_layer/bias/read. Must provide these inputs through input_map.
