### ISSUE TITLE
Android demo app crash on x86 device(libavcodec.so text relocations)

### ISSUE THREAD

**Issue by osdamv** [tensorflow/tensorflow#10277]
The app start then,  complain about libavcodec.so text relocations
![screenshot_20170529-122626](https://cloud.githubusercontent.com/assets/4120796/26559275/f5468b90-446b-11e7-85bb-fb1eadcbf691.png)
here is the log:

`05-29 12:33:36.787 12014-12014/org.tensorflow.demo E/WindowManager: android.view.WindowLeaked: Activity org.tensorflow.demo.ClassifierActivity has leaked window DecorView@34ca6d3[] that was originally added here
                                                                        at android.view.ViewRootImpl.<init>(ViewRootImpl.java:418)
                                                                        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:331)
                                                                        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:94)
                                                                        at android.app.Dialog.show(Dialog.java:329)
                                                                        at android.app.AlertDialog$Builder.show(AlertDialog.java:1112)
                                                                        at android.app.Activity.performStart(Activity.java:6723)
                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2662)
                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2766)
                                                                        at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1507)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                        at android.os.Looper.loop(Looper.java:154)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6236)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
05-29 12:33:36.864 12014-12014/org.tensorflow.demo E/Surface: dequeueBuffer failed (No such device)
05-29 12:33:36.865 12014-12014/org.tensorflow.demo E/ViewRootImpl[ClassifierActivity]: Could not lock surface
                                                                                       java.lang.IllegalArgumentException
                                                                                           at android.view.Surface.nativeLockCanvas(Native Method)
                                                                                           at android.view.Surface.lockCanvas(Surface.java:310)
                                                                                           at android.view.ViewRootImpl.drawSoftware(ViewRootImpl.java:2853)
                                                                                           at android.view.ViewRootImpl.draw(ViewRootImpl.java:2827)
                                                                                           at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2608)
                                                                                           at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2215)
                                                                                           at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
                                                                                           at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6344)
                                                                                           at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
                                                                                           at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                                                           at android.view.Choreographer.doFrame(Choreographer.java:621)
                                                                                           at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                                                                                           at android.os.Handler.handleCallback(Handler.java:751)
                                                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                           at android.os.Looper.loop(Looper.java:154)
                                                                                           at android.app.ActivityThread.main(ActivityThread.java:6236)
                                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
                                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
`

The device is an Zenfone 2 with an intel atom processor, is it supported?

**Comment by andrewharp** [comment]
Haven't seen that one. The demo definitely should work on x86, so long as you have a build x86 native libs in it (though libavcodec isn't one of those). Where did you get the demo from? If built it yourself, does the [prebuilt APK](https://ci.tensorflow.org/view/Nightly/job/nightly-android/lastSuccessfulBuild/artifact/out/tensorflow_demo.apk), which does contain x86 libs, work?

There may be an error farther up in the log that is the direct cause. Window leaks tend to happen after something else has broken.

**Comment by osdamv** [comment]
The apk is built by myself, however the prebuilt apk also crash 
but it throws a different stack trace:
`05-30 08:50:18.841 12116-12611/org.tensorflow.demo W/LegacyRequestMapper: convertRequestMetadata - control.awbRegions setting is not supported, ignoring value
05-30 08:50:18.841 12116-12611/org.tensorflow.demo W/LegacyRequestMapper: Only received metering rectangles with weight 0.
05-30 08:50:18.841 12116-12611/org.tensorflow.demo W/LegacyRequestMapper: Only received metering rectangles with weight 0.
05-30 08:50:19.113 12116-12612/org.tensorflow.demo I/CameraDeviceState: Legacy camera service transitioning to state CAPTURING
05-30 08:50:19.227 12116-12612/org.tensorflow.demo E/BufferQueueProducer: [ImageReader-640x480f23m2-12116-1] dequeueBuffer: createGraphicBuffer failed
05-30 08:50:19.227 12116-12612/org.tensorflow.demo E/Legacy-CameraDevice-JNI: LegacyCameraDevice_nativeProduceFrame: Error while producing frame Out of memory (-12).
05-30 08:50:19.228 12116-12612/org.tensorflow.demo E/CameraDeviceGLThread-0: Received exception on GL render thread: 
                                                                             java.lang.UnsupportedOperationException: Unknown error -12
                                                                                 at android.hardware.camera2.legacy.LegacyExceptionUtils.throwOnError(LegacyExceptionUtils.java:77)
                                                                                 at android.hardware.camera2.legacy.LegacyCameraDevice.produceFrame(LegacyCameraDevice.java:683)
                                                                                 at android.hardware.camera2.legacy.SurfaceTextureRenderer.drawIntoSurfaces(SurfaceTextureRenderer.java:775)
                                                                                 at android.hardware.camera2.legacy.GLThreadManager$1.handleMessage(GLThreadManager.java:105)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                 at android.os.Looper.loop(Looper.java:154)
                                                                                 at android.os.HandlerThread.run(HandlerThread.java:61)
05-30 08:50:19.228 12116-12612/org.tensorflow.demo I/CameraDeviceState: Legacy camera service transitioning to state ERROR
05-30 08:50:22.972 12116-12611/org.tensorflow.demo E/RequestThread-0: Timed out while waiting for request to complete.
05-30 08:50:22.972 12116-12611/org.tensorflow.demo E/CameraDeviceState: Cannot receive result while in state: 0
05-30 08:50:22.972 12116-12611/org.tensorflow.demo E/CameraDeviceState: Cannot receive result while in state: 0
05-30 08:50:23.003 12116-12611/org.tensorflow.demo E/CameraDeviceState: Cannot receive result while in state: 0
05-30 08:50:23.030 12116-12612/org.tensorflow.demo W/MessageQueue: Handler (android.os.Handler) {f15b46} sending message to a Handler on a dead thread
                                                                   java.lang.IllegalStateException: Handler (android.os.Handler) {f15b46} sending message to a Handler on a dead thread
                                                                       at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)
                                                                       at android.os.Handler.enqueueMessage(Handler.java:643)
                                                                       at android.os.Handler.sendMessageAtTime(Handler.java:612)
                                                                       at android.os.Handler.sendMessageDelayed(Handler.java:582)
                                                                       at android.os.Handler.sendMessage(Handler.java:519)
                                                                       at android.hardware.camera2.legacy.GLThreadManager.queueNewFrame(GLThreadManager.java:197)
                                                                       at android.hardware.camera2.legacy.RequestThreadManager$4.onFrameAvailable(RequestThreadManager.java:266)
                                                                       at android.graphics.SurfaceTexture$1.handleMessage(SurfaceTexture.java:207)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:154)
                                                                       at android.os.HandlerThread.run(HandlerThread.java:61)
05-30 08:50:23.078 12116-12129/org.tensorflow.demo E/BufferQueueProducer: [SurfaceTexture-1-12116-3] dequeueBuffer: BufferQueue has been abandoned
05-30 08:50:23.078 12116-12128/org.tensorflow.demo E/BufferQueueProducer: [SurfaceTexture-1-12116-3] dequeueBuffer: BufferQueue has been abandoned
05-30 08:50:23.079 12116-12140/org.tensorflow.demo E/BufferQueueProducer: [SurfaceTexture-1-12116-3] dequeueBuffer: BufferQueue has been abandoned
05-30 08:50:24.050 12116-12116/org.tensorflow.demo D/tensorflow: CameraActivity: onPause org.tensorflow.demo.ClassifierActivity@8d34417
05-30 08:50:24.689 12116-12116/org.tensorflow.demo D/tensorflow: CameraActivity: onStop org.tensorflow.demo.ClassifierActivity@8d34417
05-30 08:50:24.691 12116-12116/org.tensorflow.demo D/tensorflow: CameraActivity: onDestroy org.tensorflow.demo.ClassifierActivity@8d34417
`

**Comment by andrewharp** [comment]
This may be a camera2 API problem. It wouldn't surprise me if an x86 device like the Xenfone 2 has issues with it.

There's an outstanding PR #8736 to add a fallback to the original camera 1 API on problematic devices -- you might try syncing to that branch and see if it addresses your problem. If it does then we'd like to get it merged, there's just a little bit more refactoring that needs to be done if you have time to fix it up.

**Comment by osdamv** [comment]
I gonna give it a shot!! thank you very much !!

**Comment by joshua-xia** [comment]
is this issue solved? I am willing to look into it if it is still not fixed.

**Comment by osdamv** [comment]
is at review #10771

**Comment by wt-huang** [comment]
Closing as this is resolved
