### ISSUE TITLE
Cannot bazel build tensorflow pip package from source (/usr/bin/env: 'python': No such file or directory)

### ISSUE THREAD

**Issue by fferroni** [tensorflow/tensorflow#10289]
------------------------
### System information
- OS Platform and Distribution: Linux Ubuntu 16.04
- CUDA Toolkit v8.0
- cuDNN 5
- gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
- Bazel 0.5.0 (from repo)
- Anaconda Python 3.6
```
francesco@gpu-box:~/tensorflow$ python
Python 3.6.0 |Anaconda custom (64-bit)| (default, Dec 23 2016, 12:22:00) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

------------------------

Hello,

I am trying to build tensor flow pip package from source. I can install and use tensorflow with GPU using a precompiled binary just fine. However, in this case, I need to build from source.

Here is the following steps I take:
1. git clone https://github.com/tensorflow/tensorflow.git
2. cd tensorflow
3. ./configure

```
francesco@gpu-box:~/tensorflow$ ./configure 
Please specify the location of python. [Default is /home/francesco/anaconda3/bin/python]: 
Found possible Python library paths:
  /home/francesco/anaconda3/lib/python3.6/site-packages/
  /home/francesco/anaconda3/lib/python3.6/site-packages
Please input the desired Python library path to use.  Default is [/home/francesco/anaconda3/lib/python3.6/site-packages/]

Using python library path: /home/francesco/anaconda3/lib/python3.6/site-packages/
Do you wish to build TensorFlow with MKL support? [y/N] n
No MKL support will be enabled for TensorFlow
Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native]: 
Do you wish to use jemalloc as the malloc implementation? [Y/n] y
jemalloc enabled
Do you wish to build TensorFlow with Google Cloud Platform support? [y/N] n
No Google Cloud Platform support will be enabled for TensorFlow
Do you wish to build TensorFlow with Hadoop File System support? [y/N] n
No Hadoop File System support will be enabled for TensorFlow
Do you wish to build TensorFlow with the XLA just-in-time compiler (experimental)? [y/N] n
No XLA JIT support will be enabled for TensorFlow
Do you wish to build TensorFlow with VERBS support? [y/N] n
No VERBS support will be enabled for TensorFlow
Do you wish to build TensorFlow with OpenCL support? [y/N] n
No OpenCL support will be enabled for TensorFlow
Do you wish to build TensorFlow with CUDA support? [y/N] y
CUDA support will be enabled for TensorFlow
Do you want to use clang as CUDA compiler? [y/N] n
nvcc will be used as CUDA compiler
Please specify the CUDA SDK version you want to use, e.g. 7.0. [Leave empty to use system default]: 8.0
Please specify the location where CUDA 8.0 toolkit is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: 
Please specify which gcc should be used by nvcc as the host compiler. [Default is /usr/bin/gcc]: 
Please specify the cuDNN version you want to use. [Leave empty to use system default]: 5
Please specify the location where cuDNN 5 library is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: 
Please specify a list of comma-separated Cuda compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
Please note that each additional compute capability significantly increases your build time and binary size.
[Default is: "3.5,5.2"]: 6.1
Do you wish to build TensorFlow with MPI support? [y/N] n
MPI support will not be enabled for TensorFlow
INFO: Starting clean (this may take a while). Consider using --async if the clean takes more than several minutes.
Configuration finished

```

Unfortunately, when I then build with bazel, it runs into an error. It seems like it cannot find python?

```
francesco@gpu-box:~/tensorflow$ bazel build -c opt --verbose_failures --config=cuda //tensorflow/tools/pip_package:build_pip_package
WARNING: /home/francesco/tensorflow/tensorflow/contrib/learn/BUILD:15:1: in py_library rule //tensorflow/contrib/learn:learn: target '//tensorflow/contrib/learn:learn' depends on deprecated target '//tensorflow/contrib/session_bundle:exporter': Use SavedModel Builder instead.
WARNING: /home/francesco/tensorflow/tensorflow/contrib/learn/BUILD:15:1: in py_library rule //tensorflow/contrib/learn:learn: target '//tensorflow/contrib/learn:learn' depends on deprecated target '//tensorflow/contrib/session_bundle:gc': Use SavedModel instead.
INFO: Found 1 target...
INFO: From Compiling external/snappy/snappy-sinksource.cc [for host]:
cc1plus: warning: command line option '-Wno-implicit-function-declaration' is valid for C/ObjC but not for C++
cc1plus: warning: unrecognized command line option '-Wno-shift-negative-value'
INFO: From Compiling external/snappy/snappy-c.cc [for host]:
cc1plus: warning: command line option '-Wno-implicit-function-declaration' is valid for C/ObjC but not for C++
cc1plus: warning: unrecognized command line option '-Wno-shift-negative-value'
INFO: From Compiling external/snappy/snappy-stubs-internal.cc [for host]:
cc1plus: warning: command line option '-Wno-implicit-function-declaration' is valid for C/ObjC but not for C++
cc1plus: warning: unrecognized command line option '-Wno-shift-negative-value'
INFO: From Compiling external/snappy/snappy.cc [for host]:
cc1plus: warning: command line option '-Wno-implicit-function-declaration' is valid for C/ObjC but not for C++
external/snappy/snappy.cc: In member function 'void snappy::SnappySinkAllocator::Flush(size_t)':
external/snappy/snappy.cc:1403:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int i = 0; i < blocks_.size(); ++i) {
                       ^
In file included from external/snappy/snappy-internal.h:34:0,
                 from external/snappy/snappy.cc:30:
external/snappy/snappy.cc: In instantiation of 'bool snappy::SnappyScatteredWriter<Allocator>::AppendFromSelf(size_t, size_t) [with Allocator = snappy::SnappySinkAllocator; size_t = long unsigned int]':
external/snappy/snappy.cc:715:13:   required from 'void snappy::SnappyDecompressor::DecompressAllTags(Writer*) [with Writer = snappy::SnappyScatteredWriter<snappy::SnappySinkAllocator>]'
external/snappy/snappy.cc:799:3:   required from 'bool snappy::InternalUncompressAllTags(snappy::SnappyDecompressor*, Writer*, snappy::uint32) [with Writer = snappy::SnappyScatteredWriter<snappy::SnappySinkAllocator>; snappy::uint32 = unsigned int]'
external/snappy/snappy.cc:1460:78:   required from here
external/snappy/snappy.cc:1316:34: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if (PREDICT_TRUE(offset - 1u < op_ptr_ - op_base_ && op_end <= op_limit_)) {
                                  ^
external/snappy/snappy-stubs-internal.h:80:25: note: in definition of macro 'PREDICT_TRUE'
 #define PREDICT_TRUE(x) x
                         ^
At global scope:
cc1plus: warning: unrecognized command line option '-Wno-shift-negative-value'
ERROR: /home/francesco/.cache/bazel/_bazel_francesco/7b3bdb053a374c3fec955b526c0e6446/external/highwayhash/BUILD.bazel:8:1: C++ compilation of rule '@highwayhash//:sip_hash' failed: crosstool_wrapper_driver_is_not_gcc failed: error executing command 
  (cd /home/francesco/.cache/bazel/_bazel_francesco/7b3bdb053a374c3fec955b526c0e6446/execroot/tensorflow && \
  exec env - \
    CUDA_TOOLKIT_PATH=/usr/local/cuda \
    CUDNN_INSTALL_PATH=/usr/local/cuda-8.0 \
    GCC_HOST_COMPILER_PATH=/usr/bin/gcc \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/home/francesco/anaconda3/bin/python \
    PYTHON_LIB_PATH=/home/francesco/anaconda3/lib/python3.6/site-packages/ \
    TF_CUDA_CLANG=0 \
    TF_CUDA_COMPUTE_CAPABILITIES=6.1 \
    TF_CUDA_VERSION=8.0 \
    TF_CUDNN_VERSION=5 \
    TF_NEED_CUDA=1 \
    TF_NEED_OPENCL=0 \
  external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections '-std=c++11' -MD -MF bazel-out/local_linux-py3-opt/bin/external/highwayhash/_objs/sip_hash/external/highwayhash/highwayhash/sip_hash.pic.d '-frandom-seed=bazel-out/local_linux-py3-opt/bin/external/highwayhash/_objs/sip_hash/external/highwayhash/highwayhash/sip_hash.pic.o' -fPIC -iquote external/highwayhash -iquote bazel-out/local_linux-py3-opt/genfiles/external/highwayhash -iquote external/bazel_tools -iquote bazel-out/local_linux-py3-opt/genfiles/external/bazel_tools -isystem external/bazel_tools/tools/cpp/gcc3 -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -fno-canonical-system-headers -c external/highwayhash/highwayhash/sip_hash.cc -o bazel-out/local_linux-py3-opt/bin/external/highwayhash/_objs/sip_hash/external/highwayhash/highwayhash/sip_hash.pic.o): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 127.
/usr/bin/env: 'python': No such file or directory
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 44.289s, Critical Path: 5.54s
```

Both my python_bin_path and python_lib_path are correct, so I do not understand.

Any advice?

Regards

**Comment by gunan** [comment]
I am pretty certain the cause is using anaconda python, instead of ubuntu python.
Is your python bin path included in your "path" environment variable?

**Comment by fferroni** [comment]
```
francesco@gpu-box:~$ env
SHELL=/bin/bash
LD_LIBRARY_PATH=/usr/local/cuda-8.0/lib64
PATH=/home/francesco/anaconda3/bin:/usr/local/cuda-8.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
PWD=/home/francesco
HOME=/home/francesco
_=/usr/bin/env
```

Yes it's included, AFAIK

**Comment by gunan** [comment]
@damienmg Could you help look into this?
highwayhash//:siphash seems to be a cc rule, but I am not sure why we see the failure here.
maybe there is some backwards incompatible change with bazel 0.5?

**Comment by damienmg** [comment]
Can you try with `--action_env PATH`?

**Comment by fferroni** [comment]
Nope.
Tried variations like `--action_env PATH`, `--action_env=PATH`, `--action_env=$PATH` to no avail.

**Comment by damienmg** [comment]
`--action_env PATH="$PATH"`?

**Comment by fferroni** [comment]
Hi,

That worked!

```
At global scope:
cc1plus: warning: unrecognized command line option '-Wno-self-assign'
Target //tensorflow/tools/pip_package:build_pip_package up-to-date:
  bazel-bin/tensorflow/tools/pip_package/build_pip_package
INFO: Elapsed time: 1238.673s, Critical Path: 133.18s
```

 However, I then build a wheel (still fine)

```
francesco@gpu-box:~/tensorflow$ bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg
mer 31 mag 2017, 18.48.47, CEST : === Using tmpdir: /tmp/tmp.D9nGwyy56D
~/tensorflow/bazel-bin/tensorflow/tools/pip_package/build_pip_package.runfiles ~/tensorflow
~/tensorflow
/tmp/tmp.D9nGwyy56D ~/tensorflow
mer 31 mag 2017, 18.48.48, CEST : === Building wheel
warning: no files found matching '*.dll' under directory '*'
warning: no files found matching '*.lib' under directory '*'
~/tensorflow
mer 31 mag 2017, 18.48.58, CEST : === Output wheel file is in: /tmp/tensorflow_pkg
```

I install the wheel tensorflow-1.2.0rc0-cp36-cp36m-linux_x86_64.whl

```
francesco@gpu-box:~/tensorflow$ pip install /tmp/tensorflow_pkg/tensorflow-1.2.0rc0-cp36-cp36m-linux_x86_64.whl
Processing /tmp/tensorflow_pkg/tensorflow-1.2.0rc0-cp36-cp36m-linux_x86_64.whl
Requirement already satisfied: six>=1.10.0 in /home/francesco/anaconda3/lib/python3.6/site-packages (from tensorflow==1.2.0rc0)
Collecting bleach==1.5.0 (from tensorflow==1.2.0rc0)
  Using cached bleach-1.5.0-py2.py3-none-any.whl
Requirement already satisfied: wheel>=0.26 in /home/francesco/anaconda3/lib/python3.6/site-packages (from tensorflow==1.2.0rc0)
Collecting markdown==2.2.0 (from tensorflow==1.2.0rc0)
  Downloading Markdown-2.2.0.tar.gz (236kB)
    100% |████████████████████████████████| 245kB 1.8MB/s 
Requirement already satisfied: werkzeug>=0.11.10 in /home/francesco/anaconda3/lib/python3.6/site-packages (from tensorflow==1.2.0rc0)
Requirement already satisfied: protobuf>=3.2.0 in /home/francesco/anaconda3/lib/python3.6/site-packages (from tensorflow==1.2.0rc0)
Requirement already satisfied: numpy>=1.11.0 in /home/francesco/anaconda3/lib/python3.6/site-packages (from tensorflow==1.2.0rc0)
Collecting html5lib==0.9999999 (from tensorflow==1.2.0rc0)
  Using cached html5lib-0.9999999.tar.gz
Requirement already satisfied: setuptools in /home/francesco/anaconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg (from protobuf>=3.2.0->tensorflow==1.2.0rc0)
Building wheels for collected packages: markdown, html5lib
  Running setup.py bdist_wheel for markdown ... done
  Stored in directory: /home/francesco/.cache/pip/wheels/b9/4f/6c/f4c1c5207c1d0eeaaf7005f7f736620c6ded6617c9d9b94096
  Running setup.py bdist_wheel for html5lib ... done
  Stored in directory: /home/francesco/.cache/pip/wheels/6f/85/6c/56b8e1292c6214c4eb73b9dda50f53e8e977bf65989373c962
Successfully built markdown html5lib
Installing collected packages: html5lib, bleach, markdown, tensorflow
Successfully installed bleach-1.5.0 html5lib-0.9999999 markdown-2.2.0 tensorflow-1.2.0rc0
```

but when I try to import tensorflow, it fails :(

```
francesco@gpu-box:~/tensorflow$ python
Python 3.6.0 |Anaconda custom (64-bit)| (default, Dec 23 2016, 12:22:00) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
Traceback (most recent call last):
  File "/home/francesco/tensorflow/tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
ModuleNotFoundError: No module named 'tensorflow.python.pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/francesco/tensorflow/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/home/francesco/tensorflow/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/francesco/tensorflow/tensorflow/python/pywrap_tensorflow.py", line 52, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/francesco/tensorflow/tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
ModuleNotFoundError: No module named 'tensorflow.python.pywrap_tensorflow_internal'


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

Is it an issue with the building process, or making the wheel, or installing the wheel?

**Comment by fferroni** [comment]
Hi,

That worked. Ran into another issue `ModuleNotFoundError: No module named 'tensorflow.python.pywrap_tensorflow_internal'`when importing the tensorflow in python, but that's only because I was running the shell in the git directory :)

Will close the issue.

**Comment by lefnire** [comment]
Got snagged by this too. Anaconda is very common, recommend adding a side-note of this flag in the installation instructions

**Comment by hsgkim** [comment]
I used bazel 0.21 for TF 1.13.1, and I had to add `--noincompatible_strict_action_env` as well.

**Comment by saippuakauppias** [comment]
@hsgkim , Thanks! Compiled TF with this command:
```bash
bazel build --config=opt --config=cuda --noincompatible_strict_action_env //tensorflow/tools/pip_package:build_pip_package
```

**Comment by deslum** [comment]
Ubuntu 20.04.

It's work for me

`sudo ln -s /usr/bin/python3 /usr/bin/python`

**Comment by MustafaLotfi** [comment]
> Ubuntu 20.04.
> 
> It's work for me
> 
> `sudo ln -s /usr/bin/python3 /usr/bin/python`

Thank you @deslum 
the command worked for me too.
ubuntu 21.04
