### ISSUE TITLE
docker tensorflow python - FileNotFoundError: [WinError 3] The system cannot find the path specified: ''

### ISSUE THREAD

**Issue by sharjeel7r** [tensorflow/tensorflow#10297]
getting below error while running following command on docker. kindly assist..

$ python retrain.py \
> --bottleneck_dir= tf_files/bottlenecks \
> --how_many_training_steps=500 \
> --model_dir=tf_files/inception \
> --summaries_dir=tf_files/training_summaries/basic \
> --output_graph=tf_files/retrained_graph.pb \
> --output_labels=tf_files/retrained_labels.txt \
> --image_dir=tf_files/images/
Looking for images in 'cat'
Looking for images in 'dog'

Traceback (most recent call last):
  File "retrain.py", line 1063, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "C:\Users\Sharjeel.Riaz\AppData\Local\Programs\Python\Python35\Lib\site-packages\tensorflow\python\platform\app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "retrain.py", line 809, in main
    jpeg_data_tensor, bottleneck_tensor)
  File "retrain.py", line 434, in cache_bottlenecks
    ensure_dir_exists(bottleneck_dir)
  File "retrain.py", line 316, in ensure_dir_exists
    os.makedirs(dir_name)
  File "C:\Users\Sharjeel.Riaz\AppData\Local\Programs\Python\Python35\lib\os.py", line 241, in makedirs
    mkdir(name, mode)
FileNotFoundError: [WinError 3] The system cannot find the path specified: ''

**Comment by asimshankar** [comment]
I apologize but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new) . Please provide all the information it asks. Thank you.
