### ISSUE TITLE
//tensorflow/tools/test:cast_op_benchmark  and //tensorflow/tools/test:rnn_op_benchmark tests are failing with KeyError: 'l2_cache_size' on ppc64le

### ISSUE THREAD

**Issue by sandipmgiri** [tensorflow/tensorflow#10371]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
      Ubuntu 16.04 (ppc64le)
- **TensorFlow installed from (source or binary)**:
     Installed from source (v1.0.1)
- **TensorFlow version (use command below)**:
     ('v1.0.1-0-ge895d5c-dirty', '1.0.1')
- **Bazel version (if compiling from source)**:
     0.4.4-2017-05-26 (@80a07b5)
- **CUDA/cuDNN version**:
     CUDA = 8.0 and cuDNN = 5.1
- **GPU model and memory**:
     GPU 0: Tesla P100-SXM2-16GB
     GPU 1: Tesla P100-SXM2-16GB
- **Exact command to reproduce**:
    bazel test --config=opt --config=cuda //tensorflow/tools/test:cast_op_benchmark 
                                                           or
    bazel test --config=opt --config=cuda //tensorflow/tools/test:rnn_op_benchmark

### Describe the problem
Both tests are passing on x86, however getting failure on ppc64le with following errors :

### Source code / logs
```
$   bazel test --config=opt --config=cuda //tensorflow/tools/test:rnn_op_benchmark

exec ${PAGER:-/usr/bin/less} "$0" || exit 1
-----------------------------------------------------------------------------
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
..
----------------------------------------------------------------------
Ran 2 tests in 0.008s

OK
Traceback (most recent call last):
  File "/home/amit/.cache/bazel/_bazel_amit/24cb277fcedebf1cf5a3d7b8e713f578/execroot/tensorflow/bazel-out/local_linux-opt/bin/tensorflow/tools/test/rnn_op_benchmark.runfiles/org_tensorflow/tensorflow/tools/test/run_and_gather_logs.py", line 99, in <module>
    app.run()
  File "/home/amit/.cache/bazel/_bazel_amit/24cb277fcedebf1cf5a3d7b8e713f578/execroot/tensorflow/bazel-out/local_linux-opt/bin/tensorflow/tools/test/rnn_op_benchmark.runfiles/org_tensorflow/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/amit/.cache/bazel/_bazel_amit/24cb277fcedebf1cf5a3d7b8e713f578/execroot/tensorflow/bazel-out/local_linux-opt/bin/tensorflow/tools/test/rnn_op_benchmark.runfiles/org_tensorflow/tensorflow/tools/test/run_and_gather_logs.py", line 78, in main
    test_args)
  File "/home/amit/.cache/bazel/_bazel_amit/24cb277fcedebf1cf5a3d7b8e713f578/execroot/tensorflow/bazel-out/local_linux-opt/bin/tensorflow/tools/test/rnn_op_benchmark.runfiles/org_tensorflow/tensorflow/tools/test/run_and_gather_logs_lib.py", line 145, in run_and_gather_logs
    log_files=log_files), mangled_test_name)
  File "/home/amit/.cache/bazel/_bazel_amit/24cb277fcedebf1cf5a3d7b8e713f578/execroot/tensorflow/bazel-out/local_linux-opt/bin/tensorflow/tools/test/rnn_op_benchmark.runfiles/org_tensorflow/tensorflow/tools/test/run_and_gather_logs_lib.py", line 76, in process_test_logs
    system_info_lib.gather_machine_configuration())
  File "/home/amit/.cache/bazel/_bazel_amit/24cb277fcedebf1cf5a3d7b8e713f578/execroot/tensorflow/bazel-out/local_linux-opt/bin/tensorflow/tools/test/rnn_op_benchmark.runfiles/org_tensorflow/tensorflow/tools/test/system_info_lib.py", line 44, in gather_machine_configuration
    config.cpu_info.CopyFrom(gather_cpu_info())
  File "/home/amit/.cache/bazel/_bazel_amit/24cb277fcedebf1cf5a3d7b8e713f578/execroot/tensorflow/bazel-out/local_linux-opt/bin/tensorflow/tools/test/rnn_op_benchmark.runfiles/org_tensorflow/tensorflow/tools/test/system_info_lib.py", line 98, in gather_cpu_info
    l2_cache_size = re.match(r'(\d+)', str(info['l2_cache_size']))
KeyError: 'l2_cache_size'

```

Any comments/suggestions ?

**Comment by asimshankar** [comment]
Seems like `l2_cache_size` does not exist in the CPU info returned on your platform.

Could you paste the output of the following (you may need to `pip install py-cpuinfo`):
```python
import cpuinfo
print(cpuinfo.get_cpu_info())
```

That will help determine how we can make the test get L2 cache information.
(Which would ultimately end up as a patch to https://github.com/tensorflow/tensorflow/blob/557c539/tensorflow/tools/test/system_info_lib.py#L99)

**Comment by sandipmgiri** [comment]
Hi @asimshankar,  getting following output 

`{'count': 160, 'hz_advertised': '4.0230 GHz', 'bits': 64, 'brand': 'POWER8NVL (raw), altivec supported', 'cpuinfo_version': (3, 2, 0), 'flags': ['dabr', 'dabrx', 'dsisr', 'fpu', 'lp', 'mmu', 'pp', 'rislb', 'run', 'slb', 'sprg3', 'ugr_in_dscr'], 'raw_arch_string': 'ppc64le', 'hz_actual_raw': (4023000000, 0), 'hz_actual': '4.0230 GHz', 'arch': 'PPC_64', 'hz_advertised_raw': (4023000000, 0)}
`

Thanks!

**Comment by asimshankar** [comment]
Alright, it seems that `l2_cache_size` is not something that is returned by `get_cpu_info()` on your platform. I'll send out a change to make `system_info_lib.py` resilient to this case.

**Comment by sandipmgiri** [comment]
Hi @asimshankar ,

Did you get chance to look into this ?

As per my point of view - It should not just assume that the l2_cache_size will be there:

```
  # Gather the rest
  info = cpuinfo.get_cpu_info()
  cpu_info.cpu_info = info['brand']
  cpu_info.num_cores = info['count']
  cpu_info.mhz_per_cpu = info['hz_advertised_raw'][0] / 1.0e6
  l2_cache_size = re.match(r'(\d+)', str(info['l2_cache_size']))
  if l2_cache_size:
    # If a value is returned, it's in KB
   cpu_info.cache_size['L2'] = int(l2_cache_size.group(0)) * 1024
```

It could be changed to something like:

```
  # Gather the rest
  info = cpuinfo.get_cpu_info()
  cpu_info.cpu_info = info.get('brand', None)
  cpu_info.num_cores = info.get('count', None)
  cpu_info.mhz_per_cpu = info.get('hz_advertised_raw', (0, 0))[0] / 1.0e6
  if 'l2_cache_size' in info:
      l2_cache_size = re.match(r'(\d+)', str(info['l2_cache_size'])) 
      cpu_info.cache_size['L2'] = int(l2_cache_size.group(0)) * 1024

```
I am not sure whether it is correct or not, please guide me to make changes in system_info_lib.py file to support this case.

**Comment by asimshankar** [comment]
@sandipmgiri : I did submit a change internally to fix this, similar to yours. We push our internal changes to Github typically once a day so PR #10440 should resolve this.
