### ISSUE TITLE
error， I use tensorboard with pandas error

### ISSUE THREAD

**Issue by catpanda** [tensorflow/tensorflow#10383]
hello , during this days I was learning use tensorflow to build NN, when I use the tensorboard .In my code I use:
`self.writer = tf.summary.FileWriter('./board', self.graph)`\
to create the board file. and use qurery ,and It successfully have a file called events.out.tfevents.1496363479.dyy there. the Iuse query :tensorboard --logdir=board
then I got the error info.
`panda@dyy:~/code/number_test$ tensorboard --logdir=board
Traceback (most recent call last):
  File "/home/panda/anaconda3/bin/tensorboard", line 7, in <module>
    from tensorflow.tensorboard.tensorboard import main
  File "/home/panda/anaconda3/lib/python3.6/site-packages/tensorflow/tensorboard/tensorboard.py", line 33, in <module>
    from tensorflow.tensorboard.backend import application
  File "/home/panda/anaconda3/lib/python3.6/site-packages/tensorflow/tensorboard/backend/application.py", line 47, in <module>
    from tensorflow.tensorboard.plugins.projector import projector_plugin
  File "/home/panda/anaconda3/lib/python3.6/site-packages/tensorflow/tensorboard/plugins/projector/projector_plugin.py", line 28, in <module>
    from tensorflow.contrib.tensorboard.plugins.projector import PROJECTOR_FILENAME
  File "/home/panda/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/__init__.py", line 30, in <module>
    from tensorflow.contrib import factorization
  File "/home/panda/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/factorization/__init__.py", line 24, in <module>
    from tensorflow.contrib.factorization.python.ops.gmm import *
  File "/home/panda/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/factorization/python/ops/gmm.py", line 27, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import estimator
  File "/home/panda/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/learn/__init__.py", line 87, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/home/panda/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/learn/python/__init__.py", line 23, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/home/panda/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/__init__.py", line 25, in <module>
    from tensorflow.contrib.learn.python.learn import estimators
  File "/home/panda/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/estimators/__init__.py", line 297, in <module>
    from tensorflow.contrib.learn.python.learn.estimators.dnn import DNNClassifier
  File "/home/panda/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/estimators/dnn.py", line 29, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import dnn_linear_combined
  File "/home/panda/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/estimators/dnn_linear_combined.py", line 31, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import estimator
  File "/home/panda/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 49, in <module>
    from tensorflow.contrib.learn.python.learn.learn_io import data_feeder
  File "/home/panda/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/learn_io/__init__.py", line 21, in <module>
    from tensorflow.contrib.learn.python.learn.learn_io.dask_io import extract_dask_data
  File "/home/panda/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/learn_io/dask_io.py", line 26, in <module>
    import dask.dataframe as dd
  File "/home/panda/anaconda3/lib/python3.6/site-packages/dask/dataframe/__init__.py", line 3, in <module>
    from .core import (DataFrame, Series, Index, _Frame, map_partitions,
  File "/home/panda/anaconda3/lib/python3.6/site-packages/dask/dataframe/core.py", line 38, in <module>
    pd.computation.expressions.set_use_numexpr(False)
AttributeError: module 'pandas' has no attribute 'computation'
`
my python is 3.5.2 (in anaconda 4.2.0 )and my tensorflow is 1.1, and the pandas is 0.20.1（at first it is 0.18.1,but the error was about pandas so I try to update it）,this is run in ubuntu 15 with x64。

**Comment by asimshankar** [comment]
Looking at the stacktrace, it seems that you might have a old `dask` version. The stacktrace is triggered by `/home/panda/anaconda3/lib/python3.6/site-packages/dask/dataframe/core.py`, line 38, which is trying to use `pd.computation`. It seems that in pandas 0.20.0 this was changed (this was fixed in dask 0.14.2 I think - https://github.com/dask/dask/commit/bab4942b4b9eab6862226c0da868389629ee074f)

Can you disable dask in your anaconda environment or update it and retry?

FWIW, dask is not required by TensorFlow, but if it is installed it tries to use it. It seems that the versions of dask and pandas installed on your system are not compatible.

**Comment by jart** [comment]
Closing due to inactivity. If you still believe there's a bug in TensorFlow or TensorBoard, let me know and I'll re-open.

**Comment by Hjung9** [comment]
By using `conda update dask`, I solved the problem. (windows10, python 3.5 (w/ Anaconda), tensorflow-gpu 1.2.1)

**Comment by surre** [comment]
Thanks! `conda update dask`  fixed it for me.
