### ISSUE TITLE
Transform_graph android error 

### ISSUE THREAD

**Issue by santle** [tensorflow/tensorflow#10458]
Hi,
One month back I generated my custom TF model (output_graph.pb ) using Tensor Flow 1.0.1. It was working fine after optimization it using optimize_for_interface.

Now I plan to reduce its size and improve execution speed, I downloaded Tensor Flow 1.2.0.  I used transform_graph as 
 bazel-bin/tensorflow/tools/graph_transforms/transform_graph \
--in_graph=./output_graph.pb \
--out_graph=./transformed_graph.pb \
--inputs='Mul' \
--outputs='final_result' \
--transforms='
  add_default_attributes
  strip_unused_nodes(type=float, shape="1,299,299,3")
  remove_nodes(op=Identity, op=CheckNumerics)
  fold_constants(ignore_errors=true)
  fold_batch_norms
  fold_old_batch_norms
  quantize_weights
  quantize_nodes
  strip_unused_nodes
  sort_by_execution_order'

I built the APK and ran on a Lenovo Yoga 3 tablet.
It generated a run time error:

W/native  (24951): op_kernel.cc:1165 Invalid argument: computed output size would be negative
E/TensorFlowInferenceInterface(24951): Failed to run TensorFlow inference with inputs:[Mul], outputs:[final_result]
--------- beginning of crash
E/AndroidRuntime(24951): FATAL EXCEPTION: inference
E/AndroidRuntime(24951): Process: org.tensorflow.demo, PID: 24951
E/AndroidRuntime(24951): java.lang.IllegalArgumentException: computed output size would be negative
E/AndroidRuntime(24951): 	 [[Node: pool_3/eightbit = QuantizedAvgPool[T=DT_QUINT8, ksize=[1, 8, 8, 1], padding="VALID", strides=[1, 1, 1, 1], _device="/job:localhost/replica:0/task:0/cpu:0"](mixed_10/join/eightbit, mixed_10/join/eightbit:1, mixed_10/join/eightbit:2)]]
E/AndroidRuntime(24951): 	at org.tensorflow.Session.run(Native Method)
E/AndroidRuntime(24951): 	at org.tensorflow.Session.access$100(Session.java:48)

In both the cases, the Bazel version is 0.4.5
Any help to solve this?

**Comment by santle** [comment]
I am waiting to see a reply.

**Comment by mandemeskel** [comment]
Running into the same error, by any chance did you change the `INPUT_SIZE`, `IMAGE_MEAN`, and `IMAGE_STD`?

**Comment by santle** [comment]
I changed the image size to IMAGE_SIZE = 299, IMAGE_MEAN = 128, IMAGE_STD = 128.
Now the crash disappeared but the results are biased towards one of two total classes.
This incorrect results appears in 1.0,1 version of transform_graph too.
Any help to rectify this bias?

**Comment by santle** [comment]
Spent a lot time to choose a Transform Graph function combination to reduce the size and run time of my custom graph. 
But no option works for me to do both using: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/graph_transforms/README.md
The most promising one was the above combination which I tried, but it generates incorrect results.
Could you recommend any Transform Graph combination that would reduce size as well as run time. Thanks.

**Comment by petewarden** [comment]
It's hard to tell what the underlying cause is here. Can you try removing some of the transforms to narrow it down to which one is causing your inaccuracies?

**Comment by santle** [comment]
"quantize_weights"
    "quantize_nodes" 
cause the inaccuracies. Keeping any of them cause incorrect results.
when I remove both of them, the results seems to be correct, but there is no performance gain in terms of size / run time.
Any suggestion to improve both? I used Lenovo Phab 2.

**Comment by santle** [comment]
@petewarden 
Hope the above information is sufficient for you to provide me a direction to make the optimization work.
If you need more information, I can provide you. Thanks.

**Comment by petewarden** [comment]
I recently added a change that may help in this case, though I'm not certain. I increased the threshold for how large a buffer needs to be before it's quantized, from 16 up to 1024. I also made it a configurable parameter:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/graph_transforms/quantize_weights.cc#L40

This isn't in a release yet, but if you build the latest TensorFlow from source you can give it a try.

**Comment by laconstratos** [comment]
you just need to rename the created txt file and paste it in the assets directory, the created txt file is not the same name as the default txt file, because that will result to incorrect output, both files "created.txt and default.txt" should be on the same directory on build.

**Comment by philipjan** [comment]
hello guys, currently experiencing on this. do u have any ideas?

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by petewarden** [comment]
I'm hoping this is now fixed, since there hasn't been activity on this for some time. Closing, but please reopen if you're still hitting this.

**Comment by sonu107** [comment]
@santle @petewarden 
Facing somewhat similar problem, same problem.
Any suggestion will be helpful.



```Invalid argument: Computed output size would be negative: -32 [input_size: 84, effective_filter_size: 117, stride: 1]
Invalid argument: Computed output size would be negative: -32 [input_size: 85, effective_filter_size: 118, stride: 1]
Computed output size would be negative: -32 [input_size: 86, effective_filter_size: 119, stride: 1]
Failed to run TensorFlow inference with inputs:[inputTensor, dropout_keep_prob], outputs:[output/softmax]
```
