### ISSUE TITLE
tfdbg error when stepping through a graph that uses tf.train.shuffle_batch

### ISSUE THREAD

**Issue by ed-alertedh** [tensorflow/tensorflow#10478]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 17.04
- **TensorFlow installed from (source or binary)**: Binary
- **TensorFlow version (use command below)**: v1.2.0-rc1-24-gce1d6ec 1.2.0-rc2
(I also got the same error with tf 1.1.0)
- **Bazel version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: CUDA 8.0, cuDNN 5.1
- **GPU model and memory**: Nvidia GTX 1060
- **Exact command to reproduce**:
The following code will start a tfdbg session. Inside this session, enter these commands to get the error:
tfdbg> invoke_stepper
tfdbg> s
tfdbg> s
tfdbg> s
```
import tensorflow as tf
from tensorflow.python import debug as tf_debug

def read_records(filename_queue, enqueue_many_size=1024):
    reader = tf.TFRecordReader()
    _, queue_batch = reader.read_up_to(filename_queue, enqueue_many_size)
    return queue_batch

def input_batch(filenames, batch_size, num_epochs, min_after_dequeue=128, num_threads=8):
    filename_queue = tf.train.string_input_producer(filenames, num_epochs=num_epochs)
    queue_batch = read_records(filename_queue)

    capacity = min_after_dequeue + (num_threads + 3) * batch_size
    batch_serialized_example = tf.train.shuffle_batch(
        [queue_batch],
        batch_size=batch_size,
        num_threads=num_threads,
        capacity=capacity,
        min_after_dequeue=min_after_dequeue,
        enqueue_many=True)

    return batch_serialized_example

b = input_batch(['test_filename'], 32, 5)
sess = tf_debug.LocalCLIDebugWrapperSession(tf.Session())
sess.run(b)
```

### Describe the problem
tfdbg seemingly cannot step through a graph that uses tf.train.shuffle_batch. I cannot work around it by "stepping over" the node using step -t either.

### Source code / logs
Running the code provided above and stepping through the graph produces this stack trace. In a real graph, the error stops me from stepping any further. I worked out from looking at types_pb2.py that the value 20 is DT_RESOURCE. It seems like the error is triggered when tfdbg tries to convert this datatype to a numpy array.

```
--- Node Stepper: run #1: 1 fetch (shuffle_batch:0); 0 feeds ------
| <-- --> | s
Error occurred during handling of command: step :
<class 'KeyError'>: 20                                                                                                                                                                                    UP

Traceback (most recent call last):
  File "/home/ed/.pyenv/versions/neda/lib/python3.6/site-packages/tensorflow/python/debug/cli/debugger_cli_common.py", line 664, in dispatch_command
    output = handler(argv, screen_info=screen_info)
  File "/home/ed/.pyenv/versions/neda/lib/python3.6/site-packages/tensorflow/python/debug/cli/stepper_cli.py", line 487, in step
    screen_output = self.cont([self._sorted_nodes[self._next]], screen_info)
  File "/home/ed/.pyenv/versions/neda/lib/python3.6/site-packages/tensorflow/python/debug/cli/stepper_cli.py", line 397, in cont
    restore_variable_values=parsed.restore_variable_values)
  File "/home/ed/.pyenv/versions/neda/lib/python3.6/site-packages/tensorflow/python/debug/lib/stepper.py", line 679, in cont
    options=run_options)
  File "/home/ed/.pyenv/versions/neda/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/home/ed/.pyenv/versions/neda/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 952, in _run
    subfeed_dtype = subfeed_t.dtype.as_numpy_dtype
  File "/home/ed/.pyenv/versions/neda/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py", line 122, in as_numpy_dtype
    return _TF_TO_NP[self._type_enum]
KeyError: 20
```

**Comment by hbs** [comment]
Same problem arises when using tf.train.batch

**Comment by MichaelBurge** [comment]
Here is an even smaller example:

```
#!/usr/bin/python3

import tensorflow as tf
from tensorflow.python import debug as tf_debug

def problem_op():
    q = tf.FIFOQueue(1, [ tf.string ])
    return q.enqueue([ "hello" ])

sess = tf_debug.LocalCLIDebugWrapperSession(tf.Session())
sess.run(problem_op())
```
It is specifically the enqueue operation that can't be stepped over.

**Comment by MichaelBurge** [comment]
I looked at this for a bit to see if the fix was easy, or if there was a way to at least 'skip' the offending nodes in the debugger.

The problem appears to be a design constraint of the TensorFlow debugger: The NodeStepper is implemented by using feed_dict to replace the target node's dependencies with previously evaluated nodes, which are stored on disk. feed_dict requires its values to be numpy-compatible, and a queue object is not something Numpy has.

It looks like an implementation should:
* Implement a way for an arbitrary resource to be serialized to disk(or at least queues)
* Allow the feed_dict to replace queue nodes too.

I wouldn't be comfortable making this kind of design-level change myself, and it doesn't seem possible to make a quick fix to get the debugger working.

**Comment by ed-alertedh** [comment]
Nice detective work! Yeah, I assumed the lack of movement here meant it was probably not a trivial fix :/

**Comment by caisq** [comment]
Sorry for the inconvenience caused by this bug and my delayed response. The reason for this delay is that instead of fixing the specific problem that @MichaelBurge pointed out, we are planning a more thorough revamping of the NodeStepper.

The current implementation of NodeStepper has several significant limitations, including inability to handle `tf.while_loop` and incompatibility with queues and other DT_RESOURCE-based ops. In fact, the NodeStepper has been treated as more of a minor feature of tfdbg (relative to its main value dumping and inspection features) and is less well documented. The new implementation being planned will overcome these difficulties. It will be based on the recently added grpc debugger protocol (e.g., https://github.com/tensorflow/tensorflow/commit/41803db36d4f4a3239bd81e5d460eb0e6e2eea88 and https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/debug/lib/grpc_debug_server.py). So please be patient and stay tuned.

**Comment by km-sharad** [comment]
Is this problem fixed yet? If yes, what version of tensorflow is invoke_stepper available in?

**Comment by caisq** [comment]
@km-sharad A new feature is being worked on in TensorBoard to replace tfdbg CLI's `stepper` mode (tfdbg CLI's `run` will remain). The ETA is end of 2017.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by km-sharad** [comment]
I's actually tried to debug on CPU and it did not work. Was not aware hat it will work n GPU only. Anyway, my model works now and I do not need this feature right now. Thanks for your responses!

**Comment by tensorflowbutler** [comment]
A member of the TensorFlow organization has replied after the stat:awaiting tensorflower label was applied.

**Comment by tensorflowbutler** [comment]
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by caisq** [comment]
Just to be clear, the TensorBoard Debugger Plugin is not meant to replace the main features of the command-line interface of TensorFlow Debugger. Instead, it offers a GUI alternative, that is more robust for interactive stepping-based debugger on TF computation graphs.
