### ISSUE TITLE
Possible bug: LSTMCell with use_peephole=True breaks when using initializer=tf.orthogonal_initializer

### ISSUE THREAD

**Issue by Sycor4x** [tensorflow/tensorflow#10479]
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes, below.
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: OSX Sierra
- **TensorFlow installed from (source or binary)**: binary - pip
- **TensorFlow version (use command below)**: 1.2rc0
- **Bazel version (if compiling from source)**: NA
- **CUDA/cuDNN version**: NA
- **GPU model and memory**: NA
- **Exact command to reproduce**:
```

class ToyModel(object):
	def __init__(self):
		x = tf.get_variable("x", shape=[5, 3, 7],
							initializer=tf.random_normal_initializer(),
							trainable=False)
		cell = tf.contrib.rnn.LSTMCell(7, use_peepholes=True, initializer=tf.orthogonal_initializer)
		self.rnn_out, self.final_state = tf.nn.dynamic_rnn(cell=cell,
														   inputs=x,
														   parallel_iterations=8,
														   time_major=True,
														   dtype=tf.float32)


graph_context = tf.Graph()
with graph_context.as_default():
	m1 = ToyModel()

	tf_init = tf.global_variables_initializer()
	save_dir = "/Users/delkind/Desktop/whd/tf_checkpoints/unit_test"

	sv = tf.train.Supervisor(logdir=save_dir)
	with sv.managed_session() as sess:
		y1 = m1.rnn_out.eval(session=sess)

		print(y1)
```
### Describe the problem
I believe this is a bug. When using this code, the following error is raised.
```

Traceback (most recent call last):
  File "src/tensorflow_unit_tests.py", line 84, in <module>
    m1 = ToyModel()
  File "src/tensorflow_unit_tests.py", line 79, in __init__
    dtype=tf.float32)
  File "/Users/delkind/Desktop/whd/venv_tf_1.2rc0/lib/python2.7/site-packages/tensorflow/python/ops/rnn.py", line 566, in dynamic_rnn
    dtype=dtype)
  File "/Users/delkind/Desktop/whd/venv_tf_1.2rc0/lib/python2.7/site-packages/tensorflow/python/ops/rnn.py", line 729, in _dynamic_rnn_loop
    swap_memory=swap_memory)
  File "/Users/delkind/Desktop/whd/venv_tf_1.2rc0/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2766, in while_loop
    result = context.BuildLoop(cond, body, loop_vars, shape_invariants)
  File "/Users/delkind/Desktop/whd/venv_tf_1.2rc0/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2595, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/Users/delkind/Desktop/whd/venv_tf_1.2rc0/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2545, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/Users/delkind/Desktop/whd/venv_tf_1.2rc0/lib/python2.7/site-packages/tensorflow/python/ops/rnn.py", line 712, in _time_step
    skip_conditionals=True)
  File "/Users/delkind/Desktop/whd/venv_tf_1.2rc0/lib/python2.7/site-packages/tensorflow/python/ops/rnn.py", line 198, in _rnn_step
    new_output, new_state = call_cell()
  File "/Users/delkind/Desktop/whd/venv_tf_1.2rc0/lib/python2.7/site-packages/tensorflow/python/ops/rnn.py", line 700, in <lambda>
    call_cell = lambda: cell(input_t, state)
  File "/Users/delkind/Desktop/whd/venv_tf_1.2rc0/lib/python2.7/site-packages/tensorflow/contrib/rnn/python/ops/core_rnn_cell_impl.py", line 685, in __call__
    output, new_state = self._cell(inputs, state, scope)
  File "/Users/delkind/Desktop/whd/venv_tf_1.2rc0/lib/python2.7/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 165, in __call__
    return super(_RNNCell, self).__call__(inputs, state)
  File "/Users/delkind/Desktop/whd/venv_tf_1.2rc0/lib/python2.7/site-packages/tensorflow/python/layers/base.py", line 439, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/Users/delkind/Desktop/whd/venv_tf_1.2rc0/lib/python2.7/site-packages/tensorflow/contrib/rnn/python/ops/core_rnn_cell_impl.py", line 376, in call
    "w_f_diag", shape=[self._num_units], dtype=dtype)
  File "/Users/delkind/Desktop/whd/venv_tf_1.2rc0/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 1065, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "/Users/delkind/Desktop/whd/venv_tf_1.2rc0/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 962, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "/Users/delkind/Desktop/whd/venv_tf_1.2rc0/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 360, in get_variable
    validate_shape=validate_shape, use_resource=use_resource)
  File "/Users/delkind/Desktop/whd/venv_tf_1.2rc0/lib/python2.7/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 168, in _rnn_get_variable
    variable = getter(*args, **kwargs)
  File "/Users/delkind/Desktop/whd/venv_tf_1.2rc0/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 352, in _true_getter
    use_resource=use_resource)
  File "/Users/delkind/Desktop/whd/venv_tf_1.2rc0/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 725, in _get_single_variable
    validate_shape=validate_shape)
  File "/Users/delkind/Desktop/whd/venv_tf_1.2rc0/lib/python2.7/site-packages/tensorflow/python/ops/variables.py", line 200, in __init__
    expected_shape=expected_shape)
  File "/Users/delkind/Desktop/whd/venv_tf_1.2rc0/lib/python2.7/site-packages/tensorflow/python/ops/variables.py", line 278, in _init_from_args
    initial_value(), name="initial_value", dtype=dtype)
  File "/Users/delkind/Desktop/whd/venv_tf_1.2rc0/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 701, in <lambda>
    shape.as_list(), dtype=dtype, partition_info=partition_info)
  File "/Users/delkind/Desktop/whd/venv_tf_1.2rc0/lib/python2.7/site-packages/tensorflow/python/ops/init_ops.py", line 481, in __call__
    raise ValueError("The tensor to initialize must be "
ValueError: The tensor to initialize must be at least two-dimensional

```
This is unexpected behavior. If you omit either of ```initializer=tf.orthogonal_initializer``` or ```use_peephole=True```, the graph can be built and evaluated as expected. I'm not aware of a mathematical reason the weights in this model cannot be orthogonal.

**Comment by ebrevdo** [comment]
This is probably caused by the peephole parameter variables being vectors,
a limitation of the orthogonal initializer not knowing whether to treat
these as row or column vectors.

**Comment by djelkind** [comment]
@ebrevdo Your reply seems to suggest that the real problem isn't the orthogonal initializer, but employing the orthogonal initializer to initialize vectors -- since it's not meaningful for a single vector to be orthogonal in the first place.

**Comment by djelkind** [comment]
@ebrevdo Still exists in release 1.2.

**Comment by ebrevdo** [comment]
The peephole connections are vectors that represent the diagonal of a
matrix; so an orthonormal initialization for these would be a vector of all
ones.  The solution is to fix the orthonormal initializer so you can decide
how to treat vectors.

**Comment by djelkind** [comment]
To be clear, my complaint is about the software interface, not the mathematics. And for the sake of precision, note that we're speaking generally about ortho**gonal** matrices, not the special case of ortho**normal** matrices.

From a software standpoint, there are two ways to look at my bug report.

One way to look at it is that the LSTM cell is defective for trying to pound a square peg (the peepholes) into a round hole (the same initializer used for the rest of the model). Not allowing the peephole connections to be easily initialized _independently_ from the rest of the LSTM weights is the origin of the problem, to my mind. For example, in TF 1.2, the method 

> GRUCell.__init__

has no documentation, but it appears to have two weight initialization arguments, one for kernels, and one for biases. This approach to initialization seems perfectly compatible with the LSTM, with the added benefit that the GRU and LSTM classes are brought into closer alignment.

The other way is that which you point out: the orthogonal initializer needs to be smarter. But changing its behavior wholesale may not be uniformly desirable, e.g. when someone is initializing parameters otherwise than peephole connections. So for this special case, I could write an initializer for this narrow corner case, and it would solve this immediate problem, but every other user would encounter the same issue when attempting to use the orthogonal initializer, or another initialization, because these initializers are not "peephole-compatible."

**Comment by Tingbopku** [comment]
I encountered with this problem, too. 
Thank you for your post, or I think it will take me a lot of time to find the reason of this error.

But now I still wonder what the simplest way is for me to use both peephole and orthogonal initializer, cuz peephole is the most popular variant of LSTM.

**Comment by ebrevdo** [comment]
You can copy the orthogonal initializer code and modify it to generate
correct values when a vector is requested.

**Comment by zh794390558** [comment]
I have encountered this same problem in T2T.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assigneee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by ebrevdo** [comment]
@Sycor4x would you be interested in adding a peephole_initializer option to `LSTMCell` so that optimizer can be used for peephole connections if it's available?

**Comment by tensorflowbutler** [comment]
Please remove the assignee, as this issue is inviting external contributions. Otherwise, remove the `contributions welcome` label. Thank you.

**Comment by tensorflowbutler** [comment]
Please remove the assignee, as this issue is inviting external contributions. Otherwise, remove the `contributions welcome` label. Thank you.

**Comment by utkrist** [comment]
Which version of TF has the fix?

**Comment by tensorflowbutler** [comment]
Please remove the assignee, as this issue is inviting external contributions. Otherwise, remove the `contributions welcome` label. Thank you.

**Comment by tensorflowbutler** [comment]
Please remove the assignee, as this issue is inviting external contributions. Otherwise, remove the `contributions welcome` label. Thank you.

**Comment by mohantym** [comment]
Hi @Sycor4x! 
It seems you are using older versions(1.x versions) of Tensorflow. We recommend that you upgrade  your code base to 2.x  versions as many features and bug fixes has been done in newer versions and  create a new  issue if it still persists in newer versions. Thanks!

**Comment by mohantym** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)

**Comment by Yasas4D** [comment]
Hi! Where can I find this LSTMCell with tf.models?
I want to input 3 params but the docs do not have the embedding size.
rnn_cell.LSTMCell(rnn_size, input_embedding_size,  use_peepholes=True)
