### ISSUE TITLE
Can't build from source?

### ISSUE THREAD

**Issue by FabHan** [tensorflow/tensorflow#105]
I followed the instructions [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md) but failed at this step.
```
➜  tensorflow git:(master) bazel build -c opt //tensorflow/cc:tutorials_example_trainer
..........
INFO: Elapsed time: 2.016s
java.lang.NoClassDefFoundError: com/jcraft/jsch/JSchException
        at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:109)
        at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:136)
        at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:262)
        at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:161)
        at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:136)
        at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)
        at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1138)
        at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:130)
        at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:193)
        at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:133)
        at com.google.devtools.build.lib.bazel.repository.GitCloneFunction.compute(GitCloneFunction.java:124)
        at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:725)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$2.run(AbstractQueueVisitor.java:436)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.jcraft.jsch.JSchException
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 16 more
```

My environment is Ubuntu 14.04 LTS without  GPU.

**Comment by vrv** [comment]
From the stack trace, it seems likely that this is either:

1) A bazel problem
2) A connection problem

Can you validate that just plain 'bazel' is working properly?  If not, that's probably something to ask the bazel team.

**Comment by vrv** [comment]
(Please re-open if you find this is TensorFlow related)

**Comment by FabHan** [comment]
Yes, plain `bazel` works.

```
➜  tensorflow git:(master) bazel
..........
                                                 [bazel release head (@125b349)]
Usage: bazel <command> <options> ...

Available commands:
  analyze-profile     Analyzes build profile data.
  build               Builds the specified targets.
  canonicalize-flags  Canonicalizes a list of bazel options.
  clean               Removes output files and optionally stops the server.
  dump                Dumps the internal state of the bazel server process.
  fetch               Fetches external repositories that are prerequisites to the targets.
  help                Prints help for commands, or the index.
  info                Displays runtime info about the bazel server.
  mobile-install      Installs targets to mobile devices.
  query               Executes a dependency graph query.
  run                 Runs the specified target.
  shutdown            Stops the bazel server.
  test                Builds and runs the specified test targets.
  version             Prints version information for bazel.

Getting more help:
  bazel help <command>
                   Prints help and options for <command>.
  bazel help startup_options
                   Options for the JVM hosting bazel.
  bazel help target-syntax
                   Explains the syntax for specifying targets.
  bazel help info-keys
                   Displays a list of keys used by the info command.
➜  tensorflow git:(master) bazel build
INFO: Found 0 targets...
INFO: Elapsed time: 2.310s, Critical Path: 0.01s
```

I'll cross post this issue to `bazel`.

**Comment by FabHan** [comment]
Could you please leave this open? If it's not clear that the problem is only `bazel` then I suggest keeping the issue open on both repos.

If I `git checkout master` then I can get pass the Java exception state but would get into another issue (already reported by someone else [here](https://github.com/tensorflow/tensorflow/issues/119))

**Comment by pwaller** [comment]
I can't install from binaries, nor from source. Bazel said that [it's a problem with the tensorflow documentation](https://github.com/bazelbuild/bazel/issues/586#issuecomment-156053152). Please reopen.

**Comment by pwaller** [comment]
I see that the [instructions have changed](https://github.com/tensorflow/tensorflow/commit/72a5a60dd4664a7caa4611344364ac7851464a60), but for some reason the site is still out of date.

**Comment by pwaller** [comment]
Following the new installation instructions I still seem to hit the same problem:

```
$ bazel version
.......
Build label: 0.1.1-jdk7
Build target: bazel-out/local_linux-fastbuild/bin/src/main/java/bazel-main_deploy.jar
Build time: Thu Oct 15 20:35:27 2015 (1444941327)
Build timestamp: 1444941327
Build timestamp as int: 1444941327
$ bazel build -c opt //tensorflow/tools/pip_package:build_pip_package
INFO: Elapsed time: 1.092s
java.lang.NoClassDefFoundError: com/jcraft/jsch/JSchException
	at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:109)
	at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:136)
	at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:262)
	at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:161)
	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:136)
	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)
	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1138)
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:130)
	at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:193)
	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:133)
	at com.google.devtools.build.lib.bazel.repository.GitCloneFunction.compute(GitCloneFunction.java:124)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:810)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$2.run(AbstractQueueVisitor.java:439)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.jcraft.jsch.JSchException
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 16 more
```
