### ISSUE TITLE
Can't import tensorflow 1.2 since last anaconda 4.4 update

### ISSUE THREAD

**Issue by jingw222** [tensorflow/tensorflow#10596]
I installed tf 1.2 from source on Ubuntu 16.04, and It worked as it should until I updated anaconda to 4.4 yesterday. It refuses to load and gives me this error:

```
>>> import tensorflow
Traceback (most recent call last):
  File "/home/jingw222/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/jingw222/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/jingw222/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/jingw222/anaconda3/lib/python3.6/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/jingw222/anaconda3/lib/python3.6/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /home/jingw222/anaconda3/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/jingw222/anaconda3/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jingw222/anaconda3/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/home/jingw222/anaconda3/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/jingw222/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 52, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/jingw222/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/jingw222/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/jingw222/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/jingw222/anaconda3/lib/python3.6/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/jingw222/anaconda3/lib/python3.6/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /home/jingw222/anaconda3/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/jingw222/anaconda3/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

```

Anyone knows what went wrong?

**Comment by girving** [comment]
@caisq Any ideas?  Not sure if you're the right person to ask.

**Comment by caisq** [comment]
@jingw222 So you built TensorFlow from source. Could it be that your build environment uses a glibcxx  version that is unavailable in your instal environment?

**Comment by jingw222** [comment]
Yeah, it was built from source and working fine until maybe the anaconda update. I highly suspect it was due to anaconda upgrade some package, because  when I tried to install the package `libstdc++6` the terminal told me `libstdc++6 is already the newest version (5.4.0-6ubuntu1~16.04.4)`. Should I build it again?

**Comment by jingw222** [comment]
The was indeed introduced by anaconda upgrade, cause I had similiar issue with another ML library as well. After lots of searches through the web, I tried `conda install libgcc` a moment ago, and the problem disappeared. My guess is that after I updated anaconda, the `libstdc++6` library somehow didn't get installed in the conda environment. Therefore even though `libstdc++6 is already the newest version (5.4.0-6ubuntu1~16.04.4)`, it was not shared with the conda environment. Thank you guys anyway!

**Comment by aselle** [comment]
glad you got it resolved, closing for now. Thanks!

**Comment by oxydron** [comment]
Same problem and `conda install libgcc` don't solve it.

ImportError: /home/bh/anaconda3/envs/keras2/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /home/bh/anaconda3/envs/keras2/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)

**Comment by oxydron** [comment]
Same problem and `conda install libgcc` don't solve it.

ImportError: /home/bh/anaconda3/envs/keras2/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /home/bh/anaconda3/envs/keras2/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)
