### ISSUE TITLE
Bazel bring up for ROCm

### ISSUE THREAD

**Issue by adityaatluri** [tensorflow/tensorflow#10703]
Hi,
I am trying to add new backend to tensorflow. As a first step, I started changing bazel files around [(Commit here)](https://github.com/ROCmSoftwarePlatform/tensorflow/commit/b75ea3f499a5f63f2580066ae132c93e2b03d0ad). When I enable XLA + ROCM during configure, and run `bazel build -s --config=opt --config=rocm //tensorflow/tools/pip_package:build_pip_package `, I am getting the following error:
```
ERROR: no such package '@local_config_rocm//': error loading package 'external': The repository named 'local_config_rocm' could not be resolved.
INFO: Elapsed time: 0.227s
```

It would be great if someone can parse the commit mentioned and suggest changes. 
Thank you!

**Comment by aselle** [comment]
Could you try to make the minimal change that exhibits your year. Unfortunately, we have many issues and your commit is over 1296 lines.

**Comment by adityaatluri** [comment]
Hi,
Thank you response. You can ignore the LICENSE and CROSSTOOL_HCC.bzl. 
I guess the point of interest will be the rocm_configure.bzl file. https://github.com/ROCmSoftwarePlatform/tensorflow/blob/b75ea3f499a5f63f2580066ae132c93e2b03d0ad/third_party/gpus/rocm_configure.bzl
If you are familiar with bazel infrastructure, can you guide me to add AMDGPU support to bazel?

**Comment by aselle** [comment]
I am unfortunately far from a bazel expert, but @jart may have some suggestions.

**Comment by jart** [comment]
I'm noticing you added this code:

```py
# Macros for building CUDA code.
def if_rocm(if_true, if_false = []):
    return select({
        "@local_config_rocm//rocm:using_hcc": if_true,
        "//conditions:default": if_false
    })
```

What is `@local_config_rocm`? In order to have a label like that, you need to add something like the following to your `tensorflow/workspace.bzl` file:

```py
native.new_http_archive(
    name = "local_config_rocm",
   # ...
```

**Comment by adityaatluri** [comment]
Huh. Didn't know that. I'll add `local_config_rocm` to `tensorflow/workspace.bzl` and see how it goes.
Thank you for the response.

**Comment by jart** [comment]
Feel free to ping this bug again if you get stuck on Bazel. If you're writing a feature for TensorFlow, then I'm happy to support you.

**Comment by adityaatluri** [comment]
Hi,
I pushed my [code](https://github.com/ROCmSoftwarePlatform/tensorflow/tree/06202017-rocblas-se-v2). I need help stitching bazel around it so that the host compiler can touch them and link against rocm libraries.

**Comment by jart** [comment]
Have you taken a look into [cuda_configure.bzl](https://github.com/tensorflow/tensorflow/blob/master/third_party/gpus/cuda_configure.bzl). We've got a lot of code for configuring cuda in our build process. I'm not familiar with ROCm but if it's AMD's version of CUDA then this is most likely going to be a highly nontrivial undertaking.

**Comment by adityaatluri** [comment]
Hi @jart ,
We are focusing on supporting XLA first. We want to move away from using HCC (device code compiler for ROCm) and use just LLVM, libraries and runtime to run TF code. The file `cuda_configure.bzl` seems have `nvcc` specific functions, but for rocm support we want just host compiler (g++/clang++) build functions. Will this make the problem trivial?

**Comment by adityaatluri** [comment]
Hi @jart,
I added bazel files for rocm+xla [here](https://github.com/tensorflow/tensorflow/commit/33fdacaf31f9a9ee2628dc0de36c558cdd607e31)

**Comment by cy89** [comment]
@jart, this does seem like a Bazel issue; PTAL when you have a moment.

**Comment by cy89** [comment]
a

**Comment by chanil1218** [comment]
@adityaatluri 
I found [a suspicious line](https://github.com/tensorflow/tensorflow/blob/33fdacaf31f9a9ee2628dc0de36c558cdd607e31/third_party/gpus/rocm_configure.bzl#L546) of the BUILD file not found error occurs.
I think changing `cuda:BUILD` to `rocm:BUILD` could resolve the error.

I would like to support enabling ROCm backend for XLA.
It would be better separate forked tensorflow repo instead of dangling Github tree. 
Could you apply your changes to your forked tensorflow repository?

**Comment by adityaatluri** [comment]
Hi @chanil1218 
Thank you for the pointer.

You are most welcome in enabling ROCm XLA backend. We are actually waiting for CLA approval from our legal team. We would love to have bazel stuff figured out before implementing actual code.

**Comment by adityaatluri** [comment]
Hi,
I started fresh as the plan is not to use AMD compiler (HCC). Here it is:

Code:
https://github.com/ROCmSoftwarePlatform/tensorflow/tree/rocm-v1

The build instructions are here:
https://github.com/ROCmSoftwarePlatform/tensorflow/blob/rocm-v1/ROCM.md

I am getting the following error:
```shell
$ bazel build --config=opt --config=rocm //tensorflow/tools/pip_package:build_pip_package
 ERROR: no such package '@local_config_rocm//': Traceback (most recent call last):
        File "/home/aditya/tensorflow/third_party/gpus/rocm_configure.bzl", line 555
                _create_local_rocm_repository(repository_ctx)
        File "/home/aditya/tensorflow/third_party/gpus/rocm_configure.bzl", line 506, in _create_local_rocm_repository
                _tpl(repository_ctx, "rocm:build_defs.b...", ...)})
        File "/home/aditya/tensorflow/third_party/gpus/rocm_configure.bzl", line 238, in _tpl
                repository_ctx.template(out, Label(("//third_party/gpus/%s...)), ...)
 Unable to load package for //third_party/gpus/rocm:build_defs.bzl.tpl: not found.
 INFO: Elapsed time: 0.301s FAILED: Build did NOT complete successfully (0 packages loaded) 
```

`build_defs.bzl.tpl` is present here: https://github.com/ROCmSoftwarePlatform/tensorflow/blob/rocm-v1/third_party/gpus/rocm/build_defs.bzl.tpl

**Comment by adityaatluri** [comment]
@cy89 can you help me resolve this issue? Thanks!

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Awaiting TensorFlower: It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Awaiting TensorFlower: It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by Mandrewoid** [comment]
@adityaatluri  although this issue appears stale, I thought I'd let you know the https://github.com/ROCmSoftwarePlatform/tensorflow links are dead

**Comment by vigchand2705** [comment]
@Mandrewoid I am guessing this is the new link https://github.com/ROCmSoftwarePlatform/hiptensorflow

**Comment by tensorflowbutler** [comment]
Nagging Awaiting TensorFlower: It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @aselle: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.
