### ISSUE TITLE
tf.contrib.data.Dataset.filter kernel error on excluded element

### ISSUE THREAD

**Issue by EdeMeijer** [tensorflow/tensorflow#10725]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary (nightly build)
- **TensorFlow version (use command below)**:  1.2.0-rc2 (git version v1.2.0-rc0-1066-g4c0052d)
- **CUDA/cuDNN version**: 8.0
- **GPU model and memory**: GTX 970
- **Exact command to reproduce**: See script

### Describe the problem
I am trying to use Dataset's `filter()` function to exclude certain examples, but when the iterator hits the index of the first excluded example, a kernel error occurs and the program crashes.

### Source code / logs

This example creates a data set of 100 integers and filters out every third one by checking `x % 3 != 2`. The first two calls to `sess.run()` produce the digits 0 and 1 and they get printed correctly. At the third `sess.run()` call, the program crashes.

Running this

```python
import tensorflow as tf

dataset = tf.contrib.data.Dataset.range(100)
dataset = dataset.filter(lambda x: tf.not_equal(tf.mod(x, 3), 2))

iterator = dataset.make_one_shot_iterator()
next_element = iterator.get_next()

sess = tf.Session()
print(sess.run(next_element))
print(sess.run(next_element))
print(sess.run(next_element))
```

It results in this

```
2017-06-15 10:18:44.797870: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-06-15 10:18:44.797884: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-06-15 10:18:44.797886: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-06-15 10:18:44.797888: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-06-15 10:18:44.797891: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
2017-06-15 10:18:44.896171: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:893] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2017-06-15 10:18:44.896367: I tensorflow/core/common_runtime/gpu/gpu_device.cc:938] Found device 0 with properties: 
name: GeForce GTX 970
major: 5 minor: 2 memoryClockRate (GHz) 1.253
pciBusID 0000:01:00.0
Total memory: 3.94GiB
Free memory: 3.42GiB
2017-06-15 10:18:44.896377: I tensorflow/core/common_runtime/gpu/gpu_device.cc:959] DMA: 0 
2017-06-15 10:18:44.896379: I tensorflow/core/common_runtime/gpu/gpu_device.cc:969] 0:   Y 
2017-06-15 10:18:44.896384: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1028] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 970, pci bus id: 0000:01:00.0)
0
1
2017-06-15 10:18:45.918333: W tensorflow/core/framework/op_kernel.cc:1165] Invalid argument: Expects 1 arguments, but 2 is provided
Traceback (most recent call last):
  File "/home/ede/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1267, in _do_call
    return fn(*args)
  File "/home/ede/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1248, in _run_fn
    status, run_metadata)
  File "/usr/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/home/ede/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Expects 1 arguments, but 2 is provided
	 [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[]], output_types=[DT_INT64], _device="/job:localhost/replica:0/task:0/cpu:0"](OneShotIterator)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ede/.IntelliJIdea2017.1/config/scratches/scratch_6.py", line 14, in <module>
    print(sess.run(next_element))
  File "/home/ede/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 896, in run
    run_metadata_ptr)
  File "/home/ede/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1108, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/ede/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1261, in _do_run
    options, run_metadata)
  File "/home/ede/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1280, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Expects 1 arguments, but 2 is provided
	 [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[]], output_types=[DT_INT64], _device="/job:localhost/replica:0/task:0/cpu:0"](OneShotIterator)]]

Caused by op 'IteratorGetNext', defined at:
  File "/home/ede/.IntelliJIdea2017.1/config/scratches/scratch_6.py", line 8, in <module>
    next_element = iterator.get_next()
  File "/home/ede/tensorflow/lib/python3.5/site-packages/tensorflow/contrib/data/python/ops/dataset_ops.py", line 247, in get_next
    name=name))
  File "/home/ede/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 282, in iterator_get_next
    output_shapes=output_shapes, name=name)
  File "/home/ede/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/home/ede/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2528, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/ede/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1203, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Expects 1 arguments, but 2 is provided
	 [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[]], output_types=[DT_INT64], _device="/job:localhost/replica:0/task:0/cpu:0"](OneShotIterator)]]
```

**Comment by aselle** [comment]
@vrv, do you have any thoughts on this issue?

**Comment by vrv** [comment]
Thanks for the simple repro!  I'm not entirely familiar with the code unfortunately; I took a quick look at the code and nothing obvious popped out as to why there are two input tensors anywhere (range produces a single element, filter just passes on the type of its input), so we'll need to do some more debugging to figure out why this is happening.  Thanks for the report!

**Comment by vrv** [comment]
Okay I think I found the bug and sent it out for review internally, not sure if it's the right solution given my lack of knowledge about the internals, but it at least solves the issue illustrated by this code.
