### ISSUE TITLE
Undefined Symbol Import error 

### ISSUE THREAD

**Issue by kafkagt** [tensorflow/tensorflow#10768]
Hi,

SO: Linux Mint 17 x64
Version 1.1
Compiling from source
Options: sycl (Opencl)
Python 2.7

_Using TensorFlow backend.
Traceback (most recent call last):
  File "/home/kafka/PycharmProjects/Test1/Test1.py", line 1, in <module>
    from keras.models import Sequential
  File "/usr/local/lib/python2.7/dist-packages/keras/__init__.py", line 3, in <module>
    from . import activations
  File "/usr/local/lib/python2.7/dist-packages/keras/activations.py", line 4, in <module>
    from . import backend as K
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/__init__.py", line 73, in <module>
    from .tensorflow_backend import *
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py", line 1, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 51, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 52, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: /usr/local/lib/python2.7/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: _ZN2cl4sycl7program30create_program_for_kernel_implESsPKhiPKPKcSt10shared_ptrINS0_6detail7contextEE

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help._

**Comment by aselle** [comment]
OpenCL is highly experimental  right now, so marking community support. It also is not yet performant. Follow along #22 for more info.

**Comment by kafkagt** [comment]
Thanks

**Comment by rodburns** [comment]
For now you would be better on the branch referenced [here](https://www.codeplay.com/products/computesuite/computecpp/guides/how-to-setup-tensorflow-with-computecpp) until the changes make it upstream to the main TensorFlow branch 
https://github.com/lukeiwanski/tensorflow.git
branch: opencl_improvements

**Comment by kafkagt** [comment]
Thanks men, i will try it.

**Comment by harshini-gadige** [comment]
Please open a new issue if this problem still persists with the latest Tensorflow version by providing all information asked in[ this template](https://github.com/tensorflow/tensorflow/issues/new/choose).
