### ISSUE TITLE
Something error when I run  iris_monitors.py 

### ISSUE THREAD

**Issue by LuoJiaji** [tensorflow/tensorflow#10847]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **TensorFlow installed from (source or binary)**:binary
- **TensorFlow version (use command below)**:1.0.1
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:import tensorflow

### Describe the problem
When I run iris_monitors.py in Pycharm file(https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/tutorials/monitors/iris_monitors.py), It has an error :
Traceback (most recent call last):
  File "F:/temp/Python/temp.py", line 92, in <module>
    tf.app.run()
  File "C:\software\Python\Python35\lib\site-packages\tensorflow\python\platform\app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "F:/temp/Python/temp.py", line 35, in main
    filename=IRIS_TRAINING, target_dtype=np.int, features_dtype=np.float)
  File "C:\software\Python\Python35\lib\site-packages\tensorflow\contrib\learn\python\learn\datasets\base.py", line 47, in load_csv_with_header
    header = next(data_file)
StopIteration

### Source code / logs
C:\software\Python\Python35\python.exe F:/temp/Python/temp.py
Traceback (most recent call last):
  File "F:/temp/Python/temp.py", line 92, in <module>
    tf.app.run()
  File "C:\software\Python\Python35\lib\site-packages\tensorflow\python\platform\app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "F:/temp/Python/temp.py", line 35, in main
    filename=IRIS_TRAINING, target_dtype=np.int, features_dtype=np.float)
  File "C:\software\Python\Python35\lib\site-packages\tensorflow\contrib\learn\python\learn\datasets\base.py", line 47, in load_csv_with_header
    header = next(data_file)
StopIteration

Process finished with exit code 1

**Comment by tatatodd** [comment]
@LuoJiaji Can you try the latest TensorFlow 1.2.0?
