### ISSUE TITLE
Bug: MultiRNNCell.state_size is a tuple

### ISSUE THREAD

**Issue by rickyhan** [tensorflow/tensorflow#10862]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.2
- **Bazel version (if compiling from source)**: n/a
- **CUDA/cuDNN version**: 8.0
- **GPU model and memory**: 1080 Ti
- **Exact command to reproduce**: see below

### Describe the problem

Version 1:

The follow code will return LSTMStateTuple with `h` and `c`:

```python

        enc_cell = tf.contrib.rnn.LSTMCell(hidden_dim)

        enc_inp_len = np.array([seq_length_in for _ in range(batch_size)])

        ((encoder_fw_outputs,
          encoder_bw_outputs),
         (encoder_fw_final_state,
          encoder_bw_final_state)) = (
            tf.nn.bidirectional_dynamic_rnn(cell_fw=enc_cell,
                                            cell_bw=enc_cell,
                                            inputs=enc_inp,
                                            sequence_length=enc_inp_len,
                                            dtype=tf.float32)
            )
        encoder_outputs = tf.concat((encoder_fw_outputs, encoder_bw_outputs), 2)

        encoder_final_state_c = tf.concat(
            (encoder_fw_final_state.c, encoder_bw_final_state.c), 1)

        encoder_final_state_h = tf.concat(
            (encoder_fw_final_state.h, encoder_bw_final_state.h), 1)

        encoder_final_state = tf.contrib.rnn.LSTMStateTuple(
            c=encoder_final_state_c,
            h=encoder_final_state_h
        )
```

However, if I run the following MultiCellRNN:

```python
        enc_cells = []
        for i in range(0, encoder_depth):
            with tf.variable_scope('enc_RNN_{}'.format(i)):
                cell = tf.contrib.rnn.GRUCell(hidden_dim)  # Or LSTMCell(hidden_dim)
                cell = tf.contrib.rnn.DropoutWrapper(cell, output_keep_prob=1.0-dropout)
                enc_cells.append(cell)
        enc_cell = tf.contrib.rnn.MultiRNNCell(enc_cells)

        ((encoder_fw_outputs,
          encoder_bw_outputs),
         (encoder_fw_final_state,
          encoder_bw_final_state)) = (
            tf.nn.bidirectional_dynamic_rnn(cell_fw=enc_cell,
                                            cell_bw=enc_cell,
                                            inputs=enc_inp,
                                            sequence_length=enc_inp_len,
                                            dtype=tf.float32)
            )

        # encoder_fw_final_state is a Tensor from the .c part of LSTMStateTuple
```

It will return state tensor(just the `c` part, not the `h` activation)

**Comment by rickyhan** [comment]
I was using GRUCell, I'll change that to LSTMCell and test it again.

**Comment by rickyhan** [comment]
Not a bug. Please ignore this issue

**Comment by rickyhan** [comment]
Turns out there is a related bug:

```python
with tf.variable_scope("DECODE"):
    dec_cells = []
    # name="dec_cell_{}".format(i)
    for i in range(0, decoder_depth):
        with tf.variable_scope('dec_RNN_{}'.format(i)):
            cell = tf.contrib.rnn.GRUCell(hidden_dim * 2)
            cell = tf.contrib.rnn.DropoutWrapper(cell, output_keep_prob=1.0-dropout)
            dec_cells.append(cell)
    decoder_cell = tf.contrib.rnn.MultiRNNCell(dec_cells)

    print decoder_cell.state_size
    # (24, 24)
    print encoder_final_state #
    # result: LSTMStateTuple(c=<tf.Tensor 'ENCODE/concat_1:0' shape=(?, 24) dtype=float32>, h=<tf.Tensor 'ENCODE/concat_2:0' shape=(?, 24) dtype=float32>)#

    # decoder_cell = tf.contrib.rnn.LSTMCell(hidden_dim*2) # BUG:

    decoder_outputs_ta, decoder_final_state, _ = tf.nn.raw_rnn(decoder_cell, loop_fn)

(24, 24)
LSTMStateTuple(c=<tf.Tensor 'ENCODE/concat_1:0' shape=(?, 24) dtype=float32>, h=<tf.Tensor 'ENCODE/concat_2:0' shape=(?, 24) dtype=float32>)
Traceback (most recent call last):
  File "/home/g/Desktop/seq2seq/run.py", line 141, in <module>
    decoder_outputs_ta, decoder_final_state, _ = tf.nn.raw_rnn(decoder_cell, loop_fn)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/rnn.py", line 954, in raw_rnn
    nest.assert_same_structure(initial_state, cell.state_size)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/nest.py", line 147, in assert_same_structure
    _recursive_assert_same_structure(nest1, nest2, check_types)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/nest.py", line 119, in _recursive_assert_same_structure
    % (type_nest1, type_nest2))
TypeError: The two structures don't have the same sequence type. First structure has type <class 'tensorflow.python.ops.rnn_cell_impl.LSTMStateTuple'>, while second structure has type <type 'tuple'>.
```

**Comment by rickyhan** [comment]
Can someone please take a look at this?

**Comment by rickyhan** [comment]
@tatatodd Could you confirm this is a bug?

**Comment by rickyhan** [comment]
I did some research and foundhttps://github.com/suriyadeepan/augmented_seq2seq/blob/01706d3869a42f3cf0bfe5c83f069646315a945e/bi_encoder.py#L54.

He uses `tf.scan` to manually generate an output and state tuple

**Comment by ali01** [comment]
@ebrevdo, could you take a quick look?

**Comment by ebrevdo** [comment]
The output type of a MultiRnnCell is always a tuple.  It may be a tuple with one element... a LSTMStateTuple.  This is intended behavior.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
A member of the TensorFlow organization has replied after the stat:awaiting tensorflower label was applied.

**Comment by drpngx** [comment]
Working as documented.
https://www.github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/rnn_cell_impl.py#L211
