### ISSUE TITLE
 freeze_graph script error : google.protobuf.text_format.ParseError 

### ISSUE THREAD

**Issue by abhiML** [tensorflow/tensorflow#10983]
I am trying to run the freeze_graph script on my own .pb and .ckpt file. However I am getting this error.

```
google.protobuf.text_format.ParseError: 2:1 : Message type "tensorflow.GraphDef" has no field named "j".
```
The stack trace is as follows:
```
Traceback (most recent call last):
  File "/home/gabbar/ML/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/tools/freeze_graph.py", line 255, in <module>
    app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/home/gabbar/ML/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/gabbar/ML/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/tools/freeze_graph.py", line 187, in main
    FLAGS.variable_names_blacklist)
  File "/home/gabbar/ML/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/tools/freeze_graph.py", line 165, in freeze_graph
    input_graph_def = _parse_input_graph_proto(input_graph, input_binary)
  File "/home/gabbar/ML/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/tools/freeze_graph.py", line 134, in _parse_input_graph_proto
    text_format.Merge(f.read(), input_graph_def)
  File "/home/gabbar/.cache/bazel/_bazel_gabbar/3ef5463937ccade414be63dae84521e3/execroot/tensorflow/bazel-out/local_linux-opt/bin/tensorflow/python/tools/freeze_graph.runfiles/protobuf/python/google/protobuf/text_format.py", line 481, in Merge
    descriptor_pool=descriptor_pool)
  File "/home/gabbar/.cache/bazel/_bazel_gabbar/3ef5463937ccade414be63dae84521e3/execroot/tensorflow/bazel-out/local_linux-opt/bin/tensorflow/python/tools/freeze_graph.runfiles/protobuf/python/google/protobuf/text_format.py", line 535, in MergeLines
    return parser.MergeLines(lines, message)
  File "/home/gabbar/.cache/bazel/_bazel_gabbar/3ef5463937ccade414be63dae84521e3/execroot/tensorflow/bazel-out/local_linux-opt/bin/tensorflow/python/tools/freeze_graph.runfiles/protobuf/python/google/protobuf/text_format.py", line 568, in MergeLines
    self._ParseOrMerge(lines, message)
  File "/home/gabbar/.cache/bazel/_bazel_gabbar/3ef5463937ccade414be63dae84521e3/execroot/tensorflow/bazel-out/local_linux-opt/bin/tensorflow/python/tools/freeze_graph.runfiles/protobuf/python/google/protobuf/text_format.py", line 583, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "/home/gabbar/.cache/bazel/_bazel_gabbar/3ef5463937ccade414be63dae84521e3/execroot/tensorflow/bazel-out/local_linux-opt/bin/tensorflow/python/tools/freeze_graph.runfiles/protobuf/python/google/protobuf/text_format.py", line 652, in _MergeField
    (message_descriptor.full_name, name))
google.protobuf.text_format.ParseError: 2:1 : Message type "tensorflow.GraphDef" has no field named "j".
```

**Comment by AndreaPisoni** [comment]
Did you figure it out?

**Comment by abhiML** [comment]
Yeah you just have to specify --input_binary=True.

**Comment by SivaGabbi** [comment]
@abhiML Hi Abhi,

I am getting the same error.. i was wondering where you gave the --input_binary=True as a  parameter..

**Comment by abhiML** [comment]
while running the file from terminal.
