### ISSUE TITLE
map_func of tf.contrib.data.Dataset.map gets dict keys instead of values when the nested structure of Dataset is dict

### ISSUE THREAD

**Issue by c810armyHuan** [tensorflow/tensorflow#11016]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: b'0.5.0-12520-g1111e06d9' 1.2.0-rc2
- **Bazel version (if compiling from source)**: 0.4.5
- **CUDA/cuDNN version**: 8.0/6
- **GPU model and memory**:

### Describe the problem

If the nested structure of `Dataset` is `dict`, `MapDataset` will call [`map_func(*nested_args)`](https://github.com/tensorflow/tensorflow/blob/1111e06d9cd691cbdfcb67cf9f234a504f4e0f6d/tensorflow/contrib/data/python/ops/dataset_ops.py#L1463) and pass the keys of `nested_args` instead of components in the dataset to `map_func`. It seems that `nested_args` or `*nested_args.values()` need to be passed to `map_func`, so that `map_func` could transform the elements in the dataset.

### Source code / logs
```python
import tensorflow as tf

def foo(*args, **kwargs):
    print(args, kwargs) # ('a', 'b') {}
    return 1 * 100, 2 * 200

tf.contrib.data.Dataset.from_tensors({'a': [1], 'b': [2]}).map(foo)
```

**Comment by rohan100jain** [comment]
I tried reproducing and I think that Dicts are not supported as inputs in general

>>> a = tf.contrib.data.Dataset.from_tensors({'a': [1], 'b': [2]})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/data/python/ops/dataset_ops.py", line 460, in from_tensors
    return TensorDataset(tensors)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/data/python/ops/dataset_ops.py", line 864, in __init__
    for i, t in enumerate(nest.flatten(tensors))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 676, in convert_to_tensor
    as_ref=False)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 741, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/constant_op.py", line 113, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/constant_op.py", line 102, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_util.py", line 462, in make_tensor_proto
    "supported type." % (type(values), values))
TypeError: Failed to convert object of type <type 'dict'> to Tensor. Contents: {'a': [1], 'b': [2]}. Consider casting elements to a supported type.

My tensorflow version was 1.2.0 though.

**Comment by c810armyHuan** [comment]
It seems that f3f53e8b394bdcaddc707f7bde8dcc98a73531e7 adds support for `dict` as nested structures of `Dataset`.

**Comment by mrry** [comment]
This is definitely a bug. Thanks for catching it! I have a fix in the works.

**Comment by c810armyHuan** [comment]
It seemed that the parameter `padded_shapes` for `tf.contrib.data.Dataset.padded_batch` can't be `dict` too.

**Comment by mrry** [comment]
Thanks! That turned up when I was testing the fix.
