### ISSUE TITLE
AttributeError: 'module' object has no attribute 'Copy' on fully_connected.py. Built from source on 15th February.

### ISSUE THREAD

**Issue by jkschin** [tensorflow/tensorflow#1102]
I built from source on 15th February. I can run cifar10_train.py, with the warning during training as stated here.

https://github.com/tensorflow/tensorflow/issues/1076

I can run the convolutional mnist with no problems. However, when I try fully_connected.py, this error shows up.

Traceback (most recent call last):
  File "fully_connected_feed.py", line 228, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/default/_app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "fully_connected_feed.py", line 224, in main
    run_training()
  File "fully_connected_feed.py", line 130, in run_training
    data_sets = input_data.read_data_sets(FLAGS.train_dir, FLAGS.fake_data)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/examples/tutorials/mnist/input_data.py", line 198, in read_data_sets
    local_file = maybe_download(TRAIN_IMAGES, train_dir)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/examples/tutorials/mnist/input_data.py", line 42, in maybe_download
    tf.gfile.Copy(temp_file_name, filepath)
AttributeError: 'module' object has no attribute 'Copy'

I have also tried uninstalling and reinstalling TensorFlow. I don't think it's a problem with the installation since some examples run properly. Anyone else facing this too?

**Comment by vrv** [comment]
This looks like a bug, a missing function that we need to implement.   Thanks for reporting.

**Comment by jkschin** [comment]
Thanks for the fix. I have verified that Copy is back. But it's still missing Open.

  File "/usr/local/lib/python2.7/dist-packages/tensorflow/examples/tutorials/mnist/input_data.py", line 57, in extract_images
    with tf.gfile.Open(filename) as f, gzip.GzipFile(fileobj=f) as bytestream:
AttributeError: 'module' object has no attribute 'Open'

**Comment by vrv** [comment]
Yep, I have another fix for that coming.
