### ISSUE TITLE
Tensorflow 1.2.0 : can not load  graph using tf.train.import_meta_graph

### ISSUE THREAD

**Issue by prannayk** [tensorflow/tensorflow#11027]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: self written code
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04 on Azure VM
- **TensorFlow installed from (source or binary)**: Source
- **TensorFlow version (use command below)**: 1.2.0
- **Bazel version (if compiling from source)**: 0.5.1
- **CUDA/cuDNN version**: 8.0 and 6.0.21 respectively
- **GPU model and memory**: NVIDIA Tesla K80
- **Exact command to reproduce**: tf.train.import_meta_graph("graph_name")

2017-06-24 07:01:44.245235: I tensorflow/core/common_runtime/gpu/gpu_device.cc:940] Found device 0 with properties:
name: Tesla K80
major: 3 minor: 7 memoryClockRate (GHz) 0.8235
pciBusID 92f4:00:00.0
Total memory: 11.17GiB
Free memory: 11.11GiB
2017-06-24 07:01:44.245278: I tensorflow/core/common_runtime/gpu/gpu_device.cc:961] DMA: 0
2017-06-24 07:01:44.245291: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   Y
2017-06-24 07:01:44.245304: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla K80, pci bus id: 92f4:00:00.0)

### Problem
Whenever the code spawns the loading of meta graph, it does not exit. If the process is cancelled, there is no segmentation fault, and the code exits cleanly. 

### Source code / logs
Python 2.7.12 (default, Nov 19 2016, 06:48:10)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as rd
>>>
KeyboardInterrupt
>>> import tensorflow as tf
>>> tf.__version__
'1.2.0'
>>> tf.layers.conv2d_transpose
<function conv2d_transpose at 0x7fe9ccd5e668>
>>> saver = tf.train.import_meta_graph('../results/nepal/Need/wc2_nepal_2_model.ckpt.meta')                                                                                                                

^CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1686, in import_meta_graph
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/meta_graph.py", line 504, in import_scoped_meta_graph
    producer_op_list=producer_op_list)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/importer.py", line 387, in import_graph_def
    op._add_input(source_tensor, dtype=input_type)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1473, in _add_input
    self._recompute_node_def()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1542, in _recompute_node_def
    self._node_def.input.extend([t._as_node_def_input() for t in self._inputs])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 483, in _as_node_def_input
    if not self._op.name:
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1420, in name
    return self._node_def.name
KeyboardInterrupt
>>>

**Comment by skye** [comment]
Would you be able to provide us with your metagraph files? Otherwise this will be very hard to reproduce and diagnose.

Also, how long did you try running the command before cancelling it? I'm wondering if it's truly stuck or taking a long time.

**Comment by tensorflowbutler** [comment]
This issue is automatically closed due to lack of activity. Please re-open if this is still an issue for you. Thanks!
