### ISSUE TITLE
Tensorflow - No valid folders of images found at XXXXX

### ISSUE THREAD

**Issue by Bioimager-MD** [tensorflow/tensorflow#11044]
So I have a semi custom code written for a new biomedical program that I am developing. I am trying to get my model to begin retraining and I am getting this problem out of nowhere whenever I run 

python retrain.py \
  --bottleneck_dir=/tf_files/bottlenecks\
  --how_many_training_steps=100\
  --model_dir=/tf_files/ inception \
  --output_graph=/tf_files/retrained_graph.pb \
  --output_labels=/tf_files/retrained_labels.txt \
  --image_dir /tf_files/ct 

The 'ct' folder in question and giving me issues and has a stockpile of images. I have made sure that the folder does not have any other files in it, creating the issue of tensor not picking up the image first. Furthermore, I have ensured that each file has been converted to a jpg. I have no hyphens or dashes in the subfolders and they are all lowercased/ no spaces. 

Below are the following inputs that are giving me troubles. I have scoured the net for different answers to this problem and after troubleshooting the above mentioned attributes I still am finding the same error message incur. Thanks in advance. 

root@8c16ee553d5a:/tf_files# python retrain.py \
>   --bottleneck_dir=/tf_files/bottlenecks\
>   --how_many_training_steps=100\
>   --model_dir=/tf_files/ inception \
>   --output_graph=/tf_files/retrained_graph.pb \
>   --output_labels=/tf_files/retrained_labels.txt \
>   --image_dir /Users/maisiemullin/tf_files/ct 
2017-06-25 16:43:47.433755: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-06-25 16:43:47.443444: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-06-25 16:43:47.443724: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
Image directory '/Users/maisiemullin/tf_files/ct' not found.
Traceback (most recent call last):
  File "retrain.py", line 1062, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "retrain.py", line 784, in main
    class_count = len(image_lists.keys())
AttributeError: 'NoneType' object has no attribute 'keys'
root@8c16ee553d5a:/tf_files#

**Comment by ali01** [comment]
Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?  Make sure you also include the exact command if possible to produce  the output included in your test case. If you are unclear what to include  see the issue template displayed in  [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

 We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!

**Comment by wider2** [comment]
Good day for everyone
I have the same problem with the script on Windows 7

python retrain.py \
  --bottleneck_dir=/tf_files/bottlenecks \
  --how_many_training_steps=500 \
  --model_dir=/tf_files/inception \
  --summaries_dir=/tf_files/training_summaries
  --output_graph=/tf_files/retrained_graph.pb \
  --output_labels=/tf_files/retrained_labels.txt \
  --image_dir ???

"No valid folders or images found at"
I have tried different variants, but no successful results
  --image_dir d:\tfi\
  --image_dir c:/Users/Alexei/AppData/Local/Programs/Python/Python35/tf_files/bottles/
  --image_dir=/tf_files/bottles

**Comment by Phear210** [comment]
@wider2 

It seems as though you are attatching the directory for the binary bottleneck files and not your image files. It does not need to be an absolute path either, just ensure that if you 'cd' into the current directory that houses the folders. BE SURE to add within the folder you are adding to image_dir= to be filled with jpg.

**Comment by wider2** [comment]
thank you
the work with tensorflow model is very very tricky and need patience

**Comment by Phear210** [comment]
No problems! 

Tensorflow / AI classifiers are brand modalities and entail a deep level of python knowledge despite what many guides state. I believe it is possible for one to follow the guides without this dedicated knowledge but it becomes extremely tricky through certain steps. Glad to help!

**Comment by Phear210** [comment]
@ali01  

Thank you for your fast response. It is deeply appreciated! I have found a fix to the problem as within my custom retrain.py file I wrote an incorrect concated script that loads the image directories and processes them through - as i am currently trying a build that allows the retrain file to multi-classify instead of just binary classification. thanks again for the help.

**Comment by wider2** [comment]
here we go again
I have created model successfully
and got optimized model too

Python works successfully too (test image)
python label_image.py
 --graph=retrained_graph.pb
  --labels=retrained_labels.txt
  --image=hand2.jpg


I setup variables in android studio:
    private static final int INPUT_SIZE = 224;
    private static final int IMAGE_MEAN = 117;
    private static final float IMAGE_STD = 1f;

but when I run in Android, I have got this mistake:
E/TensorFlowInferenceInterface: Failed to run TensorFlow inference with inputs:[Mul], outputs:[final_result]
W/System.err: java.lang.IllegalArgumentException: computed output size would be negative

**Comment by wider2** [comment]
solution has ben found
I set these values, and application works more stable now
    private static final int INPUT_SIZE = 299;
    private static final int IMAGE_MEAN = 128;
    private static final float IMAGE_STD = 1f;

**Comment by tensorflowbutler** [comment]
This issue is automatically closed due to lack of activity. Please re-open if this is still an issue for you. Thanks!

**Comment by shahiduos14** [comment]
https://colab.research.google.com/drive/1hFte7dNUZGVukuR0OY02t0atJgMzn6oc#scrollTo=Bl-yFZqKeezp&forceEdit=true&offline=true&sandboxMode=true


**Step 0** 

Replace retrain.py with downloading file from following link and uploading it to same folder in Google drive.

https://raw.githubusercontent.com/tensorflow/hub/master/examples/image_retraining/retrain.py


**Step 1**

Go to this link : 

https://colab.research.google.com/drive/1hFte7dNUZGVukuR0OY02t0atJgMzn6oc#scrollTo=Bl-yFZqKeezp&forceEdit=true&offline=true&sandboxMode=true

**Step 2**

Go to chapter Two

**Step 3** 

**Worked by adding two lines as given following before the script section : LOL**

**It's a LOL that just added following two lines and it worked before script section and it worked.**

**Two Lines:**


    if not os.path.isdir("../Pokemons-subset"):
  
         print('Error')


**Script Section:**


     %run scripts/retrainn.py   \

       --bottleneck_dir=tf_files/bottlenecks   \

       --how_many_training_steps=4000   \

       --model_dir=tf_files/models/   \

       --summaries_dir=tf_files/training_summaries/mobilenet_0.50_160   \

       --output_graph=tf_files/retrained_graph.pb   \

       --output_labels=tf_files/retrained_labels.txt   \

       --learning_rate=0.01   \

       --architecture=mobilenet_0.50_160   \

       --image_dir=../Pokemons-subset \

       --flip_left_right \

       --random_crop=10 \

       --random_scale=10 \

       --random_brightness=10
