### ISSUE TITLE
ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'

### ISSUE THREAD

**Issue by dgovil** [tensorflow/tensorflow#11045]
### System information
- **custom code**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10 Pro 10.0.15063
- **TensorFlow installed from (source or binary)**: binary (pip)
- **TensorFlow version (use command below)**: tensorflow_gpu-1.2.0-cp36-cp36m-win_amd64.wh
- **CUDA/cuDNN version**: 8.0.6.1 / 8.0 
- **GPU model and memory**: Geforce 1080 Ti 11GB
- **Exact command to reproduce**: import tensorflow 

### Describe the problem
Importing tensorflow fails immediately on import with the following log.
I'm running Python 3.6.1 from Anaconda. I installed tensorflow-gpu with `pip install tensorflow-gpu`

I've installed the CUDA/cuDNN libraries per this guide: https://nitishmutha.github.io/tensorflow/2017/01/22/TensorFlow-with-gpu-for-windows.html

Not sure what I am missing here. Any help would be most appreciated!
Tensorflow CPU works great however. This seems limited to the GPU install.

Thank you in advance

### Source code / logs

```python
>>> import tensorflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\programdata\anaconda3\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "c:\programdata\anaconda3\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "c:\programdata\anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 52, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\ptpython\repl.py", line 117, in _execute
    code = compile_with_flags(line, 'eval')
  File "c:\programdata\anaconda3\lib\site-packages\ptpython\repl.py", line 105, in compile_with_flags
    dont_inherit=True)
  File "<stdin>", line 1
    import tensorflow
         ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "c:\programdata\anaconda3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 648, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 560, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "c:\programdata\anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 21, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "c:\programdata\anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 20, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow_internal')
  File "c:\programdata\anaconda3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\ptpython\repl.py", line 117, in _execute
    code = compile_with_flags(line, 'eval')
  File "c:\programdata\anaconda3\lib\site-packages\ptpython\repl.py", line 105, in compile_with_flags
    dont_inherit=True)
  File "<stdin>", line 1
    import tensorflow
         ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "c:\programdata\anaconda3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 648, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 560, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "c:\programdata\anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 21, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "c:\programdata\anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 20, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow_internal')
  File "c:\programdata\anaconda3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

```

**Comment by rohittavare** [comment]
I'm having the exact same problem on a late 2011 model mac book pro

**Comment by skye** [comment]
@martinwicke can you look at this or redirect? Thanks.

**Comment by martinwicke** [comment]
Yun, do you know what could be causing this behavior on Win10?

**Comment by RaymondY1213** [comment]
I encountered the same problem. Solved by add <path4cuDNN>/bin into PATH

**Comment by dgovil** [comment]
Which /bin would that be? The one under the cuda home path?

I will try that when I get home. Thanks.

**Comment by RaymondY1213** [comment]
under cuDNN path @dgovil

**Comment by dgovil** [comment]
Unfortunately that didn't work for me @RaymondY1213 . Thanks for the suggestion though.

Here's my current `PATH` sorted alphabetically for easier reading

```
['C:\\Program Files (x86)\\Common Files\\Intel\\Shared '
 'Libraries\\redist\\intel64\\compiler',
 'C:\\Program Files (x86)\\GtkSharp\\2.12\\bin',
 'C:\\Program Files (x86)\\Microsoft VS Code\\bin',
 'C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common',
 'C:\\Program Files (x86)\\Windows Kits\\10\\Windows Performance Toolkit\\',
 'C:\\Program Files (x86)\\Yarn\\bin',
 'C:\\Program Files\\CMake\\bin',
 'C:\\Program Files\\Docker\\Docker\\Resources\\bin',
 'C:\\Program Files\\Git\\cmd',
 'C:\\Program Files\\Microsoft SQL Server\\130\\Tools\\Binn\\',
 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v8.0\\bin',
 'C:\\Program Files\\NVIDIA GPU Computing '
 'Toolkit\\CUDA\\v8.0\\extras\\CUPTI\\libx64',
 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v8.0\\lib\\x64',
 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v8.0\\libnvvp',
 'C:\\Program Files\\Oculus\\Support\\oculus-runtime',
 'C:\\Program Files\\Rust stable GNU 1.18\\bin',
 'C:\\Program Files\\dotnet\\',
 'C:\\Program Files\\nodejs\\',
 'C:\\ProgramData\\Anaconda3',
 'C:\\ProgramData\\Anaconda3\\Library\\bin',
 'C:\\ProgramData\\Anaconda3\\Scripts',
 'C:\\ProgramData\\Anaconda3\\envs\\tf-gpu',
 'C:\\ProgramData\\Anaconda3\\envs\\tf-gpu\\Library\\bin',
 'C:\\ProgramData\\Anaconda3\\envs\\tf-gpu\\Library\\mingw-w64\\bin',
 'C:\\ProgramData\\Anaconda3\\envs\\tf-gpu\\Library\\usr\\bin',
 'C:\\ProgramData\\Anaconda3\\envs\\tf-gpu\\Scripts',
 'C:\\ProgramData\\chocolatey\\bin',
 'C:\\Users\\Dhruv\\.cargo\\bin',
 'C:\\Users\\Dhruv\\AppData\\Local\\Microsoft\\WindowsApps',
 'C:\\Users\\Dhruv\\AppData\\Local\\Yarn\\.bin',
 'C:\\Users\\Dhruv\\AppData\\Roaming\\npm',
 'C:\\WINDOWS',
 'C:\\WINDOWS\\System32\\Wbem',
 'C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\',
 'C:\\WINDOWS\\system32',
 'C:\\Windows',
 'C:\\Windows\\System32\\Wbem',
 'C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\',
 'C:\\Windows\\system32',
 'C:\\tools\\cmder',
 'C:\\tools\\cmder\\vendor\\conemu-maximus5',
 'C:\\tools\\cmder\\vendor\\conemu-maximus5\\ConEmu',
 'C:\\tools\\cmder\\vendor\\conemu-maximus5\\ConEmu\\Scripts',
 'c:\\programdata\\anaconda3\\Library\\bin']
```

**Comment by mopimoi** [comment]
Hello,

Any progress on this issue ? I'm having the same one on Windows 7 Pro.

Thank you in advance !

**Comment by meteorcloudy** [comment]
@dgovil @mopimoi I also believe this is a Path issue.
I have the following relevant path on my machine:
```
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\libnvvp
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\extras\CUPTI\libx64
C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
c:\tools\cuda\bin   # this is for cudnn64_6.dll
C:\Program Files\Anaconda3
C:\Program Files\Anaconda3\Scripts
C:\Program Files\Anaconda3\Library\bin
```

Can you please check if you have all corresponding directories in PATH?

**Comment by dgovil** [comment]
@meteorcloudy I've got all those paths in my PATH, with the exception of `c:\tools\cuda\bin` because that's all inside `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin`

I get this error still. It looks identical to me, but I'm just pasting it again in case there's anything of value here.

```python
>>> import tensorflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\programdata\anaconda3\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "c:\programdata\anaconda3\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "c:\programdata\anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 52, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\ptpython\repl.py", line 117, in _execute
    code = compile_with_flags(line, 'eval')
  File "c:\programdata\anaconda3\lib\site-packages\ptpython\repl.py", line 105, in compile_with_flags
    dont_inherit=True)
  File "<stdin>", line 1
    import tensorflow
         ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "c:\programdata\anaconda3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 648, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 560, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "c:\programdata\anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 21, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "c:\programdata\anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 20, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow_internal')
  File "c:\programdata\anaconda3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\ptpython\repl.py", line 117, in _execute
    code = compile_with_flags(line, 'eval')
  File "c:\programdata\anaconda3\lib\site-packages\ptpython\repl.py", line 105, in compile_with_flags
    dont_inherit=True)
  File "<stdin>", line 1
    import tensorflow
         ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "c:\programdata\anaconda3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 648, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 560, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "c:\programdata\anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 21, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "c:\programdata\anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 20, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow_internal')
  File "c:\programdata\anaconda3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

**Comment by meteorcloudy** [comment]
Hmm,, this looks strange. What version of cudnn do you have? Is there a `cudnn64_6.dll` under  `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin` ?

**Comment by dgovil** [comment]
@meteorcloudy I have cudnn-8.0-windows10-x64-v6.0

**Comment by suissemaxx** [comment]
Same problems here. Did anyone find a solution to this?

**Comment by dgovil** [comment]
Hi,
I just wanted to update this ticket.

With the exact same setup as before, I've installed tensorflow-gpu 1.3.0 and it works properly.
Maybe it was an incompatibility with tensorflow 1.2, but anyway just wanted to update the ticket for anyone else hitting it.
