### ISSUE TITLE
Keras load model raises ValueError when loading optimizer weights

### ISSUE THREAD

**Issue by kevinjos** [tensorflow/tensorflow#11055]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: I extended models_test.py to reproduce the bug
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Debian 8.8
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: ('v1.2.0-1106-g1f82b7a', '1.2.0')
- **Bazel version (if compiling from source)**: 0.5.1
- **CUDA/cuDNN version**: 8.0/6.0
- **GPU model and memory**: nvidia Tesla K-80 / 11.17gb
- **Exact command to reproduce**: See test in PR

### Describe the problem
Upon calling keras.models.load_model(fn) against a file generated by keras.models.save_model() a ValueError is raised. I believe it could be related to using padding='same' in the Conv2D layer.

Traceback (most recent call last):
  File "models_test.py", line 166, in test_saving_cnn
    model = keras.models.load_model(fname)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/keras/python/keras/models.py", line 316, in load_model
    model.optimizer.set_weights(optimizer_weight_values)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/keras/python/keras/optimizers.py", line 95, in set_weights
    'provided weight shape ' + str(w.shape))
ValueError: Optimizer weight shape (512,) not compatible with provided weight shape (64,)

### Source code / logs
Please see PR below.

**Comment by kevinjos** [comment]
The test I wrote here https://github.com/tensorflow/tensorflow/pull/11056 reproduces the model deserialization glitch.

Similar issues have been discussed quite a bit in the Keras repo. I haven't seen a comprehensive solution, only workarounds. I wasn't sure if this should be reported here or there, but since I am using the tensorflow packaged Keras and I wrote the test in the tensorflow test-cases I thought to raise the issue here.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @fchollet: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @fchollet: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @fchollet: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @fchollet: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @fchollet: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @fchollet: It has been 333 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @fchollet: It has been 348 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @fchollet: It has been 363 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @fchollet: It has been 378 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @fchollet: It has been 393 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @fchollet: It has been 408 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @fchollet: It has been 423 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @fchollet: It has been 438 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @fchollet: It has been 453 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by dksb** [comment]
As mentioned in the PR, it is better to be asked as a Keras issue. Since this is old, this issue might have already been resolved. If not, please create an issue for the Keras team.
