### ISSUE TITLE
TensorFlow 1.2.0 depends on a 5 year old release of the Markdown package

### ISSUE THREAD

**Issue by ValdemarOrn** [tensorflow/tensorflow#11063]
### System information

- This is an installation problem
- Windows 10 64 bit
- Tensorflow installed from pip
- Version 1.2.0
- Bazel version: None
- CUDA v8 CuDNN v6
- GTX980Ti and Pascal TITAN X
- python -m pip install tensorflow-gpu==1.2.0

### Describe the problem

TensorFlow 1.2.0 has added a new dependency on the markdown==2.2.0 package. This package is being actively maintained, and the latest version of it is 2.6.8. However, Tensorflow 1.2.0 has a strict dependency on version 2.2.0, which was released July 2012; almost 5 years ago. As such, the package no longer installs cleanly on all modern distributions of python.

I am attempting to use the Windows python-3.6.1-embed-amd64 release, but when attempting to install either Tensorflow==1.2.0 or markdown==2.2.0 on this environment, installation fails due to a syntax issue in the Markdown package. I haven't delved deep into the issue, but have included log output from trying to use pip to install tensorflow on this system.

However, the most recent version of markdown 2.6.8 installs fine under this environment.

Is there a good reason for why Tensorflow specifically requires the old version? Can the dependency be upgraded to a later version that will support the embedded 3.6.1 Windows release of python?

Surely taking on a legacy dependency like this is not ideal, and should hopefully be fixed.

### Source code / logs

```
C:\Users\Valdemar\Downloads\python-3.6.1-embed-amd64>python -m pip install tensorflow==1.2.0
Collecting tensorflow==1.2.0
  Using cached tensorflow-1.2.0-cp36-cp36m-win_amd64.whl
Requirement already satisfied: six>=1.10.0 in c:\users\valdemar\downloads\python-3.6.1-embed-amd64\lib\site-packages (from tensorflow==1.2.0)
Requirement already satisfied: protobuf>=3.2.0 in c:\users\valdemar\downloads\python-3.6.1-embed-amd64\lib\site-packages (from tensorflow==1.2.0)
Collecting numpy>=1.11.0 (from tensorflow==1.2.0)
  Using cached numpy-1.13.0-cp36-none-win_amd64.whl
Requirement already satisfied: html5lib==0.9999999 in c:\users\valdemar\downloads\python-3.6.1-embed-amd64\lib\site-packages (from tensorflow==1.2.0)
Collecting werkzeug>=0.11.10 (from tensorflow==1.2.0)
  Using cached Werkzeug-0.12.2-py2.py3-none-any.whl
Collecting markdown==2.2.0 (from tensorflow==1.2.0)
  Using cached Markdown-2.2.0.tar.gz
Collecting backports.weakref==1.0rc1 (from tensorflow==1.2.0)
  Using cached backports.weakref-1.0rc1-py3-none-any.whl
Requirement already satisfied: bleach==1.5.0 in c:\users\valdemar\downloads\python-3.6.1-embed-amd64\lib\site-packages (from tensorflow==1.2.0)
Requirement already satisfied: wheel>=0.26 in c:\users\valdemar\downloads\python-3.6.1-embed-amd64\lib\site-packages (from tensorflow==1.2.0)
Requirement already satisfied: setuptools in c:\users\valdemar\downloads\python-3.6.1-embed-amd64\lib\site-packages (from protobuf>=3.2.0->tensorflow==1.2.0)
Building wheels for collected packages: markdown
  Running setup.py bdist_wheel for markdown ... error
  Complete output from command C:\Users\Valdemar\Downloads\python-3.6.1-embed-amd64\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Valdemar\\AppData\\Local\\Temp\\pip-build-9rmoawj8\\markdown\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\Valdemar\AppData\Local\Temp\tmpeowqyarkpip-wheel- --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib
  creating build\lib\markdown
  copying markdown\blockparser.py -> build\lib\markdown
  copying markdown\blockprocessors.py -> build\lib\markdown
  copying markdown\etree_loader.py -> build\lib\markdown
  copying markdown\inlinepatterns.py -> build\lib\markdown
  copying markdown\odict.py -> build\lib\markdown
  copying markdown\postprocessors.py -> build\lib\markdown
  copying markdown\preprocessors.py -> build\lib\markdown
  copying markdown\serializers.py -> build\lib\markdown
  copying markdown\treeprocessors.py -> build\lib\markdown
  copying markdown\util.py -> build\lib\markdown
  copying markdown\__init__.py -> build\lib\markdown
  copying markdown\__main__.py -> build\lib\markdown
  creating build\lib\markdown\extensions
  copying markdown\extensions\abbr.py -> build\lib\markdown\extensions
  copying markdown\extensions\attr_list.py -> build\lib\markdown\extensions
  copying markdown\extensions\codehilite.py -> build\lib\markdown\extensions
  copying markdown\extensions\def_list.py -> build\lib\markdown\extensions
  copying markdown\extensions\extra.py -> build\lib\markdown\extensions
  copying markdown\extensions\fenced_code.py -> build\lib\markdown\extensions
  copying markdown\extensions\footnotes.py -> build\lib\markdown\extensions
  copying markdown\extensions\headerid.py -> build\lib\markdown\extensions
  copying markdown\extensions\html_tidy.py -> build\lib\markdown\extensions
  copying markdown\extensions\meta.py -> build\lib\markdown\extensions
  copying markdown\extensions\nl2br.py -> build\lib\markdown\extensions
  copying markdown\extensions\rss.py -> build\lib\markdown\extensions
  copying markdown\extensions\sane_lists.py -> build\lib\markdown\extensions
  copying markdown\extensions\smart_strong.py -> build\lib\markdown\extensions
  copying markdown\extensions\tables.py -> build\lib\markdown\extensions
  copying markdown\extensions\toc.py -> build\lib\markdown\extensions
  copying markdown\extensions\wikilinks.py -> build\lib\markdown\extensions
  copying markdown\extensions\__init__.py -> build\lib\markdown\extensions
  running build_scripts
  creating build\scripts-3.6
  copying and adjusting bin\markdown_py -> build\scripts-3.6
  running build_docs
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\Valdemar\AppData\Local\Temp\pip-build-9rmoawj8\markdown\setup.py", line 208, in <module>
      setup(**data)
    File "distutils\core.py", line 148, in setup
    File "distutils\dist.py", line 955, in run_commands
    File "distutils\dist.py", line 974, in run_command
    File "C:\Users\Valdemar\Downloads\python-3.6.1-embed-amd64\lib\site-packages\wheel\bdist_wheel.py", line 179, in run
      self.run_command('build')
    File "distutils\cmd.py", line 313, in run_command
    File "distutils\dist.py", line 974, in run_command
    File "distutils\command\build.py", line 135, in run
    File "distutils\cmd.py", line 313, in run_command
    File "distutils\dist.py", line 974, in run_command
    File "C:\Users\Valdemar\AppData\Local\Temp\pip-build-9rmoawj8\markdown\setup.py", line 125, in run
      import markdown
    File "build\lib\markdown\__init__.py", line 213
      except AttributeError, e:
                           ^
  SyntaxError: invalid syntax

  ----------------------------------------
  Failed building wheel for markdown
  Running setup.py clean for markdown
Failed to build markdown
Installing collected packages: numpy, werkzeug, markdown, backports.weakref, tensorflow
  Running setup.py install for markdown ... error
    Complete output from command C:\Users\Valdemar\Downloads\python-3.6.1-embed-amd64\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Valdemar\\AppData\\Local\\Temp\\pip-build-9rmoawj8\\markdown\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Valdemar\AppData\Local\Temp\pip-6zhxvaeg-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib
    creating build\lib\markdown
    copying markdown\blockparser.py -> build\lib\markdown
    copying markdown\blockprocessors.py -> build\lib\markdown
    copying markdown\etree_loader.py -> build\lib\markdown
    copying markdown\inlinepatterns.py -> build\lib\markdown
    copying markdown\odict.py -> build\lib\markdown
    copying markdown\postprocessors.py -> build\lib\markdown
    copying markdown\preprocessors.py -> build\lib\markdown
    copying markdown\serializers.py -> build\lib\markdown
    copying markdown\treeprocessors.py -> build\lib\markdown
    copying markdown\util.py -> build\lib\markdown
    copying markdown\__init__.py -> build\lib\markdown
    copying markdown\__main__.py -> build\lib\markdown
    creating build\lib\markdown\extensions
    copying markdown\extensions\abbr.py -> build\lib\markdown\extensions
    copying markdown\extensions\attr_list.py -> build\lib\markdown\extensions
    copying markdown\extensions\codehilite.py -> build\lib\markdown\extensions
    copying markdown\extensions\def_list.py -> build\lib\markdown\extensions
    copying markdown\extensions\extra.py -> build\lib\markdown\extensions
    copying markdown\extensions\fenced_code.py -> build\lib\markdown\extensions
    copying markdown\extensions\footnotes.py -> build\lib\markdown\extensions
    copying markdown\extensions\headerid.py -> build\lib\markdown\extensions
    copying markdown\extensions\html_tidy.py -> build\lib\markdown\extensions
    copying markdown\extensions\meta.py -> build\lib\markdown\extensions
    copying markdown\extensions\nl2br.py -> build\lib\markdown\extensions
    copying markdown\extensions\rss.py -> build\lib\markdown\extensions
    copying markdown\extensions\sane_lists.py -> build\lib\markdown\extensions
    copying markdown\extensions\smart_strong.py -> build\lib\markdown\extensions
    copying markdown\extensions\tables.py -> build\lib\markdown\extensions
    copying markdown\extensions\toc.py -> build\lib\markdown\extensions
    copying markdown\extensions\wikilinks.py -> build\lib\markdown\extensions
    copying markdown\extensions\__init__.py -> build\lib\markdown\extensions
    running build_scripts
    creating build\scripts-3.6
    copying and adjusting bin\markdown_py -> build\scripts-3.6
    running build_docs
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Valdemar\AppData\Local\Temp\pip-build-9rmoawj8\markdown\setup.py", line 208, in <module>
        setup(**data)
      File "distutils\core.py", line 148, in setup
      File "distutils\dist.py", line 955, in run_commands
      File "distutils\dist.py", line 974, in run_command
      File "C:\Users\Valdemar\Downloads\python-3.6.1-embed-amd64\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "distutils\command\install.py", line 545, in run
      File "distutils\cmd.py", line 313, in run_command
      File "distutils\dist.py", line 974, in run_command
      File "distutils\command\build.py", line 135, in run
      File "distutils\cmd.py", line 313, in run_command
      File "distutils\dist.py", line 974, in run_command
      File "C:\Users\Valdemar\AppData\Local\Temp\pip-build-9rmoawj8\markdown\setup.py", line 125, in run
        import markdown
      File "build\lib\markdown\__init__.py", line 213
        except AttributeError, e:
                             ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "C:\Users\Valdemar\Downloads\python-3.6.1-embed-amd64\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Valdemar\\AppData\\Local\\Temp\\pip-build-9rmoawj8\\markdown\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Valdemar\AppData\Local\Temp\pip-6zhxvaeg-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Valdemar\AppData\Local\Temp\pip-build-9rmoawj8\markdown\

C:\Users\Valdemar\Downloads\python-3.6.1-embed-amd64>
```

**Comment by aselle** [comment]
@gunan, PTAL.

**Comment by gunan** [comment]
markdown is a dependency of tensorboard. Tensorboard has moved to a new repository, and at head should be handled differently.
@dandelionmane @jart 
What do you recommend for 1.2 release?

**Comment by dandelionmane** [comment]
Indeed, as of 1.3 and onwards TF won't have a markdown dependency, just TensorBoard. However, that won't directly fix the issue, as it's failing during pip install - and TensorFlow will list TB as a dependency, meaning that pip install will still fail. We need to fix https://github.com/tensorflow/tensorboard/issues/43.

For the 1.2 release - if you want to make a patch release, it wouldn't be hard to make a new pip package with the strict version pinning removed. Just change the https://github.com/tensorflow/tensorflow/blob/r1.2/tensorflow/tools/pip_package/setup.py#L40 to '>= 2.6.8'. Unit tests cover all the markdown functionality we need, so regressions are not too big a concern.

**Comment by gunan** [comment]
@av8ramit I think we should make a patch release with this.
Could you make the change in release branch, and release 1.2.1?

**Comment by av8ramit** [comment]
@gunan sure sounds good, I'll get started.

**Comment by av8ramit** [comment]
1.2.1 was released and fixes this issue: https://github.com/tensorflow/tensorflow/commit/8695d596385e754159af5a1f0ae0676163bc73bb#diff-739fc4f018f5288972ae5826b15c36e7
