### ISSUE TITLE
error running object_detection samples TypeError: unorderable types: tuple() < str()

### ISSUE THREAD

**Issue by ckalas** [tensorflow/tensorflow#11078]
I cannot run any of the examples from the new object detection api. I followed the documented "prepare inputs" and "run locally", but when I run the below command I get the following error.

`python3 train.py --pipeline_config_path=/home/chris/tensorflow/models/object_detection/samples/configs/ssd_inception_v2_pets.config --train_dir=.
`
`Traceback (most recent call last):
  File "train.py", line 199, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train.py", line 195, in main
    worker_job_name, is_chief, FLAGS.train_dir)
  File "/home/chris/tensorflow/models/object_detection/trainer.py", line 184, in train
    data_augmentation_options)
  File "/home/chris/tensorflow/models/object_detection/trainer.py", line 77, in _create_input_queue
    prefetch_queue_capacity=prefetch_queue_capacity)
  File "/home/chris/tensorflow/models/object_detection/core/batcher.py", line 93, in __init__
    num_threads=num_batch_queue_threads)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/input.py", line 924, in batch
    name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/input.py", line 698, in _batch
    tensor_list = _as_tensor_list(tensors)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/input.py", line 386, in _as_tensor_list
    return [tensors[k] for k in sorted(tensors)]
TypeError: unorderable types: tuple() < str()
`

I get the feeling this error is because it isn't processing the record file correctly, or something along those lines is wrong. However, as far as I can tell, I followed everything correctly. I edited the paths in the config file and triple checked that they point to real files.

**Comment by apockill** [comment]
I am also having this exact issue on python 3 with tensorflow for GPU. I might be making a mistake somewhere along as well, though.

**Comment by apockill** [comment]
To add to this, I found that their trainer_test.py code also fails because of this issue, leading me to think there's more going on here:

python trainer_test.py 
E.
======================================================================
ERROR: test_configure_trainer_and_train_two_steps (__main__.TrainerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "trainer_test.py", line 201, in test_configure_trainer_and_train_two_steps
    train_dir=train_dir)
  File "/home/alex/workspace/models-master/object_detection/trainer.py", line 184, in train
    data_augmentation_options)
  File "/home/alex/workspace/models-master/object_detection/trainer.py", line 77, in _create_input_queue
    prefetch_queue_capacity=prefetch_queue_capacity)
  File "/home/alex/workspace/models-master/object_detection/core/batcher.py", line 94, in __init__
    num_threads=num_batch_queue_threads)
  File "/home/alex/.virtualenvs/tens2/lib/python3.5/site-packages/tensorflow/python/training/input.py", line 920, in batch
    name=name)
  File "/home/alex/.virtualenvs/tens2/lib/python3.5/site-packages/tensorflow/python/training/input.py", line 698, in _batch
    tensor_list = _as_tensor_list(tensors)
  File "/home/alex/.virtualenvs/tens2/lib/python3.5/site-packages/tensorflow/python/training/input.py", line 385, in _as_tensor_list
    return [tensors[k] for k in sorted(tensors)]
TypeError: unorderable types: tuple() < str()

----------------------------------------------------------------------
Ran 2 tests in 0.019s

FAILED (errors=1)

**Comment by MetaPeak** [comment]
I used pascal voc 2007 with python3.5, it had the same problem as you mentioned. However, I can run the the same model in python2.7 correctly. Maybe it is the problem of python version compatibility.

**Comment by rajeevraibhatia** [comment]
I'm getting the same error with Python 3.6.1. How can we fix this ?

**Comment by MetaPeak** [comment]
@rajatmonga  You can try python 2.7 to train your model, if you are hurry. It works.

**Comment by apockill** [comment]
Hi guys, I was able to fix this with info from [this](https://github.com/tensorflow/models/pull/1610) thread. Hopefully this gets fixed in the next release, but it'll work for now.

**Comment by ckalas** [comment]
I did this too, but for python 3 you need items() instead of iteritems(). Now it is complaining about not finding a model checkpoint
