### ISSUE TITLE
Python checkpoint to use with C++

### ISSUE THREAD

**Issue by hondaathma** [tensorflow/tensorflow#11093]
I have tried everything from freeze_graph.py to bazel  to try and use a python trained saved checkpoint of a model in c++.

Why is it so complicated in TF?Caffe was so much easier.!!

These are the steps that I follow:

1)While training I added the following line just before saving each checkpoint :  
tf.train.write_graph(sess.graph_def, 'modelsprototxt/', 'trainingmodel.pb', as_text=True)

2)I used freeze_graphy.py to send in a trained checkpoint file,the written graph fle and the output graph file and I get the following error:

Traceback (most recent call last):
  File "/home/anarayanan/TenserflowPlayground/TF_DEEPLAB_UNTOUCHED/tensorflow-deeplab-resnet-master/freeze_graph.py", line 175, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/anarayanan/TenserflowPlayground/TF_DEEPLAB_UNTOUCHED/tensorflow-deeplab-resnet-master/freeze_graph.py", line 172, in main
    FLAGS.output_graph, FLAGS.clear_devices)
  File "/home/anarayanan/TenserflowPlayground/TF_DEEPLAB_UNTOUCHED/tensorflow-deeplab-resnet-master/freeze_graph.py", line 115, in freeze_graph
    text_format.Merge(f.read(), input_graph_def)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 476, in Merge
    descriptor_pool=descriptor_pool)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 526, in MergeLines
    return parser.MergeLines(lines, message)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 559, in MergeLines
    self._ParseOrMerge(lines, message)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 574, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 619, in _MergeField
    name = tokenizer.ConsumeIdentifierOrNumber()
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 1066, in ConsumeIdentifierOrNumber
    raise self.ParseError('Expected identifier or number.')
google.protobuf.text_format.ParseError: 2:1 : Expected identifier or number.

Can someone please help me understand where the error is coming from?

**Comment by asimshankar** [comment]
I apologize but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new) . Please provide all the information it asks. Thank you.

(In particular, it isn't clear to me how you're invoking the `freeze_graph` tool, which version of TensorFlow and the tools is being used etc. Detailed instructions on reproducing the problem will be very helpful in being able to diagnose the problem. You may also want to see https://stackoverflow.com/questions/44724700/using-tensorflow-checkpoint-to-restore-model-in-c/44726029#44726029 )

**Comment by tensorflowbutler** [comment]
This issue is automatically closed due to lack of activity. Please re-open if this is still an issue for you. Thanks!
