### ISSUE TITLE
Quantization causes some operations to be missing in the graph?

### ISSUE THREAD

**Issue by kwotsin** [tensorflow/tensorflow#11142]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: Source
- **TensorFlow version (use command below)**: 1.2.1
- **Bazel version (if compiling from source)**: 5.4
- **CUDA/cuDNN version**: 8.0.61, 5.1
- **GPU model and memory**: Titan X Pascal

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.
I am currently trying to evaluate the performance of a quantized imagenet pretrained models based on what is available from TF-slim. For my inception models, the quantization works ok (except that if we use quantize_nodes, the performance becomes 20x worse and accuracy drops. Totally the opposite of what we want). However, for the resnet and VGG architectures, it gave me this error:

```
Traceback (most recent call last):
  File "evaluate_from_pb.py", line 82, in <module>
    tf.import_graph_def(graph_def)
  File "/home/kwotsin/.local/lib/python2.7/site-packages/tensorflow/python/framework/importer.py", line 331, in import_graph_def
    op_to_bind_to, node.name))
ValueError: Specified colocation to an op that does not exist during import: ToFloat_2 in cond/truediv/Switch

```

Which I did not encounter when evaluating my quantized inception models. I am suspecting this might be due to a conversion error during quantization that does not work for some operations that are contained within the VGG_16 and resnet_v1_50 architectures, as defined here:

VGG_16: https://github.com/tensorflow/models/blob/master/slim/nets/vgg.py#L131
Resnet_v1_50: https://github.com/tensorflow/models/blob/master/slim/nets/resnet_v1.py#L241

Yet, due to the limited error traceback produced, I can't seem to identify what went wrong. Because the op name is very strange - something I never named or seen in the model's definition, I suspect it is a quantization op. I don't really know how to reproduce or find this op if I cannot import my graph_def to analyze the graph variables at all.

Thank you.

**Comment by cy89** [comment]
@kwotsin would you please add the sequence of commands you issued to get the error?

**Comment by tensorflowbutler** [comment]
This issue is automatically closed due to lack of activity. Please re-open if this is still an issue for you. Thanks!

**Comment by tensorflowbutler** [comment]
This issue is automatically closed due to lack of activity. Please re-open if this is still an issue for you. Thanks!
