### ISSUE TITLE
Error while executing the imagenet_train model

### ISSUE THREAD

**Issue by cryptox31** [tensorflow/tensorflow#11141]
# bazel-bin/inception/imagenet_train --num_gpus=4 --batch_size=256 --train_dir=/tmp --data_dir=/root/kits/dataset
Traceback (most recent call last):
  File "/root/models/inception/bazel-bin/inception/imagenet_train.runfiles/inception/inception/imagenet_train.py", line 41, in <module>
    tf.app.run()
  File "/root/anaconda2/envs/tensor/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/root/models/inception/bazel-bin/inception/imagenet_train.runfiles/inception/inception/imagenet_train.py", line 37, in main
    inception_train.train(dataset)
  File "/root/models/inception/bazel-bin/inception/imagenet_train.runfiles/inception/inception/inception_train.py", line 217, in train
    num_preprocess_threads=num_preprocess_threads)
  File "/root/models/inception/bazel-bin/inception/imagenet_train.runfiles/inception/inception/image_processing.py", line 136, in distorted_inputs
    num_readers=FLAGS.num_readers)
  File "/root/models/inception/bazel-bin/inception/imagenet_train.runfiles/inception/inception/image_processing.py", line 490, in batch_inputs
    example_serialized)
  File "/root/models/inception/bazel-bin/inception/imagenet_train.runfiles/inception/inception/image_processing.py", line 397, in parse_example_proto
    bbox = tf.concat(0, [ymin, xmin, ymax, xmax])
  File "/root/anaconda2/envs/tensor/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 1029, in concat
    dtype=dtypes.int32).get_shape(
  File "/root/anaconda2/envs/tensor/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 639, in convert_to_tensor
    as_ref=False)
  File "/root/anaconda2/envs/tensor/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 704, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/root/anaconda2/envs/tensor/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 113, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/root/anaconda2/envs/tensor/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 102, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/root/anaconda2/envs/tensor/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py", line 370, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/root/anaconda2/envs/tensor/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py", line 302, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got list containing Tensors of type '_Message' instead.

Using Tensorflow 1.1 inside Anaconda
Python version 3.6.1
Machine - Power 8
OS - Ubuntu 16.04

**Can someone tell me why am I getting this error?**

**Comment by skye** [comment]
Did you mean to file this in https://github.com/tensorflow/models?

**Comment by hyperdo** [comment]
Have you tried the solutions previously posted in these issues:
- https://github.com/tensorflow/tensorflow/issues/8267
- https://github.com/tensorflow/tensorflow/issues/8267

**Comment by cryptox31** [comment]
@skye yes, that is the file.

**Comment by cryptox31** [comment]
I have re-installed tensorflow=1.0.1 and it gave me the same error. But this time I installed it without anaconda environment and with python2.7.
Further, I came across that the the tensorflow api has changed and so I had to do a 
`git checkout master` 
in /models/ directory 
and this worked.
