### ISSUE TITLE
Train a classifier error tensorflow.python.framework.errors_impl.NotFoundError:

### ISSUE THREAD

**Issue by bagueti** [tensorflow/tensorflow#11151]
I train my classifier, but when I'm going to rate an image this error appears:

root@e7bfbff82a10:/tf_files# python label_image.py new/maca/2Q==.jpg
Traceback (most recent call last):
  File "label_image.py", line 11, in <module>
    image_data = tf.gfile.FastGFile(image_path, 'rb').read()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 115, in read
    self._preread_check()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 75, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.NotFoundError: new/maca/2Q==.jpg

I follow all steps of code lab TensorFlow for poets, but I still have this problem.

**Comment by skye** [comment]
Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?  Make sure you also include the exact command if possible to produce  the output included in your test case. If you are unclear what to include  see the issue template displayed in  [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

 We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!

**Comment by tensorflowbutler** [comment]
This issue is automatically closed due to lack of activity. Please re-open if this is still an issue for you. Thanks!

**Comment by tensorflowbutler** [comment]
This issue is automatically closed due to lack of activity. Please re-open if this is still an issue for you. Thanks!
