### ISSUE TITLE
Expected one attr with name u'T' in name: "swap_out_d_0"

### ISSUE THREAD

**Issue by abenmao** [tensorflow/tensorflow#11163]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: r1.2
- **Python version**: 2.7
- **Bazel version (if compiling from source)**: 0.4.5
- **CUDA/cuDNN version**: CUDA8.0
- **GPU model and memory**:  Tesla P100, 16GB

### Describe the problem
I used OptimizeGraph API in Grappler for inserting "swap_to_host" nodes in my graph. When I import the new graph_def generated from this API, I got error mesage: "Expected one attr with name u'T' in swap_out_d_0." I think the new graph_def misses some attribute information.
I am following this bug and handing on fixing it.

### Source code / logs
source code:

```python
d.op.node_def.attr['_swap_to_host'].i = 0
mg = meta_graph.create_meta_graph_def(graph=ops.get_default_graph())
graph = tf_optimizer.OptimizeGraph(rewriter_config, mg)
tf.import_graph_def(graph)
```
log:

```python
Traceback (most recent call last):
  File "memory_optimizer_test.py", line 62, in testSimpleSwap
    tf.import_graph_def(graph)
  File "/home/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/importer.py", line 307, in import_graph_def
    output_types = _OutputTypes(node, op_dict)
  File "/home/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/importer.py", line 83, in _OutputTypes
    return _ArgsToTypes(node_def, op_def.output_arg)
  File "/home/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/importer.py", line 72, in _ArgsToTypes
    types.extend(_SingleArgToTypes(node_def, arg_def))
  File "/home/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/importer.py", line 63, in _SingleArgToTypes
    types = _ArgToTypesNoRef(node_def, arg_def)
  File "/home/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/importer.py", line 54, in _ArgToTypesNoRef
    return [_GetNodeAttr(node_def, arg_def.type_attr).type]
  File "/home/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/importer.py", line 40, in _GetNodeAttr
    % (attr_name, str(node_def)))
ValueError: Expected one attr with name u'T' in name: "swap_out_d_0"
op: "Identity"
input: "b"
device: "/CPU"
.
```

**Comment by Orion34C** [comment]
I have encountered the same problem. Any solution?

**Comment by andydavis1** [comment]
@benoitsteiner can you look at the bug fix #11283?

**Comment by yangjunpro** [comment]
@benoitsteiner can you please take a look at this fix? We have made this fix and waited for code review for about one week.

Thanks.

**Comment by benoitsteiner** [comment]
Sorry for the delay, I have been away on vacation. The fix looks good, we should be able to merge it soon.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
A member of the TensorFlow organization has replied after the stat:awaiting tensorflower label was applied.

**Comment by tatatodd** [comment]
Closing this out since #11283 was merged long ago.
