### ISSUE TITLE
ConnectionError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /tensorflow/linux/gpu/tensorflow_gpu-1.2.1-cp27-none-linux_x86_64.whl (Caused by <class 'socket.error'>: [Errno 101] Network is unreachable)

### ISSUE THREAD

**Issue by supriyalk** [tensorflow/tensorflow#11183]
I have downloaded and removed Tensorflow a few times in order to try and fix a problems with my numpy package. I now get the error above when I try and download tensorflow. Is there a max amount of times I can download it, is that why I am getting this error? 

Here is the traceback: 
Exception:
Traceback (most recent call last):
  File "/home/slkapur/tensorflow/local/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/home/slkapur/tensorflow/local/lib/python2.7/site-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/home/slkapur/tensorflow/local/lib/python2.7/site-packages/pip/req.py", line 1197, in prepare_files
    do_download,
  File "/home/slkapur/tensorflow/local/lib/python2.7/site-packages/pip/req.py", line 1375, in unpack_url
    self.session,
  File "/home/slkapur/tensorflow/local/lib/python2.7/site-packages/pip/download.py", line 546, in unpack_http_url
    resp = session.get(target_url, stream=True)
  File "/home/slkapur/tensorflow/local/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 395, in get
    return self.request('GET', url, **kwargs)
  File "/home/slkapur/tensorflow/local/lib/python2.7/site-packages/pip/download.py", line 237, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/home/slkapur/tensorflow/local/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 383, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/slkapur/tensorflow/local/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 486, in send
    r = adapter.send(request, **kwargs)
  File "/home/slkapur/tensorflow/local/lib/python2.7/site-packages/pip/_vendor/requests/adapters.py", line 378, in send
    raise ConnectionError(e)
ConnectionError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /tensorflow/linux/cpu/tensorflow-1.2.1-cp27-none-linux_x86_64.whl (Caused by <class 'socket.error'>: [Errno 101] Network is unreachable)
 
Storing debug log for failure in /tmp/tmp2du06v

**Comment by cy89** [comment]
There shouldn't be a retry limit. 

In the meantime, can you tell us exactly what you're doing, with the usual template: 

Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?  Make sure you also include the exact command if possible to produce  the output included in your test case. If you are unclear what to include  see the issue template displayed in  [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

 We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!

**Comment by tensorflowbutler** [comment]
This issue is automatically closed due to lack of activity. Please re-open if this is still an issue for you. Thanks!
