### ISSUE TITLE
error in freeze_graph.py

### ISSUE THREAD

**Issue by azadef** [tensorflow/tensorflow#11248]
### System information
Ubuntu 16.04
Python 2.7.12
Tensorflow 1.2.1 installed using pip
GPU: Nvidia Quadro M2000M 4GB
CUDA V 8.0.4

### Issue
I am trying to recreate the frozen graph using freeze_graph.py from the ssd_mobilenet pretrained model available here:

https://github.com/tensorflow/models/blob/master/object_detection/g3doc/detection_model_zoo.md

I printed the output nodes using the following command:

`for n in detection_graph.as_graph_def().node:`
`    print(n.name)`

I tried running freeze_graph with different output_nodes such as add_6, Postprocessor/BatchMultiClassNonMaxSuppression/stack with following command:

freeze_graph.py --input_graph=ssd_mobilenet_v1_coco/graph.pbtxt --input_checkpoint=ssd_mobilenet_v1_coco/model.ckpt --output_graph=./frozen_graph.pb --output_node_names=add_6

This is the error that I get:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/tools/freeze_graph.py", line 202, in <module>
    app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/home/adminloc/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/tools/freeze_graph.py", line 134, in main
    FLAGS.variable_names_blacklist)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/tools/freeze_graph.py", line 99, in freeze_graph
    _ = importer.import_graph_def(input_graph_def, name="")
  File "/home/adminloc/.local/lib/python2.7/site-packages/tensorflow/python/framework/importer.py", line 283, in import_graph_def
    raise ValueError('No op named %s in defined operations.' % node.op)
ValueError: No op named SSTableReaderV2 in defined operations.

When I try feeding the old frozen_graph (.pb file) as --input_graph with --input_binary=true to freeze_graph, I get the following error:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/tools/freeze_graph.py", line 202, in <module>
    app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/home/adminloc/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/tools/freeze_graph.py", line 134, in main
    FLAGS.variable_names_blacklist)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/tools/freeze_graph.py", line 112, in freeze_graph
    sess.run([restore_op_name], {filename_tensor_name: input_checkpoint})
  File "/home/adminloc/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/home/adminloc/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 945, in _run
    + e.args[0])
TypeError: Cannot interpret feed_dict key as Tensor: The name 'save/Const:0' refers to a Tensor which does not exist. The operation, 'save/Const', does not exist in the graph.

I don't know if this is a bug or lack of documentation, but it would be nice to add some documentation such as the output nodes.

P.S: I am trying to recreate the frozen graph to be able to create a new frozen graph after fine tuning the model.

**Comment by azadef** [comment]
The problem is solved, I used export_inference_graph from object_detection using this command:

`python export_inference_graph \
    --input_type image_tensor \
    --pipeline_config_path path/to/ssd_mobilenets_coco.config \
    --checkpoint_path path/to/model-ckpt \
    --inference_graph_path path/to/inference_graph.pb`

I had to make a new config file for coco, I used ssd_mobilenets_pets and changed the num_classes to 90 as in coco and it exported the frozen graph without any error.
