### ISSUE TITLE
label_image example does not work with Mobilenetv1 (224)

### ISSUE THREAD

**Issue by vade** [tensorflow/tensorflow#11250]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No.
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Mac OS X 10.12.5
- **TensorFlow installed from (source or binary)**:
Source
- **TensorFlow version (use command below)**:
Github tag 1.2 release
- **Python version**: 
2.7 (Mac OS X System install)
- **Bazel version (if compiling from source)**:
Homebrew 0.4.5
- **CUDA/cuDNN version**:
NA
- **GPU model and memory**:
NA

- **Exact command to reproduce**:
`bazel-bin/tensorflow/examples/label_image/label_image --image=/Path/to/image.jpg --input_layer=input --output_layer=MobilenetV1/Predictions/Reshape_1  --graph=/Path/To/my/trained/mobilenet.pb --labels=/Path/To/My/labels.txt --input_mean=0  --input_std=255`

### Describe the problem
Ive retrained MobileNetV1 (224) via the TF Slim readme.md and have produced a graph.pb trained against a data set with 5 labels to classify. I am attempting to validate my training by running the exported graph on some validation and training data myself, and have build label_image and specified the above flags  to run.

Its unclear if label image is expected  able to run MobileNet , but it does not: it errors with:

` E tensorflow/examples/label_image/main.cc:312] Running model failed: Invalid argument: Tried to explicitly squeeze dimension 1 but dimension was not 1: 2
	 [[Node: MobilenetV1/Logits/SpatialSqueeze = Squeeze[T=DT_FLOAT, squeeze_dims=[1, 2], _device="/job:localhost/replica:0/task:0/cpu:0"](MobilenetV1/Logits/Conv2d_1c_1x1/BiasAdd)]]`

### Source code / logs
Full execution command and output:

`Mayalls-Object:tensorflow vade$ bazel-bin/tensorflow/examples/label_image/label_image --image=/Volumes/MediaArchive/datasets/SynopsisCinemaNet/data/Framing/original_photos/Extreme\ Close\ Up/images_12\ copy.jpg --input_layer=input --output_layer=MobilenetV1/Predictions/Reshape_1  --graph=/Volumes/MediaArchive/datasets/SynopsisCinemaNet/model/FramingWeekend/CinemaNetFraming.pb --labels=/Volumes/MediaArchive/datasets/SynopsisCinemaNet/datasets/Framing/labels.txt --input_mean=0  --input_std=255
2017-07-03 14:44:05.971869: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-07-03 14:44:05.972224: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-07-03 14:44:05.972228: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-07-03 14:44:05.972231: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
2017-07-03 14:44:06.123365: E tensorflow/examples/label_image/main.cc:312] Running model failed: Invalid argument: Tried to explicitly squeeze dimension 1 but dimension was not 1: 2
	 [[Node: MobilenetV1/Logits/SpatialSqueeze = Squeeze[T=DT_FLOAT, squeeze_dims=[1, 2], _device="/job:localhost/replica:0/task:0/cpu:0"](MobilenetV1/Logits/Conv2d_1c_1x1/BiasAdd)]]
Mayalls-Object:tensorflow vade$ bazel-bin/tensorflow/examples/label_image/label_image --image=/Volumes/MediaArchive/datasets/SynopsisCinemaNet/data/Framing/converted_photos/Extreme\ Close\ Up/images_12\ copy.jpg --input_layer=input --output_layer=MobilenetV1/Predictions/Reshape_1  --graph=/Volumes/MediaArchive/datasets/SynopsisCinemaNet/model/FramingWeekend/CinemaNetFraming.pb --labels=/Volumes/MediaArchive/datasets/SynopsisCinemaNet/datasets/Framing/labels.txt --input_mean=0  --input_std=255
2017-07-03 14:44:47.201141: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-07-03 14:44:47.201530: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-07-03 14:44:47.201534: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-07-03 14:44:47.201538: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
2017-07-03 14:44:47.365892: E tensorflow/examples/label_image/main.cc:312] Running model failed: Invalid argument: Tried to explicitly squeeze dimension 1 but dimension was not 1: 2
	 [[Node: MobilenetV1/Logits/SpatialSqueeze = Squeeze[T=DT_FLOAT, squeeze_dims=[1, 2], _device="/job:localhost/replica:0/task:0/cpu:0"](MobilenetV1/Logits/Conv2d_1c_1x1/BiasAdd)]]
Mayalls-Object:tensorflow vade$ `

**Comment by cy89** [comment]
@petewarden can you please comment on whether label_image and MobileNet are supposed to play well together.

**Comment by petewarden** [comment]
I think this may be a documentation issue. Here's an example set of arguments I've been able to run on my copies of Mobilenet:

```
--input_layer=input --output_layer=MobilenetV1/Predictions/Reshape_1 --graph=/tmp/mobilenet_v1_224/frozen_graph.pb --logtostderr --input_mean=-127 --input_std=127 --image=third_party/tensorflow/examples/label_image/data/grace_hopper.jpg --input_width=224 --input_height=224 --labels=/tmp/mobilenet_v1_224/labels.txt
```

The key differences from yours are that I'm specifying the width and height explicitly, that I'm using -127 to 127 as the range, and that I'm using the set of labels required for Mobilenet.

I've recently updated the TF for Poets docs and scripts to support Mobilenet by the way:

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/docs_src/tutorials/image_retraining.md#other-model-architectures

**Comment by cy89** [comment]
@vade; does what @petewarden says get you back in business?

**Comment by vade** [comment]
Im out of the office today/tomorrow but will definitely check once I'm back. Thanks in advance @petewarden @cy89 !

**Comment by wider2** [comment]
Good day for everyone
if I use   --model_dir=/inception
everything works well


but I have the same problem of using imagenet on Android Studio java project

java.lang.IllegalArgumentException: Tried to explicitly squeeze dimension 1 but dimension was not 1: 2
W/System.err: 	 [[Node: MobilenetV1/Logits/SpatialSqueeze = Squeeze[T=DT_FLOAT, squeeze_dims=[1, 2], _device="/job:localhost/replica:0/task:0/cpu:0"](MobilenetV1/Logits/Conv2d_1c_1x1/BiasAdd)]]
W/System.err:     

it is look like using of wrong parameters
is anybody knows the right decision?

**Comment by StephaneZFR** [comment]
Hi, I'm facing the same kind of problem.
I fine-tuned MobileNetV1_224 on flowers dataset using procedure in [https://www.tensorflow.org/tutorials/image_retraining](url). It seems to works as it generated an output_graph.pb and output_labels.txt as expected. but when I try my fine-tuned model with label_image, it fails (but it works well with a fine-tuned inception v3).
I tried the suggestion made by  petewarden but it did not work. I had the following error:
 `ValueError: The name 'MobilenetV1/Predictions/Reshape_1' looks like an (invalid) Operation name, not a Tensor. Tensor names must be of the form "<op_name>:<output_index>".`

So I tested summarize_graph on my model and it found 1 possible input (name=input) and one possible output (name=final_result). when I put these values as input_layer and output_layer, I have this:
`Traceback (most recent call last):
  File "label_image_mobilenet.py", line 149, in <module>
    tf.app.run(main=main, argv=sys.argv[:1]+unparsed)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "label_image_mobilenet.py", line 145, in main
    FLAGS.num_top_predictions)
  File "label_image_mobilenet.py", line 107, in run_graph
    predictions, = sess.run(softmax_tensor, {input_layer_name: image_data})
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 968, in _run
    np_val = np.asarray(subfeed_val, dtype=subfeed_dtype)
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/numeric.py", line 531, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: could not convert string to float: ����`

I really don't understand what is going on.
Do you have any idea? Thanks in advance for your help.

Regards,
Stephane

**Comment by StephaneZFR** [comment]
Hi, Well, I don't know if it can help but I could make it work with the following command:
`bazel-bin/tensorflow/examples/label_image/label_image --output_layer=final_result --labels=/home/thales/data/fine_tuned_inception_on_flowers/output_labels.txt --image=/home/thales/data/flower_photos_processed/training_results/5547758_eea9edfd54_n.jpg --graph=/home/thales/data/fine_tuned_mobilenet_on_flowers/output_graph.pb --input_mean=-127 --input_std=127 --input_width=224 --input_height=224`
The output_graph.pb is the one obtained with [https://www.tensorflow.org/tutorials/image_retraining](url)
I had to change a little the suggestion made by pewarden as the tensor `MobilenetV1/Predictions/Reshape_1` could not be found.
At least, it works but I am still a little confused about these errors.
Regards,
Stephane

**Comment by AnshanTJU** [comment]
Hi, Vade, 
I have got same bug:
2017-08-08 14:05:07.302014: E tensorflow/examples/label_image/main.cc:349] Running model failed: Invalid argument: Tried to explicitly squeeze dimension 1 but dimension was not 1: 4
	 [[Node: MobilenetV1/Logits/SpatialSqueeze = Squeeze[T=DT_FLOAT, squeeze_dims=[1, 2], _device="/job:localhost/replica:0/task:0/gpu:0"](MobilenetV1/Logits/Conv2d_1c_1x1/BiasAdd)]]
	 [[Node: MobilenetV1/Predictions/Reshape_1/_3 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_613_MobilenetV1/Predictions/Reshape_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Do you fix it?

**Comment by astrung** [comment]
Hey, i used this tutorial to run model on android : https://codelabs.developers.google.com/codelabs/tensorflow-for-poets-2/index.html?index=..%2F..%2Findex#4 . But after pruning `DecodeJpeg` by command : 

    python -m tensorflow.python.tools.optimize_for_inference \
    --input=tf_files/retrained_graph.pb \
    --output=tf_files/optimized_graph.pb \
    --input_names="Cast" \
    --output_names="final_result"
I can not check the result with this command : 

    python -m scripts.label_image \
    tf_files/flower_photos/daisy/21652746_cc379e0eea_m.jpg \
    tf_files/optimized_graph.pb

,it shows error : `TypeError: Cannot interpret feed_dict key as Tensor: The name 'DecodeJpeg/contents:0' refers to a Tensor which does not exist. The operation, 'DecodeJpeg/contents', does not exist in the graph.`. So how can i check result for optimized android model on computer ?

**Comment by aureosun** [comment]
Sir,I still have the problem when I use image_retraining for mobilenet_v1
the error is:

TypeError: Cannot interpret feed_dict key as Tensor: The name 'DecodeJpeg/contents:0' refers to a Tensor which does not exist. The operation, 'DecodeJpeg/contents', does not exist in the graph.

did anyone got the solutions?

**Comment by webschik** [comment]
Hello @petewarden! 
May you suggest how to fix the next issue:

1) I've retrained my own model according to the [Tensorflow guideline](https://www.tensorflow.org/tutorials/image_retraining):

```shell
python tensorflow/examples/image_retraining/retrain.py --image-dir ../flower_photos --architecture mobilenet_1.0_224
```

where _flower_photos_ is an unarchived flowers set from http://download.tensorflow.org/example_images/flower_photos.tgz

This script produces 2 files _/tmp/output_graph.pb_ and _/tmp/output_labels.txt_

2) Then I tried to recognize some random image:

```shell
python tensorflow/examples/image_retraining/label_image.py --graph=/tmp/output_graph.pb --labels=/tmp/output_labels.txt --image=../flower_photos/daisy/54377391_15648e8d18.jpg
```

But I got  the error: 

```shell
Traceback (most recent call last):
  File "tensorflow/examples/image_retraining/label_image.py", line 147, in <module>
    tf.app.run(main=main, argv=sys.argv[:1]+unparsed)
  File "/Library/Python/2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "tensorflow/examples/image_retraining/label_image.py", line 142, in main
    FLAGS.num_top_predictions)
  File "tensorflow/examples/image_retraining/label_image.py", line 106, in run_graph
    predictions, = sess.run(softmax_tensor, {input_layer_name: image_data})
  File "/Library/Python/2.7/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/Library/Python/2.7/site-packages/tensorflow/python/client/session.py", line 1071, in _run
    + e.args[0])
TypeError: Cannot interpret feed_dict key as Tensor: The name 'DecodeJpeg/contents:0' refers to a Tensor which does not exist. The operation, 'DecodeJpeg/contents', does not exist in the graph.
```

With default architecture (without _--architecture_ flag on the step 1) everything works correctly. I've tried to find a solution on SO and in the Tensorflow documentation, but I still have no success.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue? Please update the label and/or status accordingly.

**Comment by vishalghor** [comment]
Hi @petewarden  , @cy89 ,

I am facing the same issue with Mobilenet retrained models on flower dataset.
I have tried the suggestions as mentioned by @petewarden 
Is there any other script for inferencing Mobilenet retrained model for flowers dataset?
Kindly provide your solution .

Thanks and Regards
Vishal

**Comment by sumeetguha** [comment]
I am taking images from mobile Gallery, and then calling recognizeImage method of Classifier with InputSize from 224 to 1024, and in all this values its throwing ArrayIndexOutOfBound Exception. 
So to resolve this exception, I passes InputSize as 1600 and more, and then I am getting exception as "java.lang.IllegalArgumentException: Tried to explicitly squeeze dimension 1 but dimension was not 1: 22 [[Node: MobilenetV1/Logits/SpatialSqueeze = Squeeze[T=DT_FLOAT, squeeze_dims=[1, 2], _device="/job:localhost/replica:0/task:0/cpu:0"](MobilenetV1‌​/Logits/Conv2d_1c_1x‌​1/BiasAdd)]]"

Then I was trying to retrain the model with flag IMAGE_SIZE=2048 and ARCHITECTURE="mobilenet_0.50_${IMAGE_SIZE}", but its throwing error like:- tensorflow:The Mobilenet input size should be '224', '192', '160', or '128', but found '2048' for architecture 'mobilenet_0.50_2048' ERROR:tensorflow:Did not recognize architecture flag

Any idea, how to resolve this issue?

**Comment by vade** [comment]
Hi - Sorry for the delayed response, just got back to this.

I can confirm that Mobile-net training and label classification works in TF Master branch compiled from source (from today 136697e) - ive successfully trained a new graph via @petewarden 's updated documentation of the TF for Poets code.

however, once caveat is that my python command line options varied a touch:

To train:

`python tensorflow/examples/image_retraining/retrain.py --image_dir ~/path/to/images/ --architecture mobilenet_1.0_224 --random_crop 5 --random_scale 5 --random_brightness 5 --flip_left_right --output_graph ~/Graph.pb
`

To run inference:

`python tensorflow/examples/label_image/label_image.py --graph=~/Graph.pb --labels=~/output_labels.txt --input_layer=input --output_layer=final_result --input_height=224 --input_width=224 --input_mean=128 --input_std=128 --image=~/test.jpg 
`

Note; final_result, not final_result:0

Also note the input_mean / std varies is stated in some locations to be 127, in others 128. Can we have a confirmation?

Thank you.

**Comment by vade** [comment]
Also happy to close this once I get a confirmation on the STD values. Appreciate this tool/script being available. Makes working with TF so much easier than making tf records etc.

**Comment by vade** [comment]
@sumeetguha the input_height / width are not for your "image" that you are inputting, but rather the input sizes for the tensor that the model you are using expects. This is basically the 'resize' target the tensor should be resized to prior to running the graph to get your classification result.

I could be wrong or misunderstand, but I dont think there exists a mobile net mobilenet_0.50_2048 - the graph only supports VERY specific input sizes. 

The good news is you can resize any image to the graph you have chosen. You make the graph choice based on precision vs execution time vs memory usage (and size of graph on disk). Its a balancing act :)

**Comment by vishalghor** [comment]
Hi all,

I was finally able to  inference mobilenet successfully using the label_image.py with slight modifications.
I have modified the part where image is loaded with load_image() function.
The code of label_image.py which i had modified. 
Hopefully it will help others in resolving the errors.:)  
`

    from __future__ import division
    from __future__ import absolute_import
    from __future__ import print_function
    
    import argparse
    import sys
    import PIL
    from PIL import Image
    import tensorflow as tf
    import numpy as np
    from numpy import array
    '''
    parser = argparse.ArgumentParser()
    parser.add_argument(
        '--image', required=True, type=str, help='Absolute path to image file.')
    parser.add_argument(
        '--num_top_predictions',
        type=int,
        default=5,
        help='Display this many predictions.')
    parser.add_argument(
        '--graph',
        required=True,
        type=str,
        help='Absolute path to graph file (.pb)')
    parser.add_argument(
        '--labels',
        required=True,
        type=str,
        help='Absolute path to labels file (.txt)')
    parser.add_argument(
        '--output_layer',
        type=str,
        default='final_result:0',
        help='Name of the result operation')
    parser.add_argument(
        '--input_layer',
        type=str,
        default='DecodeJpeg/contents:0',
        help='Name of the input operation')
    
    '''
    def load_image(filename):
      """Read in the image_data to be classified."""
      #return tf.gfile.FastGFile(filename, 'rb').read()
      
    
      im=Image.open(filename)
      image=np.asarray(im, dtype="float32")
      img=(image-128.0)/128.0
      
      img=array(img).reshape(1,224,224,3)
      return img
    
    def load_labels(filename):
      """Read in labels, one label per line."""
      return [line.rstrip() for line in tf.gfile.GFile(filename)]
    
    
    def load_graph(filename):
      """Unpersists graph from file as default graph."""
      with tf.gfile.FastGFile('/home/ubuntu/ML_GIT/TensorFlow/MobileNet_Multi_label/output_graph.pb', 'rb') as f:
        graph_def = tf.GraphDef()
        graph_def.ParseFromString(f.read())
        tf.import_graph_def(graph_def, name='')
    
    
    def run_graph(image_data, labels, input_layer_name, output_layer_name,
                  num_top_predictions):
    
    
      with tf.Session() as sess:
        # Feed the image_data as input to the graph.
        #   predictions  will contain a two-dimensional array, where one
        #   dimension represents the input image count, and the other has
        #   predictions per class
        input_node = sess.graph.get_tensor_by_name('input:0')
        output_node = sess.graph.get_tensor_by_name('final_result:0')
    
        softmax_tensor = sess.graph.get_tensor_by_name(output_layer_name)
        predictions, = sess.run(softmax_tensor, {input_layer_name: image_data})
        
        # Sort to show labels in order of confidence
        top_k = predictions.argsort()[-num_top_predictions:][::-1]
        for node_id in top_k:
          human_string = labels[node_id]
          score = predictions[node_id]
          print('%s (score = %.5f)' % (human_string, score))
    
        return 0
    
    
    def main(argv):
      """Runs inference on an image."""
      '''
      if argv[1:]:
        raise ValueError('Unused Command Line Args: %s' % argv[1:])
    
      if not tf.gfile.Exists(FLAGS.image):
        tf.logging.fatal('image file does not exist %s', FLAGS.image)
    
      if not tf.gfile.Exists(FLAGS.labels):
        tf.logging.fatal('labels file does not exist %s', FLAGS.labels)
    
      if not tf.gfile.Exists(FLAGS.graph):
        tf.logging.fatal('graph file does not exist %s', FLAGS.graph)
      '''
      input_layer='input:0'
      output_layer='final_result:0'
      num_top_predictions=5
      # load image
      image_data = load_image('/home/ubuntu/snpe-1.10.1/models/Mobilenet_Multi_Label/data/rawfiles/8_25.raw')#'/home/ubuntu/share/SOMC_prepared_data/testing/9_56.JPG')
    
      # load labels
      labels = load_labels('/home/ubuntu/ML_GIT/TensorFlow/Mobilenet/labels.txt')
    
      # load graph, which is stored in the default session
      load_graph('/home/ubuntu/ML_GIT/TensorFlow/MobileNet_Multi_label/output_graph.pb')
    
      run_graph(image_data, labels,input_layer,output_layer,
                num_top_predictions)
    
    
    if __name__ == '__main__':
      #FLAGS, unparsed = parser.parse_known_args()
      tf.app.run(main=main)
    
`
