### ISSUE TITLE
Import tensorflow with error information"KeyError: "Couldn't find field google.protobuf.FileOptions.php_class_prefix""

### ISSUE THREAD

**Issue by shaoyn0817** [tensorflow/tensorflow#11254]
here is the error information:
>>> import tensorflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/shaoyn/anaconda2/lib/python2.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/home/shaoyn/anaconda2/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/home/shaoyn/anaconda2/lib/python2.7/site-packages/tensorflow/core/framework/graph_pb2.py", line 10, in <module>
    from google.protobuf import descriptor_pb2
  File "/home/shaoyn/anaconda2/lib/python2.7/site-packages/google/protobuf/descriptor_pb2.py", line 1003, in <module>
    options=None),
  File "/home/shaoyn/anaconda2/lib/python2.7/site-packages/google/protobuf/descriptor.py", line 498, in __new__
    return _message.default_pool.FindFieldByName(full_name)
KeyError: "Couldn't find field google.protobuf.FileOptions.php_class_prefix"

**Comment by ScorpioCPH** [comment]
Reinstall `protobuf` maybe helpful:

```shell
$ sudo pip uninstall protobuf
$ sudo pip install protobuf
```

**Comment by cy89** [comment]
@shaoyn0817 please try @ScorpioCPH 's suggestion, and let us know if it helps.

**Comment by shaoyn0817** [comment]
thx~

**Comment by fortyMiles** [comment]
thx a lot!
