### ISSUE TITLE
faster-rcnn incompatible shapes randomly during training custom dataset

### ISSUE THREAD

**Issue by ckalas** [tensorflow/tensorflow#11265]
I'm trying to train faster-rcnn with resnet101 on a custom dataset, which I have formatted appropriately for tf. When I run training, it can run anywhere from 30-1000 steps before it gives me an error like this:

 ```
File "train.py", line 195, in main
    worker_job_name, is_chief, FLAGS.train_dir)
  File "/home/chris/tensorflow/models/object_detection/trainer.py", line 192, in train
    clones = model_deploy.create_clones(deploy_config, model_fn, [input_queue])
  File "/home/chris/tensorflow/models/slim/deployment/model_deploy.py", line 193, in create_clones
    outputs = model_fn(*args, **kwargs)
  File "/home/chris/tensorflow/models/object_detection/trainer.py", line 133, in _create_losses
    losses_dict = detection_model.loss(prediction_dict)
  File "/home/chris/tensorflow/models/object_detection/meta_architectures/faster_rcnn_meta_arch.py", line 1173, in loss
    groundtruth_classes_with_background_list))
  File "/home/chris/tensorflow/models/object_detection/meta_architectures/faster_rcnn_meta_arch.py", line 1329, in _loss_box_classifier
    batch_reg_targets, weights=batch_reg_weights) / normalizer
  File "/home/chris/tensorflow/models/object_detection/core/losses.py", line 71, in __call__
    return self._compute_loss(prediction_tensor, target_tensor, **params)
  File "/home/chris/tensorflow/models/object_detection/core/losses.py", line 158, in _compute_loss
    diff = prediction_tensor - target_tensor
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/math_ops.py", line 846, in binary_op_wrapper
    return func(x, y, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_math_ops.py", line 2582, in _sub
    result = _op_def_lib.apply_op("Sub", x=x, y=y, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)

InvalidArgumentError (see above for traceback): Incompatible shapes: [1,61,4] vs. [1,64,4]
	 [[Node: gradients/Loss/BoxClassifierLoss/Loss/sub_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](gradients/Loss/BoxClassifierLoss/Loss/sub_grad/Shape, gradients/Loss/BoxClassifierLoss/Loss/sub_grad/Shape_1)]]
	 [[Node: gradients/FirstStageFeatureExtractor/resnet_v1_101/resnet_v1_101/block1/unit_2/bottleneck_v1/conv1/BatchNorm/batchnorm/mul_grad/tuple/control_dependency_1/_3949 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_22091_gradients/FirstStageFeatureExtractor/resnet_v1_101/resnet_v1_101/block1/unit_2/bottleneck_v1/conv1/BatchNorm/batchnorm/mul_grad/tuple/control_dependency_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
```

The dimension mismatch is from what I can tell from from looking in losses.py the number of anchors, but I really don't know how to try debug this. FWIW, the training on ssd runs without issue so far.

A bit of info about the dataset, the images all contain multiple (likely crowded) of the same object.

**Comment by andydavis1** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by ckalas** [comment]
moved to https://stackoverflow.com/questions/45007328/tensorflow-object-detection-faster-rcnn-randomly-fails

**Comment by gmvidooly** [comment]
I am getting same error too.

**Comment by mjdileep** [comment]
You have to configure `num_classes = xx` in here,[https://github.com/bourdakos1/Custom-Object-Detection/blob/master/faster_rcnn_resnet101.config](url)

**Comment by wanghaiyun139** [comment]
>>> rpn_loss_cls: 0.164899
 >>> rpn_loss_box: 0.052974
 >>> loss_cls: 0.539121
 >>> loss_box: 0.132027
 >>> lr: 0.000100
speed: 20.228s / iter
image: D:\tf-faster-rcnn-windows\data\VOCdevkit2007\VOC2007\JPEGImages\class4_3.PNG
image: D:\tf-faster-rcnn-windows\data\VOCdevkit2007\VOC2007\JPEGImages\class3_93.PNG
image: D:\tf-faster-rcnn-windows\data\VOCdevkit2007\VOC2007\JPEGImages\class2_50.PNG
> d:\tf-faster-rcnn-windows\lib\layer_utils\proposal_target_layer.py(138)_sample_rois()
-> keep_inds = np.append(fg_inds, bg_inds)
(Pdb) c
Traceback (most recent call last):
  File "D:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1323, in _do_call
    return fn(*args)
  File "D:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1302, in _run_fn
    status, run_metadata)
  File "D:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [0,44] vs. [128,44]
	 [[Node: gradients/LOSS_default/mul_9_grad/mul_1 = Mul[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](vgg_16_1/rpn_rois/proposal_target:5, gradients/LOSS_default/Sum_1_grad/Tile)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/tf-faster-rcnn-windows/tools/trainval_net.py", line 143, in <module>
    max_iters=args.max_iters)
  File "D:\tf-faster-rcnn-windows\tools\..\lib\model\train_val.py", line 377, in train_net
    sw.train_model(sess, max_iters)
  File "D:\tf-faster-rcnn-windows\tools\..\lib\model\train_val.py", line 294, in train_model
    self.net.train_step(sess, blobs, train_op)
  File "D:\tf-faster-rcnn-windows\tools\..\lib\nets\network.py", line 497, in train_step
    feed_dict=feed_dict)
  File "D:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 889, in run
    run_metadata_ptr)
  File "D:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "D:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1317, in _do_run
    options, run_metadata)
  File "D:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [0,44] vs. [128,44]
	 [[Node: gradients/LOSS_default/mul_9_grad/mul_1 = Mul[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](vgg_16_1/rpn_rois/proposal_target:5, gradients/LOSS_default/Sum_1_grad/Tile)]]

Caused by op 'gradients/LOSS_default/mul_9_grad/mul_1', defined at:
  File "D:/tf-faster-rcnn-windows/tools/trainval_net.py", line 143, in <module>
    max_iters=args.max_iters)
  File "D:\tf-faster-rcnn-windows\tools\..\lib\model\train_val.py", line 377, in train_net
    sw.train_model(sess, max_iters)
  File "D:\tf-faster-rcnn-windows\tools\..\lib\model\train_val.py", line 248, in train_model
    lr, train_op = self.construct_graph(sess)
  File "D:\tf-faster-rcnn-windows\tools\..\lib\model\train_val.py", line 131, in construct_graph
    gvs = self.optimizer.compute_gradients(loss)
  File "D:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\training\optimizer.py", line 414, in compute_gradients
    colocate_gradients_with_ops=colocate_gradients_with_ops)
  File "D:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\ops\gradients_impl.py", line 581, in gradients
    grad_scope, op, func_call, lambda: grad_fn(op, *out_grads))
  File "D:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\ops\gradients_impl.py", line 353, in _MaybeCompile
    return grad_fn()  # Exit early
  File "D:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\ops\gradients_impl.py", line 581, in <lambda>
    grad_scope, op, func_call, lambda: grad_fn(op, *out_grads))
  File "D:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\ops\math_grad.py", line 747, in _MulGrad
    array_ops.reshape(math_ops.reduce_sum(x * grad, ry), sy))
  File "D:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\ops\math_ops.py", line 894, in binary_op_wrapper
    return func(x, y, name=name)
  File "D:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\ops\math_ops.py", line 1117, in _mul_dispatch
    return gen_math_ops._mul(x, y, name=name)
  File "D:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 2725, in _mul
    "Mul", x=x, y=y, name=name)
  File "D:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "D:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2956, in create_op
    op_def=op_def)
  File "D:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

...which was originally created as op 'LOSS_default/mul_9', defined at:
  File "D:/tf-faster-rcnn-windows/tools/trainval_net.py", line 143, in <module>
    max_iters=args.max_iters)
[elided 1 identical lines from previous traceback]
  File "D:\tf-faster-rcnn-windows\tools\..\lib\model\train_val.py", line 248, in train_model
    lr, train_op = self.construct_graph(sess)
  File "D:\tf-faster-rcnn-windows\tools\..\lib\model\train_val.py", line 123, in construct_graph
    anchor_ratios=cfg.ANCHOR_RATIOS)
  File "D:\tf-faster-rcnn-windows\tools\..\lib\nets\network.py", line 434, in create_architecture
    self._add_losses()
  File "D:\tf-faster-rcnn-windows\tools\..\lib\nets\network.py", line 308, in _add_losses
    loss_box = self._smooth_l1_loss(bbox_pred, bbox_targets, bbox_inside_weights, bbox_outside_weights)
  File "D:\tf-faster-rcnn-windows\tools\..\lib\nets\network.py", line 272, in _smooth_l1_loss
    out_loss_box = bbox_outside_weights * in_loss_box
  File "D:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\ops\math_ops.py", line 894, in binary_op_wrapper
    return func(x, y, name=name)
  File "D:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\ops\math_ops.py", line 1117, in _mul_dispatch
    return gen_math_ops._mul(x, y, name=name)
  File "D:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 2725, in _mul
    "Mul", x=x, y=y, name=name)
  File "D:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "D:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2956, in create_op
    op_def=op_def)
  File "D:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Incompatible shapes: [0,44] vs. [128,44]
	 [[Node: gradients/LOSS_default/mul_9_grad/mul_1 = Mul[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](vgg_16_1/rpn_rois/proposal_target:5, gradients/LOSS_default/Sum_1_grad/Tile)]]

**Comment by wanghaiyun139** [comment]
I have been looking for a few days, I have been unable to find a problem, have a friend who knows, thank you.
