### ISSUE TITLE
tensorflow.python.framework.errors.NotFoundError: No algorithm worked!

### ISSUE THREAD

**Issue by 1234clam** [tensorflow/tensorflow#11271]
I install the TensorFlow 0.10.0 on Ubuntu 14.0.4 with cuda 7.5 and cudnn 5.1.The GPU is GTX980 
when I run a softmax example on minst dataset the TensorFlow can work but when i build CNN with TensorFlow it will cause error.
```
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
Start to train the convolutional neural network......
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 0 with properties: 
name: GeForce GTX 980
major: 5 minor: 2 memoryClockRate (GHz) 1.2155
pciBusID 0000:02:00.0
Total memory: 3.94GiB
Free memory: 3.82GiB
W tensorflow/stream_executor/cuda/cuda_driver.cc:572] creating context when one is currently active; existing: 0x27e67f0
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 1 with properties: 
name: GeForce GTX 980
major: 5 minor: 2 memoryClockRate (GHz) 1.2155
pciBusID 0000:03:00.0
Total memory: 3.94GiB
Free memory: 3.87GiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:126] DMA: 0 1 
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 0:   Y Y 
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 1:   Y Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:838] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 980, pci bus id: 0000:02:00.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:838] Creating TensorFlow device (/gpu:1) -> (device: 1, name: GeForce GTX 980, pci bus id: 0000:03:00.0)
E tensorflow/stream_executor/cuda/cuda_driver.cc:1115] failed to get elapsed time between events: CUDA_ERROR_NOT_READY
E tensorflow/stream_executor/cuda/cuda_driver.cc:1115] failed to get elapsed time between events: CUDA_ERROR_NOT_READY
E tensorflow/stream_executor/cuda/cuda_driver.cc:1115] failed to get elapsed time between events: CUDA_ERROR_NOT_READY
E tensorflow/stream_executor/cuda/cuda_driver.cc:1115] failed to get elapsed time between events: CUDA_ERROR_NOT_READY
E tensorflow/stream_executor/cuda/cuda_driver.cc:1115] failed to get elapsed time between events: CUDA_ERROR_NOT_READY
Traceback (most recent call last):
  File "test.py", line 69, in <module>
    test_cnn()  
  File "test.py", line 59, in test_cnn
    sess.run(fetches=Step_train, feed_dict={x:batch[0], y:batch[1], dropout_prob:0.5})  
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 710, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 908, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 958, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 978, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors.NotFoundError: No algorithm worked!
	 [[Node: Conv2D_1 = Conv2D[T=DT_FLOAT, data_format="NHWC", padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/gpu:0"](MaxPool, weight_1/read)]]
Caused by op u'Conv2D_1', defined at:
  File "test.py", line 69, in <module>
    test_cnn()
  File "test.py", line 35, in test_cnn
    conv2_out = tf.nn.relu(conv_2d(pool1_out, w_conv2)+b_conv2)
  File "test.py", line 12, in conv_2d
    return tf.nn.conv2d(input=x, filter=w, strides=[1, 1, 1, 1], padding="SAME")
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_nn_ops.py", line 394, in conv2d
    data_format=data_format, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 703, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2317, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1239, in __init__
    self._traceback = _extract_stack()

E tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:643] Deallocating stream with pending work
^CWrite failed: Broken pipe
```
if you can help me solve the problem or give some advice, it will be great

**Comment by drpngx** [comment]
@mjanusz any idea? It looks like we're trying to get timings before some streaming operation is done?

**Comment by andydavis1** [comment]
@zheng-xq any idea in this one?

**Comment by 1234clam** [comment]
Do you have some idea to solve this problem.Thank you! @drpngx @andydavis1

**Comment by yzhwang** [comment]
Hi @1234clam . Just to make sure, is this the example you are using? https://www.tensorflow.org/get_started/mnist/beginners Thanks!

**Comment by 1234clam** [comment]
Yes I have run this example and  run the minst_mlp.py in keras example,it can work every well but when i use the cnn it  caused such a mistake. Do you have some advice to solve this problem? The result minst_softmax.py example just like this:
```
$ python test.py
Successfully downloaded train-images-idx3-ubyte.gz 9912422 bytes.
Extracting /tmp/tensorflow/mnist/input_data/train-images-idx3-ubyte.gz
Successfully downloaded train-labels-idx1-ubyte.gz 28881 bytes.
Extracting /tmp/tensorflow/mnist/input_data/train-labels-idx1-ubyte.gz
Successfully downloaded t10k-images-idx3-ubyte.gz 1648877 bytes.
Extracting /tmp/tensorflow/mnist/input_data/t10k-images-idx3-ubyte.gz
Successfully downloaded t10k-labels-idx1-ubyte.gz 4542 bytes.
Extracting /tmp/tensorflow/mnist/input_data/t10k-labels-idx1-ubyte.gz
2017-07-06 11:45:29.078223: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-07-06 11:45:29.078267: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-07-06 11:45:29.078277: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-07-06 11:45:29.078286: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-07-06 11:45:29.078294: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
2017-07-06 11:45:29.499407: I tensorflow/core/common_runtime/gpu/gpu_device.cc:940] Found device 0 with properties: 
name: GeForce GTX 980
major: 5 minor: 2 memoryClockRate (GHz) 1.2155
pciBusID 0000:02:00.0
Total memory: 3.94GiB
Free memory: 3.78GiB
2017-07-06 11:45:29.710753: W tensorflow/stream_executor/cuda/cuda_driver.cc:523] A non-primary context 0x35d7a50 exists before initializing the StreamExecutor. We haven't verified StreamExecutor works with that.
2017-07-06 11:45:29.711664: I tensorflow/core/common_runtime/gpu/gpu_device.cc:940] Found device 1 with properties: 
name: GeForce GTX 980
major: 5 minor: 2 memoryClockRate (GHz) 1.2155
pciBusID 0000:03:00.0
Total memory: 3.94GiB
Free memory: 3.87GiB
2017-07-06 11:45:29.712385: I tensorflow/core/common_runtime/gpu/gpu_device.cc:961] DMA: 0 1 
2017-07-06 11:45:29.712412: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   Y Y 
2017-07-06 11:45:29.712421: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 1:   Y Y 
2017-07-06 11:45:29.712439: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 980, pci bus id: 0000:02:00.0)
2017-07-06 11:45:29.712453: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating TensorFlow device (/gpu:1) -> (device: 1, name: GeForce GTX 980, pci bus id: 0000:03:00.0)
0.9165
```

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by yzhwang** [comment]
@1234clam Have you tried with TensorFlow 1.4? Does the problem still exist with the latest version?
Note that the warning means that your thread for running TensorFlow might already have another running CUDA program before you launch TensorFlow, according to this warning:
2017-07-06 11:45:29.710753: W tensorflow/stream_executor/cuda/cuda_driver.cc:523] A non-primary context 0x35d7a50 exists before initializing the StreamExecutor. We haven't verified StreamExecutor works with that.
One way to make sure nothing is using your GPU is to run `nvidia-smi` and kill any process showed up that are using your GPU before you run any TensorFlow program.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by yzhwang** [comment]
Close due to inactivity. Feel free to reopen if the issue still exists.
