### ISSUE TITLE
Blas SGEMM launch failed

### ISSUE THREAD

**Issue by pradyumnanpk** [tensorflow/tensorflow#11301]
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: I am using Resnet code from tensorflow models with some modifications.
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Fedora 24
- **TensorFlow installed from (source or binary)**: Binary
- **TensorFlow version (use command below)**: ('v1.2.0-rc2-21-g12f033d', '1.2.0')
- **Python version**: 2.7
- **CUDA/cuDNN version**: cuda_8.0.61-cudnnv5
- **GPU model and memory**: Nvidia Titan X, 12 GB

I am training a Resnet model on my own data from scratch. After successfully running for 65700 steps, it crashed with the following error:

2017-06-30 16:27:50.302438: E tensorflow/stream_executor/cuda/cuda_blas.cc:543] failed to run cuBLAS routine cublasSgemm_v2: CUBLAS_STATUS_EXECUTION_FAILED
Traceback (most recent call last):
  File "resnet_main.py", line 178, in <module>
    if z%100 == 0:
  File "/s/chopin/l/grad/prady/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "resnet_main.py", line 171, in main
    tf.logging.info('Loading checkpoint %s', ckpt_state.model_checkpoint_path)
  File "resnet_main.py", line 90, in train
    mon_sess.run(model.train_op)
  File "/s/chopin/l/grad/prady/.local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 505, in run
    run_metadata=run_metadata)
  File "/s/chopin/l/grad/prady/.local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 842, in run
    run_metadata=run_metadata)
  File "/s/chopin/l/grad/prady/.local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 798, in run
    return self._sess.run(*args, **kwargs)
  File "/s/chopin/l/grad/prady/.local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 952, in run
    run_metadata=run_metadata)
  File "/s/chopin/l/grad/prady/.local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 798, in run
    return self._sess.run(*args, **kwargs)
  File "/s/chopin/l/grad/prady/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/s/chopin/l/grad/prady/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "/s/chopin/l/grad/prady/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "/s/chopin/l/grad/prady/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Blas SGEMM launch failed : m=12544, n=1024, k=256
	 [[Node: unit_3_2/sub3/conv3/Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/gpu:0"](unit_3_2/sub3/leaky_relu, unit_3_2/sub3/conv3/DW/read)]]
	 [[Node: train_step/update/_6858 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_15509_train_step/update", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Caused by op u'unit_3_2/sub3/conv3/Conv2D', defined at:
  File "resnet_main.py", line 178, in <module>
    if z%100 == 0:
  File "/s/chopin/l/grad/prady/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "resnet_main.py", line 171, in main
    tf.logging.info('Loading checkpoint %s', ckpt_state.model_checkpoint_path)
  File "resnet_main.py", line 31, in train
    model.build_graph()
  File "/s/chopin/l/grad/prady/PycharmProjects/GestureRecognition/frame/resnet_model.py", line 42, in build_graph
    self._build_model()
  File "/s/chopin/l/grad/prady/PycharmProjects/GestureRecognition/frame/resnet_model.py", line 95, in _build_model
    x = res_func(x, filters[3], filters[3], self._stride_arr(1), False)
  File "/s/chopin/l/grad/prady/PycharmProjects/GestureRecognition/frame/resnet_model.py", line 245, in _bottleneck_residual
    x = self._conv('conv3', x, 1, out_filter / 4, out_filter, [1, 1, 1, 1])
  File "/s/chopin/l/grad/prady/PycharmProjects/GestureRecognition/frame/resnet_model.py", line 273, in _conv
    return tf.nn.conv2d(x, kernel, strides, padding='SAME')
  File "/s/chopin/l/grad/prady/.local/lib/python2.7/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 399, in conv2d
    data_format=data_format, name=name)
  File "/s/chopin/l/grad/prady/.local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/s/chopin/l/grad/prady/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/s/chopin/l/grad/prady/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

InternalError (see above for traceback): Blas SGEMM launch failed : m=12544, n=1024, k=256
	 [[Node: unit_3_2/sub3/conv3/Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/gpu:0"](unit_3_2/sub3/leaky_relu, unit_3_2/sub3/conv3/DW/read)]]
	 [[Node: train_step/update/_6858 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_15509_train_step/update", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

2017-06-30 16:27:55.680213: E tensorflow/stream_executor/event.cc:33] error destroying CUDA event in context 0x564291240800: CUDA_ERROR_MISALIGNED_ADDRESS

On another machine with exact configuration, it is still running successfully (425,000 steps as of now). I don't understand why it crashed on one machine after running for 65,700 steps.

**Comment by cy89** [comment]
I'm sorry, but Fedora isn't a supported configuration for us. 
It seems worth asking: can you restart from a checkpoint, and roll past the 67000 step failure point? Or otherwise repeat the failure?

**Comment by naisanza** [comment]
@cy89 how about getting `Blas GEMM launch failed` with Ubuntu 16.04?

Full log: [errors/Embedding error 2.txt](https://github.com/TheShellLand/tenderflow/blob/master/keras/errors/Embedding%20error%202.txt)

**Comment by SelaOr** [comment]
having the same problem on ubuntu 16.04 only when using webcam instead of input video and only when using GPU and not only the CPU. Any ideas?

**Comment by rosecatherinek** [comment]
Did anyone fix this? 

We are getting this error (Blas SGEMM launch failed) while trying to learn word2vec embeddings. The code is pretty much the one in the TF tutorial (https://www.tensorflow.org/tutorials/word2vec). It runs without any problem on a regular GPU machine. However, we are trying to run it in a CodaLab setup (http://codalab.org/). The TF docker image is the official one from https://hub.docker.com/r/tensorflow/tensorflow/ specified as: tensorflow/tensorflow:1.0.0-gpu

The full error can be seen here: 
https://codalab.rollme.ml.cmu.edu/bundles/0x3646a0f2dc614a6a971cbeadf753cf15/

**Comment by dksb** [comment]
Closing due to lack of recent activity. if you are still facing this problem, please create a new issue using one of the issue templates. Thanks!
