### ISSUE TITLE
wide_n_deep AttributeError (master) and ValueError (r1.2)

### ISSUE THREAD

**Issue by amandajliu** [tensorflow/tensorflow#11328]
I'm using TensorFlow 1.2.1. When I run `python wide_n_deep_tutorial.py --model_type=wide` from the [Linear Model tutorial](https://www.tensorflow.org/tutorials/wide), I get the following AttributeError:

```
  File "wide_n_deep_tutorial.py", line 139, in build_estimator
    m = tf.estimator.LinearClassifier(
AttributeError: 'module' object has no attribute 'LinearClassifier'
```

I tried switching to r1.2, as suggested in #11256, but got this ValueError on r1.2:

```
Traceback (most recent call last):
  File "wide_n_deep_tutorial.py", line 234, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/home/usr/tensorflow/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "wide_n_deep_tutorial.py", line 197, in main
    FLAGS.train_data, FLAGS.test_data)
  File "wide_n_deep_tutorial.py", line 186, in train_and_eval
    m.fit(input_fn=lambda: input_fn(df_train), steps=train_steps)
  File "/home/usr/tensorflow/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 289, in new_func
    return func(*args, **kwargs)
  File "/home/usr/tensorflow/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 455, in fit
    loss = self._train_model(input_fn=input_fn, hooks=hooks)
  File "/home/usr/tensorflow/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 953, in _train_model
    features, labels = input_fn()
  File "wide_n_deep_tutorial.py", line 186, in <lambda>
    m.fit(input_fn=lambda: input_fn(df_train), steps=train_steps)
  File "wide_n_deep_tutorial.py", line 148, in input_fn
    for k in CATEGORICAL_COLUMNS}
  File "wide_n_deep_tutorial.py", line 148, in <dictcomp>
    for k in CATEGORICAL_COLUMNS}
  File "/home/usr/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/sparse_tensor.py", line 132, in __init__
    indices_shape = indices.get_shape().with_rank(2)
  File "/home/usr/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/tensor_shape.py", line 632, in with_rank
    raise ValueError("Shape %s must have rank %d" % (self, rank))
ValueError: Shape (0,) must have rank 2
```

**Comment by amandajliu** [comment]
Resolved by using `tf.contrib.learn.LinearClassifier` and using its `fit` function.

**Comment by cy89** [comment]
Thanks!
