### ISSUE TITLE
ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'

### ISSUE THREAD

**Issue by arduano** [tensorflow/tensorflow#11326]
Windows 10 Home
Python 3.6
CUDA 8.0 & 7.5 
cuDNN 5.1 (for both 8.0 and 7.5)
CUDA path variables set (to 8.0)
GeForce GTX 970
tensorflow installed from:
https://github.com/tensorflow/tensorflow/tree/r1.2
http://i.imgur.com/tqTp5LA.png

I also have Theano and CNTK installed and they both work

the error happens when importing tensorflow
`import tensorflow as tf`

```
>>> import tensorflow as tf
Traceback (most recent call last):
  File "D:\Programs\Anaconda3.6\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "D:\Programs\Anaconda3.6\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 648, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 560, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Programs\Anaconda3.6\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "D:\Programs\Anaconda3.6\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 21, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "D:\Programs\Anaconda3.6\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 20, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow_internal')
  File "D:\Programs\Anaconda3.6\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Programs\Anaconda3.6\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "D:\Programs\Anaconda3.6\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "D:\Programs\Anaconda3.6\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 52, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "D:\Programs\Anaconda3.6\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "D:\Programs\Anaconda3.6\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 648, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 560, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Programs\Anaconda3.6\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "D:\Programs\Anaconda3.6\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 21, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "D:\Programs\Anaconda3.6\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 20, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow_internal')
  File "D:\Programs\Anaconda3.6\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

**Comment by jubjamie** [comment]
@mrry has a great script to help diagnose these problems. What are the results of that?

Check out this post here: https://stackoverflow.com/questions/42011070/

These problems are often caused by the MSVCP140.DLL not being installed and/or in your path. 

(Side bar: Are you installing tensorflow in the root of your anaconda and then accessing it through an environment or all through root?)

**Comment by arduano** [comment]
Sorry for the late response,
MSVCP140.DLL is installed and is in my PATH

I installed tensorflow with Anaconda's pip to the default location and I am accessing it from a different folder.

**Comment by arduano** [comment]
Just ran the script and got this result:
```
ERROR: Failed to import the TensorFlow module.

- Python version is 3.6.
- The official distribution of TensorFlow for Windows requires Python version 3.5.

- TensorFlow is installed at: D:\Programs\Anaconda3.6\lib\site-packages\tensorflow
The thread 'MainThread' (0x12f8) has exited with code 0 (0x0).
The program '[7320] python.exe' has exited with code -1 (0xffffffff).
```
I installed the new version of tensorflow for python 3.6

**Comment by cy89** [comment]
Sorry, I'm confused by your update. Do you mean that you installed the new version of TF for Windows, which works with 3.6, and you're still experiencing the problem?

**Comment by arduano** [comment]
Sorry for the confusion,
I didn't change anything, I just ran the script.
I always had the new version of tensorflow that is compatible with 3.6 installed, with Python 3.6 itself (anaconda).
And also sorry for the late responses, I live in Australia.

**Comment by mrry** [comment]
The latest version of TensorFlow *is* compatible with Python 3.6 (I've updated the [self-check script](https://gist.github.com/mrry/ee5dbcfdd045fa48a27d56664411d41c) to reflect that). 

You mentioned that CUDA is in your `%PATH%`... have you also added the cuDNN `bin\` directory to your path?

**Comment by arduano** [comment]
Yes.
http://i.imgur.com/vinpQwY.png

The script returns:
```
ERROR: Failed to import the TensorFlow module.

- Python version is 3.6.

- TensorFlow is installed at: D:\Programs\Anaconda3.6\lib\site-packages\tensorflow

- All required DLLs are present. Please open an issue on the
  TensorFlow GitHub page: https://github.com/tensorflow/tensorflow/issues
An exception has occurred, use %tb to see the full traceback.

SystemExit: -1
```

**Comment by arduano** [comment]
Oh, and your script's exception traceback:
```
---------------------------------------------------------------------------
SystemExit                                Traceback (most recent call last)
<ipython-input-1-fc5b8d96e0e5> in <module>()
    106 
    107 if __name__ == "__main__":
--> 108   main()

<ipython-input-1-fc5b8d96e0e5> in main()
    103   TensorFlow GitHub page: https://github.com/tensorflow/tensorflow/issues""")
    104 
--> 105   sys.exit(-1)
    106 
    107 if __name__ == "__main__":

SystemExit: -1
```

**Comment by mrry** [comment]
OK, in that case there must be some missing dependency. In the same terminal as you used to run `ipython`, can you try running [Dependency Walker](http://www.dependencywalker.com/) on the file `D:\Programs\Anaconda3.6\lib\site-packages\tensorflow\python\_pywrap_tensorflow_internal.pyd`, and let us know what DLLs it reports as missing?

**Comment by arduano** [comment]
I'm, not too sure how to use this, but this is what I got:
http://i.imgur.com/lh8Byqk.png

**Comment by mrry** [comment]
Can you get the full list of modules that have "Error opening file." next to them? Annoyingly, the `API-MS-WIN-*.DLL` and `EXT-MS-WIN-*.DLL` modules are false negatives, but hopefully something else turns up in the list.

**Comment by arduano** [comment]
https://pastebin.com/npcKuW1y

**Comment by mrry** [comment]
From the list of missing dependencies:

> `CUDNN64_6.DLL`

It looks like that DLL depends on cuDNN 6! I assume at some point our nightly builds changed to use cuDNN 6 instead of cuDNN 5.1. Can you try upgrading to cuDNN 6, updating all of the necessary paths, and see if that fixes the problem?

**Comment by arduano** [comment]
Yay!
It finally works!
Thanks

**Comment by mrry** [comment]
Thanks for persevering! I'll have to figure out how to upgrade the script so that we can handle cuDNN 5.1 versus 6 issues....

**Comment by afung01** [comment]
I know this issue has been beaten to death but I can't seem to figure out what I am doing wrong.

I am using a conda virtual environment with python 3.5.4
I have tensorflow-gpu 1.3 installed via pip install tensorflow-gpu
My CUDA is installed on my D:\ drive (D:\deeplearning\CUDA\v9.0)
I also downloaded cudnn 5.1 as well as cudnn 6 and both cudnn64_5.dll and cudnn64_6.dll are in the D:\deeplearning\CUDA\v9.0\bin folder

I have D:\deeplearning\CUDA\v9.0\bin set in my environment path
I also have a path to MSVCP140.DLL

When I run import tensorflow as tf I am still getting  ImportError: No module named '_pywrap_tensorflow_internal'

I am not sure if it makes a difference but I do have CUDA 9 installed instead of CUDA 8 and visual studios 2017.

**Comment by arduano** [comment]
I had CUDA 8.
If CUDA 8 doesn't work, try running the self-check script (scroll up and find it).
If that doesn't work either, run dependency walker and send in the list of dependencies.

**Comment by afung01** [comment]
Yes I just verified that it needs CUDA 8 (runtime and development). It works now thanks!

**Comment by will2codefresher** [comment]
DO NOT USER python 3.6 ,try python 3.5

**Comment by arduano** [comment]
Tensorflow has moved on to python 3.6 quite a while ago

**Comment by will2codefresher** [comment]
I will try 3.6 again with CUDA 9.0. 
Thx arduano

**Comment by ermyas04** [comment]
ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

Traceback (most recent call last):
  File "C:\Users\user\Anaconda3\envs\teff\lib\site-packages\IPython\core\interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-36-eeb151527e4e>", line 1, in <module>
    model.fit(X, y,
NameError: name 'model' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\Anaconda3\envs\teff\lib\site-packages\IPython\core\interactiveshell.py", line 2044, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'NameError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\user\Anaconda3\envs\teff\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\user\Anaconda3\envs\teff\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\Anaconda3\envs\teff\lib\site-packages\IPython\core\ultratb.py", line 1148, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "C:\Users\user\Anaconda3\envs\teff\lib\site-packages\IPython\core\ultratb.py", line 316, in wrapped
    return f(*args, **kwargs)
  File "C:\Users\user\Anaconda3\envs\teff\lib\site-packages\IPython\core\ultratb.py", line 350, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "C:\Users\user\Anaconda3\envs\teff\lib\inspect.py", line 1502, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
  File "C:\Users\user\Anaconda3\envs\teff\lib\inspect.py", line 1460, in getframeinfo
    filename = getsourcefile(frame) or getfile(frame)
  File "C:\Users\user\Anaconda3\envs\teff\lib\inspect.py", line 696, in getsourcefile
    if getattr(getmodule(object, filename), '__loader__', None) is not None:
  File "C:\Users\user\Anaconda3\envs\teff\lib\inspect.py", line 733, in getmodule
    if ismodule(module) and hasattr(module, '__file__'):
  File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "C:\Users\user\Anaconda3\envs\teff\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\__init__.py", line 42, in <module>
    from . _api.v2 import audio
  File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\_api\v2\audio\__init__.py", line 10, in <module>
    from tensorflow.python.ops.gen_audio_ops import decode_wav
  File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\ops\gen_audio_ops.py", line 8, in <module>
    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow
  File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "C:\Users\user\Anaconda3\envs\teff\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\user\Anaconda3\envs\teff\lib\site-packages\IPython\core\interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-36-eeb151527e4e>", line 1, in <module>
    model.fit(X, y,
NameError: name 'model' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\Anaconda3\envs\teff\lib\site-packages\IPython\core\interactiveshell.py", line 2044, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'NameError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\user\Anaconda3\envs\teff\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\user\Anaconda3\envs\teff\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by ermyas04** [comment]
> ERROR:root:Internal Python error in the inspect module.
> Below is the traceback from this internal error.
> 
> Traceback (most recent call last):
> File "C:\Users\user\Anaconda3\envs\teff\lib\site-packages\IPython\core\interactiveshell.py", line 3331, in run_code
> exec(code_obj, self.user_global_ns, self.user_ns)
> File "", line 1, in
> model.fit(X, y,
> NameError: name 'model' is not defined
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "C:\Users\user\Anaconda3\envs\teff\lib\site-packages\IPython\core\interactiveshell.py", line 2044, in showtraceback
> stb = value._render_traceback_()
> AttributeError: 'NameError' object has no attribute '_render_traceback_'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in
> from tensorflow.python.pywrap_tensorflow_internal import *
> File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in
> _pywrap_tensorflow_internal = swig_import_helper()
> File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
> _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
> File "C:\Users\user\Anaconda3\envs\teff\lib\imp.py", line 242, in load_module
> return load_dynamic(name, filename, file)
> File "C:\Users\user\Anaconda3\envs\teff\lib\imp.py", line 342, in load_dynamic
> return _load(spec)
> ImportError: DLL load failed: The specified module could not be found.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "C:\Users\user\Anaconda3\envs\teff\lib\site-packages\IPython\core\ultratb.py", line 1148, in get_records
> return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
> File "C:\Users\user\Anaconda3\envs\teff\lib\site-packages\IPython\core\ultratb.py", line 316, in wrapped
> return f(*args, **kwargs)
> File "C:\Users\user\Anaconda3\envs\teff\lib\site-packages\IPython\core\ultratb.py", line 350, in _fixed_getinnerframes records = fix_frame_records_filenames(inspect.getinnerframes(etb, context)) File "C:\Users\user\Anaconda3\envs\teff\lib\inspect.py", line 1502, in getinnerframes frameinfo = (tb.tb_frame,) + getframeinfo(tb, context) File "C:\Users\user\Anaconda3\envs\teff\lib\inspect.py", line 1460, in getframeinfo filename = getsourcefile(frame) or getfile(frame) File "C:\Users\user\Anaconda3\envs\teff\lib\inspect.py", line 696, in getsourcefile if getattr(getmodule(object, filename), '**loader**', None) is not None: File "C:\Users\user\Anaconda3\envs\teff\lib\inspect.py", line 733, in getmodule if ismodule(module) and hasattr(module, '**file**'): File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\tensorflow__init__.py", line 50, in **getattr**
> module = self._load() File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\tensorflow__init__.py", line 44, in _load
> module = _importlib.import_module(self.**name**) File "C:\Users\user\Anaconda3\envs\teff\lib\importlib__init__.py", line 127, in import_module
> return _bootstrap._gcd_import(name[level:], package, level)
> File "", line 1006, in _gcd_import
> File "", line 983, in _find_and_load
> File "", line 953, in _find_and_load_unlocked
> File "", line 219, in _call_with_frames_removed
> File "", line 1006, in _gcd_import
> File "", line 983, in _find_and_load
> File "", line 967, in _find_and_load_unlocked
> File "", line 677, in _load_unlocked
> File "", line 728, in exec_module
> File "", line 219, in _call_with_frames_removed File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\tensorflow_core__init__.py", line 42, in
> from . _api.v2 import audio File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\tensorflow_core_api\v2\audio__init__.py", line 10, in
> from tensorflow.python.ops.gen_audio_ops import decode_wav
> File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\ops\gen_audio_ops.py", line 8, in
> from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\tensorflow__init__.py", line 50, in **getattr**
> module = self._load() File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\tensorflow__init__.py", line 44, in _load
> module = _importlib.import_module(self.**name**) File "C:\Users\user\Anaconda3\envs\teff\lib\importlib__init__.py", line 127, in import_module
> return _bootstrap._gcd_import(name[level:], package, level) File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python__init__.py", line 49, in
> from tensorflow.python import pywrap_tensorflow
> File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 74, in
> raise ImportError(msg)
> ImportError: Traceback (most recent call last):
> File "C:\Users\user\Anaconda3\envs\teff\lib\site-packages\IPython\core\interactiveshell.py", line 3331, in run_code
> exec(code_obj, self.user_global_ns, self.user_ns)
> File "", line 1, in
> model.fit(X, y,
> NameError: name 'model' is not defined
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "C:\Users\user\Anaconda3\envs\teff\lib\site-packages\IPython\core\interactiveshell.py", line 2044, in showtraceback
> stb = value._render_traceback_()
> AttributeError: 'NameError' object has no attribute '_render_traceback_'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in
> from tensorflow.python.pywrap_tensorflow_internal import *
> File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in
> _pywrap_tensorflow_internal = swig_import_helper()
> File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
> _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
> File "C:\Users\user\Anaconda3\envs\teff\lib\imp.py", line 242, in load_module
> return load_dynamic(name, filename, file)
> File "C:\Users\user\Anaconda3\envs\teff\lib\imp.py", line 342, in load_dynamic
> return _load(spec)
> ImportError: DLL load failed: The specified module could not be found.
> 
> Failed to load the native TensorFlow runtime.
> 
> See https://www.tensorflow.org/install/errors
> 
> for some common reasons and solutions. Include the entire stack trace
> above this error message when asking for help.

I have this error plz help
