### ISSUE TITLE
//tensorflow/python:nn_test is failing on Windows

### ISSUE THREAD

**Issue by meteorcloudy** [tensorflow/tensorflow#11345]
https://ci.tensorflow.org/job/tf-master-win-bzl/1218/consoleFull
```
18:54:32 INFO: From Testing //py_test_dir/tensorflow/python:nn_test:
18:54:32 ==================== Test output for //py_test_dir/tensorflow/python:nn_test:
18:54:32 ......................................F...........
18:54:32 ======================================================================
18:54:32 FAIL: testOutput4DInput123 (__main__.MomentsTest)
18:54:32 ----------------------------------------------------------------------
18:54:32 Traceback (most recent call last):
18:54:32   File "\\?\c:\temp\Bazel.runfiles_nwtmklpc\runfiles\org_tensorflow\py_test_dir\tensorflow\python\ops\nn_test.py", line 878, in testOutput4DInput123
18:54:32     self.doOutputTest((10, 10, 10, 30), (1, 2, 3))
18:54:32   File "\\?\c:\temp\Bazel.runfiles_nwtmklpc\runfiles\org_tensorflow\py_test_dir\tensorflow\python\ops\nn_test.py", line 854, in doOutputTest
18:54:32     self.assertAllClose(variance, expected_var, rtol=tol, atol=tol)
18:54:32   File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\framework\test_util.py", line 660, in assertAllClose
18:54:32     self._assertArrayLikeAllClose(a, b, rtol=rtol, atol=atol)
18:54:32   File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\framework\test_util.py", line 630, in _assertArrayLikeAllClose
18:54:32     np.testing.assert_allclose(b, a, rtol=rtol, atol=atol, err_msg=msg)
18:54:32   File "C:\Program Files\Anaconda3\lib\site-packages\numpy\testing\utils.py", line 1411, in assert_allclose
18:54:32     verbose=verbose, header=header, equal_nan=equal_nan)
18:54:32   File "C:\Program Files\Anaconda3\lib\site-packages\numpy\testing\utils.py", line 796, in assert_array_compare
18:54:32     raise AssertionError(msg)
18:54:32 AssertionError: 
18:54:32 Not equal to tolerance rtol=0.0001, atol=0.0001
18:54:32 None
18:54:32 (mismatch 100.0%)
18:54:32  x: array([[[[ 0.000834]]],
18:54:32 
18:54:32 ...
18:54:32  y: array([[[[ 0.001117]]],
18:54:32 
18:54:32 ...
```

**Comment by meteorcloudy** [comment]
Possible culprit: https://github.com/tensorflow/tensorflow/commit/eccd162119675d0bf5bc6f8e6a93dcda7ab6db4a

**Comment by andydavis1** [comment]
@ekelsen any chance this is related to recent changes to the moments calculation?

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Awaiting TensorFlower: It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Awaiting TensorFlower: It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Awaiting TensorFlower: It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging TensorFlower: It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.
