### ISSUE TITLE
saver will cause crash,error message:"InvalidArgumentError: Shape [xx] has negative dimensions"

### ISSUE THREAD

**Issue by jowettcz** [tensorflow/tensorflow#11367]
### It should be a bug of tensorflow
add the saver will cause the procedure crash. error message is strange, as following:
_### InvalidArgumentError (see above for traceback): Shape [-1,32,32,3] has negative dimensions
	 [[Node: x = Placeholder[dtype=DT_FLOAT, shape=[?,32,32,3], _device="/job:localhost/replica:0/task:0/cpu:0"]()]]_

the added part is:
            if (i % 1000 == 0) or (i == num_iterations - 1):
                # Save all variables of the TensorFlow graph to a
                # checkpoint. Append the global_step counter
                # to the filename so we save the last several checkpoints.
                saver.save(sess,
                           save_path=save_dir,
                           global_step=train_step)

### System information
== cat /etc/issue ===============================================
Darwin zhangdeMacBook-Pro.local 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64
Mac OS X 10.12.5

== are we in docker =============================================
No

== compiler =====================================================
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

== uname -a =====================================================
Darwin zhangdeMacBook-Pro.local 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64

== check pips ===================================================
numpy (1.13.0)
protobuf (3.3.0)
tensorflow (1.2.1)

== check for virtualenv =========================================
False

== tensorflow import ============================================
tf.VERSION = 1.2.1
tf.GIT_VERSION = v1.2.0-5-g435cdfc
tf.COMPILER_VERSION = v1.2.0-5-g435cdfc
Sanity check: array([1], dtype=int32)

== env ==========================================================
LD_LIBRARY_PATH is unset
DYLD_LIBRARY_PATH is unset

== nvidia-smi ===================================================

== cuda libs  ===================================================

Tensorflow version:
v1.2.0-5-g435cdfc 1.2.1

### Source code / logs
source code:
```python
#coding=utf-8
import tensorflow as tf
import numpy as np
import cifar10
import preprocess
from six.moves import xrange
import os

img_size = 32
img_height = img_size
img_width = img_size
img_channel = 3

first_conv_feamap = 16
filter_size = 5
pool_size = 4

second_conv_feamap = 32

fcn1_size = 1024

epoch = 60
batch_size = 50


def weight_variable(shape):
    """weight_variable generates a weight variable of a given shape."""
    initial = tf.truncated_normal(shape, stddev=0.1)
    return tf.Variable(initial)

def bias_variable(shape):
    initial = tf.constant(0.1,shape=shape)
    return tf.Variable(initial)

def conv2d(x, W):
  """conv2d returns a 2d convolution layer with full stride."""
  return tf.nn.conv2d(x, W, strides=[1, 1, 1, 1], padding='SAME')

def max_pool_2x2(x):
  """max_pool_2x2 downsamples a feature map by 2X."""
  #ksize是窗口大小，stride是步长，4->1步长正好是2
  return tf.nn.max_pool(x, ksize=[1, 2, 2, 1],
                        strides=[1, 2, 2, 1], padding='SAME')


def sequence_batch(images, labels, idx,_batch_size):

    # Use the random index to select random images and labels.
    x_batch = images[idx:idx+_batch_size, :, :, :]
    y_batch = labels[idx:idx+_batch_size, :]

    return x_batch, y_batch

#Procedure start now!

images,training_class,labels = cifar10.load_training_data()

test_images,test_class,test_labels = cifar10.load_test_data()


log_dir = os.getcwd() + '/log'
print('log_dir is ' + log_dir)
if not os.path.exists(log_dir):
    os.makedirs(log_dir)


save_dir = os.getcwd() + '/checkpoints'
print('save_dir is ' + save_dir)
if not os.path.exists(save_dir):
    os.makedirs(save_dir)


x = tf.placeholder(tf.float32, shape=[None,img_height,img_width,img_channel], name='x')
y_ = tf.placeholder(tf.float32, shape=[None, 10], name='y_')
y_cls = tf.argmax(y_, dimension=1)

x = tf.reshape(x, shape=[-1, img_height, img_width, img_channel])

with tf.name_scope('conv1'):
    w_conv1 = weight_variable([filter_size, filter_size, img_channel, first_conv_feamap])
    b_conv1 = bias_variable([first_conv_feamap])

    h_conv1 = tf.nn.relu(conv2d(x, w_conv1) + b_conv1)
    h_pool1 = max_pool_2x2(h_conv1)

with tf.name_scope('conv2'):
    w_conv2 = weight_variable([filter_size, filter_size, first_conv_feamap, second_conv_feamap])
    b_conv2 = bias_variable([second_conv_feamap])

    h_conv2 = tf.nn.relu(conv2d(h_pool1, w_conv2) + b_conv2)
    h_pool2 = max_pool_2x2(h_conv2)

conv2_size = 8

with tf.name_scope('fcn1'):
    w_fcn1 = weight_variable([conv2_size * conv2_size * second_conv_feamap, fcn1_size])
    b_fcn1 = bias_variable([fcn1_size])

    # change with the image size and convlo
    h_pool2_flat = tf.reshape(h_pool2, [-1, conv2_size * conv2_size * second_conv_feamap])
    h_fcn1 = tf.nn.relu(tf.matmul(h_pool2_flat, w_fcn1) + b_fcn1)

    keep_prob = tf.placeholder(tf.float32)
    h_fcn1_drop = tf.nn.dropout(h_fcn1, keep_prob)

with tf.name_scope('fcn2'):
    w_fcn2 = weight_variable([fcn1_size, 10])
    b_fcn2 = bias_variable([10])

    y_cnn = tf.matmul(h_fcn1_drop, w_fcn2) + b_fcn2



cross_entropy = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(labels=y_,logits=y_cnn))

train_step = tf.train.AdamOptimizer(learning_rate=1e-4).minimize(cross_entropy)

correct_prediction = tf.equal(tf.arg_max(y_cnn,1),tf.arg_max(y_,1))

accuracy = tf.reduce_mean(tf.cast(correct_prediction,tf.float32))



saver = tf.train.Saver()



with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)


    num_iterations = int(len(images)/batch_size)

    idx = 0

    for j in xrange(60):
        for i in xrange(num_iterations):


            x_batch,y_batch = sequence_batch(images,labels,idx,batch_size)

            print("x_batch shape: " + str(x_batch.shape))
            print("y_batch shape: " + str(y_batch.shape))

            train_step.run(
                feed_dict={
                    x: x_batch,
                    y_: y_batch,
                    keep_prob: 0.5
                }
            )

            idx = idx + batch_size

            if i%100 == 0:
                training_feed_dict = {
                    x: images,
                    y_: labels,
                    keep_prob: 1.0
                }

                test_feed_dict = {
                    x: test_images,
                    y_: test_labels,
                    keep_prob: 1.0
                }



                train_accuracy = accuracy.eval(
                    feed_dict=training_feed_dict
                )
                print('step %d, training accuracy %g' % (i, train_accuracy))

                test_accuracy = accuracy.eval(
                    feed_dict=test_feed_dict
                )
                print('step %d, test accuracy %g' % (i, test_accuracy))

            if (i % 1000 == 0) or (i == num_iterations - 1):
                # Save all variables of the TensorFlow graph to a
                # checkpoint. Append the global_step counter
                # to the filename so we save the last several checkpoints.
                saver.save(sess,
                           save_path=save_dir,
                           global_step=train_step)

                print("Saved checkpoint.")


    print('test accuracy in every epoch %g' % accuracy.eval(
        feed_dict={
            x: test_images,
            y_: test_labels,
            keep_prob: 1.0
        }
        )
    )

```

**Comment by jowettcz** [comment]
Now i found the cause. If I remove the global_step=train_step when saving the saver, error will disappear. 
So the reason should be train_step been wrongly run without feed_dict. It easily mislead developer wasting a lot of time checking the data-loading process.
Now I closed it. But i think this message of the issue is still useful to other developers.

**Comment by nosqlcoco** [comment]
I got the same error when i use this code `summary,test_accuracy = sess.run([merged, accuracy], feed_dict={x: test_data, y: test_labels, input_seq_len: test_seq_len, keep_prob: 1})`

 Info
- OS: Ubuntu 16.04LTS
- TF version : Release 1.2.1 
- Python: 3.5.3

Source code & error log
```
import tensorflow as tf
from tensorflow.contrib import rnn
import numpy as np
import random

#==========
# Data Set
#==========
class HandriseData(object):
    """
    Load train-set and test-set from csv file
    """
    def __init__(self):
        self.data = []
        self.labels = []
        self.seq_len = []

        self.test_data = []
        self.test_labels = []
        self.test_seq_len = []
        
        with open("./dataset/train/train.csv", 'r', newline="") as csv_file:
            train_sets = [np.array(line.split(","), np.float).tolist() for line in csv_file]

            for i in range(0, len(train_sets), 3):
                tmp_len = len(train_sets[i])
                self.seq_len.append(tmp_len)

                train_sets[i].extend([0 for j in range(0, 80 - tmp_len)])
                train_sets[i + 1].extend([0 for j in range(0, 80 - tmp_len)])
                train_sets[i + 2].extend([0 for j in range(0, 80 - tmp_len)])
                self.data.append(np.array(train_sets[i : i + 3]).flatten())
                
            self.labels = np.loadtxt("./dataset/train/train.label.csv", dtype = np.int).tolist()

    def next(self, batch_size = 100):
        """
        input: batch_size
        output: (x_batch, y_batch, seq_len)
        """
        if batch_size <= 0:
            return;
        
        x_batch = []
        y_batch = []
        #real length
        seq_len = []
        
        rand_list = random.sample(range(0, len(self.data)), batch_size)
        for j in rand_list:
            x_batch.append(self.data[j])
            y_batch.append(self.labels[j])
            seq_len.append(self.seq_len[j])
            
        return (x_batch, y_batch, seq_len)
    
    def get_test_set(self):
        """
        Get test set
        """
        with open("./dataset/test/test.csv", 'r', newline="") as csv_file:
            test_sets = [np.array(line.split(","), np.float).tolist() for line in csv_file]

            for i in range(0, len(test_sets), 3):
                tmp_len = len(test_sets[i])
                self.test_seq_len.append(tmp_len)

                test_sets[i].extend([0 for j in range(0, 80 - tmp_len)])
                test_sets[i + 1].extend([0 for j in range(0, 80 - tmp_len)])
                test_sets[i + 2].extend([0 for j in range(0, 80 - tmp_len)])
                self.test_data.append(np.array(test_sets[i : i + 3]).flatten())
                
            self.test_labels = np.loadtxt("./dataset/test/test.label.csv", dtype = np.int).tolist()
        return (self.test_data, self.test_labels, self.test_seq_len)
#==========
# MODEL
#==========

#Parameter
training_iters = 1001
batch_size = 100
learning_rate = 0.01

n_steps = 80 #max steps
n_input = 3 #input
n_hidden_unis = 128 #hidden neurons
n_class = 2 #label (0,1)


#Graph input
x = tf.placeholder(tf.float32, [None, n_steps, n_input], name="x_input") #input 
y = tf.placeholder(tf.int32, [None], name="y_label") #real label
y_ = tf.one_hot(y, 2) #one hot vector
input_seq_len = tf.placeholder(tf.int32, [None], name="input_seq_len")
keep_prob = tf.placeholder(tf.float32, name="keep_prob")

#define weight
weights = {
    #(n_input,n_hidden_unis)
    'in': tf.Variable(tf.random_normal([n_input, n_hidden_unis],stddev=0.1)),
    #(n_hidden_unis,n_class)
    'out': tf.Variable(tf.random_normal([n_hidden_unis, n_class],stddev=0.1))
}
#define bias
biases = {
    #(n_hidden_unis, )
    'in': tf.Variable(tf.constant(0.1, shape=[n_hidden_unis, ])),
    #(n_class, )
    'out': tf.Variable(tf.constant(0.1, shape=[n_class, ]))
}

#Define RNN(LSTM) neuron networks
def LSTM_RNN(x, weights, biases, seq_len, keep_prob = 1, activation_function = tf.nn.softmax):
    #hidden layer for input to cell
    #==> (batch_size * n_steps, n_input)
    x = tf.reshape(x, [-1, n_input])
    #==>(batch_size * n_steps, n_hidden_unis)
    x_in = tf.matmul(x, weights['in']) + biases['in']
    #==>(batch_size, n_steps, n_hidden_unis)
    x_in = tf.reshape(x_in, [-1, n_steps, n_hidden_unis])

    lstm_cell = tf.contrib.rnn.BasicLSTMCell(n_hidden_unis, forget_bias=1.0, state_is_tuple=True, reuse=True)
    _init_state = lstm_cell.zero_state(batch_size, dtype = tf.float32)

    outputs, states = tf.nn.dynamic_rnn(lstm_cell, x_in, time_major=False, sequence_length=seq_len, dtype=tf.float32)

    Wx_plus_b = tf.matmul(states[1], weights['out'] + biases['out'])
    
    output = activation_function(Wx_plus_b)
    
    output = tf.nn.dropout(output, keep_prob)
    return output

#==========
# TRAIN
#==========
def train():
    pred = LSTM_RNN(x, weights, biases, input_seq_len, keep_prob, tf.nn.softmax)
    tf.summary.histogram('out',pred)
    cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=pred, labels=y_))
    tf.summary.scalar('loss', cost) 
    
    train_op = tf.train.GradientDescentOptimizer(learning_rate).minimize(cost)
    
    correct_pred = tf.equal(tf.argmax(pred,1), tf.argmax(y_,1))
    pred_output = tf.cast(correct_pred, tf.int32, name="pred_output")
    
    accuracy = tf.reduce_mean(tf.cast(correct_pred, tf.float32))
    
    merged = tf.summary.merge_all()
    init = tf.global_variables_initializer()
    
    saver = tf.train.Saver(max_to_keep=5)
    with tf.Session() as sess:

        file_writer = tf.summary.FileWriter('./tensorboard', sess.graph)
        
        sess.run(init)
        train_accuracys = []
        test_accuracys = []
        
        hand_rise = HandriseData()
       
        test_data, test_labels, test_seq_len = hand_rise.get_test_set()
        test_data = np.array(test_data).reshape([-1, n_steps, n_input])
        
        for step in range(1, training_iters):
            x_batch, y_batch, seq_len = hand_rise.next(batch_size)
            x_batch = np.array(x_batch).reshape([-1, n_steps, n_input])
            
            if step % 100 == 0:
                train_accuracy = sess.run(accuracy, feed_dict={x: x_batch, y: y_batch, input_seq_len: seq_len, keep_prob: 1})
                train_accuracys.append(train_accuracy)
                
                summary,test_accuracy = sess.run([merged,accuracy], feed_dict={x: test_data, y: test_labels, input_seq_len: test_seq_len, keep_prob: 1})
                test_accuracys.append(test_accuracy)
                
                file_writer.add_summary(summary, step)
                
                print("step:" + str(step) + ",accuracy:" + str(train_accuracy))
                
            else:
                sess.run(train_op, feed_dict={x: x_batch, y: y_batch, input_seq_len: seq_len, keep_prob: 0.5})
                
        file_writer.close()       
        print("Final test accuracy is " + str(test_accuracys[-1]))
        
        #save checkpoint file
        saver.save(sess, 'model/model.ckpt', global_step=step)
        #save pb file
        output_graph_def = tf.graph_util.convert_variables_to_constants(sess, sess.graph_def, output_node_names=['pred_output'])
        with tf.gfile.FastGFile("model/handrise.pb", mode = 'wb') as f:
            f.write(output_graph_def.SerializeToString())
```
error
```
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
/home/ksq/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1138     try:
-> 1139       return fn(*args)
   1140     except errors.OpError as e:

/home/ksq/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py in _run_fn(session, feed_dict, fetch_list, target_list, options, run_metadata)
   1120                                  feed_dict, fetch_list, target_list,
-> 1121                                  status, run_metadata)
   1122 

/home/ksq/anaconda3/lib/python3.5/contextlib.py in __exit__(self, type, value, traceback)
     65             try:
---> 66                 next(self.gen)
     67             except StopIteration:

/home/ksq/.local/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py in raise_exception_on_not_ok_status()
    465           compat.as_text(pywrap_tensorflow.TF_Message(status)),
--> 466           pywrap_tensorflow.TF_GetCode(status))
    467   finally:

InvalidArgumentError: Shape [-1,80,3] has negative dimensions
	 [[Node: x_input_1 = Placeholder[dtype=DT_FLOAT, shape=[?,80,3], _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

During handling of the above exception, another exception occurred:

InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-7-a64368429fdf> in <module>()
    223     plt.show()
    224 
--> 225 train()

<ipython-input-7-a64368429fdf> in train()
    186                 train_accuracys.append(train_accuracy)
    187 
--> 188                 summary,test_accuracy = sess.run([merged,accuracy], feed_dict={x: test_data, y: test_labels, input_seq_len: test_seq_len, keep_prob: 1})
    189                 test_accuracys.append(test_accuracy)
    190 

/home/ksq/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py in run(self, fetches, feed_dict, options, run_metadata)
    787     try:
    788       result = self._run(None, fetches, feed_dict, options_ptr,
--> 789                          run_metadata_ptr)
    790       if run_metadata:
    791         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

/home/ksq/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
    995     if final_fetches or final_targets:
    996       results = self._do_run(handle, final_targets, final_fetches,
--> 997                              feed_dict_string, options, run_metadata)
    998     else:
    999       results = []

/home/ksq/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1130     if handle is None:
   1131       return self._do_call(_run_fn, self._session, feed_dict, fetch_list,
-> 1132                            target_list, options, run_metadata)
   1133     else:
   1134       return self._do_call(_prun_fn, self._session, handle, feed_dict,

/home/ksq/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1150         except KeyError:
   1151           pass
-> 1152       raise type(e)(node_def, op, message)
   1153 
   1154   def _extend_graph(self):

InvalidArgumentError: Shape [-1,80,3] has negative dimensions
	 [[Node: x_input_1 = Placeholder[dtype=DT_FLOAT, shape=[?,80,3], _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Caused by op 'x_input_1', defined at:
  File "/home/ksq/anaconda3/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ksq/anaconda3/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ksq/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py", line 3, in <module>
    app.launch_new_instance()
  File "/home/ksq/anaconda3/lib/python3.5/site-packages/traitlets/config/application.py", line 653, in launch_instance
    app.start()
  File "/home/ksq/anaconda3/lib/python3.5/site-packages/ipykernel/kernelapp.py", line 474, in start
    ioloop.IOLoop.instance().start()
  File "/home/ksq/anaconda3/lib/python3.5/site-packages/zmq/eventloop/ioloop.py", line 162, in start
    super(ZMQIOLoop, self).start()
  File "/home/ksq/anaconda3/lib/python3.5/site-packages/tornado/ioloop.py", line 887, in start
    handler_func(fd_obj, events)
  File "/home/ksq/anaconda3/lib/python3.5/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/ksq/anaconda3/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "/home/ksq/anaconda3/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/ksq/anaconda3/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/home/ksq/anaconda3/lib/python3.5/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/ksq/anaconda3/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 276, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/home/ksq/anaconda3/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 228, in dispatch_shell
    handler(stream, idents, msg)
  File "/home/ksq/anaconda3/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 390, in execute_request
    user_expressions, allow_stdin)
  File "/home/ksq/anaconda3/lib/python3.5/site-packages/ipykernel/ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/home/ksq/anaconda3/lib/python3.5/site-packages/ipykernel/zmqshell.py", line 501, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/home/ksq/anaconda3/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2717, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/home/ksq/anaconda3/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2821, in run_ast_nodes
    if self.run_code(code, result):
  File "/home/ksq/anaconda3/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-55a42d5b2ae9>", line 104, in <module>
    x = tf.placeholder(tf.float32, [None, n_steps, n_input], name="x_input") #input
  File "/home/ksq/.local/lib/python3.5/site-packages/tensorflow/python/ops/array_ops.py", line 1530, in placeholder
    return gen_array_ops._placeholder(dtype=dtype, shape=shape, name=name)
  File "/home/ksq/.local/lib/python3.5/site-packages/tensorflow/python/ops/gen_array_ops.py", line 1954, in _placeholder
    name=name)
  File "/home/ksq/.local/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/home/ksq/.local/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/ksq/.local/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Shape [-1,80,3] has negative dimensions
	 [[Node: x_input_1 = Placeholder[dtype=DT_FLOAT, shape=[?,80,3], _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

```

**Comment by nosqlcoco** [comment]
I find what caused the error,  I delete this line `_init_state = lstm_cell.zero_state(batch_size, dtype = tf.float32)` in `LSTM_RNN()` function of source. and running successfully.
