### ISSUE TITLE
Python 3 test failure: //tensorflow/python:default_platform_gfile_test

### ISSUE THREAD

**Issue by caisq** [tensorflow/tensorflow#1146]
This happens on both Linux and Mac under Python 3:
`bazel test //tensorflow/python:default_platform_gfile_test`

Failure log:

> -----------------------------------------------------------------------------
> ..........E........
> ======================================================================
> ERROR: testOpen (__main__.FunctionTests)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/usr/local/google/home/cais/.cache/bazel/_bazel_cais/10ddfdc323bb20c9bc23987d4925ae7b/tensorflow-caisq/bazel-out/local_linux-py3-fastbuild/bin/tensorflow/python/default_platform_gfile_test.runfiles/tensorflow/python/platform/default/gfile_test.py", line 225, in testOpen
>     f.write("foo")
>   File "/usr/local/google/home/cais/.cache/bazel/_bazel_cais/10ddfdc323bb20c9bc23987d4925ae7b/tensorflow-caisq/bazel-out/local_linux-py3-fastbuild/bin/tensorflow/python/default_platform_gfile_test.runfiles/tensorflow/python/platform/default/_gfile.py", line 45, in sync
>     return fn(self, *args, **kwargs)
>   File "/usr/local/google/home/cais/.cache/bazel/_bazel_cais/10ddfdc323bb20c9bc23987d4925ae7b/tensorflow-caisq/bazel-out/local_linux-py3-fastbuild/bin/tensorflow/python/default_platform_gfile_test.runfiles/tensorflow/python/platform/default/_gfile.py", line 98, in write
>     self._fp.write(data)
> TypeError: 'str' does not support the buffer interface
> 
> ----------------------------------------------------------------------
> Ran 19 tests in 0.043s
> 
> FAILED (errors=1)

**Comment by caisq** [comment]
@vrv
