### ISSUE TITLE
Python 3 test failure: //tensorflow/tensorboard/backend:server_test

### ISSUE THREAD

**Issue by caisq** [tensorflow/tensorflow#1147]
This seems to on both Linux and Mac, under Python 3:
`bazel test //tensorflow/tensorboard/backend:server_test`

Failure log:

> -----------------------------------------------------------------------------
> .127.0.0.1 - - [17/Feb/2016 18:23:02] code 404, message Not Found
> 127.0.0.1 - - [17/Feb/2016 18:23:02] "GET /../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../etc/passwd HTTP/1.1" 404 -
> .127.0.0.1 - - [17/Feb/2016 18:23:03] "GET /data/histograms?tag=histogram&run=run1 HTTP/1.1" 200 -
> E127.0.0.1 - - [17/Feb/2016 18:23:03] "GET /data/images?tag=image&run=run1 HTTP/1.1" 200 -
> E127.0.0.1 - - [17/Feb/2016 18:23:04] "GET / HTTP/1.1" 200 -
> ./usr/local/google/home/cais/.cache/bazel/_bazel_cais/10ddfdc323bb20c9bc23987d4925ae7b/tensorflow-caisq/bazel-out/local_linux-py3-fastbuild/bin/tensorflow/tensorboard/backend/server_test.runfiles/tensorflow/python/platform/default/_resource_loader.py:49: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
>   logging.warning('IOError %s on path %s', e, path)
> WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/usr/local/google/home/cais/.cache/bazel/_bazel_cais/10ddfdc323bb20c9bc23987d4925ae7b/tensorflow-caisq/bazel-out/local_linux-py3-fastbuild/bin/tensorflow/tensorboard/backend/server_test.runfiles/tensorflow/tensorboard/asdf' on path /usr/local/google/home/cais/.cache/bazel/_bazel_cais/10ddfdc323bb20c9bc23987d4925ae7b/tensorflow-caisq/bazel-out/local_linux-py3-fastbuild/bin/tensorflow/tensorboard/backend/server_test.runfiles/tensorflow/tensorboard/asdf
> 127.0.0.1 - - [17/Feb/2016 18:23:04] code 404, message Not Found
> 127.0.0.1 - - [17/Feb/2016 18:23:04] "GET /asdf HTTP/1.1" 404 -
> .127.0.0.1 - - [17/Feb/2016 18:23:05] "GET /data/runs HTTP/1.1" 200 -
> E127.0.0.1 - - [17/Feb/2016 18:23:05] "GET /data/scalars?sample_count=10 HTTP/1.1" 200 -
> E127.0.0.1 - - [17/Feb/2016 18:23:06] "GET /data/scalars?sample_count=999999 HTTP/1.1" 200 -
> E.
> ======================================================================
> ERROR: testHistograms (__main__.TensorboardServerTest)
> Test the format of /data/histograms.
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/usr/local/google/home/cais/.cache/bazel/_bazel_cais/10ddfdc323bb20c9bc23987d4925ae7b/tensorflow-caisq/bazel-out/local_linux-py3-fastbuild/bin/tensorflow/tensorboard/backend/server_test.runfiles/tensorflow/tensorboard/backend/server_test.py", line 105, in testHistograms
>     self._getJson('/data/histograms?tag=histogram&run=run1'),
>   File "/usr/local/google/home/cais/.cache/bazel/_bazel_cais/10ddfdc323bb20c9bc23987d4925ae7b/tensorflow-caisq/bazel-out/local_linux-py3-fastbuild/bin/tensorflow/tensorboard/backend/server_test.runfiles/tensorflow/tensorboard/backend/server_test.py", line 71, in _getJson
>     return json.load(response)
>   File "/usr/lib/python3.4/json/__init__.py", line 268, in load
>     parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
>   File "/usr/lib/python3.4/json/__init__.py", line 312, in loads
>     s.__class__.__name__))
> TypeError: the JSON object must be str, not 'bytes'
> 
> ======================================================================
> ERROR: testImages (__main__.TensorboardServerTest)
> Test listing images and retrieving an individual image.
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/usr/local/google/home/cais/.cache/bazel/_bazel_cais/10ddfdc323bb20c9bc23987d4925ae7b/tensorflow-caisq/bazel-out/local_linux-py3-fastbuild/bin/tensorflow/tensorboard/backend/server_test.runfiles/tensorflow/tensorboard/backend/server_test.py", line 127, in testImages
>     image_json = self._getJson('/data/images?tag=image&run=run1')
>   File "/usr/local/google/home/cais/.cache/bazel/_bazel_cais/10ddfdc323bb20c9bc23987d4925ae7b/tensorflow-caisq/bazel-out/local_linux-py3-fastbuild/bin/tensorflow/tensorboard/backend/server_test.runfiles/tensorflow/tensorboard/backend/server_test.py", line 71, in _getJson
>     return json.load(response)
>   File "/usr/lib/python3.4/json/__init__.py", line 268, in load
>     parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
>   File "/usr/lib/python3.4/json/__init__.py", line 312, in loads
>     s.__class__.__name__))
> TypeError: the JSON object must be str, not 'bytes'
> 
> ======================================================================
> ERROR: testRuns (__main__.TensorboardServerTest)
> Test the format of the /data/runs endpoint.
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/usr/local/google/home/cais/.cache/bazel/_bazel_cais/10ddfdc323bb20c9bc23987d4925ae7b/tensorflow-caisq/bazel-out/local_linux-py3-fastbuild/bin/tensorflow/tensorboard/backend/server_test.runfiles/tensorflow/tensorboard/backend/server_test.py", line 95, in testRuns
>     self._getJson('/data/runs'),
>   File "/usr/local/google/home/cais/.cache/bazel/_bazel_cais/10ddfdc323bb20c9bc23987d4925ae7b/tensorflow-caisq/bazel-out/local_linux-py3-fastbuild/bin/tensorflow/tensorboard/backend/server_test.runfiles/tensorflow/tensorboard/backend/server_test.py", line 71, in _getJson
>     return json.load(response)
>   File "/usr/lib/python3.4/json/__init__.py", line 268, in load
>     parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
>   File "/usr/lib/python3.4/json/__init__.py", line 312, in loads
>     s.__class__.__name__))
> TypeError: the JSON object must be str, not 'bytes'
> 
> ======================================================================
> ERROR: testSampleScalars (__main__.TensorboardServerTest)
> Test the sample_count parameter of /data/scalars.
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/usr/local/google/home/cais/.cache/bazel/_bazel_cais/10ddfdc323bb20c9bc23987d4925ae7b/tensorflow-caisq/bazel-out/local_linux-py3-fastbuild/bin/tensorflow/tensorboard/backend/server_test.runfiles/tensorflow/tensorboard/backend/server_test.py", line 111, in testSampleScalars
>     samples = self._getJson('/data/scalars?sample_count=%d' % i)
>   File "/usr/local/google/home/cais/.cache/bazel/_bazel_cais/10ddfdc323bb20c9bc23987d4925ae7b/tensorflow-caisq/bazel-out/local_linux-py3-fastbuild/bin/tensorflow/tensorboard/backend/server_test.runfiles/tensorflow/tensorboard/backend/server_test.py", line 71, in _getJson
>     return json.load(response)
>   File "/usr/lib/python3.4/json/__init__.py", line 268, in load
>     parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
>   File "/usr/lib/python3.4/json/__init__.py", line 312, in loads
>     s.__class__.__name__))
> TypeError: the JSON object must be str, not 'bytes'
> 
> ======================================================================
> ERROR: testSampleScalarsWithLargeSampleCount (__main__.TensorboardServerTest)
> Test using a large sample_count.
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/usr/local/google/home/cais/.cache/bazel/_bazel_cais/10ddfdc323bb20c9bc23987d4925ae7b/tensorflow-caisq/bazel-out/local_linux-py3-fastbuild/bin/tensorflow/tensorboard/backend/server_test.runfiles/tensorflow/tensorboard/backend/server_test.py", line 121, in testSampleScalarsWithLargeSampleCount
>     samples = self._getJson('/data/scalars?sample_count=999999')
>   File "/usr/local/google/home/cais/.cache/bazel/_bazel_cais/10ddfdc323bb20c9bc23987d4925ae7b/tensorflow-caisq/bazel-out/local_linux-py3-fastbuild/bin/tensorflow/tensorboard/backend/server_test.runfiles/tensorflow/tensorboard/backend/server_test.py", line 71, in _getJson
>     return json.load(response)
>   File "/usr/lib/python3.4/json/__init__.py", line 268, in load
>     parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
>   File "/usr/lib/python3.4/json/__init__.py", line 312, in loads
>     s.__class__.__name__))
> TypeError: the JSON object must be str, not 'bytes'
> 
> ----------------------------------------------------------------------
> Ran 10 tests in 5.303s
> 
> FAILED (errors=5)
>

**Comment by caisq** [comment]
@danmane
