### ISSUE TITLE
fail to run android example

### ISSUE THREAD

**Issue by scucheri** [tensorflow/tensorflow#11474]
### System information
bazel version:
Build label: 0.5.2-homebrew

java version: "1.8.0_131"

### workspace config:
android_sdk_repository(
  name = "androidsdk",
  api_level = 23,
  build_tools_version = "25.0.1",
  path = "/Users/scucheri/Library/Android/sdk",
)

android_ndk_repository(
    name="androidndk",
    path="/Users/scucheri/Library/Android/sdk/ndk-bundle",
    api_level=14) 

### Describe the problem
error when I run 'bazel build //tensorflow/examples/android:tensorflow_demo' in terminal, could you tell me how to solve this?

### Source code / logs
bazel build //tensorflow/examples/android:tensorflow_demo
WARNING: The major revision of the Android NDK referenced by android_ndk_repository rule 'androidndk' is 15. The major revisions supported by Bazel are [10, 11, 12, 13, 14]. Defaulting to revision 14.
ERROR: /private/var/tmp/_bazel_scucheri/f55efc3e55d5b53a9cbb2375bb9bdf55/external/androidsdk/BUILD.bazel:64:1: Traceback (most recent call last):
        File "/private/var/tmp/_bazel_scucheri/f55efc3e55d5b53a9cbb2375bb9bdf55/external/androidsdk/BUILD.bazel", line 64
                create_system_images_filegroups(system_image_dirs = ["system-ima...", <53 more arguments>])
        File "/private/var/tmp/_bazel_scucheri/f55efc3e55d5b53a9cbb2375bb9bdf55/external/bazel_tools/tools/android/android_sdk_repository_template.bzl", line 246, in create_system_images_filegroups
                int(apidir.split("-")[1])
invalid literal for int() with base 10: "MNC".
ERROR: /private/var/tmp/_bazel_scucheri/f55efc3e55d5b53a9cbb2375bb9bdf55/external/androidsdk/BUILD.bazel:8:1: Target '@androidsdk//:build-tools/25.0.1/lib/dx.jar' contains an error and its package is in error and referenced by '@androidsdk//:dx_jar'.
ERROR: /private/var/tmp/_bazel_scucheri/f55efc3e55d5b53a9cbb2375bb9bdf55/external/androidsdk/BUILD.bazel:8:1: Target '@androidsdk//:dx_jar' contains an error and its package is in error and referenced by '@androidsdk//:dx_jar_import'.
ERROR: /Users/scucheri/AllMyProjects/AndroidStudioProjects/TmallAndroidProjects/tensorflow/WORKSPACE:20:1: Target '@androidsdk//:dx_jar_import' contains an error and its package is in error and referenced by '//external:android/dx_jar_import'.
ERROR: Analysis of target '//tensorflow/examples/android:tensorflow_demo' failed; build aborted.
INFO: Elapsed time: 3.653s

**Comment by andrewharp** [comment]
@scucheri Make sure you have the paths correct. /Users/scucheri/Library/Android/sdk/ndk-bundle should contain ndk-build, and /Users/scucheri/Library/Android/sdk should contain tools/android.

It seems to somehow be getting confused and splitting -MNC out of one of the sdk/.../android-MNC/ dirs rather than the appropriate API level. Do you have the indicated APIs installed? You can check via sdk/tools/android.

**Comment by scucheri** [comment]
yeah,  /Users/scucheri/Library/Android/sdk/ndk-bundle  contains ndk-build. 

Finally I solve this problem by changing the tensorflow source code from r1.2 to r1.0 and change bazel version from 0.5.2 to 0.4.3 .

Is it caused by incompatibility ?

**Comment by andrewharp** [comment]
There shouldn't be any incompatibility. My guess is that changing to TensorFlow 1.0 changed the default SDK level to one you actually have installed. I'd try ensuring that the `android` tool packaged with the SDK shows you have the relevant API levels installed.

**Comment by scucheri** [comment]
where is the default SDK level configured  ?   The workspace.bzl file config if always like below:

workspace config:

android_sdk_repository(
name = "androidsdk",
api_level = 23,
build_tools_version = "25.0.1",
path = "/Users/scucheri/Library/Android/sdk",
)

android_ndk_repository(
name="androidndk",
path="/Users/scucheri/Library/Android/sdk/ndk-bundle",
api_level=14)

**Comment by andrewharp** [comment]
Have you confirmed that these versions are installed in your SDK with the `android `tool?

**Comment by scucheri** [comment]
yeah , they have been installed correctly

**Comment by andrewharp** [comment]
Based on the other issue it seems like you were able to get past this, is that correct?

**Comment by scucheri** [comment]
No, That question is different from this.  This question is about bazel build error.

tensorflow r1.2 & bazel 0.5.2 cause error
tensorflow r1.0 & bazel 0.4.3 build successfully

**Comment by andrewharp** [comment]
Have you tried r1.0 with bazel 0.5.2?

My best guess at the cause is that something is causing it to evaluate the wrong paths when searching the SDK directory looking for API level (it's trying to evaluate "MNC" from a partial path as an integer).

You might have better luck over at https://github.com/bazelbuild/bazel with this, as I doubt it has anything directly to do with TF.

**Comment by andrewharp** [comment]
Closing due to inactivity; please respond with additional details if the issue persists.
