### ISSUE TITLE
import_graph_def input_map not updating all attributes

### ISSUE THREAD

**Issue by StanislawAntol** [tensorflow/tensorflow#11489]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Reproducible script below
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary/pip
- **TensorFlow version (use command below)**: 1.2.1
- **Python version**: 3.5
- **Bazel version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**:

```py
import tensorflow as tf
from tensorflow.python.framework import graph_util
from tensorflow.core.framework import graph_pb2

orig_model = "input_map_orig.pb"
mapped_model = "input_map_modified.pb"

# Create a graph with uint8 placeholder that gets
# cast to float32 before going through image whitening
tf.reset_default_graph()
img = tf.placeholder(tf.uint8, shape=(1, None, None, 3), name="input_tensor")
float_img = tf.cast(img, tf.float32, "ToFloat")
whiten_fn = lambda img: tf.image.per_image_standardization(img)
whitened = tf.map_fn(whiten_fn, float_img, name='image_whitening')
identity = tf.identity(whitened, name="id")

# Write graph
output_names = ["id"]
with tf.Session() as sess:
  input_graph_def = sess.graph_def
  output_graph_def = graph_util.convert_variables_to_constants(sess,
                                                               input_graph_def,
                                                               output_names)
  tf.train.write_graph(output_graph_def, "./", orig_model, False)

# Load the graph again
tf.reset_default_graph()
graph_def = graph_pb2.GraphDef()
with open(orig_model, "rb") as f:
  graph_def.ParseFromString(f.read())

# Rewire the graph with a float32 placeholder directly
img = tf.placeholder(tf.float32, shape=(1, None, None, 3), name="input")
input_map = {
  "ToFloat": img,
  }
tf.import_graph_def(graph_def, input_map=input_map, name="")

# Write the modified graph
graph = tf.get_default_graph()
output_names = ["id"]
with tf.Session(graph=graph) as sess:
  graph = tf.get_default_graph()
  input_graph_def = graph.as_graph_def()
  output_graph_def = graph_util.convert_variables_to_constants(sess,
                                                               input_graph_def,
                                                               output_names)
  tf.train.write_graph(output_graph_def, "./", mapped_model, False)

# Try to load the modified graph
tf.reset_default_graph()
graph_def = graph_pb2.GraphDef()
with open(mapped_model, "rb") as f:
  graph_def.ParseFromString(f.read())

g = tf.import_graph_def(graph_def)
```

### Describe the problem
I noticed this issue trying to modify (via input_map) an object detection model (from [tf/models/object_detection](https://github.com/tensorflow/models/tree/master/object_detection)) to directly accept float32 instead of uint8. I have managed to reproduce the using the above minimal example. It seems like one of the attributes of one of the operations doesn't get fully updated. Possibly related to  https://github.com/tensorflow/tensorflow/issues/9925 .

### Source code / logs
Traceback:
```
Traceback (most recent call last):
  File "input_map_bug.py", line 71, in <module>
    g = tf.import_graph_def(graph_def)
  File "/home/s.antol/cv/py3virtualenvs/tf1.2/lib/python3.5/site-packages/tensorflow/python/framework/importer.py", line 331, in import_graph_def
    op_to_bind_to, node.name))
ValueError: Specified colocation to an op that does not exist during import: ToFloat in image_whitening/TensorArrayUnstack/TensorArrayScatter/TensorArrayScatterV3
```

Looking through the protobuf text version, the node below has `s: "loc:@ToFloat"` instead of (what I think should be) `s:"loc:@input"`:
```
node {
  name: "image_whitening/TensorArrayUnstack/TensorArrayScatter/TensorArrayScatterV3"
  op: "TensorArrayScatterV3"
  input: "image_whitening/TensorArray"
  input: "image_whitening/TensorArrayUnstack/range"
  input: "input"
  input: "image_whitening/TensorArray:1"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "_class"
    value {
      list {
        s: "loc:@ToFloat"
      }
    }
  }
}
```

**Comment by jart** [comment]
@sherrym Our friend is trying to manipulate a graph and believes he's encountered a bug.

**Comment by mrry** [comment]
I believe that @vrv or I made a conscious decision not to update colocation constraint attrs in `tf.import_graph_def()`, so the fact that the `loc:@ToFloat` is left in there is "working as intended".

I just tried to replicate this, and it looks like the error is not raised if you don't perform the second `graph_util.convert_variables_to_constants()`. It looks like that function leaves the graph in an inconsistent state (i.e. with a dangling colocation constraint) because it is unaware of colocation constraints.

@petewarden Do you have any opinions on how colocation constraints should be handled in `graph_util.convert_variables_to_constants()`?

**Comment by StanislawAntol** [comment]
@mrry, thanks for the (quick!) update. Your suggestion of removing `graph_util.convert_variables_to_constants()` was helpful in avoiding my hacky float32 placeholder->tf.cast(uint8) prepending. It seems like this fixing this issue would remove extra work-around steps when one is trying to save a model that isn't already turned into constants (e.g., from a checkpoint), so good luck figuring out the best solution.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
A member of the TensorFlow organization has replied after the stat:awaiting tensorflower label was applied.

**Comment by petewarden** [comment]
Sorry for the lack of activity on this issue. It doesn't look like we're likely to have a chance to dig more deeply, so I'm tagging @suharshs so he's aware of another freeze_graph issue, and closing it as unlikely to be fixed. Please update with more information if this is still a problem for you.

**Comment by cweill** [comment]
I'm also encountering this issue, and have had to use a similar wrapping mechanism to work around it. Here are my steps to reproduce when using an embedding feature column:

```python
import tensorflow as tf
import difflib

orig_model = "input_map_orig.pb"
mapped_model = "input_map_modified.pb"

tf.reset_default_graph()

def define_graph(use_placeholder, wrap):
  feature = tf.feature_column.embedding_column(
      tf.feature_column.categorical_column_with_identity("feature", 10),
      dimension=10)
  feature_columns = [feature]
  if use_placeholder:
    features = tf.placeholder(dtype=tf.int32, name="input")
  else:
    features = tf.convert_to_tensor([3], name="input")
  if wrap:
    features = tf.identity(features, name="colocated")
  features = {"feature": features}
  input_layer = tf.feature_column.input_layer(features, feature_columns)
  int_data = tf.to_float(input_layer)
  process_fn = lambda data: tf.square(data)
  op = tf.map_fn(process_fn, int_data, name='process')
  identity = tf.identity(op, name="id")

# Set 'wrap' to False to reproduce bug.
define_graph(use_placeholder=True, wrap=True)

def freeze(graph, filename):
  output_names = ["id"]
  with tf.Session(graph=graph) as sess:
    sess.run(tf.global_variables_initializer())

    input_graph_def = sess.graph_def
    output_graph_def = tf.graph_util.convert_variables_to_constants(
        sess, input_graph_def, output_names)
    tf.train.write_graph(output_graph_def, "./", filename, False)

def load_frozen(filename, input_map={}):
  graph_def = tf.GraphDef()
  with open(filename, "rb") as f:
    graph_def.ParseFromString(f.read())
  tf.import_graph_def(graph_def, input_map=input_map, name="")

def make_change_in_graph():
  op = tf.convert_to_tensor([3], name="input") 

  input_map = {
    "input": op,
  }
  return input_map

# Save graph.
graph = tf.get_default_graph()
# print(graph.as_graph_def())
graph_proto0 = str(tf.get_default_graph().as_graph_def()).splitlines()
freeze(graph, orig_model)

# Load the graph again
tf.reset_default_graph()
input_map = make_change_in_graph()
load_frozen(orig_model, input_map)

graph_proto1 = str(graph.as_graph_def()).splitlines()
# print('\n'.join(difflib.ndiff(graph_proto0, graph_proto1)))


# Write the modified graph
graph = tf.get_default_graph()
freeze(graph, mapped_model)

# Load the graph again
tf.reset_default_graph()
input_map = make_change_in_graph()

load_frozen(mapped_model) # <------ Bug occurs on second load:

# Write the modified graph
graph = tf.get_default_graph()
freeze(graph, mapped_model)

# Load the graph again
tf.reset_default_graph()
load_frozen(mapped_model)
```

Is there any reason why the colocation op can't be overwritten?
