### ISSUE TITLE
[FeatureRequest] make categorical_x_entropy broadcastable

### ISSUE THREAD

**Issue by khaotik** [tensorflow/tensorflow#11534]
For example:

```
>>> x = tf.placeholder('float32', [4,5,6])
>>> y = tf.placeholder('float32', [1,5,6])
>>> z = tf.nn.softmax_cross_entropy_with_logits(labels=x, logits=y)
Traceback (most recent call last):
  File "/home/khaotik/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/common_shapes.py", line 671, in _call_cpp_shape_fn_impl
    input_tensors_as_shapes, status)
  File "/home/khaotik/anaconda3/lib/python3.6/contextlib.py", line 89, in __exit__
    next(self.gen)
  File "/home/khaotik/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimension 0 in both shapes must be equal, but are 5 and 20 for 'SoftmaxCrossEntropyWithLogits' (op: 'SoftmaxCrossEntropyWithLogits') with input shapes: [5,6], [20,6].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/khaotik/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 1594, in softmax_cross_entropy_with_logits
    precise_logits, labels, name=name)
  File "/home/khaotik/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 2380, in _softmax_cross_entropy_with_logits
    features=features, labels=labels, name=name)
  File "/home/khaotik/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/home/khaotik/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2508, in create_op
    set_shapes_for_outputs(ret)
  File "/home/khaotik/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1873, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/home/khaotik/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1823, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/home/khaotik/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/common_shapes.py", line 610, in call_cpp_shape_fn
    debug_python_shape_fn, require_shape_fn)
  File "/home/khaotik/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/common_shapes.py", line 676, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Dimension 0 in both shapes must be equal, but are 5 and 20 for 'SoftmaxCrossEntropyWithLogits' (op: 'SoftmaxCrossEntropyWithLogits') with input shapes: [5,6], [20,6].
```

But, intuitively, I'd like to broadcast `y` into shape `[4,5,6]` in the above code.

It's not too hard to get a workaround such as using `tf.tile`. However it would consume more precious GPU memory.

**Comment by aselle** [comment]
I'm trying to understand why your labels and logits wouldn't be the same shape. Usually they naturally are the same in most computations I've seen. Can you give a concrete example rather than just a placeholder where you've forced it.

**Comment by khaotik** [comment]
@aselle Yes, I encountered this during GAN training.

Basically, it looks like:

```
num_class = ...
num_sample = ...
batch_size = ...
labels = tf.placeholder('int32', [1, num_sample])
logits = tf.placeholder('float32', [batch_size, num_sample, num_class])
```

In my use case, the model is about multi-speaker audio separation, each data point comes with multiple single-speaker samples. So `num_samples` can't be merged with `batch_size`.

We wanted GAN discriminator to do multi-class classification besides true/false. So we use softmax rather than sigmoid.
Here `labels` is a constant `int` tensor across batches. The broadcast situation arises here.

It's really not a bottleneck in our model, but I'm probably just getting OCD about optimization. This situation may also arise in other separation / segmentation tasks, I think.

**Comment by aselle** [comment]
@fchollet , @martinwicke ,  thoughts on this feature request?

**Comment by martinwicke** [comment]
@ebrevdo isn't this the issue we made `softmax_cross_entropy_with_logits_v2` for?

**Comment by ebrevdo** [comment]
No, that was to allow backprop.  This is a request for broadcasting in the c++ kernel, which is a reasonable request.

**Comment by tensorflowbutler** [comment]
Nagging Awaiting TensorFlower: It has been 14 days with no activityand the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
A member of the TensorFlow organization has replied after the stat:awaiting tensorflower label was applied.

**Comment by yongtang** [comment]
Added a PR #16784 for the support.
