### ISSUE TITLE
Error when running imported/restored model that uses feedable iterator (tf.contrib.data)

### ISSUE THREAD

**Issue by eddiemundo** [tensorflow/tensorflow#11679]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **TensorFlow installed from (source or binary)**: Binary
- **TensorFlow version (use command below)**: Build #242 (Jul 17, 2017 2:25:00 AM)
- **Python version**: Python 3.6.2
- **Bazel version (if compiling from source)**: na
- **CUDA/cuDNN version**: 8.0/6.0
- **GPU model and memory**: 670 gtx 2gb
- **Exact command to reproduce**: na

### Describe the problem
I can't restore and run checkpoints of models that use feedable iterators, but I can restore and run checkpoints of models that directly use `make_one_shot_iterator()`. Below is code for the feedable iterator version, and below that code for the `make_one_shot_iterator()` version:

```python
import tensorflow as tf
from tensorflow.contrib.data import Dataset

BATCH_SIZE = 4
ITERATION_COUNT = 2
dataset = Dataset.from_tensor_slices(tf.constant([[0, 0],
                                                  [0, 1],
                                                  [1, 0],
                                                  [1, 1]], dtype=tf.float32))
batched_dataset = dataset.batch(BATCH_SIZE)
iterator_handle_placeholder = tf.placeholder(tf.string, shape=[])
tf.add_to_collection('placeholders', iterator_handle_placeholder)
iterator = tf.contrib.data.Iterator.from_string_handle(iterator_handle_placeholder, batched_dataset.output_types, batched_dataset.output_shapes)

# create some graph
inputs = iterator.get_next()
sum_placeholder = tf.placeholder_with_default(tf.reduce_sum(inputs), shape=[])
tf.add_to_collection('placeholders', sum_placeholder)
sum_variable = tf.get_variable('sum', initializer=tf.zeros(shape=[]))
assign_sum = tf.assign_add(sum_variable, sum_placeholder)
tf.add_to_collection('assigns', assign_sum)
saver = tf.train.Saver()

# run graph and save it at the end
with tf.Session() as session:
    session.run(tf.global_variables_initializer())
    batched_dataset_iterator = batched_dataset.make_one_shot_iterator()
    batched_dataset_iterator_handle = session.run(batched_dataset_iterator.string_handle())
    tf.add_to_collection('handles', batched_dataset_iterator_handle)
    inputs_feed_dict = {iterator_handle_placeholder: batched_dataset_iterator_handle}
    for i in range(ITERATION_COUNT):
        inputs_sum = session.run(assign_sum, feed_dict=inputs_feed_dict)
        inputs_feed_dict[sum_placeholder] = inputs_sum
        print(inputs_sum)
    saver.save(session, 'checkpoints/haha')

# restore saved graph and run it
with tf.Session() as session:
    saver = tf.train.import_meta_graph('checkpoints/haha.meta')
    saver.restore(session, 'checkpoints/haha')
    assign_sum = tf.get_collection('assigns')[0]
    iterator_handle_placeholder = tf.get_collection('placeholders')[0]
    batched_dataset_iterator_handle = tf.get_collection('handles')[0]
    sum_placeholder = tf.get_collection('placeholders')[1]
    inputs_feed_dict = {iterator_handle_placeholder: batched_dataset_iterator_handle}
    for i in range(ITERATION_COUNT):
        inputs_sum = session.run(assign_sum, feed_dict=inputs_feed_dict)
        print(inputs_sum)
        inputs_feed_dict[sum_placeholder] = inputs_sum
```
gives me
```
C:\Users\Jonathan\Miniconda3\envs\ai\python.exe "C:/Software Projects/ai/tensorflow/LayerTests.py"
2017-07-21 20:18:54.013753: W C:\tf_jenkins\home\workspace\nightly-win\M\windows-gpu\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-07-21 20:18:54.257354: I C:\tf_jenkins\home\workspace\nightly-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:955] Found device 0 with properties: 
name: GeForce GTX 670
major: 3 minor: 0 memoryClockRate (GHz) 0.98
pciBusID 0000:02:00.0
Total memory: 2.00GiB
Free memory: 1.64GiB
2017-07-21 20:18:54.257634: I C:\tf_jenkins\home\workspace\nightly-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:976] DMA: 0 
2017-07-21 20:18:54.257773: I C:\tf_jenkins\home\workspace\nightly-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:986] 0:   Y 
2017-07-21 20:18:54.257935: I C:\tf_jenkins\home\workspace\nightly-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:1045] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 670, pci bus id: 0000:02:00.0)
4.0
8.0
2017-07-21 20:18:54.705095: I C:\tf_jenkins\home\workspace\nightly-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:1045] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 670, pci bus id: 0000:02:00.0)
2017-07-21 20:18:54.774833: W C:\tf_jenkins\home\workspace\nightly-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1192] Not found: Container localhost does not exist.
Traceback (most recent call last):
  File "C:\Users\Jonathan\Miniconda3\envs\ai\lib\site-packages\tensorflow\python\client\session.py", line 1327, in _do_call
    return fn(*args)
  File "C:\Users\Jonathan\Miniconda3\envs\ai\lib\site-packages\tensorflow\python\client\session.py", line 1306, in _run_fn
    status, run_metadata)
  File "C:\Users\Jonathan\Miniconda3\envs\ai\lib\contextlib.py", line 88, in __exit__
    next(self.gen)
  File "C:\Users\Jonathan\Miniconda3\envs\ai\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.NotFoundError: Container localhost does not exist.
	 [[Node: IteratorFromStringHandle = IteratorFromStringHandle[_device="/job:localhost/replica:0/task:0/cpu:0"](_arg_Placeholder_0_0)]]
	 [[Node: PlaceholderWithDefault/_7 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_7_PlaceholderWithDefault", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Software Projects/ai/tensorflow/LayerTests.py", line 47, in <module>
    inputs_sum = session.run(assign_sum, feed_dict=inputs_feed_dict)
  File "C:\Users\Jonathan\Miniconda3\envs\ai\lib\site-packages\tensorflow\python\client\session.py", line 895, in run
    run_metadata_ptr)
  File "C:\Users\Jonathan\Miniconda3\envs\ai\lib\site-packages\tensorflow\python\client\session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\Jonathan\Miniconda3\envs\ai\lib\site-packages\tensorflow\python\client\session.py", line 1321, in _do_run
    options, run_metadata)
  File "C:\Users\Jonathan\Miniconda3\envs\ai\lib\site-packages\tensorflow\python\client\session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Container localhost does not exist.
	 [[Node: IteratorFromStringHandle = IteratorFromStringHandle[_device="/job:localhost/replica:0/task:0/cpu:0"](_arg_Placeholder_0_0)]]
	 [[Node: PlaceholderWithDefault/_7 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_7_PlaceholderWithDefault", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

Caused by op 'IteratorFromStringHandle', defined at:
  File "C:/Software Projects/ai/tensorflow/LayerTests.py", line 13, in <module>
    iterator = tf.contrib.data.Iterator.from_string_handle(iterator_handle_placeholder, batched_dataset.output_types, batched_dataset.output_shapes)
  File "C:\Users\Jonathan\Miniconda3\envs\ai\lib\site-packages\tensorflow\contrib\data\python\ops\dataset_ops.py", line 238, in from_string_handle
    string_handle)
  File "C:\Users\Jonathan\Miniconda3\envs\ai\lib\site-packages\tensorflow\python\ops\gen_dataset_ops.py", line 362, in iterator_from_string_handle
    string_handle=string_handle, name=name)
  File "C:\Users\Jonathan\Miniconda3\envs\ai\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "C:\Users\Jonathan\Miniconda3\envs\ai\lib\site-packages\tensorflow\python\framework\ops.py", line 2628, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "C:\Users\Jonathan\Miniconda3\envs\ai\lib\site-packages\tensorflow\python\framework\ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

NotFoundError (see above for traceback): Container localhost does not exist.
	 [[Node: IteratorFromStringHandle = IteratorFromStringHandle[_device="/job:localhost/replica:0/task:0/cpu:0"](_arg_Placeholder_0_0)]]
	 [[Node: PlaceholderWithDefault/_7 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_7_PlaceholderWithDefault", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]


Process finished with exit code 1
```
Here's the version that uses just a `make_one_shot_iterator()`:
```python
import tensorflow as tf
from tensorflow.contrib.data import Dataset

BATCH_SIZE = 4
ITERATION_COUNT = 2
dataset = Dataset.from_tensor_slices(tf.constant([[0, 0],
                                                  [0, 1],
                                                  [1, 0],
                                                  [1, 1]], dtype=tf.float32))
batched_dataset = dataset.batch(BATCH_SIZE)

# create some graph
batched_dataset_iterator = batched_dataset.make_one_shot_iterator()
inputs = batched_dataset_iterator.get_next()
sum_placeholder = tf.placeholder_with_default(tf.reduce_sum(inputs), shape=[])
tf.add_to_collection('placeholders', sum_placeholder)
sum_variable = tf.get_variable('sum', initializer=tf.zeros(shape=[]))
assign_sum = tf.assign_add(sum_variable, sum_placeholder)
tf.add_to_collection('assigns', assign_sum)
saver = tf.train.Saver()

# run graph and save it at the end
with tf.Session() as session:
    session.run(tf.global_variables_initializer())
    inputs_feed_dict = {}
    for i in range(ITERATION_COUNT):
        inputs_sum = session.run(assign_sum, feed_dict=inputs_feed_dict)
        inputs_feed_dict[sum_placeholder] = inputs_sum
        print(inputs_sum)
    saver.save(session, 'checkpoints/haha')

# restore saved graph and run it
with tf.Session() as session:
    saver = tf.train.import_meta_graph('checkpoints/haha.meta')
    saver.restore(session, 'checkpoints/haha')
    assign_sum = tf.get_collection('assigns')[0]
    sum_placeholder = tf.get_collection('placeholders')[1]
    inputs_feed_dict = {}
    for i in range(ITERATION_COUNT):
        inputs_sum = session.run(assign_sum, feed_dict=inputs_feed_dict)
        print(inputs_sum)
        inputs_feed_dict[sum_placeholder] = inputs_sum
```
Result:
```
C:\Users\Jonathan\Miniconda3\envs\ai\python.exe "C:/Software Projects/ai/tensorflow/LayerTests.py"
2017-07-21 20:12:26.273776: W C:\tf_jenkins\home\workspace\nightly-win\M\windows-gpu\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-07-21 20:12:26.516570: I C:\tf_jenkins\home\workspace\nightly-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:955] Found device 0 with properties: 
name: GeForce GTX 670
major: 3 minor: 0 memoryClockRate (GHz) 0.98
pciBusID 0000:02:00.0
Total memory: 2.00GiB
Free memory: 1.64GiB
2017-07-21 20:12:26.516852: I C:\tf_jenkins\home\workspace\nightly-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:976] DMA: 0 
2017-07-21 20:12:26.516992: I C:\tf_jenkins\home\workspace\nightly-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:986] 0:   Y 
2017-07-21 20:12:26.517145: I C:\tf_jenkins\home\workspace\nightly-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:1045] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 670, pci bus id: 0000:02:00.0)
4.0
8.0
2017-07-21 20:12:26.926502: I C:\tf_jenkins\home\workspace\nightly-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:1045] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 670, pci bus id: 0000:02:00.0)
12.0
24.0

Process finished with exit code 0
```

**Comment by eddiemundo** [comment]
I simplified the example some more and tried storing the iterator to feed using `tf.add_to_collections()` and using that to get the string handle instead of storing the string handle directly. I get a different error this time regarding initialization, but it exits fine.
```python
import tensorflow as tf
from tensorflow.contrib.data import Dataset, Iterator

BATCH_SIZE = 2
ITERATION_COUNT = 1
dataset = Dataset.from_tensor_slices(tf.constant([[0, 0],
                                                  [0, 1],
                                                  [1, 0],
                                                  [1, 1]], dtype=tf.float32))
iterator_handle_placeholder = tf.placeholder(tf.string, shape=[])
iterator = Iterator.from_string_handle(iterator_handle_placeholder, dataset.output_types, dataset.output_shapes)
dataset_iterator = dataset.make_one_shot_iterator()

element = iterator.get_next()
v = tf.get_variable('v', initializer=tf.zeros([]))

saver = tf.train.Saver()

with tf.Session() as session:
    session.run(tf.global_variables_initializer())
    dataset_iterator_handle = session.run(dataset_iterator.string_handle())
    tf.add_to_collection('iterator_handle_placeholder', iterator_handle_placeholder)
    tf.add_to_collection('iterator', dataset_iterator)
    tf.add_to_collection('element', element)
    output = session.run(element, {iterator_handle_placeholder: dataset_iterator_handle})
    print(output)
    saver.save(session, 'checkpoints/fufu')

with tf.Session() as session:
    saver = tf.train.import_meta_graph('checkpoints/fufu.meta')
    saver.restore(session, 'checkpoints/fufu')
    iterator_handle_placeholder = tf.get_collection('iterator_handle_placeholder')[0]
    dataset_iterator_handle = session.run(tf.get_collection('iterator')[0].string_handle())
    element = tf.get_collection('element')[0]
    output = session.run(element, {iterator_handle_placeholder: dataset_iterator_handle})
    print(output)
```
Error message is 
```
C:\Users\Jonathan\Miniconda3\envs\ai\python.exe "C:/Software Projects/ai/tensorflow/datasettest.py"
2017-07-21 22:15:13.371342: W C:\tf_jenkins\home\workspace\nightly-win\M\windows-gpu\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-07-21 22:15:13.612687: I C:\tf_jenkins\home\workspace\nightly-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:955] Found device 0 with properties: 
name: GeForce GTX 670
major: 3 minor: 0 memoryClockRate (GHz) 0.98
pciBusID 0000:02:00.0
Total memory: 2.00GiB
Free memory: 1.64GiB
2017-07-21 22:15:13.612996: I C:\tf_jenkins\home\workspace\nightly-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:976] DMA: 0 
2017-07-21 22:15:13.613141: I C:\tf_jenkins\home\workspace\nightly-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:986] 0:   Y 
2017-07-21 22:15:13.613302: I C:\tf_jenkins\home\workspace\nightly-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:1045] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 670, pci bus id: 0000:02:00.0)
[ 0.  0.]
WARNING:tensorflow:Error encountered when serializing iterator.
Type is unsupported, or the types of the items don't match field type in CollectionDef.
'Iterator' object has no attribute 'name'
2017-07-21 22:15:13.999859: I C:\tf_jenkins\home\workspace\nightly-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:1045] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 670, pci bus id: 0000:02:00.0)
[ 0.  0.]

Process finished with exit code 0
```

**Comment by zwify** [comment]
Hello eddiemundo,

 I'm facing exactly the same issue, did you manage to solve it, any advices about how to process ?
Thank you a lot

**Comment by youngwoo-yoon** [comment]
I successfully saved and restored the model only with the iterator handle placeholder. But you should initialize a new iterator. 
One strange thing is that the placeholder for the handle should have a name parameter. Without naming, the type and content is not correctly loaded when I call get_collection.

**Comment by annarailton** [comment]
I was also struggling with this. I tried various things along the lines of what eddiemundo did, writing iterators to collections. I also tried  [`tf.contrib.data.make_saveable_from_iterator()`](https://www.tensorflow.org/api_docs/python/tf/contrib/data/make_saveable_from_iterator) (I managed to successfully save an iterator here but not get it back!). No success with this approach.

I eventually realised what youngwoo-yoon meant by "new iterator" -  you can just make an entirely new iterator in your restored model and use that instead. You still need to grab the handle from the saved model though and call `iterator.string_handle()` on the new iterator. Works with both one shot and initialisable iterators.

Here's a simple example with `make_one_shot_iterator()`:

```python
import tensorflow as tf
import numpy as np

def save(dataset):
    """
    Create graph with an Dataset and Iterator and save the model.

    There is some op that is applied to the data from the iterator.
    """
    iterator_handle = tf.placeholder(tf.string, shape=[])
    tf.add_to_collection('iterator_handle', iterator_handle)

    iterator = tf.data.Iterator.from_string_handle(
        iterator_handle,
        dataset.output_types,
        dataset.output_shapes)
    dataset_iterator = dataset.make_one_shot_iterator()
    element = iterator.get_next()

    some_op = tf.multiply(element, 0.5)
    tf.add_to_collection('some_op', some_op)
    v = tf.get_variable('v', initializer=tf.zeros([]))  # Needs a variable to save the model

    saver = tf.train.Saver()

    with tf.Session() as session:
        session.run(tf.global_variables_initializer())
        handle_val = session.run(dataset_iterator.string_handle())
        for _ in range(4):
            print(session.run(some_op,
                feed_dict={iterator_handle: handle_val}))
        saver.save(session, 'checkpoints/fufu')

def restore(dataset):
    """Restore the model from file and pass some new data through it"""
    with tf.Session() as session:
        saver = tf.train.import_meta_graph('checkpoints/fufu.meta')
        saver.restore(session, 'checkpoints/fufu')
        iterator_handle = tf.get_collection('iterator_handle')[0]
        # Make new iterator
        iterator = dataset.make_one_shot_iterator()
        new_handle = session.run(iterator.string_handle())
        element = iterator.get_next()
        some_op = tf.get_collection('some_op')[0]
        for _ in range(4):
            print(session.run(some_op, {iterator_handle: new_handle}))

if __name__ == '__main__':

    raw_data = np.array([[0, 0],
                     [0, 1],
                     [1, 0],
                     [1, 1]])
    dataset1 = tf.data.Dataset.from_tensor_slices(tf.constant(raw_data, dtype=tf.float32))
    dataset2 = tf.data.Dataset.from_tensor_slices(tf.constant(raw_data * 2, dtype=tf.float32))

    save(dataset1)

    # Restore works with any data of the same shape in a tf.data.Dataset
    # To use different shaped data use initialisable iterator
    restore(dataset1)
    restore(dataset2)
```

**Comment by annarailton** [comment]
Here's another example with initialisable iterators.

```python
# Tensorflow 1.8.0
import tensorflow as tf
import numpy as np

def train(train_dataset, test_dataset):
    """
    Create graph with an Dataset and Iterator and save the model.

    There is some op that is applied to the data from the iterator.
    """
    iterator_handle = tf.placeholder(tf.string, shape=[])
    tf.add_to_collection('iterator_handle', iterator_handle)

    iterator = tf.data.Iterator.from_string_handle(
        iterator_handle,
        train_dataset.output_types,
        train_dataset.output_shapes)
    train_iter = train_dataset.make_initializable_iterator()
    test_iter = test_dataset.make_initializable_iterator()
    element = iterator.get_next()

    some_op = tf.multiply(element, 0.5)
    tf.add_to_collection('some_op', some_op)
    v = tf.get_variable('v', initializer=tf.zeros([]))

    saver = tf.train.Saver()

    with tf.Session() as sess:
        sess.run(tf.global_variables_initializer())

        train_handle = sess.run(train_iter.string_handle())
        test_handle = sess.run(test_iter.string_handle())

        # Run data iterator initialisation
        sess.run(train_iter.initializer)
        sess.run(test_iter.initializer)

        # "Training"
        print("Training")
        while True:
            try:
                print(sess.run(some_op,
                    feed_dict={iterator_handle: train_handle}))
            except tf.errors.OutOfRangeError:
                break

        # "Test evaluation"
        print("Testing")
        while True:
            try:
                print(sess.run(some_op,
                    feed_dict={iterator_handle: test_handle}))
            except tf.errors.OutOfRangeError:
                break

        saver.save(sess, 'checkpoints/fufu')

def eval(dataset):
    """Restore the model from file and pass some new data through it"""
    with tf.Session() as sess:
        saver = tf.train.import_meta_graph('checkpoints/fufu.meta')
        saver.restore(sess, 'checkpoints/fufu')
        iterator_handle = tf.get_collection('iterator_handle')[0]
        # Make new iterator
        iterator = dataset.make_one_shot_iterator()
        new_handle = sess.run(iterator.string_handle())
        # Don't need to call iterator.get_next() again as `some_op` will use
        # restored `element` 
        some_op = tf.get_collection('some_op')[0]

        # "Further evaluation"
        print("More testing")
        while True:
            try:
                print(sess.run(some_op,
                    feed_dict={iterator_handle: new_handle}))
            except tf.errors.OutOfRangeError:
                break

if __name__ == '__main__':

    train_dataset = tf.data.Dataset.from_tensor_slices(
        tf.constant(np.random.randint(0, 100, (5, 2)), dtype=tf.float32))
    test_dataset = tf.data.Dataset.from_tensor_slices(
        tf.constant(np.random.randint(0, 100, (2, 2)), dtype=tf.float32))

    train(train_dataset, test_dataset)

    # Now want to evaluate the results of another test dataset
    another_test_dataset = tf.data.Dataset.from_tensor_slices(
        tf.constant(np.random.randint(0, 100, (4, 2)), dtype=tf.float32))
    eval(another_test_dataset)
```

**Comment by masonk** [comment]
Your way of saving an iterator handle and then feeding it back in is the only way that I can get to work. Thanks!

Is this the most efficient way to do this? It seems like having to do an op lookup from a handle for every train step is less efficient than just grafting in your new iterator one time during graph setup. 

What made the most sense to me would have been to save a reinitializable iterator itself into the metagraph, and then to restore that iterator and call `sess.run(reinitializable_iterator.make_initializer(my_new_dataset))`. That only needs to happen once per iterator initialization instead of every train set.  But, I was unable to save an reinitializable iterator to the metagraph and then properly restore it. After a few hours of trying, I gave up and switched to feedable.

I think that attaching a new Dataset iterator to a restored model is the most common use case for metagraphs, so I think that these examples you're giving here should be in the docs. If it is indeed the *best* way to do this.

**Comment by annarailton** [comment]
Glad someone found the examples helpful. I was going a bit nuts not being able to find an example of what I thought would be a fairly common use case. 

I have no idea RE efficiency of this. I agree that using a `reinitializable_iterator` seems much more elegant, but like you I haven't managed to get it working with a restored model. The op lookup from a handle is _probably_ OK (feels like using `get_variable()` elsewhere in the graph to get some weights), but this is mere conjecture. 

The great irony of all this is I've not noticed any difference between using `tf.data.Dataset` + iterators and just passing in data via a `feed_dict` like most of the tutorials do. I'm assuming there's an amount of data where using iterators becomes better but I've not hit it yet.

**Comment by masonk** [comment]
Since we both encountered the same difficulty and solved it in the same way, I think it's a good enough hint that the docs should be updated. Filed a new bug.

**Comment by alisaaalehi** [comment]
Thank you, @annarailton for sharing that complete example.
 In addition to training and then loading the saved model in the development phase, I want to load and continue training the saved model. 
Everything works fine, but there is a small problem here. Whenever I restore the previous model and resume training, operations related to creating new datasets and iterators are added to the existing graph. This makes the graph bigger and bigger every time that I load it for further training. To be able to see this problem you need to visualize the computation graph in **Tensorboard**.
The following is a modified version of your code to make the problem clear.  Any thoughts or suggestions?
```python
# Tensorflow 1.8.0
import tensorflow as tf
import numpy as np
import os
import shutil


def train(train_dataset, test_dataset):
    """
    Create graph with an Dataset and Iterator and save the model.

    There is some op that is applied to the data from the iterator.
    """
    iterator_handle = tf.placeholder(tf.string, shape=[])
    tf.add_to_collection('iterator_handle', iterator_handle)

    iterator = tf.data.Iterator.from_string_handle(
        iterator_handle,
        train_dataset.output_types,
        train_dataset.output_shapes)
    train_iter = train_dataset.make_initializable_iterator()
    test_iter = test_dataset.make_initializable_iterator()
    element = iterator.get_next()

    v = tf.get_variable(name='v', initializer=tf.zeros(shape=(1, 2)))
    
    # to use when saving summaries
    global_step = tf.Variable(0, name='global_step', trainable=False, dtype=tf.int32)
    increament_global_step = tf.assign(global_step, global_step + 1)
    global_step = global_step + 1
    tf.add_to_collection('increament_global_step', increament_global_step)
    
    some_op = tf.assign(v,  v + tf.abs(element))
    tf.add_to_collection('some_op', tf.reduce_sum(some_op))

    tf.summary.scalar('v_sum', tf.reduce_sum(v))
    tf.summary.scalar('some_op', tf.reduce_mean(some_op))
    merged_summary = tf.summary.merge_all()
    tf.add_to_collection('merged_summary', merged_summary)
    
    writer = tf.summary.FileWriter('checkpoints', graph=tf.get_default_graph())
    saver = tf.train.Saver()

    with tf.Session() as sess:
        sess.run(tf.global_variables_initializer())

        train_handle = sess.run(train_iter.string_handle())
        test_handle = sess.run(test_iter.string_handle())

        # Run data iterator initialisation
        sess.run(train_iter.initializer)
        sess.run(test_iter.initializer)

        # "Training"
        print("Training")
        while True:
            try:
                [op, summary_values, g_step] = sess.run([some_op, merged_summary, increament_global_step],
                                                feed_dict={iterator_handle: train_handle})
                writer.add_summary(summary_values, global_step=g_step)
                print(op)
            except tf.errors.OutOfRangeError:
                break

        # "Test evaluation"
        print("Testing")
        while True:
            try:
                print(sess.run(some_op,
                    feed_dict={iterator_handle: test_handle}))
            except tf.errors.OutOfRangeError:
                break

        saver.save(sess, 'checkpoints/fufu')


def eval(dataset):
    """Restore the model from file and pass some new data through it"""
    with tf.Session() as sess:
        saver = tf.train.import_meta_graph('checkpoints/fufu.meta')
        saver.restore(sess, 'checkpoints/fufu')
        iterator_handle = tf.get_collection('iterator_handle')[0]
        # Make new iterator
        iterator = dataset.make_one_shot_iterator()
        new_handle = sess.run(iterator.string_handle())
        # Don't need to call iterator.get_next() again as `some_op` will use
        # restored `element`
        some_op = tf.get_collection('some_op')[0]

        # "Further evaluation"
        print("More testing")
        while True:
            try:
                print(sess.run(some_op,
                    feed_dict={iterator_handle: new_handle}))
            except tf.errors.OutOfRangeError:
                break


def resume_training(train_dataset, test_dataset):
    """Restore the model from file and pass some new data through it
     for further training """
    with tf.Session() as sess:
        saver = tf.train.import_meta_graph('checkpoints/fufu.meta')
        saver.restore(sess, 'checkpoints/fufu')
        iterator_handle = tf.get_collection('iterator_handle')[0]
        some_op = tf.get_collection('some_op')[0]
        increament_global_step = tf.get_collection('increament_global_step')[0]
        merged_summary = tf.get_collection('merged_summary')[0]

        writer = tf.summary.FileWriter('checkpoints',
                                       graph=tf.get_default_graph())

        # Make new iterators and handles
        train_iter = train_dataset.make_initializable_iterator()
        test_iter = test_dataset.make_initializable_iterator()

        train_handle = sess.run(train_iter.string_handle())
        test_handle = sess.run(test_iter.string_handle())

        # Further training the model using new datasets (which may be different from original ones)
        print("Resume training ...")

        train_handle = sess.run(train_iter.string_handle())
        test_handle = sess.run(test_iter.string_handle())

        # Run data iterator initialisation
        sess.run(train_iter.initializer)
        sess.run(test_iter.initializer)

        # "Training"
        print("Training")
        while True:
            try:
                [op, summary_values, g_step] = sess.run([some_op, merged_summary, increament_global_step],
                                                feed_dict={
                                                    iterator_handle: train_handle})
                writer.add_summary(summary_values, global_step=g_step)
                print(op)
            except tf.errors.OutOfRangeError:
                break

        # "Test evaluation"
        print("Testing")
        while True:
            try:
                print(sess.run(some_op,
                               feed_dict={iterator_handle: test_handle}))
            except tf.errors.OutOfRangeError:
                break

        saver.save(sess, 'checkpoints/fufu')


if __name__ == '__main__':

    flag = 3  # 1 for train, 2 for test, 3 to resume training
    if flag == 1:
        # delete existing saved models and summary files
        if os.path.exists('checkpoints'):
            shutil.rmtree('checkpoints')
        train_dataset = tf.data.Dataset.from_tensor_slices(
            tf.constant(np.random.randint(0, 100, (5, 2)), dtype=tf.float32))
        test_dataset = tf.data.Dataset.from_tensor_slices(
            tf.constant(np.random.randint(0, 100, (2, 2)), dtype=tf.float32))

        train(train_dataset, test_dataset)
    elif flag == 2:
        # Now want to evaluate the results of another test dataset
        another_test_dataset = tf.data.Dataset.from_tensor_slices(
            tf.constant(np.random.randint(0, 100, (4, 2)), dtype=tf.float32))
        eval(another_test_dataset)

    elif flag == 3:
        # Load and fine-tune the saved model using new data
        another_train_dataset = tf.data.Dataset.from_tensor_slices(
            tf.constant(np.random.randint(0, 100, (10, 2)), dtype=tf.float32))
        another_test_dataset = tf.data.Dataset.from_tensor_slices(
            tf.constant(np.random.randint(0, 100, (8, 2)), dtype=tf.float32))

        resume_training(another_train_dataset, another_test_dataset)
