### ISSUE TITLE
gather_nd InvalidArgumentError

### ISSUE THREAD

**Issue by MilesZhao** [tensorflow/tensorflow#11718]
2017-07-24 10:35:25.247357: W tensorflow/core/framework/op_kernel.cc:1152] Invalid argument: flat indices[12287, :] = [127, 42] does not index into param (shape: [32,512,100,1]).
	 [[Node: conv-maxpool-3/GatherNd = GatherNd[Tindices=DT_INT32, Tparams=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](ExpandDims, conv-maxpool-3/stack)]]
2017-07-24 10:35:25.247422: W tensorflow/core/framework/op_kernel.cc:1152] Invalid argument: flat indices[12287, :] = [127, 42] does not index into param (shape: [32,512,100,1]).
	 [[Node: conv-maxpool-3/GatherNd = GatherNd[Tindices=DT_INT32, Tparams=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](ExpandDims, conv-maxpool-3/stack)]]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1039, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1021, in _run_fn
    status, run_metadata)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 89, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: flat indices[12287, :] = [127, 42] does not index into param (shape: [32,512,100,1]).
	 [[Node: conv-maxpool-3/GatherNd = GatherNd[Tindices=DT_INT32, Tparams=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](ExpandDims, conv-maxpool-3/stack)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mix.py", line 66, in <module>
    autoen_nn.clf_train_epoch(x_train,y_train,batch_size,dropout_rate = 0.5)
  File "/Users/MilesZhao/Desktop/ORNL/data/epath_data/yong/cnn.py", line 248, in clf_train_epoch
    feed_dict = feed_dict)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 778, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 982, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1032, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1052, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: flat indices[12287, :] = [127, 42] does not index into param (shape: [32,512,100,1]).
	 [[Node: conv-maxpool-3/GatherNd = GatherNd[Tindices=DT_INT32, Tparams=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](ExpandDims, conv-maxpool-3/stack)]]

Caused by op 'conv-maxpool-3/GatherNd', defined at:
  File "mix.py", line 64, in <module>
    num_classes)
  File "/Users/MilesZhao/Desktop/ORNL/data/epath_data/yong/cnn.py", line 125, in __init__
    filter_size)
  File "/Users/MilesZhao/Desktop/ORNL/data/epath_data/yong/cnn.py", line 217, in conv_layer
    local_in_doc_mat = tf.gather_nd(in_doc_mat,temp)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 1321, in gather_nd
    name=name)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2336, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1228, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): flat indices[12287, :] = [127, 42] does not index into param (shape: [32,512,100,1]).
	 [[Node: conv-maxpool-3/GatherNd = GatherNd[Tindices=DT_INT32, Tparams=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](ExpandDims, conv-maxpool-3/stack)]]

**Comment by asimshankar** [comment]
I apologize but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new) . Please provide all the information it asks, in particular detailed instructions to reproduce the problem. Thank you.
