### ISSUE TITLE
Unexpected behavior in tf.contrib.distributions.Categorical

### ISSUE THREAD

**Issue by mbchang** [tensorflow/tensorflow#11758]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac OS X 10.12.3
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.2.0
- **Python version**: 2.7.10
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**: CPU
- **GPU model and memory**: CPU
- **Exact command to reproduce**:
```
>>> import tensorflow as tf
>>> sess = tf.Session()
>>> t = tf.contrib.distributions.Categorical(probs=[0.0,0.0,0.0])
>>> print(sess.run(t.sample([1])))
>>> [3]  # outside the support of the distribution!
```

### Describe the problem
I wonder if this is a bug or if this is a design choice to have `tf.contrib.distributions.Categorical` output a number outside the support of the distribution if all of the probabilities are 0. In any case, it would be helpful to throw an error when all probabilities are 0, rather than output a number that doesn't work.

### Source code / logs
See above.

**Comment by aselle** [comment]
@ebrevdo, could you take a look?

**Comment by ebrevdo** [comment]
I think there's a construction attribute that enables runtime checks. What happens if you turn it on?

**Comment by mbchang** [comment]
When I turn it on, I get the error:
```
>>> import tensorflow as tf
>>> sess = tf.Session()
>>> t = tf.contrib.distributions.Categorical(probs=[0.0,0.0,0.0], validate_args=True)
>>> print(sess.run(t.sample([1])))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "[...]/python2.7/site-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "[...]/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "[...]/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "[...]/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: assertion failed: [probs does not sum to 1.] [Condition x ~= y did not hold element-wise: x = ] [Categorical_2/Categorical/validate_probs/Sum:0] [0] [y = ] [Categorical_2/Categorical/validate_probs/Const:0] [1]
	 [[Node: Categorical_2/Categorical/validate_probs/assert_close/Assert/AssertGuard/Assert = Assert[T=[DT_STRING, DT_STRING, DT_STRING, DT_FLOAT, DT_STRING, DT_STRING, DT_FLOAT], summarize=3, _device="/job:localhost/replica:0/task:0/cpu:0"](Categorical_2/Categorical/validate_probs/assert_close/Assert/AssertGuard/Assert/Switch, Categorical_2/Categorical/validate_probs/assert_close/Assert/AssertGuard/Assert/data_0, Categorical_2/Categorical/validate_probs/assert_close/Assert/AssertGuard/Assert/data_1, Categorical_2/Categorical/validate_probs/assert_close/Assert/AssertGuard/Assert/data_2, Categorical_2/Categorical/validate_probs/assert_close/Assert/AssertGuard/Assert/Switch_1, Categorical_2/Categorical/validate_probs/assert_close/Assert/AssertGuard/Assert/data_4, Categorical_2/Categorical/validate_probs/assert_close/Assert/AssertGuard/Assert/data_5, Categorical_2/Categorical/validate_probs/assert_close/Assert/AssertGuard/Assert/Switch_2)]]
```
It get the error only when I call `sess.run(t.sample([1])`, but not when I construct the distribution `t = tf.contrib.distributions.Categorical(probs=[0.0,0.0,0.0], validate_args=True)`. What is the design choice for this? Also, I am curious about the design choice behind `validate_args`, because it is unintuitive to mean that an invalid distribution would be useful at all, and so validating the arguments would be necessary in any case.

**Comment by ebrevdo** [comment]
validate_args is very expensive, especially when on a GPU.  So it's
disabled by default.  Turn it on when developing models.

**Comment by ebrevdo** [comment]
Input to the constructor if usually an unknown Tensor which is why we don't
try to check until runtime. We could add static checks here though,
probably.

**Comment by mbchang** [comment]
I see. Checks would be helpful, otherwise the code might silently ignore invalid distributions if the flag is not set. Thanks for the clarifications!

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by jvdillon** [comment]
Im marking this closed since `validate_args=True` should have been used by the user to catch this case. As Eugene indicated, in general checks are expensive and therefore we do not want them to be on by default.
