### ISSUE TITLE
should tf.contrib.data.FixedLengthRecordDataset work with GS?

### ISSUE THREAD

**Issue by mari-linhares** [tensorflow/tensorflow#11766]
Trying to open a GS file (gs://path/), with tf.contrib.data.FixedLengthRecordDataset, I get: tensorflow/core/framework/op_kernel.cc:1158] Out of range: EOF reached, 0 bytes were read out of 262144 bytes requested.

**Comment by aselle** [comment]
@jhseu, are you the right person to answer this question?

**Comment by tfboyd** [comment]
it looks like Dataset might have an issue accessing resources on GCS (google cloud storage).

**Comment by tfboyd** [comment]
@mari-linhares  I know this is bit of work but I would test with head from master and make sure it is still broken.  There also likely needs to be a unit test assuming something is broken so we catch this in the future.

**Comment by rca06d** [comment]
Just got this same error kind of randomly in the middle of a training session. Here's the full trace if that helps:
```
Traceback (most recent call last): File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main "__main__", fname, loader, pkg_name) File "/usr/lib/python2.7/runpy.py", line 72, in _run_code exec code in run_globals File "/root/.local/lib/python2.7/site-packages/train/task.py", line 136, in <module> sess.run(optimize) File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 789, in run run_metadata_ptr) File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 997, in _run feed_dict_string, options, run_metadata) File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1132, in _do_run target_list, options, run_metadata) File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1152, in _do_call raise type(e)(node_def, op, message) OutOfRangeError: EOF reached, 0 bytes were read out of 262144 bytes requested. [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[-1,1024,1], [-1,1024]], output_types=[DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](Iterator)]] [[Node: sigmoid_cross_entropy_loss/assert_broadcastable/is_valid_shape/has_valid_nonscalar_shape/has_invalid_dims/num_invalid_dims/_43 = _HostRecv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_577_sigmoid_cross_entropy_loss/assert_broadcastable/is_valid_shape/has_valid_nonscalar_shape/has_invalid_dims/num_invalid_dims", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"]()]] Caused by op u'IteratorGetNext', defined at: File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main "__main__", fname, loader, pkg_name) File "/usr/lib/python2.7/runpy.py", line 72, in _run_code exec code in run_globals File "/root/.local/lib/python2.7/site-packages/train/task.py", line 93, in <module> x_train, y_train = iter_data_train.get_next() File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/data/python/ops/dataset_ops.py", line 247, in get_next name=name)) File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_dataset_ops.py", line 254, in iterator_get_next output_shapes=output_shapes, name=name) File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op op_def=op_def) File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2506, in create_op original_op=self._default_original_op, op_def=op_def) File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1269, in __init__ self._traceback = _extract_stack() OutOfRangeError (see above for traceback): EOF reached, 0 bytes were read out of 262144 bytes requested. [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[-1,1024,1], [-1,1024]], output_types=[DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](Iterator)]] [[Node: sigmoid_cross_entropy_loss/assert_broadcastable/is_valid_shape/has_valid_nonscalar_shape/has_invalid_dims/num_invalid_dims/_43 = _HostRecv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_577_sigmoid_cross_entropy_loss/assert_broadcastable/is_valid_shape/has_valid_nonscalar_shape/has_invalid_dims/num_invalid_dims", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
```
Not able to reproduce it though. Could have just been a network hiccup?

**Comment by jhseu** [comment]
We think this bug is related to other GCS issues we fixed recently. It should work better in TF 1.5.
