### ISSUE TITLE
patch is not installed on some of Windows slaves

### ISSUE THREAD

**Issue by meteorcloudy** [tensorflow/tensorflow#11900]
http://ci.tensorflow.org/job/tf-master-win-bzl/1335/console
On win0-slave:
```
16:57:47 Analyzing: target //tensorflow/tools/pip_package:build_pip_package
16:58:28 ERROR: C:/tf_jenkins/home/workspace/tf-master-win-bzl/tensorflow/tools/pip_package/BUILD:70:1: error loading package 'tensorflow/contrib/session_bundle': Encountered error while reading extension file 'protobuf.bzl': no such package '@protobuf_archive//': Traceback (most recent call last):
16:58:28 	File "C:/tf_jenkins/home/workspace/tf-master-win-bzl/tensorflow/workspace.bzl", line 119
16:58:28 		_apply_patch(repo_ctx, repo_ctx.attr.patch_file)
16:58:28 	File "C:/tf_jenkins/home/workspace/tf-master-win-bzl/tensorflow/workspace.bzl", line 110, in _apply_patch
16:58:28 		_execute_and_check_ret_code(repo_ctx, cmd)
16:58:28 	File "C:/tf_jenkins/home/workspace/tf-master-win-bzl/tensorflow/workspace.bzl", line 94, in _execute_and_check_ret_code
16:58:28 		fail("Non-zero return code({1}) when ..., <2 more arguments>))
16:58:28 Non-zero return code(127) when executing 'C:/tools/msys64/usr/bin/bash -c patch -p1 -d C:/tmp/_bazel_system/424zmya1/external/protobuf_archive -i C:/tf_jenkins/home/workspace/tf-master-win-bzl/third_party/protobuf/add_noinlines.patch':
16:58:28 Stdout: 
16:58:28 Stderr: /usr/bin/bash: patch: command not found
16:58:28  and referenced by '//tensorflow/tools/pip_package:si
```

**Comment by meteorcloudy** [comment]
@gunan @yifeif

**Comment by yifeif** [comment]
Hi Yun, they should be installed now. I rebuild a few machines(0, 1 and 3) last week. Let me know if you see anything else missing. Thanks!

**Comment by meteorcloudy** [comment]
Hi Yifei, I still see the same error on win3-slave:
https://ci.tensorflow.org/job/tf-master-win-bzl/1344/console

**Comment by yifeif** [comment]
sorry, should be fixed for 3 for reals! Passed the patch part: http://ci.tensorflow.org/job/tf-master-win-bzl/1347/console

**Comment by meteorcloudy** [comment]
Great, thanks for fixing this! But the Bazel version seems to fall back to 0.4.5, because we didn't update the Windows slave setup script. I've sent a CL to do that. ;)
