### ISSUE TITLE
Unclear about how to integrate AttentionWrapper with BeamSearchDecoder

### ISSUE THREAD

**Issue by zhedongzheng** [tensorflow/tensorflow#11904]
TF Version: 1.2.1

I cannot find information about how to integrate AttentionWrapper with BeamSearchDecoder on website / nmt tutorial, in particular how to feed the beam-search-tiled (```tf.contrib.seq2seq.tile_batch```) states to the attention-cloned (```zero_state(...).clone(...)```) states.

In my attempt, there seems to be an inconsistency between the requirement of the ```batch_size``` of the zero states generated by ```AttentionWrapper```  in the training stage and predicting stage. In training stage, initial state of decoder requires batch size, however in predicting stage it requires (batch_size * beam_width).
the minimal code to demonstrate this problem is:
``` python
import tensorflow as tf
from tensorflow.python.layers.core import Dense

BEAM_WIDTH = 5
BATCH_SIZE = 128

# INPUTS
X = tf.placeholder(tf.int32, [BATCH_SIZE, None])
Y = tf.placeholder(tf.int32, [BATCH_SIZE, None])
X_seq_len = tf.placeholder(tf.int32, [BATCH_SIZE])
Y_seq_len = tf.placeholder(tf.int32, [BATCH_SIZE])

# ENCODER         
encoder_out, encoder_state = tf.nn.dynamic_rnn(
    cell = tf.nn.rnn_cell.BasicLSTMCell(128), 
    inputs = tf.contrib.layers.embed_sequence(X, 10000, 128),
    sequence_length = X_seq_len,
    dtype = tf.float32)

# ATTENTION
attention_mechanism = tf.contrib.seq2seq.LuongAttention(
    num_units = 128, 
    memory = encoder_out,
    memory_sequence_length = X_seq_len)

decoder_cell = tf.contrib.seq2seq.AttentionWrapper(
    cell = tf.nn.rnn_cell.BasicLSTMCell(128),
    attention_mechanism = attention_mechanism,
    attention_layer_size = 128)

# DECODER COMPONENTS
Y_vocab_size = 10000
decoder_embedding = tf.Variable(tf.random_uniform([Y_vocab_size, 128], -1.0, 1.0))
projection_layer = Dense(Y_vocab_size)

# TRAINING DECODER
training_helper = tf.contrib.seq2seq.TrainingHelper(
    inputs = tf.nn.embedding_lookup(decoder_embedding, Y),
    sequence_length = Y_seq_len,
    time_major = False)
training_decoder = tf.contrib.seq2seq.BasicDecoder(
    cell = decoder_cell,
    helper = training_helper,
    initial_state = decoder_cell.zero_state(BATCH_SIZE,tf.float32).clone(cell_state=encoder_state),
    output_layer = projection_layer)
training_decoder_output, _, _ = tf.contrib.seq2seq.dynamic_decode(
    decoder = training_decoder,
    impute_finished = True,
    maximum_iterations = tf.reduce_max(Y_seq_len))
training_logits = training_decoder_output.rnn_output

# PREDICTING_DECODER
predicting_decoder = tf.contrib.seq2seq.BeamSearchDecoder(
    cell = decoder_cell,
    embedding = decoder_embedding,
    start_tokens = tf.tile(tf.constant([1], dtype=tf.int32), [BATCH_SIZE]),
    end_token = 2,
    initial_state = decoder_cell.zero_state(BATCH_SIZE * BEAM_WIDTH,tf.float32).clone(
                    cell_state=tf.contrib.seq2seq.tile_batch(encoder_state, BEAM_WIDTH)),
    beam_width = BEAM_WIDTH,
    output_layer = projection_layer,
    length_penalty_weight = 0.0)
predicting_decoder_output, _, _ = tf.contrib.seq2seq.dynamic_decode(
    decoder = predicting_decoder,
    impute_finished = False,
    maximum_iterations = 2 * tf.reduce_max(Y_seq_len))
predicting_logits = predicting_decoder_output.predicted_ids[:, :, 0]
```
the error message is:
```
Traceback (most recent call last):
  File "test.py", line 58, in <module>
    initial_state = decoder_cell.zero_state(BATCH_SIZE*BEAM_WIDTH,tf.float32).clone(
  File "/Users/l2015005/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/seq2seq/python/ops/attention_wrapper.py", line 659, in zero_state
    message=error_message)]):
  File "/Users/l2015005/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/check_ops.py", line 317, in assert_equal
    _assert_static(condition_static, data)
  File "/Users/l2015005/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/check_ops.py", line 100, in _assert_static
    raise ValueError('\n'.join(data_static))
ValueError: When calling zero_state of AttentionWrapper attention_wrapper: Non-matching batch sizes between the memory (encoder output) and the requested batch size.  Are you using the BeamSearchDecoder?  If so, make sure your encoder output has been tiled to beam_width via tf.contrib.seq2seq.tile_batch, and the batch_size= argument passed to zero_state is batch_size * beam_width.
Condition x == y did not hold element-wise:
x (AttentionWrapperZeroState_1/assert_equal/x:0) = 
640
y (AttentionWrapperZeroState_1/assert_equal/y:0) = 
128
```

**Comment by zhedongzheng** [comment]
@ebrevdo any insight about this?

**Comment by zhedongzheng** [comment]
@JerrikEph @Songweiping @pplantinga
any insight about this?

**Comment by pplantinga** [comment]
The error message seems to suggest a fix: tile the encoder output

**Comment by zhedongzheng** [comment]
hi @pplantinga 
It is already tiled here:
```python
    initial_state = decoder_cell.zero_state(BATCH_SIZE * BEAM_WIDTH,tf.float32).clone(
                    cell_state=tf.contrib.seq2seq.tile_batch(encoder_state, BEAM_WIDTH)),
```
I use clone method because of attention wrapper

**Comment by pplantinga** [comment]
I see:

Encoder out -> attention -> decoder cell -> beam search(cell=decoder cell)

Without ever getting tiled. I'm not sure of the correct place to tile, however.

**Comment by zhedongzheng** [comment]
I finally get the graph successfully compiled by the following, will further test the running environment and then close the issue if solved
``` python
import tensorflow as tf
from tensorflow.python.layers.core import Dense


BEAM_WIDTH = 5
BATCH_SIZE = 128


# INPUTS
X = tf.placeholder(tf.int32, [BATCH_SIZE, None])
Y = tf.placeholder(tf.int32, [BATCH_SIZE, None])
X_seq_len = tf.placeholder(tf.int32, [BATCH_SIZE])
Y_seq_len = tf.placeholder(tf.int32, [BATCH_SIZE])


# ENCODER         
encoder_out, encoder_state = tf.nn.dynamic_rnn(
    cell = tf.nn.rnn_cell.BasicLSTMCell(128), 
    inputs = tf.contrib.layers.embed_sequence(X, 10000, 128),
    sequence_length = X_seq_len,
    dtype = tf.float32)


# DECODER COMPONENTS
Y_vocab_size = 10000
decoder_embedding = tf.Variable(tf.random_uniform([Y_vocab_size, 128], -1.0, 1.0))
projection_layer = Dense(Y_vocab_size)


# ATTENTION (TRAINING)
attention_mechanism = tf.contrib.seq2seq.LuongAttention(
    num_units = 128, 
    memory = encoder_out,
    memory_sequence_length = X_seq_len)

decoder_cell = tf.contrib.seq2seq.AttentionWrapper(
    cell = tf.nn.rnn_cell.BasicLSTMCell(128),
    attention_mechanism = attention_mechanism,
    attention_layer_size = 128)


# DECODER (TRAINING)
training_helper = tf.contrib.seq2seq.TrainingHelper(
    inputs = tf.nn.embedding_lookup(decoder_embedding, Y),
    sequence_length = Y_seq_len,
    time_major = False)
training_decoder = tf.contrib.seq2seq.BasicDecoder(
    cell = decoder_cell,
    helper = training_helper,
    initial_state = decoder_cell.zero_state(BATCH_SIZE,tf.float32).clone(cell_state=encoder_state),
    output_layer = projection_layer)
training_decoder_output, _, _ = tf.contrib.seq2seq.dynamic_decode(
    decoder = training_decoder,
    impute_finished = True,
    maximum_iterations = tf.reduce_max(Y_seq_len))
training_logits = training_decoder_output.rnn_output


# BEAM SEARCH TILE
encoder_out = tf.contrib.seq2seq.tile_batch(encoder_out, multiplier=BEAM_WIDTH)
X_seq_len = tf.contrib.seq2seq.tile_batch(X_seq_len, multiplier=BEAM_WIDTH)
encoder_state = tf.contrib.seq2seq.tile_batch(encoder_state, multiplier=BEAM_WIDTH)


# ATTENTION (PREDICTING)
attention_mechanism = tf.contrib.seq2seq.LuongAttention(
    num_units = 128, 
    memory = encoder_out,
    memory_sequence_length = X_seq_len)

decoder_cell = tf.contrib.seq2seq.AttentionWrapper(
    cell = tf.nn.rnn_cell.BasicLSTMCell(128),
    attention_mechanism = attention_mechanism,
    attention_layer_size = 128)


# DECODER (PREDICTING)
predicting_decoder = tf.contrib.seq2seq.BeamSearchDecoder(
    cell = decoder_cell,
    embedding = decoder_embedding,
    start_tokens = tf.tile(tf.constant([1], dtype=tf.int32), [BATCH_SIZE]),
    end_token = 2,
    initial_state = decoder_cell.zero_state(BATCH_SIZE * BEAM_WIDTH,tf.float32).clone(cell_state=encoder_state),
    beam_width = BEAM_WIDTH,
    output_layer = projection_layer,
    length_penalty_weight = 0.0)
predicting_decoder_output, _, _ = tf.contrib.seq2seq.dynamic_decode(
    decoder = predicting_decoder,
    impute_finished = False,
    maximum_iterations = 2 * tf.reduce_max(Y_seq_len))
predicting_logits = predicting_decoder_output.predicted_ids[:, :, 0]

print('successful')
```

**Comment by zhedongzheng** [comment]
running is passed, this is closed, thanks.

**Comment by applenob** [comment]
One question about the code: you use two attention mechanism during training and predicting phase. Do they share the same parameters?

**Comment by zhedongzheng** [comment]
@applenob no they don't, here i just do a minimal example to demonstrate the workflow. You are right, we need to control variable scopes in practice.

**Comment by applenob** [comment]
Thanks for your reply. Do you have any code sharing? Since the two attention as two inputs with different shape, I don't think these two variables can be shared.

**Comment by zhedongzheng** [comment]
Hi, @applenob If you want to have a look at more complex and complete code, you can have a look on my repo (https://github.com/zhedongzheng/finch).

**Comment by applenob** [comment]
Cool project !

**Comment by applenob** [comment]
@zhedongzheng, Your complete code can actually work and make sense to me now. Thanks.

**Comment by lmolhw5252** [comment]
您好，我也遇到了同样的问题，为什么需要这个tile呢？

**Comment by lmolhw5252** [comment]
@zhedongzheng

**Comment by zhedongzheng** [comment]
@lmolhw5252  假设beam_width = 5，那么每次decode都需要保持5个最佳state，所以一开始就直接把初始化state复制5份，这就是tile的作用。

**Comment by vikmary** [comment]
This is the minimal fix of code by @zhedongzheng that makes parameters of attention mechanism shared for train and predict decoders:

```python
import tensorflow as tf
from tensorflow.python.layers.core import Dense


BEAM_WIDTH = 5
BATCH_SIZE = 128


# INPUTS
X = tf.placeholder(tf.int32, [BATCH_SIZE, None])
Y = tf.placeholder(tf.int32, [BATCH_SIZE, None])
X_seq_len = tf.placeholder(tf.int32, [BATCH_SIZE])
Y_seq_len = tf.placeholder(tf.int32, [BATCH_SIZE])


# ENCODER         
encoder_out, encoder_state = tf.nn.dynamic_rnn(
    cell = tf.nn.rnn_cell.BasicLSTMCell(128), 
    inputs = tf.contrib.layers.embed_sequence(X, 10000, 128),
    sequence_length = X_seq_len,
    dtype = tf.float32)


# DECODER COMPONENTS
Y_vocab_size = 10000
decoder_embedding = tf.Variable(tf.random_uniform([Y_vocab_size, 128], -1.0, 1.0))
projection_layer = Dense(Y_vocab_size)


# ATTENTION (TRAINING)
with tf.variable_scope('shared_attention_mechanism'):
    attention_mechanism = tf.contrib.seq2seq.LuongAttention(
        num_units = 128, 
        memory = encoder_out,
        memory_sequence_length = X_seq_len)

decoder_cell = tf.contrib.seq2seq.AttentionWrapper(
    cell = tf.nn.rnn_cell.BasicLSTMCell(128),
    attention_mechanism = attention_mechanism,
    attention_layer_size = 128)


# DECODER (TRAINING)
training_helper = tf.contrib.seq2seq.TrainingHelper(
    inputs = tf.nn.embedding_lookup(decoder_embedding, Y),
    sequence_length = Y_seq_len,
    time_major = False)
training_decoder = tf.contrib.seq2seq.BasicDecoder(
    cell = decoder_cell,
    helper = training_helper,
    initial_state = decoder_cell.zero_state(BATCH_SIZE,tf.float32).clone(cell_state=encoder_state),
    output_layer = projection_layer)
with tf.variable_scope('decode_with_shared_attention'):
    training_decoder_output, _, _ = tf.contrib.seq2seq.dynamic_decode(
        decoder = training_decoder,
        impute_finished = True,
        maximum_iterations = tf.reduce_max(Y_seq_len))
training_logits = training_decoder_output.rnn_output


# BEAM SEARCH TILE
encoder_out = tf.contrib.seq2seq.tile_batch(encoder_out, multiplier=BEAM_WIDTH)
X_seq_len = tf.contrib.seq2seq.tile_batch(X_seq_len, multiplier=BEAM_WIDTH)
encoder_state = tf.contrib.seq2seq.tile_batch(encoder_state, multiplier=BEAM_WIDTH)


# ATTENTION (PREDICTING)
with tf.variable_scope('shared_attention_mechanism', reuse=True):
    attention_mechanism = tf.contrib.seq2seq.LuongAttention(
        num_units = 128, 
        memory = encoder_out,
        memory_sequence_length = X_seq_len)

decoder_cell = tf.contrib.seq2seq.AttentionWrapper(
    cell = tf.nn.rnn_cell.BasicLSTMCell(128),
    attention_mechanism = attention_mechanism,
    attention_layer_size = 128)


# DECODER (PREDICTING)
predicting_decoder = tf.contrib.seq2seq.BeamSearchDecoder(
    cell = decoder_cell,
    embedding = decoder_embedding,
    start_tokens = tf.tile(tf.constant([1], dtype=tf.int32), [BATCH_SIZE]),
    end_token = 2,
    initial_state = decoder_cell.zero_state(BATCH_SIZE * BEAM_WIDTH,tf.float32).clone(cell_state=encoder_state),
    beam_width = BEAM_WIDTH,
    output_layer = projection_layer,
    length_penalty_weight = 0.0)
with tf.variable_scope('decode_with_shared_attention', reuse=True):
    predicting_decoder_output, _, _ = tf.contrib.seq2seq.dynamic_decode(
        decoder = predicting_decoder,
        impute_finished = False,
        maximum_iterations = 2 * tf.reduce_max(Y_seq_len))
predicting_logits = predicting_decoder_output.predicted_ids[:, :, 0]

print('successful')
```

To check sharing of trainable parameters execute the following code:
```python
for var in tf.trainable_variables():
    print(var)
```

For the code above it will output:
```bash
<tf.Variable 'EmbedSequence/embeddings:0' shape=(10000, 128) dtype=float32_ref>
<tf.Variable 'rnn/basic_lstm_cell/kernel:0' shape=(256, 512) dtype=float32_ref>
<tf.Variable 'rnn/basic_lstm_cell/bias:0' shape=(512,) dtype=float32_ref>
<tf.Variable 'Variable:0' shape=(10000, 128) dtype=float32_ref>
<tf.Variable 'shared_attention_mechanism/memory_layer/kernel:0' shape=(128, 128) dtype=float32_ref>
<tf.Variable 'decode_with_shared_attention/decoder/attention_wrapper/basic_lstm_cell/kernel:0' shape=(384, 512) dtype=float32_ref>
<tf.Variable 'decode_with_shared_attention/decoder/attention_wrapper/basic_lstm_cell/bias:0' shape=(512,) dtype=float32_ref>
<tf.Variable 'decode_with_shared_attention/decoder/attention_wrapper/attention_layer/kernel:0' shape=(256, 128) dtype=float32_ref>
<tf.Variable 'decode_with_shared_attention/decoder/dense/kernel:0' shape=(128, 10000) dtype=float32_ref>
<tf.Variable 'decode_with_shared_attention/decoder/dense/bias:0' shape=(10000,) dtype=float32_ref>
```
 But without wrapping of `tf.contrib.seq2seq.LuongAttention` and `tf.contrib.seq2seq.BeamSearchDecoder` into variable scopes it outputs:
```bash
<tf.Variable 'EmbedSequence/embeddings:0' shape=(10000, 128) dtype=float32_ref>
<tf.Variable 'rnn/basic_lstm_cell/kernel:0' shape=(256, 512) dtype=float32_ref>
<tf.Variable 'rnn/basic_lstm_cell/bias:0' shape=(512,) dtype=float32_ref>
<tf.Variable 'Variable:0' shape=(10000, 128) dtype=float32_ref>
<tf.Variable 'memory_layer/kernel:0' shape=(128, 128) dtype=float32_ref>
<tf.Variable 'decoder/attention_wrapper/basic_lstm_cell/kernel:0' shape=(384, 512) dtype=float32_ref>
<tf.Variable 'decoder/attention_wrapper/basic_lstm_cell/bias:0' shape=(512,) dtype=float32_ref>
<tf.Variable 'decoder/attention_wrapper/attention_layer/kernel:0' shape=(256, 128) dtype=float32_ref>
<tf.Variable 'decoder/dense/kernel:0' shape=(128, 10000) dtype=float32_ref>
<tf.Variable 'decoder/dense/bias:0' shape=(10000,) dtype=float32_ref>
<tf.Variable 'memory_layer_1/kernel:0' shape=(128, 128) dtype=float32_ref>
<tf.Variable 'decoder_1/attention_wrapper/basic_lstm_cell/kernel:0' shape=(384, 512) dtype=float32_ref>
<tf.Variable 'decoder_1/attention_wrapper/basic_lstm_cell/bias:0' shape=(512,) dtype=float32_ref>
<tf.Variable 'decoder_1/attention_wrapper/attention_layer/kernel:0' shape=(256, 128) dtype=float32_ref>
```
 where there are extra memory_layer_1/ and decoder_1/attention_wrapper/ being trained.
