### ISSUE TITLE
No OpKernel was registered to support Op 'Dequantize' with these attrs

### ISSUE THREAD

**Issue by Zumbalamambo** [tensorflow/tensorflow#11930]
Im getting the following error while running quantized graph

```
   raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'Dequantize' with these attrs.  Registered devices: [CPU], Registered kernels:
  <no registered kernels>

	 [[Node: final_training_ops/weights/final_weights/read/_1__cf__1 = Dequantize[T=DT_QUINT8, mode="MIN_FIRST"](final_training_ops/weights/final_weights/read/_1__cf__1_quantized_const, final_training_ops/weights/final_weights/read/_1__cf__1_quantized_min, final_training_ops/weights/final_weights/read/_1__cf__1_quantized_max)]]

```

**Comment by poxvoculi** [comment]
Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?  Make sure you also include the exact command if possible to produce  the output included in your test case. If you are unclear what to include  see the issue template displayed in  [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

 We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!

**Comment by Zumbalamambo** [comment]
Im using Macbook Pro to build the quantized model. The version of tensorflow is 1.2 in my mac.
Im trying to deploy the quantized model in windows. The version of tensorflow is 1.2 in my windows. 

I compiled it using bazel.


This is how is generated it,

```
  bazel-bin/tensorflow/tools/graph_transforms/transform_graph \
--in_graph=tmp/stripped.pb \
--out_graph=tmp/quantized_gender.pb \
--inputs='Mul' \
--outputs='final_result' \
--transforms='
  strip_unused_nodes(type=float, shape="1,299,299,3")
  fold_constants(ignore_errors=true)
  fold_batch_norms
  fold_old_batch_norms
  quantize_weights'
```

**Comment by poxvoculi** [comment]
As of version 0.12, Dequantize was not supported on Windows.   Here's the
[release notes ](https://github.com/tensorflow/tensorflow/releases).

I don't see any indication that support has been added yet.  @mrry?

**Comment by Zumbalamambo** [comment]
yeah.. is there any workaround for windows?

**Comment by mrry** [comment]
AFAIK, we still don't have support for gemmlowp on Windows, although it'd be nice to have!

/cc @guschmue, since I gather he's looked into this....

**Comment by guschmue** [comment]
I got the quantized ops to work on windows. A branch with the changes is here: 
https://github.com/guschmue/tensorflow/tree/win-quant
I made as little changes as possible to gemmlowp (basically for windows replace pthread with stl threads) to increase chances that I get a pull request taken.
Unit tests for quantized ops on windows are passing.

I still need to make it build with bazel/windows and should be able to send a pr in the next few days.

**Comment by guschmue** [comment]
sent the pr for for gemmlowp. If taken, the tensorflow change is fairly simple.

**Comment by mrry** [comment]
Thanks Guenther!

**Comment by anonym24** [comment]
@guschmue I tried you respitory, but the same error:

```
InvalidArgumentError (see above for traceback): No OpKernel was registered to support Op 'Dequantize' with these attrs.  Registered devices: [CPU,GPU], Registered kernels:
  <no registered kernels>

```

full logs:

```
$ python "D:\admin\Train\_TensorFlow train\tensorflow\tensorflow\examples\image_r              etraining\retrain.py" \
>   --image_dir "D:\admin\Train\_TensorFlow train\images" \
>   --learning_rate=0.0005 \
>   --testing_percentage=15 \
>   --validation_percentage=15 \
>   --train_batch_size=32 \
>   --validation_batch_size=-1 \
>   --flip_left_right True \
>   --random_scale=30 \
>   --random_brightness=30 \
>   --eval_step_interval=100 \
>   --how_many_training_steps=1000 \
>   --architecture mobilenet_1.0_128_quantized
>> Downloading mobilenet_v1_1.0_128_frozen.tgz 100.0%--- Logging error ---
Traceback (most recent call last):
  File "D:\ProgramFiles\Conda\lib\logging\__init__.py", line 992, in emit
    msg = self.format(record)
  File "D:\ProgramFiles\Conda\lib\logging\__init__.py", line 838, in format
    return fmt.format(record)
  File "D:\ProgramFiles\Conda\lib\logging\__init__.py", line 575, in format
    record.message = record.getMessage()
  File "D:\ProgramFiles\Conda\lib\logging\__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "D:\admin\Train\_TensorFlow train\tensorflow\tensorflow\examples\image_retrainin        g\retrain.py", line 1326, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "D:\ProgramFiles\Conda\lib\site-packages\tensorflow\python\platform\app.py", li        ne 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "D:\admin\Train\_TensorFlow train\tensorflow\tensorflow\examples\image_retrainin        g\retrain.py", line 982, in main
    maybe_download_and_extract(model_info['data_url'])
  File "D:\admin\Train\_TensorFlow train\tensorflow\tensorflow\examples\image_retrainin        g\retrain.py", line 339, in maybe_download_and_extract
    'bytes.')
  File "D:\ProgramFiles\Conda\lib\site-packages\tensorflow\python\platform\tf_logging.        py", line 82, in info
    _logger.info(msg, *args, **kwargs)
Message: 'Successfully downloaded'
Arguments: ('mobilenet_v1_1.0_128_frozen.tgz', 19169380, 'bytes.')
INFO:tensorflow:Looking for images in 'car'
INFO:tensorflow:Looking for images in 'road'

Traceback (most recent call last):
  File "D:\ProgramFiles\Conda\lib\site-packages\tensorflow\python\client\session.py",         line 1327, in _do_call
    return fn(*args)
  File "D:\ProgramFiles\Conda\lib\site-packages\tensorflow\python\client\session.py",         line 1297, in _run_fn
    self._extend_graph()
  File "D:\ProgramFiles\Conda\lib\site-packages\tensorflow\python\client\session.py",         line 1358, in _extend_graph
    self._session, graph_def.SerializeToString(), status)
  File "D:\ProgramFiles\Conda\lib\contextlib.py", line 89, in __exit__
    next(self.gen)
  File "D:\ProgramFiles\Conda\lib\site-packages\tensorflow\python\framework\errors_imp        l.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was register        ed to support Op 'Dequantize' with these attrs.  Registered devices: [CPU,GPU], Regist        ered kernels:
  <no registered kernels>

         [[Node: MobilenetV1/Logits/Conv2d_1c_1x1/weights/read/_1__cf__1 = Dequantize[        T=DT_QUINT8, mode="MIN_FIRST"](MobilenetV1/Logits/Conv2d_1c_1x1/weights/read/_1__cf__1        _quantized_const, MobilenetV1/Logits/Conv2d_1c_1x1/weights/read/_1__cf__1_quantized_mi        n, MobilenetV1/Logits/Conv2d_1c_1x1/weights/read/_1__cf__1_quantized_max)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\admin\Train\_TensorFlow train\tensorflow\tensorflow\examples\image_retrainin        g\retrain.py", line 1326, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "D:\ProgramFiles\Conda\lib\site-packages\tensorflow\python\platform\app.py", li        ne 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "D:\admin\Train\_TensorFlow train\tensorflow\tensorflow\examples\image_retrainin        g\retrain.py", line 1047, in main
    sess.run(init)
  File "D:\ProgramFiles\Conda\lib\site-packages\tensorflow\python\client\session.py",         line 895, in run
    run_metadata_ptr)
  File "D:\ProgramFiles\Conda\lib\site-packages\tensorflow\python\client\session.py",         line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "D:\ProgramFiles\Conda\lib\site-packages\tensorflow\python\client\session.py",         line 1321, in _do_run
    options, run_metadata)
  File "D:\ProgramFiles\Conda\lib\site-packages\tensorflow\python\client\session.py",         line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was register        ed to support Op 'Dequantize' with these attrs.  Registered devices: [CPU,GPU], Regist        ered kernels:
  <no registered kernels>

         [[Node: MobilenetV1/Logits/Conv2d_1c_1x1/weights/read/_1__cf__1 = Dequantize[        T=DT_QUINT8, mode="MIN_FIRST"](MobilenetV1/Logits/Conv2d_1c_1x1/weights/read/_1__cf__1        _quantized_const, MobilenetV1/Logits/Conv2d_1c_1x1/weights/read/_1__cf__1_quantized_mi        n, MobilenetV1/Logits/Conv2d_1c_1x1/weights/read/_1__cf__1_quantized_max)]]

Caused by op 'MobilenetV1/Logits/Conv2d_1c_1x1/weights/read/_1__cf__1', defined at:
  File "D:\admin\Train\_TensorFlow train\tensorflow\tensorflow\examples\image_retrainin        g\retrain.py", line 1326, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "D:\ProgramFiles\Conda\lib\site-packages\tensorflow\python\platform\app.py", li        ne 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "D:\admin\Train\_TensorFlow train\tensorflow\tensorflow\examples\image_retrainin        g\retrain.py", line 984, in main
    create_model_graph(model_info))
  File "D:\admin\Train\_TensorFlow train\tensorflow\tensorflow\examples\image_retrainin        g\retrain.py", line 282, in create_model_graph
    model_info['resized_input_tensor_name'],
  File "D:\ProgramFiles\Conda\lib\site-packages\tensorflow\python\framework\importer.p        y", line 313, in import_graph_def
    op_def=op_def)
  File "D:\ProgramFiles\Conda\lib\site-packages\tensorflow\python\framework\ops.py", l        ine 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "D:\ProgramFiles\Conda\lib\site-packages\tensorflow\python\framework\ops.py", l        ine 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): No OpKernel was registered to support         Op 'Dequantize' with these attrs.  Registered devices: [CPU,GPU], Registered kernels:
  <no registered kernels>

         [[Node: MobilenetV1/Logits/Conv2d_1c_1x1/weights/read/_1__cf__1 = Dequantize[        T=DT_QUINT8, mode="MIN_FIRST"](MobilenetV1/Logits/Conv2d_1c_1x1/weights/read/_1__cf__1        _quantized_const, MobilenetV1/Logits/Conv2d_1c_1x1/weights/read/_1__cf__1_quantized_mi        n, MobilenetV1/Logits/Conv2d_1c_1x1/weights/read/_1__cf__1_quantized_max)]]

2017-09-20 11:00:36.555015: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36        \tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compi        led to use AVX instructions, but these are available on your machine and could speed u        p CPU computations.
2017-09-20 11:00:36.555034: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36        \tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compi        led to use AVX2 instructions, but these are available on your machine and could speed         up CPU computations.
2017-09-20 11:00:37.459748: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36        \tensorflow\core\common_runtime\gpu\gpu_device.cc:955] Found device 0 with properties:        
name: GeForce 940MX
major: 5 minor: 0 memoryClockRate (GHz) 1.2415
pciBusID 0000:01:00.0
Total memory: 2.00GiB
Free memory: 1.66GiB
2017-09-20 11:00:37.459766: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36        \tensorflow\core\common_runtime\gpu\gpu_device.cc:976] DMA: 0
2017-09-20 11:00:37.459770: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36        \tensorflow\core\common_runtime\gpu\gpu_device.cc:986] 0:   Y
2017-09-20 11:00:37.459795: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36        \tensorflow\core\common_runtime\gpu\gpu_device.cc:1045] Creating TensorFlow device (/g        pu:0) -> (device: 0, name: GeForce 940MX, pci bus id: 0000:01:00.0)

admin@IL713 MINGW64 /d/admin/Train/_TensorFlow train
$ python "D:\admin\Train\_TensorFlow train\tensorflow\tensorflow\examples\image_retraining\retrain.py"   --image_dir "D:\admin\Train\_TensorFlow train\images"   --learning_rate=0.0005   --testing_percentage=15   --validation_percentage=15   --train_batch_size=32   --validation_batch_size=-1   --flip_left_right True   --random_scale=30   --random_brightness=30   --eval_step_interval=100   --how_many_training_steps=1000   --architecture mobilenet_1.0_128_quantized
INFO:tensorflow:Looking for images in 'car'
INFO:tensorflow:Looking for images in 'road'
Traceback (most recent call last):
  File "D:\ProgramFiles\Conda\lib\site-packages\tensorflow\python\client\session.py", line 1327, in _do_call
    return fn(*args)
  File "D:\ProgramFiles\Conda\lib\site-packages\tensorflow\python\client\session.py", line 1297, in _run_fn
    self._extend_graph()
  File "D:\ProgramFiles\Conda\lib\site-packages\tensorflow\python\client\session.py", line 1358, in _extend_graph
    self._session, graph_def.SerializeToString(), status)
  File "D:\ProgramFiles\Conda\lib\contextlib.py", line 89, in __exit__
    next(self.gen)
  File "D:\ProgramFiles\Conda\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'Dequantize' with these attrs.  Registered devices: [CPU,GPU], Registered kernels:
  <no registered kernels>

         [[Node: MobilenetV1/Logits/Conv2d_1c_1x1/weights/read/_1__cf__1 = Dequantize[T=DT_QUINT8, mode="MIN_FIRST"](MobilenetV1/Logits/Conv2d_1c_1x1/weights/read/_1__cf__1_quantized_const, MobilenetV1/Logits/Conv2d_1c_1x1/weights/read/_1__cf__1_quantized_min, MobilenetV1/Logits/Conv2d_1c_1x1/weights/read/_1__cf__1_quantized_max)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\admin\Train\_TensorFlow train\tensorflow\tensorflow\examples\image_retraining\retrain.py", line 1326, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "D:\ProgramFiles\Conda\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "D:\admin\Train\_TensorFlow train\tensorflow\tensorflow\examples\image_retraining\retrain.py", line 1047, in main
    sess.run(init)
  File "D:\ProgramFiles\Conda\lib\site-packages\tensorflow\python\client\session.py", line 895, in run
    run_metadata_ptr)
  File "D:\ProgramFiles\Conda\lib\site-packages\tensorflow\python\client\session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "D:\ProgramFiles\Conda\lib\site-packages\tensorflow\python\client\session.py", line 1321, in _do_run
    options, run_metadata)
  File "D:\ProgramFiles\Conda\lib\site-packages\tensorflow\python\client\session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'Dequantize' with these attrs.  Registered devices: [CPU,GPU], Registered kernels:
  <no registered kernels>

         [[Node: MobilenetV1/Logits/Conv2d_1c_1x1/weights/read/_1__cf__1 = Dequantize[T=DT_QUINT8, mode="MIN_FIRST"](MobilenetV1/Logits/Conv2d_1c_1x1/weights/read/_1__cf__1_quantized_const, MobilenetV1/Logits/Conv2d_1c_1x1/weights/read/_1__cf__1_quantized_min, MobilenetV1/Logits/Conv2d_1c_1x1/weights/read/_1__cf__1_quantized_max)]]

Caused by op 'MobilenetV1/Logits/Conv2d_1c_1x1/weights/read/_1__cf__1', defined at:
  File "D:\admin\Train\_TensorFlow train\tensorflow\tensorflow\examples\image_retraining\retrain.py", line 1326, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "D:\ProgramFiles\Conda\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "D:\admin\Train\_TensorFlow train\tensorflow\tensorflow\examples\image_retraining\retrain.py", line 984, in main
    create_model_graph(model_info))
  File "D:\admin\Train\_TensorFlow train\tensorflow\tensorflow\examples\image_retraining\retrain.py", line 282, in create_model_graph
    model_info['resized_input_tensor_name'],
  File "D:\ProgramFiles\Conda\lib\site-packages\tensorflow\python\framework\importer.py", line 313, in import_graph_def
    op_def=op_def)
  File "D:\ProgramFiles\Conda\lib\site-packages\tensorflow\python\framework\ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "D:\ProgramFiles\Conda\lib\site-packages\tensorflow\python\framework\ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): No OpKernel was registered to support Op 'Dequantize' with these attrs.  Registered devices: [CPU,GPU], Registered kernels:
  <no registered kernels>

         [[Node: MobilenetV1/Logits/Conv2d_1c_1x1/weights/read/_1__cf__1 = Dequantize[T=DT_QUINT8, mode="MIN_FIRST"](MobilenetV1/Logits/Conv2d_1c_1x1/weights/read/_1__cf__1_quantized_const, MobilenetV1/Logits/Conv2d_1c_1x1/weights/read/_1__cf__1_quantized_min, MobilenetV1/Logits/Conv2d_1c_1x1/weights/read/_1__cf__1_quantized_max)]]

2017-09-20 11:10:02.698409: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-09-20 11:10:02.698428: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-20 11:10:03.448744: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:955] Found device 0 with properties:
name: GeForce 940MX
major: 5 minor: 0 memoryClockRate (GHz) 1.2415
pciBusID 0000:01:00.0
Total memory: 2.00GiB
Free memory: 1.66GiB
2017-09-20 11:10:03.448762: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:976] DMA: 0
2017-09-20 11:10:03.448767: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:986] 0:   Y
2017-09-20 11:10:03.448791: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:1045] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce 940MX, pci bus id: 0000:01:00.0)

admin@IL713 MINGW64 /d/admin/Train/_TensorFlow train
$ python "D:\admin\Train\_TensorFlow train\tensorflow\tensorflow\examples\image_retraining\retrain.py"   --image_dir "D:\admin\Train\_TensorFlow train\images"   --learning_rate=0.0005   --testing_percentage=15   --validation_percentage=15   --train_batch_size=32   --validation_batch_size=-1   --flip_left_right True   --random_scale=30   --random_brightness=30   --eval_step_interval=100   --how_many_training_steps=1000   --architecture mobilenet_1.0_128_quantized
INFO:tensorflow:Looking for images in 'car'
INFO:tensorflow:Looking for images in 'road'
Traceback (most recent call last):
  File "D:\ProgramFiles\Conda\lib\site-packages\tensorflow\python\client\session.py", line 1327, in _do_call
    return fn(*args)
  File "D:\ProgramFiles\Conda\lib\site-packages\tensorflow\python\client\session.py", line 1297, in _run_fn
    self._extend_graph()
  File "D:\ProgramFiles\Conda\lib\site-packages\tensorflow\python\client\session.py", line 1358, in _extend_graph
    self._session, graph_def.SerializeToString(), status)
  File "D:\ProgramFiles\Conda\lib\contextlib.py", line 89, in __exit__
    next(self.gen)
  File "D:\ProgramFiles\Conda\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'Dequantize' with these attrs.  Registered devices: [CPU,GPU], Registered kernels:
  <no registered kernels>

         [[Node: MobilenetV1/Logits/Conv2d_1c_1x1/weights/read/_1__cf__1 = Dequantize[T=DT_QUINT8, mode="MIN_FIRST"](MobilenetV1/Logits/Conv2d_1c_1x1/weights/read/_1__cf__1_quantized_const, MobilenetV1/Logits/Conv2d_1c_1x1/weights/read/_1__cf__1_quantized_min, MobilenetV1/Logits/Conv2d_1c_1x1/weights/read/_1__cf__1_quantized_max)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\admin\Train\_TensorFlow train\tensorflow\tensorflow\examples\image_retraining\retrain.py", line 1326, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "D:\ProgramFiles\Conda\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "D:\admin\Train\_TensorFlow train\tensorflow\tensorflow\examples\image_retraining\retrain.py", line 1047, in main
    sess.run(init)
  File "D:\ProgramFiles\Conda\lib\site-packages\tensorflow\python\client\session.py", line 895, in run
    run_metadata_ptr)
  File "D:\ProgramFiles\Conda\lib\site-packages\tensorflow\python\client\session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "D:\ProgramFiles\Conda\lib\site-packages\tensorflow\python\client\session.py", line 1321, in _do_run
    options, run_metadata)
  File "D:\ProgramFiles\Conda\lib\site-packages\tensorflow\python\client\session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'Dequantize' with these attrs.  Registered devices: [CPU,GPU], Registered kernels:
  <no registered kernels>

         [[Node: MobilenetV1/Logits/Conv2d_1c_1x1/weights/read/_1__cf__1 = Dequantize[T=DT_QUINT8, mode="MIN_FIRST"](MobilenetV1/Logits/Conv2d_1c_1x1/weights/read/_1__cf__1_quantized_const, MobilenetV1/Logits/Conv2d_1c_1x1/weights/read/_1__cf__1_quantized_min, MobilenetV1/Logits/Conv2d_1c_1x1/weights/read/_1__cf__1_quantized_max)]]

Caused by op 'MobilenetV1/Logits/Conv2d_1c_1x1/weights/read/_1__cf__1', defined at:
  File "D:\admin\Train\_TensorFlow train\tensorflow\tensorflow\examples\image_retraining\retrain.py", line 1326, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "D:\ProgramFiles\Conda\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "D:\admin\Train\_TensorFlow train\tensorflow\tensorflow\examples\image_retraining\retrain.py", line 984, in main
    create_model_graph(model_info))
  File "D:\admin\Train\_TensorFlow train\tensorflow\tensorflow\examples\image_retraining\retrain.py", line 282, in create_model_graph
    model_info['resized_input_tensor_name'],
  File "D:\ProgramFiles\Conda\lib\site-packages\tensorflow\python\framework\importer.py", line 313, in import_graph_def
    op_def=op_def)
  File "D:\ProgramFiles\Conda\lib\site-packages\tensorflow\python\framework\ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "D:\ProgramFiles\Conda\lib\site-packages\tensorflow\python\framework\ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): No OpKernel was registered to support Op 'Dequantize' with these attrs.  Registered devices: [CPU,GPU], Registered kernels:
  <no registered kernels>

         [[Node: MobilenetV1/Logits/Conv2d_1c_1x1/weights/read/_1__cf__1 = Dequantize[T=DT_QUINT8, mode="MIN_FIRST"](MobilenetV1/Logits/Conv2d_1c_1x1/weights/read/_1__cf__1_quantized_const, MobilenetV1/Logits/Conv2d_1c_1x1/weights/read/_1__cf__1_quantized_min, MobilenetV1/Logits/Conv2d_1c_1x1/weights/read/_1__cf__1_quantized_max)]]

2017-09-20 11:10:45.882573: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-09-20 11:10:45.882593: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-20 11:10:46.641065: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:955] Found device 0 with properties:
name: GeForce 940MX
major: 5 minor: 0 memoryClockRate (GHz) 1.2415
pciBusID 0000:01:00.0
Total memory: 2.00GiB
Free memory: 1.66GiB
2017-09-20 11:10:46.641083: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:976] DMA: 0
2017-09-20 11:10:46.641088: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:986] 0:   Y
2017-09-20 11:10:46.641112: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:1045] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce 940MX, pci bus id: 0000:01:00.0)

```

**Comment by Prakash19921206** [comment]
having same above error! 
however  `--architecture mobilenet_1.0_128`    works
i'm using TensorFlow version 1.3, python 3.5, windows 7 64bit

 quantized is not supported in windows?
   `--architecture mobilenet_1.0_128_quantized`

**Comment by anonym24** [comment]
@wt-huang do you mean 1.13.0? when I use `pip install --upgrade tensorflow` it founds only 1.12.0 for windows

**Comment by anonym24** [comment]
@wt-huang I tried 1.13.0 nightly for Windows (1.13.0-dev20181130) but still I get this error:

```
InvalidArgumentError (see above for traceback): No OpKernel was registered to support Op 'Dequantize' used by node MobilenetV1/Conv2d_5_pointwise/weights/read/_52__cf__52 (defined at C:\tensorflow_class\scripts\retrain.py:282) with these attrs: [T=DT_QUINT8, mode="MIN_FIRST"]
Registered devices: [CPU, GPU]
Registered kernels:
  <no registered kernels>

         [[node MobilenetV1/Conv2d_5_pointwise/weights/read/_52__cf__52 (defined at C:\tensorflow_class\scripts\retrain.py:282) ]]

```

**Comment by GearWalker** [comment]
I'm got a problem too. I'm using tensorflow 1.12.0 with python 3.6.8 on Windows10 + GPU GTX1070

> tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'Dequantize' with these attrs.  Registered devices: [CPU,GPU], Registered kernels: <no registered kernels>

**Comment by rahulshenoy77** [comment]
I have got the same problem too. I'm using tensorflow 1.12.0 with python 3.6.8 on Windows10 + GPU GTX1060. Please help!

**Comment by Navpreet7** [comment]
Facing same issue in windows , retraining the mobilenetv1.0 model with --architecture=mobilenet_1.0_224_quantized
and got the error:
InvalidArgumentError (see above for traceback): No OpKernel was registered to support Op 'Dequantize' used by node MobilenetV1/Conv2d_5_pointwise/weights/read/_52__cf__52 (defined at retrain.py:282) with
these attrs: [T=DT_QUINT8, mode="MIN_FIRST"]
Registered devices: [CPU]
Registered kernels:
  <no registered kernels>

**Comment by Zhengzhongyou** [comment]
I have got the same problem too. How do you solve it in the end?

**Comment by hui121** [comment]
I have got the same problem too. Should install correct Build version.
I install tf1.15.0，package info：
tensorflow                1.15.0          **mkl_py**37h3789bd0_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
there is no error.
but if install tf1.15.0，pakage info: tensorflow                1.15.0          **eigen_py**37h9f89a44_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main,
there is an error: No OpKernel was registered to support Op 'Dequantize' .
