### ISSUE TITLE
Fail to restore the model after upgraded to version 1.2.1

### ISSUE THREAD

**Issue by rolai** [tensorflow/tensorflow#11964]
I trained my model in tensorflow version 1.1.0, and test or restore it successfully. But after I upgraded tensorflow to version 1.2.1,  I fail to restore the same model  with the same code!

### Error Log 
```
restore from ckpt: ./Models/dl_fast/TextRecognize/model-105000
2017-08-02 15:18:09.050018: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key bidirectional_rnn/bw/lstm_cell/bias not found in checkpoint
2017-08-02 15:18:09.050057: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key bidirectional_rnn/fw/lstm_cell/kernel not found in checkpoint
2017-08-02 15:18:09.050751: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key bidirectional_rnn/fw/lstm_cell/bias not found in checkpoint
2017-08-02 15:18:09.050753: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key bidirectional_rnn/bw/lstm_cell/kernel not found in checkpoint
Traceback (most recent call last):
  File "dl_fast_recognizer.py", line 151, in <module>
    text_recognizer_model=text_recognizer_model
  File "dl_fast_recognizer.py", line 37, in __init__
    self.text_recognizer = Predictor('dl_fast.yml', text_recognizer_model)
  File "../Recognition/predictor.py", line 45, in __init__
    saver.restore(self.sess, ckpt)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1548, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Key bidirectional_rnn/bw/lstm_cell/bias not found in checkpoint
	 [[Node: save/RestoreV2_6 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_6/tensor_names, save/RestoreV2_6/shape_and_slices)]]

Caused by op u'save/RestoreV2_6', defined at:
  File "dl_fast_recognizer.py", line 151, in <module>
    text_recognizer_model=text_recognizer_model
  File "dl_fast_recognizer.py", line 37, in __init__
    self.text_recognizer = Predictor('dl_fast.yml', text_recognizer_model)
  File "./Recognition/predictor.py", line 43, in __init__
    saver = tf.train.Saver(tf.global_variables(),max_to_keep=100)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1139, in __init__
    self.build()
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1170, in build
    restore_sequentially=self._restore_sequentially)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 691, in build
    restore_sequentially, reshape)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 407, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 247, in restore_op
    [spec.tensor.dtype])[0])
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_io_ops.py", line 640, in restore_v2
    dtypes=dtypes, name=name)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

NotFoundError (see above for traceback): Key bidirectional_rnn/bw/lstm_cell/bias not found in checkpoint
	 [[Node: save/RestoreV2_6 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_6/tensor_names, save/RestoreV2_6/shape_and_slices)]]
```

###  Restore Code
```
        with self.sess.as_default():
            with self.model.graph.as_default(), tf.device('/cpu:0'):
                self.sess.run(tf.global_variables_initializer())

                ckpt = tf.train.latest_checkpoint(model_path)
                print('restore from ckpt: {}'.format(ckpt))
                saver = tf.train.Saver(tf.global_variables(),max_to_keep=100)
                if ckpt:
                    saver.restore(self.sess, ckpt)
                    print('restored from ckpt: {}'.format(ckpt))
                else:
                    print('cannot restore')
```

Is it a bug of tensorflow or my code? How to fix it?

**Comment by asimshankar** [comment]
Sorry you ran into this.
I believe the RNN code was moved from experimental (`tf.contrib`) to the main repository in 1.2.0. Quoting from the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) of 1.2.0:

RNNCells' variable names have been renamed for consistency with Keras layers. Specifically, the previous variable names "weights" and "biases" have been changed to "kernel" and "bias", respectively. This may cause backward incompatibility with regard to your old checkpoints containing such RNN cells, in which case you can use the tool [checkpoint_convert script](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/rnn/python/tools/checkpoint_convert.py) to convert the variable names in your old checkpoints.

Do give that a spin and let us know if that works out.

**Comment by rolai** [comment]
It works. @asimshankar Thank you very much!
