### ISSUE TITLE
tensorflow-1.2.1：TypeError: sampled_loss() got an unexpected keyword argument 'logits'

### ISSUE THREAD

**Issue by yyx911216** [tensorflow/tensorflow#11994]
# the code is:
    def sampled_loss(labels, inputs):
            labels = tf.reshape(labels, [-1, 1])
            # We need to compute the sampled_softmax_loss using 32bit floats to
            # avoid numerical instabilities.
            local_w_t = tf.cast(w_t, tf.float32)
            local_b = tf.cast(b, tf.float32)
            local_inputs = tf.cast(inputs, tf.float32)
            return tf.cast(
                tf.nn.sampled_softmax_loss(
                    weights=local_w_t,
                    biases=local_b,
                    labels=labels,
                    inputs=local_inputs,
                    num_sampled=num_samples,
                    num_classes=self.target_vocab_size),tf.float32)
      
           softmax_loss_function = sampled_loss

Traceback (most recent call last):
  File "predict.py", line 177, in <module>
    tf.app.run()
  File "/home/amax/tensorflow/1.2.1/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "predict.py", line 159, in main
    decode()
  File "predict.py", line 40, in decode
    model = create_model(sess, True)
  File "/home/BD/bd_chenyi/nlp_code/textsum/textsum.py", line 144, in create_model
    forward_only=forward_only)
  File "/home/BD/bd_chenyi/nlp_code/textsum/seq2seq_model.py", line 167, in __init__
    softmax_loss_function=softmax_loss_function)
  File "/home/amax/tensorflow/1.2.1/local/lib/python2.7/site-packages/tensorflow/contrib/legacy_seq2seq/python/ops/seq2seq.py", line 1221, in model_with_buckets
    softmax_loss_function=softmax_loss_function))
  File "/home/amax/tensorflow/1.2.1/local/lib/python2.7/site-packages/tensorflow/contrib/legacy_seq2seq/python/ops/seq2seq.py", line 1134, in sequence_loss
    softmax_loss_function=softmax_loss_function))
  File "/home/amax/tensorflow/1.2.1/local/lib/python2.7/site-packages/tensorflow/contrib/legacy_seq2seq/python/ops/seq2seq.py", line 1089, in sequence_loss_by_example
    crossent = softmax_loss_function(labels=target, logits=logit)
TypeError: sampled_loss() got an unexpected keyword argument 'logits'

**Comment by shivaniag** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by wiseman** [comment]
Why isn't this a bug?  The bug seems to be in `tensorflow/contrib/legacy_seq2seq/python/ops/seq2seq.py`.

**Comment by jack-wxm** [comment]
Have you solved this problem? I also encountered this problem, the code is the same as yours, can you tell me how to solve it? Thank you very much!

**Comment by pangzis** [comment]
you can try to modify the first line to "def sampled_loss(labels, logits):".Of course, you need to modify the corresponding code below.I don't know why,but my code can working by this modify
