### ISSUE TITLE
Tensorboard Error on windows 

### ISSUE THREAD

**Issue by optnio00** [tensorflow/tensorflow#12055]
I want to use tensorboard on windows but when I am going to start it, its shows this error
```
(C:\Users\anura\Anaconda3) C:\Users\anura>tensorboard --logdir foo:C:\Users\anura\Desktop\Python\Tensorboard
Traceback (most recent call last):
  File "C:\Users\anura\Anaconda3\Scripts\tensorboard-script.py", line 3, in <module>
    import tensorflow.tensorboard.tensorboard
  File "C:\Users\anura\Anaconda3\lib\site-packages\tensorflow\tensorboard\tensorboard.py", line 33, in <module>
    from tensorflow.tensorboard.backend import application
  File "C:\Users\anura\Anaconda3\lib\site-packages\tensorflow\tensorboard\backend\application.py", line 47, in <module>
    from tensorflow.tensorboard.plugins.projector import projector_plugin
  File "C:\Users\anura\Anaconda3\lib\site-packages\tensorflow\tensorboard\plugins\projector\projector_plugin.py", line 28, in <module>
    from tensorflow.contrib.tensorboard.plugins.projector import PROJECTOR_FILENAME
  File "C:\Users\anura\Anaconda3\lib\site-packages\tensorflow\contrib\__init__.py", line 30, in <module>
    from tensorflow.contrib import factorization
  File "C:\Users\anura\Anaconda3\lib\site-packages\tensorflow\contrib\factorization\__init__.py", line 24, in <module>
    from tensorflow.contrib.factorization.python.ops.gmm import *
  File "C:\Users\anura\Anaconda3\lib\site-packages\tensorflow\contrib\factorization\python\ops\gmm.py", line 27, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import estimator
  File "C:\Users\anura\Anaconda3\lib\site-packages\tensorflow\contrib\learn\__init__.py", line 87, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "C:\Users\anura\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\__init__.py", line 23, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "C:\Users\anura\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\__init__.py", line 25, in <module>
    from tensorflow.contrib.learn.python.learn import estimators
  File "C:\Users\anura\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\__init__.py", line 297, in <module>
    from tensorflow.contrib.learn.python.learn.estimators.dnn import DNNClassifier
  File "C:\Users\anura\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\dnn.py", line 29, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import dnn_linear_combined
  File "C:\Users\anura\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\dnn_linear_combined.py", line 31, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import estimator
  File "C:\Users\anura\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\estimator.py", line 49, in <module>
    from tensorflow.contrib.learn.python.learn.learn_io import data_feeder
  File "C:\Users\anura\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\learn_io\__init__.py", line 21, in <module>
    from tensorflow.contrib.learn.python.learn.learn_io.dask_io import extract_dask_data
  File "C:\Users\anura\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\learn_io\dask_io.py", line 26, in <module>
    import dask.dataframe as dd
  File "C:\Users\anura\Anaconda3\lib\site-packages\dask\dataframe\__init__.py", line 3, in <module>
    from .core import (DataFrame, Series, Index, _Frame, map_partitions,
  File "C:\Users\anura\Anaconda3\lib\site-packages\dask\dataframe\core.py", line 36, in <module>
    pd.computation.expressions.set_use_numexpr(False)
AttributeError: module 'pandas' has no attribute 'computation'

(C:\Users\anura\Anaconda3) C:\Users\anura>
```
when is run localhost:6006 in my chrome browser 

![screenshot 140](https://user-images.githubusercontent.com/15853647/28995526-f9aa1742-7a08-11e7-92d6-f87038c9ea7a.png)

**Comment by tatatodd** [comment]
Please resubmit and pay attention to the issue template, including the version of TensorFlow and how you installed it (https://github.com/tensorflow/tensorflow/issues/new) . Please provide all the information it asks. Thank you.

**Comment by tatatodd** [comment]
In addition to filling out the issue template, please file tensorboard-related issues under the tensorboard repository:
https://github.com/tensorflow/tensorboard/issues
