### ISSUE TITLE
tf.py_func errors in freeze_graph

### ISSUE THREAD

**Issue by rolai** [tensorflow/tensorflow#12073]
I use `tf.py_func` in my networks, and it works fine in training and test mode.  Then I run `bazel-bin/tensorflow/python/tools/freeze_graph` to freeze the graph and generate xxx.pb file.
I try to restore the xxx.pb and run the model again, error happens.

### Erorr logs
```
2017-08-07 16:04:15.565535: W tensorflow/core/framework/op_kernel.cc:1158] Unknown: exceptions.KeyError: 'pyfunc_0'
Traceback (most recent call last):
  File "object_detector_pb.py", line 159, in <module>
    objects = detector.detect(img)
  File "object_detector_pb.py", line 118, in detect
    scores, boxes = self.im_detect(image)
  File "object_detector_pb.py", line 101, in im_detect
    scores, bbox_pred, rois = self.sess.run([self._cls_prob, self._bbox_pred, self._rois], feed)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnknownError: exceptions.KeyError: 'pyfunc_0'
	 [[Node: detector/MobilenetV1_2/ANCHOR_default/generate_anchors = PyFunc[Tin=[DT_INT32, DT_INT32, DT_INT32, DT_INT32, DT_FLOAT], Tout=[DT_FLOAT, DT_INT32], token="pyfunc_0", _device="/job:localhost/replica:0/task:0/cpu:0"](detector/MobilenetV1_2/ANCHOR_default/ToInt32, detector/MobilenetV1_2/ANCHOR_default/ToInt32_1, detector/MobilenetV1_2/ANCHOR_default/generate_anchors/input_2, detector/MobilenetV1_2/ANCHOR_default/generate_anchors/input_3, detector/MobilenetV1_2/ANCHOR_default/generate_anchors/input_4)]]

Caused by op u'detector/MobilenetV1_2/ANCHOR_default/generate_anchors', defined at:
  File "object_detector_pb.py", line 143, in <module>
    detector = ObjectDetector(model_path, config_file)
  File "object_detector_pb.py", line 76, in __init__
    tf.import_graph_def(graph_def, name="detector")
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/importer.py", line 311, in import_graph_def
    op_def=op_def)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

UnknownError (see above for traceback): exceptions.KeyError: 'pyfunc_0'
	 [[Node: detector/MobilenetV1_2/ANCHOR_default/generate_anchors = PyFunc[Tin=[DT_INT32, DT_INT32, DT_INT32, DT_INT32, DT_FLOAT], Tout=[DT_FLOAT, DT_INT32], token="pyfunc_0", _device="/job:localhost/replica:0/task:0/cpu:0"](detector/MobilenetV1_2/ANCHOR_default/ToInt32, detector/MobilenetV1_2/ANCHOR_default/ToInt32_1, detector/MobilenetV1_2/ANCHOR_default/generate_anchors/input_2, detector/MobilenetV1_2/ANCHOR_default/generate_anchors/input_3, detector/MobilenetV1_2/ANCHOR_default/generate_anchors/input_4)]]
```

I found the `tf.py_func` is not in the graph. How can I define and use the `tf.py_func` in freezed graph?

**Comment by yaroslavvb** [comment]
@petewarden would know if `tf.py_func` is meant to be supported for freeze graph

**Comment by huangwenwenlili** [comment]
I also encountered this problem, how to solve?

**Comment by rolai** [comment]
I didn't find a method to solve this problem gracefully. However you can try: split the graph into two sub-grapy, one before the py_func the other after the py_func.

**Comment by huangwenwenlili** [comment]
I  can't know how to do it? I have no idea for this problems.

**Comment by JacquelineWang** [comment]
Got the same problem.  Can you be more specific? @rolai

**Comment by rolai** [comment]
@huangwenwenlili @JacquelineWang 
Take `faster-rcnn` for example,  `py_func` is used to count the anchors and rois. The graph is splited into tow sub-graphs by the `py_func`:  `rpn` and `rcnn`. 
1. restore the faster-rcnn checkpoint model file into two checkpoint files (for `rpn` and `rcnn`)
2. freeze each checkpoint files  into one pb file
3. assemble the two pb files
   3.1 run rpn network
   3.2 run the py_func with the outputs of rpn network
   3.3 run the rcnn network with the outputs of py_func

**Comment by plin24** [comment]
Hi, @rolai . In my case,  `resnet_v1_50_3/rois/PyFunc` is in the freeze graph. However, I'm still suffering from the `pyfunc_0 is not found` error. Do you have any solutions for this, and please let me know if I misinterpret something. Thanks in advance.

**Comment by wangyunxiaa** [comment]
@rolai Hi,I have met the same problem, when I use py_func in my network, I can do inference and get the correct result,but after freeze network and save the graph_def to "model.pb", I cannot do test with error "pyfunc_0 is not found" .
do you have the solution of this problem?
