### ISSUE TITLE
distribute tensorflow programe failed when increase worker number

### ISSUE THREAD

**Issue by chengdianxuezi** [tensorflow/tensorflow#12080]
I run a distribute tensorflow programe with 5 ps and 20 workers. It work normal。
when I increase the worker number to 50, the programe fail. the error log as follow. 
I don't know how to debug this problem

2017-08-07 03:51:42.191472: E tensorflow/core/distributed_runtime/master.cc:251] Master init: Unavailable: {"created":"@1502077902.191300911","description":"OS Error","errno":104,"file":"external/grpc/src/core/lib/iomgr/tcp_posix.c","file_line":229,"grpc_status":14,"os_error":"Connection reset by peer","syscall":"recvmsg"}
2017-08-07 03:51:42.735190: E tensorflow/core/distributed_runtime/master.cc:251] Master init: Unavailable: {"created":"@1502077902.735079403","description":"OS Error","errno":104,"file":"external/grpc/src/core/lib/iomgr/tcp_posix.c","file_line":229,"grpc_status":14,"os_error":"Connection reset by peer","syscall":"recvmsg"}
2017-08-07 03:51:43.224557: E tensorflow/core/distributed_runtime/master.cc:251] Master init: Unavailable: {"created":"@1502077903.224418940","description":"OS Error","errno":104,"file":"external/grpc/src/core/lib/iomgr/tcp_posix.c","file_line":229,"grpc_status":14,"os_error":"Connection reset by peer","syscall":"recvmsg"}
2017-08-07 03:51:43.630253: I tensorflow/core/distributed_runtime/master.cc:203] CreateSession still waiting for response from worker: /job:ps/replica:0/task:1
2017-08-07 03:51:43.630305: I tensorflow/core/distributed_runtime/master.cc:203] CreateSession still waiting for response from worker: /job:ps/replica:0/task:4
2017-08-07 03:51:45.901058: E tensorflow/core/distributed_runtime/master.cc:251] Master init: Unavailable: {"created":"@1502077905.900893611","description":"OS Error","errno":104,"file":"external/grpc/src/core/lib/iomgr/tcp_posix.c","file_line":229,"grpc_status":14,"os_error":"Connection reset by peer","syscall":"recvmsg"}
2017-08-07 03:51:49.926346: E tensorflow/core/distributed_runtime/master.cc:251] Master init: Unavailable: {"created":"@1502077909.926169663","description":"OS Error","errno":104,"file":"external/grpc/src/core/lib/iomgr/tcp_posix.c","file_line":229,"grpc_status":14,"os_error":"Connection reset by peer","syscall":"recvmsg"}
Traceback (most recent call last):
File "/home/xiangqin.oxq/tensorflow/train_ps.py", line 117, in <module>
tf.app.run()
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
_sys.exit(main(_sys.argv[:1] + flags_passthrough))
File "/home/xiangqin.oxq/tensorflow/train_ps.py", line 106, in main
with sv.prepare_or_wait_for_session(server.target, config=sess_config, max_wait_secs=600) as sess:
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/supervisor.py", line 714, in prepare_or_wait_for_session
max_wait_secs=max_wait_secs)
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/session_manager.py", line 384, in wait_for_session
sess)
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/session_manager.py", line 467, in _try_run_local_init_op
sess.run(self._local_init_op)
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 786, in run
run_metadata_ptr)
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 994, in _run
feed_dict_string, options, run_metadata)
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1044, in _do_run
target_list, options, run_metadata)
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1064, in _do_call
raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnavailableError: {"created":"@1502077902.191300911","description":"OS Error","errno":104,"file":"external/grpc/src/core/lib/iomgr/tcp_posix.c","file_line":229,"grpc_status":14,"os_error":"Connection reset by peer","syscall":"recvmsg"}

**Comment by yaroslavvb** [comment]
1. This normal behavior of TensorFlow when there's connection error on operating system level. You need to catch exception and recreate the session.
2. It would be useful to figure out why your system fails to connect. This is external to TensorFlow. For instance, I've dealt with this error caused by Azure SNAT which reset connections after 4mins: https://blogs.msdn.microsoft.com/mast/2015/07/13/azure-snat/

**Comment by chengdianxuezi** [comment]
@yaroslavvb  thank you for your help, I try to catch the excetption and recreate the session.

**Comment by gclouding** [comment]
@chengdianxuezi have you solved the problem ?

**Comment by tensorflowbutler** [comment]
This issue is automatically closed due to lack of activity. Please re-open if this is still an issue for you. Thanks!
