### ISSUE TITLE
InvalidArgumentError mobilenet

### ISSUE THREAD

**Issue by Zumbalamambo** [tensorflow/tensorflow#12084]
im getting the following error while training my own dataset with mobilenet

```
Caused by op 'MobilenetV1/MobilenetV1/Conv2d_1_depthwise/depthwise', defined at:
  File "tensorflow/examples/image_retraining/retrain.py", line 1326, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/Users/zumbala/anaconda/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "tensorflow/examples/image_retraining/retrain.py", line 984, in main
    create_model_graph(model_info))
  File "tensorflow/examples/image_retraining/retrain.py", line 282, in create_model_graph
    model_info['resized_input_tensor_name'],
  File "/Users/zumbala/anaconda/lib/python3.5/site-packages/tensorflow/python/framework/importer.py", line 287, in import_graph_def
    op_def=op_def)
  File "/Users/zumbala/anaconda/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2395, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/Users/zumbala/anaconda/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1264, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): NodeDef mentions attr 'data_format' not in Op<name=DepthwiseConv2dNative; signature=input:T, filter:T -> output:T; attr=T:type,allowed=[DT_FLOAT, DT_DOUBLE]; attr=strides:list(int); attr=padding:string,allowed=["SAME", "VALID"]>; NodeDef: MobilenetV1/MobilenetV1/Conv2d_1_depthwise/depthwise = DepthwiseConv2dNative[T=DT_FLOAT, data_format="NHWC", padding="SAME", strides=[1, 1, 1, 1], _device="/job:localhost/replica:0/task:0/cpu:0"](MobilenetV1/MobilenetV1/Conv2d_0/Relu6, MobilenetV1/Conv2d_1_depthwise/depthwise_weights/read)
	 [[Node: MobilenetV1/MobilenetV1/Conv2d_1_depthwise/depthwise = DepthwiseConv2dNative[T=DT_FLOAT, data_format="NHWC", padding="SAME", strides=[1, 1, 1, 1], _device="/job:localhost/replica:0/task:0/cpu:0"](MobilenetV1/MobilenetV1/Conv2d_0/Relu6, MobilenetV1/Conv2d_1_depthwise/depthwise_weights/read)]]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tensorflow/examples/image_retraining/retrain.py", line 1326, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/Users/zumbala/anaconda/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "tensorflow/examples/image_retraining/retrain.py", line 1025, in main
    bottleneck_tensor, FLAGS.architecture)
  File "tensorflow/examples/image_retraining/retrain.py", line 476, in cache_bottlenecks
    resized_input_tensor, bottleneck_tensor, architecture)
  File "tensorflow/examples/image_retraining/retrain.py", line 418, in get_or_create_bottleneck
    bottleneck_tensor)
  File "tensorflow/examples/image_retraining/retrain.py", line 373, in create_bottleneck_file
    str(e)))
RuntimeError: Error during processing file tensorflow/examples/image_retraining/dataset/female/2Q== (1).jpg (NodeDef mentions attr 'data_format' not in Op<name=DepthwiseConv2dNative; signature=input:T, filter:T -> output:T; attr=T:type,allowed=[DT_FLOAT, DT_DOUBLE]; attr=strides:list(int); attr=padding:string,allowed=["SAME", "VALID"]>; NodeDef: MobilenetV1/MobilenetV1/Conv2d_1_depthwise/depthwise = DepthwiseConv2dNative[T=DT_FLOAT, data_format="NHWC", padding="SAME", strides=[1, 1, 1, 1], _device="/job:localhost/replica:0/task:0/cpu:0"](MobilenetV1/MobilenetV1/Conv2d_0/Relu6, MobilenetV1/Conv2d_1_depthwise/depthwise_weights/read)
	 [[Node: MobilenetV1/MobilenetV1/Conv2d_1_depthwise/depthwise = DepthwiseConv2dNative[T=DT_FLOAT, data_format="NHWC", padding="SAME", strides=[1, 1, 1, 1], _device="/job:localhost/replica:0/task:0/cpu:0"](MobilenetV1/MobilenetV1/Conv2d_0/Relu6, MobilenetV1/Conv2d_1_depthwise/depthwise_weights/read)]]

Caused by op 'MobilenetV1/MobilenetV1/Conv2d_1_depthwise/depthwise', defined at:
  File "tensorflow/examples/image_retraining/retrain.py", line 1326, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/Users/zumbala/anaconda/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "tensorflow/examples/image_retraining/retrain.py", line 984, in main
    create_model_graph(model_info))
  File "tensorflow/examples/image_retraining/retrain.py", line 282, in create_model_graph
    model_info['resized_input_tensor_name'],
  File "/Users/zumbala/anaconda/lib/python3.5/site-packages/tensorflow/python/framework/importer.py", line 287, in import_graph_def
    op_def=op_def)
  File "/Users/zumbala/anaconda/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2395, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/Users/zumbala/anaconda/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1264, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): NodeDef mentions attr 'data_format' not in Op<name=DepthwiseConv2dNative; signature=input:T, filter:T -> output:T; attr=T:type,allowed=[DT_FLOAT, DT_DOUBLE]; attr=strides:list(int); attr=padding:string,allowed=["SAME", "VALID"]>; NodeDef: MobilenetV1/MobilenetV1/Conv2d_1_depthwise/depthwise = DepthwiseConv2dNative[T=DT_FLOAT, data_format="NHWC", padding="SAME", strides=[1, 1, 1, 1], _device="/job:localhost/replica:0/task:0/cpu:0"](MobilenetV1/MobilenetV1/Conv2d_0/Relu6, MobilenetV1/Conv2d_1_depthwise/depthwise_weights/read)
	 [[Node: MobilenetV1/MobilenetV1/Conv2d_1_depthwise/depthwise = DepthwiseConv2dNative[T=DT_FLOAT, data_format="NHWC", padding="SAME", strides=[1, 1, 1, 1], _device="/job:localhost/replica:0/task:0/cpu:0"](MobilenetV1/MobilenetV1/Conv2d_0/Relu6, MobilenetV1/Conv2d_1_depthwise/depthwise_weights/read)]]
)

```

**Comment by Mazecreator** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mazecreator@gmail.com
    Domain mazecreator.com has exceeded the max emails per hour (29/25 (115%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
------ The body of the message is 14155 characters long; only the first
------ 5000 or so are included here.
Received: from o7.sgmail.github.com ([167.89.101.198]:58440)
	by server2.lowesthostingrates.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <bounces+848413-e6d9-mazecreator=mazecreator.com@sgmail.github.com>)
	id 1demEA-0003IL-6V
	for mazecreator@mazecreator.com; Mon, 07 Aug 2017 12:54:36 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=0AINoU+s8aDu8A0Euo5ZQRyHbE0=; b=EzM3/8YjKMtskB3A
	Uuz9VclXz+GKFnD8nBjACKldiL5cNmTzlbOSeybFUJaW5JOl/tMEvQJrt598AU6o
	riweKno2pROgbeh7llr6cghvCEvO+lDdMKGSVYQZaU/luSXg6cbedfvG+GQHNbQ2
	aVm0SGy0Ybxr6ZSp2PgFaK2C40Y=
Received: by filter0560p1mdw1.sendgrid.net with SMTP id filter0560p1mdw1-32731-5988ABC7-53
        2017-08-07 18:04:55.744833811 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0026p1mdw1.sendgrid.net (SG) with ESMTP id CGugROtmTEae8rmw3IRN4w
	for <mazecreator@mazecreator.com>; Mon, 07 Aug 2017 18:04:55.716 +0000 (UTC)
Date: Mon, 07 Aug 2017 18:04:55 +0000 (UTC)

**Comment by rohan100jain** [comment]
Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?  Make sure you also include the exact command if possible to produce  the output included in your test case. If you are unclear what to include  see the issue template displayed in  [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

 We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!

Please also provide the exact command you issued for execution.

**Comment by b01902041** [comment]
Hi @rohan100jain
I have the same problem.
I was running this code on GCP:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/image_retraining/retrain.py

the version of tensorflow I used: 
1.2.1

Thanks a lot.

**Comment by Zumbalamambo** [comment]
tensorflow 1.2.1
windows 10
8 gb ram, cpu

thats the spec

**Comment by ali01** [comment]
Please follow the [new issue template](https://github.com/tensorflow/tensorflow/issues/new). We need more information in order to be able to help.

**Comment by vitutc** [comment]
Hi I am having a similar issue in which prediction on GCP ML-ENGINE gives an error related to the "data_format" attr using mobilenet_v1 from the tutorials:

Tried asking in StackOverflow but nothing so far
https://stackoverflow.com/questions/45953344/getting-error-on-ml-engine-predict-but-local-predict-works-fine

**Comment by cmvikas94** [comment]
I am trying to run mobilenet model trained over imagenet on Android Tensorflow for object recognition and facing the issue as described below.

```
 TensorFlowInferenceInterface: Failed to load model 
 from 'file:///android_asset/mobilenet_imagenet.pb': java.io.IOException: 
 Not a valid TensorFlow Graph serialization: 
 NodeDef mentions attr 'data_format' not in Op<name=DepthwiseConv2dNative;
 signature=input:T, filter:T -> output:T; 
 attr=T:type,allowed=[DT_FLOAT, DT_DOUBLE]; attr=strides:list(int); 
 attr=padding:string,allowed=["SAME", "VALID"]>; 
 NodeDef: conv_dw_1/depthwise = 
 DepthwiseConv2dNative[T=DT_FLOAT, data_format="NHWC", padding="SAME", strides=[1, 1, 1, 1]]
 (conv1_relu/clip_by_value, conv_dw_1/depthwise_kernel/read)

```
I followed the tutorial as given in the [link](https://blog.mindorks.com/android-tensorflow-machine-learning-example-ff0e9b2654cc) to integrate Tensorflow on Android. I could run basic CNN classifier custom trained (using python 2.7.12, Tensorflow 1.2 on Ubuntu 16.04) and it is working fine.

I could successfully run Mobilenet trained over imagenet on python 2.7.12 on Ubuntu 16.04 using Tensorflow 1.2 and 1.3. Now when I try to run the same '.pb' model on Android it gives me the error as mentioned above.
 
The code for initializing the model is as given below :

   ```Java
TensorFlowImageClassifier c = new TensorFlowImageClassifier();
   c.inferenceInterface = new TensorFlowInferenceInterface();
   if (c.inferenceInterface.initializeTensorFlow(assetManager, modelFilename) != 0) {
            throw new RuntimeException("TF initialization failed");
   }

```
Please suggest me solution or work around. Thank you

**Comment by cmvikas94** [comment]
The above issue has been resolved by updating the "libandroid_tensorflow_inference_java.jar" and "libtensorflow_inference.so" to the latest version i.e. Tensorflow - 1.4. The latest ".jar" and ".so" files can be found [here](https://ci.tensorflow.org/view/Nightly/job/nightly-android/).

The issue was due to mismatch of Tensorflow versions. Mobilenet classifier trained over ImageNet was built on Tensorflow - 1.3 and was being used for inference on Android with Tensorflow - 1.1.

The stackoverflow answer can be found [here](https://stackoverflow.com/a/47493624/7665986)

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Awaiting TensorFlower: It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Awaiting TensorFlower: It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Awaiting TensorFlower: It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging TensorFlower: It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tatatodd** [comment]
Assigning to @petewarden for further triage.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @petewarden: It has been 16 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @petewarden: It has been 31 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @petewarden: It has been 46 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @petewarden: It has been 61 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @petewarden: It has been 76 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @petewarden: It has been 91 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @petewarden: It has been 106 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @petewarden: It has been 121 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @petewarden: It has been 136 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @petewarden: It has been 151 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @petewarden: It has been 166 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @petewarden: It has been 181 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @petewarden: It has been 196 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by petewarden** [comment]
Looks like this is resolved, so closing.
