### ISSUE TITLE
ImportError: undefined symbol: clock_gettime

### ISSUE THREAD

**Issue by markusdr** [tensorflow/tensorflow#121]
I ran these successfully:

    $ bazel build -c opt //tensorflow/tools/pip_package:build_pip_package
    $ bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg
    $ pip install --user /tmp/tensorflow_pkg/tensorflow-0.5.0-py2-none-any.whl

But the `convolutional.py` Python script gives an error:

    $ python2.7 tensorflow/models/image/mnist/convolutional.py
    Traceback (most recent call last):
      File "tensorflow/models/image/mnist/convolutional.py", line 13, in <module>
        import tensorflow.python.platform
      File "/home/name/.local/lib/python2.7/site-packages/tensorflow/__init__.py", line 4, in <module>
        from tensorflow.python import *
      File "/home/name/.local/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 22, in <module>
        from tensorflow.python.client.client_lib import *
      File "/home/name/.local/lib/python2.7/site-packages/tensorflow/python/client/client_lib.py", line 35, in <module>
        from tensorflow.python.client.session import InteractiveSession
      File "/home/name/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 11, in <module>
        from tensorflow.python import pywrap_tensorflow as tf_session
      File "/home/name/.local/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 26, in <module>
        _pywrap_tensorflow = swig_import_helper()
      File "/home/name/.local/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 22, in swig_import_helper
        _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
    ImportError: /home/name/.local/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so: 
    undefined symbol: clock_gettime

**Comment by mrry** [comment]
Which OS version and glibc version are you using? Based the answers to [a similar stackoverflow question](http://stackoverflow.com/questions/2418157/ubuntu-linux-c-error-undefined-reference-to-clock-gettime-and-clock-settim), my guess is that you have a glibc version earlier than 2.17, which is needed for the binary distribution to work.

The easiest workaround may be to install a Docker container containing TensorFlow, by following [the instructions here](http://tensorflow.org/get_started/os_setup.md#docker-based_installation).

**Comment by markusdr** [comment]
Docker seems like a good option, though I don't have root/sudo access on my current machine, so it's harder to install.

I did just solve the import error `undefined symbol: clock_gettime` error, by adding -lrt to the build like this:

    --- a/tensorflow/tensorflow.bzl
    +++ b/tensorflow/tensorflow.bzl
    @@ -284,7 +284,7 @@ _py_wrap_cc = rule(attrs={
    
     def tf_extension_linkopts():
    -  return []  # No extension link opts
    +  return ["-lrt"]

**Comment by mrry** [comment]
Thanks for checking that that works!

**Comment by penthoy** [comment]
might be a bit off topic but I'm getting the same error on another openai package:

```
>>> import fastzbarlight
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.4/site-packages/fastzbarlight/__init__.py", line 7, in <module>
    from ._zbarlight import zbar_code_scanner
ImportError: /usr/lib64/python3.4/site-packages/fastzbarlight/_zbarlight.cpython-34m.so: undefined symbol: clock_gettime
```
