### ISSUE TITLE
bug with tf.unique where index output is int64

### ISSUE THREAD

**Issue by dantkz** [tensorflow/tensorflow#12113]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: OSX El Capitan 10.11.6 
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: v1.3.0-rc1-27-g2784b1c 1.3.0-rc2
- **Python version**: 3.5.2
- **Bazel version (if compiling from source)**: n/a
- **CUDA/cuDNN version**: n/a
- **GPU model and memory**: n/a
- **Exact command to reproduce**: y, idx = tf.unique(x, out_idx=tf.int64)

### Describe the problem
The API says `tf.unique` supports `tf.int64` index output. However, no OpKernel supports such attributes.

### Source code / logs
To reproduce:

```
import tensorflow as tf
import numpy as np

x = tf.convert_to_tensor(np.array([0,1,2,0,1,2], dtype=np.int64))
y, idx = tf.unique(x, out_idx=tf.int64)
sess = tf.Session()
print(sess.run(idx))
```

Output on Macbook Air:
```
2017-08-08 16:43:20.546840: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-08-08 16:43:20.546883: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-08-08 16:43:20.546895: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-08-08 16:43:20.546905: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
Traceback (most recent call last):
  File "/Users/dturmukh/anaconda/envs/python3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1327, in _do_call
    return fn(*args)
  File "/Users/dturmukh/anaconda/envs/python3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1297, in _run_fn
    self._extend_graph()
  File "/Users/dturmukh/anaconda/envs/python3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1358, in _extend_graph
    self._session, graph_def.SerializeToString(), status)
  File "/Users/dturmukh/anaconda/envs/python3/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/Users/dturmukh/anaconda/envs/python3/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'Unique' with these attrs.  Registered devices: [CPU], Registered kernels:
  device='CPU'; T in [DT_INT64]; out_idx in [DT_INT32]
  device='CPU'; T in [DT_INT32]; out_idx in [DT_INT32]
  device='CPU'; T in [DT_UINT16]; out_idx in [DT_INT32]
  device='CPU'; T in [DT_INT16]; out_idx in [DT_INT32]
  device='CPU'; T in [DT_UINT8]; out_idx in [DT_INT32]
  device='CPU'; T in [DT_INT8]; out_idx in [DT_INT32]
  device='CPU'; T in [DT_HALF]; out_idx in [DT_INT32]
  device='CPU'; T in [DT_FLOAT]; out_idx in [DT_INT32]
  device='CPU'; T in [DT_DOUBLE]; out_idx in [DT_INT32]
  device='CPU'; T in [DT_STRING]; out_idx in [DT_INT32]
  device='GPU'; T in [DT_INT32]; out_idx in [DT_INT32]
  device='GPU'; T in [DT_INT64]; out_idx in [DT_INT32]

	 [[Node: Unique = Unique[T=DT_INT64, out_idx=DT_INT64](Const)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "unique.py", line 7, in <module>
    print(sess.run(idx))
  File "/Users/dturmukh/anaconda/envs/python3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/Users/dturmukh/anaconda/envs/python3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "/Users/dturmukh/anaconda/envs/python3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    options, run_metadata)
  File "/Users/dturmukh/anaconda/envs/python3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'Unique' with these attrs.  Registered devices: [CPU], Registered kernels:
  device='CPU'; T in [DT_INT64]; out_idx in [DT_INT32]
  device='CPU'; T in [DT_INT32]; out_idx in [DT_INT32]
  device='CPU'; T in [DT_UINT16]; out_idx in [DT_INT32]
  device='CPU'; T in [DT_INT16]; out_idx in [DT_INT32]
  device='CPU'; T in [DT_UINT8]; out_idx in [DT_INT32]
  device='CPU'; T in [DT_INT8]; out_idx in [DT_INT32]
  device='CPU'; T in [DT_HALF]; out_idx in [DT_INT32]
  device='CPU'; T in [DT_FLOAT]; out_idx in [DT_INT32]
  device='CPU'; T in [DT_DOUBLE]; out_idx in [DT_INT32]
  device='CPU'; T in [DT_STRING]; out_idx in [DT_INT32]
  device='GPU'; T in [DT_INT32]; out_idx in [DT_INT32]
  device='GPU'; T in [DT_INT64]; out_idx in [DT_INT32]

	 [[Node: Unique = Unique[T=DT_INT64, out_idx=DT_INT64](Const)]]

Caused by op 'Unique', defined at:
  File "unique.py", line 5, in <module>
    y, idx = tf.unique(x, out_idx=tf.int64)
  File "/Users/dturmukh/anaconda/envs/python3/lib/python3.5/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3927, in unique
    result = _op_def_lib.apply_op("Unique", x=x, out_idx=out_idx, name=name)
  File "/Users/dturmukh/anaconda/envs/python3/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/Users/dturmukh/anaconda/envs/python3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/Users/dturmukh/anaconda/envs/python3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): No OpKernel was registered to support Op 'Unique' with these attrs.  Registered devices: [CPU], Registered kernels:
  device='CPU'; T in [DT_INT64]; out_idx in [DT_INT32]
  device='CPU'; T in [DT_INT32]; out_idx in [DT_INT32]
  device='CPU'; T in [DT_UINT16]; out_idx in [DT_INT32]
  device='CPU'; T in [DT_INT16]; out_idx in [DT_INT32]
  device='CPU'; T in [DT_UINT8]; out_idx in [DT_INT32]
  device='CPU'; T in [DT_INT8]; out_idx in [DT_INT32]
  device='CPU'; T in [DT_HALF]; out_idx in [DT_INT32]
  device='CPU'; T in [DT_FLOAT]; out_idx in [DT_INT32]
  device='CPU'; T in [DT_DOUBLE]; out_idx in [DT_INT32]
  device='CPU'; T in [DT_STRING]; out_idx in [DT_INT32]
  device='GPU'; T in [DT_INT32]; out_idx in [DT_INT32]
  device='GPU'; T in [DT_INT64]; out_idx in [DT_INT32]

	 [[Node: Unique = Unique[T=DT_INT64, out_idx=DT_INT64](Const)]]
```

**Comment by yongtang** [comment]
Created a PR #12129 to address the int64 support for `tf.unique`.

**Comment by tatatodd** [comment]
Thanks @yongtang for the quick PR!  Marking this as community support; it'll get closed when the PR gets merged.
