### ISSUE TITLE
InvalidArgumentError in tensorflow reduce_sum gradient when compiling from sources

### ISSUE THREAD

**Issue by tbsflk** [tensorflow/tensorflow#12177]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Windows 10
- **TensorFlow installed from (source or binary)**:
source
- **TensorFlow version (use command below)**:
1.3.0rc2
- **Python version**: 
3.5.3
- **Bazel version (if compiling from source)**:
cmake 3.9.0
- **CUDA/cuDNN version**:
cpu only
- **GPU model and memory**:
cpu only
- **Exact command to reproduce**:

I compiled tensorflow from source according to the instructions given here: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/cmake/README.md
I activated support for AVX (that's the reason I want to compile from source). All steps work without problems. I then install the whl with pip in my python environment.

Now, if I run my code with that version of tf, it crashes, but it works if I use a pre-compiled version.

### Describe the problem
A script that runs without problems when I use a pre-built version of tensorflow throws an error when I use the compiled version (see below for trace). I also compiled r1.2 and saw the same problem. Since the code works with the pre-built tf version (1.1), I suspect the problem is related to compiling from source.

### Source code / logs
Error when running with the compiled tf:

```
  File "test_network.py", line 35, in <module>
    network = Network(**configuration)
[elided 0 identical lines from previous traceback]
  File "C:\Users\falke\EclipseWorkspace\nn\src\codebase\network.py", line 194, in __init__
    self._build_graph()
  File "C:\Users\falke\EclipseWorkspace\nn\src\codebase\network.py", line 227, in _build_graph
    self.graph_states = gop(self.graph_states, enc_state)
  File "C:\Users\falke\EclipseWorkspace\nn\src\codebase\network.py", line 158, in __call__
    w = tf.exp(tf.reduce_sum(tf.multiply(node_labels, enc_state), axis=2, keep_dims=True))
  File "C:\Anaconda\envs\tfc\lib\site-packages\tensorflow\python\ops\math_ops.py", line 1279, in reduce_sum
    name=name)
  File "C:\Anaconda\envs\tfc\lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 2727, in _sum
    keep_dims=keep_dims, name=name)
  File "C:\Anaconda\envs\tfc\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 328, in apply_op
    op_type_name, name, **keywords)
  File "C:\Anaconda\envs\tfc\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\Anaconda\envs\tfc\lib\site-packages\tensorflow\python\framework\ops.py", line 2624, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "C:\Anaconda\envs\tfc\lib\site-packages\tensorflow\python\framework\ops.py", line 1210, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): indices[1] is out of range
         [[Node: opt/gradients/node_label_update_1/Sum_grad/DynamicStitch = DynamicStitch[N=2, T=DT_INT32, _device="/job:localhost/replica:0/task:0/cpu:0"](opt/gradients/node_label_update_1/Sum_grad/range, opt/gradients/node_label_update_1/Sum_grad/mod, opt/gradients/node_label_update_1/Sum_grad/Shape, opt/gradients/node_label_update_1/Sum_grad/Fill)]]
```

The code causing the error is:
`w = tf.exp(tf.reduce_sum(tf.multiply(node_labels, enc_state), axis=2, keep_dims=True))`
Both `node_labels` and `enc_state` are 40x5x30 dim tensors. And as I already said, there are no issues at all running this code if I don't compile from source.

**Comment by skye** [comment]
To help narrow down this issue, have you tried compiling without AVX support and seen if that works as expected?

**Comment by tbsflk** [comment]
I just tried it, I don't see that error then, but get OutOfMemory errors instead (it looks like they happen at a later point, but I can't say that for sure).

`2017-08-14 23:00:34.852292: W C:\tf\tensorflow\tensorflow\core\framework\op_kernel.cc:1192] Resource exhausted: OOM when allocating tensor with shape[189918321]` (occurs many times)

**Comment by skye** [comment]
Hm, I wonder if the OOM error is somehow happening with your AVX code but manifesting in a weird way. Are you able to provide a script we can use to repro the problem?

**Comment by tbsflk** [comment]
The following code is enough to produce the described issue on my machine:

```
import numpy as np

x = tf.placeholder(tf.float32, [2,3])
y = tf.placeholder(tf.float32, [2,3])
W = tf.Variable(tf.random_normal([3,3], stddev=0.01))

z = tf.matmul(x, W)
# works when removing the reduce_sum op
z = tf.reduce_sum(tf.multiply(z, y), axis=1, keep_dims=True)

optimizer = tf.train.AdamOptimizer()
train_op = optimizer.minimize(z)

Xdata = np.array([[1,2,3],[4,5,6]])
Ydata = np.array([[2,3,4],[3,4,5]])

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    sess.run(train_op, feed_dict={ x: Xdata, y: Ydata })
    print('done')
```

With TF 1.3.0rc2, compiled from source, with AVX support, I get the described error:

```
>python mwe.py
2017-08-15 07:14:19.860434: W C:\tf\tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
Traceback (most recent call last):
  File "C:\Anaconda\envs\tfc\lib\site-packages\tensorflow\python\client\session.py", line 1321, in _do_call
    return fn(*args)
  File "C:\Anaconda\envs\tfc\lib\site-packages\tensorflow\python\client\session.py", line 1300, in _run_fn
    status, run_metadata)
  File "C:\Anaconda\envs\tfc\lib\contextlib.py", line 66, in __exit__
    next(self.gen)
  File "C:\Anaconda\envs\tfc\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 466, in raise_exception_on_not_ok_status
    c_api.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[1] is out of range
         [[Node: gradients/Sum_grad/DynamicStitch = DynamicStitch[N=2, T=DT_INT32, _device="/job:localhost/replica:0/task:0/cpu:0"](gradients/Sum_grad/range, gradients/Sum_grad/mod, gradients/Sum_grad/Shape, gradients/Sum_grad/Fill)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mwe.py", line 23, in <module>
    sess.run(train_op, feed_dict={ x: X, y: Y })
  File "C:\Anaconda\envs\tfc\lib\site-packages\tensorflow\python\client\session.py", line 889, in run
    run_metadata_ptr)
  File "C:\Anaconda\envs\tfc\lib\site-packages\tensorflow\python\client\session.py", line 1118, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Anaconda\envs\tfc\lib\site-packages\tensorflow\python\client\session.py", line 1315, in _do_run
    options, run_metadata)
  File "C:\Anaconda\envs\tfc\lib\site-packages\tensorflow\python\client\session.py", line 1334, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[1] is out of range
         [[Node: gradients/Sum_grad/DynamicStitch = DynamicStitch[N=2, T=DT_INT32, _device="/job:localhost/replica:0/task:0/cpu:0"](gradients/Sum_grad/range, gradients/Sum_grad/mod, gradients/Sum_grad/Shape, gradients/Sum_grad/Fill)]]

Caused by op 'gradients/Sum_grad/DynamicStitch', defined at:
  File "mwe.py", line 15, in <module>
    train_op = optimizer.minimize(z)
  File "C:\Anaconda\envs\tfc\lib\site-packages\tensorflow\python\training\optimizer.py", line 336, in minimize
    grad_loss=grad_loss)
  File "C:\Anaconda\envs\tfc\lib\site-packages\tensorflow\python\training\optimizer.py", line 407, in compute_gradients
    colocate_gradients_with_ops=colocate_gradients_with_ops)
  File "C:\Anaconda\envs\tfc\lib\site-packages\tensorflow\python\ops\gradients_impl.py", line 542, in gradients
    grad_scope, op, func_call, lambda: grad_fn(op, *out_grads))
  File "C:\Anaconda\envs\tfc\lib\site-packages\tensorflow\python\ops\gradients_impl.py", line 348, in _MaybeCompile
    return grad_fn()  # Exit early
  File "C:\Anaconda\envs\tfc\lib\site-packages\tensorflow\python\ops\gradients_impl.py", line 542, in <lambda>
    grad_scope, op, func_call, lambda: grad_fn(op, *out_grads))
  File "C:\Anaconda\envs\tfc\lib\site-packages\tensorflow\python\ops\math_grad.py", line 56, in _SumGrad
    output_shape_kept_dims = math_ops.reduced_shape(input_shape, op.inputs[1])
  File "C:\Anaconda\envs\tfc\lib\site-packages\tensorflow\python\ops\math_ops.py", line 2318, in reduced_shape
    array_ops.fill(axes_shape, 1)
  File "C:\Anaconda\envs\tfc\lib\site-packages\tensorflow\python\ops\gen_data_flow_ops.py", line 480, in dynamic_stitch
    name=name)
  File "C:\Anaconda\envs\tfc\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 328, in apply_op
    op_type_name, name, **keywords)
  File "C:\Anaconda\envs\tfc\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\Anaconda\envs\tfc\lib\site-packages\tensorflow\python\framework\ops.py", line 2624, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "C:\Anaconda\envs\tfc\lib\site-packages\tensorflow\python\framework\ops.py", line 1210, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

...which was originally created as op 'Sum', defined at:
  File "mwe.py", line 12, in <module>
    z = tf.reduce_sum(tf.multiply(z, y), axis=1, keep_dims=True)
  File "C:\Anaconda\envs\tfc\lib\site-packages\tensorflow\python\ops\math_ops.py", line 1279, in reduce_sum
    name=name)
  File "C:\Anaconda\envs\tfc\lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 2727, in _sum
    keep_dims=keep_dims, name=name)
  File "C:\Anaconda\envs\tfc\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 328, in apply_op
    op_type_name, name, **keywords)
  File "C:\Anaconda\envs\tfc\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\Anaconda\envs\tfc\lib\site-packages\tensorflow\python\framework\ops.py", line 2624, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "C:\Anaconda\envs\tfc\lib\site-packages\tensorflow\python\framework\ops.py", line 1210, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): indices[1] is out of range
         [[Node: gradients/Sum_grad/DynamicStitch = DynamicStitch[N=2, T=DT_INT32, _device="/job:localhost/replica:0/task:0/cpu:0"](gradients/Sum_grad/range, gradients/Sum_grad/mod, gradients/Sum_grad/Shape, gradients/Sum_grad/Fill)]]
```

With TF 1.3.0rc2, compiled from source, _without_ AVX support, I get an error related to dimensionality (but not the OOM I saw running the full code):

```
>python mwe.py
2017-08-15 07:21:07.349599: W C:\tf\tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-08-15 07:21:07.349726: W C:\tf\tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-08-15 07:21:29.352682: F C:\tf\tensorflow\tensorflow\core\framework\tensor_shape.cc:243] Check failed: ndims_byte() < MaxDimensions() (unsigned char value 254 vs. 254)Too many dimensions in tensor
```

With TF 1.1.0, pre-compiled, it runs just fine:

```
>python mwe.py
2017-08-15 07:22:31.147908: W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE instructions, but these are available on your machine and could speed up CPU computations.
2017-08-15 07:22:31.148040: W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE2 instructions, but these are available on your machine and could speed up CPU computations.
2017-08-15 07:22:31.149626: W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
2017-08-15 07:22:31.149752: W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-08-15 07:22:31.149881: W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-08-15 07:22:31.150000: W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-08-15 07:22:31.150127: W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-08-15 07:22:31.150252: W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
done
```

**Comment by aselle** [comment]
Could you provide the exact configure command and a reproducible self contained test example?

**Comment by tbsflk** [comment]
I compile with the following cmake command:
```
> cmake .. -A x64 -DCMAKE_BUILD_TYPE=Release ^
More? -DSWIG_EXECUTABLE=C:/tf/swigwin-3.0.12/swig.exe ^
More? -DPYTHON_EXECUTABLE=C:/Anaconda/envs/tfc/python.exe ^
More? -DPYTHON_LIBRARIES=C:/Anaconda/envs/tfc/libs/python35.lib ^
More? -Dtensorflow_WIN_CPU_SIMD_OPTIONS=/arch:AVX
```
A reproducible self-contained test example is the code I provided at the beginning of my last post.

**Comment by angersson** [comment]
@mrry, can you take a look at this?

**Comment by mrry** [comment]
Nothing obvious springs to mind. There might be some issue in one of the Eigen kernels we use when building with MSVC.

Can you narrow the reproduction down further? In particular, it would be useful to know which op produces a different *output* in the two configurations. For example, to get the immediate inputs of the failing op, you could run the following code in both versions:

```python
op = tf.get_default_graph().get_operation_by_name("opt/gradients/node_label_update_1/Sum_grad/DynamicStitch")

for input_ in op.inputs:
  print(input, sess.run(input_, feed_dict={x: Xdata, y: Ydata}))
```

**Comment by tbsflk** [comment]
Sorry, but I don't have the environment around anymore, so I cannot make more tests. I just accepted that the compiled version didn't work at some point. Anyway, thanks for looking at it again!
