### ISSUE TITLE
Tensorboard AttributeError: 'SummaryMetadata' object has no attribute 'display_name'

### ISSUE THREAD

**Issue by ro3c** [tensorflow/tensorflow#12184]
### System information
- No custom code
- **OS: MaxOS Sierra 10.12.6
- **TensorFlow installed from (source or binary)**:
- **TensorFlow version (use command below)**: 1.2.1
- **Python version**: 3.6
- **Bazel version (if compiling from source)**: Build label: 0.5.3-homebrew
- **CUDA/cuDNN version**:
- **GPU model and memory**: 
- **Exact command to reproduce**: ./tensorboard --logdir=/Users/Pertis/Syncog-TF/SUD/logs/p1/summaries

You can collect some of this information using our environment capture script:

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

You can obtain the TensorFlow version with

python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

### Describe the problem
Tensorflow and Tensorboard built from source.
Tensorboard finds event files, but returns:
AttributeError: 'SummaryMetadata' object has no attribute 'display_name'
Tensorboard installed from prebuilt binaries runs without error

### Source code / logs
See stack trace below:
TensorBoard 0.1.3 at http://Rocs-iMac.fios-router.home:6006 (Press CTRL+C to quit) ^C
(tensorflow) Rocs-iMac:tensorboard Pertis$ ./tensorboard --logdir=/Users/Pertis/Syncog-TF/SUD/logs/p1/summaries
Exception in thread Reloader:
Traceback (most recent call last):
  File "/Users/Pertis/anaconda/envs/tensorflow/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Users/Pertis/anaconda/envs/tensorflow/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/private/var/tmp/_bazel_Pertis/77b889388121c5daae674df9c3cd82a3/execroot/org_tensorflow_tensorboard/bazel-out/darwin_x86_64-py3-fastbuild/bin/tensorboard/tensorboard.runfiles/org_tensorflow_tensorboard/tensorboard/backend/application.py", line 325, in _reload_forever
    reload_multiplexer(multiplexer, path_to_run)
  File "/private/var/tmp/_bazel_Pertis/77b889388121c5daae674df9c3cd82a3/execroot/org_tensorflow_tensorboard/bazel-out/darwin_x86_64-py3-fastbuild/bin/tensorboard/tensorboard.runfiles/org_tensorflow_tensorboard/tensorboard/backend/application.py", line 299, in reload_multiplexer
    multiplexer.Reload()
  File "/private/var/tmp/_bazel_Pertis/77b889388121c5daae674df9c3cd82a3/execroot/org_tensorflow_tensorboard/bazel-out/darwin_x86_64-py3-fastbuild/bin/tensorboard/tensorboard.runfiles/org_tensorflow_tensorboard/tensorboard/backend/event_processing/event_multiplexer.py", line 195, in Reload
    accumulator.Reload()
  File "/private/var/tmp/_bazel_Pertis/77b889388121c5daae674df9c3cd82a3/execroot/org_tensorflow_tensorboard/bazel-out/darwin_x86_64-py3-fastbuild/bin/tensorboard/tensorboard.runfiles/org_tensorflow_tensorboard/tensorboard/backend/event_processing/event_accumulator.py", line 209, in Reload
    self._ProcessEvent(event)
  File "/private/var/tmp/_bazel_Pertis/77b889388121c5daae674df9c3cd82a3/execroot/org_tensorflow_tensorboard/bazel-out/darwin_x86_64-py3-fastbuild/bin/tensorboard/tensorboard.runfiles/org_tensorflow_tensorboard/tensorboard/backend/event_processing/event_accumulator.py", line 355, in _ProcessEvent
    value = data_compat.migrate_value(value)
  File "/private/var/tmp/_bazel_Pertis/77b889388121c5daae674df9c3cd82a3/execroot/org_tensorflow_tensorboard/bazel-out/darwin_x86_64-py3-fastbuild/bin/tensorboard/tensorboard.runfiles/org_tensorflow_tensorboard/tensorboard/data_compat.py", line 53, in migrate_value
    return handler(value) if handler else value
  File "/private/var/tmp/_bazel_Pertis/77b889388121c5daae674df9c3cd82a3/execroot/org_tensorflow_tensorboard/bazel-out/darwin_x86_64-py3-fastbuild/bin/tensorboard/tensorboard.runfiles/org_tensorflow_tensorboard/tensorboard/data_compat.py", line 80, in _migrate_image_value
    display_name=value.metadata.display_name or value.tag,
AttributeError: 'SummaryMetadata' object has no attribute 'display_name'

**Comment by ro3c** [comment]
Thanks for the correction.

**Comment by mariru** [comment]
I couldn't find this same issue in the tensorboard issues and multiple searches have lead me here instead. Could you please post the link?

**Comment by chihuahua** [comment]
https://github.com/tensorflow/tensorboard/issues/404
Thank you for reporting.
