### ISSUE TITLE
an error occurred which is "No algorithm without scratch worked " when using tensorflow to train data

### ISSUE THREAD

**Issue by easonhuo** [tensorflow/tensorflow#12251]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.2.1-cp36-cp36m-linux_x86_64.whl
- **TensorFlow version (use command below)**:'1.2.1'
- **Python version**: 3.6.2
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:cuda-8.0/cudnn-5.1
- **GPU model and memory**:nvidia Tesla K80 /11G

### Describe the problem
when I use tensorflow to train my model, an error always occur when my my data size is larger than [250,250,250]. 

### this  is my code :

```
import tensorflow as tf
import numpy as np
n=250
x_train=np.arange(n*n*n).reshape([1,n,n,n,1])
y_train=np.zeros(n*n*n)
tf_x = tf.placeholder(tf.float32,[1,None,None,None,1])
tf_y = tf.placeholder(tf.int64,[None])
output=tf.layers.conv3d(tf_x,
                        filters=2,
                        kernel_size=(2,2,2),
                        strides=(1,1,1), 
                        padding="same",
                        activation=tf.nn.relu)

logits = tf.reshape(output, [-1, 2])
cross_entropy = tf.nn.sparse_softmax_cross_entropy_with_logits(logits=logits, labels=tf_y)
loss = tf.reduce_mean(cross_entropy)
train_step = tf.train.AdamOptimizer(1e-6).minimize(loss)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    sess.run(train_step,feed_dict={tf_x:x_train,tf_y:y_train})
    print(sess.run(loss,feed_dict={tf_x:x_train,tf_y:y_train}))
```

### This is the error I met:

```
`NotFoundError                             Traceback (most recent call last)
/data/conda/lib/python3.6/site-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1138     try:
-> 1139       return fn(*args)
   1140     except errors.OpError as e:

/data/conda/lib/python3.6/site-packages/tensorflow/python/client/session.py in _run_fn(session, feed_dict, fetch_list, target_list, options, run_metadata)
   1120                                  feed_dict, fetch_list, target_list,
-> 1121                                  status, run_metadata)
   1122 

/data/conda/lib/python3.6/contextlib.py in __exit__(self, type, value, traceback)
     87             try:
---> 88                 next(self.gen)
     89             except StopIteration:

/data/conda/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py in raise_exception_on_not_ok_status()
    465           compat.as_text(pywrap_tensorflow.TF_Message(status)),
--> 466           pywrap_tensorflow.TF_GetCode(status))
    467   finally:

NotFoundError: No algorithm without scratch worked!
	 [[Node: gradients_2/conv3d_3/convolution_grad/Conv3DBackpropInputV2 = Conv3DBackpropInputV2[T=DT_FLOAT, data_format="NDHWC", padding="SAME", strides=[1, 1, 1, 1, 1], _device="/job:localhost/replica:0/task:0/gpu:0"](gradients_2/conv3d_3/convolution_grad/Shape, conv3d_2/kernel/read, gradients_2/conv3d_3/BiasAdd_grad/tuple/control_dependency)]]

During handling of the above exception, another exception occurred:

NotFoundError                             Traceback (most recent call last)
<ipython-input-10-78d05b6135a4> in <module>()
     19 with tf.Session() as sess:
     20     sess.run(tf.global_variables_initializer())
---> 21     sess.run(train_step,feed_dict={tf_x:x_train,tf_y:y_train})
     22     print(sess.run(loss,feed_dict={tf_x:x_train,tf_y:y_train}))
     23 #     print(sess.run(loss,feed_dict={tf_x:x_train,tf_y:y_train}))

/data/conda/lib/python3.6/site-packages/tensorflow/python/client/session.py in run(self, fetches, feed_dict, options, run_metadata)
    787     try:
    788       result = self._run(None, fetches, feed_dict, options_ptr,
--> 789                          run_metadata_ptr)
    790       if run_metadata:
    791         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

/data/conda/lib/python3.6/site-packages/tensorflow/python/client/session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
    995     if final_fetches or final_targets:
    996       results = self._do_run(handle, final_targets, final_fetches,
--> 997                              feed_dict_string, options, run_metadata)
    998     else:
    999       results = []

/data/conda/lib/python3.6/site-packages/tensorflow/python/client/session.py in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1130     if handle is None:
   1131       return self._do_call(_run_fn, self._session, feed_dict, fetch_list,
-> 1132                            target_list, options, run_metadata)
   1133     else:
   1134       return self._do_call(_prun_fn, self._session, handle, feed_dict,

/data/conda/lib/python3.6/site-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1150         except KeyError:
   1151           pass
-> 1152       raise type(e)(node_def, op, message)
   1153 
   1154   def _extend_graph(self):

NotFoundError: No algorithm without scratch worked!
	 [[Node: gradients_2/conv3d_3/convolution_grad/Conv3DBackpropInputV2 = Conv3DBackpropInputV2[T=DT_FLOAT, data_format="NDHWC", padding="SAME", strides=[1, 1, 1, 1, 1], _device="/job:localhost/replica:0/task:0/gpu:0"](gradients_2/conv3d_3/convolution_grad/Shape, conv3d_2/kernel/read, gradients_2/conv3d_3/BiasAdd_grad/tuple/control_dependency)]]

Caused by op 'gradients_2/conv3d_3/convolution_grad/Conv3DBackpropInputV2', defined at:
  File "/data/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/data/conda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/conda/lib/python3.6/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/data/conda/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/data/conda/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 477, in start
    ioloop.IOLoop.instance().start()
  File "/data/conda/lib/python3.6/site-packages/zmq/eventloop/ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "/data/conda/lib/python3.6/site-packages/tornado/ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "/data/conda/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/data/conda/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "/data/conda/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/data/conda/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/data/conda/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/data/conda/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/data/conda/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 235, in dispatch_shell
    handler(stream, idents, msg)
  File "/data/conda/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/data/conda/lib/python3.6/site-packages/ipykernel/ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/data/conda/lib/python3.6/site-packages/ipykernel/zmqshell.py", line 533, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/data/conda/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2698, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/data/conda/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2802, in run_ast_nodes
    if self.run_code(code, result):
  File "/data/conda/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2862, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-10-78d05b6135a4>", line 18, in <module>
    train_step = tf.train.AdamOptimizer(1e-6).minimize(loss)
  File "/data/conda/lib/python3.6/site-packages/tensorflow/python/training/optimizer.py", line 315, in minimize
    grad_loss=grad_loss)
  File "/data/conda/lib/python3.6/site-packages/tensorflow/python/training/optimizer.py", line 386, in compute_gradients
    colocate_gradients_with_ops=colocate_gradients_with_ops)
  File "/data/conda/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 540, in gradients
    grad_scope, op, func_call, lambda: grad_fn(op, *out_grads))
  File "/data/conda/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 346, in _MaybeCompile
    return grad_fn()  # Exit early
  File "/data/conda/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 540, in <lambda>
    grad_scope, op, func_call, lambda: grad_fn(op, *out_grads))
  File "/data/conda/lib/python3.6/site-packages/tensorflow/python/ops/nn_grad.py", line 80, in _Conv3DGrad
    data_format=data_format),
  File "/data/conda/lib/python3.6/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 666, in conv3d_backprop_input_v2
    name=name)
  File "/data/conda/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/data/conda/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/data/conda/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

...which was originally created as op 'conv3d_3/convolution', defined at:
  File "/data/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
[elided 18 identical lines from previous traceback]
  File "/data/conda/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2862, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-10-78d05b6135a4>", line 13, in <module>
    activation=tf.nn.relu)
  File "/data/conda/lib/python3.6/site-packages/tensorflow/python/layers/convolutional.py", line 728, in conv3d
    return layer.apply(inputs)
  File "/data/conda/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 492, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "/data/conda/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 441, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/data/conda/lib/python3.6/site-packages/tensorflow/python/layers/convolutional.py", line 158, in call
    data_format=utils.convert_data_format(self.data_format, self.rank + 2))
  File "/data/conda/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 670, in convolution
    op=op)
  File "/data/conda/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 338, in with_space_to_batch
    return op(input, num_spatial_dims, padding)
  File "/data/conda/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 662, in op
    name=name)
  File "/data/conda/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 146, in _non_atrous_convolution
    name=name)
  File "/data/conda/lib/python3.6/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 526, in conv3d
    data_format=data_format, name=name)
  File "/data/conda/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)

NotFoundError (see above for traceback): No algorithm without scratch worked!
	 [[Node: gradients_2/conv3d_3/convolution_grad/Conv3DBackpropInputV2 = Conv3DBackpropInputV2[T=DT_FLOAT, data_format="NDHWC", padding="SAME", strides=[1, 1, 1, 1, 1], _device="/job:localhost/replica:0/task:0/gpu:0"](gradients_2/conv3d_3/convolution_grad/Shape, conv3d_2/kernel/read, gradients_2/conv3d_3/BiasAdd_grad/tuple/control_dependency)]]`
```

**Comment by skye** [comment]
This looks related to #9576. Perhaps you're out of GPU memory?

**Comment by tensorflowbutler** [comment]
This issue is automatically closed due to lack of activity. Please re-open if this is still an issue for you. Thanks!
