### ISSUE TITLE
tensorboard 0.1.1: No such file or directory: '/usr/local/lib/python3.4/dist-packages/tensorflow/tensorboard/TAG'

### ISSUE THREAD

**Issue by weiliu620** [tensorflow/tensorflow#12270]
Just upgrade to TF 1.3 and tensorboard 0.1.1 from Pypi. Ubuntu 14.04 64 bit and python 3.4. 

Running tensorboard gives me the following error: 
```
weiliu@roundvalley:~/projects/seismic$ tensorboard --logdir ./summay_2d
Traceback (most recent call last):
  File "/usr/local/bin/tensorboard", line 11, in <module>
    sys.exit(main())
  File "/home/weiliu/.local/lib/python3.4/site-packages/tensorboard/main.py", line 219, in main
    tb = create_tb_app(plugins)
  File "/home/weiliu/.local/lib/python3.4/site-packages/tensorboard/main.py", line 122, in create_tb_app
    plugins=plugins)
  File "/home/weiliu/.local/lib/python3.4/site-packages/tensorboard/backend/application.py", line 83, in standard_tensorboard_wsgi
    return TensorBoardWSGIApp(logdir, plugins, multiplexer, reload_interval)
  File "/home/weiliu/.local/lib/python3.4/site-packages/tensorboard/backend/application.py", line 121, in __init__
    self.tag = get_tensorboard_tag()
  File "/home/weiliu/.local/lib/python3.4/site-packages/tensorboard/backend/application.py", line 372, in get_tensorboard_tag
    tag = tf.resource_loader.load_resource('tensorboard/TAG').strip()
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/platform/resource_loader.py", line 50, in load_resource
    with open(path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.4/dist-packages/tensorflow/tensorboard/TAG'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 20, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 34, in <module>
    apt_pkg.init_config()
SystemError: E:Opening configuration file /etc/apt/apt.conf - ifstream::ifstream (13: Permission denied)

Original exception was:
Traceback (most recent call last):
  File "/usr/local/bin/tensorboard", line 11, in <module>
    sys.exit(main())
  File "/home/weiliu/.local/lib/python3.4/site-packages/tensorboard/main.py", line 219, in main
    tb = create_tb_app(plugins)
  File "/home/weiliu/.local/lib/python3.4/site-packages/tensorboard/main.py", line 122, in create_tb_app
    plugins=plugins)
  File "/home/weiliu/.local/lib/python3.4/site-packages/tensorboard/backend/application.py", line 83, in standard_tensorboard_wsgi
    return TensorBoardWSGIApp(logdir, plugins, multiplexer, reload_interval)
  File "/home/weiliu/.local/lib/python3.4/site-packages/tensorboard/backend/application.py", line 121, in __init__
    self.tag = get_tensorboard_tag()
  File "/home/weiliu/.local/lib/python3.4/site-packages/tensorboard/backend/application.py", line 372, in get_tensorboard_tag
    tag = tf.resource_loader.load_resource('tensorboard/TAG').strip()
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/platform/resource_loader.py", line 50, in load_resource
    with open(path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.4/dist-packages/tensorflow/tensorboard/TAG'
```

I checked `/usr/local/lib/python3.4/dist-packages/tensorflow/` and didn't find `tensorboard` folder there. 

Here is related `pip3 list` output: 
```
tensorflow-gpu (1.3.0rc2)
tensorflow-tensorboard (0.1.1)
``` 

EDIT: I realize this is more like a issue of Tensorboard than Tensorflow. Please feel free to move it to correct place if that helps solve it.

**Comment by weiliu620** [comment]
let me move it to Tensorboard .
