### ISSUE TITLE
freeze_graph giving decode error

### ISSUE THREAD

**Issue by eyaler** [tensorflow/tensorflow#12318]
i am using tensorflow_gpu-1.3.0rc2-cp36-cp36m-win_amd64.whl
running freeze_graph in python 3.6.2 on windows 10 64

Traceback (most recent call last):
  File "C:\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\tools\freeze_graph.py", line 260, in <module>
    app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\tools\freeze_graph.py", line 192, in main
    FLAGS.variable_names_blacklist)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\tools\freeze_graph.py", line 170, in freeze_graph
    input_graph_def = _parse_input_graph_proto(input_graph, input_binary)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\tools\freeze_graph.py", line 137, in _parse_input_graph_proto
    input_graph_def.ParseFromString(f.read())
  File "C:\Anaconda3\lib\site-packages\google\protobuf\message.py", line 185, in ParseFromString
    self.MergeFromString(serialized)
  File "C:\Anaconda3\lib\site-packages\google\protobuf\internal\python_message.py", line 1063, in MergeFromString
    if self._InternalParse(serialized, 0, length) != length:
  File "C:\Anaconda3\lib\site-packages\google\protobuf\internal\python_message.py", line 1099, in InternalParse
    pos = field_decoder(buffer, new_pos, end, self, field_dict)
  File "C:\Anaconda3\lib\site-packages\google\protobuf\internal\decoder.py", line 633, in DecodeField
    if value._InternalParse(buffer, pos, new_pos) != new_pos:
  File "C:\Anaconda3\lib\site-packages\google\protobuf\internal\python_message.py", line 1099, in InternalParse
    pos = field_decoder(buffer, new_pos, end, self, field_dict)
  File "C:\Anaconda3\lib\site-packages\google\protobuf\internal\decoder.py", line 612, in DecodeRepeatedField
    if value.add()._InternalParse(buffer, pos, new_pos) != new_pos:
  File "C:\Anaconda3\lib\site-packages\google\protobuf\internal\python_message.py", line 1099, in InternalParse
    pos = field_decoder(buffer, new_pos, end, self, field_dict)
  File "C:\Anaconda3\lib\site-packages\google\protobuf\internal\decoder.py", line 743, in DecodeMap
    if submsg._InternalParse(buffer, pos, new_pos) != new_pos:
  File "C:\Anaconda3\lib\site-packages\google\protobuf\internal\python_message.py", line 1089, in InternalParse
    new_pos = local_SkipField(buffer, new_pos, end, tag_bytes)
  File "C:\Anaconda3\lib\site-packages\google\protobuf\internal\decoder.py", line 850, in SkipField
    return WIRETYPE_TO_SKIPPER[wire_type](buffer, pos, end)
  File "C:\Anaconda3\lib\site-packages\google\protobuf\internal\decoder.py", line 799, in _SkipGroup
    new_pos = SkipField(buffer, pos, end, tag_bytes)
  File "C:\Anaconda3\lib\site-packages\google\protobuf\internal\decoder.py", line 850, in SkipField
    return WIRETYPE_TO_SKIPPER[wire_type](buffer, pos, end)
  File "C:\Anaconda3\lib\site-packages\google\protobuf\internal\decoder.py", line 814, in _SkipFixed32
    raise _DecodeError('Truncated message.')
google.protobuf.message.DecodeError: Truncated message.

**Comment by reedwm** [comment]
Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?  Make sure you also include the exact command if possible to produce  the output included in your test case. If you are unclear what to include  see the issue template displayed in  [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

 We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!

**Comment by eyaler** [comment]
my bad.
