### ISSUE TITLE
import tensorflow error with correct installation,  the problem  is "Couldn't find field google.protobuf.DescriptorProto.ExtensionRange.options"

### ISSUE THREAD

**Issue by jiandanjinxin** [tensorflow/tensorflow#12326]
Hi, everyone.

------------------------

### System information
Operating System: Ubuntu 16.04 LTS
Graphics card: Tesla K40
Installed version of CUDA: 8.0 
Installed version of cuDNN: v5 , for CUDA 8.0 
pip --version 9.0.1
pip 9.0.1 from /usr/local/lib/python2.7/dist-packages (python 2.7)

Tensorflow-gpu installed from pip
$sudo pip install tensorflow-gpu
Version: 1.2.1

----------------------------------------------------------------
pip version
Name: pip
Version: 9.0.1
Summary: The PyPA recommended tool for installing Python packages.
Home-page: https://pip.pypa.io/
Author: The pip developers
Author-email: python-virtualenv@groups.google.com
License: MIT
Location: /usr/local/lib/python2.7/dist-packages
Requires: 
--------------------------------
tensorboard version 

Name: tensorboard
Version: 1.0.0a6
Summary: Standalone TensorBoard for visualizing in deep learning
Home-page: https://github.com/dmlc/tensorboard
Author: zihaolucky
Author-email: zihaolucky@gmail.com
License: Apache 2.0
Location: /usr/local/lib/python2.7/dist-packages
Requires: mock, Pillow, numpy, protobuf, wheel, six, werkzeug
-------------------------------------------------------------
tensorflow-gpu version

Name: tensorflow-gpu
Version: 1.2.1
Summary: TensorFlow helps the tensors flow
Home-page: http://tensorflow.org/
Author: Google Inc.
Author-email: opensource@google.com
License: Apache 2.0
Location: /usr/local/lib/python2.7/dist-packages
Requires: mock, numpy, bleach, markdown, wheel, six, protobuf, backports.weakref, html5lib, werkzeug
---------------------------------------------------------

### The problem
When I open the terminal and type
$python
$import tensorflow 
I get

I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bids/.local/lib/python2.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/home/bids/.local/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 75, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/home/bids/.local/lib/python2.7/site-packages/tensorflow/core/framework/graph_pb2.py", line 10, in <module>
    from google.protobuf import descriptor_pb2
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/descriptor_pb2.py", line 409, in <module>
    options=None),
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/descriptor.py", line 501, in __new__
    return _message.default_pool.FindFieldByName(full_name)
KeyError: "Couldn't find field google.protobuf.DescriptorProto.ExtensionRange.options"

### Source code / logs
Before I upgrade the tensorboard and pip version(the default pip version is 8.x  in Ubuntu 16.04 LTS)
After that I type following code in the terminal 
$python /home/wcm/.local/lib/python2.7/site-packages/tensorboard/tensorboard.py --logdir='/tmp/log'
The problem is KeyError: "Couldn't find field google.protobuf.DescriptorProto.ExtensionRange.options"
Next, I type 
$ import tensorflow
The same problem is KeyError: "Couldn't find field google.protobuf.DescriptorProto.ExtensionRange.options".

Finally, I re-installing tensorflow-gpu, tensorflow and tensorboard step by step :no change. The same problem for import tensorflow.

 Anyone have an idea for this problem?
Thanks in advance
jiandanjinxin

**Comment by xuqingquan789** [comment]
The same problem,have you solved?

**Comment by xuqingquan789** [comment]
@jiandanjinxin  The same problem,have you solved?

**Comment by jimmycode** [comment]
@jiandanjinxin I got the same problem too. Could anyone solve it?

**Comment by WihanB** [comment]
@jiandanjinxin Same problem, was using TF 1.1 perfectly. Did a conventional pip3 install, now its broken.

**Comment by shaayaansayed** [comment]
Same issue. Was running 1.1, upgraded to 1.2 and received this error. Downgrading back to 1.1 did not fix it.

**Comment by reedwm** [comment]
I can't reproduce, but I'm running Ubuntu 14.04, not Ubuntu 16.04.

@jvrb, @jart, can you take a look at this issue?

**Comment by reedwm** [comment]
Whoops had a typo, meant to at-mention @jrvb

**Comment by WihanB** [comment]
I managed to fix this by forcing reinstall on pip.

Pip3 install tensorflow-gpu --upgrade --force-reinstall

**Comment by cauchyturing** [comment]
Here is a stupid and simple way... I delete my conda tensorflow env, create a new env and reinstall tensorflow-gpu==1.2.1, seems work fine. But should be better to wait for tensorflower to dig it in a standard way...

**Comment by khumbird** [comment]
I had a similar issue (could not find backports) and pip install tensorflow --upgrade --force-reinstall fixed the problem.

**Comment by jiandanjinxin** [comment]
@WihanB  @khumbird 
I check your method in the following procedure, it has another new problem.
$sudo pip3 install tensorflow-gpu --upgrade --force-reinstall
###Successfully installed tensorflow-gpu-1.3.0
-------------------------------------------------------------------------
$python3
Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609] on linux
$import tensorflow
###Another new problem comes out.

-------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /usr/local/lib/python3.5/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: cudnnConvolutionBiasActivationForward

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 52, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /usr/local/lib/python3.5/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: cudnnConvolutionBiasActivationForward


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

------------------------------------------------------------------
I guess the new problem from the version of tensorflow. Next, I try to check this method on python2.7
$pip install tensorflow-gpu --upgrade --force-reinstall
$python
$import tensorflow
###Another new problem on python2.7 is similar to the problem on python3.5
----------------------------------------------------------------------
ImportError: /usr/local/lib/python2.7/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: cudnnConvolutionBiasActivationForward


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
-------------------------------------------
pip show tensorflow-gpu
Name: tensorflow-gpu
Version: 1.3.0
Summary: TensorFlow helps the tensors flow
Home-page: http://tensorflow.org/
Author: Google Inc.
Author-email: opensource@google.com
License: Apache 2.0
Location: /usr/local/lib/python2.7/dist-packages
Requires: mock, numpy, backports.weakref, wheel, tensorflow-tensorboard, six, protobuf

--------------------------------------
Finally, I try the @cauchyturing 's method, it works on the python2.7 and python3.5, and the problem is fixed.
$ sudo pip uninstall tensorflow-gpu
$sudo pip install tensorflow-gpu==1.2.1
$python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
>>> import tensorflow

**Comment by jessyuan24** [comment]
I have same problem, Have anyone fixed this error?

**Comment by jessyuan24** [comment]
I fixed this error. first pip uninstall protobuf, then pip install protobuf==3.3.0.

**Comment by redfish-lee** [comment]
I got the error like this, 
```
>>> import tensorflow as tf
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 52, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: /usr/local/lib/python2.7/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: cudnnConvolutionBiasActivationForward
```
I just reinstall TensorFlow 1.3.0, and everthing works fine.
```
sudo pip uninstall tensorflow-gpu tensorflow
sudo pip install tensorflow-gpu
```

**Comment by OranginaGao** [comment]
`conda create -n <name_of_project> python=3.5 anaconda` to create a virtualenv and then `pip3 install tensorflow-gpu --upgrade --force-reinstall` fixed this issue.

**Comment by jirivrany** [comment]
Same issue on Centos 7 with Anaconda. Afer update to 
```
Python 3.6.2 |Anaconda custom (64-bit)| (default, Jul 20 2017, 13:51:32) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jiri.vrany/anaconda3/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/home/jiri.vrany/anaconda3/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/home/jiri.vrany/anaconda3/lib/python3.6/site-packages/tensorflow/core/framework/graph_pb2.py", line 10, in <module>
    from google.protobuf import descriptor_pb2
  File "/home/jiri.vrany/anaconda3/lib/python3.6/site-packages/google/protobuf/descriptor_pb2.py", line 409, in <module>
    options=None),
  File "/home/jiri.vrany/anaconda3/lib/python3.6/site-packages/google/protobuf/descriptor.py", line 501, in __new__
    return _message.default_pool.FindFieldByName(full_name)
KeyError: "Couldn't find field google.protobuf.DescriptorProto.ExtensionRange.options"
```
It was caused by mixing packages installed with conda and pip. Creating new conda env and install tensorflow-gpu fixed the issue.

**Comment by unnir** [comment]
Summarize :
pip uninstall tensorflow-gpu tensorflow
pip install tensorflow-gpu 
pip uninstall protobuf==3.3.0.
pip install protobuf==3.3.0.

it helped me.

**Comment by alexweng123** [comment]
pip uninstall protobuf
pip install protobuf==3.3.0
it works. maybe something wrong about the protobuf 3.5.0

**Comment by reedwm** [comment]
/CC @gunan do you know why the issue is occurring? Ideally we wouldn't require reinstalling protobuf as a workaround.

**Comment by gunan** [comment]
Looks like a possible protobuf issue: https://github.com/google/protobuf/issues/3631

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
A member of the TensorFlow organization has replied after the stat:awaiting tensorflower label was applied.

**Comment by drpngx** [comment]
Closing due to inactivity. Hopefully the new version doesn't exhibit that behavior.

**Comment by xjcl** [comment]
I've been trying to get [CSGNet](https://github.com/Hippogriff/CSGNet) to run using [conda](https://conda.io/) and keep getting this error. I've even installed Arch Linux to get the newest version and  it's still occurring.

**Comment by yogithesymbian** [comment]
same error
```
Exception has occurred: NotFoundError

/usr/local/lib/python3.8/dist-packages/tensorflow/core/kernels/libtfkernel_sobol_op.so: undefined symbol: _ZN10tensorflow8OpKernel11TraceStringEPNS_15OpKernelContextEb

  File "/root/AndroidStudioProjects/TensorFlowTflite/tensorflow_examples/lite/model_maker/yogi/makemodel.py", line 4, in <module>

    import tensorflow as tf
```
