### ISSUE TITLE
Error while running fully_connected_feed.py of the tutorial "TensorFlow Mechanics"

### ISSUE THREAD

**Issue by silvioFromItaly** [tensorflow/tensorflow#1236]
Hello, 

while running fully_connected_feed.py i had this error. I was trying the TensorFlow Mechanics 101 Tutorial

I attach the whole execution of the py file.

$ python3 fully_connected_feed.py 
Extracting data/train-images-idx3-ubyte.gz
Extracting data/train-labels-idx1-ubyte.gz
Extracting data/t10k-images-idx3-ubyte.gz
Extracting data/t10k-labels-idx1-ubyte.gz
Step 0: loss = 2.32 (0.010 sec)
Step 100: loss = 2.17 (0.005 sec)
Step 200: loss = 1.96 (0.004 sec)
Step 300: loss = 1.73 (0.004 sec)
Step 400: loss = 1.46 (0.004 sec)
Step 500: loss = 1.01 (0.005 sec)
Step 600: loss = 0.85 (0.009 sec)
Step 700: loss = 0.75 (0.004 sec)
Step 800: loss = 0.78 (0.004 sec)
Step 900: loss = 0.62 (0.004 sec)
Traceback (most recent call last):
  File "fully_connected_feed.py", line 228, in <module>
    tf.app.run()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/python/platform/default/_app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "fully_connected_feed.py", line 224, in main
    run_training()
  File "fully_connected_feed.py", line 199, in run_training
    saver.save(sess, FLAGS.train_dir, global_step=step)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 970, in save
    self.export_meta_graph(meta_graph_file_name)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 990, in export_meta_graph
    as_text=as_text)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1315, in export_meta_graph
    os.path.basename(filename), as_text=as_text)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/python/training/training_util.py", line 70, in write_graph
    gfile.MakeDirs(logdir)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/python/platform/default/_gfile.py", line 295, in MakeDirs
    os.makedirs(path, mode)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
FileNotFoundError: [Errno 2] No such file or directory: ''

My Operating System is OSX ElCapitan Upgrade. 
I installed tensorflow from pip package. 
The same error happens for both python2.7 and python3.5

Thanks a lot in advance for your help.

Silvio

**Comment by vrv** [comment]
This is fixed in 0.7.1, which we will release soon.

**Comment by vrv** [comment]
We just released 0.7.1 -- let us know if it still happens there.
