### ISSUE TITLE
CrashLoopBackOff

### ISSUE THREAD

**Issue by chakpongchung** [tensorflow/tensorflow#12368]
I am trying to follow the tensorflow deployment on kubernetes following the tutorial here:
https://www.tensorflow.org/serving/serving_inception#part_2_deploy_in_kubernetes

Instead of running on gclound, I am trying to run on local machine. But I ran into the following problem.

pangolins:serving$ kubectl get pods
NAME                                    READY     STATUS             RESTARTS   AGE
inception-deployment-2217120516-jmkbm   0/1       CrashLoopBackOff   9          31m
inception-deployment-2217120516-rr04x   0/1       CrashLoopBackOff   9          31m
inception-deployment-2217120516-xvc58   0/1       CrashLoopBackOff   9          31m
monolith                                1/1       Running            0          1d
nginx-1803751077-5cst4                  1/1       Running            0          2d

pangolins:serving$ bazel-bin/tensorflow_serving/example/inception_client --server=10.0.0.45:32683 --image=./tensorflow/tensorflow/contrib/pi_examples/label_image/data/grace_hopper.jpg
Traceback (most recent call last):
  File "/home/pangolins/software/serving/bazel-bin/tensorflow_serving/example/inception_client.runfiles/tf_serving/tensorflow_serving/example/inception_client.py", line 56, in <module>
    tf.app.run()
  File "/home/pangolins/software/serving/bazel-bin/tensorflow_serving/example/inception_client.runfiles/org_tensorflow/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/pangolins/software/serving/bazel-bin/tensorflow_serving/example/inception_client.runfiles/tf_serving/tensorflow_serving/example/inception_client.py", line 51, in main
    result = stub.Predict(request, 10.0)  # 10 secs timeout
  File "/home/pangolins/anaconda2/lib/python2.7/site-packages/grpc/beta/_client_adaptations.py", line 324, in __call__
    self._request_serializer, self._response_deserializer)
  File "/home/pangolins/anaconda2/lib/python2.7/site-packages/grpc/beta/_client_adaptations.py", line 210, in _blocking_unary_unary
    raise _abortion_error(rpc_error_call)
grpc.framework.interfaces.face.face.AbortionError: AbortionError(code=StatusCode.UNAVAILABLE, details="Connect Failed")

**Comment by reedwm** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
