### ISSUE TITLE
[Bug] bazel test kernel_tests:scatter_ops_test on master branch, got ImportError: No module named autograd.

### ISSUE THREAD

**Issue by nolanliou** [tensorflow/tensorflow#12422]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
ubuntu 16.04
- **TensorFlow installed from (source or binary)**:
source
- **TensorFlow version (use command below)**:
master
- **Python version**:
2.7 
- **Bazel version (if compiling from source)**:
0.4.5
- **CUDA/cuDNN version**:
8.0/5.1.10
- **GPU model and memory**:
M40
- **Exact command to reproduce**:
bazel test -c opt --verbose_failures //tensorflow/python/kernel_tests:scatter_ops_test

### Describe the problem
I have clone the source and run kernel test with the  above command, got following error.
```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1                                     
-----------------------------------------------------------------------------   
Traceback (most recent call last):                                              
  File "/root/.cache/bazel/_bazel_root/0ccdc6677c64d2c9b51856e8acbdd6d3/execroot/tensorflow/bazel-out/local_linux-opt/bin/tensorflow/python/kernel_tests/scatter_ops_test.runfiles/org_tensorflow/tensorflow/python/kernel_tests/scatter_ops_test.py", line 23, in <module>
    from tensorflow.python.framework import constant_op                         
  File "/root/.cache/bazel/_bazel_root/0ccdc6677c64d2c9b51856e8acbdd6d3/execroot/tensorflow/bazel-out/local_linux-opt/bin/tensorflow/python/kernel_tests/scatter_ops_test.runfiles/org_tensorflow/tensorflow/python/framework/constant_op.py", line 48, in <module>
    from tensorflow.python.eager import execute                                 
  File "/root/.cache/bazel/_bazel_root/0ccdc6677c64d2c9b51856e8acbdd6d3/execroot/tensorflow/bazel-out/local_linux-opt/bin/tensorflow/python/kernel_tests/scatter_ops_test.runfiles/org_tensorflow/tensorflow/python/eager/execute.py", line 21, in <module>
    from autograd import core as ag_core                                        
ImportError: No module named autograd
```

Then, I check out  branch v1.3, it is ok.

**Comment by reedwm** [comment]
Try running
```
sudo pip install autograd
```
Building TensorFlow now requires autograd. When I ran the command it above on Ubuntu 14.04, it gave an error about requiring a Fortran compiler, which I installed with
```
sudo apt-get install gfortran
```

@alextp can you add the autograd dependency under the "Prepare environment for Linux" section in the [Installing TensorFlow from Sources](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/docs_src/install/install_sources.md) guide? autograd is currently only listed on the "Prepare environment for Mac OS" section.

**Comment by nolanliou** [comment]
@reedwm It works, thanks.
