### ISSUE TITLE
Tensorflow GPU import causes exeptions [Resolved]

### ISSUE THREAD

**Issue by PsyWhat** [tensorflow/tensorflow#12437]
There is a problem occures when I import tensorflow.

> 
> "C:\Program Files\Python35\python.exe" D:/NetDisks/DropBox/Dropbox/Develop/Python/TensorFlow/GPUTest.py
> Traceback (most recent call last):
>   File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_import_helper
>     return importlib.import_module(mname)
>   File "C:\Program Files\Python35\lib\importlib\__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 986, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 577, in module_from_spec
>   File "<frozen importlib._bootstrap_external>", line 906, in create_module
>   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
> ImportError: DLL load failed: Не найден указанный модуль.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 41, in <module>
>     from tensorflow.python.pywrap_tensorflow_internal import *
>   File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 21, in <module>
>     _pywrap_tensorflow_internal = swig_import_helper()
>   File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 20, in swig_import_helper
>     return importlib.import_module('_pywrap_tensorflow_internal')
>   File "C:\Program Files\Python35\lib\importlib\__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
> ImportError: No module named '_pywrap_tensorflow_internal'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "D:/NetDisks/DropBox/Dropbox/Develop/Python/TensorFlow/GPUTest.py", line 1, in <module>
>     import tensorflow as tf
>   File "C:\Program Files\Python35\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
>     from tensorflow.python import *
>   File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
>     from tensorflow.python import pywrap_tensorflow
>   File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 52, in <module>
>     raise ImportError(msg)
> ImportError: Traceback (most recent call last):
>   File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_import_helper
>     return importlib.import_module(mname)
>   File "C:\Program Files\Python35\lib\importlib\__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 986, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 577, in module_from_spec
>   File "<frozen importlib._bootstrap_external>", line 906, in create_module
>   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
> ImportError: DLL load failed: Не найден указанный модуль.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 41, in <module>
>     from tensorflow.python.pywrap_tensorflow_internal import *
>   File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 21, in <module>
>     _pywrap_tensorflow_internal = swig_import_helper()
>   File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 20, in swig_import_helper
>     return importlib.import_module('_pywrap_tensorflow_internal')
>   File "C:\Program Files\Python35\lib\importlib\__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
> ImportError: No module named '_pywrap_tensorflow_internal'
> 
> 
> Failed to load the native TensorFlow runtime.
> 
> See https://www.tensorflow.org/install/install_sources#common_installation_problems
> 
> for some common reasons and solutions.  Include the entire stack trace
> above this error message when asking for help.
> 
> Process finished with exit code 1
> 
> 

Windows 7 x64 SP1

CPU: Intel Core I7 990x
Motherboard: Asus P6T SE
GPU: GTX 1080 TI

tensorflow have been installed with native PIP, command: 

> pip install tensorflow-gpu

Python 3.5.2

CUDA 8.0 Toolkit

CUDNN 5.1

The code is:
`import tensorflow as tf`

Path:

> C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin;
> C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\libnvvp;
> C:\Program Files\Python35\Scripts\;
> C:\Program Files\Python35\;
> C:\Program Files\Microsoft MPI\Bin\;
> C:\Windows\;
> C:\Windows\System32;
> C:\Program Files\dotnet\;
> C:\Program Files\Anaconda3;
> C:\Program Files\Anaconda3\Scripts;
> C:\Program Files\Anaconda3\Library\bin;
> C:\Program Files\Anaconda2;
> C:\Program Files\Anaconda2\Scripts;
> C:\Program Files\Anaconda2\Library\bin;
> C:\Program Files (x86)\Anaconda3;
> C:\Program Files (x86)\Anaconda3\Scripts;
> C:\Program Files (x86)\Anaconda3\Library\bin;
> C:\Program Files (x86)\Anaconda2;
> C:\Program Files (x86)\Anaconda2\Scripts;
> C:\Program Files (x86)\Anaconda2\Library\bin;
> C:\Program Files\NVIDIA Corporation\cuda\bin;
> C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;
> C:\Program Files\NVIDIA Corporation\cuda\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin;
> C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0;
> C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\lib\x64;
> C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\extras\CUPTI\libx64;

CUDA_HOME

> C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0

CUDA_PATH

> C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0

CUDA_PATH_V8_0

> C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0

MSVC++ 2015 x64 is installed

cudnn64_5.dll is located at:
> C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin

Also if i install a regular tensorflow, it works OK.

How do I deal with/fix this?

**Comment by PsyWhat** [comment]
Newermind, I was using TF 1.3, whinch is using CUDNN 6.0
