### ISSUE TITLE
Installation failure on Windows 10

### ISSUE THREAD

**Issue by robmorh** [tensorflow/tensorflow#12442]
Hi,

i'm having trouble installing tensorflow. It already worked and evereything was fine when i changed cuDNN to 6.0 for something else.
But now, even after installing everything from the drivers of the gpu, to CUDA and cudnn5.1 new, tensorflow installation is failing. I am always getting this error, but every solution i found in other issues with similar errors is not working.
All the pathes are set correct. Anyone has an idea?

`>>> import tensorflow as tf
Traceback (most recent call last):
  File "C:\Users\rkoch\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\pywrap_tenso
rflow_internal.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Users\rkoch\AppData\Local\Programs\Python\Python35\lib\importlib\__init__.py", line 126, in import_
module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 985, in _gcd_import
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 577, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 938, in create_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\rkoch\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\pywrap_tenso
rflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\rkoch\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\pywrap_tenso
rflow_internal.py", line 21, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\rkoch\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\pywrap_tenso
rflow_internal.py", line 20, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow_internal')
  File "C:\Users\rkoch\AppData\Local\Programs\Python\Python35\lib\importlib\__init__.py", line 126, in import_
module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\rkoch\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\__init__.py", line
24, in <module>
    from tensorflow.python import *
  File "C:\Users\rkoch\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\__init__.py"
, line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\rkoch\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\pywrap_tenso
rflow.py", line 52, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\rkoch\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\pywrap_tenso
rflow_internal.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Users\rkoch\AppData\Local\Programs\Python\Python35\lib\importlib\__init__.py", line 126, in import_
  File "C:\Users\rkoch\AppData\Local\Programs\Python\Python35\lib\site-pac
kages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "C:\Users\rkoch\AppData\Local\Programs\Python\Python35\lib\site-pac
kages\tensorflow\python\__init__.py", line 49, in <module>                ed
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\rkoch\AppData\Local\Programs\Python\Python35\lib\site-pac
kages\tensorflow\python\pywrap_tensorflow.py", line 52, in <module>       e
    raise ImportError(msg)                                                oved
ImportError: Traceback (most recent call last):
  File "C:\Users\rkoch\AppData\Local\Programs\Python\Python35\lib\site-pac
kages\tensorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_i
mport_helper
    return importlib.import_module(mname)
  File "C:\Users\rkoch\AppData\Local\Programs\Python\Python35\lib\importlikages\tensorflow\python\pywrap_tenso
b\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 985, in _gcd_import          kages\tensorflow\python\pywrap_tenso
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlock
ed                                                                        kages\tensorflow\python\pywrap_tenso
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 577, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 938, in create_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\rkoch\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\rkoch\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 21, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\rkoch\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 20, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow_internal')
  File "C:\Users\rkoch\AppData\Local\Programs\Python\Python35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: No module named '_pywrap_tensorflow_internal'

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help`

**Comment by jubjamie** [comment]
What version of Tensorflow please?

I see you are trying to install on Windows, @mrry has a great installation troubleshooter script that can help pinpoint issues available here: [mrry's Self-check Script](https://gist.github.com/mrry/ee5dbcfdd045fa48a27d56664411d41c)

**Comment by estyrke** [comment]
It seems the current tensorflow build referenced from https://www.tensorflow.org/install/install_windows actually requires CuDNN 6.0 instead of CuDNN 5.1 as the text specifies.

Apparently the installation instructions are out of sync with the install package.

**Comment by robmorh** [comment]
Yes thank you @jubjamie this helped me a lot.
The install instructions are outdated and thus i had installed the wrong cudnn.

Now it works fine again.

**Comment by jubjamie** [comment]
Feel free to register your concern on #11784 I've been trying to get this fixed as you're not the first to have this issue with the installation docs.
