### ISSUE TITLE
AttributeError: 'int' object attribute '__doc__' is read-only

### ISSUE THREAD

**Issue by DavidNorman** [tensorflow/tensorflow#12491]
In the file `tensorflow/compiler/tests/adagrad_test_poplar.runfiles/org_tensorflow/tensorflow/python/ops/variable_scope.py", line 191`, I have an error when trying to run unit tests.

Python is unhappy with trying to assign to __doc__.

This is on OS/X, with a virtualenv containing all of the modules required for the head of master on 22nd August 2017.

I have had to add `autograd` and `enum`, and as a consequence of the OS/X built-in numpy, I have switched to building tensorflow in a virtualenv.

**Comment by yongtang** [comment]
I encountered a similar issue in Ubuntu 16.04 with python 2.7. Addressed the issue by installing `python-enum34` package which has the enum34 backport.

**Comment by andydavis1** [comment]
Please re-open if the above-mentioned work around does not solve your issue...

**Comment by MrShaham** [comment]
Hi
i face the same problem when i try 

:~/tensorflow$ bazel-bin/tensorflow/examples/image_retraining/retrain --image_dir ~/flower_photos

after enter above line in terminal, the out put is 

Traceback (most recent call last):
  File "/home/sam/tensorflow/bazel-bin/tensorflow/examples/image_retraining/retrain.runfiles/org_tensorflow/tensorflow/examples/image_retraining/retrain.py", line 108, in <module>
    import tensorflow as tf
  File "/home/sam/tensorflow/bazel-bin/tensorflow/examples/image_retraining/retrain.runfiles/org_tensorflow/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/home/sam/tensorflow/bazel-bin/tensorflow/examples/image_retraining/retrain.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 63, in <module>
    from tensorflow.python.framework.framework_lib import *
  File "/home/sam/tensorflow/bazel-bin/tensorflow/examples/image_retraining/retrain.runfiles/org_tensorflow/tensorflow/python/framework/framework_lib.py", line 102, in <module>
    from tensorflow.python.framework.importer import import_graph_def
  File "/home/sam/tensorflow/bazel-bin/tensorflow/examples/image_retraining/retrain.runfiles/org_tensorflow/tensorflow/python/framework/importer.py", line 30, in <module>
    from tensorflow.python.framework import function
  File "/home/sam/tensorflow/bazel-bin/tensorflow/examples/image_retraining/retrain.runfiles/org_tensorflow/tensorflow/python/framework/function.py", line 34, in <module>
    from tensorflow.python.ops import variable_scope as vs
  File "/home/sam/tensorflow/bazel-bin/tensorflow/examples/image_retraining/retrain.runfiles/org_tensorflow/tensorflow/python/ops/variable_scope.py", line 192, in <module>
    """
AttributeError: 'int' object attribute '__doc__' is read-only

I already install autograd and enum and python-enum34  but problem still there.

**Comment by jzharris** [comment]
I had the same result as you after installing `python-enum34` in Ubuntu 16.04 with python 2.7. I had to run the following steps at this point to get back on track:
`pip uninstall enum`
`pip install mock`

**Comment by leonmak** [comment]
fyi `pip install enum34` for mac solves it for me

**Comment by linuxjain** [comment]
I had same issue on mac, @leonmak suggestion worked for me.

**Comment by ly54mm** [comment]
I had same issue on mac with recent updated version, however, leonmak suggestion didn't work for me. (no issue with previous version.)

**Comment by MrShaham** [comment]
@leonmak  sorry for late reply. I've been busy with my studies. This method not for me either . i take different rote for achieving my goal. i upload my work as soon as possible.

**Comment by wenguanwang** [comment]
Uninstall enum and intall enum34.

**Comment by bringtree** [comment]
@wenguanwang  when i uninstall enum. it throws the error about. I had been installed enum34. 
```
ImportError: No module named enum
```

**Comment by changwuxie** [comment]
i had same issue on centos7,@leonmak suggestion worked for me.

**Comment by AllenYLJiang** [comment]
conda install enum34

**Comment by bruce1408** [comment]
> Uninstall enum and intall enum34.

this is the right answer,thx!
