### ISSUE TITLE
Tensorflow Debugger crashes on tab complete

### ISSUE THREAD

**Issue by alanhdu** [tensorflow/tensorflow#12500]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: Binary (pip wheel)
- **TensorFlow version (use command below)**: 1.3
- **Python version**:  3.5
- **GPU model and memory**: (CPU only)

### Describe the problem
Sometimes when using `tfdbg`, tab-completing on `pt` will crash the debugger (unfortunately, I haven't figured out how to reproduce this consistently yet) and my terminal will look like:

![screenshot from 2017-08-22 14-44-11](https://user-images.githubusercontent.com/1914111/29582837-2a0cd4d8-874c-11e7-899d-8430575ce1ba.png)

the terminal will be unresponsive, and scrolling + regular mouse selection will be disabled (although `SHIFT` + mouse selection will work).

### Source code / logs

Reconstructing the traceback:

```
Traceback (most recent call last):
File "GenerativeLSTM.py", line 151, in <module>
    m.train(klabels, config={"epochs": 30, "batch_size": 1})
File "GenerativeLSTM.py", line 140, in train
    [next_batch, (train_step, merged)], feed_dict)
File "/home/alan/workspace/cognescent/py3.venv/lib/python3.5/site-packages/tensorflow/python/debug/wrappers/framework.py", line 532, in run
    run_end_resp = self.on_run_end(run_end_req)
File "/home/alan/workspace/cognescent/py3.venv/lib/python3.5/site-packages/tensorflow/python/debug/wrappers/local_cli_wrapper.py", line 338, in on_run_end
    self._run_start_response = self._launch_cli()
File "/home/alan/workspace/cognescent/py3.venv/lib/python3.5/site-packages/tensorflow/python/debug/wrappers/local_cli_wrapper.py", line 429, in _launch_cli
        title_color=self._title_color)
File "/home/alan/workspace/cognescent/py3.venv/lib/python3.5/site-packages/tensorflow/python/debug/cli/curses_ui.py", line 502, in run_ui
    exit_token = self._ui_loop()
File "/home/alan/workspace/cognescent/py3.venv/lib/python3.5/site-packages/tensorflow/python/debug/cli/curses_ui.py", line 578, in _ui_loop
    tab_completed = self._tab_complete(command)
File "/home/alan/workspace/cognescent/py3.venv/lib/python3.5/site-packages/tensorflow/python/debug/cli/curses_ui.py", line 1507, in _tab_complete
    self._display_candidates(candidates)
File "/home/alan/workspace/cognescent/py3.venv/lib/python3.5/site-packages/tensorflow/python/debug/cli/curses_ui.py", line 1554, in _display_candidates
    pad, _, _ = self._display_lines(candidates_output, 0)
File "/home/alan/workspace/cognescent/py3.venv/lib/python3.5/site-packages/tensorflow/python/debug/cli/curses_ui.py", line 1130, in _display_lines
    pad = self._screen_new_output_pad(rows, cols)
File "/home/alan/workspace/cognescent/py3.venv/lib/python3.5/site-packages/tensorflow/python/debug/cli/curses_ui.py", line 978, in _screen_new_output_pad
    return curses.newpad(rows, cols)
_curses.error: curses function returned NULL
```

As I said, I unfortunately have not figured out how to reproduce this regularly -- this happens every once in a while when I'm working on the LSTM from #12465. I'll try to create a minimal reproducible test case later, but I figured I'd file this ticket first.

**Comment by caisq** [comment]
Sorry for the inconvenience, @alanhdu . Given a fixed screen size, is this reproducible? What happens if you slightly change the screen width?

**Comment by alanhdu** [comment]
I've always run `tfdbg` with a maximized window, but even then this doesn't happen all the time.

Changing the screen width doesn't seem to do anything (in general, `tfdbg` doesn't really resize when I resize my window).

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @caisq: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by caisq** [comment]
I can't reproduce this bug. Closing it. Feel free to re-open if someone sees the bug again.
