### ISSUE TITLE
import tensorflow failed with 0.7.1 pip package

### ISSUE THREAD

**Issue by JianbangZ** [tensorflow/tensorflow#1254]
### Environment info
Operating System: Ubuntu 14.04

If installed from binary pip package, provide:

1. Which pip package you installed.
I flollowed: sudo pip install --upgrade https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.7.1-cp27-none-linux_x86_64.whl

2. The output from python -c "import tensorflow ".
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 41, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 35, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/core/framework/graph_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
ImportError: No module named protobuf

Error importing tensorflow.  Unless you are using bazel,
you should not try to import tensorflow from its source directory;
please exit the tensorflow source tree, and relaunch your python interpreter

### What have you tried?
1. I reinstall the old 0.6.0 pip package, everything works
2. I installed 0.7.1 cpu only version, it still doesn't work
3. I upgrade cuda & cudnn to 7.5 &v4, it still doesn't work

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

**Comment by JianbangZ** [comment]
Sorry I just found a dup with #1180. Will close this for now

**Comment by zkl99999** [comment]
，，，  --upgrade？？？
