### ISSUE TITLE
Error: tensorflow.python.framework.errors_impl.InternalError: Unable to get element from the feed as bytes.

### ISSUE THREAD

**Issue by luckynote** [tensorflow/tensorflow#12591]
I have met this error:

> Traceback (most recent call last):
  File "demo_pb.py", line 25, in <module>
    result_dict = news_demo.newsAggreg({image_path})
  File "/home/rszj/liutao/news_aggreg/news_demo_pb.py", line 32, in newsAggreg
    predict = news_predict.run(images_path)
  File "/home/rszj/liutao/news_aggreg/news_predict_pb.py", line 201, in run
    predict = sess.run(pred, feed_dict={x: imgs, is_train:False})
  File "/home/rszj/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/home/rszj/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/home/rszj/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/home/rszj/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Unable to get element from the feed as bytes.

Background: 
    Firstly, I have a simple cnn program, and I build a model.ckpt files. 
    Secondly, I make be ckpt converting to pb.
    Thridly, I used ckpt model doing predict and pb model doing predict.
    In simple cnn program, ckpt and pb all do normal predict by using `predict = sess.run(pred, feed_dict={x: imgs, is_train:False})` .
   
   However, when I using upper method to cnn-rnn program, I could have a normal predict result using ckpt model file, but it had a `tensorflow.python.framework.errors_impl.InternalError: Unable to get element from the feed as bytes.` problem using pb.
   I can't solve this problem, I need help!
  Please!
  Thanks!

**Comment by andydavis1** [comment]
Please fill out the template, and send a reproducible test case.
