### ISSUE TITLE
cpu version Installed successfully, but cannot import tensorflow in python.

### ISSUE THREAD

**Issue by MassD** [tensorflow/tensorflow#126]
My env is like this:

```
Red Hat Enterprise Linux Server release 5.5 (Tikanga)

python 2.7.3
```

I successfully installed tensorflow, using `pip install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.5.0-cp27-none-linux_x86_64.whl`

then I goes into `python`, then `import tensorflow as trf`, I got this error:

```

$ python
Python 2.7.3 (default, Nov  1 2013, 09:47:57) 
[GCC 4.1.2 20080704 (Red Hat 4.1.2-48)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/users/jackson/pyenvs/tensorflow/lib/python2.7/site-packages/tensorflow/__init__.py", line 4, in <module>
    from tensorflow.python import *
  File "/users/jackson/pyenvs/tensorflow/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 22, in <module>
    from tensorflow.python.client.client_lib import *
  File "/users/jackson/pyenvs/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/client_lib.py", line 35, in <module>
    from tensorflow.python.client.session import InteractiveSession
  File "/users/jackson/pyenvs/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 11, in <module>
    from tensorflow.python import pywrap_tensorflow as tf_session
  File "/users/jackson/pyenvs/tensorflow/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/users/jackson/pyenvs/tensorflow/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
ImportError: /users/jackson/pyenvs/tensorflow/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so: ELF file OS ABI invalid


```

Can I get some help on this pls?

**Comment by yyttr3** [comment]
Can you echo me the outputs of:
1.) uname -a
2.) rpm -qa | grep glibc
3.) ldd --version

**Comment by ebrevdo** [comment]
Tensorflow pip packages were compiled on Ubuntu machines. Can you try building the pip package from source and installing it?

**Comment by MassD** [comment]
did pip packages from source, worked. thanks

**Comment by 2smoothformost33** [comment]
Yes ty

george

**Comment by constzi** [comment]
hi guys, can you tell me how I can " build the pip package from source and install it" in windows?

So far I did: 
pip2.7.exe install https://storage.googleapis.com/tensorflow/mac/tensorflow-0.5.0-py2-none-any.whl

and got the following error when I run a program with "import tensorflow":
ImportError: No module named _pywrap_tensorflow

Thanks ahead!
