### ISSUE TITLE
gather_nd bounds checking not working

### ISSUE THREAD

**Issue by Timeroot** [tensorflow/tensorflow#12608]
When using `gather_nd`, sometimes out-of-bounds `indices` lead to errors (bounds checking -- the expected behavior) and sometimes it seems to just read zeros. I expect it reading just other memory from the GPU, but I've never observed anything _other_ than zeros so I'm not sure. When I run on the CPU the bounds seem to be appropriately checked i.e. I get the errors desired. Here's some example code:

```python
import tensorflow as tf
sess = tf.Session()
print(sess.run(tf.gather_nd(tf.zeros([5,5,5]) + 1, [[6,6,6]])))
print(sess.run(tf.gather_nd(tf.zeros([1,5]) + 1, [-50000000000000000])))
print(sess.run(tf.gather_nd(tf.reshape(tf.range(5*5*5), [5,5,5]), [[6,6,6]])))
```

The first two print statements execute successfully, which is a bug: the indices are clearly out of range, and the arrays are clearly all 1's; but instead it returns an appropriately shaped array of 0's. (The +1 is not necessary to trigger the bug, but highlights that it's drawing from incorrect memory). The third line, for some reason, has the bounds checking operate correctly, and says that -- yes -- the index [6,6,6] is not in the bounds. It appears to something based on what the previous op is, _maybe_? Where some ops, such as `stack`, allow me to go outside the bounds, while others such as `reshape` don't. Here's an example interactive session to show the output I get.

```python
Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> sess = tf.Session()
2017-08-25 17:10:43.788433: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-08-25 17:10:43.788455: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-08-25 17:10:43.788463: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-08-25 17:10:43.788466: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-08-25 17:10:43.788470: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
2017-08-25 17:10:43.919384: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:893] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2017-08-25 17:10:43.919779: I tensorflow/core/common_runtime/gpu/gpu_device.cc:955] Found device 0 with properties: 
name: GeForce GTX 1070
major: 6 minor: 1 memoryClockRate (GHz) 1.645
pciBusID 0000:01:00.0
Total memory: 7.92GiB
Free memory: 7.59GiB
2017-08-25 17:10:43.919795: I tensorflow/core/common_runtime/gpu/gpu_device.cc:976] DMA: 0 
2017-08-25 17:10:43.919801: I tensorflow/core/common_runtime/gpu/gpu_device.cc:986] 0:   Y 
2017-08-25 17:10:43.919814: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1045] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1070, pci bus id: 0000:01:00.0)
>>> sess.run(tf.gather_nd(tf.zeros([5,5,5]) + 1, [[6,6,6]]))
array([ 0.], dtype=float32)
>>> sess.run(tf.gather_nd(tf.zeros([1,5]) + 1, [-50000000000000000]))
array([ 0.,  0.,  0.,  0.,  0.], dtype=float32)
>>> sess.run(tf.gather_nd(tf.reshape(tf.range(5*5*5), [5,5,5]), [[6,6,6]]))
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1327, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1306, in _run_fn
    status, run_metadata)
  File "/usr/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: flat indices[0, :] = [6, 6, 6] does not index into param (shape: [5,5,5]).
	 [[Node: GatherNd_2 = GatherNd[Tindices=DT_INT32, Tparams=DT_INT32, _device="/job:localhost/replica:0/task:0/cpu:0"](Reshape/_7, GatherNd_2/indices)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: flat indices[0, :] = [6, 6, 6] does not index into param (shape: [5,5,5]).
	 [[Node: GatherNd_2 = GatherNd[Tindices=DT_INT32, Tparams=DT_INT32, _device="/job:localhost/replica:0/task:0/cpu:0"](Reshape/_7, GatherNd_2/indices)]]

Caused by op 'GatherNd_2', defined at:
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 1338, in gather_nd
    name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): flat indices[0, :] = [6, 6, 6] does not index into param (shape: [5,5,5]).
	 [[Node: GatherNd_2 = GatherNd[Tindices=DT_INT32, Tparams=DT_INT32, _device="/job:localhost/replica:0/task:0/cpu:0"](Reshape/_7, GatherNd_2/indices)]]
```

Version info:
Linux Mint 4.4.0-53-generic x86_64
Python version 3.5.2
CUDA version release 8.0, V8.0.61
cuDNN version 6.0.21
Tensorflow version v1.3.0-rc2-20-g0787eee 1.3.0
nvidia drivers version 375

**Comment by ppwwyyxx** [comment]
Related: #12405

**Comment by ali01** [comment]
@langmore, are you able to take a look?

**Comment by langmore** [comment]
Any array bounds checking issues would involve digging into the C++, or maybe even the GPU kernel.  That's beyond what I can do.

**Comment by Timeroot** [comment]
It looks like relevant bounds-checking code for the CPU is in https://github.com/tensorflow/tensorflow/blob/dff1062bbf53cd8890d8d43ea815c90ba4555ba4/tensorflow/core/kernels/gather_nd_op_cpu_impl.h#L57 The 'out_of_bounds' variable gets stored in 'error_loc' and then passed out as 'bad_i' in https://github.com/tensorflow/tensorflow/blob/e073322452e41e76754314aa75d543d071003fc5/tensorflow/core/kernels/gather_nd_op.cc#L126

But based on L144 in gather_nd_op.cc, it seems that the GPU kernel is currently not designed to do the bounds checking.

https://github.com/tensorflow/tensorflow/blob/e073322452e41e76754314aa75d543d071003fc5/tensorflow/core/kernels/gather_nd_op_gpu.cu.cc#L56 shows that it deliberately returns an all-zero tensors when the bounds check fails, but doesn't report the error. L91 says something about it requiring CPU/GPU communication that I honestly don't understand. I figure this will be a #dontfix for now then? :| 

Tagging @ebrevdo since it looks like his code (many thanks, though, for this useful function!)

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by facaiy** [comment]
The issue and #12405 seems both similar with #13687, which requests a bound checking for GPU . cc @ebrevdo.

**Comment by yongtang** [comment]
Added a PR #15857 to update the docs.
