### ISSUE TITLE
It seems that tf.gfile.Copy can not support larget hdfs file

### ISSUE THREAD

**Issue by ericyue** [tensorflow/tensorflow#12630]
It seems that when using ``tf.gfile.Copy("hdfs://default/some_hdfs_file","./test")``, if `some_hdfs_file` are large file such as 11GB in my case, it will report Exception.  Change to a 3GB file works fine.

I'm using the latest version of tensorflow.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/x/anaconda2/lib/python2.7/site-packages/tensorflow/python/lib/io/file_io.py", line 384, in copy
    compat.as_bytes(oldpath), compat.as_bytes(newpath), overwrite, status)
  File "/home/x/anaconda2/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/home/x/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: hdfs://default/tmp/x/x/dmcluster_predict_data_v3/20170817/023645/part-00000
```

**Comment by quaeler** [comment]
Seems incredibly unlikely since it looks like you're on a unix-variant, but just to cover all bases: `"./test"` in this example wouldn't be on a FAT32 volume, would it?

**Comment by ericyue** [comment]
@quaeler  it's not fat32 volume.  I can download the file using "hadoop fs -get " but can not using tf.gfile.Copy.  I'm not sure if the limitation is 4GB, I will test it later by using a 4GB file.

**Comment by quaeler** [comment]
Could you monitor the memory consumption of the python process when attempting to do this; i might be looking at the wrong thing or looking at the right thing wrongly, because this will sound cuckoo-banana, but the code path looks like it is doing this copy in memory:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/platform/gfile.py#L22
->
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/lib/io/file_io.py#L371
->
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/lib/io/file_io.i#L113

**Comment by ali01** [comment]
Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?  Make sure you also include the exact command if possible to produce  the output included in your test case. If you are unclear what to include  see the issue template displayed in  [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

 We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!

**Comment by tensorflowbutler** [comment]
This issue is automatically closed due to lack of activity. Please re-open if this is still an issue for you. Thanks!
