### ISSUE TITLE
Variable in Dataset map function is not stably initialized

### ISSUE THREAD

**Issue by biolee** [tensorflow/tensorflow#12648]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:NO
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:macos
- **TensorFlow installed from (source or binary)**:source
- **TensorFlow version (use command below)**:1.3
- **Python version**: 3.6
- **Bazel version (if compiling from source)**:0.5.3-homebrew
- **CUDA/cuDNN version**:NO
- **GPU model and memory**:
- **Exact command to reproduce**:

### Describe the problem
unable to init variable in map, flatmap, fillter function of Dataset API

### Source code / logs
```python
import tensorflow as  tf
from  tensorflow.contrib.data import Dataset

dataset = Dataset.range(100)

def mapf(v):
    temp = tf.Variable(
            tf.random_uniform(
                    [1],
                    minval=0,
                    maxval=10,
                    dtype=tf.int32,
            ),
            trainable=False,
            collections=[tf.GraphKeys.LOCAL_VARIABLES],
            name="my_var"
    )

    with tf.control_dependencies([tf.variables_initializer([temp])]):
        temp = temp + 1

    return temp


dataset = dataset.map(mapf)
dataset = dataset.batch(1)

iterator = dataset.make_one_shot_iterator()

next_element = iterator.get_next()
local_init = tf.local_variables_initializer()

with tf.Session() as sess:
    sess.run(local_init)
    try:
        while True:
            print(sess.run([next_element]))
    except tf.errors.OutOfRangeError as e:
        print("ending")
```
output is not stable:
```
2017-08-28 18:09:31.817313: W tensorflow/core/framework/op_kernel.cc:1192] Failed precondition: Attempting to use uninitialized value my_var
         [[Node: my_var/read = Identity[T=DT_INT32, _class=["loc:@my_var"]](my_var)]]
Traceback (most recent call last):
  File "/Users/liyanan/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1327, in _do_call
    return fn(*args)
  File "/Users/liyanan/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1306, in _run_fn
    status, run_metadata)
  File "/Users/liyanan/anaconda3/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/Users/liyanan/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value my_var
         [[Node: my_var/read = Identity[T=DT_INT32, _class=["loc:@my_var"]](my_var)]]
         [[Node: IteratorGetNext_2 = IteratorGetNext[output_shapes=[[?,1]], output_types=[DT_INT32], _device="/job:localhost/replica:0/task:0/cpu:0"](OneShotIterator)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dataset.py", line 90, in <module>
    print(sess.run([next_element]))
  File "/Users/liyanan/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/Users/liyanan/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "/Users/liyanan/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    options, run_metadata)
  File "/Users/liyanan/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value my_var
         [[Node: my_var/read = Identity[T=DT_INT32, _class=["loc:@my_var"]](my_var)]]
         [[Node: IteratorGetNext_2 = IteratorGetNext[output_shapes=[[?,1]], output_types=[DT_INT32], _device="/job:localhost/replica:0/task:0/cpu:0"](OneShotIterator)]]


```

OR 

```
[array([[2]], dtype=int32)]
[array([[9]], dtype=int32)]
[array([[1]], dtype=int32)]
[array([[5]], dtype=int32)]
[array([[9]], dtype=int32)]
[array([[9]], dtype=int32)]
.....
ending
```

**Comment by mrry** [comment]
Using `tf.Variable` in a TensorFlow function is not supported. To make this work, you'll need to use `tf.get_variable(..., use_resource=True)` *before* defining the `mapf()` function to declare the variable in the outer scope, then simply capture the variable in your `mapf()` function. Since you're defining a stateful input pipeline, you'll also need to use an *initializable* iterator rather than a one-shot iterator.

The following code illustrates how to do this:

```python
import tensorflow as  tf
from  tensorflow.contrib.data import Dataset

dataset = Dataset.range(100)

temp = tf.get_variable(
    "my_var",
    initializer=tf.random_uniform([1], minval=0, maxval=10, dtype=tf.int32),
    trainable=False,
    collections=[tf.GraphKeys.LOCAL_VARIABLES],
    use_resource=True)

def mapf(v):
  # NOTE(mrry): I assume you didn't really intend to reinitialize the
  # variable in each call to `mapf()`, and were instead trying to
  # increment it with the `temp = temp + 1` in the original code.
  with tf.control_dependencies([temp.assign_add([1]).op]):
    return temp

dataset = dataset.map(mapf)
dataset = dataset.batch(1)

iterator = dataset.make_initializable_iterator()
next_element = iterator.get_next()
local_init = tf.local_variables_initializer()

with tf.Session() as sess:
  sess.run(local_init)
  sess.run(iterator.initializer)
  try:
    while True:
      print(sess.run([next_element]))
  except tf.errors.OutOfRangeError as e:
    print("ending")
```

**Comment by biolee** [comment]
@mrry tks for help, it bother me for a week, may be we should add this to the doc
