### ISSUE TITLE
Issue loading label file on Android example

### ISSUE THREAD

**Issue by axtscz** [tensorflow/tensorflow#12698]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Android 8.0
- **TensorFlow installed from (source or binary)**:
Android Binary
- **TensorFlow version (use command below)**:
- **Python version**: 
NA
- **Bazel version (if compiling from source)**:
NA
- **CUDA/cuDNN version**:
NA
- **GPU model and memory**:
NA
- **Exact command to reproduce**:
NA

Whenever I try to build and launch the TF Classify demo app provided, the app crashes with the following error:

`08-29 21:03:01.791 9614-9614/org.tensorflow.demo E/AndroidRuntime: FATAL EXCEPTION: main
                                                                   Process: org.tensorflow.demo, PID: 9614
                                                                   java.lang.RuntimeException: Problem reading label file!
                                                                       at org.tensorflow.demo.TensorFlowImageClassifier.create(TensorFlowImageClassifier.java:100)
                                                                       at org.tensorflow.demo.ClassifierActivity.onPreviewSizeChosen(ClassifierActivity.java:107)
                                                                       at org.tensorflow.demo.CameraActivity$2.onPreviewSizeChosen(CameraActivity.java:324)
                                                                       at org.tensorflow.demo.CameraConnectionFragment.setUpCameraOutputs(CameraConnectionFragment.java:407)
                                                                       at org.tensorflow.demo.CameraConnectionFragment.openCamera(CameraConnectionFragment.java:414)
                                                                       at org.tensorflow.demo.CameraConnectionFragment.access$000(CameraConnectionFragment.java:64)
                                                                       at org.tensorflow.demo.CameraConnectionFragment$1.onSurfaceTextureAvailable(CameraConnectionFragment.java:95)
                                                                       at android.view.TextureView.getHardwareLayer(TextureView.java:390)
                                                                       at android.view.TextureView.draw(TextureView.java:339)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:18069)
                                                                       at android.view.View.draw(View.java:18847)
                                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:4214)
                                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4000)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:18060)
                                                                       at android.view.View.draw(View.java:18847)
                                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:4214)
                                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4000)
                                                                       at android.view.View.draw(View.java:19122)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:18069)
                                                                       at android.view.View.draw(View.java:18847)
                                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:4214)
                                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4000)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:18060)
                                                                       at android.view.View.draw(View.java:18847)
                                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:4214)
                                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4000)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:18060)
                                                                       at android.view.View.draw(View.java:18847)
                                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:4214)
                                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4000)
                                                                       at android.view.View.draw(View.java:19122)
                                                                       at com.android.internal.policy.DecorView.draw(DecorView.java:785)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:18069)
                                                                       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:643)
                                                                       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:649)
                                                                       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:757)
                                                                       at android.view.ViewRootImpl.draw(ViewRootImpl.java:2980)
                                                                       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2794)
                                                                       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2347)
                                                                       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1386)
                                                                       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6733)
                                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
                                                                       at android.view.Choreographer.doCallbacks(Choreographer.java:723)
                                                                       at android.view.Choreographer.doFrame(Choreographer.java:658)
                                                                       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
                                                                       at android.os.Handler.handleCallback(Handler.java:789)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                       at android.os.Looper.loop(Looper.java:164)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                                                                    Caused by: java.io.FileNotFoundException: imagenet_comp_graph_label_strings.txt
                                                                       at android.content.res.AssetManager.openAsset(Native Method)
                                                                       at android.content.res.AssetManager.open(AssetManager.java:374)
                                                                       at android.content.res.AssetManager.open(AssetManager.java:348)
                                                                       at org.tensorflow.demo.TensorFlowImageClassifier.create(TensorFlowImageClassifier.java:93)
                                                                       at org.tensorflow.demo.ClassifierActivity.onPreviewSizeChosen(ClassifierActivity.java:107) 
                                                                       at org.tensorflow.demo.CameraActivity$2.onPreviewSizeChosen(CameraActivity.java:324) 
                                                                       at org.tensorflow.demo.CameraConnectionFragment.setUpCameraOutputs(CameraConnectionFragment.java:407) 
                                                                       at org.tensorflow.demo.CameraConnectionFragment.openCamera(CameraConnectionFragment.java:414) 
                                                                       at org.tensorflow.demo.CameraConnectionFragment.access$000(CameraConnectionFragment.java:64) 
                                                                       at org.tensorflow.demo.CameraConnectionFragment$1.onSurfaceTextureAvailable(CameraConnectionFragment.java:95) 
                                                                       at android.view.TextureView.getHardwareLayer(TextureView.java:390) 
                                                                       at android.view.TextureView.draw(TextureView.java:339) 
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:18069) 
                                                                       at android.view.View.draw(View.java:18847) 
                                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:4214) 
                                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4000) 
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:18060) 
                                                                       at android.view.View.draw(View.java:18847) 
                                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:4214) 
                                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4000) 
                                                                       at android.view.View.draw(View.java:19122) 
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:18069) 
                                                                       at android.view.View.draw(View.java:18847) 
                                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:4214) 
                                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4000) 
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:18060) 
                                                                       at android.view.View.draw(View.java:18847) 
                                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:4214) 
                                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4000) 
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:18060) 
                                                                       at android.view.View.draw(View.java:18847) 
                                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:4214) 
                                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4000) 
                                                                       at android.view.View.draw(View.java:19122) 
                                                                       at com.android.internal.policy.DecorView.draw(DecorView.java:785) 
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:18069) 
                                                                       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:643) 
                                                                       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:649) 
                                                                       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:757) 
                                                                       at android.view.ViewRootImpl.draw(ViewRootImpl.java:2980) 
                                                                       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2794) 
                                                                       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2347) 
                                                                       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1386) 
                                                                       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6733) 
                                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911) 
                                                                       at android.view.Choreographer.doCallbacks(Choreographer.java:723) 
                                                                       at android.view.Choreographer.doFrame(Choreographer.java:658) 
                                                                       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897) 
                                                                       at android.os.Handler.handleCallback(Handler.java:789) 
                                                                       at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                       at android.os.Looper.loop(Looper.java:164) 
                                                                       at android.app.ActivityThread.main(ActivityThread.java:6541) 
                                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                                       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
`
The app has storage permissions enabled and was built on windows from the makefile, not Bazel.

**Comment by szymonk92** [comment]
@axtscz How did you solve the problem?

**Comment by aldrin233** [comment]
any solutions for this?
