### ISSUE TITLE
'utf-8' codec can't decode byte (image_retraining)

### ISSUE THREAD

**Issue by paulgnz** [tensorflow/tensorflow#1274]
On the Training on Flowers how to;
https://www.tensorflow.org/versions/master/how_tos/image_retraining/index.html 

Unable to get to get the .pb file and the .txt file to create in /tmp due to;
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbb in position 1: invalid start byte

### Environment info
Operating System:
Mac OSX El Captain 10.11.3 (15D21)
Python 3.5.1
Tensorflow from source, commit [bfd5f0b](https://github.com/tensorflow/tensorflow/commit/bfd5f0bfaa13f397e80063ce59951033928b04b6)
If installed from binary pip package, provide:

1. pip3 install --upgrade https://storage.googleapis.com/tensorflow/mac/tensorflow-0.7.1-cp35-none-any.whl
2. The output from python3 -c 'import os; import inspect; import tensorflow; print(os.path.dirname(inspect.getfile(tensorflow)))'
/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow

### Steps to reproduce
1. brand new mac, fresh brew, python3, pip3 etc
2. all tutorials so far are great, then on to;
https://www.tensorflow.org/versions/master/how_tos/image_retraining/index.html
3. bazel build -c opt --copt=-mavx tensorflow/examples/image_retraining:retrain
OK
4. bazel-bin/tensorflow/examples/image_retraining/retrain --image_dir ~/flower_photos
Error, see output below

### Logs or other output that would be helpful
Traceback (most recent call last):
  File "/Users/paulg/proj/tensorflow/bazel-bin/tensorflow/examples/image_retraining/retrain.runfiles/tensorflow/examples/image_retraining/retrain.py", line 828, in <module>
    tf.app.run()
  File "/Users/paulg/proj/tensorflow/bazel-bin/tensorflow/examples/image_retraining/retrain.runfiles/tensorflow/python/platform/default/_app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "/Users/paulg/proj/tensorflow/bazel-bin/tensorflow/examples/image_retraining/retrain.runfiles/tensorflow/examples/image_retraining/retrain.py", line 715, in main
    graph = create_inception_graph()
  File "/Users/paulg/proj/tensorflow/bazel-bin/tensorflow/examples/image_retraining/retrain.runfiles/tensorflow/examples/image_retraining/retrain.py", line 301, in create_inception_graph
    graph_def.ParseFromString(f.read())
  File "/Users/paulg/proj/tensorflow/bazel-bin/tensorflow/examples/image_retraining/retrain.runfiles/tensorflow/python/platform/default/_gfile.py", line 45, in sync
    return fn(self, *args, **kwargs)
  File "/Users/paulg/proj/tensorflow/bazel-bin/tensorflow/examples/image_retraining/retrain.runfiles/tensorflow/python/platform/default/_gfile.py", line 199, in read
    return self._fp.read(n)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbb in position 1: invalid start byte

**Comment by paulgnz** [comment]
Thanks! Creating bottleneck with updated retrain.py
[6a63c2d](https://github.com/dgolden1/tensorflow/commit/6a63c2df153b6717799315bcc9a304bef5b2296d)

**Comment by dgolden1** [comment]
I'll make a PR shortly, once I figure out the contributing agreement. Feel free to cherry pick it you can't wait!

https://github.com/dgolden1/tensorflow/commit/6a63c2df153b6717799315bcc9a304bef5b2296d
