### ISSUE TITLE
build_default_serving_input_fn() uses a name that is not a valid variable scope. 

### ISSUE THREAD

**Issue by slacy** [tensorflow/tensorflow#12755]
------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: NO
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 14.04 LTS 
- **TensorFlow installed from (source or binary)**: SOURCE (pip install tensorflow) 
- **TensorFlow version (use command below)**: ('v1.3.0-rc2-20-g0787eee', '1.3.0')
- **Python version**: Python 2.7.6
- **Bazel version (if compiling from source)**: N/A 
- **CUDA/cuDNN version**: N/A 
- **GPU model and memory**: N/A 
- **Exact command to reproduce**:

### Describe the problem

See this short example:

$ python -c "import tensorflow as tf 
f = {'feature': tf.placeholder(name='feature', shape=[32], dtype=tf.float32) } 
serving_input = tf.contrib.learn.utils.input_fn_utils.build_default_serving_input_fn(f)
serving_input()"

Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "/usr/local/google/home/slacy/src/tf_clean/env/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/utils/input_fn_utils.py", line 112, in input_fn
    name=t.name)
  File "/usr/local/google/home/slacy/src/tf_clean/env/local/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 1548, in placeholder
    return gen_array_ops._placeholder(dtype=dtype, shape=shape, name=name)
  File "/usr/local/google/home/slacy/src/tf_clean/env/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 2094, in _placeholder
    name=name)
  File "/usr/local/google/home/slacy/src/tf_clean/env/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 374, in apply_op
    with g.as_default(), ops.name_scope(name) as scope:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/google/home/slacy/src/tf_clean/env/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 4522, in name_scope
    with g.as_default(), g.name_scope(n) as scope:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/google/home/slacy/src/tf_clean/env/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3172, in name_scope
    raise ValueError("'%s' is not a valid scope name" % name)
ValueError: 'feature:0' is not a valid scope name

The issue is that in input_fn_utils.py here: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/learn/python/learn/utils/input_fn_utils.py#L112

The attribute "t.name" is passed to array_ops.placeholder(), and t.name will always have a ":N" suffix, and ":" is not a valid variable scope name, so this function fals. 

### Source code / logs

See above.

**Comment by yongtang** [comment]
I think the issue could be fixed by using tensor's op name (`t.op.name`) instead. Created a PR #12759 for the fix.

**Comment by jart** [comment]
Apparently that function was moved into core as [`tf.estimator.export.build_raw_serving_input_receiver_fn`](https://www.tensorflow.org/api_docs/python/tf/estimator/export/build_raw_serving_input_receiver_fn). Does that function work for you?

**Comment by yongtang** [comment]
@jart @slacy The `tf.estimator.export.build_raw_serving_input_receiver_fn` was using:
```
t.name.split(':')[0]
```
so it is fine although I think it might make sense to change it to
```
t.op.name
```
 as well. This will make it easy to maintain later.

I updated the PR #12759 and also added the test case to cover `tf.estimator.export.build_raw_serving_input_receiver_fn`  as well. Please take a look.
