### ISSUE TITLE
bazel error 

### ISSUE THREAD

**Issue by dilli007** [tensorflow/tensorflow#12823]
ERROR: /Users/dile/tensorflow/third_party/py/numpy/BUILD:11:1: no such package '@local_config_python//': Traceback (most recent call last):
	File "/Users/dile/tensorflow/third_party/py/python_configure.bzl", line 310
		_create_local_python_repository(repository_ctx)
	File "/Users/dile/tensorflow/third_party/py/python_configure.bzl", line 268, in _create_local_python_repository
		_get_python_bin(repository_ctx)
	File "/Users/dile/tensorflow/third_party/py/python_configure.bzl", line 166, in _get_python_bin
		_get_env_var(repository_ctx, _PYTHON_BIN_PATH, No..., ...)
	File "/Users/dile/tensorflow/third_party/py/python_configure.bzl", line 49, in _get_env_var
		_python_configure_fail(("'%s' environment variable is n...))
	File "/Users/dile/tensorflow/third_party/py/python_configure.bzl", line 37, in _python_configure_fail
		fail(("%sPython Configuration Error:%...)))
Python Configuration Error: 'PYTHON_BIN_PATH' environment variable is not set
 and referenced by '//third_party/py/numpy:headers'.
ERROR: Analysis of target '//tensorflow/examples/image_retraining:retrain' failed; build aborted.

**Comment by drpngx** [comment]
Can you put the rest of the information? (OS, etc) Did you run configure?

**Comment by gunan** [comment]
maybe forgot to run configure?

I apologize but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new) . Please provide all the information it asks. Thank you.
