### ISSUE TITLE
Unhelpful exceptions from tf.truncated_normal with dtype=tf.int32 

### ISSUE THREAD

**Issue by slacy** [tensorflow/tensorflow#12857]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: NO
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 14.04 LTS 
- **TensorFlow installed from (source or binary)**: pip install tensorflow 
- **TensorFlow version (use command below)**: ('v1.3.0-rc2-20-g0787eee', '1.3.0')
- **Python version**: Python 2.7.6
- **Bazel version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A (CPU)
- **GPU model and memory**: N/A 
- **Exact command to reproduce**:

python -c "import tensorflow as tf ; tf.truncated_normal([1], dtype=tf.int32)"

### Describe the problem
When attempting to initialize a tf.Variable of type tf.int32 using ```tf.truncated_normal()```, invocation with simple args raise a TypeError, but the error message is ambiguous and unhelpful for debugging: 

```
python -c "import tensorflow as tf ; tf.truncated_normal([1], dtype=tf.int32)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/slacy/src/tf_clean/env/local/lib/python2.7/site-packages/tensorflow/python/ops/random_ops.py", line 168, in truncated_normal
    mean_tensor = ops.convert_to_tensor(mean, dtype=dtype, name="mean")
  File "/usr/slacy/src/tf_clean/env/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 611, in convert_to_tensor
    as_ref=False)
  File "/usr/slacy/src/tf_clean/env/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 676, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/slacy/src/tf_clean/env/local/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 121, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/usr/slacy/src/tf_clean/env/local/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 102, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/usr/slacy/src/tf_clean/env/local/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 376, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/usr/slacy/src/tf_clean/env/local/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 302, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got 0.0 of type 'float' instead.

```

Providing more arguments to ```tf.truncated_normal``` correctly indicates that tf.int32 isn't a supported type: 

```
python -c "import tensorflow as tf ; tf.truncated_normal([1], mean=0, stddev=1, dtype=tf.int32)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/slacy/src/tf_clean/env/local/lib/python2.7/site-packages/tensorflow/python/ops/random_ops.py", line 172, in truncated_normal
    shape_tensor, dtype, seed=seed1, seed2=seed2)
  File "/usr/slacy/src/tf_clean/env/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_random_ops.py", line 316, in _truncated_normal
    seed=seed, seed2=seed2, name=name)
  File "/usr/slacy/src/tf_clean/env/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 700, in apply_op
    attr_value.type = _MakeType(value, attr_def)
  File "/usr/slacy/src/tf_clean/env/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 179, in _MakeType
    _SatisfiesTypeConstraint(i, attr_def, param_name=attr_def.name)
  File "/usr/slacy/src/tf_clean/env/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 60, in _SatisfiesTypeConstraint
    ", ".join(dtypes.as_dtype(x).name for x in allowed_list)))
TypeError: Value passed to parameter 'dtype' has DataType int32 not in list of allowed values: float16, float32, float64
```

Contrasting this with usage of complex64, which provides the correct error message even with simple args: 

```
python -c "import tensorflow as tf ; tf.truncated_normal([1], dtype=tf.complex64)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/slacy/src/tf_clean/env/local/lib/python2.7/site-packages/tensorflow/python/ops/random_ops.py", line 172, in truncated_normal
    shape_tensor, dtype, seed=seed1, seed2=seed2)
  File "/usr/slacy/src/tf_clean/env/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_random_ops.py", line 316, in _truncated_normal
    seed=seed, seed2=seed2, name=name)
  File "/usr/slacy/src/tf_clean/env/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 700, in apply_op
    attr_value.type = _MakeType(value, attr_def)
  File "/usr/slacy/src/tf_clean/env/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 179, in _MakeType
    _SatisfiesTypeConstraint(i, attr_def, param_name=attr_def.name)
  File "/usr/slacy/src/tf_clean/env/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 60, in _SatisfiesTypeConstraint
    ", ".join(dtypes.as_dtype(x).name for x in allowed_list)))
TypeError: Value passed to parameter 'dtype' has DataType complex64 not in list of allowed values: float16, float32, float64
```

dtype argument checking should happen up front, earlier in the codepath of ```truncated_normal()```

### Source code / logs

See above

**Comment by printdhruv** [comment]
@slacy For reference, I am putting source code which is generating error.

`snippet-1` generated via `framework/tensor_util.py`.

```
def _AssertCompatible(values, dtype):
  fn_list = _TF_TO_IS_OK.get(dtype, [_FilterNotTensor])
  mismatch = _FirstNotNone([fn(values) for fn in fn_list])
  if mismatch is not None:
    if dtype is None:
      raise TypeError("List of Tensors when single Tensor expected")
    else:
      raise TypeError("Expected %s, got %s of type '%s' instead." %
                      (dtype.name, repr(mismatch), type(mismatch).__name__))
```

`snippet-2 and snippet-3` generated via `framework/op_def_library.py`

```
def _SatisfiesTypeConstraint(dtype, attr_def, param_name):
  if attr_def.HasField("allowed_values"):
    allowed_list = attr_def.allowed_values.list.type
    if dtype not in allowed_list:
      raise TypeError(
          "Value passed to parameter '%s' has DataType %s not in list of "
          "allowed values: %s" %
          (param_name, dtypes.as_dtype(dtype).name,
           ", ".join(dtypes.as_dtype(x).name for x in allowed_list)))
```

**Comment by drpngx** [comment]
The truncated normal doesn't seem to make sense to me? The integer will be mostly zero. What do you expect as a result?

**Comment by printdhruv** [comment]
@drpngx do you have any suggestions? I tried to change flow but not passing 1 test case. Would you advise something else to make it informative?

**Comment by tensorflowbutler** [comment]
This issue is automatically closed due to lack of activity. Please re-open if this is still an issue for you. Thanks!
