### ISSUE TITLE
bazel error related to python 

### ISSUE THREAD

**Issue by dilli007** [tensorflow/tensorflow#12905]
bazel build tensorflow/examples/image_retraining:retrain
ERROR: /home/dile/tensorflow/third_party/py/numpy/BUILD:11:1: no such package '@local_config_python//': Traceback (most recent call last):
	File "/home/dile/tensorflow/third_party/py/python_configure.bzl", line 310
		_create_local_python_repository(repository_ctx)
	File "/home/dile/tensorflow/third_party/py/python_configure.bzl", line 268, in _create_local_python_repository
		_get_python_bin(repository_ctx)
	File "/home/dile/tensorflow/third_party/py/python_configure.bzl", line 166, in _get_python_bin
		_get_env_var(repository_ctx, _PYTHON_BIN_PATH, No..., ...)
	File "/home/dile/tensorflow/third_party/py/python_configure.bzl", line 49, in _get_env_var
		_python_configure_fail(("'%s' environment variable is n...))
	File "/home/dile/tensorflow/third_party/py/python_configure.bzl", line 37, in _python_configure_fail
		fail(("%sPython Configuration Error:%...)))
Python Configuration Error: 'PYTHON_BIN_PATH' environment variable is not set
 and referenced by '//third_party/py/numpy:headers'
ERROR: Analysis of target '//tensorflow/examples/image_retraining:retrain' failed; build aborted
INFO: Elapsed time: 4.555s
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: tensorflow/core ... (3 packages)

Operating system is ubuntu
and i dont know how to run configure..what and all i have to select in that

**Comment by quaeler** [comment]
As you point out, you must run configure prior to attempting to build; build [guidance is here.](https://www.tensorflow.org/install/install_sources)

**Comment by zhang405744522** [comment]
anaconda work bad even if run configure file.
