### ISSUE TITLE
error when giving this command bazel-bin/tensorflow/examples/image_retraining/retrain --image_dir ~/home/dile/dataset/dosa

### ISSUE THREAD

**Issue by dilli007** [tensorflow/tensorflow#12929]
Traceback (most recent call last):
  File "/home/dile/tensorflow/bazel-bin/tensorflow/examples/image_retraining/retrain.runfiles/org_tensorflow/tensorflow/examples/image_retraining/retrain.py", line 108, in <module>
    import tensorflow as tf
  File "/home/dile/tensorflow/bazel-bin/tensorflow/examples/image_retraining/retrain.runfiles/org_tensorflow/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/home/dile/tensorflow/bazel-bin/tensorflow/examples/image_retraining/retrain.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 63, in <module>
    from tensorflow.python.framework.framework_lib import *
  File "/home/dile/tensorflow/bazel-bin/tensorflow/examples/image_retraining/retrain.runfiles/org_tensorflow/tensorflow/python/framework/framework_lib.py", line 76, in <module>
    from tensorflow.python.framework.ops import Graph
  File "/home/dile/tensorflow/bazel-bin/tensorflow/examples/image_retraining/retrain.runfiles/org_tensorflow/tensorflow/python/framework/ops.py", line 28, in <module>
    from autograd import core as ag_core
ImportError: No module named autograd

**Comment by erikbjohn** [comment]
What was the solution to this problem?
