### ISSUE TITLE
cudnn_rnn_ops.py cannot find _cudnn_rnn_ops.so

### ISSUE THREAD

**Issue by apuayush** [tensorflow/tensorflow#12939]
https://github.com/tensorflow/tensorflow/blob/702d595822e9e5f5232b8140c6296683612c33a9/tensorflow/contrib/cudnn_rnn/python/ops/cudnn_rnn_ops.py#L37

**Comment by apuayush** [comment]
`Using TensorFlow backend.
Traceback (most recent call last):
  File "/home/apurvnit/Downloads/test.py", line 3, in <module>
    import keras
  File "/home/apurvnit/anaconda/lib/python3.5/site-packages/keras/__init__.py", line 4, in <module>
    from . import activations
  File "/home/apurvnit/anaconda/lib/python3.5/site-packages/keras/activations.py", line 6, in <module>
    from .engine import Layer
  File "/home/apurvnit/anaconda/lib/python3.5/site-packages/keras/engine/__init__.py", line 8, in <module>
    from .training import Model
  File "/home/apurvnit/anaconda/lib/python3.5/site-packages/keras/engine/training.py", line 25, in <module>
    from .. import callbacks as cbks
  File "/home/apurvnit/anaconda/lib/python3.5/site-packages/keras/callbacks.py", line 26, in <module>
    from tensorflow.contrib.tensorboard.plugins import projector
  File "/home/apurvnit/anaconda/lib/python3.5/site-packages/tensorflow/contrib/__init__.py", line 25, in <module>
    from tensorflow.contrib import cudnn_rnn
  File "/home/apurvnit/anaconda/lib/python3.5/site-packages/tensorflow/contrib/cudnn_rnn/__init__.py", line 21, in <module>
    from tensorflow.contrib.cudnn_rnn.python.ops.cudnn_rnn_ops import CudnnGRU
  File "/home/apurvnit/anaconda/lib/python3.5/site-packages/tensorflow/contrib/cudnn_rnn/python/ops/cudnn_rnn_ops.py", line 28, in <module>
    resource_loader.get_path_to_datafile("_cudnn_rnn_ops.so"))
  File "/home/apurvnit/anaconda/lib/python3.5/site-packages/tensorflow/contrib/util/loader.py", line 42, in load_op_library
    ret = load_library.load_op_library(path)
  File "/home/apurvnit/anaconda/lib/python3.5/site-packages/tensorflow/python/framework/load_library.py", line 64, in load_op_library
    None, None, error_msg, error_code)
tensorflow.python.framework.errors_impl.NotFoundError: /home/apurvnit/anaconda/lib/python3.5/site-packages/tensorflow/contrib/cudnn_rnn/python/ops/_cudnn_rnn_ops.so: cannot open shared object file: No such file or directory`

**Comment by reedwm** [comment]
I apologize but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new) . Please provide all the information it asks. Thank you.

**Comment by keithyuck** [comment]
@apuayush I am having the same issue right now, how did you resolve the issue
