### ISSUE TITLE
android //tensorflow:libtensorflow.so build fails due to missing build target

### ISSUE THREAD

**Issue by d4l3k** [tensorflow/tensorflow#12988]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 14.04
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: master
- **Python version**: 3.6.2
- **Bazel version (if compiling from source)**: 0.5.4
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**:

```
export CC_OPT_FLAGS="-march=armv7-a -std=c++11"
yes '' | ./configure
bazel build --config=opt --verbose_failures //tensorflow/contrib/android:libtensorflow_inference.so //tensorflow:libtensorflow.so --crosstool_top=//external:android/crosstool --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --cpu=armeabi-v7a
```

### Describe the problem
`//tensorflow/c/eager:c_api` depends on `//tensorflow/c/eager:c_api_internal` when building with `//tensorflow:android`, but `:c_api_internal` doesn't exist.

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/c/eager/BUILD#L19

### Source code / logs

Error:
```
ERROR: /home/travis/tensorflow/tensorflow/c/eager/BUILD:11:1: in deps attribute of cc_library rule //tensorflow/c/eager:c_api: target '//tensorflow/c/eager:c_api_internal' does not exist. Since this rule was created by the macro 'tf_cuda_library', the error might have been caused by the macro implementation in /home/travis/tensorflow/tensorflow/tensorflow.bzl:669:12
```

Full build: https://travis-ci.org/luk-ai/build-tensorflow/builds/274455610

**Comment by d4l3k** [comment]
Think it should be `//tensorflow/c:c_api_internal` instead.
```
sed -i 's@":c_api_internal"@"//tensorflow/c:c_api_internal"@' tensorflow/c/eager/BUILD
```

**Comment by d4l3k** [comment]
Once that's fixed there's also a missing header file error. Seems like c/eager is all messed up with regards to Android.

```
ERROR: /home/travis/tensorflow/tensorflow/c/eager/BUILD:11:1: C++ compilation of rule '//tensorflow/c/eager:c_api' failed (Exit 1): clang failed: error executing command 
  (cd /home/travis/.cache/bazel/_bazel_travis/c397b760afc31b444fffb10b0086dea5/execroot/org_tensorflow && \
  exec env - \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/usr/bin/python \
    PYTHON_LIB_PATH=/usr/local/lib/python2.7/dist-packages \
    TF_NEED_CUDA=0 \
    TF_NEED_OPENCL=0 \
  external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -gcc-toolchain external/androidndk/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64 -fpic -ffunction-sections -funwind-tables -fstack-protector-strong -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes -fno-integrated-as -target armv7-none-linux-androideabi '-march=armv7-a' '-mfloat-abi=softfp' '-mfpu=vfpv3-d16' -mthumb -Os -g -DNDEBUG '-march=armv7-a' '-march=armv7-a' '-std=c++11' -MD -MF bazel-out/arm-linux-androideabi-clang3.8-v7a-gnu-libstdcpp-opt/bin/tensorflow/c/eager/_objs/c_api/tensorflow/c/eager/c_api.d '-frandom-seed=bazel-out/arm-linux-androideabi-clang3.8-v7a-gnu-libstdcpp-opt/bin/tensorflow/c/eager/_objs/c_api/tensorflow/c/eager/c_api.o' -DEIGEN_MPL2_ONLY -iquote . -iquote bazel-out/arm-linux-androideabi-clang3.8-v7a-gnu-libstdcpp-opt/genfiles -iquote external/protobuf_archive -iquote bazel-out/arm-linux-androideabi-clang3.8-v7a-gnu-libstdcpp-opt/genfiles/external/protobuf_archive -iquote external/bazel_tools -iquote bazel-out/arm-linux-androideabi-clang3.8-v7a-gnu-libstdcpp-opt/genfiles/external/bazel_tools -iquote external/eigen_archive -iquote bazel-out/arm-linux-androideabi-clang3.8-v7a-gnu-libstdcpp-opt/genfiles/external/eigen_archive -iquote external/local_config_sycl -iquote bazel-out/arm-linux-androideabi-clang3.8-v7a-gnu-libstdcpp-opt/genfiles/external/local_config_sycl -iquote external/nsync -iquote bazel-out/arm-linux-androideabi-clang3.8-v7a-gnu-libstdcpp-opt/genfiles/external/nsync -isystem external/protobuf_archive/src -isystem bazel-out/arm-linux-androideabi-clang3.8-v7a-gnu-libstdcpp-opt/genfiles/external/protobuf_archive/src -isystem external/bazel_tools/tools/cpp/gcc3 -isystem external/eigen_archive -isystem bazel-out/arm-linux-androideabi-clang3.8-v7a-gnu-libstdcpp-opt/genfiles/external/eigen_archive -isystem external/nsync/public -isystem bazel-out/arm-linux-androideabi-clang3.8-v7a-gnu-libstdcpp-opt/genfiles/external/nsync/public -DEIGEN_AVOID_STL_ARRAY -Iexternal/gemmlowp -Wno-sign-compare -fno-exceptions '-ftemplate-depth=900' '-mfpu=neon' '-std=c++11' -DTF_LEAN_BINARY -O2 -Wno-narrowing -fomit-frame-pointer '--sysroot=external/androidndk/ndk/platforms/android-23/arch-arm' -isystem external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include -isystem external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/include -isystem external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/backward -c tensorflow/c/eager/c_api.cc -o bazel-out/arm-linux-androideabi-clang3.8-v7a-gnu-libstdcpp-opt/bin/tensorflow/c/eager/_objs/c_api/tensorflow/c/eager/c_api.o)
In file included from tensorflow/c/eager/c_api.cc:26:
In file included from ./tensorflow/c/eager/runtime.h:31:
In file included from ./tensorflow/core/platform/fingerprint.h:82:
./tensorflow/core/platform/default/fingerprint.h:19:10: fatal error: 'farmhash.h' file not found
#include <farmhash.h>
         ^
1 error generated.
INFO: Elapsed time: 907.512s, Critical Path: 40.08s
FAILED: Build did NOT complete successfully
```

**Comment by andrewharp** [comment]
@d4l3k //tensorflow:libtensorflow.so is a non-mobile target and is not expected to build for Android. libtensorflow_inference.so should contain everything you need for inference on Android. All of the valid Android native targets (apart from the Java api I think) start with the prefix "android_".

**Comment by d4l3k** [comment]
@andrewharp, I'm trying to get the Go API working on Android but it requires the full C API. Any suggestions about how to go about that? Seems surprising that the C API isn't portable

**Comment by andrewharp** [comment]
@d4l3k Sorry, not too familiar with Go API -- what is missing from the C API supported by the Android targets?

**Comment by d4l3k** [comment]
@andrewharp The Go API binds to the C API. Whereas the Android `libtensorflow_inference.so` is completely different.

https://gist.github.com/d4l3k/ea9119dfe11d1c12b0494d570ade289f

## Android
```
00098959 g    DF .text	000004c4  VERS_1.0    Java_org_tensorflow_Session_run
00098905 g    DF .text	00000054  VERS_1.0    Java_org_tensorflow_Session_delete
000988f1 g    DF .text	00000012  VERS_1.0    Java_org_tensorflow_Session_allocate
00096f55 g    DF .text	0000000a  VERS_1.0    Java_org_tensorflow_Graph_allocate
00096f61 g    DF .text	0000000e  VERS_1.0    Java_org_tensorflow_Graph_delete
00096f71 g    DF .text	00000068  VERS_1.0    Java_org_tensorflow_Graph_operation
00096fd9 g    DF .text	000000e8  VERS_1.0    Java_org_tensorflow_Graph_importGraphDef
000987d5 g    DF .text	0000011c  VERS_1.0    Java_org_tensorflow_Session_allocate2
000982e1 g    DF .text	00000084  VERS_1.0    Java_org_tensorflow_Operation_dtype
0009840d g    DF .text	00000294  VERS_1.0    Java_org_tensorflow_SavedModelBundle_load
000970c1 g    DF .text	000000b4  VERS_1.0    Java_org_tensorflow_Graph_toGraphDef
00098365 g    DF .text	0000006c  VERS_1.0    Java_org_tensorflow_Operation_inputListLength
00098091 g    DF .text	00000030  VERS_1.0    Java_org_tensorflow_Operation_numOutputs
00097191 g    DF .text	00000078  VERS_1.0    Java_org_tensorflow_OperationBuilder_allocate
00098055 g    DF .text	0000003c  VERS_1.0    Java_org_tensorflow_Operation_type
00097209 g    DF .text	0000004a  VERS_1.0    Java_org_tensorflow_OperationBuilder_finish
0009812d g    DF .text	000001b4  VERS_1.0    Java_org_tensorflow_Operation_shape
00097255 g    DF .text	00000054  VERS_1.0    Java_org_tensorflow_OperationBuilder_addInput
000980c1 g    DF .text	0000006c  VERS_1.0    Java_org_tensorflow_Operation_outputListLength
000972a9 g    DF .text	00000194  VERS_1.0    Java_org_tensorflow_OperationBuilder_addInputList
00099ed1 g    DF .text	0000003c  VERS_1.0    Java_org_tensorflow_TensorFlow_registeredOpList
0009743d g    DF .text	00000054  VERS_1.0    Java_org_tensorflow_OperationBuilder_addControlInput
00099eb9 g    DF .text	00000018  VERS_1.0    Java_org_tensorflow_TensorFlow_version
00097491 g    DF .text	0000004c  VERS_1.0    Java_org_tensorflow_OperationBuilder_setDevice
00099e31 g    DF .text	00000088  VERS_1.0    Java_org_tensorflow_Tensor_readNDArray
000974dd g    DF .text	0000007e  VERS_1.0    Java_org_tensorflow_OperationBuilder_setAttrString
0009755d g    DF .text	00000054  VERS_1.0    Java_org_tensorflow_OperationBuilder_setAttrInt
00099abd g    DF .text	000000bc  VERS_1.0    Java_org_tensorflow_Tensor_scalarInt
000975b1 g    DF .text	0000011a  VERS_1.0    Java_org_tensorflow_OperationBuilder_setAttrIntList
000999e9 g    DF .text	000000d4  VERS_1.0    Java_org_tensorflow_Tensor_scalarDouble
00099931 g    DF .text	000000b8  VERS_1.0    Java_org_tensorflow_Tensor_scalarFloat
000976cd g    DF .text	00000052  VERS_1.0    Java_org_tensorflow_OperationBuilder_setAttrFloat
000996b5 g    DF .text	0000027c  VERS_1.0    Java_org_tensorflow_Tensor_setValue
00097721 g    DF .text	0000013e  VERS_1.0    Java_org_tensorflow_OperationBuilder_setAttrFloatList
00099cd9 g    DF .text	00000158  VERS_1.0    Java_org_tensorflow_Tensor_scalarBytes
00099c49 g    DF .text	00000090  VERS_1.0    Java_org_tensorflow_Tensor_scalarBoolean
00097861 g    DF .text	00000052  VERS_1.0    Java_org_tensorflow_OperationBuilder_setAttrBool
00099b79 g    DF .text	000000d0  VERS_1.0    Java_org_tensorflow_Tensor_scalarLong
000995f1 g    DF .text	00000030  VERS_1.0    Java_org_tensorflow_Tensor_dtype
000978b5 g    DF .text	000001a6  VERS_1.0    Java_org_tensorflow_OperationBuilder_setAttrBoolList
000995a1 g    DF .text	00000050  VERS_1.0    Java_org_tensorflow_Tensor_buffer
00097a5d g    DF .text	00000052  VERS_1.0    Java_org_tensorflow_OperationBuilder_setAttrType
00097ab1 g    DF .text	00000104  VERS_1.0    Java_org_tensorflow_OperationBuilder_setAttrTypeList
00099621 g    DF .text	00000094  VERS_1.0    Java_org_tensorflow_Tensor_shape
00097bb5 g    DF .text	00000088  VERS_1.0    Java_org_tensorflow_OperationBuilder_setAttrTensor
000994b9 g    DF .text	000000d8  VERS_1.0    Java_org_tensorflow_Tensor_allocateScalarBytes
00097c3d g    DF .text	0000013c  VERS_1.0    Java_org_tensorflow_OperationBuilder_setAttrTensorList
0009933d g    DF .text	0000017c  VERS_1.0    Java_org_tensorflow_Tensor_allocate
00097d79 g    DF .text	00000144  VERS_1.0    Java_org_tensorflow_OperationBuilder_setAttrShape
00099591 g    DF .text	0000000e  VERS_1.0    Java_org_tensorflow_Tensor_delete
00097ebd g    DF .text	0000015a  VERS_1.0    Java_org_tensorflow_OperationBuilder_setAttrStringList
00098019 g    DF .text	0000003c  VERS_1.0    Java_org_tensorflow_Operation_name
```
## C
```
00000000002d4820 g    DF .text	000000000000003a  VERS_1.0    TF_SetAttrType
00000000002d42d0 g    DF .text	0000000000000070  VERS_1.0    TF_DeleteDeviceList
00000000002d5460 g    DF .text	0000000000000190  VERS_1.0    TF_OperationGetAttrTensor
00000000002db710 g    DF .text	0000000000000052  VERS_1.0    TF_ImportGraphDefOptionsAddControlDependency
00000000002d3d60 g    DF .text	0000000000000029  VERS_1.0    TF_SetTarget
00000000002d6b50 g    DF .text	00000000000000d3  VERS_1.0    TF_StringDecode
00000000002df7a0 g    DF .text	000000000000006b  VERS_1.0    TF_DeleteSessionOptions
00000000002d3ff0 g    DF .text	00000000000001b2  VERS_1.0    TF_Reset
00000000002d4780 g    DF .text	0000000000000099  VERS_1.0    TF_SetAttrBoolList
00000000002da4c0 g    DF .text	000000000000037c  VERS_1.0    TF_SetAttrTensorShapeProtoList
00000000002d3cb0 g    DF .text	000000000000000a  VERS_1.0    TF_NumDims
00000000002d4600 g    DF .text	000000000000003c  VERS_1.0    TF_SetAttrString
00000000002d5c90 g    DF .text	000000000000014a  VERS_1.0    TF_NewSession
00000000002d66e0 g    DF .text	00000000000000a9  VERS_1.0    TF_SetConfig
00000000002d9c90 g    DF .text	0000000000000170  VERS_1.0    TF_SetAttrStringList
00000000002d3d90 g    DF .text	0000000000000027  VERS_1.0    TF_NewBuffer
00000000002d49a0 g    DF .text	000000000000000a  VERS_1.0    TF_OperationNumOutputs
00000000002e4680 g    DF .text	00000000000006f9  VERS_1.0    TF_LoadSessionFromSavedModel
00000000002e2cb0 g    DF .text	00000000000004ef  VERS_1.0    TF_NewWhile
00000000002d5de0 g    DF .text	000000000000008c  VERS_1.0    TF_CloseSession
00000000002d8fe0 g    DF .text	0000000000000102  VERS_1.0    TF_DeleteImportGraphDefOptions
00000000002dae20 g    DF .text	00000000000001d5  VERS_1.0    TF_OperationOutputListLength
00000000002df0f0 g    DF .text	00000000000002ac  VERS_1.0    TF_SetAttrTensorList
00000000002d4860 g    DF .text	000000000000003c  VERS_1.0    TF_SetAttrTypeList
00000000002defa0 g    DF .text	000000000000014a  VERS_1.0    TF_SetAttrTensor
00000000002d6080 g    DF .text	0000000000000404  VERS_1.0    TF_PRunSetup
00000000002dcdd0 g    DF .text	000000000000010a  VERS_1.0    TF_GraphOperationByName
00000000002d4a80 g    DF .text	00000000000000d8  VERS_1.0    TF_OperationOutputNumConsumers
00000000002d7970 g    DF .text	000000000000012b  VERS_1.0    TF_OperationGetAttrFloatList
00000000002d7de0 g    DF .text	0000000000000171  VERS_1.0    TF_OperationGetAttrStringList
00000000002dfb80 g    DF .text	0000000000000012  VERS_1.0    TF_GraphImportGraphDef
00000000002d39e0 g    DF .text	000000000000019e  VERS_1.0    TF_NewTensor
00000000002dde70 g    DF .text	00000000000001a9  VERS_1.0    TF_ImportGraphDefOptionsRemapControlDependency
00000000002e2200 g    DF .text	00000000000002fc  VERS_1.0    TF_SetAttrTensorShapeProto
00000000002d45b0 g    DF .text	0000000000000028  VERS_1.0    TF_SetDevice
00000000002d44e0 g    DF .text	00000000000000cf  VERS_1.0    TF_NewOperation
00000000002d6640 g    DF .text	0000000000000096  VERS_1.0    TF_OperationToNodeDef
00000000002e2500 g    DF .text	0000000000000103  VERS_1.0    TF_SetAttrValueProto
00000000002d4980 g    DF .text	000000000000000e  VERS_1.0    TF_OperationOpType
00000000002d5140 g    DF .text	00000000000000ce  VERS_1.0    TF_OperationGetAttrBool
00000000002d45e0 g    DF .text	000000000000000a  VERS_1.0    TF_AddInput
00000000002d49e0 g    DF .text	000000000000009e  VERS_1.0    TF_OperationInput
00000000002d52e0 g    DF .text	0000000000000177  VERS_1.0    TF_OperationGetAttrShape
00000000002d6e90 g    DF .text	000000000000027d  VERS_1.0    TF_OperationGetAttrShapeList
00000000002dc810 g    DF .text	000000000000006f  VERS_1.0    TF_ImportGraphDefOptionsAddReturnOutput
00000000002d3d30 g    DF .text	0000000000000028  VERS_1.0    TF_NewSessionOptions
00000000002d3e70 g    DF .text	00000000000000ac  VERS_1.0    TF_NewDeprecatedSession
00000000002d55f0 g    DF .text	000000000000021e  VERS_1.0    TF_OperationGetAttrTensorList
00000000002d69b0 g    DF .text	0000000000000097  VERS_1.0    TF_DeviceListMemoryBytes
00000000002d3fb0 g    DF .text	0000000000000038  VERS_1.0    TF_DeleteDeprecatedSession
00000000002d4970 g    DF .text	000000000000000e  VERS_1.0    TF_OperationName
00000000002d5b10 g    DF .text	0000000000000020  VERS_1.0    TF_ImportGraphDefOptionsNumReturnOutputs
00000000002d3b80 g    DF .text	000000000000005a  VERS_1.0    TF_AllocateTensor
00000000002d7690 g    DF .text	00000000000000a9  VERS_1.0    TF_OperationGetAttrValueProto
00000000002e14e0 g    DF .text	000000000000055f  VERS_1.0    TF_SessionRun
00000000002d9a40 g    DF .text	0000000000000138  VERS_1.0    TF_ColocateWith
00000000002d49c0 g    DF .text	000000000000000a  VERS_1.0    TF_OperationNumInputs
00000000002d37a0 g    DF .text	0000000000000077  VERS_1.0    TF_DeleteStatus
00000000002d44c0 g    DF .text	000000000000001f  VERS_1.0    TF_DeviceListCount
00000000002e0060 g    DF .text	00000000000004de  VERS_1.0    TF_SessionPRunSetup
00000000002d7f60 g    DF .text	00000000000001bb  VERS_1.0    TF_OperationGetAttrTensorShapeProtoList
00000000002e1fa0 g    DF .text	000000000000025e  VERS_1.0    TF_GetAllOpList
00000000002d4f90 g    DF .text	00000000000000ce  VERS_1.0    TF_OperationGetAttrInt
00000000002d7aa0 g    DF .text	0000000000000128  VERS_1.0    TF_OperationGetAttrBoolList
00000000002d4680 g    DF .text	000000000000003c  VERS_1.0    TF_SetAttrIntList
00000000002d5060 g    DF .text	00000000000000d1  VERS_1.0    TF_OperationGetAttrFloat
00000000002e2ba0 g    DF .text	0000000000000076  VERS_1.0    TF_FinishOperation
00000000002d5210 g    DF .text	00000000000000cd  VERS_1.0    TF_OperationGetAttrType
00000000002dd380 g    DF .text	0000000000000446  VERS_1.0    TF_AddGradients
0000000000000000 g    DO *ABS*	0000000000000000  VERS_1.0    VERS_1.0
00000000002d3ca0 g    DF .text	0000000000000008  VERS_1.0    TF_TensorType
00000000002d4b60 g    DF .text	0000000000000100  VERS_1.0    TF_OperationOutputConsumers
00000000002e37f0 g    DF .text	0000000000000e32  VERS_1.0    TF_FinishWhileHelper
00000000002d3cc0 g    DF .text	000000000000000e  VERS_1.0    TF_Dim
00000000002d9160 g    DF .text	0000000000000145  VERS_1.0    TF_GraphGetTensorNumDims
00000000002dbd00 g    DF .text	0000000000000363  VERS_1.0    TF_GraphGetTensorShape
00000000002d4280 g    DF .text	0000000000000020  VERS_1.0    TF_GetOpList
00000000002d3be0 g    DF .text	000000000000004b  VERS_1.0    TF_TensorMaybeMove
00000000002d49b0 g    DF .text	000000000000000a  VERS_1.0    TF_OperationOutputType
00000000002df900 g    DF .text	000000000000010a  VERS_1.0    TF_GraphToGraphDef
00000000002d4c60 g    DF .text	0000000000000059  VERS_1.0    TF_OperationNumControlInputs
00000000002d5900 g    DF .text	0000000000000028  VERS_1.0    TF_NewGraph
00000000002d7d00 g    DF .text	00000000000000e0  VERS_1.0    TF_OperationGetAttrTensorShapeProto
00000000002d48a0 g    DF .text	00000000000000cf  VERS_1.0    TF_SetAttrShape
00000000002d4400 g    DF .text	00000000000000bd  VERS_1.0    TF_DeprecatedSessionListDevices
00000000002db000 g    DF .text	00000000000001d6  VERS_1.0    TF_OperationInputListLength
00000000002d95d0 g    DF .text	00000000000002ba  VERS_1.0    TF_AddInputList
00000000002d3e20 g    DF .text	000000000000002c  VERS_1.0    TF_DeleteBuffer
00000000002d7bd0 g    DF .text	0000000000000127  VERS_1.0    TF_OperationGetAttrTypeList
00000000002d38d0 g    DF .text	0000000000000014  VERS_1.0    TF_GetCode
00000000002e4630 g    DF .text	0000000000000050  VERS_1.0    TF_FinishWhile
00000000002d49d0 g    DF .text	000000000000000a  VERS_1.0    TF_OperationInputType
00000000002d3cf0 g    DF .text	0000000000000012  VERS_1.0    TF_TensorData
00000000002d6790 g    DF .text	0000000000000107  VERS_1.0    TF_DeviceListName
00000000002db2a0 g    DF .text	000000000000008d  VERS_1.0    TF_DeleteGraph
00000000002df810 g    DF .text	00000000000000f0  VERS_1.0    TF_ExtendGraph
00000000002d42a0 g    DF .text	0000000000000023  VERS_1.0    TF_DeleteLibraryHandle
00000000002e1080 g    DF .text	0000000000000458  VERS_1.0    TF_PRun
00000000002d4740 g    DF .text	000000000000003f  VERS_1.0    TF_SetAttrBool
00000000002d3cd0 g    DF .text	0000000000000012  VERS_1.0    TF_TensorByteSize
00000000002db3a0 g    DF .text	00000000000000e6  VERS_1.0    TF_DeleteSession
00000000002ddcb0 g    DF .text	00000000000001b8  VERS_1.0    TF_ImportGraphDefOptionsAddInputMapping
00000000002d7840 g    DF .text	0000000000000127  VERS_1.0    TF_OperationGetAttrIntList
00000000002d3780 g    DF .text	0000000000000017  VERS_1.0    TF_NewStatus
00000000002d4cc0 g    DF .text	00000000000000f0  VERS_1.0    TF_OperationGetControlInputs
00000000002d5930 g    DF .text	00000000000000ef  VERS_1.0    TF_GraphNextOperation
00000000002d3770 g    DF .text	000000000000000d  VERS_1.0    TF_DataTypeSize
00000000002d3e50 g    DF .text	000000000000001f  VERS_1.0    TF_GetBuffer
00000000002dc240 g    DF .text	0000000000000337  VERS_1.0    TF_GraphSetTensorShape
00000000002d3c30 g    DF .text	0000000000000068  VERS_1.0    TF_DeleteTensor
00000000002d4e90 g    DF .text	00000000000000f8  VERS_1.0    TF_OperationGetControlOutputs
00000000002d4990 g    DF .text	000000000000000e  VERS_1.0    TF_OperationDevice
00000000002da130 g    DF .text	00000000000001b7  VERS_1.0    TF_SetAttrShapeList
00000000002d46c0 g    DF .text	000000000000003a  VERS_1.0    TF_SetAttrFloat
00000000002d5e70 g    DF .text	0000000000000012  VERS_1.0    TF_DeletePRunHandle
00000000002d5a20 g    DF .text	0000000000000071  VERS_1.0    TF_NewImportGraphDefOptions
00000000002d4640 g    DF .text	000000000000003a  VERS_1.0    TF_SetAttrInt
00000000002d3dc0 g    DF .text	0000000000000053  VERS_1.0    TF_NewBufferFromString
00000000002d7740 g    DF .text	00000000000000f5  VERS_1.0    TF_OperationGetAttrString
00000000002d3820 g    DF .text	00000000000000a3  VERS_1.0    TF_SetStatus
00000000002d3760 g    DF .text	000000000000000d  VERS_1.0    TF_Version
00000000002d38f0 g    DF .text	000000000000001e  VERS_1.0    TF_Message
00000000002d4700 g    DF .text	000000000000003c  VERS_1.0    TF_SetAttrFloatList
00000000002d5aa0 g    DF .text	0000000000000027  VERS_1.0    TF_ImportGraphDefOptionsSetPrefix
00000000002dfa10 g    DF .text	0000000000000164  VERS_1.0    TF_GraphImportGraphDefWithReturnOutputs
00000000002e1a40 g    DF .text	000000000000055f  VERS_1.0    TF_SessionPRun
00000000002d4340 g    DF .text	00000000000000bd  VERS_1.0    TF_SessionListDevices
00000000002d3d10 g    DF .text	000000000000001d  VERS_1.0    TF_StringEncodedSize
00000000002d8780 g    DF .text	00000000000006e1  VERS_1.0    TF_OperationGetAttrMetadata
00000000002d45f0 g    DF .text	000000000000000a  VERS_1.0    TF_AddControlInput
00000000002e0c20 g    DF .text	0000000000000458  VERS_1.0    TF_Run
00000000002d41b0 g    DF .text	00000000000000ce  VERS_1.0    TF_LoadLibrary
00000000002d4db0 g    DF .text	00000000000000d8  VERS_1.0    TF_OperationNumControlOutputs
00000000002d68a0 g    DF .text	0000000000000107  VERS_1.0    TF_DeviceListType
00000000002db390 g    DF .text	000000000000000a  VERS_1.0    TF_AbortWhile
00000000002d7290 g    DF .text	000000000000013b  VERS_1.0    TF_StringEncode
00000000002d3f20 g    DF .text	000000000000008c  VERS_1.0    TF_CloseDeprecatedSession
```

**Comment by d4l3k** [comment]
FYI, you need to modify `tensorflow/contrib/android/jni/version_script.lds`

```diff
VERS_1.0 {
  # Export JNI symbols.
  global:
    Java_*;
    JNI_OnLoad;
    JNI_OnUnload;
+    *TF_*;
+    *TFE_*;

  # Hide everything else.
  local:
    *;
};
```

https://github.com/luk-ai/tensorflow/commit/2814fa49f9cc1b36a2e3966352383aef982a49be#diff-df6db502bb3780540dc626b51c895c42

**Comment by BarMazal** [comment]
Hi all,
 I'm also facing issues when compiling the libraries for android.
My intention is to link the library (say libtensorflow_inference.so) to a native c code that runs from the shell with no Java involved.
When I compile the android libraries, the build succeed but the symbols are not like extern c symbols but more like c++ symbols with decorations. I can see the symbols by using readelf on the resulted library.

The build command I ran is:
bazel build  --config=android //tensorflow/examples/android:tensorflow_native_libs --cpu=armeabi-v7a --verbose_failures --copt=-g --copt=-fPIC
I also tried it without the -g and without the -fPIC with no change.

The c code did not link with the libraries, unless I also linked the code with 
-l:libandroid_tensorflow_inference_jni.lo

but still when I try to run the application it says:
CANNOT LINK EXECUTABLE: cannot find "libtensorflow_inference.so" from verneed[1] in DT_NEEDED list for "./dczoom_native"
page record for 0xf769203c was not found (block_size=16)

Although the library is in the path and I added LD_LIBRARY_PATH=./; before running the application.

Then I added the exports to tensorflow/contrib/android/jni/version_script.lds. Now it links without adding -l:libandroid_tensorflow_inference_jni.lo but still the symbols seems to be C++ mingled and not extern "C".

for example:
00d501ec  00003216 R_ARM_JUMP_SLOT   000bb355   TF_NewStatus
50: 000bb355    14 FUNC    GLOBAL DEFAULT   10 TF_NewStatus@@VERS_1.0

How did you produce the symbol table above? And what should I do to enable the executable succeed with loading the dynamic library in runtime?

Thanks.
 Guy.

**Comment by kevinan1** [comment]
@andrewharp  @d4l3k Think you , I got symbols, but I can't use it. 

    08-13 06:05:26.290 12497 12497 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: library "bazel-out/android-armeabi-v7a-opt/bin/tensorflow/contrib/android/libtensorflow_inference.so" not found
    08-13 06:05:26.290 12497 12497 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:989)
    08-13 06:05:26.290 12497 12497 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1562)

`arm-linux-androideabi-readelf -a libtensorflow_inference.so`

    Version definition section '.gnu.version_d' contains 2 entries:
      Addr: 0x00000000000052e0  Offset: 0x0052e0  Link: 2 (.dynstr)  000000: Rev: 1  Flags: BASE   
    Index: 1  Cnt: 1  Name: bazel-out/android-armeabi-v7a-opt/bin/tensorflow/contrib/android/libtensorflow_inference.so
      0x001c: Rev: 1  Flags: none  Index: 2  Cnt: 1  Name: VERS_1.0

    Version needs section '.gnu.version_r' contains 3 entries:
     Addr: 0x0000000000005318  Offset: 0x005318  Link: 2 (.dynstr)
      000000: Version: 1  File: libc.so  Cnt: 1
      0x0010:   Name: LIBC  Flags: none  Version: 3
      0x0020: Version: 1  File: libm.so  Cnt: 1
      0x0030:   Name: LIBC  Flags: none  Version: 4
      0x0040: Version: 1  File: libdl.so  Cnt: 1
      0x0050:   Name: LIBC  Flags: none  Version: 5

    Displaying notes found at file offset 0x00e062ac with length 0x0000001c:
      Owner                 Data size	Description
      GNU                  0x00000009	NT_GNU_GOLD_VERSION (gold version)
        Version: gold 1.11
    Attribute Section: aeabi
    File Attributes
      Tag_CPU_name: "ARM v7"
      Tag_CPU_arch: v7
      Tag_CPU_arch_profile: Application
      Tag_ARM_ISA_use: Yes
      Tag_THUMB_ISA_use: Thumb-2
      Tag_FP_arch: VFPv3
      Tag_Advanced_SIMD_arch: NEONv1
      Tag_ABI_PCS_GOT_use: GOT-indirect
      Tag_ABI_PCS_wchar_t: 4
      Tag_ABI_FP_denormal: Needed
      Tag_ABI_FP_exceptions: Needed
      Tag_ABI_FP_number_model: IEEE 754
      Tag_ABI_align_needed: 8-byte
      Tag_ABI_enum_size: int
      Tag_ABI_HardFP_use: SP and DP
      Tag_ABI_optimization_goals: Aggressive Speed
      Tag_CPU_unaligned_access: v6
      Tag_ABI_FP_16bit_format: IEEE 754
      Tag_Virtualization_use: TrustZone

    Name: bazel-out/android-armeabi-v7a-opt/bin/tensorflow/contrib/android/libtensorflow_inference.so

I think that's a mistake
