### ISSUE TITLE
Crash when load Fine-tune model on Android

### ISSUE THREAD

**Issue by Sixigma** [tensorflow/tensorflow#13030]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 1.3.0
- **Python version**: 2.7.12
- **Bazel version (if compiling from source)**: 0.5.4
- **CUDA/cuDNN version**:  8.0.61
- **GPU model and memory**: NVIDIA Corporation Device 1b06
- **Exact command to reproduce**: 

How I do Fine-tune : 
```

# Convert imagenet data to TFrecord ( No bounding box , just for classification ) 
python build_image_data.py \
--train_directory='imagenet/train' \
--validation_directory='imagenet/train' \
--labels_file='imagenet/labels.txt' \
--output_directory='imagenet/tfrecord' 

# Train from checkpoint
python train_image_classifier.py \
    --dataset_dir=.../imagenet/tfrecord \
    --train_dir=.../imagenet/train_logs \
    --checkpoint_path=.../checkpoint/mobilenet_v1_0.50_224.ckpt \
    --model_name=mobilenet_v1_050 \
    --dataset_name=flowers \                       ( _NUM_CLASSES and sizes has been modified )
    --dataset_split_name=train \
    --max_number_of_steps=10000 \
    --checkpoint_exclude_scopes=MobilenetV1/Logits \
    --trainable_scopes=MobilenetV1/Logits \

# Produce .pb file (use .pbtxt)
bazel-bin/tensorflow/python/tools/freeze_graph \
--input_graph=.../imagenet/train_logs/graph.pbtxt \
--input_checkpoint=.../imagenet/train_logs/model.ckpt-10000 \
--output_graph=.../imagenet/train_logs/frozen_graph.pb \
--output_node_names=MobilenetV1/Predictions/Reshape_1

# Removes parts of a graph that are only needed for training
bazel-bin/tensorflow/python/tools/optimize_for_inference \
--input=.../imagenet/train_logs/frozen_graph.pb \
--output=.../imagenet/train_logs/optimized_graph.pb \
--frozen_graph=True \
--input_names='prefetch_queue/fifo_queue' \
--output_names='MobilenetV1/Predictions/Reshape_1'

```
### Describe the problem

Hi , I am doing some fine-tune with mobilenet , I got some trouble at beginning since the input node " prefetch_queue/fifo_queue " , which Op "FIFOQueueV2" is disabled on Android , but I think it's okay  after using "bazel-bin/tensorflow/python/tools/optimize_for_inference" . ( I am not sure about it or I still need to customize my own TF library like mentioned [here](https://github.com/tensorflow/tensorflow/issues/8454) ? )

But now there is a new problem , after modify the parameter at "ClassifierActivity.java" like this : 
( input_name and output_name is from summarize_graph tool )
```

  private static final int INPUT_SIZE = 224;
  private static final int IMAGE_MEAN = 117;
  private static final float IMAGE_STD = 1;
  private static final String INPUT_NAME = "prefetch_queue/fifo_queue";
  private static final String OUTPUT_NAME = "MobilenetV1/Predictions/Reshape_1";

  private static final String MODEL_FILE = "file:///android_asset/tensorflow_inception_graph.pb";
  private static final String LABEL_FILE =
      "file:///android_asset/imagenet_comp_graph_label_strings.txt";

```

and implement the demo on android , the TF Classify can be launched , but crash when press the volume key to turn on the debug mode. 

the crash prints the following log :
### Source code / logs

Error Message from adb logcat
```
E/InputEventSender( 4197): Exception dispatching finished signal.
E/MessageQueue-JNI( 4197): Exception in MessageQueue callback: handleReceiveCallback
E/MessageQueue-JNI( 4197): java.lang.NullPointerException: Attempt to invoke interface method 'void org.tensorflow.demo.Classifier.enableStatLogging(boolean)' on a null object reference
E/MessageQueue-JNI( 4197):      at org.tensorflow.demo.ClassifierActivity.onSetDebug(ClassifierActivity.java:183)
E/MessageQueue-JNI( 4197):      at org.tensorflow.demo.CameraActivity.onKeyDown(CameraActivity.java:381)
E/MessageQueue-JNI( 4197):      at android.view.KeyEvent.dispatch(KeyEvent.java:2758)
E/MessageQueue-JNI( 4197):      at android.app.Activity.dispatchKeyEvent(Activity.java:2755)
E/MessageQueue-JNI( 4197):      at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2380)
E/MessageQueue-JNI( 4197):      at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4556)
E/MessageQueue-JNI( 4197):      at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4512)
E/MessageQueue-JNI( 4197):      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4034)
E/MessageQueue-JNI( 4197):      at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4087)
E/MessageQueue-JNI( 4197):      at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4053)
E/MessageQueue-JNI( 4197):      at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4190)
E/MessageQueue-JNI( 4197):      at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4061)
E/MessageQueue-JNI( 4197):      at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4247)
E/MessageQueue-JNI( 4197):      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4034)
E/MessageQueue-JNI( 4197):      at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4087)
E/MessageQueue-JNI( 4197):      at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4053)
E/MessageQueue-JNI( 4197):      at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4061)
E/MessageQueue-JNI( 4197):      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4034)
E/MessageQueue-JNI( 4197):      at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4087)
E/MessageQueue-JNI( 4197):      at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4053)
E/MessageQueue-JNI( 4197):      at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4223)
E/MessageQueue-JNI( 4197):      at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4393)
E/MessageQueue-JNI( 4197):      at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2285)
E/MessageQueue-JNI( 4197):      at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1909)
E/MessageQueue-JNI( 4197):      at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1900)
E/MessageQueue-JNI( 4197):      at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2262)
E/MessageQueue-JNI( 4197):      at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
E/MessageQueue-JNI( 4197):      at android.os.MessageQueue.nativePollOnce(Native Method)
E/MessageQueue-JNI( 4197):      at android.os.MessageQueue.next(MessageQueue.java:148)
E/MessageQueue-JNI( 4197):      at android.os.Looper.loop(Looper.java:151)
E/MessageQueue-JNI( 4197):      at android.app.ActivityThread.main(ActivityThread.java:5631)
E/MessageQueue-JNI( 4197):      at java.lang.reflect.Method.invoke(Native Method)
E/MessageQueue-JNI( 4197):      at java.lang.reflect.Method.invoke(Method.java:372)
E/MessageQueue-JNI( 4197):      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
E/MessageQueue-JNI( 4197):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)
E/AndroidRuntime( 4197): FATAL EXCEPTION: main
E/AndroidRuntime( 4197): Process: org.tensorflow.demo, PID: 4197
E/AndroidRuntime( 4197): java.lang.NullPointerException: Attempt to invoke interface method 'void org.tensorflow.demo.Classifier.enableStatLogging(boolean)' on a null object reference
E/AndroidRuntime( 4197):        at org.tensorflow.demo.ClassifierActivity.onSetDebug(ClassifierActivity.java:183)
E/AndroidRuntime( 4197):        at org.tensorflow.demo.CameraActivity.onKeyDown(CameraActivity.java:381)
E/AndroidRuntime( 4197):        at android.view.KeyEvent.dispatch(KeyEvent.java:2758)
E/AndroidRuntime( 4197):        at android.app.Activity.dispatchKeyEvent(Activity.java:2755)
E/AndroidRuntime( 4197):        at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2380)
E/AndroidRuntime( 4197):        at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4556)
E/AndroidRuntime( 4197):        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4512)
E/AndroidRuntime( 4197):        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4034)
E/AndroidRuntime( 4197):        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4087)
E/AndroidRuntime( 4197):        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4053)
E/AndroidRuntime( 4197):        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4190)
E/AndroidRuntime( 4197):        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4061)
E/AndroidRuntime( 4197):        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4247)
E/AndroidRuntime( 4197):        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4034)
E/AndroidRuntime( 4197):        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4087)
E/AndroidRuntime( 4197):        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4053)
E/AndroidRuntime( 4197):        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4061)
E/AndroidRuntime( 4197):        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4034)
E/AndroidRuntime( 4197):        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4087)
E/AndroidRuntime( 4197):        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4053)
E/AndroidRuntime( 4197):        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4223)
E/AndroidRuntime( 4197):        at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4393)
E/AndroidRuntime( 4197):        at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2285)
E/AndroidRuntime( 4197):        at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1909)
E/AndroidRuntime( 4197):        at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1900)
E/AndroidRuntime( 4197):        at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2262)
E/AndroidRuntime( 4197):        at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
E/AndroidRuntime( 4197):        at android.os.MessageQueue.nativePollOnce(Native Method)
E/AndroidRuntime( 4197):        at android.os.MessageQueue.next(MessageQueue.java:148)
E/AndroidRuntime( 4197):        at android.os.Looper.loop(Looper.java:151)
E/AndroidRuntime( 4197):        at android.app.ActivityThread.main(ActivityThread.java:5631)
E/AndroidRuntime( 4197):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 4197):        at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 4197):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
E/AndroidRuntime( 4197):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)

```

I am not sure which part result in this , if any further information is needed , please tell me , thank you !

**Comment by Sixigma** [comment]
Sorry , there is something weird , it seems like the crash happens when TF Classify launch : 

Here is the log when app is implemented : 
```

E/tensorflow(24851): CameraActivity: Exception!
E/tensorflow(24851): java.lang.RuntimeException: Failed to load model from 'file:///android_asset/tensorflow_inception_graph.pb'
E/tensorflow(24851):    at org.tensorflow.contrib.android.TensorFlowInferenceInterface.<init>(TensorFlowInferenceInterface.java:104)
E/tensorflow(24851):    at org.tensorflow.demo.TensorFlowImageClassifier.create(TensorFlowImageClassifier.java:103)
E/tensorflow(24851):    at org.tensorflow.demo.ClassifierActivity.onPreviewSizeChosen(ClassifierActivity.java:107)
E/tensorflow(24851):    at org.tensorflow.demo.CameraActivity.onPreviewFrame(CameraActivity.java:111)
E/tensorflow(24851):    at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1274)
E/tensorflow(24851):    at android.os.Handler.dispatchMessage(Handler.java:111)
E/tensorflow(24851):    at android.os.Looper.loop(Looper.java:194)
E/tensorflow(24851):    at android.app.ActivityThread.main(ActivityThread.java:5631)
E/tensorflow(24851):    at java.lang.reflect.Method.invoke(Native Method)
E/tensorflow(24851):    at java.lang.reflect.Method.invoke(Method.java:372)
E/tensorflow(24851):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
E/tensorflow(24851):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)
E/tensorflow(24851): Caused by: java.io.IOException: Not a valid TensorFlow Graph serialization: Invalid GraphDef
E/tensorflow(24851):    at org.tensorflow.contrib.android.TensorFlowInferenceInterface.loadGraph(TensorFlowInferenceInterface.java:511)
E/tensorflow(24851):    at org.tensorflow.contrib.android.TensorFlowInferenceInterface.<init>(TensorFlowInferenceInterface.java:96)
E/tensorflow(24851):    ... 11 more

```

So this problem still seems like  all about 'FIFOQueueV2'  , I will try to fix it up , and if any changes I will report again.

**Comment by Sixigma** [comment]
I try again using the origin model from https://storage.googleapis.com/download.tensorflow.org/models/...
But the log still prints like above , and crash when turn on debug mode.

I wonder is it possible result from the recent commit of tensorflow ? I update local repo yesterday.
Or any other idea ?

**Comment by Sixigma** [comment]
Here is some progress : 
I recover TensorFlowInferenceInterface.java at tensorflow/contrib/android/java/org/tensorflow/contrib/android/ to version on Jul 29 , the original mobilenet works well now , no longer Failed to load model from 'file:///android_asset/tensorflow_inception_graph.pb' .

But still , the fine-tune model crash when the debug mode turn on.
The error log is the same as "java.lang.NullPointerException: Attempt to invoke interface method 'void org.tensorflow.demo.Classifier.enableStatLogging(boolean)' on a null object reference" , I guess which is from "FIFOQueueV2" .

**Comment by vinishg** [comment]
Did you found any solution for crash ?

**Comment by aReaSa** [comment]
Did you found any solution for crash ?

**Comment by vinishg** [comment]
yes, check this [link](https://github.com/tensorflow/tensorflow/issues/16752)

**Comment by sthuthyraj** [comment]
Still i am facing the issue. Kindly help
