### ISSUE TITLE
Python import error, undefined symbol: secure_getenv

### ISSUE THREAD

**Issue by digitalsword** [tensorflow/tensorflow#1307]
I got python import error, undefined symbol: secure_getenv

Operating System:
Redhat 6.7

Installed from sources using gcc 4.8 (I am using gcc 4.8 installed in a custom path since the default gcc is too old):
commit b88971051fbc49fa1e0b91ec1b0b60defa11697e
Date:   Fri Feb 26 05:08:35 2016 -0800

```
Python 2.7.11 |Anaconda 2.2.0 (64-bit)| (default, Dec  6 2015, 18:08:32)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import tensorflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nfs/m01/anaconda/lib/python2.7/site-packages/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/nfs/m01/anaconda/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow import contrib
  File "/nfs/m01/anaconda/lib/python2.7/site-packages/tensorflow/contrib/__init__.py", line 23, in <module>
    from tensorflow.contrib import layers
  File "/nfs/m01/anaconda/lib/python2.7/site-packages/tensorflow/contrib/layers/__init__.py", line 67, in <module>
    from tensorflow.contrib.layers.python.framework.tensor_util import *
  File "/nfs/m01/anaconda/lib/python2.7/site-packages/tensorflow/contrib/layers/python/framework/tensor_util.py", line 21, in <module>
    from tensorflow.python.framework.ops import Tensor
  File "/nfs/m01/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 39, in <module>
    from tensorflow.python.framework import versions
  File "/nfs/m01/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/versions.py", line 22, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/nfs/m01/anaconda/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 25, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/nfs/m01/anaconda/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 21, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
ImportError: /nfs/m01/anaconda/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so: undefined symbol: secure_getenv
```

If I do ldd ~/anaconda/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so
```
	linux-vdso.so.1 =>  (0x00007ffd393ef000)
	libcudart.so.7.5 => /usr/local/cuda/7.5.18/lib64/libcudart.so.7.5 (0x00002ad591b36000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00002ad591dc3000)
	libm.so.6 => /lib64/libm.so.6 (0x00002ad591fc7000)
	libz.so.1 => /lib64/libz.so.1 (0x00002ad59224c000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00002ad592462000)
	libstdc++.so.6 => /usr/local/gcc/4.8.4/lib64/libstdc++.so.6 (0x00002ad59267f000)
	libgcc_s.so.1 => /usr/local/gcc/4.8.4/lib64/libgcc_s.so.1 (0x00002ad592989000)
	libc.so.6 => /lib64/libc.so.6 (0x00002ad592b9f000)
	/lib64/ld-linux-x86-64.so.2 (0x0000003a39400000)
	librt.so.1 => /lib64/librt.so.1 (0x00002ad592f33000)
```

**Comment by plazonic** [comment]
The problem is in the external dependency gprc which uses secure_getenv which only appeared in glibc 2.17 - https://sourceware.org/glibc/wiki/Tips_and_Tricks/secure_getenv

Turns out that gprc can be told to try to use other symbols as well but it needs the -DGPR_BACKWARDS_COMPATIBILITY_MODE option, e.g. I've managed to compile CPU only version by doing this:
bazel build --linkopt '-lrt' --copt '-DGPR_BACKWARDS_COMPATIBILITY_MODE' -c opt //tensorflow/tools/pip_package:build_pip_package 
It would be more correct to add that option only to gprc but I am far from fluent in bazel-ize.

**Comment by rdipietro** [comment]
I can confirm that this works with the GPU version. Thanks very much. Including `EXTRA_BAZEL_ARGS` and the build command below for completeness. Some flags were included simply because they were suggested in other threads to circumvent other issues, but notice `--conlyopt="-std=c99"`. It wouldn't compile for me without this.

```
export EXTRA_BAZEL_ARGS='-s --verbose_failures --ignore_unsupported_sandboxing --genrule_strategy=standalone --spawn_strategy=standalone --jobs 4'

bazel build --linkopt '-lrt' --copt="-DGPR_BACKWARDS_COMPATIBILITY_MODE" --conlyopt="-std=c99" -c opt --config=cuda --verbose_failures --genrule_strategy=standalone --spawn_strategy=standalone //tensorflow/tools/pip_package:build_pip_package
```

**Comment by digitalsword** [comment]
I confirm @rdipietro's approach works. I was building a GPU version. CPU training worked for me. However, I am not able to use k40m GPU for GPU training.

@rdipietro What's your GPU model? What is your operating system?

```
++ python cifar10_train.py
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so.7.5 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so.7.5 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcudnn.so.4 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so.7.5 locally
Filling queue with 20000 CIFAR images before starting to train. This will take a few minutes.
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 0 with properties: 
name: Tesla K40m
major: 3 minor: 5 memoryClockRate (GHz) 0.745
pciBusID 0000:08:00.0
Total memory: 11.25GiB
Free memory: 11.15GiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:126] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:718] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla K40m, pci bus id: 0000:08:00.0)
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:53] Creating bin of max chunk size 256B
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:53] Creating bin of max chunk size 512B
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:53] Creating bin of max chunk size 1.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:53] Creating bin of max chunk size 2.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:53] Creating bin of max chunk size 4.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:53] Creating bin of max chunk size 8.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:53] Creating bin of max chunk size 16.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:53] Creating bin of max chunk size 32.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:53] Creating bin of max chunk size 64.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:53] Creating bin of max chunk size 128.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:53] Creating bin of max chunk size 256.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:53] Creating bin of max chunk size 512.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:53] Creating bin of max chunk size 1.00MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:53] Creating bin of max chunk size 2.00MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:53] Creating bin of max chunk size 4.00MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:53] Creating bin of max chunk size 8.00MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:53] Creating bin of max chunk size 16.00MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:53] Creating bin of max chunk size 32.00MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:53] Creating bin of max chunk size 64.00MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:53] Creating bin of max chunk size 128.00MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:53] Creating bin of max chunk size 256.00MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:107] Allocating 10.60GiB bytes.
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:118] GPU 0 memory begins at 0x13047a0000 extends to 0x15aaa4019a
F tensorflow/stream_executor/cuda/cuda_driver.cc:383] Check failed: CUDA_SUCCESS == dynload::cuCtxSetCurrent(context) (0 vs. 216)
./run.sh: line 4: 33880 Aborted                 python cifar10_train.py

```

**Comment by rdipietro** [comment]
Odd. I had only done a stupidly simple test before (`x = tf.Variable(1.0)` ... `print(sess.run(x))`), so I was worried it wouldn't work for me either, but it does:

```
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:107] Allocating 10.57GiB bytes.
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:118] GPU 0 memory begins at 0x2303ee0000 extends to 0x25a8ae0e67
2016-03-04 12:37:58.181180: step 0, loss = 4.68 (3.8 examples/sec; 34.059 sec/batch)
2016-03-04 12:38:01.405984: step 10, loss = 4.65 (502.8 examples/sec; 0.255 sec/batch)
2016-03-04 12:38:03.791843: step 20, loss = 4.64 (533.8 examples/sec; 0.240 sec/batch)
2016-03-04 12:38:06.084344: step 30, loss = 4.61 (571.2 examples/sec; 0.224 sec/batch)
```

My specs:

```
CentOS 6.7
gcc 4.8.2
Tesla K80
cuda 7.0
cudnn 6.5
compute capability 3.5
NVIDIA-SMI 352.63     Driver Version: 352.63
```

**Comment by digitalsword** [comment]
@rdipietro Thanks for your info. I guess it's an issue specific with k40m. I currently can only use CPU for training. It is interesting that the CPU speed is about half of your GPU speed. I thought GPU is much faster than CPU. My CPU is: Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz

```
++ python cifar10_train.py
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so.7.5 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so.7.5 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcudnn.so.4 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so.7.5 locally
Filling queue with 20000 CIFAR images before starting to train. This will take a few minutes.
E tensorflow/stream_executor/cuda/cuda_driver.cc:481] failed call to cuInit: CUDA_ERROR_NO_DEVICE
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:114] retrieving CUDA diagnostic information for host: r0215.ten.osc.edu
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:121] hostname: r0215.ten.osc.edu
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:146] libcuda reported version is: 352.39
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:257] driver version file contents: """NVRM version: NVIDIA UNIX x86_64 Kernel Module  352.39  Fri Aug 14 18:09:10 PDT 2015
GCC version:  gcc version 4.4.7 20120313 (Red Hat 4.4.7-16) (GCC) 
"""
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:150] kernel reported version is: 352.39
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:226] kernel version seems to match DSO: 352.39
I tensorflow/core/common_runtime/gpu/gpu_init.cc:126] DMA: 
2016-03-04 13:35:25.498518: step 0, loss = 4.67 (7.9 examples/sec; 16.105 sec/batch)
2016-03-04 13:35:32.403652: step 10, loss = 4.66 (212.1 examples/sec; 0.604 sec/batch)
2016-03-04 13:35:38.377604: step 20, loss = 4.64 (203.0 examples/sec; 0.631 sec/batch)
2016-03-04 13:35:44.478986: step 30, loss = 4.62 (215.6 examples/sec; 0.594 sec/batch)
2016-03-04 13:35:50.481260: step 40, loss = 4.60 (218.4 examples/sec; 0.586 sec/batch)
2016-03-04 13:35:56.542513: step 50, loss = 4.58 (210.5 examples/sec; 0.608 sec/batch)
2016-03-04 13:36:02.315769: step 60, loss = 4.55 (205.9 examples/sec; 0.622 sec/batch)
2016-03-04 13:36:08.432561: step 70, loss = 4.54 (209.7 examples/sec; 0.610 sec/batch)
2016-03-04 13:36:14.322653: step 80, loss = 4.52 (216.5 examples/sec; 0.591 sec/batch)

```

**Comment by rdipietro** [comment]
Hmm. Thanks for posting this. Right now I run multiple RNN experiments with multiple jobs on a single GPU, but this saturates the GPU pretty quickly. I'll see how things go with CPUs.

**Comment by digitalsword** [comment]
@rdipietro Tensorflow should scale to mutiple CPU cores. I have 10 CPU cores (20 cores by hyperthreading) and I find each core has utilization around 50% (shown in htop command). So I am assuming all cores are used.

**Comment by rdipietro** [comment]
I tried this out. Just to report back, if I use CPUs instead of a GPU, the RNN training is about 10x slower.

**Comment by digitalsword** [comment]
@rdipietro What's the largest RNN you are able to run? I am stuck at 512 x 3 layers LSTM on Titan X (12 GB GPU memory).

**Comment by rdipietro** [comment]
When you say stuck, what exactly happens? I can't imagine memory being even close to exhausted unless your batch size is enormous, or if your inputs are huge or something. (I don't think 3x512 layers is the limiting factor.)

That said, I don't know how high I can go. In my application I went with 1x256 because two layers didn't improve val performance and neither did 512 hidden units.

**Comment by rdipietro** [comment]
Also take a look at the input/output projection layers

**Comment by digitalsword** [comment]
@rdipietro Thanks. I mean I can run 512x3, but I would like to run 1024x4 and 1024x5. My batch size is 256. Shrinking batch size to 32, I still can't run 1024x4. So I was wondering if anyone has managed to run 1024x4 or larger. Mabybe model parallelism on multiple GPUs would help.

**Comment by rdipietro** [comment]
I'm wondering what you mean by "can't run." I doubt it's memory issue?. Can check this by running `nvidia-smi` while you train. If training is simply failing, maybe it's more likely that your gradients have gone to 0 or inf?

**Comment by digitalsword** [comment]
@rdipietro Sorry. By "can't run" I mean I saw out of memory errors from tensorflow.

**Comment by rdipietro** [comment]
Oh. No clue..

**Comment by newbornking999** [comment]
digitalsword did u sloved ur problem? i got same error

**Comment by girving** [comment]
@mrry: Is there any easy to get `DGPR_BACKWARDS_COMPATIBILITY_MODE` into our grpc build in a suitable version dependent way?

**Comment by mrry** [comment]
@girving: Turns out it's quite easy: #2697.
