### ISSUE TITLE
No OpKernel was registered to support Op 'QuantizeV2'

### ISSUE THREAD

**Issue by eyaler** [tensorflow/tensorflow#13096]
I was able to build tf 1.3 quantize_graph on windows 10 64 using bazel 0.53 and cuda 8 (i could not build it without cuda). when i try to run it i get:
No OpKernel was registered to support Op 'QuantizeV2' with these attrs.

bazel-bin\tensorflow\tools\quantization\quantize_graph --input d:/export/saved_model.pb --output_node_names my_output --output d:/export/saved_model_quant.pb --mode=eightbit

2017-09-17 10:48:28.292364: W C:\tools\msys64\tmp\_bazel_user\8rsmy-kr\execroot\org_tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-09-17 10:48:28.292529: W C:\tools\msys64\tmp\_bazel_user\8rsmy-kr\execroot\org_tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
Traceback (most recent call last):
  File "\\?\C:\Users\user\AppData\Local\Temp\Bazel.runfiles_5goewho4\runfiles\org_tensorflow\tensorflow\python\client\session.py", line 1327, in _do_call
    return fn(*args)
  File "\\?\C:\Users\user\AppData\Local\Temp\Bazel.runfiles_5goewho4\runfiles\org_tensorflow\tensorflow\python\client\session.py", line 1297, in _run_fn
    self._extend_graph()
  File "\\?\C:\Users\user\AppData\Local\Temp\Bazel.runfiles_5goewho4\runfiles\org_tensorflow\tensorflow\python\client\session.py", line 1358, in _extend_graph
    self._session, graph_def.SerializeToString(), status)
  File "C:\Anaconda3\lib\contextlib.py", line 88, in __exit__
    next(self.gen)
  File "\\?\C:\Users\user\AppData\Local\Temp\Bazel.runfiles_5goewho4\runfiles\org_tensorflow\tensorflow\python\framework\errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'QuantizeV2' with these attrs.  Registered devices: [CPU], Registered kernels:
  <no registered kernels>

         [[Node: QuantizeV2 = QuantizeV2[T=DT_QUINT8, mode="MIN_FIRST"](QuantizeV2/input, QuantizeV2/min_range, QuantizeV2/max_range)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "\\?\C:\Users\user\AppData\Local\Temp\Bazel.runfiles_5goewho4\runfiles\org_tensorflow\tensorflow\tools\quantization\quantize_graph.py", line 1301, in <module>
    app.run()
  File "\\?\C:\Users\user\AppData\Local\Temp\Bazel.runfiles_5goewho4\runfiles\org_tensorflow\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "\\?\C:\Users\user\AppData\Local\Temp\Bazel.runfiles_5goewho4\runfiles\org_tensorflow\tensorflow\tools\quantization\quantize_graph.py", line 1292, in main
    output_graph = rewriter.rewrite(FLAGS.output_node_names.split(","))
  File "\\?\C:\Users\user\AppData\Local\Temp\Bazel.runfiles_5goewho4\runfiles\org_tensorflow\tensorflow\tools\quantization\quantize_graph.py", line 420, in rewrite
    self.eightbitize_nodes_recursively(output_node)
  File "\\?\C:\Users\user\AppData\Local\Temp\Bazel.runfiles_5goewho4\runfiles\org_tensorflow\tensorflow\tools\quantization\quantize_graph.py", line 600, in eightbitize_nodes_recursively
    self.eightbitize_nodes_recursively(input_node)
  File "\\?\C:\Users\user\AppData\Local\Temp\Bazel.runfiles_5goewho4\runfiles\org_tensorflow\tensorflow\tools\quantization\quantize_graph.py", line 600, in eightbitize_nodes_recursively
    self.eightbitize_nodes_recursively(input_node)
  File "\\?\C:\Users\user\AppData\Local\Temp\Bazel.runfiles_5goewho4\runfiles\org_tensorflow\tensorflow\tools\quantization\quantize_graph.py", line 600, in eightbitize_nodes_recursively
    self.eightbitize_nodes_recursively(input_node)
  [Previous line repeated 90 more times]
  File "\\?\C:\Users\user\AppData\Local\Temp\Bazel.runfiles_5goewho4\runfiles\org_tensorflow\tensorflow\tools\quantization\quantize_graph.py", line 632, in eightbitize_nodes_recursively
    for n in quantize_weight_eightbit(current_node, b"MIN_FIRST"):
  File "\\?\C:\Users\user\AppData\Local\Temp\Bazel.runfiles_5goewho4\runfiles\org_tensorflow\tensorflow\tools\quantization\quantize_graph.py", line 299, in quantize_weight_eightbit
    quint8_tensor = quantize_op[0].eval()
  File "\\?\C:\Users\user\AppData\Local\Temp\Bazel.runfiles_5goewho4\runfiles\org_tensorflow\tensorflow\python\framework\ops.py", line 541, in eval
    return _eval_using_default_session(self, feed_dict, self.graph, session)
  File "\\?\C:\Users\user\AppData\Local\Temp\Bazel.runfiles_5goewho4\runfiles\org_tensorflow\tensorflow\python\framework\ops.py", line 4085, in _eval_using_default_session
    return session.run(tensors, feed_dict)
  File "\\?\C:\Users\user\AppData\Local\Temp\Bazel.runfiles_5goewho4\runfiles\org_tensorflow\tensorflow\python\client\session.py", line 895, in run
    run_metadata_ptr)
  File "\\?\C:\Users\user\AppData\Local\Temp\Bazel.runfiles_5goewho4\runfiles\org_tensorflow\tensorflow\python\client\session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "\\?\C:\Users\user\AppData\Local\Temp\Bazel.runfiles_5goewho4\runfiles\org_tensorflow\tensorflow\python\client\session.py", line 1321, in _do_run
    options, run_metadata)
  File "\\?\C:\Users\user\AppData\Local\Temp\Bazel.runfiles_5goewho4\runfiles\org_tensorflow\tensorflow\python\client\session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'QuantizeV2' with these attrs.  Registered devices: [CPU], Registered kernels:
  <no registered kernels>

         [[Node: QuantizeV2 = QuantizeV2[T=DT_QUINT8, mode="MIN_FIRST"](QuantizeV2/input, QuantizeV2/min_range, QuantizeV2/max_range)]]

Caused by op 'QuantizeV2', defined at:
  File "\\?\C:\Users\user\AppData\Local\Temp\Bazel.runfiles_5goewho4\runfiles\org_tensorflow\tensorflow\tools\quantization\quantize_graph.py", line 1301, in <module>
    app.run()
  File "\\?\C:\Users\user\AppData\Local\Temp\Bazel.runfiles_5goewho4\runfiles\org_tensorflow\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "\\?\C:\Users\user\AppData\Local\Temp\Bazel.runfiles_5goewho4\runfiles\org_tensorflow\tensorflow\tools\quantization\quantize_graph.py", line 1292, in main
    output_graph = rewriter.rewrite(FLAGS.output_node_names.split(","))
  File "\\?\C:\Users\user\AppData\Local\Temp\Bazel.runfiles_5goewho4\runfiles\org_tensorflow\tensorflow\tools\quantization\quantize_graph.py", line 420, in rewrite
    self.eightbitize_nodes_recursively(output_node)
  File "\\?\C:\Users\user\AppData\Local\Temp\Bazel.runfiles_5goewho4\runfiles\org_tensorflow\tensorflow\tools\quantization\quantize_graph.py", line 600, in eightbitize_nodes_recursively
    self.eightbitize_nodes_recursively(input_node)
  File "\\?\C:\Users\user\AppData\Local\Temp\Bazel.runfiles_5goewho4\runfiles\org_tensorflow\tensorflow\tools\quantization\quantize_graph.py", line 600, in eightbitize_nodes_recursively
    self.eightbitize_nodes_recursively(input_node)
  File "\\?\C:\Users\user\AppData\Local\Temp\Bazel.runfiles_5goewho4\runfiles\org_tensorflow\tensorflow\tools\quantization\quantize_graph.py", line 600, in eightbitize_nodes_recursively
    self.eightbitize_nodes_recursively(input_node)
  [Previous line repeated 90 more times]
  File "\\?\C:\Users\user\AppData\Local\Temp\Bazel.runfiles_5goewho4\runfiles\org_tensorflow\tensorflow\tools\quantization\quantize_graph.py", line 632, in eightbitize_nodes_recursively
    for n in quantize_weight_eightbit(current_node, b"MIN_FIRST"):
  File "\\?\C:\Users\user\AppData\Local\Temp\Bazel.runfiles_5goewho4\runfiles\org_tensorflow\tensorflow\tools\quantization\quantize_graph.py", line 298, in quantize_weight_eightbit
    mode=quantization_mode)
  File "\\?\C:\Users\user\AppData\Local\Temp\Bazel.runfiles_5goewho4\runfiles\org_tensorflow\tensorflow\python\ops\gen_array_ops.py", line 2381, in quantize_v2
    mode=mode, name=name)
  File "\\?\C:\Users\user\AppData\Local\Temp\Bazel.runfiles_5goewho4\runfiles\org_tensorflow\tensorflow\python\framework\op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "\\?\C:\Users\user\AppData\Local\Temp\Bazel.runfiles_5goewho4\runfiles\org_tensorflow\tensorflow\python\framework\ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "\\?\C:\Users\user\AppData\Local\Temp\Bazel.runfiles_5goewho4\runfiles\org_tensorflow\tensorflow\python\framework\ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): No OpKernel was registered to support Op 'QuantizeV2' with these attrs.  Registered devices: [CPU], Registered kernels:
  <no registered kernels>

         [[Node: QuantizeV2 = QuantizeV2[T=DT_QUINT8, mode="MIN_FIRST"](QuantizeV2/input, QuantizeV2/min_range, QuantizeV2/max_range)]]

**Comment by bignamehyp** [comment]
Please upgrade to tensorflow 1.4 to see if you can reproduce this issue. Thanks.

**Comment by eyaler** [comment]
I tried to run a quantized model on windows with tf 1.4 and got:
No OpKernel was registered to support Op 'Dequantize' 

could you point me out to references showing that quantization was added on windows in 1.4?

**Comment by eyaler** [comment]
could you point me out to what was changed in this regard in 1.4?

**Comment by shinya321** [comment]
Does anyone solve this error?
I am in trouble the same problem although my version 1.4.0

**Comment by holy7water** [comment]
I got same problem. Is there anyone who can advice to solve this problem?

-------------------------------
No OpKernel was registered to support Op 'QuantizeV2' with these attrs.  Registered devices: [CPU,GPU], Registered kernels:  <no registered kernels>

**Comment by xiaoyug0901** [comment]
Has anyone solved this problem? Thank you~

**Comment by jackyLens** [comment]
This is a bug in Windows environment. If you run your command in Ubuntu or Centos, it will be OK.

**Comment by gy12346123** [comment]
In the 'tensorflow/core/BUILD' file, search for 'name = "all_kernels_impl",', the '//tensorflow/core/kernels:quantized_ops' is set to 'if_not_windows', change it into deps. Or use mkl.

**Comment by sushreebarsa** [comment]
@eyaler You are using an older version of tensorflow (1.x) which is not actively supported now, please verify it on the latest TF version 2.9.0 and let us know in case you face any errors. Thank you!

**Comment by eyaler** [comment]
@sushreebarsa thanks but the issue is from sep 2017...

**Comment by sushreebarsa** [comment]
@eyaler Sorry for the late response!
Could you please let us know if this issue still persists on latest TF versions?
Thank you!

**Comment by eyaler** [comment]
@sushreebarsa no worries. i no longer have access to the original setup. and even if i had, the upgrade path would be difficult

**Comment by sushreebarsa** [comment]
@eyaler Thank you for the update!
Please let us know if we can move this issue to closed status?
Thank you!
