### ISSUE TITLE
Errror in creatinig training and inference logits

### ISSUE THREAD

**Issue by shreyneil** [tensorflow/tensorflow#13092]
I am using ubuntu 16.04
version of tensorflow is 1.3.0
installed and validated using anaconda
While trying to create training and inference logits of input[32] of the following python notebook
https://github.com/Currie32/Chatbot-from-Movie-Dialogue/blob/master/Chatbot_Attention.ipynb

I was getting errors while executing the following command:

train_logits, inference_logits = seq2seq_model( tf.reverse(input_data, [-1]), targets, keep_prob, batch_size, sequence_length, len(answers_vocab_to_int), len(questions_vocab_to_int), encoding_embedding_size, decoding_embedding_size, rnn_size, num_layers, questions_vocab_to_int)

Stack trace:
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "<stdin>", line 6, in seq2seq_model
  File "<stdin>", line 10, in encoding_layer
  File "/home/shreyash/.local/lib/python2.7/site-packages/tensorflow/python/ops/rnn.py", line 405, in bidirectional_dynamic_rnn
    time_major=time_major, scope=fw_scope)
  File "/home/shreyash/.local/lib/python2.7/site-packages/tensorflow/python/ops/rnn.py", line 598, in dynamic_rnn
    dtype=dtype)
  File "/home/shreyash/.local/lib/python2.7/site-packages/tensorflow/python/ops/rnn.py", line 761, in _dynamic_rnn_loop
    swap_memory=swap_memory)
  File "/home/shreyash/.local/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2775, in while_loop
    result = context.BuildLoop(cond, body, loop_vars, shape_invariants)
  File "/home/shreyash/.local/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2604, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/home/shreyash/.local/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2554, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/home/shreyash/.local/lib/python2.7/site-packages/tensorflow/python/ops/rnn.py", line 744, in _time_step
    skip_conditionals=True)
  File "/home/shreyash/.local/lib/python2.7/site-packages/tensorflow/python/ops/rnn.py", line 236, in _rnn_step
    new_output, new_state = call_cell()
  File "/home/shreyash/.local/lib/python2.7/site-packages/tensorflow/python/ops/rnn.py", line 732, in <lambda>
    call_cell = lambda: cell(input_t, state)
  File "/home/shreyash/.local/lib/python2.7/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 180, in __call__
    return super(RNNCell, self).__call__(inputs, state)
  File "/home/shreyash/.local/lib/python2.7/site-packages/tensorflow/python/layers/base.py", line 450, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/home/shreyash/.local/lib/python2.7/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 938, in call
    cur_inp, new_state = cell(cur_inp, cur_state)
  File "/home/shreyash/.local/lib/python2.7/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 774, in __call__
    output, new_state = self._cell(inputs, state, scope)
  File "/home/shreyash/.local/lib/python2.7/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 180, in __call__
    return super(RNNCell, self).__call__(inputs, state)
  File "/home/shreyash/.local/lib/python2.7/site-packages/tensorflow/python/layers/base.py", line 450, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/home/shreyash/.local/lib/python2.7/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 401, in call
    concat = _linear([inputs, h], 4 * self._num_units, True)
  File "/home/shreyash/.local/lib/python2.7/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 1039, in _linear
    initializer=kernel_initializer)
  File "/home/shreyash/.local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 1065, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "/home/shreyash/.local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 962, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "/home/shreyash/.local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 360, in get_variable
    validate_shape=validate_shape, use_resource=use_resource)
  File "/home/shreyash/.local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 1405, in wrapped_custom_getter
    *args, **kwargs)
  File "/home/shreyash/.local/lib/python2.7/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 183, in _rnn_get_variable
    variable = getter(*args, **kwargs)
  File "/home/shreyash/.local/lib/python2.7/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 183, in _rnn_get_variable
    variable = getter(*args, **kwargs)
  File "/home/shreyash/.local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 352, in _true_getter
    use_resource=use_resource)
  File "/home/shreyash/.local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 664, in _get_single_variable
    name, "".join(traceback.format_list(tb))))
ValueError: Variable bidirectional_rnn/fw/multi_rnn_cell/cell_0/basic_lstm_cell/kernel already exists, disallowed. Did you mean to set reuse=True in VarScope? Originally defined at:

  File "<stdin>", line 10, in encoding_layer
  File "<stdin>", line 6, in seq2seq_model
  File "<stdin>", line 2, in <module>

**Comment by aselle** [comment]
Since this is not core TensorFlow code, we typically do not support it. Please file a bug with the author of the chatbot. Thanks!
