### ISSUE TITLE
Trouble installing as well as uninstalling Tensorflow

### ISSUE THREAD

**Issue by abi-aryan** [tensorflow/tensorflow#13102]
So as you can see here we have python and anaconda

```
Python 3.6.1 |Anaconda 4.4.0 (x86_64)| (default, May 11 2017, 13:04:09) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
```
Then installed Tensorflow using pip3 and tfBinaryURL eventually testing the installation-

```
>>> #python
... import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
ModuleNotFoundError: No module named 'tensorflow'
>>> 
```
So I tried uninstalling Tensorflow using pip uninstall tensorflow but again after the y/n prompt (typed "y")

 ```
 Installing collected packages: tensorflow
  Found existing installation: tensorflow 1.3.0
  Uninstalling tensorflow-1.3.0:
Exception:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/shutil.py", line 544, in move
    os.rename(src, real_dst)
PermissionError: [Errno 13] Permission denied: '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/external/__pycache__/__init__.cpython-36.pyc' -> '/var/folders/61/1b15w21n0jbc2sndhd3j7xfr0000gn/T/pip-oepk4q_b-uninstall/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/external/__pycache__/__init__.cpython-36.pyc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/req/req_set.py", line 778, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/req/req_install.py", line 754, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/shutil.py", line 559, in move
    os.unlink(src)
PermissionError: [Errno 13] Permission denied: '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/external/__pycache__/__init__.cpython-36.pyc'
this happens.
```

If it's pre-installed as it says ideally the program #1 should work - but it doesn't.

Can you help, please?

**Comment by shreyneil** [comment]
The tensorflow is not compatible  python version 3.6 , try installing it with version 3.5
Create the environment for tensorflow using anaconda using
conda create -n tensorflow python=3.5 anaconda

Try importing tensorflow after activating anaconda.
Hope it helps.

**Comment by abi-aryan** [comment]
This worked (just in case somebody comes from a Google search)
 
`conda install -c conda-forge tensorflow `
