### ISSUE TITLE
tensorflow.python.debug.cli.offline_analyzer failed to read debug data from HDFS filesys

### ISSUE THREAD

**Issue by luchensk** [tensorflow/tensorflow#13124]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04.2 
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 1.3.0 from master branch
- **Python version**: Python 2.7.12
- **Bazel version (if compiling from source)**: 0.4.5
- **CUDA/cuDNN version**: null
- **GPU model and memory**: null
- **Exact command to reproduce**: python -m tensorflow.python.debug.cli.offline_analyzer --dump_dir=hdfs://<debug_data_dir>

### Issue description
I saved debug data by `DumpingDebugHook` into hdfs filesys and then it failed to read the data by `python -m tensorflow.python.debug.cli.offline_analyzer --dump_dir=hdfs://<debug_data_path>` with the error "not a valid DFS filename" as Invalid argument. But it works well for the local filesys by the same way.

#### Error info:
```
# python -m tensorflow.python.debug.cli.offline_analyzer --dump_dir=hdfs://gpu1.hs.na61.tbsite.net:9000/data/luchen.sk/tfdbg/tb_debug_data_dump/run_1505733015456409_100
tfdbg offline: FLAGS.dump_dir = hdfs://gpu1.hs.na61.tbsite.net:9000/data/luchen.sk/tfdbg/tb_debug_data_dump/run_1505733015456409_100
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/local/hadoop-2.7.3/share/hadoop/kms/tomcat/webapps/kms/WEB-INF/lib/slf4j-log4j12-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/local/hadoop-2.7.3/share/hadoop/common/lib/slf4j-log4j12-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/local/hadoop-2.7.3/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/lib/slf4j-log4j12-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
^@hdfsOpenFile(/data/luchen.sk/tfdbg/tb_debug_data_dump/run_1505733015456409_100/_tfdbg_device_,job_localhost,replica_0,task_0,cpu_0/hdfs://gpu1.hs.na61.tbsite.net:9000/data/luchen.sk/tfdbg/tb_debug_data_dump/run_1505733015456409_100/_tfdbg_device_,job_localhost,replica_0,task_0,cpu_0/_tfdbg_graph_hash3076817912156706527_1505733016027244): FileSystem#open((Lorg/apache/hadoop/fs/Path;I)Lorg/apache/hadoop/fs/FSDataInputStream;) error:
java.lang.IllegalArgumentException: Pathname /data/luchen.sk/tfdbg/tb_debug_data_dump/run_1505733015456409_100/_tfdbg_device_,job_localhost,replica_0,task_0,cpu_0/hdfs:/gpu1.hs.na61.tbsite.net:9000/data/luchen.sk/tfdbg/tb_debug_data_dump/run_1505733015456409_100/_tfdbg_device_,job_localhost,replica_0,task_0,cpu_0/_tfdbg_graph_hash3076817912156706527_1505733016027244 from /data/luchen.sk/tfdbg/tb_debug_data_dump/run_1505733015456409_100/_tfdbg_device_,job_localhost,replica_0,task_0,cpu_0/hdfs:/gpu1.hs.na61.tbsite.net:9000/data/luchen.sk/tfdbg/tb_debug_data_dump/run_1505733015456409_100/_tfdbg_device_,job_localhost,replica_0,task_0,cpu_0/_tfdbg_graph_hash3076817912156706527_1505733016027244 is not a valid DFS filename.
	at org.apache.hadoop.hdfs.DistributedFileSystem.getPathName(DistributedFileSystem.java:197)
	at org.apache.hadoop.hdfs.DistributedFileSystem.access$000(DistributedFileSystem.java:106)
	at org.apache.hadoop.hdfs.DistributedFileSystem$3.doCall(DistributedFileSystem.java:303)
	at org.apache.hadoop.hdfs.DistributedFileSystem$3.doCall(DistributedFileSystem.java:299)
	at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
	at org.apache.hadoop.hdfs.DistributedFileSystem.open(DistributedFileSystem.java:299)
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/debug/cli/offline_analyzer.py", line 78, in <module>
    app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/debug/cli/offline_analyzer.py", line 41, in main
    FLAGS.dump_dir, validate=FLAGS.validate_graph)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/debug/lib/debug_data.py", line 692, in __init__
    self._load_all_device_dumps(partition_graphs, validate)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/debug/lib/debug_data.py", line 714, in _load_all_device_dumps
    self._load_partition_graphs(partition_graphs, validate)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/debug/lib/debug_data.py", line 983, in _load_partition_graphs
    self._dump_graph_file_paths[device_name])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/debug/lib/debug_data.py", line 145, in _load_graph_def_from_event_file
    event.ParseFromString(f.read())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 119, in read
    self._preread_check()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 79, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    c_api.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: hdfs://gpu1.hs.na61.tbsite.net:9000/data/luchen.sk/tfdbg/tb_debug_data_dump/run_1505733015456409_100/_tfdbg_device_,job_localhost,replica_0,task_0,cpu_0/hdfs://gpu1.hs.na61.tbsite.net:9000/data/luchen.sk/tfdbg/tb_debug_data_dump/run_1505733015456409_100/_tfdbg_device_,job_localhost,replica_0,task_0,cpu_0/_tfdbg_graph_hash3076817912156706527_1505733016027244; Invalid argument
```

In fact, it was able to read the hdfs dir info, as below:

```
$hdfs dfs -ls hdfs://ns1/data/luchen.sk/tfdbg/tb_debug_data_dump/run_1505733015456409_100/_tfdbg_device_,job_localhost,replica_0,task_0,cpu_0
Found 7 items
-rw-r--r--   3 root supergroup     141732 2017-09-18 19:10 hdfs://ns1/data/luchen.sk/tfdbg/tb_debug_data_dump/run_1505733015456409_100/_tfdbg_device_,job_localhost,replica_0,task_0,cpu_0/_tfdbg_graph_hash3076817912156706527_1505733016027244
drwxr-xr-x   - root supergroup          0 2017-09-18 19:10 hdfs://ns1/data/luchen.sk/tfdbg/tb_debug_data_dump/run_1505733015456409_100/_tfdbg_device_,job_localhost,replica_0,task_0,cpu_0/gradients
drwxr-xr-x   - root supergroup          0 2017-09-18 19:10 hdfs://ns1/data/luchen.sk/tfdbg/tb_debug_data_dump/run_1505733015456409_100/_tfdbg_device_,job_localhost,replica_0,task_0,cpu_0/layer_1
drwxr-xr-x   - root supergroup          0 2017-09-18 19:10 hdfs://ns1/data/luchen.sk/tfdbg/tb_debug_data_dump/run_1505733015456409_100/_tfdbg_device_,job_localhost,replica_0,task_0,cpu_0/layer_2
drwxr-xr-x   - root supergroup          0 2017-09-18 19:10 hdfs://ns1/data/luchen.sk/tfdbg/tb_debug_data_dump/run_1505733015456409_100/_tfdbg_device_,job_localhost,replica_0,task_0,cpu_0/layer_out
drwxr-xr-x   - root supergroup          0 2017-09-18 19:10 hdfs://ns1/data/luchen.sk/tfdbg/tb_debug_data_dump/run_1505733015456409_100/_tfdbg_device_,job_localhost,replica_0,task_0,cpu_0/loss
drwxr-xr-x   - root supergroup          0 2017-09-18 19:10 hdfs://ns1/data/luchen.sk/tfdbg/tb_debug_data_dump/run_1505733015456409_100/_tfdbg_device_,job_localhost,replica_0,task_0,cpu_0/train
```

After that, I tried to change the name of the dir as above from `_tfdbg_device_,job_localhost,replica_0,task_0,cpu_0` to `_tfdbg_device`, and then it was able to load the dir into CLI UI for debug, but there was nothing about debug info to show, as below:

![image](https://user-images.githubusercontent.com/28526467/30541641-dc4329d2-9cae-11e7-8e07-c84dd1a3a7a3.png)

**Comment by luchensk** [comment]
@caisq Do we have a schedule for this issue? Thanks.

**Comment by caisq** [comment]
@luchensk HDFS is currently not supported by tfdbg. If you or any other open-source users have the interest, you are welcome to contribute such support. I do not have enough free cycles to fulfill this feature request this month.

**Comment by nikhilrayaprolu** [comment]
@caisq I would like to take up this issue and work on it.

**Comment by caisq** [comment]
@nikhilrayaprolu Thanks a lot! Please go ahead! When you make a pull request, please add me as a reviewer. 

cc @jhseu re HDFS.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Please remove the assignee, as this issue is inviting external contributions. Otherwise, remove the `contributions welcome` label. Thank you.

**Comment by mihaimaruseac** [comment]
Closing as HDFS is no longer supported by TF itself
