### ISSUE TITLE
Build fails at patch command - different line endings

### ISSUE THREAD

**Issue by 9k37** [tensorflow/tensorflow#13130]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Windows 8.1 64bit
- **TensorFlow installed from (source or binary)**:
I'm trying to build from source to use CPU optimizations
- **TensorFlow version (use command below)**:
1.3 cloned from master
- **Python version**: 
3.6.1
- **Bazel version (if compiling from source)**:
0.5.4
- **CUDA/cuDNN version**:
CPU only
### Describe the problem
I'm trying to build TensorFlow from source to use CPU optimizations. I was getting `patch` error exactly as in [Issue #10435](https://github.com/tensorflow/tensorflow/issues/10435) so I used the [recommended solution](https://github.com/tensorflow/tensorflow/issues/10435#issuecomment-306422472) by adding `--binary` to `patch` call at _workspace.bzl_ function `_apply_patch()`. The _tensorflow/core_ is now loaded, bur I get another error with _tensorflow/contrib/session_bundle_ - see log.
### Source code / logs
```
$ ./configure
You have bazel 0.5.4 installed.
Found possible Python library paths:
  D:\anaconda\lib\site-packages
Please input the desired Python library path to use.  Default is [D:\anaconda\lib\site-packages]
Do you wish to build TensorFlow with XLA JIT support? [y/N]: n
No XLA JIT support will be enabled for TensorFlow.
Do you wish to build TensorFlow with GDR support? [y/N]: n
No GDR support will be enabled for TensorFlow.
Do you wish to build TensorFlow with VERBS support? [y/N]: n
No VERBS support will be enabled for TensorFlow.
Do you wish to build TensorFlow with CUDA support? [y/N]: n
No CUDA support will be enabled for TensorFlow.
Do you wish to build TensorFlow with MPI support? [y/N]: n
No MPI support will be enabled for TensorFlow.
Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native]:
Add "--config=mkl" to your bazel command to build with MKL support.
Please note that MKL on MacOS or windows is still not supported.
If you would like to use a local MKL instead of downloading, please set the environment variable "TF_MKL_ROOT" every time before build.
Configuration finished

$ ./bazel build --config=opt --cpu=x64_windows_msvc --host_cpu=x64_windows_msvc --copt=-w --host_copt=-w //tensorflow/tools/pip_package:build_pip_package
.............
____Loading package: tensorflow/tools/pip_package
____Loading package: @bazel_tools//tools/cpp
____Loading package: @bazel_tools//tools/jdk
____Loading package: @local_config_xcode//
____Loading package: @local_config_cc//
____Loading package: @local_jdk//
____Loading complete.  Analyzing...
____Loading package: @bazel_tools//tools/launcher
____Loading package: tensorflow/contrib/nn
____Loading package: tensorflow/python/tools
____Loading package: tensorflow/python/eager
____Downloading http://mirror.bazel.build/github.com/google/protobuf/archive/0b059a3d8a8f8aa40dde7bea55edca4ec5dfea66.tar.gz: 1,500,767 bytes
____Downloading http://mirror.bazel.build/github.com/google/protobuf/archive/0b059a3d8a8f8aa40dde7bea55edca4ec5dfea66.tar.gz: 3,866,533 bytes
____Downloading http://mirror.bazel.build/github.com/google/protobuf/archive/0b059a3d8a8f8aa40dde7bea55edca4ec5dfea66.tar.gz: 1,351,924 bytes
____Downloading http://mirror.bazel.build/github.com/google/protobuf/archive/0b059a3d8a8f8aa40dde7bea55edca4ec5dfea66.tar.gz: 3,602,866 bytes
____Downloading http://mirror.bazel.build/github.com/google/protobuf/archive/0b059a3d8a8f8aa40dde7bea55edca4ec5dfea66.tar.gz: 1,223,337 bytes
____Downloading http://mirror.bazel.build/github.com/google/protobuf/archive/0b059a3d8a8f8aa40dde7bea55edca4ec5dfea66.tar.gz: 3,589,997 bytes
ERROR: D:/tensorflow/tensorflow/tools/pip_package/BUILD:70:1: error loading package 'tensorflow/contrib/session_bundle': Encountered error while reading extension file 'protobuf.bzl': no such package '@protobuf_archive//': Traceback (most recent call last):
        File "D:/tensorflow/tensorflow/workspace.bzl", line 123
                _apply_patch(repo_ctx, repo_ctx.attr.patch_file)
        File "D:/tensorflow/tensorflow/workspace.bzl", line 114, in _apply_patch
                _execute_and_check_ret_code(repo_ctx, cmd)
        File "D:/tensorflow/tensorflow/workspace.bzl", line 94, in _execute_and_check_ret_code
                fail("Non-zero return code({1}) when ...))
Non-zero return code(1) when executing 'D:\msys\usr\bin\bash.exe -c patch --binary -p1 -d D:/msys/tmp/_bazel_admin/aeorbm85/external/protobuf_archive -i D:/tensorflow/third_party/protobuf/add_noinlines.patch':
Stdout: patching file src/google/protobuf/compiler/cpp/cpp_file.cc
Hunk #1 FAILED at 557 (different line endings).
Hunk #2 FAILED at 656 (different line endings).
Hunk #3 FAILED at 737 (different line endings).
3 out of 3 hunks FAILED -- saving rejects to file src/google/protobuf/compiler/cpp/cpp_file.cc.rej

Stderr:  and referenced by '//tensorflow/tools/pip_package:simple_console_for_windows'.
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted.
____Elapsed time: 34,135s
```

**Comment by aselle** [comment]
@gunan, have you seen anything like this? In the past cygwin and others had ways of configuring how to treat CRLF in apps. Is there somethings similar in msys  that might fix this? In any case you can also try cmake, which is currently working a little more reliably than bazel on windows.

**Comment by gunan** [comment]
It is possible this is related to the github file hash issues. We may not have updated the r1.3 branch yet. But just to check @meteorcloudy have you seen this issue?

**Comment by meteorcloudy** [comment]
@9k37 Maybe you want to add `--binary` flag [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/workspace.bzl#L107).
According to https://stackoverflow.com/questions/2076688/how-to-use-patches-created-in-windows-with-crlf-in-linuxi

**Comment by 9k37** [comment]
@meteorcloudy it was with `--binary` when I got the above error. After your response I tried couple of times with and without `--binary` and finally omit the patch error. My build is now crashing with another error - can you help me further? Note also the warning in the middle.
```
$ ./bazel build --config=opt --cpu=x64_windows --host_cpu=x64_windows --copt=-w --host_copt=-w //tensorflow/tools/pip_package:build_pip_package
____Loading complete.  Analyzing...
____Loading package: tensorflow/core/profiler
____Loading package: tensorflow/contrib/saved_model
____Loading package: tensorflow/core/util/tensor_bundle
____Loading package: @fft2d//
____Loading package: @lmdb//
____Loading package: @highwayhash//
____Loading package: @farmhash_archive//
____Loading package: @com_googlesource_code_re2//
____Loading package: @sqlite_archive//
____Loading package: @gif_archive//
____Loading package: @jsoncpp_git//
____Loading package: @png_archive//
____Loading package: @jpeg//
WARNING: D:/tensorflow/tensorflow/core/BUILD:1652:1: in includes attribute of cc_library rule //tensorflow/core:framework_headers_lib: '../../external/nsync/public' resolves to 'external/nsync/public' not below the relative path of its package 'tensorflow/core'. This will be an error in the future. Since this rule was created by the macro 'cc_header_only_library', the error might have been caused by the macro implementation in D:/tensorflow/tensorflow/tensorflow.bzl:913:30.
____Loading package: @swig//
____Loading package: @grpc//
____Loading package: @grpc//third_party/nanopb
____Loading package: @boringssl//
____Loading package: @pcre//
____Found 1 target...
____Building...
____[0 / 5] Writing file tensorflow/tools/pip_package/build_pip_package.launch_info
____[8 / 164] Writing file external/protobuf_archive/libprotoc_lib.a-2.params [for host]
____[9 / 196] Executing genrule @protobuf_archive//:protos_python_genrule
____[15 / 260] Expanding template external/jpeg/jconfigint_nowin.h
____[40 / 457] Writing file external/snappy/libsnappy.a-2.params [for host]
____[42 / 463] Writing file external/jpeg/libsimd_none.a-2.params [for host]
ERROR: D:/tensorflow/tensorflow/core/BUILD:1562:1: Executing genrule //tensorflow/core:version_info_gen failed (Exit 127).
/usr/bin/env: 'python': No such file or directory
____Building complete.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
____Elapsed time: 216,811s, Critical Path: 1,10s
```
[full_output.txt](https://github.com/tensorflow/tensorflow/files/1330723/full_output.txt)

**Comment by meteorcloudy** [comment]
@9k37 Looks like you don't have python in your `PATH`?

**Comment by 9k37** [comment]
@meteorcloudy my python is in /d/anaconda:
```
$ printenv PATH
/usr/local/bin:/usr/bin:/bin:/opt/bin:/c/Windows/System32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0/:/d/anaconda
$ printenv PYTHON_BIN_PATH
D:\anaconda\python.exe
```
and I don't even have path like /usr/bin/env. When I tried to create one inside msys\usr\bin I get this:

**Comment by 9k37** [comment]
@meteorcloudy my python is in D:\anaconda\
```
$ printenv PATH
/usr/local/bin:/usr/bin:/bin:/opt/bin:/c/Windows/System32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0/:/d/anaconda
$ printenv PYTHON_BIN_PATH
D:\anaconda\python.exe
```
and I don't have anything like /usr/bin/env: I am using MSYS with all executables in /d/msys/usr/bin

**Comment by aselle** [comment]
you could just try changing tensorflow/tools/git/gen_git_source.py first line (starts with #! to be 
```
#!/d/msys/usr/bin/python
```

**Comment by 9k37** [comment]
@aselle I did change it to my python location:
```
$ less /d/tensorflow/tensorflow/tools/git/gen_git_source.py | grep python
#!/d/anaconda/python
        # In python 3.5, symlink function exists even on Windows. But requires
```
And as I understood from gen_git_source.py I was running MSYS as administrator. Result is:
```
X@Y MSYS /d/tensorflow
$ ./bazel build --config=opt --cpu=x64_windows --host_cpu=x64_windows --copt=-w --host_copt=-w //tensorflow/tools/pip_package:build_pip_package
____Loading complete.  Analyzing...
WARNING: D:/tensorflow/tensorflow/core/BUILD:1652:1: in includes attribute of cc_library rule //tensorflow/core:framework_headers_lib: '../../external/nsync/public' resolves to 'external/nsync/public' not below the relative path of its package 'tensorflow/core'. This will be an error in the future. Since this rule was created by the macro 'cc_header_only_library', the error might have been caused by the macro implementation in D:/tensorflow/tensorflow/tensorflow.bzl:913:30.
____Found 1 target...
____Building...
ERROR: D:/tensorflow/tensorflow/core/BUILD:1562:1: Executing genrule //tensorflow/core:version_info_gen failed (Exit 1).
Traceback (most recent call last):
  File "tensorflow/tools/git/gen_git_source.py", line 264, in <module>
    generate(args.generate)
  File "tensorflow/tools/git/gen_git_source.py", line 216, in generate
    git_version = get_git_version(data["path"])
  File "tensorflow/tools/git/gen_git_source.py", line 156, in get_git_version
    str("--work-tree=" + git_base_path), "describe", "--long", "--tags"
  File "D:\anaconda\lib\subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "D:\anaconda\lib\subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "D:\anaconda\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "D:\anaconda\lib\subprocess.py", line 990, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
____Elapsed time: 1,910s, Critical Path: 0,42s
```

**Comment by gunan** [comment]
This was resolved, before the build broke with another issue.
