### ISSUE TITLE
BUG: No GPU kernel for tf.scatter_nd and tf.gather_nd with int32 or int64 tensors

### ISSUE THREAD

**Issue by dantkz** [tensorflow/tensorflow#13164]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 14.04
- **TensorFlow installed from (source or binary)**:
binary (pip)
- **TensorFlow version (use command below)**:
v1.3.0-rc2-20-g0787eee 1.3.0
- **Python version**: 
Python 3.5.2
- **Bazel version (if compiling from source)**:
n/a
- **CUDA/cuDNN version**:
CUDA-8.0 / cuDNN-5.1
- **GPU model and memory**:
NVidia GeForce GTX TITAN with 5.93GiB
- **Exact command to reproduce**:
```
import tensorflow as tf
import numpy as np

val_num = 5
val_dim = 2

with tf.device("/gpu:0"):
    indices = tf.reshape(tf.range(val_num, dtype=tf.int64), [-1, 1])
    updates = tf.constant(np.tile(np.expand_dims(np.arange(val_num, dtype=np.int64), 1), [1, val_dim]))

    res = tf.scatter_nd(indices, updates, [val_num, val_dim])
    #res = tf.gather_nd(updates, indices)

    sess = tf.Session()
    sess.run(tf.global_variables_initializer())

    print(sess.run(res))
```

### Describe the problem
**tf.scatter_nd** and **tf.gather_nd** do not support **int32** or **int64** tensors on GPU.

### Source code / logs
tf.scatter_nd:
```
2017-09-19 22:33:55.447883: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-19 22:33:55.447965: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-19 22:33:55.649706: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:893] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2017-09-19 22:33:55.650199: I tensorflow/core/common_runtime/gpu/gpu_device.cc:955] Found device 0 with properties:
name: GeForce GTX TITAN
major: 3 minor: 5 memoryClockRate (GHz) 0.8755
pciBusID 0000:04:00.0
Total memory: 5.93GiB
Free memory: 5.63GiB
2017-09-19 22:33:55.650286: I tensorflow/core/common_runtime/gpu/gpu_device.cc:976] DMA: 0
2017-09-19 22:33:55.650299: I tensorflow/core/common_runtime/gpu/gpu_device.cc:986] 0:   Y
2017-09-19 22:33:55.650316: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1045] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX TITAN, pci bus id: 0000:04:00.0)
Traceback (most recent call last):
  File "/home/daniyar/anaconda2/envs/python3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1327, in _do_call
    return fn(*args)
  File "/home/daniyar/anaconda2/envs/python3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1297, in _run_fn
    self._extend_graph()
  File "/home/daniyar/anaconda2/envs/python3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1358, in _extend_graph
    self._session, graph_def.SerializeToString(), status)
  File "/home/daniyar/anaconda2/envs/python3/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/home/daniyar/anaconda2/envs/python3/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device for operation 'ScatterNd': Could not satisfy explicit device specification '/device:GPU:0' because no supported kernel for GPU devices is available.
	 [[Node: ScatterNd = ScatterNd[T=DT_INT64, Tindices=DT_INT64, _device="/device:GPU:0"](Reshape, Const, ScatterNd/shape)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bug.py", line 15, in <module>
    sess.run(tf.global_variables_initializer())
  File "/home/daniyar/anaconda2/envs/python3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/home/daniyar/anaconda2/envs/python3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/daniyar/anaconda2/envs/python3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    options, run_metadata)
  File "/home/daniyar/anaconda2/envs/python3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device for operation 'ScatterNd': Could not satisfy explicit device specification '/device:GPU:0' because no supported kernel for GPU devices is available.
	 [[Node: ScatterNd = ScatterNd[T=DT_INT64, Tindices=DT_INT64, _device="/device:GPU:0"](Reshape, Const, ScatterNd/shape)]]

Caused by op 'ScatterNd', defined at:
  File "bug.py", line 11, in <module>
    res = tf.scatter_nd(indices, updates, [val_num, val_dim])
  File "/home/daniyar/anaconda2/envs/python3/lib/python3.5/site-packages/tensorflow/python/ops/gen_array_ops.py", line 2961, in scatter_nd
    shape=shape, name=name)
  File "/home/daniyar/anaconda2/envs/python3/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/home/daniyar/anaconda2/envs/python3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/daniyar/anaconda2/envs/python3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Cannot assign a device for operation 'ScatterNd': Could not satisfy explicit device specification '/device:GPU:0' because no supported kernel for GPU devices is available.
	 [[Node: ScatterNd = ScatterNd[T=DT_INT64, Tindices=DT_INT64, _device="/device:GPU:0"](Reshape, Const, ScatterNd/shape)]]

```

tf.gather_nd:
```
2017-09-19 22:34:26.298344: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-19 22:34:26.298436: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-19 22:34:26.504483: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:893] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2017-09-19 22:34:26.504948: I tensorflow/core/common_runtime/gpu/gpu_device.cc:955] Found device 0 with properties:
name: GeForce GTX TITAN
major: 3 minor: 5 memoryClockRate (GHz) 0.8755
pciBusID 0000:04:00.0
Total memory: 5.93GiB
Free memory: 5.61GiB
2017-09-19 22:34:26.505032: I tensorflow/core/common_runtime/gpu/gpu_device.cc:976] DMA: 0
2017-09-19 22:34:26.505044: I tensorflow/core/common_runtime/gpu/gpu_device.cc:986] 0:   Y
2017-09-19 22:34:26.505061: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1045] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX TITAN, pci bus id: 0000:04:00.0)
Traceback (most recent call last):
  File "/home/daniyar/anaconda2/envs/python3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1327, in _do_call
    return fn(*args)
  File "/home/daniyar/anaconda2/envs/python3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1297, in _run_fn
    self._extend_graph()
  File "/home/daniyar/anaconda2/envs/python3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1358, in _extend_graph
    self._session, graph_def.SerializeToString(), status)
  File "/home/daniyar/anaconda2/envs/python3/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/home/daniyar/anaconda2/envs/python3/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device for operation 'GatherNd': Could not satisfy explicit device specification '/device:GPU:0' because no supported kernel for GPU devices is available.
	 [[Node: GatherNd = GatherNd[Tindices=DT_INT64, Tparams=DT_INT64, _device="/device:GPU:0"](Const, Reshape)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bug.py", line 15, in <module>
    sess.run(tf.global_variables_initializer())
  File "/home/daniyar/anaconda2/envs/python3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/home/daniyar/anaconda2/envs/python3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/daniyar/anaconda2/envs/python3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    options, run_metadata)
  File "/home/daniyar/anaconda2/envs/python3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device for operation 'GatherNd': Could not satisfy explicit device specification '/device:GPU:0' because no supported kernel for GPU devices is available.
	 [[Node: GatherNd = GatherNd[Tindices=DT_INT64, Tparams=DT_INT64, _device="/device:GPU:0"](Const, Reshape)]]

Caused by op 'GatherNd', defined at:
  File "bug.py", line 12, in <module>
    res = tf.gather_nd(updates, indices)
  File "/home/daniyar/anaconda2/envs/python3/lib/python3.5/site-packages/tensorflow/python/ops/gen_array_ops.py", line 1338, in gather_nd
    name=name)
  File "/home/daniyar/anaconda2/envs/python3/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/home/daniyar/anaconda2/envs/python3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/daniyar/anaconda2/envs/python3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Cannot assign a device for operation 'GatherNd': Could not satisfy explicit device specification '/device:GPU:0' because no supported kernel for GPU devices is available.
	 [[Node: GatherNd = GatherNd[Tindices=DT_INT64, Tparams=DT_INT64, _device="/device:GPU:0"](Const, Reshape)]]

```

**Comment by dantkz** [comment]
I checked this bug with nightly build from September 19th (1.4.0.dev20170919-cp35-cp35m-linux_x86_64.whl). This is still not implemented.

**Comment by drpngx** [comment]
@dantkz it's only implemented with [floating point types](https://www.github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/gather_nd_op.cc#L208) (half, float, and double). We need to add `int32` and `int64`.

It should be relatively easy, just call that macro for those types. Would you like to submit a PR?

**Comment by facaiy** [comment]
#12943 seems a good example for reference.

By the way, since all types are supported on CPU, while only float is registered for GPU:

https://github.com/tensorflow/tensorflow/blob/3537e663230ba2d694f6daebc2288f180c6db4ea/tensorflow/core/kernels/gather_nd_op.cc#L170

https://github.com/tensorflow/tensorflow/blob/3537e663230ba2d694f6daebc2288f180c6db4ea/tensorflow/core/kernels/gather_nd_op.cc#L208

is it possible that the programmer designed this on purpose?

**Comment by drpngx** [comment]
I say we try to register it and see what happens.

**Comment by dantkz** [comment]
@drpngx 
I've registered those types and updated tests: https://github.com/tensorflow/tensorflow/pull/13382

tf.gather and tf.gather_nd now support int32 and int64 ref tensors when running on GPU. 
tf.scatter now supports int32 ref tensors when running on GPU. int64 is not supported as some CudaAtomic operations are not supported.

**Comment by drpngx** [comment]
Thanks!

**Comment by dantkz** [comment]
@drpngx thank you! Still waiting for a code review, though.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by unrealwill** [comment]
Hi,
@rmlarsen  
it seems the last fix is missing int32 for gather op : 
https://github.com/tensorflow/tensorflow/commit/83116bafebb500fa963809599b7f2583367c92d6#diff-0a1b05e2252bef657373e11f17bfa5d3 (or at least it isn't present in pip tensorfluw_gpu 1.9 branch)

**Comment by facaiy** [comment]
I'm afraid the it's on purpose for efficient.

**Comment by unrealwill** [comment]
@facaiy : Are you sure ? It's quite strange, if so it's error prone, currently I have used two different ugly ways to hack_it to get it to work on GPU.
I can either 
`tf.squeeze( tf.gather_nd( tf.expand_dims(tab,1),tf.expand_dims(ind,1) )`
or
`tf.cast( tf.gather( tf.cast(tab,tf.int64 ), ind ), tf.int32 )`
In either way they are both way more efficient, than a copy to cpu, the gather on cpu followed by a copy back to gpu, which happens if you let tensorflow the liberty of choosing where to allocate.

**Comment by hamlatzis** [comment]
Is there a plan to support for tflite an OpenCL kernel for Gather(V2)?
