### ISSUE TITLE
Linux installation issue for GPU-enabled version

### ISSUE THREAD

**Issue by shubhanshu-gupta** [tensorflow/tensorflow#134]
Hi,

I ran the command "$ pip install https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.5.0-cp27-none-linux_x86_64.whl" and I got:

```
Downloading/unpacking https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.5.0-cp27-none-linux_x86_64.whl
  Downloading tensorflow-0.5.0-cp27-none-linux_x86_64.whl (50.5Mb): 50.5Mb downloaded
  Running setup.py egg_info for package from https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.5.0-cp27-none-linux_x86_64.whl
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
    IOError: [Errno 2] No such file or directory: '/tmp/pip-o6Tpui-build/setup.py'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

IOError: [Errno 2] No such file or directory: '/tmp/pip-o6Tpui-build/setup.py'

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /tmp/pip-o6Tpui-build
Storing complete log in /home/shubhanshu/.pip/pip.log
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.1', 'console_scripts', 'pip-2.7')()
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 116, in main
    return command.main(args[1:], options)
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 141, in main
    log_fp = open_logfile(log_fn, 'w')
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 168, in open_logfile
    log_fp = open(filename, mode)
IOError: [Errno 13] Permission denied: '/home/shubhanshu/.pip/pip.log'
```

Any directions, how to proceed ahead?

**Comment by markusdr** [comment]
I've also encountered the missing setup.py error with an older version of pip. After upgrading pip it went through fine.

**Comment by xuezhisd** [comment]
```
sudo pip install pip --upgrade
```

**Comment by vrv** [comment]
Great!  We added these instructions to our installation docs.  Hopefully it addresses most people's issues.
