### ISSUE TITLE
Issue when the saving the model when the session is made by with statement

### ISSUE THREAD

**Issue by tancejang** [tensorflow/tensorflow#13471]
i use tensorflow to train LSTM network. The training run well but when i want to save the model, i get error below.
```
Step 1, Minibatch Loss= 0.0146, Training Accuracy= 1.000
Step 1, Minibatch Loss= 0.0129, Training Accuracy= 1.000
Optimization Finished!
Traceback (most recent call last):
  File ".\lstm.py", line 169, in <module>
    save_path = saver.save(sess, "modelslstm/" + str(time.strftime("%d-%m-%Y-%H-%M-%S")) + ".ckpt")
  File "C:\Python35\lib\site-packages\tensorflow\python\client\session.py", line 1314, in __exit__
    self._default_graph_context_manager.__exit__(exec_type, exec_value, exec_tb)
  File "C:\Python35\lib\contextlib.py", line 66, in __exit__
    next(self.gen)
  File "C:\Python35\lib\site-packages\tensorflow\python\framework\ops.py", line 3815, in get_controller
    if self.stack[-1] is not default:
IndexError: list index out of range
```

My Code :
```
with tf.Session() as sess:
    sess.run(init)
    saver = tf.train.Saver()
   ....
   save_path = saver.save(sess, "modelslstm/" + str(time.strftime("%d-%m-%Y-%H-%M-%S")) + ".ckpt")
```
After i changed the `with` statement with the `sess = tf.Session()` the problem gone

**Comment by yaroslavvb** [comment]
Sounds like you are trying to use the session outside of the `with` block which is not allowed. You can just stick to `sess=tf.Session()` line, the `with` block is only useful if you are trying to use multiple sessions at the same time

**Comment by reedwm** [comment]
I think @yaroslavvb is right but when I try to call `saver.save` with a closed session, I get the error message "RuntimeError: Attempted to use a closed Session".

@tancejang can you post a small, full example that reproduces the problem?

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue? Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue? Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?
