### ISSUE TITLE
tweak validate_shape to remove "Assign requires shapes of both tensors to match. lhs shape= [12] rhs shape= [3]" error

### ISSUE THREAD

**Issue by serendipity24** [tensorflow/tensorflow#13487]
------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:No. I am running the Audio recognition tutorial
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 14.04
- **TensorFlow installed from (source or binary)**:source
- **TensorFlow version (use command below)**: 1.3.0
- **Python version**: 3.6
- **Bazel version (if compiling from source)**:0.6.0
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:python tensorflow/examples/speech_commands/freeze.py \
--start_checkpoint=/tmp/speech_commands_train/conv.ckpt-18000 \
--output_file=/tmp/my_frozen_graph.pb

I am asking about the error (attached below) here(rather than on stackoverflow) because of this related issue https://github.com/tensorflow/tensorflow/issues/5492 . I want to know if my error can be resolved by tweaking the validate_shape parameter,by setting it to false? . If not, please suggest alternatives.

The error is as follows: 

Traceback (most recent call last):
  File "/home/cogknit/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1321, in _do_call
    return fn(*args)
  File "/home/cogknit/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1300, in _run_fn
    status, run_metadata)
  File "/home/cogknit/anaconda3/lib/python3.6/contextlib.py", line 89, in __exit__
    next(self.gen)
  File "/home/cogknit/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 467, in raise_exception_on_not_ok_status
    c_api.TF_GetCode(status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [12] rhs shape= [3]
	 [[Node: save/Assign_5 = Assign[T=DT_FLOAT, _class=["loc:@Variable_5"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/cpu:0"](Variable_5, save/RestoreV2_5)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tensorflow/examples/speech_commands/freeze.py", line 180, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/home/cogknit/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "tensorflow/examples/speech_commands/freeze.py", line 117, in main
    models.load_variables_from_checkpoint(sess, FLAGS.start_checkpoint)
  File "/home/cogknit/tensorflow/tensorflow/examples/speech_commands/models.py", line 123, in load_variables_from_checkpoint
    saver.restore(sess, start_checkpoint)
  File "/home/cogknit/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1657, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/cogknit/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/home/cogknit/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1118, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/cogknit/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1315, in _do_run
    options, run_metadata)
  File "/home/cogknit/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [12] rhs shape= [3]
	 [[Node: save/Assign_5 = Assign[T=DT_FLOAT, _class=["loc:@Variable_5"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/cpu:0"](Variable_5, save/RestoreV2_5)]]

Caused by op 'save/Assign_5', defined at:
  File "tensorflow/examples/speech_commands/freeze.py", line 180, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/home/cogknit/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "tensorflow/examples/speech_commands/freeze.py", line 117, in main
    models.load_variables_from_checkpoint(sess, FLAGS.start_checkpoint)
  File "/home/cogknit/tensorflow/tensorflow/examples/speech_commands/models.py", line 122, in load_variables_from_checkpoint
    saver = tf.train.Saver(tf.global_variables())
  File "/home/cogknit/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1214, in __init__
    self.build()
  File "/home/cogknit/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1223, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/cogknit/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1259, in _build
    build_save=build_save, build_restore=build_restore)
  File "/home/cogknit/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 747, in _build_internal
    restore_sequentially, reshape)
  File "/home/cogknit/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 435, in _AddRestoreOps
    assign_ops.append(saveable.restore(tensors, shapes))
  File "/home/cogknit/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 160, in restore
    self.op.get_shape().is_fully_defined())
  File "/home/cogknit/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/state_ops.py", line 276, in assign
    validate_shape=validate_shape)
  File "/home/cogknit/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_state_ops.py", line 56, in assign
    use_locking=use_locking, name=name)
  File "/home/cogknit/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/cogknit/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3082, in create_op
    op_def=op_def)
  File "/home/cogknit/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1632, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [12] rhs shape= [3]
	 [[Node: save/Assign_5 = Assign[T=DT_FLOAT, _class=["loc:@Variable_5"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/cpu:0"](Variable_5, save/RestoreV2_5)]]

**Comment by reedwm** [comment]
/CC @benoitsteiner can you comment on this issue and on #5492?

**Comment by reedwm** [comment]
Also /CC @petewarden.

**Comment by vclteam** [comment]
Did u manage to tweak the code? Can u share the code
I'm facing the same problem

**Comment by serendipity24** [comment]
@vclteam, the issue here was resolved without tweaking the code.

 At the beginning of freeze.py file it is mentioned that the flags used during training command have to be preserved during the freezing too: "One thing to watch out for is that you need to pass in the same arguments for `sample_rate` and other command line variables here as you did for the training
script." So in my case I had to use the flag --wanted_words=yes  again here ,something that I hadn't done previously.

In your case(https://github.com/tensorflow/tensorflow/issues/13581), I think if you have trained with the --clip_duration_ms=1000, then you can't change it to 2800 at the freezing stage. May I know if this is the case?

**Comment by vclteam** [comment]
@serendipity24 

hi

Thanks for answering, as u can see below, i trained and freezed the model with the sample parameters.
The fact at the moment is that if u change the duration from 1000ms to any other value
the system crash on the freeze with the message

**Assign requires shapes of both tensors to match**

python tensorflow/examples/speech_commands/train.py --data_dir=/notebooks/yesdb/ \
--wanted_words=yes \
--how_many_training_steps=100,100 --learning_rate=0.001,0.0001  \
--train_dir=/notebooks/yesmodel \
--summaries_dir=/notebooks/yesmodellog
--clip_duration_ms=2834 --sample_rate=16000 --window_size_ms=20


python tensorflow/examples/speech_commands/freeze.py \
--wanted_words=yes \
--clip_duration_ms=2834 --sample_rate=16000 --window_size_ms=20 \
--start_checkpoint=/notebooks/yesmodel/conv.ckpt-100 \
--output_file=/notebooks/yesmodel/conv_frozen.pb

**Comment by vclteam** [comment]
and since i'm getting the same exception how exactly did u managed to overcome it?

**Comment by serendipity24** [comment]
"The fact at the moment is that if u change the duration from 1000ms to any other value
the system crash on the freeze with the message"- I didn't change the duration from the default 1000ms during training. So I am sorry, I don't know the reason as of now. 

But if the training worked with 2834 ms without any errors, I don't see why the freezing wouldn't work. If you initially trained using 1000ms, I suggest you delete the checkpoint files created during this training and then run the training with the new duration. This was something I came across while trying to solve my issue.

**Comment by vclteam** [comment]
@serendipity24 
i deleted everything even used a clean docker.nothing!
where i change the duration freeze just keep crashing

**Comment by serendipity24** [comment]
@vclteam just to be very clear, are you changing the duration during training or freezing? As previously mentioned, if the duration used in training and freezing are different, then it will crash.  So, may I know what duration are you using during training? Is it 2834 seconds as mentioned above by you?

**Comment by vclteam** [comment]
@serendipity24  2834 is the duration in milliseconds and im using the same value for the train and freeze.and while putting the value of 1000ms everything working great,change this value generate exception on the freeze

**Comment by vclteam** [comment]
sorry found the problem,its related to linux command line not tensorflow at all
@serendipity24

**Comment by serendipity24** [comment]
@vclteam no need for sorry, glad it was resolved :), but curiosity sake I have two questions:
(i) If you trained with 2834ms and gave the freeze command with 2834ms,  what do you mean by "while putting the value of 1000ms" ?
(ii) What about linux command line caused this error? 

Thanks

**Comment by vclteam** [comment]
if forgot to put \ at the end of one of the line
so the training was actually for 1000ms

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Awaiting TensorFlower: It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
A member of the TensorFlow organization has replied after the stat:awaiting tensorflower label was applied.

**Comment by tatatodd** [comment]
Closing this out - looks like it was resolved.
