### ISSUE TITLE
osx 10.11 installation issues

### ISSUE THREAD

**Issue by schmitzel** [tensorflow/tensorflow#135]
Trying to install it with `pip install https://storage.googleapis.com/tensorflow/mac/tensorflow-0.5.0-py2-none-any.wh`. Same issue if doing it with virutalenv. 

Exception:
Traceback (most recent call last):
  File "/Users/Schmidt/anaconda/lib/python2.7/site-packages/pip/basecommand.py", line 211, in main
    status = self.run(options, args)
  File "/Users/Schmidt/anaconda/lib/python2.7/site-packages/pip/commands/install.py", line 305, in run
    wb.build(autobuilding=True)
  File "/Users/Schmidt/anaconda/lib/python2.7/site-packages/pip/wheel.py", line 705, in build
    self.requirement_set.prepare_files(self.finder)
  File "/Users/Schmidt/anaconda/lib/python2.7/site-packages/pip/req/req_set.py", line 334, in prepare_files
    functools.partial(self._prepare_file, finder))
  File "/Users/Schmidt/anaconda/lib/python2.7/site-packages/pip/req/req_set.py", line 321, in _walk_req_to_install
    more_reqs = handler(req_to_install)
  File "/Users/Schmidt/anaconda/lib/python2.7/site-packages/pip/req/req_set.py", line 491, in _prepare_file
    session=self.session)
  File "/Users/Schmidt/anaconda/lib/python2.7/site-packages/pip/download.py", line 825, in unpack_url
    session,
  File "/Users/Schmidt/anaconda/lib/python2.7/site-packages/pip/download.py", line 673, in unpack_http_url
    from_path, content_type = _download_http_url(link, session, temp_dir)
  File "/Users/Schmidt/anaconda/lib/python2.7/site-packages/pip/download.py", line 857, in _download_http_url
    stream=True,
  File "/Users/Schmidt/anaconda/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 477, in get
    return self.request('GET', url, **kwargs)
  File "/Users/Schmidt/anaconda/lib/python2.7/site-packages/pip/download.py", line 373, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/Users/Schmidt/anaconda/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/Schmidt/anaconda/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/Users/Schmidt/anaconda/lib/python2.7/site-packages/pip/_vendor/cachecontrol/adapter.py", line 46, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/Users/Schmidt/anaconda/lib/python2.7/site-packages/pip/_vendor/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

 I've installed openssl (1.0.2d) through homebrew.

Tried with bazel: `bazel build -c opt //tensorflow/tools/pip_package:build_pip_package` and the following error pops up:
`ERROR: no such package 'tensorflow/tools/pip_package': BUILD file not found on package path.`
I've got tensorflow running with docker but I want it in the host machine.

**Comment by iRapha** [comment]
This person seems to have had the same problem: https://github.com/tensorflow/tensorflow/issues/64#issuecomment-155270240

They solved it by downloading .whl file manually ( https://storage.googleapis.com/tensorflow/mac/tensorflow-0.5.0-py2-none-any.whl ) and run $pip install tensorflow-0.5.0-py2-none-any.whl

For other common OS X installation issues and troubleshooting: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md#on-macosx-

**Comment by phsieh** [comment]
Thanks for posting the problem and the solution.  I had the exact same problem and the solution given worked for me as well.

**Comment by Q-VISIONS** [comment]
Still works. Thanks

**Comment by arustagi** [comment]
Installing easy_install and upgrading setup-tools also solves the issue. 
Use command: `curl https://bootstrap.pypa.io/ez_setup.py -o - | python` (https://pythonhosted.org/setuptools/easy_install.html#installing-easy-install).

**Comment by asimjalis** [comment]
@arustagi’s solution worked for me. This is with TensorFlow version `tensorflow-0.7.1`.

**Comment by mattdns100689** [comment]
@iRapha This worked perfectly thanks.

**Comment by Heepo** [comment]
@iRapha Worked for me perfectly with tensorflow-0.9.0.

**Comment by mangate** [comment]
@arustagi’s solution worked for me. This is with TensorFlow version tensorflow-0.10.0rc0

**Comment by brando90** [comment]
Has anyone experienced this issue in Linux? I'm having this issue in a linux box.

**Comment by wingated** [comment]
@brando90 I had a similar issue on a Linux box - fixed it by running

```
pip install --upgrade $TF_BINARY_URL
pip install -I --upgrade setuptools
pip install --upgrade $TF_BINARY_URL

```

**Comment by jvanlier** [comment]
Just had this issue with pip 8.1.2./Conda 4.2.7/Python 3.5.2 on a Mac (OS X 10.11.4) in a fresh conda env. The solution @wingated posted for Linux worked for me.

**Comment by yselivonchyk** [comment]
Had the same issue with conda virtual environment. Solved it using suggestion by https://github.com/ContinuumIO/anaconda-issues/issues/542
In short, next line before upgrading the tensorflow does the trick:
`pip install --upgrade --ignore-installed setuptools `

**Comment by rodrigocava** [comment]
@yselivonchyk worked for me ! Thanks ! 👍

**Comment by StuartAxelOwen** [comment]
@yselivonchyk awesome - I came here with a similar problem with conda, but when trying to install the google cloud pubsub client lib.

**Comment by arccoder** [comment]
@yselivonchyk solution worked for me. 
Installing tensorflow-0.12 on windows.

**Comment by miladm** [comment]
arustagi's solution worked for me.

**Comment by amamh** [comment]
@yselivonchyk finally... thank you

**Comment by Nothing190** [comment]
@yselivonchyk thank you, now it works =)

**Comment by lininglouis** [comment]
@yselivonchyk   works great!

**Comment by aryanbhardwaj** [comment]
@yselivonchyk, solution worked for me thank you.

**Comment by onceupon** [comment]
@yselivonchyk, finally worked!! thanks!!!!!

**Comment by anemochore** [comment]
@yselivonchyk Thanks! Now the error was solved. TensorFlow 1.0.0(CPU) on Anaconda 4.2(Python 3.5.2) with Win8.1 64bit.

**Comment by xujin1982** [comment]
@yselivonchyk Thanks! Error problem was solved. Anaconda 4.2.12 Python 2.7 with Win7 64bit

**Comment by alexband** [comment]
@yeslivonchyk works for me

**Comment by alexband** [comment]
@yselivonchyk works for me
