### ISSUE TITLE
Importing TF in Python yields 'cannot import name 'build_info'

### ISSUE THREAD

**Issue by tsoernes** [tensorflow/tensorflow#13526]
### System information
Fedora 26 x64 (4.13.4-200.fc26.x86_64)
Tensorflow installed from source:
```
tf.VERSION = 1.3.0
tf.GIT_VERSION = b'v1.3.0-rc1-3011-gd86448938'
tf.COMPILER_VERSION = b'v1.3.0-rc1-3011-gd86448938'
```
Python version 3.6.2 (Anaconda)
Bazel installed from their Fedora/COPR repositories, version 0.6.0- (@non-git)
No CUDA (or compatible GPU)
Intel MKL 2018.0.128
c++ (GCC) 7.2.1 20170915 (Red Hat 7.2.1-2)
`bazel build -c opt --config=mkl //tensorflow/tools/pip_package:build_pip_package`
Notice the `mkl` flag in the bazel build

### Describe the problem
Configuration and bazel build finished without error. When attempting to import tensorflow in Python, I get this:

```
>>> import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/torstein/progs/tensorflow/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/home/torstein/progs/tensorflow/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/torstein/progs/tensorflow/tensorflow/python/pywrap_tensorflow.py", line 25, in <module>
    from tensorflow.python.platform import self_check
  File "/home/torstein/progs/tensorflow/tensorflow/python/platform/self_check.py", line 24, in <module>
    from tensorflow.python.platform import build_info
ImportError: cannot import name 'build_info'
```

**Comment by mrry** [comment]
Does this only affect `--config=mkl` builds?

**Comment by mrry** [comment]
Actually, is `/home/torstein/progs/tensorflow` the directory in which you built TensorFlow?

**Comment by tsoernes** [comment]
Yes, that is correct

2017-10-06 17:50 GMT+02:00 Derek Murray <notifications@github.com>:

**Comment by mrry** [comment]
OK, I think it should work if you `cd` out of that directory. `build_info.py` is a generated file and from the stack trace it looks like Python is trying to `import tensorflow` from the source tree, which doesn't contain any generated files.

This has tripped us up before, and `build_info` recently became the first generated file that we attempt to import. I've sent PR #13528 to add a better error message.

**Comment by tsoernes** [comment]
You were right. Starting Python from another directory does not result in the error.

Thank you

**Comment by mrry** [comment]
Thanks for confirming (and for raising the issue in the first place... now we have a much better error message in place)!

**Comment by DhaneshKumarHeerani** [comment]
Hi,
 can anyone tell me how can fix this error  


C:\Users\Dhanesh\Desktop\Check it Please\ChatterBot-master\examples\django_app>python manage.py
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\Dhanesh\AppData\Local\Programs\Python\Python35\lib\site-packages\django\core\management\__init__.py", line 350, in execute_from_command_line
    utility.execute()
  File "C:\Users\Dhanesh\AppData\Local\Programs\Python\Python35\lib\site-packages\django\core\management\__init__.py", line 324, in execute
    django.setup()
  File "C:\Users\Dhanesh\AppData\Local\Programs\Python\Python35\lib\site-packages\django\__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\Dhanesh\AppData\Local\Programs\Python\Python35\lib\site-packages\django\apps\registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "C:\Users\Dhanesh\AppData\Local\Programs\Python\Python35\lib\site-packages\django\apps\config.py", line 116, in create
    mod = import_module(mod_path)
  File "C:\Users\Dhanesh\AppData\Local\Programs\Python\Python35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 944, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "C:\Users\Dhanesh\AppData\Local\Programs\Python\Python35\lib\site-packages\chatterbot-0.7.6-py3.5.egg\chatterbot\__init__.py", line 4, in <module>
  File "C:\Users\Dhanesh\AppData\Local\Programs\Python\Python35\lib\site-packages\chatterbot-0.7.6-py3.5.egg\chatterbot\chatterbot.py", line 4, in <module>
  File "C:\Users\Dhanesh\AppData\Local\Programs\Python\Python35\lib\site-packages\chatterbot-0.7.6-py3.5.egg\chatterbot\input\__init__.py", line 2, in <module>
  File "C:\Users\Dhanesh\AppData\Local\Programs\Python\Python35\lib\site-packages\chatterbot-0.7.6-py3.5.egg\chatterbot\input\microsoft.py", line 4, in <module>
ImportError: cannot import name 'Statement'
