### ISSUE TITLE
AttributeError: 'SummaryMetadata' object has no attribute 'display_name' ; windows10 (64bit), install tensorflow (1.3.0rc0) in Anaconda python36  with tensorflow-tensorboard (0.1.7) on win10

### ISSUE THREAD

**Issue by SusieZ** [tensorflow/tensorflow#13585]
My laptop OS is windows10 (64bit), install tensorflow (1.3.0rc0) in Anaconda python36  with tensorflow-tensorboard (0.1.7) in it. when run command " tensorboard --logdir="path//to//logs", met below error.

```
Exception in thread Reloader:
Traceback (most recent call last):
  File "c:\soft_app\anaconda3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "c:\soft_app\anaconda3\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "c:\soft_app\anaconda3\lib\site-packages\tensorboard\backend\application.py", line 327, in _reload_forever
    reload_multiplexer(multiplexer, path_to_run)
  File "c:\soft_app\anaconda3\lib\site-packages\tensorboard\backend\application.py", line 301, in reload_multiplexer
    multiplexer.Reload()
  File "c:\soft_app\anaconda3\lib\site-packages\tensorboard\backend\event_processing\plugin_event_multiplexer.py", line 195, in Reload
    accumulator.Reload()
  File "c:\soft_app\anaconda3\lib\site-packages\tensorboard\backend\event_processing\plugin_event_accumulator.py", line 189, in Reload
    self._ProcessEvent(event)
  File "c:\soft_app\anaconda3\lib\site-packages\tensorboard\backend\event_processing\plugin_event_accumulator.py", line 335, in _ProcessEvent
    value = data_compat.migrate_value(value)
  File "c:\soft_app\anaconda3\lib\site-packages\tensorboard\data_compat.py", line 57, in migrate_value
    return handler(value) if handler else value
  File "c:\soft_app\anaconda3\lib\site-packages\tensorboard\data_compat.py", line 69, in _migrate_histogram_value
    display_name=value.metadata.display_name or value.tag,
AttributeError: 'SummaryMetadata' object has no attribute 'display_name'
```

**Comment by reedwm** [comment]
Please file this issue in the TensorBoard repository [here](https://github.com/tensorflow/tensorboard).
