### ISSUE TITLE
Keras + tfdbg error: Dump root directory does not exist

### ISSUE THREAD

**Issue by Joshuaalbert** [tensorflow/tensorflow#13604]
# Problem
I'm running the tf debugger and specifically am looking for nans and infs.
I'm doing this from keras using the tf backend by setting the keras sess to tf.Session wrapped with the debugger. 

## MVCE
```
    import tensorflow as tf
    from keras import Input
    from keras import backend as keras_backend

    inputs = Input((1,1))
    nan_ = keras_backend.log(inputs * 0)
    model = Model(inputs,nan_)
    model.compile(loss='mse',optimizer='sgd')
   
    from tensorflow.python import debug as tf_debug
    sess = tf_debug.LocalCLIDebugWrapperSession(tf.Session())
    #Add filter for nans and infs
    sess.add_tensor_filter("has_inf_or_nan", tf_debug.has_inf_or_nan)
    keras_backend.set_session(sess)

    import numpy as np
    model.fit(np.zeros([1,1,1]), np.zeros([1,1,1])) 
```
Inside the debugger execute `run -f has_inf_or_nan`.

## Traceback 

OSError: Dump root directory /tmp/tfdbg_dm3xvee9 does not exist. 

## Additional info

#7615 references the same error a while ago, and gives similar traceback.

## System information

Have I written custom code (as opposed to using a stock example script provided in TensorFlow): 
No.

OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 
Linux Fedora 4.11.5-200.fc25.x86_64

TensorFlow installed from (source or binary): 
binary

TensorFlow version (use command below): 
tf.VERSION = 1.3.0
tf.GIT_VERSION = v1.3.0-rc2-20-g0787eee
tf.COMPILER_VERSION = v1.3.0-rc2-20-g0787eee
Sanity check: array([1], dtype=int32)

Python version:
3.6

CUDA/cuDNN version:
Cuda 8.0, cuDNN v6

GPU model and memory:
Quadro M2000M, 4042MiB

**Comment by printdhruv** [comment]
Can you please follow [template](https://github.com/tensorflow/tensorflow/blob/master/ISSUE_TEMPLATE.md) so that can have more information?

**Comment by ed-alertedh** [comment]
I'm also getting this error on TF GPU 1.4.0, Python 3.6.3 x64 on Windows 10 x64

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by sandrejev** [comment]
I also had the same issue. I'm running Ubuntu 17.10 in virtual machine (VMWare) and I am getting this error every time TF code is executed (Keras in my case). Actually, I created a folder with sticky bit to see where will tfdbg fail and here is the output

Traceback (most recent call last):
  File "lesson8_yolo.py", line 133, in <module>
    tensorboard.set_model(model)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/_impl/keras/callbacks.py", line 673, in set_model
    self.sess = K.get_session()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/_impl/keras/backend.py", line 376, in get_session
    _initialize_variables(session)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/_impl/keras/backend.py", line 554, in _initialize_variables
    [variables_module.is_variable_initialized(v) for v in candidate_vars])
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/debug/wrappers/framework.py", line 543, in run
    run_end_resp = self.on_run_end(run_end_req)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/debug/wrappers/local_cli_wrapper.py", line 330, in on_run_end
    self._remove_dump_root()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/debug/wrappers/local_cli_wrapper.py", line 357, in _remove_dump_root
    shutil.rmtree(self._dump_root)
  File "/usr/lib/python3.6/shutil.py", line 484, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/usr/lib/python3.6/shutil.py", line 482, in rmtree
    os.rmdir(path)
PermissionError: [Errno 1] Operation not permitted: '/tmp/debug/'

**Comment by caisq** [comment]
@Joshuaalbert Your code snippet gave the error: 

> TypeError: Output tensors to a Model must be Keras tensors. Found: Tensor("Log:0", shape=(?, 1, 1), dtype=float32)

So I slightly modified the code, by replacing keras_backend.log with a mundane Dense layer and tfdbg seems to work fine.

```python
import tensorflow as tf
from keras import Input
from keras import backend as keras_backend
from keras.models import Model
from keras.layers import Dense

inputs = Input((1,1))
output = Dense(1)(inputs)
model = Model(inputs, [output])
model.compile(loss='mse', optimizer='sgd')

from tensorflow.python import debug as tf_debug
sess = tf_debug.LocalCLIDebugWrapperSession(tf.Session())
#Add filter for nans and infs
sess.add_tensor_filter("has_inf_or_nan", tf_debug.has_inf_or_nan)
keras_backend.set_session(sess)

import numpy as np
model.fit(np.zeros([1,1,1]), np.zeros([1,1,1]))
```

My tensorflow version:  1.5.0-dev20171229 (I tried tensorflow 1.3.0 as well and it seems to work properly, too)
My keras version: 2.1.2.

**Comment by tensorflowbutler** [comment]
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by caisq** [comment]
No reply from @Joshuaalbert for 2+ weeks. I'm closing this PR. If someone experiences this issue again, feel free to re-open it.
