### ISSUE TITLE
Tensorflow issue 

### ISSUE THREAD

**Issue by maheshwarLigade** [tensorflow/tensorflow#1369]
For bugs/issues, please fill in the following.  The more information you
provide, the more likely we can help you.

### Environment info
Operating System:
OSx
If installed from binary pip package, provide:
pip, Virtualenv
1. Which pip package you installed.
2. The output from python -c "import tensorflow; print(tensorflow.__version__)".
0.7.1
If installed from sources, provide the commit hash:

### Steps to reproduce
1.activate the virtualenv
2.ipython nootebook
3.

### What have you tried?
1. (tensorflow) ➜  ~  ipython notebook

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

[TerminalIPythonApp] WARNING | Subcommand `ipython notebook` is deprecated and will be removed in future versions.
[TerminalIPythonApp] WARNING | You likely want to use `jupyter notebook`... continue in 5 sec. Press Ctrl-C to quit now.
Traceback (most recent call last):
  File "/Users/maheshwarligade/tensorflow/bin/ipython", line 9, in <module>
    load_entry_point('ipython==4.1.1', 'console_scripts', 'ipython')()
  File "/Users/maheshwarligade/tensorflow/lib/python3.5/site-packages/ipython-4.1.1-py3.5.egg/IPython/__init__.py", line 119, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/Users/maheshwarligade/tensorflow/lib/python3.5/site-packages/traitlets-4.1.0-py3.5.egg/traitlets/config/application.py", line 588, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-111>", line 2, in initialize
  File "/Users/maheshwarligade/tensorflow/lib/python3.5/site-packages/traitlets-4.1.0-py3.5.egg/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/maheshwarligade/tensorflow/lib/python3.5/site-packages/ipython-4.1.1-py3.5.egg/IPython/terminal/ipapp.py", line 297, in initialize
    super(TerminalIPythonApp, self).initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/Users/maheshwarligade/tensorflow/lib/python3.5/site-packages/traitlets-4.1.0-py3.5.egg/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/maheshwarligade/tensorflow/lib/python3.5/site-packages/ipython-4.1.1-py3.5.egg/IPython/core/application.py", line 401, in initialize
    self.parse_command_line(argv)
  File "/Users/maheshwarligade/tensorflow/lib/python3.5/site-packages/ipython-4.1.1-py3.5.egg/IPython/terminal/ipapp.py", line 292, in parse_command_line
    return super(TerminalIPythonApp, self).parse_command_line(argv)
  File "<decorator-gen-4>", line 2, in parse_command_line
  File "/Users/maheshwarligade/tensorflow/lib/python3.5/site-packages/traitlets-4.1.0-py3.5.egg/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/maheshwarligade/tensorflow/lib/python3.5/site-packages/traitlets-4.1.0-py3.5.egg/traitlets/config/application.py", line 485, in parse_command_line
    return self.initialize_subcommand(subc, subargv)
  File "/Users/maheshwarligade/tensorflow/lib/python3.5/site-packages/ipython-4.1.1-py3.5.egg/IPython/core/application.py", line 211, in initialize_subcommand
    return super(BaseIPythonApplication, self).initialize_subcommand(subc, argv)
  File "<decorator-gen-3>", line 2, in initialize_subcommand
  File "/Users/maheshwarligade/tensorflow/lib/python3.5/site-packages/traitlets-4.1.0-py3.5.egg/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/maheshwarligade/tensorflow/lib/python3.5/site-packages/traitlets-4.1.0-py3.5.egg/traitlets/config/application.py", line 416, in initialize_subcommand
    subapp = import_item(subapp)
  File "/Users/maheshwarligade/tensorflow/lib/python3.5/site-packages/ipython_genutils-0.1.0-py3.5.egg/ipython_genutils/importstring.py", line 31, in import_item
ImportError: No module named 'notebook'

**Comment by vrv** [comment]
This doesn't look like an issue with TensorFlow -- please comment if you disagree.

**Comment by maheshwarLigade** [comment]
This is not an issue with tensorflow but encounter when I fallow the udacity deep learning course.
How do I resolve that one?
