### ISSUE TITLE
freeze  model graph failure

### ISSUE THREAD

**Issue by zbpjlc** [tensorflow/tensorflow#13730]
I can generate the pbtxt,but freeze  model graph failure
I use tensorflow1.2

File "/Users/gouwei/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph", line 178, in <module>
    Main()
  File "/Users/gouwei/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph", line 117, in Main
    module_space = FindModuleSpace()
  File "/Users/gouwei/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph", line 91, in FindModuleSpace
    sys.argv[0])
AssertionError: Cannot find .runfiles directory for /Users/gouwei/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph
Traceback (most recent call last):
  File "/Users/gouwei/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph", line 178, in <module>
    Main()
  File "/Users/gouwei/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph", line 117, in Main
    module_space = FindModuleSpace()
  File "/Users/gouwei/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph", line 91, in FindModuleSpace
    sys.argv[0])
AssertionError: Cannot find .runfiles directory for /Users/gouwei/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph

**Comment by zbpjlc** [comment]
by the ways ,I use MAC 10.12.6

**Comment by andydavis1** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
