### ISSUE TITLE
AttributeError: 'module' object has no attribute 'random_crop'

### ISSUE THREAD

**Issue by sarah039** [tensorflow/tensorflow#1376]
I'm on using Ubuntu 14.04 and installed tensorflow. When I ran the image processing example as in the website, it failed complaining about random_crop not found. I took the code from here 
https://github.com/tensorflow/tensorflow/blob/r0.7/tensorflow/models/image/cifar10/

Here's the exception stack:

```
Traceback (most recent call last):
  File "cifar10_train.py", line 136, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/default/_app.py", line 11, in run
    sys.exit(main(sys.argv))
  File "cifar10_train.py", line 132, in main
    train()
  File "cifar10_train.py", line 67, in train
    images, labels = cifar10.distorted_inputs()
  File "/home/sarah/Documents/SVHN/cifar10.py", line 150, in distorted_inputs
    batch_size=FLAGS.batch_size)
  File "/home/sarah/Documents/SVHN/cifar10_input.py", line 161, in distorted_inputs
    distorted_image = tf.random_crop(reshaped_image, [height, width, 3])
AttributeError: 'module' object has no attribute 'random_crop'

```

**Comment by vrv** [comment]
what version of tensorflow do you have?  We renamed tf.image.random_crop to tf.random_crop between 0.6 to 0.7 -- upgrading should solve the problem, or checking out the code at the 0.6.0 branch if you don't want to upgrade.

**Comment by 14251104246** [comment]
@vrv 
I upgrade the code to TensorFlow 1.0,and it is successful.
But affter i run `python cifar10_train.py`,it throw error.

**upgrade message**

```
python ../../tensorflow/tensorflow/tools/compatibility/tf_upgrade.py --infile cifar10_input.py --outfile cifar10_input2.py --copyotherfiles True
TensorFlow 1.0 Upgrade Script
-----------------------------
Converted 1 files

Detected 0 errors that require attention
--------------------------------------------------------------------------------


Make sure to read the detailed log 'report.txt' 
```


**run message**
```
python cifar10_train.py
Traceback (most recent call last):
  File "cifar10_train.py", line 138, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 124, in run
    _sys.exit(main(argv))
  File "cifar10_train.py", line 134, in main
    train()
  File "cifar10_train.py", line 69, in train
    images, labels = cifar10.distorted_inputs()
  File "../../cifar10.py", line 139, in distorted_inputs
    batch_size=FLAGS.batch_size)
  File "../../cifar10_input2.py", line 156, in distorted_inputs
    distorted_image = tf.random_crop([reshaped_image,[height, width]], 10)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/random_ops.py", line 302, in random_crop
    value = ops.convert_to_tensor(value, name="value")
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 932, in convert_to_tensor
    as_ref=False)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1022, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 1001, in _autopacking_conversion_function
    return _autopacking_helper(v, inferred_dtype, name or "packed")
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 964, in _autopacking_helper
    return gen_array_ops._pack(elems_as_tensors, name=scope)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 2928, in _pack
    "Pack", values=values, axis=axis, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3162, in create_op
    compute_device=compute_device)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3208, in _create_op_helper
    set_shapes_for_outputs(op)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2427, in set_shapes_for_outputs
    return _set_shapes_for_outputs(op)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2400, in _set_shapes_for_outputs
    shapes = shape_func(op)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2330, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/common_shapes.py", line 627, in call_cpp_shape_fn
    require_shape_fn)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/common_shapes.py", line 691, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Shapes must be equal rank, but are 3 and 1
        From merging shape 0 with other shapes. for 'random_crop/value' (op: 'Pack') with input shapes: [32,32,3], [2].
```
