### ISSUE TITLE
Import "google/protobuf/any.proto" was not found or had errors.

### ISSUE THREAD

**Issue by mike-aungsan** [tensorflow/tensorflow#13765]
make -f tensorflow/contrib/makefile/Makefile HOST_OS=PI TARGET=PI OPTFLAGS="-Os" CXX=g++-4.8
PROTOC = "protoc"
CC_PREFIX = ""
protoc  tensorflow/contrib/boosted_trees/proto/learner.proto --cpp_out /home/a_name/tensorflow/tensorflow/contrib/makefile/gen/proto/
protoc  tensorflow/contrib/boosted_trees/proto/quantiles.proto --cpp_out /home/a_name/tensorflow/tensorflow/contrib/makefile/gen/proto/
protoc  tensorflow/contrib/boosted_trees/proto/split_info.proto --cpp_out /home/a_name/tensorflow/tensorflow/contrib/makefile/gen/proto/
protoc  tensorflow/contrib/boosted_trees/proto/tree_config.proto --cpp_out /home/a_name/tensorflow/tensorflow/contrib/makefile/gen/proto/
protoc  tensorflow/core/util/test_log.proto --cpp_out /home/a_name/tensorflow/tensorflow/contrib/makefile/gen/proto/
google/protobuf/any.proto: File not found.
tensorflow/core/util/test_log.proto: Import "google/protobuf/any.proto" was not found or had errors.
tensorflow/core/util/test_log.proto:132:12: "google.protobuf.Any" is not defined.
make: *** [/home/a_name/tensorflow/tensorflow/contrib/makefile/gen/proto/tensorflow/core/util/test_log.pb.cc] Error 1

**Comment by drpngx** [comment]
Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?  Make sure you also include the exact command if possible to produce  the output included in your test case. If you are unclear what to include  see the issue template displayed in  [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

 We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!

**Comment by mike-aungsan** [comment]
OS -> Ubuntu 14.04.5 LTS (GNU/Linux 4.4.0-59-generic x86_64)
uname -r -> 4.4.0-59-generic
Python 2.7.6
pip --version ->  pip 1.5.4 from /usr/lib/python2.7/dist-packages (python 2.7)

gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.4-2ubuntu1~14.04.3' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3)

Build from tensorflow master branch by following these steps from this link ->
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/makefile#raspberry-pi

tensorflow/contrib/makefile/download_dependencies.sh
sudo apt-get install -y autoconf automake libtool gcc-4.8 g++-4.8
cd tensorflow/contrib/makefile/downloads/protobuf/
./autogen.sh
./configure
make
sudo make install
sudo ldconfig  # refresh shared library cache
cd ../../../../..
export HOST_NSYNC_LIB=`tensorflow/contrib/makefile/compile_nsync.sh`
export TARGET_NSYNC_LIB="$HOST_NSYNC_LIB"

But none of the following command work and have the error that I report.

make -f tensorflow/contrib/makefile/Makefile HOST_OS=PI TARGET=PI OPTFLAGS="-Os" CXX=g++-4.8

make -f tensorflow/contrib/makefile/Makefile HOST_OS=PI TARGET=PI \
 OPTFLAGS="-Os -mfpu=neon-vfpv4 -funsafe-math-optimizations -ftree-vectorize" CXX=g++-4.8

Cannot import tensorflow too in python

python
Python 2.7.6 (default, Oct 26 2016, 20:30:19)
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "tensorflow/python/pywrap_tensorflow.py", line 25, in <module>
    from tensorflow.python.platform import self_check
ImportError: No module named platform

**Comment by mike-aungsan** [comment]
bazel version
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_us.UTF-8)
WARNING: ignoring http_proxy in environment.
Build label: 0.6.1
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Oct 5 21:54:59 2017 (1507240499)
Build timestamp: 1507240499
Build timestamp as int: 1507240499

I try this command but it does not work.

sudo -E bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package --verbose_failures


WARNING: Config values are not defined in any .rc file: opt
ERROR: /home/a_name/tensorflow.build/third_party/py/numpy/BUILD:11:1: no such package '@local_config_python//': Traceback (most recent call last):
        File "/home/a_name/tensorflow.build/third_party/py/python_configure.bzl", line 310
                _create_local_python_repository(repository_ctx)
        File "/home/a_name/tensorflow.build/third_party/py/python_configure.bzl", line 268, in _create_local_python_repository
                _get_python_bin(repository_ctx)
        File "/home/a_name/tensorflow.build/third_party/py/python_configure.bzl", line 166, in _get_python_bin
                _get_env_var(repository_ctx, _PYTHON_BIN_PATH, No..., ...)
        File "/home/a_name/tensorflow.build/third_party/py/python_configure.bzl", line 49, in _get_env_var
                _python_configure_fail(("'%s' environment variable is n...))
        File "/home/a_name/tensorflow.build/third_party/py/python_configure.bzl", line 37, in _python_configure_fail
                fail(("%sPython Configuration Error:%...)))
Python Configuration Error: 'PYTHON_BIN_PATH' environment variable is not set
 and referenced by '//third_party/py/numpy:headers'
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted
INFO: Elapsed time: 4.234s
FAILED: Build did NOT complete successfully (25 packages loaded)
    currently loading: tensorflow/core

**Comment by drpngx** [comment]
No, you need to run the pip install as root, not build the pip package. Please follow the instructions.

**Comment by vahidn83** [comment]
I have the same issue using TF 1.4.0 with python 2.7 (via venv). I use Centos 7, CUDA 9, CNDNN 7 and GCC 4.8.5

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue? Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by drpngx** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by mmacdermaid** [comment]
Stumbled on this issue for a similar problem and realized I wasn't including the base includes from the protoc zip.

protoc-3.6.1-linux-x86_64.zip unzips with

````
~/bin/protoc$ ls -lh
total 1.4M
drwxr-xr-x 2 mmacdermaid mmacdermaid 4.0K Jul 30 15:49 bin
drwxr-xr-x 3 mmacdermaid mmacdermaid 4.0K Jul 30 15:49 include
-rw-rw-r-- 1 mmacdermaid mmacdermaid 1.4M Nov  5 16:04 protoc-3.6.1-linux-x86_64.zip
-rw-r--r-- 1 mmacdermaid mmacdermaid  715 Jul 30 15:49 readme.txt
````

Which the readme does say
````
If you intend to use the included well known types then don't forget to
copy the contents of the 'include' directory somewhere as well, for example
into '/usr/local/include/'.
````

But who reads those?

If you don't add them into /usr/local/include you have to explicitly include them via protoc options
````
protoc -I ~/bin/protoc/include
````

Hope this helps someone.

**Comment by drpngx** [comment]
Note that we have our own protobuf text serialization within tensorflow and that it doesn't support any. The closest is to use a map of Attr.

**Comment by jezzadiaz** [comment]
This was fixed when we upgraded our protoc version. Thanks
protoc --version
libprotoc 3.6.0

**Comment by yangyuan6** [comment]
fixed:
cd ~ && mkdir pb && cd pb && git clo https://github.com/protocolbuffers/protobuf.git
protoc proto/example.proto     --go_out=. --go-grpc_out=. --zrpc_out=.  -I=~/pb/protobuf/src -I={ proto/example.proto directory }
