### ISSUE TITLE
program could not run in docker but could run on local machine

### ISSUE THREAD

**Issue by guotong1988** [tensorflow/tensorflow#13778]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 
CentOS7 in local machine
Ubuntu 16.04.2 LTS in docker image
- **TensorFlow installed from (source or binary)**:
- **TensorFlow version (use command below)**:
v1.3.0-rc0-33-g6f0d70e 1.3.0-rc1
- **Python version**: 
3.5.3
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:
8.0 6.0
- **GPU model and memory**:
M40 24G

### Describe the problem
I could run my program on local machine, but can not run on docker(ubuntu image).

the stacktrace of the program in nvidia-docker:

```
2017-10-17 09:02:50.757982: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Incompatible shapes: [32,1,400] vs. [32,1,213]
	 [[Node: grads_0/gradients/model_0/main/logits2/exp_mask_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape, grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape_1)]]
2017-10-17 09:02:50.758004: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Incompatible shapes: [32,1,400] vs. [32,1,213]
	 [[Node: grads_0/gradients/model_0/main/logits2/exp_mask_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape, grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape_1)]]
2017-10-17 09:02:50.758020: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Incompatible shapes: [32,1,400] vs. [32,1,213]
	 [[Node: grads_0/gradients/model_0/main/logits2/exp_mask_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape, grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape_1)]]
2017-10-17 09:02:50.758052: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Incompatible shapes: [32,1,400] vs. [32,1,213]
	 [[Node: grads_0/gradients/model_0/main/logits2/exp_mask_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape, grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape_1)]]
2017-10-17 09:02:50.758073: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Incompatible shapes: [32,1,400] vs. [32,1,213]
	 [[Node: grads_0/gradients/model_0/main/logits2/exp_mask_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape, grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape_1)]]
2017-10-17 09:02:50.758089: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Incompatible shapes: [32,1,400] vs. [32,1,213]
	 [[Node: grads_0/gradients/model_0/main/logits2/exp_mask_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape, grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape_1)]]
2017-10-17 09:02:50.758134: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Incompatible shapes: [32,1,400] vs. [32,1,213]
	 [[Node: grads_0/gradients/model_0/main/logits2/exp_mask_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape, grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape_1)]]
2017-10-17 09:02:50.758154: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Incompatible shapes: [32,1,400] vs. [32,1,213]
	 [[Node: grads_0/gradients/model_0/main/logits2/exp_mask_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape, grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape_1)]]
2017-10-17 09:02:50.758178: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Incompatible shapes: [32,1,400] vs. [32,1,213]
	 [[Node: grads_0/gradients/model_0/main/logits2/exp_mask_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape, grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape_1)]]
2017-10-17 09:02:50.758209: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Incompatible shapes: [32,1,400] vs. [32,1,213]
	 [[Node: grads_0/gradients/model_0/main/logits2/exp_mask_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape, grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape_1)]]
2017-10-17 09:02:50.758229: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Incompatible shapes: [32,1,400] vs. [32,1,213]
	 [[Node: grads_0/gradients/model_0/main/logits2/exp_mask_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape, grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape_1)]]
2017-10-17 09:02:50.758246: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Incompatible shapes: [32,1,400] vs. [32,1,213]
	 [[Node: grads_0/gradients/model_0/main/logits2/exp_mask_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape, grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape_1)]]
2017-10-17 09:02:50.758289: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Incompatible shapes: [32,1,400] vs. [32,1,213]
	 [[Node: grads_0/gradients/model_0/main/logits2/exp_mask_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape, grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape_1)]]
2017-10-17 09:02:50.758323: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Incompatible shapes: [32,1,400] vs. [32,1,213]
	 [[Node: grads_0/gradients/model_0/main/logits2/exp_mask_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape, grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape_1)]]
2017-10-17 09:02:50.758337: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Incompatible shapes: [32,1,400] vs. [32,1,213]
	 [[Node: grads_0/gradients/model_0/main/logits2/exp_mask_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape, grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape_1)]]
2017-10-17 09:02:50.758464: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Incompatible shapes: [32,1,400] vs. [32,1,213]
	 [[Node: grads_0/gradients/model_0/main/logits2/exp_mask_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape, grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape_1)]]
2017-10-17 09:02:50.758500: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Incompatible shapes: [32,1,400] vs. [32,1,213]
	 [[Node: grads_0/gradients/model_0/main/logits2/exp_mask_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape, grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape_1)]]
2017-10-17 09:02:50.758532: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Incompatible shapes: [32,1,400] vs. [32,1,213]
	 [[Node: grads_0/gradients/model_0/main/logits2/exp_mask_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape, grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape_1)]]
2017-10-17 09:02:50.758562: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Incompatible shapes: [32,1,400] vs. [32,1,213]
	 [[Node: grads_0/gradients/model_0/main/logits2/exp_mask_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape, grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape_1)]]
2017-10-17 09:02:50.758593: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Incompatible shapes: [32,1,400] vs. [32,1,213]
	 [[Node: grads_0/gradients/model_0/main/logits2/exp_mask_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape, grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape_1)]]
2017-10-17 09:02:50.758624: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Incompatible shapes: [32,1,400] vs. [32,1,213]
	 [[Node: grads_0/gradients/model_0/main/logits2/exp_mask_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape, grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape_1)]]
2017-10-17 09:02:50.758851: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Incompatible shapes: [32,1,400] vs. [32,1,213]
	 [[Node: grads_0/gradients/model_0/main/logits2/exp_mask_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape, grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape_1)]]
2017-10-17 09:02:50.758876: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Incompatible shapes: [32,1,400] vs. [32,1,213]
	 [[Node: grads_0/gradients/model_0/main/logits2/exp_mask_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape, grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape_1)]]
2017-10-17 09:02:50.758891: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Incompatible shapes: [32,1,400] vs. [32,1,213]
	 [[Node: grads_0/gradients/model_0/main/logits2/exp_mask_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape, grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape_1)]]
2017-10-17 09:02:50.758922: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Incompatible shapes: [32,1,400] vs. [32,1,213]
	 [[Node: grads_0/gradients/model_0/main/logits2/exp_mask_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape, grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape_1)]]
2017-10-17 09:02:50.758942: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Incompatible shapes: [32,1,400] vs. [32,1,213]
	 [[Node: grads_0/gradients/model_0/main/logits2/exp_mask_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape, grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape_1)]]
2017-10-17 09:02:50.758957: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Incompatible shapes: [32,1,400] vs. [32,1,213]
	 [[Node: grads_0/gradients/model_0/main/logits2/exp_mask_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape, grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape_1)]]
2017-10-17 09:02:50.758986: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Incompatible shapes: [32,1,400] vs. [32,1,213]
	 [[Node: grads_0/gradients/model_0/main/logits2/exp_mask_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape, grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape_1)]]
2017-10-17 09:02:50.759006: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Incompatible shapes: [32,1,400] vs. [32,1,213]
	 [[Node: grads_0/gradients/model_0/main/logits2/exp_mask_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape, grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape_1)]]
2017-10-17 09:02:50.759021: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Incompatible shapes: [32,1,400] vs. [32,1,213]
	 [[Node: grads_0/gradients/model_0/main/logits2/exp_mask_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape, grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape_1)]]
2017-10-17 09:02:50.759065: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Incompatible shapes: [32,1,400] vs. [32,1,213]
	 [[Node: grads_0/gradients/model_0/main/logits2/exp_mask_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape, grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape_1)]]
2017-10-17 09:02:50.759085: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Incompatible shapes: [32,1,400] vs. [32,1,213]
	 [[Node: grads_0/gradients/model_0/main/logits2/exp_mask_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape, grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape_1)]]
2017-10-17 09:02:50.759100: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Incompatible shapes: [32,1,400] vs. [32,1,213]
	 [[Node: grads_0/gradients/model_0/main/logits2/exp_mask_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape, grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape_1)]]
2017-10-17 09:02:50.759129: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Incompatible shapes: [32,1,400] vs. [32,1,213]
	 [[Node: grads_0/gradients/model_0/main/logits2/exp_mask_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape, grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape_1)]]
2017-10-17 09:02:50.759149: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Incompatible shapes: [32,1,400] vs. [32,1,213]
	 [[Node: grads_0/gradients/model_0/main/logits2/exp_mask_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape, grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape_1)]]
2017-10-17 09:02:50.759170: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Incompatible shapes: [32,1,400] vs. [32,1,213]
	 [[Node: grads_0/gradients/model_0/main/logits2/exp_mask_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape, grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape_1)]]
2017-10-17 09:02:50.759203: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Incompatible shapes: [32,1,400] vs. [32,1,213]
	 [[Node: grads_0/gradients/model_0/main/logits2/exp_mask_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape, grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape_1)]]
2017-10-17 09:02:50.759223: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Incompatible shapes: [32,1,400] vs. [32,1,213]
	 [[Node: grads_0/gradients/model_0/main/logits2/exp_mask_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape, grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape_1)]]
2017-10-17 09:02:50.759283: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Incompatible shapes: [32,1,400] vs. [32,1,213]
	 [[Node: grads_0/gradients/model_0/main/logits2/exp_mask_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape, grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape_1)]]
Traceback (most recent call last):
  File "/nfsdata/guotong_data/Py35/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1327, in _do_call
    return fn(*args)
  File "/nfsdata/guotong_data/Py35/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1306, in _run_fn
    status, run_metadata)
  File "/nfsdata/guotong_data/Py35/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/nfsdata/guotong_data/Py35/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [32,1,400] vs. [32,1,213]
	 [[Node: grads_0/gradients/model_0/main/logits2/exp_mask_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape, grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape_1)]]
	 [[Node: grads_0/gradients/AddN_2519/_461 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_289171_grads_0/gradients/AddN_2519", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nfsdata/guotong_data/bi-att-flow-dev/basic/cli.py", line 113, in <module>
    tf.app.run()
  File "/nfsdata/guotong_data/Py35/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/nfsdata/guotong_data/bi-att-flow-dev/basic/cli.py", line 110, in main
    m(config)
  File "/nfsdata/guotong_data/bi-att-flow-dev/basic/main.py", line 25, in main
    _train(config)
  File "/nfsdata/guotong_data/bi-att-flow-dev/basic/main.py", line 102, in _train
    loss, summary, train_op = trainer.step(sess, batches, get_summary=get_summary)
  File "/nfsdata/guotong_data/bi-att-flow-dev/basic/trainer.py", line 71, in step
    loss, train_op = sess.run([self.loss, self.train_op], feed_dict=feed_dict)
  File "/nfsdata/guotong_data/Py35/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/nfsdata/guotong_data/Py35/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "/nfsdata/guotong_data/Py35/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    options, run_metadata)
  File "/nfsdata/guotong_data/Py35/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [32,1,400] vs. [32,1,213]
	 [[Node: grads_0/gradients/model_0/main/logits2/exp_mask_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape, grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape_1)]]
	 [[Node: grads_0/gradients/AddN_2519/_461 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_289171_grads_0/gradients/AddN_2519", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Caused by op 'grads_0/gradients/model_0/main/logits2/exp_mask_grad/BroadcastGradientArgs', defined at:
  File "/nfsdata/guotong_data/bi-att-flow-dev/basic/cli.py", line 113, in <module>
    tf.app.run()
  File "/nfsdata/guotong_data/Py35/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/nfsdata/guotong_data/bi-att-flow-dev/basic/cli.py", line 110, in main
    m(config)
  File "/nfsdata/guotong_data/bi-att-flow-dev/basic/main.py", line 25, in main
    _train(config)
  File "/nfsdata/guotong_data/bi-att-flow-dev/basic/main.py", line 87, in _train
    trainer = MultiGPUTrainer(config, models)
  File "/nfsdata/guotong_data/bi-att-flow-dev/basic/trainer.py", line 52, in __init__
    grads = self.opt.compute_gradients(loss, var_list=self.var_list)
  File "/nfsdata/guotong_data/Py35/lib/python3.5/site-packages/tensorflow/python/training/optimizer.py", line 386, in compute_gradients
    colocate_gradients_with_ops=colocate_gradients_with_ops)
  File "/nfsdata/guotong_data/Py35/lib/python3.5/site-packages/tensorflow/python/ops/gradients_impl.py", line 542, in gradients
    grad_scope, op, func_call, lambda: grad_fn(op, *out_grads))
  File "/nfsdata/guotong_data/Py35/lib/python3.5/site-packages/tensorflow/python/ops/gradients_impl.py", line 348, in _MaybeCompile
    return grad_fn()  # Exit early
  File "/nfsdata/guotong_data/Py35/lib/python3.5/site-packages/tensorflow/python/ops/gradients_impl.py", line 542, in <lambda>
    grad_scope, op, func_call, lambda: grad_fn(op, *out_grads))
  File "/nfsdata/guotong_data/Py35/lib/python3.5/site-packages/tensorflow/python/ops/math_grad.py", line 689, in _AddGrad
    rx, ry = gen_array_ops._broadcast_gradient_args(sx, sy)
  File "/nfsdata/guotong_data/Py35/lib/python3.5/site-packages/tensorflow/python/ops/gen_array_ops.py", line 395, in _broadcast_gradient_args
    name=name)
  File "/nfsdata/guotong_data/Py35/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/nfsdata/guotong_data/Py35/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/nfsdata/guotong_data/Py35/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

...which was originally created as op 'model_0/main/logits2/exp_mask', defined at:
  File "/nfsdata/guotong_data/bi-att-flow-dev/basic/cli.py", line 113, in <module>
    tf.app.run()
[elided 2 identical lines from previous traceback]
  File "/nfsdata/guotong_data/bi-att-flow-dev/basic/main.py", line 25, in main
    _train(config)
  File "/nfsdata/guotong_data/bi-att-flow-dev/basic/main.py", line 84, in _train
    models = get_multi_gpu_models_new(config)
  File "/nfsdata/guotong_data/bi-att-flow-dev/basic/model_fusion.py", line 23, in get_multi_gpu_models_new
    model = Model(config, scope, rep=gpu_idx == 0)
  File "/nfsdata/guotong_data/bi-att-flow-dev/basic/model_fusion.py", line 75, in __init__
    self._build_forward()
  File "/nfsdata/guotong_data/bi-att-flow-dev/basic/model_fusion.py", line 223, in _build_forward
    is_train=self.is_train, func=config.answer_func, scope='logits2')
  File "/nfsdata/guotong_data/bi-att-flow-dev/my/tensorflow/nn.py", line 107, in get_logits
    is_train=is_train)
  File "/nfsdata/guotong_data/bi-att-flow-dev/my/tensorflow/nn.py", line 83, in linear_logits
    logits = exp_mask(logits, mask)
  File "/nfsdata/guotong_data/bi-att-flow-dev/my/tensorflow/general.py", line 138, in exp_mask
    return tf.add(val, (1 - tf.cast(mask, 'float')) * VERY_NEGATIVE_NUMBER, name=name)
  File "/nfsdata/guotong_data/Py35/lib/python3.5/site-packages/tensorflow/python/ops/gen_math_ops.py", line 82, in add
    result = _op_def_lib.apply_op("Add", x=x, y=y, name=name)
  File "/nfsdata/guotong_data/Py35/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)

InvalidArgumentError (see above for traceback): Incompatible shapes: [32,1,400] vs. [32,1,213]
	 [[Node: grads_0/gradients/model_0/main/logits2/exp_mask_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape, grads_0/gradients/model_0/main/logits2/exp_mask_grad/Shape_1)]]
	 [[Node: grads_0/gradients/AddN_2519/_461 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_289171_grads_0/gradients/AddN_2519", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]


Process finished with exit code 1
```
the 213 of `[32,1,213]` in stacktrace may change to 160 or other number as I change the GPU type (M40-11G , P100-15G in nvidia-docker)

In local machine it could run without the stacktrace above.

**Comment by guotong1988** [comment]
The main reason may be the lines below , which is added by me.
```
q_j_400 = []
        for j in range(400):
            q_j_400.append(tf.squeeze(tf.matmul(tf.transpose(u,[0,2,1]),tf.expand_dims(tf.nn.softmax(u_logits[j]),-1)),[2])) # each element [32,200,30],[32,30,1]
```
Note that the stacktrace doesn't point to the lines above.

**Comment by guotong1988** [comment]
Sorry, It is my fault.
Something wrong with my code.
I haven't copy the whole folder from local machine to docker image.
I only copy one edited python file.
Although I don't know the exact reason.
But it is not the problem with the local machine and docker.
It does **could run** on docker if I copy the whole folder from local machine to docker image.
