### ISSUE TITLE
ERROR:tensorflow:Exception in QueueRunner: truncated record at 935047

### ISSUE THREAD

**Issue by wengqi123** [tensorflow/tensorflow#13773]
```
###########################small data train, train_step code:
def run_train():
    with tf.Graph().as_default():
        global_step = tf.Variable(0, trainable=False)
        images,labels=read_and_decode('./dog_train')
        images_batch,labels_batch = add_batch(images,labels,5,5)
        softmax_linear = cnn_model(images_batch)
        loss = loss(softmax_linear, labels_batch)
        train_op = train(loss, global_step)
        saver = tf.train.Saver(tf.global_variables())
        summary_op = tf.summary.merge_all()
        init = tf.global_variables_initializer()
        sess = tf.Session(config=tf.ConfigProto(log_device_placement=FLAGS.log_device_placement))
        sess.run(init)
        tf.train.start_queue_runners(sess=sess)
        summary_writer = tf.summary.FileWriter(FLAGS.train_dir,graph=sess.graph)
        for step in xrange(FLAGS.max_steps):
            start_time = time.time()
            _, loss_value = sess.run([train_op, loss])
            duration = time.time() - start_time
            assert not np.isnan(loss_value), 'Model diverged with loss = NaN'
            if step % 10 == 0:
                num_examples_per_step = FLAGS.batch_size
                examples_per_sec = num_examples_per_step / duration
                sec_per_batch = float(duration)

                format_str = ('%s: step %d, loss = %.2f (%.1f examples/sec; %.3f ''sec/batch)')
                print(format_str % (datetime.now(), step, loss_value,examples_per_sec, sec_per_batch))
            if step % 100 == 0:
                summary_str = sess.run(summary_op)
                summary_writer.add_summary(summary_str, step)
            if step % 1000 == 0 or (step + 1) == FLAGS.max_steps:
                checkpoint_path = os.path.join(FLAGS.train_dir, 'model.ckpt')
                saver.save(sess,checkpoint_path, global_step=step)
#######################################and ERROR:
2017-10-17 15:08:31.510128: W tensorflow/stream_executor/cuda/cuda_driver.cc:485] creating context when one is currently active; existing: 0x46f9230
ERROR:tensorflow:Exception in QueueRunner: truncated record at 935047
	 [[Node: ReaderReadV2 = ReaderReadV2[_device="/job:localhost/replica:0/task:0/cpu:0"](TFRecordReaderV2, input_producer)]]
	 [[Node: DecodeRaw/_9 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_17_DecodeRaw", tensor_type=DT_UINT8, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/queue_runner_impl.py", line 237, in _run
    enqueue_callable()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1060, in _single_operation_run
    target_list_as_strings, status, None)
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
DataLossError: truncated record at 935047
	 [[Node: ReaderReadV2 = ReaderReadV2[_device="/job:localhost/replica:0/task:0/cpu:0"](TFRecordReaderV2, input_producer)]]
	 [[Node: DecodeRaw/_9 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_17_DecodeRaw", tensor_type=DT_UINT8, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

ERROR:tensorflow:Exception in QueueRunner: truncated record at 935047
	 [[Node: ReaderReadV2 = ReaderReadV2[_device="/job:localhost/replica:0/task:0/cpu:0"](TFRecordReaderV2, input_producer)]]
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/queue_runner_impl.py", line 237, in _run
    enqueue_callable()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1060, in _single_operation_run
    target_list_as_strings, status, None)
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
DataLossError: truncated record at 935047
	 [[Node: ReaderReadV2 = ReaderReadV2[_device="/job:localhost/replica:0/task:0/cpu:0"](TFRecordReaderV2, input_producer)]]

2017-10-17 15:08:49.270117: step 0, loss = 21.79 (0.6 examples/sec; 8.205 sec/batch)
 ############ here stop 
```
so,why this errors ?

**Comment by drpngx** [comment]
It looks like there is some error in the tf record. The queues are a little harder to debug.

Would you consider `tf.contrib.data.DataSet`? This is a much easier API.

**Comment by wengqi123** [comment]
hi,thanks for your help.
the enclosure is all the code,
I'm the beginner for the tensorflow,so I refer to other codes,and merge it ,
so where I did wrong in it?


祝好！


翁琦 

生物信息工程师 生信综合部 

深圳市海普洛斯生物科技有限公司
网址：www.haplox.cn
地址： 深圳市南山区高新北区松坪山路3号奥特迅电力大厦8楼
邮编：518055
手机：188 5041 5501      电话：400-999-8450

 
From: drpngx
Date: 2017-10-18 01:33
To: tensorflow/tensorflow
CC: wengqi123; Author
Subject: Re: [tensorflow/tensorflow] ERROR:tensorflow:Exception in QueueRunner: truncated record at 935047 (#13773)
It looks like there is some error in the tf record. The queues are a little harder to debug.
Would you consider tf.contrib.data.DataSet? This is a much easier API.

**Comment by wengqi123** [comment]
sorry ，So late to respond，it was my samples is samll，because when i Increase the number of samples ，it seems work，

**Comment by wengqi123** [comment]
sorry ，So late to respond，it seems my samples is small，because when i Increase the number of samples ，it seems work，

**Comment by wengqi123** [comment]
sorry ，So late to respond，it seems my samples is small，because when i Increase the number of samples ，it  works，

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue? Please update the label and/or status accordingly.

**Comment by drpngx** [comment]
It sounds like it works for you, closing this issue.
