### ISSUE TITLE
MonitoredSession.close() doesn't stop a thread when using SyncReplicasOptimizer hook

### ISSUE THREAD

**Issue by mjunyentb** [tensorflow/tensorflow#13779]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.3
- **Python version**: 3.5.2

### Describe the problem
If using SyncReplicasOptimizer, the MonitoredSession is not able to stop a thread when calling session.close(). It will wait the whole "stop_grace_period_secs" and then close, reporting that a thread could not be stopped:  `INFO:tensorflow:Coordinator stopped with threads still running: Thread-5` (the thread number may vary).

Here you can find the piece of code (reduced as much as possible) to reproduce it:

### Source code
```
import tensorflow as tf
import logging
logging.getLogger().setLevel(logging.INFO) #To see the message "Coordinator stopped with threads still running"

opt = tf.train.RMSPropOptimizer(1.0)
opt = tf.train.SyncReplicasOptimizer(opt, replicas_to_aggregate=1, total_num_replicas=1)
sync_hook = opt.make_session_run_hook(is_chief=True, num_tokens=0)

global_step = tf.train.create_global_step() #global_step is necessary for SyncReplicasOptimizer
var = tf.Variable(0.0) #dummy variable and gradient
grad = tf.constant(1.0)

opt.apply_gradients([(grad, var)], global_step = global_step)

print("CREATING SESSION", flush=True)
sess = tf.train.MonitoredSession(hooks = [sync_hook],
                                 stop_grace_period_secs=10) #increasing this number will just make you wait more ;)

print("CLOSING... here's the problem!", flush=True)
sess.close()

print("DONE", flush=True)
```

### Output
It hangs at sess.close() for "stop_grace_period_secs" (showing the message "CLOSING...") 
```
INFO:tensorflow:SyncReplicasV2: replicas_to_aggregate=1; total_num_replicas=1
CREATING SESSION
CLOSING... here's the problem!
INFO:tensorflow:Coordinator stopped with threads still running: Thread-1
DONE
```

Sometimes, I additionally get the following traceback (when calling it from ipython I always get it):
```
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/queue_runner_impl.py", line 254, in _run
    coord.request_stop(e)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/coordinator.py", line 211, in request_stop
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python3.5/dist-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/queue_runner_impl.py", line 238, in _run
    enqueue_callable()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1235, in _single_operation_run
    target_list_as_strings, status, None)
  File "/usr/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.CancelledError: TakeGrad operation was cancelled
         [[Node: sync_replicas/AccumulatorTakeGradient = AccumulatorTakeGradient[_class=["loc:@sync_replicas/conditional_accumulator"], dtype=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](sync_replicas/conditional_accumulator, sync_replicas/AccumulatorTakeGradient/num_required)]]
```
After several runs of this same script I also got a segmentation fault, but only once.

**Comment by drpngx** [comment]
The `SEGV` should not happen. Can you repro this?

It's a calling pattern that I'm not used to. @ispirmustafa could you take a look?

**Comment by ispirmustafa** [comment]
Adding @isaprykin

**Comment by isaprykin** [comment]
This is most likely because you chose to say
`sync_hook = opt.make_session_run_hook(is_chief=True, num_tokens=0)`

instead of
`sync_hook = opt.make_session_run_hook(is_chief=True)`

with [the default value of num_tokens = -1](https://github.com/tensorflow/tensorflow/blob/r1.3/tensorflow/python/training/sync_replicas_optimizer.py#L432).

Is the exception still raised for you when you revert num_tokens?  Would it work for you to keep the default as-is?

**Comment by mjunyentb** [comment]
Hi @isaprykin, thanks for your help.

Leaving the default value of num_tokens = -1 still raises the exception, you can try it running the code provided (can you reproduce the error?).

This code is a simplification, of course, I actually use several processes which I want to synchronize with an effective barrier, and as far as I understood this means num_tokens needs to be 0.

**Comment by isaprykin** [comment]
Hey sorry you still have an issue.  I made my respond sound confident exactly because the exception stopped for me.  And I did try running your code.  It didn't happen under `python`, but it did happen under `ipython`.  After I removed the `num_tokens=-1` bit, `ipython` stopped throwing the exception.

If you are confident, I'll try again later and try to make sure we have exactly same versions of everything (I did test on TF 1.3).

**Comment by mjunyentb** [comment]
Yes, the problem persists. Note that in a normal python shell it might not show the exception (because the process is terminating) but it will show `INFO:tensorflow:Coordinator stopped with threads still running: Thread-1`  (since the root logger level has been set to INFO).

Adding, for instance, `time.sleep(5)` after closing the session will always show the exception using a normal python shell. 

In my code, I made sure to finalize everything before closing the session, so all this is not really a problem for me right now, but I thought it was worth reporting it.

**Comment by isaprykin** [comment]
The info message appearing is okay.

What do you in your code to finalize and prevent the exception?

**Comment by mjunyentb** [comment]
The last thing my script does is closing the session, so I actually don't prevent it.

> The info message appearing is okay.
Is it? note that the problem is that sess.close() doesn't return because the thread could not be stopped (it does return thanks to the timeout).

**Comment by donghwicha** [comment]
@mjunyentb   I'm also testing training with SyncReplicasOptimizer on MonitoredSession
but it hangs and never starts.

**Comment by weidong8405347** [comment]
i also have this problem,using monitoredsession,when close will happen thread still running,hope the answer

**Comment by isaprykin** [comment]
According to [this record](https://github.com/tensorflow/tensorflow/commit/6287fa848fb86994a503353ceb3bd663c3def4ac#diff-078d8aa8dc9179be5e99435311ade88f) that adds [ignore_live_threads=True](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/training/monitored_session.py#L1076), the stuck threads get killed later elsewhere.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by drpngx** [comment]
Closing since @isaprykin provided a solution.
