### ISSUE TITLE
Feature request: only master is allowed to export for `tf.contrib.learn.Experiment`

### ISSUE THREAD

**Issue by facaiy** [tensorflow/tensorflow#13849]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac 10.11.6
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.4.0-nightly, 1.3.0
- **Python version**:  2.7
- **Bazel version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**: N/A

### Describe the problem

When using `tf.contrib.learn.Experiment` for distributed training, it seems that all workers, ps, and master try to export model when finished. However, this will cause write conflict when `model_dir` is on hdfs, because all write the same file to the same location.

Hence, I propose that only master is allowed to export model.
I can work on it if tensorflowers're agreed.

### Source code / logs

```python
INFO:tensorflow:Saving dict for global step 30: accuracy = 0.339453, global_step = 30, loss = 70112.8
Traceback (most recent call last):
  File "main.py", line 60, in <module>
    tf.app.run()
  File "/Users/facai/Library/anaconda3/envs/py27_test/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "main.py", line 56, in main
    sess.run()
  File "/Users/facai/Workshop/sina/Prometheus/prometheus/python/session.py", line 172, in run
    ex.train_and_evaluate()
  File "/Users/facai/Library/anaconda3/envs/py27_test/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 641, in train_and_evaluate
    export_results = self._maybe_export(eval_result)
  File "/Users/facai/Library/anaconda3/envs/py27_test/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 744, in _maybe_export
    eval_result=eval_result))
  File "/Users/facai/Library/anaconda3/envs/py27_test/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/export_strategy.py", line 87, in export
    return self.export_fn(estimator, export_path, **kwargs)
  File "/Users/facai/Library/anaconda3/envs/py27_test/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/utils/saved_model_export_utils.py", line 454, in export_fn
    checkpoint_path=checkpoint_path)
  File "/Users/facai/Library/anaconda3/envs/py27_test/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 1307, in export_savedmodel
    builder = saved_model_builder.SavedModelBuilder(temp_export_dir)
  File "/Users/facai/Library/anaconda3/envs/py27_test/lib/python2.7/site-packages/tensorflow/python/saved_model/builder_impl.py", line 88, in __init__
    "directory: %s" % export_dir)
AssertionError: Export directory already exists. Please specify a different export directory: file:///tmp/facai/prome/model/new/export/Servo/temp-1508482645
```

**Comment by xiejw** [comment]
asked question in #13852

**Comment by facaiy** [comment]
Thanks, @xiejw
