### ISSUE TITLE
tensorflow java image not found

### ISSUE THREAD

**Issue by sujitbiswas** [tensorflow/tensorflow#13872]
i am running with Mac OS
<dependencies>
		<dependency>
			<groupId>org.tensorflow</groupId>
			<artifactId>tensorflow</artifactId>
			<version>1.4.0-rc0</version>
		</dependency>
	</dependencies>

please note the issue is seen in 1.4.0-rc0 and 1.3.0, however the example works fine with 1.3.0-rc0

org.tensorflow.NativeLibrary: tryLoadLibraryFailed: no tensorflow_jni in java.library.path
org.tensorflow.NativeLibrary: jniResourceName: org/tensorflow/native/darwin-x86_64/libtensorflow_jni.dylib
org.tensorflow.NativeLibrary: frameworkResourceName: org/tensorflow/native/darwin-x86_64/libtensorflow_framework.dylib
org.tensorflow.NativeLibrary: org/tensorflow/native/darwin-x86_64/libtensorflow_framework.dylib not found. This is fine assuming org/tensorflow/native/darwin-x86_64/libtensorflow_jni.dylib is not built to depend on it.
org.tensorflow.NativeLibrary: extracting native library to: /var/folders/bj/v1l790113yn16zvhljd6yl8h0000gn/T/tensorflow_native_libraries-1508538938374-0/libtensorflow_jni.dylib
org.tensorflow.NativeLibrary: copied 90774332 bytes to /var/folders/bj/v1l790113yn16zvhljd6yl8h0000gn/T/tensorflow_native_libraries-1508538938374-0/libtensorflow_jni.dylib
Exception in thread "main" java.lang.UnsatisfiedLinkError: /private/var/folders/bj/v1l790113yn16zvhljd6yl8h0000gn/T/tensorflow_native_libraries-1508538938374-0/libtensorflow_jni.dylib: dlopen(/private/var/folders/bj/v1l790113yn16zvhljd6yl8h0000gn/T/tensorflow_native_libraries-1508538938374-0/libtensorflow_jni.dylib, 1): Library not loaded: @rpath/libtensorflow_framework.so
  Referenced from: /private/var/folders/bj/v1l790113yn16zvhljd6yl8h0000gn/T/tensorflow_native_libraries-1508538938374-0/libtensorflow_jni.dylib
  Reason: image not found
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1937)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1822)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at org.tensorflow.NativeLibrary.load(NativeLibrary.java:96)
	at org.tensorflow.TensorFlow.init(TensorFlow.java:66)
	at org.tensorflow.TensorFlow.<clinit>(TensorFlow.java:70)
	at org.tensorflow.Graph.<clinit>(Graph.java:258)
	at xTensorflow.HelloTF.main(HelloTF.java:13)

**Comment by asimshankar** [comment]
Thanks for a report, there seems to be an issue with 1.4.0-rc0 and Mac OS X.
However the point release 1.3.0 should be fine.

The  snippet you provided seems to be on the usage of 1.4.0-rc0. Could you provide the same log for when you're using 1.3.0?

**Comment by mclodaa** [comment]
I ran into the same problem in 1.4.0-rc0 and 1.4.0-rc0. But it works well in 1.3.0
It's import to me for supporting string tensor with Java in version 1.4.0

**Comment by asimshankar** [comment]
Yup, we will have this fixed in 1.4.0-rc1 (if there is one) and surely in the 1.4.0 release.
(For the record, things should be fine for Linux and Windows. If the problem appears in anything other than 1.4.0-rc0 on OS X, please let us know)

**Comment by sujitbiswas** [comment]
@asimshankar yes 1.3.0 works fine

**Comment by asimshankar** [comment]
1.4.0-rc1 was just published and should have the problem fixed. Could you confirm that it works @sujitbiswas @mclodaa ?

**Comment by mclodaa** [comment]
@asimshankar it works well in 1.4.0-rc1. Thx!
I wonder what causes this problem. I tried to solve this problem, but failed.

**Comment by sujitbiswas** [comment]
i am using the maven repo [https://mvnrepository.com/artifact/org.tensorflow/libtensorflow] it is not yet updated with 1.4.0-rc1

**Comment by davidmweber** [comment]
I am able to replicate this in 1.14.0 on OSX.

**Comment by beamaster** [comment]
<dependencies>
		<dependency>
			<groupId>org.tensorflow</groupId>
			<artifactId>tensorflow</artifactId>
			<version>1.13-1</version>
		</dependency>
	</dependencies>

I use the version1.13.1, then this problem appeared too.
