### ISSUE TITLE
install from pip package fails on Ubuntu 15.10

### ISSUE THREAD

**Issue by PhamPhiLong** [tensorflow/tensorflow#1391]
### Environment info
Operating System: Ubuntu 15.10

1. pip package: tensorflow-0.7.1-cp27-none-linux_x86_64.whl

2. The screen output: 
Downloading tensorflow-0.7.1-cp27-none-linux_x86_64.whl (13.8MB): 13.8MB downloaded
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 304, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1271, in prepare_files
    req_to_install)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 109, in __init__
    self.prereleases = any([is_prerelease(x[1]) and x[0] != "!=" for x in self.req.specs])
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 739, in is_prerelease
    return any([any([y in set(["a", "b", "c", "rc", "dev"]) for y in x]) for x in parsed])
TypeError: 'int' object is not iterable

Storing debug log for failure in /home/osboxes/.pip/pip.log

### Steps to reproduce
1. sudo apt-get install python-pip python-dev
2.sudo pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.7.1-cp27-none-linux_x86_64.whl

**Comment by martinwicke** [comment]
Can you upgrade pip or tell me which version of pip is installed?

**Comment by girving** [comment]
Closing due to lack of information.  I'm happy to reopen if more information arises.
