### ISSUE TITLE
tensorflow + tensorboard on cifs results in PermissionDeniedError

### ISSUE THREAD

**Issue by AlexanderYukhanov** [tensorflow/tensorflow#13952]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
Using stock example script mnist.py from https://github.com/dandelionmane/tf-dev-summit-tensorboard-tutorial
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 16.04
- **TensorFlow installed from (source or binary)**: using standard tensorflow/tensorflow:1.1.0-gpu image
- **TensorFlow version (use command below)**: using standard tensorflow/tensorflow:1.1.0-gpu image
- **Python version**: using standard tensorflow/tensorflow:1.1.0-gpu image
- **Bazel version (if compiling from source)**: tensorflow/tensorflow:1.1.0-gpu
- **CUDA/cuDNN version**:
- **GPU model and memory**: Tesla K80
- **Exact command to reproduce**:

### Describe the problem
I am running stock  mnist.py from https://github.com/dandelionmane/tf-dev-summit-tensorboard-tutorial on  tensorflow/tensorflow:1.1.0-gpu and running tensorboard in parallel on the same container. Everything works well if logdir is located on local ssd.
If i am configuring logdir to be on samba directory and using tensorboard during job execution (specifically if i am using Embeddings), the job fails at writing temp checkpoint files (see logs below). If I am not using tensorboard embeddings during job's execution, the job finishes successfully.

### Source code / logs
2017-10-24 17:39:31.165783: W tensorflow/core/framework/op_kernel.cc:1152] Permission denied: ./model.ckpt-500.index.tempstate18351127508205389812
Traceback (most recent call last):
  File "/mnt/batch/tasks/shared/LS_root/mounts/external/tb_sample/mnist.py", line 164, in <module>
    main()
  File "/mnt/batch/tasks/shared/LS_root/mounts/external/tb_sample/mnist.py", line 156, in main
    mnist_model(learning_rate, use_two_fc, use_two_conv, hparam)
  File "/mnt/batch/tasks/shared/LS_root/mounts/external/tb_sample/mnist.py", line 136, in mnist_model
    saver.save(sess, os.path.join(LOGDIR, "model.ckpt"), i)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1391, in save
    {self.saver_def.filename_tensor_name: checkpoint_file})
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 778, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 982, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1032, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1052, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.PermissionDeniedError: ./model.ckpt-500.index.tempstate18351127508205389812
         [[Node: save/SaveV2 = SaveV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/SaveV2/tensor_names, save/SaveV2/shape_and_slices, conv1/B/_41, conv1/B/Adam/_43, conv1/B/Adam_1/_45, conv1/W/_47, conv1/W/Adam/_49, conv1/W/Adam_1/_51, conv2/B/_53, conv2/B/Adam/_55, conv2/B/Adam_1/_57, conv2/W/_59, conv2/W/Adam/_61, conv2/W/Adam_1/_63, fc1/B/_65, fc1/B/Adam/_67, fc1/B/Adam_1/_69, fc1/W/_71, fc1/W/Adam/_73, fc1/W/Adam_1/_75, fc2/B/_77, fc2/B/Adam/_79, fc2/B/Adam_1/_81, fc2/W/_83, fc2/W/Adam/_85, fc2/W/Adam_1/_87, test_embedding/_89, train/beta1_power/_91, train/beta2_power/_93)]]

Caused by op u'save/SaveV2', defined at:
  File "/mnt/batch/tasks/shared/LS_root/mounts/external/tb_sample/mnist.py", line 164, in <module>
    main()
  File "/mnt/batch/tasks/shared/LS_root/mounts/external/tb_sample/mnist.py", line 156, in main
    mnist_model(learning_rate, use_two_fc, use_two_conv, hparam)
  File "/mnt/batch/tasks/shared/LS_root/mounts/external/tb_sample/mnist.py", line 114, in mnist_model
    saver = tf.train.Saver()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1056, in __init__
    self.build()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1086, in build
    restore_sequentially=self._restore_sequentially)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 689, in build
    save_tensor = self._AddSaveOps(filename_tensor, saveables)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 276, in _AddSaveOps
    save = self.save_op(filename_tensor, saveables)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 219, in save_op
    tensors)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_io_ops.py", line 780, in save_v2
    tensors=tensors, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2336, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1228, in __init__
    self._traceback = _extract_stack()

PermissionDeniedError (see above for traceback): ./model.ckpt-500.index.tempstate18351127508205389812
         [[Node: save/SaveV2 = SaveV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/SaveV2/tensor_names, save/SaveV2/shape_and_slices, conv1/B/_41, conv1/B/Adam/_43, conv1/B/Adam_1/_45, conv1/W/_47, conv1/W/Adam/_49, conv1/W/Adam_1/_51, conv2/B/_53, conv2/B/Adam/_55, conv2/B/Adam_1/_57, conv2/W/_59, conv2/W/Adam/_61, conv2/W/Adam_1/_63, fc1/B/_65, fc1/B/Adam/_67, fc1/B/Adam_1/_69, fc1/W/_71, fc1/W/Adam/_73, fc1/W/Adam_1/_75, fc2/B/_77, fc2/B/Adam/_79, fc2/B/Adam_1/_81, fc2/W/_83, fc2/W/Adam/_85, fc2/W/Adam_1/_87, test_embedding/_89, train/beta1_power/_91, train/beta2_power/_93)]]

**Comment by skye** [comment]
@dandelionmane @jart should this be filed directly against's dandelion's project?

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by AlexanderYukhanov** [comment]
Do you have any recommendations for now how to avoid those errors or there is no way to store and consume the output from cifs?

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by jart** [comment]
Closing due to inactivity. If it's still a problem let us know and I'll reopen. Might also be worth checking StackOverflow.

**Comment by AlexanderYukhanov** [comment]
But nobody even tried to answer -)

**Comment by jart** [comment]
[StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) is the best place to get TensorFlow support. There's a larger community there and better searchability.
