### ISSUE TITLE
ImportError: libmpich.so.12: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by JerryLauzzz** [tensorflow/tensorflow#13966]
### System information
- **OS** : Ubuntu 17.10
- **TensorFlow installed from **: source 
- **TensorFlow version (use command below)**: r1.3
- **Python version**: 3.6
- **CUDA/cuDNN version**: 8.0/ 6

When I try to import tensorflow, I get error:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jihao/anaconda3/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/home/jihao/anaconda3/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/jihao/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 52, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/jihao/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/jihao/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/jihao/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/jihao/anaconda3/lib/python3.6/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/jihao/anaconda3/lib/python3.6/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libmpich.so.12: cannot open shared object file: No such file or directory
```
I try to fix it by command
```bash
sudo apt install libmpich-dev
```
It did not work.

**Comment by skye** [comment]
Try searching for and installing other libmpich packages?

**Comment by JerryLauzzz** [comment]
Already installed.
I tried find which package contains that file and got nothing.

**Comment by skye** [comment]
Unfortunately we can't help too much with environment problems here. Try asking on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow).
