### ISSUE TITLE
tensorflow/contrib/slim/python/slim/nets/resnet_v1_test.py test is failing with array mismatch error

### ISSUE THREAD

**Issue by sandipmgiri** [tensorflow/tensorflow#13992]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
      Ubuntu 16.04 (ppc64le)
- **TensorFlow installed from (source or binary)**:
      Installed from source
- **TensorFlow version (use command below)**:
      TF 1.3.1
- **Python version**: 
     Python 2.7.5
- **Bazel version (if compiling from source)**:
     bazel-0.5.4
- **CUDA/cuDNN version**:
     NA
- **GPU model and memory**:
      NA
- **Exact command to reproduce**:
 `bazel test --config=opt //tensorflow/contrib/slim/python/slim/nets:resnet_v1_test`

### Describe the problem
This test is failing due to array mismatch error – a single value in an array of 100+ elements differing i.e.  `0.69775391 VS expected 0.69799805` (minor mismatch), I feel this is not "critical".

Hence, I tried running this test by changing minor tolerance `(atol=1e-4 to atol=2e-4)`, and test is passing -
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/slim/python/slim/nets/resnet_v1_test.py#L389
Original : `output.eval(), expected.eval(), atol=1e-4, rtol=1e-4) `
Update to : ` output.eval(), expected.eval(), atol=2e-4, rtol=1e-4)`

Is it OK to raise a PR with this changes ?. Please provide your comments on this.Thanks!

### Source code / logs
 `bazel test --config=opt //tensorflow/contrib/slim/python/slim/nets:resnet_v1_test`

```
-----------------------------------------------------------------------------
..F..............
======================================================================
FAIL: testAtrousFullyConvolutionalValues (__main__.ResnetCompleteNetworkTest)
Verify dense feature extraction with atrous convolution.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/3429064d1bfc0bd7253170e3e9255ca6/execroot/org_tensorflow/bazel-out/local-opt/bin/tensorflow/contrib/slim/python/slim/nets/resnet_v1_test.runfiles/org_tensorflow/tensorflow/contrib/slim/python/slim/nets/resnet_v1_test.py", line 389, in testAtrousFullyConvolutionalValues
    output.eval(), expected.eval(), atol=1e-4, rtol=1e-4)
  File "/root/.cache/bazel/_bazel_root/3429064d1bfc0bd7253170e3e9255ca6/execroot/org_tensorflow/bazel-out/local-opt/bin/tensorflow/contrib/slim/python/slim/nets/resnet_v1_test.runfiles/org_tensorflow/tensorflow/python/framework/test_util.py", line 687, in assertAllClose
    self._assertArrayLikeAllClose(a, b, rtol=rtol, atol=atol)
  File "/root/.cache/bazel/_bazel_root/3429064d1bfc0bd7253170e3e9255ca6/execroot/org_tensorflow/bazel-out/local-opt/bin/tensorflow/contrib/slim/python/slim/nets/resnet_v1_test.runfiles/org_tensorflow/tensorflow/python/framework/test_util.py", line 657, in _assertArrayLikeAllClose
    np.testing.assert_allclose(b, a, rtol=rtol, atol=atol, err_msg=msg)
  File "/usr/lib64/python2.7/site-packages/numpy/testing/utils.py", line 1411, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "/usr/lib64/python2.7/site-packages/numpy/testing/utils.py", line 796, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Not equal to tolerance rtol=0.0001, atol=0.0001
None
(mismatch 0.173611111111%)
 x: array([[[[  0.000000e+00,   3.163050e+02,   1.810576e+02,   0.000000e+00,
            0.000000e+00,   7.204424e+01,   2.393519e+02,   2.917337e+02,
            0.000000e+00,   0.000000e+00,   4.375999e+02,   6.552710e+01,...
 y: array([[[[  0.000000e+00,   3.163050e+02,   1.810576e+02,   0.000000e+00,
            0.000000e+00,   7.204424e+01,   2.393519e+02,   2.917337e+02,
            0.000000e+00,   0.000000e+00,   4.375999e+02,   6.552710e+01,...

----------------------------------------------------------------------
Ran 17 tests in 21.369s

FAILED (failures=1)
not close where =  (array([1]), array([2]), array([1]), array([7]))
not close lhs =  [ 0.69799805]
not close rhs =  [ 0.69775391]
not close dif =  [ 0.00024414]
not close tol =  [ 0.00016978]
dtype = float32, shape = (2, 3, 3, 32)
```

**Comment by skye** [comment]
This seems like a reasonable PR to me, I say go for it.

**Comment by sandipmgiri** [comment]
Thanks @skye , I have created a PR - https://github.com/tensorflow/tensorflow/pull/14086, please have a look.

I will close this issue once PR merged.

**Comment by sandipmgiri** [comment]
PR got merged, hence closing.
