### ISSUE TITLE
CUDNN_STATUS_INTERNAL_ERROR

### ISSUE THREAD

**Issue by meccaLeccaHi** [tensorflow/tensorflow#14048]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04.2 
- **TensorFlow installed from (source or binary)**: binary (via pip)
- **TensorFlow version (use command below)**: ('v1.3.0-rc2-20-g0787eee', '1.3.0') 
- **Python version**: 2.7
- **Bazel version (if compiling from source)**: n/a
- **CUDA/cuDNN version**: Cuda 8.0 (via pip) / cuDNN 6.0.21
- **GPU model and memory**: GeForce GTX 1060 6GB
Host compiler version : GCC 4.9.3

Exact steps to reproduce (as per [nvidia Tensorflow demo](https://www.nvidia.com/en-us/data-center/gpu-accelerated-applications/tensorflow/)):
$ git clone -b update-models-1.0 https://github.com/tensorflow/models
$ cd models/tutorials/image/imagenet
$ python classify_image.py

### Describe the problem
Tensorflow fails to run demo script, despite having installed (and re-installed) as per the [manual](https://www.tensorflow.org/install/install_linux). Any help would be *greatly* appreciated. 

### Source code / logs
2017-10-27 16:09:51.154970: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-10-27 16:09:51.155000: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-10-27 16:09:51.349207: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:893] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2017-10-27 16:09:51.349589: I tensorflow/core/common_runtime/gpu/gpu_device.cc:955] Found device 0 with properties: 
name: GeForce GTX 1060 6GB
major: 6 minor: 1 memoryClockRate (GHz) 1.7845
pciBusID 0000:01:00.0
Total memory: 5.93GiB
Free memory: 5.80GiB
2017-10-27 16:09:51.349610: I tensorflow/core/common_runtime/gpu/gpu_device.cc:976] DMA: 0 
2017-10-27 16:09:51.349617: I tensorflow/core/common_runtime/gpu/gpu_device.cc:986] 0:   Y 
2017-10-27 16:09:51.349631: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1045] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1060 6GB, pci bus id: 0000:01:00.0)
2017-10-27 16:09:51.672521: W tensorflow/core/framework/op_def_util.cc:333] Op BatchNormWithGlobalNormalization is deprecated. It will cease to work in GraphDef version 9. Use tf.nn.batch_normalization().
2017-10-27 16:09:52.006440: E tensorflow/stream_executor/cuda/cuda_dnn.cc:371] could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2017-10-27 16:09:52.006471: E tensorflow/stream_executor/cuda/cuda_dnn.cc:338] could not destroy cudnn handle: CUDNN_STATUS_BAD_PARAM
2017-10-27 16:09:52.006481: F tensorflow/core/kernels/conv_ops.cc:672] Check failed: stream->parent()->GetConvolveAlgorithms( conv_parameters.ShouldIncludeWinogradNonfusedAlgo<T>(), &algorithms) 
Aborted (core dumped)

**Comment by meccaLeccaHi** [comment]
Sure! See below. No other processes are running when I've tried this. I've also tried restarting to ensure that the GPU memory was totally cleared, but the same issue occurs.

 `+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.90                 Driver Version: 384.90                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 106...  Off  | 00000000:01:00.0  On |                  N/A |
|  0%   36C    P8     9W / 120W |     52MiB /  6071MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1250      G   /usr/lib/xorg/Xorg                            50MiB |
+-----------------------------------------------------------------------------+
`

**Comment by meccaLeccaHi** [comment]
#### I don't know if anyone will read this. But, I've since upgraded my GPU, reinstalled CUDA-8.0 (from with apt-get install), and modified my .bashrc file to include:
export LIBRARY_PATH=$LIBRARY_PATH:/usr/local/cuda/lib64
as per [this post](https://groups.google.com/forum/#!topic/theano-users/qD_HHtO3b-k). The relevant portion of the latest .bashrc file is shown here:
'export CUDA_ROOT=/usr/local/cuda
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/cuda/lib64/"
export PATH="/usr/local/cuda/bin:$PATH"
export PATH="/usr/local/cuda-8.0/bin:$PATH"
export CUDA_VISIBLE_DEVICES=0
export LIBRARY_PATH=$LIBRARY_PATH:/usr/local/cuda/lib64
#export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/cuda-8.0/lib64:/usr/local/cuda-8.0/extras/CUPTI/lib64"'

#### But I still get the following error. I've tried the solutions in the [troubleshooting guide](https://www.tensorflow.org/install/install_sources#common_installation_problems) to no avail. 
'>>> import tensorflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/adam/miniconda2/lib/python2.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/home/adam/miniconda2/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/adam/miniconda2/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 52, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/adam/miniconda2/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/adam/miniconda2/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/adam/miniconda2/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: libcusolver.so.8.0: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.'

**Comment by asimshankar** [comment]
@meccaLeccaHi : Sorry that you're running into this. The error messages suggest trouble using CUDA/CUDNN, or in this last case, errors in loading the `libcusolver.so` library.

So the errors have changed after your reinstall? What is the location of `libcusolver.so.8.0` on your filesystem?

**Comment by meccaLeccaHi** [comment]
Thanks for your help!
I was able to move past the original error by adding the following line, in particular, to my .bashrc file:
`export LIBRARY_PATH=$LIBRARY_PATH:/usr/local/cuda/lib64`
But, I am still unable to import the tensorflow module.

libcusolver.so.8.0 is located at:
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcusolver.so.8.0

**Comment by asimshankar** [comment]
Hmm....so not in your `LD_LIBRARY_PATH`. Just to verify that `libcusolver.so.8.0` is accessible to the linker, can you also list out the output of `ldconfig -p | grep libcusolver`?

**Comment by meccaLeccaHi** [comment]
Happy to.
`$ ldconfig -p | grep libcusolver          
	libcusolver.so.7.5 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libcusolver.so.7.5
	libcusolver.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libcusolver.so
`

**Comment by meccaLeccaHi** [comment]
OK, if I add '/usr/local/cuda-8.0/targets/x86_64-linux/lib' to my LD_LIBRARY_PATH, importing tensorflow is successful (so, many thanks to Sir for that). But, I am still experiencing my original error which is shown below:

`$ python classify_image.py 
>> Downloading inception-2015-12-05.tgz 100.0%
Successfully downloaded inception-2015-12-05.tgz 88931400 bytes.
2017-10-30 22:14:54.542348: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-10-30 22:14:54.542378: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-10-30 22:14:54.705978: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:893] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2017-10-30 22:14:54.706540: I tensorflow/core/common_runtime/gpu/gpu_device.cc:955] Found device 0 with properties: 
name: GeForce GTX TITAN X
major: 5 minor: 2 memoryClockRate (GHz) 1.2155
pciBusID 0000:01:00.0
Total memory: 11.92GiB
Free memory: 11.80GiB
2017-10-30 22:14:54.706561: I tensorflow/core/common_runtime/gpu/gpu_device.cc:976] DMA: 0 
2017-10-30 22:14:54.706568: I tensorflow/core/common_runtime/gpu/gpu_device.cc:986] 0:   Y 
2017-10-30 22:14:54.706578: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1045] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:01:00.0)
2017-10-30 22:14:55.237837: W tensorflow/core/framework/op_def_util.cc:333] Op BatchNormWithGlobalNormalization is deprecated. It will cease to work in GraphDef version 9. Use tf.nn.batch_normalization().
2017-10-30 22:14:58.319995: E tensorflow/stream_executor/cuda/cuda_dnn.cc:371] could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2017-10-30 22:14:58.320026: E tensorflow/stream_executor/cuda/cuda_dnn.cc:338] could not destroy cudnn handle: CUDNN_STATUS_BAD_PARAM
2017-10-30 22:14:58.320035: F tensorflow/core/kernels/conv_ops.cc:672] Check failed: stream->parent()->GetConvolveAlgorithms( conv_parameters.ShouldIncludeWinogradNonfusedAlgo<T>(), &algorithms) 
Aborted (core dumped)
`

**Comment by asimshankar** [comment]
Based on that, it would appear that `libcusolver.so.8.0` is not available to the linker when TensorFlow is loading (i.e., `/usr/local/cuda-8.0/targets/x86_64-linux/lib` is not in the search path for dynamic libraries).

Not quite sure how you ended up in this state, but it seems that you'd want to correct that by updating your `ld.conf`, or perhaps including `/usr/local/cuda-8.0/targets/x86_64-linux/lib` and related paths in your `LD_LIBRARY_PATH`

**Comment by jstastny** [comment]
We ran into similar error (`CUDNN_STATUS_INTERNAL_ERROR`), but it was not happening when we ran `python` as root. It always failed when run as other, non-root user.
The root cause in the end was in the `nvidia-persistenced` daemon, which by default runs on Ubuntu under `nvidia-persistenced` user (which is member of same named group).
Adding the non-root user to `nvidia-persistenced` group (`usermod -a -G nvidia-persistenced my-nonroot-user`) resolved the issue.

**Comment by meccaLeccaHi** [comment]
Thanks jstastny, but I did exactly as you say and the error still persists.

**Comment by jstastny** [comment]
@meccaLeccaHi -- did you log out and back again (or issued other way of reloading the groups of your user)? You can validate what are you in by `groups` command.
Just to validate -- it works for you when run under `root`, right?

**Comment by meccaLeccaHi** [comment]
I have tried logging out and then back in again, but still experience the same error.
Running the command as sudo does not work, as the tensorflow module is not found (see below). Perhaps because I installed using conda as non-root user (e.g. 'conda install tensorflow-gpu').
'nvidia-persistenced' is among the groups shown when I run the 'groups' command.
`$ sudo python classify_image.py 
[sudo] password for adam: 
Traceback (most recent call last):
  File "classify_image.py", line 46, in <module>
    import tensorflow as tf
ImportError: No module named tensorflow
`

**Comment by jart** [comment]
Does it work if you do the conda thing as root?

**Comment by meccaLeccaHi** [comment]
Strangely, I get the same missing module error even after running the following commands:
`sudo -s`
`conda install tensorflow-gpu`

**Comment by squared9** [comment]
I have the same exact problem. Tried all recommended steps here, no luck. Running on Linux Mint 18.2 (Ubuntu 16.04), nvidia-375 (384.90), CUDA 8.0.61-1 + CuDNN 6.0, TensorFlow 1.3.0 and 1.4.0, default Python 2.7, no Anaconda. I once got it working right after reboot, but subsequent executions always failed. Seems like driver gets stuck in some weird state... It started happening only a few days ago, maybe some Ubuntu/Mint update exposed this problem.

**Comment by drpngx** [comment]
Just to be sure, could you try the newest version?

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue? Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by drpngx** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by chintler** [comment]
I'm facing the same issue. 

I have
Geforce GTX 1050Ti
Tensorflow 1.8.0
CUDA 9.0
cuDNN 7.0
No process is occupying the GPU, and rebooting has no effect. The last time this stopped working, it was a user rights problem, and disappeared when I added my user to nvidia-persistenced. User is probably not the issue, since it won't work with sudo either. Please help.

**Comment by PantherYan** [comment]
could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
I am also facing the same issue.

**Comment by Cancerce1l** [comment]
@chintler I have the exact same problem as yours, have you solved it yet?

**Comment by seraj94ai** [comment]
same for me in windows , any help plz

**Comment by cpoptic** [comment]
Please re-open issue.  This still hasn't been solved, even with latest TF 1.10

**Comment by skye** [comment]
@reedwm can you take a look or redirect? Thanks.

**Comment by reedwm** [comment]
Someone who still has the issue, can you paste the full output of the error and refill the issues template? TensorFlow now requires cuda 9.0 unless built from source, and I cannot reproduce this issue.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by sharmaGIT** [comment]
I am getting the same issue with window 10, tensorflow 1.10 and cuda 9.0. The error is 
2018-09-25 17:15:39.657620: E T:\src\github\tensorflow\tensorflow\stream_executor\cuda\cuda_blas.cc:459] failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED
2018-09-25 17:15:39.657926: E T:\src\github\tensorflow\tensorflow\stream_executor\cuda\cuda_blas.cc:459] failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED
2018-09-25 17:15:39.679944: E T:\src\github\tensorflow\tensorflow\stream_executor\cuda\cuda_dnn.cc:352] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by adampl** [comment]
I get the same error on Linux with TensorFlow 1.10 and CUDA 9.0.

Apparently cuDNN is trying to allocate more memory than it should, as if the `gpu_options.per_process_gpu_memory_fraction` option (which we use) weren't strictly respected. In my case this error occurs when there is little free GPU memory:

    tensorflow/stream_executor/cuda/cuda_dnn.cc:352] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR

Then the process crashes with segmentation fault (`SIGSEGV`).

**Comment by drpngx** [comment]
@adampl So there is a floor that we need? Are you comfortable enough with the code to send a fix to print out a more meaningful error message?

**Comment by adampl** [comment]
@drpngx Unfortunately I'm not familiar with TF code, but it's not the error message that needs to be fixed, but the error itself.

**Comment by drpngx** [comment]
If I understand correctly, the problem is that the memory fraction cannot be honored if there's too little GPU memory available, resulting in an error. I am assuming that there's a reason for that and it can't be fixed. If it cannot be fixed, then we would want to detect that case and return a more informative error message. (If it can be fixed, then we should fix it). Am I right?

**Comment by adampl** [comment]
The error occurs only when there is little free memory, because in such case if cuDNN exceeds the fraction, the GPU is unable to allocate the requested amount of memory. Nonetheless I suspect that the fraction is always (or often) exceeded regardless of the amount of free memory, but it just doesn't result in a fatal error because there is enough free memory.

**Comment by hongru-li** [comment]
This work for me: 
http://tuxvoid.blogspot.com/2017/08/tensorflow-could-not-create-cudnn.html

**Comment by adampl** [comment]
@wt-huang How do you know it's resolved?

**Comment by bmilde** [comment]
I got the same error when using convolutions (repeatedly), any thing else was running fine. I have not updated anything and kept the same tensorflow and CUDA version under which the same code was running before.

Deleting the .nv dir (nvidia cache) in my local home directory completely solved the issue for me. Might also explain why another commenter had success with running Python as root.
