### ISSUE TITLE
Error: E tensorflow/core/common_runtime/direct_session.cc:138] Internal: failed initializing StreamExecutor for CUDA device ordinal 0: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_INVALID_DEVICE

### ISSUE THREAD

**Issue by MounirHader** [tensorflow/tensorflow#14093]
Hi, I am working on a remote machine with many GPU cards that has CUDA v8.0.61 and Cudnn 5.1.10 installed. Upgrading these is not possible because of permission rights. In my own environment I installed TensorFlow version 1.2.1, but I get the following error when launching a `Session()`:

```
import tensorflow as tf
sess=tf.Session()
2017-10-30 13:48:47.652605: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-10-30 13:48:47.652665: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-10-30 13:48:47.652680: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-10-30 13:48:47.652694: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-10-30 13:48:47.652708: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
2017-10-30 13:48:47.930480: E tensorflow/core/common_runtime/direct_session.cc:138] Internal: failed initializing StreamExecutor for CUDA device ordinal 0: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_INVALID_DEVICE
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1292, in __init__
    super(Session, self).__init__(target, graph, config=config)
  File "/home/user/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 562, in __init__
    self._session = tf_session.TF_NewDeprecatedSession(opts, status)
  File "/home/user/anaconda2/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/home/user/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InternalError: Failed to create session.'
```

The output when calling `nvidia-smi` is

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.51                 Driver Version: 375.51                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 0000:06:00.0     Off |                    0 |
| N/A   52C    P0    61W / 149W |     65MiB / 11439MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K80           Off  | 0000:07:00.0     Off |                    0 |
| N/A   40C    P0    76W / 149W |     65MiB / 11439MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   2  Tesla K80           Off  | 0000:0A:00.0     Off |                    0 |
| N/A   46C    P0    60W / 149W |     65MiB / 11439MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   3  Tesla K80           Off  | 0000:0B:00.0     Off |                    0 |
| N/A   37C    P0    74W / 149W |     65MiB / 11439MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   4  Tesla K80           Off  | 0000:10:00.0     Off |                    0 |
| N/A   44C    P0    59W / 149W |     65MiB / 11439MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   5  Tesla K80           Off  | 0000:11:00.0     Off |                    0 |
| N/A   33C    P0    75W / 149W |     65MiB / 11439MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   6  Tesla K80           Off  | 0000:14:00.0     Off |                    0 |
| N/A   43C    P0    58W / 149W |     65MiB / 11439MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   7  Tesla K80           Off  | 0000:15:00.0     Off |                    0 |
| N/A   33C    P0    73W / 149W |     65MiB / 11439MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   8  Tesla K80           Off  | 0000:87:00.0     Off |                    0 |
| N/A   35C    P0    58W / 149W |     65MiB / 11439MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   9  Tesla K80           Off  | 0000:88:00.0     Off |                    0 |
| N/A   31C    P0    74W / 149W |     65MiB / 11439MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|  10  Tesla K80           Off  | 0000:8B:00.0     Off |                    0 |
| N/A   51C    P0   142W / 149W |   8361MiB / 11439MiB |    100%   E. Process |
+-------------------------------+----------------------+----------------------+
|  11  Tesla K80           Off  | 0000:8C:00.0     Off |                    0 |
| N/A   31C    P0    86W / 149W |     86MiB / 11439MiB |     48%   E. Process |
+-------------------------------+----------------------+----------------------+
|  12  Tesla K80           Off  | 0000:91:00.0     Off |                    0 |
| N/A   51C    P0   143W / 149W |   8330MiB / 11439MiB |     99%   E. Process |
+-------------------------------+----------------------+----------------------+
|  13  Tesla K80           Off  | 0000:92:00.0     Off |                    0 |
| N/A   23C    P8    30W / 149W |      2MiB / 11439MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|  14  Tesla K80           Off  | 0000:95:00.0     Off |                    0 |
| N/A   25C    P8    28W / 149W |      2MiB / 11439MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|  15  Tesla K80           Off  | 0000:96:00.0     Off |                    0 |
| N/A   23C    P8    30W / 149W |      2MiB / 11439MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
```
                                                                               
Any ideas on the error `E tensorflow/core/common_runtime/direct_session.cc:138] Internal: failed initializing StreamExecutor for CUDA device ordinal 0: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_INVALID_DEVICE`? Running `tf.Session()` multiple times results in the same error but will increase the number behind "ordinal".

**Comment by MounirHader** [comment]
Also, it is not a memory error on the GPUs. When explicitly setting CUDA_VISIBLE_DEVICES to a non occupied GPU I get the same error. One time I seemed to get lucky as the following command worked:

```
(root) [~]$ CUDA_VISIBLE_DEVICES=13 python -c "import tensorflow as tf;tf.InteractiveSession()

"
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 0 with properties: 
name: Tesla K80
major: 3 minor: 7 memoryClockRate (GHz) 0.8235
pciBusID 0000:92:00.0
Total memory: 11.17GiB
Free memory: 11.11GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla K80, pci bus id: 0000:92:00.0)
```

But it keeps failing all other times (on GPUs that aren't occupied)

**Comment by MounirHader** [comment]
It now seems I can only use the GPUs that have a P8 status (not the ones with P0)
