### ISSUE TITLE
Mac OS;import error "ImportError: cannot import name _message"

### ISSUE THREAD

**Issue by lemontreeshy** [tensorflow/tensorflow#1411]
### Environment info
MAC OS
python:
Python 2.7.11 |Anaconda 2.5.0 (x86_64)| (default, Dec  6 2015, 18:57:58) 
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org

install command:
pip install --upgrade https://storage.googleapis.com/tensorflow/mac/tensorflow-0.7.1-cp27-none-any.whl

error:

>>> import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "//anaconda/lib/python2.7/site-packages/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "//anaconda/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 41, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "//anaconda/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 35, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "//anaconda/lib/python2.7/site-packages/tensorflow/core/framework/graph_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
  File "//anaconda/lib/python2.7/site-packages/google/protobuf/descriptor.py", line 46, in <module>
    from google.protobuf.pyext import _message
ImportError: cannot import name _message

Error importing tensorflow.  Unless you are using bazel,
you should not try to import tensorflow from its source directory;
please exit the tensorflow source tree, and relaunch your python interpreter
from there.

but I didn't start python at the tensorfliw source directory
$ pwd
/anaconda/bin

How to  solve the problem?

**Comment by zwpaper** [comment]
I got something like that
OS: OS X El Capitan
Virtualenv
python 3.4.3

```
Traceback (most recent call last):
  File "/Users/paper/Desktop/qingyang/lib/python3.4/site-packages/tensorflow/python/__init__.py", line 35, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/Users/paper/Desktop/qingyang/lib/python3.4/site-packages/tensorflow/core/framework/graph_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
ImportError: cannot import name 'descriptor'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cifar10_eval.py", line 42, in <module>
    import tensorflow.python.platform
  File "/Users/paper/Desktop/qingyang/lib/python3.4/site-packages/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/Users/paper/Desktop/qingyang/lib/python3.4/site-packages/tensorflow/python/__init__.py", line 41, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/Users/paper/Desktop/qingyang/lib/python3.4/site-packages/tensorflow/python/__init__.py", line 35, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/Users/paper/Desktop/qingyang/lib/python3.4/site-packages/tensorflow/core/framework/graph_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
ImportError: cannot import name 'descriptor'


Error importing tensorflow.  Unless you are using bazel,
you should not try to import tensorflow from its source directory;
please exit the tensorflow source tree, and relaunch your python interpreter
from there.
```

**Comment by zwpaper** [comment]
Solved my problem by uninstalling tensorflow and protobuf, then reinstalling tensorflow.
from https://github.com/tensorflow/tensorflow/issues/1262

**Comment by lemontreeshy** [comment]
thks and I solved the problem.

**Comment by nwtgck** [comment]
Thank very much! Though I had the same problem, Reinstalling solved my problem too.

**Comment by entron** [comment]
Reinstalling doesn't solve my problem:(

**Comment by entron** [comment]
Now I solved the problem by reinstalling protobuf using pip instead of homebrew which didn't work.
