### ISSUE TITLE
Could not find any downloads that satisfy the requirement tensorflow

### ISSUE THREAD

**Issue by riless** [tensorflow/tensorflow#14207]
I cannot install Tensorflow using `pip install tensorflow`

> Installing TensorFlow on Ubuntu
> 
> This guide explains how to install TensorFlow on Ubuntu. These instructions might also work on other Linux variants, but we have only tested (and we only support) these instructions on **Ubuntu 14.04 or higher**.

```
>>> python -V
Python 2.7.6

>>> pip -V
pip 1.5.4 from /usr/lib/python2.7/dist-packages (python 2.7)

>>> uname -a
Linux 241f7b925fda 3.16.0-36-generic #48~14.04.1-Ubuntu SMP Wed Apr 15 13:11:28 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

>>> lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.2 LTS
Release:	14.04
Codename:	trusty

>>> pip install tensorflow
Downloading/unpacking tensorflow
  Could not find any downloads that satisfy the requirement tensorflow
Cleaning up...
No distributions at all found for tensorflow
Storing debug log for failure in /root/.pip/pip.log

>>> tail -n 20 /root/.pip/pip.log
    Skipping https://pypi.python.org/packages/fd/1a/7935eb82b9a9b89a3a8ef7e54f7d538698c85d248d8bedb533eab5afd293/tensorflow-1.0.1-cp36-cp36m-manylinux1_x86_64.whl#md5=61d704d2c563b2569524545f106f0a4a (from https://pypi.python.org/simple/tensorflow/) because it is not compatible with this Python
    Skipping https://pypi.python.org/packages/fd/1a/b6e78223c8e05a8bdee8f9bb20d4926f81db50e583632a1cde6e5b5ec2f0/tensorflow-1.1.0-cp35-cp35m-manylinux1_x86_64.whl#md5=fc5ed08795ef5afa60b48ae916def79c (from https://pypi.python.org/simple/tensorflow/) because it is not compatible with this Python
    Skipping https://pypi.python.org/packages/fd/cb/21c20d0597cbf67e952f590355b2cdb93544b699cd6ee46a4dc9069d037d/tensorflow-1.4.0rc0-cp33-cp33m-macosx_10_11_x86_64.whl#md5=05c4cfd97ed74ddd1753312aa5b19fca (from https://pypi.python.org/simple/tensorflow/) because it is not compatible with this Python
    Skipping https://pypi.python.org/packages/fe/d0/49d9d8e6e781acde22b7bcbee693a1be86bcf8f6c21e915159ab61d12bd8/tensorflow-1.3.0-cp33-cp33m-macosx_10_11_x86_64.whl#md5=2855104686160b99a64910d33935d7d8 (from https://pypi.python.org/simple/tensorflow/) because it is not compatible with this Python
    Skipping https://pypi.python.org/packages/fe/dd/8764ae59e8ff74421d615ddb9c86a1b404c27708dfde3caa8f17c183788d/tensorflow-1.3.0-cp27-cp27mu-manylinux1_x86_64.whl#md5=e82e309e6af0996f2083f59cf21d392c (from https://pypi.python.org/simple/tensorflow/) because it is not compatible with this Python
  Could not find any downloads that satisfy the requirement tensorflow
Cleaning up...
  Removing temporary dir /tmp/pip_build_root...
No distributions at all found for tensorflow
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1178, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 277, in find_requirement
    raise DistributionNotFound('No distributions at all found for %s' % req)
DistributionNotFound: No distributions at all found for tensorflow
```

**Comment by PhilippRK** [comment]
> pip 1.5.4 from /usr/lib/python2.7/dist-packages (python 2.7)

See [installation guide](https://www.tensorflow.org/install/install_linux):

>  We strongly recommend version 8.1 or higher of pip or pip3.

**Comment by riless** [comment]
Yes, that's it. Thank you.
