### ISSUE TITLE
Convert keras model to estimator model

### ISSUE THREAD

**Issue by KirtoXX** [tensorflow/tensorflow#14203]
ValueError: ('Expected `model` argument to be a `Model` instance, got ', <keras.engine.training.Model object at 0x00000230F36F0E10>)

**Comment by KirtoXX** [comment]
Also,I wonder how can I set some parms like epoch,batch_size,ckpt saving step...etc,Thanks a lot

**Comment by asimshankar** [comment]
I apologize but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new) . Please provide all the information it asks, in particular detailed instructions to reproduce the problem. Thank you.

**Comment by yangsiyu007** [comment]
@asimshankar can we please reopen this issue, I've encountered it as well and here's the details:

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: followed example code
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macos 10.13.1
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.6.0
- **Python version**: 3.6.4
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**:
```
from keras_contrib.applications.densenet import DenseNetImageNet161
import keras.optimizers
import tensorflow as tf

target_img_size = (224, 224, 3)
model = DenseNetImageNet161(input_shape=target_img_size)
model.compile(optimizer=keras.optimizers.Adam(lr=1e-4), loss='categorical_crossentropy',
                  metrics=['accuracy'])

estimator = tf.keras.estimator.model_to_estimator(keras_model=model, model_dir='/path/to/dir')
```

### Describe the problem
When I run the above script, it gives the error that @KirtoXX mentioned (see traceback below).

It seems to be [this exact issue referenced in keras](https://github.com/keras-team/keras/issues/9310). It seems that if the model was built with standard keras, then model_to_estimator() can't really be used, which would make model_to_estimator() not very helpful for using many pre-trained models.

### Source code / logs
...
Using TensorFlow backend.
2018-03-09 00:46:36.080703: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Weights for the model were loaded successfully
Traceback (most recent call last):
  File "/Users/siyuyang/Source/Repos/AI4E_IARPAfMoW/scripts/temp.py", line 15, in <module>
    estimator = tf.keras.estimator.model_to_estimator(keras_model=model, model_dir='/path/to/dir')
  File "/Users/siyuyang/Source/Repos/AI4E_IARPAfMoW/env/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/estimator.py", line 302, in model_to_estimator
    _save_first_checkpoint(keras_model, est, custom_objects, keras_weights)
  File "/Users/siyuyang/Source/Repos/AI4E_IARPAfMoW/env/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/estimator.py", line 231, in _save_first_checkpoint
    custom_objects)
  File "/Users/siyuyang/Source/Repos/AI4E_IARPAfMoW/env/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/estimator.py", line 111, in _clone_and_build_model
    model = models.clone_model(keras_model, input_tensors=input_tensors)
  File "/Users/siyuyang/Source/Repos/AI4E_IARPAfMoW/env/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/models.py", line 1557, in clone_model
    return _clone_functional_model(model, input_tensors=input_tensors)
  File "/Users/siyuyang/Source/Repos/AI4E_IARPAfMoW/env/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/models.py", line 1361, in _clone_functional_model
    'to be a `Model` instance, got ', model)
ValueError: ('Expected `model` argument to be a `Model` instance, got ', <keras.engine.training.Model object at 0x10e616588>)

**Comment by asimshankar** [comment]
I don't think there is an intention to have `model_to_estimator` work with `keras.Model`, it requires `tf.keras.Model`. However, since `tf.keras` implements the Keras API spec, you should be able to create the same using `tf.keras.applications`.

That said, I could be wrong, so CCing @fchollet and @anj-s for their input.

**Comment by somnathrakshit** [comment]
Same problem here.
