### ISSUE TITLE
Mandlebrot example fails on docker image

### ISSUE THREAD

**Issue by tmsimont** [tensorflow/tensorflow#1427]
I'm running through the [Mandlebrot Set tutorial](https://www.tensorflow.org/versions/r0.7/tutorials/mandelbrot/index.html) and hit a snag.

I am running tensor flow from Docker -- the `b.gcr.io/tensorflow/tensorflow` image

When I try to initialize all variables, I get this error:

```
W tensorflow/core/kernels/cast_op.cc:125] Unimplemented: Cast complex64 to float is not supported
E tensorflow/core/common_runtime/executor.cc:275] Executor failed to create kernel. Unimplemented: Cast complex64 to float is not supported
```

Full error after copy/pasting tutorial code to python file:
```
W tensor [[Node: zeros_like/Cast = Cast[DstT=DT_FLOAT, SrcT=DT_COMPLEX64, _device="/job:localhost/replica:0/task:0/cpu:0"](zeros_like/ZerosLike)]]
Traceback (most recent call last):xecutor.cc:275] Executor failed to create kernel.
  File "mb.py", line 36, in <module>oat is not supported
    tf.i [[Node: zeros_like/Cast = Cast[DstT=DT_FLOAT, SrcT=DT_COMPLEX64, _device="/job:localhost/replica:0/task:0/cpu:0"](zeros_like/ZerosLike)]]n/framework/ops.py",
Caused by op u'zeros_like/Cast', defined at:
  File "mb.py", line 34, in <module> feed_dict, self.graph, session)
    ns = tf.Variable(tf.zeros_like(xs, tf.float32))orflow/python/framework/ops.py",
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 632, in zeros_liken, feed_dict)
    ret = gen_math_ops.cast(ret, dtype)ackages/tensorflow/python/client/session.py"
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_math_ops.py", line 193, in castNone, fetches, feed_dict)
    return _op_def_lib.apply_op("Cast", x=x, DstT=DstT, name=name)lient/session.py"
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/op_def_library.py", line 655, in apply_op
    op_def=op_def)/lib/python2.7/dist-packages/tensorflow/python/client/session.py"
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2040, in create_op
    original_op=self._default_original_op, op_def=op_def)/python/client/session.py"
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1087, in __init__
    self._traceback = _extract_stack()mplementedError: Cast complex64 to float is n
ot supported
```

Is the docker image out of date?

**Comment by caisq** [comment]
This is caused by changes in the behavior of zeros_like (See). 

As a temporary workaround, please replace
`ns = tf.Variable(tf.zeros_like(xs, tf.float32))`
with
`ns = tf.Variable(tf.zeros(Z.shape))`

We will provide a more permanent solution to this soon.

**Comment by tmsimont** [comment]
That did the trick! Thanks.

**Comment by girving** [comment]
Fix in review.
