### ISSUE TITLE
map_fn not working with string tensor on Android

### ISSUE THREAD

**Issue by andreas-eberle** [tensorflow/tensorflow#14291]
It seems that the tensorflow Android version (1.4.0) does not include the kernel for TensorArrayScatterV3 for string tensors (see stacktrace below). This leads to the problem that I cannot use map_fn with string tensors on Android. 

The same code and model runs fine with the desktop Java API in the same version. 

Can you please add the missing kernel?

Stacktrace

```
11-06 15:14:45.760 32605-1644/de.test.android.fisheye.local W/System.err: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: No OpKernel was registered to support Op 'TensorArrayScatterV3' with these attrs.  Registered devices: [CPU], Registered kernels:
11-06 15:14:45.760 32605-1644/de.test.android.fisheye.local W/System.err:   device='CPU'; T in [DT_BOOL]
11-06 15:14:45.760 32605-1644/de.test.android.fisheye.local W/System.err:   device='CPU'; T in [DT_FLOAT]
11-06 15:14:45.760 32605-1644/de.test.android.fisheye.local W/System.err:   device='CPU'; T in [DT_INT32]
11-06 15:14:45.760 32605-1644/de.test.android.fisheye.local W/System.err: 	 [[Node: map/TensorArrayUnstack/TensorArrayScatter/TensorArrayScatterV3 = TensorArrayScatterV3[T=DT_STRING, _class=["loc:@image_strings"]](map/TensorArray, map/TensorArrayUnstack/range, image_strings, map/TensorArray:1)]]
11-06 15:14:45.760 32605-1644/de.test.android.fisheye.local W/System.err:     at java.util.concurrent.FutureTask.report(FutureTask.java:94)
11-06 15:14:45.760 32605-1644/de.test.android.fisheye.local W/System.err:     at java.util.concurrent.FutureTask.get(FutureTask.java:164)
11-06 15:14:45.760 32605-1644/de.test.android.fisheye.local W/System.err:     at de.test.neuronalnetwork.service.TaskWorkerLoop$Loop.run(TaskWorkerLoop.java:71)
11-06 15:14:45.761 32605-1644/de.test.android.fisheye.local W/System.err:     at java.lang.Thread.run(Thread.java:762)
11-06 15:14:45.761 32605-1644/de.test.android.fisheye.local W/System.err: Caused by: java.lang.IllegalArgumentException: No OpKernel was registered to support Op 'TensorArrayScatterV3' with these attrs.  Registered devices: [CPU], Registered kernels:
11-06 15:14:45.761 32605-1644/de.test.android.fisheye.local W/System.err:   device='CPU'; T in [DT_BOOL]
11-06 15:14:45.761 32605-1644/de.test.android.fisheye.local W/System.err:   device='CPU'; T in [DT_FLOAT]
11-06 15:14:45.761 32605-1644/de.test.android.fisheye.local W/System.err:   device='CPU'; T in [DT_INT32]
11-06 15:14:45.761 32605-1644/de.test.android.fisheye.local W/System.err: 	 [[Node: map/TensorArrayUnstack/TensorArrayScatter/TensorArrayScatterV3 = TensorArrayScatterV3[T=DT_STRING, _class=["loc:@image_strings"]](map/TensorArray, map/TensorArrayUnstack/range, image_strings, map/TensorArray:1)]]
11-06 15:14:45.761 32605-1644/de.test.android.fisheye.local W/System.err:     at org.tensorflow.Session.run(Native Method)
11-06 15:14:45.761 32605-1644/de.test.android.fisheye.local W/System.err:     at org.tensorflow.Session.access$100(Session.java:48)
11-06 15:14:45.761 32605-1644/de.test.android.fisheye.local W/System.err:     at org.tensorflow.Session$Runner.runHelper(Session.java:298)
11-06 15:14:45.761 32605-1644/de.test.android.fisheye.local W/System.err:     at org.tensorflow.Session$Runner.run(Session.java:248)
11-06 15:14:45.761 32605-1644/de.test.android.fisheye.local W/System.err:     at de.test.brain.Api.run(Api.java:39)
11-06 15:14:45.761 32605-1644/de.test.android.fisheye.local W/System.err:     at de.test.client.api.Evaluator.evaluateBatch(Evaluator.java:66)
11-06 15:14:45.761 32605-1644/de.test.android.fisheye.local W/System.err:     at de.test.client.api.Evaluator.evaluate(Evaluator.java:54)
11-06 15:14:45.761 32605-1644/de.test.android.fisheye.local W/System.err:     at de.test.client.api.EvaluationService.evaluateNN(EvaluationService.java:114)
11-06 15:14:45.761 32605-1644/de.test.android.fisheye.local W/System.err:     at de.test.client.api.EvaluationService.evaluateSections(EvaluationService.java:73)
11-06 15:14:45.761 32605-1644/de.test.android.fisheye.local W/System.err:     at de.test.neuronalnetwork.service.engine.NetworkEngine.lambda$calculate$0(NetworkEngine.java:59)
11-06 15:14:45.762 32605-1644/de.test.android.fisheye.local W/System.err:     at de.test.neuronalnetwork.service.engine.NetworkEngine$$Lambda$1.call(Unknown Source)
11-06 15:14:45.762 32605-1644/de.test.android.fisheye.local W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
11-06 15:14:45.762 32605-1644/de.test.android.fisheye.local W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
11-06 15:14:45.762 32605-1644/de.test.android.fisheye.local W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
11-06 15:14:45.762 32605-1644/de.test.android.fisheye.local W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
11-06 15:14:45.762 32605-1644/de.test.android.fisheye.local W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
11-06 15:14:45.762 32605-1644/de.test.android.fisheye.local W/System.err: 	... 1 more
```

**Comment by angersson** [comment]
@petewarden Can you take a look at this?

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
A member of the TensorFlow organization has replied after the stat:awaiting tensorflower label was applied.

**Comment by andreas-eberle** [comment]
any news on this?

**Comment by tatatodd** [comment]
@andrewharp can you comment on this?

**Comment by tensorflowbutler** [comment]
Nagging Awaiting TensorFlower: It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Awaiting TensorFlower: It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Awaiting TensorFlower: It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @bignamehyp: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @bignamehyp: It has been 120 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @bignamehyp: It has been 135 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @bignamehyp: It has been 150 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by pogamar** [comment]
I have same problem also, is there any progress? 
@andreas-eberle did you find a solution? or a workaround?

**Comment by andreas-eberle** [comment]
@pogamar: No, unfortunately not.

**Comment by nithinmurali** [comment]
I am also facing this issue while trying to run a model on mobile.  @bignamehyp any updates on when this will be fixed ? or any workarounds?

**Comment by bignamehyp** [comment]
@andrewharp can you comment on this?

**Comment by tensorflowbutler** [comment]
Nagging Assignee @andrewharp: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by jdduke** [comment]
Apologies for the delay, I'll take a look, thanks for your patience.

**Comment by jdduke** [comment]
If you need to support string types, you should make sure that you've built TensorFlow(Mobile) with the __ANDROID_TYPES_FULL__ build define (`--copt=-D__ANDROID_TYPES_FULL__`). See also [register_types.h](https://github.com/tensorflow/tensorflow/blob/9590c4c32dd4346ea5c35673336f5912c6072bf2/tensorflow/core/framework/register_types.h#L89). Otherwise, building for Android defaults to only supporting float, int and bool types.
