### ISSUE TITLE
Supervisor does not initialize parameters

### ISSUE THREAD

**Issue by AlexWang90** [tensorflow/tensorflow#14320]
Hi， 
      It throws an exception when I tried to initialize parameters with tf.train.Supervisor where the net is contructed with tensorlayer. The code is like this:
 
```
    init_op = tf.global_variables_initializer()
    saver = tf.train.Saver()
    config = tf.ConfigProto()
    config.gpu_options.allow_growth = True
    sv = tf.train.Supervisor(logdir=FLAGS.summary_dir, save_summaries_secs=0, saver=None)
    with sv.managed_session(config=config) as sess:
           init_ = sess.run(init_op)
           net.print_params()
           net.print_layers()
            tl.layers.print_all_variables()
```
and the exception is:

```
Cannot evaluate tensor using `eval()`: No default session is registered. Use `with sess.as_default()` or pass an explicit session to `eval(session=sess)`
Traceback (most recent call last):
  File "/home/recsys/anaconda3/envs/tf1.2/lib/python3.6/site-packages/tensorlayer/layers.py", line 309, in print_params
    val = p.eval()
  File "/home/recsys/anaconda3/envs/tf1.2/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 463, in eval
    return self._variable.eval(session=session)
  File "/home/recsys/anaconda3/envs/tf1.2/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 606, in eval
    return _eval_using_default_session(self, feed_dict, self.graph, session)
  File "/home/recsys/anaconda3/envs/tf1.2/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3914, in _eval_using_default_session
    raise ValueError("Cannot evaluate tensor using `eval()`: No default "
ValueError: Cannot evaluate tensor using `eval()`: No default session is registered. Use `with sess.as_default()` or pass an explicit session to `eval(session=sess)`

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "MainEntryPtb.py", line 65, in <module>
    train_rnn(FLAGS)
  File "/home/recsys/wangjian/learntf/TFTemplate/examples/ptb.py", line 122, in train_rnn
    net.print_params()
  File "/home/recsys/anaconda3/envs/tf1.2/lib/python3.6/site-packages/tensorlayer/layers.py", line 313, in print_params
    raise Exception("Hint: print params details after tl.layers.initialize_global_variables(sess) or use network.print_params(False).")
Exception: Hint: print params details after tl.layers.initialize_global_variables(sess) or use network.print_params(False).
```

It seems that when I run initialize op `init_ = sess.run(init_op)`  it does not really work.

I use tensorflow v1.2.1 and python3.6

**Comment by ppwwyyxx** [comment]
All the exceptions are throws from tensorlayer. Why would you think "Supervisor does not initialize parameters"?

**Comment by AlexWang90** [comment]
As if tensorflow initializes parameters succeed,  the following code could run without any Exception.
```
           net.print_params()
           net.print_layers()
            tl.layers.print_all_variables()
```

**Comment by ppwwyyxx** [comment]
> As if tensorflow initializes parameters succeed, the following code could run without any Exception.

You probably came to this wrong conclusion only because of the misleading messages from tensorlayer: ` Hint: print params details after tl.layers.initialize_global_variables(sess)`, which is irrelevant to the bug you're seeing.
In fact TensorFlow is already giving you the correct message: you need `with sess.as_default()`.

**Comment by bignamehyp** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
