### ISSUE TITLE
Build is broken at HEAD

### ISSUE THREAD

**Issue by damienmg** [tensorflow/tensorflow#14375]
From ci.bazel.io (mac and Linux: https://ci.bazel.io/blue/organizations/jenkins/TensorFlow/detail/TensorFlow/1544/pipeline/):

```
ERROR: /home/ci/.cache/bazel/_bazel_ci/9630feff78264ece04615e9d6bad98b7/external/local_config_sycl/sycl/BUILD:14:14: Traceback (most recent call last):
	File "/home/ci/.cache/bazel/_bazel_ci/9630feff78264ece04615e9d6bad98b7/external/local_config_sycl/sycl/BUILD", line 12
		config_setting(name = "using_sycl_ccpp", values =..."})
	File "/home/ci/.cache/bazel/_bazel_ci/9630feff78264ece04615e9d6bad98b7/external/local_config_sycl/sycl/BUILD", line 14, in config_setting
		{"define": "using_sycl=true", "define": "using_trisycl=false"}
Duplicated key "define" when creating dictionary.
ERROR: /home/ci/.cache/bazel/_bazel_ci/9630feff78264ece04615e9d6bad98b7/external/local_config_sycl/sycl/BUILD:22:14: Traceback (most recent call last):
	File "/home/ci/.cache/bazel/_bazel_ci/9630feff78264ece04615e9d6bad98b7/external/local_config_sycl/sycl/BUILD", line 20
		config_setting(name = "using_sycl_trisycl", value..."})
	File "/home/ci/.cache/bazel/_bazel_ci/9630feff78264ece04615e9d6bad98b7/external/local_config_sycl/sycl/BUILD", line 22, in config_setting
		{"define": "using_sycl=true", "define": "using_trisycl=true"}
Duplicated key "define" when creating dictionary.
```

Repro:
```
$ bazel build @local_config_sycl//sycl:sycl
..........
ERROR: /usr/local/google/home/dmarting/.cache/bazel/_bazel_dmarting/7d9873875fd56d2bc53371f0098a5332/external/local_config_sycl/sycl/BUILD:14:14: Traceback (most recent call last):
        File "/usr/local/google/home/dmarting/.cache/bazel/_bazel_dmarting/7d9873875fd56d2bc53371f0098a5332/external/local_config_sycl/sycl/BUILD", line 12
                config_setting(name = "using_sycl_ccpp", values =..."})
        File "/usr/local/google/home/dmarting/.cache/bazel/_bazel_dmarting/7d9873875fd56d2bc53371f0098a5332/external/local_config_sycl/sycl/BUILD", line 14, in config_setting
                {"define": "using_sycl=true", "define": "using_trisycl=false"}
Duplicated key "define" when creating dictionary
ERROR: /usr/local/google/home/dmarting/.cache/bazel/_bazel_dmarting/7d9873875fd56d2bc53371f0098a5332/external/local_config_sycl/sycl/BUILD:22:14: Traceback (most recent call last):
        File "/usr/local/google/home/dmarting/.cache/bazel/_bazel_dmarting/7d9873875fd56d2bc53371f0098a5332/external/local_config_sycl/sycl/BUILD", line 20
                config_setting(name = "using_sycl_trisycl", value..."})
        File "/usr/local/google/home/dmarting/.cache/bazel/_bazel_dmarting/7d9873875fd56d2bc53371f0098a5332/external/local_config_sycl/sycl/BUILD", line 22, in config_setting
                {"define": "using_sycl=true", "define": "using_trisycl=true"}
Duplicated key "define" when creating dictionary
ERROR: error loading package '@local_config_sycl//sycl': Package 'sycl' contains errors
INFO: Elapsed time: 2.250s
FAILED: Build did NOT complete successfully (1 packages loaded)
```
After configuring.

Bisecting blame fe197f7dc5bd3b986141bcdaa27928206e74741a

/cc @gunan

**Comment by smcveigh-phunware** [comment]
+1

**Comment by gunan** [comment]
Fix is now merged.
