### ISSUE TITLE
valueerror when install 0.7.1 in centos 7

### ISSUE THREAD

**Issue by hoyeunglee** [tensorflow/tensorflow#1441]
[martin@localhost ~]$ sudo pip install ./tensorflow-0.7.1-cp27-none-linux_x86_64.whl
[sudo] password for martin: 
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pip/basecommand.py", line 139, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/site-packages/pip/commands/install.py", line 235, in run
    InstallRequirement.from_line(name, None))
  File "/usr/lib/python2.7/site-packages/pip/req.py", line 118, in from_line
    return cls(req, comes_from, url=url)
  File "/usr/lib/python2.7/site-packages/pip/req.py", line 43, in __init__
    req = pkg_resources.Requirement.parse(req)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2914, in parse
    reqs = list(parse_requirements(s))
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2839, in parse_requirements
    line, p, specs = scan_list(VERSION,LINE_END,line,p,(1,2),"version spec")
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2807, in scan_list
    raise ValueError("Expected "+item_name+" in",line,"at",line[p:])
ValueError: ('Expected version spec in', './tensorflow-0.7.1-cp27-none-linux_x86_64.whl', 'at', '/tensorflow-0.7.1-cp27-none-linux_x86_64.whl')

Storing complete log in /root/.pip/pip.log
[martin@localhost ~]$ 
[martin@localhost ~]$ python -V
Python 2.7.5
[martin@localhost ~]$ uname -a
Linux localhost.localdomain 3.10.0-327.10.1.el7.x86_64 #1 SMP Tue Feb 16 17:03:50 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by girving** [comment]
@martinwicke: Looks like the wonderful world of wheel naming conventions?

**Comment by martinwicke** [comment]
Can you try with the 0.9 wheel? I have no idea what the problem can be and the message is useless, but maybe we get lucky.

**Comment by michaelisard** [comment]
Closing due to lack of activity. Please re-open if this is still a problem.
