### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError:

### ISSUE THREAD

**Issue by taeyeon816** [tensorflow/tensorflow#14429]
I got this erros.
I tried to convert csv to tfrecord with https://www.youtube.com/watch?v=kq2Gjv_pPe8

kimvlvl@cmlabUbuntu:~/object-detection$ python3 generate_tfrecord.py --csv_input=data/train_labels.csv  --output_path=datacord
Traceback (most recent call last):
  File "generate_tfrecord.py", line 107, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "generate_tfrecord.py", line 98, in main
    tf_example = create_tf_example(group, path)
  File "generate_tfrecord.py", line 53, in create_tf_example
    encoded_jpg = fid.read()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/lib/io/file_io.py", line 118, in read
    self._preread_check()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/lib/io/file_io.py", line 78, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "/usr/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_ostatus
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.NotFoundError: /home/kimvlvl/object-detection/images/0265.png

I cheacked all the names and labels of xxx.png

please help

**Comment by angersson** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
