### ISSUE TITLE
index_to_string_table_from_file cannot use tf.string as vocabulary file

### ISSUE THREAD

**Issue by OlavHN** [tensorflow/tensorflow#14505]
Running stock tensorflow on macOS I get:

```
import tensorflow as tf

print (tf.__version__)

with open('test', 'w') as f:
  f.write('hello\n')
  f.write('world\n')
  f.write('!\n')

file_path = tf.constant('test')
#file_path = 'test' # this works

a = tf.constant(['world', 'hello'])

with tf.Session() as sess:
  str2i = tf.contrib.lookup.index_table_from_file(vocabulary_file=file_path)
  sess.run(str2i.init)
  i = str2i.lookup(a)
  print(sess.run(i))

  # Other way doesn't work
  i2str = tf.contrib.lookup.index_to_string_table_from_file(vocabulary_file=file_path)
  sess.run(i2str.init)
  s = i2str.lookup(i)
  print(sess.run(s))
```

results in:

```
1.4.0
2017-11-12 23:29:51.316725: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
[1 0]
Traceback (most recent call last):
  File "test.py", line 22, in <module>
    i2str = tf.contrib.lookup.index_to_string_table_from_file(vocabulary_file=file_path)
  File "/Users/olanymoe/anaconda2/envs/tf3/lib/python3.5/site-packages/tensorflow/python/ops/lookup_ops.py", line 1121, in index_to_string_table_from_file
    if not vocabulary_file:
  File "/Users/olanymoe/anaconda2/envs/tf3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 528, in __bool__
    raise TypeError("Using a `tf.Tensor` as a Python `bool` is not allowed. "
TypeError: Using a `tf.Tensor` as a Python `bool` is not allowed. Use `if t is not None:` instead of `if t:` to test if a tensor is defined, and use TensorFlow ops such as tf.cond to execute subgraphs conditioned on the value of a tensor.
```

Expected:

```
1.4.0
2017-11-12 23:30:22.082767: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
[1 0]
[b'world' b'hello']
```

Due to None check at https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/lookup_ops.py#L1126

This is an issue because I can't seem to be able to make `index_to_string_table_from_file` read the vocabulary_file from a `GraphKeys.ASSET_FILEPATHS` collection when storing the graph as a saved_model

**Comment by cy89** [comment]
@ysuematsu can you comment or offer advice here?

**Comment by OlavHN** [comment]
Using the underlying ops of `index_to_string_table_from_file` (`tf.contrib.lookup.HashTable ` with `tf.contrib.lookup.TextFileStringTableInitializer`) which can take the file path as a tf.tensor seems to solve the issue of loading the file from the saved_model assets folder, so I assume the proposed patch from @facaiy for input validation will work for my issue.

**Comment by sathyamoorthyrr** [comment]
```
vocabulary_file = "vocab_target.txt"

table = tf.contrib.lookup.index_table_from_file(
    vocabulary_file,
    vocab_size=None,
    default_value=-1,
    key_dtype=tf.string,
    key_column_index=0,
    value_column_index=1,
    delimiter='\t'
)
```

This results in,

>  TypeError: index_table_from_file() got an unexpected keyword argument 'key_column_index'
