### ISSUE TITLE
Cannot use keras estimator_from_model() in distributed cluster

### ISSUE THREAD

**Issue by droidicus** [tensorflow/tensorflow#14504]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: tf.VERSION = 1.4.0 tf.GIT_VERSION = v1.4.0-rc1-11-g130a514
- **Python version**: 2.7.12
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: 8.0.61/6.0.21
- **GPU model and memory**: NVIDIA Tesla M60 8 GB
- **Exact command to reproduce**: See Below

### Describe the problem
When trying to use an estimator that is derived from ```tf.keras.estimator.estimator_from_model()``` and training with ```tf.estimator.train_and_evaluate()```, it will work as expected if in a standalone non-distributed session. However, when in a distributed training cluster and the TF_CONFIG has the cluster information set, there is a an explicit device assignment of an op to a device that is not valid in the current cluster spec.

Below is code to reproduce this issue. When ```simulate_cluster``` is set to True an error is throws as shown in the log below. When ```simulate_cluster``` is set to False the network is constructed and trained as intended. It should be noted that the error occurs when calling ```tf.keras.estimator.model_to_estimator(keras_model=model)``` and not when doing the training, the cluster config is required for the distributed training to take place.

The TF_CONFIG that is set below is derived from calling the code using the gcloud SDK as follows:
```gcloud ml-engine local train --distributed --parameter-server-count=1 --worker-count=2 --package-path=trainer --module-name=trainer.task --```

### Source code / logs
Minimal example:
```python
import os
import numpy as np
import tensorflow as tf

tf.logging.set_verbosity(tf.logging.INFO)

simulate_cluster = True
if simulate_cluster:
    os.environ["TF_CONFIG"] = '{"environment": "cloud", "cluster": {"worker": ["localhost:27184", "localhost:27185"], \
               "ps": ["localhost:27183"], "master": ["localhost:27182"]}, "job": {"args": [""], \
               "job_name": "trainer.task"}, "task": {"index": 0, "type": "master"}}'
else:
    os.environ["TF_CONFIG"] = ''

inputs = tf.keras.layers.Input(shape=(10,))
outputs = tf.keras.layers.Dense(10)(inputs)
model = tf.keras.models.Model(inputs, outputs)
model.compile(optimizer='Adam', loss='binary_crossentropy')
est_keras = tf.keras.estimator.model_to_estimator(keras_model=model) # InvalidArgumentError thrown here if simulate_cluster is True

input_name = model.input_names[0]
data = np.random.rand(1000,10).astype(np.float32)
train_input_fn = tf.estimator.inputs.numpy_input_fn({input_name:data}, data, batch_size=10, num_epochs=None, shuffle=False)

train_spec = tf.estimator.TrainSpec(input_fn=train_input_fn, max_steps=100)
eval_spec = tf.estimator.EvalSpec(input_fn=train_input_fn, steps=10)
tf.estimator.train_and_evaluate(est_keras, train_spec, eval_spec)
```

InvalidArgumentError emitted when ```simulate_cluster = True```:
```python
Traceback (most recent call last):
  File "minimal.py", line 19, in <module>
    est_keras = tf.keras.estimator.model_to_estimator(keras_model=model)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/_impl/keras/estimator.py", line 280, in model_to_estimator
    _save_first_checkpoint(keras_model, est, custom_objects, keras_weights)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/_impl/keras/estimator.py", line 217, in _save_first_checkpoint
    model.set_weights(keras_weights)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/_impl/keras/engine/topology.py", line 766, in set_weights
    K.batch_set_value(tuples)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/_impl/keras/backend.py", line 2406, in batch_set_value
    get_session().run(assign_ops, feed_dict=feed_dict)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/_impl/keras/backend.py", line 376, in get_session
    _initialize_variables(session)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/_impl/keras/backend.py", line 554, in _initialize_variables
    [variables_module.is_variable_initialized(v) for v in candidate_vars])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device for operation 'loss/dense_1_loss/sub': Operation was explicitly assigned to /job:master/task:0 but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0, /job:localhost/replica:0/task:0/device:GPU:0, /job:localhost/replica:0/task:0/device:GPU:1, /job:localhost/replica:0/task:0/device:GPU:2, /job:localhost/replica:0/task:0/device:GPU:3 ]. Make sure the device specification refers to a valid device.
         [[Node: loss/dense_1_loss/sub = Sub[T=DT_FLOAT, _device="/job:master/task:0"](loss/dense_1_loss/sub/x, loss/dense_1_loss/Const)]]

Caused by op u'loss/dense_1_loss/sub', defined at:
  File "minimal.py", line 19, in <module>
    est_keras = tf.keras.estimator.model_to_estimator(keras_model=model)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/_impl/keras/estimator.py", line 280, in model_to_estimator
    _save_first_checkpoint(keras_model, est, custom_objects, keras_weights)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/_impl/keras/estimator.py", line 209, in _save_first_checkpoint
    custom_objects)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/_impl/keras/estimator.py", line 124, in _clone_and_build_model
    target_tensors=target_tensors)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/_impl/keras/engine/training.py", line 840, in compile
    output_loss = weighted_loss(y_true, y_pred, sample_weight, mask)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/_impl/keras/engine/training.py", line 444, in weighted
    score_array = fn(y_true, y_pred)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/_impl/keras/losses.py", line 78, in binary_crossentropy
    return K.mean(K.binary_crossentropy(y_true, y_pred), axis=-1)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/_impl/keras/backend.py", line 3027, in binary_crossentropy
    output = clip_ops.clip_by_value(output, epsilon_, 1 - epsilon_)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/math_ops.py", line 910, in r_binary_op_wrapper
    return func(x, y, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_math_ops.py", line 4636, in _sub
    "Sub", x=x, y=y, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Cannot assign a device for operation 'loss/dense_1_loss/sub': Operation was explicitly assigned to /job:master/task:0 but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0, /job:localhost/replica:0/task:0/device:GPU:0, /job:localhost/replica:0/task:0/device:GPU:1, /job:localhost/replica:0/task:0/device:GPU:2, /job:localhost/replica:0/task:0/device:GPU:3 ]. Make sure the device specification refers to a valid device.
         [[Node: loss/dense_1_loss/sub = Sub[T=DT_FLOAT, _device="/job:master/task:0"](loss/dense_1_loss/sub/x, loss/dense_1_loss/Const)]]
```

Full logs, tf_env, and more are here: https://gist.github.com/droidicus/2abd4ddad81a1e9169a1c7a100057b15

**Comment by yaroslavvb** [comment]
Which instructions/examples are you following? Usually there are some extra steps needed to configure the cluster

**Comment by droidicus** [comment]
Primary reference for the Keras model -> Estimator: https://www.tensorflow.org/api_docs/python/tf/keras/estimator/model_to_estimator
Primary reference for the TF_CONFIG settings for cluster: https://www.tensorflow.org/api_docs/python/tf/estimator/train_and_evaluate
Primary reference for gcloud ml-engine: https://cloud.google.com/sdk/gcloud/reference/ml-engine/

I agree that the code snippet above will likely not proceed to completion when simulate_cluster is set to true even without the error shown above, since this is just simulating a single job (in this case master). It is rather intended to show that when the custer spec is set in the TF_CONFIG variable (as required by tf.estimator.train_and_evaluate()) the call to tf.keras.estimator.model_to_estimator() fails.

The code after the call to tf.keras.estimator.model_to_estimator() is there only to show that the estimator created from the keras model works correctly when simulate_cluster is set to false, and is not intended to show a full working distributed training solution. I do have a full solution, but it is much larger and multi-file, this was an attempt at a minimal example of the keras estimator error only.

The full model training code is based on a working example in TFv1.3 using tf.estimator.EstimatorSpec() to manually create an estimator from a keras model ops, tf.contrib.learn.Experiment(), and tf.contrib.learn.learn_runner.run(). The hope here is to transition over to core functions since TFv1.4 now has them.

**Comment by yaroslavvb** [comment]
That page seems to be for distributed training of estimator. Don't know if distributed training on Keras is supported, cc @fchollet 

For distributed training, session needs to be created in a different way, ie, `tf.Session("grpc://....")`. From your error it looks like keras creates just a regular local session `tf.Session()`

**Comment by mvsusp** [comment]
I'm experimenting exactly the same issue.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by droidicus** [comment]
Gentle ping, this is still an issue for me, and had been confirmed above.

**Comment by tensorflowbutler** [comment]
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by djrut** [comment]
We are seeing this same issue with model_to_estimator, and it is currently blocking a large project. 

Any update?

**Comment by JVOSU** [comment]
me too.

**Comment by tensorflowbutler** [comment]
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by bhack** [comment]
Probably also multi_gpu is not well supported. See https://github.com/tensorflow/tensorflow/issues/16907#issuecomment-366825713

**Comment by bhack** [comment]
@yifeif Do you have coverage of tf.keras.utils.multi_gpu_mode with this commit?

**Comment by JVOSU** [comment]
@bhack I suspect not.  _clone_and_build_model relies on keras.models.clone_model, which appears to copy the underlying keras model, but does not preserve device placement.  

I had to hack model_to_estimator to call multi_gpu_model after the cloned model is created. I suspect a better fix is to have keras.models.clone_model respect device placement, or to remove the need to clone the model altogether.  It is unclear to me why this is needed, rather than to use the input keras_model directly in model_fn and _save_first_checkpoint.

This is critical to support distributed training + multi_gpu.  Ideally, this would be officially supported in tf 1.6.

**Comment by bhack** [comment]
@JVOSU so is it related also to https://github.com/tensorflow/tensorflow/issues/16468?

**Comment by zippeurfou** [comment]
Any update on this?
Having an example that use keras + multi gpu + distributed cluster seems in my opinion pretty important for anyone the want to do production work.

**Comment by bhack** [comment]
@zippeurfou This is now closed. Probably you can open a new Documentation/example issue  mentioning this one.

**Comment by droidicus** [comment]
The original issue should be resolved in TFv1.6, although I will admit to not having had the chance to test it yet. As for a comprehensive example, that would be nice, but to the best of my knowledge it doesn't exist currently.

**Comment by zippeurfou** [comment]
@droidicus Cloud ML is not on 1.6 [ source ](https://cloud.google.com/ml-engine/docs/runtime-version-list) but I guess it will come at some point or you can manually force it.
@bhack As much as I agree with you I really think that just a gist would be enough for most people than a full tutorial especially since this is the first result when you google `distributed model_to_estimator`.

**Comment by bhack** [comment]
I still think that is partially a counter sense to non having Highlevel api documented or with example cause are the first ones that a beginner is approaching. As @JVOSU confirmed probably `model_to_estimator` is not working with Distributed/Multi-gpu also If I think that users will try to use it also if undocumented :smile:
