### ISSUE TITLE
Can not import transformed and quantized model using tf.import_graph_def

### ISSUE THREAD

**Issue by phongnhhn92** [tensorflow/tensorflow#14535]
Hello guys,
I am trying to quantized the pretrain SSD_mobilenet_v1_coco from the Tensorflow Object Detection API using the following command:
`bazel build tensorflow/tools/graph_transforms:transform_graph
bazel-bin/tensorflow/tools/graph_transforms/transform_graph \
--in_graph=MobileNetSSD.pb \
--out_graph=optimized_SSD.pb \
--inputs='image_tensor' \
--outputs='detection_boxes,detection_scores,detection_classes,num_detections' \
--transforms='
  add_default_attributes
  strip_unused_nodes(type=uint8, shape="1,300,300,3")  
  fold_constants(ignore_errors=true)
  fold_batch_norms
  fold_old_batch_norms
  quantize_weights
  quantize_nodes
  strip_unused_nodes
  sort_by_execution_order'`

The command run successfully and I had the optimized_SSD.pb with only 6MB. However, when I try to use this pb model in the provided IPython Notebook file [title](https://github.com/tensorflow/models/blob/master/research/object_detection/object_detection_tutorial.ipynb) I received this error:
`Traceback (most recent call last):
  File "/home/phong/PycharmProjects/ConvertDarknet2VOC/evaluation.py", line 52, in <module>
    tf.import_graph_def(od_graph_def, name='')
  File "/home/phong/.virtualenvs/tensorflow_pycharm/local/lib/python2.7/site-packages/tensorflow/python/framework/importer.py", line 283, in import_graph_def
    raise ValueError('No op named %s in defined operations.' % node.op)
ValueError: No op named QuantizedResizeBilinear in defined operations.`

Is there any way to load the quantized model using tensorflow ?

**Comment by cy89** [comment]
Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?  Make sure you also include the exact command if possible to produce  the output included in your test case. If you are unclear what to include  see the issue template displayed in  [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

 We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!

**Comment by offbye** [comment]
I quantize the ssd_mobilenet_v1 model o ubuntu 14,  using the below command
```
bazel-bin/tensorflow/tools/graph_transforms/transform_graph --in_graph=/data5/zxt/coco_log/export/frozen_inference_graph.pb  --out_graph=/home/zxt/git/ssd_optimized.pb --inputs='image_tensor' --outputs='detection_boxes,detection_scores,num_detections,detection_classes' --transforms='
  add_default_attributes
  strip_unused_nodes(type=float, shape="-1,-1,-1,3")
  remove_nodes(op=Identity, op=CheckNumerics)
  fold_batch_norms
  fold_old_batch_norms
  quantize_weights
  strip_unused_nodes
  sort_by_execution_order'
```
I also have tried some other parameters，but all failed with same issue.
When run on android phone, met errors
```
                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:799)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:689)
                                                                        Caused by: java.io.IOException: Not a valid TensorFlow Graph serialization: NodeDef mentions attr 'T' not in Op<name=Where; signature=input:bool -> index:int64>; NodeDef: Postprocessor/BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/FilterGreaterThan/Where = Where[T=DT_BOOL](Postprocessor/BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/FilterGreaterThan/Greater). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
                                                                           at org.tensorflow.contrib.android.TensorFlowInferenceInterface.loadGraph(TensorFlowInferenceInterface.java:535)
 
```

**Comment by phongnhhn92** [comment]
@cy89 I am sorry I didnt include required information. This is it
System information

OS Platform and Distribution (Linux Ubuntu 16.04.05 LTS):
TensorFlow installed from source:
**TensorFlow version : 1.4.0-rc1
Python version: 2.7
**Bazel version : 0.70
GCC/Compiler version (if compiling from source): 5.4.0
**CUDA/cuDNN version : 8.0
**GPU model and memory: NVIDIA 1070 GTX

**Comment by phongnhhn92** [comment]
Also I would like to update what I have done so far.
With my trained model, using the following command I can have the same results on both PC and android version.
`
bazel-bin/tensorflow/tools/graph_transforms/transform_graph \
--in_graph=frozen_inference_graph.pb \
--out_graph=optimized_SSD_graph.pb \
--inputs='image_tensor' \
--outputs='num_detections,detection_boxes,detection_scores,detection_classes' \
--transforms='  
  sort_by_execution_order
  fold_batch_norms
  fold_old_batch_norms
  strip_unused_nodes
  round_weights(num_steps=256)'
`
However if I add 'quantize_weights' graph transformation then I almost can not detect anything (zero bounding box detected)
`
bazel-bin/tensorflow/tools/graph_transforms/transform_graph \
--in_graph=frozen_inference_graph.pb \
--out_graph=optimized_SSD_graph.pb \
--inputs='image_tensor' \
--outputs='num_detections,detection_boxes,detection_scores,detection_classes' \
--transforms='  
  sort_by_execution_order
  fold_batch_norms
  fold_old_batch_norms
  strip_unused_nodes
  round_weights(num_steps=256)
  quantize_weights'
`

**Comment by reedwm** [comment]
/CC @petewarden do you know what the issue is?

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Awaiting TensorFlower: It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Awaiting TensorFlower: It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by zyuan2009** [comment]
Same problem happens to me, and I managed to fix it
a. Add a dependency ""//tensorflow/python:image_ops" to import_pb_to_tensorboard target
b. Add an import "from tensorflow.python.ops import gen_image_ops" to import_pb_to_tensorboard.py

diff:

diff --git a/tensorflow/python/tools/BUILD b/tensorflow/python/tools/BUILD
index 63f16c5..23e8055 100644
--- a/tensorflow/python/tools/BUILD
+++ b/tensorflow/python/tools/BUILD
@@ -71,6 +71,7 @@ py_binary(
         "//tensorflow/python:client",
         "//tensorflow/python:framework",
         "//tensorflow/python:framework_ops",
+        "//tensorflow/python:image_ops",
         "//tensorflow/python:platform",
         "//tensorflow/python:summary",
     ],
diff --git a/tensorflow/python/tools/import_pb_to_tensorboard.py b/tensorflow/python/tools/import_pb_to_tensorboard.py
index 00de044..a83ff1d 100755
--- a/tensorflow/python/tools/import_pb_to_tensorboard.py
+++ b/tensorflow/python/tools/import_pb_to_tensorboard.py
@@ -25,6 +25,7 @@ from tensorflow.core.framework import graph_pb2
 from tensorflow.python.client import session
 from tensorflow.python.framework import importer
 from tensorflow.python.framework import ops
+from tensorflow.python.ops import gen_image_ops
 from tensorflow.python.platform import app
 from tensorflow.python.platform import gfile
 from tensorflow.python.summary import summary

**Comment by tensorflowbutler** [comment]
Nagging Awaiting TensorFlower: It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Awaiting TensorFlower: It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging TensorFlower: It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @skye: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @suharshs: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @suharshs: It has been 37 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @suharshs: It has been 52 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @suharshs: It has been 67 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.
