### ISSUE TITLE
freeze_graph "No variables to save"

### ISSUE THREAD

**Issue by jasminezz** [tensorflow/tensorflow#14580]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
I do not modify any of the source code
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:
binary
- **TensorFlow version (use command below)**:
1.4.0
- **Python version**: 
3.5
_ **Bazel version
N
_ **CUDA/cuDNN version
N
_ **GPU model and memory
N

### Describe the problem
First, I download mobilenet_v1_0.25_224 pretrained model from [here](http://download.tensorflow.org/models/mobilenet_v1_0.25_224_2017_06_14.tar.gz)

Then,Exporting the Inference Graph, I use the commond:
python export_inference_graph.py \
  --alsologtostderr \
  --model_name=mobilenet_v1_025 \
  --image_size=224 \
  --output_file=/tmp/mobilenet_v1_025_224.pb

Next, freeze graph, I use the command:
python tensorflow/python/tools/freeze_graph.py --input_graph= tmp/mobilenet_v1_025_224.pb --input_checkpoint=tmp/mobilenet_v1_0.25_224.ckpt --input_binary=true --output_graph=tmp/frozen_mobilenet_v1_025_224.pb --output_node_names=MobileNetV1/Predictions/Reshape_1

Finally, I got the error:
 I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
Traceback (most recent call last):
  File "tensorflow/python/tools/freeze_graph.py", line 350, in <module>
    app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/home/libs/anaconda3/envs/python35/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "tensorflow/python/tools/freeze_graph.py", line 249, in main
    FLAGS.saved_model_tags)
  File "tensorflow/python/tools/freeze_graph.py", line 239, in freeze_graph
    input_meta_graph_def, input_saved_model_dir, saved_model_tags.split(","))
  File "tensorflow/python/tools/freeze_graph.py", line 127, in freeze_graph_with_def_protos
    saver = saver_lib.Saver(var_list=var_list)
  File "/home/libs/anaconda3/envs/python35/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1218, in __init__
    self.build()
  File "/home/libs/anaconda3/envs/python35/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1227, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/libs/anaconda3/envs/python35/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1251, in _build
    raise ValueError("No variables to save")
ValueError: No variables to save

Another machine:
windows 7
tensorflow 1.4.0
python 3.6

Using the same operations, I can get the frozen .pb file successfully.

All source code are not modified.I also  changed the other models to test, and get the same error, need your help?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by jasminezz** [comment]
@tensorflowbutler  I have updated the question, the Exact commands were already described

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by kuonb** [comment]
I got the same error trying to freeze a graph.
I thought the problem is that I'm not saving correctly my variables and model, but I tried different models and I was not successful at freezing any graph.

I copied this very simple code from stackoverflow and added the line to generate the .pb file.
```
import tensorflow as tf

#Prepare to feed input, i.e. feed_dict and placeholders
w1 = tf.placeholder("float", name="w1")
w2 = tf.placeholder("float", name="w2")
b1= tf.Variable(2.0,name="bias")
feed_dict ={w1:4,w2:8}

#Define a test operation that we will restore
w3 = tf.add(w1,w2)
w4 = tf.multiply(w3,b1,name="op_to_restore")
sess = tf.Session()
sess.run(tf.global_variables_initializer())

#Create a saver object which will save all the variables
saver = tf.train.Saver()

#Run the operation by feeding input
print sess.run(w4,feed_dict)
#Prints 24 which is sum of (w1+w2)*b1 

#Now, save the graph
saver.save(sess, 'tmp/model.ckpt',global_step=1000)
builder = tf.saved_model.builder.SavedModelBuilder("exported")
builder.save()
```

It generates the .pb file and it generates the checkpoints. After this, I try to freeze the graph by doing:

bazel-bin/tensorflow/python/tools/freeze_graph --input_graph=../code/exported/saved_model.pb --input_checkpoint=../code/tmp/model.ckpt --input_binary=true --output_graph=../code/exported/frozen_output.pb --output_node_names=op_to_restore

And then I get the same error:

```
  File "/home/user/python_env/course/testfreeze/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/tools/freeze_graph.py", line 350, in <module>
    app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/home/user/python_env/course/testfreeze/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/platform/app.py", line 124, in run
    _sys.exit(main(argv))
  File "/home/user/python_env/course/testfreeze/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/tools/freeze_graph.py", line 249, in main
    FLAGS.saved_model_tags)
  File "/home/user/python_env/course/testfreeze/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/tools/freeze_graph.py", line 239, in freeze_graph
    input_meta_graph_def, input_saved_model_dir, saved_model_tags.split(","))
  File "/home/user/python_env/course/testfreeze/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/tools/freeze_graph.py", line 127, in freeze_graph_with_def_protos
    saver = saver_lib.Saver(var_list=var_list)
  File "/home/user/python_env/course/testfreeze/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/training/saver.py", line 1288, in __init__
    self.build()
  File "/home/user/python_env/course/testfreeze/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/training/saver.py", line 1297, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/user/python_env/course/testfreeze/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/training/saver.py", line 1322, in _build
    raise ValueError("No variables to save")
ValueError: No variables to save
```

Does someone know how to fix it?

**Comment by tensorflowbutler** [comment]
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by yangcong955** [comment]
I have exactly the same problem. Still no response yet.

**Comment by tensorflowbutler** [comment]
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by zhengzhiyuan** [comment]
I have exactly the same problem. Still no response yet.

**Comment by Kaalvonn** [comment]
This problem have occured when i changed model from "ssd_mobilenet_v1_coco_11_06_2017" to "faster_rcnn_inception_resnet_v2_atrous_coco_11_06_2017".
The same also happens when i try "faster_rcnn_resnet101_coco_11_06_2017".

But it works for "ssd_mobilenet_v1_coco_11_06_2017".

**Comment by saeed68gm** [comment]
bump

**Comment by tensorflowbutler** [comment]
Nagging Assignee @petewarden: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by yselivonchyk** [comment]
Encountered a similar problem while trying to freeze graph using meta:

```
python freeze_graph.py \
--input_meta_graph_def=/path/graph-0000-1111111.meta \
--input_checkpoint=/path/min-validation_error.data-00000-of-00001 \
--output_graph=/tmp/frozen_graph.pb \
--output_node_names=super/cool/result
```

which resulted in next error:

```
Traceback (most recent call last):
  File "freeze_graph.py", line 382, in <module>
    run_main()
  File "freeze_graph.py", line 379, in run_main
    app.run(main=my_main, argv=[sys.argv[0]] + unparsed)
  File "/home/sey1pal/tf_gpu/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "freeze_graph.py", line 378, in <lambda>
    my_main = lambda unused_args: main(unused_args, flags)
  File "freeze_graph.py", line 272, in main
    flags.saved_model_tags, checkpoint_version)
  File "freeze_graph.py", line 254, in freeze_graph
    checkpoint_version=checkpoint_version)
  File "freeze_graph.py", line 128, in freeze_graph_with_def_protos
    var_list=var_list, write_version=checkpoint_version)
  File "/home/sey1pal/tf_gpu/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1293, in __init__
    self.build()
  File "/home/sey1pal/tf_gpu/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1302, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/sey1pal/tf_gpu/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1327, in _build
    raise ValueError("No variables to save")
ValueError: No variables to save
```

**Comment by yselivonchyk** [comment]
back to my issue: --input_meta_graph_def should be --input_meta_graph

Yet, it means that a call like:
```
python freeze_graph.py \
--input_checkpoint=/path/min-validation_error.data-00000-of-00001 \
--output_graph=/tmp/frozen_graph.pb \
--output_node_names=super/cool/result
```
will fail with obscure 'ValueError("No variables to save")'. This can be improved

**Comment by tensorflowbutler** [comment]
Nagging Assignee @petewarden: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @petewarden: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @petewarden: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @petewarden: It has been 59 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @petewarden: It has been 74 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by Aashit-Sharma** [comment]
still getting this issue X_X
any solutions ?

**Comment by Aashit-Sharma** [comment]
okay , so the issue is more conceptual than code based : you (and I) aren't choosing the right nodes to optimize

choose the 'central' nodes , it'll work (until you get the next error)

**Comment by tensorflowbutler** [comment]
Nagging Assignee @petewarden: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @petewarden: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by xiaobeibeinihao** [comment]
我也遇到同样的问题

**Comment by xiaobeibeinihao** [comment]
still getting this issue，any solutions ?

**Comment by xiaobeibeinihao** [comment]
@jasminezz how do you resolved this problems

**Comment by tensorflowbutler** [comment]
Nagging Assignee @petewarden: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @petewarden: It has been 31 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by Anastasiya888** [comment]
I have the same issue, please can you suggest any solution?

**Comment by saeed68gm** [comment]
@yselivonchyk I think I know how to resolve this issue. Can you try this command instead:
python freeze_graph.py \
--input_checkpoint=/path/min-validation_error \
--output_graph=/tmp/frozen_graph.pb \
--output_node_names=super/cool/result

**Comment by saeed68gm** [comment]
@Anastasiya888 Can you post your command as well? sometimes this error happens when the checkpoint is not loaded correctly.

**Comment by yselivonchyk** [comment]
@Aashit-Sharma, I think @saeed68gm solution could have been what I did.

From what I remember: there are 2 arguments of freeze_graph that do essentially the same thing but in a different way. If script fails to parse one it automatically assumes that the other one is the right one and a few nested calls later fails with an irrelevant error.
I think it helped when I tried different combination of parameter1/parameter2 and checkpoint path with/without extension (.data-00000-of-00001)

**Comment by tensorflowbutler** [comment]
Nagging Assignee @petewarden: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @petewarden: It has been 30 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by zkl99999** [comment]
same issue, any answer, work?

**Comment by tensorflowbutler** [comment]
Nagging Assignee @petewarden: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @petewarden: It has been 30 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by petewarden** [comment]
@gargn this seems to be a common cause of confusion for users of freeze_graph. Could you look at whether we could improve the error messaging, handling, or documentation to help, since you're looking at that script? Thanks!

**Comment by jvishnuvardhan** [comment]
This is a stale issue. Please check the issue with latest TensorFlow. If the issue still persists in the newer version of TF, please feel free to reopen it by providing details about the issue and a standalone code to reproduce the issue. Thanks!
