### ISSUE TITLE
KeyError: "Couldn't find field google.protobuf.DescriptorProto.ExtensionRange.options"

### ISSUE THREAD

**Issue by monajalal** [tensorflow/tensorflow#14611]
My tensorflow was working fine a few days ago and now I get this error:

```
Last login: Mon Nov 13 17:56:32 on ttys001
pWed Nov 15 22:38:01 :~$ python
Python 3.6.2 |Anaconda custom (x86_64)| (default, Jul 20 2017, 13:14:59)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mona/anaconda/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/Users/mona/anaconda/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/Users/mona/anaconda/lib/python3.6/site-packages/tensorflow/core/framework/graph_pb2.py", line 10, in <module>
    from google.protobuf import descriptor_pb2
  File "/Users/mona/anaconda/lib/python3.6/site-packages/google/protobuf/descriptor_pb2.py", line 409, in <module>
    options=None),
  File "/Users/mona/anaconda/lib/python3.6/site-packages/google/protobuf/descriptor.py", line 501, in __new__
    return _message.default_pool.FindFieldByName(full_name)
KeyError: "Couldn't find field google.protobuf.DescriptorProto.ExtensionRange.options"
>>>
```

And my sys info is:
```
Wed Nov 15 23:41:58 :~$ uname -a
Darwin Monas-MacBook-Pro.local 17.0.0 Darwin Kernel Version 17.0.0: Thu Aug 24 21:48:19 PDT 2017; root:xnu-4570.1.46~2/RELEASE_X86_64 x86_64
Wed Nov 15 23:42:05 :~$ conda list | grep tensorflow
tensorflow                1.1.0               np112py36_0
tensorflow                1.4.0                     <pip>
tensorflow-tensorboard    0.1.8                     <pip>
```

**Comment by monajalal** [comment]
I uninstalled all the packages and installed again using pip and still getting error:
```
Wed Nov 15 23:55:20 :~$ /Users/mona/anaconda/bin/pip install tensorflow tensorflow-tensorboard
Collecting tensorflow
  Using cached tensorflow-1.4.0-cp36-cp36m-macosx_10_11_x86_64.whl
Collecting tensorflow-tensorboard
  Using cached tensorflow_tensorboard-0.1.8-py3-none-any.whl
Requirement already satisfied: protobuf>=3.3.0 in ./anaconda/lib/python3.6/site-packages (from tensorflow)
Requirement already satisfied: numpy>=1.12.1 in ./anaconda/lib/python3.6/site-packages (from tensorflow)
Requirement already satisfied: wheel>=0.26 in ./anaconda/lib/python3.6/site-packages (from tensorflow)
Requirement already satisfied: six>=1.10.0 in ./anaconda/lib/python3.6/site-packages (from tensorflow)
Requirement already satisfied: enum34>=1.1.6 in ./anaconda/lib/python3.6/site-packages (from tensorflow)
Requirement already satisfied: html5lib==0.9999999 in ./anaconda/lib/python3.6/site-packages (from tensorflow-tensorboard)
Requirement already satisfied: markdown>=2.6.8 in ./anaconda/lib/python3.6/site-packages (from tensorflow-tensorboard)
Requirement already satisfied: werkzeug>=0.11.10 in ./anaconda/lib/python3.6/site-packages (from tensorflow-tensorboard)
Requirement already satisfied: bleach==1.5.0 in ./anaconda/lib/python3.6/site-packages (from tensorflow-tensorboard)
Requirement already satisfied: setuptools in ./anaconda/lib/python3.6/site-packages (from protobuf>=3.3.0->tensorflow)
Installing collected packages: tensorflow-tensorboard, tensorflow
Successfully installed tensorflow-1.4.0 tensorflow-tensorboard-0.1.8
Wed Nov 15 23:56:36 :~$ python
Python 3.6.2 |Anaconda custom (x86_64)| (default, Jul 20 2017, 13:14:59)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mona/anaconda/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/Users/mona/anaconda/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/Users/mona/anaconda/lib/python3.6/site-packages/tensorflow/core/framework/graph_pb2.py", line 10, in <module>
    from google.protobuf import descriptor_pb2
  File "/Users/mona/anaconda/lib/python3.6/site-packages/google/protobuf/descriptor_pb2.py", line 409, in <module>
    options=None),
  File "/Users/mona/anaconda/lib/python3.6/site-packages/google/protobuf/descriptor.py", line 501, in __new__
    return _message.default_pool.FindFieldByName(full_name)
KeyError: "Couldn't find field google.protobuf.DescriptorProto.ExtensionRange.options"
>>> quit()
Wed Nov 15 23:57:51 :~$ conda list | grep tensorflow
tensorflow                1.4.0                     <pip>
tensorflow-tensorboard    0.1.8                     <pip>
```

I need both tensorflow and tensor board that's why I used pip. Please suggest a solution.

**Comment by abieler** [comment]
I had the same error today (on manjaro linux, however). Somehow there was a system wide tensorflow installation that was updated (`python-tensorflow-cuda`) which interfered with the pip install of `tensorflow-gpu`. After I uninstalled `python-tensorflow-cuda` everything was back to normal. Hope this helps in your case too!

**Comment by cy89** [comment]
@monajalal can you please try @abieler 's suggestion, and let us know if that doesn't work for you?

**Comment by abieler** [comment]
Edit: after initially solving the problem, I updated TF back to `1.4.0` which broke the installation again. It was then resolved by downgrading `protobuf` as I commented here:

https://github.com/google/protobuf/issues/3631

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue? Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue? Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
It has been 180 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
We are closing this issue for now due to lack of activity. Please comment if this is still an issue for you. Thanks!
