### ISSUE TITLE
Android tensorflow lite kernel_util.cc:34 input_product_scale < output_scale

### ISSUE THREAD

**Issue by jasminezz** [tensorflow/tensorflow#14642]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Windows 7.0
- **TensorFlow installed from (source or binary)**:
- **TensorFlow version (use command below)**:
- **Python version**: 3.0
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:

### Describe the problem
1.down load Quantilized MobileNet model 0.75_224 from [here](https://storage.googleapis.com/download.tensorflow.org/models/mobilenet_v1_0.75_224_frozen.tgz
)

2.Transform the frozen .pb model to .tflite file:
 bazel run --config=opt tensorflow/contrib/lite/toco:toco -- --input_file=tmp/mobilenet_v1_0.75_224/frozen_graph.pb --input_format=TENSORFLOW_GRAPHDEF --output_format=TFLITE --output_file=tmp/mobilenet_v1_0.75_224/mobilenet_v1_0.75_224.tflite --inference_type=QUANTIZED_UINT8  --input_type=QUANTIZED_UINT8  --input_arrays=input --default_ranges_min=0 --default_ranges_max=6 --output_arrays=MobilenetV1/Predictions/Reshape_1 --input_shapes=1,224,224,3

3.Change the "MODEL_PATH" in Tensorflow lite Android demo to "mobilenet_v1_0.75_224.tflite"

### logs
4.Then run the demo, make the error:
FATAL EXCEPTION: CameraBackground
                                                                                      Process: android.example.com.tflitecamerademo, PID: 13909
                                                                                      java.lang.NullPointerException: Can not allocate memory for the given inputs: tensorflow/contrib/lite/kernels/kernel_util.cc:34 input_product_scale < output_scale was not true.
                                                                                          at org.tensorflow.lite.NativeInterpreterWrapper.run(Native Method)
                                                                                          at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:95)
                                                                                          at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:112)
                                                                                          at org.tensorflow.lite.Interpreter.run(Interpreter.java:93)
                                                                                          at com.example.android.tflitecamerademo.ImageClassifier.classifyFrame(ImageClassifier.java:109)
                                                                                          at com.example.android.tflitecamerademo.Camera2BasicFragment.classifyFrame(Camera2BasicFragment.java:663)
                                                                                          at com.example.android.tflitecamerademo.Camera2BasicFragment.-wrap0(Camera2BasicFragment.java)
                                                                                          at com.example.android.tflitecamerademo.Camera2BasicFragment$4.run(Camera2BasicFragment.java:558)
                                                                                          at android.os.Handler.handleCallback(Handler.java:739)
                                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                          at android.os.Looper.loop(Looper.java:135)
                                                                                          at android.os.HandlerThread.run(HandlerThread.java:61)

need your help?

Followed the same steps , transform other mobilenet models, only the  "mobilenet_v1_1.0_128" can run successfully.

**Comment by andrehentz** [comment]
Thanks for the detailed description of the error.

Unfortunately the quantization method used in the models you downloaded are currently incompatible with TF Lite's quantization. (Details: the weights were quantized, and a Dequantize op was introduced post-training, as opposed to retrained the model with quantization in mind). This is why the tensors lack min/max information.

To make this work you need to use pass:
  '--default_ranges_min=0' '--default_ranges_max=6' '--std_values=128' '--mean_values=128'
but bear in mind that this will noticeably affect the accuracy of the model. The alternative is to use the corresponding float model and alter the demo app to provide floating-point input.

**Comment by jasminezz** [comment]
@andrehentz Thanks for you detailed explanation.  
So, if I retrained the models with quantization, the error will be solved?
Moreover,why add '--std_values=128' '--mean_values=128' will let it work? My test mobilenet model is mobilenet_v1_0.75_224?

**Comment by derdav3** [comment]
This appears on iOS as well (do you want a different bug issue?) -stack:  
```
/Library/Developer/CoreSimulator/Devices/10888914-22EB-4CA7-B019-F95D5A8A6F5C/data/Containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
nnapi error: unable to open library libneuralnetworks.so
Loaded model resolved reportertensorflow/contrib/lite/kernels/kernel_util.cc:34 input_product_scale < output_scale was not true.Failed to allocate tensors!(lldb) 
```
  
this also appears with the mentioned retraining parameters:  
`'--default_ranges_min=0' '--default_ranges_max=6' '--std_values=128' '--mean_values=128'`

**Comment by andrehentz** [comment]
No need for a different issue for iOS since this is platform-independent.

The conversion tool uses std_value and mean_value to map raw input values into real values:
    real_value = (raw_input_value - mean_value) / std_value
The default values of 0 and 1 yield real_value = raw_input_value, which in conjunction with -
 inference_type=QUANTIZED_UINT8 means the input will range from 0.0 to 255.0, while the output will use the default ranges or 0.0 to 6.0.

By passing '--std_values=128' '--mean_values=128'  you are telling the conversion tool that the real input values are between -1.0 and 1.0 (for the corresponding uint8 0 and 255), which satisfies the quantization constraint that input_product_scale < output_scale. (That's the gist of it, the details are slightly  more complex).

We are in the process of documenting the details on how to retain a quantized model for TF Lite. Meanwhile, if you are interested there are more details here: https://stackoverflow.com/questions/47463204

**Comment by derdav3** [comment]
@andrehentz thanks a lot for your explanation! maybe I misunderstood, but as I read it `--std_values=128' '--mean_values=128` should resolve it, however at my end the error still persists. (I will try again later today.)

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue? Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue? Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by andrehentz** [comment]
Please reopen and add details if this still happens.

**Comment by shubchat** [comment]
@andrehentz -I tried the above(std_values=128' '--mean_values=128) but still getting the error on ios:

`` nnapi error: unable to open library libneuralnetworks.so
Loaded model 1resolved reportertensorflow/contrib/lite/kernels/kernel_util.cc:37 input_product_scale < output_scale was not true.
Failed to allocate tensors!2018-06-07 06:40:37.952396+1000 tflite_camera_example[9900:3643432] [MC] System group container for systemgroup.com.apple.configurationprofiles path is /private/var/containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
2018-06-07 06:40:37.954062+1000 tflite_camera_example[9900:3643432] [MC] Reading from public effective user settings error: unable to open library libneuralnetworks.so
Loaded model 1resolved reportertensorflow/contrib/lite/kernels/kernel_util.cc:37 input_product_scale < output_scale was not true.
Failed to allocate tensors!2018-06-07 06:40:37.952396+1000 tflite_camera_example[9900:3643432] [MC] System group container for systemgroup.com.apple.configurationprofiles path is /private/var/containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
2018-06-07 06:40:37.954062+1000 tflite_camera_example[9900:3643432] [MC] Reading from public effective user settings.

@derdav3 -Were you able to resolve this for ios?
