### ISSUE TITLE
Unable to install Tensorflow on Ubuntu - Anaconda error trace

### ISSUE THREAD

**Issue by vickylance** [tensorflow/tensorflow#14654]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Ubuntu 16.04.2 LTS
- **TensorFlow installed from (source or binary)**:binary
- **TensorFlow version (use command below)**:1.4.0
- **Python version**: 3.5.4
- **Bazel version (if compiling from source)**:NA
- **GCC/Compiler version (if compiling from source)**:NA
- **CUDA/cuDNN version**:NA
- **GPU model and memory**:NA
- **Exact command to reproduce**: 

You can collect some of this information using our environment capture script:

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

### Describe the problem
I am installing the latest version of tensorflow 1.4.0 and I am getting an error when I try to install it inside a conda environment.

`
conda create -n py36-tensorflow python=3.6
`
`
source activate py36-tensorflow
`
`
pip install --ignore-installed --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.4.0-cp36-cp36m-linux_x86_64.whl
`

the above are the commands I ran and below is the error trace I am getting.

### Source code / logs
Logs:

`ubuntuvm@ubuntuvm:~$ conda create -n py36-tensorflow python=3.6`
`Fetching package metadata ...........`
`Solving package specifications: .`

Package plan for installation in environment /home/ubuntuvm/anaconda3/envs/py36-tensorflow:

The following NEW packages will be INSTALLED:

    ca-certificates: 2017.08.26-h1d4fec5_0
    certifi:         2017.7.27.1-py36h8b7b77e_0
    libedit:         3.1-heed3624_0
    libffi:          3.2.1-hd88cf55_4
    libgcc-ng:       7.2.0-h7cc24e2_2
    libstdcxx-ng:    7.2.0-h7a57d05_2
    ncurses:         6.0-h9df7e31_2
    openssl:         1.0.2m-h26d622b_1
    pip:             9.0.1-py36h6c6f9ce_4
    python:          3.6.3-h1284df2_4
    readline:        7.0-ha6073c6_4
    setuptools:      36.5.0-py36he42e2e1_0
    sqlite:          3.20.1-hb898158_2
    tk:              8.6.7-hc745277_3
    wheel:           0.29.0-py36he7f4e38_1
    xz:              5.2.3-h55aa19d_2
    zlib:            1.2.11-ha838bed_2

Proceed ([y]/n)? y
```
python-3.6.3-h 100% |#################################################################| Time: 0:00:01  16.93 MB/s
pip-9.0.1-py36 100% |#################################################################| Time: 0:00:00  54.97 MB/s
`#`
`# To activate this environment, use:`
`# > source activate py36-tensorflow`
`#`
`# To deactivate an active environment, use:`
`# > source deactivate`
`#`

`ubuntuvm@ubuntuvm:~$ source activate py36-tensorflow`
`(py36-tensorflow) ubuntuvm@ubuntuvm:~$ pip install --ignore-installed --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.4.0-cp36-cp36m-linux_x86_64.whl`
`Collecting tensorflow==1.4.0 from https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.4.0-cp36-cp36m-linux_x86_64.whl`
  `Downloading https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.4.0-cp36-cp36m-linux_x86_64.whl (41.2MB)`
    100% |████████████████████████████████| 41.2MB 33kB/s
`Collecting protobuf>=3.3.0 (from tensorflow==1.4.0)`
  Using cached protobuf-3.5.0-py2.py3-none-any.whl
`Collecting tensorflow-tensorboard<0.5.0,>=0.4.0rc1 (from tensorflow==1.4.0)`
  Using cached tensorflow_tensorboard-0.4.0rc3-py3-none-any.whl
`Collecting six>=1.10.0 (from tensorflow==1.4.0)`
  Using cached six-1.11.0-py2.py3-none-any.whl
`Collecting enum34>=1.1.6 (from tensorflow==1.4.0)`
  Using cached enum34-1.1.6-py3-none-any.whl
`Collecting wheel>=0.26 (from tensorflow==1.4.0)`
  Using cached wheel-0.30.0-py2.py3-none-any.whl
`Collecting numpy>=1.12.1 (from tensorflow==1.4.0)`
Exception:
Traceback (most recent call last):
  File "/home/ubuntuvm/anaconda3/envs/py36-tensorflow/lib/python3.6/site-packages/pip/basecommand.py", line 215,in main
    status = self.run(options, args)
  File "/home/ubuntuvm/anaconda3/envs/py36-tensorflow/lib/python3.6/site-packages/pip/commands/install.py", line335, in run
    wb.build(autobuilding=True)
  File "/home/ubuntuvm/anaconda3/envs/py36-tensorflow/lib/python3.6/site-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/home/ubuntuvm/anaconda3/envs/py36-tensorflow/lib/python3.6/site-packages/pip/req/req_set.py", line 380,in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/home/ubuntuvm/anaconda3/envs/py36-tensorflow/lib/python3.6/site-packages/pip/req/req_set.py", line 554,in _prepare_file
    require_hashes
  File "/home/ubuntuvm/anaconda3/envs/py36-tensorflow/lib/python3.6/site-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/home/ubuntuvm/anaconda3/envs/py36-tensorflow/lib/python3.6/site-packages/pip/index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/home/ubuntuvm/anaconda3/envs/py36-tensorflow/lib/python3.6/site-packages/pip/index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/home/ubuntuvm/anaconda3/envs/py36-tensorflow/lib/python3.6/site-packages/pip/index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "/home/ubuntuvm/anaconda3/envs/py36-tensorflow/lib/python3.6/site-packages/pip/index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/home/ubuntuvm/anaconda3/envs/py36-tensorflow/lib/python3.6/site-packages/pip/index.py", line 792, in get_page
    "Cache-Control": "max-age=600",
  File "/home/ubuntuvm/anaconda3/envs/py36-tensorflow/lib/python3.6/site-packages/pip/_vendor/requests/sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
  File "/home/ubuntuvm/anaconda3/envs/py36-tensorflow/lib/python3.6/site-packages/pip/download.py", line 386, inrequest
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/home/ubuntuvm/anaconda3/envs/py36-tensorflow/lib/python3.6/site-packages/pip/_vendor/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ubuntuvm/anaconda3/envs/py36-tensorflow/lib/python3.6/site-packages/pip/_vendor/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/home/ubuntuvm/anaconda3/envs/py36-tensorflow/lib/python3.6/site-packages/pip/_vendor/cachecontrol/adapter.py", line 37, in send
    cached_response = self.controller.cached_request(request)
  File "/home/ubuntuvm/anaconda3/envs/py36-tensorflow/lib/python3.6/site-packages/pip/_vendor/cachecontrol/controller.py", line 111, in cached_request
    resp = self.serializer.loads(request, cache_data)
  File "/home/ubuntuvm/anaconda3/envs/py36-tensorflow/lib/python3.6/site-packages/pip/_vendor/cachecontrol/serialize.py", line 114, in loads
    return getattr(self, "_loads_v{0}".format(ver))(request, data)
  File "/home/ubuntuvm/anaconda3/envs/py36-tensorflow/lib/python3.6/site-packages/pip/_vendor/cachecontrol/serialize.py", line 176, in _loads_v2
    cached = json.loads(zlib.decompress(data).decode("utf8"))
zlib.error: Error -5 while decompressing data: incomplete or truncated stream
(py36-tensorflow) ubuntuvm@ubuntuvm:~$`
```

**Comment by gunan** [comment]
looks to be simply a bad download?
Could you retry installation, and see if it repeats exactly the same way?

If it still does not work, we recommend following one of the official installation methods here:
https://www.tensorflow.org/install/install_linux

**Comment by vickylance** [comment]
@gunan If I simply do 
`pip install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.4.0-cp36-cp36m-linux_x86_64.whl`
then it is installing (however without numpy), but I did 
`pip install numpy`
I am getting requirement already satisfied. 
But if I do 
`pip install numpy --upgrade`
I am getting that exception again
I think I am not able to retrieve the latest version of numpy package.
My numpy version is '1.13.3' Can I use this with the latest version of tensorflow 1.4.0?

**Comment by vickylance** [comment]
@gunan However when I import the tensorflow library. I am getting the below warning.

`>>> import tensorflow
/home/ubuntuvm/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
>>>`

I assume the above warning is just a normal warning because I tried in a diffrent ubuntu machine where it installed properly. And yes I used the 1.4.0 version. And upon importing the library in python I still got the same warning.

**Comment by gunan** [comment]
@vickylance Thanks for trying out the suggestions.
TF should work fine with numpy 1.13.3, that is why the first command installs without numpy.

About the warning you are seeing. It looks like just a warning. can you use TF normally despite that?
In case you see issues, it should be fixed in our latest nightly packages.

**Comment by vickylance** [comment]
@gunan In windows I see no issues/warnings but its definitely persistent in ubuntu I tried in 3 different environments of ubuntu. And the warning is still there. But I think it should work fine with no issues.

Thanks for the help. I am closing this issue for now. Will reopen if I were to face some issue due to it.
