### ISSUE TITLE
i'm a newcomer , and met the following problem!!

### ISSUE THREAD

**Issue by cav-cav** [tensorflow/tensorflow#14686]
i install tensorflow following the guide explanation in 
**www.tensorflow.org/install/install_windows**
### System information
- **OS Platform and Distribution:win10
- **TensorFlow installed from (source or binary)**:source
- **TensorFlow version (use command below): i use the following command: pip3 install --upgrade tensorflow-gpu
- **Python version:3.5.2 
- **CUDA/cuDNN version**:cuda 8.0 /cudnn 8.0
- **GPU model and memory:GTX1070 8g
i download the source successfully and when i enter the following short program inside the python interactive shell:   import tensorflow as tf
it goes wrong:
Traceback (most recent call last):
  File "E:\SoftWare\Python\lib\site-packages\tensorflow\python\platform\self_check.py", line 87, in preload_check
    ctypes.WinDLL(build_info.cudnn_dll_name)
  File "E:\SoftWare\Python\lib\ctypes\__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] Could not find the specified module

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\SoftWare\Python\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "E:\SoftWare\Python\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "E:\SoftWare\Python\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 30, in <module>
    self_check.preload_check()
  File "E:\SoftWare\Python\lib\site-packages\tensorflow\python\platform\self_check.py", line 97, in preload_check
    % (build_info.cudnn_dll_name, build_info.cudnn_version_number))
ImportError: Could not find 'cudnn64_6.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Note that installing cuDNN is a separate step from installing CUDA, and this DLL is often found in a different directory from the CUDA DLLs. You may install the necessary DLL by downloading cuDNN 6 from this URL: https://developer.nvidia.com/cudnn

in my file sys ,the dll file's name is cudnn64_5.dll
and following is my path:
![image](https://user-images.githubusercontent.com/33776263/32978257-56054f12-cc79-11e7-838e-a10a1b138b07.png)
(i can find my msvcp140.dll)
please help ,thx

**Comment by qmick** [comment]
As the document says, you should use cuDNN v6.1.

**Comment by cav-cav** [comment]
@qmick ok! uh i'm sorry that i asked question here. but thanks for your help,i‘ve solved the problem!
