### ISSUE TITLE
failed to bazel build tensorflow lite 

### ISSUE THREAD

**Issue by wujsy** [tensorflow/tensorflow#14706]
build tensorflow lite  demo with "bazel --output_base=/data/wjx/bazel/tensorflow/output --output_user_root=/data/wjx/bazel/tensorflow build --cxxopt='--std=c++11'  //tensorflow/contrib/
lite/java/demo/app/src/main:TfLiteCameraDemo"

Environment:
OS: ubuntu 16.04
tf version: tensorflow 1.4 master
python:2.7.12
AndroidSDK: 27 BuildToolsVersion: 27.0.1
NDK: android-ndk-r14e

ERROR: /data/wjx/bazel/tensorflow/output/external/androidsdk/com.android.support/BUILD:4277:1: Merging Android resources for @androidsdk//com.android.support:support-compat-25.2.0 failed (Exit 1)
Nov 20, 2017 1:31:06 AM com.google.devtools.build.android.AndroidResourceMergingAction main
SEVERE: Unexpected
java.io.IOException: Mount point not found
	at sun.nio.fs.LinuxFileStore.findMountEntry(LinuxFileStore.java:91)
	at sun.nio.fs.UnixFileStore.<init>(UnixFileStore.java:65)
	at sun.nio.fs.LinuxFileStore.<init>(LinuxFileStore.java:44)
	at sun.nio.fs.LinuxFileSystemProvider.getFileStore(LinuxFileSystemProvider.java:51)
	at sun.nio.fs.LinuxFileSystemProvider.getFileStore(LinuxFileSystemProvider.java:39)
	at sun.nio.fs.UnixFileSystemProvider.getFileStore(UnixFileSystemProvider.java:368)
	at java.nio.file.Files.getFileStore(Files.java:1461)
	at com.google.devtools.build.android.ScopedTemporaryDirectory.makeWritable(ScopedTemporaryDirectory.java:59)
	at com.google.devtools.build.android.ScopedTemporaryDirectory.visitFile(ScopedTemporaryDirectory.java:83)
	at com.google.devtools.build.android.ScopedTemporaryDirectory.visitFile(ScopedTemporaryDirectory.java:36)
	at java.nio.file.Files.walkFileTree(Files.java:2670)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at com.google.devtools.build.android.ScopedTemporaryDirectory.close(ScopedTemporaryDirectory.java:96)
	at com.google.devtools.build.android.AndroidResourceMergingAction.main(AndroidResourceMergingAction.java:289)
	at com.google.devtools.build.android.ResourceProcessorBusyBox$Tool$7.call(ResourceProcessorBusyBox.java:91)
	at com.google.devtools.build.android.ResourceProcessorBusyBox.main(ResourceProcessorBusyBox.java:172)

Exception in thread "main" java.io.IOException: Mount point not found
	at sun.nio.fs.LinuxFileStore.findMountEntry(LinuxFileStore.java:91)
	at sun.nio.fs.UnixFileStore.<init>(UnixFileStore.java:65)
	at sun.nio.fs.LinuxFileStore.<init>(LinuxFileStore.java:44)
	at sun.nio.fs.LinuxFileSystemProvider.getFileStore(LinuxFileSystemProvider.java:51)
	at sun.nio.fs.LinuxFileSystemProvider.getFileStore(LinuxFileSystemProvider.java:39)
	at sun.nio.fs.UnixFileSystemProvider.getFileStore(UnixFileSystemProvider.java:368)
	at java.nio.file.Files.getFileStore(Files.java:1461)
	at com.google.devtools.build.android.ScopedTemporaryDirectory.makeWritable(ScopedTemporaryDirectory.java:59)
	at com.google.devtools.build.android.ScopedTemporaryDirectory.visitFile(ScopedTemporaryDirectory.java:83)
	at com.google.devtools.build.android.ScopedTemporaryDirectory.visitFile(ScopedTemporaryDirectory.java:36)
	at java.nio.file.Files.walkFileTree(Files.java:2670)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at com.google.devtools.build.android.ScopedTemporaryDirectory.close(ScopedTemporaryDirectory.java:96)
	at com.google.devtools.build.android.AndroidResourceMergingAction.main(AndroidResourceMergingAction.java:289)
	at com.google.devtools.build.android.ResourceProcessorBusyBox$Tool$7.call(ResourceProcessorBusyBox.java:91)
	at com.google.devtools.build.android.ResourceProcessorBusyBox.main(ResourceProcessorBusyBox.java:172)
Target //tensorflow/contrib/lite/java/demo/app/src/main:TfLiteCameraDemo failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 16.750s, Critical Path: 3.39s
FAILED: Build did NOT complete successfully

can anyone help me?

**Comment by angersson** [comment]
I've discovered this too, running builds in Docker. I'm surprised, because a very similar environment didn't have this issue.

**Comment by angersson** [comment]
@wujsy, are you using Docker for this?

**Comment by angersson** [comment]
This is a Bazel version problem. You're probably using Bazel 0.5.4 -- switching from that version to the latest Bazel version fixes the problem when I saw it in my builds.

**Comment by wujsy** [comment]
@angersson Thanks for your reply, Yes, I use Docker for building, my bazel version 0.7.0, but I can build sucessfully if do not use a Docker. So I doubt that is it a Docker problem?
Here is my Docker system info:
### System information
- **Have I written custom code: No
- **OS Platform and Distribution : Linux Ubuntu 16.04
- **TensorFlow installed from: Source
- **TensorFlow version (use command below)**: 1.4
- **Python version**: 2.7.12
- **Bazel version (if compiling from source)**: 0.7.0
- **GCC/Compiler version (if compiling from source)**:5.4.0
- **CUDA/cuDNN version**: 8.0 / 6.0
- **GPU model and memory**: GPU K80 12G
