### ISSUE TITLE
//tensorflow/python:session_list_devices_test fails on X86

### ISSUE THREAD

**Issue by sandipmgiri** [tensorflow/tensorflow#14711]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
     Ubuntu 16.04 
- **TensorFlow installed from (source or binary)**:
      Installed from source
- **TensorFlow version (use command below)**:
      TF-1.3.1
- **Python version**:
      Python 2.7.12
- **Bazel version (if compiling from source)**:
      Bazel - 0.5.4
- **CUDA/cuDNN version**:
      NA
- **GPU model and memory**:
      NA
- **Exact command to reproduce**:
     ` bazel test --config=opt  //tensorflow/python:session_list_devices_test `

### Describe the problem
Following 3 sub-tests are failing on Ubuntu:16.04 (x86) with the assertion errors
1) FAIL: testListDevices (__main__.SessionListDevicesWithCApiTest)
https://github.com/tensorflow/tensorflow/blob/v1.3.1/tensorflow/python/client/session_list_devices_test.py#L39
 `self.assertGreaterEqual(1, len(devices), devices)` .....# Getting AssertionError due to: "1" unexpectedly not greater than or equal to "3"  
2) FAIL: testListDevicesGrpcSession (__main__.SessionListDevicesWithCApiTest)
https://github.com/tensorflow/tensorflow/blob/v1.3.1/tensorflow/python/client/session_list_devices_test.py#L47
 `self.assertGreaterEqual(1, len(devices), devices`) .....#  Getting AssertionError due to: "1" unexpectedly not greater than or equal to "3"  
3) FAIL: testListDevicesClusterSpecPropagation (__main__.SessionListDevicesWithCApiTest)
https://github.com/tensorflow/tensorflow/blob/v1.3.1/tensorflow/python/client/session_list_devices_test.py#L66
 `self.assertGreaterEqual(2, len(devices), devices)` ..... #  Getting AssertionError due to: "2" unexpectedly not greater than or equal to "6"

Is this is a known failure (can we ignore ) or I am missing something here ?. Please provide your comments on this.Thanks!
### Source code / logs
```

$  bazel test --config=opt  //tensorflow/python:session_list_devices_test

2017-11-20 08:35:46.791667: W tensorflow/core/distributed_runtime/rpc/grpc_session.cc:343] GrpcSession::ListDevices will initialize the session with an empty graph and other defaults because the session has not yet been created.
2017-11-20 08:35:46.795931: I tensorflow/core/distributed_runtime/master_session.cc:998] Start master session 026f646fb0c59742 with config:
F.
======================================================================
FAIL: testListDevices (__main__.SessionListDevicesTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/0cb601a163d4c4c6c065cdaa9629611b/execroot/tensorflow/bazel-out/local-opt/bin/tensorflow/python/session_list_devices_test.runfiles/org_tensorflow/tensorflow/python/client/session_list_devices_test.py", line 39, in testListDevices
    self.assertGreaterEqual(1, len(devices), devices)
AssertionError: [_DeviceAttributes(/job:localhost/replica:0/task:0/device:CPU:0, CPU, 42115744), _DeviceAttributes(/job:localhost/replica:0/task:0/device:XLA_EXEC:0, XLA_EXEC, 42116496), _DeviceAttributes(/job:localhost/replica:0/task:0/device:XLA_CPU:0, XLA_CPU, 42116608)]

======================================================================
FAIL: testListDevicesClusterSpecPropagation (__main__.SessionListDevicesTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/0cb601a163d4c4c6c065cdaa9629611b/execroot/tensorflow/bazel-out/local-opt/bin/tensorflow/python/session_list_devices_test.runfiles/org_tensorflow/tensorflow/python/client/session_list_devices_test.py", line 66, in testListDevicesClusterSpecPropagation
    self.assertGreaterEqual(2, len(devices), devices)
AssertionError: [_DeviceAttributes(/job:worker/replica:0/task:0/device:CPU:0, CPU, 42238272), _DeviceAttributes(/job:worker/replica:0/task:0/device:XLA_EXEC:0, XLA_EXEC, 42238864), _DeviceAttributes(/job:worker/replica:0/task:0/device:XLA_CPU:0, XLA_CPU, 42238896), _DeviceAttributes(/job:worker/replica:0/task:1/device:CPU:0, CPU, 42238928), _DeviceAttributes(/job:worker/replica:0/task:1/device:XLA_EXEC:0, XLA_EXEC, 42238960), _DeviceAttributes(/job:worker/replica:0/task:1/device:XLA_CPU:0, XLA_CPU, 42238992)]

======================================================================
FAIL: testListDevicesGrpcSession (__main__.SessionListDevicesTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/0cb601a163d4c4c6c065cdaa9629611b/execroot/tensorflow/bazel-out/local-opt/bin/tensorflow/python/session_list_devices_test.runfiles/org_tensorflow/tensorflow/python/client/session_list_devices_test.py", line 47, in testListDevicesGrpcSession
    self.assertGreaterEqual(1, len(devices), devices)
AssertionError: [_DeviceAttributes(/job:local/replica:0/task:0/device:CPU:0, CPU, 42226672), _DeviceAttributes(/job:local/replica:0/task:0/device:XLA_EXEC:0, XLA_EXEC, 41891296), _DeviceAttributes(/job:local/replica:0/task:0/device:XLA_CPU:0, XLA_CPU, 41891328)]

======================================================================
FAIL: testListDevices (__main__.SessionListDevicesWithCApiTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/0cb601a163d4c4c6c065cdaa9629611b/execroot/tensorflow/bazel-out/local-opt/bin/tensorflow/python/session_list_devices_test.runfiles/org_tensorflow/tensorflow/python/client/session_list_devices_test.py", line 39, in testListDevices
    self.assertGreaterEqual(1, len(devices), devices)
AssertionError: [_DeviceAttributes(/job:localhost/replica:0/task:0/device:CPU:0, CPU, 42268048), _DeviceAttributes(/job:localhost/replica:0/task:0/device:XLA_EXEC:0, XLA_EXEC, 42268800), _DeviceAttributes(/job:localhost/replica:0/task:0/device:XLA_CPU:0, XLA_CPU, 42268912)]

======================================================================
FAIL: testListDevicesClusterSpecPropagation (__main__.SessionListDevicesWithCApiTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/0cb601a163d4c4c6c065cdaa9629611b/execroot/tensorflow/bazel-out/local-opt/bin/tensorflow/python/session_list_devices_test.runfiles/org_tensorflow/tensorflow/python/client/session_list_devices_test.py", line 66, in testListDevicesClusterSpecPropagation
    self.assertGreaterEqual(2, len(devices), devices)
AssertionError: [_DeviceAttributes(/job:worker/replica:0/task:0/device:CPU:0, CPU, 42313280), _DeviceAttributes(/job:worker/replica:0/task:0/device:XLA_EXEC:0, XLA_EXEC, 42313872), _DeviceAttributes(/job:worker/replica:0/task:0/device:XLA_CPU:0, XLA_CPU, 42313904), _DeviceAttributes(/job:worker/replica:0/task:1/device:CPU:0, CPU, 42313936), _DeviceAttributes(/job:worker/replica:0/task:1/device:XLA_EXEC:0, XLA_EXEC, 42313968), _DeviceAttributes(/job:worker/replica:0/task:1/device:XLA_CPU:0, XLA_CPU, 42314000)]

======================================================================
FAIL: testListDevicesGrpcSession (__main__.SessionListDevicesWithCApiTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/0cb601a163d4c4c6c065cdaa9629611b/execroot/tensorflow/bazel-out/local-opt/bin/tensorflow/python/session_list_devices_test.runfiles/org_tensorflow/tensorflow/python/client/session_list_devices_test.py", line 47, in testListDevicesGrpcSession
    self.assertGreaterEqual(1, len(devices), devices)
AssertionError: [_DeviceAttributes(/job:local/replica:0/task:0/device:CPU:0, CPU, 42260656), _DeviceAttributes(/job:local/replica:0/task:0/device:XLA_EXEC:0, XLA_EXEC, 42260688), _DeviceAttributes(/job:local/replica:0/task:0/device:XLA_CPU:0, XLA_CPU, 42331824)]

----------------------------------------------------------------------
Ran 8 tests in 1.857s

FAILED (failures=6)
swig/python detected a memory leak of type 'int64_t *', no destructor found.
swig/python detected a memory leak of type 'int64_t *', no destructor found.
swig/python detected a memory leak of type 'int64_t *', no destructor found.
swig/python detected a memory leak of type 'int64_t *', no destructor found.
swig/python detected a memory leak of type 'int64_t *', no destructor found.
swig/python detected a memory leak of type 'int64_t *', no destructor found.
swig/python detected a memory leak of type 'int64_t *', no destructor found.
swig/python detected a memory leak of type 'int64_t *', no destructor found.
swig/python detected a memory leak of type 'int64_t *', no destructor found.
swig/python detected a memory leak of type 'int64_t *', no destructor found.
swig/python detected a memory leak of type 'int64_t *', no destructor found.
swig/python detected a memory leak of type 'int64_t *', no destructor found.
swig/python detected a memory leak of type 'int64_t *', no destructor found.
swig/python detected a memory leak of type 'int64_t *', no destructor found.
swig/python detected a memory leak of type 'int64_t *', no destructor found.
swig/python detected a memory leak of type 'int64_t *', no destructor found.
swig/python detected a memory leak of type 'int64_t *', no destructor found.
swig/python detected a memory leak of type 'int64_t *', no destructor found.
swig/python detected a memory leak of type 'int64_t *', no destructor found.
swig/python detected a memory leak of type 'int64_t *', no destructor found.
swig/python detected a memory leak of type 'int64_t *', no destructor found.
swig/python detected a memory leak of type 'int64_t *', no destructor found.
swig/python detected a memory leak of type 'int64_t *', no destructor found.
swig/python detected a memory leak of type 'int64_t *', no destructor found.

```

**Comment by tatatodd** [comment]
@sandipmgiri Thanks for filing the issue!

It looks like the test is only expecting to see the CPU device, but it's getting confused by the extra XLA_EXEC and XLA_CPU devices.  I'm assuming you built with XLA support enabled?

In the short-term it's safe to just ignore these failures, since I believe it's a problem with the tests themselves, not with the system.

FYI @saeta who added these tests.  Perhaps the `assertGreaterEqual` should have been `assertLessEqual`?

**Comment by sandipmgiri** [comment]
Hi @saeta , Please provide your comments on this.Thanks!
