### ISSUE TITLE
After quantized ssd_mobilenet_v1_coco model, loaded error on Android 

### ISSUE THREAD

**Issue by offbye** [tensorflow/tensorflow#14777]
### System information
- **OS Platform and Distribution** : Linux Ubuntu 14.04.5 LTS
- **TensorFlow installed from** : binary
- **TensorFlow version** : 1.2.1
- **Python version**: 2.7
- **Bazel version**: 0.70
- **GCC/Compiler version (if compiling from source)**: 4.8.4 
- **CUDA/cuDNN version**: 8.0
- **GPU model and memory**: Tesla P100-PCIE 
- **Exact command to reproduce**:

### Describe the problem
Load a quantized ssd_mobilenet_v1 model on Android meet error
Caused by: java.io.IOException: Not a valid TensorFlow Graph serialization: NodeDef mentions attr 'T' not in Op<name=Where; signature=input:bool -> index:int64>; 

I quantize the ssd_mobilenet_v1 model o ubuntu 14,  using the below command
```
bazel-bin/tensorflow/tools/graph_transforms/transform_graph 
--in_graph=/data5/zxt/coco_log/export/frozen_inference_graph.pb  
--out_graph=/home/zxt/git/ssd_optimized.pb --inputs='image_tensor'
 --outputs='detection_boxes,detection_scores,num_detections,detection_classes' --transforms='
  add_default_attributes
  strip_unused_nodes(type=float, shape="-1,-1,-1,3")
  remove_nodes(op=Identity, op=CheckNumerics)
  fold_batch_norms
  fold_old_batch_norms
  quantize_weights
  strip_unused_nodes
  sort_by_execution_order'
```
I also have tried some other parameters，but all failed with same issue.
the  frozen_inference_graph.pb   is ok on Android, but the quantized pb is can NOT load.
When run the quantized pb on android phone, met errors
```
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:799)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:689)
    Caused by: java.io.IOException: Not a valid TensorFlow Graph serialization: NodeDef mentions attr 'T' not in Op<name=Where; signature=input:bool -> index:int64>; 
NodeDef: Postprocessor/BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/FilterGreaterThan/Where = Where[T=DT_BOOL](Postprocessor/BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/FilterGreaterThan/Greater). 
(Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
           at org.tensorflow.contrib.android.TensorFlowInferenceInterface.loadGraph(TensorFlowInferenceInterface.java:535)
 
```

**Comment by juandes** [comment]
Hi @offbye, I believe you comment on an issue of mine because I am also experiencing the same error. Were you able to find a solution or a workaround? Thanks.

**Comment by tatatodd** [comment]
@offbye As I mentioned in the other issue you filed, I'm suspecting that there's a mismatch between the version of the code that is running the graph (the android demo?), vs. the code that built the GraphDef.

Can you provide details on exactly how you're running your models on Android?

**Comment by offbye** [comment]
I use the lastest code in master , and I quantized the    `assets/ssd_mobilenet_v1_android_export.pb`， then I change the `tensorflow\examples\android\src\org\tensorflow\demo\DetectorActivity.java` ,use the quantized ssd_mobilenet_v1_android_quantized.pb， and  I met errors:

```
12-19 16:39:49.231 23831-23855/? E/TensorFlowInferenceInterface: Failed to run TensorFlow inference with inputs:[image_tensor], outputs:[detection_boxes, detection_scores, detection_classes, num_detections]
12-19 16:39:49.231 23831-23855/? E/AndroidRuntime: FATAL EXCEPTION: inference
                                                   Process: org.tensorflow.demo, PID: 23831
                                                   java.lang.IllegalArgumentException: The node 'Postprocessor/BatchMultiClassNonMaxSuppression/map/while/TensorArrayWrite/TensorArrayWriteV3' has inputs from different frames. The input 'Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/cond/Merge' is in frame ''. The input 'Postprocessor/BatchMultiClassNonMaxSuppression/map/while/TensorArrayWrite/TensorArrayWriteV3/Enter' is in frame 'Postprocessor/BatchMultiClassNonMaxSuppression/map/while/while_context'.
                                                       at org.tensorflow.Session.run(Native Method)
                                                       at org.tensorflow.Session.access$100(Session.java:48)
                                                       at org.tensorflow.Session$Runner.runHelper(Session.java:298)
                                                       at org.tensorflow.Session$Runner.run(Session.java:248)
                                                       at org.tensorflow.contrib.android.TensorFlowInferenceInterface.run(TensorFlowInferenceInterface.java:218)
                                                       at org.tensorflow.demo.TensorFlowObjectDetectionAPIModel.recognizeImage(TensorFlowObjectDetectionAPIModel.java:158)
                                                       at org.tensorflow.demo.DetectorActivity$3.run(DetectorActivity.java:289)
                                                       at android.os.Handler.handleCallback(Handler.java:743)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:150)
                                                       at android.os.HandlerThread.run(HandlerThread.java:61)
```

Before quantized the ssd_mobilenet_v1_android_export.pb,  the android Detect Demo is ok on my phone.

**Comment by offbye** [comment]
I have confirmed that if I only use quantize_weights , the pb model can run on Android, but can not detect anything. 
But I can use rounded_weights to transform the pb model , and the final apk size compressed about 17M !

**Comment by offbye** [comment]
I have confirmed that if I only use quantize_weights , the pb model can run on Android, but can not detect anything.
But I can use rounded_weights to transform the pb model , and the final apk size compressed about 17M !

So I think the issue can be closed!

**Comment by jeffxtang** [comment]
@offbye is the complete command you used with rounded_weights the following?
```
bazel-bin/tensorflow/tools/graph_transforms/transform_graph 
--in_graph=/data5/zxt/coco_log/export/frozen_inference_graph.pb  
--out_graph=/home/zxt/git/ssd_optimized.pb --inputs='image_tensor'
 --outputs='detection_boxes,detection_scores,num_detections,detection_classes' --transforms='
  add_default_attributes
  strip_unused_nodes(type=float, shape="-1,-1,-1,3")
  remove_nodes(op=Identity, op=CheckNumerics)
  fold_batch_norms
  fold_old_batch_norms
  round_weights
  strip_unused_nodes
  sort_by_execution_order'
```
I used  the transforms values above on ssd_mobilenet_v1_coco_2017_11_17's frozen_inference_graph.pb (size 29112121) but the transformed graph's size is still about 25MB.

Thanks!
