### ISSUE TITLE
Batch Normalization layer is unusable

### ISSUE THREAD

**Issue by nikonikolov** [tensorflow/tensorflow#14809]
Despite the numerous submitted issues, `tf.layers.batch_normalization` still feels completely unusable. The major problems are:

1. It does not allow for input tensors with varying shapes. It is complete nonsense to have a fixed batch size. It should be allowed for the batch dimension to be vary.

2. One needs to manually update the running mean and variance. This is very uncomfortable and a very common pitfall for many beginners, while it would take just a couple of lines to do the update internally based on the value of the `training` parameter.

I have recently seen too many custom implementations of a batch normalization layer because of the above problems and it will definitely be very useful if these problems are fixed ASAP.

I am using `tensorflow-gpu`, version `1.4`

**Comment by ppwwyyxx** [comment]
1. It does allow varying shapes. `tf.layers.batch_normalization(x)` only require x to have known channel.

2. Doing the update internally can be significantly slower in certain cases, due to the dependency it introduced. So I think the current API is a reasonable choice. Though I don't mind seeing a new API which does the update internally so it's more friendly to beginners.

**Comment by nikonikolov** [comment]
Thanks for the quick reply!

1. It does not seem to work for me. 
```
>>> data = tf.placeholder(tf.float32, shape=[None, 2, 3])
>>> norm = tf.layers.batch_normalization(data, axis=0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.6/site-packages/tensorflow/python/layers/normalization.py", line 586, in batch_normalization
    return layer.apply(inputs, training=training)
  File "/usr/lib64/python3.6/site-packages/tensorflow/python/layers/base.py", line 671, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "/usr/lib64/python3.6/site-packages/tensorflow/python/layers/base.py", line 559, in __call__
    self.build(input_shapes[0])
  File "/usr/lib64/python3.6/site-packages/tensorflow/python/layers/normalization.py", line 179, in build
    input_shape)
ValueError: ('Input has undefined `axis` dimension. Input shape: ', TensorShape([Dimension(None), Dimension(2), Dimension(3)]))
```
In the source code, it seems that the batch dimension must be fixed: https://github.com/tensorflow/tensorflow/blob/b5df90f91cde6eb12af9cbe818bd2cf4a9bcc687/tensorflow/python/layers/normalization.py#L176-L179 Am I doing something wrong?


2. Out of curiosity, is it slower because computing the input for the next layer takes more time when you do the update internally? In any case, there is often a trade-off between code readability and performance, so in my opinion it would definitely be much better if there is some parameter that controls if the update is done internally or not, rather than leaving no choice for the programmer. It would also be a good, if possible, to provide some approximate metric of the speed up, when the update is not done internally, so the programmer can choose for himself.

**Comment by facaiy** [comment]
Axis is the last dimension by default, so it indeed is the channel dimension as mentioned by @ppwwyyxx.

**Comment by ppwwyyxx** [comment]
1. `axis` does not mean batch dimension
2. Theoretically, doing updates in the layer means the layer might get slower, because it waits for the updates to finish.
Half year ago I switched from doing the updates internally to externally in tensorpack, to match the performance of official benchmark ([see the note](https://github.com/ppwwyyxx/tensorpack/issues/254#issuecomment-299681482)). I remembered there was a significant difference at that time. But just now I ran a ResNet50 test, it seems like the performance difference becomes negligible today. Maybe now it makes sense to add the option to improve usability.

**Comment by nikonikolov** [comment]
1. Sorry, I got confused and it took me some time to clear it. I feel that the documentation is not clear  enough on the meaning of axis. A lot of the confusion comes from the way that `dense` and `conv` layers are handled. Specifically, in `conv` layers, the moments are taken over all dimensions except for the channel dimension, while in `dense` layers the moments are taken over the batch dimension only (since there are only 2 dimensions). When one reads the code in detail, this becomes clear, but in my opinion it is very unclear the way it is currently written in the documentation.

I saw that on the master branch it is now allowed to give a list for the `axis` argument and the documentation there is much more clear on the issue. For complete clarity, I think that examples for both `conv` and `dense` layers would save a lot of time for beginners. Meanwhile it would be a very good idea to update the documentation for the 1.4 API so that it is at least as clear as the one on the master branch.

2. Since the performance difference is negligible, it seems absolutely pointless to have to run the update ops manually. The default behavior must definitely be that the ops are run internally, and possibly a parameter to control this can be included (if there are still ppl interested in running the ops manually).

**Comment by facaiy** [comment]
Hi, @nikonikolov. I agree that readable documents can save user a lot of time. And if you'd like, welcome to help revise documents. Thanks.

Could we update the op internally? I believe @fchollet can give us more useful information.

**Comment by cdbfoster** [comment]
I just got bitten by this.  The way that it's mentioned in the doc is very easy to overlook, considering that updating these manually is critical for use, and the note font is smaller than any other on the page...

It would be great to have these updated internally by default, providing an option to update manually if desired.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by ppwwyyxx** [comment]
I'm not sure why this was closed without answers. An option to update the moving averages internally is a totally valid feature request. 

Besides the ease of use, #14699 has mentioned another valid reason for this feature, i.e. to use within `tf.cond`, the update ops should be evaluated depending on the condition.

`tf.contrib.layers.batch_norm` already supports this feature, btw.

**Comment by facaiy** [comment]
@fchollet Could you take a look?

**Comment by BiaoLiu2017** [comment]
axis: An int, the axis that should be normalized (typically the features axis). For instance, after a Convolution2D layer with data_format="channels_first", set axis=1 in BatchNormalization.

so, you should choose the exact axis that you want to normalize.

Such as:
Z = [100, None]
B = tf.layers.batch_normalization(Z, **axis = 0**, training = is_training)

if you write "axis = -1", it will get wrong bug report.
