### ISSUE TITLE
Object detection works on Linux but not Mac

### ISSUE THREAD

**Issue by teaglin** [tensorflow/tensorflow#14884]
------------------------

### System information
- **OS Platform and Distribution **: Linux 16.04 and Mac OS 10.12.6
- **TensorFlow installed from (source or binary)**: Mac – Binary, Linux – Source
- **TensorFlow version (use command below)**: Mac – ('v1.3.0-rc2-20-g0787eee', '1.3.0')
Linux – ('v1.3.0-rc1-4003-g1f582aa', '1.4.0-rc0')
- **Python version**: Mac – 2.7.14, Linux – 2.7.12
- **Bazel version (if compiling from source)**: Linux – 0.7.0
- **GCC/Compiler version (if compiling from source)**: Linux GCC 5.4.0
- **CUDA/cuDNN version**: Linux CUDA 9, cuDNN 7
- **GPU model and memory**: Linux TitanXp

### Describe the problem

I trained a model using the tensor flow object detection api with faster_rcnn_resnet101. I then exported the model using the provided export_inference_graph.py. The model works on Linux, but does not work on Mac. Both platforms are using tensor flow 1.3.0. I've provided the crash log.

### Source code / logs
2017-11-25 20:39:12.847344: E tensorflow/core/common_runtime/executor.cc:644] Executor failed to create kernel. Invalid argument: NodeDef mentions attr 'T' not in Op<name=Where; signature=input:bool -> index:int64>; NodeDef: ClipToWindow/Where = Where[T=DT_BOOL, _device="/job:localhost/replica:0/task:0/cpu:0"](ClipToWindow/Greater). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
	 [[Node: ClipToWindow/Where = Where[T=DT_BOOL, _device="/job:localhost/replica:0/task:0/cpu:0"](ClipToWindow/Greater)]]
Traceback (most recent call last):
  File "/Documents/detect.py", line 13, in <module>
    model.detect(image)
  File "/Documents/object_detector.py", line 71, in detect
    feed_dict={self.image_tensor: image_np_expanded})
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: NodeDef mentions attr 'T' not in Op<name=Where; signature=input:bool -> index:int64>; NodeDef: ClipToWindow/Where = Where[T=DT_BOOL, _device="/job:localhost/replica:0/task:0/cpu:0"](ClipToWindow/Greater). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
	 [[Node: ClipToWindow/Where = Where[T=DT_BOOL, _device="/job:localhost/replica:0/task:0/cpu:0"](ClipToWindow/Greater)]]

Caused by op u'ClipToWindow/Where', defined at:
  File "/Documents/detect.py", line 7, in <module>
    limbs = det.object_detector("/Documents/graph.pbtxt","/Documents/graph.pb", 2)
  File "/Documents/object_detector.py", line 49, in __init__
    tf.import_graph_def(od_graph_def, name='')
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/importer.py", line 313, in import_graph_def
    op_def=op_def)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): NodeDef mentions attr 'T' not in Op<name=Where; signature=input:bool -> index:int64>; NodeDef: ClipToWindow/Where = Where[T=DT_BOOL, _device="/job:localhost/replica:0/task:0/cpu:0"](ClipToWindow/Greater). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
	 [[Node: ClipToWindow/Where = Where[T=DT_BOOL, _device="/job:localhost/replica:0/task:0/cpu:0"](ClipToWindow/Greater)]]

**Comment by ebrevdo** [comment]
The problem seems to be with the new type T.  This was introduced in TF 1.4; you may want to upgrade your mac os version to using TF 1.4 as well.

As a long-term solution, we probably also want to add forwards compatibility-type default attr stripping in `import_scoped_meta_graph`.  @josh11b for comments.

**Comment by teaglin** [comment]
You are right, I exported the model using export_inference_graph.py on Mac OS with CPU and the frozen graph now works. Thanks for the help!

**Comment by juandes** [comment]
Hi @teaglin. I'm having a somehow similar issue. Could you explain how you specify you want to export the model using export_inference_graph.py but with CPU. Thanks.

**Comment by teaglin** [comment]
@juandes I used the CPU only version of tensorflow for Mac. So it automatically defaults to that. I didn’t specify anything in the export inference graph. 

Some what related to this I can’t get either of these models to work on iOS. They complain about a similar issue.

**Comment by juandes** [comment]
@teaglin thanks for the quick reply.

**Comment by mghildiy** [comment]
Hi,

I trained ssd mobilenet model. When I use the trained model fo rinferecne on ain image, I get error as:

ValueError: cannot reshape array of size X into shape (a,b,c)
X,a,b,c are different values for different test images.

SO link is:
https://stackoverflow.com/questions/47699181/tensorflow-object-detectionvalueerror-cannot-reshape-array

Please help me here.

**Comment by mghildiy** [comment]
Issue is solved. My image has 4 channels, while program expects image with 3 channel.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assigneee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by ChaosPredictor** [comment]
Have the same issue on Ubuntu.

**I have one setup that working and the second one that doesn't both are Ubuntu 16.04.**

> 2018-01-17 13:34:33.500813: E tensorflow/core/common_runtime/executor.cc:643] Executor failed to create kernel. Invalid argument: NodeDef mentions attr 'dilations' not in Op<name=Conv2D; signature=input:T, filter:T -> output:T; attr=T:type,allowed=[DT_HALF, DT_FLOAT]; attr=strides:list(int); attr=use_cudnn_on_gpu:bool,default=true; attr=padding:string,allowed=["SAME", "VALID"]; attr=data_format:string,default="NHWC",allowed=["NHWC", "NCHW"]>; NodeDef: conv/Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], padding="VALID", strides=[1, 2, 2, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](Mul, conv/conv2d_params). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
> 	 [[Node: conv/Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], padding="VALID", strides=[1, 2, 2, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](Mul, conv/conv2d_params)]]
> Traceback (most recent call last):
>   File "label_image.py", line 246, in <module>
>     tf.app.run(main=main, argv=sys.argv[:1]+unparsed)
>   File "/home/master/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
>     _sys.exit(main(_sys.argv[:1] + flags_passthrough))
>   File "label_image.py", line 224, in main
>     FLAGS.num_top_predictions)
>   File "label_image.py", line 188, in run_on_images
>     num_top_predictions)
>   File "label_image.py", line 160, in predict_image
>     temp = run_graph_label_only(image, labels, input_layer_name, output_layer_name, num_top_predictions)
>   File "label_image.py", line 133, in run_graph_label_only
>     predictions, = sess.run(softmax_tensor, {input_layer_name: image_data})
>   File "/home/master/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 889, in run
>     run_metadata_ptr)
>   File "/home/master/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1120, in _run
>     feed_dict_tensor, options, run_metadata)
>   File "/home/master/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run
>     options, run_metadata)
>   File "/home/master/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1336, in _do_call
>     raise type(e)(node_def, op, message)
> tensorflow.python.framework.errors_impl.InvalidArgumentError: NodeDef mentions attr 'dilations' not in Op<name=Conv2D; signature=input:T, filter:T -> output:T; attr=T:type,allowed=[DT_HALF, DT_FLOAT]; attr=strides:list(int); attr=use_cudnn_on_gpu:bool,default=true; attr=padding:string,allowed=["SAME", "VALID"]; attr=data_format:string,default="NHWC",allowed=["NHWC", "NCHW"]>; NodeDef: conv/Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], padding="VALID", strides=[1, 2, 2, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](Mul, conv/conv2d_params). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
> 	 [[Node: conv/Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], padding="VALID", strides=[1, 2, 2, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](Mul, conv/conv2d_params)]]
> 
> Caused by op u'conv/Conv2D', defined at:
>   File "label_image.py", line 246, in <module>
>     tf.app.run(main=main, argv=sys.argv[:1]+unparsed)
>   File "/home/master/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
>     _sys.exit(main(_sys.argv[:1] + flags_passthrough))
>   File "label_image.py", line 221, in main
>     load_graph(FLAGS.graph)
>   File "label_image.py", line 99, in load_graph
>     tf.import_graph_def(graph_def, name='')
>   File "/home/master/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/importer.py", line 313, in import_graph_def
>     op_def=op_def)
>   File "/home/master/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
>     op_def=op_def)
>   File "/home/master/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
>     self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access
> 
> InvalidArgumentError (see above for traceback): NodeDef mentions attr 'dilations' not in Op<name=Conv2D; signature=input:T, filter:T -> output:T; attr=T:type,allowed=[DT_HALF, DT_FLOAT]; attr=strides:list(int); attr=use_cudnn_on_gpu:bool,default=true; attr=padding:string,allowed=["SAME", "VALID"]; attr=data_format:string,default="NHWC",allowed=["NHWC", "NCHW"]>; NodeDef: conv/Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], padding="VALID", strides=[1, 2, 2, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](Mul, conv/conv2d_params). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
> 	 [[Node: conv/Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], padding="VALID", strides=[1, 2, 2, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](Mul, conv/conv2d_params)]]

I have tries to update the tensorflow but getting the same error. The Retrain part working without problem. only when I'm trying with use the retrained model. I'm thinking that maybe it some how related to Conda or Cuda

**Comment by jayshah19949596** [comment]
I am facing the same error.... Using tensorflow 1.3 on ubuntu with cuda 8

**Comment by xiaoluojun** [comment]
same error!

**Comment by josh11b** [comment]
You can now use the "strip_default_attrs=True" option when exporting your model to increase the chances that it will work with an older version of TensorFlow. However this is only likely to really work when the exporting version of TensorFlow is not much newer than the importing version, so updating TensorFlow to a more recent version may also be necessary.

**Comment by eraoul** [comment]
Ran into the same thing -- glad to find this thread! GPU training, running on CPU. Will try fixes above.  May I suggest exposing a note about this somewhere in the TF model export docs?

**Comment by xiaoluojun** [comment]
@juandes Thanks! I'm updating Tensorflow to recent version==1.6.0. Iit's working

**Comment by leungs** [comment]
@josh11b But, which step for ""strip_default_attrs=True"? freeze_graph? or optimize_graph? or quantize_graph?

**Comment by peci1** [comment]
For anyone who'd like to take models from newer TF and transform them into models compatible with TF 1.3, here's my piece of code:

```
def fix_graph_def(graph_def):
        # fix nodes
        for node in graph_def.node:
            if node.op == 'RefSwitch':
                node.op = 'Switch'
                for index in range(len(node.input)):
                    if 'moving_' in node.input[index]:
                        node.input[index] = node.input[index] + '/read'
            elif node.op == 'AssignSub':
                node.op = 'Sub'
                if 'use_locking' in node.attr:
                    del node.attr['use_locking']
            if "dilations" in node.attr:
                del node.attr["dilations"]
            if "index_type" in node.attr:
                del node.attr["index_type"]
```

It's probably not a complete list of all new attributes that have to be deleted, but in a few iterations you can make it strip everything you need.

**Comment by enningxie** [comment]
@peci1 hello, I meet sameproblem with TF 1.3. Does the code you mentioned work?

**Comment by peci1** [comment]
@enningxie For my networks, it does. It depends on which ops you are using.

**Comment by enningxie** [comment]
@peci1  the `del node.attr["dilations"]` doesn't work for me.

**Comment by peci1** [comment]
@enningxie can you be more verbose?

**Comment by enningxie** [comment]
@peci1 I had retrained a model using TF1.7 HUB. I want to deploy it with TF 1.3. But meet errors above, so I would try your func to transform them into models compatible with TF 1.3, while it do nothing. By the       way, it couldn't del the `node.attr["dilations"]`.

**Comment by peci1** [comment]
Paste the error here.

**Comment by enningxie** [comment]
2018-06-01 10:03:31.606643: E tensorflow/core/common_runtime/executor.cc:644] Executor failed to create kernel. Invalid argument: NodeDef mentions attr 'dilations' not in Op<name=Conv2D; signature=input:T, filter:T -> output:T; attr=T:type,allowed=[DT_HALF, DT_FLOAT]; attr=strides:list(int); attr=use_cudnn_on_gpu:bool,default=true; attr=padding:string,allowed=["SAME", "VALID"]; attr=data_format:string,default="NHWC",allowed=["NHWC", "NCHW"]>; NodeDef: module_apply_default/InceptionV3/InceptionV3/Conv2d_1a_3x3/Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], padding="VALID", strides=[1, 2, 2, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/cpu:0"](module_apply_default/hub_input/Sub, module_apply_default/InceptionV3/InceptionV3/Conv2d_1a_3x3/Conv2D/ReadVariableOp). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
	 [[Node: module_apply_default/InceptionV3/InceptionV3/Conv2d_1a_3x3/Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], padding="VALID", strides=[1, 2, 2, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/cpu:0"](module_apply_default/hub_input/Sub, module_apply_default/InceptionV3/InceptionV3/Conv2d_1a_3x3/Conv2D/ReadVariableOp)]]
Traceback (most recent call last):
  File "/home/enningxie/anaconda3/envs/tf13/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1327, in _do_call
    return fn(*args)
  File "/home/enningxie/anaconda3/envs/tf13/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1306, in _run_fn
    status, run_metadata)
  File "/home/enningxie/anaconda3/envs/tf13/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/home/enningxie/anaconda3/envs/tf13/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: NodeDef mentions attr 'dilations' not in Op<name=Conv2D; signature=input:T, filter:T -> output:T; attr=T:type,allowed=[DT_HALF, DT_FLOAT]; attr=strides:list(int); attr=use_cudnn_on_gpu:bool,default=true; attr=padding:string,allowed=["SAME", "VALID"]; attr=data_format:string,default="NHWC",allowed=["NHWC", "NCHW"]>; NodeDef: module_apply_default/InceptionV3/InceptionV3/Conv2d_1a_3x3/Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], padding="VALID", strides=[1, 2, 2, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/cpu:0"](module_apply_default/hub_input/Sub, module_apply_default/InceptionV3/InceptionV3/Conv2d_1a_3x3/Conv2D/ReadVariableOp). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
	 [[Node: module_apply_default/InceptionV3/InceptionV3/Conv2d_1a_3x3/Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], padding="VALID", strides=[1, 2, 2, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/cpu:0"](module_apply_default/hub_input/Sub, module_apply_default/InceptionV3/InceptionV3/Conv2d_1a_3x3/Conv2D/ReadVariableOp)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/enningxie/Codes_03/example_code/label_image_13.py", line 230, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/home/enningxie/anaconda3/envs/tf13/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/enningxie/Codes_03/example_code/label_image_13.py", line 206, in main
    predictions, = sess.run(softmax_tensor, {FLAGS.input_layer: t})
  File "/home/enningxie/anaconda3/envs/tf13/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/home/enningxie/anaconda3/envs/tf13/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/enningxie/anaconda3/envs/tf13/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    options, run_metadata)
  File "/home/enningxie/anaconda3/envs/tf13/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: NodeDef mentions attr 'dilations' not in Op<name=Conv2D; signature=input:T, filter:T -> output:T; attr=T:type,allowed=[DT_HALF, DT_FLOAT]; attr=strides:list(int); attr=use_cudnn_on_gpu:bool,default=true; attr=padding:string,allowed=["SAME", "VALID"]; attr=data_format:string,default="NHWC",allowed=["NHWC", "NCHW"]>; NodeDef: module_apply_default/InceptionV3/InceptionV3/Conv2d_1a_3x3/Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], padding="VALID", strides=[1, 2, 2, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/cpu:0"](module_apply_default/hub_input/Sub, module_apply_default/InceptionV3/InceptionV3/Conv2d_1a_3x3/Conv2D/ReadVariableOp). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
	 [[Node: module_apply_default/InceptionV3/InceptionV3/Conv2d_1a_3x3/Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], padding="VALID", strides=[1, 2, 2, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/cpu:0"](module_apply_default/hub_input/Sub, module_apply_default/InceptionV3/InceptionV3/Conv2d_1a_3x3/Conv2D/ReadVariableOp)]]

Caused by op 'module_apply_default/InceptionV3/InceptionV3/Conv2d_1a_3x3/Conv2D', defined at:
  File "/home/enningxie/Codes_03/example_code/label_image_13.py", line 230, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/home/enningxie/anaconda3/envs/tf13/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/enningxie/Codes_03/example_code/label_image_13.py", line 185, in main
    load_graph(FLAGS.graph)
  File "/home/enningxie/Codes_03/example_code/label_image_13.py", line 114, in load_graph
    tf.import_graph_def(graph_def, name='')
  File "/home/enningxie/anaconda3/envs/tf13/lib/python3.5/site-packages/tensorflow/python/framework/importer.py", line 313, in import_graph_def
    op_def=op_def)
  File "/home/enningxie/anaconda3/envs/tf13/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/enningxie/anaconda3/envs/tf13/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): NodeDef mentions attr 'dilations' not in Op<name=Conv2D; signature=input:T, filter:T -> output:T; attr=T:type,allowed=[DT_HALF, DT_FLOAT]; attr=strides:list(int); attr=use_cudnn_on_gpu:bool,default=true; attr=padding:string,allowed=["SAME", "VALID"]; attr=data_format:string,default="NHWC",allowed=["NHWC", "NCHW"]>; NodeDef: module_apply_default/InceptionV3/InceptionV3/Conv2d_1a_3x3/Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], padding="VALID", strides=[1, 2, 2, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/cpu:0"](module_apply_default/hub_input/Sub, module_apply_default/InceptionV3/InceptionV3/Conv2d_1a_3x3/Conv2D/ReadVariableOp). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
	 [[Node: module_apply_default/InceptionV3/InceptionV3/Conv2d_1a_3x3/Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], padding="VALID", strides=[1, 2, 2, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/cpu:0"](module_apply_default/hub_input/Sub, module_apply_default/InceptionV3/InceptionV3/Conv2d_1a_3x3/Conv2D/ReadVariableOp)]]

**Comment by peci1** [comment]
I forgot to mention the code I posted (probably) only works for .pb models with variables converted to constants. I've created a gist where you'll find how I build, save and execute the models: https://gist.github.com/peci1/80cf0dd79986db83b4c99d0714ddf2ff .

If the model you have is in a different format, first load it in newer TF, save it with save_pb_model.py from the gist, and then the fix_graph_def should work. You can even call fix_graph_def before saving the model, and then you wouldn't need to call it during execution.

**Comment by enningxie** [comment]
@peci1 Thanks!
