### ISSUE TITLE
avg_pool ignores channel stride dimension, but max_pool does not

### ISSUE THREAD

**Issue by themightyoarfish** [tensorflow/tensorflow#14886]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary (conda-tensorflow-gpu)
- **TensorFlow version (use command below)**: `b'unknown' 1.3.0`
- **Python version**: 3.6
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: 9/7
- **GPU model and memory**: GeForce GTX 1050 Ti
- **Exact command to reproduce**:
```
import tensorflow as tf

x = tf.get_variable('x', shape=(100, 32, 32, 64),
        initializer=tf.constant_initializer(5), dtype=tf.float32)
ksize = (1, 2, 2, 2)
strides = (1, 2, 2, 2)
max_pool = tf.nn.max_pool(x, ksize, strides, padding='SAME')
avg_pool = tf.nn.avg_pool(x, ksize, strides, padding='SAME')
print(max_pool.shape)
print(avg_pool.shape)
``` 

The unexpected output is
```
(100, 16, 16, 32)
(100, 16, 16, 64)
```

It says [here](https://github.com/Hvass-Labs/TensorFlow-Tutorials/issues/19#issuecomment-274249942) that first and last stride dimension must be 1, but apparently it isn't implemented like this. If this is a feature, there should be consistent behaviour and documentation.

Link to StackOverflow question: https://stackoverflow.com/q/47423172/2397253

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Bazel version

**Comment by themightyoarfish** [comment]
Not compiling from source, so setting to N/A.

**Comment by drpngx** [comment]
@martinwicke WDYT?

**Comment by martinwicke** [comment]
I see no documentation about this behavior. @themightyoarfish, where did you see "that first and last stride dimension must be 1"? I cannot find anything like that. 

So I think this is a bug. Fixing avgpool to respect the channels stride would be ideal. Or we can clearly document the expectations.

**Comment by themightyoarfish** [comment]
i forgot to add the link to my issue; it says here (https://github.com/Hvass-Labs/TensorFlow-Tutorials/issues/19) that first and last should be 1, but it's not official documentation.

On 18 December 2017 19:58:51 CET, Martin Wicke <notifications@github.com> wrote:
>I see no documentation about this behavior. @themightyoarfish, where
>did you see "that first and last stride dimension must be 1"? I cannot
>find anything like that. 
>
>So I think this is a bug. Fixing avgpool to respect the channels stride
>would be ideal. Or we can clearly document the expectations.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/tensorflow/tensorflow/issues/14886#issuecomment-352523480

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by martinwicke** [comment]
Yeah, IMO that's pointing out a bug. Let's fix this.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by facaiy** [comment]
Hi, I read the implementation of pool functions, and found that:
+ `MaxPool`: 
   - supports pooing across either depth (`DepthwiseMaxPool`) or width/height (`SpatialMaxPool`).
   - only supports NHWC for CPU.
+ `AvgPool`:
   - only supports pooling accross widht/height (`SpatialAvgPool`).
   - only supports NHWC for CPU.
For more details to see the script and logs at the bottom.

Unfortunately, all those checking are placed in c++ side, and the corresponding exception is raised at runtime.
I think we should check those conditions on python side to warn user as soon as possible.

### test script
```python
import tensorflow as tf

x = tf.fill((100, 32, 32, 64), 5.0)
ksize = (1, 2, 2, 2)
strides = (1, 2, 2, 2)
max_pool = tf.nn.max_pool(x, ksize, strides, padding='VALID')
avg_pool = tf.nn.avg_pool(x, ksize, strides, padding='VALID')
print(max_pool.shape)
print(avg_pool.shape)

with tf.Session() as sess:
    print(sess.run([max_pool, avg_pool]))
```

### logs
```python
~/Downloads ❯❯❯ python test.py
(100, 16, 16, 32)
(100, 16, 16, 64)
2018-01-17 13:17:48.363973: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
Traceback (most recent call last):
  File "/Users/facai/Library/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1323, in _do_call
    return fn(*args)
  File "/Users/facai/Library/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1302, in _run_fn
    status, run_metadata)
  File "/Users/facai/Library/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.UnimplementedError: MaxPooling supports exactly one of pooling across depth or pooling across width/height.
         [[Node: MaxPool = MaxPool[T=DT_FLOAT, data_format="NHWC", ksize=[1, 2, 2, 2], padding="VALID", strides=[1, 2, 2, 2], _device="/job:localhost/replica:0/task:0/device:CPU:0"](Fill)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 12, in <module>
    print(sess.run([max_pool, avg_pool]))
  File "/Users/facai/Library/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/Users/facai/Library/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/Users/facai/Library/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/Users/facai/Library/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnimplementedError: MaxPooling supports exactly one of pooling across depth or pooling across width/height.
         [[Node: MaxPool = MaxPool[T=DT_FLOAT, data_format="NHWC", ksize=[1, 2, 2, 2], padding="VALID", strides=[1, 2, 2, 2], _device="/job:localhost/replica:0/task:0/device:CPU:0"](Fill)]]

Caused by op 'MaxPool', defined at:
  File "test.py", line 6, in <module>
    max_pool = tf.nn.max_pool(x, ksize, strides, padding='VALID')
  File "/Users/facai/Library/anaconda3/lib/python3.5/site-packages/tensorflow/python/ops/nn_ops.py", line 1958, in max_pool
    name=name)
  File "/Users/facai/Library/anaconda3/lib/python3.5/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 2806, in _max_pool
    data_format=data_format, name=name)
  File "/Users/facai/Library/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/Users/facai/Library/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/Users/facai/Library/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

UnimplementedError (see above for traceback): MaxPooling supports exactly one of pooling across depth or pooling across width/height.
         [[Node: MaxPool = MaxPool[T=DT_FLOAT, data_format="NHWC", ksize=[1, 2, 2, 2], padding="VALID", strides=[1, 2, 2, 2], _device="/job:localhost/replica:0/task:0/device:CPU:0"](Fill)]]
```

**Comment by tensorflowbutler** [comment]
Please remove the assignee, as this issue is inviting external contributions. Otherwise, remove the `contributions welcome` label. Thank you.
