### ISSUE TITLE
[BUG] argparse (Argument Parser) is not working in nightly build

### ISSUE THREAD

**Issue by dantkz** [tensorflow/tensorflow#14913]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: pip install tf-nightly-gpu
- **TensorFlow version (use command below)**: v1.3.0-rc1-5211-gab0fcac 1.5.0-dev20171125
- **Python version**: 3.5.3
- **Bazel version (if compiling from source)**:n/a
- **GCC/Compiler version (if compiling from source)**:n/a
- **CUDA/cuDNN version**:9.0/7.0
- **GPU model and memory**:Titan Xp (12Gb)
- **Exact command to reproduce**: python test.py --myarg buzz

### Describe the problem
Nightly build is not handing correctly arguments passed to the script. The arguments are parsed correctly in the official 1.4 version.

```
(nightly) daniyar@sleepy-prism:~/tmp/argsparse$ python test.py --myarg buzz
buzz
FATAL Flags parsing error: Unknown command line flag 'myarg'
Pass --helpshort or --helpfull to see help on flags.
```

### Source code
```
import numpy as np
import argparse
import tensorflow as tf

parser = argparse.ArgumentParser(description='argsparse test for tensorflow nightly build')
parser.add_argument('--myarg', type=str, help='fizz or buzz', default='fizz')
args = parser.parse_args()

def main(argv):
    print(args.myarg)

if __name__ == '__main__':
    main([]) # test before tf.app.run()
    tf.app.run()
```

**Comment by mrry** [comment]
2652704b576adc16b4d735f651cea1024e88b72e changed the behavior of `tf.app.run()` to look at `sys.argv` and attempt to parse the flags using `absl.flags`.

As a workaround, you can pass an empty list of args to `tf.app.run()`:

```python
if __name__ == '__main__':
  tf.app.run(argv=[])
```

@martinwicke @yilei This seems like it might be a breaking change for existing users of `argparse`. Should we find a way to make this optional before it gets into a release?

**Comment by martinwicke** [comment]
Yeah, that is a problem. @yilei, we do need to maintain backwards compatibility for the behavior of `tf.app.*`. Maybe we need to extend the wrapper to be ugly. 

We should also deprecate `tf.app` and `tf.flags` altogether. They are included for historical reasons, TF has no business containing those modules.

**Comment by yilei** [comment]
Looks like `tf.app.run` needs to continue ignoring unknown flags (i.e. unfix #11195)

However, does the example code work before the change? `tf.app.run` will call `main` with positional arguments, but here the `main` function has no arguments and it's called manually.

Did you mean the following?

    def main(argv):
      parser = argparse.ArgumentParser(description='argsparse test for tensorflow nightly build')
      parser.add_argument('--myarg', type=str, help='fizz or buzz', default='fizz')
      args = parser.parse_args()

    if __name__ == '__main__':
      tf.app.run()

I'm asking since I'm wondering if the positional arguments passed to `main` by `tf.app.run` is important or not. If it's not important, we can simply swallow the `absl.flags` parsing exception in `tf.app.run` and pass `sys.argv[:1]` to `main`. Otherwise we need to add an extra API to `absl.flags`.

**Comment by dantkz** [comment]
@yilei yes, the example code works with tensorflow 1.4.

I call `main` manually just to show that the arguments are parsed by python. I wouldn't call it in a usual usecase. I don't think I would want any arguments from `tf.app.run`.


@mrry Unfortunately the work-around doesn't work:
```
(nightly) daniyar@sleepy-prism:~/tmp/argsparse$ python test.py --myarg buzz
Traceback (most recent call last):
  File "test.py", line 13, in <module>
    tf.app.run(argv=[])
  File "/home/daniyar/anaconda2/envs/tensorsource/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 119, in run
    argv = flags.FLAGS(_sys.argv if argv is None else argv)
  File "/home/daniyar/anaconda2/envs/tensorsource/lib/python3.5/site-packages/absl/flags/_flagvalues.py", line 634, in __call__
    'argv cannot be an empty list, and must contain the program name as '
ValueError: argv cannot be an empty list, and must contain the program name as the first element.
```

This, however, works:
```
if __name__ == '__main__':
    import sys
    tf.app.run(argv=sys.argv[1:])
```
and this doesn't:
```
if __name__ == '__main__':
    import sys
    tf.app.run(argv=sys.argv)
```

**Comment by yilei** [comment]
The correct workaround should be `tf.app.run(argv=sys.argv[:1])`, not `tf.app.run(argv=sys.argv[1:])`

**Comment by dantkz** [comment]
@yilei you are right, but surprisingly it works in both cases.

**Comment by yilei** [comment]
Hmm I think it worked in your example since `sys.argv[1:]` is `['--myarg', 'buzz']`, `--myargv` is treated as the program name, and it only tries to parse `['buzz']`, which only contains positional arguments.

**Comment by yilei** [comment]
@dantkz I tried your example in 1.4, but I got this:

```
$ python test.py --myarg buzz
buzz
Traceback (most recent call last):
  File "test.py", line 17, in <module>
    tf.app.run()
  File "/tmp/tf/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
TypeError: main() takes no arguments (1 given)
```

**Comment by dantkz** [comment]
@yilei Oops, my tensorflow 1.4 example had `def main(argv):`, sorry. :(

The bug is still there with `def main(argv):`.

**Comment by mrry** [comment]
Sorry for the bug in the workaround. Perhaps the following would work to ensure that the executable name is preserved?

```python
if __name__ == '__main__':
  tf.app.run(argv=sys.argv[:1])
```

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by yilei** [comment]
I believe this has been fixed with https://github.com/tensorflow/tensorflow/commit/f38f92eb369b9cbb12b2c8bd0006d7fa1c64c5c0
