### ISSUE TITLE
Tensorflow minimize operation runs into shape mismatch with StridedSliceGrad

### ISSUE THREAD

**Issue by Andrew-Draganov** [tensorflow/tensorflow#14947]
System Info:
   - custom code
   - Linux Ubuntu 16.04
   - Tensorflow 1.4.0 installed with pip install tensorflow-gpu
   - python 2.7
   - CuDa 8
   - terminal command just calls my script with "python GAN.py"

Source code:

input_points = tf.placeholder(shape=[batch_size, 2048, 3], dtype=tf.float32)
latent_vector = encoder(input_points, encoder_weights, encoder_biases)                       
reconstructed_points = decoder(latent_vector, decoder_weights, decoder_biases)               
                                                                                                 
AE_loss = chamfer_distance(input_points, reconstructed_points, batch_size)                   
                                                                                        
AE_optimizer = tf.train.AdamOptimizer(learning_rate=0.0005, beta1=0.9)                       
AE_minimizer = AE_optimizer.minimize(AE_loss)

Context: The input points and reconstructed points are the same shape. After the call to chamfer_distance(), AE_loss becomes a tf.constant.

Upon calling AE_minimizer, I receive the following error log:
Traceback (most recent call last):
  File "GAN.py", line 168, in <module>
    main()
  File "GAN.py", line 162, in main
    AE_minimizer = AE_optimizer.minimize(AE_loss, var_list=AE_parameters)
  File "/home/adraganov/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/training/optimizer.py", line 343, in minimize
    grad_loss=grad_loss)
  File "/home/adraganov/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/training/optimizer.py", line 414, in compute_gradients
    colocate_gradients_with_ops=colocate_gradients_with_ops)
  File "/home/adraganov/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/gradients_impl.py", line 581, in gradients
    grad_scope, op, func_call, lambda: grad_fn(op, *out_grads))
  File "/home/adraganov/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/gradients_impl.py", line 353, in _MaybeCompile
    return grad_fn()  # Exit early
  File "/home/adraganov/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/gradients_impl.py", line 581, in <lambda>
    grad_scope, op, func_call, lambda: grad_fn(op, *out_grads))
  File "/home/adraganov/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/array_grad.py", line 245, in _StridedSliceGrad
    shrink_axis_mask=op.get_attr("shrink_axis_mask")), None, None, None
  File "/home/adraganov/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 5572, in strided_slice_grad
    shrink_axis_mask=shrink_axis_mask, name=name)
  File "/home/adraganov/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 546, in _apply_op_helper
    inferred_from[input_arg.type_attr]))
TypeError: Input 'begin' of 'StridedSliceGrad' Op has type int64 that does not match type int32 of argument 'shape'.

I have seen traffic regarding problems with type mismatches with input 'begin', such as in Issue 11380. I have, however, seen nothing online for this specific problem, where the fields 'begin' and 'shape' have different types.

**Comment by Andrew-Draganov** [comment]
I found what the issue was, but am curious why the trace error didn't specify. The chamfer_distance loss metric had an arg_min operation, which was then being processed by minimize incorrectly, as it is non-differentiable. Does minimize not check for differentiability in the graph it is working with?

**Comment by tatatodd** [comment]
@ebrevdo or @andydavis1 might know whether `tf.train.AdamOptimizer(loss)` is supposed to return a better error, if `loss` is non-differentiable.

**Comment by facaiy** [comment]
As I known, the gradient op is not registered for `argmax` and `argmin`, since there not practical implementation, see #14931 and #2177 .  I just wonder whether we should mark them by `ops.NotDifferentiable` or `REGISTER_OP_NO_GRADIENT`. So the gradients are always zero when those ops are involved.

**Comment by andydavis1** [comment]
@aselle Can you comment on the StrideSliceGrad?

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Awaiting TensorFlower: It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
A member of the TensorFlow organization has replied after the stat:awaiting tensorflower label was applied.

**Comment by reedwm** [comment]
I believe ops without a gradient (like argmax) are treated as if their gradient is zeros (@mrry can you confirm?) I don't see how that could cause the error @Andrew-Draganov is getting though.

@Andrew-Draganov, can you post a self-contained example reproducing the problem?

**Comment by tensorflowbutler** [comment]
Nagging Awaiting TensorFlower: It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Awaiting TensorFlower: It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Awaiting TensorFlower: It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by poxvoculi** [comment]
Perhaps this is solved, or just no longer of interest.

**Comment by ZhuoyaYang** [comment]
I define op with argmax, but my loss function is differentiable. When I use python 3.6 ,it works without error.When I transfer the same code to the server(python 2.7)，it report an error "TypeError: Input 'begin' of 'StridedSliceGrad' Op has type int64 that does not match type int32 of argument 'shape'".Maybe it is a bug of tensorflow?

**Comment by ZhuoyaYang** [comment]
Oh, my problem solved! If your python is 2.7,try it!
 index = tf.to_int32(tf.argmax(xxx))
