### ISSUE TITLE
Getting the given error while installing gpu version of tensorflow

### ISSUE THREAD

**Issue by ShivamSharma1997** [tensorflow/tensorflow#14946]
Exception:
Traceback (most recent call last):
  File "C:\Users\Shivam\Anaconda2\envs\tensorflow\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\Users\Shivam\Anaconda2\envs\tensorflow\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "C:\Users\Shivam\Anaconda2\envs\tensorflow\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "C:\Users\Shivam\Anaconda2\envs\tensorflow\lib\site-packages\pip\req\req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "C:\Users\Shivam\Anaconda2\envs\tensorflow\lib\site-packages\pip\req\req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "C:\Users\Shivam\Anaconda2\envs\tensorflow\lib\site-packages\pip\wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "C:\Users\Shivam\Anaconda2\envs\tensorflow\lib\site-packages\pip\wheel.py", line 323, in clobber
    shutil.copyfile(srcfile, destfile)
  File "C:\Users\Shivam\Anaconda2\envs\tensorflow\lib\shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Shivam\\Anaconda2\\envs\\tensorflow\\Lib\\site-packages\\numpy\\core\\multiarray.cp35-win_amd64.pyd'

**Comment by ShivamSharma1997** [comment]
Also on doing import tensorflow I am getting the following

import tensorflow
Traceback (most recent call last):

  File "<ipython-input-1-d6579f534729>", line 1, in <module>
    import tensorflow

  File "C:\Users\Shivam\Anaconda2\envs\tensorflow\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import *

  File "C:\Users\Shivam\Anaconda2\envs\tensorflow\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow

  File "C:\Users\Shivam\Anaconda2\envs\tensorflow\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 30, in <module>
    self_check.preload_check()

  File "C:\Users\Shivam\Anaconda2\envs\tensorflow\lib\site-packages\tensorflow\python\platform\self_check.py", line 97, in preload_check
    % (build_info.cudnn_dll_name, build_info.cudnn_version_number))

ImportError: Could not find 'cudnn64_6.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Note that installing cuDNN is a separate step from installing CUDA, and this DLL is often found in a different directory from the CUDA DLLs. You may install the necessary DLL by downloading cuDNN 6 from this URL: https://developer.nvidia.com/cudnn

**Comment by aselle** [comment]
The error suggests this. Did you try finding cudnn and putting it in your path?
```
ImportError: Could not find 'cudnn64_6.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Note that installing cuDNN is a separate step from installing CUDA, and this DLL is often found in a different directory from the CUDA DLLs. You may install the necessary DLL by downloading cuDNN 6 from this URL: https://developer.nvidia.com/cudnn
```

**Comment by prabufca** [comment]
if you not get the cudnn64_6.dll, then use below method

you should rename the cudnn64_7.dll or cudnn64_8.dll as cudnn64_6.dll in the below path of your system

C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue? Please update the label and/or status accordingly.

**Comment by sytelus** [comment]
I'm also getting this error on Windows 10 for Tensorflow GPU version:

Tensorflow version is correct:
```
Name: tensorflow-gpu
Version: 1.4.0
```

Python/Anaconda versions are correct:
```
conda version : 4.4.3
python version : 3.5.0.final.0
```

cuDNN64_6.dll exists:
```
>where cudnn64_6.dll
>C:\Program Files\cuDNN6\cuda\bin\cudnn64_6.dll
```

NVidia CUDA 8.0 is installed.

So everything looks good and still I'm getting:
```
ImportError: DLL load failed: The specified module could not be found.
```

**Comment by sytelus** [comment]
Ok... I figured out the cause for `ImportError: DLL load failed` and also figured out the way to debug this systematically. I have seen this error occuring because either cuDNN or CUDA toolkit DLLs being of wrong version or found in Anaconda folder instead of NVidia's folder. I've written a blog post on how to debug this error:

http://shitalshah.com/p/debugging-tensorflow-dll-importerror/

Hope this helps.

**Comment by tensorflowbutler** [comment]
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
It has been 29 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
We are closing this issue for now due to lack of activity. Please comment if this is still an issue for you. Thanks!
