### ISSUE TITLE
traceback error

### ISSUE THREAD

**Issue by niinmashie** [tensorflow/tensorflow#14956]
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec cod in run_globals
  File "/usr/lib/python2.7/py_compile.py", line 181, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/py_compile.py", line 173, in main
    compile(filename, doraise=True)
  File "/usr/lib/python2.7/py_compile.py", line 106, in compile
    with open(file, 'U') as f:
IOError: [Errno 2] No such file or directory: ''
[Finished in 0.7s with exit code 1]
[shell_cmd: python -m py_compile ""]
[dir: /opt/sublime_text]
[path: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin]c

**Comment by aselle** [comment]
I apologize but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new) . Please provide all the information it asks. Thank you.
