### ISSUE TITLE
Header mismatch when running 'Simple Audio Recognition'

### ISSUE THREAD

**Issue by JerryLauzzz** [tensorflow/tensorflow#14978]
tensorflow: 1.4, ubuntu 17.10, python3.6 anaconda, cuda 8.0, cudnn 6.0

Going with [Simple Audio Recognition](https://www.tensorflow.org/versions/master/tutorials/audio_recognition), I met an error when running 
```bash
python tensorflow/examples/speech_commands/train.py --data_dir=tensorflow/examples/speech_commands/train/audio
```

error:
```
Traceback (most recent call last):                                                                                                                            
  File "/home/jihao/.conda/envs/tf_cpu/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1323, in _do_call                               
    return fn(*args)                                                                                                                                          
  File "/home/jihao/.conda/envs/tf_cpu/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1302, in _run_fn                                
    status, run_metadata)                                                                                                                                     
  File "/home/jihao/.conda/envs/tf_cpu/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__                         
    c_api.TF_GetCode(self.status.status))                                                                                                                     
tensorflow.python.framework.errors_impl.InvalidArgumentError: Header mismatch: Expected RIFF but found \udc87\udc9b\udc8f\udc8c                               
         [[Node: DecodeWav = DecodeWav[desired_channels=1, desired_samples=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](ReadFile)]]
```

**Comment by aselle** [comment]
Could you try Python 2? It looks like a unicode python 3 problem.

**Comment by aselle** [comment]
@petewarden, did you test this on Python 3?

**Comment by JerryLauzzz** [comment]
I tried anaconda python2, and the error:
```
2017-11-30 21:26:39.194187: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Header mismatch: Expected RIFF but found ����
Traceback (most recent call last):
  File "tensorflow/examples/speech_commands/train.py", line 430, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/home/jihao/.conda/envs/python27/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "tensorflow/examples/speech_commands/train.py", line 106, in main
    FLAGS.testing_percentage, model_settings)
  File "/home/jihao/deep_learning/tensorflow/tensorflow/examples/speech_commands/input_data.py", line 162, in __init__
    self.prepare_background_data()
  File "/home/jihao/deep_learning/tensorflow/tensorflow/examples/speech_commands/input_data.py", line 323, in prepare_background_data
    feed_dict={wav_filename_placeholder: wav_path}).audio.flatten()
  File "/home/jihao/.conda/envs/python27/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/home/jihao/.conda/envs/python27/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/jihao/.conda/envs/python27/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/home/jihao/.conda/envs/python27/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1323, in _do_call
    return fn(*args)
  File "/home/jihao/.conda/envs/python27/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1302, in _run_fn
    status, run_metadata)
  File "/home/jihao/.conda/envs/python27/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 472, in __exit__
    compat.as_text(c_api.TF_Message(self.status.status)),
  File "/home/jihao/.conda/envs/python27/lib/python2.7/site-packages/tensorflow/python/util/compat.py", line 84, in as_text
    return bytes_or_text.decode(encoding)
  File "/home/jihao/.conda/envs/python27/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x87 in position 41: invalid start byte
```

**Comment by JerryLauzzz** [comment]
I think this problem is caused by improper decompression
If I use the default Ubuntu decompression tool to extract, there will be this problem.

**Comment by JerryLauzzz** [comment]
I think this problem is caused by improper decompression.
If I use the default Ubuntu decompression tool to extract, there will be this problem.
If i use 
```bash 
7z x train.7z
```
I will not encounter this problem.
More in-depth reasons have yet to be studied.
Closed.

**Comment by sehargul-123** [comment]
tensorflow.python.framework.errors_impl.InvalidArgumentError: Header mismatch: Expected RIFF but found 
i am getting this error while running my run file

**Comment by outlook313** [comment]
have any solution for this problem

**Comment by yevklym** [comment]
In my case, the problem was that in the folder containing the dataset there were system files left by OS. (e.g. on Mac OS .DS_Store file).

**Comment by yagyapandeya** [comment]
In my case, this error happed due to the audio format. The TensorFlow audio could not decode the .mp3 audio format so I fixed this problem by inputting the .wav audio.
