### ISSUE TITLE
AttentionWrapperZeroState: Input to reshape is a tensor with 32768 values, but the requested shape has 65536

### ISSUE THREAD

**Issue by tusharag171** [tensorflow/tensorflow#15060]
I am building an encoder-decoder model with attention and BeamSearchDecoder using tensor flow documentation. I am getting following error:

    ---------------------------------------------------------------------------
    InvalidArgumentError                      Traceback (most recent call last)
    <ipython-input-160-ac947b28f4dd> in <module>()
         29                                           summary_length: [generagte_summary_length], #summary_length: [np.random.randint(5,8)],
         30                                           text_length: [len(text)]*batch_size,
    ---> 31                                           keep_prob: 1.0})[0] 
         32         # Remove the padding from the summaries
         33         pad = vocab_to_int["<PAD>"]

    /Users/tusharagarwal/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in run(self, fetches, feed_dict, options, run_metadata)
        893     try:
        894       result = self._run(None, fetches, feed_dict, options_ptr,
    --> 895                          run_metadata_ptr)
        896       if run_metadata:
        897         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

    /Users/tusharagarwal/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in _run(self, handle, fetches, feed_dict, options, run_metadata)
       1122     if final_fetches or final_targets or (handle and feed_dict_tensor):
       1123       results = self._do_run(handle, final_targets, final_fetches,
    -> 1124                              feed_dict_tensor, options, run_metadata)
       1125     else:
       1126       results = []

    /Users/tusharagarwal/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
       1319     if handle is None:
       1320       return self._do_call(_run_fn, self._session, feeds, fetches, targets,
    -> 1321                            options, run_metadata)
       1322     else:
       1323       return self._do_call(_prun_fn, self._session, handle, feeds, fetches)

    /Users/tusharagarwal/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in _do_call(self, fn, *args)
       1338         except KeyError:
       1339           pass
    -> 1340       raise type(e)(node_def, op, message)
       1341 
       1342   def _extend_graph(self):

    InvalidArgumentError: Input to reshape is a tensor with 32768 values, but the requested shape has 65536
         [[Node: decode_1/Reshape_2 = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/cpu:0"](tile_batch_2/Reshape_2, decode_1/concat_2)]]

    Caused by op u'decode_1/Reshape_2', defined at:
      File "/Users/tusharagarwal/anaconda2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
        "__main__", fname, loader, pkg_name)
      File "/Users/tusharagarwal/anaconda2/lib/python2.7/runpy.py", line 72, in _run_code
        exec code in run_globals
      File "/Users/tusharagarwal/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py", line 3, in <module>
        app.launch_new_instance()
      File "/Users/tusharagarwal/anaconda2/lib/python2.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
        app.start()
      File "/Users/tusharagarwal/anaconda2/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 474, in start
        ioloop.IOLoop.instance().start()
      File "/Users/tusharagarwal/anaconda2/lib/python2.7/site-packages/zmq/eventloop/ioloop.py", line 177, in start
        super(ZMQIOLoop, self).start()
      File "/Users/tusharagarwal/anaconda2/lib/python2.7/site-packages/tornado/ioloop.py", line 887, in start
        handler_func(fd_obj, events)
      File "/Users/tusharagarwal/anaconda2/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
        return fn(*args, **kwargs)
      File "/Users/tusharagarwal/anaconda2/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
        self._handle_recv()
      File "/Users/tusharagarwal/anaconda2/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
        self._run_callback(callback, msg)
      File "/Users/tusharagarwal/anaconda2/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
        callback(*args, **kwargs)
      File "/Users/tusharagarwal/anaconda2/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
        return fn(*args, **kwargs)
      File "/Users/tusharagarwal/anaconda2/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 276, in dispatcher
        return self.dispatch_shell(stream, msg)
      File "/Users/tusharagarwal/anaconda2/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 228, in dispatch_shell
        handler(stream, idents, msg)
      File "/Users/tusharagarwal/anaconda2/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 390, in execute_request
        user_expressions, allow_stdin)
      File "/Users/tusharagarwal/anaconda2/lib/python2.7/site-packages/ipykernel/ipkernel.py", line 196, in do_execute
        res = shell.run_cell(code, store_history=store_history, silent=silent)
      File "/Users/tusharagarwal/anaconda2/lib/python2.7/site-packages/ipykernel/zmqshell.py", line 501, in run_cell
        return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
      File "/Users/tusharagarwal/anaconda2/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2717, in run_cell
        interactivity=interactivity, compiler=compiler, result=result)
      File "/Users/tusharagarwal/anaconda2/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2821, in run_ast_nodes
        if self.run_code(code, result):
      File "/Users/tusharagarwal/anaconda2/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2881, in run_code
        exec(code_obj, self.user_global_ns, self.user_ns)
      File "<ipython-input-160-ac947b28f4dd>", line 18, in <module>
        loader = tf.train.import_meta_graph(checkpoint + '.meta')
      File "/Users/tusharagarwal/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1698, in import_meta_graph
        **kwargs)
      File "/Users/tusharagarwal/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/meta_graph.py", line 656, in import_scoped_meta_graph
        producer_op_list=producer_op_list)
      File "/Users/tusharagarwal/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/importer.py", line 313, in import_graph_def
        op_def=op_def)
      File "/Users/tusharagarwal/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
        original_op=self._default_original_op, op_def=op_def)
      File "/Users/tusharagarwal/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
        self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

    InvalidArgumentError (see above for traceback): Input to reshape is a tensor with 32768 values, but the requested shape has 65536
         [[Node: decode_1/Reshape_2 = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/cpu:0"](tile_batch_2/Reshape_2, decode_1/concat_2)]]

The error occurs when trying to Make predictions(Test the Model Section) .Training runs fine. The error occurs when I set beam_size >=2. (The error shown is for beam_size=2). However it runs fine for beam_size = 1. I am not able to figure out what is going wrong. I know the code is long. Any help will be highly appreciated as I am unable to debug it and stuck on it for days. My code is:

My code is here:
# Model Inputs

    def model_inputs():
        input_data = tf.placeholder(tf.int32, [None, None], name='input')
        targets = tf.placeholder(tf.int32, [None, None], name='targets')
        lr = tf.placeholder(tf.float32, name='learning_rate')
        keep_prob = tf.placeholder(tf.float32, name='keep_prob')
        summary_length = tf.placeholder(tf.int32, (None,), name='summary_length')
        max_summary_length = tf.reduce_max(summary_length, name='max_dec_len')
        text_length = tf.placeholder(tf.int32, (None,), name='text_length')

        return input_data, targets, lr, keep_prob, summary_length, max_summary_length, text_length

    def process_encoding_input(target_data, vocab_to_int, batch_size):  
        ending = tf.strided_slice(target_data, [0, 0], [batch_size, -1], [1, 1]) # slice it to target_data[0:batch_size, 0: -1]
        dec_input = tf.concat([tf.fill([batch_size, 1], vocab_to_int['<GO>']), ending], 1)

        return dec_input
# Encoding layer

    def encoding_layer(rnn_size, sequence_length, num_layers, rnn_inputs, keep_prob):
        for layer in range(num_layers):
            with tf.variable_scope('encoder_{}'.format(layer)):
                cell_fw = tf.contrib.rnn.LSTMCell(rnn_size,
                                                  initializer=tf.random_uniform_initializer(-0.1, 0.1, seed=2))
                cell_fw = tf.contrib.rnn.DropoutWrapper(cell_fw, 
                                                        input_keep_prob = keep_prob)

                cell_bw = tf.contrib.rnn.LSTMCell(rnn_size,
                                                  initializer=tf.random_uniform_initializer(-0.1, 0.1, seed=2))
                cell_bw = tf.contrib.rnn.DropoutWrapper(cell_bw, 
                                                        input_keep_prob = keep_prob)

                enc_output, enc_state = tf.nn.bidirectional_dynamic_rnn(cell_fw, 
                                                                        cell_bw, 
                                                                        rnn_inputs,
                                                                        sequence_length,
                                                                        dtype=tf.float32)
                enc_output = tf.concat(enc_output,2)
                # original code is missing this line below, that is how we connect layers 
                # by feeding the current layer's output to next layer's input
                #rnn_inputs = enc_output
        return enc_output, enc_state

# Training Decoding layer  

    def training_decoding_layer(dec_embed_input, summary_length, dec_cell, output_layer,
                                vocab_size, max_summary_length,batch_size,enc_state):
        training_helper = tf.contrib.seq2seq.TrainingHelper(inputs=dec_embed_input,
                                                            sequence_length=summary_length,
                                                            time_major=False)

        training_decoder = tf.contrib.seq2seq.BasicDecoder(cell=dec_cell,
                                                           helper=training_helper,
                                            initial_state=dec_cell.zero_state(dtype=tf.float32, batch_size=batch_size).clone(cell_state=enc_state),
                                                           output_layer = output_layer)

        training_logits,_,_ = tf.contrib.seq2seq.dynamic_decode(training_decoder,
                                                                impute_finished = True,
                                                               maximum_iterations=max_summary_length)
        return training_logits

# Inference Decoding layer  

    def inference_decoding_layer(embeddings, start_token, end_token, dec_cell, output_layer,
                                 max_summary_length, batch_size,lengths,enc_state,beam_width):
        '''Create the inference logits'''

        start_tokens = tf.ones_like(lengths) * start_token

        inference_decoder = tf.contrib.seq2seq.BeamSearchDecoder(
                        cell          = dec_cell,
                        embedding     = embeddings,
                        start_tokens  = start_tokens,
                        end_token     = end_token,
                        initial_state = dec_cell.zero_state(dtype=tf.float32, batch_size=batch_size * beam_width*2).clone(cell_state=enc_state) ,
                        beam_width    = beam_width,
                        output_layer  = output_layer)

        inference_logits,_,_ = tf.contrib.seq2seq.dynamic_decode(inference_decoder,
                                                                 impute_finished = False,
                                                                maximum_iterations=max_summary_length)

        return inference_logits

    def lstm_cell(lstm_size, keep_prob):
        cell = tf.contrib.rnn.BasicLSTMCell(lstm_size)
        return tf.contrib.rnn.DropoutWrapper(cell, input_keep_prob = keep_prob)

# Decoding layer 

    def decoding_layer(dec_embed_input, embeddings, enc_output, enc_state, vocab_size, text_length, summary_length,
                       max_summary_length, rnn_size, vocab_to_int, keep_prob, batch_size, num_layers):
        '''Create the decoding cell and attention for the training and inference decoding layers'''
        output_layer = Dense(vocab_size,kernel_initializer=tf.truncated_normal_initializer(mean=0.0, stddev=0.1))

        with tf.variable_scope("decode"):
            dec_cell = tf.contrib.rnn.MultiRNNCell([lstm_cell(rnn_size, keep_prob) for _ in range(num_layers)])
            attn_mech = tf.contrib.seq2seq.BahdanauAttention(rnn_size,
                                                         enc_output,
                                                         text_length,
                                                         normalize=False,
                                                         )
            dec_cell = tf.contrib.seq2seq.AttentionWrapper(cell =dec_cell,
                                                           attention_mechanism = attn_mech, 
                                                           attention_layer_size=rnn_size)

            training_logits = training_decoding_layer(dec_embed_input,summary_length,dec_cell,
                                                      output_layer,
                                                      vocab_size,
                                                      max_summary_length,
                                                      batch_size,enc_state)

        beam_width = 2
        enc_output = tf.contrib.seq2seq.tile_batch(enc_output, multiplier=beam_width)
        lengths = tf.contrib.seq2seq.tile_batch(text_length, multiplier=beam_width)
        enc_state = tf.contrib.seq2seq.tile_batch(enc_state, multiplier=beam_width)

        with tf.variable_scope("decode", reuse=True):
            dec_cell = tf.contrib.rnn.MultiRNNCell([lstm_cell(rnn_size, keep_prob) for _ in range(num_layers)])
            attn_mech = tf.contrib.seq2seq.BahdanauAttention(rnn_size,
                                                         enc_output,
                                                         lengths,
                                                         normalize=False,
                                                         )
            dec_cell = tf.contrib.seq2seq.AttentionWrapper(cell =dec_cell,
                                                           attention_mechanism = attn_mech, 
                                                           attention_layer_size=rnn_size)

            inference_logits = inference_decoding_layer(embeddings,
                                                        vocab_to_int['<GO>'],
                                                        vocab_to_int['<EOS>'],
                                                        dec_cell,
                                                        output_layer,
                                                        max_summary_length,
                                                        batch_size,lengths,enc_state,beam_width)
        return training_logits, inference_logits

    def seq2seq_model(input_data, target_data, keep_prob, text_length, summary_length, max_summary_length, 
                      vocab_size, rnn_size, num_layers, vocab_to_int, batch_size):
        '''Use the previous functions to create the training and inference logits'''

        # Use Numberbatch's embeddings and the newly created ones as our embeddings
        #embeddings = word_embedding_matrix
        embeddings_s = tf.get_variable("word_embeddings",[vocab_size, 300])
        embeddings_t = tf.get_variable("word_embeddings2",[vocab_size, 300])
        enc_embed_input = tf.nn.embedding_lookup(embeddings_s, input_data)
        enc_output, enc_state = encoding_layer(rnn_size, text_length, num_layers, enc_embed_input, keep_prob)
        dec_input = process_encoding_input(target_data, vocab_to_int, batch_size) #shape=(batch_size, senquence length) each seq start with index of<GO>
        dec_embed_input = tf.nn.embedding_lookup(embeddings_t, dec_input)
        training_logits, inference_logits  = decoding_layer(dec_embed_input, 
                                                            embeddings_t,
                                                            enc_output,
                                                            enc_state, 
                                                            vocab_size, 
                                                            text_length, 
                                                            summary_length, 
                                                            max_summary_length,
                                                            rnn_size, 
                                                            vocab_to_int, 
                                                            keep_prob, 
                                                            batch_size,
                                                            num_layers)
        return training_logits, inference_logits

# Set the Hyperparameters
    epochs = 100
    batch_size = 64
    rnn_size = 256
    num_layers = 2
    learning_rate = 0.005
    keep_probability = 0.95

# Build the graph
    train_graph = tf.Graph()
    # Set the graph to default to ensure that it is ready for training
    with train_graph.as_default():

        # Load the model inputs    
        input_data, targets, lr, keep_prob, summary_length, max_summary_length, text_length = model_inputs()

        # Create the training and inference logits
        training_logits, inference_logits = seq2seq_model(tf.reverse(input_data, [-1]),
                                                          targets, 
                                                          keep_prob,   
                                                          text_length,
                                                          summary_length,
                                                          max_summary_length,
                                                          len(vocab_to_int)+1,
                                                          rnn_size, 
                                                          num_layers, 
                                                          vocab_to_int,
                                                          batch_size)

        # Create tensors for the training logits and inference logits
        training_logits = tf.identity(training_logits.rnn_output, 'logits')
        #inference_logits = inference_logits.predicted_ids[:,:,0]
        inference_logits = tf.identity(inference_logits.predicted_ids, name='predictions')

        # Create the weights for sequence_loss, the sould be all True across since each batch is padded
        masks = tf.sequence_mask(summary_length, max_summary_length, dtype=tf.float32, name='masks')

        with tf.name_scope("optimization"):
            # Loss function
            cost = tf.contrib.seq2seq.sequence_loss(
                training_logits,
                targets,
                masks)

            # Optimizer
            optimizer = tf.train.AdamOptimizer(learning_rate)

            # Gradient Clipping
            gradients = optimizer.compute_gradients(cost)
            capped_gradients = [(tf.clip_by_value(grad, -5., 5.), var) for grad, var in gradients if grad is not None]
            train_op = optimizer.apply_gradients(capped_gradients)
    print("Graph is built.")
    graph_location = "./graph"
    print(graph_location)
    train_writer = tf.summary.FileWriter(graph_location)
    train_writer.add_graph(train_graph)

# Train the Model
    learning_rate_decay = 0.95
    min_learning_rate = 0.0005
    display_step = 20 # Check training loss after every 20 batches
    stop_early = 0 
    stop = 3 # If the update loss does not decrease in 3 consecutive update checks, stop training
    per_epoch = 3 # Make 3 update checks per epoch
    #update_check = (len(sorted_texts_short)//batch_size//per_epoch)-1
    update_check = 2

    update_loss = 0 
    batch_loss = 0
    summary_update_loss = [] # Record the update losses for saving improvements in the model

    checkpoint = "./best_model.ckpt" 
    with tf.Session(graph=train_graph) as sess:
        sess.run(tf.global_variables_initializer())

        # If we want to continue training a previous session
        #loader = tf.train.import_meta_graph("./" + checkpoint + '.meta')
        #loader.restore(sess, checkpoint)

        for epoch_i in range(1, epochs+1):
            update_loss = 0
            batch_loss = 0
            for batch_i, (summaries_batch, texts_batch, summaries_lengths, texts_lengths) in enumerate(
                    get_batches(sorted_summaries_short, sorted_texts_short, batch_size)):
                start_time = time.time()
                _, loss = sess.run(
                    [train_op, cost],
                    {input_data: texts_batch,
                     targets: summaries_batch,
                     lr: learning_rate,
                     summary_length: summaries_lengths,
                     text_length: texts_lengths,
                     keep_prob: keep_probability})

                batch_loss += loss
                update_loss += loss
                end_time = time.time()
                batch_time = end_time - start_time

                if batch_i % display_step == 0 and batch_i > 0:
                    print('Epoch {:>3}/{} Batch {:>4}/{} - Loss: {:>6.3f}, Seconds: {:>4.2f}'
                          .format(epoch_i,
                                  epochs, 
                                  batch_i, 
                                  len(sorted_texts_short) // batch_size, 
                                  batch_loss / display_step, 
                                  batch_time*display_step))
                    batch_loss = 0

                if batch_i % update_check == 0 and batch_i > 0:
                    print("Average loss for this update:", round(update_loss/update_check,3))
                    summary_update_loss.append(update_loss)

                    # If the update loss is at a new minimum, save the model
                    if update_loss <= min(summary_update_loss):
                        print('New Record!') 
                        stop_early = 0
                        saver = tf.train.Saver() 
                        saver.save(sess, checkpoint)

                    else:
                        print("No Improvement.")
                        stop_early += 1
                        if stop_early == stop:
                            break
                    update_loss = 0

            # Reduce learning rate, but not below its minimum value
            learning_rate *= learning_rate_decay
            if learning_rate < min_learning_rate:
                learning_rate = min_learning_rate

            if stop_early == stop:
                print("Stopping Training.")
                break

    def text_to_seq(text):
        '''Prepare the text for the model'''

        text = clean_text(text)
        return [vocab_to_int.get(word, vocab_to_int['<UNK>']) for word in text.split()]
# Test The Model   

    input_sentences=["The coffee tasted great and was at such a good price! I highly recommend this to everyone!",
                   "love individual oatmeal cups found years ago sam quit selling sound big lots quit selling found target expensive buy individually trilled get entire case time go anywhere need water microwave spoon know quaker flavor packets"]
    generagte_summary_length =  [3,2]

    # input_sentences = test_text[0:10]
    # generagte_summary_length = summary_l[0:10]
    texts = [text_to_seq(input_sentence) for input_sentence in input_sentences]
    checkpoint = "./best_model.ckpt"
    if type(generagte_summary_length) is list:
        if len(input_sentences)!=len(generagte_summary_length):
            raise Exception("[Error] makeSummaries parameter generagte_summary_length must be same length as input_sentences or an integer")
        generagte_summary_length_list = generagte_summary_length
    else:
        generagte_summary_length_list = [generagte_summary_length] * len(texts)
    loaded_graph = tf.Graph()
    with tf.Session(graph=loaded_graph) as sess:
        # Load saved model
        loader = tf.train.import_meta_graph(checkpoint + '.meta')
        loader.restore(sess, checkpoint)
        input_data = loaded_graph.get_tensor_by_name('input:0')
        logits = loaded_graph.get_tensor_by_name('predictions:0')
        text_length = loaded_graph.get_tensor_by_name('text_length:0')
        summary_length = loaded_graph.get_tensor_by_name('summary_length:0')
        keep_prob = loaded_graph.get_tensor_by_name('keep_prob:0')
        #Multiply by batch_size to match the model's input parameters
        for i, text in enumerate(texts):
            generagte_summary_length = generagte_summary_length_list[i]
            answer_logits = sess.run(logits, {input_data: [text]*batch_size, 
                                              summary_length: [generagte_summary_length], #summary_length: [np.random.randint(5,8)], 
                                              text_length: [len(text)]*batch_size,
                                              keep_prob: 1.0})[0] 
            # Remove the padding from the summaries
            pad = vocab_to_int["<PAD>"] 
            print('- Review:\n\r {}'.format(input_sentences[i]))
            print('- Summary:\n\r {}\n\r\n\r'.format(" ".join([int_to_vocab[i[0]] for i in answer_logits if i[0] != pad])))
tensorflow

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue? Please update the label and/or status accordingly.

**Comment by tusharag171** [comment]
Figured out the problem. Thanks

**Comment by harryxu-yscz** [comment]
@tusharag171 hi! I am running into the same problem. Would you mind sharing your solution? Thanks in advance!

**Comment by yprajakta12** [comment]
Can u please share the solution to the problem?? we would be glad to you @tusharag171 
please!!

**Comment by aijianiula0601** [comment]
I encoutered the same problem.How to save it ,thanks!
