### ISSUE TITLE
java.lang.UnsatisfiedLinkError: No implementation found for void com.ppdai.tensorflow.tracking.ObjectTracker.initNative(int, int, boolean)

### ISSUE THREAD

**Issue by webwalker** [tensorflow/tensorflow#15096]
recently i begin to learn and use tensorflow but some errors i don't know why,  help me please, error as follow:

Process: com.ppdai.tensorflow, PID: 4226
                                                 java.lang.UnsatisfiedLinkError: No implementation found for void com.ppdai.tensorflow.tracking.ObjectTracker.initNative(int, int, boolean) (tried Java_com_ppdai_tensorflow_tracking_ObjectTracker_initNative and Java_com_ppdai_tensorflow_tracking_ObjectTracker_initNative__IIZ)
                                                     at com.ppdai.tensorflow.tracking.ObjectTracker.initNative(Native Method)
                                                     at com.ppdai.tensorflow.tracking.ObjectTracker.init(ObjectTracker.java:257)
                                                     at com.ppdai.tensorflow.tracking.ObjectTracker.getInstance(ObjectTracker.java:220)
                                                     at com.ppdai.tensorflow.tracking.MultiBoxTracker.onFrame(MultiBoxTracker.java:211)
                                                     at com.ppdai.tensorflow.DetectorActivity.processImage(DetectorActivity.java:250)
                                                     at com.ppdai.tensorflow.CameraActivity.onPreviewFrame(CameraActivity.java:149)
                                                     at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1285)
                                                     at android.os.Handler.dispatchMessage(Handler.java:111)
                                                     at android.os.Looper.loop(Looper.java:194)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5868)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1019)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:814)

1、firstly compile aar from jcenter 1.4.0
2、secondly add related so to jniLibs 
      libtensorflow_demo.so
      libtensorflow_inference.so
      libandroid_tensorflow_lib.lo
      benchmark_model
3、then use offical demo code to test tensorflow detect function, error comes.

what will i can do to solve this problem?

i have add related so

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assigneee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @derekjchow: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
It has been 44 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
It has been 60 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by achraf-boussaada** [comment]
having the same problem.. any updates ?

**Comment by umutboz** [comment]
Could it be related to the android studio update? After updating, I started getting errors in my old apps

**Comment by bnhc** [comment]
having the same problem.. me too, any updates ?

**Comment by achraf-boussaada** [comment]
Solved this here [#19384](https://github.com/tensorflow/tensorflow/issues/19384)

**Comment by tensorflowbutler** [comment]
It has been 15 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
It has been 30 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
We are closing this issue for now due to lack of activity. Please comment if this is still an issue for you. Thanks!
