### ISSUE TITLE
tensorflow lite: error when convert frozen model to lite format

### ISSUE THREAD

**Issue by zhang13850588961** [tensorflow/tensorflow#15122]
Hi,
I build the freeze .pb with the guide at https://github.com/tensorflow/models/tree/master/research/slim 
with the below step:
 
python train_image_classifier.py \
--train_dir /home/ubuntu/train/ \
--dataset_dir /home/ubuntu/vegetables/ \
--dataset_name=vegetables \
--dataset_split_name=train  \
--num_clones=2 \
--clone_on_cpu=True \
--checkpoint_path=/home/ubuntu/check_point/mobilenet_v1_1.0_224.ckpt \
--max_number_of_steps=10 \
--checkpoint_exclude_scopes=MobilenetV1/Logits,MobilenetV1/AuxLogits \
--model_name=mobilenet_v1

python tensorflow/python/tools/freeze_graph.py \
    --input_graph=/home/ubuntu/train/mobilenet_v1_224.pb \
    --input_checkpoint=/home/ubuntu/check_point/mobilenet_v1_1.0_224.ckpt \
    --input_binary=true \
    --output_graph=/home/ubuntu/train/frozen_mobilenet_v1_224.pb \
    --output_node_names=MobilenetV1/Predictions/Reshape_1

NOTE: I download mobilenet_v1_1.0_224.ckpt from http://download.tensorflow.org/models/mobilenet_v1_1.0_224_2017_06_14.tar.gz

But when I convert to lite mode with 

ubuntu@ip-172-31-27-248:~/tensorflow$ bazel-bin/tensorflow/contrib/lite/toco/toco \
  --input_format=TENSORFLOW_GRAPHDEF \
   --input_format=TENSORFLOW_GRAPHDEF \
   --input_file=/home/ubuntu/mobilenet_v1_1.0_224/frozen_mobilenet_v1_224.pb \
   --output_format=TFLITE \
   --output_file=/tmp/mobilenet_v1_1.0_224.lite --inference_type=FLOAT \
   --inference_input_type=FLOAT \
   --input_arrays=input \
   --output_arrays=MobilenetV1/Predictions/Reshape_1 --input_shapes=1,224,224,3
 
2017-12-05 09:53:56.604720: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 336 operators, 502 arrays (0 quantized)
2017-12-05 09:53:56.627922: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 1: 31 operators, 88 arrays (0 quantized)
2017-12-05 09:53:56.628156: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before dequantization graph transformations: 31 operators, 88 arrays (0 quantized)
2017-12-05 09:53:56.628327: I tensorflow/contrib/lite/toco/allocate_transient_arrays.cc:312] Total transient array allocated size: 6422528 bytes, theoretical optimal value: 4816896 bytes.
2017-12-05 09:53:56.628487: I tensorflow/contrib/lite/toco/toco_tooling.cc:268] Estimated count of arithmetic ops: 1.14264 billion (note that a multiply-add is counted as 2 ops).
2017-12-05 09:53:56.628653: F tensorflow/contrib/lite/toco/tflite/export.cc:192] Unsupported operator: Squeeze
Aborted (core dumped)

Pls help me! 

my other question is when I download the pretrain freeze pb from https://storage.googleapis.com/download.tensorflow.org/models/tflite/mobilenet_v1_1.0_224_float_2017_11_08.zip 
It's work when I use toco tools. where I can find guide which generate these freeze pb.

Pls Help!

**Comment by andrehentz** [comment]
I am not able to retrain and freeze using train_image_classifier.py.

Have you tried something like the following?

```
python tensorflow/examples/image_retraining/retrain.py \
  --image_dir /home/ubuntu/flower_photos \
  --architecture mobilenet_1.0_224
```

```
bazel-bin/tensorflow/contrib/lite/toco/toco \
  --input_format=TENSORFLOW_GRAPHDEF \
  --input_file=/tmp/output_graph.pb \
  --output_format=TFLITE \
  --output_file=/tmp/mobilenet_v1_1.0_224.lite \
  --inference_type=FLOAT \
  --inference_input_type=FLOAT \
  --input_arrays=input \
  --output_arrays=final_result \
  --input_shapes=1,224,224,3
```

**Comment by zhang13850588961** [comment]
@andrehentz tks for you help!
I try below:
python tensorflow/examples/image_retraining/retrain.py \
    --image_dir /home/ubuntu/vegetables_photos/ \
    --output_graph /home/ubuntu/vegetables_out/vegetables.pb \
    --output_label /home/ubuntu/vegetables_out/labels.txt \
    --how_many_training_steps=60 \
    --architecture mobilenet_1.0_224

bazel-bin/tensorflow/contrib/lite/toco/toco \
  --input_format=TENSORFLOW_GRAPHDEF \
  --input_file=/home/ubuntu/vegetables_out/vegetables.pb \
  --output_format=TFLITE \
  --output_file=/home/ubuntu/vegetables_out/mobilenet_quant_v1_224.tflite \
  --inference_type=FLOAT \
  --inference_input_type=FLOAT \
  --input_arrays=input \
  --output_arrays=final_result \
  --input_shapes=1,224,224,3
android I put the mobilenet_quant_v1_224.tflite into the TfLiteCameraDemo.apk assert dir,android run TfLiteCameraDemo.apk, but the apk throws error:
Caused by: java.lang.IllegalArgumentException: Failed to get input dimensions. 0-th input should have 602112 bytes, but found 150528 bytes.



however I find then TfLiteCameraDemo.apk need quant mode,so I try below:
python tensorflow/examples/image_retraining/retrain.py \
    --image_dir /home/ubuntu/vegetables_photos/ \
    --output_graph /home/ubuntu/vegetables_out/vegetables.pb \
    --output_label /home/ubuntu/vegetables_out/labels.txt \
    --how_many_training_steps=60 \
    --architecture mobilenet_1.0_224_quantized

bazel-bin/tensorflow/contrib/lite/toco/toco \
  --input_format=TENSORFLOW_GRAPHDEF \
  --input_file=/home/ubuntu/vegetables_out/vegetables.pb \
  --output_format=TFLITE \
  --output_file=/home/ubuntu/vegetables_out/mobilenet_quant_v1_224.tflite \
  --input_shapes=1,224,224,3 \
  --inference_type=QUANTIZED_UINT8 \
  --input_arrays=Placeholder \
  --output_arrays=final_result \
  --mean_values=128 \
  --std_values=127
then I got the error:
017-12-06 09:21:10.165673: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1046] Converting unsupported operation: AssignSub
2017-12-06 09:21:10.165698: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1046] Converting unsupported operation: AssignAdd
2017-12-06 09:21:10.165729: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1046] Converting unsupported operation: Pow
2017-12-06 09:21:10.165757: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1046] Converting unsupported operation: AssignSub
2017-12-06 09:21:10.165801: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1046] Converting unsupported operation: AssignSub
2017-12-06 09:21:10.165823: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1046] Converting unsupported operation: AssignAdd
2017-12-06 09:21:10.165853: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1046] Converting unsupported operation: Pow
2017-12-06 09:21:10.165890: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1046] Converting unsupported operation: AssignSub
2017-12-06 09:21:10.219204: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 1433 operators, 2236 arrays (0 quantized)
2017-12-06 09:21:10.623803: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 1: 401 operators, 962 arrays (1 quantized)
2017-12-06 09:21:10.630679: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 2: 94 operators, 184 arrays (1 quantized)
2017-12-06 09:21:10.631553: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 3: 94 operators, 184 arrays (1 quantized)
2017-12-06 09:21:10.632222: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before pre-quantization graph transformations: 94 operators, 184 arrays (1 quantized)
2017-12-06 09:21:10.632392: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] After pre-quantization graph transformations pass 1: 66 operators, 156 arrays (1 quantized)
2017-12-06 09:21:10.632699: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before quantization graph transformations: 66 operators, 156 arrays (1 quantized)
2017-12-06 09:21:10.671081: F tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:354] Unimplemented: this graph contains an operator of type (Unsupported TensorFlow op: Pow) for which the quantized form is not yet implemented. Sorry, and patches welcome (that's a relatively fun patch to write, mostly providing the actual quantized arithmetic code for this op).
Aborted (core dumped)

My question is : 
 How I can retrain model which like mobilenet_quant_v1_224.tflite in the TfLiteCameraDemo.apk
pls help!

**Comment by andrehentz** [comment]
Retraining  mobilenet_1.0_224_quantized is something we are still working on and we hope to update our docs and code soon.

Meanwhile, I have to suboptimal workarounds for you:
  1) Change the demo app to work with floating-point numbers (it requires changes [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/lite/java/demo/app/src/main/java/com/example/android/tflitecamerademo/ImageClassifier.java#L75) and [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/lite/java/demo/app/src/main/java/com/example/android/tflitecamerademo/ImageClassifier.java#L157) at least)

  2) Use "approximate" quantization when converting with toco:
```
python tensorflow/examples/image_retraining/retrain.py \
  --image_dir /home/ubuntu/flower_photos \
  --architecture mobilenet_1.0_224

bazel-bin/tensorflow/contrib/lite/toco/toco \
  --input_format=TENSORFLOW_GRAPHDEF \
  --input_file=/tmp/output_graph.pb \
  --output_format=TFLITE \
  --output_file=/tmp/mobilenet_v1_1.0_224.lite \
  --inference_type=QUANTIZED_UINT8 \
  --inference_input_type=QUANTIZED_UINT8 \
  --input_arrays=input \
  --output_arrays=final_result \
  --input_shapes=1,224,224,3\
  --mean_values=128 \
  --std_values=128 \
  --default_ranges_min=0 \
  --default_ranges_max=6
```

**Comment by zhang13850588961** [comment]
@andrehentz  It's work for me,very thanks for your help.

**Comment by zhang13850588961** [comment]
@andrehentz @aselle 
I face one problem like below,
I retain my modes ,and test in pc:
ubuntu@ip-172-31-27-248:~/tensorflow$ python tensorflow/examples/label_image/label_image.py \
>   --graph=/home/ubuntu/vegetables_train/vegetables_out/vegetables.pb \
>   --labels=/home/ubuntu/vegetables_train/vegetables_out/labels.txt \
>   --image=/home/ubuntu/test_photos/3.jpg \
>   --input_layer=input \
>   --output_layer=final_result \
>   --input_mean=128 \
>   --input_std=128 \
>   --input_width=224 \
>   --input_height=224
xi hong shi 0.99971
xi qin 0.000140324
hu luo bo 6.89621e-05
shang hai qing 3.10927e-05
jian jiao 2.14989e-05
the reusult is very nice!


but after I quant the model with:
bazel-bin/tensorflow/contrib/lite/toco/toco \
  --input_format=TENSORFLOW_GRAPHDEF \
  --input_file=/home/ubuntu/vegetables_train/vegetables_out/vegetables.pb \
  --output_format=TFLITE \
  --output_file=/home/ubuntu/vegetables_train/vegetables_out/mobilenet_quant_v1_224.tflite \
  --input_shapes=1,224,224,3 \
  --inference_type=QUANTIZED_UINT8 \
  --inference_input_type=QUANTIZED_UINT8 \
  --input_arrays=input \
  --output_arrays=final_result \
  --default_ranges_min=0 \
  --default_ranges_max=6 \
  --mean_values=128 \
  --std_values=128
put the mobilenet_quant_v1_224.tflite into TfLiteCameraDemo.apk , run TfLiteCameraDemo.apk,it's very very diffcult to  recognition the vegetables,
I think this because quant to UINT8.
And now I will try FLOAT model ,My question is:How to modify TfLiteCameraDemo app code to support FLOAT lite mode?
pls help!

**Comment by aselle** [comment]
Doing quantized requires specialized training. Your input of default ranges sets invalid ranges that are useful for testing the possible speedup due to quantization but will not result in correct classification. We plan to release a quantized training script to show how you might do this with your model. 

As far as changing TfLiteCameraDemo to support floats:
edit this
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/lite/java/demo/app/src/main/java/com/example/android/tflitecamerademo/ImageClassifier.java

You can change the convertBitmapToByteBuffer to make a float array instead of a byte array.
That's about it I think.

**Comment by powderluv** [comment]
@aselle any luck with the sample  quantized training script ? Thanks

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by kk-huang** [comment]
Hi, I covert the frozen graph:mobilenet_v1_224 to tflite, and put it in the tflitecamerademo app, but the regonization result is not correct. If I use the tflite file which download from https://storage.googleapis.com/download.tensorflow.org/models/tflite/mobilenet_v1_224_android_quant_2017_11_08.zip

The regonization result is correct, I don't know what steps is not correct when I covert the frozeon graph to tflite file, could you help me to review what steps is the wrong?

I put the frozen graph, coverting tflite file and the regonized picture in the https://drive.google.com/drive/folders/12h9O2AtcnDuQZXogAdmexRSjxIQVc1Ej?usp=sharing

The correct result should be "malamute", but I use the my coverting tflite file, the result  is "shower curtain"

I use the command to do the covert
bazel run --config=opt //tensorflow/contrib/lite/toco:toco -- '--input_file=/tmp/mobilenet_frozen_graph.pb' '--output_file=/tmp/mobilenet_quant_20180117.tflite' '--input_format=TENSORFLOW_GRAPHDEF' '--output_format=TFLITE' '--inference_type=QUANTIZED_UINT8' '--inference_input_type=QUANTIZED_UINT8' '--input_shapes=1,224,224,3' '--input_arrays=input' '--output_arrays=MobilenetV1/Predictions/Reshape_1' '--mean_values=128' '--std_values=128' '--default_ranges_min=0' '--default_ranges_max=6'

Thanks

**Comment by cqf7174** [comment]
@andrehentz have you solve the issue for mobilenet_1.0_224_quantized retrain + toco .tflite ?

**Comment by cqf7174** [comment]
@aselle @andrehentz do you have new ImageClassifier.java file which can support float?

**Comment by ecrasy** [comment]
Here is the example of use float for inference
[https://github.com/googlecodelabs/tensorflow-for-poets-2/blob/master/android/tflite/app/src/main/java/com/example/android/tflitecamerademo/ImageClassifier.java](url)

**Comment by andrehentz** [comment]
While full quantized training is still in the works, retraining an existing quantized mobilenet (currently only  mobilenet_1.0_224_quantized) should work. You can follow the step in [TensorFlow for Poets](https://codelabs.developers.google.com/codelabs/tensorflow-for-poets/) which I reproduce (slightly modified) here:

```
ARCHITECTURE=mobilenet_1.0_224_quantized                                                           
DATA_DIR=~/tensorflow-for-poets-2/tf_files                                                         
TRAINING_DIR=/tmp/tf_files                                                                         
                                                                                                   
python tensorflow/tensorflow/examples/image_retraining/retrain.py \                                
  --bottleneck_dir=$TRAINING_DIR/bottlenecks \                                                     
  --how_many_training_steps=500 \                                                                  
  --model_dir=$TRAINING_DIR/models \                                                               
  --summaries_dir=$TRAINING_DIR/training_summaries/"${ARCHITECTURE}" \                             
  --output_graph=$TRAINING_DIR/retrained_graph.pb \                                                
  --output_labels=$TRAINING_DIR/retrained_labels.txt \                                             
  --architecture="${ARCHITECTURE}" \                                                               
  --image_dir=$DATA_DIR/flower_photos  

rm -f /$TRAINING_DIR/${ARCHITECTURE}.tflite                              
                        
tensorflow/bazel-bin/tensorflow/contrib/lite/toco/toco \                                           
  --input_file=$TRAINING_DIR/retrained_graph.pb \                                                  
  --input_format=TENSORFLOW_GRAPHDEF \                                                             
  --output_format=TFLITE \                                                                         
  --output_file=/$TRAINING_DIR/${ARCHITECTURE}.tflite \                                            
  --inference_type=QUANTIZED_UINT8 \                                                               
  --input_array=Placeholder \                                                                      
  --output_array=final_result \                                                                    
  --input_shape=1,224,224,3 \                                                                      
  --mean_value=128 \                                                                               
  --std_value=128                                                                                  
```

That should leave two files:
```
/tmp/tf_files/mobilenet_1.0_224_quantized.tflite
/tmp/tf_files/retrained_labels.txt
```
which you can use in the original demo app.

For floating-point inference the link given by @ecrasy should work.

**Comment by igsoft** [comment]
@andrehentz I'm trying to use your method but I'm not able to create the quantized.tflite. I'm using a docker with tf1.5 and in your second step with toco I received:
`toco --input_file=tf_files/retrained_graph.pb --input_format=TENSORFLOW_GRAPHDEF --output_format=TFLITE --output_file=tf_files/model.tflite --inference_type=QUANTIZED_UINT8 --input_array=Placeholder --output_array=final_result --input_shape=1,224,224,3 --mean_value=128 --std_value=128
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2018-02-12 14:30:20.126646: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting unsupported operation: Dequantize
2018-02-12 14:30:20.126818: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting unsupported operation: Dequantize
2018-02-12 14:30:20.127122: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting unsupported operation: Dequantize
2018-02-12 14:30:20.127511: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting unsupported operation: Dequantize
2018-02-12 14:30:20.127633: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting unsupported operation: Dequantize
2018-02-12 14:30:20.128115: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting unsupported operation: Dequantize
2018-02-12 14:30:20.128356: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting unsupported operation: Dequantize
2018-02-12 14:30:20.128786: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting unsupported operation: Dequantize
2018-02-12 14:30:20.129454: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting unsupported operation: Dequantize
2018-02-12 14:30:20.129759: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting unsupported operation: Dequantize
2018-02-12 14:30:20.132161: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 145 operators, 239 arrays (0 quantized)
2018-02-12 14:30:20.134624: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 1: 62 operators, 152 arrays (0 quantized)
2018-02-12 14:30:20.136101: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 2: 62 operators, 153 arrays (0 quantized)
2018-02-12 14:30:20.137529: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 3: 61 operators, 151 arrays (0 quantized)
2018-02-12 14:30:20.138834: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before pre-quantization graph transformations: 61 operators, 151 arrays (0 quantized)
2018-02-12 14:30:20.139734: F tensorflow/contrib/lite/toco/tooling_util.cc:1204] Array input, which is an input to the Conv operator producing the output array MobilenetV1/MobilenetV1/Conv2d_0/Relu6, is lacking min/max data, which is necessary for quantization. Either target a non-quantized output format, or change the input graph to contain min/max information, or pass --default_ranges_min= and --default_ranges_max= if you do not care about the accuracy of results.
Aborted` 
Am I doing something wrong?

**Comment by andrehentz** [comment]
@igsoft you might want to open a separate issue for that. Could you show the command lines you are using?

**Comment by vikoo** [comment]
@zhang13850588961 
your models are trained in Mobilenet with Float.

you can use the following link to make it work on the android demo app

https://stackoverflow.com/questions/47761514/tensorflow-lite-pretrained-model-does-not-work-in-android-demo/49271024#49271024

**Comment by araefr** [comment]
I have trained a custom model using DNN and tried to use TF_Lite for using that in Android. I'm using the same method in the demo app for loading the asset file. But I'm getting following error

`E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: revan.locationspeed, PID: 12072
                                                                     java.lang.RuntimeException: Unable to start activity ComponentInfo{revan.locationspeed/thambu.locationspeed.MainActivity}: java.lang.IllegalArgumentException: Contents of /dnn_frozen_graph.pb does not encode a valid TensorFlowLite model: Could not open '/dnn_frozen_graph.pb'.The model is not a valid Flatbuffer file
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3319)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3415)
                                                                         at android.app.ActivityThread.-wrap17(ActivityThread.java)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:148)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:7325)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                                      Caused by: java.lang.IllegalArgumentException: Contents of /dnn_frozen_graph.tflite does not encode a valid TensorFlowLite model: Could not open '/dnn_frozen_graph.tflite'.The model is not a valid Flatbuffer file
                                                                         at org.tensorflow.lite.NativeInterpreterWrapper.createModel(Native Method)
                                                                         at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:40)
                                                                         at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:35)
                                                                         at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:67)
                                                                         at thambu.locationspeed.MainActivity.onCreate(MainActivity.java:90)
                                                                         at android.app.Activity.performCreate(Activity.java:6904)
                                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1136)
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3266)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3415) 
                                                                         at android.app.ActivityThread.-wrap17(ActivityThread.java) 
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                         at android.os.Looper.loop(Looper.java:148) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:7325) 
                                                                         at java.lang.reflect.Method.invoke(Native Method)`


I used toco for conversion... Expecting guidance for succeeding this

**Comment by praneetloke** [comment]
@Revan007 not sure if you already did this but, for tflite files, you should tell gradle not to compress it. Add this:
```
aaptOptions {
        noCompress "tflite"
        noCompress "lite"
}
```
You can find this in the gradle files of the TF demo Android apps as well.

**Comment by CoCa520** [comment]
@andrehentz @
how can I run iOS camera demo with float .lite file？

**Comment by duplex143** [comment]
@andrehentz 
I used this `ARCHITECTURE=mobilenet_1.0_224_quantized` for training and got  `--output_graph=$TRAINING_DIR/retrained_graph.pb` file with some 85% accuracy on test images. But when I'm using this .pb file in https://codelabs.developers.google.com/codelabs/tensorflow-for-poets-2/ , I'm getting highly incorrect labels in predictions. 
Do I need to change anything when I'm using the code written for unquantised architectures for quantised architectures?

**Comment by nheidloff** [comment]
Hi @CoCa520 , here is how I got the iOS camera app to work for the tutorial: https://github.com/nheidloff/watson-deep-learning-tensorflow-lite
https://github.com/nheidloff/watson-deep-learning-tensorflow-lite/blob/master/ios-camera/CameraExampleViewController.mm#L256-L272

**Comment by gaojingwen945** [comment]
@andrehentz Sadly the approach you provided in the former comment does not work for me here...
I retrained my mobilenet_v1_1.0_224_quantized model, and then running with the following command, and it still reports the same error message as posted in the original question. It IS driving me crazy. Do you have any other ideas about this?
Here's my toco command, where retrained_graph.pb is my retrained model without freeze (also, a frozen model after freeze_graph does not work as well, which by the way, really confuses me that is freeze_graph necessary for converting to tflite?):

`toco \
  --graph_def_file=output_dir/retrained_graph.pb \
  --output_file=output_dir/optimized_graph.tflite \
  --input_format=TENSORFLOW_GRAPHDEF \
  --output_format=TFLITE \
  --inference_type=QUANTIZED_UINT8 \
  --inference_input_type=QUANTIZED_UINT8 \
  --input_array=input \
  --input_shape=1,224,224,3 \
  --output_array=final_result \
  --mean_value=128 \
  --std_dev_values=128 \
  --default_ranges_min=0 \
  --default_ranges_max=6 \
  --logtostderr '--v=2'`

> While full quantized training is still in the works, retraining an existing quantized mobilenet (currently only mobilenet_1.0_224_quantized) should work. You can follow the step in TensorFlow for Poets which I reproduce (slightly modified) here:

ARCHITECTURE=mobilenet_1.0_224_quantized                                                           
DATA_DIR=~/tensorflow-for-poets-2/tf_files                                                         
TRAINING_DIR=/tmp/tf_files                                                                         
                                                                                                   
python tensorflow/tensorflow/examples/image_retraining/retrain.py \                                
  --bottleneck_dir=$TRAINING_DIR/bottlenecks \                                                     
  --how_many_training_steps=500 \                                                                  
  --model_dir=$TRAINING_DIR/models \                                                               
  --summaries_dir=$TRAINING_DIR/training_summaries/"${ARCHITECTURE}" \                             
  --output_graph=$TRAINING_DIR/retrained_graph.pb \                                                
  --output_labels=$TRAINING_DIR/retrained_labels.txt \                                             
  --architecture="${ARCHITECTURE}" \                                                               
  --image_dir=$DATA_DIR/flower_photos  

rm -f /$TRAINING_DIR/${ARCHITECTURE}.tflite                              
                        
tensorflow/bazel-bin/tensorflow/contrib/lite/toco/toco \                                           
  --input_file=$TRAINING_DIR/retrained_graph.pb \                                                  
  --input_format=TENSORFLOW_GRAPHDEF \                                                             
  --output_format=TFLITE \                                                                         
  --output_file=/$TRAINING_DIR/${ARCHITECTURE}.tflite \                                            
  --inference_type=QUANTIZED_UINT8 \                                                               
  --input_array=Placeholder \                                                                      
  --output_array=final_result \                                                                    
  --input_shape=1,224,224,3 \                                                                      
  --mean_value=128 \                                                                               
  --std_value=128                                                                                  

That should create two files:

/tmp/tf_files/mobilenet_1.0_224_quantized.tflite
/tmp/tf_files/retrained_labels.txt

which you can use in the original demo app.

For floating-point inference the link given by @ecrasy should work.

**Comment by gaojingwen945** [comment]
Update: 
And, I retrained the mobilenet_1.0_224 model, the un-quantized version, and using toco to convert it to a QUANTIZED_UINT8 tflite file, it works, and the .tflite file is much smaller in size, which is 4.3M.
The command I use is as follows:

`IMAGE_SIZE=224`
`OUTPUT_NODE_NAME='final_result'
INPUT_TYPE="QUANTIZED_UINT8"`
`toco \
  --graph_def_file=$output_dir/$INPUT_FILE \
  --output_file=$output_dir/optimized_graph.lite \
  --input_format=TENSORFLOW_GRAPHDEF \
  --output_format=TFLITE \
  --inference_type=$INPUT_TYPE \
  --inference_input_type=$INPUT_TYPE \
  --input_array=input \
  --input_shape=1,"${IMAGE_SIZE}","${IMAGE_SIZE}",3 \
  --output_array=$OUTPUT_NODE_NAME \
  --mean_value=128 \
  --std_dev_values=128 \
  --default_ranges_min=0 \
  --default_ranges_max=6 \
  --logtostderr '--v=2'`

**Comment by efung** [comment]
For anyone wondering where the `--default_ranges_min=0` and `--default_ranges_max=6` values come from, see [this note](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/lite/toco/g3doc/cmdline_examples.md#use-dummy-quantization-to-try-out-quantized-inference-on-a-float-graph-) about dummy quantization, from the TOCO Command Line Examples documentation.

As they describe there, I got pretty poor accuracy after quantizing a retrained float MobileNet (the retrained model from the TensorFlow for Poets codelab)

**Comment by ouclbc** [comment]
converting unsupported operation decodejpeg
