### ISSUE TITLE
Error_Converting_TliteFormat

### ISSUE THREAD

**Issue by himsikha123** [tensorflow/tensorflow#15144]
.....................................................## System information##........................................................................
-Python -2.7.12
-OS -Ubuntu 16.04
-Tensorflow version-1.4.0
-Bazel version-0.8.0
     ......................................................##Description ###...............................................................
1. I went through the following link and 
=>https://codelabs.developers.google.com/codelabs/tensorflow-for-poets/#3
and successfully retrained the last layer of the model.

2. Now i was trying to use that retrained.pb file and convert into.tlite format.
=>https://github.com/tensorflow/tensorflow
--Downloaded the tensorflow-master directory.
--Install Bazel (0.8.0)
--Then, using the retrained.pb file,trying to do model format conversion
--Downloaded the checkpoints from 
=>https://github.com/tensorflow/models/blob/master/research/slim/nets/mobilenet_v1.md
But got stucked while running the command for conversion.[bazel-bin/tensorflow/python/tools/freeze_graph --input_graph=/home/ee210201/tensorflow-for-poets-2/tf_files/retrained_graph.pb --input_checkpoint=/tmp/checkpoints/mobilenet_v1_0.50_224.ckpt.data-00000-of-00001 --input_binary=true --output_graph=/tmp/checkpoints/frozen_mobilenet.pb  --output_node_names=Softmax}

.........................................................### Source code ##..........................................................................................
1. 
(tensorflow) root@pcz-ee210201:/u/tensorflow-master# bazel build -c opt --copt=-msse4.1 --copt=-msse4.2 tensorflow/python/tools:freeze_graph

=>INFO: Elapsed time: 1057.269s, Critical Path: 44.92s
INFO: Build completed successfully, 2109 total actions
.................................................................................................................................

2. But while running the below script [To convert into .tlite format] ,i was unable to resolved the following error?
(tensorflow) root@pcz-ee210201:/u/tensorflow-master# bazel-bin/tensorflow/python/tools/freeze_graph --input_graph=/home/ee210201/tensorflow-for-poets-2/tf_files/retrained_graph.pb --input_checkpoint=/tmp/checkpoints/mobilenet_v1_0.50_224.ckpt.data-00000-of-00001 --input_binary=true --output_graph=/tmp/checkpoints/frozen_mobilenet.pb  --output_node_names=Softmax

Error:::::::::::::::::::::::::::::::::::::::::
Traceback (most recent call last):
  File "/u/tensorflow-master/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/tools/freeze_graph.py", line 56, in <module>
    from tensorflow.python.tools import saved_model_utils
  File "/u/tensorflow-master/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/tools/saved_model_utils.py", line 21, in <module>
    from tensorflow.contrib.saved_model.python.saved_model import reader
  File "/u/tensorflow-master/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/contrib/__init__.py", line 82, in <module>
    from tensorflow.contrib.eager.python import tfe as eager
  File "/u/tensorflow-master/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/contrib/eager/python/tfe.py", line 75, in <module>
    from tensorflow.contrib.eager.python.datasets import Iterator
  File "/u/tensorflow-master/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/contrib/eager/python/datasets.py", line 23, in <module>
    from tensorflow.contrib.data.python.ops import prefetching_ops
  File "/u/tensorflow-master/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/contrib/data/python/ops/prefetching_ops.py", line 25, in <module>
    resource_loader.get_path_to_datafile("../../_prefetching_ops.so"))
  File "/u/tensorflow-master/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/contrib/util/loader.py", line 55, in load_op_library
    ret = load_library.load_op_library(path)
  File "/u/tensorflow-master/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename, status)
  File "/u/tensorflow-master/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))

=>tensorflow.python.framework.errors_impl.NotFoundError: /u/tensorflow-master/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/contrib/data/python/ops/../../_prefetching_ops.so: undefined symbol: _ZN6google8protobuf8internal26fixed_address_empty_stringB5cxx11E
.........................................................................................................................

Please let me know what does above error
--(tensorflow.python.framework.errors_impl.NotFoundError: --_ZN6google8protobuf8internal26fixed_address_empty_stringB5cxx11E)
means and how to solved it.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by himsikha123** [comment]
Have I written custom code: N/A
OS Platform and Distribution: UBUNTU 16.04LTS
TensorFlow installed from:  https://www.tensorflow.org/install/install_linux
                                           https://www.tensorflow.org/install/install_linux#InstallingVirtualenv
CUDA/cuDNN version : N/A
GPU model and memory: N/A
Exact command to reproduce:
 1.https://codelabs.developers.google.com/codelabs/tensorflow-for-poets/#3
( generated the new pb file from the above site)=>retranined.pb obtained
2. wanted to convert .tlite format.I have followed the below link:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/lite/README.md
Step 2. Model format conversion
Graph freezing can be done using the command below (and modifying the arguments appropriately)

bazel build tensorflow/python/tools:freeze_graph

bazel-bin/tensorflow/python/tools/freeze_graph\
    --input_graph=/tmp/retrained.pb \
    --input_checkpoint=/tmp/checkpoints/mobilenet-10202.ckpt \
    --input_binary=true 
       --output_graph=/tmp/frozen_mobilenet_v1_224.pb \
    --output_node_names=MobileNet/Softmax

**Comment by himsikha123** [comment]
After running the 2nd command ,i got error as:
tensorflow.python.framework.errors_impl.NotFoundError: /u/tensorflow-master/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/contrib/data/python/ops/../../_prefetching_ops.so: undefined symbol: _ZN6google8protobuf8internal26fixed_address_empty_stringB5cxx11E

**Comment by himsikha123** [comment]
Please let me know if you want any other information to solved the problem.

**Comment by euntaik** [comment]
I think this might be a protobuf version problem. protobuf 3.5.0.post1 works fine.

**Comment by himsikha123** [comment]
Please someone guide me how can i convert my retrained model (.pb file) into .tflite format so that i can run on the  android device.

**Comment by drpngx** [comment]
Are you able to run the network correctly without freeze graph? Can you use `nm` on the tensorflow shared object and see which one is defined? Did you try the protobuf as suggested by @euntaik ?

**Comment by himsikha123** [comment]
Hi,
yes,its running correctly without freeze graph.
-> protoc --version
libprotoc 2.6.1
 I am trying now with protobuf 3.5.0 version and shall update the same.

**Comment by himsikha123** [comment]
Actually,my current version of protobuf: 3.0.0 ,so i was trying to install 3.5.0 version but got the following error:

root@pcz-ee210201:/u/protobuf-master/python# pip install protobu
Collecting protobu
  Could not find a version that satisfies the requirement protobu (from versions: )
No matching distribution found for protobu

**Comment by himsikha123** [comment]
->I have downloaded the protobuf 3.5.0 from the below link :
https://github.com/google/protobuf/releases

->and followed the following steps to install from
https://github.com/google/protobuf/tree/master/python
->Then i tried to run the below cmd:
root@pcz-ee210201:/u/tensorflow-master#  bazel-bin/tensorflow/python/tools/freeze_graph --input_graph=/home/ee210201/tensorflow-for-poets-2/tf_files/retrained_graph.pb --input_checkpoint=/tmp/checkpoints/mobilenet_v1_0.50_224.ckpt.data-00000-of-00001 --input_binary=true --output_graph=/tmp/checkpoints/frozen_mobilenet.pb --output_node_names=Softmax

-> But getting the same error:
tensorflow.python.framework.errors_impl.NotFoundError: /u/tensorflow-master/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/contrib/data/python/ops/../../_prefetching_ops.so: undefined symbol: _ZN6google8protobuf8internal26fixed_address_empty_stringB5cxx11E
Is my approach is alright?

**Comment by himsikha123** [comment]
I have installed  protobuf-3.5.0:
  /usr/local/lib/python2.7/dist-packages/protobuf-3.5.0-py2.7.egg
But still its showing the same error.Please guide me in order to resolved this.

**Comment by himsikha123** [comment]
Please suggest me what should i try to resolved the issue.

**Comment by madenmud** [comment]
I have same problem. No updates?

**Comment by himsikha123** [comment]
I am unable to resolve the issue.

**Comment by kirilg** [comment]
We started seeing the same error in TensorFlow Serving at around the same time when running an example client - https://github.com/tensorflow/serving/issues/684

```
tensorflow.python.framework.errors_impl.NotFoundError: /tensorflow/bazel-bin/tensorflow/examples/image_retraining/retrain.runfiles/org_tensorflow/tensorflow/contrib/data/python/ops/../../_prefetching_ops.so: undefined symbol: _ZN6google8protobuf8internal26fixed_address_empty_stringB5cxx11E
```

Any ideas?

**Comment by himsikha123** [comment]
Sorry,i don't have any idea.

**Comment by himsikha123** [comment]
I am following the below steps from [https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/lite] and obtained the retrrained.pb file by retraining the model(tensorflow for poets) and now wanted to convert .pb to .tlite format so that i can used in android phone.

Step 2. Model format conversion:
Freeze Graph

To use this .pb GraphDef file within TensorFlow Lite, the application developer will need checkpoints containing trained weight parameters. The .pb contains only the structure of the graph. The process of merging the checkpoint values with the graph structure is known as "freezing" the graph.

The developer should know where the checkpoints folder is present or checkpoints can also be downloaded for a pre-trained model (Example: Here is a link to the MobileNets).

Graph freezing can be done using the command below (and modifying the arguments appropriately)

bazel build tensorflow/python/tools:freeze_graph

bazel-bin/tensorflow/python/tools/freeze_graph\
    --input_graph=/tmp/mobilenet_v1_224.pb \
    --input_checkpoint=/tmp/checkpoints/mobilenet-10202.ckpt \
    --input_binary=true --output_graph=/tmp/frozen_mobilenet_v1_224.pb \
    --output_node_names=MobileNet/Predictions/Reshape_1

**Comment by madenmud** [comment]
About the link error of  tensorflow/serving#684 ,
I fixed adding deps on BUILD file under "./tensorflow/tensorflow/contrib/data/" as below.

` 27
 28 tf_custom_op_library(
 29     name = "_prefetching_ops.so",
 30     srcs = ["ops/prefetching_ops.cc"],
 31     deps = [
 32             "//tensorflow/contrib/data/kernels:prefetching_kernels",
 33             **"@protobuf_archive//:protobuf",**
 34     ],
 35 )
`

But it makes core dump...



Training model...
Extracting /tmp/train-images-idx3-ubyte.gz
Extracting /tmp/train-labels-idx1-ubyte.gz
Extracting /tmp/t10k-images-idx3-ubyte.gz
Extracting /tmp/t10k-labels-idx1-ubyte.gz
2017-12-20 15:40:15.177713: I external/org_tensorflow/tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2017-12-20 15:40:15.584699: F external/org_tensorflow/tensorflow/core/framework/op.cc:54] Non-OK-status: RegisterAlreadyLocked(op_data_factory) status: Already exists: Op with name _Arg
 (core dumped)

**Comment by brentian** [comment]
save problem when querying a service:

**Comment by brentian** [comment]
Get the same error running a query client

root@ubuntu:~/tools/tensorflow-serving$ bazel-bin/tensorflow_serving/example/inception_client --server=localhost:9000 --image=/root/data/flower_photos/roses/5529341024_0c35f2657d.jpg
`Traceback (most recent call last):
  File "/root/tools/tensorflow-serving/bazel-bin/tensorflow_serving/example/inception_client.runfiles/tf_serving/tensorflow_serving/example/inception_client.py", line 56, in <module>
    tf.app.run()
  File "/root/tools/tensorflow-serving/bazel-bin/tensorflow_serving/example/inception_client.runfiles/org_tensorflow/tensorflow/python/platform/app.py", line 124, in run
    _sys.exit(main(argv))
  File "/root/tools/tensorflow-serving/bazel-bin/tensorflow_serving/example/inception_client.runfiles/tf_serving/tensorflow_serving/example/inception_client.py", line 50, in main
    tf.contrib.util.make_tensor_proto(data, shape=[1]))
  File "/root/tools/tensorflow-serving/bazel-bin/tensorflow_serving/example/inception_client.runfiles/org_tensorflow/tensorflow/python/util/lazy_loader.py", line 53, in __getattr__
    module = self._load()
  File "/root/tools/tensorflow-serving/bazel-bin/tensorflow_serving/example/inception_client.runfiles/org_tensorflow/tensorflow/python/util/lazy_loader.py", line 42, in _load
    module = importlib.import_module(self.__name__)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/root/tools/tensorflow-serving/bazel-bin/tensorflow_serving/example/inception_client.runfiles/org_tensorflow/tensorflow/contrib/__init__.py", line 82, in <module>
    from tensorflow.contrib.eager.python import tfe as eager
  File "/root/tools/tensorflow-serving/bazel-bin/tensorflow_serving/example/inception_client.runfiles/org_tensorflow/tensorflow/contrib/eager/python/tfe.py", line 75, in <module>
    from tensorflow.contrib.eager.python.datasets import Iterator
  File "/root/tools/tensorflow-serving/bazel-bin/tensorflow_serving/example/inception_client.runfiles/org_tensorflow/tensorflow/contrib/eager/python/datasets.py", line 23, in <module>
    from tensorflow.contrib.data.python.ops import prefetching_ops
  File "/root/tools/tensorflow-serving/bazel-bin/tensorflow_serving/example/inception_client.runfiles/org_tensorflow/tensorflow/contrib/data/python/ops/prefetching_ops.py", line 25, in <module>
    resource_loader.get_path_to_datafile("../../_prefetching_ops.so"))
  File "/root/tools/tensorflow-serving/bazel-bin/tensorflow_serving/example/inception_client.runfiles/org_tensorflow/tensorflow/contrib/util/loader.py", line 55, in load_op_library
    ret = load_library.load_op_library(path)
  File "/root/tools/tensorflow-serving/bazel-bin/tensorflow_serving/example/inception_client.runfiles/org_tensorflow/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename, status)
  File "/root/tools/tensorflow-serving/bazel-bin/tensorflow_serving/example/inception_client.runfiles/org_tensorflow/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: /root/tools/tensorflow-serving/bazel-bin/tensorflow_serving/example/inception_client.runfiles/org_tensorflow/tensorflow/contrib/data/python/ops/../../_prefetching_ops.so: undefined symbol: _ZN6google8protobuf8internal26fixed_address_empty_stringE`

**Comment by ChaosPredictor** [comment]
Same here, on ubuntu 16.04.
compiled with:
bazel build -c opt --copt=-msse4.1 --copt=-msse4.2 tensorflow/python/tools:freeze_graph
from [here](https://github.com/tensorflow/tensorflow/issues/14610)

**Comment by manjunaths** [comment]
I have the same issue. It seems this issue was introduced after this commit (https://github.com/tensorflow/tensorflow/commit/cd81bc8e09c7f551911276c5bfaafa6930f1961f).

**Comment by fengdragon** [comment]
@manjunaths Got the same issue, have you solved it using the commit u mentioned? Thx!

**Comment by manjunaths** [comment]
@fengdragon In my specific case that problem disappeared, but I am getting a segfault. I do not know if the segfault is because of the change or some other new issue that I have.

**Comment by tensorflowbutler** [comment]
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @aselle: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by KhabarlakKonstantin** [comment]
I had this issue with Tensorflow 1.5, but everything seems to be working fine as of 1.6-rc. Both versions were compiled from sources

**Comment by xtr33me** [comment]
I have tried on both r1.5 and r1.6 and I am getting the same error when trying to run my client.  I tried to build r1.4 but was dealing with a number of bazel related issues that had answers online aligned with upgrading to the newer versions of TF. Going to try running my model in docker to see if I have any better luck.

> Traceback (most recent call last):
>   File "/media/daniel/Data/serving/bazel-bin/tensorflow_serving/example/sentiment_client.runfiles/tf_serving/tensorflow_serving/example/sentiment_client.py", line 107, in <module>
>     tf.app.run()
>   File "/media/daniel/Data/serving/bazel-bin/tensorflow_serving/example/sentiment_client.runfiles/org_tensorflow/tensorflow/python/platform/app.py", line 126, in run
>     _sys.exit(main(argv))
>   File "/media/daniel/Data/serving/bazel-bin/tensorflow_serving/example/sentiment_client.runfiles/tf_serving/tensorflow_serving/example/sentiment_client.py", line 97, in main
>     tf.contrib.util.make_tensor_proto(tf.convert_to_tensor("This is awesome"), shape=[1]))
>   File "/media/daniel/Data/serving/bazel-bin/tensorflow_serving/example/sentiment_client.runfiles/org_tensorflow/tensorflow/python/util/lazy_loader.py", line 53, in __getattr__
>     module = self._load()
>   File "/media/daniel/Data/serving/bazel-bin/tensorflow_serving/example/sentiment_client.runfiles/org_tensorflow/tensorflow/python/util/lazy_loader.py", line 42, in _load
>     module = importlib.import_module(self.__name__)
>   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
>     __import__(name)
>   File "/media/daniel/Data/serving/bazel-bin/tensorflow_serving/example/sentiment_client.runfiles/org_tensorflow/tensorflow/contrib/__init__.py", line 84, in <module>
>     from tensorflow.contrib.eager.python import tfe as eager
>   File "/media/daniel/Data/serving/bazel-bin/tensorflow_serving/example/sentiment_client.runfiles/org_tensorflow/tensorflow/contrib/eager/python/tfe.py", line 78, in <module>
>     from tensorflow.contrib.eager.python.datasets import Iterator
>   File "/media/daniel/Data/serving/bazel-bin/tensorflow_serving/example/sentiment_client.runfiles/org_tensorflow/tensorflow/contrib/eager/python/datasets.py", line 23, in <module>
>     from tensorflow.contrib.data.python.ops import prefetching_ops
>   File "/media/daniel/Data/serving/bazel-bin/tensorflow_serving/example/sentiment_client.runfiles/org_tensorflow/tensorflow/contrib/data/python/ops/prefetching_ops.py", line 25, in <module>
>     resource_loader.get_path_to_datafile("../../_prefetching_ops.so"))
>   File "/media/daniel/Data/serving/bazel-bin/tensorflow_serving/example/sentiment_client.runfiles/org_tensorflow/tensorflow/contrib/util/loader.py", line 55, in load_op_library
>     ret = load_library.load_op_library(path)
>   File "/media/daniel/Data/serving/bazel-bin/tensorflow_serving/example/sentiment_client.runfiles/org_tensorflow/tensorflow/python/framework/load_library.py", line 58, in load_op_library
>     lib_handle = py_tf.TF_LoadLibrary(library_filename, status)
>   File "/media/daniel/Data/serving/bazel-bin/tensorflow_serving/example/sentiment_client.runfiles/org_tensorflow/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
>     c_api.TF_GetCode(self.status.status))
> tensorflow.python.framework.errors_impl.NotFoundError: /media/daniel/Data/serving/bazel-bin/tensorflow_serving/example/sentiment_client.runfiles/org_tensorflow/tensorflow/contrib/data/python/ops/../../_prefetching_ops.so: undefined symbol: _ZN6google8protobuf8internal9ArenaImpl10AddCleanupEPvPFvS3_E

**Comment by tensorflowbutler** [comment]
Nagging Assignee @aselle: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @aselle: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by 15940260868** [comment]
@himsikha123 Have you got the solution? I have the same error. I'll very appreciate your help

**Comment by usptact** [comment]
I had this issue because I installed "libtensorflow_framework.so" in my system. Removing this library out of "/usr/local/lib" solved this problem for me.
