### ISSUE TITLE
Unable access S3 using the S3 filesystem

### ISSUE THREAD

**Issue by chris-smith-zocdoc** [tensorflow/tensorflow#15159]
------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes 
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  docker container based on centos7
- **TensorFlow installed from (source or binary)**: binary, from pip
- **TensorFlow version (use command below)**: ('v1.4.0-rc1-11-g130a514', '1.4.0')
- **Python version**: 2.7.5
- **Bazel version (if compiling from source)**: n/a
- **GCC/Compiler version (if compiling from source)**: n/a
- **CUDA/cuDNN version**: n/a
- **GPU model and memory**: n/a
- **Exact command to reproduce**:
```
from tensorflow.python.lib.io import file_io
file_io.stat('s3://datasets.elasticmapreduce/ngrams/books/20090715/eng-1M/1gram/data')
```

### Describe the problem
I'm unable to read files using the s3 filesystem. I believe my example above should work, please correct my usage of the api if not. I tried using both an object in a public bucket and one in a private bucket that I have credentials in my ~/.aws/config for. 

I'm not quite sure what the error is, or how to diagnose it further. Setting the log level to Debug had no effect. `tf.logging.set_verbosity(tf.logging.DEBUG)` 

### Source code / logs

Traceback from file_io.stat
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/tensorflow/python/lib/io/file_io.py", line 540, in stat
    return file_statistics
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: Object s3://datasets.elasticmapreduce/ngrams/books/20090715/eng-1M/1gram/data does not exist
```

Using the aws cli, you can verify the object exists 
```
aws s3 ls s3://datasets.elasticmapreduce/ngrams/books/20090715/eng-1M/1gram/data
```

**Comment by reedwm** [comment]
Hmmm, the 2-line program works when I try it on my workstation. Did you try the aws cli command line in the docker container, or outside of it?

/CC @drpngx, any ideas?

**Comment by chris-smith-zocdoc** [comment]
The cli command works both from without and outside the container. It might be worthwhile to try and reproduce on a common docker image. Do you have one that you'd recommend? 

In my current setup, I'm running the container using docker for mac with a mounted volume for my aws credentials

**Comment by reedwm** [comment]
Good idea. The TensorFlow docker images are [here](https://hub.docker.com/r/tensorflow/tensorflow/tags/). The following commands worked for me:

```
docker run -it tensorflow/tensorflow:1.4.0 bash
python
>>> from tensorflow.python.lib.io import file_io
>>> file_io.stat('s3://datasets.elasticmapreduce/ngrams/books/20090715/eng-1M/1gram/data')
```
I ran this on Ubuntu 14.04 and didn't use any AWS credentials. I don't think the host OS matters, but try without the credentials to match what I did.

**Comment by drpngx** [comment]
Right, I'm guessing it's an auth issue. Some of these things are env variable controlled. The cli also drops files in the home directory. Is it a public bucket?

**Comment by chris-smith-zocdoc** [comment]
I can confirm official tensorflow docker image works correctly for both public and private buckets. 

The below Dockerfile is the smallest repro of the issue. Are there additional dependencies I need to install? Does the pip installation ship with the s3 filesystem? 

```
docker build -t tf-15159:latest .
docker run --rm -it tf-15159:latest
```

```
FROM centos:7

RUN yum -y update && \
    yum -y install epel-release && \
    yum -y install python2-pip

RUN pip install 'tensorflow == 1.4.0'

CMD python -c "from tensorflow.python.lib.io import file_io; file_io.stat('s3://datasets.elasticmapreduce/ngrams/books/20090715/eng-1M/1gram/data')"
```

**Comment by drpngx** [comment]
Can you try `env` to see what you have defined (please don't paste your secret key here).

**Comment by chris-smith-zocdoc** [comment]
Heres my environment variables within the container 

```
[root@af2f2940e30a /]# env
HOSTNAME=af2f2940e30a
TERM=xterm
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;05;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=01;36:*.au=01;36:*.flac=01;36:*.mid=01;36:*.midi=01;36:*.mka=01;36:*.mp3=01;36:*.mpc=01;36:*.ogg=01;36:*.ra=01;36:*.wav=01;36:*.axa=01;36:*.oga=01;36:*.spx=01;36:*.xspf=01;36:
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/
SHLVL=1
HOME=/root
no_proxy=*.local, 169.254/16
_=/usr/bin/env
[root@af2f2940e30a /]#
```

**Comment by chris-smith-zocdoc** [comment]
For comparison, the env inside the tensorflow/tensorflow:1.4.0 container

```
HOSTNAME=2b58ca0af29e
TERM=xterm
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/notebooks
SHLVL=1
HOME=/root
no_proxy=*.local, 169.254/16
_=/usr/bin/env
```

**Comment by chris-smith-zocdoc** [comment]
Please note, that without credentials you must pass the `--no-sign-request` option to the cli. So that would look like this

```
pip install awscli

aws s3 ls s3://datasets.elasticmapreduce/ngrams/books/20090715/eng-1M/1gram/data --region us-east-1 --no-sign-request
```

This works correctly in both containers. 

Is there a way to enable debug logging for the s3 filesystem? It would be useful to look at the actual requests it is making

**Comment by drpngx** [comment]
The code is [here](https://www.github.com/tensorflow/tensorflow/blob/master/tensorflow/core/platform/s3/s3_file_system.cc#L404) but there is no debugging info, unless the AWS toolkit prints something.

If memory serves, there was a perl script cli that you could tweak to dump the header. If you fixed up the date/time field then you could compare side-by-side with your implementation.

The code does use `.WithKey()`. @yongtang any suggestion?

**Comment by quaeler** [comment]
@drpngx (sorry if this is what you're saying - being a pedant to assure clarity) `.WithKey()` refers to the object key which is basically the path & file name within the bucket, as opposed to being a key related to authentication / credentials.

**Comment by quaeler** [comment]
@chris-smith-zocdoc it is something peculiar to CentOS 7 or the Python dot-dot version therein.

This Dockerfile:
```Dockerfile
FROM ubuntu:16.04

RUN apt-get update && apt-get install -y --no-install-recommends \
        ca-certificates \
        curl \
        python \
        && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN curl -O https://bootstrap.pypa.io/get-pip.py && \
    python get-pip.py && \
    rm get-pip.py

RUN pip install 'tensorflow == 1.4.0'

CMD sleep infinity
```
when built and run (attaching a bash shell, running Python:
```
Python 2.7.12 (default, Nov 20 2017, 18:23:56) 
[GCC 5.4.0 20160609] on linux2
```
) works fine stat'ing the s3 file you cite, where as this Dockerfile
```Dockerfile
FROM centos:7

RUN yum -y update && \
    yum -y install \
        ca-certificates \
        curl \
        python

RUN curl -O https://bootstrap.pypa.io/get-pip.py && \
    python get-pip.py && \
    rm get-pip.py

RUN pip install 'tensorflow == 1.4.0'

CMD sleep infinity
```
when built and run (attaching a bash shell, running Python:
```
Python 2.7.5 (default, Aug  4 2017, 00:39:18) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)] on linux2
```
) produces the error you cite.

**Comment by chris-smith-zocdoc** [comment]
Hmm, not sure what you want to do with this issue, but I'll move over to an ubuntu based image

**Comment by yongtang** [comment]
I think adding AWS logging to TensorFlow's logging system might help. Will take a look and see if I can do something about it.

**Comment by yongtang** [comment]
Added a PR #15493 for the S3 logging. Please take a look if interested.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue? Please update the label and/or status accordingly.

**Comment by drpngx** [comment]
PR merged. Thank you!
