### ISSUE TITLE
DataLossError : Checksum does not match

### ISSUE THREAD

**Issue by PumayHui** [tensorflow/tensorflow#15203]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:windows 7 professional,64bit
- **TensorFlow installed from (source or binary)**:binary
- **TensorFlow version (use command below)**:1.3.0
- **Python version**: 3.6.2
- **Bazel version (if compiling from source)**:N/A
- **GCC/Compiler version (if compiling from source)**:N/A
- **CUDA/cuDNN version**:N/A
- **GPU model and memory**:N/A
- **Exact command to reproduce**:N/A

### Describe the problem
I trained on Ubuntu16.04 to get the model, and then restore the model on  Windows7 Professional, but it occured such a mistake:

`DataLossError (see above for traceback): Checksum does not match: stored 1713499277 vs. calculated on the restored bytes 1894941567`

`[Node: save/RestoreV2_282 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"]]`

**Both machines have the same version of python and TensorFlow, and the model tested in another machine succeed, but this machine failed**, how to solve it? Thank you!

### Source code / logs

```
Traceback (most recent call last):
  File "D:/tensorboxPy3/evaluate.py", line 138, in <module>
    main()
  File "D:/tensorboxPy3/evaluate.py", line 117, in main
    get_results(args, H, os.path.dirname(args.datadir))
  File "D:/tensorboxPy3/evaluate.py", line 59, in get_results
    saver.restore(sess, args.weights)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1560, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 895, in run
    run_metadata_ptr)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1321, in _do_run
    options, run_metadata)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.DataLossError: Checksum does not match: stored 1713499277 vs. calculated on the restored bytes 1894941567
	 [[Node: save/RestoreV2_282 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_282/tensor_names, save/RestoreV2_282/shape_and_slices)]]

Caused by op 'save/RestoreV2_282', defined at:
  File "D:/tensorboxPy3/evaluate.py", line 138, in <module>
    main()
  File "D:/tensorboxPy3/evaluate.py", line 117, in main
    get_results(args, H, os.path.dirname(args.datadir))
  File "D:/tensorboxPy3/evaluate.py", line 55, in get_results
    saver = tf.train.Saver()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1140, in __init__
    self.build()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1172, in build
    filename=self._filename)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 688, in build
    restore_sequentially, reshape)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 407, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 247, in restore_op
    [spec.tensor.dtype])[0])
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_io_ops.py", line 663, in restore_v2
    dtypes=dtypes, name=name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

DataLossError (see above for traceback): Checksum does not match: stored 1713499277 vs. calculated on the restored bytes 1894941567
	 [[Node: save/RestoreV2_282 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_282/tensor_names, save/RestoreV2_282/shape_and_slices)]]
```

`Process finished with exit code 1`

**Comment by reedwm** [comment]
@martinwicke any ideas what the problem could be?

**Comment by PumayHui** [comment]
@reedwm Any updates? Thanks!

**Comment by zxczhkzxc** [comment]
I also meet this,when i use tensorflow object detection API; i training the model more steps,the mistake missing,i guess the reason is  that tf required the trained models at least  a value,we need to reach it

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue? Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by martinwicke** [comment]
Ok, I don't know what to do here, without a repro we can work from. Please reopen this is someone has more information.

**Comment by lcvcl** [comment]
i meet the same problem

**Comment by NicolasKun** [comment]
same probleam on Windows10 / tensorflow-gpu-1.2 / python3.6.6

**Comment by xxAVOGADROxx** [comment]
The same problem Ubunutu 18.04, python2.7, tensorflow-1.31,1

**Comment by siddas27** [comment]
The same problem Ubuntu 18.04, python3.7, tensorflow-1.31.1
