### ISSUE TITLE
Can tensorflow support slicing tensor every N element

### ISSUE THREAD

**Issue by Ian09** [tensorflow/tensorflow#1524]
Slicing an array every N elements is a basic function of numpy or python list. However, I found that tensorflow doesn't support it. For example,

a = tf.constant(np.random.rand(3,100))
b = a[:,::4]
Traceback (most recent call last):
  File "/Applications/Eclipse.app/Contents/Eclipse/plugins/org.python.pydev_4.3.0.201508182223/pysrc/pydevd_exec.py", line 3, in Exec
    exec exp in global_vars, local_vars
  File "<console>", line 1, in <module>
  File "/Users/yin.zheng/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 131, in _SliceHelper
    "Steps other than 1 are not currently supported")
NotImplementedError: Steps other than 1 are not currently supported

I wonder that how can we use slicing on tensor to select every N elements (rows or lines)?

Best wishes 
Yin

**Comment by mrry** [comment]
At present this doesn't work, unless you write some complicated code that uses `tf.transpose()` and `tf.gather()` (euch). @ebrevdo is working on generalizing the slicing code as part of #206, so I'll merge this issue with that one.
