### ISSUE TITLE
vm compiled tensorflow - libmklml_intel.so ImportError

### ISSUE THREAD

**Issue by ic0n** [tensorflow/tensorflow#15252]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 16.04 VM
- **TensorFlow installed from (source or binary)**:
Source
- **TensorFlow version (use command below)**:
Branch `r1.4` and branch `master`
- **Python version**: 
3.6.3
- **Bazel version (if compiling from source)**:
Build label: 0.8.1 (Install using apt repository)
- **GCC/Compiler version (if compiling from source)**:
gcc-6 (Ubuntu 6.4.0-10ubuntu1~16.04.york0) 6.4.0 20171112

- **Exact command to reproduce**:
python -c "import tensorflow as tf;"

### Describe the problem
After compiling Tensorflow from source with tutorial: `https://www.tensorflow.org/install/install_sources` and install the compiled pip package, I import tensorflow on python console and get those errors:

~~~
python -c "import tensorflow as tf;"
Traceback (most recent call last):
  File "/home/potatoman/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/potatoman/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/potatoman/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/potatoman/anaconda3/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/home/potatoman/anaconda3/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libmklml_intel.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/potatoman/anaconda3/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/home/potatoman/anaconda3/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/potatoman/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 73, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/potatoman/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/potatoman/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/potatoman/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/potatoman/anaconda3/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/home/potatoman/anaconda3/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libmklml_intel.so: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
~~~

My machine is a headless KVM virtual machine running on a ubuntu 17.10, btw.

I figure out where the problem is somehow, which is the pip packaging script don't include those mkl so files, and in my case, replace `_solib_k8` in script `tensorflow/tools/pip_package/setup.py` at line 185 with `_solib_local` solves the issue.

**Comment by drpngx** [comment]
OK, since you have a fix, would you mind sending a PR?

/CC: @gunan

**Comment by ic0n** [comment]
@drpngx  PR #15253 sent, not very clean though. 

oh, there's a related PR #14709 .

**Comment by drpngx** [comment]
Thanks!

**Comment by ic0n** [comment]
Looks like PR #14709 had fix my problem, closing this issue now.
