### ISSUE TITLE
Library not loaded: /usr/lib/libc++.1.dylib

### ISSUE THREAD

**Issue by mrob27** [tensorflow/tensorflow#153]
When trying to run an example, as given in the [instructions](http://tensorflow.org/get_started/os_setup.md#virtualenv_install), the command "python tensorflow/models/image/mnist/convolutional.py" does not work because that is not the proper path to convolutional.py.

If I use the proper path, I get this error:

```
 $ source bin/activate
(tensorflow) $ python lib/python2.7/site-packages/tensorflow/models/image/mnist/convolutional.py
Traceback (most recent call last):
  File "lib/python2.7/site-packages/tensorflow/models/image/mnist/convolutional.py", line 12, in <module>
    import tensorflow.python.platform
  File "/Users/munafo/devt/tensorflow/lib/python2.7/site-packages/tensorflow/__init__.py", line 4, in <module>
    from tensorflow.python import *
  File "/Users/munafo/devt/tensorflow/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 22, in <module>
    from tensorflow.python.client.client_lib import *
  File "/Users/munafo/devt/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/client_lib.py", line 35, in <module>
    from tensorflow.python.client.session import InteractiveSession
  File "/Users/munafo/devt/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 11, in <module>
    from tensorflow.python import pywrap_tensorflow as tf_session
  File "/Users/munafo/devt/tensorflow/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/Users/munafo/devt/tensorflow/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
ImportError: dlopen(/Users/munafo/devt/tensorflow/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so, 2): Library not loaded: /usr/lib/libc++.1.dylib
  Referenced from: /Users/munafo/devt/tensorflow/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so
  Reason: image not found
(tensorflow) $ 
```

I have a complete index of all files on my machine, and there is no "libc++.1.dylib" anywhere. I do have a "/usr/lib/libstdc++.6.dylib".

MacOS 10.6.8, Python 2.7.3, virtualenv 1.7.1.2

**Comment by ebrevdo** [comment]
Can you try to build the pip package from source following the instructions on tensorflow.org, install that, and report back?

**Comment by mrob27** [comment]
[Here](http://tensorflow.org/get_started/os_setup.md#installing_from_sources) are the instructions. As you can see, the first step is to install [Bazel](http://bazel.io/docs/install.html), and their fist step is to install JDK 8. The JDK 8 installers are [here](http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html). I got "JDK 8 Update 65.pkg", dated 2015 Oct 6. It claims it needs "Mac OS X 10.7.3 or later" to install. Even JDK 7 [makes the same claim](https://docs.oracle.com/javase/7/docs/webnotes/install/mac/mac-jdk.html).

**Comment by vrv** [comment]
Closing due to inactivity -- reopen if still interested and the problem hasn't been fixed in the past few months.

**Comment by sgrinich** [comment]
I am trying to set up TensorFlow and am receiving this same error both with a standard pip install and also using virtual env. Has any progress been made @vrv @mrob27 @ebrevdo ? Any tips much appreciated to get started with the appealing library.

**Comment by mrob27** [comment]
I got stuck at a later stage of the process, and switched to non-TF
approach to deep learning.

On Monday, 19 September 2016, Stephen Grinich <notifications@github.com>
wrote:

> I am trying to set up TensorFlow and am receiving this same error both
> with a standard pip install and also using virtual env. Has any progress
> been made @vrv <https://github.com/vrv> @mrob27
> <https://github.com/mrob27> @ebrevdo <https://github.com/ebrevdo> ? Any
> tips much appreciated to get started with the appealing library.
>


-- 
  Robert Munafo  --  mrob.com
  Follow me at: gplus.to/mrob - fb.com/mrob27 - twitter.com/mrob_27 -
mrob27.wordpress.com - youtube.com/user/mrob143 - rilybot.blogspot.com

**Comment by aselle** [comment]
I am closing this bug due to lack of recent activity. For future searchwes, the original poster posted that they were using Mac OS 10.6. which was subsumed by Mac OS Lion in 2011. libc++ was not included in Mac OS Snow Leopward because Apple had not switched to Clang and libc++ yet. Our binaries are for a single version of Mac OS (El Capitan currently). For the subsequent posters, please file a new bug with your relevant system details.

**Comment by kaustubh2024** [comment]
I am using handwrite to create my own font. I have MacBook with macOS Big Sur, 11.7.10 version. I'm getting following error:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/bin/handwrite", line 5, in <module>
    from handwrite.cli import main
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/handwrite/__init__.py", line 1, in <module>
    from handwrite.sheettopng import SHEETtoPNG
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/handwrite/sheettopng.py", line 5, in <module>
    import cv2
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/cv2/cv2.abi3.so, 2): Symbol not found: __ZNSt3__113basic_filebufIcNS_11char_traitsIcEEE4openEPKcj
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/cv2/.dylibs/libvmaf.1.dylib (which was built for Mac OS X 12.0)
  Expected in: /usr/lib/libc++.1.dylib

I can't upgrade Mac OS to OS X 12
