### ISSUE TITLE
Tensorflow AOT examples fail to compile

### ISSUE THREAD

**Issue by uziela** [tensorflow/tensorflow#15338]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 'v1.3.0-rc1-5779-g441571a', '1.4.0'
- **Python version**: 2.7.12
- **Bazel version (if compiling from source)**: 0.8.1
- **GCC/Compiler version (if compiling from source)**: GCC 5.4.0
- **CUDA/cuDNN version**: CUDA 8.0, CUDNN 6.0.21
- **GPU model and memory**: GeForce GTX 1080, 8GB
- **Exact command to reproduce**: cd tensorflow/compiler/aot/tests ; bazel clean ; bazel build all_tests &>gcc5.log

### Describe the problem

I am trying to compile AOT examples, but the compilation fails. I tried to use two different compiler versions (GCC 5.4 and GCC 4.8), but I get errors with both versions. I also tried adding --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" option when using bazel with GCC 5.4, but it doesn't help.

So the exact commands commands were:
bazel build all_tests &>gcc5.log
bazel build --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" all_tests &>gcc5_abi0.log
bazel build all_tests  # Using GCC 4.8, I copied the output manually to gcc_4.8.txt

Tensorflow source code itself was build without any problems both with GCC 5.4 and GCC 4.8. I have built the two versions in separate python virtual environments and afterwards tried to compile aot tests with the corresponding GCC version. I used --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" option when building tensorflow source with GCC 5.4.

### Source code / logs
The logs are attached.
[gcc5.log](https://github.com/tensorflow/tensorflow/files/1555478/gcc5.log)
[gcc5_abi0.log](https://github.com/tensorflow/tensorflow/files/1555479/gcc5_abi0.log)
[gcc_4.8.txt](https://github.com/tensorflow/tensorflow/files/1555485/gcc_4.8.txt)

**Comment by sanjoy** [comment]
I don't think this is specific to XLA AOT -- the build errors are from bazel-out/host/bin/external/org_tensorflow/tensorflow/python/pywrap_tensorflow_internal.cc which I think is generated by SWIG.  I suspect this is due to some new %includes in tensorflow/python/tensorflow.i, but I'm not really sure.  @michaelisard - perhaps this is better handled by someone more familiar with that side of things?

**Comment by uziela** [comment]
I have also tried to compile the same example tests using tensorflow v1.5 branch and I got a different error:
[gcc5_tensorflow_v1.5_abi0.log](https://github.com/tensorflow/tensorflow/files/1600863/gcc5_tensorflow_v1.5_abi0.log)

The exact version of tensorflow used to create the above log was:
tf.GIT_VERSION, tf.VERSION = 'v1.3.0-rc1-6081-g6e08980', '1.5.0-rc0'

As before, the tensorflow v1.5 itself was compiled without any problems and the command to compile aot examples was:
cd tensorflow/compiler/aot/tests ; bazel clean ; bazel build --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" all_tests &>gcc5_tensorflow_v1.5_abi0.log

I have also tried these tensorflow versions, but they gave pretty much the same error as in gcc5_abi0.log that I shared before:
('v1.4.1-0-g438604f', '1.4.1')
('v1.3.0-rc1-6508-g97a4c22', '1.4.0')

**Comment by tensorflowbutler** [comment]
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by sanjoy** [comment]
I'm not working on this now; as stated above I don't think this is XLA AOT specific.

**Comment by uziela** [comment]
@sanjoy Did you look into all of the logs I attached? Aren't any of them XLA/AOT specific? I tried to compile XLA/AOT examples with 2 different gcc compilers and 3 different tensorflow branches. None of them worked and all gave different errors. For me it is really important to get it to work in at least one of the cases. I would really appreciate your help.

**Comment by sanjoy** [comment]
@uziela All of the errors are in bazel-out/host/bin/external/org_tensorflow/tensorflow/python/pywrap_tensorflow_internal.cc as far as I can tell, which isn't an XLA AOT specific file.  However, I don't understand you're hitting this only when building with XLA AOT.  Can you please run a bazel query (https://docs.bazel.build/versions/master/query-how-to.html) to find out how the target you're trying to build depends on pywrap_tensorflow_internal.cc?

There is also a way to disable building the python bindings: -Dtensorflow_BUILD_PYTHON_BINDINGS=(ON|OFF) (see https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/cmake) -- perhaps you can use that as a workaround?

**Comment by uziela** [comment]
@sanjoy I have three points:
1) When compiling AOT tests with tensorflow 1.5 version, the compilation errors are not related to pywrap_tensorflow_internal. See again the log that I attached to the previous comment: 
[gcc5_tensorflow_v1.5_abi0.log](https://github.com/tensorflow/tensorflow/files/1652635/gcc5_tensorflow_v1.5_abi0.log)

2) I tried to query for the dependencies of pywrap_tensorflow_internal. I am a novice in bazel, so I am not sure if I used the correct command. Here is the command that I used and the output:
bazel query "deps(//tensorflow/python:pywrap_tensorflow_internal)" &>pywrap_tensorflow_internal_deps.txt
[pywrap_tensorflow_internal_deps.txt](https://github.com/tensorflow/tensorflow/files/1652627/pywrap_tensorflow_internal_deps.txt)

3) Sorry for a beginner question, but I do I pass the cmake option from bazel? I tried this, but it doesn't work:
cd tensorflow/compiler/aot/tests ; bazel build -Dtensorflow_BUILD_PYTHON_BINDINGS=OFF --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" all_tests

**Comment by sanjoy** [comment]
> When compiling AOT tests with tensorflow 1.5 version, the compilation errors are not related to pywrap_tensorflow_internal. See again the log that I attached to the previous comment:
gcc5_tensorflow_v1.5_abi0.log

None of the logs you attached in the first comment have the same "undeclared inclusion" error as far as I can tell.  I tried `blaze build all_tests` on top of tree, and I get the SWIG related duplicate symbol error so I think we should try to fix that first, even if it isn't the only error.

I've never dealt with SWIG myself so I'm out of my depth here, but perhaps you could try binary searching through the %includes in tensorflow.i (by commenting out a set of %includes) to figure out why we're %include 'ing files that redefine the same symbols?

> Sorry for a beginner question, but I do I pass the cmake option from bazel? I tried this, but it doesn't work:
cd tensorflow/compiler/aot/tests ; bazel build -Dtensorflow_BUILD_PYTHON_BINDINGS=OFF --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" all_tests

I've never used cmake with bazel, but as a starting point, I'd suggest reading the BUILD or .bzl files that invoke cmake (they're written in Skylark, which is a language similar to python) to see how they discover the arguments that are to be passed to cmake.

**Comment by uziela** [comment]
> I've never dealt with SWIG myself so I'm out of my depth here, but perhaps you could try binary searching through the %includes in tensorflow.i (by commenting out a set of %includes) to figure out why we're %include 'ing files that redefine the same symbols?

Sorry, I am not exactly sure what you meant by this. Can you perform this step yourself? Or can you be more specific with the steps and linux commands that I need to execute?

**Comment by sanjoy** [comment]
Sorry for the silence, I was talking to some bazel developers internally.  As far as I can tell there are three issues here:

1. Our dependency labels are not quite correct for a non-sandbox build.  This leads to the "undeclared inclusions" error in the second gcc5_tensorflow_v1.5_abi0.log you uploaded.  I'm working on a fix for this.
2. I haven't yet root-caused the SWIG error in the log you posted in the first message.  I'll take a look at this once I have a handle on (1).
3. The build fails differently in a clean build vs a incremental build -- on a clean build I see the SWIG error, but on an incremental build I see the "undeclared inclusion" error.  I suspect something in the SWIG generation pipeline is broken.  I'll take a look at this once I have a handle on (1) and (2).

**Comment by uziela** [comment]
Great, looking forward to hear more news!

**Comment by sanjoy** [comment]
Locally I was able to successfully run `blaze all_tests` in `tensorflow/compiler/aot/tests`.  Can you please verify if this works on your end, and if it does can you please close the issue?

**Comment by uziela** [comment]
If I type `blaze all_tests` in `tensorflow/compiler/aot/tests`, I get this error:
```
transpiling build
Error: ENOENT: no such file or directory, open 'build'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.load_yaml (/usr/local/lib/node_modules/blaze_compiler/src/blaze.ts:21:24)
    at Object.compile (/usr/local/lib/node_modules/blaze_compiler/src/compiler.ts:99:39)
    at Object.<anonymous> (/usr/local/lib/node_modules/blaze_compiler/src/cli.ts:25:26)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)

```

**Comment by sanjoy** [comment]
I just tried on head and I don't see the same problem.  Could it be because you used `blaze all_tests` when you should have done `bazel build all_tests`?  `bazel test all_tests` also works for me.

**Comment by uziela** [comment]
I used blaze, because you instructed me to do so. Now I tried `bazel build all_tests` with the newest tensorflow version (v1.6.0-rc1-337-gd100729) and it works. Thanks for your help!
