### ISSUE TITLE
With tf-nightly-gpu, getting error: ImportError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.23' not found

### ISSUE THREAD

**Issue by reedwm** [tensorflow/tensorflow#15376]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 14.04
- **TensorFlow installed from (source or binary)**: Binary
- **TensorFlow version (use command below)**: `tf-nightly-gpu` -- I can't import TensorFlow to check the version
- **Python version**: 2.7
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: Cuda 9.0, cuDNN 7.0.4
- **GPU model and memory**: GTX 1080 8GB
- **Exact command to reproduce**:

```
virtualenv --system-site-packages ~/tftest
source ~/tftest/bin/activate
pip install tf-nightly-gpu
python -c 'import tensorflow'
```

### Describe the problem
When I run the commands above, I get the following error:
```
(tftest) reedwm@reedwm2:~$ python -c 'import tensorflow'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/buildtools/current/sitecustomize/sitecustomize.py", line 152, in SetupPathsAndImport
    return real_import(name, globals, locals, fromlist, level)
  File "/usr/local/google/home/reedwm/tftest/local/lib/python2.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/usr/local/google/home/reedwm/tftest/local/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/google/home/reedwm/tftest/local/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 73, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/google/home/reedwm/tftest/local/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/google/home/reedwm/tftest/local/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/google/home/reedwm/tftest/local/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.23' not found (required by /usr/local/google/home/reedwm/tftest/local/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

This occurs if I `pip install tf-nightly-gpu==1.5.0.dev20171212`, which is the earliest version of `tf-nightly-gpu` it occurs on. When I pip install the previous version with `pip install tf-nightly-gpu==1.5.0.dev20171207`, the issue does not occur.

This issue is similar to #53 and #3127.

/CC @gunan @jhseu @martinwicke, any ideas what the issue could be?

**Comment by gunan** [comment]
@jhseu I think this is caused by our nightly and release GPU builds having to move to ubuntu 16, because the there are no more ubuntu 14 docker images with cuda9.

Maybe our builds are missing this flag: `--cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0"`

**Comment by yongtang** [comment]
I think the issue is that ubuntu 14.04 has a lower version of GLIBC. When build moves to ubuntu 16.04, some of the GLIBC symbols that is linked on is not available for GLIBC in 14.04.

The easiest path for the fix might be to upgrade from 14.04 to ubuntu 16.04.

Otherwise I think you can try alternatives:
1. Upgrade or install newer version of glibc on 14.04 (may typically cause some other issues on other software in your system, as glibc has a much bigger impact)
2. Recompile TensorFlow from source on Ubuntu 14.04.
3. Use docker to run inside the container.

Also if the build is run on Ubuntu 16.04 maybe the supported platform for binary install could be updated.

**Comment by jhseu** [comment]
@gunan I don't think that flag will work here. I think we'll just have to require Ubuntu 16.04 as the minimum for our builds.

**Comment by sleepfin** [comment]
I have the same error on RedHat7.2. Any suggestion to fix it?

**Comment by gunan** [comment]
Unfortunately your current workaround is to build from sources.
#15458 should fix this, but we are blocked from merging that PR right now.

**Comment by tensorflowbutler** [comment]
Nagging Awaiting TensorFlower: It has been 14 days with no activityand the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by reedwm** [comment]
Closing since the pre-built binaries no longer support Ubuntu 14.04.
