### ISSUE TITLE
setuptools error on upgrading to 1.4.1

### ISSUE THREAD

**Issue by martin-gorner** [tensorflow/tensorflow#15400]
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: NO
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS Sierra
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.4.0
- **Python version**: 3.6 (normal install, NO virtualenv, NO anaconda, ...)
- **Exact command to reproduce**: ```sudo pip3 install --upgrade tensorflow```

When upgrading TF 1.4.0 to 1.4.1 using the command above, I get the error message:
```
Could not import setuptools which is required to install from a source distribution.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/req/req_install.py", line 387, in setup_py
    import setuptools  # noqa
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/__init__.py", line 10, in <module>
    from setuptools.extern.six.moves import filter, map
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/extern/__init__.py", line 1, in <module>
    from pkg_resources.extern import VendorImporter
ModuleNotFoundError: No module named 'pkg_resources.extern'
```

I have been able to solve the problem with the following command:

```
pip3 install -U setuptools
```
After this, running pip3 install --upgrade Tensorflow runs successfully.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Bazel version
CUDA/cuDNN version
GPU model and memory

**Comment by martin-gorner** [comment]
Bazel version: irrelevant, not building from source
CUDA/cuDNN version: irrelevant, not using GPU
GPU model and memory: irrelevant, not using

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue? Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
The original poster has replied to this issue after the stat:awaiting response label was applied.

**Comment by drpngx** [comment]
@gunan are we missing a dependency?

**Comment by gunan** [comment]
The error message seems to be during the installation of tensorflow?
Unless @yifeif sees something else in the error, I think this is a pip/setuptools bug, not a tensorflow one as the command the error is seen is a pip command.

**Comment by michaelisard** [comment]
It sounds as if it may make sense to report this to pip/setuptools. Closing here, but please reopen if you think this is a TensorFlow bug.
