### ISSUE TITLE
TypeError: broadcast() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by ppwwyyxx** [tensorflow/tensorflow#15425]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **TensorFlow installed from (source or binary)**:source
- **TensorFlow version (use command below)**: b'v1.3.0-rc1-6044-g0b80606' 1.4.0    (2 days ago)
- **Python version**: 3.6
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:

### Source code / logs
I ran `tensorflow/benchmarks`, and got the following error.
```
Traceback (most recent call last):
  File "tf_cnn_benchmarks.py", line 47, in <module>
    tf.app.run()
  File "/MYHOME/.local/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 124, in run
    _sys.exit(main(argv))
  File "tf_cnn_benchmarks.py", line 43, in main
    bench.run()
  File "/MYHOME/tf-benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 956, in run
    return self._benchmark_cnn()
  File "/MYHOME/tf-benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 1046, in _benchmark_cnn
    self._build_model_single_session())
  File "/MYHOME/tf-benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 1563, in _build_model_single_session                                                                      all_top_5_ops, phase_train)
  File "/MYHOME/tf-benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 1370, in _build_fetches
    self.variable_mgr.preprocess_device_grads(device_grads))
  File "/MYHOME/tf-benchmarks/scripts/tf_cnn_benchmarks/variable_mgr.py", line 386, in preprocess_device_grads
    agg_small_grads_max_group=self._agg_small_grads_max_group)
  File "/MYHOME/tf-benchmarks/scripts/tf_cnn_benchmarks/allreduce.py", line 332, in sum_gradients_all_reduce
    if is_hierarchical else aux_device_groups[group_index], num_shards))
  File "/MYHOME/tf-benchmarks/scripts/tf_cnn_benchmarks/allreduce.py", line 236, in sum_grad_and_var_all_reduce
    tf.add)
  File "/MYHOME/.local/lib/python3.6/site-packages/tensorflow/contrib/all_reduce/python/all_reduce.py", line 780, in build_nccl_then_ring
    return _build_nccl_hybrid(input_tensors, red_op, upper_level_f)
  File "/MYHOME/.local/lib/python3.6/site-packages/tensorflow/contrib/all_reduce/python/all_reduce.py", line 748, in _build_nccl_hybrid
    send_op, dst_tensors = nccl.broadcast(level_2_output[w], dst_devices)
TypeError: broadcast() takes 1 positional argument but 2 were given
```

The reason is that the invocation of `nccl.broadcast` is different from its signature:
https://github.com/tensorflow/tensorflow/blob/17e725c0558581cba19bd6c409698b2c3f88efe5/tensorflow/contrib/all_reduce/python/all_reduce.py#L748
https://github.com/tensorflow/tensorflow/blob/17e725c0558581cba19bd6c409698b2c3f88efe5/tensorflow/contrib/nccl/python/ops/nccl_ops.py#L173-L182 
Problems still exists in current HEAD.

**Comment by jart** [comment]
@chsigg contrib/all_reduce needs to be updated due to the contrib/nccl API change made in https://github.com/tensorflow/tensorflow/commit/ca8af1d0dbb605087a4f8ae076188f2b9a26b1ba which broke some benchmarks. cc: @poxvoculi

**Comment by anpark** [comment]
#15642 same problem

**Comment by tensorflowbutler** [comment]
Nagging Awaiting TensorFlower: It has been 14 days with no activityand the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by poxvoculi** [comment]
nccl.broadcast got changed without updating its uses.  The immediate problem has been fixed in the internal build and should roll out with the next update.

**Comment by anpark** [comment]
@poxvoculi  thanks very much!
how do i get this fix now?

**Comment by poxvoculi** [comment]
The fix is easy, you can patch your own client now if you're eager.

In all_reduce.py remove these lines

      dst_devices = per_worker_devices[w][1:]
      send_op, dst_tensors = nccl.broadcast(level_2_output[w], dst_devices)
      # NOTE: need control dependency to ensure send_op executes
      with ops.control_dependencies([send_op]):
        with ops.device(per_worker_devices[w][0]):
          dst_tensors.insert(0, array_ops.identity(level_2_output[w]))
          down_values[w] = dst_tensors

and replace with these lines:


      dst_tensors = []
      with ops.device(per_worker_devices[w][0]):
        broadcast_src = nccl.broadcast(array_ops.identity(level_2_output[w]))
      for d in per_worker_devices[w]:
        with ops.device(d):
          dst_tensors.append(array_ops.identity(broadcast_src))
      down_values[w] = dst_tensors

I'm not expert at NCCL, but I wouldn't be surprised if it only works on dense tensors of numeric types.  IndexedSlices are a sparse representation, right?

**Comment by anpark** [comment]
@poxvoculi thanks, i had already tried same fix with you before this issue. 
yesterday i tried your code, but failed again at same error: (use tf_benchmark: 
variable_update: distributed_all_reduce
all_reduce_spec: nccl/xring)

UnimplementedError (see above for traceback): This op should be replaced during graph optimization. 
caused by 
File "/home/slurm/tools/tf_py/lib/python2.7/site-packages/tensorflow/contrib/all_reduce/python/all_reduce.py", line 781, in build_nccl_then_ring 
return _build_nccl_hybrid(input_tensors, red_op, upper_level_f) 
File "/home/slurm/tools/tf_py/lib/python2.7/site-packages/tensorflow/contrib/all_reduce/python/all_reduce.py", line 749, in _build_nccl_hybrid 
broadcast_src = nccl.broadcast(array_ops.identity(level_2_output[w])) 
File "/home/slurm/tools/tf_py/lib/python2.7/site-packages/tensorflow/contrib/nccl/python/ops/nccl_ops.py", line 187, in broadcast 
return gen_nccl_ops.nccl_broadcast(input=tensor, shape=tensor.shape) 
File "/home/slurm/tools/tf_py/lib/python2.7/site-packages/tensorflow/contrib/nccl/ops/gen_nccl_ops.py", line 98, in nccl_broadcast 
"NcclBroadcast", input=input, shape=shape, name=name) 

which i guess rewrite graph maybe happen in nccl send/recv op.

IndexedSlices are a sparse representation, right?
Yes,  excuse me for that i sayed that nccl in the issue above, actually it's contrib/all_reduce module, i fix it now, thanks.

**Comment by Agoniii** [comment]
Hi All, I meet the same issue.
Need your help. Thanks.

**Comment by anpark** [comment]
@Agoniii  can you post detail? thanks

**Comment by Agoniii** [comment]
@anpark  I run tf_cnn_benchmarks with the commands `--variable_update=distributed_all_reduce --all_reduce_spec nccl/xring`. My problem is almost as same as yours.
```
  File "/root/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 1545, in _build_fetches
    self.variable_mgr.preprocess_device_grads(device_grads))
  File "/root/benchmarks/scripts/tf_cnn_benchmarks/variable_mgr.py", line 386, in preprocess_device_grads
    agg_small_grads_max_group=self._agg_small_grads_max_group)
  File "/root/benchmarks/scripts/tf_cnn_benchmarks/allreduce.py", line 332, in sum_gradients_all_reduce
    if is_hierarchical else aux_device_groups[group_index], num_shards))
  File "/root/benchmarks/scripts/tf_cnn_benchmarks/allreduce.py", line 236, in sum_grad_and_var_all_reduce
    tf.add)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/all_reduce/python/all_reduce.py", line 780, in build_nccl_then_ring
    return _build_nccl_hybrid(input_tensors, red_op, upper_level_f)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/all_reduce/python/all_reduce.py", line 749, in _build_nccl_hybrid
    broadcast_src = nccl.broadcast(array_ops.identity(level_2_output[w]))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/nccl/python/ops/nccl_ops.py", line 187, in broadcast
    return gen_nccl_ops.nccl_broadcast(input=tensor, shape=tensor.shape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/nccl/ops/gen_nccl_ops.py", line 98, in nccl_broadcast
    "NcclBroadcast", input=input, shape=shape, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3172, in create_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1617, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

UnimplementedError (see above for traceback): This op should be replaced during graph optimization.
	 [[Node: allreduce_160/NcclBroadcast = NcclBroadcast[T=DT_FLOAT, shape=[1001], _device="/job:worker/replica:0/task:0/device:GPU:0"](allreduce_160/Slice)]]
	 [[Node: group_deps_3_G19865 = _Recv[client_terminated=false, recv_device="/job:worker/replica:0/task:0/device:CPU:0", send_device="/job:worker/replica:0/task:0/device:GPU:0", send_device_incarnation=-2613134839557745882, tensor_name="edge_55804_group_deps_3", tensor_type=DT_FLOAT, _device="/job:worker/replica:0/task:0/device:CPU:0"]()]]
```

**Comment by benbarsdell** [comment]
I've run into this UnimplementedError as well with 1.5. A small repro:
```
import tensorflow as tf
import tensorflow.contrib.nccl as nccl

if __name__ == '__main__':
    devices = ['/gpu:0', '/gpu:0']
    with tf.device(devices[0]):
        data0 = tf.constant([1.1, 2.2, 3.3, 4.4])
        received_tensor = nccl.broadcast(data0)
    received_tensors = []
    for device in devices[1:]:
        with tf.device(device):
            received_tensors.append(tf.identity(received_tensor))
    sess = tf.Session()
    sess.run(received_tensors)
```

It looks like the registration of the optimization pass at this line never happens:

https://github.com/tensorflow/tensorflow/blob/bf1fad214febef6af5c101d8f953d0109c46dfbb/tensorflow/contrib/nccl/kernels/nccl_rewrite.cc#L270

This may be because _nccl_ops.so doesn't include kernels/nccl_rewrite.cc:

https://github.com/tensorflow/tensorflow/blob/bf1fad214febef6af5c101d8f953d0109c46dfbb/tensorflow/contrib/nccl/BUILD#L24

Unfortunately Bazel throws a fit when I try to add the source file to this target.

**Comment by poxvoculi** [comment]
@chsigg can you clarify as to whether this test program is using contrib/nccl in the anticipated way?

**Comment by anpark** [comment]
@benbarsdell Great!
 i add the same issue in tensorflow/benchmarks repo, but @reedwm closed it and ask me to  run with tf1.5.
Hope anyone can help!

**Comment by tensorflowbutler** [comment]
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignees @chsigg, @poxvoculi: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignees @chsigg, @poxvoculi: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by poxvoculi** [comment]
Reassigning to @zheng-xq

**Comment by ppwwyyxx** [comment]
Seems to be fixed already.

**Comment by anpark** [comment]
@ppwwyyxx  which version do you use?  Have you tested it ok?

**Comment by ppwwyyxx** [comment]
There might be other issues, but at least my original one seems fixed. As I can run tensorflow/benchmarks with TF1.6.
