### ISSUE TITLE
ImportError: libmklml_intel.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by sergiubuciumas** [tensorflow/tensorflow#15631]
GPU: 1080 Ti
cuda 9.0
cuddn 7.0 v7
centos 7.
installed Intel MKL-DNN but the error is still present.

here is the output:
````
ipython
Python 3.6.3 |Anaconda custom (64-bit)| (default, Oct 13 2017, 12:02:49) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.1.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import tensorflow as tf
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
~/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py in <module>()
     57 
---> 58   from tensorflow.python.pywrap_tensorflow_internal import *
     59   from tensorflow.python.pywrap_tensorflow_internal import __version__

~/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py in <module>()
     27             return _mod
---> 28     _pywrap_tensorflow_internal = swig_import_helper()
     29     del swig_import_helper

~/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py in swig_import_helper()
     23             try:
---> 24                 _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
     25             finally:

~/anaconda3/lib/python3.6/imp.py in load_module(name, file, filename, details)
    242         else:
--> 243             return load_dynamic(name, filename, file)
    244     elif type_ == PKG_DIRECTORY:

~/anaconda3/lib/python3.6/imp.py in load_dynamic(name, path, file)
    342             name=name, loader=loader, origin=path)
--> 343         return _load(spec)
    344 

ImportError: libmklml_intel.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-1-41389fad42b5> in <module>()
----> 1 import tensorflow as tf

~/anaconda3/lib/python3.6/site-packages/tensorflow/__init__.py in <module>()
     22 
     23 # pylint: disable=wildcard-import
---> 24 from tensorflow.python import *
     25 # pylint: enable=wildcard-import
     26 

~/anaconda3/lib/python3.6/site-packages/tensorflow/python/__init__.py in <module>()
     47 import numpy as np
     48 
---> 49 from tensorflow.python import pywrap_tensorflow
     50 
     51 # Protocol buffers

~/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py in <module>()
     70 for some common reasons and solutions.  Include the entire stack trace
     71 above this error message when asking for help.""" % traceback.format_exc()
---> 72   raise ImportError(msg)
     73 
     74 # pylint: enable=wildcard-import,g-import-not-at-top,unused-import,line-too-long

ImportError: Traceback (most recent call last):
  File "/home/sb0709/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/sb0709/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/sb0709/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/sb0709/anaconda3/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/home/sb0709/anaconda3/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libmklml_intel.so: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```
`

**Comment by Gagazet** [comment]
Good day. Totally same setup with same error. Can anyone help, please?

**Comment by bignamehyp** [comment]
Please see PR #12975

**Comment by Gagazet** [comment]
Missed, but i am using python 2.7, not 3.6 :(

**Comment by sergiubuciumas** [comment]
@bignamehyp  is not the same issue, the build works fine with cuda 8 and is not a vm and in the article pointed by you. Also I use GPU version and https://github.com/mind/wheels/releases/download/tf1.4-gpu/tensorflow-1.4.0-cp36-cp36m-linux_x86_64.whl

MKL is for running NN on CPU faster and the version installed on my machine is GPU. 
I installed libraries, build from source and still same issue. 

you closed the issue without pointing to a solution ...

**Comment by lechatthecat** [comment]
I am using python 3.5 with Linux mint. I uninstalled tensorflow once:
sudo python3.5 -m pip uninstall tensorflow-gpu
Then installed again:
sudo python3.5 -m pip install tensorflow-gpu
And tensorflow worked without "libmklml_intel.so" error for some reason.

**Comment by sergiubuciumas** [comment]
@lechatthecat so you use python3.5 and the issue i have is due the python 3.6 is is not installed as you pointing out.

**Comment by lechatthecat** [comment]
@sergiubuciumas
Maybe Python 3.6 should be already installed in your PC. I tried with python3.6 also but it wprks too.
What I did was:
(Installed gpu driver and cuda and rebooted the PC)
1. Installed Tensorflow-gpu
2. Installed cudnn.
3. Installed mkl-dnn. 
(Here I got the libmklml error)
4. Uninstalled tensorflow-gpu
sudo python3.6 -m pip uninstall tensorflow-gpu
5. Installed the tensorflow again and rebooted the PC.
sudo python3.6 -m pip install tensorflow-gpu
6. The error was gone.
I'm not sure this work for you too.

**Comment by sergiubuciumas** [comment]
I missed the ‘ , ‘ after the python3.6, so not working in centos, will just wait for tensorflow 1.5 stable release, for now just downgraded to cuda 8 because the building from source is not working as well, tried everything posible to make it work under centos 7 and none works, if fixing the intel MKL than comes up the naming of libcudnn naming problem.

Will double check the whl to modify but as for now source compile fails so need to look more on requirements and is getting hard to upgrade some tools in Centos 7.
