### ISSUE TITLE
Read tflite file failed on iOS

### ISSUE THREAD

**Issue by llyyun** [tensorflow/tensorflow#15636]
Hi

I tried the examples on iOS according to TF Lite guide, but failed when assign data to tflite because address "out" is NULL. probably my tflite file is incorrect, but I am not sure, can anybody give some help? 

My test step is as follows:
1.  Try the following code(https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/lite),  get the tflite file converteds_model.tflite

```
import tensorflow as tf
img = tf.placeholder(name="img", dtype=tf.float32, shape=(1, 64, 64, 3))
val = img + tf.constant([1., 2., 3.]) + tf.constant([1., 4., 4.])
out = tf.identity(val, name="out")
with tf.Session() as sess:
  tflite_model = tf.contrib.lite.toco_convert(sess.graph_def, [img], [out])
  open("converteds_model.tflite", "wb").write(tflite_model)
```

2. Integrated the tflite into my app, which is from iOS sample code "simple"(/Users/Sensteer/Software/tensorflowclone/tensorflow/tensorflow/contrib/lite/examples/ios/simple).But exception happed because address "out" is NULL

```
int input = interpreter->inputs()[0];                                 //input is 3
float* out = interpreter->typed_tensor<float>(input);          //out is NULL
```

So my questions are:
1. The tflite created above is right or not?
2. The reading tflite code is right or not?
2. If the tflite file is not right, do I must create tflite with  "pb", "ckpt" and "FrozenGraphDef" mentioned in guide?

Thanks

**Comment by ailias** [comment]
I had the same problem.  It seemed that the converted part failed. 
You'd better use bazel_bin command to build the conversion(Not python code). And you should check the tflite file size(1/3 of .data file size). Then when you move the file to you mac os, its small file icon shows the black window which means it is a binary file. That means your conversion is success.
Good luck.

**Comment by asimshankar** [comment]
@andrehentz @aselle - Any guidance here?

**Comment by andrehentz** [comment]
@llyyun Can you verify that your converteds_model.tflite is not empty?

**Comment by tensorflowbutler** [comment]
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by llyyun** [comment]
yes, the tflite file is incorrect. finally we used bazel command build the model file

**Comment by tslater** [comment]
I'm having the same issue. @llyyun, how did you resolve this? I'm trying to use visualize.py to check out my model. Unfortunately, that is failing too! Is there a good way to check the model?

**Comment by tslater** [comment]
Here's the output from visualize.py
```
tylers-iMac:tensorflow tyler$ bazel run tensorflow/contrib/lite/tools:visualize --  /Users/tyler/face-it/facenet-models/frozen_models/mobilenet_v0.1.tflite /Users/tyler/Desktop/mobilenet_v0.1.tflite.html
INFO: Analysed target //tensorflow/contrib/lite/tools:visualize (0 packages loaded).
INFO: Found 1 target...
Target //tensorflow/contrib/lite/tools:visualize up-to-date:
  bazel-bin/tensorflow/contrib/lite/tools/visualize
INFO: Elapsed time: 0.252s, Critical Path: 0.00s
INFO: Build completed successfully, 1 total action

INFO: Running command line: bazel-bin/tensorflow/contrib/lite/tools/visualize /Users/tyler/face-it/facenet-models/frozen_models/mobilenet_v0.1.tflite /Users/tyler/Desktop/mobilenet_v0.1.tflite.html
sh: third_party/flatbuffers/flatc: No such file or directory
third_party/flatbuffers/flatc -t --strict-json --defaults-json -o /tmp third_party/tensorflow/contrib/lite/schema/schema.fbs -- /Users/tyler/face-it/facenet-models/frozen_models/mobilenet_v0.1.tflite
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_tyler/980b2407727d0312ad05cca671189978/execroot/org_tensorflow/bazel-out/darwin-py3-opt/bin/tensorflow/contrib/lite/tools/visualize.runfiles/org_tensorflow/tensorflow/contrib/lite/tools/visualize.py", line 391, in <module>
    main(sys.argv)
  File "/private/var/tmp/_bazel_tyler/980b2407727d0312ad05cca671189978/execroot/org_tensorflow/bazel-out/darwin-py3-opt/bin/tensorflow/contrib/lite/tools/visualize.runfiles/org_tensorflow/tensorflow/contrib/lite/tools/visualize.py", line 387, in main
    CreateHtmlFile(tflite_input, html_output)
  File "/private/var/tmp/_bazel_tyler/980b2407727d0312ad05cca671189978/execroot/org_tensorflow/bazel-out/darwin-py3-opt/bin/tensorflow/contrib/lite/tools/visualize.runfiles/org_tensorflow/tensorflow/contrib/lite/tools/visualize.py", line 307, in CreateHtmlFile
    data = json.load(open(real_output))
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/mobilenet_v0.1.json'
ERROR: Non-zero return code '1' from command: Process exited with status 1
```

**Comment by tslater** [comment]
Here's the output of toco:
```
WARNING:tensorflow:From /usr/local/Cellar/python/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py:198: retry (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Use the retry module or similar alternatives.
2018-05-01 07:11:47.154904: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 225 operators, 419 arrays (0 quantized)
2018-05-01 07:11:47.163571: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 225 operators, 419 arrays (0 quantized)
2018-05-01 07:11:47.193564: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 1: 31 operators, 88 arrays (0 quantized)
2018-05-01 07:11:47.194331: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before dequantization graph transformations: 31 operators, 88 arrays (0 quantized)
2018-05-01 07:11:47.194877: I tensorflow/contrib/lite/toco/allocate_transient_arrays.cc:311] Total transient array allocated size: 3276800 bytes, theoretical optimal value: 2457600 bytes.
2018-05-01 07:11:47.195146: I tensorflow/contrib/lite/toco/toco_tooling.cc:307] Estimated count of arithmetic ops: 0.582426 billion (note that a multiply-add is counted as 2 ops).
```

Should there be some success command at the end?

**Comment by tslater** [comment]
I figured it out. The example is quantized...but I'm using floats. Here's how I changed it to work.
```
    
    int input = interpreter->inputs()[0];
    

    
    auto* out = interpreter->typed_tensor<float>(input);
    for (int y = 0; y < wanted_input_height; ++y) {
        auto* out_row = out + (y * wanted_input_width * wanted_input_channels);
        for (int x = 0; x < wanted_input_width; ++x) {
            const int in_x = (y * image_width) / wanted_input_width;
            const int in_y = (x * image_height) / wanted_input_height;
            auto* in_pixel = in + (in_y * image_width * image_channels) + (in_x * image_channels);
            auto* out_pixel = out_row + (x * wanted_input_channels);
            for (int c = 0; c < wanted_input_channels; ++c) {
                out_pixel[c] = in_pixel[c];
            }
        }
    }
    
    double startTimestamp = [[NSDate new] timeIntervalSince1970];
    if (interpreter->Invoke() != kTfLiteOk) {
        LOG(FATAL) << "Failed to invoke!";
    }
    double endTimestamp = [[NSDate new] timeIntervalSince1970];
    total_latency += (endTimestamp - startTimestamp);
    total_count += 1;
    NSLog(@"Time: %.4lf, avg: %.4lf, count: %d", endTimestamp - startTimestamp,
          total_latency / total_count, total_count);
    
      const int output_size = 256;
      const int kNumResults = 5;
      const float kThreshold = 0.1f;
    
    std::vector<std::pair<float, int>> top_results;
    
    auto* output = interpreter->typed_output_tensor<float>(0);
    
    NSData *dataData = [NSData dataWithBytes:output length:sizeof(output)];
    NSLog(@"output %@", dataData);
```

**Comment by kuanzi** [comment]
how did you fix the problem "sh: third_party/flatbuffers/flatc: No such file or directory"? I encounter the same problem, and can't find the proper way to solve. THANK YOU.

**Comment by andrehentz** [comment]
@kuanzi This will hopefully be fixed soon. Meanwhile, you might be able to workaround the issue by changing: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/lite/tools/visualize.py#L35
