### ISSUE TITLE
speech commands check_nans doesnt work

### ISSUE THREAD

**Issue by thinkinds** [tensorflow/tensorflow#15684]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: I'm running the simple audio recognition tutorial code.
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**:tf-nightly-gpu15
- **Python version**: 3.5
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:CUDA8.0/cuDNNv7
- **GPU model and memory**: 1060 6GB
- **Exact command to reproduce**:python train.py --check-nans=True

You can collect some of this information using our environment capture script:

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

You can obtain the TensorFlow version with

python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.
As the tutorial said, by enabling the --check_nans flag I could track down the source of the not-a-number error in model tuning. But I got following errors instead, which I guess maybe a bug or something?

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.
Traceback (most recent call last):
  File "/home/renq/.conda/envs/py35_tfnightly_gpu15/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1323, in _do_call
    return fn(*args)
  File "/home/renq/.conda/envs/py35_tfnightly_gpu15/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1302, in _run_fn
    status, run_metadata)
  File "/home/renq/.conda/envs/py35_tfnightly_gpu15/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'Placeholder_1' with dtype float
         [[Node: Placeholder_1 = Placeholder[dtype=DT_FLOAT, shape=[], _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
         [[Node: global_step/read/_18 = _Send[T=DT_INT64, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_4_global_step/read", _device="/job:localhost/replica:0/task:0/device:CPU:0"](global_step/read)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 432, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/home/renq/.conda/envs/py35_tfnightly_gpu15/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 124, in run
    _sys.exit(main(argv))
  File "train.py", line 217, in main
    dropout_prob: 0.5
  File "/home/renq/.conda/envs/py35_tfnightly_gpu15/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/home/renq/.conda/envs/py35_tfnightly_gpu15/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/renq/.conda/envs/py35_tfnightly_gpu15/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/home/renq/.conda/envs/py35_tfnightly_gpu15/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'Placeholder_1' with dtype float
         [[Node: Placeholder_1 = Placeholder[dtype=DT_FLOAT, shape=[], _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
         [[Node: global_step/read/_18 = _Send[T=DT_INT64, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_4_global_step/read", _device="/job:localhost/replica:0/task:0/device:CPU:0"](global_step/read)]]

Caused by op 'Placeholder_1', defined at:
  File "train.py", line 432, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/home/renq/.conda/envs/py35_tfnightly_gpu15/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 124, in run
    _sys.exit(main(argv))
  File "train.py", line 106, in main
    FLAGS.testing_percentage, model_settings)
  File "/home/renq/tensorflow/tensorflow/examples/speech_commands/input_data.py", line 163, in __init__
    self.prepare_processing_graph(model_settings)
  File "/home/renq/tensorflow/tensorflow/examples/speech_commands/input_data.py", line 355, in prepare_processing_graph
    self.foreground_volume_placeholder_ = tf.placeholder(tf.float32, [])
  File "/home/renq/.conda/envs/py35_tfnightly_gpu15/lib/python3.5/site-packages/tensorflow/python/ops/array_ops.py", line 1680, in placeholder
    return gen_array_ops._placeholder(dtype=dtype, shape=shape, name=name)
  File "/home/renq/.conda/envs/py35_tfnightly_gpu15/lib/python3.5/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3141, in _placeholder
    "Placeholder", dtype=dtype, shape=shape, name=name)
  File "/home/renq/.conda/envs/py35_tfnightly_gpu15/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/renq/.conda/envs/py35_tfnightly_gpu15/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3143, in create_op
    op_def=op_def)
  File "/home/renq/.conda/envs/py35_tfnightly_gpu15/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1611, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'Placeholder_1' with dtype float
         [[Node: Placeholder_1 = Placeholder[dtype=DT_FLOAT, shape=[], _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
         [[Node: global_step/read/_18 = _Send[T=DT_INT64, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_4_global_step/read", _device="/job:localhost/replica:0/task:0/device:CPU:0"](global_step/read)]]

**Comment by skye** [comment]
Can you post the exact command that produces this error?

**Comment by tensorflowbutler** [comment]
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by drpngx** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
