### ISSUE TITLE
ResourceExhaustedError in translate example (with GPU)

### ISSUE THREAD

**Issue by ybbaigo** [tensorflow/tensorflow#1568]
GitHub issues are for bugs / installation problems / feature requests.  
For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System: Ubuntu 15.10

If installed from binary pip package, provide:

Which pip package you installed.

> sudo pip install --upgrade https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.7.1-cp27-none-linux_x86_64.whl

The output from python -c "import tensorflow; print(tensorflow.__version__)".

> I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so locally
> I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcudnn.so locally
> I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so locally
> I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally
> I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so locally
> 0.7.1

If installed from sources, provide the commit hash:

### Steps to reproduce
Just run translate.py with 10M pairs training data.

### What have you tried?
smaller batch size 32

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:475] Sum Total of in-use chunks: 3.63GiB
W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:211] Ran out of memory trying to allocate 32.00MiB.  See logs for memory state
W tensorflow/core/kernels/matmul_op.cc:158] Resource exhausted: OOM when allocating tensor with shape[2048,4096]
W tensorflow/core/common_runtime/executor.cc:1102] 0xe723bd30 Compute status: Resource exhausted: OOM when allocating tensor with shape[2048,4096]
	 [[Node: gradients_2/model_with_buckets/embedding_attention_seq2seq_2/RNN/MultiRNNCell/Cell0/BasicLSTMCell/Linear/MatMul_grad/MatMul_1 = MatMul[T=DT_FLOAT, transpose_a=true, transpose_b=false, _device="/job:localhost/replica:0/task:0/gpu:0"](model_with_buckets/embedding_attention_seq2seq_2/RNN/MultiRNNCell/Cell0/BasicLSTMCell/Linear/concat, gradients_2/model_with_buckets/embedding_attention_seq2seq_2/RNN/MultiRNNCell/Cell0/BasicLSTMCell/add_grad/Reshape)]]
Traceback (most recent call last):
  File "translate.py", line 289, in <module>
    tf.app.run()
  File "/home/yy/virtualenv/env1/local/lib/python2.7/site-packages/tensorflow/python/platform/default/_app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "translate.py", line 286, in main
    train()
  File "translate.py", line 187, in train
    target_weights, bucket_id, False)
  File "/home/yy/virtualenv/env1/local/lib/python2.7/site-packages/tensorflow/models/rnn/translate/seq2seq_model.py", line 224, in step
    outputs = session.run(output_feed, input_feed)
  File "/home/yy/virtualenv/env1/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 315, in run
    return self._run(None, fetches, feed_dict)
  File "/home/yy/virtualenv/env1/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 511, in _run
    feed_dict_string)
  File "/home/yy/virtualenv/env1/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 564, in _do_run
    target_list)
  File "/home/yy/virtualenv/env1/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 586, in _do_call
    e.code)
tensorflow.python.framework.errors.ResourceExhaustedError: OOM when allocating tensor with shape[2048,4096]
	 [[Node: gradients_2/model_with_buckets/embedding_attention_seq2seq_2/embedding_attention_decoder/attention_decoder/MultiRNNCell_3/Cell0/BasicLSTMCell/Linear/MatMul_grad/MatMul_1 = MatMul[T=DT_FLOAT, transpose_a=true, transpose_b=false, _device="/job:localhost/replica:0/task:0/gpu:0"](model_with_buckets/embedding_attention_seq2seq_2/embedding_attention_decoder/attention_decoder/MultiRNNCell_3/Cell0/BasicLSTMCell/Linear/concat, gradients_2/model_with_buckets/embedding_attention_seq2seq_2/embedding_attention_decoder/attention_decoder/MultiRNNCell_3/Cell0/BasicLSTMCell/add_grad/Reshape)]]
	 [[Node: clip_by_global_norm_2/clip_by_global_norm_2/_9/_3023 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_179468_clip_by_global_norm_2/clip_by_global_norm_2/_9", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
Caused by op u'gradients_2/model_with_buckets/embedding_attention_seq2seq_2/embedding_attention_decoder/attention_decoder/MultiRNNCell_3/Cell0/BasicLSTMCell/Linear/MatMul_grad/MatMul_1', defined at:
  File "translate.py", line 289, in <module>
    tf.app.run()
  File "/home/yy/virtualenv/env1/local/lib/python2.7/site-packages/tensorflow/python/platform/default/_app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "translate.py", line 286, in main
    train()
  File "translate.py", line 155, in train
    model = create_model(sess, False)
  File "translate.py", line 132, in create_model
    forward_only=forward_only)
  File "/home/yy/virtualenv/env1/local/lib/python2.7/site-packages/tensorflow/models/rnn/translate/seq2seq_model.py", line 161, in __init__
    gradients = tf.gradients(self.losses[b], params)
  File "/home/yy/virtualenv/env1/local/lib/python2.7/site-packages/tensorflow/python/ops/gradients.py", line 483, in gradients
    in_grads = _AsList(grad_fn(wrapped_op, *out_grads))
  File "/home/yy/virtualenv/env1/local/lib/python2.7/site-packages/tensorflow/python/ops/math_grad.py", line 431, in _MatMulGrad
    math_ops.matmul(op.inputs[0], grad, transpose_a=True))
  File "/home/yy/virtualenv/env1/local/lib/python2.7/site-packages/tensorflow/python/ops/math_ops.py", line 951, in matmul
    name=name)
  File "/home/yy/virtualenv/env1/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_math_ops.py", line 686, in _mat_mul
    transpose_b=transpose_b, name=name)
  File "/home/yy/virtualenv/env1/local/lib/python2.7/site-packages/tensorflow/python/ops/op_def_library.py", line 655, in apply_op
    op_def=op_def)
  File "/home/yy/virtualenv/env1/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2040, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/yy/virtualenv/env1/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1087, in __init__
    self._traceback = _extract_stack()

...which was originally created as op u'model_with_buckets/embedding_attention_seq2seq_2/embedding_attention_decoder/attention_decoder/MultiRNNCell_3/Cell0/BasicLSTMCell/Linear/MatMul', defined at:
  File "translate.py", line 289, in <module>
    tf.app.run()
[elided 3 identical lines from previous traceback]
  File "translate.py", line 132, in create_model
    forward_only=forward_only)
  File "/home/yy/virtualenv/env1/local/lib/python2.7/site-packages/tensorflow/models/rnn/translate/seq2seq_model.py", line 152, in __init__
    softmax_loss_function=softmax_loss_function)
  File "/home/yy/virtualenv/env1/local/lib/python2.7/site-packages/tensorflow/python/ops/seq2seq.py", line 926, in model_with_buckets
    decoder_inputs[:bucket[1]])
  File "/home/yy/virtualenv/env1/local/lib/python2.7/site-packages/tensorflow/models/rnn/translate/seq2seq_model.py", line 151, in <lambda>
    lambda x, y: seq2seq_f(x, y, False),
  File "/home/yy/virtualenv/env1/local/lib/python2.7/site-packages/tensorflow/models/rnn/translate/seq2seq_model.py", line 115, in seq2seq_f
    feed_previous=do_decode)
  File "/home/yy/virtualenv/env1/local/lib/python2.7/site-packages/tensorflow/python/ops/seq2seq.py", line 691, in embedding_attention_seq2seq
    initial_state_attention=initial_state_attention)
  File "/home/yy/virtualenv/env1/local/lib/python2.7/site-packages/tensorflow/python/ops/seq2seq.py", line 621, in embedding_attention_decoder
    initial_state_attention=initial_state_attention)
  File "/home/yy/virtualenv/env1/local/lib/python2.7/site-packages/tensorflow/python/ops/seq2seq.py", line 530, in attention_decoder
    cell_output, state = cell(x, state)
  File "/home/yy/virtualenv/env1/local/lib/python2.7/site-packages/tensorflow/python/ops/rnn_cell.py", line 663, in __call__
    cur_inp, new_state = cell(cur_inp, cur_state)

**Comment by girving** [comment]
@prb12: Did you get a chance to look at this?

**Comment by prb12** [comment]
Could you please clarify what you mean by 
"Just run translate.py with 10M pairs training data." ?
Are you saying that you're trying to run with a batch_size argument of 10 million?

Could you please provide the exact command line you used, along with any changes to translate.py, and it would also be helpful to know what GPU configuration you have (e.g. the output of nvidia-smi)

**Comment by michaelisard** [comment]
Closing due to lack of response. Please reopen if you have more information.

**Comment by znculee** [comment]
Use small model will work.
python translate.py
  --data_dir [your_data_directory] --train_dir [checkpoints_directory]
  --size=256 --num_layers=2 --steps_per_checkpoint=50

**Comment by znculee** [comment]
Default parameters in translate are set to quite large values. Large models trained over a long time give good results, but it might take too long or use too much memory for your GPU. You can request to train a smaller model as in the following example.
``` python
python translate.py
  --data_dir [your_data_directory] --train_dir [checkpoints_directory]
  --size=256 --num_layers=2 --steps_per_checkpoint=50
```
