### ISSUE TITLE
ValueError: Batch length of predictions should be same

### ISSUE THREAD

**Issue by PierreBoyeau** [tensorflow/tensorflow#15715]
Hi,

I'm trying to visualize the output of a convolutional autoencoder using TensorFlow Estimator API.
I use 64*64 images stored in a Numpy array as input, and use `tf.estimator.inputs.numpy_input_fn` to feed this input to my estimator.
Everything works perfectly fine during training, but as soon as I try to do predictions, it seems that I have an issue with my input_fn.
Please forgive me in advance, I am not 100% sure this is a bug, but I think I have tried everything I had in mind.

```
input_fn = tf.estimator.inputs.numpy_input_fn(
    x={"x": train_data},
    y=None,
    batch_size=8,
    num_epochs=None,
    shuffle=True)

autoencoder = tf.estimator.Estimator(model_fn=autoencoder_model_fn, model_dir=model_dir)
tensors_to_log = {"loss": "loss"}
logging_hook = tf.train.LoggingTensorHook(tensors=tensors_to_log, every_n_iter=1000)

autoencoder.train(
    input_fn=input_fn,
    steps=50000,
    hooks=[logging_hook])

input_fn_predict = tf.estimator.inputs.numpy_input_fn(
    x={"x": train_data},
    y=None,
    batch_size=1,
    num_epochs=None,
    shuffle=False)
predictions = autoencoder.predict(input_fn=input_fn_predict)
predictions = [p['decoded_image'] for p in predictions]
print predictions[0].shape
```
I tried among other things to set `batch_size` to the same value for both input_fn, but it doesn't work and I get the following error : 
```bash 
Traceback (most recent call last):
  File "AutoEncoder.py", line 164, in <module>
    main()
  File "AutoEncoder.py", line 157, in main
    predictions = [p['decoded_image'] for p in predictions]
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 425, in predict
    for i in range(self._extract_batch_length(preds_evaluated)):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 592, in _extract_batch_length
    'different batch length then others.' % key)
ValueError: Batch length of predictions should be same. features has different batch length then others.
```

Can anybody see what's wrong?
Thanks in advance :)

**Comment by jzhongaa** [comment]
Same here. Wonder if there is any solution towords it. Tks

**Comment by HELIN007** [comment]
The batch_size of function input_fn and input_fn_predict should be the same.
This works for me.
