### ISSUE TITLE
Crash on retraining flowers

### ISSUE THREAD

**Issue by ricochet2200** [tensorflow/tensorflow#1582]
I am following the tutorial [How to Retrain Inception's Final Layer for New Categories](https://www.tensorflow.org/versions/master/how_tos/image_retraining/index.html) but am getting this error:   
```
...
3600 bottleneck files created.
Traceback (most recent call last):
  File "/Users/rick/tensorflow/bazel-bin/tensorflow/examples/image_retraining/retrain.runfiles/tensorflow/examples/image_retraining/retrain.py", line 829, in <module>
    tf.app.run()
  File "/Users/rick/tensorflow/bazel-bin/tensorflow/examples/image_retraining/retrain.runfiles/tensorflow/python/platform/default/_app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "/Users/rick/tensorflow/bazel-bin/tensorflow/examples/image_retraining/retrain.runfiles/tensorflow/examples/image_retraining/retrain.py", line 785, in main
    ground_truth_tensor: train_ground_truth})
  File "/Users/rick/tensorflow/bazel-bin/tensorflow/examples/image_retraining/retrain.runfiles/tensorflow/python/client/session.py", line 332, in run
    result = self._run(None, fetches, feed_dict, options_ptr, run_outputs_ptr)
  File "/Users/rick/tensorflow/bazel-bin/tensorflow/examples/image_retraining/retrain.runfiles/tensorflow/python/client/session.py", line 530, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (100, 2048) for Tensor u'pool_3/_reshape:0', which has shape '(1, 2048)'
```

### Environment info
Operating System: OSX  10.11.1 El Capitan

I've installed from source from this commit `ad1d98011ebc`.  I ran `./configure` with the default answers and followed [these build instructions](https://www.tensorflow.org/versions/master/get_started/os_setup.html#installation-for-mac-os-x)

### Steps to reproduce
```
cd ~
curl -O http://download.tensorflow.org/example_images/flower_photos.tgz
tar xzf flower_photos.tgz
bazel build -c opt --copt=-mavx tensorflow/examples/image_retraining:retrain
# Crashes with error above
bazel-bin/tensorflow/examples/image_retraining/retrain --image_dir ~/flower_photos
```

### What have you tried?
1.  I've tried deleting `/tmp/bottleneck` and re-running, but I got the same error.

**Comment by sherrym** [comment]
Could you try passing in the following argument:

bazel-bin/tensorflow/examples/image_retraining/retrain --train_batch_size=1 --image_dir ~/flower_photos

Sherry

**Comment by ricochet2200** [comment]
I ran it and it still crashed, although the output and stack trace is a little different.  Here is the relevant output:

```
...
3600 bottleneck files created.
2016-03-23 10:03:18.932934: Step 0: Train accuracy = 100.0%
2016-03-23 10:03:18.933883: Step 0: Cross entropy = 0.116586
Traceback (most recent call last):
  File "/Users/rick/tensorflow/bazel-bin/tensorflow/examples/image_retraining/retrain.runfiles/tensorflow/examples/image_retraining/retrain.py", line 829, in <module>
    tf.app.run()
  File "/Users/rick/tensorflow/bazel-bin/tensorflow/examples/image_retraining/retrain.runfiles/tensorflow/python/platform/default/_app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "/Users/rick/tensorflow/bazel-bin/tensorflow/examples/image_retraining/retrain.runfiles/tensorflow/examples/image_retraining/retrain.py", line 804, in main
    ground_truth_tensor: validation_ground_truth})
  File "/Users/rick/tensorflow/bazel-bin/tensorflow/examples/image_retraining/retrain.runfiles/tensorflow/python/client/session.py", line 332, in run
    result = self._run(None, fetches, feed_dict, options_ptr, run_outputs_ptr)
  File "/Users/rick/tensorflow/bazel-bin/tensorflow/examples/image_retraining/retrain.runfiles/tensorflow/python/client/session.py", line 530, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (100, 2048) for Tensor u'pool_3/_reshape:0', which has shape '(1, 2048)'
```

**Comment by pmmucsd** [comment]
If you set test_batch_size, validation_batch_size and train_batch_size all to 1 it works. But that's probably not what you want.

**Comment by petewarden** [comment]
I looked into this, and it appears to have broken when the new shape strictness checking went into effect:
https://github.com/tensorflow/tensorflow/commit/9a8c5ad18c61cb0695d31e2ce969008c82999c7c

Unfortunately, the input we're feeding in is not a placeholder, but is an override of a regular node that's loaded from the graph def, so it's not clear from the examples how to fix the error in this case. Passing over to @mrry for advice on the best way to fix this.

**Comment by mrry** [comment]
Right, you need to replace the node `"pool_3/_reshape:0"` with a `tf.placeholder_with_default(tf.reshape(...), shape=[None, 2048])`.

Would one of you be a dear and show me where this graph is created? Then I can send a PR or make the appropriate changes. If as I fear it's using a binary graph downloaded the website, we might need to mint a new graph.

**Comment by petewarden** [comment]
> If as I fear it's using a binary graph downloaded the website, we might need to mint a new graph.

Your fear is correct, and it's actually even worse, because we also need to save the result out to a binary file, so we'll have to do any swapouts twice. Here's the place where the loading is done:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/image_retraining/retrain.py#L291

Here's where we save it out again at the end:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/image_retraining/retrain.py#L820

**Comment by mrry** [comment]
Oh, maybe it's not so bad then: in `create_inception_graph()` you can specify `{BOTTLENECK_TENSOR_NAME: some_placeholder_tensor}` as the `input_map` argument. That way, you can define the placeholder to be whatever shape you want it to be in `retrain.py`, and you won't have to modify the original binary graph!

**Comment by petewarden** [comment]
Thanks Derek! I'll see if I can get your help on this tomorrow, since I'm still a bit lost. I expected that changing input_map would mean that the original Reshape node would be inaccessible when I ran the full graph?

**Comment by mrry** [comment]
Absolutely, let's talk tomorrow! (Using `input_map` would modify all consumers of the reshape node so that they took the placeholder instead. In the present implementation, the reshape node would actually still be in the graph, but nothing would be connected to it, and it probably wouldn't ever be executed.)

**Comment by trentmccormick** [comment]
I'm getting the exact same issue as @ricochet2200  with the shape of `Tensor u'pool_3/_reshape:0'` except I'm running on Ubuntu 14.04 and commit `46bfa0feef`

> Right, you need to replace the node "pool_3/_reshape:0" with a tf.placeholder_with_default(tf.reshape(...), shape=[None, 2048]).

Where can I find the node?

**Comment by petewarden** [comment]
We have just got a fix completed and approved, I should be able to check it in this evening. Apologies for the breakage!

**Comment by petewarden** [comment]
Sorry for the delay, I have this working on our internal repo, but there are some hiccups on exporting it to Github. I should be able to get this released on Monday morning.

**Comment by trentmccormick** [comment]
Thanks!  I followed your tutorial on getting it set up on Docker and that worked but it doesn't utilize my GPU.

**Comment by petewarden** [comment]
The fixed version should now be in the top-of-tree code. Please let me know if you're still having issues:

https://github.com/tensorflow/tensorflow/commit/3ca08f75896d733d12d7106f76abf51e782f50da

**Comment by forfish** [comment]
I also got this error!Please help!
`Traceback (most recent call last):
  File "/home/user01/Documents/tensorflow/bazel-bin/tensorflow/examples/image_retraining/retrain.runfiles/tensorflow/examples/image_retraining/retrain.py", line 835, in <module>
    tf.app.run()
  File "/home/user01/Documents/tensorflow/bazel-bin/tensorflow/examples/image_retraining/retrain.runfiles/tensorflow/python/platform/default/_app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "/home/user01/Documents/tensorflow/bazel-bin/tensorflow/examples/image_retraining/retrain.runfiles/tensorflow/examples/image_retraining/retrain.py", line 791, in main
    ground_truth_tensor: train_ground_truth})
  File "/home/user01/Documents/tensorflow/bazel-bin/tensorflow/examples/image_retraining/retrain.runfiles/tensorflow/python/client/session.py", line 332, in run
    result = self._run(None, fetches, feed_dict, options_ptr, run_outputs_ptr)
  File "/home/user01/Documents/tensorflow/bazel-bin/tensorflow/examples/image_retraining/retrain.runfiles/tensorflow/python/client/session.py", line 530, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (100, 2048) for Tensor 'pool_3/_reshape:0', which has shape '(1, 2048)'`

**Comment by ricochet2200** [comment]
I verified this and it is indeed working as expected.  Thanks everyone!

**Comment by padmalcom** [comment]
The error _ValueError: Cannot feed value of shape (100, 2048) for Tensor 'pool_3/_reshape:0
', which has shape '(1, 2048)'_ still occurs for the current build _#202 (08.06.2017 02:25:00)_ (tensorflow 1.2.0 rc1) on Windows 7.
