### ISSUE TITLE
gradient function missing for odeint

### ISSUE THREAD

**Issue by LionSR** [tensorflow/tensorflow#15833]
I am trying to program a optimization problem using TensorFlow. The cost function depends on the outcome of an ODE solved by TensorFlow. However I find that TensorFlow's auto differential does not support the function which contains odeint.

odeint: tensorflow.org/api_docs/python/tf/contrib/integrate/odeint

It would great be of great help if we could have it.

Have I written custom code: N/A
OS Platform and Distribution: Ubuntu 16.04 
TensorFlow installed from: official website pip 
TensorFlow version: 14.01
Bazel version: N/A
CUDA/cuDNN version: 8.0
GPU model and memory: GTX1080Ti, not relevant
Exact command to reproduce: N/A

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by LionSR** [comment]
I don't think this problem has been solved @tensorflowbutler

**Comment by shoyer** [comment]
@LionSR Can you provide code that reproduces this issue and report the error message you find?

As a simple example, here how you could modify the Lorenz equation example from the docs to optimize the initial conditions for the ODE:
```python
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

rho = 28.0
sigma = 10.0
beta = 8.0/3.0

def lorenz_equation(state, t):
  x, y, z = tf.unstack(state)
  dx = sigma * (y - x)
  dy = x * (rho - z) - y
  dz = x * y - beta * z
  return tf.stack([dx, dy, dz])

target = tf.constant([0, 2, 20], dtype=tf.float64)
init_state = tf.Variable(target)
t = np.linspace(0, 0.5, num=100)
tensor_state, tensor_info = tf.contrib.integrate.odeint(
    lorenz_equation, init_state, t, full_output=True)

loss = tf.reduce_sum((tensor_state[-1] - target) ** 2)
train_step = tf.train.GradientDescentOptimizer(5e-2).minimize(loss)

sess = tf.Session()
sess.run(tf.global_variables_initializer())
losses = []
trajectories = []
for i in range(100):
  loss_eval, trajectory, _ = sess.run([loss, tensor_state, train_step])
  losses.append(loss_eval)
  trajectories.append(trajectory)
  if i % 10 == 0:
    print(loss_eval)
```
It doesn't entirely converge (this problem is probably non-convex), but the loss decreases over time. The program prints:
```
663.541165873
4.66117861453
3.95432178915
3.5868347332
3.37596507952
3.25978177698
3.19799942176
3.16602229662
3.14980148132
3.14169093144
```

**Comment by tensorflowbutler** [comment]
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by reedwm** [comment]
Closing due to a lack of a response.

**Comment by seb1000** [comment]
The issue is not resolved, at least when manually recoring the gradient on tapes.
To be precise, it is not  possible to compute the gradients of the results of odeint.
This minimal example:

```
import tensorflow as tf

def f(x, t):
    return 2*x

x_init = tf.ones((1))
t_list = tf.range(0, 10, 0.01)

with tf.GradientTape(persistent=True) as tape:
    tape.watch(x_init)
    run = tf.contrib.integrate.odeint(f, y0=x_init, t = t_list)

diff = tape.gradient(run, x_init)
```

raises the following error:

Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2862, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-e630f0280360>", line 12, in <module>
    diff = tape.gradient(run, x_init)
  File "/opt/anaconda3/lib/python3.6/site-packages/tensorflow/python/eager/backprop.py", line 851, in gradient
    output_gradients=output_gradients)
  File "/opt/anaconda3/lib/python3.6/site-packages/tensorflow/python/eager/imperative_grad.py", line 63, in imperative_grad
    tape._tape, vspace, target, sources, output_gradients)  # pylint: disable=protected-access
  File "/opt/anaconda3/lib/python3.6/site-packages/tensorflow/python/eager/backprop.py", line 116, in _gradient_function
    return grad_fn(mock_op, *out_grads)
  File "/opt/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/tensor_array_grad.py", line 158, in _TensorArrayGatherGrad
    grad_source = _GetGradSource(grad)
  File "/opt/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/tensor_array_grad.py", line 74, in _GetGradSource
    ", got: %s" % op_or_tensor.name)
ValueError: Expected op/tensor name to start with gradients (excluding scope), got: Const:0

I am using tf version 1.13.1

**Comment by shoyer** [comment]
We are porting `odeint` over into [TensorFlow Probability](https://github.com/tensorflow/probability) (tf.contrib is being removed in TensorFlow 2.0) -- see https://github.com/tensorflow/probability/tree/master/tensorflow_probability/python/math/ode.

It would be good to check if gradients work there -- it's unlikely we will fix this here given the deprecated status of tf.contrib.

**Comment by seb1000** [comment]
I tried with tf-nightly and tfp-nightly (the tfp release does not yet include ode), and the ode solver is not differentiable with gradient tapes. When trying to differentiate the result of the solver, the gradient function returns None ( see below).
Or maybe I am getting something wrong, and differentiation works differently in tensorflow-probability? I just used the solver from tfp, and the rest I left as ik works in pure tf.

```import tensorflow as tf

import tensorflow_probability as tfp

def f(x, t):
    return 2*x

x_init = tf.ones((1))
t_list = tf.range(0, 10, 1.)

with tf.GradientTape(persistent=True) as tape:
    tape.watch(x_init)
    solver = tfp.math.ode.BDF()
    times, states, _,_ = solver.solve(f, initial_time=t_list[0], initial_state=x_init, solution_times=t_list)

diff = tape.gradient(states, x_init)
# diff is None
print(diff)```

**Comment by shoyer** [comment]
@seb1000 thanks for giving this a try, it looks like this should work. I just opened https://github.com/tensorflow/probability/issues/405 to discuss this in TF-probability

**Comment by seb1000** [comment]
thanks for opening it in TF-probability, I will follow it there.
