### ISSUE TITLE
【TensorFlow Servering】 bazel build tensorflow_serving/... ImportError: No module named numpy

### ISSUE THREAD

**Issue by stealingchen** [tensorflow/tensorflow#15904]
fong@ubuntu:~/serving$ bazel build tensorflow_serving/...
..........
DEBUG: /home/fong/.cache/bazel/_bazel_fong/38e1867f819d663d91548408e483d3bf/external/bazel_tools/tools/build_defs/pkg/pkg.bzl:197:9: @//tensorflow_serving/model_servers:tensorflow_model_server_tar: you provided a non dictionary to the pkg_tar `files` attribute. This attribute was renamed to `srcs`. Consider renaming it in your BUILD file.

ERROR: /home/fong/.cache/bazel/_bazel_fong/38e1867f819d663d91548408e483d3bf/external/org_tensorflow/third_party/py/numpy/BUILD:11:1: no such package '@local_config_python//': Traceback (most recent call last):
	File "/home/fong/.cache/bazel/_bazel_fong/38e1867f819d663d91548408e483d3bf/external/org_tensorflow/third_party/py/python_configure.bzl", line 291
		_create_local_python_repository(repository_ctx)
	File "/home/fong/.cache/bazel/_bazel_fong/38e1867f819d663d91548408e483d3bf/external/org_tensorflow/third_party/py/python_configure.bzl", line 255, in _create_local_python_repository
		_get_numpy_include(repository_ctx, python_bin)
	File "/home/fong/.cache/bazel/_bazel_fong/38e1867f819d663d91548408e483d3bf/external/org_tensorflow/third_party/py/python_configure.bzl", line 239, in _get_numpy_include
		_execute(repository_ctx, [python_bin, "-c",..."], <2 more arguments>)
	File "/home/fong/.cache/bazel/_bazel_fong/38e1867f819d663d91548408e483d3bf/external/org_tensorflow/third_party/py/python_configure.bzl", line 54, in _execute
		_fail("\n".join([error_msg.strip() if ... ""]))
	File "/home/fong/.cache/bazel/_bazel_fong/38e1867f819d663d91548408e483d3bf/external/org_tensorflow/third_party/py/python_configure.bzl", line 27, in _fail
		fail(("%sPython Configuration Error:%...)))
Python Configuration Error: Problem getting numpy include path.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named numpy
Is numpy installed?
 and referenced by '@org_tensorflow//third_party/py/numpy:headers'
ERROR: Analysis of target '//tensorflow_serving/example:inception_saved_model' failed; build aborted: Loading failed
INFO: Elapsed time: 35.784s
FAILED: Build did NOT complete successfully (149 packages loaded)
    currently loading: @org_tensorflow//tensorflow/contrib/rnn ... (6 packages\
)

This is the error，but  my python paths and python library path is true,python library path have numpy already.

fong@ubuntu:~/serving/tensorflow$ ./configure 
You have bazel 0.9.0 installed.
Please specify the location of python. [Default is /home/fong/anaconda3/bin/python]: 

Found possible Python library paths:
  /home/fong/anaconda3/lib/python3.5/site-packages
Please input the desired Python library path to use.  Default is [/home/fong/anaconda3/lib/python3.5/site-packages]

Do you wish to build TensorFlow with jemalloc as malloc support? [Y/n]: y
jemalloc as malloc support will be enabled for TensorFlow.

Do you wish to build TensorFlow with Google Cloud Platform support? [Y/n]: y
Google Cloud Platform support will be enabled for TensorFlow.

Do you wish to build TensorFlow with Hadoop File System support? [Y/n]: y
Hadoop File System support will be enabled for TensorFlow.

Do you wish to build TensorFlow with Amazon S3 File System support? [Y/n]: y
Amazon S3 File System support will be enabled for TensorFlow.

Do you wish to build TensorFlow with XLA JIT support? [y/N]: y
XLA JIT support will be enabled for TensorFlow.

Do you wish to build TensorFlow with GDR support? [y/N]: y
GDR support will be enabled for TensorFlow.

Do you wish to build TensorFlow with VERBS support? [y/N]: y
VERBS support will be enabled for TensorFlow.

Do you wish to build TensorFlow with OpenCL SYCL support? [y/N]: n
No OpenCL SYCL support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: n
No CUDA support will be enabled for TensorFlow.

Do you wish to build TensorFlow with MPI support? [y/N]: n
No MPI support will be enabled for TensorFlow.

Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native]: 

Add "--config=mkl" to your bazel command to build with MKL support.
Please note that MKL on MacOS or windows is still not supported.
If you would like to use a local MKL instead of downloading, please set the environment variable "TF_MKL_ROOT" every time before build.

Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]: n
Not configuring the WORKSPACE for Android builds.

Configuration finished

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by lkluo** [comment]
@tensorflowbutler: Hi, I encountered the similar errors (also posted in serving issues, but have not got response yet; the issue: https://github.com/tensorflow/serving/issues/930)
> ERROR: /root/.cache/bazel/_bazel_root/71fb59ccb20e34305f765068f873db73/external/org_tensorflow/util/python/BUILD:5:1: no such package '@local_config_python//': Traceback (most recent call last):
File "/root/.cache/bazel/_bazel_root/71fb59ccb20e34305f765068f873db73/external/org_tensorflow/third_party/py/python_configure.bzl", line 291
_create_local_python_repository(repository_ctx)
File "/root/.cache/bazel/_bazel_root/71fb59ccb20e34305f765068f873db73/external/org_tensorflow/third_party/py/python_configure.bzl", line 255, in _create_local_python_repository
_get_numpy_include(repository_ctx, python_bin)
File "/root/.cache/bazel/_bazel_root/71fb59ccb20e34305f765068f873db73/external/org_tensorflow/third_party/py/python_configure.bzl", line 239, in _get_numpy_include
_execute(repository_ctx, [python_bin, "-c",..."], <2 more arguments>)
File "/root/.cache/bazel/_bazel_root/71fb59ccb20e34305f765068f873db73/external/org_tensorflow/third_party/py/python_configure.bzl", line 54, in _execute
_fail("\n".join([error_msg.strip() if ... ""]))
File "/root/.cache/bazel/_bazel_root/71fb59ccb20e34305f765068f873db73/external/org_tensorflow/third_party/py/python_configure.bzl", line 27, in _fail
fail(("%sPython Configuration Error:%...)))
Python Configuration Error: Problem getting numpy include path.
Traceback (most recent call last):
File "", line 1, in 
ImportError: No module named numpy
Is numpy installed?
and referenced by '@org_tensorflow//util/python:python_headers'
ERROR: Analysis of target '//tensorflow_serving/servables/tensorflow/testdata:export_bad_half_plus_two' failed; build aborted: Loading failed

Here are my responses:

> Have I written custom code 
-> no
> OS Platform and Distribution
-> CentOS 7
> TensorFlow installed from
-> pip
> TensorFlow version
-> 1.8
> Bazel version
-> 0.10.0/0.11.1/0.14.1 all three have been tried
> CUDA/cuDNN version
-> 9.0/7.x For the timing being, I use CPU only, and will switch to GPU in future. 
> GPU model and memory
-> Tesla P100 with 16G RAM
> Exact command to reproduce
->`bazel build -c opt tensorflow_serving/...`
