### ISSUE TITLE
android CameraActivity: Exception!

### ISSUE THREAD

**Issue by javantiger720** [tensorflow/tensorflow#15935]
tensorflow: CameraActivity: Exception!
java.lang.RuntimeException: Error initializing box priors from file:///android_asset/multibox_location_priors.txt
                                                                     at org.tensorflow.demo.TensorFlowMultiBoxDetector.create(TensorFlowMultiBoxDetector.java:121)
                                                                     at org.tensorflow.demo.DetectorActivity.onPreviewSizeChosen(DetectorActivity.java:146)
                                                                     at org.tensorflow.demo.CameraActivity.onPreviewFrame(CameraActivity.java:120)
                                                                     at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1189)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                     at android.os.Looper.loop(Looper.java:135)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5372)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1117)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810)

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
It has been 15 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
We are closing this issue for now due to lack of activity. Please comment if this is still an issue for you. Thanks!
