### ISSUE TITLE
DataLossError when loading saved model from r1.4 (Unable to read file ... failed to seek to header entry)

### ISSUE THREAD

**Issue by ahmed-shariff** [tensorflow/tensorflow#15945]
I have a few saved models stored, these were built using _version 1.2.0-rc1_ 
When I try to load any of these saved models using _version 1.4.1_, I get the following error:
```
INFO:tensorflow:Restoring parameters from b'../models/export_output/1510150323/variables/variables'
2018-01-08 19:42:35.838751: W tensorflow/core/framework/op_kernel.cc:1192] Data loss: Unable to read file (../models/export_output/1510150323/variables/variables.index). Perhaps the file is corrupt or was produced by a newer version of TensorFlow with format changes (failed to seek to header entry): corrupted compressed block contents
--------quite a few entries of the above log-------------
2018-01-08 19:42:36.134122: W tensorflow/core/framework/op_kernel.cc:1192] Data loss: Unable to read file (../models/export_output/1510150323/variables/variables.index). Perhaps the file is corrupt or was produced by a newer version of TensorFlow with format changes (failed to seek to header entry): corrupted compressed block contents
2018-01-08 19:42:36.134144: W tensorflow/core/framework/op_kernel.cc:1192] Data loss: Unable to read file (../models/export_output/1510150323/variables/variables.index). Perhaps the file is corrupt or was produced by a newer version of TensorFlow with format changes (failed to seek to header entry): corrupted compressed block contents
2018-01-08 19:42:36.134177: W tensorflow/core/framework/op_kernel.cc:1192] Data loss: Unable to read file (../models/export_output/1510150323/variables/variables.index). Perhaps the file is corrupt or was produced by a newer version of TensorFlow with format changes (failed to seek to header entry): corrupted compressed block contents
Traceback (most recent call last):
  File "/home/amsha/virtualenv/tf14-no-gpu-p3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1323, in _do_call
    return fn(*args)
  File "/home/amsha/virtualenv/tf14-no-gpu-p3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1302, in _run_fn
    status, run_metadata)
  File "/home/amsha/virtualenv/tf14-no-gpu-p3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.DataLossError: Unable to read file (../models/export_output/1510150323/variables/variables.index). Perhaps the file is corrupt or was produced by a newer version of TensorFlow with format changes (failed to seek to header entry): corrupted compressed block contents
	 [[Node: save_1/RestoreV2_159 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save_1/Const_0_0, save_1/RestoreV2_159/tensor_names, save_1/RestoreV2_159/shape_and_slices)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/media/Files/Research/FoodClassification/deployment/deployment.py", line 308, in _main
    tf.saved_model.loader.load(sess, [tf.saved_model.tag_constants.SERVING], EXPORT_MODEL_DIR)
  File "/home/amsha/virtualenv/tf14-no-gpu-p3/lib/python3.6/site-packages/tensorflow/python/saved_model/loader_impl.py", line 226, in load
    saver.restore(sess, variables_path)
  File "/home/amsha/virtualenv/tf14-no-gpu-p3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1666, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/amsha/virtualenv/tf14-no-gpu-p3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/home/amsha/virtualenv/tf14-no-gpu-p3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/amsha/virtualenv/tf14-no-gpu-p3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/home/amsha/virtualenv/tf14-no-gpu-p3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.DataLossError: Unable to read file (../models/export_output/1510150323/variables/variables.index). Perhaps the file is corrupt or was produced by a newer version of TensorFlow with format changes (failed to seek to header entry): corrupted compressed block contents
	 [[Node: save_1/RestoreV2_159 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save_1/Const_0_0, save_1/RestoreV2_159/tensor_names, save_1/RestoreV2_159/shape_and_slices)]]

Caused by op 'save_1/RestoreV2_159', defined at:
  File "<stdin>", line 1, in <module>
  File "/media/Files/Research/FoodClassification/deployment/deployment.py", line 308, in _main
    tf.saved_model.loader.load(sess, [tf.saved_model.tag_constants.SERVING], EXPORT_MODEL_DIR)
  File "/home/amsha/virtualenv/tf14-no-gpu-p3/lib/python3.6/site-packages/tensorflow/python/saved_model/loader_impl.py", line 216, in load
    saver = tf_saver.import_meta_graph(meta_graph_def_to_load, **saver_kwargs)
  File "/home/amsha/virtualenv/tf14-no-gpu-p3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1810, in import_meta_graph
    **kwargs)
  File "/home/amsha/virtualenv/tf14-no-gpu-p3/lib/python3.6/site-packages/tensorflow/python/framework/meta_graph.py", line 660, in import_scoped_meta_graph
    producer_op_list=producer_op_list)
  File "/home/amsha/virtualenv/tf14-no-gpu-p3/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 313, in import_graph_def
    op_def=op_def)
  File "/home/amsha/virtualenv/tf14-no-gpu-p3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/home/amsha/virtualenv/tf14-no-gpu-p3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

DataLossError (see above for traceback): Unable to read file (../models/export_output/1510150323/variables/variables.index). Perhaps the file is corrupt or was produced by a newer version of TensorFlow with format changes (failed to seek to header entry): corrupted compressed block contents
	 [[Node: save_1/RestoreV2_159 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save_1/Const_0_0, save_1/RestoreV2_159/tensor_names, save_1/RestoreV2_159/shape_and_slices)]]
```
I was able to load the same models in _version 1.2.0-rc1_.
I tried building a new saved model using _version 1.4.1_ , that I was able to load in both versions without any problems. 

The versions I tested were both built, without cuda. 
OS: arch linux

**Comment by allenlavoie** [comment]
Could you try in 1.5RC0? Header compression was accidentally disabled in 1.4.

**Comment by ahmed-shariff** [comment]
I have to build it. Yes, i'll try it and let you know.

**Comment by tensorflowbutler** [comment]
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?
