### ISSUE TITLE
FasterRCNN error

### ISSUE THREAD

**Issue by chiru83** [tensorflow/tensorflow#16035]
Hi friends. 
While  i am trying to execute tensor flow based faster RCNN, i got the following error. 
please help me how to solve this.

tensorflow.python.framework.errors_impl.InternalError: WhereOp: Could not launch cub::DeviceReduce::Sum to count number of true indices.  temp_storage_bytes: 2815, status: invalid device function

**Comment by chiru83** [comment]
This is the complete error

018-01-11 06:05:49.066479: W tensorflow/core/framework/op_kernel.cc:1192] Internal: WhereOp: Could not launch cub::DeviceReduce::Sum to count number of true indices.  temp_storage_bytes: 2815, status: invalid device function
2018-01-11 06:05:49.066923: W tensorflow/core/framework/op_kernel.cc:1192] Internal: WhereOp: Could not launch cub::DeviceReduce::Sum to count number of true indices.  temp_storage_bytes: 2815, status: invalid device function
	 [[Node: LOSS_default/Where = Where[_device="/job:localhost/replica:0/task:0/gpu:0"](LOSS_default/NotEqual/_411)]]
2018-01-11 06:05:49.094692: W tensorflow/core/framework/op_kernel.cc:1192] Internal: WhereOp: Could not launch cub::DeviceReduce::Sum to count number of true indices.  temp_storage_bytes: 2815, status: invalid device function
	 [[Node: LOSS_default/Where = Where[_device="/job:localhost/replica:0/task:0/gpu:0"](LOSS_default/NotEqual/_411)]]
2018-01-11 06:05:49.094692: W tensorflow/core/framework/op_kernel.cc:1192] Internal: WhereOp: Could not launch cub::DeviceReduce::Sum to count number of true indices.  temp_storage_bytes: 2815, status: invalid device function
	 [[Node: LOSS_default/Where = Where[_device="/job:localhost/replica:0/task:0/gpu:0"](LOSS_default/NotEqual/_411)]]
2018-01-11 06:05:49.094700: W tensorflow/core/framework/op_kernel.cc:1192] Internal: WhereOp: Could not launch cub::DeviceReduce::Sum to count number of true indices.  temp_storage_bytes: 2815, status: invalid device function
	 [[Node: LOSS_default/Where = Where[_device="/job:localhost/replica:0/task:0/gpu:0"](LOSS_default/NotEqual/_411)]]
2018-01-11 06:05:49.094705: W tensorflow/core/framework/op_kernel.cc:1192] Internal: WhereOp: Could not launch cub::DeviceReduce::Sum to count number of true indices.  temp_storage_bytes: 2815, status: invalid device function
	 [[Node: LOSS_default/Where = Where[_device="/job:localhost/replica:0/task:0/gpu:0"](LOSS_default/NotEqual/_411)]]
2018-01-11 06:05:49.094712: W tensorflow/core/framework/op_kernel.cc:1192] Internal: WhereOp: Could not launch cub::DeviceReduce::Sum to count number of true indices.  temp_storage_bytes: 2815, status: invalid device function
	 [[Node: LOSS_default/Where = Where[_device="/job:localhost/replica:0/task:0/gpu:0"](LOSS_default/NotEqual/_411)]]
Traceback (most recent call last):
  File "/home/rtcin/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1327, in _do_call
    return fn(*args)
  File "/home/rtcin/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1306, in _run_fn
    status, run_metadata)
  File "/home/rtcin/anaconda3/lib/python3.6/contextlib.py", line 89, in __exit__
    next(self.gen)
  File "/home/rtcin/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InternalError: WhereOp: Could not launch cub::DeviceReduce::Sum to count number of true indices.  temp_storage_bytes: 2815, status: invalid device function
	 [[Node: LOSS_default/Where = Where[_device="/job:localhost/replica:0/task:0/gpu:0"](LOSS_default/NotEqual/_411)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./tools/trainval_net.py", line 140, in <module>
    max_iters=args.max_iters)
  File "/home/cnk1kor/FasterRCNN/tf-faster-rcnn-master/tools/../lib/model/train_val.py", line 400, in train_net
    sw.train_model(sess, max_iters)
  File "/home/cnk1kor/FasterRCNN/tf-faster-rcnn-master/tools/../lib/model/train_val.py", line 311, in train_model
    self.net.train_step(sess, blobs, train_op)
  File "/home/cnk1kor/FasterRCNN/tf-faster-rcnn-master/tools/../lib/nets/network.py", line 465, in train_step
    feed_dict=feed_dict)
  File "/home/rtcin/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/home/rtcin/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/rtcin/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    options, run_metadata)
  File "/home/rtcin/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: WhereOp: Could not launch cub::DeviceReduce::Sum to count number of true indices.  temp_storage_bytes: 2815, status: invalid device function
	 [[Node: LOSS_default/Where = Where[_device="/job:localhost/replica:0/task:0/gpu:0"](LOSS_default/Not

**Comment by chiru83** [comment]
018-01-11 06:05:49.066479: W tensorflow/core/framework/op_kernel.cc:1192] Internal: WhereOp: Could not launch cub::DeviceReduce::Sum to count number of true indices.  temp_storage_bytes: 2815, status: invalid device function
2018-01-11 06:05:49.066923: W tensorflow/core/framework/op_kernel.cc:1192] Internal: WhereOp: Could not launch cub::DeviceReduce::Sum to count number of true indices.  temp_storage_bytes: 2815, status: invalid device function
	 [[Node: LOSS_default/Where = Where[_device="/job:localhost/replica:0/task:0/gpu:0"](LOSS_default/NotEqual/_411)]]
2018-01-11 06:05:49.094692: W tensorflow/core/framework/op_kernel.cc:1192] Internal: WhereOp: Could not launch cub::DeviceReduce::Sum to count number of true indices.  temp_storage_bytes: 2815, status: invalid device function
	 [[Node: LOSS_default/Where = Where[_device="/job:localhost/replica:0/task:0/gpu:0"](LOSS_default/NotEqual/_411)]]
2018-01-11 06:05:49.094692: W tensorflow/core/framework/op_kernel.cc:1192] Internal: WhereOp: Could not launch cub::DeviceReduce::Sum to count number of true indices.  temp_storage_bytes: 2815, status: invalid device function
	 [[Node: LOSS_default/Where = Where[_device="/job:localhost/replica:0/task:0/gpu:0"](LOSS_default/NotEqual/_411)]]
2018-01-11 06:05:49.094700: W tensorflow/core/framework/op_kernel.cc:1192] Internal: WhereOp: Could not launch cub::DeviceReduce::Sum to count number of true indices.  temp_storage_bytes: 2815, status: invalid device function
	 [[Node: LOSS_default/Where = Where[_device="/job:localhost/replica:0/task:0/gpu:0"](LOSS_default/NotEqual/_411)]]
2018-01-11 06:05:49.094705: W tensorflow/core/framework/op_kernel.cc:1192] Internal: WhereOp: Could not launch cub::DeviceReduce::Sum to count number of true indices.  temp_storage_bytes: 2815, status: invalid device function
	 [[Node: LOSS_default/Where = Where[_device="/job:localhost/replica:0/task:0/gpu:0"](LOSS_default/NotEqual/_411)]]
2018-01-11 06:05:49.094712: W tensorflow/core/framework/op_kernel.cc:1192] Internal: WhereOp: Could not launch cub::DeviceReduce::Sum to count number of true indices.  temp_storage_bytes: 2815, status: invalid device function
	 [[Node: LOSS_default/Where = Where[_device="/job:localhost/replica:0/task:0/gpu:0"](LOSS_default/NotEqual/_411)]]
Traceback (most recent call last):
  File "/home/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1327, in _do_call
    return fn(*args)
  File "/home/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1306, in _run_fn
    status, run_metadata)
  File "/home/anaconda3/lib/python3.6/contextlib.py", line 89, in __exit__
    next(self.gen)
  File "/home/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InternalError: WhereOp: Could not launch cub::DeviceReduce::Sum to count number of true indices.  temp_storage_bytes: 2815, status: invalid device function
	 [[Node: LOSS_default/Where = Where[_device="/job:localhost/replica:0/task:0/gpu:0"](LOSS_default/NotEqual/_411)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./tools/trainval_net.py", line 140, in <module>
    max_iters=args.max_iters)
  File "/home/FasterRCNN/tf-faster-rcnn-master/tools/../lib/model/train_val.py", line 400, in train_net
    sw.train_model(sess, max_iters)
  File "/home/FasterRCNN/tf-faster-rcnn-master/tools/../lib/model/train_val.py", line 311, in train_model
    self.net.train_step(sess, blobs, train_op)
  File "/home/FasterRCNN/tf-faster-rcnn-master/tools/../lib/nets/network.py", line 465, in train_step
    feed_dict=feed_dict)
  File "/home/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/home/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    options, run_metadata)
  File "/home/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: WhereOp: Could not launch cub::DeviceReduce::Sum to count number of true indices.  temp_storage_bytes: 2815, status: invalid device function
	 [[Node: LOSS_default/Where = Where[_device="/job:localhost/replica:0/task:0/gpu:0"](LOSS_default/Not

**Comment by chiru83** [comment]
This is the complete error while , executing faster RCNN. please help me to resolve it. Thanks in advance.


018-01-11 06:05:49.066479: W tensorflow/core/framework/op_kernel.cc:1192] Internal: WhereOp: Could not launch cub::DeviceReduce::Sum to count number of true indices. temp_storage_bytes: 2815, status: invalid device function
2018-01-11 06:05:49.066923: W tensorflow/core/framework/op_kernel.cc:1192] Internal: WhereOp: Could not launch cub::DeviceReduce::Sum to count number of true indices. temp_storage_bytes: 2815, status: invalid device function
[[Node: LOSS_default/Where = Where_device="/job:localhost/replica:0/task:0/gpu:0"]]
2018-01-11 06:05:49.094692: W tensorflow/core/framework/op_kernel.cc:1192] Internal: WhereOp: Could not launch cub::DeviceReduce::Sum to count number of true indices. temp_storage_bytes: 2815, status: invalid device function
[[Node: LOSS_default/Where = Where_device="/job:localhost/replica:0/task:0/gpu:0"]]
2018-01-11 06:05:49.094692: W tensorflow/core/framework/op_kernel.cc:1192] Internal: WhereOp: Could not launch cub::DeviceReduce::Sum to count number of true indices. temp_storage_bytes: 2815, status: invalid device function
[[Node: LOSS_default/Where = Where_device="/job:localhost/replica:0/task:0/gpu:0"]]
2018-01-11 06:05:49.094700: W tensorflow/core/framework/op_kernel.cc:1192] Internal: WhereOp: Could not launch cub::DeviceReduce::Sum to count number of true indices. temp_storage_bytes: 2815, status: invalid device function
[[Node: LOSS_default/Where = Where_device="/job:localhost/replica:0/task:0/gpu:0"]]
2018-01-11 06:05:49.094705: W tensorflow/core/framework/op_kernel.cc:1192] Internal: WhereOp: Could not launch cub::DeviceReduce::Sum to count number of true indices. temp_storage_bytes: 2815, status: invalid device function
[[Node: LOSS_default/Where = Where_device="/job:localhost/replica:0/task:0/gpu:0"]]
2018-01-11 06:05:49.094712: W tensorflow/core/framework/op_kernel.cc:1192] Internal: WhereOp: Could not launch cub::DeviceReduce::Sum to count number of true indices. temp_storage_bytes: 2815, status: invalid device function
[[Node: LOSS_default/Where = Where_device="/job:localhost/replica:0/task:0/gpu:0"]]
Traceback (most recent call last):
File "/home/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1327, in _do_call
return fn(*args)
File "/home/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1306, in _run_fn
status, run_metadata)
File "/home/anaconda3/lib/python3.6/contextlib.py", line 89, in exit
next(self.gen)
File "/home/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InternalError: WhereOp: Could not launch cub::DeviceReduce::Sum to count number of true indices. temp_storage_bytes: 2815, status: invalid device function
[[Node: LOSS_default/Where = Where_device="/job:localhost/replica:0/task:0/gpu:0"]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "./tools/trainval_net.py", line 140, in
max_iters=args.max_iters)
File "/home/FasterRCNN/tf-faster-rcnn-master/tools/../lib/model/train_val.py", line 400, in train_net
sw.train_model(sess, max_iters)
File "/home/FasterRCNN/tf-faster-rcnn-master/tools/../lib/model/train_val.py", line 311, in train_model
self.net.train_step(sess, blobs, train_op)
File "/home/FasterRCNN/tf-faster-rcnn-master/tools/../lib/nets/network.py", line 465, in train_step
feed_dict=feed_dict)
File "/home/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 895, in run
run_metadata_ptr)
File "/home/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1124, in _run
feed_dict_tensor, options, run_metadata)
File "/home/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
options, run_metadata)
File "/home/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: WhereOp: Could not launch cub::DeviceReduce::Sum to count number of true indices. temp_storage_bytes: 2815, status: invalid device function
[[Node: LOSS_default/Where = Where[_device="/job:localhost/replica:0/task:0/gpu:0"](LOSS_default/Not

**Comment by cy89** [comment]
Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?  Make sure you also include the exact command if possible to produce  the output included in your test case. If you are unclear what to include  see the issue template displayed in  [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

 We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!

**Comment by tensorflowbutler** [comment]
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by chiru83** [comment]
The problem is coming when i set GPU NMS flag. But if  disable GPU NMS flag,  the no error is showing up.
Linux OS. TF latest version

**Comment by chiru83** [comment]
Thanks for suggestion

**Comment by skye** [comment]
Is this still an issue? If so, please provide us with instructions for reproducing the error.

**Comment by chiru83** [comment]
If i make 'use_GPU_nms flag' as False in cfg file, code is executing without any error.
