### ISSUE TITLE
Key generator/encoder_8/conv/filter not found in checkpoint

### ISSUE THREAD

**Issue by vhagier** [tensorflow/tensorflow#16069]
I'm using python 3.6.3 win 10 64bit and tensorflow 1.2.1 and now I'm working on https://github.com/datitran/face2face-demo project and **part 4.export model** I'm taking this error:NotFoundError (see above for traceback): Key generator/encoder_8/conv/filter not found in checkpoint 

how can I solve this problem ?

what I run
`C:\Users\hajum>python C:\Users\hajum\Desktop\face2face-demo-master\reduce_model.py --model-input C:\Users\hajum\Desktop\face2face-model --model-output C:\Users\hajum\Desktop\face2face-reduced-model`

same folder names with project but I have my own models

what it shows
```
2018-01-12 13:24:05.337267: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE instructions, but these are available on your machine and could speed up CPU computations.
2018-01-12 13:24:05.337407: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE2 instructions, but these are available on your machine and could speed up CPU computations.
2018-01-12 13:24:05.338476: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
2018-01-12 13:24:05.338779: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2018-01-12 13:24:05.339070: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2018-01-12 13:24:05.339369: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2018-01-12 13:24:05.339659: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2018-01-12 13:24:05.339962: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
2018-01-12 13:24:05.779044: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\framework\op_kernel.cc:1158] Not found: Key generator/encoder_8/conv/filter not found in checkpoint
2018-01-12 13:24:05.779482: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\framework\op_kernel.cc:1158] Not found: Key generator/decoder_2/deconv/filter not found in checkpoint
2018-01-12 13:24:05.779562: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\framework\op_kernel.cc:1158] Not found: Key generator/decoder_1/deconv/filter not found in checkpoint
2018-01-12 13:24:05.780339: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\framework\op_kernel.cc:1158] Not found: Key generator/decoder_3/deconv/filter not found in checkpoint
2018-01-12 13:24:05.780354: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\framework\op_kernel.cc:1158] Not found: Key generator/decoder_3/batchnorm/offset not found in checkpoint
2018-01-12 13:24:05.781063: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\framework\op_kernel.cc:1158] Not found: Key generator/decoder_2/batchnorm/scale not found in checkpoint
2018-01-12 13:24:05.781066: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\framework\op_kernel.cc:1158] Not found: Key generator/decoder_3/batchnorm/scale not found in checkpoint
2018-01-12 13:24:05.781015: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\framework\op_kernel.cc:1158] Not found: Key generator/decoder_2/batchnorm/offset not found in checkpoint
2018-01-12 13:24:05.784971: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\framework\op_kernel.cc:1158] Not found: Key generator/encoder_8/batchnorm/scale not found in checkpoint
2018-01-12 13:24:05.785703: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\framework\op_kernel.cc:1158] Not found: Key generator/decoder_4/batchnorm/offset not found in checkpoint
2018-01-12 13:24:05.785849: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\framework\op_kernel.cc:1158] Not found: Key generator/decoder_4/batchnorm/scale not found in checkpoint
2018-01-12 13:24:05.785928: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\framework\op_kernel.cc:1158] Not found: Key generator/decoder_4/deconv/filter not found in checkpoint
2018-01-12 13:24:05.787052: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\framework\op_kernel.cc:1158] Not found: Key generator/decoder_5/batchnorm/offset not found in checkpoint
2018-01-12 13:24:05.787160: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\framework\op_kernel.cc:1158] Not found: Key generator/decoder_6/batchnorm/offset not found in checkpoint
2018-01-12 13:24:05.787346: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\framework\op_kernel.cc:1158] Not found: Key generator/decoder_5/deconv/filter not found in checkpoint
2018-01-12 13:24:05.787687: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\framework\op_kernel.cc:1158] Not found: Key generator/decoder_5/batchnorm/scale not found in checkpoint
2018-01-12 13:24:05.791739: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\framework\op_kernel.cc:1158] Not found: Key generator/encoder_8/batchnorm/offset not found in checkpoint
2018-01-12 13:24:05.793255: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\framework\op_kernel.cc:1158] Not found: Key generator/decoder_6/batchnorm/scale not found in checkpoint
2018-01-12 13:24:05.793508: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\framework\op_kernel.cc:1158] Not found: Key generator/decoder_6/deconv/filter not found in checkpoint
2018-01-12 13:24:05.794303: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\framework\op_kernel.cc:1158] Not found: Key generator/decoder_7/batchnorm/offset not found in checkpoint
2018-01-12 13:24:05.795123: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\framework\op_kernel.cc:1158] Not found: Key generator/decoder_7/batchnorm/scale not found in checkpoint
2018-01-12 13:24:05.795823: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\framework\op_kernel.cc:1158] Not found: Key generator/decoder_8/batchnorm/offset not found in checkpoint
2018-01-12 13:24:05.796067: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\framework\op_kernel.cc:1158] Not found: Key generator/decoder_7/deconv/filter not found in checkpoint
2018-01-12 13:24:05.797352: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\framework\op_kernel.cc:1158] Not found: Key generator/decoder_8/batchnorm/scale not found in checkpoint
2018-01-12 13:24:05.798112: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\framework\op_kernel.cc:1158] Not found: Key generator/encoder_7/conv/filter not found in checkpoint
2018-01-12 13:24:05.800556: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\framework\op_kernel.cc:1158] Not found: Key generator/encoder_1/conv/filter not found in checkpoint
2018-01-12 13:24:05.801703: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\framework\op_kernel.cc:1158] Not found: Key generator/encoder_2/batchnorm/offset not found in checkpoint
2018-01-12 13:24:05.801868: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\framework\op_kernel.cc:1158] Not found: Key generator/decoder_8/deconv/filter not found in checkpoint
2018-01-12 13:24:05.801974: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\framework\op_kernel.cc:1158] Not found: Key generator/encoder_2/batchnorm/scale not found in checkpoint
2018-01-12 13:24:05.801977: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\framework\op_kernel.cc:1158] Not found: Key generator/encoder_2/conv/filter not found in checkpoint
2018-01-12 13:24:05.804154: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\framework\op_kernel.cc:1158] Not found: Key generator/encoder_3/batchnorm/offset not found in checkpoint
2018-01-12 13:24:05.805983: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\framework\op_kernel.cc:1158] Not found: Key generator/encoder_3/batchnorm/scale not found in checkpoint
2018-01-12 13:24:05.806160: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\framework\op_kernel.cc:1158] Not found: Key generator/encoder_7/batchnorm/scale not found in checkpoint
2018-01-12 13:24:05.807834: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\framework\op_kernel.cc:1158] Not found: Key generator/encoder_4/batchnorm/offset not found in checkpoint
2018-01-12 13:24:05.808628: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\framework\op_kernel.cc:1158] Not found: Key generator/encoder_3/conv/filter not found in checkpoint
2018-01-12 13:24:05.808808: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\framework\op_kernel.cc:1158] Not found: Key generator/encoder_5/batchnorm/offset not found in checkpoint
2018-01-12 13:24:05.809721: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\framework\op_kernel.cc:1158] Not found: Key generator/encoder_4/batchnorm/scale not found in checkpoint
2018-01-12 13:24:05.809836: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\framework\op_kernel.cc:1158] Not found: Key generator/encoder_4/conv/filter not found in checkpoint
2018-01-12 13:24:05.810842: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\framework\op_kernel.cc:1158] Not found: Key generator/encoder_5/batchnorm/scale not found in checkpoint
2018-01-12 13:24:05.811998: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\framework\op_kernel.cc:1158] Not found: Key generator/encoder_5/conv/filter not found in checkpoint
2018-01-12 13:24:05.812062: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\framework\op_kernel.cc:1158] Not found: Key generator/encoder_7/batchnorm/offset not found in checkpoint
2018-01-12 13:24:05.812846: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\framework\op_kernel.cc:1158] Not found: Key generator/encoder_6/batchnorm/offset not found in checkpoint
2018-01-12 13:24:05.812889: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\framework\op_kernel.cc:1158] Not found: Key generator/encoder_6/batchnorm/scale not found in checkpoint
2018-01-12 13:24:05.813195: W c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\framework\op_kernel.cc:1158] Not found: Key generator/encoder_6/conv/filter not found in checkpoint
Traceback (most recent call last):
  File "C:\Users\hajum\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1139, in _do_call
    return fn(*args)
  File "C:\Users\hajum\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1121, in _run_fn
    status, run_metadata)
  File "C:\Users\hajum\Anaconda3\lib\contextlib.py", line 88, in __exit__
    next(self.gen)
  File "C:\Users\hajum\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.NotFoundError: Key generator/encoder_8/conv/filter not found in checkpoint
         [[Node: save/RestoreV2_43 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_43/tensor_names, save/RestoreV2_43/shape_and_slices)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\hajum\Desktop\face2face-demo-master\reduce_model.py", line 215, in <module>
    saver.restore(sess, checkpoint)
  File "C:\Users\hajum\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1548, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "C:\Users\hajum\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 789, in run
    run_metadata_ptr)
  File "C:\Users\hajum\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "C:\Users\hajum\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "C:\Users\hajum\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Key generator/encoder_8/conv/filter not found in checkpoint
         [[Node: save/RestoreV2_43 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_43/tensor_names, save/RestoreV2_43/shape_and_slices)]]

Caused by op 'save/RestoreV2_43', defined at:
  File "C:\Users\hajum\Desktop\face2face-demo-master\reduce_model.py", line 213, in <module>
    saver = tf.train.Saver()
  File "C:\Users\hajum\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1139, in __init__
    self.build()
  File "C:\Users\hajum\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1170, in build
    restore_sequentially=self._restore_sequentially)
  File "C:\Users\hajum\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 691, in build
    restore_sequentially, reshape)
  File "C:\Users\hajum\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 407, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "C:\Users\hajum\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 247, in restore_op
    [spec.tensor.dtype])[0])
  File "C:\Users\hajum\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_io_ops.py", line 640, in restore_v2
    dtypes=dtypes, name=name)
  File "C:\Users\hajum\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "C:\Users\hajum\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "C:\Users\hajum\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

NotFoundError (see above for traceback): Key generator/encoder_8/conv/filter not found in checkpoint
         [[Node: save/RestoreV2_43 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_43/tensor_names, save/RestoreV2_43/shape_and_slices)]]
```

**Comment by baloodevil** [comment]
Same error running Windows 10, python 3.6.2 and tensorflow 1.4.0

**Comment by aselle** [comment]
Since this seems to be related to code in an external repository, I'm closing for now.

**Comment by Adisriman** [comment]
lionawurscht its working thanks
