### ISSUE TITLE
ValueError: Inputs to `Dense` should have rank >= 2.

### ISSUE THREAD

**Issue by zhaoyingjun** [tensorflow/tensorflow#16190]
##error

Traceback (most recent call last):
  File "firstGANtf.py", line 90, in <module>
    G = Generator(input_size=g_input_size, hidden_size=g_hidden_size, output_size=g_output_size)
  File "firstGANtf.py", line 55, in __init__
    self.map1 = tf.contrib.layers.linear(inputs=input_size , num_outputs=hidden_size)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 177, in func_with_args
    return func(*args, **current_args)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 1409, in fully_connected
    outputs = layer.apply(inputs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/python/layers/base.py", line 303, in apply
    return self.__call__(inputs, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/python/layers/base.py", line 269, in __call__
    self.build(input_shapes[0])
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/python/layers/core.py", line 110, in build
    raise ValueError('Inputs to `Dense` should have rank >= 2.')
ValueError: Inputs to `Dense` should have rank >= 2.

##code

       self.map1 = tf.contrib.layers.linear(inputs=input_size , num_outputs=hidden_size)
        self.map2 = tf.contrib.layers.linear(inputs=hidden_size,  num_outputs=hidden_size)
        self.map3 = tf.contrib.layers.linear(inputs=hidden_size, num_outputs=output_size)

**Comment by gouthamand** [comment]
Running into similar issues for sometime now. Any help would be appericiated

**Comment by poxvoculi** [comment]
I apologize but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new) . Please provide all the information it asks. Thank you.

**Comment by facaiy** [comment]
I think `tf.contrib.layers.linear` has been removed in the latest version. And for functional interface, you should use `inputs`, rather than `inputs_size`.  

Take dense layer for example, `tf.layers.Dense` is the layer class, and its functional interface named ` tf.layers.dense`.  The layer class uses `input_shape` to build it, while functional interface requires `inputs`.

**Comment by tensorflowbutler** [comment]
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by poxvoculi** [comment]
Closing due to inactivity.
