### ISSUE TITLE
add broadcasting to `softmax_cross_entropy_with_logits`

### ISSUE THREAD

**Issue by csbrown** [tensorflow/tensorflow#16197]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yeah
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: ubuntu 16.04
- **TensorFlow installed from (source or binary)**: pip3 binary
- **TensorFlow version (use command below)**:
```
>>> tf.__git_version__
'v1.4.0-rc1-11-g130a514'
>>> tf.__version__
'1.4.0'
```
- **Python version**: 3.5.2
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**: NA
- **GPU model and memory**: NA
- **Exact command to reproduce**: tf.nn.softmax_cross_entropy_with_logits(labels=tf.constant(1., shape=(2,)), logits=tf.constant(1., shape=(50,2)))

### Describe the problem
FEATURE REQUEST: `softmax_cross_entropy_with_logits` should broadcast, maybe?  I'm reading groups of data that all have the same label.  Seems a waste to have to replicate the label a gazillion times.

### Source code / logs
```
>>> a = tf.nn.softmax_cross_entropy_with_logits(labels=tf.constant(1., shape=(2,)), logits=tf.constant(1., shape=(50,2)))

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/common_shapes.py", line 686, in _call_cpp_shape_fn_impl
    input_tensors_as_shapes, status)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimension 0 in both shapes must be equal, but are 50 and 1 for 'SoftmaxCrossEntropyWithLogits_3' (op: 'SoftmaxCrossEntropyWithLogits') with input shapes: [50,2], [1,2].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/nn_ops.py", line 1783, in softmax_cross_entropy_with_logits
    precise_logits, labels, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_nn_ops.py", line 4364, in _softmax_cross_entropy_with_logits
    name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 2958, in create_op
    set_shapes_for_outputs(ret)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 2209, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 2159, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/common_shapes.py", line 627, in call_cpp_shape_fn
    require_shape_fn)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/common_shapes.py", line 691, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Dimension 0 in both shapes must be equal, but are 50 and 1 for 'SoftmaxCrossEntropyWithLogits_3' (op: 'SoftmaxCrossEntropyWithLogits') with input shapes: [50,2], [1,2].
```

**Comment by aselle** [comment]
I'm not sure how likely the label is to be the same on multiple entries of the batch (which I assume that is the broadcast dimension you are thinking about).

**Comment by facaiy** [comment]
Perhaps it's safer to broadcast your labels explicitly. I'm afraid that the feature would be unexpected (or even wrong) for user in most cases.

**Comment by csbrown** [comment]
That's cool.  Seemed reasonable that broadcasting might generalize as a
useful feature for many binary operators, just like it is for basic math...
I have a use case for broadcasting in this particular binary operation, but
I'm just `.tile`ing my labels now, and it works just fine, so it's a minor
efficiency point.

Just in case solving a more general problem would solve this one:

Can I hack broadcasting together with what currently exists?  Maybe a
`broadcast` node would be useful?

**Comment by tensorflowbutler** [comment]
The original poster has replied to this issue after the stat:awaiting response label was applied.

**Comment by reedwm** [comment]
I think using `tf.tile` is the best solution for now, and adding broadcasting to `softmax_cross_entropy_with_logits` would make it easy to accidentally introduce bugs, as no error would be raised if the second dimension of `labels` was accidentally omitted. I don't see what a "boradcast" node would do that a `tf.tile` would not.

/CC @ebrevdo, thoughts?

**Comment by tensorflowbutler** [comment]
Nagging Awaiting TensorFlower: It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Awaiting TensorFlower: It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Awaiting TensorFlower: It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by ebrevdo** [comment]
I agree that for now, tiling manually is the best approach. A recent change to broadcasting in a similar softmax op caused invisible/subtle errors.

**Comment by FypTeamFast2019TumorDetection** [comment]
We answered this problem which is also related to architecture Understand this in following link
https://stackoverflow.com/questions/46465925/input-to-reshape-is-a-tensor-with-37632-values-but-the-requested-shape-has-1505/52240509#52240509
Let us know if you face any issue
