### ISSUE TITLE
Socket issue of run whl

### ISSUE THREAD

**Issue by liuhaiyang150** [tensorflow/tensorflow#16207]
Hi ,
I have a problem about run tensorflow .whl.  as follow:

Exception:
Traceback (most recent call last):
  File "/home/CORPUSERS/xp022898/anaconda3/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/CORPUSERS/xp022898/anaconda3/lib/python3.6/site-packages/pip/commands/install.py", line 335, in run
    wb.build(autobuilding=True)
  File "/home/CORPUSERS/xp022898/anaconda3/lib/python3.6/site-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/home/CORPUSERS/xp022898/anaconda3/lib/python3.6/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/home/CORPUSERS/xp022898/anaconda3/lib/python3.6/site-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/home/CORPUSERS/xp022898/anaconda3/lib/python3.6/site-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/home/CORPUSERS/xp022898/anaconda3/lib/python3.6/site-packages/pip/index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/home/CORPUSERS/xp022898/anaconda3/lib/python3.6/site-packages/pip/index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/home/CORPUSERS/xp022898/anaconda3/lib/python3.6/site-packages/pip/index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "/home/CORPUSERS/xp022898/anaconda3/lib/python3.6/site-packages/pip/index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/home/CORPUSERS/xp022898/anaconda3/lib/python3.6/site-packages/pip/index.py", line 792, in get_page
    "Cache-Control": "max-age=600",
  File "/home/CORPUSERS/xp022898/anaconda3/lib/python3.6/site-packages/pip/_vendor/requests/sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
  File "/home/CORPUSERS/xp022898/anaconda3/lib/python3.6/site-packages/pip/download.py", line 386, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/home/CORPUSERS/xp022898/anaconda3/lib/python3.6/site-packages/pip/_vendor/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/CORPUSERS/xp022898/anaconda3/lib/python3.6/site-packages/pip/_vendor/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/home/CORPUSERS/xp022898/anaconda3/lib/python3.6/site-packages/pip/_vendor/cachecontrol/adapter.py", line 47, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/home/CORPUSERS/xp022898/anaconda3/lib/python3.6/site-packages/pip/_vendor/requests/adapters.py", line 390, in send
    conn = self.get_connection(request.url, proxies)
  File "/home/CORPUSERS/xp022898/anaconda3/lib/python3.6/site-packages/pip/_vendor/requests/adapters.py", line 290, in get_connection
    proxy_manager = self.proxy_manager_for(proxy)
  File "/home/CORPUSERS/xp022898/anaconda3/lib/python3.6/site-packages/pip/_vendor/requests/adapters.py", line 184, in proxy_manager_for
    **proxy_kwargs
  File "/home/CORPUSERS/xp022898/anaconda3/lib/python3.6/site-packages/pip/_vendor/requests/packages/urllib3/contrib/socks.py", line 154, in __init__
    "Unable to determine SOCKS version from %s" % proxy_url
ValueError: Unable to determine SOCKS version from socks:*********

**Comment by liuhaiyang150** [comment]
modify pip source code to use http socket type is ok

**Comment by aselle** [comment]
This seems to be a pip / python problem rather than a TensorFlow problem? Are you able to install any pip packages?

**Comment by tensorflowbutler** [comment]
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by reedwm** [comment]
Closing due to a lack of a response.
