### ISSUE TITLE
ValueError: Protocol message RewriterConfig has no "layout_optimizer" field.

### ISSUE THREAD

**Issue by jimo123** [tensorflow/tensorflow#16268]
I just start learning tensorflow object detection API.And now,I can use the train.py script to train my model,and use the eval.py script to evaluate normally,but when I use the export_inference_graph.py script to export .pb file,the following error occurred.my tf version is 1.4 and python version is 3.5,ubuntu14.04.thank you very much.

Traceback (most recent call last):
  File "export_inference_graph.py", line 110, in <module>
    tf.app.run()
  File "/home/yj/anaconda3/envs/tensorflow3.4/lib/python3.4/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "export_inference_graph.py", line 106, in main
    FLAGS.output_directory)
  File "/home/yj/anaconda3/envs/tensorflow3.4/models/research/object_detection/exporter.py", line 427, in export_inference_graph
    input_shape, optimize_graph, output_collection_name)
  File "/home/yj/anaconda3/envs/tensorflow3.4/models/research/object_detection/exporter.py", line 391, in _export_inference_graph
    initializer_nodes='')
  File "/home/yj/anaconda3/envs/tensorflow3.4/models/research/object_detection/exporter.py", line 72, in freeze_graph_with_def_protos
    layout_optimizer=rewriter_config_pb2.RewriterConfig.ON)
ValueError: Protocol message RewriterConfig has no "layout_optimizer" field.

I guess I installed a wrong protobuf version,but I tried 2.6.0 2.6.1 3.5.1,and the same error occured.

**Comment by Geoyi** [comment]
@jimo123 you might wanna refer to [this PR](https://github.com/tensorflow/models/pull/3106) and what I follow someone's advise over there. 
I changed models/research/object_detection/exporter.py line 71/72 from:
```python
rewrite_options = rewriter_config_pb2.RewriterConfig(
          layout_optimizer=rewriter_config_pb2.RewriterConfig.ON)
```
 to 
```python
rewrite_options = rewriter_config_pb2.RewriterConfig()
```
It worked ~~~ good luck!

**Comment by jimo123** [comment]
@Geoyi  thank you very much!! it does worked thanks again!!

**Comment by openedhardware** [comment]
@Geoyi 
You saved my day!

**Comment by natesh2310** [comment]
@Geoyi : This saved my day too :)

**Comment by lekshmi17** [comment]
File "C:\Users\user\AppData\Local\Programs\Python\Python36\models\research\object_detection\export_inference_graph.py", line 119, in <module>
    tf.app.run()
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\models\research\object_detection\export_inference_graph.py", line 115, in main
    FLAGS.output_directory, input_shape)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\exporter.py", line 427, in export_inference_graph
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\exporter.py", line 391, in _export_inference_graph
    _write_frozen_graph(frozen_graph_path, frozen_graph_def)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\exporter.py", line 72, in freeze_graph_with_def_protos
    rewrite_options.optimizers.append('pruning')
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\google\protobuf\internal\python_message.py", line 484, in init
    field = _GetFieldByName(message_descriptor, field_name)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\google\protobuf\internal\python_message.py", line 548, in _GetFieldByName
    (message_descriptor.name, field_name))
ValueError: Protocol message RewriterConfig has no "layout_optimizer" field.



I'm still getting this error :(

**Comment by Reactorbase** [comment]
@lekshmi17
me too getting the same error 
did you figured it out?
