### ISSUE TITLE
BUG: py_func don't support unicode string results for python2

### ISSUE THREAD

**Issue by facaiy** [tensorflow/tensorflow#16320]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Y
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac 10.11
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: master
- **Python version**: 2.7
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**: N/A

### Describe the problem

When I investigated #14116, I found that `py_func` converts unicode strings result to bytes only for  Python3, while raise an exception for Python 2.

I'm curious why we don't the same thing for Python 2.

### Source code / logs

script:

```python
  def testReturnUnicodeString(self):
    with self.test_session():
      correct = u"你好 世界"

      def unicode_string():
        return correct

      z, = script_ops.py_func(unicode_string, [], [dtypes.string])
      self.assertEqual(z.eval(), correct.encode("utf8"))
```

logs:

```python
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
-----------------------------------------------------------------------------
2018-01-23 09:43:04.611108: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
..2018-01-23 09:43:06.545687: W tensorflow/core/framework/op_kernel.cc:1181] Unimplemented: Unsupported numpy type 20
.2018-01-23 09:43:06.548797: W tensorflow/core/framework/op_kernel.cc:1181] Unimplemented: Unsupported object type dict
.....2018-01-23 09:43:08.129501: W tensorflow/core/framework/op_kernel.cc:1181] Invalid argument: exceptions.ValueError: blah
2018-01-23 09:43:08.131595: W tensorflow/core/framework/op_kernel.cc:1181] Invalid argument: exceptions.TypeError: blah
2018-01-23 09:43:08.134736: W tensorflow/core/framework/op_kernel.cc:1181] Resource exhausted: exceptions.MemoryError: blah
2018-01-23 09:43:08.136335: W tensorflow/core/framework/op_kernel.cc:1181] Unimplemented: exceptions.NotImplementedError: blah
2018-01-23 09:43:08.138000: W tensorflow/core/framework/op_kernel.cc:1181] Unknown: WeirdError: blah
2018-01-23 09:43:08.138882: W tensorflow/core/framework/op_kernel.cc:1181] Invalid argument: exceptions.ValueError: blah
2018-01-23 09:43:08.139022: W tensorflow/core/framework/op_kernel.cc:1181] Invalid argument: exceptions.TypeError: blah
2018-01-23 09:43:08.139236: W tensorflow/core/framework/op_kernel.cc:1181] Resource exhausted: exceptions.MemoryError: blah
2018-01-23 09:43:08.139349: W tensorflow/core/framework/op_kernel.cc:1181] Unimplemented: exceptions.NotImplementedError: blah
2018-01-23 09:43:08.139492: W tensorflow/core/framework/op_kernel.cc:1181] Unknown: WeirdError: blah
.....2018-01-23 09:43:10.036466: W tensorflow/core/framework/op_kernel.cc:1181] Invalid argument: exceptions.ValueError: blah
2018-01-23 09:43:10.038219: W tensorflow/core/framework/op_kernel.cc:1181] Invalid argument: exceptions.TypeError: blah
2018-01-23 09:43:10.041279: W tensorflow/core/framework/op_kernel.cc:1181] Resource exhausted: exceptions.MemoryError: blah
2018-01-23 09:43:10.044136: W tensorflow/core/framework/op_kernel.cc:1181] Unimplemented: exceptions.NotImplementedError: blah
2018-01-23 09:43:10.046983: W tensorflow/core/framework/op_kernel.cc:1181] Unknown: WeirdError: blah
............2018-01-23 09:43:11.081837: W tensorflow/core/framework/op_kernel.cc:1181] Invalid argument: exceptions.UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)
E..........
======================================================================
ERROR: testReturnUnicodeString (__main__.PyFuncTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data1/users/facai/.cache/bazel/_bazel_facai/3338df3cdc4fd0e5fdd3f3ae6490e0be/execroot/org_tensorflow/bazel-out/local-opt/bin/tensorflow/python/kernel_tests/py_func_test.runfiles/org_tensorflow/tensorflow/python/kernel_tests/py_func_test.py", line 227, in testReturnUnicodeString
    self.assertEqual(z.eval(), correct.encode("utf8"))
  File "/data1/users/facai/.cache/bazel/_bazel_facai/3338df3cdc4fd0e5fdd3f3ae6490e0be/execroot/org_tensorflow/bazel-out/local-opt/bin/tensorflow/python/kernel_tests/py_func_test.runfiles/org_tensorflow/tensorflow/python/framework/ops.py", line 639, in eval
    return _eval_using_default_session(self, feed_dict, self.graph, session)
  File "/data1/users/facai/.cache/bazel/_bazel_facai/3338df3cdc4fd0e5fdd3f3ae6490e0be/execroot/org_tensorflow/bazel-out/local-opt/bin/tensorflow/python/kernel_tests/py_func_test.runfiles/org_tensorflow/tensorflow/python/framework/ops.py", line 4795, in _eval_using_default_session
    return session.run(tensors, feed_dict)
  File "/data1/users/facai/.cache/bazel/_bazel_facai/3338df3cdc4fd0e5fdd3f3ae6490e0be/execroot/org_tensorflow/bazel-out/local-opt/bin/tensorflow/python/kernel_tests/py_func_test.runfiles/org_tensorflow/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/data1/users/facai/.cache/bazel/_bazel_facai/3338df3cdc4fd0e5fdd3f3ae6490e0be/execroot/org_tensorflow/bazel-out/local-opt/bin/tensorflow/python/kernel_tests/py_func_test.runfiles/org_tensorflow/tensorflow/python/client/session.py", line 1128, in _run
    feed_dict_tensor, options, run_metadata)
  File "/data1/users/facai/.cache/bazel/_bazel_facai/3338df3cdc4fd0e5fdd3f3ae6490e0be/execroot/org_tensorflow/bazel-out/local-opt/bin/tensorflow/python/kernel_tests/py_func_test.runfiles/org_tensorflow/tensorflow/python/client/session.py", line 1344, in _do_run
    options, run_metadata)
  File "/data1/users/facai/.cache/bazel/_bazel_facai/3338df3cdc4fd0e5fdd3f3ae6490e0be/execroot/org_tensorflow/bazel-out/local-opt/bin/tensorflow/python/kernel_tests/py_func_test.runfiles/org_tensorflow/tensorflow/python/client/session.py", line 1363, in _do_call
    raise type(e)(node_def, op, message)
InvalidArgumentError: exceptions.UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)
	 [[Node: PyFunc = PyFunc[Tin=[], Tout=[DT_STRING], token="pyfunc_2049", _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op u'PyFunc', defined at:
  File "/data1/users/facai/.cache/bazel/_bazel_facai/3338df3cdc4fd0e5fdd3f3ae6490e0be/execroot/org_tensorflow/bazel-out/local-opt/bin/tensorflow/python/kernel_tests/py_func_test.runfiles/org_tensorflow/tensorflow/python/kernel_tests/py_func_test.py", line 476, in <module>
    test.main()
  File "/data1/users/facai/.cache/bazel/_bazel_facai/3338df3cdc4fd0e5fdd3f3ae6490e0be/execroot/org_tensorflow/bazel-out/local-opt/bin/tensorflow/python/kernel_tests/py_func_test.runfiles/org_tensorflow/tensorflow/python/platform/test.py", line 74, in main
    return _googletest.main(argv)
  File "/data1/users/facai/.cache/bazel/_bazel_facai/3338df3cdc4fd0e5fdd3f3ae6490e0be/execroot/org_tensorflow/bazel-out/local-opt/bin/tensorflow/python/kernel_tests/py_func_test.runfiles/org_tensorflow/tensorflow/python/platform/googletest.py", line 99, in main
    benchmark.benchmarks_main(true_main=main_wrapper)
  File "/data1/users/facai/.cache/bazel/_bazel_facai/3338df3cdc4fd0e5fdd3f3ae6490e0be/execroot/org_tensorflow/bazel-out/local-opt/bin/tensorflow/python/kernel_tests/py_func_test.runfiles/org_tensorflow/tensorflow/python/platform/benchmark.py", line 336, in benchmarks_main
    true_main()
  File "/data1/users/facai/.cache/bazel/_bazel_facai/3338df3cdc4fd0e5fdd3f3ae6490e0be/execroot/org_tensorflow/bazel-out/local-opt/bin/tensorflow/python/kernel_tests/py_func_test.runfiles/org_tensorflow/tensorflow/python/platform/googletest.py", line 98, in main_wrapper
    return app.run(main=g_main, argv=args)
  File "/data1/users/facai/.cache/bazel/_bazel_facai/3338df3cdc4fd0e5fdd3f3ae6490e0be/execroot/org_tensorflow/bazel-out/local-opt/bin/tensorflow/python/kernel_tests/py_func_test.runfiles/org_tensorflow/tensorflow/python/platform/app.py", line 124, in run
    _sys.exit(main(argv))
  File "/data1/users/facai/.cache/bazel/_bazel_facai/3338df3cdc4fd0e5fdd3f3ae6490e0be/execroot/org_tensorflow/bazel-out/local-opt/bin/tensorflow/python/kernel_tests/py_func_test.runfiles/org_tensorflow/tensorflow/python/platform/googletest.py", line 69, in g_main
    return unittest_main(argv=argv)
  File "/usr/home/facai/workshop/anaconda2/lib/python2.7/unittest/main.py", line 95, in __init__
    self.runTests()
  File "/usr/home/facai/workshop/anaconda2/lib/python2.7/unittest/main.py", line 232, in runTests
    self.result = testRunner.run(self.test)
  File "/usr/home/facai/workshop/anaconda2/lib/python2.7/unittest/runner.py", line 151, in run
    test(result)
  File "/usr/home/facai/workshop/anaconda2/lib/python2.7/unittest/suite.py", line 70, in __call__
    return self.run(*args, **kwds)
  File "/usr/home/facai/workshop/anaconda2/lib/python2.7/unittest/suite.py", line 108, in run
    test(result)
  File "/usr/home/facai/workshop/anaconda2/lib/python2.7/unittest/suite.py", line 70, in __call__
    return self.run(*args, **kwds)
  File "/usr/home/facai/workshop/anaconda2/lib/python2.7/unittest/suite.py", line 108, in run
    test(result)
  File "/usr/home/facai/workshop/anaconda2/lib/python2.7/unittest/case.py", line 393, in __call__
    return self.run(*args, **kwds)
  File "/usr/home/facai/workshop/anaconda2/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/data1/users/facai/.cache/bazel/_bazel_facai/3338df3cdc4fd0e5fdd3f3ae6490e0be/execroot/org_tensorflow/bazel-out/local-opt/bin/tensorflow/python/kernel_tests/py_func_test.runfiles/org_tensorflow/tensorflow/python/kernel_tests/py_func_test.py", line 226, in testReturnUnicodeString
    z, = script_ops.py_func(unicode_string, [], [dtypes.string])
  File "/data1/users/facai/.cache/bazel/_bazel_facai/3338df3cdc4fd0e5fdd3f3ae6490e0be/execroot/org_tensorflow/bazel-out/local-opt/bin/tensorflow/python/kernel_tests/py_func_test.runfiles/org_tensorflow/tensorflow/python/ops/script_ops.py", line 300, in py_func
    func=func, inp=inp, Tout=Tout, stateful=stateful, eager=False, name=name)
  File "/data1/users/facai/.cache/bazel/_bazel_facai/3338df3cdc4fd0e5fdd3f3ae6490e0be/execroot/org_tensorflow/bazel-out/local-opt/bin/tensorflow/python/kernel_tests/py_func_test.runfiles/org_tensorflow/tensorflow/python/ops/script_ops.py", line 209, in _internal_py_func
    input=inp, token=token, Tout=Tout, name=name)
  File "/data1/users/facai/.cache/bazel/_bazel_facai/3338df3cdc4fd0e5fdd3f3ae6490e0be/execroot/org_tensorflow/bazel-out/local-opt/bin/tensorflow/python/kernel_tests/py_func_test.runfiles/org_tensorflow/tensorflow/python/ops/gen_script_ops.py", line 93, in _py_func
    "PyFunc", input=input, token=token, Tout=Tout, name=name)
  File "/data1/users/facai/.cache/bazel/_bazel_facai/3338df3cdc4fd0e5fdd3f3ae6490e0be/execroot/org_tensorflow/bazel-out/local-opt/bin/tensorflow/python/kernel_tests/py_func_test.runfiles/org_tensorflow/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/data1/users/facai/.cache/bazel/_bazel_facai/3338df3cdc4fd0e5fdd3f3ae6490e0be/execroot/org_tensorflow/bazel-out/local-opt/bin/tensorflow/python/kernel_tests/py_func_test.runfiles/org_tensorflow/tensorflow/python/framework/ops.py", line 3172, in create_op
    op_def=op_def)
  File "/data1/users/facai/.cache/bazel/_bazel_facai/3338df3cdc4fd0e5fdd3f3ae6490e0be/execroot/org_tensorflow/bazel-out/local-opt/bin/tensorflow/python/kernel_tests/py_func_test.runfiles/org_tensorflow/tensorflow/python/framework/ops.py", line 1617, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): exceptions.UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)
	 [[Node: PyFunc = PyFunc[Tin=[], Tout=[DT_STRING], token="pyfunc_2049", _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]


----------------------------------------------------------------------
Ran 36 tests in 6.497s

FAILED (errors=1)
```

**Comment by facaiy** [comment]
Moreover, `py_func` runs well for English (even though unicode string), while Chinese failed. I don't know whether the inconsistent result is intentional. #16322 is proposed to fix the issue.

**Comment by tatianashp** [comment]
Thank you for noticing this issue. As you already submitted PR that fixes it I am closing the issue.

**Comment by tatianashp** [comment]
Thank you for noticing this issue. As you already submitted PR that fixes it I am closing the issue.
