### ISSUE TITLE
ValueError: Dimensions 1069539296 and 13528529576648672 are not compatible

### ISSUE THREAD

**Issue by lihua213** [tensorflow/tensorflow#16454]
Traceback (most recent call last):
  File "/home/lihua/.local/lib/python3.5/site-packages/tensorflow/python/framework/tensor_shape.py", line 558, in merge_with
    new_dims.append(dim.merge_with(other[i]))
  File "/home/lihua/.local/lib/python3.5/site-packages/tensorflow/python/framework/tensor_shape.py", line 133, in merge_with
    self.assert_is_compatible_with(other)
  File "/home/lihua/.local/lib/python3.5/site-packages/tensorflow/python/framework/tensor_shape.py", line 106, in assert_is_compatible_with
    other))
ValueError: Dimensions 1069539296 and 13528529576648672 are not compatible

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Train.py", line 117, in <module>
    train()
  File "Train.py", line 54, in train
    train_op=Evaluation.trainning(loss=loss1, learning_rate=0.0001)
  File "/home/lihua/Documents/Projects/Project2018/trafficSignClassification/Evaluation.py", line 36, in trainning
    train_op = optimizer.minimize(loss, global_step= global_step)
  File "/home/lihua/.local/lib/python3.5/site-packages/tensorflow/python/training/optimizer.py", line 315, in minimize
    grad_loss=grad_loss)
  File "/home/lihua/.local/lib/python3.5/site-packages/tensorflow/python/training/optimizer.py", line 386, in compute_gradients
    colocate_gradients_with_ops=colocate_gradients_with_ops)
  File "/home/lihua/.local/lib/python3.5/site-packages/tensorflow/python/ops/gradients_impl.py", line 560, in gradients
    in_grad.set_shape(t_in.get_shape())
  File "/home/lihua/.local/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 443, in set_shape
    self._shape = self._shape.merge_with(shape)
  File "/home/lihua/.local/lib/python3.5/site-packages/tensorflow/python/framework/tensor_shape.py", line 561, in merge_with
    raise ValueError("Shapes %s and %s are not compatible" % (self, other))
ValueError: Shapes (128, 4, 4, 1069539296) and (128, 4, 4, 13528529576648672) are not compatible

ubuntu16.04
tensorflow 1.4

**Comment by tatianashp** [comment]
I apologize but I am having a hard time understanding what the problem is, where the problem is, and on what platform it happens. Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new) . Please provide all the information it asks. Thank you.
