### ISSUE TITLE
macOS mnist download error

### ISSUE THREAD

**Issue by windend** [tensorflow/tensorflow#16461]
```
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("MNIST_data/", one_hot=True)
```
MacOS python3.6 is wrong
windows is right.

```
Traceback (most recent call last):
  File "/Users/funny/Documents/AIML/test.py", line 8, in <module>
    from tensorflow.examples.tutorials.mnist import input_data
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 63, in <module>
    from tensorflow.python.framework.framework_lib import *
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/framework/framework_lib.py", line 76, in <module>
    from tensorflow.python.framework.ops import Graph
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 37, in <module>
    from tensorflow.python.eager import context
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/eager/context.py", line 27, in <module>
    from tensorflow.python.framework import errors
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/framework/errors.py", line 22, in <module>
    from tensorflow.python.framework import errors_impl as _impl
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 27, in <module>
    from tensorflow.python.util import compat
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/util/compat.py", line 130, in <module>
    remove_undocumented(__name__, _allowed_symbols)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/util/all_util.py", line 103, in remove_undocumented
    should_have = make_all(module_name, doc_string_modules)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/util/all_util.py", line 55, in make_all
    for m in _reference_pattern.finditer(doc_module.__doc__)
TypeError: expected string or bytes-like object
```

**Comment by windend** [comment]
Traceback (most recent call last):
  File "/Users/funny/Documents/AIML/test.py", line 8, in <module>
    from tensorflow.examples.tutorials.mnist import input_data
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 63, in <module>
    from tensorflow.python.framework.framework_lib import *
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/framework/framework_lib.py", line 76, in <module>
    from tensorflow.python.framework.ops import Graph
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 37, in <module>
    from tensorflow.python.eager import context
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/eager/context.py", line 27, in <module>
    from tensorflow.python.framework import errors
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/framework/errors.py", line 22, in <module>
    from tensorflow.python.framework import errors_impl as _impl
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 27, in <module>
    from tensorflow.python.util import compat
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/util/compat.py", line 130, in <module>
    remove_undocumented(__name__, _allowed_symbols)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/util/all_util.py", line 103, in remove_undocumented
    should_have = make_all(module_name, doc_string_modules)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/util/all_util.py", line 55, in make_all
    for m in _reference_pattern.finditer(doc_module.__doc__)
TypeError: expected string or bytes-like object

**Comment by redfish-lee** [comment]
which tensorflow version have you installed? `tensorflow` or `tensorflow-gpu`

- `macos 10.13.3`
- `python 2.7.14` with `pip install tensorflow`, pass
- `python 3.6.4` got same error issues, uninstall first and then `pip3 install tensorflow` fix the problem.

**Comment by reedwm** [comment]
I apologize but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new) . Please provide all the information it asks. Thank you.

**Comment by tensorflowbutler** [comment]
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by reedwm** [comment]
Closing due to inactivity. Please reopen if this is still a problem.
