### ISSUE TITLE
There's no problem running on window, and there's a problem on Ubuntu

### ISSUE THREAD

**Issue by songpeng326** [tensorflow/tensorflow#16575]
Traceback (most recent call last):

  File "<ipython-input-1-fc398a1d9321>", line 1, in <module>
    runfile('/home/lab326/songpeng/anacoda项目/tflearn-vgg1.py', wdir='/home/lab326/songpeng/anacoda项目')

  File "/home/lab326/anaconda3/lib/python3.5/site-packages/spyder/utils/site/sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "/home/lab326/anaconda3/lib/python3.5/site-packages/spyder/utils/site/sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/lab326/songpeng/anacoda项目/tflearn-vgg1.py", line 59, in <module>
    files_extension=['.jpg'], filter_channel=True)

  File "/home/lab326/anaconda3/lib/python3.5/site-packages/tflearn/data_utils.py", line 512, in image_preloader
    flags=files_extension, filter_channel=filter_channel)

  File "/home/lab326/anaconda3/lib/python3.5/site-packages/tflearn/data_utils.py", line 732, in directory_to_samples
    classes = sorted(os.walk(directory).__next__()[1])

StopIteration

There's no problem running on window, and there's a problem on Ubuntu

code:
from tflearn.data_utils import image_preloader
data_dir = "/home/songpeng/dataset"
X, Y = image_preloader(data_dir, image_shape=(224, 224), mode='folder',
                       categorical_labels=True, normalize=True,
                       files_extension=['.jpg'], filter_channel=True)

**Comment by reedwm** [comment]
This looks like an issue with [TFLearn](https://github.com/tflearn/tflearn). Can you file an issue there instead?
