### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'keras'

### ISSUE THREAD

**Issue by ashishkumar14** [tensorflow/tensorflow#16614]
(tensorflow) admins-Mac-Pro:get_started admin$ python premade_estimator.py
Traceback (most recent call last):
  File "premade_estimator.py", line 88, in <module>
    tf.app.run(main)
  File "/Users/admin/Work/tensorflow/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "premade_estimator.py", line 34, in main
    (train_x, train_y), (test_x, test_y) = iris_data.load_data()
  File "/Users/admin/Work/tensorflow/models/samples/core/get_started/iris_data.py", line 19, in load_data
    train_path, test_path = maybe_download()
  File "/Users/admin/Work/tensorflow/models/samples/core/get_started/iris_data.py", line 12, in maybe_download
    train_path = tf.keras.utils.get_file(TRAIN_URL.split('/')[-1], TRAIN_URL)
AttributeError: module 'tensorflow' has no attribute 'keras'

**Comment by rimidalv** [comment]
What is tensorflow version?

**Comment by ashishkumar14** [comment]
tensorflow version 0.12.0

**Comment by rimidalv** [comment]
The keras was added in tensorflow 1.4
https://github.com/tensorflow/tensorflow/blob/r1.5/RELEASE.md#release-141

**Comment by ashishkumar14** [comment]
Thank you @rimidalv,  I upgrade it and it's working fine

**Comment by Samuel-Sigauke** [comment]
thank you

**Comment by Samuel-Sigauke** [comment]
thanks

**Comment by Masoume** [comment]
train_path = tf.keras.utils.get_file(TRAIN_URL.split('/')[-1], TRAIN_URL)
**AttributeError: 'module' object has no attribute 'keras'**

OS: Mac 10.13.3
TensorFlow Version: 1.5.0

**Comment by farzadhallaji** [comment]
`**AttributeError: 'module' object has no attribute 'keras'**`

Python 2.7.12
TensorFlow 1.2.0

**Comment by prashant-bansod** [comment]
Hi Everyone, I am getting the AttributeError: module 'keras_applications' has no attribute 'set_keras_submodules'.  I am running the code on Ububtu 16.04 
Tensroflow:1.12
I would appreciate your help with this. Thanks. 
```
[Traceback (most recent call last):
  File "multiprocess_detect_actions.py", line 11, in <module>
    import object_detection.object_detector as obj
  File "/home/prashantb/Documents/prashant_workspaace/ACAM_Demo/object_detection/object_detector.py", line 1, in <module>
    import tensorflow as tf
  File "/home/prashantb/anaconda3/envs/demo/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/prashantb/anaconda3/envs/demo/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 88, in <module>
    from tensorflow.python import keras
  File "/home/prashantb/anaconda3/envs/demo/lib/python3.6/site-packages/tensorflow/python/keras/__init__.py", line 25, in <module>
    from tensorflow.python.keras import applications
  File "/home/prashantb/anaconda3/envs/demo/lib/python3.6/site-packages/tensorflow/python/keras/applications/__init__.py", line 37, in <module>
    keras_applications.set_keras_submodules)[0]:
AttributeError: module 'keras_applications' has no attribute 'set_keras_submodules'
](url)
```

**Comment by pakashu** [comment]
still not resolved, my Tensorflow version 2.0.0a0

**Comment by Dayananda-V** [comment]
@pakashu 

Please check Keras-Applications version on your environment("pip list | grep Keras"). Try with remove existing Keras-Applications and install freshly and try one more time.

Use https://pypi.org/project/Keras-Applications/ to install Keras-Applications.

**Comment by JosephCatrambone** [comment]
I'm sorry to bump this closed ticket, but I'm having the same issue as Pakashu.  

```AttributeError: module 'tensorflow' has no attribute 'keras'```

On tensorflow-gpu 2.0.0a0, even after a forced uninstall/reinstall of Keras-Applications.

**Comment by TZVIh** [comment]
hey,
I have the same issue when I working in google cloud.
in my computer it works fine.
what should I do?
Thanks!

**Comment by zdyyyy** [comment]
![image](https://user-images.githubusercontent.com/44237873/66004415-c4c48c80-e476-11e9-8b0e-9be4c9d89b69.png)

**Comment by zdyyyy** [comment]
![image](https://user-images.githubusercontent.com/44237873/66004455-df970100-e476-11e9-9b97-b2daa21313ff.png)

**Comment by zdyyyy** [comment]
![image](https://user-images.githubusercontent.com/44237873/66004539-1240f980-e477-11e9-990e-f9d467ad51de.png)
What should I do?

**Comment by dmquin** [comment]
I'm having this problem too

TensorFlow v2
Python 3.7

```
C:\Users\DDD\Documents>python tut.py
Traceback (most recent call last):
  File "tut.py", line 6, in <module>
    data = keras.dataset.fashion_mnist
  File "C:\Users\DDD\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\tensorflow\__init__.py", line 51, in __getattr__
    return getattr(module, item)
AttributeError: module 'tensorflow_core.keras' has no attribute 'dataset'
```

**Code**

```
import tensorflow as tf
from tensorflow import keras
import numpy as np
import matplotlib.pyplot as plt

data = keras.dataset.fashion_mnist

(train_images, train_labels), (test_images, test_labels) = data.load_data()

print(train_labels)
```

**Comment by sam-cannon** [comment]
I'm having the same issue here

**Comment by lucas-hattori-costa** [comment]
Similar ticket here: https://github.com/tensorflow/tensorflow/issues/28213

I had the same problem because my folder was named tensorflow. Check if there isn't any other file named tensorflow for you.

**Comment by zgushonka** [comment]
In my case in JupyterNotebook after fixing and reinstall all dependencies I still got this error while importing Keras.
until restarting notebook: Kernel -> Restart

**Comment by liminn** [comment]
> still not resolved, my Tensorflow version 2.0.0a0

try reinstall tensorflow, sunch as `pip install tensorflow-gpu==2.2.0rc2` solved my problem

**Comment by minsky-1** [comment]
I have the same problem 
train_path = tf.keras.utils.get_file(
AttributeError: module 'tensorflow' has no attribute 'keras'

It took me years to install tensorflow with bazel, and the keras is there installed. In tensorflow... the file is there:
/usr/lib64/python3.6/site-packages/tensorflow/keras/preprocessing/image/__init__.py 
which it says it doesn't exist..

I installed aside Keras, aside... Now keras is in 
 ls /usr/lib/python3.6/site-packages/keras
activations.py  callbacks.py    engine           layers      models.py      preprocessing    utils
applications    constraints.py  initializers.py  losses.py   objectives.py  __pycache__      wrappers
backend.py      datasets        __init__.py      metrics.py  optimizers     regularizers.py

So all the files are there installed. the same is in /usr/lib64/python3.6/site-packages/tensorflow/keras/....

But I continue with the problem 

train_path = tf.keras.utils.get_file(
AttributeError: module 'tensorflow' has no attribute 'keras'

And when I explicitly import keras, 
the error is:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/keras/__init__.py", line 3, in <module>
    from tensorflow.keras.layers.experimental.preprocessing import RandomRotation
  File "/usr/lib64/python3.6/site-packages/tensorflow/keras/__init__.py", line 19, in <module>
    from . import datasets
  File "/usr/lib64/python3.6/site-packages/tensorflow/keras/datasets/__init__.py", line 14, in <module>
    from . import imdb
  File "/usr/lib64/python3.6/site-packages/tensorflow/keras/datasets/imdb/__init__.py", line 11, in <module>
    from tensorflow.python.keras.datasets.imdb import get_word_index
  File "/usr/lib64/python3.6/site-packages/tensorflow/python/keras/datasets/imdb.py", line 25, in <module>
    from tensorflow.python.keras.preprocessing.sequence import _remove_long_seq
  File "/usr/lib64/python3.6/site-packages/tensorflow/python/keras/preprocessing/__init__.py", line 26, in <module>
    from tensorflow.python.keras.preprocessing import image
  File "/usr/lib64/python3.6/site-packages/tensorflow/python/keras/preprocessing/image.py", line 23, in <module>
    from keras_preprocessing import image
  File "/usr/lib/python3.6/site-packages/keras_preprocessing/image.py", line 18, in <module>
    backend = get_keras_submodule('backend')
  File "/usr/lib/python3.6/site-packages/keras_preprocessing/__init__.py", line 24, in get_keras_submodule
    raise ImportError('You need to first `import keras` '
ImportError: You need to first `import keras` in order to use `keras_preprocessing`. For instance, you can do:

```
import keras
from keras_preprocessing import image
```

Or, preferably, this equivalent formulation:

```
from keras import preprocessing
```


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/carlos/.PyCharmCE2019.3/config/scratches/classification.py", line 7, in <module>
    import keras
  File "/usr/lib/python3.6/site-packages/keras/__init__.py", line 6, in <module>
    'Keras requires TensorFlow 2.2 or higher. '
ImportError: Keras requires TensorFlow 2.2 or higher. Install TensorFlow via `pip install tensorflow`

My tensorflow installation when I do  
%pip3 list | grep tensorflow is:

tensorflow                             2.2.0
tensorflow-estimator                   2.2.0

And when I do:
%pip3 list | grep keras

keras-tuner                            1.0.2rc1.dev0


Please, any help... How do I tell pycharm that everythin is there...!!!!

**Comment by MagonBC** [comment]
I had the same Error while trying some labs here -> https://github.com/https-deeplearning-ai/tensorflow-1-public
Resolved by installing [requirements.txt](https://github.com/https-deeplearning-ai/tensorflow-1-public/blob/main/C1/requirements.txt)

jupyterlab
dlai-grader
tensorflow
keras
tensorflow-datasets
pandas
matplotlib
ipywidgets
pooch

I don't know which package exactly resolved the error
