### ISSUE TITLE
update tensorflow to 1.5 

### ISSUE THREAD

**Issue by Tracy6465** [tensorflow/tensorflow#16622]
I update tensorflow to 1.5,and reinstall cuda to 9.1,now  I run my program get the error:
Traceback (most recent call last):
  File "/home/chris/tensorflowDemo/7_1_Word2Vec.py", line 24, in <module>
    import tensorflow as tf
  File "/home/chris/.local/lib/python3.5/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/home/chris/.local/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/chris/.local/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/chris/.local/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/chris/.local/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/chris/.local/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory

**Comment by CNugteren** [comment]
That's an issue with your CUDA install: cuBLAS is not in your library path. If you are on Linux, you should set up your `LD_LIBRARY_PATH` properly, e.g. like this (depending on where you installed CUDA 9):
```
export CUDA_HOME=/usr/local/cuda/
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$CUDA_HOME/lib64:$CUDA_HOME/extras/CUPTI/lib64"
```

**Comment by Tracy6465** [comment]
**I have set the variables**
chris@chris:~$ echo $CUDA_HOME
/usr/local/cuda-9.1
chris@chris:~$ echo $LD_LIBRARY_PATH
/home/chris/torch/install/lib:/home/chris/torch/install/lib:/usr/local/cuda-9.1/lib64:/usr/local/cuda-9.1/extras/CUPTI/lib64:/home/chris/torch/install/lib:

**Comment by CNugteren** [comment]
In that case there is something wrong with your CUDA installation. CUDA should come with `libcublas.so` in the `lib64` subdirectory. My CUDA 9.1 installation has it, so should yours. Try to reinstall CUDA?

**Comment by kasyoukin** [comment]
@CNugteren I meet the same problem, and my CUDA come with libcublas.so in the lib64 subdirector
![2018-02-01 18-34-58](https://user-images.githubusercontent.com/8893270/35674136-ac0253e8-077e-11e8-89a5-103bb00dd2cf.png)

**Comment by Tracy6465** [comment]
I uninstalled the cuda9.1,and install cuda9.0. Now it works.

**Comment by nadavb** [comment]
Where did you install cuda 9.0 from? I only see there the 9.1 version (for ubuntu 16)

**Comment by Tracy6465** [comment]
@nadavb 
https://developer.nvidia.com/cuda-90-download-archive

**Comment by michaelisard** [comment]
Closing, but please reopen if this is not resolved.
