### ISSUE TITLE
ImportError after compiling

### ISSUE THREAD

**Issue by webprogrammingsolutions** [tensorflow/tensorflow#16641]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:

Yes. I followed this guide in an attempt to gain GPU support under macOS. (https://tweakmind.com/tensorflow-1-5-macos-10-13-2/). The code changes are made by these commands:

sed -i.bu 's/__align__(sizeof(T)) //g' tensorflow/core/kernels/depthwise_conv_op_gpu.cu.cc
sed -i.bu 's/__align__(sizeof(T)) //g' tensorflow/core/kernels/split_lib_gpu.cu.cc
sed -i.bu 's/__align__(sizeof(T)) //g' tensorflow/core/kernels/concat_lib_gpu_impl.cu.cc

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
macOS 10.13.2 High Sierra

- **TensorFlow installed from (source or binary)**:
Source

- **TensorFlow version (use command below)**:
1.5

- **Python version**: 
3.6.4

- **Bazel version (if compiling from source)**:
0.9.0-homebrew

- **GCC/Compiler version (if compiling from source)**:
xcode 8.3.3

- **CUDA/cuDNN version**:
9.1 / 7

- **GPU model and memory**:
Nvidia GTX 1080 Ti

- **Exact command to reproduce**:
python
import tensorflow as tf

### Describe the problem
After following the guide at the URL above, building w/bazel and creating the wheel, I installed the tensorflow package with pip3 install --upgrade --force-reinstall <package name> and was successful. However, when I try to import tensorflow, I get an ImportError, Symbol not found: _PyCObject_Type

### Source code / logs

python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 6): Symbol not found: _PyCObject_Type
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
  Expected in: flat namespace
 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 6): Symbol not found: _PyCObject_Type
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
  Expected in: flat namespace
 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so

Failed to load the native TensorFlow runtime.

**Comment by reedwm** [comment]
/CC @gunan, any ideas? I'm not sure if we support using a GPU on macs. If we don't, this should be tagged with community support.

**Comment by webprogrammingsolutions** [comment]
As of v1.2 you do not support GPU on Mac, however there have been several people post succesful workarounds. My hope in posting this issue was that it might be something common to other builds and someone could help me get it sorted.

**Comment by gunan** [comment]
Stackoverflow may be a better place for reaching out for community support. However, your issue does not seem related to cuda itself. This is the line you should be paying attention to:
```
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 6): Symbol not found: _PyCObject_Type
```

**Comment by kaiiyer** [comment]
GPU on mac is not that compatible
but external GPU cann be set up
read more from here https://egpu.io/

**Comment by rthadur** [comment]
This is now supported with latest versions , please check https://blog.tensorflow.org/2020/11/accelerating-tensorflow-performance-on-mac.html.
