### ISSUE TITLE
Feature request: Support SparseTensor in Dataset.from_generator 

### ISSUE THREAD

**Issue by rasmusbergpalm** [tensorflow/tensorflow#16689]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No

== cat /etc/issue ===============================================
Darwin c02ql2p2fvh7-c 16.7.0 Darwin Kernel Version 16.7.0: Mon Nov 13 21:56:25 PST 2017; root:xnu-3789.72.11~1/RELEASE_X86_64 x86_64
Mac OS X 10.12.6

== are we in docker =============================================
No

== compiler =====================================================
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

== uname -a =====================================================
Darwin c02ql2p2fvh7-c 16.7.0 Darwin Kernel Version 16.7.0: Mon Nov 13 21:56:25 PST 2017; root:xnu-3789.72.11~1/RELEASE_X86_64 x86_64

== check pips ===================================================
numpy (1.14.0)
protobuf (3.5.1)
tensorflow (1.5.0)
tensorflow-tensorboard (1.5.0)

== check for virtualenv =========================================
False

== tensorflow import ============================================
tf.VERSION = 1.5.0
tf.GIT_VERSION = v1.5.0-0-g37aa430d84
tf.COMPILER_VERSION = v1.5.0-0-g37aa430d84
Sanity check: array([1], dtype=int32)
/Users/rbp/anaconda/envs/python3/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: compiletime version 3.6 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.5
  return f(*args, **kwds)
/Users/rbp/anaconda/envs/python3/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters

== env ==========================================================
LD_LIBRARY_PATH is unset
DYLD_LIBRARY_PATH is unset

== nvidia-smi ===================================================
./tf_env_collect.sh: line 105: nvidia-smi: command not found

- **Exact command to reproduce**:

```
        def generator():
            indices = [(1, 1)]
            values = (1.,)
            shape = (3, 3)
            while True:
                yield tf.SparseTensor(indices, values, shape)

        iterator = tf.data.Dataset.from_generator(generator, tf.float32, (3,3)).make_one_shot_iterator()

        sample = iterator.get_next()
        ss = tf.sparse_reduce_sum(sample)
        with tf.Session() as sess:
            _ss = sess.run(ss)
```

### Describe the problem

Above code throws `AttributeError: 'Tensor' object has no attribute 'indices'`

It seems the `from_generator` always expects Tensors as output.

**Comment by mrry** [comment]
It should be possible to do something here, although the `from_generator()` signature would need to expand (e.g. with `output_classes`?) to provide a way for the caller to specify that an output should be interpreted as a `tf.SparseTensor`. I've marked this as "contributions welcome", since it is unlikely that anyone on the team will get to this for a while, and there is a workaround as follows:

```python
def generator():
    indices = [(1, 1)]
    values = (1.,)
    shape = (3, 3)
    while True:
        yield (indices, values, shape)

dataset = tf.data.Dataset.from_generator(generator, (tf.int64, tf.float32, tf.int64))
dataset = dataset.map(lambda i, v, s: tf.SparseTensor(i, v, s))
iterator = dataset.make_one_shot_iterator()

sample = iterator.get_next()
ss = tf.sparse_reduce_sum(sample)
with tf.Session() as sess:
    _ss = sess.run(ss)
```

/cc @jsimsa

**Comment by qiang2008** [comment]
@mrry  if two  or  more  sparse tensor ,how to  code?

**Comment by mrry** [comment]
@qiang2008 You can extend the `output_types` arguments in that example to return as many sparse tensors as you like. For example:

```python
def generator():
    indices = [(1, 1)]
    values = (1.,)
    shape = (3, 3)
    while True:
        yield (indices, values, shape), (indices, values, shape)

dataset = tf.data.Dataset.from_generator(generator, ((tf.int64, tf.float32, tf.int64), (tf.int64, tf.float32, tf.int64)))

```

**Comment by reuben** [comment]
@mrry I'm seeing a difference in behavior between `from_tensor_slices` and your proposed solution when batching the resulting dataset:

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import absolute_import, division, print_function

import tensorflow as tf
import numpy as np

tf.enable_eager_execution()


def to_sparse_tuple(sequences, dtype=np.int32):
    indices = []
    values = []

    for n, seq in enumerate(sequences):
        indices.extend(zip([n]*len(seq), range(len(seq))))
        values.extend(seq)

    indices = np.asarray(indices, dtype=np.int64)
    values = np.asarray(values, dtype=dtype)
    shape = np.asarray([len(sequences), indices.max(0)[1]+1], dtype=np.int64)

    return indices, values, shape


def to_sparse_tensor(sequences, dtype=np.int32):
    return tf.SparseTensor(*to_sparse_tuple(sequences, dtype))


print('Using from_tensor_slices:')
sparse = to_sparse_tensor([[0], [1, 2, 3]])
dset = tf.data.Dataset.from_tensor_slices(sparse).batch(2)
for t in dset:
    print(t)


print('Using from_generator:')
def generate_values():
    yield to_sparse_tuple([[0]])
    yield to_sparse_tuple([[1, 2, 3]])

dset = (tf.data.Dataset.from_generator(generate_values, output_types=(tf.int64, tf.int32, tf.int64))
                       .map(lambda i, v, s: tf.SparseTensor(i, v, s))
                       .batch(2))
for t in dset:
    print(t)
```

Output:

```
Using from_tensor_slices:
SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 0]
 [1 1]
 [1 2]], shape=(4, 2), dtype=int64), values=tf.Tensor([0 1 2 3], shape=(4,), dtype=int32), dense_shape=tf.Tensor([2 3], shape=(2,), dtype=int64))
Using from_generator:
SparseTensor(indices=tf.Tensor(
[[0 0 0]
 [1 0 0]
 [1 0 1]
 [1 0 2]], shape=(4, 3), dtype=int64), values=tf.Tensor([0 1 2 3], shape=(4,), dtype=int32), dense_shape=tf.Tensor([2 1 3], shape=(3,), dtype=int64))
```

The source of the problem seems to be that you can't create a 1D SparseTensor, so each individual tensor yielded by the generator is 2D, and then when you batch them the result is 3D.

This 3D result can't be used for example with CTCLoss, it complains about the shape (the 2D output using `from_tensor_slices` works fine):

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import absolute_import, division, print_function

import tensorflow as tf
import numpy as np

tf.enable_eager_execution()


def to_sparse_tuple(sequences, dtype=np.int32):
    indices = []
    values = []

    for n, seq in enumerate(sequences):
        indices.extend(zip([n]*len(seq), range(len(seq))))
        values.extend(seq)

    indices = np.asarray(indices, dtype=np.int64)
    values = np.asarray(values, dtype=dtype)
    shape = np.asarray([len(sequences), indices.max(0)[1]+1], dtype=np.int64)

    return indices, values, shape


def to_sparse_tensor(sequences, dtype=np.int32):
    return tf.SparseTensor(*to_sparse_tuple(sequences, dtype))


def generate_values():
    yield to_sparse_tuple([[0]])
    yield to_sparse_tuple([[1, 2, 3]])

dset = (tf.data.Dataset.from_generator(generate_values, output_types=(tf.int64, tf.int32, tf.int64))
                       .map(lambda i, v, s: tf.SparseTensor(i, v, s))
                       .batch(2))
for t in dset:
    loss = tf.nn.ctc_loss(t, np.random.rand(3, 2, 5), [1, 3])
```

Result:
```
2019-03-16 12:01:40.561683: W tensorflow/core/framework/op_kernel.cc:1431] OP_REQUIRES failed at ctc_loss_op.cc:106 : Invalid argument: Order length must be SparseTensor rank.
Traceback (most recent call last):
  File "test_sparse_from_generator.py", line 38, in <module>
    loss = tf.nn.ctc_loss(t, np.random.rand(3, 2, 5), [1, 3])
  File "/Users/rmorais/.local/share/virtualenvs/DeepSpeech-HmF6CP0D/lib/python3.6/site-packages/tensorflow/python/ops/ctc_ops.py", line 175, in ctc_loss
    ignore_longer_outputs_than_inputs=ignore_longer_outputs_than_inputs)
  File "/Users/rmorais/.local/share/virtualenvs/DeepSpeech-HmF6CP0D/lib/python3.6/site-packages/tensorflow/python/ops/gen_ctc_ops.py", line 309, in ctc_loss
    name=name, ctx=_ctx)
  File "/Users/rmorais/.local/share/virtualenvs/DeepSpeech-HmF6CP0D/lib/python3.6/site-packages/tensorflow/python/ops/gen_ctc_ops.py", line 378, in ctc_loss_eager_fallback
    ctx=_ctx, name=name)
  File "/Users/rmorais/.local/share/virtualenvs/DeepSpeech-HmF6CP0D/lib/python3.6/site-packages/tensorflow/python/eager/execute.py", line 66, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: Order length must be SparseTensor rank. [Op:CTCLoss]
```

**Comment by reuben** [comment]
Workaround using `tf.sparse.reshape`:

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import absolute_import, division, print_function

import tensorflow as tf
import numpy as np

tf.enable_eager_execution()


def to_sparse_tuple(sequences, dtype=np.int32):
    indices = []
    values = []

    for n, seq in enumerate(sequences):
        indices.extend(zip([n]*len(seq), range(len(seq))))
        values.extend(seq)

    indices = np.asarray(indices, dtype=np.int64)
    values = np.asarray(values, dtype=dtype)
    shape = np.asarray([len(sequences), indices.max(0)[1]+1], dtype=np.int64)

    return indices, values, shape


def to_sparse_tensor(sequences, dtype=np.int32):
    return tf.SparseTensor(*to_sparse_tuple(sequences, dtype))


print('Using from_tensor_slices:')
sparse = to_sparse_tensor([[0], [1, 2, 3]])
dset = tf.data.Dataset.from_tensor_slices(sparse).batch(2)
for t in dset:
    print(t)


print('Using from_generator:')
def generate_values():
    yield to_sparse_tuple([[0]])
    yield to_sparse_tuple([[1, 2, 3]])

def sparse_reshape(sparse):
    shape = sparse.dense_shape
    return tf.sparse.reshape(sparse, [shape[0], shape[2]])

dset = (tf.data.Dataset.from_generator(generate_values, output_types=(tf.int64, tf.int32, tf.int64))
                       .map(lambda i, v, s: tf.SparseTensor(i, v, s))
                       .batch(2)
                       .map(sparse_reshape))
for t in dset:
    print(t)
    loss = tf.nn.ctc_loss(t, np.random.rand(3, 2, 5), [1, 3])
```

Result:

```
Using from_tensor_slices:
SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 0]
 [1 1]
 [1 2]], shape=(4, 2), dtype=int64), values=tf.Tensor([0 1 2 3], shape=(4,), dtype=int32), dense_shape=tf.Tensor([2 3], shape=(2,), dtype=int64))
Using from_generator:
SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 0]
 [1 1]
 [1 2]], shape=(4, 2), dtype=int64), values=tf.Tensor([0 1 2 3], shape=(4,), dtype=int32), dense_shape=tf.Tensor([2 3], shape=(2,), dtype=int64))
```

**Comment by MishaelRosenthal** [comment]
What about the following?

```python
def dataset_from_sparse_tensor_slices(sparse_tensors):
  """
  Similar to tf.data.Dataset.from_tensor_slices but from sparse tensors.
  """
  def gen():
    for x in sparse_tensors:
      yield (x.indices, x.values, x.dense_shape)

  # Assumes non empty.
  first = next(gen())
  tuples = tf.data.Dataset.from_generator(gen, tuple(map(lambda x: x.dtype, first)))
  return tuples.map(lambda indices, values, dense_shape: tf.SparseTensor(indices, values, dense_shape))
```

Just for testing:
```python
sparse_tensors = [
 tf.SparseTensor(indices = [[0, 0], [0, 1]], values=[2, 3], dense_shape=[2, 2]),
 tf.SparseTensor(indices = [[1, 0], [0, 1]], values=[5, 7], dense_shape=[2, 2]),
 tf.SparseTensor(indices = [[0, 0], [0, 1], [1, 1]], values=[-2, 7, 18], dense_shape=[2, 2])
]

for x in dataset_from_sparse_tensor_slices(sparse_tensors):
  print(x)
```

Prints:
```
SparseTensor(indices=tf.Tensor(
[[0 0]
 [0 1]], shape=(2, 2), dtype=int64), values=tf.Tensor([2 3], shape=(2,), dtype=int32), dense_shape=tf.Tensor([2 2], shape=(2,), dtype=int64))
SparseTensor(indices=tf.Tensor(
[[1 0]
 [0 1]], shape=(2, 2), dtype=int64), values=tf.Tensor([5 7], shape=(2,), dtype=int32), dense_shape=tf.Tensor([2 2], shape=(2,), dtype=int64))
SparseTensor(indices=tf.Tensor(
[[0 0]
 [0 1]
 [1 1]], shape=(3, 2), dtype=int64), values=tf.Tensor([-2  7 18], shape=(3,), dtype=int32), dense_shape=tf.Tensor([2 2], shape=(2,), dtype=int64))
```
