### ISSUE TITLE
ImportError: /usr/local/lib/python2.7/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: _Py_FalseStruct

### ISSUE THREAD

**Issue by youthpasses** [tensorflow/tensorflow#16720]
I update my tensorflow to 1.5, the last version is 1.3.0. But I got a issue about numpy, after lot of attempts, it was solved, numpy can be used. 

**But now, I have a new issue when I import tensorflow:**

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: /usr/local/lib/python2.7/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: _Py_FalseStruct

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

I can't get any solutions on the Internet. Anyone can help me?

**Comment by martinwicke** [comment]
This error (`undefined symbol: _Py_FalseStruct`) is a symptom of a mismatch between the python version and the version of a module. Have you somehow installed the py3 version of tensorflow into your py2 environment?

How did you install TensorFlow? 

Can you try to install tensorflow into a clean virtualenv? It does look like your python installation is broken.

**Comment by tensorflowbutler** [comment]
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by martinwicke** [comment]
I'll close this, assuming this is a problem with your installation. Please reopen if more information is available.

**Comment by sarahwxj** [comment]
Hello, I met a problem like yours. I have a model in docker and I try to train it. It works and everything is ok. But later on , I try t train it, a problem occurs:
ImportError: /usr/local/lib/python2.7/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: _ZTIN10tensorflow17CostGraphDef_NodeE
Failed to load the native TensorFlow runtime.
Could you please give some suggestion? Thank you in advance.

**Comment by sandip-narwade** [comment]
ImportError: /usr/local/lib/python3.6/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: _Py_FalseStruct


I am using flask and wsgi
