### ISSUE TITLE
Debug prompts use_default_colors() returned ERR

### ISSUE THREAD

**Issue by MrWanter** [tensorflow/tensorflow#16799]
I was running a example code from [tensorpack](http://tensorpack.readthedocs.io/en/latest/index.html) on Pycharm, which runs properly, then I changed the session to 
`sess = tf_debug.LocalCLIDebugWrapperSession(sess) ` in order to debug
as suggested by official example https://www.tensorflow.org/programmers_guide/debugger, but then I got:
```
Traceback (most recent call last):
  File "/home/user/.pycharm_helpers/pydev/pydev_run_in_console.py", line 53, in run_file
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/user/prj/shufflenet_v1/shufflenet.py", line 231, in <module>
    launch_train_with_config(config, SyncMultiGPUTrainerParameterServer(nr_tower))
  File "/home/user/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorpack/train/interface.py", line 96, in launch_train_with_config
    config.steps_per_epoch, config.starting_epoch, config.max_epoch)
  File "/home/user/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorpack/train/base.py", line 288, in train
    self.main_loop(steps_per_epoch, starting_epoch, max_epoch)
  File "/home/user/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorpack/utils/argtools.py", line 171, in wrapper
    return func(*args, **kwargs)
  File "/home/user/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorpack/train/base.py", line 239, in main_loop
    self.loop.update_global_step()
  File "/home/user/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorpack/train/base.py", line 59, in update_global_step
    self._global_step = get_global_step_value()
  File "/home/user/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorpack/tfutils/common.py", line 77, in get_global_step_value
    get_global_step_var())
  File "/home/user/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/training/training_util.py", line 67, in global_step
    return int(sess.run(global_step_tensor))
  File "/home/user/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/debug/wrappers/framework.py", line 455, in run
    is_callable_runner=bool(callable_runner)))
  File "/home/user/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/debug/wrappers/local_cli_wrapper.py", line 253, in on_run_start
    self._prep_cli_for_run_start()
  File "/home/user/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/debug/wrappers/local_cli_wrapper.py", line 275, in _prep_cli_for_run_start
    self._run_cli = ui_factory.get_ui(self._ui_type)
  File "/home/user/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/debug/cli/ui_factory.py", line 56, in get_ui
    return curses_ui.CursesUI(on_ui_exit=on_ui_exit)
  File "/home/user/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/debug/cli/curses_ui.py", line 285, in __init__
    self._screen_init()
  File "/home/user/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/debug/cli/curses_ui.py", line 400, in _screen_init
    self._screen_color_init()
  File "/home/user/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/debug/cli/curses_ui.py", line 405, in _screen_color_init
    curses.use_default_colors()
error: use_default_colors() returned ERR
```
which I have no clue for the reason, can someone help?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by MrWanter** [comment]
I run `tfdbg` in `pycharm`, switch to terminal solve the problem

**Comment by skye** [comment]
Thanks for sharing your solution! cc/ @caisq
