### ISSUE TITLE
transform_graph generates faulty model after optimization (quantisation).

### ISSUE THREAD

**Issue by kmonachopoulos** [tensorflow/tensorflow#16803]
------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:
source
- **TensorFlow version (use command below)**:
- **Python version**: 
1.4.1
- **Bazel version (if compiling from source)**:
0.8.1
- **GCC/Compiler version (if compiling from source)**:
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.6)

### Describe the problem
I am using a pre-trained style transfer model that I have converted  to .pb format. When I inference a single image through the fp32 model then I can see the styled image at the output of the network and everything works fine. Later on I optimized the model for inference using `transform_graph` tool with these parameters : 

```
--transforms='
  add_default_attributes
  strip_unused_nodes(type=float)
  remove_nodes(op=CheckNumerics)
  fold_constants(ignore_errors=true)
  fold_batch_norms
  fold_old_batch_norms
  quantize_weights
  quantize_nodes
  strip_unused_nodes
  sort_by_execution_order'
```
the quantised models (.pb) generated successfully but now I have problem with inference when I execute sess.run().

### Source code / logs
```
Traceback (most recent call last):
  File "Inf_Image_pb.py", line 89, in <module>
    Session_out = sess.run(l_output, feed_dict={l_input: image})            
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Shapes of all inputs must match: values[0].shape = [474,712,3] != values[2].shape = []
	 [[Node: Reshape/shape = Pack[N=3, T=DT_INT32, axis=0, _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_input_image_0_0, _arg_input_image_0_0, Reshape/shape/2)]]

Caused by op u'Reshape/shape', defined at:
  File "Inf_Image_pb.py", line 74, in <module>
    producer_op_list=None
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/importer.py", line 313, in import_graph_def
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Shapes of all inputs must match: values[0].shape = [474,712,3] != values[2].shape = []
	 [[Node: Reshape/shape = Pack[N=3, T=DT_INT32, axis=0, _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_input_image_0_0, _arg_input_image_0_0, Reshape/shape/2)]]
```
I have tried other tensorflow versions, other bazel versions to rebuild the tool and the legacy quantisation tool 'quantize_graph' with mode --mode=eightbit but still fail to inference. In addition I tried other transform combinations using the `transform_graph` tool, other batch sizes and other input dimensions but still getting error. What is this error refers to ? I can't find any useful information online ..

**Comment by kmonachopoulos** [comment]
This is the part that I am getting the error : 

![image](https://user-images.githubusercontent.com/3832904/35868951-dfd9674e-0b55-11e8-87e8-3a92a8931a18.png)

**Comment by skye** [comment]
@suharshs can you comment or redirect? Thanks!

**Comment by suharshs** [comment]
cc @petewarden 

transform_graph has had some hard to debug issue for various models in the past. From your error, it seems that some transformation is screwing up shape information in the graph, but i am really not sure. 

We have focused our 8-bit quantization efforts for mobile models on TensorFlow Lite : https://www.tensorflow.org/mobile/tflite/. Currently TFLite quantizations requires quantizing both weights and activations, though this may change.

We use fake quantized training (https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/quantize) to get models that are compatible with TensorFlow Lite's converter, TOCO. TOCO can then convert these models to fully quantized models. We find that for many models, quantizing with training in the loop is necessary for good accuracy.
We are working on making these rewriters more general over various models, so expect improvements in this department.

Here are some examples for how we train mobilenet_v1 for quantization : https://github.com/tensorflow/models/blob/master/research/slim/nets/mobilenet_v1.md

The graph resulting from https://github.com/tensorflow/models/blob/master/research/slim/nets/mobilenet_v1_eval.py is compatible with TensorFlow Lite.

Hope that helps!

What model architecture are you trying to quantize? Are you ok with quantizing both weights and activations?

**Comment by kmonachopoulos** [comment]
Hi @suharshs,

Thanks for the information. I am currently not interested on gaining back the quatnization error through re-training but only to manage to inference through the quantized graph. The model is a style transfer model and I want to quantize both weights and activations as I am showing above.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @suharshs: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @suharshs: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @suharshs: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @suharshs: It has been 78 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @suharshs: It has been 94 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @suharshs: It has been 110 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by kmonachopoulos** [comment]
Hello,

I think that the activity is expected by you ...

Thanks.

**Comment by suharshs** [comment]
Hi @kmonachopoulos ,

We are working on putting together weight and activation quantization for TensorFlow Lite (that doesn't require training), will keep you posted once that is ready.

In the meantime can you inspect the inputs of the culprit "Reshape/shape" (looks like it is a Pack node) node before and after you call the transformation to see what exactly is changing. This may give you some hints as to what is going wrong with the shapes.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @suharshs: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @suharshs: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tofulawrence** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
