### ISSUE TITLE
TensorFlow Lite for Inception v3 - Squeeze operator isn't supported

### ISSUE THREAD

**Issue by Johnson145** [tensorflow/tensorflow#16813]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No, I haven't used any custom code for this.
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:
source
- **TensorFlow version (use command below)**:
r1.5 (6c5063a3f099c302412fcefa17edb2efa9921f01)
- **Python version**: 
3
- **Bazel version (if compiling from source)**:
0.9.0
- **GCC/Compiler version (if compiling from source)**:
gcc4.4
- **CUDA/cuDNN version**:
9.0/7.0
- **GPU model and memory**:
GTX 1080 8GB
- **Exact command to reproduce**:
```
bazel-bin/tensorflow/contrib/lite/toco/toco \
  --input_file=inception-retrained-graph_freezed.pb \
  --input_format=TENSORFLOW_GRAPHDEF  --output_format=TFLITE \
  --output_file=inception-retrained-graph.tflite --inference_type=FLOAT \
  --input_type=FLOAT --input_arrays=input \
  --output_arrays=InceptionV3/Predictions/Reshape_1 --input_shapes=1,299,299,3
```

### Describe the problem
I tried to use the above command to convert a retrained inception v3 model into the new tflite format. The input graph has already been freezed. The general process is described in [this tutorial](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/lite#freeze-graph). However, I'm not able to finish the conversion as the tool complains that the Squeeze operator isn't supported. [According to this guide](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/lite/g3doc/tf_ops_compatibility.md) the script should be able to remove the squeeze operation. [This comment](https://github.com/tensorflow/tensorflow/issues/16001#issuecomment-356635651) suggests that it may not always be possible to remove it. [The inception v3 architecture is guaranteed to work though](https://www.tensorflow.org/mobile/tflite/). Am I safe using the `--allow_custom_ops` flag?

Some final note:
I retrained the inception net using the [slim model](https://github.com/tensorflow/models/tree/master/research/inception/inception/slim) rather than just retraining the last layer using the freezed graph version. May this be the cause of the additional squeeze problem?

### Source code / logs
This is the complete log as returned by the toco script:
```
W tensorflow/contrib/lite/toco/toco_cmdline_flags.cc:178] --input_type is deprecated. It was an ambiguous flag that set both --input_data_types and --inference_input_type. If you are trying to complement the input file with information about the type of input arrays, use --input_data_type. If you are trying to control the quantization/dequantization of real-numbers input arrays in the output file, use --inference_input_type.
2018-02-07 01:23:50.754337: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 1074 operators, 1657 arrays (0 quantized)
2018-02-07 01:23:50.826283: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 1: 126 operators, 317 arrays (0 quantized)
2018-02-07 01:23:50.827683: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before dequantization graph transformations: 126 operators, 317 arrays (0 quantized)
2018-02-07 01:23:50.828908: I tensorflow/contrib/lite/toco/allocate_transient_arrays.cc:313] Total transient array allocated size: 11139584 bytes, theoretical optimal value: 8297856 bytes.
2018-02-07 01:23:50.829206: I tensorflow/contrib/lite/toco/toco_tooling.cc:269] Estimated count of arithmetic ops: 11.4574 billion (note that a multiply-add is counted as 2 ops).
2018-02-07 01:23:50.829493: F tensorflow/contrib/lite/toco/tflite/export.cc:303] Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If you have a custom implementation for them you can disable this error with --allow_custom_ops. Here is a list of operators for which you will need custom implementations: Squeeze.
[1]    16187 abort (core dumped)  bazel-bin/tensorflow/contrib/lite/toco/toco   --output_format=TFLITE
```

**Comment by Johnson145** [comment]
I just figured out that the [commit which is required for the squeeze support](ec652809b15b9308d3f9e864cd8d0b97a532b64a) was actually added after the v1.5 release. Using the latest master commit works just fine. However, it should be considered to backport this feature as the [1.5 docs](https://github.com/tensorflow/tensorflow/blob/r1.5/tensorflow/contrib/lite/g3doc/tf_ops_compatibility.md) already list the squeeze operator as supported (more precisely it's listed as removable).

**Comment by Johnson145** [comment]
Unfortunately, I still can't use any inception model that I retrained on my own. Using the master branch fixes the above error and allows using the [precompiled inception-v3 slim model](https://storage.googleapis.com/download.tensorflow.org/models/tflite/inception_v3_slim_2016_android_2017_11_10.zip). The latter implies that there shouldn't be any problem with the slim version in general. It doesn't work with mine though. The tflite conversion seems to be completed without any errors now, but if I want to use the graph in the Android example app, I always get the following crash log:
```
02-07 17:32:06.651 18636-18651/android.example.com.tflitecamerademo E/AndroidRuntime: FATAL EXCEPTION: CameraBackground
                                                                                      Process: android.example.com.tflitecamerademo, PID: 18636
                                                                                      java.lang.IllegalArgumentException: Invalid handle to Interpreter.
                                                                                          at org.tensorflow.lite.NativeInterpreterWrapper.getInputDims(Native Method)
                                                                                          at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:82)
                                                                                          at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:112)
                                                                                          at org.tensorflow.lite.Interpreter.run(Interpreter.java:93)
                                                                                          at com.example.android.tflitecamerademo.ImageClassifierFloatInception.runInference(ImageClassifierFloatInception.java:103)
                                                                                          at com.example.android.tflitecamerademo.ImageClassifier.classifyFrame(ImageClassifier.java:107)
                                                                                          at com.example.android.tflitecamerademo.Camera2BasicFragment.classifyFrame(Camera2BasicFragment.java:664)
                                                                                          at com.example.android.tflitecamerademo.Camera2BasicFragment.-wrap0(Camera2BasicFragment.java)
                                                                                          at com.example.android.tflitecamerademo.Camera2BasicFragment$4.run(Camera2BasicFragment.java:559)
                                                                                          at android.os.Handler.handleCallback(Handler.java:739)
                                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                          at android.os.Looper.loop(Looper.java:158)
                                                                                          at android.os.HandlerThread.run(HandlerThread.java:61)
```

It doesn't help to recreate the input graph using the current TensorFlow version. I also tried to start the conversion using python instead of the command line, but it doesn't help either.

Any thoughts?

**Comment by andrehentz** [comment]
The java exception seems to imply that file you are trying to read is invalid. I'd say loading failed at https://github.com/tensorflow/tensorflow/blob/d4ad9c73969c45d1a224ebfc43eb645b9860216b/tensorflow/contrib/lite/java/src/main/native/nativeinterpreterwrapper_jni.cc#L296 but I can't tell exactly why.

**Comment by Johnson145** [comment]
Thanks for your answer. Yes, it states that my model file seems to be invalid, but I don't see a reason why. Unfortunately, I'm not really familiar with the native code parts. Can someone give me some hints how to debug this appropriately?

**Comment by tensorflowbutler** [comment]
Nagging Assignee @andrehentz: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @andrehentz: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @andrehentz: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @andrehentz: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by andrehentz** [comment]
Hi @Johnson145 any chance you can try this again? I'm hoping the new versions will give you a better error message and help debug.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @andrehentz: It has been 30 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @andrehentz: It has been 45 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by andrehentz** [comment]
Could you try this again? Can you confirm that toco succeeds and a non-zero file is created?

**Comment by tensorflowbutler** [comment]
Nagging Assignee @andrehentz: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @andrehentz: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by anitha-v** [comment]
Closing it, please reopen if you still see this issue
