### ISSUE TITLE
 tensorflow/tensorflow/contrib/factorization/python/ops/gmm_ops_test.py  FAILED

### ISSUE THREAD

**Issue by ludovicdmt** [tensorflow/tensorflow#16832]
### System information
- **Code** :  tensorflow/tensorflow/contrib/factorization/python/ops/gmm_ops_test.py
- **OS Platform and Distribution** : Linux Ubuntu 16.04)
- **TensorFlow installed from** : Binary
- **TensorFlow version** : '1.4.0'
- **Python version**:  2.7.12
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**: CUDA 8.0 & cuDNN 6.0
- **GPU model and memory**: Nvidia 1080Ti
- **Exact command to reproduce**: python gmm_ops_test.py

### Issue
gmm test isn't working, either gmm_ops_test.py 

### Error message
```
`======================================================================
ERROR: testParams (__main__.GmmOpsTest)
Tests that the params work as intended.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "gmm_ops_test.py", line 147, in testParams
    sess.run(training_ops)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
InvalidArgumentError: Incompatible shapes: [1,1000,2] vs. [0]
	 [[Node: sub_2 = Sub[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](ExpandDims_2, clusters/read)]]

Caused by op u'sub_2', defined at:
  File "gmm_ops_test.py", line 200, in <module>
    tf.test.main()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/test.py", line 73, in main
    return _googletest.main(argv)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/googletest.py", line 99, in main
    benchmark.benchmarks_main(true_main=main_wrapper)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/benchmark.py", line 341, in benchmarks_main
    true_main()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/googletest.py", line 98, in main_wrapper
    return app.run(main=g_main, argv=args)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/googletest.py", line 69, in g_main
    return unittest_main(argv=argv)
  File "/usr/lib/python2.7/unittest/main.py", line 95, in __init__
    self.runTests()
  File "/usr/lib/python2.7/unittest/main.py", line 232, in runTests
    self.result = testRunner.run(self.test)
  File "/usr/lib/python2.7/unittest/runner.py", line 151, in run
    test(result)
  File "/usr/lib/python2.7/unittest/suite.py", line 70, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python2.7/unittest/suite.py", line 108, in run
    test(result)
  File "/usr/lib/python2.7/unittest/suite.py", line 70, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python2.7/unittest/suite.py", line 108, in run
    test(result)
  File "/usr/lib/python2.7/unittest/case.py", line 393, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "gmm_ops_test.py", line 143, in testParams
    [[3.0, 3.0], [0.0, 0.0]], 'w')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/factorization/python/ops/gmm_ops.py", line 154, in __init__
    self._define_graph(data)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/factorization/python/ops/gmm_ops.py", line 274, in _define_graph
    self._define_log_prob_operation(shard_id, shard)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/factorization/python/ops/gmm_ops.py", line 338, in _define_log_prob_operation
    self._define_full_covariance_probs(shard_id, shard)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/factorization/python/ops/gmm_ops.py", line 290, in _define_full_covariance_probs
    diff = shard - self._means
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/math_ops.py", line 894, in binary_op_wrapper
    return func(x, y, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_math_ops.py", line 4636, in _sub
    "Sub", x=x, y=y, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Incompatible shapes: [1,1000,2] vs. [0]
	 [[Node: sub_2 = Sub[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](ExpandDims_2, clusters/read)]]


======================================================================
ERROR: test_simple_cluster (__main__.GmmOpsTest)
Tests that the clusters are correct.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "gmm_ops_test.py", line 125, in test_simple_cluster
    random_seed=self.seed)
ValueError: too many values to unpack

----------------------------------------------------------------------
Ran 4 tests in 0.992s

FAILED (errors=2`
```

**Comment by tensorflowbutler** [comment]
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by xavigonzalvo** [comment]
This is part of tensorflow's [bazel](https://www.tensorflow.org/install/install_sources) packages. So this is supposed to be run like this:

    cd tensorflow/tensorflow/contrib/factorization
    bazel test :gmm_ops_test :gmm_test

or just do:

    bazel test tensorflow/contrib/factorization:all

for all packages related to factorization (i.e. kmeans and gmm so far).

**Comment by tensorflowbutler** [comment]
Nagging Assignee @agarwal-ashish: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by agarwal-ashish** [comment]
Closing as per comment from @xavigonzalvo
