### ISSUE TITLE
concurrent.futures for Python 2 installed with tensorflow-gpu with pip3 

### ISSUE THREAD

**Issue by thiell** [tensorflow/tensorflow#16850]
We noticed an issue with the tensorflow-gpu package available in pip for Python 3: it leads to `concurrent.futures` for Python 2 being installed as a dependency.

```
$ jupyter-notebook --no-browser
Traceback (most recent call last):
  File "/share/software/user/open/py-jupyter/1.0.0_py36/bin/jupyter-notebook", line 7, in <module>
    from notebook.notebookapp import main
  File "/share/software/user/open/py-jupyter/1.0.0_py36/lib/python3.6/site-packages/notebook/notebookapp.py", line 35, in <module>
    from jinja2 import Environment, FileSystemLoader
  File "/share/software/user/open/py-jupyter/1.0.0_py36/lib/python3.6/site-packages/jinja2/__init__.py", line 81, in <module>
    _patch_async()
  File "/share/software/user/open/py-jupyter/1.0.0_py36/lib/python3.6/site-packages/jinja2/__init__.py", line 77, in _patch_async
    from jinja2.asyncsupport import patch_all
  File "/share/software/user/open/py-jupyter/1.0.0_py36/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 13, in <module>
    import asyncio
  File "/share/software/user/open/python/3.6.1/lib/python3.6/asyncio/__init__.py", line 21, in <module>
    from .base_events import *
  File "/share/software/user/open/python/3.6.1/lib/python3.6/asyncio/base_events.py", line 17, in <module>
    import concurrent.futures
  File "/share/software/user/open/py-tensorflow/1.5.0_py36/lib/python3.6/site-packages/concurrent/futures/__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
  File "/share/software/user/open/py-tensorflow/1.5.0_py36/lib/python3.6/site-packages/concurrent/futures/_base.py", line 381
    raise exception_type, self._exception, self._traceback
                        ^
SyntaxError: invalid syntax
```

The workaround is to remove concurrent.futures as it is already included in Python 3 standard library.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by thiell** [comment]
Have I written custom code: no
OS Platform and Distribution: Linux CentOS 7.4
TensorFlow installed from: pip
TensorFlow version: tensorflow-gpu 1.5.0
Bazel version: N/A
CUDA/cuDNN version: 9/7
GPU model and memory: Not relevant here, it's a packaging issue
Exact command to reproduce: already provided

**Comment by martinwicke** [comment]
@yifeif do you recall what we did for unittest (and enum), which has a similar problem? A module needed for py2, but not as a dependency for py3?

**Comment by yifeif** [comment]
I don't think we have `concurrent` as one of our dependencies. Could it be from another package @thiell?

**Comment by martinwicke** [comment]
But we are using it in `grpc_debug_server.py`, so maybe we should have a dependency?

**Comment by thiell** [comment]
The dependency only makes sense for Python 2 as `concurrent.futures` has been added to Python 3's standard library (see https://docs.python.org/3/library/concurrent.futures.html and https://www.python.org/dev/peps/pep-3148/).

**Comment by yifeif** [comment]
We don't have concurrent explicitly listed out in our dependencies (see https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/pip_package/setup.py). @caisq do you think we need to add it for `grpc_debug_server.py`?

Curious how `concurrent` got installed here. I saw grpcio has dependency on `future`, but not `concurrent`.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @martinwicke: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by martinwicke** [comment]
@caisq assigning to you -- please reassign when you answer.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @caisq: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @caisq: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @caisq: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @caisq: It has been 16 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by thiell** [comment]
Still no fix?

**Comment by tensorflowbutler** [comment]
Nagging Assignee @caisq: It has been 16 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @caisq: It has been 31 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @caisq: It has been 46 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @caisq: It has been 61 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @caisq: It has been 76 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @caisq: It has been 91 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @caisq: It has been 106 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @caisq: It has been 121 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @caisq: It has been 136 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @caisq: It has been 151 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @caisq: It has been 166 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @caisq: It has been 181 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @caisq: It has been 196 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by mohantym** [comment]
Hi @thiell ! I am not getting any issue while running "jupyter notebook --no-browser" with 2.8 GPU and python 3.8 . Can this issue be closed now?

**Comment by thiell** [comment]
Please feel free to close, this is an old issue. Thanks!
