### ISSUE TITLE
Building TensorFlow v1.5.0 from sources does not detect bazel v0.10.0 correctly

### ISSUE THREAD

**Issue by dmak** [tensorflow/tensorflow#16893]
It looks like build script uses strings for version comparison, i.e. tuple `("0", "10", "0") < ("0", "4", "5")`, hence Bazel version 0.10.0 is considered less then required version 0.4.5:
```
user@server:~/tensorflow-1.5.0$ bazel build --config opt //tensorflow/java:tensorflow //tensorflow/java:libtensorflow_jni
ERROR: /home/user/tensorflow-1.5.0/WORKSPACE:15:1: Traceback (most recent call last):
        File "/home/user/tensorflow-1.5.0/WORKSPACE", line 15
                closure_repositories()
        File "/home/user/.cache/bazel/_bazel_user/999dc7eb04d16a3dd0103e4cb7e7e45c/external/io_bazel_rules_closure/closure/repositories.bzl", line 69, in closure_repositories
                _check_bazel_version("Closure Rules", "0.4.5")
        File "/home/user/.cache/bazel/_bazel_user/999dc7eb04d16a3dd0103e4cb7e7e45c/external/io_bazel_rules_closure/closure/repositories.bzl", line 172, in _check_bazel_version
                fail(("%s requires Bazel >=%s but was...)))
Closure Rules requires Bazel >=0.4.5 but was 0.10.0- (@non-git)
```
OS Platform and Distribution: SuSE Linux 12.3
TensorFlow installed from: [this source](https://github.com/tensorflow/tensorflow/archive/v1.5.0.zip)
TensorFlow version: 1.5.0
Bazel version: 0.10.0, compiled from [this source](https://github.com/bazelbuild/bazel/releases/download/0.10.0/bazel-0.10.0-dist.zip)
CUDA/cuDNN version: N/A / was not enabled
GPU model and memory: N/A / was not enabled
Exact command to reproduce: `bazel build --config opt //tensorflow/java:tensorflow //tensorflow/java:libtensorflow_jni`

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by dmak** [comment]
Most of the information is visible from the log, however I've updated the ticket to make it complete.

**Comment by bignamehyp** [comment]
Thanks for the feedback. Please sync to the latest build script. We fixed this issue.

**Comment by tensorflowbutler** [comment]
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by dmak** [comment]
I confirm that Tensorflow from master now builds OK with Bazel v0.10.0.
