### ISSUE TITLE
tensorflow 1.3,1.4,1.5,1.6 DLL load failed with CUDA 9.1, CUDnn-7.05, Windows 10

### ISSUE THREAD

**Issue by apiszcz** [tensorflow/tensorflow#16939]
import tensorflow strack trace

```
> py lib\_learn\tensorflow\versions\versiontest.py
Traceback (most recent call last):
  File "lib/tensorflow_gpu_130\tensorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\g\TEST\lib\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 577, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 914, in create_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lib/tensorflow_gpu_130\tensorflow\python\pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "lib/tensorflow_gpu_130\tensorflow\python\pywrap_tensorflow_internal.py", line 21, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "lib/tensorflow_gpu_130\tensorflow\python\pywrap_tensorflow_internal.py", line 20, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow_internal')
  File "C:\g\TEST\lib\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lib\_learn\tensorflow\versions\versiontest.py", line 4, in <module>
    import tensorflow as tf
  File "lib/tensorflow_gpu_130\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "lib/tensorflow_gpu_130\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "lib/tensorflow_gpu_130\tensorflow\python\pywrap_tensorflow.py", line 52, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "lib/tensorflow_gpu_130\tensorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\g\TEST\lib\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 577, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 914, in create_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lib/tensorflow_gpu_130\tensorflow\python\pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "lib/tensorflow_gpu_130\tensorflow\python\pywrap_tensorflow_internal.py", line 21, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "lib/tensorflow_gpu_130\tensorflow\python\pywrap_tensorflow_internal.py", line 20, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow_internal')
  File "C:\g\TEST\lib\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: No module named '_pywrap_tensorflow_internal'


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by apiszcz** [comment]
OS Platform and Distribution: Windows 10
TensorFlow installed from: .whl files from : https://pypi.python.org/
TensorFlow version: 1.4,1.5,1.6
Bazel version: UNKNOWN
CUDA/cuDNN version: 9.1, 7.05
GPU model and memory: NVIDIA, QUADRO, K5100M
Exact command to reproduce: import tensorflow

**Comment by apiszcz** [comment]
With version <1.3.0 I was able to load using the following

sys.path.insert(0, r'lib\tensorflow_gpu_130')
sys.path.append('lib')
os.environ['PATH']=r'lib\tensorflow_gpu_130;'+os.environ['PATH']
import tensorflow as tf
print(tf.__version__)

Version 1.3.0 and later this scheme no longer works, the approach to find the mname value in pywrap_tensorflow_internal.py appears to be the same, Reviewing now.

**Comment by gunan** [comment]
v1.3 and 1.4 prebuilt binaries work with buda 8, and 1.5 and 1.6 binaries work with cuda 9.0.
To make any of these releases work with cuda 9.1, you need to build from sources.
Therefore, this is working as expected.

**Comment by gunan** [comment]
You need to set this to 9.1:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/cmake/CMakeLists.txt#L40

You can do it through the command line by `-Dtensorflow_CUDA_VERSION=9.1`

**Comment by apiszcz** [comment]
Thank you, that made it past that error, I am testing or trying to use
Microsoft Visual Studio 2017 Community.

-- Found CUDA: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.1
(found suitable exact version "9.1")
CMake Error at CMakeLists.txt:322 (message):
  Selected compiler (or version) is not supported for CUDA

**Comment by gunan** [comment]
https://devtalk.nvidia.com/default/topic/1027299/cuda-setup-and-installation/cuda-9-failed-to-support-the-latest-visual-studio-2017-version-15-5/

Looks like cuda still does not work with visual studio 2017?

**Comment by apiszcz** [comment]
http://docs.nvidia.com/cuda/cuda-installation-guide-microsoft-windows/index.html
