### ISSUE TITLE
[Android Studio + TensorFlow] Error with some Kernel's Operations

### ISSUE THREAD

**Issue by gabrielrlp** [tensorflow/tensorflow#17013]
### System information
- **Have I written custom code**: Yes
- **OS Platform and Distribution**: Linux Ubuntu 16.04
- **TensorFlow installed from**: Source
- **TensorFlow version (use command below)**: 1.5.0
- **Python version**: 2.7.12
- **Bazel version**: 0.10.0
- **GCC/Compiler version (if compiling from source)**: 5.4.0
- **GPU model and memory**: GTX 1050 TI 256MB
- **Exact command to reproduce**: Build on Android Studio

## Describe the problem
Hello guys,

My team and I are attempting to import and use a specific model on Android Studio. This functionality is pretty easy, we feed this model with an image in bitmap format and we receive a matrix points with results.
But on **Run** step this model shows different errors according to **libtensorflow_inference.so**.

I create an image to better explain my problem to you. See below:
![issue](https://user-images.githubusercontent.com/29979626/36210004-7405189e-1184-11e8-80b4-1f77044c100a.png)

### Initially, I want to load my model:
```
public static Detector testCreate(AssetManager assetManager, String modelFileName, String labelFileName, int inputWidth, int inputHeight, int inputDepth, String inputName, String outputName) throws IOException {

	TensorFlowImageDetector d = new TensorFlowImageDetector();
        d.inputName = inputName;
        d.outputName = outputName;
        d.inferenceInterface = new TensorFlowInferenceInterface(assetManager, modelFileName);

        d.inputWidth = inputWidth;
        d.inputHeight = inputHeight;
        d.inputDepth = inputDepth;

        d.outputNames = new String[]{outputName};
        // start outputs
        // fix labelfilename != null

        return d;
}
```

### Before I need to detect element on image (feed, run and fetch):
```
public Detection testDetectImage(final float[] pixels) {

        // Log this method so that it can be analyzed with systrace.
        TraceCompat.beginSection("detectImage");

        // Copy the input data into TensorFlow.
        TraceCompat.beginSection("feed");
        inferenceInterface.feed(inputName, pixels, 1, inputWidth, inputHeight, inputDepth);
        TraceCompat.endSection();

        // Run the inference call.
        TraceCompat.beginSection("run");
        inferenceInterface.run(outputNames, Boolean.parseBoolean(null));
        TraceCompat.endSection();

        // Copy the output Tensor back into the output array.
        TraceCompat.beginSection("fetch");
        //inferenceInterface.fetch(outputName, outputs);
        TraceCompat.endSection();

        return null;
}
```
### Comments
1. Errors occurring on **Run** function
2. We already tried to solve the problem with 3 different ways mentioned in the image
3. My model has an input size of 1x256x256x3 and for test, I'm using a matrix of zeros
4. To generate a custom library we used this tutorial: https://medium.com/@daj/how-to-shrink-the-tensorflow-android-inference-library-cb698facf758
5. To generate a full library of Android, on Bazel, we used `--copt=-D__ANDROID_TYPES_FULL__` flag
6. We used JAR created by Bazel when generated custom libraries

### Logs for errors
>**Op Sin**
```
02-14 13:23:08.584 8090-8090/? E/art: No implementation found for long org.tensorflow.contrib.android.RunStats.allocate() (tried Java_org_tensorflow_contrib_android_RunStats_allocate and Java_org_tensorflow_contrib_android_RunStats_allocate__)
02-14 13:23:08.584 8090-8090/? I/TensorFlowInferenceInterface: TensorFlow native methods not found, attempting to load via tensorflow_inference
02-14 13:23:08.685 8090-8090/? I/TensorFlowInferenceInterface: Successfully loaded TensorFlow native methods (RunStats error may be ignored)
02-14 13:23:11.083 8090-8090/com.example.lis.zitronenkuchen I/TensorFlowInferenceInterface: Model load took 518ms, TensorFlow version: 1.6.0-rc0
02-14 13:23:11.092 8090-8090/com.example.lis.zitronenkuchen I/TensorFlowInferenceInterface: Successfully loaded model from 'file:///android_asset/frozen_pose3d.pb'
02-14 13:23:11.092 8090-8090/com.example.lis.zitronenkuchen D/MainActivity: Load Success!
02-14 13:23:11.215 8090-8090/com.example.lis.zitronenkuchen E/TensorFlowInferenceInterface: Failed to run TensorFlow inference with inputs:[input_image], outputs:[MatMul]
02-14 13:23:11.216 8090-8090/com.example.lis.zitronenkuchen D/AndroidRuntime: Shutting down VM
02-14 13:23:11.217 8090-8090/com.example.lis.zitronenkuchen E/AndroidRuntime: FATAL EXCEPTION: main
                                                                              Process: com.example.lis.zitronenkuchen, PID: 8090
                                                                              java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.lis.zitronenkuchen/com.example.lis.zitronenkuchen.MainActivity}: java.lang.RuntimeException: Error initializing TensorFlow!
                                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2659)
                                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2724)
                                                                                  at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                  at android.os.Looper.loop(Looper.java:154)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:6123)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
                                                                               Caused by: java.lang.RuntimeException: Error initializing TensorFlow!
                                                                                  at com.example.lis.zitronenkuchen.MainActivity.onCreate(MainActivity.java:44)
                                                                                  at android.app.Activity.performCreate(Activity.java:6672)
                                                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1140)
                                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2612)
                                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2724) 
                                                                                  at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473) 
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                  at android.os.Looper.loop(Looper.java:154) 
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:6123) 
                                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867) 
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757) 
                                                                               Caused by: java.lang.IllegalArgumentException: No OpKernel was registered to support Op 'Sin' with these attrs.  Registered devices: [CPU], Registered kernels:
                                                                                <no registered kernels>
                                                                              
                                                                              	 [[Node: ViewpointNet/get_rot_mat/Sin = Sin[T=DT_FLOAT](ViewpointNet/get_rot_mat/Sqrt)]]
                                                                                  at org.tensorflow.Session.run(Native Method)
                                                                                  at org.tensorflow.Session.access$100(Session.java:48)
                                                                                  at org.tensorflow.Session$Runner.runHelper(Session.java:298)
                                                                                  at org.tensorflow.Session$Runner.run(Session.java:248)
                                                                                  at org.tensorflow.contrib.android.TensorFlowInferenceInterface.run(TensorFlowInferenceInterface.java:230)
                                                                                  at org.tensorflow.contrib.android.TensorFlowInferenceInterface.run(TensorFlowInferenceInterface.java:197)
                                                                                  at org.tensorflow.contrib.android.TensorFlowInferenceInterface.run(TensorFlowInferenceInterface.java:187)
                                                                                  at com.example.lis.zitronenkuchen.TensorFlowImageDetector.detectImage(TensorFlowImageDetector.java:73)
                                                                                  at com.example.lis.zitronenkuchen.MainActivity.onCreate(MainActivity.java:41)
                                                                                  	... 12 more
```

>**Op Identity**
```
E/art: No implementation found for long org.tensorflow.contrib.android.RunStats.allocate() (tried Java_org_tensorflow_contrib_android_RunStats_allocate and Java_org_tensorflow_contrib_android_RunStats_allocate__)
I/TensorFlowInferenceInterface: TensorFlow native methods not found, attempting to load via tensorflow_inference
I/TensorFlowInferenceInterface: Successfully loaded TensorFlow native methods (RunStats error may be ignored)
D/AndroidRuntime: Shutting down VM


                  --------- beginning of crash
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.example.lis.zitronenkuchen, PID: 6521
                  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.lis.zitronenkuchen/com.example.lis.zitronenkuchen.MainActivity}: java.lang.RuntimeException: Error initializing TensorFlow!
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2659)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2724)
                      at android.app.ActivityThread.-wrap12(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6123)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
                   Caused by: java.lang.RuntimeException: Error initializing TensorFlow!
                      at com.example.lis.zitronenkuchen.MainActivity.onCreate(MainActivity.java:44)
                      at android.app.Activity.performCreate(Activity.java:6672)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1140)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2612)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2724) 
                      at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:154) 
                      at android.app.ActivityThread.main(ActivityThread.java:6123) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757) 
                   Caused by: org.tensorflow.TensorFlowException: Op type not registered 'Identity' in binary running on localhost. Make sure the Op and Kernel are registered in the binary running in this process.
                      at org.tensorflow.Graph.importGraphDef(Native Method)
                      at org.tensorflow.Graph.importGraphDef(Graph.java:130)
                      at org.tensorflow.Graph.importGraphDef(Graph.java:114)
                      at org.tensorflow.contrib.android.TensorFlowInferenceInterface.loadGraph(TensorFlowInferenceInterface.java:561)
                      at org.tensorflow.contrib.android.TensorFlowInferenceInterface.<init>(TensorFlowInferenceInterface.java:105)
                      at com.example.lis.zitronenkuchen.TensorFlowImageDetector.create(TensorFlowImageDetector.java:47)
                      at com.example.lis.zitronenkuchen.MainActivity.onCreate(MainActivity.java:29)
                      at android.app.Activity.performCreate(Activity.java:6672) 
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1140) 
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2612) 
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2724) 
                      at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:154) 
                      at android.app.ActivityThread.main(ActivityThread.java:6123) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757) 
```

>**Op Switch**
```
02-14 13:09:36.334 26040-26040/com.example.lis.zitronenkuchen E/art: No implementation found for long org.tensorflow.contrib.android.RunStats.allocate() (tried Java_org_tensorflow_contrib_android_RunStats_allocate and Java_org_tensorflow_contrib_android_RunStats_allocate__)
02-14 13:09:36.334 26040-26040/com.example.lis.zitronenkuchen I/TensorFlowInferenceInterface: TensorFlow native methods not found, attempting to load via tensorflow_inference
02-14 13:09:36.406 26040-26040/com.example.lis.zitronenkuchen I/TensorFlowInferenceInterface: Successfully loaded TensorFlow native methods (RunStats error may be ignored)
02-14 13:09:37.835 26040-26040/com.example.lis.zitronenkuchen I/TensorFlowInferenceInterface: Model load took 1382ms, TensorFlow version: 1.3.1
02-14 13:09:37.843 26040-26040/com.example.lis.zitronenkuchen I/TensorFlowInferenceInterface: Successfully loaded model from 'file:///android_asset/frozen_pose3d.pb'
02-14 13:09:37.843 26040-26040/com.example.lis.zitronenkuchen D/MainActivity: Load Success!
02-14 13:09:37.892 26040-26040/com.example.lis.zitronenkuchen E/TensorFlowInferenceInterface: Failed to run TensorFlow inference with inputs:[input_image], outputs:[MatMul]
02-14 13:09:37.892 26040-26040/com.example.lis.zitronenkuchen D/AndroidRuntime: Shutting down VM
02-14 13:09:37.893 26040-26040/com.example.lis.zitronenkuchen E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                Process: com.example.lis.zitronenkuchen, PID: 26040
                                                                                java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.lis.zitronenkuchen/com.example.lis.zitronenkuchen.MainActivity}: java.lang.RuntimeException: Error initializing TensorFlow!
                                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2426)
                                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490)
                                                                                    at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                    at android.os.Looper.loop(Looper.java:148)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
                                                                                 Caused by: java.lang.RuntimeException: Error initializing TensorFlow!
                                                                                    at com.example.lis.zitronenkuchen.MainActivity.onCreate(MainActivity.java:44)
                                                                                    at android.app.Activity.performCreate(Activity.java:6245)
                                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1130)
                                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
                                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490) 
                                                                                    at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354) 
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                    at android.os.Looper.loop(Looper.java:148) 
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5443) 
                                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728) 
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618) 
                                                                                 Caused by: java.lang.IllegalArgumentException: No OpKernel was registered to support Op 'Switch' with these attrs.  Registered devices: [CPU], Registered kernels:
                                                                                  device='GPU'; T in [DT_STRING]
                                                                                  device='GPU'; T in [DT_BOOL]
                                                                                  device='GPU'; T in [DT_INT32]
                                                                                  device='GPU'; T in [DT_INT64]
                                                                                  device='GPU'; T in [DT_FLOAT]
                                                                                  device='GPU'; T in [DT_HALF]
                                                                                  device='CPU'; T in [DT_QINT32]
                                                                                  device='CPU'; T in [DT_QUINT8]
                                                                                  device='CPU'; T in [DT_QINT8]
                                                                                  device='CPU'; T in [DT_FLOAT]
                                                                                  device='CPU'; T in [DT_HALF]
                                                                                  device='CPU'; T in [DT_INT32]
                                                                                  device='CPU'; T in [DT_INT64]
                                                                                
                                                                                	 [[Node: PosePrior/dropout/cond/Switch = Switch[T=DT_BOOL](PlaceholderWithDefault, PlaceholderWithDefault)]]
                                                                                    at org.tensorflow.Session.run(Native Method)
                                                                                    at org.tensorflow.Session.access$100(Session.java:48)
                                                                                    at org.tensorflow.Session$Runner.runHelper(Session.java:295)
                                                                                    at org.tensorflow.Session$Runner.run(Session.java:245)
                                                                                    at org.tensorflow.contrib.android.TensorFlowInferenceInterface.run(TensorFlowInferenceInterface.java:143)
                                                                                    at com.example.lis.zitronenkuchen.TensorFlowImageDetector.detectImage(TensorFlowImageDetector.java:73)
                                                                                    at com.example.lis.zitronenkuchen.MainActivity.onCreate(MainActivity.java:41)
                                                                                    	... 12 more
```

Thank you! :grin:

**Comment by gabrielrlp** [comment]
@daj can you help me?

**Comment by LuisFernandoBecker** [comment]
:+1:

**Comment by bernardo-felipetto** [comment]
I'm having a similar problem, I was getting the " No OpKernel was registered to support Op 'ArgMax' with these attrs." error when i tried to run after generating my custom .so

**Comment by gabrielrlp** [comment]
@daj Thanks for the,

However I did it. I has check `ops_to_register.h` file and it contained `Identity` function. 

So after I rebuilt it and load on Android Studio that error happened: 
`org.tensorflow.TensorFlowException: Op type not registered 'Identity' in binary running on localhost. Make sure the Op and Kernel are registered in the binary running in this process.`

Is there any other error that I could have made or probably the error is in the `libtensorflow_inference.so` build?

**Comment by gabrielrlp** [comment]
What I mean is that it looks like my code in Android Studio is not loading my library. Because I believe I have done everything the right way. I use the library that I created but it does not recognize the function inside it.

**Comment by daj** [comment]
What kind of device/emulator are you using?  Did you build the correct architecture for your device using the `--cpu` option?  Most real devices will need to use an `armeabi-v7a`, whereas most emulators will need `x86`.  

Since you are getting different error messages each time, that suggests that you are succeeding in replacing the default library with your own one.  You could try using the Android Studio `Profile or Debug APK` option to check the correct versions of the libraries are inside the APK in the correct folders.

Were you able to get the example from my blog to work?  I suggest starting from a working project and making minor changes until you get close enough to your final destination.

**Comment by gabrielrlp** [comment]
I am using `armeabi-v7a` for real device and `x86_64` for emulated device. But I created the library for both of them. Yes, I repeated every step for each one with the correct flag `--cpu=armeabi-v7a` and `--cpu=x86_64`.

[On your blog](https://medium.com/@daj/how-to-shrink-the-tensorflow-android-inference-library-cb698facf758),

> Copy your new `libtensorflow_inference.so` file into your project, putting it in the correct folder for the architecture that you built, e.g. `app/src/main/jniLibs/armeabi-v7a/`.

In my case: `jniLibs/armeabi-v7a` and `jniLibs/x86_64`

Yeah, We have already use a lot of debug :smile:

I think the only thing I did not try was to download your project and test it.

**Comment by gabrielrlp** [comment]
I believe I need to mention that the only part that I was in doubt was in this part

> Extract the Java classes.jar from the `org.tensorflow:tensorflow-android` dependency. Copy them into your `app/libs` folder, and update your `build.gradle` file.

I don't understood how to _extract the Java classes.jar from the org.tensorflow:tensorflow-android dependency_.

But after searching I found that it was possible to generate a JAR file based on my project, using the Bazel.

**Comment by daj** [comment]
> I don't understood how to extract the Java classes.jar from the org.tensorflow:tensorflow-android dependency.

You can probably just take my `app/libs/tensorflow-android.jar` from this commit:
https://github.com/daj/AndroidTensorFlowMNISTExample/commit/6e1b15ff6d3182be0e665c0456f356ffc2f62514

**Comment by jspark-cochlearai** [comment]
I am suffering from the same problem. I want to replace the model in the tensorflow for android demo app (https://github.com/tensorflow/tensorflow) with my custom model but I never succeeded. Below are what I have tried so far:

1. I replaced the `.pb` file and its corresponding labels. But it showed runtime error something like
`No OpKernel was registered to support Op 'ListDiff'`
This is because my model requires some additional tensorflow operations like `ListDiff` which are not included in `org.tensorflow:tensorflow-android`.

2. I followed the instructions that I found by googling most of which mention rebuilding `libtensorflow_inference.so` with this command:
`bazel build -c opt --copt="-DSELECTIVE_REGISTRATION" --copt="-DSUPPORT_SELECTIVE_REGISTRATION" //tensorflow/contrib/android:libtensorflow_inference.so     --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --crosstool_top=//external:android/crosstool --cpu=armeabi-v7a --verbose_failures`
After that I copied `libtensorflow_inference.so` to the `libs/armeabi-v7a` folder under my android example folder. 
But it also failed.

3. I tried a number of options when building the `libtensorflow_inference.so` (like removing selective registration) and it failed. Supporting selective registration affected the file size of `libtensorflow_inference.so` from 13.7MB to 3.4MB but it seems that the operations used in my `.pb` file like `ListDiff` are excluded in the both cases.

4. What is more interesting is that `ops_to_register.h` was properly generated. The `ListDiff` operation was included in the `ops_to_register.h`. Besides, when I tried to build the `libtensorflow_inference.so` without `ops_to_register.h` it gave an error as
`./tensorflow/core/framework/selective_registration.h:46:10: fatal error: 'ops_to_register.h' file not found`
But when I examined the `libtensorflow_inference.so` file with `nm -D libtensorflow_inference.so` command, I could not find the `ListDiff` operation in it.

5. To avoid collisions of any kind, I commented out
`compile 'org.tensorflow:tensorflow-android:+'`
and inserted
`compile fileTree(dir: 'libs', include: ['*.jar', '**/*.so'])`
but it did not solve the problem.

6. I compressed the `.so` file after I put it into `lib` folder and changed the file extension from `zip` to `.jar`, but it did not help.
I guess this is because the operations are already missing in the `.so` file.

7. As my phone uses 64-bit CPU, I changed `armeabi-v7a` to `arm64-v8a` when building the native library. However, it did notwork.
(This failure was expected in advance actually because `arm64-v8a` systems are compatible with `armeabi-v7a` libraries.)

8. I added to import tensorflow inference to the `.java` file but it did not work.


I am using android ndk r14b  and sdk 26.0.1 (and 27.0.3) in Mac OS X and ubuntu 16.04.
Does anyone have a solution?

**Comment by gabrielrlp** [comment]
@jspark-cochlearai We tried everything you said. Unsuccessfully.

**Comment by JcmeLs** [comment]
@gabrielrlp maybe you can check /tensorflow/contrib/makefile/tf_op_files.txt

**Comment by tensorflowbutler** [comment]
It has been 30 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
We are closing this issue for now due to lack of activity. Please comment if this is still an issue for you. Thanks!

**Comment by StevenBanama** [comment]
you can add list_diff_op.cc to android_extended_ops_group1 in "tensorflow/core/kernels/BUILD" or update tensorflow to latest version (over 1.8).
