### ISSUE TITLE
Saving the model throws "op_kernel.cc" No such file or directory error

### ISSUE THREAD

**Issue by tastyminerals** [tensorflow/tensorflow#17041]
```
Epoch: 50 Train Perplexity: 37.819
Epoch: 50 Valid Perplexity: 60.281
Test Perplexity: 44.138
Saving model to output.
2018-02-15 14:05:42.473937: W tensorflow/core/framework/op_kernel.cc:1198] Not found: ; No such file or directory
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _do_call
    return fn(*args)
  File "/usr/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1329, in _run_fn
    status, run_metadata)
  File "/usr/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: ; No such file or directory
	 [[Node: save_1/SaveV2 = SaveV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT64, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save_1/Const_0_0, save_1/SaveV2/tensor_names, save_1/SaveV2/shape_and_slices, Model/Model/RNN/multi_rnn_cell/cell_0/lstm_cell/bias/Adam/_109, Model/Model/RNN/multi_rnn_cell/cell_0/lstm_cell/bias/Adam_1/_111, Model/Model/RNN/multi_rnn_cell/cell_0/lstm_cell/kernel/Adam/_113, Model/Model/RNN/multi_rnn_cell/cell_0/lstm_cell/kernel/Adam_1/_115, Model/Model/embedding/Adam/_117, Model/Model/embedding/Adam_1/_119, Model/Model/softmax_b/Adam/_121, Model/Model/softmax_b/Adam_1/_123, Model/Model/softmax_w/Adam/_125, Model/Model/softmax_w/Adam_1/_127, Model/RNN/multi_rnn_cell/cell_0/lstm_cell/bias/_129, Model/RNN/multi_rnn_cell/cell_0/lstm_cell/kernel/_131, Model/embedding/_133, Model/global_step, Model/softmax_b/_135, Model/softmax_w/_137, Train/Model/Variable/_139, Train/Model/beta1_power/_141, Train/Model/beta2_power/_143)]]
```
### System information
- **Have I written custom code**: [PTB model](https://github.com/tensorflow/models/blob/master/tutorials/rnn/ptb/ptb_word_lm.py) from official RNN tutorial (using custom data and hyperparams slightly modified)
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  Linux 4.14.16-1 Manjaro
- **TensorFlow installed from**: pip
- **TensorFlow version**: 1.5.0
- **Python version**: 3.6 
- **Bazel version (if compiling from source)**: -
- **GCC/Compiler version (if compiling from source)**: -
- **CUDA/cuDNN version**: 9.0
- **GPU model and memory**: NVIDIA GTX 1070 Mobile (8GB, driver 384.111)
- **Exact command to reproduce**: just running the training file `main.py` with default FLAG params

### Describe the problem
Training goes fine and I can observe loss decreasing. I can also run Tensorboard on the log dir and see the model graph. When the max_epoch is reached the code throws the above mentioned error.

### Source code / logs
--

**Comment by bignamehyp** [comment]
Check checkpoint dir path is provided?

**Comment by tastyminerals** [comment]
Yes, that was the issue. Thank you.
