### ISSUE TITLE
Flag names no longer compatible with argparse

### ISSUE THREAD

**Issue by naktinis** [tensorflow/tensorflow#17132]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 17.10
- **TensorFlow installed from (source or binary)**:
- **TensorFlow version (use command below)**: v1.5.0-0-g37aa430d84 1.5.0
- **Python version**: 3.6.3
- **Exact command to reproduce**:

```
import tensorflow as tf
tf.app.flags.DEFINE_string(
    name='flag-name',
    default=None,
    help='Flag description.'
)
print(tf.app.flags.FLAGS.flag_name)
```

### Describe the problem
Up to version 1.4.1 you would be able to access the flag defined as "flag-name" via `FLAGS.flag_name` just like in [argparse](https://docs.python.org/3/library/argparse.html). Since 1.5.0 this functionality is no longer available.

### Source code / logs
Here's the traceback:
```
Traceback (most recent call last):
  File "flagtest.py", line 15, in <module>
    print(tf.app.flags.FLAGS.flag_name)
  File "/code/venv3/lib/python3.6/site-packages/tensorflow/python/platform/flags.py", line 85, in __getattr__
    return wrapped.__getattr__(name)
  File "/code/venv3/lib/python3.6/site-packages/absl/flags/_flagvalues.py", line 470, in __getattr__
    raise AttributeError(name)
AttributeError: flag_name
```

Since up to version 1.4.1 this was the default functionality, bringing this back should not affect many projects.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Bazel version
CUDA/cuDNN version
GPU model and memory

**Comment by tensorflowbutler** [comment]
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by pooyan1983** [comment]
I am getting the same error on Windows10 when running model_test.py in deeplab model
Tensorflow 1.6
CUDA version 9.0      cudnn64_7.dll
GPU GeForce GTX 1070

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
We are closing this issue for now due to lack of activity. Please comment if this is still an issue for you. Thanks!
