### ISSUE TITLE
LookupError: gradient registry has no entry for: Svd

### ISSUE THREAD

**Issue by nbansal90** [tensorflow/tensorflow#17156]
Hello All,

I am using singular values of the weights at each convolution layer as a regularizer and adding it in kernel_regularizer=self.l2_reg(). Where l2_reg is the function which return that.
```

        def l2_reg(weights):
                """ Reshaping the matrxi in to 2D tensor for enforcing orthogonality"""
                w = tf.identity(weights)

                """Calculating the Loss Obtained"""
                s1 = tf.linalg.svd(reg, full_matrices=True,compute_uv=False)
                ortho_loss = tf.nn.l2_loss(s1)
                return ortho_loss
```
Error I am getting is:
```
raceback (most recent call last):
  File "/usr/local/keras-python3/lib/python3.5/site-packages/tensorflow/python/ops/gradients_impl.py", line 551, in gradients
    grad_fn = ops.get_gradient_function(op)
  File "/usr/local/keras-python3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2134, in get_gradient_function
    return _gradient_registry.lookup(op_type)
  File "/usr/local/keras-python3/lib/python3.5/site-packages/tensorflow/python/framework/registry.py", line 93, in lookup
    "%s registry has no entry for: %s" % (self._name, name))
LookupError: gradient registry has no entry for: Svd

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_dense_net.py", line 142, in <module>
    model = DenseNet(data_provider=data_provider, **model_params)
  File "/home/bansa01/densenet_final/tmp_spectral/models/dense_net.py", line 85, in __init__
    self._build_graph()
  File "/home/bansa01/densenet_final/tmp_spectral/models/dense_net.py", line 461, in _build_graph
    cross_entropy + l2_loss_total + reg_loss_total)
  File "/usr/local/keras-python3/lib/python3.5/site-packages/tensorflow/python/training/optimizer.py", line 343, in minimize
    grad_loss=grad_loss)
  File "/usr/local/keras-python3/lib/python3.5/site-packages/tensorflow/python/training/optimizer.py", line 414, in compute_gradients
    colocate_gradients_with_ops=colocate_gradients_with_ops)
  File "/usr/local/keras-python3/lib/python3.5/site-packages/tensorflow/python/ops/gradients_impl.py", line 555, in gradients
    (op.name, op.type))
LookupError: No gradient defined for operation 'Initial_convolution/conv2d/kernel/Regularizer/Svd' (op type: Svd)
```
I Understand that this is due to not able to calculate the gradient for SVD operation, but then how do I remove this issue.
Nitin

**Comment by asimshankar** [comment]
Please do provide all the information asked for in the issue template  (https://github.com/tensorflow/tensorflow/issues/new), for example which version of TensorFlow are you using?

Support for gradients of SVD was added in TensorFlow 1.5 (see https://github.com/tensorflow/tensorflow/issues/6503#issuecomment-335878473 and commit https://github.com/tensorflow/tensorflow/pull/13640/commits/e1d9e4ed05420ab9486bf18ec331e90e59e51982). Is it possible that you're using an older version?

**Comment by nbansal90** [comment]
I have been using tensorflow version 1.4.1.  I do see the commit going in. Do I just need to update my tensorflow?

**Comment by asimshankar** [comment]
Yes, can you try with version 1.5?

**Comment by tensorflowbutler** [comment]
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?
