### ISSUE TITLE
Error raised incorrectly in CheckInputFromValidContext

### ISSUE THREAD

**Issue by iganichev** [tensorflow/tensorflow#17199]
Happens in TF 1.5.

**Error message and logs:**
INFO:tensorflow:Cannot use 'transducer_training/while/rnn/strided_slice' as input to 'gradients/transducer_training/while/rnn/while/Select_1_grad/Select/f_acc' because 'transducer_training/while/rnn/strided_slice' is in a while loop.

gradients/transducer_training/while/rnn/while/Select_1_grad/Select/f_acc while context: None
transducer_training/while/rnn/strided_slice while context: transducer_training/while/while_context

Traceback for gradients/transducer_training/while/rnn/while/Select_1_grad/Select/f_acc:
  File "./loop_error.py", line 219, in <module>
    model = Model(cons_manager=constants_manager)
  File "./loop_error.py", line 44, in __init__
    self.targets, self.train_op, self.loss = self.build_training_step()
  File "./loop_error.py", line 211, in build_training_step
    train_op = tf.train.AdamOptimizer().minimize(loss)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/optimizer.py", line 355, in minimize
    grad_loss=grad_loss)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/optimizer.py", line 456, in compute_gradients
    colocate_gradients_with_ops=colocate_gradients_with_ops)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gradients_impl.py", line 609, in gradients
    grad_scope, op, func_call, lambda: grad_fn(op, *out_grads))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gradients_impl.py", line 375, in _MaybeCompile
    return grad_fn()  # Exit early
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gradients_impl.py", line 609, in <lambda>
    grad_scope, op, func_call, lambda: grad_fn(op, *out_grads))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/math_grad.py", line 949, in _SelectGrad
    return (None, array_ops.where(c, grad, zeros),
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 2540, in where
    return gen_math_ops._select(condition=condition, x=x, y=y, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_math_ops.py", line 4043, in _select
    "Select", condition=condition, t=x, e=y, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3160, in create_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1674, in __init__
    self._control_flow_context.AddOp(self)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2251, in AddOp
    self._AddOpInternal(op)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2274, in _AddOpInternal
    real_x = self.AddValue(x)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2207, in AddValue
    real_val = grad_ctxt.grad_state.GetRealValue(val)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 1050, in GetRealValue
    history_value = cur_grad_state.AddForwardAccumulator(cur_value)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 908, in AddForwardAccumulator
    name="f_acc")
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 3578, in _stack_v2
    stack_name=stack_name, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3160, in create_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1625, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

Traceback for transducer_training/while/rnn/strided_slice:
  File "./loop_error.py", line 219, in <module>
    model = Model(cons_manager=constants_manager)
  File "./loop_error.py", line 42, in __init__
    self.transducer_hidden_state_new, self.train_saver = self.build_full_transducer()
  File "./loop_error.py", line 183, in build_full_transducer
    tf.while_loop(cond, body, init_state, parallel_iterations=1)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2934, in while_loop
    result = loop_context.BuildLoop(cond, body, loop_vars, shape_invariants)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2720, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2662, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "./loop_error.py", line 119, in body
    dtype=tf.float32, initial_state=encoder_hidden_state_t)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/rnn.py", line 629, in dynamic_rnn
    dtype=dtype)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/rnn.py", line 688, in _dynamic_rnn_loop
    time_steps = input_shape[0]
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 573, in _slice_helper
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 737, in strided_slice
    shrink_axis_mask=shrink_axis_mask)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 5501, in strided_slice
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3160, in create_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1625, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

Traceback (most recent call last):
  File "./loop_error.py", line 219, in <module>
    model = Model(cons_manager=constants_manager)
  File "./loop_error.py", line 44, in __init__
    self.targets, self.train_op, self.loss = self.build_training_step()
  File "./loop_error.py", line 211, in build_training_step
    train_op = tf.train.AdamOptimizer().minimize(loss)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/optimizer.py", line 355, in minimize
    grad_loss=grad_loss)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/optimizer.py", line 456, in compute_gradients
    colocate_gradients_with_ops=colocate_gradients_with_ops)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gradients_impl.py", line 609, in gradients
    grad_scope, op, func_call, lambda: grad_fn(op, *out_grads))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gradients_impl.py", line 375, in _MaybeCompile
    return grad_fn()  # Exit early
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gradients_impl.py", line 609, in <lambda>
    grad_scope, op, func_call, lambda: grad_fn(op, *out_grads))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/math_grad.py", line 949, in _SelectGrad
    return (None, array_ops.where(c, grad, zeros),
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 2540, in where
    return gen_math_ops._select(condition=condition, x=x, y=y, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_math_ops.py", line 4043, in _select
    "Select", condition=condition, t=x, e=y, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3160, in create_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1674, in __init__
    self._control_flow_context.AddOp(self)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2251, in AddOp
    self._AddOpInternal(op)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2274, in _AddOpInternal
    real_x = self.AddValue(x)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2207, in AddValue
    real_val = grad_ctxt.grad_state.GetRealValue(val)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 1050, in GetRealValue
    history_value = cur_grad_state.AddForwardAccumulator(cur_value)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 908, in AddForwardAccumulator
    name="f_acc")
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 3578, in _stack_v2
    stack_name=stack_name, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3160, in create_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1672, in __init__
    control_flow_util.CheckInputFromValidContext(self, input_tensor.op)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_util.py", line 200, in CheckInputFromValidContext
    raise ValueError(error_msg + " See info log for more details.")
ValueError: Cannot use 'transducer_training/while/rnn/strided_slice' as input to 'gradients/transducer_training/while/rnn/while/Select_1_grad/Select/f_acc' because 'transducer_training/while/rnn/strided_slice' is in a while loop. See info log for more details.

**Code to reproduce:**

    import logging
    import tensorflow as tf
    from tensorflow.contrib.rnn import LSTMCell, LSTMStateTuple
    from tensorflow.python.layers import core as layers_core
    
    logging.getLogger().setLevel(logging.DEBUG)
    # NOTE: Time major
    
    # ---------------- Constants Manager ----------------------------
    class ConstantsManager(object):
        def __init__(self, input_dimensions, input_embedding_size, inputs_embedded, encoder_hidden_units,
                     transducer_hidden_units, vocab_ids, input_block_size, beam_width):
            assert transducer_hidden_units == encoder_hidden_units, 'Encoder and transducer have to have the same amount' \
                                                                    'of hidden units'
            self.input_dimensions = input_dimensions
            self.vocab_ids = vocab_ids
            self.E_SYMBOL = len(self.vocab_ids)
            self.vocab_ids.append('E_SYMBOL')
            self.GO_SYMBOL = len(self.vocab_ids)
            self.vocab_ids.append('GO_SYMBOL')
            self.vocab_size = len(self.vocab_ids)
            self.input_embedding_size = input_embedding_size
            self.inputs_embedded = inputs_embedded
            self.encoder_hidden_units = encoder_hidden_units
            self.transducer_hidden_units = transducer_hidden_units
            self.input_block_size = input_block_size
            self.beam_width = beam_width
            self.batch_size = 1  # Cannot be increased, see paper
            self.log_prob_init_value = 0
    
    # ----------------- Model ---------------------------------------
    
    
    class Model(object):
        def __init__(self, cons_manager):
            self.var_list = []
            self.cons_manager = cons_manager
            self.max_blocks, self.inputs_full_raw, self.transducer_list_outputs, self.start_block, self.encoder_hidden_init,\
                self.trans_hidden_init, self.logits, self.encoder_hidden_state_new, \
                self.transducer_hidden_state_new, self.train_saver = self.build_full_transducer()
    
            self.targets, self.train_op, self.loss = self.build_training_step()
    
        def build_full_transducer(self):
            with tf.variable_scope('transducer_training'):
    
                embeddings = tf.Variable(tf.random_uniform([self.cons_manager.vocab_size,
                                                            self.cons_manager.input_embedding_size], -1.0, 1.0),
                                         dtype=tf.float32,
                                         name='embedding')
                # Inputs
                max_blocks = tf.placeholder(dtype=tf.int32, name='max_blocks')  # total amount of blocks to go through
                if self.cons_manager.inputs_embedded is True:
                    input_type = tf.float32
                else:
                    input_type = tf.int32
                inputs_full_raw = tf.placeholder(shape=(None, self.cons_manager.batch_size,
                                                        self.cons_manager.input_dimensions), dtype=input_type,
                                                 name='inputs_full_raw')  # shape [max_time, 1, input_dims]
                transducer_list_outputs = tf.placeholder(shape=(None,), dtype=tf.int32,
                                                         name='transducer_list_outputs')  # amount to output per block
                start_block = tf.placeholder(dtype=tf.int32, name='transducer_start_block')  # where to start the input
    
                encoder_hidden_init = tf.placeholder(shape=(2, 1, self.cons_manager.encoder_hidden_units), dtype=tf.float32,
                                                     name='encoder_hidden_init')
                trans_hidden_init = tf.placeholder(shape=(2, 1, self.cons_manager.transducer_hidden_units), dtype=tf.float32,
                                                   name='trans_hidden_init')
    
                # Temporary constants, maybe changed during inference
                end_symbol = tf.get_variable(name='end_symbol',
                                             initializer=tf.constant_initializer(self.cons_manager.vocab_size),
                                             shape=(), dtype=tf.int32)
    
                # Turn inputs into tensor which is easily readable#
    
                inputs_full = tf.reshape(inputs_full_raw, shape=[-1, self.cons_manager.input_block_size,
                                                                 self.cons_manager.batch_size,
                                                                 self.cons_manager.input_dimensions])
    
                # Outputs
                outputs_ta = tf.TensorArray(dtype=tf.float32, size=max_blocks)
    
                init_state = (start_block, outputs_ta, encoder_hidden_init, trans_hidden_init)
    
                # Initiate cells, NOTE: if there is a future error, put these back inside the body function
                encoder_cell = tf.contrib.rnn.LSTMCell(num_units=self.cons_manager.encoder_hidden_units)
                transducer_cell = tf.contrib.rnn.LSTMCell(self.cons_manager.transducer_hidden_units)
    
                def cond(current_block, outputs_int, encoder_hidden, trans_hidden):
                    return current_block < start_block + max_blocks
    
                def body(current_block, outputs_int, encoder_hidden, trans_hidden):
    
                    # --------------------- ENCODER ----------------------------------------------------------------------
                    encoder_inputs = inputs_full[current_block]
                    encoder_inputs_length = [tf.shape(encoder_inputs)[0]]
                    encoder_hidden_state = encoder_hidden
    
                    if self.cons_manager.inputs_embedded is True:
                        encoder_inputs_embedded = encoder_inputs
                    else:
                        encoder_inputs = tf.reshape(encoder_inputs, shape=[-1, self.cons_manager.batch_size])
                        encoder_inputs_embedded = tf.nn.embedding_lookup(embeddings, encoder_inputs)
    
                    # Build model
    
                    # Build previous state
                    encoder_hidden_c, encoder_hidden_h = tf.split(encoder_hidden_state, num_or_size_splits=2, axis=0)
                    encoder_hidden_c = tf.reshape(encoder_hidden_c, shape=[-1, self.cons_manager.encoder_hidden_units])
                    encoder_hidden_h = tf.reshape(encoder_hidden_h, shape=[-1, self.cons_manager.encoder_hidden_units])
                    encoder_hidden_state_t = LSTMStateTuple(encoder_hidden_c, encoder_hidden_h)
    
                    #   encoder_outputs: [max_time, batch_size, num_units]
                    encoder_outputs, encoder_hidden_state_new = tf.nn.dynamic_rnn(
                        encoder_cell, encoder_inputs_embedded,
                        sequence_length=encoder_inputs_length, time_major=True,
                        dtype=tf.float32, initial_state=encoder_hidden_state_t)
    
                    # Modify output of encoder_hidden_state_new so that it can be fed back in again without problems.
                    encoder_hidden_state_new = tf.concat([encoder_hidden_state_new.c, encoder_hidden_state_new.h], axis=0)
                    encoder_hidden_state_new = tf.reshape(encoder_hidden_state_new,
                                                          shape=[2, -1, self.cons_manager.encoder_hidden_units])
    
                    # --------------------- TRANSDUCER --------------------------------------------------------------------
                    encoder_raw_outputs = encoder_outputs
                    # Save/load the state as one tensor, use encoder state as init if this is the first block
                    trans_hidden_state = tf.cond(current_block > 0, lambda: trans_hidden, lambda: encoder_hidden_state_new)
                    transducer_amount_outputs = transducer_list_outputs[current_block - start_block]
    
                    # Model building
                    helper = tf.contrib.seq2seq.GreedyEmbeddingHelper(
                        embedding=embeddings,
                        start_tokens=tf.tile([self.cons_manager.GO_SYMBOL],
                                             [self.cons_manager.batch_size]),  # TODO: check if this looks good
                        end_token=end_symbol)  # vocab size, so that it doesn't prematurely end the decoding
    
                    attention_states = tf.transpose(encoder_raw_outputs,
                                                    [1, 0, 2])  # attention_states: [batch_size, max_time, num_units]
    
                    attention_mechanism = tf.contrib.seq2seq.LuongAttention(
                        self.cons_manager.encoder_hidden_units, attention_states)
    
                    decoder_cell = tf.contrib.seq2seq.AttentionWrapper(
                        transducer_cell,
                        attention_mechanism,
                        attention_layer_size=self.cons_manager.transducer_hidden_units)
    
                    projection_layer = layers_core.Dense(self.cons_manager.vocab_size, use_bias=False)
    
                    # Build previous state
                    trans_hidden_c, trans_hidden_h = tf.split(trans_hidden_state, num_or_size_splits=2, axis=0)
                    trans_hidden_c = tf.reshape(trans_hidden_c, shape=[-1, self.cons_manager.transducer_hidden_units])
                    trans_hidden_h = tf.reshape(trans_hidden_h, shape=[-1, self.cons_manager.transducer_hidden_units])
                    trans_hidden_state_t = LSTMStateTuple(trans_hidden_c, trans_hidden_h)
    
                    decoder = tf.contrib.seq2seq.BasicDecoder(
                        decoder_cell, helper,
                        decoder_cell.zero_state(1, tf.float32).clone(cell_state=trans_hidden_state_t),
                        output_layer=projection_layer)
    
                    outputs, transducer_hidden_state_new, _ = tf.contrib.seq2seq.dynamic_decode(decoder,
                                                                                                output_time_major=True,
                                                                                                maximum_iterations=transducer_amount_outputs)
                    logits = outputs.rnn_output  # logits of shape [max_time,batch_size,vocab_size]
                    decoder_prediction = outputs.sample_id  # For debugging
    
                    # Modify output of transducer_hidden_state_new so that it can be fed back in again without problems.
                    transducer_hidden_state_new = tf.concat(
                        [transducer_hidden_state_new[0].c, transducer_hidden_state_new[0].h],
                        axis=0)
                    transducer_hidden_state_new = tf.reshape(transducer_hidden_state_new,
                                                             shape=[2, -1, self.cons_manager.transducer_hidden_units])
    
    
                    # Note the outputs
                    outputs_int = outputs_int.write(current_block - start_block, logits)
    
                    return current_block + 1, outputs_int, encoder_hidden_state_new, transducer_hidden_state_new
    
                _, outputs_final, encoder_hidden_state_new, transducer_hidden_state_new = \
                    tf.while_loop(cond, body, init_state, parallel_iterations=1)
    
                # Process outputs
                outputs = outputs_final.concat()
                logits = tf.reshape(
                    outputs,
                    shape=(-1, 1, self.cons_manager.vocab_size))  # And now its [max_output_time, batch_size, vocab]
    
                # For loading the model later on
                logits = tf.identity(logits, name='logits')
                encoder_hidden_state_new = tf.identity(encoder_hidden_state_new, name='encoder_hidden_state_new')
                transducer_hidden_state_new = tf.identity(transducer_hidden_state_new, name='transducer_hidden_state_new')
    
            train_saver = tf.train.Saver()  # For now save everything
    
            return max_blocks, inputs_full_raw, transducer_list_outputs, start_block, encoder_hidden_init,\
                trans_hidden_init, logits, encoder_hidden_state_new, transducer_hidden_state_new, train_saver
    
        def build_training_step(self):
            targets = tf.placeholder(shape=(None,), dtype=tf.int32, name='targets')
            targets_one_hot = tf.one_hot(targets, depth=self.cons_manager.vocab_size, dtype=tf.float32)
    
            targets_one_hot = tf.Print(targets_one_hot, [targets], message='Targets: ', summarize=10)
            targets_one_hot = tf.Print(targets_one_hot, [tf.argmax(self.logits, axis=2)], message='Argmax: ', summarize=10)
    
            stepwise_cross_entropy = tf.nn.softmax_cross_entropy_with_logits(labels=targets_one_hot,
                                                                             logits=self.logits)
            loss = tf.reduce_mean(stepwise_cross_entropy)
    
            # ERROR happens in this line
            train_op = tf.train.AdamOptimizer().minimize(loss)
            train_op = None
            return targets, train_op, loss
    
    
    constants_manager = ConstantsManager(input_dimensions=1, input_embedding_size=11, inputs_embedded=False,
                                         encoder_hidden_units=100, transducer_hidden_units=100, vocab_ids=[0, 1, 2],
                                         input_block_size=1, beam_width=5)
    model = Model(cons_manager=constants_manager)
    
    with tf.Session() as sess:
        writer = tf.summary.FileWriter("/tmp/graph", sess.graph_def)
        sess.run(tf.global_variables_initializer())
        writer.flush()
        writer.close()

**Picture of the graph and offending tensor (in red)**

The `rnn` box is in a while loop itself.

![graph](https://user-images.githubusercontent.com/9123400/36559487-0d147680-17c3-11e8-9ae9-d2dca5950579.jpeg)

**Comment by tensorflowbutler** [comment]
Nagging Assignee @skye: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by nikita68** [comment]
Any new information?

**Comment by skye** [comment]
Unfortunately no, there are a number of open control flow bugs and I haven't got to this one yet. You can try running at head, it's possible this has already been fixed.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @skye: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by nikita68** [comment]
This error is gone with 1.7!

**Comment by skye** [comment]
Awesome, thanks for confirming!

**Comment by DeepakPawar1** [comment]
How did you remove this error. I am facing a similar error
@skye

**Comment by DeepakPawar1** [comment]
File "C:\Users\DELL\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\tensorflow\python\training\saver.py", line 1338, in __init__
    self.build()
  File "C:\Users\DELL\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\tensorflow\python\training\saver.py", line 1347, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "C:\Users\DELL\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\tensorflow\python\training\saver.py", line 1384, in _build
    build_save=build_save, build_restore=build_restore)
  File "C:\Users\DELL\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\tensorflow\python\training\saver.py", line 832, in _build_internal
    save_tensor = self._AddSaveOps(filename_tensor, saveables)
  File "C:\Users\DELL\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\tensorflow\python\training\saver.py", line 350, in _AddSaveOps
    save = self.save_op(filename_tensor, saveables)
  File "C:\Users\DELL\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\tensorflow\python\training\saver.py", line 266, in save_op
    tensors)
  File "C:\Users\DELL\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\tensorflow\python\ops\gen_io_ops.py", line 1800, in save_v2
    shape_and_slices=shape_and_slices, tensors=tensors, name=name)
  File "C:\Users\DELL\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\DELL\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\tensorflow\python\framework\ops.py", line 3392, in create_op
    op_def=op_def)
  File "C:\Users\DELL\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\tensorflow\python\framework\ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

UnknownError (see above for traceback): Failed to rename: out/heart_disease.chkp.index.tempstate11972684499671613654 to: out/heart_disease.chkp.index : Access is denied.
; Input/output error
[[Node: save_4/SaveV2 = SaveV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT64, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save_4/Const_0_0, save_4/SaveV2/tensor_names, save_4/SaveV2/shape_and_slices, Adam/beta_1, Adam/beta_2, Adam/decay, Adam/iterations, Adam/lr, Adam_1/beta_1, Adam_1/beta_2, Adam_1/decay, Adam_1/iterations, Adam_1/lr, Adam_2/beta_1, Adam_2/beta_2, Adam_2/decay, Adam_2/iterations, Adam_2/lr, dense_1/bias, dense_1/kernel, dense_2/bias, dense_2/kernel, dense_3/bias, dense_3/kernel, dense_4/bias, dense_4/kernel, dense_5/bias, dense_5/kernel, dense_6/bias, dense_6/kernel, dense_7/bias, dense_7/kernel, dense_8/bias, dense_8/kernel, dense_9/bias, dense_9/kernel, training/Adam/Variable, training/Adam/Variable_1, training/Adam/Variable_10, training/Adam/Variable_11, training/Adam/Variable_12, training/Adam/Variable_13, training/Adam/Variable_14, training/Adam/Variable_15, training/Adam/Variable_16, training/Adam/Variable_17, training/Adam/Variable_2, training/Adam/Variable_3, training/Adam/Variable_4, training/Adam/Variable_5, training/Adam/Variable_6, training/Adam/Variable_7, training/Adam/Variable_8, training/Adam/Variable_9, training_1/Adam/Variable, training_1/Adam/Variable_1, training_1/Adam/Variable_10, training_1/Adam/Variable_11, training_1/Adam/Variable_12, training_1/Adam/Variable_13, training_1/Adam/Variable_14, training_1/Adam/Variable_15, training_1/Adam/Variable_16, training_1/Adam/Variable_17, training_1/Adam/Variable_2, training_1/Adam/Variable_3, training_1/Adam/Variable_4, training_1/Adam/Variable_5, training_1/Adam/Variable_6, training_1/Adam/Variable_7, training_1/Adam/Variable_8, training_1/Adam/Variable_9, training_2/Adam/Variable, training_2/Adam/Variable_1, training_2/Adam/Variable_10, training_2/Adam/Variable_11, training_2/Adam/Variable_12, training_2/Adam/Variable_13, training_2/Adam/Variable_14, training_2/Adam/Variable_15, training_2/Adam/Variable_16, training_2/Adam/Variable_17, training_2/Adam/Variable_2, training_2/Adam/Variable_3, training_2/Adam/Variable_4, training_2/Adam/Variable_5, training_2/Adam/Variable_6, training_2/Adam/Variable_7, training_2/Adam/Variable_8, training_2/Adam/Variable_9)]]

**Comment by nikita68** [comment]
The error is gone when you update to tf version 1.7 or above for me

**Comment by DeepakPawar1** [comment]
how to update tf to 1.7 version

**Comment by DeepakPawar1** [comment]
Actually when I check tf.__version__ it gives me 1.8.0 as version

**Comment by nikita68** [comment]
I'm not sure that this is the same error. It looks like you have an "Access is denied." error in there, I think the folder where you're saving the checkpoints doesn't have the correct access rights.

**Comment by DeepakPawar1** [comment]
how to change the folder
