### ISSUE TITLE
got error when run eval.py in object detection api

### ISSUE THREAD

**Issue by zeynali** [tensorflow/tensorflow#17212]
Hi ,
i faced with this error when i run eval.py:

INFO:tensorflow:depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
Traceback (most recent call last):
File "eval.py", line 142, in
tf.app.run()
File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 124, in run
_sys.exit(main(argv))
File "eval.py", line 138, in main
FLAGS.checkpoint_dir, FLAGS.eval_dir)
File "/home/mm/models/research/object_detection/evaluator.py", line 240, in evaluate
save_graph_dir=(eval_dir if eval_config.save_graph else ''))
File "/home/mm/models/research/object_detection/eval_util.py", line 448, in repeated_checkpoint_run
return metrics
UnboundLocalError: local variable 'metrics' referenced before assignment

########################################################################
i once saw that must be initial metrics : in the beginning of repeated_checkpoint_run i i added this :
metrics={}
pr_value={}
global_step={}
i this case , that error don't face but after for a while processing don't give me any value :
mm@mm:~/models/research/object_detection$ python3 eval.py \

        --logtostderr \
        --checkpoint_dir=training_ssd_mobile/model.ckpt-200000 \
        --eval_dir=eval_log\
        --pipeline_config_path=ssd_mobilenet_v1_coco_2017_11_17/ssd_mobilenet_v1_focal_loss_coco.config

INFO:tensorflow:depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0

**Comment by asimshankar** [comment]
I apologize but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new) . Please provide all the information it asks. Thank you.

**Comment by tensorflowbutler** [comment]
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by zeynali** [comment]
yes , i'm working to solve this problem.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @bignamehyp: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by sniper0110** [comment]
I am facing the same problem, has anyone found a workaround to solve this issue?

**Comment by bignamehyp** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by yangsiyu007** [comment]
OS: Ubuntu 16.04
TF version: 1.6.0
(note that it also happens to me on macOS, TF 1.6.0)

Command used:
`python scripts/eval.py --logtostderr --checkpoint_dir=models/baseline --eval_dir=models/baseline/eval --pipeline_config_path=scripts/baseline.config`

In the folder models/baseline, there are 3 files:
baseline-ckpt.data-00000-of-00001
baseline-ckpt.index
baseline-ckpt.meta

I also tried command
`python scripts/eval.py --logtostderr --checkpoint_dir=models/baseline/baseline-ckpt --eval_dir=models/baseline/eval --pipeline_config_path=scripts/baseline.config`
because in baseline.config, I have the setting `fine_tune_checkpoint: "models/baseline/baseline-ckpt"` and I used it to run training fine. 

After adding `from tensorflow.python.platform import tf_logging as logging` in eval_util.py as suggested in this [post](https://stackoverflow.com/questions/48163085/tensorflow-object-detection-api-eval-py-metrics-referenced-before-assignment), I can see that it was because of the following error

INFO:tensorflow:depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
INFO:tensorflow:Starting evaluation at 2018-05-02-21:07:47
**INFO:tensorflow:No model found in model/baseline. Will try again in 300 seconds
INFO:tensorflow:Finished evaluation!**
Traceback (most recent call last):
  File "scripts/eval.py", line 162, in <module>
    tf.app.run()
  File "/Users/siyuyang/anaconda/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "scripts/eval.py", line 158, in main
    FLAGS.checkpoint_dir, FLAGS.eval_dir)
  File "/Users/siyuyang/source/repos/TF_models/research/object_detection/evaluator.py", line 274, in evaluate
    losses_dict=losses_dict)
  File "/Users/siyuyang/source/repos/TF_models/research/object_detection/eval_util.py", line 438, in repeated_checkpoint_run
    return metrics
UnboundLocalError: local variable 'metrics' referenced before assignment

**Comment by xiaoyongzhu** [comment]
@bignamehyp I probably have information that can help narrow down the issue. So I had an early clone of the `model` repository which works, however the latest clone from the `model` repo does not work for me either (the same error message as above). I believe there's some check-in which introduces some backward incompatibility.

The output of `git logs` from my clone is like this, which doesn't have the issue mentioned above. 


```
commit aad56e4c428ce9ff5fbb1e9e1b0ef96f1e1fdfd2
Merge: e3bfb9b c54c9bd
Author: Lukasz Kaiser <lukaszkaiser@users.noreply.github.com>
Date:   Mon Apr 9 15:57:25 2018 -0700

    Merge pull request #3918 from andrefaraujo/master

    Updating DELF README

commit c54c9bd9f028ee9ec29aa63b5303ac1282662888
Author: Andre Araujo <andrearaujo@rodete-desktop-imager.corp.google.com>
Date:   Mon Apr 9 15:21:37 2018 -0700

    Updating DELF README

commit e3bfb9b8dc0161d77e7df4be4592ebbe0ec579d3
Merge: 2506c9a e658d64
Author: pkulzc <lzc@google.com>
Date:   Mon Apr 9 12:01:25 2018 -0700

    Merge pull request #3744 from liangxiao05/master

    Update create_pascal_tf_record.py

commit 2506c9a65757b371d66a7aea3a6f973ea414f4da
Merge: fbb27cf 77725c6
Author: pkulzc <lzc@google.com>
Date:   Mon Apr 9 12:01:02 2018 -0700

    Merge pull request #3914 from matiji66/master

    Update evaluation_protocols.md

commit fbb27cf31f09c3b4b10c1e237fd283f06db301d2
Author: Taylor Robie <taylorrobie@google.com>
Date:   Mon Apr 9 11:14:59 2018 -0700

    Add fp16 support to official ResNet. (#3687)

    * Add fp16 support to resnet.

    * address PR comments

    * add dtype checking to model definition

    * delint

    * more PR comments
```

And following the trace, I believe https://github.com/tensorflow/models/tree/c54c9bd9f028ee9ec29aa63b5303ac1282662888 this branch should not have the problem above (though I haven't validated)

**Comment by yangsiyu007** [comment]
@bignamehyp 
I was able to resolve my issue! It was actually because I lacked the "checkpoint" text file of the format
> model_checkpoint_path: "baseline-ckpt"
> all_model_checkpoint_paths: "baseline-ckpt"

in `checkpoint_dir`.

The `local variable 'metrics' referenced before assignment` error is probably just failing to catch that case when no checkpoints can be found. 

Could you also add `from tensorflow.python.platform import tf_logging as logging` to `eval_util.py` in the place of `import logging`, as it is really hard to tell what's going on without the logging messages.

**Comment by zeynali** [comment]
@yangsiyu007 , `from tensorflow.python.platform import tf_logging as logging to eval_util.py` that is work. i before tested this .

**Comment by tensorflowbutler** [comment]
Nagging Assignee @bignamehyp: It has been 23 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by njzhaixiang** [comment]
@yangsiyu007 I met the same issue like you. 
Where to add the "checkpoint" text file?
 I still have the result `INFO:tensorflow:No model found in tran_logs/model-ckpt. Will try again in 300 seconds`

**Comment by xiaoyongzhu** [comment]
@njzhaixiang the checkpoint file should be in the train_folder (i.e. together with the checkpoint file)

**Comment by yangsiyu007** [comment]
@njzhaixiang yes like xiaoyongzhu said, the "checkpoint" text file should be in the same directory where your other 3 checkpoint files are.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
It has been 29 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by achowdhery** [comment]
Try the updated tutorial:
https://medium.com/tensorflow/training-and-serving-a-realtime-mobile-object-detector-in-30-minutes-with-cloud-tpus-b78971cf1193
