### ISSUE TITLE
Unable to load retrained MobileNet

### ISSUE THREAD

**Issue by frap129** [tensorflow/tensorflow#17227]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Arch Linux on x86_64
- **TensorFlow installed from (source or binary)**: binary/pip
- **TensorFlow version (use command below)**: 1.5.0
- **Python version**: 3.6.4
- **Exact command to reproduce**:
`python3 label_image/label_image.py \
--graph=output_graph.pb --labels=output_labels.txt \
--input_layer=Mul \
--output_layer=final_result \
--input_mean=128 --input_std=128 \
--image=images.jpg`

### Describe the problem
Attempting to use a retrained MobileNet model (retrained with retrain.py) results in 

`Traceback (most recent call last):
  File "label_image/label_image.py", line 144, in <module>
    classify()
  File "label_image/label_image.py", line 116, in classify
    graph = load_graph(model_file)
  File "label_image/label_image.py", line 34, in load_graph
    graph_def.ParseFromString(f.read())
google.protobuf.message.DecodeError: Error parsing message`

when trying to use the label_image example, and 

`Traceback (most recent call last):
  File "label_image/label_image.py", line 144, in <module>
    classify()
  File "label_image/label_image.py", line 116, in classify
    graph = load_graph(model_file)
  File "label_image/label_image.py", line 34, in load_graph
    graph_def.ParseFromString(f.read())
  File "/usr/lib/python3.6/site-packages/google/protobuf/message.py", line 185, in ParseFromString
    self.MergeFromString(serialized)
  File "/usr/lib/python3.6/site-packages/google/protobuf/internal/python_message.py", line 1083, in MergeFromString
    if self._InternalParse(serialized, 0, length) != length:
  File "/usr/lib/python3.6/site-packages/google/protobuf/internal/python_message.py", line 1120, in InternalParse
    pos = field_decoder(buffer, new_pos, end, self, field_dict)
  File "/usr/lib/python3.6/site-packages/google/protobuf/internal/decoder.py", line 633, in DecodeField
    if value._InternalParse(buffer, pos, new_pos) != new_pos:
  File "/usr/lib/python3.6/site-packages/google/protobuf/internal/python_message.py", line 1120, in InternalParse
    pos = field_decoder(buffer, new_pos, end, self, field_dict)
  File "/usr/lib/python3.6/site-packages/google/protobuf/internal/decoder.py", line 612, in DecodeRepeatedField
    if value.add()._InternalParse(buffer, pos, new_pos) != new_pos:
  File "/usr/lib/python3.6/site-packages/google/protobuf/internal/python_message.py", line 1120, in InternalParse
    pos = field_decoder(buffer, new_pos, end, self, field_dict)
  File "/usr/lib/python3.6/site-packages/google/protobuf/internal/decoder.py", line 743, in DecodeMap
    if submsg._InternalParse(buffer, pos, new_pos) != new_pos:
  File "/usr/lib/python3.6/site-packages/google/protobuf/internal/python_message.py", line 1109, in InternalParse
    new_pos = local_SkipField(buffer, new_pos, end, tag_bytes)
  File "/usr/lib/python3.6/site-packages/google/protobuf/internal/decoder.py", line 850, in SkipField
    return WIRETYPE_TO_SKIPPER[wire_type](buffer, pos, end)
  File "/usr/lib/python3.6/site-packages/google/protobuf/internal/decoder.py", line 799, in _SkipGroup
    new_pos = SkipField(buffer, pos, end, tag_bytes)
  File "/usr/lib/python3.6/site-packages/google/protobuf/internal/decoder.py", line 850, in SkipField
    return WIRETYPE_TO_SKIPPER[wire_type](buffer, pos, end)
  File "/usr/lib/python3.6/site-packages/google/protobuf/internal/decoder.py", line 814, in _SkipFixed32
    raise _DecodeError('Truncated message.')
google.protobuf.message.DecodeError: Truncated message.` 

when using `PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python` as mentioned in [https://github.com/tensorflow/tensorflow/issues/582](url)

I also get the same issues when trying to quantize the model.

**Comment by domarps** [comment]
I had faced a similar issue a while ago, but I realized that my Linux shell variables, `IMAGE_SIZE` and `ARCHITECTURE` had been incorrectly populated.

**Comment by frap129** [comment]
Unfortunately, that doesn't seem to be my issue. Unsetting them before retraining, as well as setting them to the correct values, doesn't change the outcome.

**Comment by frap129** [comment]
@tensorflowbutler

**Comment by kaskagir** [comment]
same here...:(

**Comment by frap129** [comment]
I was able to fix it by using the v1.4.0 tag, something broke it since then.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @petewarden: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @petewarden: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @petewarden: It has been 59 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @petewarden: It has been 75 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @petewarden: It has been 90 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by s5plus1** [comment]
@frap129 

Same here.

I'm trying to freeze graph from saved model and get the same error after setting PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION.

Windows 10
Python 3.5.4
TensorFlow 1.5

**Comment by eaglep91** [comment]
Same here, just loaded a model and got this error

**Comment by frap129** [comment]
Nagging Assignee @petewarden: It has been 122 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @petewarden: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @petewarden: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @petewarden: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by frap129** [comment]
@tensorflowbutler can you nag a little harder? Thanks

**Comment by tensorflowbutler** [comment]
Nagging Assignee @petewarden: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @petewarden: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @petewarden: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @petewarden: It has been 59 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @petewarden: It has been 77 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by petewarden** [comment]
Apologies for the very long delay on this one. I've not been able to reproduce this, so closing for now, but please reopen if you're still hitting it.
