### ISSUE TITLE
The labels do not appear on android app screen

### ISSUE THREAD

**Issue by aReaSa** [tensorflow/tensorflow#17248]
------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 17.10
- **TensorFlow installed from (source or binary)**: Tensorflow For Poets 2 
- **Python version**: 3
You can obtain the TensorFlow version with
v1.5.0-0-g37aa430d84 1.5.0

### Describe the problem

Hello dear friends,
I literally followed all instructions in Tenforflow For Poets.
and for Tensorflow For Poets Mobile.

I visited all the sites, blogs and forums, but I could not find any solution or similar of this problem.

The first android application was not opened, it was resolved in some way.
Now it opens but the labels do not appear.

I trained with Inception v3. I optimized it, stripped it, tried it on all emulators, tried it on my own phone.

I'm adding a screenshot so you can look at it.

Thank you in advance for your answers ...

![screenshot from 2018-02-25 05-58-19](https://user-images.githubusercontent.com/26048237/36637916-358ee1dc-19f7-11e8-96d4-59d5eac06c93.png)

### Source code / logs
02-25 06:23:37.531 4375-4375/? I/zygote: Not late-enabling -Xcheck:jni (already on)
02-25 06:23:37.538 4375-4375/? W/zygote: Unexpected CPU variant for X86 using defaults: x86
02-25 06:23:37.582 4375-4382/? I/zygote: Debugger is no longer active
02-25 06:23:37.810 4375-4375/? I/InstantRun: starting instant run server: is main process
02-25 06:23:37.852 4375-4375/? D/tensorflow: CameraActivity: onCreate org.tensorflow.demo.ClassifierActivity@e5ff96d
02-25 06:23:38.025 4375-4375/? D/tensorflow: CameraActivity: onStart org.tensorflow.demo.ClassifierActivity@e5ff96d
02-25 06:23:38.025 4375-4375/? D/tensorflow: CameraActivity: onResume org.tensorflow.demo.ClassifierActivity@e5ff96d
02-25 06:23:38.029 4375-4394/? D/OpenGLRenderer: HWUI GL Pipeline
02-25 06:23:38.048 4375-4375/? D/tensorflow: CameraActivity: onPause org.tensorflow.demo.ClassifierActivity@e5ff96d
02-25 06:23:38.048 4375-4375/? D/tensorflow: CameraActivity: Requesting finish
02-25 06:23:38.119 4375-4394/? I/OpenGLRenderer: Initialized EGL, version 1.4
02-25 06:23:38.119 4375-4394/? D/OpenGLRenderer: Swap behavior 1
02-25 06:23:38.120 4375-4394/? W/OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
02-25 06:23:38.120 4375-4394/? D/OpenGLRenderer: Swap behavior 0
02-25 06:23:38.180 4375-4394/? D/EGL_emulation: eglCreateContext: 0xab032640: maj 2 min 0 rcv 2
02-25 06:23:38.686 4375-4394/org.tensorflow.demo D/EGL_emulation: eglMakeCurrent: 0xab032640: ver 2 0 (tinfo 0xab00b1d0)
02-25 06:23:38.711 4375-4375/org.tensorflow.demo I/Choreographer: Skipped 35 frames!  The application may be doing too much work on its main thread.
02-25 06:23:38.882 4375-4394/org.tensorflow.demo D/EGL_emulation: eglMakeCurrent: 0xab032640: ver 2 0 (tinfo 0xab00b1d0)
02-25 06:23:39.475 4375-4394/org.tensorflow.demo D/EGL_emulation: eglMakeCurrent: 0xab032640: ver 2 0 (tinfo 0xab00b1d0)
02-25 06:23:39.677 4375-4375/org.tensorflow.demo D/tensorflow: CameraActivity: onStop org.tensorflow.demo.ClassifierActivity@e5ff96d
02-25 06:23:39.678 4375-4375/org.tensorflow.demo D/tensorflow: CameraActivity: onDestroy org.tensorflow.demo.ClassifierActivity@e5ff96d
02-25 06:23:45.425 4375-4375/org.tensorflow.demo D/tensorflow: CameraActivity: onCreate org.tensorflow.demo.ClassifierActivity@186f2a1
02-25 06:23:45.436 4375-4375/org.tensorflow.demo I/CameraManagerGlobal: Connecting to camera service
02-25 06:23:45.447 4375-4375/org.tensorflow.demo I/tensorflow: CameraActivity: Camera API lv2?: false
02-25 06:23:45.467 4375-4375/org.tensorflow.demo D/tensorflow: CameraActivity: onStart org.tensorflow.demo.ClassifierActivity@186f2a1
02-25 06:23:45.467 4375-4375/org.tensorflow.demo D/tensorflow: CameraActivity: onResume org.tensorflow.demo.ClassifierActivity@186f2a1
02-25 06:23:45.773 4375-4375/org.tensorflow.demo I/tensorflow: CameraConnectionFragment: Desired size: 640x480, min size: 480x480
02-25 06:23:45.774 4375-4375/org.tensorflow.demo I/tensorflow: CameraConnectionFragment: Valid preview sizes: [640x480]
02-25 06:23:45.774 4375-4375/org.tensorflow.demo I/tensorflow: CameraConnectionFragment: Rejected preview sizes: []
02-25 06:23:45.774 4375-4375/org.tensorflow.demo I/tensorflow: CameraConnectionFragment: Exact size match found.
02-25 06:23:45.844 4375-4394/org.tensorflow.demo D/EGL_emulation: eglMakeCurrent: 0xab032640: ver 2 0 (tinfo 0xab00b1d0)
02-25 06:23:46.007 4375-4375/org.tensorflow.demo I/TensorFlowImageClassifier: Reading labels from: retrained_labels.txt
02-25 06:23:46.009 4375-4375/org.tensorflow.demo I/TensorFlowInferenceInterface: Checking to see if TensorFlow native methods are already loaded
02-25 06:23:46.009 4375-4375/org.tensorflow.demo E/zygote: No implementation found for long org.tensorflow.contrib.android.RunStats.allocate() (tried Java_org_tensorflow_contrib_android_RunStats_allocate and Java_org_tensorflow_contrib_android_RunStats_allocate__)
02-25 06:23:46.009 4375-4375/org.tensorflow.demo I/TensorFlowInferenceInterface: TensorFlow native methods not found, attempting to load via tensorflow_inference
02-25 06:23:46.022 4375-4375/org.tensorflow.demo W/native: cpu_feature_guard.cc:34 The TensorFlow library was compiled to use SSE instructions, but these aren't available on your machine.
02-25 06:23:46.022 4375-4375/org.tensorflow.demo W/native: cpu_feature_guard.cc:34 The TensorFlow library was compiled to use SSE2 instructions, but these aren't available on your machine.
02-25 06:23:46.022 4375-4375/org.tensorflow.demo W/native: cpu_feature_guard.cc:34 The TensorFlow library was compiled to use SSE3 instructions, but these aren't available on your machine.
02-25 06:23:46.024 4375-4375/org.tensorflow.demo I/TensorFlowInferenceInterface: Successfully loaded TensorFlow native methods (RunStats error may be ignored)
02-25 06:23:46.596 4375-4375/org.tensorflow.demo E/tensorflow: CameraActivity: Exception!
                                                               java.lang.RuntimeException: Failed to load model from 'file:///android_asset/rounded_graph_str.pb'
                                                                   at org.tensorflow.contrib.android.TensorFlowInferenceInterface.<init>(TensorFlowInferenceInterface.java:113)
                                                                   at org.tensorflow.demo.TensorFlowImageClassifier.create(TensorFlowImageClassifier.java:103)
                                                                   at org.tensorflow.demo.ClassifierActivity.onPreviewSizeChosen(ClassifierActivity.java:113)
                                                                   at org.tensorflow.demo.CameraActivity.onPreviewFrame(CameraActivity.java:119)
                                                                   at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1124)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                   at android.os.Looper.loop(Looper.java:164)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                                                                Caused by: java.io.IOException: Not a valid TensorFlow Graph serialization: NodeDef mentions attr 'dilations' not in Op<name=Conv2D; signature=input:T, filter:T -> output:T; attr=T:type,allowed=[DT_HALF, DT_FLOAT]; attr=strides:list(int); attr=use_cudnn_on_gpu:bool,default=true; attr=padding:string,allowed=["SAME", "VALID"]; attr=data_format:string,default="NHWC",allowed=["NHWC", "NCHW"]>; NodeDef: conv/Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], padding="VALID", strides=[1, 2, 2, 1], use_cudnn_on_gpu=true](Mul, conv/conv2d_params). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
                                                                   at org.tensorflow.contrib.android.TensorFlowInferenceInterface.loadGraph(TensorFlowInferenceInterface.java:535)
                                                                   at org.tensorflow.contrib.android.TensorFlowInferenceInterface.<init>(TensorFlowInferenceInterface.java:105)
                                                                   at org.tensorflow.demo.TensorFlowImageClassifier.create(TensorFlowImageClassifier.java:103) 
                                                                   at org.tensorflow.demo.ClassifierActivity.onPreviewSizeChosen(ClassifierActivity.java:113) 
                                                                   at org.tensorflow.demo.CameraActivity.onPreviewFrame(CameraActivity.java:119) 
                                                                   at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1124) 
                                                                   at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                                   at android.os.Looper.loop(Looper.java:164) 
                                                                   at android.app.ActivityThread.main(ActivityThread.java:6541) 
                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                   at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
02-25 06:23:49.350 4375-4380/org.tensorflow.demo I/zygote: Do partial code cache collection, code=20KB, data=21KB
02-25 06:23:49.350 4375-4380/org.tensorflow.demo I/zygote: After code cache collection, code=20KB, data=21KB
02-25 06:23:49.350 4375-4380/org.tensorflow.demo I/zygote: Increasing code cache capacity to 128KB
02-25 06:23:55.613 4375-4380/org.tensorflow.demo I/zygote: Do partial code cache collection, code=61KB, data=49KB
02-25 06:23:55.614 4375-4380/org.tensorflow.demo I/zygote: After code cache collection, code=61KB, data=49KB
02-25 06:23:55.614 4375-4380/org.tensorflow.demo I/zygote: Increasing code cache capacity to 256KB

**Comment by angersson** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
