### ISSUE TITLE
Retrain.py script failing with nan-error at random without any code changes

### ISSUE THREAD

**Issue by RT-TL** [tensorflow/tensorflow#17252]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Working on a notebook with MacOS High Sierra v10.13.1 in a Docker container using Ubuntu 16.04.3
- **TensorFlow installed from (source or binary)**: Source
- **TensorFlow version (use command below)**: 1.5
- **Python version**: 2.7
- **Bazel version (if compiling from source)**: -
- **GCC/Compiler version (if compiling from source)**: -
- **CUDA/cuDNN version**: Using CPU 
- **GPU model and memory**:
- **Exact command to reproduce**: 

```
python -m scripts.retrain \
  --bottleneck_dir=tf_files/bottlenecks \
  --summaries_dir=tf_files/training_summaries/ \
  --output_graph=tf_files/retrained_graph.pb \
  --output_labels=tf_files/retrained_labels.txt \
  --image_dir=/ml/data/images
```

### Describe the problem

My set up is based on the tensorflow-for-poets tutorial. To test if everything is working I use the contained flower dataset. I tried to train the default inceptionV3 as well as the mobilenet architectures. However, training fails at some random point with the below listed error. This error does not seem to appear (or at least not as regular) if I train 500 or less training steps.

Based on what I read here the thrown error is indicating model instability. Since I changed neither code nor data this seems a bit strange. I think it might be a bug but you can probably help me figuring out if this is the case.

### Source code / logs

This is the error:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/ml/tensorflow-for-poets/scripts/retrain.py", line 1296, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 124, in run
    _sys.exit(main(argv))
  File "/ml/tensorflow-for-poets/scripts/retrain.py", line 1041, in main
    ground_truth_input: train_ground_truth})
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1128, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1344, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1363, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Nan in summary histogram for: activations
	 [[Node: activations = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](activations/tag, final_result)]]

Caused by op u'activations', defined at:
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/ml/tensorflow-for-poets/scripts/retrain.py", line 1296, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 124, in run
    _sys.exit(main(argv))
  File "/ml/tensorflow-for-poets/scripts/retrain.py", line 1001, in main
    model_info['bottleneck_tensor_size'], model_info['quantize_layer'])
  File "/ml/tensorflow-for-poets/scripts/retrain.py", line 754, in add_final_training_ops
    tf.summary.histogram('activations', final_tensor)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/summary/summary.py", line 193, in histogram
    tag=tag, values=values, name=scope)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_logging_ops.py", line 189, in _histogram_summary
    "HistogramSummary", tag=tag, values=values, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3160, in create_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1625, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Nan in summary histogram for: activations
	 [[Node: activations = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](activations/tag, final_result)]]
```

**Comment by angersson** [comment]
@petewarden Is there a bug on our end here?

**Comment by RT-TL** [comment]
A post on Stackoverflow helped me fix this. Switching from Python 2.7.12 to Python 3.4.6 removes the issue. So perhaps this is not a tensorflow issue - but it probably deserves a note in the docs because numeric instability is in general a common problem.

**Details on the issue**

It turns out the error originated mostly from the calculation of the softmax activation layer, it sometimes occurred later during cross entropy calculation. I used `tf.losses.sparse_softmax_cross_entropy` to calculate the loss.

Tensorflow uses some normalization in order to produce inf values due to large exponents in the softmax calculation by replacing e^x with e^(x-c) where c = max(0,x). Usually this should mitigate the issue and it obviously works in Python 3. 

Let me know if I can provide any additional info. Luckily for me: issue solved :-)
