### ISSUE TITLE
RuntimeError: TOCO failed see console for info.

### ISSUE THREAD

**Issue by SanthoshMKunthe** [tensorflow/tensorflow#17349]
I tried your way but its giving error. . . Kindly help. . . tf.version = 1.6.0rc1 and Ubuntu

**_#ERROR is as follows:_**

Converted 2 variables to const ops.
Traceback (most recent call last):

File "tf.py", line 94, in 
tflite_model=tf.contrib.lite.toco_convert(sess.graph_def,[x],[mxc])

File "/home/siteurl/anaconda3/envs/osrco/lib/python3.6/site-packages/tensorflow/contrib/lite/python/lite.py", line 212, in toco_convert
input_data.SerializeToString())

File "/home/siteurl/anaconda3/envs/osrco/lib/python3.6/site-packages/tensorflow/contrib/lite/python/lite.py", line 134, in toco_convert_protos
(stdout, stderr))

### RuntimeError: TOCO failed see console for info.
b'2018-03-01 14:40:13.614956: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1171]

Converting unsupported operation: VariableV2\n2018-03-01 14:40:13.615016: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1171]

Converting unsupported operation: Assign\n2018-03-01 14:40:13.615059: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1171]

Converting unsupported operation: VariableV2\n2018-03-01 14:40:13.615083: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1171]

Converting unsupported operation: Assign\n2018-03-01 14:40:13.615118: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1171]

Converting unsupported operation: Log\n2018-03-01 14:40:13.615212: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1171]

Converting unsupported operation: DynamicStitch\n2018-03-01 14:40:13.615283: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1171]

Converting unsupported operation: Reciprocal\n2018-03-01 14:40:13.615341: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1171]

Converting unsupported operation: BroadcastGradientArgs\n2018-03-01 14:40:13.615384: F tensorflow/contrib/lite/toco/import_tensorflow.cc:973]

Check failed: GetBoolAttr(node, "transpose_b") == false (1 vs. 0)\nAborted (core dumped)\n'
None

**_#CODE is as follows:_**

import tensorflow as tf
import pandas as pd
import numpy as np
import tempfile
import subprocess
tf.contrib.lite.tempfile = tempfile
tf.contrib.lite.subprocess = subprocess

from tensorflow.python.tools import freeze_graph
from tensorflow.python.tools import optimize_for_inference_lib

print(tf.version)
data=pd.read_csv('iris.data',names=['f1','f2','f3','f4','f5'])

s=np.asarray([1,0,0])
ve=np.asarray([0,1,0])
vi=np.asarray([0,0,1])

data['f5']=data['f5'].map({'Iris-setosa':s,'Iris-versicolor':ve,'Iris-virginica':vi})

#print(data)

data=data.iloc[np.random.permutation(len(data))]

print(data)

data=data.reset_index(drop=True)

#training data
trainFeats=data.ix[0:105,['f1','f2','f3','f4']]
temp=data['f5']
trainlabels=temp[0:106]

y=tf.placeholder(tf.float32,shape=[106, 3])
#weight and bias
m=tf.Variable(tf.zeros([4,3]))
x=tf.placeholder(tf.float32,shape=[106,4],name="Input")
c=tf.Variable(tf.zeros([3]))
mxc = tf.nn.softmax((tf.matmul(x, m) + c) ,name="output")

loss = tf.reduce_mean(-tf.reduce_sum(y * tf.log(mxc), reduction_indices=[1]))

train_step = tf.train.AdamOptimizer(0.01).minimize(loss)

sess = tf.InteractiveSession()
init = tf.initialize_all_variables()
sess.run(init)

#_=tf.contrib.tflite.Convert(sess.graph_def,[x],[mxc])

#number of interations
epoch=2000
for step in range(epoch):
print(sess.run([train_step,loss], feed_dict={x: trainFeats, y:[t for t in trainlabels.as_matrix()]}))

#testData=data.ix[130,['f1','f2','f3','f4']]
#testDataInFrormat=testData.reshape(1,4)
#print(sess.run(tf.argmax(mxc),feed_dict={x:testDataInFrormat}))

tf.train.write_graph(sess.graph_def,'pbtxtFiles/','savegraph.pbtxt',as_text=True)

tf.train.Saver().save(sess,'pbtxtFiles/model.ckpt')

MODEL_NAME = 'iris'
input_graph_path = 'pbtxtFiles/savegraph.pbtxt'
checkpoint_path = 'pbtxtFiles/model.ckpt'
input_saver_def_path = ""
input_binary = False
output_node_names = "output"
restore_op_name = "save/restore_all"
filename_tensor_name = "save/Const:0"
output_frozen_graph_name = 'pbtxtFiles/frozen_model_'+MODEL_NAME+'.pb'
output_optimized_graph_name = 'pbtxtFiles/optimized_inference_model_'+MODEL_NAME+'.pb'
clear_devices = True

freeze_graph.freeze_graph(input_graph_path, input_saver_def_path,
input_binary, checkpoint_path, output_node_names,
restore_op_name, filename_tensor_name,
output_frozen_graph_name, clear_devices, "")

output_graph_def = optimize_for_inference_lib.optimize_for_inference(
sess.graph_def,
["Input"], # an array of the input node(s)
["output"], # an array of output nodes
tf.float32.as_datatype_enum)

tflite_model=tf.contrib.lite.toco_convert(sess.graph_def,[x],[mxc])
open("wow.tflite","w").write(tflite_model)

**_#IRIS.DATA is this:_**

5.1,3.5,1.4,0.2,Iris-setosa
4.9,3.0,1.4,0.2,Iris-setosa
4.7,3.2,1.3,0.2,Iris-setosa
4.6,3.1,1.5,0.2,Iris-setosa
5.0,3.6,1.4,0.2,Iris-setosa
5.4,3.9,1.7,0.4,Iris-setosa
4.6,3.4,1.4,0.3,Iris-setosa
5.0,3.4,1.5,0.2,Iris-setosa
4.4,2.9,1.4,0.2,Iris-setosa
4.9,3.1,1.5,0.1,Iris-setosa
5.4,3.7,1.5,0.2,Iris-setosa
4.8,3.4,1.6,0.2,Iris-setosa
4.8,3.0,1.4,0.1,Iris-setosa
4.3,3.0,1.1,0.1,Iris-setosa
5.8,4.0,1.2,0.2,Iris-setosa
5.7,4.4,1.5,0.4,Iris-setosa
5.4,3.9,1.3,0.4,Iris-setosa
5.1,3.5,1.4,0.3,Iris-setosa
5.7,3.8,1.7,0.3,Iris-setosa
5.1,3.8,1.5,0.3,Iris-setosa
5.4,3.4,1.7,0.2,Iris-setosa
5.1,3.7,1.5,0.4,Iris-setosa
4.6,3.6,1.0,0.2,Iris-setosa
5.1,3.3,1.7,0.5,Iris-setosa
4.8,3.4,1.9,0.2,Iris-setosa
5.0,3.0,1.6,0.2,Iris-setosa
5.0,3.4,1.6,0.4,Iris-setosa
5.2,3.5,1.5,0.2,Iris-setosa
5.2,3.4,1.4,0.2,Iris-setosa
4.7,3.2,1.6,0.2,Iris-setosa
4.8,3.1,1.6,0.2,Iris-setosa
5.4,3.4,1.5,0.4,Iris-setosa
5.2,4.1,1.5,0.1,Iris-setosa
5.5,4.2,1.4,0.2,Iris-setosa
4.9,3.1,1.5,0.1,Iris-setosa
5.0,3.2,1.2,0.2,Iris-setosa
5.5,3.5,1.3,0.2,Iris-setosa
4.9,3.1,1.5,0.1,Iris-setosa
4.4,3.0,1.3,0.2,Iris-setosa
5.1,3.4,1.5,0.2,Iris-setosa
5.0,3.5,1.3,0.3,Iris-setosa
4.5,2.3,1.3,0.3,Iris-setosa
4.4,3.2,1.3,0.2,Iris-setosa
5.0,3.5,1.6,0.6,Iris-setosa
5.1,3.8,1.9,0.4,Iris-setosa
4.8,3.0,1.4,0.3,Iris-setosa
5.1,3.8,1.6,0.2,Iris-setosa
4.6,3.2,1.4,0.2,Iris-setosa
5.3,3.7,1.5,0.2,Iris-setosa
5.0,3.3,1.4,0.2,Iris-setosa
7.0,3.2,4.7,1.4,Iris-versicolor
6.4,3.2,4.5,1.5,Iris-versicolor
6.9,3.1,4.9,1.5,Iris-versicolor
5.5,2.3,4.0,1.3,Iris-versicolor
6.5,2.8,4.6,1.5,Iris-versicolor
5.7,2.8,4.5,1.3,Iris-versicolor
6.3,3.3,4.7,1.6,Iris-versicolor
4.9,2.4,3.3,1.0,Iris-versicolor
6.6,2.9,4.6,1.3,Iris-versicolor
5.2,2.7,3.9,1.4,Iris-versicolor
5.0,2.0,3.5,1.0,Iris-versicolor
5.9,3.0,4.2,1.5,Iris-versicolor
6.0,2.2,4.0,1.0,Iris-versicolor
6.1,2.9,4.7,1.4,Iris-versicolor
5.6,2.9,3.6,1.3,Iris-versicolor
6.7,3.1,4.4,1.4,Iris-versicolor
5.6,3.0,4.5,1.5,Iris-versicolor
5.8,2.7,4.1,1.0,Iris-versicolor
6.2,2.2,4.5,1.5,Iris-versicolor
5.6,2.5,3.9,1.1,Iris-versicolor
5.9,3.2,4.8,1.8,Iris-versicolor
6.1,2.8,4.0,1.3,Iris-versicolor
6.3,2.5,4.9,1.5,Iris-versicolor
6.1,2.8,4.7,1.2,Iris-versicolor
6.4,2.9,4.3,1.3,Iris-versicolor
6.6,3.0,4.4,1.4,Iris-versicolor
6.8,2.8,4.8,1.4,Iris-versicolor
6.7,3.0,5.0,1.7,Iris-versicolor
6.0,2.9,4.5,1.5,Iris-versicolor
5.7,2.6,3.5,1.0,Iris-versicolor
5.5,2.4,3.8,1.1,Iris-versicolor
5.5,2.4,3.7,1.0,Iris-versicolor
5.8,2.7,3.9,1.2,Iris-versicolor
6.0,2.7,5.1,1.6,Iris-versicolor
5.4,3.0,4.5,1.5,Iris-versicolor
6.0,3.4,4.5,1.6,Iris-versicolor
6.7,3.1,4.7,1.5,Iris-versicolor
6.3,2.3,4.4,1.3,Iris-versicolor
5.6,3.0,4.1,1.3,Iris-versicolor
5.5,2.5,4.0,1.3,Iris-versicolor
5.5,2.6,4.4,1.2,Iris-versicolor
6.1,3.0,4.6,1.4,Iris-versicolor
5.8,2.6,4.0,1.2,Iris-versicolor
5.0,2.3,3.3,1.0,Iris-versicolor
5.6,2.7,4.2,1.3,Iris-versicolor
5.7,3.0,4.2,1.2,Iris-versicolor
5.7,2.9,4.2,1.3,Iris-versicolor
6.2,2.9,4.3,1.3,Iris-versicolor
5.1,2.5,3.0,1.1,Iris-versicolor
5.7,2.8,4.1,1.3,Iris-versicolor
6.3,3.3,6.0,2.5,Iris-virginica
5.8,2.7,5.1,1.9,Iris-virginica
7.1,3.0,5.9,2.1,Iris-virginica
6.3,2.9,5.6,1.8,Iris-virginica
6.5,3.0,5.8,2.2,Iris-virginica
7.6,3.0,6.6,2.1,Iris-virginica
4.9,2.5,4.5,1.7,Iris-virginica
7.3,2.9,6.3,1.8,Iris-virginica
6.7,2.5,5.8,1.8,Iris-virginica
7.2,3.6,6.1,2.5,Iris-virginica
6.5,3.2,5.1,2.0,Iris-virginica
6.4,2.7,5.3,1.9,Iris-virginica
6.8,3.0,5.5,2.1,Iris-virginica
5.7,2.5,5.0,2.0,Iris-virginica
5.8,2.8,5.1,2.4,Iris-virginica
6.4,3.2,5.3,2.3,Iris-virginica
6.5,3.0,5.5,1.8,Iris-virginica
7.7,3.8,6.7,2.2,Iris-virginica
7.7,2.6,6.9,2.3,Iris-virginica
6.0,2.2,5.0,1.5,Iris-virginica
6.9,3.2,5.7,2.3,Iris-virginica
5.6,2.8,4.9,2.0,Iris-virginica
7.7,2.8,6.7,2.0,Iris-virginica
6.3,2.7,4.9,1.8,Iris-virginica
6.7,3.3,5.7,2.1,Iris-virginica
7.2,3.2,6.0,1.8,Iris-virginica
6.2,2.8,4.8,1.8,Iris-virginica
6.1,3.0,4.9,1.8,Iris-virginica
6.4,2.8,5.6,2.1,Iris-virginica
7.2,3.0,5.8,1.6,Iris-virginica
7.4,2.8,6.1,1.9,Iris-virginica
7.9,3.8,6.4,2.0,Iris-virginica
6.4,2.8,5.6,2.2,Iris-virginica
6.3,2.8,5.1,1.5,Iris-virginica
6.1,2.6,5.6,1.4,Iris-virginica
7.7,3.0,6.1,2.3,Iris-virginica
6.3,3.4,5.6,2.4,Iris-virginica
6.4,3.1,5.5,1.8,Iris-virginica
6.0,3.0,4.8,1.8,Iris-virginica
6.9,3.1,5.4,2.1,Iris-virginica
6.7,3.1,5.6,2.4,Iris-virginica
6.9,3.1,5.1,2.3,Iris-virginica
5.8,2.7,5.1,1.9,Iris-virginica
6.8,3.2,5.9,2.3,Iris-virginica
6.7,3.3,5.7,2.5,Iris-virginica
6.7,3.0,5.2,2.3,Iris-virginica
6.3,2.5,5.0,1.9,Iris-virginica
6.5,3.0,5.2,2.0,Iris-virginica
6.2,3.4,5.4,2.3,Iris-virginica
5.9,3.0,5.1,1.8,Iris-virginica

Kindly help MR. @aselle
Kindly help MR. @facaiy
Kindly help MR. @leandroBorgesFerreira
Kindly help MR. @javierluraschi
Kindly help MR. @tensorflowbutler

**Comment by SanthoshMKunthe** [comment]
above code is not giving any output. . . wow.tflite is not even created. . . Please help. . .

**Comment by andrehentz** [comment]
> Check failed: GetBoolAttr(node, "transpose_b") == false (1 vs. 0)

That means you have a matmul with transposition, but that isn't supported yet.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @andrehentz: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by andrehentz** [comment]
@SanthoshMKunthe  I think this might be fixed now. Would you mind giving it another try?

**Comment by tkdkop** [comment]
This does not appear to be fixed on master as of today

**Comment by tensorflowbutler** [comment]
Nagging Assignee @andrehentz: It has been 21 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @andrehentz: It has been 36 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @andrehentz: It has been 51 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @andrehentz: It has been 66 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by aselle** [comment]
The presence of the Assign and Variable ops means this is not an inference graph. You need to use the optimize_for_inference_script for it to work.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @andrehentz: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tofulawrence** [comment]
Problem is that you're not freezing the graph, which converts variables into constants.

Before you call the TOCO convert, you need to convert variables to constants to produce a frozen graph def. Then pipe that frozen graph def into the TOCO convert.

Right now, you're referencing the sess.graph_def instead of the frozen graph.

**Comment by tofulawrence** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by cjr0106** [comment]
hi 
@tofulawrence i met the same wrong ,with the info :
RuntimeError: TOCO failed see console for info.
b'e:\\anaconda3\\lib\\site-packages\\h5py\\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.\r\n  from ._conv import register_converters as _register_converters\r\nTraceback (most recent call last):\r\n  File "e:\\anaconda3\\lib\\site-packages\\tensorflow\\contrib\\lite\\toco\\python\\tensorflow_wrap_toco.py", line 18, in swig_import_helper\r\n    fp, pathname, description = imp.find_module(\'_tensorflow_wrap_toco\', [dirname(__file__)])\r\n  File "e:\\anaconda3\\lib\\imp.py", line 297, in find_module\r\n    raise ImportError(_ERR_MSG.format(name), name=name)\r\nImportError: No module named \'_tensorflow_wrap_toco\'\r\n\r\nDuring handling of the above exception, another exception occurred:\r\n\r\nTraceback (most recent call last):\r\n  File "e:\\anaconda3\\lib\\runpy.py", line 193, in _run_module_as_main\r\n    "__main__", mod_spec)\r\n  File "e:\\anaconda3\\lib\\runpy.py", line 85, in _run_code\r\n    exec(code, run_globals)\r\n  File "E:\\Anaconda3\\Scripts\\toco_from_protos.exe\\__main__.py", line 5, in <module>\r\n  File "e:\\anaconda3\\lib\\site-packages\\tensorflow\\contrib\\lite\\toco\\python\\toco_from_protos.py", line 22, in <module>\r\n    from tensorflow.contrib.lite.toco.python import tensorflow_wrap_toco\r\n  File "e:\\anaconda3\\lib\\site-packages\\tensorflow\\contrib\\lite\\toco\\python\\tensorflow_wrap_toco.py", line 28, in <module>\r\n    _tensorflow_wrap_toco = swig_import_helper()\r\n  File "e:\\anaconda3\\lib\\site-packages\\tensorflow\\contrib\\lite\\toco\\python\\tensorflow_wrap_toco.py", line 20, in swig_import_helper\r\n    import _tensorflow_wrap_toco\r\nModuleNotFoundError: No module named \'_tensorflow_wrap_toco\'\r\n'
None
could you give me some advice

**Comment by soumy94** [comment]
Hi, 
I get the same error as the above. And I've been using the example given [converter python api guide(https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/lite/g3doc/convert/python_api.md)

`import numpy as np
import tensorflow as tf

# Generate tf.keras model.
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(2, input_shape=(3,)))
model.add(tf.keras.layers.RepeatVector(3))
model.add(tf.keras.layers.TimeDistributed(tf.keras.layers.Dense(3)))
model.compile(loss=tf.keras.losses.MSE,
              optimizer=tf.keras.optimizers.RMSprop(lr=0.0001),
              metrics=[tf.keras.metrics.categorical_accuracy],
              sample_weight_mode='temporal')

x = np.random.random((1, 3))
y = np.random.random((1, 3, 3))
model.train_on_batch(x, y)
model.predict(x)

# Save tf.keras model in HDF5 format.
keras_file = "keras_model.h5"
tf.keras.models.save_model(model, keras_file)

# Convert to TensorFlow Lite model.
converter = tf.contrib.lite.TFLiteConverter.from_keras_model_file(keras_file)

tflite_model = converter.convert()`

I ran this code and this is the error I get:

> RuntimeError: TOCO failed see console for info.
b'Traceback (most recent call last):\r\n  File "C:\\Users\\sgavvala\\AppData\\Roaming\\Python\\Python35\\site-packages\\tensorflow\\contrib\\lite\\toco\\python\\tensorflow_wrap_toco.py", line 18, in swig_import_helper\r\n    fp, pathname, description = imp.find_module(\'_tensorflow_wrap_toco\', [dirname(__file__)])\r\n  File "c:\\users\\sgavvala\\appdata\\local\\continuum\\anaconda3\\envs\\tensorflow\\lib\\imp.py", line 297, in find_module\r\n    raise ImportError(_ERR_MSG.format(name), name=name)\r\nImportError: No module named \'_tensorflow_wrap_toco\'\r\n\r\nDuring handling of the above exception, another exception occurred:\r\n\r\nTraceback (most recent call last):\r\n  File "c:\\users\\sgavvala\\appdata\\local\\continuum\\anaconda3\\envs\\tensorflow\\lib\\runpy.py", line 193, in _run_module_as_main\r\n    "__main__", mod_spec)\r\n  File "c:\\users\\sgavvala\\appdata\\local\\continuum\\anaconda3\\envs\\tensorflow\\lib\\runpy.py", line 85, in _run_code\r\n    exec(code, run_globals)\r\n  File "C:\\Users\\sgavvala\\AppData\\Local\\Continuum\\anaconda3\\envs\\tensorflow\\Scripts\\toco_from_protos.exe\\__main__.py", line 5, in <module>\r\n  File "C:\\Users\\sgavvala\\AppData\\Roaming\\Python\\Python35\\site-packages\\tensorflow\\contrib\\lite\\toco\\python\\toco_from_protos.py", line 22, in <module>\r\n    from tensorflow.contrib.lite.toco.python import tensorflow_wrap_toco\r\n  File "C:\\Users\\sgavvala\\AppData\\Roaming\\Python\\Python35\\site-packages\\tensorflow\\contrib\\lite\\toco\\python\\tensorflow_wrap_toco.py", line 28, in <module>\r\n    _tensorflow_wrap_toco = swig_import_helper()\r\n  File "C:\\Users\\sgavvala\\AppData\\Roaming\\Python\\Python35\\site-packages\\tensorflow\\contrib\\lite\\toco\\python\\tensorflow_wrap_toco.py", line 20, in swig_import_helper\r\n    import _tensorflow_wrap_toco\r\nImportError: No module named \'_tensorflow_wrap_toco\'\r\n'
None


I'm using Anaconda on windows with python 3.5 and tensorflow 1.11.

My plan is to convert a keras model with my custom layers into tflite quantized version.

**Comment by gjraza** [comment]
I am getting the same error. I am trying to load from a saved model which is saved in the form of a pb file generated from simple_save()

 TOCO failed see console for info.
b'Traceback (most recent call last):\r\n  File "C:\\anaconda3\\envs\\for Quantization\\lib\\site-packages\\tensorflow\\contrib\\lite\\toco\\python\\tensorflow_wrap_toco.py", line 18, in swig_import_helper\r\n    fp, pathname, description = imp.find_module(\'_tensorflow_wrap_toco\', [dirname(__file__)])\r\n  File "C:\\anaconda3\\envs\\for Quantization\\lib\\imp.py", line 297, in find_module\r\n    raise ImportError(_ERR_MSG.format(name), name=name)\r\nImportError: No module named \'_tensorflow_wrap_toco\'\r\n\r\nDuring handling of the above exception, another exception occurred:\r\n\r\nTraceback (most recent call last):\r\n  File "C:\\anaconda3\\envs\\for Quantization\\Scripts\\toco_from_protos-script.py", line 6, in <module>\r\n    from tensorflow.contrib.lite.toco.python.toco_from_protos import main\r\n  File "C:\\anaconda3\\envs\\for Quantization\\lib\\site-packages\\tensorflow\\contrib\\lite\\toco\\python\\toco_from_protos.py", line 22, in <module>\r\n    from tensorflow.contrib.lite.toco.python import tensorflow_wrap_toco\r\n  File "C:\\anaconda3\\envs\\for Quantization\\lib\\site-packages\\tensorflow\\contrib\\lite\\toco\\python\\tensorflow_wrap_toco.py", line 28, in <module>\r\n    _tensorflow_wrap_toco = swig_import_helper()\r\n  File "C:\\anaconda3\\envs\\for Quantization\\lib\\site-packages\\tensorflow\\contrib\\lite\\toco\\python\\tensorflow_wrap_toco.py", line 20, in swig_import_helper\r\n    import _tensorflow_wrap_toco\r\nModuleNotFoundError: No module named \'_tensorflow_wrap_toco\'\r\n'
None

**Comment by 0xpulsar** [comment]
This is a code from the documentation (https://www.tensorflow.org/lite/convert/python_api)
<code>
<img width="1129" alt="Screen Shot 2019-03-23 at 4 40 26 PM" src="https://user-images.githubusercontent.com/26170275/54865364-66617780-4d8a-11e9-8f5d-f0551153a643.png">

I am getting this error:
<error>
<img width="1134" alt="Screen Shot 2019-03-23 at 4 41 13 PM" src="https://user-images.githubusercontent.com/26170275/54865372-7f6a2880-4d8a-11e9-88fc-e75770df3b50.png">

My tensorFlow version is '1.12.0'

**Comment by iamhankai** [comment]
> This is a code from the documentation (https://www.tensorflow.org/lite/convert/python_api)
> ` <img alt="Screen Shot 2019-03-23 at 4 40 26 PM" width="1129" src="https://user-images.githubusercontent.com/26170275/54865364-66617780-4d8a-11e9-8f5d-f0551153a643.png">`
> 
> ` I am getting this error: <img alt="Screen Shot 2019-03-23 at 4 41 13 PM" width="1134" src="https://user-images.githubusercontent.com/26170275/54865372-7f6a2880-4d8a-11e9-88fc-e75770df3b50.png"> My tensorFlow version is '1.12.0' Please help me.`

Have you solved your problem? I met the same one.

**Comment by 0xpulsar** [comment]
@iamhankai .
What i did for converting model to TFlite is, used **tflite_convert** command in terminal.
Example: `tflite_convert   --output_file=too.tflite   --keras_model_file=keras_model.h5`
Input file: ' keras_model.h5'
Output file: 'too.tflite'

**Comment by iamhankai** [comment]
> @iamhankai .
> What i did for converting model to TFlite is, used **tflite_convert** command in terminal.
> Example: `tflite_convert --output_file=too.tflite --keras_model_file=keras_model.h5`
> Input file: ' keras_model.h5'
> Output file: 'too.tflite'

Thanks~
