### ISSUE TITLE
Cannot import Tensorflow on a system that has anaconda installed, though tensorflow installed successfully

### ISSUE THREAD

**Issue by isalirezag** [tensorflow/tensorflow#17341]
I installed tensorflow  on ubntu 16.04 by using 
``` 
pip  install --upgrade https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.5.0-cp27-none-linux_x86_64.whl
```
it sounds like that it is installed correct, after installation it shows that:
```
Collecting setuptools (from protobuf>=3.4.0->tensorflow-gpu==1.5.0)
  Using cached setuptools-38.5.1-py2.py3-none-any.whl
Requirement already up-to-date: funcsigs>=1; python_version < "3.3" in ./anaconda2/lib/python2.7/site-packages (from mock>=2.0.0->tensorflow-gpu==1.5.0)
Requirement already up-to-date: pbr>=0.11 in ./anaconda2/lib/python2.7/site-packages (from mock>=2.0.0->tensorflow-gpu==1.5.0)
Installing collected packages: numpy, tensorflow-gpu, setuptools
  Found existing installation: numpy 1.14.0
    Uninstalling numpy-1.14.0:
      Successfully uninstalled numpy-1.14.0
  Found existing installation: tensorflow-gpu 1.5.0
    Uninstalling tensorflow-gpu-1.5.0:
      Successfully uninstalled tensorflow-gpu-1.5.0
  Found existing installation: setuptools 38.4.0
    Uninstalling setuptools-38.4.0:
      Successfully uninstalled setuptools-38.4.0
Successfully installed numpy-1.14.1 setuptools-38.5.1 tensorflow-gpu-1.5.0
```
Now Im tryin to import tensorflow and i receive the following error:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/alireza/anaconda2/lib/python2.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/home/alireza/anaconda2/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/alireza/anaconda2/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/alireza/anaconda2/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/alireza/anaconda2/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/alireza/anaconda2/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

Any help or suggestion on what should i do??

**Comment by impanyu** [comment]
It seems you still need to install cuda9.0

**Comment by isalirezag** [comment]
@impanyu I already have cuda 8, isnot that enough?

**Comment by impanyu** [comment]
I think you should upgrade to  cuda9.0

**Comment by isalirezag** [comment]
I will try that to see if it works...
