### ISSUE TITLE
Cannot feed value of shape (64, 25, 9) for Tensor 'Placeholder:0', which has shape '(?, 25, 25)'

### ISSUE THREAD

**Issue by deerdodo** [tensorflow/tensorflow#17381]
i am trying to train my RNN-LSTM model in python 3.5, this is my code and my dataset is a 3D accelerometer dataset

```
X = tf.placeholder(tf.float32, [None, config.n_steps, config.n_inputs])
Y = tf.placeholder(tf.float32, [None, config.n_classes])

with tf.Session() as sess:
    tf.global_variables_initializer().run()

    for epoch in range(training_epochs):
        cost_history = np.empty(shape=[0],dtype=float)
        for b in range(total_batches):
            offset = (b * config.batch_size) % (train_y.shape[0] - config.batch_size)
            batch_x = train_x[offset:(offset + config.batch_size), :, :]
            batch_y = train_y[offset:(offset + config.batch_size), :]

            print ("batch_x shape =",batch_x.shape)
            print ("batch_y shape =",batch_y.shape)

            _, c = sess.run([optimizer, cost],feed_dict={X: batch_x, Y : batch_y})
            cost_history = np.append(cost_history,c)
        loss_over_time[epoch] = np.mean(cost_history)
```
but it gives me the following error

```
Traceback (most recent call last):
  File "C:\Users\hp\Downloads\Deep-Learning-for-Human-Activity-Recognition-master\ModelCreation\RNN\FFLSTM\fflstm.py", line 250, in <module>
    _, c = sess.run([optimizer, cost],feed_dict={X: batch_x, Y : batch_y})
  File "C:\Users\hp\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\client\session.py", line 895, in run
    run_metadata_ptr)
  File "C:\Users\hp\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\client\session.py", line 1100, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (64, 25, 9) for Tensor 'Placeholder:0', which has shape '(?, 25, 25)'

```
and this is the shapes of my dataset
```
n_inputs len(X_train[0][0]) 25
batch_x shape = (64, 25, 9)
batch_y shape = (64, 2)
X <tf.Tensor 'Placeholder:0' shape=(?, 25, 25) dtype=float32>
Y <tf.Tensor 'Placeholder_1:0' shape=(?, 2) dtype=float32>
```

**Comment by r0mainK** [comment]
Well its kinda self explanatory, the placeholder `X` expected you to feed it tensors of shape (n, 25, 25) where n is (I guess) 64 in your case, but you fed it tensors of shape (n, 25, 9). I'm guessing you did a mistake while creating the `train_x` variable.

**Comment by rohan100jain** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
