### ISSUE TITLE
ValueError: features should be a dictionary of `Tensor`s. Given type: <class 'NoneType'>

### ISSUE THREAD

**Issue by luto65** [tensorflow/tensorflow#17403]
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacBook Pro, MacOs High Sierra 10.13.3
- **TensorFlow installed from (source or binary)**:binary
- **TensorFlow version (use command below)**: v1.4.0-rc1-11-g130a514 1.4.0
- **Python version**: 3.6.1
- **Bazel version (if compiling from source)**:n.a.
- **GCC/Compiler version (if compiling from source)**: n.a.
- **CUDA/cuDNN version**: n.a.
- **GPU model and memory**:n.a.
- **Exact command to reproduce**: 
git clone https://github.com/tensorflow/models
cd models/samples/core/get_started/
python premade_estimator.py

Darwin ZZZM30774783A 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64
Mac OS X 10.13.3
== are we in docker =============================================
No
== compiler =====================================================
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
== uname -a =====================================================
Darwin ZZZM30774783A 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64
== check pips ===================================================
numpy (1.12.1)
protobuf (3.4.0)
tensorflow (1.4.0)
tensorflow-tensorboard (0.4.0rc2)
== check for virtualenv =========================================
True
== tensorflow import ============================================
tf.VERSION = 1.4.0
tf.GIT_VERSION = v1.4.0-rc1-11-g130a514
tf.COMPILER_VERSION = v1.4.0-rc1-11-g130a514
Sanity check: array([1], dtype=int32)
/Users/xxx/tensorflow/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
== env ==========================================================
LD_LIBRARY_PATH is unset
DYLD_LIBRARY_PATH is unset

== nvidia-smi ===================================================
== cuda libs  ===================================================

### Describe the problem
I am following the tutorial https://www.tensorflow.org/get_started/premade_estimators and I get the following error

INFO:tensorflow:Loss for final step: 4.43589.
Traceback (most recent call last):
  File "premade_estimator.py", line 88, in <module>
    tf.app.run(main)
  File "/Users/d069082/tensorflow/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "premade_estimator.py", line 57, in main
    input_fn=lambda:iris_data.eval_input_fn(test_x, test_y,
  File "/Users/d069082/tensorflow/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 355, in evaluate
    name=name)
  File "/Users/d069082/tensorflow/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 810, in _evaluate_model
    features, labels, model_fn_lib.ModeKeys.EVAL, self.config)
  File "/Users/d069082/tensorflow/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 694, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/Users/d069082/tensorflow/lib/python3.6/site-packages/tensorflow/python/estimator/canned/dnn.py", line 334, in _model_fn
    config=config)
  File "/Users/d069082/tensorflow/lib/python3.6/site-packages/tensorflow/python/estimator/canned/dnn.py", line 167, in _dnn_model_fn
    'Given type: {}'.format(type(features)))
ValueError: features should be a dictionary of `Tensor`s. Given type: <class 'NoneType'>

**Comment by cy89** [comment]
@luto65 looking at the backtracke and source a little, it seems like "features" in _evaluate_mode is turning out to be None. That comes from a call to _get_features_and_labels_from_input_fn. 

So if you wouldn't mind a little bit of Python debugging, can you please check that the input_fun you're passing in is sane?

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by cy89** [comment]
Closing for lack of response; please reopen if you've got more information.
