### ISSUE TITLE
TOCO API fail with the basic Python example

### ISSUE THREAD

**Issue by alexst07** [tensorflow/tensorflow#17413]
### System information
- **OS Platform and Distribution (Linux Ubuntu 17.10)**:
- **TensorFlow installed from (pip3)**:
- **TensorFlow version (1.6)**:
- **Python 3.6.3**: 

### Describe the problem
TOCO API fail with the basic Python example:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/lite/toco/g3doc/python_api.md#example-2-export-with-variables

### Error
```
Traceback (most recent call last):
  File "fb.py", line 15, in <module>
    sess, sess.graph_def, map(canonical_name, out_tensors))
  File "/home/alex/.local/lib/python3.6/site-packages/tensorflow/python/framework/graph_util_impl.py", line 232, in convert_variables_to_constants
    inference_graph = extract_sub_graph(input_graph_def, output_node_names)
  File "/home/alex/.local/lib/python3.6/site-packages/tensorflow/python/framework/graph_util_impl.py", line 176, in extract_sub_graph
    nodes_to_keep = _bfs_for_reachable_nodes(dest_nodes, name_to_input_name)
  File "/home/alex/.local/lib/python3.6/site-packages/tensorflow/python/framework/graph_util_impl.py", line 140, in _bfs_for_reachable_nodes
    next_to_visit = target_nodes[:]
TypeError: 'map' object is not subscriptable
```

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by bholota** [comment]
Try `list(map(canonical_name, out_tensors)))`

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
It has been 45 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
It has been 62 days with no activity and the `awaiting response` label was assigned. Is this still an issue?
