### ISSUE TITLE
Retrain Inception Image

### ISSUE THREAD

**Issue by trungdn** [tensorflow/tensorflow#1743]
I'm running Tensorflow on Ubuntu 14.04
newest version 0.7.1

when I try to retrain by using this command

python retrain.py --image_dir ~/flower

After it extract bottleneck, it shows that errors

Traceback (most recent call last):
  File "retrain.py", line 824, in <module>
    tf.app.run()
  File "/home/trungdn/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/platform/default/_app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "retrain.py", line 751, in main
    bottleneck_tensor)
  File "retrain.py", line 673, in add_final_training_ops
    bottleneck_input = tf.placeholder_with_default(
**AttributeError: 'module' object has no attribute 'placeholder_with_default'**

Name: tensorflow
Version: 0.7.1
Location: /home/trungdn/tensorflow/lib/python2.7/site-packages
Requires: numpy, protobuf, wheel, six

I tried to git pull with update repo but it doesn't help. Thanks

**Comment by vrv** [comment]
retrain.py at HEAD now uses code that is only available after 0.7.1.  Try installing the pip nightly or use retrain.py at the r0.7 branch.
