### ISSUE TITLE
train priblem

### ISSUE THREAD

**Issue by cyqluowang** [tensorflow/tensorflow#17464]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Distributor ID: 
CentOS
Description:    CentOS Linux release 7.2.1511 (Core) 
Release:        7.2.1511
- **TensorFlow installed from (source or binary)**:pip
- **TensorFlow version (use command below)**:1.5.0
- **Python version**: Python 2.7.5
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:no
- **GPU model and memory**:no
- **Exact command to reproduce**:

ps
```
2018-03-06 11:13:09.816655: I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:324] Started server with target: grpc://localhost:2222
2018-03-06 11:14:56.902071: W tensorflow/core/framework/op_kernel.cc:1198] Not found: checkpoint/model.ckpt-1_temp_9e8396c2f6d04e91ad3c3fbc194a9f70; No such file or directory
2018-03-06 11:14:56.902071: W tensorflow/core/framework/op_kernel.cc:1198] Not found: checkpoint/model.ckpt-1_temp_9e8396c2f6d04e91ad3c3fbc194a9f70; No such file or directory
```

work:
```
2018-03-06 11:10:24.342583: I tensorflow/core/distributed_runtime/master_session.cc:1017] Start master session 592fd1b6a4409f07 with config: gpu_options { allow_growth: true } allow_soft_placement: true
Exception in thread QueueRunnerThread-dummy_queue-sync_token_q_EnqueueMany:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 765, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/queue_runner_impl.py", line 266, in _run
    coord.request_stop(e)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/coordinator.py", line 211, in request_stop
    six.reraise(*sys.exc_info())
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/queue_runner_impl.py", line 250, in _run
    enqueue_callable()
  File "/usr/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1251, in _single_operation_run
    self._session, None, {}, [], target_list, status, None)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
CancelledError: Step was cancelled by an explicit call to `Session::Close()`.

Traceback (most recent call last):
  File "leave.py", line 204, in <module>
    tf.app.run()
  File "/usr/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 124, in run
    _sys.exit(main(argv))
  File "leave.py", line 195, in main
    rnn_model.global_step], feed_dict={keep_prob: FLAGS.dropout_keep_prob})
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 539, in run
    run_metadata=run_metadata)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1013, in run
    run_metadata=run_metadata)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1104, in run
    raise six.reraise(*original_exc_info)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1089, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1169, in run
    run_metadata=run_metadata))
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/basic_session_run_hooks.py", line 452, in after_run
    self._save(run_context.session, global_step)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/basic_session_run_hooks.py", line 468, in _save
    self._get_saver().save(session, self._save_path, global_step=step)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1614, in save
    raise exc
tensorflow.python.framework.errors_impl.NotFoundError: checkpoint/model.ckpt-1_temp_5d8d532077d241a38f2d79ac2ffeb9a7; No such file or directory
         [[Node: save/SaveV2 = SaveV2[dtypes=[DT_INT64], _device="/job:ps/replica:0/task:0/device:CPU:0"](save/ShardedFilename, save/SaveV2/tensor_names, save/SaveV2/shape_and_slices, global_step)]]
         [[Node: save/Identity_S445 = _HostRecv[client_terminated=false, recv_device="/job:worker/replica:0/task:0/device:CPU:0", send_device="/job:ps/replica:0/task:0/device:CPU:0", send_device_incarnation=-8763115780137487660, tensor_name="edge_111_save/Identity", tensor_type=DT_STRING, _device="/job:worker/replica:0/task:0/device:CPU:0"]()]]

Caused by op u'save/SaveV2', defined at:
  File "leave.py", line 204, in <module>
    tf.app.run()
  File "/usr/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 124, in run
    _sys.exit(main(argv))
  File "leave.py", line 184, in main
    config=set_config_proto()) as mon_sess:
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 380, in MonitoredTrainingSession
    stop_grace_period_secs=stop_grace_period_secs)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 787, in __init__
    stop_grace_period_secs=stop_grace_period_secs)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 511, in __init__
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 972, in __init__
    _WrappedSession.__init__(self, self._create_session())
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 977, in _create_session
    return self._sess_creator.create_session()
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 668, in create_session
    self.tf_sess = self._session_creator.create_session()
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 431, in create_session
    self._scaffold.finalize()
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 210, in finalize
    self._saver = training_saver._get_saver_or_default()  # pylint: disable=protected-access
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 821, in _get_saver_or_default
    saver = Saver(sharded=True, allow_empty=True)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1239, in __init__
    self.build()
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1248, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1284, in _build
    build_save=build_save, build_restore=build_restore)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 756, in _build_internal
    save_tensor = self._AddShardedSaveOps(filename_tensor, per_device)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 382, in _AddShardedSaveOps
    return self._AddShardedSaveOpsForV2(filename_tensor, per_device)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 356, in _AddShardedSaveOpsForV2
    sharded_saves.append(self._AddSaveOps(sharded_filename, saveables))
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 297, in _AddSaveOps
    save = self.save_op(filename_tensor, saveables)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 240, in save_op
    tensors)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1174, in save_v2
    shape_and_slices=shape_and_slices, tensors=tensors, name=name)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3160, in create_op
    op_def=op_def)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1625, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

NotFoundError (see above for traceback): checkpoint/model.ckpt-1_temp_5d8d532077d241a38f2d79ac2ffeb9a7; No such file or directory
         [[Node: save/SaveV2 = SaveV2[dtypes=[DT_INT64], _device="/job:ps/replica:0/task:0/device:CPU:0"](save/ShardedFilename, save/SaveV2/tensor_names, save/SaveV2/shape_and_slices, global_step)]]
         [[Node: save/Identity_S445 = _HostRecv[client_terminated=false, recv_device="/job:worker/replica:0/task:0/device:CPU:0", send_device="/job:ps/replica:0/task:0/device:CPU:0", send_device_incarnation=-8763115780137487660, tensor_name="edge_111_save/Identity", tensor_type=DT_STRING, _device="/job:worker/replica:0/task:0/device:CPU:0"]()]]
```

**Comment by cyqluowang** [comment]
```
   with tf.train.MonitoredTrainingSession(master=server.target,
                                                   is_chief=is_chief,
                                                   checkpoint_dir="checkpoint/",
                                                   hooks=hooks,
                                                   save_checkpoint_secs=60,
                                                   config=set_config_proto()) as mon_sess:
```

**Comment by cyqluowang** [comment]
The development environment for the MAC can run. On the server, if the amount of data is relatively small, it can run, and the data volume is too large to fail.

**Comment by cyqluowang** [comment]
Even if all the data is cleared, the rerun is a failure.

**Comment by AlphaSue** [comment]
have you solved this problem? @cyqluowang

**Comment by asimshankar** [comment]
From the error message `NotFoundError (see above for traceback): checkpoint/model.ckpt-1_temp_5d8d532077d241a38f2d79ac2ffeb9a7; No such file or directory` it seems that the workers are having trouble writing to the `checkpoint` directory.

It is possible that the parent directory where checkpoints are to be written is either not accessible or is being removed while the training is in process?

**Comment by cyqluowang** [comment]
ok

**Comment by asimshankar** [comment]
Closing since I interpreted your last comment to imply that my hunch was correct. Please feel free to reopen if I was mistaken. Thanks.

**Comment by HandsomeHans** [comment]
i got a same error when doing sync training in distribution environment.
Sys: Linux 14.04
TF: 1.6.0

`Exception in thread QueueRunnerThread-dummy_queue-sync_token_q_EnqueueMany:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/queue_runner_impl.py", line 268, in _run
    coord.request_stop(e)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/coordinator.py", line 213, in request_stop
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/queue_runner_impl.py", line 252, in _run
    enqueue_callable()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1259, in _single_operation_run
    None)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
CancelledError: Step was cancelled by an explicit call to `Session::Close()`.
`

**and part of my codes is:**

`class _LoggerHook(tf.train.SessionRunHook):
                def begin(self):
                    self._step = 0
                    self._start_time = time.time()
                    self._total_loss = 0
            
                def before_run(self, run_context):
                    self._step += 1
                    return tf.train.SessionRunArgs(loss)
            
                def after_run(self, run_context, run_values):
                    loss_value = run_values.results
                    self._total_loss += loss_value
                    if self._step % FLAGS.log_frequency == 0:
                        current_time = time.time()
                        duration = current_time - self._start_time
                        self._start_time = current_time
                        if self._step==0:
                            avg_loss = loss_value
                        else:
                            avg_loss = self._total_loss/self._step
                        eg_per_sec = FLAGS.log_frequency * FLAGS.batch_size / duration
                        sec_per_batch = float(duration / FLAGS.log_frequency)
                        print('%s: training step %d cur loss = %.4f avg loss = %.4f (%.1f images/sec %.3f sec/batch)'
                              % (datetime.now(), self._step, loss_value, avg_loss, eg_per_sec, sec_per_batch))
            
            all_hooks=[tf.train.NanTensorHook(loss), tf.train.StopAtStepHook(last_step=FLAGS.max_steps), _LoggerHook()]
            if FLAGS.issync:
                all_hooks.append(sync_replicas_hook)
            if FLAGS.debug:
                all_hooks.append(tfdbg.LocalCLIDebugHook(ui_type='curses'))
            if FLAGS.finetune:
                print('Finetune from %s'%FLAGS.finetune)
                saver = tf.train.Saver()
            config = tf.ConfigProto(log_device_placement=FLAGS.log_device_placement)
            config.gpu_options.allow_growth=True
            with tf.train.MonitoredTrainingSession(
                    master=server.target,
                    is_chief=(FLAGS.task_index == 0),
                    checkpoint_dir=FLAGS.model_dir,
                    hooks=all_hooks,
                    config=config,
                    save_summaries_steps=100,
                    save_summaries_secs=None,
                    log_step_count_steps=None) as sess:
                if FLAGS.finetune:
                    print('Load Pretrained model')
                    ckpt = tf.train.get_checkpoint_state(FLAGS.finetune)
                    if ckpt and ckpt.model_checkpoint_path:
                        saver.restore(sess, ckpt.model_checkpoint_path)
                    print('-------------------------')
                while not sess.should_stop():
                    sess.run(train_op)`

**Comment by tobegit3hub** [comment]
Got the same error log of @HandsomeHans  in `TensorFlow 1.8.0`.
