### ISSUE TITLE
ValueError: No attr named '_XlaCompile' in name: "Tile_1"，please help me

### ISSUE THREAD

**Issue by lxwithgod** [tensorflow/tensorflow#17469]
/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gradients_impl.py:96: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gradients_impl.py", line 348, in _MaybeCompile
    xla_compile = op.get_attr("_XlaCompile")
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 2003, in get_attr
    raise ValueError("No attr named '" + name + "' in " + str(self._node_def))
ValueError: No attr named '_XlaCompile' in name: "Tile_1"
op: "Tile"
input: "Const_1"
input: "Tile_1/multiples"
attr {
  key: "T"
  value {
    type: DT_FLOAT
  }
}
attr {
  key: "Tmultiples"
  value {
    type: DT_INT32
  }
}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lx/PycharmProjects/chinese/img/model/tfDect_tiny.py", line 342, in <module>
    tfd = TFDect(logdir=".")
  File "/home/lx/PycharmProjects/chinese/img/model/tfDect_tiny.py", line 293, in __init__
    global_step=self.global_step)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/optimizer.py", line 343, in minimize
    grad_loss=grad_loss)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/optimizer.py", line 414, in compute_gradients
    colocate_gradients_with_ops=colocate_gradients_with_ops)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gradients_impl.py", line 581, in gradients
    grad_scope, op, func_call, lambda: grad_fn(op, *out_grads))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gradients_impl.py", line 353, in _MaybeCompile
    return grad_fn()  # Exit early
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gradients_impl.py", line 581, in <lambda>
    grad_scope, op, func_call, lambda: grad_fn(op, *out_grads))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/array_grad.py", line 523, in _TileGrad
    assert isinstance(grad, ops.Tensor)
AssertionError

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by GoyalShreya** [comment]
File "D:\svn\Demystifier\completeDataExtractor\build\exe.win-amd64-3.6\tensorflow\python\framework\ops.py", line 2245, in get_attr
    "No attr named '" + name + "' in " + str(self._node_def_val))
ValueError: No attr named '_XlaCompile' in name: "cond/Reshape_1"
op: "Reshape"
input: "cond/Shape_1/Switch"
input: "cond/Reshape_1/shape"
attr {
  key: "T"
  value {
    type: DT_FLOAT
  }
}
attr {
  key: "Tshape"
  value {
    type: DT_INT32
  }
}

Tensorflow on python 3.6 is installed on windows10.
The error comes, when the following piece of code is called:
self.train_op = optimizer.minimize(loss)

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by angersson** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by prasadwork** [comment]
@lxwithgod , @GoyalShreya , Did you solve the problem? I am having an extremely similar issue.
