### ISSUE TITLE
TfLiteCameraDemo crashed on Android 8.1 with call setUseNNAPI(true)

### ISSUE THREAD

**Issue by dimitryn** [tensorflow/tensorflow#17506]
Hi , 
I follow steps in : https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/lite to build tensoflowlite from sources.

trying run output demo apk on Google Pixel 2   create crash :

```
03-07 06:09:44.739 22823-22837/? I/Adreno: ESXAPILOG: API logging initialized: Name = com.example.android.tflitecamerademo, PID = 22823
03-07 06:09:44.744 22823-22823/? W/linker: /data/app/com.example.android.tflitecamerademo-qSwQ-3Ztm2MtPAw8Lu3x4A==/lib/arm64/libtensorflowlite_jni.so: is missing DT_SONAME will use basename as a replacement: "libtensorflowlite_jni.so"
03-07 06:09:44.744 22823-22823/? W/System.err: TensorFlowLite: failed to load native library: dlopen failed: cannot locate symbol "_ZN6tflite14getCurrentTimeEv" referenced by "/data/app/com.example.android.tflitecamerademo-qSwQ-3Ztm2MtPAw8Lu3x4A==/lib/arm64/libtensorflowlite_jni.so"...
03-07 06:09:44.745 22823-22823/? W/linker: /data/app/com.example.android.tflitecamerademo-qSwQ-3Ztm2MtPAw8Lu3x4A==/lib/arm64/libtensorflowlite_jni.so: is missing DT_SONAME will use basename as a replacement: "libtensorflowlite_jni.so"
03-07 06:09:44.745 22823-22823/? W/System.err: TensorFlowLite: failed to load native library: dlopen failed: cannot locate symbol "_ZN6tflite14getCurrentTimeEv" referenced by "/data/app/com.example.android.tflitecamerademo-qSwQ-3Ztm2MtPAw8Lu3x4A==/lib/arm64/libtensorflowlite_jni.so"...
03-07 06:09:44.745 22823-22823/? E/zygote64: No implementation found for long org.tensorflow.lite.NativeInterpreterWrapper.createErrorReporter(int) (tried Java_org_tensorflow_lite_NativeInterpreterWrapper_createErrorReporter and Java_org_tensorflow_lite_NativeInterpreterWrapper_createErrorReporter__I)
03-07 06:09:44.745 22823-22823/? D/AndroidRuntime: Shutting down VM
03-07 06:09:44.746 22823-22823/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.example.android.tflitecamerademo, PID: 22823
                                                   java.lang.UnsatisfiedLinkError: No implementation found for long org.tensorflow.lite.NativeInterpreterWrapper.createErrorReporter(int) (tried Java_org_tensorflow_lite_NativeInterpreterWrapper_createErrorReporter and Java_org_tensorflow_lite_NativeInterpreterWrapper_createErrorReporter__I)
                                                       at org.tensorflow.lite.NativeInterpreterWrapper.createErrorReporter(Native Method)
                                                       at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:48)
                                                       at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:77)
                                                       at com.example.android.tflitecamerademo.ImageClassifier.<init>(ImageClassifier.java:87)
                                                       at com.example.android.tflitecamerademo.ImageClassifierFloatIntel.<init>(ImageClassifierFloatIntel.java:50)
                                                       at com.example.android.tflitecamerademo.CameraActivity.testImage(CameraActivity.java:71)
                                                       at com.example.android.tflitecamerademo.CameraActivity.onCreate(CameraActivity.java:36)
                                                       at android.app.Activity.performCreate(Activity.java:6999)
                                                       at android.app.Activity.performCreate(Activity.java:6990)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
                                                       at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
                                                       at android.os.Handler.dispatchMessage(Handler.java:106)
                                                       at android.os.Looper.loop(Looper.java:164)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6494)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

Build command :  bazel build --cxxopt=--std=c++11 //tensorflow/contrib/lite/java/demo/app/src/main:TfLiteCameraDemo --config=android_arm64 --cpu=arm64-v8a --fat_apk_cpu=arm64-v8a

Tensorflow WORKSPACE file changes:

```
# Uncomment and update the paths in these entries to build the Android demo.
android_sdk_repository(
    name = "androidsdk",
   api_level = 27,
   # Ensure that you have the build_tools_version below installed in the
    # SDK manager as it updates periodically.
    build_tools_version = "27.0.3",
    # Replace with path to Android SDK on your system
    path = "/home/XXX/Android/Sdk/",
)

android_ndk_repository(
    name="androidndk",
    path="/home/dnozik/Code/Tensorflow/android-ndk-r14b/",
    # This needs to be 14 or higher to compile TensorFlow.
#    # Please specify API level to >= 21 to build for 64-bit
#    # archtectures or the Android NDK will automatically select biggest
#    # API level that it supports without notice.
#    # Note that the NDK version is not the API level.
    api_level=27)
```

Symbols:
XXX@XXX-VirtualBox:~/Code$ nm -S libtensorflowlite_jni.so 
nm: libtensorflowlite_jni.so: no symbols

Thanks for help.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by dimitryn** [comment]
Have I written custom code
1.Add call to SetUseNNAPI(true) inside ImageClassifier.java constructor
2.comment on  ` url 'https://google.bintray.com/tensorflow'  in  tensorflow-master\tensorflow\contrib\lite\java\demo\app\build.gradle    -  It load old tensorflow lite library

OS Platform and Distribution
**_Ubuntu 17.10_**
TensorFlow installed from
**Github**
TensorFlow version
**Master Clone 3 days ago**
Bazel version 
**0.10.1**
CUDA/cuDNN version
**No**  VM  VirtualBox Machine
GPU model and memory
**No** VM  VirtualBox Machine
Exact command to reproduce

 **bazel build --cxxopt=--std=c++11 //tensorflow/contrib/lite/java/demo/app/src/main:TfLiteCameraDemo --config=android_arm64 --cpu=arm64-v8a --fat_apk_cpu=arm64-v8a**

**Comment by andrehentz** [comment]
A fix for this should appear soon. It amounts to adding  "duration_utils_jni.cc", around line 14 of java/src/main/native/BUILD

**Comment by dimitryn** [comment]
Hi , 
after changing BUILD file with duration_utils_jni.cc I have new issue:

```
3-10 01:11:14.171 15236-15236/? W/System.err: java.io.FileNotFoundException: labels_imagenet_slim.txt
03-10 01:11:14.171 15236-15236/? W/System.err:     at android.content.res.AssetManager.openAsset(Native Method)
03-10 01:11:14.171 15236-15236/? W/System.err:     at android.content.res.AssetManager.open(AssetManager.java:374)
03-10 01:11:14.171 15236-15236/? W/System.err:     at android.content.res.AssetManager.open(AssetManager.java:348)
03-10 01:11:14.171 15236-15236/? W/System.err:     at com.example.android.tflitecamerademo.ImageClassifier.loadLabelList(ImageClassifier.java:146)
03-10 01:11:14.171 15236-15236/? W/System.err:     at com.example.android.tflitecamerademo.ImageClassifier.<init>(ImageClassifier.java:89)
03-10 01:11:14.171 15236-15236/? W/System.err:     at com.example.android.tflitecamerademo.ImageClassifierFloatIntel.<init>(ImageClassifierFloatIntel.java:50)
03-10 01:11:14.171 15236-15236/? W/System.err:     at com.example.android.tflitecamerademo.CameraActivity.testImage(CameraActivity.java:71)
03-10 01:11:14.171 15236-15236/? W/System.err:     at com.example.android.tflitecamerademo.CameraActivity.onCreate(CameraActivity.java:36)
03-10 01:11:14.171 15236-15236/? W/System.err:     at android.app.Activity.performCreate(Activity.java:6975)
03-10 01:11:14.171 15236-15236/? W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
03-10 01:11:14.171 15236-15236/? W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2779)
03-10 01:11:14.171 15236-15236/? W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2904)
```
Assets folder do contain labels_imagenet_slim.txt but in BUILD file there is : 

```
    assets = [
        "@tflite_mobilenet//:labels.txt",
        "@tflite_mobilenet//:mobilenet_quant_v1_224.tflite",
    ],
```
Or something I missing ?!

**Comment by dimitryn** [comment]
Thanks. It worked.
One small issue question : How can I change (syntax ...) BUILD file to build apk with my assets   that I put  in assets folder.

```
android_binary(
    name = "TfLiteCameraDemo",
    srcs = glob(["java/**/*.java"]),
    assets = [
        "@tflite_mobilenet//:labels.txt",
        "@tflite_mobilenet//:mobilenet_quant_v1_224.tflite",
    ],
    assets_dir = "",
    custom_package = "com.example.android.tflitecamerademo",
    manifest = "AndroidManifest.xml",
    nocompress_extensions = [
        ".tflite",
    ],
    resource_files = glob(["res/**"]),
    # In some platforms we don't have an Android SDK/NDK and this target
    # can't be built. We need to prevent the build system from trying to
    # use the target in that case.
    tags = ["manual"],
    deps = [
        "//tensorflow/contrib/lite/java:tensorflowlite",
        "//tensorflow/contrib/lite/java/src/testhelper/java/org/tensorflow/lite:testhelper",
        "@androidsdk//com.android.support:support-v13-25.2.0",
        "@androidsdk//com.android.support:support-v4-25.2.0",
    ],
)
```

Thanks

**Comment by dimitryn** [comment]
P.S Without call to setUseNNAPI(true) sample crash also on Android 8.1

**Comment by dimitryn** [comment]
Another log . I created activity without camera . passing frame from assets.

```
03-17 16:52:40.343 5284-5310/? E/ReloadingLock: Finalizing LOCKED Token[shortcuts 2018-03-17 16:51:55.915]
03-17 16:52:45.329 5284-12571/? I/EventLogSendingHelper: Sending log events.
03-17 16:52:47.094 12545-12545/? I/MemoryIntArray: created from parcel MemoryIntArray@243249334 mMemoryAddr=543454302208 mFd=43
03-17 16:52:47.097 761-4939/? D/audio_hw_primary: enable_snd_device: snd_device(2: speaker)
03-17 16:52:47.097 761-4939/? D/audio_route: Apply path: speaker
03-17 16:52:47.098 761-4939/? D/ACDB-LOADER: ACDB -> send_audio_cal, acdb_id = 15, path = 0, app id = 0x11130, sample rate = 48000
03-17 16:52:47.098 761-4939/? D/ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_GAIN_DEP_STEP_TABLE, vol index 0
03-17 16:52:47.099 761-4939/? D/ACDB-LOADER: ACDB -> GET_AFE_TOPOLOGY_ID for adcd_id 15, Topology Id 112fc
                                             
                                             [ 03-17 16:52:47.099   761: 4939 D/         ]
                                             Failed to fetch the lookup information of the device 0000000F 
03-17 16:52:47.099 761-4939/? D/ACDB-LOADER: Error: ACDB AFE returned = -19
03-17 16:52:47.099 761-4939/? D/audio_hw_primary: enable_audio_route: usecase(1) apply and update mixer path: low-latency-playback speaker
03-17 16:52:47.099 761-4939/? D/audio_route: Apply path: low-latency-playback speaker
03-17 16:52:47.103 821-821/? D/android.hardware.power@1.2-service.wahoo-libperfmgr: AUDIO STREAMING ON
03-17 16:52:47.104 12545-12545/? D/TfLiteCameraDemo: Created a Tensorflow Lite Image Classifier.
03-17 16:52:47.111 12545-12545/? D/TfLiteCameraDemo: Timecost to put values into ByteBuffer: 4
03-17 16:52:47.127 1192-4006/? W/InputDispatcher: channel 'a917b4d com.example.android.tflitecamerademo/com.example.android.tflitecamerademo.TestLite (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
03-17 16:52:47.128 1192-4006/? E/InputDispatcher: channel 'a917b4d com.example.android.tflitecamerademo/com.example.android.tflitecamerademo.TestLite (server)' ~ Channel is unrecoverably broken and will be disposed!
03-17 16:52:47.128 1192-5238/? I/WindowManager: WIN DEATH: Window{a917b4d u0 com.example.android.tflitecamerademo/com.example.android.tflitecamerademo.TestLite}
03-17 16:52:47.128 1192-5238/? W/InputDispatcher: Attempted to unregister already unregistered input channel 'a917b4d com.example.android.tflitecamerademo/com.example.android.tflitecamerademo.TestLite (server)'
03-17 16:52:47.128 1192-1203/? I/ActivityManager: Process com.example.android.tflitecamerademo (pid 12545) has died: fore TOP 
03-17 16:52:47.128 1192-1223/? W/libprocessgroup: kill(-12545, 9) failed: No such process
03-17 16:52:47.128 1192-1223/? I/libprocessgroup: Successfully killed process cgroup uid 10136 pid 12545 in 0ms
03-17 16:52:47.129 1192-1203/? W/ActivityManager: Force removing ActivityRecord{52cc38f u0 com.example.android.tflitecamerademo/.TestLite t16}: app died, no saved state
03-17 16:52:47.129 742-742/? I/Zygote: Process 12545 exited cleanly (1)
03-17 16:52:47.137 761-4939/? D/audio_hw_primary: out_write: retry previous failed cal level set
03-17 16:52:47.138 821-821/? D/android.hardware.power@1.2-service.wahoo-libperfmgr: AUDIO STREAMING OFF
03-17 16:52:47.145 1192-1240/? W/ActivityManager: setHasOverlayUi called on unknown pid: 12545
03-17 16:52:47.159 5167-5757/? W/GCoreFlp: No location to return for getLastLocation()
03-17 16:52:47.164 600-600/? D/SurfaceFlinger: duplicate layer name: changing com.google.android.apps.nexuslauncher/com.google.android.apps.nexuslauncher.NexusLauncherActivity to com.google.android.apps.nexuslauncher/com.google.android.apps.nexuslauncher.NexusLauncherActivity#1
03-17 16:52:47.181 4441-4441/? I/WallpaperService: engine resumed
03-17 16:52:47.188 863-896/? D/CHRE: @ 100126.609: +: id 10, otherClientPresent 1, mode 3
03-17 16:52:47.189 863-896/? D/CHRE: @ 100126.609: [ImuCal] Dynamic sensor configuration: high-performance.
03-17 16:52:47.190 863-896/? D/CHRE: @ 100126.609: sensorType 9 allowed 1: mergedMode 3, otherClientPresent 1
03-17 16:52:47.190 863-896/? D/CHRE: @ 100126.609: sensorType 12 allowed 1: mergedMode 3, otherClientPresent 1
03-17 16:52:47.191 863-896/? D/CHRE: @ 100126.617: sensorType 14 allowed 0: mergedMode 3, otherClientPresent 0
03-17 16:52:47.209 5284-5284/? W/SessionLifecycleManager: Handover failed. Creating new session controller.
03-17 16:52:47.213 5284-5284/? I/OptInState: There is a new client and it does not support opt-in. Dropping request.
03-17 16:52:47.228 5284-12293/? W/LocationOracle: No location history returned by ContextManager
03-17 16:52:47.232 5284-5284/? I/MicroDetectionWorker: #updateMicroDetector [detectionMode: [mDetectionMode: [1]]]
03-17 16:52:47.233 5284-5284/? I/MicroDetectionWorker: #startMicroDetector [speakerMode: 0]
03-17 16:52:47.237 5167-5757/? W/GCoreFlp: No location to return for getLastLocation()
03-17 16:52:47.238 5284-12293/? I/MicroRecognitionRunner: Starting detection.
03-17 16:52:47.238 5284-12317/? I/MicrophoneInputStream: mic_starting com.google.android.apps.gsa.speech.audio.af@b0d47b1
03-17 16:52:47.241 761-761/? W/DeviceHAL: Device 0xf1244000 open_input_stream: Invalid argument
03-17 16:52:47.241 5167-5757/? W/GCoreFlp: No location to return for getLastLocation()
03-17 16:52:47.242 871-12574/? I/AudioFlinger: AudioFlinger's thread 0xede24a80 tid=12574 ready to run
03-17 16:52:47.245 5284-5284/? I/MicroDetectionWorker: onReady
03-17 16:52:47.249 871-4028/? I/SoundTriggerHwService::Module: onCallbackEvent no clients
03-17 16:52:47.249 5284-12317/? I/MicrophoneInputStream: mic_started com.google.android.apps.gsa.speech.audio.af@b0d47b1
03-17 16:52:47.250 761-12575/? D/sound_trigger_platform: platform_stdev_check_and_update_concurrency: concurrency active 0, tx 1, rx 0, concurrency session_allowed 0
03-17 16:52:47.250 761-12575/? D/audio_hw_primary: enable_snd_device: snd_device(75: voice-rec-mic)
03-17 16:52:47.250 761-12575/? D/audio_route: Apply path: voice-rec-mic
03-17 16:52:47.250 821-821/? D/android.hardware.power@1.2-service.wahoo-libperfmgr: AUDIO STREAMING ON
03-17 16:52:47.253 761-12575/? D/ACDB-LOADER: ACDB -> send_audio_cal, acdb_id = 41, path = 1, app id = 0x11132, sample rate = 48000
03-17 16:52:47.253 761-12575/? D/ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_GAIN_DEP_STEP_TABLE, vol index 0
                                              
                                              [ 03-17 16:52:47.253   761:12575 D/         ]
                                              Failed to fetch the lookup information of the device 00000029 
03-17 16:52:47.253 761-12575/? E/ACDB-LOADER: Error: ACDB AudProc vol returned = -19
03-17 16:52:47.253 761-12575/? D/ACDB-LOADER: ACDB -> GET_AFE_TOPOLOGY_ID for adcd_id 41, Topology Id 112fb
                                              
                                              [ 03-17 16:52:47.253   761:12575 D/         ]
                                              Failed to fetch the lookup information of the device 00000029 
03-17 16:52:47.253 761-12575/? D/ACDB-LOADER: Error: ACDB AFE returned = -19
03-17 16:52:47.253 761-12575/? D/audio_hw_primary: enable_audio_route: usecase(9) apply and update mixer path: audio-record
03-17 16:52:47.253 761-12575/? D/audio_route: Apply path: audio-record
03-17 16:52:47.265 5167-5757/? W/GCoreFlp: No location to return for getLastLocation()
03-17 16:52:47.265 1192-1203/? I/WifiService: acquireWifiLock uid=10037 lockMode=2
03-17 16:52:47.268 5167-12388/? I/Places: ?: Couldn't find platform key file.
03-17 16:52:47.271 5167-5757/? W/GCoreFlp: No location to return for getLastLocation()
03-17 16:52:47.275 1192-1203/? I/WifiService: releaseWifiLock uid=10037
03-17 16:52:47.283 8925-8955/? W/PlayCommon: [77] PlayEventLogger.getAuthToken: No account for auth token provided
03-17 16:52:47.285 5167-5757/? W/GCoreFlp: No location to return for getLastLocation()
03-17 16:52:47.286 5167-7917/? I/Places: ?: PlacesBleScanner start() with priority 2
03-17 16:52:47.286 5167-7917/? I/PlaceInferenceEngine: [anon] Changed inference mode: 1
03-17 16:52:47.286 5167-5757/? W/GCoreFlp: No location to return for getLastLocation()
03-17 16:52:47.288 8925-8955/? E/PlayCommon: [77] PlayEventLogger.uploadLog: Failed to connect to server: java.net.UnknownHostException: Unable to resolve host "play.googleapis.com": No address associated with hostname
03-17 16:52:47.290 5167-5757/? W/GCoreFlp: No location to return for getLastLocation()
03-17 16:52:47.296 5167-5757/? I/chatty: uid=10037(com.google.android.gms) FlpThread identical 2 lines
03-17 16:52:47.303 5167-5757/? W/GCoreFlp: No location to return for getLastLocation()
03-17 16:52:47.305 1192-11972/? I/WifiService: acquireWifiLock uid=10037 lockMode=2
03-17 16:52:47.308 821-821/? D/android.hardware.power@1.2-service.wahoo-libperfmgr: AUDIO STREAMING OFF
03-17 16:52:47.311 1192-5238/? I/WifiService: releaseWifiLock uid=10037
03-17 16:52:47.320 5167-11613/? I/Places: ?: Couldn't find platform key file.
03-17 16:52:47.325 5167-7917/? I/Places: ?: PlacesBleScanner start() with priority 2
03-17 16:52:47.326 5167-5757/? W/GCoreFlp: No location to return for getLastLocation()
03-17 16:52:47.326 5284-5284/? I/MicroDetectionWorker: onReady
03-17 16:52:47.330 5167-5757/? W/GCoreFlp: No location to return for getLastLocation()
03-17 16:52:47.333 5167-7917/? I/Places: ?: PlacesBleScanner start() with priority 2
03-17 16:52:47.333 5167-7917/? I/PlaceInferenceEngine: [anon] Changed inference mode: 1
03-17 16:52:47.334 5167-5757/? W/GCoreFlp: No location to return for getLastLocation()
03-17 16:52:47.336 5167-5757/? I/chatty: uid=10037(com.google.android.gms) FlpThread identical 1 line
03-17 16:52:47.338 5167-5757/? W/GCoreFlp: No location to return for getLastLocation()
03-17 16:52:47.340 1192-11972/? I/WifiService: acquireWifiLock uid=10037 lockMode=2
03-17 16:52:47.341 5167-5757/? W/GCoreFlp: No location to return for getLastLocation()
03-17 16:52:47.344 5167-5757/? W/GCoreFlp: No location to return for getLastLocation()
03-17 16:52:47.346 1192-5238/? I/WifiService: releaseWifiLock uid=10037
03-17 16:52:47.347 5167-5757/? W/GCoreFlp: No location to return for getLastLocation()
03-17 16:52:47.352 5167-5757/? I/chatty: uid=10037(com.google.android.gms) FlpThread identical 2 lines
03-17 16:52:47.353 5167-5757/? W/GCoreFlp: No location to return for getLastLocation()
03-17 16:52:47.354 1192-11972/? I/WifiService: acquireWifiLock uid=10037 lockMode=2
03-17 16:52:47.360 5167-5757/? W/GCoreFlp: No location to return for getLastLocation()
03-17 16:52:47.361 1192-5238/? I/WifiService: releaseWifiLock uid=10037
03-17 16:52:47.363 1192-5238/? I/WifiService: acquireWifiLock uid=10037 lockMode=2
03-17 16:52:47.366 1192-5238/? I/WifiService: releaseWifiLock uid=10037
03-17 16:52:48.422 863-896/? I/CHRE: @ 100127.844: [AR_CHRE] IDLE => ON
03-17 16:52:50.322 761-761/? D/audio_hw_primary: disable_audio_route: usecase(1) reset and update mixer path: low-latency-playback speaker
03-17 16:52:50.331 761-761/? D/audio_hw_primary: disable_snd_device: snd_device(2: speaker)
03-17 16:52:51.132 1192-1192/? V/SettingsProvider: Notifying for 0: content://settings/system/screen_brightness
03-17 16:52:52.700 863-896/? D/CHRE: @ 100132.117: [NanoSensorCal] UPDATE OTC-GYRO Offset [rad/sec] | Temp [Celsius]: 0.000386, 0.000656, 0.004380 | 28.52
03-17 16:52:52.700 863-896/? D/CHRE: @ 100132.117: [NanoSensorCal] UPDATE OTC-GYRO Temp Sensitivity [rad/sec/C]: 1000000.000000, 1000000.000000, 1000000.000000
03-17 16:52:52.700 863-896/? D/CHRE: @ 100132.117: [NanoSensorCal] UPDATE OTC-GYRO Temp Intercept [rad/sec]: 0.000000, 0.000000, 0.000000
```

**Comment by xhsoldier** [comment]
any update? crash too when setUseNNAPI(true) run detection not classification.

**Comment by dimitryn** [comment]
for me it start working when I remove exit(1) from nnapi_delegate.cpp on an unsupported layer.
