### ISSUE TITLE
strange error on mac

### ISSUE THREAD

**Issue by oushuintern** [tensorflow/tensorflow#17538]
here is the code:
```
import tensorflow as tf
a =tf.Variable(tf.float32,tf.zeros([1,1]))
```
system:
osx 10.12.6
macbook pro 2017

I installed tensorflow 1.6 using the following command:
`pip install --ignore-installed --upgrade https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.6.0-py3-none-any.whl`

below is the debug info

```
/Users/long/anaconda3/envs/tf_env/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "/Users/long/dev/littleboy/tftest.py", line 2, in <module>
    a =tf.Variable(tf.float32,tf.zeros([1,1]))
  File "/Users/long/anaconda3/envs/tf_env/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 233, in __init__
    constraint=constraint)
  File "/Users/long/anaconda3/envs/tf_env/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 309, in _init_from_args
    if trainable and ops.GraphKeys.TRAINABLE_VARIABLES not in collections:
  File "/Users/long/anaconda3/envs/tf_env/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 614, in __bool__
    raise TypeError("Using a `tf.Tensor` as a Python `bool` is not allowed. "
```

**Comment by oushuintern** [comment]
should place tf.float32 behind the initial value
