### ISSUE TITLE
Tensorflow installation problem

### ISSUE THREAD

**Issue by TamouzeAssi** [tensorflow/tensorflow#17677]
Hello, 
I trie to install tensorflow on a SSH server and uisng the following command: pip install tensorflow. They give me that the installataion was Successfully done. When i execute my code i get the following error, any help will be so appreciated:
Traceback (most recent call last):
  ```
File "/gs/project/tws-462-aa/Python_directory/src/TripleArray.py", line 6, in <module>
    from config import invert
  File "/gs/project/tws-462-aa/Python_directory/src/config.py", line 5, in <module>
    import tensorflow as tf
  File "/gs/project/tws-462-aa/Python_directory/ENV2.7/lib/python2.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/gs/project/tws-462-aa/Python_directory/ENV2.7/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/gs/project/tws-462-aa/Python_directory/ENV2.7/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/gs/project/tws-462-aa/Python_directory/ENV2.7/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/gs/project/tws-462-aa/Python_directory/ENV2.7/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/gs/project/tws-462-aa/Python_directory/ENV2.7/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by /gs/project/tws-462-aa/Python_directory/ENV2.7/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

**Comment by kr-ish** [comment]
see #53

**Comment by tensorflowbutler** [comment]
Nagging Assignee @skye: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by skye** [comment]
@MarkDaoust are you the person to assign docs-related requests to?

**Comment by tensorflowbutler** [comment]
Nagging Assignee @skye: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @skye: It has been 31 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @skye: It has been 46 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @skye: It has been 61 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @skye: It has been 76 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @skye: It has been 91 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by skye** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
