### ISSUE TITLE
Bazel build Android shared object libtensorflow_demo.so fails with jni.h not found

### ISSUE THREAD

**Issue by lingz** [tensorflow/tensorflow#1769]
I'm trying to build a .so of the Tensorflow Android lib in order to include in the build process of an existing app. Bazel is able to build the full apk fine, but it's having trouble when I tell it to only build the .so, complaining that jni.h is not found.

### Environment info
Operating System:

Ubuntu 14.04 x64

If installed from binary pip package, provide:
1. Which pip package you installed:

https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.7.1-cp27-none-linux_x86_64.whl

2. The output from python -c "import tensorflow; print(tensorflow.__version__)":
0.7.1

If installed from sources, provide the commit hash:

### Steps to reproduce
1.  bazel build //tensorflow/examples/android:libtensorflow_demo.so

2. You get the error message: 

ERROR: /Code/tensorflow/tensorflow/examples/android/BUILD:12:1: C++ compilation of rule '//tensorflow/examples/android:libtensorflow_demo.so' failed: namespace-sandbox failed: error executing command /home/user/.cache/bazel/_bazel_user/460c757144c1d801a3560f7277d7643a/tensorflow/_bin/namespace-sandbox ... (remaining 63 argument(s) skipped).
In file included from tensorflow/examples/android/jni/jni_utils.cc:16:0:
./tensorflow/examples/android/jni/jni_utils.h:19:17: fatal error: jni.h: No such file or directory
 #include <jni.h>
                 ^
compilation terminated.

### What have you tried?
1. Running bazel build //tensorflow/examples/android:tensorflow_demo does in fact work correctly.

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

**Comment by lingz** [comment]
I'm no expert on Bazel, but I assume it's because that it is using an android toolchain when the root target is an android_binary target. Could I make bazel somehow use this same toolchain for just compiling the cc_binary target?

**Comment by andrewharp** [comment]
Unfortunately it's not very obvious how to build standalone Android in bazel. There's an example command in the comments for //tensorflow/core:android_tensorflow_lib.  Here it is for reference (adapted for libtensorflow_demo.so):

bazel build -c opt tensorflow/examples/android/libtensorflow_demo.so \
 --crosstool_top=//third_party/java/android/android_ndk_linux/toolchains:everything \
 --cpu=armeabi-v7a \
 --host_crosstool_top=@bazel_tools//tools/cpp:toolchain

Keep in mind that the link flags for libtensorflow_demo.so will by default strip out anything not explicitly exported by the library.

**Comment by lingz** [comment]
Thanks for the comment but I'm still getting the error:

ERROR: /home/ling/Code/tensorflow/tools/defaults/BUILD:11:1: no such package 'third_party/java/android/android_ndk_linux/toolchains': BUILD file not found on package path and referenced by '//tools/defaults:crosstool'.

I tried copying the NDK manually into that location but it seems there is no Bazel BUILD file for it.

Also two other questions:
1. Is it possible to have my native code be outside the Tensorflow directory, and just refer to it remotely?
2. Can Bazel be set to output object files .o or static libraries .a instead of shared libraries?

Thanks for your help!

**Comment by andrewharp** [comment]
Sorry, I mixed up my build commands. Here's one I just verified to work with a fixed crosstool_top param.

bazel build -c opt tensorflow/examples/android:libtensorflow_demo.so \
--crosstool_top=//external:android/crosstool \
--cpu=armeabi-v7a \
--host_crosstool_top=@bazel_tools//tools/cpp:toolchain

1. You can certainly have other targets depend on Tensorflow, or have Tensorflow depend on other targets. Or do you mean depending on TF from outside of Bazel? That's also possible, if you have the precompiled static library and the header paths configured appropriately.

2. You can build a static library by removing the alwayslink=1 attributes from the //tensorflow/core:android_tensorflow_lib(_lite) targets and building those. If you want the examples/android/jni code as well I think you could experiment with a "-static" linkopt, or alternatively turn that lib into a cc_library.

**Comment by andrewharp** [comment]
Closing due to lack of activity; please reopen if still seeing issues.

**Comment by gecece** [comment]
@andrewharp  
Hi, I tried you build command, and it works works with tensorflow v0.6.0 codes.
But when I run it with the master codes, I got the error:

**ERROR: /home/gece/.cache/bazel/_bazel_gece/1caf8a34a8f0c8f7d976c36c83fa823a/external/protobuf/BUILD:73:1: C++ compilation of rule '@protobuf//:protobuf_lite' failed: false failed: error executing command /bin/false -MD -MF bazel-out/stub_armeabi-v7a-opt/bin/external/protobuf/_objs/protobuf_lite/external/protobuf/src/google/protobuf/stubs/bytestream.pic.d ... (remaining 26 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
Target //tensorflow/examples/android:libtensorflow_demo.so failed to build
Use --verbose_failures to see the command lines of failed build steps.**

This is the outputs with '--verbose_failures'

**ERROR: /home/gece/.cache/bazel/_bazel_gece/1caf8a34a8f0c8f7d976c36c83fa823a/external/protobuf/BUILD:73:1: C++ compilation of rule '@protobuf//:protobuf_lite' failed: false failed: error executing command 
  (cd /home/gece/.cache/bazel/_bazel_gece/1caf8a34a8f0c8f7d976c36c83fa823a/execroot/tensorflow && \
  exec env - \
    LD_LIBRARY_PATH=/home/gece/Workspace/torch/install/lib:/home/gece/Workspace/torch/install/lib:/usr/local/cuda-7.5/lib64: \
    PATH=/home/gece/Workspace/torch/install/bin:/home/gece/Workspace/torch/install/bin:/usr/local/cuda-7.5/bin:/home/gece/anaconda2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games \
  /bin/false -MD -MF bazel-out/stub_armeabi-v7a-opt/bin/external/protobuf/_objs/protobuf_lite/external/protobuf/src/google/protobuf/stubs/bytestream.pic.d '-frandom-seed=bazel-out/stub_armeabi-v7a-opt/bin/external/protobuf/_objs/protobuf_lite/external/protobuf/src/google/protobuf/stubs/bytestream.pic.o' -fPIC -iquote external/protobuf -iquote bazel-out/stub_armeabi-v7a-opt/genfiles/external/protobuf -iquote external/bazel_tools -iquote bazel-out/stub_armeabi-v7a-opt/genfiles/external/bazel_tools -isystem external/protobuf/src -isystem bazel-out/stub_armeabi-v7a-opt/genfiles/external/protobuf/src -isystem external/bazel_tools/tools/cpp/gcc3 -DHAVE_PTHREAD -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -Wno-unused-function -c external/protobuf/src/google/protobuf/stubs/bytestream.cc -o bazel-out/stub_armeabi-v7a-opt/bin/external/protobuf/_objs/protobuf_lite/external/protobuf/src/google/protobuf/stubs/bytestream.pic.o): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
Target //tensorflow/examples/android:libtensorflow_demo.so failed to build**

**Comment by sandeeptengale** [comment]
@drcege I got exactly same error, you got any solution for this?

**Comment by andrewharp** [comment]
Have you [set up your WORKSPACE file](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/android/README.md#edit-workspace) yet? This build error is typical when the NDK is not installed and configured there.

**Comment by drcege** [comment]
@sandeeptengale  Sorry,  I cannot help you. I have not worked with the code for a while.

**Comment by sandeeptengale** [comment]
Thank you guys, now its working for me, I have not used the proper version of NDK I guess, as mentioned in the comment of workspace file, I replaced my NDK with 12b version it started working perfectly for me

**Comment by j2emanue** [comment]
i've already updated git submodules recursively on my macbook.  But i am getting an error on building with bazel. Here is my workspace file changes:

```
# Uncomment and update the paths in these entries to build the Android demo.
android_sdk_repository(
    name = "androidsdk",
    api_level = 23,
    # Ensure that you have the build_tools_version below installed in the
    # SDK manager as it updates periodically.
    build_tools_version = "25.0.2",
#    # Replace with path to Android SDK on your system
    path = "/Users/j2emanue/Library/Android/sdk",
)
#
# Android NDK r12b is recommended (higher may cause issues with Bazel)
android_ndk_repository(
    name="androidndk",
    path="/Users/j2emanue/Downloads/android-ndk-r12b",
#    # This needs to be 14 or higher to compile TensorFlow.
#    # Note that the NDK version is not the API level.
    api_level=14)
```

for the api_level in the android_ndk_repository closure i tried 23, 14, 21 . im not sure what to put there ?  on my pc i have android api 23 sdk already installed.  

here is the build error i get:

`ERROR: /private/var/tmp/_bazel_j2emanue/b0092c80c1dd2ccd3bd26061f20bf823/external/protobuf/BUILD:113:1: C++ compilation of rule '@protobuf//:protobuf' failed: Process exited with status 71 [sandboxed].
sandbox-exec: external/androidndk/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-gcc: No such file or directory
Use --strategy=CppCompile=standalone to disable sandboxing for the failing actions.
Target //tensorflow/examples/android:tensorflow_demo failed to build`


and if i use verbose reporting here is the error i get and the command used:

`bazel build  --verbose_failures -c  opt --local_resources 2048,0.5,1.0 //tensorflow/examples/android:tensorflow_demo`

error:

`ERROR: /private/var/tmp/_bazel_j2emanue/b0092c80c1dd2ccd3bd26061f20bf823/external/protobuf/BUILD:113:1: C++ compilation of rule '@protobuf//:protobuf' failed: arm-linux-androideabi-gcc failed: error executing command
  (exec env - \
    PATH='/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/j2emanue/Library/Android/sdk/platform-tools/:
/Users/j2emanue/Library/Android/sdk/ndk-bundle/:
/Users/j2emanue/Library/Android/sdk/build-tools/25.0.2/' \
    TMPDIR=/var/folders/q7/m2l4qpf11mqf2wjr24_jxrhc0000gn/T/ \
  external/androidndk/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-gcc -fstack-protector-strong -fpic -ffunction-sections -funwind-tables -no-canonical-prefixes -fno-canonical-system-headers '-march=armv7-a' '-mfpu=vfpv3-d16' '-mfloat-abi=softfp' -mthumb -Os -g -DNDEBUG -MD -MF bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-opt/bin/external/protobuf/_objs/protobuf/external/protobuf/src/google/protobuf/util/type_resolver_util.d '-frandom-seed=bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-opt/bin/external/protobuf/_objs/protobuf/external/protobuf/src/google/protobuf/util/type_resolver_util.o' -iquote external/protobuf -iquote bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-opt/genfiles/external/protobuf -iquote external/bazel_tools -iquote bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-opt/genfiles/external/bazel_tools -isystem external/protobuf/src -isystem bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-opt/genfiles/external/protobuf/src -isystem external/bazel_tools/tools/cpp/gcc3 -DHAVE_PTHREAD -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -Wno-unused-function '--sysroot=external/androidndk/ndk/platforms/android-14/arch-arm' -isystem external/androidndk/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/include -isystem external/androidndk/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/include-fixed -isystem external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include -isystem external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/include -isystem external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/backward -c external/protobuf/src/google/protobuf/util/type_resolver_util.cc -o bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-opt/bin/external/protobuf/_objs/protobuf/external/protobuf/src/google/protobuf/util/type_resolver_util.o)

Use --sandbox_debug to see verbose messages from the sandbox.
sandbox-exec: external/androidndk/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-gcc: No such file or directory
Use --strategy=CppCompile=standalone to disable sandboxing for the failing actions.
Target //tensorflow/examples/android:tensorflow_demo failed to build
INFO: Elapsed time: 5.458s, Critical Path: 4.98s`


How can i resolve this ?

**Comment by andrewharp** [comment]
@j2emanue Bazel isn't able to find your ndk. Check your paths, dirrctory permissions, and perhaps disable sandboxed building?

**Comment by j2emanue** [comment]
@andrewharp what api_level should i put in there. im using 12b ndk ? i have api 23 installed on my pc can i use 23 for the ndk api level then ?

**Comment by andrewharp** [comment]
@j2emanue The NDK API level doesn't really matter, it just determines which headers are used to build. 14 and higher is fine. Your problem is that Bazel can't even find the compiler.

**Comment by j2emanue** [comment]
thanks @andrewharp  seem to be working now. i actually had the wrong NDK installed. i was using the linux version instead of darwin for mac. Also when i was setting the path i was using enter key to separate the entries. they should all be on one line.  looks good now.

**Comment by missionary0** [comment]
Hello! I had tried building the `libtensorflow_inference.so` file using the following -
`bazel build -c opt //tensorflow/contrib/android:libtensorflow_inference.so --crosstool_top=//external:android/crosstool --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --cpu=armeabi-v7a`
As you can see I have changed the `--cpu` argument to `arm64-v8a` and the command above is generating the desired `libtensorflow_inference.so` file, which I have copied in my Android Project directory in `src/main/jniLibs/arm64-v8a/`.

But, upon running building the project on a device, it's throwing the following error -
`
05-10 11:29:00.421 14215-14254/com.example.zeus.objectdetection E/AndroidRuntime: FATAL EXCEPTION: pool-1-thread-1
                                                                                  Process: com.example.zeus.objectdetection, PID: 14215
                                                                                  Theme: themes:{default=overlay:system, iconPack:system, fontPkg:system, com.android.systemui=overlay:system, com.android.systemui.navbar=overlay:system}
                                                                                  java.lang.RuntimeException: Error Initializing TensorFlow
                                                                                      at com.example.zeus.objectdetection.MainActivity$2.run(MainActivity.java:91)
                                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                      at java.lang.Thread.run(Thread.java:818)
                                                                                   Caused by: java.lang.RuntimeException: Native TF methods not found; check that the correct native libraries are present in the APK.
                                                                                      at org.tensorflow.contrib.android.TensorFlowInferenceInterface.<init>(TensorFlowInferenceInterface.java:68)
                                                                                      at com.example.zeus.objectdetection.TensorFlowImageClassifier.create(TensorFlowImageClassifier.java:52)
                                                                                      at com.example.zeus.objectdetection.MainActivity$2.run(MainActivity.java:80)
                                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                                      at java.lang.Thread.run(Thread.java:818) 
`

Can anyone please tell me what might be the problem?

**Comment by andrewharp** [comment]
Just to confirm, you're running this on an arm64-v8a device? What's the output of unzip -v tensorflow_demo.so?

**Comment by missionary0** [comment]
Thank you for the reply @andrewharp. I don't exactly know that. I am running it on One Plus One. On this device building with `armeabi-v7a` worked just fine. I was just trying out the above to understand what it means.

 What is the meaning of this device architecture thing? Can you please send me some links where I can read about it?

**Comment by andrewharp** [comment]
arm64-v8a is a higher-performing 64-bit variant of the ARM architecture that only a subset of armeabi-v7a compatible devices support. If you add both to your apk your device will pick the highest compatible target available, but if you only add arm64-v8a and your device doesn't support it you may get error messages like the above.

You can see what .so libs are packaged in your apk with `unzip -v tensorflow_demo.apk`

**Comment by chingjunehao** [comment]
Hi @andrewharp , I was trying to build the libtensorflow_inference.so file, following this [tutorial](https://www.skcript.com/svr/realtime-object-and-face-detection-in-android-using-tensorflow-object-detection-api/). 

I'm on
- Windows 10
- Installed the latest version of Bazel using `choco install bazel` with cmd
- NDK r14b version
- JDK 8 updated with Android Studio

When I was trying to build .so file with 
```
bazel build -c opt //tensorflow/contrib/android:libtensorflow_inference.so 
  --crosstool_top=//external:android/crosstool
  --host_crosstool_top=@bazel_tools//tools/cpp:toolchain
  --cpu=armeabi-v7a --verbose_failures
```

I had this error:
ERROR: C:/users/user/appdata/local/temp/_bazel_user/xbt4cnkp/external/protobuf_archive/BUILD:265:1: Executing genrule @protobuf_archive//:generate_js_well_known_types_embed failed (Exit -1). Note: Remote connection/protocol failed with: execution failed: bash.exe failed: error executing command
  cd C:/users/user/appdata/local/temp/_bazel_user/xbt4cnkp/execroot/org_tensorflow
  SET PATH=C:\tools\msys64\usr\bin;C:\tools\msys64\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\libnvvp;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files\nodejs\;C:\Program Files\MATLAB\R2016b\bin;C:\Program Files\ibm\gsk8\lib64;C:\Program Files (x86)\ibm\gsk8\lib;C:\PROGRA~1\IBM\SQLLIB\BIN;C:\PROGRA~1\IBM\SQLLIB\FUNCTION;C:\PROGRA~1\IBM\SQLLIB\SAMPLES\REPL;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Users\User\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Git\cmd;C:\Program Files\OpenVPN\bin;C:\Program Files\PuTTY\;C:\Program Files\Java\jdk1.7.0_79\bin;C:\Users\User\Anaconda3\envs\py36;C:\Python27;C:\Users\User\Anaconda3\Scripts;C:\Users\User\Anaconda3\Library\bin;C:\Users\User\AppData\Local\Microsoft\WindowsApps;C:\Users\User\AppData\Roaming\npm;C:\Program Files (x86)\CodeBlocks\MinGW\bin;C:\Program Files\Docker Toolbox;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\extras\CUPTI\libx64;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\lib\x64;C:\ProgramData\chocolatey\bin
  C:/tools/msys64/usr/bin/bash.exe -c source external/bazel_tools/tools/genrule/genrule-setup.sh; bazel-out/host/bin/external/protobuf_archive/js_embed.exe external/protobuf_archive/src/google/protobuf/compiler/js/well_known_types/any.js external/protobuf_archive/src/google/protobuf/compiler/js/well_known_types/struct.js external/protobuf_archive/src/google/protobuf/compiler/js/well_known_types/timestamp.js > bazel-out/host/genfiles/external/protobuf_archive/src/google/protobuf/compiler/js/well_known_types_embed.cc
Action failed to execute: java.io.IOException: ERROR: src/main/native/windows/processes-jni.cc(239): CreateProcessW("C:\tools\msys64\usr\bin\bash.exe" -c "source external/bazel_tools/tools/genrule/genrule-setup.sh; bazel-out/host/bin/external/protobuf_archive/js_embed.exe external/protobuf_archive/src/google/protobuf/compiler/js/well_known_types/any.js external/protobuf_archive/src/google/protobuf/compiler/js/well_known_types/struct.js external/protobuf_archive/src/google/protobuf/compiler/js/well_known_types/timestamp.js > bazel-out/host/genfiles/external/protobuf_archive/src/google/protobuf/compiler/js/well_known_types_embed.cc"): The system cannot find the file specified.

Target //tensorflow/contrib/android:libtensorflow_inference.so failed to build
INFO: Elapsed time: 232.602s, Critical Path: 15.31s
FAILED: Build did NOT complete successfully


I have been trying with other version of bazel and NDK, but still can't build the file. Can you help me look into it?

Thanks in advance.

**Comment by chingjunehao** [comment]
@Vrishod are you on Windows too? Feel free to find me, I will help.

**Comment by Vrishod** [comment]
Yes I am on Windows. Help me in this regard

**Comment by chingjunehao** [comment]
You can get the .so and .jar files that are required to build the apps from http://ci.tensorflow.org/view/Nightly/job/nightly-android/
1. Click on the Last stable build
2. Artifact
3. Download all files in the zip, then you are ready with .so and .jar, place them in the correct places and you are done.

**Comment by Vrishod** [comment]
Thanks a lot @chingjunehao ...
