### ISSUE TITLE
tf.flags cannot handle options contain hyphen in the middle.

### ISSUE THREAD

**Issue by nagachika** [tensorflow/tensorflow#17734]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Google Cloud ML Engine (maybe Ubuntu)
- **TensorFlow installed from (source or binary)**: Pre installed on Google Cloud ML Engine
- **TensorFlow version (use command below)**: 1.5.0
- **Python version**: 2.7
- **Bazel version (if compiling from source)**:NA
- **GCC/Compiler version (if compiling from source)**:NA
- **CUDA/cuDNN version**:NA
- **GPU model and memory**:NA
- **Exact command to reproduce**:

### Describe the problem

According to the documentation of Google Cloud ML Engine [1], the ML Engine pass the option `--job-dir` to the python process and the program should be able to handle `--job-dir` option.

The snippet shown in the next section can run successfully with TensorFlow 1.4.1 but failed with 1.5.0, 1.6.0, 1.7.0.rc0.

As a result, I cannot use runtime version 1.5 on Cloud ML Engine with my package using `tf.flags` to handle option `--job-dir`.
The support of TensorFlow 1.5.0 on Cloud ML Engine training was released officially just few days before [2].

### Source code / logs

Here is a snippet to reproduce the issue.

```
import tensorflow as tf

tf.flags.DEFINE_string("job-dir", "default", "job dir")

def main(argv):
    print(tf.__version__)
    print(tf.flags.FLAGS.job_dir)

tf.app.run()
```

Here is the backtrace from :

```
> python snippent.py --job-dir=foo
1.5.0
Traceback (most recent call last):
  File "snippet.py", line 9, in <module>
    tf.app.run()
  File "/Users/chikanaga/.anyenv/envs/pyenv/versions/2.7.12/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 124, in run
    _sys.exit(main(argv))
  File "hoge.py", line 7, in main
    print(tf.flags.FLAGS.job_dir)
  File "/Users/chikanaga/.anyenv/envs/pyenv/versions/2.7.12/lib/python2.7/site-packages/tensorflow/python/platform/flags.py", line 85, in __getattr__
    return wrapped.__getattr__(name)
  File "/Users/chikanaga/.anyenv/envs/pyenv/versions/2.7.12/lib/python2.7/site-packages/absl/flags/_flagvalues.py", line 470, in __getattr__
    raise AttributeError(name)
AttributeError: job_dir
```

1. https://cloud.google.com/ml-engine/docs/training-overview#job_configuration_parameters
2. https://cloud.google.com/ml-engine/docs/runtime-version-list

**Comment by asimshankar** [comment]
Thanks for the report. I believe this is rooted in the move to the absl flags library in https://myhire.googleplex.com/a/google.com/feedback/#review:c=google.com-70987962&fid=781967491
which happened between the release of 1.4.0 and 1.5.0.

Will look into what should be done with this.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @asimshankar: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by asimshankar** [comment]
Long story short: In an ideal world, TensorFlow wouldn't be providing a flags library - that is squarely not in its area of expertise :). However, due to historical reasons around the time we created an opensource version of what was being developed within Google, the `tf.flags` library had to be created (this was before `absl-py` existed).

Long story short, it doesn't seem like investing in `tf.flags` is worthwhile and since it seems that for CloudML using a different library (like `argparse`) suffices.

So, I'm going to go ahead an close this issue.
(CC @martinwicke )

Hopefully that sounds reasonable to y'all.
Thanks.
