### ISSUE TITLE
Can't import TensorFlow

### ISSUE THREAD

**Issue by Gad1001** [tensorflow/tensorflow#17761]
### System information
- OS Platform:
    Windows 10 Pro 64bit
- Python version: 
   Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit (AMD64)] on win32
- TensorFlow version
   1.6.0 installed using:
`pip3 install --upgrade tensorflow`

```
Collecting tensorflow
  Using cached tensorflow-1.6.0-cp36-cp36m-win_amd64.whl
Requirement already up-to-date: astor>=0.6.0 in c:\users\pc\appdata\local\programs\python\python36\lib\site-packages (from tensorflow)
Requirement already up-to-date: protobuf>=3.4.0 in c:\users\pc\appdata\local\programs\python\python36\lib\site-packages (from tensorflow)
Requirement already up-to-date: grpcio>=1.8.6 in c:\users\pc\appdata\local\programs\python\python36\lib\site-packages (from tensorflow)
Requirement already up-to-date: wheel>=0.26 in c:\users\pc\appdata\local\programs\python\python36\lib\site-packages (from tensorflow)
Requirement already up-to-date: numpy>=1.13.3 in c:\users\pc\appdata\local\programs\python\python36\lib\site-packages (from tensorflow)
Requirement already up-to-date: tensorboard<1.7.0,>=1.6.0 in c:\users\pc\appdata\local\programs\python\python36\lib\site-packages (from tensorflow)
Requirement already up-to-date: termcolor>=1.1.0 in c:\users\pc\appdata\local\programs\python\python36\lib\site-packages (from tensorflow)
Requirement already up-to-date: absl-py>=0.1.6 in c:\users\pc\appdata\local\programs\python\python36\lib\site-packages (from tensorflow)
Requirement already up-to-date: six>=1.10.0 in c:\users\pc\appdata\local\programs\python\python36\lib\site-packages (from tensorflow)
Requirement already up-to-date: gast>=0.2.0 in c:\users\pc\appdata\local\programs\python\python36\lib\site-packages (from tensorflow)
Requirement already up-to-date: setuptools in c:\users\pc\appdata\local\programs\python\python36\lib\site-packages (from protobuf>=3.4.0->tensorflow)
Requirement already up-to-date: bleach==1.5.0 in c:\users\pc\appdata\local\programs\python\python36\lib\site-packages (from tensorboard<1.7.0,>=1.6.0->tensorflow)
Requirement already up-to-date: werkzeug>=0.11.10 in c:\users\pc\appdata\local\programs\python\python36\lib\site-packages (from tensorboard<1.7.0,>=1.6.0->tensorflow)
Requirement already up-to-date: html5lib==0.9999999 in c:\users\pc\appdata\local\programs\python\python36\lib\site-packages (from tensorboard<1.7.0,>=1.6.0->tensorflow)
Requirement already up-to-date: markdown>=2.6.8 in c:\users\pc\appdata\local\programs\python\python36\lib\site-packages (from tensorboard<1.7.0,>=1.6.0->tensorflow)
Installing collected packages: tensorflow
Successfully installed tensorflow-1.6.0
```
- Have I written custom code: No
- Bazel version : I don't have
- CUDA/cuDNN version : I don't have
- GPU model and memory :N\A
- Exact command to reproduce : `import tensorflow as tf`
### The problem
Can't import TensorFlow
`import tensorflow as tf`

```
Traceback (most recent call last):
  File "C:\Users\pc\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Users\pc\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\pc\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\pc\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 21, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\pc\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 20, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow_internal')
  File "C:\Users\pc\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\pc\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "C:\Users\pc\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\pc\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\pc\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Users\pc\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\pc\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\pc\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 21, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\pc\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 20, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow_internal')
  File "C:\Users\pc\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```
I have no idea what to do.
TY in advance

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by DhinakaranSDK** [comment]
Installing tensorflow using ```conda install tensorflow``` can fix this error

**Comment by cbcoder** [comment]
I'm having the same issue above on Windows Server 2012 r2 datacenter, version 6.3.9600  I tried multiple uninstalls but can't get it to work.  

```
C:\Users\Administrator>python
Python 3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:57:36) [MSC v.1900 64 bit (AMD64)]
 on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\tensorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_impor
t_helper
    return importlib.import_module(mname)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\import
lib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 648, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 560, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
ImportError: DLL load failed: A dynamic link library (DLL) initialization routin
e failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\tensorflow\python\pywrap_tensorflow_internal.py", line 21, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\tensorflow\python\pywrap_tensorflow_internal.py", line 20, in swig_impor
t_helper
    return importlib.import_module('_pywrap_tensorflow_internal')
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\import
lib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\tensorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_impor
t_helper
    return importlib.import_module(mname)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\import
lib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 648, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 560, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
ImportError: DLL load failed: A dynamic link library (DLL) initialization routin
e failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\tensorflow\python\pywrap_tensorflow_internal.py", line 21, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\tensorflow\python\pywrap_tensorflow_internal.py", line 20, in swig_impor
t_helper
    return importlib.import_module('_pywrap_tensorflow_internal')
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\import
lib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_probl
ems
```

**Comment by skye** [comment]
@gunan do you know if someone can triage installation issues?

**Comment by gunan** [comment]
We have seen this on windows where users were running on old CPUs that did not have AVX instruction set available.
What is your CPU model?

**Comment by cbcoder** [comment]
Sorry to hijack your thread @Gad1001

I compiled and ran [this tool](https://gist.github.com/hi2p-perim/7855506#file-ssecheck-cpp) to check for AVX support and it shows my CPU does not, also confirmed at [cpu boss](http://cpuboss.com/cpu/Intel-Xeon-W3670)   I'm running on a VM in hyper-V on a xeon W3670. 

I just read the releases page mentioning AVX starting with 1.6.   I was running tensorflow 1.5 before so this makes sense!

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by codegeek2014** [comment]
I am facing the same issue on windows 8. Plus I have set installed VC++ 2015 Update 6 and set path to the required dll. Still facing the above error.

**Comment by gunan** [comment]
If you do not have a CPU that supports AVX instruction sets, prebuilt binaries wont work on your system.
While we work on a more portable and fast solution, you can build TF from sources to work around this problem. If you search existing issues, you can also find community built packages that can work on older systems.

**Comment by akhil30garg** [comment]
just downgrade tensorflow version to 1.5...............wasted 4 days to get this right...................rest all worked fine automatically.
use command "pip install tensorflow==1.5"
