### ISSUE TITLE
Make feature column input_layer compatible with sequential data

### ISSUE THREAD

**Issue by philippnormann1337** [tensorflow/tensorflow#17811]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes.
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Debian Buster/Sid
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.7.0-rc0
- **Python version**: 3.6.5rc1
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**: See source code below

### Describe the problem

Feature columns offer easy and reproducible feature encodings. It would be nice if they could be made compatible with sequential data as well. I currently would like to use them for processing inputs in a custom RNN estimator and sadly discovered that the current [`input_layer`](https://www.tensorflow.org/api_docs/python/tf/feature_column/input_layer) API doesn't support sequential inputs. It always returns a Tensor shaped `(batch_size, first_layer_dimension)`, which makes it unusable in combination with the[ `dynamic_rnn`](https://www.tensorflow.org/api_docs/python/tf/nn/dynamic_rnn) wrapper which expects inputs of shape `(batch_size, max_time, first_layer_dimension)`

### Source code / logs
My first attempt at a workaround for this shortcoming, was mapping the `input_layer` function across the sequences of the inputs. 
```python
def model_fn(features, labels, mode, params, config):
    sequence_lengths = features.pop('session_length')
    rnn_cell, state_size, initializer = params['rnn_cell'].values()

    encoded_features = tf.map_fn(lambda input_features: tf.feature_column.input_layer(input_features, params['feature_columns']), features, dtype=tf.float32)
    encoded_labels = tf.tile(tf.map_fn(lambda seqeunce_labels: tf.feature_column.input_layer(seqeunce_labels, params['label_columns']), labels, dtype=tf.float32), sequence_lengths)

    cell = rnn_cell(num_units=state_size, initializer=initializer())
    outputs, state = tf.nn.dynamic_rnn(cell=cell, inputs=encoded_features, dtype=tf.float32, sequence_length=sequence_lengths)
    logits = tf.contrib.layers.fully_connected(outputs, num_outputs=2, activation_fn=None)
    predictions = tf.nn.softmax(logits)
    
    loss = tf.losses.softmax_cross_entropy(encoded_labels, logits)
    optimizer = tf.train.AdamOptimizer(learning_rate=params["learning_rate"])
    train_op = optimizer.minimize(loss=loss, global_step=tf.train.get_global_step())
    
    return tf.estimator.EstimatorSpec(mode, predictions=predictions, train_op=train_op, loss=loss)
```
Due to some kind of frame error this sadly is also not possible. Maybe I am missing something here and any tips on why this is failing would be highly appreciated.
```bash
InvalidArgumentError: The node 'group_deps_1' has inputs from different frames. 
The input 'map/while/input_layer/url_indicator/url_lookup/hash_table/table_init' is in frame 'map/while/while_context'. 
The input 'map_1/while/input_layer/label_indicator/label_lookup/hash_table/table_init' is in frame 'map_1/while/while_context'.`
```
**In my opinion a native (higher-level) solution to this problem is needed nonetheless!**

**Comment by philippnormann** [comment]
@ebrevdo Given your deep involvement in the development of RNN features, maybe you can provide some valuable input on this issue...

**Comment by philippnormann** [comment]
Since the `map_fn` approach at unrolling the input layer wasn't successful, I tried to achieve the same effect using the `while_loop`. 
```python
def unroll_input_layer(inputs_dict, feature_columns, batch_size):
    def cond(n, batch_size, encoded_inputs, inputs_dict):
        return n < batch_size
    
    def body(n, batch_size, encoded_inputs, inputs_dict):
        example_features = {name: feature[n] for name, feature in inputs_dict.items()}
        encoded_example = tf.feature_column.input_layer(example_features, feature_columns)
        encoded_inputs = encoded_inputs.write(n, encoded_example)
        return n + 1, batch_size, encoded_inputs, inputs_dict
    encoded_inputs = tf.TensorArray(tf.float32, size=batch_size)
    _, _, encoded_inputs, _ = tf.while_loop(cond, body, loop_vars=[0, batch_size, encoded_inputs, inputs_dict])
    return encoded_inputs.stack()
```

**Comment by philippnormann** [comment]
I found a way to apply the feature columns to sequences by reshaping it into a non-sequential batch, applying the `input_layer` function and unpacking it into sequences afterwards.
```python
def unpack_batch(packed_batch, batch_size, max_len):
    return {feature_name: tf.reshape(feature_tensor, [batch_size * max_len]) for feature_name, feature_tensor in packed_batch.items()}
  
def pack_batch(unpacked_batch, batch_size, max_len, first_layer_dimension):
    return tf.reshape(unpacked_batch, [batch_size, max_len, first_layer_dimension])

def apply_feature_columns_to_sequences(feature_dict, feature_columns, batch_size, max_len, first_layer_dimension):
    unpacked_feature_dict = unpack_batch(feature_dict, batch_size, max_len)
    packed_features = pack_batch(tf.feature_column.input_layer(unpacked_feature_dict, feature_columns), batch_size, max_len, first_layer_dimension)
    return packed_features
```
Even though this works for now, I still see the need for a higher level solution to this problem.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @ebrevdo: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @ebrevdo: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @ebrevdo: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by BenMacKenzie** [comment]
@philippnormann can you share the full code for your solution?

**Comment by Corbalt** [comment]
You may be interested in sequential feature columns which were recently added:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/feature_column/python/feature_column/sequence_feature_column.py

These can be used with sequence_input_layer (also in that file).

**Comment by BenMacKenzie** [comment]
thanks @Corbalt 

I am familiar with regular feature columns.  i think what is confusing me is how to connect up the graph to data.  In the case of a regular estimator i create the input_layer as follows:

input_layer = tf.feature_column.input_layer(features, get_feature_columns())

where 'features'  is provided by an input_fn and via the dataset api are attached in graph to a de-queueing operation. 

in the case of the sequence_feature_column the input_layer is created as follows:

input_layer, sequence_length = sequence_input_layer(features, columns)

Where the features are created by tf.parse_example:

features = tf.parse_example(..., features=make_parse_example_spec(columns))

 where '....'  refers to 'a number of serialized protos'.  

So….if this were to work in the same way as a regular estimator, the call to tf.parse_example would need to occur in an estimator input_fn….but the fact that parse_example contains a reference to the columns suggests it belongs in the model function.

Maybe i am reading much into the code snippet in the comments and i should just send raw data from the input_fn in a suitable shape and ignore the tf.parse_example.

Ben

**Comment by Corbalt** [comment]
That part of the API is actually the same. FeatureColumns can be used in two places: specifying how to parse features (in the input_fn) and how to construct the input layer (done after parsing to combine the dictionary of raw features into a single Tensor with transformed features). The parse features part is relevant if you have tf.Examples in some file that you're parsing, but if you have data in a pandas DataFrame or something like that you can ignore it and produce the features dictionary some other way.

Glad the tests were helpful!

**Comment by tensorflowbutler** [comment]
Nagging Assignee @ebrevdo: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by vijaik2k7** [comment]
Trying to use the functions defined in sequence_feature_column.py on sequence data read from TFRecords to be fed to a dynamic RNN. I am using sequence_categorical_column_with_vocabulary_file() to generate my _SequenceCategoricalColumn and use feature_column.indicator_column on this _SequenceCategoricalColumn. This is passed along with my features to the sequence_input_layer to obtain the Categorical Tensors

Here is a snippet of the code **that I use for the categorical features**:

`tf_transform_output = input_utils.TFTransformOutput(os.path.join(metadata_dir, 'transform_fn'))
one_hot_columns = [tf_seq.sequence_categorical_column_with_vocabulary_file(key=key,vocabulary_file=tf_transform_output.vocabulary_file_by_name(vocab_filename=key),vocabulary_size=constants.CATEGORICAL_VOCAB_SIZE[key])for key in constants.CATEGORICAL_FEATURES]
for fc in one_hot_columns:
    features[fc[0]], _ = tf_seq.sequence_input_layer(features, [tf.feature_column.indicator_column(fc)])`

I get the following error:

`Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/kasthurirangan/trainer/modelf2/task.py", line 172, in <module>
    learn_runner.run(generate_experiment_fn(**experiment_args), output_dir)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.py", line 250, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/learn_runner.py", line 225, in run
    return _execute_schedule(experiment, schedule)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/learn_runner.py", line 52, in _execute_schedule
    return task()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 682, in train_and_evaluate
    export_results = self._maybe_export(eval_result)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 802, in _maybe_export
    eval_result=eval_result))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/export_strategy.py", line 110, in export
    return self.export_fn(estimator, export_path, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/utils/saved_model_export_utils.py", line 478, in export_fn
    strip_default_attrs=strip_default_attrs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 1399, in export_savedmodel
    model_fn_lib.ModeKeys.INFER)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 1227, in _call_model_fn
    model_fn_results = self._model_fn(features, labels, **kwargs)
  File "trainer/modelf2/model.py", line 105, in rnn_model
    print(tf.shape(features['berth_type_cat']))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 285, in shape
    return shape_internal(input, name, optimize=True, out_type=out_type)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 309, in shape_internal
    input_tensor = ops.convert_to_tensor(input)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1014, in convert_to_tensor
    as_ref=False)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1104, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 1034, in _autopacking_conversion_function
    return _autopacking_helper(v, inferred_dtype, name or "packed")
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 976, in _autopacking_helper
    elem))
TypeError: Cannot convert a list containing a tensor of dtype <dtype: 'int64'> to <dtype: 'float32'> (Tensor is: <tf.Tensor 'sequence_input_layer/foo_type_indicator/sequence_length:0' shape=(?,) dtype=int64>)`

Any thoughts on what I should be looking at changing or the reason for this error?

**Comment by tensorflowbutler** [comment]
Nagging Assignee @ebrevdo: It has been 40 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by philippnormann1337** [comment]
Thanks @Corbalt! The `sequence_feature_column` solves this issue!

**Comment by SijanC147** [comment]
Hey @tpatel0409 , don't know if you figured it out, but being completely new to TF myself I ran into the exact same problem you mentioned. 

I was using `padded_batch` to pad my sequence input features and was getting the same error that my input had to be a SparseTensor. 

Have a look at [dense_to_sparse_batch](https://www.tensorflow.org/api_docs/python/tf/contrib/data/dense_to_sparse_batch), I got it working ditching the `padded_batch` and instead converting each of my sequence features to SparseTensor form, by setting batch size to 1, and row_shape to what was my padded_shapes argument from before, in my case that's [ _max_seq_length_, _embedding_dim_size_ ]

Like I said, I just started out with TF a few days ago, so there might be a better, more efficient solution to this, but hopefully, this helps in some way.

**Comment by yweweler** [comment]
@tpatel0409,
from [sequence_feature_column_test.py](https://github.com/tensorflow/tensorflow/blob/r1.12/tensorflow/contrib/feature_column/python/feature_column/sequence_feature_column_test.py) it seems that the only way to use `sequence_numeric_column` is with `SparseTensor`. Looking at the [implementation](https://github.com/tensorflow/tensorflow/blob/a6d8ffae097d0132989ae4688d224121ec6d8f35/tensorflow/contrib/feature_column/python/feature_column/sequence_feature_column.py#L449), `_SequenceNumericColumn` can only handle `SparseTensor`.

However, it seems that with the upcoming rework of the feature columns [feature_column_v2.py](https://github.com/tensorflow/tensorflow/blob/0ef639bf1d7cc540c382513c19ff3565becac537/tensorflow/python/feature_column/feature_column_v2.py) there will be a column called `SequenceDenseColumn`. Not sure if it is intended for this case.

Overall it seems to me that using feature columns for sequence data is currently not advisable. 
Sadly communication or any clarification on this issue seems to be missing.

**Suggestion for improvement**:
I think to prevent the overall discussion about this restriction of `sequence_numeric_column`, in the future we should add some clarification to the [documentation](https://www.tensorflow.org/api_docs/python/tf/contrib/feature_column/sequence_numeric_column).
I think it should clearly state that it does only support `SparseTensor` objects.
