### ISSUE TITLE
Hello, I am having a problem running the classify_image file from my command line. I have a recurring error and nothing I seem to do fixes it.

### ISSUE THREAD

**Issue by akiljames83** [tensorflow/tensorflow#17841]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:no, i was using script
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: windows
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 1.6.0
- **Python version**: 3.6
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**: python classify_image.py --image_file "C:\Users\akilj\Desktop\cropped_panda.jpg"

### Describe the problem

I Ran this line of from my command line:

python classify_image.py --image_file "C:\Users\akilj\Desktop\cropped_panda.jpg"                                                                                           
I was in this directory:
~/Desktop/models-master/tutorials/image/imagenet

### Source code / logs

The resultant error was:

Traceback (most recent call last):
  File "C:\Users\akilj\AppData\Local\Programs\Python\Python36\lib\tarfile.py", l                                                                                            ine 2294, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "C:\Users\akilj\AppData\Local\Programs\Python\Python36\lib\tarfile.py", l                                                                                            ine 1090, in fromtarfile
    obj = cls.frombuf(buf, tarfile.encoding, tarfile.errors)
  File "C:\Users\akilj\AppData\Local\Programs\Python\Python36\lib\tarfile.py", l                                                                                            ine 1026, in frombuf
    raise EmptyHeaderError("empty header")
tarfile.EmptyHeaderError: empty header

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "classify_image.py", line 227, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "C:\Users\akilj\AppData\Local\Programs\Python\Python36\lib\site-packages\                                                                                            tensorflow\python\platform\app.py", line 126, in run
    _sys.exit(main(argv))
  File "classify_image.py", line 190, in main
    maybe_download_and_extract()
  File "classify_image.py", line 186, in maybe_download_and_extract
    tarfile.open(filepath, 'r:gz').extractall(dest_directory)
  File "C:\Users\akilj\AppData\Local\Programs\Python\Python36\lib\tarfile.py", l                                                                                            ine 1586, in open
    return func(name, filemode, fileobj, **kwargs)
  File "C:\Users\akilj\AppData\Local\Programs\Python\Python36\lib\tarfile.py", l                                                                                            ine 1640, in gzopen
    t = cls.taropen(name, mode, fileobj, **kwargs)
  File "C:\Users\akilj\AppData\Local\Programs\Python\Python36\lib\tarfile.py", l                                                                                            ine 1616, in taropen
    return cls(name, mode, fileobj, **kwargs)
  File "C:\Users\akilj\AppData\Local\Programs\Python\Python36\lib\tarfile.py", l                                                                                            ine 1479, in __init__
    self.firstmember = self.next()
  File "C:\Users\akilj\AppData\Local\Programs\Python\Python36\lib\tarfile.py", l                                                                                            ine 2309, in next
    raise ReadError("empty file")
tarfile.ReadError: empty file

##
I tried changing up file location, checked instillation and found no issues but code wouldnt run. Please help.

**Comment by angersson** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
