### ISSUE TITLE
GPU sits idle for increasing time between consecutive training runs

### ISSUE THREAD

**Issue by androidbeepboop** [tensorflow/tensorflow#17905]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10 Version 10.0.16299 
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 1.5.0
- **Python version**: 3.6
- **Bazel version (if compiling from source)**: not sure (is this important here?)
- **GCC/Compiler version (if compiling from source)**: not sure (is this important here?)
- **CUDA/cuDNN version**: not sure (is this important here?)
- **GPU model and memory**: NVIDIA Quadro P5000 16GB
- **Exact command to reproduce**: Not exactly an "exact command", but what I'm trying to do is perform CNN training runs consecutively without the GPU stalling between subsequent runs. 

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.

I'm using an evolutionary algorithm to optimize the hyperparameters of a CNN. However, over time, the GPU "waits" for greater and greater times between training cycles (afterburner visualization):

![image](https://user-images.githubusercontent.com/37384864/37736912-93ab0f72-2d28-11e8-837b-19c4da783251.png)

I assume this is a memory issue in a similar vein to https://github.com/tensorflow/tensorflow/issues/17048 and http://forums.fast.ai/t/tip-clear-tensorflow-gpu-memory/1979, however, the fixes mentioned there are not working. 

Any ideas of a workaround? The second link above uses Keras to reset GPU memory after each run, and have tried this, but it has not solved the problem (it may have somewhat shortened the lag between training runs, but not enough to constitute a fix). 

What do you suppose is going on here? I.e. what may be the source of the problem, and resources that could help me address it?

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.
(I'm not sure source code will be helpful in this general issue; let me know if you'd like to see my code).

**Comment by androidbeepboop** [comment]
@asimshankar and @vrv, you seem to have expertise in this area- any thoughts?

**Comment by vrv** [comment]
I don't think it is related to GPU memory usage, as you show it gets reset properly.  My only guess is that the size of the graph being built is increasing each time, rather than creating a new graph from scratch for every new hyperparameter setting.  Theoretically these should be pruned effectively, but I wonder if this is a problem.  I don't know much about Keras details, but there may be a way to reset the "graph" or "session" between model training runs.

Beyond that, I don't think we have enough information here to really know why this is happening (e.g., where is the time being idle; is it in your application program, in python, at the C++ level, etc.)

**Comment by androidbeepboop** [comment]
Hi @vrv- thanks for your reply, and good point re. it maybe not being a memory issue. I will investigate Keras graph/session resets and report back, though I will note that this issue was occurring prior to using Keras in this script. If it is helpful, here is a snippet of the error report (goes on for pages):

f_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\bfc_allocator.cc:662] Chunk at 00000015F2859800 of size 1280
2018-03-24 05:25:21.775992: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\bfc_allocator.cc:662] Chunk at 00000015F2859D00 of size 1280
2018-03-24 05:25:21.776691: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\bfc_allocator.cc:662] Chunk at 00000015F285A200 of size 159488
2018-03-24 05:25:21.777238: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\bfc_allocator.cc:662] Chunk at 00000015F2881100 of size 1280
2018-03-24 05:25:21.777484: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\bfc_allocator.cc:662] Chunk at 00000015F2881600 of size 1280
2018-03-24 05:25:21.777704: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\bfc_allocator.cc:662] Chunk at 00000015F2881B00 of size 95744
2018-03-24 05:25:21.777897: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\bfc_allocator.cc:662] Chunk at 00000015F2899100 of size 95744
.
.
.
Limit:                 13618452890
InUse:                 13618441472
MaxInUse:              13618452736
NumAllocs:                48687782
MaxAllocSize:           3805937664

2018-03-24 05:25:22.292220: W C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\bfc_allocator.cc:277] ****************************************************************************************************
2018-03-24 05:25:22.292545: W C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1198] Resource exhausted: OOM when allocating tensor with shape[5,7,72,16] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
2018-03-24 05:25:32.294665: W C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\bfc_allocator.cc:273] Allocator (GPU_0_bfc) ran out of memory trying to allocate 34.00MiB.  Current allocation summary follows.
2018-03-24 05:25:32.295801: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\bfc_allocator.cc:628] Bin (256): 	Total Chunks: 1118, Chunks in use: 1118. 279.5KiB allocated for chunks. 279.5KiB in use in bin. 32.0KiB client-requested in use in bin.
2018-03-24 05:25:32.297028: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\bfc_allocator.cc:628] Bin (512): 	Total Chunks: 746, Chunks in use: 746. 466.3KiB allocated for chunks. 466.3KiB in use in bin. 303.1KiB client-requested in use in bin.
.
.
.
Traceback (most recent call last):
  File "C:/Users/ashort7/PycharmProjects/CNN/venv1/SSVEP_TimeDomain_DeepCNN/layer_num_evo.py", line 1040, in <module>
    sess.run(init_op)
  File "C:\Users\ashort7\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\client\session.py", line 895, in run
    run_metadata_ptr)
  File "C:\Users\ashort7\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\client\session.py", line 1128, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\ashort7\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\client\session.py", line 1344, in _do_run
    options, run_metadata)
  File "C:\Users\ashort7\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\client\session.py", line 1363, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[3,7,1,72] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[Node: Variable_910/Adam/Assign = Assign[T=DT_FLOAT, _class=["loc:@Variable_910"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](Variable_910/Adam, Variable_910/Adam/Initializer/zeros)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.


Caused by op 'Variable_910/Adam/Assign', defined at:
  File "C:/Users/ashort7/PycharmProjects/CNN/venv1/SSVEP_TimeDomain_DeepCNN/layer_num_evo.py", line 1017, in <module>
    train_step = tf.train.AdamOptimizer(LEARNING_RATE).minimize(cross_entropy)
  File "C:\Users\ashort7\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\training\optimizer.py", line 365, in minimize
    name=name)
  File "C:\Users\ashort7\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\training\optimizer.py", line 516, in apply_gradients
    self._create_slots([_get_variable_for(v) for v in var_list])
  File "C:\Users\ashort7\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\training\adam.py", line 139, in _create_slots
    self._zeros_slot(v, "m", self._name)
  File "C:\Users\ashort7\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\training\optimizer.py", line 883, in _zeros_slot
    named_slots[_var_key(var)] = slot_creator.create_zeros_slot(var, op_name)
  File "C:\Users\ashort7\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\training\slot_creator.py", line 174, in create_zeros_slot
    colocate_with_primary=colocate_with_primary)
  File "C:\Users\ashort7\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\training\slot_creator.py", line 148, in create_slot_with_initializer
    dtype)
  File "C:\Users\ashort7\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\training\slot_creator.py", line 67, in _create_slot_var
    validate_shape=validate_shape)
  File "C:\Users\ashort7\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\ops\variable_scope.py", line 1262, in get_variable
    constraint=constraint)
  File "C:\Users\ashort7\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\ops\variable_scope.py", line 1097, in get_variable
    constraint=constraint)
  File "C:\Users\ashort7\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\ops\variable_scope.py", line 435, in get_variable
    constraint=constraint)
  File "C:\Users\ashort7\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\ops\variable_scope.py", line 404, in _true_getter
    use_resource=use_resource, constraint=constraint)
  File "C:\Users\ashort7\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\ops\variable_scope.py", line 806, in _get_single_variable
    constraint=constraint)
  File "C:\Users\ashort7\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\ops\variables.py", line 229, in __init__
    constraint=constraint)
  File "C:\Users\ashort7\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\ops\variables.py", line 366, in _init_from_args
    validate_shape=validate_shape).op
  File "C:\Users\ashort7\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\ops\state_ops.py", line 276, in assign
    validate_shape=validate_shape)
  File "C:\Users\ashort7\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\ops\gen_state_ops.py", line 62, in assign
    use_locking=use_locking, name=name)
  File "C:\Users\ashort7\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\ashort7\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\framework\ops.py", line 3160, in create_op
    op_def=op_def)
  File "C:\Users\ashort7\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\framework\ops.py", line 1625, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[3,7,1,72] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[Node: Variable_910/Adam/Assign = Assign[T=DT_FLOAT, _class=["loc:@Variable_910"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](Variable_910/Adam, Variable_910/Adam/Initializer/zeros)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

**Comment by androidbeepboop** [comment]
Hi poxvoculi,

Thanks for your response. It is still a problem, and I will examine what's going on with the CPU during the GPU pause. I'll post a screenshot next chance I get.

**Comment by androidbeepboop** [comment]
Here's a word doc with images of the afterburner output during a period when the GPU stalling is visible:
[afterburner logs.docx](https://github.com/tensorflow/tensorflow/files/1876339/afterburner.logs.docx)

It seems you're correct about the CPU idea; CPUs 1 and 2 (and some of the others) tend to exhibit high activity during the "GPU stalls". 

I'll upload a .py file and some test data with a version of my CNN that should hopefully replicate the issue later today.

**Comment by androidbeepboop** [comment]
The word doc I uploaded displays both CPU and GPU activity (though in separate images); is that what you're looking for? Note that the vertical line on the images is placed at the same time in each, so it should be easy to compare. Let me know if that's not what you're looking for.

**Comment by poxvoculi** [comment]
I do have something else in mind, I wonder what the CPU is doing between periods when the GPU is active.  Just knowing that it's consuming power is much less interesting that knowing what task it's doing and whether running the next step (or sequence of steps?) on the GPU requires waiting for that task.

You said:
"I'm using an evolutionary algorithm to optimize the hyperparameters of a CNN. However, over time, the GPU "waits" for greater and greater times between training cycles (afterburner visualization):"

Does your algorithm execute on the CPU between GPU runs?  Is it possible that your algorithm is more expensive than you anticipated?  Do you have a way of tracing the CPU activity during that time and identifying which subroutines it's executing in?

**Comment by poxvoculi** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by anant111** [comment]
hello, i have got the same error, once the gpu is used for training and then i tune the hyperparameters in the same script it shows out of memeory, how to resolve it?
