### ISSUE TITLE
contrib.nccl.broadcast raises UnimplementedError

### ISSUE THREAD

**Issue by benbarsdell** [tensorflow/tensorflow#17908]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: Docker image tensorflow/tensorflow:nightly-devel-gpu
- **TensorFlow version (use command below)**: nightly (also 1.7rc1)
- **Python version**: 2.7
- **Bazel version (if compiling from source)**: NA
- **GCC/Compiler version (if compiling from source)**: NA
- **CUDA/cuDNN version**: 7.0.5
- **GPU model and memory**: NA
- **Exact command to reproduce**:

Copying repro from https://github.com/tensorflow/tensorflow/issues/15425#issuecomment-361835192:

```
import tensorflow as tf
import tensorflow.contrib.nccl as nccl

if __name__ == '__main__':
    devices = ['/gpu:0', '/gpu:0']
    with tf.device(devices[0]):
        data0 = tf.constant([1.1, 2.2, 3.3, 4.4])
        received_tensor = nccl.broadcast(data0)
    received_tensors = []
    for device in devices[1:]:
        with tf.device(device):
            received_tensors.append(tf.identity(received_tensor))
    sess = tf.Session()
    sess.run(received_tensors)
```

### Describe the problem

```
Traceback (most recent call last):
  File "<stdin>", line 11, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 906, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1141, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1322, in _do_run
    run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1341, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnimplementedError: This op should be replaced during graph optimization.
	 [[Node: NcclBroadcast = NcclBroadcast[T=DT_FLOAT, shape=[4], _device="/job:localhost/replica:0/task:0/device:GPU:0"](Const)]]

Caused by op u'NcclBroadcast', defined at:
  File "<stdin>", line 5, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/nccl/python/ops/nccl_ops.py", line 187, in broadcast
    return gen_nccl_ops.nccl_broadcast(input=tensor, shape=tensor.shape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/nccl/ops/gen_nccl_ops.py", line 132, in nccl_broadcast
    "NcclBroadcast", input=input, shape=shape, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3305, in create_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1669, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

UnimplementedError (see above for traceback): This op should be replaced during graph optimization.
	 [[Node: NcclBroadcast = NcclBroadcast[T=DT_FLOAT, shape=[4], _device="/job:localhost/replica:0/task:0/device:GPU:0"](Const)]]
```

**Comment by rohan100jain** [comment]
I can reproduce the bug. Assigning.

**Comment by jxluo** [comment]
I get same issue on install from source tf-1.7.0

**Comment by xysmlx** [comment]
Get the same issue on TF-1.7 installing from source.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @chsigg: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @chsigg: It has been 32 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @chsigg: It has been 47 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @chsigg: It has been 62 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @chsigg: It has been 77 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by EFanZh** [comment]
Any updates on this? Is there any way to workaround this?

**Comment by tensorflowbutler** [comment]
Nagging Assignee @chsigg: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by enestaylan** [comment]
Hi @chsigg, is there any news here? I use tf 1.9.0 and have exactly the same problem. Thanks.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @chsigg: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by simtony** [comment]
Still got this problem with tf1.10

**Comment by simtony** [comment]
Any news here? @chsigg

**Comment by tensorflowbutler** [comment]
Nagging Assignee @chsigg: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by jeffdaily** [comment]
The file `nccl_rewrite.cc` was added by ca8af1d0dbb605087a4f8ae076188f2b9a26b1ba on Oct 15 2017.  Was it working back then?

**Comment by tensorflowbutler** [comment]
Nagging Assignee @chsigg: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @chsigg: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @chsigg: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.
