### ISSUE TITLE
TensorArray does not work inside `else` clause of `tf.cond`

### ISSUE THREAD

**Issue by iganichev** [tensorflow/tensorflow#17965]
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Custom code
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux 
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 'v1.5.0-0-g37aa430', '1.5.0'
- **Python version**:  2.7
- **Exact command to reproduce**:

```python
    import tensorflow as tf
    def body(v):
        m = tf.constant([v, v])
        ta = tf.TensorArray(dtype=tf.float32, size=1)
        t = ta.write(0, m)
        return t

    cond = tf.constant(False)
    t = tf.cond(cond, true_fn=lambda : body(2.0), false_fn=lambda : body(3.0))

    with tf.Session() as ss:
        print(ss.run(t.stack()))
```

The code above leads to the following error:

Traceback (most recent call last):
  File "./array_cond.py", line 69, in <module>
    print(ss.run(t.stack()))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1128, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1344, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1363, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Retval[0] does not have value

Interestingly if `False` is replace with `True` it works as expected.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @skye: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @skye: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @skye: It has been 63 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by t94126** [comment]
Hi, @iganichev I think I know the correct solution. (credit to my friends.)
You should move the .stack inside the body:

```
import tensorflow as tf

def body(v):
    m = tf.constant([v,v])
    ta = tf.TensorArray(dtype=tf.float32, size=3, dynamic_size=False)
    t = ta.write(0, m)
    return t.stack()

cond = tf.constant(False)
t = tf.cond(cond, true_fn=lambda: body(2.0), false_fn=lambda: body(3.0))
with tf.Session() as ss:
    print(ss.run(t))
```
Unfortunately, I cannot explain why. I will try to to do that and post later. I think I need check the doc of tf.cond
If anyone know how to explain, please also tell me. Thx!

**Comment by tensorflowbutler** [comment]
Nagging Assignee @skye: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @skye: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by t94126** [comment]
Hi, I think here is the problem:
the true_fn should accept a tensor object (e.g. t.stack() ). However, t is a tensorArray and directly return it will cause problem.
This issue should be be closed.

**Comment by zaxliu** [comment]
Is there any update?

**Comment by tensorflowbutler** [comment]
Nagging Assignee @skye: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @skye: It has been 33 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @skye: It has been 49 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @skye: It has been 65 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @skye: It has been 79 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @skye: It has been 94 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @skye: It has been 109 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @skye: It has been 125 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @skye: It has been 140 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by mohantym** [comment]
We see that you are using old version of Tensorflow which is officially considered as end of life, We recommend that you upgrade to 2.4 or later version and let us know if the issue still persists in newer versions .Please open a new issue in case you face any errors, we will get you the right help .Thanks!
