### ISSUE TITLE
AttributeError: '_LSTMModel' object has no attribute '_get_exogenous_embedding_shape'

### ISSUE THREAD

**Issue by gaceladri** [tensorflow/tensorflow#17976]
### System information
**Ubuntu 16.04**
**Tensorflow 1.6**

### Describe the problem

When I try to execute 

> **tensorflow/tensorflow/contrib/timeseries/examples/lstm.py**

 the next error appears:

```
WARNING:tensorflow:Using temporary folder as model directory: /tmp/tmp1pp2uy_k
Traceback (most recent call last):
  File "lstm.py", line 296, in <module>
    tf.app.run(main=main)
  File "/home/proto/anaconda3/envs/tensor/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 124, in run
    _sys.exit(main(argv))
  File "lstm.py", line 284, in main
    all_times, predictions) = train_and_predict()
  File "lstm.py", line 219, in train_and_predict
    estimator.train(input_fn=train_input_fn, steps=training_steps)
  File "/home/proto/anaconda3/envs/tensor/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 314, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/proto/anaconda3/envs/tensor/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 743, in _train_model
    features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
  File "/home/proto/anaconda3/envs/tensor/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 725, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/home/proto/anaconda3/envs/tensor/lib/python3.5/site-packages/tensorflow/contrib/timeseries/python/timeseries/head.py", line 225, in create_estimator_spec
    model=self.model, input_statistics=input_statistics)
  File "/home/proto/anaconda3/envs/tensor/lib/python3.5/site-packages/tensorflow/contrib/timeseries/python/timeseries/state_management.py", line 147, in initialize_graph
    self._start_state = model.get_start_state()
  File "lstm.py", line 114, in get_start_state
    tf.zeros(self._get_exogenous_embedding_shape(), dtype=self.dtype),
AttributeError: '_LSTMModel' object has no attribute '_get_exogenous_embedding_shape'
```

Seems that the pull is coming from @gunan, @tensorflower-gardener,  authored by @allenlavoie 

EDIT: If I hard-code the 'self._get_exogenous_emebedding_shape()' (line 114 in lstm.py file) to 0, I get the next error also:

```
Traceback (most recent call last):
  File "lstm.py", line 296, in <module>
    tf.app.run(main=main)
  File "/home/proto/anaconda3/envs/tensor/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 124, in run
    _sys.exit(main(argv))
  File "lstm.py", line 284, in main
    all_times, predictions) = train_and_predict()
  File "lstm.py", line 219, in train_and_predict
    estimator.train(input_fn=train_input_fn, steps=training_steps)
  File "/home/proto/anaconda3/envs/tensor/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 314, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/proto/anaconda3/envs/tensor/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 743, in _train_model
    features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
  File "/home/proto/anaconda3/envs/tensor/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 725, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/home/proto/anaconda3/envs/tensor/lib/python3.5/site-packages/tensorflow/contrib/timeseries/python/timeseries/head.py", line 228, in create_estimator_spec
    return self._train_ops(features)
  File "/home/proto/anaconda3/envs/tensor/lib/python3.5/site-packages/tensorflow/contrib/timeseries/python/timeseries/head.py", line 78, in _train_ops
    self.model, features, estimator_lib.ModeKeys.TRAIN)
  File "/home/proto/anaconda3/envs/tensor/lib/python3.5/site-packages/tensorflow/contrib/timeseries/python/timeseries/state_management.py", line 93, in define_loss
    model=model, features=features, mode=mode)
  File "/home/proto/anaconda3/envs/tensor/lib/python3.5/site-packages/tensorflow/contrib/timeseries/python/timeseries/state_management.py", line 182, in _define_loss_with_saved_state
    mode=mode)
  File "/home/proto/anaconda3/envs/tensor/lib/python3.5/site-packages/tensorflow/contrib/timeseries/python/timeseries/state_management.py", line 237, in _update_cached_states
    state=looked_up_state)
  File "/home/proto/anaconda3/envs/tensor/lib/python3.5/site-packages/tensorflow/contrib/timeseries/python/timeseries/model.py", line 588, in per_step_batch_loss
    features={key: value for key, value in features.items()
  File "/home/proto/anaconda3/envs/tensor/lib/python3.5/site-packages/tensorflow/contrib/timeseries/python/timeseries/model.py", line 296, in _process_exogenous_features
    trainable=True))
  File "/home/proto/anaconda3/envs/tensor/lib/python3.5/site-packages/tensorflow/contrib/layers/python/layers/feature_column_ops.py", line 221, in input_from_feature_columns
    cols_to_outs=cols_to_outs)
  File "/home/proto/anaconda3/envs/tensor/lib/python3.5/site-packages/tensorflow/contrib/layers/python/layers/feature_column_ops.py", line 104, in _input_from_feature_columns
    check_feature_columns(feature_columns)
  File "/home/proto/anaconda3/envs/tensor/lib/python3.5/site-packages/tensorflow/contrib/layers/python/layers/feature_column_ops.py", line 776, in check_feature_columns
    key = f.key
AttributeError: '_EmbeddingColumn' object has no attribute 'key'


```

**Comment by allenlavoie** [comment]
Try the version from the 1.6 branch: https://github.com/tensorflow/tensorflow/blob/r1.6/tensorflow/contrib/timeseries/examples/lstm.py

Or use a nightly if you're using the example at head.

**Comment by gaceladri** [comment]
Thanks for the fast response @allenlavoie. I will be using the last branch meanwhile. Thanks.
