### ISSUE TITLE
run_test_in_graph_and_eager_modes does not work

### ISSUE THREAD

**Issue by peastman** [tensorflow/tensorflow#18055]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS 10.13.3
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: v1.6.0-0-gd2e24b6039 1.6.0
- **Python version**: 3.6.1
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**: See below

I have code that was written to work in graph mode, and I am now converting it to work in eager mode as well.  I am trying to use the `run_test_in_graph_and_eager_modes` decorator to make my tests run in both modes.  When I add `@run_test_in_graph_and_eager_modes()` in front of a test method, it simply causes the test not to run at all, in either mode.  I run the tests with `nosetests` version 1.3.7.  There is no error message or any indication that something has gone wrong.  The decorated tests are just silently skipped.

**Comment by asimshankar** [comment]
Could you provide some more detail, or instructions to reproduce? Here's what I tried:

- Create `test.py`:
```python
import tensorflow as tf

class MyTest(tf.test.TestCase):
  @tf.contrib.eager.run_test_in_graph_and_eager_modes()
  def test_foo(self):
    print("Hello")

if __name__ == "__main__":
  tf.test.main()
```

- `python ./test.py`

And I see `Hello` printed twice, as expected.
So, if there is a bug, it's triggered by your specific use - if you could provide instructions to reproduce, we can investigate.

Thanks.

**Comment by peastman** [comment]
I tried your test, and sure enough if I run it directly it works.  However, if I run it using `nosetests` it gets skipped:

```
$ nosetests --nocapture -v test.py
Returns a TensorFlow Session for use in executing tests. ... ok

----------------------------------------------------------------------
Ran 1 test in 0.001s

OK
```

In addition, if I tell it to run just that one test rather than all tests in the file

```
$ nosetests test.py:MyTest.test_foo
```

then it fails:

```
Traceback (most recent call last):
  File "/Users/peastman/miniconda3/lib/python3.6/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/Users/peastman/miniconda3/lib/python3.6/site-packages/nose/loader.py", line 522, in makeTest
    return self._makeTest(obj, parent)
  File "/Users/peastman/miniconda3/lib/python3.6/site-packages/nose/loader.py", line 576, in _makeTest
    return parent(obj.__name__)
  File "/Users/peastman/miniconda3/lib/python3.6/site-packages/tensorflow/python/framework/test_util.py", line 708, in __init__
    super(TensorFlowTestCase, self).__init__(methodName)
  File "/Users/peastman/miniconda3/lib/python3.6/unittest/case.py", line 399, in __init__
    (self.__class__, methodName))
ValueError: no such test method in <class 'test.MyTest'>: decorated
```

**Comment by asimshankar** [comment]
I'm not familiar enough with `nosetests` to provide help here. From the stacktrace it seems that somehow the use of `nosetests` is resulting in an incorrect import of TensorFlow where it is looking for the `decorated` symbol in the wrong module.

Marking as "Community Support" since I don't believe anyone on the team here has the expertise to debug interactions with `nosetests`.

**Comment by tensorflowbutler** [comment]
As this issue has invited community support, please remove the assignee. Otherwise, remove the `community support` label. Thank you.
