### ISSUE TITLE
ImportError : Could not find 'msvcp140.dll'

### ISSUE THREAD

**Issue by shubhamtanwar23** [tensorflow/tensorflow#18116]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Window 7
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.5, 1.6, 1.7
- **Python version**: 3.6
- **Bazel version (if compiling from source)**: NA
- **GCC/Compiler version (if compiling from source)**: NA
- **CUDA/cuDNN version**: NA
- **GPU model and memory**: NA
- **Exact command to reproduce**: import tensorflow as tf

### Problem
I am using python 3.6 and have successfully installed tensorflow 1.7 via pip3 command. While importing tensorflow in python interpreter an OSError occurs and while handling the exception ImportError also occurs which gives the message that 'Couldnot find msvcp140.dll'. I checked that the dll files are present in the directory that is in the PATH variable and also installed the Visual C++ Redistributable as mentioned.

### Logs
>>> import tensorflow as tf
<module 'tensorflow.python.platform.build_info' from 'C:\\Python36\\lib\\site-packages\\tensorflow\\python\\platform\\build_info.py'>
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\tensorflow\python\platform\self_check.py",
 line 48, in preload_check
    ctypes.WinDLL(build_info.msvcp_dll_name)
  File "C:\Python36\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 is not a valid Win32 application
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python36\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "C:\Python36\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 30, in <module>
    self_check.preload_check()
  File "C:\Python36\lib\site-packages\tensorflow\python\platform\self_check.py",
 line 56, in preload_check
    % build_info.msvcp_dll_name)
ImportError: Could not find 'msvcp140.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. You may install this DLL by downloading Visual C++ 2015 Redistributable Update 3 from this URL:https://www.microsoft.com/en-us/download/details.aspx?id=53587

**Comment by mrry** [comment]
What result do you get if you type `where msvcp140.dll` in the same command prompt as you used for the Python interpreter?

**Comment by shubhamtanwar23** [comment]
C:\Windows\System32\msvcp140.dll
C:\Windows\SysWOW64\msvcp140.dll

**Comment by mrry** [comment]
Can you try running the following command at the same command prompt?

```
python -c "import ctypes; print(ctypes.WinDLL('msvcp140.dll'))"
```

**Comment by tensorflowbutler** [comment]
Nagging Assignee @mrry: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @mrry: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by grzegorz-swirski** [comment]
Installing the DLL as in the error message fixed the issue for me.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by JETTIDIVYA** [comment]
i have the same issue

**Comment by shathesh18** [comment]
Hi I am facing the same issue but in pycharm virtual environment. Any help is highly appreciated

**Comment by punyidea** [comment]
@shathesh18, I had the same issue. I then went [here (sorry for the German link)](https://support.microsoft.com/de-de/help/2977003/the-latest-supported-visual-c-downloads) and downoaded the  Microsoft Visual C++ Redistributable für Visual Studio 2015, 2017 und 2019 for my platform. The problem went away after restarting.

**Comment by smithkanzariya** [comment]
@punyidea, I had the same issue. It worked pretty neat for me, thanks.

**Comment by pkbagchi** [comment]
Just click this link https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads Then install

    x64: vc_redist.x64.exe

and restart your pc.

**Comment by YashTalaiche** [comment]
> Just click this link https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads Then install
> 
> ```
> x64: vc_redist.x64.exe
> ```
> 
> and restart your pc.

it not work in my PC

**Comment by Rohit5055** [comment]
Then Maybe you need to check the following things
1. Check the path variable it must be inside local/prpgrams/python39 if u have previously installed 32 bit python the path must be inside roaming
2. So make sure you hyave 64 bit python installed
3. C++ redistributable may vary for your system so download it according to your configuration
4.

**Comment by justanotheranonymoususer** [comment]
I had the same problem, this guide helped me:
https://winbindex.m417z.com/?file=msvcp140.dll
