### ISSUE TITLE
tfdbg error on windows 10

### ISSUE THREAD

**Issue by alanpurple** [tensorflow/tensorflow#18118]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Windows 10 x64 pro
- **TensorFlow installed from (source or binary)**:
binary 1.7.0 gpu win64
- **TensorFlow version (use command below)**:
1.7.0
- **Python version**: 
3.6.5
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
9.0/7.0
- **GPU model and memory**:
GTX1080 GDDR5X 8GB
- **Exact command to reproduce**:
python -m tensorflow.python.debug.examples.debug_mnist --debug

### Source code / logs

WARNING:tensorflow:From C:\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\datasets\mnist.py:290: Data
Set.__init__ (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future v
ersion.
Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
2018-03-30 20:50:57.501717: I T:\src\github\tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:140] Your CPU suppo
rts instructions that this TensorFlow binary was not compiled to use: AVX2
2018-03-30 20:50:57.892716: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1344] Found devi
ce 0 with properties:
name: GeForce GTX 1080 major: 6 minor: 1 memoryClockRate(GHz): 1.835
pciBusID: 0000:01:00.0
totalMemory: 8.00GiB freeMemory: 6.60GiB
2018-03-30 20:50:57.904881: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1423] Adding vis
ible gpu devices: 0
2018-03-30 20:50:58.560856: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:911] Device inte
rconnect StreamExecutor with strength 1 edge matrix:
2018-03-30 20:50:58.568769: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:917]      0
2018-03-30 20:50:58.574326: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:930] 0:   N
2018-03-30 20:50:58.578842: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1041] Created Te
nsorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6379 MB memory) -> physical GPU (device: 0, name: GeF
orce GTX 1080, pci bus id: 0000:01:00.0, compute capability: 6.1)
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\debug\cli\ui_factory.py", line 60, in get_ui
    from tensorflow.python.debug.cli import curses_ui
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\debug\cli\curses_ui.py", line 21, in <module>
    import curses
  File "C:\Anaconda3\lib\curses\__init__.py", line 13, in <module>
    from _curses import *
ModuleNotFoundError: No module named '_curses'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\debug\cli\ui_factory.py", line 63, in get_ui
    from tensorflow.python.debug.cli import readline_ui
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\debug\cli\readline_ui.py", line 20, in <module>
    import readline
ModuleNotFoundError: No module named 'readline'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\debug\examples\debug_mnist.py", line 193, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 126, in run
    _sys.exit(main(argv))
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\debug\examples\debug_mnist.py", line 136, in main
    acc = sess.run(accuracy, feed_dict=feed_dict(False))
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\debug\wrappers\framework.py", line 462, in run
    is_callable_runner=bool(callable_runner)))
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\debug\wrappers\local_cli_wrapper.py", line 255, in on_run_start

    self._prep_cli_for_run_start()
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\debug\wrappers\local_cli_wrapper.py", line 277, in _prep_cli_fo
r_run_start
    self._run_cli = ui_factory.get_ui(self._ui_type)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\debug\cli\ui_factory.py", line 71, in get_ui
    available_ui_types=available_ui_types)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\debug\cli\ui_factory.py", line 69, in get_ui
    raise ValueError("Exhausted all fallback ui_types.")
ValueError: Exhausted all fallback ui_types.

**Comment by pvaneck** [comment]
Take a look at the note at the top here: https://www.tensorflow.org/programmers_guide/debugger

You are probably missing the curses or pyreadline package on your system which tfdbg relies on for the user interface.

For Windows, I say go ahead and try out the curses wheel for your system on the site mentioned in those docs, as I think it's a nicer looking UI than readline. If I recall correctly, with windows curses-based tfdbg, you need to do long mouse presses (click and hold) for button/link presses in the terminal.

**Comment by alanpurple** [comment]
@pvaneck 

thx, solved after install pyreadline( using conda ) and unofficial curses 2.2

**Comment by pournami123** [comment]
@alapurple how did you install unofficial curses 2.2. can you please tell?
