### ISSUE TITLE
Segmentation fault with TF 1.7 built from source with MKL support

### ISSUE THREAD

**Issue by zhiz21** [tensorflow/tensorflow#18133]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: NO
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  Amazon Linux (Linux version 4.9.85-38.58.amzn1.x86_64)
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 1.7.0
- **Python version**: 2.7
- **Bazel version (if compiling from source)**: 0.11.1
- **GCC/Compiler version (if compiling from source)**: 5.3.0
- **CUDA/cuDNN version**: None
- **GPU model and memory**: None
- **Exact command to reproduce**:
```
git clone -b r1.7 https://github.com/tensorflow/tensorflow.git
cd tensorflow
./configure
bazel build --jobs $(nproc) --config=opt --config=mkl --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" --copt="-DEIGEN_USE_VML" //tensorflow/tools/pip_package:build_pip_package

git clone https://github.com/tensorflow/models.git
cd models/tutorials/image/cifar10/
python cifar10_train.py
```
**Result:**
```
[ec2-user@ip-xxx-xx-xx-xxx cifar10]$ python cifar10_train.py
Filling queue with 20000 CIFAR images before starting to train. This will take a few minutes.
Segmentation fault
```

### Describe the problem
I tried to compile TF 1.7 from source with MKL and AVX512 support on my AWS EC2 C5.18xlarge instance. 
This Segmentation fault appeared when running cifar10_train.py. This error appeared with TF1.5 as well and TF 1.6 fixed it, but now it appears again with 1.7. 
I have tried to compile TF without AVX512 with following commands and this error didn't appear again:
```
bazel build --jobs $(nproc) --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" --config=mkl --copt=-msse4.1 --copt=-msse4.2 --copt=-mavx2 --copt=-mavx --copt=-mfma --copt="-DEIGEN_USE_VML" //tensorflow/tools/pip_package:build_pip_package
```
So I'm guessing this issue is related with AVX512.

**Comment by yaroslavvb** [comment]
Can you do backtrace on segfault?

ulimit -Sc unlimited
<crashy script>
gdb python
core core
bt

**Comment by zhiz21** [comment]
@yaroslavvb Thank you for your reply, this is what I got with your commands, but I'm not sure whether this is what you want for traceback
```
[ec2-user@ip cifar10]$ python cifar10_train.py
Filling queue with 20000 CIFAR images before starting to train. This will take a few minutes.
Traceback (most recent call last):
  File "cifar10_train.py", line 127, in <module>
    tf.app.run()
  File "/usr/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "cifar10_train.py", line 123, in main
    train()
  File "cifar10_train.py", line 115, in train
    mon_sess.run(train_op)
  File "/usr/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 546, in run
    run_metadata=run_metadata)
  File "/usr/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 1022, in run
    run_metadata=run_metadata)
  File "/usr/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 1113, in run
    raise six.reraise(*original_exc_info)
  File "/usr/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 1098, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 1170, in run
    run_metadata=run_metadata)
  File "/usr/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 950, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 905, in run
    run_metadata_ptr)
  File "/usr/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1140, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    run_metadata)
  File "/usr/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Nan in summary histogram for: conv2/conv2/conv2/activations
	 [[Node: conv2/conv2/conv2/activations = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](conv2/conv2/conv2/activations/tag, conv2/conv2)]]

Caused by op u'conv2/conv2/conv2/activations', defined at:
  File "cifar10_train.py", line 127, in <module>
    tf.app.run()
  File "/usr/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "cifar10_train.py", line 123, in main
    train()
  File "cifar10_train.py", line 72, in train
    logits = cifar10.inference(images)
  File "/home/ec2-user/src/models/tutorials/image/cifar10/cifar10.py", line 231, in inference
    _activation_summary(conv2)
  File "/home/ec2-user/src/models/tutorials/image/cifar10/cifar10.py", line 93, in _activation_summary
    tf.summary.histogram(tensor_name + '/activations', x)
  File "/usr/lib/python2.7/dist-packages/tensorflow/python/summary/summary.py", line 196, in histogram
    tag=tag, values=values, name=scope)
  File "/usr/lib/python2.7/dist-packages/tensorflow/python/ops/gen_logging_ops.py", line 282, in _histogram_summary
    "HistogramSummary", tag=tag, values=values, name=name)
  File "/usr/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3290, in create_op
    op_def=op_def)
  File "/usr/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1654, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Nan in summary histogram for: conv2/conv2/conv2/activations
	 [[Node: conv2/conv2/conv2/activations = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](conv2/conv2/conv2/activations/tag, conv2/conv2)]]

[ec2-user@ip cifar10]$ gdb python
GNU gdb (GDB) Amazon Linux (7.6.1-64.33.amzn1)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-amazon-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/bin/python2.7...(no debugging symbols found)...done.
Missing separate debuginfos, use: debuginfo-install python26-2.6.9-2.89.amzn1.x86_64 python27-2.7.13-2.122.amzn1.x86_64 python34-3.4.7-1.38.amzn1.x86_64
(gdb) core core
/home/ec2-user/src/models/tutorials/image/cifar10/core: No such file or directory.
(gdb) bt
No stack.
(gdb)
```

**Comment by yaroslavvb** [comment]
It looks like your error is a NaN rather than segmentation fault, this is why there's no core file

**Comment by zhiz21** [comment]
@yaroslavvb Thanks! I agree with you, but why this happened only when I compiled with AVX512 support? Do you have any idea about how to solve it?

**Comment by yaroslavvb** [comment]
I've seen segfaults happening when applying avx instruction to memory that has not been 64-byte aligned. The first step would be to obtain core file and look at backtrace.

**Comment by jbobba** [comment]
@zhiz21 Can you check if https://github.com/tensorflow/tensorflow/pull/18411 addresses your issue?

**Comment by mdfaijul** [comment]
@jbobba @zhiz21 Not sure if #18411 will resolve this issue, because #18411 is not not related to MKL.

**Comment by bignamehyp** [comment]
@zhiz21 can you please obtain the core file?
Thanks.

**Comment by wei-v-wang** [comment]
Related to issue of: https://github.com/tensorflow/tensorflow/issues/17273 
We are working on this AVX512 issue with Eigen. As a workaround, please configure AND compile with AVX2 only (i.e. use -march=broadwell instead of -march=native).

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by wei-v-wang** [comment]
@zhiz21 Can you please try compiling wih -march=broadwell instead of -march=native and see if problems go away? FYI we are working on fixing Eigen AVX512 related issues. Thanks!

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
It has been 29 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
It has been 44 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
We are closing this issue for now due to lack of activity. Please comment if this is still an issue for you. Thanks!
