### ISSUE TITLE
Error in restoring the tensorflow model and metagraph while using seq2seq and attention model.

### ISSUE THREAD

**Issue by sfarkya** [tensorflow/tensorflow#18139]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: pip3 install tensorflow-gpu==1.0.0
- **TensorFlow version (use command below)**: 1.0.0
- **Python version**: 3.5.2
- **Bazel version (if compiling from source)**:No
- **GCC/Compiler version (if compiling from source)**: 5.4.0
- **CUDA/cuDNN version**: 8/7
- **GPU model and memory**:GTX 1060X and 6GB
- **Exact command to reproduce**:

I am using seq2seq model with attention mechanism for a chatbot as given in the [link](https://github.com/Currie32/Chatbot-from-Movie-Dialogue/blob/master/Chatbot_Attention.ipynb), I am able to train the model and save it but when I am trying to restore the model I am getting an error:

Code for loading the model:
```
with tf.Session() as sess:
        #try:
        saver = tf.train.import_meta_graph('/media/saurabh/New Volume/nlp_ucf/project/model/model_0.ckpt.meta')
        saver.restore(sess, '/media/saurabh/New Volume/nlp_ucf/project/model/model_0.ckpt.data-00000-of-00001')
```
The error I am getting is

```
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1060, pci bus id: 0000:01:00.0)
Traceback (most recent call last):
  File "start_something.py", line 254, in <module>
    saver = tf.train.import_meta_graph('/media/saurabh/New Volume/nlp_ucf/project/model/model_0.ckpt.meta')
  File "/home/saurabh/tfenv3/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1577, in import_meta_graph
    **kwargs)
  File "/home/saurabh/tfenv3/lib/python3.5/site-packages/tensorflow/python/framework/meta_graph.py", line 498, in import_scoped_meta_graph
    producer_op_list=producer_op_list)
  File "/home/saurabh/tfenv3/lib/python3.5/site-packages/tensorflow/python/framework/importer.py", line 259, in import_graph_def
    raise ValueError('No op named %s in defined operations.' % node.op)
ValueError: No op named attn_add_fun_f32f32f32 in defined operations.
```
I am even unable to understand the error. Does anyone have any clue about it? I was able to find one more person with a similar issue on StackOverflow but couldn't understand what exactly is the solution?

**Comment by tensorflowbutler** [comment]
Nagging Assignee @rohan100jain: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @rohan100jain: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @rohan100jain: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by sonu107** [comment]
@sfarkya Is this issue solved?

**Comment by rohan100jain** [comment]
Euguene can you take a look?

The library code is pretty old, but relevant line seems to be  and I was able to dig it out at https://github.com/tensorflow/tensorflow/blob/r1.0/tensorflow/contrib/seq2seq/python/ops/attention_decoder_fn.py

My understand was that calling the function should have added it to the graph at train time, so it puzzling a bit that on restore it cant find it.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @ebrevdo: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @ebrevdo: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by ebrevdo** [comment]
Try using a newer version of tensorflow for both saving and loading the graph

**Comment by tensorflowbutler** [comment]
Nagging Assignee @ebrevdo: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.
