### ISSUE TITLE
Missing @grpc//third_party/address_sorting

### ISSUE THREAD

**Issue by fat-tire** [tensorflow/tensorflow#18152]
I think a [regression was introduced recently](https://github.com/tensorflow/tensorflow/commit/f80486324807181614ac71367dbb9cf588aa2804#diff-bb845bf0c867fef59b6527c0946799f9R116) when doing a new cpu build:

`failed; build aborted: no such package '@grpc//third_party/address_sorting': java.io.IOException: Error downloading [https://mirror.bazel.build/github.com/grpc/grpc/archive/bd6bdf93279a39a8cd92978fd7c9d14eccd98fc2.tar.gz, https://github.com/grpc/grpc/archive/bd6bdf93279a39a8cd92978fd7c9d14eccd98fc2.tar.gz] `

Reverting this commit allowed the build to continue.

Update:  building origin/master

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by fat-tire** [comment]
No custom code.  This was building TF from source on Ubuntu.  origin/master branch.  bazel release 0.11.1.  No CUDA/cuDNN.  No GPU at all.

Exact commands to reproduce the error is a simple build as described in the "building from source" instructions.

Cheers

**Comment by kpayson64** [comment]
@apolcyn
@nicolasnoble

**Comment by apolcyn** [comment]
I'm wondering if this is an upstream issue in [grpc](https://github.com/grpc/grpc/tree/master/third_party/address_sorting).

@fat-tire do you have command lines to reproduce?

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by apolcyn** [comment]
I'm currently trying to repro from Tensorflow's master branch (commit 714f3c4f2f901e865bfcbf830485adafb92dca48), with ubuntu 16.04 and bazel 0.13.1 (I'll try bazel 0.11.1 next).

I'm trying to follow the [instructions for install tensorflow from source](https://www.tensorflow.org/install/install_sources), but I'm stumbling on what looks like unrelated issues and I'm not able to reproduce so far. @fat-tire can you please post more details if you have any?E.g., are you following [these source build instructions](https://www.tensorflow.org/install/install_sources), and using the `configure` defaults? Or, do we know if this is still an issue?

Probably a minor issue but FWIW, after following the "install tensorflow from source" instructions, using python 2.7, and using all of the defaults in the `configure` script, I first ran into an issue with the `enum` module not being available (probably because I tried the python2.7 route). 

After installing the `enum` module, my bazel build command (`bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package`) now fails with:

```
[4,403 / 8,171] Executing genrule //tensorflow/python:framework/fast_tensor_util.pyx_cython_translation; 0s local
ERROR: /src/tensorflow/tensorflow/tools/api/generator/BUILD:27:1: Executing genrule //tensorflow/tools/api/generator:python_api_gen failed (Exit 1)
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/1c025c2968c1aa16bac5eca67aaf21d1/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/tools/api/generator/create_python_api.runfiles/org_tensorflow/tensorflow/tools/api/generator/create_python_api.py", line 26, in <module>
    from tensorflow import python  # pylint: disable=unused-import
  File "/root/.cache/bazel/_bazel_root/1c025c2968c1aa16bac5eca67aaf21d1/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/tools/api/generator/create_python_api.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 63, in <module>
    from tensorflow.python.framework.framework_lib import *  # pylint: disable=redefined-builtin
  File "/root/.cache/bazel/_bazel_root/1c025c2968c1aa16bac5eca67aaf21d1/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/tools/api/generator/create_python_api.runfiles/org_tensorflow/tensorflow/python/framework/framework_lib.py", line 52, in <module>
    from tensorflow.python.framework.importer import import_graph_def
  File "/root/.cache/bazel/_bazel_root/1c025c2968c1aa16bac5eca67aaf21d1/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/tools/api/generator/create_python_api.runfiles/org_tensorflow/tensorflow/python/framework/importer.py", line 32, in <module>
    from tensorflow.python.framework import function
  File "/root/.cache/bazel/_bazel_root/1c025c2968c1aa16bac5eca67aaf21d1/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/tools/api/generator/create_python_api.runfiles/org_tensorflow/tensorflow/python/framework/function.py", line 37, in <module>
    from tensorflow.python.ops import variable_scope as vs
  File "/root/.cache/bazel/_bazel_root/1c025c2968c1aa16bac5eca67aaf21d1/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/tools/api/generator/create_python_api.runfiles/org_tensorflow/tensorflow/python/ops/variable_scope.py", line 197, in <module>
    """
AttributeError: 'int' object attribute '__doc__' is read-only
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 35.977s, Critical Path: 21.32s
INFO: 1 process, local.
FAILED: Build did NOT complete successfully
```

**Comment by tensorflowbutler** [comment]
It has been 18 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
It has been 33 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
We are closing this issue for now due to lack of activity. Please comment if this is still an issue for you. Thanks!

**Comment by zhosteven** [comment]
WARNING: The following configs were expanded more than once: [cuda]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
DEBUG: /root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:91:3: 
Auto-Configuration Warning: 'TMP' environment variable is not set, using 'C:\Windows\Temp' as default
WARNING: /root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/external/protobuf_archive/WORKSPACE:1: Workspace name in /root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/external/protobuf_archive/WORKSPACE (@com_google_protobuf) does not match the name given in the repository's definition (@protobuf_archive); this will cause a build error in future versions
WARNING: /root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/external/absl_py/WORKSPACE:1: Workspace name in /root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/external/absl_py/WORKSPACE (@io_abseil_py) does not match the name given in the repository's definition (@absl_py); this will cause a build error in future versions
WARNING: /root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/external/flatbuffers/WORKSPACE:1: Workspace name in /root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/external/flatbuffers/WORKSPACE (@com_github_google_flatbuffers) does not match the name given in the repository's definition (@flatbuffers); this will cause a build error in future versions
ERROR: /root/tensorflow/tensorflow/tools/pip_package/BUILD:123:1: no such package '@grpc//third_party/address_sorting': java.io.IOException: thread interrupted and referenced by '//tensorflow/tools/pip_package:licenses'
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: no such package '@grpc//third_party/address_sorting': java.io.IOException: thread interrupted
INFO: Elapsed time: 52.940s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (172 packages loaded)
