### ISSUE TITLE
tensorboard take an TypeError after change tensorflow-cpu to tensorflow-gpu installed by pip 

### ISSUE THREAD

**Issue by Geek-Peng** [tensorflow/tensorflow#18167]
error messages are as follows：
Traceback (most recent call last):
File "e:\anaconda\lib\runpy.py", line 184, in _run_module_as_main
"main", mod_spec)
File "e:\anaconda\lib\runpy.py", line 85, in run_code
exec(code, run_globals)
File "E:\Anaconda\Scripts\tensorboard.exe_main.py", line 5, in 
File "e:\anaconda\lib\site-packages\tensorboard\main.py", line 30, in 
from tensorboard import default
File "e:\anaconda\lib\site-packages\tensorboard\default.py", line 35, in 
from tensorboard.plugins.audio import audio_plugin
File "e:\anaconda\lib\site-packages\tensorboard\plugins\audio\audio_plugin.py", line 30, in 
from tensorboard.plugins.audio import metadata
File "e:\anaconda\lib\site-packages\tensorboard\plugins\audio\metadata.py", line 22, in 
from tensorboard.plugins.audio import plugin_data_pb2
File "e:\anaconda\lib\site-packages\tensorboard\plugins\audio\plugin_data_pb2.py", line 63, in 
options=None, file=DESCRIPTOR),
TypeError: init() got an unexpected keyword argument 'file'

before i changed the version，tensorboard worked，i don't know whether the tensorboard arguments are different between cpu version and gpu version
I will appreciate for your help

OS Platform and Distribution ： windows 10
TensorFlow installed from： pip
TensorFlow version： tensorflow-gpu 1.7
CUDA/cuDNN version： cuda 9.0 cudnn9.0

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by Geek-Peng** [comment]
OS Platform and Distribution ：   windows 10
TensorFlow installed from： pip 
TensorFlow version： tensorflow-gpu 1.7
CUDA/cuDNN version： cuda 9.0   cudnn9.0
