### ISSUE TITLE
Tensorboard has takew

### ISSUE THREAD

**Issue by Geek-Peng** [tensorflow/tensorflow#18166]

**Comment by Geek-Peng** [comment]
error messages are as follows：
Traceback (most recent call last):
  File "e:\anaconda\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "e:\anaconda\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\Anaconda\Scripts\tensorboard.exe\__main__.py", line 5, in <module>
  File "e:\anaconda\lib\site-packages\tensorboard\main.py", line 30, in <module>
    from tensorboard import default
  File "e:\anaconda\lib\site-packages\tensorboard\default.py", line 35, in <module>
    from tensorboard.plugins.audio import audio_plugin
  File "e:\anaconda\lib\site-packages\tensorboard\plugins\audio\audio_plugin.py", line 30, in <module>
    from tensorboard.plugins.audio import metadata
  File "e:\anaconda\lib\site-packages\tensorboard\plugins\audio\metadata.py", line 22, in <module>
    from tensorboard.plugins.audio import plugin_data_pb2
  File "e:\anaconda\lib\site-packages\tensorboard\plugins\audio\plugin_data_pb2.py", line 63, in <module>
    options=None, file=DESCRIPTOR),
TypeError: __init__() got an unexpected keyword argument 'file'

before i changed the version，tensorboard worked，i don't know whether the tensorboard arguments are different between cpu version and gpu version
I will appreciate for your help
