### ISSUE TITLE
Tensorflow version of word2vec issue with huge corpora

### ISSUE THREAD

**Issue by JosuGoiko** [tensorflow/tensorflow#1820]
Hi All,

I have the pip wheel distribution of Tensorflow r7.1 in Red Hat 6 in our cluster.

My issue is that I wanted to extract the embedding from a huge corpora (5*10⁹ tokens), but  the 32 bit "corpus_size_" counter in "word2vec_kernel.cc" is not enough. It seems that it is not so straightforward to fix it (changing the counter to int64). 

I have seen that this very error was reported last  17th of Dec 2015 in issue #531.

I also receive the following error:

W tensorflow/models/embedding/word2vec_kernels.cc:59] Invalid argument: The text file wbu.txt contains too little data: -522037214 words
E tensorflow/core/framework/op_segment.cc:53] Create kernel failed: Invalid argument: The text file wbu.txt contains too little data: -522037214 words
E tensorflow/core/common_runtime/executor.cc:275] Executor failed to create kernel. Invalid argument: The text file wbu.txt contains too little data: -522037214 words
     [[Node: Skipgram = Skipgram[batch_size=16, filename="wbu.txt", min_count=5, subsample=0.001, window_size=5, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
Traceback (most recent call last):
  File "word2vec_minibatch.py", line 425, in <module>
    tf.app.run()
  File "/opt/python-2.7/lib/python2.7/site-packages/tensorflow/python/platform/default/_app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "word2vec_minibatch.py", line 411, in main
    model = Word2Vec(opts, session)
  File "word2vec_minibatch.py", line 175, in __init__
    self.build_graph()
  File "word2vec_minibatch.py", line 312, in build_graph
    opts.words_per_epoch) = self._session.run([words, counts, words_per_epoch])
  File "/opt/python-2.7/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 315, in run
    return self._run(None, fetches, feed_dict)
  File "/opt/python-2.7/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 511, in _run
    feed_dict_string)
  File "/opt/python-2.7/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 564, in _do_run
    target_list)
  File "/opt/python-2.7/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 586, in _do_call
    e.code)
tensorflow.python.framework.errors.InvalidArgumentError: The text file wbu.txt contains too little data: -522037214 words
     [[Node: Skipgram = Skipgram[batch_size=16, filename="wbu.txt", min_count=5, subsample=0.001, window_size=5, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
Caused by op u'Skipgram', defined at:
  File "word2vec_minibatch.py", line 425, in <module>
    tf.app.run()
  File "/opt/python-2.7/lib/python2.7/site-packages/tensorflow/python/platform/default/_app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "word2vec_minibatch.py", line 411, in main
    model = Word2Vec(opts, session)

Thanx

**Comment by kashif** [comment]
The issue seems to be that `corpus_size_` is an int rather than long and so overflows...

**Comment by zffchen78** [comment]
To deal w/ a large text corpus while still using a single process, mainly we need to change the code to avoid loading the text file in memory in whole and instead use LineReader to maintain a sliding window over the corpus.

**Comment by shkarupa-alex** [comment]
Got same issue when dealing with wikipedia corpus.
But error message differs a bit:

> W tensorflow/core/framework/op_kernel.cc:890] Invalid argument: wiki_combined.txt
> E tensorflow/core/framework/op_segment.cc:53] Create kernel failed: Invalid argument: wiki_combined.txt
> E tensorflow/core/common_runtime/executor.cc:332] Executor failed to create kernel. Invalid argument: wiki_combined.txt

TensorFlow v0.8.0rc0

**Comment by suiyuan2009** [comment]
any update? the link [](https://tensorflow-review.googlesource.com/#/c/1252/) in #531 is invalid

**Comment by Robin-des-Bois** [comment]
Maybe this helps someone: 
For me, It still does not work on OS X using clang (7.3.0) but it works on CentOS 6 using GCC (4.8.2 and 4.9.2).

**Comment by ravyg** [comment]
I have to processes around 30 million tweets text with Tensorflow based word2vec implementation. I have data in json files saved on bases of daily streaming. Is there a way I can batch (queue) feed data from multiple files to word2vec? Please help!

**Comment by gunan** [comment]
I am closing this issue due to inactivity.
Also, we moved word2vec to our models repo. 
If this is still a problem, please file an issue in the models repository.
