### ISSUE TITLE
tensorflow object detection training on own data

### ISSUE THREAD

**Issue by vibhuti19** [tensorflow/tensorflow#18239]
I want to use the tensorflow object detection api for my own objects, so I am using the ssd_mobilenet_v1_coco and I have made the necessary changes in the config files and all and now after I run my train.py file through the following command:

python3 train.py --logtostderr --train_dir=data/ --pipeline_config_path=data/ssd_mobilenet_v1_pets.config

I get this error:

2018-04-04 21:42:05.832786: I tensorflow/core/common_runtime/bfc_allocator.cc:67                               9] 2 Chunks of size 4194304 totalling 8.00MiB
2018-04-04 21:42:05.832801: I tensorflow/core/common_runtime/bfc_allocator.cc:67                               9] 2 Chunks of size 4718592 totalling 9.00MiB
2018-04-04 21:42:05.832817: I tensorflow/core/common_runtime/bfc_allocator.cc:68                               3] Sum Total of in-use chunks: 50.14MiB
2018-04-04 21:42:05.832837: I tensorflow/core/common_runtime/bfc_allocator.cc:68                               5] Stats:
Limit:                   701038592
InUse:                    52573952
MaxInUse:                 75702272
NumAllocs:                    6172
MaxAllocSize:              4718592

2018-04-04 21:42:05.832996: W tensorflow/core/common_runtime/bfc_allocator.cc:27                               7] *__********__________________________________________________________________                               _______________________
Traceback (most recent call last):
  File "/home/16mcmt36/anaconda3/envs/object_detection/lib/python3.5/site-packag                               es/tensorflow/python/client/session.py", line 1323, in _do_call
    return fn(*args)
  File "/home/16mcmt36/anaconda3/envs/object_detection/lib/python3.5/site-packag                               es/tensorflow/python/client/session.py", line 1302, in _run_fn
    status, run_metadata)
  File "/home/16mcmt36/anaconda3/envs/object_detection/lib/python3.5/site-packag                               es/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InternalError: Dst tensor is not initial                               ized.
         [[Node: prefetch_queue_Dequeue/_3249 = _Recv[client_terminated=false, r                               ecv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:loc                               alhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="e                               dge_912_prefetch_queue_Dequeue", tensor_type=DT_FLOAT, _device="/job:localhost/r                               eplica:0/task:0/device:GPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/16mcmt36/anaconda3/envs/object_detection/lib/python3.5/site-packag                               es/tensorflow/python/training/supervisor.py", line 954, in managed_session
    yield sess
  File "/home/16mcmt36/anaconda3/envs/object_detection/lib/python3.5/site-packag                               es/tensorflow/contrib/slim/python/slim/learning.py", line 763, in train
    sess, train_op, global_step, train_step_kwargs)
  File "/home/16mcmt36/anaconda3/envs/object_detection/lib/python3.5/site-packag                               es/tensorflow/contrib/slim/python/slim/learning.py", line 487, in train_step
    run_metadata=run_metadata)
  File "/home/16mcmt36/anaconda3/envs/object_detection/lib/python3.5/site-packag                               es/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/home/16mcmt36/anaconda3/envs/object_detection/lib/python3.5/site-packag                               es/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/16mcmt36/anaconda3/envs/object_detection/lib/python3.5/site-packag                               es/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/home/16mcmt36/anaconda3/envs/object_detection/lib/python3.5/site-packag                               es/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Dst tensor is not initial                               ized.
         [[Node: prefetch_queue_Dequeue/_3249 = _Recv[client_terminated=false, r                               ecv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:loc                               alhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="e                               dge_912_prefetch_queue_Dequeue", tensor_type=DT_FLOAT, _device="/job:localhost/r                               eplica:0/task:0/device:GPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 163, in <module>
    tf.app.run()
  File "/home/16mcmt36/anaconda3/envs/object_detection/lib/python3.5/site-packag                               es/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train.py", line 159, in main
    worker_job_name, is_chief, FLAGS.train_dir)
  File "/home/16mcmt36/models/object_detection/trainer.py", line 332, in train
    saver=saver)
  File "/home/16mcmt36/anaconda3/envs/object_detection/lib/python3.5/site-packag                               es/tensorflow/contrib/slim/python/slim/learning.py", line 775, in train
    sv.stop(threads, close_summary_writer=True)
  File "/home/16mcmt36/anaconda3/envs/object_detection/lib/python3.5/contextlib.                               py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/16mcmt36/anaconda3/envs/object_detection/lib/python3.5/site-packag                               es/tensorflow/python/training/supervisor.py", line 964, in managed_session
    self.stop(close_summary_writer=close_summary_writer)
  File "/home/16mcmt36/anaconda3/envs/object_detection/lib/python3.5/site-packag                               es/tensorflow/python/training/supervisor.py", line 792, in stop
    stop_grace_period_secs=self._stop_grace_secs)
  File "/home/16mcmt36/anaconda3/envs/object_detection/lib/python3.5/site-packag                               es/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/home/16mcmt36/anaconda3/envs/object_detection/lib/python3.5/site-packag                               es/six.py", line 693, in reraise
    raise value
  File "/home/16mcmt36/anaconda3/envs/object_detection/lib/python3.5/site-packag                               es/tensorflow/python/training/coordinator.py", line 296, in stop_on_exception
    yield
  File "/home/16mcmt36/anaconda3/envs/object_detection/lib/python3.5/site-packag                               es/tensorflow/python/training/coordinator.py", line 494, in run
    self.run_loop()
  File "/home/16mcmt36/anaconda3/envs/object_detection/lib/python3.5/site-packag                               es/tensorflow/python/training/supervisor.py", line 994, in run_loop
    self._sv.global_step])
  File "/home/16mcmt36/anaconda3/envs/object_detection/lib/python3.5/site-packag                               es/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/home/16mcmt36/anaconda3/envs/object_detection/lib/python3.5/site-packag                               es/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/16mcmt36/anaconda3/envs/object_detection/lib/python3.5/site-packag                               es/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/home/16mcmt36/anaconda3/envs/object_detection/lib/python3.5/site-packag                               es/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Dst tensor is not initialized.
         [[Node: prefetch_queue_Dequeue/_21 = _Recv[client_terminated=false, rec                               v_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:local                               host/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edg                               e_379_prefetch_queue_Dequeue", tensor_type=DT_FLOAT, _device="/job:localhost/rep                               lica:0/task:0/device:GPU:0"]()]]
sorflow

Please help...

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
It has been 21 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by kalpitsmehta** [comment]
@vibhuti19  Were you able to resolve this?

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
It has been 29 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
It has been 44 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by vibhuti19** [comment]
No

**Comment by achowdhery** [comment]
@vibhuti19 Are you able to use Transfer learning as suggested in the tutorial?

**Comment by vibhuti19** [comment]
I was able to do my experiments this issue can be closed.

**Comment by vibhuti19** [comment]
I was able to do my experiments this issue can be closed.
