### ISSUE TITLE
Failed to load the native TensorFlow runtime.

### ISSUE THREAD

**Issue by tolotrasamuel** [tensorflow/tensorflow#18329]
------------------------

### System information

- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10 Pro
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: tensorflow-gpu (1.7.0). 
- **Python version**:  3.5.5 
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: Cudnn 5,  Cudnn 6 with Cuda 8  and Cudnn 7 with Cuda 9 
- **GPU model and memory**: 3*GeForce GTX 1060 6G  MSI
- **Exact command to reproduce**: import tensorflow

### Describe the problem
My issue is I cannot even import tensorflow. I takes 2 minutes to load and output this error: 

### Source code / logs

```

(tensorflow) C:\Users\Technotronics Ltd\Documents\AI\nlp>python
Python 3.5.5 |Anaconda, Inc.| (default, Mar 12 2018, 17:44:09) [MSC
v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
Traceback (most recent call last):
Traceback (most recent call last):


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Technotronics
Ltd\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\__init__.py",
line 24, in <module>
    from tensorflow.python import *  # pylint: disable=redefined-builtin
  File "C:\Users\Technotronics
Ltd\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\__init__.py",
line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Technotronics
Ltd\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\pywrap_tensorflow.py",
line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Technotronics
Ltd\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\pywrap_tensorflow.py",
line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Technotronics
Ltd\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py",
line 18, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Technotronics
Ltd\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py",
line 17, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Users\Technotronics
Ltd\AppData\Local\conda\conda\envs\tensorflow\lib\importlib\__init__.py",
line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed: A dynamic link library (DLL)
initialization routine failed.


Failed to load the native TensorFlow runtime.

```

I stumbled upon this [script](https://gist.github.com/mrry/ee5dbcfdd045fa48a27d56664411d41c) that checks the tensorflow package but it tells me that all the required DLLs appear to be present but Failed to import the TensorFlow module. 

```

ERROR: Failed to import the TensorFlow module.

WARNING! This script is no longer maintained!
=============================================
Since TensorFlow 1.4, the self-check has been integrated with TensorFlow itself,
and any missing DLLs will be reported when you execute the `import tensorflow`
statement. The error messages printed below refer to TensorFlow 1.3 and earlier,
and are inaccurate for later versions of TensorFlow.

- Python version is 3.5.

- TensorFlow is installed at: C:\Users\Technotronics
Ltd\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow

- All required DLLs appear to be present. Please open an issue on the
  TensorFlow GitHub page: https://github.com/tensorflow/tensorflow/issues
```
I am totally out of clue now. Please help

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tolotrasamuel** [comment]
------------------------

### System information

- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10 Pro
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: tensorflow-gpu (1.7.0). 
- **Python version**:  3.5.5 
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: Cudnn 5,  Cudnn 6 with Cuda 8  and Cudnn 7 with Cuda 9 
- **GPU model and memory**: 3*GeForce GTX 1060 6G  MSI
- **Exact command to reproduce**: import tensorflow


### Describe the problem
My issue is I cannot even import tensorflow. I takes 2 minutes to load and output this error: 

### Source code / logs

```

(tensorflow) C:\Users\Technotronics Ltd\Documents\AI\nlp>python
Python 3.5.5 |Anaconda, Inc.| (default, Mar 12 2018, 17:44:09) [MSC
v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
Traceback (most recent call last):
Traceback (most recent call last):


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Technotronics
Ltd\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\__init__.py",
line 24, in <module>
    from tensorflow.python import *  # pylint: disable=redefined-builtin
  File "C:\Users\Technotronics
Ltd\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\__init__.py",
line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Technotronics
Ltd\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\pywrap_tensorflow.py",
line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Technotronics
Ltd\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\pywrap_tensorflow.py",
line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Technotronics
Ltd\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py",
line 18, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Technotronics
Ltd\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py",
line 17, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Users\Technotronics
Ltd\AppData\Local\conda\conda\envs\tensorflow\lib\importlib\__init__.py",
line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed: A dynamic link library (DLL)
initialization routine failed.


Failed to load the native TensorFlow runtime.

```

I stumbled upon this [script](https://gist.github.com/mrry/ee5dbcfdd045fa48a27d56664411d41c) that checks the tensorflow package but it tells me that all the required DLLs appear to be present but Failed to import the TensorFlow module. 

```

ERROR: Failed to import the TensorFlow module.

WARNING! This script is no longer maintained!
=============================================
Since TensorFlow 1.4, the self-check has been integrated with TensorFlow itself,
and any missing DLLs will be reported when you execute the `import tensorflow`
statement. The error messages printed below refer to TensorFlow 1.3 and earlier,
and are inaccurate for later versions of TensorFlow.

- Python version is 3.5.

- TensorFlow is installed at: C:\Users\Technotronics
Ltd\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow

- All required DLLs appear to be present. Please open an issue on the
  TensorFlow GitHub page: https://github.com/tensorflow/tensorflow/issues
```
I am totally out of clue now. Please help

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatatodd: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tatatodd** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!

**Comment by FlamesoFF** [comment]
Same error after completing these instructions: https://www.tensorflow.org/install/pip
