### ISSUE TITLE
Input shape Error, bidirectional rnn

### ISSUE THREAD

**Issue by XMaster96** [tensorflow/tensorflow#18326]
System Info:
    - OS: Windows 7
    - Cude: 9, 9.1
    - Tensorflow: 1.7.0
    - GPU Mode

I have some problems with bidirectional rnn inputs. After my anderstanging, a bidirectional  rnn needs a input from the shape "[batch_size, input_size]".  
May input "hidden" has first the shape (?, 512), I then reshape is to (1, 512) and expande the dims to
(1, 1, 512). I treid to pass all three versions to the bidirectional  rnn (and many more).  I have already used the last shap successful, with a normal rnn.

Error:
```
Traceback (most recent call last):
  File "X:/PyProjects/Domm_Lerner/A3C_Arthur_Julianis_Doom.py", line 572, in <module>
    master_network = AC_Network(s_size, a_size, cnn_size, 'global', None)  # Generate global network
  File "X:/PyProjects/Domm_Lerner/A3C_Arthur_Julianis_Doom.py", line 159, in __init__
    lstm_1_outputs, lstm_1_state_fw, lstm_1_state_bw = tf.nn.static_bidirectional_rnn(lstm_cell, lstm_cell, rnn_in,         initial_state_fw=state_1_in_fw, initial_state_bw=state_1_in_bw, sequence_length=step_size)
  File "X:\PyProjects\Domm_Lerner\venv\lib\site-packages\tensorflow\python\ops\rnn.py", line 1478, in static_bidirectional_rnn
    raise TypeError("inputs must be a sequence")
TypeError: inputs must be a sequence
```
 
 

Code:
```
            hidden = tf.reshape(hidden, shape=[1, cnn_size])
            rnn_in = tf.expand_dims(hidden, [0])

            step_size = tf.shape(self.imageIn)[:1]

            lstm_1_outputs, lstm_1_state_fw, lstm_1_state_bw = tf.nn.static_bidirectional_rnn(lstm_cell, lstm_cell, rnn_in,         initial_state_fw=state_1_in_fw, initial_state_bw=state_1_in_bw, sequence_length=step_size)
            lstm_2_outputs, lstm_2_state_fw, lstm_2_state_bw = tf.nn.static_bidirectional_rnn(lstm_cell, lstm_cell, lstm_1_outputs, initial_state_fw=state_2_in_fw, initial_state_bw=state_2_in_bw, sequence_length=step_size)
            lstm_3_outputs, lstm_3_state_fw, lstm_3_state_bw = tf.nn.static_bidirectional_rnn(lstm_cell, lstm_cell, lstm_2_outputs, initial_state_fw=state_3_in_fw, initial_state_bw=state_3_in_bw, sequence_length=step_size)
            lstm_4_outputs, lstm_4_state_fw, lstm_4_state_bw = tf.nn.static_bidirectional_rnn(lstm_cell, lstm_cell, lstm_3_outputs, initial_state_fw=state_4_in_fw, initial_state_bw=state_4_in_bw, sequence_length=step_size)
            lstm_5_outputs, lstm_5_state_fw, lstm_5_state_bw = tf.nn.static_bidirectional_rnn(lstm_cell, lstm_cell, lstm_4_outputs, initial_state_fw=state_5_in_fw, initial_state_bw=state_5_in_bw, sequence_length=step_size)
            lstm_6_outputs, lstm_6_state_fw, lstm_6_state_bw = tf.nn.static_bidirectional_rnn(lstm_cell, lstm_cell, lstm_5_outputs, initial_state_fw=state_6_in_fw, initial_state_bw=state_6_in_bw, sequence_length=step_size)
```

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by XMaster96** [comment]
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 7 6.1.7601 Service Pack 1 Build 7601
- **TensorFlow installed from (source or binary)**: pip install
- **TensorFlow version (use command below)**: 1.7.0
- **Python version**: 3.6
- **Bazel version (if compiling from source)**: n/a
- **GCC/Compiler version (if compiling from source)**: n/a
- **CUDA/cuDNN version**: 9
- **GPU model and memory**: GTX 750 Ti 2GB and GTX 1080 Ti 11GB
- **Exact command to reproduce**:

**Comment by tensorflowbutler** [comment]
Nagging Assignee @rohan100jain: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @rohan100jain: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @rohan100jain: It has been 46 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @rohan100jain: It has been 61 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @rohan100jain: It has been 76 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @rohan100jain: It has been 91 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @rohan100jain: It has been 106 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by rohan100jain** [comment]
I think inputs needs to be a list more than the appropriate shape.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
It has been 35 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
We are closing this issue for now due to lack of activity. Please comment if this is still an issue for you. Thanks!
