### ISSUE TITLE
Got "ValueError: array must not contain infs or NaNs" error in word2vec_basic.py.

### ISSUE THREAD

**Issue by zhongzyd** [tensorflow/tensorflow#1839]
I ran https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/tutorials/word2vec/word2vec_basic.py, and got "ValueError: array must not contain infs or NaNs" error from this line "low_dim_embs = tsne.fit_transform(final_embeddings[:plot_only,:])".
There wasn't any inf or Nan in final_embeddings[:plot_only,:].
I think it is scipy or numpy's issue. 
Is there any suggestion for me ?

### Environment info
Operating System:OS X EI Capitan 10.11.4
under anaconda python 3.5
numpy (1.11.0)
scipy (0.17.0)

Installed version of CUDA and cuDNN: 
Didn't install CUDA.

If installed from sources, provide the commit hash:
de5101da4638ac469041575dadb4921ebb33eb6a

### Steps to reproduce
python3 word2vec_basic.py

### Logs or other output that would be helpful

Traceback (most recent call last):
  File "word2vec_basic.py", line 237, in <module>
    low_dim_embs = tsne.fit_transform(final_embeddings[:plot_only,:])
  File "/Users/zhongzyd/anaconda/envs/TensorFlow-master/lib/python3.5/site-packages/sklearn/manifold/t_sne.py", line 866, in fit_transform
    embedding = self._fit(X)
  File "/Users/zhongzyd/anaconda/envs/TensorFlow-master/lib/python3.5/site-packages/sklearn/manifold/t_sne.py", line 777, in _fit
    skip_num_points=skip_num_points)
  File "/Users/zhongzyd/anaconda/envs/TensorFlow-master/lib/python3.5/site-packages/sklearn/manifold/t_sne.py", line 832, in _tsne
    params, error, it = _gradient_descent(obj_func, params, **opt_args)
  File "/Users/zhongzyd/anaconda/envs/TensorFlow-master/lib/python3.5/site-packages/sklearn/manifold/t_sne.py", line 387, in _gradient_descent
    grad_norm = linalg.norm(grad)
  File "/Users/zhongzyd/anaconda/envs/TensorFlow-master/lib/python3.5/site-packages/scipy/linalg/misc.py", line 129, in norm
    a = np.asarray_chkfinite(a)
  File "/Users/zhongzyd/anaconda/envs/TensorFlow-master/lib/python3.5/site-packages/numpy-1.11.0-py3.5-macosx-10.5-x86_64.egg/numpy/lib/function_base.py", line 1022, in asarray_chkfinite
    "array must not contain infs or NaNs")
ValueError: array must not contain infs or NaNs

**Comment by itsmeolivia** [comment]
TensorFlow does not support 3.5 as of today. Try using 3.4 which is supported.

**Comment by kavasseri** [comment]
I am facing the same issue - did you find a solution yet?

**Comment by zhongzyd** [comment]
No, I haven't found a solution yet. @kavasseri

**Comment by laurendeason** [comment]
I was able to solve this same problem (under anaconda python 2.7) by updating numpy to 1.11.  I see that the OP already has 1.11, but is using python 3.  Maybe try either updating all of numpy/scipy/sklearn to latest or reverting to older versions to find the combination that works with python 3?

**Comment by rasbt** [comment]
just wanted to reference the related thread on the scikit-learn tracker here: https://github.com/scikit-learn/scikit-learn/issues/6665
