### ISSUE TITLE
freeze_graph

### ISSUE THREAD

**Issue by Neilcc** [tensorflow/tensorflow#18417]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: None
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  macOS High Sierra 10.13.3
- **TensorFlow installed from (source or binary)**:  binary, Installing with Virtualenv and pip install 
- **TensorFlow version (use command below)**:1.7.0
- **Python version**:  2.7
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**: 
- **GPU model and memory**: 
- **Exact command to reproduce**:   freeze_graph \
--input_graph=/Users/cc/TF/MNIST/mnist_convnet_model/graph.pbtxt \
--input_checkpoint=/Users/cc/TF/MNIST/mnist_convnet_model/model.ckpt-31817 \
--output_graph=/tmp/frozen_graph_mnist.pb \
--output_node_names='save/restore_all' \
--input_binary=false

### Describe the problem

I'm trying to freeze my mnist graph which name is graph.pbtxt with these command:

```
      freeze_graph \
--input_graph=/Users/cc/TF/MNIST/mnist_convnet_model/graph.pbtxt \
--input_checkpoint=/Users/cc/TF/MNIST/mnist_convnet_model/model.ckpt-31817 \
--output_graph=/tmp/frozen_graph_mnist.pb \
--output_node_names='save/restore_all' \
--input_binary=false
```
but the following error always acours:

```
    Instructions for updating:
Use the retry module or similar alternatives.
Traceback (most recent call last):
  File "/usr/local/bin/freeze_graph", line 11, in <module>
    sys.exit(main())
TypeError: main() takes exactly 1 argument (0 given)

```

### Source code / logs
WARNING:tensorflow:From /usr/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py:198: retry (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Use the retry module or similar alternatives.
Traceback (most recent call last):
  File "/usr/local/bin/freeze_graph", line 11, in <module>
    sys.exit(main())
TypeError: main() takes exactly 1 argument (0 given)

**Comment by Neilcc** [comment]
I solved this by use "python -m tensorflow.python.tools.freeze_graph" instead of "freeze_graph" . But I'm still confused with this. Why does the command does not works on my computer?  Thanks a lot

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatatodd: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatatodd: It has been 45 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatatodd: It has been 59 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatatodd: It has been 74 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatatodd: It has been 89 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatatodd: It has been 105 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatatodd: It has been 119 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatatodd: It has been 134 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatatodd: It has been 149 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatatodd: It has been 164 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by dksb** [comment]
There could be an issue of the wrong version. I am glad it worked out for you. 
 Thanks!
