### ISSUE TITLE
Cannot apply convolution twice

### ISSUE THREAD

**Issue by tsoernes** [tensorflow/tensorflow#18421]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Fedora 27
- **TensorFlow installed from (source or binary)**: Source
- **TensorFlow version (use command below)**: b'v1.3.0-rc1-3011-gd86448938' 1.3.0

- **Python version**: 3.6.4
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**:
```
import tensorflow as tf

sess = tf.Session()
inp1 = tf.ones((1, 2, 2, 5))
inp2 = tf.zeros((1, 2, 2, 5))

conv_layer = tf.layers.Conv2D(
    filters=2,
    kernel_size=2,
    padding='SAME',
    kernel_initializer=tf.glorot_uniform_initializer(),
    name="vconv")
dense_layer = tf.layers.Dense(units=1, use_bias=False, activation=None)

tdout1 = dense_layer.apply(inp1)
tdout2 = dense_layer.apply(inp2)
sess.run(tf.global_variables_initializer())
# This works:
print(sess.run((tdout1, tdout2)))

tcout1 = conv_layer.apply(inp1)
tcout2 = conv_layer.apply(inp2)
sess.run(tf.global_variables_initializer())
# This does not work:
print(sess.run((tcout1, tcout2)))
# ValueError: cannot add op with name vconv/convolution as that name is already used
```
Throws:
```
Traceback (most recent call last):
  File "div/tf_2conv.py", line 16, in <module>
    tcout2 = conv_layer.apply(inp2)
  File "/home/torstein/anaconda3/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 659, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "/home/torstein/anaconda3/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 563, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/home/torstein/anaconda3/lib/python3.6/site-packages/tensorflow/python/layers/convolutional.py", line 171, in call
    outputs = self._convolution_op(inputs, self.kernel)
  File "/home/torstein/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 835, in __call__
    return self.conv_op(inp, filter)
  File "/home/torstein/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 499, in __call__
    return self.call(inp, filter)
  File "/home/torstein/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 187, in __call__
    name=self.name)
  File "/home/torstein/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 631, in conv2d
    data_format=data_format, name=name)
  File "/home/torstein/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/torstein/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2941, in create_op
    self._add_op(ret)
  File "/home/torstein/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2595, in _add_op
    "is already used" % op.name)
ValueError: cannot add op with name vconv/convolution as that name is already used
```

**Comment by asimshankar** [comment]
Looking at the version string ("v1.3.0-rc1-3011-gd86448938") it seems you compiled a non-release version of the code.

This problem shouldn't exist in release branches for version 1.4 onwards.
So if you could build from a release branch (or just use release binaries), that should do the trick.

Closing this out since I don't believe the problem exists in release branches. Please feel free to reopen if I'm mistaken. Thanks.
