### ISSUE TITLE
tensorflow/google/protobuf/BUILD:520:1: no such package 'util/python'

### ISSUE THREAD

**Issue by gaoshan2006** [tensorflow/tensorflow#1844]
GitHub issues are for bugs / installation problems / feature requests.  
For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System:   redhat, tensorflow (0.5.0), bazel (0.1.1)

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

If installed from binary pip package, provide:

1. Which pip package you installed.
2. The output from python -c "import tensorflow; print(tensorflow.__version__)".

If installed from sources, provide the commit hash:

### Steps to reproduce
1.  I am compiling tensorflow (0.5.0)  ,  run this :
bazel build -c opt --spawn_strategy=standalone --genrule_strategy=standalone --jobs=20 //tensorflow/cc:tutorials_example_trainer
2.  The compile error looks like: 
   Object of type 'Label' has no field "workspace_root"
3.

### What have you tried?
1.

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

ERROR: /opt/TensorFlow/tensorflow/tensorflow/core/BUILD:297:1: in _proto_gen rule //tensorflow/core:protos_all_cc_genproto: 
Traceback (most recent call last):
        File "/opt/TensorFlow/tensorflow/tensorflow/core/BUILD", line 297
                _proto_gen(name = 'protos_all_cc_genproto')
        File "/opt/TensorFlow/tensorflow/google/protobuf/protobuf.bzl", line 54, in _proto_gen_impl
                _GenDir(ctx)
        File "/opt/TensorFlow/tensorflow/google/protobuf/protobuf.bzl", line 11, in _GenDir
                ctx.label.workspace_root
Object of type 'Label' has no field "workspace_root".
ERROR: Analysis of target '//tensorflow/cc:tutorials_example_trainer' failed; build aborted.
INFO: Elapsed time: 16.462s

**Comment by gaoshan2006** [comment]
And when I run: 
bazel build -c opt --spawn_strategy=standalone --genrule_strategy=standalone --jobs=20 //tensorflow/tools/pip_package:build_pip_package

The error message is :
ERROR: /opt/TensorFlow/tensorflow/google/protobuf/BUILD:520:1: no such package 'util/python': BUILD file not found on package path and referenced by '//google/protobuf:internal/_api_implementation.so'.
ERROR: Loading failed; build aborted.

**Comment by gaoshan2006** [comment]
And when I run: 
bazel build -c opt --spawn_strategy=standalone --genrule_strategy=standalone --jobs=20 //tensorflow/tools/pip_package:build_pip_package

The error message is :
ERROR: /opt/TensorFlow/tensorflow/google/protobuf/BUILD:520:1: no such package 'util/python': BUILD file not found on package path and referenced by '//google/protobuf:internal/_api_implementation.so'.
ERROR: Loading failed; build aborted.

**Comment by gaoshan2006** [comment]
Oh, I have found the root cause.
  That was caused the "protobuf" was not correctly gotten by git..
  The solution is running this: "git submodule foreach --recursive"
