### ISSUE TITLE
crop_and_resize on gpu in eager mode fails

### ISSUE THREAD

**Issue by cruvadom** [tensorflow/tensorflow#18459]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
 Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:
using pip
- **TensorFlow version (use command below)**:
('v1.7.0-3-g024aecf414', '1.7.0')
- **Python version**: 
2.7
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
Cuda 9, Cudnn 7
- **GPU model and memory**:
GeForce GTX 745, 4GB
- **Exact command to reproduce**:
import tensorflow as tf, numpy as np
tf.enable_eager_execution()
images = np.random.uniform(size=[1, 28, 28, 1]).astype('float32')
with tf.device('gpu:0'):
  tf.image.crop_and_resize(images, boxes=[(0, 0, 0.9, 0.5)], box_ind=[0], crop_size=[20, 20])

### Describe the problem
When using `tf.image.crop_and_resize` in eager mode with the gpu, getting the error that says `box_index` has wrong values, where values are actually fine. 

See the reproduction code above. Works without the gpu, or without eager mode. 
Looks similar to [https://github.com/tensorflow/tensorflow/issues/10618](url)

Error message:
2018-04-12 14:44:57.137104: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-04-12 14:44:57.542554: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-04-12 14:44:57.542970: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1344] Found device 0 with properties: 
name: GeForce GTX 745 major: 5 minor: 0 memoryClockRate(GHz): 1.0325
pciBusID: 0000:01:00.0
totalMemory: 3.95GiB freeMemory: 3.92GiB
2018-04-12 14:44:57.542987: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1423] Adding visible gpu devices: 0
2018-04-12 14:44:57.688951: I tensorflow/core/common_runtime/gpu/gpu_device.cc:911] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-04-12 14:44:57.688973: I tensorflow/core/common_runtime/gpu/gpu_device.cc:917]      0 
2018-04-12 14:44:57.688982: I tensorflow/core/common_runtime/gpu/gpu_device.cc:930] 0:   N 
2018-04-12 14:44:57.689139: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3713 MB memory) -> physical GPU (device: 0, name: GeForce GTX 745, pci bus id: 0000:01:00.0, compute capability: 5.0)
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_image_ops.py", line 368, in crop_and_resize
    extrapolation_value=extrapolation_value, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_image_ops.py", line 396, in crop_and_resize_eager_fallback
    attrs=_attrs, ctx=_ctx, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/eager/execute.py", line 66, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "/usr/local/lib/python2.7/dist-packages/six.py", line 737, in raise_from
    raise value
tensorflow.python.framework.errors_impl.OutOfRangeError: box_index has values outside [0, batch_size) [Op:CropAndResize]

**Comment by tensorflowbutler** [comment]
Nagging Assignee @rohan100jain: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @rohan100jain: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @rohan100jain: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @rohan100jain: It has been 59 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @rohan100jain: It has been 74 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @rohan100jain: It has been 89 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by rohan100jain** [comment]
I tried reproducing the error but couldn't do so.

>>> import tensorflow as tf
>>> tf.__version__
'1.7.0'
>>> import numpy as np
>>> tf.enable_eager_execution()
>>> images = np.random.uniform(size=[1, 28, 28, 1]).astype('float32')
>>> with tf.device('/gpu:0'):
...     tf.image.crop_and_resize(images, boxes=[(0, 0, 0.9, 0.5)], box_ind=[0], crop_size=[20, 20])
<tf.Tensor: id=4, shape=(1, 20, 20, 1), dtype=float32, numpy=
array([[[[0.23771048],
         [0.3173547 ],
         [0.55291235],
         [0.7272838 ],
         [0.16079727],
         [0.5161821 ],
         [0.90516174],
         [0.9034853 ],
         [0.7911546 ],
         [0.7401962 ],
         [0.68701637],
         [0.3191714 ],
         [0.62902766],
         [0.774474  ],
         [0.11670986],
         [0.4090613 ],
         [0.73830366],
         [0.9687719 ],
         [0.69964784],
         [0.5468331 ]],
........

**Comment by tensorflowbutler** [comment]
It has been 15 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
It has been 35 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
We are closing this issue for now due to lack of activity. Please comment if this is still an issue for you. Thanks!
