### ISSUE TITLE
Tensorflow failed when build with MSVC

### ISSUE THREAD

**Issue by shanshan0309** [tensorflow/tensorflow#18456]
System information
•	Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
N/A
•	OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Windows server 2016
•	TensorFlow installed from (source or binary):
Source
•	TensorFlow version (use command below):
Master branch latest revison
•	Python version:
Anaconda 4.1.1 (Python 3.5 64-bit)
•	Bazel version (if compiling from source):
N/A
•	GCC/Compiler version (if compiling from source):
VS2017 15.5.7
•	CUDA/cuDNN version:
NVidia CUDA Toolkit 8.0
NVidia CUDNN 5.1
•	GPU model and memory:
N/A
•	Exact command to reproduce:
N/A

**Describe the problem:**
Tensorflow failed to build due to the error: No module named 'google'. This issue can be reproduced from master revision [90a3db9.](https://github.com/tensorflow/tensorflow/commit/90a3db9ff995634314227f0aacf4984d1eee752a) This should be tensorflow source issue, could you please help take a look at this? Thanks!

**The failures like:**
The whole log file please see attachment.
[log_x64_build.log](https://github.com/tensorflow/tensorflow/files/1902589/log_x64_build.log)

 520>CustomBuild:
         Traceback (most recent call last):
           File "D:/TensorFlow/build_x64/tf_python/tensorflow/tools/api/generator/create_python_api.py", line 26, in <module>
             from tensorflow.python.util import tf_decorator
           File "D:\TensorFlow\build_x64\tf_python\tensorflow\python\__init__.py", line 52, in <module>
             from tensorflow.core.framework.graph_pb2 import *
           File "D:\TensorFlow\build_x64\tf_python\tensorflow\core\framework\graph_pb2.py", line 6, in <module>
             from google.protobuf import descriptor as _descriptor
         ModuleNotFoundError: No module named 'google'
   520>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1. [D:\TensorFlow\build_x64\tf_python_api.vcxproj]

**Repro steps:**

1. git clone https://github.com/tensorflow/tensorflow D:\Tensorflow\src
2. pushd D:\Tensorflow
3. set PreferredToolArchitecture=x64
4. set rel=Release
5. set CUDNN_HOME="C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\cuda"
6. set PY=C:\ProgramData\Anaconda3
7. set CL=/FS /permissive-
8. cmake D:\Tensorflow\src\tensorflow\contrib\cmake -A x64 -DCMAKE_BUILD_TYPE=Release -DPYTHON_EXECUTABLE=C:\ProgramData\Anaconda3\python.exe -DPYTHON_LIBRARIES=C:\ProgramData\Anaconda3\libs\python36.lib -DSWIG_EXECUTABLE=D:\Tensorflow\swigwin-3.0.12\swig.exe -Dtensorflow_BUILD_PYTHON_TESTS=ON -Dtensorflow_BUILD_SHARED_LIB=ON
9. MSBuild /m /p:Configuration=Release;Platform=x64 /p:WindowsTargetPlatformVersion=10.0.16299.0 tensorflow.sln /t:Rebuild

**Comment by shanshan0309** [comment]
Hello, Any update for this?

**Comment by shanshan0309** [comment]
Hi @cy89, any update for this?

**Comment by tensorflowbutler** [comment]
Nagging Assignee @cy89: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tambu-j** [comment]
Since the addition of the create_python_api.py, it does an import during the build of the pip package which means that you need to have protobuf and absl-py installed in the python environment that you are using to do the build. Ideally, the build of protobuf would be added to the pythonpath but a few additional steps need to be added to the protobuf build need to be performed to get the locally build version to work, so as a workaround I just pip installed protobuf at a version compatible with the constraint in setup.py on master. You will also need to pip / conda install absl-py.

**Comment by shanshan0309** [comment]
Thanks all for your help. I installed 'google' and 'abs1' modules and Tnesorflow no longer hit this issue.

**Comment by simpeng** [comment]
thanks for the explanation @tambu-j. I pip install protobuf and absl before doing the windows build. Also, I found, for GPU version build, cuda/bin and cudnn/bin needs to be in PATH, otherwise, will have errors like 

> 
     File "C:/agent/_work/5/b/tf_python/tensorflow/tools/api/generator/create_python_api.py", line 26, in <module>
2018-05-11T02:49:37.9634660Z              from tensorflow.python.util import tf_decorator
2018-05-11T02:49:37.9636047Z            File "C:\agent\_work\5\b\tf_python\tensorflow\python\__init__.py", line 49, in <module>
2018-05-11T02:49:37.9636803Z              from tensorflow.python import pywrap_tensorflow
2018-05-11T02:49:37.9638401Z            File "C:\agent\_work\5\b\tf_python\tensorflow\python\pywrap_tensorflow.py", line 30, in <module>
2018-05-11T02:49:37.9639141Z              self_check.preload_check()
2018-05-11T02:49:37.9640148Z            File "C:\agent\_work\5\b\tf_python\tensorflow\python\platform\self_check.py", line 97, in preload_check
2018-05-11T02:49:37.9641098Z              % (build_info.cudnn_dll_name, build_info.cudnn_version_number))
2018-05-11T02:49:37.9643318Z          ImportError: Could not find 'cudnn64_7.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Note that installing cuDNN is a separate step from installing CUDA, and this DLL is often found in a different directory from the CUDA DLLs. You may install the necessary DLL by downloading cuDNN 7 from this URL: https://developer.nvidia.com/cudnn

**Comment by tensorflowbutler** [comment]
Nagging Assignee @cy89: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @cy89: It has been 30 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @cy89: It has been 45 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @cy89: It has been 60 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by cy89** [comment]
Thanks for the help, @StevenVerne and @tambu-j . I'll close, as it looks like this is resolved.
