### ISSUE TITLE
Error fetching values from variables - queue behavior semantics needs clarification

### ISSUE THREAD

**Issue by knkumar** [tensorflow/tensorflow#18532]
I am generating the following traceback when I try to feed data to the queue.

Have I written custom code : NO
OS Platform and Distribution : Ubuntu 16.04
TensorFlow installed from : pip
TensorFlow version: 1.4.1
Bazel version : N/A
CUDA/cuDNN version : CUDA Version 8.0.61
GPU model and memory : GTX 680 - 4 gb memory
Exact command to reproduce : detaliled in description

The error message is very long so let me try to break it down

The variable is declared as follows 

    a = tf.placeholder(tf.float32, shape=[1,2], name='a')

The variable is fed using a feed_dict as follows

     _,X_hat_val,loss_val = sess.run([train,X_hat,loss],  
                            feed_dict={X : np.array([[ x_ord[0,0],y_ord[0,0]]]), 
                                      a : np.array([[ x_acc[0,0], y_acc[0,0] ]]),
                                      a_prev : np.array([[ out_xacc[0,0], out_yacc[0,0] ]]) })

The variable is printed before feeding to the queue:

    [[ 0.  0.]] # the value of the variable
    (1, 2) # the shape of the variable
    float32 # the data type of the variable

The error is generated at 

    tensorflow.python.framework.errors_impl.InvalidArgumentError: 
    You must feed a value for placeholder tensor 'a' with dtype float and shape [1,2]

However, when I remove an operation to fetch the variable value it works perfectly

print(sess.run(a))

I am not sure if the queue mechanism is seeking out a new value when I run the operation, or if the semantics of the operation is not what I think it is

    ==========      Training Model  ==========
    
    
    /home/kiran/projects/Kalman/data/S10_05_19_2017_train_mouse_subjects.tfrecords
    Running Model
    
    
    
    
    **********Running Graph with a session**********
    
    
    
    
    2018-04-15 09:07:11.227273: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX
    2018-04-15 09:07:11.263222: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:892] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning
     NUMA node zero
    2018-04-15 09:07:11.263499: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties:
    name: GeForce GTX 680 major: 3 minor: 0 memoryClockRate(GHz): 1.0845
    pciBusID: 0000:02:00.0
    totalMemory: 3.93GiB freeMemory: 3.49GiB
    2018-04-15 09:07:11.263522: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 680, pci bus id: 0000:02:00.0, compute capa
    bility: 3.0)
    19999
    [[ 0.  0.]]
    (1, 2)
    float32
    Processing record :  0
    
    
    2018-04-15 09:07:11.871973: W tensorflow/core/kernels/queue_base.cc:295] _0_input_producer: Skipping cancelled enqueue attempt with queue not closed
    Traceback (most recent call last):
      File "/home/kiran/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1323, in _do_call
        return fn(*args)
      File "/home/kiran/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1302, in _run_fn
        status, run_metadata)
      File "/home/kiran/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
        c_api.TF_GetCode(self.status.status))
    tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'a' with dtype float and shape [1,2]
             [[Node: a = Placeholder[dtype=DT_FLOAT, shape=[1,2], _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
             [[Node: a/_69 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_4_a", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "KalmanModel.py", line 378, in <module>
        training(subject)
      File "KalmanModel.py", line 242, in training
        print(sess.run(a))
      File "/home/kiran/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 889, in run
        run_metadata_ptr)
      File "/home/kiran/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1120, in _run
        feed_dict_tensor, options, run_metadata)
      File "/home/kiran/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run
        options, run_metadata)
      File "/home/kiran/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1336, in _do_call
        raise type(e)(node_def, op, message)
    tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'a' with dtype float and shape [1,2]
             [[Node: a = Placeholder[dtype=DT_FLOAT, shape=[1,2], _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
             [[Node: a/_69 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_4_a", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
    
    Caused by op 'a', defined at:
      File "KalmanModel.py", line 378, in <module>
        training(subject)
      File "KalmanModel.py", line 159, in training
        a = tf.placeholder(tf.float32, shape=[1,2], name='a')
      File "/home/kiran/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 1599, in placeholder
        return gen_array_ops._placeholder(dtype=dtype, shape=shape, name=name)
      File "/home/kiran/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3091, in _placeholder
        "Placeholder", dtype=dtype, shape=shape, name=name)
      File "/home/kiran/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
        op_def=op_def)
      File "/home/kiran/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
        op_def=op_def)
      File "/home/kiran/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
        self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access
    
    InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'a' with dtype float and shape [1,2]
             [[Node: a = Placeholder[dtype=DT_FLOAT, shape=[1,2], _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
             [[Node: a/_69 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_4_a", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

**Comment by poxvoculi** [comment]
In your post above I don't see the actual TF program where the queue is defined and used, so it's hard to say what might be going on.

**Comment by knkumar** [comment]
Hi, thanks for your reply. I am not sure what aspects define the queue internally but let me try to highlight the aspects

```
        # create a string input producer to read the tfrecords
        filename_queue = tf.train.string_input_producer([filenames_train], shuffle=False)
       ...decoded vars... = read_and_decode(filename_queue)  

    # create a batch to train the model
    batch = tf.train.batch([...decoded vars... ], 
                           batch_size=1, capacity=2000, num_threads=1) 
```

**Comment by poxvoculi** [comment]
Can you post a simple reproducible example?

**Comment by knkumar** [comment]
Hi, I will post a reproducible example soon. I have been busy dealing with other commitments. Sorry for the delay.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @poxvoculi: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by poxvoculi** [comment]
I'm going to close this for now.  If it continues to be a problem and you can show a small reproducible example that suggests a bug, please reopen.
