### ISSUE TITLE
Fail to save the checkpoint with dataset Iterator saveable

### ISSUE THREAD

**Issue by tobegit3hub** [tensorflow/tensorflow#18583]
### System information
== cat /etc/issue ===============================================
Darwin mbp-2.local 17.5.0 Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64 x86_64
Mac OS X 10.13.4

== are we in docker =============================================
No

== compiler =====================================================
Apple LLVM version 9.1.0 (clang-902.0.39.1)
Target: x86_64-apple-darwin17.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

== uname -a =====================================================
Darwin mbp-2.local 17.5.0 Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64 x86_64

== check pips ===================================================
numpy (1.14.2)
protobuf (3.5.2.post1)
simple-tensorflow-serving (0.2.6, /usr/local/lib/python2.7/site-packages/simple_tensorflow_serving-0.2.6-py2.7.egg)
tensorflow (1.7.0)
tensorflow-hub (0.1.0)
tensorflow-model-analysis (0.6.0)
tensorflow-serving-api (1.0.0)
tensorflow-tensorboard (1.5.0)
tensorflow-transform (0.6.0)
tensorflowjs (0.1.0)
tensorflowonspark (1.0.0)

== check for virtualenv =========================================
False

== tensorflow import ============================================
tf.VERSION = 1.7.0
tf.GIT_VERSION = v1.7.0-3-g024aecf414
tf.COMPILER_VERSION = v1.7.0-3-g024aecf414
Sanity check: array([1], dtype=int32)
/usr/local/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np
.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters

== env ==========================================================
LD_LIBRARY_PATH is unset
DYLD_LIBRARY_PATH is unset

== nvidia-smi ===================================================
a.sh: line 105: nvidia-smi: command not found

== cuda libs  ===================================================

### Describe the problem

We follow the [official document](https://www.tensorflow.org/programmers_guide/datasets#saving_iterator_state) to save the checkpoint with dataset Iterator saveable but it fails. Maybe the implementation of serializing `iterator_ops` is not released in public repo.

### Source code / logs

```
dataset = tf.data.Dataset.from_tensor_slices((image_list_placeholder, label_list_placeholder))
iterator = dataset.make_initializable_iterator()
saveable = tf.contrib.data.make_saveable_from_iterator(iterator)
tf.add_to_collection(tf.GraphKeys.SAVEABLE_OBJECTS, saveable)
saver = tf.train.Saver()

with tf.Session() as sess:
  saver.save(sess, checkpoint_file, global_step=step_value)
```

Here is the error log.

```
2018-04-17 11:02:40.756347: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at iterator_ops.cc:1049 : Unimplemented: AsGraphDefInternal
Traceback (most recent call last):
  File "./mnist_train.py", line 181, in <module>
    main(parse_args())
  File "./mnist_train.py", line 156, in main
    saver.save(sess, checkpoint_file, global_step=step_value)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1676, in save
    {self.saver_def.filename_tensor_name: checkpoint_file})
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 905, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1140, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    run_metadata)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnimplementedError: AsGraphDefInternal
         [[Node: SerializeIterator = SerializeIterator[_device="/job:localhost/replica:0/task:0/device:CPU:0"](Iterator)]]
```

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by jart** [comment]
Assigning to @saxenasaurabh who was the author of these lines:

```cpp
  virtual Status AsGraphDefInternal(DatasetGraphDefBuilder* b,
                                    Node** node) const {
    return errors::Unimplemented("AsGraphDefInternal");
  }
```

**Comment by saxenasaurabh** [comment]
Hi @tobegit3hub 

Thanks for trying this out! The error you are seeing should happen if any of the Datasets in your input pipeline does not support  serialization. However, from you code sample, your input pipeline just contains the TensorSliceDataset which [does support](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/data/tensor_slice_dataset_op.cc#L87) checkpointing. Could you please verify that you have indeed posted your complete input pipeline?

Thanks!

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
It has been 29 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tobegit3hub** [comment]
Sorry for the late response. I still get the same error with `TensorFlow 1.8.0`. I will post the test script so that everyone can re-produce this issue easily.

**Comment by tobegit3hub** [comment]
I get this error when adding `shuffle()` for the `dataset` object. It is easy to re-produce. We need one image file which could be named `1.jpg` and one csv file named `train.csv`. The content of `train.csv` is like this.

```
1.jpg,1
```

Then we can run the following script which throw `UnimplementedError` when saving the checkpoint. Notice that it is normal if we don't use `shuffle()` for the dataset.

```
#!/usr/bin/env python

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import pandas as pd
import tensorflow as tf


def _decode_image_file(filename, label):
  image_string = tf.read_file(filename)
  features = tf.image.decode_jpeg(image_string, channels=1)
  features = tf.image.resize_images(features, [28, 28])
  return features, label


def main():
  train_csv_file = "./train.csv"
  feature_size = 28 * 28 * 1
  label_size = 10
  epoch_number = 10
  batch_size = 1

  train_image_list_placeholder = tf.placeholder(tf.string, [None])
  train_label_list_placeholder = tf.placeholder(tf.int64, [None])
  train_dataset = tf.data.Dataset.from_tensor_slices(
          (train_image_list_placeholder, train_label_list_placeholder))
  train_dataset = train_dataset.repeat(epoch_number).shuffle(1000).map(_decode_image_file).batch(batch_size)
  train_iterator = train_dataset.make_initializable_iterator()
  train_features_op, train_label_op = train_iterator.get_next()
  train_features_op = tf.cast(train_features_op, tf.float32)

  train_dataframe = pd.read_csv(
      train_csv_file,
      delimiter=",",
      header=None,
      dtype={"label": "int64"}).sample(frac=1.0)
  train_image_list = train_dataframe[0].tolist()
  train_label_list = train_dataframe[1].tolist()

  global_step = tf.Variable(
      0, name="global_step", dtype=tf.int64, trainable=False)
  input = tf.reshape(train_features_op, (-1, feature_size))
  weights = tf.get_variable(
          "weight", [feature_size, label_size],
          dtype=tf.float32,
          initializer=tf.zeros_initializer)
  bias = tf.get_variable("bias", [label_size], dtype=tf.float32, initializer=tf.zeros_initializer)
  logits = tf.matmul(input, weights) + bias
  loss = tf.reduce_mean(
      tf.nn.sparse_softmax_cross_entropy_with_logits(
          logits=logits, labels=train_label_op))
  train_op = tf.train.GradientDescentOptimizer(0.01).minimize(
          loss, global_step=global_step)

  saveable = tf.contrib.data.make_saveable_from_iterator(train_iterator)
  tf.add_to_collection(tf.GraphKeys.SAVEABLE_OBJECTS, saveable)
  saver = tf.train.Saver()

  with tf.Session() as sess:

    sess.run(tf.global_variables_initializer())
    sess.run(
        train_iterator.initializer,
        feed_dict={
            train_image_list_placeholder: train_image_list,
            train_label_list_placeholder: train_label_list
        })

    try:
      _, loss_value, global_step_value = sess.run([train_op, loss, global_step])
      saver.save(sess, "checkpoint/checkpoint.ckpt", global_step=global_step_value)
    except tf.errors.OutOfRangeError:
      print("End of data")


if __name__ == "__main__":
  main()
```

**Comment by tobegit3hub** [comment]
I'm not sure if it is by design. If so, it would be better to add the introduction about the conflict of `shuffle` and `checkpoint`.

Saving the status of "shuffled" data is different from the offset and not needed in checkpoint files. But we use `dataset` to read training data and "resuming" training with checkpoints. We can do that by shuffling data in advance and do not use `shuffle` in dataset. Or dataset supports saving the "offset" of data but not strictly guarantee the sequence of shuffled data.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tobegit3hub: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tobegit3hub** [comment]
Great. Thanks @saxenasaurabh 👍
