### ISSUE TITLE
[Deprecation Warning] -  tf.contrib.layers.xavier_initializer

### ISSUE THREAD

**Issue by DEKHTIARJonathan** [tensorflow/tensorflow#18592]
Hello dear friends,

If you run the following code, you will have a deprecation warning in version 1.7.0

```python
import tensorflow as tf
print("TF Version:", tf.__version__)
a = tf.contrib.layers.xavier_initializer()
```

```raw
TF Version: 1.7.0
WARNING:tensorflow:From /usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/datasets/base.py:198: retry (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating: Use the retry module or similar alternatives.
```

For information, this warning did not appear in version **1.6.0**, it appears from **1.7.0**.

Have a good day,

Jonathan

**Comment by cchan** [comment]
Can replicate the problem, with an even simpler command:

    from tensorflow.contrib.layers import xavier_initializer

Seems like the problem is with the `__init__.py` in that folder.

**Comment by cchan** [comment]
Replaced deprecation warning with raising an error, here's the traceback:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/__init__.py", line 35, in <module>
    from tensorflow.contrib import distributions
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/distributions/__init__.py", line 38, in <module>
    from tensorflow.contrib.distributions.python.ops.estimator import *
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/distributions/python/ops/estimator.py", line 21, in <module>
    from tensorflow.contrib.learn.python.learn.estimators.head import _compute_weighted_loss
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/__init__.py", line 95, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/__init__.py", line 28, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/__init__.py", line 29, in <module>
    from tensorflow.contrib.learn.python.learn import datasets
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/datasets/__init__.py", line 31, in <module>
    from tensorflow.contrib.learn.python.learn.datasets import base
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/datasets/base.py", line 198, in <module>
    @retry(initial_delay=1.0, max_delay=16.0, is_retriable=_is_retriable)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 243, in new_func
    raise ValueError("dep")
ValueError: dep
```

**Comment by cchan** [comment]
Seems to be fixed in master lol. https://github.com/tensorflow/tensorflow/commit/fdec18588d7f8b5f6383601f1030ed71f634d1c0

Recommend close.

**Comment by DEKHTIARJonathan** [comment]
@cchan just tested with 1.8.0rc0 you are absolutely right.
Closing this issue
