### ISSUE TITLE
floating point of image classifier is broken in tflite demo

### ISSUE THREAD

**Issue by zhongleiwang** [tensorflow/tensorflow#18594]
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **TensorFlow installed from (source or binary)**:
- **TensorFlow version (use command below)**:
- **Python version**: 
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:

== cat /etc/issue ===============================================
Darwin Zhongleis-MBP 17.5.0 Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64 x86_64
Mac OS X 10.13.4

== are we in docker =============================================
No

== compiler =====================================================
Apple LLVM version 9.1.0 (clang-902.0.39.1)
Target: x86_64-apple-darwin17.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

== uname -a =====================================================
Darwin Zhongleis-MBP 17.5.0 Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64 x86_64

== check pips ===================================================
numpy (1.14.0)

== check for virtualenv =========================================
False

== tensorflow import ============================================
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "tensorflow/python/pywrap_tensorflow.py", line 25, in <module>
    from tensorflow.python.platform import self_check
ImportError: No module named platform

== env ==========================================================
LD_LIBRARY_PATH is unset
DYLD_LIBRARY_PATH is unset

== nvidia-smi ===================================================
./tools/tf_env_collect.sh: line 105: nvidia-smi: command not found

== cuda libs  ===================================================

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.

In current tflite demo, if I enable floating point image classifier, the app doesn't work.

The error message is
04-17 19:56:31.538 29418 29418 E TfLiteCameraDemo: Exception java.lang.NullPointerException: Can not allocate memory for the interpreter

I think it's caused by

$ git show 91c3199
commit 91c31997e6854a3d07acc76381cff7436df1c1dd
Author: A. Unique TensorFlower <gardener@tensorflow.org>
Date:   Fri Apr 13 08:12:42 2018 -0700

    Add support to TFLite for dilated convolution.

    PiperOrigin-RevId: 192770919

### Source code / logs
The error message is
04-17 19:56:31.538 29418 29418 E TfLiteCameraDemo: Exception java.lang.NullPointerException: Can not allocate memory for the interpreter

**Comment by cchan** [comment]
@zhongleiwang How did you determine that it was due to that commit? That just sounds like you're out of memory.

**Comment by zhongleiwang** [comment]
I'm bit puzzled by out of memory problem, however, git bisect seems to indicate the breakage happened from this cl. Maybe the author say more.

**Comment by bwuzhang** [comment]
I have the same issue.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @aselle: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.
