### ISSUE TITLE
Key LayerCollection/ff_fckron/concat_10_False/cov not found in checkpoint

### ISSUE THREAD

**Issue by sandipmgiri** [tensorflow/tensorflow#18645]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: NA
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
     Ubuntu 16.04 (ppc64le)
- **TensorFlow installed from (source or binary)**:
      Installed from source
- **TensorFlow version (use command below)**:
     TF1.6.0
- **Python version**: 
     Python 2.7.5
- **Bazel version (if compiling from source)**:
       0.11.1
- **CUDA/cuDNN version**:
     NA
- **GPU model and memory**:
      NA
- **Exact command to reproduce**:
      bazel test -c opt //tensorflow/contrib/kfac/examples/tests:mlp_test

### Describe the problem
This test passed successfully on x86 , however its failing on ppc64le with below error  - 
```

INFO: From Testing //tensorflow/contrib/kfac/examples/tests:mlp_test:
==================== Test output for //tensorflow/contrib/kfac/examples/tests:mlp_test:
..WARNING:tensorflow:Estimator's model_fn (<function model_fn at 0x3fff9b1c45f0>) includes params argument, but params are not passed to Estimator.
2018-04-18 10:12:24.430611: W tensorflow/core/framework/op_kernel.cc:1202] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: Key LayerCollection/ff_fckron/concat_10_False/cov not found in checkpoint
E..
======================================================================
ERROR: testTrainMnistEstimator (__main__.MlpTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/f1b093cb2d3fbb9bf169263a57926f78/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/kfac/examples/tests/mlp_test.runfiles/org_tensorflow/tensorflow/contrib/kfac/examples/tests/mlp_test.py", line 59, in testTrainMnistEstimator
    mlp.train_mnist_estimator(data_dir=None, num_epochs=1, use_fake_data=True)
  File "/root/.cache/bazel/_bazel_root/f1b093cb2d3fbb9bf169263a57926f78/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/kfac/examples/tests/mlp_test.runfiles/org_tensorflow/tensorflow/contrib/kfac/examples/mlp.py", line 326, in train_mnist_estimator
    estimator.train(input_fn=input_fn)
  File "/root/.cache/bazel/_bazel_root/f1b093cb2d3fbb9bf169263a57926f78/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/kfac/examples/tests/mlp_test.runfiles/org_tensorflow/tensorflow/python/estimator/estimator.py", line 352, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/root/.cache/bazel/_bazel_root/f1b093cb2d3fbb9bf169263a57926f78/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/kfac/examples/tests/mlp_test.runfiles/org_tensorflow/tensorflow/python/estimator/estimator.py", line 888, in _train_model
    log_step_count_steps=self._config.log_step_count_steps) as mon_sess:
  File "/root/.cache/bazel/_bazel_root/f1b093cb2d3fbb9bf169263a57926f78/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/kfac/examples/tests/mlp_test.runfiles/org_tensorflow/tensorflow/python/training/monitored_session.py", line 384, in MonitoredTrainingSession
    stop_grace_period_secs=stop_grace_period_secs)
  File "/root/.cache/bazel/_bazel_root/f1b093cb2d3fbb9bf169263a57926f78/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/kfac/examples/tests/mlp_test.runfiles/org_tensorflow/tensorflow/python/training/monitored_session.py", line 795, in __init__
    stop_grace_period_secs=stop_grace_period_secs)
  File "/root/.cache/bazel/_bazel_root/f1b093cb2d3fbb9bf169263a57926f78/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/kfac/examples/tests/mlp_test.runfiles/org_tensorflow/tensorflow/python/training/monitored_session.py", line 518, in __init__
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "/root/.cache/bazel/_bazel_root/f1b093cb2d3fbb9bf169263a57926f78/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/kfac/examples/tests/mlp_test.runfiles/org_tensorflow/tensorflow/python/training/monitored_session.py", line 981, in __init__
    _WrappedSession.__init__(self, self._create_session())
  File "/root/.cache/bazel/_bazel_root/f1b093cb2d3fbb9bf169263a57926f78/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/kfac/examples/tests/mlp_test.runfiles/org_tensorflow/tensorflow/python/training/monitored_session.py", line 986, in _create_session
    return self._sess_creator.create_session()
  File "/root/.cache/bazel/_bazel_root/f1b093cb2d3fbb9bf169263a57926f78/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/kfac/examples/tests/mlp_test.runfiles/org_tensorflow/tensorflow/python/training/monitored_session.py", line 675, in create_session
    self.tf_sess = self._session_creator.create_session()
  File "/root/.cache/bazel/_bazel_root/f1b093cb2d3fbb9bf169263a57926f78/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/kfac/examples/tests/mlp_test.runfiles/org_tensorflow/tensorflow/python/training/monitored_session.py", line 446, in create_session
    init_fn=self._scaffold.init_fn)
  File "/root/.cache/bazel/_bazel_root/f1b093cb2d3fbb9bf169263a57926f78/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/kfac/examples/tests/mlp_test.runfiles/org_tensorflow/tensorflow/python/training/session_manager.py", line 275, in prepare_session
    config=config)
  File "/root/.cache/bazel/_bazel_root/f1b093cb2d3fbb9bf169263a57926f78/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/kfac/examples/tests/mlp_test.runfiles/org_tensorflow/tensorflow/python/training/session_manager.py", line 207, in _restore_checkpoint
    saver.restore(sess, ckpt.model_checkpoint_path)
  File "/root/.cache/bazel/_bazel_root/f1b093cb2d3fbb9bf169263a57926f78/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/kfac/examples/tests/mlp_test.runfiles/org_tensorflow/tensorflow/python/training/saver.py", line 1755, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/root/.cache/bazel/_bazel_root/f1b093cb2d3fbb9bf169263a57926f78/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/kfac/examples/tests/mlp_test.runfiles/org_tensorflow/tensorflow/python/client/session.py", line 905, in run
    run_metadata_ptr)
  File "/root/.cache/bazel/_bazel_root/f1b093cb2d3fbb9bf169263a57926f78/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/kfac/examples/tests/mlp_test.runfiles/org_tensorflow/tensorflow/python/client/session.py", line 1137, in _run
    feed_dict_tensor, options, run_metadata)
  File "/root/.cache/bazel/_bazel_root/f1b093cb2d3fbb9bf169263a57926f78/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/kfac/examples/tests/mlp_test.runfiles/org_tensorflow/tensorflow/python/client/session.py", line 1355, in _do_run
    options, run_metadata)
  File "/root/.cache/bazel/_bazel_root/f1b093cb2d3fbb9bf169263a57926f78/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/kfac/examples/tests/mlp_test.runfiles/org_tensorflow/tensorflow/python/client/session.py", line 1374, in _do_call
    raise type(e)(node_def, op, message)
NotFoundError: Key LayerCollection/ff_fckron/concat_10_False/cov not found in checkpoint
         [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT64], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

Caused by op u'save/RestoreV2', defined at:
  File "/root/.cache/bazel/_bazel_root/f1b093cb2d3fbb9bf169263a57926f78/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/kfac/examples/tests/mlp_test.runfiles/org_tensorflow/tensorflow/contrib/kfac/examples/tests/mlp_test.py", line 63, in <module>
    tf.test.main()
  File "/root/.cache/bazel/_bazel_root/f1b093cb2d3fbb9bf169263a57926f78/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/kfac/examples/tests/mlp_test.runfiles/org_tensorflow/tensorflow/python/platform/test.py", line 76, in main
    return _googletest.main(argv)
  File "/root/.cache/bazel/_bazel_root/f1b093cb2d3fbb9bf169263a57926f78/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/kfac/examples/tests/mlp_test.runfiles/org_tensorflow/tensorflow/python/platform/googletest.py", line 99, in main
    benchmark.benchmarks_main(true_main=main_wrapper)
  File "/root/.cache/bazel/_bazel_root/f1b093cb2d3fbb9bf169263a57926f78/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/kfac/examples/tests/mlp_test.runfiles/org_tensorflow/tensorflow/python/platform/benchmark.py", line 338, in benchmarks_main
    true_main()
  File "/root/.cache/bazel/_bazel_root/f1b093cb2d3fbb9bf169263a57926f78/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/kfac/examples/tests/mlp_test.runfiles/org_tensorflow/tensorflow/python/platform/googletest.py", line 98, in main_wrapper
    return app.run(main=g_main, argv=args)
  File "/root/.cache/bazel/_bazel_root/f1b093cb2d3fbb9bf169263a57926f78/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/kfac/examples/tests/mlp_test.runfiles/org_tensorflow/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "/root/.cache/bazel/_bazel_root/f1b093cb2d3fbb9bf169263a57926f78/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/kfac/examples/tests/mlp_test.runfiles/org_tensorflow/tensorflow/python/platform/googletest.py", line 69, in g_main
    return unittest_main(argv=argv)
  File "/usr/lib/python2.7/unittest/main.py", line 95, in __init__
    self.runTests()
  File "/usr/lib/python2.7/unittest/main.py", line 232, in runTests
    self.result = testRunner.run(self.test)
  File "/usr/lib/python2.7/unittest/runner.py", line 151, in run
    test(result)
  File "/usr/lib/python2.7/unittest/suite.py", line 70, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python2.7/unittest/suite.py", line 108, in run
    test(result)
  File "/usr/lib/python2.7/unittest/suite.py", line 70, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python2.7/unittest/suite.py", line 108, in run
    test(result)
  File "/usr/lib/python2.7/unittest/case.py", line 393, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/root/.cache/bazel/_bazel_root/f1b093cb2d3fbb9bf169263a57926f78/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/kfac/examples/tests/mlp_test.runfiles/org_tensorflow/tensorflow/contrib/kfac/examples/tests/mlp_test.py", line 59, in testTrainMnistEstimator
    mlp.train_mnist_estimator(data_dir=None, num_epochs=1, use_fake_data=True)
  File "/root/.cache/bazel/_bazel_root/f1b093cb2d3fbb9bf169263a57926f78/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/kfac/examples/tests/mlp_test.runfiles/org_tensorflow/tensorflow/contrib/kfac/examples/mlp.py", line 326, in train_mnist_estimator
    estimator.train(input_fn=input_fn)
  File "/root/.cache/bazel/_bazel_root/f1b093cb2d3fbb9bf169263a57926f78/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/kfac/examples/tests/mlp_test.runfiles/org_tensorflow/tensorflow/python/estimator/estimator.py", line 352, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/root/.cache/bazel/_bazel_root/f1b093cb2d3fbb9bf169263a57926f78/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/kfac/examples/tests/mlp_test.runfiles/org_tensorflow/tensorflow/python/estimator/estimator.py", line 888, in _train_model
    log_step_count_steps=self._config.log_step_count_steps) as mon_sess:
  File "/root/.cache/bazel/_bazel_root/f1b093cb2d3fbb9bf169263a57926f78/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/kfac/examples/tests/mlp_test.runfiles/org_tensorflow/tensorflow/python/training/monitored_session.py", line 384, in MonitoredTrainingSession
    stop_grace_period_secs=stop_grace_period_secs)
  File "/root/.cache/bazel/_bazel_root/f1b093cb2d3fbb9bf169263a57926f78/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/kfac/examples/tests/mlp_test.runfiles/org_tensorflow/tensorflow/python/training/monitored_session.py", line 795, in __init__
    stop_grace_period_secs=stop_grace_period_secs)
  File "/root/.cache/bazel/_bazel_root/f1b093cb2d3fbb9bf169263a57926f78/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/kfac/examples/tests/mlp_test.runfiles/org_tensorflow/tensorflow/python/training/monitored_session.py", line 518, in __init__
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "/root/.cache/bazel/_bazel_root/f1b093cb2d3fbb9bf169263a57926f78/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/kfac/examples/tests/mlp_test.runfiles/org_tensorflow/tensorflow/python/training/monitored_session.py", line 981, in __init__
    _WrappedSession.__init__(self, self._create_session())
  File "/root/.cache/bazel/_bazel_root/f1b093cb2d3fbb9bf169263a57926f78/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/kfac/examples/tests/mlp_test.runfiles/org_tensorflow/tensorflow/python/training/monitored_session.py", line 986, in _create_session
    return self._sess_creator.create_session()
  File "/root/.cache/bazel/_bazel_root/f1b093cb2d3fbb9bf169263a57926f78/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/kfac/examples/tests/mlp_test.runfiles/org_tensorflow/tensorflow/python/training/monitored_session.py", line 675, in create_session
    self.tf_sess = self._session_creator.create_session()
  File "/root/.cache/bazel/_bazel_root/f1b093cb2d3fbb9bf169263a57926f78/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/kfac/examples/tests/mlp_test.runfiles/org_tensorflow/tensorflow/python/training/monitored_session.py", line 437, in create_session
    self._scaffold.finalize()
  File "/root/.cache/bazel/_bazel_root/f1b093cb2d3fbb9bf169263a57926f78/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/kfac/examples/tests/mlp_test.runfiles/org_tensorflow/tensorflow/python/training/monitored_session.py", line 214, in finalize
    self._saver.build()
  File "/root/.cache/bazel/_bazel_root/f1b093cb2d3fbb9bf169263a57926f78/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/kfac/examples/tests/mlp_test.runfiles/org_tensorflow/tensorflow/python/training/saver.py", line 1302, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/root/.cache/bazel/_bazel_root/f1b093cb2d3fbb9bf169263a57926f78/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/kfac/examples/tests/mlp_test.runfiles/org_tensorflow/tensorflow/python/training/saver.py", line 1339, in _build
    build_save=build_save, build_restore=build_restore)
  File "/root/.cache/bazel/_bazel_root/f1b093cb2d3fbb9bf169263a57926f78/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/kfac/examples/tests/mlp_test.runfiles/org_tensorflow/tensorflow/python/training/saver.py", line 790, in _build_internal
    restore_sequentially, reshape)
  File "/root/.cache/bazel/_bazel_root/f1b093cb2d3fbb9bf169263a57926f78/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/kfac/examples/tests/mlp_test.runfiles/org_tensorflow/tensorflow/python/training/saver.py", line 502, in _AddShardedRestoreOps
    name="restore_shard"))
  File "/root/.cache/bazel/_bazel_root/f1b093cb2d3fbb9bf169263a57926f78/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/kfac/examples/tests/mlp_test.runfiles/org_tensorflow/tensorflow/python/training/saver.py", line 449, in _AddRestoreOps
    restore_sequentially)
  File "/root/.cache/bazel/_bazel_root/f1b093cb2d3fbb9bf169263a57926f78/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/kfac/examples/tests/mlp_test.runfiles/org_tensorflow/tensorflow/python/training/saver.py", line 847, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/root/.cache/bazel/_bazel_root/f1b093cb2d3fbb9bf169263a57926f78/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/kfac/examples/tests/mlp_test.runfiles/org_tensorflow/tensorflow/python/ops/gen_io_ops.py", line 1030, in restore_v2
    shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)
  File "/root/.cache/bazel/_bazel_root/f1b093cb2d3fbb9bf169263a57926f78/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/kfac/examples/tests/mlp_test.runfiles/org_tensorflow/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/root/.cache/bazel/_bazel_root/f1b093cb2d3fbb9bf169263a57926f78/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/kfac/examples/tests/mlp_test.runfiles/org_tensorflow/tensorflow/python/framework/ops.py", line 3271, in create_op
    op_def=op_def)
  File "/root/.cache/bazel/_bazel_root/f1b093cb2d3fbb9bf169263a57926f78/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/kfac/examples/tests/mlp_test.runfiles/org_tensorflow/tensorflow/python/framework/ops.py", line 1650, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

NotFoundError (see above for traceback): Key LayerCollection/ff_fckron/concat_10_False/cov not found in checkpoint
         [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT64], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]


----------------------------------------------------------------------
Ran 5 tests in 3.637s

FAILED (errors=1)
================================================================================
Target //tensorflow/contrib/kfac/examples/tests:mlp_test up-to-date:
  bazel-bin/tensorflow/contrib/kfac/examples/tests/mlp_test
INFO: Elapsed time: 5.752s, Critical Path: 5.12s
INFO: Build completed, 1 test FAILED, 2 total actions
//tensorflow/contrib/kfac/examples/tests:mlp_test                        FAILED in 5.1s
  /root/.cache/bazel/_bazel_root/f1b093cb2d3fbb9bf169263a57926f78/execroot/org_tensorflow/bazel-out/ppc-opt/testlogs/tensorflow/contrib/kfac/examples/tests/mlp_test/test.log

Executed 1 out of 1 test: 1 fails locally.

```

I have started looking into the issue. 
Please provide if any suggestions/inputs on what would be the reason of failure. Thanks!

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
It has been 22 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by sandipmgiri** [comment]
This test is passing in TF master, hence closing this issue.
