### ISSUE TITLE
InvalidArgumentError is raised when restoring large (>2GB) variable on macOS

### ISSUE THREAD

**Issue by alyaxey** [tensorflow/tensorflow#18640]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac OS X 10.13.4
- **TensorFlow installed from (source or binary)**: from pip
- **TensorFlow version (use command below)**: 1.7.0, 1.6.0, 1.8.0rc0
- **Python version**: Anaconda, python 3.6
- **Bazel version (if compiling from source)**: no
- **GCC/Compiler version (if compiling from source)**: no
- **CUDA/cuDNN version**: no
- **GPU model and memory**: no
- **Exact command to reproduce**:
```python
import tensorflow as tf

v = tf.get_variable(
    name='a',
    shape=(550 * 1000 * 1000,),
    dtype=tf.float32,
    initializer=tf.zeros_initializer(),
)
saver = tf.train.Saver()
with tf.Session() as s:
    s.run(tf.global_variables_initializer())
    saver.save(s, 'tmp.tf/a')
    saver.restore(s, 'tmp.tf/a')
```

### Describe the problem
When saving and then restoring variable >2GB on macOS tensorflow throws InvalidArgumentError

### Source code / logs
```
2018-04-18 12:25:50.620884: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
'tmp.tf/a'
INFO:tensorflow:Restoring parameters from tmp.tf/a
2018-04-18 12:26:00.866457: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Invalid argument: tmp.tf/a.data-00000-of-00001; Invalid argument
Traceback (most recent call last):
  File "/Users/alyaxey/anaconda/envs/myenv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1327, in _do_call
    return fn(*args)
  File "/Users/alyaxey/anaconda/envs/myenv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1312, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/Users/alyaxey/anaconda/envs/myenv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1420, in _call_tf_sessionrun
    status, run_metadata)
  File "/Users/alyaxey/anaconda/envs/myenv/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: tmp.tf/a.data-00000-of-00001; Invalid argument
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/Users/alyaxey/anaconda/envs/myenv/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1775, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/Users/alyaxey/anaconda/envs/myenv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 905, in run
    run_metadata_ptr)
  File "/Users/alyaxey/anaconda/envs/myenv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1140, in _run
    feed_dict_tensor, options, run_metadata)
  File "/Users/alyaxey/anaconda/envs/myenv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    run_metadata)
  File "/Users/alyaxey/anaconda/envs/myenv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: tmp.tf/a.data-00000-of-00001; Invalid argument
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

Caused by op 'save/RestoreV2', defined at:
  File "<stdin>", line 1, in <module>
  File "/Users/alyaxey/anaconda/envs/myenv/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1311, in __init__
    self.build()
  File "/Users/alyaxey/anaconda/envs/myenv/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1320, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/Users/alyaxey/anaconda/envs/myenv/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1357, in _build
    build_save=build_save, build_restore=build_restore)
  File "/Users/alyaxey/anaconda/envs/myenv/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 809, in _build_internal
    restore_sequentially, reshape)
  File "/Users/alyaxey/anaconda/envs/myenv/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 448, in _AddRestoreOps
    restore_sequentially)
  File "/Users/alyaxey/anaconda/envs/myenv/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 860, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/Users/alyaxey/anaconda/envs/myenv/lib/python3.6/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1458, in restore_v2
    shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)
  File "/Users/alyaxey/anaconda/envs/myenv/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/Users/alyaxey/anaconda/envs/myenv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3290, in create_op
    op_def=op_def)
  File "/Users/alyaxey/anaconda/envs/myenv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1654, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): tmp.tf/a.data-00000-of-00001; Invalid argument
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]
```

**Comment by rothn** [comment]
I may have observed something similar: https://github.com/tensorflow/tensorflow/issues/18769

**Comment by tensorflowbutler** [comment]
Nagging Assignee @cy89: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @cy89: It has been 31 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @cy89: It has been 46 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by danielwatson6** [comment]
Reproduced error. It happens exactly when attempting to restore a tensor of >2GB data size.

**Comment by dmbuchta** [comment]
I am having a very similar issue as well. Following [this tutorial](https://www.tensorflow.org/tutorials/estimators/cnn), but working with larger images.

**Comment by yinnxinn** [comment]
i met same problem , is it a software bug??

**Comment by jhorowitz** [comment]
I'm having the same issue when restoring several GBs of embeddings. Has anyone found any sort of workaround?

**Comment by rothn** [comment]
That works fine, unless you have single embeddings >2GB. Then it's really a serialization nightmare that requires major code changes.

**Comment by cy89** [comment]
@rothn thanks for the link to #18769. It seems useful information that the error happens on both Mac and Windows. 

FWIW, @alyaxey 's demonstration script works fine on my Ubuntu desktop.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @cy89: It has been 20 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @cy89: It has been 35 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @cy89: It has been 50 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @cy89: It has been 65 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @cy89: It has been 80 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @cy89: It has been 95 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @cy89: It has been 110 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by gadagashwini** [comment]
@alyaxey,
Given code works fine with Tensorflow v2.8.0 on MAC os 
```
import tensorflow as tf
tf.compat.v1.disable_eager_execution()
v = tf.compat.v1.get_variable(
    name='a',
    shape=(550 * 1000 * 1000,),
    dtype=tf.float32,
    initializer=tf.zeros_initializer(),
)
saver = tf.compat.v1.train.Saver()
with tf.compat.v1.Session() as s:
    s.run(tf.compat.v1.global_variables_initializer())
    saver.save(s, 'tmp.tf/a')
    saver.restore(s, 'tmp.tf/a')
``` 
**Output**
`INFO:tensorflow:Restoring parameters from tmp.tf/a`

**tmp.tf file has**

> a.data-00000-of-00001
> a.index
> a.meta
> checkpoint
