### ISSUE TITLE
Bug: tf.keras.estimator.model_to_estimator() API giving error when Keras model contains Lambda layer.

### ISSUE THREAD

**Issue by sibyjackgrove** [tensorflow/tensorflow#18660]
------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Custom code
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows
- **TensorFlow installed from (source or binary)**: Binary
- **TensorFlow version (use command below)**: 1.7
- **Python version**:  3.6
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**:
`estimator_vae = tf.keras.estimator.model_to_estimator(keras_model=vae)`

### Describe the problem
 `tf.keras.estimator.model_to_estimator()` API is failing when Keras model contains `Lambda ` layer.
The error I am getting is `SystemError: unknown opcode`
The problem seems to be only there when I am using custom functions inside the Keras mode.

### Source code / logs
I implemented a VAE in Keras and was trying to convert it into an TF estimator model. The model works and trains using Keras. The Keras model has functions for gaussian sampling and VAE training loss. The code and  error trace back is given below.

```
#Encoder network, mapping inputs to our latent distribution parameters:
x = Input(batch_shape=(batch_size, original_dim),name='encoder_input')
encoded = Dense(intermediate_dim, activation='relu',name='encoder_dense_1')(x)
z_mean = Dense(latent_dim,name='z_mean')(encoded)
z_log_var = Dense(latent_dim,name='z_log_var')(encoded)

# Sampling from Gaussian
def sampling(args):
    
    z_mean, z_log_var = args

    epsilon = tf.random_normal(shape=(batch_size, latent_dim),
                               mean=0., stddev=epsilon_std) 
    
    return z_mean + tf.exp(z_log_var/2) * epsilon
z = Lambda(sampling,name='z')([z_mean, z_log_var]) 

#Compute VAE loss
def vae_loss(x, x_decoded):
    x_mse_loss = original_dim*tf.keras.losses.mean_squared_error(tf.layers.flatten(x), tf.layers.flatten(x_decoded))
    beta = 4.0
    kl_loss = - 0.5*beta* tf.reduce_sum(1 + z_log_var - tf.square(z_mean) - tf.exp(z_log_var), axis=-1)
    return tf.reduce_mean(x_mse_loss + kl_loss)

# Map these sampled latent points back to reconstructed inputs:
#Decoder network layers
decoder_dense_1 = Dense(intermediate_dim, activation='relu',name='decoder_dense_1')
decoder_output = Dense(48, activation='relu',name='decoder_output')
decoded = decoder_dense_1(z)
x_decoded = decoder_output(decoded)

# end-to-end autoencoder
vae = Model(x, x_decoded)
vae.compile(optimizer='adam',loss=vae_loss) 
vae.summary()
#Converting to tf estimator
estimator_vae = tf.keras.estimator.model_to_estimator(keras_model=vae)
```
Output:

```
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
==================================================================================================
encoder_input (InputLayer)      (50, 48)             0                                            
__________________________________________________________________________________________________
encoder_dense_1 (Dense)         (50, 24)             1176        encoder_input[0][0]              
__________________________________________________________________________________________________
z_mean (Dense)                  (50, 10)             250         encoder_dense_1[0][0]            
__________________________________________________________________________________________________
z_log_var (Dense)               (50, 10)             250         encoder_dense_1[0][0]            
__________________________________________________________________________________________________
z (Lambda)                      (50, 10)             0           z_mean[0][0]                     
                                                                 z_log_var[0][0]                  
__________________________________________________________________________________________________
decoder_dense_1 (Dense)         (50, 24)             264         z[0][0]                          
__________________________________________________________________________________________________
decoder_output (Dense)          (50, 48)             1200        decoder_dense_1[0][0]            
==================================================================================================
Total params: 3,140
Trainable params: 3,140
Non-trainable params: 0
__________________________________________________________________________________________________
INFO:tensorflow:Using the Keras model provided.
INFO:tensorflow:Using default config.
WARNING:tensorflow:Using temporary folder as model directory: C:\Users\SPLATH~1\AppData\Local\Temp\tmps7nagdhz
INFO:tensorflow:Using config: {'_model_dir': 'C:\\Users\\SPLATH~1\\AppData\\Local\\Temp\\tmps7nagdhz', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x00000238136D9DA0>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
---------------------------------------------------------------------------
SystemError                               Traceback (most recent call last)
<ipython-input-10-77cc01c33881> in <module>()
     13 vae.summary()
     14 #Converting to tf estimator
---> 15 estimator_vae = tf.keras.estimator.model_to_estimator(keras_model=vae)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\keras\_impl\keras\estimator.py in model_to_estimator(keras_model, keras_model_path, custom_objects, model_dir, config)
    481                            estimator,
    482                            custom_objects,
--> 483                            keras_weights)
    484   elif keras_model.built:
    485     logging.warning('You are creating an Estimator from a Keras model '

~\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\keras\_impl\keras\estimator.py in _save_first_checkpoint(keras_model, estimator, custom_objects, keras_weights)
    396       training_util.create_global_step()
    397       model = _clone_and_build_model(model_fn_lib.ModeKeys.TRAIN, keras_model,
--> 398                                      custom_objects)
    399       if isinstance(model, models.Sequential):
    400         model = model.model

~\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\keras\_impl\keras\estimator.py in _clone_and_build_model(mode, keras_model, custom_objects, features, labels)
    270         model = models.clone_model(keras_model, input_tensors=input_tensors)
    271     else:
--> 272       model = models.clone_model(keras_model, input_tensors=input_tensors)
    273   else:
    274     model = keras_model

~\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\keras\_impl\keras\models.py in clone_model(model, input_tensors)
    261     return _clone_sequential_model(model, input_tensors=input_tensors)
    262   else:
--> 263     return _clone_functional_model(model, input_tensors=input_tensors)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\keras\_impl\keras\models.py in _clone_functional_model(model, input_tensors)
    166               kwargs['mask'] = computed_masks
    167           output_tensors = generic_utils.to_list(layer(computed_tensors,
--> 168                                                        **kwargs))
    169           output_masks = generic_utils.to_list(
    170               layer.compute_mask(computed_tensors, computed_masks))

~\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\keras\_impl\keras\engine\base_layer.py in __call__(self, inputs, **kwargs)
    237     """
    238     # Actually call the layer (optionally building it).
--> 239     output = super(Layer, self).__call__(inputs, **kwargs)
    240     if context.executing_eagerly():
    241       return output

~\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\layers\base.py in __call__(self, inputs, *args, **kwargs)
    712 
    713         if not in_deferred_mode:
--> 714           outputs = self.call(inputs, *args, **kwargs)
    715           if outputs is None:
    716             raise ValueError('A layer\'s `call` method should return a Tensor '

~\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\keras\_impl\keras\layers\core.py in call(self, inputs, mask)
    640     if has_arg(self.function, 'mask'):
    641       arguments['mask'] = mask
--> 642     return self.function(inputs, **arguments)
    643 
    644   def compute_mask(self, inputs, mask=None):

~\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\keras\_impl\keras\layers\core.py in sampling(args)
     16 def sampling(args):
     17     #import tensorflow as tf
---> 18     z_mean, z_log_var = args
     19 
     20     epsilon = tf.random_normal(shape=(batch_size, latent_dim),

SystemError: unknown opcode
```

**Comment by angersson** [comment]
@fchollet Can you take a look at this?

**Comment by tensorflowbutler** [comment]
Nagging Assignees @fchollet, @angersson: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by facaiy** [comment]
I run the test on Mac (tf 1.8).  A similar exception is raised, which seems related with clone behavior of Lambda: the function copied jumps out the original code scope.

```python
import tensorflow as tf
from tensorflow.python.keras import Input, Model
from tensorflow.python.keras.layers import Dense, Lambda

x = Input(shape=(32,))
y = Dense(10)(x)

def func(x):
    return tf.exp(x)

y = Lambda(func)(y)

vae = Model(x, y)
vae.compile(optimizer='adam', loss='categorical_crossentropy')
vae.summary()

estimator_vae = tf.keras.estimator.model_to_estimator(keras_model=vae)
```

```python
~/Downloads ❯❯❯ python test.py
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
input_1 (InputLayer)         (None, 32)                0
_________________________________________________________________
dense_1 (Dense)              (None, 10)                330
_________________________________________________________________
lambda_1 (Lambda)            (None, 10)                0
=================================================================
Total params: 330
Trainable params: 330
Non-trainable params: 0
_________________________________________________________________
WARNING:tensorflow:Using temporary folder as model directory: /var/folders/6n/7463w47j649757l3cyct9qp00000gn/T/tmptdyvm5v3
2018-05-06 06:56:08.030004: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Traceback (most recent call last):
  File "test.py", line 19, in <module>
    estimator_vae = tf.keras.estimator.model_to_estimator(keras_model=vae)
  File "/Users/facai/Library/anaconda3/lib/python3.5/site-packages/tensorflow/python/keras/_impl/keras/estimator.py", line 478, in model_to_estimator
    keras_weights)
  File "/Users/facai/Library/anaconda3/lib/python3.5/site-packages/tensorflow/python/keras/_impl/keras/estimator.py", line 395, in _save_first_checkpoint
    custom_objects)
  File "/Users/facai/Library/anaconda3/lib/python3.5/site-packages/tensorflow/python/keras/_impl/keras/estimator.py", line 272, in _clone_and_build_model
    model = models.clone_model(keras_model, input_tensors=input_tensors)
  File "/Users/facai/Library/anaconda3/lib/python3.5/site-packages/tensorflow/python/keras/_impl/keras/models.py", line 263, in clone_model
    return _clone_functional_model(model, input_tensors=input_tensors)
  File "/Users/facai/Library/anaconda3/lib/python3.5/site-packages/tensorflow/python/keras/_impl/keras/models.py", line 156, in _clone_functional_model
    **kwargs))
  File "/Users/facai/Library/anaconda3/lib/python3.5/site-packages/tensorflow/python/keras/_impl/keras/engine/base_layer.py", line 314, in __call__
    output = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "/Users/facai/Library/anaconda3/lib/python3.5/site-packages/tensorflow/python/layers/base.py", line 716, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/Users/facai/Library/anaconda3/lib/python3.5/site-packages/tensorflow/python/keras/_impl/keras/layers/core.py", line 642, in call
    return self.function(inputs, **arguments)
  File "test.py", line 11, in func
    return tf.exp(x)
NameError: name 'tf' is not defined
```

**Comment by fchollet** [comment]
I suggest the following:

- Put the content of your `Lambda` inside a custom layer (say `MyLayer`)
- Place the `MyLayer` definition in your file
- Call `model_to_estimator` within the following scope:

```python
with tf.keras.utils.CustomObjectScope({'MyLayer': MyLayer}):
   estimator = model_to_estimator(model)
```

**Comment by angersson** [comment]
@sibyjackgrove Has @fchollet's advice resolved your issue?

**Comment by sibyjackgrove** [comment]
@angersson 
I tried making the custom layer like below:
```
class MyLayer(Layer):
    
    def compute_output_shape(self, input_shape):
        shape = list(input_shape)
        assert len(shape) == 2  # only valid for 2D tensors
        shape[-1] *= 2
        return tuple(shape)

    def call(self, x):
        z_mean, z_log_var = x

        epsilon = tf.random_normal(shape=(batch_size, latent_dim),mean=0., stddev=epsilon_std) 
    
        return z_mean + tf.exp(z_log_var/2) * epsilon
```
Then used it within the model like below: 
`z = MyLayer()([z_mean, z_log_var]) `
However it is throwing off an error.
Could you tell me if I made the custom layer correctly? I was following example of antirectifier custom layer in the Keras repository.

**Comment by bhack** [comment]
@fchollet Hasn't the `model_to_estimator` the `custom_objects` parameter already? 
Generally It is better to officially document if lambda layer are not supported cause I think that it will be one of the first things that user will try after using standard layers.

**Comment by tensorflowbutler** [comment]
Nagging Assignees @fchollet, @angersson: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by sibyjackgrove** [comment]
I am still having the same problem with TF 1.9-rc1 for my code. However, in case of @facaiy 's code, it works if you put an import statement in the lambda function declaration.

```
def func(x):
    import tensorflow as tf
    return tf.exp(x)
```
Can anyone tell me why I am getting  

> SystemError: unknown opcode

for my lamda function below while the above code doesn't get it.

```
def sampling(args):
    
    z_mean, z_log_var = args

    epsilon = tf.random_normal(shape=(batch_size, latent_dim),
                               mean=0., stddev=epsilon_std) 
    
    return z_mean + tf.exp(z_log_var/2) * epsilon
```

**Comment by tensorflowbutler** [comment]
Nagging Assignees @fchollet, @angersson: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignees @fchollet, @angersson: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @fchollet: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @fchollet: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @fchollet: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @fchollet: It has been 59 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @fchollet: It has been 89 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @fchollet: It has been 104 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by sibyjackgrove** [comment]
Thanks, @azmikamis  I will try this out.

**Comment by vladdxc** [comment]
@azmikamis I tried what you mentioned it still throws the same error, namely:
`z_mean, z_log_var = args
SystemError: unknown opcode`

**Comment by allen-ash** [comment]
@sibyjackgrove Have you solved this problem? I am currently get into this problem too.

**Comment by nikitamaia** [comment]
Closing this issue now since the following code shared earlier in this thread now works in TF 2.4. [Gist here](https://colab.research.google.com/gist/nikitamaia/71dc9908be12c88b58fa4dfc4394897f/keras_m2e_lambda.ipynb)

**Comment by AI-Ahmed** [comment]
It is weird that you closed the issue @nikitamaia while your gist is giving an error!!!
![image](https://user-images.githubusercontent.com/72295771/193039830-a7a8dc90-e98d-4f03-856f-de753e1e69e2.png)
