### ISSUE TITLE
Tensorflow Lite demo app crashes when using inception-v3/Mobilenet_v1 (float) instead of quantised mobilenet

### ISSUE THREAD

**Issue by albin84b** [tensorflow/tensorflow#18697]
------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 14.04
- **TensorFlow installed from (source or binary)**: Git cloned source
- **TensorFlow version (use command below)**: NA
- **Python version**: python 2.7
- **Bazel version (if compiling from source)**: bazel release 0.11.1
- **GCC/Compiler version (if compiling from source)**:  4.8.4
- **CUDA/cuDNN version**: NA
- **GPU model and memory**: x86 8GB RAM
- **Exact command to reproduce**:  bazel build --cxxopt=--std=c++11 //tensorflow/contrib/lite/java/demo/app/src/main:TfLiteCameraDemo --config android  --cpu=x86_64 --fat_apk_cpu=x86_64

### Describe the problem

Tensorflow Lite demo app crashes while launching the app, if I use Float inception model (inceptionv3_slim_2016.tflite or mobilenet_v1_1.0_224.tflite) instead of quantised mobilenet. I added the code changes from https://github.com/tensorflow/tensorflow/issues/14719 on top of the github source for moving quantised mobilenet to float inception/Mobilenet.

### Source code / logs
```
--------- beginning of crash --------- 
04-19 08:57:09.480  7131  7160 E AndroidRuntime: FATAL EXCEPTION: VideoBackground
04-19 08:57:09.480  7131  7160 E AndroidRuntime: Process: com.example.android.tflitecamerademo, PID: 7131
04-19 08:57:09.480  7131  7160 E AndroidRuntime: java.lang.IllegalArgumentException: Failed to get input dimensions. 0-th input should have 602112 bytes, but found 4291248 bytes.
04-19 08:57:09.480  7131  7160 E AndroidRuntime:        at org.tensorflow.lite.NativeInterpreterWrapper.getInputDims(Native Method)
04-19 08:57:09.480  7131  7160 E AndroidRuntime:        at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:98)
04-19 08:57:09.480  7131  7160 E AndroidRuntime:        at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:143)
04-19 08:57:09.480  7131  7160 E AndroidRuntime:        at org.tensorflow.lite.Interpreter.run(Interpreter.java:121)
04-19 08:57:09.480  7131  7160 E AndroidRuntime:        at com.example.android.tflitecamerademo.ImageClassifierFloatInception.runInference(ImageClassifierFloatInception.java:123)
04-19 08:57:09.480  7131  7160 E AndroidRuntime:        at com.example.android.tflitecamerademo.ImageClassifier.classifyFrame(ImageClassifier.java:121)
04-19 08:57:09.480  7131  7160 E AndroidRuntime:        at com.example.android.tflitecamerademo.MainActivity.classifyFrame(MainActivity.java:496)
04-19 08:57:09.480  7131  7160 E AndroidRuntime:        at com.example.android.tflitecamerademo.MainActivity.access$600(MainActivity.java:54)
04-19 08:57:09.480  7131  7160 E AndroidRuntime:        at com.example.android.tflitecamerademo.MainActivity$2.run(MainActivity.java:459)
04-19 08:57:09.480  7131  7160 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:790)
04-19 08:57:09.480  7131  7160 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
04-19 08:57:09.480  7131  7160 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:164)
04-19 08:57:09.480  7131  7160 E AndroidRuntime:        at android.os.HandlerThread.run(HandlerThread.java:65)
04-19 08:57:06.663  7131  7131 I chatty  : uid=10073(com.example.android.tflitecamerademo) identical 3 lines
04-19 08:57:06.680  7131  7131 D ViewRootImpl[MainActivity]: updatePointerIcon called with position out of bounds
04-19 08:57:09.482  5448  5591 W ActivityManager:   Force finishing activity com.example.android.tflitecamerademo/.MainActivity
```
-----------------------------------------------------------

**Comment by aselle** [comment]
@albin84b, the comments by  @pkurogerjs  on #14719 are correct. Your image bytebuffer is the worng size a float buffer should to feed in a 224x224 image should be `224*224*3*4 = 602112` bytes. Your buffer is a factor of 4 too big. Can you provide your full code changes as  PR so I can take a look at exactly what you are doing?

**Comment by mythilivadali** [comment]
I have also noticed this crash when using Inception_v3 model after pulling the latest demo app changes.

**Comment by albin84b** [comment]
@aselle, Its works for me after changing the buffer size as per the code changes given in #14719. thanks a lot for the help.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @aselle: It has been 30 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by albin84b** [comment]
Closing this issue as it works
