### ISSUE TITLE
Problem:  Cannot merge devices with incompatible types: '/job:localhost/replica:0/task:0/device:CPU:0' and '/job:localhost/replica:0/task:0/device:GPU:0'

### ISSUE THREAD

**Issue by chauhochow** [tensorflow/tensorflow#18720]
I get a problem. Here is the description of the error:

Caused by op u'block_stack_0/block_0/short_cut/weight/Initializer/random_uniform/RandomUniform', defined at:
  File "train.py", line 133, in <module>
    train()
  File "train.py", line 84, in train
    model.get_loss(image, gt, args.block_num_channel_list)
  File "model.py", line 145, in get_loss
    self.logits = self.inference(images, block_num_channel_list=block_num_channel_list)
  File "model.py", line 126, in inference
    output = self.stack(inputs=output, output_channel=bottel_neck_channel * 4, stack_num=stack_num, strides=stride, scope='block_stack_%d' % stack_block_index, bottel_neck_channel=bottel_neck_channel)
  File "model.py", line 118, in stack
    output = self.block(inputs, bottel_neck_channel=bottel_neck_channel, output_channel=output_channel, strides=strides, is_projection=True, scope='block_0')
  File "model.py", line 106, in block
    short_cut = self.conv(output, kernel_size=1, strides=strides, output_channel=output_channel, scope='short_cut', use_bias=False, is_activate=False)
  File "model.py", line 48, in conv
    name='weight')
  File "model.py", line 36, in get_variable
    trainable=trainable)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 1065, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 962, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 367, in get_variable
    validate_shape=validate_shape, use_resource=use_resource)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 352, in _true_getter
    use_resource=use_resource)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 725, in _get_single_variable
    validate_shape=validate_shape)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/variables.py", line 199, in __init__
    expected_shape=expected_shape)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/variables.py", line 277, in _init_from_args
    initial_value(), name="initial_value", dtype=dtype)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 701, in <lambda>
    shape.as_list(), dtype=dtype, partition_info=partition_info)
  File "/usr/lib/python2.7/site-packages/tensorflow/contrib/layers/python/layers/initializers.py", line 144, in _initializer
    dtype, seed=seed)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/random_ops.py", line 240, in random_uniform
    shape, dtype, seed=seed1, seed2=seed2)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/gen_random_ops.py", line 247, in _random_uniform
    seed=seed, seed2=seed2, name=name)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Cannot colocate nodes 'block_stack_0/block_0/short_cut/weight/Initializer/random_uniform/RandomUniform' and 'block_stack_0/block_0/short_cut/weight: Cannot merge devices with incompatible types: '/job:localhost/replica:0/task:0/device:CPU:0' and '/job:localhost/replica:0/task:0/device:GPU:0'
	 [[Node: block_stack_0/block_0/short_cut/weight/Initializer/random_uniform/RandomUniform = RandomUniform[T=DT_INT32, _class=["loc:@block_stack_0/block_0/short_cut/weight"], dtype=DT_FLOAT, seed=0, seed2=0](block_stack_0/block_0/short_cut/weight/Initializer/random_uniform/shape)]]

('add regulariztion, regularization decay:', 0.003)
set learning rate
Traceback (most recent call last):
  File "train.py", line 133, in <module>
    train()
  File "train.py", line 91, in train
    sess.run(tf.global_variables_initializer())
  File "/usr/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    options, run_metadata)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Node 'block_stack_0/block_0/short_cut/cond/Switch_1': Unknown input node 'block_stack_0/block_0/short_cut/weight/Initializer/random_uniform'

it seems that the error happen on the op "tf.global_variables_initializer()"
some code may be related to this error is : 

os.environ['CUDA_VISIBLE_DEVICES'] = '0'

with tf.device('/cpu:0'):
            var = tf.get_variable(shape=shape,
                                  name=name,
                                  dtype=dtype,
                                  initializer=initializer,
                                  regularizer=regularizer,
                                  trainable=trainable)
            moving_average_opt = self.moving_averager.apply([var])
            tf.add_to_collection(tf.GraphKeys.UPDATE_OPS, moving_average_opt)
            moving_average_variable = self.moving_averager.average(var)
            tf.summary.histogram(var.name, var)
            tf.summary.histogram('moving_'+ var.name, moving_average_variable)

how can i solve this problem? Thanks.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
It has been 20 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by asimshankar** [comment]
From the error message, it seems there are some unsatisfiable constraints on the placement of the operations being provided.

Is it possible to provide enough information to reproduce the problem so that we can determine if there is a bug in some library code, or an error in some usage of it?

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
It has been 29 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
It has been 44 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
We are closing this issue for now due to lack of activity. Please comment if this is still an issue for you. Thanks!

**Comment by rhr407** [comment]
I am facing the same error. 

TF = 2.3.0.
Number of GPUs = 3
