### ISSUE TITLE
tf.profile.ProfileOptionBuilder.trainable_variables_parameter errors with pooling layer

### ISSUE THREAD

**Issue by irmowan** [tensorflow/tensorflow#18755]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: GPU 1.4.1
- **Python version**: 3.5
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**: CUDA8, cuDNN 6.0.20
- **GPU model and memory**: Tesla P4
- **Exact command to reproduce**: 

### Describe the problem
tf.profile.ProfileOptionBuilder.trainable_variables_parameter() errors with max_pooling layer.

### Source code / logs
```python
    opts = (tf.profiler.ProfileOptionBuilder(
         tf.profiler.ProfileOptionBuilder.trainable_variables_parameter())
         .with_node_names(hide_name_regexes=['.*pool.*'])
         .build())
     params_stats = tf.profiler.profile(
         graph,
         options=opts
     )   
     logger.info('Total params: {}'.format(params_stats.total_parameters))
 
```
The code above works ok for [Resnet](https://github.com/tensorflow/models/blob/r1.4.0/official/resnet/resnet_model.py), but when I want to profile my vgg_net or shuffle_net, it crashes with:

```
Traceback (most recent call last):
  File "model_analysis.py", line 50, in <module>
    profile_model_params(graph)
  File "model_analysis.py", line 25, in profile_model_params
    options=opts
  File "/home/ymwan/python3/lib/python3.5/site-packages/tensorflow/python/profiler/model_analyzer.py", line 312, in profile
    graph, op_log, run_meta, add_trace=cmd == 'code')
  File "/home/ymwan/python3/lib/python3.5/site-packages/tensorflow/python/profiler/tfprof_logger.py", line 146, in _merge_default_with_oplog
    graph, run_meta, add_trace=add_trace, add_trainable_var=add_trainable_var)
  File "/home/ymwan/python3/lib/python3.5/site-packages/tensorflow/python/profiler/tfprof_logger.py", line 88, in _get_logged_ops
    graph, op.node_def, REGISTERED_FLOP_STATS)
  File "/home/ymwan/python3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2362, in get_stats_for_node_def
    result = stats_func(graph, node)
  File "/home/ymwan/python3/lib/python3.5/site-packages/tensorflow/python/profiler/internal/flops_registry.py", line 376, in _max_pool_grad_flops
    max_pool_ops = kernel_area * orig_out_shape.num_elements()
TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'
```
This problem seems related to 'max_pool2d' (and error says) as ResNet doesn't have this problem.
From my code you can see `hide_name_regexes`, try to skip this problem but failed.
Here, someone else also report this issue: https://github.com/vahidk/TensorflowFramework/issues/2

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatianashp: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatianashp: It has been 19 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatianashp: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatianashp: It has been 64 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatianashp: It has been 79 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatianashp: It has been 95 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatianashp: It has been 109 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatianashp: It has been 124 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatianashp: It has been 139 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatianashp: It has been 154 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tatianashp** [comment]
@irmowan So sorry this fell through the cracks. I am closing the issue since it has been a long time. 
If this is still a problem for you please reopen and post the results from running with the latest version of TensorFlow.
