### ISSUE TITLE
InvalidArgumentError for save/restore of variables (same version, same OS, same directory)

### ISSUE THREAD

**Issue by rothn** [tensorflow/tensorflow#18769]
I get an InvalidArgumentError with no further information when I try to save and then restore parts of my model later to continue training it (due to needing my laptop for class).

Initialization:
saver = tf.train.Saver({"embeddings": embeddings, "weights": nce_weights, "biases": nce_biases})

Save:
saver.save(sess, model_checkpoint_path)

Load:
saver.restore(sess, model_checkpoint_path)

```
2018-04-21 22:45:00.143245: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Invalid argument: /Users/nroth/Documents/****/trained_model/****embeddings.ckpt.data-00000-of-00001; Invalid argument
Traceback (most recent call last):
  File "/Users/nroth/tf_python/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1327, in _do_call
    return fn(*args)
  File "/Users/nroth/tf_python/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1312, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/Users/nroth/tf_python/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1420, in _call_tf_sessionrun
    status, run_metadata)
  File "/Users/nroth/tf_python/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: /Users/nroth/Documents/****/trained_model/****embeddings.ckpt.data-00000-of-00001; Invalid argument
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

... <contains sensitive info> ...

InvalidArgumentError (see above for traceback): /Users/nroth/Documents/****/trained_model/****embeddings.ckpt.data-00000-of-00001; Invalid argument
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]
```

**Clarification requested by tensorflowbutler**
_Have I written custom code:_
Yes, I modified this code (https://github.com/PacktPublishing/TensorFlow-Machine-Learning-Cookbook/blob/master/Chapter%2007/doc2vec.py) to work with TensorFlow 1.7 and to use the same embeddings variable for documents as for words with average instead of concatenation. I also updated the saved variables to include nce_weights and nce_biases so that training may be resumed.
_OS Platform and Distribution_
MacOS 10.13.4 (17E199)
_TensorFlow installed from_
pip on VirtualEnv, according to instructions (https://www.tensorflow.org/install/install_mac)
_TensorFlow version_
1.7
_Bazel version_
NA
_CUDA/cuDNN version_
NA
_GPU model and memory_
NA
_Exact command to reproduce_
saver = tf.train.Saver({"embeddings": embeddings, "weights": nce_weights, "biases": nce_biases})
saver.restore(sess, "../trained_model/saved_stuff")

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by rothn** [comment]
Ticket updated with requested information. Will use template in the future!

**Comment by rothn** [comment]
Possibly related to: https://github.com/tensorflow/tensorflow/issues/18640

**Comment by rothn** [comment]
Update: I tried this on Windows as well, and I got rid of the stuff for loading the model graph and used the Saver to explicitly restore my variables. On Windows, it fails for the same reason (because I am loading an embedding larger than 2GB) but with a better error message:

`OutOfRangeError (see above for traceback): Read fewer bytes than requested
         [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]`

**Comment by rothn** [comment]
@rohan100jain bump :)

**Comment by tensorflowbutler** [comment]
Nagging Assignee @rohan100jain: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by madaoLic** [comment]
I am using tensorflow-gpu 1.7.0, and meet exactly the same problem when restoring model in distributed tensorflow environment.

when the model file is larger than 3GB, the error below occurs:
InvalidArgumentError (see above for traceback): hdfs://xxxx/model.ckpt-5154361.data-00001-of-00008; Invalid argument
         [[Node: save_1/RestoreV2_1 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:ps/replica:0/task:0/device:CPU:0"](_recv_save_1/Const_0_S7, save_1/RestoreV2_1/tensor_names, save_1/RestoreV2_1/shape_and_slices)]]
         [[Node: save_1/restore_all/NoOp_S10 = _Recv[client_terminated=false, recv_device="/job:worker/replica:0/task:0/device:GPU:0", send_device="/job:ps/replica:0/task:0/device:GPU:0", send_device_incarnation=1493071510865629599, tensor_name="edge_147_save_1/restore_all/NoOp", tensor_type=DT_FLOAT, _device="/job:worker/replica:0/task:0/device:GPU:0"]()]]



when I decrease the model size, the error changed:
tensorflow.python.framework.errors_impl.OutOfRangeError: Read less bytes than requested
         [[Node: save_1/RestoreV2_3 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT], _device="/job:ps/replica:0/task:1/device:CPU:0"](_recv_save_1/Const_0_S1, save_1/RestoreV2_3/tensor_names, save_1/RestoreV2_3/shape_and_slices)]]

List the smaller models:
-rw-r--r--   3 root supergroup   11893084 2018-06-06 19:12 /tmp/xxx/model.ckpt-446327.data-00000-of-00008
-rw-r--r--   3 root supergroup  330000440 2018-06-06 19:12 /tmp/xxx/model.ckpt-446327.data-00001-of-00008
-rw-r--r--   3 root supergroup  106483864 2018-06-06 19:12 /tmp/xxx/model.ckpt-446327.data-00002-of-00008
-rw-r--r--   3 root supergroup 5130000440 2018-06-06 19:13 /tmp/xxx/model.ckpt-446327.data-00003-of-00008
-rw-r--r--   3 root supergroup     375688 2018-06-06 19:12 /tmp/xxx/model.ckpt-446327.data-00004-of-00008
-rw-r--r--   3 root supergroup  330000440 2018-06-06 19:12 /tmp/xxx/model.ckpt-446327.data-00005-of-00008
-rw-r--r--   3 root supergroup  232909600 2018-06-06 19:12 /tmp/xxx/model.ckpt-446327.data-00006-of-00008
-rw-r--r--   3 root supergroup  330000440 2018-06-06 19:12 /tmp/xxx/model.ckpt-446327.data-00007-of-00008
-rw-r--r--   3 root supergroup       1564 2018-06-06 19:13 /tmp/xxx/model.ckpt-446327.index
-rw-r--r--   3 root supergroup     571996 2018-06-06 19:13 /tmp/xxx/model.ckpt-446327.meta

**Comment by rothn** [comment]
Any updates, @rohan100jain ?

**Comment by madaoLic** [comment]
I think the root cause may be:
in https://github.com/tensorflow/tensorflow/blob/r1.7/tensorflow/core/platform/hadoop/hadoop_file_system.cc
line 213:

`      tSize r = hdfs_->hdfsPread(fs_, file_, static_cast<tOffset>(offset), dst,
                                 static_cast<tSize>(n));
`

the last param static_cast<tSize>(n) means the number of bytes required. ie., the tensor's size.
in https://github.com/tensorflow/tensorflow/blob/r1.7/third_party/hadoop/hdfs.h
line 75,

typedef int32_t tSize;    /// size of data for read/write io ops

tSize is int32, but tensor's size is int64, when the tensor is big enough, overflow occurs. 

My solution is to use partitioned variables for large tensor, then problem solved.

**Comment by rothn** [comment]
But I'm not using HDFS -- this is all on my local SSD.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @rohan100jain: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @rohan100jain: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by dmbuchta** [comment]
I am having a very similar issue as well. Following [this tutorial](https://www.tensorflow.org/tutorials/estimators/cnn), but working with larger images.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @rohan100jain: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @rohan100jain: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @rohan100jain: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @rohan100jain: It has been 59 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @rohan100jain: It has been 74 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by rohan100jain** [comment]
@allenlavoie seems like we're having issues with large restore? I thought the V2 version of the save restore ops was supposed to fix this. Any ideas?

**Comment by allenlavoie** [comment]
We can put >2GB in checkpoints now. https://github.com/tensorflow/tensorflow/commit/b8c86c3bbd8271ed968087f24e7fb704103bc733#diff-f4340b63dcfb03e060905682f7471faa fixes an int32 size issue for string dtypes. I don't see a similar issue for Tensors, and this error doesn't look like it's a length/checksum issue. From "OP_REQUIRES failed at save_restore_v2_ops.cc:184" and reading the exceptions in the function it's calling, it looks vaguely like this could be complaining about a dtype mismatch? But that could just be the first thing that doesn't match if the whole file is corrupted for some reason.

Can someone distill their issue into a snippet I can run, e.g. with fill()? I ran the following and it seems to work:

```
import tensorflow as tf
from tensorflow.python.ops import io_ops

def main(_):
  tf.enable_eager_execution()
  large = tf.fill([10] * 9 + [5], value=tf.constant(1., dtype=tf.float32))
  path = '/some/network/path'
  io_ops.save_v2([path], ["a"], [""], [large])
  restored = io_ops.restore_v2(path, ["a"], [""], [tf.float32])
  print(tf.reduce_sum(restored))

if __name__ == '__main__':
  tf.app.run()

```

Prints:

`tf.Tensor(5e+09, shape=(), dtype=float32)`

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by shkarupa-alex** [comment]
> We can put >2GB in checkpoints now. [b8c86c3#diff-f4340b63dcfb03e060905682f7471faa](https://github.com/tensorflow/tensorflow/commit/b8c86c3bbd8271ed968087f24e7fb704103bc733#diff-f4340b63dcfb03e060905682f7471faa) fixes an int32 size issue for string dtypes. I don't see a similar issue for Tensors, and this error doesn't look like it's a length/checksum issue. From "OP_REQUIRES failed at save_restore_v2_ops.cc:184" and reading the exceptions in the function it's calling, it looks vaguely like this could be complaining about a dtype mismatch? But that could just be the first thing that doesn't match if the whole file is corrupted for some reason.
> 
> Can someone distill their issue into a snippet I can run, e.g. with fill()? I ran the following and it seems to work:
> 
> ```
> import tensorflow as tf
> from tensorflow.python.ops import io_ops
> 
> def main(_):
>   tf.enable_eager_execution()
>   large = tf.fill([10] * 9 + [5], value=tf.constant(1., dtype=tf.float32))
>   path = '/some/network/path'
>   io_ops.save_v2([path], ["a"], [""], [large])
>   restored = io_ops.restore_v2(path, ["a"], [""], [tf.float32])
>   print(tf.reduce_sum(restored))
> 
> if __name__ == '__main__':
>   tf.app.run()
> ```
> Prints:
> 
> `tf.Tensor(5e+09, shape=(), dtype=float32)`

I've tried this snippet on Mac OS X 10.14.1 + TF 1.12.0
Got such error:

> >>> restored = io_ops.restore_v2(path, ["a"], [""], [tf.float32])
> 2018-11-08 17:27:05.767089: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Invalid argument: /Users/alex/HDD/Develop/semtech/fio/tmp.data-00000-of-00001; Invalid argument
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1486, in restore_v2
>     ctx=_ctx)
>   File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1511, in restore_v2_eager_fallback
>     attrs=_attrs, ctx=_ctx, name=name)
>   File "/usr/local/lib/python3.6/site-packages/tensorflow/python/eager/execute.py", line 66, in quick_execute
>     six.raise_from(core._status_to_exception(e.code, message), None)
>   File "<string>", line 3, in raise_from
> tensorflow.python.framework.errors_impl.InvalidArgumentError: /Users/alex/HDD/Develop/tmp.data-00000-of-00001; Invalid argument [Op:RestoreV2]

**Comment by allenlavoie** [comment]
Interesting, thank you for trying that out. So maybe it is a Mac-specific issue.

Just to check, do you have >20GB of disk and >20GB of RAM free before running that snippet? This could be a badly reported OOM or out-of-disk error I suppose.

**Comment by shkarupa-alex** [comment]
I have about 400Gb free space on disk and total 16Gb of RAM (swapfile ON).
Such issue occurs even if try to load 2.7Gb variable file.

**Comment by allenlavoie** [comment]
Interesting. I'll find a Mac next week and see if I can reproduce on it.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
It has been 29 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
It has been 44 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
We are closing this issue for now due to lack of activity. Please comment if this is still an issue for you. Thanks!

**Comment by shkarupa-alex** [comment]
The issue is still there

**Comment by kwokkawinghk** [comment]
Problem still exist when I restore a 18GB model.

My OS is Windows Server 2016
Tensorflow 1.13.0 installed from pip
512GB memory and hard disk
Only run on CPU.
CUDA 3.6.8

Please advise.

**Comment by kwokkawinghk** [comment]
I also put the below in my code

tf.variable_axis_size_partitioner(
    max_shard_bytes=2**35,
    axis=0,
    bytes_per_string_element=16,
    max_shards=None
)

However it still shows below error when restoring the model:

2019-03-16 08:12:32.430456: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Out of range: Read fewer bytes than requested

**Comment by tensorflowbutler** [comment]
It has been 17 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by kwokkawinghk** [comment]
> It has been 17 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

Yes, it is still an issue

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
It has been 29 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by rothn** [comment]
Yes it’s still an issue

**Comment by allenlavoie** [comment]
Finally got a chance to debug this on a mac. Apparently the `pread` system call, despite taking a four-byte `size_t` for its `nbytes` argument, returns `EINVAL` if "The sum of the iov_len values in the iov array overflowed a 32-bit integer." And presumably `pread` is implemented in terms of `readv` so they have the same limitation.

I have a change out for review which just limits reads to INT32_MAX on every platform. Seems to work if we do that. I checked that the checkpoints themselves were identical to what gets written on Linux, so existing checkpoints will start working once that change is in.

**Comment by Sam-DevZ** [comment]
Uh, this is still an issue? I built the latest version of tensorflow from source and it's still happening! I've tried practically everything.

**Comment by allenlavoie** [comment]
@Sam-DevZ operating system and version, TF git version, repro instructions? The [repro I posted](https://github.com/tensorflow/tensorflow/issues/18769#issuecomment-430030868) works for me on `1.14.1-dev20190522` (nightly) and macOS 10.14.2.

**Comment by Sam-DevZ** [comment]
Hi! Your snippet doesn't work either. Code: 

```Python
import tensorflow as tf
from tensorflow.python.ops import io_ops

print('Tensorflow version: ' + tf.__version__)
print('MacOS Version: ' + '10.14.5')

def main(_):
  tf.enable_eager_execution()
  large = tf.fill([10] * 9 + [5], value=tf.constant(1., dtype=tf.float32))
  path = '/Users/clearlycoder/Desktop/Extra.nosync/Machine Learning.nosync/TensorCNN'
  io_ops.save_v2([path], ["a"], [""], [large])
  restored = io_ops.restore_v2(path, ["a"], [""], [tf.float32])
  print(tf.reduce_sum(restored))

if __name__ == '__main__':
  tf.app.run()
```

Output: 

```
Tensorflow version: 1.12.2
MacOS Version: 10.14.5
2019-05-23 07:16:10.724624: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Invalid argument: /Users/samdevz/Desktop/Extra.nosync/Machine Learning.nosync/TensorCNN.data-00000-of-00001; Invalid argument
Traceback (most recent call last):
  File "/Users/samdevz/Desktop/Extra.nosync/Machine Learning.nosync/TensorCNN/tester.py", line 16, in <module>
    tf.app.run()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/Users/samdevz/Desktop/Extra.nosync/Machine Learning.nosync/TensorCNN/tester.py", line 12, in main
    restored = io_ops.restore_v2(path, ["a"], [""], [tf.float32])
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1486, in restore_v2
    ctx=_ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1511, in restore_v2_eager_fallback
    attrs=_attrs, ctx=_ctx, name=name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/eager/execute.py", line 66, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: /Users/samdevz/Desktop/Extra.nosync/Machine Learning.nosync/TensorCNN.data-00000-of-00001; Invalid argument [Op:RestoreV2]
[Finished in 80.3s with exit code 1]
[cmd: ['/Library/Frameworks/Python.framework/Versions/3.6/bin/python3', '-u', '/Users/samdevz/Desktop/Extra.nosync/Machine Learning.nosync/TensorCNN/tester.py']]
[dir: /Users/samdevz/Desktop/Extra.nosync/Machine Learning.nosync/TensorCNN]
[path: /usr/bin:/bin:/usr/sbin:/sbin]
```

**Comment by Sam-DevZ** [comment]
@allenlavoie

**Comment by Sam-DevZ** [comment]
Oh, er, I'm guessing version 0.12.2 is not recent enough. I need `1.14.1-dev20190522`, right? Haha.

**Comment by Sam-DevZ** [comment]
Sorry! It's definitely fixed. I ran: 

```pip uninstall tensorflow
pip install tf-nightly```

And now it works perfectly. Sorry about that!
