### ISSUE TITLE
Android：No OpKernel was registered to support Op 'Cumsum' with these attrs

### ISSUE THREAD

**Issue by lxwithgod** [tensorflow/tensorflow#18772]
i use http://ci.tensorflow.org/view/Nightly/job/nightly-android/lastStableBuild/  
but i get error on my cell phone，please how can slove this question

04-22 21:43:19.665 11453-11453/com.lemon.demo W/System.err: java.lang.IllegalArgumentException: No OpKernel was registered to support Op 'Cumsum' with these attrs.  Registered devices: [CPU], Registered kernels:
      <no registered kernels>
    	 [[Node: Cumsum = Cumsum[T=DT_FLOAT, Tidx=DT_INT32, exclusive=false, reverse=false](crop_sub_imgs, Cumsum/axis)]]
        at org.tensorflow.Session.run(Native Method)
        at org.tensorflow.Session.access$100(Session.java:48)
        at org.tensorflow.Session$Runner.runHelper(Session.java:298)
        at org.tensorflow.Session$Runner.run(Session.java:248)
        at org.tensorflow.contrib.android.TensorFlowInferenceInterface.run(TensorFlowInferenceInterface.java:228)
        at org.tensorflow.contrib.android.TensorFlowInferenceInterface.run(TensorFlowInferenceInterface.java:197)

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by lxwithgod** [comment]
I use tf.cumsum

**Comment by lxwithgod** [comment]
@tensorflowbutler

**Comment by tensorflowbutler** [comment]
Nagging Assignee @jart: It has been 16 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by jart** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!

**Comment by Jack10001** [comment]
Have you solved it? I met the same error.
