### ISSUE TITLE
pywrap_tensorflow_internal cannot load/not found - Windows tensorflow CPU

### ISSUE THREAD

**Issue by jimlynnjulian** [tensorflow/tensorflow#18785]
I have finished attempting installations of tensorflow CPU for Windows using Python3.5 and 3.6. I've tried installing a wheel placed in the Python directory. 
I tried installing from the web vis a vis Pip. 
I've tried adding paths to PYTHONPATH and PATH (Windows).
 I've done everything but install in a virtual environment using Anaconda. 
The traceback is always the same. 
The pywrap_tensorflow_internal files are in place but do not seem to be visible to the import routines. 
(*.pyd, *.py, *.pyl). I placed the pyd DLL in the System32 directory with no change.
I tried using Python 3.6 installed in the root and installing a c36 amd64 wheel and a c35 amd64 wheel from Python 3.5 in C:/User/nnnnn/AppData/Local---etc.. 
I'm using Win 10 Pro x64 on a laptop with Intel Core 2 Duo processor. No Nvidia GPU card. 
Everything installs and seems to run, including Swig, but still the install fails when I run ">>>import tensorflow as tf" from a python command line session.
I haven't tried the Bazel or Anaconda approaches since I'm using Tensorflow with Tensorlayer and SRGAN for image recognition. I don't know if the virtual environment will be compatible yet.
The output from the attempts follows:

">>> import tensorflow as tf
Traceback (most recent call last):
  File "C:\Users\jimjulian\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Users\jimjulian\AppData\Local\Programs\Python\Python35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 577, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 903, in create_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jimjulian\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\jimjulian\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 17, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\jimjulian\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 16, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow_internal')
  File "C:\Users\jimjulian\AppData\Local\Programs\Python\Python35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\jimjulian\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import *  # pylint: disable=redefined-builtin
  File "C:\Users\jimjulian\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\jimjulian\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\jimjulian\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Users\jimjulian\AppData\Local\Programs\Python\Python35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 577, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 903, in create_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jimjulian\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\jimjulian\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 17, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\jimjulian\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 16, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow_internal')
  File "C:\Users\jimjulian\AppData\Local\Programs\Python\Python35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: No module named '_pywrap_tensorflow_internal'

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
>>>"

Any suggestions will be appreciated.

**Comment by vijaysaimutyala** [comment]
Which version of TensorFlow are you trying to install? Try installing 1.5 or 1.4.

1.6 & beyond does not seem to work on Windows CPU well.

**Comment by jimlynnjulian** [comment]
Thanks Vijay. I got 1.5.1 going. The install needed an internet connectyion to find a compatible tensorboard, but after that, ,everything went smoothly.

**Comment by vijaysaimutyala** [comment]
I'm curious if this issue with Windows CPU version is being looked on in any other open issues ? The TFLite  does not seem to supported in version <1.7 which means that I'm limited to not using TFLite for any mobile models.
