### ISSUE TITLE
Tensorflow object detection API

### ISSUE THREAD

**Issue by alisalar1000** [tensorflow/tensorflow#18790]
Traceback (most recent call last):
  File "export_inference_graph.py", line 147, in <module>
    tf.app.run()
  File "C:\Users\Ali Salar\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\platform\app.py", line 126, in run
    _sys.exit(main(argv))
  File "export_inference_graph.py", line 143, in main
    FLAGS.output_directory, input_shape)
  File "C:\tensorflow2\models\research\object_detection\exporter.py", line 453, in export_inference_graph
    graph_hook_fn=None)
  File "C:\tensorflow2\models\research\object_detection\exporter.py", line 421, in _export_inference_graph
    placeholder_tensor, outputs)
  File "C:\tensorflow2\models\research\object_detection\exporter.py", line 280, in write_saved_model
    builder = tf.saved_model.builder.SavedModelBuilder(saved_model_path)
  File "C:\Users\Ali Salar\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\saved_model\builder_impl.py", line 90, in __init__
    "directory: %s" % export_dir)
AssertionError: Export directory already exists. Please specify a different export directory: inference_graph\saved_model

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by zedyao** [comment]
As the error message indicates, the output directory you specified already exists. You should either 1) change the output directory; or 2) try to backup and delete the already-exist "saved-model" folder, then run it again

**Comment by michaelisard** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!

**Comment by Rojina99** [comment]
This might be helpful :
https://www.youtube.com/watch?v=Rgpfk6eYxJA
