### ISSUE TITLE
Android Example won't run: AndroidRuntime: FATAL EXCEPTION NullPointerException

### ISSUE THREAD

**Issue by anonym24** [tensorflow/tensorflow#18891]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Android 6.0.1
- **TensorFlow installed from (source or binary)**: not used
- **TensorFlow version (use command below)**: not used
- **Python version**:  not used
- **Bazel version (if compiling from source)**: not used
- **GCC/Compiler version (if compiling from source)**: not used
- **CUDA/cuDNN version**: not used
- **GPU model and memory**: not used
- **Exact command to reproduce**: download android example project https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/android, set `def nativeBuildSystem = 'none'`, try to start **Detector Activity**

### Describe the problem
**AndroidRuntime: FATAL EXCEPTION NullPointerException**

### Source code / logs
```
04-26 09:43:01.808 2417-2475/? E/AndroidRuntime: FATAL EXCEPTION: inference
    Process: org.tensorflow.demo, PID: 2417
    java.lang.NullPointerException: Attempt to invoke interface method 'java.util.List org.tensorflow.demo.Classifier.recognizeImage(android.graphics.Bitmap)' on a null object reference
        at org.tensorflow.demo.DetectorActivity$3.run(DetectorActivity.java:289)
        at android.os.Handler.handleCallback(Handler.java:742)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:157)
        at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by anonym24** [comment]
so it run ok for next android studio run

as temporary solution I added try...catch in case it will happen again

 ```
  runInBackground(
        new Runnable() {
          @Override
          public void run() {
            try {
              LOGGER.i("Running detection on image " + currTimestamp);
              final long startTime = SystemClock.uptimeMillis();
              final List<Classifier.Recognition> results = detector.recognizeImage(croppedBitmap);
              lastProcessingTimeMs = SystemClock.uptimeMillis() - startTime;

              cropCopyBitmap = Bitmap.createBitmap(croppedBitmap);
              final Canvas canvas = new Canvas(cropCopyBitmap);
              final Paint paint = new Paint();
              paint.setColor(Color.RED);
              paint.setStyle(Style.STROKE);
              paint.setStrokeWidth(2.0f);

              float minimumConfidence = MINIMUM_CONFIDENCE_TF_OD_API;
              switch (MODE) {
                case TF_OD_API:
                  minimumConfidence = MINIMUM_CONFIDENCE_TF_OD_API;
                  break;
                case MULTIBOX:
                  minimumConfidence = MINIMUM_CONFIDENCE_MULTIBOX;
                  break;
                case YOLO:
                  minimumConfidence = MINIMUM_CONFIDENCE_YOLO;
                  break;
              }

              final List<Classifier.Recognition> mappedRecognitions =
                      new LinkedList<Classifier.Recognition>();

              for (final Classifier.Recognition result : results) {
                final RectF location = result.getLocation();
                if (location != null && result.getConfidence() >= minimumConfidence) {
                  canvas.drawRect(location, paint);

                  cropToFrameTransform.mapRect(location);
                  result.setLocation(location);
                  mappedRecognitions.add(result);
                }
              }

              tracker.trackResults(mappedRecognitions, luminanceCopy, currTimestamp);
              trackingOverlay.postInvalidate();

              requestRender();
              computingDetection = false;
            } catch (NullPointerException e) {
              e.printStackTrace();
            }
          }
        });
  }
```

**Comment by angersson** [comment]
It looks like the issue is now resolved. If you think you've found a bug, please make another issue with replication information. Thanks!

**Comment by xjohnxjohn** [comment]
@angersson  Could you please tell me what and where to solved this issue?

**Comment by gsadhas** [comment]
@xjohnxjohn I faced the same issue and I solved by following these steps,
1. Sync gradle file if it asks
2. Uninstall existing APKs
3. Run again
