### ISSUE TITLE
Planning Ticket  CUDA 9.2 + cuDNN 7.1

### ISSUE THREAD

**Issue by tfboyd** [tensorflow/tensorflow#18906]
Updated 02-JUNE-2018

I have done some testing with CUDA 9.2/cuDNN 7.1.4/NCCL 2.x with tf_cnn_benchmarks.

Below you will see that if you upgrade to cuDNN 7.1.4 and a newer device driver you get some pretty nice gains and no need to compile from source as well as using CUDA 9.0.  Compiling from source and using NCCL 2.x (Hierarchal Copy was almost the same) I was able to get 6,800+ 8xV100s ResNet50v1 FP16 with synthetic data and about 6,500+ real data sustained over a full run for under 5 hours.  

I suspect many of you saw NVIDIA announce 1K and 1.3K for 1xV100 ResNet50.  That was with **unreleased** libraries and we are working to ensure we can hit those numbers when the libraries are available or with our own tricks.

I apologize for any short hand I use below in describing the runs.  I am happy to answer questions or make clarifications.  This testing was slightly informal but recent full scale testing yielded similar results.  

**CUDA 9.0**
[Recommended driver] 6,197.70 CUDA 9.0 + 384.13 (v1.8.0-1386-g2dc7575) hierarchical copy
6,620 CUDA 9.0 + 390.59 (v1.8.0-1386-g2dc7575) NCCL
6,613.11 CUDA 9.0 + 396.26 (v1.8.0-2215-gf528eba) NCCL
6,564.9 CUDA 9.0 + 396.26 (v1.8.0-2215-gf528eba) hierarchical copy
6,541.25 CUDA 9.0 + 390.59 (1.9.0.dev20180523) hierarchical copy
6,276.02 CUDA 9.0 + 384.13 (1.9.0.dev20180523) hierarchical copy
6,197.70 CUDA 9.0 + 384.13 (v1.8.0-1386-g2dc7575) hierarchical copy

**CUDA 9.1**
[Recommended driver]  6,227.64 CUDA 9.1 + 390.59 (v1.8.0-2215-gf528eba) hierarchical copy
6,210.28 CUDA 9.1 + 396.26 (v1.8.0-2215-gf528eba) hierarchical copy
6,118.21 CUDA 9.1 + 396.26 (v1.8.0-2215-gf528eba) NCCL

**CUDA 9.2**
[Recommended driver]  6,696.39 CUDA 9.2 + 396.26 (v1.8.0-2215-gf528eba) NCCL
6,606.57 CUDA 9.2 + 396.26 (v1.8.0-2215-gf528eba) hierarchical copy
6,738.32 CUDA 9.2 + 396.26 (v1.8.0-2215-gf528eba) NCCL SGD

**Full test runs with CUDA 9.2**
top_1 ranges between 75.7% and 76% and does not seem to be based on the hyper parameters.  I was focused on testing NCCL vs. hierarchical copy.  I have a minor concern about my validation command, but this is still good info.
Hierarchical copy:  6441.64  Accuracy @ 1 = 0.7584 Accuracy @ 5 = 0.9267 [49920 examples] 
NCCL (repacking:2):  6490.62  Accuracy @ 1 = 0.7572 Accuracy @ 5 = 0.9265 [49920 examples]
NCCL (repacking:8):  6490.62  Accuracy @ 1 = 0.7582 Accuracy @ 5 = 0.9268 [49920 examples]
My first hierarchical copy run was 76% exactly. 

**Note:**  I would like to move to CUDA 9.2 as the default but the driver is not widely available for easy apt-get install.  I am working long-term to get the build team to support a secondary CUDA build.  I am also very open to feedback as I do not see any easy path forward to moving to newer CUDA versions faster.  You can always (usually) install a new cuDNN.  We are compiling with 7.0 but you see gains by installing 7.1.4 as you see above if you upgrade your driver.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by SephirothFFKH** [comment]
Great! I was able to build TF with the configuration below but the biggest roadblock is to get a version of TensorRT that works with anything above 9.0 hopefully TensorRT 4.1 comes right in time for this r1.9

OS Platform and Distribution: Lubuntu 17.04
TensorFlow installed from Source
TensorFlow version r1.8
GCC version 7
Bazel version 0.12
CUDA/cuDNN version 9.1/7.1
NCCL 2.1.15
TensorRT None
GPU model and memory Dual GTX1080Ti + GTX980Ti

**Comment by ViktorM** [comment]
When 1.9 release can be expected, at least approximately?

**Comment by tfboyd** [comment]
1.9 had a code cut off of 31st May.  It normally takes 1-2 weeks to verify the RCs and let them "bake".  CUDA 9.2 will not be in 1.9 as the default due to CUDA 9.2 not being public yet and in my opinion the device driver is too new and still not available for Debian although you can get it for Ubuntu as "beta".  I am hopeful NVIDIA is making some changes that will reduce this pain.

@SephirothFFKH   I am just getting more involved in including TensorRT.  I did the testing for the NVIDIA "launch" but that was very one off.  Thank you for the info on versions working with 9.2.

**Comment by tfboyd** [comment]
1.9 has a code cut off target of 31st may.  It will not have CUDA 9.2 as the default due to 9.2 not being public yet and the device driver needed is just too new and not in Debian yet.  I am hopeful NVIDIA will resolve the device driver lock for CUDA releases later this year.  Moving CUDA versions forward is always my desire but I worry about abandoning people that cannot upgrade.  I worry more when I see the driver isn't even available on LTS editions of Linux yet.  

@SephirothFFKH  Thank you for the TensorRT info.  I did the initial perf tests for the launch and I am about to start getting more involved again.  I hope we can smooth this out.  I did see some PRs (open source) that make TensorRT easier to use and hopefully even more seamless.  

I appreciate all the comments, I like knowing what is happening so I can try to make things easier to use.  Keep them coming.

**Comment by ViktorM** [comment]
@tfboyd Thanks for clarification! So 1.9 will be shipped with CUDA 9.0 or at least switch to 9.1 could be expected?

**Comment by alanpurple** [comment]
CUDA 9.2 GA is just released and support official driver of course
FYI

**Comment by K3n4** [comment]
I can't find cudnn for cuda 9.2 windows

**Comment by achalshah20** [comment]
I am trying to build tensorflow with cuda 9.2. Although cudnn doesn't support cuda 9.2 officially.

**Comment by alanpurple** [comment]
@K3n4 
@achalshah20 

cudnn also just been released

cudnn 7.1.4 for cuda 9.2

**Comment by achalshah20** [comment]
@alanpurple Thanks!

**Comment by K3n4** [comment]
@alanpurple Thanks,
Is it possible to build tf with this configuration ?

**Comment by alanpurple** [comment]
@K3n4 
I'll skip that one until 1.9rc

as a developer it's not a good timing for trying those, since 1.8 has many compiling issue( intel MPI support for example)

and 1.9 will come with prebuilt binary for cuda 9.2 and cudnn 7.1(so compiling will be promising), and mpi-support issue fixed

1.9rc are planned to come within 2 weeks as far as I know

so I recommend you also wait for 1.9rc

**Comment by mirekphd** [comment]
You've missed CUDA 9.1 and now decide to simply skip it? People will never be able to switch from CUDA 8.0 if the support for CUDAs 9.x among ML algos is so randomly scattered among these 3 versions (and counting)...

**Comment by mirekphd** [comment]
Yes, Tensorflow 1.7 can be built against CUDA 9.1 and CuDNN if you have 1-2 hours per each try and don't want automated builds (e.g. for Docker). [Here's how to do it](http://www.python36.com/install-tensorflow141-gpu/), dear Tensorflow team.

**Comment by mirekphd** [comment]
But wait, there's more: TinyMind prepared a comprehensive set of [pre-compiled Tensorflow wheels](https://github.com/mind/wheels), including those for CUDA 9.1. Make sure to star their hard work.

**Comment by alanpurple** [comment]
@mirekphd  no i'm using 9.1 to build tf-gpu 1.8 and i'm using it
i'm skipping 9.2 for 1.8, waiting 1.9rc

**Comment by mirekphd** [comment]
@alanpurple, if you have a working wheel for TF 1.8 compiled under CUDA 9.1 and CuDNN 7.1.2, than consider contributing it to TinyMind, they seem to be missing 1.8

**Comment by mirekphd** [comment]
@Harbing: try to
```
apt install protobuf-compiler 
```
as it helped others [here](https://github.com/tensorflow/tensorflow/issues/17629)

**Comment by fredguth** [comment]
@mirekphd, unfortunately there is no CUDA 9.2 build there.  To sum up, the problem is that Nvidia is pointing users to install CUDA 9.2, but the available builds are 9.0 compatible only.  It seems that the only solution is either downgrade to CUDA 9.0 (could use some help here, I couldn't find a simple way in Nvidia's site) or to compile Tensorflow from source.

**Comment by tfboyd** [comment]
It was just released a couple days ago.  There are a few problems:

1) It shipped day one with a patch
2) the device driver is very new  396.26 is needed. Ubuntu does not have it in their repo just yet and it will be a while before Debian has it even in experimental.  The DGX-1 also does not have a driver that supports it.  

Not sure who will read this, but I am concluding that we should roll out TensorFlow with 9.1 as the default, which seems to be stable with ~4 patches you have to apply.  The downside is the NVIDIA download site for cuDNN does not list 9.1 but I think you can just use cuDNN based on 9.0 and that is just a typo.  

Very much welcome feedback.  Keep in mind the target audience is a wide range of people and upgrade to a device driver released just a few years ago as a requirement to install TensorFlow is a little steep.  

I would also like feedback on this idea:  I would like to have a second "cutting edge" build that is linux only to reduce the amount of resources needed to test and deploy.  Likely linux + python 2.x.  This will be really vital to many of you when we start playing with CUDA 10.  I am not aware of anything huge in CUDA 9.0 to 9.2 that is amazing but with data as proof I could be very wrong.

**Comment by patrikhuber** [comment]
> upgrade to a device driver released just a few years ago

I think you probably mean "days", not years, right? :-)

Another side of the story might be that people who right away upgrade to the newest TensorFlow version are cutting-edge anyway and also don't mind upgrading to the latest device driver.
I do believe that there's a significant portion of people that like to live on the "edge" and have the latest stuff, particularly with respect to CUDA version.

> have a second "cutting edge" build
I do like the idea about that. Would be nice if there was a Windows build too though. Doesn't have to be for all Python versions etc., just the latest would be fine, to reduce the number of builds needed.

But why would you use python 2.x for that? There's not really much "cutting edge" about that. I don't think I even have python 2.x installed anymore.

**Comment by fo40225** [comment]
@tfboyd cudnn 7.1.4 for cuda 9.2 is link to *_92.dll and for 9.0 use *_90.dll. It is not typo, nvidia delete all cudnn 7.1.* for cuda 9.1 download link except for Linux (Power8/Power9) with 7.1.2.

@patrikhuber 
Here is tensorflow-gpu1.8.0 with cuda 9.2, cudnn 7.1.4 for windows, and this repo contain tensorflow with python2 for windows.

https://github.com/fo40225/tensorflow-windows-wheel/tree/master/1.8.0/py36/GPU/cuda92cudnn71sse2

**Comment by prova** [comment]
@fo40225 Thanks for this wheel, I am able to install it under Anaconda 3.6 Python on a dual-1080 Ti machine with the latest official CUDA 9.2 driver 397.93, and run Keras R.

**Comment by longxi7997** [comment]
@fo40225 Thanks for your answer , it works for me.

**Comment by arunmandal53** [comment]
Finally a tutorial on [How to install Tensorflow GPU with CUDA 9.2, cudnn 7.1.4 and NCCL 2.2 for python on Ubuntu](http://www.python36.com/how-to-install-tensorflow-gpu-with-cuda-9-2-for-python-on-ubuntu/)

**Comment by mtianyan** [comment]
@arunmandal53  I try this tutorial on ubuntu18.04，Failed。

**Comment by VRscience** [comment]
@fo40225 I installed tensorflow-gpu1.8.0 with cuda 9.2, cudnn 7.1.4 for windows but i still get this error message when importing tensorflow:

Traceback (most recent call last):
  File "C:\Users\royba\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\platform\self_check.py", line 75, in preload_check
    ctypes.WinDLL(build_info.cudart_dll_name)
  File "C:\Users\royba\AppData\Local\conda\conda\envs\tensorflow\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\royba\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\royba\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\royba\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 30, in <module>
    self_check.preload_check()
  File "C:\Users\royba\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\platform\self_check.py", line 82, in preload_check
    % (build_info.cudart_dll_name, build_info.cuda_version_number))
ImportError: Could not find 'cudart64_90.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Download and install CUDA 9.0 from this URL: https://developer.nvidia.com/cuda-toolkit

shouldn't it recall cudart64_92.dll rather than cudart64_90.dll?

**Comment by purpledawn777** [comment]
@fo40225 I get the same issue as @VRscience  above!

**Comment by purpledawn777** [comment]
...well I take that back. after exiting the command line and opening a new command window and re-activating the conda environment I did the installation in, going into python not longer showed the error above. 
running python without pre-activating the conda environment did complain.

**Comment by VRscience** [comment]
@purpledawn777 Are you using CUDA 9.2 toolkit? No other CUDA toolkit is installed in your machine?
I am still struggling with it but I do not really see how to solve the issue but downgrade to CUDA 9.0...

**Comment by purpledawn777** [comment]
I am using toolkit 9.2 
I installed in an anaconda environment and I first created a tensorflow conda environment, as instructed.
when testing it complained about not finding cuda 9.0.
I then installed the wheel nicely provided by fo40225 
when I tested immediately it still had the error, but then when I reopened the command line, activate tensorflow and tested again, it worked.... sorta -- it now complained about missing cuDNN7, but I just had to install that from Nvidia's website into the cuda 9.2 directories and it works fully now.

**Comment by VRscience** [comment]
@purpledawn777 I did exactly the same but i keep on having the same issue. Also, it seems there is no more need of installing the wheel provided by @fo40225 as on (tensorflow)C:> pip install --ignore-installed --upgrade tensorflow-gpu the wheel installed is already tensorflow_gpu-1.8.0-cp36-cp36m-win_amd64.whl . 

Any idea?

**Comment by tfboyd** [comment]
@mirekphd 
Sorry for the slow response. Every PR for TensorFlow is unit tested across every platform we support and then internally run against an even large set of tests.  Adding another version of CUDA expands the matrix and we are currently using hundreds of GPUs just for the unit testing much less performance testing.  CUDA 9.1 ended up being a slight perf regression depending on how you look at the results and what is compared.  I like all the builds people do to try out new things.

NVIDIA's official DGX-1 also was not upgraded and still, as of today, only supports CUDA 9.0 with the official image.

@fo40225 You likely figured this out but you can just use the CUDA 9.0 cuDNN with CUDA 9.1.  That is what NVIDIA suggested when I saw that a few days back.  I would not bother with CUDA 9.1.

@ViktorM  1.9 will be CUDA 9.0.  CUDA 9.1 seems to have a perf regression (check out my updated original post above) or I might have pushed for the upgrade after the driver for CUDA 9.2 was newer than I expected.  I am still working on NCCL 2.x as that provides a nice boost, but there are some license issues to work out.

**Note**:  I think it is cool other people post how to compile.  The community likely does a better job than I would as I take short cuts and have some weird preferences as to how I like to install things.  I also only do linux and old python (@patrikhuber :-))  What I can do in the future is post how I compiled along with the sha-hash or branch where I did so.  Far from perfect and if other people are ahead of me that is great.  I have a small insight.  TensorFlow is part of the Brain team at Google.  While some might upgrade to the latest versions of cuDNN and such, it is not something I hear people talking about.  I am still hopeful that CUDA 10 will bring a new approach to drivers that makes it easier for us to roll out minor CUDA bumps with less pain.  

**As a random note.**  I strongly suggest using Docker.  I use to deal with all of these different versions of CUDA in python virtual environments.  I feel kind of silly having not moved to docker sooner.  So much better.

**Comment by yukoba** [comment]
If someone wants to install CUDA 9.2 to Ubuntu 18.04, use this.

```
sudo apt-key adv --fetch-keys http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1710/x86_64/7fa2af80.pub
echo "deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1710/x86_64 /" | sudo tee /etc/apt/sources.list.d/cuda.list
sudo apt update
sudo apt -o Dpkg::Options::="--force-overwrite" install cuda-9-2 cuda-drivers
sudo reboot
```

**Comment by tfboyd** [comment]
I still think all of you are nuts not to just use docker and just keep your local device driver updated.  :-)  That is how I do the performance test if you were curious.  Total docker convert here and I fought it to the end.

**Comment by mtianyan** [comment]
@yukoba  Have you try these command on ubuntu18.04， I try the first command
```
sudo apt-key adv --fetch-keys http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1710/x86_64/7fa2af80.pub
```
I got:

```
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
```

and when i use the command `sudo apt update`:

```
W: GPG error: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1710/x86_64  Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY F60F4B3D7FA2AF80
E: The repository 'https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1710/x86_64  Release' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by mtianyan** [comment]
I build the cuda9.2 for TensorFlow1.8.0 on python3.6 use the ubuntu18.04

https://github.com/mtianyan/tensorflow-linux-wheel

**Comment by alanhsieh2000** [comment]
I migrated to TensorFlow r1.8 with cuda 9.2.88+patch 1, cuDNN 7.1.4  from r1.3 20 days ago. Maybe some issues I experienced and found the way out would help you.
https://github.com/tensorflow/tensorflow/issues/19371

**Comment by XiaoqiChai** [comment]
@alanhsieh2000  
Hi, I also have cuda 9.2.88 with patch1, cuDNN 7.1.4, and tensorflow-gpu 1.8 in conda virtue environment with python 3.6. But I got following problem. Do you have any ideas?

ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory

Thanks!

**Comment by alanhsieh2000** [comment]
@XiaoqiChai 
Did you build tensorflow r1.8 from source? It looks like your python is trying to load cuda 9.0 rather than cuda 9.2. This information is specified when you configure Bazel before you started to build. You have to give it 9.2 rather than 9, when the config tool asks you for the cuda version.

**Comment by hadim** [comment]
I have recently created a Dockerfile that make it easy for anyone to compile tensorflow in Linux: https://github.com/hadim/docker-tensorflow-builder

**Comment by Sri06006** [comment]
Install Cuda 9.2.88_windows 10, and cuDNN 7.1 for cuda 9.2. dll is copied to "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.2\bin".  
installed tensorflow gpu python 3.6
But getting error while importing tensorflow
(tf15) C:\Users\91966>python
Python 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
Traceback (most recent call last):
  File "C:\Users\91966\Anaconda3\envs\tf15\lib\site-packages\tensorflow\python\platform\self_check.py", line 75, in preload_check
    ctypes.WinDLL(build_info.cudart_dll_name)
  File "C:\Users\91966\Anaconda3\envs\tf15\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\91966\Anaconda3\envs\tf15\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\91966\Anaconda3\envs\tf15\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\91966\Anaconda3\envs\tf15\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 30, in <module>
    self_check.preload_check()
  File "C:\Users\91966\Anaconda3\envs\tf15\lib\site-packages\tensorflow\python\platform\self_check.py", line 82, in preload_check
    % (build_info.cudart_dll_name, build_info.cuda_version_number))
ImportError: Could not find 'cudart64_90.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Download and install CUDA 9.0 from this URL: https://developer.nvidia.com/cuda-toolkit
>>>

I tried to downgrade to 9.0, but failed to so.

Is there a solution for issue#1 and if not how do I downgrade to 9.0?

**Comment by Enumaris** [comment]
@VRscience Have you found a solution to your issue yet? I am getting the exact same issue (and it looks like @Sri06006 has run into this issue as well). It does look like the wheel being installed when running `pip install --upgrade tensorflow-gpu` is the one that purports to be for cuda 9.2 (the one @fo40225 posted) and yet when you look into the `build_info` after installation, it definitely says the build version is for cuda 9.0. So I am confused. I've tried uninstalling and reinstalling, clearing my cache and then reinstalling, and nothing seems to work. The only thing I can think to do right now is to install cuda 9.0 alongside cuda 9.2 (they can coexist afaik) and see if that helps, but it seems like I will be missing out on any potential performance boosts with cuda 9.2.

**Comment by Enumaris** [comment]
@Sri06006 I was also able to get things working by installing CUDA 9.0. I installed it along side CUDA 9.2 since I was told they can coexist. Things are working, but I still think it's odd that the whl file's description would say it has CUDA 9.2 support if it only explicitly looks for CUDA 9.0.

**Comment by beew** [comment]
I have successfully built and run tensorflow1.8 and 1.9rc1 against cuda9.2 and cudnn 7.1, with python3.5 on Ubuntu 16.04. I put cuda9.2 stuffs in a separate test folder and source this script when building and whenever I run these version of tf (tf1.9 compiled with openmpi. but need to change
line 76 of tensorflow/tensorflow/contrib/mpi_collectives/kernels/mpi_ops.cc  from se to stream_executor or build would fail) 

$PYTHONUSERBASE is set to the test folder so pip3 install --user would install the test tf whl inside the test folder without messing up the system's version. To invoke it would need to prepend $PYTHONPATH accordingly
```
export PREFIX=/home/beew/opt/cuda_test/cuda92
export PATH=$PREFIX/cuda/bin:$PREFIX/bin:$PATH
export CUDA_SDK_ROOT_DIR=$PREFIX/samples/common
export TENSORRT_PATH=$PREFIX/TensorRT-4.0.1.6

export LD_LIBRARY_PATH=$PREFIX/cuda/lib64:$PREFIX/cuda/extras/CUPTI/lib64:$LD_LIBRRAY_PATH:$TENSORRT_PATH/lib

export PYTHONUSERBASE=$PREFIX

export PYTHONPATH=$PREFIX/lib/python3.5/site-packages:$PYTHONPATH

export MPI_HOME=/usr/lib/openmpi

export CPATH=$PREFIX/include:$CPATH
export LIBRARY_PATH=$PREFIX/lib:$LIBRARY_PATH
export LD_LIBRARY_PATH=$PREFIX/lib:$LD_LIBRARY_PATH

alias nvblas92="LD_PRELOAD=$PREFIX/cuda/lib64/libnvblas.so"
```

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tfboyd: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by alanpurple** [comment]
this issue can be closed, it's working with cuda 9.2 and cudnn 7.1 already

**Comment by tfboyd** [comment]
@sliedes  The part you may be missing is licensing and the legal ability to distribute something like CUDA, cuDNN (officially it is behind a login), or the other associated libraries.

As a side thing, I updated the install guide to include [installing everything from NVIDIA with apt-get](https://www.tensorflow.org/versions/r1.10/install/install_linux#tensorflow_gpu_support).  I have done this myself on a clean system and it seems to be smooth.  I would still do it from docker as it is easy to get the packages mixed up and get the versions misaligned.

On a positive side CUDA 10 will not require device driver updates and amusingly enough is going to be more backwards compatible than CUDA 9.2.  I and I am sure others have been working with NVIDIA to simplify everything.

**Comment by fangyihao** [comment]
Hopefully, this wheel file below helps. 
TensorFlow 1.9.0 build with cuda 9.2, cudnn 7.1.4 and python 3.5 on ubuntu 16.04: 
https://github.com/fangyihao/tensorflow-wheels/blob/master/tensorflow-1.9.0-cp35-cp35m-linux_x86_64.whl

**Comment by LukeSBE** [comment]
hi is there a Windows build that works with Cuda 9.2?

9.0 is 10 months out of date and tensorflow is unusable.

**Comment by haramoz** [comment]
Does someone have a way to build tensorflow-gpu for centOS and cuda 9.2. My cluster admin has updated driver and removed cuda 9.0 i can not fin anything for cuda 9.2 and CENTOS Linux. If anyone can make one or have a clue please let me know. Thank you  :(

**Comment by beew** [comment]
I have been able to build tensorflow-gpu on Cuda 9.2 and Cuda 10 on Ubuntu 16.04, basically just configure, choose your options and install whatever missing. Shouldn't be a problem on  Centos if you have up to date bazel and Nvidia driver

**Comment by tfboyd** [comment]
I have started a thread on CUDA 10. 

https://github.com/tensorflow/tensorflow/issues/22706

**Comment by edumucelli** [comment]
> Hopefully, this wheel file below helps.
> TensorFlow 1.9.0 build with cuda 9.2, cudnn 7.1.4 and python 3.5 on ubuntu 16.04:
> https://github.com/fangyihao/tensorflow-wheels/blob/master/tensorflow-1.9.0-cp35-cp35m-linux_x86_64.whl
@fangyihao how have you built this one? Any chance you can share the dockerfile (if any)?
