### ISSUE TITLE
tf.keras.utils.plot_model with Sequential API

### ISSUE THREAD

**Issue by brge17** [tensorflow/tensorflow#18908]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.7.0
- **Python version**: 2.7
- **Bazel version (if compiling from source)**: n/a
- **GCC/Compiler version (if compiling from source)**: n/a
- **CUDA/cuDNN version**: n/a
- **GPU model and memory**: n/a 
- **Exact command to reproduce**: See code/logs.

### Describe the problem
tf.keras.utils.plot_model does not work with a model specified in the Sequential API.

### Source code / logs
```
import tensorflow as tf

model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(10, input_dim=50))

tf.keras.utils.plot_model(model, "sequential.png")
```

Error tensorflow 1.7.0:
```
Traceback (most recent call last):
  File "plot_tf.py", line 6, in <module>
    tf.keras.utils.plot_model(model, "sequential.png")
  File "/Users/removed/.local/lib/python2.7/site-packages/tensorflow/python/keras/_impl/keras/utils/vis_utils.py", line 149, in plot_model
    dot = model_to_dot(model, show_shapes, show_layer_names, rankdir)
  File "/Users/removed/.local/lib/python2.7/site-packages/tensorflow/python/keras/_impl/keras/utils/vis_utils.py", line 123, in model_to_dot
    if node_key in model._container_nodes:
AttributeError: 'Model' object has no attribute '_container_nodes'
```

Error tensorflow 1.8.0.rc1
```
Traceback (most recent call last):
  File "plot_tf.py", line 6, in <module>
    tf.keras.utils.plot_model(model, "sequential.png")
  File "/Users/removed/.local/lib/python2.7/site-packages/tensorflow/python/keras/_impl/keras/utils/vis_utils.py", line 149, in plot_model
    dot = model_to_dot(model, show_shapes, show_layer_names, rankdir)
  File "/Users/removed/.local/lib/python2.7/site-packages/tensorflow/python/keras/_impl/keras/utils/vis_utils.py", line 80, in model_to_dot
    model = model.model
AttributeError: 'Sequential' object has no attribute 'model'
```

**Comment by brge17** [comment]
Note in tensorflow 1.8.0.rc1 the functional API appears to be working:

```
import tensorflow as tf

inputs = tf.keras.layers.Input(shape=(784,))
outputs = tf.keras.layers.Dense(10)(inputs)
model = tf.keras.models.Model(inputs=inputs, outputs=outputs)

tf.keras.utils.plot_model(model, "functional.png")
```

in tensorflow 1.7.0 the functional API has the same error as the Sequential API.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @shivaniag: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.
