### ISSUE TITLE
TensorFlow Tutorials should have a Jupyter notebook friendly option

### ISSUE THREAD

**Issue by ArriFerrari** [tensorflow/tensorflow#18929]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: 
Nope
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Windows 10 (latest 04/27/2018)
- **TensorFlow installed from (source or binary)**:
python -m pip install tensorflow
- **TensorFlow version (use command below)**:
1.7.0
- **Python version**: 
3.6.5
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: 9.0/1.7
- **GPU model and memory**: GeoForce GTX 1050Ti (4GB)
- **Exact command to reproduce**:
I opened jupyter notebook in my main python installation: 
C:\Users\ (me) \AppData\Local\Programs\Python\Python36\Scripts\jupyter-notebook.exe
I downloaded the master models folder, put it in my jupyter directory and went to
http://localhost:8888/tree/models-master/official/wide_deep
Then I created a new notebook (in the wide_deep directory) and tried to do the very first shell command

! data_download.py

### Describe the problem
The TensorFlow tutorial code (https://www.tensorflow.org/tutorials/wide) can't be run from Jupyter notebook. TensorFlow is a tool mainly for data scientists and we use Jupyter notebook a lot! The official tutorial/sample code should have a Jupyter friendly option.

### Source code / logs
Traceback (most recent call last):
  File "data_download.py", line 71, in <module>
    tf.app.run(argv=[sys.argv[0]] + unparsed)
  File "C:\Users\shado\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\platform\app.py", line 126, in run
    _sys.exit(main(argv))
  File "data_download.py", line 60, in main
    tf.gfile.MkDir(FLAGS.data_dir)
  File "C:\Users\shado\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 358, in create_dir
    pywrap_tensorflow.CreateDir(compat.as_bytes(dirname), status)
  File "C:\Users\shado\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: Failed to create a directory: /tmp/census_data; No such file or directory

**Comment by tensorflowbutler** [comment]
Nagging Assignee @michaelisard: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @MarkDaoust: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @MarkDaoust: It has been 30 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @MarkDaoust: It has been 45 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by MarkDaoust** [comment]
Your problem was mostly just a question of setting the python path correctly.

See working example here:

https://colab.research.google.com/github/tensorflow/models/blob/master/samples/core/tutorials/estimators/linear.ipynb#scrollTo=-MPr95UccYvL
