### ISSUE TITLE
ERROR: in target '//external:cc_toolchain': no such package '

### ISSUE THREAD

**Issue by helloworkcupid** [tensorflow/tensorflow#18930]
ERROR: in target '//external:cc_toolchain': no such package '@local_config_cc//': Traceback (most recent call last):
        File "C:/users/wondercupid/appdata/local/temp/_bazel_wondercupid/dlqxfaaz/external/bazel_tools/tools/cpp/cc_configure.bzl", line 37
                configure_windows_toolchain(repository_ctx)
        File "C:/users/wondercupid/appdata/local/temp/_bazel_wondercupid/dlqxfaaz/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 302, in configure_windows_toolchain
                tpl(repository_ctx, "CROSSTOOL", {"%{cpu...}": ""})
        File "C:/users/wondercupid/appdata/local/temp/_bazel_wondercupid/dlqxfaaz/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 314, in tpl
                _get_escaped_windows_msys_crosstool_content(repository_ctx)
        File "C:/users/wondercupid/appdata/local/temp/_bazel_wondercupid/dlqxfaaz/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 42, in _get_escaped_windows_msys_crosstool_content
                auto_configure_fail(("Could not determine MSYS/Cygwi...))
        File "C:/users/wondercupid/appdata/local/temp/_bazel_wondercupid/dlqxfaaz/external/bazel_tools/tools/cpp/lib_cc_configure.bzl", line 84, in auto_configure_fail
                fail(("\n%sAuto-Configuration Error:%...)))

Auto-Configuration Error: Could not determine MSYS/Cygwin root from BAZEL_SH (e:/msys32/usr/bin)
INFO: Elapsed time: 7.287s
FAILED: Build did NOT complete successfully (2 packages loaded)

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by helloworkcupid** [comment]
OS Platform and Distribution windows10 msys2
TensorFlow installed from source(git clone --recurse-submodules https://github.com/tensorflow/tensorflow.git)
TensorFlow version (up)
Bazel version 0.12.0
CUDA/cuDNN version cuda 9.1 cuDNN 9.10
GPU model and memory NVIDIA GeForce GTX 850
Exact command to reproduce.

please help me

**Comment by HarshHC** [comment]
Im getting a simillar error. Found any solution so far?

**Comment by helloworkcupid** [comment]
No，，，，

**Comment by tensorflowbutler** [comment]
Nagging Assignee @cy89: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @cy89: It has been 47 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @cy89: It has been 62 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by cy89** [comment]
@helloworkcupid this looks like an install/build error. Have you tried the different issues on the Install Tensorflow on Windows page:
https://www.tensorflow.org/install/install_windows

In particular, have you tried the uninstall/reinstall sequence on StackOverflow:
https://stackoverflow.com/questions/42006320/tensorflow-pip-installation-issue-cannot-import-name-descriptor

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
It has been 29 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
It has been 44 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
We are closing this issue for now due to lack of activity. Please comment if this is still an issue for you. Thanks!
