### ISSUE TITLE
bug of tf.extract_image_patches

### ISSUE THREAD

**Issue by DC-Swind** [tensorflow/tensorflow#18962]
### System information
- **OS Platform and Distribution**: Linux Ubuntu  16.04
- **TensorFlow installed from pip**:
- **TensorFlow version**: 1.5
- **Python version**: 2.7 
- **CUDA/cuDNN version**: 8.0
- **Have I written custom code**: N/A
- **Bazel version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**: N/A

### the problem
I have a input "x" which size is (batch, width, height, chanel), because the height of data is variable. so x.get_shape() is (?, 20, ?, 64). I use the following code to do something like im2col:
`im2col = tf.extract_image_patches(x, ksizes=[1, 1, KERNEL_SIZE, 1], strides=[1, 1, 1, 1], rates=[1, 1, 1, 1], padding="SAME")
`
the output "im2col" lost some shape, so I use the following code to set_shape:
 `im2col.set_shape([shape1, shape2, shape3, KERNEL_SIZE * shape4])`
and then reshape im2col to (shape1, shape2, shape3, KERNEL_SIZE, shape4)

In the process of building graph, errors arise when processing optimization algorithms (Adam).

> TypeError: unsupported operand type(s) for /: 'NoneType' and 'long'

I'm sure the error is produced by tf.extract_image_patches. If I replace tf.extract_image_patches with tf.tile (to make the output size of tf.tile same as tf.extract_image_patches), graph will be built sucessfully.

### Error message
Traceback (most recent call last):
  File "/home/anaconda2/bin/t2t-trainer", line 32, in <module>
    tf.app.run()
  File "/home/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 129, in run
    _sys.exit(main(argv))
  File "/home/anaconda2/bin/t2t-trainer", line 28, in main
    t2t_trainer.main(argv)
  File "/home/anaconda2/lib/python2.7/site-packages/tensor2tensor/bin/t2t_trainer.py", line 338, in main
    execute_schedule(exp)
  File "/home/anaconda2/lib/python2.7/site-packages/tensor2tensor/bin/t2t_trainer.py", line 288, in execute_schedule
    getattr(exp, FLAGS.schedule)()
  File "/home/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 635, in train_and_evaluate
    self.train(delay_secs=0)
  File "/home/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 377, in train
    saving_listeners=self._saving_listeners)
  File "/home/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 824, in _call_train
    saving_listeners=saving_listeners)
  File "/home/anaconda2/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 314, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/anaconda2/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 743, in _train_model
    features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
  File "/home/anaconda2/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 725, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/home/anaconda2/lib/python2.7/site-packages/tensor2tensor/utils/t2t_model.py", line 886, in wrapping_model_fn
    use_tpu=use_tpu)
  File "/home/anaconda2/lib/python2.7/site-packages/tensor2tensor/utils/t2t_model.py", line 980, in estimator_model_fn
    loss, num_async_replicas=num_async_replicas)
  File "/home/anaconda2/lib/python2.7/site-packages/tensor2tensor/utils/t2t_model.py", line 984, in estimator_spec_train
    train_op = self.optimize(loss, num_async_replicas=num_async_replicas)
  File "/home/anaconda2/lib/python2.7/site-packages/tensor2tensor/utils/t2t_model.py", line 401, in optimize
    loss, lr, self.hparams, use_tpu=common_layers.is_on_tpu())
  File "/home/anaconda2/lib/python2.7/site-packages/tensor2tensor/utils/optimize.py", line 68, in optimize
    colocate_gradients_with_ops=True)
  File "/home/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/layers/python/layers/optimizers.py", line 241, in optimize_loss
    colocate_gradients_with_ops=colocate_gradients_with_ops)
  File "/home/anaconda2/lib/python2.7/site-packages/tensor2tensor/utils/optimize.py", line 110, in compute_gradients
    gradients = self._opt.compute_gradients(loss, var_list, **kwargs)
  File "/home/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/optimizer.py", line 456, in compute_gradients
    colocate_gradients_with_ops=colocate_gradients_with_ops)
  File "/home/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/gradients_impl.py", line 608, in gradients
    grad_scope, op, func_call, lambda: grad_fn(op, *out_grads))
  File "/home/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/gradients_impl.py", line 374, in _MaybeCompile
    return grad_fn()  # Exit early
  File "/home/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/gradients_impl.py", line 608, in <lambda>
    grad_scope, op, func_call, lambda: grad_fn(op, *out_grads))
  File "/home/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/array_grad.py", line 724, in _ExtractImagePatchesGrad
    cols_out = int(ceil(cols_in / stride_h))
TypeError: unsupported operand type(s) for /: 'NoneType' and 'long'

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by DC-Swind** [comment]
@tensorflowbutler These fields are added now.

**Comment by fmannan** [comment]
The gradient of extract_image_patches currently doesn't support variable sized input. See if PR #17420 works for you.

**Comment by DC-Swind** [comment]
@fmannan Does extract_image_patches support a input whose first dimension(batch dimension) is a variable? e.g. (?, 20, step, 64)
Are there plans to make extract_image_patches support the variable sized input?

**Comment by fmannan** [comment]
@DC-Swind  Yes, the PR that I linked supports variable sized input like the one you have.

**Comment by DC-Swind** [comment]
@fmannan 
I test tf.extract_image_patches in tensorflow 1.5, it supports input size (?, 20, step, 64) but doesn't support (?, 20, ?, 64).
I notice that your PR hasn't been merged. Does it exist any problems or just an approving review is expected? 
If I use this PR to support (?, 20, ?, 64), the only thing is to replace the file "tensorflow/python/ops/array_grad.py" in my tf 1.5?

**Comment by fmannan** [comment]
@DC-Swind I'm not aware of any issues with PR, so I'm expecting it to be merged. You can build TF with the PR and install, or update your `array_grad.py`.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @shivaniag: It has been 19 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @shivaniag: It has been 34 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @shivaniag: It has been 49 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @shivaniag: It has been 64 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @shivaniag: It has been 79 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @shivaniag: It has been 94 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @shivaniag: It has been 109 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @shivaniag: It has been 124 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @shivaniag: It has been 139 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @shivaniag: It has been 154 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @shivaniag: It has been 169 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @shivaniag: It has been 184 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @shivaniag: It has been 199 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by rmothukuru** [comment]
@DC-Swind,
Sorry for the delayed response. This issue has been fixed in [this PR](https://github.com/tensorflow/tensorflow/pull/29815). Can you please confirm so that we can close this issue? Thanks!
