### ISSUE TITLE
No module named tensorFlow when trying to import it through Neptune

### ISSUE THREAD

**Issue by Salinatorimperator** [tensorflow/tensorflow#18985]
### System information
- I am following the instructions found [here](https://blog.deepsense.ai/region-of-interest-pooling-in-tensorflow-example) in order to create a roi pooling using Neptune and tensorflow:
-  Linux Ubuntu 16.04
- **TensorFlow installed from** binary, using virtual environment
- **TensorFlow version (use command below)**:1.7
- **Python version**: 3.5.2
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: CUDA
- **GPU model and memory**: working with CPU
- **Exact command to reproduce**: 
```neptune run             --parameter im_folder:$PWD/../data/images             --parameter roidb:$PWD/../data/roidb             --parameter pretrained_path:$PWD/../data/vgg16-20160129.tfmodel```

### Describe the problem

When trying to run the previous command, I get the `ImportError: No module named tensorflow` error while the environment is activated. If I try to import it with a  normal python command it works perfectly.

### Source code / logs
```
(tensorflow3) ignacio@ignacio-Swift-SF314-52:~/Escritorio/nacho/AVIVA/roi-pooling/code$ neptune run             --parameter im_folder:$PWD/../data/images             --parameter roidb:$PWD/../data/roidb             --parameter pretrained_path:$PWD/../data/vgg16-20160129.tfmodel
>
> Experiment enqueued, id: SAN-43
>
> To browse the experiment, follow:
> https://app.neptune.ml/dashboard/experiment/d28dc701-8477-4dee-9281-def81feddc8f?getStartedState=folded
>

Calculated experiment snapshot size: 44.82 kB   
Sending sources to server: 100%|█████████████████████████████████████████████████████████| 44.8k/44.8k [00:00<00:00, 170kB/s]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/deepsense/neptune/job_wrapper.py", line 107, in <module>
    execute()
  File "/usr/local/lib/python2.7/dist-packages/deepsense/neptune/job_wrapper.py", line 103, in execute
    execfile(job_filepath, job_globals)
  File "main.py", line 4, in <module>
    from trainer import Trainer
  File "trainer.py", line 8, in <module>
    import tensorflow as tf
ImportError: No module named tensorflow
Calculated experiment snapshot size: 0 Bytes   
Process exited with return code 1.
```

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution

**Comment by Salinatorimperator** [comment]
Hi, I have updated the issue. Thanks!

**Comment by Salinatorimperator** [comment]
Any hints? I tried also with the native pip installation but I get the same output

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatatodd: It has been 22 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatatodd: It has been 36 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatatodd: It has been 66 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatatodd: It has been 81 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatatodd: It has been 96 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.
