### ISSUE TITLE
TensorFlow Error : java.lang.UnsatisfiedLinkError: Cannot find TensorFlow native library for OS: windows

### ISSUE THREAD

**Issue by OrionWambert** [tensorflow/tensorflow#18982]
Hello everyone I have this error when I compile my project tensorflow on netbeans

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: Cannot find TensorFlow native library for OS: windows, architecture: x86. See https://github.com/tensorflow/tensorflow/tree/master/tensorflow/java/README.md for possible solutions (such as building the library from source). Additional information on attempts to find the native library can be obtained by adding org.tensorflow.NativeLibrary.DEBUG=1 to the system properties of the JVM.
 at org.tensorflow.NativeLibrary.load(NativeLibrary.java:77)
 at org.tensorflow.TensorFlow.init(TensorFlow.java:66) at org.tensorflow.TensorFlow.(TensorFlow.java:70)
 at org.tensorflow.Graph.(Graph.java:258) at HelloTF.main(HelloTF.java:8)
 C:\Users\HP Notebook\AppData\Local\NetBeans\Cache\8.2\executor-enter codeheresnippets\run.xml:53: Java returned: 1 BUILD FAILED (total time: 0 seconds)
```

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by asimshankar** [comment]
As suggested with the error message, could you try after setting `-Dorg.tensorflow.NativeLibrary.DEBUG=1` in the JVM? That will provide additional information about what's missing.

Regardless, do fill out the issue template including ideally a [minimal, complete, verifiable](https://stackoverflow.com/help/mcve) set of steps to reproduce.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by OrionWambert** [comment]
Unfortunately I still have not been able to fix the problem, so I will try to test with another work environment to see what will happen

**Comment by tensorflowbutler** [comment]
Nagging Assignee @skye: It has been 16 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by asimshankar** [comment]
@OrionWambert : please update this issue with the results of https://github.com/tensorflow/tensorflow/issues/18982#issuecomment-385728771 when you get a chance.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
It has been 29 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
We are closing this issue for now due to lack of activity. Please comment if this is still an issue for you. Thanks!

**Comment by kishorecs** [comment]
This is still as issue..

Exception in thread "main" java.lang.UnsatisfiedLinkError: Cannot find TensorFlow native library for OS: linux, architecture: x86_64. See https://github.com/tensorflow/tensorflow/tree/master/tensorflow/java/README.md for possible solutions (such as building the library from source). Additional information on attempts to find the native library can be obtained by adding org.tensorflow.NativeLibrary.DEBUG=1 to the system properties of the JVM.
    at org.tensorflow.NativeLibrary.load(NativeLibrary.java:77)
    at org.tensorflow.TensorFlow.init(TensorFlow.java:66)
    at org.tensorflow.TensorFlow.<clinit>(TensorFlow.java:70)
    at org.tensorflow.Graph.<clinit>(Graph.java:361)
    at org.tf.sample.hellotensorflow.HelloTensorFlow.main(HelloTensorFlow.java:10)

I am trying to run sample code from tensorflow.org

**Comment by asimshankar** [comment]
@kishorecs : You might want to outline the exact set of steps to reproduce the problem as suggested in https://github.com/tensorflow/tensorflow/issues/18982#issuecomment-385728771

**Comment by BRkumara0** [comment]
Exception in thread "main" java.lang.UnsatisfiedLinkError: Cannot find TensorFlow native library for OS: windows, architecture: x86_64. See https://github.com/tensorflow/tensorflow/tree/master/tensorflow/java/README.md for possible solutions (such as building the library from source). Additional information on attempts to find the native library can be obtained by adding org.tensorflow.NativeLibrary.DEBUG=1 to the system properties of the JVM.
	at org.tensorflow.NativeLibrary.load(NativeLibrary.java:77)	at org.tensorflow.NativeLibrary.load(NativeLibrary.java:77)
	at org.tensorflow.TensorFlow.init(TensorFlow.java:66)
	at org.tensorflow.TensorFlow.<clinit>(TensorFlow.java:70)
	at org.tensorflow.Graph.<clinit>(Graph.java:479)
	at forecast.HelloTensorFlow.main(HelloTensorFlow.java:19)
Java Result: 1

**Comment by beamaster** [comment]
> Exception in thread "main" java.lang.UnsatisfiedLinkError: Cannot find TensorFlow native library for OS: windows, architecture: x86_64. See https://github.com/tensorflow/tensorflow/tree/master/tensorflow/java/README.md for possible solutions (such as building the library from source). Additional information on attempts to find the native library can be obtained by adding org.tensorflow.NativeLibrary.DEBUG=1 to the system properties of the JVM.
> at org.tensorflow.NativeLibrary.load(NativeLibrary.java:77) at org.tensorflow.NativeLibrary.load(NativeLibrary.java:77)
> at org.tensorflow.TensorFlow.init(TensorFlow.java:66)
> at org.tensorflow.TensorFlow.(TensorFlow.java:70)
> at org.tensorflow.Graph.(Graph.java:479)
> at forecast.HelloTensorFlow.main(HelloTensorFlow.java:19)
> Java Result: 1

Unfortunately, I still meet the problem too. It's sad.

**Comment by dkkplk** [comment]
When you have tensor flow dependency in your pom.xml file as below

<dependencies>
<dependency>
  <groupId>org.tensorflow</groupId>
  <artifactId>tensorflow</artifactId>
  <version>1.14.0</version>
</dependency>
It will download required 3 libraries tensorflow-1.14.0.jar libtensorflow-1.14.0.jar libtensorflow_jni-1.14.0.jar

So you have to manually extract the 3rd jar(libtensorflow_jni) and get your OS compatible file like for windows you have to copy the tensorflow_jni.dll file and paste in your project root directory that will solve your problem.

**Comment by Gamer069** [comment]
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: Cannot find TensorFlow native library for OS: darwin, architecture: x86_64. See https://github.com/tensorflow/tensorflow/tree/master/tensorflow/java/README.md for possible solutions (such as building the library from source). Additional information on attempts to find the native library can be obtained by adding org.tensorflow.NativeLibrary.DEBUG=1 to the system properties of the JVM.
	at org.tensorflow.NativeLibrary.load(NativeLibrary.java:77)
	at org.tensorflow.TensorFlow.init(TensorFlow.java:67)
	at org.tensorflow.TensorFlow.<clinit>(TensorFlow.java:82)
	at org.tensorflow.Graph.<clinit>(Graph.java:479)
	at com.simiacryptus.text.gpt2.GPT2Model.<init>(GPT2Model.java:120)
	at com.simiacryptus.text.gpt2.GPT2Model.<init>(GPT2Model.java:108)
	at com.simiacryptus.text.gpt2.GPT2Util.getModel_345M(GPT2Util.java:182)
	at com.simiacryptus.text.gpt2.GPT2Util.getModel_345M(GPT2Util.java:170)
	at com.simiacryptus.text.gpt2.GPT2Util.getModel_345M(GPT2Util.java:101)
	at com.simiacryptus.text.gpt2.GPT2Util.get345M(GPT2Util.java:61)
	at com.simiacryptus.text.gpt2.GPT2Util.<clinit>(GPT2Util.java:52)
	at Main.main(Main.java:7)
```
i have the same problem, it's very sad
