### ISSUE TITLE
[r1.7][TensorRT] Will it be able to use TRT to optimized the GraphDef that gained from a TF saved_model?

### ISSUE THREAD

**Issue by oscarriddle** [tensorflow/tensorflow#18994]
------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Red Hat 4.8.5-16, Linux version 3.10.0-693.5.2.el7.x86_64
- **TensorFlow installed from (source or binary)**: pip (python 2.7)
- **TensorFlow version (use command below)**: tensorflow-gpu==1.7.0
- **Python version**:  python 2.7
- **Bazel version (if compiling from source)**: NA
- **GCC/Compiler version (if compiling from source)**: gcc 5.3
- **CUDA/cuDNN version**: CUDA9.0, cuDNN7.0.5
- **GPU model and memory**: Tesla P4, 8GB
- **Exact command to reproduce**: NA

### Describe the problem
I tried to load the saved_model and optimize it by integrated TensorRT to do the prediction. The TensorRT will optimize the GraphDef and eventually get about 50% throughput speed-up. I verified this on frozen model, but when trying to apply that on the saved_model, I encountered an error during the graph conversion like below:
```
2018-05-01 11:36:30.553143: I tensorflow/core/grappler/devices.cc:51] Number of eligible GPUs (core count >= 8): 1
2018-05-01 11:36:41.562979: W tensorflow/contrib/tensorrt/convert/convert_nodes.cc:2524] Type conversion failed for InceptionV3/Conv2d_2a_3x3/BatchNorm/moving_mean
2018-05-01 11:36:41.563063: W tensorflow/contrib/tensorrt/convert/convert_graph.cc:412] subgraph conversion error for subgraph_index:0 due to: "Invalid argument: Unsupported data type float_ref" SKIPPING......( 803 nodes)
Tensor("input:0", shape=(?, 299, 299, 3), dtype=float32)
```
I printed out the GraphDef but not found key name "float_ref", so not quite sure how to address this issue. 

### Source code / logs
Some essential part of my script:
```
    with tf.Graph().as_default():                                                                                                            
        with tf.Session(graph=tf.Graph()) as sess:
            if args.image:
                import numpy as np
                func = TestKit.preprocess_func['tensorflow'][args.network]
                img = func(args.image)
                img = np.expand_dims(img, axis = 0)                                                                  
            inp, out = importer.import_graph_def(graph_def=sess.graph_def, return_elements=['input','InceptionV3/Logits/SpatialSqueeze'])
            t0 = time.time()                                                                                                                                   
            print sess.graph_def
            f32_graph = trt.create_inference_graph(    #<<<<< Breakpoint
                input_graph_def=sess.graph_def,
                #outputs=[logits],                                                                                                                                              
                outputs=['InceptionV3/Logits/SpatialSqueeze'],
                #  max_batch_size = int(input_dims[0]),                                                                                                                         
                max_batch_size = 1,
                max_workspace_size_bytes=1 << 20,
                precision_mode="FP32",  # TRT Engine precision "FP32","FP16" or "INT8"                                                                                          
                minimum_segment_size=2  # minimum number of nodes in an engine      
            )                                                                                                                                         
        features_tensor = sess.graph.get_tensor_by_name("InceptionV3/Logits/SpatialSqueeze:0")
        data_input = sess.graph.get_tensor_by_name("input:0")
        print data_input
    init_g = tf.global_variables_initializer()
    init_l = tf.local_variables_initializer()
    g = ops.Graph()
```

Any idea will be welcome.
Thanks,

**Comment by samikama** [comment]
@oscarriddle TRT is an inference engine. So you need to try to convert frozen models and it won't work on training graphs. The graph you are trying to convert is probably not frozen. Can you ensure that you ran freeze_graph.py on the model you want to import?

Thanks,
Sami

**Comment by oscarriddle** [comment]
Hi @samikama ,

Thanks for your replay.

I'm actually trying to speed-up the inference, so nothing to do with training for now. My idea is to use the TF 1.7 with TRT GraphDef optimization API to optimize a trained model, and then use the TF to do the prediction on the optimized GraphDef. The TRT UFF model conversion or TRT inference engine are not used.

I've successfully done this procedure on the frozen model (#18548). But since the online serving is using the saved_model, I tried to load a saved_model and extract its graph_def, and use TRT to optimize it. But Error occurs here.

Thanks,

**Comment by samikama** [comment]
@oscarriddle,

Unfortunately, saved_model is not frozen. freeze_graph.py convert variables to constants and removes training nodes that are not used in inference as well as may apply a couple of optimizations. graph_def from saved model still contains training nodes and variables. If you want to call TRT optimization on saved_model, graphdef you need to first freeze it. You can call freeze_graph() in your script. Check freeze_graph.py.

Cheers,

**Comment by samikama** [comment]
@oscarriddle , unfortunately this is a nuisance on our part and we will take care of it when TRT4.0 comes out. It is happening because of memory allocation incompatibility between TRT3 and TF. In order to workaround it you need to tell TF to leave some memory for TRT. You can do this by passing GPUOptions to session configuration like below. But since TF allocation policy defines the amount of allocated memory at first call, you have to make sure that you set the memory fraction at the first session call. I would suggest you to create a dummy session without any graph or anything right after you import tensorflow, before doing anything else. Of course, you have to tune the fraction to accommodate your model and memory size you are passing to TensorRT during the conversion call.

```python
  sess = tf.Session(config=tf.ConfigProto(gpu_options=tf.GPUOptions(per_process_gpu_memory_fraction=0.50)))
```
Let me know if this helps.
Cheers,

**Comment by oscarriddle** [comment]
Hi @samikama 

Thanks for your reply, it helps me understand the behind mechanism.
I added this line to partition the available memory in creating a session, and now previous error disappeared, but a new one popped that:
`tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./fs2/variables/variables`

I noticed the saved_model, which is generated based on a optimized frozen model, is in a different format from normal saved_models. The new saved_model has below file list:
```
-rw-r--r-- 1 web_server users 85M 5月   2 14:54 saved_model.pb
drwxr-xr-x 2 web_server users   6 5月   2 14:54 variables
```
And the folder "varibales" is actually empty. This is different from normal saved_models that generated from the original model:
```
-rw-r--r-- 1 web_server users      1.8M 4月  16 17:09 saved_model.pb
drwxr-xr-x 2 web_server users        66 4月  17 17:08 variables
```
And in ./variables/*
```
-rw-r--r-- 1 web_server users 95M 4月  16 18:57 variables.data-00000-of-00001
-rw-r--r-- 1 web_server users 17K 4月  16 18:57 variables.index
```

I'm not quite familiar with the saved_model mechanism, but I suggests this difference comes from the source model is a TRT optimized frozen model, but not the original one.

However, seems that saved_model loader is unable to load this "saved_model" in this format. 

Let me share the log:
```
2018-05-03 11:10:03.502930: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-05-03 11:10:04.112785: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-05-03 11:10:04.113087: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1344] Found device 0 with properties: 
name: Tesla P4 major: 6 minor: 1 memoryClockRate(GHz): 1.1135
pciBusID: 0000:00:08.0
totalMemory: 7.43GiB freeMemory: 7.31GiB
2018-05-03 11:10:04.113124: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1423] Adding visible gpu devices: 0
2018-05-03 11:10:04.566803: I tensorflow/core/common_runtime/gpu/gpu_device.cc:911] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-05-03 11:10:04.566852: I tensorflow/core/common_runtime/gpu/gpu_device.cc:917]      0 
2018-05-03 11:10:04.566861: I tensorflow/core/common_runtime/gpu/gpu_device.cc:930] 0:   N 
2018-05-03 11:10:04.567079: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3805 MB memory) -> physical GPU (device: 0, name: Tesla P4, pci bus id: 0000:00:08.0, compute capability: 6.1)
2018-05-03 11:10:06.909755: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:170 : Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./fs2/variables/variables
Traceback (most recent call last):
  File "trt_run_saved.py", line 115, in <module>
    _main()
  File "trt_run_saved.py", line 103, in _main
    tf.saved_model.loader.load(sess, ['serve'], './fs2')
  File "/home/web_server/dlpy72/dlpy/lib/python2.7/site-packages/tensorflow/python/saved_model/loader_impl.py", line 229, in load
    saver.restore(sess, variables_path)
  File "/home/web_server/dlpy72/dlpy/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1775, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/web_server/dlpy72/dlpy/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 905, in run
    run_metadata_ptr)
  File "/home/web_server/dlpy72/dlpy/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1140, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/web_server/dlpy72/dlpy/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    run_metadata)
  File "/home/web_server/dlpy72/dlpy/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./fs2/variables/variables
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]
	 [[Node: save/RestoreV2/_301 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_306_save/RestoreV2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

Caused by op u'save/RestoreV2', defined at:
  File "trt_run_saved.py", line 115, in <module>
    _main()
  File "trt_run_saved.py", line 103, in _main
    tf.saved_model.loader.load(sess, ['serve'], './fs2')
  File "/home/web_server/dlpy72/dlpy/lib/python2.7/site-packages/tensorflow/python/saved_model/loader_impl.py", line 219, in load
    saver = tf_saver.import_meta_graph(meta_graph_def_to_load, **saver_kwargs)
  File "/home/web_server/dlpy72/dlpy/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1933, in import_meta_graph
    return Saver()
  File "/home/web_server/dlpy72/dlpy/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1311, in __init__
    self.build()
  File "/home/web_server/dlpy72/dlpy/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1320, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/web_server/dlpy72/dlpy/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1357, in _build
    build_save=build_save, build_restore=build_restore)
  File "/home/web_server/dlpy72/dlpy/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 809, in _build_internal
    restore_sequentially, reshape)
  File "/home/web_server/dlpy72/dlpy/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 448, in _AddRestoreOps
    restore_sequentially)
  File "/home/web_server/dlpy72/dlpy/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 860, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/home/web_server/dlpy72/dlpy/lib/python2.7/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1458, in restore_v2
    shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)
  File "/home/web_server/dlpy72/dlpy/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/web_server/dlpy72/dlpy/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3290, in create_op
    op_def=op_def)
  File "/home/web_server/dlpy72/dlpy/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1654, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

NotFoundError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./fs2/variables/variables
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]
	 [[Node: save/RestoreV2/_301 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_306_save/RestoreV2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
```

Thanks,

**Comment by samikama** [comment]
@oscarridle, when you freeze the graph you remove the Variable nodes from the graph so you can not save and restore variables with saved model at least not without changing graph and saver. I am not an expert but AFAIK saver can not save frozen graphs. If you want to serialize the converted model you need to save it as graph_def. Please take a look at the tensorrt example in model zoo or the https://devblogs.nvidia.com/tensorrt-integration-speeds-tensorflow-inference/ on how to  serialize converted graph.

**Comment by oscarriddle** [comment]
@samikama 
Thanks for your reply. That makes sense, so I think it's time to make a conclusion. 

1. TRT optimization engine can only support the graph def that gained from frozen model. Saved_model cannot be directly load and optimized. 
2. The procedure restore a frozen model, then TRT optimize it, and then save it to saved_model is not feasible.
3. Then I tried to restore previously trained frozen model, then TRT optimize it, and then export the optimized graph to a new frozen model. And the new one can be successfully restored and executed. This procedure is OK, though my online Tensorflow serving environment need to be recompiled from utilizing saved_model to frozen_model.

Thanks for your help and patience.
Cheers~

**Comment by caibobit** [comment]
@oscarriddle how to export the optimized graph using TRT to a new forzen model ? From my point of view ,the optimized graph is already a frozen graph .

**Comment by oscarriddle** [comment]
@caibobit yep, it is already a frozen graph so you can export it to file in regular way. The nodes of the new frozen model will be replaced by TRTEngineOp.

**Comment by caibobit** [comment]
@oscarriddle i tried your solution，and use the mnist to test ,but the tensorflow_serving can't recognize the forzen graph ,and the error occurs, the following  is the logs:
```shell
2018-07-05 18:57:34.846301: I tensorflow_serving/model_servers/main.cc:153] Building single TensorFlow model file config:  model_name: mnist model_base_path: /home/caibo/tmp/mnist_model
2018-07-05 18:57:34.846479: I tensorflow_serving/model_servers/server_core.cc:459] Adding/updating models.
2018-07-05 18:57:34.846504: I tensorflow_serving/model_servers/server_core.cc:514]  (Re-)adding model: mnist
2018-07-05 18:57:34.946753: I tensorflow_serving/core/basic_manager.cc:716] Successfully reserved resources to load servable {name: mnist version: 5}
2018-07-05 18:57:34.946784: I tensorflow_serving/core/loader_harness.cc:66] Approving load for servable version {name: mnist version: 5}
2018-07-05 18:57:34.946799: I tensorflow_serving/core/loader_harness.cc:74] Loading servable version {name: mnist version: 5}
2018-07-05 18:57:34.946819: I external/org_tensorflow/tensorflow/contrib/session_bundle/bundle_shim.cc:360] Attempting to load native SavedModelBundle in bundle-shim from: /home/caibo/tmp/mnist_model/5
2018-07-05 18:57:34.946837: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:242] Loading SavedModel with tags: { serve }; from: /home/caibo/tmp/mnist_model/5
2018-07-05 18:57:34.946953: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:291] SavedModel load for tags { serve }; Status: fail. Took 113 microseconds.
2018-07-05 18:57:34.946973: E tensorflow_serving/util/retrier.cc:37] Loading servable: {name: mnist version: 5} failed: Not found: Could not find meta graph def matching supplied tags: { serve }. To inspect available tag-sets in the SavedModel, please use the SavedModel CLI: `saved_model_cli`
```
----------------------------------------------------------------
```shell
caibo@ubuntu:~/PycharmProjects/untitled1/my/output$ ls
frozen_graph.pb  log.txt  trt_mnist_fp16.pb  trt_mnist_fp32.pb
```
and also i convert the trt_graph to the saved_model.pb and put the into the model_base_path ,still the same error ,  that is " could not find meta graph def matching supplied tags"

i wonder if  the way i bazel build the tensorflow serving is wrong , or something else.

**Comment by oscarriddle** [comment]
@caibobit 
First of all, I think you need to clarify the difference between frozen model and the saved_model. They are almost the same but saved_model provided signatureDef that you need to take care.

When you export a saved model, it requires to set a tag for signaturedef, and later when you load it, you have to specify the tag. From your log, I think you can check the tag of your saved model, by using saved_model_cli:
```
2018-07-05 18:57:34.946953: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:291] SavedModel load for tags { serve }; Status: fail. Took 113 microseconds.
2018-07-05 18:57:34.946973: E tensorflow_serving/util/retrier.cc:37] Loading servable: {name: mnist version: 5} failed: Not found: Could not find meta graph def matching supplied tags: { serve }. To inspect available tag-sets in the SavedModel, please use the SavedModel CLI: `saved_model_cli`
```
For the second, the c++ tensorflow shall already support loading serialized model, you can check this: [https://medium.com/jim-fleming/loading-a-tensorflow-graph-with-the-c-api-4caaff88463f](url)

The frozen model can be converted to saved model and vice versa, because they are both serialized ones.

Thanks,

**Comment by caibobit** [comment]
@oscarriddle 
 i use the command bazel build  --config=cuda --action_env TENSORRT_BIN_PATH="/home/caibo/TensorRT-3.0.4"  -c opt tensorflow_serving/...
as you said in [this issue](https://github.com/tensorflow/serving/issues/925)
but the tensorflow serving still can't use the optimize TRT graph .
Can you add my WeChat(c842426077) for further communication?  
thanks

**Comment by caibobit** [comment]
@oscarriddle 
I referenced the build process in the official [dockerfile](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/tools/docker/Dockerfile.devel-gpu) and successfully compiled tf_serving, tensorrt, and cuda together. The original tf_serving is inferred on the CPU. In this way, it can be inferred on the GPU. Whether multi-machine multi-card can be inferred is still under study.
Thanks

**Comment by qiaohaijun** [comment]
thank

**Comment by elvys-zhang** [comment]
@oscarriddle Hi. I just wonder how did your tensorflow serving load frozen model ? It seems that TensorRT could only optimize frozen model to frozen model. Did you recompile your serving to support tensorRT or do something to transfer frozen model to saved model?
Thanks.

**Comment by rankeey** [comment]
@elvys-zhang 
Have you known how to export a savedModel for tf-serving?
I have the same question.

**Comment by YUHAO19910716** [comment]
> @oscarriddle，遗憾的是这对我们来说是一件麻烦事，我们将在TRT4.0发布时对其进行处理。这是由于TRT3和TF之间的内存分配不兼容而发生的。为了解决它，你需要告诉TF为TRT留下一些内存。您可以通过将GPUOptions传递给会话配置来完成此操作，如下所示。但由于TF分配策略定义了第一次调用时分配的内存量，因此必须确保在第一次会话调用时设置内存分数。在做其他任何事情之前，我建议你在导入tensorflow后立即创建一个没有任何图形或虚拟会话的虚拟会话。当然，您必须调整分数以适应您在转换调用期间传递给TensorRT的模型和内存大小。
> 
> ```python
>   sess = tf.Session（config = tf.ConfigProto（gpu_options = tf.GPUOptions（per_process_gpu_memory_fraction = 0.50）））
> ```
> 
> 如果这有帮助，请告诉我。


Use the method you provide,I succeeded in solving it.
thankyou,verymuch!!
