### ISSUE TITLE
Tensorflow r1.8  ImportError: dlopen: cannot load any more object with static TLS

### ISSUE THREAD

**Issue by crawforc3** [tensorflow/tensorflow#19010]
Have I written custom code: No
OS Platform and Distribution: Debian 8.10
TensorFlow installed from: Source
TensorFlow version: r1.8
Bazel version: 0.13.0
CUDA/cuDNN version: n/a
GPU model and memory: n/a
Exact command to reproduce:

Importing Tensorflow r1.8 **after** some libraries (specifically cv2) results in: 
`ImportError: dlopen: cannot load any more object with static TLS`

A temporary fix seems to be to import Tensorflow before any other libraries. 
Has this shown up before? Any other information I can provide?

https://github.com/Kaggle/docker-python/issues/206
https://www.kaggle.com/kmader/library-overload

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/opt/conda/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py in <module>()
     57 
---> 58   from tensorflow.python.pywrap_tensorflow_internal import *
     59   from tensorflow.python.pywrap_tensorflow_internal import __version__

/opt/conda/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py in <module>()
     27             return _mod
---> 28     _pywrap_tensorflow_internal = swig_import_helper()
     29     del swig_import_helper

/opt/conda/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py in swig_import_helper()
     23             try:
---> 24                 _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
     25             finally:

/opt/conda/lib/python3.6/imp.py in load_module(name, file, filename, details)
    242         else:
--> 243             return load_dynamic(name, filename, file)
    244     elif type_ == PKG_DIRECTORY:

/opt/conda/lib/python3.6/imp.py in load_dynamic(name, path, file)
    342             name=name, loader=loader, origin=path)
--> 343         return _load(spec)
    344 

ImportError: dlopen: cannot load any more object with static TLS

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-2-41389fad42b5> in <module>()
----> 1 import tensorflow as tf

/opt/conda/lib/python3.6/site-packages/tensorflow/__init__.py in <module>()
     22 
     23 # pylint: disable=g-bad-import-order
---> 24 from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
     25 # pylint: disable=wildcard-import
     26 from tensorflow.tools.api.generator.api import *  # pylint: disable=redefined-builtin

/opt/conda/lib/python3.6/site-packages/tensorflow/python/__init__.py in <module>()
     47 import numpy as np
     48 
---> 49 from tensorflow.python import pywrap_tensorflow
     50 
     51 # Protocol buffers

/opt/conda/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py in <module>()
     72 for some common reasons and solutions.  Include the entire stack trace
     73 above this error message when asking for help.""" % traceback.format_exc()
---> 74   raise ImportError(msg)
     75 
     76 # pylint: enable=wildcard-import,g-import-not-at-top,unused-import,line-too-long

ImportError: Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/opt/conda/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/opt/conda/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: dlopen: cannot load any more object with static TLS


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by crawforc3** [comment]
Added information to the original post

**Comment by yaroslavvb** [comment]
I've seen this problem in Ubuntu 14.04 which was solved by upgrading to 16.04 which raises static TLS limit. Basically each dynamically loaded .so can request a number of static TLS slots, and kernel sets limit on total number. I don't have explanation why changing import order can get around the TLS restriction

**Comment by lakshmisivareddy** [comment]
from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\abc\Anaconda3\envs\MYML\lib\site-packages\tensorflow\python\__init__.py", line 47, in <module>
    import numpy as np
  File "C:\Users\abc\Anaconda3\envs\MYML\lib\site-packages\numpy\__init__.py", line 158, in <module>
    from . import add_newdocs
  File "C:\Users\abc\Anaconda3\envs\MYML\lib\site-packages\numpy\add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "C:\Users\abc\Anaconda3\envs\MYML\lib\site-packages\numpy\lib\__init__.py", line 8, in <module>
    from .type_check import *
  File "C:\Users\abc\Anaconda3\envs\MYML\lib\site-packages\numpy\lib\type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "C:\Users\abc\Anaconda3\envs\MYML\lib\site-packages\numpy\core\__init__.py", line 26, in <module>
    raise ImportError(msg)

**Comment by tensorflowbutler** [comment]
Nagging Assignee @asimshankar: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @asimshankar: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @asimshankar: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @asimshankar: It has been 60 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @asimshankar: It has been 74 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @asimshankar: It has been 89 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by mzakariaCERN** [comment]
Same issue happened to me today with a fresh install of Keras. order of importing didn't make any difference. 
The fix was updating it
```
conda upgrade -c conda-forge keras 
```

**Comment by mihaimaruseac** [comment]
Please try to use 1.15, 2.0, 2.1 or 2.2. 1.8 is not supported.

In fact, I think we should close this issue as no longer supported and open a new one if there are problems in the supported versions listed at the beginning of this comment

**Comment by jvishnuvardhan** [comment]
Closing this issue as `TF1.8` is no longer support. 

Feel free to open a new issue if this issue persists with recent TF versions. Thanks!
