### ISSUE TITLE
IOError: [Errno 21] Is a directory: '/tmp/speech_dataset/'

### ISSUE THREAD

**Issue by UrimLimani** [tensorflow/tensorflow#19109]
I'm following the speech recognition tutorial from TensorFlow, and when I'm running the following command, which downloads the dataset provided by TensorFlow, it runs perfectly.

`python tensorflow/examples/speech_commands/train.py`

However, when I'm changing the defaults, so that it points to my dataset, it throws the following error:

```
Traceback (most recent call last):
  File "/home/users2/lmn/.local/lib/python2.7/site-packages/tensorflow/examples/speech_commands/train.py", line 428, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/home/users2/lmn/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "/home/users2/lmn/.local/lib/python2.7/site-packages/tensorflow/examples/speech_commands/train.py", line 106, in main
    FLAGS.testing_percentage, model_settings)
  File "/home/users2/lmn/.local/lib/python2.7/site-packages/tensorflow/examples/speech_commands/input_data.py", line 158, in __init__
    self.maybe_download_and_extract_dataset(data_url, data_dir)
  File "/home/users2/lmn/.local/lib/python2.7/site-packages/tensorflow/examples/speech_commands/input_data.py", line 204, in maybe_download_and_extract_dataset
    tarfile.open(filepath, 'r:gz').extractall(dest_directory)
  File "/usr/lib64/python2.7/tarfile.py", line 1693, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/usr/lib64/python2.7/tarfile.py", line 1740, in gzopen
    fileobj = gzip.GzipFile(name, mode, compresslevel, fileobj)
  File "/usr/lib64/python2.7/gzip.py", line 94, in __init__
    fileobj = self.myfileobj = __builtin__.open(filename, mode or 'rb')
IOError: [Errno 21] Is a directory: '/tmp/speech_dataset/' 

The command I'm running is:
`python tensorflow/examples/speech_commands/train.py --data_url=path/to/data/ --sample_rate=20000 --wanted_words=one,two,three,four,five,six,seven,eight,nine`
```

Now, the error says that '/tmp/speech_dataset/' is a directory, but it is expecting a file, I guess. When I looked at `train.py` file, found the following code:

```
parser.add_argument(
      '--data_dir',
      type=str,
      default='/tmp/speech_dataset/',
      help="""\
      Where to download the speech training data to.
      """)

The `--data-dir `argument defines where the files from the downloaded dataset should be stored. However, I'm not changing that argument at all, nor does the code need to save any data, since I already have the data on my computer, where I define them at `--data-url a`rgument. It seems to me that this is a bug in the code.

Does anyone has experience with speech recognition on TensorFlow and know where the problem might be?
```

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by angersson** [comment]
Did you try using `--data_dir` instead of `--data_url`? The docs in https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/speech_commands/train.py show use of the `--data_dir` flag when using your own local data.

The stack trace reveals that Python is trying to use gzip to unpack the directory you specified in `--data_url`, because it wants to download and unarchive it.
