### ISSUE TITLE
Tensorflow AttributeError: module 'bottleneck' has no attribute '__version__'

### ISSUE THREAD

**Issue by gr8Adakron** [tensorflow/tensorflow#19173]
**Tensorflow version==1.7**
**Tensorhub version==1.0**

**I am trying to learn tensorflow serving using small tutorial on [Medium blog](https://medium.com/@utsumukiMutsuki/using-inception-v3-from-tensorflow-hub-for-transfer-learning-a931ff884526)  as soon as I am running the basic program its returning this error.**

  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/afzal/.virtualenvs/tensorflow_python36/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *  # pylint: disable=redefined-builtin
  File "/home/afzal/.virtualenvs/tensorflow_python36/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 82, in <module>
    from tensorflow.python.estimator import estimator_lib as estimator
  File "/home/afzal/.virtualenvs/tensorflow_python36/lib/python3.6/site-packages/tensorflow/python/estimator/estimator_lib.py", line 37, in <module>
    from tensorflow.python.estimator.inputs import inputs
  File "/home/afzal/.virtualenvs/tensorflow_python36/lib/python3.6/site-packages/tensorflow/python/estimator/inputs/inputs.py", line 22, in <module>
    from tensorflow.python.estimator.inputs.numpy_io import numpy_input_fn
  File "/home/afzal/.virtualenvs/tensorflow_python36/lib/python3.6/site-packages/tensorflow/python/estimator/inputs/numpy_io.py", line 26, in <module>
    from tensorflow.python.estimator.inputs.queues import feeding_functions
  File "/home/afzal/.virtualenvs/tensorflow_python36/lib/python3.6/site-packages/tensorflow/python/estimator/inputs/queues/feeding_functions.py", line 40, in <module>
    import pandas as pd
  File "/home/afzal/.virtualenvs/tensorflow_python36/lib/python3.6/site-packages/pandas/__init__.py", line 42, in <module>
    from pandas.core.api import *
  File "/home/afzal/.virtualenvs/tensorflow_python36/lib/python3.6/site-packages/pandas/core/api.py", line 9, in <module>
    from pandas.core.categorical import Categorical
  File "/home/afzal/.virtualenvs/tensorflow_python36/lib/python3.6/site-packages/pandas/core/categorical.py", line 36, in <module>
    from pandas.core.base import (PandasObject,
  File "/home/afzal/.virtualenvs/tensorflow_python36/lib/python3.6/site-packages/pandas/core/base.py", line 20, in <module>
    import pandas.core.nanops as nanops
  File "/home/afzal/.virtualenvs/tensorflow_python36/lib/python3.6/site-packages/pandas/core/nanops.py", line 30, in <module>
    ver = bn.__version__
AttributeError: module 'bottleneck' has no attribute '__version__'

**Comment by saeed68gm** [comment]
+1

**Comment by skye** [comment]
I believe this an environment issue, not a TensorFlow issue.

**Comment by hari2255** [comment]
Any update , I am also getting same issue

**Comment by mmderakhshani** [comment]
I have got the same issue too, waiting for any update.

**Comment by hari2255** [comment]
Issue got solved by reinstalling bottleneck.

**Comment by fay011235** [comment]
do 'pip install bottleneck' is ok for me.

**Comment by schliffen** [comment]
I also solved this issue by re installing bottleneck in python3

**Comment by AjayKannan97** [comment]
I have the same problem using env-"jupyter". How do to I resolve it?
