### ISSUE TITLE
AttributeError: 'SsdAnchorGenerator' object has no attribute 'height_stride'

### ISSUE THREAD

**Issue by Tgmstriker** [tensorflow/tensorflow#19207]
### System information
- I am trying to use export_inference_graph.py within tensorflow/research/object_detection
- Windows 10
- Tensorflow installed from binary
- Tensorflow Version b'v1.8.0-0-g93bc2e2072' 1.8.0
- Python 3.6.4
### Describe the problem
I am trying to train a detector using a custom data set.  I have run through the training and produced the model.ckpt files (meta, index, etc).  The issue I'm running into is creating the frozen inference graph.  Running export_inference_graph.py always fails out with the error:

AttributeError: 'SsdAnchorGenerator' object has no attribute 'height_stride'

After some mild searching online, I didn't uncover any hits or paths to go down to address this.  What might I be missing?

### Source code / logs
tensorflow\research\object_detection> python export_inference_graph.py --input_type i
mage_tensor --pipeline_config_path training/ssd_mobilenet_v1_coco.config --trained_checkpoint_prefix training/model.ckpt
-89076 --output_directory inference_graph
C:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "export_inference_graph.py", line 147, in <module>
    tf.app.run()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 126, in run
    _sys.exit(main(argv))
  File "export_inference_graph.py", line 143, in main
    FLAGS.output_directory, input_shape)
  File "C:\ProgramData\Anaconda3\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\exporter.py", line 447, in export_inference_graph
    is_training=False)
  File "C:\ProgramData\Anaconda3\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\builders\model_builder.py", line 98, in build
    add_background_class)
  File "C:\ProgramData\Anaconda3\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\builders\model_builder.py", line 178, in _build_ssd_model
    ssd_config.anchor_generator)
  File "C:\ProgramData\Anaconda3\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\builders\anchor_generator_builder.py", line 59, in build
    if ssd_anchor_generator_config.height_stride:
AttributeError: 'SsdAnchorGenerator' object has no attribute 'height_stride'

### Edit 5/14/2018:
Have I written custom code: not for this instance.
OS Platform : Windows 10
Basel Version: NA
Cuda version l: NA
Gpu Model: NA
Command: tensorflow\research\object_detection> python export_inference_graph.py --input_type i
mage_tensor --pipeline_config_path training/ssd_mobilenet_v1_coco.config --trained_checkpoint_prefix training/model.ckpt
-89076 --output_directory inference_graph

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by Tgmstriker** [comment]
Checking in on rohan100jain.

**Comment by Tgmstriker** [comment]
Bumping @rohan100jain

**Comment by Tgmstriker** [comment]
Issue solved. It appears to be the mobilenet SSD V1 coco model doesn't have a height or width stride. Re training using another model proceeded with no issues.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @rohan100jain: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @rohan100jain: It has been 30 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.
