### ISSUE TITLE
unorderable types: str() < tuple() in /tensorflow/python/feature_column/feature_column.py

### ISSUE THREAD

**Issue by werowe** [tensorflow/tensorflow#19219]
Google Tensorflow forum guy asked me to open this issue:

### System information
- **Have I written custom code **:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Ubuntu 14.04 LTS
- **TensorFlow installed from (source or binary)**:
pip3 install tensorflow --upgrade
- **TensorFlow version (use command below)**:
TF 1.7.0.
- **Python version**: 
Python 3.4.3 
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.

run time error in python: unorderable types: str() < tuple() in /tensorflow/python/feature_column/feature_column.py

### Source code / logs
https://github.com/werowe/tripAdvisorNeuralNetworkTensorFlow/blob/master/tripadvisorNN.py
data:   https://raw.githubusercontent.com/werowe/tripAdvisorNeuralNetworkTensorFlow/master/tripAdvisorFL.csv

dictionary {'Nrhotelreviews': <tf.Tensor 'DecodeCSV:2' shape=() dtype=int32>, 'Casino': <tf.Tensor 'DecodeCSV:11' shape=() dtype=int32>, 'Travelertype': <tf.Tensor 'DecodeCSV:6' shape=() dtype=int32>, 'Helpfulvotes': <tf.Tensor 'DecodeCSV:3' shape=() dtype=int32>, 'Usercontinent': <tf.Tensor 'DecodeCSV:16' shape=() dtype=int32>, 'Tenniscourt': <tf.Tensor 'DecodeCSV:9' shape=() dtype=int32>, 'Usercountry': <tf.Tensor 'DecodeCSV:0' shape=() dtype=int32>, 'Reviewmonth': <tf.Tensor 'DecodeCSV:18' shape=() dtype=int32>, 'Hotelname': <tf.Tensor 'DecodeCSV:13' shape=() dtype=int32>, 'Nrrooms': <tf.Tensor 'DecodeCSV:15' shape=() dtype=int32>, 'Freeinternet': <tf.Tensor 'DecodeCSV:12' shape=() dtype=int32>, 'Nrreviews': <tf.Tensor 'DecodeCSV:1' shape=() dtype=int32>, 'Gym': <tf.Tensor 'DecodeCSV:8' shape=() dtype=int32>, 'Memberyears': <tf.Tensor 'DecodeCSV:17' shape=() dtype=int32>, 'Periodofstay': <tf.Tensor 'DecodeCSV:5' shape=() dtype=int32>, 'Pool': <tf.Tensor 'DecodeCSV:7' shape=() dtype=int32>, 'Reviewweekday': <tf.Tensor 'DecodeCSV:19' shape=() dtype=int32>, 'Spa': <tf.Tensor 'DecodeCSV:10' shape=() dtype=int32>, 'Hotelstars': <tf.Tensor 'DecodeCSV:14' shape=() dtype=int32>}  label =  Tensor("DecodeCSV:4", shape=(), dtype=int32)
INFO:tensorflow:Calling model_fn.
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/home/walker/tf3/lib/python3.4/site-packages/tensorflow/python/estimator/estimator.py", line 355, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/walker/tf3/lib/python3.4/site-packages/tensorflow/python/estimator/estimator.py", line 824, in _train_model
    features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
  File "/home/walker/tf3/lib/python3.4/site-packages/tensorflow/python/estimator/estimator.py", line 805, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/home/walker/tf3/lib/python3.4/site-packages/tensorflow/python/estimator/canned/dnn.py", line 354, in _model_fn
    config=config)
  File "/home/walker/tf3/lib/python3.4/site-packages/tensorflow/python/estimator/canned/dnn.py", line 184, in _dnn_model_fn
    logits = logit_fn(features=features, mode=mode)
  File "/home/walker/tf3/lib/python3.4/site-packages/tensorflow/python/estimator/canned/dnn.py", line 92, in dnn_logit_fn
    features=features, feature_columns=feature_columns)
  File "/home/walker/tf3/lib/python3.4/site-packages/tensorflow/python/feature_column/feature_column.py", line 274, in input_layer
    trainable, cols_to_vars)
  File "/home/walker/tf3/lib/python3.4/site-packages/tensorflow/python/feature_column/feature_column.py", line 192, in _internal_input_layer
    for column in sorted(feature_columns, key=lambda x: x.name):
TypeError: unorderable types: str() < tuple()

**Comment by ispirmustafa** [comment]
`key` argument must be a string. You have provide a tuple in some of your feature columns, such as:
`tf.feature_column.numeric_column(("Usercountry",47))`
