### ISSUE TITLE
Error when freeze the graph

### ISSUE THREAD

**Issue by xav12358** [tensorflow/tensorflow#19268]
Information:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary 1.5
- **Python version**: 3.5
- **CUDA/cuDNN version**: No

Hello,

I use a model, in my code I save the model with that command:
`                writer = tf.summary.FileWriter("/tmp/model4/MTCNN/", self.sess.graph)
                saver = tf.train.Saver() #saver load pretrain model
                save_path = tf.train.Saver().save(self.sess, "/tmp/model4/MTCNN/model.ckpt")`

It generates me these files:
```
/tmp/model4/MTCNN/checkpoint
/tmp/model4/MTCNN/events.out.tfevents.1526300275.xavier-Inspiron
/tmp/model4/MTCNN/model.ckpt.data-00000-of-00001
/tmp/model4/MTCNN/model.ckpt.index
/tmp/model4/MTCNN/model.ckpt.meta
```

I reload this saved model and graph with that code:

```
               self.sess = tf.Session()
                model_path = "/tmp/model4/MTCNN/model.ckpt"
                model_path_p = "/tmp/model4/MTCNN/"
                self.sess.run(tf.global_variables_initializer())
                new_saver = tf.train.import_meta_graph(model_path + '.meta')
                new_saver.restore(self.sess,tf.train.latest_checkpoint(model_path_p))
```

And this works properly. Now I want to freeze my model in pb file with that command:
`python3 ./tensorflow/python/tools/freeze_graph.py --input_checkpoint=/tmp/model4/MTCNN/model.ckpt.data-00000-of-00001 --input_meta_graph_def=/tmp/model4/MTCNN/model.ckpt.meta  --output_graph=frozen_graph.pb --output_node_names='pnet/conv4-2/BiasAdd'`

And I get that errors:

`2018-05-14 14:35:20.597234: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-05-14 14:35:20.598060: W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open /tmp/model4/FaceFeature/model.ckpt.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
Traceback (most recent call last):
  File "./tensorflow/python/tools/freeze_graph.py", line 360, in <module>
    app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "./tensorflow/python/tools/freeze_graph.py", line 254, in main
    FLAGS.saved_model_tags, FLAGS.checkpoint_version)
  File "./tensorflow/python/tools/freeze_graph.py", line 244, in freeze_graph
    saved_model_tags.split(","), checkpoint_version=checkpoint_version)
  File "./tensorflow/python/tools/freeze_graph.py", line 119, in freeze_graph_with_def_protos
    reader = pywrap_tensorflow.NewCheckpointReader(input_checkpoint)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 150, in NewCheckpointReader
    return CheckpointReader(compat.as_bytes(filepattern), status)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.DataLossError: Unable to open table file /tmp/model4/FaceFeature/model.ckpt.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
`

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatatodd: It has been 21 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatatodd: It has been 36 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatatodd: It has been 51 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatatodd: It has been 66 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatatodd: It has been 81 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatatodd: It has been 96 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatatodd: It has been 111 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatatodd: It has been 126 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by dksb** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
