### ISSUE TITLE
Multiple TITAN V introduce new error: CUB segmented reduce error

### ISSUE THREAD

**Issue by ialhashim** [tensorflow/tensorflow#19290]
### System information
- Keras code (with tf backend) that works perfectly on multiples of Titan Xp or 1080 Ti and tested on multiple TF versions both on Windows and Ubuntu
- Windows 10
- TensorFlow  1.8.0 (b'v1.8.0-0-g93bc2e2072' 1.8.0)
- Python 3.6.5
- CUDA 9.0/ cuDNN 7.0
- Two TITAN V

### Describe the problem
We upgraded our hardware from two Titan Xp to two Titan V. Running the exact same training script that was running perfectly on two GPUs now produces the error:
```
tensorflow.python.framework.errors_impl.InternalError: CUB segmented reduce errorinvalid configuration argument
```

If we run the same script on a single GPU it runs fine. If we run on two GPUs with batch size '1' it also works fine. This could be a Keras issue, but I don't find anything in the Trackback to indicate that. The training starts but at Epoch 2 it crashes after going over some batches.

Also, a minor note, the word 'errorinvalid' has no space in between.

### Source code / logs
Full trackback:
```
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\conda\conda\envs\py3tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1322, in _do_call
    return fn(*args)
  File "C:\Users\User\AppData\Local\conda\conda\envs\py3tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "C:\Users\User\AppData\Local\conda\conda\envs\py3tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InternalError: CUB segmented reduce errorinvalid configuration argument
         [[Node: loss/DEC_CONV1C_loss/Mean_1 = Mean[T=DT_FLOAT, Tidx=DT_INT32, _class=["loc:@training/Adam/gradients/loss/DEC_CONV1C_loss/Mean_1_grad/truediv"], keep_dims=false, _device="/job:localhost/replica:0/task:0/device:GPU:0"](loss/DEC_CONV1C_loss/Mean, training/Adam/gradients/loss/DEC_CONV1C_loss/Mean_1_grad/mod)]]
         [[Node: training/Adam/gradients/DEC_CONV1C_1/concat_grad/Slice_1/_429 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:1", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_1072_training/Adam/gradients/DEC_CONV1C_1/concat_grad/Slice_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:1"]()]]
```
The error prints this twice.

**Comment by ialhashim** [comment]
The fields are filled, do I need to modify the format to match the initial issue guide?

**Comment by tensorflowbutler** [comment]
Nagging Assignee @ekelsen: It has been 16 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @ekelsen: It has been 31 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by twinanda** [comment]
I have a code to train a segmentation network, which works well on a single-GPU setup. However, I encountered this issue when I am training the network on a multiple-GPU machine. The funny thing is that the first epoch was running just fine and I got this error at the beginning of the second epoch. Any ideas why?

**Comment by ialhashim** [comment]
I still haven't found a solution. But its interesting if you are getting the same "CUB segmented reduce error" on different hardware.

In my case the same multi GPU code was working fine on many different card types, only started encountering issues with the Titan V.

**Comment by twinanda** [comment]
Another thing I observed is that the optimization on multi-gpu was working fine for me if I use a built-in loss function, i.e., I did classification using categorical_cross_entropy from keras, and it went smoothly. Could this be a hint of the issue?

**Comment by twinanda** [comment]
@ialhashim I did not get exactly CUB segmented reduce error, but I had `CUB reduce errorinvalid configuration argument` . Not sure if the `segmented` keyword really matters, but I assumed this refers to the same issue. FYI, I am using TF 1.4.1. and keras 2.1.2

**Comment by tensorflowbutler** [comment]
Nagging Assignee @ekelsen: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by ialhashim** [comment]
After updating to latest drivers and nightly TF and latest Keras the problem seem to be gone.

**Comment by ningyanuta** [comment]
After upgrade to TF1.10 from 1.8, with keras 2.2.4 and nv driver 390.48 this problem is gone.

**Comment by VaibhavKhamgaonkar** [comment]
Hi ,

I am also getting the following error every time I am trying to train a model using Convolution NN.
I have GEForce GTX1050 4GB graphics card with CUDA computability 6.1.

**Error : tensorflow.python.framework.errors_impl.InternalError: CUB reduce errorinvalid configuration argument
[[{{node FUllYConnected_1/weight_regularizer/Sum}}]]
[[{{node metrics/acc/Mean}}]]**

so far I have tried following setting

    ```from keras import backend as K
    #import tensorflow as tf
    '''with K.tf.device('/gpu:0'):
        config = tf.ConfigProto(intra_op_parallelism_threads=4,\
               #inter_op_parallelism_threads=4, 
               allow_soft_placement=True,\
               device_count = {'CPU' : 4, 'GPU' : 1}
               )
        session = tf.Session(config=config)
        K.set_session(session)'''
    config = tf.ConfigProto(intra_op_parallelism_threads=1, allow_soft_placement=True, device_count = {'GPU': 1 , 'CPU': 1} ) 
    sess = tf.Session(config=config) 
    K.set_session(sess)

The entire Log is here below

```
2019-04-24 20:06:26.915635: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
2019-04-24 20:06:27.820975: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties:
name: GeForce GTX 1050 major: 6 minor: 1 memoryClockRate(GHz): 1.493
pciBusID: 0000:01:00.0
totalMemory: 4.00GiB freeMemory: 3.30GiB
2019-04-24 20:06:27.828955: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2019-04-24 20:06:28.433254: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-04-24 20:06:28.438610: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990] 0
2019-04-24 20:06:28.441346: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0: N
2019-04-24 20:06:28.444947: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3011 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1050, pci bus id: 0000:01:00.0, compute capability: 6.1)
Found 670341 images belonging to 36 classes.
Found 13700 images belonging to 36 classes.
WARNING:tensorflow:From D:\AnacondaInstalled\envs\tfgpu\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
2019-04-24 20:07:00.696348: E tensorflow/core/grappler/clusters/utils.cc:83] Failed to get device properties, error code: 30
Failed to initialize GPU device #0: unknown error
WARNING:tensorflow:From D:\AnacondaInstalled\envs\tfgpu\lib\site-packages\keras\backend\tensorflow_backend.py:3445: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
_________________________________________________________________
Layer (type) Output Shape Param #
=================================================================
1stInput (InputLayer) (None, 32, 32, 1) 0
_________________________________________________________________
1st (Conv2D) (None, 32, 32, 32) 832
_________________________________________________________________
batchNorm1 (BatchNormalizati (None, 32, 32, 32) 128
_________________________________________________________________
Relu1 (ReLU) (None, 32, 32, 32) 0
_________________________________________________________________
pool3 (MaxPooling2D) (None, 32, 32, 32) 0
_________________________________________________________________
dropout1 (Dropout) (None, 32, 32, 32) 0
_________________________________________________________________
2nd_conv (Conv2D) (None, 32, 32, 64) 18496
_________________________________________________________________
batchNorm2 (BatchNormalizati (None, 32, 32, 64) 256
_________________________________________________________________
relu2 (ReLU) (None, 32, 32, 64) 0
_________________________________________________________________
pool4 (MaxPooling2D) (None, 32, 32, 64) 0
_________________________________________________________________
dropout2 (Dropout) (None, 32, 32, 64) 0
_________________________________________________________________
3rd_conv (Conv2D) (None, 32, 32, 86) 49622
_________________________________________________________________
batchNorm3 (BatchNormalizati (None, 32, 32, 86) 344
_________________________________________________________________
relu3 (ReLU) (None, 32, 32, 86) 0
_________________________________________________________________
pool5 (MaxPooling2D) (None, 16, 16, 86) 0
_________________________________________________________________
dropout3 (Dropout) (None, 16, 16, 86) 0
_________________________________________________________________
FlattenLayer1 (Flatten) (None, 22016) 0
_________________________________________________________________
FUllYConnected_1 (Dense) (None, 1024) 22545408
_________________________________________________________________
batchNorm4 (BatchNormalizati (None, 1024) 4096
_________________________________________________________________
relu4 (ReLU) (None, 1024) 0
_________________________________________________________________
dropout6 (Dropout) (None, 1024) 0
_________________________________________________________________
FUll_2 (Dense) (None, 1024) 1049600
_________________________________________________________________
batchNorm5 (BatchNormalizati (None, 1024) 4096
_________________________________________________________________
relu5 (ReLU) (None, 1024) 0
_________________________________________________________________
dropout7 (Dropout) (None, 1024) 0
_________________________________________________________________
FUll_3 (Dense) (None, 36) 36900
=================================================================
Total params: 23,709,778
Trainable params: 23,705,318
Non-trainable params: 4,460
_________________________________________________________________
None
Model configured..!
WARNING:tensorflow:From D:\AnacondaInstalled\envs\tfgpu\lib\site-packages\tensorflow\python\ops\math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Epoch 1/30
2019-04-24 20:07:12.231219: I tensorflow/stream_executor/dso_loader.cc:152] successfully opened CUDA library cublas64_100.dll locally
Traceback (most recent call last):
File "CNN_mainScript.py", line 74, in <module>
obj.training()
File "D:\Projects\OCR-master\LSTMTraining.py", line 234, in training
workers=1
File "D:\AnacondaInstalled\envs\tfgpu\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
return func(*args, **kwargs)
File "D:\AnacondaInstalled\envs\tfgpu\lib\site-packages\keras\engine\training.py", line 1418, in fit_generator
initial_epoch=initial_epoch)
File "D:\AnacondaInstalled\envs\tfgpu\lib\site-packages\keras\engine\training_generator.py", line 217, in fit_generator
class_weight=class_weight)
File "D:\AnacondaInstalled\envs\tfgpu\lib\site-packages\keras\engine\training.py", line 1217, in train_on_batch
outputs = self.train_function(ins)
File "D:\AnacondaInstalled\envs\tfgpu\lib\site-packages\keras\backend\tensorflow_backend.py", line 2715, in __call__
return self._call(inputs)
File "D:\AnacondaInstalled\envs\tfgpu\lib\site-packages\keras\backend\tensorflow_backend.py", line 2675, in _call
fetched = self._callable_fn(*array_vals)
File "D:\AnacondaInstalled\envs\tfgpu\lib\site-packages\tensorflow\python\client\session.py", line 1439, in __call__
run_metadata_ptr)
File "D:\AnacondaInstalled\envs\tfgpu\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 528, in __exit__
c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InternalError: CUB reduce errorinvalid configuration argument
[[{{node FUllYConnected_1/weight_regularizer/Sum}}]]
[[{{node metrics/acc/Mean}}]]
```


Can anyone please help me to resolve this issue.

**Comment by Eshan2203** [comment]
After Restarting kernel it run well
