### ISSUE TITLE
Image Classification: Usage with C++ API (python_api_gen failed)

### ISSUE THREAD

**Issue by aarontan94** [tensorflow/tensorflow#19302]
### System information
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
**No custom code**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
**Ubuntu 16.04**
- TensorFlow installed from (source or binary):
**Installed from source**
- TensorFlow version (use command below):
**Tensorflow 1.8**
- Python version: 
**3**
- Bazel version (if compiling from source):
**Build label: 0.13.0**
- GCC/Compiler version (if compiling from source):
**gcc (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609**
- CUDA/cuDNN version:
**Cuda 9.0, cuDNN 7.0**
- GPU model and memory:
**GTX 1060 3gb**
- Exact command to reproduce:
----as taken from: https://www.tensorflow.org/tutorials/image_recognition

bazel build tensorflow/examples/label_image/...

curl -L "https://storage.googleapis.com/download.tensorflow.org/mode /inception_v3_2016_08_28_frozen.pb.tar.gz" |
  tar -C tensorflow/examples/label_image/data -xz

bazel build tensorflow/examples/label_image/...

### Describe the problem

I am trying to run the image classification example with the c++ api; however, when I  do bazel build, the following error occurs. I had completed the python api example with no problems. Please help.

Aaron

### Source code / logs
ERROR: /home/aaron/Software/tensorflow/tensorflow/tools/api/generator/BUILD:27:1: Executing genrule //tensorflow/tools/api/generator:python_api_gen failed (Exit 1)
Traceback (most recent call last):
  File "/home/aaron/.cache/bazel/_bazel_aaron/f08049efc03facba46c4fd0cb426b554/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/tools/api/generator/create_python_api.runfiles/org_tensorflow/tensorflow/tools/api/generator/create_python_api.py", line 26, in <module>
    from tensorflow.python.util import tf_decorator
  File "/home/aaron/.cache/bazel/_bazel_aaron/f08049efc03facba46c4fd0cb426b554/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/tools/api/generator/create_python_api.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/home/aaron/.cache/bazel/_bazel_aaron/f08049efc03facba46c4fd0cb426b554/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/tools/api/generator/create_python_api.runfiles/org_tensorflow/tensorflow/core/framework/graph_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/__init__.py", line 37, in <module>
    __import__('pkg_resources').declare_namespace(__name__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2952, in _initialize_master_working_set
    add_activation_listener(lambda dist: dist.activate())
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 956, in subscribe
    callback(dist)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2952, in <lambda>
    add_activation_listener(lambda dist: dist.activate())
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2515, in activate
    declare_namespace(pkg)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2097, in declare_namespace
    _handle_ns(packageName, path_item)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2047, in _handle_ns
    _rebuild_mod_path(path, packageName, module)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2066, in _rebuild_mod_path
    orig_path.sort(key=position_in_sys_path)
AttributeError: '_NamespacePath' object has no attribute 'sort'
INFO: Elapsed time: 4009.117s, Critical Path: 120.96s
INFO: 7023 processes, local.

**Comment by aarontan94** [comment]
Figured it out, running the following worked:
bazel build tensorflow/examples/label_image:label_image

instead of 
bazel build tensorflow/examples/label_image/...
