### ISSUE TITLE
AttributeError: 'module' object has no attribute 'Exporter'

### ISSUE THREAD

**Issue by suryathemass** [tensorflow/tensorflow#19315]
i ran retrain.py 
i got the code from tensorflow.org

Traceback (most recent call last):
  File "retrain.py", line 133, in <module>
    import tensorflow_hub as hub
  File "/home/pi/.local/lib/python2.7/site-packages/tensorflow_hub/__init__.py", line 26, in <module>
    from tensorflow_hub.estimator import LatestModuleExporter
  File "/home/pi/.local/lib/python2.7/site-packages/tensorflow_hub/estimator.py", line 61, in <module>
    class LatestModuleExporter(tf.estimator.Exporter):
AttributeError: 'module' object has no attribute 'Exporter'

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
It has been 16 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
It has been 32 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by skye** [comment]
I apologize, but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new). Please provide all the information it asks. Thank you.
