### ISSUE TITLE
ImportError: libnvidia-fatbinaryloader.so.384.111: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Deepak-Ceg** [tensorflow/tensorflow#19362]
### System information
- **Have I written custom code (as opposed to off a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04 LTS**:
- **TensorFlow installed from (source or binary) from official wesite:
- **TensorFlow version (use command below)**: 
- **Python version : 2.7**: 
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version: 9.0**:
- **GPU model and memory: GEFORCE GTX 1050(with GPU.While installation, it didnt**:
4 GB)**:
- **Exact command to reproduce: I installed tensor flow with pip(with GPU).While installation, it didnt recieve any errors but running I am getting following errors**:

### Describe the problem

when I tried importing Tensor flow I got the following errors:
 
>>> import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/deepak/.local/lib/python2.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/deepak/.local/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/deepak/.local/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/deepak/.local/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/deepak/.local/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/deepak/.local/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: libnvidia-fatbinaryloader.so.384.111: cannot open shared object file: No such file or directory

Failed to load the native TensorFlow runtime.

Does Anyone have experienced it?
please do help me!!!

**Comment by codeteo** [comment]
What worked for me was adding the path to my nvidia installation to `LD_LIBRARY_PATH` variable : 

```
export LD_LIBRARY_PATH=/usr/local/cuda-9.0/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}:/usr/lib/nvidia-396/
```

Of course instead of `nvidia-396` use your driver's version.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @cy89: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by Deepak-Ceg** [comment]
@codeteo Thanks a lot!!
It worked for me :)

**Comment by fi000** [comment]
Thanks how I could find my driver version as this is a cluster?

**Comment by eduOSS** [comment]
I get stuck by the same issue and cannot be solved with @codeteo's solution. Any other possibilities causing this issue?
