### ISSUE TITLE
Can't re-install tensorflow

### ISSUE THREAD

**Issue by JeremyLst** [tensorflow/tensorflow#1936]
Hi Everyone,

I have encountered a problem. I installed the tensorflow version 0.7.0, and using it to test mnist example, which outputted the error “AttributeError: 'module' object has no attribute 'gfile'”

I searched for the solution about this error, and realised that I need to roll back to version 0.6.0 or version 0.7.1, so I did un-installed the tensorflow and tried to install version 0.7.1 using
      sudo -H pip install https://storage.googleapis.com/tensorflow/mac/tensorflow-0.7.1-cp27-none-any.whl
However, it gave me the error:
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip/req/req_set.py", line 732, in install
    **kwargs
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 835, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 1030, in move_wheel_files
    isolated=self.isolated,
  File "/Library/Python/2.7/site-packages/pip/wheel.py", line 477, in move_wheel_files
    generated.extend(maker.make(spec))
  File "/Library/Python/2.7/site-packages/pip/_vendor/distlib/scripts.py", line 372, in make
    self._make_script(entry, filenames, options=options)
  File "/Library/Python/2.7/site-packages/pip/_vendor/distlib/scripts.py", line 276, in _make_script
    self._write_script(scriptnames, shebang, script, filenames, ext)
  File "/Library/Python/2.7/site-packages/pip/_vendor/distlib/scripts.py", line 250, in _write_script
    self._fileop.write_binary_file(outname, script_bytes)
  File "/Library/Python/2.7/site-packages/pip/_vendor/distlib/util.py", line 401, in write_binary_file
    with open(path, 'wb') as f:
**IOError: [Errno 2] No such file or directory: '/usr/local/bin/easy_install' **

As I checked, easy_install is lying in the directory  '/usr/local/bin/easy_install' , I don't know why this error happened.

Please help me solve this problem. It drives me crazy!!!!

Thank you!!

**Comment by keveman** [comment]
Can you please try installing a virtualenv as described [here](https://www.tensorflow.org/versions/r0.7/get_started/os_setup.html#virtualenv-installation) and let us know if you see the same problem?

**Comment by JeremyLst** [comment]
Thank you Keveman, using virtualenv and it works. 

But I still don't know why using pip directly did not work. Anyway, I just keep going with my mnist example testing.
