### ISSUE TITLE
The channel dimension of the inputs is `None` when tf.layers.conv2d after tf.slice with tf.shape instead of constant value

### ISSUE THREAD

**Issue by Giangblackk** [tensorflow/tensorflow#19376]
Here is my sample code to test the case:
```python
import tensorflow as tf
import numpy as np

if __name__ == '__main__':
    n_channel = 3
    n_layer = 5
    input_tensor = tf.placeholder(tf.float32, shape=[None, None, None, n_channel])
    input_image = np.random.rand(4, 512, 512,n_channel)

    slice = tf.slice(input_tensor, [0,0,0,0], [-1, tf.shape(input_tensor)[1], tf.shape(input_tensor)[2], -1])
    conv = tf.layers.conv2d(slice,filters=16,kernel_size=3,strides=1,padding='valid')

    with tf.Session() as sess:
        sess.run(tf.global_variables_initializer())
        output_image = sess.run(conv,feed_dict={input_tensor:input_image})
    print(output_image.shape)
```
Here is the error:
```python-traceback
Traceback (most recent call last):
  File "test_concat_then_conv.py", line 11, in <module>
    conv = tf.layers.conv2d(slice,filters=16,kernel_size=3,strides=1,padding='valid')
  File "/home/python3.6/site-packages/tensorflow/python/layers/convolutional.py", line 619, in conv2d
    return layer.apply(inputs)
  File "/home/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 825, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "/home/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 696, in __call__
    self.build(input_shapes)
  File "/home/lib/python3.6/site-packages/tensorflow/python/layers/convolutional.py", line 133, in build
    raise ValueError('The channel dimension of the inputs '
ValueError: The channel dimension of the inputs should be defined. Found `None`.
```
This happen only when I used `tf.layers.conv2d`. It works with `tf.nn.conv2d`.
I wonder what is the root of this problem?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by Giangblackk** [comment]
- Have I written custom code?
Yes
- OS Platform and Distribution?
Linux - Ubuntu 16.04
- TensorFlow installed from?
Anaconda3
TensorFlow version?
1.7.1
Bazel version?
I don't know.
CUDA/cuDNN version?
CUDA 9.0, cuDNN 7.1
GPU model and memory?
GPU GTX 1050 Ti
Exact command to reproduce?
I run the above code.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatatodd: It has been 16 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatatodd: It has been 31 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatatodd: It has been 46 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatatodd: It has been 61 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatatodd: It has been 77 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatatodd: It has been 93 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatatodd: It has been 109 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatatodd: It has been 123 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatatodd: It has been 138 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatatodd: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatatodd: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatatodd: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by gadagashwini** [comment]
@Giangblackk,
As mentioned by @yongtang `tf.slice` not able to capture output shape if size is `-1`. Workaround is, use absolute size as `3`. Below code snippet works with Tensorflow v2.8.0. 
```
import tensorflow as tf
tf.compat.v1.disable_eager_execution()
import numpy as np
n_channel = 3
n_layer = 5
input_tensor = tf.compat.v1.placeholder(tf.float32, shape=[None, None, None, n_channel])

input_image = np.random.rand(4, 512, 512,n_channel)

slice = tf.slice(input_tensor, [0,0,0,0], [3, tf.shape(input_tensor)[1], tf.shape(input_tensor)[2], 3])
print(slice)
conv = tf.keras.layers.Conv2D(16,kernel_size=3,strides=1,padding='valid')(slice)
```

**Output**
`Tensor("Slice_6:0", shape=(3, None, None, 3), dtype=float32)`
