### ISSUE TITLE
App crashes when building with gradle

### ISSUE THREAD

**Issue by achraf-boussaada** [tensorflow/tensorflow#19384]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
NO
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
macOS Sierra 10.12.6
- **TensorFlow installed from (source or binary)**:
source

- **Python version**: 
python 3.6
- **Bazel version (if compiling from source)**:
bazel 0.13.0
- **GCC/Compiler version (if compiling from source)**:
GCC 4.2.1

I managed to implement the object detection api in my app with my trained model. Despite that the app works fine I always get an error the the tensorflow_demo.so was not find so the tracking is unavailable which affected the bounding boxes in comparison with the tensorflow object detection demo (when you build it with bazel)

I downloaded the missing .so file and add it to my project by adding this to my gradle :
 
     lintOptions {
        abortOnError false
    }

    sourceSets.main {
        jniLibs.srcDirs =  ['libs']
    }

and then dropping the files into the created directory (JniLibs)

when I unpack my .apk file I can see clearly that the .so are packed in the .apk : 

     20336344  Defl:N  5832450  71% 00-00-1980 00:00 33cca329  lib/arm64-       v8a/libtensorflow_inference.so
      412440  Defl:N   210820  49% 00-00-1980 00:00 f305dd00  lib/armeabi- v7a/libtensorflow_demo.so
      1.3987972  Defl:N  4856867  65% 00-00-1980 00:00 be7adc48  lib/armeabi-v7a/libtensorflow_inference.so
       21178780  Defl:N  6353576  70% 00-00-1980 00:00 addfcb9d  lib/x86/libtensorflow_inference.so
       21811248  Defl:N  6681692  69% 00-00-1980 00:00 4cac1c73  lib/x86_64/libtensorflow_inference.so

the problem now is when I launch the app it crashes with the following error : 

         No implementation found for void package_name_tracking.ObjectTracker.initNative(int, int, boolean) (tried Java_package_name_tracking_ObjectTracker_initNative and Java_package_name_tracking_ObjectTracker_initNative__IIZ)

I want to avoid the use of bazel or cmake, is it possible or there is a solution for the error I'm getting !!

Any information would be helpful

**Comment by umutboz** [comment]
Could it be related to the android studio update? After updating, I started getting errors in my old apps

**Comment by achraf-boussaada** [comment]
As suggested downloading and including the `.so` file to your own project was not enough. Since we're including a pre-compiled version of the library the native methods (in the `.cpp` files) have the package name of the tensorflow demo on their names. That's why this error occur since our own projects packages named differently.  

 - To solve this problem you need to rename your package to `org.tensorflow.demo` and make sure that `ObjectTracker.java` is under `org.tensorflow.demo.tracking` 

- Second solution would be  changing the naming of the native methods in the `.cpp` files according to your package name and then rebuild the `.so` file with bazel (faced many problems there if anyone manage to do it please mention how).

 - I hope the tensorflow will mention this information when suggesting to download and drop the pre-buit version so the not so experienced developers won't waste unnecessary time on this issue.

**Comment by tensorflowbutler** [comment]
Nagging Assignees @petewarden, @angersson: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignees @petewarden, @angersson: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by petewarden** [comment]
I haven't had a chance to look at this. Passing to @achowdhery to take a look, since she's been working on this code recently.

**Comment by achowdhery** [comment]
@achraf-boussaada Please consider following the instructions in this Tutorial with bazel build. Please suggest if you are still stuck after trying those.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @achowdhery: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by achowdhery** [comment]
@achraf-boussaada Are you able to build the app with the latest code release?

**Comment by MohammadMoradi** [comment]
Hi, I have the same problem. I managed to implement object detection with my own model but I get the error tensorflow_demo.so is not found and so the tracking support cannot be enabled. I've download the package and replace it to jniLibs folder of my app and I haven't change the default app name. Still the error exists. Could you please help me?
How can I build my own tensorflow_demo.so?

**Comment by achraf-boussaada** [comment]
@achowdhery sorry for the late response ! unfortunately i didn't get to test it with the new build since i'm no longer working on the project..  i will keep the issue updated if i did come back to working on it.

@MohammadMoradi did you make sure you supported all CPU architectures? that may be your problem. it should be looking like this : 

> --jniLibs
> ----arm64-v8
> --------tensorflow_demo.so
> ----armeabi-v7a
> --------tensorflow_demo.so
> ----x86
> --------tensorflow_demo.so
> ----x86_64
> --------tensorflow_demo.so

**Comment by MohammadMoradi** [comment]
@achraf-boussaada Thanks for your response. My CPU architecture is armeabi-v7a and I only made the areabi-v7a directory. But maybe I should build all of them. Not sure!

**Comment by kate-kate** [comment]
Hello again @achowdhery :)
As you probably remember from [here](https://github.com/tensorflow/models/issues/5020) I am still not able to build .tflite file, so I decided to user Tensorflow Mobile with frozen graph instead of ml-kit, as it was in the [article](https://medium.com/tensorflow/training-and-serving-a-realtime-mobile-object-detector-in-30-minutes-with-cloud-tpus-b78971cf1193)
So, I successfully built the demo project with Android Studio as it was described in this [tutorial](https://www.tensorflow.org/mobile/android_build) and TF Classify works great, but I need TF Detect. And with enabling TF Detect demo I faced the same problem that guys above T____T
I really hope there is some solution for at least on of these issues...

**Comment by achowdhery** [comment]
@kate-kate you are building with Android Studio and cant get the app to build? What is the error message? You already get the TF Lite file correctly?

**Comment by achowdhery** [comment]
@kate-kate I am happy to help you. Please answer the following questions
1. Platform where you are install tensorflow. How did you install Tensorflow? What version?
2. Are you able to download a mobilenet_v1_ssd coco checkpoint and convert it to frozen graph?
3. Are you able to convert a frozen graph to tflite file?
4. Are you able to get the some version of Android Studio SDK and NDK? What is the version?
5. Are you able to build the app? Note for step 5, you dont need to try 1-3, there is a pre-built coco tflite model already in the app folder if you are trying to build it. What steps did you follow to build app? Is this device on a 32 bit architecture or 64 bit architecture?
6. Did you try to deploy the app on your Android Device?
In the steps above, please provide detailed instructions where something failed to help us reproduce. Also, it would be useful for you to try this with bazel build if Android Studio is not working (the key challenge is to get all the SDK and NDK versions correct in Android Studio).

**Comment by kate-kate** [comment]
@achowdhery Deeply appreciate your help.
1. I install Tensorflow 1.10 on mac os from source
2. Yes
3. I have an issue with "Converting unsupported operation: TFLite_Detection_PostProcess" but after converting the file appears
4. NDK version 16, SDK - 8.0
5. I've succesfully built the app (with an Android Studio) and even used TF Classify action, it worked
6. No, I used only emulator

**Comment by achowdhery** [comment]
@kate-kate I believe your TFlite file conversion is successful. "Converting unsupported operation: TFLite_Detection_PostProcess" message is showing up simply because this custom op is only in Tensorflow Lite and not in Tensorflow.
Now the main question that needs debugging is why the Android app does not work. Are you able to print out the logcat messages and copy/paste them here?

**Comment by kate-kate** [comment]
@achowdhery Sure
Logcat messages when I use TFlite file and android demo with ml-kit:
```
08-21 11:22:14.971 16825-16825/com.google.firebase.codelab.mlkit_custommodel W/System.err: com.google.firebase.ml.common.FirebaseMLException: The load task failed
08-21 11:22:14.973 16825-16825/com.google.firebase.codelab.mlkit_custommodel W/System.err:     at com.google.android.gms.internal.firebase_ml.zzgy.zzf(Unknown Source:75)
        at com.google.android.gms.internal.firebase_ml.zzgu.call(Unknown Source:8)
        at com.google.android.gms.internal.firebase_ml.zzgp.zza(Unknown Source:0)
08-21 11:22:14.974 16825-16825/com.google.firebase.codelab.mlkit_custommodel W/System.err:     at com.google.android.gms.internal.firebase_ml.zzgq.run(Unknown Source:4)
08-21 11:22:14.978 16825-16825/com.google.firebase.codelab.mlkit_custommodel W/System.err:     at android.os.Handler.handleCallback(Handler.java:789)
08-21 11:22:14.980 16825-16825/com.google.firebase.codelab.mlkit_custommodel W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
    Caused by: com.google.firebase.ml.common.FirebaseMLException: Internal error has occurred when executing Firebase ML tasks
        at com.google.android.gms.internal.firebase_ml.zzgp.zza(Unknown Source:15)
    	... 5 more
    Caused by: java.lang.IllegalArgumentException: Cannot create interpreter: Didn't find custom op for name 'TFLite_Detection_PostProcess'
    Registration failed.
08-21 11:22:14.981 16825-16825/com.google.firebase.codelab.mlkit_custommodel W/System.err:     at org.tensorflow.lite.NativeInterpreterWrapper.createInterpreter(Native Method)
        at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:63)
        at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:51)
        at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:90)
        at com.google.android.gms.internal.firebase_ml.zzhn.zzey(Unknown Source:103)
        at com.google.android.gms.internal.firebase_ml.zzha.zzfb(Unknown Source:75)
        at com.google.android.gms.internal.firebase_ml.zzha.call(Unknown Source:0)
        at com.google.android.gms.internal.firebase_ml.zzgp.zza(Unknown Source:0)
    	... 5 more
```

When I use Tensorflow Mobile android demo, TF Detect, without changing anything in models
```
08-21 11:27:01.833 17319-17319/org.tensorflow.demo I/TensorFlowInferenceInterface: Successfully loaded TensorFlow native methods (RunStats error may be ignored)
08-21 11:27:03.391 17319-17319/org.tensorflow.demo I/TensorFlowInferenceInterface: Model load took 1190ms, TensorFlow version: 1.10.0
08-21 11:27:03.392 17319-17319/org.tensorflow.demo I/TensorFlowInferenceInterface: Successfully loaded model from 'file:///android_asset/ssd_mobilenet_v1_android_export.pb'
08-21 11:27:03.394 17319-17319/org.tensorflow.demo I/tensorflow: DetectorActivity: Camera orientation relative to screen canvas: 90
08-21 11:27:03.395 17319-17319/org.tensorflow.demo I/tensorflow: DetectorActivity: Initializing at size 640x480
08-21 11:27:03.400 17319-17319/org.tensorflow.demo E/tensorflow: ObjectTracker: libtensorflow_demo.so not found, tracking unavailable
08-21 11:27:03.400 17319-17319/org.tensorflow.demo I/tensorflow: MultiBoxTracker: Initializing ObjectTracker: 640x480
08-21 11:27:03.400 17319-17319/org.tensorflow.demo E/tensorflow: ObjectTracker: Native object tracking support not found. See tensorflow/examples/android/README.md for details.
08-21 11:27:03.405 17319-17319/org.tensorflow.demo E/tensorflow: MultiBoxTracker: Object tracking support not found. See tensorflow/examples/android/README.md for details.
08-21 11:27:03.405 17319-17319/org.tensorflow.demo I/tensorflow: DetectorActivity: Preparing image 1 for detection in bg thread.
```
BTW - today the magic happened. I still had the error above while running TF Detect, but it worked! For the first time. For other who faced this problem - this time Android Studio warned be that its going to reinstall APK. After reinstallation it worked

But the error with ml-kit remains :(

**Comment by achowdhery** [comment]
@kate-kate Thanks for the update. We pushed some updates to gradle build yesterday.
We will look in to the ML-kit errors next.

**Comment by achowdhery** [comment]
@kate-kate ML-Kit has not yet updated to Tensorflow 1.10.
Can you modify your ML Kit to point to Tensorflow Lite 1.10? Here is the link:
https://firebase.google.com/docs/ml-kit/android/use-custom-tflite

**Comment by tensorflowbutler** [comment]
Nagging Assignee @achowdhery: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by kate-kate** [comment]
@achowdhery I've tried to follow your advice about ml kit but build didn't complete successfully because of ```ERROR: /private/var/tmp/_bazel_kate/8be913d8cdea6dd8174f0dac0a48c277/external/flatbuffers/BUILD.bazel:24:1: C++ compilation of rule '@flatbuffers//:flatbuffers' failed (Exit 1)```

**Comment by japer21** [comment]
@achraf-boussaada @tensorflowbutler @umutboz @angersson @petewarden @achowdhery 
I get this error:

```
09-20 18:48:31.364 9726-9726/org.tensorflow.mypackage E/art: No implementation found for long org.tensorflow.contrib.android.RunStats.allocate() (tried Java_org_tensorflow_contrib_android_RunStats_allocate and Java_org_tensorflow_contrib_android_RunStats_allocate__)
09-20 18:48:32.154 9726-9726/org.tensorflow.mypackageE/art: No implementation found for void org.tensorflow.mypackage.tracking.ObjectTracker.initNative(int, int, boolean) (tried Java_org_tensorflow_mypackage_tracking_ObjectTracker_initNative and Java_org_tensorflow_mypackage_tracking_ObjectTracker_initNative__IIZ)
09-20 18:48:32.154 9726-9726/org.tensorflow.mypackageE/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.tensorflow.mypackage, PID: 9726
    java.lang.UnsatisfiedLinkError: No implementation found for void org.tensorflow.mypackage.tracking.ObjectTracker.initNative(int, int, boolean) (tried Java_org_tensorflow_mypackage_tracking_ObjectTracker_initNative and Java_org_tensorflow_mypackage_tracking_ObjectTracker_initNative__IIZ)
        at org.tensorflow.mypackage.tracking.ObjectTracker.initNative(Native Method)
        at org.tensorflow.mypackage.tracking.ObjectTracker.init(ObjectTracker.java:257)
        at org.tensorflow.mypackage.tracking.ObjectTracker.getInstance(ObjectTracker.java:220)
        at org.tensorflow.mypackage.tracking.MultiBoxTracker.onFrame(MultiBoxTracker.java:211)
        at org.tensorflow.mypackage.DetectorActivity.processImage(DetectorActivity.java:254)
        at org.tensorflow.mypackage.CameraActivity.onPreviewFrame(CameraActivity.java:150)
        at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1183)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:158)
        at android.app.ActivityThread.main(ActivityThread.java:7231)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

```

Since I have renamed the project org.tensorflow.demo into org.tensorflow.mypackage because I wanted to have more applications running with different models.
The application starts but it crashes because of this error.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @achowdhery: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @achowdhery: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @achowdhery: It has been 45 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by idrissbellil** [comment]
did you @achraf-boussaada && @MohammadMoradi  try to right-click on app from Android-Studio -> link Cpp module, choose cmake then point it to tensorflow/examples/android/jni/CMakeLists.txt ?

**Comment by idrissbellil** [comment]
@NorwayLobster follow this [https://github.com/tensorflow/tensorflow/issues/22106#issuecomment-428409506](url) will solve it

**Comment by SerjSmor** [comment]
> As suggested downloading and including the `.so` file to your own project was not enough. Since we're including a pre-compiled version of the library the native methods (in the `.cpp` files) have the package name of the tensorflow demo on their names. That's why this error occur since our own projects packages named differently.
> 
> * To solve this problem you need to rename your package to `org.tensorflow.demo` and make sure that `ObjectTracker.java` is under `org.tensorflow.demo.tracking`
> * Second solution would be  changing the naming of the native methods in the `.cpp` files according to your package name and then rebuild the `.so` file with bazel (faced many problems there if anyone manage to do it please mention how).

I think I've managed to do that thanks to you. Here are the details:
1. Changed build to 'cmake' 
2. c files: changed all package #defines to match my custom structure (about 100 cases, use "replace in path")
FROM
#include "tensorflow/examples/android/jni/object_tracking/geom.h"
TO 
#include "geom.h"

Now the loading of the ObjectTracker succeeds but running methods are causing exceptions. 
1. Either create and move  ObjectTracker to 'org.tensorflow.demo.tracking' package 
1. Or change the following package under the 'object_tracker_jni.cc' 
FROM
Java_org_tensorflow_demo_tracking_ObjectTracker_##METHOD_NAME  // NOLINT
TO
Java_your_package_ObjectTracker_##METHOD_NAME  // NOLINT

@achraf-boussaada thanks for leading me to the right path !

**Comment by EbadSyed** [comment]
> > As suggested downloading and including the `.so` file to your own project was not enough. Since we're including a pre-compiled version of the library the native methods (in the `.cpp` files) have the package name of the tensorflow demo on their names. That's why this error occur since our own projects packages named differently.
> > 
> > * To solve this problem you need to rename your package to `org.tensorflow.demo` and make sure that `ObjectTracker.java` is under `org.tensorflow.demo.tracking`
> > * Second solution would be  changing the naming of the native methods in the `.cpp` files according to your package name and then rebuild the `.so` file with bazel (faced many problems there if anyone manage to do it please mention how).
> 
> I think I've managed to do that thanks to you. Here are the details:
> 
> 1. Changed build to 'cmake'
> 2. c files: changed all package #defines to match my custom structure (about 100 cases, use "replace in path")
>    FROM
>    #include "tensorflow/examples/android/jni/object_tracking/geom.h"
>    TO
>    #include "geom.h"
> 
> Now the loading of the ObjectTracker succeeds but running methods are causing exceptions.
> 
> 1. Either create and move  ObjectTracker to 'org.tensorflow.demo.tracking' package
> 2. Or change the following package under the 'object_tracker_jni.cc'
>    FROM
>    Java_org_tensorflow_demo_tracking_ObjectTracker_##METHOD_NAME  // NOLINT
>    TO
>    Java_your_package_ObjectTracker_##METHOD_NAME  // NOLINT
> 
> @achraf-boussaada thanks for leading me to the right path !

@SerjSmor Did you move the JNI folder to the custom application folder ?

Or did you just made changes to existing files without changing any locations ?

I am trying to do the same but still confused.

**Comment by Zeit42** [comment]
Any updates for 2019 for Tensorflow-lite? The Nightly Build links are now dead.

**Comment by achowdhery** [comment]
The nightly build for Tensorflow lite is working appropriately. Please advise what link are you trying.

**Comment by jdduke** [comment]
> Nightly Build links are now dead.

Which links in particular? I strongly encourage users to switch to using TensorFlow Lite. The detection sample for that can be found @ https://github.com/tensorflow/examples/blob/master/lite/examples/object_detection/android/README.md.

**Comment by Zeit42** [comment]
@achowdhery and @jdduke sorry for the carelessly worded statement, I'm trying to build the Android Demo from source [using this link](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/android#building-the-demo-with-tensorflow-from-source) with the hopes of getting Object Tracking in Tensorflow-Lite to work. I'll go through with this process and open a ticket if I encounter any Build Issues.

**Comment by sal0w** [comment]
> > Nightly Build links are now dead.
> 
> Which links in particular? I strongly encourage users to switch to using TensorFlow Lite. The detection sample for that can be found @ https://github.com/tensorflow/examples/blob/master/lite/examples/object_detection/android/README.md.

When I use the above repo I am getting the same error

> 12142-12142/org.tensorflow.lite.examples.detection I/tensorflow: DetectorActivity: Camera orientation relative to screen canvas: 90
2019-03-27 19:51:02.065 12142-12142/org.tensorflow.lite.examples.detection I/tensorflow: DetectorActivity: Initializing at size 640x480
2019-03-27 19:51:02.072 12142-12142/org.tensorflow.lite.examples.detection E/tensorflow: ObjectTracker: libtensorflow_demo.so not found, tracking unavailable
2019-03-27 19:51:02.073 12142-12142/org.tensorflow.lite.examples.detection I/tensorflow: MultiBoxTracker: Initializing ObjectTracker: 640x480
2019-03-27 19:51:02.073 12142-12142/org.tensorflow.lite.examples.detection E/tensorflow: ObjectTracker: Native object tracking support not found. See tensorflow/examples/android/README.md for details.
2019-03-27 19:51:02.091 12142-12142/org.tensorflow.lite.examples.detection E/tensorflow: MultiBoxTracker: Object tracking support not found. See tensorflow/examples/android/README.md for details.
2019-03-27 19:51:02.092 12142-12142/org.tensorflow.lite.examples.detection I/tensorflow: DetectorActivity: Preparing image 1 for detection in bg thread.
2019-03-27 19:51:02.208 12142-12172/org.tensorflow.lite.examples.detection I/tensorflow: DetectorActivity: Running detection on image 1

And I am not able to find the JNI folder or the libtensorflow_demo.so in any of the folders. If libtensorflow_demo.so is availble can you point me the path? Or is there any procedudre I have to follow to build it?

**Comment by Zeit42** [comment]
@achowdhery and @jdduke, I opened a [new ticket here](https://github.com/tensorflow/tensorflow/issues/27199)

**Comment by MeghnaNatraj** [comment]
Marking issue as resolved. Feel free to re-open this if it's unresolved or file a [new issue](https://github.com/tensorflow/tensorflow/issues/new/choose)
