### ISSUE TITLE
Speech demo crash [Bug]

### ISSUE THREAD

**Issue by Mohammad-Tabbara** [tensorflow/tensorflow#19383]
I installed the demo APK on my android phone to test it out. during my playthrough of the speech app, the APP crashed but I had the phone connected to my PC so I found in the logs the following error(couldn't reproduce crash).

`org.tensorflow.demo E/AndroidRuntime: FATAL EXCEPTION: Thread-6
    Process: org.tensorflow.demo, PID: 29587
    java.lang.RuntimeException: You must feed results in increasing time order, but received a timestamp of 1526649298145 that was earlier than the previous one of 1526649298240
        at org.tensorflow.demo.RecognizeCommands.processLatestResults(RecognizeCommands.java:114)
        at org.tensorflow.demo.SpeechActivity.recognize(SpeechActivity.java:319)
        at org.tensorflow.demo.SpeechActivity.access$100(SpeechActivity.java:61)
        at org.tensorflow.demo.SpeechActivity$3.run(SpeechActivity.java:265)
        at java.lang.Thread.run(Thread.java:762)`

### FORM

APK link: https://ci.tensorflow.org/view/Nightly/job/nightly-android/lastSuccessfulBuild/artifact/out/tensorflow_demo.apk

Have I written custom code: No Used the already build Demo APK
OS Platform and Distribution: Android API 24 - Samsung
TensorFlow installed from N/A
TensorFlow version: N/A
Bazel version: N/A
CUDA/cuDNN version: N/A
GPU model and memory: Mali-T830 (Single core GPU)
Exact command to reproduce: Opened Voice Apk then said the second word(Couldn't reproduce)

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
It has been 15 days with no activity and the `awaiting response` label was assigned. Is this still an issue?
