### ISSUE TITLE
[Bug] tf.shape does not return correct value when using tf.cond and tf.reshape

### ISSUE THREAD

**Issue by chmod644** [tensorflow/tensorflow#19397]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Y
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: ('v1.8.0-0-g93bc2e2072', '1.8.0')
- **Python version**: 2.7.15
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**: 9.0/7.0
- **GPU model and memory**: GeForce GTX 1060 6GB
- **Exact command to reproduce**:

### Describe the problem

When  all of below conditions is true, tf.shape return NOT correct value.
* use `tf.reshape` in and out of `tf.cond` and 
* `tf.reshape` inside of `tf.cond` has unknown shape (-1)
* `tf.reshape` inside of `tf.cond` reduces or increases rank of tensor

I have checked that same code doesn't cause error  in TensorFlow 1.7. But TensorFlow 1.8 cause this error.

I guess this phenomena caused by a failure of branch prediction or error of graph-optimization.

#### Source code
```python
import tensorflow as tf


def init(height):
    orig = tf.zeros(shape=[height])
    reshaped = tf.reshape(orig, shape=[-1])

    # tf.shape(reshaped) must return [1, 2]. But this actually return [2, 2]. It's WRONG!!
    reshaped = tf.Print(reshaped, [tf.shape(reshaped)], message="tf.shape(reshaped) before tf.cond: ")

    def true_fn(t):
        t = tf.Print(t, [], message="pass in true_fn")
        return tf.reshape(t, (2, 1))

    def false_fn(t):
        t = tf.Print(t, [], message="pass in false_fn")
        return tf.reshape(t, (-1, 1))

    reshaped = tf.cond(
        tf.equal(tf.shape(reshaped)[0], 2), lambda: true_fn(reshaped), lambda: false_fn(reshaped), strict=True)

    reshaped = tf.Print(reshaped, [tf.shape(reshaped)], message="tf.shape(reshaped) after tf.cond: ")

    return reshaped


def main():

    height = tf.placeholder(dtype=tf.int32, shape=())
    reshaped = init(height)

    with tf.Session() as sess:
        sess.run(reshaped, feed_dict={height: 1})


if __name__ == '__main__':
    main()
```

#### Log
```
2018-05-19 04:54:10.722065: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning
 NUMA node zero
2018-05-19 04:54:10.722448: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 0 with properties:
name: GeForce GTX 1060 6GB major: 6 minor: 1 memoryClockRate(GHz): 1.7845
pciBusID: 0000:01:00.0
totalMemory: 5.94GiB freeMemory: 4.86GiB
2018-05-19 04:54:10.722467: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1435] Adding visible gpu devices: 0
2018-05-19 04:54:10.911223: I tensorflow/core/common_runtime/gpu/gpu_device.cc:923] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-05-19 04:54:10.911263: I tensorflow/core/common_runtime/gpu/gpu_device.cc:929]      0
2018-05-19 04:54:10.911271: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 0:   N
2018-05-19 04:54:10.911466: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 4623 MB memory) -> physical GPU (device: 0
, name: GeForce GTX 1060 6GB, pci bus id: 0000:01:00.0, compute capability: 6.1)
tf.shape(reshaped) before tf.cond: [2]
pass in true_fn
Traceback (most recent call last):
  File "./main.py", line 40, in <module>
    main()
  File "./main.py", line 36, in main
    sess.run(reshaped, feed_dict={height: 1})
  File "/home/n/anaconda2/envs/tf18/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/home/n/anaconda2/envs/tf18/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/n/anaconda2/envs/tf18/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/home/n/anaconda2/envs/tf18/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 1 values, but the requested shape has 2
         [[Node: cond/Reshape = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](cond/Print/_19, cond/Reshape/shape)]]
         [[Node: Shape_2/_25 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_26_Shape_2", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op u'cond/Reshape', defined at:
  File "./main.py", line 40, in <module>
    main()
  File "./main.py", line 33, in main
    reshaped = init(height)
  File "./main.py", line 23, in init
    tf.equal(tf.shape(reshaped)[0], 2), lambda: true_fn(reshaped), lambda: false_fn(reshaped), strict=True)
  File "/home/n/anaconda2/envs/tf18/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 432, in new_func
    return func(*args, **kwargs)
  File "/home/n/anaconda2/envs/tf18/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2063, in cond
    orig_res_t, res_t = context_t.BuildCondBranch(true_fn)
  File "/home/n/anaconda2/envs/tf18/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 1913, in BuildCondBranch
    original_result = fn()
  File "./main.py", line 23, in <lambda>
    tf.equal(tf.shape(reshaped)[0], 2), lambda: true_fn(reshaped), lambda: false_fn(reshaped), strict=True)
  File "./main.py", line 16, in true_fn
    return tf.reshape(t, (2, 1))
  File "/home/n/anaconda2/envs/tf18/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 6113, in reshape
    "Reshape", tensor=tensor, shape=shape, name=name)
  File "/home/n/anaconda2/envs/tf18/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/n/anaconda2/envs/tf18/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/home/n/anaconda2/envs/tf18/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Input to reshape is a tensor with 1 values, but the requested shape has 2
         [[Node: cond/Reshape = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](cond/Print/_19, cond/Reshape/shape)]]
         [[Node: Shape_2/_25 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_26_Shape_2", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
```

**Comment by tensorflowbutler** [comment]
Nagging Assignee @bignamehyp: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by bignamehyp** [comment]
Thanks for reporting this bug. I can reproduce. Maybe turn off graph rewriting to see if it's the cause.
      rewriter_config = rewriter_config_pb2.RewriterConfig(
          disable_model_pruning=True,
          constant_folding=rewriter_config_pb2.RewriterConfig.OFF,
          arithmetic_optimization=rewriter_config_pb2.RewriterConfig.OFF,
          dependency_optimization=rewriter_config_pb2.RewriterConfig.OFF,
          function_optimization=rewriter_config_pb2.RewriterConfig.OFF,
          layout_optimizer=rewriter_config_pb2.RewriterConfig.OFF,
          loop_optimization=rewriter_config_pb2.RewriterConfig.OFF,
          memory_optimization=rewriter_config_pb2.RewriterConfig.NO_MEM_OPT)
      config = tf.ConfigProto(
          allow_soft_placement=True,
          graph_options=tf.GraphOptions(rewrite_options=rewriter_config)
      )
      sess = tf.Session(config=config)

**Comment by chmod644** [comment]
Thank you very much. I got the appropriate result. Also, i got the correct result with the following code.
```python
rewriter_config = rewriter_config_pb2.RewriterConfig(                      
        constant_folding=rewriter_config_pb2.RewriterConfig.OFF,           
        )                                                                  
config = tf.ConfigProto(                                                   
        graph_options=tf.GraphOptions(rewrite_options=rewriter_config)     
        ) 
sess = tf.Session(config=config)                                                           
```

Does adding the option slow down the program ? Will this behavior be fixed in tensorflow 1.9 (or 1.10) ?

**Comment by bignamehyp** [comment]
We will work on fixing this issue. Thank you very much for reporting it.

**Comment by chmod644** [comment]
OK. I will use this workaround for a while.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @bignamehyp: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @bignamehyp: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @bignamehyp: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @bignamehyp: It has been 60 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @bignamehyp: It has been 76 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @bignamehyp: It has been 91 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @bignamehyp: It has been 106 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @bignamehyp: It has been 121 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by nartes** [comment]
what release this issue has been fixed in?

**Comment by nartes** [comment]
1.11.0rc1 is still buggy!

**Comment by nartes** [comment]
> This bug will be fixed in the next release.

Could you please tell the commit which has introduced the fix?
