### ISSUE TITLE
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by rnunziata** [tensorflow/tensorflow#19427]
Please note that I have cuda-9.2 ...there are no cuda 9.0 files anywhere in my system or references . Yet tensorflow still wants  libcublas.so.9.0.  I tried uninstalling both cuda and tensorflow but still error is show. Has anyone seen this and what can be done? Thank you.
```
sudo find . / -name libcublas.so.9.*

./cuda-9.2/targets/x86_64-linux/lib/libcublas.so.9.2
./cuda-9.2/targets/x86_64-linux/lib/libcublas.so.9.2.113
./cuda-9.2/targets/x86_64-linux/lib/libcublas.so.9.2.88
/usr/local/cuda-9.2/targets/x86_64-linux/lib/libcublas.so.9.2
/usr/local/cuda-9.2/targets/x86_64-linux/lib/libcublas.so.9.2.113
/usr/local/cuda-9.2/targets/x86_64-linux/lib/libcublas.so.9.2.88
```

```
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/rjn/.local/lib/python2.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/rjn/.local/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/rjn/.local/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/rjn/.local/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/rjn/.local/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/rjn/.local/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

```

**Comment by venkat-kittu** [comment]
me to facing same problem

**Comment by venkat-kittu** [comment]
me to facing a problem like this i can't import tensorflow with CUDA 9.2

**Comment by achalshah20** [comment]
Tensorflow from pip is compiled with cuda 9.0. Read this comment for solution https://github.com/tensorflow/tensorflow/issues/19438#issuecomment-390740115

**Comment by rnunziata** [comment]
following advice from achalshah20  comment....I downloaded the nvida file.
sudo dpkg -i cuda-repo-ubuntu1604_9.0.176-1_amd64.deb
sudo apt-get install cuda-9.0

note: its important specify 9.0 if you just put cuda down then you will not get the 9.0 release if anything greater is installed.
