### ISSUE TITLE
tf.fill fails when dims has type tf.int64

### ISSUE THREAD

**Issue by jeffpollock9** [tensorflow/tensorflow#19424]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.8.0 (CPU version)
- **Python version**: 3.6.5

### Describe the problem

`tf.fill([n], 42.0)` fails when `n` is of type `tf.int64`, according to [the docs](https://www.tensorflow.org/api_docs/python/tf/fill):

>  dims: A `Tensor`. Must be one of the following types: `int32`, `int64`. 1-D. Represents the shape of the output tensor.

### Source code / logs

The following code describes the problem:

```python
import tensorflow as tf

n1 = tf.constant(3, tf.int32)
n2 = tf.constant(3, tf.int64)

x1 = tf.fill([n1], 42.0)  # OK
x2 = tf.fill([n2], 42.0)  # not OK
```

output:

```python
>>> import tensorflow as tf
>>> n1 = tf.constant(3, tf.int32)
>>> n2 = tf.constant(3, tf.int64)
>>> x1 = tf.fill([n1], 42.0)  # OK
>>> x2 = tf.fill([n2], 42.0)  # not OK
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 2717, in fill
    "Fill", dims=dims, value=value, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py", line 513, in _apply_op_helper
    raise err
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py", line 510, in _apply_op_helper
    preferred_dtype=default_dtype)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 1104, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/constant_op.py", line 235, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/constant_op.py", line 214, in constant
    value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/tensor_util.py", line 432, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/tensor_util.py", line 340, in _AssertCompatible
    raise TypeError("List of Tensors when single Tensor expected")
TypeError: List of Tensors when single Tensor expected
```

Thanks!

**Comment by facaiy** [comment]
Hi, List is not Tensor. I think you should pass a tf.constant([3], tf.int64) directly for dims.

**Comment by jeffpollock9** [comment]
Hi, thanks for the reply, @facaiy. Indeed it seems like it is best to pass what you said and it works for `tf.int64` and `tf.int32`.

Any idea why this works for `tf.int32` and not for `tf.int64`? Is it a bug?

```python
import tensorflow as tf

n = tf.constant(3, tf.int32)
x = tf.fill([n], 42.0)

with tf.Session() as sess:
    print(sess.run(x))
```

**Comment by facaiy** [comment]
I think it's not bug. `tf.int32` is the default dtype for `tf.fill`, so tensorflow always try to cast your list to `tf.int32` if possible.
