### ISSUE TITLE
I am trying to deploy my tensorflow model(CNN) to android, when I am trying to use my .pb file( generated after training the model )in android studio it shows! 

### ISSUE THREAD

**Issue by sonu107** [tensorflow/tensorflow#19458]
05-22 16:23:02.608 27021-27021/com.example.bibhu.smscnn E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.example.bibhu.smscnn, PID: 27021
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.bibhu.smscnn/com.example.bibhu.smscnn.MainActivity}: java.lang.RuntimeException: Failed to load model from 'file:///android_asset/graph11.pb'
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2820)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2895)
at android.app.ActivityThread.-wrap11(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1596)
at android.os.Handler.dispatchMessage(Handler.java:105)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6565)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
Caused by: java.lang.RuntimeException: Failed to load model from 'file:///android_asset/graph11.pb'
at org.tensorflow.contrib.android.TensorFlowInferenceInterface.(TensorFlowInferenceInterface.java:113)
at com.example.bibhu.smscnn.TensorFlowClassifier.create(TensorFlowClassifier.java:70)
at com.example.bibhu.smscnn.TensorflowIntegrationExample.loadModel(TensorflowIntegrationExample.java:35)
at com.example.bibhu.smscnn.TensorflowIntegrationExample.(TensorflowIntegrationExample.java:27)
at com.example.bibhu.smscnn.MainActivity.onCreate(MainActivity.java:21)
at android.app.Activity.performCreate(Activity.java:6975)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2773)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2895) 
at android.app.ActivityThread.-wrap11(Unknown Source:0) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1596) 
at android.os.Handler.dispatchMessage(Handler.java:105) 
at android.os.Looper.loop(Looper.java:164) 
at android.app.ActivityThread.main(ActivityThread.java:6565) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
Caused by: java.io.IOException: Not a valid TensorFlow Graph serialization: Input 1 of node embedding/embedding_lookup was passed float from inputTensor:0 incompatible with expected int32.
at org.tensorflow.contrib.android.TensorFlowInferenceInterface.loadGraph(TensorFlowInferenceInterface.java:561)
at org.tensorflow.contrib.android.TensorFlowInferenceInterface.(TensorFlowInferenceInterface.java:105)
at com.example.bibhu.smscnn.TensorFlowClassifier.create(TensorFlowClassifier.java:70) 
at com.example.bibhu.smscnn.TensorflowIntegrationExample.loadModel(TensorflowIntegrationExample.java:35) 
at com.example.bibhu.smscnn.TensorflowIntegrationExample.(TensorflowIntegrationExample.java:27) 
at com.example.bibhu.smscnn.MainActivity.onCreate(MainActivity.java:21) 
at android.app.Activity.performCreate(Activity.java:6975) 
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214) 
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2773) 
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2895) 
at android.app.ActivityThread.-wrap11(Unknown Source:0) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1596) 
at android.os.Handler.dispatchMessage(Handler.java:105) 
at android.os.Looper.loop(Looper.java:164) 
at android.app.ActivityThread.main(ActivityThread.java:6565) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by sonu107** [comment]
05-22 16:23:02.608 27021-27021/com.example.bibhu.smscnn E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.bibhu.smscnn, PID: 27021
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.bibhu.smscnn/com.example.bibhu.smscnn.MainActivity}: java.lang.RuntimeException: Failed to load model from 'file:///android_asset/graph11.pb'
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2820)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2895)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1596)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6565)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
     Caused by: java.lang.RuntimeException: Failed to load model from 'file:///android_asset/graph11.pb'
        at org.tensorflow.contrib.android.TensorFlowInferenceInterface.<init>(TensorFlowInferenceInterface.java:113)
        at com.example.bibhu.smscnn.TensorFlowClassifier.create(TensorFlowClassifier.java:70)
        at com.example.bibhu.smscnn.TensorflowIntegrationExample.loadModel(TensorflowIntegrationExample.java:35)
        at com.example.bibhu.smscnn.TensorflowIntegrationExample.<init>(TensorflowIntegrationExample.java:27)
        at com.example.bibhu.smscnn.MainActivity.onCreate(MainActivity.java:21)
        at android.app.Activity.performCreate(Activity.java:6975)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2773)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2895) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1596) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6565) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
     Caused by: java.io.IOException: Not a valid TensorFlow Graph serialization: Input 1 of node embedding/embedding_lookup was passed float from inputTensor:0 incompatible with expected int32.
        at org.tensorflow.contrib.android.TensorFlowInferenceInterface.loadGraph(TensorFlowInferenceInterface.java:561)
        at org.tensorflow.contrib.android.TensorFlowInferenceInterface.<init>(TensorFlowInferenceInterface.java:105)
        at com.example.bibhu.smscnn.TensorFlowClassifier.create(TensorFlowClassifier.java:70) 
        at com.example.bibhu.smscnn.TensorflowIntegrationExample.loadModel(TensorflowIntegrationExample.java:35) 
        at com.example.bibhu.smscnn.TensorflowIntegrationExample.<init>(TensorflowIntegrationExample.java:27) 
        at com.example.bibhu.smscnn.MainActivity.onCreate(MainActivity.java:21) 
        at android.app.Activity.performCreate(Activity.java:6975) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2773) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2895) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1596) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6565) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by Akshathar8** [comment]
How did you solve this issue?
I am facing the same issue. Please help!

**Comment by bibhu107** [comment]
Hi,  @Akshathar8, Read this line   Caused by: java.io.IOException: Not a valid TensorFlow Graph serialization: Input 1 of node embedding/embedding_lookup was passed float from inputTensor:0 incompatible with expected int32.
