### ISSUE TITLE
How to optimize for inference , from frozen graph?

### ISSUE THREAD

**Issue by sonu107** [tensorflow/tensorflow#19495]
```
import tensorflow as tf
from tensorflow.python.tools import freeze_graph
from tensorflow.python.tools import optimize_for_inference_lib

inputGraph = tf.GraphDef()
with tf.gfile.Open("frozen.pb", "rb") as f:
    data2read = f.read()
    inputGraph.ParseFromString(data2read)

outputGraph = optimize_for_inference_lib.optimize_for_inference(
                inputGraph,
                ["inputTensor"], # an array of the input node(s)
                ["output/output"], # an array of output nodes
                tf.int32.as_datatype_enum)

        # Save the optimized graph

f = tf.gfile.FastGFile("outputOptimizedGraph.pb", "w")
f.write(outputGraph.SerializeToString())    

```
Output : /home/bibhu/anaconda2/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "convert_frozen.py", line 14, in <module>
    tf.int32.as_datatype_enum)
  File "/home/bibhu/anaconda2/lib/python2.7/site-packages/tensorflow/python/tools/optimize_for_inference_lib.py", line 111, in optimize_for_inference
    placeholder_type_enum)
  File "/home/bibhu/anaconda2/lib/python2.7/site-packages/tensorflow/python/tools/strip_unused_lib.py", line 86, in strip_unused
    output_node_names)
  File "/home/bibhu/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/graph_util_impl.py", line 174, in extract_sub_graph
    _assert_nodes_are_present(name_to_node, dest_nodes)
  File "/home/bibhu/anaconda2/lib/python2.7/site-**packages/tensorflow/python/framework/graph_util_impl.py", line 133, in _assert_nodes_are_present
    assert d in name_to_node, "%s is not in graph" % d
AssertionError: output/output is not in grap**

**Comment by sonu107** [comment]
@achalshah20  Here is the new issue!

**Comment by sonu107** [comment]
```
outputGraph = optimize_for_inference_lib.optimize_for_inference(
                inputGraph,
                ["inputTensor"], # an array of the input node(s)
                ["output/predictions"], # an array of output nodes
                tf.int32.as_datatype_enum)
```
