### ISSUE TITLE
KeyError: "The following input nodes were not found: set(['Mul'])\n"

### ISSUE THREAD

**Issue by qemb01** [tensorflow/tensorflow#19515]
I have a model named rounded_graph.pb that's been produced from the TensorFlow for Poets codelab. Then I should strip the DecodeJpeg Op from model by the following command :

python strip_unused.py --input_graph=rounded_graph.pb --output_graph=output.pb --input_node_names="Mul" --output_node_names="final_result" --input_binary=true  

But I got the following error :

  File "strip_unused.py", line 107, in <module>
    app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/home/eli/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "strip_unused.py", line 61, in main
    FLAGS.placeholder_type_enum)
  File "/home/eli/.local/lib/python2.7/site-packages/tensorflow/python/tools/strip_unused_lib.py", line 114, in strip_unused_from_files
    placeholder_type_enum)
  File "/home/eli/.local/lib/python2.7/site-packages/tensorflow/python/tools/strip_unused_lib.py", line 83, in strip_unused
    raise KeyError("The following input nodes were not found: %s\n" % not_found)
KeyError: "The following input nodes were not found: set(['Mul'])\n"
eli@eli-virtual-machine:~/Documents/tensorflow-master/tensorflow/python/tools$ python strip_unused.py --input_graph=optimized_graph.pb --output_graph=output.pb --input_node_names="Mul" --output_node_names="final_result" --input_binary=true 
Traceback (most recent call last):
  File "strip_unused.py", line 107, in <module>
    app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/home/eli/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "strip_unused.py", line 61, in main
    FLAGS.placeholder_type_enum)
  File "/home/eli/.local/lib/python2.7/site-packages/tensorflow/python/tools/strip_unused_lib.py", line 114, in strip_unused_from_files
    placeholder_type_enum)
  File "/home/eli/.local/lib/python2.7/site-packages/tensorflow/python/tools/strip_unused_lib.py", line 83, in strip_unused
    raise KeyError("The following input nodes were not found: %s\n" % not_found)
KeyError: "The following input nodes were not found: set(['Mul'])\n"

If I don't do this before moving the model to APP, "Error initializing TensorFlow" will happen when APP run.

What should I do? Please help me, thanks!

**Comment by qemb01** [comment]
I got the error: APP use the inceptionv3 model ,but TensorFlow for Poets codelab have updated the model from inceptionv3 to mobilenet. So error happened.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @reedwm: It has been 17 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @reedwm: It has been 32 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by reedwm** [comment]
/CC @wolffg any ideas? Maybe this is more suited to StackOverflow.

**Comment by wolffg** [comment]
Mark, do you have insight here?

**Comment by Sagarsharma4244** [comment]
If you are getting an error KeyError: "The following input nodes were not found: {'input'}\n" then change "input" to "Mul"
If anybody still has doubt refer [TensorFlow on Mobile: Tutorial](https://towardsdatascience.com/tensorflow-on-mobile-tutorial-1-744703297267)

**Comment by tensorflowbutler** [comment]
Nagging Assignees @wolffg, @MarkDaoust: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignees @wolffg, @MarkDaoust: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignees @wolffg, @MarkDaoust: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignees @wolffg, @MarkDaoust: It has been 59 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignees @wolffg, @MarkDaoust: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignees @wolffg, @MarkDaoust: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignees @wolffg, @MarkDaoust: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by shirokuromaguro** [comment]
if the Protocol Buffer file is created by retrain.py, change the input node name to "Placeholder".
my graph optimized successfully by doing so.

**Comment by tensorflowbutler** [comment]
Nagging Assignees @wolffg, @MarkDaoust: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignees @wolffg, @MarkDaoust: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by wolffg** [comment]
I'm going to close this, as we have a vastly different converter at this point.
