### ISSUE TITLE
[BUG] max_pooling1d can not run in GPU 

### ISSUE THREAD

**Issue by simon-moloco** [tensorflow/tensorflow#19567]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.6.0
- **Python version**: 2.71.0
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:  9.0/7102
- **GPU model and memory**: 3x GeForce GTX 1080 at 8G
- **Exact command to reproduce**: 

### Describe the problem

I have a rank-2 tensor, say a 1024*512 tensor, and I want to apply 1D max pooling. If I run in CPU, codes work great. However, If I run in GPU, codes will throw exceptions like the following.

```
2018-05-25 18:28:34.272767: E tensorflow/stream_executor/cuda/cuda_dnn.cc:396] Loaded runtime CuDNN library: 7102 (compatibility version 7100) but source was compiled with 7005 (compatibility version 7000).  If using a binary install, upgrade your CuDNN library to match.  If building from sources, make sure the library loaded at runtime matches a compatible version specified during compile configuration.
2018-05-25 18:28:34.273613: W ./tensorflow/stream_executor/stream.h:2018] attempting to perform DNN operation using StreamExecutor without DNN support
Traceback (most recent call last):
  File "/var/lib/jenkins/venvs/gpumoloco/local/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 355, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/var/lib/jenkins/venvs/gpumoloco/local/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 903, in _train_model
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/var/lib/jenkins/venvs/gpumoloco/local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 546, in run
    run_metadata=run_metadata)
  File "/var/lib/jenkins/venvs/gpumoloco/local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1022, in run
    run_metadata=run_metadata)
  File "/var/lib/jenkins/venvs/gpumoloco/local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1113, in run
    raise six.reraise(*original_exc_info)
  File "/var/lib/jenkins/venvs/gpumoloco/local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1098, in run
    return self._sess.run(*args, **kwargs)
  File "/var/lib/jenkins/venvs/gpumoloco/local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1170, in run
    run_metadata=run_metadata)
  File "/var/lib/jenkins/venvs/gpumoloco/local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 950, in run
    return self._sess.run(*args, **kwargs)
  File "/var/lib/jenkins/venvs/gpumoloco/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 905, in run
    run_metadata_ptr)
  File "/var/lib/jenkins/venvs/gpumoloco/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1140, in _run
    feed_dict_tensor, options, run_metadata)
  File "/var/lib/jenkins/venvs/gpumoloco/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    run_metadata)
  File "/var/lib/jenkins/venvs/gpumoloco/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: cudnn PoolForward launch failed
	 [[Node: dnn/input_from_feature_columns_2/max_pooling1d/MaxPool = MaxPool[T=DT_FLOAT, data_format="NCHW", ksize=[1, 1, 1, 3], padding="SAME", strides=[1, 1, 1, 3], _device="/job:localhost/replica:0/task:0/device:GPU:0"](dnn/input_from_feature_columns_2/max_pooling1d/MaxPool-0-TransposeNHWCToNCHW-LayoutOptimizer)]]
	 [[Node: dnn/gradients/dnn/input_from_feature_columns_2/input_layer/b_media_appbundle_format_embedding/b_media_appbundle_format_embedding_weights_grad/Select_1/_313 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1344_...d/Select_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op u'dnn/input_from_feature_columns_2/max_pooling1d/MaxPool', defined at:
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/data2/jenkins/src/marvel2/python/moloco/deploy/models/tf_dnn/training/main/task.py", line 66, in <module>
    tf.app.run()
  File "/var/lib/jenkins/venvs/gpumoloco/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "/data2/jenkins/src/marvel2/python/moloco/deploy/models/tf_dnn/training/main/task.py", line 61, in main
    t.train_eval()
  File "/data2/jenkins/src/marvel2/python/moloco/learn/training/trainer.py", line 127, in train_eval
    self.model.train_eval(config, model_dir, train_data, eval_data)
  File "/data2/jenkins/src/marvel2/python/moloco/learn/models/tf_deep.py", line 170, in train_eval
    training.train_and_evaluate(m, train_spec, eval_spec)
  File "/data2/jenkins/src/marvel2/python/moloco/learn/estimators/training.py", line 401, in train_and_evaluate
    executor.run_local()
  File "/data2/jenkins/src/marvel2/python/moloco/learn/estimators/training.py", line 572, in run_local
    self._estimator.train(input_fn=self._train_spec.input_fn, max_steps=max_steps, hooks=train_hooks)
  File "/var/lib/jenkins/venvs/gpumoloco/local/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 355, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/var/lib/jenkins/venvs/gpumoloco/local/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 824, in _train_model
    features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
  File "/var/lib/jenkins/venvs/gpumoloco/local/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 805, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/data2/jenkins/src/marvel2/python/moloco/learn/estimators/dnn.py", line 466, in _model_fn
    config=config)
  File "/data2/jenkins/src/marvel2/python/moloco/learn/estimators/dnn.py", line 224, in _dnn_model_fn
    last_layer_feats=ll_feats.values())
  File "/data2/jenkins/src/marvel2/python/moloco/learn/estimators/logit_ops.py", line 301, in build_dnn_logits
    last_layer_feats=last_layer_feats)
  File "/data2/jenkins/src/marvel2/python/moloco/learn/estimators/logit_ops.py", line 206, in build_hidden_layers
    net = apply_pooling(net, pooling, pooling_size, pooling_stride)
  File "/data2/jenkins/src/marvel2/python/moloco/learn/estimators/logit_ops.py", line 343, in apply_pooling
    o = tf.layers.max_pooling1d(o, pooling_size, strides=pooling_stride, padding="same")
  File "/var/lib/jenkins/venvs/gpumoloco/local/lib/python2.7/site-packages/tensorflow/python/layers/pooling.py", line 231, in max_pooling1d
    return layer.apply(inputs)
  File "/var/lib/jenkins/venvs/gpumoloco/local/lib/python2.7/site-packages/tensorflow/python/layers/base.py", line 825, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "/var/lib/jenkins/venvs/gpumoloco/local/lib/python2.7/site-packages/tensorflow/python/layers/base.py", line 714, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/var/lib/jenkins/venvs/gpumoloco/local/lib/python2.7/site-packages/tensorflow/python/layers/pooling.py", line 86, in call
    data_format=data_format)
  File "/var/lib/jenkins/venvs/gpumoloco/local/lib/python2.7/site-packages/tensorflow/python/ops/nn_ops.py", line 2144, in max_pool
    name=name)
  File "/var/lib/jenkins/venvs/gpumoloco/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 4587, in max_pool
    data_format=data_format, name=name)
  File "/var/lib/jenkins/venvs/gpumoloco/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/var/lib/jenkins/venvs/gpumoloco/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3290, in create_op
    op_def=op_def)
  File "/var/lib/jenkins/venvs/gpumoloco/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1654, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InternalError (see above for traceback): cudnn PoolForward launch failed
	 [[Node: dnn/input_from_feature_columns_2/max_pooling1d/MaxPool = MaxPool[T=DT_FLOAT, data_format="NCHW", ksize=[1, 1, 1, 3], padding="SAME", strides=[1, 1, 1, 3], _device="/job:localhost/replica:0/task:0/device:GPU:0"](dnn/input_from_feature_columns_2/max_pooling1d/MaxPool-0-TransposeNHWCToNCHW-LayoutOptimizer)]]
	 [[Node: dnn/gradients/dnn/input_from_feature_columns_2/input_layer/b_media_appbundle_format_embedding/b_media_appbundle_format_embedding_weights_grad/Select_1/_313 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1344_...d/Select_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

INFO:root:RETURN CODES: 1
```

### Source code / logs

Here are my codes:

```python
def apply_pooling(inputs, pooling, pooling_size, pooling_stride):
  """Apply pooling operations on inputs tensor.

  Args:
    inputs: A tensor with at least 3 rank.
    pooling: When not `None`, `max` means max pooling, and `average` means average pooling.
    pooling_size: The pooling size in all spatial dimensions.
    pooling_stride: The stride operation size in all spatial dimensions.

  Returns:
    A tensors after applying for pooling strategy.
  """
  if pooling is None or pooling == Pooling.NONE:
    return inputs

  # Expand dimension if inputs has not enough rank
  ndims = len(inputs.get_shape().as_list())
  if ndims == 1:
    raise ValueError("inputs must be at least rank 2. Given it's {}".format(ndims))
  o = inputs
  if ndims == 2:
    o = tf.expand_dims(o, -1)
  # TODO: fix the issue of not being able to run pooling in GPU
  if pooling == Pooling.MAX:
    o = tf.layers.max_pooling1d(o, pooling_size, strides=pooling_stride, padding="same")
  elif pooling == Pooling.AVERAGE:
    o = tf.layers.average_pooling1d(o, pooling_size, strides=pooling_stride, padding="same")
  else:
    raise ValueError("Unsupported pooling strategy: {}".format(pooling))
  # Squeeze dimenion if necessary
  if ndims == 2:
    o = tf.squeeze(o, -1)
  return o
```

**Comment by tensorflowbutler** [comment]
Nagging Assignee @robieta: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @robieta: It has been 30 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @robieta: It has been 45 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by CZWin32768** [comment]
I encountered the same problem😣

**Comment by CZWin32768** [comment]
@simon-moloco I've solved this problem by `pip install tf-nightly-gpu`. This may help.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @robieta: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @robieta: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @robieta: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @robieta: It has been 59 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @robieta: It has been 74 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @robieta: It has been 89 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @robieta: It has been 104 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @robieta: It has been 119 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @robieta: It has been 134 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by wendli01** [comment]
For me an arbitrary combination of reinstalling tensorflow and/or CUDNN and/or CUDA solved the problem unreliably.

However `tf.reset_default_graph()` fixes it every time. 
This can happen when some zombie process (invisible in nvidia-smi) has some memory allocated on the GPU.

Environment info

- Tensorflow 1.10.1
- Python 3.6.6
- CUDA 10.0
- cuDNN 7.3.1
- Nvidia Driver 410.78
- OS: Ubuntu 18.04 LTS
- GPU: GeForce RTX 2080ti

**Comment by wendli01** [comment]
I have the same problem with MaxPooling directly after input (`tf.reshape`). This happens only with CUDA 10, but multiple versions of tensorflow (1.13 nightly, 1.10 stable).

Any updates @simon-moloco ?

**Comment by Amahsa** [comment]
> 
> 
> @simon-moloco I've solved this problem by `pip install tf-nightly-gpu`. This may help.

and where you used it ?

**Comment by TinyGrass** [comment]
I met this problem too. I resolved it by using 'sudo' when running tf code.
I am not sure what exactly happened, but it works.

**Comment by bbrito** [comment]
Is this problem fixed in any of the current Tensorflow versions? For instance, 1.15.0?

**Comment by zh794390558** [comment]
Does this solved?

**Comment by benlcb** [comment]
> Does this solved?

No

**Comment by rmothukuru** [comment]
@simon-moloco,
Sorry for the delayed response. Your code could be executed with **`GPU`**, successfully, with **`Tensorflow Version, 2.4.1`** . Please find [the Gist](https://colab.research.google.com/gist/rmothukuru/88da49b94d0776944ed504c05067dece/gh_19567.ipynb) of the working code. Thanks!
