### ISSUE TITLE
Can any one help me in resolving this issue?? I'm using keras and tensorflow

### ISSUE THREAD

**Issue by Devil369** [tensorflow/tensorflow#19582]
Using TensorFlow backend.
Traceback (most recent call last):
  File "app.py", line 32, in <module>
    model, graph = init()
  File "/home/jitendra/cnn-hand-written-digit-master/model/load.py", line 12, in init
    loaded_model = model_from_json(loaded_model_json)
  File "build/bdist.linux-x86_64/egg/keras/engine/saving.py", line 369, in model_from_json
  File "build/bdist.linux-x86_64/egg/keras/layers/__init__.py", line 55, in deserialize
  File "build/bdist.linux-x86_64/egg/keras/utils/generic_utils.py", line 145, in deserialize_keras_object
  File "build/bdist.linux-x86_64/egg/keras/engine/sequential.py", line 293, in from_config
  File "build/bdist.linux-x86_64/egg/keras/engine/sequential.py", line 166, in add
  File "build/bdist.linux-x86_64/egg/keras/engine/base_layer.py", line 414, in __call__
  File "build/bdist.linux-x86_64/egg/keras/engine/base_layer.py", line 279, in assert_input_compatibility
  File "build/bdist.linux-x86_64/egg/keras/backend/tensorflow_backend.py", line 469, in is_keras_tensor
  File "build/bdist.linux-x86_64/egg/keras/backend/tensorflow_backend.py", line 477, in is_tensor
AttributeError: 'module' object has no attribute '_TensorLike'

**Comment by unnir** [comment]
I guess it has nothing to do with the tensorflow repo. I would recommend to ask this question on stackoverflow.

**Comment by angersson** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) (thanks @unnir!) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
