### ISSUE TITLE
Tensorflow Lite NNAPI doesn't work

### ISSUE THREAD

**Issue by efeiefei** [tensorflow/tensorflow#19620]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Android armeabi-v7a
- **TensorFlow installed from (source or binary)**: no
- **TensorFlow version (use command below)**: no
- **Python version**:  no
- **Bazel version (if compiling from source)**: no
- **GCC/Compiler version (if compiling from source)**: no
- **CUDA/cuDNN version**: no
- **GPU model and memory**: no
- **Exact command to reproduce**: no

### Describe the problem
I build a graph with simple matmul and reshap ops, and compile android apk with nigthly-build `org.tensorflow:tensorflow-lite:0.1.7'`. Then run the app in Android 8.1 devices.
If I `setUseNNAPI(false)`, its' result is rigth. However, when I `setUseNNAPI(true)`, it excute very fast and its result is wrong (it outputs whatever I feed inputs).

Can anyone help me ?

**Comment by efeiefei** [comment]
When it runs, the device GPU utilization is 0

**Comment by zhongleiwang** [comment]
check your device indeed support NNAPI.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @aselle: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @aselle: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by anonym24** [comment]
Can you add some Toast message (for Tensorflow Lite samples) that will tell if device supports NNAPI?

**Comment by anonym24** [comment]
For me it just crashes on Xiaomi 8.1 Redmi Note 5. Mb device doesn't support NNAPI - suitable hardware needed for that.. I guess. But why does it crash? Why not just use CPU fallback?

Also would be great to have some function which will tell us if NNAPI is supported by device. 

```
2018-10-08 17:30:36.273 21069-21493/com.tes E/tflite: Custom operations are not supported when using NNAPI.
2018-10-08 17:30:36.273 21069-21493/com.tes E/tflite: Returning error since TFLite returned failure nnapi_delegate.cc:745.
2018-10-08 17:30:36.273 21069-21493/com.tes E/tflite: Failed to build graph for NNAPI
2018-10-08 17:30:36.274 21069-21493/com.tes E/AndroidRuntime: FATAL EXCEPTION: Thread-4
    Process: com.tes, PID: 21069
    java.lang.IllegalArgumentException: Internal error: Failed to run on the given Interpreter: 
        at org.tensorflow.lite.NativeInterpreterWrapper.run(Native Method)
        at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:130)
        at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:216)
        at com.tes.Lite.TFLiteObjectDetection.recognizeImage(TFLiteObjectDetection.java:226)
        at com.tes.Lite.NeuralNet.detect(NeuralNet.java:82)
        at com.tes.camera.JavaCameraView$CameraWorker.run(JavaCameraView.java:395)
        at java.lang.Thread.run(Thread.java:764)

```

**Comment by zishanahmed08** [comment]
@anonym24 - Where you able to fix it? I face the same error

**Comment by anonym24** [comment]
@anonym24 no, I just don't use NNAPI (GPU acceleration), seems it works only with Google Devices (Nexus, Pixel)
