### ISSUE TITLE
bazel build libtensorflow_inference.so failed

### ISSUE THREAD

**Issue by manlok1992** [tensorflow/tensorflow#19685]
I try to put this `TensorFlow` to Unity for Android. I built the aar file in Android Studio. But I got below error.<br>

> 06-01 16:38:34.341  4137  4154 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: No OpKernel was registered to support Op 'All' with these attrs.  Registered devices: [CPU], Registered kernels:
06-01 16:38:34.341  4137  4154 E AndroidRuntime:   <no registered kernels>
06-01 16:38:34.341  4137  4154 E AndroidRuntime: 
06-01 16:38:34.341  4137  4154 E AndroidRuntime: 	 [[Node: assert_equal/All = All[Tidx=DT_INT32, keep_dims=false](assert_equal/Equal, assert_equal/Const)]]
06-01 16:38:34.341  4137  4154 E AndroidRuntime: 	at org.tensorflow.Session.run(Native Method)
06-01 16:38:34.341  4137  4154 E AndroidRuntime: 	at org.tensorflow.Session.access$100(Session.java:48)
06-01 16:38:34.341  4137  4154 E AndroidRuntime: 	at org.tensorflow.Session$Runner.runHelper(Session.java:285)
06-01 16:38:34.341  4137  4154 E AndroidRuntime: 	at org.tensorflow.Session$Runner.run(Session.java:235)
06-01 16:38:34.341  4137  4154 E AndroidRuntime: 	at org.tensorflow.contrib.android.TensorFlowInferenceInterface.run(TensorFlowInferenceInterface.java:142)
06-01 16:38:34.341  4137  4154 E AndroidRuntime: 	at org.tensorflow.demo.TensorFlowObjectDetectionAPIModel.recognizeImage(TensorFlowObjectDetectionAPIModel.java:158)
06-01 16:38:34.341  4137  4154 E AndroidRuntime: 	at org.tensorflow.demo.DetectorActivity$3.run(DetectorActivity.java:289)
06-01 16:38:34.341  4137  4154 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
06-01 16:38:34.341  4137  4154 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
06-01 16:38:34.341  4137  4154 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
06-01 16:38:34.341  4137  4154 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:61)

Do anyone know how to resolve it?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by manlok1992** [comment]
Have I written custom code: NO
OS Platform and Distribution: MacOS
TensorFlow installed from: source
TensorFlow version: 1.8
Bazel version: Build label: 0.13.1-homebrew
CUDA/cuDNN version: NA
GPU model and memory: NA
Exact command to reproduce: NA

I just know I don't build the `jar` file for Android.
So I try to follow the instruction to build the `libtensorflow_inference.so`.  But I got a error.

> ERROR: /private/var/tmp/_bazel_manlokwong/dc8d33585d6d4874e40cf9ad36bf2389/external/protobuf_archive/BUILD:265:1: Executing genrule @protobuf_archive//:generate_js_well_known_types_embed failed (Exit 126)
/bin/bash: bazel-out/armeabi-v7a-opt/bin/external/protobuf_archive/js_embed: cannot execute binary file
Target //tensorflow/contrib/android:libtensorflow_inference.so failed to build
Use --verbose_failures to see the command lines of failed build steps.

**Comment by karmel** [comment]
@andrehentz - any insight on how to build this package?

**Comment by tensorflowbutler** [comment]
Nagging Assignee @andrehentz: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @andrehentz: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @andrehentz: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by pramenku** [comment]
I am also seeing similar kind of issues. Can someone help.
 $ pip3 list | grep -i protobuf
 protobuf 3.5.1
 Bazel version is 0.15.2
 tf1.8
 OS: Ubuntu16.04.4
 Python : 3.5.2

INFO: Found 1 target...
 ERROR: /home/taccuser/.cache/bazel/_bazel_taccuser/cbc64142ddf66660b02ff669605f4d7f/external/protobuf_archive/BUILD:265:1: Executing genrule @protobuf_archive//:generate_js_well_known_types_embed failed (Aborted): bash failed: error executing command
 (cd /home/taccuser/.cache/bazel/_bazel_taccuser/cbc64142ddf66660b02ff669605f4d7f/execroot/org_tensorflow && 
 exec env - 
 LD_LIBRARY_PATH=/usr/local/lib:/usr/local/mpi/lib:/usr/local/lib:/usr/local/mpi/lib: 
 PATH=/opt/rocm/hcc/bin:/opt/rocm/hip/bin:/opt/rocm/hcc/bin:/opt/rocm/hip/bin:/home/taccuser/bin:/home/taccuser/.local/bin:/usr/local/mpi/bin:/home/taccuser/bin:/home/taccuser/.local/bin:/usr/local/mpi/bin:/home/taccuser/bin:/home/taccuser/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin 
 /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; bazel-out/host/bin/external/protobuf_archive/js_embed external/protobuf_archive/src/google/protobuf/compiler/js/well_known_types/any.js external/protobuf_archive/src/google/protobuf/compiler/js/well_known_types/struct.js external/protobuf_archive/src/google/protobuf/compiler/js/well_known_types/timestamp.js > bazel-out/host/genfiles/external/protobuf_archive/src/google/protobuf/compiler/js/well_known_types_embed.cc'): bash failed: error executing command
 (cd /home/taccuser/.cache/bazel/_bazel_taccuser/cbc64142ddf66660b02ff669605f4d7f/execroot/org_tensorflow && 
 exec env - 
 LD_LIBRARY_PATH=/usr/local/lib:/usr/local/mpi/lib:/usr/local/lib:/usr/local/mpi/lib: 
 PATH=/opt/rocm/hcc/bin:/opt/rocm/hip/bin:/opt/rocm/hcc/bin:/opt/rocm/hip/bin:/home/taccuser/bin:/home/taccuser/.local/bin:/usr/local/mpi/bin:/home/taccuser/bin:/home/taccuser/.local/bin:/usr/local/mpi/bin:/home/taccuser/bin:/home/taccuser/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin 
 /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; bazel-out/host/bin/external/protobuf_archive/js_embed external/protobuf_archive/src/google/protobuf/compiler/js/well_known_types/any.js external/protobuf_archive/src/google/protobuf/compiler/js/well_known_types/struct.js external/protobuf_archive/src/google/protobuf/compiler/js/well_known_types/timestamp.js > bazel-out/host/genfiles/external/protobuf_archive/src/google/protobuf/compiler/js/well_known_types_embed.cc')
 /bin/bash: line 1: 15045 Aborted (core dumped) bazel-out/host/bin/external/protobuf_archive/js_embed external/protobuf_archive/src/google/protobuf/compiler/js/well_known_types/any.js external/protobuf_archive/src/google/protobuf/compiler/js/well_known_types/struct.js external/protobuf_archive/src/google/protobuf/compiler/js/well_known_types/timestamp.js > bazel-out/host/genfiles/external/protobuf_archive/src/google/protobuf/compiler/js/well_known_types_embed.cc
 Target //tensorflow/tools/pip_package:build_pip_package failed to build
 INFO: Elapsed time: 1.329s, Critical Path: 0.65s
 INFO: 12 processes: 12 local.
 FAILED: Build did NOT complete successfully

**Comment by tensorflowbutler** [comment]
Nagging Assignee @andrehentz: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @andrehentz: It has been 30 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @andrehentz: It has been 46 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @andrehentz: It has been 61 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @andrehentz: It has been 76 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @andrehentz: It has been 91 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @andrehentz: It has been 106 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by jdduke** [comment]
Please reopen if this is still an issue, I haven't observed this in more recent builds.
