### ISSUE TITLE
feature request: tf.string_split cannot split more than twice, when the maxlengths are not same

### ISSUE THREAD

**Issue by ZhuoyuWei** [tensorflow/tensorflow#19686]
------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Windows10
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**:1.7
- **Python version**: 3.6.2
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: CUDA 9.0 / cuDNN7
- **GPU model and memory**:  NVIDIA Quadro K620
- **Exact command to reproduce**:

### Describe the problem
I used Dataset API to process NLP task.
In input function, I have a string col, which contains three kinds of  delimiter '\1', '\2', ' '.
For example, the string is a ducument, the '\1' is used to split passages and '\2' is used to split sentecnes and ' ' is used to split tokens(words).
I want to split it into a 3-D tensor, whose shape may be [None,None,None], and before the data is truly read, these three numbers cannot be determined.

Firstly, I try the following code to directly call tf.string_split three times:
```python 
#parsed_line[4] is the string col, Tensor("DecodeCSV:5", shape=(), dtype=string)
parsed_line[4]=tf.string_split([parsed_line[4]],delimiter='\2').values
parsed_line[4]=tf.string_split(parsed_line[4],delimiter='\1').values
parsed_line[4]=tf.string_split(parsed_line[4],delimiter=' ')
parsed_line[4]=tf.sparse_tensor_to_dense(parsed_line[4], default_value = "")
#after processing, parsed_line[4] is Tensor("SparseToDense_2:0", shape=(?, ?), dtype=string)
```
However, I want to get [None,None,None], but not [None,None], because it loss the information which passage the sencences are belong to.

Secondly, I try tf.map_fn as follows:
```python
parsed_line[4]=tf.string_split([parsed_line[4]],delimiter='\2').values
parsed_line[4]=tf.string_split(parsed_line[4],delimiter='\1')
parsed_line[4]=tf.SparseTensor(parsed_line[4].indices,tf.map_fn(tf.string_split,[parsed_line[4].values]),parsed_line[4].dense_shape)
parsed_line[4]=tf.sparse_tensor_to_dense(parsed_line[4], default_value = "")
```
Then it will throw out the following errors:
```
Traceback (most recent call last):
  File "D:/PythonProjects/PhillyNNFramework/p_data_func/LSATInput.py", line 179, in <module>
    first_batch = sess.run(binput.input_fn(r'D:\Datadump\LSAT\debug_data\test_tsv.tsv','train'))
  File "D:/PythonProjects/PhillyNNFramework/p_data_func/LSATInput.py", line 109, in train_input
    .map(lambda x: decode_tsv_indexing(x)))
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 838, in map
    return MapDataset(self, map_func)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 1826, in __init__
    self._map_func.add_to_graph(ops.get_default_graph())
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\function.py", line 488, in add_to_graph
    self._create_definition_if_needed()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\function.py", line 321, in _create_definition_if_needed
    self._create_definition_if_needed_impl()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\function.py", line 338, in _create_definition_if_needed_impl
    outputs = self._func(*inputs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 1791, in tf_map_func
    ret = map_func(nested_args)
  File "D:/PythonProjects/PhillyNNFramework/p_data_func/LSATInput.py", line 109, in <lambda>
    .map(lambda x: decode_tsv_indexing(x)))
  File "D:/PythonProjects/PhillyNNFramework/p_data_func/LSATInput.py", line 54, in decode_tsv_indexing
    parsed_line[4]=tf.SparseTensor(parsed_line[4].indices,tf.map_fn(tf.string_split,[parsed_line[4].values]),parsed_line[4].dense_shape)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\functional_ops.py", line 413, in map_fn
    swap_memory=swap_memory)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 3202, in while_loop
    result = loop_context.BuildLoop(cond, body, loop_vars, shape_invariants)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 2940, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 2877, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\functional_ops.py", line 404, in compute
    nest.assert_same_structure(dtype or elems, packed_fn_values)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\util\nest.py", line 267, in assert_same_structure
    _recursive_assert_same_structure(nest1, nest2, check_types)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\util\nest.py", line 193, in _recursive_assert_same_structure
    "First structure: %s\n\nSecond structure: %s." % (nest1, nest2))
ValueError: The two structures don't have the same nested structure.

First structure: [tf.string]

Second structure: SparseTensor(indices=Tensor("map/while/StringSplit:0", shape=(?, 2), dtype=int64), values=Tensor("map/while/StringSplit:1", shape=(?,), dtype=string), dense_shape=Tensor("map/while/StringSplit:2", shape=(2,), dtype=int64)).

Process finished with exit code 1
```
I think it is caused by the lengths (the last dimensionality) of each sentence are different.

To valid my guess, I split this col to 5 cols in the input file, and I run tf.string_split on each of them to get [None,None] tensor, and finally, I try to stack them int one tensor [None,None,None]
```python
for i in range(4,9):
    parsed_line[i] = tf.string_split([parsed_line[i]], delimiter='\1').values
    parsed_line[i] = tf.string_split(parsed_line[i])
    parsed_line[i] = tf.sparse_tensor_to_dense(parsed_line[i], default_value="")
parsed_line[4]=tf.stack(parsed_line[4:9])
```
Yes, it throws an error:
```
2018-06-01 17:41:31.412421: W T:\src\github\tensorflow\tensorflow\core\framework\op_kernel.cc:1273] OP_REQUIRES failed at iterator_ops.cc:891 : Invalid argument: Shapes of all inputs must match: values[0].shape = [2,31] != values[1].shape = [2,35]
	 [[Node: stack = Pack[N=5, T=DT_STRING, axis=0](SparseToDense_2, SparseToDense_3, SparseToDense_4, SparseToDense_5, SparseToDense_6)]]
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1327, in _do_call
    return fn(*args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1312, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1420, in _call_tf_sessionrun
    status, run_metadata)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Shapes of all inputs must match: values[0].shape = [2,31] != values[1].shape = [2,35]
	 [[Node: stack = Pack[N=5, T=DT_STRING, axis=0](SparseToDense_2, SparseToDense_3, SparseToDense_4, SparseToDense_5, SparseToDense_6)]]
	 [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[?,?,?], [?,5,?,?], [?,?], [?,?,?], [?,?], [?]], output_types=[DT_STRING, DT_STRING, DT_STRING, DT_STRING, DT_STRING, DT_INT32], _device="/job:localhost/replica:0/task:0/device:CPU:0"](OneShotIterator)]]

```
When truly read the input data, two sentences has 31 tokens and 35 tokens, respectively.
Finally, I try to pad them dynamically as follows:
```python
for i in range(4,9):
    parsed_line[i] = tf.string_split([parsed_line[i]], delimiter='\1').values
    parsed_line[i] = tf.string_split(parsed_line[i])
    parsed_line[i] = tf.sparse_tensor_to_dense(parsed_line[i], default_value="")

shape_list=[]
for i in range(4, 9):
    tmp=tf.convert_to_tensor(parsed_line[i].shape,dtype=None)
    shape_list.append(tmp)
shape_stack=tf.stack(shape_list)
maxs=tf.reduce_max(shape_stack,0)
for i in range(4,9):
    paddings=tf.stack([tf.constant([0,0],dtype='int32'),maxs-parsed_line[i].shape])
    parsed_line[i]=tf.pad(parsed_line[i],paddings,"CONSTANT")
parsed_line[4]=tf.stack(parsed_line[4:9])
```
This code throws the following erros:
```
Traceback (most recent call last):
  File "D:/PythonProjects/PhillyNNFramework/p_data_func/LSATInput.py", line 175, in <module>
    first_batch = sess.run(binput.input_fn(r'D:\Datadump\LSAT\debug_data\test_tsv.tsv','train'))
  File "D:/PythonProjects/PhillyNNFramework/p_data_func/LSATInput.py", line 105, in train_input
    .map(lambda x: decode_tsv_indexing(x)))
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 838, in map
    return MapDataset(self, map_func)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 1826, in __init__
    self._map_func.add_to_graph(ops.get_default_graph())
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\function.py", line 488, in add_to_graph
    self._create_definition_if_needed()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\function.py", line 321, in _create_definition_if_needed
    self._create_definition_if_needed_impl()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\function.py", line 338, in _create_definition_if_needed_impl
    outputs = self._func(*inputs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 1791, in tf_map_func
    ret = map_func(nested_args)
  File "D:/PythonProjects/PhillyNNFramework/p_data_func/LSATInput.py", line 105, in <lambda>
    .map(lambda x: decode_tsv_indexing(x)))
  File "D:/PythonProjects/PhillyNNFramework/p_data_func/LSATInput.py", line 71, in decode_tsv_indexing
    tmp=tf.convert_to_tensor(parsed_line[i].shape,dtype=None)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 950, in convert_to_tensor
    as_ref=False)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1040, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\constant_op.py", line 256, in _tensor_shape_tensor_conversion_function
    "Cannot convert a partially known TensorShape to a Tensor: %s" % s)
ValueError: Cannot convert a partially known TensorShape to a Tensor: (?, ?)
```
"Cannot convert a partially known TensorShape to a Tensor: (?, ?)"
Thus, I don't know whether there is other methods to solve my problems.

Thanks.

**Comment by ZhuoyuWei** [comment]
Solve it by changing x.shape to tf.shape(x), and I close the issue. Sorry for trouble.
