### ISSUE TITLE
ppc64le: //tensorflow/contrib/distributions:sinh_arcsinh_bijector_test test fails

### ISSUE THREAD

**Issue by wdirons** [tensorflow/tensorflow#19694]
Please assign this issue to me and add the tag: stat:community support

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes, Have written a Dockerfile.gpu.ppc64le file and modified ci_parameterized_build.sh to allow for build/test runs on ppc64le. (Will submit as a PR)
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: ppc64le Ubuntu 16.04.4 
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: master from may 30th
- **Python version**:  2.7.12
- **Bazel version (if compiling from source)**: 0.11.0
- **GCC/Compiler version (if compiling from source)**: 5.4.0
- **CUDA/cuDNN version**: 9.2.88, 7
- **GPU model and memory**: 2 P100 GPUs with 16 GB of memory each

- **Exact command to reproduce**:
bazel test --config=cuda -c opt --local_test_jobs=2 --cache_test_results=no --run_under=//tensorflow/tools/ci_build/gpu_build:parallel_gpu_execute //tensorflow/contrib/distributions:sinh_arcsinh_bijector_test

### Describe the problem
```
======================================================================
FAIL: testBijectorOverRange (__main__.SinhArcsinhBijectorTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/distributions/sinh_arcsinh_bijector_test.runfiles/org_tensorflow/tensorflow/contrib/distributions/python/kernel_tests/bijectors/sinh_arcsinh_bijector_test.py", line 163, in testBijectorOverRange
    atol=0.)
  File "/root/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/distributions/sinh_arcsinh_bijector_test.runfiles/org_tensorflow/tensorflow/python/framework/test_util.py", line 1368, in assertAllClose
    self._assertAllCloseRecursive(a, b, rtol=rtol, atol=atol, msg=msg)
  File "/root/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/distributions/sinh_arcsinh_bijector_test.runfiles/org_tensorflow/tensorflow/python/framework/test_util.py", line 1338, in _assertAllCloseRecursive
    path_str))
  File "/root/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/distributions/sinh_arcsinh_bijector_test.runfiles/org_tensorflow/tensorflow/python/framework/test_util.py", line 1273, in _assertArrayLikeAllClose
    a, b, rtol=rtol, atol=atol, err_msg=msg, equal_nan=True)
  File "/usr/local/lib/python2.7/dist-packages/numpy/testing/utils.py", line 1411, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "/usr/local/lib/python2.7/dist-packages/numpy/testing/utils.py", line 762, in assert_array_compare
    chk_same_position(x == -inf, y == -inf, hasval='-inf')
  File "/usr/local/lib/python2.7/dist-packages/numpy/testing/utils.py", line 735, in chk_same_position
    raise AssertionError(msg)
AssertionError:
Not equal to tolerance rtol=0.0001, atol=0
Mismatched value: a is different from b.
x and y -inf location mismatch:
 x: array([[-2.66556, -52.9496],
       [-2.76943, -53.0418],
       [-2.91071, -53.1402],...
 y: array([[  -2.665562,  -52.949618],
       [  -2.769431,  -53.041801],
       [  -2.910706,  -53.140182],...

----------------------------------------------------------------------
Ran 12 tests in 1.492s

FAILED (failures=1)
not close where =  (array([473, 474, 475, ..., 998, 999, 999]), array([1, 1, 1, ..., 1, 0, 1]))
not close lhs =  [-inf -inf -inf ..., -inf -inf -inf]
not close rhs =  [-327.55577066 -328.16256741 -328.76936416 ..., -646.12406241 -357.13107722
 -646.73085916]
not close dif =  [ inf  inf  inf ...,  inf  inf  inf]
not close tol =  [ 0.03275558  0.03281626  0.03287694 ...,  0.06461241  0.03571311
  0.06467309]
dtype = float128, shape = (1000, 2)
================================================================================

```

### Source code / logs
[distributions_sinh_arcsinh_bijector_test.log](https://github.com/tensorflow/tensorflow/files/2063320/distributions_sinh_arcsinh_bijector_test.log)

**Comment by npanpaliya** [comment]
I've a fix for this. Will raise a PR.

**Comment by npanpaliya** [comment]
Raised a PR - https://github.com/tensorflow/tensorflow/pull/19860

**Comment by wdirons** [comment]
I will be retesting this since 19860 is now merged.
