### ISSUE TITLE
ppc64le: //tensorflow/python/kernel_tests:self_adjoint_eig_op_test test fails

### ISSUE THREAD

**Issue by wdirons** [tensorflow/tensorflow#19698]
Please assign this issue to me and add the tag: stat:community support

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes, Have written a Dockerfile.gpu.ppc64le file and modified ci_parameterized_build.sh to allow for build/test runs on ppc64le. (Will submit as a PR)
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: ppc64le Ubuntu 16.04.4 
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: master from may 30th
- **Python version**:  2.7.12
- **Bazel version (if compiling from source)**: 0.11.0
- **GCC/Compiler version (if compiling from source)**: 5.4.0
- **CUDA/cuDNN version**: 9.2.88, 7
- **GPU model and memory**: 2 P100 GPUs with 16 GB of memory each

- **Exact command to reproduce**:
bazel test --config=cuda -c opt --local_test_jobs=2 --cache_test_results=no --run_under=//tensorflow/tools/ci_build/gpu_build:parallel_gpu_execute //tensorflow/python/kernel_tests:self_adjoint_eig_op_test

### Describe the problem
```
======================================================================
FAIL: testMatrixThatFailsWhenFlushingDenormsToZero (__main__.SelfAdjointEigTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/python/kernel_tests/self_adjoint_eig_op_test.runfiles/org_tensorflow/tensorflow/python/kernel_tests/self_adjoint_eig_op_test.py", line 87, in testMatrixThatFailsWhenFlushingDenormsToZero
    np.matmul(v, v.transpose()), np.eye(32, dtype=np.float32), atol=2e-3)
  File "/root/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/python/kernel_tests/self_adjoint_eig_op_test.runfiles/org_tensorflow/tensorflow/python/framework/test_util.py", line 1368, in assertAllClose
    self._assertAllCloseRecursive(a, b, rtol=rtol, atol=atol, msg=msg)
  File "/root/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/python/kernel_tests/self_adjoint_eig_op_test.runfiles/org_tensorflow/tensorflow/python/framework/test_util.py", line 1338, in _assertAllCloseRecursive
    path_str))
  File "/root/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/python/kernel_tests/self_adjoint_eig_op_test.runfiles/org_tensorflow/tensorflow/python/framework/test_util.py", line 1273, in _assertArrayLikeAllClose
    a, b, rtol=rtol, atol=atol, err_msg=msg, equal_nan=True)
  File "/usr/local/lib/python2.7/dist-packages/numpy/testing/utils.py", line 1411, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "/usr/local/lib/python2.7/dist-packages/numpy/testing/utils.py", line 754, in assert_array_compare
    chk_same_position(x_isnan, y_isnan, hasval='nan')
  File "/usr/local/lib/python2.7/dist-packages/numpy/testing/utils.py", line 735, in chk_same_position
    raise AssertionError(msg)
AssertionError:
Not equal to tolerance rtol=1e-06, atol=0.002
Mismatched value: a is different from b.
x and y nan location mismatch:
 x: array([[ nan,  nan,  nan, ...,  nan,  nan,  nan],
       [ nan,  nan,  nan, ...,  nan,  nan,  nan],
       [ nan,  nan,  nan, ...,  nan,  nan,  nan],...
 y: array([[ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  1.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  1., ...,  0.,  0.,  0.],...

----------------------------------------------------------------------
Ran 9 tests in 1.543s

FAILED (failures=1)
not close where =  (array([ 0,  0,  0, ..., 31, 31, 31]), array([ 0,  1,  2, ..., 28, 29, 30]))
not close lhs =  [ nan  nan  nan ...,  nan  nan  nan]
not close rhs =  [ 1.  0.  0. ...,  0.  0.  0.]
not close dif =  [ nan  nan  nan ...,  nan  nan  nan]
not close tol =  [ 0.002001  0.002     0.002    ...,  0.002     0.002     0.002   ]
dtype = float32, shape = (32, 32)
================================================================================

```
### Source code / logs
[self_adjoint_eig_op_test.log](https://github.com/tensorflow/tensorflow/files/2063585/self_adjoint_eig_op_test.log)

**Comment by wdirons** [comment]
@sandipmgiri - Can you look at this issue. Is this another case of needing to disable a denormal_test on the ppc64le platform?

See: https://github.com/tensorflow/tensorflow/issues/11902, fixed by: https://github.com/tensorflow/tensorflow/pull/11939/files

**Comment by sandipmgiri** [comment]
This test is passing for me with CPU support on Ubuntu16.04(ppc64le).
Can you please try re-running the test 3-4 times ?

**Comment by tensorflowbutler** [comment]
Nagging Assignee @aselle: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @aselle: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by wdirons** [comment]
This test was failing on GPU only, but in the most recent master branch code it is working. I don't know what commit fixed it, but the issue is resolved now. Closing.
