### ISSUE TITLE
ppc64le: //tensorflow/python/kernel_tests:conv_ops_test test fails

### ISSUE THREAD

**Issue by wdirons** [tensorflow/tensorflow#19693]
Please assign this issue to me and add the tag: stat:community support

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes, Have written a Dockerfile.gpu.ppc64le file and modified ci_parameterized_build.sh to allow for build/test runs on ppc64le. (Will submit as a PR)
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: ppc64le Ubuntu 16.04.4 
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: master from may 30th
- **Python version**:  2.7.12
- **Bazel version (if compiling from source)**: 0.11.0
- **GCC/Compiler version (if compiling from source)**: 5.4.0
- **CUDA/cuDNN version**: 9.2.88, 7
- **GPU model and memory**: 2 P100 GPUs with 16 GB of memory each

- **Exact command to reproduce**:
bazel test --config=cuda -c opt --local_test_jobs=2 --cache_test_results=no --run_under=//tensorflow/tools/ci_build/gpu_build:parallel_gpu_execute //tensorflow/python/kernel_tests:conv_ops_test

### Describe the problem
```
======================================================================
FAIL: testInceptionFwd_46 (__main__.Conv2DTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/python/kernel_tests/conv_ops_test.runfiles/org_tensorflow/tensorflow/python/framework/test_util.py", line 717, in decorated
    f(self, **kwargs)
  File "/root/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/python/kernel_tests/conv_ops_test.runfiles/org_tensorflow/tensorflow/python/kernel_tests/conv_ops_test.py", line 1842, in Test
    self._CompareFwdValues(input_size, filter_size, [stride, stride], padding)
  File "/root/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/python/kernel_tests/conv_ops_test.runfiles/org_tensorflow/tensorflow/python/kernel_tests/conv_ops_test.py", line 252, in _CompareFwdValues
    self.assertAllClose(values[0], values[i], rtol=1e-5, atol=1e-5)
  File "/root/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/python/kernel_tests/conv_ops_test.runfiles/org_tensorflow/tensorflow/python/framework/test_util.py", line 1368, in assertAllClose
    self._assertAllCloseRecursive(a, b, rtol=rtol, atol=atol, msg=msg)
  File "/root/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/python/kernel_tests/conv_ops_test.runfiles/org_tensorflow/tensorflow/python/framework/test_util.py", line 1338, in _assertAllCloseRecursive
    path_str))
  File "/root/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/python/kernel_tests/conv_ops_test.runfiles/org_tensorflow/tensorflow/python/framework/test_util.py", line 1273, in _assertArrayLikeAllClose
    a, b, rtol=rtol, atol=atol, err_msg=msg, equal_nan=True)
  File "/usr/local/lib/python2.7/dist-packages/numpy/testing/utils.py", line 1411, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "/usr/local/lib/python2.7/dist-packages/numpy/testing/utils.py", line 796, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Not equal to tolerance rtol=1e-05, atol=1e-05
Mismatched value: a is different from b.
(mismatch 26.2006802721%)
 x: array([[[[  9.935687,   9.715093,   9.417497,  10.535542,   9.895369,
            8.248978],
         [ 12.098586,  12.769324,  11.302494,  11.481708,  13.940086,...
 y: array([[[[  9.933954,   9.714816,   9.417538,  10.534116,   9.897067,
            8.247837],
         [ 12.099165,  12.76971 ,  11.302752,  11.482008,  13.93998 ,...

----------------------------------------------------------------------
Ran 72 tests in 22.143s

FAILED (failures=1)

```

### Source code / logs
[conv_ops_test.log](https://github.com/tensorflow/tensorflow/files/2063282/conv_ops_test.log)

**Comment by michaelisard** [comment]
Sorry for the delay. Thanks for taking this on.

**Comment by tensorflowbutler** [comment]
As this issue has invited community support, please remove the assignee. Otherwise, remove the `community support` label. Thank you.

**Comment by tensorflowbutler** [comment]
As this issue has invited community support, please remove the assignee. Otherwise, remove the `community support` label. Thank you.

**Comment by tensorflowbutler** [comment]
As this issue has invited community support, please remove the assignee. Otherwise, remove the `community support` label. Thank you.

**Comment by wdirons** [comment]
Unable to recreate using the new CI/CD process of calling ci_build.sh using the latest master branch of Tensorflow code.

**Comment by tensorflowbutler** [comment]
As this issue has invited community support, please remove the assignee. Otherwise, remove the `community support` label. Thank you.

**Comment by wdirons** [comment]
I think I meant to close it 22 days ago when it wasn't recreating. Anyways, I just double checked and it is passing now. Will close.

```
Target //tensorflow/python/kernel_tests:conv_ops_test up-to-date:
  bazel-bin/tensorflow/python/kernel_tests/conv_ops_test
INFO: Elapsed time: 590.123s, Critical Path: 414.38s
INFO: 4125 processes: 4125 local.
INFO: Build completed successfully, 4345 total actions
//tensorflow/python/kernel_tests:conv_ops_test                           PASSED in 111.8s
  Stats over 4 runs: max = 111.8s, min = 88.9s, avg = 97.6s, dev = 8.6s
  WARNING: //tensorflow/python/kernel_tests:conv_ops_test: Test execution time (88.9s excluding execution overhead) outside of range for LONG tests. Consider setting timeout="moderate" or size="medium".
  WARNING: //tensorflow/python/kernel_tests:conv_ops_test: Test execution time (94.4s excluding execution overhead) outside of range for LONG tests. Consider setting timeout="moderate" or size="medium".
  WARNING: //tensorflow/python/kernel_tests:conv_ops_test: Test execution time (95.2s excluding execution overhead) outside of range for LONG tests. Consider setting timeout="moderate" or size="medium".
  WARNING: //tensorflow/python/kernel_tests:conv_ops_test: Test execution time (111.8s excluding execution overhead) outside of range for LONG tests. Consider setting timeout="moderate" or size="medium".

Executed 1 out of 1 test: 1 test passes.
INFO: Build completed successfully, 4345 total actions
```
