### ISSUE TITLE
Library not loaded: @rpath/libcublas.8.0.dylib when running TF GPU on MacOS 

### ISSUE THREAD

**Issue by JiangHoumin** [tensorflow/tensorflow#19720]
### System information

- **System: Mac OS 10.13.4**:
- **Xcode:9.2 .  Apple LLVM version 9.0.0 (clang-900.0.39.2)**:
- **Cuda:**:
- **nvcc: NVIDIA (R) Cuda compiler driver**:
- **Copyright (c) 2005-2018 NVIDIA Corporation**:
- **Built on Sun_Mar_18_21:08:25_CDT_2018**:
- **Cuda compilation tools, release 9.2, V9.2.64**:
- **cudnn:7.1.4**:
- **gcc g++ : 4.2.1**:

- **Question:**:
When i use anaconda install tensorflow-gpu,the terminal say i was successful! Such as:
Installing collected packages: numpy, six, werkzeug, protobuf, tensorflow-gpu
Successfully installed numpy-1.14.3 protobuf-3.5.2.post1 six-1.11.0 tensorflow-gpu-1.1.0 werkzeug-0.14.1

But when is write "import tensorflow as tf",some erroes is show.

> (tensorflowGPU) jhmdeMacBook-Air:Sources jhm$ python
Python 3.6.5 |Anaconda, Inc.| (default, Apr 26 2018, 08:42:37) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "/Users/jhm/anaconda3/envs/tensorflowGPU/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/Users/jhm/anaconda3/envs/tensorflowGPU/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/Users/jhm/anaconda3/envs/tensorflowGPU/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/Users/jhm/anaconda3/envs/tensorflowGPU/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/Users/jhm/anaconda3/envs/tensorflowGPU/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: dlopen(/Users/jhm/anaconda3/envs/tensorflowGPU/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 10): Library not loaded: @rpath/libcublas.8.0.dylib
  Referenced from: /Users/jhm/anaconda3/envs/tensorflowGPU/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
  Reason: image not found

During handling of the above exception, another exception occurred:

>Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jhm/anaconda3/envs/tensorflowGPU/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/Users/jhm/anaconda3/envs/tensorflowGPU/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 51, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/Users/jhm/anaconda3/envs/tensorflowGPU/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 52, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/Users/jhm/anaconda3/envs/tensorflowGPU/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/Users/jhm/anaconda3/envs/tensorflowGPU/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/Users/jhm/anaconda3/envs/tensorflowGPU/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/Users/jhm/anaconda3/envs/tensorflowGPU/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/Users/jhm/anaconda3/envs/tensorflowGPU/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: dlopen(/Users/jhm/anaconda3/envs/tensorflowGPU/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 10): Library not loaded: @rpath/libcublas.8.0.dylib
  Referenced from: /Users/jhm/anaconda3/envs/tensorflowGPU/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
  Reason: image not found

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

BugLog/tensorflowGPU-01.log

I don't konw what to do!

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
It has been 15 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by gunan** [comment]
We are not supporting GPUs on macos anymore, because apple and nvidia do not provide official support for each other. I will mark this community support.
You may have better luck trying to get support for this from stackoverflow.

**Comment by iRonJ** [comment]
So the cause of this issue is the SIP in Mac OS, basically when python launches, due to SIP, the subprocess of Tensorflow doesn't get passed the environment variable for the library locations, so _pywrap_tensorflow_internal.so as referenced in the error message can't find the library locations.

The solution is to link _pywrap_tensorflow_internal.so so rather than relying on environment variables, it checks the file path directly (in this case looking for /usr/local/cuda/lib/<dylib name>).

The workaround, so you don't have to rebuild everything is to use the command line tool "install_name_tool" to update the object file linking. To do this you just run this command, using the appropriate path for where your tensorflow wheel installed, you'll need to do this for 2 object files actually:
install_name_tool -change @rpath/libcusolver.9.2.dylib /usr/local/cuda/lib/libcusolver.9.2.dylib -change @rpath/libcudart.9.2.dylib /usr/local/cuda/lib/libcudart.9.2.dylib   -change @rpath/libcublas.9.2.dylib /usr/local/cuda/lib/libcublas.9.2.dylib **CHANGETHISPATH**/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so


install_name_tool -change @rpath/libcudart.9.2.dylib /usr/local/cuda/lib/libcudart.9.2.dylib -change @rpath/libcublas.9.2.dylib /usr/local/cuda/lib/libcublas.9.2.dylib -change @rpath/libcudnn.7.dylib /usr/local/cuda/lib/libcudnn.7.dylib -change @rpath/libcufft.9.2.dylib /usr/local/cuda/lib/libcufft.9.2.dylib -change @rpath/libcurand.9.2.dylib /usr/local/cuda/lib/libcurand.9.2.dylib -change @rpath/libcudart.9.2.dylib /usr/local/cuda/lib/libcudart.9.2.dylib  **CHANGETHISPATH**/python3.5/site-packages/tensorflow/libtensorflow_framework.so

The permanent solution seems to be to add a flag to the compile per https://stackoverflow.com/questions/39927235/alternative-for-the-dyld-library-path-trick-since-mac-os-10-11-el-capitan-with-s but I don't know enough about the tensorflow build to say where this needs to go

**Comment by xlla** [comment]
I have encounter similar problem in my hackintosh, I am not sure if it is related to SIP,  while I am use 0x67 in clover config.

the simplest way is : 

export DYLD_LIBRARY_PATH="/usr/local/cuda/lib":$DYLD_LIBRARY_PATH

then everything is fine.

**Comment by tilakrayal** [comment]
@JiangHoumin ,
Could you take a look at this [comment](https://github.com/tensorflow/tensorflow/issues/19720#issuecomment-409439626) with the similar error and let us know if the issue still persists. Thank you!
