### ISSUE TITLE
MyDatasetReaderOp crashes on assertion in tensorflow::core::RefCounted::~RefCounted()

### ISSUE THREAD

**Issue by ilya-edrenkin** [tensorflow/tensorflow#19747]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**:v1.8.0-0-g93bc2e2072 1.8.0
- **Python version**: 3.5
- **Bazel version (if compiling from source)**: Not relevant
- **GCC/Compiler version (if compiling from source)**:g++ (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
- **CUDA/cuDNN version**: 9.0/7.0.5
- **GPU model and memory**:GTX 1080Ti
- **Exact command to reproduce**:

```bash
/usr/bin/c++   -Dexample_EXPORTS  -I/opt/ssd/ilya/temp-environment-for-bugreport/lib/python3.5/site-packages/tensorflow/include -I/opt/ssd/ilya/temp-environment-for-bugreport/lib/python3.5/site-packages/tensorflow/include/external/nsync/public -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC   -std=gnu++11 -o CMakeFiles/example.dir/my-reader-dataset-op.cc.o -c /opt/ssd/ilya/temp/my-reader-dataset-op.cc
/usr/bin/c++  -fPIC -I/opt/ssd/ilya/temp-environment-for-bugreport/lib/python3.5/site-packages/tensorflow/include -I/opt/ssd/ilya/temp-environment-for-bugreport/lib/python3.5/site-packages/tensorflow/include/external/nsync/public -D_GLIBCXX_USE_CXX11_ABI=0  -shared -Wl,-soname,libexample.so -o libexample.so CMakeFiles/example.dir/my-reader-dataset-op.cc.o -L/opt/ssd/ilya/temp-environment-for-bugreport/lib/python3.5/site-packages/tensorflow -ltensorflow_framework 
```

`my-reader-dataset-op.cc` and `my.py` are copied from https://www.tensorflow.org/extend/new_data_formats#writing_a_dataset_for_a_file_format with two small changes in the Python code:
1) The dataset is wrapped into `batch` Dataset (any other wrapper that calls `Unref` in its destructor would work too, e.g. `cache`).
2) The iterator is initialized twice. The crash happens on the re-initialization attempt.

```python3
if __name__ == "__main__":
  # Create a MyReaderDataset and print its elements.
  with tf.Session() as sess:
    dataset = MyReaderDataset()
    dataset = dataset.batch(1)
    iterator = dataset.make_initializable_iterator()
    sess.run([iterator.initializer])
    print("First init OK")
    sess.run([iterator.initializer])
    print("Reinit OK")
    next_element = iterator.get_next()
    try:
      while True:
        print(sess.run(next_element))  # Prints "MyReader!" ten times.
    except tf.errors.OutOfRangeError:
      pass
```

```gdb
First init OK
2018-06-04 14:52:16.062227: F /opt/ssd/ilya/temp-environment-for-bugreport/lib/python3.5/site-packages/tensorflow/include/tensorflow/core/lib/core/refcount.h:79] Check failed: ref_.load() == 0 (1 vs. 0)

Thread 59 "python3" received signal SIGABRT, Aborted.
[Switching to Thread 0x7ff95bfff700 (LWP 24856)]
0x00007ffff7825428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
54	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff7825428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff782702a in __GI_abort () at abort.c:89
#2  0x00007fffa62a1174 in tensorflow::internal::LogMessageFatal::~LogMessageFatal() ()
   from /opt/ssd/ilya/temp-environment-for-bugreport/lib/python3.5/site-packages/tensorflow/python/../libtensorflow_framework.so
#3  0x00007fffe6cf34e4 in tensorflow::core::RefCounted::~RefCounted() () from ./libexample.so
#4  0x00007fffe6cf4670 in tensorflow::DatasetBase::~DatasetBase() () from ./libexample.so
#5  0x00007fffe6cf4a7c in tensorflow::GraphDatasetBase::~GraphDatasetBase() () from ./libexample.so
#6  0x00007fffe6cf25fc in tensorflow::(anonymous namespace)::MyReaderDatasetOp::Dataset::~Dataset() ()
   from ./libexample.so
#7  0x00007fffe6cf262c in tensorflow::(anonymous namespace)::MyReaderDatasetOp::Dataset::~Dataset() ()
   from ./libexample.so
#8  0x00007fffa941529f in tensorflow::(anonymous namespace)::BatchDatasetOp::Dataset::~Dataset() ()
   from /opt/ssd/ilya/temp-environment-for-bugreport/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#9  0x00007fffa9414f3b in tensorflow::(anonymous namespace)::BatchDatasetOp::Dataset::Iterator::~Iterator() ()
   from /opt/ssd/ilya/temp-environment-for-bugreport/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#10 0x00007fffa84387b9 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release() ()
   from /opt/ssd/ilya/temp-environment-for-bugreport/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#11 0x00007fffa945e6b6 in tensorflow::(anonymous namespace)::MakeIteratorOp::Compute(tensorflow::OpKernelContext*) ()
   from /opt/ssd/ilya/temp-environment-for-bugreport/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#12 0x00007fffa664150c in tensorflow::ThreadPoolDevice::Compute(tensorflow::OpKernel*, tensorflow::OpKernelContext*) ()
   from /opt/ssd/ilya/temp-environment-for-bugreport/lib/python3.5/site-packages/tensorflow/python/../libtensorflow_framework.so
#13 0x00007fffa660724d in tensorflow::(anonymous namespace)::ExecutorState::Process(tensorflow::(anonymous namespace)::ExecutorState::TaggedNode, long long) ()
   from /opt/ssd/ilya/temp-environment-for-bugreport/lib/python3.5/site-packages/tensorflow/python/../libtensorflow_framework.so
#14 0x00007fffa65f5fd0 in std::_Function_handler<void (), std::_Bind<std::_Mem_fn<void (tensorflow::(anonymous namespace)::ExecutorState::*)(tensorflow::(anonymous namespace)::ExecutorState::TaggedNode, long long)> (tensorflow::(anonymous namespace)::ExecutorState*, tensorflow::(anonymous namespace)::ExecutorState::TaggedNode, long long)> >::_M_invoke(std::_Any_data const&) ()
   from /opt/ssd/ilya/temp-environment-for-bugreport/lib/python3.5/site-packages/tensorflow/python/../libtensorflow_framework.so
#15 0x00007fffa626d6aa in Eigen::NonBlockingThreadPoolTempl<tensorflow::thread::EigenEnvironment>::WorkerLoop(int) ()
   from /opt/ssd/ilya/temp-environment-for-bugreport/lib/python3.5/site-packages/tensorflow/python/../libtensorflow_framework.so
#16 0x00007fffa626c752 in std::_Function_handler<void (), tensorflow::thread::EigenEnvironment::CreateThread(std::function<void ()>)::{lambda()#1}>::_M_invoke(std::_Any_data const&) ()
   from /opt/ssd/ilya/temp-environment-for-bugreport/lib/python3.5/site-packages/tensorflow/python/../libtensorflow_framework.so
#17 0x00007fff9d36fc80 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#18 0x00007ffff7bc16ba in start_thread (arg=0x7ff95bfff700) at pthread_create.c:333
#19 0x00007ffff78f741d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
(gdb) 
```

It looks like `Unref` in https://github.com/tensorflow/tensorflow/blob/v1.8.0/tensorflow/core/kernels/data/batch_dataset_op.cc#L62 observes ref-count `1` and causes the destructor `MyReaderDatasetOp::Dataset::~Dataset()` to be called via `delete this`: https://github.com/tensorflow/tensorflow/blob/v1.8.0/tensorflow/core/lib/core/refcount.h#L93. However, later in destructor unfolding non-zero count is observed for the same object, which causes assertion failure.

The error doesn't reproduce with built-in datasets, e.g. TextLineReader or RangeDataset. However, if I copy RangeDataset code and rebuild it as MyRangeDataset, it reproduces with exactly the same symptoms.

**Comment by ilya-edrenkin** [comment]
@sjperkins Simon: thanks, that makes perfect sense.

(What happens is: the BatchDatasetOp, compiled with NDEBUG in the stock tensorflow package, doesn't actually decrement the counter when it is equal to 1 and just calls the destructor. MyDatasetOp, compiled without NDEBUG, fails on assertion because the check is not cut out.)
