### ISSUE TITLE
Unity Tensorflow crash

### ISSUE THREAD

**Issue by manlok1992** [tensorflow/tensorflow#19768]
Have I written custom code: NO
OS Platform and Distribution: MacOS
TensorFlow installed from: source
TensorFlow version: 1.8
Bazel version: Build label: 0.13.1-homebrew
CUDA/cuDNN version: NA
GPU model and memory: NA
Exact command to reproduce: NA

I am using the example for Android. I try to build it to `.aar` file. I put the aar file to `Plugins/Android`. And put the .so file to `Assets/Plugins/Android/libs` When I start the apps, I got the crash. 

> 06-05 16:50:17.865 26605 26639 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: No OpKernel was registered to support Op 'All' with these attrs.  Registered devices: [CPU], Registered kernels:
06-05 16:50:17.865 26605 26639 E AndroidRuntime:   <no registered kernels>
06-05 16:50:17.865 26605 26639 E AndroidRuntime: 
06-05 16:50:17.865 26605 26639 E AndroidRuntime: 	 [[Node: assert_equal/All = All[Tidx=DT_INT32, keep_dims=false](assert_equal/Equal, assert_equal/Const)]]
06-05 16:50:17.865 26605 26639 E AndroidRuntime: 	at org.tensorflow.Session.run(Native Method)
06-05 16:50:17.865 26605 26639 E AndroidRuntime: 	at org.tensorflow.Session.access$100(Session.java:48)
06-05 16:50:17.865 26605 26639 E AndroidRuntime: 	at org.tensorflow.Session$Runner.runHelper(Session.java:285)
06-05 16:50:17.865 26605 26639 E AndroidRuntime: 	at org.tensorflow.Session$Runner.run(Session.java:235)
06-05 16:50:17.865 26605 26639 E AndroidRuntime: 	at org.tensorflow.contrib.android.TensorFlowInferenceInterface.run(TensorFlowInferenceInterface.java:142)
06-05 16:50:17.865 26605 26639 E AndroidRuntime: 	at org.tensorflow.demo.TensorFlowObjectDetectionAPIModel.recognizeImage(TensorFlowObjectDetectionAPIModel.java:158)
06-05 16:50:17.865 26605 26639 E AndroidRuntime: 	at org.tensorflow.demo.DetectorActivity$3.run(DetectorActivity.java:289)
06-05 16:50:17.865 26605 26639 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
06-05 16:50:17.865 26605 26639 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
06-05 16:50:17.865 26605 26639 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
06-05 16:50:17.865 26605 26639 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by tensorflowbutler** [comment]
Nagging Assignee @skye: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @skye: It has been 30 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @skye: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @skye: It has been 60 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by asimshankar** [comment]
Not all operations are included in the default builds for TensorFlow Mobile to keep the binary size smaller. You may need to use [selective registration](https://github.com/tensorflow/tensorflow/blob/915cf10d4bcbb51f079f6841aeaf876b430a920b/tensorflow/python/tools/print_selective_registration_header.py#L15) to include the 'All' op and build from source.

Assigning to @petewarden , who I believe might have some pointers on documentation for selective registration (see also #10299)

**Comment by petewarden** [comment]
There's some documentation on the process of adding ops here:
https://www.tensorflow.org/mobile/prepare_models

It's not very easy to do unfortunately, so we are working on improvements for TensorFlow Lite.
