### ISSUE TITLE
 from tensorflow.tools.api.generator.api import *  # pylint: disable=redefined-builtin ImportError: No module named 'tensorflow.tools.api'

### ISSUE THREAD

**Issue by leehomcs** [tensorflow/tensorflow#19765]
I came across this issue when I import tensorflow on a server:
the configurations are as follows:
Ubuntu 16.04.4 LTS
Kernel: 4.13.0-1011
Tensorflow 0.18

>>> import tensorflow
/anaconda/envs/py35/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda/envs/py35/lib/python3.5/site-packages/tensorflow/__init__.py", line 26, in <module>
    from tensorflow.tools.api.generator.api import *  # pylint: disable=redefined-builtin
ImportError: No module named 'tensorflow.tools.api'

Any idea how to solve this problem?  
Thanks!

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
It has been 15 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
It has been 30 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by Nathan-81** [comment]
Well I actually have the same problem what was your solution ?

**Comment by juskuz** [comment]
I get the same error. Any solutions?
I'm using Win 10 with conda.

**Comment by juskuz** [comment]
ok, I downgraded tensorflow to 1.3 and import works
