### ISSUE TITLE
metagraph loading fails with 'No op named ImageProjectiveTransform' message

### ISSUE THREAD

**Issue by akamaus** [tensorflow/tensorflow#19774]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:
binary, installed with pip3
- **TensorFlow version (use command below)**:
v1.8.0-0-g93bc2e2072
- **Python version**: 
3.5

### Describe the problem
I'm trying to load a metagraph file saved with tf-v1.4.0-rc1-11-g130a514. Loading fails with the following error: 

```
  File "/home/vyal/.local/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1955, in import_meta_graph
    **kwargs)
  File "/home/vyal/.local/lib/python3.5/site-packages/tensorflow/python/framework/meta_graph.py", line 743, in import_scoped_meta_graph
    producer_op_list=producer_op_list)
  File "/home/vyal/.local/lib/python3.5/site-packages/tensorflow/python/util/deprecation.py", line 432, in new_func
    return func(*args, **kwargs)
  File "/home/vyal/.local/lib/python3.5/site-packages/tensorflow/python/framework/importer.py", line 460, in import_graph_def
    _RemoveDefaultAttrs(op_dict, producer_op_list, graph_def)
  File "/home/vyal/.local/lib/python3.5/site-packages/tensorflow/python/framework/importer.py", line 227, in _RemoveDefaultAttrs
    op_def = op_dict[node.op]
KeyError: 'ImageProjectiveTransform'
```

I thought it's the result of some backward incompability so I retested on python2.7 and tf-v1.4.0-rc1-11-g130a514. Getting very similar message:

```
In [3]: tf.train.import_meta_graph('00000000000001107000.meta')
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-6d533993d6fe> in <module>()
----> 1 tf.train.import_meta_graph('00000000000001107000.meta')

/home/marin/tensorflow/lib/python2.7/site-packages/tensorflow/python/training/saver.pyc in import_meta_graph(meta_graph_or_file, clear_devices, import_scope, **kwargs)
   1808                                       clear_devices=clear_devices,
   1809                                       import_scope=import_scope,
-> 1810                                       **kwargs)
   1811   if meta_graph_def.HasField("saver_def"):
   1812     return Saver(saver_def=meta_graph_def.saver_def, name=import_scope)

/home/marin/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/meta_graph.pyc in import_scoped_meta_graph(meta_graph_or_file, clear_devices, graph, import_scope, input_map, unbound_inputs_col_name, restore_collections_predicate)
    658     importer.import_graph_def(
    659         input_graph_def, name=(import_scope or ""), input_map=input_map,
--> 660         producer_op_list=producer_op_list)
    661 
    662     scope_to_prepend_to_names = "/".join(

/home/marin/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/importer.pyc in import_graph_def(graph_def, input_map, return_elements, name, op_dict, producer_op_list)
    283       # Set any default attr values that aren't present.
    284       if node.op not in op_dict:
--> 285         raise ValueError('No op named %s in defined operations.' % node.op)
    286       op_def = op_dict[node.op]
    287       for attr_def in op_def.attr:

ValueError: No op named ImageProjectiveTransform in defined operations.
```

**Comment by Jibanprakash** [comment]
Similar error when trying to load a meta file using C++ interface
FYI: https://github.com/tensorflow/tensorflow/issues/17942

`  
        MetaGraphDef graph_def;
        auto session = NewSession(SessionOptions());
        status = ReadBinaryProto(Env::Default(), GRAPH_PATH, &graph_def);
        status = session->Create(graph_def.graph_def());
        if (!status.ok()) {
                **log_err("Error creating graph: %s", status.ToString());**
                return -1;
        }`

**System information**

    TensorFlow build using make 
    built as a static library. **libtensorflow-core.a**

    TensorFlow version (use command below):
    v1.8.0-0

Below are the error message

 Apr 10 16:17:22  E tensorflow/core/framework/op_kernel.cc:1242] OpKernel ('op: "MutableDenseHashTable" device_type: "CPU" constraint { name: "key_
dtype" allowed_values { list { type: DT_INT64 } } } constraint { name: "value_dtype" allowed_values { list { type: DT_DOUBLE } } }') for unknown op: MutableDenseHashTable
Apr 10 16:17:22: E tensorflow/core/framework/op_kernel.cc:1242] OpKernel ('op: "HashTableV2" device_type: "CPU" constraint { name: "key_dtype" all
owed_values { list { type: DT_STRING } } } constraint { name: "value_dtype" allowed_values { list { type: DT_DOUBLE } } }') for unknown op: HashTableV2
pr 10 16:17:22  E tensorflow/core/framework/op_kernel.cc:1242] OpKernel ('op: "LookupTableImportV2" device_type: "CPU"') for unknown op: LookupTa
bleImportV2
Apr 10 16:17:22: E tensorflow/core/framework/op_kernel.cc:1242] OpKernel ('op: "LookupTableImport" device_type: "CPU"') for unknown op: LookupTabl
eImport
Apr 10 16:17:22 : E tensorflow/core/framework/op_kernel.cc:1242] OpKernel ('op: "LookupTableExport" device_type: "CPU"') for unknown op: LookupTabl
eExport
Apr 10 16:17:22 : E tensorflow/core/framework/op_kernel.cc:1242] OpKernel ('op: "LookupTableSize" device_type: "CPU"') for unknown op: LookupTableS
ize
Apr 10 16:17:22 : E tensorflow/core/framework/op_kernel.cc:1242] OpKernel ('op: "LookupTableInsertV2" device_type: "CPU"') for unknown op: LookupTa
bleInsertV2
Apr 10 16:17:22 : E tensorflow/core/framework/op_kernel.cc:1242] OpKernel ('op: "LookupTableInsert" device_type: "CPU"') for unknown op: LookupTabl
eInsert
Apr 10 16:17:22E tensorflow/core/framework/op_kernel.cc:1242] OpKernel ('op: "LookupTableFindV2" device_type: "CPU"') for unknown op: LookupTabl
eFindV2
Apr 10 16:17:22 E tensorflow/core/framework/op_kernel.cc:1242] OpKernel ('op: "LookupTableFind" device_type: "CPU"') for unknown op: LookupTableF
ind

Have checked the tensorflow/contrib/makefile/tf_op_file.txt and all the necessary operation files are available.

**Comment by akamaus** [comment]
I found the culprit. It was call to tf.contrib.image.rotate. Importing tf.contrib.image before loading the metagraph helps.

Looks to me like quite unintuitive behavior.

**Comment by gnthibault** [comment]
Thank you very much @akamaus for sharing the workaround!

**Comment by michaelisard** [comment]
Is it OK to close this issue? I'm not sure what TF would do differently to avoid the problem since ops are loaded on demand.

**Comment by akamaus** [comment]
A warning saying something like 'perhaps you forgot to import contrib module' would have saved a day for me.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @michaelisard: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by martinwicke** [comment]
This will be fixed once we automatically load op libraries from a directory instead of relying on (lazy) python imports to load them. I'm ok with adding a warning as you describe. Happy to approve a PR.

**Comment by tensorflowbutler** [comment]
Please remove the assignee, as this issue is inviting external contributions. Otherwise, remove the `contributions welcome` label. Thank you.

**Comment by tilakrayal** [comment]
@akamaus,
Could you please take a look at this [comment](https://github.com/tensorflow/tensorflow/issues/19774#issuecomment-404689427) from the developer and provide the PR for the same. Thank you!
