### ISSUE TITLE
I have a problem with a script python that launch a choregraphe behavior

### ISSUE THREAD

**Issue by frax9499** [tensorflow/tensorflow#19773]
I have this script write in python 2.7:
from naoqi import ALProxy

tts = ALProxy("ALBehaviorManager", "127.0.0.1" , 9559)
tts.runBehavior("<NomeBehavior>");

when launch this script, however, i have this result:
Traceback (most recent call last):
  File "C:\Users\franc\eclipse-workspace\Connection\src\connection.py", line 7, in <module>
    from naoqi import ALProxy
  File "C:\Program Files (x86)\Aldebaran\Choregraphe 1.14.5.1\lib\naoqi.py", line 14, in <module>
    import _inaoqi_d as _inaoqi
ImportError: DLL load failed: Impossibile trovare il modulo specificato.
Could not find _inaoqi, trying with _inaoqi_d

someone knows how to solve it?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
