### ISSUE TITLE
Documentation code for ScipyOptimizerInterface crashes

### ISSUE THREAD

**Issue by alexis-mignon** [tensorflow/tensorflow#19813]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
I have copied code from the documentation.
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux zenon 4.15.0-22-generic #24-Ubuntu SMP Wed May 16 12:15:17 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
VERSION="18.04 LTS (Bionic Beaver)"
VERSION_ID="18.04"
VERSION_CODENAME=bionic

- **TensorFlow installed from (source or binary)**:
binary using pip
- **TensorFlow version (use command below)**:
tf.VERSION = 1.8.0
tf.GIT_VERSION = v1.8.0-0-g93bc2e2072
tf.COMPILER_VERSION = v1.8.0-0-g93bc2e2072
Sanity check: array([1], dtype=int32)

- **Python version**: 
3.6

- **Bazel version (if compiling from source)**:
N/A
- **GCC/Compiler version (if compiling from source)**:
N/A
- **CUDA/cuDNN version**:
9.0 / 7.1
- **GPU model and memory**:
```
    +-----------------------------------------------------------------------------+
    | NVIDIA-SMI 390.59                 Driver Version: 390.59                    |
    |-------------------------------+----------------------+----------------------+
    | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
    | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
    |===============================+======================+======================|
    |   0  GeForce GTX 965M    Off  | 00000000:01:00.0  On |                  N/A |
    | N/A   43C    P5     8W /  N/A |    379MiB /  2002MiB |      0%      Default |
    +-------------------------------+----------------------+----------------------+
```
- **Exact command to reproduce**:
N/A

### Describe the problem
Example code from the documentation of `tf.contrib.opt.ScipyOptimizerInterface` does not work. Was tried with tensorflow 1.8.0 and 1.7.1 on CPU and GPU.

The code crashed with an exception.

### Source code / logs

The code is mainly copied from [the documentation of ScipyOptimizerInterface](https://www.tensorflow.org/api_docs/python/tf/contrib/opt/ScipyOptimizerInterface), pasted into a file with additionnal imports.

test.py file:
```python
import tensorflow as tf
from tensorflow.contrib.opt import ScipyOptimizerInterface

vector = tf.Variable([7., 7.], 'vector')

# Make vector norm as small as possible.
loss = tf.reduce_sum(tf.square(vector))

optimizer = ScipyOptimizerInterface(loss, options={'maxiter': 100})

with tf.Session() as session:
  optimizer.minimize(session)
```
executed by:

```bash
$ python test.py
```

With the following output:

```
2018-06-06 17:34:36.869162: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Traceback (most recent call last):
  File "/mnt/data/amignon/Projets/mypython3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1322, in _do_call
    return fn(*args)
  File "/mnt/data/amignon/Projets/mypython3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/mnt/data/amignon/Projets/mypython3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value Variable
	 [[Node: Variable/read = Identity[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](Variable)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./test.py", line 12, in <module>
    optimizer.minimize(session)
  File "/mnt/data/amignon/Projets/mypython3/lib/python3.6/site-packages/tensorflow/contrib/opt/python/training/external_optimizer.py", line 195, in minimize
    initial_packed_var_val = session.run(self._packed_var)
  File "/mnt/data/amignon/Projets/mypython3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/mnt/data/amignon/Projets/mypython3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/mnt/data/amignon/Projets/mypython3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/mnt/data/amignon/Projets/mypython3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value Variable
	 [[Node: Variable/read = Identity[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](Variable)]]

Caused by op 'Variable/read', defined at:
  File "./test.py", line 4, in <module>
    vector = tf.Variable([7., 7.], 'vector')
  File "/mnt/data/amignon/Projets/mypython3/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 235, in __init__
    constraint=constraint)
  File "/mnt/data/amignon/Projets/mypython3/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 397, in _init_from_args
    self._snapshot = array_ops.identity(self._variable, name="read")
  File "/mnt/data/amignon/Projets/mypython3/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 142, in identity
    return gen_array_ops.identity(input, name=name)
  File "/mnt/data/amignon/Projets/mypython3/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3187, in identity
    "Identity", input=input, name=name)
  File "/mnt/data/amignon/Projets/mypython3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/mnt/data/amignon/Projets/mypython3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/mnt/data/amignon/Projets/mypython3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

FailedPreconditionError (see above for traceback): Attempting to use uninitialized value Variable
	 [[Node: Variable/read = Identity[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](Variable)]]
```

**Comment by erfan-matroid** [comment]
The problem is that you have not ran the initialization operation before doing the optimization.
If you add `session.run(tf.global_variables_initializer())` before calling `optimizer.minimize(session)` the code will work fine.

**Comment by michaelisard** [comment]
Did that solution work?

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by michaelisard** [comment]
Closing for now due to lack of activity.
