### ISSUE TITLE
Attention Wrapper state error.

### ISSUE THREAD

**Issue by vsai121** [tensorflow/tensorflow#19834]
Hello! I am implementing a seq2seq model with attention for multi-step time series forecasting. I am encountering an error with implementing attention for MultiRNN cell.

System Information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:   Yes , I have attached my code below.

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)** - Linux Ubuntu 16.04

- **TensorFlow installed from (source or binary)**: - Source

- **TensorFlow version (use command below)**: -VERSION = 1.4.1

- **Python version**: 2.7.12

- **Bazel version (if compiling from source)**:  - NA

- **GCC/Compiler version (if compiling from source)**: COMPILER_VERSION = v1.4.0-19-ga52c8d9

- **CUDA/cuDNN version**: - NA

- **GPU model and memory**: - NA

- **Exact command to reproduce**:
I am implementing a seq2seq model with attention for multi-step time series forecasting.

I am facing an issue with attention wrapper state.

My code is given below.

Function for defining the decoder 

    def decoder_network(attention_mechanism,dropout=config.dropout ):
        cells = []
        for i in range(config.num_stacked_layers)
    
            lstm_cell = tf.contrib.rnn.LSTMCell(config.hidden_dim)
            decoder_cell = tf.contrib.seq2seq.AttentionWrapper(lstm_cell, attention_mechanism=attention_mechanism, attention_layer_size=config.hidden_dim)
            cells.append(decoder_cell)
    
    
        cell = tf.contrib.rnn.MultiRNNCell(cells)
        return cell,cells
		
		

Using the above function

    cell,cells = decoder_network(attention_mechanism)
    new_state = cells[0].zero_state(batch_size=batch_size, dtype=tf.float32).clone(cell_state = initial_state)

	for i, inp in enumerate(decoder_inputs):
	      output, new_state = cell(inp, state=new_state)
	

However, I am facing the following error :

    Traceback (most recent call last):
      File "seq2seq.py", line 351, in <module>
        train()
      File "seq2seq.py", line 274, in train
        rnn_model = build_train_graph(feed_previous=True)
      File "seq2seq.py", line 247, in build_train_graph
        dec_outputs, dec_memory = _basic_rnn_seq2seq(enc_inp, dec_inp, cell, Why , by , feed_previous=feed_previous)
      File "seq2seq.py", line 165, in _basic_rnn_seq2seq
        return _rnn_decoder(decoder_inputs, enc_state, attention_mechanism, Why , by ,_loop_function)
      File "seq2seq.py", line 147, in _rnn_decoder
        output, new_state = cell(inp, state=new_state)
      File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/rnn_cell_impl.py", line 183, in __call__
        return super(RNNCell, self).__call__(inputs, state)
      File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/layers/base.py", line 575, in __call__
        outputs = self.call(inputs, *args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/rnn_cell_impl.py", line 1066, in call
        cur_inp, new_state = cell(cur_inp, cur_state)
      File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/rnn_cell_impl.py", line 183, in __call__
        return super(RNNCell, self).__call__(inputs, state)
      File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/layers/base.py", line 575, in __call__
        outputs = self.call(inputs, *args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/seq2seq/python/ops/attention_wrapper.py", line 1289, in call
        "Received type %s instead."  % type(state))
    TypeError: Expected state to be instance of AttentionWrapperState. Received type <class 'tensorflow.python.ops.rnn_cell_impl.LSTMStateTuple'> instead.
    

I have tried printing the type of new state and i got the following type

`    
    ('new_state', AttentionWrapperState(cell_state=(LSTMStateTuple(c=<tf.Tensor 'rnn/rnn/multi_rnn_cell/cell_0/cell_0/lstm_cell/add_9:0' shape=(?, 40) dtype=float32>, h=<tf.Tensor 'rnn/rnn/multi_rnn_cell/cell_0/cell_0/lstm_cell/mul_14:0' shape=(?, 40) dtype=float32>),), attention=<tf.Tensor 'AttentionWrapperZeroState/zeros_1:0' shape=(244, 40) dtype=float32>, time=<tf.Tensor 'AttentionWrapperZeroState/zeros:0' shape=() dtype=int32>, alignments=<tf.Tensor 'AttentionWrapperZeroState/zeros_2:0' shape=(244, 5) dtype=float32>, alignment_history=()))
    `
Even though new state is an instance of AttentionWrapperState it still gives an error.

Thanks in advance for your replies .

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by vsai121** [comment]
Thanks for replying to my issue, I have updated my comment and added more details.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @reedwm: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @ebrevdo: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by ebrevdo** [comment]
@oahziur any chance you could take a look?

**Comment by oahziur** [comment]
@vsai121 

I think you initial state should created from `cell.zero_state(batch_size=batch_size, dtype=tf.float32)` instead of `cells[0].zero_state(batch_size=batch_size, dtype=tf.float32)`. `cells[0]` is just your first rnn layer's cell.

**Comment by nimroha** [comment]
@oahziur I have the same issue
tried your solution `cell.zero_state(batch_size=batch_size, dtype=tf.float32)..clone(cell_state=initial_state)`

got:
AttributeError: 'tuple' object has no attribute 'clone'

---
* tf 1.8 (cpu)
* python 3.5
* ubuntu 16.04

**Comment by nimroha** [comment]
@vsai121 I solved it
in `MultiRNN` `zero_state` is a tuple of the states of each layer. so:

`new_state = tuple([cells.zero_state(batch_size, tf.float32)[i].clone(cell_state=initial_state[i]) for i in range(num_layers)])`

**Comment by ebrevdo** [comment]
We should consider a helper function that uses nest.map_structure to do
this for you.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @ebrevdo: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by ebrevdo** [comment]
For posterity, the most general way to do this is:

```
new_state = tf.contrib.framework.nest.map_structure(
   lambda cell, is: cell.zero_state(batch_size, tf.float32).clone(cell_state=is),
   cells, initial_state)
```
