### ISSUE TITLE
optimize_for_inference_lib.optimize_for_inference produces an invalid graph

### ISSUE THREAD

**Issue by yegord** [tensorflow/tensorflow#19838]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
Yes.
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:
Source.
- **TensorFlow version (use command below)**:
1.8.0
- **Python version**: 
2.7.12
- **Bazel version (if compiling from source)**:
0.13.0
- **GCC/Compiler version (if compiling from source)**:
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9)
- **CUDA/cuDNN version**:
9.0.176/7.0.5.15
- **GPU model and memory**:
1080 Ti
- **Exact command to reproduce**:
```
cat > test.py <<EOF && python test.py
import tensorflow as tf

from collections import namedtuple
from tensorflow.python.tools import optimize_for_inference_lib


def main():
    with tf.Graph().as_default(), tf.Session() as session:
        input = tf.placeholder(shape=[10], dtype=tf.float32)
        output = top_k(input)

        graph_def = session.graph.as_graph_def()

    input_nodes = [input]
    output_nodes = [output.values, output.indices]

    graph_def = tf.graph_util.convert_variables_to_constants(
        session, graph_def, [_get_node_name(t) for t in output_nodes]
    )

    with tf.Graph().as_default():
        tf.import_graph_def(graph_def)  # OK

    graph_def = optimize_for_inference_lib.optimize_for_inference(
        input_graph_def=graph_def,
        input_node_names=[_get_node_name(t) for t in input_nodes],
        output_node_names=[_get_node_name(t) for t in output_nodes],
        placeholder_type_enum=[node.dtype.as_datatype_enum for node in input_nodes]
    )

    with tf.Graph().as_default():
        tf.import_graph_def(graph_def)  # ERROR


TopKResult = namedtuple('TopKResult', ['values', 'indices'])


def top_k(input, k=1, sorted=True, name=None):
    """
    A version of tf.nn.top_k tolerant to k == 0 and k < tf.shape(input)[-1].
    """
    k = tf.minimum(k, tf.shape(input)[-1])

    return tf.cond(
        tf.equal(k, 0),
        lambda: TopKResult(
            values=tf.zeros(
                shape=tf.concat([tf.shape(input)[:-1], [0]], axis=0),
                dtype=input.dtype
            ),
            indices=tf.zeros(
                shape=tf.concat([tf.shape(input)[:-1], [0]], axis=0),
                dtype=tf.int32
            )
        ),
        lambda: TopKResult(**tf.nn.top_k(input, k, sorted, name)._asdict())
    )


def _get_node_name(tensor):
    assert tensor.name.endswith(':0')
    return tensor.name[:-len(':0')]


if __name__ == '__main__':
    main()
EOF
```

### Describe the problem

`optimize_for_inference_lib.optimize_for_inference` produces an invalid graph for the graph generated by the above script. The returned GraphDef cannot be imported:

```
Traceback (most recent call last):
  File "test.py", line 66, in <module>
    main()
  File "test.py", line 32, in main
    tf.import_graph_def(graph_def)  # ERROR
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.py", line 432, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/importer.py", line 493, in import_graph_def
    raise ValueError(str(e))
ValueError: NodeDef expected inputs '' do not match 1 inputs specified; Op<name=Const; signature= -> output:dtype; attr=value:tensor; attr=dtype:type>; NodeDef: import/cond/zeros_1/Const = Const[dtype=DT_INT32, value=Tensor<type: int32 shape: [] values: 0>](import/cond/Switch:1)
```

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatatodd: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatatodd: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatatodd: It has been 46 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatatodd: It has been 60 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by kasyoukin** [comment]
I met the same problem when i use the .pb produced by quantize_graph

**Comment by zh794390558** [comment]
```
$ ./summarize_graph.sh optimized_for_inference_graph.pb
Found 1 possible inputs: (name=input, type=float(1), shape=None)
No variables spotted.
Found 1 possible outputs: (name=softmax_output, op=Softmax)
Found 3156821 (3.16M) const parameters, 0 (0) variable parameters, and 0 control_edges
Op types used: 221 Const, 28 Mul, 27 Reshape, 26 Pack, 25 Add, 18 Sub, 14 ConcatV2, 12 Range, 10 StridedSlice, 10 Cast, 8 Transpose, 8 FloorDiv, 8 GatherV2, 8 Less, 7 Enter, 7 RealDiv, 6 Shape, 6 Prod, 6 MatMul, 5 BiasAdd, 5 Fill, 4 Log, 4 Maximum, 4 ExpandDims, 3 ListDiff, 3 Conv2D, 3 Merge, 3 Select, 3 NextIteration, 3 GreaterEqual, 3 Switch, 2 SplitV, 2 Softmax, 2 Size, 2 Rsqrt, 2 FusedBatchNorm, 2 Pad, 2 Neg, 2 LinSpace, 2 TensorArrayV3, 2 Mean, 2 MaxPool, 1 TensorArrayScatterV3, 1 TensorArrayReadV3, 1 TensorArrayGatherV3, 1 TensorArraySizeV3, 1 Sum, 1 TensorArrayWriteV3, 1 Cos, 1 ComplexAbs, 1 Square, 1 Split, 1 Sigmoid, 1 Exit, 1 FloorMod, 1 RandomStandardNormal, 1 RFFT, 1 Placeholder, 1 PadV2, 1 Minimum, 1 LoopCond, 1 LogicalAnd
To use with tensorflow/tools/benchmark:benchmark_model try these arguments:
bazel run tensorflow/tools/benchmark:benchmark_model -- --graph=optimized_for_inference_graph.pb --show_flops --input_layer=input --input_layer_type=float --input_layer_shape= --output_layer=softmax_output

 ./summarize_graph.sh frozen_graph.pb
Found 1 possible inputs: (name=input, type=float(1), shape=[?,480000])
No variables spotted.
Found 1 possible outputs: (name=softmax_output, op=Softmax)
Found 3156821 (3.16M) const parameters, 0 (0) variable parameters, and 129 control_edges
Op types used: 221 Const, 32 Identity, 28 Mul, 27 Reshape, 26 Pack, 25 Add, 18 Sub, 14 ConcatV2, 12 Range, 10 StridedSlice, 10 Cast, 8 FloorDiv, 8 GatherV2, 8 Transpose, 8 Less, 7 Enter, 7 RealDiv, 6 Shape, 6 Prod, 6 MatMul, 5 BiasAdd, 5 Fill, 4 Log, 4 Maximum, 4 ExpandDims, 3 ListDiff, 3 Conv2D, 3 Merge, 3 Select, 3 NextIteration, 3 GreaterEqual, 3 Switch, 2 SplitV, 2 Softmax, 2 Size, 2 Rsqrt, 2 FusedBatchNorm, 2 Pad, 2 Neg, 2 LinSpace, 2 TensorArrayV3, 2 Mean, 2 MaxPool, 1 TensorArrayScatterV3, 1 TensorArrayReadV3, 1 TensorArrayGatherV3, 1 TensorArraySizeV3, 1 Sum, 1 TensorArrayWriteV3, 1 Cos, 1 ComplexAbs, 1 Square, 1 Split, 1 Sigmoid, 1 Exit, 1 FloorMod, 1 RandomStandardNormal, 1 RFFT, 1 Placeholder, 1 PadV2, 1 Minimum, 1 LoopCond, 1 LogicalAnd
To use with tensorflow/tools/benchmark:benchmark_model try these arguments:
```

After using optimized_for_inference bin, the input shape changed. tf version 1.9

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatatodd: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatatodd: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatatodd: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatatodd: It has been 30 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by mvhsin** [comment]
> 
> 
> I met the same problem when i use the .pb produced by quantize_graph

Hi kasyoukin,
I also met the same issue when use the .pb produced by quantize_graph.
Did you find the solution?

**Comment by lipixun** [comment]
I met exactly the same problem and it seems like that the problem is caused by `tf.cond`.

**Comment by tall-josh** [comment]
Same problem, looks like the dropout node. I was also trying to use an optimized  graph. It looks like I can used an unoptimized graph just fine.
```
ValueError: NodeDef expected inputs '' do not match 1 inputs specified; Op<name=Const; signature= -> output:dtype; attr=value:tensor; attr=dtype:type>; NodeDef: prefix/dense_0/Dropout/cond/dropout/keep_prob = Const[dtype=DT_FLOAT, value=Tensor<type: float shape: [] values: 0.2>](prefix/dense_0/Dropout/cond/Switch:1)
```

**Comment by jvishnuvardhan** [comment]
I could reproduce the issue with TF1.13.1. Thanks!

**Comment by ylz1104** [comment]
In my opinion  it caused by tf.cond(),but without any solutions,unless remove this node.

**Comment by ronitshaw** [comment]
Facing the a similar issue when using LSTM in my model. Any leads so far?

ValueError: NodeDef expected inputs '' do not match 1 inputs specified; Op<name=Const; signature= -> output:dtype; attr=value:tensor; attr=dtype:type>; NodeDef: {{node lstm_1/while/add/y}} = Const[_output_shapes=[[]], dtype=DT_INT32, value=Tensor<type: int32 shape: [] values: 1>](lstm_1/while/Switch:1)

**Comment by xxoospring** [comment]
I met the same problem yesterday. The reason seem to be related  "tf.graph_util.remove_training_nodes"(or this function wrapped in "tensorflow.python.tools").

`
def save_pb_file(meta_file, ckpt, output_pb_file, output_nodes, deploy=True):
    saver = tf.train.import_meta_graph(meta_file)
    with tf.Session() as sess:
        saver.restore(sess, ckpt)
        output_graph_def = graph_util.convert_variables_to_constants(
            sess,
            input_graph_def=sess.graph_def,
            output_node_names=output_nodes
        )
        **# if i set this Ture,  when i restore frozen pb model, "** NodeDef expected inputs '' do not match 1 inputs specified***"error occur**
        if deploy:
            output_graph_def = tf.graph_util.remove_training_nodes(output_graph_def)

        with tf.gfile.GFile(output_pb_file, 'wb') as fw:
            fw.write(output_graph_def.SerializeToString())

def load_pb_model(pb_file):
    output_graph_def = tf.GraphDef()
    with tf.gfile.Open(pb_file, "rb") as f:
        output_graph_def.ParseFromString(f.read())
    # new_graph = optimize_for_inference_lib.optimize_for_inference(output_graph_def, op_lst[:2], op_lst[2:3],[tf.int32.as_datatype_enum, tf.int32.as_datatype_enum])
    ret = tf.import_graph_def(output_graph_def,)
    return ret
`

**Comment by xxoospring** [comment]
I met the same problem("**do not match 1 inputs specified...***") yesterday. The reason seem to be related "tf.graph_util.remove_training_nodes"(or this function wrapped in "tensorflow.python.tools").

**Comment by saxenasaurabh** [comment]
I am unable to repro this in 1.14 for the examples posted by @yegord and @dvicini. Please reopen with a repro if this is still not working for you.

**Comment by prateethvnayak** [comment]
> I am unable to repro this in 1.14 for the examples posted by @yegord and @dvicini. Please reopen with a repro if this is still not working for you.

What about Tf 1.13.1  ?

**Comment by zhoujianqian** [comment]
entity_tagging/bidirectional_rnn/fw/fw/cond/fw/multi_rnn_cell/cell_0/basic_lstm_cell/MatMul/Switch' expects to be colocated with unknown node 'entity_tagging/bidirectional_rnn/fw/multi_rnn_cell/cell_0/basic_lstm_cell/kernel/read'

when use quantize tools cause this problem
solved this problem by delete graph_util.remove_training_nodes function

**Comment by tonyw** [comment]
reproduct the it:
1. train a model by tf/models/official/transformer
2. do freeze_graph for the model, which created at step 1
3. try to import the graph_def, which created at step 2

> input_tensor = tf.placeholder(tf.int64, shape=(1, None), name='input_tensor')
    with tf.gfile.GFile(model_file, 'rb') as f:
        graph_def = tf.GraphDef()
        graph_def.ParseFromString(f.read())
        with tf.Session() as sess:
            tf.import_graph_def(graph_def,{"input_tensor":input_tensor},name="")

**Comment by stefanpantic** [comment]
I'm having the same issue. For me it seems to occur in ```tf.keras.layers.BatchNormalization```. When I pass the bool ```training=is_training``` to the call operator the error dissapears. Any idea on why this happens?

**Comment by jayle19930918** [comment]
use tensorflow 1.14.0

**Comment by ZeliangSu** [comment]
Same issue with TF 1.13.1 caused by batch_norm. 
`ValueError: NodeDef expected inputs '' do not match 1 inputs specified; Op<name=Const; signature= -> output:dtype; attr=value:tensor; attr=dtype:type>; NodeDef: {{node import/model/conv1/batch_norm/cond/Const}}`
Disappear with TF 1.14.0
