### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow.python.training'

### ISSUE THREAD

**Issue by robi56** [tensorflow/tensorflow#19848]
No Module Found for Tensorflow, 

I have installed tensorflow-gpu(version=1.5) in a conda virtual env and the cuda version 9.1 

The packages in the virtual environment  
......................................installed packages......................................
spyder (3.2.4)
SQLAlchemy (1.1.13)
statsmodels (0.8.0)
sympy (1.1.1)
tables (3.4.2)
tblib (1.3.2)
tensorflow-gpu (1.5.0)
tensorflow-tensorboard (1.5.1)
terminado (0.6)
testpath (0.3.1)
toolz (0.8.2)
------------------------------------------------------------------------------------------------

I run the following program,
`python train_tripletloss.py --logs_base_dir ~/logs/facenet/ --models_base_dir ~/models/facenet/ --data_dir /home/socian/Documents/facenet/data/lfw --image_size 250 --model_def src.models.inception_resnet_v1 --lfw_dir /home/socian/Documents/facenet/data/lfw_182 --optimizer RMSPROP --learning_rate 0.01 --weight_decay 1e-4 --max_nrof_epochs 500`

**but it shows the error 
Traceback (most recent call last):
  File "train_tripletloss.py", line 39, in <module>
    from src import facenet
  File "/home/tareq/rabindra/facenet/src/facenet.py", line 37, in <module>
    from tensorflow.python.training import training
ModuleNotFoundError: No module named 'tensorflow.python.training'**

Then I have checkout  the problem in python shell,

 >>> import tensorflow as tf
```
>>> from tensorflow.python.training import training
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'tensorflow.python.training'
>>> from tensorflow.python.data import dataset
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'dataset'
>>> 
```

`

**Comment by nikhilranjan7** [comment]
Some of the modules have changed in version 1.5 like instead of using 
`from tensorflow.python.data import dataset`
you can use 
`tf.data.Dataset`

For other API info visit this [link.](https://www.tensorflow.org/versions/r1.5/api_docs/python/tf/data/Dataset)

**Comment by tensorflowbutler** [comment]
Nagging Assignee @reedwm: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by reedwm** [comment]
As @nikhilranjan7 stated, internal modules can change between TensorFlow releases. See [this link](https://www.tensorflow.org/programmers_guide/version_compat) for version compatibility info.
