### ISSUE TITLE
TF that is build from r1.9 - crashes with _gru_ops.so: undefined symbol: _ZN15stream_executor6Stream12ThenBlasGemmENS_4blas9TransposeES2_yyyfRKNS_12DeviceMemoryIfEEiS6_ifPS4_i 

### ISSUE THREAD

**Issue by b0noI** [tensorflow/tensorflow#19840]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No, I have used unchanged code from branch r1.9, commit e1436b2952c7600c8ac88114210381db0398be16
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**:branch r1.9, commit e1436b2952c7600c8ac88114210381db0398be16
- **Python version**: 3.6.5
- **Bazel version (if compiling from source)**: 0.10.1
- **GCC/Compiler version (if compiling from source)**: 4.8
- **CUDA/cuDNN version**: 9.2/7.2
- **GPU model and memory**: V100, 16Gb
- **Exact command to reproduce**:

```bash
git clone https://github.com/tensorflow/benchmarks.git
cd benchmarks/scripts/tf_cnn_benchmarks
git checkout 551caecb936312690d6bc8c8c2e2562089e2c200
python3 tf_cnn_benchmarks.py --data_format=NCHW --batch_size=256 --num_batches=100 --model=resnet50 --optimizer=momentum --variable_update=replicated --nodistortions --hierarchical_copy=True --gradient_repacking=8 --datasets_use_prefetch=False --display_every=10 --gpu_thread_mode=gpu_shared --num_gpus=8 --use_fp16=True
```

### Results:
```
python3 tf_cnn_benchmarks.py --data_format=NCHW --batch_size=256 --num_batches=100 --model=resnet50 --optimizer=momentum --variable_update=replicated --nodistortions --hierarchical_copy=True --gradient_repacking=8 --datasets_use_prefetch=False --display_every=10 --gpu_thread_mode=gpu_shared --num_gpus=8 --use_fp16=True
/usr/lib/python3/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "tf_cnn_benchmarks.py", line 27, in <module>
    import benchmark_cnn
  File "/home/vkovalevskyi/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 48, in <module>
    import data_utils
  File "/home/vkovalevskyi/benchmarks/scripts/tf_cnn_benchmarks/data_utils.py", line 21, in <module>
    from tensorflow.contrib.data.python.ops import batching
  File "/home/vkovalevskyi/.local/lib/python3.6/site-packages/tensorflow/contrib/__init__.py", line 35, in <module>
    from tensorflow.contrib import cudnn_rnn
  File "/home/vkovalevskyi/.local/lib/python3.6/site-packages/tensorflow/contrib/cudnn_rnn/__init__.py", line 34, in <module>
    from tensorflow.contrib.cudnn_rnn.python.layers import *
  File "/home/vkovalevskyi/.local/lib/python3.6/site-packages/tensorflow/contrib/cudnn_rnn/python/layers/__init__.py", line 23, in <module>
    from tensorflow.contrib.cudnn_rnn.python.layers.cudnn_rnn import *
  File "/home/vkovalevskyi/.local/lib/python3.6/site-packages/tensorflow/contrib/cudnn_rnn/python/layers/cudnn_rnn.py", line 20, in <module>
    from tensorflow.contrib.cudnn_rnn.python.ops import cudnn_rnn_ops
  File "/home/vkovalevskyi/.local/lib/python3.6/site-packages/tensorflow/contrib/cudnn_rnn/python/ops/cudnn_rnn_ops.py", line 22, in <module>
    from tensorflow.contrib.rnn.python.ops import lstm_ops
  File "/home/vkovalevskyi/.local/lib/python3.6/site-packages/tensorflow/contrib/rnn/__init__.py", line 88, in <module>
    from tensorflow.contrib.rnn.python.ops.gru_ops import *
  File "/home/vkovalevskyi/.local/lib/python3.6/site-packages/tensorflow/contrib/rnn/python/ops/gru_ops.py", line 33, in <module>
    resource_loader.get_path_to_datafile("_gru_ops.so"))
  File "/home/vkovalevskyi/.local/lib/python3.6/site-packages/tensorflow/contrib/util/loader.py", line 56, in load_op_library
    ret = load_library.load_op_library(path)
  File "/home/vkovalevskyi/.local/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home/vkovalevskyi/.local/lib/python3.6/site-packages/tensorflow/contrib/rnn/python/ops/_gru_ops.so: undefined symbol: _ZN15stream_executor6Stream12ThenBlasGemmENS_4blas9TransposeES2_yyyfRKNS_12DeviceMemoryIfEEiS6_ifPS4_i
```

**Comment by freewilll** [comment]
Same here under macos following saudet's lead on #19676

```
$ python3 -c 'import tensorflow.contrib.eager as tfe'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/freewilll/code/machine-learning/tensorflow/venv/lib/python3.4/site-packages/tensorflow/contrib/__init__.py", line 35, in <module>
    from tensorflow.contrib import cudnn_rnn
  File "/Users/freewilll/code/machine-learning/tensorflow/venv/lib/python3.4/site-packages/tensorflow/contrib/cudnn_rnn/__init__.py", line 34, in <module>
    from tensorflow.contrib.cudnn_rnn.python.layers import *
  File "/Users/freewilll/code/machine-learning/tensorflow/venv/lib/python3.4/site-packages/tensorflow/contrib/cudnn_rnn/python/layers/__init__.py", line 23, in <module>
    from tensorflow.contrib.cudnn_rnn.python.layers.cudnn_rnn import *
  File "/Users/freewilll/code/machine-learning/tensorflow/venv/lib/python3.4/site-packages/tensorflow/contrib/cudnn_rnn/python/layers/cudnn_rnn.py", line 20, in <module>
    from tensorflow.contrib.cudnn_rnn.python.ops import cudnn_rnn_ops
  File "/Users/freewilll/code/machine-learning/tensorflow/venv/lib/python3.4/site-packages/tensorflow/contrib/cudnn_rnn/python/ops/cudnn_rnn_ops.py", line 22, in <module>
    from tensorflow.contrib.rnn.python.ops import lstm_ops
  File "/Users/freewilll/code/machine-learning/tensorflow/venv/lib/python3.4/site-packages/tensorflow/contrib/rnn/__init__.py", line 88, in <module>
    from tensorflow.contrib.rnn.python.ops.gru_ops import *
  File "/Users/freewilll/code/machine-learning/tensorflow/venv/lib/python3.4/site-packages/tensorflow/contrib/rnn/python/ops/gru_ops.py", line 33, in <module>
    resource_loader.get_path_to_datafile("_gru_ops.so"))
  File "/Users/freewilll/code/machine-learning/tensorflow/venv/lib/python3.4/site-packages/tensorflow/contrib/util/loader.py", line 56, in load_op_library
    ret = load_library.load_op_library(path)
  File "/Users/freewilll/code/machine-learning/tensorflow/venv/lib/python3.4/site-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: dlopen(/Users/freewilll/code/machine-learning/tensorflow/venv/lib/python3.4/site-packages/tensorflow/contrib/rnn/python/ops/_gru_ops.so, 6): Symbol not found: __ZN15stream_executor6Stream12ThenBlasGemmENS_4blas9TransposeES2_yyydRKNS_12DeviceMemoryIdEEiS6_idPS4_i
  Referenced from: /Users/freewilll/code/machine-learning/tensorflow/venv/lib/python3.4/site-packages/tensorflow/contrib/rnn/python/ops/_gru_ops.so
  Expected in: flat namespace
 in /Users/freewilll/code/machine-learning/tensorflow/venv/lib/python3.4/site-packages/tensorflow/contrib/rnn/python/ops/_gru_ops.so
 ```

**Comment by b0noI** [comment]
same bug on RC1:

```
Traceback (most recent call last):
 File "tf_cnn_benchmarks.py", line 27, in <module>
   import benchmark_cnn
 File "/home/builder/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 48, in <module>
   import data_utils
 File "/home/builder/benchmarks/scripts/tf_cnn_benchmarks/data_utils.py", line 21, in <module>
   from tensorflow.contrib.data.python.ops import batching
 File "/home/builder/.local/lib/python2.7/site-packages/tensorflow/contrib/__init__.py", line 35, in <module>
   from tensorflow.contrib import cudnn_rnn
 File "/home/builder/.local/lib/python2.7/site-packages/tensorflow/contrib/cudnn_rnn/__init__.py", line 34, in <module>
   from tensorflow.contrib.cudnn_rnn.python.layers import *
 File "/home/builder/.local/lib/python2.7/site-packages/tensorflow/contrib/cudnn_rnn/python/layers/__init__.py", line 23, in <module>
   from tensorflow.contrib.cudnn_rnn.python.layers.cudnn_rnn import *
 File "/home/builder/.local/lib/python2.7/site-packages/tensorflow/contrib/cudnn_rnn/python/layers/cudnn_rnn.py", line 20, in <module>
   from tensorflow.contrib.cudnn_rnn.python.ops import cudnn_rnn_ops
 File "/home/builder/.local/lib/python2.7/site-packages/tensorflow/contrib/cudnn_rnn/python/ops/cudnn_rnn_ops.py", line 22, in <module>
   from tensorflow.contrib.rnn.python.ops import lstm_ops
 File "/home/builder/.local/lib/python2.7/site-packages/tensorflow/contrib/rnn/__init__.py", line 88, in <module>
   from tensorflow.contrib.rnn.python.ops.gru_ops import *
 File "/home/builder/.local/lib/python2.7/site-packages/tensorflow/contrib/rnn/python/ops/gru_ops.py", line 33, in <module>
   resource_loader.get_path_to_datafile("_gru_ops.so"))
 File "/home/builder/.local/lib/python2.7/site-packages/tensorflow/contrib/util/loader.py", line 56, in load_op_library
   ret = load_library.load_op_library(path)
 File "/home/builder/.local/lib/python2.7/site-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
   lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home/builder/.local/lib/python2.7/site-packages/tensorflow/contrib/rnn/python/ops/_
gru_ops.so: undefined symbol: _ZN15stream_executor6Stream12ThenBlasGemmENS_4blas9TransposeES2_yyyfRKNS_12DeviceMemoryIfEEiS6_ifPS4_i
Traceback (most recent call last):
```

**Comment by reedwm** [comment]
I was not able to reproduce in the Docker image [nvidia/cuda:9.2-cudnn7-devel-ubuntu18.04](https://hub.docker.com/r/nvidia/cuda/) with identical settings. tf_cnn_benchmarks worked fine when i ran it.

@gunan, any ideas what the issue could be?

**Comment by gunan** [comment]
No idea off the top of my head.
Are you using TF built from sources, or are you using any of our release packages?

**Comment by b0noI** [comment]
@reedwm @gunan I was building from source. I have recreated builder machine and now it works fine (looks like). Not sure what was the root case on the original builder. Probably some strange combination of dependancies that was impacting 1.9 but not 1.8.

**Comment by b0noI** [comment]
Closing, since looks like latest r1.9 works for me.

**Comment by b0noI** [comment]
reopening, same on v1.9.0-rc2:

/usr/lib/python2.7/dist-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated.
In future, it will be treated as `np.float64 == np.dtype(float).type`.
 from ._conv import register_converters as _register_converters
Traceback (most recent call last):
 File "tf_cnn_benchmarks.py", line 27, in <module>
   import benchmark_cnn
 File "/home/builder/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 48, in <module>
   import data_utils
 File "/home/builder/benchmarks/scripts/tf_cnn_benchmarks/data_utils.py", line 21, in <module>
   from tensorflow.contrib.data.python.ops import batching
 File "/home/builder/.local/lib/python2.7/site-packages/tensorflow/contrib/__init__.py", line 36, in <module>
   from tensorflow.contrib import cudnn_rnn
 File "/home/builder/.local/lib/python2.7/site-packages/tensorflow/contrib/cudnn_rnn/__init__.py", line 34, in <module>
   from tensorflow.contrib.cudnn_rnn.python.layers import *
 File "/home/builder/.local/lib/python2.7/site-packages/tensorflow/contrib/cudnn_rnn/python/layers/__init__.py", line 23, in <module>
   from tensorflow.contrib.cudnn_rnn.python.layers.cudnn_rnn import *
 File "/home/builder/.local/lib/python2.7/site-packages/tensorflow/contrib/cudnn_rnn/python/layers/cudnn_rnn.py", line 20, in <module>
   from tensorflow.contrib.cudnn_rnn.python.ops import cudnn_rnn_ops
 File "/home/builder/.local/lib/python2.7/site-packages/tensorflow/contrib/cudnn_rnn/python/ops/cudnn_rnn_ops.py", line 22, in <module>
   from tensorflow.contrib.rnn.python.ops import lstm_ops
 File "/home/builder/.local/lib/python2.7/site-packages/tensorflow/contrib/rnn/__init__.py", line 89, in <module>
   from tensorflow.contrib.rnn.python.ops.gru_ops import *
 File "/home/builder/.local/lib/python2.7/site-packages/tensorflow/contrib/rnn/python/ops/gru_ops.py", line 33, in <module>
   resource_loader.get_path_to_datafile("_gru_ops.so"))
 File "/home/builder/.local/lib/python2.7/site-packages/tensorflow/contrib/util/loader.py", line 56, in load_op_library
   ret = load_library.load_op_library(path)
 File "/home/builder/.local/lib/python2.7/site-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
   lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home/builder/.local/lib/python2.7/site-packages/tensorflow/contrib/rnn/python/ops/_gru_ops.so: undefined s
ymbol: _ZN15stream_executor6Stream12ThenBlasGemmENS_4blas9TransposeES2_yyyfRKNS_12DeviceMemoryIfEEiS6_ifPS4_i
Traceback (most recent call last):

**Comment by martinwicke** [comment]
Which commit worked (you said some r1.9 worked)?

**Comment by martinwicke** [comment]
And to confirm, this is gcc 4.8, CUDA 9.2, Ubuntu 18.04 still

**Comment by b0noI** [comment]
@martinwicke my mistake it did not work before :(

our updated builder:
CUDA 9.2, 
GCC: Ubuntu 5.4.0-6ubuntu1~16.04.10
Ubuntu 16.04.10

**Comment by b0noI** [comment]
I can provide binary if needed

**Comment by rudrapoudel** [comment]
I have also similar problem with tensorflow 1.8.0, whenever I import/use tensorflow.contrib.

**Code to generate error,**
import tensorflow.contrib

**My system has,**
CUDA 9.0
Ubuntu 16.04.4 LTS
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609

**Comment by b0noI** [comment]
I will close the bug, I was able to correctly compile the TF 1.9, now bazel build requires different way of triggering the build in order to find all the required CUDA libraries, on top of this monolithic build almost always shows that build is ok even though some of the libs were not found. Combinations of these 2 things makes it hard to identify the root cause and quickly come up with the solution.

**Comment by rdwrt** [comment]
Same error at latest upload: 

https://github.com/tensorflow/serving/blob/012e0b992d4b6ff003e0bc02226681ae526c9059/tensorflow_serving/tools/docker/Dockerfile.devel-gpu

Is there some way to build from a tag that is stable?

**Comment by rdwrt** [comment]
I am trying 1.9.0-rc2 now

https://github.com/tensorflow/serving/tree/1.9.0-rc2/tensorflow_serving/tools/docker

**Comment by aclowkey** [comment]
@rdwrt It won't build 

> E: Packages were downgraded and -y was used without --allow-downgrades.

**Comment by rdwrt** [comment]
Maybe with a --no-cache when running the docker build.

**Comment by yunjiangster** [comment]
I had the same error in the title earlier when I built (on CentOS7 with CUDA 9.0) with --config=monolithic, after removing the flag the problem went away. The installation steps are documented in https://gist.github.com/gentaiscool/a628fab5cd98953af7f46b69463394b3

**Comment by noahstier** [comment]
I'm getting the same error, not related to tf-serving. Just building tensorflow with
```
bazel build \
  --config=opt \
  --config=cuda \
  --config=mkl \
  //tensorflow/tools/pip_package:build_pip_package
```
specs:
- Python 3.5.5
- TensorFlow 1.9 and 1.10 (tried both, same result)
- Ubuntu 16.04
- gcc 5.4.0
- cuda 9.2
- with and without --config=monolithic (tried both)

```
In [4]: import tensorflow.contrib
---------------------------------------------------------------------------
NotFoundError                             Traceback (most recent call last)
<ipython-input-4-9ce6c8f43c36> in <module>()
----> 1 import tensorflow.contrib
...
NotFoundError: ~/miniconda3/envs/35/lib/python3.5/site-packages/tensorflow/contrib/rnn/python/ops/_lstm_ops.so: undefined symbol: _ZN15stream_executor6Stream12ThenBlasGemmENS_4blas9TransposeES2_yyyfRKNS_12DeviceMemoryIfEEiS6_ifPS4_i
```

**Comment by ilya-edrenkin** [comment]
> I will close the bug, I was able to correctly compile the TF 1.9, now bazel build requires different way of triggering the build in order to find all the required CUDA libraries, on top of this monolithic build almost always shows that build is ok even though some of the libs were not found. Combinations of these 2 things makes it hard to identify the root cause and quickly come up with the solution.

@b0noI : could you please elaborate on that? What is the new different way that bazel now requires?
(instructions in https://www.tensorflow.org/install/install_sources seem to be unchanged.)

We also hit exactly this error with `--monolithic` builds; we are forced to do this because of problematic libprotobuf behavior when loaded by different shared libraries (like described in https://github.com/protocolbuffers/protobuf/issues/1489#issuecomment-217241765). 

(Perhaps there exists an easier solution which would link only protobuf statically, we haven't really looked carefully yet at the corresponding tf-bazel rules; if someone knows a way to do this off top of their head, I would really appreciate a hint!)

**Comment by ethereon** [comment]
I also encountered this on a monolithic build of TensorFlow `v1.11.0`.

It's pretty easily and consistently reproducible:
- Build within an official tf docker image (eg: `tensorflow/tensorflow:1.11.0-devel-gpu`) with `--monolithic`
- Install the pip package
- Import `tensorflow.contrib` --> observe it fail due to missing symbols

Investigating a bit, I found that a simple fix is to add the following entry to [tf_version_script.lds](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tf_version_script.lds):

```
*stream_executor*;
```

**Comment by lifeiteng** [comment]
@ethereon the right way!

**Comment by vmarkovtsev** [comment]
@ethereon's workaround worked for me (v1.11, cuda+monolithic+mkl+opt)
