### ISSUE TITLE
tf.feature_column.indicator_column lack of hash_bucket conflict resolver

### ISSUE THREAD

**Issue by xielm12** [tensorflow/tensorflow#19876]
Here is my code:

```

import tensorflow as tf

features = {'color': [['R','A'], ['A','G'], ['A','G'], ['G','B'],['B','R']],
            'weight': [[1.0,2.0], [0.1,4.0], [5.0,1.0], [8.0,7.0],[3.0,2.0]]}

color_feature = tf.feature_column.categorical_column_with_hash_bucket(
                key = "color",
                hash_bucket_size = 10,
                dtype=tf.string)

column = tf.feature_column.weighted_categorical_column(color_feature, 'weight',dtype = tf.float32)

indicator = tf.feature_column.indicator_column(column)
tensor = tf.feature_column.input_layer(features, [indicator])

with tf.Session() as session:
    session.run(tf.global_variables_initializer())
    session.run(tf.tables_initializer())
    print(session.run([tensor]))

```

then, got the error as follow:

```
D:\ProgramData\Anaconda3\python.exe E:/wnd_test/test.py
D:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2018-06-09 20:54:36.683625: I T:\src\github\tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2018-06-09 20:54:36.699225: W T:\src\github\tensorflow\tensorflow\core\framework\op_kernel.cc:1318] OP_REQUIRES failed at sparse_to_dense_op.cc:126 : Invalid argument: indices[9] = [4,8] is repeated
2018-06-09 20:54:36.699225: W T:\src\github\tensorflow\tensorflow\core\framework\op_kernel.cc:1318] OP_REQUIRES failed at sparse_to_dense_op.cc:126 : Invalid argument: indices[9] = [4,8] is repeated
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1322, in _do_call
    return fn(*args)
  File "D:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "D:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[9] = [4,8] is repeated
	 [[Node: input_layer/color_weighted_by_weight_indicator/SparseToDense = SparseToDense[T=DT_FLOAT, Tindices=DT_INT64, validate_indices=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](input_layer/color_weighted_by_weight_indicator/SparseSlice, input_layer/color_weighted_by_weight_indicator/SparseSlice:2, input_layer/color_weighted_by_weight_indicator/SparseSlice:1, input_layer/color_weighted_by_weight_indicator/SparseToDense/default_value)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:/wnd_test/test.py", line 55, in <module>
    print(session.run([tensor]))
  File "D:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 900, in run
    run_metadata_ptr)
  File "D:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "D:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1316, in _do_run
    run_metadata)
  File "D:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[9] = [4,8] is repeated
	 [[Node: input_layer/color_weighted_by_weight_indicator/SparseToDense = SparseToDense[T=DT_FLOAT, Tindices=DT_INT64, validate_indices=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](input_layer/color_weighted_by_weight_indicator/SparseSlice, input_layer/color_weighted_by_weight_indicator/SparseSlice:2, input_layer/color_weighted_by_weight_indicator/SparseSlice:1, input_layer/color_weighted_by_weight_indicator/SparseToDense/default_value)]]

Caused by op 'input_layer/color_weighted_by_weight_indicator/SparseToDense', defined at:
  File "E:/wnd_test/test.py", line 50, in <module>
    tensor = tf.feature_column.input_layer(features, [indicator])
  File "D:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\feature_column\feature_column.py", line 277, in input_layer
    trainable, cols_to_vars)
  File "D:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\feature_column\feature_column.py", line 202, in _internal_input_layer
    trainable=trainable)
  File "D:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\feature_column\feature_column.py", line 3302, in _get_dense_tensor
    return inputs.get(self)
  File "D:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\feature_column\feature_column.py", line 2100, in get
    transformed = column._transform_feature(self)  # pylint: disable=protected-access
  File "D:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\feature_column\feature_column.py", line 3244, in _transform_feature
    return sparse_ops.sparse_tensor_to_dense(weighted_column)
  File "D:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\sparse_ops.py", line 1011, in sparse_tensor_to_dense
    name=name)
  File "D:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\sparse_ops.py", line 791, in sparse_to_dense
    name=name)
  File "D:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_sparse_ops.py", line 3268, in sparse_to_dense
    name=name)
  File "D:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "D:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3392, in create_op
    op_def=op_def)
  File "D:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): indices[9] = [4,8] is repeated
	 [[Node: input_layer/color_weighted_by_weight_indicator/SparseToDense = SparseToDense[T=DT_FLOAT, Tindices=DT_INT64, validate_indices=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](input_layer/color_weighted_by_weight_indicator/SparseSlice, input_layer/color_weighted_by_weight_indicator/SparseSlice:2, input_layer/color_weighted_by_weight_indicator/SparseSlice:1, input_layer/color_weighted_by_weight_indicator/SparseToDense/default_value)]]


Process finished with exit code 1

```

The ```InvalidArgumentError``` is caused by the fact that feature "B" and feature  "R" are hashed into the same hash_bucket.  
It'll be great if a ```combiner``` argument (as in ```tf.feature_column.embedding_column```) can be implemented in the ```tf.feature_column.indicator_column``` funciton.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by xielm12** [comment]
System information:
· Have I written custom code: No
· OS Platform and Distribution: Win7-x64
· TensorFlow installed from: pip install tensorflow
· TensorFlow version: 1.5.0
· Bazel version: No
· CUDA/cuDNN version: No
· GPU model and memory: No
. Exact command to reproduce: python test.py

**Comment by tensorflowbutler** [comment]
Nagging Assignee @rohan100jain: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.
