### ISSUE TITLE
ValueError: Could not interpret optimizer identifier (tf.keras)

### ISSUE THREAD

**Issue by isaacsultan** [tensorflow/tensorflow#19913]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Windows 10
- **TensorFlow installed from (source or binary)**:
binary
- **TensorFlow version (use command below)**:
1.8.0
- **Python version**: 
3.5
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
8.0/6.0
- **GPU model and memory**:
Nvidia
- **Exact command to reproduce**:
model.compile(optimizer=tf.keras.optimizers.Adadelta() ...)

### Describe the problem
Passing in keras optimizers into a tf.keras model causes a value error, unless they are passed as strings i.e. "Adadelta" instead of Adadelta( ). This prevents arguments from being passed to the optimizer. Please note that when the optimizer is imported from vanilla Keras i.e. `keras.optimizers.Adadelta(rho=0.9)` there is no such issue. 

### Source code / logs

``
    import tensorflow as tf
    from tensorflow.python.keras.optimizers import Adadelta, Adam

    model = deepshading.get_model()
    model.compile(optimizer=tf.keras.optimizers.Adadelta(rho=0.9),
                  loss=DSSIMObjective(k1=0.0001, k2=0.001, kernel_size=8),
                  metrics=[DSSIMObjective(k1=0.0001, k2=0.001, kernel_size=8)])
``

Returns trace-back
``
identifier=identifier.__class__.__name__))
Traceback (most recent call last):
  File "C:/Users/isultan/PycharmProjects/deep-shading/run.py", line 69, in <module>
    train()
  File "C:/Users/isultan/PycharmProjects/deep-shading/run.py", line 35, in train
    metrics=[DSSIMObjective(k1=0.0001, k2=0.001, kernel_size=8)])
  File "C:\Users\isultan\AppData\Local\Continuum\miniconda3\envs\tf\lib\site-packages\keras\engine\training.py", line 604, in compile
    self.optimizer = optimizers.get(optimizer)
  File "C:\Users\isultan\AppData\Local\Continuum\miniconda3\envs\tf\lib\site-packages\keras\optimizers.py", line 768, in get
    str(identifier))
ValueError: Could not interpret optimizer identifier: <tensorflow.python.keras._impl.keras.optimizers.Adadelta object at 0x000001E563508860>
``

**Comment by tensorflowbutler** [comment]
Nagging Assignee @fchollet: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by anj-s** [comment]
isaacsultan@ I am unable to reproduce this issue. Here is the code sample I am using: [gist link](https://gist.github.com/anj-s/5c3396f3c33653c3b2a4b2a1cb0778f2). I am using Tensorflow version 1.8 and python 2.7. 

Can you try with another example and see if you are hitting the same issue? Another thing you could try is updating tensorflow to 1.9.

**Comment by isaacsultan** [comment]
Hi @anj-s  I just tried with another example, and can confirm that the issue does not reproduce. I'm closing the issue, thanks.

**Comment by MarcelBeining** [comment]
Having the same issue with SGD optimizer, also tensorflow version 1.8.0

```
Optimizer = tf.keras.optimizers.SGD(lr=1e-3, momentum=0.3, decay=0, nesterov=False)
model.compile(loss=tf.keras.losses.binary_crossentropy,
                  optimizer=Optimizer,
                  metrics=['accuracy'],options = run_opts)
```

> ValueError: ('Could not interpret optimizer identifier:', (<tensorflow.python.keras._impl.keras.optimizers.SGD object at 0x2b98cdfe7c50>,))

It works as soon as I do not provide any parameters to SGD  (`Optimizer = tf.keras.optimizers.SGD() ` )

**Comment by ObsaGILO** [comment]
**please help to fix this error I am running on gpu**
valueError: ('Could not interpret optimizer identifier:', <keras.optimizers.Adadelta object at 0x7ff7cf7bb710>)

**Comment by joshhansen** [comment]
I got this error by using the optimizer class rather than an instance of it, e.g. `optimizer = Adam` instead of `optimizer = Adam()`.

**Comment by jayaBalaR** [comment]
Hi

I am facing this error when I used SGD for my optimizer.
I am running the code on colab, version of tensorflow 2.2.0-rc3.
I took the sample code from Keras documentation.
I need to be able to set and get my learning_rate and other params in my optimizer. But currently only default option is working.
Could you please give a resolution or a temporary workaround for this issue, as I my work is held up for this.
Attaching the screenshot here.

![error 2020-04-23 222914](https://user-images.githubusercontent.com/21074002/80127437-f4251d00-85b1-11ea-8b1b-2130cc1abfb4.jpg)


Thank you

**Comment by Jangab-water** [comment]
'''
import argparse
import os
import tensorflow as tf
import numpy as np
import sys
from sklearn.datasets import load_iris
from matplotlib import pyplot as plt

def overview():
    print("python version=", sys.version)
    print("tensorflow version=", tf.__version__)
    if len(tf.config.list_physical_devices('GPU'))==0:
        print('no gpu device is detected')
    else:
        print(tf.config.list_physical_devices('GPU'))

class SETTING:
    epochs=30
    optimizer='adam'
    loss='categorical_crossentropy'

def load_data():
    iris=load_data()
    X=iris.data
    y=iris.target
    y=np.eye(len(np.unique(target)))[target]
    return X, y

def set_model(fc1, fc2):
    model=tf.keras.models.Sequential()
    model.add(tf.keras.layers.Dense(fc1, activation='relu', input_shape=(4,)))
    model.add(tf.keras.layers.Dense(fc2, activation='relu'))
    model.add(tf.keras.layers.Dense(3, activation='softmax'))
    return model

def train_step():
    mymodel=set_model(20,10)
    mymodel.compile(loss=SETTING.loss, optimizer='adam') # here
    history=mymodel.fit(load_data(), epochs=SETTING.epochs, metrics=['accuracy'], validation_split=0.3)
    return history

def main():
    overview()
    history=train_step()
    plt.plot(history.history['val_accuracy'], label='val_accuracy')

if __name__=='__main__':
    parser=argparse.ArgumentParser(description='simpoe ML using iris datasets')
    parser.add_argument('--epochs', help='setup epochs')
    parser.add_argument('--loss', help='setup loss function')
    parser.add_argument('--callback', help='save best model')
    parser.add_argument('--optimizer', help='setup optimizer')
    # parser.add_argument('--summary', help='show model summary', action=mymodel.summary())
    args=parser.parse_args()
    SETTING.epochs=args.epochs
    SETTING.loss=args.loss
    SETTING.optimizer=args.optimizer
    SETTING.callback=args.callback
    main()
'''

hi bro.

i am facing same problem when i using optimizer from "SETTING" class. i tried to change optimizer 'adam', 'SGD', but it didn't solve.

it was not worked when i using 'SETTING.optimizer', but working when i using 'adam'. i don't know what is difference between 'SETTING.optimizer' and 'adam'

thank you

**Comment by Maigtello** [comment]
> 
> 
> ```
> from tensorflow.python.keras import initializers
> from tensorflow.python.keras import layers
> from tensorflow.keras.optimizers import Adam
> from tensorflow.python.keras.models import Model
> from tensorflow.python.keras.activations import relu
> from tensorflow.python.keras.layers import Input, Dense, Reshape, Flatten, LSTM, Bidirectional
> from tensorflow.python.keras import backend as K
> from tensorflow.python.keras.callbacks import TensorBoard
> from tensorflow.python.keras import regularizers
> from sklearn.model_selection import train_test_split
> ...
> adam_opt = Adam(learning_rate=0.0001)
> loss = weighted_bce
> model.compile(loss=loss, optimizer=adam_opt, experimental_run_tf_function=False)
> ```
> 
> and I got
> 
> ```
> ValueError: Could not interpret optimizer identifier: <keras.optimizer_v2.adam.Adam object at 0x7f4e5c06fca0>
> ```
> 
> does anyone have solved this problem?

Same problem

**Comment by OhnkytaBlabdey** [comment]
> > ```
> > from tensorflow.python.keras import initializers
> > from tensorflow.python.keras import layers
> > from tensorflow.keras.optimizers import Adam
> > from tensorflow.python.keras.models import Model
> > from tensorflow.python.keras.activations import relu
> > from tensorflow.python.keras.layers import Input, Dense, Reshape, Flatten, LSTM, Bidirectional
> > from tensorflow.python.keras import backend as K
> > from tensorflow.python.keras.callbacks import TensorBoard
> > from tensorflow.python.keras import regularizers
> > from sklearn.model_selection import train_test_split
> > ...
> > adam_opt = Adam(learning_rate=0.0001)
> > loss = weighted_bce
> > model.compile(loss=loss, optimizer=adam_opt, experimental_run_tf_function=False)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and I got
> > ```
> > ValueError: Could not interpret optimizer identifier: <keras.optimizer_v2.adam.Adam object at 0x7f4e5c06fca0>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > does anyone have solved this problem?
> 
> Same problem

I solved this problem by uninstalling keras(independent package), and use `keras` in tensorflow.

**Comment by Maigtello** [comment]
> 
> 
> > > ```
> > > from tensorflow.python.keras import initializers
> > > from tensorflow.python.keras import layers
> > > from tensorflow.keras.optimizers import Adam
> > > from tensorflow.python.keras.models import Model
> > > from tensorflow.python.keras.activations import relu
> > > from tensorflow.python.keras.layers import Input, Dense, Reshape, Flatten, LSTM, Bidirectional
> > > from tensorflow.python.keras import backend as K
> > > from tensorflow.python.keras.callbacks import TensorBoard
> > > from tensorflow.python.keras import regularizers
> > > from sklearn.model_selection import train_test_split
> > > ...
> > > adam_opt = Adam(learning_rate=0.0001)
> > > loss = weighted_bce
> > > model.compile(loss=loss, optimizer=adam_opt, experimental_run_tf_function=False)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > and I got
> > > ```
> > > ValueError: Could not interpret optimizer identifier: <keras.optimizer_v2.adam.Adam object at 0x7f4e5c06fca0>
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > does anyone have solved this problem?
> > 
> > 
> > Same problem
> 
> I solved this problem by uninstalling keras(independent package), and use `keras` in tensorflow.

Thanks, I solved changing the import. Now I use `from tensorflow.python.keras.optimizer_v2.adam import Adam`

**Comment by JakeTheSnake3p0** [comment]
I'm getting the same error, but I'm importing from `tensorflow_addons`. It's only occurring due to the fact that I'm attempting to load the model via `bytes()`. Due to limitations in the platform I'm using ([QuantConnect](https://lean-api-docs.netlify.app/classQuantConnect_1_1Storage_1_1ObjectStore.html)), I need to store/retrieve objects using their `ObjectStore.ReadBytes` / `ObjectStore.SaveBytes` methods. I cannot just save a file.

Using some patchwork found [here](https://github.com/tensorflow/tensorflow/issues/34697#issuecomment-627193883), I've been able to get it to the point where I get the error this issue is about but no further. I modified the solution a bit to include keras' `custom_objects`.

```python
# Normally this would include other custom Loss/Metrics classes...
custom_keras_objects = {}

def unpack(model, training_config, weights):
    restored_model = deserialize(model, custom_keras_objects)
    if training_config is not None:
        restored_model.compile(
            **saving_utils.compile_args_from_training_config(training_config, custom_keras_objects)
        )
    restored_model.set_weights(weights)
    return restored_model


# Hotfix function
def make_keras_picklable(*args):

    # Allow caller to include classes not already a part of tensorflow
    # so that deserializing won't trigger a custom_objects warning
    for obj in args:
        custom_keras_objects[obj.__name__] = obj

    def __reduce__(self):
        model_metadata = saving_utils.model_metadata(self)
        training_config = model_metadata.get("training_config", None)
        model = serialize(self)
        weights = self.get_weights()
        return (unpack, (model, training_config, weights))

    cls = Model
    cls.__reduce__ = __reduce__


# This is a grossly oversimplified and untested example...
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, InputLayer
from tensorflow_addons.optimizers import AdamW
make_keras_picklable(AdamW, SGDW)

model = Sequential()
model.add(InputLayer(batch_input_shape=(1, 1, 1)))
model.add(Dense(1)
model.compile(optimizer=self.optimizer)
```
Results in an error inside the call to `compile_args_from_training_config`:

> ValueError: Could not interpret optimizer identifier: <tensorflow_addons.optimizers.weight_decay_optimizers.AdamW object at 0x7f73e9b71a58>

**Comment by ShahidHasib586** [comment]
### I am also getting this type of error!
``
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation, Conv1D, MaxPool1D, Flatten, Dropout
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras import regularizers

# Build the CNN network
model = Sequential()

model.add(Conv1D(filters=128, 
                 kernel_size=6, 
                 padding="same", 
                 strides=2, 
                 activation="relu",
                 input_shape=(x_train.shape[1],x_train.shape[2])))
model.add(MaxPool1D(pool_size=1))
model.add(Flatten())

model.add(Dense(128,  activation='relu')) # Hidden 1
model.add(Dense(64,  activation='relu')) # Hidden 1
model.add(Dense(32,  activation='relu')) # Hidden 1
model.add(Dense(16,  activation='relu')) # Hidden 1
model.add(Dense(1)) # Output
model.compile(loss='mean_squared_error', optimizer= BatAlgorithm(10, 40, 1000, 0.5, 0.5, 0.0, 2.0, -10.0, 10.0, Fun))
``

> ---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-37-e147193aa417>](https://localhost:8080/#) in <module>()
     21 model.add(Dense(16,  activation='relu')) # Hidden 1
     22 model.add(Dense(1)) # Output
---> 23 model.compile(loss='mean_squared_error', optimizer= BatAlgorithm(10, 40, 1000, 0.5, 0.5, 0.0, 2.0, -10.0, 10.0, Fun))

1 frames
[/usr/local/lib/python3.7/dist-packages/keras/optimizers.py](https://localhost:8080/#) in get(identifier)
    143   else:
    144     raise ValueError(
--> 145         'Could not interpret optimizer identifier: {}'.format(identifier))

ValueError: Could not interpret optimizer identifier: <BatAlgorithm.BatAlgorithm object at 0x7f8472aa7310>

>

**Comment by jayaBalaR** [comment]
@ShahidHasib586 , from the stacktrace we can see that the library/ package from which  BatAlgorithm is called is missing. If it is a custom optimizer you wrote, maybe then you need to add to the path and supply the entire path in import for it to pick up. Not sure, if it has got anything to do with tf.keras [Refer to this link for the optimizers in tensorflow.keras https://www.tensorflow.org/api_docs/python/tf]
Hope this helps you
