### ISSUE TITLE
linalg_grad_test is failing with minor array mismatch 

### ISSUE THREAD

**Issue by sandipmgiri** [tensorflow/tensorflow#19935]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:N/A
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
      Ubuntu 16.04 (ppc64le)
- **TensorFlow installed from (source or binary)**:
      Installed from source
- **TensorFlow version (use command below)**:
      TF master
- **Python version**: 
     Python 2.7.5
- **Bazel version (if compiling from source)**:
     bazel-0.11.1
- **CUDA/cuDNN version**:
     NA
- **GPU model and memory**:
      NA
- **Exact command to reproduce**:
 `bazel test -c opt --test_output=errors //tensorflow/python/kernel_tests:linalg_grad_test`

### Describe the problem
This test is failing due to array mismatch error – a single value in an array of 100+ (or 200+) elements differing i.e.  `-0.2765212 VS  -0.09727482` (minor mismatch i.e. 0.01%), I feel this is not "critical".

Hence, I tried running this test by changing minor tolerance `(from atol=0.16 to 0.17)`, and test is passing -
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/kernel_tests/linalg_grad_test.py#L133
Original : `self.assertAllClose(theoretical, numerical, atol=tol, rtol=tol) `
Update to : ` self.assertAllClose(theoretical, numerical, atol=tol+0.01, rtol=tol)`

@skye Is it OK to raise a PR with this changes ?. Please provide your comments on this.
This is similar to PR https://github.com/tensorflow/tensorflow/pull/14086 (Issue : https://github.com/tensorflow/tensorflow/issues/13992).
Thanks!

### Source code / logs
 `bazel test -c opt --test_output=errors //tensorflow/python/kernel_tests:linalg_grad_test`

```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
-----------------------------------------------------------------------------
..F.........
======================================================================
FAIL: test_MatrixSolveLsGradient_float32_10_10_1e-06 (__main__.MatrixBinaryFunctorGradientTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/8f6ddabc24aafac92d95350c806a3c5a/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/python/kernel_tests/linalg_grad_test.runfiles/org_tensorflow/tensorflow/python/kernel_tests/linalg_grad_test.py", line 133, in Test
    self.assertAllClose(theoretical, numerical, atol=tol, rtol=tol)
  File "/root/.cache/bazel/_bazel_root/8f6ddabc24aafac92d95350c806a3c5a/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/python/kernel_tests/linalg_grad_test.runfiles/org_tensorflow/tensorflow/python/framework/test_util.py", line 1368, in assertAllClose
    self._assertAllCloseRecursive(a, b, rtol=rtol, atol=atol, msg=msg)
  File "/root/.cache/bazel/_bazel_root/8f6ddabc24aafac92d95350c806a3c5a/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/python/kernel_tests/linalg_grad_test.runfiles/org_tensorflow/tensorflow/python/framework/test_util.py", line 1338, in _assertAllCloseRecursive
    path_str))
  File "/root/.cache/bazel/_bazel_root/8f6ddabc24aafac92d95350c806a3c5a/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/python/kernel_tests/linalg_grad_test.runfiles/org_tensorflow/tensorflow/python/framework/test_util.py", line 1273, in _assertArrayLikeAllClose
    a, b, rtol=rtol, atol=atol, err_msg=msg, equal_nan=True)
  File "/usr/local/lib/python2.7/dist-packages/numpy/testing/nose_tools/utils.py", line 1396, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "/usr/local/lib/python2.7/dist-packages/numpy/testing/nose_tools/utils.py", line 779, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Not equal to tolerance rtol=0.16, atol=0.16
Mismatched value: a is different from b.
(mismatch 0.01%)
 x: array([[-0.274541,  0.232045,  0.238228, ..., -0.034111, -0.373466,
         0.033984],
       [-0.781969,  3.879241, -0.101673, ..., -2.040497, -3.555899,...
 y: array([[-0.27545 ,  0.234431,  0.2381  , ..., -0.040039, -0.382935,
         0.036284],
       [-0.782201,  3.879493, -0.102113, ..., -2.039877, -3.555702,...

----------------------------------------------------------------------
Ran 12 tests in 1.858s

FAILED (failures=1)
not close where =  (array([40]), array([33]))
not close lhs =  [-0.2765212]
not close rhs =  [-0.09727482]
not close dif =  [0.1792464]
not close tol =  [0.17556396]
dtype = float32, shape = (100, 100)
```

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code

**Comment by robieta** [comment]
This strikes me as reasonable. Can you check on bazel v0.12 first? And if it still fails I'll ping someone in build.

**Comment by sandipmgiri** [comment]
@robieta  Tried to run this test with bazel v0.12.0 , but it's still failing.

**Comment by sandipmgiri** [comment]
@robieta Can we go for PR ?

**Comment by sandipmgiri** [comment]
@gunan , @robieta Can we go for PR ?

**Comment by sandipmgiri** [comment]
Hi @robieta , any update on this ?

**Comment by tensorflowbutler** [comment]
Nagging Assignee @robieta: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @robieta: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @robieta: It has been 47 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @robieta: It has been 63 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @robieta: It has been 79 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.
