### ISSUE TITLE
(tensorboard) TypeError: __new__() got an unexpected keyword argument 'file'

### ISSUE THREAD

**Issue by isaacsultan** [tensorflow/tensorflow#19955]
# System information

    Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
    Yes
    OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
    Windows 10
    TensorFlow installed from (source or binary):
    binary
    TensorFlow version (use command below):
    1.8.0
    Python version:
    3.5
    Bazel version (if compiling from source):
    GCC/Compiler version (if compiling from source):
    CUDA/cuDNN version:
    9.0/7.2
    GPU model and memory:
    Nvidia
    Exact command to reproduce:
     tensorboard --logdir="C:\Users\isultan\PycharmProjects\deep-shading\logs"`

# Describe the problem

Calling tensorboard with an argument for the directory of logs from Anaconda prompt causes a type error. Logs where produced in tf.keras with tensorboard callback `model_tb = TensorBoard(log_dir='./logs', write_graph=True)` passed to `model.fit_generator`. 

# Source code / logs

`(tf) C:\Users\isultan> tensorboard --logdir="C:\Users\isultan\PycharmProjects\deep-shading\logs"`

Traceback (most recent call last):
  File "c:\users\isultan\appdata\local\continuum\miniconda3\envs\tf\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\isultan\appdata\local\continuum\miniconda3\envs\tf\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\isultan\AppData\Local\Continuum\miniconda3\envs\tf\Scripts\tensorboard.exe\__main__.py", line 5, in <module>
  File "c:\users\isultan\appdata\local\continuum\miniconda3\envs\tf\lib\site-packages\tensorboard\main.py", line 30, in <module>
    from tensorboard import default
  File "c:\users\isultan\appdata\local\continuum\miniconda3\envs\tf\lib\site-packages\tensorboard\default.py", line 35, in <module>
    from tensorboard.plugins.audio import audio_plugin
  File "c:\users\isultan\appdata\local\continuum\miniconda3\envs\tf\lib\site-packages\tensorboard\plugins\audio\audio_plugin.py", line 30, in <module>
    from tensorboard.plugins.audio import metadata
  File "c:\users\isultan\appdata\local\continuum\miniconda3\envs\tf\lib\site-packages\tensorboard\plugins\audio\metadata.py", line 22, in <module>
    from tensorboard.plugins.audio import plugin_data_pb2
  File "c:\users\isultan\appdata\local\continuum\miniconda3\envs\tf\lib\site-packages\tensorboard\plugins\audio\plugin_data_pb2.py", line 63, in <module>
    options=None, file=DESCRIPTOR),
TypeError: __new__() got an unexpected keyword argument 'file'
``

**Comment by tensorflowbutler** [comment]
Nagging Assignee @rohan100jain: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @rohan100jain: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by rohan100jain** [comment]
Please submit this issue with the Tensorboard repo https://github.com/tensorflow/tensorboard.
