### ISSUE TITLE
Runtime Error on TFLite Sample App

### ISSUE THREAD

**Issue by yasuhitotsu** [tensorflow/tensorflow#19975]
### System information
* Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
* OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04.4 LTS
* TensorFlow installed from (source or binary): pip/binary
* TensorFlow version (use command below): 1.8.0
* Python version: 3.5.2
* Bazel version (if compiling from source): N/A
* CUDA/cuDNN version: N/A
* GPU model and memory: N/A
* Exact command to reproduce: Please see the description.

### Describe the problem
I'm developing an android application based on the tensorflow-lite [object detection examples](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/lite/examples/android
).

I trained `ssd_mobilenet_v1` and converted that model by following [this instructions](https://github.com/tensorflow/tensorflow/issues/15633#issuecomment-377652630).

Now I modified some lines which are shown the folloing before building and deploying the app.

### Source code

```diff
diff --git a/tensorflow/contrib/lite/examples/android/BUILD b/tensorflow/contrib/lite/examples/android/BUILD
index 5700007..85b58fc 100644
--- a/tensorflow/contrib/lite/examples/android/BUILD
+++ b/tensorflow/contrib/lite/examples/android/BUILD
@@ -34,7 +34,8 @@ android_binary(
         "@tflite_mobilenet//:mobilenet_quant_v1_224.tflite",
         "@tflite_conv_actions_frozen//:conv_actions_frozen.tflite",
         "//tensorflow/contrib/lite/examples/android/assets:conv_actions_labels.txt",
-        "@tflite_mobilenet_ssd//:mobilenet_ssd.tflite",
+        # "@tflite_mobilenet_ssd//:mobilenet_ssd.tflite",
+        "//tensorflow/contrib/lite/examples/android/assets:ssd.tflite",
         "//tensorflow/contrib/lite/examples/android/assets:box_priors.txt",
         "//tensorflow/contrib/lite/examples/android/assets:coco_labels_list.txt",
     ],
diff --git a/tensorflow/contrib/lite/examples/android/src/org/tensorflow/demo/DetectorActivity.java b/tensorflow/contrib/lite/examples/android/src/org/tensorflow/demo/DetectorActivity.java
index de997e4..95710ff 100644
--- a/tensorflow/contrib/lite/examples/android/src/org/tensorflow/demo/DetectorActivity.java
+++ b/tensorflow/contrib/lite/examples/android/src/org/tensorflow/demo/DetectorActivity.java
@@ -50,7 +50,8 @@ public class DetectorActivity extends CameraActivity implements OnImageAvailable

   // Configuration values for the prepackaged SSD model.
   private static final int TF_OD_API_INPUT_SIZE = 300;
-  private static final String TF_OD_API_MODEL_FILE = "mobilenet_ssd.tflite";
+  // private static final String TF_OD_API_MODEL_FILE = "mobilenet_ssd.tflite";
+  private static final String TF_OD_API_MODEL_FILE = "ssd.tflite";
   private static final String TF_OD_API_LABELS_FILE = "file:///android_asset/coco_labels_list.txt";

   // Which detection model to use: by default uses Tensorflow Object Detection API frozen
diff --git a/tensorflow/contrib/lite/examples/android/src/org/tensorflow/demo/TFLiteObjectDetectionAPIModel.java b/tensorflow/contrib/lite/examples/android/src/org/tensorflow/demo/TFLiteObjectDetectionAPIModel.java
index bfb4a0a..b21e753 100644
--- a/tensorflow/contrib/lite/examples/android/src/org/tensorflow/demo/TFLiteObjectDetectionAPIModel.java
+++ b/tensorflow/contrib/lite/examples/android/src/org/tensorflow/demo/TFLiteObjectDetectionAPIModel.java
@@ -47,8 +47,8 @@ public class TFLiteObjectDetectionAPIModel implements Classifier {

   // Only return this many results.
   private static final int NUM_RESULTS = 1917;
-  private static final int NUM_CLASSES = 91;
-
+  // private static final int NUM_CLASSES = 91;
+  private static final int NUM_CLASSES = 22;
   private static final float Y_SCALE = 10.0f;
   private static final float X_SCALE = 10.0f;
   private static final float H_SCALE = 5.0f;
```

### logs
Under those conditions, I faced the following Runtime Error.
```JAVA
06-13 15:38:39.120 21951-21971/org.tensorflow.lite.demo E/AndroidRuntime: FATAL EXCEPTION: inference
    Process: org.tensorflow.lite.demo, PID: 21951
    java.lang.IllegalArgumentException: Output error: Shape of output target [1, 1917, 4] does not match with the shape of the Tensor [1, 1917, 1, 4].
        at org.tensorflow.lite.Tensor.copyTo(Tensor.java:44)
        at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:178)
        at org.tensorflow.demo.TFLiteObjectDetectionAPIModel.recognizeImage(TFLiteObjectDetectionAPIModel.java:222)
        at org.tensorflow.demo.DetectorActivity$3.run(DetectorActivity.java:243)
        at android.os.Handler.handleCallback(Handler.java:761)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:156)
        at android.os.HandlerThread.run(HandlerThread.java:61)
```

Actually I applied another dataset to the model (`ssd.tflite`), but I just used [train.py](https://github.com/tensorflow/models/blob/master/research/object_detection/train.py) as is, so I'm wondering why it was happened.

I hope someone would help me.

Thank you.

**Comment by MengAjin** [comment]
Hello @yasuhitotsu.
I'm having the same problem. 
Did you solve it?

**Comment by MengAjin** [comment]
Hello.
In [#15633](https://github.com/tensorflow/tensorflow/issues/15633), @Haijunlv give two ways to solve this problem. 
I have tried way 2 and success to run model in mobile. 
Many thanks to Haijunlv.

**Comment by issac8huxley** [comment]
Hi， @MengAjin 
I'm having the same problem.
Do you means revise python script box_predictor.py, and bazel build a new apk? Or revise TFLiteObjectDetectionAPIModel.java file? Would you share your revise, thanks.

**Comment by MengAjin** [comment]
@issac8huxley
After revise the box_predictor.py, you should train the model from scratch. There is no need to revise TFLiteObjectDetectionAPIModel.java file.

**Comment by MengAjin** [comment]
Hello @Haijunlv.
Maybe NNAPI? Did you tried NNAPI?
I don't know much about it yet. I don't have a Android device supporting NNAPI.^^

**Comment by Haijunlv** [comment]
@MengAjin No. I didnot try NNAPI. I only have iphone. You are right. It is need to  try tflite with apple CoreML or to Andriod with NNAPI. Maybe the spped is different.

**Comment by issac8huxley** [comment]
@MengAjin  @Haijunlv 
Thanks. With your advise, I can run model in mobile at present.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @aselle: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by achowdhery** [comment]
Hi, 
We have just published a set of instructions that should allow you to run Mobilenet SSD at least on Pixel 2 at 15fps. 
Please try the following and let us know if it works:
https://medium.com/tensorflow/training-and-serving-a-realtime-mobile-object-detector-in-30-minutes-with-cloud-tpus-b78971cf1193

**Comment by anonym24** [comment]
@achowdhery your article talks about quantized model  

`mobilenet_ssd.tflite` isn't quantized! 

change `detect.tflite` to `mobilenet_ssd.tflite` https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/examples/android/app/src/main/java/org/tensorflow/demo/DetectorActivity.java#L54

and `true` to `false` for https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/examples/android/app/src/main/java/org/tensorflow/demo/DetectorActivity.java#L53

this model is being downloaded by https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/examples/android/app/download-models.gradle#L13
