### ISSUE TITLE
tf lite demo throw the error: Op builtin_code out or range: 59

### ISSUE THREAD

**Issue by wenhui7909** [tensorflow/tensorflow#20005]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 17.10
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: tensorflow 1.8
- **Python version**: 2.7
- **Bazel version (if compiling from source)**: 0.13.0
- **GCC/Compiler version (if compiling from source)** : 6.4
- **CUDA/cuDNN version**: None
- **GPU model and memory**: GeForce GTX 750
- **Exact command to reproduce**: run mtcnn pnet model in tflite android demo of tflitecamerademo.

### Describe the problem
Tflite generate is ok.
But run in tflitecamerademo error:
"Op builtin_code out or range: 59. Are you using old TFLite binary with newer model?Registration failed."
For the version of 3daa07aa2dde379388beb2a557a78bc5dd1b86ba on June 6.
It is strange that running demo ok on June 6. 
on June 11, I download new code to another folder to run the demo,
it was error as below log.
Then, I use the demo of June 6, 
the error appeared.
I checked the jar file, it is not changed.
So now I will reproduce the error both the version of June 6, and June 11.
I don't know how the June 6 be changed, 
and how to resolve the error  about "Op builtin_code out or range: 59"

### Source code / logs
The error log in adb as below:
   
    Caused by: java.lang.IllegalArgumentException: Cannot create interpreter: Op builtin_code out or range: 59. Are you using old TFLite binary with newer model?Registration failed.
    
        at org.tensorflow.lite.NativeInterpreterWrapper.createInterpreter(Native Method)
        at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:63)
        at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:51)
        at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:90)
        at com.example.android.tflitecamerademo.ImageClassifier.<init>(ImageClassifier.java:96)
        at com.example.android.tflitecamerademo.ImageClassifierFloatInception.<init>(ImageClassifierFloatInception.java:50)
        at com.example.android.tflitecamerademo.Camera2BasicFragment.onActivityCreated(Camera2BasicFragment.java:335)
        at android.app.Fragment.performActivityCreated(Fragment.java:2077)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:917)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1072)
        at android.app.BackStackRecord.run(BackStackRecord.java:852)
        at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1478)
        at android.app.Activity.performStart(Activity.java:6107)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2491)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2608) 
        at android.app.ActivityThread.access$800(ActivityThread.java:178) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1470) 
        at android.os.Handler.dispatchMessage(Handler.java:111) 
        at android.os.Looper.loop(Looper.java:194) 
        at android.app.ActivityThread.main(ActivityThread.java:5637) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)

**Comment by wenhui7909** [comment]
I rebuilt libtensorflowlite_jni.so, But I can't find the path to replace.
I delete all the libtensorflowlite_jni.so files in my computer, 
It can run mobilenet module OK ...
Before, I can replace the libtensorflowlite_jni.so, I can add my log to the jni so.
I guess the error of "Op builtin_code out or range: 59 " is caused by the jni so is not update.

**Comment by wenhui7909** [comment]
After compile with 'org.tensorflow:tensorflow-lite:0.0.0-nightly'
the error of "Op builtin_code out or range: 59 " disappeared.
Now it is OK.

Now I just don't know how to replace libtensorflowlite_jni.so in my enviroment.
But it is not important now.

**Comment by cy89** [comment]
@andrehentz any hints about the libtensorflowlite_jni.so file?

**Comment by tensorflowbutler** [comment]
Nagging Assignee @cy89: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @andrehentz: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @andrehentz: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tofulawrence** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

Original issue solved.
