### ISSUE TITLE
//tensorflow/python:cost_analyzer_test test fails on ppc64le

### ISSUE THREAD

**Issue by sandipmgiri** [tensorflow/tensorflow#20008]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:N/A
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
      Ubuntu 16.04 (ppc64le)
- **TensorFlow installed from (source or binary)**:
      Installed from source
- **TensorFlow version (use command below)**:
      TF master
- **Python version**: 
     Python 2.7.5
- **Bazel version (if compiling from source)**:
     bazel-0.11.1
- **CUDA/cuDNN version**:
     NA
- **GPU model and memory**:
      NA
- **Exact command to reproduce**:
 `bazel test -c opt --jobs 1 -k --cache_test_results=no --test_output=errors  //tensorflow/python:cost_analyzer_test`

### Describe the problem
FAIL: testBasicMemory (__main__.CostAnalysisTest)
Make sure arguments can be passed correctly.
AssertionError: False is not true

I have started looking into this. 
Any comments/suggestions appreciated.Thanks! 
### Source code / logs
```
INFO: Analysed target //tensorflow/python:cost_analyzer_test (0 packages loaded).
INFO: Found 1 test target...
FAIL: //tensorflow/python:cost_analyzer_test (see /root/.cache/bazel/_bazel_root/78afe71156c58ea89dc510bdb03ba2b0/execroot/org_tensorflow/bazel-out/ppc-opt/testlogs/tensorflow/python/cost_analyzer_test/test.log)
INFO: From Testing //tensorflow/python:cost_analyzer_test:
==================== Test output for //tensorflow/python:cost_analyzer_test:
2018-06-14 09:10:09.134980: I tensorflow/core/grappler/devices.cc:51] Number of eligible GPUs (core count >= 8): 0
2018-06-14 09:10:09.135207: I tensorflow/core/grappler/clusters/single_machine.cc:359] Starting new session
2018-06-14 09:10:09.136755: I tensorflow/core/grappler/clusters/single_machine.cc:349] Cleaning up previous session
2018-06-14 09:10:09.138122: I tensorflow/core/grappler/clusters/single_machine.cc:359] Starting new session
2018-06-14 09:10:09.147635: I tensorflow/core/grappler/clusters/single_machine.cc:349] Cleaning up previous session
2018-06-14 09:10:09.148782: I tensorflow/core/grappler/clusters/single_machine.cc:359] Starting new session
.2018-06-14 09:10:09.157410: I tensorflow/core/grappler/devices.cc:51] Number of eligible GPUs (core count >= 8): 0
2018-06-14 09:10:09.157507: I tensorflow/core/grappler/clusters/single_machine.cc:359] Starting new session
F2018-06-14 09:10:09.352496: I tensorflow/core/grappler/devices.cc:51] Number of eligible GPUs (core count >= 8): 0
2018-06-14 09:10:09.352692: I tensorflow/core/grappler/clusters/single_machine.cc:359] Starting new session
2018-06-14 09:10:09.359070: I tensorflow/core/grappler/clusters/single_machine.cc:349] Cleaning up previous session
2018-06-14 09:10:09.360080: I tensorflow/core/grappler/clusters/single_machine.cc:359] Starting new session
2018-06-14 09:10:09.566104: I tensorflow/core/grappler/clusters/single_machine.cc:349] Cleaning up previous session
2018-06-14 09:10:09.569427: I tensorflow/core/grappler/clusters/single_machine.cc:359] Starting new session

Total time measured in ns (serialized):                           5000
Total time measured in ns (actual):                             281002
Total time analytical in ns (upper bound):        -9223372036854775000
Total time analytical in ns (lower bound):                           0
Overall efficiency (analytical upper/actual):             -3.28232e+13
Overall efficiency (analytical lower/actual):                        0

                                 Op,          Count,  Measured time (ns),    Time percent,     Acc percent,    Analytical upper,    Analytical lower,      Overall eff      Compute eff       Memory eff
                               AddN,              1,                5000,          1e+02%,          1e+02%,-9223372036854775000,                   0,       -1.8e+17%,       -1.8e+17%,              0%,

Below is the per-node report summary:
                                 Op,  Measured time (ns),   Compute time (ns),    Memory time (ns),     Compute eff,      Memory eff,    Inputs
                               AddN,                5000,-9223372036854775000,                   0,       -1.8e+17%,           -inf%,    []


Peak usage for device /job:localhost/replica:0/task:0/device:CPU:0: 12 bytes
  a:0 uses 4 bytes
  b:0 uses 4 bytes
  c:0 uses 4 bytes


Total time measured in ns (serialized):                        8460000
Total time measured in ns (actual):                            5328500
Total time analytical in ns (upper bound):        -9223372036854519848
Total time analytical in ns (lower bound):        -9223372036854655544
Overall efficiency (analytical upper/actual):             -1.73095e+12
Overall efficiency (analytical lower/actual):             -1.73095e+12

                                 Op,          Count,  Measured time (ns),    Time percent,     Acc percent,    Analytical upper,    Analytical lower,      Overall eff      Compute eff       Memory eff
                             MatMul,              3,             2160000,             26%,             26%,-9223372036854676232, 9223372036854773384,       -4.3e+14%,        4.3e+14%,            4.7%,
                          ApplyAdam,              4,             1422000,             17%,             42%,              128232,              125000,              9%,           0.23%,            8.8%,
               Conv2DBackpropFilter,              1,             1040000,             12%,             55%, 9223372036854775000, 9223372036854775000,        8.9e+14%,        8.9e+14%,              0%,
                           ReluGrad,              1,              958000,             11%,             66%,-9223372036854767616, 9223372036854775000,       -9.6e+14%,        9.6e+14%,           0.94%,
                             Conv2D,              1,              604000,            7.1%,             73%,-9223372036854773616, 9223372036854775000,       -1.5e+15%,        1.5e+15%,            0.5%,
                         VariableV2,             14,              537000,            6.3%,             79%,                   0,                   0,              0%,              0%,              0%,
                                Sum,              4,              513000,            6.1%,             86%,               12232,                9000,            2.4%,           0.63%,            1.8%,
                              Const,             10,              465000,            5.5%,             91%,                   0,                   0,              0%,              0%,              0%,
                                Mul,              6,              415000,            4.9%,             96%,               -4848,               -4848,           -1.2%,           -1.2%,              0%,
                                Add,              2,              205000,            2.4%,             98%,                4384,               -1616,            2.1%,          -0.79%,            2.9%,
                               Relu,              1,               35000,           0.41%,             99%,-9223372036854770616, 9223372036854775000,       -2.6e+16%, .2018-06-14 09:10:09.738459: I tensorflow/core/grappler/devices.cc:51] Number of eligible GPUs (core count >= 8): 0
2018-06-14 09:10:09.738574: I tensorflow/core/grappler/clusters/single_machine.cc:359] Starting new session
2018-06-14 09:10:09.739464: I tensorflow/core/grappler/clusters/single_machine.cc:349] Cleaning up previous session
2018-06-14 09:10:09.740389: I tensorflow/core/grappler/clusters/single_machine.cc:359] Starting new session
2018-06-14 09:10:09.747818: I tensorflow/core/grappler/clusters/single_machine.cc:349] Cleaning up previous session
2018-06-14 09:10:09.749965: I tensorflow/core/grappler/clusters/single_machine.cc:359] Starting new session
..
======================================================================
FAIL: testBasicMemory (__main__.CostAnalysisTest)
Make sure arguments can be passed correctly.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/78afe71156c58ea89dc510bdb03ba2b0/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/python/cost_analyzer_test.runfiles/org_tensorflow/tensorflow/python/grappler/cost_analyzer_test.py", line 152, in testBasicMemory
    in report)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 5 tests in 0.639s

FAILED (failures=1)
       2.6e+16%,             17%,
                         Reciprocal,              1,               25000,            0.3%,             99%, 9223372036854775000, 9223372036854775000,        3.7e+16%,        3.7e+16%,              0%,
                           Identity,              6,               24000,           0.28%,             99%,                   0,                   0,              0%,              0%,              0%,
                            Reshape,              6,               22000,           0.26%,          1e+02%,                   0,                   0,              0%,              0%,              0%,
                             Assign,              2,               10000,           0.12%,          1e+02%,                1616,                   0,             16%,             16%,              0%,
                            Softmax,              1,                9000,           0.11%,          1e+02%,-9223372036854775000,                   0,         -1e+17%,         -1e+17%,              0%,
                               Tile,              1,                7000,          0.083%,          1e+02%,-9223372036854775000,                   0,       -1.3e+17%,       -1.3e+17%,              0%,
                                Sub,              1,                5000,          0.059%,          1e+02%, 9223372036854775000, 9223372036854775000,        1.8e+17%,        1.8e+17%,              0%,
                               NoOp,              2,                4000,          0.047%,          1e+02%,                   0,                   0,              0%,              0%,              0%,



Total time measured in ns (serialized):                           5000
Total time measured in ns (actual):                             149014
Total time analytical in ns (upper bound):        -9223372036854775000
Total time analytical in ns (lower bound):                           0
Overall efficiency (analytical upper/actual):              -6.1896e+13
Overall efficiency (analytical lower/actual):                        0

                                 Op,          Count,  Measured time (ns),    Time percent,     Acc percent,    Analytical upper,    Analytical lower,      Overall eff      Compute eff       Memory eff
                               AddN,              1,                5000,          1e+02%,          1e+02%,-9223372036854775000,                   0,       -1.8e+17%,       -1.8e+17%,              0%,

Below is the full per-node report:
op_performance {
  op {
    op: "AddN"
    attr {
      key: "N"
      value {
        i: 2
      }
    }
    attr {
      key: "T"
      value {
        type: DT_INT32
      }
    }
    inputs {
      shape {
        unknown_rank: true
      }
      value {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 20
      }
    }
    inputs {
      shape {
        unknown_rank: true
      }
    }
    device {
      type: "CPU"
      model: "0"
      num_cores: 4
      environment {
        key: "cpu_instruction_set"
        value: "VSX"
      }
      environment {
        key: "eigen"
        value: "3.3.90"
      }
      l1_cache_size: 16384
      l2_cache_size: 524288
      l3_cache_size: 524288
      memory_size: 993132544
    }
  }
  compute_cost: 5000
  compute_efficiency: -1844674407370955
  node: "d"
  compute_time: -9223372036854775000
  memory_efficiency: -inf
  op_memory {
    output_memory: 4
    persistent_memory: 4
  }
}

================================================================================
Target //tensorflow/python:cost_analyzer_test up-to-date:
  bazel-bin/tensorflow/python/cost_analyzer_test
INFO: Elapsed time: 1.835s, Critical Path: 1.36s
INFO: Build completed, 1 test FAILED, 2 total actions
//tensorflow/python:cost_analyzer_test                                   FAILED in 1.4s
```

**Comment by reedwm** [comment]
/CC @gunan, how should ppc64le issues be handled?

**Comment by sandipmgiri** [comment]
Out of 5 sub-tests only one is failing i.e. testBasicMemory .  
The test is failing due to incorrect peak usage on ppc64le :
```
Peak usage for device /job:localhost/replica:0/task:0/device:CPU:0: 12 bytes
  a:0 uses 4 bytes
  b:0 uses 4 bytes
  c:0 uses 4 bytes
```
  
However on X86 , we are getting peak usage as below and test is passing :
```
Peak usage for device /job:localhost/replica:0/task:0/device:CPU:0: 16 bytes
  a:0 uses 4 bytes
  b:0 uses 4 bytes
  d:0 uses 4 bytes
  c:0 uses 4 bytes
```
  
Looks like last 4 bytes are missing on ppc64le. Looking further...  

Relevant log for ppc64le : 
```
F.
======================================================================
FAIL: testBasicMemory (__main__.CostAnalysisTest)
Make sure arguments can be passed correctly.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/78afe71156c58ea89dc510bdb03ba2b0/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/python/cost_analyzer_test.runfiles/org_tensorflow/tensorflow/python/grappler/cost_analyzer_test.py", line 61, in testBasicMemory
    in report)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 2 tests in 0.020s

FAILED (failures=1)
Peak usage for device /job:localhost/replica:0/task:0/device:CPU:0: 12 bytes
  a:0 uses 4 bytes
  b:0 uses 4 bytes
  c:0 uses 4 bytes

================================================================================
Target //tensorflow/python:cost_analyzer_test up-to-date:
```

**Comment by gunan** [comment]
Adding @wdirons as he is also fixing a lot of ppc64le issues.

**Comment by sandipmgiri** [comment]
On both the platform getting same mg(metagraph) value , see below :

```
meta_info_def {
  stripped_op_list {
    op {
      name: "AddN"
      input_arg {
        name: "inputs"
        type_attr: "T"
        number_attr: "N"
      }
      output_arg {
        name: "sum"
        type_attr: "T"
      }
      attr {
        name: "N"
        type: "int"
        has_minimum: true
        minimum: 1
      }
      attr {
        name: "T"
        type: "type"
        allowed_values {
          list {
            type: DT_FLOAT
            type: DT_DOUBLE
            type: DT_INT32
            type: DT_UINT8
            type: DT_INT16
            type: DT_INT8
            type: DT_COMPLEX64
            type: DT_INT64
            type: DT_QINT8
            type: DT_QUINT8
            type: DT_QINT32
            type: DT_BFLOAT16
            type: DT_UINT16
            type: DT_COMPLEX128
            type: DT_HALF
            type: DT_UINT32
            type: DT_UINT64
            type: DT_VARIANT
          }
        }
      }
      is_aggregate: true
      is_commutative: true
    }
    op {
      name: "Const"
      output_arg {
        name: "output"
        type_attr: "dtype"
      }
      attr {
        name: "value"
        type: "tensor"
      }
      attr {
        name: "dtype"
        type: "type"
      }
    }
  }
  tensorflow_version: "1.9.0-rc0"
  tensorflow_git_version: "v1.8.0-3287-g5ae5ab4"
}
graph_def {
  node {
    name: "a"
    op: "Const"
    device: "/device:CPU:0"
    attr {
      key: "_output_shapes"
      value {
        list {
          shape {
          }
        }
      }
    }
    attr {
      key: "dtype"
      value {
        type: DT_INT32
      }
    }
    attr {
      key: "value"
      value {
        tensor {
          dtype: DT_INT32
          tensor_shape {
          }
          int_val: 10
        }
      }
    }
  }
  node {
    name: "b"
    op: "Const"
    device: "/device:CPU:0"
    attr {
      key: "_output_shapes"
      value {
        list {
          shape {
          }
        }
      }
    }
    attr {
      key: "dtype"
      value {
        type: DT_INT32
      }
    }
    attr {
      key: "value"
      value {
        tensor {
          dtype: DT_INT32
          tensor_shape {
          }
          int_val: 20
        }
      }
    }
  }
  node {
    name: "c"
    op: "AddN"
    input: "a"
    input: "b"
    device: "/device:CPU:0"
    attr {
      key: "N"
      value {
        i: 2
      }
    }
    attr {
      key: "T"
      value {
        type: DT_INT32
      }
    }
    attr {
      key: "_output_shapes"
      value {
        list {
          shape {
          }
        }
      }
    }
  }
  node {
    name: "d"
    op: "AddN"
    input: "b"
    input: "c"
    device: "/device:CPU:0"
    attr {
      key: "N"
      value {
        i: 2
      }
    }
    attr {
      key: "T"
      value {
        type: DT_INT32
      }
    }
    attr {
      key: "_output_shapes"
      value {
        list {
          shape {
          }
        }
      }
    }
  }
  versions {
    producer: 26
  }
}
collection_def {
  key: "train_op"
  value {
    node_list {
      value: "d:0"
    }
  }
}

```

However , `report = cost_analyzer.GenerateMemoryReport(mg)` line returns incorrect result on ppc64le :
```
Peak usage for device /job:localhost/replica:0/task:0/device:CPU:0: 12 bytes
  a:0 uses 4 bytes
  b:0 uses 4 bytes
  c:0 uses 4 bytes
```
  
Expected :
```
Peak usage for device /job:localhost/replica:0/task:0/device:CPU:0: 16 bytes
  a:0 uses 4 bytes
  b:0 uses 4 bytes
  d:0 uses 4 bytes
  c:0 uses 4 bytes
  
```

I have looked into the `GenerateMemoryReport() `function in file `tensorflow/python/grappler/cost_analyzer.py`, and got to know that the `peak_usage = cluster.DeterminePeakMemoryUsage(item) `line returning incorrect value.

Now looking into the DeterminePeakMemoryUsage() code.

**Comment by wdirons** [comment]
@sandipmgiri , this test is not failing for me on ppc64le.

This is how I run the entire unit test bucket:
git clone https://github.com/tensorflow/tensorflow
cd tensorflow
screen -L
export TF_BUILD_CONTAINER_TYPE="CPU.PPC64LE"
export TF_BUILD_PYTHON_VERSION="PYTHON2"
export TF_BUILD_IS_OPT="OPT"
export TF_BUILD_IS_PIP="NO_PIP"
export TF_BUILD_APPEND_ARGUMENTS="--test_tag_filters=-no_gpu,-no_oss,-oss_serial --color no"
./tensorflow/tools/ci_build/ci_parameterized_build.sh

Afterwards , I can use the docker image created (tf_ci.cpu.ppc64le) to run bazel test as you have above.

**Comment by sandipmgiri** [comment]
@wdirons Tried to execute the steps as you mentioned , however I'm getting the below error :  

```
./tensorflow/tools/ci_build/ci_parameterized_build.sh
Parameterized build starts at: Wed Jul  4 12:25:36 UTC 2018

Required build parameters:
  TF_BUILD_CONTAINER_TYPE=cpu.ppc64le
  TF_BUILD_PYTHON_VERSION=python2
  TF_BUILD_IS_OPT=opt
  TF_BUILD_IS_PIP=no_pip
Optional build parameters:
  TF_BUILD_DRY_RUN=
  TF_BUILD_MAVX=
  TF_BUILD_APPEND_CI_DOCKER_EXTRA_PARAMS=
  TF_BUILD_APPEND_ARGUMENTS=--test_tag_filters=-no_gpu,-no_oss,-oss_serial --color no
  TF_BUILD_BAZEL_TARGET=
  TF_BUILD_BAZEL_CLEAN=
  TF_BUILD_TEST_TUTORIALS=
  TF_BUILD_INTEGRATION_TESTS=
  TF_BUILD_RUN_BENCHMARKS=
  TF_BUILD_OPTIONS=
Exporting CI_DOCKER_EXTRA_PARAMS: -v /tmp/tmp.VAbHWZouts_ci_parameterized_build.sh:/tmp/tf_build.sh
Executing final command (/tmp/tmp.VAbHWZouts_ci_parameterized_build.sh)...
==========================================
#!/usr/bin/env bash
bazel test --test_output=errors -c opt --test_tag_filters=-no_gpu,-no_oss,-oss_serial,-benchmark-test --color no --distinct_host_configuration=false -- //tensorflow/... -//tensorflow/compiler/... -//tensorflow/contrib/lite/... //tensorflow/contrib/lite:context_test //tensorflow/contrib/lite:framework //tensorflow/contrib/lite:interpreter_test //tensorflow/contrib/lite:model_test //tensorflow/contrib/lite/toco:toco //tensorflow/contrib/lite:simple_memory_arena_test //tensorflow/contrib/lite:string_util_test //tensorflow/contrib/lite/kernels:activations_test //tensorflow/contrib/lite/kernels:add_test //tensorflow/contrib/lite/kernels:basic_rnn_test //tensorflow/contrib/lite/kernels:concatenation_test //tensorflow/contrib/lite/kernels:conv_test //tensorflow/contrib/lite/kernels:depthwise_conv_test //tensorflow/contrib/lite/kernels:embedding_lookup_test //tensorflow/contrib/lite/kernels:embedding_lookup_sparse_test //tensorflow/contrib/lite/kernels:fully_connected_test //tensorflow/contrib/lite/kernels:hashtable_lookup_test //tensorflow/contrib/lite/kernels:local_response_norm_test //tensorflow/contrib/lite/kernels:lsh_projection_test //tensorflow/contrib/lite/kernels:lstm_test //tensorflow/contrib/lite/kernels:l2norm_test //tensorflow/contrib/lite/kernels:mul_test //tensorflow/contrib/lite/kernels:pooling_test //tensorflow/contrib/lite/kernels:reshape_test //tensorflow/contrib/lite/kernels:resize_bilinear_test //tensorflow/contrib/lite/kernels:skip_gram_test //tensorflow/contrib/lite/kernels:softmax_test //tensorflow/contrib/lite/kernels:space_to_depth_test //tensorflow/contrib/lite/kernels:svdf_test
==========================================

WORKSPACE: /root/tensorflow
CI_DOCKER_EXTRA_PARAMS: -v /tmp/tmp.VAbHWZouts_ci_parameterized_build.sh:/tmp/tf_build.sh
COMMAND: /tmp/tf_build.sh
CI_COMMAND_PREFIX: ./tensorflow/tools/ci_build/builds/with_the_same_user ./tensorflow/tools/ci_build/builds/configured cpu.ppc64le
CONTAINER_TYPE: cpu.ppc64le
BUILD_TAG: tf_ci
  (docker container name will be tf_ci.cpu.ppc64le)

Building container (tf_ci.cpu.ppc64le)...
Sending build context to Docker daemon 390.7 kB
Step 1 : FROM ubuntu:16.04
 ---> a267250427b3
Step 2 : LABEL maintainer "William Irons <wdirons@us.ibm.com>"
 ---> Using cache
 ---> f470162bd3d1
Step 3 : COPY install/*.sh /install/
 ---> Using cache
 ---> 59704b8bc034
Step 4 : RUN /install/install_bootstrap_deb_packages.sh
 ---> Using cache
 ---> 82a4ac2345c4
Step 5 : RUN add-apt-repository -y ppa:openjdk-r/ppa
 ---> Using cache
 ---> ac7be5fc321f
Step 6 : RUN /install/install_deb_packages.sh
 ---> Using cache
 ---> b30410c2d510
Step 7 : RUN apt-get update && apt-get install -y libopenblas-dev
 ---> Using cache
 ---> 65b05a51b4a7
Step 8 : RUN /install/install_hdf5_ppc64le.sh
 ---> Using cache
 ---> b0c5826da7fc
Step 9 : RUN /install/install_pip_packages.sh
 ---> Using cache
 ---> 21d9e8b7e9bf
Step 10 : RUN /install/install_bazel_from_source.sh
 ---> Using cache
 ---> e4b783fec046
Step 11 : RUN /install/install_proto3.sh
 ---> Using cache
 ---> b90d0afd44f5
Step 12 : RUN /install/install_buildifier_from_source.sh
 ---> Using cache
 ---> bbbe9d957269
Step 13 : RUN /install/install_auditwheel.sh
 ---> Using cache
 ---> 7c86f6b0e0bb
Step 14 : RUN /install/install_golang_ppc64le.sh
 ---> Using cache
 ---> e452271dfd67
Step 15 : COPY install/.bazelrc /etc/bazel.bazelrc
 ---> Using cache
 ---> 44e52aaaa7fa
Successfully built 44e52aaaa7fa
Running '/tmp/tf_build.sh' inside tf_ci.cpu.ppc64le...
docker: Error response from daemon: oci runtime error: exec: "./tensorflow/tools/ci_build/builds/with_the_same_user": stat ./tensorflow/tools/ci_build/builds/with_the_same_user: no such file or directory.
time="2018-07-04T12:25:36Z" level=error msg="error getting events from daemon: net/http: request canceled"
```

**Comment by wdirons** [comment]
@sandipmgiri , I'll work with you offline. I don't want to confused this issue trying to debug the unit test process.

**Comment by sandipmgiri** [comment]
Test passed successfully on high end vm. Closing this issue.
