### ISSUE TITLE
//tensorflow/contrib/distributions:matrix_inverse_tril_test fails on ppc64le

### ISSUE THREAD

**Issue by sandipmgiri** [tensorflow/tensorflow#20013]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:N/A
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
      Ubuntu 16.04 (ppc64le)
- **TensorFlow installed from (source or binary)**:
      Installed from source
- **TensorFlow version (use command below)**:
      TF master
- **Python version**: 
     Python 2.7.5
- **Bazel version (if compiling from source)**:
     bazel-0.11.1
- **CUDA/cuDNN version**:
     NA
- **GPU model and memory**:
      NA
- **Exact command to reproduce**:
 `bazel test -c opt --jobs 1 -k --cache_test_results=no --test_output=errors  //tensorflow/contrib/distributions:matrix_inverse_tril_test`

### Describe the problem
Getting error `InvalidArgumentError: assertion failed: [Input must be lower triangular.] [Condition x == y did not hold element-wise:]`.
Not sure what exactly causing this issue, need to investigate.

### Source code / logs
```
E.......
======================================================================
ERROR: testBatch (__main__.MatrixInverseTriLBijectorTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/78afe71156c58ea89dc510bdb03ba2b0/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/distributions/matrix_inverse_tril_test.runfiles/org_tensorflow/tensorflow/python/framework/test_util.py", line 625, in decorated
    f(self, **kwargs)
  File "/root/.cache/bazel/_bazel_root/78afe71156c58ea89dc510bdb03ba2b0/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/distributions/matrix_inverse_tril_test.runfiles/org_tensorflow/tensorflow/contrib/distributions/python/kernel_tests/bijectors/matrix_inverse_tril_test.py", line 110, in testBatch
    y_, x_back_, fldj_, ildj_ = self.evaluate([y, x_back, fldj, ildj])
  File "/root/.cache/bazel/_bazel_root/78afe71156c58ea89dc510bdb03ba2b0/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/distributions/matrix_inverse_tril_test.runfiles/org_tensorflow/tensorflow/python/framework/test_util.py", line 864, in evaluate
    return sess.run(tensors)
  File "/root/.cache/bazel/_bazel_root/78afe71156c58ea89dc510bdb03ba2b0/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/distributions/matrix_inverse_tril_test.runfiles/org_tensorflow/tensorflow/python/client/session.py", line 877, in run
    run_metadata_ptr)
  File "/root/.cache/bazel/_bazel_root/78afe71156c58ea89dc510bdb03ba2b0/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/distributions/matrix_inverse_tril_test.runfiles/org_tensorflow/tensorflow/python/client/session.py", line 1100, in _run
    feed_dict_tensor, options, run_metadata)
  File "/root/.cache/bazel/_bazel_root/78afe71156c58ea89dc510bdb03ba2b0/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/distributions/matrix_inverse_tril_test.runfiles/org_tensorflow/tensorflow/python/client/session.py", line 1272, in _do_run
    run_metadata)
  File "/root/.cache/bazel/_bazel_root/78afe71156c58ea89dc510bdb03ba2b0/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/distributions/matrix_inverse_tril_test.runfiles/org_tensorflow/tensorflow/python/client/session.py", line 1291, in _do_call
    raise type(e)(node_def, op, message)
InvalidArgumentError: assertion failed: [Input must be lower triangular.] [Condition x == y did not hold element-wise:] [x (matrix_inverse_tril_1/inverse/MatrixBandPart:0) = ] [[[[0 2.77555756e-17][0]]]...] [y (matrix_inverse_tril_1/inverse/zeros_like:0) = ] [[[[0 0][0]]]...]
         [[Node: matrix_inverse_tril_1/inverse/assert_equal_1/Assert/AssertGuard/Assert = Assert[T=[DT_STRING, DT_STRING, DT_STRING, DT_FLOAT, DT_STRING, DT_FLOAT], summarize=3, _device="/job:localhost/replica:0/task:0/device:CPU:0"](matrix_inverse_tril_1/inverse/assert_equal_1/Assert/AssertGuard/Assert/Switch, matrix_inverse_tril_1/inverse/assert_equal_1/Assert/AssertGuard/Assert/data_0, matrix_inverse_tril_1/inverse/assert_equal_1/Assert/AssertGuard/Assert/data_1, matrix_inverse_tril_1/inverse/assert_equal_1/Assert/AssertGuard/Assert/data_2, matrix_inverse_tril_1/inverse/assert_equal_1/Assert/AssertGuard/Assert/Switch_1, matrix_inverse_tril_1/inverse/assert_equal_1/Assert/AssertGuard/Assert/data_4, matrix_inverse_tril_1/inverse/assert_equal_1/Assert/AssertGuard/Assert/Switch_2)]]

Caused by op u'matrix_inverse_tril_1/inverse/assert_equal_1/Assert/AssertGuard/Assert', defined at:
  File "/root/.cache/bazel/_bazel_root/78afe71156c58ea89dc510bdb03ba2b0/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/distributions/matrix_inverse_tril_test.runfiles/org_tensorflow/tensorflow/contrib/distributions/python/kernel_tests/bijectors/matrix_inverse_tril_test.py", line 190, in <module>
    test.main()
  File "/root/.cache/bazel/_bazel_root/78afe71156c58ea89dc510bdb03ba2b0/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/distributions/matrix_inverse_tril_test.runfiles/org_tensorflow/tensorflow/python/platform/test.py", line 64, in main
    return _googletest.main(argv)
  File "/root/.cache/bazel/_bazel_root/78afe71156c58ea89dc510bdb03ba2b0/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/distributions/matrix_inverse_tril_test.runfiles/org_tensorflow/tensorflow/python/platform/googletest.py", line 100, in main
    benchmark.benchmarks_main(true_main=main_wrapper)
  File "/root/.cache/bazel/_bazel_root/78afe71156c58ea89dc510bdb03ba2b0/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/distributions/matrix_inverse_tril_test.runfiles/org_tensorflow/tensorflow/python/platform/benchmark.py", line 344, in benchmarks_main
    true_main()
  File "/root/.cache/bazel/_bazel_root/78afe71156c58ea89dc510bdb03ba2b0/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/distributions/matrix_inverse_tril_test.runfiles/org_tensorflow/tensorflow/python/platform/googletest.py", line 99, in main_wrapper
    return app.run(main=g_main, argv=args)
  File "/root/.cache/bazel/_bazel_root/78afe71156c58ea89dc510bdb03ba2b0/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/distributions/matrix_inverse_tril_test.runfiles/org_tensorflow/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/root/.cache/bazel/_bazel_root/78afe71156c58ea89dc510bdb03ba2b0/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/distributions/matrix_inverse_tril_test.runfiles/org_tensorflow/tensorflow/python/platform/googletest.py", line 70, in g_main
    return unittest_main(argv=argv)
  File "/usr/lib/python2.7/unittest/main.py", line 95, in __init__
    self.runTests()
  File "/usr/lib/python2.7/unittest/main.py", line 232, in runTests
    self.result = testRunner.run(self.test)
  File "/usr/lib/python2.7/unittest/runner.py", line 151, in run
    test(result)
  File "/usr/lib/python2.7/unittest/suite.py", line 70, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python2.7/unittest/suite.py", line 108, in run
    test(result)
  File "/usr/lib/python2.7/unittest/suite.py", line 70, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python2.7/unittest/suite.py", line 108, in run
    test(result)
  File "/usr/lib/python2.7/unittest/case.py", line 393, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/root/.cache/bazel/_bazel_root/78afe71156c58ea89dc510bdb03ba2b0/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/distributions/matrix_inverse_tril_test.runfiles/org_tensorflow/tensorflow/python/framework/test_util.py", line 625, in decorated
    f(self, **kwargs)
  File "/root/.cache/bazel/_bazel_root/78afe71156c58ea89dc510bdb03ba2b0/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/distributions/matrix_inverse_tril_test.runfiles/org_tensorflow/tensorflow/contrib/distributions/python/kernel_tests/bijectors/matrix_inverse_tril_test.py", line 106, in testBatch
    x_back = inv.inverse(x_inv_)
  File "/root/.cache/bazel/_bazel_root/78afe71156c58ea89dc510bdb03ba2b0/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/distributions/matrix_inverse_tril_test.runfiles/org_tensorflow/tensorflow/python/ops/distributions/bijector_impl.py", line 800, in inverse
    return self._call_inverse(y, name)
  File "/root/.cache/bazel/_bazel_root/78afe71156c58ea89dc510bdb03ba2b0/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/distributions/matrix_inverse_tril_test.runfiles/org_tensorflow/tensorflow/python/ops/distributions/bijector_impl.py", line 779, in _call_inverse
    mapping = mapping.merge(x=self._inverse(y, **kwargs))
  File "/root/.cache/bazel/_bazel_root/78afe71156c58ea89dc510bdb03ba2b0/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/distributions/matrix_inverse_tril_test.runfiles/org_tensorflow/tensorflow/contrib/distributions/python/ops/bijectors/matrix_inverse_tril.py", line 80, in _inverse
    return self._forward(y)
  File "/root/.cache/bazel/_bazel_root/78afe71156c58ea89dc510bdb03ba2b0/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/distributions/matrix_inverse_tril_test.runfiles/org_tensorflow/tensorflow/contrib/distributions/python/ops/bijectors/matrix_inverse_tril.py", line 74, in _forward
    with ops.control_dependencies(self._assertions(x)):
  File "/root/.cache/bazel/_bazel_root/78afe71156c58ea89dc510bdb03ba2b0/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/distributions/matrix_inverse_tril_test.runfiles/org_tensorflow/tensorflow/contrib/distributions/python/ops/bijectors/matrix_inverse_tril.py", line 138, in _assertions
    message="Input must be lower triangular.")
  File "/root/.cache/bazel/_bazel_root/78afe71156c58ea89dc510bdb03ba2b0/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/distributions/matrix_inverse_tril_test.runfiles/org_tensorflow/tensorflow/python/ops/check_ops.py", line 382, in assert_equal
    return control_flow_ops.Assert(condition, data, summarize=summarize)
  File "/root/.cache/bazel/_bazel_root/78afe71156c58ea89dc510bdb03ba2b0/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/distributions/matrix_inverse_tril_test.runfiles/org_tensorflow/tensorflow/python/util/tf_should_use.py", line 118, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs))
  File "/root/.cache/bazel/_bazel_root/78afe71156c58ea89dc510bdb03ba2b0/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/distributions/matrix_inverse_tril_test.runfiles/org_tensorflow/tensorflow/python/ops/control_flow_ops.py", line 151, in Assert
    guarded_assert = cond(condition, no_op, true_assert, name="AssertGuard")
  File "/root/.cache/bazel/_bazel_root/78afe71156c58ea89dc510bdb03ba2b0/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/distributions/matrix_inverse_tril_test.runfiles/org_tensorflow/tensorflow/python/util/deprecation.py", line 432, in new_func
    return func(*args, **kwargs)
  File "/root/.cache/bazel/_bazel_root/78afe71156c58ea89dc510bdb03ba2b0/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/distributions/matrix_inverse_tril_test.runfiles/org_tensorflow/tensorflow/python/ops/control_flow_ops.py", line 2049, in cond
    orig_res_f, res_f = context_f.BuildCondBranch(false_fn)
  File "/root/.cache/bazel/_bazel_root/78afe71156c58ea89dc510bdb03ba2b0/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/distributions/matrix_inverse_tril_test.runfiles/org_tensorflow/tensorflow/python/ops/control_flow_ops.py", line 1890, in BuildCondBranch
    original_result = fn()
  File "/root/.cache/bazel/_bazel_root/78afe71156c58ea89dc510bdb03ba2b0/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/distributions/matrix_inverse_tril_test.runfiles/org_tensorflow/tensorflow/python/ops/control_flow_ops.py", line 149, in true_assert
    condition, data, summarize, name="Assert")
  File "/root/.cache/bazel/_bazel_root/78afe71156c58ea89dc510bdb03ba2b0/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/distributions/matrix_inverse_tril_test.runfiles/org_tensorflow/tensorflow/python/ops/gen_logging_ops.py", line 51, in _assert
    name=name)
  File "/root/.cache/bazel/_bazel_root/78afe71156c58ea89dc510bdb03ba2b0/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/distributions/matrix_inverse_tril_test.runfiles/org_tensorflow/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/root/.cache/bazel/_bazel_root/78afe71156c58ea89dc510bdb03ba2b0/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/distributions/matrix_inverse_tril_test.runfiles/org_tensorflow/tensorflow/python/util/deprecation.py", line 432, in new_func
    return func(*args, **kwargs)
  File "/root/.cache/bazel/_bazel_root/78afe71156c58ea89dc510bdb03ba2b0/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/distributions/matrix_inverse_tril_test.runfiles/org_tensorflow/tensorflow/python/framework/ops.py", line 3206, in create_op
    op_def=op_def)
  File "/root/.cache/bazel/_bazel_root/78afe71156c58ea89dc510bdb03ba2b0/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/distributions/matrix_inverse_tril_test.runfiles/org_tensorflow/tensorflow/python/framework/ops.py", line 1701, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): assertion failed: [Input must be lower triangular.] [Condition x == y did not hold element-wise:] [x (matrix_inverse_tril_1/inverse/MatrixBandPart:0) = ] [[[[0 2.77555756e-17][0]]]...] [y (matrix_inverse_tril_1/inverse/zeros_like:0) = ] [[[[0 0][0]]]...]
         [[Node: matrix_inverse_tril_1/inverse/assert_equal_1/Assert/AssertGuard/Assert = Assert[T=[DT_STRING, DT_STRING, DT_STRING, DT_FLOAT, DT_STRING, DT_FLOAT], summarize=3, _device="/job:localhost/replica:0/task:0/device:CPU:0"](matrix_inverse_tril_1/inverse/assert_equal_1/Assert/AssertGuard/Assert/Switch, matrix_inverse_tril_1/inverse/assert_equal_1/Assert/AssertGuard/Assert/data_0, matrix_inverse_tril_1/inverse/assert_equal_1/Assert/AssertGuard/Assert/data_1, matrix_inverse_tril_1/inverse/assert_equal_1/Assert/AssertGuard/Assert/data_2, matrix_inverse_tril_1/inverse/assert_equal_1/Assert/AssertGuard/Assert/Switch_1, matrix_inverse_tril_1/inverse/assert_equal_1/Assert/AssertGuard/Assert/data_4, matrix_inverse_tril_1/inverse/assert_equal_1/Assert/AssertGuard/Assert/Switch_2)]]


----------------------------------------------------------------------
Ran 8 tests in 3.177s
```

**Comment by karmel** [comment]
@jvdillon , can you take a look?

**Comment by wdirons** [comment]
I take the failing example, and run it thru numpy's linalg inverse method the inverse of 0 doesn't remain as 0 like on x86, it is populated with some non-logical value. This is breaking the method.

Recreatable testcase:

docker run -idt --name $USER-temp ubuntu:18.04 bash
docker attach $USER-temp

apt update
apt install vim python python-pip
pip install numpy
vi test.py
python test.py



where test.py is:

import numpy as np


if __name__ == "__main__":
    x_ = np.array([[[[1., 0.],
                     [2., 3.]]],
                   [[[4., 0.],
                     [5., -6.]]]], dtype=np.float32)
    print(x_)
    x_inv_ = np.linalg.inv(x_)
    print(x_inv_)



x86:

root@08d7b342534c:/# python test.py
[[[[ 1.  0.]
   [ 2.  3.]]]


 [[[ 4.  0.]
   [ 5. -6.]]]]
[[[[ 1.          0.        ]
   [-0.6666667   0.33333334]]]


 [[[ 0.25        0.        ]
   [ 0.20833333 -0.16666667]]]]




ppc64le: 

root@68c0b6023e55:/# python test.py
[[[[ 1.  0.]
   [ 2.  3.]]]


 [[[ 4.  0.]
   [ 5. -6.]]]]
[[[[ 1.0000000e+00  2.7755576e-17]
   [-6.6666669e-01  3.3333334e-01]]]


 [[[ 2.5000000e-01  1.1102230e-17]
   [ 2.0833333e-01 -1.6666667e-01]]]]
root@68c0b6023e55:/#

**Comment by jayfurmanek** [comment]
The inverse of 0 is technically undefined, right?

**Comment by wdirons** [comment]
I opened an issue against numpy on this: https://github.com/numpy/numpy/issues/11445

**Comment by wdirons** [comment]
@jvdillon , would you be able to review the PR #20477 to fix this issue?

I took your suggestion from the numpy issue.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @jvdillon: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.
