### ISSUE TITLE
Failed to create CUPTI subcriber when profiling on servers with no GPU's

### ISSUE THREAD

**Issue by majoros** [tensorflow/tensorflow#20041]
------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:

Custom i guess? I took the first example on the [Using GPUs](https://www.tensorflow.org/programmers_guide/using_gpu) page and added profiling to it (code below).

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:

Red Hat Enterprise Linux Server release 6.7 (Santiago)

- **TensorFlow installed from (source or binary)**:

Source

- **TensorFlow version (use command below)**:

>>> import tensorflow as tf
>>> print(tf.GIT_VERSION, tf.VERSION)
('unknown', '1.8.0')

- **Python version**:

Built for both version of python same outcome for both
2.7.14
3.6.5

- **Bazel version (if compiling from source)**:

0.11.1

- **GCC/Compiler version (if compiling from source)**:

4.9.3

- **CUDA/cuDNN version**:

CUDA: 9.1.85
cuDNN: 7.0.5

- **GPU model and memory**:

My GPU test server has the following GPU's and driver version

```bash
$ nvidia-smi
Thu Jun 14 12:58:15 2018
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.30                 Driver Version: 390.30                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K40m          On   | 00000000:0B:00.0 Off |                    0 |
| N/A   24C    P8    19W / 235W |    207MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K40m          On   | 00000000:81:00.0 Off |                    0 |
| N/A   25C    P8    20W / 235W |    207MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

- **Exact command to reproduce**:

Run the following script with TF built with GPU support on a server without GPU's with the cuda stub and cupti extras library path's in your LD_LIBRARY_PATH environment variable.

```python
import tensorflow as tf
import os
trace_dir = '/tmp/tf_trace'

builder = tf.profiler.ProfileOptionBuilder
opts = builder(builder.time_and_memory()).order_by('micros').build()

with tf.contrib.tfprof.ProfileContext(trace_dir, trace_steps=[], dump_steps=[]) as pctx:
    a = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[2, 3], name='a')
    b = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[3, 2], name='b')
    c = tf.matmul(a, b)
    with tf.Session() as sess:
        pctx.trace_next_step()
        pctx.dump_next_step()
        _ = sess.run(c)
        pctx.profiler.profile_operations(options=opts)

```

Works perfect on servers with GPU's fails on servers without GPU's

### Describe the problem

I am attempting to make a single, portable version of TensorFlow 1.8.0 with XLA and GPU support. Everything works as expected on servers with GPU's.
The only thing that’s not working on servers without GPU's is when you run a session in a profiler context, you get the below message.

The error seems fairly straight forward. The calls to the libcupti are failing since there are no GPU's or cuda drivers installed.

How feasible would it be to have TensorFlow fallback(or do a pre-check) to CPU only profiling if TensorFlow was built with GPU support but there are no GPU's on the servers?

### Source code / logs

Note: I manually truncated the paths of the log files up until the lib directory.

$ python ~/tmp/tfprof.py
2018-06-14 17:32:07.348377: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-06-14 17:32:07.354865: E tensorflow/stream_executor/cuda/cuda_driver.cc:406] failed call to cuInit: CUresult(-1)
2018-06-14 17:32:07.354921: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:145] kernel driver does not appear to be running on this host (HOST_NAME): /proc/driver/nvidia/version does not exist
None
2018-06-14 17:32:07.360597: I tensorflow/stream_executor/dso_loader.cc:152] successfully opened CUDA library libcupti.so.9.1 locally
2018-06-14 17:32:07.460813: E tensorflow/core/platform/default/device_tracer.cc:134] cuda call ActivityRegisterCallbacks(BufferRequested, BufferCompleted) failed 15
Failed to create CUPTI subcriber.
Traceback (most recent call last):
  File "lib/tensorflow/python/client/session.py", line 1323, in _do_call
    return fn(*args)
  File "/home/o594256/tmp/tf18/lib/tensorflow/python/client/session.py", line 1308, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "lib/tensorflow/python/client/session.py", line 1411, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InternalError: Failed to create CUPTI subcriber.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/tfprof.py", line 24, in <module>
    _ = sess.run(c)
  File "lib/tensorflow/python/profiler/profile_context.py", line 74, in _profiled_run
    fetches, feed_dict, options, run_metadata)
  File "lib/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "lib/tensorflow/python/client/session.py", line 1136, in _run
    feed_dict_tensor, options, run_metadata)
  File "lib/tensorflow/python/client/session.py", line 1317, in _do_run
    run_metadata)
  File "lib/tensorflow/python/client/session.py", line 1337, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Failed to create CUPTI subcriber.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @rohan100jain: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @rohan100jain: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @rohan100jain: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @zheng-xq: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @zheng-xq: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @zheng-xq: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @robieta: It has been 59 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @robieta: It has been 74 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @robieta: It has been 89 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @robieta: It has been 104 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @robieta: It has been 119 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by HongmingHUANG** [comment]
I got the same problem with you, with tensorflow 1.9.0 and cuda 10.0.
How do you fix the problem? I am trying to update the tensorflow now.

**Comment by Asphelzhn** [comment]
the same problem occured in tensorflow 1.12.0 and cuda 9.0 , how can I fix it?

**Comment by Hawk0826** [comment]
I got the same problem in tensorflow 1.5.0 and cuda 10.1 , how can I fix the problem?

**Comment by rao208** [comment]
This answer from @trisolaran from https://github.com/tensorflow/tensorflow/issues/35860 helped me to solve many issues:

> Adding options nvidia "NVreg_RestrictProfilingToAdminUsers=0" to /etc/modprobe.d/nvidia-kernel-common.conf
> and reboot should resolve the permission issue.

Try it...

**Comment by rthadur** [comment]
Yes the above comment helped to resolve the issue. Thank you, closing this issue.
