### ISSUE TITLE
Fail to find the dnn implementation.

### ISSUE THREAD

**Issue by hadaev8** [tensorflow/tensorflow#20067]
Last keras, tensorflow.
Using anaconda with jupiter notebook.
It sometimes breaks then I use CuDNNGRU.
Restarting jupiter helps.

UnknownError: Fail to find the dnn implementation.
	 [[Node: cu_dnngru_1/CudnnRNN = CudnnRNN[T=DT_FLOAT, direction="unidirectional", dropout=0, input_mode="linear_input", is_training=true, rnn_mode="gru", seed=87654321, seed2=0, _device="/job:localhost/replica:0/task:0/device:GPU:0"](cu_dnngru_1/transpose, cu_dnngru_1/ExpandDims_1, cu_dnngru_1/Const_1, cu_dnngru_1/concat)]]
	 [[Node: loss/mul/_73 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_618_loss/mul", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'cu_dnngru_1/CudnnRNN', defined at:
  File "e:\neuro_projects\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "e:\neuro_projects\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "e:\neuro_projects\anaconda3\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "e:\neuro_projects\anaconda3\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "e:\neuro_projects\anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 486, in start
    self.io_loop.start()
  File "e:\neuro_projects\anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 127, in start
    self.asyncio_loop.run_forever()
  File "e:\neuro_projects\anaconda3\lib\asyncio\base_events.py", line 421, in run_forever
    self._run_once()
  File "e:\neuro_projects\anaconda3\lib\asyncio\base_events.py", line 1431, in _run_once
    handle._run()
  File "e:\neuro_projects\anaconda3\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "e:\neuro_projects\anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 117, in _handle_events
    handler_func(fileobj, events)
  File "e:\neuro_projects\anaconda3\lib\site-packages\tornado\stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "e:\neuro_projects\anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 450, in _handle_events
    self._handle_recv()
  File "e:\neuro_projects\anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 480, in _handle_recv
    self._run_callback(callback, msg)
  File "e:\neuro_projects\anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 432, in _run_callback
    callback(*args, **kwargs)
  File "e:\neuro_projects\anaconda3\lib\site-packages\tornado\stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "e:\neuro_projects\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "e:\neuro_projects\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "e:\neuro_projects\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "e:\neuro_projects\anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "e:\neuro_projects\anaconda3\lib\site-packages\ipykernel\zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "e:\neuro_projects\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2662, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "e:\neuro_projects\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2785, in _run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "e:\neuro_projects\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2903, in run_ast_nodes
    if self.run_code(code, result):
  File "e:\neuro_projects\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-1-982a486f943a>", line 44, in <module>
    i = CuDNNGRU(128)(i)
  File "e:\neuro_projects\anaconda3\lib\site-packages\keras\layers\recurrent.py", line 500, in __call__
    return super(RNN, self).__call__(inputs, **kwargs)
  File "e:\neuro_projects\anaconda3\lib\site-packages\keras\engine\base_layer.py", line 460, in __call__
    output = self.call(inputs, **kwargs)
  File "e:\neuro_projects\anaconda3\lib\site-packages\keras\layers\cudnn_recurrent.py", line 90, in call
    output, states = self._process_batch(inputs, initial_state)
  File "e:\neuro_projects\anaconda3\lib\site-packages\keras\layers\cudnn_recurrent.py", line 297, in _process_batch
    is_training=True)
  File "e:\neuro_projects\anaconda3\lib\site-packages\tensorflow\contrib\cudnn_rnn\python\ops\cudnn_rnn_ops.py", line 1552, in __call__
    seed=self._seed)
  File "e:\neuro_projects\anaconda3\lib\site-packages\tensorflow\contrib\cudnn_rnn\python\ops\cudnn_rnn_ops.py", line 941, in _cudnn_rnn_no_input_c
    direction, dropout, seed, name)
  File "e:\neuro_projects\anaconda3\lib\site-packages\tensorflow\contrib\cudnn_rnn\python\ops\cudnn_rnn_ops.py", line 855, in _cudnn_rnn
    name=name)
  File "e:\neuro_projects\anaconda3\lib\site-packages\tensorflow\python\ops\gen_cudnn_rnn_ops.py", line 143, in cudnn_rnn
    is_training=is_training, name=name)
  File "e:\neuro_projects\anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "e:\neuro_projects\anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3309, in create_op
    op_def=op_def)
  File "e:\neuro_projects\anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1669, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

UnknownError (see above for traceback): Fail to find the dnn implementation.
	 [[Node: cu_dnngru_1/CudnnRNN = CudnnRNN[T=DT_FLOAT, direction="unidirectional", dropout=0, input_mode="linear_input", is_training=true, rnn_mode="gru", seed=87654321, seed2=0, _device="/job:localhost/replica:0/task:0/device:GPU:0"](cu_dnngru_1/transpose, cu_dnngru_1/ExpandDims_1, cu_dnngru_1/Const_1, cu_dnngru_1/concat)]]
	 [[Node: loss/mul/_73 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_618_loss/mul", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by hadaev8** [comment]
Windows 10
tensorflow tf-nightly-gpu
cuda 9 cudnn 7
nvidia gtx 760

`import pandas as pd
import numpy as np
import os
from time import *
import matplotlib.pyplot as plt
%matplotlib inline

from keras.models import Model
from keras.layers import Input, Dense, Reshape, Dropout, SimpleRNN, CuDNNGRU, CuDNNLSTM, LeakyReLU
from keras.callbacks import TerminateOnNaN, EarlyStopping, ReduceLROnPlateau

from sklearn.preprocessing import MinMaxScaler
from sklearn.utils import shuffle

work_dir = r'E:\neuro_projects\morda'

data = pd.read_csv(os.path.join(work_dir, 'train.tsv'), delim_whitespace=True, names=[str(i) for i in range(101)])
data = shuffle(data)
scaler = MinMaxScaler()
data = pd.DataFrame(scaler.fit_transform(data), columns=data.columns)
x = data[data.columns[:-1]]
y = data['100']
x_train = x[:8000]
x_test = x[8000:]
y_train = y[:8000]
y_test = y[8000:]

lr_reducer = ReduceLROnPlateau(monitor='val_loss', factor=0.9,
                               cooldown=1,
                               patience=10,
                               verbose=1,
                               min_lr=1e-8)
nan = TerminateOnNaN()
stop = EarlyStopping(monitor='val_loss', min_delta=0, patience=200, verbose=1, mode='auto')
callbacks = [lr_reducer, nan, stop]
#test = pd.read_csv(os.path.join(work_dir, 'test.tsv'), delim_whitespace=True, names=[str(i) for i in range(101)])
#x_test = test[test.columns[:-1]]
#y_test = test['100']

def test_model():
    y_pred = model.predict(x_test)
    y_pred = y_pred/scaler.scale_[-1]
    from sklearn.metrics import mean_absolute_error
    print(mean_absolute_error(data['100'][8000:], y_pred))
    

inp = Input(shape=(x_test.shape[1],))
i = inp
i = Reshape((1, x_test.shape[1]))(i)

i = CuDNNGRU(256)(i)
i = LeakyReLU()(i)
#i = Dropout(0.3)(i)

i = Dense(1)(i)

model = Model(inp, i)

model.compile(loss='mae', optimizer='adam')
#model.summary()
timer = time()
history = model.fit(x_train, y_train,
                      epochs=10000,
                      batch_size=64,
                      verbose=2,
                      validation_data=(x_test, y_test),
                      callbacks=callbacks
                   )
plt.plot(history.history['loss'][10:])
plt.plot(history.history['val_loss'][10:])
plt.title('model loss')
plt.ylabel('loss')
plt.xlabel('epoch')
plt.legend(['train', 'test'], loc='upper left')
plt.show()
print(history.history['loss'][-1], history.history['val_loss'][-1])
print((time()-timer)/60)
test_model()`

**Comment by tensorflowbutler** [comment]
Nagging Assignee @shivaniag: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @shivaniag: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by yoonforh** [comment]
Hi, there. I also met the same problem with CuDNN GRU.

I know that working example of cudnn lstm exists (below link), and modified it to use gru instead of lstm.
https://gist.github.com/protoget/9b45881f23c96e201a90581c8f4b692d

// tested gru version
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import numpy as np

import tensorflow as tf


shape = [2, 2, 2]
n_cell_dim = 2

class TestCuDNN(object) :
    def init_vars(self, sess):
      sess.run(tf.global_variables_initializer())


    def train_graph(self):
      with tf.Graph().as_default(), tf.device('/gpu:0'):
        with tf.Session() as sess :
          is_training = True

          inputs = tf.random_uniform(shape, dtype=tf.float32)

          with tf.variable_scope('A', reuse=tf.AUTO_REUSE) as scope:
              gru = tf.contrib.cudnn_rnn.CudnnGRU(
                  num_layers=1,
                  num_units=n_cell_dim,
                  direction='bidirectional',
                  dtype=tf.float32)
              gru.build(inputs.get_shape())
              outputs, output_states = gru(inputs, training=is_training)

          with tf.variable_scope('B', reuse=tf.AUTO_REUSE) as scope:
              gru2 = tf.contrib.cudnn_rnn.CudnnGRU(
                  num_layers=1,
                  num_units=n_cell_dim,
                  direction='bidirectional',
                  dtype=tf.float32)
              gru2.build(inputs.get_shape())
              outputs2, output_states2 = gru2(inputs, training=is_training)

          with tf.device('/cpu:0'):
            saver = tf.train.Saver()

          self.dump_graph('before save')
        
          self.init_vars(sess)
          saver.save(sess, '/tmp/cudnn_gru_test')


    def inf_graph(self):
      with tf.Graph().as_default(), tf.device('/cpu:0'):
        with tf.Session() as sess:
          inputs = tf.random_uniform(shape, dtype=tf.float32)
          with tf.variable_scope('A', reuse=tf.AUTO_REUSE) as scope:
                outputs = self.do_inference(inputs)

          with tf.variable_scope('B', reuse=tf.AUTO_REUSE) as scope:
                outputs2 = self.do_inference(inputs)
                
          # debug graphs
          g = tf.get_default_graph()
          print('default tf graph :', g)
          keys = g.get_all_collection_keys()
          print('current name scope :', g.get_name_scope())
          for key in keys :
                print('all graph (', key, ')  :', g.get_collection(key))
          print('current name scope :', g.get_name_scope())
            
          reader = tf.train.NewCheckpointReader('/tmp/cudnn_test')
          for var_name in reader.get_variable_to_shape_map() :
                print(var_name)
   
                
          saver = tf.train.Saver()

          saver.restore(sess, '/tmp/cudnn_gru_test')
          print(sess.run([outputs, outputs2]))

    def do_inference(self, inputs) :
      single_cell = lambda: tf.contrib.cudnn_rnn.CudnnCompatibleGRUCell(
          n_cell_dim, reuse=tf.get_variable_scope().reuse)

      gru_fw_cell = [single_cell() for _ in range(1)]
      print('gru fw cell graph :', gru_fw_cell[0].graph)
      gru_bw_cell = [single_cell() for _ in range(1)]
      (outputs, output_state_fw,
       output_state_bw) = tf.contrib.rnn.stack_bidirectional_dynamic_rnn(
           gru_fw_cell,
           gru_bw_cell,
           inputs,
           dtype=tf.float32,
           time_major=True)
      return outputs

    def dump_graph(self, where) :
        print('')

        print('--- dumping tensorflow graph [', where, '] ---')
        g = tf.get_default_graph()
        print('default tf graph :', g)

        # debug graphs
        keys = g.get_all_collection_keys()
        print('current name scope :', g.get_name_scope())
        for key in keys :
            print('all graph (', key, ')  :', g.get_collection(key))
        print('') 
        print('')
    
    def main(self):
        with tf.Graph().as_default() :
          print('default graph :', tf.get_default_graph())
          self.train_graph()
        with tf.Graph().as_default() :
          print('default graph :', tf.get_default_graph())
          self.inf_graph()
        print('finishes')  

The result is as follows : 

default graph : <tensorflow.python.framework.ops.Graph object at 0x000001D9A04742E8>

--- dumping tensorflow graph [ before save ] ---
default tf graph : <tensorflow.python.framework.ops.Graph object at 0x000001D9A0474518>
current name scope : 
all graph ( trainable_variables )  : [<tf.Variable 'A/cudnn_gru/opaque_kernel:0' shape=<unknown> dtype=float32_ref>, <tf.Variable 'B/cudnn_gru/opaque_kernel:0' shape=<unknown> dtype=float32_ref>]
all graph ( variables )  : [<tf.Variable 'A/cudnn_gru/opaque_kernel:0' shape=<unknown> dtype=float32_ref>, <tf.Variable 'B/cudnn_gru/opaque_kernel:0' shape=<unknown> dtype=float32_ref>]
all graph ( saveable_objects )  : [<tensorflow.contrib.cudnn_rnn.python.ops.cudnn_rnn_ops.CudnnGRUSaveable object at 0x000001D9E5472390>, <tensorflow.contrib.cudnn_rnn.python.ops.cudnn_rnn_ops.CudnnGRUSaveable object at 0x000001D99E51F550>]
all graph ( update_ops )  : []


---------------------------------------------------------------------------
UnknownError                              Traceback (most recent call last)
~\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py in _do_call(self, fn, *args)
   1277     try:
-> 1278       return fn(*args)
   1279     except errors.OpError as e:

~\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py in _run_fn(feed_dict, fetch_list, target_list, options, run_metadata)
   1262       return self._call_tf_sessionrun(
-> 1263           options, feed_dict, fetch_list, target_list, run_metadata)
   1264 

~\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py in _call_tf_sessionrun(self, options, feed_dict, fetch_list, target_list, run_metadata)
   1349         self._session, options, feed_dict, fetch_list, target_list,
-> 1350         run_metadata)
   1351 

UnknownError: Fail to find the dnn implementation.
	 [[Node: A/cudnn_gru_1/CudnnRNNCanonicalToParams = CudnnRNNCanonicalToParams[T=DT_FLOAT, direction="bidirectional", dropout=0, input_mode="linear_input", num_params=12, rnn_mode="gru", seed=0, seed2=0, _device="/job:localhost/replica:0/task:0/device:GPU:0"](A/cudnn_gru_1/CudnnRNNCanonicalToParams/num_layers, A/cudnn_gru_1/CudnnRNNCanonicalToParams/num_units, A/cudnn_gru_1/CudnnRNNCanonicalToParams/num_units, A/cudnn_gru_1/random_uniform, A/cudnn_gru_1/random_uniform_1, A/cudnn_gru_1/random_uniform_2, A/cudnn_gru_1/random_uniform_3, A/cudnn_gru_1/random_uniform_4, A/cudnn_gru_1/random_uniform_5, A/cudnn_gru_1/random_uniform_6, A/cudnn_gru_1/random_uniform_7, A/cudnn_gru_1/random_uniform_8, A/cudnn_gru_1/random_uniform_9, A/cudnn_gru_1/random_uniform_10, A/cudnn_gru_1/random_uniform_11, A/cudnn_gru_1/Const, A/cudnn_gru_1/Const, A/cudnn_gru_1/Const, A/cudnn_gru_1/Const, A/cudnn_gru_1/Const, A/cudnn_gru_1/Const, A/cudnn_gru_1/Const, A/cudnn_gru_1/Const, A/cudnn_gru_1/Const, A/cudnn_gru_1/Const, A/cudnn_gru_1/Const, A/cudnn_gru_1/Const)]]

During handling of the above exception, another exception occurred:
...

**Comment by riklmr** [comment]
I was also using Keras/Tensorflow inside Jupyter notebooks. The first notebook worked OK. The second gave the UnknownError: Fail to find the dnn implementation.
After closing the first notebook (Save + Close/Halt), the second notebook started to work again.
Note: both notebooks used the same CuDNNLSTM layer.

**Comment by hwong39** [comment]
"CudnnCompatibleGRUCell. A GRU impl akin to tf.nn.rnn_cell.GRUCell to use along with tf.contrib.cudnn _rnn.CudnnGRU. The latter's params can be used by it seamlessly."
--How can CudnnCompatibleGRUCell get weights and biases from CudnnGRU's params ???

**Comment by atenciop** [comment]
I encountered a similar issue as riklmr. I had to restart Jupyter Notebook to get the 2nd notebook's model to overcome this error. I rather do that at this point than upgrading versions of Keras/Tensorflow as recommended in other pages. Moving on with my life, for now...

**Comment by agarnitin86** [comment]
@riklmr : I have a similar issue. I have two processes using CuDNNLSTM. One process trains model on some data and another process predicts using a previously saved model. When i run both the process i get this error. When i change cudnnLSTM to LSTM cell it works fine. But i need to use CuDNNLSTM. Does anyone have any resolution.

**Comment by dmitryponv** [comment]
The solution here seemed to work
https://stackoverflow.com/questions/54473254/cudnnlstm-unknownerror-fail-to-find-the-dnn-implementation

adding this worked for me
 ```
import tensorflow as tf
physical_devices = tf.config.list_physical_devices('GPU')
tf.config.experimental.set_memory_growth(physical_devices[0], enable=True)
```

Some other recommendations were to do a full install of CUDA including the display driver its shipped with, it may be your current driver is outdated

**Comment by quantitative-technologies** [comment]
@dmitrievanthony That worked for me for a while, but the same error came back even with growth enabled.
