### ISSUE TITLE
WishartCholesky with 1-D batch shape fails to calculate mean

### ISSUE THREAD

**Issue by DrKwint** [tensorflow/tensorflow#20125]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac OS X 10.13.4
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: v1.8.0-0-g93bc2e2072 1.8.0
- **Python version**: Python 3.6.5
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**: See source below

### Describe the problem
Initializing a `tf.contrib.distributions.WishartCholesky` distribution with parameters identical to those provided in the one of the examples, the `mean()` function fails an attempted multiplication.

### Source code / logs
```
# Initialize two 3x3 Wisharts with Cholesky factored scale matrices.
df = [5, 4]
chol_scale = tf.cholesky(tf.ones([2.,3.,3.]))  # Shape is [2, 3, 3].
dist = tf.contrib.distributions.WishartCholesky(df=df, scale=chol_scale)
dist.mean()
```

```
Traceback (most recent call last):
  File "/Users/equint/interpretable-classification/env/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1567, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimensions must be equal, but are 2 and 3 for 'WishartCholesky/WishartCholesky/mean/mul' (op: 'Mul') with input shapes: [2], [2,3,3].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/equint/interpretable-classification/env/lib/python3.6/site-packages/tensorflow/python/ops/distributions/distribution.py", line 923, in mean
    return self._mean()
  File "/Users/equint/interpretable-classification/env/lib/python3.6/site-packages/tensorflow/contrib/distributions/python/ops/wishart.py", line 375, in _mean
    return self.df * self._square_scale_operator()
  File "/Users/equint/interpretable-classification/env/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 979, in binary_op_wrapper
    return func(x, y, name=name)
  File "/Users/equint/interpretable-classification/env/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 1211, in _mul_dispatch
    return gen_math_ops.mul(x, y, name=name)
  File "/Users/equint/interpretable-classification/env/lib/python3.6/site-packages/tensorflow/python/ops/gen_math_ops.py", line 4759, in mul
    "Mul", x=x, y=y, name=name)
  File "/Users/equint/interpretable-classification/env/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/Users/equint/interpretable-classification/env/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/Users/equint/interpretable-classification/env/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1734, in __init__
    control_input_ops)
  File "/Users/equint/interpretable-classification/env/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1570, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimensions must be equal, but are 2 and 3 for 'WishartCholesky/WishartCholesky/mean/mul' (op: 'Mul') with input shapes: [2], [2,3,3].
```

**Comment by tensorflowbutler** [comment]
Nagging Assignee @rohan100jain: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @rohan100jain: It has been 30 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @rohan100jain: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by srvasude** [comment]
Fixed in TFP: https://github.com/tensorflow/probability/commit/c10cc8e1120f9e017d0117c934316d09679a52e7.
