### ISSUE TITLE
Tensorflow on GCP instance

### ISSUE THREAD

**Issue by sakethramanujam** [tensorflow/tensorflow#20149]
I'm trying to setup my GCP instance for working with TF and Keras. I installed Cuda-toolkit, libcupti-dev and cudnn.
I also installed the *tensorflow-gpu* but when I import Tensorflow, I get the following.

Operating System : Ubuntu 16.04 LTS
Tensorflow Installation Method : ```pip install tensorflow-gpu```
Tensorflow Version: 1.8
Pip Version: 10.0
Cuda version 9.2
Cudnn  version: 7
GPU: Nvidia Tesla K80 - 12 GB

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory
Failed to load the native TensorFlow runtime.
See https://www.tensorflow.org/install/install_sources#common_installation_problems
```

 cudnn and CUDA are setup as precribed in the documentation. Could you help me with this?

```
import tensorflow as tf
```
gives me the above error on server

**Comment by gunan** [comment]
```
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory
```
This means TF is looking for cuda 9.0 and failing to find.
prebuilt TF packages are built on top of cuda 9.0. To use cuda 9.2, you need to rebuild TF from sources.

**Comment by sakethramanujam** [comment]
Thanks!

On Fri, Jun 29, 2018 at 11:30 AM Gunhan Gulsoy <notifications@github.com<mailto:notifications@github.com>> wrote:

ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory


This means TF is looking for cuda 9.0 and failing to find.
prebuilt TF packages are built on top of cuda 9.0. To use cuda 9.2, you need to rebuild TF from sources.
