### ISSUE TITLE
Feature Request: Initialize tables when passing a Dataset as input to a Keras model

### ISSUE THREAD

**Issue by dillondaudert** [tensorflow/tensorflow#20158]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
Yes.
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 18
- **TensorFlow installed from (source or binary)**:
Binary
- **TensorFlow version (use command below)**:
v1.8.0-3410-g79d7e11f3e, 1.10.0-dev20180616
- **Python version**: 
3.6
- **Bazel version (if compiling from source)**:
N/A
- **GCC/Compiler version (if compiling from source)**:
N/A
- **CUDA/cuDNN version**:
CUDA 9.0, cuDNN 7.0
- **GPU model and memory**:
NVIDIA GeForce 1080
- **Exact command to reproduce**:
Running the provided script should produce this error.

### Describe the problem
tf.keras.Model will throw a `FailedPreconditionError: Table not initialized.` error when passing a Dataset that includes a lookup table to Model.fit(). This can be worked around by creating a Session and running `tf.tables_initializer()` and `keras.backend.set_session`, but it would be nice if Keras could check for tables and initialize them automatically.

### Source code / logs
- **Script**:
```python
import tensorflow as tf
import numpy as np
from tensorflow.python.ops import lookup_ops
from tensorflow import keras

alphabet = ['A', 'B', 'C']
table = lookup_ops.index_table_from_tensor(tf.constant(alphabet))
# generate samples of strings of different lengths
inputs = [''.join([np.random.choice(alphabet) for _ in range(5)]) for _ in range(10)]
targets = np.zeros((10, 4))

dataset = tf.data.Dataset.from_tensor_slices((inputs, targets))
def map_fn(x, y):
    x = tf.string_split([x], delimiter="").values
    x = table.lookup(x)
    x = tf.nn.embedding_lookup(tf.eye(3), x)
    return x, y
dataset = dataset.map(lambda x, y: map_fn(x, y))
dataset = dataset.repeat(100)
dataset = dataset.batch(5)

x = keras.layers.Input(shape=(5, 3), name='input')
flat = keras.layers.Flatten()(x)
y = keras.layers.Dense(4, name='dense')(flat)

model = keras.Model(x, y)
model.compile(loss='mse', optimizer='rmsprop')

model.fit(dataset, epochs=1, steps_per_epoch=2, verbose=1)
```

- **Output**:
```bash
Script started on 2018-06-20 16:09:12-0400
dillon@dillon-linux:~/github/dillondaudert$ python keras_table_init_ex.py 
2018-06-20 16:09:20.610136: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-06-20 16:09:20.717933: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:883] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-06-20 16:09:20.718316: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1392] Found device 0 with properties: 
name: GeForce GTX 1080 major: 6 minor: 1 memoryClockRate(GHz): 1.8475
pciBusID: 0000:01:00.0
totalMemory: 7.93GiB freeMemory: 7.17GiB
2018-06-20 16:09:20.788286: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:883] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-06-20 16:09:20.788649: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1392] Found device 1 with properties: 
name: GeForce GTX 1080 major: 6 minor: 1 memoryClockRate(GHz): 1.8475
pciBusID: 0000:02:00.0
totalMemory: 7.93GiB freeMemory: 7.81GiB
2018-06-20 16:09:20.789264: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1471] Adding visible gpu devices: 0, 1
2018-06-20 16:09:21.112863: I tensorflow/core/common_runtime/gpu/gpu_device.cc:952] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-06-20 16:09:21.112890: I tensorflow/core/common_runtime/gpu/gpu_device.cc:958]      0 1 
2018-06-20 16:09:21.112895: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   N Y 
2018-06-20 16:09:21.112899: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 1:   Y N 
2018-06-20 16:09:21.113086: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6917 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080, pci bus id: 0000:01:00.0, compute capability: 6.1)
2018-06-20 16:09:21.169182: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 7537 MB memory) -> physical GPU (device: 1, name: GeForce GTX 1080, pci bus id: 0000:02:00.0, compute capability: 6.1)
Epoch 1/1
2018-06-20 16:09:21.490711: W tensorflow/core/framework/op_kernel.cc:1328] OP_REQUIRES failed at lookup_table_op.cc:675 : Failed precondition: Table not initialized.
Traceback (most recent call last):
  File "keras_table_init_ex.py", line 29, in <module>
    model.fit(dataset, epochs=1, steps_per_epoch=2, verbose=1)
  File "/home/dillon/.conda/envs/tf1.10-nightly/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1353, in fit
    validation_steps=validation_steps)
  File "/home/dillon/.conda/envs/tf1.10-nightly/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_arrays.py", line 195, in fit_loop
    outs = f(ins)
  File "/home/dillon/.conda/envs/tf1.10-nightly/lib/python3.6/site-packages/tensorflow/python/keras/backend.py", line 2897, in __call__
    fetched = self._callable_fn(*array_vals)
  File "/home/dillon/.conda/envs/tf1.10-nightly/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1382, in __call__
    run_metadata_ptr)
  File "/home/dillon/.conda/envs/tf1.10-nightly/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 519, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.FailedPreconditionError: Table not initialized.
	 [[Node: hash_table_Lookup = LookupTableFindV2[Tin=DT_STRING, Tout=DT_INT64](hash_table_lookup_placeholder, StringSplit:1, hash_table_lookup_placeholder_1)]]
	 [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[?,?,3], [?,4]], output_types=[DT_FLOAT, DT_DOUBLE], _device="/job:localhost/replica:0/task:0/device:CPU:0"](Iterator)]]
	 [[Node: IteratorGetNext/_17 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_18_IteratorGetNext", tensor_type=DT_DOUBLE, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
dillon@dillon-linux:~/github/dillondaudert$ exit
exit

Script done on 2018-06-20 16:09:29-0400
```

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
It has been 15 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
It has been 33 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by marco-willi** [comment]
As suggested by the poster, the following Callback is a (temporary) fix for the problem:

```
class TableInitializerCallback(Callback):
    """ Initialize Tables """
    def on_train_begin(self, logs=None):
        K.get_session().run(tf.tables_initializer())
```

**Comment by tensorflowbutler** [comment]
It has been 18 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
It has been 34 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
We are closing this issue for now due to lack of activity. Please comment if this is still an issue for you. Thanks!

**Comment by dhruvdcoder** [comment]
@marco-willi 
This will work for training. How do I make it work with the `predict` method which does not take any callbacks?

**Comment by spate141** [comment]
Any update with the predict methid? @dhruvdcoder

**Comment by innerNULL** [comment]
> @marco-willi
> This will work for training. How do I make it work with the `predict` method which does not take any callbacks?

so is there any solution (for tf 1.14) ?
