### ISSUE TITLE
F-RCN protobuf issue decoding string when reading in label_map

### ISSUE THREAD

**Issue by zacharymostowsky** [tensorflow/tensorflow#20205]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Stock
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04 LTS
- **TensorFlow installed from (source or binary)**: Source
- **TensorFlow version (use command below)**: 1.6.0 (GPU)
- **Python version**: 2.7
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**: 9.0 (This is what I deduced from the help script provided)
- **GPU model and memory**:Tesla P100-PCIE-16GB
- **Exact command to reproduce**:python /home/_myhomedir_/tensorflow/models/research/object_detection/train.py --pipeline_config_path=/home/_myhomedir_/test_rfcn/rfcn_resnet101-1.config --train_dir=gs://mygcsbucket/mydir --ps_tasks=1
Config File: [rfcn_resnet101-1.txt](https://github.com/tensorflow/tensorflow/files/2125622/rfcn_resnet101-1.txt)

### Describe the problem
The bug occurs when trying to read in the label map (stack trace below). I am using the exact same setup when I test with ssd_mobilenet config file (points to ssd_mobilenet initial checkpoint) and training runs fine. Same for F-RCNN. Only when using the R-FCN config file is when this error is thrown. It seems to be related to protobuf and I have tried some various fixes found in the issues section. None seem to work, and I am unsure how/why that is a problem if it works for ssd and frcnn. I also have attache dmy config file (as .txt due to file type restrictions). Thanks for the help.

Zach

### Source code / logs
```
WARNING:tensorflow:From /home/zachary_mostowsky/tensorflow/models/research/object_detection/trainer.py:257: create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.create_global_step
Traceback (most recent call last):
  File "/home/zachary_mostowsky/tensorflow/models/research/object_detection/train.py", line 184, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "/home/zachary_mostowsky/tensorflow/models/research/object_detection/train.py", line 180, in main
    graph_hook_fn=graph_rewriter_fn)
  File "/home/zachary_mostowsky/tensorflow/models/research/object_detection/trainer.py", line 264, in train
    train_config.prefetch_queue_capacity, data_augmentation_options)
  File "/home/zachary_mostowsky/tensorflow/models/research/object_detection/trainer.py", line 59, in create_input_queue
    tensor_dict = create_tensor_dict_fn()
  File "/home/zachary_mostowsky/tensorflow/models/research/object_detection/train.py", line 121, in get_next
    dataset_builder.build(config)).get_next()
  File "/home/zachary_mostowsky/tensorflow/models/research/object_detection/builders/dataset_builder.py", line 155, in build
    label_map_proto_file=label_map_proto_file)
  File "/home/zachary_mostowsky/tensorflow/models/research/object_detection/data_decoders/tf_example_decoder.py", line 245, in __init__
    use_display_name)
  File "/home/zachary_mostowsky/tensorflow/models/research/object_detection/utils/label_map_util.py", line 152, in get_label_map_dict
    label_map = load_labelmap(label_map_path)
  File "/home/zachary_mostowsky/tensorflow/models/research/object_detection/utils/label_map_util.py", line 137, in load_labelmap
    label_map.ParseFromString(label_map_string)
google.protobuf.message.DecodeError: Error parsing message

```

**Comment by drpngx** [comment]
this looks like an object detection issue.

@derekjchow WDYT?

**Comment by derekjchow** [comment]
I think you have your label map and TF record paths mixed up:

```
train_input_reader {
  label_map_path: "/home/zachary_mostowsky/rev20180614/xview_train_mapped_id-1.record"
  tf_record_input_reader {
    input_path: "/home/zachary_mostowsky/rev20180614/label_map.pbtxt"
  }
}
```

`label_map_path` should be "**/*.pbtxt", while `input_path` should be "**/*.record". They are mixed up in your config.

**Comment by zacharymostowsky** [comment]
Thank you. I start thinking it is these complicated errors when they are in reality very simple. Sorry to waste your time.
