### ISSUE TITLE
tensorflow/core/framework/op_kernel.cc:1318] Not found 

### ISSUE THREAD

**Issue by morrislompi** [tensorflow/tensorflow#20252]
What is the reason this error is happening ?

WARNING:tensorflow:From /home/Admin/anaconda3/envs/fastai/lib/python3.6/site-packages/tensorflow/python/util/tf_should_use.py:118: initialize_all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
Instructions for updating:
Use `tf.global_variables_initializer` instead.
2018-06-23 21:43:50.471573: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1435] Adding visible gpu devices: 0
2018-06-23 21:43:50.471640: I tensorflow/core/common_runtime/gpu/gpu_device.cc:923] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-06-23 21:43:50.471665: I tensorflow/core/common_runtime/gpu/gpu_device.cc:929]      0
2018-06-23 21:43:50.471684: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 0:   N
2018-06-23 21:43:50.471857: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10654 MB memory) -> physical GPU (device: 0, name: Tesla K80, pci bus id: 0000:00:04.0, compute capability: 3.7)
2018-06-23 21:43:55.304510: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1435] Adding visible gpu devices: 0
2018-06-23 21:43:55.304589: I tensorflow/core/common_runtime/gpu/gpu_device.cc:923] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-06-23 21:43:55.304618: I tensorflow/core/common_runtime/gpu/gpu_device.cc:929]      0
2018-06-23 21:43:55.304636: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 0:   N
2018-06-23 21:43:55.304812: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10654 MB memory) -> physical GPU (device: 0, name: Tesla K80, pci bus id: 0000:00:04.0, compute capability: 3.7)
Epoch 1/25
2018-06-23 21:44:00.405493: W tensorflow/core/framework/op_kernel.cc:1318] OP_REQUIRES failed at resource_variable_ops.cc:389 : Not found: Resource localhost/RMSprop/iterations/N10tensorflow3VarE does not exist.
Traceback (most recent call last):
  File "/home/Admin/anaconda3/envs/fastai/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1322, in _do_call
    return fn(*args)
  File "/home/Admin/anaconda3/envs/fastai/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/Admin/anaconda3/envs/fastai/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.FailedPreconditionError: Error while reading resource variable RMSprop/lr from Container: localhost. This could mean that the variable was uninitialized. Not found: Resource localhost/RMSprop/lr/N10tensorflow3VarE does not exist.
         [[Node: training/RMSprop/ReadVariableOp_4 = ReadVariableOp[dtype=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](RMSprop/lr)]]
         [[Node: training/RMSprop/gradients/add_9/add_grad/Shape_1/_1445 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_2193_training/RMSprop/gradients/add_9/add_grad/Shape_1", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 161, in <module>
    callbacks=[TensorBoard(log_dir='./log')])
  File "/home/Admin/anaconda3/envs/fastai/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/engine/training.py", line 1598, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/Admin/anaconda3/envs/fastai/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/engine/training_generator.py", line 191, in fit_generator
    x, y, sample_weight=sample_weight, class_weight=class_weight)
  File "/home/Admin/anaconda3/envs/fastai/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/engine/training.py", line 1390, in train_on_batch
    outputs = self.train_function(ins)
  File "/home/Admin/anaconda3/envs/fastai/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/backend.py", line 2824, in __call__
    fetches=fetches, feed_dict=feed_dict, **self.session_kwargs)
  File "/home/Admin/anaconda3/envs/fastai/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/home/Admin/anaconda3/envs/fastai/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/Admin/anaconda3/envs/fastai/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/home/Admin/anaconda3/envs/fastai/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.FailedPreconditionError: Error while reading resource variable RMSprop/lr from Container: localhost. This could mean that the variable was uninitialized. Not found: Resource localhost/RMSprop/lr/N10tensorflow3VarE does not exist.
         [[Node: training/RMSprop/ReadVariableOp_4 = ReadVariableOp[dtype=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](RMSprop/lr)]]
         [[Node: training/RMSprop/gradients/add_9/add_grad/Shape_1/_1445 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_2193_training/RMSprop/gradients/add_9/add_grad/Shape_1", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by morrislompi** [comment]
Already fixed thanks. I previous using these import statement in pre-trained xception model and visual the information in the tensorboard using callback occur these error after I change to second statement work for me.

I changing the import statement from 
import tensorflow as tf
import numpy as np
import os
import matplotlib.pyplot as plt
from keras.preprocessing.image import ImageDataGenerator
from keras.callbacks import TensorBoard
from keras.optimizers import SGD


to

import tensorflow as tf
import numpy as np
import os
import matplotlib.pyplot as plt
from tensorflow.python.keras.preprocessing.image import ImageDataGenerator
from tensorflow.python.keras.callbacks import TensorBoard

**Comment by VincentOkala** [comment]
I just change the TensorBoard import statement from:

> from keras.callbacks import TensorBoard

to:

> from tensorflow.python.keras.callbacks import TensorBoard

And everything goes without any error

**Comment by suziW** [comment]
ubuntu 16.04
tensorflow 1.15
keras 2.3.1
and i get exactly the same problem when trying this example [https://keras.io/examples/tensorboard_embeddings_mnist/]
