### ISSUE TITLE
TensorRT - KeyError: 'shape'

### ISSUE THREAD

**Issue by Aashit-Sharma** [tensorflow/tensorflow#20267]
------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:yes
- **OS Platform and Distribution: Linux Ubuntu 16.04**
- **TensorFlow installed from (source or binary)**:
- **TensorFlow version (use command below)**:
> tensorflow (1.8.0)
> tensorrt (4.0.1.6)

- **Python version**: 2.7.14 
- **Bazel version (if compiling from source)**:None
- **CUDA/cuDNN version**: 9.0
- **Exact command to reproduce**:

### Describe the problem
Getting the following error while trying to optimize the predict node in from a frozen graph of an estimator-based transformer model. This is the line where I get the issue : 
`uff_model = uff.from_tensorflow_frozen_model(frozen_file, ["train/enc_0"])`

### Source code / logs
```
Warning: No conversion function registered for layer: IteratorGetNext yet.
Converting as custom op IteratorGetNext train/IteratorGetNext
name: "train/IteratorGetNext"
op: "IteratorGetNext"
input: "train/Iterator"
attr {
  key: "output_shapes"
  value {
    list {
      shape {
        dim {
          size: -1
        }
        dim {
          size: -1
        }
      }
      shape {
        dim {
          size: -1
        }
        dim {
          size: -1
        }
      }
    }
  }
}
attr {
  key: "output_types"
  value {
    list {
      type: DT_INT32
      type: DT_INT32
    }
  }
}

Traceback (most recent call last):
  File "tensorRT_optimize.py", line 25, in <module>
    uff_model = uff.from_tensorflow("logs/check_tiny/frozen_model_new.pb", ['train/pred_0'])
  File "/home/user/.local/lib/python2.7/site-packages/uff/converters/tensorflow/conversion_helpers.py", line 120, in from_tensorflow
    name="main")
  File "/home/user/.local/lib/python2.7/site-packages/uff/converters/tensorflow/converter.py", line 76, in convert_tf2uff_graph
    uff_graph, input_replacements)
  File "/home/user/.local/lib/python2.7/site-packages/uff/converters/tensorflow/converter.py", line 63, in convert_tf2uff_node
    op, name, tf_node, inputs, uff_graph, tf_nodes=tf_nodes)
  File "/home/user/.local/lib/python2.7/site-packages/uff/converters/tensorflow/converter.py", line 38, in convert_layer
    fields = cls.parse_tf_attrs(tf_node.attr)
  File "/home/user/.local/lib/python2.7/site-packages/uff/converters/tensorflow/converter.py", line 209, in parse_tf_attrs
    for key, val in attrs.items()}
  File "/home/user/.local/lib/python2.7/site-packages/uff/converters/tensorflow/converter.py", line 209, in <dictcomp>
    for key, val in attrs.items()}
  File "/home/user/.local/lib/python2.7/site-packages/uff/converters/tensorflow/converter.py", line 204, in parse_tf_attr_value
    return cls.convert_tf2uff_field(code, val)
  File "/home/user/.local/lib/python2.7/site-packages/uff/converters/tensorflow/converter.py", line 189, in convert_tf2uff_field
    'type': 'dtype', 'list': 'list'}[code]
KeyError: 'shape'
```

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
GPU model and memory

**Comment by samikama** [comment]
@Aashit-Sharma ,

This is an UFF issue. Please report this to Nvidia forums for TensorRT.

**Comment by vilmara** [comment]
hi @Aashit-Sharma , did you solve the issue?, I got a similar error:

Warning: No conversion function registered for layer: IteratorGetNext yet.
Converting as custom op IteratorGetNext IteratorGetNext
name: "IteratorGetNext"
op: "IteratorGetNext"
input: "OneShotIterator"
attr {
  key: "_output_shapes"
  value {
    list {
      shape {
        dim {
          size: 8
        }
        dim {
          size: 224
        }
        dim {
          size: 224
        }
        dim {
          size: 3
        }
      }
      shape {
        dim {
          size: 8
        }
        dim {
          size: -1
        }
      }
    }
  }
}
attr {
  key: "output_shapes"
  value {
    list {
      shape {
        dim {
          size: 8
        }
        dim {
          size: 224
        }
        dim {
          size: 224
        }
        dim {
          size: 3
        }
      }
      shape {
        dim {
          size: 8
        }
        dim {
          size: -1
        }
      }
    }
  }
}
attr {
  key: "output_types"
  value {
    list {
      type: DT_FLOAT
      type: DT_INT64
    }
  }
}

Traceback (most recent call last):
  File "tf_to_trt_chest_bhavesh_model.py", line 188, in <module>
    main()
  File "tf_to_trt_chest_bhavesh_model.py", line 158, in main
    uff_model = uff.from_tensorflow(tf_model, ["probs"])
  File "/usr/lib/python3.5/dist-packages/uff/converters/tensorflow/conversion_helpers.py", line 120, in from_tenso                             rflow
    name="main")
  File "/usr/lib/python3.5/dist-packages/uff/converters/tensorflow/converter.py", line 76, in convert_tf2uff_graph
    uff_graph, input_replacements)
  File "/usr/lib/python3.5/dist-packages/uff/converters/tensorflow/converter.py", line 63, in convert_tf2uff_node
    op, name, tf_node, inputs, uff_graph, tf_nodes=tf_nodes)
  File "/usr/lib/python3.5/dist-packages/uff/converters/tensorflow/converter.py", line 38, in convert_layer
    fields = cls.parse_tf_attrs(tf_node.attr)
  File "/usr/lib/python3.5/dist-packages/uff/converters/tensorflow/converter.py", line 209, in parse_tf_attrs
    for key, val in attrs.items()}
  File "/usr/lib/python3.5/dist-packages/uff/converters/tensorflow/converter.py", line 209, in <dictcomp>
    for key, val in attrs.items()}
  File "/usr/lib/python3.5/dist-packages/uff/converters/tensorflow/converter.py", line 204, in parse_tf_attr_value
    return cls.convert_tf2uff_field(code, val)
  File "/usr/lib/python3.5/dist-packages/uff/converters/tensorflow/converter.py", line 189, in convert_tf2uff_fiel                             d
    'type': 'dtype', 'list': 'list'}[code]
KeyError: 'shape'

**Comment by samikama** [comment]
@vilmara, your problem is related with uff which is pure tensorrt and not related with tensorflow. Please raise the issue in NVIDIA forums.
