### ISSUE TITLE
Computing gradients in extracted subgraph which contains a 'while_loop'

### ISSUE THREAD

**Issue by Tal-Golan** [tensorflow/tensorflow#20263]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 17.10
- **TensorFlow installed from (source or binary)**:
Binary
- **TensorFlow version (use command below)**:
v1.8.0-0-g93bc2e2072 
- **Python version**: 
3.6.5
- **Bazel version (if compiling from source)**:
N/A
- **GCC/Compiler version (if compiling from source)**:
N/A
- **CUDA/cuDNN version**:
9.0/7.0.5
- **GPU model and memory**:
Titan XP
- **Exact command to reproduce**:
```
import tensorflow as tf
g1=tf.Graph()
sess1=tf.Session(graph=g1)
with g1.as_default():
    with sess1.as_default():
        i=tf.constant(0, name="input")
        out=tf.while_loop(lambda i: tf.less(i,5), lambda i: [tf.add(i,1)], [i], name="output")
        loss=tf.square(out,name='loss')
        graph_def = tf.graph_util.convert_variables_to_constants(sess1,g1.as_graph_def(),['output/Exit'])

g2 = tf.Graph()
with g2.as_default():
    tf.import_graph_def(graph_def,name='')
    i_imported = g2.get_tensor_by_name("input:0")
    out_imported = g2.get_tensor_by_name("output/Exit:0")
    tf.gradients(out_imported, i_imported)

```
output:
```
INFO:tensorflow:Froze 0 variables.
Converted 0 variables to const ops.
Traceback (most recent call last):

  File "<ipython-input-1-908dc1dee750>", line 23, in <module>
    tf.gradients(out_imported, i_imported)

  File "/home/user/anaconda3/envs/tf1.8_gpu/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 494, in gradients
    gate_gradients, aggregation_method, stop_gradients)

  File "/home/user/anaconda3/envs/tf1.8_gpu/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 543, in _GradientsHelper
    ops.get_default_graph(), to_ops, from_ops, colocate_gradients_with_ops)

  File "/home/user/anaconda3/envs/tf1.8_gpu/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 195, in _PendingCount
    between_op_list, between_ops, colocate_gradients_with_ops)

  File "/home/user/anaconda3/envs/tf1.8_gpu/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 1456, in MaybeCreateControlFlowState
    loop_state.AddWhileContext(op, between_op_list, between_ops)

  File "/home/user/anaconda3/envs/tf1.8_gpu/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 1262, in AddWhileContext
    outer_forward_ctxt = forward_ctxt.outer_context

AttributeError: 'NoneType' object has no attribute 'outer_context'
```
### Describe the problem
TF  [issue #7404](https://github.com/tensorflow/tensorflow/issues/7404) describes that when trying to form a gradient op in an imported (sub)graph, a 'No attribute 'outer_context'' error occurs. This issue was closed with the recommendation to use `tf.train.import_meta_graph` instead, so the outer context related to the while op is included.

However, this does not fully solve the problem. In some deep-learning related settings, one might want to train a model, extract a subgraph (i.e., remove training related ops), connect the extracted subgraph into a larger graph to serve as part of an ensemble, GAN and so on, and then retrain the larger graph. When there is no dependence on outer context, one can easily use graph editing tools such as `tf.graph_util.convert_variables_to_constants` or `tf.graph_util.extract_sub_graph` to achieve that, exporting and importing subgraphs and then forming new tf.gradients operations. 

The minimal example above, adapted from issue 7404, shows how this approach fails when a tf.while is used and the outer context is missing. Importing and exporting the metagraph instead would leave the tf.square op in the graph. While for this minimal example being forced to save also the loss tensor looks like a very minor limitation it is easy to conceive actual applications in which there are large parts of the graph which we might really want to exclude (e.g., a decoder network in Capsule-network training). 

Right now, the dependence on outer context for computing gradients for tf.while is incompatible with tf.graph_util.extract_sub_graph and similar operations that operate on graphdefs. I believe that this is not a negligible functionality limitation.  A [related StackOverflow question](https://stackoverflow.com/questions/50663594/computing-gradients-in-extracted-tensorflow-subgraph-which-contains-a-while-loo) was upvoted but left unanswered.

In general, from the perspective of an API user who is ignorant of the internal implementation of TF, any dependence of operations on information stored out of the graphdef is not expected, hinders graph editing (as I try to convey above) and seems patchy.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatatodd: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatatodd: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatatodd: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatatodd: It has been 59 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatatodd: It has been 74 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatatodd: It has been 89 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatatodd: It has been 104 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatatodd: It has been 119 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatatodd: It has been 134 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatatodd: It has been 149 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatatodd: It has been 164 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by rmothukuru** [comment]
@Tal-Golan,
Your code could be executed successfully, with **`Tensorflow Version 1.15.2`**. Please find [the Gist](https://colab.research.google.com/gist/rmothukuru/49763dd0e78f5d06a448750d824cd1c3/gh_20263.ipynb) of the working code. Thanks!
