### ISSUE TITLE
tensor flow does not install on windows 10

### ISSUE THREAD

**Issue by jonmelvin** [tensorflow/tensorflow#20266]
Windows 10, TensorFlow 1.8.1, NVIDIA 1060
Was working.  Had to resinstall OS.  Now I always get error below with
CUDA 8.0, CUDA 9.0, CUDA 9.2, Visual Studio 2015, Visual Studio 2017 (have tried everything I can think of).  Any pointers for how to diagnose/solve?

(tensorflow) v:\deeplearning>python -W ignore test.py
Traceback (most recent call last):
  File "C:\Users\jdm\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\jdm\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 18, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\jdm\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 17, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Users\jdm\Anaconda3\envs\tensorflow\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import tensorflow as tf
  File "C:\Users\jdm\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\jdm\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\jdm\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\jdm\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\jdm\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 18, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\jdm\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 17, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Users\jdm\Anaconda3\envs\tensorflow\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by friketrike** [comment]
A bit of a shot in the dark since I don't see the same code from your stack-trace in the current state of the repo but since you ask for pointers, here goes:
You could use gflags to monitor dll loading when you run python -W ignore test.py. 
- Get gflags from Microsoft: https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/gflags-commands
- Run and open the Image tab
- Enter Python.exe as an image
- Select 'show loader snaps'
Brace yourself for somewhat verbose output (remember to unset this after you've solved your issue) but you should see which dlls are being loaded and from where. You'll probably see one trying to load from each directory in your path and failing right before the stack-trace.
Additionally, once you've found a couple of suspect dlls, you can use dependency walker show information regarding the dlls that they will try to load. Dependency walke has a 32b and 64b version, they don't see all dlls equally, so you might need to use both.
Hope this helps and good luck

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatianashp: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by jonmelvin** [comment]
Thank you.

**Comment by tatianashp** [comment]
If you are running on an older processor that has no support for AVX instructions it might be the same issue as discussed #19584.

**Comment by jonmelvin** [comment]
Thanks.
Well, I went into Anaconda3 navigator and deleted the entire environment, created the environment again, and installed tensorflow-gpu, keras-gpu, etc etc only in Anaconda navigator (no "pip install …") and now it all works.  Finally.  Sorry to raise this issue!
