### ISSUE TITLE
transfer learning: /scripts/label_image.py", line 137, in <module>     print(template.format(labels[i], results[i])) IndexError: list index out of range

### ISSUE THREAD

**Issue by monajalal** [tensorflow/tensorflow#20293]
In Tensorflow 1.8, Ubuntu 16.04, Anaconda Python 3.6.5, I have:

```
mona@Mona:~/code/alternative-controllers/style_transfer$ python -m scripts.label_image     --graph=dataset/retrained_graph.pb      --image=dataset/charmander/charmander30.jpg 
/home/mona/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2018-06-25 18:51:53.814201: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-06-25 18:51:53.934034: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 0 with properties: 
name: TITAN Xp major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:01:00.0
totalMemory: 11.90GiB freeMemory: 10.57GiB
2018-06-25 18:51:53.934061: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1435] Adding visible gpu devices: 0
2018-06-25 18:51:54.128693: I tensorflow/core/common_runtime/gpu/gpu_device.cc:923] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-06-25 18:51:54.128723: I tensorflow/core/common_runtime/gpu/gpu_device.cc:929]      0 
2018-06-25 18:51:54.128728: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 0:   N 
2018-06-25 18:51:54.128937: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10233 MB memory) -> physical GPU (device: 0, name: TITAN Xp, pci bus id: 0000:01:00.0, compute capability: 6.1)
2018-06-25 18:51:54.240643: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1435] Adding visible gpu devices: 0
2018-06-25 18:51:54.240673: I tensorflow/core/common_runtime/gpu/gpu_device.cc:923] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-06-25 18:51:54.240678: I tensorflow/core/common_runtime/gpu/gpu_device.cc:929]      0 
2018-06-25 18:51:54.240682: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 0:   N 
2018-06-25 18:51:54.240766: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10233 MB memory) -> physical GPU (device: 0, name: TITAN Xp, pci bus id: 0000:01:00.0, compute capability: 6.1)

Evaluation time (1-image): 0.752s

Traceback (most recent call last):
  File "/home/mona/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/mona/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/mona/code/alternative-controllers/style_transfer/scripts/label_image.py", line 137, in <module>
    print(template.format(labels[i], results[i]))
IndexError: list index out of range
```

I was successfully able to follow the tutorial for transfer learning for flowers from Google Collab, but then I tried it on Pokemon images of 200*200 and set the image size to 224 (because it did not accept the 200), I was able to pretrain but inference does not work. Can you please guide how to fix?

I got the pokemon images from:
https://github.com/AravindVasudev/Pokedex

and I followed this codelab tutorial for transfer learning:
https://codelabs.developers.google.com/codelabs/tensorflow-for-poets/#8

As you can see the retrained_labels.txt and retrained_graph.pb are already made:

```
mona@Mona:~/code/alternative-controllers/style_transfer$ ls -ltra dataset/
total 5524
drwxrwxr-x  2 mona mona    4096 Jun 25 18:41 alakazam
drwxrwxr-x  2 mona mona    4096 Jun 25 18:41 abra
drwxrwxr-x  2 mona mona    4096 Jun 25 18:41 bulbasaur
drwxrwxr-x  2 mona mona    4096 Jun 25 18:41 blastoise
drwxrwxr-x  2 mona mona    4096 Jun 25 18:41 articuno
drwxrwxr-x  2 mona mona    4096 Jun 25 18:41 magikarp
drwxrwxr-x  2 mona mona    4096 Jun 25 18:41 ivysaur
drwxrwxr-x  2 mona mona    4096 Jun 25 18:41 gengar
drwxrwxr-x  2 mona mona    4096 Jun 25 18:41 charmeleon
drwxrwxr-x  2 mona mona    4096 Jun 25 18:41 charmander
drwxrwxr-x  2 mona mona    4096 Jun 25 18:41 charizard
drwxrwxr-x  2 mona mona    4096 Jun 25 18:41 squirtle
drwxrwxr-x  2 mona mona    4096 Jun 25 18:41 pikachu
drwxrwxr-x  2 mona mona    4096 Jun 25 18:41 moltres
drwxrwxr-x  2 mona mona    4096 Jun 25 18:41 mewtwo
drwxrwxr-x  2 mona mona    4096 Jun 25 18:41 mew
drwxrwxr-x  2 mona mona    4096 Jun 25 18:41 meowth
drwxrwxr-x  2 mona mona    4096 Jun 25 18:41 zapdos
drwxrwxr-x  2 mona mona    4096 Jun 25 18:41 wartortle
drwxrwxr-x  2 mona mona    4096 Jun 25 18:41 venusaur
drwxr-xr-x  4 mona mona    4096 Jun 25 18:45 training_summaries
drwxrwxr-x  3 mona mona    4096 Jun 25 18:45 models
drwxrwxr-x 22 mona mona    4096 Jun 25 18:45 bottlenecks
-rw-rw-r--  1 mona mona     168 Jun 25 18:45 retrained_labels.txt
-rw-rw-r--  1 mona mona 5548864 Jun 25 18:45 retrained_graph.pb
drwxrwxr-x 25 mona mona    4096 Jun 25 18:45 .
drwxrwxr-x  7 mona mona    4096 Jun 25 18:51 ..

```

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by duplex143** [comment]
@monajalal The line [73](https://github.com/googlecodelabs/tensorflow-for-poets-2/blob/master/scripts/label_image.py#L73) in [label_image.py](https://github.com/googlecodelabs/tensorflow-for-poets-2/blob/master/scripts/label_image.py) is `label_file = "tf_files/retrained_labels.txt"`. So, if you don't pass `--labels` flag, it refers to label file of flowers dataset. Your command should be 
```
python -m scripts.label_image --graph=dataset/retrained_graph.pb --image=dataset/charmander/charmander30.jpg --labels=dataset/retrained_labels.txt
```
You are getting `list index out of range` because the flowers dataset has 5 labels and I can see that you have 20.
