### ISSUE TITLE
Error while importing tensorflow in ubuntu

### ISSUE THREAD

**Issue by ellurunaresh** [tensorflow/tensorflow#20302]
Hi all,
I have installed tensorflow=1.5.0 in ubuntu 14.04. while importing tensorflow I got the below error. Please let me know how to handle this issue.

**>>> import tensorflow as tf**
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/__init__.py", line 22,                          in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-im                         port
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/__init__.py", l                         ine 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/core/framework/graph_p                         b2.py", line 15, in <module>
    from tensorflow.core.framework import node_def_pb2 as tensorflow_dot_core_do                         t_framework_dot_node__def__pb2
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/core/framework/node_de                         f_pb2.py", line 15, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_                         dot_framework_dot_attr__value__pb2
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/core/framework/attr_va                         lue_pb2.py", line 15, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_                         framework_dot_tensor__pb2
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/core/framework/tensor_                         pb2.py", line 15, in <module>
    from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_                         core_dot_framework_dot_resource__handle__pb2
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/core/framework/resourc                         e_handle_pb2.py", line 22, in <module>
    serialized_pb=_b('\n/tensorflow/core/framework/resource_handle.proto\x12\nte                         nsorflow\"r\n\x13ResourceHandleProto\x12\x0e\n\x06\x64\x65vice\x18\x01 \x01(\t\x                         12\x11\n\tcontainer\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x11\n\                         thash_code\x18\x04 \x01(\x04\x12\x17\n\x0fmaybe_type_name\x18\x05 \x01(\tBn\n\x1                         8org.tensorflow.frameworkB\x0eResourceHandleP\x01Z=github.com/tensorflow/tensorf                         low/tensorflow/go/core/framework\xf8\x01\x01\x62\x06proto3')
**TypeError: __init__() got an unexpected keyword argument 'serialized_options'**

**Comment by huangrunml** [comment]
first,you should in python environment,then import tensorflow

**Comment by ellurunaresh** [comment]
Yes I was in python environment

**Comment by huangrunml** [comment]
https://stackoverflow.com/questions/33622842/error-in-python-after-import-tensorflow-typeerror-init-got-an-unexpect/33638454，this website may help you

**Comment by ellurunaresh** [comment]
I followed the same procedure but I couldn't solve it.
pip3 uninstall protobuf
pip3 uninstall tensorflow==1.5.0
pip3 install tensorflow==1.5.0 (It installed protobuf-3.6.0 tensorflow-1.5.0)

**Comment by gunan** [comment]
This is due to latest protobuf having a backwards incompatible change.
You can try installing an older version of protobuf with this command for tensorflow 1.5
```
pip install protobuf==3.4.0
```

**Comment by tensorflowbutler** [comment]
Nagging Assignee @jart: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by gunan** [comment]
Closing because this is due to protobuf version incompatibility.
If you are using tensorflow 1.8 or older, please use protobuf version 3.4 or older.
If you are using TF 1.9 or newer, please use the latest version of protobuf.

**Comment by JinMengKang** [comment]
Hello, I encountered TypeError error when I was running the program.

File "/home/kjm/Desktop/inpainting/GatedConvolution/inpaint_ops.py", line 512, in contextual_attention
offset = tf.argmax(yi, axis=3, output_type=tf.int32)
TypeError: argmax() got an unexpected keyword argument 'output_type'

I used python3.6+tensorflow1.2.

Thank you very much for your help.

**Comment by cpoptic** [comment]
uninstalling Protobuf 3.6 and pip installing Protobuf 3.4.0 as per the above instructions but importing tensorflow still yields same error message about **TypeError: init() got an unexpected keyword argument 'serialized_option**

Instailling Protobuf==3.4   gives this error:

tensorflow 1.11.0 has requirement protobuf>=3.6.0, but you'll have protobuf 3.4.0 which is incompatible.

So using the most up-to-date version of Tensorflow requires protobuf>-3.6.0 but using that version yields a serialized_option error.  What to do?

**Comment by wei-v-wang** [comment]
@cpoptic I think the suggestion was to use the latest version of protobuf (3.6.0+) for TF v1.11 

You probably need to try uninstall protobuf for every user account (root and non-root) to avoid your user setting picking a system installed protobuf. 

Then you do the "pip install protobuf" again after making sure there are no protobuf system-wide.
