### ISSUE TITLE
InternalError: Dst tensor is not initialized.

### ISSUE THREAD

**Issue by jaiaravind4u** [tensorflow/tensorflow#20301]
`2018-06-26 09:22:30.314633: W tensorflow/core/common_runtime/bfc_allocator.cc:277] **************xx***x******************************************xx********xx***********_____**********
Traceback (most recent call last):
  File "/home/bitwise/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1323, in _do_call
    return fn(*args)
  File "/home/bitwise/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1302, in _run_fn
    status, run_metadata)
  File "/home/bitwise/.local/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InternalError: Dst tensor is not initialized.
         [[Node: dynamic_seq2seq/decoder/embedding_lookup/_61 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_50_dynamic_seq2seq/decoder/embedding_lookup", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 21, in <module>
    tf.app.run(main=nmt.main, argv=[os.getcwd() + '\nmt\nmt\nmt.py'] + unparsed)
  File "/home/bitwise/.local/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/datadrived/jai/nmt-chatbot-v1/nmt/nmt/nmt.py", line 529, in main
    run_main(FLAGS, default_hparams, train_fn, inference_fn)
  File "/datadrived/jai/nmt-chatbot-v1/nmt/nmt/nmt.py", line 522, in run_main
    train_fn(hparams, target_session=target_session)
  File "/datadrived/jai/nmt-chatbot-v1/nmt/nmt/train.py", line 251, in train
    sample_tgt_data)
  File "/datadrived/jai/nmt-chatbot-v1/nmt/nmt/train.py", line 125, in run_full_eval
    eval_model, eval_sess, model_dir, hparams, summary_writer)
  File "/datadrived/jai/nmt-chatbot-v1/nmt/nmt/train.py", line 56, in run_internal_eval
    summary_writer, "dev")
  File "/datadrived/jai/nmt-chatbot-v1/nmt/nmt/train.py", line 405, in _internal_eval
    ppl = model_helper.compute_perplexity(model, sess, label)
  File "/datadrived/jai/nmt-chatbot-v1/nmt/nmt/model_helper.py", line 414, in compute_perplexity
    loss, predict_count, batch_size = model.eval(sess)
  File "/datadrived/jai/nmt-chatbot-v1/nmt/nmt/model.py", line 221, in eval
    self.batch_size])
  File "/home/bitwise/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/home/bitwise/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/bitwise/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/home/bitwise/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Dst tensor is not initialized.
         [[Node: dynamic_seq2seq/decoder/embedding_lookup/_61 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_50_dynamic_seq2seq/decoder/embedding_lookup", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
`

I get the above error when i try to run the train.py using the gpu server

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by jaiaravind4u** [comment]
Have I written custom code - yes
OS Platform and Distribution - Ubuntu 16.04
TensorFlow installed from - official tensorflow site
TensorFlow version - tensorflow-gpu 1.4
Bazel version - N/A
CUDA/cuDNN version - 8.0/6.0
GPU model and memory - NVIDIA Tesla K80 GPU on azure GPU server NC6 instance
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
Nagging Assignee @bignamehyp: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.
