### ISSUE TITLE
Tensorflow failed to build on x64 when build with MSVC

### ISSUE THREAD

**Issue by shanshan0309** [tensorflow/tensorflow#20336]
System information
•	Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
N/A
•	OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Windows server 2016
•	TensorFlow installed from (source or binary):
Source
•	TensorFlow version (use command below):
Master branch latest revison
•	Python version:
Anaconda 4.1.1 (Python 3.5 64-bit)
•	Bazel version (if compiling from source):
N/A
•	GCC/Compiler version (if compiling from source):
VS2017 15.5.7
•	CUDA/cuDNN version:
NVidia CUDA Toolkit 8.0
NVidia CUDNN 5.1
•	GPU model and memory:
N/A
•	Exact command to reproduce:
N/A

**Describe the problem:**
Tensorflow failed to build on x64. This issue can be reproduced from the master revision 68bb435. This should be tensorflow source issue, could you please help take a look at this? Thanks!

**The failures like:**
The whole log file please see attachment.
[tensorflow_x64_build.log](https://github.com/tensorflow/tensorflow/files/2140452/tensorflow_x64_build.log)

**Repro steps:**
1. git clone https://github.com/tensorflow/tensorflow D:\Tensorflow\src
2. pushd D:\Tensorflow
3. set PreferredToolArchitecture=x64
4. set rel=Release
5. set CUDNN_HOME="C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\cuda"
6. set PY=C:\ProgramData\Anaconda3
7. set CL=/FS /permissive-
8. cmake D:\Tensorflow\src\tensorflow\contrib\cmake -A x64 -DCMAKE_BUILD_TYPE=Release -DPYTHON_EXECUTABLE=C:\ProgramData\Anaconda3\python.exe -DPYTHON_LIBRARIES=C:\ProgramData\Anaconda3\libs\python36.lib -DSWIG_EXECUTABLE=D:\Tensorflow\swigwin-3.0.12\swig.exe -Dtensorflow_BUILD_PYTHON_TESTS=ON -Dtensorflow_BUILD_SHARED_LIB=ON
9. MSBuild /m /p:Configuration=Release;Platform=x64 /p:WindowsTargetPlatformVersion=10.0.17134.0 tensorflow.sln /t:Rebuild

**Comment by shanshan0309** [comment]
Hello,
Any update for this?

**Comment by icedream2linxi** [comment]
为什么不编译 Release 版？

> Why not compile the Release version?

**Comment by mrry** [comment]
Here's the error:

```
   526>CustomBuild:
         Generating __init__.py files for Python API.
         Traceback (most recent call last):
           File "D:/Tensorflow/build_x64/tf_python/tensorflow/tools/api/generator/create_python_api.py", line 27, in <module>
             from tensorflow.python.util import tf_decorator
           File "D:\Tensorflow\build_x64\tf_python\tensorflow\python\__init__.py", line 52, in <module>
             from tensorflow.core.framework.graph_pb2 import *
           File "D:\Tensorflow\build_x64\tf_python\tensorflow\core\framework\graph_pb2.py", line 15, in <module>
             from tensorflow.core.framework import node_def_pb2 as tensorflow_dot_core_dot_framework_dot_node__def__pb2
           File "D:\Tensorflow\build_x64\tf_python\tensorflow\core\framework\node_def_pb2.py", line 15, in <module>
             from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
           File "D:\Tensorflow\build_x64\tf_python\tensorflow\core\framework\attr_value_pb2.py", line 15, in <module>
             from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
           File "D:\Tensorflow\build_x64\tf_python\tensorflow\core\framework\tensor_pb2.py", line 15, in <module>
             from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
           File "D:\Tensorflow\build_x64\tf_python\tensorflow\core\framework\resource_handle_pb2.py", line 22, in <module>
             serialized_pb=_b('\n/tensorflow/core/framework/resource_handle.proto\x12\ntensorflow\"r\n\x13ResourceHandleProto\x12\x0e\n\x06\x64\x65vice\x18\x01 \x01(\t\x12\x11\n\tcontainer\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x11\n\thash_code\x18\x04 \x01(\x04\x12\x17\n\x0fmaybe_type_name\x18\x05 \x01(\tBn\n\x18org.tensorflow.frameworkB\x0eResourceHandleP\x01Z=github.com/tensorflow/tensorflow/tensorflow/go/core/framework\xf8\x01\x01\x62\x06proto3')
         TypeError: __new__() got an unexpected keyword argument 'serialized_options'
```

It looks like there is a mismatch between the installed version of the `protobuf` package for your Python environment and the version used for generating code in the TensorFlow build. Try upgrading to protobuf 3.6.0 using `pip install -U protobuf==3.6.0` and then rebuilding.

**Comment by LoSealL** [comment]
There's also another issue when importing compiled protobuf, see my response to #20669

**Comment by tensorflowbutler** [comment]
It has been 15 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
It has been 30 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by mrry** [comment]
Hi folks, since we are not maintaining the CMake build after TF 1.10 (https://github.com/tensorflow/tensorflow/releases/tag/v1.10.0), I'd recommend trying to reproduce this using the Bazel for Windows build. This page has instructions for building with Bazel on Windows:

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/docs_src/install/install_sources_windows.md

If you continue to have problems building using Bazel for Windows, please open a new issue with details of the problem.
