### ISSUE TITLE
how to build the project for intel x86 emulator instead of armeabi v7?

### ISSUE THREAD

**Issue by CalmWaves** [tensorflow/tensorflow#2035]
Hi, I am beginner in android,

  I have successfully built the android demo with bazel. Now I am trying to work with it in Android studio.

 I found this repository [https://github.com/miyosuda/TensorFlowAndroidDemo](url).
 It currently works well with **armeabiv7** but crashes with **intel x86**  emulator. 

But I want to build it for **intel x86 and x86_64** and I want to **build it in Android studio** using gradle what should I do? Please help

I am using 
                  NDK 10re 
                  Android Studio 2.0
                  UBUNTU 14.04

**Comment by andrewharp** [comment]
I've never used Gradle before, but the project you linked to seems to be configured to only produce armeabi-v7a builds. I assume you'd edit the occurrences here: https://github.com/miyosuda/TensorFlowAndroidDemo/search?utf8=%E2%9C%93&q=armeabi-v7a
and add x86 and x86_64 to each.

**Comment by CalmWaves** [comment]
I modified the Makefile and the Application.mk as you said but I am getting this error with the make command

> kaushalya@kaushalya-HP-350-G1:~/TensorFlowAndroidDemo-master/jni-build$ make
ndk-build
Android NDK: WARNING:jni/Android.mk:tensorflow_demo: non-system libraries in linker flags: jni/libs/armeabi-v7a/libandroid_tensorflow_lib.a jni/libs/armeabi-v7a/libre2.a jni/libs/armeabi-v7a/libprotos_all_cc.a jni/libs/armeabi-v7a/libprotobuf.a jni/libs/armeabi-v7a/libprotobuf_lite.a /home/kaushalya/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/libgnustl_static.a /home/kaushalya/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/libsupc++.a    
Android NDK:     This is likely to result in incorrect builds. Try using LOCAL_STATIC_LIBRARIES    
Android NDK:     or LOCAL_SHARED_LIBRARIES instead to list the library dependencies of the    
Android NDK:     current module    
Android NDK: WARNING:jni/Android.mk:tensorflow_demo: non-system libraries in linker flags: jni/libs/x86/libandroid_tensorflow_lib.a jni/libs/x86/libre2.a jni/libs/x86/libprotos_all_cc.a jni/libs/x86/libprotobuf.a jni/libs/x86/libprotobuf_lite.a /home/kaushalya/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/libs/x86/libgnustl_static.a /home/kaushalya/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/libs/x86/libsupc++.a    
Android NDK:     This is likely to result in incorrect builds. Try using LOCAL_STATIC_LIBRARIES    
Android NDK:     or LOCAL_SHARED_LIBRARIES instead to list the library dependencies of the    
Android NDK:     current module    
Android NDK: WARNING:jni/Android.mk:tensorflow_demo: non-system libraries in linker flags: jni/libs/x86_64/libandroid_tensorflow_lib.a jni/libs/x86_64/libre2.a jni/libs/x86_64/libprotos_all_cc.a jni/libs/x86_64/libprotobuf.a jni/libs/x86_64/libprotobuf_lite.a /home/kaushalya/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/libs/x86_64/libgnustl_static.a /home/kaushalya/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/libs/x86_64/libsupc++.a    
Android NDK:     This is likely to result in incorrect builds. Try using LOCAL_STATIC_LIBRARIES    
Android NDK:     or LOCAL_SHARED_LIBRARIES instead to list the library dependencies of the    
Android NDK:     current module    
make[1]: Entering directory `/home/kaushalya/TensorFlowAndroidDemo-master/jni-build'
[armeabi-v7a] Compile++ arm  : tensorflow_demo <= tensorflow_jni.cc
[armeabi-v7a] Compile++ arm  : tensorflow_demo <= imageutils_jni.cc
[armeabi-v7a] Compile++ arm  : tensorflow_demo <= jni_utils.cc
[armeabi-v7a] Compile++ arm  : tensorflow_demo <= rgb2yuv.cc
[armeabi-v7a] Compile++ arm  : tensorflow_demo <= yuv2rgb.cc
[armeabi-v7a] SharedLibrary  : libtensorflow_demo.so
[armeabi-v7a] Install        : libtensorflow_demo.so => libs/armeabi-v7a/libtensorflow_demo.so
[x86] Compile++      : tensorflow_demo <= tensorflow_jni.cc
i686-linux-android-g++: error: unrecognized command line option '-mfpu=vfpv3-d16'
i686-linux-android-g++: error: unrecognized command line option '-mfloat-abi=softfp'
i686-linux-android-g++: error: unrecognized command line option '-mfpu=neon'
make[1]: *** [obj/local/x86/objs/tensorflow_demo/./tensorflow_jni.o] Error 1
make[1]: Leaving directory `/home/kaushalya/TensorFlowAndroidDemo-master/jni-build'
make: *** [build] Error 2
kaushalya@kaushalya-HP-350-G1:~/TensorFlowAndroidDemo-master/jni-build$ 

I think there should be change in Android.mk too. But I do not know how?

**Comment by andrewharp** [comment]
It looks like you'll also need to make sure the copts given to the compiler match the ones for Android arm defined in tensorflow.bzl. There are flags that only work for building x86, and likewise some that only work for arm.

**Comment by miyosuda** [comment]
Sorry for inconvenience with my project and let me investigate about this.

By the way this repository,
https://github.com/miyosuda/TensorFlowAndroidDemo
is using .a library files and headers from TensorFlow 0.6.0.

I've recently upgraded another repository with MNIST sample
https://github.com/miyosuda/TensorFlowAndroidMNIST
with latest TensorFlow r0.8.

Let me upgrade TensorFlowAndroidDemo with r0.8 too.

**Comment by miyosuda** [comment]
@CalmWaves 
I've prepared compiler options and .a library files for x86 and x86_64
Could you try this branch?

https://github.com/miyosuda/TensorFlowAndroidDemo/tree/x86

When I tried this with x86 emulator, the app crashed with IllegalArgumentException at
CameraManager.openCamera()
because emulator does not have camera.

**Comment by CalmWaves** [comment]
Forgive me for late response, In my situation app crashes, although I have used my web cam as the emulator camera,
Emulator details:

> Name: Nexus_5X_API_23
CPU/ABI: Google APIs Intel Atom (x86)
Path: /home/kaushalya/.android/avd/Nexus_5X_API_23.avd
Target: google_apis [Google APIs] (API level 23)
Skin: nexus_5x
SD Card: /home/kaushalya/.android/avd/Nexus_5X_API_23.avd/sdcard.img
hw.dPad: no
runtime.network.speed: full
hw.accelerometer: yes
hw.device.name: Nexus 5X
vm.heapSize: 512
hw.device.manufacturer: Google
hw.gps: yes
image.androidVersion.api: 23
hw.audioInput: yes
image.sysdir.1: system-images/android-23/google_apis/x86/
tag.id: google_apis
hw.camera.back: webcam0
hw.mainKeys: no
AvdId: Nexus_5X_API_23
hw.camera.front: webcam0
hw.lcd.density: 420
runtime.scalefactor: auto
avd.ini.displayname: Nexus 5X API 23
hw.gpu.mode: auto
hw.device.hash2: MD5:1be89bc42ec9644d4b77968b23474980
hw.ramSize: 2048
hw.trackBall: no
hw.battery: yes
hw.sdCard: yes
tag.display: Google APIs
runtime.network.latency: none
hw.keyboard: yes
hw.sensors.proximity: yes
disk.dataPartition.size: 800M
hw.sensors.orientation: yes
avd.ini.encoding: UTF-8
hw.gpu.enabled: yes

when I open the default emulator Camera app it works fine.
but in logcat it gives:

> 04-25 19:00:52.728 1941-2192/com.google.android.googlequicksearchbox E/Surface: getSlotFromBufferLocked: unknown buffer: 0xb2e79620
04-25 19:00:59.060 1186-1186/? E/EGL_emulation: tid 1186: eglCreateSyncKHR(1294): error 0x3004 (EGL_BAD_ATTRIBUTE)
04-25 19:00:59.242 1196-1539/? E/CameraService: disconnect: Disconnect called on already disconnected client for device 0
04-25 19:00:59.403 2260-2294/com.android.camera E/Surface: getSlotFromBufferLocked: unknown buffer: 0xb28848b0

When I open the TF_Demo 

App crashes

in logcat:

> 04-25 19:02:14.167 3250-3250/org.tensorflow.tensorflowdemo E/AndroidRuntime: FATAL EXCEPTION: main
                                                                             Process: org.tensorflow.tensorflowdemo, PID: 3250
                                                                             java.lang.SecurityException: Lacking privileges to access camera service
                                                                                 at android.hardware.camera2.utils.CameraBinderDecorator.throwOnError(CameraBinderDecorator.java:108)
                                                                                 at android.hardware.camera2.legacy.CameraDeviceUserShim.connectBinderShim(CameraDeviceUserShim.java:336)
                                                                                 at android.hardware.camera2.CameraManager.openCameraDeviceUserAsync(CameraManager.java:327)
                                                                                 at android.hardware.camera2.CameraManager.openCamera(CameraManager.java:457)
                                                                                 at org.tensorflow.demo.CameraConnectionFragment.openCamera(CameraConnectionFragment.java:380)
                                                                                 at org.tensorflow.demo.CameraConnectionFragment.access$000(CameraConnectionFragment.java:63)
                                                                                 at org.tensorflow.demo.CameraConnectionFragment$1.onSurfaceTextureAvailable(CameraConnectionFragment.java:96)
                                                                                 at android.view.TextureView.getHardwareLayer(TextureView.java:368)
                                                                                 at android.view.View.updateDisplayListIfDirty(View.java:15151)
                                                                                 at android.view.View.draw(View.java:15948)
                                                                                 at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                                 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                                 at android.view.View.updateDisplayListIfDirty(View.java:15169)
                                                                                 at android.view.View.draw(View.java:15948)
                                                                                 at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                                 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                                 at android.view.View.draw(View.java:16181)
                                                                                 at android.view.View.updateDisplayListIfDirty(View.java:15174)
                                                                                 at android.view.View.draw(View.java:15948)
                                                                                 at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                                 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                                 at android.view.View.updateDisplayListIfDirty(View.java:15169)
                                                                                 at android.view.View.draw(View.java:15948)
                                                                                 at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                                 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                                 at android.view.View.updateDisplayListIfDirty(View.java:15169)
                                                                                 at android.view.View.draw(View.java:15948)
                                                                                 at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                                 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                                 at android.view.View.draw(View.java:16181)
                                                                                 at com.android.internal.policy.PhoneWindow$DecorView.draw(PhoneWindow.java:2690)
                                                                                 at android.view.View.updateDisplayListIfDirty(View.java:15174)
                                                                                 at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:281)
                                                                                 at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:287)
                                                                                 at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:322)
                                                                                 at android.view.ViewRootImpl.draw(ViewRootImpl.java:2615)
                                                                                 at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2434)
                                                                                 at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2067)
                                                                                 at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
                                                                                 at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
                                                                                 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                                 at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                                 at android.view.Choreographer.doFrame(Choreographer.java:606)
                                                                                 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                                 at android.os.Handler.handleCallback(Handler.java:739)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                 at android.os.Looper.loop(Looper.java:148)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
> 

what should I do? have you tried with emulator with webcam as the camera. what was you detail configurations?

**Comment by CalmWaves** [comment]
I tested with emulator with the config given above except this emulator uses API 21 and it gives me in logcat:

> 04-25 19:57:18.936 2313-2382/org.tensorflow.tensorflowdemo E/EGL_emulation: tid 2382: eglCreateContext(877): error 0x3005 (EGL_BAD_CONFIG)
04-25 19:57:18.936 2313-2382/org.tensorflow.tensorflowdemo E/CameraDeviceGLThread-0: Received exception on GL render thread: 
                                                                                     java.lang.IllegalStateException: eglCreateContext: EGL error: 0x3005
                                                                                         at android.hardware.camera2.legacy.SurfaceTextureRenderer.checkEglError(SurfaceTextureRenderer.java:487)
                                                                                         at android.hardware.camera2.legacy.SurfaceTextureRenderer.configureEGLContext(SurfaceTextureRenderer.java:386)
                                                                                         at android.hardware.camera2.legacy.SurfaceTextureRenderer.configureSurfaces(SurfaceTextureRenderer.java:600)
                                                                                         at android.hardware.camera2.legacy.GLThreadManager$1.handleMessage(GLThreadManager.java:87)
                                                                                         at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                         at android.os.Looper.loop(Looper.java:135)
                                                                                         at android.os.HandlerThread.run(HandlerThread.java:61)


tensorflow demo app stays with empty blue band with totally black camera input area.

Another thing to notice is here default camera app on the emulator crashes. with the messages given below in the emulator message view:

> emulator: ERROR: camera_device_start_capturing: VIDIOC_STREAMON on camera '/dev/video0' has failed: Timer expired
emulator: ERROR: _camera_client_query_start: Cannot start camera '/dev/video0' for NV21[640x480]: Inappropriate ioctl for device

help me on this? If someone can drop API level of the app to 19 I can try it on my phone?

**Comment by andrewharp** [comment]
The only thing preventing the demo from running on API 19 is that it uses the camera2 api. If you rewrite the relevant code to use android.hardware.Camera it will run fine on older devices.

In general I haven't found emulators and cameras to get along, unfortunately. If possible I'd suggest running on a real device or altering the code to take canned images (if you're just trying to test a model).

**Comment by andrewharp** [comment]
Closing this now as your original issue has been addressed (thanks 
@miyosuda!) and there are complete instructions for adapting the TF demo to api level < 21 in https://github.com/tensorflow/tensorflow/issues/419 now.

Emulator support for cameras is outside the scope of Tensorflow support (I'd try stackoverflow for that), but feel free to open any additional TF-specific issues you have with the demo.

**Comment by CalmWaves** [comment]
Thank you @andrewharp  and @miyosuda.
