### ISSUE TITLE
MirroredStrategy fails with "no supported kernel for GPU devices is available"

### ISSUE THREAD

**Issue by martin-gorner** [tensorflow/tensorflow#20370]
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: YES
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: ML Engine default
- **TensorFlow installed from (source or binary)**: ML Engine default
- **TensorFlow version (use command below)**: 1.8
- **Python version**: 2.6
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: ML Engine default
- **GPU model and memory**: NVIDIA Tesla K80
- **Exact command to reproduce**: N/A

MirroredStrategy fails with "no supported kernel for GPU devices is available". The same code works on a single GPU.

Traceback:
Traceback (most recent call last): File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main "__main__", fname, loader, pkg_name) File "/usr/lib/python2.7/runpy.py", line 72, in _run_code exec code in run_globals File "/root/.local/lib/python2.7/site-packages/trainer_yolo/main.py", line 188, in <module> main(sys.argv) File "/root/.local/lib/python2.7/site-packages/trainer_yolo/main.py", line 184, in main start_training(output_dir, hparams, **otherargs) File "/root/.local/lib/python2.7/site-packages/trainer_yolo/main.py", line 131, in start_training tf.estimator.train_and_evaluate(estimator, train_spec, eval_spec) File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/training.py", line 439, in train_and_evaluate executor.run() File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/training.py", line 546, in run getattr(self, task_to_run)() File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/training.py", line 601, in run_master self._start_distributed_training(saving_listeners=saving_listeners) File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/training.py", line 739, in _start_distributed_training saving_listeners=saving_listeners) File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 363, in train loss = self._train_model(input_fn, hooks, saving_listeners) File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 841, in _train_model return self._train_model_distributed(input_fn, hooks, saving_listeners) File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 977, in _train_model_distributed saving_listeners) File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 1056, in _train_with_estimator_spec log_step_count_steps=self._config.log_step_count_steps) as mon_sess: File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 405, in MonitoredTrainingSession stop_grace_period_secs=stop_grace_period_secs) File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 816, in __init__ stop_grace_period_secs=stop_grace_period_secs) File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 539, in __init__ self._sess = _RecoverableSession(self._coordinated_creator) File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 1002, in __init__ _WrappedSession.__init__(self, self._create_session()) File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 1007, in _create_session return self._sess_creator.create_session() File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 696, in create_session self.tf_sess = self._session_creator.create_session() File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 467, in create_session init_fn=self._scaffold.init_fn) File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/session_manager.py", line 285, in prepare_session sess.run(init_op, feed_dict=init_feed_dict) File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 900, in run run_metadata_ptr) File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1135, in _run feed_dict_tensor, options, run_metadata) File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1316, in _do_run run_metadata) File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1335, in _do_call raise type(e)(node_def, op, message) InvalidArgumentError: Cannot assign a device for operation 'tower_3/Tile_7/input': Could not satisfy explicit device specification '/device:GPU:3' because **no supported kernel for GPU devices is available**. Registered kernels: device='CPU'; T in [DT_QINT32] device='CPU'; T in [DT_QUINT8] device='CPU'; T in [DT_QINT8] device='CPU'; T in [DT_VARIANT] device='CPU'; T in [DT_RESOURCE] device='CPU'; T in [DT_STRING] device='CPU'; T in [DT_BOOL] device='CPU'; T in [DT_COMPLEX128] device='CPU'; T in [DT_COMPLEX64] device='CPU'; T in [DT_DOUBLE] device='CPU'; T in [DT_FLOAT] device='CPU'; T in [DT_BFLOAT16] device='CPU'; T in [DT_HALF] device='CPU'; T in [DT_INT8] device='CPU'; T in [DT_UINT8] device='CPU'; T in [DT_INT16] device='CPU'; T in [DT_UINT16] device='CPU'; T in [DT_INT32] device='CPU'; T in [DT_INT64] device='GPU'; T in [DT_INT32] device='GPU'; T in [DT_BOOL] device='GPU'; T in [DT_INT64] device='GPU'; T in [DT_BFLOAT16] device='GPU'; T in [DT_DOUBLE] device='GPU'; T in [DT_FLOAT] device='GPU'; T in [DT_HALF] [[Node: tower_3/Tile_7/input = Pack[N=1, T=DT_INT16, axis=0, _device="/device:GPU:3"](tower_3/Cast_4)]] Caused by op u'tower_3/Tile_7/input', defined at: File "/usr/lib/python2.7/threading.py", line 774, in __bootstrap self.__bootstrap_inner() File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner self.run() File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/distribute/python/mirrored_strategy.py", line 465, in run self.main_result = self.main_fn(*self.main_args, **self.main_kwargs) File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 831, in _call_model_fn model_fn_results = self._model_fn(features=features, **kwargs) File "/root/.local/lib/python2.7/site-packages/trainer_yolo/model.py", line 230, in model_fn iou_accuracy = box.compute_safe_IOU(target_rois, detected_rois, detected_rois_overflow, settings.TILE_SIZE) File "/root/.local/lib/python2.7/site-packages/trainer_yolo/utils_box.py", line 521, in compute_safe_IOU iou_accuracy = IOUCalculator.batch_intersection_over_union(detected_rois * tile_size, target_rois * tile_size, tile_size=tile_size) File "/root/.local/lib/python2.7/site-packages/trainer_yolo/utils_box.py", line 476, in batch_intersection_over_union linmap2 = cls.__iou_gen_linmap(batch, n2, tile_size) File "/root/.local/lib/python2.7/site-packages/trainer_yolo/utils_box.py", **line 428, in __iou_gen_linmap linmap = tf.tile([row], [tile_size, 1])** File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 8430, in tile "Tile", input=input, multiples=multiples, name=name) File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 510, in _apply_op_helper preferred_dtype=default_dtype) File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1104, in internal_convert_to_tensor ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref) File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 1034, in _autopacking_conversion_function return _autopacking_helper(v, inferred_dtype, name or "packed") File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 997, in _autopacking_helper return gen_array_ops.pack(elems_as_tensors, name=scope) File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 4517, in pack "Pack", values=values, axis=axis, name=name) File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper op_def=op_def) File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3392, in create_op op_def=op_def) File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1718, in __init__ self._traceback = self._graph._extract_stack() # pylint: disable=protected-access InvalidArgumentError (see above for traceback): Cannot assign a device for operation 'tower_3/Tile_7/input': Could not satisfy explicit device specification '/device:GPU:3' because **no supported kernel for GPU devices is available**. Registered kernels: device='CPU'; T in [DT_QINT32] device='CPU'; T in [DT_QUINT8] device='CPU'; T in [DT_QINT8] device='CPU'; T in [DT_VARIANT] device='CPU'; T in [DT_RESOURCE] device='CPU'; T in [DT_STRING] device='CPU'; T in [DT_BOOL] device='CPU'; T in [DT_COMPLEX128] device='CPU'; T in [DT_COMPLEX64] device='CPU'; T in [DT_DOUBLE] device='CPU'; T in [DT_FLOAT] device='CPU'; T in [DT_BFLOAT16] device='CPU'; T in [DT_HALF] device='CPU'; T in [DT_INT8] device='CPU'; T in [DT_UINT8] device='CPU'; T in [DT_INT16] device='CPU'; T in [DT_UINT16] device='CPU'; T in [DT_INT32] device='CPU'; T in [DT_INT64] device='GPU'; T in [DT_INT32] device='GPU'; T in [DT_BOOL] device='GPU'; T in [DT_INT64] device='GPU'; T in [DT_BFLOAT16] device='GPU'; T in [DT_DOUBLE] device='GPU'; T in [DT_FLOAT] device='GPU'; T in [DT_HALF] [[Node: tower_3/Tile_7/input = Pack[N=1, T=DT_INT16, axis=0, _device="/device:GPU:3"](tower_3/Cast_4)]]

**Comment by martin-gorner** [comment]
I managed to remove the offending instruction but the code failed in a different place:

Traceback (most recent call last): File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main "__main__", fname, loader, pkg_name) File "/usr/lib/python2.7/runpy.py", line 72, in _run_code exec code in run_globals File "/root/.local/lib/python2.7/site-packages/trainer_yolo/main.py", line 188, in <module> main(sys.argv) File "/root/.local/lib/python2.7/site-packages/trainer_yolo/main.py", line 184, in main start_training(output_dir, hparams, **otherargs) File "/root/.local/lib/python2.7/site-packages/trainer_yolo/main.py", line 131, in start_training tf.estimator.train_and_evaluate(estimator, train_spec, eval_spec) File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/training.py", line 439, in train_and_evaluate executor.run() File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/training.py", line 546, in run getattr(self, task_to_run)() File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/training.py", line 601, in run_master self._start_distributed_training(saving_listeners=saving_listeners) File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/training.py", line 739, in _start_distributed_training saving_listeners=saving_listeners) File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 363, in train loss = self._train_model(input_fn, hooks, saving_listeners) File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 841, in _train_model return self._train_model_distributed(input_fn, hooks, saving_listeners) File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 977, in _train_model_distributed saving_listeners) File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 1056, in _train_with_estimator_spec log_step_count_steps=self._config.log_step_count_steps) as mon_sess: File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 405, in MonitoredTrainingSession stop_grace_period_secs=stop_grace_period_secs) File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 816, in __init__ stop_grace_period_secs=stop_grace_period_secs) File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 539, in __init__ self._sess = _RecoverableSession(self._coordinated_creator) File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 1002, in __init__ _WrappedSession.__init__(self, self._create_session()) File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 1007, in _create_session return self._sess_creator.create_session() File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 696, in create_session self.tf_sess = self._session_creator.create_session() File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 467, in create_session init_fn=self._scaffold.init_fn) File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/session_manager.py", line 285, in prepare_session sess.run(init_op, feed_dict=init_feed_dict) File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 900, in run run_metadata_ptr) File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1135, in _run feed_dict_tensor, options, run_metadata) File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1316, in _do_run run_metadata) File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1335, in _do_call raise type(e)(node_def, op, message) InvalidArgumentError: Cannot assign a device for operation 'concat_97': Could not satisfy explicit device specification '/device:GPU:0' because no supported kernel for GPU devices is available. Registered kernels: device='GPU'; T in [DT_INT32] device='GPU'; T in [DT_BOOL] device='GPU'; T in [DT_INT64] device='GPU'; T in [DT_COMPLEX128] device='GPU'; T in [DT_COMPLEX64] device='GPU'; T in [DT_UINT8] device='GPU'; T in [DT_BFLOAT16] device='GPU'; T in [DT_DOUBLE] device='GPU'; T in [DT_FLOAT] device='GPU'; T in [DT_HALF] device='CPU'; T in [DT_QINT32] device='CPU'; T in [DT_QINT16] device='CPU'; T in [DT_QUINT16] device='CPU'; T in [DT_QINT8] device='CPU'; T in [DT_QUINT8] device='CPU'; T in [DT_STRING] device='CPU'; T in [DT_BOOL] device='CPU'; T in [DT_COMPLEX128] device='CPU'; T in [DT_COMPLEX64] device='CPU'; T in [DT_DOUBLE] device='CPU'; T in [DT_FLOAT] device='CPU'; T in [DT_BFLOAT16] device='CPU'; T in [DT_HALF] device='CPU'; T in [DT_INT8] device='CPU'; T in [DT_UINT8] device='CPU'; T in [DT_INT16] device='CPU'; T in [DT_UINT16] device='CPU'; T in [DT_INT32] device='CPU'; T in [DT_INT64] [[Node: concat_97 = ConcatV2[N=2, T=DT_STRING, Tidx=DT_INT32, _device="/device:GPU:0"](report_uninitialized_variables/boolean_mask/GatherV2, report_uninitialized_resources/Const, concat_97/axis)]] Caused by op u'concat_97', defined at: File "/usr/lib/python2.7/threading.py", line 774, in __bootstrap self.__bootstrap_inner() File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner self.run() File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/distribute/python/mirrored_strategy.py", line 465, in run self.main_result = self.main_fn(*self.main_args, **self.main_kwargs) File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 1139, in create_per_tower_ready_op 'ready_op', ops.GraphKeys.READY_OP, default_ready_op) File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 264, in get_or_default op = default_constructor() File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 1136, in default_ready_op ], 0) File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 1189, in concat return gen_array_ops.concat_v2(values=values, axis=axis, name=name) File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 953, in concat_v2 "ConcatV2", values=values, axis=axis, name=name) File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper op_def=op_def) File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3392, in create_op op_def=op_def) File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1718, in __init__ self._traceback = self._graph._extract_stack() # pylint: disable=protected-access InvalidArgumentError (see above for traceback): Cannot assign a device for operation 'concat_97': Could not satisfy explicit device specification '/device:GPU:0' because no supported kernel for GPU devices is available. Registered kernels: device='GPU'; T in [DT_INT32] device='GPU'; T in [DT_BOOL] device='GPU'; T in [DT_INT64] device='GPU'; T in [DT_COMPLEX128] device='GPU'; T in [DT_COMPLEX64] device='GPU'; T in [DT_UINT8] device='GPU'; T in [DT_BFLOAT16] device='GPU'; T in [DT_DOUBLE] device='GPU'; T in [DT_FLOAT] device='GPU'; T in [DT_HALF] device='CPU'; T in [DT_QINT32] device='CPU'; T in [DT_QINT16] device='CPU'; T in [DT_QUINT16] device='CPU'; T in [DT_QINT8] device='CPU'; T in [DT_QUINT8] device='CPU'; T in [DT_STRING] device='CPU'; T in [DT_BOOL] device='CPU'; T in [DT_COMPLEX128] device='CPU'; T in [DT_COMPLEX64] device='CPU'; T in [DT_DOUBLE] device='CPU'; T in [DT_FLOAT] device='CPU'; T in [DT_BFLOAT16] device='CPU'; T in [DT_HALF] device='CPU'; T in [DT_INT8] device='CPU'; T in [DT_UINT8] device='CPU'; T in [DT_INT16] device='CPU'; T in [DT_UINT16] device='CPU'; T in [DT_INT32] device='CPU'; T in [DT_INT64] [[Node: concat_97 = ConcatV2[N=2, T=DT_STRING, Tidx=DT_INT32, _device="/device:GPU:0"](report_uninitialized_variables/boolean_mask/GatherV2, report_uninitialized_resources/Const, concat_97/axis)]]

**Comment by martin-gorner** [comment]
I got rid of the "pack" instruction. The code now fails in a different place (see trace above) and I am not able to identify where in my code it is. It looks like it is not in my code at all. What i do not understand is how can this work on a single GPU and fail with MirroredStrategy ?

**Comment by yongtang** [comment]
Added a PR #20378 to support int16 of Pack in GPU.

**Comment by guptapriya** [comment]
@martin-gorner could you point me to your code? I think the failure doesn't happen on single GPU because the concat op that's failing wouldn't exist in that case (assuming you're running on one GPU without using any distribution strategy).
From what i can tell from the stack trace, the concat is from there:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/estimator/estimator.py#L1456
This code in estimator is only reached when a distribution strategy like MirroredStrategy is present.

**Comment by martin-gorner** [comment]
OK, understood.
@yongtang the second issue seems to be with "concat", not "pack"

**Comment by martin-gorner** [comment]
@guptapriya done
code sent through direct message

**Comment by drpngx** [comment]
Can you go back to the descriptions and format your log file?

Thank you.

**Comment by martin-gorner** [comment]
"format your log file" > I do not know what you mean ?

**Comment by yongtang** [comment]
@martin-gorner If you use (three backticks):
````
```
Traceback:
Traceback (most recent call last): 
```
````

The it will be formatted like the following:
```
Traceback:
Traceback (most recent call last): 
```

**Comment by yuefengz** [comment]
Don't use MirroredStrategy for between-graph replicated training for now. It doesn't work with "worker" and "ps" jobs. We'll have a strategy that works in this case.

**Comment by ajbouh** [comment]
@yuefengz What strategy do you recommend for putting models on "ps" jobs?

**Comment by yuefengz** [comment]
@ajbouh We'll have a ParameterServerStrategy soon which works both locally and on a cluster.

**Comment by yuefengz** [comment]
It is still under review.
