### ISSUE TITLE
TypeError: 'InvalidArgumentError' object is not iterable

### ISSUE THREAD

**Issue by whatdhack** [tensorflow/tensorflow#20382]
Occasionally encounter   issues like the above during training.  Tensorflow does not provide any information about  where is it is happening. For example  take a look at the following ?  

```
Traceback (most recent call last):
  File "networks.py", line 586, in <module>
    main()
  File "networks.py", line 572, in main
    x, y, z = train_dataset_batch ()
  File "networks.py", line 505, in train_dataset_batch
    loss_f, train_op_f, summary_str = sess.run([ loss, train_op, summaries_op], feed_dict=fd)
TypeError: 'InvalidArgumentError' object is not iterable
```

 How can anyone debug this ?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by whatdhack** [comment]
OS Platform and Distribution : Ubuntu 16.04
TensorFlow installed from : source 
TensorFlow version : 1.6
Bazel version
CUDA/cuDNN version : 9.1
GPU model and memory : quadros
Exact command to reproduce :   it is a complex network, and  the exceptions happens  unpredictably.

**Comment by whatdhack** [comment]
It  has certainly  something to do with tf.summary .  Probably  histogram and image.   It will save lot of time if TF print out specific   histogram op  in the traceback.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @shivaniag: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @shivaniag: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @shivaniag: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @shivaniag: It has been 60 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @shivaniag: It has been 75 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @shivaniag: It has been 90 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @shivaniag: It has been 105 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @shivaniag: It has been 120 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @shivaniag: It has been 135 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @shivaniag: It has been 150 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by jvishnuvardhan** [comment]
@whatdhack This is a stale issue. If this is still an issue for you, can you please share a simple standalone code to reproduce the issue? If it is not an issue any more for you, then bot will close this issue automatically. Thanks!
