### ISSUE TITLE
cuDevicePrimaryCtxRetain: CUDA_ERROR_INVALID_DEVICE ... Failed to create session

### ISSUE THREAD

**Issue by MounirB** [tensorflow/tensorflow#20414]
Hello everyone, when I execute this code :

```
import tensorflow as tf
hello = tf.constant('hi,tensorflow')
sess = tf.Session()
```

I get each time the same error :

```
2018-06-29 15:14:01.587077: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-06-29 15:14:01.694678: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-06-29 15:14:01.695507: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 0 with properties: 
name: Quadro P400 major: 6 minor: 1 memoryClockRate(GHz): 1.2525
pciBusID: 0000:05:00.0
totalMemory: 1.95GiB freeMemory: 1.92GiB
2018-06-29 15:14:01.715820: E tensorflow/core/common_runtime/direct_session.cc:154] Internal: failed initializing StreamExecutor for CUDA device ordinal 1: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_INVALID_DEVICE
Traceback (most recent call last):
  File "/home/mounir/PycharmProjects/ssd_keras-master/ssd512_inference.py", line 6, in <module>
    sess = tf.Session()
  File "/home/mounir/anaconda3/envs/gpukeras/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1560, in __init__
    super(Session, self).__init__(target, graph, config=config)
  File "/home/mounir/anaconda3/envs/gpukeras/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 633, in __init__
    self._session = tf_session.TF_NewSession(self._graph._c_graph, opts)
tensorflow.python.framework.errors_impl.InternalError: Failed to create session.

```
I have two GPUs in my computer, the P400 is the most powerful one.
I tried to troubleshoot it by adding to .bashrc export CUDA_VISIBLE_DEVICES with alternatively these values =0, =1, =0,1, but it outputs always the same error

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by reedwm** [comment]
I'm not sure what you mean by "Cudatoolkit installed within the virtual env is 9.0". I do not think it's possible to install CUDA in a virtualenv. You should only have one CUDA version, and currently the TensorFlow nightlies only work with Cuda 9.0. Try replacing the system CUDA with 9.0 if possible, or use docker.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by MounirB** [comment]
I will be back on my computer on Thursday, If will tell you by then If I still encounter the issue

**Comment by MounirB** [comment]
I'll be back at my office on Thursday, I'll retry it at that moment !

**Comment by tensorflowbutler** [comment]
Nagging Assignee @zheng-xq: It has been 16 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @zheng-xq: It has been 31 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by MounirB** [comment]
Hello, I abandoned the double GPU setup. I kept only the Quadro P400, and I am intending to reinstall everything from scratch. This problem was probably, essentially, due to a bad connection between Cuda and the GPU version of Tensorflow. I think that it is suitable to close the issue as I may have understood what the source of the problem was.
