### ISSUE TITLE
TypeError('{!r} is not a Python function'.format(func))

### ISSUE THREAD

**Issue by meanmee** [tensorflow/tensorflow#2045]
When I import tensorflow, It raise an error like this(the newest version of tensorflow via pip installtaion)

`
/usr/bin/python2.7 /home/dell/wxm/Code/ImageCaption-tensorflow/test.py
Traceback (most recent call last):
  File "/home/dell/wxm/Code/ImageCaption-tensorflow/test.py", line 3, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 62, in <module>
    import tensorflow.contrib as contrib
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/__init__.py", line 26, in <module>
    from tensorflow.contrib import learn
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/__init__.py", line 20, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/__init__.py", line 20, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/__init__.py", line 22, in <module>
    from tensorflow.contrib.learn.python.learn.io import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/io/__init__.py", line 20, in <module>
    from tensorflow.contrib.learn.python.learn.io.dask_io import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/io/dask_io.py", line 23, in <module>
    import dask.dataframe as dd
  File "/usr/local/lib/python2.7/dist-packages/dask/dataframe/__init__.py", line 1, in <module>
    from .core import (DataFrame, Series, Index, _Frame, map_partitions,
  File "/usr/local/lib/python2.7/dist-packages/dask/dataframe/core.py", line 1234, in <module>
    class Index(Series):
  File "/usr/local/lib/python2.7/dist-packages/dask/dataframe/core.py", line 1266, in Index
    @derived_from(pd.Index)
  File "/usr/local/lib/python2.7/dist-packages/dask/utils.py", line 526, in wrapper
    original_args = getargspec(original_method).args
  File "/usr/local/lib/python2.7/dist-packages/dask/compatibility.py", line 190, in getargspec
    return _getargspec(func)
  File "/usr/local/lib/python2.7/dist-packages/dask/compatibility.py", line 56, in _getargspec
    return inspect.getargspec(func)
  File "/usr/lib/python2.7/inspect.py", line 816, in getargspec
    raise TypeError('{!r} is not a Python function'.format(func))
TypeError: <method 'max' of 'numpy.ndarray' objects> is not a Python function

Process finished with exit code 1
`

**Comment by liuyifly06** [comment]
I have similar problem:

```
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so locally
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 62, in <module>
    import tensorflow.contrib as contrib
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/__init__.py", line 26, in <module>
    from tensorflow.contrib import learn
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/__init__.py", line 20, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/__init__.py", line 20, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/__init__.py", line 22, in <module>
    from tensorflow.contrib.learn.python.learn.io import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/io/__init__.py", line 20, in <module>
    from tensorflow.contrib.learn.python.learn.io.dask_io import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/io/dask_io.py", line 23, in <module>
    import dask.dataframe as dd
  File "/usr/local/lib/python2.7/dist-packages/dask/dataframe/__init__.py", line 1, in <module>
    from .core import (DataFrame, Series, Index, _Frame, map_partitions,
  File "/usr/local/lib/python2.7/dist-packages/dask/dataframe/core.py", line 1233, in <module>
    class Index(Series):
  File "/usr/local/lib/python2.7/dist-packages/dask/dataframe/core.py", line 1250, in Index
    @derived_from(pd.Index)
  File "/usr/local/lib/python2.7/dist-packages/dask/utils.py", line 526, in wrapper
    original_args = getargspec(original_method).args
  File "/usr/local/lib/python2.7/dist-packages/dask/compatibility.py", line 181, in getargspec
    return _getargspec(func)
  File "/usr/local/lib/python2.7/dist-packages/dask/compatibility.py", line 55, in _getargspec
    return inspect.getargspec(func)
  File "/usr/lib/python2.7/inspect.py", line 816, in getargspec
    raise TypeError('{!r} is not a Python function'.format(func))
TypeError: <method 'max' of 'numpy.ndarray' objects> is not a Python function
```

**Comment by jessebett** [comment]
I am also trying to install tensorflow via pip and am getting this same error:


`$ python
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 62, in <module>
    import tensorflow.contrib as contrib
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/__init__.py", line 26, in <module>
    from tensorflow.contrib import learn
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/__init__.py", line 20, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/__init__.py", line 20, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/__init__.py", line 22, in <module>
    from tensorflow.contrib.learn.python.learn.io import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/io/__init__.py", line 20, in <module>
    from tensorflow.contrib.learn.python.learn.io.dask_io import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/io/dask_io.py", line 23, in <module>
    import dask.dataframe as dd
  File "/usr/local/lib/python2.7/dist-packages/dask/dataframe/__init__.py", line 1, in <module>
    from .core import (DataFrame, Series, Index, _Frame, map_partitions,
  File "/usr/local/lib/python2.7/dist-packages/dask/dataframe/core.py", line 1185, in <module>
    class Index(Series):
  File "/usr/local/lib/python2.7/dist-packages/dask/dataframe/core.py", line 1202, in Index
    @derived_from(pd.Index)
  File "/usr/local/lib/python2.7/dist-packages/dask/utils.py", line 526, in wrapper
    original_args = getargspec(original_method).args
  File "/usr/local/lib/python2.7/dist-packages/dask/compatibility.py", line 181, in getargspec
    return _getargspec(func)
  File "/usr/local/lib/python2.7/dist-packages/dask/compatibility.py", line 55, in _getargspec
    return inspect.getargspec(func)
  File "/usr/lib/python2.7/inspect.py", line 816, in getargspec
    raise TypeError('{!r} is not a Python function'.format(func))
TypeError: <method 'max' of 'numpy.ndarray' objects> is not a Python function`

**Comment by jessebett** [comment]
I've tried building previous r.08 builds, all returned the same errors.
However, r.07 builds work fine. Anyone have any fixes for this yet? (because I need some r.08 functionality)

**Comment by meanmee** [comment]
what is the r.07's whl path?

**Comment by ruilog** [comment]
I installed the #45 from build history, it is 0.7.1 version. You can download it from here-->http://ci.tensorflow.org/view/Nightly/job/nigntly-matrix-linux-gpu/TF_BUILD_CONTAINER_TYPE=GPU,TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=PIP,TF_BUILD_PYTHON_VERSION=PYTHON2,label=gpu-working/45/

**Comment by byungjo** [comment]
I have the same problem. 
- I have installed tensorflow by pip and anaconda and also installed the caffe. 
I got a problem by anaconda so I reinstalled the tensorflow 8.0 by pip 

After that, I have the same problem 
>>> import tensorflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 62, in <module>
    import tensorflow.contrib as contrib
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/__init__.py", line 26, in <module>
    from tensorflow.contrib import learn
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/__init__.py", line 20, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/__init__.py", line 20, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/__init__.py", line 22, in <module>
    from tensorflow.contrib.learn.python.learn.io import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/io/__init__.py", line 20, in <module>
    from tensorflow.contrib.learn.python.learn.io.dask_io import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/io/dask_io.py", line 23, in <module>
    import dask.dataframe as dd
  File "/usr/local/lib/python2.7/dist-packages/dask/dataframe/__init__.py", line 1, in <module>
    from .core import (DataFrame, Series, Index, _Frame, map_partitions,
  File "/usr/local/lib/python2.7/dist-packages/dask/dataframe/core.py", line 1234, in <module>
    class Index(Series):
  File "/usr/local/lib/python2.7/dist-packages/dask/dataframe/core.py", line 1266, in Index
    @derived_from(pd.Index)
  File "/usr/local/lib/python2.7/dist-packages/dask/utils.py", line 526, in wrapper
    original_args = getargspec(original_method).args
  File "/usr/local/lib/python2.7/dist-packages/dask/compatibility.py", line 190, in getargspec
    return _getargspec(func)
  File "/usr/local/lib/python2.7/dist-packages/dask/compatibility.py", line 56, in _getargspec
    return inspect.getargspec(func)
  File "/usr/lib/python2.7/inspect.py", line 816, in getargspec
    raise TypeError('{!r} is not a Python function'.format(func))
TypeError: <method 'max' of 'numpy.ndarray' objects> is not a Python function

**Comment by vrv** [comment]
ping @ilblackdragon @terrytangyuan

**Comment by terrytangyuan** [comment]
I wasn't able to reproduce the issue under either Linux or Mac. 
Try installing from a clean virtualenv. Also try removing your dask install.

**Comment by liuyifly06** [comment]
After the PIP install, when you import tensorflow, this error just appears !

`TypeError: <method 'max' of 'numpy.ndarray' objects> is not a Python function `

**Comment by terrytangyuan** [comment]
Seems like you have dask installed but this `import dask.dataframe as dd` failed. Could you try uninstalling your dask and try it again? I'll contact dask people too.

**Comment by mrocklin** [comment]
Taking a look now.  It sounds like regardless tensorflow should be robust to misbehavior in dask.  Perhaps you should keep imports to external and optional dependencies under try-except blocks.

**Comment by mrocklin** [comment]
What are the relevant versions of Pandas on the failing machines?

**Comment by mrocklin** [comment]
And what are relevant versions of numpy

**Comment by mrocklin** [comment]
I can reproduce with fairly old versions of numpy/pandas.

**Comment by terrytangyuan** [comment]
I think it should be able to avoid this easily with a new virtualenv.

**Comment by mrocklin** [comment]
Dask requirements list `pandas >= 0.16.0`.  

When using `pip` or a `requirements.txt` file is it possible that you're just installing `dask` rather than `dask[dataframe]` or `dask[complete]`?  Depending on `dask[dataframe]` should properly enforce installation of newer NumPy/Pandas libraries.

**Comment by terrytangyuan** [comment]
Per @jreback: if you are using dask you should have a relatively recent version of pandas, say >= 0.17.0 (even better is 0.18.0); certainly older versions will work, but can unexpected things. 

@meanmee @liuyifly06 @byungjo @ruilog @jessebett 
Uninstall dask if you don't intend to use it. If you need to use it, use newer versions of pandas and dask.

**Comment by terrytangyuan** [comment]
@vrv This can be closed now.

**Comment by marutiagarwal** [comment]
I have neither dask nor pandas installed on my ubuntu machine. I still see this error for tensorflow 0.8 as soon as I import tensorflow.

**Comment by mrocklin** [comment]
Looking at one of the above stack traces

> File "/usr/local/lib/python2.7/dist-packages/dask/dataframe/core.py", line 1234, in class Index(Series):
> File "/usr/local/lib/python2.7/dist-packages/dask/dataframe/core.py", line 1266, in Index @derived_from(pd.Index)
> File "/usr/local/lib/python2.7/dist-packages/dask/utils.py", line 526, in wrapper original_args = getargspec(original_method).args

We see a reference to `pandas.Index` and then we see the stack trace continue on in a way that wasn't "Error, pandas not found" so clearly, at least on the machine for which this stack trace was produced, Pandas was installed.  

If you have a different error then you should probably post more information about how it was produced and the software environment necessary to reproduce it.

**Comment by terrytangyuan** [comment]
Probably a different error traceback though. Could you post it here?

**Comment by mrocklin** [comment]
@terrytangyuan how are you directing people to install dask?  If you are using a requirements.txt file then the correct entry is probably `dask[dataframe]` rather than just dask.

**Comment by terrytangyuan** [comment]
Haven't mentioned anything about installing dask yet. Just put them in try catch. It's not required but optional.  @mrocklin

**Comment by mrocklin** [comment]
Ah, are they `pip installing dask` on their own then?  (I'm getting these error reports myself now)

**Comment by terrytangyuan** [comment]
Yep on their own. We can probably add a note there.

**Comment by tobegit3hub** [comment]
It works for me. Thanks!
