### ISSUE TITLE
Cannot use tf.metrics with MirroredStrategy

### ISSUE THREAD

**Issue by jdvylder** [tensorflow/tensorflow#20509]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: using nvidia containter: https://docs.nvidia.com/deeplearning/dgx/tensorflow-release-notes/rel_18.06.html#rel_18.06 
- **TensorFlow version (use command below)**:1.8.0
- **Python version**: 3.5
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: 9.0.176
- **GPU model and memory**: nvidia tesla v100
- **Exact command to reproduce**: N/A

### Describe the problem
I'm training a network using a custom tf.estimator. To monitor its training i used several metrics from tf. metrics: accuracy, auc, true positives, ... When running this on a single GPU, This works as expected, however when using `tf.contrib.distribute.MirroredStrategy` i get an exception. Apparently all metrics suffer from the same bug (tested by iteratively leaving the metric out).

### Source code / logs
I tried to extract the relevant part from my code:
```
def configure_trainer(self):
        if self.configuration.get("multi_gpu"):
            distribute = tf.contrib.distribute.MirroredStrategy(num_gpus=2)
        else:
            distribute = None

        run_config = tf.estimator.RunConfig(model_dir=out_dir, tf_random_seed=self.configuration.get("random_seed"),
                                                save_summary_steps=400,
                                                save_checkpoints_steps=1000,
                                                log_step_count_stepss400,
                                                train_distribute=distribute)

        self.trainer = tf.estimator.Estimator(
            model_fn=self.get_model_fn,  
            config=run_config
        )

def get_model_fn(self, mode, features, labels, params):
        self.configure_network(input_tensor=features, output_tensor=labels, mode=mode)
        eval_metrics = self.get_accuracy(self.network.get_output_tensor(),labels)
        return tf.estimator.EstimatorSpec(mode=mode, predictions=self.predictions,
                                              loss=self.loss, train_op=self.trainer_conf.get_train_op_fn(self.loss,mode),
                                              eval_metric_ops=eval_metrics
                                              )
...
def get_accuracy(self, output_tensor,  ground_truth, name=""):
        metric_name = 'Accuracy_' + name
        accuracy = tf.metrics.accuracy(
                labels=ground_truth,
                predictions=tf.argmax(output_tensor, axis=-1),
                name=metric_name)
        tf.summary.scalar(metric_name , accuracy[1])
        return {
            metric_name : accuracy
        }
```

This results in the following error trace:

```
Traceback (most recent call last):
  File "train.py", line 27, in <module>
    experimenter.run_training_experiment(config)
  File "/media/local/BDA_tf_framework/neuralnetwork/trainingexperimenter.py", line 39, in run_training_experiment
    tf.estimator.train_and_evaluate(self.trainer, self.training_specs, self.eval_specs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/training.py", line 439, in train_and_evaluate
    executor.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/training.py", line 518, in run
    self.run_local()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/training.py", line 650, in run_local
    hooks=train_hooks)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 363, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 841, in _train_model
    return self._train_model_distributed(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 977, in _train_model_distributed
    saving_listeners)
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 5265, in get_controller
    yield g
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 5060, in get_controller
    yield default
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 5265, in get_controller
    yield g
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 977, in _train_model_distributed
    saving_listeners)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/distribute.py", line 304, in __exit__
    self._var_creator_scope.__exit__(exception_type, exception_value, traceback)
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/variable_scope.py", line 2283, in variable_creator_scope
    yield
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 2939, in _variable_creator_scope
    yield
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/variable_scope.py", line 2283, in variable_creator_scope
    yield
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 884, in _train_model_distributed
    self.config)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/distribute.py", line 756, in call_for_each_tower
    return self._call_for_each_tower(fn, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/distribute/python/mirrored_strategy.py", line 254, in _call_for_each_tower
    coord.join(threads)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/usr/local/lib/python3.5/dist-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/coordinator.py", line 297, in stop_on_exception
    yield
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/distribute/python/mirrored_strategy.py", line 466, in run
    self.done = True
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/eager/context.py", line 295, in _mode
    yield
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/distribute/python/mirrored_strategy.py", line 466, in run
    self.done = True
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/eager/context.py", line 514, in device_policy
    yield
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/distribute/python/mirrored_strategy.py", line 466, in run
    self.done = True
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 5265, in get_controller
    yield g
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 5060, in get_controller
    yield default
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 5265, in get_controller
    yield g
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/distribute/python/mirrored_strategy.py", line 466, in run
    self.done = True
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 4338, in device
    yield
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/distribute/python/mirrored_strategy.py", line 466, in run
    self.done = True
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 5991, in __exit__
    self._name_scope.__exit__(type_arg, value_arg, traceback_arg)
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 4115, in name_scope
    yield "" if new_stack is None else new_stack + "/"
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/distribute/python/mirrored_strategy.py", line 466, in run
    self.done = True
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/variable_scope.py", line 2097, in __exit__
    self._graph_context_manager.__exit__(type_arg, value_arg, traceback_arg)
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 5265, in get_controller
    yield g
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 5060, in get_controller
    yield default
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 5265, in get_controller
    yield g
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/distribute/python/mirrored_strategy.py", line 466, in run
    self.done = True
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/variable_scope.py", line 2283, in variable_creator_scope
    yield
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 2939, in _variable_creator_scope
    yield
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/variable_scope.py", line 2283, in variable_creator_scope
    yield
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/distribute/python/mirrored_strategy.py", line 465, in run
    self.main_result = self.main_fn(*self.main_args, **self.main_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 831, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/media/local/BDA_tf_framework/neuralnetwork/trainingexperimenter.py", line 116, in get_model_fn
    eval_metrics = self.logger.get_eval_metrics(self.predictions, labels)
  File "/media/local/myfiles/Mytraininglogger.py", line 26, in get_eval_metrics
    metrics.update(self.get_accuracy(output_tensor, ground_truth, name=name))
  File "/media/local/BDA_tf_framework/neuralnetwork/traininglogger.py", line 60, in get_accuracy
    name=metric_name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/metrics_impl.py", line 409, in accuracy
    name or 'accuracy')
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/metrics_impl.py", line 345, in mean
    return mean_t, update_op
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/variable_scope.py", line 2095, in __exit__
    self._current_name_scope.__exit__(type_arg, value_arg, traceback_arg)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 5991, in __exit__
    self._name_scope.__exit__(type_arg, value_arg, traceback_arg)
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 4115, in name_scope
    yield "" if new_stack is None else new_stack + "/"
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/metrics_impl.py", line 332, in mean
    update_total_op = state_ops.assign_add(total, math_ops.reduce_sum(values))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/state_ops.py", line 251, in assign_add
    return ref.assign_add(value)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/distribute/python/values.py", line 311, in assign_add
    return self.get(device=_get_update_device()).assign_add(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/distribute/python/values.py", line 283, in _get_update_device
    "Use DistributionStrategy.update() to modify a MirroredVariable.")
RuntimeError: Use DistributionStrategy.update() to modify a MirroredVariable.
Exception ignored in: <generator object get_controller at 0x7f2dec1a2fc0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 5267, in get_controller
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/eager/context.py", line 136, in pop
IndexError: pop from empty list
Exception ignored in: <generator object get_controller at 0x7f2dec1f0830>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 5267, in get_controller
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/eager/context.py", line 136, in pop
IndexError: pop from empty list
Exception ignored in: <generator object get_controller at 0x7f2dec17d9e8>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 5267, in get_controller
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/eager/context.py", line 136, in pop
IndexError: pop from empty list
Makefile:19: recipe for target 'train_gpu' failed
make: *** [train_gpu] Error 1
```

**Comment by guptapriya** [comment]
@jdvylder - Metrics support in distribution strategies was added about a month ago and was not part of the tensorflow 1.8 release. It should be part of the nightly build though. Would it possible for you to try your code with tensorflow nightly build? (https://pypi.org/project/tf-nightly-gpu/)

**Comment by jdvylder** [comment]
Hi @guptapriya 
Thanks for the reply. I've tried the nightly build and the training does seem to get past the point where it originally threw the exception. Since I've run into a new [bug](https://github.com/tensorflow/tensorflow/issues/20874), I can't test if the metrics work, but will close this issue since the initial exception seems to be solved.

Thanks

Jonas

**Comment by carlthome** [comment]
This is still an issue. Can this be reopened?

```
tensorflow/python/ops/metrics_impl.py in mean(values, weights, metrics_collections, updates_collections, name)
    374       return mean_t
    375 
--> 376     mean_t = distribute_lib.get_tower_context().merge_call(
    377         aggregate_across_towers, total, count)
    378     update_op = _safe_div(update_total_op, update_count_op, 'update_op')

AttributeError: 'NoneType' object has no attribute 'merge_call'
```

**Comment by guptapriya** [comment]
@carlthome - it seems like your might be seeing this error if you're trying to update metrics in cross tower mode. Typically, we would expect metrics to be computed in tower mode, as that's where your labels and logits etc are available. Could you provide a complete stack trace + your code that triggers this so we can debug further?

**Comment by carlthome** [comment]
This seems to reproduce the error consistently. Am I doing something wrong?

```python
import tensorflow as tf


def input_fn():
    dataset = (
        tf.data.Dataset
        .range(100)
        .map(lambda x: tf.random_normal([100]))
        .batch(32)
        .map(lambda x: ({'input': x}, {'output': x}))
        .repeat()
    )
    return dataset


def model_fn(features, labels, mode, params):

    units = features['input'].shape[-1]
    predictions = tf.layers.dense(features['input'], units)
    labels = labels['output']

    loss = tf.losses.mean_squared_error(labels, predictions)
    tf.losses.add_loss(loss)
    loss = tf.losses.get_total_loss()

    if mode == tf.estimator.ModeKeys.EVAL:
        metrics = {'mse': tf.metrics.mean_squared_error(labels, predictions)}

        return tf.estimator.EstimatorSpec(
            mode,
            loss=loss,
            eval_metric_ops=metrics,
        )

    if mode == tf.estimator.ModeKeys.TRAIN:
        step = tf.train.get_or_create_global_step()
        optimizer = tf.train.AdamOptimizer()
        train_op = optimizer.minimize(loss, step)

        return tf.estimator.EstimatorSpec(
            mode,
            loss=loss,
            train_op=train_op,
        )


estimator = tf.estimator.Estimator(
    model_fn,
    config=tf.estimator.RunConfig(
        save_checkpoints_steps=100,
        train_distribute=tf.contrib.distribute.MirroredStrategy()),
)

tf.estimator.train_and_evaluate(
    estimator,
    train_spec=tf.estimator.TrainSpec(input_fn),
    eval_spec=tf.estimator.EvalSpec(input_fn),
)
```

**Comment by guptapriya** [comment]
@carlthome thanks for the code and stack trace. I think what's happening is that as part of `train_and_evaluate`, evaluate gets called in a hook (_NewCheckpointListenerForEvaluate) as part of the training call. This means that the distribution strategy scope that we open in estimator.train (https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/estimator/estimator.py#L1194)  is still open when we execute this hook.  
Due to this, the metrics that you create in evaluate are created inside the scope in a cross tower context - and this leads to the error above. 
This setup to use _NewCheckpointListenerForEvaluate is new and hence you're probably one of the first people to run into this. 

I see 2 options to move forward:
1. Can you use Estimator.train and Estimator.evaluate directly instead of train_and_evaluate? We've definitely tested those to work as expected in presence of MirroredStrategy (even though evaluate itself is not distributed). The main benefit of using train_and_evaluate (from my understanding) is to run on multiple machines with Parameter Server distribution. Since you are not looking for that, directly using train and evaluate might be better and get around this error. 
2. As I mentioned above, Estimator.evaluate itself in general is not yet distributed under MirroredStrategy so currently it would just run on the first GPU (but should not throw errors). This support is actually in progress right now and should be available in 1-2 weeks. I suspect this might address the issue while using train_and_evaluate as well but I haven't tested that (will do). 

Hope this helps!

**Comment by carlthome** [comment]
Thanks for the clarification @guptapriya!

I'm using `train_and_evaluate` because I'd like to do [early stopping](https://en.wikipedia.org/wiki/Early_stopping) (checking loss on a validation set every now and then during training, and stopping the training loop when the model stops improving on the validation data). I'm currently doing this with `tf.contrib.estimator.stop_if_no_decrease_hook`. This also crashes with the same stack trace:
```py
eval_hook = tf.contrib.estimator.InMemoryEvaluatorHook(estimator, validation_input_fn)
estimator.train(training_input_fn, hooks=[early_stopping, eval_hook])
metrics = estimator.evaluate(test_input_fn)
```

I guess this is a workaround at the moment for local training:
```py
best = float('inf')
for epoch in range(100):
    estimator.train(training_input_fn)
    metrics = estimator.evaluate(validation_input_fn)
    if metrics['loss'] < best:
        best = metrics['loss']
    else:
        tf.logging.info(f'Early stopping after {epoch} epochs.')
        break
```
but it would be nice to have asynchronous training and validation loops via some high-level construct like `train_and_evaluate` eventually! The dream would be to write high-level TensorFlow code once, and have that working in any hardware configuration (multi-machine, single-machine, multi-GPU, CPU-only, etc.).

**Comment by guptapriya** [comment]
@carlthome absolutely, i am looking into fixing this issue, and also implementing distributed eval directly, both of which should address your issue. Your workaround in the meantime looks right.

**Comment by guptapriya** [comment]
Also, please feel free to open a new issue for this with your code and stack trace. Thanks!

**Comment by carlthome** [comment]
@guptapriya done! https://github.com/tensorflow/tensorflow/issues/21180
