### ISSUE TITLE
Exception in thread "main" java.lang.UnsatisfiedLinkError: Cannot find TensorFlow native library for OS

### ISSUE THREAD

**Issue by 8502596** [tensorflow/tensorflow#20563]
Have I written custom code (as opposed to using a stock example script provided in TensorFlow)
OS Platform and Distribution (window 7 64b):
TensorFlow installed from (binary) 1.6 later:
TensorFlow version NA:
Python version NA: 
Bazel version NA:
GCC/Compiler version NA:
CUDA/cuDNN version NA:
GPU model and memory NA:
Exact command to reproduce NA:

### Describe the problem
when i  get start  with [https://www.tensorflow.org/install/install_java] I found a problem.
if the tensorflow_jni.dll version Higher than 1.5.1 then  will receive the error：

`Exception in thread "main" java.lang.UnsatisfiedLinkError: Cannot find TensorFlow native library for OS: windows, architecture: x86_64. See https://github.com/tensorflow/tensorflow/tree/master/tensorflow/java/README.md for possible solutions (such as building the library from source). Additional information on attempts to find the native library can be obtained by adding org.tensorflow.NativeLibrary.DEBUG=1 to the system properties of the JVM.
	at org.tensorflow.NativeLibrary.load(NativeLibrary.java:78)
	at org.tensorflow.TensorFlow.init(TensorFlow.java:66)
	at org.tensorflow.TensorFlow.<clinit>(TensorFlow.java:70)
	at org.tensorflow.Graph.<clinit>(Graph.java:258)
	at HelloTF.main(HelloTF.java:25)`

1. 1.3.0  
2. 1.4.1
3. 1.5.1

these versions lower than 1.6.0 is good.

1.  1.6.0
2.  1.7.0
3.  1.8.0
4.  1.9.0.rc2

these versions receive this error.

### Source code / logs
[https://www.tensorflow.org/install/install_java]   HelloTF.java

**Comment by 8502596** [comment]
I thank I find the problem.
![ll8t 2kmlixk 5wn x 1d](https://user-images.githubusercontent.com/15864647/42314072-c809550c-8076-11e8-8abe-f770926ad088.png)

![xh hs4ubyeux5 fh z2g6](https://user-images.githubusercontent.com/15864647/42314163-03dc1ea2-8077-11e8-8871-2b19c4044fda.png)
![odmjppa2zsrc n7t ay](https://user-images.githubusercontent.com/15864647/42314310-54adb82c-8077-11e8-90d8-15a5c4b20f7e.png)
My computer not  Contained  avx instructions.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @bignamehyp: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by bignamehyp** [comment]
@yifeif  can you please take a look or assign it to some one more appropriate? Thanks.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @bignamehyp: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @bignamehyp: It has been 31 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @bignamehyp: It has been 46 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @bignamehyp: It has been 61 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @bignamehyp: It has been 76 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @bignamehyp: It has been 91 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @bignamehyp: It has been 106 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @bignamehyp: It has been 121 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by sachinprasadhs** [comment]
Could you please try with the latest `Tensorflow` version(2.6 as of now).
Feel free to reopen the issue if the issue still persist.
