### ISSUE TITLE
Cannot use warm startup of an estimator with MirroredStrategy

### ISSUE THREAD

**Issue by jdvylder** [tensorflow/tensorflow#20566]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:  using nvidia containter: https://docs.nvidia.com/deeplearning/dgx/tensorflow-release-notes/rel_18.06.html#rel_18.06 
- **TensorFlow version (use command below)**: 1.8.0
- **Python version**: 3.5
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**:N/A
- **CUDA/cuDNN version**: 9.0.176
- **GPU model and memory**: nvidia tesla v100
- **Exact command to reproduce**:N/A

### Describe the problem
I'm training an network using tf.estimator where I load a set of variables from an existing checkpoint. This is done using the warm start-up option from the estimator class. While the code works when running on a single GPU, It generates an error when I use the MirroredStrategy.

### Source code / logs
The code:
```
ws = tf.estimator.WarmStartSettings(ckpt_to_initialize_from="init_checkpoint.ckpt"),
                                                vars_to_warm_start="^((?!Logits).)*$"
                                                )
self.trainer = tf.estimator.Estimator(
            model_fn=self.get_model_fn,  # First-class function
            params=None,  # HParams are passed using the config file
            config=run_config,
            warm_start_from=ws
        )
```

This generate the following trace:
```
Traceback (most recent call last):
  File "train.py", line 37, in <module>
    experimenter.run_training_experiment(config)
  File "/media/local/BDA_tf_framework/neuralnetwork/trainingexperimenter.py", line 39, in run_training_experiment
    tf.estimator.train_and_evaluate(self.trainer, self.training_specs, self.eval_specs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/training.py", line 439, in train_and_evaluate
    executor.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/training.py", line 518, in run
    self.run_local()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/training.py", line 650, in run_local
    hooks=train_hooks)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 363, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 841, in _train_model
    return self._train_model_distributed(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 977, in _train_model_distributed
    saving_listeners)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 986, in _train_with_estimator_spec
    warm_starting_util.warm_start(*self._warm_start_settings)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/warm_starting_util.py", line 342, in warm_start
    _warm_start_var(variable, ckpt_to_initialize_from, prev_var_name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/warm_starting_util.py", line 139, in _warm_start_var
    "PartitionedVariable, but is {}".format(type(var)))
TypeError: var MUST be one of the following: a Variable, list of Variable or PartitionedVariable, but is <class 'tensorflow.contrib.distribute.python.values.MirroredVariable'>
Makefile:19: recipe for target 'train_gpu' failed
make: *** [train_gpu] Error 1
```

**Comment by guptapriya** [comment]
The fix has been merged: https://github.com/tensorflow/tensorflow/commit/f1de0ddd55dcae6237ea7d21ccddcc6467a6cf8b

You should be able to test this out in a nightly build soon.
