### ISSUE TITLE
Cannot query shape of opaque params in CudnnGRU

### ISSUE THREAD

**Issue by danielwatson6** [tensorflow/tensorflow#20571]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Yes
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 1.9.0-rc0
- **Python version**: 3.6.5
- **Bazel version (if compiling from source)**: 0.14.1
- **GCC/Compiler version (if compiling from source)**: 5.4.0
- **CUDA/cuDNN version**: 9.0/7.0
- **GPU model and memory**: NVIDIA GTX 1080 Ti, 11176MiB

### Describe the problem
When trying to compute the number of parameters in `tf.contrib.cudnn_rnn.CudnnGRU`, TensorFlow will crash.

The reason to do this is to share the weights between `CudnnGRU` and `CudnnCompatibleGRUCell`. There is no documentation with examples on how to do this (see #20273 ), but there is a high-level description from the tf 1.2 docs:
```
Cudnn implementation of the GRU model. Cudnn RNN has an opaque parameter buffer that can be used for inference and training. But it is possible that the layout of the parameter buffers changes between generations. So it is highly recommended to use RNNParamsSaveable to save and restore weights and biases in a canonical format.

This is a typical use case:
  * The user creates a CudnnRNN model.
  * The user query that parameter buffer size.
  * The user creates a variable of that size that serves as the parameter buffers.
  * The user either initialize the parameter buffer, or load the canonical weights into the parameter buffer.
  * The user calls the model with the parameter buffer for inference, or training.
  * If training, the user creates a Saver object.
  * If training, the user creates a RNNParamsSaveable object from the parameter buffer for it to be later saved in the canonical format. When creating a RNNParamsSaveable object, a name could be provided, which is useful in distinguishing the names of multiple RNNParamsSaveable objects (e.g. for an encoder-decoder model).
  * Once a while, the user saves the parameter buffer into model checkpoints with Saver.save().
  * When restoring, the user creates a RNNParamsSaveable object and uses Saver.restore() to restore the paramter buffer from the canonical format to a user-defined format, as well as to restore other savable objects in the checkpoint file.
```
So the second step in this process fails.

Also to consider: [the test file has deprecated code and will fail](https://github.com/tensorflow/tensorflow/blob/r1.9/tensorflow/contrib/cudnn_rnn/python/kernel_tests/cudnn_rnn_ops_test.py), using `cuddn_gru_instance.params_size()` rather than `.count_params()`, which is no longer defined. These test cases are the only resource available for users attempting to find out how undocumented features should be used, but they're outdated.

### Source code / logs
```
import tensorflow as tf
rnn = tf.contrib.cudnn_rnn.CudnnGRU(1, 7, direction='unidirectional')
rnn.build([2,3,5])
rnn.count_params()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/danielwatson/.pyenv/versions/3.6.5/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1298, in count_params
    weight_shapes = [w.get_shape().as_list() for w in self.weights]
  File "/home/danielwatson/.pyenv/versions/3.6.5/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1298, in <listcomp>
    weight_shapes = [w.get_shape().as_list() for w in self.weights]
  File "/home/danielwatson/.pyenv/versions/3.6.5/lib/python3.6/site-packages/tensorflow/python/framework/tensor_shape.py", line 903, in as_list
    raise ValueError("as_list() is not defined on an unknown TensorShape.")
ValueError: as_list() is not defined on an unknown TensorShape.
```

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by drpngx** [comment]
@protoget could you comment on this?

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by drpngx** [comment]
@protoget Any thoughts on this?

**Comment by protoget** [comment]
tf1.2 doc on this is deprecated. We started to have more usable CudnnRNN classes since 1.6.

It probably doesn't help you achieve much by querying the size of opaque params, which is subject to change depending on cudnn version.

To share params between CudnnLSTM and CudnnCompatibleLSTM, one could export a CudnnLSTM checkpoint and import into a CudnnCompatibleLSTM graph. Check this unittest for an example how that could be done.
https://github.com/tensorflow/tensorflow/blob/r1.9/tensorflow/contrib/cudnn_rnn/python/kernel_tests/cudnn_rnn_test.py#L904

**Comment by danielwatson6** [comment]
@protoget That makes sense. There's a [related issue](https://github.com/tensorflow/tensorflow/issues/20273) I opened about putting this in documentation, rather than making users have to read source to know how to use these classes. I'll close this given your explanation.
