### ISSUE TITLE
simple_estimator_example.py does not working

### ISSUE THREAD

**Issue by Bocharick** [tensorflow/tensorflow#20588]
Hello. 
Tried to figure out with your
and try https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/distribute/python/examples/simple_estimator_example.py
but it doesn't working with that errors:

/usr/bin/python3.5 /___SOME_PATH____/simple_estimator_example.py
WARNING:tensorflow:Using temporary folder as model directory: /tmp/tmp0qhilmok
2018-07-06 17:41:20.153970: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-07-06 17:41:20.269549: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:897] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-07-06 17:41:20.269961: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1392] Found device 0 with properties: 
name: GeForce GTX 1070 major: 6 minor: 1 memoryClockRate(GHz): 1.683
pciBusID: 0000:01:00.0
totalMemory: 7.92GiB freeMemory: 7.83GiB
2018-07-06 17:41:20.269973: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1471] Adding visible gpu devices: 0
2018-07-06 17:41:20.475627: I tensorflow/core/common_runtime/gpu/gpu_device.cc:952] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-07-06 17:41:20.475650: I tensorflow/core/common_runtime/gpu/gpu_device.cc:958]      0 
2018-07-06 17:41:20.475655: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   N 
2018-07-06 17:41:20.475841: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1084] Created TensorFlow device (/device:GPU:0 with 7559 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1070, pci bus id: 0000:01:00.0, compute capability: 6.1)
2018-07-06 17:41:20.564665: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1471] Adding visible gpu devices: 0
2018-07-06 17:41:20.564699: I tensorflow/core/common_runtime/gpu/gpu_device.cc:952] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-07-06 17:41:20.564705: I tensorflow/core/common_runtime/gpu/gpu_device.cc:958]      0 
2018-07-06 17:41:20.564709: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   N 
2018-07-06 17:41:20.564810: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7559 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1070, pci bus id: 0000:01:00.0, compute capability: 6.1)
Traceback (most recent call last):
  File "/home/bocharick/HDD/UbuntuFiles/PycharmProjects/LanguageDetector/bin/estimator_tst.py", line 89, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/home/bocharick/HDD/UbuntuFiles/PycharmProjects/LanguageDetector/bin/estimator_tst.py", line 73, in main
    estimator.train(input_fn=input_fn, steps=10)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 366, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 1117, in _train_model
    return self._train_model_distributed(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 1160, in _train_model_distributed
    self.config)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/distribute.py", line 794, in call_for_each_tower
    return self._call_for_each_tower(fn, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/distribute/python/mirrored_strategy.py", line 269, in _call_for_each_tower
    coord.join(threads)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/usr/lib/python3/dist-packages/six.py", line 686, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/coordinator.py", line 297, in stop_on_exception
    yield
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/distribute/python/mirrored_strategy.py", line 263, in _call_for_each_tower
    self, *merge_args, **merge_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/optimizer.py", line 652, in _distributed_apply
    reduced_grads = distribution.batch_reduce("sum", grads_and_vars)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/distribute.py", line 840, in batch_reduce
    return self._batch_reduce(method_string, value_destination_pairs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/distribute/python/mirrored_strategy.py", line 310, in _batch_reduce
    value_destination_pairs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/distribute/python/cross_tower_ops.py", line 171, in batch_reduce
    raise ValueError("`value_destination_pairs` must be a list or a tuple of "
ValueError: `value_destination_pairs` must be a list or a tuple of tuples of PerDevice objects and destinations

Process finished with exit code 1

I tried two versions of tensorflow:
1) 1.10.nigthly
2) 1.9.rc2
Python 3.5

Same problems both TF versions.
Thank you. Help me, plz

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by Bocharick** [comment]
**0) Have I written custom code:**
Yes. For test on my single GeForce GTX 1070 machine I changed one code line:
BEFORE:

> distribution = tf.contrib.distribute.MirroredStrategy(["/device:GPU:0", "/device:GPU:1"])

AFTER:

> distribution = tf.contrib.distribute.MirroredStrategy(["/device:GPU:0"])

**1) OS Platform and Distribution:**
-Linux UbuntuPC 4.4.0-130-generic #156-Ubuntu SMP Thu Jun 14 08:53:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
**2) TensorFlow installed from:**
sudo pip3.5 install ***
**3) TensorFlow version:**
Checked on two versions of tf:
     a) 1.10.nightly
     tf_nightly_gpu-1.10.0.dev20180620-cp35-cp35m-manylinux1_x86_64.whl
     b) 1.9.rc2
     tensorflow_gpu-1.9.0rc2-cp35-cp35m-manylinux1_x86_64.whl
**4) Bazel version:**
> Extracting Bazel installation...
> Build label: 0.13.1
> Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
> Build time: Wed May 23 11:17:23 2018 (1527074243)
> Build timestamp: 1527074243
> Build timestamp as int: 1527074243
**5) CUDA/cuDNN version**
CUDA - 9.0.176.2
cuDNN - 7.1.2
**6) GPU model and memory:**
Nvidia GeForce GTX 1070 8Gb
**7) Exact command to reproduce:**

**Comment by Bocharick** [comment]
I've made some tests on my multi gpu machine. and found some strange (for me) behavior.
1) If i set 

> distribution = tf.contrib.distribute.MirroredStrategy(["/device:GPU:0"])

OR

> distribution = tf.contrib.distribute.MirroredStrategy(num_gpus=1)

It has an error, which I had earlier.

2) If i set this parameter as >=2 it works fine. **BUT!** It works on my single-gpu machine with this parameter, but it lost half of data. If I set num_gpus=4, i lost 3/4 of my data on my single-gpu machine.
I've tested it on 4-gpu machine, set this parameter as 40. So it work, but 36/40 of data was never saw by model.
I hope this is unexpected behavior.
And why it's not working with num_gpus==1 (It's both not working on single-gpu machine and on multi-gpu machine)?

**Comment by tensorflowbutler** [comment]
Nagging Assignee @guptapriya: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @yuefengz: It has been 20 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by guptapriya** [comment]
I believe @yuefengz already fixed the error in this commit : https://github.com/tensorflow/tensorflow/commit/0cb022678a143bd2b41f83fff89a4d2f6d54fd3e#diff-0cdfc5bf8ae2d22bee6308579f191fd0

Please re-open if you still see the issue
