### ISSUE TITLE
Cmake build with GPU fails on Windows 7

### ISSUE THREAD

**Issue by Ducanhvu** [tensorflow/tensorflow#20598]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 7 64-Bit
- **TensorFlow installed from (source or binary)**: Source
- **TensorFlow version (use command below)**: commit id: b2fe2a874bade4782aaca5c44bf29e7ff6c39200
- **Python version**: 3.55
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: 3.6.3
- **CUDA/cuDNN version**: CUDA 9.0 cuDNN 7.1
- **GPU model and memory**: NVIDIA NVS 510 2GB
- **Exact command to reproduce**:
First:
cmake .. -A x64 -DCMAKE_BUILD_TYPE=Release -DSWIG_EXECUTABLE=C:/tools/swigwin-3.0.10/swig.exe -DPYTHON_EXECUTABLE=C:/Users/{username}/Anaconda3/envs/py35/python.exe -DPYTHON_LIBRARIES=C:/Users/{username}/Anaconda3/envs/py35/libs/python35.lib -DPYTHON_INCLUDE_DIRS=C:/Users/{username}/Anaconda3/envs/py35/include -Dtensorflow_ENABLE_GPU=ON -DCUDNN_HOME="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0" -Dtensorflow_WIN_CPU_SIMD_OPTIONS=/arch:AVX

Then
MSBuild /p:Configuration=Release /filelogger tf_python_build_pip_package.vcxproj

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.

This is what is at the end of the log:
"C:\Users\{username}\tensorflow\tensorflow\contrib\cmake\build\tf_python_build_pip_package.vcxproj" (default target) (1) ->
"C:\Users\{username}\tensorflow\tensorflow\contrib\cmake\build\estimator_python_api.vcxproj" (default target) (2) ->
(CustomBuild target) -> 
  C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1. [C:\Users\{username}\tensorflow\tensorflow\contrib\cmake\build\estimator_python_api.vcxproj]

"C:\Users\{username}\tensorflow\tensorflow\contrib\cmake\build\tf_python_build_pip_package.vcxproj" (default target) (1) ->
"C:\Users\{username}\tensorflow\tensorflow\contrib\cmake\build\tf_python_api.vcxproj" (default target) (264) ->
  C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1. [C:\Users\{username}\tensorflow\tensorflow\contrib\cmake\build\tf_python_api.vcxproj]

    27022 Warning(s)
    2 Error(s)

I searched in the log for the keyword "Error:" and came across this passage:

  Traceback (most recent call last):
    File "C:/Users/{username}/tensorflow/tensorflow/contrib/cmake/build/tf_python/tensorflow/tools/api/generator/create_python_api.py", line 27, in <module>
      from tensorflow.python.util import tf_decorator
    File "C:\Users\{username}\tensorflow\tensorflow\contrib\cmake\build\tf_python\tensorflow\python\__init__.py", line 52, in <module>
      from tensorflow.core.framework.graph_pb2 import *
    File "C:\Users\{username}\tensorflow\tensorflow\contrib\cmake\build\tf_python\tensorflow\core\framework\graph_pb2.py", line 6, in <module>
      from google.protobuf import descriptor as _descriptor
  ImportError: No module named 'google'

Time Elapsed 18:43:53.58
### Source code / logs
[msbuild - Copy.zip](https://github.com/tensorflow/tensorflow/files/2171451/msbuild.-.Copy.zip)

Thank you in advance :)

**Comment by cy89** [comment]
@Ducanhvu do the "common installation problems" at the bottom of https://www.tensorflow.org/install/install_windows

shed any light? In particular, this StackOverflow link [https://stackoverflow.com/questions/42006320/tensorflow-pip-installation-issue-cannot-import-name-descriptor] has some suggestions around import problems.

**Comment by Ducanhvu** [comment]
@cy89 Thank you for your response. Unfortunately, that has not changed anything and I'm getting the same error.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @cy89: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.
