### ISSUE TITLE
Error in Compiling the CPU Module for Python

### ISSUE THREAD

**Issue by fifothekid** [tensorflow/tensorflow#20669]
System information
- Have I written custom code: No
- OS Platform and Distribution: Windows 10 64bit
- TensorFlow installed from: Latest master source
- TensorFlow version: commit dfcec822728c6569914db37eb55a78a019866e6f
- Python version: 3.6.5 
- CMake version: 3.12.0-rc2
- MS C+_+ Compiler version: 19.00.24234.1
- CPU model and memory: i5-4460 with 16GB of RAM
- Exact command to reproduce:

1- Opening Developer Command Line as admin
2- Choosing the 64bit compiler
"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\Tools\vsdevcmd\ext\vcvars.bat" amd64
3- cd D:\opencv\tensorflow\tensorflow\contrib\cmake\build\
4- 
cmake .. -A x64 -T host=x64 -DCMAKE_BUILD_TYPE=Release -DSWIG_EXECUTABLE=D:/opencv/swigwin-3.0.12/swig.exe -DPYTHON_EXECUTABLE="C:/Users/FiFo/AppData/Local/Programs/Python/Python36/python.exe" -DPYTHON_LIBRARIES="C:/Users/FiFo/AppData/Local/Programs/Python/Python36/libs/python36.lib" -Dtensorflow_WIN_CPU_SIMD_OPTIONS=/arch:AVX2 -Dtensorflow_BUILD_CC_TESTS=OFF -Dtensorflow_BUILD_PYTHON_TESTS=OFF -Dtensorflow_BUILD_MORE_PYTHON_TESTS=OFF -Dtensorflow_BUILD_CC_EXAMPLE=ON -Dtensorflow_BUILD_PYTHON_BINDINGS=ON -Dtensorflow_BUILD_CC_TESTS=OFF -Dtensorflow_OPTIMIZE_FOR_NATIVE_ARCH=ON -Dtensorflow_ENABLE_MKL_SUPPORT=ON -Dtensorflow_ENABLE_MKLDNN_SUPPORT=ON -Dtensorflow_VERBOSE=ON -Dtensorflow_BUILD_SHARED_LIB=ON
5- MSBuild /p:Configuration=Release ALL_BUILD.vcxproj
SUCCESS
6- MSBuild  /p:Configuration=Release INSTALL.vcxproj
SUCCESS
7- MSBuild /p:Configuration=Release tf_python_build_pip_package.vcxproj
Fails with:

  Generating __init__.py files for Python API.
  Traceback (most recent call last):
    File "D:\opencv\tensorflow\tensorflow\contrib\cmake\build\tf_python\tensorflow\python\pywrap_tensorflow_internal.py", line 14, in swig_import_helper
      return importlib.import_module(mname)
    File "C:\Users\FiFo\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 994, in _gcd_import
    File "<frozen importlib._bootstrap>", line 971, in _find_and_load
    File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
    File "<frozen importlib._bootstrap>", line 571, in module_from_spec
    File "<frozen importlib._bootstrap_external>", line 922, in create_module
    File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  ImportError: DLL load failed: NÒo foi possÝvel encontrar o m¾dulo especificado.

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "D:\opencv\tensorflow\tensorflow\contrib\cmake\build\tf_python\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
      from tensorflow.python.pywrap_tensorflow_internal import *
    File "D:\opencv\tensorflow\tensorflow\contrib\cmake\build\tf_python\tensorflow\python\pywrap_tensorflow_internal.py", line 17, in <module>
      _pywrap_tensorflow_internal = swig_import_helper()
    File "D:\opencv\tensorflow\tensorflow\contrib\cmake\build\tf_python\tensorflow\python\pywrap_tensorflow_internal.py", line 16, in swig_import_helper
      return importlib.import_module('_pywrap_tensorflow_internal')
    File "C:\Users\FiFo\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
  ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'

Failed to load the native TensorFlow runtime.

It used to work before with version 1.8
I don't want to install the PIP version
Compilation works without any problem on Ubuntu 16.04

**Comment by fifothekid** [comment]
In the tf_python_build_pip_package.vcxproj I found the following command:
C:\Program Files\CMake\bin\cmake.exe" -E copy D:/opencv/tensorflow/tensorflow/tools/pip_package/setup.py D:/opencv/tensorflow/tensorflow/contrib/cmake/build/tf_python/

But it doesn't look like the file was copied
So I copied it manually and did:
python setup.py bdist_wheel

Which generated a wheel that I installed with pip install sucessfully
But then when I try to import tensorflow it gives me the same error message

Any ideas?

**Comment by mrry** [comment]
Can you share the full log from running `MSBuild /p:Configuration=Release tf_python_build_pip_package.vcxproj`?

**Comment by fifothekid** [comment]
Here you go
[log1.txt](https://github.com/tensorflow/tensorflow/files/2196102/log1.txt)

**Comment by mrry** [comment]
From the log, it appears that something is failing during the build of `estimator_python_api.vcxproj`. Assigning to @case540, since he added that project in 501cf726cbee2ee13efef43884a6552ca211979d, and I'm not familiar with its mechanics. Mike: from this traceback, it looks like the API code generator is attempting to `from tensorflow.python import pywrap_tensorflow` *before* `pywrap_tensorflow.pyd` has been build:

```
  Traceback (most recent call last):
    File "D:/opencv/tensorflow/tensorflow/contrib/cmake/build/tf_python/tensorflow/python/tools/api/generator/create_python_api.py", line 27, in <module>
      from tensorflow.python.tools.api.generator import doc_srcs
    File "D:\opencv\tensorflow\tensorflow\contrib\cmake\build\tf_python\tensorflow\__init__.py", line 24, in <module>
      from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
    File "D:\opencv\tensorflow\tensorflow\contrib\cmake\build\tf_python\tensorflow\python\__init__.py", line 49, in <module>
      from tensorflow.python import pywrap_tensorflow
    File "D:\opencv\tensorflow\tensorflow\contrib\cmake\build\tf_python\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
      raise ImportError(msg)
  ImportError: Traceback (most recent call last):
    File "D:\opencv\tensorflow\tensorflow\contrib\cmake\build\tf_python\tensorflow\python\pywrap_tensorflow_internal.py", line 14, in swig_import_helper
      return importlib.import_module(mname)
    File "C:\Users\FiFo\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 994, in _gcd_import
    File "<frozen importlib._bootstrap>", line 971, in _find_and_load
    File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
    File "<frozen importlib._bootstrap>", line 571, in module_from_spec
    File "<frozen importlib._bootstrap_external>", line 922, in create_module
    File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  ImportError: DLL load failed: NÒo foi possÝvel encontrar o m¾dulo especificado.
```

I'm not sure how this is working in other builds, but perhaps we need a build dependency to ensure that the C++ extension is built first?

**Comment by fifothekid** [comment]
[tensorflow.zip](https://github.com/tensorflow/tensorflow/files/2196581/tensorflow.zip)
here is the full log if anybody is interested

**Comment by LoSealL** [comment]
@fifothekid @mrry 
I noticed that you built tensorflow with **MKL**, there is a known issue that comes with the previously installed tensorflow package in the system.

In detail, if your system has an installed tensorflow package, the cmake script will firstly import system module, rather than your compiled one. This will cause version mismatch and some import error occurs.

There is also another issue while importing `google.protobuf`, and I'm working it out. I suggest you at first uninstall any tensorflow packages (`tensorflow-gpu`, `protobuf`, `grpcio`) and build from scratch.

**P.S** For now, it will failed at importing google.protobuf, to work around, you must install and only install `protobuf` in the system.

**Comment by fifothekid** [comment]
I'm building with CPU not with GPU
I don't have an installed tensorflow package, and I've just unisntalled grpcio
I'll try building again

**Comment by LoSealL** [comment]
Hi @fifothekid 
I recognized, the problem may lie in the generating of `estimator_python_api`, you can first try to only build `tf_python_api`.
If you are urgent with this, please refer to my [PR](https://github.com/tensorflow/tensorflow/pull/20951 )

**Comment by fifothekid** [comment]
Tried the latest version merged with the PR above, and had the following error:

CustomBuild:
  Generating __init__.py files for Python API.
  Traceback (most recent call last):
    File "D:/opencv/tensorflow/tensorflow/contrib/cmake/build/tf_python/tensorflow/python/tools/api/generator/create_python_api.py", line 27, in <module>
      from tensorflow.python.tools.api.generator import doc_srcs
    File "D:\opencv\tensorflow\tensorflow\contrib\cmake\build\tf_python\tensorflow\__init__.py", line 31, in <module>
      app.flags = flags  # pylint: disable=undefined-variable
  NameError: name 'app' is not defined
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" foi enc
errado com o código 1. [D:\opencv\tensorflow\tensorflow\contrib\cmake\build\estimator_python_api.vcxproj]

**Comment by LoSealL** [comment]
@fifothekid Have you install absl-py? That’s a required module and must be installed at the beginning.

**Comment by fifothekid** [comment]
Requirement already satisfied: absl-py in c:\users\fifo\appdata\local\programs\python\python36\lib\site-packages (0.2.2)
Requirement already satisfied: six in c:\users\fifo\appdata\local\programs\python\python36\lib\site-packages (from absl-py) (1.11.0)

**Comment by LoSealL** [comment]
@fifothekid I'm not able to reproduce your error, specifically your error message:
```
File "D:\opencv\tensorflow\tensorflow\contrib\cmake\build\tf_python\tensorflow_init_.py", line 31, in 
app.flags = flags # pylint: disable=undefined-variable
NameError: name 'app' is not defined
```
Is `tensorflow_init__.py` actually `tensorflow\__init__.py`? If so, the line 31 of mine isn't `app.flags = flags`, which is in line 604 for me, and I also have the declaration of `app` (`from tensorflow import app`) 

As suggestion, could you build `tf_tutorials_example_trainer` and run it (of course you may need to copy mklml.dll and mkldnn.dll to **Release directory**)

**Comment by fifothekid** [comment]
Are you using the latest Master with the PR?
I'll just clean-up everything and build and run tf_tutorials_example_trainer

**Comment by LoSealL** [comment]
Yeah, I committed PR using the latest branch several days ago, though it's not the very **LATEST**, but there seems no new commits for CMAKE and related python scripts recently.

**Comment by zhangcong2009** [comment]
@fifothekid I have the same error. 

> File "D:\opencv\tensorflow\tensorflow\contrib\cmake\build\tf_python\tensorflow_init_.py", line 31, in 
app.flags = flags # pylint: disable=undefined-variable
NameError: name 'app' is not defined

 am building tensorflow1.8 on Win7 with cuda9.0 and cudnn6.0. Have you found a solution?

**Comment by LoSealL** [comment]
@fifothekid Is this build with or without MKL & MKLDNN?

Please try to build `tf_python_api` and then `estimator_python_api`, if anything failed, could you paste the failure information?
(With cmake options unchanged)

**Comment by fifothekid** [comment]
> @fifothekid Is this build with or without MKL & MKLDNN?
Yes I did. I used this CMake command:

`cmake .. -A x64 -T host=x64 -DCMAKE_BUILD_TYPE=Release -DSWIG_EXECUTABLE=D:/opencv/swigwin-3.0.12/swig.exe -DPYTHON_EXECUTABLE="C:/Users/FiFo/AppData/Local/Programs/Python/Python36/python.exe" -DPYTHON_LIBRARIES="C:/Users/FiFo/AppData/Local/Programs/Python/Python36/libs/python36.lib" -Dtensorflow_WIN_CPU_SIMD_OPTIONS=/arch:AVX2 -Dtensorflow_BUILD_CC_TESTS=OFF -Dtensorflow_BUILD_PYTHON_TESTS=OFF -Dtensorflow_BUILD_MORE_PYTHON_TESTS=OFF -Dtensorflow_BUILD_CC_EXAMPLE=ON -Dtensorflow_BUILD_PYTHON_BINDINGS=ON -Dtensorflow_BUILD_CC_TESTS=OFF -Dtensorflow_OPTIMIZE_FOR_NATIVE_ARCH=ON -Dtensorflow_ENABLE_MKL_SUPPORT=ON -Dtensorflow_ENABLE_MKLDNN_SUPPORT=ON -Dtensorflow_BUILD_SHARED_LIB=OFF`

I'll try building again today
Rebuilding on Windows takes soooooooooo much time
It seems like on Linux with Bazel only the addition files are built, not everything!
I mean, for building the Python project I assume about 10% more files need to be built, still the building process takes 90+ minutes, and it seems like it almost rebuilds everything

**Comment by fifothekid** [comment]
Built tf_python_api in 43 minutes with no errors
Now building estimator_python_api

**Comment by fifothekid** [comment]
after 41 minutes I had this error

CustomBuild:
  Generating __init__.py files for Python API.
  Traceback (most recent call last):
    File "D:/opencv/tensorflow/tensorflow/contrib/cmake/build/tf_python/tensorflow/python/tools/api/gene
  rator/create_python_api.py", line 27, in <module>
      from tensorflow.python.tools.api.generator import doc_srcs
    File "D:\opencv\tensorflow\tensorflow\contrib\cmake\build\tf_python\tensorflow\__init__.py", line 31
  , in <module>
      app.flags = flags  # pylint: disable=undefined-variable
  NameError: name 'app' is not defined
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppCom
mon.targets(171,5): error MSB6006: "cmd.exe" foi encerrado com o código 1. [D:\opencv\tensorflow\tensorf
low\contrib\cmake\build\estimator_python_api.vcxproj]

**Comment by LoSealL** [comment]
Hi @fifothekid @zhangcong2009 
I tried a new build on the very latest master branch, **without** my PR, I manually copied `mklml.dll` and `mkldnn.dll` and `libiomp5md.dll` into `build\tf_python\tensorflow\python` (mkdir if the directory doesn't exist), with an absolutely new python environment, and the build of `tf_python_build_pip_package` succeeded.

You can try this "last" method, good luck.

**Comment by fifothekid** [comment]
copied the DLL's to the directory and ended with the same compilation error...
which version of Python are you using?
I think that I'll uninstall completely my Python 3.6.5 and reinstall it without any additional packages

**Comment by LoSealL** [comment]
@fifothekid 3.6.5, the same as yours.
That's very strange and unusual, and I never could reproduce your error. Could you provide me your full log? And could you list your package by `pip list`?

**Comment by fifothekid** [comment]
I'll be sending the full log later today

pip list
Package          Version
---------------- ---------
absl-py          0.2.2
asn1crypto       0.24.0
astor            0.7.1
awscli           1.15.63
bcrypt           3.1.4
bleach           2.1.3
boto             2.49.0
botocore         1.10.62
cached-property  1.4.3
certifi          2018.4.16
cffi             1.11.5
chardet          3.0.4
colorama         0.3.9
cryptography     2.3
docker           3.4.1
docker-compose   1.22.0
docker-pycreds   0.3.0
dockerpty        0.4.1
docopt           0.6.2
docutils         0.14
fabric           2.2.1
gast             0.2.0
html5lib         1.0.1
httpie           0.9.9
idna             2.7
invoke           1.1.0
jmespath         0.9.3
jsonschema       2.6.0
Markdown         2.6.11
numpy            1.14.5
paramiko         2.4.1
pip              18.0
prettytable      0.7.2
protobuf         3.6.0
pyasn1           0.4.3
pycparser        2.18
Pygments         2.2.0
PyNaCl           1.2.1
pypiwin32        223
PyQt4            4.11.4
PyQt5            5.11.2
PyQt5-sip        4.19.12
python-dateutil  2.7.3
pywin32          223
PyYAML           3.13
requests         2.19.1
rsa              3.4.2
s3transfer       0.1.13
setuptools       40.0.0
sip              4.19.8
six              1.11.0
tensorboard      1.9.0
termcolor        1.1.0
texttable        1.4.0
urllib3          1.23
virtualenv       16.0.0
webencodings     0.5.1
websocket-client 0.48.0
Werkzeug         0.14.1
wheel            0.31.1

**Comment by annarev** [comment]
@fifothekid can you try deleting D:\opencv\tensorflow\tensorflow\contrib\cmake\build\tf_python\tensorflow\__init__.py and rerunning?

Our cmake build is actually supposed to remove this file before running create_python_api:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/cmake/tf_python.cmake#L802
I wonder why that didn't work in this case.

**Comment by fifothekid** [comment]
the problem is the rebuilding on Windows takes at least 45 minutes to reach the same point where I had an error last time! this is not the case with Bazel on Linux
that's why I usually let it do the compilation overnight since I use the computer every single hour of the day

**Comment by tensorflowbutler** [comment]
Nagging Assignee @case540: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by fifothekid** [comment]
I can build now with bazel and CMake support will be ended soon
You can close this issue
