### ISSUE TITLE
ImportError: cannot import name bessel_i0

### ISSUE THREAD

**Issue by yxyuni** [tensorflow/tensorflow#20664]
Hi, I cannot figure out what happened. Anyone help?
>>> import tensorflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yinxiaoyi/Software/anaconda2/lib/python2.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *  # pylint: disable=redefined-builtin
  File "/home/yinxiaoyi/Software/anaconda2/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 47, in <module>
    import numpy as np
  File "/home/yinxiaoyi/Software/anaconda2/lib/python2.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/home/yinxiaoyi/Software/anaconda2/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/home/yinxiaoyi/Software/anaconda2/lib/python2.7/site-packages/numpy/lib/__init__.py", line 3, in <module>
    import math
  File "math/__init__.py", line 11, in <module>
    from tensorflow.python import bessel_i0
ImportError: cannot import name bessel_i0

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by Heermosi** [comment]
Well, your user name exposed...
As well as someone's true name?
:-)

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
It has been 29 days with no activity and the `awaiting response` label was assigned. Is this still an issue?
