### ISSUE TITLE
KeyError: "Couldn't find message protos.FasterRcnnBoxCoder"

### ISSUE THREAD

**Issue by azacha** [tensorflow/tensorflow#20670]
### System information
-  **Using ssd_mobilenet_pets_config and edit serval codes to solve the import errors**
- **Windows 10**:
- **installation via pip**:
- **Tensorflow 1.8**:
- **Python  3.6.0**: 
- **CUDA 9.0, cudnn 9.0*:
- **Geforce GTX 1050Ti 4GB VRAM**:
- **Exact command to reproduce:** python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/ssd_mobilenet_v1_pets.config running via cmd.exe from folder object_detection:

### Describe the problem
First of all I face import issues with for examples "from object_detection.core import box_coder", which was solved by "from core import box_coder".

    `Traceback (most recent call last):
     File "train.py", line 52, in <module>
     from builders import model_builder
    File "C:\Users\azach\Desktop\python\tensorflow\models0- 
    master\research\object_detection\builders\model_builder.py", line 18, in <module>
    from builders import box_coder_builder
    File "C:\Users\azach\Desktop\python\tensorflow\models- 
    master\research\object_detection\builders\box_coder_builder.py", line 21, in <module>
    from protos import box_coder_pb2
    File "C:\Users\azach\Desktop\python\tensorflow\models- 
    master\research\object_detection\protos\box_coder_pb2.py", line 16, in <module>
    from protos import faster_rcnn_box_coder_pb2 as protos_dot_faster__rcnn__box__coder__pb2
    File "C:\Users\azach\Desktop\python\tensorflow\models- 
    master\research\object_detection\protos\faster_rcnn_box_coder_pb2.py", line 76, in <module>
    serialized_end=191,
    File "C:\Users\azach\Anaconda3\lib\site-packages\google\protobuf\descriptor.py", line 288, in __ 
    new__
    return _message.default_pool.FindMessageTypeByName(full_name)
    KeyError: "Couldn't find message protos.FasterRcnnBoxCoder"`

### Source code / logs

    `# Generated by the protocol buffer compiler.  DO NOT EDIT!
     # source: object_detection/protos/faster_rcnn_box_coder.proto
      import sys
    _b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
     from google.protobuf import descriptor as _descriptor
     from google.protobuf import message as _message
     from google.protobuf import reflection as _reflection
     from google.protobuf import symbol_database as _symbol_database
     from google.protobuf import descriptor_pb2
     # @@protoc_insertion_point(imports)

    _sym_db = _symbol_database.Default()
    DESCRIPTOR = _descriptor.FileDescriptor(
    name='protos/faster_rcnn_box_coder.proto',
    package='protos',
    syntax='proto2', 
    #next part is shortend for increased readability  
serialized_pb=_b('\n3object_detection/protos/faster_rcnn_box_coder.proto\x12\x17object_detection.protos\"o\n\x12\x46\x61sterRcnnBoxCoder....')
)

    _FASTERRCNNBOXCODER = _descriptor.Descriptor(
     name='FasterRcnnBoxCoder',
     full_name='protos.FasterRcnnBoxCoder',
     filename=None,
     file=DESCRIPTOR,
     containing_type=None,
     fields=[
    _descriptor.FieldDescriptor(
      name='y_scale', full_name='object_detection.protos.FasterRcnnBoxCoder.y_scale', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(10),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='x_scale', full_name='object_detection.protos.FasterRcnnBoxCoder.x_scale', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(10),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='height_scale', full_name='object_detection.protos.FasterRcnnBoxCoder.height_scale', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(5),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='width_scale', full_name='object_detection.protos.FasterRcnnBoxCoder.width_scale', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(5),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
      ],
     extensions=[
     ],
     nested_types=[],
     enum_types=[
     ],
     options=None,
     is_extendable=False,
     syntax='proto2',
     extension_ranges=[],
     oneofs=[
     ],
     serialized_start=80,
     serialized_end=191,
    )

    DESCRIPTOR.message_types_by_name['FasterRcnnBoxCoder'] = _FASTERRCNNBOXCODER
    _sym_db.RegisterFileDescriptor(DESCRIPTOR)

     FasterRcnnBoxCoder = _reflection.GeneratedProtocolMessageType('FasterRcnnBoxCoder', 
     (_message.Message,), dict(
     DESCRIPTOR = _FASTERRCNNBOXCODER,
      __module__ = 'protos.faster_rcnn_box_coder_pb2'
      # @@protoc_insertion_point(class_scope:object_detection.protos.FasterRcnnBoxCoder)
      ))
     _sym_db.RegisterMessage(FasterRcnnBoxCoder)
 

     # @@protoc_insertion_point(module_scope)`

This is the script which causes the error.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory

**Comment by tensorflowbutler** [comment]
It has been 15 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by cy89** [comment]
@azacha I'm sorry, I don't understand the situation. Did you write your own code? Or is the not-found error happening with an unmodified build? It sounds like you changed an import to make progress, but is there now some other problem?

**Comment by tensorflowbutler** [comment]
It has been 17 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
It has been 34 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
We are closing this issue for now due to lack of activity. Please comment if this is still an issue for you. Thanks!
