### ISSUE TITLE
Trying to open a non-existing file in tf.data.Dataset on Windows crashes Python instance

### ISSUE THREAD

**Issue by PiotrDabrowskey** [tensorflow/tensorflow#20689]
## System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 7 Enterprise
- **TensorFlow installed from (source or binary)**: binary (compiled by conda-forge)
- **TensorFlow version (use command below)**: v1.8.0-0-g93bc2e2072, 1.8.0
- **Python version**: Python 3.6.5
- **Bazel version (if compiling from source)**: n/a
- **GCC/Compiler version (if compiling from source)**: n/a
- **CUDA/cuDNN version**: none (CPU only)
- **GPU model and memory**: none (CPU only)
- **Exact command to reproduce**:
```python
import tensorflow as tf

sess = tf.Session()

filenames = [r'C:\nonexistent.tfrecords']
dataset = tf.data.TFRecordDataset(filenames)
iterator = dataset.make_one_shot_iterator()
next_element = iterator.get_next()

print(sess.run(next_element))
```

### Describe the problem
Trying to open a non-existing tfrecords dataset using `tf.data.Dataset` on Windows crashes Python instance. On Linux the same code properly raises a `NotFoundError`.

### Source code / logs
Error on Windows:
![image](https://user-images.githubusercontent.com/9080823/42564829-1d66b532-8502-11e8-9fd9-a9a235ad6523.png)
Error details (in Polish):
```
Podpis problemu:
  Nazwa zdarzenia problemu:	APPCRASH
  Nazwa aplikacji:	python.exe
  Wersja aplikacji:	3.6.5150.1013
  Sygnatura czasowa aplikacji:	5ac79d8c
  Nazwa modułu z błędem:	_pywrap_tensorflow_internal.pyd
  Wersja modułu z błędem:	0.0.0.0
  Sygnatura czasowa modułu z błędem:	5ae380ee
  Kod wyjątku:	c0000005
  Przesunięcie wyjątku:	0000000000236acf
  Wersja systemu operacyjnego:	6.1.7601.2.1.0.256.4
  Identyfikator ustawień regionalnych:	1045
  Dodatkowe informacje 1:	2583
  Dodatkowe informacje 2:	258324ee3ae15385fdd62136546133f9
  Dodatkowe informacje 3:	1bc4
  Dodatkowe informacje 4:	1bc4034f8418cb6d1dc9351873ca4aa5
```
Result:
```
Process finished with exit code -1073741819 (0xC0000005)
```

Proper error on Linux (part of, full stacktrace removed):
```
NotFoundError (see above for traceback): C:\nonexistent.tfrecords; No such file or directory
         [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[]], output_types=[DT_STRING], _device="/job:localhost/replica:0/task:0/device:CPU:0"](OneShotIterator)]]
```

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatatodd: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatatodd: It has been 30 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatatodd: It has been 50 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatatodd: It has been 66 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatatodd: It has been 80 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatatodd: It has been 96 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatatodd: It has been 111 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatatodd: It has been 127 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatatodd: It has been 142 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by jvishnuvardhan** [comment]
@PiotrDabrowskey I ran your code on Windows with `TF1.15.5`. Code is throwing the following `NotFoundError` error trace as expected. It is not crashing with `TF1.15.5`. 

Please verify once and close the issue if this was resolved for you. Thanks!


```
1.15.5
WARNING:tensorflow:From C:\Users\Vishnu\Desktop\Testing_TF\GH20689.py:5: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

WARNING:tensorflow:From C:\Users\Vishnu\Desktop\Testing_TF\GH20689.py:9: DatasetV1.make_one_shot_iterator (from tensorflow.python.data.ops.dataset_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `for ... in dataset:` to iterate over a dataset. If using `tf.estimator`, return the `Dataset` object directly from your input function. As a last resort, you can use `tf.compat.v1.data.make_one_shot_iterator(dataset)`.
Traceback (most recent call last):
  File "C:\Users\Vishnu\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\client\session.py", line 1365, in _do_call
    return fn(*args)
  File "C:\Users\Vishnu\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\client\session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "C:\Users\Vishnu\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\client\session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open: C:\nonexistent.tfrecords : The system cannot find the file specified.

; No such file or directory
	 [[{{node IteratorGetNext}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Vishnu\Desktop\Testing_TF\GH20689.py", line 12, in <module>
    print(sess.run(next_element))
  File "C:\Users\Vishnu\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\client\session.py", line 956, in run
    run_metadata_ptr)
  File "C:\Users\Vishnu\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\client\session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\Vishnu\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\client\session.py", line 1359, in _do_run
    run_metadata)
  File "C:\Users\Vishnu\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\client\session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open: C:\nonexistent.tfrecords : The system cannot find the file specified.

; No such file or directory
	 [[node IteratorGetNext (defined at C:\Users\Vishnu\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\framework\ops.py:1748) ]]

Original stack trace for 'IteratorGetNext':
  File "<string>", line 1, in <module>
  File "C:\Users\Vishnu\AppData\Local\Programs\Python\Python37\Lib\idlelib\run.py", line 155, in main
    ret = method(*args, **kwargs)
  File "C:\Users\Vishnu\AppData\Local\Programs\Python\Python37\Lib\idlelib\run.py", line 548, in runcode
    exec(code, self.locals)
  File "C:\Users\Vishnu\Desktop\Testing_TF\GH20689.py", line 10, in <module>
    next_element = iterator.get_next()
  File "C:\Users\Vishnu\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\data\ops\iterator_ops.py", line 426, in get_next
    name=name)
  File "C:\Users\Vishnu\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\ops\gen_dataset_ops.py", line 2517, in iterator_get_next
    output_shapes=output_shapes, name=name)
  File "C:\Users\Vishnu\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\framework\op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\Vishnu\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\Users\Vishnu\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "C:\Users\Vishnu\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "C:\Users\Vishnu\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()
```

**Comment by PiotrDabrowskey** [comment]
Hi! I haven't been using TensorFlow for 2 years now and was using it on Windows only for a limited time due to project specifics. I had a problem in 1.8.0 (vs yours 1.15.1). Maybe it got fixed in the meantime. I am not even able to check whether this issue is solved, as it'd require me to use a paid platform (Windows OS) to do so, but I guess if it works properly for you, it's solved. Thank you!
