### ISSUE TITLE
TPU code running locally but not on TPU

### ISSUE THREAD

**Issue by jplu** [tensorflow/tensorflow#20747]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes, I did put the code below
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Debian 9
- **TensorFlow installed from (source or binary)**: already installed while creating the VM
- **TensorFlow version (use command below)**: 1.9.0-rc2
- **Python version**: 3.5
- **Bazel version (if compiling from source)**: Not compiled
- **GCC/Compiler version (if compiling from source)**: Not compiled
- **CUDA/cuDNN version**: not installed
- **GPU model and memory**: no GPU
- **Exact command to reproduce**: ```python3 test.py --tpu=$TPU_NAME --model_dir=output -use-tpu=True --batch_size=24```

### Describe the problem
When I run the following code:

```python
from tensorflow.python.keras.applications.vgg16 import VGG16
from tensorflow.python.keras import models
from tensorflow.python.keras import layers
from tensorflow.python.keras.preprocessing import image
import numpy as np
import tensorflow as tf
from tensorflow.python import keras
from absl import flags
import absl.logging as _logging
from tensorflow.contrib.tpu.python.tpu import tpu_config
from tensorflow.contrib.tpu.python.tpu import tpu_estimator
from tensorflow.contrib.tpu.python.tpu import tpu_optimizer
import numpy as np
import random
import math
import os


#  Cloud TPU Cluster Resolver flags
tf.flags.DEFINE_string(
    "tpu", default=None,
    help="The Cloud TPU to use for training. This should be either the name "
    "used when creating the Cloud TPU, or a grpc://ip.address.of.tpu:8470 "
    "url.")
tf.flags.DEFINE_string(
    "tpu_zone", default=None,
    help="[Optional] GCE zone where the Cloud TPU is located in. If not "
    "specified, we will attempt to automatically detect the GCE project from "
    "metadata.")
tf.flags.DEFINE_string(
    "gcp_project", default=None,
    help="[Optional] Project name for the Cloud TPU-enabled project. If not "
    "specified, we will attempt to automatically detect the GCE project from "
    "metadata.")

# Model specific parameters
tf.flags.DEFINE_string(
    "master", default=None,
    help="GRPC URL of the master (e.g. grpc://ip.address.of.tpu:8470). You "
    "must specify either this flag or --tpu.")
tf.flags.DEFINE_string("data_dir", "",
                       "Path to directory containing the dataset")
tf.flags.DEFINE_string("model_dir", 'output', "Estimator model_dir")
tf.flags.DEFINE_integer("batch_size", 3,
                        "Mini-batch size for the training. Note that this "
                        "is the global batch size and not the per-shard batch.")
tf.flags.DEFINE_integer("train_steps", 1, "Total number of training steps.")
tf.flags.DEFINE_float("learning_rate", 0.001, "Learning rate.")

tf.flags.DEFINE_bool("use_tpu", True, "Use TPUs rather than plain CPUs")
tf.flags.DEFINE_integer("iterations", 1,
                        "Number of iterations per TPU training loop.")
tf.flags.DEFINE_integer("num_shards", 8, "Number of shards (TPU chips).")

FLAGS = tf.flags.FLAGS

feature_names = [
    'query',
    'positive',
    'negative']

def load_triplets():
    triplets = []
    triplet_file = os.path.join(FLAGS.data_dir, 'triplets.txt')
    with tf.gfile.GFile(triplet_file) as f:
        count = 0
        for line in f:
            triplets.append(line.strip().split(','))
            count += 1
            if count % 1000 == 0:
                tf.logging.info("Loading {} triplets".format(count))

    tf.logging.info("Loading {} triplets".format(count))
    return triplets

def my_input_fn(triplet, label):
    query_img = tf.image.decode_jpeg(triplet[0], channels=3)
    query_img.set_shape([None, None, None])
    query_img = tf.image.resize_images(query_img, [224, 224])
    query_img.set_shape([224, 224, 3])
    positive_img = tf.image.decode_jpeg(tf.read_file(triplet[1]), channels=3)
    positive_img.set_shape([None, None, None])
    positive_img = tf.image.resize_images(positive_img, [224, 224])
    positive_img.set_shape([224, 224, 3])
    negative_img = tf.image.decode_jpeg(tf.read_file(triplet[2]), channels=3)
    negative_img.set_shape([None, None, None])
    negative_img = tf.image.resize_images(negative_img, [224, 224])
    negative_img.set_shape([224, 224, 3])

    return dict(zip(feature_names, [query_img, positive_img, negative_img])), label

def random_flip_left_right(image, label):
    augmented_query = tf.to_float(image['query'])
    augmented_query = tf.image.random_flip_left_right(image['query'])
    augmented_query = tf.cast(augmented_query, np.uint8)
    augmented_positive = tf.to_float(image['positive'])
    augmented_positive = tf.image.random_flip_left_right(image['positive'])
    augmented_positive = tf.cast(augmented_positive, np.uint8)
    augmented_negative = tf.to_float(image['negative'])
    augmented_negative = tf.image.random_flip_left_right(image['negative'])
    augmented_negative = tf.cast(augmented_negative, np.uint8)

    return dict(zip(feature_names, [augmented_query, augmented_positive, augmented_negative])), label

def random_flip_up_down(image, label):
    augmented_query = tf.to_float(image['query'])
    augmented_query = tf.image.random_flip_up_down(image['query'])
    augmented_query = tf.cast(augmented_query, np.uint8)
    augmented_positive = tf.to_float(image['positive'])
    augmented_positive = tf.image.random_flip_up_down(image['positive'])
    augmented_positive = tf.cast(augmented_positive, np.uint8)
    augmented_negative = tf.to_float(image['negative'])
    augmented_negative = tf.image.random_flip_up_down(image['negative'])
    augmented_negative = tf.cast(augmented_negative, np.uint8)

    return dict(zip(feature_names, [augmented_query, augmented_positive, augmented_negative])), label


def random_brightness(image, label):
    augmented_query = tf.to_float(image['query'])
    augmented_query = tf.image.random_brightness(image['query'], max_delta=random.uniform(0.0, 1.0))
    augmented_query = tf.cast(augmented_query, np.uint8)
    augmented_positive = tf.to_float(image['positive'])
    augmented_positive = tf.image.random_brightness(image['positive'], max_delta=random.uniform(0.0, 1.0))
    augmented_positive = tf.cast(augmented_positive, np.uint8)
    augmented_negative = tf.to_float(image['negative'])
    augmented_negative = tf.image.random_brightness(image['negative'], max_delta=random.uniform(0.0, 1.0))
    augmented_negative = tf.cast(augmented_negative, np.uint8)

    return dict(zip(feature_names, [augmented_query, augmented_positive, augmented_negative])), label

def random_contrast(image, label):
    augmented_query = tf.to_float(image['query'])
    augmented_query = tf.image.random_contrast(image['query'], lower=0.3, upper=1.0)
    augmented_query = tf.cast(augmented_query, np.uint8)
    augmented_positive = tf.to_float(image['positive'])
    augmented_positive = tf.image.random_contrast(image['positive'], lower=0.3, upper=1.0)
    augmented_positive = tf.cast(augmented_positive, np.uint8)
    augmented_negative = tf.to_float(image['negative'])
    augmented_negative = tf.image.random_contrast(image['negative'], lower=0.3, upper=1.0)
    augmented_negative = tf.cast(augmented_negative, np.uint8)

    return dict(zip(feature_names, [augmented_query, augmented_positive, augmented_negative])), label

def random_hue(image, label):
    augmented_query = tf.to_float(image['query'])
    augmented_query = tf.image.random_hue(image['query'], max_delta=random.uniform(0.0, 0.5))
    augmented_query = tf.cast(augmented_query, np.uint8)
    augmented_positive = tf.to_float(image['positive'])
    augmented_positive = tf.image.random_hue(image['positive'], max_delta=random.uniform(0.0, 0.5))
    augmented_positive = tf.cast(augmented_positive, np.uint8)
    augmented_negative = tf.to_float(image['negative'])
    augmented_negative = tf.image.random_hue(image['negative'], max_delta=random.uniform(0.0, 0.5))
    augmented_negative = tf.cast(augmented_negative, np.uint8)

    return dict(zip(feature_names, [augmented_query, augmented_positive, augmented_negative])), label

def random_saturation(image, label):
    augmented_query = tf.to_float(image['query'])
    augmented_query = tf.image.random_saturation(image['query'], lower=0.0, upper=2.0)
    augmented_query = tf.cast(augmented_query, np.uint8)
    augmented_positive = tf.to_float(image['positive'])
    augmented_positive = tf.image.random_saturation(image['positive'], lower=0.0, upper=2.0)
    augmented_positive = tf.cast(augmented_positive, np.uint8)
    augmented_negative = tf.to_float(image['negative'])
    augmented_negative = tf.image.random_saturation(image['negative'], lower=0.0, upper=2.0)
    augmented_negative = tf.cast(augmented_negative, np.uint8)

    return dict(zip(feature_names, [augmented_query, augmented_positive, augmented_negative])), label

def random_rotate(image, label):
    augmented_query = tf.to_float(image['query'])
    augmented_query = tf.contrib.image.rotate(image['query'], angles=random.uniform(0, 360) * math.pi / 180)
    augmented_query = tf.cast(augmented_query, np.uint8)
    augmented_positive = tf.to_float(image['positive'])
    augmented_positive = tf.contrib.image.rotate(image['positive'], angles=random.uniform(0, 360) * math.pi / 180)
    augmented_positive = tf.cast(augmented_positive, np.uint8)
    augmented_negative = tf.to_float(image['negative'])
    augmented_negative = tf.contrib.image.rotate(image['negative'], angles=random.uniform(0, 360) * math.pi / 180)
    augmented_negative = tf.cast(augmented_negative, np.uint8)

    return dict(zip(feature_names, [augmented_query, augmented_positive, augmented_negative])), label

def train_input_fn(params):
    batch_size = params["batch_size"]
    triplets = load_triplets()
    triplets_const = tf.constant(triplets)
    labels_const =tf.zeros([len(triplets)], tf.int32)
    dataset = tf.data.Dataset.from_tensor_slices((triplets_const, labels_const))
    dataset = dataset.shuffle(buffer_size=len(triplets))
    triplets.clear()
    dataset = dataset.map(my_input_fn)

    augmented_flip_left_right = dataset.map(random_flip_left_right)
    dataset = dataset.concatenate(augmented_flip_left_right)
    augmented_flip_up_down = dataset.map(random_flip_up_down)
    dataset = dataset.concatenate(augmented_flip_up_down)
    augmented_brightness = dataset.map(random_brightness)
    dataset = dataset.concatenate(augmented_brightness)
    augmented_contrast = dataset.map(random_contrast)
    dataset = dataset.concatenate(augmented_contrast)
    augmented_hue = dataset.map(random_hue)
    dataset = dataset.concatenate(augmented_hue)
    augmented_saturation = dataset.map(random_saturation)
    dataset = dataset.concatenate(augmented_saturation)
    augmented_rotate = dataset.map(random_rotate)
    dataset = dataset.concatenate(augmented_rotate)

    ds = dataset.cache().repeat().apply(tf.contrib.data.batch_and_drop_remainder(batch_size))
    triplets, labels = ds.make_one_shot_iterator().get_next()

    return triplets, labels


def convnet_model_():
    vgg_model = VGG16(weights=None, include_top=False)
    x = vgg_model.output
    x = layers.GlobalAveragePooling2D()(x)
    x = layers.Dense(4096, activation='relu')(x)
    x = layers.Dropout(0.6)(x)
    x = layers.Dense(4096, activation='relu')(x)
    x = layers.Dropout(0.6)(x)
    x = layers.Lambda(lambda x_: keras.backend.l2_normalize(x_, axis=1))(x)
    convnet_model = models.Model(inputs=vgg_model.input, outputs=x)

    return convnet_model

_EPSILON = keras.backend.epsilon()
def _loss_tensor(y_true, y_pred):
    y_pred = keras.backend.clip(y_pred, _EPSILON, 1.0-_EPSILON)
    loss = tf.convert_to_tensor(0, dtype=tf.float32)
    g = tf.constant(1.0, shape=[1], dtype=tf.float32)
    #for i in range(0, 24, 3):
    for i in range(0, FLAGS.batch_size, 3):
        try:
            q_embedding = y_pred[i+0]
            p_embedding = y_pred[i+1]
            n_embedding = y_pred[i+2]
            D_q_p = keras.backend.sqrt(keras.backend.sum((q_embedding - p_embedding)**2))
            D_q_n = keras.backend.sqrt(keras.backend.sum((q_embedding - n_embedding)**2))
            loss = (loss + g + D_q_p - D_q_n)
        except:
            continue
    #loss = loss / 8
    loss = loss / FLAGS.batch_size
    zero = tf.constant(0.0, shape=[1], dtype=tf.float32)

    return tf.maximum(loss, zero)


def model_fn(features, labels, mode, params):
    del params

    convnet_model = convnet_model_()
    first_input = layers.Input(shape=(224, 224, 3))
    first_conv = layers.Conv2D(96, kernel_size=(8, 8), strides=(16, 16), padding='same')(first_input)
    first_max = layers.MaxPool2D(pool_size=(3, 3), strides=(4, 4), padding='same')(first_conv)
    first_max = layers.Flatten()(first_max)
    first_max = layers.Lambda(lambda x: keras.backend.l2_normalize(x, axis=1))(first_max)
    second_input = layers.Input(shape=(224, 224, 3))
    second_conv = layers.Conv2D(96, kernel_size=(8, 8), strides=(32, 32), padding='same')(second_input)
    second_max = layers.MaxPool2D(pool_size=(7, 7), strides=(2, 2), padding='same')(second_conv)
    second_max = layers.Flatten()(second_max)
    second_max = layers.Lambda(lambda x: keras.backend.l2_normalize(x, axis=1))(second_max)
    merge_one = layers.concatenate([first_max, second_max])
    merge_two = layers.concatenate([convnet_model.output, merge_one])
    emb = layers.Dense(4096)(merge_two)
    l2_norm_final = layers.Lambda(lambda x: keras.backend.l2_normalize(x, axis=1))(emb)
    final_model = models.Model(inputs=[convnet_model.input, first_input, second_input], outputs=l2_norm_final)
    final_model.summary()
    if mode == tf.estimator.ModeKeys.PREDICT:
        logits = final_model([features['query'], features['positive'], features['negative']], training=False)
        predictions = {
            'embedding': logits[0]
        }
        return tf.estimator.EstimatorSpec(
            mode=tf.estimator.ModeKeys.PREDICT,
            predictions=predictions,
            export_outputs={
                'classify': tf.estimator.export.PredictOutput(predictions)
            })
    logits = final_model([features['query'], features['positive'], features['negative']], training=(mode == tf.estimator.ModeKeys.TRAIN))
    loss = _loss_tensor(None, logits)
    optimizer = tf.train.MomentumOptimizer(learning_rate=FLAGS.learning_rate, momentum=0.9, use_nesterov=True)

    if FLAGS.use_tpu:
        optimizer = tf.contrib.tpu.CrossShardOptimizer(optimizer)
    return tf.contrib.tpu.TPUEstimatorSpec(mode=tf.estimator.ModeKeys.TRAIN, loss=loss, train_op=optimizer.minimize(loss, tf.train.get_global_step()))


def main(argv):
    del argv
    tf.logging.set_verbosity(tf.logging.INFO)

    if FLAGS.master is None and FLAGS.tpu is None:
        raise RuntimeError('You must specify either --master or --tpu.')
    if FLAGS.master is not None:
        if FLAGS.tpu is not None:
            tf.logging.warn('Both --master and --tpu are set. Ignoring '
                      '--tpu and using --master.')
        tpu_grpc_url = FLAGS.master
    else:
        tpu_cluster_resolver = (tf.contrib.cluster_resolver.TPUClusterResolver(FLAGS.tpu, zone=FLAGS.tpu_zone, project=FLAGS.gcp_project))
        tpu_grpc_url = tpu_cluster_resolver.get_master()

    run_config = tpu_config.RunConfig(master=tpu_grpc_url, model_dir=FLAGS.model_dir, save_checkpoints_secs=3600, session_config=tf.ConfigProto(allow_soft_placement=True, log_device_placement=True), tpu_config=tpu_config.TPUConfig(iterations_per_loop=FLAGS.iterations, num_shards=FLAGS.num_shards),)
    estimator = tpu_estimator.TPUEstimator(model_fn=model_fn, use_tpu=FLAGS.use_tpu, config=run_config, train_batch_size=FLAGS.batch_size)
    estimator.train(input_fn=train_input_fn, max_steps=FLAGS.train_steps)
    img_input = tf.placeholder(tf.float32, [None, 224, 224, 3])
    input_fn =tf.estimator.export.build_raw_serving_input_receiver_fn({
        'query': img_input,
        'positive': img_input,
        'negative': img_input,
    })
    estimator.export_savedmodel('output', input_fn)


if __name__ == "__main__":
    tf.app.run()
```
I get the following error:

```
Traceback (most recent call last):
  File "test.py", line 370, in <module>
    tf.app.run()
  File "/home/julien_plu/.local/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "test.py", line 359, in main
    estimator.train(input_fn=train_input_fn, max_steps=FLAGS.train_steps)
  File "/home/julien_plu/.local/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 376, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/julien_plu/.local/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 1143, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/home/julien_plu/.local/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 1168, in _train_model_default
    features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
  File "/home/julien_plu/.local/lib/python3.5/site-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2162, in _call_model_fn
    features, labels, mode, config)
  File "/home/julien_plu/.local/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 1131, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/home/julien_plu/.local/lib/python3.5/site-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2414, in _model_fn
    _train_on_tpu_system(ctx, model_fn_wrapper, dequeue_fn))
  File "/home/julien_plu/.local/lib/python3.5/site-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2724, in _train_on_tpu_system
    device_assignment=ctx.device_assignment)
  File "/home/julien_plu/.local/lib/python3.5/site-packages/tensorflow/contrib/tpu/python/tpu/tpu.py", line 829, in shard
    name=name)
  File "/home/julien_plu/.local/lib/python3.5/site-packages/tensorflow/contrib/tpu/python/tpu/tpu.py", line 475, in replicate
    device_assignment, name)[1]
  File "/home/julien_plu/.local/lib/python3.5/site-packages/tensorflow/contrib/tpu/python/tpu/tpu.py", line 635, in split_compile_and_replicate
    outputs = computation(*computation_inputs)
  File "/home/julien_plu/.local/lib/python3.5/site-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2717, in multi_tpu_train_steps_on_single_shard
    single_tpu_train_step, [_INITIAL_LOSS])
  File "/home/julien_plu/.local/lib/python3.5/site-packages/tensorflow/contrib/tpu/python/tpu/training_loop.py", line 207, in repeat
    cond, body_wrapper, inputs=inputs, infeed_queue=infeed_queue, name=name)
  File "/home/julien_plu/.local/lib/python3.5/site-packages/tensorflow/contrib/tpu/python/tpu/training_loop.py", line 169, in while_loop
    name="")
  File "/home/julien_plu/.local/lib/python3.5/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3232, in while_loop
    return_same_structure)
  File "/home/julien_plu/.local/lib/python3.5/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2952, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/home/julien_plu/.local/lib/python3.5/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2924, in _BuildLoop
    next_vars.append(_AddNextAndBackEdge(m, v))
  File "/home/julien_plu/.local/lib/python3.5/site-packages/tensorflow/python/ops/control_flow_ops.py", line 666, in _AddNextAndBackEdge
    _EnforceShapeInvariant(m, v)
  File "/home/julien_plu/.local/lib/python3.5/site-packages/tensorflow/python/ops/control_flow_ops.py", line 610, in _EnforceShapeInvariant
    (input_t.name, input_t.shape, n_shape))
ValueError: Input tensor 'Const_1:0' enters the loop with shape (), but has shape (1,) after one iteration. To allow the shape to vary across iterations, use the `shape_invariants` argument of tf.while_loop to specify a less-specific shape.
```
While if I run the exact same code with ```--use_tpu=False --master=''``` it works like a charm.

Is it somehow related to a bug or is it me who is doing something wrong with dedicated TPU code?

Thanks in advance.

**Comment by rjpower** [comment]
Thanks for the report Julien. 

I was able to reproduce this.  It appears the issue is that your loss is a vector but we are expecting the returned loss to be a scalar value.  The TPUEstimator machinery wraps your model in a training loop which returns the loss as the final result.  The "dummy" initial loss is a scalar value which means your model function must also return a scalar value to be retain the same shape.  Apply `tf.reduce_sum(loss)` fixes the issue.  

I ended up summing the logits instead of the loss, as I was seeing a gradient error with the loss function you pasted in.  Hopefully this works for you -- please close the issue if this resolves your problem.

I've filed a bug internally to track improving the error message.

**Comment by jplu** [comment]
Thanks a lot @rjpower for the fix, I will test it ASAP today and let you know :)

What was the gradient error you have seen with my loss function? If I follow your fix I should be able to reproduce it?

**Comment by rjpower** [comment]
I don't have it handy, but the gradient error didn't appear TPU related: it was a warning from the optimizer that there were no gradients to the weight variables.  

Looking at it, my guess is that in my reproduction the `try: ... except: continue` block failed to execute and so the loss was a constant zero.  If you don't see the error in the CPU execution then it's probably fine.

**Comment by jplu** [comment]
Hummm... In my loss the constraint I have is that the batch size must be a multiple of 3 otherwise the loss fails. Maybe somewhere I forgot to take this into account, I will remove the ```try: ... except: continue``` and add a check if the loss equals 0, and see if I succeed to get this state.

Thanks a lot for everything as now I don't have anymore the issue with your fix :)
