### ISSUE TITLE
AttributeError: module 'pandas' has no attribute 'rolling_count'

### ISSUE THREAD

**Issue by jasonachonu** [tensorflow/tensorflow#20779]
Hi,

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: 
NO
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS Hugh Sierra
- **TensorFlow installed from (source or binary)**: I did pip install tensor flow
- **TensorFlow version (use command below)**: v1.9.0-0-g25c197e023 1.9.0
- **Python version**:  3.6
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:
Please find below the error am having.

Building the network
Traceback (most recent call last):
  File "./src/NeirbiLSTM-occupancy.py", line 49, in <module>
    trainoccupancy.run()
  File "/Users/jasonachonu/git/SeqHub_Summer2018/src/nblib/trainoccupancy.py", line 173, in run
    config.cost_type)
  File "/Users/jasonachonu/git/SeqHub_Summer2018/src/nblib/network.py", line 34, in train_net
    from tensorflow.contrib import rnn
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/__init__.py", line 39, in <module>
    from tensorflow.contrib import distributions
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/distributions/__init__.py", line 40, in <module>
    from tensorflow.contrib.distributions.python.ops.estimator import *
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/distributions/python/ops/estimator.py", line 21, in <module>
    from tensorflow.contrib.learn.python.learn.estimators.head import _compute_weighted_loss
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/learn/__init__.py", line 95, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/learn/python/__init__.py", line 28, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/__init__.py", line 30, in <module>
    from tensorflow.contrib.learn.python.learn import estimators
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/estimators/__init__.py", line 302, in <module>
    from tensorflow.contrib.learn.python.learn.estimators.dnn import DNNClassifier
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/estimators/dnn.py", line 35, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import dnn_linear_combined
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/estimators/dnn_linear_combined.py", line 36, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import estimator
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 52, in <module>
    from tensorflow.contrib.learn.python.learn.learn_io import data_feeder
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/learn_io/__init__.py", line 26, in <module>
    from tensorflow.contrib.learn.python.learn.learn_io.dask_io import extract_dask_data
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/learn_io/dask_io.py", line 33, in <module>
    import dask.dataframe as dd
  File "/anaconda3/lib/python3.6/site-packages/dask/dataframe/__init__.py", line 12, in <module>
    from .rolling import (rolling_count, rolling_sum, rolling_mean, rolling_median,
  File "/anaconda3/lib/python3.6/site-packages/dask/dataframe/rolling.py", line 200, in <module>
    rolling_count = wrap_rolling(pd.rolling_count, 'count')
AttributeError: module 'pandas' has no attribute 'rolling_count'

**Comment by chabir** [comment]
uninstall and reinstall dask worked for me...

**Comment by jasonachonu** [comment]
Thank you Xavier Capdepon, I did as you recommended and it worked.

Regards.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @jart: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @jart: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @jart: It has been 45 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @jart: It has been 61 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @jart: It has been 76 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by ffisc** [comment]
Similarly to what happened [here](https://github.com/pyviz/pyviz/issues/56), this might be likely due to the fact that pandas 0.23 no longer has `rolling_x` methods.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @jart: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @jart: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by wt-huang** [comment]
Closing as this is no longer relevant
