### ISSUE TITLE
BUG: Estimator training with tf.contrib.distribute fails under 1.9.0 but works under 1.8.0

### ISSUE THREAD

**Issue by Schnabbel** [tensorflow/tensorflow#20784]
------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:
binary
- **TensorFlow version (use command below)**:
1.9.0 and and v1.8.0-0-g93bc2e2072 1.8.0
- **Python version**:
3.6.5 
- **Bazel version (if compiling from source)**:
N/A
- **GCC/Compiler version (if compiling from source)**:
N/A
- **CUDA/cuDNN version**:
9.0
- **GPU model and memory**:
Titan 1080 Ti 12GB
- **Exact command to reproduce**:
See description

### Describe the problem
Training Estimator single or multi-gpu with OneDeviceStrategy and MirroredStrategy respectively works under 1.8.0 but produces a graph assertion error under 1.9.0. I know of no breaking changes regarding this mentioned in the [release notes](https://github.com/tensorflow/tensorflow/releases/tag/v1.9.0).

### Source code / logs

I broke it down to the following MWE. Under 1.8.0, both versions work fine, whereas in 1.9.0, the commented out lines work fine and the marked line produces the error as outlined in the Traceback.

```
import tensorflow as tf

def model_fn(features, labels=None, mode=tf.estimator.ModeKeys.TRAIN, params=None):

    train_images_batch = features
    res = tf.layers.conv2d(inputs=train_images_batch, filters=3, kernel_size=3, strides=1, padding='same', data_format='channels_first')
    loss = tf.reduce_mean((train_images_batch - res) ** 2)
    optimizer = tf.train.AdamOptimizer().minimize(loss = loss)
    return tf.estimator.EstimatorSpec(
        mode=tf.estimator.ModeKeys.TRAIN,
        loss=loss, train_op=optimizer)

class Dataset():
    def __init__(self):
        self.dataset = tf.data.Dataset.from_tensors(tf.ones([3,124,124]))

    def map_func(self, entry):

        return (tf.zeros([3,124,124]))
      
    def input_fn(self):

        #dataset = tf.data.Dataset.from_tensors(np.ones(shape=(3,124,124)))
        #dataset = dataset.apply(tf.contrib.data.shuffle_and_repeat(1, count=1))
        dataset = self.dataset.apply(tf.contrib.data.shuffle_and_repeat(1, count=1)) # this line actually produces the error
        dataset = dataset.apply(tf.contrib.data.map_and_batch(map_func= self.map_func, num_parallel_batches=1, batch_size=1))
        dataset = dataset.prefetch(buffer_size = 1)

        return dataset

dset = Dataset()

single_gpu = tf.contrib.distribute.OneDeviceStrategy(device='/gpu:0')

runconfig = tf.estimator.RunConfig(train_distribute=single_gpu)

estimator = tf.estimator.Estimator(model_fn=model_fn,
                                   config=runconfig)

estimator.train(input_fn = lambda: dset.input_fn())
```

Traceback:
```
Traceback (most recent call last):
  File "/home/staff/rippel/TF_MSD/MWE.py", line 40, in <module>
    estimator.train(input_fn = lambda: dset.input_fn())
  File "/home/staff/rippel/.conda/envs/rippel_tf/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 366, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/staff/rippel/.conda/envs/rippel_tf/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1117, in _train_model
    return self._train_model_distributed(input_fn, hooks, saving_listeners)
  File "/home/staff/rippel/.conda/envs/rippel_tf/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1145, in _train_model_distributed
    input_fn, model_fn_lib.ModeKeys.TRAIN))
  File "/home/staff/rippel/.conda/envs/rippel_tf/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 987, in _get_features_and_labels_from_input_fn
    return estimator_util.parse_input_fn_result(result)
  File "/home/staff/rippel/.conda/envs/rippel_tf/lib/python3.6/site-packages/tensorflow/python/estimator/util.py", line 104, in parse_input_fn_result
    iterator = result.make_initializable_iterator()
  File "/home/staff/rippel/.conda/envs/rippel_tf/lib/python3.6/site-packages/tensorflow/contrib/distribute/python/values.py", line 606, in make_initializable_iterator
    dataset_iterator = self._dataset.make_initializable_iterator()
  File "/home/staff/rippel/.conda/envs/rippel_tf/lib/python3.6/site-packages/tensorflow/contrib/distribute/python/prefetching_ops_v2.py", line 181, in make_initializable_iterator
    shared_name=shared_name)
  File "/home/staff/rippel/.conda/envs/rippel_tf/lib/python3.6/site-packages/tensorflow/contrib/distribute/python/prefetching_ops_v2.py", line 105, in __init__
    self._input_dataset)
  File "/home/staff/rippel/.conda/envs/rippel_tf/lib/python3.6/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 311, in make_initializer
    dataset._as_variant_tensor(), self._iterator_resource, name=name)  # pylint: disable=protected-access
  File "/home/staff/rippel/.conda/envs/rippel_tf/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 2082, in _as_variant_tensor
    self._input_dataset._as_variant_tensor(),  # pylint: disable=protected-access
  File "/home/staff/rippel/.conda/envs/rippel_tf/lib/python3.6/site-packages/tensorflow/contrib/data/python/ops/batching.py", line 485, in _as_variant_tensor
    input_resource = self._input_dataset._as_variant_tensor()
  File "/home/staff/rippel/.conda/envs/rippel_tf/lib/python3.6/site-packages/tensorflow/contrib/data/python/ops/shuffle_ops.py", line 62, in _as_variant_tensor
    sparse.as_dense_shapes(self.output_shapes, self.output_classes)))
  File "/home/staff/rippel/.conda/envs/rippel_tf/lib/python3.6/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 3554, in shuffle_and_repeat_dataset
    output_types=output_types, output_shapes=output_shapes, name=name)
  File "/home/staff/rippel/.conda/envs/rippel_tf/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 350, in _apply_op_helper
    g = ops._get_graph_from_inputs(_Flatten(keywords.values()))
  File "/home/staff/rippel/.conda/envs/rippel_tf/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 5663, in _get_graph_from_inputs
    _assert_same_graph(original_graph_element, graph_element)
  File "/home/staff/rippel/.conda/envs/rippel_tf/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 5599, in _assert_same_graph
    original_item))
ValueError: Tensor("buffer_size:0", shape=(), dtype=int64, device=/device:CPU:0) must be from the same graph as Tensor("TensorDataset:0", shape=(), dtype=variant).
```

**Comment by robieta** [comment]
I would say this is expected behavior. One of the key features of estimator is that it performs graph and session management for you. So what you've done is you've created a tensor in the default graph (implicitly when you create self.dataset). However model_fn is called within estimator, using the estimator's graph. So you're trying to create a tensor in one graph that depends on another graph which is not allowed. The fact that is worked before is a bug in 1.8 I believe, rather than vice versa. 

Thanks for submitting, and for providing a lovely minimal example.
