### ISSUE TITLE
TF Lite ---- Not a variable: Tensor("w1:0", shape=(1, 128, 128, 3), dtype=float32)

### ISSUE THREAD

**Issue by longchr123** [tensorflow/tensorflow#20824]
**Environment:**
tensorflow 1.8,ubuntu16.0.4,cuda9.0,cudnn:7.0.5

**Test Demo:**

def save_to_pb(sess):
    constant_graph = graph_util.convert_variables_to_constants(sess, sess.graph_def, ['out'])
    with tf.gfile.FastGFile(MODEL_DIR + 'expert-graph.pb', mode='wb') as f:
        f.write(constant_graph.SerializeToString())

train_model():
    img = tf.placeholder(name="img", dtype=tf.float32, shape=(1, 128, 128, 3))
    b = tf.Variable(tf.truncated_normal((1, 128, 128, 3), seed=1),name='w1')
    y_real = img + tf.constant([1., 2., 3.]) + tf.constant([1., 4., 4.])

    val = tf.add(img, b)
    val = batch_norm_lite(val)
    out = tf.identity(val, name="out")

    MSE = tf.reduce_mean(tf.square(y_real - out), name='mse')
    train_step = tf.train.GradientDescentOptimizer(0.9).minimize(MSE)

    saver = tf.train.Saver(var_list={'w1':b},max_to_keep=10)

    os.environ["CUDA_VISIBLE_DEVICES"] = ''
    config = tf.ConfigProto()
    config.gpu_options.per_process_gpu_memory_fraction = 0.1
    config.gpu_options.allow_growth = True

    with tf.Session() as sess:
        sess.run(tf.initialize_all_variables())
        for epoch in range(100):
            sess.run(train_step,feed_dict={img:read_data(sess)})
            if epoch % 20 == 0:
                save_path = saver.save(sess, MODEL_DIR + MODEL_NAME, global_step=epoch + 1)
            print('step = ' + str(epoch))
        save_to_pb(sess)

**Terminal:**
bazel-bin/tensorflow/python/tools/freeze_graph --input_graph=/path/to/expert-graph.pb --input_checkpoint=/path/to/model.ckpt --output_node_names=output --output_graph=/path/to/frozen.pb --input_binary=true

**Error：**
/home/leve/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2018-07-13 18:37:04.467417: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-07-13 18:37:04.579724: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-07-13 18:37:04.580044: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 0 with properties: 
name: GeForce GTX 1060 6GB major: 6 minor: 1 memoryClockRate(GHz): 1.7845
pciBusID: 0000:01:00.0
totalMemory: 5.93GiB freeMemory: 5.29GiB
2018-07-13 18:37:04.580057: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1435] Adding visible gpu devices: 0
2018-07-13 18:37:04.747082: I tensorflow/core/common_runtime/gpu/gpu_device.cc:923] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-07-13 18:37:04.747104: I tensorflow/core/common_runtime/gpu/gpu_device.cc:929]      0 
2018-07-13 18:37:04.747109: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 0:   N 
2018-07-13 18:37:04.747225: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 5066 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1060 6GB, pci bus id: 0000:01:00.0, compute capability: 6.1)
Traceback (most recent call last):
  File "/home/leve/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/tools/freeze_graph.py", line 382, in <module>
    run_main()
  File "/home/leve/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/tools/freeze_graph.py", line 379, in run_main
    app.run(main=my_main, argv=[sys.argv[0]] + unparsed)
  File "/home/leve/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "/home/leve/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/tools/freeze_graph.py", line 378, in <lambda>
    my_main = lambda unused_args: main(unused_args, flags)
  File "/home/leve/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/tools/freeze_graph.py", line 272, in main
    flags.saved_model_tags, checkpoint_version)
  File "/home/leve/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/tools/freeze_graph.py", line 254, in freeze_graph
    checkpoint_version=checkpoint_version)
  File "/home/leve/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/tools/freeze_graph.py", line 128, in freeze_graph_with_def_protos
    var_list=var_list, write_version=checkpoint_version)
  File "/home/leve/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/training/saver.py", line 1338, in __init__
    self.build()
  File "/home/leve/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/training/saver.py", line 1347, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/leve/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/training/saver.py", line 1384, in _build
    build_save=build_save, build_restore=build_restore)
  File "/home/leve/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/training/saver.py", line 813, in _build_internal
    saveables = self._ValidateAndSliceInputs(names_to_saveables)
  File "/home/leve/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/training/saver.py", line 714, in _ValidateAndSliceInputs
    variable)
**TypeError: names_to_saveables must be a dict mapping string names to Tensors/Variables. Not a variable: Tensor("w1:0", shape=(1, 128, 128, 3), dtype=float32)**

**Comment by longchr123** [comment]
Does anyone know about this problem?

**Comment by shashishekhar** [comment]
@longchr123 : Can you used tf.saved_model to save the graph and tf_convert https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/lite/toco/g3doc/cmdline_examples.md#savedmodel

to convert it. It is available with latest version of Tensorflow

**Comment by shashishekhar** [comment]
@longchr123 : Please reopen this issue, if you are still having trouble converting the model.
