### ISSUE TITLE
TFLite --- TypeError: names_to_saveables must be a dict mapping string names to Tensors/Variables. Not a variable: Tensor("MobilenetV1/Conv2d_0/BatchNorm/beta:0", shape=(32,), dtype=float32)

### ISSUE THREAD

**Issue by longchr123** [tensorflow/tensorflow#20825]
we can get mobilenet tflite&pb(Mobilenet_1.0_224) from https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/lite/g3doc/models.md

when I use the command:
bazel-bin/tensorflow/python/tools/freeze_graph --input_graph=/path/to/mobilenet_v1_1.0_224_frozen.pb --input_checkpoint=/path/to/mobilenet_v1_1.0_224.ckpt --output_graph=/path/to/freezed_mobilenet.pb --output_node_names=MobilenetV1/Predictions/Reshape_1 --input_binary=true

error occured:
/home/leve/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2018-07-16 11:04:48.613520: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-07-16 11:04:48.728926: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-07-16 11:04:48.729264: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 0 with properties: 
name: GeForce GTX 1060 6GB major: 6 minor: 1 memoryClockRate(GHz): 1.7845
pciBusID: 0000:01:00.0
totalMemory: 5.93GiB freeMemory: 5.31GiB
2018-07-16 11:04:48.729276: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1435] Adding visible gpu devices: 0
2018-07-16 11:04:48.873004: I tensorflow/core/common_runtime/gpu/gpu_device.cc:923] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-07-16 11:04:48.873030: I tensorflow/core/common_runtime/gpu/gpu_device.cc:929]      0 
2018-07-16 11:04:48.873035: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 0:   N 
2018-07-16 11:04:48.873192: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 5086 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1060 6GB, pci bus id: 0000:01:00.0, compute capability: 6.1)
Traceback (most recent call last):
  File "/home/leve/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/tools/freeze_graph.py", line 382, in <module>
    run_main()
  File "/home/leve/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/tools/freeze_graph.py", line 379, in run_main
    app.run(main=my_main, argv=[sys.argv[0]] + unparsed)
  File "/home/leve/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "/home/leve/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/tools/freeze_graph.py", line 378, in <lambda>
    my_main = lambda unused_args: main(unused_args, flags)
  File "/home/leve/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/tools/freeze_graph.py", line 272, in main
    flags.saved_model_tags, checkpoint_version)
  File "/home/leve/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/tools/freeze_graph.py", line 254, in freeze_graph
    checkpoint_version=checkpoint_version)
  File "/home/leve/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/tools/freeze_graph.py", line 128, in freeze_graph_with_def_protos
    var_list=var_list, write_version=checkpoint_version)
  File "/home/leve/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/training/saver.py", line 1338, in __init__
    self.build()
  File "/home/leve/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/training/saver.py", line 1347, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/leve/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/training/saver.py", line 1384, in _build
    build_save=build_save, build_restore=build_restore)
  File "/home/leve/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/training/saver.py", line 813, in _build_internal
    saveables = self._ValidateAndSliceInputs(names_to_saveables)
  File "/home/leve/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/training/saver.py", line 714, in _ValidateAndSliceInputs
    variable)
**TypeError: names_to_saveables must be a dict mapping string names to Tensors/Variables. Not a variable: Tensor("MobilenetV1/Conv2d_0/BatchNorm/beta:0", shape=(32,), dtype=float32)**

### System information
- **Linux Ubuntu 16.04**:
- **TensorFlow installed from source**:
- **TensorFlow version 1.8.0**:
- **Python version:3.6**: 
- **Bazel version 0.11.1**:
- **GCC/Compiler version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10) **:
- **CUDA/cuDNN 9.0/7.0.5**:
- **GPU  1060-6G**:
- **Exact command to reproduce**:

**Comment by freedomtan** [comment]
@longchr123 why are you trying to freeze a frozen_graph?
```
bazel-bin/tensorflow/python/tools/freeze_graph --input_graph=/path/to/mobilenet_v1_1.0_224_frozen.pb --input_checkpoint=/path/to/mobilenet_v1_1.0_224.ckpt --output_graph=/path/to/freezed_mobilenet.pb --output_node_names=MobilenetV1/Predictions/Reshape_1 --input_binary=true
```
If what you want to do is to generate a new frozen graph from the mobilenet tflite&pb 
 (Mobilenet_1.0_224) file, try 
```
bazel-bin/tensorflow/python/tools/freeze_graph --input_graph=/path/to/mobilenet_v1_1.0_224_eval.pbtxt --input_checkpoint=/path/to/mobilenet_v1_1.0_224.ckpt --output_graph=/path/to/freezed_mobilenet.pb --output_node_names=MobilenetV1/Predictions/Reshape_1
```
instead.

**Comment by longchr123** [comment]
@freedomtan what you said is right, I have tested,but when I write a test code(#20824 ), convert pb to pbtxt, the problem also happend, when execute the command
`bazel-bin/tensorflow/python/tools/freeze_graph` --input_graph=/path/to/mobilenet_v1_1.0_224_eval.pbtxt --input_checkpoint=/path/to/mobilenet_v1_1.0_224.ckpt --output_graph=/path/to/freezed_mobilenet.pb --output_node_names=MobilenetV1/Predictions/Reshape_1`
I don't know why

**Comment by karmel** [comment]
I apologize, but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please fill out the issue template (https://github.com/tensorflow/tensorflow/issues/new), and please re-paste using the error from trying to freeze a not-frozen graph rather than an already frozen one. Thanks--

**Comment by longchr123** [comment]
@karmel  I should change mobilenet_v1_1.0_224_frozen.pb to mobilenet.pb  from
```
bazel-bin/tensorflow/python/tools/freeze_graph --input_graph=/path/to/mobilenet_v1_1.0_224_frozen.pb --input_checkpoint=/path/to/mobilenet_v1_1.0_224.ckpt --output_graph=/path/to/freezed_mobilenet.pb --output_node_names=MobilenetV1/Predictions/Reshape_1 --input_binary=true
```

like this:
```
bazel-bin/tensorflow/python/tools/freeze_graph --input_graph=/path/to/mobilenet.pb --input_checkpoint=/path/to/mobilenet_v1_1.0_224.ckpt --output_graph=/path/to/freezed_mobilenet.pb --output_node_names=MobilenetV1/Predictions/Reshape_1 --input_binary=true
```

Code to generate mobilenet.pb files:
```
def freeze_graph(ckpt_dir):
    output_graph = os.path.join(MODEL_DIR, MODEL_NAME)
    output_node_names = "output"
    saver = tf.train.import_meta_graph(ckpt_dir + '.meta', clear_devices=True)

    graph = tf.get_default_graph()
    input_graph_def = graph.as_graph_def()

    with tf.Session() as sess:
        saver.restore(sess, ckpt_dir)

        output_graph_def = graph_util.convert_variables_to_constants(
            sess,
            input_graph_def,
            output_node_names.split(",")
        )
        with tf.gfile.GFile(output_graph, "wb") as f:
            f.write(output_graph_def.SerializeToString())
        print("%d ops in the final graph." % len(output_graph_def.node))

        for op in graph.get_operations():
            print(op.name, op.values())
```

Is the action of graph_util.convert_variables_to_constants and command(bazel...freeze_graph ) the same?

**Comment by freedomtan** [comment]
@longchr123 not exactly the same, but one of the important steps in [freeze_graph](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/tools/freeze_graph.py) is `graph_util.convert_variables_to_constants`

**Comment by tensorflowbutler** [comment]
Nagging Assignee @karmel: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by gargn** [comment]
Can you explain your motivation behind freezing the model `mobilenet_v1_1.0_224_frozen.pb`?

The model is already frozen, so it does not need to run through the `freeze_graph` tool again. Additionally, if you are trying to use this model in TensorFlow Lite, then you can use the provided `mobilenet_v1_1.0_224.tflite` file.
