### ISSUE TITLE
Coordinator stopped with threads still running

### ISSUE THREAD

**Issue by dcmrlee** [tensorflow/tensorflow#20833]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:  Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: N/A
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.8
- **Python version**: 3.5
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: 8.0
- **GPU model and memory**: NV-P40
- **Exact command to reproduce**: N/A

### Describe the problem
Running distributed tensorflow using estimator in sync mode, there is always a exception after the last training step, as followed:
```
INFO:tensorflow:Coordinator stopped with threads still running: QueueRunnerThread-dummy_queue-sync_token_q_EnqueueMany
Exception in thread QueueRunnerThread-dummy_queue-sync_token_q_EnqueueMany:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/queue_runner_impl.py", line 268, in _run
    coord.request_stop(e)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/coordinator.py", line 213, in request_stop
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python3.5/dist-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/queue_runner_impl.py", line 252, in _run
    enqueue_callable()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1244, in _single_operation_run
    self._call_tf_sessionrun(None, {}, [], target_list, None)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.CancelledError: Step was cancelled by an explicit call to `Session::Close()`.
``` 

It seems there is a closing problem when using tf.train.SyncReplicasOptimizer.
Any one know how to fix this?  

### Source code / logs
Main Code Fragment(model_fn) as followed:
```
with tf.device('/job:worker/task:%d' % task_index):
    with slim.arg_scope([slim.variables.variable, slim.variables.global_step],
                 device=slim.variables.VariableDeviceChooser(num_parameter_servers)):
             global_step = slim.variables.global_step()
             # Calculate the learning rate schedule.
             num_batches_per_epoch = (num_examples_per_epoch / FLAGS.batch_size)
             decay_steps = int(num_batches_per_epoch * FLAGS.num_epochs_per_decay)

             # Decay the learning rate exponentially based on the number of steps.
             lr = tf.train.exponential_decay(FLAGS.initial_learning_rate,
                                             global_step,
                                             decay_steps,
                                             FLAGS.learning_rate_decay_factor,
                                             staircase=True)
             opt = tf.train.RMSPropOptimizer(learning_rate=lr,
                                                 decay=RMSPROP_DECAY,
                                                 momentum=RMSPROP_MOMENTUM,
                                                 epsilon=RMSPROP_EPSILON)
            # forward
             logits = inception.inference(features, num_classes, for_training=True)

             # loss
             inception.loss(logits, labels)
             losses = tf.get_collection(slim.losses.LOSSES_COLLECTION)
             losses += tf.get_collection(tf.GraphKeys.REGULARIZATION_LOSSES)

             total_loss = tf.add_n(losses, name='total_loss')

              # Create synchronous replica optimizer.
             opt = tf.train.SyncReplicasOptimizer(
                     opt,
                     replicas_to_aggregate=num_replicas_to_aggregate,
                     total_num_replicas=num_workers)

             # Compute gradients with respect to the loss.
             grads = opt.compute_gradients(total_loss)
             apply_gradient_op = opt.apply_gradients(grads, global_step=global_step)
             sync_replicas_hook = opt.make_session_run_hook(is_chief, num_tokens=num_workers)
             
              return tf.estimator.EstimatorSpec(
                 mode=mode,
                 loss=total_loss,
                 train_op=train_op,
                 training_chief_hooks=[],
                 training_hooks=[sync_replicas_hook])
```
--------------------
And some  logs:
```
INFO:tensorflow:SyncReplicasV2: replicas_to_aggregate=2; total_num_replicas=2
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:tokens_needed = 0
INFO:tensorflow:Graph was finalized.
2018-07-16 09:13:43.014523: I tensorflow/core/distributed_runtime/master_session.cc:1142] Start master session a13a7f78ee358c84 with config: allow_soft_placement: true
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:loss = 13.082163, step = 0
INFO:tensorflow:Saving checkpoints for 1 into /tmp/aves/train_dir/model.ckpt.
INFO:tensorflow:loss = 13.082163
INFO:tensorflow:loss = 13.115122 (15.557 sec)
INFO:tensorflow:Saving checkpoints for 2 into /tmp/aves/train_dir/model.ckpt.
INFO:tensorflow:loss = 13.103788 (7.314 sec)
INFO:tensorflow:global_step/sec: 0.043722
INFO:tensorflow:Saving checkpoints for 3 into /tmp/aves/train_dir/model.ckpt.
INFO:tensorflow:loss = 13.137239 (6.563 sec)
INFO:tensorflow:global_step/sec: 0.152378
INFO:tensorflow:Saving checkpoints for 4 into /tmp/aves/train_dir/model.ckpt.
INFO:tensorflow:loss = 13.200961 (6.763 sec)
INFO:tensorflow:global_step/sec: 0.147865
INFO:tensorflow:Saving checkpoints for 5 into /tmp/aves/train_dir/model.ckpt.
INFO:tensorflow:loss = 13.265466 (6.318 sec)
INFO:tensorflow:global_step/sec: 0.158291
INFO:tensorflow:Saving checkpoints for 6 into /tmp/aves/train_dir/model.ckpt.
INFO:tensorflow:loss = 13.165977 (6.270 sec)
INFO:tensorflow:global_step/sec: 0.159476
INFO:tensorflow:Saving checkpoints for 7 into /tmp/aves/train_dir/model.ckpt.
INFO:tensorflow:loss = 13.478054 (7.017 sec)
INFO:tensorflow:global_step/sec: 0.14252
INFO:tensorflow:Saving checkpoints for 8 into /tmp/aves/train_dir/model.ckpt.
WARNING:tensorflow:Ignoring: /tmp/aves/train_dir/model.ckpt-3.meta; No such file or directory
INFO:tensorflow:loss = 13.231509 (6.544 sec)
INFO:tensorflow:global_step/sec: 0.152785
INFO:tensorflow:Saving checkpoints for 9 into /tmp/aves/train_dir/model.ckpt.
INFO:tensorflow:loss = 13.367797 (6.686 sec)
INFO:tensorflow:global_step/sec: 0.149593
INFO:tensorflow:Saving checkpoints for 10 into /tmp/aves/train_dir/model.ckpt.
INFO:tensorflow:loss = 13.461123 (6.659 sec)
INFO:tensorflow:global_step/sec: 0.150159
INFO:tensorflow:Coordinator stopped with threads still running: QueueRunnerThread-dummy_queue-sync_token_q_EnqueueMany
Exception in thread QueueRunnerThread-dummy_queue-sync_token_q_EnqueueMany:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/queue_runner_impl.py", line 268, in _run
    coord.request_stop(e)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/coordinator.py", line 213, in request_stop
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python3.5/dist-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/queue_runner_impl.py", line 252, in _run
    enqueue_callable()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1244, in _single_operation_run
    self._call_tf_sessionrun(None, {}, [], target_list, None)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.CancelledError: Step was cancelled by an explicit call to `Session::Close()`.

INFO:tensorflow:Loss for final step: 13.461123.
```

**Comment by allenzhang010** [comment]
@mrry is that related to this?   After a thread has called `coord.request_stop()` the other threads have a
  fixed time to stop, this is called the 'stop grace period' and defaults to 2
  minutes.  If any of the threads is still alive after the grace period expires
  `coord.join()` raises a RuntimeError reporting the laggards.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by cy89** [comment]
@dcmrlee there's a hint in #13779 about adding an ignore_live_threads=True; would you please try that?

**Comment by tensorflowbutler** [comment]
It has been 17 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by ashahba** [comment]
Hi, I'm also experiencing this behavior.
I'm using `TensorFlow` version `1.9.0` and I'm running a `distributed mnist` job using [tfoperator](https://github.com/kubeflow/tf-operator) and [mlt](https://github.com/IntelAI/mlt) on a `GKE` cluster.

After my [main.py](https://github.com/IntelAI/mlt/blob/master/mlt-templates/tf-dist-mnist/main.py) finishes near line 221, I get:
```
[my-tf-dist-a5dfa2c6-a28b-4f86-8b4c-251ee-worker-6mdt-1-bmbvb] INFO:root:worker 1, step 254 of 256: loss = 1.478 
[my-tf-dist-a5dfa2c6-a28b-4f86-8b4c-251ee-worker-6mdt-0-zlea4] INFO:root:worker 0, step 254 of 256: loss = 1.481 
[my-tf-dist-a5dfa2c6-a28b-4f86-8b4c-251ee-worker-6mdt-0-zlea4] INFO:root:worker 0, step 255 of 256: loss = 1.499 
[my-tf-dist-a5dfa2c6-a28b-4f86-8b4c-251ee-worker-6mdt-1-bmbvb] INFO:root:worker 1, step 255 of 256: loss = 1.47 
[my-tf-dist-a5dfa2c6-a28b-4f86-8b4c-251ee-worker-6mdt-1-bmbvb] INFO:root:Finished on task 1 in 98.08173823356628 seconds 
[my-tf-dist-a5dfa2c6-a28b-4f86-8b4c-251ee-worker-6mdt-1-bmbvb] INFO:root:Session from worker 1 closed cleanly 
[my-tf-dist-a5dfa2c6-a28b-4f86-8b4c-251ee-worker-6mdt-0-zlea4] INFO:tensorflow:Coordinator stopped with threads still running: QueueRunnerThread-dummy_queue-sync_token_q_EnqueueMany
```
and for that reason my `Pods` remain running indefinitely and the TfJob is never marked as `Succeeded`.

Have I written custom code: No
OS Platform and Distribution: Ubuntu 16.04
TensorFlow installed from: https://hub.docker.com/r/intelaipg/intel-optimized-tensorflow/
TensorFlow version: 1.9.0
Bazel version: N/A
CUDA/cuDNN version: N/A
GPU model and memory: N/A
Exact command to reproduce: 
```
mlt init my-tf-dist --template=tf-dist-mnist --template-repo=.
mlt deploy -l
```
first command instantiates a distributed `TensorFlow mnist` template to be used for deploying as a TfJob on a `GKE` cluster and then the second command deploys the job and uses [kubetail](https://github.com/johanhaleby/kubetail) to tail the aggregated logs for all the Pods.

This is currently blocking one of our PRs on `mlt` here: https://github.com/IntelAI/mlt/pull/387

**Comment by ashahba** [comment]
I even tried modifying [coordinator.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/training/coordinator.py#L322) as follows:
```python
  def join(self, threads=None, stop_grace_period_secs=120,
           ignore_live_threads=True):
    """Wait for threads to terminate.
```
and deployed the TfJob again but still same behavior and I get:
```
[my-tf-dist-7bd9faec-bd67-41cc-a9c2-86e68-worker-g1qj-1-urvjt] INFO:root:Finished on task 1 in 99.67636966705322 seconds 
[my-tf-dist-7bd9faec-bd67-41cc-a9c2-86e68-worker-g1qj-1-urvjt] INFO:root:Session from worker 1 closed cleanly 
[my-tf-dist-7bd9faec-bd67-41cc-a9c2-86e68-worker-g1qj-0-3oxfi] INFO:tensorflow:Coordinator stopped with threads still running: QueueRunnerThread-dummy_queue-sync_token_q_EnqueueMany 
```

**Comment by ashahba** [comment]
I just verified that with version `1.8.0` I don't have this issue.

**Comment by tobegit3hub** [comment]
We have the similar problem in `TensorFlow 1.8.0` when using `MonitoredSession ` and  `SyncReplicasOptimizer` in distributed training. The parameter `ignore_live_threads` is in Coordinator and I'm not sure if we can set in `MonitoredSession`.

Here is the error log of trying to close the session.

```
INFO:tensorflow:Coordinator stopped with threads still running: QueueRunnerThread-dummy_queue-sync_token_q_EnqueueMany
2018-08-15 15:50:02 INFO     Coordinator stopped with threads still running: QueueRunnerThread-dummy_queue-sync_token_q_EnqueueMany
Exception in thread QueueRunnerThread-dummy_queue-sync_token_q_EnqueueMany:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/training/queue_runner_impl.py", line 268, in _run
    coord.request_stop(e)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/training/coordinator.py", line 213, in request_stop
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/training/queue_runner_impl.py", line 252, in _run
    enqueue_callable()
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1244, in _single_operation_run
    self._call_tf_sessionrun(None, {}, [], target_list, None)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
CancelledError: Step was cancelled by an explicit call to `Session::Close()`.
```

**Comment by ashahba** [comment]
@tobegit3hub Thanks for the update.
I'm seeing that error in my `kubetail` logs too, but it seems like for some reason `TfOperator` won't see that as a show stopper and marks the jobs as `Succeeded`:
So on `1.9.0` I have (`State:                Running`):
```
$ kubectl describe tfjob my-tf-dist-7bd9faec-bd67-41cc-a9c2-86e685f157da 
Name:         my-tf-dist-7bd9faec-bd67-41cc-a9c2-86e685f157da
Namespace:    ashahba
Labels:       mlt-app-name=my-tf-dist
Annotations:  kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"kubeflow.org/v1alpha1","kind":"TFJob","metadata":{"annotations":{},"labels":{"mlt-app-name":"my-tf-dist"},"name":"my-tf-dist-7bd9faec-bd...
API Version:  kubeflow.org/v1alpha1
Kind:         TFJob
Metadata:
  Cluster Name:        
  Creation Timestamp:  2018-08-15T06:43:54Z
  Generation:          1
  Resource Version:    36154858
  Self Link:           /apis/kubeflow.org/v1alpha1/namespaces/ashahba/tfjobs/my-tf-dist-7bd9faec-bd67-41cc-a9c2-86e685f157da
  UID:                 93d30628-a056-11e8-8f32-42010a8a0062
Spec:
  Runtime Id:  g1qj
  Replica Specs:
    Replicas:  1
    Template:
      Metadata:
        Creation Timestamp:  <nil>
      Spec:
        Containers:
          Image:  <MY_IMAGE_REPOSITORY>/my-tf-dist:ee01f210-692a-4f5f-9211-1b57ddc35250
          Name:   tensorflow
          Resources:
        Restart Policy:  OnFailure
    Tf Port:             2222
    Tf Replica Type:     PS
    Replicas:            2
    Template:
      Metadata:
        Creation Timestamp:  <nil>
      Spec:
        Containers:
          Image:  <MY_IMAGE_REPOSITORY>/my-tf-dist:ee01f210-692a-4f5f-9211-1b57ddc35250
          Name:   tensorflow
          Resources:
        Restart Policy:  OnFailure
    Tf Port:             2222
    Tf Replica Type:     WORKER
  Termination Policy:
    Chief:
      Replica Index:  0
      Replica Name:   WORKER
  Tf Image:           tensorflow/tensorflow:1.3.0
Status:
  Phase:   Running
  Reason:  
  Replica Statuses:
    Replicas States:
      Running:            1
    State:                Running
    Tf _ Replica _ Type:  PS
    Replicas States:
      Running:            1
      Succeeded:          1
    State:                Running
    Tf _ Replica _ Type:  WORKER
  State:                  Running
Events:                   <none>
```
and on `1.8.0` we get (`State:                  Succeeded`):
```
$ kubectl describe tfjob my-tf-dist-edb61c5c-6ef4-4d90-baac-752956f59978
Name:         my-tf-dist-edb61c5c-6ef4-4d90-baac-752956f59978
Namespace:    ashahba
Labels:       mlt-app-name=my-tf-dist
Annotations:  kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"kubeflow.org/v1alpha1","kind":"TFJob","metadata":{"annotations":{},"labels":{"mlt-app-name":"my-tf-dist"},"name":"my-tf-dist-edb61c5c-6e...
API Version:  kubeflow.org/v1alpha1
Kind:         TFJob
Metadata:
  Cluster Name:        
  Creation Timestamp:  2018-08-15T07:03:24Z
  Generation:          1
  Resource Version:    36158966
  Self Link:           /apis/kubeflow.org/v1alpha1/namespaces/ashahba/tfjobs/my-tf-dist-edb61c5c-6ef4-4d90-baac-752956f59978
  UID:                 4d73f22e-a059-11e8-8f32-42010a8a0062
Spec:
  Runtime Id:  qt9l
  Replica Specs:
    Replicas:  1
    Template:
      Metadata:
        Creation Timestamp:  <nil>
      Spec:
        Containers:
          Image:  gcr.io/constant-cubist-173123/my-tf-dist:15e9dd11-22a0-45e0-9a8e-9f72bd445703
          Name:   tensorflow
          Resources:
        Restart Policy:  OnFailure
    Tf Port:             2222
    Tf Replica Type:     PS
    Replicas:            2
    Template:
      Metadata:
        Creation Timestamp:  <nil>
      Spec:
        Containers:
          Image:  <MY_IMAGE_REPOSITORY>/my-tf-dist:15e9dd11-22a0-45e0-9a8e-9f72bd445703
          Name:   tensorflow
          Resources:
        Restart Policy:  OnFailure
    Tf Port:             2222
    Tf Replica Type:     WORKER
  Termination Policy:
    Chief:
      Replica Index:  0
      Replica Name:   WORKER
  Tf Image:           tensorflow/tensorflow:1.3.0
Status:
  Phase:   Done
  Reason:  
  Replica Statuses:
    Replicas States:
      Running:            1
    State:                Running
    Tf _ Replica _ Type:  PS
    Replicas States:
      Running:            1
      Succeeded:          1
    State:                Running
    Tf _ Replica _ Type:  WORKER
  State:                  Succeeded
Events:                   <none>
```

and we have the first one with

**Comment by ashahba** [comment]
@allenzhang010 Do you need more info on this?

**Comment by allenzhang010** [comment]
@ashahba Thanks, I think this ticket can be closed.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by dksb** [comment]
Please create a new issue, if you have a similar issue.

**Comment by dingevin** [comment]
@ashahba  I have the similar problem in TensorFlow 1.10.0 when using MonitoredSession and SyncReplicasOptimizer at chief worker in distributed training, and i still don't know how to solve it. can you give me some advice. thanks.

**Comment by YesterdayxD** [comment]
@dcmrlee I have same problem with you.But i don't understand that how to solve the problem finally.Have you solve it?

**Comment by sharkdtu** [comment]
I have same problem too. But `SyncReplicasOptimizer ` was deprecated, and will not be fixed.

**Comment by 0chandansharma** [comment]
>>this problem happens because you are training more steps the what you have put in configuration file.

**Comment by shanshanpt** [comment]
> I have same problem too. But `SyncReplicasOptimizer ` was deprecated, and will not be fixed.

+1
