### ISSUE TITLE
Tensorflow inference on Android, can't find 'Iterator' op. No OpKernel was registered to support Op

### ISSUE THREAD

**Issue by gerardocervantes8** [tensorflow/tensorflow#20846]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: Source
- **TensorFlow version (use command below)**: 1.8.0 (For training and for creating the .so and .jar files)
- **Python version**: Python 3.5.2
- **Bazel version (if compiling from source)**: 0.14.1
- **GCC/Compiler version (if compiling from source)**: gcc version 5.4.0
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: None, running using CPU
- **Android Studio**: 3.1.3
- **Android NDK**: 14b
- **Andorid SDK**: v28
- **Exact command to reproduce**:

### Describe the problem

I am trying to run a trained Tensorflow model on an Android device.  The model I am trying to run on the android mobile device uses an Iterator operation in the inference graph.

I am compiling from source using:
`bazel build -c opt --copt=-D__ANDROID_TYPES_FULL__ //tensorflow/contrib/android:libtensorflow_inference.so --crosstool_top=//external:android/crosstool --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --cpu=armeabi-v7a`

17.2 MB (.so file)
I can load the graph and use the feed method from TensorFlowInferenceInterface, but whenever I try to make a prediction by using a run method from the  TensorFlowInferenceInterface.  I get the "java.lang.IllegalArgumentException: No OpKernel was registered to support Op 'Iterator' with these attrs." error.

I asked on Stackoverflow here https://stackoverflow.com/questions/51331474/tensorflow-inferences-on-android-cant-find-iterator-op-no-opkernel-was-regi but I believe this might be a better place to ask because this appears to be a bug.

I am compiling from source using the D__ANDROID_TYPES_FULL__ so I would expect it to be able to find the iterator operation, which is why I believe it's a bug.  

I am able to run this using a Python/Tensorflow script on my laptop, but am unable to make it run on an Android device.  I give the python script I use to run the model below.

 I tried attaching the frozen model that I run in the code, but I couldn't attach on Github because the file size was too big.  The model was made from using this code: https://github.com/tensorflow/nmt and saving the model when making an inference.
### Source code / logs

This the error I get in Android Studio
```
I/TensorFlowInferenceInterface: Checking to see if TensorFlow native methods are already loaded
    E/art: No implementation found for long org.tensorflow.contrib.android.RunStats.allocate() (tried Java_org_tensorflow_contrib_android_RunStats_allocate and Java_org_tensorflow_contrib_android_RunStats_allocate__)
    I/TensorFlowInferenceInterface: TensorFlow native methods not found, attempting to load via tensorflow_inference
    I/TensorFlowInferenceInterface: Successfully loaded TensorFlow native methods (RunStats error may be ignored)
    I/TensorFlowInferenceInterface: Model load took 764ms, TensorFlow version: 1.8.0
    I/TensorFlowInferenceInterface: Successfully loaded model from 'file:///android_asset/laptop_frozen_graph_init_tables.pb'
    E/TensorFlowInferenceInterface: Failed to run TensorFlow inference with inputs:[batch_size, src_data], outputs:[index_to_string_Lookup]
    E/AndroidRuntime: FATAL EXCEPTION: Thread-5769
                      Process: com.example.student.projecttest, PID: 6805
                      java.lang.IllegalArgumentException: No OpKernel was registered to support Op 'Iterator' with these attrs.  Registered devices: [CPU], Registered kernels:
                        <no registered kernels>
    
                      	 [[Node: Iterator = Iterator[container="infer", output_shapes=[[?,?], [?]], output_types=[DT_INT32, DT_INT32], shared_name=""]()]]
                          at org.tensorflow.Session.run(Native Method)
                          at org.tensorflow.Session.access$100(Session.java:48)
                          at org.tensorflow.Session$Runner.runHelper(Session.java:298)
                          at org.tensorflow.Session$Runner.run(Session.java:248)
                          at org.tensorflow.contrib.android.TensorFlowInferenceInterface.run(TensorFlowInferenceInterface.java:228)
                          at org.tensorflow.contrib.android.TensorFlowInferenceInterface.run(TensorFlowInferenceInterface.java:197)
                          at org.tensorflow.contrib.android.TensorFlowInferenceInterface.run(TensorFlowInferenceInterface.java:187)
                          at com.example.student.projecttest.MainActivity.translateToFrench(MainActivity.java:79)
                          at com.example.student.projecttest.MainActivity$1$1.run(MainActivity.java:42)
```

This is the code I use to run the model on my laptop
```
import tensorflow as tf

def load_graph(frozen_graph_filename):
    # We load the protobuf file from the disk and parse it to retrieve the 
    # unserialized graph_def
    with tf.gfile.GFile(frozen_graph_filename, "rb") as f:
        graph_def = tf.GraphDef()
        graph_def.ParseFromString(f.read())

    # Then, we import the graph_def into a new Graph and returns it 
    with tf.Graph().as_default() as graph:
        # The name var will prefix every op/nodes in your graph
        # Since we load everything in a new graph, this is not needed
        tf.import_graph_def(graph_def, name="prefix")
    return graph

tgt_eos = '</s>'
frozen_model_path =  'laptop_frozen_graph_init_tables.pb'
graph = load_graph(frozen_model_path)

with tf.Session(graph = graph) as sess:

  #Get input tensors
  src_file_placeholder = sess.graph.get_tensor_by_name("prefix/src_data:0")
  batch_size_placeholder = sess.graph.get_tensor_by_name("prefix/batch_size:0")
  
  
  #Initialize tables
  init_tables_operation = sess.graph.get_operation_by_name("prefix/init_all_tables")
  sess.run(init_tables_operation)
  
  #Get init iterator operation
  make_iterator_operation = sess.graph.get_operation_by_name("prefix/MakeIterator")
  
  
  src_data = ['Bonjour', 'tout', 'le', 'monde', 'c', '\'', 'est', 'vrai', tgt_eos]
  
  #Make_iterator has to be fed with src_data
  sess.run(make_iterator_operation, feed_dict={
            src_file_placeholder: src_data,
            batch_size_placeholder: 32
        })

  #Get output tensor
  output0 = graph.get_tensor_by_name("prefix/index_to_string_Lookup:0")
  
  #Iterate through input until we run out of input
  try:
    while True:
      txt_output = sess.run(output0)
      print(txt_output)
  except tf.errors.OutOfRangeError:
      print('Done inferencing')
```

This is the code I use in Android Studio which produces a very error to the one mentioned above.
```
        String modelName = "laptop_frozen_graph_init_tables.pb";
        String fullModelPath = "file:///android_asset/" + modelName;

        AssetManager assetManager = getAssets();

        TensorFlowInferenceInterface inferenceInterface = new TensorFlowInferenceInterface(assetManager, fullModelPath);
        Graph graph = inferenceInterface.graph();

        inferenceInterface.run(new String[]{"init_all_tables"});
```

**Comment by NPetsky** [comment]
Hello @gerardocervantes8, I don't know about building with bazel for android but if you use the makefile building for android (tensorflow/contrib/makefile) you need to include the file tensorflow/core/kernels/data/iterator_ops.cc file in the tf_op_files.txt before compiling
Then the OpKernel for the 'Iterator' op should be included in the library

**Comment by tensorflowbutler** [comment]
Nagging Assignee @robieta: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.
