### ISSUE TITLE
MonitoredTrainingSession is not handling the dummy_QueueRunner cleanly?

### ISSUE THREAD

**Issue by tsoi2** [tensorflow/tensorflow#20844]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  Linux Fedora Red Hat Enterprise Linux Server release 7.5 (Maipo)
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.7.0
- **Python version**: 3.6.3
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**: CUDA9.0/ CUDNN7.0
- **GPU model and memory**:  P100 16GB
- **Exact command to reproduce**:  bash run.sh

### Describe the problem
I am using the MonitoredTrainingSession to test a simple script (base on [this](https://github.com/tmulc18/Distributed-TensorFlow-Guide/blob/master/Synchronous-SGD/ssgd.py) of synchronized distributed training/multi_gpu training. When the training is finished, the session always throws out Exception (CancelledError) in thread QueueRunnerThread.  I suspect this is related to QueueRunner is not handled cleanly when sess.close() is called. 

### Source code / logs
`REPLICAS_TO_AGGREGATE = 1
def main():
    # Configure
    config=tf.ConfigProto(allow_soft_placement=True, log_device_placement=False)
    config.gpu_options.allow_growth = True

    # Server Setup
    cluster = tf.train.ClusterSpec({
        'ps':['localhost:2222'],
        'worker':['localhost:2223']#,'localhost:2224']
        }) #allows this node know about all other nodes
    if FLAGS.job_name == 'ps': #checks if parameter server
        with tf.device('/job:ps/task:0/cpu:0'):
            server = tf.train.Server(cluster,
                            job_name="ps",
                            task_index=FLAGS.task_index,
                            config=config)
            server.join()
    else: #it must be a worker server
        is_chief = (FLAGS.task_index == 0) #checks if this is the chief node
        with tf.device('/gpu:%d' % (FLAGS.task_index)):
            server = tf.train.Server(cluster,
                    job_name="worker",
                    task_index=FLAGS.task_index,
                    config=config)
    
        # Graph
        # ps_device = "/job:ps/task:0/cpu:0"
        worker_device = "/job:worker/task:%d/gpu:%d" % (FLAGS.task_index, FLAGS.task_index)
        with tf.device(tf.train.replica_device_setter(ps_tasks=1,
                       #ps_device=ps_device,
                       worker_device=worker_device)):

            a = tf.Variable(tf.constant(0.,shape=[2]),dtype=tf.float32)
            b = tf.Variable(tf.constant(0.,shape=[2]),dtype=tf.float32)
            c= a+b

            global_step = tf.Variable(0,dtype=tf.int32,trainable=False,name='global_step')
            target = tf.constant(100.,shape=[2],dtype=tf.float32)
            loss = tf.reduce_mean(tf.square(c-target))

            # create an optimizer then wrap it with SynceReplicasOptimizer
            optimizer = tf.train.GradientDescentOptimizer(.0001)
            optimizer1 = tf.train.SyncReplicasOptimizer(optimizer,
                     replicas_to_aggregate=REPLICAS_TO_AGGREGATE, total_num_replicas=REPLICAS_TO_AGGREGATE)
      
            opt = optimizer1.minimize(loss,global_step=global_step) # averages gradients
            #opt = optimizer1.minimize(REPLICAS_TO_AGGREGATE*loss,
            #                           global_step=global_step) # hackily sums gradients

        # Session
        sync_replicas_hook = optimizer1.make_session_run_hook(is_chief)
        stop_hook = tf.train.StopAtStepHook(last_step=10)
        hooks = [sync_replicas_hook,stop_hook]

        # Monitored Training Session
        with tf.train.MonitoredTrainingSession(master = server.target, 
              is_chief=is_chief,
              config=config,
              hooks=hooks,
              stop_grace_period_secs=10) as sess:

            print('Starting training on worker %d'%FLAGS.task_index)
            while not sess.should_stop():
                _,r,gs=sess.run([opt,c,global_step])
                print(r,'step: ',gs,'worker: ',FLAGS.task_index)
                # if is_chief: time.sleep(1)
                time.sleep(1)
            print('Done',FLAGS.task_index)
  
            time.sleep(10) #grace period to wait before closing session
            #sess.close() # is uncomment this, it will raise error 'Session is already closed' after the CanceledError 
        print('Session from worker %d closed cleanly'%FLAGS.task_index)

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    # Flags for defining the tf.train.ClusterSpec
    parser.add_argument(
        "--job_name",
        type=str,
        default="",
        help="One of 'ps', 'worker'"
      )
    # Flags for defining the tf.train.Server
    parser.add_argument(
        "--task_index",
        type=int,
        default=0,
        help="Index of task within the job"
      )
    FLAGS, unparsed = parser.parse_known_args()
    print(FLAGS.task_index)
    main()`

**************** I use the following script to run the code 
`#!/bin/bash -e
export CUDA_VISIBLE_DEVICES='' 
python text_multi_gpu.py --job_name="ps" --task_index=0 &
export CUDA_VISIBLE_DEVICES='0' 
python text_multi_gpu.py --job_name="worker" --task_index=0 &
export CUDA_VISIBLE_DEVICES='1'
python text_multi_gpu.py --job_name="worker" --task_index=1`

****************** Below is part of the log
`[0.15988803 0.15988803] step:  8 worker:  0
[0.17985605 0.17985605] step:  9 worker:  0
Done 0
Exception in thread QueueRunnerThread-dummy_queue-sync_token_q_EnqueueMany:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/python3_env/lib64/python3.6/site-packages/tensorflow/python/training/queue_runner_impl.py", line 268, in _run
    coord.request_stop(e)
  File "/home/python3_env/lib64/python3.6/site-packages/tensorflow/python/training/coordinator.py", line 213, in request_stop
    six.reraise(*sys.exc_info())
  File "/home/python3_env/lib64/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/python3_env/lib64/python3.6/site-packages/tensorflow/python/training/queue_runner_impl.py", line 252, in _run
    enqueue_callable()
  File "/home/python3_env/lib64/python3.6/site-packages/tensorflow/python/client/session.py", line 1249, in _single_operation_run
    self._call_tf_sessionrun(None, {}, [], target_list, None)
  File "/home/python3_env/lib64/python3.6/site-packages/tensorflow/python/client/session.py", line 1420, in _call_tf_sessionrun
    status, run_metadata)
  File "/home/python3_env/lib64/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.CancelledError: Step was cancelled by an explicit call to "Session::Close()".

Session from worker 0 closed cleanly`

**Comment by karmel** [comment]
Sorry, I'm having a little trouble understanding the problem here-- you should not need to explicitly close the session in the `with ...` block, so the version with sess.close() commented out is the correct one. Is there a problem still with that version?

**Comment by tsoi2** [comment]
@karmel 
Yes, the problem shown above still happens when "sess.close()" is commented. 
If "sess.close()" is uncommented, there is another error as you can expect in addition to the Error I shown above.

**Comment by tsoi2** [comment]
@karmel 
any clue? Thank for your help.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @karmel: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by karmel** [comment]
Unfortunately, it is hard to debug from a distance. Is there any reason you are using the deprecated Queue API rather than the newer [Dataset API](https://www.tensorflow.org/guide/datasets)

**Comment by dulex123** [comment]
I have the same issue, any ideas?

**Comment by tensorflowbutler** [comment]
It has been 15 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
It has been 29 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by wu-play** [comment]
@tsoi2 how do you fix this problem? I met the same problem..
