### ISSUE TITLE
tensorflow 1.9 still asks for cuda 9.0 though i have 9.2

### ISSUE THREAD

**Issue by steathy** [tensorflow/tensorflow#20865]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: windows 10
- **TensorFlow installed from (source or binary)**: pip3
- **TensorFlow version (use command below)**: 1.9
- **Python version**: 3.6.6
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**: 
- **CUDA/cuDNN version**: 9.2
- **GPU model and memory**:
- **Exact command to reproduce**:

When importing tensorflow it fails and asks for cuda 9.0 dll
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Python36\lib\site-packages\tensorflow\__init__.py", line 22, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "D:\Python36\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "D:\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 30, in <module>
    self_check.preload_check()
  File "D:\Python36\lib\site-packages\tensorflow\python\platform\self_check.py", line 82, in preload_check
    % (build_info.cudart_dll_name, build_info.cuda_version_number))
ImportError: Could not find 'cudart64_90.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Download and install CUDA 9.0 from this URL: https://developer.nvidia.com/cuda-toolkit

**Comment by FarhanTejani** [comment]
The PyPI (pip) versions of TensorFlow are still [built against CUDA 9.0](https://github.com/tensorflow/tensorflow/pull/19474#issuecomment-394934043). You will have to build from source if you want to build against CUDA 9.2. See [here](https://github.com/tensorflow/tensorflow/issues/18906) for lots of discussion on how to do this.

**Comment by steathy** [comment]
Thanks. Is there a tutorial of doing that step by step?

**Comment by Mukundan314** [comment]
Tutorial for installing tensorflow from source is available [here](https://www.tensorflow.org/install/install_sources)

**Comment by steathy** [comment]
Thanks. I tried and failed on windows as well. Maybe I'll just wait till pip version gets updated. Hope it will happen soon.

**Comment by hadim** [comment]
If you are building on Linux, feel free to use the following project that make TF compilation super easy: https://github.com/hadim/docker-tensorflow-builder

**Comment by steathy** [comment]
Thanks for the advice. Unfortunately I'm running it on Windows now. Besides is running tensorflow on linux faster than that on windows?

**Comment by scottgigante** [comment]
Is there an ETA for a CUDA 9.2 Windows build?

**Comment by tensorflowbutler** [comment]
Nagging Assignee @poxvoculi: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by zhanwenchen** [comment]
If anyone is interested in an alternative tutorial for building from source, I wrote one for [cuda9.0](https://medium.com/@zhanwenchen/speed-up-learning-by-building-tensorflow-gpu-from-source-on-ubuntu-d03bb4e06b23) and another for [cuda9.2](https://medium.com/@zhanwenchen/install-cuda-9-2-and-cudnn-7-1-for-tensorflow-pytorch-gpu-on-ubuntu-16-04-1822ab4b2421).

**Comment by tensorflowbutler** [comment]
Nagging Assignee @poxvoculi: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by martinwicke** [comment]
It's as @FarhanTejani said.
