### ISSUE TITLE
Cannot allocate memory for the interpreter

### ISSUE THREAD

**Issue by sukkyoung** [tensorflow/tensorflow#20872]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: example source code and custom model
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: ubuntu 16.04
- **TensorFlow installed from (source or binary)**:source
- **TensorFlow version (use command below)**:github master branch
- **Python version**: 3.6.3
- **Bazel version (if compiling from source)**:0.11.0
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:

### Describe the problem

I'm trying to build & run tensorflow lite example using custom model.
Build is ok, but error occurs running this program.
why this error occur?

`root@90f212114f89:/tensorflow# bazel-bin/tensorflow/contrib/lite/examples/minimal/minimal /root/DNNSE/model/tflite_model.lite`
`tensorflow/contrib/lite/kernels/reduce.cc:107 current >= 0 && current < input_num_dims was not true.`
`tensorflow/contrib/lite/kernels/reduce.cc:107 current >= 0 && current < input_num_dims was not true.`
`tensorflow/contrib/lite/kernels/reduce.cc:107 current >= 0 && current < input_num_dims was not true.`
`tensorflow/contrib/lite/kernels/reduce.cc:107 current >= 0 && current < input_num_dims was not true.`
`Node 8 failed to prepare.`

`Error at tensorflow/contrib/lite/examples/minimal/minimal.cc:59`

Used model is custom model training on tensorflow and convert tensorflow lite using toco.
I think some error in the process of converting model to lite.
But i don't know how to debugging it.

I also try to run in android example.
There are same error.

E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: android.example.com.tflitecamerademo, PID: 13202
                  java.lang.RuntimeException: Unable to start activity ComponentInfo{android.example.com.tflitecamerademo/com.example.android.tflitecamerademo.CameraActivity}: java.lang.NullPointerException: Internal error: Cannot allocate memory for the interpreter: tensorflow/contrib/lite/kernels/reduce.cc:107 current >= 0 && current < input_num_dims was not true.tensorflow/contrib/lite/kernels/reduce.cc:107 current >= 0 && current < input_num_dims was not true.tensorflow/contrib/lite/kernels/reduce.cc:107 current >= 0 && current < input_num_dims was not true.tensorflow/contrib/lite/kernels/reduce.cc:107 current >= 0 && current < input_num_dims was not true.Node 8 failed to prepare.

                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2875)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2950)
                      at android.app.ActivityThread.-wrap11(Unknown Source:0)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1616)
                      at android.os.Handler.dispatchMessage(Handler.java:105)
                      at android.os.Looper.loop(Looper.java:164)
                      at android.app.ActivityThread.main(ActivityThread.java:6759)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)
                   Caused by: java.lang.NullPointerException: Internal error: Cannot allocate memory for the interpreter: tensorflow/contrib/lite/kernels/reduce.cc:107 current >= 0 && current < input_num_dims was not true.tensorflow/contrib/lite/kernels/reduce.cc:107 current >= 0 && current < input_num_dims was not true.tensorflow/contrib/lite/kernels/reduce.cc:107 current >= 0 && current < input_num_dims was not true.tensorflow/contrib/lite/kernels/reduce.cc:107 current >= 0 && current < input_num_dims was not true.Node 8 failed to prepare.

                      at org.tensorflow.lite.NativeInterpreterWrapper.createInterpreter(Native Method)
                      at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:75)
                      at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:54)
                      at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:114)
                      at com.example.android.tflitecamerademo.ImageClassifier.<init>(ImageClassifier.java:92)
                      at com.example.android.tflitecamerademo.ImageClassifierQuantizedMobileNet.<init>(ImageClassifierQuantizedMobileNet.java:38)
                      at com.example.android.tflitecamerademo.Camera2BasicFragment.onActivityCreated(Camera2BasicFragment.java:332)
                      at android.app.Fragment.performActivityCreated(Fragment.java:2620)
                      at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1296)
                      at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2415)
                      at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2194)
                      at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2148)
                      at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2049)
                      at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3044)
                      at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2991)
                      at android.app.FragmentController.dispatchActivityCreated(FragmentController.java:178)
                      at android.app.Activity.performCreateCommon(Activity.java:6974)
                      at android.app.Activity.performCreate(Activity.java:6982)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2828)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2950) 
                      at android.app.ActivityThread.-wrap11(Unknown Source:0) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1616) 
                      at android.os.Handler.dispatchMessage(Handler.java:105) 
                      at android.os.Looper.loop(Looper.java:164) 
                      at android.app.ActivityThread.main(ActivityThread.java:6759) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770) 
Application terminated.

**Comment by shashishekhar** [comment]
@sukkyoung : On which device are you running this?

**Comment by sukkyoung** [comment]
@shashishekhar I used LG G7. (android ver.8.0.0)

**Comment by sukkyoung** [comment]
Can I share only tf.reduce_* ops ??
I used only tf.reduce_mean.

**Comment by shashishekhar** [comment]
@sukkyoung :
It seems the model has a bug, I am trying to see if there is a bug in our conversion script.
Can you attach:
1. The original graphDef or saved model that you used to convert the model.
2.  The command/script that you used to convert the model.

**Comment by sukkyoung** [comment]
I attach original graph and frozen graph using freeze_graph script

1. freeze graph
bazel build tensorflow/python/tools:freeze_graph && \
bazel-bin/tensorflow/python/tools/freeze_graph \
--input_graph=/root/DNNSE/model/graph.pb \
--input_checkpoint=/root/DNNSE/model/epoch_71.ckpt-71 \
--output_graph=/root/DNNSE/model/frozen_graph.pb \
--output_node_names=Mean

2. toco
[graph.tar.gz](https://github.com/tensorflow/tensorflow/files/2217777/graph.tar.gz)

bazel build tensorflow/contrib/lite/toco:toco && \
toco --graph_def_file=/root/DNNSE/model/frozen_graph.pb \
--input_format=TENSORFLOW_GRAPHDEF \
--output_format=TFLITE \
--output_file=/root/DNNSE/model/tflite_model.lite \
--inference_type=FLOAT \
--input_type=FLOAT \
--input_arrays=x \
--output_arrays=Mean \
--input_shapes=64,257

**Comment by shashishekhar** [comment]
@sukkyoung : It seems that your model has x and y as inputs, if you specify both x,y in input_arrays then it should work.

**Comment by sukkyoung** [comment]
@shashishekhar  Thank you! it works well.

**Comment by SreehariRamMohan** [comment]
@shashishekhar How do you specify the X and y in input_arrays? Do you list their sizes? Which command do you use to create the tf lite file. I am running into the following issue: 

`Caused by: com.google.firebase.ml.common.FirebaseMLException: Internal error has occurred when executing Firebase ML tasks
W/System.err:     at com.google.android.gms.internal.firebase_ml.zzhg.zza(Unknown Source)
W/System.err: 	... 5 more
W/System.err: Caused by: java.lang.NullPointerException: Can not allocate memory for the interpreter
W/System.err:     at org.tensorflow.lite.NativeInterpreterWrapper.createInterpreter(Native Method)
W/System.err:     at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:63)
W/System.err:     at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:51)
W/System.err:     at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:90)
W/System.err:     at com.google.android.gms.internal.firebase_ml.zzif.zzfm(Unknown Source)
W/System.err:     at com.google.android.gms.internal.firebase_ml.zzhr.zzfp(Unknown Source)
W/System.err:     at com.google.android.gms.internal.firebase_ml.zzhr.call(Unknown Source)
W/System.err:     at com.google.android.gms.internal.firebase_ml.zzhg.zza(Unknown Source)
W/System.err: 	... 5 more`
