### ISSUE TITLE
Freezing + fake quantization of graph

### ISSUE THREAD

**Issue by Basil-M** [tensorflow/tensorflow#20886]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Custom code
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: Source (v1.8) / binary (v1.9)
- **TensorFlow version (use command below)**:  v1.8.0-0-g93bc2e2072 1.8.0 AND v1.9.0-0-g25c197e023 1.9.0
- **Python version**: 3.6 
- **Bazel version (if compiling from source)**: 
- **GCC/Compiler version (if compiling from source)**: (result of gcc -v) gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9) 
- **CUDA/cuDNN version**: Not used
- **GPU model and memory**: Not used
- **Exact command to reproduce**: Code given below

### Describe the problem
Problem described [here](https://stackoverflow.com/questions/51327204/freezing-quantizing-fake-quantized-graph), but didn't have any luck; essentially, I cannot freeze a graph which has been fake quantized using [tf.contrib.quantize.create_training_graph()](https://github.com/tensorflow/tensorflow/blob/r1.8/tensorflow/contrib/quantize/python/quantize_graph.py). I have a sample below (there may be a better way to add a freezing operation at the end of the [graph quantization test](https://github.com/tensorflow/tensorflow/blob/r1.8/tensorflow/contrib/quantize/python/quantize_graph.py) script).

The code shown spits out the following error (or variants dependent on architecture):

> ValueError: Input 0 of node import/weights_quant/AssignMinLast was passed float from import/weights_quant/min:0 incompatible with expected float_ref

I may be doing something wrong - this arises regardless of which order I apply the creation of training/eval graphs and which of the 3 methods I use for freezing the graph. I also tried the fixes [here](https://github.com/davidsandberg/facenet/issues/161) to no avail.

### Source code / logs
```
import tensorflow as tf


def conv_simple(_input):
    _input_r = tf.reshape(_input, shape=[-1, 28, 28, 1])
    _conv1 = tf.nn.conv2d(_input_r, tf.Variable(tf.random_normal([3, 3, 1, 64], stddev=0.1)), strides=[1, 1, 1, 1],
                          padding='SAME')
    _conv2 = tf.nn.bias_add(_conv1, tf.Variable(tf.random_normal([64], stddev=0.1)))
    _conv3 = tf.nn.relu(_conv2)
    _pool = tf.nn.max_pool(_conv3, ksize=[1, 2, 2, 1], strides=[1, 2, 2, 1], padding='SAME')
    _dense = tf.reshape(_pool, [-1, 14 * 14 * 64])
    _out = tf.add(tf.matmul(_dense, tf.Variable(tf.random_normal([14 * 14 * 64, 10], stddev=0.1))),
                  tf.Variable(tf.random_normal([10], stddev=0.1)), name='Output')
    out = {
        'input_r': _input_r, 'conv1': _conv1, 'conv2': _conv2, 'conv3': _conv3
        , 'pool': _pool, 'dense': _dense, 'out': _out
    }
    return out


# tf Graph input
x = tf.placeholder(tf.float32, [None, 784], name='X')
_pred = conv_simple(x)['out']

tf.contrib.quantize.create_training_graph()

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

    # FREEZE GRAPH
    output_graph_def = sess.graph.as_graph_def()
    input_names = ["X"]
    output_names = ["Output"]
    LOG_DIR = '/some/path/to/log/dir/'

    output_graph_def = tf.graph_util.convert_variables_to_constants(
        sess,  # The session is used to retrieve the weights
        output_graph_def,  # The graph_def is used to retrieve the nodes
        output_names  # The output node names are used to select the useful nodes,
    )

    g = tf.import_graph_def(output_graph_def)
```

**Comment by Basil-M** [comment]
I think this issue may be fixed with correct usage of tf.contrib.create_eval_graph()
There are currently two issues I have there:

1. If I use create_eval_graph() after create_training_graph() it doesn't correctly change the graph
2. If I freeze the graph after create_eval_graph() (having not applied create_training_graph()) it fails, giving the following error:

> tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value Output/weights_quant/min
> [[Node: _retval_Output/weights_quant/min_0_53 = _Retval[T=DT_FLOAT, index=53, _device="/job:localhost/replica:0/task:0/device:CPU:0"](Output/weights_quant/min)]]

Intuitively I feel create_eval_graph() applied after create_training_graph() should work and also have values initialised correctly but it doesn't want to play nice!

I also thought it may be I need to run more data through the graph after creating the eval_graph but this did not work.

**Comment by meixiaofeng** [comment]
Got the same problem,don't know how to solve.

**Comment by CanoeFZH** [comment]
Just do not use tf.contrib.xxx in the case that you will try to load graph.

**Comment by meixiaofeng** [comment]
I've solved the problem by using create_training_graph() after construction or building of the graph and before running the session while training, and using create_eval_graph()  after the construction of the graph and before converting variables to constants while freezing the graph.

**Comment by ZJZheng** [comment]
@meixiaofeng Could you please post your code? I have the same issue and still wondering where to put the quantization functions. Thanks.

**Comment by sxsxsx** [comment]
@meixiaofeng hello,  while freezing and deploying the graph for inference,  could you tell me how to  put create_eval_graph() right after the construction of the graph and right before converting variables in the graph to constants. Thanks.

**Comment by sxsxsx** [comment]
@Basil-M hi, I meet the same problem. Have you solved the problem?

**Comment by krworks** [comment]
Same issue here as well.  The only thing I can reason out of this is it's just not designed to manipulate the altered training graph to an altered eval graph.  It may be worth trying to extract the weights out of the training graph and then move them into a newly constructed eval graph before attempting this.  I believe that the API is designed for use with the Estimator API but at this moment I'm only in guessing mode.

@ZJPUBG I'm converting my model from Keras to a TensorFlow API one because I couldn't figure out how to utilize these functions with Keras as well.

**Comment by v-ilin** [comment]
I did not get success with resolving the error.
@meixiaofeng it will be very helpful if you post your code here.

**Comment by meixiaofeng** [comment]
I solved this problem by 
following the document here,https://github.com/tensorflow/models/blob/master/research/slim/nets/mobilenet_v1.md .While training, I refer to this file https://github.com/tensorflow/models/blob/master/research/slim/nets/mobilenet_v1_train.py ,and while for deployment, I refer code here https://github.com/tensorflow/models/blob/master/research/slim/nets/mobilenet_v1_eval.py .This is actually very simple!

**Comment by hzhyhx1117** [comment]
Got same problems. 
The only solution is, as I think, is reconstruct your graph when you want to make evaluation.

**Comment by chutongz** [comment]
@hzhyhx1117 Hi, I have same error when using create_training_graph() and create_eval_graph().
I have a question about reconstructing the graph. Do you mean to restart a session and reload the checkpoint to evaluate?
Because I am currently use this method but still can not work, when I use 'toco' to convert the graph, it gave me error as bellow:
`ValueError: Input 0 of node Lenet/conv1/weights_quant/AssignMinLast was passed float from Lenet/conv1/weights_quant/min:0 incompatible with expected float_ref.`
Did you use tf.reset_default_graph() to reset the graph or something else to solve it? I really appreciate it if you could give any instruction in detail.

**Comment by ved27** [comment]
Wait, I used layers from slim instead of the following

**Comment by Maximilianxu** [comment]
> @hzhyhx1117 Hi, I have same error when using create_training_graph() and create_eval_graph().
> I have a question about reconstructing the graph. Do you mean to restart a session and reload the checkpoint to evaluate?
> Because I am currently use this method but still can not work, when I use 'toco' to convert the graph, it gave me error as bellow:
> `ValueError: Input 0 of node Lenet/conv1/weights_quant/AssignMinLast was passed float from Lenet/conv1/weights_quant/min:0 incompatible with expected float_ref.`
> Did you use tf.reset_default_graph() to reset the graph or something else to solve it? I really appreciate it if you could give any instruction in detail.

Hi, I have the exactly same error like yours. Did you solve this problem? (I used code from Pocketflow and then converted the checkpoint file to a pb file. After that I use TFLite converter, it turns out this error.)

**Comment by michalo2882** [comment]
The problem is, you cannot apply `create_eval_graph` to the graph on which you already called `create_training_graph`.
To solve this, I save variables after training with fake quantization using `tf.train.Saver.save`.
Then I simply create a new graph from scratch, call `create_eval_graph` and finally restore the variables using `tf.train.Saver.restore`.
Remeber to call execute `tf.global_variables_initializer()` after both `create_training_graph` and `create_eval_graph`.

**Comment by YaroslavSchubert** [comment]
Fixed `tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value Output/weights_quant/min` error by adding `tf.global_variables_initializer()` after `create_eval_graph`

**Comment by ignvinay** [comment]
I am also getting same error, even though i used create_training_graph and initailaized using tf.global_variables_initializer() . The tflite gives errors as below .
toco --graph_def_file=frozen_graph_quantize.pb --output_file=tflite_model.tflite --input_format=TENSORFLOW_GRAPHDEF --output_format=TFLITE  --inference_type=QUANTIZED_UINT8 --input_shape="1,784" --input_array=input_x --output_array=ArgMax --std_dev_value 127 --mean_value 255 --default_ranges_min 0  --default_ranges_max 6  --inference_input_type=QUANTIZED_UINT8



2019-07-15 17:02:53.729357: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-07-15 17:02:53.731481: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0
2019-07-15 17:02:53.732792: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N
2019-07-15 17:02:53.734200: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3010 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1050, pci bus id: 0000:01:00.0, compute capability: 6.1)
Traceback (most recent call last):
  File "C:\Users\GF63\.conda\envs\tflite\lib\site-packages\tensorflow\python\framework\importer.py", line 426, in import_graph_def
    graph._c_graph, serialized, options)  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input 0 of node conv1/weights_quant/AssignMinLast was passed float from conv1/weights_quant/min:0 incompatible with expected float_ref.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\GF63\.conda\envs\tflite\Scripts\toco-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\GF63\.conda\envs\tflite\lib\site-packages\tensorflow\lite\python\tflite_convert.py", line 442, in main
    app.run(main=run_main, argv=sys.argv[:1])
  File "C:\Users\GF63\.conda\envs\tflite\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "C:\Users\GF63\.conda\envs\tflite\lib\site-packages\tensorflow\lite\python\tflite_convert.py", line 438, in run_main
    _convert_model(tflite_flags)
  File "C:\Users\GF63\.conda\envs\tflite\lib\site-packages\tensorflow\lite\python\tflite_convert.py", line 122, in _convert_model
    converter = _get_toco_converter(flags)
  File "C:\Users\GF63\.conda\envs\tflite\lib\site-packages\tensorflow\lite\python\tflite_convert.py", line 109, in _get_toco_converter
    return converter_fn(**converter_kwargs)
  File "C:\Users\GF63\.conda\envs\tflite\lib\site-packages\tensorflow\lite\python\lite.py", line 274, in from_frozen_graph
    _import_graph_def(graph_def, name="")
  File "C:\Users\GF63\.conda\envs\tflite\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\Users\GF63\.conda\envs\tflite\lib\site-packages\tensorflow\python\framework\importer.py", line 430, in import_graph_def
    raise ValueError(str(e))
ValueError: Input 0 of node conv1/weights_quant/AssignMinLast was passed float from conv1/weights_quant/min:0 incompatible with expected float_ref.

 I tried inspecting the graph and found that float operations are used in operations as below

![Uploading sample_quantize.png…]()
![Uploading sample_quantize.png…]()
![Uploading sample_quantize.png…]()

**Comment by ignvinay** [comment]
Any suggestions please !

**Comment by ved27** [comment]
Hi @ignvinay 

are you getting the same toco error for the case of using create eval graph ?

**Comment by ignvinay** [comment]
Yeah @ved27 .
Any suggestions to resolve this ?

**Comment by ved27** [comment]
Hi 

So , can you post the code ? or a snippet of that

**Comment by ignvinay** [comment]
Freezing of buffer is as follows : 

`with tf.Session() as sess:
    
    y_conv, keep_prob = deepnn(x)
    with tf.name_scope('loss'):
      cross_entropy = tf.losses.sparse_softmax_cross_entropy(
        labels=y_, logits=y_conv)
      cross_entropy = tf.reduce_mean(cross_entropy)

    graph = tf.get_default_graph()
    
    with graph.as_default():
      tf.contrib.quantize.create_training_graph(input_graph=graph,
                                          quant_delay=200) #2000000
    
    init = tf.global_variables_initializer()

    with tf.name_scope('adam_optimizer'):
      train_step = tf.train.AdamOptimizer(1e-4).minimize(cross_entropy)

    #with tf.name_scope('accuracy1'):
    correct_prediction = tf.equal(tf.argmax(y_conv, 1), y_)
    correct_prediction = tf.cast(correct_prediction, tf.float32)
    accuracy = tf.reduce_mean(correct_prediction,name='accuracy')
    saver = tf.train.Saver(sharded=True)
    sess.run(init)
    sess.run(tf.global_variables_initializer())
    
    for i in range(200):
      batch = mnist.train.next_batch(50)
      if i % 100 == 0:
        
        train_accuracy = accuracy.eval(feed_dict={
            x: batch[0], y_: batch[1], keep_prob: 1.0})
        print('step %d, training accuracy %g' % (i, train_accuracy))
      train_step.run(feed_dict={x: batch[0], y_: batch[1], keep_prob: 0.5})
    
    
    print('test accuracy %g' % accuracy.eval(feed_dict={
        x: mnist.test.images, y_: mnist.test.labels, keep_prob: 1.0}))
    
   
    #tf.saved_model.simple_save(sess,'export_1',inputs={"input_x":x},outputs={"ArgMax":y_conv})
    #builder = tf.saved_model.builder.SavedModelBuilder('export_path')
    #signature = predict_signature_def(inputs={"input_x":x},outputs={"ArgMax":y_conv})
    # using custom tag instead of: tags=[tag_constants.SERVING]
    #builder.add_meta_graph_and_variables(sess=sess,
    #                                 tags=["myTag"],
    #                                 signature_def_map={'predict': signature})
    #builder.save()
    # this step will take care of frezzing graph 
    gd = sess.graph.as_graph_def()
    out_graph_def = tf.graph_util.convert_variables_to_constants(sess,gd,
                                                 ["ArgMax"])
    
    tf.train.write_graph(out_graph_def,"./", "frozen_train_quantize.pb", as_text=False)`

toco command line is given as above in my post.

**Comment by ignvinay** [comment]
Please let me know how to solve this.

**Comment by ved27** [comment]
Hi ,

Is create_eval_graph(..) used in the above ?

I can suggest you to use the above api after deepcnn() for inference and load from ckpt and save the frozen file

**Comment by ignvinay** [comment]
After deepnn(), called create_training_graph, which will do quantization.
So how can i call create_eval_graph, which is meant for inference.

Can you post your suggested code , please.

**Comment by ignvinay** [comment]
This is not at inference. Its during training.

**Comment by ved27** [comment]
Toco is used for inference . And hence you need a frozen pb file for inference

**Comment by ignvinay** [comment]
The frozen graph generated using tf.train.write_graph(out_graph_def,"./", "frozen_train_quantize.pb", as_text=False)` is incorrect ?

**Comment by ved27** [comment]
As mentioned , the frozen pb file needs to be generated from inference graph

**Comment by ignvinay** [comment]
Introduced additional code as below : 
with tf.Session() as sess:
  inference_graph(sess)


where function is : 

```
def inference_graph(sess):
  # Call the eval rewrite which rewrites the graph in-place with
  # FakeQuantization nodes and fold batchnorm for eval.
  g = tf.get_default_graph()
  tf.contrib.quantize.create_eval_graph(input_graph=g)

  # Save the checkpoint and eval graph proto to disk for freezing
  # and providing to TFLite.
  with open('test', "w") as f:
    f.write(str(g.as_graph_def()))
  saver = tf.train.Saver()
  saver.save(sess, "checkpoint_name")
```

I get the errors as : 
    raise ValueError('Training op found in graph, exiting %s' % train_op_list)
ValueError: Training op found in graph, exiting {'ApplyAdam'}

**Comment by ved27** [comment]
This link for ref.

https://github.com/tensorflow/tensorflow/blob/r1.14/tensorflow/contrib/quantize/README.md

**Comment by ignvinay** [comment]
Same code i used .

**Comment by ved27** [comment]
Try to make training and inference codes in separate files

**Comment by ignvinay** [comment]
Yes, even in new file the same error.
That gradient problem, i am not able remove.

**Comment by ved27** [comment]
Hi ,

do not import from meta as it has info of training .

call your deepnn , followed by create eval graph ; 



- y_conv, keep_prob = deepnn(x)
- graph = tf.get_default_graph()
- tf.contrib.quantize.create_eval_graph(input_graph=graph)

- then create saver and restore 

sess.graph.as_graph_def()
out_graph_def = tf.graph_util.convert_variables_to_constants(sess,gd,
                                             ["Outputnode_name"])

**Comment by ignvinay** [comment]
Got it. Thanks.
But tflite conversion still gives error 
``
(tflite) D:\Vinay\gyrus\models>toco --graph_def_file=frozen_inference_quantize.pb --output_file=tflite_model.tflite --input_format=TENSORFLOW_GRAPHDEF --output_format=TFLITE --inference_type=QUANTIZED_UINT8 --input_shape="1,784" --input_array=input_x --output_array=ArgMax --std_dev_value 127 --mean_value 255 --default_ranges_min 0 --default_ranges_max 6
2019-07-17 22:03:55.657362: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
2019-07-17 22:03:56.502116: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties:
name: GeForce GTX 1050 major: 6 minor: 1 memoryClockRate(GHz): 1.493
pciBusID: 0000:01:00.0
totalMemory: 4.00GiB freeMemory: 3.30GiB
2019-07-17 22:03:56.506268: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2019-07-17 22:03:56.915974: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-07-17 22:03:56.918685: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0
2019-07-17 22:03:56.919975: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N
2019-07-17 22:03:56.921397: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3010 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1050, pci bus id: 0000:01:00.0, compute capability: 6.1)
Traceback (most recent call last):
  File "C:\Users\GF63\.conda\envs\tflite\Scripts\toco-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\GF63\.conda\envs\tflite\lib\site-packages\tensorflow\lite\python\tflite_convert.py", line 442, in main
    app.run(main=run_main, argv=sys.argv[:1])
  File "C:\Users\GF63\.conda\envs\tflite\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "C:\Users\GF63\.conda\envs\tflite\lib\site-packages\tensorflow\lite\python\tflite_convert.py", line 438, in run_main
    _convert_model(tflite_flags)
  File "C:\Users\GF63\.conda\envs\tflite\lib\site-packages\tensorflow\lite\python\tflite_convert.py", line 191, in _convert_model
    output_data = converter.convert()
  File "C:\Users\GF63\.conda\envs\tflite\lib\site-packages\tensorflow\lite\python\lite.py", line 455, in convert
    **converter_kwargs)
  File "C:\Users\GF63\.conda\envs\tflite\lib\site-packages\tensorflow\lite\python\convert.py", line 442, in toco_convert_impl
    input_data.SerializeToString())
  File "C:\Users\GF63\.conda\envs\tflite\lib\site-packages\tensorflow\lite\python\convert.py", line 205, in toco_convert_protos
    "TOCO failed. See console for info.\n%s\n%s\n" % (stdout, stderr))
tensorflow.lite.python.convert.ConverterError: TOCO failed. See console for info.
2019-07-17 22:03:58.832651: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 61 operators, 94 arrays (0 quantized)
2019-07-17 22:03:58.833307: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 61 operators, 94 arrays (0 quantized)
2019-07-17 22:03:58.906787: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 1: 25 operators, 42 arrays (1 quantized)
2019-07-17 22:03:58.941310: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 2: 24 operators, 41 arrays (1 quantized)
2019-07-17 22:03:58.941785: W tensorflow/lite/toco/graph_transformations/resolve_constant_random_uniform.cc:88] RandomUniform op outputting "dropout/dropout/random_uniform/RandomUniform" is truly random (using /dev/random system entropy). Therefore, cannot resolve as constant. Set
"seed" or "seed2" attr non-zero to fix this
2019-07-17 22:03:58.942427: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 3: 20 operators, 35 arrays (1 quantized)
2019-07-17 22:03:58.942767: W tensorflow/lite/toco/graph_transformations/resolve_constant_random_uniform.cc:88] RandomUniform op outputting "dropout/dropout/random_uniform/RandomUniform" is truly random (using /dev/random system entropy). Therefore, cannot resolve as constant. Set
"seed" or "seed2" attr non-zero to fix this
2019-07-17 22:03:58.943375: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before pre-quantization graph transformations: 20 operators, 35 arrays (1 quantized)
2019-07-17 22:03:58.943717: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After pre-quantization graph transformations pass 1: 16 operators, 31 arrays (1 quantized)
2019-07-17 22:03:58.944040: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before default min-max range propagation graph transformations: 16 operators, 31 arrays (1 quantized)
2019-07-17 22:03:58.944393: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After default min-max range propagation graph transformations pass 1: 16 operators, 31 arrays (1 quantized)
2019-07-17 22:03:58.944778: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before quantization graph transformations: 16 operators, 31 arrays (1 quantized)
2019-07-17 22:03:58.945131: F tensorflow/lite/toco/graph_transformations/quantize.cc:606] Check failed: is_rnn_state_array``

**Comment by ved27** [comment]
Hi ,


This seems another issue .
- Do you have a dropout layer during inference ?
- What kind of deepnn is yours ?
