### ISSUE TITLE
[ Interpreter.runForMultipleInputsOutputs ] Error When running  SSD-Mobilenet-v1 model in tensorflow-lite. 

### ISSUE THREAD

**Issue by AbdelfettahBentaleb** [tensorflow/tensorflow#20920]
@andrewharp I tried your cutosm inference class TFLiteObjectDetectionAPIModel.java in [tensorflow/contrib/lite/examples/android](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/lite/examples/android) , and i use it with your ssd mobilenet v1 tflite mobilenet_ssd_tflite_v1.zip but it seems i have a problem when i call tfLite.runForMultipleInputsOutputs(inputArray, outputMap); ( in function recognizeImage(final Bitmap bitmap) ) . it throws this exception

```
07-18 10:37:02.416 19957-19996/com.app.cerist.realtimeobjectdetectionapi E/AndroidRuntime: FATAL EXCEPTION: Camera
    Process: com.app.cerist.realtimeobjectdetectionapi, PID: 19957
    java.lang.IllegalArgumentException: Output error: Outputs do not match with model outputs.
        at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:170)
        at com.app.cerist.realtimeobjectdetectionapi.ImageClassifierTFLiteAPI.recognizeImage(ImageClassifierTFLiteAPI.java:207)
        at com.app.cerist.realtimeobjectdetectionapi.MainActivity.classifyFrame(MainActivity.java:421)
        at com.app.cerist.realtimeobjectdetectionapi.MainActivity.access$1000(MainActivity.java:48)
        at com.app.cerist.realtimeobjectdetectionapi.MainActivity$4.run(MainActivity.java:455)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:159)
        at android.os.HandlerThread.run(HandlerThread.java:61)
07-18 10:37:02.436 19957-19996/com.app.cerist.realtimeobjectdetectionapi V/Process: killProcess [19957] Callers=com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException:99 java.lang.ThreadGroup.uncaughtException:693 java.lang.ThreadGroup.uncaughtException:690 <bottom of call stack> 
07-18 10:37:02.436 19957-19996/com.app.cerist.realtimeobjectdetectionapi I/Process: Sending signal. PID: 19957 SIG: 9
```

the error said that the length of outputs array is bigger than the length of inputs array
in this condition line in the Interpreter.java

``` 
public void runForMultipleInputsOutputs(Object[] inputs, @NonNull Map<Integer, Object> outputs) {
        if (this.wrapper == null) {
            throw new IllegalStateException("Internal error: The Interpreter has already been closed.");
        } else {
            Tensor[] tensors = this.wrapper.run(inputs);
            if (outputs != null && tensors != null && outputs.size() <= tensors.length) {
                int size = tensors.length;
                //...
            }} else {
                throw new IllegalArgumentException("Output error: Outputs do not match with model outputs.");
}
```
This is my inputs array : 

```
d.imgData = ByteBuffer.allocateDirect(1 * d.inputSize * d.inputSize * 3 * numBytesPerChannel);
d.imgData.order(ByteOrder.nativeOrder());
//...
 imgData.rewind();
        for (int i = 0; i < inputSize; ++i) {
            for (int j = 0; j < inputSize; ++j) {
                int pixelValue = intValues[i * inputSize + j];
                if (isModelQuantized) {
                    // Quantized model
                    imgData.put((byte) ((pixelValue >> 16) & 0xFF));
                    imgData.put((byte) ((pixelValue >> 8) & 0xFF));
                    imgData.put((byte) (pixelValue & 0xFF));
                } else { // Float model
                    imgData.putFloat((((pixelValue >> 16) & 0xFF) - IMAGE_MEAN) / IMAGE_STD);
                    imgData.putFloat((((pixelValue >> 8) & 0xFF) - IMAGE_MEAN) / IMAGE_STD);
                    imgData.putFloat(((pixelValue & 0xFF) - IMAGE_MEAN) / IMAGE_STD);
} 

```

```
Object[] inputArray = {imgData};
```

And this  the outputs arrays :

```
// Copy the input data into TensorFlow.
        Trace.beginSection("feed");
        outputLocations = new float[1][NUM_DETECTIONS][4];
        outputClasses = new float[1][NUM_DETECTIONS];
        outputScores = new float[1][NUM_DETECTIONS];
        numDetections = new float[1];
//...
        Map<Integer, Object> outputMap = new HashMap<>();
        outputMap.put(0, outputLocations);
        outputMap.put(1, outputScores);
        outputMap.put(2, numDetections);
        outputMap.put(3, outputClasses);
        Trace.endSection();
```

And the Inference :
```
// Run the inference call.
        Trace.beginSection("run");
        Log.d("TAG_INPUT",""+String.valueOf(inputArray.length)); // inputArray has length of 1
        Log.d("TAG_OUTPUT",""+String.valueOf(outputMap.size())); // outputMap has length of 4

        tfLite.runForMultipleInputsOutputs(inputArray, outputMap);
        Trace.endSection();
```

I didn't understand the meaning of this Error cuz i did exactly the same as your TFLiteObjectDetectionAPIModel.java class .
thank you for Help

**Comment by jdduke** [comment]
TFLiteObjectDetectionAPIModel was recently modified to use a different model, which as additional outputs (see this [commit](https://github.com/tensorflow/tensorflow/commit/f3785197b4de9466b48462f4f93b455c88dd622b#diff-c748d758eb53ac58d70a13e07e02c6db)). If you want to continue using mobilenet_v1, pattern your code after the code before that commit. In particular, mobilenet_v1 only has outputLocations and outputClass. It does not have outputScores or numDetections.

**Comment by AbdelfettahBentaleb** [comment]
@jdduke Thank you so much for your help That works  for Me , I reviewed the old version of this class and i fixe the issue. 
But somthing it wasn't clear for me, what is the purpose of the box_priors.txt file and why he used it ? is it important to use it ?  
Thank you for your replay
