### ISSUE TITLE
tensorflow.contrib.autograph generated the code to update variables with conditions but throws UnboundLocalError

### ISSUE THREAD

**Issue by tobegit3hub** [tensorflow/tensorflow#20956]
### Environment

python3 -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
v1.9.0-rc2-724-gc0dbd7e456 1.10.0-dev20180718

== cat /etc/issue ===============================================
Linux localhost 4.15.13-x86_64-linode106 #1 SMP Tue Mar 27 14:42:14 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
VERSION="16.04.4 LTS (Xenial Xerus)"
VERSION_ID="16.04"
VERSION_CODENAME=xenial

== are we in docker =============================================
No

== compiler =====================================================
c++ (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

== uname -a =====================================================
Linux localhost 4.15.13-x86_64-linode106 #1 SMP Tue Mar 27 14:42:14 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

== check pips ===================================================
numpy             1.14.5
protobuf          3.6.0

== check for virtualenv =========================================
False

== tensorflow import ============================================
tf.VERSION = 1.6.0
tf.GIT_VERSION = v1.6.0-0-gd2e24b6039
tf.COMPILER_VERSION = v1.6.0-0-gd2e24b6039
Sanity check: array([1], dtype=int32)

== env ==========================================================
LD_LIBRARY_PATH is unset
DYLD_LIBRARY_PATH is unset

== nvidia-smi ===================================================
./tf_env_collect.sh: line 105: nvidia-smi: command not found

== cuda libs  ===================================================

### Describe the problem

We use `tensorflow.contrib.autograph` and try to update the variable with conditional logic. The code is simple and should work with Python.

``` 
a = "test"
if x == 0:
  a = "test1"
else:
  a = "test2"
```

But it throws `UnboundLocalError` and unable to access the existing variables.

### Source code / logs

Here is the example code to reproduce the issue.

```
#!/usr/bin/env python

import tensorflow as tf
from tensorflow.contrib import autograph as ag

def f(x):
  a = "test"
  if x == 0:
    a = "test1"
  else:
    a = "test2"

converted_f = ag.to_graph(f)

print(ag.to_code(f))
print(converted_f(tf.constant(-1)))
```

And it is the generated code of the above code.

```
from __future__ import print_function
import tensorflow as tf

def tf__f(x):
  try:
    with tf.name_scope('f'):
      a = 'test'

      def if_true():
        with tf.name_scope('if_true'):
          a, = a,
          a = 'test1'
          return 1,

      def if_false():
        with tf.name_scope('if_false'):
          a_1, = a,
          a_1 = 'test2'
          return 1,
      with ag__.utils.control_dependency_on_returns(ag__.utils.run_cond(tf.
          equal(x, 0), if_true, if_false)):
        x_1, if_true_1, if_false_1 = ag__.utils.alias_tensors(x, if_true,
            if_false)
  except:
    ag__.rewrite_graph_construction_error(ag_source_map__)
```

It is the full error log when try to run generated graph with test data.

```
Traceback (most recent call last):
  File "/tmp/tmpn2n1i2l2.py", line 20, in tf__f
    equal(x, 0), if_true, if_false)):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/autograph/utils/multiple_dispatch.py", line 50, in run_cond
    return control_flow_ops.cond(condition, true_fn, false_fn)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2048, in cond
    orig_res_t, res_t = context_t.BuildCondBranch(true_fn)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 1895, in BuildCondBranch
    original_result = fn()
  File "/tmp/tmpn2n1i2l2.py", line 10, in if_true
    a, = a,
UnboundLocalError: local variable 'a' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./demo2.py", line 16, in <module>
    print(converted_f(tf.constant(-1)))
  File "/tmp/tmpn2n1i2l2.py", line 24, in tf__f
    ag__.rewrite_graph_construction_error(ag_source_map__)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/autograph/core/errors.py", line 158, in rewrite_graph_construction_error
    raise new_error
tensorflow.contrib.autograph.core.errors.GraphConstructionError: Traceback (most recent call last):
  File "./demo2.py", line 8, in f
    if x == 0:
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/autograph/utils/multiple_dispatch.py", line 50, in run_cond
    return control_flow_ops.cond(condition, true_fn, false_fn)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2048, in cond
    orig_res_t, res_t = context_t.BuildCondBranch(true_fn)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 1895, in BuildCondBranch
    original_result = fn()
  File "/tmp/tmpn2n1i2l2.py", line 10, in if_true
    a, = a,

local variable 'a' referenced before assignment
```

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by mdanatg** [comment]
Hi, looks like a bug in the static analysis - it gets confused because `a` is not used after the conditional.

We'll look at the bug, but in the mean time, returning `a` from the function should clear the error:

```
def f(x):
  a = "test"
  if x == 0:
    a = "test1"
  else:
    a = "test2"
  return a
```

**Comment by tensorflowbutler** [comment]
Nagging Assignee @mdanatg: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by sid619sid** [comment]
I am new to this kind of environment of open source project / product
development can suggest me few guide lines regarding how to learn and
understand about the flow of project.
Any help is appreciated...

Thanks regards
Sidhartha

**Comment by mdanatg** [comment]
Hi Sid, please have a look at the [general TF contrib guidelines](https://www.tensorflow.org/community/contributing for contribution) and the [AutoGraph supplement](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/autograph/CONTRIBUTING.md) to get you started. We're planning to include additional developer documentation, but that's not yet ready.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @mdanatg: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @mdanatg: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @mdanatg: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @mdanatg: It has been 59 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @mdanatg: It has been 74 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @mdanatg: It has been 90 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @mdanatg: It has been 105 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @mdanatg: It has been 120 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by brilee** [comment]
Sorry for the delayed response. We were combing through our old bugs and noticed that this one should already be fixed. Please reopen this bug if you are still seeing issues.
