### ISSUE TITLE
Build failed on windows 10 MSB3073: :VCEnd" exited with code 1

### ISSUE THREAD

**Issue by guileryu01** [tensorflow/tensorflow#21056]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10 64 bit
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: master
- **Python version**: 3.6
- **Bazel version (if compiling from source)**: NA
- **GCC/Compiler version (if compiling from source)**: Visual Studio 2017
- **CUDA/cuDNN version**: 9.2/7.1
- **GPU model and memory**: GTX 1080 8GB
- **Exact command to reproduce**: MSBuild /p:Configuration=Release tf_python_build_pip_package.vcxproj

### Describe the problem
Build failed with error MSB6006: "cmd.exe" exited with code 1. Before that, there is an ModuleNotFound Error: No module named 'tensorflow.python.tools.api' while running create_python_api, even though I do find it from the specified location.

### Source code / logs
```
Task Parameter:BuildSuffix=
                     :VCEnd (TaskId:7050)
                     Task Parameter:TrackerLogDirectory=x64\Release\estimator_python_api\estimato.8A00678D.tlog\ (TaskId:7050)
                     Task Parameter:MinimalRebuildFromTracking=True (TaskId:7050)
                     Task Parameter:TrackFileAccess=True (TaskId:7050)
                     Task Parameter:ToolArchitecture=Native32Bit (TaskId:7050)
                     Write Tracking Logs: (TaskId:7050)
                     	x64\Release\estimator_python_api\estimato.8A00678D.tlog\custombuild.write.1.tlog (TaskId:7050)
                     Read Tracking Logs: (TaskId:7050)
                     	x64\Release\estimator_python_api\estimato.8A00678D.tlog\custombuild.read.1.tlog (TaskId:7050)
                     No output for C:\WORK\LIBRARIES_LOCAL\TENSORFLOW\TENSORFLOW\CONTRIB\CMAKE\BUILD\CMAKEFILES\C75366AEF4FA6332EF71118C646F7D1C\__INIT__.PY.RULE was found in the tracking log; source compilation required. (TaskId:7050)
                     C:\work\libraries_local\tensorflow\tensorflow\contrib\cmake\build\CMakeFiles\c75366aef4fa6332ef71118c646f7d1c\__init__.py.rule will be compiled because it was not found in the tracking log. (TaskId:7050)
                     setlocal
                     cd C:\work\libraries_local\tensorflow\tensorflow\contrib\cmake\build\tf_python
                     if %errorlevel% neq 0 goto :cmEnd
                     C:
                     if %errorlevel% neq 0 goto :cmEnd
                     C:\work\tools\cmake-3.12.0-win32-x86\bin\cmake.exe -E env PYTHONPATH=C:/work/libraries_local/tensorflow/tensorflow/contrib/cmake/build/tf_python C:/Anaconda3/envs/python36/python.exe C:/work/libraries_local/tensorflow/tensorflow/contrib/cmake/build/tf_python/tensorflow/python/tools/api/generator/create_python_api.py --apidir=C:/work/libraries_local/tensorflow/tensorflow/contrib/cmake/build/tf_python/tensorflow/python/estimator/api --package=tensorflow.python.estimator --apiname=estimator --output_package=tensorflow.python.estimator.api C:/work/libraries_local/tensorflow/estimator_api_init_files_list.txt
                     if %errorlevel% neq 0 goto :cmEnd
                     :cmEnd
                     endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
                     :cmErrorLevel
                     exit /b %1
                     :cmDone
                     if %errorlevel% neq 0 goto :VCEnd (TaskId:7050)
                     Generating __init__.py files for Python API. (TaskId:7050)
                     Traceback (most recent call last): (TaskId:7050)
                       File "C:/work/libraries_local/tensorflow/tensorflow/contrib/cmake/build/tf_python/tensorflow/python/tools/api/generator/create_python_api.py", line 27, in <module> (TaskId:7050)
                         from tensorflow.python.tools.api.generator import doc_srcs (TaskId:7050)
                     ModuleNotFoundError: No module named 'tensorflow.python.tools.api' (TaskId:7050)
15:52:23.015     2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1. [C:\work\libraries_local\tensorflow\tensorflow\contrib\cmake\build\estimator_python_api.vcxproj]
                   Done executing task "CustomBuild" -- FAILED. (TaskId:7050)
15:52:23.016     2>Done building target "CustomBuild" in project "estimator_python_api.vcxproj" -- FAILED.: (TargetId:18239)
15:52:23.016     2>Done Building Project "C:\work\libraries_local\tensorflow\tensorflow\contrib\cmake\build\estimator_python_api.vcxproj" (default targets) -- FAILED.
15:52:23.016     1>Done executing task "MSBuild" -- FAILED. (TaskId:8)
15:52:23.016     1>Done building target "ResolveProjectReferences" in project "tf_python_build_pip_package.vcxproj" -- FAILED.: (TargetId:12)
15:52:23.016     1>Done Building Project "c:\work\libraries_local\tensorflow\tensorflow\contrib\cmake\build\tf_python_build_pip_package.vcxproj" (default targets) -- FAILED.
```

**Comment by picsag** [comment]
I receive the same error when Building TensorFlow in Windows 10 (without GPU version) 1.9 with Visual Studio 2015 after 2,5 hours of buidling time. 

File "D:/temp/tensorflow/tensorflow/contrib/cmake/build/tf_python/tensorflow/python/tools/api/generator/create_python_api.py", line 27, in <module> from tensorflow.python.tools.api.generator import doc_srcs
ModuleNotFoundError: No module named 'tensorflow.python.tools.api'
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1.

Protobuf, google and absl-py packages in the python environment were updated beforehand.
 
The machine that was used has 16 GB RAM and 2GB RAM for the nVidia GPU.
If someone has a clue how to avoid this error message, please help.

**Comment by guileryu01** [comment]
@bignamehyp Yes it was built against HEAD.

**Comment by guileryu01** [comment]
Figured it out - in my case it was because target copy path is too long so it has problem creating a file with specified path. It would be nice if the error message can be made more informative.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @bignamehyp: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @bignamehyp: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @bignamehyp: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by bignamehyp** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
