### ISSUE TITLE
AttributeError: 'Series' object has no attribute 'columns'

### ISSUE THREAD

**Issue by jasonachonu** [tensorflow/tensorflow#21067]
Hi,

System information

Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
NO
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS Hugh Sierra
TensorFlow installed from (source or binary): I did pip install tensor flow
TensorFlow version (use command below): v1.9.0-0-g25c197e023 1.9.0
Python version: 3.6
Bazel version (if compiling from source):
GCC/Compiler version (if compiling from source):
CUDA/cuDNN version:
GPU model and memory:
Exact command to reproduce:
Please find below the error am having.

/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
updated
Performing function: predict
on outcome: continuous_static_outcome_occupancy
Predicting for date 2017-01-01 00:00:00
Traceback (most recent call last):
  File "./src/NeirbiLSTM-occupancy.py", line 52, in <module>
    predict.run()
  File "/Users/jasonachonu/git/SeqHub_Summer2018/src/nblib/predict.py", line 51, in run
    [rawdata, var_type,var_timing,var_use,key] = preprocess.preprocess(rawdata,checks=False)
  File "/Users/jasonachonu/git/SeqHub_Summer2018/src/nblib/preprocess.py", line 29, in preprocess
    meta_data = np.core.defchararray.split(np.asarray(rawdata.columns).astype(str),sep="_")
  File "/anaconda3/lib/python3.6/site-packages/pandas/core/generic.py", line 4372, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'columns'

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatatodd: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by jasonachonu** [comment]
I would be glad if you can help resolve this issue, as am stuck on my work
because of it. Please let me know if you need more info.

On Tue, Aug 7, 2018 at 3:13 PM, Alfred Sorten Wolf <notifications@github.com

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatatodd: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatatodd: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.
