### ISSUE TITLE
tf.contrib.image.sparse_image_warp

### ISSUE THREAD

**Issue by GeorgeKaspar** [tensorflow/tensorflow#21153]
System:

== cat /etc/issue ===============================================
Linux george-OMEN-by-HP-Laptop 4.10.0-38-generic #42~16.04.1-Ubuntu SMP Tue Oct 10 16:32:20 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
VERSION="18.3 (Sylvia)"
VERSION_ID="18.3"
VERSION_CODENAME=sylvia

== are we in docker =============================================
No

== compiler =====================================================
c++ (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

== uname -a =====================================================
Linux george-OMEN-by-HP-Laptop 4.10.0-38-generic #42~16.04.1-Ubuntu SMP Tue Oct 10 16:32:20 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

== check pips ===================================================
numpy                              1.14.5            
numpydoc                           0.7.0             
protobuf                           3.6.0             
tensorflow-gpu                     1.9.0             
tensorflow-lattice                 0.9.6             
tensorflow-probability-gpu         0.2.0             
tensorflow-tensorboard             1.5.1             

== check for virtualenv =========================================
False

== tensorflow import ============================================
tf.VERSION = 1.9.0
tf.GIT_VERSION = v1.9.0-0-g25c197e023
tf.COMPILER_VERSION = v1.9.0-0-g25c197e023
Sanity check: array([1], dtype=int32)
/home/george/anaconda3/envs/py36/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters

== env ==========================================================
LD_LIBRARY_PATH /usr/local/cuda-9.1/lib64:/usr/local/cuda/lib64:/usr/local/cuda-9.1/lib64:/usr/local/cuda/extras/CUPTI/lib64/:
DYLD_LIBRARY_PATH is unset

== nvidia-smi ===================================================
Thu Jul 26 11:04:57 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 387.26                 Driver Version: 387.26                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1050    Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   54C    P0    N/A /  N/A |    355MiB /  4038MiB |      2%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1451      G   /usr/lib/xorg/Xorg                           187MiB |
|    0      2194      G   cinnamon                                      79MiB |
|    0      2864      G   ...-token=685C4795125F550AF469D7ED70DAE1ED    81MiB |
|    0      3149      G   /usr/lib/firefox/firefox                       3MiB |
+-----------------------------------------------------------------------------+

== cuda libs  ===================================================
/usr/local/cuda-9.1/targets/x86_64-linux/lib/libcudart.so.9.1.85
/usr/local/cuda-9.1/targets/x86_64-linux/lib/libcudart_static.a
/usr/local/cuda-9.1/lib64/libcudart.so.9.1.85
/usr/local/cuda-9.1/lib64/libcudart_static.a
/usr/local/cuda-9.1/doc/man/man7/libcudart.so.7
/usr/local/cuda-9.1/doc/man/man7/libcudart.7
/usr/local/cuda-9.0/lib64/libcudart.so.9.0.176
/usr/local/cuda-9.0/lib64/libcudart_static.a
/usr/local/cuda-9.0/doc/man/man7/libcudart.so.7
/usr/local/cuda-9.0/doc/man/man7/libcudart.7

VERSION: v1.9.0-0-g25c197e023 1.9.0

Code:
def warp(image, R0, C0, R, C):
    A = tf.reshape(tf.stack([R0, C0], axis=-1), (1, -1, 2))
    B = tf.reshape(tf.stack([R, C], axis=-1), (1, -1, 2))
    image = tf.expand_dims(tf.cast(image, tf.float32), axis=0)
    print(image, A, B)
    image = tf.contrib.image.sparse_image_warp(image, A, B)[0]
    print(image)
    image = tf.cast(image, tf.uint8)
    return image
Error:

Traceback (most recent call last):
  File "rotate.py", line 167, in <module>
    test_warp()
  File "rotate.py", line 154, in test_warp
    new_image = sess.run(warp(image, R0, C0, R, C))
  File "rotate.py", line 70, in warp
    image = tf.contrib.image.sparse_image_warp(image, A, B)[0]
  File "/home/george/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/util/lazy_loader.py", line 53, in __getattr__
    module = self._load()
  File "/home/george/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/util/lazy_loader.py", line 42, in _load
    module = importlib.import_module(self.__name__)
  File "/home/george/anaconda3/envs/py36/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/george/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/contrib/__init__.py", line 47, in <module>
    from tensorflow.contrib import image
  File "/home/george/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/contrib/image/__init__.py", line 70, in <module>
    from tensorflow.contrib.image.python.ops.single_image_random_dot_stereograms import single_image_random_dot_stereograms
  File "/home/george/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/contrib/image/python/ops/single_image_random_dot_stereograms.py", line 27, in <module>
    "_single_image_random_dot_stereograms.so"))
  File "/home/george/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/contrib/util/loader.py", line 56, in load_op_library
    ret = load_library.load_op_library(path)
  File "/home/george/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 73, in load_op_library
    exec(wrappers, module.__dict__)
  File "<string>", line 27
    def single_image_random_dot_stereograms(depth_values, hidden_surface_removal=True, convergence_dots_size=8, dots_per_inch=72, eye_separation=2,5, mu=0,333299994, normalize=True, normalize_max=-100, normalize_min=100, border_level=0, number_colors=256, output_image_shape=[1024, 768, 1], output_data_window=[1022, 757], name=None):
                                                                                                                                                   ^
SyntaxError: invalid syntax

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by GeorgeKaspar** [comment]
Can I send pull request for this issue?

**Comment by mamrehn** [comment]
Same issue here during
```python
ds_finite = tf.data.Dataset.from_generator(
                python_iterator, output_types=output_types, output_shapes=output_shapes)
ds_finite = ds_finite.apply(tf.contrib.data.batch_and_drop_remainder(self._batch_size))
```

```
[...]
ds_finite = ds_finite.apply(tf.contrib.data.batch_and_drop_remainder(self._batch_size))
File "/home/usr/miniconda3/envs/myenv/lib/python3.6/site-packages/tensorflow/python/util/lazy_loader.py", line 53, in __getattr__
module = self._load()
File "/home/usr/miniconda3/envs/myenv/lib/python3.6/site-packages/tensorflow/python/util/lazy_loader.py", line 42, in _load
module = importlib.import_module(self.__name__)
File "/home/usr/miniconda3/envs/myenv/lib/python3.6/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 994, in _gcd_import
File "<frozen importlib._bootstrap>", line 971, in _find_and_load
File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 678, in exec_module
File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
File "/home/usr/miniconda3/envs/myenv/lib/python3.6/site-packages/tensorflow/contrib/__init__.py", line 49, in <module>
from tensorflow.contrib import image
File "/home/usr/miniconda3/envs/myenv/lib/python3.6/site-packages/tensorflow/contrib/image/__init__.py", line 70, in <module>
from tensorflow.contrib.image.python.ops.single_image_random_dot_stereograms import single_image_random_dot_stereograms
File "/home/usr/miniconda3/envs/myenv/lib/python3.6/site-packages/tensorflow/contrib/image/python/ops/single_image_random_dot_stereograms.py", line 27, in <module>
"_single_image_random_dot_stereograms.so"))
File "/home/usr/miniconda3/envs/myenv/lib/python3.6/site-packages/tensorflow/contrib/util/loader.py", line 56, in load_op_library
ret = load_library.load_op_library(path)
File "/home/usr/miniconda3/envs/myenv/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 73, in load_op_library
exec(wrappers, module.__dict__)
File "<string>", line 28
def single_image_random_dot_stereograms(depth_values, hidden_surface_removal=True, convergence_dots_size=8, dots_per_inch=72, eye_separation=2,5, mu=0,333299994, normalize=True, normalize_max=-100, normalize_min=100, border_level=0, number_colors=256, output_image_shape=[1024, 768, 1], output_data_window=[1022, 757], name=None):
                                                                                                                                               ^
SyntaxError: invalid syntax
```

The generated code string seems to use a colon instead of a dot for its floating point value:
`dots_per_inch=72, eye_separation=2,5, mu=0,333299994`
