### ISSUE TITLE
Native TF operations drop Keras tensor metadata

### ISSUE THREAD

**Issue by metaluga145** [tensorflow/tensorflow#21152]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution: Ubuntu 16.04
- **Mobile device**: N/A
- **TensorFlow installed from**: from pip
- **TensorFlow version**: ('v1.9.0-0-g25c197e023', '1.9.0')
- **Python version**: 2.7.12
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: CUDA-9.0/cuDNN-7.1.4
- **GPU model and memory**: N/A
- **Exact command to reproduce**:

```
$ python
import tensorflow as tf
from tensorflow.keras.layers import Input

x = Input((28, 28, 3))
y = Input((28, 28, 3))
z = x + y

model = tf.keras.Model([x, y], z)
```

### Description
The code mentioned above throws the error (see logs). As it turned out, almost all native tf operations , such padding, convolution, etc., drop tensor metadata.

I do understand that these operations can be replaced with similar Keras layers or wrapped with Lambda. However, since Keras is officially moved to tensorflow package, it would be nice to preserve tensor compatibility between tf and Keras.

### Source code / logs
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/oleg/tf/venv/local/lib/python2.7/site-packages/tensorflow/python/keras/engine/training.py", line 111, in __init__
    super(Model, self).__init__(*args, **kwargs)
  File "/home/oleg/tf/venv/local/lib/python2.7/site-packages/tensorflow/python/keras/engine/network.py", line 78, in __init__
    self._init_graph_network(*args, **kwargs)
  File "/home/oleg/tf/venv/local/lib/python2.7/site-packages/tensorflow/python/keras/engine/network.py", line 201, in _init_graph_network
    '(thus holding past layer metadata). Found: ' + str(x))
ValueError: Output tensors to a Model must be the output of a TensorFlow `Layer` (thus holding past layer metadata). Found: Tensor("add:0", shape=(?, 28, 28, 3), dtype=float32)
```

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Bazel version
GPU model and memory
Mobile device

**Comment by metaluga145** [comment]
- **Mobile device**: N/A
- **Bazel version (if compiling from source)**: N/A (installed from pip)
- **GCC/Compiler version (if compiling from source)**: N/A (installed from pip)
- **GPU model and memory**: N/A (Irrelevant, sample code is for CPU)

**Comment by tensorflowbutler** [comment]
Nagging Assignee @bignamehyp: It has been 18 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by bignamehyp** [comment]
Keras is a higher level API. It doesn't mean naive ops need to support higher level meta-data.
