### ISSUE TITLE
Lambda Layer issue when receiving a list of DeferredTensor with a TensorShape shape

### ISSUE THREAD

**Issue by jnd77** [tensorflow/tensorflow#21181]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
MacOS
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
- **TensorFlow installed from (source or binary)**:
binary
- **TensorFlow version (use command below)**:
v1.9.0-0-g25c197e023 1.9.0
- **Python version**:
Python 3.6.6
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:
See below.

### Describe the problem
Following [this issue](https://github.com/tensorflow/tensorflow/issues/20338), I used the work-around and wrapped the result of `compute_output_shape` with tf.TensorShape.
However when using a Lambda layer with multiple inputs, the shape isn't handled properly and throws the exception:

`TypeError: int() argument must be a string, a bytes-like object or a number, not 'TensorShape'`

### Source code / logs
Here is a basic set-up to reproduce it:

    import tensorflow as tf

    class MyLayer(tf.layers.Layer):

        def __init__(self, **kwargs):
            super(MyLayer, self).__init__(**kwargs)

        def call(self, x):
            return x

        def compute_output_shape(self, input_shape):
            return tf.TensorShape(input_shape[0])

    tf.enable_eager_execution()

    a = tf.keras.layers.Input(shape=[1])
    b = tf.keras.layers.Input(shape=[1])
    layer_1 = MyLayer()(a)
    layer_2 = MyLayer()(b)

    layer_3 = tf.keras.layers.Lambda(lambda x: x[0])([layer_1, layer_2])

And the stack-trace:

```

Traceback (most recent call last):
  File "/Users/jnd/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-C/ch-0/181.5087.37/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 1664, in <module>
    main()
  File "/Users/jnd/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-C/ch-0/181.5087.37/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Users/jnd/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-C/ch-0/181.5087.37/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Users/jnd/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-C/ch-0/181.5087.37/PyCharm CE.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/jnd/dev/mask_rcnn/bug_replication.py", line 23, in <module>
    layer_3 = tf.keras.layers.Lambda(lambda x: x[0])([layer_1, layer_2])
  File "/usr/local/anaconda3/envs/mask_rcnn_cpu/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 714, in __call__
    output_shapes = self.compute_output_shape(input_shapes)
  File "/usr/local/anaconda3/envs/mask_rcnn_cpu/lib/python3.6/site-packages/tensorflow/python/keras/layers/core.py", line 677, in compute_output_shape
    input_shape = tuple(tensor_shape.TensorShape(input_shape).as_list())
  File "/usr/local/anaconda3/envs/mask_rcnn_cpu/lib/python3.6/site-packages/tensorflow/python/framework/tensor_shape.py", line 541, in __init__
    self._dims = [as_dimension(d) for d in dims_iter]
  File "/usr/local/anaconda3/envs/mask_rcnn_cpu/lib/python3.6/site-packages/tensorflow/python/framework/tensor_shape.py", line 541, in <listcomp>
    self._dims = [as_dimension(d) for d in dims_iter]
  File "/usr/local/anaconda3/envs/mask_rcnn_cpu/lib/python3.6/site-packages/tensorflow/python/framework/tensor_shape.py", line 482, in as_dimension
    return Dimension(value)
  File "/usr/local/anaconda3/envs/mask_rcnn_cpu/lib/python3.6/site-packages/tensorflow/python/framework/tensor_shape.py", line 37, in __init__
    self._value = int(value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'TensorShape'

```

**Comment by omalleyt12** [comment]
Hi @jnd77, this should now work in the nightly build: ```pip install tf-nightly```` (or ```pip install tf-nightly-gpu``` if you have a GPU)

**Comment by jnd77** [comment]
Hi !
I did run the code above with the nightly version '1.11.0-dev20180808', and I have the same exception.

**Comment by omalleyt12** [comment]
Hi @jnd77 that version is going to be just a little too old to have the fix, can you please upgrade to ```1.11.0.dev20180813``` and let me know if you still see the error?

**Comment by jnd77** [comment]
Unfortunately I have a Mac, and the latest version is still 1.11.0-dev20180808. Let me get back to you when a newer Mac version is available ...

**Comment by jnd77** [comment]
@omalleyt12 Just ran the test. It works. Thanks for your help !

**Comment by omalleyt12** [comment]
Great, no prob!
