### ISSUE TITLE
[Bug] tf.map_fn cannot work with tf.histogram_fixed_width when using float

### ISSUE THREAD

**Issue by ybsave** [tensorflow/tensorflow#21190]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Y
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: N/A
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.9
- **Python version**: 3.6
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: 9.0/7
- **GPU model and memory**: Quardo M4000
- **Exact command to reproduce**: N/A

### Describe the problem
I have tested the tf.map_fn to produce a list of histograms for a tensor. My example codes are as below.
My findings: 

1. When running tf.histogram_fixed_width for single floating tensor, there is no problem. (see test0() below)
2. When running tf.map_fn together with tf.histogram_fixed_width for integer tensor, there is no problem (see test2() below)
3. When running tf.map_fn together with tf.histogram_fixed_width for floating tensor, the program crashed (see test1() below)

### Source code / logs
	import tensorflow as tf
	import numpy as np
	def test0():
	  V = tf.placeholder(tf.float32, [None, 3])
	  hists = tf.histogram_fixed_width(V[0], [0.0,10.0], 10)
	  A = [[1.0,2.0,3.0], [4.0,5.0,6.0]]
	  with tf.Session() as sess:
		print(sess.run(hists, {V:A}))
		
	def test1():
	  V = tf.placeholder(tf.float32, [None, 3])
	  hists = tf.map_fn(
		lambda x: tf.histogram_fixed_width(x, [0.0,10.0], 10), V)
	  A = [[1.0,2.0,3.0], [4.0,5.0,6.0]]
	  with tf.Session() as sess:
		print(sess.run(hists, {V:A}))

	def test2():
	  V = tf.placeholder(tf.int32, [None, 3])
	  hists = hists = tf.map_fn(
		lambda x: tf.histogram_fixed_width(x, [0,10], 10), V)
	  A = [[1,2,3], [4,5,6]]
	  with tf.Session() as sess:
		print(sess.run(hists, {V:A}))

test0() and test2() work fine. test1() produce the following error. Therefore, I think this may be a bug in tensorflow.

	Traceback (most recent call last):
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1322, in _do_call
		return fn(*args)
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1307, in _run_fn
		options, feed_dict, fetch_list, target_list, run_metadata)
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1409, in _call_tf_sessionrun
		run_metadata)
	tensorflow.python.framework.errors_impl.InvalidArgumentError: TensorArray dtype is float but Op is trying to write dtype int32.
			 [[Node: map/while/TensorArrayWrite/TensorArrayWriteV3 = TensorArrayWriteV3[T=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](map/while/TensorArrayWrite/TensorArrayWriteV3/Enter, map/while/Switch_1/_31, map/while/histogram_fixed_width, map/while/Switch_2/_33)]]
			 [[Node: map/while/TensorArrayWrite/TensorArrayWriteV3/_35 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_66_map/while/TensorArrayWrite/TensorArrayWriteV3", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](^_cloopmap/while/NextIteration_2/_6)]]

	During handling of the above exception, another exception occurred:

	Traceback (most recent call last):
	  File "train_model.py", line 196, in <module>
		main()
	  File "train_model.py", line 193, in main
		test1()
	  File "train_model.py", line 166, in test1
		print(sess.run(hists, {V:A}))
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\client\session.py", line 900, in run
		run_metadata_ptr)
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1135, in _run
		feed_dict_tensor, options, run_metadata)
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1316, in _do_run
		run_metadata)
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1335, in _do_call
		raise type(e)(node_def, op, message)
	tensorflow.python.framework.errors_impl.InvalidArgumentError: TensorArray dtype is float but Op is trying to write dtype int32.
			 [[Node: map/while/TensorArrayWrite/TensorArrayWriteV3 = TensorArrayWriteV3[T=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](map/while/TensorArrayWrite/TensorArrayWriteV3/Enter, map/while/Switch_1/_31, map/while/histogram_fixed_width, map/while/Switch_2/_33)]]
			 [[Node: map/while/TensorArrayWrite/TensorArrayWriteV3/_35 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_66_map/while/TensorArrayWrite/TensorArrayWriteV3", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](^_cloopmap/while/NextIteration_2/_6)]]

	Caused by op 'map/while/TensorArrayWrite/TensorArrayWriteV3', defined at:
	  File "train_model.py", line 196, in <module>
		main()
	  File "train_model.py", line 193, in main
		test1()
	  File "train_model.py", line 163, in test1
		lambda x: tf.histogram_fixed_width(x, [0.0,10.0], 10), V)
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\ops\functional_ops.py", line 459, in map_fn
		maximum_iterations=n)
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 3209, in while_loop
		result = loop_context.BuildLoop(cond, body, loop_vars, shape_invariants)
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 2941, in BuildLoop
		pred, body, original_loop_vars, loop_vars, shape_invariants)
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 2878, in _BuildLoop
		body_result = body(*packed_vars_for_body)
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 3179, in <lambda>
		body = lambda i, lv: (i + 1, orig_body(*lv))
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\ops\functional_ops.py", line 451, in compute
		tas = [ta.write(i, value) for (ta, value) in zip(tas, flat_fn_values)]
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\ops\functional_ops.py", line 451, in <listcomp>
		tas = [ta.write(i, value) for (ta, value) in zip(tas, flat_fn_values)]
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\util\tf_should_use.py", line 118, in wrapped
		return _add_should_use_warning(fn(*args, **kwargs))
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\ops\tensor_array_ops.py", line 842, in write
		return self._implementation.write(index, value, name=name)
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\util\tf_should_use.py", line 118, in wrapped
		return _add_should_use_warning(fn(*args, **kwargs))
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\ops\tensor_array_ops.py", line 276, in write
		name=name)
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\ops\gen_data_flow_ops.py", line 7870, in tensor_array_write_v3
		flow_in=flow_in, name=name)
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
		op_def=op_def)
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 3414, in create_op
		op_def=op_def)
	  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 1740, in __init__
		self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

	InvalidArgumentError (see above for traceback): TensorArray dtype is float but Op is trying to write dtype int32.
			 [[Node: map/while/TensorArrayWrite/TensorArrayWriteV3 = TensorArrayWriteV3[T=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](map/while/TensorArrayWrite/TensorArrayWriteV3/Enter, map/while/Switch_1/_31, map/while/histogram_fixed_width, map/while/Switch_2/_33)]]
			 [[Node: map/while/TensorArrayWrite/TensorArrayWriteV3/_35 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_66_map/while/TensorArrayWrite/TensorArrayWriteV3", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](^_cloopmap/while/NextIteration_2/_6)]]

**Comment by yongtang** [comment]
@ybsave In the docstring `tf.map_fn`:
```
dtype: (optional) The output type(s) of fn. If fn returns a structure of Tensors differing
from the structure of elems, then dtype is not optional and must have the same
structure as the output of fn.
```

As the return type of `tf.histogram_fixed_width` is `tf.int32` (differs from `V`), I think the issue could be resolved with:
```
  V = tf.placeholder(tf.float32, [None, 3])
  hists = tf.map_fn(
	lambda x: tf.histogram_fixed_width(x, [0.0,10.0], 10), V, tf.int32)
  A = [[1.0,2.0,3.0], [4.0,5.0,6.0]]
  with tf.Session() as sess:
	print(sess.run(hists, {V:A}))
```

**Comment by ybsave** [comment]
@yongtang Thank you for your help. It works now.
