### ISSUE TITLE
Unimplemented cast int64 to string is not supported

### ISSUE THREAD

**Issue by aroraakshit** [tensorflow/tensorflow#21192]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution**: Linux Ubuntu 16.04.4
- **TensorFlow installed from (source or binary)**: Binary
- **TensorFlow version (use command below)**: 1.8
- **Python version**: 3.5.2
- Bazel version: N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A
- Exact command to reproduce: described below
- Mobile device: N/A

### Describe the problem
After following the steps in Using SavedModel with Estimators: When sending a classification request from client, the server is not able to cast it into serialized tf example that model is expecting.

The same error comes up even when I used ```
tf.contrib.predictor.from_saved_model```

So far, I have checked StackOverflow, Tf documentation, issues on Tf and Tf/serving. No one has ever encountered this error. Hence reporting here. This [issue {#1017}](https://github.com/tensorflow/serving/issues/1017) was rejected by @chrisolston in Tf/serving because the error trace indicates it is an issue in one of the core modules on main Tf repo and it had looked like there was no serialization of tf example proto in the client side code: But that task is already accomplished by [prediction_service_pb2.py](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/apis/prediction_service_pb2.py) file. 

There are no other pointers online to what is going wrong here, please help!

### Source code / error logs
TensorFlow model server **error** trace:
```
2018-07-27 14:54:49.685755: W external/org_tensorflow/tensorflow/core/framework/op_kernel.cc:1295] OP_REQUIRES failed at cast_op.cc:77 : Unimplemented: Cast int64 to string is not supported
2018-07-27 14:54:49.685822: E external/org_tensorflow/tensorflow/core/common_runtime/executor.cc:696] Executor failed to create kernel. Unimplemented: Cast int64 to string is not supported
         [[Node: Cast = Cast[DstT=DT_STRING, SrcT=DT_INT64, _output_shapes=[[2]], _device="/job:localhost/replica:0/task:0/device:CPU:0"](ArgMax)]]
```

**Error** on running client side code:
```
Traceback (most recent call last):
  File "/home/mldev/venv/lib/python3.5/site-packages/grpc/beta/_client_adaptations.py", line 193, in _blocking_unary_unary
    credentials=_credentials(protocol_options))
  File "/home/mldev/venv/lib/python3.5/site-packages/grpc/_channel.py", line 500, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/mldev/venv/lib/python3.5/site-packages/grpc/_channel.py", line 434, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.UNIMPLEMENTED, Cast int64 to string is notsupported
         [[Node: Cast = Cast[DstT=DT_STRING, SrcT=DT_INT64, _output_shapes=[[2]], _device="/job:localhost/replica:0/task:0/device:CPU:0"](ArgMax)]])>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mldev/intelligent_sp/train_scripts/client.py", line 63, in <module>
    run(args.host, args.port, args.input, args.model, args.signature_name)
  File "/home/mldev/intelligent_sp/train_scripts/client.py", line 42, in run
    result = stub.Classify(request, 10.0)
  File "/home/mldev/venv/lib/python3.5/site-packages/grpc/beta/_client_adaptations.py", line 309, in __call__
    self._request_serializer, self._response_deserializer)
  File "/home/mldev/venv/lib/python3.5/site-packages/grpc/beta/_client_adaptations.py", line 195, in _blocking_unary_unary
    raise _abortion_error(rpc_error_call)
grpc.framework.interfaces.face.face.LocalError: LocalError(code=StatusCode.UNIMPLEMENTED, details="Cast int64 to string isnot supported
         [[Node: Cast = Cast[DstT=DT_STRING, SrcT=DT_INT64, _output_shapes=[[2]], _device="/job:localhost/replica:0/task:0/device:CPU:0"](ArgMax)]]")
```

**Relevant Client Code**:
```
    channel = implementations.insecure_channel(host, port)
    stub = prediction_service_pb2.beta_create_PredictionService_stub(channel)

    # Pre-processing
    prediction_input = [json.dumps(eval(input_str))]
    
    ink, classname = creat.parse_line(prediction_input[0])

    classnames = ['doodle', 'expression', 'symbols']
    features = {}
    features["class_index"] = tf.train.Feature(int64_list=tf.train.Int64List(value=[classnames.index("doodle")]))
    features["ink"] = tf.train.Feature(float_list=tf.train.FloatList(value=ink.flatten()))
    features["shape"] = tf.train.Feature(int64_list=tf.train.Int64List(value=ink.shape))
    f = tf.train.Features(feature=features)
    example = tf.train.Example(features=f)
    final_req = [example]
    start = time.time()

    # Call classification model to make prediction
    request = classification_pb2.ClassificationRequest()
    request.model_spec.name = model
    request.model_spec.signature_name = signature_name
    request.input.example_list.examples.extend(final_req)
    
    result = stub.Classify(request, 10.0)
```

Imports used in Client Code:
```
from tensorflow_serving.apis import classification_pb2
from tensorflow_serving.apis import prediction_service_pb2
from tensorflow_serving.apis import input_pb2 as final_inp
```

Code used to **export saved model** (runs successfully):
```
      feature_spec = {
      "ink": tf.VarLenFeature(dtype=tf.float32),
      "shape": tf.FixedLenFeature([2], dtype=tf.int64),
      "class_index": tf.FixedLenFeature([1], dtype=tf.int64)
      }
      
      # defining serving input receiver function
      def serving_input_receiver_fn():
        """An input receiver that expects a serialized tf.Example."""
        serialized_tf_example = tf.placeholder(dtype=tf.string, shape=[None], name='input_example_tensor')
        receiver_tensors = {'examples': serialized_tf_example}
        parsed_features = tf.parse_example(serialized_tf_example, feature_spec)
        parsed_features["ink"] = tf.sparse_tensor_to_dense(parsed_features["ink"])
        return tf.estimator.export.ServingInputReceiver(parsed_features, receiver_tensors)

      # export saved model
      estimator.export_savedmodel(FLAGS.model_dir+"/serve/", serving_input_receiver_fn, strip_default_attrs=True)
      print("done exporting")
```

The output from **saved_model_cli** (used to inspect saved model) looks like this:
```
MetaGraphDef with tag-set: 'serve' contains the following SignatureDefs:

signature_def['output']:
  The given SavedModel SignatureDef contains the following input(s):
    inputs['inputs'] tensor_info:
        dtype: DT_STRING
        shape: (-1)
        name: input_example_tensor:0
  The given SavedModel SignatureDef contains the following output(s):
    outputs['classes'] tensor_info:
        dtype: DT_STRING
        shape: (2)
        name: Cast:0
    outputs['scores'] tensor_info:
        dtype: DT_FLOAT
        shape: (2, 348)
        name: dense/BiasAdd:0
  Method name is: tensorflow/serving/classify

signature_def['serving_default']:
  The given SavedModel SignatureDef contains the following input(s):
    inputs['inputs'] tensor_info:
        dtype: DT_STRING
        shape: (-1)
        name: input_example_tensor:0
  The given SavedModel SignatureDef contains the following output(s):
    outputs['classes'] tensor_info:
        dtype: DT_STRING
        shape: (2)
        name: Cast:0
    outputs['scores'] tensor_info:
        dtype: DT_FLOAT
        shape: (2, 348)
        name: dense/BiasAdd:0
  Method name is: tensorflow/serving/classify
```

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by skye** [comment]
cc/ @sukritiramesh @nfiedel

**Comment by karmel** [comment]
Hi @aroraakshit -- I imagine it's been frustrating to have to go through so many places to find an answer, but hopefully we can figure out what's happening here. 

It would help to make a simpler example, to extract the possibility that it's something inside the model that's raising an error. Can you create a minimal example that starts with a tf.example holding an int, and a SavedModel from a model_fn that just accepts that int and doesn't actually do any learning? That will isolate whether this is an issue inside the model, or in the communication between the client and the server.

**Comment by aroraakshit** [comment]
Hi @karmel, thank you for looking into this. 

Since the way I am exporting my SavedModel is [using Estimator API](https://www.tensorflow.org/guide/saved_model#using_savedmodel_with_estimators), to isolate the error I am facing, I would simply extend the TensorFlow's [RNN for Drawing Classification](https://www.tensorflow.org/tutorials/sequences/recurrent_quickdraw) tutorial by adding SavedModel functionality to it. I have put the code and documented the steps to reproduce the error in a small repo [here](https://github.com/aroraakshit/cast_issue_poc_). 

Thanks!

**Comment by karmel** [comment]
Great, thanks, that helps to extract the model. Does that produce precisely the same error? My guess is the cited node is different? Can you provide the trace?

**Comment by aroraakshit** [comment]
To my knowledge, it is precisely the same error. I visualized the graph on TensorBoard, it is the same node that's giving the error, you can find the graph [here](https://github.com/aroraakshit/cast_issue_poc_/blob/master/TensorBoard_vis.png).

Here is the server side log upon a single request:
```
2018-07-31 17:50:15.878264: I tensorflow_serving/model_servers/main.cc:323] Running ModelServer at 0.0.0.0:9000 ...
2018-07-31 17:55:12.725076: W external/org_tensorflow/tensorflow/core/framework/op_kernel.cc:1295] OP_REQUIRES failed at cast_op.cc:77 : Unimplemented: Cast int64 to string is not supported
2018-07-31 17:55:12.725149: E external/org_tensorflow/tensorflow/core/common_runtime/executor.cc:696] Executor failed to create kernel. Unimplemented: Cast int64 to string is not supported
	 [[Node: Cast = Cast[DstT=DT_STRING, SrcT=DT_INT64, _output_shapes=[[8]], _device="/job:localhost/replica:0/task:0/device:CPU:0"](ArgMax)]]
```

Here is the client side error trace:
```
Traceback (most recent call last):
  File "/home/mldev/venv/lib/python3.5/site-packages/grpc/beta/_client_adaptations.py", line 193, in _blocking_unary_unary
    credentials=_credentials(protocol_options))
  File "/home/mldev/venv/lib/python3.5/site-packages/grpc/_channel.py", line 500, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/mldev/venv/lib/python3.5/site-packages/grpc/_channel.py", line 434, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.UNIMPLEMENTED, Cast int64 to string is not supported
	 [[Node: Cast = Cast[DstT=DT_STRING, SrcT=DT_INT64, _output_shapes=[[8]], _device="/job:localhost/replica:0/task:0/device:CPU:0"](ArgMax)]])>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/storage/test_env/cast_issue_poc_/client.py", line 59, in <module>
    run(args.host, args.port, args.input, args.model, args.signature_name)
  File "/storage/test_env/cast_issue_poc_/client.py", line 41, in run
    result = stub.Classify(request, 10.0)
  File "/home/mldev/venv/lib/python3.5/site-packages/grpc/beta/_client_adaptations.py", line 309, in __call__
    self._request_serializer, self._response_deserializer)
  File "/home/mldev/venv/lib/python3.5/site-packages/grpc/beta/_client_adaptations.py", line 195, in _blocking_unary_unary
    raise _abortion_error(rpc_error_call)
grpc.framework.interfaces.face.face.LocalError: LocalError(code=StatusCode.UNIMPLEMENTED, details="Cast int64 to string is not supported
	 [[Node: Cast = Cast[DstT=DT_STRING, SrcT=DT_INT64, _output_shapes=[[8]], _device="/job:localhost/replica:0/task:0/device:CPU:0"](ArgMax)]]")
```

**Comment by tensorflowbutler** [comment]
Nagging Assignee @karmel: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @karmel: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @karmel: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @karmel: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @karmel: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @karmel: It has been 59 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.
