### ISSUE TITLE
errors after installing pydot-ng  ImportError: DLL load failed: The specified module could not be found. and SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by AyaMohamedS** [tensorflow/tensorflow#21194]
I followed the instructions given in the link. 
http://www.codesofinterest.com/2017/02/visualizing-model-structures-in-keras.html

then I did:
conda install pydot-ng 

Then i installed graphviz from here http://www.graphviz.org/download/ and added C:\Program Files (x86)\Graphviz2.38\bin to PATH

  after that it gives me errors if i made any " conda" instruction in command window or anaconda prompt
and also give the same error when writing "  activate tensorflow  " in command window

Error:

(base) C:\Users\BioHelwan>activate tensorflow
Traceback (most recent call last):
  File "C:\Users\BioHelwan\Anaconda3\lib\site-packages\conda\cli\main.py", line 98, in main
    return activator_main()
  File "C:\Users\BioHelwan\Anaconda3\lib\site-packages\conda\activate.py", line 632, in main
    print(activator.execute(), end='')
  File "C:\Users\BioHelwan\Anaconda3\lib\site-packages\conda\activate.py", line 166, in execute
    return getattr(self, self.command)()
  File "C:\Users\BioHelwan\Anaconda3\lib\site-packages\conda\activate.py", line 152, in activate
    return self._finalize(self._yield_commands(self.build_activate(self.env_name_or_prefix)),
  File "C:\Users\BioHelwan\Anaconda3\lib\site-packages\conda\activate.py", line 231, in build_activate
    prefix = locate_prefix_by_name(env_name_or_prefix)
  File "C:\Users\BioHelwan\Anaconda3\lib\site-packages\conda\base\context.py", line 951, in locate_prefix_by_name
    envs_dirs = context.envs_dirs
  File "C:\Users\BioHelwan\Anaconda3\lib\site-packages\conda\base\context.py", line 381, in envs_dirs
    join(self._user_data_dir, 'envs'),
  File "C:\Users\BioHelwan\Anaconda3\lib\site-packages\conda\base\context.py", line 416, in _user_data_dir
    return user_data_dir(APP_NAME, APP_NAME)
  File "C:\Users\BioHelwan\Anaconda3\lib\site-packages\conda\_vendor\appdirs.py", line 67, in user_data_dir
    path = os.path.join(_get_win_folder(const), appauthor, appname)
  File "C:\Users\BioHelwan\Anaconda3\lib\site-packages\conda\_vendor\appdirs.py", line 284, in _get_win_folder_with_pywin32
    from win32com.shell import shellcon, shell
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\BioHelwan\Anaconda3\Scripts\conda-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\BioHelwan\Anaconda3\lib\site-packages\conda\cli\main.py", line 108, in main
    init_loggers()
  File "C:\Users\BioHelwan\Anaconda3\lib\site-packages\conda\cli\main.py", line 55, in init_loggers
    from ..gateways.logging import initialize_logging, set_verbosity
  File "C:\Users\BioHelwan\Anaconda3\lib\site-packages\conda\gateways\logging.py", line 12, in <module>
    from ..common.io import attach_stderr_handler
  File "C:\Users\BioHelwan\Anaconda3\lib\site-packages\conda\common\io.py", line 5, in <module>
    from concurrent.futures import ThreadPoolExecutor, _base, as_completed
  File "C:\Users\BioHelwan\Anaconda3\envs\tensorflow\Lib\site-packages\concurrent\futures\__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
  File "C:\Users\BioHelwan\Anaconda3\envs\tensorflow\Lib\site-packages\concurrent\futures\_base.py", line 414
    raise exception_type, self._exception, self._traceback
                        ^
SyntaxError: invalid syntax

Note: any instruction related to anaconda gives me an  error also i can't remove anaconda to start setup from beginning to get rid of from this problem

i'm using 
windows10 (64)  - Anaconda 4.2 and python 3.5.2
i installed tensor flow gpu version from instructions in this link https://www.tensorflow.org/install/install_windows 
tensorflow version=1.9.0
cuda versions installed 8.0 /9.0
GPU : NVIDIA GeForce GTX 960M   specs link: https://www.geforce.com/hardware/notebook-gpus/geforce-gtx-960m/specifications

Exact command to reproduce : activate tensorflow (also any code related to anaconda i can't use "conda" or "pip" instructions in my command prompt because they give errors too)

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by AyaMohamedS** [comment]
i solved the problem by uninstall anaconda then reinstall the tensor flow 
for visualization keras models
this link solved my problem 
https://www.experts-exchange.com/questions/29106033/Pydot-having-problems-with-GraphViz.html

**Comment by VanitarNordic** [comment]
if you use Anaconda, you can use  `conda install -c hesi_m tensorflow ` to install **tensorflow 1.9.0** for CPU 

if you specifically use Keras also, you can use  `conda install -c hesi_m keras` which installs **Keras 2.2.2** in accompany with everything including tensorflow 1.9.0

It is better to make a fresh anaconda environment for your experiments
