### ISSUE TITLE
Passing/Retrieving String data to/from TFLite model

### ISSUE THREAD

**Issue by the-dagger** [tensorflow/tensorflow#21213]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
     [Yes, here's the source code](https://github.com/the-dagger/MLKitAndroid/blob/master/app/src/main/java/io/github/the_dagger/mlkit/activity/SmartReplyActivity.kt)
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: OSX, High Sierra
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: Pixel 2XL
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**:  1.9.0
- **Python version**: 2.7
- **Bazel version (if compiling from source)**: 0.15.2-homebrew

### Describe the problem
I am using the smartReply TFLite model with Firebase but couldn't figure out how to pass and retrieve the input data as String to and from my tflite Interpreter.
The default data types are limited to FLOAT32, INT32, UINT8 and INT64 and the documentation nowhere specifies how to provide string input or retrieving String output from a model.

https://firebase.google.com/docs/ml-kit/android/use-custom-models

### Source code / logs

Source code of the app : [https://github.com/the-dagger/MLKitAndroid/blob/master/app/src/main/java/io/github/the_dagger/mlkit/activity/SmartReplyActivity.kt](https://github.com/the-dagger/MLKitAndroid/blob/master/app/src/main/java/io/github/the_dagger/mlkit/activity/SmartReplyActivity.kt)

Stacktrace
```
07-29 00:14:26.286 6489-6489/? W/System.err: Caused by: java.lang.IllegalArgumentException: DataType error: DataType 5 is not recognized in Java (version 3)
        at org.tensorflow.lite.DataType.fromNumber(DataType.java:54)
        at org.tensorflow.lite.Tensor.<init>(Tensor.java:211)
        at org.tensorflow.lite.Tensor.fromHandle(Tensor.java:32)
        at org.tensorflow.lite.NativeInterpreterWrapper.getInputTensor(NativeInterpreterWrapper.java:245)
        at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:110)
        at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:168)
        at com.google.android.gms.internal.firebase_ml.zzho.runForMultipleInputsOutputs(Unknown Source:2)
        at com.google.android.gms.internal.firebase_ml.zzhn.zza(Unknown Source:459)
        at com.google.android.gms.internal.firebase_ml.zzhn.zza(Unknown Source:2)
        at com.google.android.gms.internal.firebase_ml.zzgu.call(Unknown Source:15)
        at com.google.android.gms.internal.firebase_ml.zzgp.zza(Unknown Source:0)
07-29 00:19:17.979 7895-7895/? W/System.err: com.google.firebase.ml.common.FirebaseMLException: Internal error has occurred when executing Firebase ML tasks
        at com.google.android.gms.internal.firebase_ml.zzgp.zza(Unknown Source:15)
        at com.google.android.gms.internal.firebase_ml.zzgq.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
    Caused by: java.lang.IllegalArgumentException: DataType error: DataType 5 is not recognized in Java (version 3)
        at org.tensorflow.lite.DataType.fromNumber(DataType.java:54)
        at org.tensorflow.lite.Tensor.<init>(Tensor.java:211)
```

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by the-dagger** [comment]
CUDA/cuDNN version : N/A
GPU model and memory : N/A
Exact command to reproduce : Running the app results in this exception message.
So possibly either the input or output has an issue.

**Comment by jdduke** [comment]
Hi @the-dagger, thanks for the report. At the moment, the Java API does not support string inputs/outputs. This limitation is definitely on our radar, and something we plan to address in the near future.

Note that properly supporting strings will require some reworking of the current API. In particular, to support dynamically sized outputs, we'll need to decouple extracting output data from interpreter invocation. At the moment, the client needs to know the size of the output *before* invoking the interpreter, but this doesn't map well for dynamic outputs.

**Comment by the-dagger** [comment]
@jdduke Thanks for the heads up, glad to know that this is something that's being worked on.
P.S. would it e possible to hack around and modify the current custom ops that accept a String input to accept a Byte array instead?

I tried this but that ended up with the same DataType 5 error.

**Comment by jdduke** [comment]
So, eventually the string Tensors will actually take byte arrays (see also [TensorFlow's Java Tensor class](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/java/src/main/java/org/tensorflow/Tensor.java#L83)). Eventually we'll relax [this type check](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/lite/java/src/main/java/org/tensorflow/lite/Tensor.java#L182) in TensorFlow Lite's Java Tensor class, but doing so will also require some additional work to interpret the byte array as a String, rather than as a uint8 array (Tensor dimensions for String types have a very different connotation than the dimensions of the uint8 Tensor type).

If you did write a custom op, it would probably be a custom input op which converts a uint8 input Tensor to a String Tensor. Even then, the Java API doesn't support dynamically sized outputs, so there's some additional work required there (all of which is actively being worked on and should be supported in the near future).

**Comment by the-dagger** [comment]
Ok, understood.
That makes sense, thanks a lot!

**Comment by tensorflowbutler** [comment]
Nagging Assignee @jdduke: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by jdduke** [comment]
No concrete updates, it will likely be a few weeks before we can start working on proper string support for the Java API.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @jdduke: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by jdduke** [comment]
Will be prioritizing this in Q4.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @jdduke: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @jdduke: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @jdduke: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @jdduke: It has been 59 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @jdduke: It has been 74 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.
