### ISSUE TITLE
Using Dataset api with Estimator in MirroredStrategy, Dst tensor is not initialized

### ISSUE THREAD

**Issue by Jetcodery** [tensorflow/tensorflow#21260]
### **System information**

- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): centos
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below):1.9.0
- Python version: python 2.7
- Bazel version (if compiling from source): 0.15.0
- GCC/Compiler version (if compiling from source):4.8.5
- CUDA/cuDNN version: 9.0
- GPU model and memory:GeForce GTX 1080Ti * 4
- Exact command to reproduce:
### **Describe the problem**
 In order to solve the problem here:https://github.com/tensorflow/tensorflow/issues/19588, I git clone the master branch of tensorflow and compile it with bazel 0.15.0, then the  "Non-DMA-safe string tensor error" disappeared ,  the training went well , but when the evaluation part start, it ran into this: 
 **'Dst tensor is not initialized'**
it should be a “Not enough memory” problem , what i have tried:

1. tune the batchsize to a very small one
2. set config.gpu_options.per_process_gpu_memory_fraction to a smaller fraction like 0.6
3. set config.gpu_options.allow_growth to True
4. use a small dataset

But none of them can help .

### **Source code / logs**
![image](https://user-images.githubusercontent.com/31854634/43434228-5b6e6356-94ad-11e8-9e8d-e00a2c64bb1a.png)

![image](https://user-images.githubusercontent.com/31854634/43434328-c4f53642-94ad-11e8-8113-554a1c03c5a9.png)

LOG：
(Jet_env_3) [lijiaji@m7-model-gpu05 classification]$ python demo.py 
2018-07-30 11:49:33,994:INFO:tensorflow:Begin configure dataset.
2018-07-30 11:49:34,210:INFO:tensorflow:End configure dataset.
2018-07-30 11:49:34,210:INFO:tensorflow:Mission hyper parameters
2018-07-30 11:49:34,210:INFO:tensorflow:{'adagrad_initial_accumulator_value': 0.1, 'label_list': ['1', '0', '3', '2', '5', '4', '7', '6', '9', '8'], 'learning_rate_decay_factor': 0.94, 'learning_rate_decay_type': 'exponential', 'save_steps': 1000, 'ftrl_initial_accumulator_value': 0.1, 'ftrl_learning_rate_power': -0.5, 'num_train_samples': 48000, 'rmsprop_decay': 0.9, 'weight_decay': 4e-05, 'end_learning_rate': 0.0001, 'num_epochs': 2, 'trainable_scopes': None, 'checkpoint_path': None, 'finetune_flag': 'False', 'rmsprop_momentum': 0.9, 'model_dir': '/home/lijiaji/test_models/multi_gou_test', 'replicas_to_aggregate': 1, 'learning_rate': 0.01, 'momentum': 0.9, 'opt_epsilon': 1.0, 'optimizer': 'momentum', 'num_epochs_per_decay': 2.0, 'label_smoothing': 0.0, 'adam_beta1': 0.9, 'adam_beta2': 0.999, 'batch_size': 32, 'num_classes': 10, 'ftrl_l1': 0.0, 'ftrl_l2': 0.0, 'train_image_size': 224, 'train_dir': '/home/lijiaji/project/augments/mnist', 'moving_average_decay': None, 'sync_replicas': False, 'checkpoint_exclude_scopes': None, 'ignore_missing_vars': False, 'model_name': 'inception_resnet_v2', 'adadelta_rho': 0.95}
2018-07-30 11:49:34,211:INFO:tensorflow:Using config: {'_save_checkpoints_secs': None, '_keep_checkpoint_max': 5, '_task_type': 'worker', '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f0dcd846ed0>, '_keep_checkpoint_every_n_hours': 10000, '_service': None, '_num_ps_replicas': 0, '_tf_random_seed': 912, '_device_fn': None, '_num_worker_replicas': 1, '_task_id': 0, '_log_step_count_steps': 100, '_evaluation_master': '', '_train_distribute': <tensorflow.contrib.distribute.python.mirrored_strategy.MirroredStrategy object at 0x7f0dcd846b90>, '_session_config': gpu_options {
  allow_growth: true
}
allow_soft_placement: true
, '_global_id_in_cluster': 0, '_is_chief': True, '_protocol': None, '_save_checkpoints_steps': 1000, '_save_summary_steps': 1000, '_model_dir': '/home/lijiaji/test_models/multi_gou_test', '_master': ''}
2018-07-30 11:49:34,212:INFO:tensorflow:Starting epoch 1 / 2
2018-07-30 11:49:42,557:INFO:tensorflow:Device is available but not used by distribute strategy: /device:CPU:0
2018-07-30 11:49:42,559:INFO:tensorflow:Device is available but not used by distribute strategy: /device:XLA_GPU:0
2018-07-30 11:49:42,559:INFO:tensorflow:Device is available but not used by distribute strategy: /device:XLA_CPU:0
2018-07-30 11:49:42,559:INFO:tensorflow:Device is available but not used by distribute strategy: /device:GPU:0
2018-07-30 11:49:42,559:INFO:tensorflow:Device is available but not used by distribute strategy: /device:GPU:1
2018-07-30 11:49:42,559:INFO:tensorflow:Configured nccl all-reduce.
2018-07-30 11:49:42,655:INFO:tensorflow:Calling model_fn.
2018-07-30 11:50:09,603:INFO:tensorflow:Calling model_fn.
2018-07-30 11:50:22,764:INFO:tensorflow:batch_all_reduce invoked for batches size = 496 with algorithm = nccl, num_packs = 1, agg_small_grads_max_bytes = 0 and agg_small_grads_max_group = 10
2018-07-30 11:50:34,055:INFO:tensorflow:Done calling model_fn.
2018-07-30 11:50:34,067:INFO:tensorflow:Done calling model_fn.
2018-07-30 11:50:39,149:INFO:tensorflow:Create CheckpointSaverHook.
2018-07-30 11:51:11,985:INFO:tensorflow:Graph was finalized.
2018-07-30 11:51:37,259:INFO:tensorflow:Running local_init_op.
2018-07-30 11:51:38,022:INFO:tensorflow:Done running local_init_op.
2018-07-30 11:52:26,489:INFO:tensorflow:Saving checkpoints for 0 into /home/lijiaji/test_models/multi_gou_test/model.ckpt.
18/07/30 11:53:09 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2018-07-30 11:53:21,956:INFO:tensorflow:loss = 11.345272, step = 0
2018-07-30 11:55:20,779:INFO:tensorflow:global_step/sec: 0.841569
2018-07-30 11:55:20,780:INFO:tensorflow:loss = 1.7503239, step = 100 (118.825 sec)
2018-07-30 11:56:24,385:INFO:tensorflow:global_step/sec: 1.5722
2018-07-30 11:56:24,385:INFO:tensorflow:loss = 1.5974646, step = 200 (63.605 sec)
2018-07-30 11:57:28,862:INFO:tensorflow:global_step/sec: 1.55093
2018-07-30 11:57:28,863:INFO:tensorflow:loss = 1.3371584, step = 300 (64.478 sec)
2018-07-30 11:58:18,151:INFO:tensorflow:Saving checkpoints for 375 into /home/lijiaji/test_models/multi_gou_test/model.ckpt.
2018-07-30 11:58:28,894:INFO:tensorflow:Loss for final step: 1.3792272.
2018-07-30 11:58:28,900:INFO:tensorflow:Begin evaluation of epoch 1
2018-07-30 11:58:28,973:INFO:tensorflow:Calling model_fn.
2018-07-30 11:58:36,515:INFO:tensorflow:Done calling model_fn.
2018-07-30 11:58:36,539:INFO:tensorflow:Starting evaluation at 2018-07-30-03:58:36
2018-07-30 11:58:41,904:INFO:tensorflow:Graph was finalized.
2018-07-30 11:58:41,907:INFO:tensorflow:Restoring parameters from /home/lijiaji/test_models/multi_gou_test/model.ckpt-375
Traceback (most recent call last):
  File "demo.py", line 22, in <module>
    run(config)
  File "/mnt/disk0/home/lijiaji/test_cvalgo/cv_algo/classification/run_classification.py", line 473, in run
    run_impl(args)   
  File "/mnt/disk0/home/lijiaji/test_cvalgo/cv_algo/classification/run_classification.py", line 435, in run_impl
    steps = args.save_steps * 2
  File "/home/lijiaji/anaconda2/envs/Jet_env_3/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 464, in evaluate
    output_dir=self.eval_dir(name))
  File "/home/lijiaji/anaconda2/envs/Jet_env_3/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 1521, in _evaluate_run
    config=self._session_config)
  File "/home/lijiaji/anaconda2/envs/Jet_env_3/lib/python2.7/site-packages/tensorflow/python/training/evaluation.py", line 209, in _evaluate_once
    session_creator=session_creator, hooks=hooks) as session:
  File "/home/lijiaji/anaconda2/envs/Jet_env_3/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 832, in __init__
    stop_grace_period_secs=stop_grace_period_secs)
  File "/home/lijiaji/anaconda2/envs/Jet_env_3/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 555, in __init__
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "/home/lijiaji/anaconda2/envs/Jet_env_3/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1018, in __init__
    _WrappedSession.__init__(self, self._create_session())
  File "/home/lijiaji/anaconda2/envs/Jet_env_3/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1023, in _create_session
    return self._sess_creator.create_session()
  File "/home/lijiaji/anaconda2/envs/Jet_env_3/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 712, in create_session
    self.tf_sess = self._session_creator.create_session()
  File "/home/lijiaji/anaconda2/envs/Jet_env_3/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 483, in create_session
    init_fn=self._scaffold.init_fn)
  File "/home/lijiaji/anaconda2/envs/Jet_env_3/lib/python2.7/site-packages/tensorflow/python/training/session_manager.py", line 281, in prepare_session
    config=config)
  File "/home/lijiaji/anaconda2/envs/Jet_env_3/lib/python2.7/site-packages/tensorflow/python/training/session_manager.py", line 195, in _restore_checkpoint
    saver.restore(sess, checkpoint_filename_with_path)
  File "/home/lijiaji/anaconda2/envs/Jet_env_3/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1727, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/lijiaji/anaconda2/envs/Jet_env_3/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 886, in run
    run_metadata_ptr)
  File "/home/lijiaji/anaconda2/envs/Jet_env_3/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1109, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/lijiaji/anaconda2/envs/Jet_env_3/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1281, in _do_run
    run_metadata)
  File "/home/lijiaji/anaconda2/envs/Jet_env_3/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1300, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Dst tensor is not initialized.
	 [[Node: save/RestoreV2/_1311 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_1315_save/RestoreV2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
	 [[Node: save/RestoreV2/_1438 = _Send[T=DT_FLOAT, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_1443_save/RestoreV2", _device="/job:localhost/replica:0/task:0/device:CPU:0"](save/RestoreV2:719)]]

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Mobile device

**Comment by tensorflowbutler** [comment]
It has been 20 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
It has been 35 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by ymodak** [comment]
The [issue](https://github.com/tensorflow/tensorflow/issues/19588) is resolved and this should fix current issue as well. Closing this issue since fix has been pushed. Feel free to reopen if the issue still persists.
Thanks!
