### ISSUE TITLE
TensorFlow 1.9.0 deadlocks on libc6 2.19?

### ISSUE THREAD

**Issue by ravwojdyla** [tensorflow/tensorflow#21284]
### System information
- **Have I written custom code**: Yes, reproduction repo: https://github.com/ravwojdyla/tf190bug
- **OS Platform and Distribution**: Ubuntu 14.04, Container-Optimized OS
- **TensorFlow installed from (source or binary)**:  binary
- **TensorFlow version (use command below)**: 1.9.0
- **Exact command to reproduce**: see repo https://github.com/ravwojdyla/tf190bug
- **Mobile device**: N/A
- **Python version**: N/A
- **Bazel version**: N/A
- **GCC/Compiler version**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A

### Describe the problem
It seems like TF 1.9.0 deadlocks when used concurrently and linked to libc 2.19 (libpthread?)  (Ubuntu 14.04 and COS to name a some). See the reproduction repo. This is specifically a problem if TF 1.9.0 is used on Google Dataflow worker which  currently ship with libc 2.19. The libc/libpthread is currently just a theory, that said I validated that the reproduction code works fine with libc 2.24 (Ubuntu 16.04).

I might continue investigating this issue, but wanted to double check if this is a known problem?

### Source code / logs

Reproduction repo: https://github.com/ravwojdyla/tf190bug

Stack of one of the threads:

```
"Thread-9" #18 prio=5 os_prio=0 tid=0x00007fa568149800 nid=0x4a runnable [0x00007fa55244e000]
   java.lang.Thread.State: RUNNABLE
        at org.tensorflow.Tensor.allocateScalarBytes(Native Method)
        at org.tensorflow.Tensor.create(Tensor.java:150)
        at org.tensorflow.Tensor.create(Tensor.java:115)
        at org.tensorflow.Tensors.create(Tensors.java:257)
        at sh.rav.TestTF.createTensor(TestTF.java:11)
        at sh.rav.TestTF$1.run(TestTF.java:18)
        at java.lang.Thread.run(Thread.java:745)
```

Those threads are all in runnable state, and in fact they do burn CPU, I checked the native frames as well, it seems like some form of a starvation.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Bazel version
CUDA/cuDNN version
GPU model and memory
Mobile device

**Comment by ravwojdyla** [comment]
hi @shivaniag,
Any update on this? Should I look deeper into this?

**Comment by tensorflowbutler** [comment]
Nagging Assignee @shivaniag: It has been 17 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @shivaniag: It has been 32 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @shivaniag: It has been 47 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @shivaniag: It has been 62 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @shivaniag: It has been 77 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @shivaniag: It has been 92 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by wt-huang** [comment]
Closing as this is resolved.
