### ISSUE TITLE
bfloat16 training with GPUs

### ISSUE THREAD

**Issue by ranjeethks** [tensorflow/tensorflow#21317]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.8.0
- **Python version**: 2.7
- **Bazel version (if compiling from source)**: NA
- **GCC/Compiler version (if compiling from source)**: NA
- **CUDA/cuDNN version**: 9.1/7.1.1
- **GPU model and memory**: NVIDIA GTX 1080 Ti
- **Exact command to reproduce**: shown below

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.
I have two issues, one could be feature request, and the other could be seeking confirmation from the Tensorflow team
I am trying to execute the language model training - https://github.com/okuchaiev/f-lm
the model runs fine with the tf.float16 or tf.float32 datatypes for trainable variables.
However, if the trainable variables are tf.bfloat16 type, I am getting the errors (shown below for two separate cases). 
(line 22 and 24 of https://github.com/okuchaiev/f-lm/blob/master/model_utils.py can affect the datatype of varibles. To define dtype as bfloat16, I changed tf.float16 in line 22 and 24 to tf.bfloat16)

Case 1: Looks are bfloat16 not supported for moving_averages:

Error:

 File "/home/ranjeeths/langModel/f-lm/single_lm_train.py", line 54, in <module>
    tf.app.run()
  File "/home/ranjeeths/MLProj/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "/home/ranjeeths/langModel/f-lm/single_lm_train.py", line 37, in main
    run_train(dataset, hps, os.path.join(FLAGS.logdir, "train"), ps_device="/gpu:0")
  File "/home/ranjeeths/langModel/f-lm/run_utils.py", line 14, in run_train
    model = LM(hps, "train", ps_device)
  File "/home/ranjeeths/langModel/f-lm/language_model.py", line 62, in __init__
    self.train_op = tf.group(*[self.train_op, ema.apply(variables_to_average)])
  File "/home/ranjeeths/MLProj/lib/python2.7/site-packages/tensorflow/python/training/moving_averages.py", line 386, in apply
    var.name)
TypeError: The variables must be half, float, or double: model/lstm_0/lstm_cell/kernel:0

To get this error in executed the code as follows:
export CUDA_VISIBLE_DEVICES=1
SECONDS=604800
LOGSUFFIX=bigLSTM
python /home/ranjeeths/langModel/f-lm/single_lm_train.py --logdir=/home/ranjeeths/langModel/f-lm/log/bigLSTM/$LOGSUFFIX/ --num_gpus=1 --datadir=/home/ranjeeths/langModel/lm/data/lm1b/1-billion-word-language-modeling-benchmark-r13output/ --hpconfig run_profiler=False,max_time=$SECONDS,num_steps=20,num_shards=8,num_layers=2,learning_rate=0.2,max_grad_norm=1,keep_prob=0.9,emb_size=1024,projected_size=1024,state_size=8192,num_sampled=8192,batch_size=256,float16_rnn=True,float16_non_rnn=False,loss_scale=1.0

(with float16_rnn=True, float16_non_rnn=False, the lstm related variables will all be tf.bfloat16 and remaining variables will be tf.float32)

Case 2: Looks like bfloat16 is not supported for 'Floor' operation (and probably many more)?

Error:

Traceback (most recent call last):
  File "/home/ranjeeths/langModel/f-lm/single_lm_train.py", line 54, in <module>
    tf.app.run()
  File "/home/ranjeeths/MLProj/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "/home/ranjeeths/langModel/f-lm/single_lm_train.py", line 37, in main
    run_train(dataset, hps, os.path.join(FLAGS.logdir, "train"), ps_device="/gpu:0")
  File "/home/ranjeeths/langModel/f-lm/run_utils.py", line 40, in run_train
    with sv.managed_session(master, config=config) as sess:
  File "/usr/lib64/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/home/ranjeeths/MLProj/lib/python2.7/site-packages/tensorflow/python/training/supervisor.py", line 1000, in managed_session
    self.stop(close_summary_writer=close_summary_writer)
  File "/home/ranjeeths/MLProj/lib/python2.7/site-packages/tensorflow/python/training/supervisor.py", line 828, in stop
    ignore_live_threads=ignore_live_threads)
  File "/home/ranjeeths/MLProj/lib/python2.7/site-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/home/ranjeeths/MLProj/lib/python2.7/site-packages/tensorflow/python/training/supervisor.py", line 989, in managed_session
    start_standard_services=start_standard_services)
  File "/home/ranjeeths/MLProj/lib/python2.7/site-packages/tensorflow/python/training/supervisor.py", line 726, in prepare_or_wait_for_session
    init_feed_dict=self._init_feed_dict, init_fn=self._init_fn)
  File "/home/ranjeeths/MLProj/lib/python2.7/site-packages/tensorflow/python/training/session_manager.py", line 285, in prepare_session
    sess.run(init_op, feed_dict=init_feed_dict)
  File "/home/ranjeeths/MLProj/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/home/ranjeeths/MLProj/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/ranjeeths/MLProj/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/home/ranjeeths/MLProj/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'Floor' with these attrs.  Registered devices: [CPU,GPU], Registered kernels:
  device='CPU'; T in [DT_DOUBLE]
  device='CPU'; T in [DT_HALF]
  device='CPU'; T in [DT_FLOAT]
  device='GPU'; T in [DT_DOUBLE]
  device='GPU'; T in [DT_HALF]
  device='GPU'; T in [DT_FLOAT]

         [[Node: model/model/dropout/Floor = Floor[T=DT_BFLOAT16, _device="/gpu:0"](model/model/dropout/add)]]

Caused by op u'model/model/dropout/Floor', defined at:
  File "/home/ranjeeths/langModel/f-lm/single_lm_train.py", line 54, in <module>
    tf.app.run()
  File "/home/ranjeeths/MLProj/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "/home/ranjeeths/langModel/f-lm/single_lm_train.py", line 37, in main
    run_train(dataset, hps, os.path.join(FLAGS.logdir, "train"), ps_device="/gpu:0")
  File "/home/ranjeeths/langModel/f-lm/run_utils.py", line 14, in run_train
    model = LM(hps, "train", ps_device)
  File "/home/ranjeeths/langModel/f-lm/language_model.py", line 29, in __init__
    loss = self._forward(i, xs[i], ys[i])
  File "/home/ranjeeths/langModel/f-lm/language_model.py", line 87, in _forward
    x = tf.nn.dropout(x, hps.keep_prob)
  File "/home/ranjeeths/MLProj/lib/python2.7/site-packages/tensorflow/python/ops/nn_ops.py", line 2318, in dropout
    binary_tensor = math_ops.floor(random_tensor)
  File "/home/ranjeeths/MLProj/lib/python2.7/site-packages/tensorflow/python/ops/gen_math_ops.py", line 2811, in floor
    "Floor", x=x, name=name)
  File "/home/ranjeeths/MLProj/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/ranjeeths/MLProj/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/home/ranjeeths/MLProj/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): No OpKernel was registered to support Op 'Floor' with these attrs.  Registered devices: [CPU,GPU], Registered kernels:
  device='CPU'; T in [DT_DOUBLE]
  device='CPU'; T in [DT_HALF]
  device='CPU'; T in [DT_FLOAT]
  device='GPU'; T in [DT_DOUBLE]
  device='GPU'; T in [DT_HALF]
  device='GPU'; T in [DT_FLOAT]

         [[Node: model/model/dropout/Floor = Floor[T=DT_BFLOAT16, _device="/gpu:0"](model/model/dropout/add)]]

To get this error in executed the code as follows:
export CUDA_VISIBLE_DEVICES=1
SECONDS=604800
LOGSUFFIX=bigLSTM
python /home/ranjeeths/langModel/f-lm/single_lm_train.py --logdir=/home/ranjeeths/langModel/f-lm/log/bigLSTM/$LOGSUFFIX/ --num_gpus=1 --datadir=/home/ranjeeths/langModel/lm/data/lm1b/1-billion-word-language-modeling-benchmark-r13output/ --hpconfig run_profiler=False,max_time=$SECONDS,num_steps=20,num_shards=8,num_layers=2,learning_rate=0.2,max_grad_norm=1,keep_prob=0.9,emb_size=1024,projected_size=1024,state_size=8192,num_sampled=8192,batch_size=256,float16_rnn=False,float16_non_rnn=True,loss_scale=1.0

(with float16_rnn=False, float16_non_rnn=True, the lstm related variables will all be tf.float32 and remaining variables will be tf.bfloat16)

I am not sure if bfloat16 is supported for all operations (not just the ones mentioned above), or whether these errors are due to the fact that I am not using a TPU (I am using a GPU GTX 1080 now). If I use run the above code on a TPU do you think I wont be getting any more errors?

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Comment by rjpower** [comment]
`bfloat16` support isn't complete for GPUs, as it's not supported natively by the devices.

For performance you'll want to use float32 or float16 for GPU execution (though float16 can be difficult to train models with).  TPUs support bfloat16 for effectively all operations (but you currently have to migrate your model to work on the TPU).

**Comment by rjpower** [comment]
When training with bfloat16 we recommend using float32 for variables, and bfloat16 for operations.  There is a helper scope to make this easier: https://www.tensorflow.org/api_docs/python/tf/contrib/tpu/bfloat16_scope

Unfortunately, we don't have a documented API outside of TPUEstimator at the moment.  This will likely come in TF 1.11.  If you're using a Keras model, you can use `tf.contrib.tpu.keras_to_tpu_model` to convert your model.  You can also inspect  `keras_support.py` for examples of the lower-level interface.  At this time we can't support the use of it, so you're on your own in the short-term if you want to go this route.

**Comment by ranjeethks** [comment]
Thank you very much! I will keep variables in FP32 as suggested. Can you suggest how can we specify either bfloat16 or float32 type for operations?

**Comment by rjpower** [comment]
We normally use the bfloat16_scope to automatically adjust operations
inside, e.g.:

with tf.contrib.tpu.bfloat16_scope():
  x = y * z

You can also specify an explicit `dtype` on some ops, or cast the inputs to
bfloat16 (ops preserve the type of their inputs).
