### ISSUE TITLE
FusedBatchNorm of TF 1.9 doesn't work fine 

### ISSUE THREAD

**Issue by haifenghan** [tensorflow/tensorflow#21328]
After importing the frozen model [mobilenet_v2_1.0_224](https://storage.googleapis.com/mobilenet_v2/checkpoints/mobilenet_v2_1.0_224.tgz), I find there are 4 outputs of FusedBatchNorm operation and I can't eval() other 3 tensors:

### System information
- **Ubuntu 18.04 desktop
- **TensorFlow installed from (source or binary)**: binary(pip)
- **TensorFlow version (use command below)**: 1.9
- **Python version**: 2.7.15rc1
- **CUDA/cuDNN version**: CPU only
- **Exact command to reproduce**:
```
ipdb> batch_norm = tf.get_default_graph().get_operation_by_name('MobilenetV2/expanded_conv/depthwise/BatchNorm/FusedBatchNorm')                  
ipdb> batch_norm.outputs
[<tf.Tensor 'MobilenetV2/expanded_conv/depthwise/BatchNorm/FusedBatchNorm:0' shape=(1, 112, 112, 32) dtype=float32>, <tf.Tensor 'MobilenetV2/expan
ded_conv/depthwise/BatchNorm/FusedBatchNorm:1' shape=(32,) dtype=float32>, <tf.Tensor 'MobilenetV2/expanded_conv/depthwise/BatchNorm/FusedBatchNor
m:2' shape=(32,) dtype=float32>, <tf.Tensor 'MobilenetV2/expanded_conv/depthwise/BatchNorm/FusedBatchNorm:3' shape=(32,) dtype=float32>, <tf.Tenso
r 'MobilenetV2/expanded_conv/depthwise/BatchNorm/FusedBatchNorm:4' shape=(32,) dtype=float32>]                                                   
ipdb> batch_norm.outputs[1].eval()
Optimizing fused batch norm node name: "MobilenetV2/expanded_conv/depthwise/BatchNorm/FusedBatchNorm"                                            
op: "FusedBatchNorm"
input: "MobilenetV2/expanded_conv/depthwise/depthwise"
input: "Const_198"                                                                                                                               
input: "Const_37"
input: "Const_138"
input: "Const_120"
device: "/job:localhost/replica:0/task:0/device:CPU:0"
attr {
  key: "T"
  value {
    type: DT_FLOAT
  }
}
attr {
  key: "data_format"
  value {
    s: "NHWC"
  }
}
attr {
  key: "epsilon"
  value {
    f: 0.001
  }
}
attr {
  key: "is_training"
  value {
    b: false
  }
}

*** InvalidArgumentError: FetchOutputs MobilenetV2/expanded_conv/depthwise/BatchNorm/FusedBatchNorm:1: output index too large, must be < 1

```

BTW, TensorFlow 1.8 works fine.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
Bazel version
GPU model and memory
Mobile device

**Comment by haifenghan** [comment]
Thanks for your response.
Additional information is as follows:

- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: 
No, all nodes are imported from the frozen graph.
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 
Ubuntu 18.04
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: 
Not in mobile device.
- **Bazel version (if compiling from source)**: 
0.16.0
- **GPU model and memory**:
 No GPU

**Comment by rohan100jain** [comment]
@marksandler2 can you take a look?

**Comment by marksandler2** [comment]
Can you describe what are you trying to achieve? The outputs 1-3 of fused batchnorm are meant as for   tensorflow access during training,   that you normally wouldn't need to access directly.  Particulaly if mode is_training is set ot False, then these nodes are often optimized away by the optimizer. 

If you want another look please make reproducible example in colab.  (you can use mobilentev2's ipynb as a strating point).

**Comment by haifenghan** [comment]
When running the following example code, I get error message which doesn't exist in TF 1.8.

```
import tensorflow as tf
import numpy as np

sess = tf.Session()
sess.as_default()

with tf.gfile.FastGFile('mobilenet_v2_1.0_224_frozen.pb', 'rb') as f:
    sess.graph.as_default()
    graph_def = tf.GraphDef()
    graph_def.ParseFromString(f.read())

input_data = np.random.randn(1,224,224,3)

input_data = tf.convert_to_tensor(input_data, dtype=tf.float32)
tf.import_graph_def(graph_def, name="", input_map={'input:0':input_data})
batch_norm = tf.get_default_graph().get_operation_by_name('MobilenetV2/expanded_conv/depthwise/BatchNorm/FusedBatchNorm')
out = sess.run(batch_norm.outputs[1])
print out

```

Error is as follow:
```
Optimizing fused batch norm node name: "MobilenetV2/expanded_conv/depthwise/BatchNorm/FusedBatchNorm"                                            
op: "FusedBatchNorm"                                                                                                                             
input: "MobilenetV2/expanded_conv/depthwise/depthwise"
input: "Const_198"                                                                                                                               
input: "Const_37"
input: "Const_138"                                                                                                                               
input: "Const_120"
device: "/job:localhost/replica:0/task:0/device:CPU:0"                                                                                           
attr {
  key: "T"                                                                                                                                       
  value {
    type: DT_FLOAT                                                                                                                               
  }
}
attr {
  key: "data_format"
  value {
    s: "NHWC"
  }
}
attr {
  key: "epsilon"
  value {
    f: 0.001
  }
}
attr {
  key: "is_training"                                                                                                                             
  value {
    b: false
  }                                     
Traceback (most recent call last):
  File "test.py", line 17, in <module>
    out = sess.run(batch_norm.outputs[1])
  File "/home/haifeng/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/home/haifeng/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/haifeng/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/home/haifeng/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: FetchOutputs MobilenetV2/expanded_conv/depthwise/BatchNorm/FusedBatchNorm:1: output
index too large, must be < 1

```

**Comment by haifenghan** [comment]
@marksandler2 I can't access google colab due to internet limitation. Sorry for this. Please try above reproducible example

**Comment by marksandler2** [comment]
See my comment above.

There is no second-and-third output in FusedBatchNorm operator when created in evaluation mode (which is what frozen proto contains).  
So you get out-of-range error because there is no such node,  this is working as expected. 

If you want to create network in training mode you need to use the python code and restore from checkpoint. But even then it is unclear what yo uare trying to do. 

```python
import tensorflow as tf
from nets.mobilenet import mobilenet_v2

tf.reset_default_graph()

# For simplicity we just decode jpeg inside tensorflow.
# But one can provide any input obviously.
file_input = tf.placeholder(tf.string, ())

image = tf.image.decode_jpeg(tf.read_file(file_input))

images = tf.expand_dims(image, 0)
images = tf.cast(images, tf.float32) / 128.  - 1
images.set_shape((None, None, None, 3))
images = tf.image.resize_images(images, (224, 224))

# Note: arg_scope is optional for inference.
with tf.contrib.slim.arg_scope(mobilenet_v2.training_scope(is_training=False)):
  logits, endpoints = mobilenet_v2.mobilenet(images)
  
# Restore using exponential moving average since it produces (1.5-2%) higher 
# accuracy
ema = tf.train.ExponentialMovingAverage(0.999)
vars = ema.variables_to_restore()

saver = tf.train.Saver(vars)  
from IPython import display
import pylab
from datasets import imagenet
import PIL
display.display(display.Image('panda.jpg'))

with tf.Session() as sess:
  saver.restore(sess,  checkpoint)
  x = endpoints['Predictions'].eval(feed_dict={file_input: 'panda.jpg'})
label_map = imagenet.create_readable_names_for_imagenet_labels()  
print("Top 1 prediction: ", x.argmax(),label_map[x.argmax()], x.max())


```



If you need further help, please explain what are you trying to do.

**Comment by haifenghan** [comment]
I want to evaluate all the output of FusedBatchNorm. The easy way to get it/them is to run the following code `sess.run(batch_norm.outputs[:]`. I'll get an error in TF 1.10 now:
```
ipdb> out = sess.run(batch_norm.outputs[:])
*** OutOfRangeError: Node 'MobilenetV2/expanded_conv/depthwise/BatchNorm/FusedBatchNorm' (type: 'Const', num of outputs: 1) does not have output 1 
```
However,  if we see the length of `batch_norm`, it's `5`.

**Comment by marksandler2** [comment]
There is nothing to evaluate - the frozen inference graph have  a trivial
(constant) BatchNorm tensor.  If you want to evaluate batch-norm outputs  -
you need to create real training graph, not frozen graph.

**Comment by marksandler2** [comment]
Interestingly even frozen graph have FusedBatchNorm that technically has 5
outputs, but tensorflow refuses to evaluate them.  I didn't check the
details, but fusedbatchnorm outptuts [1:5] are undocumented, so perhaps
graphs freezing destroys
them somehow..

Anyway:  this code works fine:

import tensorflow as tf
from nets.mobilenet import mobilenet_v2

tf.reset_default_graph()

# For simplicity we just decode jpeg inside tensorflow.
# But one can provide any input obviously.
file_input = tf.placeholder(tf.string, ())

image = tf.image.decode_jpeg(tf.read_file(file_input))

images = tf.expand_dims(image, 0)
images = tf.cast(images, tf.float32) / 128.  - 1
images.set_shape((None, None, None, 3))
images = tf.image.resize_images(images, (224, 224))

# Note: arg_scope is optional for inference.
with
tf.contrib.slim.arg_scope(mobilenet_v2.training_scope(is_training=False)):
  logits, endpoints = mobilenet_v2.mobilenet(images)

# Restore using exponential moving average since it produces (1.5-2%)
higher
# accuracy
ema = tf.train.ExponentialMovingAverage(0.999)
vars = ema.variables_to_restore()

saver = tf.train.Saver(vars)
g = tf.get_default_graph()
op =
g.get_operation_by_name('MobilenetV2/expanded_conv/depthwise/BatchNorm/FusedBatchNorm')
with tf.Session() as sess:
  saver.restore(sess,  checkpoint)
  x = endpoints['Predictions'].eval(feed_dict={file_input: 'panda.jpg'})
  print(op.outputs[1].eval(feed_dict={file_input: 'panda.jpg'}))
label_map = imagenet.create_readable_names_for_imagenet_labels()
print("Top 1 prediction: ", x.argmax(),label_map[x.argmax()], x.max())

**Comment by marksandler2** [comment]
Interestingly even frozen graph have FusedBatchNorm that technically has 5
outputs, but tensorflow refuses to evaluate them.  I didn't check the
details, but fusedbatchnorm outptuts [1:5] are undocumented, so perhaps
graphs freezing destroys
them somehow..

Anyway:  this code works fine:

```python
import tensorflow as tf
from nets.mobilenet import mobilenet_v2
tf.reset_default_graph()

# For simplicity we just decode jpeg inside tensorflow.
# But one can provide any input obviously.
file_input = tf.placeholder(tf.string, ())

image = tf.image.decode_jpeg(tf.read_file(file_input))

images = tf.expand_dims(image, 0)
images = tf.cast(images, tf.float32) / 128.  - 1
images.set_shape((None, None, None, 3))
images = tf.image.resize_images(images, (224, 224))

# Note: arg_scope is optional for inference.
with
tf.contrib.slim.arg_scope(mobilenet_v2.training_scope(is_training=False)):
  logits, endpoints = mobilenet_v2.mobilenet(images)

# Restore using exponential moving average since it produces (1.5-2%)
higher
# accuracy
ema = tf.train.ExponentialMovingAverage(0.999)
vars = ema.variables_to_restore()

saver = tf.train.Saver(vars)
g = tf.get_default_graph()
op =
g.get_operation_by_name('MobilenetV2/expanded_conv/depthwise/BatchNorm/FusedBatchNorm')
with tf.Session() as sess:
  saver.restore(sess,  checkpoint)
  x = endpoints['Predictions'].eval(feed_dict={file_input: 'panda.jpg'})
  print(op.outputs[1].eval(feed_dict={file_input: 'panda.jpg'}))
label_map = imagenet.create_readable_names_for_imagenet_labels()
print("Top 1 prediction: ", x.argmax(),label_map[x.argmax()], x.max())
```

**Comment by haifenghan** [comment]
Thanks @marksandler2 

I tried your code and it works fine.  we can evaluate all output of the FusedBatchNorm.

It seems the frozen graph has a compatibility issue with latest TensorFlow. 
Only TF1.8 or earlier version can correctly evaluate outputs of the fused batchnorm in the frozen graph.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @rohan100jain: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @rohan100jain: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @rohan100jain: It has been 45 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @rohan100jain: It has been 59 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @rohan100jain: It has been 74 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @rohan100jain: It has been 90 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @rohan100jain: It has been 105 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by mohantym** [comment]
Hi @haifenghan !
It seems you are using older versions(1.x versions) of Tensorflow. We recommend that you upgrade  your code base to 2.x  versions as many features and bug fixes has been done in newer versions and let us know if the issue still persists in newer versions. Thanks!

**Comment by haifenghan** [comment]
Thanks for your suggestion

**Comment by mohantym** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
