### ISSUE TITLE
TensorFlow 1.9.0 fails on aarch64 platforms

### ISSUE THREAD

**Issue by psyhtest** [tensorflow/tensorflow#21332]
Building TensorFlow 1.9.0 from source fails on aarch64 platforms (NVIDIA TX1 and Linaro HiKey960) due to using an inappropriate compiler flag (`-mfpu=neon`):
```
ERROR: /home/anton/CK_TOOLS/lib-tensorflow-src-cpu-1.9-compiler.python-2.7.12-linux-64/src/tensorflow/contrib/lite/kernels/internal/BUILD:359:1: C++ compilation of rule '//tensorflow/contrib/lite/kernels/internal:tensor_utils' failed (Exit 1)
gcc: error: unrecognized command line option '-mfpu=neon'
```

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: N/A (a build problem)
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04 (JetPack 3.1)
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 1.9.0
- **Python version**: 2.7.12
- **Bazel version (if compiling from source)**: 0.15.2
- **GCC/Compiler version (if compiling from source)**: 5.5.0
- **CUDA/cuDNN version**: N/A (CPU ony)
- **GPU model and memory**: N/A (CPU only)
- **Exact command to reproduce**: Install dependencies and build via [CK-TensorFlow](github.com/ctuning/ck-tensorflow):
```
$ sudo apt install liblapack-dev libatlas-dev
$ sudo pip install enum34 mock pillow wheel absl-py scipy ck
$ ck pull repo:ck-tensorflow
$ ck install ck-env:package:tool-bazel-0.15.2-linux
$ ck install package:lib-tensorflow-1.9.0-src-cpu --env.CK_HOST_CPU_NUMBER_OF_PROCESSORS=1
```
**NB:** Restricting the number of building processes to 1 is necessary to prevent running out of memory on the NVIDIA TX1 platform (4 GB and no swap enabled) or similar.

### Describe the problem

Building TensorFlow 1.9.0 fails on aarch64 platforms (NVIDIA TX1 and Linaro HiKey960). Similar instructions for TensorFlow 1.7.0 with Bazel 0.11.1 worked well:
```
$ ck install package:lib-tensorflow-1.7.0-src-cpu --env.CK_HOST_CPU_NUMBER_OF_PROCESSORS=1
$ ck install package:lib-tensorflow-1.7.0-src-cpu-xla --env.CK_HOST_CPU_NUMBER_OF_PROCESSORS=1

$ ck show env --tags=tensorflow,v1.7
Env UID:         Target OS: Bits: Name:                                       Version: Tags:

ed191cc45dda7ee4   linux-64    64 TensorFlow library (from sources, cpu, xla) 1.7      64bits,bazel,channel-stable,host-os-linux-64,lib,needs-bazel,needs-bazel-0.11.1,target-os-linux-64,tensorflow,tensorflow-cpu,v1,v1.7,v1.7.0,vcpu,vsrc,vxla
ed191cc45dda7ee3   linux-64    64 TensorFlow library (from sources, cpu)      1.7      64bits,bazel,channel-stable,host-os-linux-64,lib,needs-bazel,needs-bazel-0.11.1,target-os-linux-64,tensorflow,tensorflow-cpu,v1,v1.7,v1.7.0,vcpu,vsrc
```
They also worked for TensorFlow 1.8.0 with Bazel 0.13.0 after [including a patch](
https://github.com/tensorflow/tensorflow/issues/18643#issuecomment-386245419
) into the CK package:

```
$ sudo apt install liblapack-dev libatlas-dev
$ sudo pip install enum34 mock pillow wheel absl-py scipy ck
$ ck pull repo:ck-tensorflow
$ ck install ck-env:package:tool-bazel-0.13.0-linux
$ ck install package:lib-tensorflow-1.8.0-src-cpu [--env.CK_HOST_CPU_NUMBER_OF_PROCESSORS=1]
```

### Source code / logs
After about 10 hours, the build failed:
```
ERROR: /home/anton/CK_TOOLS/lib-tensorflow-src-cpu-1.9-compiler.python-2.7.12-linux-64/src/tensorflow/contrib/lite/kernels/internal/BUILD:359:1: C++ compilation of rule '//tensorflow/contrib/lite/kernels/internal:tensor_utils' failed (Exit 1)
gcc: error: unrecognized command line option '-mfpu=neon'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
```

**Comment by freedomtan** [comment]
I have a PR (https://github.com/tensorflow/tensorflow/pull/16175) for this.

**Comment by psyhtest** [comment]
Thanks @freedomtan!

**Comment by psyhtest** [comment]
@freedomtan's patch has helped me to make progress but only to find out about another failure to build TF 1.9 on aarch64 platforms:
```
ERROR: /home/anton/CK_TOOLS/lib-tensorflow-src-cpu-1.9-compiler.python-2.7.12-linux-64/src/tensorflow/contrib/lite/kernels/BUILD:128:1: C++ compilation of rule '//tensorflow/contrib/lite/kernels:builtin_ops' failed (Exit 1)
In file included from ./tensorflow/contrib/lite/kernels/internal/optimized/depthwiseconv_uint8.h:21:0,
                 from tensorflow/contrib/lite/kernels/depthwise_conv.cc:26:
./tensorflow/contrib/lite/kernels/internal/optimized/depthwiseconv_uint8_3x3_filter.h:80:43: error: expected primary-expression before ',' token
 static_assert(offsetof(DepthwiseConvParams, input_depth) ==
                                           ^
./tensorflow/contrib/lite/kernels/internal/optimized/depthwiseconv_uint8_3x3_filter.h:80:45: error: 'input_depth' was not declared in this scope
 static_assert(offsetof(DepthwiseConvParams, input_depth) ==
                                             ^
./tensorflow/contrib/lite/kernels/internal/optimized/depthwiseconv_uint8_3x3_filter.h:80:56: error: 'offsetof' was not declared in this scope
 static_assert(offsetof(DepthwiseConvParams, input_depth) ==
                                                        ^
...
```
Now, peeking into `tensorflow/contrib/lite/kernels/internal/optimized/depthwiseconv_uint8_3x3_filter.h` revealed the following case of conditional compilation excluding practically all of the file (full of inline assembly):
```
// Enable for arm64 except for the Nvidia Linux 4 Tegra (L4T) running on
// Jetson TX-2. This compiler does not support the offsetof() macro.
#if defined(__aarch64__) && !defined(GOOGLE_L4T)
```
Now, that's at the same time both too specific (why only TX2, not TX1, HiKey960 or any other target?) and not specific (which compiler? gcc-5?)

**Comment by psyhtest** [comment]
There are 20 occurrences of `offsetof` under `src/tensorflow`:
```
$ grep offsetof * -R 
contrib/lite/kernels/internal/optimized/depthwiseconv_uint8_3x3_filter.h:// Jetson TX-2. This compiler does not support the offsetof() macro.
contrib/lite/kernels/internal/optimized/depthwiseconv_uint8_3x3_filter.h:static_assert(offsetof(DepthwiseConvParams, input_depth) ==
contrib/lite/kernels/internal/optimized/depthwiseconv_uint8_3x3_filter.h:static_assert(offsetof(DepthwiseConvParams, input_row_size) ==
contrib/lite/kernels/internal/optimized/depthwiseconv_uint8_3x3_filter.h:static_assert(offsetof(DepthwiseConvParams, output_depth) ==
contrib/lite/kernels/internal/optimized/depthwiseconv_uint8_3x3_filter.h:static_assert(offsetof(DepthwiseConvParams, output_row_size) ==
contrib/lite/kernels/internal/optimized/depthwiseconv_uint8_3x3_filter.h:static_assert(offsetof(DepthwiseConvParams, input_offset) ==
contrib/lite/kernels/internal/optimized/depthwiseconv_uint8_3x3_filter.h:static_assert(offsetof(DepthwiseConvParams, output_offset) ==
contrib/lite/kernels/internal/optimized/depthwiseconv_uint8_3x3_filter.h:static_assert(offsetof(DepthwiseConvParams, filter_offset) ==
contrib/lite/kernels/internal/optimized/depthwiseconv_uint8_3x3_filter.h:static_assert(offsetof(DepthwiseConvParams, output_multiplier) ==
contrib/lite/kernels/internal/optimized/depthwiseconv_uint8_3x3_filter.h:static_assert(offsetof(DepthwiseConvParams, output_activation_min) ==
contrib/lite/kernels/internal/optimized/depthwiseconv_uint8_3x3_filter.h:static_assert(offsetof(DepthwiseConvParams, output_activation_max) ==
contrib/lite/kernels/internal/optimized/depthwiseconv_uint8_3x3_filter.h:static_assert(offsetof(DepthwiseConvParams, output_shift) ==
contrib/lite/kernels/internal/optimized/depthwiseconv_uint8_3x3_filter.h:static_assert(offsetof(DepthwiseConvParams, input_width) ==
contrib/lite/kernels/internal/optimized/depthwiseconv_uint8_3x3_filter.h:static_assert(offsetof(DepthwiseConvParams, input_height) ==
contrib/lite/kernels/internal/optimized/depthwiseconv_uint8_3x3_filter.h:static_assert(offsetof(DepthwiseConvParams, output_width) ==
contrib/lite/kernels/internal/optimized/depthwiseconv_uint8_3x3_filter.h:static_assert(offsetof(DepthwiseConvParams, output_height) ==
contrib/lite/kernels/internal/optimized/depthwiseconv_uint8.h:// Jetson TX-2. This compiler does not support the offsetof() macro.
python/eager/pywrap_tensor.cc:    offsetof(EagerTensor, weakreflist), /* tp_weaklistoffset */
stream_executor/cuda/cuda_helpers.h:static_assert(offsetof(cuComplex, x) == 0,
stream_executor/cuda/cuda_helpers.h:static_assert(offsetof(cuDoubleComplex, x) == 0,
```
I suspect this feature has crept into TF via TFLite, and requires compiler support (e.g. [gcc-7.1+](https://github.com/gcc-mirror/gcc/blob/gcc-7_1_0-release/gcc/ginclude/stddef.h#L416-L417)).

The same `grep` for TF 1.8 and 1.7 returns only two occurrences:
```
anton@tegra-ubuntu:~/CK_TOOLS/lib-tensorflow-src-cpu-1.8-linux-64/src/tensorflow$ grep offsetof * -R 
stream_executor/cuda/cuda_helpers.h:static_assert(offsetof(cuComplex, x) == 0,
stream_executor/cuda/cuda_helpers.h:static_assert(offsetof(cuDoubleComplex, x) == 0,
anton@tegra-ubuntu:~/CK_TOOLS/lib-tensorflow-src-cpu-1.7-linux-64/src/tensorflow$ grep offsetof * -R 
stream_executor/cuda/cuda_helpers.h:static_assert(offsetof(cuComplex, x) == 0,
stream_executor/cuda/cuda_helpers.h:static_assert(offsetof(cuDoubleComplex, x) == 0,
```

**Comment by psyhtest** [comment]
However, I have the same failure on HiKey960 with gcc-7.2.

**Comment by psyhtest** [comment]
The following patch (commenting out all lines mentioning `offsetof` in `depthwiseconv_uint8_3x3_filter.h`):
```
anton@hikey962:~/CK_REPOS/ck-tensorflow$ cat package/lib-tensorflow-1.9.0-src-cpu/patch.linux/offsetof-off.patch
diff --git a/tensorflow/contrib/lite/kernels/internal/optimized/depthwiseconv_uint8_3x3_filter.h b/tensorflow/contrib/lite/kernels/internal/optimized/depthwiseconv_uint8_3x3_filter.h
index 8cd72239e9..a7c4cf8f76 100644
--- a/tensorflow/contrib/lite/kernels/internal/optimized/depthwiseconv_uint8_3x3_filter.h
+++ b/tensorflow/contrib/lite/kernels/internal/optimized/depthwiseconv_uint8_3x3_filter.h
@@ -76,7 +76,7 @@ struct DepthwiseConvParams {
 #define OFFSET_INPUT_HEIGHT 64
 #define OFFSET_OUTPUT_WIDTH 68
 #define OFFSET_OUTPUT_HEIGHT 72
-
+#if 0
 static_assert(offsetof(DepthwiseConvParams, input_depth) ==
                   OFFSET_INPUT_DEPTH, "");
 static_assert(offsetof(DepthwiseConvParams, input_row_size) ==
@@ -107,7 +107,7 @@ static_assert(offsetof(DepthwiseConvParams, output_width) ==
                   OFFSET_OUTPUT_WIDTH, "");
 static_assert(offsetof(DepthwiseConvParams, output_height) ==
                   OFFSET_OUTPUT_HEIGHT, "");
-
+#endif
 template <int32 kDepth, int32 kStrideWidth, int32 kStrideHeight>
 struct DepthwiseConvWindow {};
```
allowed me to complete the build on HiKey960:
```
anton@hikey962:~/CK_REPOS/ck-tensorflow/package/lib-tensorflow-1.9.0-src-cpu$ ck install \
--env.CK_HOST_CPU_NUMBER_OF_PROCESSORS=2 --rebuild
...
Environment entry added (89bab7b66c62ba7e)!

Recording CK configuration to /home/anton/CK_TOOLS/lib-tensorflow-src-cpu-1.9-compiler.python-2.7.13-linux-64/ck-install.json ...

Installation path: /home/anton/CK_TOOLS/lib-tensorflow-src-cpu-1.9-compiler.python-2.7.13-linux-64
```

Of course, it cannot be considered a proper fix, but I've committed it as a workaround to `ck-tensorflow:package:lib-tensorflow-1.9.0-src-cpu`. One can test it as follows:
```
$ ck install package:lib-tensorflow-1.9.0-src-cpu --env.CK_HOST_CPU_NUMBER_OF_PROCESSORS=1
```
(See full CK instructions above.)

**Comment by psyhtest** [comment]
Just a note that the above worked with Python 2.7 only. With Python 3.5 it failed:
```
INFO: From Compiling tensorflow/python/framework/fast_tensor_util.cpp:
In file included from bazel-out/arm-opt/genfiles/external/local_config_python/numpy_include/numpy/ndarraytypes.h:1821:0,
                 from bazel-out/arm-opt/genfiles/external/local_config_python/numpy_include/numpy/ndarrayobject.h:18,
                 from bazel-out/arm-opt/genfiles/external/local_config_python/numpy_include/numpy/arrayobject.h:4,
                 from bazel-out/arm-opt/genfiles/tensorflow/python/framework/fast_tensor_util.cpp:531:
bazel-out/arm-opt/genfiles/external/local_config_python/numpy_include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
ERROR: /home/anton/CK_TOOLS/lib-tensorflow-src-cpu-1.9-compiler.python-3.5.2-linux-64/src/tensorflow/BUILD:541:1: Executing genrule //tensorflow:python_api_gen failed (Exit 1)
Traceback (most recent call last):
  File "/home/anton/.cache/bazel/_bazel_anton/6d1d19b4e763685a94d885534baf7158/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/tools/api/generator/create_python_api.runfiles/org_tensorflow/tensorflow/tools/api/generator/create_python_api.py", line 27, in <module>
    from tensorflow.python.util import tf_decorator
  File "/home/anton/.cache/bazel/_bazel_anton/6d1d19b4e763685a94d885534baf7158/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/tools/api/generator/create_python_api.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/home/anton/.cache/bazel/_bazel_anton/6d1d19b4e763685a94d885534baf7158/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/tools/api/generator/create_python_api.runfiles/org_tensorflow/tensorflow/core/framework/graph_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/__init__.py", line 37, in <module>
    __import__('pkg_resources').declare_namespace(__name__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2952, in _initialize_master_working_set
    add_activation_listener(lambda dist: dist.activate())
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 956, in subscribe
    callback(dist)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2952, in <lambda>
    add_activation_listener(lambda dist: dist.activate())
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2515, in activate
    declare_namespace(pkg)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2097, in declare_namespace
    _handle_ns(packageName, path_item)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2047, in _handle_ns
    _rebuild_mod_path(path, packageName, module)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2066, in _rebuild_mod_path
    orig_path.sort(key=position_in_sys_path)
AttributeError: '_NamespacePath' object has no attribute 'sort'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 36844.569s, Critical Path: 170.55s
INFO: 4722 processes: 4722 local.
FAILED: Build did NOT complete successfully
```
What's weird is that I used NumPy 1.11 with Python 2, and NumPy 1.15 with Python 3.

**Comment by freedomtan** [comment]
@psyhtest FYR, I was able to build pip package for Python 3.6 last week, so mostly it's problem of your environment?

**Comment by psyhtest** [comment]
@freedomtan I can hardly call it "mine" :). It's a standard TX1 environment, and TX1 is a very popular board. 

It's very disheartening to see that the TensorFlow community enables support for aarch64 platforms only one platform at a time (notably, only Raspberry Pi is properly supported).

**Comment by freedomtan** [comment]
@psyhtest I guess no Google TensorFlow guys are really working on AArch64 linux platforms. That's why nobody reviewed the PR I sent in in Jan. Yes, RPI 3s are on ARMv8 SoC, but Raspbian for RPI 3 is actually running AArch32 kernel and user space. I started building TensorFlow on ARM64 Debian env because I wanted to have better debugging and profiling env than Android AArch64 devices.

The Debian rootfs I am using is from deboostrap arm64 [1], so I think I am using the "authentic" standard Debian env. I know TX1 is quite popular, but I don't have access it. If there is no TensorFlow guys working on it. I think you should ask NVIDIA to support it or "use the source" and "scratch your own itch".

[1] https://wiki.debian.org/Arm64Port#Debootstrap_arm64
[2] http://catb.org/jargon/html/U/UTSL.html

**Comment by psyhtest** [comment]
Thanks @freedomtan. That perfectly matches my understanding.

> I think you should ask NVIDIA to support it or "use the source" and "scratch your own itch".

As far as I know, NVIDIA do not recommend using TensorFlow on the TXs because it's slow and consumes too much memory. Google suggest to use TFLite now, but it seems to share the same build problems. Given the situation, I'd switch to an alternative framework e.g. MXNet or Caffe2, and recommend our community to do the same. If my response makes Google guys angry (and thus reluctant to fix this problem), it will just prove the point :)).

**Comment by tensorflowbutler** [comment]
Nagging Assignee @alanchiao: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by fferroni** [comment]
Did you manage to get a proper solution? I am experiencing the same problem on 1.10 (DrivePX2)

**Comment by tensorflowbutler** [comment]
Nagging Assignee @case540: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by vielmetti** [comment]
Is there any update @case540 ?

**Comment by NPetsky** [comment]
Hi, nvidia has wheels for different tensorflow versions (up to 1.11) and JetPack and Python versions here (should work for TX1 and TX2 but havn't tried): https://devtalk.nvidia.com/default/topic/1031300/jetson-tx2/tensorflow-1-11-0-wheel-with-jetpack-3-3/1
Another approach is building tensorflow with makefile (no python and GPU support), that worked for me on the TX1

**Comment by tensorflowbutler** [comment]
Nagging Assignee @case540: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @case540: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @case540: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @case540: It has been 59 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by jdduke** [comment]
Is this still failing with the latest TensorFlow source/build?

**Comment by alanchiao** [comment]
Sorry I never got around to fixing this.

@jdduke : this should still be failing on the specific platforms that Anton and others mentioned. 
- Looks like after freedomtan@'s PR, the build will work on his/her platform
- From Anton's comments, we need to find the right compile-time flags to ignore offsetof for TX1 and other listed platforms he mentioned, and then find a followup fix for Python 3.5.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by vielmetti** [comment]
@alanchiao - are there any resource blockers for this work? I have server-class machines at @packethost from @worksonarm that can be had (by anyone involved here) for additional testing and CI.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
It has been 29 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
It has been 44 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
We are closing this issue for now due to lack of activity. Please comment if this is still an issue for you. Thanks!
