### ISSUE TITLE
Inconsistent behavior for decode_bmp() with channels specification

### ISSUE THREAD

**Issue by wrongtest** [tensorflow/tensorflow#21331]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 3.10.0-693.2.2.el7.x86_64
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.8.0
- **Python version**: Python 2.7.14 :: Anaconda
- **Bazel version (if compiling from source)**: None
- **GCC/Compiler version (if compiling from source)**: None
- **CUDA/cuDNN version**: None
- **GPU model and memory**: None
- **Exact command to reproduce**: See below

### Describe the problem
We rely on tensorflow.image.decode_xxx() apis to load images. We expect a fixed channel size for decoded images and below code works:

```python
import tensorflow as tf
data = tf.placeholder(dtype=tf.string, shape=())
image = tf.image.decode_jpeg(data, channels=3)
```

However, it does not work for tensorflow.image.decode_bmp() for every images. For example, a bmp image with channel model "L":
[my_image.bmp.zip](https://github.com/tensorflow/tensorflow/files/2252717/my_image.bmp.zip)

```python
import tensorflow as tf
data = tf.placeholder(dtype=tf.string, shape=())

image_no_spec = tf.image.decode_bmp(data)
image = tf.image.decode_bmp(data, channels=3)

my_image = open("my_image.bmp", "rb").read()
with tf.Session() as sess:
    res = sess.run(image_no_spec, {data: my_image})
    print "Decode shape: ", res.shape   # (666, 1000, 1)

    res = sess.run(image, {data: my_image})
    print "Decode shape: ", res.shape  # err
```

Since tensorflow.image.decode_image() is a wrapper for decode_xxx() api(s), it may benefits if we can specify channels for all formats safely.

### Source code / logs

Decode shape:  (666, 1000, 1)
Traceback (most recent call last):
  File "a.py", line 12, in <module>
    res = sess.run(image, {data: my_image})
  File "/home/work/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 905, in run
    run_metadata_ptr)
  File "/home/work/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1137, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/work/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1355, in _do_run
    options, run_metadata)
  File "/home/work/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1374, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: channels attribute 3 does not match bits per pixel from file 1
	 [[Node: DecodeBmp_1 = DecodeBmp[channels=3, _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_Placeholder_0_0)]]

Caused by op u'DecodeBmp_1', defined at:
  File "a.py", line 5, in <module>
    image = tf.image.decode_bmp(data, channels=3)
  File "/home/work/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/gen_image_ops.py", line 513, in decode_bmp
    "DecodeBmp", contents=contents, channels=channels, name=name)
  File "/home/work/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/work/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3271, in create_op
    op_def=op_def)
  File "/home/work/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1650, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): channels attribute 3 does not match bits per pixel from file 1
	 [[Node: DecodeBmp_1 = DecodeBmp[channels=3, _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_Placeholder_0_0)]]

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Mobile device

**Comment by tensorflowbutler** [comment]
It has been 15 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by vrv** [comment]
I think this is working as intended.  You are feeding in a bmp image that has only 1 channel and telling the operation that it should expect 3 channels. 

https://www.tensorflow.org/api_docs/python/tf/image/decode_image the documentation says that channels=None or 0 means 'automatically figure it out'.  Otherwise channels is used as a specification to enforce.

Decode with channels=0 and then use something like grayscale_to_rgb if you need to guarantee that all images are 3 channels as output.

**Comment by wrongtest** [comment]
@vrv  Thanks for your nice notes :)

I understand that you mean the semantic of specified channels is "the operation expect (for eg) 3 channels input", rather than "the operation will produce 3 channels output".

I think it is ok but my problem is I do not find any TensorFlow api to convert decoded images with different channels to (for eg) RGB format. I have to depend on external lib like opencv or pillow to deal with all kind of images, or I have to guarantee that all input images are of the same format.

**Comment by vrv** [comment]
Try: https://www.tensorflow.org/api_docs/python/tf/image/grayscale_to_rgb

If your BMP is 1 channel, then you need an API like that to convert it.  

Something I've done in the past is to conditionally convert the image to 3 channels by using that API if the output is 1 channel, as a post-processing step.

    image = tf.cond(tf.equal(tf.shape(image)[2], 1), lambda: tf.image.grayscale_to_rgb(image), lambda: image)

**Comment by tobegit3hub** [comment]
Thanks @vrv . it may work if we "reshape" the tensor after `decode_bmp`. But the interface/usage/meaning of `decode_jpeg` and `decode_jpeg` are a little different which may lead to confusion for the developers.
