### ISSUE TITLE
Boosted Trees Regressor - incompatible tensor shapes

### ISSUE THREAD

**Issue by jessiejc23** [tensorflow/tensorflow#21347]
Hi, I used the boosted trees regressor estimator and it gave results on the first run. Cleared my checkpoints  to rerun the model but the program then gave the following value error. Think that this may be a bug because the value error was not raised during my first run, and I am not sure how to fix this error.

````
Traceback (most recent call last):
  File "main.py", line 191, in <module>
tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/.../.../.local/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
_sys.exit(main(argv))
  File "main.py", line 170, in main
experiment.train_and_evaluate()
  File "/.../.../.local/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 671, in train_and_evaluate
self.train(delay_secs=0)
  File "/.../.../.local/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 389, in train
saving_listeners=self._saving_listeners)
  File "/.../.../.local/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 881, in _call_train
saving_listeners=saving_listeners)
  File "/.../.../.local/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 366, in train
loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/.../.../.local/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1119, in _train_model
return self._train_model_default(input_fn, hooks, saving_listeners)
 File "/.../.../.local/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1132, in _train_model_default
features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
  File "/.../.../.local/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1107, in _call_model_fn
model_fn_results = self._model_fn(features=features, **kwargs)
  File "/.../.../.local/lib/python3.6/site-packages/tensorflow/python/estimator/canned/boosted_trees.py", line 929, in _model_fn
n_batches_per_layer, config)
  File "/.../.../.local/lib/python3.6/site-packages/tensorflow/python/estimator/canned/boosted_trees.py", line 650, in _bt_model_fn
logits=logits)
File "/.../.../.local/lib/python3.6/site-packages/tensorflow/python/estimator/canned/head.py", line 239, in create_estimator_spec
regularization_losses))
  File "/.../.../.local/lib/python3.6/site-packages/tensorflow/python/estimator/canned/head.py", line 1506, in _create_tpu_estimator_spec
train_op = train_op_fn(regularized_training_loss)
  File "/.../.../.local/lib/python3.6/site-packages/tensorflow/python/estimator/canned/boosted_trees.py", line 611, in _train_op_fn
array_ops.stack(stats_summaries, axis=0), stamp_token)
  File "/.../.../.local/lib/python3.6/site-packages/tensorflow/python/ops/data_flow_ops.py", line 1286, in apply_grad
grad.get_shape().assert_is_compatible_with(self._shape)
  File "/.../.../.local/lib/python3.6/site-packages/tensorflow/python/framework/tensor_shape.py", line 847, in assert_is_compatible_with
raise ValueError("Shapes %s and %s are incompatible" % (self, other))
ValueError: Shapes (0,) and (0, 63, 2, 2) are incompatible
````

For reference, these are my feature columns.

```
a = tf.feature_column.categorical_column_with_hash_bucket("a", hash_bucket_size=1000)
b = tf.feature_column.numeric_column("b")
b_bucket = tf.feature_column.bucketized_column(b,  boundaries=np.arange(0,2644,100).tolist())
c= tf.feature_column.numeric_column("c")
c_bucket = tf.feature_column.bucketized_column(c,  boundaries=np.arange(0,210,10).tolist())
d = tf.feature_column.numeric_column("d")
d_bucket = tf.feature_column.bucketized_column(d,  boundaries=np.arange(0,245,10).tolist())
e = tf.feature_column.categorical_column_with_vocabulary_list(key="e", vocabulary_list =["l", "m", "h"])
columns = [a, b_bucket, c_bucket, d_bucket, e]
feature_columns = [tf.feature_column.indicator_column(x) for x in columns]
```

**Comment by jony0917** [comment]
Did you remove all the files in your model directory or just the checkpoint files ?

**Comment by jessiejc23** [comment]
I removed the checkpoint files and any potential cache files.

**Comment by asimshankar** [comment]
@nataliaponomareva - Can you take a look?

**Comment by nataliaponomareva** [comment]
Can you show your config for the boosted trees estimator? Did you pass in the feature columns? This first 0 in (0, 63, 2, 2) indicates that you have 0 feature columns

**Comment by jessiejc23** [comment]
Hi Natalia, thanks for your reply. This is my code snippet.

```
feature_columns = build_model_columns()
#the build_model_columns() function returns the feature_columns from the previous code snippet.
run_config = tf.estimator.RunConfig(tf_random_seed=42, save_checkpoints_steps=5000)
 
if model_type == 'boosted_trees':
        nn = tf.estimator.BoostedTreesRegressor(
            model_dir=FLAGS.model_dir,
            feature_columns = feature_columns,
            n_batches_per_layer = 1000,
            learning_rate = 0.1,
            n_trees = 100,
            max_depth = 6,
            config=run_config)

train_spec=tf.estimator.TrainSpec(input_fn=lambda: input_fn(FLAGS.train_data, FLAGS.train_epochs, True, FLAGS.batch_size))
eval_spec=tf.estimator.EvalSpec(input_fn=lambda: input_fn(FLAGS.test_data, 1, True, FLAGS.batch_size),steps=1000)
tf.estimator.train_and_evaluate(nn, train_spec, eval_spec)
```

I think I passed the feature columns correctly..?

**Comment by nataliaponomareva** [comment]
Btw when you say you cleared the checkpoints - it means you cleared the whole model dir right? Not just checkpoint files? Can you try on a completely new folder
Can you print out the length of feature columns list after u do the build_model_columns()

**Comment by jessiejc23** [comment]
Yep I cleared the whole model directory. and tried it on a completely new folder. Same error still exists.
Length of feature columns list printed is 5.

**Comment by nataliaponomareva** [comment]
Ah, sorry this is weird
feature_columns = [tf.feature_column.indicator_column(x) for x in columns]
You seem to be creating an indicator over bucketized columns as well. This is not needed. Also, to narrow down
1) Can you first try just with bucketized feature columns b_bucket, d_bucket (no indicator over them)
2) Then add the categorical with an indicator

**Comment by nataliaponomareva** [comment]
have not heard back, closing
