### ISSUE TITLE
tf.linspace doesn't except integers for start/stop and floats for num

### ISSUE THREAD

**Issue by RanFeldesh** [tensorflow/tensorflow#21391]
tf.linspace(start=1.0, stop=3.0, num=3) - works fine.
tf.linspace(start=1, stop=3, num=3) yields an error (because start and stop are integers)
tf.linspace(start=1.0, stop=3.0, num=3.0) yields an error (because num is float)
In both cases the error is: "Could not find valid device for node name: "LinSpace" "

I would expect the following behavior:
* start and stop can be integers (the op can convert it to float if fractions are produced; but see below)
* num can be float, if its modulo with 1 is zero (the op can convert it to int; but see below)
* the error message should reflect the problem precisely
* the comments and reference page should reflect the expected dtype more clearly (at the top, not just in args)

This behavior is how numpy linspace function works (including stating all optional dtype in the autocomplete while typing).

dtype conversion within a TF op might not follow TF design rules as it might create dtype changes without the user awareness. Yet, I would still be happy to have an error message that explicitly states the problem with the dtypes.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows10
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: NA
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.9
- **Python version**: 3.6
- **Bazel version (if compiling from source)**: NA
- **GCC/Compiler version (if compiling from source)**: NA
- **CUDA/cuDNN version**: NA
- **GPU model and memory**: NA
- **Exact command to reproduce**: See above

**Comment by yongtang** [comment]
@RanFeldesh On Linux the error is quite descriptive:
```
# python3
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> tf.linspace(start=1, stop=3, num=3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_math_ops.py", line 3908, in lin_space
    "LinSpace", start=start, stop=stop, num=num, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 609, in _apply_op_helper
    param_name=input_name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 60, in _SatisfiesTypeConstraint
    ", ".join(dtypes.as_dtype(x).name for x in allowed_list)))
TypeError: Value passed to parameter 'start' has DataType int32 not in list of allowed values: bfloat16, float32, float64
>>> tf.linspace(start=1.0, stop=3.0, num=3.0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_math_ops.py", line 3908, in lin_space
    "LinSpace", start=start, stop=stop, num=num, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 609, in _apply_op_helper
    param_name=input_name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 60, in _SatisfiesTypeConstraint
    ", ".join(dtypes.as_dtype(x).name for x in allowed_list)))
TypeError: Value passed to parameter 'num' has DataType float32 not in list of allowed values: int32, int64
>>> tf.__version__
'1.9.0'
>>> 

```

**Comment by yongtang** [comment]
Not so sure about the automatic conversion of dtype, but would be happy to add support if this could be confirmed by tf API team.

**Comment by RanFeldesh** [comment]
Dear @yongtang , thank you so much for the quick reply and verification on your machine.
The first post's error message was with eager mode. With the graph mode, I get a similar error message  to your Linux example. It didn't occur to me that the vague error message might be due to eager mode. I usually debug in eager, then execute in graph. It might be possible to add the explicit error message in eager mode as well. I wonder how simple it is adding it, and if it falls within the TF API design rules.

Running on same config as in the first post:
* Here is the full code for eager mode:
import tensorflow as tf
tf.enable_eager_execution()
tf.linspace(1,2,1)

* And the associated error message (eager mode; it doesn't state the error type explicitly):
Traceback (most recent call last):
  File "C:/Users/Ran/Documents/TensorFlow Models/NeuronalMemory/linspace.py", line 3, in <module>
    tf.linspace(1,2,1)
  File "C:\Users\Ran\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 4205, in lin_space
    start, stop, num, name=name, ctx=_ctx)
  File "C:\Users\Ran\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 4225, in lin_space_eager_fallback
    attrs=_attrs, ctx=_ctx, name=name)
  File "C:\Users\Ran\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\eager\execute.py", line 66, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InternalError: Could not find valid device for node name: "LinSpace"
op: "LinSpace"
input: "dummy_input"
input: "dummy_input"
input: "dummy_input"
attr {
  key: "T"
  value {
    type: DT_INT32
  }
}
attr {
  key: "Tidx"
  value {
    type: DT_INT32
  }
}
 [Op:LinSpace]

Process finished with exit code 1

* The same in a graph-mode code:
import tensorflow as tf
tf.linspace(1,2,1)

* the error message in graph mode (which states error explicitly - which is great!):
File "C:/Users/Ran/Documents/TensorFlow Models/NeuronalMemory/linspace.py", line 2, in <module>
    tf.linspace(1,2,1)
  File "C:\Users\Ran\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 4188, in lin_space
    "LinSpace", start=start, stop=stop, num=num, name=name)
  File "C:\Users\Ran\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 609, in _apply_op_helper
    param_name=input_name)
  File "C:\Users\Ran\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 60, in _SatisfiesTypeConstraint
    ", ".join(dtypes.as_dtype(x).name for x in allowed_list)))
TypeError: Value passed to parameter 'start' has DataType int32 not in list of allowed values: bfloat16, float32, float64

**Comment by karmel** [comment]
Thanks, @RanFeldesh and @yongtang . @asimshankar -- can you comment on whether this would be a desired feature, and, while you're here, whether the error message can be improved for eager?

**Comment by asimshankar** [comment]
Will look into it. 
Some possibly useful background information can be found in https://stackoverflow.com/questions/51698096/from-design-perspective-why-arent-the-error-messages-in-eager-and-in-graph-mod/51735894#51735894

**Comment by tensorflowbutler** [comment]
Nagging Assignees @asimshankar, @karmel: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignees @asimshankar, @karmel: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignees @asimshankar, @karmel: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignees @asimshankar, @karmel: It has been 59 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignees @asimshankar, @karmel: It has been 74 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignees @asimshankar, @karmel: It has been 89 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignees @asimshankar, @karmel: It has been 104 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignees @asimshankar, @karmel: It has been 119 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.
