### ISSUE TITLE
The installation procedure for Ubuntu does not work.

### ISSUE THREAD

**Issue by rogermorgan** [tensorflow/tensorflow#21408]
I tried to follow the procedure for installing on Ubuntu 16.04 or later.
I am using Ubuntu 16.04 with the latest updates on 64-bit AMD/Intel.
I am using Python 3, version 3.5.2. I checked the version of pip3, it is 8.1.1
The step of the procedure which fails is:
virtualenv --system-site-packages -p python3 venv

and the error messages are as follows:
Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /home/nick/tensorflow/venv/bin/python3
Also creating executable in /home/nick/tensorflow/venv/bin/python
Installing setuptools, pkg_resources, pip, wheel...
  Complete output from command /home/nick/tensorflow/venv/bin/python3 - setuptools pkg_resources pip wheel:
  Collecting setuptools
Exception:
Traceback (most recent call last):
  File "/home/nick/tensorflow/venv/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 560, in urlopen
    body=body, headers=headers)
  File "/home/nick/tensorflow/venv/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/home/nick/tensorflow/venv/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 787, in _validate_conn
    conn.connect()
  File "/home/nick/tensorflow/venv/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/connection.py", line 252, in connect
    ssl_version=resolved_ssl_version)
  File "/home/nick/tensorflow/venv/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/util/ssl_.py", line 305, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.5/ssl.py", line 377, in wrap_socket
    _context=self)
  File "/usr/lib/python3.5/ssl.py", line 752, in __init__
    self.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 988, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 633, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

**Comment by av8ramit** [comment]
Hi @rogermorgan unfortunately this seems to be a virtualenv with python3 issue you're hitting. Unfortunately it's not easily reproducible since it most like is an issue with the machine you're running on. I recommend maybe asking on StackOverFlow if any other users have this this. Maybe you're hitting [this](https://stackoverflow.com/questions/15954467/python-ssl-example-from-docs-gives-connection-reset-by-peer-error)?
