### ISSUE TITLE
contrib.rnn.ConvLSTMCell: zero_state has wrong size if cell has skip connections

### ISSUE THREAD

**Issue by su-si** [tensorflow/tensorflow#21400]
There seems to be a but in how ConvLSTMCell handles its states:

When calculating the output size, ConvLSTMCell has one more channel dimension (in general, as many more channels as there are input channels) than what was given as output_channels. 
This is only if skip_connection was True at initialization, **and makes sense** (the input is concatenated to the output --> n_channels_out = n_channels_in + original_n_channels_out).

Also, when creating a cell and applying it to inputs and a state:
```
cell = tf.contrib.rnn.ConvLSTMCell(conv_ndims=2, input_shape=[80,80,1], output_channels=2,
                                               kernel_shape=[5,5], skip_connection=True)
state= cell.zero_state(10, dtype=tf.float32)
output, next_state = cell(last_outputs, states)
```

--> next_state is an LSTMStateTuple with shapes (?, 80, 80, 2) and (?, 80, 80, **3**). Still makes sense since it stores its hidden state as well as outputs and re-uses them in the next timestep, and the outputs gained an additional channel.

But the zero_state() calculation seems wrong; the code reads (in contrib/rnn/python/ops/rnn_cell.py):

```
    self._total_output_channels = output_channels
    if self._skip_connection:
      self._total_output_channels += self._input_shape[-1]

    state_size = tensor_shape.TensorShape(
        self._input_shape[:-1] + [self._output_channels])
    self._state_size = **rnn_cell_impl.LSTMStateTuple(state_size, state_size)**
    self._output_size = tensor_shape.TensorShape(
        self._input_shape[:-1] + [self._total_output_channels])
```

Shouldn't it be not` rnn_cell_impl.LSTMStateTuple(state_size, state_size)`, but `rnn_cell_impl.LSTMStateTuple(state_size, self._output_size)` ?

Funnily, it does not disturb the cell to be called with a state of size (80, 80, **2**)   - but for me it raised an error when called again with its next state which has size (80, 80, 3). For completeness, this error was (and this error is _not my problem_, my problem was inconsistency of shapes of the cell states): 

> Traceback (most recent call last):
  File "/home/me/programs/pycharm-community-2016.1.1/helpers/pydev/_pydevd_bundle/pydevd_comm.py", line 1079, in do_it
    result = pydevd_vars.evaluate_expression(self.thread_id, self.frame_id, self.expression, self.doExec)
  File "/home/me/programs/pycharm-community-2016.1.1/helpers/pydev/_pydevd_bundle/pydevd_vars.py", line 352, in evaluate_expression
    Exec(expression, updated_globals, frame.f_locals)
  File "/home/me/programs/pycharm-community-2016.1.1/helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<string>", line 1, in <module>
  File "/home/me/miniconda3/envs/tf36/lib/python3.6/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 232, in __call__
    return super(RNNCell, self).__call__(inputs, state)
  File "/home/me/miniconda3/envs/tf36/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 717, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/home/me/miniconda3/envs/tf36/lib/python3.6/site-packages/tensorflow/contrib/rnn/python/ops/rnn_cell.py", line 2113, in call
    4 * self._output_channels, self._use_bias)
  File "/home/me/miniconda3/envs/tf36/lib/python3.6/site-packages/tensorflow/contrib/rnn/python/ops/rnn_cell.py", line 2207, in _conv
    "kernel", filter_size + [total_arg_size_depth, num_features], dtype=dtype)
  File "/home/me/miniconda3/envs/tf36/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 1317, in get_variable
    constraint=constraint)
  File "/home/me/miniconda3/envs/tf36/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 1079, in get_variable
    constraint=constraint)
  File "/home/me/miniconda3/envs/tf36/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 417, in get_variable
    return custom_getter(**custom_getter_kwargs)
  File "/home/me/miniconda3/envs/tf36/lib/python3.6/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 235, in _rnn_get_variable
    variable = getter(*args, **kwargs)
  File "/home/me/miniconda3/envs/tf36/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 394, in _true_getter
    use_resource=use_resource, constraint=constraint)
  File "/home/me/miniconda3/envs/tf36/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 738, in _get_single_variable
    found_var.get_shape()))
ValueError: Trying to share variable conv_lstm_cell/kernel, but specified shape (5, 5, 4, 8) and found shape (5, 5, 3, 8).

------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
Yes.
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 14.04
- **TensorFlow installed from (source or binary)**: 
binary
- **TensorFlow version (use command below)**:
1.8.0
- **Python version**:
3.6
- **Bazel version (if compiling from source)**: 
-
- **GCC/Compiler version (if compiling from source)**:
-
- **CUDA/cuDNN version**:
- (using CPU version)
- **GPU model and memory**:
- (using CPU version)
- **Exact command to reproduce**:
See description above

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Mobile device

**Comment by su-si** [comment]
Sure...

**Comment by drpngx** [comment]
Thank you for the detailed report. That seems reasonable! Feel free to contribute a PR.

**Comment by songzenghui** [comment]
Hi, @su-si .
I want to know if the `tf.nn.dynamic` did not suport the `ConvLSTMCell` ?

**Comment by su-si** [comment]
Hi @songzenghui ,
In my case I couldn't use a dynamic_rnn, so I don't know. (I had a problem with changing state sizes using ConvLSTMCell in a tf.while loop.) So just give it a try :) dynamic_rnn is probably the most frequent use case, so it will probably work. 
The code to dynamic_rnn looks a bit complicated, I don't see right away whether they circumvent the changing state size within a while loop. It might be they do the first step outside of the loop, then both old and 'fixed' versions should work fine with dynamic_rnn.
Could still be that my suggested fix destroys compatibility with dynamic_rnn.
