### ISSUE TITLE
Discrepancy between Python and C++ loading of corrupt SavedModels

### ISSUE THREAD

**Issue by priyankjain** [tensorflow/tensorflow#21417]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: YES
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS High Seirra 10.13.6
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: NOT MOBILE
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: ('v1.9.0-0-g25c197e023', '1.9.0')
- **Python version**:Python 2.7.10
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**: 
 	- Train and export the MNIST model with `python mnist.py`. This will export a model in tmp directory in the same folder as mnist.py script.

 	-  Remove the variables.index file from ./tmp/mnist_model/15*/variables/ folder. This is an important step required to reproduce the partial model load issue.
	- Load the model in python with load.py (might want to change path on line 6) by executing
	`python load.py`. This should throw an error. Expected behavior.
	- Load the model in java with Load.java (might want to change path on line 6) by executing
	`javac -cp libtensorflow-1.9.0.jar Load.java` and
	`java -cp libtensorflow-1.9.0.jar:. -Djava.library.path=./jni Load`. This does not throw an error. Only when you send some input data to this model does it throw an error. Unexpected behavior.

### Describe the problem
This bug is to illustrate the partial model load discrepancy in the Python and Java API.

- The exported model directory consists of a saved_model.pb file corresponding to the 
graph of the exported model. The directory also consists of a variables directory. This variables
directory consists of a variables.index file which list the variables used by the model and a variables.data file. Note that it is possible to have a model with no variables directory for a model with zero variables.

- Situation: In cases where model does not have the variables.index file, Python API throws an exception whereas Java API doesn't throw an exception.

If you load the partial model in Python with

`tf.saved_model.loader.load`
the missing variables.index file issue is caught and it throws an error. This is because, in python when it loads the model, it restores the variables too: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/saved_model/loader_impl.py#L349. It sees that some of the variables needed in the graph, are not specified via the variables.index file, hence results in UndefinedError.

If you load the partial model in Java with

`SavedModelBundle.load`
the missing variables.index file issue is not caught and therefore it does not throw an error. This is because in Java, when it loads the model: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/cc/saved_model/loader.cc#L171, it sees that the variables.index file is missing, hence makes the assumption that the graph does not have any variables.

### Source code / logs
mnist.py
```python
import tensorflow as tf
import numpy as np

from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets('MNIST_data')

def input(dataset):
    return dataset.images, dataset.labels.astype(np.int32)

# Specify feature
feature_columns = [tf.feature_column.numeric_column("x", shape=[28, 28])]

# Build 2 layer DNN classifier
classifier = tf.estimator.DNNClassifier(
    feature_columns=feature_columns,
    hidden_units=[256, 32],
    optimizer=tf.train.AdamOptimizer(1e-4),
    n_classes=10,
    dropout=0.1,
    model_dir="./tmp/mnist_model"
)

# Define the training inputs
train_input_fn = tf.estimator.inputs.numpy_input_fn(
    x={"x": input(mnist.train)[0]},
    y=input(mnist.train)[1],
    num_epochs=None,
    batch_size=50,
    shuffle=True
)

classifier.train(input_fn=train_input_fn, steps=100)

# Define the test inputs
test_input_fn = tf.estimator.inputs.numpy_input_fn(
    x={"x": input(mnist.test)[0]},
    y=input(mnist.test)[1],
    num_epochs=1,
    shuffle=False
)

# Evaluate accuracy
accuracy_score = classifier.evaluate(input_fn=test_input_fn)["accuracy"]
print("\nTest Accuracy: {0:f}%\n".format(accuracy_score*100))
image = tf.placeholder(tf.float32,[None])
classifier.export_savedmodel("./tmp/mnist_model", 
	tf.estimator.export.build_raw_serving_input_receiver_fn({"x":image}))
```

load.py (might want to change path in line 6)
```python
import tensorflow as tf 

sess = tf.Session()
tf.saved_model.loader.load(sess, 
	[tf.saved_model.tag_constants.SERVING],
	'./tmp/mnist_model/1533576273')
```

Load.java (might want to change path in line 6)
```java
import org.tensorflow.SavedModelBundle;

public class Load {
  public static void main(String[] args) throws Exception {
  	SavedModelBundle savedModelBundle = SavedModelBundle.load(
  		"./tmp/mnist_model/1533576273/", "serve");
  }
}
```

Here's the output when loading the model in python:
```sh
$ python load.py
/Users/priyankj/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2018-08-06 15:27:37.363952: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-08-06 15:27:37.411644: W tensorflow/core/framework/op_kernel.cc:1318] OP_REQUIRES failed at save_restore_tensor.cc:170 : Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./tmp/mnist_model/1533576273/variables/variables
Traceback (most recent call last):
  File "load.py", line 6, in <module>
    './tmp/mnist_model/1533576273')
  File "/Users/priyankj/lib/python2.7/site-packages/tensorflow/python/saved_model/loader_impl.py", line 229, in load
    saver.restore(sess, variables_path)
  File "/Users/priyankj/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1768, in restore
    six.reraise(exception_type, exception_value, exception_traceback)
  File "/Users/priyankj/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1752, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/Users/priyankj/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/Users/priyankj/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/Users/priyankj/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/Users/priyankj/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./tmp/mnist_model/1533576273/variables/variables
	 [[Node: save_1/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT64], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save_1/Const_0_0, save_1/RestoreV2/tensor_names, save_1/RestoreV2/shape_and_slices)]]

Caused by op u'save_1/RestoreV2', defined at:
  File "load.py", line 6, in <module>
    './tmp/mnist_model/1533576273')
  File "/Users/priyankj/lib/python2.7/site-packages/tensorflow/python/saved_model/loader_impl.py", line 219, in load
    saver = tf_saver.import_meta_graph(meta_graph_def_to_load, **saver_kwargs)
  File "/Users/priyankj/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1960, in import_meta_graph
    **kwargs)
  File "/Users/priyankj/lib/python2.7/site-packages/tensorflow/python/framework/meta_graph.py", line 744, in import_scoped_meta_graph
    producer_op_list=producer_op_list)
  File "/Users/priyankj/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 432, in new_func
    return func(*args, **kwargs)
  File "/Users/priyankj/lib/python2.7/site-packages/tensorflow/python/framework/importer.py", line 442, in import_graph_def
    _ProcessNewOps(graph)
  File "/Users/priyankj/lib/python2.7/site-packages/tensorflow/python/framework/importer.py", line 234, in _ProcessNewOps
    for new_op in graph._add_new_tf_operations(compute_devices=False):  # pylint: disable=protected-access
  File "/Users/priyankj/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3563, in _add_new_tf_operations
    for c_op in c_api_util.new_tf_operations(self)
  File "/Users/priyankj/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3450, in _create_op_from_tf_operation
    ret = Operation(c_op, self)
  File "/Users/priyankj/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1740, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

NotFoundError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./tmp/mnist_model/1533576273/variables/variables
	 [[Node: save_1/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT64], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save_1/Const_0_0, save_1/RestoreV2/tensor_names, save_1/RestoreV2/shape_and_slices)]]
```

Here's the output of loading the model in Java:
```sh
$ javac -cp libtensorflow-1.9.0.jar Load.java
$ java -cp libtensorflow-1.9.0.jar:. -Djava.library.path=./jni Load
2018-08-06 14:56:48.242783: I tensorflow/cc/saved_model/loader.cc:242] Loading SavedModel with tags: { serve }; from: ./tmp/mnist_model/1533576273/
2018-08-06 14:56:48.244329: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.2 AVX AVX2 FMA
2018-08-06 14:56:48.246854: I tensorflow/cc/saved_model/loader.cc:161] Restoring SavedModel bundle.
2018-08-06 14:56:48.246888: I tensorflow/cc/saved_model/loader.cc:171] The specified SavedModel has no variables; no checkpoints were restored.
2018-08-06 14:56:48.246894: I tensorflow/cc/saved_model/loader.cc:196] Running LegacyInitOp on SavedModel bundle.
2018-08-06 14:56:48.250752: I tensorflow/cc/saved_model/loader.cc:291] SavedModel load for tags { serve }; Status: success. Took 8012 microseconds.
```

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatianashp: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatianashp: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatianashp: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by asimshankar** [comment]
Thanks for the detailed report and the debugging @priyankjain.

@karmel : If I may summarize, there is a discrepancy between the Python and [C++](https://github.com/tensorflow/tensorflow/blob/4aa639c0cbb47f4707f735e0cc80f4c39506d928/tensorflow/cc/saved_model/loader.cc#L171) implementations of loading a saved model where the former raises an exception on a missing `variables.index` file and the latter doesn't. Though, admittedly this can only happen if someone explicitly removed the `variables.index` file from the saved model directory.

**Comment by karmel** [comment]
@christisg -- we can add the corresponding validation of variables.index in C++, but is that okay from the serving side? Are there reasons to avoid checking?

**Comment by priyankjain** [comment]
@karmel There are models where the index.variables file is not there, yet the model/graph is valid and ready for inference. Models with no variables should fall under this category. An example would be an additive model:
```python

import tensorflow as tf
x = tf.placeholder(dtype=tf.float32, name="x")
y = tf.placeholder(dtype=tf.float32, name="y")
with tf.Session() as sess:  
tf.saved_model.simple_save(sess, "./exported_model",
                             inputs={"x": x, 
                             "y": y},
                             outputs={"z": tf.add(x,y, name="z")})
```

**Comment by christisg** [comment]
It's not acceptable to crash serving because of a missing variables.index file for one of the models.
Would it make sense to make the Python implementation consistent with C++? i.e. can we reconsider throwing exception in this case?
@chrisolston for additional perspective.

**Comment by chrisolston** [comment]
+1 on not crashing the server if the variables.index file is absent. SGTM to throw an exception instead. Thanks @karmel !

**Comment by chrisolston** [comment]
I just want to make sure the C++ "check" throws a tensorflow::Status error, rather than crashing the program. That's all. (I think the confusion may stem from the fact that inside Google the term "check" is often used to mean crash, for reason having to do with some APIs we have internally.)

**Comment by priyankjain** [comment]
Got you, thanks Chris!

**Comment by priyankjain** [comment]
Checking in to see if there was any progress on this? Thanks!

**Comment by priyankjain** [comment]
Bump, wondering whether you got a chance to look into this.

**Comment by karmel** [comment]
Sorry, we have not had the time to look into this yet. Would you be interested in contributing a PR?

**Comment by priyankjain** [comment]
Yes, I can contribute a PR. It should be around two weeks before I start working on it, feel free to assign this issue to me.

**Comment by karmel** [comment]
Great, thanks!

**Comment by tensorflowbutler** [comment]
Nagging Assignees @karmel, @priyankjain: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignees @karmel, @priyankjain: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by Happyzippy** [comment]
Bump,
What is the current status on this regarding TF2? I see that model loading of TF 1.xx serialized models in TF2 allows this.
