### ISSUE TITLE
tensorflow ScipyOptimizerInterface feeding error 

### ISSUE THREAD

**Issue by ywanglocus** [tensorflow/tensorflow#21415]
-----------------------
My code are as follow:
```
p_f = tf.get_variable('p_f', shape=(1, 1)) #corresponding index 0 in 

W1_1 = tf.constant(paras[0], dtype=tf.float32, name='W1_1' )
W1_2_1 = tf.constant(paras[1][0, :], dtype=tf.float32, shape=[1, 79], name='W1_2_1')
W1_2_2 = tf.constant(paras[1][1:, :], dtype=tf.float32, name='W1_2_2')
b1 = tf.constant(paras[2], dtype=tf.float32, name='b1' )
W2_1_1 = tf.constant(paras[3][0, :], dtype=tf.float32, shape=[1, 1], name='W1_2_1')
W2_1_2 = tf.constant(paras[3][1:, :], dtype=tf.float32, name='W1_2_2')
W2_2 = tf.constant(paras[4], dtype=tf.float32, name='W2_2' )
b2 = tf.constant(paras[5], dtype=tf.float32, name='b2' )

p_sub =  tf.placeholder(shape=(None, 18), dtype=tf.float32 , name="p_sub")
p_t =  tf.placeholder(shape=(None, 60), dtype=tf.float32, name= 'p_t') #the other part except for the price

D = tf.matmul(tf.nn.sigmoid(tf.matmul(p_f, W1_2_1)+ tf.matmul(p_t, W1_2_2) + tf.matmul(p_sub, W1_1)+b1), W2_2)+tf.matmul(p_f, W2_1_1)+ tf.matmul(p_t, W2_1_2)+b2
    
p_loss = tf.reduce_mean(-p_f*D) #self defined loss

###parameters
learning_rate = 0.5
optimizer = tf.contrib.opt.ScipyOptimizerInterface(p_loss, method='L-BFGS-B', options={'maxiter': 1000})

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    for step in range(419):
        #parameters 
        x1_train = tv_train.iloc[step*batch_size:step*batch_size+batch_size, 66:84].values 
        x1_test = tv_test.iloc[:, 66:84].values
        x2_train = np.concatenate((tv_train.iloc[step*batch_size:step*batch_size+batch_size, 4:11].values, tv_train.iloc[step*batch_size:step*batch_size+batch_size, 14:67].values), 1) 
        #x2_train = tf.concat(axis=1, values=[tv_train.iloc[step*batch_size:step*batch_size+batch_size, 4:11].values, tv_train.iloc[step*batch_size:step*batch_size+batch_size, 14:67].values])
        x2_test = np.concatenate((tv_test.iloc[:, 4:11].values, tv_test.iloc[:, 14:67].values), 1) 
        
        sess.run(init, feed_dict={p_sub: x1_train, 
                                  p_t: x2_train})
        optimizer.minimize(sess) 
        ret=sess.run(p_f)
        
        if step % 200 == 0:
            print()
            print(ret)
            print()
```
```
----------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py in _do_call(self, fn, *args)
   1349     try:
-> 1350       return fn(*args)
   1351     except errors.OpError as e:

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py in _run_fn(session, feed_dict, fetch_list, target_list, options, run_metadata)
   1328                                    feed_dict, fetch_list, target_list,
-> 1329                                    status, run_metadata)
   1330 

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.py in __exit__(self, type_arg, value_arg, traceback_arg)
    472             compat.as_text(c_api.TF_Message(self.status.status)),
--> 473             c_api.TF_GetCode(self.status.status))
    474     # Delete the underlying status object from memory otherwise it stays alive

InvalidArgumentError: You must feed a value for placeholder tensor 'p_sub' with dtype float and shape [?,18]
	 [[Node: p_sub = Placeholder[dtype=DT_FLOAT, shape=[?,18], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

During handling of the above exception, another exception occurred:

InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-67-986c52132edf> in <module>()
     39         sess.run(init, feed_dict={p_sub: x1_train, 
     40                                   p_t: x2_train})
---> 41         optimizer.minimize(sess)
     42         ret=sess.run(p_f)
     43 

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\opt\python\training\external_optimizer.py in minimize(self, session, feed_dict, fetches, step_callback, loss_callback, **run_kwargs)
    205         packed_bounds=self._packed_bounds,
    206         step_callback=step_callback,
--> 207         optimizer_kwargs=self.optimizer_kwargs)
    208     var_vals = [
    209         packed_var_val[packing_slice] for packing_slice in self._packing_slices

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\opt\python\training\external_optimizer.py in _minimize(self, initial_val, loss_grad_func, equality_funcs, equality_grad_funcs, inequality_funcs, inequality_grad_funcs, packed_bounds, step_callback, optimizer_kwargs)
    404 
    405     import scipy.optimize  # pylint: disable=g-import-not-at-top
--> 406     result = scipy.optimize.minimize(*minimize_args, **minimize_kwargs)
    407 
    408     message_lines = [

C:\ProgramData\Anaconda3\lib\site-packages\scipy\optimize\_minimize.py in minimize(fun, x0, args, method, jac, hess, hessp, bounds, constraints, tol, callback, options)
    448     elif meth == 'l-bfgs-b':
    449         return _minimize_lbfgsb(fun, x0, args, jac, bounds,
--> 450                                 callback=callback, **options)
    451     elif meth == 'tnc':
    452         return _minimize_tnc(fun, x0, args, jac, bounds, callback=callback,

C:\ProgramData\Anaconda3\lib\site-packages\scipy\optimize\lbfgsb.py in _minimize_lbfgsb(fun, x0, args, jac, bounds, disp, maxcor, ftol, gtol, eps, maxfun, maxiter, iprint, callback, maxls, **unknown_options)
    326             # until the completion of the current minimization iteration.
    327             # Overwrite f and g:
--> 328             f, g = func_and_grad(x)
    329         elif task_str.startswith(b'NEW_X'):
    330             # new iteration

C:\ProgramData\Anaconda3\lib\site-packages\scipy\optimize\lbfgsb.py in func_and_grad(x)
    276     else:
    277         def func_and_grad(x):
--> 278             f = fun(x, *args)
    279             g = jac(x, *args)
    280             return f, g

C:\ProgramData\Anaconda3\lib\site-packages\scipy\optimize\optimize.py in function_wrapper(*wrapper_args)
    290     def function_wrapper(*wrapper_args):
    291         ncalls[0] += 1
--> 292         return function(*(wrapper_args + args))
    293 
    294     return ncalls, function_wrapper

C:\ProgramData\Anaconda3\lib\site-packages\scipy\optimize\optimize.py in __call__(self, x, *args)
     61     def __call__(self, x, *args):
     62         self.x = numpy.asarray(x).copy()
---> 63         fg = self.fun(x, *args)
     64         self.jac = fg[1]
     65         return fg[0]

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\opt\python\training\external_optimizer.py in loss_grad_func_wrapper(x)
    365     def loss_grad_func_wrapper(x):
    366       # SciPy's L-BFGS-B Fortran implementation requires gradients as doubles.
--> 367       loss, gradient = loss_grad_func(x)
    368       return loss, gradient.astype('float64')
    369 

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\opt\python\training\external_optimizer.py in eval_func(x)
    276 
    277       augmented_fetch_vals = session.run(
--> 278           augmented_fetches, feed_dict=augmented_feed_dict)
    279 
    280       if callable(callback):

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py in run(self, fetches, feed_dict, options, run_metadata)
    893     try:
    894       result = self._run(None, fetches, feed_dict, options_ptr,
--> 895                          run_metadata_ptr)
    896       if run_metadata:
    897         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1126     if final_fetches or final_targets or (handle and feed_dict_tensor):
   1127       results = self._do_run(handle, final_targets, final_fetches,
-> 1128                              feed_dict_tensor, options, run_metadata)
   1129     else:
   1130       results = []

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1342     if handle is None:
   1343       return self._do_call(_run_fn, self._session, feeds, fetches, targets,
-> 1344                            options, run_metadata)
   1345     else:
   1346       return self._do_call(_prun_fn, self._session, handle, feeds, fetches)

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py in _do_call(self, fn, *args)
   1361         except KeyError:
   1362           pass
-> 1363       raise type(e)(node_def, op, message)
   1364 
   1365   def _extend_graph(self):

InvalidArgumentError: You must feed a value for placeholder tensor 'p_sub' with dtype float and shape [?,18]
	 [[Node: p_sub = Placeholder[dtype=DT_FLOAT, shape=[?,18], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'p_sub', defined at:
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 477, in start
    ioloop.IOLoop.instance().start()
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\eventloop\ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 235, in dispatch_shell
    handler(stream, idents, msg)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\zmqshell.py", line 533, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2717, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2821, in run_ast_nodes
    if self.run_code(code, result):
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-67-986c52132edf>", line 18, in <module>
    p_sub =  tf.placeholder(shape=(None, 18), dtype=tf.float32 , name="p_sub")
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\array_ops.py", line 1680, in placeholder
    return gen_array_ops._placeholder(dtype=dtype, shape=shape, name=name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 4105, in _placeholder
    "Placeholder", dtype=dtype, shape=shape, name=name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3160, in create_op
    op_def=op_def)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1625, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'p_sub' with dtype float and shape [?,18]
	 [[Node: p_sub = Placeholder[dtype=DT_FLOAT, shape=[?,18], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
```

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by asimshankar** [comment]
The error message:
```
You must feed a value for placeholder tensor 'p_sub' with dtype float and shape [?,18]
```
suggests that the value being fed to `p_sub`, i.e., the value of `x1_train` in the line:
```python
        sess.run(init, feed_dict={p_sub: x1_train, p_t: x2_train})
```
has either the wrong type (i.e., is not a `float32`) or has an incompatible shape (i.e., is not a 2-dimensional tensor, or the size of the second dimension is not 18).

You'd want to verify that:
```python
        x1_train = tv_train.iloc[step*batch_size:step*batch_size+batch_size, 66:84].values 
```
has the right shape and type.

Hope that helps.
