### ISSUE TITLE
tensorflow.python.framework.errors_impl.InternalError: Could not allocate ndarray

### ISSUE THREAD

**Issue by csitaula** [tensorflow/tensorflow#21442]
HI,
I am using running Places pre-trained VGG16 network in python  using CPU. I got this error? How to solve this memory issue after several computations? Thanks
C:/Experiment/PicAlertData/public/4326658334.jpg
Traceback (most recent call last):
  File "C:\Python3.5\lib\site-packages\tensorflow\python\client\session.py", line 1322, in _do_call
    return fn(*args)
  File "C:\Python3.5\lib\site-packages\tensorflow\python\client\session.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "C:\Python3.5\lib\site-packages\tensorflow\python\client\session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InternalError: Could not allocate ndarray

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Chiru\places_trained_vgg16.py", line 274, in <module>
    model = VGG16_Places365(weights='places')
  File "C:\Users\Chiru\places_trained_vgg16.py", line 221, in VGG16_Places365
    model.load_weights(weights_path)
  File "C:\Python3.5\lib\site-packages\keras\engine\network.py", line 1161, in load_weights
    f, self.layers, reshape=reshape)
  File "C:\Python3.5\lib\site-packages\keras\engine\saving.py", line 928, in load_weights_from_hdf5_group
    K.batch_set_value(weight_value_tuples)
  File "C:\Python3.5\lib\site-packages\keras\backend\tensorflow_backend.py", line 2440, in batch_set_value
    get_session().run(assign_ops, feed_dict=feed_dict)
  File "C:\Python3.5\lib\site-packages\tensorflow\python\client\session.py", line 900, in run
    run_metadata_ptr)
  File "C:\Python3.5\lib\site-packages\tensorflow\python\client\session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Python3.5\lib\site-packages\tensorflow\python\client\session.py", line 1316, in _do_run
    run_metadata)
  File "C:\Python3.5\lib\site-packages\tensorflow\python\client\session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Could not allocate ndarray

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by csitaula** [comment]
Thanks, I fixed the problem! I used model inside loop in my coding! I changed it and kept outside of loop for multiple images and now, it worked.

**Comment by gragundier** [comment]
Then can you close the issue?

**Comment by YingjieL** [comment]
Thanks a lot,I have same error,after used model outsied loop,problem solved.
