### ISSUE TITLE
NCCL is not supported on Windows 

### ISSUE THREAD

**Issue by Windaway** [tensorflow/tensorflow#21470]
------------------------
### System information
Windows 10 x64 pro 17314.365, i7 7900X R6E, TTxp (*4), 16G DDR4 3000@2666 (*6) 
Channel .
Tensorflow 1.9.0 with AVX2 simd, CUDA9.2.148, Cudnn7.1.4, py3.6.6 , VS2017 15.7(with cmake), CP/SM6.1

### Describe the problem
Op type not registered 'NcclAllReduce' in binary running on Windows10.
With onedevicestrategy no problems. I noticed that NCCL only works in Linux.

### Source code / logs
tensorflow/contrib/distribute/python/examples/simple_tfkeras_example.py

> `
> from __future__ import absolute_import
> from __future__ import division
> from __future__ import print_function
> 
> import sys
> 
> import numpy as np
> import tensorflow as tf
> 
> 
> def input_fn():
>   x = np.random.random((1024, 10))
>   y = np.random.randint(2, size=(1024, 1))
>   x = tf.cast(x, tf.float32)
>   dataset = tf.data.Dataset.from_tensor_slices((x, y))
>   dataset = dataset.repeat(10)
>   dataset = dataset.batch(32)
>   return dataset
> 
> 
> def main(args):
> 
>   model_dir = './'
>   print('Using %s to store checkpoints.' % model_dir)
> 
>   # Define tf.keras Model.
>   model = tf.keras.Sequential()
>   model.add(tf.keras.layers.Dense(16, activation='relu', input_shape=(10,)))
>   model.add(tf.keras.layers.Dense(1, activation='sigmoid'))
> 
>   # Compile tf.keras Model.
>   optimizer = tf.train.GradientDescentOptimizer(0.2)
>   model.compile(loss='binary_crossentropy', optimizer=optimizer)
>   model.summary()
>   tf.keras.backend.set_learning_phase(True)
> 
>   # Define a DistributionStrategy and convert the tf.keras Model to a
>   # tf.Estimator that utilizes the DistributionStrategy.
>   strategy = tf.contrib.distribute.MirroredStrategy()
>   config = tf.estimator.RunConfig(
>       train_distribute=strategy)
>   keras_estimator = tf.keras.estimator.model_to_estimator(
>       keras_model=model, config=config, model_dir=model_dir)
> 
>   # Train and evaluate the tf.Estimator.
>   keras_estimator.train(input_fn=input_fn, steps=10)
>   eval_result = keras_estimator.evaluate(input_fn=input_fn)
>   print('Eval result: {}'.format(eval_result))
> 
> if __name__ == '__main__':
>   tf.app.run(argv=sys.argv)`

Logs:

> D:\Anaconda3\envs\tensorflow\python.exe Z:/PyProj/leaf/othertest.py
> Using ./ to store checkpoints.
> _________________________________________________________________
> Layer (type)                 Output Shape              Param #   
> =================================================================
> dense (Dense)                (None, 16)                176       
> _________________________________________________________________
> dense_1 (Dense)              (None, 1)                 17        
> =================================================================
> Total params: 193
> Trainable params: 193
> Non-trainable params: 0
> _________________________________________________________________
> 2018-08-08 16:28:32.965695: I c:\users\user\source\repos\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1392] Found device 0 with properties: 
> name: TITAN Xp COLLECTORS EDITION major: 6 minor: 1 memoryClockRate(GHz): 1.582
> pciBusID: 0000:17:00.0
> totalMemory: 12.00GiB freeMemory: 9.93GiB
> 2018-08-08 16:28:33.068708: I c:\users\user\source\repos\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1392] Found device 1 with properties: 
> name: TITAN Xp COLLECTORS EDITION major: 6 minor: 1 memoryClockRate(GHz): 1.582
> pciBusID: 0000:18:00.0
> totalMemory: 12.00GiB freeMemory: 9.93GiB
> 2018-08-08 16:28:33.170068: I c:\users\user\source\repos\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1392] Found device 2 with properties: 
> name: TITAN Xp COLLECTORS EDITION major: 6 minor: 1 memoryClockRate(GHz): 1.582
> pciBusID: 0000:65:00.0
> totalMemory: 12.00GiB freeMemory: 9.93GiB
> 2018-08-08 16:28:33.280326: I c:\users\user\source\repos\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1392] Found device 3 with properties: 
> name: TITAN Xp COLLECTORS EDITION major: 6 minor: 1 memoryClockRate(GHz): 1.582
> pciBusID: 0000:b3:00.0
> totalMemory: 12.00GiB freeMemory: 9.93GiB
> 2018-08-08 16:28:33.281257: I c:\users\user\source\repos\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1471] Adding visible gpu devices: 0, 1, 2, 3
> 2018-08-08 16:28:35.779554: I c:\users\user\source\repos\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:952] Device interconnect StreamExecutor with strength 1 edge matrix:
> 2018-08-08 16:28:35.779811: I c:\users\user\source\repos\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:958]      0 1 2 3 
> 2018-08-08 16:28:35.779990: I c:\users\user\source\repos\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:971] 0:   N N N N 
> 2018-08-08 16:28:35.780385: I c:\users\user\source\repos\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:971] 1:   N N N N 
> 2018-08-08 16:28:35.780639: I c:\users\user\source\repos\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:971] 2:   N N N N 
> 2018-08-08 16:28:35.783787: I c:\users\user\source\repos\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:971] 3:   N N N N 
> 2018-08-08 16:28:35.784232: I c:\users\user\source\repos\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 9612 MB memory) -> physical GPU (device: 0, name: TITAN Xp COLLECTORS EDITION, pci bus id: 0000:17:00.0, compute capability: 6.1)
> 2018-08-08 16:28:36.220466: I c:\users\user\source\repos\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 9612 MB memory) -> physical GPU (device: 1, name: TITAN Xp COLLECTORS EDITION, pci bus id: 0000:18:00.0, compute capability: 6.1)
> 2018-08-08 16:28:36.655982: I c:\users\user\source\repos\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:2 with 9612 MB memory) -> physical GPU (device: 2, name: TITAN Xp COLLECTORS EDITION, pci bus id: 0000:65:00.0, compute capability: 6.1)
> 2018-08-08 16:28:37.091894: I c:\users\user\source\repos\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:3 with 9612 MB memory) -> physical GPU (device: 3, name: TITAN Xp COLLECTORS EDITION, pci bus id: 0000:b3:00.0, compute capability: 6.1)
> 2018-08-08 16:28:37.529496: I c:\users\user\source\repos\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1471] Adding visible gpu devices: 0, 1, 2, 3
> 2018-08-08 16:28:37.530168: I c:\users\user\source\repos\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:952] Device interconnect StreamExecutor with strength 1 edge matrix:
> 2018-08-08 16:28:37.530377: I c:\users\user\source\repos\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:958]      0 1 2 3 
> 2018-08-08 16:28:37.530527: I c:\users\user\source\repos\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:971] 0:   N N N N 
> 2018-08-08 16:28:37.530675: I c:\users\user\source\repos\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:971] 1:   N N N N 
> 2018-08-08 16:28:37.530822: I c:\users\user\source\repos\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:971] 2:   N N N N 
> 2018-08-08 16:28:37.530971: I c:\users\user\source\repos\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:971] 3:   N N N N 
> 2018-08-08 16:28:37.531268: I c:\users\user\source\repos\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 9612 MB memory) -> physical GPU (device: 0, name: TITAN Xp COLLECTORS EDITION, pci bus id: 0000:17:00.0, compute capability: 6.1)
> 2018-08-08 16:28:37.531988: I c:\users\user\source\repos\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 9612 MB memory) -> physical GPU (device: 1, name: TITAN Xp COLLECTORS EDITION, pci bus id: 0000:18:00.0, compute capability: 6.1)
> 2018-08-08 16:28:37.532651: I c:\users\user\source\repos\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:2 with 9612 MB memory) -> physical GPU (device: 2, name: TITAN Xp COLLECTORS EDITION, pci bus id: 0000:65:00.0, compute capability: 6.1)
> 2018-08-08 16:28:37.533329: I c:\users\user\source\repos\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:3 with 9612 MB memory) -> physical GPU (device: 3, name: TITAN Xp COLLECTORS EDITION, pci bus id: 0000:b3:00.0, compute capability: 6.1)
> 2018-08-08 16:28:37.570852: I c:\users\user\source\repos\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1471] Adding visible gpu devices: 0, 1, 2, 3
> 2018-08-08 16:28:37.571420: I c:\users\user\source\repos\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:952] Device interconnect StreamExecutor with strength 1 edge matrix:
> 2018-08-08 16:28:37.571620: I c:\users\user\source\repos\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:958]      0 1 2 3 
> 2018-08-08 16:28:37.571766: I c:\users\user\source\repos\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:971] 0:   N N N N 
> 2018-08-08 16:28:37.571910: I c:\users\user\source\repos\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:971] 1:   N N N N 
> 2018-08-08 16:28:37.572056: I c:\users\user\source\repos\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:971] 2:   N N N N 
> 2018-08-08 16:28:37.572200: I c:\users\user\source\repos\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:971] 3:   N N N N 
> 2018-08-08 16:28:37.572479: I c:\users\user\source\repos\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 9612 MB memory) -> physical GPU (device: 0, name: TITAN Xp COLLECTORS EDITION, pci bus id: 0000:17:00.0, compute capability: 6.1)
> 2018-08-08 16:28:37.573133: I c:\users\user\source\repos\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 9612 MB memory) -> physical GPU (device: 1, name: TITAN Xp COLLECTORS EDITION, pci bus id: 0000:18:00.0, compute capability: 6.1)
> 2018-08-08 16:28:37.573824: I c:\users\user\source\repos\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:2 with 9612 MB memory) -> physical GPU (device: 2, name: TITAN Xp COLLECTORS EDITION, pci bus id: 0000:65:00.0, compute capability: 6.1)
> 2018-08-08 16:28:37.574554: I c:\users\user\source\repos\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:3 with 9612 MB memory) -> physical GPU (device: 3, name: TITAN Xp COLLECTORS EDITION, pci bus id: 0000:b3:00.0, compute capability: 6.1)
> 2018-08-08 16:28:37.902576: I c:\users\user\source\repos\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1471] Adding visible gpu devices: 0, 1, 2, 3
> 2018-08-08 16:28:37.903108: I c:\users\user\source\repos\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:952] Device interconnect StreamExecutor with strength 1 edge matrix:
> 2018-08-08 16:28:37.903311: I c:\users\user\source\repos\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:958]      0 1 2 3 
> 2018-08-08 16:28:37.903456: I c:\users\user\source\repos\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:971] 0:   N N N N 
> 2018-08-08 16:28:37.903604: I c:\users\user\source\repos\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:971] 1:   N N N N 
> 2018-08-08 16:28:37.903751: I c:\users\user\source\repos\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:971] 2:   N N N N 
> 2018-08-08 16:28:37.903896: I c:\users\user\source\repos\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:971] 3:   N N N N 
> 2018-08-08 16:28:37.904189: I c:\users\user\source\repos\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1084] Created TensorFlow device (/device:GPU:0 with 9612 MB memory) -> physical GPU (device: 0, name: TITAN Xp COLLECTORS EDITION, pci bus id: 0000:17:00.0, compute capability: 6.1)
> 2018-08-08 16:28:37.904886: I c:\users\user\source\repos\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1084] Created TensorFlow device (/device:GPU:1 with 9612 MB memory) -> physical GPU (device: 1, name: TITAN Xp COLLECTORS EDITION, pci bus id: 0000:18:00.0, compute capability: 6.1)
> 2018-08-08 16:28:37.905868: I c:\users\user\source\repos\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1084] Created TensorFlow device (/device:GPU:2 with 9612 MB memory) -> physical GPU (device: 2, name: TITAN Xp COLLECTORS EDITION, pci bus id: 0000:65:00.0, compute capability: 6.1)
> 2018-08-08 16:28:37.906462: I c:\users\user\source\repos\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1084] Created TensorFlow device (/device:GPU:3 with 9612 MB memory) -> physical GPU (device: 3, name: TITAN Xp COLLECTORS EDITION, pci bus id: 0000:b3:00.0, compute capability: 6.1)
> Traceback (most recent call last):
>   File "D:\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py", line 1589, in _create_c_op
>     c_op = c_api.TF_FinishOperation(op_desc)
> tensorflow.python.framework.errors_impl.InvalidArgumentError: Op type not registered 'NcclAllReduce' in binary running on DESKTOP-K1BEKCL. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed. while building NodeDef 'NcclAllReduce'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "Z:/PyProj/leaf/othertest.py", line 66, in <module>
>     tf.app.run(argv=sys.argv)
>   File "D:\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
>     _sys.exit(main(argv))
>   File "Z:/PyProj/leaf/othertest.py", line 61, in main
>     keras_estimator.train(input_fn=input_fn, steps=10)
>   File "D:\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\estimator\estimator.py", line 366, in train
>     loss = self._train_model(input_fn, hooks, saving_listeners)
>   File "D:\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\estimator\estimator.py", line 1117, in _train_model
>     return self._train_model_distributed(input_fn, hooks, saving_listeners)
>   File "D:\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\estimator\estimator.py", line 1160, in _train_model_distributed
>     self.config)
>   File "D:\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\training\distribute.py", line 794, in call_for_each_tower
>     return self._call_for_each_tower(fn, *args, **kwargs)
>   File "D:\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\contrib\distribute\python\mirrored_strategy.py", line 269, in _call_for_each_tower
>     coord.join(threads)
>   File "D:\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\training\coordinator.py", line 389, in join
>     six.reraise(*self._exc_info_to_raise)
>   File "D:\Anaconda3\envs\tensorflow\lib\site-packages\six.py", line 693, in reraise
>     raise value
>   File "D:\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\training\coordinator.py", line 297, in stop_on_exception
>     yield
>   File "D:\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\contrib\distribute\python\mirrored_strategy.py", line 263, in _call_for_each_tower
>     self, *merge_args, **merge_kwargs)
>   File "D:\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\training\optimizer.py", line 652, in _distributed_apply
>     reduced_grads = distribution.batch_reduce("sum", grads_and_vars)
>   File "D:\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\training\distribute.py", line 840, in batch_reduce
>     return self._batch_reduce(method_string, value_destination_pairs)
>   File "D:\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\contrib\distribute\python\mirrored_strategy.py", line 310, in _batch_reduce
>     value_destination_pairs)
>   File "D:\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\contrib\distribute\python\cross_tower_ops.py", line 177, in batch_reduce
>     return self._batch_reduce(method_string, value_destination_pairs)
>   File "D:\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\contrib\distribute\python\cross_tower_ops.py", line 475, in _batch_reduce
>     [v[0] for v in value_destination_pairs])
>   File "D:\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\contrib\distribute\python\cross_tower_ops.py", line 520, in _batch_all_reduce
>     device_grad_packs)
>   File "D:\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\contrib\distribute\python\cross_tower_utils.py", line 37, in aggregate_gradients_using_nccl
>     agg_grads = nccl.all_sum(single_grads)
>   File "D:\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\contrib\nccl\python\ops\nccl_ops.py", line 47, in all_sum
>     return _apply_all_reduce('sum', tensors)
>   File "D:\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\contrib\nccl\python\ops\nccl_ops.py", line 228, in _apply_all_reduce
>     shared_name=shared_name))
>   File "D:\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\contrib\nccl\ops\gen_nccl_ops.py", line 58, in nccl_all_reduce
>     num_devices=num_devices, shared_name=shared_name, name=name)
>   File "D:\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
>     op_def=op_def)
>   File "D:\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py", line 3414, in create_op
>     op_def=op_def)
>   File "D:\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py", line 1756, in __init__
>     control_input_ops)
>   File "D:\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py", line 1592, in _create_c_op
>     raise ValueError(str(e))
> ValueError: Op type not registered 'NcclAllReduce' in binary running on DESKTO Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed. while building NodeDef 'NcclAllReduce'

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by Windaway** [comment]
Have I written custom code
Yes
OS Platform and Distribution
Windows 10 x64 pro 17314.365, i7 7900X R6E
Channel .
TensorFlow installed from Self Compiled,TensorFlow version
Tensorflow 1.9.0 with AVX2 simd, 
Bazel version
With Cmake
CUDA/cuDNN version
CUDA9.2.148, Cudnn7.1.4, py3.6.6 , VS2017 15.7(with cmake), CP/SM6.1
GPU model and memory
TTxp (*4), 16G DDR4 3000@2666 (*6)

**Comment by tensorflowbutler** [comment]
Nagging Assignee @yuefengz: It has been 20 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by guptapriya** [comment]
@tfboyd - do you know what needs to be done for getting nccl to run with windows?

**Comment by tfboyd** [comment]
I am not aware of a nccl binary for Windows from NVIDIA.  That does not
mean it does not exist.  You can use hierarchical copy and get the same or
very similar performance.

**Comment by guptapriya** [comment]
@Windaway nccl is only useful if there are GPU to GPU connections available in your setup. Is that the case? If yes, you could try finding a nccl binary for Windows.

If not, then it would be better to try some of the non nccl options. To get those, try the following:

Option 1:
Try using hierarchical copy. 
```
cross_tower_ops = tf.contrib.distribute.AllReduceCrossTowerOps(
    'hierarchical_copy', num_packs=num_gpus))
strategy = tf.contrib.distribute.MirroredStrategy(cross_tower_ops=cross_tower_ops)
```

Option 2: 
Reduce to first GPU:
```
cross_tower_ops = tf.contrib.distribute. ReductionToOneDeviceCrossTowerOps()
strategy = tf.contrib.distribute.MirroredStrategy(cross_tower_ops=cross_tower_ops)
```

Option 3: 
Reduce to CPU:
```
cross_tower_ops = tf.contrib.distribute. ReductionToOneDeviceCrossTowerOps(
    reduce_to_device="/device:CPU:0")
strategy = tf.contrib.distribute.MirroredStrategy(cross_tower_ops=cross_tower_ops)
```

You will have to try out the 2 approaches and see which one works and gives the best performance for your use case. 

@yuefengz - for use cases like this, perhaps we should detect if nccl is not available, give a warning, and default to something else that will work for sure?

**Comment by tensorflowbutler** [comment]
Nagging Assignee @yuefengz: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @yuefengz: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignees @yuefengz, @seemuch: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignees @yuefengz, @seemuch: It has been 31 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignees @yuefengz, @seemuch: It has been 45 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by KrisKusano** [comment]
Does this work? https://github.com/tbennun/nccl-windows

**Comment by prabindh** [comment]
This seems more recent ? https://github.com/MyCaffe/NCCL

**Comment by SivilTaram** [comment]
> @Windaway nccl is only useful if there are GPU to GPU connections available in your setup. Is that the case? If yes, you could try finding a nccl binary for Windows.
> 
> If not, then it would be better to try some of the non nccl options. To get those, try the following:
> 
> Option 1:
> Try using hierarchical copy.
> 
> ```
> cross_tower_ops = tf.contrib.distribute.AllReduceCrossTowerOps(
>     'hierarchical_copy', num_packs=num_gpus))
> strategy = tf.contrib.distribute.MirroredStrategy(cross_tower_ops=cross_tower_ops)
> ```
> 
> Option 2:
> Reduce to first GPU:
> 
> ```
> cross_tower_ops = tf.contrib.distribute. ReductionToOneDeviceCrossTowerOps()
> strategy = tf.contrib.distribute.MirroredStrategy(cross_tower_ops=cross_tower_ops)
> ```
> 
> Option 3:
> Reduce to CPU:
> 
> ```
> cross_tower_ops = tf.contrib.distribute. ReductionToOneDeviceCrossTowerOps(
>     reduce_to_device="/device:CPU:0")
> strategy = tf.contrib.distribute.MirroredStrategy(cross_tower_ops=cross_tower_ops)
> ```
> 
> You will have to try out the 2 approaches and see which one works and gives the best performance for your use case.
> 
> @yuefengz - for use cases like this, perhaps we should detect if nccl is not available, give a warning, and default to something else that will work for sure?

The API for the first solution has changed from `AllReduceCrossTowerOps` to `AllReduceCrossDeviceOps`. Hope it help you guys :)

**Comment by mohapatras** [comment]
Any update on this thread. For now, I have to use 'hierarchical copy' as reduce algorithm in place of 'nccl' in tf 1.14 CUDA 10. Can't find official binaries for nccl windows 10.


```
cross_tower_ops = tf.contrib.distribute.AllReduceCrossDeviceOps(
    'hierarchical_copy', num_packs=num_gpus))
strategy = tf.contrib.distribute.MirroredStrategy(cross_tower_ops=cross_tower_ops)
```

**Comment by SadeghMSalehi** [comment]
> @Windaway nccl is only useful if there are GPU to GPU connections available in your setup. Is that the case? If yes, you could try finding a nccl binary for Windows.
> 
> If not, then it would be better to try some of the non nccl options. To get those, try the following:
> 
> Option 1:
> Try using hierarchical copy.
> 
> ```
> cross_tower_ops = tf.contrib.distribute.AllReduceCrossTowerOps(
>     'hierarchical_copy', num_packs=num_gpus))
> strategy = tf.contrib.distribute.MirroredStrategy(cross_tower_ops=cross_tower_ops)
> ```
> 
> Option 2:
> Reduce to first GPU:
> 
> ```
> cross_tower_ops = tf.contrib.distribute. ReductionToOneDeviceCrossTowerOps()
> strategy = tf.contrib.distribute.MirroredStrategy(cross_tower_ops=cross_tower_ops)
> ```
> 
> Option 3:
> Reduce to CPU:
> 
> ```
> cross_tower_ops = tf.contrib.distribute. ReductionToOneDeviceCrossTowerOps(
>     reduce_to_device="/device:CPU:0")
> strategy = tf.contrib.distribute.MirroredStrategy(cross_tower_ops=cross_tower_ops)
> ```
> 
> You will have to try out the 2 approaches and see which one works and gives the best performance for your use case.
> 
> @yuefengz - for use cases like this, perhaps we should detect if nccl is not available, give a warning, and default to something else that will work for sure?

In TensorFlow 2, option 1 should be used as follow:
`cross_tower_ops = tf.distribute.HierarchicalCopyAllReduce(num_packs=num_gpus)
strategy = tf.distribute.MirroredStrategy(cross_device_ops=cross_tower_ops)`

**Comment by sachinprasadhs** [comment]
You can follow the installations from https://github.com/MyCaffe/NCCL/blob/master/INSTALL.md and test it on your Windows machine with  [NcclAllReduce](https://www.tensorflow.org/api_docs/python/tf/distribute/NcclAllReduce) which is basically a inherited class from [CrossDeviceOps](https://www.tensorflow.org/api_docs/python/tf/distribute/CrossDeviceOps).

Feel free to reopen the issue, if the issue still persists.Thank You.
