### ISSUE TITLE
Implement "quantize_graph" will print "tf.estimator package not installed."

### ISSUE THREAD

**Issue by gary90231** [tensorflow/tensorflow#21478]
Making quantization by using command "sudo bazel-bin/tensorflow/tools/quantization/quantize_graph ......." in the directory of tensorflow, and it will input "tf.estimator package not installed." And in this directory, implemt "python->import tensorflow", it will return error message. But in other directory, implemt "python->import tensorflow", it will be normally. The folllowing is my envirnment information: 
 OS Platform and Distribution: Linux Ubuntu 18.04
 TensorFlow installed from: using TF source code (CPU) for graph conversion, not using binary-python(GPU) for inference
TensorFlow version:  using r1.10.0-rc1
Python version: 3.6
Bazel version: 0.16.0

**Comment by gary90231** [comment]
Have I written custom code: N/A
CUDA/cuDNN version: Not supported when confugurate
GPU model and memory : Not supported GPU
Exact command to reproduce : N/A
Mobile device: In PC not in mobile device
Thank you.

**Comment by gary90231** [comment]
To complement,
in the directory of tensorflow/: 
xxxx@edward-ubuntu-18:~/tensorflow$ python
Python 3.6.5 (default, Apr  1 2018, 05:46:30)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
Traceback (most recent call last):
  File "/home/xx/tensorflow/tensorflow/python/platform/self_check.py", line 25, in <module>
    from tensorflow.python.platform import build_info
ImportError: cannot import name 'build_info'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xx/tensorflow/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/xx/tensorflow/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/xx/tensorflow/tensorflow/python/pywrap_tensorflow.py", line 25, in <module>
    from tensorflow.python.platform import self_check
  File "/home/xx/tensorflow/tensorflow/python/platform/self_check.py", line 27, in <module>
    raise ImportError("Could not import tensorflow. Do not import tensorflow "
ImportError: Could not import tensorflow. Do not import tensorflow from its source directory; change directory to outside the TensorFlow source tree, and relaunch your Python interpreter from there.

But when implemet the same operation not in the directory of /tensorflow, it can successfully import tensorflow

**Comment by Kayoku** [comment]
Hi, I have the same problem with the "optimize_for_inference" script : "tf.estimator package not installed"... I'm using TF 1.9

**Comment by gary90231** [comment]
i found that it may because the version of tensorflow is not fit to the version of bazel.

**Comment by Kayoku** [comment]
What do you mean by "not fit" ? What is the version that we need to use so ?

**Comment by WenguoLi** [comment]
I have the same problem with the "optimize_for_inference"  and " quantize_graph" scripts in TF 1.8 / 1.9

**Comment by alexcdot** [comment]
I have the same problem with the "optimize_for_inference" script in TF 1.10

**Comment by stcdalyc** [comment]
same problem with "quantize_graph" scripts in latest TF

**Comment by Shershebnev** [comment]
I had the same issue with optimize_for_inference, commenting out the following lines
`from tensorflow.python.estimator import api as estimator_api  # pylint: disable=g-import-not-at-top  
__path__ += [os.path.dirname(estimator_api.__file__)]  
del estimator_api` from the top of this file (inside `try..except` block)
`bazel-bin/tensorflow/python/tools/optimize_for_inference.runfiles/org_tensorflow/tensorflow/__init__.py` seems to solve it though getting some official comments would be great

**Comment by tensorflowbutler** [comment]
Nagging Assignee @bignamehyp: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by VadimShevchuk** [comment]
I have the same problem

**Comment by martinwicke** [comment]
@case540 There probably is some additional untangling to be done?

**Comment by case540** [comment]
I'll take a look

**Comment by tensorflowbutler** [comment]
Nagging Assignee @case540: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by lauriebyrum** [comment]
> I have the same problem when compile
> bazel build -c opt --copt="-DSELECTIVE_REGISTRATION" 
> --copt="-DSUPPORT_SELECTIVE_REGISTRATION" 
> //tensorflow/contrib/android:libtensorflow_inference.so 
> --host_crosstool_top=@bazel_tools//tools/cpp:toolchain 
> --crosstool_top=//external:android/crosstool --cpu=arm64-v8a

I also see this with 1.11 when building selective registration for iOS: 
bazel-bin/tensorflow/python/tools/print_selective_registration_header \
  --graphs="${MODEL_PATHS}" > tensorflow/core/framework/ops_to_register.h

**Comment by tensorflowbutler** [comment]
Nagging Assignee @case540: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @case540: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @case540: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by sushreebarsa** [comment]
Hi There,

We are moving this issue to closed status, as you are using an older version of tensorflow(1.x) which is officially considered as end of life. We recommend that you upgrade to 2.4 or later version and let us know if the issue still persists in newer versions.
Please open a new issue for any help you need against 2.x, and we will get you the right help.Thanks!
