### ISSUE TITLE
Tensorflow PIP Package fails to build - AttributeError: module 'pandas' has no attribute 'core'

### ISSUE THREAD

**Issue by matt-garman** [tensorflow/tensorflow#21488]
This may be a bug in the Python PIP build script(s), or something askew in my environment.  I am trying to build Tensorflow from source, to include AVX/AVX2 support.  It always fails with the error log pasted below.  I have tried the latest git pull over the last week or so (i.e. multiple git pulls, followed by "bazel clean ; bazel build <options>".  I have also tried the same with the r1.10 branch.

There is [this somewhat similar question on StackOverflow](https://stackoverflow.com/questions/36521691/importing-pandas-gives-error-attributeerror-module-pandas-has-no-attribute-c).  That is more about using Pandas, rather than building Tensorflow.  At any rate I tried all the suggestions to no avail.  And my Pandas is working:

```
$ python -c "import pandas as pd ; import pandas.core.ops as ops ; print(pd.__version__)" && echo $?
0.23.4
0
```

System Details:
-----------------

  - Have I written custom code: NO
  - OS Platform and Distribution: CentOS Linux 7.4.1708 with Anaconda Python3 distribution
  - Mobile device: N/A
  - TensorFlow installed from: not yet installed, trying to build from source (no build-halting errors during the C/C++ portion of the build)
  - TensorFlow version: latest git pull over the last several days, both master and r1.10 branch
  - Python version: Python 3.6.6 :: Anaconda custom (64-bit)
  - Bazel version (if compiling from source):
```
$ bazel version
Build label: 0.16.0- (@non-git)
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Jul 31 18:27:17 2018 (1533061637)
Build timestamp: 1533061637
Build timestamp as int: 1533061637
```
  - GCC/Compiler version: gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-16)
  - CUDA/cuDNN version: N/A
  - GPU model and memory: N/A
  - Exact command to reproduce:
```
  $ git clone https://github.com/tensorflow/tensorflow.git
  $ cd tensorflow
  $ ./configure # accept all defaults
  $ bazel build -c opt --copt=-mavx --copt=-mavx2 --copt=-mfma --copt=-msse4.1 --copt=-msse4.2 --verbose_failures -k //tensorflow/tools/pip_package:build_pip_package
```

Output of tf_env_collect.sh:
------------------------------

== cat /etc/issue ===============================================
Linux septictank 3.10.0-693.21.1.el7.x86_64 #1 SMP Wed Mar 7 19:03:37 UTC 2018 x
86_64 x86_64 x86_64 GNU/Linux
VERSION="7 (Core)"
VERSION_ID="7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

== are we in docker =============================================
No

== compiler =====================================================
c++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-16)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

== uname -a =====================================================
Linux septictank 3.10.0-693.21.1.el7.x86_64 #1 SMP Wed Mar 7 19:03:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

== check pips ===================================================
numpy                              1.15.0
numpydoc                           0.8.0
protobuf                           3.5.2

== check for virtualenv =========================================
False

== tensorflow import ============================================
Traceback (most recent call last):
  File "/home/matt/tensorflow/tensorflow/python/platform/self_check.py", line 2$, in <module>
    from tensorflow.python.platform import build_info
ImportError: cannot import name 'build_info'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/matt/tensorflow/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-i$port
  File "/home/matt/tensorflow/tensorflow/python/__init__.py", line 49, in <modul
e>
    from tensorflow.python import pywrap_tensorflow
  File "/home/matt/tensorflow/tensorflow/python/pywrap_tensorflow.py", line 25,
in <module>
    from tensorflow.python.platform import self_check
  File "/home/matt/tensorflow/tensorflow/python/platform/self_check.py", line 27
, in <module>
    raise ImportError("Could not import tensorflow. Do not import tensorflow "
ImportError: Could not import tensorflow. Do not import tensorflow from its sour
ce directory; change directory to outside the TensorFlow source tree, and relaun
ch your Python interpreter from there.

== env ==========================================================
LD_LIBRARY_PATH is unset
DYLD_LIBRARY_PATH is unset

== nvidia-smi ===================================================
./tf_env_collect.sh: line 105: nvidia-smi: command not found

== cuda libs  ===================================================

Error message from bazel:
-----------------------------
```
ERROR: /home/matt/tensorflow/tensorflow/python/estimator/api/BUILD:12:1: Couldn't build file tensorflow/python/estimator/api/__init__.py: Executing genrule //tensorflow/python/estimator/api:estimator_python_api_gen failed (Exit 1): bash failed: error executing command
  (cd /home/matt/.cache/bazel/_bazel_matt/b51f46dcf2ef174fa43a943ad13629f0/execroot/org_tensorflow && \
  exec env - \
    PATH=/opt/anaconda3/bin:/opt/anaconda3/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/usr/local/bin:/sbin:/usr/sbin:/usr/local/bin:/sbin:/usr/sbin \
    PYTHON_BIN_PATH=/opt/anaconda3/bin/python \
    PYTHON_LIB_PATH=/opt/anaconda3/lib/python3.6/site-packages \
    TF_DOWNLOAD_CLANG=0 \
    TF_NEED_CUDA=0 \
    TF_NEED_OPENCL_SYCL=0 \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; bazel-out/host/bin/tensorflow/python/estimator/api/create_tensorflow.python.estimator_api  --apidir=bazel-out/k8-opt/genfiles/tensorflow/python/estimator/api --apiname=estimator --apiversion=2 --package=tensorflow.python.estimator --output_package=tensorflow.python.estimator.api bazel-out/k8-opt/genfiles/tensorflow/python/estimator/api/__init__.py bazel-out/k8-opt/genfiles/tensorflow/python/estimator/api/estimator/__init__.py bazel-out/k8-opt/genfiles/tensorflow/python/estimator/api/estimator/export/__init__.py bazel-out/k8-opt/genfiles/tensorflow/python/estimator/api/estimator/inputs/__init__.py')
tf.estimator package not installed.
Traceback (most recent call last):
  File "/home/matt/.cache/bazel/_bazel_matt/b51f46dcf2ef174fa43a943ad13629f0/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/estimator/api/create_tensorflow.python.estimator_api.runfiles/org_tensorflow/tensorflow/python/tools/api/generator/create_python_api.py", line 511, in <module>
    main()
  File "/home/matt/.cache/bazel/_bazel_matt/b51f46dcf2ef174fa43a943ad13629f0/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/estimator/api/create_tensorflow.python.estimator_api.runfiles/org_tensorflow/tensorflow/python/tools/api/generator/create_python_api.py", line 504, in main
    importlib.import_module(args.package)
  File "/opt/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/matt/.cache/bazel/_bazel_matt/b51f46dcf2ef174fa43a943ad13629f0/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/estimator/api/create_tensorflow.python.estimator_api.runfiles/org_tensorflow/tensorflow/python/estimator/__init__.py", line 25, in <module>
    import tensorflow.python.estimator.estimator_lib
  File "/home/matt/.cache/bazel/_bazel_matt/b51f46dcf2ef174fa43a943ad13629f0/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/estimator/api/create_tensorflow.python.estimator_api.runfiles/org_tensorflow/tensorflow/python/estimator/estimator_lib.py", line 41, in <module>
    from tensorflow.python.estimator.inputs import inputs
  File "/home/matt/.cache/bazel/_bazel_matt/b51f46dcf2ef174fa43a943ad13629f0/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/estimator/api/create_tensorflow.python.estimator_api.runfiles/org_tensorflow/tensorflow/python/estimator/inputs/inputs.py", line 23, in <module>
    from tensorflow.python.estimator.inputs.pandas_io import pandas_input_fn
  File "/home/matt/.cache/bazel/_bazel_matt/b51f46dcf2ef174fa43a943ad13629f0/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/estimator/api/create_tensorflow.python.estimator_api.runfiles/org_tensorflow/tensorflow/python/estimator/inputs/pandas_io.py", line 31, in <module>
    import pandas as pd
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/__init__.py", line 42, in <module>
    from pandas.core.api import *
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/api.py", line 10, in <module>
    from pandas.core.groupby.groupby import Grouper
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/groupby/__init__.py", line 2, in <module>
    from pandas.core.groupby.groupby import (
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/groupby/groupby.py", line 49, in <module>
    from pandas.core.frame import DataFrame
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py", line 74, in <module>
    from pandas.core.series import Series
  File "/opt/anaconda3/lib/python3.6/site-packages/pandas/core/series.py", line 67, in <module>
    import pandas.core.ops as ops
AttributeError: module 'pandas' has no attribute 'core'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
```

**Comment by aselle** [comment]
@yifeif, could you ptal.

**Comment by yifeif** [comment]
Does re-install the package help?

**Comment by matt-garman** [comment]
To which package are you referring?

**Comment by yifeif** [comment]
Sorry for not being clear @matt-garman. I meant pandas.

**Comment by matt-garman** [comment]
I just un-installed, then re-installed pandas v0.23.4: same result as
posted above.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @yifeif: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @yifeif: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @yifeif: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @yifeif: It has been 74 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @yifeif: It has been 89 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @yifeif: It has been 104 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by DavidNorman** [comment]
i have the same issue.  how come pandas is not listed in the dependencies of the pip setup.py?

it is listed in the build environment dependencies in ci_build

```
install/install_python3.5_pip_packages.sh:# pandas required by `inflow`
install/install_python3.5_pip_packages.sh:pip3 install pandas==0.19.2
install/install_python3.6_pip_packages.sh:# pandas required by `inflow`
install/install_python3.6_pip_packages.sh:pip3 install pandas==0.19.2
install/install_pip_packages.sh:# pandas required by `inflow`
install/install_pip_packages.sh:pip2 install pandas==0.19.2
install/install_pip_packages.sh:pip3 install pandas==0.19.2
```

**Comment by DavidNorman** [comment]
perhaps it was transitively pulled in by something else which TF depends upon, which has removed recently.

**Comment by DavidNorman** [comment]
Here is my backtrace.

```
Traceback (most recent call last):
  File "tf.py", line 1, in <module>
    import tensorflow as tf
  File "/home/buildslave/workdir/buildslave/framework_comparison_ubuntu_18_04_python2/workspace/external/framework-comparison/tensorflow/local/lib/python2.7/site-packages/tensorflow/__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/buildslave/workdir/buildslave/framework_comparison_ubuntu_18_04_python2/workspace/external/framework-comparison/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 82, in <module>
    from tensorflow.python import keras
  File "/home/buildslave/workdir/buildslave/framework_comparison_ubuntu_18_04_python2/workspace/external/framework-comparison/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/keras/__init__.py", line 29, in <module>
    from tensorflow.python.keras import datasets
  File "/home/buildslave/workdir/buildslave/framework_comparison_ubuntu_18_04_python2/workspace/external/framework-comparison/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/keras/datasets/__init__.py", line 25, in <module>
    from tensorflow.python.keras.datasets import imdb
  File "/home/buildslave/workdir/buildslave/framework_comparison_ubuntu_18_04_python2/workspace/external/framework-comparison/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/keras/datasets/imdb.py", line 25, in <module>
    from tensorflow.python.keras.preprocessing.sequence import _remove_long_seq
  File "/home/buildslave/workdir/buildslave/framework_comparison_ubuntu_18_04_python2/workspace/external/framework-comparison/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/keras/preprocessing/__init__.py", line 30, in <module>
    from tensorflow.python.keras.preprocessing import image
  File "/home/buildslave/workdir/buildslave/framework_comparison_ubuntu_18_04_python2/workspace/external/framework-comparison/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/keras/preprocessing/image.py", line 23, in <module>
    from keras_preprocessing import image
  File "/home/buildslave/workdir/buildslave/framework_comparison_ubuntu_18_04_python2/workspace/external/framework-comparison/tensorflow/local/lib/python2.7/site-packages/keras_preprocessing/image/__init__.py", line 8, in <module>
    from .dataframe_iterator import DataFrameIterator
  File "/home/buildslave/workdir/buildslave/framework_comparison_ubuntu_18_04_python2/workspace/external/framework-comparison/tensorflow/local/lib/python2.7/site-packages/keras_preprocessing/image/dataframe_iterator.py", line 11, in <module>
    from pandas.api.types import is_numeric_dtype
ImportError: No module named pandas.api.types
```

this TF installation has been installed from the pip wheel generated by `bazel build --config=opt tensorflow/tools/pip_package:build_pip_package`

**Comment by DavidNorman** [comment]
ah ha - https://github.com/keras-team/keras-preprocessing/issues/154
