### ISSUE TITLE
export_tflite_ssd_graph_lib.py didn't work with 1.10.0-rc1 ?

### ISSUE THREAD

**Issue by MaeThird** [tensorflow/tensorflow#21506]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Y
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux  4.17.11-arch1
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: None of them
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**:b'v1.9.0-rc2-1981-gb674f63ab1' 1.10.0-rc1
- **Python version**: 3.6
- **Bazel version (if compiling from source)**: 0.15.2- (@non-git)
- **GCC/Compiler version (if compiling from source)**: gcc-7
- **CUDA/cuDNN version**: cuda-9.2 cudnn-7.1
- **GPU model and memory**: 24G
- **Exact command to reproduce**: 

**Everything works fine before I updated the newest source code ,compiled and installed it**.
With the installed version(1.10.0-rc1) the **export_tflite_ssd_graph_lib.py**  said 

`
2018-08-09 03:18:34.547212: I tensorflow/tools/graph_transforms/transform_graph.cc:318] Applying strip_unused_nodes
2018-08-09 03:18:34.565931: I tensorflow/tools/graph_transforms/transform_graph.cc:318] Applying fold_constants
Traceback (most recent call last):
  File "export_tflite_ssd_graph.py", line 137, in <module>
    tf.app.run(main)
  File "/usr/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "export_tflite_ssd_graph.py", line 133, in main
    FLAGS.max_classes_per_detection)
  File "/home/mae/tf-newest-nightly/tensorflow/tensorflow/models/research/object_detection/export_tflite_ssd_graph_lib.py", line 280, in export_tflite_graph
    nms_score_threshold, nms_iou_threshold, num_classes, scale_values)
  File "/home/mae/tf-newest-nightly/tensorflow/tensorflow/models/research/object_detection/export_tflite_ssd_graph_lib.py", line 137, in append_postprocessing_op
    output_names, transforms)
  File "/usr/lib/python3.6/site-packages/tensorflow/tools/graph_transforms/__init__.py", line 51, in TransformGraph
    transforms_string, status)
  File "/usr/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 519, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'TFLite_Detection_PostProcess' in binary running on Mae. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.
`

Other scripts such as train and eval can work except the exporter.

**Comment by MaeThird** [comment]
I found If i remove the 'fold_constants' in **TransformGraph** processing,it would be OK. Thanks.

**Comment by zhyj3038** [comment]
hello, how did you remove the 'fold_constants'?     I face the same problem and can not find  "fold_constants".
