### ISSUE TITLE
tf.contrib.ffmpeg.decode_video Error

### ISSUE THREAD

**Issue by Flowerfan** [tensorflow/tensorflow#21549]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: pip
- **TensorFlow version (use command below)**: 1.9.0
- **Python version**:  2.7
- **GCC/Compiler version (if compiling from source)**: 4.8
- **CUDA/cuDNN version**: 9.0
- **GPU model and memory**: Titan 1080 Ti

### Describe the problem
I try to use tf.contrib.ffmpeg.decode_video to decode *avi video, but i got errors when processing some videos.

### Source code / logs

Source code:

with tf.Session() as sess:
    for pth in pths:
        print(pth)
        vids = tf.contrib.ffmpeg.decode_video(tf.read_file(pth))
        np_frames = sess.run(vids)

Log Information:

UnknownError                              Traceback (most recent call last)
<ipython-input-3-525c5b7a8b81> in <module>()
      5         print(pth)
      6         vids = tf.contrib.ffmpeg.decode_video(tf.read_file(pth))
----> 7         np_frames = sess.run(vids)
      8         im_shapes += [np_frames.shape]

/home/flowerfan/anaconda3/envs/tf27/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in run(self, fetches, feed_dict, options, run_metadata)
    875     try:
    876       result = self._run(None, fetches, feed_dict, options_ptr,
--> 877                          run_metadata_ptr)
    878       if run_metadata:
    879         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

/home/flowerfan/anaconda3/envs/tf27/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1098     if final_fetches or final_targets or (handle and feed_dict_tensor):
   1099       results = self._do_run(handle, final_targets, final_fetches,
-> 1100                              feed_dict_tensor, options, run_metadata)
   1101     else:
   1102       results = []

/home/flowerfan/anaconda3/envs/tf27/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1270     if handle is None:
   1271       return self._do_call(_run_fn, feeds, fetches, targets, options,
-> 1272                            run_metadata)
   1273     else:
   1274       return self._do_call(_prun_fn, handle, feeds, fetches)

/home/flowerfan/anaconda3/envs/tf27/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in _do_call(self, fn, *args)
   1289         except KeyError:
   1290           pass
-> 1291       raise type(e)(node_def, op, message)
   1292 
   1293   def _extend_graph(self):

UnknownError: Output created by FFmpeg [967449600] does not match description [100, 608, 1360, 3]
	 [[Node: DecodeVideo_5 = DecodeVideo[_device="/job:localhost/replica:0/task:0/device:CPU:0"](ReadFile_5)]]

Caused by op u'DecodeVideo_5', defined at:
  File "/home/flowerfan/anaconda3/envs/tf27/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/flowerfan/anaconda3/envs/tf27/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/flowerfan/anaconda3/envs/tf27/lib/python2.7/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/home/flowerfan/anaconda3/envs/tf27/lib/python2.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/flowerfan/anaconda3/envs/tf27/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 486, in start
    self.io_loop.start()
  File "/home/flowerfan/anaconda3/envs/tf27/lib/python2.7/site-packages/tornado/ioloop.py", line 1064, in start
    handler_func(fd_obj, events)
  File "/home/flowerfan/anaconda3/envs/tf27/lib/python2.7/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/flowerfan/anaconda3/envs/tf27/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 450, in _handle_events
    self._handle_recv()
  File "/home/flowerfan/anaconda3/envs/tf27/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 480, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/flowerfan/anaconda3/envs/tf27/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 432, in _run_callback
    callback(*args, **kwargs)
  File "/home/flowerfan/anaconda3/envs/tf27/lib/python2.7/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/flowerfan/anaconda3/envs/tf27/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/home/flowerfan/anaconda3/envs/tf27/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "/home/flowerfan/anaconda3/envs/tf27/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/home/flowerfan/anaconda3/envs/tf27/lib/python2.7/site-packages/ipykernel/ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/home/flowerfan/anaconda3/envs/tf27/lib/python2.7/site-packages/ipykernel/zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/home/flowerfan/anaconda3/envs/tf27/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2714, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/home/flowerfan/anaconda3/envs/tf27/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2818, in run_ast_nodes
    if self.run_code(code, result):
  File "/home/flowerfan/anaconda3/envs/tf27/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2878, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-525c5b7a8b81>", line 6, in <module>
    vids = tf.contrib.ffmpeg.decode_video(tf.read_file(pth))
  File "/home/flowerfan/anaconda3/envs/tf27/lib/python2.7/site-packages/tensorflow/contrib/ffmpeg/ffmpeg_ops.py", line 108, in decode_video
    return gen_decode_video_op_py.decode_video(contents)
  File "/home/flowerfan/anaconda3/envs/tf27/lib/python2.7/site-packages/tensorflow/contrib/ffmpeg/ops/gen_decode_video_op_py.py", line 46, in decode_video
    "DecodeVideo", contents=contents, name=name)
  File "/home/flowerfan/anaconda3/envs/tf27/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/flowerfan/anaconda3/envs/tf27/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "/home/flowerfan/anaconda3/envs/tf27/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3155, in create_op
    op_def=op_def)
  File "/home/flowerfan/anaconda3/envs/tf27/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1717, in __init__
    self._traceback = tf_stack.extract_stack()

UnknownError (see above for traceback): Output created by FFmpeg [967449600] does not match description [100, 608, 1360, 3]
	 [[Node: DecodeVideo_5 = DecodeVideo[_device="/job:localhost/replica:0/task:0/device:CPU:0"](ReadFile_5)]]

**Comment by yongtang** [comment]
@Flowerfan Would you mind to provide one video samples that trigger the issue described?

**Comment by Flowerfan** [comment]
[VIRAT_S_000000_0023.avi.zip](https://github.com/tensorflow/tensorflow/files/2280711/VIRAT_S_000000_0023.avi.zip)
@yongtang  I uploaded the video.

Below is the video info using ffprobe
ffprobe version 2.8.14-0ubuntu0.16.04.1 Copyright (c) 2007-2018 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.9) 20160609
  configuration: --prefix=/usr --extra-version=0ubuntu0.16.04.1 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
Input #0, avi, from '/home/flowerfan/data/cubes/gt_train/VIRAT_S_000000/VIRAT_S_000000_0023.avi':
  Metadata:
    encoder         : Lavf56.40.101
  Duration: 00:00:13.00, start: 0.000000, bitrate: 1000 kb/s
    Stream #0:0: Video: h264 (High) (H264 / 0x34363248), yuv420p, 1360x608, 993 kb/s, 30 fps, 30 tbr, 30 tbn, 60 tbc

**Comment by tensorflowbutler** [comment]
Nagging Assignee @yongtang: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @yongtang: It has been 30 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @yongtang: It has been 45 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @yongtang: It has been 60 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @yongtang: It has been 75 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @yongtang: It has been 90 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @yongtang: It has been 105 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by yongtang** [comment]
@Flowerfan The tf.contrib.ffmpeg in tensorflow repo has been deprecated and will be removed in 2.0 (soon to be released). The video decoding functionality support is now in `tensorflow/io` repo:

https://github.com/tensorflow/io

Also google group discussion: https://groups.google.com/a/tensorflow.org/forum/#!forum/io

I tried your sample video with `tensorflow-io`, everything seems to be fine.

I will close this issue for now. But if you continue to encounter issues with the video clip when using `tensorflow-io`, you can create an issue in https://github.com/tensorflow/io
