### ISSUE TITLE
Issue with tensorflow runtime. Failed to load DLL.

### ISSUE THREAD

**Issue by meghabhamare** [tensorflow/tensorflow#21731]
The issue 
I have installed tensorflow 1.10.0 on my Win 7 machine and trying to do an 
import tensorflow as tf 
gives an "Dll failed to load" error. 

### Source code / logs
 Code
import tensorflow as tf

Error on the console
runfile('C:/Users/Teluser/Desktop/Megha/FujitsuCode/test_tensorflow.py', wdir='C:/Users/Teluser/Desktop/Megha/FujitsuCode')
Traceback (most recent call last):

  File "<ipython-input-1-88270b61ce99>", line 1, in <module>
    runfile('C:/Users/Teluser/Desktop/Megha/FujitsuCode/test_tensorflow.py', wdir='C:/Users/Teluser/Desktop/Megha/FujitsuCode')

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/Teluser/Desktop/Megha/FujitsuCode/test_tensorflow.py", line 8, in <module>
    import tensorflow as tf

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\__init__.py", line 22, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)

ImportError: Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\ProgramData\Anaconda3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed with error code -1073741795

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 17, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 16, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow_internal')
  File "C:\ProgramData\Anaconda3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

I found many such issues but no exact resolution. Please can anyone help me here to understand what I am missing ?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by andrewgconnors** [comment]
I saw this exact stack trace when updating from TF 1.8 to 1.10 on Windows 10. Installing 2015 Visual C++ Redistributable fixed the import for me. I think the error was happening due to missing vcomp140.dll, but I'm not 100% sure because the output of Dependency Walker on Windows 10 is cluttered with a lot of errors about missing DLLs that have actually just been moved, and I didn't bother to check exactly what DLL was causing the error after it was fixed. However, I'm not sure how using anaconda might change the environment compared to using pip. If installing that doesn't work, you could also try using Dependency Walker and see what dependencies it finds are missing.

**Comment by meghabhamare** [comment]
I have downloaded TF 1.9 and that seemed to fix the issue. Probably problem with TF1.10.

Thanks

**Comment by josephzjw** [comment]
@andrewgconnors I took your advice and installed the 2015 Visual C++ Redistributable.  Now I can import tensorflow without error dll. Then I checked the `windows\system32\` and found the `msvcp140.dll` was there (before there was not)... Thx!
