### ISSUE TITLE
OverflowError: timeout value is too large

### ISSUE THREAD

**Issue by chouqin3** [tensorflow/tensorflow#21760]
Preliminaries：win10, tensorflow-gpu1.8. I got bugs like this.
Traceback (most recent call last):
  File "D:/Workspace/PythonProjects/studyProjects/multisensory/src/sep_video.py", line 450, in <module>
    ig.show(table)
  File "D:\Workspace\PythonProjects\studyProjects\multisensory\src\aolib\img.py", line 13, in show
    return imtable.show(*args, **kwargs)
  File "D:\Workspace\PythonProjects\studyProjects\multisensory\src\aolib\imtable.py", line 72, in show_table
    html_rows = html_from_rows(table, output_dir)
  File "D:\Workspace\PythonProjects\studyProjects\multisensory\src\aolib\imtable.py", line 413, in html_from_rows
    html_rows.append("<td>" + "<td>".join(html_from_cell(x, output_dir) for x in row))
  File "D:\Workspace\PythonProjects\studyProjects\multisensory\src\aolib\imtable.py", line 413, in <genexpr>
    html_rows.append("<td>" + "<td>".join(html_from_cell(x, output_dir) for x in row))
  File "D:\Workspace\PythonProjects\studyProjects\multisensory\src\aolib\imtable.py", line 308, in html_from_cell
    return x.make_html(output_dir)
  File "D:\Workspace\PythonProjects\studyProjects\multisensory\src\aolib\imtable.py", line 587, in make_html
    make_video(fname, self.ims, self.fps, sound = self.sound)
  File "D:\Workspace\PythonProjects\studyProjects\multisensory\src\aolib\imtable.py", line 498, in make_video
    [(i, x, in_dir, tmp_ext) for i, x in enumerate(ims)])
  File "D:\Workspace\PythonProjects\studyProjects\multisensory\src\aolib\util.py", line 2725, in parmap
    ret = pool.map_async(f, xs).get(10000000)
  File "C:\Anaconda3\envs\tensorflow-gpu\lib\multiprocessing\pool.py", line 638, in get
    self.wait(timeout)
  File "C:\Anaconda3\envs\tensorflow-gpu\lib\multiprocessing\pool.py", line 635, in wait
    self._event.wait(timeout)
  File "C:\Anaconda3\envs\tensorflow-gpu\lib\threading.py", line 551, in wait
    signaled = self._cond.wait(timeout)
  File "C:\Anaconda3\envs\tensorflow-gpu\lib\threading.py", line 299, in wait
    gotit = waiter.acquire(True, timeout)
OverflowError: timeout value is too large

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by asimshankar** [comment]
I apologize, but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new). Please provide all the information it asks. Thank you.

In particular, a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) will be helpful.

That said, just looking at the stacktrace, it seems you're using the Python multiprocessing module, which may not be friendly to the TensorFlow runtime (see https://github.com/tensorflow/tensorflow/issues/8220#issuecomment-302826884 as well).
