### ISSUE TITLE
Cannot set name of tf.keras.models

### ISSUE THREAD

**Issue by Dapid** [tensorflow/tensorflow#21769]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Fedora Linux 27
- **TensorFlow installed from (source or binary)**: Binary wheel
- **TensorFlow version (use command below)**: 1.10.0
- **Python version**: 3.6
- **Keras version**: 2.2.0
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**: See below
- **Mobile device**: N/A

### Describe the problem

The name of models created with the embedded version of Keras cannot be changed, as seen in the example. Raises an Attribute error. The same works with the standalone Keras library.

### Source code / logs
```
EMBEDDED = True
if EMBEDDED:
    from tensorflow.keras.layers import Input, Dense
    from tensorflow.keras.models import Model
else:
    from keras.layers import Input, Dense
    from keras.models import Model

inp = Input((32,))
x = Dense(1)(inp)
model = Model(inp, x)
model.name = 'mymodel'
```
Setting EMBEDDED to False it uses the independent Keras library, and it works.

Here is the full traceback:
```
Traceback (most recent call last):
  File "/home/david/.PyCharm2018.2/config/scratches/scratch_17.py", line 13, in <module>
    model.name = 'mymodel'
  File "/home/david/.virtualenvs/py36/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 432, in __setattr__
    super(Network, self).__setattr__(name, value)
AttributeError: can't set attribute
```

**Comment by facaiy** [comment]
Does the workaround work for you `model = Model(inp, x, name='mymodel')`?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by Dapid** [comment]
@facaiy it does! Still, it would be nice to have the same API capabilities.

**Comment by facaiy** [comment]
ping @fchollet what do you think?

**Comment by nkcr7** [comment]
You can change the name using a similar way: `model._name = 'mymodel'`. Note that there is a "protected" variable `._name` as well as `.name`. So if you change the `.name`, they conflict.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatatodd: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by Dapid** [comment]
I am OK either way, but I think both APIs should be synchronised.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @facaiy: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by facaiy** [comment]
I'll close the issue,  and please feel free to reopen it if necessary :-)

**Comment by alias-noa** [comment]
I can't figure out how to fix this.  This is my code:

```
def crossover_rnn(model_1, model_2):
    """
    Executes crossover for the RNN in the GA for 2 models, modifying the first model
    :param model_1:
    :param model_2:
    :return:
    """
    # new_model = copy.copy(model_1)
    new_model = model_1

    # Probabilty of models depending on their RMSE test score
    # Lower RMSE score has higher prob
    test_score_total = model_1.test_score + model_2.test_score
    model_1_prob = 1 - (model_1.test_score / test_score_total)
    model_2_prob = 1 - model_1_prob
    # Probabilities of each item for each model (all items have same probabilities)
    model_1_prob_item = model_1_prob / (len(model_1.layers) - 2)
    model_2_prob_item = model_2_prob / (len(model_2.layers) - 2)

    # Number of layers of new generation depend on probability of each model
    num_layers_new_gen = int(model_1_prob * (len(model_1.layers) - 1) + model_2_prob * (len(model_2.layers) - 1))

    # Create list of int with positions of the layers of both models.
    cross_layers_pos = []
    # Create list of weights
    attention_weights = []
    # Add positions of layers for model 1. Input and ouput layer are not added.
    for i in range(2, len(model_1.layers)):
        mod_item = type('', (), {})()
        mod_item.pos = i
        mod_item.model = 1
        cross_layers_pos.append(mod_item)
        attention_weights.append(model_1_prob_item)

    # Add positions of layers for model 2. Input and ouput layer are not added.
    for i in range(2, len(model_2.layers)):
        mod_item = type('', (), {})()
        mod_item.pos = i
        mod_item.model = 2
        cross_layers_pos.append(mod_item)
        attention_weights.append(model_2_prob_item)

    collect_gc()

    # If new num of layers are larger than the num crossover layers, keep num of crossover layers
    if num_layers_new_gen > len(cross_layers_pos):
        num_layers_new_gen = len(cross_layers_pos)

    # Randomly choose num_layers_new_gen layers of the new list
    cross_layers_pos = list(np.random.choice(cross_layers_pos, size=num_layers_new_gen, replace=False,
                                             p=attention_weights))

    # Add both group of hidden layers to new group of layers using previously chosen layer positions of models
    cross_layers = []
    for i in range(len(cross_layers_pos)):
        mod_item = cross_layers_pos[i]
        if mod_item.model == 1:
            cross_layers.append(model_1.layers[mod_item.pos])
        else:
            cross_layers.append(model_2.layers[mod_item.pos])

    collect_gc()

    # Add input layer randomly from parent 1 or parent 2
    bit_random = random.randint(0, 1)
    if bit_random == 0:
        cross_layers.insert(0, model_1.layers[0])
    else:
        cross_layers.insert(0, model_2.layers[0])

    bit_random = random.randint(0, 1)
    if bit_random == 0:
        cross_layers.append(model_1.layers[len(model_1.layers) - 1])
    else:
        cross_layers.append(model_2.layers[len(model_2.layers) - 1])

    # Set new layers
    new_model.layers = cross_layers

    return new_model
```

I get the error: 

  File "Ensemble.py", line 263, in crossover_rnn
    new_model.layers = cross_layers
  File "C:\Users\Noa\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\network.py", line 316, in __setattr__
    super(Network, self).__setattr__(name, value)
AttributeError: can't set attribute

Can anyone tell me how to fix this?

**Comment by alias-noa** [comment]
I'm using tensorflow 1.13.1 with keras 2.2.4

**Comment by ludwikbukowski** [comment]
I have the same issue. Cannot set layer name with tensor flow backend

**Comment by qxde01** [comment]
you can try :
`layer.__class__.name='othername'`
