### ISSUE TITLE
dataloss error tf.records at random times

### ISSUE THREAD

**Issue by Suryabhan90** [tensorflow/tensorflow#21772]
OS Platform and Distribution --> Ubuntu - 18.04.1
TensorFlow installed from --> using pip
TensorFlow version --> 1.8.0
Bazel version --> don't know 
CUDA/cuDNN version --> cuda 9
GPU model and memory --> nvidia Titan XP 12GB

I am stuck at a very strange issue for a long time. This is my problem - 
I have a tfrecords file (name = "Input.tfrecords") from which I read data and then I do some modifcation to the data and store it to another tfrecords file (name = "Output.tfrecods") . Below is the code snippet --

    tf.reset_default_graph()
    config = tf.ConfigProto()
    config.gpu_options.allow_growth = True
    
    
    def _bytes_feature(value):
        return tf.train.Feature(bytes_list=tf.train.BytesList(value=[value]))
    
    
    def _str_feature(value):
        return tf.train.Feature(bytes_list=tf.train.BytesList(value=[value.encode('utf-8')]))
    
    
    def _float_feature(value):
        return tf.train.Feature(float_list=tf.train.FloatList(value=value.reshape(-1)))
    
    
    def _int64_feature(value):
        return tf.train.Feature(int64_list=tf.train.Int64List(value=[value]))
    
    
    def som_function(FLAGS):
        with tf.Graph().as_default() as g:
    
            tfr_writer = tf.python_io.TFRecordWriter(FLAGS.Output_tfrdatafile)
    
            dataset = tf.data.TFRecordDataset(FLAGS.Input_tfrdatafile)
    
            dataset = dataset.map(lambda x: reader.initial_parser(x, FLAGS.HEIGHT, FLAGS.WIDTH))
    
            dataset = dataset.batch(FLAGS.BATCH_SIZE)
            iterator = dataset.make_one_shot_iterator()
    
            images, original_ig, img_name = iterator.get_next()
    
    
            org_batch = tf.Variable(tf.random_normal([FLAGS.BATCH_SIZE, FLAGS.HEIGHT, FLAGS.WIDTH, 3]), trainable=False)
            initial = tf.Variable(tf.random_normal([FLAGS.BATCH_SIZE, FLAGS.HEIGHT, FLAGS.WIDTH, 3]))
            org_batch_assign_op = org_batch.assign(original_ig)
    
            initial_assign_op = initial.assign(images)
    
            total_loss = #someloss function
    
    
    
            train_op = tf.train.MomentumOptimizer(FLAGS.LEARNING_RATE, momentum=0.95, use_nesterov=True,
                                                  name="non_paraopt_SGD").minimize(total_loss,
                                                                                   global_step=global_step)
    
    
            init_op = tf.group(tf.global_variables_initializer(), tf.local_variables_initializer())
    
            with tf.Session(config=config) as sess:
                sess.run(init_op)
                start_time = time.time()
                batches_count = 0
                while True:
                    try:
                        _, _, image_names = sess.run([initial_assign_op,org_batch_assign_op,  img_name])
    
                        //some code that updates initial variable
    
                        org_batch = tf.cast(org_batch, tf.uint8)
                        image_t, org_image_t = sess.run([initial, org_batch])
    
                        if not FLAGS.addNetworklose:
                            lambda_val = np.zeros(image_t.shape).astype(np.float32)
    
                        for i in range(image_t.shape[0]):
                            filename = str(image_names[i], 'utf-8')
    
                            example = tf.train.Example(features=tf.train.Features(feature={
                                    'file_name': _str_feature(filename),
                                    'float_image': _float_feature(image_t[i] + reader.mean_pixel),
                                    'image_raw': _bytes_feature(org_image_t[i].tostring()),
                                    'lambda_image': _float_feature(lambda_val[i])
                                }))
                            tfr_writer.write(example.SerializeToString())
    
                        batches_count = batches_count + 1
                    except tf.errors.OutOfRangeError:
                        print("final time elspased", (time.time() - start_time))
                        print('Done doing non paramteric part')
                        break
    
                tfr_writer.close()

I always succesfully creats the  "Output.tfrecods".But whenever I read the file  "Output.tfrecods"file, I randomly get the **Dataloss Error**. This is where I am trying to read the Output.tfrecods file.
```
def start_training(FLAGS):
    tf.reset_default_graph()
    run_id = FLAGS.MODEL_NAME if FLAGS.MODEL_NAME else str(uuid.uuid4())

    if not os.path.exists(FLAGS.summary_path):
        os.makedirs(FLAGS.summary_path)

    model_path = '%s/%s' % (FLAGS.MODEL_DIR, run_id)
    if not os.path.exists(model_path):
        os.makedirs(model_path)

    training_dataset = tf.data.TFRecordDataset(FLAGS.Training_tfrdatafile)
    training_dataset = training_dataset.map(lambda x: reader.lambda_parser(x, FLAGS.HEIGHT, FLAGS.WIDTH))

    training_dataset = training_dataset.batch(FLAGS.BATCH_SIZE)
    min_queue_examples = int(FLAGS.EPOCHS * 0.4)
    training_dataset = training_dataset.shuffle(buffer_size=min_queue_examples + 3 * FLAGS.BATCH_SIZE)

    validation_dataset = tf.data.TFRecordDataset(FLAGS.Validation_tfrdatafile)
    validation_dataset = validation_dataset.map(lambda x: reader.lambda_parser(x, FLAGS.HEIGHT, FLAGS.WIDTH))
    validation_dataset = validation_dataset.batch(FLAGS.VAL_BATCH_SIZE)
    
    iterator = tf.data.Iterator.from_structure(training_dataset.output_types,
                                               training_dataset.output_shapes)

    training_init_op = iterator.make_initializer(training_dataset)
    validation_init_op = iterator.make_initializer(validation_dataset)

    target_ig, images, img_name, _ = iterator.get_next()

    ae_inputs = tf.placeholder(tf.float32, (None, FLAGS.HEIGHT, FLAGS.WIDTH, 3),
                               name='auto_input')  # input to the network (MNIST images)
    target = tf.placeholder(tf.float32, (None, FLAGS.HEIGHT, FLAGS.WIDTH, 3),
                            name='target')

    ae_output = model.net(ae_inputs, training=True)

    learning_rate = tf.placeholder(tf.float32, shape=[], name='learning_rate')
    img_loss = tf.nn.l2_loss((target - ae_output), name='img_l2loss') / tf.to_float(size2)

    tv_loss = total_variation_loss(ae_output, FLAGS.HEIGHT, FLAGS.WIDTH)
    loss = img_loss + 200.0 * tv_loss

    global_step = tf.Variable(FLAGS.gs_val, name="p_global_step", trainable=False)

    
    train_op = tf.train.AdamOptimizer(learning_rate, name="p_trainopt").minimize(loss, global_step=global_step)
    
    init_op = tf.group(tf.global_variables_initializer(), tf.local_variables_initializer())
    return_lr = FLAGS.LEARNING_RATE

    with tf.Session(config=config) as sess:
        
        saver = tf.train.Saver(tf.trainable_variables())
        if FLAGS.ModelFromName:
            file = FLAGS.MODEL_FILENAME
        else:
            file = tf.train.latest_checkpoint(model_path)
        # file = model_path + '/' + FLAGS.MODEL_FILENAME

        sess.run(init_op)
        if file:
            print('Restoring model from {}'.format(file))
            saver.restore(sess, file)

        start_time = time.time()
        start_ti = time.time()
        acc_loss = []
        vgg_pl_loss = []
        img_pl_loss = []
        cl_pl_loss = []
        sl_pl_loss = []
        fl_pl_loss = []

        cont_los_FF = 0
        stl_los_FF = 0

        total_batches = FLAGS.TOTALINPUT // FLAGS.BATCH_SIZE
        val_batches = FLAGS.TOTALVAL // FLAGS.VAL_BATCH_SIZE
        print('the value of total batches is: ', total_batches)
        for ep_count in range(FLAGS.EPOCHS):
            sess.run(training_init_op)
            count = 1
            st_t = time.time()
            # if ep_count+1 <= FLAGS.EPOCHS  or ep_count == 0:
            while True:
                try:
                    ig_b, tg_b = sess.run([images, target_ig])

                    _, loss_t,img_l2_t, step = sess.run([train_op, loss, img_loss],feed_dict={ae_inputs: ig_b,
                                                                                           target: tg_b,
                                                                                           learning_rate: FLAGS.LEARNING_RATE})
                                                                                
                    count = count + 1
                except tf.errors.OutOfRangeError:
                    print("final time elspased", (time.time() - st_t))
                    #  print('Done doing non paramteric part')
                    break

            print('Number of epochs done= ', (ep_count + 1))
            if (ep_count + 1) % FLAGS.chanelr == 0:
                print('the value of count is: ', count)
                FLAGS.LEARNING_RATE = FLAGS.LEARNING_RATE / FLAGS.div
                print('learning rate now: ', FLAGS.LEARNING_RATE)
                return_lr = FLAGS.LEARNING_RATE

        print(step, loss_t, elapsed_time)
        saver.save(sess, model_path + '/style-model', global_step=step)
        nameofmodel = model_path + '/style-model-' + str(step)
        print("final time elspased", (time.time() - start_ti))
        print('Done training -- epoch limit reached')

    return step, return_lr, nameofmodel
```

I have to restart my system and re-run the above code for 5-6 times and then it works fine. And when I run the same code on a different linux machine its work fine all the time. I really don't know what is the issue here.

Thanks in advance. Please comment if need more explanation from my side. 

Here is the stack trace
```

Traceback (most recent call last):
  File "/home/suryabhan/anaconda3/envs/nn_env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1322, in _do_call
    return fn(*args)
  File "/home/suryabhan/anaconda3/envs/nn_env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/suryabhan/anaconda3/envs/nn_env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.DataLossError: corrupted record at 775087002
         [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[?,256,256,3], [?,256,256,3], [?], [?,256,256,3]], output_types=[DT_FLOAT, DT_FLOAT, DT_STRI
NG, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](Iterator)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Maincreateall.py", line 240, in <module>
    main()
  File "Maincreateall.py", line 194, in main
    opts_para["gs_val"], nameofmodel = tm.train_model(opts_para)
  File "/home/suryabhan/Desktop/New_NST_MAC/teststuff.py", line 465, in train_model
    gs,_,nameofmodel = start_training(FLAGS)
  File "/home/suryabhan/Desktop/New_NST_MAC/teststuff.py", line 277, in start_training
    ig_b, tg_b = sess.run([images, target_ig])
  File "/home/suryabhan/anaconda3/envs/nn_env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/home/suryabhan/anaconda3/envs/nn_env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/suryabhan/anaconda3/envs/nn_env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/home/suryabhan/anaconda3/envs/nn_env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.DataLossError: corrupted record at 775087002
         [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[?,256,256,3], [?,256,256,3], [?], [?,256,256,3]], output_types=[DT_FLOAT, DT_FLOAT, DT_STRI
NG, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](Iterator)]]

Caused by op 'IteratorGetNext', defined at:
  File "Maincreateall.py", line 240, in <module>
    main()
  File "Maincreateall.py", line 194, in main
    opts_para["gs_val"], nameofmodel = tm.train_model(opts_para)
  File "/home/suryabhan/Desktop/New_NST_MAC/teststuff.py", line 465, in train_model
    gs,_,nameofmodel = start_training(FLAGS)
  File "/home/suryabhan/Desktop/New_NST_MAC/teststuff.py", line 137, in start_training
    target_ig, images, img_name,_ = iterator.get_next()
  File "/home/suryabhan/anaconda3/envs/nn_env/lib/python3.6/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 370, in get_next
    name=name)), self._output_types,
  File "/home/suryabhan/anaconda3/envs/nn_env/lib/python3.6/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 1466, in iterator_get_next
    output_shapes=output_shapes, name=name)
  File "/home/suryabhan/anaconda3/envs/nn_env/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/suryabhan/anaconda3/envs/nn_env/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/home/suryabhan/anaconda3/envs/nn_env/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

DataLossError (see above for traceback): corrupted record at 775087002
         [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[?,256,256,3], [?,256,256,3], [?], [?,256,256,3]], output_types=[DT_FLOAT, DT_FLOAT, DT_STRI
NG, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](Iterator)]]
```

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by Suryabhan90** [comment]
I have udated the information

**Comment by karmel** [comment]
Thanks @Suryabhan90 -- can you provide the stack trace for the error you are seeing?

**Comment by Suryabhan90** [comment]
I have updated the information

**Comment by stillwalker1234** [comment]
I have the exact same problem, can I ask what CPU you are using?

**Comment by Suryabhan90** [comment]
@stillwalker1234  Here are the CPU details - 
model name	: Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              8
On-line CPU(s) list: 0-7
Thread(s) per core:  2
Core(s) per socket:  4
Socket(s):           1
NUMA node(s):        1

**Comment by karmel** [comment]
What does record 775087002 look like in the file? Can you reproduce the error by just reading the file, and remove all the actual training above? That will help isolate the problem.

**Comment by Suryabhan90** [comment]
@karmel I have another file which just reads the data when I read the file through it. Yes it gives the error of "Dataloss" as expected but when type the command 

> sudo sh -c "sync; echo 1 > /proc/sys/vm/drop_caches"

It works fine after that. But after a while, the error comes back with a different record.
Btw --> 
The record is of following type - 
 tf.train.Example(features=tf.train.Features(feature={
                                'file_name': _str_feature(filename),
                                'float_image': _float_feature(image_t[i] + reader.mean_pixel),
                                'image_raw': _bytes_feature(org_image_t[i].tostring()),
                                'lambda_image': _float_feature(lambda_val[i])
                            }))

**Comment by stillwalker1234** [comment]
That is exactly the same error i have (and the same temporary fix). Curruption happens in memory.

________________________________

**Comment by tensorflowbutler** [comment]
Nagging Assignee @karmel: It has been 17 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @karmel: It has been 31 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @karmel: It has been 46 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by karmel** [comment]
Unfortunately, this is very hard for us to replicate. Is there any way you can produce a minimal example that we can replicate on our side?

**Comment by tensorflowbutler** [comment]
Nagging Assignee @karmel: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @karmel: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @karmel: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
It has been 29 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
It has been 44 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by clstl** [comment]
Experiencing the same issue, posted at `tesnsorflow/models` https://github.com/tensorflow/models/issues/6053

**Comment by gitmcdull** [comment]
This issue has driven me mad. I trained a transformer using the codes & data from tensorflow/models. 
The problem of datalosserror corrupted record popped up at random steps. As shown in the following snippet, the training process failed around step 40300. While in other cases, it might fail at the very begining. It's so wired.
<img width="1127" alt="481e79e5-2cbd-429f-9ad8-54dfcc4860a4" src="https://user-images.githubusercontent.com/17263464/51719756-b3c0b180-2085-11e9-8445-c270ec42a02d.png">

**Comment by tensorflowbutler** [comment]
It has been 20 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
It has been 35 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
We are closing this issue for now due to lack of activity. Please comment if this is still an issue for you. Thanks!

**Comment by clstl** [comment]
Yep

**Comment by abal6725** [comment]
I am having this same issue.
