### ISSUE TITLE
MirroredStrategy 

### ISSUE THREAD

**Issue by anilmaddala** [tensorflow/tensorflow#21786]
System Information:
```./tf_env_collect.sh 
Collecting system information...
/home/ubuntu/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2018-08-22 06:54:38.919033: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:897] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-08-22 06:54:38.919644: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1392] Found device 0 with properties: 
name: GRID K520 major: 3 minor: 0 memoryClockRate(GHz): 0.797
pciBusID: 0000:00:03.0
totalMemory: 3.94GiB freeMemory: 3.90GiB
2018-08-22 06:54:38.948734: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:897] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-08-22 06:54:38.949481: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1392] Found device 1 with properties: 
name: GRID K520 major: 3 minor: 0 memoryClockRate(GHz): 0.797
pciBusID: 0000:00:04.0
totalMemory: 3.94GiB freeMemory: 3.90GiB
2018-08-22 06:54:38.981236: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:897] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-08-22 06:54:38.981765: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1392] Found device 2 with properties: 
name: GRID K520 major: 3 minor: 0 memoryClockRate(GHz): 0.797
pciBusID: 0000:00:05.0
totalMemory: 3.94GiB freeMemory: 3.90GiB
2018-08-22 06:54:39.013129: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:897] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-08-22 06:54:39.013651: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1392] Found device 3 with properties: 
name: GRID K520 major: 3 minor: 0 memoryClockRate(GHz): 0.797
pciBusID: 0000:00:06.0
totalMemory: 3.94GiB freeMemory: 3.90GiB
2018-08-22 06:54:39.013798: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1471] Adding visible gpu devices: 0, 1, 2, 3
2018-08-22 06:54:40.283791: I tensorflow/core/common_runtime/gpu/gpu_device.cc:952] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-08-22 06:54:40.283880: I tensorflow/core/common_runtime/gpu/gpu_device.cc:958]      0 1 2 3 
2018-08-22 06:54:40.283908: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   N N N N 
2018-08-22 06:54:40.283920: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 1:   N N N N 
2018-08-22 06:54:40.283934: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 2:   N N N N 
2018-08-22 06:54:40.283944: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 3:   N N N N 
2018-08-22 06:54:40.284549: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3648 MB memory) -> physical GPU (device: 0, name: GRID K520, pci bus id: 0000:00:03.0, compute capability: 3.0)
2018-08-22 06:54:40.321176: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 3648 MB memory) -> physical GPU (device: 1, name: GRID K520, pci bus id: 0000:00:04.0, compute capability: 3.0)
2018-08-22 06:54:40.357480: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:2 with 3648 MB memory) -> physical GPU (device: 2, name: GRID K520, pci bus id: 0000:00:05.0, compute capability: 3.0)
2018-08-22 06:54:40.394082: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:3 with 3648 MB memory) -> physical GPU (device: 3, name: GRID K520, pci bus id: 0000:00:06.0, compute capability: 3.0)
Wrote environment to tf_env.txt. You can review the contents of that file.
and use it to populate the fields in the github issue template.

cat tf_env.txt```

TF Version:
```tf.GIT_VERSION: b'v1.9.0-0-g25c197e' 
tf.VERSION: 1.9.0```

### Describe the problem
I am retraining ssd_mobilenet_v1_coco and following the steps as per https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_locally.md

I am able to run the retraining using OneDeviceStrategy and None distribution.
However when using MirroredStrategy I get the following error:

```2018-08-22 06:49:29.272903: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:897] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-08-22 06:49:29.273436: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1392] Found device 0 with properties: 
name: GRID K520 major: 3 minor: 0 memoryClockRate(GHz): 0.797
pciBusID: 0000:00:03.0
totalMemory: 3.94GiB freeMemory: 3.90GiB
2018-08-22 06:49:29.309479: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:897] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-08-22 06:49:29.310018: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1392] Found device 1 with properties: 
name: GRID K520 major: 3 minor: 0 memoryClockRate(GHz): 0.797
pciBusID: 0000:00:04.0
totalMemory: 3.94GiB freeMemory: 3.90GiB
2018-08-22 06:49:29.343433: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:897] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-08-22 06:49:29.343977: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1392] Found device 2 with properties: 
name: GRID K520 major: 3 minor: 0 memoryClockRate(GHz): 0.797
pciBusID: 0000:00:05.0
totalMemory: 3.94GiB freeMemory: 3.90GiB
2018-08-22 06:49:29.379652: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:897] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-08-22 06:49:29.380222: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1392] Found device 3 with properties: 
name: GRID K520 major: 3 minor: 0 memoryClockRate(GHz): 0.797
pciBusID: 0000:00:06.0
totalMemory: 3.94GiB freeMemory: 3.90GiB
2018-08-22 06:49:29.380429: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1471] Adding visible gpu devices: 0, 1, 2, 3
2018-08-22 06:49:30.617246: I tensorflow/core/common_runtime/gpu/gpu_device.cc:952] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-08-22 06:49:30.617312: I tensorflow/core/common_runtime/gpu/gpu_device.cc:958]      0 1 2 3 
2018-08-22 06:49:30.617327: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   N N N N 
2018-08-22 06:49:30.617345: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 1:   N N N N 
2018-08-22 06:49:30.617360: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 2:   N N N N 
2018-08-22 06:49:30.617371: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 3:   N N N N 
2018-08-22 06:49:30.617926: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3648 MB memory) -> physical GPU (device: 0, name: GRID K520, pci bus id: 0000:00:03.0, compute capability: 3.0)
2018-08-22 06:49:30.653271: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 3648 MB memory) -> physical GPU (device: 1, name: GRID K520, pci bus id: 0000:00:04.0, compute capability: 3.0)
2018-08-22 06:49:30.689029: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:2 with 3648 MB memory) -> physical GPU (device: 2, name: GRID K520, pci bus id: 0000:00:05.0, compute capability: 3.0)
2018-08-22 06:49:30.724507: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:3 with 3648 MB memory) -> physical GPU (device: 3, name: GRID K520, pci bus id: 0000:00:06.0, compute capability: 3.0)
WARNING:tensorflow:Estimator's model_fn (<function create_model_fn.<locals>.model_fn at 0x7f679afa32f0>) includes params argument, but params are not passed to Estimator.
2018-08-22 06:49:30.781121: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1471] Adding visible gpu devices: 0, 1, 2, 3
2018-08-22 06:49:30.781362: I tensorflow/core/common_runtime/gpu/gpu_device.cc:952] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-08-22 06:49:30.781389: I tensorflow/core/common_runtime/gpu/gpu_device.cc:958]      0 1 2 3 
2018-08-22 06:49:30.781409: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   N N N N 
2018-08-22 06:49:30.781424: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 1:   N N N N 
2018-08-22 06:49:30.781442: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 2:   N N N N 
2018-08-22 06:49:30.781458: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 3:   N N N N 
2018-08-22 06:49:30.781801: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1084] Created TensorFlow device (/device:GPU:0 with 3648 MB memory) -> physical GPU (device: 0, name: GRID K520, pci bus id: 0000:00:03.0, compute capability: 3.0)
2018-08-22 06:49:30.781913: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1084] Created TensorFlow device (/device:GPU:1 with 3648 MB memory) -> physical GPU (device: 1, name: GRID K520, pci bus id: 0000:00:04.0, compute capability: 3.0)
2018-08-22 06:49:30.781999: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1084] Created TensorFlow device (/device:GPU:2 with 3648 MB memory) -> physical GPU (device: 2, name: GRID K520, pci bus id: 0000:00:05.0, compute capability: 3.0)
2018-08-22 06:49:30.782122: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1084] Created TensorFlow device (/device:GPU:3 with 3648 MB memory) -> physical GPU (device: 3, name: GRID K520, pci bus id: 0000:00:06.0, compute capability: 3.0)
WARNING:tensorflow:num_readers has been reduced to 2 to match input file shards.
WARNING:tensorflow:From /home/ubuntu/tensorflow/models/research/object_detection/core/preprocessor.py:1205: calling squeeze (from tensorflow.python.ops.array_ops) with squeeze_dims is deprecated and will be removed in a future version.
Instructions for updating:
Use the `axis` argument instead
Traceback (most recent call last):
  File "object_detection/model_main.py", line 106, in <module>
    tf.app.run()
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "object_detection/model_main.py", line 102, in main
    tf.estimator.train_and_evaluate(estimator, train_spec, eval_specs[0])
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/estimator/training.py", line 447, in train_and_evaluate
    return executor.run()
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/estimator/training.py", line 531, in run
    return self.run_local()
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/estimator/training.py", line 669, in run_local
    hooks=train_hooks)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 366, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1117, in _train_model
    return self._train_model_distributed(input_fn, hooks, saving_listeners)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1160, in _train_model_distributed
    self.config)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/distribute.py", line 794, in call_for_each_tower
    return self._call_for_each_tower(fn, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/distribute/python/mirrored_strategy.py", line 269, in _call_for_each_tower
    coord.join(threads)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/coordinator.py", line 297, in stop_on_exception
    yield
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/distribute/python/mirrored_strategy.py", line 479, in run
    self.main_result = self.main_fn(*self.main_args, **self.main_kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1107, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/home/ubuntu/tensorflow/models/research/object_detection/model_lib.py", line 252, in model_fn
    preprocessed_images, features[fields.InputDataFields.true_image_shape])
  File "/home/ubuntu/tensorflow/models/research/object_detection/meta_architectures/ssd_meta_arch.py", line 514, in predict
    preprocessed_inputs)
  File "/home/ubuntu/tensorflow/models/research/object_detection/models/ssd_mobilenet_v1_feature_extractor.py", line 126, in extract_features
    scope=scope)
  File "/home/ubuntu/tensorflow/models/research/slim/nets/mobilenet_v1.py", line 284, in mobilenet_v1_base
    scope=end_point)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 183, in func_with_args
    return func(*args, **current_args)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 2798, in separable_convolution2d
    collections=weights_collections)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 183, in func_with_args
    return func(*args, **current_args)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/framework/python/ops/variables.py", line 297, in model_variable
    use_resource=use_resource)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 183, in func_with_args
    return func(*args, **current_args)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/framework/python/ops/variables.py", line 252, in variable
    use_resource=use_resource)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 1328, in get_variable
    constraint=constraint)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 1090, in get_variable
    constraint=constraint)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 427, in get_variable
    return custom_getter(**custom_getter_kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 1734, in wrapped_custom_getter
    *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 1744, in layer_variable_getter
    return _model_variable_getter(getter, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 1735, in _model_variable_getter
    use_resource=use_resource)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 183, in func_with_args
    return func(*args, **current_args)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/framework/python/ops/variables.py", line 297, in model_variable
    use_resource=use_resource)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 183, in func_with_args
    return func(*args, **current_args)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/framework/python/ops/variables.py", line 252, in variable
    use_resource=use_resource)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/distribute.py", line 599, in disable_partitioned_variables
    return getter(*args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 404, in _true_getter
    use_resource=use_resource, constraint=constraint)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 806, in _get_single_variable
    with ops.colocate_with(v):
  File "/home/ubuntu/anaconda3/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 4219, in _colocate_with_for_gradient
    with self.colocate_with(op, ignore_existing):
  File "/home/ubuntu/anaconda3/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 4272, in colocate_with
    op = internal_convert_to_tensor_or_indexed_slices(op, as_ref=True).op
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1268, in internal_convert_to_tensor_or_indexed_slices
    value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1107, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/distribute/python/values.py", line 245, in _tensor_conversion
    assert not as_ref
AssertionError
```
Following is the code change to https://github.com/tensorflow/models/blob/master/research/object_detection/model_main.py

```def main(unused_argv):
  flags.mark_flag_as_required('model_dir')
  flags.mark_flag_as_required('pipeline_config_path')

  distribution = tf.contrib.distribute.MirroredStrategy()
   config = tf.estimator.RunConfig(model_dir=FLAGS.model_dir,train_distribute=distribution)
```

I am also switched the gpu using OneDeviceStrategy to any of the 4 available GPU without a problem.
I run into the problem only when using MirroredStrategy. Reproducibility 100%

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by anilmaddala** [comment]
I updated the issue to reflect the details. Let me know if you need more details.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @anj-s: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by anj-s** [comment]
This issue has been fixed in TF v1.11. Can you try updating TensorFlow and retrying this example? Thanks!

**Comment by tensorflowbutler** [comment]
Nagging Assignee @anj-s: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @anj-s: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.
