### ISSUE TITLE
//tensorflow/contrib/fused_conv:fused_conv2d_bias_activation_op_test  running into `implementation not found` error

### ISSUE THREAD

**Issue by deven-amd** [tensorflow/tensorflow#21829]
------------------------

### System information
- **Have I written custom code**: No
- **OS Platform and Distribution**:
`tensorflow/tensorflow:1.9.0-devel-gpu-py3` docker container running on `Linux Ubuntu 16.04` host
- **Mobile device**:  Not Applicable
- **TensorFlow installed from (source or binary)**: cloned from repo
- **TensorFlow version (use command below)**: `b'v1.9.0-0-g25c197e' 1.9.0`
- **Python version**: `Python 3.5.2`
- **Bazel version (if compiling from source)**: `0.15.0`
- **GCC/Compiler version (if compiling from source)**: `5.4.0`
- **CUDA/cuDNN version**: 9.0
- **GPU model and memory**: Not Applicable
- **Exact command to reproduce**: 
```
bazel test --config=cuda  //tensorflow/contrib/fused_conv:fused_conv2d_bias_activation_op_test 
```

### Describe the problem

I am unable to run the `fused_conv` example from the contrib area. The error I run into is shown in the `Source code / logs` section below. The problem seems to be that 
- the code in kernel implementation for the `fused_conv2d_bias_activation_op` calls routines that are present in the `_pywrap_tensorflow_internal.so` library
- the shared library created for the custom op `_fused_conv2d_bias_activation_op.so` does **not** have a dependency on the `_pywrap_tensorflow_internal.so` library

I think one way to get past this error would be add the missing library dependency, but I do not know how to go about doing that. 

### Source code / logs

error from bazel command output

```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //tensorflow/contrib/fused_conv:fused_conv2d_bias_activation_op_test
-----------------------------------------------------------------------------
Traceback (most recent call last):
 File "/root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/contrib/fused_conv/fused_conv2d_bias_activation_op_test.runfiles/org_tensorflow/tensorflow/contrib/fused_conv/python/ops/fused_conv2d_bia\
s_activation_op_test.py", line 23, in <module>
   from tensorflow.contrib.fused_conv.python.ops import fused_conv2d_bias_activation_op
 File "/root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/contrib/fused_conv/fused_conv2d_bias_activation_op_test.runfiles/org_tensorflow/tensorflow/contrib/fused_conv/__init__.py", line 22, in <\
module>
   from tensorflow.contrib.fused_conv.python.ops.fused_conv2d_bias_activation_op import *
 File "/root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/contrib/fused_conv/fused_conv2d_bias_activation_op_test.runfiles/org_tensorflow/tensorflow/contrib/fused_conv/python/ops/fused_conv2d_bia\
s_activation_op.py", line 26, in <module>
   resource_loader.get_path_to_datafile("_fused_conv2d_bias_activation_op.so"))
 File "/root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/contrib/fused_conv/fused_conv2d_bias_activation_op_test.runfiles/org_tensorflow/tensorflow/contrib/util/loader.py", line 56, in load_op_l\
ibrary
   ret = load_library.load_op_library(path)
 File "/root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/contrib/fused_conv/fused_conv2d_bias_activation_op_test.runfiles/org_tensorflow/tensorflow/python/framework/load_library.py", line 56, in\
load_op_library
   lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/contrib/fused_conv/fused_conv2d_bias_activation_op_test.runfiles/org_tensorflow/tensorflow\
/contrib/fused_conv/python/ops/_fused_conv2d_bias_activation_op.so: undefined symbol: _ZN10tensorflow7functor10NHWCToNCHWIN5Eigen9GpuDeviceEfLi4EEclERKS3_NS2_9TensorMapINS2_6TensorIKfLi4ELi1ElEELi16ENS2_11MakePointerEEENS7_INS8_IfLi4ELi1ElEELi16ESB_EE
```

note the lack of dependency on `_pywrap_tensorflow_internal.so`

```
root@fptitan1:~/tensorflow# ldd ./bazel-tensorflow/bazel-out/k8-opt/bin/tensorflow/contrib/fused_conv/python/ops/_fused_conv2d_bias_activation_op.so
	linux-vdso.so.1 =>  (0x00007ffebf7a9000)
	libtensorflow_framework.so => /root/tensorflow/./bazel-tensorflow/bazel-out/k8-opt/bin/tensorflow/contrib/fused_conv/python/ops/../../../../../_solib_local/_U_S_Stensorflow_Scontrib_Sfused_Uconv_Cpython_Sops_S_Ufused_Uconv2d_Ubias_Uactivation_Uop.so___Utensorflow/libtensorflow_framework.so (0x00007f93a5e5e000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f93a5b55000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f93a5951000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f93a5734000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f93a552c000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f93a51aa000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f93a4f94000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f93a4bca000)
	libcublas.so.9.0 => /usr/local/cuda-9.0/targets/x86_64-linux/lib/libcublas.so.9.0 (0x00007f93a12c5000)
	libcuda.so.1 => /usr/local/nvidia/lib64/libcuda.so.1 (0x00007f93a0725000)
	libcudnn.so.7 => /usr/lib/x86_64-linux-gnu/libcudnn.so.7 (0x00007f938c734000)
	libcufft.so.9.0 => /usr/local/cuda-9.0/targets/x86_64-linux/lib/libcufft.so.9.0 (0x00007f9384693000)
	libcurand.so.9.0 => /usr/local/cuda-9.0/targets/x86_64-linux/lib/libcurand.so.9.0 (0x00007f938072f000)
	libcudart.so.9.0 => /usr/local/cuda-9.0/targets/x86_64-linux/lib/libcudart.so.9.0 (0x00007f93804c2000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f93a70d5000)
	libnvidia-fatbinaryloader.so.390.30 => /usr/local/nvidia/lib64/libnvidia-fatbinaryloader.so.390.30 (0x00007f9380276000)
```

**Comment by tensorflowbutler** [comment]
Nagging Assignee @robieta: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by cogbee** [comment]
I have the same problem,:
_ZN10tensorflow7functor10NHWCToNCHWIN5Eigen9GpuDeviceEfLi4EEclERKS3_NS2_9TensorMapINS2_6TensorIKfLi4ELi1ElEELi16ENS2_11MakePointerEEENS7_INS8_IfLi4ELi1ElEELi16ESB_EE

when compile contrib/fused_conv, it depends conv_ops_gpu_hdrs(NHWCToNCHWIN is define here)
`cc_library(
    name = "conv_ops_gpu_hdrs",
    hdrs = ["conv_ops_gpu.h"],
)`
but it just a header, and the implements is in a .cu.cc file which is not include in this cc_library.

so how to import the unresolved symbols?????

**Comment by tensorflowbutler** [comment]
Nagging Assignees @robieta, @aaroey: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignees @robieta, @aaroey: It has been 30 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignees @robieta, @aaroey: It has been 46 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by Saduf2019** [comment]
As contrib is deprecated, Please google the name of the module without the tf.contrib part to know it's new location and thus migrating your code accordingly by correcting the import statement.

you may also refer to the below links:
[link](https://stackoverflow.com/questions/55082483/why-can-i-not-import-tensorflow-contrib-i-get-an-error-of-no-module-named-tenso)
[link1](https://www.tensorflow.org/guide/migrate)
