### ISSUE TITLE
Missing quantized implementation of TopK_V2

### ISSUE THREAD

**Issue by Turakar** [tensorflow/tensorflow#21870]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Fedora 27
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: N/A
- **TensorFlow installed from (source or binary)**: `pip install tensorflow-gpu`
- **TensorFlow version (use command below)**: v1.9.0-0-g25c197e023
- **Python version**: 3.6.6
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: 9.0 / 7.1.4
- **GPU model and memory**: 940MX, 2GB VRAM
- **Exact command to reproduce**: see code below

### Describe the problem
I am trying to quantize my network.
There is a special logic in one layer which takes the k highest activations and sets all other to zero.
It is implemented using the following code:
```python
top = tf.nn.top_k(intermediate, k, sorted=True)
min_indices = top.indices[..., -1]
batch_indices = tf.range(intermediate.shape[0], dtype=tf.int32)
total_indices = tf.stack([batch_indices, min_indices], axis=1)
mins = tf.reshape(tf.gather_nd(intermediate, total_indices), [-1, 1])
selection = intermediate >= mins
zeros = tf.zeros(intermediate.shape, dtype=intermediate.dtype)
intermediate = tf.where(selection, x=intermediate, y=zeros)
```
Where `k` is a `int32` placeholder and `intermediate` a Tensor containing the activations of a fully connected layer. It is shaped `[batch_size, nodes]`.

I then call `tf.contrib.quantize.create_training_graph()`, train using Adam and save the weights as a checkpoint. After a reset of the graph I create the eval graph and rewrite it using `tf.contrib.quantize.create_eval_graph()`. That one is saved to a graph definition file. After that I run the following commands:

```
freeze_graph --input_graph definition.pb --input_checkpoint lastcheckpoint --output_graph frozen_graph.pb --output_node=out
```

```
tflite_convert --output_file model.tflite --graph_def_file frozen_graph.pb --inference_type QUANTIZED_UINT8 --input_arrays input/in,density --output_arrays out --mean_values 1,1 --std_dev_values 1,1
```

The second command fails with the following log:

```
2018-08-25 12:39:14.510582: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-08-25 12:39:14.605698: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:897] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-08-25 12:39:14.606404: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1392] Found device 0 with properties: 
name: GeForce 940MX major: 5 minor: 0 memoryClockRate(GHz): 0.8605
pciBusID: 0000:01:00.0
totalMemory: 1.96GiB freeMemory: 1.71GiB
2018-08-25 12:39:14.606429: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1471] Adding visible gpu devices: 0
2018-08-25 12:39:15.293534: I tensorflow/core/common_runtime/gpu/gpu_device.cc:952] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-08-25 12:39:15.293568: I tensorflow/core/common_runtime/gpu/gpu_device.cc:958]      0 
2018-08-25 12:39:15.293576: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   N 
2018-08-25 12:39:15.293738: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 1465 MB memory) -> physical GPU (device: 0, name: GeForce 940MX, pci bus id: 0000:01:00.0, compute capability: 5.0)
Traceback (most recent call last):
  File "/home/t/development/projects/nncompression/JugendForscht2019/venv/bin/tflite_convert", line 11, in <module>
    sys.exit(main())
  File "/home/t/development/projects/nncompression/JugendForscht2019/venv/lib/python3.6/site-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 320, in main
    app.run(main=run_main, argv=sys.argv[:1])
  File "/home/t/development/projects/nncompression/JugendForscht2019/venv/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/home/t/development/projects/nncompression/JugendForscht2019/venv/lib/python3.6/site-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 316, in run_main
    _convert_model(tflite_flags)
  File "/home/t/development/projects/nncompression/JugendForscht2019/venv/lib/python3.6/site-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 121, in _convert_model
    output_data = converter.convert()
  File "/home/t/development/projects/nncompression/JugendForscht2019/venv/lib/python3.6/site-packages/tensorflow/contrib/lite/python/lite.py", line 309, in convert
    allow_custom_ops=self.allow_custom_ops)
  File "/home/t/development/projects/nncompression/JugendForscht2019/venv/lib/python3.6/site-packages/tensorflow/contrib/lite/python/convert.py", line 225, in toco_convert
    input_data.SerializeToString())
  File "/home/t/development/projects/nncompression/JugendForscht2019/venv/lib/python3.6/site-packages/tensorflow/contrib/lite/python/convert.py", line 107, in toco_convert_protos
    (stdout, stderr))
RuntimeError: TOCO failed see console for info.
b'2018-08-25 12:39:18.308856: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1366] Converting unsupported operation: GatherNd
2018-08-25 12:39:18.308926: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1366] Converting unsupported operation: Round
2018-08-25 12:39:18.309390: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 57 operators, 96 arrays (0 quantized)
2018-08-25 12:39:18.309831: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 57 operators, 96 arrays (0 quantized)
2018-08-25 12:39:18.312078: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 1: 28 operators, 55 arrays (1 quantized)
2018-08-25 12:39:18.312642: W tensorflow/contrib/lite/toco/tooling_util.cc:1639] Dropping MinMax information in array model/conv1/weights_quant/FakeQuantWithMinMaxVars. Expect inaccuracy in quantized inference.
2018-08-25 12:39:18.312788: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 2: 26 operators, 51 arrays (1 quantized)
2018-08-25 12:39:18.312907: W tensorflow/contrib/lite/toco/graph_transformations/propagate_fixed_sizes.cc:1304] Skipping StridedSlice op with output "model/sparsity/strided_slice_1". ellipsis_mask is not supported (mask=1)
2018-08-25 12:39:18.313073: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 3: 25 operators, 49 arrays (1 quantized)
2018-08-25 12:39:18.313173: W tensorflow/contrib/lite/toco/graph_transformations/propagate_fixed_sizes.cc:1304] Skipping StridedSlice op with output "model/sparsity/strided_slice_1". ellipsis_mask is not supported (mask=1)
2018-08-25 12:39:18.313322: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before pre-quantization graph transformations: 25 operators, 49 arrays (1 quantized)
2018-08-25 12:39:18.313431: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] After pre-quantization graph transformations pass 1: 22 operators, 46 arrays (1 quantized)
2018-08-25 12:39:18.313573: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before quantization graph transformations: 22 operators, 46 arrays (1 quantized)
2018-08-25 12:39:18.313591: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:87] Constant array model/conv1/weights_quant/FakeQuantWithMinMaxVars lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2018-08-25 12:39:18.315866: F tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:456] Unimplemented: this graph contains an operator of type TopK_V2 for which the quantized form is not yet implemented. Sorry, and patches welcome (that\'s a relatively fun patch to write, mostly providing the actual quantized arithmetic code for this op).\n'
None
```
The main problem seems to be the missing implementation of TopK_V2. Although it is suggested as a "fun patch to write", I only have little knowledge of C/C++ and don't know the tensorflow internals. So I'm opening this issue here to show the need for a quantized implementation of TopK_V2. Maybe somebody can help with that.

I'm unsure if the other warnings are coming from this issue, too.
If you know why they show up, please tell me.

**Comment by Cibifang** [comment]
It seems that it's already supported on Aug 30

commit: https://github.com/tensorflow/tensorflow/commit/0278712da34922ec9fd5e2a4484b3b3243f7784c#diff-ef90f22f58f3bf2d3d6d3baa471f24b6

**Comment by jdduke** [comment]
The fix should be in the next TensorFlow binary release.
