### ISSUE TITLE
AttributeError: module 'tensorflow.python.keras' has no attribute 'Model'

### ISSUE THREAD

**Issue by kopecdav** [tensorflow/tensorflow#21927]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: not custom code / object_detection
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary 
- **TensorFlow version (use command below)**: 1.4.0
- **Python version**:  3.5
- **CUDA/cuDNN version**: 8.0
- **GPU model and memory**: 
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                56
On-line CPU(s) list:   0-55
Thread(s) per core:    2
Core(s) per socket:    14
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 79
Model name:            Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz
Stepping:              1
CPU MHz:               2599.695
CPU max MHz:           3500.0000
CPU min MHz:           1200.0000
BogoMIPS:              5189.84
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              35840K
NUMA node0 CPU(s):     0-13,28-41
NUMA node1 CPU(s):     14-27,42-55
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb invpcid_single intel_pt ibrs ibpb stibp kaiser tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdseed adx smap xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm arat pln pts

- **Exact command to reproduce**:
python3 object_detection/legacy/train.py --logtostderr --train_dir=object_detection/training/ --pipeline_config_path=object_detection/training/ssd_mobilenet_v1_pets.config

When i wanted to start training object detector i get this error even if tensorflow has valid installation. With the same configuration on tf 1.10. its working well. Is this a problem of version? was the "Model attribute" released after tf 1.4 version?

ERROR LOG:
Traceback (most recent call last):
  File "object_detection/legacy/train.py", line 51, in <module>
    from object_detection.builders import model_builder
  File "/home/klapajar/cone_detection/tensorflow/models/research/object_detection/builders/model_builder.py", line 20, in <module>
    from object_detection.builders import box_predictor_builder
  File "/home/klapajar/cone_detection/tensorflow/models/research/object_detection/builders/box_predictor_builder.py", line 18, in <module>
    from object_detection.predictors import convolutional_box_predictor
  File "/home/klapajar/cone_detection/tensorflow/models/research/object_detection/predictors/convolutional_box_predictor.py", line 18, in <module>
    from object_detection.core import box_predictor
  File "/home/klapajar/cone_detection/tensorflow/models/research/object_detection/core/box_predictor.py", line 137, in <module>
    class KerasBoxPredictor(tf.keras.Model):
AttributeError: module 'tensorflow.python.keras' has no attribute 'Model'

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Bazel version
Mobile device

**Comment by jagadishk89** [comment]
@kopecdav - I faced the same issue. upgrading the tensorflow version to 1.7.0 helped me. Thanks.

**Comment by tensorflowbutler** [comment]
It has been 15 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by harshini-gadige** [comment]
@kopecdav Does this issue still persist ?
@ViktorPot Hi, can you provide the tensorflow version you're using ?

**Comment by JoanneCh** [comment]
`pip install -U tensorflow`

worked for me. It updated tensorflow to v1.11

**Comment by farzadhallaji** [comment]
worked for me too.

**Comment by harshini-gadige** [comment]
Feel free to close this issue if it no longer persists. Thanks !

**Comment by tensorflowbutler** [comment]
It has been 29 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
It has been 44 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by cottrell** [comment]
It appears that was added in 4aef7dde40a3ffb1871d9a58aafec20711e7131f Nov 29 2018 which I think is more recently that 1.12 release. Probably means need 1.13 or something like this.

**Comment by pakashu** [comment]
still not resolved ,y Tensorflow version is 2.0.0a0

**Comment by oaky87** [comment]
Here the same problem, my Tensorflow version is 2.0.0a0

**Comment by VertexC** [comment]
Here the same problem, my Tensorflow version is 1.4. Any responses???

**Comment by TZVIh** [comment]
> I encountered the same problem when deploying a training on ml engine on google cloud platform. Any updates on this issue?

Hey @ViktorPot  
did you solve this problem?

**Comment by sarbanidatta12** [comment]
import tensorflow as tf
tf.keras.models.Model() solves the issue

**Comment by Jayanth1812** [comment]
ERROR:
(tensorflow) C:\tensorflow\models\research\object_detection>python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_inception_v2_pets.config
Traceback (most recent call last):
  File "train.py", line 54, in <module>
    from object_detection.builders import model_builder
  File "C:\tensorflow\models\research\object_detection\builders\model_builder.py", line 66, in <module>
    from object_detection.models import ssd_efficientnet_bifpn_feature_extractor as ssd_efficientnet_bifpn
  File "C:\tensorflow\models\research\object_detection\models\ssd_efficientnet_bifpn_feature_extractor.py", line 33, in <module>
    from official.vision.image_classification.efficientnet import efficientnet_model
  File "C:\tensorflow\models\official\vision\image_classification\efficientnet\efficientnet_model.py", line 35, in <module>
    from official.modeling import tf_utils
  File "C:\tensorflow\models\official\modeling\tf_utils.py", line 25, in <module>
    from official.modeling import activations
  File "C:\tensorflow\models\official\modeling\activations\__init__.py", line 16, in <module>
    from official.modeling.activations.gelu import gelu
  File "C:\tensorflow\models\official\modeling\activations\gelu.py", line 20, in <module>
    @tf.keras.utils.register_keras_serializable(package='Text')
AttributeError: module 'tensorflow_core.keras.utils' has no attribute 'register_keras_serializable'

(tensorflow) C:\tensorflow\models\research\object_detection>
