### ISSUE TITLE
x86/ppc64le //tensorflow/contrib/lite/delegates/eager:kernel_test and delegate_test core dump

### ISSUE THREAD

**Issue by wdirons** [tensorflow/tensorflow#21932]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: ppc64le Linux Ubuntu 16.04
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: N/A
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: master branch from 8/27 (Last commit 514f65a)
- **Python version**: both 2.7 and 3.6
- **Bazel version (if compiling from source)**: 0.15.0
- **GCC/Compiler version (if compiling from source)**: 5.4.0
- **CUDA/cuDNN version**: 9.0, 7
- **GPU model and memory**: 4 V100 GPUs with 16 GB of memory each
- **Exact command to reproduce**:
bazel test --config=cuda --test_tag_filters=-no_oss,-oss_serial,-no_gpu,-benchmark-test --test_timeout 300,450,1200,3600 --local_test_jobs=4 --test_output=errors --build_tests_only //tensorflow/tools/ci_build/gpu_build:parallel_gpu_execute //tensorflow/contrib/lite/delegates/eager:kernel_test //tensorflow/contrib/lite/delegates/eager:delegate_test 

### Describe the problem
on x86 and ppc64le when running the Tensorflow Unit Test against contrib, both contrib/lite/delegates/eager:kernel_test and delegate_test core dump. Maybe 'contrib/lite' since it was meant for mobile should be excluded from unit test for x86 and ppc64le?

```
==================== Test output for //tensorflow/contrib/lite/delegates/eager:kernel_test:
Running test /home/wdirons/tensorflow/bazel-ci_build-cache/.cache/bazel/_bazel_wdirons/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/lite/delegates/eager/kernel_test.runfiles/org_tensorflow/tensorflow/contrib/lite/delegates/eager/kernel_test  on GPU 0
[==========] Running 7 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 7 tests from KernelTest
[ RUN      ] KernelTest.FullGraph
2018-08-28 22:14:43.578155: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Found device 0 with properties:
name: Tesla V100-SXM2-16GB major: 7 minor: 0 memoryClockRate(GHz): 1.53
pciBusID: 0004:04:00.0
totalMemory: 15.75GiB freeMemory: 15.34GiB
2018-08-28 22:14:43.578223: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1485] Adding visible gpu devices: 0
2018-08-28 22:18:23.446411: I tensorflow/core/common_runtime/gpu/gpu_device.cc:966] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-08-28 22:18:23.446445: I tensorflow/core/common_runtime/gpu/gpu_device.cc:972]      0
2018-08-28 22:18:23.446454: I tensorflow/core/common_runtime/gpu/gpu_device.cc:985] 0:   N
2018-08-28 22:18:23.447047: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1098] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 14846 MB memory) -> physical GPU (device: 0, name: Tesla V100-SXM2-16GB, pci bus id: 0004:04:00.0, compute capability: 7.0)
/home/wdirons/tensorflow/bazel-ci_build-cache/.cache/bazel/_bazel_wdirons/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/lite/delegates/eager/kernel_test.runfiles/org_tensorflow/tensorflow/tools/ci_build/gpu_build/parallel_gpu_execute: line 64: 61525 Segmentation fault      (core dumped) "$TEST_BINARY" $@
================================================================================

```

### Source code / logs
gdb where ran on the core dump for kernel_test on ppc64le

```
(gdb) where
#0  __memcpy_power7 () at ../sysdeps/powerpc/powerpc64/power7/memcpy.S:277
#1  0x00000001118dd344 in void tflite::eager::(anonymous namespace)::KernelTest::ConfigureDelegate<tflite::eager::(anonymous namespace)::KernelTest_FullGraph_Test::TestBody()::{lambda(                       TfLiteContext*, _TfLiteDelegate*)#1}>(tflite::eager::(anonymous namespace)::KernelTest_FullGraph_Test::TestBody()::{lambda(TfLiteContext*, _TfLiteDelegate*)#1})::{lambda(TfLiteContext*                       , _TfLiteDelegate*, int, void*, unsigned long)#1}::_FUN ()
#2  0x00007fffa4afd9d0 in tflite::Interpreter::Invoke() ()
   from /home/wdirons/tensorflow/bazel-ci_build-cache/.cache/bazel/_bazel_wdirons/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/lite                       /delegates/eager/../../../../../_solib_local/libtensorflow_Scontrib_Slite_Slibframework.so
#3  0x00007fffa6773b14 in tflite::eager::testing::EagerModelTest::Invoke() ()
   from /home/wdirons/tensorflow/bazel-ci_build-cache/.cache/bazel/_bazel_wdirons/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/lite                       /delegates/eager/../../../../../_solib_local/libtensorflow_Scontrib_Slite_Sdelegates_Seager_Slibtest_Uutil.so
#4  0x00000001118e8444 in tflite::eager::(anonymous namespace)::KernelTest_FullGraph_Test::TestBody() ()
#5  0x00007fffa47f272c in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) ()
   from /home/wdirons/tensorflow/bazel-ci_build-cache/.cache/bazel/_bazel_wdirons/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/lite                       /delegates/eager/../../../../../_solib_local/libexternal_Scom_Ugoogle_Ugoogletest_Slibgtest.so
#6  0x00007fffa47f2ab4 in testing::Test::Run() ()
   from /home/wdirons/tensorflow/bazel-ci_build-cache/.cache/bazel/_bazel_wdirons/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/lite                       /delegates/eager/../../../../../_solib_local/libexternal_Scom_Ugoogle_Ugoogletest_Slibgtest.so
#7  0x00007fffa47f2f98 in testing::TestInfo::Run() ()
   from /home/wdirons/tensorflow/bazel-ci_build-cache/.cache/bazel/_bazel_wdirons/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/lite                       /delegates/eager/../../../../../_solib_local/libexternal_Scom_Ugoogle_Ugoogletest_Slibgtest.so
#8  0x00007fffa47f33a4 in testing::TestCase::Run() ()
   from /home/wdirons/tensorflow/bazel-ci_build-cache/.cache/bazel/_bazel_wdirons/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/lite                       /delegates/eager/../../../../../_solib_local/libexternal_Scom_Ugoogle_Ugoogletest_Slibgtest.so
#9  0x00007fffa47f387c in testing::internal::UnitTestImpl::RunAllTests() ()
   from /home/wdirons/tensorflow/bazel-ci_build-cache/.cache/bazel/_bazel_wdirons/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/lite                       /delegates/eager/../../../../../_solib_local/libexternal_Scom_Ugoogle_Ugoogletest_Slibgtest.so
#10 0x00007fffa47f3c5c in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::                       UnitTestImpl::*)(), char const*) ()
   from /home/wdirons/tensorflow/bazel-ci_build-cache/.cache/bazel/_bazel_wdirons/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/lite                       /delegates/eager/../../../../../_solib_local/libexternal_Scom_Ugoogle_Ugoogletest_Slibgtest.so
#11 0x00007fffa47f3f60 in testing::UnitTest::Run() ()
   from /home/wdirons/tensorflow/bazel-ci_build-cache/.cache/bazel/_bazel_wdirons/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/lite                       /delegates/eager/../../../../../_solib_local/libexternal_Scom_Ugoogle_Ugoogletest_Slibgtest.so
#12 0x00000001117950fc in main ()
(gdb)
```

gdb where ran on the core dump for delegate_test on ppc64le

```
(gdb) where
#0  __memcpy_power7 () at ../sysdeps/powerpc/powerpc64/power7/memcpy.S:277
#1  0x00007fffaabc2b24 in tflite::eager::delegate::CopyFromBufferHandle(TfLiteContext*, _TfLiteDelegate*, int, void*, unsigned long) ()
   from /home/wdirons/tensorflow/bazel-ci_build-cache/.cache/bazel/_bazel_wdirons/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/lite/delegates/eager/../../../../../_solib_local/libtensorflow_Scontrib_Slite_Sdelegates_Seager_Slibdelegate.so
#2  0x00007fff9716d9d0 in tflite::Interpreter::Invoke() ()
   from /home/wdirons/tensorflow/bazel-ci_build-cache/.cache/bazel/_bazel_wdirons/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/lite/delegates/eager/../../../../../_solib_local/libtensorflow_Scontrib_Slite_Slibframework.so
#3  0x00007fff98ec3b14 in tflite::eager::testing::EagerModelTest::Invoke() ()
   from /home/wdirons/tensorflow/bazel-ci_build-cache/.cache/bazel/_bazel_wdirons/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/lite/delegates/eager/../../../../../_solib_local/libtensorflow_Scontrib_Slite_Sdelegates_Seager_Slibtest_Uutil.so
#4  0x0000000105bf182c in tflite::eager::(anonymous namespace)::DelegateTest_FullGraph_Test::TestBody() ()
#5  0x00007fff96f4272c in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) ()
   from /home/wdirons/tensorflow/bazel-ci_build-cache/.cache/bazel/_bazel_wdirons/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/lite/delegates/eager/../../../../../_solib_local/libexternal_Scom_Ugoogle_Ugoogletest_Slibgtest.so
#6  0x00007fff96f42ab4 in testing::Test::Run() ()
   from /home/wdirons/tensorflow/bazel-ci_build-cache/.cache/bazel/_bazel_wdirons/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/lite/delegates/eager/../../../../../_solib_local/libexternal_Scom_Ugoogle_Ugoogletest_Slibgtest.so
#7  0x00007fff96f42f98 in testing::TestInfo::Run() ()
   from /home/wdirons/tensorflow/bazel-ci_build-cache/.cache/bazel/_bazel_wdirons/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/lite/delegates/eager/../../../../../_solib_local/libexternal_Scom_Ugoogle_Ugoogletest_Slibgtest.so
#8  0x00007fff96f433a4 in testing::TestCase::Run() ()
   from /home/wdirons/tensorflow/bazel-ci_build-cache/.cache/bazel/_bazel_wdirons/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/lite/delegates/eager/../../../../../_solib_local/libexternal_Scom_Ugoogle_Ugoogletest_Slibgtest.so
#9  0x00007fff96f4387c in testing::internal::UnitTestImpl::RunAllTests() ()
   from /home/wdirons/tensorflow/bazel-ci_build-cache/.cache/bazel/_bazel_wdirons/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/lite/delegates/eager/../../../../../_solib_local/libexternal_Scom_Ugoogle_Ugoogletest_Slibgtest.so
#10 0x00007fff96f43c5c in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) ()
   from /home/wdirons/tensorflow/bazel-ci_build-cache/.cache/bazel/_bazel_wdirons/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/lite/delegates/eager/../../../../../_solib_local/libexternal_Scom_Ugoogle_Ugoogletest_Slibgtest.so
#11 0x00007fff96f43f60 in testing::UnitTest::Run() ()
   from /home/wdirons/tensorflow/bazel-ci_build-cache/.cache/bazel/_bazel_wdirons/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/contrib/lite/delegates/eager/../../../../../_solib_local/libexternal_Scom_Ugoogle_Ugoogletest_Slibgtest.so
#12 0x0000000105aa3f7c in main ()
```

On my x86 container I was unable to determine the location of the core that was generated.

**Comment by jdduke** [comment]
In theory these tests should succeed on desktop platforms. We'll take a look.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @jdduke: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @jdduke: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.
