### ISSUE TITLE
import tensorflow.contrib fails on arm32

### ISSUE THREAD

**Issue by hododoy** [tensorflow/tensorflow#21935]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No. running "tensorflow/examples/learn/resnet.py"
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: custom embedded linux
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: Yes, rpi class device
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 1.10.1 / 4dcfddc5d12018a5a0fdca652b9221ed95e9eb23
- **Python version**: 2.7.15
- **Bazel version (if compiling from source)**:  0.16.0
- **GCC/Compiler version (if compiling from source)**: gcc 6.3
- **CUDA/cuDNN version**: None
- **GPU model and memory**: None
- **Exact command to reproduce**: "import tensorflow.contrib"

### Describe the problem
I am cross-compiling tensorflow to work on a 32-bit armhf system. My build system is x86-64. sample apps seem to work ok. but I am having difficulty in the python environment. "import tensorflow" works ok. But "import tensorflow.contrib" fails with this error:

```
>>> import tensorflow.contrib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/nfs/baseline/obj.32/target/usr/local/lib/python2.7/site-packages/tensorflow/contrib/__init__.py", line 69, in <module>
    from tensorflow.contrib import periodic_resample
  File "/mnt/nfs/baseline/obj.32/target/usr/local/lib/python2.7/site-packages/tensorflow/contrib/periodic_resample/__init__.py", line 22, in <module>
    from tensorflow.contrib.periodic_resample.python.ops.periodic_resample_op import periodic_resample
  File "/mnt/nfs/baseline/obj.32/target/usr/local/lib/python2.7/site-packages/tensorflow/contrib/periodic_resample/python/ops/periodic_resample_op.py", line 32, in <module>
    resource_loader.get_path_to_datafile('_periodic_resample_op.so'))
  File "/mnt/nfs/baseline/obj.32/target/usr/local/lib/python2.7/site-packages/tensorflow/contrib/util/loader.py", line 56, in load_op_library
    ret = load_library.load_op_library(path)
  File "/mnt/nfs/baseline/obj.32/target/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/load_library.py", line 73, in load_op_library
    exec(wrappers, module.__dict__)
  File "<string>", line 293, in <module>
  File "<string>", line 229, in _InitOpDefLibrary
  File "/mnt/nfs/baseline/obj.32/target/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_registry.py", line 35, in register_op_list
    assert _registered_ops[op_def.name] == op_def
AssertionError
```

I have tried combinations of bazel 0.12/0.16, tensorflow 1.8/1.10 and python 2.7.10/2.7.15. I get the same result every time. Issue seems to be related to only PeriodicResample & PeriodicResampleOpGrad. Other modules do not assert.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @cy89: It has been 17 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @cy89: It has been 32 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @cy89: It has been 47 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @cy89: It has been 62 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @cy89: It has been 77 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @cy89: It has been 92 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by mohantym** [comment]
Hi @hododoy ! 
It seems you are using older versions(1.x versions) of Tensorflow which is not supported any more. Have you referred this [document ](https://www.tensorflow.org/lite/guide/build_arm)from TF 2.7 version yet? Thanks!
