### ISSUE TITLE
Variable in a while loop - Segmentation fault (core dumped) 

### ISSUE THREAD

**Issue by mpekalski** [tensorflow/tensorflow#21980]
I use TF 1.10.0, build from master last week.

I am trying to make a function to erase patches in images and wanted to apply it with map to a Dataset. I use scatter_nd_update, so I had to define a variable that would be updated outside of the loop and assign tensor to it within the loop, but then I get segmentation fault.

Log and the code

```
Using TensorFlow backend.
2018-08-30 21:36:51.556778: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:964] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-08-30 21:36:51.557216: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.721
pciBusID: 0000:01:00.0
totalMemory: 10.92GiB freeMemory: 10.03GiB
2018-08-30 21:36:51.557236: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1485] Adding visible gpu devices: 0
2018-08-30 21:36:51.755752: I tensorflow/core/common_runtime/gpu/gpu_device.cc:966] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-08-30 21:36:51.755792: I tensorflow/core/common_runtime/gpu/gpu_device.cc:972]      0 
2018-08-30 21:36:51.755799: I tensorflow/core/common_runtime/gpu/gpu_device.cc:985] 0:   N 
2018-08-30 21:36:51.755996: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1098] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 9692 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
2018-08-30 21:36:51.840570: I tensorflow/core/common_runtime/process_util.cc:69] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
Using device /gpu:0, and data format channels_last.
Starting
Tensor("learning_rate_decay:0", shape=(), dtype=float32)
WARNING:tensorflow:case: An unordered dictionary of predicate/fn pairs was provided, but exclusive=False. The order of conditional tests is deterministic but not guaranteed.
(300, 28, 28, 1)
2018-08-30 21:36:52.518523: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1485] Adding visible gpu devices: 0
2018-08-30 21:36:52.518567: I tensorflow/core/common_runtime/gpu/gpu_device.cc:966] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-08-30 21:36:52.518576: I tensorflow/core/common_runtime/gpu/gpu_device.cc:972]      0 
2018-08-30 21:36:52.518584: I tensorflow/core/common_runtime/gpu/gpu_device.cc:985] 0:   N 
2018-08-30 21:36:52.518686: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1098] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 9692 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
2018-08-30 21:36:52.518876: I tensorflow/core/common_runtime/process_util.cc:69] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
Segmentation fault (core dumped)
```

```
def random_erase(img_z, img, label, width=28, height=28):
        #with g.as_default():
        a = tf.random_uniform(minval=0,   maxval=width-1, shape=[], dtype=tf.int32)
        b = tf.random_uniform(minval=a+1, maxval=width,   shape=[], dtype=tf.int32)

        c = tf.random_uniform(minval=0,   maxval=height-1, shape=[], dtype=tf.int32)
        d = tf.random_uniform(minval=c+1, maxval=height,   shape=[], dtype=tf.int32)

        h = tf.range(start=a, limit=b, dtype=tf.int32)
        v = tf.range(start=c, limit=d, dtype=tf.int32)

        h, v = h[ None, :, None ], v[ :, None, None ]
        cartesian_product = tf.concat( [ h + tf.zeros_like( v ),
                                        tf.zeros_like( h ) + v ], axis = 2, name="caretsian_product")
        
        random_patch = tf.random_uniform(minval=0, maxval=255, shape=[d-c,b-a], dtype=tf.float32, name="random_patch")
        return tf.scatter_nd_update(tf.assign(img_z, img), cartesian_product, random_patch, name="image_with_patch"), label

```

and I use it in

```
    img_z = tf.Variable(tf.zeros(shape=[28*28], dtype=tf.float32),
                            trainable=False, use_resource=True)
    ds = mnist_train('.')
    ds = ds.map(lambda img, label:random_erase(img_z, img, label))
```

**Comment by mpekalski** [comment]
I tried approach described in https://github.com/tensorflow/tensorflow/issues/12648 but it did not help. Still getting segmentation fault. If I do not pass variable to random_erase explicitly TF complaints that it is not defined, if I do I get segmentation fault.

**Comment by mpekalski** [comment]
Applying #12648 got rid of the segmentation fault but left me with another issue. 
```
ValueError: Tensor("dataset/img/temp:0", shape=(784,), dtype=float32_ref) must be from the same graph as Tensor("cond_1/loss_fn:0", shape=(), dtype=float32).
```
The problem is that I do not define any graph anywhere, so it should use the default one (as far as I know). I wanted to get rid of a problem with float_ref returned by `tf.scatter_nd_update` by assigning it to a Variable that would be returned by a function, but somehow it causes the scoping issue.

The new code
```
    with tf.variable_scope("dataset/img", reuse=tf.AUTO_REUSE):
        temp = tf.get_variable(
            "temp",
            initializer=tf.zeros(shape=[28*28], dtype=tf.float32),
            trainable=False,
            use_resource=True)       
        temp2 = tf.get_variable(
            "temp2",
            initializer=tf.zeros(shape=[28*28], dtype=tf.float32),
            trainable=False,
            use_resource=True)
    def random_erase(img, label, width=28, height=28):
        a = tf.random_uniform(minval=0,   maxval=width-1, shape=[], dtype=tf.int32)
        b = tf.random_uniform(minval=a+1, maxval=width,   shape=[], dtype=tf.int32)

        c = tf.random_uniform(minval=0,   maxval=height-1, shape=[], dtype=tf.int32)
        d = tf.random_uniform(minval=c+1, maxval=height,   shape=[], dtype=tf.int32)

        h = tf.range(start=a, limit=b, dtype=tf.int32)
        v = tf.range(start=c, limit=d, dtype=tf.int32)

        h, v = h[ None, :, None ], v[ :, None, None ]
        cartesian_product = tf.concat( [ h + tf.zeros_like( v ),
                                        tf.zeros_like( h ) + v ], axis = 2, name="caretsian_product")

        with tf.variable_scope("img",  reuse=tf.AUTO_REUSE):
            temp = tf.get_variable("temp",initializer=tf.zeros(shape=[28*28], dtype=tf.float32), dtype=tf.float32) 
            temp2 = tf.get_variable("temp2",initializer=tf.zeros(shape=[28*28], dtype=tf.float32), dtype=tf.float32) 
        random_patch = tf.random_uniform(minval=0, maxval=255, shape=[d-c,b-a], dtype=tf.float32, name="random_patch")
        with tf.control_dependencies([temp.assign(img)]):
            with tf.control_dependencies([temp2.assign(tf.scatter_nd_update(temp, cartesian_product, random_patch, name="image_with_patch"))]):
                return temp2, label

    ds = mnist_train('.')
    ds = ds.map(lambda img, label:random_erase(img, label))
    ds = ds.shuffle(buffer_size=60000)
```

**Comment by mpekalski** [comment]
Now there are two things:

1) Printed scope is different, even though I am reusing it, but the variable is read with `tf.get_variable()` . If I change the second scope, I do not get ReadVariableOp as variable name. From the log:
```
Starting
SCOPE 1 =============
dataset/img
dataset/img/temp:0
dataset/img/temp2:0
SCOPE 2 =============
img
dataset/ReadVariableOp:0
dataset/ReadVariableOp_1:0
```
2) Why it complains that `AttributeError: 'Tensor' object has no attribute 'assign'` in line
```with tf.control_dependencies([temp.assign(img)]):```
I am using `temp = tf.get_variable(...)`, so it should return variable not tensor.


```
def ds_train(batch_size, num_epochs, data_dir='.', data_format='channels_last'):
    print("SCOPE 1 =============")
    with tf.variable_scope("img", reuse=tf.AUTO_REUSE):
        temp = tf.get_variable(
            "temp",
            initializer=tf.zeros(shape=[28*28], dtype=tf.float32),
            trainable=False,
            use_resource=True)       
        temp2 = tf.get_variable(
            "temp2",
            initializer=tf.zeros(shape=[28*28], dtype=tf.float32),
            trainable=False,
            use_resource=True)       
        print(tf.get_variable_scope().name)
        print(temp.name)
        print(temp2.name)
    print("SCOPE 2 =============")
    def random_erase(img, label, width=28, height=28):
        a = tf.random_uniform(minval=0,   maxval=width-1, shape=[], dtype=tf.int32)
        b = tf.random_uniform(minval=a+1, maxval=width,   shape=[], dtype=tf.int32)

        c = tf.random_uniform(minval=0,   maxval=height-1, shape=[], dtype=tf.int32)
        d = tf.random_uniform(minval=c+1, maxval=height,   shape=[], dtype=tf.int32)

        h = tf.range(start=a, limit=b, dtype=tf.int32)
        v = tf.range(start=c, limit=d, dtype=tf.int32)

        h, v = h[ None, :, None ], v[ :, None, None ]
        cartesian_product = tf.concat( [ h + tf.zeros_like( v ),
                                        tf.zeros_like( h ) + v ], axis = 2, name="caretsian_product")
        
        with tf.variable_scope("img", reuse=tf.AUTO_REUSE):
            temp = tf.get_variable("temp",initializer=tf.zeros(shape=[28*28], dtype=tf.float32), dtype=tf.float32) 
            temp2 = tf.get_variable("temp2",initializer=tf.zeros(shape=[28*28], dtype=tf.float32), dtype=tf.float32) 
            print(tf.get_variable_scope().name)
            print(temp.name)
            print(temp2.name)
            random_patch = tf.random_uniform(minval=0, maxval=255, shape=[d-c,b-a], dtype=tf.float32, name="random_patch")
            with tf.control_dependencies([temp.assign(img)]):
                assign_op = tf.assign(temp2, tf.scatter_nd_update(temp, cartesian_product, random_patch, name="image_with_patch"))
                with tf.control_dependencies([assign_op]):
                    return temp2, label

    ds = mnist_train('.')
    ds = ds.map(lambda img, label:random_erase(img, label))
    ds = ds.shuffle(buffer_size=60000)
    ds = ds.batch(batch_size, drop_remainder=True)
    ds = ds.repeat(num_epochs)
    ds = ds.prefetch(tf.contrib.data.AUTOTUNE)
    return ds

with tf.variable_scope("dataset"):       
     ds_t = ds_train(batch_size, num_epochs)

```


log
```
root@3bed2f328777:/home/marcgrab/kaggle/zalando/zalando/dataset_api_test# python3 model_resampling.py 
Using TensorFlow backend.
2018-08-31 22:30:56.899358: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:964] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-08-31 22:30:56.899820: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.721
pciBusID: 0000:01:00.0
totalMemory: 10.92GiB freeMemory: 10.02GiB
2018-08-31 22:30:56.899907: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1485] Adding visible gpu devices: 0
2018-08-31 22:30:57.098776: I tensorflow/core/common_runtime/gpu/gpu_device.cc:966] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-08-31 22:30:57.098815: I tensorflow/core/common_runtime/gpu/gpu_device.cc:972]      0 
2018-08-31 22:30:57.098821: I tensorflow/core/common_runtime/gpu/gpu_device.cc:985] 0:   N 
2018-08-31 22:30:57.099020: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1098] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 9683 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
2018-08-31 22:30:57.185881: I tensorflow/core/common_runtime/process_util.cc:69] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
Using device /gpu:0, and data format channels_last.
Starting
SCOPE 1 =============
dataset/img
dataset/img/temp:0
dataset/img/temp2:0
SCOPE 2 =============
img
dataset/ReadVariableOp:0
dataset/ReadVariableOp_1:0
Traceback (most recent call last):
  File "model_resampling.py", line 852, in <module>
    loss, accuracy = run_a_graph(data_format=data_format)
  File "model_resampling.py", line 583, in run_a_graph
    ds_t = ds_train(batch_size, num_epochs)
  File "model_resampling.py", line 364, in ds_train
    ds = ds.map(lambda img, label:random_erase(img, label))
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1005, in map
    return MapDataset(self, map_func)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 2216, in __init__
    map_func, "Dataset.map()", input_dataset)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1473, in __init__
    self._function.add_to_graph(ops.get_default_graph())
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/function.py", line 479, in add_to_graph
    self._create_definition_if_needed()
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/function.py", line 335, in _create_definition_if_needed
    self._create_definition_if_needed_impl()
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/function.py", line 344, in _create_definition_if_needed_impl
    self._capture_by_value, self._caller_device)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/function.py", line 865, in func_graph_from_py_func
    outputs = func(*func_graph.inputs)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1411, in tf_data_structured_function_wrapper
    ret = func(*nested_args)
  File "model_resampling.py", line 364, in <lambda>
    ds = ds.map(lambda img, label:random_erase(img, label))
  File "model_resampling.py", line 358, in random_erase
    with tf.control_dependencies([temp.assign(img)]):
AttributeError: 'Tensor' object has no attribute 'assign'
```

**Comment by mpekalski** [comment]
I will post a workaround or what was the issue when I find it, as for now I will close the ticket as I think the problem is with my code not TF itself.
