### ISSUE TITLE
tf.get_variable returns Tensor instead of Variable

### ISSUE THREAD

**Issue by mpekalski** [tensorflow/tensorflow#22009]
-----------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 16.04
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
- **TensorFlow installed from (source or binary)**:
source
- **TensorFlow version (use command below)**:

TF checkpoint I have built
```
/tmp/tensorflow# git log   
commit 09792df012c22622324f085f46edde33006c7355
Author: A. Unique TensorFlower <gardener@tensorflow.org>
Date:   Sun Aug 26 02:07:11 2018 -0700

    compat: Update forward compatibility horizon to 2018-08-26
    
    PiperOrigin-RevId: 210266798
```

```
== cat /etc/issue ===============================================
Linux 3bed2f328777 4.13.0-38-generic #43~16.04.1-Ubuntu SMP Wed Mar 14 17:48:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
VERSION="16.04.5 LTS (Xenial Xerus)"
VERSION_ID="16.04"
VERSION_CODENAME=xenial

== are we in docker =============================================
Yes

== compiler =====================================================
c++ (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


== uname -a =====================================================
Linux 3bed2f328777 4.13.0-38-generic #43~16.04.1-Ubuntu SMP Wed Mar 14 17:48:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

== check pips ===================================================
numpy (1.14.5)
protobuf (3.6.1)
tensorflow (1.10.0)

== check for virtualenv =========================================
False

== tensorflow import ============================================
tf.VERSION = 1.10.0
tf.GIT_VERSION = b'unknown'
tf.COMPILER_VERSION = b'unknown'
Sanity check: array([1], dtype=int32)

== env ==========================================================
LD_LIBRARY_PATH /usr/local/cuda/lib64/stubs:/usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/lib64/stubs:/usr/local/cuda/lib64/stubs:/usr/local/cuda/extras/CUPTI/lib64:/lib/amd64/server/:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server:/opt/boost/lib:/opt/conda/lib/:/usr/local/cuda/lib64/:/opt/conda/lib/R/lib/:/usr/local/nvidia/lib64/:/usr/local/nvidia/lib:/lib/x86_64-linux-gnu:/usr/local/cuda/extras/CUPTI/lib64:/usr/lib/x86_64-linux-gnu:/opt/opencv/lib
DYLD_LIBRARY_PATH is unset

== nvidia-smi ===================================================
Wed Aug 29 19:57:14 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 396.26                 Driver Version: 396.26                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:01:00.0  On |                  N/A |
|  0%   41C    P0    76W / 250W |    708MiB / 11177MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+

== cuda libs  ===================================================
/usr/local/cuda-9.2/targets/x86_64-linux/lib/libcudart.so.9.2.148
/usr/local/cuda-9.2/targets/x86_64-linux/lib/libcudart_static.a

```
**Bazel** version
```
$ bazel version
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
Build label: 0.16.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Jul 31 17:01:24 2018 (1533056484)
Build timestamp: 1533056484
Build timestamp as int: 1533056484
```

**CUDNN** version:
```
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Tue_Jun_12_23:07:04_CDT_2018
Cuda compilation tools, release 9.2, V9.2.148
```

**GPU**: GEFORCE GTX 1080Ti, 11GB, GIGABYTE AORUS

- **Exact command to reproduce**:
```
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import tensorflow as tf

def scope_1():
    print("DS1 SCOPE =============")
    with tf.variable_scope("scope_1", reuse=tf.AUTO_REUSE):
        x = tf.get_variable("x", initializer=0.0, dtype=tf.float32
                               , trainable=False, use_resource=True)             
        print("graph: {}".format(x.graph))
        print("scope: {}".format(tf.get_variable_scope().name))
        print(" name: {}".format(x.name))
        print("  var: {}".format(str(x)))
        current_scope = tf.get_variable_scope()       
        assign_one = tf.assign(x, 1, name="x_is_one")
    
    def scope_2(inputs, label):        
        print("initial scope: {}".format(tf.get_variable_scope().name))
        print("DS1 SCOPE =============")
        with tf.variable_scope("scope_1", reuse=tf.AUTO_REUSE):
        #with tf.variable_scope(current_scope, reuse=tf.AUTO_REUSE):
            y = tf.get_variable("x", initializer=0.0, dtype=tf.float32
                                   , trainable=False, use_resource=True)         
            print("graph: {}".format(y.graph))
            print("scope: {}".format(tf.get_variable_scope().name))
            print(" name: {}".format(y.name))
            print("  var: {}".format(str(y)))
            print("=============")
            
            assign_two = tf.assign(y, inputs+1, name="inputs_plus_1")
            with tf.control_dependencies([assign_two]):
                return y, label
            #return x,label
    
    # test that original x is mutable
    with tf.control_dependencies([assign_one]):
        dataset = (tf.data.Dataset.from_tensor_slices(([1,2,3,4,5], [0,0,0,0,0]))
                    .map(scope_2)
                    .batch(2)
                    .repeat(10)        
                    )
    
                
with tf.variable_scope("scope_0"):
        dataset_fn = scope_1

with tf.Session() as sess:
    dataset_fn()
    sess.run([tf.global_variables_initializer(),tf.local_variables_initializer()])
    print(sess.graph.get_operations())    
    print()
    print("global vars: {}".format(tf.global_variables()))
    print("local vars: {}".format(tf.local_variables()))
    print(tf.get_default_graph().get_name_scope())

```

### Describe the problem
I am trying to create a function that would modify a Tensor within a pipeline of Dataset API.
The scoping may seem weird, but that is minimal example that shows the problem that I created from my project.but somehow it is using `ReadVariableOp` that only 

Looks like when I fetch a variable using `tf.get_variable` (within def scope_2) it returns immutable Tensor, whereas the original Variable is mutable. In `scope_1` I am able to run `x.assign(0)` but then within `scope_2` (that is invoked in dataset.map) it throws an `AttributeError: 'Tensor' object has no attribute 'assign'`

According to the docs https://www.tensorflow.org/api_docs/python/tf/get_variable `tf.get_variable` should return a Variable not a Tensor.
```
Returns:
The created or existing Variable (or PartitionedVariable, if a partitioner was used).
```

### Source code / logs

```
2018-09-01 23:26:58.452631: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:964] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-09-01 23:26:58.453216: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.721
pciBusID: 0000:01:00.0
totalMemory: 10.92GiB freeMemory: 9.98GiB
2018-09-01 23:26:58.453237: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1485] Adding visible gpu devices: 0
2018-09-01 23:26:58.653750: I tensorflow/core/common_runtime/gpu/gpu_device.cc:966] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-09-01 23:26:58.653789: I tensorflow/core/common_runtime/gpu/gpu_device.cc:972]      0 
2018-09-01 23:26:58.653796: I tensorflow/core/common_runtime/gpu/gpu_device.cc:985] 0:   N 
2018-09-01 23:26:58.654003: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1098] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 9644 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
2018-09-01 23:26:58.758539: I tensorflow/core/common_runtime/process_util.cc:69] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
DS1 SCOPE =============
graph: <tensorflow.python.framework.ops.Graph object at 0x7f1ebf351400>
scope: scope_1
 name: scope_1/x:0
  var: <tf.Variable 'scope_1/x:0' shape=() dtype=float32>
initial scope: 
DS1 SCOPE =============
graph: <tensorflow.python.framework.ops.Graph object at 0x7f1ebf351400>
scope: scope_1
 name: ReadVariableOp:0
  var: Tensor("ReadVariableOp:0", shape=(), dtype=float32)
=============
Traceback (most recent call last):
  File "bug.py", line 50, in <module>
    dataset_fn()
  File "bug.py", line 40, in scope_1
    .map(scope_2)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1005, in map
    return MapDataset(self, map_func)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 2216, in __init__
    map_func, "Dataset.map()", input_dataset)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1473, in __init__
    self._function.add_to_graph(ops.get_default_graph())
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/function.py", line 479, in add_to_graph
    self._create_definition_if_needed()
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/function.py", line 335, in _create_definition_if_needed
    self._create_definition_if_needed_impl()
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/function.py", line 344, in _create_definition_if_needed_impl
    self._capture_by_value, self._caller_device)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/function.py", line 865, in func_graph_from_py_func
    outputs = func(*func_graph.inputs)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1411, in tf_data_structured_function_wrapper
    ret = func(*nested_args)
  File "bug.py", line 32, in scope_2
    assign_two = tf.assign(y, inputs+1, name="inputs_plus_1")
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/ops/state_ops.py", line 222, in assign
    return ref.assign(value, name=name)
AttributeError: 'Tensor' object has no attribute 'assign'

```

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Bazel version
CUDA/cuDNN version
GPU model and memory

**Comment by mpekalski** [comment]
I've updated the description with Bazel Version, CUDA/CuDNN version, and GPU model.

**Comment by mpekalski** [comment]
I got it working with the piece of code I have commented out in the original issue. I do not know why it did not work for me before. Either way, the solution was to use the same scope again but with reference to it by variable not name, so use `current_scope` not `"scope_1"`.

I find it strange that although I use `tf.get_variable` a new variable is created with the same name as original but followed by `_1`. 

```
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import tensorflow as tf

def scope_1():
    print("DS1 SCOPE =============")
    with tf.variable_scope("scope_1", reuse=tf.AUTO_REUSE):
        x = tf.get_variable("x", initializer=0.0, dtype=tf.float32
                               , trainable=False, use_resource=True)             
        print("graph: {}".format(x.graph))
        print("scope: {}".format(tf.get_variable_scope().name))
        print(" name: {}".format(x.name))
        print("  var: {}".format(str(x)))
        current_scope = tf.get_variable_scope()       
        assign_one = tf.assign(x, 1.0, name="x_is_one")
    
    def scope_2(inputs, label):        
        print("initial scope: {}".format(tf.get_variable_scope().name))
        print("DS1 SCOPE =============")
        #with tf.variable_scope("scope_1", reuse=tf.AUTO_REUSE):
        with tf.variable_scope(current_scope, reuse=tf.AUTO_REUSE):
            y = tf.get_variable("x", initializer=0.0, dtype=tf.float32
                                   , trainable=False, use_resource=True)         
            print("graph: {}".format(y.graph))
            print("scope: {}".format(tf.get_variable_scope().name))
            print(" name: {}".format(y.name))
            print("  var: {}".format(str(y)))
            print("=============")
            
            #assign_two = tf.assign(y, tf.add(tf.cast(inputs, dtype=tf.float32),1.0), name="inputs_plus_1")
            assign_two = tf.identity(tf.assign(y, tf.add(tf.cast(inputs, dtype=tf.float32), 1.0)))
            with tf.control_dependencies([assign_two]):
                return y.read_value(), label
            #return x,label
    
    # test that original x is mutable
    with tf.control_dependencies([assign_one]):
        dataset = (tf.data.Dataset.from_tensor_slices(([1,2,3,4,5], [-1,-2,-3,-4,-5]))
                    .map(scope_2)
                    .batch(1)
                    .repeat(1)        
                    )
    return dataset
    
                
with tf.variable_scope("scope_0"):
        dataset_fn = scope_1()

with tf.variable_scope("iterator"):
    # Define iterator from_string_handle. In general it is useful to have
    # this kind of iterator if one wants to switch between train and validation
    # within the training loop.        
    iterator_t = dataset_fn.make_initializable_iterator()
    iterator_handle = tf.placeholder(tf.string, shape=[], name="iterator_handle")
    iterator = tf.data.Iterator.from_string_handle(iterator_handle, 
                                                iterator_t.output_types,
                                                iterator_t.output_shapes)
    
    def get_next_item():
        next_elem = iterator.get_next(name="next_element")
        x, y = tf.cast(next_elem[0], tf.float32), next_elem[1]# tf.cast(next_elem[1], tf.int32)
        return x, y    
with tf.Session() as sess:
    handle_t = sess.run(iterator_t.string_handle())
    # Run data iterator initialisation
    sess.run(iterator_t.initializer)
    sess.run([tf.global_variables_initializer(),tf.local_variables_initializer()])
    print(sess.graph.get_operations()) 
    while True:
        try:
            print(sess.run(get_next_item(), feed_dict={iterator_handle:handle_t}))
        except tf.errors.OutOfRangeError:
                        print("End of training dataset.")
                        break        
    print()
    print("global vars: {}".format(tf.global_variables()))
    print("local vars: {}".format(tf.local_variables()))
    print(tf.get_default_graph().get_name_scope())
```
LOG
```
DS1 SCOPE =============
graph: <tensorflow.python.framework.ops.Graph object at 0x7f56a3a98470>
scope: scope_0/scope_1
 name: scope_0/scope_1/x:0
  var: <tf.Variable 'scope_0/scope_1/x:0' shape=() dtype=float32>
initial scope: 
DS1 SCOPE =============
graph: <tensorflow.python.framework.ops.Graph object at 0x7f56a3a98470>
scope: scope_0/scope_1
 name: scope_0/scope_1/x_1:0
  var: <tf.Variable 'scope_0/scope_1/x_1:0' shape=() dtype=float32>
=============
2018-09-02 19:37:43.456845: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:964] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-09-02 19:37:43.457271: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.721
pciBusID: 0000:01:00.0
totalMemory: 10.92GiB freeMemory: 10.29GiB
2018-09-02 19:37:43.457291: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1485] Adding visible gpu devices: 0
2018-09-02 19:37:43.662214: I tensorflow/core/common_runtime/gpu/gpu_device.cc:966] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-09-02 19:37:43.662252: I tensorflow/core/common_runtime/gpu/gpu_device.cc:972]      0 
2018-09-02 19:37:43.662260: I tensorflow/core/common_runtime/gpu/gpu_device.cc:985] 0:   N 
2018-09-02 19:37:43.662470: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1098] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 9951 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
2018-09-02 19:37:43.759025: I tensorflow/core/common_runtime/process_util.cc:69] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
[<tf.Operation 'Const' type=Const>, <tf.Operation 'scope_0/scope_1/x/Initializer/initial_value' type=Const>, <tf.Operation 'scope_0/scope_1/x' type=VarHandleOp>, <tf.Operation 'scope_0/scope_1/x/IsInitialized/VarIsInitializedOp' type=VarIsInitializedOp>, <tf.Operation 'scope_0/scope_1/x/Assign' type=AssignVariableOp>, <tf.Operation 'scope_0/scope_1/x/Read/ReadVariableOp' type=ReadVariableOp>, <tf.Operation 'scope_0/scope_1/Const' type=Const>, <tf.Operation 'scope_0/scope_1/x_is_one' type=AssignVariableOp>, <tf.Operation 'scope_0/scope_1/ReadVariableOp' type=ReadVariableOp>, <tf.Operation 'scope_0/tensors/component_0' type=Const>, <tf.Operation 'scope_0/tensors/component_1' type=Const>, <tf.Operation 'scope_0/scope_1/x_1/Initializer/initial_value' type=Const>, <tf.Operation 'scope_0/scope_1/x_1' type=VarHandleOp>, <tf.Operation 'scope_0/scope_1/x_1/IsInitialized/VarIsInitializedOp' type=VarIsInitializedOp>, <tf.Operation 'scope_0/scope_1/x_1/Assign' type=AssignVariableOp>, <tf.Operation 'scope_0/scope_1/x_1/Read/ReadVariableOp' type=ReadVariableOp>, <tf.Operation 'scope_0/batch_size' type=Const>, <tf.Operation 'scope_0/drop_remainder' type=Const>, <tf.Operation 'scope_0/count' type=Const>, <tf.Operation 'iterator/IteratorV2' type=IteratorV2>, <tf.Operation 'iterator/TensorSliceDataset' type=TensorSliceDataset>, <tf.Operation 'iterator/MapDataset' type=MapDataset>, <tf.Operation 'iterator/BatchDatasetV2' type=BatchDatasetV2>, <tf.Operation 'iterator/RepeatDataset' type=RepeatDataset>, <tf.Operation 'iterator/MakeIterator' type=MakeIterator>, <tf.Operation 'iterator/IteratorToStringHandle' type=IteratorToStringHandle>, <tf.Operation 'iterator/iterator_handle' type=Placeholder>, <tf.Operation 'iterator/IteratorFromStringHandleV2' type=IteratorFromStringHandleV2>, <tf.Operation 'iterator/IteratorToStringHandle_1' type=IteratorToStringHandle>, <tf.Operation 'init' type=NoOp>, <tf.Operation 'init_1' type=NoOp>]
(array([2.], dtype=float32), array([-1], dtype=int32))
(array([3.], dtype=float32), array([-2], dtype=int32))
(array([4.], dtype=float32), array([-3], dtype=int32))
(array([5.], dtype=float32), array([-4], dtype=int32))
(array([6.], dtype=float32), array([-5], dtype=int32))
End of training dataset.

global vars: [<tf.Variable 'scope_0/scope_1/x:0' shape=() dtype=float32>, <tf.Variable 'scope_0/scope_1/x_1:0' shape=() dtype=float32>]
local vars: []
```
