### ISSUE TITLE
Newly included absl headers are missing from the include path

### ISSUE THREAD

**Issue by alsrgv** [tensorflow/tensorflow#22007]
[Newly included](https://github.com/tensorflow/tensorflow/commit/3cb3a450ed845c4602080f43d7bb6cfade298a22) `absl` headers are present in the `tf-nightly` Python package but do not seem to be part of the include path, and now custom op plugin compilation fails.

This has been broken between `tf_nightly-1.11.0.dev20180830` and `tf_nightly-1.11.0.dev20180831`.

```
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DHAVE_CUDA=1 -DHAVE_NCCL=1 -DHOROVOD_GPU_ALLREDUCE='N' -I/usr/local/cuda/include -I/usr/include/python2.7 -c horovod/tensorflow/mpi_ops.cc -o build/temp.linux-x86_64-2.7/horovod/tensorflow/mpi_ops.o -std=c++11 -fPIC -O2 -I/usr/local/include -pthread -Wl,-rpath -Wl,/usr/local/lib -Wl,--enable-new-dtags -L/usr/local/lib -lmpi -I/usr/local/lib/python2.7/dist-packages/tensorflow/include -D_GLIBCXX_USE_CXX11_ABI=0
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
    In file included from /usr/local/lib/python2.7/dist-packages/tensorflow/include/tensorflow/core/lib/core/status.h:24:0,
                     from /usr/local/lib/python2.7/dist-packages/tensorflow/include/tensorflow/core/framework/op_def_builder.h:25,
                     from /usr/local/lib/python2.7/dist-packages/tensorflow/include/tensorflow/core/framework/op.h:23,
                     from horovod/tensorflow/mpi_ops.cc:22:
    /usr/local/lib/python2.7/dist-packages/tensorflow/include/tensorflow/core/lib/core/stringpiece.h:34:38: fatal error: absl/strings/string_view.h: No such file or directory
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```

cc @yunxing

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by mhorikos** [comment]
I saw same issue for the horovod installation.
Workaround was to clone abseil-cpp from git. And making soft link of absl directory to your include path.

**Comment by skye** [comment]
cc @gunan

**Comment by willSapgreen** [comment]
Hello @mhorikos 
does 

> abseil-cpp from git

 mean this one
https://github.com/abseil/abseil-cpp

Thank you.

**Comment by gunan** [comment]
This is being investigated internally.
WE are currently trying to roll back the change to fix custom ops, and then we will try moving forward with a fix.

**Comment by mhorikos** [comment]
@willSapgreen

**Comment by mhorikos** [comment]
Hello  @willSapgreen 
Yes, it is.

**Comment by willSapgreen** [comment]
Hello @mhorikos , Thanks!!!

**Comment by alsrgv** [comment]
@gunan, thanks!

**Comment by gunan** [comment]
I don't think we have support for that usage. All of our code has a lot of dependencies, and we recommend using bazel to build our code.

For the initial issue reported, I think @angersson submitted a fix. @alsrgv could you try the latest nightly package?

**Comment by alsrgv** [comment]
@gunan, the issue is fixed, thanks!

I do see a different error in Travis CI, very similar to #19375:
```
/usr/bin/python: Relink `/usr/local/lib/python2.7/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so' with `/lib/x86_64-linux-gnu/librt.so.1' for IFUNC symbol `clock_gettime'
```

I will look into it separately next week, after I'm back from my vacation.

**Comment by dingevin** [comment]
hello @mhorikos, can you describe more detailed?  I have the same error, thanks.

**Comment by dingevin** [comment]
> Hello @dingevin
> 
> In your tensorflow installed top directory (that has Eigen, external, tensorflow, third_party, unsupported and etc.),
> 
> $ git clone https://github.com/abseil/abseil-cpp.git
> $ ln -s abseil-cpp/absl ./absl
> 
> Then you can install horovod

hi ， @mhorikos， thank you very much.

**Comment by dingevin** [comment]
hello @tensorflowbutler , the same issue was disappear when I compiled older versions(1.8.0). At the beginning i was just executed the command: git clone https://github.com/tensorflow/tensorflow.git,  i thought it git the latest version.

**Comment by girving** [comment]
Hitting a possibly related linker error when trying to load custom ops:

```
Traceback (most recent call last):
  File "./safety/debate/test_azero.py", line 4, in <module>
    from safety.debate import azero
  File "/Users/irving/openai/safety/safety/debate/azero.py", line 5, in <module>
    from safety.debate import gomoku
  File "/Users/irving/openai/safety/safety/debate/gomoku.py", line 9, in <module>
    gomoku_value = utils.load_debate_ops().gomoku_value
  File "/Users/irving/openai/safety/safety/core/utils.py", line 212, in load_debate_ops
    return tf.load_op_library(path)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 60, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: dlopen(/Users/irving/openai/safety/debate_ops.cpython-36m-darwin.so, 6): Symbol not found: __ZN10tensorflow11GetNodeAttrERKNS_9AttrSliceENSt3__117basic_string_viewIcNS3_11char_traitsIcEEEEPNS3_12basic_stringIcS6_NS3_9allocatorIcEEEE
  Referenced from: /Users/irving/openai/safety/debate_ops.cpython-36m-darwin.so
  Expected in: flat namespace
 in /Users/irving/openai/safety/debate_ops.cpython-36m-darwin.so
```

The custom op thinks the symbol is 

```
tensorflow::GetNodeAttr(tensorflow::AttrSlice const&, std::__1::basic_string_view<char, std::__1::char_traits<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*)
```

but the actual symbol is

```
tensorflow::GetNodeAttr(tensorflow::AttrSlice const&, absl::string_view, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*)
```

I.e., `absl::string_view` vs. `basic_string_view`.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @yunxing: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @yunxing: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by liamuk** [comment]
@girving I'm facing the same issue, did you find a solution?

**Comment by girving** [comment]
@liamuk No solution, but I haven't tried in a while.  Unfortunately I can't build at all now due to https://github.com/tensorflow/tensorflow/issues/22902, so I don't know if it's still an issue.

**Comment by liamuk** [comment]
@girving Ah. If you hit it again, here's an issue I opened for it (with a workaround): https://github.com/tensorflow/tensorflow/issues/23561

**Comment by LJXLJXLJX** [comment]
> Hello @dingevin
> 
> In your tensorflow installed top directory (that has Eigen, external, tensorflow, third_party, unsupported and etc.),
> 
> $ git clone https://github.com/abseil/abseil-cpp.git
> $ ln -s abseil-cpp/absl ./absl
> 
> Then you can install horovod

Hello, I am working on windows10 visual studio 2015, how can I build the links?

**Comment by Oceania2018** [comment]
@LJXLJXLJX The file struct should looks like below:
![image](https://user-images.githubusercontent.com/1705364/51222977-9c572b00-1905-11e9-9983-8eb340f70896.png)

**Comment by AtekiRyu** [comment]
This probably helps https://github.com/tensorflow/tensorflow/commit/914f68bfc0d7629496cd5ef6a6104efc94b6eecc

**Comment by mohantym** [comment]
Hi @alsrgv! 
We are checking to see if you still need help in this issue , Have you tried latest stable version TF 2.6  yet? Please create a new issue if the issue is replicating in newer version. Thanks!
