### ISSUE TITLE
TensorflowLite compile error on Android

### ISSUE THREAD

**Issue by myflashlab** [tensorflow/tensorflow#22018]
I can't compile apk file when trying to use Firebase MLKIT using Tensorflowlite. I see this error when compiling:

The last line says: ```<br>...while parsing org/tensorflow/lite/DataType$1.class<br>1 error; aborting```

```
dx tool failed:<br>UNEXPECTED TOP-LEVEL EXCEPTION:<br>com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)<br>	
at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:472)<br>	
at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)<br>	
at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:388)<br>	
at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:251)<br>	
at com.android.dx.command.dexer.Main.processClass(Main.java:709)<br>	
at com.android.dx.command.dexer.Main.processFileBytes(Main.java:678)<br>	
at com.android.dx.command.dexer.Main.access$300(Main.java:83)<br>	
at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:607)<br>	
at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)<br>	
at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)<br>	
at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)<br>	
at com.android.dx.command.dexer.Main.processOne(Main.java:637)<br>	
at com.android.dx.command.dexer.Main.processAllFiles(Main.java:506)<br>	
at com.android.dx.command.dexer.Main.runMultiDex(Main.java:335)<br>	
at com.android.dx.command.dexer.Main.run(Main.java:245)<br>	
at com.android.dx.command.dexer.Main.main(Main.java:215)<br>	
at com.android.dx.command.Main.main(Main.java:106)<br>
...while parsing org/tensorflow/lite/DataType$1.class<br>1 error; aborting
```

We're on a Mac, JDK version is 1.8.0_152 and compiling with IntelliJ IDE. Any thought?

**Comment by myflashlab** [comment]
SOLVED. This was a problem with AdobeAIR SDK. Not related to tensorflow. cheers.
https://tracker.adobe.com/#/view/AIR-4198726
