### ISSUE TITLE
tflite_convert 

### ISSUE THREAD

**Issue by dlml** [tensorflow/tensorflow#22022]
huangwei@ubuntu:~$ tflite_convert --output_file=foo.tflite  --graph_def_file=opt_mnist_graph.pb --input_arrays=the_input_2 --output_arrays=out_2/truediv
2018-09-03 01:34:59.887931: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Traceback (most recent call last):
  File "/home/huangwei/.local/lib/python3.5/site-packages/tensorflow/python/framework/importer.py", line 418, in import_graph_def
    graph._c_graph, serialized, options)  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: NodeDef expected inputs '' do not match 1 inputs specified; Op<name=Const; signature= -> output:dtype; attr=value:tensor; attr=dtype:type>; NodeDef: batch_normalization_55/cond/batchnorm/add/y = Const[dtype=DT_FLOAT, value=Tensor<type: float shape: [] values: 1.1e-05>](batch_normalization_55/cond/Switch)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/huangwei/.local/bin/tflite_convert", line 11, in <module>
    sys.exit(main())
  File "/home/huangwei/.local/lib/python3.5/site-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 370, in main
    app.run(main=run_main, argv=sys.argv[:1])
  File "/home/huangwei/.local/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/home/huangwei/.local/lib/python3.5/site-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 366, in run_main
    _convert_model(tflite_flags)
  File "/home/huangwei/.local/lib/python3.5/site-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 94, in _convert_model
    converter = _get_toco_converter(flags)
  File "/home/huangwei/.local/lib/python3.5/site-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 81, in _get_toco_converter
    return converter_fn(**converter_kwargs)
  File "/home/huangwei/.local/lib/python3.5/site-packages/tensorflow/contrib/lite/python/lite.py", line 220, in from_frozen_graph
    _import_graph_def(graph_def, name="")
  File "/home/huangwei/.local/lib/python3.5/site-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "/home/huangwei/.local/lib/python3.5/site-packages/tensorflow/python/framework/importer.py", line 422, in import_graph_def
    raise ValueError(str(e))
ValueError: NodeDef expected inputs '' do not match 1 inputs specified; Op<name=Const; signature= -> output:dtype; attr=value:tensor; attr=dtype:type>; NodeDef: batch_normalization_55/cond/batchnorm/add/y = Const[dtype=DT_FLOAT, value=Tensor<type: float shape: [] values: 1.1e-05>](batch_normalization_55/cond/Switch)

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by dlml** [comment]
my model is generated by tf 1.4.0，i use tf 1.10.0 to convert my model to the tflite, i can use "freeze_graph.py" to convert my model, also, can use "optimize_for_inference.py" to convert my frozen_graph to pb, but the last step to generate tflite has this bug

**Comment by dlml** [comment]
i use keras tosave my model use the format of h5, the backend is  tf tensorflow-gpu (1.4.0), the model architecture is densnet+ctc

**Comment by dlml** [comment]
ValueError: Didn't find custom op for name 'Merge' with version 1
Didn't find custom op for name 'Switch' with version 1
Didn't find custom op for name 'SquaredDifference' with version 1
Registration failed.

**Comment by jdduke** [comment]
Generalized support for Merge and Switch are a ways off, as they're control flow mechanisms, but I've added SquaredDifference to our todo list. It would really help if you could share the model, or how you generated the model, so we can see if there's a way to remove the Merge/Switch ops.

**Comment by dlml** [comment]
i have perfectly solved my problems by using orignal tensorflow, i found use keras will generate the ops that is not supported by tflite

**Comment by dlml** [comment]
@jdduke

**Comment by jdduke** [comment]
Thanks for the feedback @dlml. We're always looking to improve native Keras support, but I'll go ahead and close this for now.

**Comment by Elites2017** [comment]
> i have perfectly solved my problems by using orignal tensorflow, i found use keras will generate the ops that is not supported by tflite

How didi you solve the problem @dlml ? I have the same problem. Any help is welcomed

**Comment by dlml** [comment]
@Elites2017 you can use tf.keras to train model
