### ISSUE TITLE
Inconsistent behaviour of CSVDataset with eager disabled/enabled

### ISSUE THREAD

**Issue by superbobry** [tensorflow/tensorflow#22030]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: N/A
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: v1.10.0-12-g4dcfddc5d1 1.10.1
- **Python version**: 3.6.5
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**: see below

### Describe the problem

The following code snippet works without any errors in eager mode but fails when eager is disabled

```python
import tensorflow as tf
data = tf.contrib.data.CsvDataset("foo.csv", [tf.constant(0, dtype=tf.int64)])
data.make_one_shot_iterator().get_next()
```

wheer `foo.csv` is generated by `echo 42 > foo.csv`. The issue is fixed by making 42 a single-element list following the example in the `CsvDataset` [documentation](https://www.tensorflow.org/api_docs/python/tf/contrib/data/CsvDataset).

#### Eager execution disabled

```python
>>> data.make_one_shot_iterator().get_next()
Traceback (most recent call last):
  File "[...]/tensorflow/python/framework/ops.py", line 1576, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Shape must be rank 1 but is rank 0 for 'CSVDataset' (op: 'CSVDataset') with input shapes: [], [], [], [], [], [], [0], [].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "[...]/tensorflow/python/data/ops/dataset_ops.py", line 170, in make_one_shot_iterator
    six.reraise(ValueError, err)
  File "[...]/six.py", line 692, in reraise
    raise value.with_traceback(tb)
ValueError: Shape must be rank 1 but is rank 0 for 'CSVDataset' (op: 'CSVDataset') with input shapes: [], [], [], [], [], [], [0], [].
```

#### Eager execution enabled

```
>>> data.make_one_shot_iterator().get_next()
(<tf.Tensor: id=53, shape=(), dtype=int64, numpy=42>,)
```

**Comment by superbobry** [comment]
Thanks @rachellim!
