### ISSUE TITLE
Optimizing slice of variable not possible

### ISSUE THREAD

**Issue by Hoeze** [tensorflow/tensorflow#22059]
Applying the gradient of a variable slice currently results in a `NotImplemented` error of tf.train.Optimizer.

**The following two examples are working:**
```python
### WORKING ###
X = tf.Variable(2, dtype=tf.float32)
y = tf.constant(10, dtype="float32")
loss = y - (X*X)

variables=[X]
gradient = tf.gradients(loss, variables)
gradient = [(g, v) for g, v in zip(gradient, variables)]
train_op = tf.train.AdamOptimizer().apply_gradients(gradient)
```

```python
### WORKING ###
big_X = tf.Variable([2,3,4], dtype=tf.float32)
X = big_X[0]
y = tf.constant(10, dtype="float32")
loss = y - (X*X)

train_op = train_op = tf.train.AdamOptimizer().minimize(loss)
```

**The following example throws an error:**
```python
### NOT WORKING ###
big_X = tf.Variable([2,3,4], dtype=tf.float32)
X = big_X[0]
y = tf.constant(10, dtype="float32")
loss = y - (X*X)

variables=[X]
gradient = tf.gradients(loss, variables)
gradient = [(g, v) for g, v in zip(gradient, variables)]
train_op = tf.train.AdamOptimizer().apply_gradients(gradient)
```
The error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-22-10282dee2005>", line 10, in <module>
    train_op = tf.train.AdamOptimizer().apply_gradients(gradient)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/optimizer.py", line 605, in apply_gradients
    update_ops.append(processor.update_op(self, grad))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/optimizer.py", line 189, in update_op
    raise NotImplementedError("Trying to update a Tensor ", self._v)
NotImplementedError: ('Trying to update a Tensor ', <tf.Tensor 'strided_slice_9:0' shape=() dtype=float32>)
```
------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: NA
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: v1.10.1-0-g4dcfddc5d1 1.10.1
- **Python version**: 3.6.5
- **Bazel version (if compiling from source)**: NA
- **GCC/Compiler version (if compiling from source)**: NA
- **CUDA/cuDNN version**: NA
- **GPU model and memory**: NA
- **Exact command to reproduce**: NA

**Comment by Hoeze** [comment]
I debugged this problem:
Since this variable slice is a Tensor, it gets wrapped by the class `_TensorProcessor` in `tensorflow/python/training/optimizer.py`.
Since `update_op()` is not implemented in this special case, the gradient cannot be applied.

There would be multiple solutions to this problem:
- Make variable slices return another special variable type
- Implement `update_op()` in `_TensorProcessor` for tensors supporting some `.assign()` method

**Comment by tensorflowbutler** [comment]
Nagging Assignee @robieta: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @robieta: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @robieta: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @robieta: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @robieta: It has been 59 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by jvishnuvardhan** [comment]
@Hoeze Is this still an issue? Thanks!

**Comment by Hoeze** [comment]
@jvishnuvardhan Yes, the issue is still the same

**Comment by mayou36** [comment]
Are there any news on this? That would indeed be helpful

**Comment by maxhgerlach** [comment]
Hi @rmlarsen, is some extension to lift this limitation on the TensorFlow roadmap? Applying an optimizer to a slice of a variable would unblock quite a few more flexible approaches to training certain classes of models.

**Comment by SNMS95** [comment]
Are there any updates on this ?

**Comment by Emalude** [comment]
Hi, any updates about this issue? I'm using a library for Knowledge Graph Embedding models based on Tensorflow to develop an explainability gradient-based method by tracking the influence of single training samples. Given the high number of parameters of such models I think it would be very useful for Tensorflow to support the gradient computation of only a subset of training variables.

**Comment by jonas-eschle** [comment]
Actually, it seems to still be an issue, even running with the [nightlies](https://colab.research.google.com/drive/1yUI4iMZx1tYCWlz4b1oZpkKWnI69c5Ie?usp=sharing)

**Comment by Venkat6871** [comment]
Hi @Hoeze ,
Thank you so much for filing this bug request! We truly appreciate your support. At the moment, this request is not prioritized and mark it for community contributions. If you would like to contribute on a fix, please feel free to fork the repository and submit a pull request in accordance with the TensorFlow [CONTRIBUTION GUIDELINES](https://www.tensorflow.org/community/contribute/code) and link this issue in your PR to ensure the maintainers can easily review and collaborate.To avoid duplicate work, please leave a comment here if you decide to take it on!
Thank you again for your interest and we look forward to seeing your contributions!

**Comment by Venkat6871** [comment]
Hi @Hoeze ,
We are closing this issue due to inactivity. If this is still relevant and you would like to work on it, please feel free to reopen the issue or submit a pull request referencing it.

Thank you for your understanding.
