### ISSUE TITLE
freeze_graph.py with --input_saved_model argument gives `IOError: SavedModel file does not exist`

### ISSUE THREAD

**Issue by chrisrapson** [tensorflow/tensorflow#22069]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Ubuntu 18.04
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
n/a
- **TensorFlow installed from (source or binary)**:
pip
- **TensorFlow version (use command below)**:
1.10.1
- **Python version**:
2.7.15rc1
- **Bazel version (if compiling from source)**:
n/a
- **GCC/Compiler version (if compiling from source)**:
n/a
- **CUDA/cuDNN version**:
n/a
- **GPU model and memory**:
n/a
- **Exact command to reproduce**:
```
#first, train the model with
python tensorflow/models/research/deeplab/train.py \
    --logtostderr \
    --clone_on_cpu=True \
    --training_number_of_steps=900 \ # 90000 \
    --train_split="train" \
    --model_variant="mobilenet_v2" \
    --atrous_rates=6 \
    --atrous_rates=12 \
    --atrous_rates=18 \
    --output_stride=16 \
    --decoder_output_stride=4 \
    --train_crop_size=128 \
    --train_crop_size=128 \
    --train_batch_size=1 \
    --dataset="cityscapes" \
    --tf_initial_checkpoint=${PATH_TO_INITIAL_CHECKPOINT} \
    --train_logdir=${PATH_TO_TRAIN_DIR} \
    --dataset_dir=${PATH_TO_DATASET}

#then try to freeze the output
python tensorflow/python/tools/freeze_graph.py \
     --input_saved_model=${PATH_TO_TRAIN_DIR} \
     --output_graph=${PATH_TO_TRAIN_DIR}/frozen_graph.pb \
     --output_node_names=MobilenetV2/expanded_conv_16/output
```

### Describe the problem
The first problem is that the train.py script seems to change the structure of the graph. Specifically, the input and output nodes from the `initial_checkpoint` are missing. The normal `output_node_names` such as softmax, predictions etc do not appear in the trained graph.pbtxt, which is why I have used `MobilenetV2/expanded_conv_16/output`. The ImageTensor also does not appear as an input_node.
However, the problem with missing nodes is not the focus of this issue.

The second problem is that `freeze_graph.ph` with the `--input_saved_model` option gives 
```
Traceback (most recent call last):
  File "/home/username/.local/lib/python2.7/site-packages/tensorflow/python/tools/freeze_graph.py", line 382, in <module>
    run_main()
  File "/home/username/.local/lib/python2.7/site-packages/tensorflow/python/tools/freeze_graph.py", line 379, in run_main
    app.run(main=my_main, argv=[sys.argv[0]] + unparsed)
  File "/home/username/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/home/username/.local/lib/python2.7/site-packages/tensorflow/python/tools/freeze_graph.py", line 378, in <lambda>
    my_main = lambda unused_args: main(unused_args, flags)
  File "/home/username/.local/lib/python2.7/site-packages/tensorflow/python/tools/freeze_graph.py", line 272, in main
    flags.saved_model_tags, checkpoint_version)
  File "/home/username/.local/lib/python2.7/site-packages/tensorflow/python/tools/freeze_graph.py", line 229, in freeze_graph
    input_saved_model_dir, saved_model_tags).graph_def
  File "/home/username/.local/lib/python2.7/site-packages/tensorflow/python/tools/saved_model_utils.py", line 42, in get_meta_graph_def
    saved_model = reader.read_saved_model(saved_model_dir)
  File "/home/username/.local/lib/python2.7/site-packages/tensorflow/contrib/saved_model/python/saved_model/reader.py", line 55, in read_saved_model
    raise IOError("SavedModel file does not exist at: %s" % saved_model_dir)
IOError: SavedModel file does not exist at: /path/given/in/PATH_TO_TRAIN_DIR

$ls ${PATH_TO_TRAIN_DIR}
-rw-r--r-- 1 username username    21786 Sep  3 15:28 model.ckpt-0.index
-rw-r--r-- 1 username username 21955616 Sep  3 15:28 model.ckpt-0.data-00000-of-00001
-rw-r--r-- 1 username username  3070908 Sep  3 15:28 model.ckpt-0.meta
-rw-r--r-- 1 username username  6081043 Sep  4 10:54 graph.pbtxt
-rw-r--r-- 1 username username 21955616 Sep  4 10:54 model.ckpt-900.data-00000-of-00001
-rw-r--r-- 1 username username    21786 Sep  4 10:54 model.ckpt-900.index
-rw-r--r-- 1 username username  3070908 Sep  4 10:54 model.ckpt-900.meta
-rw-r--r-- 1 username username      541 Sep  4 10:54 checkpoint

```

**Comment by chrisrapson** [comment]
I have since discovered that some of the options I was supplying to `train.py` were not recommended for MobileNetV2. My goal is to keep the same network structure of MobileNetV2 (as far as possible, given that I am using a different number of classes), but retrain the weights. If the network structure would stay the same, I think `freeze_graph.py` would have no problems with missing nodes.

See also https://stackoverflow.com/questions/52177020/trying-to-retrain-a-tensorflow-model-input-and-output-nodes-disappear

**Comment by harshini-gadige** [comment]
Closing this issue for now. Feel free to reopen.

**Comment by chrisrapson** [comment]
What is the reason for closing? I have seen examples elsewhere where people have the same problem, so I don't think it's just me. I think it could be a user error which we all have in common, or a bug. Either way, I don't think it has been resolved, so I would think that it shouldn't be closed?

**Comment by karmel** [comment]
@chrisrapson , it looks like you are trying to freeze a checkpoint, not a SavedModel. A SavedModel should have a saved_model.pb and associated variables-- please see https://www.tensorflow.org/guide/saved_model

**Comment by chrisrapson** [comment]
@karmel yes, I am trying to freeze a checkpoint, not a SavedModel. Isn't that what `freeze_graph.py` is for? The first line of `freeze_graph.py` reads:

`Converts checkpoint variables into Const ops in a standalone GraphDef file.`

If what I am doing is not the correct way to convert `ckpt` files to `pb` files, then what is?

**Comment by karmel** [comment]
A SavedModel includes checkpointed vars, so that comment refers to the component of the SavedModel that is checkpointed vars, which it inserts into the other component, which is the graph def. I don't think a checkpoint alone has enough information in it to produce a frozen graph currently. @gargn to confirm.

**Comment by gargn** [comment]
In order to freeze a graph, you need to provide either a SavedModel or a non-frozen GraphDef (i.e. a GraphDef with variables) and the checkpoints. Freeze graph can then produce a GraphDef with all of the weights represented as constants.

In your case you might be able to freeze the graph with a command such as the following:
```
bazel build tensorflow/python/tools:freeze_graph && \
bazel-bin/tensorflow/python/tools/freeze_graph \
--input_graph=${PATH_TO_TRAIN_DIR}/graph.pbtxt \
--input_binary=false \
--input_checkpoint=${PATH_TO_TRAIN_DIR}/checkpoint/model.ckpt-100 \
--output_graph=${PATH_TO_TRAIN_DIR}/frozen_graph.pb \
--output_node_names=MobilenetV2/expanded_conv_16/output
```

**Comment by chrisrapson** [comment]
Thanks @gargn, that solves the second problem I referred to, and allows me to successfully generate a frozen graph from my checkpoint. Unfortunately, when I try to use the frozen graph, it tells me

`TypeError: Cannot interpret feed_dict key as Tensor: the name 'ImageTensor:0' refers to a Tensor which does not exist. The operation, 'ImageTensor', does not exist in the graph.`

So the first problem still persists. I expected my checkpoint graph to have the same input/output nodes as the `tf_initial_checkpoint`, and for this checkpoint to have the same input/output nodes as the frozen graph which was bundled with it in a tar file. (Specifically, [this tar file](http://download.tensorflow.org/models/deeplabv3_mnv2_pascal_train_aug_2018_01_29.tar.gz).)

Is that expectation correct? If not, how do I take a downloaded model (pb or ckpt) and retrain it? The pb file I downloaded is already very good at image segmentation. I am looking to modify it slightly to segment only 4 classes instead of 30, and to teach it these classes by training it on my own data.

**Comment by gargn** [comment]
Can you provide the exact steps to reproduce this problem? Namely the `train.py` script, the commands you are using to run the training script, and any additional files used during the retraining process?
 
@karmel might have context?

**Comment by chrisrapson** [comment]
The command is as I wrote in the original issue. The `train.py` script is part of the tensorflow repo in the models/research/deeplab directory. The last three arguments are:
tf_initial_checkpoint - which is the index file, downloaded as part of the tar file I linked in my previous message
train_logdir - which is an empty directory
dataset_dir - which is a directory filled with tfrecords (created with the `convert_cityscapes.sh` script in the models/research/deeplab/datasets directory)

**Comment by tensorflowbutler** [comment]
Nagging Assignee @karmel: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @karmel: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @karmel: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by mohantym** [comment]
Hi @chrisrapson ! 
It seems you are using older versions(1.x versions) of Tensorflow which is not supported any more. Please switch to[ 2.8](https://github.com/tensorflow/models/tree/master/research/deeplab) or later and let us know .Thank you!

**Comment by chrisrapson** [comment]
This issue was raised in 2018, I don't think tf2.0 was available then? Feel free to close this issue.
