### ISSUE TITLE
Build failes

### ISSUE THREAD

**Issue by Tockra** [tensorflow/tensorflow#22082]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux powerai 4.4.0-109-generic #132-Ubuntu SMP Tue Jan 9 20:00:40 UTC 2018 ppc64le ppc64le ppc64le GNU/Linux

- **TensorFlow installed from (source or binary)**:
source (R1.11)
- **TensorFlow version (use command below)**:
R1.11
- **Python version**:
3.5.2
- **Bazel version (if compiling from source)**:
1.15.2
- **GCC/Compiler version (if compiling from source)**:
5.4.0 20160609 
- **CUDA/cuDNN version**:
CUDA 9.2, cuDNN 7.1
- **GPU model and memory**:
4 x  Tesla P100-SXM2-16GB
- **Exact command to reproduce**:
bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package

### Describe the problem
Build failes at the end:

cc1plus: warning: unrecognized command line option '-Wno-self-assign'
ERROR: /root/tensorflow/tensorflow/BUILD:592:1: Executing genrule //tensorflow:tensorflow_python_api_gen failed (Exit 1)
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api.runfiles/org_tensorflow/tensorflow/python/tools/api/generator/create_python_api.py", line 27, in <module>
    from tensorflow.python.tools.api.generator import doc_srcs
  File "/root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api.runfiles/org_tensorflow/tensorflow/core/framework/graph_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/__init__.py", line 37, in <module>
    __import__('pkg_resources').declare_namespace(__name__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2952, in _initialize_master_working_set
    add_activation_listener(lambda dist: dist.activate())
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 956, in subscribe
    callback(dist)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2952, in <lambda>
    add_activation_listener(lambda dist: dist.activate())
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2515, in activate
    declare_namespace(pkg)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2097, in declare_namespace
    _handle_ns(packageName, path_item)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2047, in _handle_ns
    _rebuild_mod_path(path, packageName, module)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2066, in _rebuild_mod_path
    orig_path.sort(key=position_in_sys_path)
AttributeError: '_NamespacePath' object has no attribute 'sort'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 7114.719s, Critical Path: 1859.33s
INFO: 4737 processes: 4737 local.
FAILED: Build did NOT complete successfully

**Comment by yongtang** [comment]
It looks like to be related to https://github.com/pypa/setuptools/issues/1282

Wondering if upgrade setuptools will resolve the issue?

**Comment by Tockra** [comment]
So that shouldn't happen with the 40.2.0 version?

**Comment by gunan** [comment]
I agree with @yongtang 
The stacktrace points to an issue outside tensorflow.
Could you try the recommendation on pypa/setuptools#1282

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by daa** [comment]
Similar issue is https://github.com/pypa/setuptools/issues/1321 and it's solved in setuptools-40.3.0, so I hope that with latest setuptools build will succeed.

**Comment by luaGeeko** [comment]
upgrading setuptools==40.6.3 works perfectly and build succeeds.
OS - ubuntu 16.04 
tensorflow 1.12, python-3.5
cuda 10.0, cudnn-7.3.1, nccl-2.3.5
If anyone requires the built .whl you can download from here
[https://drive.google.com/open?id=1ukL8M93LBPsBcERWPmL3VIzLSkFbCL_R](url)
