### ISSUE TITLE
GDR Cannot register memory region

### ISSUE THREAD

**Issue by wangshuaizs** [tensorflow/tensorflow#22081]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: NO
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  Linux Ubuntu 16.04
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: no
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**:1.10
- **Python version**: 2.7 
- **Bazel version (if compiling from source)**: 0.16.1
- **GCC/Compiler version (if compiling from source)**: 5.4
- **CUDA/cuDNN version**: 9.0
- **GPU model and memory**: K40c 12G

## Describe the problem
I tried to use GDR, but it seems no performance improvement compared to native RDMA, and logs are the following:

```
$ python benchmarks/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py --local_parameter_device=cpu --num_gpus=4 --batch_size=128 --num_epochs=10 --model=alexnet --variable_update=distributed_replicated --data_dir=/home/shuai/imagenet-data --all_reduce_spec=pscpu --job_name=worker --ps_hosts=10.10.10.6:2222 --worker_hosts=10.10.10.5:3333 --task_index=0 --server_protocol=grpc+gdr
2018-09-05 15:05:58.062100: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1405] Found device 0 with properties:
name: Tesla K40c major: 3 minor: 5 memoryClockRate(GHz): 0.745
pciBusID: 0000:02:00.0
totalMemory: 11.92GiB freeMemory: 11.84GiB
2018-09-05 15:05:58.211502: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1405] Found device 1 with properties:
name: Tesla K40c major: 3 minor: 5 memoryClockRate(GHz): 0.745
pciBusID: 0000:03:00.0
totalMemory: 11.92GiB freeMemory: 11.84GiB
2018-09-05 15:05:58.374791: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1405] Found device 2 with properties:
name: Tesla K40c major: 3 minor: 5 memoryClockRate(GHz): 0.745
pciBusID: 0000:83:00.0
totalMemory: 11.92GiB freeMemory: 11.84GiB
2018-09-05 15:05:58.553152: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1405] Found device 3 with properties:
name: Tesla K40c major: 3 minor: 5 memoryClockRate(GHz): 0.745
pciBusID: 0000:84:00.0
totalMemory: 11.92GiB freeMemory: 11.84GiB
2018-09-05 15:05:58.553735: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1484] Adding visible gpu devices: 0, 1, 2, 3
2018-09-05 15:05:59.918282: I tensorflow/core/common_runtime/gpu/gpu_device.cc:965] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-09-05 15:05:59.918335: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971]      0 1 2 3
2018-09-05 15:05:59.918344: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] 0:   N Y N N
2018-09-05 15:05:59.918349: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] 1:   Y N N N
2018-09-05 15:05:59.918354: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] 2:   N N N Y
2018-09-05 15:05:59.918359: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] 3:   N N Y N
2018-09-05 15:05:59.919609: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1097] Created TensorFlow device (/job:worker/replica:0/task:0/device:GPU:0 with 11473 MB memory) -> physical GPU (device: 0, name: Tesla K40c, pci bus id: 0000:02:00.0, compute capability: 3.5)
2018-09-05 15:06:00.088804: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1097] Created TensorFlow device (/job:worker/replica:0/task:0/device:GPU:1 with 11473 MB memory) -> physical GPU (device: 1, name: Tesla K40c, pci bus id: 0000:03:00.0, compute capability: 3.5)
2018-09-05 15:06:00.288448: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1097] Created TensorFlow device (/job:worker/replica:0/task:0/device:GPU:2 with 11473 MB memory) -> physical GPU (device: 2, name: Tesla K40c, pci bus id: 0000:83:00.0, compute capability: 3.5)
2018-09-05 15:06:00.487520: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1097] Created TensorFlow device (/job:worker/replica:0/task:0/device:GPU:3 with 11473 MB memory) -> physical GPU (device: 3, name: Tesla K40c, pci bus id: 0000:84:00.0, compute capability: 3.5)
2018-09-05 15:06:00.688704: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:215] Initialize GrpcChannelCache for job ps -> {0 -> 10.10.10.6:2222}
2018-09-05 15:06:00.688752: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:215] Initialize GrpcChannelCache for job worker -> {0 -> localhost:3333}
2018-09-05 15:06:00.697485: I tensorflow/contrib/gdr/gdr_memory_manager.cc:254] RDMA server is listening on 10.10.10.5:3333
2018-09-05 15:06:00.697568: I tensorflow/contrib/gdr/gdr_memory_manager.cc:302] Instrumenting CPU allocator cuda_host_bfc
2018-09-05 15:06:00.697588: I tensorflow/contrib/gdr/gdr_memory_manager.cc:302] Instrumenting CPU allocator cpu_pool
2018-09-05 15:06:00.697607: I tensorflow/contrib/gdr/gdr_memory_manager.cc:302] Instrumenting CPU allocator cpu_rdma_bfc
2018-09-05 15:06:00.697830: I tensorflow/contrib/gdr/gdr_memory_manager.cc:95] NUMA node for device: mlx4_0 is 1
2018-09-05 15:06:00.734616: W tensorflow/contrib/gdr/gdr_memory_manager.cc:705] Cannot register memory region
2018-09-05 15:06:00.771893: W tensorflow/contrib/gdr/gdr_memory_manager.cc:705] Cannot register memory region
2018-09-05 15:06:00.771954: I tensorflow/contrib/gdr/gdr_memory_manager.cc:314] Instrumenting GPU allocator with bus_id 2
2018-09-05 15:06:00.772783: I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:375] Started server with target: grpc://localhost:3333
```
and here is GPU topology；
···
$ nvidia-smi topo -m
        GPU0    GPU1    GPU2    GPU3    mlx4_0  CPU Affinity
GPU0     X      PHB     SYS     SYS     SYS     0-7,16-23
GPU1    PHB      X      SYS     SYS     SYS     0-7,16-23
GPU2    SYS     SYS      X      PHB     PHB     8-15,24-31
GPU3    SYS     SYS     PHB      X      PHB     8-15,24-31
mlx4_0  SYS     SYS     PHB     PHB      X

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe switches (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing a single PCIe switch
  NV#  = Connection traversing a bonded set of # NVLinks
···

The logs said," cannot register memory region" in GPU 2 and GPU 3. Is it a bug?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Exact command to reproduce

**Comment by wangshuaizs** [comment]
@tensorflowbutler 
Hi,
 I have updated exact command to reproduce, and I use the benchmark source code from tensorflow/benchmarks.

Thanks

**Comment by wangshuaizs** [comment]
@tensorflowbutler 

Do you have any ideas about this? Is it caused by a bug ?

**Comment by byronyi** [comment]
Have you tried to install `nv_peer_mem` driver to enable GDR?

By the way, what is the output for command `ulimit -l`? If you have inherit limit for page-locked memory, the RDMA memory allocator might not be able to register enough memory region. It is thus recommended to modify the limits in `/etc/security/limits.conf`.

**Comment by byronyi** [comment]
Then you could try adding `perror("rdma_reg_read");` here: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/gdr/gdr_memory_manager.cc#L703 and see what is the detailed error message.

**Comment by wangshuaizs** [comment]
As you have said, I modified the code to 
```else {
    perror("rdma_reg_read");
    LOG(WARNING) << "Cannot register memory region";
  }```

But there is no more message to output, compared with the code without ```perror()```. Maybe, this is only a warning, not an error.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatatodd: It has been 18 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by byronyi** [comment]
@wangshuai Wait until my PR https://github.com/tensorflow/tensorflow/pull/22559 is merged, or you could try that out  you self if you can’t wait.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatatodd: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatatodd: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by byronyi** [comment]
@wangshuaizs Should be fixed now. Could you try again?

**Comment by wangshuaizs** [comment]
Hi, @byronyi 

Sorry for late reply. I tried to replace the original code with the modified code in gdr_memory_manager.cc, based on tf r 1.10.1. But it failed. Then I downloaded the master source code and tried to install it, but it failed again with the following error messages:
```
ERROR: /home/shuai/tensorflow-master/tensorflow/contrib/gdr/BUILD:61:1: C++ compilati
tensorflow/contrib/gdr/gdr_worker.cc: In constructor 'tensorflow::GdrWorker::GdrWorke
tensorflow/contrib/gdr/gdr_worker.cc:46:45: error: no matching function for call to '
       recv_tensor_recent_request_ids_(100000) {}
                                             ^
In file included from ./tensorflow/contrib/gdr/gdr_worker.h:22:0,
                 from tensorflow/contrib/gdr/gdr_worker.cc:16:
./tensorflow/core/distributed_runtime/rpc/grpc_worker_service.h:36:3: note: candidate
   GrpcWorker(WorkerEnv* env, const ConfigProto& config);
   ^
./tensorflow/core/distributed_runtime/rpc/grpc_worker_service.h:36:3: note:   candida
Target //tensorflow/tools/pip_package:build_pip_package failed to build
```

**Comment by byronyi** [comment]
It seems 462a79b7fe98ad71dccbcf691a06a4a7f48ee382 breaks GDR and MPI by introducing an additional config parameter.

Ping @poxvoculi. I will send a PR soon.

**Comment by byronyi** [comment]
@wangshuaizs You could try 
``curl https://patch-diff.githubusercontent.com/raw/tensorflow/tensorflow/pull/23480.patch | git apply`` and see if it works.

**Comment by wangshuaizs** [comment]
@byronyi 
It compiled successfully this time. but it seems my training source code is not compatible with master. Here is the log:
```
2018-11-07 12:49:40.514512: I tensorflow/contrib/gdr/gdr_memory_manager.cc:228] RDMA server is listening on 10.10.11.7:3333
2018-11-07 12:49:40.514610: I tensorflow/contrib/gdr/gdr_memory_manager.cc:90] NUMA node for device: mlx4_0 is 1
2018-11-07 12:49:40.514643: I tensorflow/contrib/gdr/gdr_memory_manager.cc:266] Instrumenting CPU allocator(s)
2018-11-07 12:49:43.439704: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties:
name: Tesla K40c major: 3 minor: 5 memoryClockRate(GHz): 0.745
pciBusID: 0000:83:00.0
totalMemory: 11.92GiB freeMemory: 11.84GiB
2018-11-07 12:49:43.439772: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2018-11-07 12:49:43.441047: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-11-07 12:49:43.441076: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0
2018-11-07 12:49:43.441088: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N
2018-11-07 12:49:43.441642: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:worker/replica:0/task:0/device:GPU:0 with 11519 MB memory) -> physical GPU (device: 0, name: Tesla K40c, pci bus id: 0000:83:00.0, compute capability: 3.5)
2018-11-07 12:49:43.446125: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:222] Initialize GrpcChannelCache for job ps -> {0 -> 10.10.11.2:2222}
2018-11-07 12:49:43.446158: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:222] Initialize GrpcChannelCache for job worker -> {0 -> localhost:3333}
2018-11-07 12:49:43.452238: I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:381] Started server with target: grpc://localhost:3333
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From /home/shuai/test/yolo_tensorflow/yolo/yolo_net.py:346: calling reduce_max (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
WARNING:tensorflow:From train.py:239: __init__ (from tensorflow.python.training.sync_replicas_optimizer) is deprecated and will be removed in a future version.
Instructions for updating:
The `SyncReplicaOptimizer` is deprecated. For synchrononous training, please use [Distribution Strategies](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/distribute).
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/tensorflow/python/training/sync_replicas_optimizer.py:346: __init__ (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
WARNING:tensorflow:From train.py:251: __init__ (from tensorflow.python.training.supervisor) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.MonitoredTrainingSession
Worker 0: Initializing session...
2018-11-07 12:49:45.947153: I tensorflow/core/distributed_runtime/master_session.cc:1161] Start master session cdc6fedbc4db30df with config: gpu_options { } allow_soft_placement: true
2018-11-07 12:49:51.843039: I tensorflow/contrib/gdr/gdr_memory_manager.cc:685] RDMA endpoint connected to rdma://10.10.11.2:2222
WARNING:tensorflow:Standard services need a 'logdir' passed to the SessionManager
Worker 0: Session initialization complete.
Starting chief queue runner and running init_tokens_op
Start distributed training ...
Traceback (most recent call last):
  File "train.py", line 358, in <module>
    main()
  File "train.py", line 353, in main
    distributed_train(params)
  File "train.py", line 315, in distributed_train
    sess.run(train_op, feed_dict=feed_dict)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: NodeDef mentions attr 'reduction_type' not in Op<name=ConditionalAccumulator; signature= -> handle:Ref(string); attr=dtype:type,allowed=[DT_FLOAT, DT_DOUBLE, DT_INT32, DT_UINT8, DT_INT16, ..., DT_UINT16, DT_COMPLEX128, DT_HALF, DT_UINT32, DT_UINT64]; attr=shape:shape; attr=container:string,default=""; attr=shared_name:string,default=""; is_stateful=true>; NodeDef: sync_replicas/conditional_accumulator = ConditionalAccumulator[_class=["loc:@sync_replicas/AccumulatorApplyGradient"], container="", dtype=DT_FLOAT, reduction_type="MEAN", shape=[7,7,3,64], shared_name="yolo/conv_2/weights:0/grad_accum", _device="/job:ps/replica:0/task:0/device:CPU:0"](). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
```
Though no ```Cannot register memory region``` is printed, I don't know if it works.
ps: ```verbs``` failed to compile with tf-master. Would you mind making a patch based on r1.10? 

thanks

**Comment by byronyi** [comment]
@wangshuaizs Sorry, AFAIK we do not have necessary resources to back port patches to contrib to branch other than master.
