### ISSUE TITLE
AttributeError: 'SsdAnchorGenerator' object has no attribute 'height_stride'

### ISSUE THREAD

**Issue by Tgmstriker** [tensorflow/tensorflow#22093]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
I am using the stock scripts with a custom training dataset
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Windows 10
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
n/A
- **TensorFlow installed from (source or binary)**:
Installed via Anaconda command line
- **TensorFlow version (use command below)**:
b'v1.10.0-rc1-19-g656e7a2b34' 1.10.0
- **Python version**:
anaconda                  5.1.0                    py36_2
- **Bazel version (if compiling from source)**:
N/A
- **GCC/Compiler version (if compiling from source)**:
N/A
- **CUDA/cuDNN version**:
N/A
- **GPU model and memory**:
N/A
- **Exact command to reproduce**:
python train.py --logtostderr --train_dir=training\\ --pipeline_config_path=training\\test.config

### Describe the problem
I'm trying to train various models using a custom dataset.  I am able to train using the Faster RCNN Inception V2 without issue.  However, all of the other models I try to use throw the same error:

AttributeError: 'SsdAnchorGenerator' object has no attribute 'height_stride'

I've tried with ssd_mobilenet_v1_coco,ssd_mobilenet_v2_coco, and ssd_inception_v2_coco.  All three produce the same error.

### Source code / logs
C:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "train.py", line 168, in <module>
    tf.app.run()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "train.py", line 164, in main
    worker_job_name, is_chief, FLAGS.train_dir)
  File "C:\ProgramData\Anaconda3\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\trainer.py", line 240, in train
    detection_model = create_model_fn()
  File "C:\ProgramData\Anaconda3\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\builders\model_builder.py", line 98, in build
    add_background_class)
  File "C:\ProgramData\Anaconda3\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\builders\model_builder.py", line 178, in _build_ssd_model
    ssd_config.anchor_generator)
  File "C:\ProgramData\Anaconda3\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\builders\anchor_generator_builder.py", line 59, in build
    if ssd_anchor_generator_config.height_stride:
AttributeError: 'SsdAnchorGenerator' object has no attribute 'height_stride'
PS C:\Users\timothy.molner\Desktop\tensorflow\research\object_detection> python train.py --logtostderr --train_dir=training\\ --pipeline_config_path=training\\test.config

**Comment by Tgmstriker** [comment]
Bumping

**Comment by tensorflowbutler** [comment]
Nagging Assignee @jch1: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @jch1: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @jch1: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @jch1: It has been 59 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @jch1: It has been 74 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by jvishnuvardhan** [comment]
This is a stale issue. Also, we are no longer supporting TF1.x version. 

In the recent years, There were lot of improvements in the model garden. I think this might have got resolved with the recent TF version. If this is still an issue with recent TF2.x version, please feel free to share a simple standalone code to reproduce the issue.

There is a good resource to install and test recent TF models in model garden by following the tutorials in [this resource](https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/auto_examples/plot_object_detection_saved_model.html#sphx-glr-auto-examples-plot-object-detection-saved-model-py). Thanks!

I am closing this issue. Please feel free to reopen if I am mistaken. Thanks!
