### ISSUE TITLE
raw_rnns not working with xla jit compile

### ISSUE THREAD

**Issue by vishalsubbiah** [tensorflow/tensorflow#22102]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Centos 7.4.1708
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 1.10
- **Python version**: 3.4.5
- **Bazel version (if compiling from source)**: 0.16
- **GCC/Compiler version (if compiling from source)**: 4.8.5
- **CUDA/cuDNN version**: NA
- **GPU model and memory**: NA
- **Exact command to reproduce**: NA

### Describe the problem
Trying to run char_rnn using raw_rnns with LSTMCell using TF estimators on the shakespeare dataset. It trains when I don't use the xla jit compile. When I do try to add the xla jit compile, I run into errors.  

first error:
```
Traceback (most recent call last):
  File "/net/server5/srv/nfs/vishal-data/ws/venv_tf110/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 1278, in _do_call
    return fn(*args)
  File "/net/server5/srv/nfs/vishal-data/ws/venv_tf110/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 1263, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/net/server5/srv/nfs/vishal-data/ws/venv_tf110/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 1350, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InternalError: Resource arguments cannot be constant (argument 3)
	EncapsulateSubgraphsPass failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "basic_rnn.py", line 332, in <module>
    classifier.train(input_fn, steps=args.num_steps)
  File "/net/server5/srv/nfs/vishal-data/ws/venv_tf110/lib/python3.4/site-packages/tensorflow/python/estimator/estimator.py", line 376, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/net/server5/srv/nfs/vishal-data/ws/venv_tf110/lib/python3.4/site-packages/tensorflow/python/estimator/estimator.py", line 1145, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/net/server5/srv/nfs/vishal-data/ws/venv_tf110/lib/python3.4/site-packages/tensorflow/python/estimator/estimator.py", line 1173, in _train_model_default
    saving_listeners)
  File "/net/server5/srv/nfs/vishal-data/ws/venv_tf110/lib/python3.4/site-packages/tensorflow/python/estimator/estimator.py", line 1451, in _train_with_estimator_spec
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/net/server5/srv/nfs/vishal-data/ws/venv_tf110/lib/python3.4/site-packages/tensorflow/python/training/monitored_session.py", line 583, in run
    run_metadata=run_metadata)
  File "/net/server5/srv/nfs/vishal-data/ws/venv_tf110/lib/python3.4/site-packages/tensorflow/python/training/monitored_session.py", line 1059, in run
    run_metadata=run_metadata)
  File "/net/server5/srv/nfs/vishal-data/ws/venv_tf110/lib/python3.4/site-packages/tensorflow/python/training/monitored_session.py", line 1150, in run
    raise six.reraise(*original_exc_info)
  File "/net/server5/srv/nfs/vishal-data/ws/venv_tf110/lib/python3.4/site-packages/six.py", line 693, in reraise
    raise value
  File "/net/server5/srv/nfs/vishal-data/ws/venv_tf110/lib/python3.4/site-packages/tensorflow/python/training/monitored_session.py", line 1135, in run
    return self._sess.run(*args, **kwargs)
  File "/net/server5/srv/nfs/vishal-data/ws/venv_tf110/lib/python3.4/site-packages/tensorflow/python/training/monitored_session.py", line 1207, in run
    run_metadata=run_metadata)
  File "/net/server5/srv/nfs/vishal-data/ws/venv_tf110/lib/python3.4/site-packages/tensorflow/python/training/monitored_session.py", line 987, in run
    return self._sess.run(*args, **kwargs)
  File "/net/server5/srv/nfs/vishal-data/ws/venv_tf110/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 877, in run
    run_metadata_ptr)
  File "/net/server5/srv/nfs/vishal-data/ws/venv_tf110/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 1100, in _run
    feed_dict_tensor, options, run_metadata)
  File "/net/server5/srv/nfs/vishal-data/ws/venv_tf110/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 1272, in _do_run
    run_metadata)
  File "/net/server5/srv/nfs/vishal-data/ws/venv_tf110/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 1291, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Resource arguments cannot be constant (argument 3)
	EncapsulateSubgraphsPass failed
```
I fixed this by modifying the tensorflow/compiler/tf2xla/const_analysis.cc with
```
Status BackwardsConstAnalysis(const Graph& g,
         int index;
         status = GetNodeAttr(node->attrs(), "index", &index);
         if (!status.ok()) return;
-        compile_time_const_args->at(index) = true;
+       DataType dt;
+       status = GetNodeAttr(node->attrs(), "T", &dt);
+       if (!status.ok()) return;
+       if (dt != DT_RESOURCE) {
+         VLOG(1) << "HIHIH "<< SummarizeNodeDef(node->def());
+         compile_time_const_args->at(index) = true;
+       }
         return;
       }
       for (const Edge* pred : node->in_edges()) {
``` 
I then run into this error:
```
 (No registered '_Retval' OpKernel for XLA_CPU_JIT devices compatible with node test_conv_gradients_test_conv_rnn_while_select_1_grad_select_f_acc_0_retval_RetVal = _Retval[T=DT_RESOURCE, index=0](test_conv/gradients/test_conv/rnn/while/Select_1_grad/Select/f_acc)
         (OpKernel was found, but attributes didn't match)
        .  Registered:  device='XLA_CPU_JIT'; T in [DT_FLOAT, DT_DOUBLE, DT_INT32, DT_COMPLEX64, DT_INT64, DT_BOOL, DT_HALF, DT_UINT32, DT_UINT64]
  device='GPU'; T in [DT_STRING]
  device='GPU'; T in [DT_RESOURCE]
  device='GPU'; T in [DT_INT32]
  device='GPU'; T in [DT_BOOL]
  device='GPU'; T in [DT_COMPLEX128]
  device='GPU'; T in [DT_COMPLEX64]
  device='GPU'; T in [DT_INT8]
  device='GPU'; T in [DT_UINT8]
  device='GPU'; T in [DT_INT16]
  device='GPU'; T in [DT_UINT16]
  device='GPU'; T in [DT_INT64]
  device='GPU'; T in [DT_DOUBLE]
  device='GPU'; T in [DT_FLOAT]
  device='GPU'; T in [DT_BFLOAT16]
  device='GPU'; T in [DT_HALF]
  device='CPU'
  device='XLA_CPU'; T in [DT_FLOAT, DT_DOUBLE, DT_INT32, DT_COMPLEX64, DT_INT64, DT_BOOL, DT_HALF, DT_UINT32, DT_UINT64]
)
```

Is there a way for me to fix this? Or for the tensorflow folks to fix this? Or is there an example of using raw_rnns with the xla jit compile that I can look at?

**Comment by tensorflowbutler** [comment]
Nagging Assignee @jpienaar: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @jpienaar: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by jpienaar** [comment]
Variables should be handled specially around XLA compilation blocks, XLA doesn't have variables and instead the interaction with variables are handled by way of a rewrite (e.g., the variable's value is read before the part compiled by XLA and written upon return). The rewritting of resource variable read/use/writes should be taken care of for you by the new xla.compile. Could you try with the xla.compile?

**Comment by vishalsubbiah** [comment]
Thanks for the quick response. When I tired xla.compile on a VGGNet it took over an hour, so i'm guessing im not using it correctly. Do you have dummy example with how xla.compile is meant to be used? (I followed the comments in the code to use it, but I'm probably providing information I dont need to, in the tensors I am passing.). Also is it not possible to do it without xla.compile?

**Comment by vishalsubbiah** [comment]
So I did try again, with xla.compile,  and it didnt work, this was my stack trace: 
```
2018-10-10 11:33:05.589418: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3311865000 Hz
2018-10-10 11:33:05.591668: I tensorflow/compiler/xla/service/service.cc:149] XLA service 0x7f3600060dd0 executing computations on platform Host. Devices:
2018-10-10 11:33:05.591699: I tensorflow/compiler/xla/service/service.cc:157]   StreamExecutor device (0): <undefined>, <undefined>
2018-10-10 11:33:05.618642: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at xla_ops.cc:290 : Invalid argument: Detected unsupported operations when trying to compile graph cluster_7643397997199028266_f15n_0[] on XLA_CPU_JIT: _Arg (No registered '_Arg' OpKernel for XLA_CPU_JIT devices compatible with node {{node iteratortostringhandle_0_arg}} = _Arg[T=DT_STRING, index=2]()
	 (OpKernel was found, but attributes didn't match)
	.  Registered:  device='XLA_CPU_JIT'; T in [DT_FLOAT, DT_DOUBLE, DT_INT32, DT_UINT8, DT_INT8, ..., DT_QINT32, DT_HALF, DT_UINT32, DT_UINT64, DT_RESOURCE]
  device='XLA_CPU'; T in [DT_STRING]
  device='XLA_CPU'; T in [DT_RESOURCE]
  device='XLA_CPU'; T in [DT_UINT8, DT_QUINT8, DT_INT8, DT_QINT8, DT_INT32, DT_QINT32, DT_INT64, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_BOOL]
  device='CPU'
  device='GPU'; T in [DT_STRING]
  device='GPU'; T in [DT_RESOURCE]
  device='GPU'; T in [DT_INT32]
  device='GPU'; T in [DT_BOOL]
  device='GPU'; T in [DT_COMPLEX128]
  device='GPU'; T in [DT_COMPLEX64]
  device='GPU'; T in [DT_INT8]
  device='GPU'; T in [DT_UINT8]
  device='GPU'; T in [DT_INT16]
  device='GPU'; T in [DT_UINT16]
  device='GPU'; T in [DT_INT64]
  device='GPU'; T in [DT_DOUBLE]
  device='GPU'; T in [DT_FLOAT]
  device='GPU'; T in [DT_BFLOAT16]
  device='GPU'; T in [DT_HALF]
){{node iteratortostringhandle_0_arg}}
Traceback (most recent call last):
  File "/home/vishal/venv_master_xla/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/home/vishal/venv_master_xla/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/vishal/venv_master_xla/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Detected unsupported operations when trying to compile graph cluster_7643397997199028266_f15n_0[] on XLA_CPU_JIT: _Arg (No registered '_Arg' OpKernel for XLA_CPU_JIT devices compatible with node {{node iteratortostringhandle_0_arg}} = _Arg[T=DT_STRING, index=2]()
	 (OpKernel was found, but attributes didn't match)
	.  Registered:  device='XLA_CPU_JIT'; T in [DT_FLOAT, DT_DOUBLE, DT_INT32, DT_UINT8, DT_INT8, ..., DT_QINT32, DT_HALF, DT_UINT32, DT_UINT64, DT_RESOURCE]
  device='XLA_CPU'; T in [DT_STRING]
  device='XLA_CPU'; T in [DT_RESOURCE]
  device='XLA_CPU'; T in [DT_UINT8, DT_QUINT8, DT_INT8, DT_QINT8, DT_INT32, DT_QINT32, DT_INT64, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_BOOL]
  device='CPU'
  device='GPU'; T in [DT_STRING]
  device='GPU'; T in [DT_RESOURCE]
  device='GPU'; T in [DT_INT32]
  device='GPU'; T in [DT_BOOL]
  device='GPU'; T in [DT_COMPLEX128]
  device='GPU'; T in [DT_COMPLEX64]
  device='GPU'; T in [DT_INT8]
  device='GPU'; T in [DT_UINT8]
  device='GPU'; T in [DT_INT16]
  device='GPU'; T in [DT_UINT16]
  device='GPU'; T in [DT_INT64]
  device='GPU'; T in [DT_DOUBLE]
  device='GPU'; T in [DT_FLOAT]
  device='GPU'; T in [DT_BFLOAT16]
  device='GPU'; T in [DT_HALF]
){{node iteratortostringhandle_0_arg}}
	 [[{{node cluster}} = XlaLaunch[Nresources=9, Targs=[DT_FLOAT, DT_FLOAT, DT_STRING, DT_INT64, DT_INT64, ..., DT_INT32, DT_FLOAT, DT_BOOL, DT_FLOAT, DT_FLOAT], Tconstants=[], Tresults=[DT_FLOAT, DT_INT32, DT_INT32, DT_INT32, DT_INT32, ..., DT_INT32, DT_FLOAT, DT_INT32, DT_INT32, DT_FLOAT], function=cluster_7643397997199028266_f15n_0[], _device="/job:localhost/replica:0/task:0/device:CPU:0"](IteratorGetNext, IteratorGetNext:1, IteratorToStringHandle, batch_size, count, drop_remainder, tensors/component_0, tensors/component_1, test_conv/func/lstm_cell/bias/Initializer/zeros, test_conv/func/lstm_cell/bias/IsInitialized/VarIsInitializedOp, test_conv/func/lstm_cell/bias/Read/ReadVariableOp, test_conv/func/lstm_cell/kernel/Initializer/random_uniform/RandomUniform, test_conv/func/lstm_cell/kernel/Initializer/random_uniform/max, test_conv/func/lstm_cell/kernel/Initializer/random_uniform/min, test_conv/func/lstm_cell/kernel/Initializer/random_uniform/mul, test_conv/func/lstm_cell/kernel/Initializer/random_uniform/shape, test_conv/func/lstm_cell/kernel/Initializer/random_uniform/sub, test_conv/func/lstm_cell/kernel/Initializer/random_uniform, test_conv/func/lstm_cell/kernel/IsInitialized/VarIsInitializedOp, test_conv/func/lstm_cell/kernel/Read/ReadVariableOp, test_conv/rnn_final/final_layer/bias/Initializer/zeros, test_conv/rnn_final/final_layer/bias/IsInitialized/VarIsInitializedOp, test_conv/rnn_final/final_layer/bias/Read/ReadVariableOp, test_conv/rnn_final/final_layer/kernel/Initializer/random_uniform/RandomUniform, test_conv/rnn_final/final_layer/kernel/Initializer/random_uniform/max, test_conv/rnn_final/final_layer/kernel/Initializer/random_uniform/min, test_conv/rnn_final/final_layer/kernel/Initializer/random_uniform/mul, test_conv/rnn_final/final_layer/kernel/Initializer/random_uniform/shape, test_conv/rnn_final/final_layer/kernel/Initializer/random_uniform/sub, test_conv/rnn_final/final_layer/kernel/Initializer/random_uniform, test_conv/rnn_final/final_layer/kernel/IsInitialized/VarIsInitializedOp, test_conv/rnn_final/final_layer/kernel/Read/ReadVariableOp, test_conv/test_conv/func/lstm_cell/bias/Momentum/Read/ReadVariableOp, test_conv/test_conv/func/lstm_cell/bias/Momentum/Initializer/zeros, test_conv/test_conv/func/lstm_cell/bias/Momentum/IsInitialized/VarIsInitializedOp, test_conv/test_conv/func/lstm_cell/bias/Momentum/Read/ReadVariableOp, test_conv/test_conv/func/lstm_cell/bias/Momentum/Read_1/ReadVariableOp, test_conv/test_conv/func/lstm_cell/kernel/Momentum/Read/ReadVariableOp, test_conv/test_conv/func/lstm_cell/kernel/Momentum/Initializer/zeros/Const, test_conv/test_conv/func/lstm_cell/kernel/Momentum/Initializer/zeros/shape_as_tensor, test_conv/test_conv/func/lstm_cell/kernel/Momentum/Initializer/zeros, test_conv/test_conv/func/lstm_cell/kernel/Momentum/IsInitialized/VarIsInitializedOp, test_conv/test_conv/func/lstm_cell/kernel/Momentum/Read/ReadVariableOp, test_conv/test_conv/func/lstm_cell/kernel/Momentum/Read_1/ReadVariableOp, test_conv/test_conv/rnn_final/final_layer/bias/Momentum/Read/ReadVariableOp, test_conv/test_conv/rnn_final/final_layer/bias/Momentum/Initializer/zeros, test_conv/test_conv/rnn_final/final_layer/bias/Momentum/IsInitialized/VarIsInitializedOp, test_conv/test_conv/rnn_final/final_layer/bias/Momentum/Read/ReadVariableOp, test_conv/test_conv/rnn_final/final_layer/bias/Momentum/Read_1/ReadVariableOp, test_conv/test_conv/rnn_final/final_layer/kernel/Momentum/Read/ReadVariableOp, test_conv/test_conv/rnn_final/final_layer/kernel/Momentum/Initializer/zeros/Const, test_conv/test_conv/rnn_final/final_layer/kernel/Momentum/Initializer/zeros/shape_as_tensor, test_conv/test_conv/rnn_final/final_layer/kernel/Momentum/Initializer/zeros, test_conv/test_conv/rnn_final/final_layer/kernel/Momentum/IsInitialized/VarIsInitializedOp, test_conv/test_conv/rnn_final/final_layer/kernel/Momentum/Read/ReadVariableOp, test_conv/test_conv/rnn_final/final_layer/kernel/Momentum/Read_1/ReadVariableOp, OneShotIterator, test_conv/func/lstm_cell/bias, test_conv/func/lstm_cell/kernel, test_conv/rnn_final/final_layer/bias, test_conv/rnn_final/final_layer/kernel, test_conv/test_conv/func/lstm_cell/bias/Momentum, test_conv/test_conv/func/lstm_cell/kernel/Momentum, test_conv/test_conv/rnn_final/final_layer/bias/Momentum, test_conv/test_conv/rnn_final/final_layer/kernel/Momentum)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "basic_rnn.py", line 241, in <module>
    sess.run(result)
  File "/home/vishal/venv_master_xla/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/vishal/venv_master_xla/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/vishal/venv_master_xla/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/vishal/venv_master_xla/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Detected unsupported operations when trying to compile graph cluster_7643397997199028266_f15n_0[] on XLA_CPU_JIT: _Arg (No registered '_Arg' OpKernel for XLA_CPU_JIT devices compatible with node {{node iteratortostringhandle_0_arg}} = _Arg[T=DT_STRING, index=2]()
	 (OpKernel was found, but attributes didn't match)
	.  Registered:  device='XLA_CPU_JIT'; T in [DT_FLOAT, DT_DOUBLE, DT_INT32, DT_UINT8, DT_INT8, ..., DT_QINT32, DT_HALF, DT_UINT32, DT_UINT64, DT_RESOURCE]
  device='XLA_CPU'; T in [DT_STRING]
  device='XLA_CPU'; T in [DT_RESOURCE]
  device='XLA_CPU'; T in [DT_UINT8, DT_QUINT8, DT_INT8, DT_QINT8, DT_INT32, DT_QINT32, DT_INT64, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_BOOL]
  device='CPU'
  device='GPU'; T in [DT_STRING]
  device='GPU'; T in [DT_RESOURCE]
  device='GPU'; T in [DT_INT32]
  device='GPU'; T in [DT_BOOL]
  device='GPU'; T in [DT_COMPLEX128]
  device='GPU'; T in [DT_COMPLEX64]
  device='GPU'; T in [DT_INT8]
  device='GPU'; T in [DT_UINT8]
  device='GPU'; T in [DT_INT16]
  device='GPU'; T in [DT_UINT16]
  device='GPU'; T in [DT_INT64]
  device='GPU'; T in [DT_DOUBLE]
  device='GPU'; T in [DT_FLOAT]
  device='GPU'; T in [DT_BFLOAT16]
  device='GPU'; T in [DT_HALF]
){{node iteratortostringhandle_0_arg}}
	 [[{{node cluster}} = XlaLaunch[Nresources=9, Targs=[DT_FLOAT, DT_FLOAT, DT_STRING, DT_INT64, DT_INT64, ..., DT_INT32, DT_FLOAT, DT_BOOL, DT_FLOAT, DT_FLOAT], Tconstants=[], Tresults=[DT_FLOAT, DT_INT32, DT_INT32, DT_INT32, DT_INT32, ..., DT_INT32, DT_FLOAT, DT_INT32, DT_INT32, DT_FLOAT], function=cluster_7643397997199028266_f15n_0[], _device="/job:localhost/replica:0/task:0/device:CPU:0"](IteratorGetNext, IteratorGetNext:1, IteratorToStringHandle, batch_size, count, drop_remainder, tensors/component_0, tensors/component_1, test_conv/func/lstm_cell/bias/Initializer/zeros, test_conv/func/lstm_cell/bias/IsInitialized/VarIsInitializedOp, test_conv/func/lstm_cell/bias/Read/ReadVariableOp, test_conv/func/lstm_cell/kernel/Initializer/random_uniform/RandomUniform, test_conv/func/lstm_cell/kernel/Initializer/random_uniform/max, test_conv/func/lstm_cell/kernel/Initializer/random_uniform/min, test_conv/func/lstm_cell/kernel/Initializer/random_uniform/mul, test_conv/func/lstm_cell/kernel/Initializer/random_uniform/shape, test_conv/func/lstm_cell/kernel/Initializer/random_uniform/sub, test_conv/func/lstm_cell/kernel/Initializer/random_uniform, test_conv/func/lstm_cell/kernel/IsInitialized/VarIsInitializedOp, test_conv/func/lstm_cell/kernel/Read/ReadVariableOp, test_conv/rnn_final/final_layer/bias/Initializer/zeros, test_conv/rnn_final/final_layer/bias/IsInitialized/VarIsInitializedOp, test_conv/rnn_final/final_layer/bias/Read/ReadVariableOp, test_conv/rnn_final/final_layer/kernel/Initializer/random_uniform/RandomUniform, test_conv/rnn_final/final_layer/kernel/Initializer/random_uniform/max, test_conv/rnn_final/final_layer/kernel/Initializer/random_uniform/min, test_conv/rnn_final/final_layer/kernel/Initializer/random_uniform/mul, test_conv/rnn_final/final_layer/kernel/Initializer/random_uniform/shape, test_conv/rnn_final/final_layer/kernel/Initializer/random_uniform/sub, test_conv/rnn_final/final_layer/kernel/Initializer/random_uniform, test_conv/rnn_final/final_layer/kernel/IsInitialized/VarIsInitializedOp, test_conv/rnn_final/final_layer/kernel/Read/ReadVariableOp, test_conv/test_conv/func/lstm_cell/bias/Momentum/Read/ReadVariableOp, test_conv/test_conv/func/lstm_cell/bias/Momentum/Initializer/zeros, test_conv/test_conv/func/lstm_cell/bias/Momentum/IsInitialized/VarIsInitializedOp, test_conv/test_conv/func/lstm_cell/bias/Momentum/Read/ReadVariableOp, test_conv/test_conv/func/lstm_cell/bias/Momentum/Read_1/ReadVariableOp, test_conv/test_conv/func/lstm_cell/kernel/Momentum/Read/ReadVariableOp, test_conv/test_conv/func/lstm_cell/kernel/Momentum/Initializer/zeros/Const, test_conv/test_conv/func/lstm_cell/kernel/Momentum/Initializer/zeros/shape_as_tensor, test_conv/test_conv/func/lstm_cell/kernel/Momentum/Initializer/zeros, test_conv/test_conv/func/lstm_cell/kernel/Momentum/IsInitialized/VarIsInitializedOp, test_conv/test_conv/func/lstm_cell/kernel/Momentum/Read/ReadVariableOp, test_conv/test_conv/func/lstm_cell/kernel/Momentum/Read_1/ReadVariableOp, test_conv/test_conv/rnn_final/final_layer/bias/Momentum/Read/ReadVariableOp, test_conv/test_conv/rnn_final/final_layer/bias/Momentum/Initializer/zeros, test_conv/test_conv/rnn_final/final_layer/bias/Momentum/IsInitialized/VarIsInitializedOp, test_conv/test_conv/rnn_final/final_layer/bias/Momentum/Read/ReadVariableOp, test_conv/test_conv/rnn_final/final_layer/bias/Momentum/Read_1/ReadVariableOp, test_conv/test_conv/rnn_final/final_layer/kernel/Momentum/Read/ReadVariableOp, test_conv/test_conv/rnn_final/final_layer/kernel/Momentum/Initializer/zeros/Const, test_conv/test_conv/rnn_final/final_layer/kernel/Momentum/Initializer/zeros/shape_as_tensor, test_conv/test_conv/rnn_final/final_layer/kernel/Momentum/Initializer/zeros, test_conv/test_conv/rnn_final/final_layer/kernel/Momentum/IsInitialized/VarIsInitializedOp, test_conv/test_conv/rnn_final/final_layer/kernel/Momentum/Read/ReadVariableOp, test_conv/test_conv/rnn_final/final_layer/kernel/Momentum/Read_1/ReadVariableOp, OneShotIterator, test_conv/func/lstm_cell/bias, test_conv/func/lstm_cell/kernel, test_conv/rnn_final/final_layer/bias, test_conv/rnn_final/final_layer/kernel, test_conv/test_conv/func/lstm_cell/bias/Momentum, test_conv/test_conv/func/lstm_cell/kernel/Momentum, test_conv/test_conv/rnn_final/final_layer/bias/Momentum, test_conv/test_conv/rnn_final/final_layer/kernel/Momentum)]]
```

The code I am trying to run is found [here](https://github.com/tensorflow/tensorflow/issues/22216) (issue #22216)

**Comment by tensorflowbutler** [comment]
Nagging Assignee @jpienaar: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by smit-hinsu** [comment]
Saw this issue while looking into #22216.

Seems like the suggestion in https://github.com/tensorflow/tensorflow/issues/22216#issuecomment-433159156 should apply here as well.

Closing this as well but let us know if I am mistaken.

**Comment by vishalsubbiah** [comment]
I don't think this has been resolved. 2 similar issues (the other can be seen [here](https://github.com/tensorflow/tensorflow/issues/22216#issuecomment-433562028)). So I think both should be reopened.

**Comment by hpucha** [comment]
To use xla.compile with the model from issue #22216, I'd recommend using the estimator_model_fn decorator as seen [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/compiler/xla.py#L606).

Note that this requires all variables to be resource variables.

Please let us know if you run into issues with this approach.

**Comment by vishalsubbiah** [comment]
in tf1.13 using dynamic_rnns use xla entirely :)
