### ISSUE TITLE
Unable to profile tf.keras Model. Am I missing something or is it a known issue?

### ISSUE THREAD

**Issue by Nithanaroy** [tensorflow/tensorflow#22121]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: RHEL 7
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: NA
- **TensorFlow installed from (source or binary)**: No
- **TensorFlow version (use command below)**: 1.9
- **Python version**: 2.7
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**: NA
- **Exact command to reproduce**: Below code

### Describe the problem
**tf.contrib.tfprof** does not profile tf.keras Model. Am I missing something or is it a known issue?

### Source code / logs
The goal is to find what % of total time is spent in the input pipeline (mostly IO) and what % of total time is spent on model training – ideally a chart like the one presented in the [Training Performance session](https://www.youtube.com/watch?v=SxOsJPaxHME&feature=youtu.be&t=977) at tf dev summit 2018.

**Model Training:**
```python
training_set = tfdata_generator_with_interleave([“f1.avro”, “f2.avro”, …], is_training=True, batch_size=512, preprocess_fn=preprocess_fn_dense)
validation_set = tfdata_generator_with_interleave([“f1_val.avro”, “f2_val.avro”, …], is_training=False, batch_size=512, preprocess_fn=preprocess_fn_dense)
model = my_tf_keras_dense_deep_model()
model.compile(loss='categorical_crossentropy', optimizer=”adam”, metrics=['accuracy'])

with tf.contrib.tfprof.ProfileContext( './profiles/dense_model’) ) as pctx:
   model.fit(
                training_set.make_one_shot_iterator(),
                steps_per_epoch=TOTAL_TRAIN_RECORDS // _BATCH_SIZE, # need this as we are feeding data using a generator
                epochs=_EPOCHS,
                validation_data= validation_set.make_one_shot_iterator(),
                validation_steps=TOTAL_TEST_RECORDS // _BATCH_SIZE,
                callbacks=[tensorboard])
```

**Input Pipeline:**
```python
def tfdata_generator_with_interleave(data_files, is_training, batch_size=128, preprocess_fn=preprocess_fn_dense):
    def wrap_generator(filename):
        return tf.data.Dataset.from_generator(read_local_avro_data_gen, (tf.float32, tf.float64),
                                              args=[filename, batch_size / 4])

    files = tf.data.Dataset.from_tensor_slices(data_files)
    dataset = files.apply(tf.contrib.data.parallel_interleave(wrap_generator, cycle_length=4, sloppy=True))
    dataset = dataset.flat_map(lambda *x: tf.data.Dataset.from_tensor_slices(x))

    if is_training:
        dataset = dataset.apply(tf.contrib.data.shuffle_and_repeat(1000, -1, 42))

    dataset = dataset.apply(tf.contrib.data.map_and_batch(preprocess_fn, batch_size,
                                                          num_parallel_batches=num_parallel_data_fetch,
                                                          drop_remainder=True if is_training else False)
                            )

    dataset = dataset.prefetch(tf.contrib.data.AUTOTUNE)
    return dataset
```

But I do not see any files to load into tensorboard or chrome in ./profiles directory. Does the profile not work with tf.keras models? Or Am I missing any setup?

Also tried contacting the email address mentioned on the [Profiler README](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/profiler/README.md) - xpan@google.com, but message sending failed.

**Comment by carrondt** [comment]
@Nithanaroy just a comment, because I am wondering about the same thing, is that if you include the trace_steps and dump_steps parameters with ProfileContext initialization then you can get some output. I also saw no output without them.

also, there is a report of no output for the later versions of keras: https://github.com/keras-team/keras/issues/10880#issuecomment-419377716

**Comment by tensorflowbutler** [comment]
Nagging Assignee @cy89: It has been 18 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @cy89: It has been 33 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @cy89: It has been 48 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @cy89: It has been 63 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @cy89: It has been 78 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by ChriPo92** [comment]
I had the same problem, but it actually created the profile after the epoch was done. If this does not work you can also use the python API entirely. Something like this might work for you:
```
run_options = tf.RunOptions(trace_level=tf.RunOptions.FULL_TRACE)
run_metadata = tf.RunMetadata()
ProfileOptionBuilder = tf.profiler.ProfileOptionBuilder
opts = ProfileOptionBuilder(ProfileOptionBuilder.time_and_memory()
                                    ).with_node_names(show_name_regexes=['.*']).build()
## model is some keras.models.Model instance
model.compile(
            ...,
            options=run_options,
            run_metadata=run_metadata
        )
### train model, or something else which calls tf.Session.run()
tf.profiler.profile(keras.backend.get_session().graph, run_metadata, cmd="code", options=opts)
```
or if you want to have multiple steps and save the profiling data (for example to open it with the ProfilerUI):
```
prof = tf.profiler.Profiler(graph=keras.backend.get_session().graph)
### train model, or something else which calls tf.Session.run()
prof.add_step(1, run_metadata)
### train model, or something else which calls tf.Session.run()
prof.add_step(1, run_metadata)
### continue as long as you want
with open('./profile', 'wb') as f:
    f.write(prof.serialize_to_string())
```

**Comment by parvjainmetal** [comment]
--------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py in <module>
     57 
---> 58   from tensorflow.python.pywrap_tensorflow_internal import *
     59   from tensorflow.python.pywrap_tensorflow_internal import __version__

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py in <module>
     27             return _mod
---> 28     _pywrap_tensorflow_internal = swig_import_helper()
     29     del swig_import_helper

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py in swig_import_helper()
     23             try:
---> 24                 _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
     25             finally:

C:\ProgramData\Anaconda3\lib\imp.py in load_module(name, file, filename, details)
    242         else:
--> 243             return load_dynamic(name, filename, file)
    244     elif type_ == PKG_DIRECTORY:

C:\ProgramData\Anaconda3\lib\imp.py in load_dynamic(name, path, file)
    342             name=name, loader=loader, origin=path)
--> 343         return _load(spec)
    344 

ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-10-78121b9dd84b> in <module>
----> 1 from keras import layers, models, optimizers

C:\ProgramData\Anaconda3\lib\site-packages\keras\__init__.py in <module>
      1 from __future__ import absolute_import
      2 
----> 3 from . import utils
      4 from . import activations
      5 from . import applications

C:\ProgramData\Anaconda3\lib\site-packages\keras\utils\__init__.py in <module>
      4 from . import data_utils
      5 from . import io_utils
----> 6 from . import conv_utils
      7 
      8 # Globally-importable utils.

C:\ProgramData\Anaconda3\lib\site-packages\keras\utils\conv_utils.py in <module>
      7 from six.moves import range
      8 import numpy as np
----> 9 from .. import backend as K
     10 
     11 

C:\ProgramData\Anaconda3\lib\site-packages\keras\backend\__init__.py in <module>
     87 elif _BACKEND == 'tensorflow':
     88     sys.stderr.write('Using TensorFlow backend.\n')
---> 89     from .tensorflow_backend import *
     90 else:
     91     # Try and load external backend.

C:\ProgramData\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py in <module>
      3 from __future__ import print_function
      4 
----> 5 import tensorflow as tf
      6 from tensorflow.python.framework import ops as tf_ops
      7 from tensorflow.python.training import moving_averages

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\__init__.py in <module>
     22 
     23 # pylint: disable=g-bad-import-order
---> 24 from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
     25 
     26 try:

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\__init__.py in <module>
     47 import numpy as np
     48 
---> 49 from tensorflow.python import pywrap_tensorflow
     50 
     51 from tensorflow.python.tools import component_api_helper

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py in <module>
     72 for some common reasons and solutions.  Include the entire stack trace
     73 above this error message when asking for help.""" % traceback.format_exc()
---> 74   raise ImportError(msg)
     75 
     76 # pylint: enable=wildcard-import,g-import-not-at-top,unused-import,line-too-long

ImportError: Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\ProgramData\Anaconda3\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\ProgramData\Anaconda3\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
