### ISSUE TITLE
How to classify an image with the trained cifar10 model?

### ISSUE THREAD

**Issue by yhlleo** [tensorflow/tensorflow#2215]
After trained a cifar10 model, I want to test the model with a image. There are some other people trying to make it, but it's still a confusing question. My test code is presented, as follows:

    from datetime import datetime
    import math
    import time
    
    import numpy as np
    import tensorflow as tf
    import cifar10
    
    FLAGS = tf.app.flags.FLAGS
    
    tf.app.flags.DEFINE_string('checkpoint_dir', 'cifar10_train/',
                               """Directory where to read model checkpoints.""")
    
    
    def  evaluate_images(images):
      logit = cifar10.inference(images)
      load_trained_model(logit)
    
    def load_trained_model(logits):
      with tf.Session() as sess:
        sess.run(tf.initialize_all_variables())
        ckpt = tf.train.get_checkpoint_state(FLAGS.checkpoint_dir)
        if ckpt and ckpt.model_checkpoint_path:
          # Restores from checkpoint
          saver.restore(sess, ckpt.model_checkpoint_path)
        else:
          print('No checkpoint file found')
          return
    
        predict = tf.argmax(logits,1)
        print(predict.eval(), '\n')
    
    def img_read(filename):
      if not tf.gfile.Exists(filename):
        tf.logging.fatal('File does not exists %s', filename)
      image_data = tf.gfile.FastGFile(filename, 'rb').read()
      image = tf.cast(image_data, tf.float32)
      return image
     
    filename = '1.png'
    images = img_read(filename)
    evaluate_images(images)

But it occurs the bug: 

    File "/home/swoda/tensorflow/tensorflow/models/image/cifar10/cifar10.py", line 192, in inference
        conv = tf.nn.conv2d(images, kernel, [1, 1, 1, 1], padding='SAME')
      File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_nn_ops.py", line 295, in conv2d
        data_format=data_format, name=name)
      File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/op_def_library.py", line 655, in apply_op
        op_def=op_def)
      File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2156, in create_op
        set_shapes_for_outputs(ret)
      File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1612, in set_shapes_for_outputs
        shapes = shape_func(op)
      File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/common_shapes.py", line 202, in conv2d_shape
        input_shape = op.inputs[0].get_shape().with_rank(4)
      File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_shape.py", line 625, in with_rank
        raise ValueError("Shape %s must have rank %d" % (self, rank))
    ValueError: Shape () must have rank 4

If you know how to fix this problem, please tell me. Thank you very much!

**Comment by girving** [comment]
The network expects a batch of images, so add `tf.expand_dims(image, -1)`.

**Comment by danleh93** [comment]
Did the `tf.expand_dims(image, -1)` ever solve the problem? I tried that workaround writing `image = tf.expand_dims(tf.cast(image_data, tf.float32), -1)`, but now the error is:

> File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_shape.py", line 625, in with_rank
>     raise ValueError("Shape %s must have rank %d" % (self, rank))
> ValueError: Shape (1,) must have rank 4

**Comment by apiszcz** [comment]
This may be work.
img = tf.reshape(img, (1,32,32,3))

**Comment by hungpt297** [comment]
I fixed @yhlleo script as follow

`from datetime import datetime
import math
import time

import numpy as np
import tensorflow as tf
import cv2
import acr

FLAGS = tf.app.flags.FLAGS

tf.app.flags.DEFINE_string('checkpoint_dir', 'cifar10_train/',
                            """Directory where to read model checkpoints.""")


def evaluate_images(images):
    logit = acr.inference(images)
    load_trained_model(logit, images)

def load_trained_model(logits, images):
    saver = tf.train.Saver()
    with tf.Session() as sess:
        sess.run(tf.global_variables_initializer())
        ckpt = tf.train.get_checkpoint_state(FLAGS.checkpoint_dir)
        if ckpt and ckpt.model_checkpoint_path:
            # Restores from checkpoint
            saver.restore(sess, ckpt.model_checkpoint_path)
        else:
            print('No checkpoint file found')
            return

        predict = tf.argmax(logits, 1)
        print(predict.eval(), '\n')

def img_read(filename):
    if not tf.gfile.Exists(filename):
        tf.logging.fatal('File does not exists %s', filename)
    image = cv2.imread(filename)
    image = tf.cast(image, tf.float32)
    image = tf.reshape(image, (1, 32, 32, 3))
    print(image)
    return image

filename = 'test/6_00001.jpg'
images = img_read(filename)
evaluate_images(images)
`
But it occurs the bug:
`Traceback (most recent call last):
  File "cifar10_predict.py", line 50, in <module>
    evaluate_images(images)
  File "cifar10_predict.py", line 18, in evaluate_images
    load_trained_model(logit, images)
  File "cifar10_predict.py", line 27, in load_trained_model
    saver.restore(sess, ckpt.model_checkpoint_path)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1388, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 766, in run
    run_metadata_ptr)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 964, in _run
    feed_dict_string, options, run_metadata)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1014, in _do_run
    target_list, options, run_metadata)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1034, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [32,384] rhs shape= [4096,384]
         [[Node: save/Assign_5 = Assign[T=DT_FLOAT, _class=["loc:@local3/weights"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/cpu:0"](local3/weights, save/RestoreV2_5)]]

Caused by op u'save/Assign_5', defined at:
  File "cifar10_predict.py", line 50, in <module>
    evaluate_images(images)
  File "cifar10_predict.py", line 18, in evaluate_images
    load_trained_model(logit, images)
  File "cifar10_predict.py", line 21, in load_trained_model
    saver = tf.train.Saver()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1000, in __init__
    self.build()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1030, in build
    restore_sequentially=self._restore_sequentially)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 624, in build
    restore_sequentially, reshape)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 373, in _AddRestoreOps
    assign_ops.append(saveable.restore(tensors, shapes))
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 130, in restore
    self.op.get_shape().is_fully_defined())
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/ops/gen_state_ops.py", line 47, in assign
    use_locking=use_locking, name=name)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 759, in apply_op
    op_def=op_def)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2240, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1128, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [32,384] rhs shape= [4096,384]
         [[Node: save/Assign_5 = Assign[T=DT_FLOAT, _class=["loc:@local3/weights"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/cpu:0"](local3/weights, save/RestoreV2_5)]]`

How to fix it. Thank you very much!

**Comment by wangtianrui** [comment]
use tf.train.shuffle_batch() to change image into [1,size,size,3] and change batch_size to 1 can solve this bug

**Comment by xzy256** [comment]
@yhlleo  Have fixed the bug? How to run this case, as if it has not a main function. By the way, do you have the complete code?
