### ISSUE TITLE
TENSORFLOW ISSUES 

### ISSUE THREAD

**Issue by acsy0802** [tensorflow/tensorflow#22165]
I've been trying to install TensorFlow for the past few hours and keep getting this error:
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 812, in __call__
        return func(*args, **kwargs)
      File "/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 78, in _main
        exit_code = do_call(args, p)
      File "/anaconda2/lib/python2.7/site-packages/conda/cli/conda_argparse.py", line 77, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/anaconda2/lib/python2.7/site-packages/conda/cli/main_install.py", line 11, in execute
        install(args, parser, 'install')
      File "/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 253, in install
        handle_txn(unlink_link_transaction, prefix, args, newenv)
      File "/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 269, in handle_txn
        unlink_link_transaction.print_transaction_summary()
      File "/anaconda2/lib/python2.7/site-packages/conda/core/link.py", line 730, in print_transaction_summary
        legacy_action_groups = self._make_legacy_action_groups()
      File "/anaconda2/lib/python2.7/site-packages/conda/core/link.py", line 713, in _make_legacy_action_groups
        self._pfe.prepare()
      File "/anaconda2/lib/python2.7/site-packages/conda/common/io.py", line 46, in decorated
        return f(*args, **kwds)
      File "/anaconda2/lib/python2.7/site-packages/conda/core/package_cache_data.py", line 561, in prepare
        for prec in self.link_precs)
      File "/anaconda2/lib/python2.7/_abcoll.py", line 571, in update
        for key, value in other:
      File "/anaconda2/lib/python2.7/site-packages/conda/core/package_cache_data.py", line 561, in <genexpr>
        for prec in self.link_precs)
      File "/anaconda2/lib/python2.7/site-packages/conda/core/package_cache_data.py", line 454, in make_actions_for_record
        ), None)
      File "/anaconda2/lib/python2.7/site-packages/conda/core/package_cache_data.py", line 451, in <genexpr>
        pcrec for pcrec in concat(PackageCacheData(pkgs_dir).query(pref_or_spec)
      File "/anaconda2/lib/python2.7/site-packages/conda/core/package_cache_data.py", line 452, in <genexpr>
        for pkgs_dir in context.pkgs_dirs)
      File "/anaconda2/lib/python2.7/site-packages/conda/core/package_cache_data.py", line 125, in query
        return (pcrec for pcrec in itervalues(self._package_cache_records) if pcrec == param)
      File "/anaconda2/lib/python2.7/site-packages/conda/core/package_cache_data.py", line 221, in _package_cache_records
        self.load()
      File "/anaconda2/lib/python2.7/site-packages/conda/core/package_cache_data.py", line 91, in load
        package_cache_record = self._make_single_record(base_name)
      File "/anaconda2/lib/python2.7/site-packages/conda/core/package_cache_data.py", line 350, in _make_single_record
        md5 = compute_md5sum(package_tarball_full_path)
      File "/anaconda2/lib/python2.7/site-packages/conda/gateways/disk/read.py", line 71, in compute_md5sum
        return _digest_path('md5', file_full_path)
      File "/anaconda2/lib/python2.7/site-packages/conda/gateways/disk/read.py", line 64, in _digest_path
        with open(path, "rb") as fh:
      File "/anaconda2/lib/python2.7/site-packages/conda/common/compat.py", line 121, in open
        errors=errors, newline=newline, closefd=closefd)
    IOError: [Errno 13] Permission denied: '/anaconda2/pkgs/pyspark-2.3.0-py27_0.tar.bz2'

`$ /anaconda2/bin/conda install tensorflow`

  environment variables:
                 CIO_TEST=<not set>
               CONDA_ROOT=/anaconda2
                     PATH=/Library/Frameworks/Python.framework/Versions/3.7/bin:/anaconda2/bin:/
                          Users/asy/Downloads/google-cloud-sdk/bin:/usr/local/bin:/usr/bin:/bin:
                          /usr/sbin:/sbin:/Library/TeX/texbin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
       user config file : /Users/asy/.condarc
 populated config files : /Users/asy/.condarc
          conda version : 4.5.0
    conda-build version : 3.0.27
         python version : 2.7.14.final.0
       base environment : /anaconda2  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/osx-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /anaconda2/pkgs
                          /Users/asy/.conda/pkgs
       envs directories : /anaconda2/envs
                          /Users/asy/.conda/envs
               platform : osx-64
             user-agent : conda/4.5.0 requests/2.18.4 CPython/2.7.14 Darwin/16.7.0 OSX/10.12.6
                UID:GID : 301705310:285281272
             netrc file : None
           offline mode : False

 This is what happens when I go down the conda route. 

When I go through the pip route,  this happens: 

Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: u'/private/var/folders/k7/xthqkfr968g8c83fbtdm1jfc8zq_2y/T/pip-unpack-yhcLfC/tensorflow-1.10.1-cp27-cp27m-macosx_10_11_x86_64.whl'
Consider using the `--user` option or check the permissions. 

Please assist.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by robieta** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
