### ISSUE TITLE
Java version at Maven Central is built for CUDA 0.9 (==a bit too old)

### ISSUE THREAD

**Issue by okdzhimiev** [tensorflow/tensorflow#22202]
I have **libcublas.so.9.2** installed.
Please, update. And make it somewhat usable if possible.
Many thanks.

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: /tmp/tensorflow_native_libraries-1536621740227-0/libtensorflow_jni.so: libcublas.so.9.0: cannot open shared object file: No such file or directory
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at org.tensorflow.NativeLibrary.load(NativeLibrary.java:101)
	at org.tensorflow.TensorFlow.init(TensorFlow.java:66)
	at org.tensorflow.TensorFlow.<clinit>(TensorFlow.java:70)
	at org.tensorflow.Graph.<clinit>(Graph.java:337)
	at TensorflowExamplePlugin.main(TensorflowExamplePlugin.java:25)
	at TensorflowExamplePlugin.run(TensorflowExamplePlugin.java:17)
```

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by okdzhimiev** [comment]
You're welcome.
> Have I written custom code
No, testing HelloTF.java from [here](https://www.tensorflow.org/install/install_java) TF GPU for Java.
> OS Platform and Distribution
Kubuntu 16.04 64x
> TensorFlow installed from
https://mvnrepository.com/artifact/org.tensorflow/libtensorflow_jni_gpu ?
> TensorFlow version
1.10.0
> Bazel version
N/A
> CUDA/cuDNN version
0.9.2
> GPU model and memory
GeForce GTX 750 Ti
> Exact command to reproduce
N/A
> Mobile device
N/A

Thanks
