### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError: No registered 'Empty' OpKernel for XLA_CPU devices compatible with node Empty

### ISSUE THREAD

**Issue by vishalsubbiah** [tensorflow/tensorflow#22216]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Centos 7.4.1708
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: NA
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 1.10
- **Python version**: 3.4.5
- **Bazel version (if compiling from source)**: 0.16
- **GCC/Compiler version (if compiling from source)**: 4.8.5
- **CUDA/cuDNN version**: NA
- **GPU model and memory**: NA
- **Exact command to reproduce**: NA

### Describe the problem
I am trying to run a char_rnn model on a TPU. To do so I am using 
tf.contrib.recurrent.functional_rnn. It runs successfully on CPU. When I change it to XLA_CPU I am running into the error mentioned in the title. I built from source, and the XLA_CPU works well for my other models. 
```
tensorflow.python.framework.errors_impl.NotFoundError: No registered 'Empty' OpKernel for XLA_CPU devices compatible with node Empty = Empty[dtype=DT_FLOAT, init=true, _device="/job:localhost/replica:0/task:0/device:XLA_CPU:0"](concat)
	.  Registered:  device='CPU'; dtype in [DT_UINT8]
  device='CPU'; dtype in [DT_BOOL]
  device='CPU'; dtype in [DT_INT64]
  device='CPU'; dtype in [DT_INT32]
  device='CPU'; dtype in [DT_STRING]
  device='CPU'; dtype in [DT_HALF]
  device='CPU'; dtype in [DT_DOUBLE]
  device='CPU'; dtype in [DT_FLOAT]

	 [[Node: Empty = Empty[dtype=DT_FLOAT, init=true, _device="/job:localhost/replica:0/task:0/device:XLA_CPU:0"](concat)]]
	 [[Node: test_conv/Forward_eNPkQVpjczA = Forward_eNPkQVpjczA[_device="/job:localhost/replica:0/task:0/device:XLA_CPU:0"](cluster_30/_6/_7, cluster_31/_2/_3, cluster_28/_10/_11, cluster_28/_10/_11, cluster_26/_14/_15, cluster_29/_8/_9/_69)]]
	 [[Node: cluster_27/_12/_13/_74 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:XLA_CPU:0", send_device_incarnation=1, tensor_name="edge_68_cluster_27/_12/_13", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
````

**Comment by reedwm** [comment]
Can you give a self-contained example to reproduce the issue? And the stacktrace of the error?

**Comment by vishalsubbiah** [comment]
This is the input for the code
[input.txt](https://github.com/tensorflow/tensorflow/files/2416432/input.txt)

The code is:
```
import tensorflow as tf
import numpy as np
import os
import argparse
from tensorflow.python.estimator import run_config
from tensorflow.python.ops.rnn import _transpose_batch_time
from tensorflow.python.training import training

BATCH_SIZE = 64
SEQ_LENGTH = 32
NUM_BATCHES = 1

def file_to_input_data(file, seq_length):
    """
    Reads file, divides into train, validation, test sets and returns the
    corresponding input source arrays
    """
    with open(file, 'r') as f:
        data = f.read()

    char_array = np.array(list(data))
    char_list, mapped_array = np.unique(char_array, return_inverse=True)

    char_map = {c: i for i, c in enumerate(char_list)}
    indices_char = {i: c for i, c in enumerate(char_list)}

    num_unique_chars = char_list.shape[0]
    dataset_size = mapped_array.shape[0]

    # create the partitions
    val_start = int(0.7 * dataset_size)
    test_start = int(0.8 * dataset_size)
    train_data, val_data, test_data = np.array_split(mapped_array,
                                                     [val_start, test_start])

    # truncate into multiple of seq length
    def _truncate(x):
        return x[:(x.shape[0] // seq_length) * seq_length]

    return {
        "train": _truncate(train_data),
        "val": _truncate(val_data),
        "test": _truncate(test_data),
        "vocab_size": num_unique_chars,
        "char_map": char_map,
        "indices_char": indices_char
    }

def shifted(x, value=0):
    '''
    returns target for a given linear sequence, x
    '''
    print(x.shape)

    return np.append(x[1:],0)#np.pad(x[:-1], (1, 0), "constant", constant_values=value)


def data_from_file(file, seq_length):
    """Takes params, file, converts to one hot numpy arrays
    and returns x, y, and vocab_size"""
    text = open(file).read()[:10000] # for debugging
    print("Corpus len:", len(text))
    chars = sorted(list(set(text)))
    vocab_size = len(chars)
    print('total chars:', len(chars))
    char_indices = dict((c, i) for i, c in enumerate(chars))
    indices_char = dict((i, c) for i, c in enumerate(chars))
    sentences = []
    next_chars = []
    for i in range(0, len(text)-seq_length, 2):
        sentences.append(text[i:i+seq_length]) #"the cat in the ha"
        next_chars.append(text[i+seq_length])     #"t"
    print("Vectorization...")
    x = np.zeros((len(sentences), seq_length, vocab_size), dtype=np.float32)
    y = np.zeros((len(sentences), vocab_size), dtype=np.float32)
    for i, sentence in enumerate(sentences):
        for t, char in enumerate(sentence):
            x[i, t, char_indices[char]] = 1
        y[i, char_indices[next_chars[i]]] = 1
    return {'x':x, 'y':y, 'vocab_size':vocab_size,'indices_char':indices_char,'char_indices':char_indices,'text':text}


def input_fn(params, mode):
    batch_size = params.get('batch_size', BATCH_SIZE)
    seq_length = params.get('seq_length', SEQ_LENGTH)
    char_indices = params.get('char_indices', None)
    num_classes = params.get('num_classes', None)
    if mode == tf.estimator.ModeKeys.TRAIN:
        x = params.get('x', None)#[:32000]  #[:batch_size*NUM_BATCHES]
        #print("X SHAPE", x.shape)
        y = params.get('y', None) #size: (4984, 57) for 10,000 char sample
        repeat_count = None
    elif mode == tf.estimator.ModeKeys.EVAL:
        data_source = params.get('val_data', None)
        repeat_count = 1
    elif mode == tf.estimator.ModeKeys.PREDICT:
        sentence = params.get('seed_text')
        char_indices = params.get('char_indices')


        x = np.zeros((len(sentence)//seq_length, seq_length, num_classes), dtype=np.float32)
        for t, char in enumerate(sentence):
            x[0, t, char_indices[char]] = 1


        #print("X SHAPE: ", x.shape)
        ds = tf.data.Dataset.from_tensor_slices(x)
        ds = ds.apply(tf.contrib.data.batch_and_drop_remainder(1))
        return ds

    assert x is not None, "Must supply the data"

    ds = tf.data.Dataset.from_tensor_slices((x, y))
    ds = ds.repeat(repeat_count)
    ds = ds.apply(tf.contrib.data.batch_and_drop_remainder(batch_size))

    return ds


def lstm_model_fn(features, labels, mode, params):
    """ Basic RNN that uses LSTM Cells
    features = input_tensors: one-hot tensors encoding the chars
    mode: instance of tf.estimator.ModeKeys (e.g. ModeKeys.TRAIN)
    rnn_type = GRU, LSTM, BasicRNN
    params: dict specifying [learning_rate, seq_length, hidden_units]"""

    with tf.device("/job:localhost/replica:0/task:0/device:XLA_CPU:0"):
        with tf.variable_scope("test_rnn", use_resource=True):
            num_classes = params.get("num_classes")
            batch_size = params.get('batch_size', BATCH_SIZE)
            state_size = params.get("state_size", 128)
            seq_length = params.get("seq_length", SEQ_LENGTH)

        #     labels = tf.Print(labels, [labels, tf.shape(labels), "LABELS SHAPE"])

            # input tensors need to be [batch_size x sentence_size x vocab_size]
            #lstm_cell = tf.nn.rnn_cell.LSTMCell(state_size,name="lstm_cell",reuse=tf.AUTO_REUSE)#tf.nn.rnn_cell.BasicLSTMCell(state_size)
            lstm_cell = tf.nn.rnn_cell.BasicRNNCell(state_size,name="lstm_cell",reuse=tf.AUTO_REUSE)
            initial_state = lstm_cell.zero_state(batch_size, dtype=tf.float32)
            logits = None
            predictions = None

            if mode != tf.estimator.ModeKeys.PREDICT:
                inputs=features
                outputs,final_state=tf.contrib.recurrent.functional_rnn(cell=lstm_cell,
                            inputs=inputs,initial_state=initial_state,scope="func",
                            sequence_length=seq_length,
                            dtype= tf.float32)
                #outputs = outputs_ta#.stack()

                #outputs = _transpose_batch_time(outputs)
        #         outputs = tf.Print(outputs, [outputs, tf.shape(outputs), "outputs SHAPE"])
                with tf.variable_scope("rnn_final",use_resource=True): #to allow prediction to call same function
                    logits = tf.layers.dense(
                        outputs, num_classes, name="final_layer") #tf.reshape(outputs, [-1 , state_size])

                logit_loss = logits[:,-1,:] #(64, 57) gets the prediction from the whole sequence
                logit_loss = tf.reshape(logit_loss, (batch_size, num_classes))


                predictions = tf.argmax(logits, axis=1,name="predictions")

            elif mode == tf.estimator.ModeKeys.PREDICT:
                seed_length = len(params.get('seed_text'))
                target_length = params.get('target_length')
                inputs = features

                outputs_ta,final_state=tf.contrib.recurrent.functional_rnn(lstm_cell,inputs,initial_state=initial_state,scope="func")
                predictions = outputs_ta.stack()

                predictions = tf.Print(predictions, [predictions[90], "PREDICTIONS"])
                return tf.estimator.EstimatorSpec(mode, predictions=predictions)

            loss = tf.reduce_mean(
                    tf.nn.softmax_cross_entropy_with_logits(
                    logits=logit_loss, labels=labels)) #tf.reshape(labels, [-1]))

            optimizer = tf.train.MomentumOptimizer(learning_rate=0.15, momentum=0.97)

            train_op = optimizer.minimize(loss, global_step=tf.train.get_global_step())

            if mode == tf.estimator.ModeKeys.TRAIN:
                return tf.estimator.EstimatorSpec(
                    mode=mode, loss=loss, train_op=train_op)
            elif mode == tf.estimator.ModeKeys.EVAL:
                return tf.estimator.EstimatorSpec(mode=mode, loss=loss, eval_metric_ops=metrics)

if __name__ == "__main__":
    tf.logging.set_verbosity(tf.logging.INFO)
    parser = argparse.ArgumentParser()
    parser.add_argument(
        '--train_file',
        type=str,
        default=os.path.expanduser("./input.txt"),
        help='where pre-processed data is stored')
    parser.add_argument(
        '--mode',
        type=str,
        default='train',
        help='train, eval, or predict')
    parser.add_argument(
        '--num_states', type=int, default=128, help='size of each rnn layer')
    parser.add_argument(
        '--seed_text', type=str, default="The Volsces have much corn; take", help='seed for prediction mode')
    parser.add_argument(
        '--target_length', type=int, default=100, help='the output length of your given prediction')
    parser.add_argument(
        '--seq_length', type=int, default=SEQ_LENGTH, help='number of unrolled time steps')
    parser.add_argument(
        '--num_steps', type=int, default=10, help='number of training steps')
    parser.add_argument(
        '--batch_size', type=int, default=BATCH_SIZE, help="samples per batch")
    args = parser.parse_args()

    data = data_from_file(args.train_file, seq_length=args.seq_length)

    classifier = tf.estimator.Estimator(
        model_fn=lstm_model_fn,
        params={
            'num_classes': data["vocab_size"],
            'state_size': args.num_states,
            'batch_size': args.batch_size,
            'seq_length': args.seq_length,
            'x': data["x"],
            'y': data['y'],
            'char_indices': data["char_indices"],
            'seed_text': args.seed_text,
            'target_length': args.target_length,
        },
        config=run_config.RunConfig(
            save_summary_steps=10,
            save_checkpoints_steps=100,
            model_dir="./model"))

    classifier.train(input_fn, steps=args.num_steps)
```



this is the stacktrace of the error: 
```
2018-09-25 10:54:39.604560: E tensorflow/core/common_runtime/executor.cc:697] Executor failed to create kernel. Not found: No registered 'Empty' OpKernel for XLA_CPU devices compatible with node Empty = Empty[dtype=DT_FLOAT, init=true, _device="/job:localhost/replica:0/task:0/device:XLA_CPU:0"](concat)
	.  Registered:  device='CPU'; dtype in [DT_UINT8]
  device='CPU'; dtype in [DT_BOOL]
  device='CPU'; dtype in [DT_INT64]
  device='CPU'; dtype in [DT_INT32]
  device='CPU'; dtype in [DT_STRING]
  device='CPU'; dtype in [DT_HALF]
  device='CPU'; dtype in [DT_DOUBLE]
  device='CPU'; dtype in [DT_FLOAT]

	 [[Node: Empty = Empty[dtype=DT_FLOAT, init=true, _device="/job:localhost/replica:0/task:0/device:XLA_CPU:0"](concat)]]
Traceback (most recent call last):
  File "/net/server5/srv/nfs/vishal-data/ws/venv_tf110/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 1278, in _do_call
    return fn(*args)
  File "/net/server5/srv/nfs/vishal-data/ws/venv_tf110/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 1263, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/net/server5/srv/nfs/vishal-data/ws/venv_tf110/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 1350, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: No registered 'Empty' OpKernel for XLA_CPU devices compatible with node Empty = Empty[dtype=DT_FLOAT, init=true, _device="/job:localhost/replica:0/task:0/device:XLA_CPU:0"](concat)
	.  Registered:  device='CPU'; dtype in [DT_UINT8]
  device='CPU'; dtype in [DT_BOOL]
  device='CPU'; dtype in [DT_INT64]
  device='CPU'; dtype in [DT_INT32]
  device='CPU'; dtype in [DT_STRING]
  device='CPU'; dtype in [DT_HALF]
  device='CPU'; dtype in [DT_DOUBLE]
  device='CPU'; dtype in [DT_FLOAT]

	 [[Node: Empty = Empty[dtype=DT_FLOAT, init=true, _device="/job:localhost/replica:0/task:0/device:XLA_CPU:0"](concat)]]
	 [[Node: test_rnn/Forward_MIH5xlXOmdc = Forward_MIH5xlXOmdc[_device="/job:localhost/replica:0/task:0/device:XLA_CPU:0"](cluster_30/_4/_5, cluster_31/_2/_3, cluster_28/_8/_9, cluster_26/_12/_13, cluster_29/_6/_7/_69)]]
	 [[Node: cluster_27/_10/_11/_74 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:XLA_CPU:0", send_device_incarnation=1, tensor_name="edge_63_cluster_27/_10/_11", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "basic_rnn.py", line 236, in <module>
    classifier.train(input_fn, steps=args.num_steps)
  File "/net/server5/srv/nfs/vishal-data/ws/venv_tf110/lib/python3.4/site-packages/tensorflow/python/estimator/estimator.py", line 376, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/net/server5/srv/nfs/vishal-data/ws/venv_tf110/lib/python3.4/site-packages/tensorflow/python/estimator/estimator.py", line 1145, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/net/server5/srv/nfs/vishal-data/ws/venv_tf110/lib/python3.4/site-packages/tensorflow/python/estimator/estimator.py", line 1173, in _train_model_default
    saving_listeners)
  File "/net/server5/srv/nfs/vishal-data/ws/venv_tf110/lib/python3.4/site-packages/tensorflow/python/estimator/estimator.py", line 1451, in _train_with_estimator_spec
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/net/server5/srv/nfs/vishal-data/ws/venv_tf110/lib/python3.4/site-packages/tensorflow/python/training/monitored_session.py", line 583, in run
    run_metadata=run_metadata)
  File "/net/server5/srv/nfs/vishal-data/ws/venv_tf110/lib/python3.4/site-packages/tensorflow/python/training/monitored_session.py", line 1059, in run
    run_metadata=run_metadata)
  File "/net/server5/srv/nfs/vishal-data/ws/venv_tf110/lib/python3.4/site-packages/tensorflow/python/training/monitored_session.py", line 1150, in run
    raise six.reraise(*original_exc_info)
  File "/net/server5/srv/nfs/vishal-data/ws/venv_tf110/lib/python3.4/site-packages/six.py", line 693, in reraise
    raise value
  File "/net/server5/srv/nfs/vishal-data/ws/venv_tf110/lib/python3.4/site-packages/tensorflow/python/training/monitored_session.py", line 1135, in run
    return self._sess.run(*args, **kwargs)
  File "/net/server5/srv/nfs/vishal-data/ws/venv_tf110/lib/python3.4/site-packages/tensorflow/python/training/monitored_session.py", line 1207, in run
    run_metadata=run_metadata)
  File "/net/server5/srv/nfs/vishal-data/ws/venv_tf110/lib/python3.4/site-packages/tensorflow/python/training/monitored_session.py", line 987, in run
    return self._sess.run(*args, **kwargs)
  File "/net/server5/srv/nfs/vishal-data/ws/venv_tf110/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 877, in run
    run_metadata_ptr)
  File "/net/server5/srv/nfs/vishal-data/ws/venv_tf110/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 1100, in _run
    feed_dict_tensor, options, run_metadata)
  File "/net/server5/srv/nfs/vishal-data/ws/venv_tf110/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 1272, in _do_run
    run_metadata)
  File "/net/server5/srv/nfs/vishal-data/ws/venv_tf110/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 1291, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: No registered 'Empty' OpKernel for XLA_CPU devices compatible with node Empty = Empty[dtype=DT_FLOAT, init=true, _device="/job:localhost/replica:0/task:0/device:XLA_CPU:0"](concat)
	.  Registered:  device='CPU'; dtype in [DT_UINT8]
  device='CPU'; dtype in [DT_BOOL]
  device='CPU'; dtype in [DT_INT64]
  device='CPU'; dtype in [DT_INT32]
  device='CPU'; dtype in [DT_STRING]
  device='CPU'; dtype in [DT_HALF]
  device='CPU'; dtype in [DT_DOUBLE]
  device='CPU'; dtype in [DT_FLOAT]

	 [[Node: Empty = Empty[dtype=DT_FLOAT, init=true, _device="/job:localhost/replica:0/task:0/device:XLA_CPU:0"](concat)]]
	 [[Node: test_rnn/Forward_MIH5xlXOmdc = Forward_MIH5xlXOmdc[_device="/job:localhost/replica:0/task:0/device:XLA_CPU:0"](cluster_30/_4/_5, cluster_31/_2/_3, cluster_28/_8/_9, cluster_26/_12/_13, cluster_29/_6/_7/_69)]]
	 [[Node: cluster_27/_10/_11/_74 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:XLA_CPU:0", send_device_incarnation=1, tensor_name="edge_63_cluster_27/_10/_11", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
```

**Comment by tensorflowbutler** [comment]
Nagging Assignee @reedwm: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @reedwm: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by smit-hinsu** [comment]
Thanks for providing with a self-contained example to reproduce the issue. That's always useful!

'device:XLA_CPU:0' is used primarily for testing. Please take a look at https://www.tensorflow.org/performance/xla/jit for instructions on other ways to invoke XLA.

https://github.com/tensorflow/tensorflow/issues/17458 discusses this in more details.

Closing this issue but feel free to file a new issue in case you run into an actual bug after following the XLA guide.

**Comment by vishalsubbiah** [comment]
@smit-hinsu, thanks for the response, but this issues seems independent of how I invoke XLA, since the other ways suggested, would keep it on the cpu device instead of the xla_cpu device which kind of hides the problem but doesn't solve it for my use case. Ideally I would want the entire graph to run on xla_cpu(currently the only way it seems to work, is by moving the while loop to the cpu). I am not running on a distributed system, so the concerns raised in #17458 may not be applicable here.

**Comment by smit-hinsu** [comment]
Could you update the example reproducing the issue with either Session or Manual mode as described in https://www.tensorflow.org/extend/xla/jit? Or you could use xla.compile as suggested by @jpienaar in the #22102. See https://github.com/tensorflow/tensorflow/blob/8c33e02e66b936d947245e6a0943898b810b16c4/tensorflow/contrib/compiler/xla.py#L63

Thanks!

**Comment by vishalsubbiah** [comment]
I used the xla.compile as seen [here](https://github.com/tensorflow/tensorflow/issues/22102#issuecomment-428684652) 

The code I ran is : 
```
import tensorflow as tf
import numpy as np
import os
import argparse
from tensorflow.python.estimator import run_config
from tensorflow.python.ops.rnn import _transpose_batch_time
from tensorflow.python.training import training

from tensorflow.python import debug as tf_debug
hooks = [tf_debug.LocalCLIDebugHook()]



BATCH_SIZE = 64#64
SEQ_LENGTH = 32 #32
NUM_BATCHES = 1 #for testing on really small datasets


def data_from_file(file, seq_length):
    """Takes params, file, converts to one hot numpy arrays
    and returns x, y, and vocab_size"""
    text = open(file).read()[:10000] # for debugging
    print("Corpus len:", len(text))
    chars = sorted(list(set(text)))
    vocab_size = len(chars)
    print('total chars:', len(chars))
    char_indices = dict((c, i) for i, c in enumerate(chars))
    indices_char = dict((i, c) for i, c in enumerate(chars))
    sentences = []
    next_chars = []
    for i in range(0, len(text)-seq_length, 2):
        sentences.append(text[i:i+seq_length]) #"the cat in the ha"
        next_chars.append(text[i+seq_length])     #"t"
    print("Vectorization...")
    x = np.zeros((len(sentences), seq_length, vocab_size), dtype=np.float32)
    y = np.zeros((len(sentences), vocab_size), dtype=np.float32)
    for i, sentence in enumerate(sentences):
        for t, char in enumerate(sentence):
            x[i, t, char_indices[char]] = 1
        y[i, char_indices[next_chars[i]]] = 1
    return {'x':x, 'y':y, 'vocab_size':vocab_size,'indices_char':indices_char,'char_indices':char_indices,'text':text}


def input_fn(params, mode):
    batch_size = params.get('batch_size', BATCH_SIZE)
    seq_length = params.get('seq_length', SEQ_LENGTH)
    char_indices = params.get('char_indices', None)
    num_classes = params.get('num_classes', None)
    if mode == tf.estimator.ModeKeys.TRAIN:
        x = params.get('x', None)#[:32000]  #[:batch_size*NUM_BATCHES]
        #print("X SHAPE", x.shape)
        y = params.get('y', None) #size: (4984, 57) for 10,000 char sample
        repeat_count = None
    elif mode == tf.estimator.ModeKeys.EVAL:
        data_source = params.get('val_data', None)
        repeat_count = 1
    elif mode == tf.estimator.ModeKeys.PREDICT:
        sentence = params.get('seed_text')
        char_indices = params.get('char_indices')


        x = np.zeros((len(sentence)//seq_length, seq_length, num_classes), dtype=np.float32)
        for t, char in enumerate(sentence):
            x[0, t, char_indices[char]] = 1


        #print("X SHAPE: ", x.shape)
        ds = tf.data.Dataset.from_tensor_slices(x)
        ds=ds.batch(1)
        features,labels=ds.make_one_shot_iterator().get_next()
        #ds = ds.apply(tf.contrib.data.batch_and_drop_remainder(batch_size))
        return features,labels

    assert x is not None, "Must supply the data"
    #print("test1")
    ds = tf.data.Dataset.from_tensor_slices((x, y))
    ds = ds.repeat(repeat_count)
    #print("test2")
    ds=ds.batch(batch_size)
    #ds = ds.apply(tf.contrib.data.batch_and_drop_remainder(batch_size))
    features,labels=ds.make_one_shot_iterator().get_next()
    return features,labels


def lstm_model_fn(features, labels, mode, params):
    """ Basic RNN that uses LSTM Cells
    features = input_tensors: one-hot tensors encoding the chars
    mode: instance of tf.estimator.ModeKeys (e.g. ModeKeys.TRAIN)
    rnn_type = GRU, LSTM, BasicRNN
    params: dict specifying [learning_rate, seq_length, hidden_units]"""
    if True:
    #with tf.device("/job:localhost/replica:0/task:0/device:XLA_CPU:0"):
        with tf.variable_scope("test_conv", use_resource=True):
            num_classes = params.get("num_classes")
            batch_size = params.get('batch_size', BATCH_SIZE)
            state_size = params.get("state_size", 128)
            seq_length = params.get("seq_length", SEQ_LENGTH)

        #     labels = tf.Print(labels, [labels, tf.shape(labels), "LABELS SHAPE"])

            # input tensors need to be [batch_size x sentence_size x vocab_size]
            #lstm_cell = tf.nn.rnn_cell.LSTMCell(state_size,name="lstm_cell",reuse=tf.AUTO_REUSE)#tf.nn.rnn_cell.BasicLSTMCell(state_size)
            lstm_cell = tf.nn.rnn_cell.BasicRNNCell(state_size,name="lstm_cell",reuse=tf.AUTO_REUSE)
            initial_state = lstm_cell.zero_state(batch_size, dtype=tf.float32)
            logits = None
            predictions = None

            if mode != tf.estimator.ModeKeys.PREDICT:
                inputs=features
                outputs,final_state=tf.contrib.recurrent.functional_rnn(cell=lstm_cell,
                            inputs=inputs,initial_state=initial_state,scope="func",
                            sequence_length=seq_length,
                            dtype= tf.float32,use_tpu=True)
                #outputs = outputs_ta#.stack()

                #outputs = _transpose_batch_time(outputs)
        #         outputs = tf.Print(outputs, [outputs, tf.shape(outputs), "outputs SHAPE"])
                with tf.variable_scope("rnn_final",use_resource=True): #to allow prediction to call same function
                    logits = tf.layers.dense(
                        outputs, num_classes, name="final_layer") #tf.reshape(outputs, [-1 , state_size])

                logit_loss = logits[:,-1,:] #(64, 57) gets the prediction from the whole sequence
                logit_loss = tf.reshape(logit_loss, (batch_size, num_classes))


                predictions = tf.argmax(logits, axis=1,name="predictions")

            elif mode == tf.estimator.ModeKeys.PREDICT:
                seed_length = len(params.get('seed_text'))
                target_length = params.get('target_length')
                inputs = features

                outputs_ta,final_state=tf.contrib.recurrent.functional_rnn(lstm_cell,inputs,initial_state=initial_state,scope="func",use_tpu=True)
                predictions = outputs_ta.stack() #outputs of this are partly one-hot, partly log probs?


                predictions = tf.Print(predictions, [predictions[90], "PREDICTIONS"])
                return tf.estimator.EstimatorSpec(mode, predictions=predictions)

        #     acc_labels = tf.reshape(labels, [-1, 1]) #disabling accuracy since shapes mismatched
        #     accuracy = tf.metrics.accuracy(labels=acc_labels, predictions=predictions, name="acc_op")

            loss = tf.reduce_mean(
                    tf.nn.softmax_cross_entropy_with_logits(
                    logits=logit_loss, labels=labels)) #tf.reshape(labels, [-1]))

            optimizer = tf.train.MomentumOptimizer(learning_rate=0.15, momentum=0.97)
            #     optimizer = tf.train.AdamOptimizer(learning_rate=0.15)
            train_op = optimizer.minimize(loss, global_step=tf.train.get_global_step())

        #     metrics = {"accuracy": accuracy}
        #     tf.summary.scalar('accuracy', accuracy[1])

            #specify what to do with each mode
            if mode == tf.estimator.ModeKeys.TRAIN:
                return tf.estimator.EstimatorSpec(
                    mode=mode, loss=loss, train_op=train_op)
            elif mode == tf.estimator.ModeKeys.EVAL:
                return tf.estimator.EstimatorSpec(mode=mode, loss=loss, eval_metric_ops=metrics)



if __name__ == "__main__":
    tf.logging.set_verbosity(tf.logging.INFO)
    parser = argparse.ArgumentParser()
    parser.add_argument(
        '--train_file',
        type=str,
        default=os.path.expanduser("./input.txt"), #currently only works with 'input.txt'?
        help='where pre-processed data is stored')
    parser.add_argument(
        '--mode',
        type=str,
        default='train',
        help='train, eval, or predict')
    parser.add_argument(
        '--model_dir',
        type=str,
        default="/tmp/char_rnn",
        help='where to store model results')
    parser.add_argument(
        '--num_states', type=int, default=128, help='size of each rnn layer')
    parser.add_argument(
        '--seed_text', type=str, default="The Volsces have much corn; take", help='seed for prediction mode')
    parser.add_argument(
        '--target_length', type=int, default=100, help='the output length of your given prediction')
    parser.add_argument(
        '--seq_length', type=int, default=SEQ_LENGTH, help='number of unrolled time steps')
    parser.add_argument(
        '--num_steps', type=int, default=10, help='number of training steps')
    parser.add_argument(
        '--batch_size', type=int, default=BATCH_SIZE, help="samples per batch")
    args = parser.parse_args()

    data = data_from_file(args.train_file, seq_length=args.seq_length)
    #{'x':x, 'y':y, 'vocab_size':vocab_size,'indices_char':indices_char,'char_indices':char_indices,'text':text}

    classifier = tf.estimator.Estimator(
        model_fn=lstm_model_fn,
        params={
            'num_classes': data["vocab_size"],
            'state_size': args.num_states,
            'batch_size': args.batch_size,
            'seq_length': args.seq_length,
            'x': data["x"],
            'y': data['y'],
            'char_indices': data["char_indices"],
            'seed_text': args.seed_text,
            'target_length': args.target_length,
        },
        config=run_config.RunConfig(
            save_summary_steps=10,
            save_checkpoints_steps=100,
            model_dir="./model"))



from tensorflow.contrib.compiler.xla import compile

def run(features,labels):
    mode=tf.estimator.ModeKeys.TRAIN
    params=classifier.params
    net=lstm_model_fn(features, labels, mode, params)
    graph = tf.get_default_graph()
    list_tensors=[]
    for op in graph.get_operations():
        if(len(op.values())>0):
            list_tensors.append(op.values()[0])

    return list_tensors+tf.get_default_graph().get_operations()

features,labels=input_fn(classifier.params,tf.estimator.ModeKeys.TRAIN)
#features,labels=csv_input_fn(train_path, train_batch_size)
result=compile(run,inputs=[features,labels])

with tf.Session() as sess:
   sess.run(tf.global_variables_initializer())
   sess.run(result)
```

Hope this helps

**Comment by smit-hinsu** [comment]
Thanks for the updated code.

I will assign this to @jpienaar for triage.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @jpienaar: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by vishalsubbiah** [comment]
in tf1.13 using dynamic_rnns use xla entirely :)
