### ISSUE TITLE
Eeager Mode:sigmoid_cross_entropy_with_logits expects int32 but not float tensor

### ISSUE THREAD

**Issue by Paul0M** [tensorflow/tensorflow#22224]
### System information
OS: ubuntu 1604
Virtual Env:Conda
TF Version:1.10
Python:3.6.6

```python
tfe = tf.contrib.eager
def loss(inputs, labels):
    print(labels.dtype)
    logits = model(inputs, training=True)
    print(logits.dtype)
    return tf.reduce_mean(
      tf.nn.sigmoid_cross_entropy_with_logits(
        logits=logits,
        labels=labels)
    )

val_grad_fn = tfe.implicit_value_and_gradients(loss)
```
Error: here can be seen the type of logits is float32, same as the requirement of  [sigmoid_cross_entropy_with_logits](https://www.tensorflow.org/api_docs/python/tf/nn/sigmoid_cross_entropy_with_logits).   
So I'm curious where's wrong.
```
<dtype: 'int32'>
<dtype: 'float32'>
Traceback (most recent call last):
  File "model.py", line 384, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/home/ubuntu/hdd1/zip_data/Paul/miniconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "model.py", line 335, in main
    train_one_epoch(epoch_i=i, train_data=ds_train, log_interval=FLAGS.log_interval, **model_objects)
  File "model.py", line 264, in train_one_epoch
    value, grads_and_vars = val_grad_fn((u, i, i_c, ts, hist_c, sl), y)
  File "/home/ubuntu/hdd1/zip_data/Paul/miniconda3/lib/python3.6/site-packages/tensorflow/python/eager/backprop.py", line 203, in grad_fn
    end_node = f(*args, **kwds)
  File "model.py", line 249, in loss
    labels=labels)
  File "/home/ubuntu/hdd1/zip_data/Paul/miniconda3/lib/python3.6/site-packages/tensorflow/python/ops/nn_impl.py", line 181, in sigmoid_cross_entropy_with_logits
    relu_logits - logits * labels,
  File "/home/ubuntu/hdd1/zip_data/Paul/miniconda3/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 850, in binary_op_wrapper
    return func(x, y, name=name)
  File "/home/ubuntu/hdd1/zip_data/Paul/miniconda3/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 1094, in _mul_dispatch
    return gen_math_ops.mul(x, y, name=name)
  File "/home/ubuntu/hdd1/zip_data/Paul/miniconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_math_ops.py", line 4959, in mul
    _six.raise_from(_core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: cannot compute Mul as input #0 was expected to be a int32 tensor but is a float tensor [Op:Mul] name: logistic_loss/mul/
```

**Comment by Paul0M** [comment]
logits should be same as labels
