### ISSUE TITLE
Error restoring checkpoint: BeamSearchDecoder

### ISSUE THREAD

**Issue by pj-parag** [tensorflow/tensorflow#22236]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows7, CPU 
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: NA
- **TensorFlow installed from (source or binary)**: pip
- **TensorFlow version (use command below)**: tf.VERSION = 1.10.0|tf.GIT_VERSION = b'v1.10.0-rc1-19-g656e7a2b34'| tf.COMPILER_VERSION = b'v1.10.0-rc1-19-g656e7a2b34'
- **Python version**: Python 3.5.5
- **Bazel version (if compiling from source)**: NA
- **GCC/Compiler version (if compiling from source)**: NA
- **CUDA/cuDNN version**: NA
- **GPU model and memory**: NA
- **Exact command to reproduce**: NA

### Describe the problem
I am trying to load a model trained using basic decoder with train_ce=True and loading it with beamsearch with train_ws=True (like inference) but it fails during restore:

```
Traceback (most recent call last):
  File "train_ws.py", line 502, in <module>
    tf.app.run()
  File "C:\ProgramData\Miniconda3\envs\tensorflow\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "train_ws.py", line 337, in main
    saver.restore(sess, FLAGS.restore_path)
  File "C:\ProgramData\Miniconda3\envs\tensorflow\lib\site-packages\tensorflow\python\training\saver.py", line 1759, in restore
    err, "a mismatch between the current graph and the graph")
tensorflow.python.framework.errors_impl.InvalidArgumentError: Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Input 1 of node decoder/dynamic_decoder_out/decoder/while/Merge_7_1 was passed float from decoder/dynamic_decoder_out/decoder/while/NextIteration_7:0 incompatible with expected int32.
```

### Source code 
```
def inference_s2s_ce(self, encoder_inputs, decoder_inputs, encoder_inputs_lenghts, decoder_inputs_lenghts, feed_previous):
    true_batch_size = tf.size(encoder_inputs_lenghts)
    encoder_outputs, encoder_state = self.input_encoder(encoder_inputs)
    print('encoder_state ', encoder_state)
    attention_inputs = encoder_outputs # Not time major
    #encoder_outputs = tf.transpose(encoder_outputs, [1, 0, 2]) # time major
    if self.mode == 'train_ws':
        attention_inputs = tf.contrib.seq2seq.tile_batch(encoder_outputs, multiplier=self.beam_width)
        encoder_state = tf.contrib.seq2seq.tile_batch(encoder_state, multiplier=self.beam_width)
        encoder_inputs_lenghts = tf.contrib.seq2seq.tile_batch(encoder_inputs_lenghts, multiplier=self.beam_width)  
    with tf.variable_scope('decoder', reuse=tf.AUTO_REUSE) as scope:
        decoder_cell = tf.contrib.rnn.LSTMCell(self.rnn_size,state_is_tuple=True)
        embedding_decoder = variable_scope.get_variable("embedding_decoder", [self.tgt_vocab_size, self.decoder_embedding_size])
        decoder_emb_inp = tf.nn.embedding_lookup(embedding_decoder, decoder_inputs)
        input_layer = Dense(self.rnn_size, dtype=self.dtype, name='input_projection')
        decoder_emb_inp = input_layer(decoder_emb_inp)
        attention_mechanism = tf.contrib.seq2seq.BahdanauAttention( num_units=self.rnn_size, memory=attention_inputs, 
        memory_sequence_length=encoder_inputs_lenghts)
        attn_cell = tf.contrib.seq2seq.AttentionWrapper(decoder_cell, attention_mechanism)#, attention_layer_size= self.num_units / 2)
        projection_layer = tf.layers.Dense(self.tgt_vocab_size, use_bias=False)
        if self.mode == 'train_ce':
            helper = tf.contrib.seq2seq.TrainingHelper(decoder_emb_inp, decoder_inputs_lenghts)#,  time_major=False)
            decoder_initial_state = attn_cell.zero_state(true_batch_size, dtype=tf.float32).clone(cell_state=encoder_state)
            decoder = tf.contrib.seq2seq.BasicDecoder(
                cell=attn_cell, helper=helper,
                initial_state=decoder_initial_state, 
                output_layer=projection_layer)
            inference_decoder = decoder
        elif self.mode == 'train_ws':
            tgt_sos_id = 3
            tgt_eos_id = 1
            start_tokens = tf.tile(tf.constant([tgt_sos_id], dtype=tf.int32), [true_batch_size])
            batch_size = true_batch_size * self.beam_width#tf.cast(true_batch_size * self.beam_width, dtype=tf.int32)
            decoder_initial_state = attn_cell.zero_state(batch_size, tf.float32).clone(cell_state=encoder_state)
            print('decoder_initial_state shape ', decoder_initial_state)
            decoder = tf.contrib.seq2seq.BeamSearchDecoder(cell = attn_cell, embedding=embedding_decoder, start_tokens=start_tokens,
            end_token=tgt_eos_id, initial_state=decoder_initial_state, beam_width=int(self.beam_width), output_layer=projection_layer)
            inference_decoder = decoder
        with tf.variable_scope('dynamic_decoder_out', reuse=tf.AUTO_REUSE) as scope:
            outputs, _, _ = seq2seq.dynamic_decode(decoder=inference_decoder,output_time_major=False,maximum_iterations=self.output_max_length) 
            if self.mode == 'train_ce':
                logits = outputs.rnn_output
                print('Logits ', logits.get_shape())
                return logits
            elif self.mode == 'train_ws':
                return outputs.beam_search_decoder_output.scores
        
```
I have tried restoring basicdecoder, that works.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by pj-parag** [comment]
Updated the system info and added NA in fields which were skipped.

**Comment by karmel** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
