### ISSUE TITLE
[Bug] Keras TimeDistributed Concatenation

### ISSUE THREAD

**Issue by OneMoreSecond** [tensorflow/tensorflow#22234]
### System information
- **Code**:
```
import tensorflow.keras as k
import numpy as np

input1 = k.layers.Input(shape=(None, 10))
input2 = k.layers.Input(shape=(10,))

concat_layer = k.layers.Lambda(lambda x: k.layers.concatenate([x, input2]))
results = k.layers.TimeDistributed(concat_layer)(input1)

model = k.models.Model([input1, input2], results)

data1 = np.zeros((3,7,10))
data2 = np.zeros((3,10))

model.predict([data1,data2])
```
- **OS Platform and Distribution**: Windows server 2016
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 'v1.10.0-rc1-19-g656e7a2b34' 1.10.0
- **Python version**: 3.6.6
- **CUDA/cuDNN version**: CUDA 9.0, cuDNN 7.0
- **Have I written custom code**: all the same as above code
- **Bazel version** : N/A
- **GPU model and memory**: Quadro P600, 2GiB
- **Exact command to reproduce**: python test.py
- **Mobile device**: N/A

### Describe the problem
I try to run the code mentioned above.
My goal is to concatenate input2 to each timestep of input1.
But the log shows TF reshaped first two dimensions of input1 when concatenating.

Line 235 in https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/layers/wrappers.py is wrong.
Even the batch size is None, the time-distributed layer's behavior may relate to actual batch size.

```
if input_shape[0]:
      # batch size matters, use rnn-based implementation
      ...................
else:
      # No batch size specified, therefore the layer will be able
      # to process batches of any size. (TRUE)
      # We can go with reshape-based implementation for performance.
      (FALSE! BEHAVIOR MAY RELATE TO ACTUAL BATCH SIZE)
```

### Source code / logs
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1493, in predict
>     self, x, batch_size=batch_size, verbose=verbose, steps=steps)
>   File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\keras\engine\training_arrays.py", line 374, in predict_loop
>     batch_outs = f(ins_batch)
>   File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\keras\backend.py", line 2914, in __call__
>     fetched = self._callable_fn(*array_vals)
>   File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1382, in __call__
>     run_metadata_ptr)
>   File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 519, in __exit__
>     c_api.TF_GetCode(self.status.status))
> tensorflow.python.framework.errors_impl.InvalidArgumentError: ConcatOp : Dimensions of inputs should match: shape[0] = [21,10] vs. shape[1] = [3,10]
>          [[Node: time_distributed_2/concatenate_1/concat = ConcatV2[N=2, T=DT_FLOAT, Tidx=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](time_distributed_2/Reshape, _arg_input_3_0_1/_3, time_distributed_2/concatenate_1
> /concat/axis)]]
>          [[Node: time_distributed_2/Reshape_1/_5 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_n
> ame="edge_27_time_distributed_2/Reshape_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

**Comment by harshini-gadige** [comment]
@fchollet  Could you please help the user to understand if the existing code is as expected or if there is a change required, can suggest to open a new PR.

**Comment by omalleyt12** [comment]
@OneMoreSecond Your `Lambda` should accept a list of inputs rather than referencing the global variable `inputs2`. I'm not sure `TimeDistributed` is the best way to go about this. Here's an example that I believe satisfies your use case

```python
import tensorflow.keras as k
import numpy as np

input1 = k.layers.Input(shape=(None, 10))
input2 = k.layers.Input(shape=(10,))

def expand_and_concat(x):
  x0, x1 = x
  x1  = tf.expand_dims(x1, axis=1)
  x1  = tf.tile(x1, [1, tf.shape(x0)[1], 1])
  return tf.concat([x0, x1], axis=2)

results = k.layers.Lambda(expand_and_concat)([input1, input2])
model = k.models.Model([input1, input2], results)

data1 = np.zeros((3,7,10))
data2 = np.zeros((3,10))

model.predict([data1,data2])
```

**Comment by tensorflowbutler** [comment]
Nagging Assignee @fchollet: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @fchollet: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @fchollet: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @fchollet: It has been 62 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @fchollet: It has been 76 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.
