### ISSUE TITLE
`tf.nn.softmax` gives an error at execution time for certain empty inputs

### ISSUE THREAD

**Issue by daniel-ziegler** [tensorflow/tensorflow#22259]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS High Sierra (10.13.6)
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: n/a
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: v1.10.0-12-g4dcfddc5d1 1.10.1
- **Python version**: 3.6.4 (Anaconda)
- **Bazel version (if compiling from source)**: n/a
- **GCC/Compiler version (if compiling from source)**: n/a
- **CUDA/cuDNN version**: n/a
- **GPU model and memory**: n/a
- **Exact command to reproduce**: n/a

### Describe the problem
When the softmax axis has length 0 and rank of the tensor is not 2, `tf.nn.softmax` gives an error at execution time:
```
  File "/Users/dmz/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 1612, in _flatten_outer_dims
    output = array_ops.reshape(logits, array_ops.concat([[-1], last_dim_size], 0))
  File "/Users/dmz/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 6222, in reshape
    _six.raise_from(_core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: Reshape cannot infer the missing input size for an empty tensor unless all specified input sizes are non-zero [Op:Reshape]
```
I'd expect it to instead just give back a tensor of the same shape (also empty).

For example, `tf.nn.softmax(tf.zeros([0]))` and `tf.nn.softmax(tf.zeros([16,16,0]))` fail, but `tf.nn.softmax(tf.zeros([16,0]))` works (since no reshape needs to be performed).

This seems to happen because `_flatten_outer_dims` in `nn_ops.py` uses `-1` as a dimension in a `reshape`. 

### Source code / logs
Here's an interactive session with eager execution that demonstrates the problem. It happens the same way without eager execution.
```
Python 3.6.4 |Anaconda custom (64-bit)| (default, Jan 16 2018, 12:04:33)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> tf.enable_eager_execution()
>>> tf.nn.softmax(tf.zeros([0]))
2018-09-13 13:08:55.015409: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/dmz/anaconda3/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "/Users/dmz/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 1738, in softmax
    return _softmax(logits, gen_nn_ops.softmax, axis, name)
  File "/Users/dmz/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 1679, in _softmax
    logits = _flatten_outer_dims(logits)
  File "/Users/dmz/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 1612, in _flatten_outer_dims
    output = array_ops.reshape(logits, array_ops.concat([[-1], last_dim_size], 0))
  File "/Users/dmz/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 6222, in reshape
    _six.raise_from(_core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: Reshape cannot infer the missing input size for an empty tensor unless all specified input sizes are non-zero [Op:Reshape]
>>> tf.nn.softmax(tf.zeros([16,0]))
<tf.Tensor: id=17, shape=(16, 0), dtype=float32, numpy=array([], shape=(16, 0), dtype=float32)>
>>> tf.nn.softmax(tf.zeros([16,16,0]))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/dmz/anaconda3/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "/Users/dmz/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 1738, in softmax
    return _softmax(logits, gen_nn_ops.softmax, axis, name)
  File "/Users/dmz/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 1679, in _softmax
    logits = _flatten_outer_dims(logits)
  File "/Users/dmz/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 1612, in _flatten_outer_dims
    output = array_ops.reshape(logits, array_ops.concat([[-1], last_dim_size], 0))
  File "/Users/dmz/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 6222, in reshape
    _six.raise_from(_core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: Reshape cannot infer the missing input size for an empty tensor unless all specified input sizes are non-zero [Op:Reshape]
>>>
```

**Comment by yongtang** [comment]
@daniel-ziegler I tried with the latest tf-nightly (on Ubuntu 16.04 though), it looks fine. Can you give the tf-nightly a try?
```
# python
Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> tf.enable_eager_execution()
>>> tf.nn.softmax(tf.zeros([0]))
2018-09-22 12:48:06.009335: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
<tf.Tensor: id=4, shape=(0,), dtype=float32, numpy=array([], dtype=float32)>
>>> tf.nn.softmax(tf.zeros([16,0]))
<tf.Tensor: id=9, shape=(16, 0), dtype=float32, numpy=array([], shape=(16, 0), dtype=float32)>
>>> tf.nn.softmax(tf.zeros([16,16,0]))
<tf.Tensor: id=14, shape=(16, 16, 0), dtype=float32, numpy=array([], shape=(16, 16, 0), dtype=float32)>
>>> tf.VERSION
'1.12.0-dev20180922'
>>> 
```

**Comment by harshini-gadige** [comment]
@daniel-ziegler Hi, have you tried with tf-nightly ?

**Comment by daniel-ziegler** [comment]
Just tried it on nightly both with eager and without -- works great. I'll close this issue.
