### ISSUE TITLE
Is tensorflow-gpu version same with just tensorflow for cpu?

### ISSUE THREAD

**Issue by bughunter99** [tensorflow/tensorflow#22252]
I've developed some Keras code using tensorflow with cpu on Windows7 on my pc, and trained it with GPU on linux.

After complete training, I have moved the trained model files to my pc and used them without any problems. But I don't know what happened, it doesn't work on my pc. I guess it is from Keras and tensorflow version issue.

The linux's Keras and tensorflow version are Keras (2.1.5), tensorflow-gpu (1.4.1), and my pc's version are Keras (2.1.5), tensorflow (1.4.0.).

Below is the error msg.

```
Traceback (most recent call last):
  File "C:\WinPython-64bit-3.5.4.1Qt5\python-3.5.4.amd64\lib\site-packages\tensorflow\python\client\session.py", line 1323, in _do_call
    return fn(*args)
  File "C:\WinPython-64bit-3.5.4.1Qt5\python-3.5.4.amd64\lib\site-packages\tensorflow\python\client\session.py", line 1302, in _run_fn
    status, run_metadata)
  File "C:\WinPython-64bit-3.5.4.1Qt5\python-3.5.4.amd64\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[22,3] = 13257 is not in [0, 13004)
         [[Node: embedding_1/Gather = Gather[Tindices=DT_INT32, Tparams=DT_FLOAT, validate_indices=true, _device="/job:localhost/replica:0/task:0/devi
ce:CPU:0"](embedding_1/embeddings/read, embedding_1/Cast)]]


```
and 
```
File "C:\WinPython-64bit-3.5.4.1Qt5\python-3.5.4.amd64\lib\site-packages\tensorflow\python\client\session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[22,3] = 13257 is not in [0, 13004)
         [[Node: embedding_1/Gather = Gather[Tindices=DT_INT32, Tparams=DT_FLOAT, validate_indices=true, _device="/job:localhost/replica:0/task:0/devi
ce:CPU:0"](embedding_1/embeddings/read, embedding_1/Cast)]]
```

and
```
File "C:\WinPython-64bit-3.5.4.1Qt5\python-3.5.4.amd64\lib\site-packages\tensorflow\python\framework\ops.py", line 2956, in create_op
    op_def=op_def)
  File "C:\WinPython-64bit-3.5.4.1Qt5\python-3.5.4.amd64\lib\site-packages\tensorflow\python\framework\ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): indices[22,3] = 13257 is not in [0, 13004)
         [[Node: embedding_1/Gather = Gather[Tindices=DT_INT32, Tparams=DT_FLOAT, validate_indices=true, _device="/job:localhost/replica:0/task:0/devi
ce:CPU:0"](embedding_1/embeddings/read, embedding_1/Cast)]]

Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x000000001A8DE198>>
Traceback (most recent call last):
  File "C:\WinPython-64bit-3.5.4.1Qt5\python-3.5.4.amd64\lib\site-packages\tensorflow\python\client\session.py", line 696, in __del__
TypeError: 'NoneType' object is not callable

```

There were several similar questions, but anything were helpful. To use trained model file from Keras (2.1.5) and tensorflow-gpu (1.4.1), which Keras and tensorflow(cpu) version should I use? Of course I use same python version with the linux which is 3.5 on 64bit.

**Comment by wt-huang** [comment]
@bughunter99 If you use Keras (2.1.5) and tensorflow-gpu (1.4.1), use the same versions for pc. Make sure your model doesn't have explicit device allocations to gpu. As an alternative, you can also install tensorflow-gpu on the pc.

**Comment by wt-huang** [comment]
Closing this issue, feel free to reopen if problem persists.
