### ISSUE TITLE
TFLite Android ArrayIndex outofBound Exception length=40, index=-7

### ISSUE THREAD

**Issue by DeepakSridhar** [tensorflow/tensorflow#22278]
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Partially modified TFLite Android code

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.
I converted mobilenet_v2_ssd trained using my data to tflite following the instructions in the blog post:
https://medium.com/tensorflow/training-and-serving-a-realtime-mobile-object-detector-in-30-minutes-with-cloud-tpus-b78971cf1193

I did not quantize the model since I didn't train it using quantized training. To run on mobile I set the 
IS_QUANTIZED variable in Detector.Activity to false. When I run the app, i get the error 
java.lang.ArrayIndexOutOfBoundsException: length=40; index=-8
at java.util.Vector.elementAt(Vector.java:326)
at java.util.Vector.get(Vector.java:442)
at org.tensorflow.demo.TFLiteObjectDetectionAPIModel.recognizeImage(TFLiteObjectDetectionAPIModel.java:214)

I thought the issue is due to the length of the output vector. So I changed the NUM_DETECTIONS in TFLiteObjectDetectionAPIModel.java to 40, then  I get another error saying
Cannot copy between a TensorFlowLite tensor with shape [1, 10] and a Java object with shape [1, 40].

Is the length of output vector fixed? Please help me with the issue.Thanks!

**Comment by tensorflowbutler** [comment]
Nagging Assignee @shivaniag: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @shivaniag: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by idrissbellil** [comment]
The android demo app was made for one specific case this [https://github.com/tensorflow/tensorflow/issues/22106#issuecomment-428409506](url) the last part of the last comment may solve your issue, you don't have to switch branch or anything, just do boundary checks like he did.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @shivaniag: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @shivaniag: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by suharshs** [comment]
Closing due to inactivity and since this is answered above.

**Comment by aravindchaluvadi** [comment]
ERROR : W/System.err: java.lang.ArrayIndexOutOfBoundsException: length=10; index=-2147483648

Even I am facing the same issue could you brief on the solution?

**Comment by patrick-ucr** [comment]
I am having similar issues when using custom trained models converted by https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_on_mobile_tensorflowlite.md

but don't see the problem with default models automatically downloaded.

**Comment by Davari393** [comment]
I have it too.does not any one help us?
it is force for me

**Comment by HaFred** [comment]
> I have it too.does not any one help us?
> it is force for me

I suggest you refer to #22106 https://github.com/tensorflow/tensorflow/issues/22106#issuecomment-428409506 for solution.
It would help change the input tensor.

**Comment by Ehtasha** [comment]
@patrick-ucr  Have you resolve this ?
I'm also facing same issue while working with custom model ?

**Comment by karuneshpalekar** [comment]
@DeepakSridhar @HaFred I am facing the same issue . If there is any legitimate solution found until now ,Please forward .
