### ISSUE TITLE
Distributed training fails when I use FixedLengthRecordDataset

### ISSUE THREAD

**Issue by dmitrievanthony** [tensorflow/tensorflow#22319]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
I slightly updated `keras_model_to_estimator_client.py` example so that it uses FixedLengthRecordDataset. Updated version is [here](https://github.com/dmitrievanthony/ecosystem/blob/ignite/distribution_strategy/keras_model_to_estimator_client.py).

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Ubuntu 17.04

- **TensorFlow installed from (source or binary)**:
Binary

- **TensorFlow version (use command below)**:
1.11.0-dev20180917

- **Python version**:
3.6.3

- **Exact command to reproduce**:
See [updated example](https://github.com/dmitrievanthony/ecosystem/blob/ignite/distribution_strategy/keras_model_to_estimator_client.py).

### Describe the problem
Hi,

I'm investigating TensorFlow distributed training approaches with help of @yuefengz who kindly helps me. So far I updated [keras_model_to_estimator_client.py](https://github.com/tensorflow/ecosystem/blob/master/distribution_strategy/keras_model_to_estimator_client.py) example so that it uses FixedLengthRecordDataset, but as result the whole code fails.

### Source code / logs

```
Traceback (most recent call last):
  File "/home/gridgain/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 2667, in gather
    return params.sparse_read(indices, name=name)
AttributeError: 'Tensor' object has no attribute 'sparse_read'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gridgain/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1628, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Shape must be at least rank 1 but is rank 0 for 'GatherV2' (op: 'GatherV2') with input shapes: [], [1], [].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "keras_model_to_estimator_client.py", line 134, in <module>
    tf.app.run(argv=sys.argv)
  File "/home/gridgain/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "keras_model_to_estimator_client.py", line 129, in main
    eval_spec=tf.estimator.EvalSpec(input_fn=input_fn))
  File "/home/gridgain/anaconda3/lib/python3.6/site-packages/tensorflow/python/estimator/training.py", line 462, in train_and_evaluate
    estimator, train_spec, eval_spec, _TrainingExecutor)
  File "/home/gridgain/anaconda3/lib/python3.6/site-packages/tensorflow/python/distribute/estimator_training.py", line 264, in train_and_evaluate
    session_config=run_config.session_config)
  File "/home/gridgain/anaconda3/lib/python3.6/site-packages/tensorflow/python/distribute/distribute_coordinator.py", line 798, in run_distribute_coordinator
    session_config, rpc_layer)
  File "/home/gridgain/anaconda3/lib/python3.6/site-packages/tensorflow/python/distribute/distribute_coordinator.py", line 344, in _run_single_worker
    worker_fn(strategy)
  File "/home/gridgain/anaconda3/lib/python3.6/site-packages/tensorflow/python/distribute/estimator_training.py", line 232, in _worker_fn
    hooks=list(train_spec.hooks))
  File "/home/gridgain/anaconda3/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 355, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/gridgain/anaconda3/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1178, in _train_model
    return self._train_model_distributed(input_fn, hooks, saving_listeners)
  File "/home/gridgain/anaconda3/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1246, in _train_model_distributed
    input_fn, model_fn_lib.ModeKeys.TRAIN, self._train_distribution)
  File "/home/gridgain/anaconda3/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1037, in _get_iterator_from_input_fn
    lambda: self._call_input_fn(input_fn, mode))
  File "/home/gridgain/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/distribute/python/mirrored_strategy.py", line 480, in distribute_dataset
    self._prefetch_on_device)
  File "/home/gridgain/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/distribute/python/values.py", line 814, in __init__
    worker_input, len(worker_device_map), i)
  File "/home/gridgain/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/distribute/python/input_ops.py", line 140, in auto_shard_dataset
    return _auto_shard_impl(dataset=dataset, found_reader_op=False)
  File "/home/gridgain/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/distribute/python/input_ops.py", line 107, in _auto_shard_impl
    dataset._input_dataset, found_reader_op)
  File "/home/gridgain/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/distribute/python/input_ops.py", line 107, in _auto_shard_impl
    dataset._input_dataset, found_reader_op)
  File "/home/gridgain/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/distribute/python/input_ops.py", line 107, in _auto_shard_impl
    dataset._input_dataset, found_reader_op)
  File "/home/gridgain/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/distribute/python/input_ops.py", line 67, in _auto_shard_impl
    filenames_tensor, math_ops.range(index, num_files, num_shards))
  File "/home/gridgain/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 2669, in gather
    return gen_array_ops.gather_v2(params, indices, axis, name=name)
  File "/home/gridgain/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3232, in gather_v2
    "GatherV2", params=params, indices=indices, axis=axis, name=name)
  File "/home/gridgain/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/gridgain/anaconda3/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/home/gridgain/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/home/gridgain/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1792, in __init__
    control_input_ops)
  File "/home/gridgain/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1631, in _create_c_op
    raise ValueError(str(e))
ValueError: Shape must be at least rank 1 but is rank 0 for 'GatherV2' (op: 'GatherV2') with input shapes: [], [1], [].
```
It looks like the exception happens in `input_ops.py` in `_auto_shard_impl` method when TensorFlow tries to shard file names. Unfortunately, I don't clearly understand this command to be honest: 

```
 sharded_filenames_tensor = array_ops.gather(
            filenames_tensor, math_ops.range(index, num_files, num_shards))
```

**Comment by yuefengz** [comment]
It is not recommended to use MirroredStrategy for multi-node, could you try CollectiveAllReduceStrategy while we are fixing this issue?

**Comment by dmitrievanthony** [comment]
@yuefengz, I tried, please have a look at #22321 :)

**Comment by guptapriya** [comment]
Will there be a way to turn it on by users?

**Comment by dmitrievanthony** [comment]
Hi, @yuefengz. Looks like it's been fixed, right?

**Comment by guptapriya** [comment]
Yes, commit https://github.com/tensorflow/tensorflow/commit/301e3043e67493ce3777d2b36b43d0210f7b920c#diff-6d6d850ad586ab99cc0dbaabba8a229c disables auto sharding by default, and instead adds an argument to `MirroredStrategy` to explicitly turn it on. 

If this works for you now, feel free to close the issue. Thanks!

**Comment by dksb** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
