### ISSUE TITLE
Distributed training fails when I use CollectiveAllReduceStrategy

### ISSUE THREAD

**Issue by dmitrievanthony** [tensorflow/tensorflow#22321]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
I slightly updated mnist.py example so that it uses CollectiveAllReduceStrategy. Updated version is [here](https://github.com/dmitrievanthony/models/blob/ignite/official/mnist/mnist.py#L208).

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Mac OS 10.13.3

- **TensorFlow installed from (source or binary)**:
Binary

- **TensorFlow version (use command below)**:
1.11.0-dev20180913

- **Python version**:
3.6.3

- **Exact command to reproduce**:
See [updated example](https://github.com/dmitrievanthony/models/blob/ignite/official/mnist/mnist.py#L208).

### Describe the problem

Hi, 

I'm trying to update `mnist` model from [official repository](https://github.com/tensorflow/models/tree/master/official/) so that it uses CollectiveAllReduceStrategy as it's shown in [keras_model_to_estimator_client.py](https://github.com/tensorflow/ecosystem/blob/master/distribution_strategy/keras_model_to_estimator_client.py). Updated example you can find [here](https://github.com/dmitrievanthony/models/blob/ignite/official/mnist/mnist.py#L208). Unfortunately, it fails on `deepcopy` of run config.

### Source code / logs
```
Traceback (most recent call last):
  File "mnist.py", line 286, in <module>
    absl_app.run(main)
  File "/Users/antondmitriev/anaconda3/lib/python3.6/site-packages/absl/app.py", line 274, in run
    _run_main(main, args)
  File "/Users/antondmitriev/anaconda3/lib/python3.6/site-packages/absl/app.py", line 238, in _run_main
    sys.exit(main(argv))
  File "mnist.py", line 280, in main
    run_mnist(flags.FLAGS)
  File "mnist.py", line 226, in run_mnist
    'data_format': data_format,
  File "/Users/antondmitriev/anaconda3/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 190, in __init__
    model_dir)
  File "/Users/antondmitriev/anaconda3/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1591, in maybe_overwrite_model_dir_and_session_config
    config = run_config.RunConfig.replace(config, session_config=session_config)
  File "/Users/antondmitriev/anaconda3/lib/python3.6/site-packages/tensorflow/python/estimator/run_config.py", line 849, in replace
    copy.deepcopy(self),
  File "/Users/antondmitriev/anaconda3/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/Users/antondmitriev/anaconda3/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/Users/antondmitriev/anaconda3/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/Users/antondmitriev/anaconda3/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/Users/antondmitriev/anaconda3/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/Users/antondmitriev/anaconda3/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/Users/antondmitriev/anaconda3/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/Users/antondmitriev/anaconda3/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/Users/antondmitriev/anaconda3/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/Users/antondmitriev/anaconda3/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/Users/antondmitriev/anaconda3/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/Users/antondmitriev/anaconda3/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/Users/antondmitriev/anaconda3/lib/python3.6/copy.py", line 169, in deepcopy
    rv = reductor(4)
TypeError: can't pickle _thread._local objects
```

**Comment by itsliupeng** [comment]
I met the same problem when using CollectiveAllReduceStrategy

**Comment by yuefengz** [comment]
I couldn't reproduce this problem. I am wondering whether you are still running with standalone client mode?

**Comment by harshini-gadige** [comment]
@dmitrievanthony Hi, Could you please share a small code snippet to reproduce this issue. Also you may clarify if you are running this with standalone client mode or not.

**Comment by dmitrievanthony** [comment]
@yuefengz, @harshini-gadige, yes I use standalone client mode. 

I've prepared an example based on keras_model_to_estimator_client.py. Please take a look [here](https://github.com/dmitrievanthony/ecosystem/blob/ignite-2/distribution_strategy/keras_model_to_estimator_client.py). It uses `FixedLengthRecordDataset` and `CollectiveAllReduceStrategy` strategy.

I don't use Kubernetes, so to reproduce this problem I do the following:
1. Start [worker1.py](https://github.com/dmitrievanthony/ecosystem/blob/ignite-2/ignite/worker1.py).
2. Start [worker2.py](https://github.com/dmitrievanthony/ecosystem/blob/ignite-2/ignite/worker2.py).
3. Set `TF_CONFIG='{"cluster":{"worker":["localhost:1111", "localhost:1112"],"chief":["localhost:1113"]}, "task":{"type":"chief","index":0}}'`
4. Start [keras_model_to_estimator_client.py](https://github.com/dmitrievanthony/ecosystem/blob/ignite-2/distribution_strategy/keras_model_to_estimator_client.py).
Get the exception.

![screen](https://s3.amazonaws.com/helloworld23423423ew23/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA+%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0+2018-09-18+%D0%B2+21.39.19.png)

**Comment by yuefengz** [comment]
@dmitrievanthony But you haven't specified `remote_cluster` in your code?

**Comment by dmitrievanthony** [comment]
I specified `TF_CONFIG`. As far as I understand documentation it's another source of information about cluster if `remote_cluster` is not specified. Am I wrong?

**Comment by byronyi** [comment]
If I remember correctly, I suppose if you don’t specify the remote_cluster, the client runs in independent worker mode, which means all your nodes should run the same Python program but not a standard TF server. I would recommend you to try standalone client mode, which is in effect when you do specify remote_cluster.

**Comment by dmitrievanthony** [comment]
Looks like it would be better to make documentation of API more clear, but anyway... :)

I tried the following approach:
1. Set `export TF_CONFIG='{"cluster":{"worker":["localhost:1111", "localhost:1112"],"chief":["localhost:1113"]}, "task":{"type":"worker","index":0}}'`
2. Start [worker1](https://github.com/dmitrievanthony/ecosystem/blob/ignite-2/ignite/worker1.py) (it's modified and now calls `run_standard_tensorflow_server`).
3. Set `export TF_CONFIG='{"cluster":{"worker":["localhost:1111", "localhost:1112"],"chief":["localhost:1113"]}, "task":{"type":"worker","index":1}}'`
4. Start [worker2](https://github.com/dmitrievanthony/ecosystem/blob/ignite-2/ignite/worker2.py) (it's modified and now calls `run_standard_tensorflow_server` and equal to `worker1.py` to be honest).
5. Start [keras_model_to_estimator_client.py](https://github.com/dmitrievanthony/ecosystem/blob/ignite-2/distribution_strategy/keras_model_to_estimator_client.py#L106) with cluster specification passed via `remote_cluster`.

Unfortunately, after all these actions I get the same exception:

```
INFO:tensorflow:Initializing RunConfig with distribution strategies.
INFO:tensorflow:RunConfig initialized for Distribute Coordinator with STANDALONE_CLIENT mode
INFO:tensorflow:Using the Keras model provided.
Traceback (most recent call last):
  File "keras_model_to_estimator_client.py", line 126, in <module>
    tf.app.run(argv=sys.argv)
  File "/Users/antondmitriev/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "keras_model_to_estimator_client.py", line 114, in main
    keras_model=model, config=run_config, model_dir=model_dir)
  File "/Users/antondmitriev/anaconda3/lib/python3.6/site-packages/tensorflow/python/estimator/keras.py", line 412, in model_to_estimator
    model_dir)
  File "/Users/antondmitriev/anaconda3/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1591, in maybe_overwrite_model_dir_and_session_config
    config = run_config.RunConfig.replace(config, session_config=session_config)
  File "/Users/antondmitriev/anaconda3/lib/python3.6/site-packages/tensorflow/python/estimator/run_config.py", line 849, in replace
    copy.deepcopy(self),
  File "/Users/antondmitriev/anaconda3/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/Users/antondmitriev/anaconda3/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/Users/antondmitriev/anaconda3/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/Users/antondmitriev/anaconda3/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/Users/antondmitriev/anaconda3/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/Users/antondmitriev/anaconda3/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/Users/antondmitriev/anaconda3/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/Users/antondmitriev/anaconda3/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/Users/antondmitriev/anaconda3/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/Users/antondmitriev/anaconda3/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/Users/antondmitriev/anaconda3/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/Users/antondmitriev/anaconda3/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/Users/antondmitriev/anaconda3/lib/python3.6/copy.py", line 169, in deepcopy
    rv = reductor(4)
TypeError: can't pickle _thread._local objects
````

**Comment by yuefengz** [comment]
Looks like this is a problem with python3.

**Comment by dmitrievanthony** [comment]
Hi @yuefengz, yes, looks like you are right. I changed example so that it doesn't require kubernetes. From my perspective it's easier to start with such example without external dependencies.

**Comment by dmitrievanthony** [comment]
Hi @yuefengz, I tried to do the same things with `python2`. It workers better because it doesn't throw an exception, but I still get in a trouble because it hangs up. I posted details in #22407, please have a look (maybe I juts configured something wrongly).

**Comment by dmitrievanthony** [comment]
@yuefengz, comment of this line unfortunately didn't help me.

**Comment by yuefengz** [comment]
This should fix the problem: https://github.com/tensorflow/tensorflow/commit/f10b00558de87020554c9c0512537dab96dba918

**Comment by yuefengz** [comment]
Closing this issue.

**Comment by khaitranvan96kt** [comment]
> here

Your code links are not accessible, you can update it again, I am looking for an example, I would like to thank

**Comment by dmitrievanthony** [comment]
Hi, @khaitranvan96kt. The issue was closed, so I removed examples. If you are interested in similar use cases you can have a look at the example I've prepared and tried to merge into "ecosystem" module: https://github.com/tensorflow/ecosystem/pull/101.
