### ISSUE TITLE
[TF1.10] Use the method "experimental_create_eval_graph()" of quantize_graph.py to quantize a frozen_model, succeeded but failed at serializing by graph_util

### ISSUE THREAD

**Issue by oscarriddle** [tensorflow/tensorflow#22379]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS 10.13.6
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: No
- **TensorFlow installed from (source or binary)**: pip install tensorflow-gpu==1.10.0
- **TensorFlow version (use command below)**: 1.10.0
- **Python version**: 2.7
- **Bazel version (if compiling from source)**: no
- **GCC/Compiler version (if compiling from source)**: clang 9.1.0
- **CUDA/cuDNN version**: no
- **GPU model and memory**: no
- **Exact command to reproduce**: Please refer to my test script below:

Hi, 
I tried to use the tool named quantize_graph.py to quantize a frozen_graph from FP32 to INT8.
After import the frozen model, I called the method named "experimental_create_eval_graph" and seems succeeded.
Later when I try to use graph_util to freeze variables to constant, error occurred.
Script:
```
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import tensorflow as tf
from tensorflow.contrib.layers.python.layers import layers
from tensorflow.contrib.quantize.python import quantize_graph
from tensorflow.python.framework import ops
from tensorflow.python.framework import test_util
from tensorflow.python.ops import array_ops
from tensorflow.python.ops import init_ops
from tensorflow.python.ops import nn_ops

from tensorflow.python.framework import importer as importer
from tensorflow.python.client import session as csess
from tensorflow.core.protobuf import config_pb2 as cpb2
from tensorflow.python.framework import ops as ops
from tensorflow.python.framework import graph_util
from tensorflow.python.platform import gfile

#tf.enable_eager_execution()

output_node_name = 'InceptionV3/Logits/SpatialSqueeze'
input_node_name = 'Placeholder'
output_path = 'test.pb'
g = tf.Graph()
with g.as_default():
    output_graph_def = tf.GraphDef()
    with open('frozen_graph.pb', 'rb') as f:
        output_graph_def.ParseFromString(f.read())
        _ = tf.import_graph_def(output_graph_def, name='')
    print([n.name for n in output_graph_def.node])
    quantize_graph.experimental_create_eval_graph(
        input_graph = g,
        weight_bits = 8,
        activation_bits = 8,
        quant_delay=None,
        scope=None)

    print('=========================')
    print([n.name for n in g.as_graph_def().node])


#saver = tf.train.Saver(write_version=tf.train.SaverDef.V1)
with csess.Session(config=cpb2.ConfigProto(), graph=g) as sess:
    inp = tf.get_default_graph().get_tensor_by_name('Placeholder:0')
    out = tf.get_default_graph().get_tensor_by_name('InceptionV3/Logits/SpatialSqueeze:0')
    g = graph_util.convert_variables_to_constants(sess, g.as_graph_def(), out)
    with tf.gfile.GFile(output_path, "wb") as f:
        f.write(g.SerializeToString())
#    saver_path = saver.save(sess, "model.ckpt")
```
The Error log:
```
Traceback (most recent call last):
  File "test.py", line 48, in <module>
    g = graph_util.convert_variables_to_constants(sess, g.as_graph_def(), out)
  File "/Library/Python/2.7/site-packages/tensorflow/python/framework/graph_util_impl.py", line 232, in convert_variables_to_constants
    inference_graph = extract_sub_graph(input_graph_def, output_node_names)
  File "/Library/Python/2.7/site-packages/tensorflow/python/framework/graph_util_impl.py", line 174, in extract_sub_graph
    _assert_nodes_are_present(name_to_node, dest_nodes)
  File "/Library/Python/2.7/site-packages/tensorflow/python/framework/graph_util_impl.py", line 132, in _assert_nodes_are_present
    for d in nodes:
  File "/Library/Python/2.7/site-packages/tensorflow/python/framework/ops.py", line 431, in __iter__
    "Tensor objects are not iterable when eager execution is not "
TypeError: Tensor objects are not iterable when eager execution is not enabled. To iterate over this tensor use tf.map_fn.

```
After enabling the eager execution mode, the error remains the same.
Not sure whether my script is correct and whether there is a way to serialize the quantized graph to a file? Any idea will be welcome.

Thanks,

--------------------------

I wrote a script to try to evaluate the accuracy of the quantized model over a test dataset.
But a "FailedPreconditionError" error raised. Note that I'm using the official inceptionv3 model, and the output node is named "InceptionV3/Logits/SpatialSqueeze".
I wonder whether there will be a demo about how to use the quantized graph to do the prediction?
Let me update the full log
```

2018-09-25 10:51:49.521178: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-09-25 10:51:49.700182: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1405] Found device 0 with properties: 
name: TITAN Xp major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:84:00.0
totalMemory: 11.91GiB freeMemory: 11.75GiB
2018-09-25 10:51:49.700336: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1484] Adding visible gpu devices: 0
2018-09-25 10:51:50.023026: I tensorflow/core/common_runtime/gpu/gpu_device.cc:965] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-09-25 10:51:50.023106: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971]      0 
2018-09-25 10:51:50.023120: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] 0:   N 
2018-09-25 10:51:50.023437: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1097] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 11364 MB memory) -> physical GPU (device: 0, name: TITAN Xp, pci bus id: 0000:84:00.0, compute capability: 6.1)
Traceback (most recent call last):
  File "test.py", line 61, in <module>
    val = sess.run(out, {inp: preProcessImage(img_path)})
  File "/home/web_server/dlpy72/dlpy/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 877, in run
    run_metadata_ptr)
  File "/home/web_server/dlpy72/dlpy/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1100, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/web_server/dlpy72/dlpy/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1272, in _do_run
    run_metadata)
  File "/home/web_server/dlpy72/dlpy/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1291, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value InceptionV3/InceptionV3/Mixed_7c/Branch_0/Conv2d_0a_1x1/weights_quant/min
	 [[Node: InceptionV3/InceptionV3/Mixed_7c/Branch_0/Conv2d_0a_1x1/weights_quant/min/read = Identity[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](InceptionV3/InceptionV3/Mixed_7c/Branch_0/Conv2d_0a_1x1/weights_quant/min)]]
	 [[Node: InceptionV3/Logits/SpatialSqueeze/_755 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_2389_InceptionV3/Logits/SpatialSqueeze", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op u'InceptionV3/InceptionV3/Mixed_7c/Branch_0/Conv2d_0a_1x1/weights_quant/min/read', defined at:
  File "test.py", line 50, in <module>
    quantize_graph.experimental_create_eval_graph(input_graph = g,weight_bits = 8,activation_bits = 8,quant_delay=None,scope=None)
  File "/home/web_server/dlpy72/dlpy/lib/python2.7/site-packages/tensorflow/contrib/quantize/python/quantize_graph.py", line 228, in experimental_create_eval_graph
    scope=scope)
  File "/home/web_server/dlpy72/dlpy/lib/python2.7/site-packages/tensorflow/contrib/quantize/python/quantize_graph.py", line 73, in _create_graph
    scope=scope)
  File "/home/web_server/dlpy72/dlpy/lib/python2.7/site-packages/tensorflow/contrib/quantize/python/quantize.py", line 94, in Quantize
    consumer_scope=scope)
  File "/home/web_server/dlpy72/dlpy/lib/python2.7/site-packages/tensorflow/contrib/quantize/python/quantize.py", line 545, in _InsertQuantOp
    name_prefix=name_prefix))
  File "/home/web_server/dlpy72/dlpy/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 183, in func_with_args
    return func(*args, **current_args)
  File "/home/web_server/dlpy72/dlpy/lib/python2.7/site-packages/tensorflow/contrib/quantize/python/quant_ops.py", line 101, in LastValueQuantize
    trainable=False)
  File "/home/web_server/dlpy72/dlpy/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 183, in func_with_args
    return func(*args, **current_args)
  File "/home/web_server/dlpy72/dlpy/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/variables.py", line 297, in model_variable
    use_resource=use_resource)
  File "/home/web_server/dlpy72/dlpy/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 183, in func_with_args
    return func(*args, **current_args)
  File "/home/web_server/dlpy72/dlpy/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/variables.py", line 252, in variable
    use_resource=use_resource)
  File "/home/web_server/dlpy72/dlpy/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 1467, in get_variable
    aggregation=aggregation)
  File "/home/web_server/dlpy72/dlpy/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 1217, in get_variable
    aggregation=aggregation)
  File "/home/web_server/dlpy72/dlpy/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 527, in get_variable
    aggregation=aggregation)
  File "/home/web_server/dlpy72/dlpy/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 481, in _true_getter
    aggregation=aggregation)
  File "/home/web_server/dlpy72/dlpy/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 903, in _get_single_variable
    aggregation=aggregation)
  File "/home/web_server/dlpy72/dlpy/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 2443, in variable
    aggregation=aggregation)
  File "/home/web_server/dlpy72/dlpy/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 2425, in <lambda>
    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
  File "/home/web_server/dlpy72/dlpy/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 2406, in default_variable_creator
    constraint=constraint)
  File "/home/web_server/dlpy72/dlpy/lib/python2.7/site-packages/tensorflow/python/ops/variables.py", line 259, in __init__
    constraint=constraint)
  File "/home/web_server/dlpy72/dlpy/lib/python2.7/site-packages/tensorflow/python/ops/variables.py", line 422, in _init_from_args
    self._snapshot = array_ops.identity(self._variable, name="read")
  File "/home/web_server/dlpy72/dlpy/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 80, in identity
    return gen_array_ops.identity(input, name=name)
  File "/home/web_server/dlpy72/dlpy/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3264, in identity
    "Identity", input=input, name=name)
  File "/home/web_server/dlpy72/dlpy/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/web_server/dlpy72/dlpy/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "/home/web_server/dlpy72/dlpy/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3155, in create_op
    op_def=op_def)
  File "/home/web_server/dlpy72/dlpy/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1717, in __init__
    self._traceback = tf_stack.extract_stack()

FailedPreconditionError (see above for traceback): Attempting to use uninitialized value InceptionV3/InceptionV3/Mixed_7c/Branch_0/Conv2d_0a_1x1/weights_quant/min
	 [[Node: InceptionV3/InceptionV3/Mixed_7c/Branch_0/Conv2d_0a_1x1/weights_quant/min/read = Identity[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](InceptionV3/InceptionV3/Mixed_7c/Branch_0/Conv2d_0a_1x1/weights_quant/min)]]
	 [[Node: InceptionV3/Logits/SpatialSqueeze/_755 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_2389_InceptionV3/Logits/SpatialSqueeze", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

```

**Comment by harshini-gadige** [comment]
@oscarriddle Hi, can you please share frozen_graph.pb

**Comment by tensorflowbutler** [comment]
Nagging Assignee @sguada: It has been 18 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by harshini-gadige** [comment]
@sguada Hi, could you please look into this issue.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @sguada: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @sguada: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by oscarriddle** [comment]
I tried to quantize the graph and create a session to run it, but failed, saying:
`KeyError: "The name 'Placeholder:0' refers to a Tensor which does not exist. The operation, 'Placeholder', does not exist in the graph."`

The script is:
```
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import tensorflow as tf
from tensorflow.contrib.layers.python.layers import layers
from tensorflow.contrib.quantize.python import quantize_graph
from tensorflow.python.framework import ops
from tensorflow.python.framework import test_util
from tensorflow.python.ops import array_ops
from tensorflow.python.ops import init_ops
from tensorflow.python.ops import nn_ops

from tensorflow.python.framework import importer as importer
from tensorflow.python.client import session as csess
from tensorflow.core.protobuf import config_pb2 as cpb2
from tensorflow.python.framework import ops as ops
from tensorflow.python.framework import graph_util
from tensorflow.python.platform import gfile
from tensorflow.python.framework import tensor_util

from PIL import Image
import numpy as np
import io,os
#tf.enable_eager_execution()                                                                                                                                                                   
#np.set_printoptions(threshold=np.nan)                                                                                                                                                         

output_node_name = 'InceptionV3/Logits/SpatialSqueeze'
input_node_name = 'Placeholder'
output_path = 'test.pb'
img_path = './1223832538_h.jpg'

def preProcessImage(img_path):
    list = []
    img = io.BytesIO(open(img_path,'rb').read())
    img = Image.open(img)
    img = img.resize((299, 299), Image.NEAREST)
    images = np.array(img, dtype=np.uint32)
    for x in xrange(16):
        list.append(images)
    list_np = np.array(list)
    return list_np

def get_all_const(graph_nodes):
    wts = [n for n in graph_nodes if n.op=='Const']
    for n in wts:
        print("Name of the node - %s" % n.name)
        print("Value - ")
        print(tensor_util.MakeNdarray(n.attr['value'].tensor).shape)
        print(tensor_util.MakeNdarray(n.attr['value'].tensor))
    return wts

g = tf.Graph()
with g.as_default():
    output_graph_def = tf.GraphDef()
    with open('frozen_graph.pb', 'rb') as f:
        output_graph_def.ParseFromString(f.read())
        _ = tf.import_graph_def(output_graph_def, name='')
    print([n.name for n in output_graph_def.node])
    graph_nodes=[n for n in output_graph_def.node]
#    get_all_const(graph_nodes)                                                                                                                                                                
    quantize_graph.experimental_create_eval_graph(input_graph = g,weight_bits = 8,activation_bits = 8)
    #quantize_graph.create_eval_graph(input_graph = g)                                                                                                                                         
    for i in xrange(5):
        print('=========================')
    print([n.name for n in g.as_graph_def().node])
    graph_nodes=[n for n in g.as_graph_def().node]
#    get_all_const(graph_nodes)             
gpu_options = cpb2.GPUOptions(per_process_gpu_memory_fraction = 0.8)
output_tensor_name = output_node_name
inp = tf.get_default_graph().get_tensor_by_name('Placeholder:0')
out = tf.get_default_graph().get_tensor_by_name('InceptionV3/Logits/SpatialSqueeze:0')
print('here')
images = preProcessImage(img_path)
with csess.Session(config=cpb2.ConfigProto(gpu_options=gpu_options), graph=g) as sess:
    val = sess.run(out, {inp: images})
print(val)

```
Error log is:
```
Traceback (most recent call last):
  File "test.py", line 75, in <module>
    inp = tf.get_default_graph().get_tensor_by_name('Placeholder:0')
  File "/home/web_server/dlpy72/dlpy.tensor1.12/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3666, in get_tensor_by_name
    return self.as_graph_element(name, allow_tensor=True, allow_operation=False)
  File "/home/web_server/dlpy72/dlpy.tensor1.12/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3490, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/home/web_server/dlpy72/dlpy.tensor1.12/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3532, in _as_graph_element_locked
    "graph." % (repr(name), repr(op_name)))
KeyError: "The name 'Placeholder:0' refers to a Tensor which does not exist. The operation, 'Placeholder', does not exist in the graph."
```

**Comment by tensorflowbutler** [comment]
Nagging Assignee @sguada: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by ymodak** [comment]
Apologies for the delay in response. Is this still an issue? Thanks!

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
