### ISSUE TITLE
tensorflow.python.framework.errors_impl.FailedPreconditionError: temp/G2D19_P2OF_ResHB_1LSTM_dataAug_expLR; Not a directory 

### ISSUE THREAD

**Issue by vandana-rajan** [tensorflow/tensorflow#22389]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: 

Yes. I was trying out the code given in https://github.com/JoshuaPiinRueyPan/ViolenceDetection

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:

Ubuntu 18.04

- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:

NA

- **TensorFlow (CPU version) installed from (source or binary)**:

Installed using pip3 as shown in https://www.python36.com/install-tensorflow-using-official-pip-pacakage/

- **TensorFlow version (use command below)**:

1.9

- **Python version**:

3.6.5

- Machine details

Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  2
Core(s) per socket:  2
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               142
Model name:          Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz

- **Exact command to reproduce**:

>> python Train.py 

This is from the code given in https://github.com/JoshuaPiinRueyPan/ViolenceDetection

### Describe the problem

The code contains an LSTM+CNN network and when training with a set of videos, it fails with a tensorflow error. I checked and found that the 'temp/G2D19_P2OF_ResHB_1LSTM_dataAug_expLR' mentioned in the error log is indeed a directory. However Tensorflow complains that it is not and throws an error. I am unable to understand why.

### Source code / logs

Traceback (most recent call last):
File "Train.py", line 199, in
main = Main()
File "Train.py", line 19, in init
self.trainer = Trainer(classifier)
File "/home/vandana/Documents/Code/ViolenceDetection-master/src/Trainer.py", line 36, in init
self._summaryWriter = tf.summary.FileWriter(trainSettings.PATH_TO_SAVE_MODEL+"/train")
File "/home/vandana/anaconda3/lib/python3.6/site-packages/tensorflow/python/summary/writer/writer.py", line 366, in init
filename_suffix)
File "/home/vandana/anaconda3/lib/python3.6/site-packages/tensorflow/python/summary/writer/event_file_writer.py", line 67, in init
gfile.MakeDirs(self._logdir)
File "/home/vandana/anaconda3/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 379, in recursive_create_dir
pywrap_tensorflow.RecursivelyCreateDir(compat.as_bytes(dirname), status)
File "/home/vandana/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 519, in exit
c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.FailedPreconditionError: temp/G2D19_P2OF_ResHB_1LSTM_dataAug_expLR; Not a directory
Send Stop singal to Loading threads...
The Loading threads will Stop in about 100 (s).
Send Stop singal to Loading threads...
The Loading threads will Stop in about 100 (s).
TrainDataManager.thread.join() successfully.
Exception ignored in: <bound method Main.del of <main.Main object at 0x7f91467b57f0>>
Traceback (most recent call last):
File "Train.py", line 55, in del
self.session.close()
AttributeError: 'Main' object has no attribute 'session'

**Comment by ymodak** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by tensorflowbutler** [comment]
Nagging Assignee @ymodak: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by ymodak** [comment]
Is this still an issue? Can you try updating your TensorFlow version and check is the issue still persists?

**Comment by ymodak** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
