### ISSUE TITLE
numpy not found during python_api generation

### ISSUE THREAD

**Issue by maxnbk** [tensorflow/tensorflow#22395]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: CentOS-7.4
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: None
- **TensorFlow installed from (source or binary)**: Source
- **TensorFlow version (use command below)**: 1.10.1, earlier versions
- **Python version**: 2.7, 3.6 (separate rebuilds same issue)
- **Bazel version (if compiling from source)**: 0.17.1
- **GCC/Compiler version (if compiling from source)**: 4.8.5, 6.3.1 (separate rebuilds same issue)
- **CUDA/cuDNN version**: CPU only build
- **GPU model and memory**: Quadro K4000
- **Exact command to reproduce**: Not reproducible with single command

### Describe the problem
Problem manifests as "No module named numpy", during python api generation as detailed below in log section.

If placing a simple `print(sys.path)` or `print(os.environ['PYTHONPATH'])` in the listed `__init__.py` (in below log), none of the resulting paths listed include the path that numpy is included on via the PYTHONPATH, which is being passed along to the build environ included via bazels CLI opts, `--action_env` and `--test_env` arguments to the build call.

I believe this issue will be reproducible only under a state where someone has installed numpy to a nonstandard location, and is including it via PYTHONPATH and `--action_env` such as is listed. However, all python modules in our environment are in separate paths, as managed by an environment manager, so I cannot install them to a common system path for testing if the issue resolves itself. What is strange is that earlier steps that require numpy have built just fine and not errored from what I can tell.

Apologies if my details included are omitting some crucial detail. The specific set of config values seems unnecessary for detail here, but let me know if they are needed. (Every optional component driven by `TF_NEED_{var}` is turned off except for `TF_NEED_JEMALLOC` which does not appear to be part of the problem)

### Source code / logs

build command, while prefaced by many environment variable changes and the ./configure step, is of the form:
`bazel --batch build --action_env=PYTHONPATH --action_env=LD_LIBRARY_PATH --test_env=PYTHONPATH --test_env=LD_LIBRARY_PATH -c opt --copt=-mfpmath=both --copt=-msse4.2 //tensorflow/tools/pip_package:build_pip_package`

`ERROR: ${build_root}/tensorflow/BUILD:581:1: Executing genrule //tensorflow:tensorflow_python_api_gen failed (Exit 1)
Traceback (most recent call last):
  File "/home/${user}/.cache/bazel/_bazel_${user}/ff38b9a62494579437724e08cde1b695/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api.runfiles/org_tensorflow/tensorflow/python/tools/api/generator/create_python_api.py", line 27, in <module>
    from tensorflow.python.tools.api.generator import doc_srcs
  File "/home/${user}/.cache/bazel/_bazel_${user}/ff38b9a62494579437724e08cde1b695/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 49, in <module>
    import numpy as np
ImportError: No module named numpy`

**Comment by ymodak** [comment]
@maxnbk TensorFlow has a dependency on NumPy module. Please install NumPy and build again.

**Comment by maxnbk** [comment]
numpy is installed. Please read the details more thoroughly. It is simply not in a typical system-installed path, but is available on the PYTHONPATH.

**Comment by gunan** [comment]
Not sure how bazel resolves/uses `PYTHONPATH` I am guessing that may be a part of the problem.
Did you use `pip install` command to install numpy?

**Comment by davidlange6** [comment]
Wanted to report that I've run into the same issue when upgrading from tensorflow 1.6 to 1.10.1 [building from source, we also have a not-very-typical installation of python modules (including numpy). I haven't found a way to force my PYTHONPATH to be used (with --action_env or otherwise)

**Comment by maxnbk** [comment]
pip install was used to install numpy, but you must be aware that people can relocate pip packages with --prefix or --target commands (depending on the install procedure), and as such, PYTHONPATH should be used to find a python module, not relying that all systems or users install it in the same location on every type of host or user environment.

bazel declares in it's docs that --action_env is how one can ensure an environment variable makes it from the shell-executed environment to the build environment, and --test_env is similar but obviously for the test running environments. However it appears it is also required for a bazel build to declare something else I am unfamiliar with in order to propagate the environment to the task which runs the build components. That is the portion that I am declaring there is an issue with.

Glad to hear I am not alone with David Lange, as our last built tensorflow was 1.4.1 . I could attempt to nail down the exact version it stopped working in.

**Comment by gunan** [comment]
CC @annarev

**Comment by maxnbk** [comment]
I was able to produce a working 1.9.0 build, but unable to produce a working 1.10.0 build with the same exact build settings, with completely accurate details as above, e.g. did not do GPU build etc (nothing else was changed other than the release version that I selected.)

**Comment by boegel** [comment]
I'm running into a very similar problem as reported here, where `import keras_applications` fails during the build of TensorFlow 1.11.0 (cfr. #21518), even though `Keras-Applications` is installed in a location listed in `$PYTHONPATH` (installed with `pip install --prefix`, so not in a standard location).

Testing with `python -c "import keras_applications"` confirms that my environment (outside of the Bazel sandbox) is correctly set up.

Like @maxnbk I have tried instructing Bazel (v0.16.0 in my case) to pass down `$PYTHONPATH` using `--action_env=PYTHONPATH`, but that doesn't fix the issue...

Any updates on this?

**Comment by maxnbk** [comment]
I ran a build with the latest 1.12.0-rc0 and experienced the same issue, in case testing it against the most recent release helps locate the problem.

**Comment by annarev** [comment]
Can you try removing PYTHON_LIB_PATH setting from .tf_configure.bazelrc file in the root tensorflow directory? (this file is generated when running ./configure)

Why I think that might work:
We look for pip packages in location specified when running ./configure. This location is stored as value of PYTHON_LIB_PATH in .tf_configure.bazelrc file. If PYTHON_LIB_PATH is not set, then we seem to fallback to PYTHONPATH
(https://github.com/tensorflow/tensorflow/blob/master/third_party/py/python_configure.bzl#L177).

**Comment by annarev** [comment]
Actually I don't think my suggestion above would work. Seems like even if we pick up PYTHONPATH, we only take 1st path in PYTHONPATH. As I understand, this bug is for configurations that have Python modules installed in multiple locations.

@meteorcloudy do you know the right way to pass PYTHONPATH to bazel?

**Comment by meteorcloudy** [comment]
@annarev I think you can use `--action_env=PYTHONPATH`

**Comment by annarev** [comment]
Thank you @meteorcloudy!

hm passing --action_env PYTHONPATH=<pythonpath value> works for me. I tried the following:
1. Setup virtualenv "venv" and install pip dependencies *except keras_applications*
2. Setup virtualenv "venv1" and install *only keras_applications*
3. Then I activate "venv" and run:
```
bazel test tensorflow/tools/api/tests:api_compatibility_test --nocache_test_results
```
It fails because keras_applications is not found, as expected.

4. Then, I run the same but pass PYTHONPATH that points to venv1 site-packages:
```
bazel test --action_env PYTHONPATH="<path to venv1>/venv1/lib/python2.7/site-packages" tensorflow/tools/api/tests:api_compatibility_test --nocache_test_results
```
This command passes.



In case relevant, this is my setup:
```
virtualenv venv1
source venv1/bin/activate
pip install keras_applications==1.0.4
deactivate

virtualenv venv
source venv/bin/activate
pip install --upgrade setuptools==39.1.0
pip install keras_preprocessing==1.0.2
pip install --upgrade six mock portpicker scipy sklearn grpcio
pip install numpy==1.14.5
pip uninstall keras_applications

git clone https://github.com/tensorflow/tensorflow.git
cd tensorflow/
export TF_NEED_CUDA=0
yes "" | python configure.py
```

**Comment by maxnbk** [comment]
That's still just one path inside pythonpath, though? Creating a virtualenv will not be a solve if someone has, for example, some python packages installed at system root, and some at user root, and must build like that.

If you made two venvs and passed a PYTHONPATH var which contains two paths via --action_env would it work?

**Comment by meteorcloudy** [comment]
@maxnbk I believe so, `PYTHONPATH` is like `PATH`, it can contain a list of path instead of just one.

See more from https://docs.python.org/3/using/cmdline.html#envvar-PYTHONPATH

**Comment by maxnbk** [comment]
@meteorcloudy You slightly missed the point here, .. Only one specific path as set, out of many, on the PYTHONPATH is being consumed by the numpy build, or something to that effect, functionally.

**Comment by meteorcloudy** [comment]
I see, @annarev do you know why only one specific path is consumed by the numpy build?

**Comment by annarev** [comment]
My instructions above have a flaw. Really sorry about that! I actually tested by first running a successful build with keras-applications installed, then uninstalled keras-applications and and reran the test. It probably didn't rebuild api-generation genrule for the second run. That's why I missed the error.

I experimented a bit more. Looks like PYTHONPATH gets picked up at runtime but not at genrule execution time. I then tried passing `--distinct_host_configuration=false` to bazel and PYTHONPATH got picked up during genrule execution as well.

So, you can try `--distinct_host_configuration=false` as a workaround if you are building for the same platform where you are running the build.

@meteorcloudy does `--action_env` apply to `host` and/or `target` configuration?

**Comment by maxnbk** [comment]
That workaround (using --distinct_host_configuration=false as part of the bazel build flags) is working for me in non-GPU build tests.
Of course, I don't like workarounds, but it will get me through until a conclusive solve is worked out.
Thanks @annarev . I am happy to run any other tests needed / provide data to help debug further.

**Comment by maxnbk** [comment]
Ah, weird. Perhaps premature. The resulting wheel doesn't want to install on my platform, despite attempting to install for the same platform as the build was run for.

**Comment by meteorcloudy** [comment]
@annarev `--action_env` should apply to both host and target configuration

**Comment by maxnbk** [comment]
Apologies for waffling back and forth, I've gotten the --distinct_host_configuration=false wheel to install, I had a name wrong due to testing on the latest RC and the error is a little bit misleading.
That functions correctly for me. Is there a downside to this if my current platform will always be my target platform?

**Comment by maxnbk** [comment]
Also able to produce valid GPU build with above details still relevant.

**Comment by annarev** [comment]
Its great that it works. Thank you for trying it out @maxnbk. --distinct_host_configuration=false flag is fine so long as your target is same as current platform.

Thank you @meteorcloudy for investigating and opening a bazel bug!

It would be nice if it worked without that flag. I want to look at skipping this genrule during build (instead submitting some data that it generates). So, I will keep this issue open.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @annarev: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by wdirons** [comment]
@annarev, for a similar defect https://github.com/tensorflow/tensorflow/issues/23695, I created this patch: https://github.com/wdirons/tensorflow/commit/01c28a94e63edc8aa301ee377ca026107762858b

Please review and let me know if you think it should be submitted as a PR?

**Comment by tensorflowbutler** [comment]
Nagging Assignee @annarev: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by mohantym** [comment]
Hi @maxnbk!
It seems you are using older versions(1.x versions) of Tensorflow which is not supported any more. Could you confirm whether issue is replicating after [migrating](https://www.tensorflow.org/guide/migrate/migrate_tf2) to 2.6 or not ? Thanks!

**Comment by maxnbk** [comment]
My issue was worked around with the `--distinct_host_configuration=false` flag and my production environment has switched to using wheels after v2.0 I believe, so I don't believe I need this solved personally. I'd still recommend that someone independently verify the issue, as single-pythonpath-entry-consumption could be an issue in any number of other environments, but not mine anymore. Do what you will with the issue according to whichever principles this org operates by. Cheers.

**Comment by mohantym** [comment]
Ok @maxnbk ! Thanks for confirmation. Closing this issue as it seems to be resolved from above comment.

**Comment by mohantym** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
