### ISSUE TITLE
Assign a name to SaprseTensor when build_tensor_info of it

### ISSUE THREAD

**Issue by haotianteng** [tensorflow/tensorflow#22396]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: N.A.
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 1.10.1
- **Python version**: 3.6
- **Bazel version (if compiling from source)**: 0.16.1
- **GCC/Compiler version (if compiling from source)**: gcc version 5.4.0 20160609
- **CUDA/cuDNN version**: 9.0/7.0
- **GPU model and memory**: Tesla P100 16GB
- **Exact command to reproduce**:
A minimum reproduce example:
```
a = tf.constant([[[1.0]]])
b = tf.constant([1])
output,prob = tf.nn.ctc_beam_search_decoder(a,b)
a_tensor_proto = tf.saved_model.utils.build_tensor_info(a)
output_tensor_proto = tf.saved_model.utils.build_tensor_info(output[0]) 
```
### Describe the problem
A normal Tensor has a name:
```
a_tensor_proto
name: "Const_15:0"
dtype: DT_FLOAT
tensor_shape {
  dim {
    size: 1
  }
  dim {
    size: 1
  }
  dim {
    size: 1
  }
}

```
while the SparseTensor from the ctc Beam_Search_Decoder does not has a name:
```
output_tensor_proto
dtype: DT_INT64
tensor_shape {
  dim {
    size: -1
  }
  dim {
    size: -1
  }
}
coo_sparse {
  values_tensor_name: "CTCBeamSearchDecoder_12:1"
  indices_tensor_name: "CTCBeamSearchDecoder_12:0"
  dense_shape_tensor_name: "CTCBeamSearchDecoder_12:2"
}
```
Which cause the error when predict:

```
import tensorflow as tf
from tensorflow.contrib import predictor
from tensorflow.contrib.saved_model.python.saved_model import reader
from tensorflow.contrib.saved_model.python.saved_model import signature_def_utils
from tensorflow.python.tools import saved_model_utils

exp_dir = MY_EXPORT_DIRECTORY
metagraph_def = saved_model_utils.get_meta_graph_def(exp_dir,'serve')
signature_def = signature_def_utils.get_signature_def_by_key(
        metagraph_def,
        'predicted_sequences')
output_names = {k: v.name for k, v in signature_def.outputs.items()}
print(output_names)
predict_fn = predictor.from_saved_model(exp_dir)
seq_len = np.asarray([[4]])
combined_input = np.concatenate((batch_x,seq_len),axis = 1)
predictions = predict_fn({'inputs':combined_input})
```
ValueError: The name '' looks like an (invalid) Operation name, not a Tensor. Tensor names must be of the form "<op_name>:<output_index>".
and  also the above error, when export it into a saved_model and request it.

The reason is when building a TensorProto for the SaprseTensor, no name is assigned to it:
https://github.com/tensorflow/tensorflow/blob/r1.10/tensorflow/python/saved_model/utils_impl.py#L46

### Source code / logs
However, this can be solved by splitting the SaprseTensor into indices, values, dense_shape first and output the dense Tensor, but it would be easier of the name of the Saparse Tensor can be assigned when the TensorProto is created.

**Comment by haotianteng** [comment]
tensorflow/serving#1096

**Comment by haotianteng** [comment]
SparseTensor is a group of three dense tensors: indices, values, and dense_shape, what do you mean by saying it's not actually a tensor?

**Comment by facaiy** [comment]
Sorry, I'm not familiar with tf serving. Yes, as you said, SparseTensor is a group of 3 Tensors. I guess that ValueError might be raised by codes where expect a Tensor (but it receives a SparseTensor? ). Could you post the whole exception stack?

**Comment by facaiy** [comment]
Hi, I didn't find the stack trace of your exception ValueError in those two issues. It should be useful for analysis.

@karmel  @annarev Hi, are you a good person to look at this, or can you redirect as necessary? Thanks!

**Comment by karmel** [comment]
tf-serving should support sparse tensors, as they can be encoded as you show above in the metagraph. Can you provide the stack trace? It's hard to tell from the above what the precise issue is, but my guess is you need to specify options from the set of three names to properly find the tensor:

```
  values_tensor_name: "CTCBeamSearchDecoder_12:1"
  indices_tensor_name: "CTCBeamSearchDecoder_12:0"
  dense_shape_tensor_name: "CTCBeamSearchDecoder_12:2"
```

**Comment by haotianteng** [comment]
Here is the trace:
ErrorReport_tf_SparseTensor_Name/error_reproduce_client.py', wdir='/home/heavens/Documents/ErrorReport_tf_SparseTensor_Name')
{'output': ''}
INFO:tensorflow:Restoring parameters from /home/heavens/Documents/ErrorReport_tf_SparseTensor_Name/TEST_MODEL/export/1/variables/variables
Traceback (most recent call last):

  File "<ipython-input-6-a4394582e9d4>", line 1, in <module>
    runfile('/home/heavens/Documents/ErrorReport_tf_SparseTensor_Name/error_reproduce_client.py', wdir='/home/heavens/Documents/ErrorReport_tf_SparseTensor_Name')

  File "/home/heavens/anaconda3/envs/tensorflow-1.10.1/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "/home/heavens/anaconda3/envs/tensorflow-1.10.1/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/heavens/Documents/ErrorReport_tf_SparseTensor_Name/error_reproduce_client.py", line 23, in <module>
    predict_fn = predictor.from_saved_model(exp_dir)

  File "/home/heavens/anaconda3/envs/tensorflow-1.10.1/lib/python3.6/site-packages/tensorflow/contrib/predictor/predictor_factories.py", line 143, in from_saved_model
    config=config)

  File "/home/heavens/anaconda3/envs/tensorflow-1.10.1/lib/python3.6/site-packages/tensorflow/contrib/predictor/saved_model_predictor.py", line 169, in __init__
    for k, v in output_names.items()}

  File "/home/heavens/anaconda3/envs/tensorflow-1.10.1/lib/python3.6/site-packages/tensorflow/contrib/predictor/saved_model_predictor.py", line 169, in <dictcomp>
    for k, v in output_names.items()}

  File "/home/heavens/anaconda3/envs/tensorflow-1.10.1/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3515, in get_tensor_by_name
    return self.as_graph_element(name, allow_tensor=True, allow_operation=False)

  File "/home/heavens/anaconda3/envs/tensorflow-1.10.1/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3339, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)

  File "/home/heavens/anaconda3/envs/tensorflow-1.10.1/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3413, in _as_graph_element_locked
    raise ValueError(err_msg)

ValueError: The name '' looks like an (invalid) Operation name, not a Tensor. Tensor names must be of the form "<op_name>:<output_index>".

**Comment by haotianteng** [comment]
And here is a reproduce example I try to build by delete unrelated code from my own project:
Export script:
```
import os
import tensorflow as tf
from tensorflow.python.saved_model import signature_constants as sig_constants
from chiron.chiron_model import inference,read_config
from chiron.chiron_eval import path_prob

model_path = "/home/heavens/Documents/ErrorReport_tf_SparseTensor_Name/TEST_MODEL"
OUTPUT = "/home/heavens/Documents/ErrorReport_tf_SparseTensor_Name/TEST_MODEL/export"
def output_list(x,seq_length):
    training = tf.constant(False,dtype = tf.bool,name = 'Training')
    config_path = os.path.join(model_path,'model.json')
    model_configure = read_config(config_path)
    logits, ratio = inference(x, 
                              seq_length, 
                              training=training,
                              full_sequence_len = 4,
                              configure = model_configure)
    ratio = tf.constant(ratio,dtype = tf.float32,shape = [])
    seq_length_r = tf.cast(tf.round(tf.cast(seq_length,dtype = tf.float32)/ratio),tf.int32)
    prob_logits = path_prob(logits)
    predict,log_prob = tf.nn.ctc_beam_search_decoder(tf.transpose(logits, perm=[1, 0, 2]), 
                                            seq_length_r, 
                                            merge_repeated=True,
                                            beam_width = 30)
    return predict[0],logits,prob_logits,log_prob

def build_and_run_exports():
    """Given the latest checkpoint file export the saved model.
    """

    prediction_graph = tf.Graph()
    
    with prediction_graph.as_default():
        x = tf.placeholder(tf.float32, shape=[None, 4])
        seq_len = tf.placeholder(tf.int32, shape = [None])
        #Inference
        predict,logits,prob_logits,log_prob = output_list(x,seq_len)
        values, indices = tf.nn.top_k(logits,k=1)
        saver = tf.train.Saver()

        with tf.Session(graph=prediction_graph) as sess:
            ckpt = tf.train.get_checkpoint_state(model_path)
            if ckpt and ckpt.model_checkpoint_path:
                saver.restore(sess,ckpt.model_checkpoint_path)
            output_path = os.path.join(
                    tf.compat.as_bytes(OUTPUT),
                    tf.compat.as_bytes(str(1)))
            exporter = tf.saved_model.builder.SavedModelBuilder(output_path)
            x_tensor_info = tf.saved_model.utils.build_tensor_info(x)
            seq_len_tensor_info = tf.saved_model.utils.build_tensor_info(seq_len)
            sparse_output_tensor_info = tf.saved_model.utils.build_tensor_info(
                    predict)
            
            prediction_signature = (tf.saved_model.signature_def_utils.build_signature_def(
                inputs = {'x':x_tensor_info,
                          'seq_len':seq_len_tensor_info},
                outputs = {'output':sparse_output_tensor_info},
                method_name=sig_constants.PREDICT_METHOD_NAME))
            
            exporter.add_meta_graph_and_variables(
                sess,
                tags=[tf.saved_model.tag_constants.SERVING],
                signature_def_map={
                        tf.saved_model.signature_constants.DEFAULT_SERVING_SIGNATURE_DEF_KEY:prediction_signature
                },
                main_op=tf.tables_initializer(),
                strip_default_attrs=True)
            exporter.save()


if __name__ == '__main__':
    build_and_run_exports()
```
Predict Script:
```
import tensorflow as tf
from tensorflow.contrib import predictor
from tensorflow.contrib.saved_model.python.saved_model import reader
from tensorflow.contrib.saved_model.python.saved_model import signature_def_utils
from tensorflow.python.tools import saved_model_utils
import numpy as np

exp_dir = "/home/heavens/Documents/ErrorReport_tf_SparseTensor_Name/TEST_MODEL/export/1"
metagraph_def = saved_model_utils.get_meta_graph_def(exp_dir,'serve')
signature_def = signature_def_utils.get_signature_def_by_key(
        metagraph_def,
         tf.saved_model.signature_constants.DEFAULT_SERVING_SIGNATURE_DEF_KEY)
output_names = {k: v.name for k, v in signature_def.outputs.items()}
print(output_names)
predict_fn = predictor.from_saved_model(exp_dir)
batch_x = np.asarray([[[1,1,1,1]]])
seq_len = np.asarray([[4]])
predictions = predict_fn({'x':batch_x,'seq_len':seq_len})
```
[TEST_MODEL.tar.gz](https://github.com/tensorflow/tensorflow/files/2413795/TEST_MODEL.tar.gz)

**Comment by haotianteng** [comment]
The problem can be solved by exporting the three dense tensor of the Sparse Tensor instead of exporting the Sparse Tensor itself, e.g.:
Change
```
sparse_output_tensor_info = tf.saved_model.utils.build_tensor_info(
                    predict)
outputs = {'output':sparse_output_tensor_info}
```

to

```
indices_output_tensor_info = tf.saved_model.utils.build_tensor_info(
                    predict.indices)
values_output_tensor_info = tf.saved_model.utils.build_tensor_info(
                    predict.values)
dense_shape_output_tensor_info = tf.saved_model.utils.build_tensor_info(
                    predict.dense_shape)
 outputs = {'indices':indices_output_tensor_info,
                           'values':values_output_tensor_info,
                           'dense_shape':dense_shape_output_tensor_info}
```
Well I guess it could be an easy fix by redirecting the correct name of SparseTensor when predicting, but I am not sure.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @karmel: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @karmel: It has been 30 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @karmel: It has been 45 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @karmel: It has been 60 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by mckeown12** [comment]
I am experiencing this same issue when attempting to call the predict REST endpoint for a served model:
```
"error": "Tensor :0, specified in either feed_devices or fetch_devices was not found in the Graph"
```
The output tensor in question is a sparse tensor resulting from a 
[tf.string_split()](https://www.tensorflow.org/api_docs/python/tf/string_split) call.

**Comment by gauravgola96** [comment]
@mckeown12 did you find the solution?

**Comment by mckeown12** [comment]
That depends... does using PyTorch count as a solution?

**Comment by gauravgola96** [comment]
@mckeown12 Yes, please share whatever you have done it might be useful

**Comment by mohantym** [comment]
Hi @haotianteng ! You can use [tf.name_scope](https://www.tensorflow.org/api_docs/python/tf/name_scope) from the 2.x version to assign names to operators . Attached [gist](https://colab.sandbox.google.com/gist/mohantym/db64c1743e8fc24b43968c50bd99a9f2/git_22396.ipynb) for reference . Thank you!
