### ISSUE TITLE
InvalidArgumentError when SparseTensorValue is not ordered by row then col

### ISSUE THREAD

**Issue by jilljenn** [tensorflow/tensorflow#22438]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac OS 10.13.6
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: no
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: v1.10.0-rc1-19-g656e7a2b34 1.10.0
- **Python version**: 3.6.5
- **Bazel version (if compiling from source)**: no
- **GCC/Compiler version (if compiling from source)**: no
- **CUDA/cuDNN version**: no
- **GPU model and memory**: no
- **Exact command to reproduce**: `python bug.py`

### Describe the problem

If we feed a `SparseTensorValue` to `tf.data.Dataset.from_tensor_slices` such that its indices are not lexicographically sorted by row then col, then we will get a `InvalidArgumentError`.

Maybe it could be said in the docs, or the error should provide a clearer message. It was hard to guess that `indices[2] = [1,0] is out of order` meant the indices were not provided in lexicographic order.

I finally saw that it was explained in the [`SparseTensor` docs](https://www.tensorflow.org/api_docs/python/tf/SparseTensor), but I feel it should be said in the [`SparseTensorValue` docs](https://www.tensorflow.org/api_docs/python/tf/SparseTensorValue) as well.

### Source code / logs

```python
from scipy.sparse import csr_matrix
import tensorflow as tf
import numpy as np


M = np.array([[0, 1, 1], [1, 0, 0], [1, 0, 2], [0, 1, 1]])

# First observation: these two slicing operations provide different orderings
S = csr_matrix(M)[1:3].tocoo()
print('1:3', S.row, S.col)
S = csr_matrix(M)[[1, 2]].tocoo()
print('1,2', S.row, S.col)

entries = np.column_stack((S.row, S.col, S.data))
ordering = np.arange(len(S.data))

# Uncomment the following line to fix the error
# ordering = np.lexsort((S.col, S.row))  # Sort by row then col

X_train = tf.SparseTensorValue(indices=entries[ordering, :2],
                               values=entries[ordering, 2],
                               dense_shape=S.shape)

dataset = tf.data.Dataset.from_tensor_slices(X_train)
iterator = dataset.make_initializable_iterator()
X_sample = iterator.get_next()

with tf.Session() as sess:
    sess.run(iterator.initializer)
    print(sess.run(X_sample))
```

    Traceback (most recent call last):
      File "/Users/jilljenn/code/vae/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1278, in _do_call
        return fn(*args)
      File "/Users/jilljenn/code/vae/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1263, in _run_fn
        options, feed_dict, fetch_list, target_list, run_metadata)
      File "/Users/jilljenn/code/vae/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _call_tf_sessionrun
        run_metadata)
    tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[2] = [1,0] is out of order
         [[Node: SerializeManySparse = SerializeManySparse[T=DT_INT64, out_type=DT_VARIANT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](tensors/SparseTensor/indices, tensors/SparseTensor/values, tensors/SparseTensor/dense_shape)]]

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "bug.py", line 27, in <module>
        sess.run(iterator.initializer)
      File "/Users/jilljenn/code/vae/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 877, in run
        run_metadata_ptr)
      File "/Users/jilljenn/code/vae/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1100, in _run
        feed_dict_tensor, options, run_metadata)
      File "/Users/jilljenn/code/vae/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1272, in _do_run
        run_metadata)
      File "/Users/jilljenn/code/vae/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1291, in _do_call
        raise type(e)(node_def, op, message)
    tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[2] = [1,0] is out of order
         [[Node: SerializeManySparse = SerializeManySparse[T=DT_INT64, out_type=DT_VARIANT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](tensors/SparseTensor/indices, tensors/SparseTensor/values, tensors/SparseTensor/dense_shape)]]

    Caused by op 'SerializeManySparse', defined at:
      File "bug.py", line 22, in <module>
        dataset = tf.data.Dataset.from_tensor_slices(X_train)
      File "/Users/jilljenn/code/vae/venv/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 254, in from_tensor_slices
        return TensorSliceDataset(tensors)
      File "/Users/jilljenn/code/vae/venv/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1173, in __init__
        self._tensors = sparse.serialize_many_sparse_tensors(tensors)
      File "/Users/jilljenn/code/vae/venv/lib/python3.6/site-packages/tensorflow/python/data/util/sparse.py", line 132, in serialize_many_sparse_tensors
        for tensor in nest.flatten(tensors)
      File "/Users/jilljenn/code/vae/venv/lib/python3.6/site-packages/tensorflow/python/data/util/sparse.py", line 132, in <listcomp>
        for tensor in nest.flatten(tensors)
      File "/Users/jilljenn/code/vae/venv/lib/python3.6/site-packages/tensorflow/python/ops/sparse_ops.py", line 1469, in serialize_many_sparse
        out_type=out_type)
      File "/Users/jilljenn/code/vae/venv/lib/python3.6/site-packages/tensorflow/python/ops/gen_sparse_ops.py", line 502, in serialize_many_sparse
        out_type=out_type, name=name)
      File "/Users/jilljenn/code/vae/venv/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
        op_def=op_def)
      File "/Users/jilljenn/code/vae/venv/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
        return func(*args, **kwargs)
      File "/Users/jilljenn/code/vae/venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3155, in create_op
        op_def=op_def)
      File "/Users/jilljenn/code/vae/venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1717, in __init__
        self._traceback = tf_stack.extract_stack()

    InvalidArgumentError (see above for traceback): indices[2] = [1,0] is out of order
         [[Node: SerializeManySparse = SerializeManySparse[T=DT_INT64, out_type=DT_VARIANT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](tensors/SparseTensor/indices, tensors/SparseTensor/values, tensors/SparseTensor/dense_shape)]]

**Comment by wt-huang** [comment]
@jilljenn Good catch and agreed that more clarity on SparseTensorValue would help. 

@MarkDaoust Can you take a look at this?

**Comment by wt-huang** [comment]
Closing this issue, we will add this to the future release.

**Comment by hiro-o918** [comment]
I've also met this error and been confused this message.
I hope you to implement some sorting function to avoid this error as well as to update the message.

- Environment: 
    - macOS: 10.14.4
    - docker: 19.03.1
    - docker image: tensorflow/tensorflow:latest-py3

**Comment by MarkDaoust** [comment]
@hiro-o918 thanks for pinging this bug, 

I've improved the error message to point people in the right direction:

```
 InvalidArgumentError (see above for traceback): indices[2] = [1,0] is out of order. Many sparse ops require sorted indices.
    Use `tf.sparse.reorder` to create a correctly ordered copy.
```
