### ISSUE TITLE
No functions or submodules are installed in 1.11.0rc1 when compiled from source

### ISSUE THREAD

**Issue by nelsyeung** [tensorflow/tensorflow#22445]
### System information
- **OS**: `uname -a`: Linux pnode1.cluster 3.10.0-514.el7.ppc64le #1 SMP Sat Nov 5 15:08:14 GMT 2016 ppc64le ppc64le ppc64le GNU/Linux
- **TensorFlow installed from**: source
- **TensorFlow version**: 1.11.0rc1
- **Python version**: 3.5.6
- **Bazel version**: 0.17.1
- **GCC/Compiler version**: gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)
- **CUDA/cuDNN version**: 9.1
- **GPU model and memory**: NVIDIA Tesla P100
- **Exact command to reproduce**: `python3.5 -c "import tensorflow.keras"`

### Reproduction steps
Compile and install Tensorflow from source:
```
git clone https://github.com/tensorflow/tensorflow.git
cd tensorflow
./configure
# Leave everything as default except for cuda options which I chose 9.1 and the correct cuda path
bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg
cp /tmp/tensorflow_pkg/tensorflow-1.11.0rc1-cp35-cp35m-linux_ppc64le.whl ../
cd ..
pip3.5 install tensorflow-1.11.0rc1-cp35-cp35m-linux_ppc64le.whl
```
Test `tensorflow.keras`:
```
python3.5 -c "import tensorflow.keras"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named 'tensorflow.keras'
```
Test other functions:
```
$ python3.5
>>> x = tf.constant([[-2.25 + 4.75j], [-3.25 + 5.75j]])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'tensorflow' has no attribute 'constant'
```

### Pip packages
`pip3.5 list`:
```
absl-py                  0.5.0
alabaster                0.7.11
appdirs                  1.4.3
astor                    0.7.1
atomicwrites             1.2.1
attrs                    18.2.0
Babel                    2.6.0
certifi                  2018.8.24
chardet                  3.0.4
Cython                   0.28.5
decorator                4.3.0
docutils                 0.14
gast                     0.2.0
grpcio                   1.15.0
h5py                     2.8.0
idna                     2.7
imagesize                1.1.0
Jinja2                   2.10
Keras                    2.2.2
Keras-Applications       1.0.5
Keras-Preprocessing      1.0.3
Mako                     1.0.7
Markdown                 2.6.11
MarkupSafe               1.0
mock                     2.0.0
more-itertools           4.3.0
nose                     1.3.7
numpy                    1.15.1
packaging                17.1
pathlib2                 2.3.2
pbr                      4.2.0
pip                      18.0
pluggy                   0.7.1
protobuf                 3.6.1
py                       1.6.0
pydot                    1.2.4
pydot-ng                 1.0.0
Pygments                 2.2.0
PyGraph                  0.2.1
pygraphviz               1.5
pyparsing                2.2.1
pytest                   3.8.0
pytools                  2018.5.2
pytz                     2018.5
PyYAML                   3.13
requests                 2.19.1
scipy                    1.1.0
setuptools               28.8.0
six                      1.11.0
snowballstemmer          1.2.1
Sphinx                   1.8.0
sphinxcontrib-websupport 1.1.0
tensorboard              1.10.0
tensorflow               1.11.0rc1
termcolor                1.1.0
urllib3                  1.23
Werkzeug                 0.14.1
wheel                    0.31.1
```

**Comment by ymodak** [comment]
@nelsyeung Can you try : import tensorflow.python.keras ?
This should solve your import problem.

**Comment by nelsyeung** [comment]
`import tensorflow.python.keras` also would not work:
```
python3.5 -c "import tensorflow.python.keras"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named 'tensorflow.python'
```
@ymodak I'd recommend you to familiarize yourself with the [Tensorflow documentation](https://www.tensorflow.org/api_docs/python/tf). Ever since v1.9 `tensorflow.python.keras` is moved to `tensorflow.keras`.

### Some further information:
- I cleaned up the system and recompiled everything from scratch, but that didn't help.

- I just realized that nothing from Tensorflow is actually working, even though it took around 3 hours to compile. Did I miss some installation steps that's not documented? For example:
```
>>> x = tf.constant([[-2.25 + 4.75j], [-3.25 + 5.75j]])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'tensorflow' has no attribute 'constant'
```
- On my cluster, v1.10 and v1.9 branch simply gives too many compilation errors for me to solve them all, that's why I'm doing it on the master branch since it actually compiles.

- I only know for a fact that the below commit from v1.6 would work perfectly for Python 2.7 on my system. I will try to compile that for Python 3.5 later:
```
git checkout `git rev-list -n 1 --before="2018-02-23 18:00" master`
```

**Comment by nelsyeung** [comment]
@gunan I apologize that I didn't rename the title after my discovery that *nothing from Tensorflow is actually working*.

I'd recommend you to also familiarize yourself with the [Tensorflow Guide](https://www.tensorflow.org/guide/keras). Ever since v1.10, it **is** possible to import `tensorflow.keras` using, and I quote from the above link,
```
import tensorflow as tf
from tensorflow import keras
```
There was an issue sometime ago discussing `tf.keras` is simply too frustrating to use.

Furthermore, just test this before you recommend anything, I can see that the below works fine on macOS with pip (I'm using pyenv to isolate all my Python packages and versions):
```
pip install tensorflow==1.11.0rc1
python3.5 -c "import tensorflow.keras"
```

Have a read on my [further information comment](https://github.com/tensorflow/tensorflow/issues/22445#issuecomment-423619601) just above yours.

**Comment by annarev** [comment]
I just tried building and installing from head. The only difference is that I built a CPU-only package.
python3 -m venv venv/
source venv/bin/activate

git clone https://github.com/tensorflow/tensorflow.git
cd tensorflow

pip install keras_applications==1.0.4
pip install keras_preprocessing==1.0.2
pip install --upgrade six mock portpicker scipy sklearn grpcio
pip install numpy==1.14.5
pip install h5py==2.8.0

# Here I picked default for everything
./configure

bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package

# Move out of tensorflow directory before installing tensorflow pip package.
cd ..
pip install /tmp/tensorflow_pkg/tensorflow-1.11.0rc1-cp35-cp35m-linux_x86_64.whl

"from tensorflow import keras" worked fine after this step. I don't know if we want to support this type of import long term, however.
I might try GPU build later today, but for now you can check if anything is missing.

**Comment by gunan** [comment]
@nelsyeung You are right. I apologize for the misleading information I provided.
Looks like the top level modules under tensorflow are expected to work like that, at least for now.
However, we have no tests that verify these work. Therefore, any breakages on this has been invisible to us.

**Comment by annarev** [comment]
I just tried GPU build (with Python 2.7 this time). "from tensorflow import keras" works fine.

For GPU build, I also had to set nccl and cudnn, but the other steps were the same.

**Comment by nelsyeung** [comment]
I feel like that I must be missing some sort of environment variables, since this is a cluster a lot of the paths has to be set myself, can someone please check whether I'm missing anything:
```sh
export PNODE=/home/user/pnode
export PATH=$PNODE/bin:$PATH
export LD_LIBRARY_PATH=$PNODE/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$PNODE/lib64:$LD_LIBRARY_PATH
export PYTHONPATH=$PNODE/lib/python3.5
export CPATH=$PNODE/include:$CPATH
export PKG_CONFIG_PATH=$PNODE/lib/pkgconfig:$PKG_CONFIG_PATH
export CUDA_HOME=$PNODE/cuda-9.1
export PATH=$CUDA_HOME/bin:$PATH
export CPATH=$CUDA_HOME/include:$CPATH
export LD_LIBRARY_PATH=$CUDA_HOME/lib64:$LD_LIBRARY_PATH
```
The only real clue to what's wrong is that I can import Tensorflow with no errors, but just that none of its functions or sub-modules work.

I'll recompile everything later and give my full reproduction steps that includes building Python, cmake, OpenBlas, HDF5, Bazel and finally Tensorflow.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @ymodak: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by nelsyeung** [comment]
No time to recompile everything and deal with this, decided to just revert Python 2.7 and Tensorflow 1.6.
