### ISSUE TITLE
Issue with gradients computation when using stop_gradient on a map_fn output

### ISSUE THREAD

**Issue by jnd77** [tensorflow/tensorflow#22448]
------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOs
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: v1.10.0-rc1-19-g656e7a2b34
- **Python version**: 3.6
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:

### Describe the problem

When training the model, the error with the stack trace below occurs randomly.
Original exception is thrown from there:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/tensor_array.h#L571

The error disappears if I remove the `stop_gradient`.

### Code

Unfortunately, I haven't managed to replicate the issue with a small piece of code.
Basically, I have a model where a layer forward pass is based on `map_fn`. Inside the function called by `map_fn`, there is a `tf.cond`.
Downstream this layer, there is another layer with a `stop_gradient` on one of the outputs of the previous layer.

### Error stack

```
2018-09-21 20:54:20.894525: W tensorflow/core/framework/op_kernel.cc:1275] OP_REQUIRES failed at tensor_array_ops.cc:527 : Invalid argument: TensorArray scene_model/roi_filter_layer/map/TensorArray_3_8140@gradients: Could not read from TensorArray index 0.  Furthermore, the element shape is not fully defined: <unknown>.  It is possible you are working with a resizeable TensorArray and stop_gradients is not allowing the gradients to be written.  If you set the full element_shape property on the forward TensorArray, the proper all-zeros tensor will be returned instead of incurring this error.
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/mask_rcnn_cpu/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1278, in _do_call
    return fn(*args)
  File "/usr/local/anaconda3/envs/mask_rcnn_cpu/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1263, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/local/anaconda3/envs/mask_rcnn_cpu/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: TensorArray scene_model/roi_filter_layer/map/TensorArray_3_8140@gradients: Could not read from TensorArray index 0.  Furthermore, the element shape is not fully defined: <unknown>.  It is possible you are working with a resizeable TensorArray and stop_gradients is not allowing the gradients to be written.  If you set the full element_shape property on the forward TensorArray, the proper all-zeros tensor will be returned instead of incurring this error.
	 [[Node: gradients/scene_model/roi_filter_layer/map/while/TensorArrayWrite/TensorArrayWriteV3_grad/TensorArrayReadV3 = TensorArrayReadV3[dtype=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](gradients/scene_model/roi_filter_layer/map/while/TensorArrayWrite/TensorArrayWriteV3_grad/TensorArrayGrad/TensorArrayGradV3, gradients/scene_model/roi_filter_layer/map/while/TensorArrayWrite_2/TensorArrayWriteV3_grad/TensorArrayReadV3/StackPopV2, gradients/scene_model/roi_filter_layer/map/while/Merge_2_grad/Switch:1)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jnd/dev/mask_rcnn/scripts/train_eval_export/new_train.py", line 55, in <module>
    train(config_path)
  File "/Users/jnd/dev/mask_rcnn/scripts/train_eval_export/new_train.py", line 48, in train
    training_schedule=training_program, epoch_offset=0)
  File "/Users/jnd/dev/mask_rcnn/libs/models/scene/helpers/model_trainer.py", line 91, in train
    estimator.train(input_fn=input_fn_train, steps=self.config.STEPS_PER_EPOCH)
  File "/usr/local/anaconda3/envs/mask_rcnn_cpu/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 376, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/anaconda3/envs/mask_rcnn_cpu/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1145, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/usr/local/anaconda3/envs/mask_rcnn_cpu/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1173, in _train_model_default
    saving_listeners)
  File "/usr/local/anaconda3/envs/mask_rcnn_cpu/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1451, in _train_with_estimator_spec
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/usr/local/anaconda3/envs/mask_rcnn_cpu/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 583, in run
    run_metadata=run_metadata)
  File "/usr/local/anaconda3/envs/mask_rcnn_cpu/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1059, in run
    run_metadata=run_metadata)
  File "/usr/local/anaconda3/envs/mask_rcnn_cpu/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1150, in run
    raise six.reraise(*original_exc_info)
  File "/usr/local/anaconda3/envs/mask_rcnn_cpu/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/anaconda3/envs/mask_rcnn_cpu/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1135, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/local/anaconda3/envs/mask_rcnn_cpu/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1207, in run
    run_metadata=run_metadata)
  File "/usr/local/anaconda3/envs/mask_rcnn_cpu/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 987, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/local/anaconda3/envs/mask_rcnn_cpu/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 877, in run
    run_metadata_ptr)
  File "/usr/local/anaconda3/envs/mask_rcnn_cpu/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1100, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/anaconda3/envs/mask_rcnn_cpu/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1272, in _do_run
    run_metadata)
  File "/usr/local/anaconda3/envs/mask_rcnn_cpu/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1291, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: TensorArray scene_model/roi_filter_layer/map/TensorArray_3_8140@gradients: Could not read from TensorArray index 0.  Furthermore, the element shape is not fully defined: <unknown>.  It is possible you are working with a resizeable TensorArray and stop_gradients is not allowing the gradients to be written.  If you set the full element_shape property on the forward TensorArray, the proper all-zeros tensor will be returned instead of incurring this error.
	 [[Node: gradients/scene_model/roi_filter_layer/map/while/TensorArrayWrite/TensorArrayWriteV3_grad/TensorArrayReadV3 = TensorArrayReadV3[dtype=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](gradients/scene_model/roi_filter_layer/map/while/TensorArrayWrite/TensorArrayWriteV3_grad/TensorArrayGrad/TensorArrayGradV3, gradients/scene_model/roi_filter_layer/map/while/TensorArrayWrite_2/TensorArrayWriteV3_grad/TensorArrayReadV3/StackPopV2, gradients/scene_model/roi_filter_layer/map/while/Merge_2_grad/Switch:1)]]

Caused by op 'gradients/scene_model/roi_filter_layer/map/while/TensorArrayWrite/TensorArrayWriteV3_grad/TensorArrayReadV3', defined at:
  File "/Users/jnd/dev/mask_rcnn/scripts/train_eval_export/new_train.py", line 55, in <module>
    train(config_path)
  File "/Users/jnd/dev/mask_rcnn/scripts/train_eval_export/new_train.py", line 48, in train
    training_schedule=training_program, epoch_offset=0)
  File "/Users/jnd/dev/mask_rcnn/libs/models/scene/helpers/model_trainer.py", line 91, in train
    estimator.train(input_fn=input_fn_train, steps=self.config.STEPS_PER_EPOCH)
  File "/usr/local/anaconda3/envs/mask_rcnn_cpu/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 376, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/anaconda3/envs/mask_rcnn_cpu/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1145, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/usr/local/anaconda3/envs/mask_rcnn_cpu/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1170, in _train_model_default
    features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
  File "/usr/local/anaconda3/envs/mask_rcnn_cpu/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1133, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/Users/jnd/dev/mask_rcnn/libs/models/scene/helpers/estimator.py", line 84, in model_fn
    grad_vars = optimizer.compute_gradients(loss, var_list=trainable_variables)
  File "/usr/local/anaconda3/envs/mask_rcnn_cpu/lib/python3.6/site-packages/tensorflow/python/training/optimizer.py", line 514, in compute_gradients
    colocate_gradients_with_ops=colocate_gradients_with_ops)
  File "/usr/local/anaconda3/envs/mask_rcnn_cpu/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 596, in gradients
    gate_gradients, aggregation_method, stop_gradients)
  File "/usr/local/anaconda3/envs/mask_rcnn_cpu/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 779, in _GradientsHelper
    lambda: grad_fn(op, *out_grads))
  File "/usr/local/anaconda3/envs/mask_rcnn_cpu/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 398, in _MaybeCompile
    return grad_fn()  # Exit early
  File "/usr/local/anaconda3/envs/mask_rcnn_cpu/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 779, in <lambda>
    lambda: grad_fn(op, *out_grads))
  File "/usr/local/anaconda3/envs/mask_rcnn_cpu/lib/python3.6/site-packages/tensorflow/python/ops/tensor_array_grad.py", line 132, in _TensorArrayWriteGrad
    grad = g.read(index)
  File "/usr/local/anaconda3/envs/mask_rcnn_cpu/lib/python3.6/site-packages/tensorflow/python/ops/tensor_array_ops.py", line 824, in read
    return self._implementation.read(index, name=name)
  File "/usr/local/anaconda3/envs/mask_rcnn_cpu/lib/python3.6/site-packages/tensorflow/python/ops/tensor_array_ops.py", line 258, in read
    name=name)
  File "/usr/local/anaconda3/envs/mask_rcnn_cpu/lib/python3.6/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 6515, in tensor_array_read_v3
    dtype=dtype, name=name)
  File "/usr/local/anaconda3/envs/mask_rcnn_cpu/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/anaconda3/envs/mask_rcnn_cpu/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "/usr/local/anaconda3/envs/mask_rcnn_cpu/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3155, in create_op
    op_def=op_def)
  File "/usr/local/anaconda3/envs/mask_rcnn_cpu/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1717, in __init__
    self._traceback = tf_stack.extract_stack()

...which was originally created as op 'scene_model/roi_filter_layer/map/while/TensorArrayWrite/TensorArrayWriteV3', defined at:
  File "/Users/jnd/dev/mask_rcnn/scripts/train_eval_export/new_train.py", line 55, in <module>
    train(config_path)
[elided 5 identical lines from previous traceback]
  File "/usr/local/anaconda3/envs/mask_rcnn_cpu/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1133, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/Users/jnd/dev/mask_rcnn/libs/models/scene/helpers/estimator.py", line 56, in model_fn
    outputs = model(features, training=(mode == tf.estimator.ModeKeys.TRAIN), train_bn=train_bn)
  File "/usr/local/anaconda3/envs/mask_rcnn_cpu/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 736, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/Users/jnd/dev/mask_rcnn/libs/models/scene/model.py", line 197, in call
    rcnn_outputs = self.object_rcnn_model.call(inputs, **kwargs)
  File "/Users/jnd/dev/mask_rcnn/libs/models/scene/head/rcnn/object_rcnn.py", line 160, in call
    filter_outputs = self.roi_filter_layer(filter_inputs, **kwargs)
  File "/usr/local/anaconda3/envs/mask_rcnn_cpu/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 736, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/Users/jnd/dev/mask_rcnn/libs/models/scene/head/rcnn/roi_filter_layer.py", line 77, in call
    (tf.float32, tf.int32, tf.float32))
  File "/usr/local/anaconda3/envs/mask_rcnn_cpu/lib/python3.6/site-packages/tensorflow/python/ops/functional_ops.py", line 459, in map_fn
    maximum_iterations=n)
  File "/usr/local/anaconda3/envs/mask_rcnn_cpu/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3232, in while_loop
    return_same_structure)
  File "/usr/local/anaconda3/envs/mask_rcnn_cpu/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2952, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/usr/local/anaconda3/envs/mask_rcnn_cpu/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2887, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/usr/local/anaconda3/envs/mask_rcnn_cpu/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3201, in <lambda>
    body = lambda i, lv: (i + 1, orig_body(*lv))
  File "/usr/local/anaconda3/envs/mask_rcnn_cpu/lib/python3.6/site-packages/tensorflow/python/ops/functional_ops.py", line 451, in compute
    tas = [ta.write(i, value) for (ta, value) in zip(tas, flat_fn_values)]
  File "/usr/local/anaconda3/envs/mask_rcnn_cpu/lib/python3.6/site-packages/tensorflow/python/ops/functional_ops.py", line 451, in <listcomp>
    tas = [ta.write(i, value) for (ta, value) in zip(tas, flat_fn_values)]
  File "/usr/local/anaconda3/envs/mask_rcnn_cpu/lib/python3.6/site-packages/tensorflow/python/util/tf_should_use.py", line 118, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs))

InvalidArgumentError (see above for traceback): TensorArray scene_model/roi_filter_layer/map/TensorArray_3_8140@gradients: Could not read from TensorArray index 0.  Furthermore, the element shape is not fully defined: <unknown>.  It is possible you are working with a resizeable TensorArray and stop_gradients is not allowing the gradients to be written.  If you set the full element_shape property on the forward TensorArray, the proper all-zeros tensor will be returned instead of incurring this error.
	 [[Node: gradients/scene_model/roi_filter_layer/map/while/TensorArrayWrite/TensorArrayWriteV3_grad/TensorArrayReadV3 = TensorArrayReadV3[dtype=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](gradients/scene_model/roi_filter_layer/map/while/TensorArrayWrite/TensorArrayWriteV3_grad/TensorArrayGrad/TensorArrayGradV3, gradients/scene_model/roi_filter_layer/map/while/TensorArrayWrite_2/TensorArrayWriteV3_grad/TensorArrayReadV3/StackPopV2, gradients/scene_model/roi_filter_layer/map/while/Merge_2_grad/Switch:1)]]

```

**Comment by jnd77** [comment]
Hi @ymodak. Sorry for the late reply, I was out of office. Let me see what I can do. Tricky to reproduce race conditions issues ...

**Comment by jnd77** [comment]
Sorry, haven't managed to do a repro with a simple code. Will close it for now ...

**Comment by Frank17** [comment]
```python
input_placeholer = tf.placeholder(tf.float32, shape=(None, None, 3))
sizes = [2, 3]
result = tf.TensorArray(tf.float32, size=1, dynamic_size=True, infer_shape=False)
for i in sizes:
    tensor_arr = tf.TensorArray(tf.float32, size=1, dynamic_size=True)
    for j in range(i):
        tensor_arr = tensor_arr.write(j, input_placeholer)
    result = result.write(i, tensor_arr.stack())

result = result.concat()

init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    print(sess.run([tf.shape(result)], feed_dict={input_placeholer: np.random.randn(10, 10, 3)}))
```

This code can reproduce this issue.
