### ISSUE TITLE
[bazel] Unrecoverable error while evaluating node '//tensorflow/cc:ops/io_ops_gen_cc

### ISSUE THREAD

**Issue by pauldelmusica** [tensorflow/tensorflow#22459]
I am running bazel  0.17.2 on Windows 7, with the following command:
bazel build tensorflow/examples/wav_to_spectrogram/...

The output:

c:\tensorflow-master>bazel build tensorflow/examples/wav_to_spectrogram/...
Loading:
Loading: 0 packages loaded
DEBUG: C:/users/me/_bazel_me/cxy76ymx/external/bazel_tools/tools/cpp/lib_cc_conf
igure.bzl:115:5:
Auto-Configuration Warning: 'BAZEL_VC' is not set, start looking for the latest
Visual C++ installed.
DEBUG: C:/users/me/_bazel_me/cxy76ymx/external/bazel_tools/tools/cpp/lib_cc_conf
igure.bzl:115:5:
Auto-Configuration Warning: Looking for VS%VERSION%COMNTOOLS environment variabl
es, eg. VS140COMNTOOLS
DEBUG: C:/users/me/_bazel_me/cxy76ymx/external/bazel_tools/tools/cpp/lib_cc_conf
igure.bzl:115:5:
Auto-Configuration Warning: Visual C++ build tools found at C:\Program Files (x8
6)\Microsoft Visual Studio 12.0\VC\
Analyzing: 3 targets (0 packages loaded)
Analyzing: 3 targets (0 packages loaded)
Analyzing: 3 targets (1 packages loaded)
WARNING: C:/tensorflow-master/tensorflow/core/BUILD:2501:1: in includes attribut
e of cc_library rule //tensorflow/core:framework_internal_headers_lib: '../../ex
ternal/com_google_absl' resolves to 'external/com_google_absl' not below the rel
ative path of its package 'tensorflow/core'. This will be an error in the future
. Since this rule was created by the macro 'cc_header_only_library', the error m
ight have been caused by the macro implementation in C:/tensorflow-master/tensor
flow/tensorflow.bzl:1376:20
WARNING: C:/tensorflow-master/tensorflow/core/BUILD:2587:1: in includes attribut
e of cc_library rule //tensorflow/core:framework_headers_lib: '../../external/co
m_google_absl' resolves to 'external/com_google_absl' not below the relative pat
h of its package 'tensorflow/core'. This will be an error in the future. Since t
his rule was created by the macro 'cc_header_only_library', the error might have
 been caused by the macro implementation in C:/tensorflow-master/tensorflow/tens
orflow.bzl:1376:20
Unhandled exception thrown during build; message: Unrecoverable error while eval
uating node '//tensorflow/cc:ops/io_ops_gen_cc BuildConfigurationValue.Key[ac98f
5975123fd6eeb07a7415b6161fb] true' (requested by nodes '//tensorflow/cc:io_ops_g
enrule BuildConfigurationValue.Key[6a75becf8194103d260d4e5a345be2c2] false')
INFO: Elapsed time: 31.631s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (2 packages loaded)
java.lang.RuntimeException: Unrecoverable error while evaluating node '//tensorf
low/cc:ops/io_ops_gen_cc BuildConfigurationValue.Key[ac98f5975123fd6eeb07a7415b6
161fb] true' (requested by nodes '//tensorflow/cc:io_ops_genrule BuildConfigurat
ionValue.Key[6a75becf8194103d260d4e5a345be2c2] false')
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate
.run(AbstractParallelEvaluator.java:497)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$Wrapped
Runnable.run(AbstractQueueVisitor.java:368)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown S
ource)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown
Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException
        at com.google.common.base.Preconditions.checkState(Preconditions.java:49
1)
        at com.google.devtools.build.lib.rules.cpp.LibrariesToLinkCollector.addD
ynamicInputLinkOptions(LibrariesToLinkCollector.java:290)
        at com.google.devtools.build.lib.rules.cpp.LibrariesToLinkCollector.addL
inkerInputs(LibrariesToLinkCollector.java:258)
        at com.google.devtools.build.lib.rules.cpp.LibrariesToLinkCollector.coll
ectLibrariesToLink(LibrariesToLinkCollector.java:203)
        at com.google.devtools.build.lib.rules.cpp.CppLinkActionBuilder.build(Cp
pLinkActionBuilder.java:916)
        at com.google.devtools.build.lib.rules.cpp.CcBinary.init(CcBinary.java:4
13)
        at com.google.devtools.build.lib.rules.cpp.CcBinary.create(CcBinary.java
:179)
        at com.google.devtools.build.lib.rules.cpp.CcBinary.create(CcBinary.java
:71)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.create
Rule(ConfiguredTargetFactory.java:320)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.create
ConfiguredTarget(ConfiguredTargetFactory.java:205)
        at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfig
uredTarget(SkyframeBuildView.java:631)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.creat
eConfiguredTarget(ConfiguredTargetFunction.java:770)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compu
te(ConfiguredTargetFunction.java:320)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate
.run(AbstractParallelEvaluator.java:420)
        ... 4 more
java.lang.RuntimeException: Unrecoverable error while evaluating node '//tensorf
low/cc:ops/io_ops_gen_cc BuildConfigurationValue.Key[ac98f5975123fd6eeb07a7415b6
161fb] true' (requested by nodes '//tensorflow/cc:io_ops_genrule BuildConfigurat
ionValue.Key[6a75becf8194103d260d4e5a345be2c2] false')
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate
.run(AbstractParallelEvaluator.java:497)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$Wrapped
Runnable.run(AbstractQueueVisitor.java:368)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown S
ource)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown
Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException
        at com.google.common.base.Preconditions.checkState(Preconditions.java:49
1)
        at com.google.devtools.build.lib.rules.cpp.LibrariesToLinkCollector.addD
ynamicInputLinkOptions(LibrariesToLinkCollector.java:290)
        at com.google.devtools.build.lib.rules.cpp.LibrariesToLinkCollector.addL
inkerInputs(LibrariesToLinkCollector.java:258)
        at com.google.devtools.build.lib.rules.cpp.LibrariesToLinkCollector.coll
ectLibrariesToLink(LibrariesToLinkCollector.java:203)
        at com.google.devtools.build.lib.rules.cpp.CppLinkActionBuilder.build(Cp
pLinkActionBuilder.java:916)
        at com.google.devtools.build.lib.rules.cpp.CcBinary.init(CcBinary.java:4
13)
        at com.google.devtools.build.lib.rules.cpp.CcBinary.create(CcBinary.java
:179)
        at com.google.devtools.build.lib.rules.cpp.CcBinary.create(CcBinary.java
:71)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.create
Rule(ConfiguredTargetFactory.java:320)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.create
ConfiguredTarget(ConfiguredTargetFactory.java:205)
        at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfig
uredTarget(SkyframeBuildView.java:631)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.creat
eConfiguredTarget(ConfiguredTargetFunction.java:770)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compu
te(ConfiguredTargetFunction.java:320)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate
.run(AbstractParallelEvaluator.java:420)
        ... 4 more
FAILED: Build did NOT complete successfully (2 packages loaded)

Server terminated abruptly (error code: 14, error message: '', log file: 'c:\use
rs\me\_bazel_me\cxy76ymx/server/jvm.out')

c:\tensorflow-master>

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by pauldelmusica** [comment]
Have I written custom code:  No
OS Platform and Distribution: Windows 7, 64 bit
TensorFlow installed from: windows build
TensorFlow version: 1.5, newer versions would not import
Bazel version: 0.17.2
CUDA/cuDNN version: NA
GPU model and memory: NA
Exact command to reproduce: bazel build tensorflow/examples/wav_to_spectrogram/...
Mobile device: NA

**Comment by mrsabhar** [comment]
I'm also seeing similar issue with below command line . I did try different TF version (1.9, 1.10, 1.11) but all gives similar error
bazel test -c opt -- //tensorflow/... -//tensorflow/compiler/... -//tensorflow/contrib/lite/...

**Comment by tensorflowbutler** [comment]
Nagging Assignee @ymodak: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by pauldelmusica** [comment]
Here maybe a related problem. What is //tensorflow/cc:ops/math_ops_gen_cc? I can see a folder /tensorflow/cc/ops but what is cc:ops?

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\tensorflow-master>bazel run tensorflow/examples/wav_to_spectrogram:wav_to_spe
ctrogram -- ^
More? --input_wav=/tmp/speech_dataset/happy/ab00c4b2_nohash_0.wav ^
More? --output_image=/tmp/spectrogram.png
Starting local Bazel server and connecting to it...
Loading:
Loading: 0 packages loaded
Loading: 0 packages loaded
    currently loading: tensorflow/examples/wav_to_spectrogram
Analyzing: target //tensorflow/examples/wav_to_spectrogram:wav_to_spectrogram (3
 packages loaded)
Analyzing: target //tensorflow/examples/wav_to_spectrogram:wav_to_spectrogram (8
 packages loaded)
Analyzing: target //tensorflow/examples/wav_to_spectrogram:wav_to_spectrogram (1
0 packages loaded)
Analyzing: target //tensorflow/examples/wav_to_spectrogram:wav_to_spectrogram (1
1 packages loaded)
Analyzing: target //tensorflow/examples/wav_to_spectrogram:wav_to_spectrogram (1
9 packages loaded)
Analyzing: target //tensorflow/examples/wav_to_spectrogram:wav_to_spectrogram (3
0 packages loaded)
Analyzing: target //tensorflow/examples/wav_to_spectrogram:wav_to_spectrogram (4
3 packages loaded)
Analyzing: target //tensorflow/examples/wav_to_spectrogram:wav_to_spectrogram (5
0 packages loaded)
Analyzing: target //tensorflow/examples/wav_to_spectrogram:wav_to_spectrogram (5
2 packages loaded)
WARNING: C:/tensorflow-master/tensorflow/core/BUILD:2501:1: in includes attribut
e of cc_library rule //tensorflow/core:framework_internal_headers_lib: '../../ex
ternal/com_google_absl' resolves to 'external/com_google_absl' not below the rel
ative path of its package 'tensorflow/core'. This will be an error in the future
. Since this rule was created by the macro 'cc_header_only_library', the error m
ight have been caused by the macro implementation in C:/tensorflow-master/tensor
flow/tensorflow.bzl:1376:20
WARNING: C:/tensorflow-master/tensorflow/core/BUILD:2587:1: in includes attribut
e of cc_library rule //tensorflow/core:framework_headers_lib: '../../external/co
m_google_absl' resolves to 'external/com_google_absl' not below the relative pat
h of its package 'tensorflow/core'. This will be an error in the future. Since t
his rule was created by the macro 'cc_header_only_library', the error might have
 been caused by the macro implementation in C:/tensorflow-master/tensorflow/tens
orflow.bzl:1376:20
Analyzing: target //tensorflow/examples/wav_to_spectrogram:wav_to_spectrogram (6
9 packages loaded)
Unhandled exception thrown during build; message: Unrecoverable error while eval
uating node '//tensorflow/cc:ops/math_ops_gen_cc BuildConfigurationValue.Key[ac9
8f5975123fd6eeb07a7415b6161fb] true' (requested by nodes '//tensorflow/cc:math_o
ps_genrule BuildConfigurationValue.Key[6a75becf8194103d260d4e5a345be2c2] false')

INFO: Elapsed time: 24.494s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (72 packages loaded)
java.lang.RuntimeException: Unrecoverable error while evaluating node '//tensorf
low/cc:ops/math_ops_gen_cc BuildConfigurationValue.Key[ac98f5975123fd6eeb07a7415
b6161fb] true' (requested by nodes '//tensorflow/cc:math_ops_genrule BuildConfig
urationValue.Key[6a75becf8194103d260d4e5a345be2c2] false')
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate
.run(AbstractParallelEvaluator.java:497)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$Wrapped
Runnable.run(AbstractQueueVisitor.java:368)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown S
ource)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown
Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException
        at com.google.common.base.Preconditions.checkState(Preconditions.java:49
1)
        at com.google.devtools.build.lib.rules.cpp.LibrariesToLinkCollector.addD
ynamicInputLinkOptions(LibrariesToLinkCollector.java:290)
        at com.google.devtools.build.lib.rules.cpp.LibrariesToLinkCollector.addL
inkerInputs(LibrariesToLinkCollector.java:258)
        at com.google.devtools.build.lib.rules.cpp.LibrariesToLinkCollector.coll
ectLibrariesToLink(LibrariesToLinkCollector.java:203)
        at com.google.devtools.build.lib.rules.cpp.CppLinkActionBuilder.build(Cp
pLinkActionBuilder.java:916)
        at com.google.devtools.build.lib.rules.cpp.CcBinary.init(CcBinary.java:4
13)
        at com.google.devtools.build.lib.rules.cpp.CcBinary.create(CcBinary.java
:179)
        at com.google.devtools.build.lib.rules.cpp.CcBinary.create(CcBinary.java
:71)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.create
Rule(ConfiguredTargetFactory.java:320)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.create
ConfiguredTarget(ConfiguredTargetFactory.java:205)
        at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfig
uredTarget(SkyframeBuildView.java:631)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.creat
eConfiguredTarget(ConfiguredTargetFunction.java:770)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compu
te(ConfiguredTargetFunction.java:320)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate
.run(AbstractParallelEvaluator.java:420)
        ... 4 more
java.lang.RuntimeException: Unrecoverable error while evaluating node '//tensorf
low/cc:ops/math_ops_gen_cc BuildConfigurationValue.Key[ac98f5975123fd6eeb07a7415
b6161fb] true' (requested by nodes '//tensorflow/cc:math_ops_genrule BuildConfig
urationValue.Key[6a75becf8194103d260d4e5a345be2c2] false')
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate
.run(AbstractParallelEvaluator.java:497)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$Wrapped
Runnable.run(AbstractQueueVisitor.java:368)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown S
ource)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown
Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException
        at com.google.common.base.Preconditions.checkState(Preconditions.java:49
1)
        at com.google.devtools.build.lib.rules.cpp.LibrariesToLinkCollector.addD
ynamicInputLinkOptions(LibrariesToLinkCollector.java:290)
        at com.google.devtools.build.lib.rules.cpp.LibrariesToLinkCollector.addL
inkerInputs(LibrariesToLinkCollector.java:258)
        at com.google.devtools.build.lib.rules.cpp.LibrariesToLinkCollector.coll
ectLibrariesToLink(LibrariesToLinkCollector.java:203)
        at com.google.devtools.build.lib.rules.cpp.CppLinkActionBuilder.build(Cp
pLinkActionBuilder.java:916)
        at com.google.devtools.build.lib.rules.cpp.CcBinary.init(CcBinary.java:4
13)
        at com.google.devtools.build.lib.rules.cpp.CcBinary.create(CcBinary.java
:179)
        at com.google.devtools.build.lib.rules.cpp.CcBinary.create(CcBinary.java
:71)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.create
Rule(ConfiguredTargetFactory.java:320)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.create
ConfiguredTarget(ConfiguredTargetFactory.java:205)
        at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfig
uredTarget(SkyframeBuildView.java:631)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.creat
eConfiguredTarget(ConfiguredTargetFunction.java:770)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compu
te(ConfiguredTargetFunction.java:320)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate
.run(AbstractParallelEvaluator.java:420)
        ... 4 more
FAILED: Build did NOT complete successfully (72 packages loaded)

C:\tensorflow-master>

**Comment by rafalfirlejczyk** [comment]
I have the same problem on Windows7/64 when running:
bazel build tensorflow/contrib/lite/toco:tocoFAILED: Build did NOT complete successfully (443 packages loaded)

Server terminated abruptly (error code: 14, error message: '', log file: 'c:\users\brm738\_bazel_brm738\cxmuuzyy/server/jvm.out').

Python 3.6.2
VS 2017
TF1.11.0

**Comment by tensorflowbutler** [comment]
Nagging Assignee @gunan: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @gunan: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by mohantym** [comment]
Hi @pauldelmusica ! The above example on wave_to_spectrogram has depreciated now.  Can we close this issue now? Attaching [audio recognition ](https://www.tensorflow.org/tutorials/audio/simple_audio)documentation from the 2.8 version for reference. Thanks!
