### ISSUE TITLE
Unable to use TFOptimizer from keras in tensorflow

### ISSUE THREAD

**Issue by adityakumarakash** [tensorflow/tensorflow#22466]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: NA
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: NA
- **TensorFlow installed from (source or binary)**: Running in colab, chrome
- **TensorFlow version (use command below)**: 1.10.1
- **Python version**: 2
- **Bazel version (if compiling from source)**: NA
- **GCC/Compiler version (if compiling from source)**: NA
- **CUDA/cuDNN version**: NA
- **GPU model and memory**: NA
- **Exact command to reproduce**: NA

### Describe the problem
Using TFOptimizer from keras inside tensorflow gives error - 
```
---> 22 opt = keras.optimizers.TFOptimizer(tf_opt)
     23 opt.lr = lr
     24 

AttributeError: 'module' object has no attribute 'TFOptimizer'
```

I manually imported it to make the code work-
```
from tensorflow.python.keras.optimizers import TFOptimizer
```

Could TFOptimizer class be exported from tensorflow in the following file-
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/optimizers.py#L691

**Comment by yongtang** [comment]
Added the PR #22467 for the fix.

**Comment by wt-huang** [comment]
@yongtang Thanks for the PR. Looks like this issue will be fixed separately with API changes at the level of TF optimizers which is in progress.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @wt-huang: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by wt-huang** [comment]
Closing as this will be fixed in API changes.

**Comment by nrgopalrao** [comment]
Hi, I am facing this error now, could anyone please help me out on how to solve it? Thanks.

`Epoch 00001: loss improved from inf to 2.88872, saving model to weights\weights-improvement-01-2.8887.hdf5
Traceback (most recent call last):

  File "<ipython-input-22-50033a1e00fb>", line 16, in <module>
    history = model.fit(X, y, epochs=10, batch_size=128, callbacks=callbacks_list)

  File "C:\Users\nrgra\anaconda3\lib\site-packages\keras\engine\training.py", line 1239, in fit
    validation_freq=validation_freq)

  File "C:\Users\nrgra\anaconda3\lib\site-packages\keras\engine\training_arrays.py", line 216, in fit_loop
    callbacks.on_epoch_end(epoch, epoch_logs)

  File "C:\Users\nrgra\anaconda3\lib\site-packages\keras\callbacks\callbacks.py", line 152, in on_epoch_end
    callback.on_epoch_end(epoch, logs)

  File "C:\Users\nrgra\anaconda3\lib\site-packages\keras\callbacks\callbacks.py", line 719, in on_epoch_end
    self.model.save(filepath, overwrite=True)

  File "C:\Users\nrgra\anaconda3\lib\site-packages\keras\engine\network.py", line 1152, in save
    save_model(self, filepath, overwrite, include_optimizer)

  File "C:\Users\nrgra\anaconda3\lib\site-packages\keras\engine\saving.py", line 449, in save_wrapper
    save_function(obj, filepath, overwrite, *args, **kwargs)

  File "C:\Users\nrgra\anaconda3\lib\site-packages\keras\engine\saving.py", line 541, in save_model
    _serialize_model(model, h5dict, include_optimizer)

  File "C:\Users\nrgra\anaconda3\lib\site-packages\keras\engine\saving.py", line 163, in _serialize_model
    if isinstance(model.optimizer, optimizers.TFOptimizer):

AttributeError: module 'tensorflow.keras.optimizers' has no attribute 'TFOptimizer'`

**Comment by Mahmood-Hoseini** [comment]
I am getting the same error too with tf 2.2.0 and kears 2.4.3.
Any help?

**Comment by SarahEnac** [comment]
@nrgopalrao @Mahmood-Hoseini  Hi ! I have the same problem than you. Did you find a solution please ?

**Comment by Mahmood-Hoseini** [comment]
@nrgopalrao I did not. It seems like a incompatibility of tf and keras versions. I moved to pytorch.

**Comment by zikunliu6** [comment]
Try to replace all the keras to tensorflow.keras
