### ISSUE TITLE
ArchLinux [Optimus-Bumblebee] - Could not satisfy explicit device specification '/device:GPU:0' because no supported kernel for GPU devices is available

### ISSUE THREAD

**Issue by Dentrax** [tensorflow/tensorflow#22476]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: ArchLinux x64
- **TensorFlow installed from (source or binary)**: via pip
- **TensorFlow version (use command below)**: 1.10.0
- **Python version**: 3.6.5
- **CUDA/cuDNN version**: CUDA 9.2.148 - cuDNN 7.2.1
- **GPU model and memory**: NVIDIA GTX 970M 3GB

- I'm using Nvidia Optimus with Bumblebee: https://wiki.archlinux.org/index.php/bumblebee

- **Exact command to reproduce**:

1. git clone https://github.com/isseu/emotion-recognition-neural-networks
# Make reqiured configurations...

2. I removed tensorflow and added tensorflow-gpu 1.10.0

3. sudo optirun python3 emotion_recognition.py train

### Describe the problem

To run Train the data on my GPU, I just edited a few lines on emotion_recognation.py:

`import tensorflow as tf`

Added under `def __init__(self):`
`tf.ConfigProto(allow_soft_placement=True)`

Added under `def start_training(self):`
```
        with tf.device('/gpu:0'):
            self.model.fit(bla bla bla)
```

### Source code / logs

```
hdf5 is not supported on this machine (please install/reinstall h5py for optimal experience)
[+] Dataset found and loaded
[+] Building CNN
WARNING:tensorflow:From /home/dentrax/Projects/GitHub/emotion-recognition-neural-networks/lib/python3.6/site-packages/tflearn/initializations.py:119: UniformUnitScaling.__init__ (from tensorflow.python.ops.init_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.initializers.variance_scaling instead with distribution=uniform to get equivalent behavior.
WARNING:tensorflow:From /home/dentrax/Projects/GitHub/emotion-recognition-neural-networks/lib/python3.6/site-packages/tflearn/objectives.py:66: calling reduce_sum (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
2018-09-23 21:31:13.883618: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-09-23 21:31:14.001876: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:897] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-09-23 21:31:14.002292: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1405] Found device 0 with properties: 
name: GeForce GTX 970M major: 5 minor: 2 memoryClockRate(GHz): 1.038
pciBusID: 0000:01:00.0
totalMemory: 2.95GiB freeMemory: 2.89GiB
2018-09-23 21:31:14.002318: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1484] Adding visible gpu devices: 0
2018-09-23 21:31:14.260311: I tensorflow/core/common_runtime/gpu/gpu_device.cc:965] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-09-23 21:31:14.260358: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971]      0 
2018-09-23 21:31:14.260364: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] 0:   N 
2018-09-23 21:31:14.260525: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1097] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 2595 MB memory) -> physical GPU (device: 0, name: GeForce GTX 970M, pci bus id: 0000:01:00.0, compute capability: 5.2)
2018-09-23 21:31:14.554680: W tensorflow/core/framework/allocator.cc:108] Allocation of 226492416 exceeds 10% of system memory.
2018-09-23 21:31:14.644729: W tensorflow/core/framework/allocator.cc:108] Allocation of 226492416 exceeds 10% of system memory.
2018-09-23 21:31:14.733250: W tensorflow/core/framework/allocator.cc:108] Allocation of 226492416 exceeds 10% of system memory.
2018-09-23 21:31:14.822594: W tensorflow/core/framework/allocator.cc:108] Allocation of 226492416 exceeds 10% of system memory.
2018-09-23 21:31:14.911661: W tensorflow/core/framework/allocator.cc:108] Allocation of 226492416 exceeds 10% of system memory.
2018-09-23 21:31:15.880266: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1484] Adding visible gpu devices: 0
2018-09-23 21:31:15.880304: I tensorflow/core/common_runtime/gpu/gpu_device.cc:965] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-09-23 21:31:15.880313: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971]      0 
2018-09-23 21:31:15.880321: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] 0:   N 
2018-09-23 21:31:15.880412: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1097] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 2595 MB memory) -> physical GPU (device: 0, name: GeForce GTX 970M, pci bus id: 0000:01:00.0, compute capability: 5.2)
[+] Training network
---------------------------------
Run id: emotion_recognition
Log directory: /tmp/tflearn_logs/
---------------------------------
Training samples: 11214
Validation samples: 2804
--
Traceback (most recent call last):
  File "/home/dentrax/Projects/GitHub/emotion-recognition-neural-networks/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1278, in _do_call
    return fn(*args)
  File "/home/dentrax/Projects/GitHub/emotion-recognition-neural-networks/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1261, in _run_fn
    self._extend_graph()
  File "/home/dentrax/Projects/GitHub/emotion-recognition-neural-networks/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1295, in _extend_graph
    tf_session.ExtendSession(self._session)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device for operation 'Accuracy/__raw_': Could not satisfy explicit device specification '/device:GPU:0' because no supported kernel for GPU devices is available.
Registered kernels:
  device='CPU'; T in [DT_DOUBLE]
  device='CPU'; T in [DT_FLOAT]
  device='CPU'; T in [DT_BFLOAT16]
  device='CPU'; T in [DT_HALF]
  device='CPU'; T in [DT_INT8]
  device='CPU'; T in [DT_UINT8]
  device='CPU'; T in [DT_INT16]
  device='CPU'; T in [DT_UINT16]
  device='CPU'; T in [DT_INT32]
  device='CPU'; T in [DT_INT64]

	 [[Node: Accuracy/__raw_ = ScalarSummary[T=DT_FLOAT, _device="/device:GPU:0"](Accuracy/__raw_/tags, Accuracy/Mean)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "emotion_recognition.py", line 110, in <module>
    network.start_training()
  File "emotion_recognition.py", line 78, in start_training
    run_id='emotion_recognition'
  File "/home/dentrax/Projects/GitHub/emotion-recognition-neural-networks/lib/python3.6/site-packages/tflearn/models/dnn.py", line 216, in fit
    callbacks=callbacks)
  File "/home/dentrax/Projects/GitHub/emotion-recognition-neural-networks/lib/python3.6/site-packages/tflearn/helpers/trainer.py", line 339, in fit
    show_metric)
  File "/home/dentrax/Projects/GitHub/emotion-recognition-neural-networks/lib/python3.6/site-packages/tflearn/helpers/trainer.py", line 816, in _train
    tflearn.is_training(True, session=self.session)
  File "/home/dentrax/Projects/GitHub/emotion-recognition-neural-networks/lib/python3.6/site-packages/tflearn/config.py", line 95, in is_training
    tf.get_collection('is_training_ops')[0].eval(session=session)
  File "/home/dentrax/Projects/GitHub/emotion-recognition-neural-networks/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 680, in eval
    return _eval_using_default_session(self, feed_dict, self.graph, session)
  File "/home/dentrax/Projects/GitHub/emotion-recognition-neural-networks/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 4951, in _eval_using_default_session
    return session.run(tensors, feed_dict)
  File "/home/dentrax/Projects/GitHub/emotion-recognition-neural-networks/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 877, in run
    run_metadata_ptr)
  File "/home/dentrax/Projects/GitHub/emotion-recognition-neural-networks/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1100, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/dentrax/Projects/GitHub/emotion-recognition-neural-networks/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1272, in _do_run
    run_metadata)
  File "/home/dentrax/Projects/GitHub/emotion-recognition-neural-networks/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1291, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device for operation 'Accuracy/__raw_': Could not satisfy explicit device specification '/device:GPU:0' because no supported kernel for GPU devices is available.
Registered kernels:
  device='CPU'; T in [DT_DOUBLE]
  device='CPU'; T in [DT_FLOAT]
  device='CPU'; T in [DT_BFLOAT16]
  device='CPU'; T in [DT_HALF]
  device='CPU'; T in [DT_INT8]
  device='CPU'; T in [DT_UINT8]
  device='CPU'; T in [DT_INT16]
  device='CPU'; T in [DT_UINT16]
  device='CPU'; T in [DT_INT32]
  device='CPU'; T in [DT_INT64]

	 [[Node: Accuracy/__raw_ = ScalarSummary[T=DT_FLOAT, _device="/device:GPU:0"](Accuracy/__raw_/tags, Accuracy/Mean)]]

Caused by op 'Accuracy/__raw_', defined at:
  File "emotion_recognition.py", line 110, in <module>
    network.start_training()
  File "emotion_recognition.py", line 78, in start_training
    run_id='emotion_recognition'
  File "/home/dentrax/Projects/GitHub/emotion-recognition-neural-networks/lib/python3.6/site-packages/tflearn/models/dnn.py", line 216, in fit
    callbacks=callbacks)
  File "/home/dentrax/Projects/GitHub/emotion-recognition-neural-networks/lib/python3.6/site-packages/tflearn/helpers/trainer.py", line 288, in fit
    self.summ_writer, self.coord)
  File "/home/dentrax/Projects/GitHub/emotion-recognition-neural-networks/lib/python3.6/site-packages/tflearn/helpers/trainer.py", line 794, in initialize_fit
    val_feed_dict)
  File "/home/dentrax/Projects/GitHub/emotion-recognition-neural-networks/lib/python3.6/site-packages/tflearn/helpers/trainer.py", line 937, in create_testing_summaries
    summarize(self.metric, "scalar", sname, tr_summ_collection)
  File "/home/dentrax/Projects/GitHub/emotion-recognition-neural-networks/lib/python3.6/site-packages/tflearn/helpers/summarizer.py", line 98, in summarize
    summaries.get_summary(type, name, value, summary_collection)
  File "/home/dentrax/Projects/GitHub/emotion-recognition-neural-networks/lib/python3.6/site-packages/tflearn/summaries.py", line 46, in get_summary
    summ = tf.summary.scalar(tag, value)
  File "/home/dentrax/Projects/GitHub/emotion-recognition-neural-networks/lib/python3.6/site-packages/tensorflow/python/summary/summary.py", line 90, in scalar
    val = _gen_logging_ops.scalar_summary(tags=tag, values=tensor, name=scope)
  File "/home/dentrax/Projects/GitHub/emotion-recognition-neural-networks/lib/python3.6/site-packages/tensorflow/python/ops/gen_logging_ops.py", line 623, in scalar_summary
    "ScalarSummary", tags=tags, values=values, name=name)
  File "/home/dentrax/Projects/GitHub/emotion-recognition-neural-networks/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/dentrax/Projects/GitHub/emotion-recognition-neural-networks/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "/home/dentrax/Projects/GitHub/emotion-recognition-neural-networks/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3155, in create_op
    op_def=op_def)
  File "/home/dentrax/Projects/GitHub/emotion-recognition-neural-networks/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1717, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Cannot assign a device for operation 'Accuracy/__raw_': Could not satisfy explicit device specification '/device:GPU:0' because no supported kernel for GPU devices is available.
Registered kernels:
  device='CPU'; T in [DT_DOUBLE]
  device='CPU'; T in [DT_FLOAT]
  device='CPU'; T in [DT_BFLOAT16]
  device='CPU'; T in [DT_HALF]
  device='CPU'; T in [DT_INT8]
  device='CPU'; T in [DT_UINT8]
  device='CPU'; T in [DT_INT16]
  device='CPU'; T in [DT_UINT16]
  device='CPU'; T in [DT_INT32]
  device='CPU'; T in [DT_INT64]

	 [[Node: Accuracy/__raw_ = ScalarSummary[T=DT_FLOAT, _device="/device:GPU:0"](Accuracy/__raw_/tags, Accuracy/Mean)]]
```

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
Bazel version
Mobile device
