### ISSUE TITLE
 java.lang.IllegalArgumentException: Input to reshape is a tensor with 3072 values, but the requested shape has 9437184

### ISSUE THREAD

**Issue by maitreya2954** [tensorflow/tensorflow#22482]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: NA
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 1.8
- **Python version**:3.6
- **Bazel version (if compiling from source)**:0.16.1
- **GCC/Compiler version (if compiling from source)**:NA 
- **CUDA/cuDNN version**:NA
- **GPU model and memory**:NA
- **Exact command to reproduce**:NA

### Describe the problem
I have built a custom classifier model using keras with tensorflow backend and I am trying to inference the model to use it in model. I have successfully created protobuf file which contains inference model. When I am trying to feed the input to the model in android. I am getting this error
```
java.lang.IllegalArgumentException: Input to reshape is a tensor with 3072 values, but the requested shape has 9437184
    	 [[{{node reshape_1/Reshape}} = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_reshape_1_input_0_0, reshape_1/Reshape/shape)]]
```

### Source code / logs
```
09-24 18:24:52.780 2480-3594/com.appa.iocsv2 E/TensorFlowInferenceInterface: Failed to run TensorFlow inference with inputs:[reshape_1_input], outputs:[dense_2/Softmax]
    
    --------- beginning of crash
09-24 18:24:52.780 2480-3594/com.appa.iocsv2 E/AndroidRuntime: FATAL EXCEPTION: IntentService[Prediction Service]
    Process: com.appa.iocsv2, PID: 2480
    java.lang.IllegalArgumentException: Input to reshape is a tensor with 3072 values, but the requested shape has 9437184
    	 [[{{node reshape_1/Reshape/eightbit}} = QuantizedReshape[T=DT_QUINT8, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](reshape_1/Reshape_eightbit/reshape_1_input/quantize, reshape_1/Reshape/shape, reshape_1/Reshape_eightbit/reshape_1_input/quantize:1, reshape_1/Reshape_eightbit/reshape_1_input/quantize:2)]]
        at org.tensorflow.Session.run(Native Method)
        at org.tensorflow.Session.access$100(Session.java:48)
        at org.tensorflow.Session$Runner.runHelper(Session.java:314)
        at org.tensorflow.Session$Runner.run(Session.java:264)
        at org.tensorflow.contrib.android.TensorFlowInferenceInterface.run(TensorFlowInferenceInterface.java:228)
        at org.tensorflow.contrib.android.TensorFlowInferenceInterface.run(TensorFlowInferenceInterface.java:197)
        at org.tensorflow.contrib.android.TensorFlowInferenceInterface.run(TensorFlowInferenceInterface.java:187)
        at com.appa.iocsv2.analyze.PredictionService.predict(PredictionService.java:151)
        at com.appa.iocsv2.analyze.PredictionService.onHandleIntent(PredictionService.java:103)
        at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:68)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by harshini-gadige** [comment]
@maitreya2954 Hi, could you please share a code snippet to reproduce this error.

**Comment by maitreya2954** [comment]
Hey @harshini-gadige 
Here is the code for which i am facing the issue
## Keras model
```
model = Sequential()
model.add(Reshape((image_dim, image_dim, 3), input_shape=(image_dim * image_dim * 3,)))
model.add(Conv2D(32, (5, 5), padding='same', kernel_regularizer=l2(reg_strength)))
model.add(LeakyReLU(alpha=alpha_LReLU))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(dropout_rate))
model.add(Flatten())
model.add(Dense(512, kernel_constraint=maxnorm(1), kernel_regularizer=l2(reg_strength)))
model.add(LeakyReLU(alpha=alpha_LReLU))
model.add(Dropout(dropout_rate))
model.add(Dense(64, kernel_constraint=maxnorm(1), kernel_regularizer=l2(reg_strength)))
model.add(LeakyReLU(alpha=alpha_LReLU))
model.add(Dropout(dropout_rate))
model.add(Dense(num_of_classes, activation='softmax', kernel_regularizer=l2(reg_strength)))
```
## Inferencing into protobuf file
```
from tensorflow.python.framework import graph_util
from tensorflow.python.framework import graph_io
if args.quantize:
    from tensorflow.tools.graph_transforms import TransformGraph
    transforms = ["quantize_weights", "quantize_nodes"]
    transformed_graph_def = TransformGraph(sess.graph.as_graph_def(), [], pred_node_names, transforms)
    constant_graph = graph_util.convert_variables_to_constants(sess, transformed_graph_def, pred_node_names)
else:
    constant_graph = graph_util.convert_variables_to_constants(sess, sess.graph.as_graph_def(), pred_node_names)    
graph_io.write_graph(constant_graph, output_fld, args.output_model_file, as_text=False)
```
## Android
```
inferenceInterface = new TensorFlowInferenceInterface(getAssets(), "CNNMODEL.pb");                Log.d("GETREP", "Tensorflow model loaded...Input size: " + String.valueOf(input.length));
//dimensions of input is (1, 3072)
float[] output = predict(input);

private float[] predict(float[] input){
        // model has only 2 output neuron
        float output[] = new float[2];
        inferenceInterface.feed("conv2d_1_input", input, 1, input.length);
        Log.d("GETREP", "Feed completed");
        inferenceInterface.run(new String[]{"dense_2/Softmax"});
        Log.d("GETREP", "Run completed");
        inferenceInterface.fetch("dense_2/Softmax", output);
        // return prediction
        return output;
    }
```

**Comment by wt-huang** [comment]
@maitreya2954 You may want to check whether the input is 1D when feeding the graph. Consider reshaping the input to match TFLite model requirements.

**Comment by maitreya2954** [comment]
@wt-huang  Currently I am initializing input as 
> float[] input = new float[3072];
So input is 1D

**Comment by wt-huang** [comment]
@maitreya2954 In your code snippet it appears that your image size is `32x32`, note that `input.length` should equal input size. If you are using `(1,3072)` as your input, then system is expecting image size of `3072x3072`, which I doubt that is what you want.

**Comment by maitreya2954** [comment]
@wt-huang The system is throwing an error ```The array of length xxxx cannot be wrapped into tensor of length 3072``` if size of the array is anything else but 3072.

I have grep'ed the error result and found out it was in [https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/reshape_op.h](url) line 78

```
OP_REQUIRES(context, shape.num_elements() == input.NumElements(),
                errors::InvalidArgument("Input to reshape is a tensor with ",
                                        input.NumElements(),
                                        " values, but the requested shape has ",
                                        shape.num_elements()));
```

**Comment by wt-huang** [comment]
@maitreya2954 Please post your full code also attach .pb file.

**Comment by wt-huang** [comment]
Closing this for now, feel free to reopen if any errors come up.
