### ISSUE TITLE
OSError: SavedModel file does not exist at: saved_model_dir/{saved_model.pbtxt|saved_model.pb}

### ISSUE THREAD

**Issue by Akhtar303nu** [tensorflow/tensorflow#22480]
I want to optimized the my Tensor flow model (mars-small128.pb) 
I have saved_model_dir directory which contain mars-small128.pb file 
Here is my code 
import tensorflow as tf
converter = tf.contrib.lite.TocoConverter.from_saved_model(saved_model_dir)
converter.post_training_quantize = True
tflite_quantized_model = converter.convert()
open("quantized_model.tflite", "wb").write(tflite_quantized_model)
Error
OSError: SavedModel file does not exist at: saved_model_dir/{saved_model.pbtxt|saved_model.pb}
System information
Os:linux 16
Python:3.5
tensorflow Installation:pip install -U tf-nightly (latest versiopn)
using Cpu

Thanks

**Comment by devanandd8245** [comment]
@Akhtar303nu Can you guide me with the step by step procedures to be followed for the training to obtain the model file (.pb) in the format

**Comment by Akhtar303nu** [comment]
> @Akhtar303nu Can you guide me with the step by step procedures to be followed for the training to obtain the model file (.pb) in the format
Thanks @devanandd8245 I take  pretrained model of Google (https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_modo.md)
it genrate same error in my case
code:
import tensorflow as tf
converter = tf.contrib.lite.TocoConverter.from_saved_model('ssd_mobilenet_v1_coco_2018_01_28')
converter.post_training_quantize = True
tflite_quantized_model = converter.convert()
open("quantized_model.tflite", "wb").write(tflite_quantized_model)

Error:

018-09-24 18:56:08.695359: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Traceback (most recent call last):
  File "t.py", line 2, in <module>
    converter = tf.contrib.lite.TocoConverter.from_saved_model('ssd_mobilenet_v1_coco_2018_01_28')
  File "/home/akhtar/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/lite/python/lite.py", line 339, in from_saved_model
    output_arrays, tag_set, signature_key)
  File "/home/akhtar/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/lite/python/convert_saved_model.py", line 239, in freeze_saved_model
    meta_graph = _get_meta_graph_def(saved_model_dir, tag_set)
  File "/home/akhtar/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/lite/python/convert_saved_model.py", line 61, in _get_meta_graph_def
    return loader.load(sess, tag_set, saved_model_dir)
  File "/home/akhtar/anaconda3/lib/python3.6/site-packages/tensorflow/python/saved_model/loader_impl.py", line 192, in load
    loader = SavedModelLoader(export_dir)
  File "/home/akhtar/anaconda3/lib/python3.6/site-packages/tensorflow/python/saved_model/loader_impl.py", line 208, in __init__
    self._saved_model = _parse_saved_model(export_dir)
  File "/home/akhtar/anaconda3/lib/python3.6/site-packages/tensorflow/python/saved_model/loader_impl.py", line 81, in _parse_saved_model
    constants.SAVED_MODEL_FILENAME_PB))
OSError: SavedModel file does not exist at: ssd_mobilenet_v1_coco_2018_01_28/{saved_model.pbtxt|saved_model.pb}

**Comment by harshini-gadige** [comment]
@sukritiramesh  -  Hi, could you please look into this issue.

**Comment by karmel** [comment]
It sounds like the path to your saved model file is not correct. My guess is you want the full path to `ssd_mobilenet_v1_coco_2018_01_28` rather than a relative path. Can you try the same script with the absolute path specified?

**Comment by Akhtar303nu** [comment]
Thanks @karmel  I have tried it with full path but genrate same error

**Comment by yashwantptl7** [comment]
Hi @devanandd8245 , here is the link for step by step guide....hope it may help you
https://medium.com/@jsflo.dev/saving-and-loading-a-tensorflow-model-using-the-savedmodel-api-17645576527

**Comment by devanandd8245** [comment]
i found it is good to understand the basics but the training steps which means i am in requried of the No.Of.folders and the kind of images and annotations to be used.


I am new to tensorflow so i would like to get more depth informations on the training procedures to be followed


________________________________

**Comment by tensorflowbutler** [comment]
Nagging Assignee @karmel: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by karmel** [comment]
This is hard to debug with the information specified. It seems like you are not passing in your saved_model_dir correctly based on the error message. Can you clarify where the saved model is, and how you are passing in the directory name?

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by gdj0nes** [comment]
I'm having the same issue. The follow files we created using a tf.estimator checkpointing on S3.
```                           PRE eval/
2018-11-09 11:49:00        133 checkpoint
2018-11-09 11:49:56   22748845 events.out.tfevents.1541779585.76ea0bf64a92
2018-11-09 10:06:42    4322097 graph.pbtxt
2018-11-09 11:09:04  188348504 model.ckpt-1124.data-00000-of-00001
2018-11-09 11:09:07      16509 model.ckpt-1124.index
2018-11-09 11:09:10    2100949 model.ckpt-1124.meta
2018-11-09 11:42:34  188348504 model.ckpt-1699.data-00000-of-00001
2018-11-09 11:42:37      16509 model.ckpt-1699.index
2018-11-09 11:42:39    2100949 model.ckpt-1699.meta
2018-11-09 11:48:58  188348504 model.ckpt-1814.data-00000-of-00001
2018-11-09 11:49:00      16509 model.ckpt-1814.index
2018-11-09 11:49:02    2100949 model.ckpt-1814.meta
```
Attempting to call 
```python
meta_graph_def = tf.saved_model.loader.load(sess, [tf.saved_model.tag_constants.SERVING], 's3://path_to_checkpoints')
```
raises the following error.
```python
OSError: SavedModel file does not exist at: s3://path_to_checkpoints/{saved_model.pbtxt|saved_model.pb}
```
I am able to view the weights but unable to load with this tool

**Comment by deangelacgn** [comment]
@Akhtar303nu @gdj0nes You are probably passing the path to the .pb file of the **frozen model/graph, which is different from the .pb file of a SavedModel**, and that's why the SavedModel can't be found. Unlike frozen models/graphs, SavedModels are also associated with an auto-generated folder called "variables", so be sure your .pb file was generated in the correct way as it is described in the docs: https://www.tensorflow.org/guide/saved_model.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
It has been 29 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
It has been 44 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
We are closing this issue for now due to lack of activity. Please comment if this is still an issue for you. Thanks!

**Comment by Knize** [comment]
@deangelacgn This looks like my problem or very close. I just don't get it completely. I use uber's framework called ludwig. It use tf under the hood. They say that models generated by ludwig saved by tf's saver.
Directory with model looks like that:
![model](https://user-images.githubusercontent.com/9881948/56100847-6d614d00-5f26-11e9-8a41-fcbf9d966003.png)
So in documentation of this saver written:
![tf structure](https://user-images.githubusercontent.com/9881948/56100870-c204c800-5f26-11e9-851f-267d02334c66.png)
Looks like i have variables and don't have .pb file.
So is there a way to convert model as i have it to tflite model? I'm not sure where is a gap. Is it ludwig, tflite converter or just my understanding?

**Comment by saintthor** [comment]
hello, I got a similar error. I am running tensorflow on colab.research.google.com. I saved a model to "drive/Colab/mo_big7_12345789bcdfghijklm" while the tensorflow version was 1.14. it is just one file.
now, the tensorflow upgraded to 1.15. when loading the file by 
tf.keras.models.load_model( 'drive/Colab/mo_big7_12345789bcdfghijklm' )
it raises: OSError: SavedModel file does not exist at: drive/Colab/mo_big7_12345789bcdfghijklm/{saved_model.pbtxt|saved_model.pb}
I havn't seen the .pb or .pbtxt files before. how to fix it?

**Comment by Aaronreb** [comment]
> [odel](https://www.tensorflow.org/guide/saved_model).
> 
> I was also struggl

So is there a method to converts such frozen pb files to savedModel format??

**Comment by ThomasKlein18** [comment]
If you run into this when trying to load a model stored in a .h5-file, e.g. one created using model.save for a tf.keras.Sequential model, the problem might simply be that h5py is not installed. To solve that problem, run `pip3 install h5py`.

**Comment by PooyaLaryan** [comment]
you should save your model in the .pb file
at first load you model if you saved it before.
and then run YOUR_MODEL.save('NAME.pb') .
now you have a folder that contain saved model.pb and necessary other file.
create converter instance with 
convertor = tensorflow.lite.TFLiteConverter.from_saved_model('P1.pb')
at end convert your model and save it 

tfmodel = converter.convert()
open("model.tflite","wb").write(tfmodel)

**Comment by prpeixoto** [comment]
> If you run into this when trying to load a model stored in a .h5-file, e.g. one created using model.save for a tf.keras.Sequential model, the problem might simply be that h5py is not installed. To solve that problem, run `pip3 install h5py`.

@ThomasKlein18 Hy Thomas, that appeared to be my error, however, now as I try to run the program I get the following error:
AttributeError("type object 'h5py.h5.H5PYConfig' has no attribute '__reduce_cython__'")
Any ideas on what it could be? Thank you

**Comment by JoseLGP** [comment]
Hello !!

I had a similar problem with a saved model that was present in the folders but I could not load because of the same error.
The solution was to write the absolute path to the model, instead of the generic path that I had on the code.

I hope that this can help to anyone with the same issue.
Regards.

**Comment by dikshantjn** [comment]
Im getting the same error while trying to load the saved_model.pb file while using
 converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir)
It shows the file when i run "%ls {saved_model_dir}"
but when i run it on converter it gives error : "SavedModel file does not exist at: saved_model/{saved_model.pbtxt|saved_model.pb}"

**Comment by loretoparisi** [comment]
I'm having the same issue when using ther converter

```
ip-192-168-178-22:toxicity_model loretoparisi$ tensorflowjs_converter --input_format=tf_hub --output_format=tfjs_graph_model ./model.json ./saved
Loading the module using TF 2.X interface from ./model.json.
Traceback (most recent call last):
  File "/usr/local/bin/tensorflowjs_converter", line 8, in <module>
    sys.exit(pip_main())
  File "/usr/local/lib/python3.7/site-packages/tensorflowjs/converters/converter.py", line 757, in pip_main
    main([' '.join(sys.argv[1:])])
  File "/usr/local/lib/python3.7/site-packages/tensorflowjs/converters/converter.py", line 761, in main
    convert(argv[0].split(' '))
  File "/usr/local/lib/python3.7/site-packages/tensorflowjs/converters/converter.py", line 711, in convert
    experiments=args.experiments)
  File "/usr/local/lib/python3.7/site-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 725, in convert_tf_hub_module
    experiments=experiments)
  File "/usr/local/lib/python3.7/site-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 481, in convert_tf_saved_model
    model = load(saved_model_dir, saved_model_tags)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/saved_model/load.py", line 603, in load
    return load_internal(export_dir, tags, options)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/saved_model/load.py", line 614, in load_internal
    loader_impl.parse_saved_model_with_debug_info(export_dir))
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/saved_model/loader_impl.py", line 56, in parse_saved_model_with_debug_info
    saved_model = _parse_saved_model(export_dir)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/saved_model/loader_impl.py", line 113, in parse_saved_model
    constants.SAVED_MODEL_FILENAME_PB))
OSError: SavedModel file does not exist at: ./model.json/{saved_model.pbtxt|saved_model.pb}
ip-192-168-178-22:toxicity_model loretoparisi$ 
```

**Comment by dalavayi** [comment]
Hello all, 
I am getting the OSError, when trying to access the saved model

commands used: 

tf.saved_model.save(model,'./content') - to save the model 

files inside content folder:
02/17/2021  01:32 PM    <DIR>          assets
02/17/2021  01:32 PM                         saved_model.pb
02/17/2021  01:32 PM    <DIR>          variables

!python -m tf2onnx.convert --saved-model './content' --opset 10 --output model.onnx
error: OSError: SavedModel file does not exist at: './content'/{saved_model.pbtxt|saved_model.pb}.

I have tried by passing the absolute path, still the error persists, please help me resolve this issue.

Thank you

**Comment by thibaultvt** [comment]
I fixed it by using '/' instead of '\' in my path..

**Comment by Zakria96** [comment]
line 83, in parse_saved_model
    constants.SAVED_MODEL_FILENAME_PB))
OSError: SavedModel file does not exist at: exported_output_graph/saved_model/saved_model.pb/{saved_model.pbtxt|saved_model.pb}

I am using faster_rcnn_inception_v2_coco model and want to convert it into tflite...


import tensorflow as tf

tflite_model_name="TF.lite"
saved_model_dir="exported_output_graph/saved_model/saved_model.pb"
 #Convert the model
converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir) # path to the SavedModel directory
tflite_model = converter.convert()

# Save the model.
with open(tflite_model_name, 'wb') as f:
  f.write(tflite_model)


I don't what I am missing here

**Comment by murithinjeru** [comment]
I am new to tf but i solved the issue by pointing to the folder with my saved model as opposed to pointing to the .pb file.

saved_path = 'models/saved_model1'

NOT

saved_path = 'models/saved_model1/saved_model.pb'

I hope this helps.

**Comment by remi-cel** [comment]
###  

> 

- `@[**helow**``](mmhjhjg)`

**Comment by m416kar98k** [comment]
No, it is just literally not working. All the trys are useless.

**Comment by arminbiglari** [comment]
hello 
Simply just give the directory of the file containing all files to the path.
my first path was : /home/armin/deepSORT/yolov4-deepsort/checkpoints/yolov4-416/saved_model.pb'
which i got error No such directory so i changed it to:
/home/armin/deepSORT/yolov4-deepsort/checkpoints/yolov4-416'
and it solved my problem.

**Comment by pratishthaa** [comment]
```
import tensorflow as tf
import os
 
# Convert the model
mypath ="E:/strokestuff/strokelr"
converter = tf.lite.TFLiteConverter.from_saved_model(mypath) 
tflite_model = converter.convert()
 
# Save the model.
with open('stroke_lr.tflite', 'wb') as f:
  f.write(tflite_model)
  ```

  The error I get:
  OSError: SavedModel file does not exist at: E:/strokestuff/strokelr\{saved_model.pbtxt|saved_model.pb}

Can someone help?

**Comment by Karan-Dhingra** [comment]
Hii, 
I am facing the same error, 
In my case there exists a save_model.pb file but still, it showing me this...

Here's my code:
```
MODEL = tf.keras.models.load_model("..\\training\\my_model")
```

# Result got while debugging:
```
Exception has occurred: OSError
SavedModel file does not exist at: ..\training\my_model\{saved_model.pbtxt|saved_model.pb}
  File "F:\Projects\Deep Learning\Potato Leave\api\main.py", line 9, in <module>
    MODEL = tf.keras.models.load_model("..\\training\\my_model")
```

**Comment by Zakria96** [comment]
Which model are you trying to convert...?

**Comment by Zakria96** [comment]
There are only some model that are tflite supported

**Comment by kvpratama** [comment]
when using conda environment uninstalling h5py installed from pip and reinstall it using conda solve my problem.
```
pip uninstall h5py
conda install h5py
```

**Comment by ijnrghjkdsmigywneig203** [comment]
hello, I have the same issue, i am loading the model by this
detector = hub.load("https://tfhub.dev/tensorflow/centernet/resnet50v1_fpn_512x512/1")

**Comment by dydxdt** [comment]
This problem occurs when I used tf2.2, and I use tf2.3, it disappears

**Comment by Alps-Sun** [comment]
path: 
-- root
    -- tensorflow
        -- model
            --  20180402-114759
                 -- 20180402-114759.pb
            -- tf_to_tflite.py

`
import tensorflow as tf
import os

os.chdir("/root/tensorflow/model")

# saved_model_dir = "/20180402-114759/20180402-114759.pb"
saved_model_dir = '/20180402-114759'

# Convert the model
converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir) # path to the SavedModel directory
tflite_model = converter.convert()

# Save the model.
with open('model.tflite', 'wb') as f:
  f.write(tflite_model)
`
OSError: SavedModel file does not exist at: /20180402-114759/{saved_model.pbtxt|saved_model.pb}

Help me , thx , so many  times to solve this issue
