### ISSUE TITLE
failed to build tensorfolow lite demo via both bazel 

### ISSUE THREAD

**Issue by benshi001** [tensorflow/tensorflow#22490]
I tried to build the tflite demo apk via bazel.

1. git checkout remotes/origin/r1.9
2.  bazel build --cxxopt=--std=c++11 //tensorflow/contrib/lite/java/demo/app/src/main:TfLiteCameraDemo --config=android_arm64 --cpu=arm64-v8a --fat_apk_cpu=arm64-v8a

	INFO: SHA256 (https://github.com/bazelbuild/rules_python/archive/8b5d0683a7d878b28fffe464779c8a53659fc645.tar.gz) = 8b32d2dbb0b0dca02e0410da81499eef8ff051dad167d6931a92579e3b2a1d48	
	ERROR: error loading package '': Encountered error while reading extension file 'requirements.bzl': no such package '@pip_deps//': Traceback (most recent call last):	
		File "/home/local/SPREADTRUM/ben.shi/.cache/bazel/_bazel_spreadtrum.com/1ebbfeac35eb8d759797bb7ba5198a8a/external/io_bazel_rules_python/python/pip.bzl", line 26
			repository_ctx.execute(["python", repository_ctx.path(r...("")])
		File "/home/local/SPREADTRUM/ben.shi/.cache/bazel/_bazel_spreadtrum.com/1ebbfeac35eb8d759797bb7ba5198a8a/external/io_bazel_rules_python/python/pip.bzl", line 29, in repository_ctx.execute
			repository_ctx.path(repository_ctx.attr.requirements)
	Not a regular file: /home/local/SPREADTRUM/ben.shi/Desktop/tensorflow/tensorflow/requirements.txt
	ERROR: error loading package '': Encountered error while reading extension file 'requirements.bzl': no such package '@pip_deps//': Traceback (most recent call last):
		File "/home/local/SPREADTRUM/ben.shi/.cache/bazel/_bazel_spreadtrum.com/1ebbfeac35eb8d759797bb7ba5198a8a/external/io_bazel_rules_python/python/pip.bzl", line 26
			repository_ctx.execute(["python", repository_ctx.path(r...("")])
		File "/home/local/SPREADTRUM/ben.shi/.cache/bazel/_bazel_spreadtrum.com/1ebbfeac35eb8d759797bb7ba5198a8a/external/io_bazel_rules_python/python/pip.bzl", line 29, in repository_ctx.execute
			repository_ctx.path(repository_ctx.attr.requirements)
	Not a regular file: /home/local/SPREADTRUM/ben.shi/Desktop/tensorflow/tensorflow/requirements.txt
	INFO: Elapsed time: 96.822s
	INFO: 0 processes.
	FAILED: Build did NOT complete successfully (0 packages loaded)

I explicitly set NDK and SDK in WORKSPACE as 

	android_sdk_repository(
	    name = "androidsdk",
	    api_level = 26,
	    # Ensure that you have the build_tools_version below installed in the
	    # SDK manager as it updates periodically.
	    build_tools_version = "27.0.3",
	    # Replace with path to Android SDK on your system
	    path = "/home/local/SPREADTRUM/ben.shi/android/sdk"
	)
	android_ndk_repository(
	    name="androidndk",
	    path="/home/local/SPREADTRUM/ben.shi/android/android-ndk-r16b",
	    # This needs to be 14 or higher to compile TensorFlow.
	    # Please specify API level to >= 21 to build for 64-bit
	    # archtectures or the Android NDK will automatically select biggest
	    # API level that it supports without notice.
	    # Note that the NDK version is not the API level.
	    api_level=28
	)

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by benshi001** [comment]
[[Have I written custom code]]
    no. pure checkout of branch 1.9
[[OS Platform and Distribution]]
    ubuntu 16.04 / amd64
[[TensorFlow installed from]]
    git clone https://github.com/tensorflow/tensorflow
[[TensorFlow version]]
    git checkout remotes/origin/r1.9
[[Bazel version]]
   0.15.2
[[CUDA/cuDNN version]]
    not used
[[GPU model and memory]]
    not used
[[Exact command to reproduce]]
    bazel build --cxxopt=--std=c++11 //tensorflow/contrib/lite/java/demo/app/src/main:TfLiteCameraDemo --config=android_arm64 --cpu=arm64-v8a --fat_apk_cpu=arm64-v8a
[[Mobile device]]
    pixel 2 with android 9.0

**Comment by benshi001** [comment]
I also failed to build to Android Studio 3.2, with error message:

	Could not find com.android.tools.build:aapt2:3.2.0-4818971.
	Searched in the following locations:
	    file:/home/local/SPREADTRUM/ben.shi/android/sdk/extras/m2repository/com/android/tools/build/aapt2/3.2.0-4818971/aapt2-3.2.0-4818971.pom
	    file:/home/local/SPREADTRUM/ben.shi/android/sdk/extras/m2repository/com/android/tools/build/aapt2/3.2.0-4818971/aapt2-3.2.0-4818971-linux.jar
	    file:/home/local/SPREADTRUM/ben.shi/android/sdk/extras/google/m2repository/com/android/tools/build/aapt2/3.2.0-4818971/aapt2-3.2.0-4818971.pom
	    file:/home/local/SPREADTRUM/ben.shi/android/sdk/extras/google/m2repository/com/android/tools/build/aapt2/3.2.0-4818971/aapt2-3.2.0-4818971-linux.jar
	    file:/home/local/SPREADTRUM/ben.shi/android/sdk/extras/android/m2repository/com/android/tools/build/aapt2/3.2.0-4818971/aapt2-3.2.0-4818971.pom
    	file:/home/local/SPREADTRUM/ben.shi/android/sdk/extras/android/m2repository/com/android/tools/build/aapt2/3.2.0-4818971/aapt2-3.2.0-4818971-linux.jar
	    https://jcenter.bintray.com/com/android/tools/build/aapt2/3.2.0-4818971/aapt2-3.2.0-4818971.pom	
	    https://jcenter.bintray.com/com/android/tools/build/aapt2/3.2.0-4818971/aapt2-3.2.0-4818971-linux.jar
	    https://google.bintray.com/tensorflow/com/android/tools/build/aapt2/3.2.0-4818971/aapt2-3.2.0-4818971.pom
		  https://google.bintray.com/tensorflow/com/android/tools/build/aapt2/3.2.0-4818971/aapt2-3.2.0-4818971-linux.jar
	Required by:
	    project :app

**Comment by wt-huang** [comment]
@benshi001 Please check this out in Android 3.2 release note:
Beginning with Android Studio 3.2, the source for AAPT2 (Android Asset Packaging Tool 2) is Google's Maven repository.
To use AAPT2, make sure that you have a google() dependency in your build.gradle file, as shown here:
```
  buildscript {
      repositories {
          google() // here
          jcenter()
      }
      dependencies {
          classpath 'com.android.tools.build:gradle:3.2.0'
      }
  } allprojects {
      repositories {
          google() // and here
          jcenter()
  }
```

**Comment by YXLCN** [comment]
> @benshi001 Please check out Android 3.2 release note:
> Beginning with Android Studio 3.2, the source for AAPT2 (Android Asset Packaging Tool 2) is Google's Maven repository.
> To use AAPT2, make sure that you have a google() dependency in your build.gradle file, as shown here:
> 
> ```
>   buildscript {
>       repositories {
>           google() // here
>           jcenter()
>       }
>       dependencies {
>           classpath 'com.android.tools.build:gradle:3.2.0'
>       }
>   } allprojects {
>       repositories {
>           google() // and here
>           jcenter()
>   }
> ```

Hello, by using AndroidStudio3.0 I have a problem is that TF-Lite demo project cannot sync with error "org.gradle.internal.event.ListenerNotificationException: Failed to notify build listener".
There are more log such as "Cause: org.jetbrains.plugins.gradle.tooling.util.ModuleComponentIdentifierImpl", "java.lang.AbstractMethodError: org.jetbrains.plugins.gradle.tooling.util.ModuleComponentIdentifierImpl.getModuleIdentifier()". 
But I can run this demo project with AndroidStudio2.2.. I want to know the reason, could u help me?
顺便，这里好像都是中国人啊XD

**Comment by YXLCN** [comment]
> @benshi001 Please check out Android 3.2 release note:
> Beginning with Android Studio 3.2, the source for AAPT2 (Android Asset Packaging Tool 2) is Google's Maven repository.
> To use AAPT2, make sure that you have a google() dependency in your build.gradle file, as shown here:
> 
> ```
>   buildscript {
>       repositories {
>           google() // here
>           jcenter()
>       }
>       dependencies {
>           classpath 'com.android.tools.build:gradle:3.2.0'
>       }
>   } allprojects {
>       repositories {
>           google() // and here
>           jcenter()
>   }
> ```

[idea.log](https://github.com/tensorflow/tensorflow/files/2642076/idea.log)
This is my log file..
