### ISSUE TITLE
[Feature Request] DistributionStrategy example not using Keras or estimator API

### ISSUE THREAD

**Issue by terrykong** [tensorflow/tensorflow#22511]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
- **TensorFlow installed from (source or binary)**:
- **TensorFlow version (use command below)**:
- **Python version**:
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:

### Describe the problem
Hi guys,

I was curious if there are any resources to using a DistributionStrategy if some of us to choose to create a model using the low level tensorflow API and manage our own session. I see that with estimators we can define a tf.estimator.RunConfig and pass the strategies there, and with keras you can pass the strategy when you compile the model, but in general where are we supposed to pass the DistributionStrategy? Is it somehow supposed to be passed to tf.ConfigProto or tf.train.MonitoredTrainingSession? If there aren't any resources, I think it would be super helpful to have an example like https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/distribute/python/examples/keras_mnist.py 

Thanks!

**Comment by terrykong** [comment]
I see. I can start looking there. I was trying to find a good starting point to trying out CollectiveAllReduceStrategy. What I'm interested in is an alternative to Horovod, and this looks like the way to do it.

**Comment by guptapriya** [comment]
In that case I think this is a better place to start, as CollectiveAllReduceStrategy requires additional setup:

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/distribute/python/collective_all_reduce_strategy_test.py

**Comment by terrykong** [comment]
Cool, so I've tried my best to create a self contained working example but it isn't working and I'm not quite sure what's wrong. Here is what I'm running (this is a box with two GPUs):

1. Running `CUDA_VISIBLE_DEVICES=0 python train.py --task_type=worker --task_index=0 &`
2. Running `CUDA_VISIBLE_DEVICES=1 python train.py --task_type=worker --task_index=1 &`
3. Running `CUDA_VISIBLE_DEVICES=-1 python train.py --task_type=chief --task_index=0`

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/distribute/python/values.py", line 69, in get
    return self._index[device]
KeyError: '/replica:0/task:0/device:CPU:0'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "train.py", line 165, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "train.py", line 154, in main
    master=server.target) as sess:
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 504, in MonitoredTrainingSession
    stop_grace_period_secs=stop_grace_period_secs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 921, in __init__
    stop_grace_period_secs=stop_grace_period_secs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 643, in __init__
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 1107, in __init__
    _WrappedSession.__init__(self, self._create_session())
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 1112, in _create_session
    return self._sess_creator.create_session()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 800, in create_session
    self.tf_sess = self._session_creator.create_session()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 557, in create_session
    self._scaffold.finalize()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 195, in finalize
    default_ready_op)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 265, in get_or_default
    op = default_constructor()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 190, in default_ready_op
    variables.report_uninitialized_variables(),
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/tf_should_use.py", line 189, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/variables.py", line 2720, in report_uninitialized_variables
    [s.op.name for s in var_list])
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/variables.py", line 2720, in <listcomp>
    [s.op.name for s in var_list])
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/distribute/python/values.py", line 305, in op
    return self.get().op
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/distribute/python/values.py", line 73, in get
    (device, self._index.keys(), device_util.current())), e)
  File "<string>", line 3, in raise_from
ValueError: Device /replica:0/task:0/device:CPU:0 not found in dict_keys(['/job:chief/replica:0/task:0/device:GPU:0']) (current device /device:CPU:0)
```

Here's the training script:

```python
#!/usr/bin/env python

import os
import tensorflow as tf
import tensorflow.contrib as tfc
from enum import Enum
import json

flags = tf.flags

flags.DEFINE_integer("task_index", None, "task_index")
flags.DEFINE_enum("task_type", None, ('chief', 'worker'), "task type")

FLAGS = flags.FLAGS

class Mode(Enum):
    TRAINING = 1
    VALIDATING = 2
    INFERENCE = 3

tf.set_random_seed(4)
batch_size = 4
def get_dataset(x,y):
    dataset1 = tf.data.Dataset.from_tensor_slices(x).batch(batch_size).map(lambda x: tf.reshape(x,[-1,1]))
    dataset2 = tf.data.Dataset.from_tensor_slices(y).batch(batch_size).map(lambda x: tf.reshape(x,[-1,1]))
    dataset = tf.data.Dataset.zip((dataset1,dataset2))
    
    return dataset

class Model(object):
    def __init__(self, mode, iterator=None, task_index=0):
        self.task_index = task_index
        self.iterator = iterator
        self.distribution = tf.contrib.distribute.get_distribution_strategy()
        
        self.input_data = tf.placeholder(tf.float32, [None,1], name="input_data")
        
        if mode == Mode.TRAINING:
            tower_train_ops = self.distribution.call_for_each_tower(self.tower_loss_and_backprop, self.iterator.get_next(), True)
            self.train_op = tf.group(self.distribution.unwrap(tower_train_ops))
            
        elif mode == Mode.VALIDATING:
            total_loss = self.distribution.call_for_each_tower(self.tower_loss, *self.iterator.get_next())
            self.loss = self.distribution.unwrap(self.distribution.reduce(tf.VariableAggregation.SUM, total_loss, "/device:GPU:0"))[0]
        else:
            self.loss = self.tower_loss(self.input_data)
        
    def tower_loss(self, inputs, labels=None):
        self.w = w = tf.get_variable('w',initializer=tf.random_normal_initializer, shape=(1,1))
        self.b = b = tf.get_variable('b',initializer=tf.constant_initializer(0.0), shape=(1,1))
        
        self.y_pred = tf.matmul(inputs,w) + b
        if labels is None:
            return None
        loss = (labels - self.y_pred)**2
        
        return tf.reduce_sum(loss)
    
    def tower_loss_and_backprop(self, iter_get_next, is_training=False):
        inputs, labels = iter_get_next
        
        self.loss = self.tower_loss(inputs,labels)
        
        if not is_training:
            return None
        optimizer = tf.train.AdamOptimizer(0.01)
        gradients, variables = zip(*optimizer.compute_gradients(self.loss))
        gradients, _ = tf.clip_by_global_norm(gradients, 5.0)
        with tf.variable_scope(tf.get_variable_scope(), reuse=tf.AUTO_REUSE):
            train_op = optimizer.apply_gradients(zip(gradients, variables), global_step=tf.train.get_or_create_global_step())
        
        return train_op
        

def main(_):
    #distribution = tfc.distribute.OneDeviceStrategy('device:CPU:0')
    distribution = tfc.distribute.CollectiveAllReduceStrategy(num_gpus_per_worker=1)
    
    worker_hosts = ['localhost:1111', 'localhost:1112']
    chief_host = ['localhost:1113']
    cluster = tf.train.ClusterSpec({"worker": worker_hosts, "chief": chief_host})
    task_type = FLAGS.task_type
    task_index = FLAGS.task_index
    is_chief = FLAGS.task_type == "chief"
    
    sess_config = tf.ConfigProto(
                    log_device_placement=True,
                    allow_soft_placement=True,  # Choose existing device to run ops in case specified one doesn't exist
                )
    sess_config.gpu_options.allow_growth = True  # This is to avoid using all RAM and to only use what it needs
    
    # If this is a worker, then set environment variable and join
    if not is_chief:
        os.environ['TF_CONFIG'] = json.dumps({"cluster":
                                                  {"worker": worker_hosts, "chief": chief_host},
                                              "task":
                                                  {"type": task_type,"index": task_index}
                                              })
        print('TF_CONFIG=' + os.environ['TF_CONFIG'])
        tf.contrib.distribute.run_standard_tensorflow_server(sess_config).join()
    
    server = tf.train.Server(
            cluster, job_name=task_type, task_index=task_index)
    
    if task_type and task_index is not None:
        if type(distribution) == tfc.distribute.OneDeviceStrategy:
            print('Using OneDeviceStrategy')
            distribution.configure(session_config=sess_config)
        elif type(distribution) == tfc.distribute.CollectiveAllReduceStrategy:
            print('Using CollectiveAllReduceStrategy')
            distribution.configure(session_config=sess_config,
                                   cluster_spec=cluster,
                                   task_type=task_type,
                                   task_id=task_index)
    
    foo = lambda a: list(map(lambda x: 3.0*x + 5.0, a))
    x_train = [i*1.0 for i in range(-100,100)]
    x_valid = [i*1.0 for i in range(-10,10)]
    
    with distribution.scope():
        with tf.name_scope('Train'):
            train_dataset = get_dataset(x_train, foo(x_train))
            train_iterator = distribution.distribute_dataset(lambda: train_dataset).make_initializable_iterator()
            with tf.variable_scope('Model'):
                m = Model(Mode.TRAINING, train_iterator)
        
        with tf.name_scope('Valid'):
            valid_dataset = get_dataset(x_valid, foo(x_valid))
            valid_iterator = distribution.distribute_dataset(lambda: valid_dataset).make_initializable_iterator()
            with tf.variable_scope('Model', reuse=True):
                m_valid = Model(Mode.VALIDATING, valid_iterator)
        
        with tf.name_scope('Serving'):
            with tf.variable_scope('Model', reuse=True):
                m_serve = Model(Mode.INFERENCE)
        
    def run_epoch(model, train_op=None):
        sess.run(model.iterator.initializer)
        total_loss = 0
        
        fetches = {'loss':model.loss}
        if train_op is not None:
            fetches['train_op'] = train_op
        while True:
            try:
                vals = sess.run(fetches)
            except tf.errors.OutOfRangeError:
                break
            total_loss += vals['loss']
        return total_loss
    
    with tf.train.MonitoredTrainingSession(config=sess_config,
                                          is_chief=is_chief,
                                          master=server.target) as sess:
        for epoch_id in range(50):
            t_loss = run_epoch(m, m.train_op)
            if epoch_id % 10 == 0:
                print('Epoch:', epoch_id)
                print('Training loss:',t_loss)
                print('Validating loss:', run_epoch(m_valid))
                print('w = {} | b = {}'.format(*sess.run([m.w, m.b])))
                print('----'*10)

if __name__ == "__main__":
    tf.app.run()

```

I also don't understand why this script complains when I don't specify the "destinations" when calling `self.loss = self.distribution.unwrap(self.distribution.reduce(tf.VariableAggregation.SUM, total_loss, "/device:GPU:0"))[0]`.  If I let "destinations" default to None, I get this error

```
Traceback (most recent call last):
  File "train.py", line 165, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "train.py", line 131, in main
    m_valid = Model(Mode.VALIDATING, valid_iterator)
  File "train.py", line 44, in __init__
    self.loss = self.distribution.unwrap(self.distribution.reduce(tf.VariableAggregation.SUM, total_loss))[0]
TypeError: reduce() missing 1 required positional argument: 'destinations'
```

**Comment by yuefengz** [comment]
To use multi-worker distribution strategies without Estimator training API, you have to use distribute coordinator which is not exposed yet: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/distribute/estimator_training.py#L272 It's very error-prone to mimic it by yourself. The details are also subject to change.

@guptapriya We probably need to think about whether and how to support multi-worker training without high-level APIs.

**Comment by yuefengz** [comment]
This is not right: `# If this is a worker, then set environment variable and join`. For `CollectiveAllReduceStrategy`, all workers including chief should run the same model replica with different "TF_CONFIG", which is similar to parameter server architectures.

**Comment by guptapriya** [comment]
@yuefengz i think the replicator story that we've started working on will be a good alternative for when people cannot use high level APIs. in a nutshell, it allows you to distribute an arbitrary step function. It  doesn't deal with the session creation etc. though, so i am not yet clear how we can integrate distributed coordinator with it.

**Comment by terrykong** [comment]
@yuefengz I see. I mistakenly thought I could also just start up the workers with a join() which seemed to be the case here #22321 . Let me see if what you're suggesting helps.

@guptapriya Is this alternative you have in mind released/exposed yet?

**Comment by guptapriya** [comment]
@terrykong No, we are working on the design right now so it might be a while before that is released.

**Comment by ymodak** [comment]
@terrykong  Is this still an issue?

**Comment by terrykong** [comment]
I still haven't gotten this to work even with the suggestions. I haven't had time yet to look into the distribute coordinator that yuefengz mentioned, but I'm hoping that there's a simpler way to get this example up and running

**Comment by yuefengz** [comment]
We will be creating a mid-level API for users to customize their training loop. See the [RFC PR](https://github.com/tensorflow/community/pull/25) here.
