### ISSUE TITLE
TFLite Model Optimizer: Doesn't work on Transformer Model

### ISSUE THREAD

**Issue by vkmenon** [tensorflow/tensorflow#22552]
------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
- **TensorFlow installed from (source or binary)**: Binary
- **TensorFlow version (use command below)**: 1.10.0
- **Python version**: 2.7
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:

```
tflite_convert \
  --output_file=foo.tflite \
  --saved_model_dir=./saved
```
### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.

I have a SavedModel of the Transformer from the Models repo (https://github.com/tensorflow/models/tree/master/official/transformer). I am trying to use the 'Model Optimization Toolkit for TensorFlow' available in TFLite. The documentation states that I should be able to convert a SavedModel into a TFLite Model using the above command. However, I get an error: ValueError: None is only supported in the 1st dimension. Tensor 'input_tensor' has invalid shape '[None, None]'. (see full log below).

This is a feature request to allow TFLite to quantize variable length sequence models. 

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

```
2018-09-26 16:06:20.690105: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX512F
2018-09-26 16:06:20.712622: I tensorflow/core/common_runtime/process_util.cc:69] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
2018-09-26 16:06:23.327033: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:344] Starting optimization for grappler item: tf_graph
2018-09-26 16:06:25.991930: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:344] Starting optimization for grappler item: tf_graph
2018-09-26 16:06:26.384859: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:344] Starting optimization for grappler item: tf_graph
Traceback (most recent call last):
  File "/home/<>/int8/virt2.7/bin/tflite_convert", line 11, in <module>
    sys.exit(main())
  File "/home/<>/int8/virt2.7/lib/python2.7/site-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 412, in main
    app.run(main=run_main, argv=sys.argv[:1])
  File "/home/<>/int8/virt2.7/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/home/<>/int8/virt2.7/lib/python2.7/site-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 408, in run_main
    _convert_model(tflite_flags)
  File "/home/<>/int8/virt2.7/lib/python2.7/site-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 162, in _convert_model
    output_data = converter.convert()
  File "/home/<>/int8/virt2.7/lib/python2.7/site-packages/tensorflow/contrib/lite/python/lite.py", line 408, in convert
    "invalid shape '{1}'.".format(_tensor_name(tensor), shape))
ValueError: None is only supported in the 1st dimension. Tensor 'input_tensor' has invalid shape '[None, None]'
```

**Comment by wt-huang** [comment]
@vkmenon Currently quantization for variable length sequence models is not supported.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @wt-huang: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by abal6725** [comment]
Hello, I was wondering if this is now supported?
