### ISSUE TITLE
Tensorflow example, Object Detection: Failed to find input Node 'image_tensor

### ISSUE THREAD

**Issue by digital-prime** [tensorflow/tensorflow#22565]
I try to run tensorflow object Detection example on android with my own '.pb' file.
I change `TF_OD_API_MODEL_FILE` and `TF_OD_API_LABELS_FILE` to my own files.
When I run it I've got the error:

```
java.lang.RuntimeException: Failed to find input Node 'image_tensor'
        at org.tensorflow.demo.TensorFlowObjectDetectionAPIModel.create(TensorFlowObjectDetectionAPIModel.java:102)
```
But by graph HAS input node name 'image_tensor'!! To check it, I open it with tensorboard and check it.

I don't know what versions and libraries should i write here, maybe someone has same issue? 
 
PS - maybe some error got because I have only one class (and label) to detect? Or it doesn't mean?

_________

EDIT: answer on questions from @tensorflowbutler 

**Have I written custom code**
I'm using only code example from [`official page`](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/android)
I only change name's of files to my own pb - `TF_OD_API_MODEL_FILE` and `TF_OD_API_LABELS_FILE`.

**OS Platform and Distribution**
MAC OS High Sierra 10.13.6

**TensorFlow installed from**
Tensorflow installed from pip

**TensorFlow version**
1.10.1

**Bazel version**
Build label: 0.16.1
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Aug 13 13:42:50 2018 (1534167770)
Build timestamp: 1534167770
Build timestamp as int: 1534167770

**CUDA/cuDNN version**
no

**GPU model and memory**
no

**Exact command to reproduce**
Run app in android studio, start application 'TF Detect', crash on starting.

**Mobile device**
google Nexus 5, api23

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by digital-prime** [comment]
@tensorflowbutler I've edited my question and add this info to it

**Comment by digital-prime** [comment]
when I try to build and run app with option `cmake` + I comment line 
```
apply from: "download-models.gradle"
```
in build.gradle file, app runs and don't fall with error of wrong `input_name`, but now it have another error: with input labels size..  
How does params `outputScores` and `outputClasses` collected in code? Where can i change it ? 

ps - now I don't understand: does code use my own pb file or not? Labels are parsed, I can see it while debugging, but about pb file I can't understand how to check

**Comment by digital-prime** [comment]
Maybe someone can tell me - what should I do - to use TF DETECT demo app with my own pb model file? And all my errors will 'go out' ) 
I have only one class to detect, file pb with exported frozen graph - and what I need to do next?

**Comment by digital-prime** [comment]
So, after I compile and build project with `cmake`, change paths `TF_OD_API_MODEL_FILE` and `TF_OD_API_LABELS_FILE`, create file `labels.txt` with:

```
???
your_object_class_name
```

I can run working example app.
Why don't I find any explanation about this moment with `???` on the top of labels file in Tensorflow tutorials? I think it must be included somewhere, because without this moment no will be worked.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @jch1: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @jch1: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by SteveIb** [comment]
Hi, I have the same issue
I followed the following tutorial to convert it to TFLITE

https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_on_mobile_tensorflowlite.md

Then I had tflite model from my custom dataset. using Mobilenet network.

Now Im having the same error you had When i run TF Detect.
here is the android log

11-19 14:58:53.492 29465-29465/? I/tensorflow: CameraConnectionFragment: Desired size: 640x480, min size: 480x480
    CameraConnectionFragment: Valid preview sizes: [1920x1080, 1440x1080, 1280x720, 720x480, 640x480]
    CameraConnectionFragment: Rejected preview sizes: [320x240]
    CameraConnectionFragment: Exact size match found.
11-19 14:58:53.507 29465-29465/? W/tensorflow: ImageUtils: Native library not found, native RGB -> YUV conversion may be unavailable.
11-19 14:58:53.695 29465-29465/org.tensorflow.demo W/tensorflow: TensorFlowObjectDetectionAPIModel: positive
    TensorFlowObjectDetectionAPIModel: negative
11-19 14:58:53.699 29465-29465/org.tensorflow.demo I/TensorFlowInferenceInterface: Checking to see if TensorFlow native methods are already loaded
11-19 14:58:53.699 29465-29465/org.tensorflow.demo E/art: No implementation found for long org.tensorflow.contrib.android.RunStats.allocate() (tried Java_org_tensorflow_contrib_android_RunStats_allocate and Java_org_tensorflow_contrib_android_RunStats_allocate__)
11-19 14:58:53.699 29465-29465/org.tensorflow.demo I/TensorFlowInferenceInterface: TensorFlow native methods not found, attempting to load via tensorflow_inference
11-19 14:58:53.796 29465-29465/org.tensorflow.demo I/TensorFlowInferenceInterface: Successfully loaded TensorFlow native methods (RunStats error may be ignored)
11-19 14:58:54.082 29465-29465/org.tensorflow.demo I/TensorFlowInferenceInterface: Model load took 27ms, TensorFlow version: 1.12.0
11-19 14:58:54.083 29465-29465/org.tensorflow.demo I/TensorFlowInferenceInterface: Successfully loaded model from 'file:///android_asset/detect300300.tflite'
11-19 14:58:54.084 29465-29465/org.tensorflow.demo E/tensorflow: CameraActivity: Exception!
    java.lang.RuntimeException: Failed to find input Node 'image_tensor'
        at org.tensorflow.demo.TensorFlowObjectDetectionAPIModel.create(TensorFlowObjectDetectionAPIModel.java:102)
        at org.tensorflow.demo.DetectorActivity.onPreviewSizeChosen(DetectorActivity.java:169)
        at org.tensorflow.demo.CameraActivity.onPreviewFrame(CameraActivity.java:120)
        at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1150)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5461)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
11-19 14:59:16.527 29465-29465/org.tensorflow.demo D/tensorflow: CameraActivity: onPause org.tensorflow.demo.DetectorActivity@9bf609f
    CameraActivity: Requesting finish
11-19 14:59:16.580 29465-29465/org.tensorflow.demo D/tensorflow: CameraActivity: onStop org.tensorflow.demo.DetectorActivity@9bf609f
11-19 14:59:16.584 29465-29465/org.tensorflow.demo D/tensorflow: CameraActivity: onDestroy org.tensorflow.demo.DetectorActivity@9bf609f


one of the solution is to change the tensorflow since it is not compatible with the one that android is using .. but still the same results .. i have the latest tensorflow  like this

dependencies {
    if (nativeBuildSystem == 'cmake' || nativeBuildSystem == 'none') {
        compile 'org.tensorflow:tensorflow-android:1.12.0'
        //compile 'org.tensorflow:tensorflow-android:+'
    }
}

but the same error!
any hint?

**Comment by SteveIb** [comment]
I run summarize_graph to see the input and changed the input name to normalized_input_image_tensor but still the same error

bazel-bin/tensorflow/tools/graph_transforms/summarize_graph --in_graph=/home/dell/TFObject-detection/tensorflow/models/research/object_detection/Output2/tflite_graph.pb

Found 1 possible inputs: (name=normalized_input_image_tensor, type=float(1), shape=[1,300,300,3]) 
No variables spotted.
Found 1 possible outputs: (name=TFLite_Detection_PostProcess, op=TFLite_Detection_PostProcess) 
Found 4035720 (4.04M) const parameters, 0 (0) variable parameters, and 0 control_edges
Op types used: 411 Identity, 340 Const, 60 FusedBatchNorm, 55 Conv2D, 43 Relu6, 17 DepthwiseConv2dNative, 12 BiasAdd, 12 Reshape, 10 Add, 2 ConcatV2, 1 Placeholder, 1 RealDiv, 1 Sigmoid, 1 Squeeze, 1 TFLite_Detection_PostProcess
To use with tensorflow/tools/benchmark:benchmark_model try these arguments:
bazel run tensorflow/tools/benchmark:benchmark_model -- --graph=/home/dell/TFObject-detection/tensorflow/models/research/object_detection/Output2/tflite_graph.pb --show_flops --input_layer=normalized_input_image_tensor --input_layer_type=float --input_layer_shape=1,300,300,3 --output_layer=TFLite_Detection_PostProcess

**Comment by SteveIb** [comment]
@SheptunovaAA 
Hi,
Yest I tried it .. didnt work either!

**Comment by xfj81525** [comment]
fuck, following the tensorflow object detection android app demo, it does not work, Failed to find input Node 'normalized_input_image_tensor'
nobody can solve this fucking problem

**Comment by defaultUser3214** [comment]
I have the same issue using a .tflite file that I converted from the ssd_mobilenet_v1 model from http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v1_coco_2017_11_17.tar.gz

Here I have already left a comment:
https://github.com/tensorflow/tensorflow/issues/15633#issuecomment-456860149

**Comment by sushreebarsa** [comment]
@digital-prime Is this still an issue ? We see that you are using old version of tensorflow  1.x which is not actively supported, We recommend that you upgrade to 2.4 or later version and let us know if the issue still persists in newer versions .Please open a new issue in case you face any errors in TF v2, we will get you the right help . Thanks!
