### ISSUE TITLE
[BUG] Tensorflow branch 1.11 test. 

### ISSUE THREAD

**Issue by nikitaverbis** [tensorflow/tensorflow#22602]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04 LTS
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: No
- **TensorFlow installed from (source or binary)**: Source
- **TensorFlow version (use command below)**: 1.11 (git branch 1.11)
- **Python version**: 2.7.12
- **Bazel version (if compiling from source)**: 0.15.2
- **GCC/Compiler version (if compiling from source)**: 
- **CUDA/cuDNN version**: 9.0/7.3
- **GPU model and memory**: Titan Xp
- **Exact command to reproduce**: ```bazel test -c opt -- //tensorflow/... -//tensorflow/compiler/... -//tensorflow/contrib/lite/...```

### Describe the problem
Found a missing imports (pandas and dask) in file tensorflow/tensorflow/contrib/learn/python/learn/learn_io/data_feeder_test.py at line 295.

### Source code / logs
Error1 log:
```
//tensorflow/contrib/learn:data_feeder_test                              FAILED in 1.9s
======================================================================
ERROR: test_dask_data_feeder (__main__.SetupPredictDataFeederTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nikita/.cache/bazel/_bazel_nikita/992bfa23a6d33fa546f39f500a08968c/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/contrib/learn/data_feeder_test.runfiles/org_tensorflow/tensorflow/contrib/learn/python/learn/learn_io/data_feeder_test.py", line 295, in test_dask_data_feeder
    x = pd.DataFrame(
NameError: global name 'pandas' is not defined
```

Solution1:
in file tensorflow/tensorflow/contrib/learn/python/learn/learn_io/data_feeder_test.py add:
```
import pandas as pd
import dask.dataframe as dd
```

Error2 log:
```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //tensorflow/contrib/learn:data_feeder_test
-----------------------------------------------------------------------------
WARNING:tensorflow:From /home/nikita/.cache/bazel/_bazel_nikita/992bfa23a6d33fa546f39f500a08968c/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/contrib/learn/data_feeder_test.runfiles/org_tensorflow/tensorflow/contrib/learn/python/learn/learn_io/data_feeder_test.py:307: __init__ (from tensorflow.contrib.learn.python.learn.learn_io.data_feeder) is deprecated and will be removed in a future version.
Instructions for updating:
Please feed input to tf.data to support dask.
WARNING:tensorflow:float64 is not supported by many models, consider casting to float32.
EWARNING:tensorflow:From /home/nikita/.cache/bazel/_bazel_nikita/992bfa23a6d33fa546f39f500a08968c/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/contrib/learn/data_feeder_test.runfiles/org_tensorflow/tensorflow/contrib/learn/python/learn/learn_io/data_feeder_test.py:246: __init__ (from tensorflow.contrib.learn.python.learn.learn_io.data_feeder) is deprecated and will be removed in a future version.
Instructions for updating:
Please use tensorflow/transform or tf.data.
WARNING:tensorflow:From /home/nikita/.cache/bazel/_bazel_nikita/992bfa23a6d33fa546f39f500a08968c/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/contrib/learn/data_feeder_test.runfiles/org_tensorflow/tensorflow/contrib/learn/python/learn/learn_io/data_feeder.py:340: check_array (from tensorflow.contrib.learn.python.learn.learn_io.data_feeder) is deprecated and will be removed in a future version.
Instructions for updating:
Please convert numpy dtypes explicitly.
...2018-09-28 16:50:14.407888: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX
....WARNING:tensorflow:float64 is not supported by many models, consider casting to float32.
WARNING:tensorflow:float64 is not supported by many models, consider casting to float32.
WARNING:tensorflow:float64 is not supported by many models, consider casting to float32.
.............WARNING:tensorflow:float64 is not supported by many models, consider casting to float32.
E.......WARNING:tensorflow:float64 is not supported by many models, consider casting to float32.
WARNING:tensorflow:float64 is not supported by many models, consider casting to float32.
WARNING:tensorflow:float64 is not supported by many models, consider casting to float32.
..........WARNING:tensorflow:From /home/nikita/.cache/bazel/_bazel_nikita/992bfa23a6d33fa546f39f500a08968c/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/contrib/learn/data_feeder_test.runfiles/org_tensorflow/tensorflow/contrib/learn/python/learn/learn_io/data_feeder_test.py:363: setup_predict_data_feeder (from tensorflow.contrib.learn.python.learn.learn_io.data_feeder) is deprecated and will be removed in a future version.
Instructions for updating:
Please use tensorflow/transform or tf.data.
WARNING:tensorflow:From /home/nikita/.cache/bazel/_bazel_nikita/992bfa23a6d33fa546f39f500a08968c/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/contrib/learn/data_feeder_test.runfiles/org_tensorflow/tensorflow/contrib/learn/python/learn/learn_io/data_feeder.py:215: extract_dask_data (from tensorflow.contrib.learn.python.learn.learn_io.dask_io) is deprecated and will be removed in a future version.
Instructions for updating:
Please feed input to tf.data to support dask.
WARNING:tensorflow:From /home/nikita/.cache/bazel/_bazel_nikita/992bfa23a6d33fa546f39f500a08968c/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/contrib/learn/data_feeder_test.runfiles/org_tensorflow/tensorflow/contrib/learn/python/learn/learn_io/data_feeder.py:217: extract_pandas_data (from tensorflow.contrib.learn.python.learn.learn_io.pandas_io) is deprecated and will be removed in a future version.
Instructions for updating:
Please access pandas data directly.
....
======================================================================
ERROR: test_dask_data_feeder (__main__.DataFeederTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nikita/.cache/bazel/_bazel_nikita/992bfa23a6d33fa546f39f500a08968c/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/contrib/learn/data_feeder_test.runfiles/org_tensorflow/tensorflow/contrib/learn/python/learn/learn_io/data_feeder_test.py", line 307, in test_dask_data_feeder
    df = data_feeder.DaskDataFeeder(x, y, n_classes=2, batch_size=2)
  File "/home/nikita/.cache/bazel/_bazel_nikita/992bfa23a6d33fa546f39f500a08968c/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/contrib/learn/data_feeder_test.runfiles/org_tensorflow/tensorflow/python/util/deprecation.py", line 306, in new_func
    return func(*args, **kwargs)
  File "/home/nikita/.cache/bazel/_bazel_nikita/992bfa23a6d33fa546f39f500a08968c/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/contrib/learn/data_feeder_test.runfiles/org_tensorflow/tensorflow/contrib/learn/python/learn/learn_io/data_feeder.py", line 872, in __init__
    self._output_dtype = _check_dtype(self._y.dtypes[self._y_columns])
  File "/home/nikita/.cache/bazel/_bazel_nikita/992bfa23a6d33fa546f39f500a08968c/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/contrib/learn/data_feeder_test.runfiles/org_tensorflow/tensorflow/contrib/learn/python/learn/learn_io/data_feeder.py", line 281, in _check_dtype
    if dtypes.as_dtype(dtype) == dtypes.float64:
  File "/home/nikita/.cache/bazel/_bazel_nikita/992bfa23a6d33fa546f39f500a08968c/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/contrib/learn/data_feeder_test.runfiles/org_tensorflow/tensorflow/python/framework/dtypes.py", line 681, in as_dtype
    return _INTERN_TABLE[type_value]
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/generic.py", line 1045, in __hash__
    ' hashed'.format(self.__class__.__name__))
TypeError: 'Series' objects are mutable, thus they cannot be hashed

======================================================================
ERROR: test_dask_data_feeder (__main__.SetupPredictDataFeederTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nikita/.cache/bazel/_bazel_nikita/992bfa23a6d33fa546f39f500a08968c/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/contrib/learn/data_feeder_test.runfiles/org_tensorflow/tensorflow/contrib/learn/python/learn/learn_io/data_feeder_test.py", line 307, in test_dask_data_feeder
    df = data_feeder.DaskDataFeeder(x, y, n_classes=2, batch_size=2)
  File "/home/nikita/.cache/bazel/_bazel_nikita/992bfa23a6d33fa546f39f500a08968c/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/contrib/learn/data_feeder_test.runfiles/org_tensorflow/tensorflow/python/util/deprecation.py", line 306, in new_func
    return func(*args, **kwargs)
  File "/home/nikita/.cache/bazel/_bazel_nikita/992bfa23a6d33fa546f39f500a08968c/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/contrib/learn/data_feeder_test.runfiles/org_tensorflow/tensorflow/contrib/learn/python/learn/learn_io/data_feeder.py", line 872, in __init__
    self._output_dtype = _check_dtype(self._y.dtypes[self._y_columns])
  File "/home/nikita/.cache/bazel/_bazel_nikita/992bfa23a6d33fa546f39f500a08968c/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/contrib/learn/data_feeder_test.runfiles/org_tensorflow/tensorflow/contrib/learn/python/learn/learn_io/data_feeder.py", line 281, in _check_dtype
    if dtypes.as_dtype(dtype) == dtypes.float64:
  File "/home/nikita/.cache/bazel/_bazel_nikita/992bfa23a6d33fa546f39f500a08968c/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/contrib/learn/data_feeder_test.runfiles/org_tensorflow/tensorflow/python/framework/dtypes.py", line 681, in as_dtype
    return _INTERN_TABLE[type_value]
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/generic.py", line 1045, in __hash__
    ' hashed'.format(self.__class__.__name__))
TypeError: 'Series' objects are mutable, thus they cannot be hashed

Ran 43 tests in 0.184s

FAILED (errors=2)
tf.estimator package not installed.
```

With second error I don`t know what to do.

**Comment by gunan** [comment]
@ispirmustafa @martinwicke do we still support contrib/learn?

**Comment by martinwicke** [comment]
No. It's been deprecated for a while.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @gunan: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by gunan** [comment]
I will close this issue as it is an issue in a deprecated component.
