### ISSUE TITLE
[BUG] Executing genrule //tensorflow:tf_python_api_gen_v1 failed (Exit 1)

### ISSUE THREAD

**Issue by SummerLife** [tensorflow/tensorflow#22641]
ERROR: /home/tensor/tensorflow/tensorflow/BUILD:566:1: Executing genrule //tensorflow:tf_python_api_gen_v1 failed (Exit 1)
Traceback (most recent call last):
  File "/home/tensor/.cache/bazel/_bazel_tensor/6576bf81f142261c3a81cca43642eb08/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/python/tools/api/generator/create_python_api.py", line 27, in <module>
    from tensorflow.python.tools.api.generator import doc_srcs
  File "/home/tensor/.cache/bazel/_bazel_tensor/6576bf81f142261c3a81cca43642eb08/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 127, in <module>
    from tensorflow.python.platform import test
  File "/home/tensor/.cache/bazel/_bazel_tensor/6576bf81f142261c3a81cca43642eb08/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/python/platform/test.py", line 47, in <module>
    import mock                # pylint: disable=g-import-not-at-top,unused-import
ImportError: No module named mock
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 3283.850s, Critical Path: 90.89s
INFO: 3418 processes: 3418 local.
FAILED: Build did NOT complete successfully

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by SummerLife** [comment]
Thank you very much. I want to build tensorflow by using its source code. And it is cup-only

**Comment by SummerLife** [comment]
the Bazel version I used is 0.17.2

**Comment by charlesverge** [comment]
See
```ImportError: No module named mock```

@SummerLife Try installing the module mock

**Comment by ymodak** [comment]
@SummerLife Did this solve your issue?
> See
> `ImportError: No module named mock`
> 
> @SummerLife Try installing the module mock

**Comment by SummerLife** [comment]
Thank you very much! I truely solved this problem through installing the module!

**Comment by quantitative-technologies** [comment]
$ bazel build --verbose_failures tensorflow/tools/pip_package:build_pip_package

Traceback (most recent call last):
  File "/home/james/.cache/bazel/_bazel_james/eb428e77df4edf260b1a35afd0cdd799/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen_compat_v2.runfiles/org_tensorflow/tensorflow/python/tools/api/generator/create_python_api.py", line 776, in <module>
    main()
  File "/home/james/.cache/bazel/_bazel_james/eb428e77df4edf260b1a35afd0cdd799/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen_compat_v2.runfiles/org_tensorflow/tensorflow/python/tools/api/generator/create_python_api.py", line 755, in main
    importlib.import_module(package)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/james/.cache/bazel/_bazel_james/eb428e77df4edf260b1a35afd0cdd799/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen_compat_v2.runfiles/org_tensorflow/tensorflow/python/keras/datasets/imdb.py", line 25, in <module>
    from tensorflow.python.keras.preprocessing.sequence import _remove_long_seq
  File "/home/james/.cache/bazel/_bazel_james/eb428e77df4edf260b1a35afd0cdd799/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen_compat_v2.runfiles/org_tensorflow/tensorflow/python/keras/preprocessing/__init__.py", line 23, in <module>
    import keras_preprocessing
ModuleNotFoundError: No module named 'keras_preprocessing'


However, I do have `keras_preprocessing` installed.

**Comment by sumit0309** [comment]
I am also facing same issue.

**Comment by Devjiu** [comment]
+1

**Comment by MtotheKay** [comment]
+1

**Comment by penny9287** [comment]
I solved this problem through reinstalling the numpy module.
