### ISSUE TITLE
fully_connected_preloaded.py fails with Error on Python 2.7.6

### ISSUE THREAD

**Issue by knetch** [tensorflow/tensorflow#2267]
### Environment info
Operating System: Linux xxxxx-Lenovo-Ideapad-V570 3.19.0-58-generic #64~14.04.1-Ubuntu SMP Fri Mar 18 19:05:43 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Installed version of CUDA and cuDNN: n/a
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

If installed from binary pip package, provide:

1. Which pip package you installed.
n/a - used install.sh
2. The output from python -c "import tensorflow; print(tensorflow.__version__)".
0.6.0

If installed from sources, provide the commit hash:
0d350f9324ae08dcbe0c14f0dbfde169da260a37
### Steps to reproduce
1. python tensorflow/examples/how_tos/reading_data/fully_connected_preloaded.py 
2.
3.

### What have you tried?
1. cd tensorflow/examples/how_tos/reading_data
python fully_connected_preloaded.py

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).
Extracting /tmp/data/train-images-idx3-ubyte.gz
Extracting /tmp/data/train-labels-idx1-ubyte.gz
Extracting /tmp/data/t10k-images-idx3-ubyte.gz
Extracting /tmp/data/t10k-labels-idx1-ubyte.gz
I tensorflow/core/common_runtime/local_device.cc:40] Local device intra op parallelism threads: 4
I tensorflow/core/common_runtime/direct_session.cc:58] Direct session inter op parallelism threads: 4
Traceback (most recent call last):
  File "tensorflow/examples/how_tos/reading_data/fully_connected_preloaded.py", line 157, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/default/_app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "tensorflow/examples/how_tos/reading_data/fully_connected_preloaded.py", line 153, in main
    run_training()
  File "tensorflow/examples/how_tos/reading_data/fully_connected_preloaded.py", line 106, in run_training
    summary_writer = tf.train.SummaryWriter(FLAGS.train_dir, sess.graph)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/summary_io.py", line 103, in __init__
    self.add_graph(graph_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/summary_io.py", line 151, in add_graph
    event = event_pb2.Event(wall_time=time.time(), graph_def=graph_def)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/internal/python_message.py", line 455, in init
    _ReraiseTypeErrorWithFieldName(message_descriptor.name, field_name)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/internal/python_message.py", line 386, in _ReraiseTypeErrorWithFieldName
    raise type(exc)(exc, sys.exc_info()[2])
TypeError: (TypeError('Parameter to MergeFrom() must be instance of same class: expected GraphDef got Graph. for field Event.graph_def',), <traceback object at 0x7fce35658b00>)

**Comment by mrry** [comment]
This example has been updated to use features only available in TensorFlow 0.8. I'd strongly recommend upgrading to the newest version. Otherwise, you should check out the [version of this example from the 0.6.0 branch](https://github.com/tensorflow/tensorflow/blob/0.6.0/tensorflow/examples/how_tos/reading_data/fully_connected_preloaded.py).
