### ISSUE TITLE
Keras Mobilenet not loading after save

### ISSUE THREAD

**Issue by mhwilder** [tensorflow/tensorflow#22697]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
    - Yes, though very basic
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
    - Mac OSX 10.13.6
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
    - N/A
- **TensorFlow installed from (source or binary)**:
    - pip install tf-nightly
- **TensorFlow version (use command below)**:
    - v1.9.0-rc2-4942-g19b2383cc0 1.12.0-dev20180929
- **Python version**:
    - 3.6.5
- **Bazel version (if compiling from source)**:
    - N/A
- **GCC/Compiler version (if compiling from source)**:
    - N/A
- **CUDA/cuDNN version**:
    - N/A
- **GPU model and memory**:
    - N/A
- **Exact command to reproduce**:

```python
from tensorflow import keras
model = keras.applications.MobileNet()
model.compile(optimizer='adam', loss='categorical_crossentropy')
model.save('./model.h5')
loaded_model = keras.models.load_model('./model.h5')
```

### Describe the problem

Keras mobilenet_v1 model will not load after saving (see code sample above). An error is thrown in advanced_activations when loading a ReLU layer with a max_value parameter because the parameters are not of the expected type (float or None). They are a dict because that's how they were read from the config. The dict looks like this: {'type': 'ndarray', 'value': 6.0} but really should just be a float. This error occurs with the nightly build and also in 1.11.

### Source code / logs

```
Traceback (most recent call last):
  File "error.py", line 5, in <module>
    loaded_model = keras.models.load_model('./model.h5')
  File "tmp_env/lib/python3.6/site-packages/tensorflow/python/keras/engine/saving.py", line 230, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "tmp_env/lib/python3.6/site-packages/tensorflow/python/keras/engine/saving.py", line 310, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "tmp_env/lib/python3.6/site-packages/tensorflow/python/keras/layers/serialization.py", line 64, in deserialize
    printable_module_name='layer')
  File "tmp_env/lib/python3.6/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 173, in deserialize_keras_object
    list(custom_objects.items())))
  File "tmp_env/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 1292, in from_config
    process_layer(layer_data)
  File "tmp_env/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 1278, in process_layer
    layer = deserialize_layer(layer_data, custom_objects=custom_objects)
  File "tmp_env/lib/python3.6/site-packages/tensorflow/python/keras/layers/serialization.py", line 64, in deserialize
    printable_module_name='layer')
  File "tmp_env/lib/python3.6/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 175, in deserialize_keras_object
    return cls.from_config(config['config'])
  File "tmp_env/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1617, in from_config
    return cls(**config)
  File "tmp_env/lib/python3.6/site-packages/tensorflow/python/keras/layers/advanced_activations.py", line 309, in __init__
    if max_value is not None and max_value < 0.:
TypeError: '<' not supported between instances of 'dict' and 'float'
```

**Comment by harshini-gadige** [comment]
@mhwilder Hi, I understand that you are facing the similar issue with nightly build also. Can you please give a try with a lower version of tensorflow and let us know if you still face this issue.

**Comment by mhwilder** [comment]
@harshini-gadige I just verified that I get the same error in TensorFlow version 1.11.0.

**Comment by mevatron** [comment]
@harshini-gadige @fchollet  I'm also seeing this with the `MobileNetV2` model. I see it when using the `tf.keras.load_model` with version `tf.keras.__version__ = 2.1.6-tf`. However, when using `keras.load_model` with version `keras.__version__ = 2.2.4` it loads the model properly. Hope that helps!

**Comment by tensorflowbutler** [comment]
Nagging Assignee @fchollet: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by patinronin** [comment]
hi i have the same issue can´t load my model,  i was  working whit mobilnetV2 with keras 2.2.4 version and tensorflow 1.10.0 version ¿ do you have any solution ? 
i downgrade tensorflow to 1.9.0 version and still have the same problem 
¿Any recommendation?

**Comment by mhwilder** [comment]
This issue is still a problem but here's the workaround I've been using. It's not really the right solution, but at least my mobilenet V1 and V2 models can be reloaded. I agree with @mevatron that the problem is probably in how the model is being saved (specifically, the format used for the ReLu parameters).

**Temporary Fix:**
After the ```super()``` call in the ReLu ```init()``` function in _tensorflow/python/keras/layers/advanced\_activations.py_ (around line 310), add the following lines of code:
```
    if type(max_value) is dict:
        max_value = max_value['value']
    if type(negative_slope) is dict:
        negative_slope = negative_slope['value']
    if type(threshold) is dict:
        threshold = threshold['value']
```

**Comment by stetelepta** [comment]
I've had the same problem and found that since Tensorflow 1.12.0 you can [directly export Keras models to the SavedModel format](https://github.com/tensorflow/tensorflow/releases).

Using this new feature, I can successfully save and load my Mobilenet models. 

Note that if you save models like this, Tensorflow recommends an optimizer from `tf.train`, instead of the Keras optimizer.

```
import tensorflow as tf
model = tf.keras.applications.MobileNet()
model.compile(optimizer=tf.train.AdamOptimizer(), loss='categorical_crossentropy')
output_path = tf.contrib.saved_model.save_keras_model(model, './tmp_dir')
loaded_model = tf.contrib.saved_model.load_keras_model(output_path)
```

**Comment by danilfromekb** [comment]
For some purposes (for example, for using in another keras-compatible frameworks) you may want to save model exactly in hdf5 format. 
To save model with ReLU layer in hdf5 format using tensorflow implementation of keras one can replace:
    config = {
        'max_value': self.max_value,
        'negative_slope': self.negative_slope,
        'threshold': self.threshold
    }
with:
    max_value = None if self.max_value is None else float(self.max_value)
    config = {
        'max_value': max_value,
        'negative_slope': float(self.negative_slope),
        'threshold': float(self.threshold)
    }
in get_config method of ReLU class in tensorflow/python/keras/layers/advanced_activations.py (around line 332)

**Comment by ividal** [comment]
> ```
> import tensorflow as tf
> model = tf.keras.applications.MobileNet()
> model.compile(optimizer=tf.train.AdamOptimizer(), loss='categorical_crossentropy')
> output_path = tf.contrib.saved_model.save_keras_model(model, './tmp_dir')
> loaded_model = tf.contrib.saved_model.load_keras_model(output_path)
> ```

You are a lifesaver, thank you! This worked for me with TF 1.12 and python 3.6.

**Comment by fzyzcjy** [comment]
Hi! Is there any fix now?

**Comment by ingramator** [comment]
This is still not fixed and on 1.12 and 1.13 the newly loaded model actually just produces random results if not in the session that trained the model.

**Comment by ymodak** [comment]
This is fixed with TF version 1.15 and in TF 2. Thanks!

**Comment by Shradha97** [comment]
> I've had the same problem and found that since Tensorflow 1.12.0 you can [directly export Keras models to the SavedModel format](https://github.com/tensorflow/tensorflow/releases).
> 
> Using this new feature, I can successfully save and load my Mobilenet models.
> 
> Note that if you save models like this, Tensorflow recommends an optimizer from `tf.train`, instead of the Keras optimizer.
> 
> ```
> import tensorflow as tf
> model = tf.keras.applications.MobileNet()
> model.compile(optimizer=tf.train.AdamOptimizer(), loss='categorical_crossentropy')
> output_path = tf.contrib.saved_model.save_keras_model(model, './tmp_dir')
> loaded_model = tf.contrib.saved_model.load_keras_model(output_path)
> ```

Thanks a lot!!...You saved my life.

**Comment by MarceloSabaris** [comment]
Verify  if the model using token or any object to train, in the new version of tensorflow don´t have problem. My sugest , serialize the objetcs using picle like the code below . 

import pickle

with open('Percentage_'+ str(percentageData) +  '/train_dataframe', "wb") as f:
    pickle.dump(train_dataframe, f)

And use de model.save and tf.keras.models.load_model
