### ISSUE TITLE
tensorflow-gpu being ruined by matplotlib

### ISSUE THREAD

**Issue by H0bbitBaron** [tensorflow/tensorflow#22703]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: gpu-1.10.0-hf154084_0
- **Python version**: 3.6.6-hc3d631a_0
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**: 9.0
- **GPU model and memory**: 1070
- **Exact command to reproduce**:
conda create --name test python=3.6.6 tensorflow-gpu spyder pandas
source activate test
-- problem starts here
conda install matplotlib
spyder
import tensorflow.contrib.training as training
- **Versions**:spyder=3.3.1, pandas=0.23.4, matplotlib=3.0.0

### Describe the problem
Tensorflow-gpu works fine (import tensorflow.contrib.training as training executes without errors) until the installation of matplotlib. After that "import tensorflow.contrib.training as training" gives this error:

    import tensorflow.contrib.training as training
    Traceback (most recent call last):
    
      File "/home/nikolay/anaconda3/envs/test/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2961, in run_code
        exec(code_obj, self.user_global_ns, self.user_ns)
    
      File "<ipython-input-1-f7e526cc11b2>", line 1, in <module>
        import tensorflow.contrib.training as training
    
      File "/home/nikolay/anaconda3/envs/test/lib/python3.6/site-packages/tensorflow/contrib/__init__.py", line 48, in <module>
        from tensorflow.contrib import image
    
      File "/home/nikolay/anaconda3/envs/test/lib/python3.6/site-packages/tensorflow/contrib/image/__init__.py", line 70, in <module>
        from tensorflow.contrib.image.python.ops.single_image_random_dot_stereograms import single_image_random_dot_stereograms
    
      File "/home/nikolay/anaconda3/envs/test/lib/python3.6/site-packages/tensorflow/contrib/image/python/ops/single_image_random_dot_stereograms.py", line 27, in <module>
        "_single_image_random_dot_stereograms.so"))
    
      File "/home/nikolay/anaconda3/envs/test/lib/python3.6/site-packages/tensorflow/contrib/util/loader.py", line 56, in load_op_library
        ret = load_library.load_op_library(path)
    
      File "/home/nikolay/anaconda3/envs/test/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 73, in load_op_library
        exec(wrappers, module.__dict__)
    
      File "<string>", line 27
        def single_image_random_dot_stereograms(depth_values, hidden_surface_removal=True, convergence_dots_size=8, dots_per_inch=72, eye_separation=2,5, mu=0,333299994, normalize=True, normalize_max=-100, normalize_min=100, border_level=0, number_colors=256, output_image_shape=[1024, 768, 1], output_data_window=[1022, 757], name=None):
                                                                                                                                                       ^
    SyntaxError: invalid syntax

if it matters, here is what matplotlib installation looks like:

    (test) xxx@xxx:~$ conda install matplotlib
    Solving environment: done
    
    ## Package Plan ##
    
      environment location: /home/xxx/anaconda3/envs/test
    
      added / updated specs: 
        - matplotlib
    
    
    The following NEW packages will be INSTALLED:
    
        cycler:     0.10.0-py36_0       
        kiwisolver: 1.0.1-py36hf484d3e_0
        matplotlib: 3.0.0-py36h5429711_0
    
    Proceed ([y]/n)? y
    
    Preparing transaction: done
    Verifying transaction: done
    Executing transaction: done

**Comment by H0bbitBaron** [comment]
Neither it is ok after installing tensorflow-gpu via pip:

    conda create --name test python=3.6.6 setuptools=39.1.0 pip=18.0 spyder
    conda activate test
    pip install --ignore-installed --upgrade https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.11.0-cp36-cp36m-linux_x86_64.whl
    pip install matplotlib
    spyder
    import tensorflow.contrib.training as training

BUT, everything works fine if i use console python:

    source activate test
    python
    import tensorflow.contrib.training as training

**Comment by SteScheller** [comment]
I also get this error while trying to use the **tf.contrib.gan.eval.sliced_wasserstein_distance** function.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/local/schellsn/Projects/edaml/code/trunk/ignored/wasserstein.py", line 53, in main
    init_emd_tensorflow(dummy.ravel().shape)
  File "/local/schellsn/Projects/edaml/code/trunk/ignored/wasserstein.py", line 27, in init_emd_tensorflow
    TF_EMD_DIST = tf.contrib.gan.eval.sliced_wasserstein_distance(
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/util/lazy_loader.py", line 53, in __getattr__
    module = self._load()
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/util/lazy_loader.py", line 42, in _load
    module = importlib.import_module(self.__name__)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.6/site-packages/tensorflow/contrib/__init__.py", line 49, in <module>
    from tensorflow.contrib import image
  File "/usr/local/lib/python3.6/site-packages/tensorflow/contrib/image/__init__.py", line 70, in <module>
    from tensorflow.contrib.image.python.ops.single_image_random_dot_stereograms import single_image_random_dot_stereograms
  File "/usr/local/lib/python3.6/site-packages/tensorflow/contrib/image/python/ops/single_image_random_dot_stereograms.py", line 27, in <module>
    "_single_image_random_dot_stereograms.so"))
  File "/usr/local/lib/python3.6/site-packages/tensorflow/contrib/util/loader.py", line 56, in load_op_library
    ret = load_library.load_op_library(path)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 73, in load_op_library
    exec(wrappers, module.__dict__)
  File "<string>", line 28
    def single_image_random_dot_stereograms(depth_values, hidden_surface_removal=True, convergence_dots_size=8, dots_per_inch=72, eye_separation=2,5, mu=0,333299994, normalize=True, normalize_max=-100, normalize_min=100, border_level=0, number_colors=256, output_image_shape=[1024, 768, 1], output_data_window=[1022, 757], name=None):
                                                                                                                                                   ^
SyntaxError: invalid syntax

```

I use a build-from-source version of Tensorflow v1.11.0 with CUDA 10.0 and cuDNN 7.3.1

**Comment by tensorflowbutler** [comment]
Nagging Assignee @suharshs: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @suharshs: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @suharshs: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by ymodak** [comment]
Apparently its an IDE related issue. Closing this issue since its a TF related bug/feature request. Feel free to reopen this issue if the problem still persists by providing additional information.
@SteScheller Please open a new issue to report your problem and provide all the information asked by the template. Thanks!
