### ISSUE TITLE
CUDA 10 tensorflow installation

### ISSUE THREAD

**Issue by Ayshine** [tensorflow/tensorflow#22743]
Hi,
I have NVDIA gtx 1080 and succesfully installed CUDA 10. I am having the following error.
Tensorflow installation does n ot warn me with anything but trying to import tensorflow I am getting the folllowing error.

`Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "/home/ayshine/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/ayshine/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/ayshine/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/ayshine/anaconda3/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/home/ayshine/anaconda3/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ayshine/anaconda3/lib/python3.6/site-packages/tensorflow/__init__.py", line 22, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/ayshine/anaconda3/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/ayshine/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/ayshine/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/ayshine/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/ayshine/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/ayshine/anaconda3/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/home/ayshine/anaconda3/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
>>> 
`

**Comment by samikama** [comment]
@Ayshine, you need to build from sources to use cuda 10. If you want to use pip installation, you need to have cuda9.0 and cudnn7 installed. Please see installation instructions

**Comment by Ayshine** [comment]
Thanks, @joseortiz3. Trying to follow through your solution now. I have a little different configuration so I hope this would also work for me. I will get back here and update the issue after I completed my process. 

**~$ python --version**
Python 3.6.5 :: Anaconda, Inc.
**~$ nvcc --version**
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Nov__3_21:07:56_CDT_2017
Cuda compilation tools, release 9.1, V9.1.85
**~$ cat /usr/local/cuda/version.txt**
CUDA Version 10.0.130

**Comment by Ayshine** [comment]
ok wh'le runn'ng basel got this 

ayshine@ayshine:~/tensorflow$ ./configure
/home/ayshine/bin/bazel: line 88: /home/ayshine/.bazel/bin/bazel-real: cannot execute binary file: Exec format error
/home/ayshine/bin/bazel: line 88: /home/ayshine/.bazel/bin/bazel-real: Success
Traceback (most recent call last):
  File "./configure.py", line 1592, in <module>
    main()
  File "./configure.py", line 1458, in main
    check_bazel_version('0.15.0')
  File "./configure.py", line 450, in check_bazel_version
    curr_version = run_shell(['bazel', '--batch', '--bazelrc=/dev/null', 'version'])
  File "./configure.py", line 141, in run_shell
    output = subprocess.check_output(cmd)
  File "/home/ayshine/anaconda3/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/home/ayshine/anaconda3/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['bazel', '--batch', '--bazelrc=/dev/null', 'version']' returned non-zero exit status 1.

**Comment by Ayshine** [comment]
@samikama @joseortiz3 thanks for the help. I am going to downgrade from CUDA 10 to CUDA 9. Some other libraries I want to install does not have CUDA 10 version. But, I will keep in mind to come back installing tensorflow on CUDA 10 and make it work :)
