### ISSUE TITLE
Udacity assignment 4 run time error

### ISSUE THREAD

**Issue by omidb** [tensorflow/tensorflow#2277]
Hi, Thanks for the tutorials. I was able to run everything until now. I'm trying to run assignment 4 and in last step in the following part, I get exception which is related to "session" and its graph! I haven't change anything, I'm just running the code:

```python
num_steps = 1001

with tf.Session(graph=graph) as session:
  tf.initialize_all_variables().run()
  print('Initialized')
  for step in range(num_steps):
    offset = (step * batch_size) % (train_labels.shape[0] - batch_size)
    batch_data = train_dataset[offset:(offset + batch_size), :, :, :]
    batch_labels = train_labels[offset:(offset + batch_size), :]
    feed_dict = {tf_train_dataset : batch_data, tf_train_labels : batch_labels}
    _, l, predictions = session.run(
      [optimizer, loss, train_prediction], feed_dict=feed_dict)
    if (step % 50 == 0):
      print('Minibatch loss at step %d: %f' % (step, l))
      print('Minibatch accuracy: %.1f%%' % accuracy(predictions, batch_labels))
      print('Validation accuracy: %.1f%%' % accuracy(
        valid_prediction.eval(), valid_labels))
  print('Test accuracy: %.1f%%' % accuracy(test_prediction.eval(), test_labels))
```

and the error messages are:

```
Initialized
Minibatch loss at step 0: 3.362968
Minibatch accuracy: 6.2%

InternalErrorTraceback (most recent call last)
<ipython-input-23-c56b394d9d7c> in <module>()
     15       print('Minibatch accuracy: %.1f%%' % accuracy(predictions, batch_labels))
     16       print('Validation accuracy: %.1f%%' % accuracy(
---> 17         valid_prediction.eval(), valid_labels))
     18   print('Test accuracy: %.1f%%' % accuracy(test_prediction.eval(), test_labels))

/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.pyc in eval(self, feed_dict, session)
    500 
    501     """
--> 502     return _eval_using_default_session(self, feed_dict, self.graph, session)
    503 
    504 

/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.pyc in _eval_using_default_session(tensors, feed_dict, graph, session)
   3346                        "the tensor's graph is different from the session's "
   3347                        "graph.")
-> 3348   return session.run(tensors, feed_dict)
   3349 
   3350 

/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.pyc in run(self, fetches, feed_dict, options, run_metadata)
    341     try:
    342       result = self._run(None, fetches, feed_dict, options_ptr,
--> 343                          run_metadata_ptr)
    344       if run_metadata:
    345         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.pyc in _run(self, handle, fetches, feed_dict, options, run_metadata)
    565     try:
    566       results = self._do_run(handle, target_list, unique_fetches,
--> 567                              feed_dict_string, options, run_metadata)
    568     finally:
    569       # The movers are no longer used. Delete them.

/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.pyc in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
    638     if handle is None:
    639       return self._do_call(_run_fn, self._session, feed_dict, fetch_list,
--> 640                            target_list, options, run_metadata)
    641     else:
    642       return self._do_call(_prun_fn, self._session, handle, feed_dict,

/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.pyc in _do_call(self, fn, *args)
    660       # pylint: disable=protected-access
    661       raise errors._make_specific_exception(node_def, op, error_message,
--> 662                                             e.code)
    663       # pylint: enable=protected-access
    664 

InternalError: Dst tensor is not initialized.
	 [[Node: Const = Const[dtype=DT_FLOAT, value=Tensor<type: float shape: [10000,28,28,1] values: -0.45294118 0.029411765 0.40588236...>, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
Caused by op u'Const', defined at:
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/ipykernel/__main__.py", line 3, in <module>
    app.launch_new_instance()
  File "/usr/local/lib/python2.7/dist-packages/traitlets/config/application.py", line 596, in launch_instance
    app.start()
  File "/usr/local/lib/python2.7/dist-packages/ipykernel/kernelapp.py", line 442, in start
    ioloop.IOLoop.instance().start()
  File "/usr/lib/python2.7/dist-packages/zmq/eventloop/ioloop.py", line 160, in start
    super(ZMQIOLoop, self).start()
  File "/usr/local/lib/python2.7/dist-packages/tornado/ioloop.py", line 883, in start
    handler_func(fd_obj, events)
  File "/usr/local/lib/python2.7/dist-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 433, in _handle_events
    self._handle_recv()
  File "/usr/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 465, in _handle_recv
    self._run_callback(callback, msg)
  File "/usr/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 407, in _run_callback
    callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/ipykernel/kernelbase.py", line 276, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/usr/local/lib/python2.7/dist-packages/ipykernel/kernelbase.py", line 228, in dispatch_shell
    handler(stream, idents, msg)
  File "/usr/local/lib/python2.7/dist-packages/ipykernel/kernelbase.py", line 391, in execute_request
    user_expressions, allow_stdin)
  File "/usr/local/lib/python2.7/dist-packages/ipykernel/ipkernel.py", line 199, in do_execute
    shell.run_cell(code, store_history=store_history, silent=silent)
  File "/usr/local/lib/python2.7/dist-packages/IPython/core/interactiveshell.py", line 2723, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/usr/local/lib/python2.7/dist-packages/IPython/core/interactiveshell.py", line 2825, in run_ast_nodes
    if self.run_code(code, result):
  File "/usr/local/lib/python2.7/dist-packages/IPython/core/interactiveshell.py", line 2885, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-18-aedb1ef46e04>", line 14, in <module>
    tf_valid_dataset = tf.constant(valid_dataset)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/constant_op.py", line 166, in constant
    attrs={"value": tensor_value, "dtype": dtype_value}, name=name).outputs[0]
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2154, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1154, in __init__
    self._traceback = _extract_stack()
```

Is there anything I have to do ? I can see the exception comes from `.eval()` function. I guess @vincentvanhoucke might be right person to ping. 

Thanks

**Comment by vincentvanhoucke** [comment]
I will attempt to reproduce on Monday. However, this specific error is typically TensorFlow's oh-so-cryptic way of saying it's run out of memory. Can that be the case here? Can you also tell me what tf.__version__ this is?

**Comment by omidb** [comment]
Thanks, here are the information you asked for:

```
ubuntu@ip-10-197-185-133:~$ free -m
             total       used       free     shared    buffers     cached
Mem:         15039       5314       9725         66         36       1109
-/+ buffers/cache:       4169      10870
Swap:            0          0          0
ubuntu@ip-10-197-185-133:~$ pip show tensorflow
---
Metadata-Version: 2.0
Name: tensorflow
Version: 0.8.0

```

**Comment by vincentvanhoucke** [comment]
I can't reproduce this at the head of the tree. It seems to strongly point at a memory issue.
If you reduce the size of the test and validation sets (which are kept in memory), does it start working?

**Comment by Crusty82** [comment]
I have just received a very similar error on Assignment 3, after copying over an existing and working movel from Assignment 2. I restarted my colab kernel and things worked fine afterwards.

**Comment by brett--anderson** [comment]
I'm seeing this error on assignment 4 when running on the GPU. If I switch back to CPU it completes successfully. Any tips on how to tweak this so I can run it on the GPU? (GTX 1070)
