### ISSUE TITLE
Error in importing tensorflow

### ISSUE THREAD

**Issue by Dudu197** [tensorflow/tensorflow#22823]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10 Home
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: N/A
- **TensorFlow installed from (source or binary)**: pip install tf-nightly-gpu
- **TensorFlow version (use command below)**: Can't see (error while importing)
- **Python version**: 3.6.0
- **Bazel version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: Cuda 9.1; cuDNN 7.2.1
- **GPU model and memory**: GTX 1060 6Gb
- **Exact command to reproduce**: import tensorflow as tf

### Describe the problem
Error while importing tensorflow.
I have successfully installed via pip, but while I'm trying to import I get the log listed error.
Unfortunately, the error dosen't describe which DLL is missing, and all tickets I've seen doesn't solved my problem.

### Source code / logs

Python 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "D:\Program Files\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "D:\Program Files\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "D:\Program Files\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "D:\Program Files\Python36\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "D:\Program Files\Python36\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Program Files\Python36\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "D:\Program Files\Python36\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "D:\Program Files\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "D:\Program Files\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "D:\Program Files\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "D:\Program Files\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "D:\Program Files\Python36\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "D:\Program Files\Python36\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Bazel version
Mobile device

**Comment by Dudu197** [comment]
Updated as requested.

**Comment by ymodak** [comment]
I suspect you are using incorrect cuDNN version for Windows compatibility. Can you please try with [cuDNN  7.1.4](https://anaconda.org/anaconda/cudnn/7.1.4/download/win-64/cudnn-7.1.4-cuda9.0_0.tar.bz2).

**Comment by Dudu197** [comment]
I still got the same error.

But, reading the test bat it raised me one question, am I missing any env path?
I have created the LIBRARY_INC, LIBRARY_LIB and LIBRARY_BIN paths, but I still got the same error.

Is there any list about the environment variables I should have?

Thanks.

**Comment by gunan** [comment]
There are two potential issues.
First, we need to check your CPU model, does your CPU support AVX instruction sets?
Next, MSVC 2015 redistributable update 3. It is listed here under windows:
https://www.tensorflow.org/install/pip

**Comment by Dudu197** [comment]
My current CPU supports AVX (I7 7700HQ), and tensorflow on CPU installs and runs fine.
MSVC 2015 is also installed and working (since I've compiled dlib with GPU support).

By reading https://www.tensorflow.org/install/gpu, the "Windows Setup" part defined the path as v9.0, but mine is v9.1.
Is the tensorflow expecting the v9.0?
My path var is setted to v9.1.

Thanks.

**Comment by Dudu197** [comment]
It worked!
**After installing the CUDA 9.0 (instead of 9.1) I was able to successfully import and print the current version of tensorflow-gpu.**

I guess I'll have no more trouble in using tensorflow.

Thanks for all support and help,
Carlos.

**Comment by gargisri68** [comment]
![image](https://user-images.githubusercontent.com/22957479/53956677-4a12d900-4102-11e9-8c0a-b062efa3d363.png)


I cannot import tensorflow.

**Comment by RostyxCZ** [comment]
Hi, please help me, I am getting this - same as person above. I think I did whole instalation properly, I tried it for 3 times but it always result in same error. I am using Python 3.7.2, anaconda, tensorflow-gpu 1.13.1, CUDA 10.1, cuDNN 7.5.

**Comment by gargisri68** [comment]
Use cuda version 9 and cudnn 6.4.7

**Comment by gargisri68** [comment]
If required downgrade your python to 3.6 and tensorflow-gpu to 1.12 or
lesser.

**Comment by RostyxCZ** [comment]
So I reinstalled CUDA to version 9.2, downgraded cudnn and also python to 3.6 and tf-gpu to 1.12 and I am still getting the same error as I did before. Do you guys have any other advices? Btw, I am running on GTX 1050 ti.

**Comment by RostyxCZ** [comment]
Right now I am reinstalling CUDA to ver 9.0. I will give feedback after the instalation done.

**Comment by RostyxCZ** [comment]
[SOLVED] Okay, so my problem is solved. Actually successfuly running on :
 CUDA 9.0, cuDNN 7.3.1,  python 3.6.0 (Anaconda), tensorflow 1.12 with my GPU Nvidia GTX 1050 Ti.

Thanks alot for your help and this tread in general 💯

**Comment by Bocul16** [comment]
anybody can help me 
im running on: PyCharm 2019 1.3, Anaconda3 2019.03, Tensorflow 1.14.0 GPU Nvidia GTX 950 CUDA 10.0 cuDNN 7.1.4

C:\Users\bonix\Anaconda3\envs\tensor\pythonw.exe C:/Users/bonix/PycharmProjects/TensorPye/testing.py
Traceback (most recent call last):
  File "C:\Users\bonix\Anaconda3\envs\tensor\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\bonix\Anaconda3\envs\tensor\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\bonix\Anaconda3\envs\tensor\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\bonix\Anaconda3\envs\tensor\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\bonix\Anaconda3\envs\tensor\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/bonix/PycharmProjects/TensorPye/testing.py", line 1, in <module>
    import tensorflow
  File "C:\Users\bonix\Anaconda3\envs\tensor\lib\site-packages\tensorflow\__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\bonix\Anaconda3\envs\tensor\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\bonix\Anaconda3\envs\tensor\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\bonix\Anaconda3\envs\tensor\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\bonix\Anaconda3\envs\tensor\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\bonix\Anaconda3\envs\tensor\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\bonix\Anaconda3\envs\tensor\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\bonix\Anaconda3\envs\tensor\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

Process finished with exit code 1

**Comment by Dudu197** [comment]
@Bocul16 try using CUDA 9.0
