### ISSUE TITLE
TensorFlow 1.11.0 fails on aarch64 platform

### ISSUE THREAD

**Issue by bellycat77** [tensorflow/tensorflow#22834]
Building TensorFlow 1.11.0 from source fails on aarch64 platform
Ubuntu 16.04.5 LTS (GNU/Linux 4.4.77 aarch64)

------------------------

### System information
- **Have I written custom code**: N/A (a build problem)
- **OS Platform and Distribution**: Ubuntu 16.04.5 LTS (GNU/Linux 4.4.77 aarch64)
- **Mobile device**: N/A
- **TensorFlow installed from**: source
- **TensorFlow version**: 1.11
- **Python version**: 2.7.12
- **Bazel version**: 0.16.1
- **GCC/Compiler version**: gcc (Ubuntu/Linaro 7.3.0-21ubuntu1~16.04) 7.3.0
- **CUDA/cuDNN version**: Mobile device
- **GPU model and memory**: N/A
- **Exact command to reproduce**: Install dependencies and build via [CK-TensorFlow](https://github.com/ctuning/ck-tensorflow):

```bash
$ sudo apt install liblapack-dev libatlas-dev
$ sudo pip install enum34 mock pillow wheel absl-py scipy ck
$ ck pull repo:ck-tensorflow
$ ck install ck-env:package:tool-bazel-0.16.1-linux
$ ck install package:lib-tensorflow-1.11.0-src-cpu --env.CK_HOST_CPU_NUMBER_OF_PROCESSORS=1
```
**NB**: Restricting the number of building processes to 1 is necessary to prevent running out of memory on the platform with 4 GB and no swap enabled or similar.
### Describe the problem
Building TensorFlow 1.11.0 from source fails on aarch64 platform. Similar instruction for x86_64 platform works well:
```
$ ck install package:lib-tensorflow-1.7.0-src-cpu --env.CK_HOST_CPU_NUMBER_OF_PROCESSORS=1
```

### Logs:
```
ERROR: /home/ivan/CK-TOOLS/lib-tensorflow-src-cpu-1.11.0-compiler.python-2.7.12-linux-64/src/tensorflow/BUILD:592:1: Executing genrule //tensorflow:tensorflow_python_api_gen failed (Exit 1)
Traceback (most recent call last):
  File "/home/ivan/.cache/bazel/_bazel_ivan/6cdff2b5ba48d82461ef4df735b65391/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api.runfiles/org_tensorflow/tensorflow/python/tools/api/generator/create_python_api.py", line 27, in <module>
    from tensorflow.python.tools.api.generator import doc_srcs
  File "/home/ivan/.cache/bazel/_bazel_ivan/6cdff2b5ba48d82461ef4df735b65391/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 81, in <module>
    from tensorflow.python import keras
  File "/home/ivan/.cache/bazel/_bazel_ivan/6cdff2b5ba48d82461ef4df735b65391/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api.runfiles/org_tensorflow/tensorflow/python/keras/__init__.py", line 25, in <module>
    from tensorflow.python.keras import applications
  File "/home/ivan/.cache/bazel/_bazel_ivan/6cdff2b5ba48d82461ef4df735b65391/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api.runfiles/org_tensorflow/tensorflow/python/keras/applications/__init__.py", line 22, in <module>
    import keras_applications
ImportError: No module named keras_applications
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 29255.108s, Critical Path: 262.73s
INFO: 5693 processes: 5693 local.
FAILED: Build did NOT complete successfully
```

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Mobile device

**Comment by bellycat77** [comment]
Thanks. Mobile device: N/A . Issue is updated too.

**Comment by freedomtan** [comment]
install keras_applications and other pip wheels should help, see #21518

**Comment by bellycat77** [comment]
It helps. After lowering  versions of keras_applications and keras_preprocessing TF was built.
But it not works without additional manual installation of python libraries: gast, astor and termcolor.
