### ISSUE TITLE
IndexedSlices problem on porting ptb_word_lm.py to multi-GPU-towers

### ISSUE THREAD

**Issue by smartcat2010** [tensorflow/tensorflow#2283]
I try to port RNN model in [ptb_word_lm.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/models/rnn/ptb/ptb_word_lm.py) to multi-GPU cards. I follow the multi-tower style in [cifar10_multi_gpu_train.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/models/image/cifar10/cifar10_multi_gpu_train.py) 
However, I found the "grads" returned by `tf.clip_by_global_norm(tf.gradients(cost, tvars), config.max_grad_norm)` is not list of Tensor type. It is a list of type `tensorflow.python.framework.ops.IndexedSlices`.  Now I need to sum & average the lists of "grads" returned by multiple GPU towers into one list of IndexedSlices or Tensor, in order to pass it into `self._train_op = optimizer.apply_gradients(zip(grads, tvars))`
 I've tried the `tf.convert_to_tensor` to conver IndexedSlices to Tensor, but it failed with the following errors:

  File "ptb_word_lm.py", line 328, in <module>
    tf.app.run()
  File "/usr/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "ptb_word_lm.py", line 305, in main
    m = PTBModel(is_training=True, config=config)
  File "ptb_word_lm.py", line 152, in \_\_init\_\_
    grads_0_tensor = tf.convert_to_tensor(grads[0])
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 566, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/gradients.py", line 77, in _IndexedSlicesToTensor
    % str(value))
ValueError: Tensor conversion requested for IndexedSlices without dense_shape: IndexedSlices(indices=Tensor("model/gradients/concat_1:0", shape=(400,), dtype=int32), values=Tensor("model/clip_by_global_norm/model/clip_by_global_norm/_0:0", shape=(?, 200), dtype=float32))

Is it a bug?
How could I reduce_mean these IndexedSlices(reduce_mean seems only accept "Tensor" as input)? Or is there any existing code that parallelize RNN in multi-GPU-towers style?

Thanks a lot in advance!

**Comment by girving** [comment]
@smartcat2010: Could you try to isolate where the problematic `IndexedSlices` object without a dense shape is coming from?  It's likely that whoever is creating that object needs to attach a shape at creation time.

**Comment by smartcat2010** [comment]
Hi, girving:
The problematic IndexedSlices comes from "tf.gradients(cost, tvars)". Because if I remove the wrapper "tf.clip_by_global_norm" and leave "grads, _ = tf.gradients(cost, tvars)" alone, the same error shows again.

**Comment by girving** [comment]
@smartcat2010: We need more information than that it comes from somewhere inside `tf.gradients`, which contains something like half of TensorFlow.  The best way would to be either find the specific line that constructs the `IndexedSlices` without specifying a `dense_shape`, or to produce a minimized test case.  Here are some ways to go about the former:

1. Add an assert in the constructor of `IndexedSlices` that `dense_shape` is specified.  If you're lucky, this will break on the problematic line.

2. In the constructor of `IndexedSlices`, print `id(self)` if `dense_shape` is not specified, and compare it to the `id` of the problematic `IndexedSlices` you're getting out.

**Comment by girving** [comment]
Closing for now.  @smartcat2010: Please comment if you have more information and I'll reopen.

**Comment by lijiajia** [comment]
I have the same problem, my code is as following. Please help me.

tower_outputs = []
    tower_loss = []
    tower_grad_norms = []
    tower_clipped_grads = []

    for i in xrange(1, 2):
      with tf.device('/gpu:%d' % i):
        # Training outputs and losses.
        if forward_only:
          outputs, losses = tf.nn.seq2seq.model_with_buckets(
              encoder_inputs_split[i], decoder_inputs_split[i], targets_split[i],
              target_weights_split[i], buckets, lambda x, y: seq2seq_f(x, y, True),
              softmax_loss_function=softmax_loss_function)
          # If we use output projection, we need to project outputs for decoding.
          if output_projection is not None:
            for b in xrange(len(buckets)):
              outputs[b] = [
                  tf.matmul(output, output_projection[0]) + output_projection[1]
                  for output in outputs[b]
              ]
        else:
          outputs, losses = tf.nn.seq2seq.model_with_buckets(
              encoder_inputs_split[i], decoder_inputs_split[i], targets_split[i],
              target_weights_split[i], buckets,
              lambda x, y: seq2seq_f(x, y, False),
              softmax_loss_function=softmax_loss_function)

        tower_outputs.append(outputs)
        tower_loss.append(losses)

        # Gradients and SGD update operation for training the model.
        params = tf.trainable_variables()
        print(params)
        tmp_norms = []
        tmp_clip_grad = []
if not forward_only:
          for b in xrange(len(buckets)):
            gradients = tf.gradients(losses[b], params)
            clipped_gradients, norm = tf.clip_by_global_norm(gradients, max_gradient_norm)
            tmp_norms.append(norm)
            tmp_clip_grad.append(clipped_gradients)
          tower_grad_norms.append(tmp_norms)
          tower_clipped_grads.append(tmp_clip_grad)
        print('gpu:%d' % i)
        tf.get_variable_scope().reuse_variables()

    self.outputs = tf.concat(1, tower_outputs)
    self.losses = tf.reduce_mean(tower_loss, 0)

    if not forward_only:
      self.gradient_norms = tf.reduce_mean(tower_grad_norms, 0)
      gradients = self.average_gradients(tower_clipped_grads)
      self.updates = []
      for b in xrange(len(buckets)):
        clipped_gradients = gradients[b]
        self.updates.append(opt.apply_gradients(
            zip(clipped_gradients, params), global_step=self.global_step))

    self.saver = tf.train.Saver(tf.all_variables())

  def average_gradients(self, tower_grads):
    average_grads = []
    for tower_grad in zip(*tower_grads):
      # Average over the 'tower' dimension.
      grad = tf.reduce_mean(tower_grad, 1)

      # Keep in mind that the Variables are redundant because they are shared across towers. So .. we will just return the first tower's pointer to the Variable.
      average_grads.append(grad)
    return average_grads

**Comment by girving** [comment]
@lijiajia Can you (1) include your error message and (2) isolate which IndexedSlices is responsible as I requested of @smartcat2010?

**Comment by lijiajia** [comment]
The error message is as following. The problematic IndexedSlices comes from "gradients = tf.gradients(losses[b], params)". 

The gradients is consists of:
<class 'tensorflow.python.framework.ops.Tensor'>
<class 'tensorflow.python.framework.ops.IndexedSlices'>
<class 'tensorflow.python.framework.ops.IndexedSlices'>
<class 'tensorflow.python.framework.ops.Tensor'>
<class 'tensorflow.python.framework.ops.Tensor'>
<class 'tensorflow.python.framework.ops.Tensor'>
<class 'tensorflow.python.framework.ops.Tensor'>
<class 'tensorflow.python.framework.ops.IndexedSlices'>
<class 'tensorflow.python.framework.ops.Tensor'>
<class 'tensorflow.python.framework.ops.Tensor'>
<class 'tensorflow.python.framework.ops.Tensor'>
<class 'tensorflow.python.framework.ops.Tensor'>
<class 'tensorflow.python.framework.ops.Tensor'>
<class 'tensorflow.python.framework.ops.Tensor'>
<class 'tensorflow.python.framework.ops.Tensor'>
<class 'tensorflow.python.framework.ops.Tensor'>
<class 'tensorflow.python.framework.ops.Tensor'>
<class 'tensorflow.python.framework.ops.Tensor'>
<class 'tensorflow.python.framework.ops.Tensor'>
<class 'tensorflow.python.framework.ops.Tensor'>


Traceback (most recent call last):
  File "train.py", line 277, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "train.py", line 274, in main
    train()
  File "train.py", line 168, in train
    model = create_model(sess, False)
  File "train.py", line 142, in create_model
    forward_only=forward_only, gpus=FLAGS.gpus)
  File "/root/dialog_sms/seq2seq_model.py", line 200, in __init__
    gradients = self.average_gradients(tower_clipped_grads)
  File "/root/dialog_sms/seq2seq_model.py", line 213, in average_gradients
    grad = tf.reduce_mean(tower_grad, 1)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/math_ops.py", line 1089, in reduce_mean
    keep_dims, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_math_ops.py", line 1345, in _mean
    keep_dims=keep_dims, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 454, in apply_op
    as_ref=input_arg.is_ref)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 621, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 630, in _autopacking_conversion_function
    return _autopacking_helper(v, inferred_dtype, name or "packed")
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 576, in _autopacking_helper
    converted_elem = _autopacking_helper(elem, dtype, str(i))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 592, in _autopacking_helper
    constant_op.constant(elem, dtype=dtype, name=str(i)))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/constant_op.py", line 163, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_util.py", line 353, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_util.py", line 290, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected float32, got <tensorflow.python.framework.ops.IndexedSlices object at 0x7f2ab403bfd0> of type 'IndexedSlices' instead.

**Comment by girving** [comment]
Copying my comment above for convenience:

@lijiajia We need more information than that it comes from somewhere inside `tf.gradients`, which contains something like half of TensorFlow. The best way would to be either find the specific line that constructs the `IndexedSlices` without specifying a `dense_shape`, or to produce a minimized test case. Here are some ways to go about the former:

1. Add an assert in the constructor of `IndexedSlices` that `dense_shape` is specified. If you're lucky, this will break on the problematic line.

2. In the constructor of `IndexedSlices`, `print id(self)` if `dense_shape` is not specified, and compare it to the id of the problematic `IndexedSlices` you're getting out.

**Comment by drpngx** [comment]
Closing due to inactivity. Please re-open if you have more info.

**Comment by dngu7** [comment]
I ran into the same problem and the indexedslices are coming from the keras **Embedding** Layer based on my own model. Right now I'm minimizing them individually. Is there a way to reduce and average these for multi-gpu gradient descent.
