### ISSUE TITLE
import tensorflow failed, "ImportError: DLL load failed: The specified module could not be found"

### ISSUE THREAD

**Issue by willSapgreen** [tensorflow/tensorflow#22872]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10 Home
- **TensorFlow installed from (source or binary)**: binary ( pip install tensorflow-gpu )
- **TensorFlow version (use command below)**: 1.11.0
- **Python version**: python-3.5.4-amd64
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**: cuda_10.0.130_411.31_win10
- **GPU model and memory**: Nvidia Geforece GTX 1060 6G
- **Exact command to reproduce**: python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

### Describe the problem
Cannot import tensorflow successfully.
Try "visual studio 2015, Microsoft Visual C++ 2015 Redistributable Update 3" but the update in my laptop is newer than this, so I cannot install this update.

### Source code / logs
The error message after the command above
Traceback (most recent call last):
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Program Files\Python35\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Program Files\Python35\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\__init__.py", line 22, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Program Files\Python35\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Program Files\Python35\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

Please let me know if any question or suggestion.

**Comment by ymodak** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)

**Comment by ExiledMercenary** [comment]
Im getting the same error using cuda 9.0

**Comment by ExiledMercenary** [comment]
Using TensorFlow backend.
Traceback (most recent call last):
  File "C:\Users\aniag\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\aniag\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\aniag\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\aniag\AppData\Local\Programs\Python\Python36\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\aniag\AppData\Local\Programs\Python\Python36\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\D_CASE\task1\Untitled.py", line 7, in <module>
    import keras
  File "C:\Users\aniag\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\__init__.py", line 3, in <module>
    from . import utils
  File "C:\Users\aniag\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\utils\__init__.py", line 6, in <module>
    from . import conv_utils
  File "C:\Users\aniag\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\utils\conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "C:\Users\aniag\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\backend\__init__.py", line 89, in <module>
    from .tensorflow_backend import *
  File "C:\Users\aniag\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\backend\tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf
  File "C:\Users\aniag\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\__init__.py", line 22, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\aniag\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\aniag\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\aniag\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\aniag\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\aniag\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\aniag\AppData\Local\Programs\Python\Python36\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\aniag\AppData\Local\Programs\Python\Python36\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by ExiledMercenary** [comment]
The above is the error

**Comment by ymodak** [comment]
@ExiledMercenary Please open a new issue describing your problem and provide the system information. This will help us to focus on your issue explicitly.

**Comment by 57ar7up** [comment]
I just downgraded TensorFlow to 1.10.0 and it worked

pip install tensorflow-gpu==1.10.0

**Comment by thangduong** [comment]
same issue.  same resolution.  tensorflow 1.12 is broken.

**Comment by JanVanIm** [comment]
I tried the solution of @dwindy, the installation seemed to proceed well. But when I tried to confirm that Tensorflow GPU was installed it failed.
I then tried to re-run the same code `conda install -c aaronzs tensorflow-gpu` and the following message appears 

> Solving environment: failed
> 
> UnsatisfiableError: The following specifications were found to be in conflict:
>   - tensorflow-gpu
> Use "conda info <package>" to see the dependencies for each package.

**Comment by globefire** [comment]
> I just downgraded TensorFlow to 1.10.0 and it worked
> 
> `pip install tensorflow-gpu==1.10.0`

@57ar7up were you using cuda 10 ?

**Comment by lugq1990** [comment]
CUDA 9.0 with the same issue on windows, both TensorFlow 1.13 and 2.0-alpha. So I just use the previous version as 1.12 solved this problem.
`pip unistall tensorflow-gpu`
`pip install tensorflow-gpu==1.12.0`

**Comment by peyifyp** [comment]
hi, i have this error. How can i solve this problem?

Traceback (most recent call last):
  File "C:\Users\User\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\User\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\User\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\User\Anaconda3\envs\tensorflow1\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\User\Anaconda3\envs\tensorflow1\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "generate_tfrecord.py", line 17, in <module>
    import tensorflow as tf
  File "C:\Users\User\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\User\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\User\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\User\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\User\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\User\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\User\Anaconda3\envs\tensorflow1\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\User\Anaconda3\envs\tensorflow1\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by corleonechensiyu** [comment]
i have the same error .
but when i import torch first and then import tensorflow 
it works :0
@ymodak

**Comment by peyifyp** [comment]
Thanks for reply I will try it

**Comment by Sum-RED** [comment]
> I just downgraded TensorFlow to 1.10.0 and it worked
> 
> `pip install tensorflow-gpu==1.10.0`

Can confirm that this works for me too. Thanks a ton man.

BTW I'm using **CUDA 9.0** and as @57ar7up said, I downgraded my tensorflow-gpu version to **1.10**

**Comment by smer44** [comment]
Can someone help me, i v tryed combination of :
Cuda 9 , cudnn 7.4.1.5 , different tensofrlows 1.10 to latest,  (like in posts above), 
then cuda 10 with tensorflow 2 .0.0. alfa but no combination works for no reason!!!!!

 It is possible to get the **INFORMATIVE ERROR MESSAGE** from tensorflow that **EXACTLY** the problem is,

**Comment by yushuxin1** [comment]
> CUDA 9.0在Windows上具有相同的问题，TensorFlow 1.13和2.0-alpha。所以我只使用1.12以前的版本解决了这个问题。
> `pip unistall tensorflow-gpu`
> `pip install tensorflow-gpu==1.12.0`
AttributeError: module 'tensorflow._api.v1.compat' has no attribute 'v1'
