### ISSUE TITLE
Integrating imported graphs into Dataset pipelines

### ISSUE THREAD

**Issue by matthai** [tensorflow/tensorflow#22879]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Ubuntu 16.04
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
n/a
- **TensorFlow installed from (source or binary)**:
binary (pip)
- **TensorFlow version (use command below)**:
1.5.0
- **Python version**:
3.5.5
- **Bazel version (if compiling from source)**:
NA
- **GCC/Compiler version (if compiling from source)**:
NA
- **CUDA/cuDNN version**:
cuda 9.0/cudnn 7.0
- **GPU model and memory**:
gtx 1080, 12GB
- **Exact command to reproduce**

### Describe the problem
I'd like to build parts of my `dataset` by importing pre-existing graphs. It looks like a way to do this is to import the graph from within a `dataset.map` operation as in the source code below. But this approach fails with a placeholder-not-mapped error (please see below). I know, e.g., that it is possible to import and stick a graph _after_ the iterator at the end of the dataset. But I'd like to stick them _in_ the dataset pipeline. Is this currently infeasible using datasets, or am I doing something wrong?

### Source code
Here is my minimal source code. It works when `USE_GRAPH` is set to `False` and fails (see below for trace) when set to `True`:
```
import tensorflow as tf
USE_GRAPH = True
INT = tf.int64


def sq_fun(x):
    if USE_GRAPH:
        g = tf.Graph()
        with g.as_default() as g:
            d = tf.placeholder(INT, shape=(), name='d')
            _ = tf.pow(d, 2, name='e')
        xx = tf.import_graph_def(
            g.as_graph_def(),
            input_map={'d': x},
            return_elements=['e:0'])
    else:
        xx = tf.pow(x, 2, name='e')
    return xx


dataset = tf.data.Dataset.range(10)
dataset = dataset.map(sq_fun)
next_element = dataset.make_one_shot_iterator().get_next()

with tf.Session() as sess:
    for i in range(10):
        value = sess.run(next_element)
        print(value)
```

### Error trace
Here is the error trace when the above code is run as is (wiith `USE_GRAPH` set to `True`):

```
(tensorflow) matthai@matthai-z400:~/projects/w4ml/src/python/w4ml$ python test1.py 
/home/matthai/install/anaconda/anaconda3-4.4.0/envs/tensorflow/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2018-10-10 18:05:42.047846: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2
2018-10-10 18:05:42.177377: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:895] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-10-10 18:05:42.177855: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1105] Found device 0 with properties: 
name: TITAN X (Pascal) major: 6 minor: 1 memoryClockRate(GHz): 1.531
pciBusID: 0000:0f:00.0
totalMemory: 11.90GiB freeMemory: 7.23GiB
2018-10-10 18:05:42.177883: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1195] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: TITAN X (Pascal), pci bus id: 0000:0f:00.0, compute capability: 6.1)
2018-10-10 18:05:42.577441: W tensorflow/core/framework/op_kernel.cc:1198] Invalid argument: You must feed a value for placeholder tensor 'import/d' with dtype int64
	 [[Node: import/d = Placeholder[dtype=DT_INT64, shape=[]]()]]
Traceback (most recent call last):
  File "/home/matthai/install/anaconda/anaconda3-4.4.0/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1350, in _do_call
    return fn(*args)
  File "/home/matthai/install/anaconda/anaconda3-4.4.0/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1329, in _run_fn
    status, run_metadata)
  File "/home/matthai/install/anaconda/anaconda3-4.4.0/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'import/d' with dtype int64
	 [[Node: import/d = Placeholder[dtype=DT_INT64, shape=[]]()]]
	 [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[]], output_types=[DT_INT64], _device="/job:localhost/replica:0/task:0/device:CPU:0"](OneShotIterator)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test1.py", line 28, in <module>
    value = sess.run(next_element)
  File "/home/matthai/install/anaconda/anaconda3-4.4.0/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/home/matthai/install/anaconda/anaconda3-4.4.0/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1128, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/matthai/install/anaconda/anaconda3-4.4.0/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1344, in _do_run
    options, run_metadata)
  File "/home/matthai/install/anaconda/anaconda3-4.4.0/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1363, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'import/d' with dtype int64
	 [[Node: import/d = Placeholder[dtype=DT_INT64, shape=[]]()]]
	 [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[]], output_types=[DT_INT64], _device="/job:localhost/replica:0/task:0/device:CPU:0"](OneShotIterator)]]
```

**Comment by matthai** [comment]
Ah great, thanks! Will try.

**Comment by matthai** [comment]
@wt-huang , I tested with TF 1.10 and it indeed does work. Thanks for your quick response!

**Comment by wt-huang** [comment]
Glad that it worked.

**Comment by wt-huang** [comment]
Are all your questions answered?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
