### ISSUE TITLE
Strange issue converting Tensorflow model to TFLite using toco

### ISSUE THREAD

**Issue by josephn123** [tensorflow/tensorflow#22893]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04.5 LTS
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: N/A
- **TensorFlow installed from (source or binary)**: Binary
- **TensorFlow version (use command below)**: Tensorflow v1.9.0-rc2-5420-g411b9ba 1.11.0-rc1 
- **Python version**: 3.5.2
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:

I have a tensorflow model, in two formats, the first in a frozen graph definition (pb) file, and the second in a Keras model (h5) file.

Via pb file:
```
toco --graph_def_file=./model.pb --output_file=./model.tflite --inference_type=FLOAT --input_type=FLOAT --input_arrays=input_1 --output_arrays=out0 --allow_custom_operators
```
Yields:
```
2018-10-09 12:24:55.039391: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 5705 operators, 7732 arrays (0 quantized)
2018-10-09 12:24:55.664965: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 5705 operators, 7732 arrays (0 quantized)
2018-10-09 12:24:56.867861: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 1: 4908 operators, 9078 arrays (0 quantized)
2018-10-09 12:24:57.400037: F tensorflow/contrib/lite/toco/graph_transformations/propagate_fixed_sizes.cc:1442] Check failed: axis < input_shape.dimensions_count() (90746776 vs. 4)
Aborted (core dumped)'
None
```
Interestingly the 90746776 (axis) value in the error changes between successive calls

Via the h5 file
```
toco --keras_model_file=./model.h5 --output_file=./model.tflite --inference_type=FLOAT --input_type=FLOAT --input_arrays=input_1 --output_arrays=out0 --allow_custom_ops
```
Yields:
```
Traceback (most recent call last):
  File "/home/joseph/.local/bin/toco", line 11, in <module>
    sys.exit(main())
  File "/home/joseph/.local/lib/python3.5/site-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 412, in main
    app.run(main=run_main, argv=sys.argv[:1])
  File "/home/joseph/.local/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/home/joseph/.local/lib/python3.5/site-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 408, in run_main
    _convert_model(tflite_flags)
  File "/home/joseph/.local/lib/python3.5/site-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 100, in _convert_model
    converter = _get_toco_converter(flags)
  File "/home/joseph/.local/lib/python3.5/site-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 87, in _get_toco_converter
    return converter_fn(**converter_kwargs)
  File "/home/joseph/.local/lib/python3.5/site-packages/tensorflow/contrib/lite/python/lite.py", line 368, in from_keras_model_file
    keras_model = _keras.models.load_model(model_file)
  File "/home/joseph/.local/lib/python3.5/site-packages/tensorflow/python/keras/engine/saving.py", line 230, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/home/joseph/.local/lib/python3.5/site-packages/tensorflow/python/keras/engine/saving.py", line 310, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/home/joseph/.local/lib/python3.5/site-packages/tensorflow/python/keras/layers/serialization.py", line 64, in deserialize
    printable_module_name='layer')
  File "/home/joseph/.local/lib/python3.5/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 173, in deserialize_keras_object
    list(custom_objects.items())))
  File "/home/joseph/.local/lib/python3.5/site-packages/tensorflow/python/keras/engine/network.py", line 1298, in from_config
    process_layer(layer_data)
  File "/home/joseph/.local/lib/python3.5/site-packages/tensorflow/python/keras/engine/network.py", line 1284, in process_layer
    layer = deserialize_layer(layer_data, custom_objects=custom_objects)
  File "/home/joseph/.local/lib/python3.5/site-packages/tensorflow/python/keras/layers/serialization.py", line 64, in deserialize
    printable_module_name='layer')
  File "/home/joseph/.local/lib/python3.5/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 173, in deserialize_keras_object
    list(custom_objects.items())))
  File "/home/joseph/.local/lib/python3.5/site-packages/tensorflow/python/keras/engine/sequential.py", line 340, in from_config
    model.add(layer)
  File "/home/joseph/.local/lib/python3.5/site-packages/tensorflow/python/training/checkpointable/base.py", line 474, in _method_wrapper
    method(self, *args, **kwargs)
  File "/home/joseph/.local/lib/python3.5/site-packages/tensorflow/python/keras/engine/sequential.py", line 175, in add
    output_tensor = layer(self.outputs[0])
  File "/home/joseph/.local/lib/python3.5/site-packages/tensorflow/python/keras/engine/base_layer.py", line 746, in __call__
    self.build(input_shapes)
  File "/home/joseph/.local/lib/python3.5/site-packages/tensorflow/python/keras/layers/wrappers.py", line 213, in build
    self.layer.build(tuple(child_input_shape))
  File "/home/joseph/.local/lib/python3.5/site-packages/tensorflow/python/keras/layers/core.py", line 933, in build
    raise ValueError('The last dimension of the inputs to `Dense` '
ValueError: The last dimension of the inputs to `Dense` should be defined. Found `None`.
```

**Comment by ymodak** [comment]
Please go through the documentation [to convert tf model into tensorflow lite](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/lite/g3doc/tflite_convert/python_api.md#exporting-a-tfkeras-file-)  if you haven't already. 
In addition, can you please try tf-nightly and check if the issue still persists?

**Comment by josephn123** [comment]
Both links provided are broken

**Comment by ymodak** [comment]
I have updated the links now. Please fire them up.

**Comment by josephn123** [comment]
Thanks for your fast reply. I've pulled the latest revision from tensorflow master, built a new python pip package from source using [these instructions](https://www.tensorflow.org/install/source) and installed via pip using the built `whl` file. Still the same issue when trying:
```
import tensorflow as tf


converter = tf.contrib.lite.TFLiteConverter.from_keras_model_file("model.h5")
tflite_model = converter.convert()
open("converted_model.tflite", "wb").write(tflite_model)
```
Results in:

```
Traceback (most recent call last):
  File "convert.py", line 4, in <module>
    converter = tf.contrib.lite.TFLiteConverter.from_keras_model_file("model.h5")
  File "/home/joseph/.local/lib/python3.5/site-packages/tensorflow/contrib/lite/python/lite.py", line 368, in from_keras_model_file
    keras_model = _keras.models.load_model(model_file)
  File "/home/joseph/.local/lib/python3.5/site-packages/tensorflow/python/keras/engine/saving.py", line 230, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/home/joseph/.local/lib/python3.5/site-packages/tensorflow/python/keras/engine/saving.py", line 310, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/home/joseph/.local/lib/python3.5/site-packages/tensorflow/python/keras/layers/serialization.py", line 64, in deserialize
    printable_module_name='layer')
  File "/home/joseph/.local/lib/python3.5/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 173, in deserialize_keras_object
    list(custom_objects.items())))
  File "/home/joseph/.local/lib/python3.5/site-packages/tensorflow/python/keras/engine/network.py", line 1319, in from_config
    process_layer(layer_data)
  File "/home/joseph/.local/lib/python3.5/site-packages/tensorflow/python/keras/engine/network.py", line 1305, in process_layer
    layer = deserialize_layer(layer_data, custom_objects=custom_objects)
  File "/home/joseph/.local/lib/python3.5/site-packages/tensorflow/python/keras/layers/serialization.py", line 64, in deserialize
    printable_module_name='layer')
  File "/home/joseph/.local/lib/python3.5/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 173, in deserialize_keras_object
    list(custom_objects.items())))
  File "/home/joseph/.local/lib/python3.5/site-packages/tensorflow/python/keras/engine/sequential.py", line 340, in from_config
    model.add(layer)
  File "/home/joseph/.local/lib/python3.5/site-packages/tensorflow/python/training/checkpointable/base.py", line 474, in _method_wrapper
    method(self, *args, **kwargs)
  File "/home/joseph/.local/lib/python3.5/site-packages/tensorflow/python/keras/engine/sequential.py", line 175, in add
    output_tensor = layer(self.outputs[0])
  File "/home/joseph/.local/lib/python3.5/site-packages/tensorflow/python/keras/engine/base_layer.py", line 746, in __call__
    self.build(input_shapes)
  File "/home/joseph/.local/lib/python3.5/site-packages/tensorflow/python/keras/layers/wrappers.py", line 214, in build
    self.layer.build(tuple(child_input_shape))
  File "/home/joseph/.local/lib/python3.5/site-packages/tensorflow/python/keras/layers/core.py", line 933, in build
    raise ValueError('The last dimension of the inputs to `Dense` '
ValueError: The last dimension of the inputs to `Dense` should be defined. Found `None`.
```

**Comment by tensorflowbutler** [comment]
Nagging Assignee @gargn: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by zhang-jian** [comment]
Sorry for posting on a closed issue.

@josephn123 , I am have the exact issue, just wondering how did you solved this? Thank

**Comment by gashmish** [comment]
This error still appears when converting any Keras model which has custom layer
On TF 1.13

**Comment by Ir0098** [comment]
> 
> 
> This error still appears when converting any Keras model which has custom layer
> On TF 1.13

The same issue, did you find a solution?

**Comment by sheirving** [comment]
same problem with the first in a frozen graph definition (pb) file, did you find a solution? Thankyou

**Comment by gargn** [comment]
Starting 1.14, [`TFLiteConverter.from_keras_model_file`](https://www.tensorflow.org/api_docs/python/tf/lite/TFLiteConverter#from_keras_model_file) takes in the argument `custom_objects` which is passed directly into the Keras loading function. The logic should look something like the following:

```
converter = tf.lite.TFLiteConverter.from_keras_model_file(
   keras_model_file,
   custom_objects={'Dense': Dense})
```

If you need to use 1.13 then you can load the Keras model yourself and use `TFLiteConverter.from_session` with logic similar to the following:

```
tf.keras.backend.set_learning_phase(False)
keras_model = tf.keras.models.load_model(model_file, custom_objects)
sess = tf.keras.backend.get_session()
converter = tf.lite.TFLiteConverter.from_session(sess, keras_model.inputs, keras_model.outputs)
```
