### ISSUE TITLE
Error reported to Coordinator: libnccl.so.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by xiaohu2015** [tensorflow/tensorflow#22899]
When I use tf-version 1.11, I found above error for distribute strategy on multi-gpus

**Comment by xiaohu2015** [comment]
Calling model_fn.
INFO:tensorflow:batch_all_reduce invoked for batches size = 158 with algorithm = nccl, num_packs = 1, agg_small_grads_max_bytes = 0 and agg_small_grads_max_group = 10
INFO:tensorflow:Error reported to Coordinator: libnccl.so.2: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/root/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/coordinator.py", line 297, in stop_on_exception
    yield
  File "/root/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/distribute/python/mirrored_strategy.py", line 177, in _call_for_each_tower
    **merge_kwargs)
  File "/root/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/optimizer.py", line 659, in _distributed_apply
    variable_scope.VariableAggregation.SUM, grads_and_vars)
  File "/root/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/distribute.py", line 773, in batch_reduce
    return self._batch_reduce(aggregation, value_destination_pairs)
  File "/root/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/distribute/python/mirrored_strategy.py", line 620, in _batch_reduce
    value_destination_pairs)
  File "/root/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/distribute/python/cross_tower_ops.py", line 243, in batch_reduce
    return self._batch_reduce(aggregation, value_destination_pairs)
  File "/root/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/distribute/python/cross_tower_ops.py", line 597, in _batch_reduce
    [v[0] for v in value_destination_pairs])
  File "/root/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/distribute/python/cross_tower_ops.py", line 631, in _batch_all_reduce
    device_grad_packs)
  File "/root/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/distribute/python/cross_tower_utils.py", line 41, in aggregate_gradients_using_nccl
    agg_grads = nccl.all_sum(single_grads)
  File "/root/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/nccl/python/ops/nccl_ops.py", line 49, in all_sum
    return _apply_all_reduce('sum', tensors)
  File "/root/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/nccl/python/ops/nccl_ops.py", line 217, in _apply_all_reduce
    _validate_and_load_nccl_so()
  File "/root/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/nccl/python/ops/nccl_ops.py", line 288, in _validate_and_load_nccl_so
    _maybe_load_nccl_ops_so()
  File "/root/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/nccl/python/ops/nccl_ops.py", line 274, in _maybe_load_nccl_ops_so
    resource_loader.get_path_to_datafile('_nccl_ops.so'))
  File "/root/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/util/loader.py", line 56, in load_op_library
    ret = load_library.load_op_library(path)
  File "/root/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
NotFoundError: libnccl.so.2: cannot open shared object file: No such file or directory

**Comment by wt-huang** [comment]
@xiaohu2015 Did you install NCCL2? Please provide more information by filling out the issue template.

**System information**

OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
TensorFlow installed from (source or binary): 
TensorFlow version: 
Python version: 
Installed using virtualenv? pip? conda?:
Bazel version (if compiling from source): 
GCC/Compiler version (if compiling from source): 
CUDA/cuDNN version: 
GPU model and memory:
Describe the problem

Provide the exact sequence of commands / steps that you executed before running into the problem

**Comment by huizhang0110** [comment]
I meet the same problem as you when I use the distribute.MirroredStrategy
```
tensorflow.python.framework.errors_impl.NotFoundError: libnccl.so.2: cannot open shared object file: No such file or directory
```

**Comment by huizhang0110** [comment]
You should install NVIDIA Collective Communications Library (NCCL) first for contribution training.
https://developer.nvidia.com/nccl/nccl-download

**Comment by xiaohu2015** [comment]
@huizhang0110 thx, I will try

**Comment by xiaohu2015** [comment]
@wt-huang thx, I got.

**Comment by wt-huang** [comment]
Closing as this is resolved, free to reopen if problem persists
