### ISSUE TITLE
Invalid loop strucure

### ISSUE THREAD

**Issue by ankitesh97** [tensorflow/tensorflow#22936]
I had converted a h5 file to pb file, then while loading the pb file I get the following error.

Traceback (most recent call last):
  File "import_model.py", line 244, in <module>
    detections = sess.run(detectionsT, feed_dict={img_ph: molded_images, img_meta_ph: image_metas})
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 877, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1100, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1272, in _do_run
    run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1291, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Invalid loop structure: Loop "mrcnn_detection/map/while/while_context" has more than one LoopCond node: "mrcnn_detection/map/while/LoopCond_1" and "mrcnn_detection/map/while/LoopCond". This is an internal bug, please file a bug report with instructions on how to reproduce the error.

Have I written custom code - No, forked from - https://github.com/GustavZ/Mobile_Mask_RCNN
OS Platform and Distribution- linux ubuntu 16.04
TensorFlow installed from - using pip
Bazel version- N/A
CUDA/cuDNN version- N/A
GPU model and memory- N/A
Exact command to reproduce - convert the h5 file to pb and then load the pb file
Mobile device - N/A

**Comment by harshini-gadige** [comment]
@ankitesh97 Hi, request you to provide a code snippet to reproduce the error and share the following information. 

Have I written custom code
OS Platform and Distribution
TensorFlow installed from
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by ankitesh97** [comment]
Hey, I have updated the details please check

**Comment by tensorflowbutler** [comment]
Nagging Assignee @harshini-gadige: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by harshini-gadige** [comment]
@skye   PTAL

**Comment by skye** [comment]
@ankitesh97 can you provide the exact commands you run in the Mobile_Mask_RCNN repo to get this error?

**Comment by harshini-gadige** [comment]
> @ankitesh97 can you provide the exact commands you run in the Mobile_Mask_RCNN repo to get this error?

@ankitesh97  Could you please provide the information asked above. It would help us to look into the issue. Thanks !

**Comment by skye** [comment]
Hi, sorry for the delay. This looks like a control flow bug, which we're currently reimplementing (see https://github.com/tensorflow/community/blob/master/rfcs/20180507-cond-v2.md and https://github.com/tensorflow/community/blob/master/rfcs/20180821-differentiable-functional-while.md for details).

Would you mind running your code with the following environment variables set:
TF_ENABLE_WHILE_V2=1 TF_ENABLE_COND_V2=1

Please report any errors you get with these env variables set. Thanks!

**Comment by harshini-gadige** [comment]
@ankitesh97  Have you tried with the above setting of environment variables ? Please keep us posted and we will reopen.
