### ISSUE TITLE
How to convert Tensorrt Optimized graph to Tensorrt engine

### ISSUE THREAD

**Issue by LinHungShi** [tensorflow/tensorflow#22955]
I need to convert my tensorflow model to tensorrt engine. However, since there are some unsupported layers in the model, I decided to use create_inference_graph to skip those operations. Although it works well with Python, I need to write it to *.engine file so that I can read it in C++. I tried to convert it to uff model using uff_model_from_tensorflow_frozen_model, but got key error. Is there a way I can convert the optimized graph to an engine? Any suggestion would be appreciated.

### System information

- **OS Platform and Distribution : Ubuntu 16.04
- **TensorFlow installed from (source or binary) : source
- **TensorFlow version 1.7 ~ 1.11
- **Python version**: 3.5
- **CUDA/cuDNN version**: CUDA 8.0, 9.0; CUDNN 7.0, 7.3

- **Exact command to reproduce**:
```
def load_graph(file):
    with tf.gfile.GFile(file, 'rb') as f:
        graph_def = tf.GraphDef()
        graph_def.ParseFromString(f.read())
    with tf.Graph().as_default() as graph:
        tf.import_graph_def(graph_def)
    return graph, graph_def

graph = load_graph('tensorflow_model.pb')
tensorrt_graph = trt.create_inference_graph(graph_def, outputs=['output_node'], max_batch_size=1, precision_mode='FP32', max_workspace_size_bytes=1<<33)

with tf.gfile.GFile('tensorrt_model.pb', 'wb') as f:
    f.write(tensorrt_graph.SerializeToString())

loaded_tensorrt_graph, loaded_tensorrt_graph_def = load_graph('tensorrt_model.pb')
uff_model = uff.from_tensorflow_frozen_model(loaded_tensorrt_graph_def)
```

Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/usr/lib/python3.5/dist-packages/uff/converters/tensorflow/conversion_helpers.py", line 149, in from_tensorflow_frozen_model
return from_tensorflow(graphdef, output_nodes, preprocessor, **kwargs)
File "/usr/lib/python3.5/dist-packages/uff/converters/tensorflow/conversion_helpers.py", line 120, in from_tensorflow
name="main")
File "/usr/lib/python3.5/dist-packages/uff/converters/tensorflow/converter.py", line 76, in convert_tf2uff_graph
uff_graph, input_replacements)
File "/usr/lib/python3.5/dist-packages/uff/converters/tensorflow/converter.py", line 63, in convert_tf2uff_node
op, name, tf_node, inputs, uff_graph, tf_nodes=tf_nodes)
File "/usr/lib/python3.5/dist-packages/uff/converters/tensorflow/converter.py", line 38, in convert_layer
fields = cls.parse_tf_attrs(tf_node.attr)
File "/usr/lib/python3.5/dist-packages/uff/converters/tensorflow/converter.py", line 209, in parse_tf_attrs
for key, val in attrs.items()}
File "/usr/lib/python3.5/dist-packages/uff/converters/tensorflow/converter.py", line 209, in <dictcomp>
for key, val in attrs.items()}
File "/usr/lib/python3.5/dist-packages/uff/converters/tensorflow/converter.py", line 204, in parse_tf_attr_value
return cls.convert_tf2uff_field(code, val)
File "/usr/lib/python3.5/dist-packages/uff/converters/tensorflow/converter.py", line 189, in convert_tf2uff_field
'type': 'dtype', 'list': 'list'}
KeyError: 'shape'

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
Bazel version
GPU model and memory
Mobile device

**Comment by fferroni** [comment]
If there are unsupported operations, you will have to keep it inside a Tensorflow graph. What tensorflow.contrib.tensorrt does is replace the sections of the TF graph with TensorRT calls. You can still run this optimized protobuf in C++ but you will have to compile the tensorflow_cc.so and use the Tensorflow C++ API.

If you want to use a TensorRT engine, and you have unsupported operations in your graph, then the UFF parser will fail. One way is to export to ONNX and implement the unsupported operations as custom plugins.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @samikama: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.
