### ISSUE TITLE
Tensor is not an element of this graph.

### ISSUE THREAD

**Issue by epicvrvs** [tensorflow/tensorflow#22999]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes.
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10, Version 10.0.17134.285.
- **TensorFlow installed from (source or binary)**: Binary.
- **TensorFlow version (use command below)**: b'v1.11.0-rc2-4-gc19e29306c' 1.11.0.
- **Python version**: Python 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 03:37:03) [MSC v.1900 64 bit (AMD64)] on win32.
- **CUDA/cuDNN version**: CUDA V9.0.176, cuDNN v7.3.1.
- **GPU model and memory**: Nvidia GTX 970 4 GB.
- **Bazel version**: N/A.
- **Mobile platform**: N/A.
- **Exact command to reproduce**: `python test.py training_dry.wav training_wet.wav validation_dry.wav validation_wet.wav`

### Description

I'm probably doing something horribly wrong with regard to graph/session handling. I tried to copy examples from the documentation but my code is still failing with the following error:

```
C:\Users\Markov\AppData\Local\Programs\Python\Python36\lib\site-packages\scipy\io\wavfile.py:273: WavFileWarning: Chunk (non-data) not understood, skipping it.
  WavFileWarning)
2018-10-16 00:11:07.807782: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2018-10-16 00:11:08.164098: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1411] Found device 0 with properties:
name: GeForce GTX 970 major: 5 minor: 2 memoryClockRate(GHz): 1.253
pciBusID: 0000:01:00.0
totalMemory: 4.00GiB freeMemory: 3.31GiB
2018-10-16 00:11:08.172047: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1490] Adding visible gpu devices: 0
2018-10-16 00:11:09.229492: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-10-16 00:11:09.234965: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977]      0
2018-10-16 00:11:09.237217: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990] 0:   N
2018-10-16 00:11:09.240415: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1103] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3023 MB memory) -> physical GPU (device: 0, name: GeForce GTX 970, pci bus id: 0000:01:00.0, compute capability: 5.2)
Commencing training.
Iteration 1
Traceback (most recent call last):
  File "C:\Users\Markov\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1050, in _run
    subfeed, allow_tensor=True, allow_operation=False)
  File "C:\Users\Markov\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 3488, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "C:\Users\Markov\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 3567, in _as_graph_element_locked
    raise ValueError("Tensor %s is not an element of this graph." % obj)
ValueError: Tensor Tensor("Const:0", shape=(24085052,), dtype=float32) is not an element of this graph.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 92, in <module>
    train(dry_training_wav, wet_training_wav, dry_validation_wav, wet_validation_wav)
  File "train.py", line 66, in train
    run_operation(dry_training_wav, wet_training_wav, batch_size, minimize, session)
  File "train.py", line 26, in run_operation
    operation_output = session.run(operation, feed)
  File "C:\Users\Markov\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 887, in run
    run_metadata_ptr)
  File "C:\Users\Markov\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1053, in _run
    'Cannot interpret feed_dict key as Tensor: ' + e.args[0])
TypeError: Cannot interpret feed_dict key as Tensor: Tensor Tensor("Const:0", shape=(24085052,), dtype=float32) is not an element of this graph.
```

### Reproduction
```
import sys

import scipy.io.wavfile
import tensorflow as tf

def read_wav(path):
	rate, data = scipy.io.wavfile.read(path)
	return tf.convert_to_tensor(data, dtype = tf.float32)

def get_batch(data, offset, batch_size):
	return data[offset : offset + batch_size]

def get_length(tensor):
	return tensor.shape[0].value

def run_operation(dry_data, wet_data, batch_size, operation, session):
	offset = 0
	output = []
	while offset + batch_size < get_length(dry_training_wav):
		dry_batch = get_batch(dry_data, offset, batch_size)
		wet_batch = get_batch(wet_data, offset, batch_size)
		feed = {
			dry_data: dry_batch,
			wet_data: wet_batch
		}
		operation_output = session.run(operation, feed)
		output.append(operation_output)
		offset += batch_size
	return output

def get_graph():
	graph = tf.Graph()
	with graph.as_default():
		frame_count = 96
		lstm_layers = 64

		frame_shape = [frame_count]

		dry_data = tf.placeholder(tf.float32, frame_shape, 'dry_data')
		wet_data = tf.placeholder(tf.float32, frame_shape, 'wet_data')

		lstm = tf.contrib.cudnn_rnn.CudnnLSTM(lstm_layers, frame_count)
		reshaped_dry_data = tf.reshape(dry_data, [1, 1, frame_count])
		lstm_output, _ = lstm(reshaped_dry_data)
		flat_lstm_output = tf.reshape(lstm_output, frame_shape)
		prediction = tf.nn.elu(flat_lstm_output)

		loss = tf.sqrt(tf.losses.mean_squared_error(prediction, wet_data), name = 'loss')
		optimizer = tf.train.AdamOptimizer()
		minimize = optimizer.minimize(loss, name = 'minimize')
	return graph

def train(dry_training_wav, wet_training_wav, dry_validation_wav, wet_validation_wav):
	graph = get_graph()
	with tf.Session(graph = graph) as session:
		initializer = tf.global_variables_initializer()
		session.run(initializer)
		iteration = 1
		dry_data_placeholder = graph.get_operation_by_name('dry_data')
		batch_size = dry_data_placeholder.outputs[0].shape[0].value
		loss = graph.get_operation_by_name('loss')
		minimize = graph.get_operation_by_name('minimize')
		print('Commencing training.')
		while True:
			print(f'Iteration {iteration}')
			run_operation(dry_training_wav, wet_training_wav, batch_size, minimize, session)
			losses = run_operation(dry_validation_wav, wet_validation_wav, batch_size, loss, session)
			validation_loss = sum(losses)
			print(f'Validation: {validation_loss}')
			iteration += 1

if len(sys.argv) != 5:
	print('Usage:')
	print(f'{sys.argv[0]} <dry training WAV file> <wet training WAV file> <dry validation WAV file> <wet validation WAV file>')
	sys.exit(1)

dry_training_wav_path = sys.argv[1]
wet_training_wav_path = sys.argv[2]

dry_validation_wav_path = sys.argv[3]
wet_validation_wav_path = sys.argv[4]

dry_training_wav = read_wav(dry_training_wav_path)
wet_training_wav = read_wav(wet_training_wav_path)

dry_validation_wav = read_wav(dry_validation_wav_path)
wet_validation_wav = read_wav(wet_validation_wav_path)

if get_length(dry_training_wav) != get_length(wet_training_wav) or get_length(dry_validation_wav) != get_length(wet_validation_wav):
	raise Exception('Dry and wet WAVs must be same length.')

train(dry_training_wav, wet_training_wav, dry_validation_wav, wet_validation_wav)
```

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Bazel version
Exact command to reproduce
Mobile device

**Comment by epicvrvs** [comment]
I added the missing fields but the command probably wouldn't help you much, unless you added some bogus WAV files to run my test script with. I doubt this a bug. I'm afraid I just don't fully grasp the graph/session documentation.

Why is it rejecting my input tensor? Isn't this the right way to feed input into the graph for execution on the GPU?

- **Bazel version**: N/A.
- **Mobile platform**: N/A.
- **Exact command to reproduce**: `python test.py training_dry.wav training_wet.wav validation_dry.wav validation_wet.wav`

**Comment by epicvrvs** [comment]
Figured it out. There are several horrible mistakes in that code. First off, you're not supposed to create tensors outside the session context, second, those don't go into the feed dictionary anyway, from what I gathered, third, I confused JavaScript object notation with Python dictionary syntax, causing me to use PCM frames rather than placeholders from the graph as feed keys. Humiliating. Ouch.
