### ISSUE TITLE
Undefined reference to stream_executor::Stream::ThenBlasGemm in _gru_ops.so

### ISSUE THREAD

**Issue by momeara** [tensorflow/tensorflow#22997]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Adjustments for build
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux <HOST> 2.6.32-573.7.1.el6.centos.plus.x86_64 #1 SMP Wed Sep 23 03:02:55 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
- **TensorFlow installed from (source or binary)**: source git rev: ac7b84de8803edbb2d4da573b3f8704e9fad8fa8
- **TensorFlow version (use command below)**: b'v1.9.0-rc2-5328-gac7b84d' 1.11.0-rc1
- **Python version**: Python 3.6.6 :: Anaconda, Inc.
- **Bazel version (if compiling from source)**: bazel-0.17.1
- **GCC/Compiler version (if compiling from source)**: gcc version 4.9.3 (GCC)
- **CUDA/cuDNN version**: cuda-9.0, libcudnn.so.7.3.1
- **GPU model and memory**:
- **Exact command to reproduce**: `python -c "import tensorflow.contrib`

### Describe the problem

Problem seems similar to the now closed #19840

#### Modifications to Tensorflow source
From the checked out source I made the following modifications:

- added `-lrt` to linkopts  in `tensorflow.bzl` for compatibility with CentOS following https://github.com/tensorflow/tensorflow/issues/15129

- Added `use_default_shell_env = True to `ctx.action()` in  in `tensorflow.bzl` for problems with swig following https://github.com/aiqu/devsetting/commit/f927890e05e06382ef1606decf38f192a75bac71

- compiled with --monolithic because of an issue with `load_library` throwing a `ByteSizeConsistencyError` when serializing `_bigtable.so` perhaps among others when running on my compute cluster vs. workstation where tensorflow is compiled.

- changed the paths for `gcc` to point to `v4.9` installed in `~/opt` in various `CROSSTOOL` config files.

Here is a [gist](https://gist.github.com/momeara/2edb2d606ea9490d3bbb358ed2b57855) of the diffs.

#### Set up the environment
```
export CC=/mnt/nfs/home/momeara/opt/bin/gcc
export CXX=/mnt/nfs/home/momeara/opt/bin/g++
export PYTHON_BIN_PATH=/nfs/ex9/work/momeara/tools/anaconda3/envs/DeepSEA/bin/python
export PYTHON_LIB_PATH=/nfs/ex9/work/momeara/tools/anaconda3/envs/DeepSEA/lib/python3.6/site-packages
export TF_NEED_AWS=0
export TF_NEED_KAFKA=0
export TF_NEED_NGRAPH=0
export TF_NEED_IGNITE=0
export TF_NEED_ROCM=0
export TF_NEED_TENSORRT=0
export TF_NEED_JEMALLOC=0
export TF_NEED_GCP=0
export TF_NEED_HDFS=0
export TF_NEED_S3=0
export TF_ENABLE_XLA=0
export TF_NEED_GDR=0
export TF_NEED_VERBS=0
export TF_NEED_OPENCL=0
export TF_NEED_OPENCL_SYCL=0
export TF_NCCL_VERSION="2.3"
export NCCL_INSTALL_PATH=/mnt/nfs/ex9/work/momeara/collaborations/DeepSEA/nccl/nccl_2.3.5-2+cuda9.0_x86_64
export TF_SET_ANDROID_WORKSPACE=0
export TF_NEED_CUDA=1
export TF_CUDA_VERSION=10.0
export CUDA_TOOLKIT_PATH=/nfs/soft/cuda-10.0
export CUDA_HOME=/nfs/soft/cuda-10.0
export TF_CUDNN_VERSION=7.3.1
export CUDNN_INSTALL_PATH=/mnt/nfs/ex9/work/momeara/collaborations/DeepSEA/cuda
export TF_CUDA_COMPUTE_CAPABILITIES=5.2
export TF_CUDA_CLANG=0
export TF_NEED_MPI=0
export GCC_HOST_COMPILER_PATH=/mnt/nfs/home/momeara/opt/bin/gcc
export CC_OPT_FLAGS='-march=native'
# path to /nfs/soft is for /nfs/soft/cuda/include/cudnn.h
export CPLUS_INCLUDE_PATH=/mnt/nfs/home/momeara/opt/include:/nfs/soft:/nfs/soft/cuda/include
export C_INCLUDE_PATH=/mnt/nfs/home/momeara/opt/include:/nfs/soft:/nfs/soft/cuda/include
export LIBRARY_PATH=/nfs/soft/cuda-10.0/lib64:/nfs/soft/cuda-10.0/extras/CUPTI/lib64:/mnt/nfs/home/momeara/opt/lib:/mnt/nfs/home/momeara/opt/lib64:/nfs/soft/cuda/nfs/soft/cuda/lib64
export LD_LIBRARY_PATH=/nfs/soft/cuda-10.0/lib64:/nfs/ex9/work/momeara/collaborations/DeepSEA/cuda/lib64:/nfs/soft/cuda-10.0/extras/CUPTI/lib64:/mnt/nfs/home/momeara/opt/lib:/mnt/nfs/home/momeara/opt/lib64:/nfs/soft/cuda/nfs/soft/cuda/lib64
export PATH=/nfs/soft/cuda-10.0/bin:/mnt/nfs/ex9/work/momeara/collaborations/DeepSEA/tensorflow/bazel-0.17.1/output:/nfs/home/momeara/opt/ncbi-blast-2.2.30+/bin:/nfs/ex9/work/momeara/tools/anaconda3/envs/DeepSEA/bin:/nfs/ex9/work/momeara/tools/anaconda3/bin:/mnt/nfs/home/momeara/.local/bin:/mnt/nfs/home/momeara/opt/node-v4.5.0-linux-x64/bin:/mnt/nfs/home/momeara/opt/bin:/usr/lib64/qt-3.3/bin:/usr/kerberos/sbin:/usr/kerberos/bin:/usr/local/bin:/bin:/usr/bin
```

#### Build and install `tensorflow`
```
./configure
bazel \
  --output_user_root=/nfs/ex9/work/momeara/collaborations/DeepSEA/tensorflow/.cache \
  build \
  --config=cuda \
  --config=opt \
  --config=monolithic \
  //tensorflow/tools/pip_package:build_pip_package

./bazel-bin/tensorflow/tools/pip_package/build_pip_package \
  --src /scratch/momeara/tensorflow_pkg_dbg_monolithic_src \
  /scratch/momeara/tensorflow_pkg_dbg_monolithic
pip install --upgrade /scratch/momeara/tensorflow_pkg_dbg_monolithic/tensorflow-*.whl

python -c "import tensorflow.contrib"
```
gives this error (see below for full backtrace)

```
tensorflow.python.framework.errors_impl.NotFoundError: /nfs/ex9/work/momeara/tools/anaconda3/envs/DeepSEA/lib/python3.6/site-packages/tensorflow/contrib/rnn/python/ops/_gru_ops.so: undefined symbol: _ZN15stream_executor6Stream12ThenBlasGemmENS_4blas9TransposeES2_yyyfRKNS_12DeviceMemoryIfEEiS6_ifPS4_i
```

#### Differential testing
- The same problem only arises with the `--config=monolithic` flags.
- Including debug flags `-c dbg --copt=-DNDEBUG --strip=never` makes no difference.

### Source code / logs

```
python -c "import tensorflow.contrib"
# ...generic warnings...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nfs/ex9/work/momeara/tools/anaconda3/envs/DeepSEA/lib/python3.6/site-packages/tensorflow/contrib/__init__.py", line 45, in <module>
    from tensorflow.contrib import cudnn_rnn
  File "/nfs/ex9/work/momeara/tools/anaconda3/envs/DeepSEA/lib/python3.6/site-packages/tensorflow/contrib/cudnn_rnn/__init__.py", line 34, in <module>
    from tensorflow.contrib.cudnn_rnn.python.layers import *
  File "/nfs/ex9/work/momeara/tools/anaconda3/envs/DeepSEA/lib/python3.6/site-packages/tensorflow/contrib/cudnn_rnn/python/layers/__init__.py", line 23, in <module>
    from tensorflow.contrib.cudnn_rnn.python.layers.cudnn_rnn import *
  File "/nfs/ex9/work/momeara/tools/anaconda3/envs/DeepSEA/lib/python3.6/site-packages/tensorflow/contrib/cudnn_rnn/python/layers/cudnn_rnn.py", line 20, in <module>
    from tensorflow.contrib.cudnn_rnn.python.ops import cudnn_rnn_ops
  File "/nfs/ex9/work/momeara/tools/anaconda3/envs/DeepSEA/lib/python3.6/site-packages/tensorflow/contrib/cudnn_rnn/python/ops/cudnn_rnn_ops.py", line 22, in <module>
    from tensorflow.contrib.rnn.python.ops import lstm_ops
  File "/nfs/ex9/work/momeara/tools/anaconda3/envs/DeepSEA/lib/python3.6/site-packages/tensorflow/contrib/rnn/__init__.py", line 92, in <module>
    from tensorflow.contrib.rnn.python.ops.gru_ops import *
  File "/nfs/ex9/work/momeara/tools/anaconda3/envs/DeepSEA/lib/python3.6/site-packages/tensorflow/contrib/rnn/python/ops/gru_ops.py", line 33, in <module>
    resource_loader.get_path_to_datafile("_gru_ops.so"))
  File "/nfs/ex9/work/momeara/tools/anaconda3/envs/DeepSEA/lib/python3.6/site-packages/tensorflow/contrib/util/loader.py", line 56, in load_op_library
    ret = load_library.load_op_library(path)
  File "/nfs/ex9/work/momeara/tools/anaconda3/envs/DeepSEA/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 60, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /nfs/ex9/work/momeara/tools/anaconda3/envs/DeepSEA/lib/python3.6/site-packages/tensorflow/contrib/rnn/python/ops/_gru_ops.so: undefined symbol: _ZN15stream_executor6Stream12ThenBlasGemmENS_4blas9TransposeES2_yyyfRKNS_12DeviceMemoryIfEEiS6_ifPS4_i
```

For what it's worth here the symbols in `_gru_ops.so` missing containing `stream_executor`:

```
nm -C -u /nfs/ex9/work/momeara/tools/anaconda3/envs/DeepSEA/lib/python3.6/site-packages/tensorflow/contrib/rnn/python/ops/_gru_ops.so | grep stream_executor                                                                                                
                 U stream_executor::Stream::ThenBlasGemm(stream_executor::blas::Transpose, stream_executor::blas::Transpose, unsigned long long, unsigned long long, unsigned long long, double, stream_executor::DeviceMemory<double> const&, int, stream_executor::DeviceMemory<double> const&, int, double, stream_executor::DeviceMemory<double>*, int)
                 U stream_executor::Stream::ThenBlasGemm(stream_executor::blas::Transpose, stream_executor::blas::Transpose, unsigned long long, unsigned long long, unsigned long long, float, stream_executor::DeviceMemory<float> const&, int, stream_executor::DeviceMemory<float> const&, int, float, stream_executor::DeviceMemory<float>*, int)
```

**Comment by eryshev** [comment]
Oh thank you @momeara for filling the issue. 
I just wanted to do it by myself. 
We have the same problem in our  home-compiled TF since the 1.9.rc0 or rc1.
BTW I think the commit introduced it is https://github.com/tensorflow/tensorflow/commit/80fc661853f9a0844faf95eb68438dc85a5879e3#diff-06268ec57b0c7871d7e7cab011778559
and there is a related issue that was closed with no resolution https://github.com/tensorflow/tensorflow/issues/19840

**Comment by agansa** [comment]
Same issue with TF1.11, with/without monolithic
CUDA 9.2
CUDNN 7.1.4
RHEL 7.3
Power 8
gcc (GCC) 4.8.5
bazel-0.18.0
...../tensorflow/contrib/rnn/python/ops/_gru_ops.so: undefined symbol: _ZN15stream_executor6Stream12ThenBlasGemmENS_4blas9TransposeES2_yyydRKNS_12DeviceMemoryIdEEiS6_idPS4_i

**Comment by agansa** [comment]
I tried with --config=opt
the other options are not available but it gives the same error.

**Comment by momeara** [comment]
As @eryshev suggested, I tried with building with the parent of 80fc661, and it looks like it may not have the issue.

**Comment by wt-huang** [comment]
Looks like this is resolved by suggestion from @eryshev. You can also use the latest TensorFlow version or leverage docker
