### ISSUE TITLE
tf.contrib.feature_column.sequence_numeric_column normalize_fn argument not working

### ISSUE THREAD

**Issue by cadama** [tensorflow/tensorflow#22991]
I am using tf.contrib.feature_column.sequence_numeric_column to normalize a sparse tensor through normalize_fn. Here is a minimal example of the error that I get:
```
import tensorflow as tf
import numpy as np
a = np.reshape(np.arange(12), (3, 4, 1))
with tf.Session() as sess:
    a_t = tf.constant(a)
    idx = tf.where(tf.not_equal(a_t, 0))
    sparse = tf.SparseTensor(idx, tf.gather_nd(a_t, idx), a_t.get_shape())
    seq_cols = tf.contrib.feature_column.sequence_numeric_column('test', default_value=.0, normalizer_fn=lambda x: (x - 2.) / .3)
    seq_features, sequence_length = tf.contrib.feature_column.sequence_input_layer({'test': sparse}, [seq_cols])

    b = sess.run(seq_features)
```
Rises:

```
Traceback (most recent call last):
  File "/anaconda2/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2878, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-12-137e79726dfc>", line 9, in <module>
    seq_features, sequence_length = tf.contrib.feature_column.sequence_input_layer({'test': sparse}, [seq_cols])
  File "/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/feature_column/python/feature_column/sequence_feature_column.py", line 120, in sequence_input_layer
    trainable=trainable)
  File "/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/feature_column/python/feature_column/sequence_feature_column.py", line 448, in _get_sequence_dense_tensor
    sp_tensor = inputs.get(self)
  File "/anaconda2/lib/python2.7/site-packages/tensorflow/python/feature_column/feature_column.py", line 2263, in get
    transformed = column._transform_feature(self)  # pylint: disable=protected-access
  File "/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/feature_column/python/feature_column/sequence_feature_column.py", line 435, in _transform_feature
    input_tensor = self.normalizer_fn(input_tensor)
  File "<ipython-input-12-137e79726dfc>", line 8, in <lambda>
    seq_cols = tf.contrib.feature_column.sequence_numeric_column('test', default_value=.0, normalizer_fn=lambda x: (x - 2.) / .3)
TypeError: unsupported operand type(s) for -: 'SparseTensor' and 'float'
```
Note that tf.contrib.feature_column.sequence_numeric_column is actually meant for sparse tensors so moving to dense is not an option here.

I am running tf 1.11.0 on python2.7

**Comment by harshini-gadige** [comment]
@cadama Hi, can you try with a lower version of tensorflow and tf-nightly and check if you still get this error.

**Comment by harshini-gadige** [comment]
@cadama - Hi, is this still an issue ?

**Comment by harshini-gadige** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by bhorkar** [comment]
The issue exists even with tf1.14.
