### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found | lib\site-packages\tensorflow\python\pywrap_tensorflow.py

### ISSUE THREAD

**Issue by umitkilic** [tensorflow/tensorflow#23016]
------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Win10 x64
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: -
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 1.11.0
- **Python version**: 3.6.4
- **Bazel version (if compiling from source)**: -
- **GCC/Compiler version (if compiling from source)**: -
- **CUDA/cuDNN version**: CUDA9 / cuDNN7.0.5
- **GPU model and memory**: Nvidia GeForce 1050 Ti
- **Exact command to reproduce**:
pip install tensorflow-gpu
python
import tensorflow as tf

### Describe the problem
I'm trying to install TensorFlow for my study. I tried a few version of python and CUDA/cuDNN but I am still getting the same error. This [blog](https://medium.com/@lmoroney_40129/installing-tensorflow-with-gpu-on-windows-10-3309fec55a00) is used to install properly. I have done each steps exactly the same with the blog. I have read and tried solutions from the tensorflow error list and almost all solution provided on the internet. Result is the same.

### Source code / logs
Traceback (most recent call last):
  File "C:\Users\Umit Kilic\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Umit Kilic\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Umit Kilic\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Umit Kilic\AppData\Local\Programs\Python\Python36\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Umit Kilic\AppData\Local\Programs\Python\Python36\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Umit Kilic\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\__init__.py", line 22, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\Umit Kilic\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Umit Kilic\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Umit Kilic\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Umit Kilic\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Umit Kilic\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Umit Kilic\AppData\Local\Programs\Python\Python36\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Umit Kilic\AppData\Local\Programs\Python\Python36\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found

**Comment by umitkilic** [comment]
First, I intalled CUDA10 and cuDNN 7.3.1 and the problem was still there. Then, I installed CUDA9 and cuDNN 7.0.5 again and restarted the computer. The related problem has just gone for now.

**Comment by nesjboor** [comment]
> First, I intalled CUDA10 and cuDNN 7.3.1 and the problem was still there. Then, I uninstalled both of them and reinstalled CUDA9 and cuDNN 7.0.5 again and restarted the computer. The related problem has just gone for now. Probably this is not a real solution but it works for me. Actually, finding the real causes of the errors will help other people that this solution does not work for.

Yup this worked for me. Thanks a lot.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @gunan: It has been 21 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @gunan: It has been 36 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by ymodak** [comment]
Thanks for sharing your solution. The compatible configuration fo TF 1.11 is cuda 9 and cudnn 7 which helped to resolve your issue. We have captured this information in Tested build configurations table.
See https://www.tensorflow.org/install/source#tested_build_configurations.
Closing this issue now since it's resolved. Thanks!
