### ISSUE TITLE
tf.make_tensor_proto doesn't work as expected

### ISSUE THREAD

**Issue by KineticCookie** [tensorflow/tensorflow#23012]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac OS X 10.13.6
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: none
- **TensorFlow installed from (source or binary)**: `pip install tensorflow==1.11.0`
- **TensorFlow version (use command below)**: v1.11.0-rc2-4-gc19e29306c 1.11.0
- **Python version**: Python 3.6.4
- **Bazel version (if compiling from source)**: none
- **GCC/Compiler version (if compiling from source)**: none
- **CUDA/cuDNN version**: none
- **GPU model and memory**: none
- **Exact command to reproduce**:
`print(tf.make_tensor_proto([1,2,3,4], dtype=tf.uint32))`

### Describe the problem

According to TensorProto message definition there are specific fields for different DataType e.g. for DT_UINT32 (https://github.com/tensorflow/tensorflow/blob/903a6399aab19b549fefd0ead836af644f3d00f8/tensorflow/core/framework/tensor.proto#L79-L80) 
However, `make_tensor_proto` puts content for most numeric types into `tensor_content` field.

In addition to that there is same inconsistency in `tf.make_ndarray` function: it tries to deserealize tensor_content and then it searches for correct fields with DataType. https://github.com/tensorflow/tensorflow/blob/903a6399aab19b549fefd0ead836af644f3d00f8/tensorflow/python/framework/tensor_util.py#L548

### Source code / logs

```python
import tensorflow as tf
from tensorflow.core.framework import tensor_pb2
from tensorflow.python.framework import dtypes

current = tf.make_tensor_proto([1,2,3,4], dtype=tf.uint32)
print(current)
#dtype: DT_UINT32
#tensor_shape {
#  dim {
#    size: 4
#  }
#}
#tensor_content: "\001\000\000\000\002\000\000\000\003\000\000\000\004\000\000\000"

expected = tensor_pb2.TensorProto(dtype=dtypes.uint32.as_datatype_enum, uint32_val=[1,2,3,4])
print(expected)
#dtype: DT_UINT32
#uint32_val: 1
#uint32_val: 2
#uint32_val: 3
#uint32_val: 4
```

**Comment by KineticCookie** [comment]
In addition to that, I can't make ndarray from manually composed uint32 tensor.
```python
import tensorflow as tf
from tensorflow.core.framework import tensor_pb2
from tensorflow.python.framework import dtypes

expected_tensor = tensor_pb2.TensorProto(dtype=dtypes.uint32.as_datatype_enum, uint32_val=[1,2,3,4])
expected_array = tf.make_ndarray(expected_tensor)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/bulat/anaconda/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py", line 649, in MakeNdarray
    raise TypeError("Unsupported tensor type: %s" % tensor.dtype)
TypeError: Unsupported tensor type: 22
```

**Comment by KineticCookie** [comment]
I fixed the `tensor_content` issue in my code by using the forked version of the function.
By removing the following `if` clause I restored the documented behavior.
https://github.com/tensorflow/tensorflow/blob/4bb45e6cdddfd8f818ee037216e732f3fd133413/tensorflow/python/framework/tensor_util.py#L503-L508

However, I'm don't know what is the purpose of`_TENSOR_CONTENT_TYPES`.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @harshini-gadige: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @harshini-gadige: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by aselle** [comment]
@josh11b may be able to comment further, but I believe that the type specific fields are mostly historical and are not required to be used. If you use tensor_content you don't use the int specific one. So the output given is expected and valid.

**Comment by mohantym** [comment]
Hi @KineticCookie!
It seems you are using 1.x versions of Tensorflow. We recommend that you upgrade  your code base to 2.x  versions  as as Many features and bug fixes has been done in newer versions and let us know if the issue still persists in newer versions. Thanks!
