### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by KevorkSulahian** [tensorflow/tensorflow#23026]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:  failed at import tensorflow
- **OS Platform and Distribution: Ubuntu 18.04.1 LTS
- **TensorFlow installed from : Anaconda
- **TensorFlow version (use command below)**:  1.11.0
- **Python version**: 3.6.6
- **Bazel version (if compiling from source)**: not using
- **GCC/Compiler version (if compiling from source)**: [GCC 7.3.0] on linux
- **CUDA/cuDNN version**: 9.1.85 /  not sure was automatically download
- **GPU model and memory**: GeForce 840m

### Describe the problem
basically it doesn't work when i run "import tensorflow"

### Source code / logs
Python 3.6.6 |Anaconda, Inc.| (default, Oct  9 2018, 12:34:16) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
Traceback (most recent call last):
  File "/home/herooooooooo/anaconda3/envs/tf_gpu/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/herooooooooo/anaconda3/envs/tf_gpu/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/herooooooooo/anaconda3/envs/tf_gpu/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/herooooooooo/anaconda3/envs/tf_gpu/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/home/herooooooooo/anaconda3/envs/tf_gpu/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libcuda.so.1: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/herooooooooo/anaconda3/envs/tf_gpu/lib/python3.6/site-packages/tensorflow/__init__.py", line 22, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/herooooooooo/anaconda3/envs/tf_gpu/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/herooooooooo/anaconda3/envs/tf_gpu/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/herooooooooo/anaconda3/envs/tf_gpu/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/herooooooooo/anaconda3/envs/tf_gpu/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/herooooooooo/anaconda3/envs/tf_gpu/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/herooooooooo/anaconda3/envs/tf_gpu/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/home/herooooooooo/anaconda3/envs/tf_gpu/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libcuda.so.1: cannot open shared object file: No such file or directory

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by KevorkSulahian** [comment]
> 
> 
> It is CUDA error. Tensorflow is not able to find cuda. How did you install tensorflow?

I simply used     conda install -c anaconda tensorflow-gpu

**Comment by KevorkSulahian** [comment]
I just checked there's no libcuda.so.1, i did find libcuda.so.9

**Comment by smitshilu** [comment]
Try creating an alias of libcuda.so.9 as libcuda.so.1

**Comment by KevorkSulahian** [comment]
I'm really sorry it's libcudart.so.9.2 and does it change if it is in a environment? basically i have to write
conda activate tf_gpu
to start it
