### ISSUE TITLE
Error using kernel_regularizer with tf.layers.Dense and tf.contrib.distribute.MirroredStrategy TF v1.12.0rc0 regression

### ISSUE THREAD

**Issue by Matt-Hicks-Bose** [tensorflow/tensorflow#23030]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: N/A
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: ('v1.12.0-rc0-0-g1a6dea36de', '1.12.0-rc0')
- **Python version**: 2.7.12
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: 9.0.176/7.2.1.38
- **GPU model and memory**: Nvidia V100 16GB
- **Exact command to reproduce**: See below

### Describe the problem
Attempting to use a `tf.contrib.layers.l2_regularizer` for the `kernel_regularizer` param of `tf.layers.Dense` causes an `AssertionError` when using with `tf.contrib.distribute.MirroredStrategy` under Tensorflow v1.12.0rc0, but not under Tensorflow v1.11.0. This also occurs with several other layers including `tf.layers.dense` and `tf.layers.conv2d`.

### Source code / logs
Source of test.py:
```python
import tensorflow as tf

DO_L2_REG = False

tf.logging.set_verbosity(tf.logging.INFO)

def model_fn(features, labels, mode):
    regularizer = tf.contrib.layers.l2_regularizer(0.001) if DO_L2_REG else None
    layer = tf.layers.Dense(1, kernel_regularizer=regularizer)
    logits = layer(features)

    if mode == tf.estimator.ModeKeys.PREDICT:
        predictions = {"logits": logits}
        return tf.estimator.EstimatorSpec(mode, predictions=predictions)

    loss = tf.losses.mean_squared_error(
        labels=labels, predictions=tf.reshape(logits, []))

    loss += tf.losses.get_regularization_loss()

    if mode == tf.estimator.ModeKeys.EVAL:
        return tf.estimator.EstimatorSpec(mode, loss=loss)

    if mode == tf.estimator.ModeKeys.TRAIN:
        train_op = tf.train.GradientDescentOptimizer(0.2).minimize(loss, global_step=tf.train.get_global_step())#loss_fn())
        return tf.estimator.EstimatorSpec(mode, loss=loss, train_op=train_op)

def input_fn():
    features = tf.data.Dataset.from_tensors([[1.]]).repeat()
    labels = tf.data.Dataset.from_tensors(1.).repeat()
    return tf.data.Dataset.zip((features, labels))

distribution = tf.contrib.distribute.MirroredStrategy()
config = tf.estimator.RunConfig(train_distribute=distribution)
classifier = tf.estimator.Estimator(model_fn=model_fn, config=config, model_dir='out_test')
print('********* start train **********')
classifier.train(input_fn=input_fn, steps=1000)
print('********* end train/start eval **********')
classifier.evaluate(input_fn=input_fn, steps=1000)
print('********* end eval **********')
```

### Results of testing this code with different version of Tensorflow and `DO_L2_REG` values:
* Calling this with Tensorflow v1.11.0 with `DO_L2_REG` set to either `True` or `False` works as expected, both training and evaluation run successfully.
* Calling this with Tensorflow v1.12.0rc0 with `DO_L2_REG` set to `False` works as expected, both training and evaluation run successfully.
* Calling this with Tensorflow v1.12.0rc0 with `DO_L2_REG` set to `True` results in the following error when the `classifier.train` is called:
```
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Error reported to Coordinator:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/coordinator.py", line 297, in stop_on_exception
    yield
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/distribute/python/mirrored_strategy.py", line 795, in run
    self.main_result = self.main_fn(*self.main_args, **self.main_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 1195, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "test.py", line 10, in model_fn
    logits = layer(features)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/layers/base.py", line 374, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 746, in __call__
    self.build(input_shapes)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/layers/core.py", line 944, in build
    trainable=True)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/layers/base.py", line 293, in add_weight
    self._handle_weight_regularization(name, variable, regularizer)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 638, in _handle_weight_regularization
    self.add_loss(functools.partial(_loss_for_variable, variable))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/layers/base.py", line 142, in add_loss
    loss_tensor = regularizer()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 434, in _tag_unconditional
    loss = loss()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 629, in _loss_for_variable
    with ops.colocate_with(v):
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 4094, in _colocate_with_for_gradient
    with self.colocate_with(op, ignore_existing):
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 4146, in colocate_with
    op = internal_convert_to_tensor_or_indexed_slices(op, as_ref=True).op
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1307, in internal_convert_to_tensor_or_indexed_slices
    value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1146, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/distribute/python/values.py", line 439, in _tensor_conversion_mirrored
    assert not as_ref
AssertionError
Traceback (most recent call last):
  File "test.py", line 35, in <module>
    classifier.train(input_fn=input_fn, steps=1000)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 354, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 1205, in _train_model
    return self._train_model_distributed(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 1316, in _train_model_distributed
    self.config)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/distribute.py", line 721, in call_for_each_tower
    return self._call_for_each_tower(fn, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/distribute/python/mirrored_strategy.py", line 556, in _call_for_each_tower
    return _call_for_each_tower(self, fn, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/distribute/python/mirrored_strategy.py", line 183, in _call_for_each_tower
    coord.join(threads)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/coordinator.py", line 297, in stop_on_exception
    yield
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/distribute/python/mirrored_strategy.py", line 795, in run
    self.main_result = self.main_fn(*self.main_args, **self.main_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 1195, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "test.py", line 10, in model_fn
    logits = layer(features)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/layers/base.py", line 374, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 746, in __call__
    self.build(input_shapes)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/layers/core.py", line 944, in build
    trainable=True)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/layers/base.py", line 293, in add_weight
    self._handle_weight_regularization(name, variable, regularizer)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 638, in _handle_weight_regularization
    self.add_loss(functools.partial(_loss_for_variable, variable))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/layers/base.py", line 142, in add_loss
    loss_tensor = regularizer()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 434, in _tag_unconditional
    loss = loss()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 629, in _loss_for_variable
    with ops.colocate_with(v):
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 4094, in _colocate_with_for_gradient
    with self.colocate_with(op, ignore_existing):
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 4146, in colocate_with
    op = internal_convert_to_tensor_or_indexed_slices(op, as_ref=True).op
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1307, in internal_convert_to_tensor_or_indexed_slices
    value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1146, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/distribute/python/values.py", line 439, in _tensor_conversion_mirrored
    assert not as_ref
AssertionError
```

**Comment by tensorflowbutler** [comment]
Nagging Assignee @anj-s: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by jdvylder** [comment]
It also does not work when applying the l2 regularization with convolution layers: 
```Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/coordinator.py", line 297, in stop_on_exception
    yield
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/distribute/python/mirrored_strategy.py", line 795, in run
    self.main_result = self.main_fn(*self.main_args, **self.main_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 1195, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/media/local/BDA_tf_framework/neuralnetwork/trainingexperimenter.py", line 129, in get_model_fn
    self.configure_network(input_tensor=features, output_tensor=labels, mode=mode)
  File "/media/local/BDA_tf_framework/neuralnetwork/trainingexperimenter.py", line 86, in configure_network
    self.network.construct_network(input_tensor=input_tensor, output_tensor=output_tensor, mode=mode)
  File "/media/local/myfiles/mynetwork.py", line 91, in construct_network
    self.construct_architecture(input_tensor=input_tensor,mode=mode)
  File "/media/local/myfiles/mynetwork.py", line 54, in construct_architecture
    conv1, pool1 = self.conv_conv_pool(input_tensor, [filter_size, filter_size], training, l2, name=1)
  File "/media/local/myfiles/mynetwork.py", line 130, in conv_conv_pool
    name="conv_{}".format(i + 1))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/layers/convolutional.py", line 417, in conv2d
    return layer.apply(inputs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 817, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/layers/base.py", line 374, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 746, in __call__
    self.build(input_shapes)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/layers/convolutional.py", line 165, in build
    dtype=self.dtype)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/layers/base.py", line 293, in add_weight
    self._handle_weight_regularization(name, variable, regularizer)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 638, in _handle_weight_regularization
    self.add_loss(functools.partial(_loss_for_variable, variable))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/layers/base.py", line 142, in add_loss
    loss_tensor = regularizer()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 434, in _tag_unconditional
    loss = loss()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 629, in _loss_for_variable
    with ops.colocate_with(v):
  File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 4094, in _colocate_with_for_gradient
    with self.colocate_with(op, ignore_existing):
  File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 4146, in colocate_with
    op = internal_convert_to_tensor_or_indexed_slices(op, as_ref=True).op
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1307, in internal_convert_to_tensor_or_indexed_slices
    value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1146, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/distribute/python/values.py", line 439, in _tensor_conversion_mirrored
    assert not as_ref
AssertionError
[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 1546790882788519247
, name: "/device:XLA_CPU:0"
device_type: "XLA_CPU"
memory_limit: 17179869184
locality {
}
incarnation: 10996947278692380426
physical_device_desc: "device: XLA_CPU device"
, name: "/device:XLA_GPU:0"
device_type: "XLA_GPU"
memory_limit: 17179869184
locality {
}
incarnation: 9829494766080756018
physical_device_desc: "device: XLA_GPU device"
, name: "/device:GPU:0"
device_type: "GPU"
memory_limit: 15568473293
locality {
  bus_id: 1
  links {
    link {
      device_id: 1
      type: "StreamExecutor"
      strength: 1
    }
  }
}
incarnation: 10718015977797192246
physical_device_desc: "device: 0, name: Tesla V100-SXM2-16GB, pci bus id: 0000:62:00.0, compute capability: 7.0"
, name: "/device:GPU:1"
device_type: "GPU"
memory_limit: 15568473293
locality {
  bus_id: 2
  numa_node: 1
  links {
    link {
      type: "StreamExecutor"
      strength: 1
    }
  }
}
incarnation: 12456162273957908465
physical_device_desc: "device: 1, name: Tesla V100-SXM2-16GB, pci bus id: 0000:89:00.0, compute capability: 7.0"
]
Traceback (most recent call last):
  File "train.py", line 37, in <module>
    experimenter.run_training_experiment(config)
  File "/media/local/BDA_tf_framework/neuralnetwork/trainingexperimenter.py", line 40, in run_training_experiment
    tf.estimator.train_and_evaluate(self.trainer, self.training_specs, self.eval_specs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/training.py", line 471, in train_and_evaluate
    return executor.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/training.py", line 610, in run
    return self.run_local()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/training.py", line 711, in run_local
    saving_listeners=saving_listeners)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 354, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 1205, in _train_model
    return self._train_model_distributed(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 1316, in _train_model_distributed
    self.config)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/distribute.py", line 721, in call_for_each_tower
    return self._call_for_each_tower(fn, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/distribute/python/mirrored_strategy.py", line 556, in _call_for_each_tower
    return _call_for_each_tower(self, fn, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/distribute/python/mirrored_strategy.py", line 183, in _call_for_each_tower
    coord.join(threads)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/usr/local/lib/python3.5/dist-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/coordinator.py", line 297, in stop_on_exception
    yield
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/distribute/python/mirrored_strategy.py", line 795, in run
    self.main_result = self.main_fn(*self.main_args, **self.main_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 1195, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/media/local/BDA_tf_framework/neuralnetwork/trainingexperimenter.py", line 129, in get_model_fn
    self.configure_network(input_tensor=features, output_tensor=labels, mode=mode)
  File "/media/local/BDA_tf_framework/neuralnetwork/trainingexperimenter.py", line 86, in configure_network
    self.network.construct_network(input_tensor=input_tensor, output_tensor=output_tensor, mode=mode)
  File "/media/local/myfiles/mynetwork.py", line 91, in construct_network
    self.construct_architecture(input_tensor=input_tensor,mode=mode)
  File "/media/local/myfiles/mynetwork.py", line 54, in construct_architecture
    conv1, pool1 = self.conv_conv_pool(input_tensor, [filter_size, filter_size], training, l2, name=1)
  File "/media/local/myfiles/mynetwork.py", line 130, in conv_conv_pool
    name="conv_{}".format(i + 1))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/layers/convolutional.py", line 417, in conv2d
    return layer.apply(inputs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 817, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/layers/base.py", line 374, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 746, in __call__
    self.build(input_shapes)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/layers/convolutional.py", line 165, in build
    dtype=self.dtype)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/layers/base.py", line 293, in add_weight
    self._handle_weight_regularization(name, variable, regularizer)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 638, in _handle_weight_regularization
    self.add_loss(functools.partial(_loss_for_variable, variable))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/layers/base.py", line 142, in add_loss
    loss_tensor = regularizer()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 434, in _tag_unconditional
    loss = loss()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 629, in _loss_for_variable
    with ops.colocate_with(v):
  File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 4094, in _colocate_with_for_gradient
    with self.colocate_with(op, ignore_existing):
  File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 4146, in colocate_with
    op = internal_convert_to_tensor_or_indexed_slices(op, as_ref=True).op
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1307, in internal_convert_to_tensor_or_indexed_slices
    value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1146, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/distribute/python/values.py", line 439, in _tensor_conversion_mirrored
    assert not as_ref
AssertionError```

**Comment by CatEek** [comment]
Experiencing same problem with both conv layers and dense. TF 1.12/CUDA 10/CuDNN 7.4.1

**Comment by berendo** [comment]
Hmmm... b08c981d1d5556fb384cbbadcdc0d7c373324300 _seems_ to address this, but this issue is not linked?

**Comment by kevinyen-oath** [comment]
same issue in 1.12.0

**Comment by CatEek** [comment]
@berendo I can confirm, it's working

**Comment by raofengyun** [comment]
I have encountered the same problem.   
Both `tf.contrib.layers.l2_regularizer` and `tf.keras.regularizers.l2` not working with `tf.layers.dense` layer, using MirroredStratedy.  
tf 1.12 CUDA 9.0

**Comment by v-qjqs** [comment]
@raofengyun I have encountered the same problem. Both tf.contrib.layers.l2_regularizer and tf.keras.regularizers.l2 not working with tf.layers.dense or conv2d layer, using MirroredStratedy. Have you solved this problem? Thanks a lot.
tf 1.12 CUDA 9.0

**Comment by rmothukuru** [comment]
@Matt-Hicks-Bose,
Your code could be executed without any error in **`Tensorflow Version 1.15.2`**. Please find the [Colab Gist](https://colab.research.google.com/gist/rmothukuru/e13335eae0b81b9dcca7593394899c9c/gh_23030.ipynb#scrollTo=IyY5Ie5Tg9jH) of the working code, with **`GPU Runtime`**. Thanks!
