### ISSUE TITLE
dll load failed in tensorflow install using pip on windows 10

### ISSUE THREAD

**Issue by Ridhwanluthra** [tensorflow/tensorflow#23058]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): windows 10
- TensorFlow installed from (source or binary): pip
- TensorFlow version: 1.11
- Python version: 3.6
- Installed using virtualenv? pip? conda?: pip and venv
- CUDA/cuDNN version: 8 | 5.1/6
- GPU model and memory: nvidia geforce gtx 960m
- Have I written custom code: N/A
- Bazel version: N/A
- Exact command to reproduce: N/A
- Mobile device: N/A

**Describe the problem**

I did look at these issues and applied the fixes but still not working.
https://github.com/tensorflow/tensorflow/issues/10033
https://github.com/tensorflow/tensorflow/issues/5949

Then i found this https://gist.github.com/mrry/ee5dbcfdd045fa48a27d56664411d41c
turns out there were some version issues like it needed cuda 8 instead of 9. so I fixed all those things and its still not working please help

**Any other info / logs**
```
Traceback (most recent call last):
  File "C:\Users\luthr\rl\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\luthr\rl\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\luthr\rl\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\luthr\AppData\Local\Programs\Python\Python36\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\luthr\AppData\Local\Programs\Python\Python36\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\luthr\rl\lib\site-packages\tensorflow\__init__.py", line 22, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\luthr\rl\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\luthr\rl\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\luthr\rl\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\luthr\rl\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\luthr\rl\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\luthr\AppData\Local\Programs\Python\Python36\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\luthr\AppData\Local\Programs\Python\Python36\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
Bazel version
Exact command to reproduce
Mobile device

**Comment by harshini-gadige** [comment]
@Ridhwanluthra Hello, thanks for the post. Please make sure you are using cuDNN 7 and CUDA 9 when using tensorflow versions 1.5 or above. Thank you !

**Comment by Ridhwanluthra** [comment]
@harshini-gadige That is what I had initially done but it gave me the same error. I will try once again and get back to you

**Comment by Ridhwanluthra** [comment]
My graphics drivers were outdated and did not update on its own had to uninstall and reinstall them and it worked. I am assuming it was because of that as I rebuilt everything and it worked and this was the only difference between before and now

**Comment by xhyydynlxxd** [comment]
Have you solved this problem? The problem I encountered is exactly the same as you. Can you help me?I tried many ways。
