### ISSUE TITLE
Losses collection is not thread local so it can't be used inside model_fn call when using MirroredStrategy

### ISSUE THREAD

**Issue by antifriz** [tensorflow/tensorflow#23056]
**System information**

- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: no
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 'v1.12.0-rc0-0-g1a6dea3' 1.12.0-rc0
- Python version: 3.6
- Bazel version (if compiling from source): 0.18.0
- GCC/Compiler version (if compiling from source): gcc-6 (Ubuntu 6.4.0-17ubuntu1) 6.4.0 20180424
- CUDA/cuDNN version: 10.0/7.3.1.20
- GPU model and memory: GeForce GTX 1080 Ti (11GB)

**Describe the current behavior**

When calling `tf.losses.add_loss` inside model_fn in Estimator API, it is added to the `tf.GraphKeys.LOSSES` collection. `tf.losses.get_total_loss` is aggregating all the losses from the `tf.GraphKeys.LOSSES` collection.

Unfortunately, when using `tf.contrib.distribute.MirroredStrategy` as a distribute strategy, collection is updated from all concurrent `model_fn` calls. This leads to tower losses being aggregated to total loss in other towers as well.

So if we have 4 GPUs with losses L1, L2, L3, L4, Estimator will report total loss as `a * L1 + b * L2 + c * L3 + d* L4` where a,b,c,d depends on the races encountered.

**Describe the expected behavior**

I would expect total loss to be `L1 + L2 + L3 + L4`.

**Code to reproduce the issue**

When running this code, second call to `model_fn` causes assertion that losses collection is empty to fail.

```python
import tensorflow as tf


def model_fn(features, labels, mode):
    loss = tf.abs(features + tf.get_variable('foo', shape=()) - labels)

    assert len(tf.get_collection(tf.GraphKeys.LOSSES)) == 0
    tf.losses.add_loss(loss)

    loss = tf.losses.get_total_loss()
    train_op = tf.train.GradientDescentOptimizer(0.0).minimize(loss)
    return tf.estimator.EstimatorSpec(mode, loss=loss, train_op=train_op)


def input_fn():
    return tf.data.Dataset.zip((
        tf.data.Dataset.from_tensors(0.).repeat(100),
        tf.data.Dataset.from_tensors(0.).repeat(100)
    ))


distribution = tf.contrib.distribute.MirroredStrategy(num_gpus=2)
config = tf.estimator.RunConfig(train_distribute=distribution)
estimator = tf.estimator.Estimator(model_fn=model_fn, config=config)
estimator.train(input_fn=input_fn)
```

**Other info / logs**

Script output:

```
INFO:tensorflow:Initializing RunConfig with distribution strategies.
INFO:tensorflow:Not using Distribute Coordinator.
WARNING:tensorflow:Using temporary folder as model directory: /tmp/tmpq6v9w4nh
INFO:tensorflow:Using config: {'_model_dir': '/tmp/tmpq6v9w4nh', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': <tensorflow.contrib.distribute.python.mirrored_strategy.MirroredStrategy object at 0x7f27bd939240>, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f27bd939f60>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1, '_distribute_coordinator_mode': None}
INFO:tensorflow:Device is available but not used by distribute strategy: /device:CPU:0
INFO:tensorflow:Device is available but not used by distribute strategy: /device:GPU:2
INFO:tensorflow:Device is available but not used by distribute strategy: /device:GPU:3
INFO:tensorflow:Configured nccl all-reduce.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Error reported to Coordinator: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/coordinator.py", line 297, in stop_on_exception
    yield
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/distribute/python/mirrored_strategy.py", line 795, in run
    self.main_result = self.main_fn(*self.main_args, **self.main_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/estimator/estimator.py", line 1195, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "<ipython-input-9-57173fdb3adc>", line 7, in model_fn
    assert len(tf.get_collection(tf.GraphKeys.LOSSES)) == 0
AssertionError
```

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by harshini-gadige** [comment]
@seemuch  Any update ?

**Comment by seemuch** [comment]
Nothing to update for now. 
I did not have the bandwidth to deal with this yet.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @seemuch: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by sdll** [comment]
Any updates on this?

**Comment by guptapriya** [comment]
Unfortunately we are focus on 2.0 and Keras integration currently, so will not have the bandwidth to fix 1.x / Estimator issues. I will open this up for contributions if anyone would like to pitch in.

**Comment by sachinprasadhs** [comment]
Hi, Could you please migrate from Estimator to Keras API which will enable you to perform the aforementioned tasks, such as [model building](https://www.tensorflow.org/guide/keras/custom_layers_and_models), gradient application, [training](https://www.tensorflow.org/guide/keras/customizing_what_happens_in_fit), evaluation, and prediction.
Refer Migration guide here https://www.tensorflow.org/guide/migrate/migrating_estimator for more details. Thanks!
