### ISSUE TITLE
Problem when try to decode some bmp images with tf.image.decode_bmp

### ISSUE THREAD

**Issue by VenkateshSatagopan** [tensorflow/tensorflow#23085]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:NA
- TensorFlow installed from (source or binary): PIP
- TensorFlow version (use command below):1.12
- Python version:3.6
- Bazel version (if compiling from source):No
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version NO
- GPU model and memory: Not using GPU

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**
Hi,
I have written a python script to read bmp image from local drive using tensorflow and trying to display the image. 

First case:
I am getting error when i try to use the 
below command - tf.image.decode_bmp(image_string,channels=3)

The error is as below:

Traceback (most recent call last):
  File "/home/venkatesh/anaconda3/envs/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/home/venkatesh/anaconda3/envs/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/venkatesh/anaconda3/envs/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: channels attribute 3 does not match bits per pixel from file 4
	 [[{{node DecodeBmp}} = DecodeBmp[channels=3](ReadFile)]]
	 [[{{node IteratorGetNext}} = IteratorGetNext[output_shapes=[[?,?,3]], output_types=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](OneShotIterator)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/venkatesh/Desktop/Image_processing_thesis/Thesis_deep_learning/problem_tensorfile.py", line 38, in <module>
    res = sess.run(patches)
  File "/home/venkatesh/anaconda3/envs/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/venkatesh/anaconda3/envs/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/venkatesh/anaconda3/envs/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/venkatesh/anaconda3/envs/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: channels attribute 3 does not match bits per pixel from file 4
	 [[{{node DecodeBmp}} = DecodeBmp[channels=3](ReadFile)]]
	 [[node IteratorGetNext (defined at /home/venkatesh/Desktop/Image_processing_thesis/Thesis_deep_learning/problem_tensorfile.py:35)  = IteratorGetNext[output_shapes=[[?,?,3]], output_types=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](OneShotIterator)]]

Process finished with exit code 1

Second case:
If i use the command tf.image.decode_bmp(image_string) instead of tf.image.decode_bmp(image_string,channels=3) 

I am not getting error but when i see the shape , it's showing the no of channels =4 and not 3.  I want to know why I am getting shape =4 for the second case and why getting error for some images for the first case.

For example consider 00001.bmp Image(attached in attachments) size:
Height=351
Width=572
channels=3
is getting shape(351,572,4) for the second case.

Additionally
All the images works fine without tensorflow
For example: I used scipy to read the image and try to print the shapes of all images in which the no of channels are 3 and not 4.

The image which i used is one of the images form waterloo exploratory dataset. In the first 50 images i have faced the above issue for 5 images and tf.image.decode_bmp works for remaining 45 images.

Please use the below link if you like to download the waterloo exploratory dataset :
[https://ece.uwaterloo.ca/~k29ma/exploration/](url)
**Describe the expected behavior**
Requires information about why the above error is getting displayed for some of bmp images.

**Code to reproduce the issue**
import tensorflow as tf
import numpy as np
from scipy import misc
import glob
import os
#Command to extract all file names
list_ground_truth=glob.glob("Truth_Images/*.bmp")  

num_parallel_calls=4

def parse_fn(filename):
    """Decode the jpeg image from the filename and convert to [0, 1]."""
    image_string = tf.read_file(filename)
    image_decoded = tf.image.decode_bmp(image_string,channels=3)
    #print(image_decoded.get_shape().dims)
    # This will convert to float values in [0, 1]
    image = tf.image.convert_image_dtype(image_decoded, tf.float32)
    return image

# Create a dataset
dataset = (tf.data.Dataset.from_tensor_slices(list_ground_truth)
           .map(parse_fn, num_parallel_calls=num_parallel_calls)
           .prefetch(1))

iterator = dataset.make_one_shot_iterator()
patches = iterator.get_next()
sess = tf.Session()
res = sess.run(patches)
print(res.shape)
misc.imshow(res)
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

1. Load the above script. 
2. Change the location in the below command to where the image file which i have attached 
list_ground_truth=glob.glob("Truth_Images/*.bmp")  
3.Run the script and if it runs without error.

[problem_files.zip](https://github.com/tensorflow/tensorflow/files/2493751/problem_files.zip)

**Other info / logs**
Additional information:
I am trying the process as part of initial data preparation for training a convolutional network. To make it simple i have removed the unnecessary steps for recreating the issue.

Thanks,
Venkatesh.S
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Exact command to reproduce

**Comment by wt-huang** [comment]
@VenkateshSatagopan The output from `tf.image.decode_bmp()` is correct and the number of channels should equal to 4. Basically, channel(=4) corresponds to RGBA whereas channel(=3) corresponds to RGB. Your image is RGBA where A denotes opacity.

**Comment by VenkateshSatagopan** [comment]
@wt-huang Thanks for the response. 
I tried to find the shape(for finding the no of channels) of the image using scipy and opencv before using tensorflow 
In both scipy and opencv when i read image and print it's shape it shows the no of channels as 3 and not 4.
It will be helpful if you can explain  how you have decided the images to be RGBA image and not RGB image

**Comment by wt-huang** [comment]
@VenkateshSatagopan Actually you are correct, I was looking at different images. Your attached images should be RGB, confirmed using scipy, opencv and PIL. When running the above code snippet with the following line

`image_decoded = tf.image.decode_bmp(image_string, channels = 3)`

I didn't encounter the error you mentioned from my end. Could you verify that the other images had no issues with this code snippet?

**Comment by VenkateshSatagopan** [comment]
@wt-huang I checked with other images among first 50 images of WED dataset and I
 am not finding issue when i execute the code

As i said earlier I am having issue with images 1,11,18,32,47 among first 50 images.

I am not facing issue for the above images(1,11,18,32,47) when i try to specify channels=4 in the code.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @wt-huang: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by gadagashwini** [comment]
Hi @VenkateshSatagopan, As @wt-huang commented, channel=4 represents RGBA images. 
```
tf.io.decode_bmp(
    contents, channels=0, name=None
)
```
Channels accepts 

> 3: output an RGB image.
> 4: output an RGBA image. 

Looks like you are mixing up RGB and RGBA images. Make sure use same type of images from your directory. Thank you!
