### ISSUE TITLE
Error while calling TFLite interpreter (Similar to #21574)

### ISSUE THREAD

**Issue by saurabh-kachhia** [tensorflow/tensorflow#23082]
**Tensorflow Version: 1.11.0
Python Version: 3.4 (Also tried with 2.7)**

I tried to install Tensorflow **using PIP install** on my Raspberry Pi3 B+ (Raspbian Stretch - June 2018 Version) and when I tried to run the sample [label_image.py ](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/lite/examples/python/label_image.py)example with TFLite model file I am getting this error -

```
Traceback (most recent call last):
  File "label_image.py", line 37, in <module>
    interpreter = tf.contrib.lite.Interpreter(model_path=args.model_file)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/contrib/lite/python/interpreter.py", line 52, in __init__
    _interpreter_wrapper.InterpreterWrapper_CreateWrapperCPPFromFile(
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/util/lazy_loader.py", line 53, in __getattr__
    module = self._load()
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/util/lazy_loader.py", line 42, in _load
    module = importlib.import_module(self.__name__)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/contrib/lite/python/interpreter_wrapper/tensorflow_wrap_interpreter_wrapper.py", line 28, in <module>
    _tensorflow_wrap_interpreter_wrapper = swig_import_helper()
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/contrib/lite/python/interpreter_wrapper/tensorflow_wrap_interpreter_wrapper.py", line 24, in swig_import_helper
    _mod = imp.load_module('_tensorflow_wrap_interpreter_wrapper', fp, pathname, description)
  File "/usr/lib/python3.4/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
ImportError: /usr/local/lib/python3.4/dist-packages/tensorflow/contrib/lite/python/interpreter_wrapper/_tensorflow_wrap_interpreter_wrapper.so: undefined symbol: _ZN6tflite12tensor_utils24NeonVectorScalarMultiplyEPKaifPf

```

I also tried another way and build the **Cross Compile Package** using latest Tensorflow code from master branch and install the package on pi. After running the [same example](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/lite/examples/python/label_image.py) I am facing this error -

```
Traceback (most recent call last):
  File "label_image.py", line 37, in <module>
    interpreter = tf.contrib.lite.Interpreter(model_path=args.model_file)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/util/lazy_loader.py", line 53, in __getattr__
    module = self._load()
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/util/lazy_loader.py", line 42, in _load
    module = importlib.import_module(self.__name__)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/contrib/__init__.py", line 48, in <module>
    from tensorflow.contrib import distribute
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/contrib/distribute/__init__.py", line 34, in <module>
    from tensorflow.contrib.distribute.python.tpu_strategy import TPUStrategy
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/contrib/distribute/python/tpu_strategy.py", line 27, in <module>
    from tensorflow.contrib.tpu.python.ops import tpu_ops
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/contrib/tpu/__init__.py", line 69, in <module>
    from tensorflow.contrib.tpu.python.ops.tpu_ops import *
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/contrib/tpu/python/ops/tpu_ops.py", line 39, in <module>
    resource_loader.get_path_to_datafile("_tpu_ops.so"))
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/contrib/util/loader.py", line 56, in load_op_library
    ret = load_library.load_op_library(path)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/load_library.py", line 60, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)

tensorflow.python.framework.errors_impl.InvalidArgumentError: Invalid name: 

An op that loads optimization parameters into HBM for embedding. Must be
preceded by a ConfigureTPUEmbeddingHost op that sets up the correct
embedding table configuration. For example, this op is used to install
parameters that are loaded from a checkpoint before a training loop is
executed.
```
So none of the provided methods are working for me.

**Comment by ymodak** [comment]
I think it will be better if you create a new issue expressing the problem you are facing. The reason for that is the previous issue was created by different user which may be addressed by TensorFlow team or else user must have found a workaround himself. By opening new issue we can focus on your specific problem and will help us to keep track of issues we are committing to. Thanks!

**Comment by PINTO0309** [comment]
@saurabh-kachhia 
I resolved it by native build on RaspberryPi.
The official pip package is broken.
https://github.com/PINTO0309/Tensorflow-bin.git

**Comment by ymodak** [comment]
@saurabh-kachhia  Please post your findings after trying PINTO0309's suggestion. Thanks!

> @saurabh-kachhia
> I resolved it by native build on RaspberryPi (Raspbian Stretch).
> The official pip package is broken.
> 
> **For Python2.7 or Python3.5**
> https://github.com/PINTO0309/Tensorflow-bin.git
> 
> I tried implementing "Tenforflow Lite UNet" to RaspberryPi.
> https://github.com/PINTO0309/TensorflowLite-UNet.git

**Comment by saurabh-kachhia** [comment]
@PINTO0309 Thanks a lot for sharing .whl files. It fixed my issue. 

@ymodak Yes, it resolved the issue, but the official build and cross compiling of the package are still broken. Is there any update on it?

**Comment by tensorflowbutler** [comment]
Nagging Assignees @petewarden, @aselle: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by thedch** [comment]
Just ran into this error as well, @PINTO0309 solution fixes it... thanks!

**Comment by aselle** [comment]
Cross compiling to the raspberry pi tends to be pretty tricky to get right and is somewhat fragile. Unfortunately, it is quite difficult to build Tensorflow natively in a reasonable amount of time. We'll see if we can work on getting this resolved.

**Comment by PINTO0309** [comment]
@saurabh-kachhia 

Prebuilt binary for TensorflowLite's standalone installer. For RaspberryPi.

**Tensorflow Lite v1.12.0 rc0, Binary Size=1.1MB**
**https://github.com/PINTO0309/TensorflowLite-bin.git**

Thank you, @aselle !!

**Comment by brunolinux** [comment]
@PINTO0309, when build the newest version of tf-lite runtime python package, I have the same problem like you. 
So the tf lite runtime whl of your repo: https://github.com/PINTO0309/TensorflowLite-bin.git can work or not ?

**Comment by PINTO0309** [comment]
@brunolinux 

If you allow v1.11.0, it should work fine.
Please try first.
By the way, I am currently concentrating on other tasks, so I do not plan to build at v1.12.0 immediately.
It takes 30 hours or more to perform the regular build procedure.

**Comment by bennuttall** [comment]
I'm the maintainer of the piwheels.org project which hosts the Raspberry Pi TF wheels (built by the TF team).

Please note that the neon instructions differ between 2836 and 2837, therefore the armv7l wheel won't work on 2836. The original Pi 2 was 2836 but after the Pi 3 came out, any Pi 2s made had the 2837 on them. So there's only a limited supply of 2836 in the world. However, the armv6l wheels will work on 2836 (and 2837).

To install the armv6l wheels on a Pi 2/3:

```bash
wget https://www.piwheels.org/simple/tensorflow/tensorflow-1.11.0-cp35-none-linux_armv6l.whl
mv tensorflow-1.11.0-cp35-none-linux_armv6l.whl tensorflow-1.11.0-cp35-none-linux_armv7l.whl
sudo pip3 install tensorflow-1.11.0-cp35-none-linux_armv7l.whl
```

**Comment by Mark84** [comment]
@PINTO0309 @aselle This still doesn't seem to work, latest pip packages still broken on RPi 3b+. Any updates?

**Comment by PINTO0309** [comment]
@Mark84 
Informally, I generated the wheel package for Tensorflow v2.0.0-alpha.
**https://github.com/PINTO0309/Tensorflow-bin**
**tensorflow-2.0.0a0-cp35-cp35m-linux_armv7l.whl**

I have not built v1.12.0 and v1.13.1.

**Comment by Mark84** [comment]
@PINTO0309 Didn’t try the alpha, but did try the 1.11 version, but I need the tensorflow.lite package which isn’t included as it’s broken still?

**Comment by PINTO0309** [comment]
@Mark84 
The official package is broken, but the package I created works fine.
```console
$ sudo apt-get install -y libhdf5-dev libc-ares-dev libeigen3-dev
$ sudo pip3 install keras_applications==1.0.7 --no-deps
$ sudo pip3 install keras_preprocessing==1.0.9 --no-deps
$ sudo pip3 install h5py==2.9.0
$ sudo apt-get install -y openmpi-bin libopenmpi-dev
$ sudo pip3 uninstall tensorflow
$ wget -O tensorflow-1.11.0-cp35-cp35m-linux_armv7l.whl https://github.com/PINTO0309/Tensorflow-bin/raw/master/tensorflow-1.11.0-cp35-cp35m-linux_armv7l_jemalloc_multithread.whl
$ sudo pip3 install tensorflow-1.11.0-cp35-cp35m-linux_armv7l.whl

【Required】 Restart the terminal.
```

**Comment by Mark84** [comment]
@PINTO0309 
Following those steps exactly and then
Using example label_image.py : from : tensorflow/tensorflow/lite/examples/python/label_image.py
      
(.venv):~/tensor_example $ python3 label_image.py 
Traceback (most recent call last):
  File "label_image.py", line 26, in <module>
    from tensorflow.lite.python import interpreter as interpreter_wrapper
ImportError: No module named 'tensorflow.lite'

**Comment by zaichang** [comment]
@PINTO0309 
Thanks for providing the package! For me your package worked after having run into problems with the installation stalling during numpy and h5py. Ended up solving that by downloading the wheels and installing them manually, in case it helps anyone else:

```
wget -O numpy-1.16.1-cp35-cp35m-linux_armv7l.whl https://www.piwheels.hostedpi.com/simple/numpy/numpy-1.16.1-cp35-cp35m-linux_armv7l.whl
pip3 install numpy-1.16-1.whl

wget -O h5py-2.9.0-cp35-cp35m-linux_armv7l.whl https://www.piwheels.org/simple/h5py/h5py-2.9.0-cp35-cp35m-linux_armv7l.whl
pip3 install h5py-2.9.0-cp35-cp35m-linux_armv7l.whl --no-deps

pip3 install tensorflow-1.11.0-cp35-cp35m-linux_armv7l.whl --no-deps
```

**Comment by PINTO0309** [comment]
@zaichang 
Thanks for the feedback!
I will update the installation procedure.

**Comment by zaichang** [comment]
@PINTO0309 
I'm not sure if that my amendments should be part of the official installation procedure as I'm not sure if the problem I faced is isolated to my setup (I did not start from a fresh image). But maybe it'd help someone out there

**Comment by wangzhihua520** [comment]
Hi，@PINTO0309 @aselle 

How to solve the problem:

Python3.5 ---> The __init__.py description is inappropriate and results in an import error.

pi@raspberrypi:~/TensorflowLite-UNet $ python3 tflite_test.py 
Traceback (most recent call last):
  File "tflite_test.py", line 4, in <module>
    import tflite_runtime as tflr
  File "/usr/local/lib/python3.5/dist-packages/tflite_runtime/__init__.py", line 1, in <module>
    import tflite_runtime.lite.interpreter
  File "/usr/local/lib/python3.5/dist-packages/tflite_runtime/lite/__init__.py", line 1, in <module>
    from interpreter import Interpreter as Interpreter
ImportError: No module named 'interpreter'

Best Regards

**Comment by PINTO0309** [comment]
@wangzhihua520 
```
# Tensorflow v1.12.0
from tensorflow.contrib.lite.python import interpreter as ip
```
or
```
# Tensorflow v1.13.0
from tensorflow.lite.python import interpreter as ip
```
```
interpreter = ip.Interpreter(model_path=<model_file_path>)
```

**Comment by wangzhihua520** [comment]
Dear @PINTO0309 

Thank you very much for your help.

I just follow the instruction: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/pip_package
to deploy Tensorflow Lite interpreter and use it from python without requiring the rest of Tensorflow. As your suggestion, I should install the total version of tensorflow, is it right?

If so, where I can download the total version of tensorflow?  To do as 

wget -O numpy-1.16.1-cp35-cp35m-linux_armv7l.whl https://www.piwheels.hostedpi.com/simple/numpy/numpy-1.16.1-cp35-cp35m-linux_armv7l.whl
pip3 install numpy-1.16-1.whl

wget -O h5py-2.9.0-cp35-cp35m-linux_armv7l.whl https://www.piwheels.org/simple/h5py/h5py-2.9.0-cp35-cp35m-linux_armv7l.whl
pip3 install h5py-2.9.0-cp35-cp35m-linux_armv7l.whl --no-deps

pip3 install tensorflow-1.11.0-cp35-cp35m-linux_armv7l.whl --no-deps

Best regasrds

Zhihua

**Comment by PINTO0309** [comment]
@wangzhihua520
Although it is an unofficial package, please try the following.
It's a full build package, but its introduction is very easy.
**https://github.com/PINTO0309/Tensorflow-bin**

For armv7l.

**`Tensorflow v1.11.0`**
or
**`Tensorflow v1.13.1`**
or
**`Tensorflow v2.0.0 alpha`**

If that doesn't work, try rebuilding Tensorflow yourself, referring to the working sequence in my repository.
I built a full Tensorflow using RaspberryPi3. (Native Build)
**https://github.com/PINTO0309/Tensorflow-bin#build-parameter**
You may need to adjust the parameters depending on your device environment.

**Comment by rajurimu** [comment]
> @wangzhihua520
> Although it is an unofficial package, please try the following.
> It's a full build package, but its introduction is very easy.
> **https://github.com/PINTO0309/Tensorflow-bin**
> 
> For armv7l.
> 
> **`Tensorflow v1.11.0`**
> or
> **`Tensorflow v1.13.1`**
> or
> **`Tensorflow v2.0.0 alpha`**
> 
> If that doesn't work, try rebuilding Tensorflow yourself, referring to the working sequence in my repository.
> I built a full Tensorflow using RaspberryPi3. (Native Build)
> **https://github.com/PINTO0309/Tensorflow-bin#build-parameter**
> You may need to adjust the parameters depending on your device environment.
> 
> I can not try because I do not own "NanoPi".

Hello,

I am trying to deploy TFlite standalone (without TF) on RPi zero and struggling.  I tried https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/pip_package, however it is slow on RPi0 so I tried on RPi4 and getting errors. Goal was to build a whl on RPi4 so that the process is validated and then try on RPi0 (with different architecture).

**Comment by mohantym** [comment]
Hi @saurabh-kachhia ,  
We see that you are using old version of Tensorflow which is officially considered as end of life, We recommend that you upgrade to 2.6 version and let us know if the issue still persists in newer versions .Please open a new issue in case you face any errors, we will get you the right help .Thanks!
