### ISSUE TITLE
I get error when I want to load my Model

### ISSUE THREAD

**Issue by hamidrezafazlali** [tensorflow/tensorflow#23108]
I am building a deep CNN and I get my graph files by running my code on a GPU on cluster. The training procedure work perfect. Then I move my graph files to my laptop to build this network on my laptop which has CPU. But when I try to load the model I receive the following error:

Traceback (most recent call last): File "dev_test.py", line 28, in new_saver = tf.train.import_meta_graph('./3/Model_Arch3/Deep_CNN_Color_Arch8.ckpt-178000.meta') File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1810, in import_meta_graph **kwargs) File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/meta_graph.py", line 660, in import_scoped_meta_graph producer_op_list=producer_op_list) File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/importer.py", line 285, in import_graph_def raise ValueError('No op named %s in defined operations.' % node.op) ValueError: No op named ParseSingleExample in defined operations.

The strange thing is that when I train this network on my laptop using my CPU, then I can load the model without any problem!

Also I can build the graph and load the model successfully on the GPU cluster where I trained it! 

I tried the dir(tf.contrib) solution that was suggested in other question, but it did not work for me.

I really appreciate if someone helps me

**Comment by blueeda** [comment]
Maybe the problem is from the verison of tf?

**Comment by wt-huang** [comment]
@blueeda is correct. Make sure you have the same tf version between CPU and GPU, you can provide more details by filling out the issue template.
