### ISSUE TITLE
CAN'T BUILD TENSORFLOW

### ISSUE THREAD

**Issue by WagnerCaetano** [tensorflow/tensorflow#23142]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):WINDOWS 7 64
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: r1.11
- Python version: 3.7
- Installed using virtualenv? pip? conda?: PIP
- Bazel version (if compiling from source): 0.18.0
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:  not using
- GPU model and memory:

I cant build tensorflow because happens some error about@png_archive

`C:\Users\00\tensorflow>bazel build --config=opt //tensorflow/tools/pip_package:
uild_pip_package
WARNING: Processed legacy workspace file c:\users\00\tensorflow/tools/bazel.rc.
This file will not be processed in the next release of Bazel. Please read https
//github.com/bazelbuild/bazel/issues/6319 for further information, including ho
 to upgrade.
WARNING: Option 'experimental_shortened_obj_file_path' is deprecated
Loading:
Loading: 0 packages loaded
INFO: Build options have changed, discarding analysis cache.
Analyzing: target //tensorflow/tools/pip_package:build_pip_package (0 packages
oaded)
Analyzing: target //tensorflow/tools/pip_package:build_pip_package (0 packages
oaded)
Analyzing: target //tensorflow/tools/pip_package:build_pip_package (0 packages
oaded)
Analyzing: target //tensorflow/tools/pip_package:build_pip_package (0 packages
oaded)
Analyzing: target //tensorflow/tools/pip_package:build_pip_package (0 packages
oaded)
Analyzing: target //tensorflow/tools/pip_package:build_pip_package (0 packages
oaded)
Analyzing: target //tensorflow/tools/pip_package:build_pip_package (0 packages
oaded)
Analyzing: target //tensorflow/tools/pip_package:build_pip_package (0 packages
oaded)
Analyzing: target //tensorflow/tools/pip_package:build_pip_package (0 packages
oaded)
ERROR: C:/users/00/tensorflow/tensorflow/core/platform/default/build_config/BUI
D:188:1: no such package '@png_archive//': Traceback (most recent call last):
        File "C:/users/00/tensorflow/third_party/repo.bzl", line 106
                _apply_patch(ctx, ctx.attr.patch_file)
        File "C:/users/00/tensorflow/third_party/repo.bzl", line 73, in _apply_
atch
                _execute_and_check_ret_code(ctx, cmd)
        File "C:/users/00/tensorflow/third_party/repo.bzl", line 52, in _execut
_and_check_ret_code
                fail("Non-zero return code({1}) when ...))
Non-zero return code(127) when executing 'E:\MSYS2\usr\bin\bash.exe -l -c patch
-p1 -d C:/users/00/_bazel_00/xjibpket/external/png_archive -i C:/users/00/tenso
flow/third_party/png_fix_rpi.patch':
Stdout:
Stderr: /usr/bin/bash: patch: comando n├úo encontrado
 and referenced by '//tensorflow/core/platform/default/build_config:png'
Analyzing: target //tensorflow/tools/pip_package:build_pip_package (0 packages
oaded)
ERROR: C:/users/00/tensorflow/tensorflow/core/platform/default/build_config/BUI
D:188:1: no such package '@png_archive//': Traceback (most recent call last):
        File "C:/users/00/tensorflow/third_party/repo.bzl", line 106
                _apply_patch(ctx, ctx.attr.patch_file)
        File "C:/users/00/tensorflow/third_party/repo.bzl", line 73, in _apply_
atch
                _execute_and_check_ret_code(ctx, cmd)
        File "C:/users/00/tensorflow/third_party/repo.bzl", line 52, in _execut
_and_check_ret_code
                fail("Non-zero return code({1}) when ...))
Non-zero return code(127) when executing 'E:\MSYS2\usr\bin\bash.exe -l -c patch
-p1 -d C:/users/00/_bazel_00/xjibpket/external/png_archive -i C:/users/00/tenso
flow/third_party/png_fix_rpi.patch':
Stdout:
Stderr: /usr/bin/bash: patch: comando n├úo encontrado
 and referenced by '//tensorflow/core/platform/default/build_config:png'
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' fa
led; build aborted: Analysis failed
Analyzing: target //tensorflow/tools/pip_package:build_pip_package (0 packages
oaded)
ERROR: C:/users/00/tensorflow/tensorflow/core/platform/default/build_config/BUI
D:188:1: no such package '@png_archive//': Traceback (most recent call last):
        File "C:/users/00/tensorflow/third_party/repo.bzl", line 106
                _apply_patch(ctx, ctx.attr.patch_file)
        File "C:/users/00/tensorflow/third_party/repo.bzl", line 73, in _apply_
atch
                _execute_and_check_ret_code(ctx, cmd)
        File "C:/users/00/tensorflow/third_party/repo.bzl", line 52, in _execut
_and_check_ret_code
                fail("Non-zero return code({1}) when ...))
Non-zero return code(127) when executing 'E:\MSYS2\usr\bin\bash.exe -l -c patch
-p1 -d C:/users/00/_bazel_00/xjibpket/external/png_archive -i C:/users/00/tenso
flow/third_party/png_fix_rpi.patch':
Stdout:
Stderr: /usr/bin/bash: patch: comando n├úo encontrado
 and referenced by '//tensorflow/core/platform/default/build_config:png'
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' fa
led; build aborted: Analysis failed
INFO: Elapsed time: 9,864s
Analyzing: target //tensorflow/tools/pip_package:build_pip_package (0 packages
oaded)
ERROR: C:/users/00/tensorflow/tensorflow/core/platform/default/build_config/BUI
D:188:1: no such package '@png_archive//': Traceback (most recent call last):
        File "C:/users/00/tensorflow/third_party/repo.bzl", line 106
                _apply_patch(ctx, ctx.attr.patch_file)
        File "C:/users/00/tensorflow/third_party/repo.bzl", line 73, in _apply_
atch
                _execute_and_check_ret_code(ctx, cmd)
        File "C:/users/00/tensorflow/third_party/repo.bzl", line 52, in _execut
_and_check_ret_code
                fail("Non-zero return code({1}) when ...))
Non-zero return code(127) when executing 'E:\MSYS2\usr\bin\bash.exe -l -c patch
-p1 -d C:/users/00/_bazel_00/xjibpket/external/png_archive -i C:/users/00/tenso
flow/third_party/png_fix_rpi.patch':
Stdout:
Stderr: /usr/bin/bash: patch: comando n├úo encontrado
 and referenced by '//tensorflow/core/platform/default/build_config:png'
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' fa
led; build aborted: Analysis failed
INFO: Elapsed time: 9,864s
INFO: 0 processes.
Analyzing: target //tensorflow/tools/pip_package:build_pip_package (0 packages
oaded)
ERROR: C:/users/00/tensorflow/tensorflow/core/platform/default/build_config/BUI
D:188:1: no such package '@png_archive//': Traceback (most recent call last):
        File "C:/users/00/tensorflow/third_party/repo.bzl", line 106
                _apply_patch(ctx, ctx.attr.patch_file)
        File "C:/users/00/tensorflow/third_party/repo.bzl", line 73, in _apply_
atch
                _execute_and_check_ret_code(ctx, cmd)
        File "C:/users/00/tensorflow/third_party/repo.bzl", line 52, in _execut
_and_check_ret_code
                fail("Non-zero return code({1}) when ...))
Non-zero return code(127) when executing 'E:\MSYS2\usr\bin\bash.exe -l -c patch
-p1 -d C:/users/00/_bazel_00/xjibpket/external/png_archive -i C:/users/00/tenso
flow/third_party/png_fix_rpi.patch':
Stdout:
Stderr: /usr/bin/bash: patch: command not found
 and referenced by '//tensorflow/core/platform/default/build_config:png'
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' fa
led; build aborted: Analysis failed
INFO: Elapsed time: 9,864s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
Analyzing: target //tensorflow/tools/pip_package:build_pip_package (0 packages
oaded)
ERROR: C:/users/00/tensorflow/tensorflow/core/platform/default/build_config/BUI
D:188:1: no such package '@png_archive//': Traceback (most recent call last):
        File "C:/users/00/tensorflow/third_party/repo.bzl", line 106
                _apply_patch(ctx, ctx.attr.patch_file)
        File "C:/users/00/tensorflow/third_party/repo.bzl", line 73, in _apply_
atch
                _execute_and_check_ret_code(ctx, cmd)
        File "C:/users/00/tensorflow/third_party/repo.bzl", line 52, in _execut
_and_check_ret_code
                fail("Non-zero return code({1}) when ...))
Non-zero return code(127) when executing 'E:\MSYS2\usr\bin\bash.exe -l -c patch
-p1 -d C:/users/00/_bazel_00/xjibpket/external/png_archive -i C:/users/00/tenso
flow/third_party/png_fix_rpi.patch':
Stdout:
Stderr: /usr/bin/bash: patch: command not found
 and referenced by '//tensorflow/core/platform/default/build_config:png'
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' fa
led; build aborted: Analysis failed
INFO: Elapsed time: 9,864s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
Analyzing: target //tensorflow/tools/pip_package:build_pip_package (0 packages
oaded)
ERROR: C:/users/00/tensorflow/tensorflow/core/platform/default/build_config/BUI
D:188:1: no such package '@png_archive//': Traceback (most recent call last):
        File "C:/users/00/tensorflow/third_party/repo.bzl", line 106
                _apply_patch(ctx, ctx.attr.patch_file)
        File "C:/users/00/tensorflow/third_party/repo.bzl", line 73, in _apply_
atch
                _execute_and_check_ret_code(ctx, cmd)
        File "C:/users/00/tensorflow/third_party/repo.bzl", line 52, in _execut
_and_check_ret_code
                fail("Non-zero return code({1}) when ...))
Non-zero return code(127) when executing 'E:\MSYS2\usr\bin\bash.exe -l -c patch
-p1 -d C:/users/00/_bazel_00/xjibpket/external/png_archive -i C:/users/00/tenso
flow/third_party/png_fix_rpi.patch':
Stdout:
Stderr: /usr/bin/bash: patch: command not found
 and referenced by '//tensorflow/core/platform/default/build_config:png'
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' fa
led; build aborted: Analysis failed
INFO: Elapsed time: 9,864s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
Analyzing: target //tensorflow/tools/pip_package:build_pip_package (0 packages
oaded)
ERROR: C:/users/00/tensorflow/tensorflow/core/platform/default/build_config/BUI
D:188:1: no such package '@png_archive//': Traceback (most recent call last):
        File "C:/users/00/tensorflow/third_party/repo.bzl", line 106
                _apply_patch(ctx, ctx.attr.patch_file)
        File "C:/users/00/tensorflow/third_party/repo.bzl", line 73, in _apply_
atch
                _execute_and_check_ret_code(ctx, cmd)
        File "C:/users/00/tensorflow/third_party/repo.bzl", line 52, in _execut
_and_check_ret_code
                fail("Non-zero return code({1}) when ...))
Non-zero return code(127) when executing 'E:\MSYS2\usr\bin\bash.exe -l -c patch
-p1 -d C:/users/00/_bazel_00/xjibpket/external/png_archive -i C:/users/00/tenso
flow/third_party/png_fix_rpi.patch':
Stdout:
Stderr: /usr/bin/bash: patch: command not found
 and referenced by '//tensorflow/core/platform/default/build_config:png'
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' fa
led; build aborted: Analysis failed
INFO: Elapsed time: 9,864s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
`

**Comment by gokul-uf** [comment]
Seems like you don't have the `patch` command installed

**Comment by MartinRe63** [comment]
You should use pacman to install patch of msys2 and should ensure that the path to patch is available. msys2 should use the path of the system

**Comment by WagnerCaetano** [comment]
I installed patch with pacman , but it still not working..

`
1 error detected in the compilation of "C:/Users/00/AppData/Local/Temp/nvcc_inter_files_tmp_dir/extract_image_patches_op_gpu.cu.cpp1.ii".
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 427,427s, Critical Path: 77,24s
INFO: 368 processes: 368 local.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully

C:\Users\00\tensorflow>`

**Comment by tensorflowbutler** [comment]
Nagging Assignee @harshini-gadige: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by gunan** [comment]
I think this is a duplicate issue, assigning to @meteorcloudy, who took a look at the other ones.

**Comment by meteorcloudy** [comment]
@WagnerCaetano Can you show me the exact compilation error?

**Comment by WagnerCaetano** [comment]
Compilation Error: https://pastebin.com/WtdtJNke

**Comment by meteorcloudy** [comment]
Looks like you are encountering https://github.com/tensorflow/tensorflow/issues/19198

**Comment by mohantym** [comment]
We see that you are using old version of Tensorflow which is officially considered as end of life, We recommend that you upgrade to 2.5  version or later and let us know if the issue still persists in newer versions .Please open a new issue in case you face any errors, we will get you the right help .Thanks!
