### ISSUE TITLE
tf.layers.dense activity_regularizer= tf.contrib.layers.l2_regularizer(0.0) causes error.

### ISSUE THREAD

**Issue by corynezin** [tensorflow/tensorflow#23160]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): RHEL 7.3
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): binary (pip)
- TensorFlow version (use command below): 1.10
- Python version: 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 9.0 / 7
- GPU model and memory: Tesla k80

**Describe the current behavior**
Setting the activity regularizer of a tf.layers.dense layer to tf.contrib.layers.l2_regularizer(0.0) gives the error:
ValueError: None values not supported.

**Describe the expected behavior**
No error should be thrown - the regularizer should be disabled.
**Code to reproduce the issue**
x = tf.placeholder(tf.float32, (64,100))
layer = tf.layers.dense(
    x,
    100,
    activation=None,
    kernel_initializer=tf.contrib.layers.xavier_initializer(),
    activity_regularizer=tf.contrib.layers.l2_regularizer(scale=0.0)
)

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

Trace:
Traceback (most recent call last):
  File "<stdin>", line 7, in <module>
  File "/tensorflow/python/layers/core.py", line 189, in dense
    return layer.apply(inputs)
  File "/tensorflow/python/keras/engine/base_layer.py", line 805, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "/tensorflow/python/layers/base.py", line 362, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "/tensorflow/python/keras/engine/base_layer.py", line 758, in __call__
    self._handle_activity_regularization(inputs, outputs)
  File "/tensorflow/python/keras/engine/base_layer.py", line 640, in _handle_activity_regularization
    self.add_loss(activity_regularization, inputs=inputs)
  File "/tensorflow/python/layers/base.py", line 134, in add_loss
    super(Layer, self).add_loss(losses, inputs=inputs)
  File "/tensorflow/python/keras/engine/base_layer.py", line 411, in add_loss
    if not tensor_util.is_tensor(loss) else loss for loss in losses]
  File "/tensorflow/python/keras/engine/base_layer.py", line 411, in <listcomp>
    if not tensor_util.is_tensor(loss) else loss for loss in losses]
  File "/tensorflow/python/framework/ops.py", line 998, in convert_to_tensor
    as_ref=False)
  File "/tensorflow/python/framework/ops.py", line 1094, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/tensorflow/python/framework/constant_op.py", line 217, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/tensorflow/python/framework/constant_op.py", line 196, in constant
    value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/tensorflow/python/framework/tensor_util.py", line 424, in make_tensor_proto
    raise ValueError("None values not supported.")

**Comment by yongtang** [comment]
@corynezin I can reproduce the issue with 1.10 but not with tf-nightly. Can you check the latest version of tf-nightly and see if the issue has been resolved?

**Comment by wt-huang** [comment]
@yongtang is correct, this issue is not in the latest TensorFlow version either.

**Comment by wt-huang** [comment]
Closing as this is resolved

**Comment by PeterMitrano** [comment]
I have this issue in 1.13.1

Code to reproduce:
```
#!/usr/bin/env python
import numpy as np
import tensorflow
from tensorflow import keras

tensorflow.enable_eager_execution()

dense = keras.layers.Dense(8, activity_regularizer=keras.regularizers.l1(0.0))
out = dense(np.random.randn(1,16))
print(out)
```

The error I get:
```
Traceback (most recent call last):
  File "./test.py", line 9, in <module>
    out = dense(np.random.randn(1,16))
  File "/home/pmitrano/.local/opt/anaconda3/envs/ros1py3/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 593, in __call__
    self._handle_activity_regularization(inputs, outputs)
  File "/home/pmitrano/.local/opt/anaconda3/envs/ros1py3/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1345, in _handle_activity_regularization
    array_ops.shape(output)[0], activity_loss.dtype)
AttributeError: 'float' object has no attribute 'dtype'
```
