### ISSUE TITLE
"Invalid loop structure. Mismatched parent frames"

### ISSUE THREAD

**Issue by carlini** [tensorflow/tensorflow#23166]
Computing the gradient through a batch normalization layer as implemented in keras with a batch size of None while in a tf.while loop can cause the following error:

"tensorflow.python.framework.errors_impl.InvalidArgumentError: Invalid loop structure: Mismatched parent frames for "while/while_context": "while/while_context" vs "". This is an internal bug, please file a bug report with instructions on how to reproduce the error"

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution: Ubuntu 16.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): Reproducible using the latest release [v1.12.0-rc1-0-g7b08198113 1.12.0-rc1] through back to at least 1.10.0.
- Python version: 3.5.2
- CUDA/cuDNN version: Reproducible without CUDA.
- GPU model and memory: Reproducible without any GPUs.

Current Behavior: running the below script throws a really bad error.

Expected Behavior: it crashes, but not with this error.

**Code to reproduce the issue**

This is the minimal example that I can get to cause a crash. It isn't "correct" code in that it shouldn't work, but it shouldn't crash because of mismatched parent frames. Code that I believe is actually correct also causes the crash, but is much longer.

```python
import numpy as np
import tensorflow as tf
### MUST be keras, not from tensorflow import keras
import keras

if __name__ == "__main__":
  sess = keras.backend.get_session()

  ### I can't reproduce this with tf.layers.batch_normalization
  model = keras.models.Sequential([keras.layers.BatchNormalization(input_shape=(1,))])
  ### This next line MUST have the None, otherwise it doesn't crash
  x = tf.placeholder(tf.float32, (None, 1))

  eta = tf.zeros(tf.shape(x))
  def cond(i, _):
    return tf.less(i, 10)
  def body(i, e):
    preds = model(x+e)
    return i + 1, tf.gradients(preds, x)[0]

  _, eta = tf.while_loop(cond, body, [tf.zeros([]), eta])

  sess.run(eta, {x: np.zeros((128,1))})
```

**Other info / logs**

```
2018-10-22 17:21:30.132455: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Traceback (most recent call last):
  File "/home/ncarlini/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/home/ncarlini/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/ncarlini/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InternalError: Invalid loop structure: Mismatched parent frames for "while/while_context": "while/while_context" vs "". The node giving this error: {{node while/gradients/while/sequential_1/batch_normalization_1/cond/batchnorm/mul_1_grad/Shape/Enter}}This is an internal bug, please file a bug report with instructions on how to reproduce the error.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bug.py", line 26, in <module>
    sess.run(eta, {x: np.zeros((128,1))})
  File "/home/ncarlini/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/ncarlini/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/ncarlini/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/ncarlini/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Invalid loop structure: Mismatched parent frames for "while/while_context": "while/while_context" vs "". The node giving this error: node while/gradients/while/sequential_1/batch_normalization_1/cond/batchnorm/mul_1_grad/Shape/Enter (defined at bug.py:22) This is an internal bug, please file a bug report with instructions on how to reproduce the error.
```

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Bazel version
Exact command to reproduce
Mobile device

**Comment by tensorflowbutler** [comment]
Nagging Assignee @wt-huang: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by carlini** [comment]
Is there something I can do to help diagnose the bug to make it easier to fix? I (and others, it seems) have been running into this reasonably often recently.

**Comment by carlini** [comment]
[I don't know why it says I unassigned @wt-huang -- I didn't intend to do that if I did somehow]

**Comment by tastenachim** [comment]
I have the same issue when experimenting around with nested while-loops and imported graphs (trying to connect frozen graphs). Esp. I use an imported graph containing a while-loop inside a while body:

Completely standalone example:
in short (pseudocode):
```
with innerGraph:
    inner_results = tf.while(...)

with outerGraph:
    def outer_body():
        tf.import_graph_def(innerGraph.as_graph_def(), ...)
        ...
   def outer_condition(): ...
   outer_results = tf.while( outer_condition, outer_body, ...)

   with sess:
        sess.run(outer_results)
```

and in python:
```
import tensorflow as tf


myInnerGraph = tf.Graph()
with myInnerGraph.as_default():

    limit_inner = tf.placeholder(dtype=tf.float32, name="inner_limit")
    def body_inner(counter_inner, my_sum_inner):
        return (counter_inner + 1, my_sum_inner + counter_inner)
    
    def cond_inner(counter_inner, my_sum_inner):
        return counter_inner <= limit_inner

    counter_inner = tf.constant(0, dtype=tf.float32, name="inner_initialCounter")
    my_sum_inner = tf.constant(0, dtype=tf.float32, name="inner_initialSum")
    
    [_, result_inner] = tf.while_loop( 
        cond_inner, 
        body_inner, 
        [counter_inner, my_sum_inner],
        back_prop=False, parallel_iterations=1)
    result_inner = tf.identity(result_inner, name="inner_result")
    

outerGraph = tf.Graph()
with outerGraph.as_default():

    limit = tf.placeholder(dtype=tf.float32, name="limit")
    
    tempVar = tf.Variable(0.0, dtype = tf.float32)
    tempVar.assign(0.0, name='assigner')
    def body(counter, my_sum):
        
        [inner_sum_result] = tf.import_graph_def(myInnerGraph.as_graph_def(),
                            input_map={"inner_limit:0" : counter},
                            return_elements=['inner_result:0'],
                            name="importedGraph",
                            producer_op_list=None
                            )
        assigned = tempVar.assign(inner_sum_result)
        return (counter + 1, my_sum + assigned)

    def cond(counter, my_sum):
        return counter <= limit
    
    my_sum = tf.constant(0, dtype=tf.float32, name="initialSum")
    counter = tf.constant(0, dtype=tf.float32, name="initialCounter")
    [counter_result, my_sum_result] = tf.while_loop( 
            cond, 
            body, 
            [counter, my_sum],
            back_prop=False, parallel_iterations=1)

    my_sum_result = tf.identity(my_sum_result, name = "sum_result")

    #writeBlub = tf.summary.FileWriter('/tmp/', outerGraph); # for tensorBoard
    #tf.train.write_graph(outerGraph.as_graph_def(), '/tmp/', 'example.pbtxt', as_text=True) # for human readable

    with tf.Session() as sess:
        sess.run(tf.global_variables_initializer())
        sess.run(my_assigner)
        sum_value = sess.run(my_sum_result,
                              feed_dict={limit : 5})

```
This throws the mentioned exception. In contrast: Defining the inner loop directly inside the outer_body works fine and produces the expected result (35.0 = sum_{i=0..5}(  i * (i+1) / 2 )

The example code generates a "while/importedGraph/while" namespace. (uncomment and see the exported  `/tmp/exampleGraph.pbtxt`) But the nodes with a `frame_name` attribute in the inner loop still have only attribute `frame_name=while/while_context` where `while/importedGraph/while/while_context` was expected. 

Adjusting the frame_name and reimporting the graphdef fixes the problem. But that's only a dirty workaround and probably only works well with frozen graphs (which contains only a few variables).

hope that helps

**Comment by tastenachim** [comment]
here is even a short script which -- when inserted in the example above right before the Session -- replaces the bogus-`frame_name` on the fly:

```python
def fix_frame_name(op):
    attr_list = list(op.attr.keys())
    if 'frame_name' in attr_list:
        frame_name = op.attr['frame_name']
        if (str(frame_name.s) == "b'while/while_context'" and op.name.count("while") > 1 ):
            idx = op.name.rfind("while")
            prefix = op.name[:idx]
            frame_name.s = bytes(prefix + "while/while_context", 'utf-8')
            print(op.name, frame_name.s) 
    
outerGraphDef = outerGraph.as_graph_def()
for op in outerGraphDef.node:
    fix_frame_name(op)
    
with tf.Graph().as_default():

    [my_sum_result, limit, my_assigner] = tf.import_graph_def(outerGraphDef,
                                input_map=None,
                                return_elements=['sum_result:0', 'limit:0', 'assigner:0'],
                                name="",
                                producer_op_list=None
                                )    
```
But **Warning**: it
* completely exports and reimports the whole graph. 
* probably does not work well with variables/trained model data. 
* has a somewhat handmade bug-recognition
* is only a workaround.

**Comment by Shawn-Shan** [comment]
I encountered the same problem when using Dropout layers rather than BatchNorm. I was able to solve the problem by `K.set_learning_phase(0)`. However, this doesn't work with BatchNorm.

**Comment by carlini** [comment]
@azaks2 is there something we can do to help this move along?

**Comment by cloudseasail** [comment]
@azaks2  is there any workaround we can use?  blocking here for days

**Comment by saxenasaurabh** [comment]
Could you setting the environment flag `TF_ENABLE_CONTROL_FLOW_V2="1"` and see if the issue remains?

**Comment by carlini** [comment]
I still get the same error when setting that environment variable.

**Comment by bckim1318** [comment]
Did this issue get solved now? I'm suffering from the same error with dropout and batch normalization.

**Comment by carlini** [comment]
Last I checked it's still an issue with the same crash.

**Comment by carlini** [comment]
Can we get some attention on this bug? It is consistently a problem with our usecase on tensorflow/cleverhans and has been present for a year and a half.

**Comment by deeb02** [comment]
To the best of our knowledge this does not reproduce on any recent TF release. And the code patterns that give it rise are not idiomatic TF2. Closing as stale. Please open again if you have a repro on a recent TF release.

**Comment by carlini** [comment]
It is somewhat amusing the ultimate resolution to a bug with a crash that literally says "This is an internal bug, please file a bug report with instructions on how to reproduce the error" is to wait 2.5 years without fixing the issue, and then close as "not idiomatic".

**Comment by deeb02** [comment]
The irony is not lost on us either, believe me.
But under limited time and resources, we must prioritize. Is this still crashing with more recent version of TF? IS there a particular functionality that you are unable to implement because of this? If either is true (esp. if both) we'll try to prioritize it.
