### ISSUE TITLE
Segfault reading dataset more than once (`make_batched_features_dataset`)

### ISSUE THREAD

**Issue by brianmartin** [tensorflow/tensorflow#23195]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): **No**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **macOS 10.14 Mojave**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: **NA**
- TensorFlow installed from (source or binary): **Binary / pip**
- TensorFlow version (use command below): **`('v1.11.0-rc2-4-gc19e29306c', '1.11.0')`**
- Python version: **2.7.10**
- Bazel version (if compiling from source): **NA**
- GCC/Compiler version (if compiling from source): **NA**
- CUDA/cuDNN version: **NA**
- GPU model and memory: **NA**

[Gist of full output of `./tools/tf_env_collect.sh](https://gist.github.com/brianmartin/2b43dca69453478ed33b49f1029e03fe)

**Exact command to reproduce:**

```
$ wget https://gist.githubusercontent.com/brianmartin/4f221eb838dce8099342f829fb13253d/raw/00c2a1736b9a292f8a6fb88164d240a766468744/gistfile1.txt
$ python gistfile1.txt
```

**Describe the current behavior**

Current behavior in 1.11.0, 1.12.0rcX is that the included script segfaults (11: SIGSEGV).

**Describe the expected behavior**

Expected behavior is no segfault. Version 1.10.1, 1.10.0, and 1.9.0 do not segfault. I have not checked lower versions.

**Code to reproduce the issue**

See a full script which reproduces this issue along two different code paths here: https://gist.github.com/brianmartin/4f221eb838dce8099342f829fb13253d

The segfault occurs when reading the dataset a second time. The first read works as expected.

For reference the two code samples which produce datasets which cause a segfault on second read are:

```py
    dataset = make_batched_features_dataset(file_pattern=data_file,
                                            batch_size=1,
                                            features=feature_spec)
```

I've also dug into `make_batched_features_dataset` and minified down to this repro:

```py
    from tensorflow.contrib.data.python.ops import parsing_ops
    from tensorflow.python.data.ops import readers

    dataset = Dataset.from_tensor_slices([data_file]) \
                     .interleave(readers.TFRecordDataset, cycle_length=1) \
                     .batch(batch_size=1) \
                     .apply(parsing_ops.parse_example_dataset(feature_spec))
```

------

Please let me know if there's anything else I can provide or help with! This is blocking us from upgrading to the latest Tensorflow version in [spotify/spotify-tensorflow](https://github.com/spotify/spotify-tensorflow).

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by brianmartin** [comment]
Updated!

**Comment by brianmartin** [comment]
I've dug in a bit more. For a FixedLenFeature, this test case still succeeds on the first read and fails on the second read -- no change there. But it fails with an exception rather than the segfault we see with VarLenFeature.

I've updated the gist to reproduce in tensorflow>=1.11.0 here: https://gist.github.com/brianmartin/4f221eb838dce8099342f829fb13253d

The exception on the second, failing read (after seeing the first read succeed):

```
Attempting first read..
2018-10-30 10:53:26.766551: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
{'f0': <tf.Tensor: id=26, shape=(1, 1), dtype=int64, numpy=array([[1]])>}
Attempting second identical read..
Traceback (most recent call last):
  File "/Users/brianm/wrk/spotify-tensorflow-brianmartin/scratch.py", line 109, in <module>
    main()
  File "/Users/brianm/wrk/spotify-tensorflow-brianmartin/scratch.py", line 104, in main
    run(make_it_fail, read_fn, var_len=var_len)
  File "/Users/brianm/wrk/spotify-tensorflow-brianmartin/scratch.py", line 79, in run
    _print_first(read_fn(data_file, feature_spec))
  File "/Users/brianm/wrk/spotify-tensorflow-brianmartin/scratch.py", line 35, in _print_first
    print next(xs.__iter__())
  File "/Users/brianm/wrk/spotify-tensorflow-brianmartin/venv/lib/python2.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 139, in __iter__
    return iterator_ops.EagerIterator(self)
  File "/Users/brianm/wrk/spotify-tensorflow-brianmartin/venv/lib/python2.7/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 521, in __init__
    ds_variant = dataset._as_variant_tensor()  # pylint: disable=protected-access
  File "/Users/brianm/wrk/spotify-tensorflow-brianmartin/venv/lib/python2.7/site-packages/tensorflow/contrib/data/python/ops/parsing_ops.py", line 90, in _as_variant_tensor
    **dataset_ops.flat_structure(self))
  File "/Users/brianm/wrk/spotify-tensorflow-brianmartin/venv/lib/python2.7/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 3963, in parse_example_dataset
    ctx=_ctx)
  File "/Users/brianm/wrk/spotify-tensorflow-brianmartin/venv/lib/python2.7/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 4015, in parse_example_dataset_eager_fallback
    attrs=_attrs, ctx=_ctx, name=name)
  File "/Users/brianm/wrk/spotify-tensorflow-brianmartin/venv/lib/python2.7/site-packages/tensorflow/python/eager/execute.py", line 66, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "/Users/brianm/wrk/spotify-tensorflow-brianmartin/venv/lib/python2.7/site-packages/six.py", line 737, in raise_from
    raise value
tensorflow.python.framework.errors_impl.InvalidArgumentError: Expected len(dense_defaults) == len(dense_keys) but got: 1 vs. 0 [Op:ParseExampleDataset]
```

**Comment by shivaniag** [comment]
@brianmartin Thank you very much for narrowing down the bug, we have fixed it and are going to submit it soon, will update you when that is done.
