### ISSUE TITLE
r1.12: "No module named enum"

### ISSUE THREAD

**Issue by amcphail** [tensorflow/tensorflow#23200]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- Linux Ubuntu 16.04.1
- no mobile device
- TensorFlow installed from github
- TensorFlow version: r1.12
- Python version: 2.7
- Installed using virtualenv? pip? conda?: apt-get
- Bazel version (if compiling from source): 0.17.1
- GCC/Compiler version (if compiling from source): 5.4.0
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the problem**
 File "/home/amcp011/.cache/bazel/_bazel_amcp011/2a4bcc1a1f556f9e46df7e271eeaa164/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/python/ops/variables.py", line 20, in <module>
    import enum  # pylint: disable=g-bad-import-order
ImportError: No module named enum

**Provide the exact sequence of commands / steps that you executed before running into the problem**
bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

ERROR: /home/amcp011/local/tensorflow/tensorflow/BUILD:533:1: Executing genrule //tensorflow:tf_python_api_gen_v1 failed (Exit 1)
Traceback (most recent call last):
  File "/home/amcp011/.cache/bazel/_bazel_amcp011/2a4bcc1a1f556f9e46df7e271eeaa164/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/python/tools/api/generator/create_python_api.py", line 27, in <module>
    from tensorflow.python.tools.api.generator import doc_srcs
  File "/home/amcp011/.cache/bazel/_bazel_amcp011/2a4bcc1a1f556f9e46df7e271eeaa164/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 70, in <module>
    from tensorflow.python.framework.framework_lib import *  # pylint: disable=redefined-builtin
  File "/home/amcp011/.cache/bazel/_bazel_amcp011/2a4bcc1a1f556f9e46df7e271eeaa164/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/python/framework/framework_lib.py", line 52, in <module>
    from tensorflow.python.framework.importer import import_graph_def
  File "/home/amcp011/.cache/bazel/_bazel_amcp011/2a4bcc1a1f556f9e46df7e271eeaa164/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/python/framework/importer.py", line 27, in <module>
    from tensorflow.python.framework import function
  File "/home/amcp011/.cache/bazel/_bazel_amcp011/2a4bcc1a1f556f9e46df7e271eeaa164/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/python/framework/function.py", line 36, in <module>
    from tensorflow.python.ops import resource_variable_ops
  File "/home/amcp011/.cache/bazel/_bazel_amcp011/2a4bcc1a1f556f9e46df7e271eeaa164/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/python/ops/resource_variable_ops.py", line 38, in <module>
    from tensorflow.python.ops import variables
  File "/home/amcp011/.cache/bazel/_bazel_amcp011/2a4bcc1a1f556f9e46df7e271eeaa164/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/python/ops/variables.py", line 20, in <module>
    import enum  # pylint: disable=g-bad-import-order
ImportError: No module named enum
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 128.659s, Critical Path: 101.44s
INFO: 72 processes: 72 local.
FAILED: Build did NOT complete successfully

**Comment by ymodak** [comment]
Can you try installing enum and building again. You can do something like this:
pip install --upgrade pip enum34

**Comment by amcphail** [comment]
I changed to python 3.6 from the ananconda3 distribution and now I get:

ERROR: /home/amcp011/local/tensorflow/tensorflow/python/eager/BUILD:10:1: undeclared inclusion(s) in rule '//tensorflow/python/eager:pywrap_tfe_lib':
this rule is missing dependency declarations for the following files included by 'tensorflow/python/eager/pywrap_tensor.cc':
  'bazel-out/host/genfiles/external/local_config_python/python_include/numpy/arrayobject.h'
  'bazel-out/host/genfiles/external/local_config_python/python_include/numpy/ndarrayobject.h'
  'bazel-out/host/genfiles/external/local_config_python/python_include/numpy/ndarraytypes.h'
  'bazel-out/host/genfiles/external/local_config_python/python_include/numpy/npy_common.h'
  'bazel-out/host/genfiles/external/local_config_python/python_include/numpy/numpyconfig.h'
  'bazel-out/host/genfiles/external/local_config_python/python_include/numpy/_numpyconfig.h'
  'bazel-out/host/genfiles/external/local_config_python/python_include/numpy/npy_endian.h'
  'bazel-out/host/genfiles/external/local_config_python/python_include/numpy/npy_cpu.h'
  'bazel-out/host/genfiles/external/local_config_python/python_include/numpy/utils.h'
  'bazel-out/host/genfiles/external/local_config_python/python_include/numpy/_neighborhood_iterator_imp.h'
  'bazel-out/host/genfiles/external/local_config_python/python_include/numpy/__multiarray_api.h'
  'bazel-out/host/genfiles/external/local_config_python/python_include/numpy/npy_interrupt.h'
  'bazel-out/host/genfiles/external/local_config_python/python_include/numpy/ufuncobject.h'
  'bazel-out/host/genfiles/external/local_config_python/python_include/numpy/npy_math.h'
  'bazel-out/host/genfiles/external/local_config_python/python_include/numpy/npy_common.h'
  'bazel-out/host/genfiles/external/local_config_python/python_include/numpy/arrayobject.h'
  'bazel-out/host/genfiles/external/local_config_python/python_include/numpy/__ufunc_api.h'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 2047.164s, Critical Path: 434.58s
INFO: 2724 processes: 2724 local.
FAILED: Build did NOT complete successfully

**Comment by gunan** [comment]
@jjhelmus may have some input on the 2nd issue. I think this is a configuration issue.

**Comment by jjhelmus** [comment]
Is numpy installed into the conda environment?  Was `site-packages` directory of the environment detected by the configuration script and selected?

**Comment by rayanelleuch** [comment]
I got same problem :

System information:

    Linux Ubuntu 16.04 LTS
    no mobile device
    TensorFlow installed from github
    TensorFlow version: r1.12
    Python version: 3.5.2
    Installed using virtualenv? pip? conda?: apt-get
    Bazel version (if compiling from source): 0.15.0
    GCC/Compiler version (if compiling from source): 5.4.0
    CUDA/cuDNN version: N/A
    GPU model and memory: N/A

.tf_configure.bazelrc:
```
build --action_env PYTHON_BIN_PATH="/usr/bin/python3"
build --action_env PYTHON_LIB_PATH="/usr/local/lib/python3.5/dist-packages"
build --python_path="/usr/bin/python3"
build:ignite --define with_ignite_support=true
build:xla --define with_xla_support=true
build --action_env TF_NEED_OPENCL_SYCL="0"
build --action_env TF_NEED_ROCM="0"
build --action_env TF_NEED_CUDA="0"
build --action_env TF_DOWNLOAD_CLANG="0"
build:opt --copt=-march=native
build:opt --host_copt=-march=native
build:opt --define with_default_optimizations=true
build:v2 --define=tf_api_version=2
```

```
~/tensorflow$ pip3 install numpy
Requirement already satisfied: numpy in /usr/local/lib/python3.5/dist-packages (1.14.3)
```

Error:
```
ERROR: /home/rayan/tensorflow/tensorflow/python/eager/BUILD:10:1: undeclared inclusion(s) in rule '//tensorflow/python/eager:pywrap_tfe_lib':
this rule is missing dependency declarations for the following files included by 'tensorflow/python/eager/pywrap_tensor.cc':
  'bazel-out/k8-opt/genfiles/external/local_config_python/python_include/numpy/arrayobject.h'
  'bazel-out/k8-opt/genfiles/external/local_config_python/python_include/numpy/ndarrayobject.h'
  'bazel-out/k8-opt/genfiles/external/local_config_python/python_include/numpy/ndarraytypes.h'
  'bazel-out/k8-opt/genfiles/external/local_config_python/python_include/numpy/npy_common.h'
  'bazel-out/k8-opt/genfiles/external/local_config_python/python_include/numpy/numpyconfig.h'
  'bazel-out/k8-opt/genfiles/external/local_config_python/python_include/numpy/_numpyconfig.h'
  'bazel-out/k8-opt/genfiles/external/local_config_python/python_include/numpy/npy_endian.h'
  'bazel-out/k8-opt/genfiles/external/local_config_python/python_include/numpy/npy_cpu.h'
  'bazel-out/k8-opt/genfiles/external/local_config_python/python_include/numpy/utils.h'
  'bazel-out/k8-opt/genfiles/external/local_config_python/python_include/numpy/_neighborhood_iterator_imp.h'
  'bazel-out/k8-opt/genfiles/external/local_config_python/python_include/numpy/__multiarray_api.h'
  'bazel-out/k8-opt/genfiles/external/local_config_python/python_include/numpy/npy_interrupt.h'
  'bazel-out/k8-opt/genfiles/external/local_config_python/python_include/numpy/ufuncobject.h'
  'bazel-out/k8-opt/genfiles/external/local_config_python/python_include/numpy/npy_math.h'
  'bazel-out/k8-opt/genfiles/external/local_config_python/python_include/numpy/npy_common.h'
  'bazel-out/k8-opt/genfiles/external/local_config_python/python_include/numpy/arrayobject.h'
  'bazel-out/k8-opt/genfiles/external/local_config_python/python_include/numpy/__ufunc_api.h'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.

```

**Comment by lorenzesz** [comment]
****System information**

* OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
* Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
* TensorFlow installed from (source or binary): source
* TensorFlow version: 1.13.0rc2
* Python version: 3.7.2
* Installed using virtualenv? pip? conda?: pip
* Bazel version (if compiling from source): 0.22
* GCC/Compiler version (if compiling from source): 6.5.0
* CUDA/cuDNN version: 10.0/7.3
* GPU model and memory: RTX 2070 and 8GB

**Describe the problem**

ERROR: /home/max/tensorflow/tensorflow/python/eager/BUILD:10:1: undeclared inclusion(s) in rule '//tensorflow/python/eager:pywrap_tfe_lib':
this rule is missing dependency declarations for the following files included by 'tensorflow/python/eager/pywrap_tensor.cc':
'bazel-out/host/genfiles/external/local_config_python/python_include/numpy/arrayobject.h'
'bazel-out/host/genfiles/external/local_config_python/python_include/numpy/ndarrayobject.h'
'bazel-out/host/genfiles/external/local_config_python/python_include/numpy/ndarraytypes.h'
'bazel-out/host/genfiles/external/local_config_python/python_include/numpy/npy_common.h'
'bazel-out/host/genfiles/external/local_config_python/python_include/numpy/numpyconfig.h'
'bazel-out/host/genfiles/external/local_config_python/python_include/numpy/_numpyconfig.h'
'bazel-out/host/genfiles/external/local_config_python/python_include/numpy/npy_endian.h'
'bazel-out/host/genfiles/external/local_config_python/python_include/numpy/npy_cpu.h'
'bazel-out/host/genfiles/external/local_config_python/python_include/numpy/utils.h'
'bazel-out/host/genfiles/external/local_config_python/python_include/numpy/_neighborhood_iterator_imp.h'
'bazel-out/host/genfiles/external/local_config_python/python_include/numpy/__multiarray_api.h'
'bazel-out/host/genfiles/external/local_config_python/python_include/numpy/npy_interrupt.h'
'bazel-out/host/genfiles/external/local_config_python/python_include/numpy/ufuncobject.h'
'bazel-out/host/genfiles/external/local_config_python/python_include/numpy/npy_math.h'
'bazel-out/host/genfiles/external/local_config_python/python_include/numpy/npy_common.h'
'bazel-out/host/genfiles/external/local_config_python/python_include/numpy/arrayobject.h'
'bazel-out/host/genfiles/external/local_config_python/python_include/numpy/__ufunc_api.h'
Target //tensorflow/tools/pip_package:build_pip_package failed to build**

**Comment by mrgloom** [comment]
`pip install --upgrade pip enum34` didn't helped.

`bazel build tensorflow/python/tools:optimize_for_inference`

```
ERROR: /Users/my_user/external_projects/tensorflow/tensorflow/python/keras/api/BUILD:28:1: Executing genrule //tensorflow/python/keras/api:keras_python_api_gen_compat_v1 failed (Exit 1)
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_my_user/747948fb577123a5771581be02ddf56a/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_1_keras_python_api_gen_compat_v1.runfiles/org_tensorflow/tensorflow/python/tools/api/generator/create_python_api.py", line 27, in <module>
    from tensorflow.python.tools.api.generator import doc_srcs
  File "/private/var/tmp/_bazel_my_user/747948fb577123a5771581be02ddf56a/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_1_keras_python_api_gen_compat_v1.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 63, in <module>
    from tensorflow.python.framework.framework_lib import *  # pylint: disable=redefined-builtin
  File "/private/var/tmp/_bazel_my_user/747948fb577123a5771581be02ddf56a/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_1_keras_python_api_gen_compat_v1.runfiles/org_tensorflow/tensorflow/python/framework/framework_lib.py", line 52, in <module>
    from tensorflow.python.framework.importer import import_graph_def
  File "/private/var/tmp/_bazel_my_user/747948fb577123a5771581be02ddf56a/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_1_keras_python_api_gen_compat_v1.runfiles/org_tensorflow/tensorflow/python/framework/importer.py", line 28, in <module>
    from tensorflow.python.framework import function
  File "/private/var/tmp/_bazel_my_user/747948fb577123a5771581be02ddf56a/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_1_keras_python_api_gen_compat_v1.runfiles/org_tensorflow/tensorflow/python/framework/function.py", line 37, in <module>
    from tensorflow.python.ops import resource_variable_ops
  File "/private/var/tmp/_bazel_my_user/747948fb577123a5771581be02ddf56a/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_1_keras_python_api_gen_compat_v1.runfiles/org_tensorflow/tensorflow/python/ops/resource_variable_ops.py", line 41, in <module>
    from tensorflow.python.ops import variables
  File "/private/var/tmp/_bazel_my_user/747948fb577123a5771581be02ddf56a/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_1_keras_python_api_gen_compat_v1.runfiles/org_tensorflow/tensorflow/python/ops/variables.py", line 20, in <module>
    import enum  # pylint: disable=g-bad-import-order
ImportError: No module named enum
Target //tensorflow/python/tools:optimize_for_inference failed to build
Use --verbose_failures to see the command lines of failed build steps.
```

**Comment by mrgloom** [comment]
I can do `import enum`

```
python -c "import enum; print(enum.__file__)"
/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/enum.py
```

How to check if `bazel build tensorflow/python/tools:optimize_for_inference` use the right python?

**Comment by gunan** [comment]
TF's build uses python based on which python version you use during configure.py run.

**Comment by Saduf2019** [comment]
@amcphail Can you please confirm if your issue is resolved.

**Comment by amcphail** [comment]
I reverted to the anaconda version of TF.

**Comment by Saduf2019** [comment]
@amcphail please confirm if we may proceed to move this issue to resolved.

**Comment by amcphail** [comment]
Yes.
