### ISSUE TITLE
Broken distributed training with tf.estimator.Estimator

### ISSUE THREAD

**Issue by Luonic** [tensorflow/tensorflow#23232]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: None
- TensorFlow installed from (source or binary): Source
- TensorFlow version (use command below): v1.11.0-0-gc19e29306c 1.11.0
- Python version: 3.6.6
- Bazel version (if compiling from source): 0.18.0 (PPA)
- GCC/Compiler version (if compiling from source): gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
- CUDA/cuDNN version: 10.0/7.3.1
- GPU model and memory: 2x1080ti + 2x1070

When I am trying to train network with Estimator and MirroredStrategy there is naming issue in estimator's code.
I get following error:
```
Traceback (most recent call last):
  File "/snap/pycharm-community/85/helpers/pydev/pydevd.py", line 1664, in <module>
    main()
  File "/snap/pycharm-community/85/helpers/pydev/pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/snap/pycharm-community/85/helpers/pydev/pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/snap/pycharm-community/85/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/alexandr/Code/DRIT_Tensorflow/train_est.py", line 102, in <module>
    tf.app.run(main)
  File "/home/alexandr/.local/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/home/alexandr/Code/DRIT_Tensorflow/train_est.py", line 79, in main
    estimator.train(train_input_fn)
  File "/home/alexandr/.local/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 356, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/alexandr/.local/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1179, in _train_model
    return self._train_model_distributed(input_fn, hooks, saving_listeners)
  File "/home/alexandr/.local/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1309, in _train_model_distributed
    grouped_estimator_spec.training_hooks)
  File "/home/alexandr/.local/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1305, in get_hooks_from_the_first_device
    for per_device_hook in per_device_hooks
  File "/home/alexandr/.local/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1305, in <listcomp>
    for per_device_hook in per_device_hooks
AttributeError: 'Estimator' object has no attribute '_distribution'
```

Problem occurs here:
```
        def get_hooks_from_the_first_device(per_device_hooks):
          return [
              self._distribution.unwrap(per_device_hook)[0]
              for per_device_hook in per_device_hooks
          ]
```
when estimator tries to call `unwrap()` method of `_distribution` but distribution strategy is stored in `_train_distribution` field.

This is from PyCharm's debugger:
```
per_device_hooks = {tuple} <class 'tuple'>: (PerDevice({'/replica:0/task:0/device:GPU:0': <model.model_fn.<locals>.TrainOpSelectorHook object at 0x7f0189a444e0>, '/replica:0/task:0/device:GPU:1': <model.model_fn.<locals>.TrainOpSelectorHook object at 0x7f01c3331d68>, '/replica:0/tas
self = {Estimator} <tensorflow.python.estimator.estimator.Estimator object at 0x7f0c3f44f4a8>
 _config = {RunConfig} <tensorflow.python.estimator.run_config.RunConfig object at 0x7f0c3f44f4e0>
 _device_fn = {NoneType} None
 _estimator_api_names = {tuple} <class 'tuple'>: ('estimator.Estimator',)
 _estimator_api_names_v1 = {tuple} <class 'tuple'>: ('estimator.Estimator',)
 _eval_distribution = {NoneType} None
 _model_dir = {str} 'train_logs/37/checkpoints'
 _params = {dict} {'batch_size': 1, 'image_size': [216, 216], 'float_type': tf.float32, 'gradient_scale': 1.0, 'leaky_relu_alpha': 0.2, 'attribute_tensor_depth': 32, 'attribute_subsample_factor': 4, 'attribute_tensor_global_pooling': False, 'remap_attribute_with_content': True, 'weight_decay': 1e-05, 'learning_rate': 1e-05, 'content_discriminator_lr_multiplier': 0.4, 'attribute_discriminator_lr_multiplier': 0.4, 'quantize': False, 'content_discriminator_steps': 1, 'domain_discriminator_steps': 1, 'num_steps_start_lr_decay': 100000, 'max_iter': 250000}
 _session_config = {ConfigProto} 
LOOK HERE ==> _train_distribution = {MirroredStrategy} <tensorflow.contrib.distribute.python.mirrored_strategy.MirroredStrategy object at 0x7f0c3f44f5c0>
 _warm_start_settings = {NoneType} None
 config = {RunConfig} <tensorflow.python.estimator.run_config.RunConfig object at 0x7f017d7b0f98>
 model_dir = {str} 'train_logs/37/checkpoints'
 params = {dict} {'batch_size': 1, 'image_size': [216, 216], 'float_type': tf.float32, 'gradient_scale': 1.0, 'leaky_relu_alpha': 0.2, 'attribute_tensor_depth': 32, 'attribute_subsample_factor': 4, 'attribute_tensor_global_pooling': False, 'remap_attribute_with_content': True, 'weight_decay': 1e-05, 'learning_rate': 1e-05, 'content_discriminator_lr_multiplier': 0.4, 'attribute_discriminator_lr_multiplier': 0.4, 'quantize': False, 'content_discriminator_steps': 1, 'domain_discriminator_steps': 1, 'num_steps_start_lr_decay': 100000, 'max_iter': 250000}
```

**Describe the expected behavior**
What I expect? I expect tf.estimator's code to not be broken.

**Code to reproduce the issue**
Any example with MirroredStrategy should be fine.

**Comment by guptapriya** [comment]
thanks for filing, https://github.com/tensorflow/estimator/pull/3#pullrequestreview-168946557 is going to fix this. I am working on getting that merged.
