### ISSUE TITLE
Using TensorRT in TensorFlow from java

### ISSUE THREAD

**Issue by sujitbiswas** [tensorflow/tensorflow#23243]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using):1.11
- Are you willing to contribute it (Yes/No):

**Describe the feature and the current behavior/state.**
Using TensorRT in TensorFlow from java for inference only

**Will this change the current api? How?** 
not sure if the current java api needs to change in order to load graph and infer

**Who will benefit with this feature?**
anyone using java runtime

**Any Other info.**

**Comment by tensorflowbutler** [comment]
Nagging Assignee @samikama: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by sujitbiswas** [comment]
@samikama any update, when this feature will be available?

**Comment by sujitbiswas** [comment]
@asimshankar @samikama 

I am following the tf-trt example  here
https://medium.com/tensorflow/speed-up-tensorflow-inference-on-gpus-with-tensorrt-13b49f3db3fa
 
The example start with  resnetV150_frozen.pb  and generates a set of TF-TRT optimized  inference graph
 
1. resnetV150_TRTFP16.pb
2. resnetV150_TRTFP32.pb
3. resnetV150_TRTINT8.pb
 
 
Idea is to infer using the tf-trt optimized graph using the java API, I am running on
 
Ubuntu linux 16.04
Tensorflow  1.12.0
Cuda 9.0
Cudnn 7.4.1
TensorRT 4.1.2
 
with the java API for inference using resnetV150_frozen.pb  works fine , however when I try to use  TF-TRT optimized “resnetV150_TRTFP16.pb” or resnetV150_TRTFP32.pb it runs into the following, 
 
 
2018-11-22 23:08:44.747554: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 11297 MB memory) -> physical GPU (device: 0, name: TITAN Xp, pci bus id: 0000:06:00.0, compute capability: 6.1)
Exception in thread "main" org.tensorflow.TensorFlowException: **Op type not registered 'TRTEngineOp'** in binary running on sujit-desktop. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) **`tf.contrib.resampler`** should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.
                at org.tensorflow.Graph.importGraphDef(Native Method)
                at org.tensorflow.Graph.importGraphDef(Graph.java:130)
                at org.tensorflow.Graph.importGraphDef(Graph.java:114)
                at com.nvidia.tf.InspectModel2$.main(InspectModel2.scala:64)
                at com.nvidia.tf.InspectModel2.main(InspectModel2.scala)
 
 
please let me how to resolve the issue?
 
Does https://mvnrepository.com/artifact/org.tensorflow/libtensorflow_jni_gpu/1.12.0 includes tf-trt related ops
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/tensorrt  ?

**Comment by samikama** [comment]
@sujitbiswas As message tells you, you need to load op libs first to make TRTEngineOp available to the system.

**Comment by asimshankar** [comment]
@sujitbiswas : To elaborate on what @samikama said, `contrib` libraries aren't packaged with the TensorFlow Java distribution and currently need to be explicitly loaded. See [this StackOverflow answer](https://stackoverflow.com/a/47277367/6708503)

Here is what I did on my installation:

- Get the path to the shared library defining the operation in contrib
```
python -c "import tensorflow.contrib.tensorrt as trt; print(trt.__path__)"

# Which printed /usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tensorrt
# Specifically, the library is: 
/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tensorrt/python/ops/_trt_engine_op.so
```

- Load that library in Java using something like this:

```java
import java.nio.file.Files;
import java.nio.file.Paths;
import org.tensorflow.Graph;
import org.tensorflow.Session;
import org.tensorflow.TensorFlow;

public class HelloTF {
  public static void main(String[] args) throws Exception {
    // You could copy the library and package it with your Java application instead.
    TensorFlow.loadLibrary("/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tensorrt/python/ops/_trt_engine_op.so");
    try (Graph graph = new Graph();
        Session session = new Session(graph)) {
      graph.importGraphDef(Files.readAllBytes(Paths.get("resnetV150_TRTFP16.pb")));
      // Use session to execute the graph
    }
  }
}
```

Hope that helps.
Feel free to reopen this issue if the question isn't answered or if the above didn't work.

**Comment by sujitbiswas** [comment]
Thanks for the help @samikama @asimshankar 

note the error changes when we load

TensorFlow.loadLibrary("/home/sujitb/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/contrib/tensorrt/python/ops/**_trt_engine_op.so"**)
 
 
 
Exception in thread "main" java.lang.IllegalArgumentException: **No shape inference function exists for op 'TRTEngineOp',** did you forget to define it?
                at org.tensorflow.Graph.importGraphDef(Native Method)
                at org.tensorflow.Graph.importGraphDef(Graph.java:130)
                at org.tensorflow.Graph.importGraphDef(Graph.java:114)
                at com.nvidia.tf.InspectModel2$.main(InspectModel2.scala:31)
                at com.nvidia.tf.InspectModel2.main(InspectModel2.scala)
 
 
I see a similar issue open, someone tried the same with C++
https://github.com/tensorflow/tensorflow/issues/23853
 
please let me know how to proceed?

**Comment by asimshankar** [comment]
Ugh, that's a shame.
I'll look into it and follow up on #23853 
Sorry for the trouble.

**Comment by mon28** [comment]
> Thanks for the help @samikama @asimshankar
> 
> note the error changes when we load
> 
> TensorFlow.loadLibrary("/home/sujitb/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/contrib/tensorrt/python/ops/**_trt_engine_op.so"**)
> 
> Exception in thread "main" java.lang.IllegalArgumentException: **No shape inference function exists for op 'TRTEngineOp',** did you forget to define it?
> at org.tensorflow.Graph.importGraphDef(Native Method)
> at org.tensorflow.Graph.importGraphDef(Graph.java:130)
> at org.tensorflow.Graph.importGraphDef(Graph.java:114)
> at com.nvidia.tf.InspectModel2$.main(InspectModel2.scala:31)
> at com.nvidia.tf.InspectModel2.main(InspectModel2.scala)
> 
> I see a similar issue open, someone tried the same with C++
> #23853
> 
> please let me know how to proceed?

@sujitbiswas did you find a solution to this? I am stuck with the same issue.
