### ISSUE TITLE
 CUDA driver version is insufficient for CUDA runtime version

### ISSUE THREAD

**Issue by jaimeet64** [tensorflow/tensorflow#23263]
Python 3.6.6 | packaged by conda-forge | (default, Oct 12 2018, 14:08:43) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
>>> import tensorflow as tf
>>> sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))
2018-10-25 12:10:00.651103: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-10-25 12:10:00.738944: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:964] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-10-25 12:10:00.739553: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1411] Found device 0 with properties: 
name: GeForce GTX 1070 major: 6 minor: 1 memoryClockRate(GHz): 1.683
pciBusID: 0000:01:00.0
totalMemory: 7.93GiB freeMemory: 7.40GiB
2018-10-25 12:10:00.739580: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1490] Adding visible gpu devices: 0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jaimeet/.conda/envs/py-dl/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1511, in __init__
    super(Session, self).__init__(target, graph, config=config)
  File "/home/jaimeet/.conda/envs/py-dl/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 634, in __init__
    self._session = tf_session.TF_NewSessionRef(self._graph._c_graph, opts)
tensorflow.python.framework.errors_impl.InternalError: cudaGetDevice() failed. Status: CUDA driver version is insufficient for CUDA runtime version

**System information**
- OS Platform and Distribution :Ubuntu 18.04 
- TensorFlow installed from (source or binary): library
- TensorFlow version: 1.11.0
- Python version: 3.6
- Installed using virtualenv? pip? conda?: conda
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: Cuda compilation tools, release 9.0, V9.0.176. NVIDIA-SMI 390.87 
- GPU model and memory:  GTX 1070 

*

**Comment by hdtsirai** [comment]
I've got the same proble with Ubuntu 18.04+GeForce 1080Ti+nvidia-390+cuda-9.[012] and corresponding cuDNNs +tensorflow-1.11.0 .
My solution is to downgrade the tensorflow and tensorflow-gpu to 1.6.0 with cuda-9.0+CuDNN 7. It worked.

**Comment by ymodak** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
