### ISSUE TITLE
Unable to import tensorflow

### ISSUE THREAD

**Issue by johnnardini** [tensorflow/tensorflow#23273]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 14.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.11
- Python version: python 2.7.12
- Installed using virtualenv? pip? conda?: inside of a virtualenv installed using pip
- Bazel version (if compiling from source): not sure
- GCC/Compiler version (if compiling from source): not sure
- CUDA/cuDNN version: not sure
- GPU model and memory: not sure

**Describe the problem**
I have installed tensorflow (CPU only) for python 2.7 from source. However, when I try to import tensorflow I come across the following error

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/john/python_2_7_12/lib/python2.7/site-packages/tensorflow/__init__.py", line 22, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/john/python_2_7_12/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/john/python_2_7_12/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/john/python_2_7_12/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/john/python_2_7_12/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/john/python_2_7_12/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: /home/john/python_2_7_12/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: PyUnicodeUCS4_FromString

**Provide the exact sequence of commands / steps that you executed before running into the problem**

python -c "import tensorflow as tf; print(tf.__version__)"

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by johnnardini** [comment]
Hello,

I fixed this problem by installing python2.14 with unicode 4 instead of
unicode 2.

Thanks,
John
