### ISSUE TITLE
Can't import tensorflow

### ISSUE THREAD

**Issue by Maxlaxs** [tensorflow/tensorflow#23285]
- Windows 10 1709
 - Tensorflow version 1.11 install via pip
 - Python 3.6.6 64bit
 - Have I written custom code: No
 - Bazel version : I don't have
 - CUDA/cuDNN version : I don't have
 - GPU model and memory :N\A
 - Exact command to reproduce : import tensorflow

**The problem**
Can't import tensorflow

Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Python36\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Python36\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: Failed to initialize a DLL.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\latit\Desktop\LanParty\LANParty1.py", line 27, in <module>
    import tensorflow
  File "C:\Python36\lib\site-packages\tensorflow\__init__.py", line 22, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Python36\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Python36\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Python36\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: Failed to initialize a DLL.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by MartinKondor** [comment]
Use Python 3.5 on Windows.

**Comment by gunan** [comment]
We also build and distribute python 3.6 binaries.
This can be missing MSVC redistributable, or CPU not supporting AVX instruction set.

**Comment by Maxlaxs** [comment]
> 
> 
> Use Python 3.5.X 64bit on Windows.
> 
> For me, this version is working with Tensorflow, I had this same issue, but installing an older python solved it:
> 
> ```
> Python 3.5.4 (Aug  8 2017) 64 bit
> Tensorflow 1.11.0
> ```
> 
> So python must be 64 bit and 3.5.X at the same time.

Getting the same error in 3.5.4

**Comment by MartinKondor** [comment]
[Missing MSVC redistributable](https://www.microsoft.com/en-us/download/details.aspx?id=53587)
[CPU not supporting AVX (Install GPU version)](https://github.com/rohit-patel/Install_Instructions-Win10-Deeplearning-Keras-Tensorflow)

**Comment by Maxlaxs** [comment]
The first link did not fix it and I don't have a NVIDIA gpu

**Comment by Maxlaxs** [comment]
I have already installed the MSVC download, and I don't have a NVIDIA gpu

**Comment by Maxlaxs** [comment]
I have already installed the MSVC download, and I don't have a NVIDIA gpu

**Comment by tensorflowbutler** [comment]
Nagging Assignee @gunan: It has been 33 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by lyind** [comment]
I tried to debug this or a related issue a little more: https://github.com/tensorflow/tensorflow/issues/27035#issuecomment-479392652

**Comment by ymodak** [comment]
Apologies for the delay in response.
*TensorFlow release binaries (CPU/GPU) version 1.6 and higher are prebuilt with AVX instruction sets.*  
See [hardware requirements][1] to know more.  

Therefore on any CPU that does not have these instruction sets, either CPU or GPU version of TF will fail to load.
Apparently, your CPU model does not support AVX instruction sets. You can still use TensorFlow with the alternatives given below:  

* Try Google Colab to use TensorFlow.    
 * The easiest way to use TF will be to switch to [google colab](https://colab.sandbox.google.com/notebooks/welcome.ipynb#recent=true). You get pre-installed latest stable TF version. Also you can use ```pip install``` to install any other preferred TF version.  
    * It has an added advantage since you can you easily switch to different hardware accelerators (cpu, gpu, tpu) as per the task. 
    * All you need is a good internet connection and you are all set.  
* Try to build TF from sources by changing CPU optimization flags.


  [1]: https://www.tensorflow.org/install/pip#hardware-requirements
