### ISSUE TITLE
[Keras tensorflow] float16 doesn't work with conv2d ?

### ISSUE THREAD

**Issue by NitroBAY** [tensorflow/tensorflow#23295]
Hello,
I have a rtx card to use RT cores (dedicated for NN, uses half-precision to my understanding) I'd like using float16 so I : 

    from tensorflow.keras import backend
    os.environ['KERAS_FLOATX'] = 'float16'
    os.environ['TF_FP16_CONV_USE_FP32_COMPUTE'] = '0'
    backend.set_floatx('float16')

but this triggers error : 
   model = Sequential([
        Conv2D(32, kernel_size=(5, 5), input_shape=(32, 32, 3), strides=(1, 1))
    ])
    model.compile(optimizer=Adam(), loss='mse')

Traceback (most recent call last):
  File "C:\Users\xd111\Miniconda3\envs\evo\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 510, in _apply_op_helper
    preferred_dtype=default_dtype)
  File "C:\Users\xd111\Miniconda3\envs\evo\lib\site-packages\tensorflow\python\framework\ops.py", line 1107, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "C:\Users\xd111\Miniconda3\envs\evo\lib\site-packages\tensorflow\python\framework\ops.py", line 944, in _TensorTensorConversionFunction
    (dtype.name, t.dtype.name, str(t)))
ValueError: Tensor conversion requested dtype float16 for Tensor with dtype float32: 'Tensor("conv2d_sample_weights:0", shape=(?,), dtype=float32)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "float16.py", line 17, in <module>
    init()
  File "float16.py", line 15, in init
    model.compile(optimizer=Adam(), loss='mse')
  File "C:\Users\xd111\Miniconda3\envs\evo\lib\site-packages\tensorflow\python\keras\engine\training.py", line 442, in compile
    output_loss = weighted_loss(y_true, y_pred, sample_weight, mask)
  File "C:\Users\xd111\Miniconda3\envs\evo\lib\site-packages\tensorflow\python\keras\engine\training_utils.py", line 453, in weighted
    score_array *= weights
  File "C:\Users\xd111\Miniconda3\envs\evo\lib\site-packages\tensorflow\python\ops\math_ops.py", line 847, in binary_op_wrapper
    return func(x, y, name=name)
  File "C:\Users\xd111\Miniconda3\envs\evo\lib\site-packages\tensorflow\python\ops\math_ops.py", line 1091, in _mul_dispatch
    return gen_math_ops.mul(x, y, name=name)
  File "C:\Users\xd111\Miniconda3\envs\evo\lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 4758, in mul
    "Mul", x=x, y=y, name=name)
  File "C:\Users\xd111\Miniconda3\envs\evo\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 546, in _apply_op_helper
    inferred_from[input_arg.type_attr]))
TypeError: Input 'y' of 'Mul' Op has type float32 that does not match type float16 of argument 'x'.

I'm not a professional I'm a newbie to NN so excuse me if my question is not relevant.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @fchollet: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @fchollet: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by harshini-gadige** [comment]
Closing this as it is in "awaiting response" status for more than 7 days. Feel free to add your comments and we will reopen(if required).
