### ISSUE TITLE
Cannot import tensorflow into my file. Error message suggests that this is a build issue I think. 

### ISSUE THREAD

**Issue by ChandlerMunro** [tensorflow/tensorflow#23308]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): "pip install tensorflow" from cmd
- TensorFlow version: 1.11.0
- Python version: 3.6.6
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

**Describe the problem**
I am getting an error message when trying to import tensorflow in my python file. I will post the error message below. I have uninstalled and reinstalled tensorflow using pip multiple times (like 3) using the same command every time : "pip install tensorflow"

**Provide the exact sequence of commands / steps that you executed before running into the problem**
I installed tensorflow using pip in cmd using the command "pip install tensorflow." I am running this in my x64 laptop and this device does not have a GPU. Tensorflows says that it installs correctly. However, when I open my python file in my text editor and I type "import tensorflow" and then I try to run the code, it gives me a long error message. 

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

This is the error message I recieve in the terminal when trying to run my python file. Note that even though I do not have a gpu and did not install it using pip with the gpu configuration, it gives me an error that other people get trying to install the that uses their GPU. I don't know if that's important or not. 

Traceback (most recent call last):
  File "C:\Users\18ngc\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\18ngc\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\18ngc\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\18ngc\AppData\Local\Programs\Python\Python36\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\18ngc\AppData\Local\Programs\Python\Python36\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\18ngc\Documents\python-workspace\workshop\__main__.py", line 1, in <module>
    import tensorflow
  File "C:\Users\18ngc\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\__init__.py", line 22, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\18ngc\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\18ngc\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\18ngc\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\18ngc\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\18ngc\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\18ngc\AppData\Local\Programs\Python\Python36\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\18ngc\AppData\Local\Programs\Python\Python36\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by harshini-gadige** [comment]
@ChandlerMunro  - Hi, please refer [this link](https://kb.froglogic.com/display/KB/Article+-+Errors+with+%28third+party%29+Python+modules) which helps you to resolve the issue.

**Comment by ChandlerMunro** [comment]
I think the problem was my cpu does not support the new AVX instructions. I found a tensorflow 1.0.0 on github and installed that instead of "pip instasll tensorflow". Now, tensorflow imports fine. 
So the new tensorflow packages no longer work with cpu's that don't have avx instructions? I am guessing this is what is causing these problems.
