### ISSUE TITLE
Hey. Just saw that the vocabulary size is a parameter you have to define manually? Seems not very intuitive for me as it can be computed automatically.

### ISSUE THREAD

**Issue by kartikitrak** [tensorflow/tensorflow#23311]
_Originally posted by @b-3-n in https://github.com/tensorflow/tensorflow/issues/2734#issuecomment-224732629_

**Comment by kartikitrak** [comment]
I am  facing " tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[47] = 20000 is not in [0, 20000)" error ,similar to what @b-3-n(you) was facing and I am unable to resolve it,please eleborate your solution if you have one.

Mode : train

Preparing data in working_dir/
Creating 3 layers of 256 units.
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "BestSplits" device_type: "CPU"') for unknown op: BestSplits
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "CountExtremelyRandomStats" device_type: "CPU"') for unknown op: CountExtremelyRandomStats
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "FinishedNodes" device_type: "CPU"') for unknown op: FinishedNodes
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "GrowTree" device_type: "CPU"') for unknown op: GrowTree
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "ReinterpretStringToFloat" device_type: "CPU"') for unknown op: ReinterpretStringToFloat
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "SampleInputs" device_type: "CPU"') for unknown op: SampleInputs
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "ScatterAddNdim" device_type: "CPU"') for unknown op: ScatterAddNdim
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "TopNInsert" device_type: "CPU"') for unknown op: TopNInsert
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "TopNRemove" device_type: "CPU"') for unknown op: TopNRemove
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "TreePredictions" device_type: "CPU"') for unknown op: TreePredictions
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "UpdateFertileSlots" device_type: "CPU"') for unknown op: UpdateFertileSlots
Created model with fresh parameters.
Reading development and training data (limit: 0).
  reading data line 100000
Traceback (most recent call last):
  File "C:\Users\makke\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\client\session.py", line 1022, in _do_call
    return fn(*args)
  File "C:\Users\makke\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\client\session.py", line 1004, in _run_fn
    status, run_metadata)
  File "C:\Users\makke\AppData\Local\Programs\Python\Python35\lib\contextlib.py", line 66, in __exit__
    next(self.gen)
  File "C:\Users\makke\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 469, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[47] = 20000 is not in [0, 20000)
         [[Node: model_with_buckets/embedding_attention_seq2seq_2/rnn/embedding_wrapper_14/embedding_lookup = Gather[Tindices=DT_INT32, Tparams=DT_FLOAT, _class=["loc:@embedding_attention_seq2seq/rnn/embedding_wrapper/embedding/read"], validate_indices=true, _device="/job:localhost/replica:0/task:0/cpu:0"](embedding_attention_seq2seq/rnn/embedding_wrapper/embedding/read, model_with_buckets/embedding_attention_seq2seq_2/rnn/embedding_wrapper_14/Reshape)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "execute.py", line 352, in <module>
  File "execute.py", line 180, in train
    previous_losses.append(loss)
  File "C:\Users\makke\ml\tensor\seq2seq_model.py", line 230, in step
    outputs = session.run(output_feed, input_feed)
  File "C:\Users\makke\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\client\session.py", line 767, in run
    run_metadata_ptr)
  File "C:\Users\makke\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\client\session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "C:\Users\makke\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\client\session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "C:\Users\makke\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\client\session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[47] = 20000 is not in [0, 20000)
         [[Node: model_with_buckets/embedding_attention_seq2seq_2/rnn/embedding_wrapper_14/embedding_lookup = Gather[Tindices=DT_INT32, Tparams=DT_FLOAT, _class=["loc:@embedding_attention_seq2seq/rnn/embedding_wrapper/embedding/read"], validate_indices=true, _device="/job:localhost/replica:0/task:0/cpu:0"](embedding_attention_seq2seq/rnn/embedding_wrapper/embedding/read, model_with_buckets/embedding_attention_seq2seq_2/rnn/embedding_wrapper_14/Reshape)]]

Caused by op 'model_with_buckets/embedding_attention_seq2seq_2/rnn/embedding_wrapper_14/embedding_lookup', defined at:
  File "execute.py", line 352, in <module>
  File "execute.py", line 148, in train
  File "execute.py", line 109, in create_model
    print("Created model with fresh parameters.")
  File "C:\Users\makke\ml\tensor\seq2seq_model.py", line 158, in __init__
    softmax_loss_function=softmax_loss_function)
  File "C:\Users\makke\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\contrib\legacy_seq2seq\python\ops\seq2seq.py", line 1180, in model_with_buckets
    decoder_inputs[:bucket[1]])
  File "C:\Users\makke\ml\tensor\seq2seq_model.py", line 157, in <lambda>
    lambda x, y: seq2seq_f(x, y, False),
  File "C:\Users\makke\ml\tensor\seq2seq_model.py", line 121, in seq2seq_f
    feed_previous=do_decode)
  File "C:\Users\makke\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\contrib\legacy_seq2seq\python\ops\seq2seq.py", line 850, in embedding_attention_seq2seq
    encoder_cell, encoder_inputs, dtype=dtype)
  File "C:\Users\makke\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\contrib\rnn\python\ops\core_rnn.py", line 197, in static_rnn
    (output, state) = call_cell()
  File "C:\Users\makke\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\contrib\rnn\python\ops\core_rnn.py", line 184, in <lambda>
    call_cell = lambda: cell(input_, state)
  File "C:\Users\makke\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\contrib\rnn\python\ops\core_rnn_cell_impl.py", line 595, in __call__
    embedding, array_ops.reshape(inputs, [-1]))
  File "C:\Users\makke\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\ops\embedding_ops.py", line 111, in embedding_lookup
    validate_indices=validate_indices)
  File "C:\Users\makke\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 1359, in gather
    validate_indices=validate_indices, name=name)
  File "C:\Users\makke\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "C:\Users\makke\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\ops.py", line 2395, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "C:\Users\makke\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\ops.py", line 1264, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): indices[47] = 20000 is not in [0, 20000)
         [[Node: model_with_buckets/embedding_attention_seq2seq_2/rnn/embedding_wrapper_14/embedding_lookup = Gather[Tindices=DT_INT32, Tparams=DT_FLOAT, _class=["loc:@embedding_attention_seq2seq/rnn/embedding_wrapper/embedding/read"], validate_indices=true, _device="/job:localhost/replica:0/task:0/cpu:0"](embedding_attention_seq2seq/rnn/embedding_wrapper/embedding/read, model_with_buckets/embedding_attention_seq2seq_2/rnn/embedding_wrapper_14/Reshape)]]

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
