### ISSUE TITLE
Win10 + Anaconda3  cannot install tensorflow-gpu

### ISSUE THREAD

**Issue by ericxumit** [tensorflow/tensorflow#23310]
Hi All,
Has been stuck for a few hours, hope to get some solutions.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Win10
- TensorFlow installed from (source or binary): pip install --ignore-installed --upgrade tensorflow-gpu
- Python version: Python 3.5.3
- CUDA/cuDNN version: CUDA 9.0, cuDNN 9.0
- GPU model and memory: NVIDIA 1050, 4GB

**Describe the current behavior**
Cannot install. Error message as below. 
(PY35) C:\>pip install --upgrade setuptools
Collecting setuptools
  Downloading https://files.pythonhosted.org/packages/82/a1/ba6fb41367b375f5cb653d1317d8ca263c636cff6566e2da1b0da716069d/setuptools-40.5.0-py2.py3-none-any.whl (569kB)
    100% |################################| 573kB 1.3MB/s
Installing collected packages: setuptools
  Found existing installation: setuptools 38.4.1
    Uninstalling setuptools-38.4.1:
      Successfully uninstalled setuptools-38.4.1
Successfully installed setuptools-40.5.0

(PY35) C:\>pip install --ignore-installed --upgrade tensorflow-gpu
Collecting tensorflow-gpu
  Using cached https://files.pythonhosted.org/packages/43/93/07f5cae2c8e02b37c4d64fa9c9eb1f8d3b39128247d0c1acd9110da45f67/tensorflow_gpu-1.11.0-cp35-cp35m-win_amd64.whl
Collecting six>=1.10.0 (from tensorflow-gpu)
  Using cached https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting tensorboard<1.12.0,>=1.11.0 (from tensorflow-gpu)
  Using cached https://files.pythonhosted.org/packages/9b/2f/4d788919b1feef04624d63ed6ea45a49d1d1c834199ec50716edb5d310f4/tensorboard-1.11.0-py3-none-any.whl
Collecting grpcio>=1.8.6 (from tensorflow-gpu)
  Using cached https://files.pythonhosted.org/packages/5e/8c/da9316699398607a22c91e39e16e4c0f3e8233e0faa88ed52df736f2b1d6/grpcio-1.16.0-cp35-cp35m-win_amd64.whl
Collecting keras-preprocessing>=1.0.3 (from tensorflow-gpu)
  Using cached https://files.pythonhosted.org/packages/fc/94/74e0fa783d3fc07e41715973435dd051ca89c550881b3454233c39c73e69/Keras_Preprocessing-1.0.5-py2.py3-none-any.whl
Collecting termcolor>=1.1.0 (from tensorflow-gpu)
  Using cached https://files.pythonhosted.org/packages/8a/48/a76be51647d0eb9f10e2a4511bf3ffb8cc1e6b14e9e4fab46173aa79f981/termcolor-1.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\ericx\appdata\local\conda\conda\envs\py35\lib\site-packages\setuptools\__init__.py", line 191, in <module>
        monkey.patch_all()
      File "c:\users\ericx\appdata\local\conda\conda\envs\py35\lib\site-packages\setuptools\monkey.py", line 101, in patch_all
        patch_for_msvc_specialized_compiler()
      File "c:\users\ericx\appdata\local\conda\conda\envs\py35\lib\site-packages\setuptools\monkey.py", line 138, in patch_for_msvc_specialized_compiler
        msvc = import_module('setuptools.msvc')
      File "c:\users\ericx\appdata\local\conda\conda\envs\py35\lib\importlib\__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "c:\users\ericx\appdata\local\conda\conda\envs\py35\lib\site-packages\setuptools\msvc.py", line 58, in <module>
        from distutils.msvc9compiler import Reg
      File "c:\users\ericx\appdata\local\conda\conda\envs\py35\lib\distutils\msvc9compiler.py", line 254
        log.debug("Unable to find vcvarsall.bat Eric edit C:\Users\ericx\AppData\Local\conda\conda\envs\r-tensorflow\Lib\site-packages\numpy\distutils")
                 ^
    SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 41-42: truncated \UXXXXXXXX escape

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\ericx\AppData\Local\Temp\pip-install-mxk6dgpl\termcolor\

**Describe the expected behavior**

**Code to reproduce the issue**
Cannot install, every time same error.

**Comment by aaniin** [comment]
Hi @ericxumit 
I'm not a tensorflow pro either (yet). To me it looks like you need to install Visual Studio.
Simply google your error "Unable to find vcvarsall.bat" and find for example this one:
https://blogs.msdn.microsoft.com/pythonengineering/2016/04/11/unable-to-find-vcvarsall-bat/
