### ISSUE TITLE
tflite_convert - ValueError: Invalid tensors 'input' were found.

### ISSUE THREAD

**Issue by ramtin2080** [tensorflow/tensorflow#23319]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Linux Ubuntu 18.04
- TensorFlow installed from (source or binary):
Installed from binary.
- TensorFlow version: Apparently this problem exists in all versions.  The versions I have tested: 1.5 | 1.11 | 1.12.0-rc2 | tf-nightly
- Python version: 3.6
- CUDA/cuDNN version: I have the CPU version.
- GPU model and memory: I have the CPU version.

**Describe the current behavior**
I want to convert Mobilenet_0.50_224 frozen graph using tflite_convert or toco to a TensorFlow Lite model, but I get the following error:
`2018-10-27 21:31:49.213953: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Traceback (most recent call last):
  File "/home/ramtin/Desktop/Model/venv/bin/tflite_convert", line 11, in <module>
    sys.exit(main())
  File "/home/ramtin/Desktop/Model/venv/lib/python3.6/site-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 412, in main
    app.run(main=run_main, argv=sys.argv[:1])
  File "/home/ramtin/Desktop/Model/venv/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/home/ramtin/Desktop/Model/venv/lib/python3.6/site-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 408, in run_main
    _convert_model(tflite_flags)
  File "/home/ramtin/Desktop/Model/venv/lib/python3.6/site-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 100, in _convert_model
    converter = _get_toco_converter(flags)
  File "/home/ramtin/Desktop/Model/venv/lib/python3.6/site-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 87, in _get_toco_converter
    return converter_fn(**converter_kwargs)
  File "/home/ramtin/Desktop/Model/venv/lib/python3.6/site-packages/tensorflow/contrib/lite/python/lite.py", line 283, in from_frozen_graph
    sess.graph, input_arrays)
  File "/home/ramtin/Desktop/Model/venv/lib/python3.6/site-packages/tensorflow/contrib/lite/python/convert_saved_model.py", line 189, in get_tensors_from_tensor_names
    ",".join(invalid_tensors)))
ValueError: Invalid tensors 'input' were found.
`
**Describe the expected behavior**
 tflite_convert could be able to convert the frozen graph to a tflite model successfully.
**Code to reproduce the issue**
I run the following command:
```
tflite_convert \
  --output_file=foo.tflite \
  --graph_def_file=frozen_graph.pb \
  --input_arrays=input \
  --output_arrays=MobilenetV1/Predictions/Reshape_1
```

**Other info / logs**
I have tried this on both the default Mobilenet_0.50_224 frozen graph and the retrained graph which is the output of retrain.py script from [Tensorflow for poets 2].(https://github.com/googlecodelabs/tensorflow-for-poets-2/blob/master/scripts/retrain.py)
I also tried to use toco, but the result was the same.
However, I can optimize the graph for Tensorflow Mobile without any  problem.

**Comment by ramtin2080** [comment]
Update: I installed "Ubuntu 16.04.3 LTS" and now the problem is solved.

**Comment by AliceDinh** [comment]
I have this error on WINDOW 10
