### ISSUE TITLE
i encounter very strange and serious Bug with dataset feeding （Emergency）

### ISSUE THREAD

**Issue by henryatman** [tensorflow/tensorflow#23323]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information** MAC OS 10.14 And Ubuntu 18 either
- TensorFlow version (you are using): 1.11.0

My model is LSTM + DNN, dataset structure is:

[
    [ [1,2,3],4,5,6 ],
    [ [11,22,33],44,55,66 ],
    [ [4,5,6],7,8,9 ],
]

convert to Dict is

{
    a: [ [1,2,3], [11,22,33], [4,5,6] ]
    b: [4,44,7]
    c: [5,55,8]
    d: [6,66,9]
}

it's work well but when LSTM exceed 31 step, i will reshape feature "a" to (time_step, columns) for LSTM input, when time_step more than 31, like 32, 33..., software will crash, and show bug info below:

`Retval[0] does not have value`

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1295, in _do_call
    return fn(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1277, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1375, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Retval[0] does not have value

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "estimator.py", line 340, in <module>
    tf.app.run(main)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "estimator.py", line 275, in main
    steps=args.train_steps
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 356, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1181, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1215, in _train_model_default
    saving_listeners)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1409, in _train_with_estimator_spec
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 671, in run
    run_metadata=run_metadata)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1148, in run
    run_metadata=run_metadata)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1239, in run
    raise six.reraise(*original_exc_info)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1224, in run
    return self._sess.run(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1296, in run
    run_metadata=run_metadata)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1076, in run
    return self._sess.run(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 887, in run
    run_metadata_ptr)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1110, in _run
    feed_dict_tensor, options, run_metadata)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1286, in _do_run
    run_metadata)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1314, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Retval[0] does not have value
``` 

i'm first think reason is data too long，so i change and reduce columns (32, 50) to (32, 30), (32, 10), (32, 1), it's can't work, but i change and reduce shape to (31, 50), (31, 30), (31, 60), (32, 1), (16, 60), (2, 16) it's work well, just say, when LSTM time step exceed 31, Tensorflow can't work,

**Who will benefit with this fix?**

every one

**Any Other info.**

i use tech beblow:

1. tensorflow estimator + dataset,
2. RNN ( LSTM + MUILTI + Dynamic),
3. DNN( fully connected layer )

it's strange Bug and important Bug, even cause i can't running completely now，hope official can fix Bug as soon as possible，very thanks

**Comment by ymodak** [comment]
Can you please out together a minimal example to reproduce this bug? It will help us to save time from the troubleshooting and we can focus more on the actual issue. Thanks!

**Comment by ppwwyyxx** [comment]
The same bug (RNN failed for length > 31) has been reported already with a minimal reproducible example, for almost a year, without a fix. The oldest issue is at this link: https://github.com/tensorflow/tensorflow/issues/15874.

**Comment by skye** [comment]
Please see my comment on #15874.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @skye: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.
