### ISSUE TITLE
AttributeError: 'module' object has no attribute 'Model'

### ISSUE THREAD

**Issue by wangyongqi** [tensorflow/tensorflow#23338]
This is my TensorFlow configuration.
tensorflow-gpu          1.5.0
Keras                  2.2.4    
cuda           8.0
cudnn       6.0
The following error occurred when I tried to run the TensorFlow SSD-mobilenet model.
root@VM-0-15-ubuntu:/mine/models/research# python object_detection/model_main.py --train_dir object_detection/train --pipeline_config_path object_detection/ssd_model/ssd_mobilenet_v1_pets.config
/usr/lib/python2.7/dist-packages/matplotlib/__init__.py:1352: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
Traceback (most recent call last):
  File "object_detection/model_main.py", line 26, in <module>
    from object_detection import model_lib
  File "/usr/local/lib/python2.7/dist-packages/object_detection-0.1-py2.7.egg/object_detection/model_lib.py", line 28, in <module>
    from object_detection import inputs
  File "/usr/local/lib/python2.7/dist-packages/object_detection-0.1-py2.7.egg/object_detection/inputs.py", line 26, in <module>
    from object_detection.builders import model_builder
  File "/usr/local/lib/python2.7/dist-packages/object_detection-0.1-py2.7.egg/object_detection/builders/model_builder.py", line 22, in <module>
    from object_detection.builders import box_predictor_builder
  File "/usr/local/lib/python2.7/dist-packages/object_detection-0.1-py2.7.egg/object_detection/builders/box_predictor_builder.py", line 21, in <module>
    from object_detection.predictors import convolutional_box_predictor
  File "/usr/local/lib/python2.7/dist-packages/object_detection-0.1-py2.7.egg/object_detection/predictors/convolutional_box_predictor.py", line 19, in <module>
    from object_detection.core import box_predictor
  File "/usr/local/lib/python2.7/dist-packages/object_detection-0.1-py2.7.egg/object_detection/core/box_predictor.py", line 137, in <module>
    class KerasBoxPredictor(tf.keras.Model):
AttributeError: 'module' object has no attribute 'Model'

Try the same mistakes with tensorflow-gpu 1.4 and 1.5, and try changing the Keras version but still have the same problem.

Who can help me? Thank you very much.

**Comment by PINTO0309** [comment]
@wangyongqi 
Will not it improve even if Tensorflow is upgraded to 1.9.0 or higher?
https://stackoverflow.com/questions/51701247/tensorflow-object-detection-custom-data-set
