### ISSUE TITLE
"EncapsulateTPUComputationsPass failed" on a model with Conv3D and Dropout layers

### ISSUE THREAD

**Issue by ftokarev** [tensorflow/tensorflow#23350]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.11.0
- Python version: 3.6.6
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a
- TPU version: v3.8

The model fails to run on a TPU. Here is a code snippet to reproduce the issue:

```
from tensorflow.keras.layers import Conv3D, Dropout, Input
import tensorflow as tf
import tensorflow.keras.backend as K


K.set_image_data_format("channels_last")


BATCH_SIZE = 8
INPUT_SIZE = (80, 40, 20, 3)
OUTPUT_SIZE = (40, 20, 10, 32)


TPU = "<tpu-name>"
TPU_ZONE = "europe-west4-a"
GCP_PROJECT = "<gcp-project>"
MODEL_DIR = "gs://<gcs-bucket>"


def input_fn(params):
    return (
        tf.random_uniform((BATCH_SIZE, *INPUT_SIZE)),
        tf.random_uniform((BATCH_SIZE, *OUTPUT_SIZE)))


def model_fn(features, labels, mode, params):
    x = Input(tensor=features)
    x = Conv3D(filters=32, kernel_size=(5, 5, 5), padding='same', strides=2)(x)
    x = Dropout(0.5)(x)
    loss = tf.losses.mean_squared_error(labels, x)
    optimizer = tf.train.AdamOptimizer()
    optimizer = tf.contrib.tpu.CrossShardOptimizer(optimizer)
    train_op = optimizer.minimize(loss, global_step=tf.train.get_global_step())
    return tf.contrib.tpu.TPUEstimatorSpec(mode=mode, loss=loss, train_op=train_op)


tpu_cluster_resolver = tf.contrib.cluster_resolver.TPUClusterResolver(TPU,
                                                                      zone=TPU_ZONE,
                                                                      project=GCP_PROJECT)

session_config = tf.ConfigProto(allow_soft_placement=True, log_device_placement=True)
tpu_config = tf.contrib.tpu.TPUConfig(iterations_per_loop=1, num_shards=8)
run_config = tf.contrib.tpu.RunConfig(cluster=tpu_cluster_resolver,
                                      model_dir=MODEL_DIR,
                                      save_checkpoints_secs=3600,
                                      session_config=session_config,
                                      tpu_config=tpu_config)

estimator = tf.contrib.tpu.TPUEstimator(
    model_fn=model_fn,
    use_tpu=True,
    config=run_config,
    train_batch_size=8)
estimator.train(input_fn=input_fn, max_steps=2)
```

Full stack trace:

```
WARNING:tensorflow:Estimator's model_fn (<function model_fn at 0x7fdd54a11158>) includes params argument, but params are not passed to Estimator.
2018-10-29 13:02:51.199228: W tensorflow/core/distributed_runtime/rpc/grpc_session.cc:349] GrpcSession::ListDevices will initialize the session with an empty graph and other defaults because the session has not yet been created.
WARNING:tensorflow:Reraising captured error
Traceback (most recent call last):
  File "/opt/miniconda3/envs/tpu-tf-1.11/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1292, in _do_call
    return fn(*args)
  File "/opt/miniconda3/envs/tpu-tf-1.11/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1275, in _run_fn
    self._extend_graph()
  File "/opt/miniconda3/envs/tpu-tf-1.11/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1312, in _extend_graph
    tf_session.ExtendSession(self._session)
tensorflow.python.framework.errors_impl.InvalidArgumentError: {{node gradients/dropout/cond/dropout/div_grad/Neg/Enter}} has inputs from different frames. The input {{node dropout/cond/dropout/div/Switch}} is in frame 'while_context'. The input {{node TPUReplicateMetadata}} is in frame ''.
        EncapsulateTPUComputationsPass failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dropout_issue.py", line 54, in <module>
    estimator.train(input_fn=input_fn, max_steps=2)
  File "/opt/miniconda3/envs/tpu-tf-1.11/lib/python3.6/site-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2400, in train
    rendezvous.raise_errors()
  File "/opt/miniconda3/envs/tpu-tf-1.11/lib/python3.6/site-packages/tensorflow/contrib/tpu/python/tpu/error_handling.py", line 128, in raise_errors
    six.reraise(typ, value, traceback)
  File "/opt/miniconda3/envs/tpu-tf-1.11/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/miniconda3/envs/tpu-tf-1.11/lib/python3.6/site-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2394, in train
    saving_listeners=saving_listeners
  File "/opt/miniconda3/envs/tpu-tf-1.11/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 356, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/opt/miniconda3/envs/tpu-tf-1.11/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1181, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/opt/miniconda3/envs/tpu-tf-1.11/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1215, in _train_model_default
    saving_listeners)
  File "/opt/miniconda3/envs/tpu-tf-1.11/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1406, in _train_with_estimator_spec
    log_step_count_steps=self._config.log_step_count_steps) as mon_sess:
  File "/opt/miniconda3/envs/tpu-tf-1.11/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 504, in MonitoredTrainingSession
    stop_grace_period_secs=stop_grace_period_secs)
  File "/opt/miniconda3/envs/tpu-tf-1.11/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 921, in __init__
    stop_grace_period_secs=stop_grace_period_secs)
  File "/opt/miniconda3/envs/tpu-tf-1.11/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 643, in __init__
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "/opt/miniconda3/envs/tpu-tf-1.11/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1107, in __init__
    _WrappedSession.__init__(self, self._create_session())
  File "/opt/miniconda3/envs/tpu-tf-1.11/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1112, in _create_session
    return self._sess_creator.create_session()
  File "/opt/miniconda3/envs/tpu-tf-1.11/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 800, in create_session
    self.tf_sess = self._session_creator.create_session()
  File "/opt/miniconda3/envs/tpu-tf-1.11/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 566, in create_session
    init_fn=self._scaffold.init_fn)
  File "/opt/miniconda3/envs/tpu-tf-1.11/lib/python3.6/site-packages/tensorflow/python/training/session_manager.py", line 287, in prepare_session
    sess.run(init_op, feed_dict=init_feed_dict)
  File "/opt/miniconda3/envs/tpu-tf-1.11/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 887, in run
    run_metadata_ptr)
  File "/opt/miniconda3/envs/tpu-tf-1.11/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1110, in _run
    feed_dict_tensor, options, run_metadata)
  File "/opt/miniconda3/envs/tpu-tf-1.11/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1286, in _do_run
    run_metadata)
  File "/opt/miniconda3/envs/tpu-tf-1.11/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1308, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: {{node gradients/dropout/cond/dropout/div_grad/Neg/Enter}} has inputs from different frames. The input {{node dropout/cond/dropout/div/Switch}} is in frame 'while_context'. The input {{node TPUReplicateMetadata}} is in frame ''.
        EncapsulateTPUComputationsPass failed
```

**Comment by ftokarev** [comment]
I ended up using `tf.layers.dropout` instead of `tensorflow.keras.layers.Dropout`

**Comment by harshini-gadige** [comment]
@ftokarev - So, is this still an issue with tf.layers.dropout ? Feel free to close if it's resolved.

**Comment by harshini-gadige** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. 

Please note that issues with _stat:awaiting response_ are closed if we do not receive any update from the user within 3 days. Thanks!

**Comment by chellary** [comment]
This happening even without Dropout. Any clue why this happening ?

tensorflow.python.framework.errors_impl.InvalidArgumentError: {{node seq2seq/loss/gradients/seq2seq/encoder1/bidirectional_rnn/bw/bw/cond_399/cond/Select_grad/Select/Enter}} has inputs from different frames. The input {{node seq2seq/encoder1/bidirectional_rnn/bw/bw/cond_399/cond/Select/Switch_1}} is in frame 'while_context'. The input {{node TPUReplicateMetadata}} is in frame ''.
        EncapsulateTPUComputationsPass failed
