### ISSUE TITLE
Failed to load

### ISSUE THREAD

**Issue by whydoyoumakeitsohard** [tensorflow/tensorflow#23355]
**System information**
- OS Platform and Distribution: Windows 10 x64
- TensorFlow installed from (source or binary):
- TensorFlow version: tensorflow_gpu-1.11.0
- Python version: Python 3.6.7
- Installed using: pip
- CUDA/cuDNN version: cuda 9.0 and cuDNN v7.3.1
- GPU model and memory: 1080 ti 11 GB

Running import tensorflow as tf returns: 

Traceback (most recent call last):
  File "C:\Users\Sebastian\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Sebastian\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Sebastian\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Sebastian\AppData\Local\Programs\Python\Python36\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Sebastian\AppData\Local\Programs\Python\Python36\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: Could not find the module.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import tensorflow as tf
  File "C:\Users\Sebastian\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\__init__.py", line 22, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\Sebastian\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Sebastian\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Sebastian\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Sebastian\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Sebastian\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Sebastian\AppData\Local\Programs\Python\Python36\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Sebastian\AppData\Local\Programs\Python\Python36\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: Could not find the module.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

I guess my problem is something with the paths. I have added the following: 
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\lib\x64

**Comment by harshini-gadige** [comment]
@whydoyoumakeitsohard  - Hi, try installing Microsoft Visual C++ 2015 Redistributable Update 3 and see if you are running into this error.

Also please try with CUDA9 and cuDNN 7.0.5

**Comment by whydoyoumakeitsohard** [comment]
Hi, thank you for your answer. 

Installing Microsoft Visual C++ 2015 Redistributable Update 3 did resolve the problem.
I'm pretty sure something is wrong with my path variables. I will read your link later, thanks.

**Comment by APotatoBoy** [comment]
I met the same problem as you. Have you got any solution?

**Comment by whydoyoumakeitsohard** [comment]
@harshini-gadige I have a working installation now by following the guide you linked, thanks alot!
@APotatoBoy Follow the link [above](https://www.pugetsystems.com/labs/hpc/The-Best-Way-to-Install-TensorFlow-with-GPU-Support-on-Windows-10-Without-Installing-CUDA-1187/) to install tensorflow with gpu-support through conda.

**Comment by harshini-gadige** [comment]
@whydoyoumakeitsohard  - Great !

**Comment by harshini-gadige** [comment]
Are you satisfied with the resolution of your issue?<br> [Yes](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=Yes&entry.2137816233=23355)<br> [No](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=No&entry.2137816233=23355)
