### ISSUE TITLE
"bazel test" fails on MacOS with setuptools-21.0

### ISSUE THREAD

**Issue by yaroslavvb** [tensorflow/tensorflow#2335]
I just went through official MacOS instructions to setup bazel/swig and tried the following

```
git clone --recurse-submodules https://github.com/tensorflow/tensorflow
cd tensorflow
./configure
bazel test -c opt //tensorflow/python/...
```

They all fail with stack trace like below, any suggestions?

```
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_yaroslavvb/ea642be0829ea15e6d2092d22e894d3d/tensorflow/bazel-out/local_darwin-opt/bin/tensorflow/python/zero_division_test.runfiles/tensorflow/python/kernel_tests/zero_division_test.py", line 22, in <module>
    import tensorflow as tf
  File "/Users/yaroslavvb/g/src/hacking/tensorflow/_python_build/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/Users/yaroslavvb/g/src/hacking/tensorflow/_python_build/tensorflow/python/__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/Users/yaroslavvb/g/src/hacking/tensorflow/_python_build/tensorflow/core/framework/graph_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/Library/Python/2.7/site-packages/protobuf-3.0.0b2-py2.7.egg/google/__init__.py", line 1, in <module>

  File "/Library/Python/2.7/site-packages/setuptools-21.0.0-py2.7.egg/pkg_resources/__init__.py", line 2927, in <module>

  File "/Library/Python/2.7/site-packages/setuptools-21.0.0-py2.7.egg/pkg_resources/__init__.py", line 2913, in _call_aside

  File "/Library/Python/2.7/site-packages/setuptools-21.0.0-py2.7.egg/pkg_resources/__init__.py", line 2952, in _initialize_master_working_set

  File "/Library/Python/2.7/site-packages/setuptools-21.0.0-py2.7.egg/pkg_resources/__init__.py", line 956, in subscribe

  File "/Library/Python/2.7/site-packages/setuptools-21.0.0-py2.7.egg/pkg_resources/__init__.py", line 2952, in <lambda>

  File "/Library/Python/2.7/site-packages/setuptools-21.0.0-py2.7.egg/pkg_resources/__init__.py", line 2515, in activate

  File "/Library/Python/2.7/site-packages/setuptools-21.0.0-py2.7.egg/pkg_resources/__init__.py", line 2097, in declare_namespace

  File "/Library/Python/2.7/site-packages/setuptools-21.0.0-py2.7.egg/pkg_resources/__init__.py", line 2047, in _handle_ns

  File "/Library/Python/2.7/site-packages/setuptools-21.0.0-py2.7.egg/pkg_resources/__init__.py", line 2066, in _rebuild_mod_path

  File "/Library/Python/2.7/site-packages/setuptools-21.0.0-py2.7.egg/pkg_resources/__init__.py", line 2064, in position_in_sys_path

ValueError: '/private/var/tmp/_bazel_yaroslavvb/4a326dbae226c596bf5de825a172dee9/tensorflow/bazel-out/local_darwin-opt/bin/tensorflow/tools/pip_package/build_pip_package.runfiles' is not in list
```

**Comment by yaroslavvb** [comment]
Googling suggested problem with new setuptools. Downgrading setuptools to version 19 fixes it

```
sudo rm -R /Library/Python/2.7/site-packages/setuptools*
sudo pip install setuptools==19.2 
bazel test -c opt //tensorflow/python:graph_util_test --test_output=streamed
```

**Comment by yaroslavvb** [comment]
Actually maybe this should be open because setuptools-21.0 is the default for new users and this issue was tricky to diagnose, maybe the installing for MacOS page could be updated to say that setuptools-21.0 is not supported? https://www.tensorflow.org/versions/r0.8/get_started/os_setup.html#installation-for-mac-os-x

**Comment by martinwicke** [comment]
Can we encode this requirement in the dependencies for the tensorflow pip package? Can tensorflow require setuptools=19.0?

**Comment by girving** [comment]
@yaroslavvb: What was the problem with the new setuptools?  Is it something we could work around, and is it possible to upgrade rather than downgrade to fix the problem?

**Comment by yaroslavvb** [comment]
I searched for "is not in list" and "setuptools" and found other people having this problem in other packages. Here's on description: https://lab.nexedi.cn/nexedi/wendelin.core/commit/2ce96a76421f942e8416ceeebf5088352b5fa1c7

Do you guys have a Mac CB setup yet?

**Comment by girving** [comment]
@yaroslavvb: What does "Mac CB" mean?

**Comment by yaroslavvb** [comment]
Mac continuous build/test

**Comment by girving** [comment]
@yaroslavvb: Yes we do, but it doesn't cover all versions of setuptools.   @martinwicke: Yaroslav's linked fix seems like something we could do.

**Comment by martinwicke** [comment]
So basically people hack around a problem in setuptools? This cannot be intended behavior?

**Comment by martinwicke** [comment]
FYI our Mac CI uses setuptools 18.3.1.

**Comment by gunan** [comment]
@yaroslavvb has this issue been resolved?
Mac builds seem to be pretty stable so far, but I have not checked the setuptools version on our mac machines.

**Comment by yaroslavvb** [comment]
This has a high chance of being fixed and/or irrelevant hence closing
