### ISSUE TITLE
tensorflow\contrib\coder\python\ops\_coder_ops.so not found

### ISSUE THREAD

**Issue by lunasdejavu** [tensorflow/tensorflow#23368]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
sample from matterport/maskrcnn
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):windows 10 x64
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below):
conda list
tensorflow-gpu            1.10.0                   py36_0    aaronzs
tensorflow-gpu            1.11.0                    <pip>
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
b'v1.10.0-rc1-19-g656e7a2b34' 1.10.0
- Python version:3.6.7
- CUDA/cuDNN version:9.0/7.1.4
- GPU model and memory:GeForce GTX 1060 3GB

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**
I tired to train a sample in the project from [https://github.com/matterport/Mask_RCNN](url)
then there is an error showed up.
I tried the basic functions of tensorflow like session they works fine.
but when I used train something about DLL showed up
it said that it can't find something like program input  "? MakeShape@TensorShapeUtils@tensorflow@@SA?AVStatus@2@V?$Span@$$CBH@absl@@PEAVTensorShape@2@@Z(in DLL C:\Users\willy_sung\AppData\Local\Continuum\anaconda3\envs\venv\lib\site-packages\tensorflow\contrib\coder\python\ops_coder_ops.so)"
**Describe the expected behavior**
there should be no error 
**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
there is no error until this line
`train(model)`
**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
Loading weights  C:\HSIR\Mask_RCNN\mask_rcnn_coco.h5
2018-10-30 15:35:55.918873: I T:\src\github\tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2018-10-30 15:35:56.255762: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1405] Found device 0 with properties:
name: GeForce GTX 1060 3GB major: 6 minor: 1 memoryClockRate(GHz): 1.759
pciBusID: 0000:01:00.0
totalMemory: 3.00GiB freeMemory: 2.42GiB
2018-10-30 15:35:56.255976: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1484] Adding visible gpu devices: 0
2018-10-30 15:35:56.948830: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:965] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-10-30 15:35:56.948953: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:971]      0
2018-10-30 15:35:56.953167: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:984] 0:   N
2018-10-30 15:35:56.954126: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1097] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 2125 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1060 3GB, pci bus id: 0000:01:00.0, compute capability: 6.1)
Training network heads
Traceback (most recent call last):
  File "balloon.py", line 364, in <module>
    train(model)
  File "balloon.py", line 199, in train
    layers='heads')
  File "C:\HSIR\Mask_RCNN\mrcnn\model.py", line 2341, in train
    histogram_freq=0, write_graph=True, write_images=False),
  File "C:\Users\willy_sung\AppData\Local\Continuum\anaconda3\envs\venv\lib\site-packages\keras\callbacks.py", line 745, in __init__
    from tensorflow.contrib.tensorboard.plugins import projector
  File "C:\Users\willy_sung\AppData\Local\Continuum\anaconda3\envs\venv\lib\site-packages\tensorflow\contrib\__init__.py", line 31, in <module>
    from tensorflow.contrib import coder
  File "C:\Users\willy_sung\AppData\Local\Continuum\anaconda3\envs\venv\lib\site-packages\tensorflow\contrib\coder\__init__.py", line 22, in <module>
    from tensorflow.contrib.coder.python.layers.entropybottleneck import *
  File "C:\Users\willy_sung\AppData\Local\Continuum\anaconda3\envs\venv\lib\site-packages\tensorflow\contrib\coder\python\layers\entropybottleneck.py", line 24, in <module>
    from tensorflow.contrib.coder.python.ops import coder_ops
  File "C:\Users\willy_sung\AppData\Local\Continuum\anaconda3\envs\venv\lib\site-packages\tensorflow\contrib\coder\python\ops\coder_ops.py", line 30, in <module>
    resource_loader.get_path_to_datafile("_coder_ops.so"))
  File "C:\Users\willy_sung\AppData\Local\Continuum\anaconda3\envs\venv\lib\site-packages\tensorflow\contrib\util\loader.py", line 56, in load_op_library
    ret = load_library.load_op_library(path)
  File "C:\Users\willy_sung\AppData\Local\Continuum\anaconda3\envs\venv\lib\site-packages\tensorflow\python\framework\load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: C:\Users\willy_sung\AppData\Local\Continuum\anaconda3\envs\venv\lib\site-packages\tensorflow\contrib\coder\python\ops\_coder_ops.so not found

**Comment by ymodak** [comment]
Not able to access your project from the link you provided 9https://github.com/matterport/Mask_RCNN).
Can you please update it? Thanks!

**Comment by ymodak** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by ymodak** [comment]
Thanks for the update. Can you please share your updated configuration which helped you solve your issue?

**Comment by lunasdejavu** [comment]
@ymodak  I used GPU with  3 GB, then my professor bought GTX 1060 with 6GB memory which solves the problem.

**Comment by user-ZJ** [comment]
at window10 platform, I used pip3 install --force-reinstall tensorflow-gpu==1.12.0 to fix the problem

**Comment by Angus1996** [comment]
I meet this problem when i was using Tensorflow-gpu 1.10.0；But this problem doesn't appear when I update the tensorflow to 1.11.0.
