### ISSUE TITLE
Is the tensorflow framework wrong?

### ISSUE THREAD

**Issue by zhouhao-learning** [tensorflow/tensorflow#23391]
When I use the tensorflow framework to train my model through the CPU, I get an tensorflow unexpected error.Error is as follows:
```
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1361, in _do_call
    return fn(*args)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1340, in _run_fn
    target_list, status, run_metadata)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.AbortedError: Operation received an exception:Status: 5, message: could not create a eltwise forward primitive descriptor, in file tensorflow/core/kernels/mkl_relu_op.cc:457
	 [[Node: DAGLayer_4/Relu = _MklRelu[T=DT_FLOAT, _kernel="MklOp", _device="/job:localhost/replica:0/task:0/device:CPU:0"](DAGLayer_4/xw_plus_b, DMT/_8)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/worker/bin/run.py", line 375, in task_main
    await module_run(api) if iscoroutinefunction(module_run) else module_run(api)
  File "/worker/package/smiles_package_DAG_qlaVw/train_model/__init__.py", line 135, in run
    callbacks=[processcallback])
  File "/worker/package/smiles_package_DAG_qlaVw/DAG_tensorgraph.py", line 91, in fit_generator
    fetched_values = self.session.run(fetches, feed_dict=train_generator)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 905, in run
    run_metadata_ptr)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1137, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1355, in _do_run
    options, run_metadata)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1374, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.AbortedError: Operation received an exception:Status: 5, message: could not create a eltwise forward primitive descriptor, in file tensorflow/core/kernels/mkl_relu_op.cc:457
	 [[Node: DAGLayer_4/Relu = _MklRelu[T=DT_FLOAT, _kernel="MklOp", _device="/job:localhost/replica:0/task:0/device:CPU:0"](DAGLayer_4/xw_plus_b, DMT/_8)]]

Caused by op 'DAGLayer_4/Relu', defined at:
  File "main.py", line 32, in <module>
    main()
  File "main.py", line 28, in main
    router.task_run()
  File "/worker/bin/router.py", line 129, in task_run
    p.start()
  File "/usr/local/anaconda3/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/local/anaconda3/lib/python3.6/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/local/anaconda3/lib/python3.6/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/local/anaconda3/lib/python3.6/multiprocessing/popen_fork.py", line 26, in __init__
    self._launch(process_obj)
  File "/usr/local/anaconda3/lib/python3.6/multiprocessing/popen_fork.py", line 80, in _launch
    code = process_obj._bootstrap()
  File "/usr/local/anaconda3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/anaconda3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/worker/bin/router.py", line 111, in run_worker
    run([worker])
  File "/atlas/home/test/.local/lib/python3.6/site-packages/autobahn/asyncio/component.py", line 373, in run
    loop.run_forever()
  File "/usr/local/anaconda3/lib/python3.6/asyncio/base_events.py", line 421, in run_forever
    self._run_once()
  File "/usr/local/anaconda3/lib/python3.6/asyncio/base_events.py", line 1431, in _run_once
    handle._run()
  File "/usr/local/anaconda3/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/worker/bin/router.py", line 38, in onJoin
    api = await task_main(task_id)
  File "/worker/bin/run.py", line 375, in task_main
    await module_run(api) if iscoroutinefunction(module_run) else module_run(api)
  File "/worker/package/smiles_package_DAG_qlaVw/train_model/__init__.py", line 115, in run
    model = DAG_fit.load_from_dir(model_dir)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/deepchem/models/tensorgraph/tensor_graph.py", line 818, in load_from_dir
    tensorgraph.restore()
  File "/usr/local/anaconda3/lib/python3.6/site-packages/deepchem/models/tensorgraph/tensor_graph.py", line 785, in restore
    self.build()
  File "/usr/local/anaconda3/lib/python3.6/site-packages/deepchem/models/tensorgraph/tensor_graph.py", line 476, in build
    layer.create_tensor(training=self._training_placeholder)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/deepchem/models/tensorgraph/graph_layers.py", line 686, in create_tensor
    batch_outputs = self.DAGgraph_step(batch_inputs, self.W_list, self.b_list)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/deepchem/models/tensorgraph/graph_layers.py", line 705, in DAGgraph_step
    outputs = self.activation(outputs)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/deepchem/models/tensorgraph/activations.py", line 96, in relu
    return model_ops.relu(x, alpha=alpha, max_value=max_value)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/deepchem/models/tensorgraph/model_ops.py", line 516, in relu
    x = tf.nn.relu(x)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 4331, in relu
    "Relu", features=features, name=name)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3271, in create_op
    op_def=op_def)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1650, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

AbortedError (see above for traceback): Operation received an exception:Status: 5, message: could not create a eltwise forward primitive descriptor, in file tensorflow/core/kernels/mkl_relu_op.cc:457
	 [[Node: DAGLayer_4/Relu = _MklRelu[T=DT_FLOAT, _kernel="MklOp", _device="/job:localhost/replica:0/task:0/device:CPU:0"](DAGLayer_4/xw_plus_b, DMT/_8)]]
```

I managed to train this model on my GPU by running a model built by tensorflow, but I got this unexpected error when I used CPU training.

Why can't I train on the CPU? My version of tensorflow is 1.6, please give me some guidance, thank you!

**Comment by pldelisle** [comment]
There is missing too much information. Did you compile TensorFlow from source ? 

As I can see first, it seems like there is an error with an operator from MKL (Math Kernel Library) operator. Seems like to compiled TensorFlow using config=mkl. Is this right ?

Redo your issue using a template : https://github.com/tensorflow/tensorflow/issues/new/choose

**Comment by harshini-gadige** [comment]
It looks like you haven't used a template to create this issue. Please resubmit your issue using a template from [here](https://github.com/tensorflow/tensorflow/issues/new/choose). We ask users to use the template because it reduces overall time to resolve a new issue by avoiding extra communication to get to the root of the issue. Thank you for your cooperation.

**Comment by harshini-gadige** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
