### ISSUE TITLE
parallel_for: No converter defined for MaxPoolGradGrad

### ISSUE THREAD

**Issue by jonasrauber** [tensorflow/tensorflow#23397]
I have written a `fwd_gradients`-based implementation of `batch_jacobian` (comparable to the `tf.gradients`-based `tensorflow.python.ops.parallel_for.batch_jacobian`). To efficiently implement `batch_jacobian`, TensorFlow added support `parallel_for`: unfortunately, `pfor` does not support the `MaxPoolGradGrad` op, requiring a fallback to a slow while loop. For performance reasons, it would be great to add a converter for `MaxPoolGradGrad` to `parallel_for`.

**Code to reproduce the issue**
The following code is a minimal example to reproduce the issue and can be run as is.

```python
#!/usr/bin/env python3
import tensorflow as tf
from tensorflow.python.ops.parallel_for import control_flow_ops
from tensorflow.contrib.nn.python.ops.fwd_gradients import fwd_gradients
from tensorflow.python.platform import flags
import sys
import numpy as np


def main():
    sess = tf.InteractiveSession()

    print(tf.__version__)

    flags.FLAGS(sys.argv)

    x = tf.placeholder(tf.float32, (None, 2, 2, 1))
    y = tf.nn.max_pool(x, (1, 2, 2, 1), strides=(1, 1, 1, 1), padding='SAME')

    input_shape = tf.shape(x)
    batch_size = input_shape[0]

    input_size = 4
    one_hot_vectors = tf.eye(input_size)

    def loop_fn(i):
        one_hot = tf.gather(one_hot_vectors, i)
        one_hot = one_hot[tf.newaxis]
        grad_inputs = tf.tile(one_hot, (batch_size, 1))
        grad_inputs = tf.reshape(grad_inputs, input_shape)
        g = fwd_gradients([y], [x], [grad_inputs])
        assert len(g) == 1
        print(g[0])
        return g[0]

    J = control_flow_ops.pfor(loop_fn, 4)

    x_ = np.array([4, 1, 2, 3]).reshape(1, 2, 2, 1)
    y_, J_ = sess.run([y, J], feed_dict={x: x_})
    print(x_.squeeze())
    print(y_.squeeze())
    print(J_.squeeze())


if __name__ == '__main__':
    main()
```

**Describe the current behavior**
```
1.11.0
Tensor("loop_body/gradients_1/loop_body/gradients/MaxPool_grad/MaxPoolGrad_grad/MaxPoolGradGrad:0", shape=(?, 2, 2, 1), dtype=float32)
Traceback (most recent call last):
  File "./minimal_example.py", line 46, in <module>
    main()
  File "./minimal_example.py", line 36, in main
    J = control_flow_ops.pfor(loop_fn, 4)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/parallel_for/control_flow_ops.py", line 129, in pfor
    outputs.append(converter.convert(loop_fn_output))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/parallel_for/pfor.py", line 1077, in convert
    output = self._convert_helper(y)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/parallel_for/pfor.py", line 1223, in _convert_helper
    "which may run slower" % (y_op.type, y_op, converted_inputs))
ValueError: No converter defined for MaxPoolGradGrad
name: "loop_body/gradients_1/loop_body/gradients/MaxPool_grad/MaxPoolGrad_grad/MaxPoolGradGrad"
op: "MaxPoolGradGrad"
input: "Placeholder"
input: "MaxPool"
input: "loop_body/gradients_1/grad_ys_0"
attr {
  key: "T"
  value {
    type: DT_FLOAT
  }
}
attr {
  key: "data_format"
  value {
    s: "NHWC"
  }
}
attr {
  key: "ksize"
  value {
    list {
      i: 1
      i: 2
      i: 2
      i: 1
    }
  }
}
attr {
  key: "padding"
  value {
    s: "SAME"
  }
}
attr {
  key: "strides"
  value {
    list {
      i: 1
      i: 1
      i: 1
      i: 1
    }
  }
}

inputs: [WrappedTensor(t=<tf.Tensor 'Placeholder:0' shape=(?, 2, 2, 1) dtype=float32>, is_stacked=False, is_sparse_stacked=False), WrappedTensor(t=<tf.Tensor 'MaxPool:0' shape=(?, 2, 2, 1) dtype=float32>, is_stacked=False, is_sparse_stacked=False), WrappedTensor(t=<tf.Tensor 'loop_body/gradients_1/grad_ys_0/pfor/Identity:0' shape=(4, ?, 2, 2, 1) dtype=float32>, is_stacked=True, is_sparse_stacked=False)]. 
Either add a converter or set --op_conversion_fallback_to_while_loop=True, which may run slower
```

**Describe the expected behavior**
(produced by running the above script with `--op_conversion_fallback_to_while_loop`)

```
1.11.0
Tensor("loop_body/gradients_1/loop_body/gradients/MaxPool_grad/MaxPoolGrad_grad/MaxPoolGradGrad:0", shape=(?, 2, 2, 1), dtype=float32)
WARNING:tensorflow:Using a while_loop for converting MaxPoolGradGrad
[[4 1]
 [2 3]]
[[4. 3.]
 [3. 3.]]
[[[1. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 1.]
  [1. 1.]]]
```

P.S. If you are interested, I'd be happy to contribute my `fwd_gradients`-based `batch_jacobian` to TensorFlow once this performance issue with MaxPool ops is fixed and I've cleaned up my code.

**Comment by agarwal-ashish** [comment]
A converter for MaxPoolGradGrad has been added and should make its way to a nightly build soon.

However I suspect there might be a bunch of other ops that would turn up as not having converters given that you are relying on second order gradients.

**Comment by jonasrauber** [comment]
Thanks @agarwal-ashish for fixing this so fast! Works :)
