### ISSUE TITLE
Couldn't find field google.protobuf.FileOptions.javanano_use_deprecated_package"

### ISSUE THREAD

**Issue by rawandeheliah** [tensorflow/tensorflow#23411]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Ubunto 16.04

- TensorFlow version: 1.4.0
- Python version:2.7.1
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source):

whenever i run a command such as : python pythonFile.py
i got this error : 
Traceback (most recent call last):
  File "111.py", line 1, in <module>
    import tensorflow as tf
  File "/home/lenovo/.local/lib/python2.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/home/lenovo/.local/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 54, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/home/lenovo/.local/lib/python2.7/site-packages/tensorflow/core/framework/graph_pb2.py", line 10, in <module>
    from google.protobuf import descriptor_pb2
  File "/home/lenovo/.local/lib/python2.7/site-packages/google/protobuf/descriptor_pb2.py", line 964, in <module>
    options=None),
  File "/home/lenovo/.local/lib/python2.7/site-packages/google/protobuf/descriptor.py", line 505, in __new__
    return _message.default_pool.FindFieldByName(full_name)
KeyError: "Couldn't find field google.protobuf.FileOptions.javanano_use_deprecated_package"

i tried all solutions such as uninstalling and installing protobuf==3.5.0.post1  , but nothing helped , any ideas ?

**Comment by ymodak** [comment]
Can you please upgrade to the latest version of TensorFlow and build again?

**Comment by ymodak** [comment]
Is this still an issue for you?

**Comment by ymodak** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
