### ISSUE TITLE
a  confused problem about placeholder

### ISSUE THREAD

**Issue by sanlb** [tensorflow/tensorflow#23422]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Linux Ubuntu 16.04
- TensorFlow installed from (source or binary):from pycharm(+anaconda)
- TensorFlow version (use command below):1.9
- Python version:3.6
- CUDA/cuDNN version:8.0/5.1
- GPU model and memory:1060/6g

I want to  give values of lr and beta1 to adam with placeholder but there is an error'You must feed a value for placeholder tensor 'm' with dtype float'. it's confused because when i fix the beta1=0.5, the lr can deliver to the adam, once i want to deliver lr and beta1 to adam there will be error. 

`def build_training_pi_graph(x, y, ul_x, lr, unsup_weight, m):
    global_step = tf.get_variable(
        name="global_step",
        shape=[],
        dtype=tf.float32,
        initializer=tf.constant_initializer(0.0),
        trainable=False,
    )

    z_label1 = PiModels.call(x)
    z_label2 = PiModels.call(x)

    z_unlabeled1 = PiModels.call(ul_x)
    z_unlabeled2 = PiModels.call(ul_x)
    with tf.variable_scope(tf.get_variable_scope(), reuse=True):
        ce = tf.losses.softmax_cross_entropy(z_label1, y)
        ul_loss = tf.losses.mean_squared_error(z_label1, z_label2)
        l_loss = tf.losses.mean_squared_error(z_unlabeled1, z_unlabeled2)
        loss = ce + unsup_weight * (ul_loss + l_loss)

    opt = tf.train.AdamOptimizer(learning_rate=lr, beta1=m, beta2=0.999)
    tvars = tf.trainable_variables()
    grads_and_vars = opt.compute_gradients(loss, tvars)
    train_op = opt.apply_gradients(grads_and_vars, global_step=global_step)

    return loss, train_op, global_step`
`def main():
    with tf.Graph().as_default() as g:

        with tf.device("/cpu:0"):
            train_labeled_iterator = inputs(batch_size=batch_size,
                                    train=True,
                                    validation=validation,
                                    shuffle=True, num_epochs=num_epochs+1000)
            train_x, train_y, label_index = train_labeled_iterator.get_next()

            train_unlabeled_iterator = unlabeled_inputs(batch_size=ul_batch_size,
                                        validation=validation,
                                         shuffle=True,num_epochs=num_epochs)
            ul_x, _, unlabel_index = train_unlabeled_iterator.get_next()

            validation_iterator = inputs(batch_size=eval_batch_size,
                                                          train=True,
                                                          validation=True,
                                                          shuffle=True)
            val_x, val_y, _ = validation_iterator.get_next()

            itest_iterator = inputs(batch_size=eval_batch_size,
                                                        train=False,
                                                        validation=validation,
                                                        shuffle=True)
            test_x, test_y, _= itest_iterator.get_next()

        with tf.device(device):
            lr = tf.placeholder(tf.float32, shape=[], name='learning_rate')
            unsupervised_weight = tf.placeholder(tf.float32, shape=[], name='unsupervised_weight')
            m = tf.placeholder(tf.float32, shape=[], name='m')
            with tf.variable_scope('CNN', reuse=tf.AUTO_REUSE):
                loss, train_op, global_step = build_training_pi_graph(train_x, train_y, ul_x, lr, unsupervised_weight, m)

            init_op = tf.global_variables_initializer()

        with tf.Session().as_default() as sess:
            sess.run(init_op)
            for ep in range(num_epochs):

                sum_loss = 0

                feed_dict = {lr: 0.001, unsupervised_weight: 0.5, m: 0.5}

                start = time.time()
                for i in range(num_iter_per_epoch):
                    batch_loss, _, _ = sess.run([loss, train_op, global_step], feed_dict=feed_dict)
                    sum_loss += batch_loss
                end = time.time()
                print('epoch:', ep, 'epoch train loss:', sum_loss / num_iter_per_epoch, 'epoch train time:',
                      end - start)

main()`

**Other info / logs**
Traceback (most recent call last):
  File "/home/zw/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1292, in _do_call
    return fn(*args)
  File "/home/zw/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1277, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/zw/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1367, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'm' with dtype float
	 [[{{node m}} = Placeholder[dtype=DT_FLOAT, shape=[], _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zw/PycharmProjects/self/tempens-self/piModel.py", line 172, in <module>
    main()
  File "/home/zw/PycharmProjects/self/tempens-self/piModel.py", line 157, in main
    sess.run(init_op)
  File "/home/zw/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 887, in run
    run_metadata_ptr)
  File "/home/zw/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1110, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/zw/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1286, in _do_run
    run_metadata)
  File "/home/zw/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1308, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'm' with dtype float
	 [[{{node m}} = Placeholder[dtype=DT_FLOAT, shape=[], _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

Caused by op 'm', defined at:
  File "/home/zw/PycharmProjects/self/tempens-self/piModel.py", line 172, in <module>
    main()
  File "/home/zw/PycharmProjects/self/tempens-self/piModel.py", line 146, in main
    m = tf.placeholder(tf.float32, shape=[], name='m')
  File "/home/zw/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 1745, in placeholder
    return gen_array_ops.placeholder(dtype=dtype, shape=shape, name=name)
  File "/home/zw/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 5020, in placeholder
    "Placeholder", dtype=dtype, shape=shape, name=name)
  File "/home/zw/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/zw/anaconda3/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/home/zw/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3272, in create_op
    op_def=op_def)
  File "/home/zw/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1768, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'm' with dtype float
	 [[{{node m}} = Placeholder[dtype=DT_FLOAT, shape=[], _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

any help, thanks

**Comment by harshini-gadige** [comment]
@aselle   PTAL

**Comment by tensorflowbutler** [comment]
Nagging Assignee @aselle: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by aselle** [comment]
The traceback tells you that you need to provide m. It tells you where, in the "init" call
i.e. change your sess.run(init_op) to sess.run(init_op, {m: .5})

**Comment by harshini-gadige** [comment]
Closing this as it is in "awaiting response" status for more than 7 days. Feel free to add your comments and we will reopen(if required).
