### ISSUE TITLE
Windows cluster: could not start gRPC server

### ISSUE THREAD

**Issue by ivan-marroquin** [tensorflow/tensorflow#23434]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.8.0
- Python version: 3.6.5
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: 9
- GPU model and memory:  Quadro K22000 with 3.34GB

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**
I have a cluster running on Windows 10 and wanted to test tensorflow on a distributed environment. As a test, I want to detect the video card installed on 3 machines. When I ran the code, I get the following error messages:

E1101 16:04:32.821000000 17460 server_chttp2.cc:40] {"created":"@1541106272.820000000","description":"No address added out of total 1 resolved","file":"T:\src\github\tensorflow\cmake_build\grpc\src\grpc\src\core\ext\transport\chttp2\server\chttp2_server.cc","file_line":307,"referenced_errors":[{"created":"@1541106272.820000000","description":"Failed to add port to server","file":"T:\src\github\tensorflow\cmake_build\grpc\src\grpc\src\core\lib\iomgr\tcp_server_windows.cc","file_line":508,"referenced_errors":[{"created":"@1541106272.820000000","description":"OS Error","file":"T:\src\github\tensorflow\cmake_build\grpc\src\grpc\src\core\lib\iomgr\tcp_server_windows.cc","file_line":200,"os_error":"Only one usage of each socket address (protocol/network address/port) is normally permitted.\r\n","syscall":"bind","wsa_error":10048}]}]}
Process Process-4:
Traceback (most recent call last):
  File "C:\Temp\Python\Python-3.6.5\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Temp\Python\Python-3.6.5\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\IMarroquin\Documents\My_Python_Scripts\MLP\Test_main_distributed.py", line 34, in find_amount_gpus
    server= tf.train.Server(spec, job_name= params.job_name, task_index= params.task_index)
  File "C:\Temp\Python\Python-3.6.5\lib\site-packages\tensorflow\python\training\server_lib.py", line 147, in __init__
    self._server_def.SerializeToString(), status)
  File "C:\Temp\Python\Python-3.6.5\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 519, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.UnknownError: Could not start gRPC server
EE11101 16:04:321.0976000000 17868 server_chttp2.1 16:04:32c.c976000000 16224 server_chttp2.cc:40] {"created":"@1541106272.976000000","description":"No address added out of total 1 resolved","file":"T:\src\github\tensorflow\cmake_build\grpc\src\grpc\src\core\ext\transport\chttp2\server\chttp2_server.cc","file_line":307:,40] {"created":"@1541106272.976000000","description":"No address added out of total 1 resolv"referenced_errors":[{"created":"@1541106272.976000000","description":"Failed to add port to server","filed","file":"T:\src\github\tensorflow\cmake_beu"ild\grpc\src\grpc\src\core\ext\transpo:rt\chttp2\server\chttp2_server.cc","file_line":307,"referenced_errors":[{"created":"@1541106272.976000000","descript"Ti:\src\github\tensorflow\cmake_build\grpc\src\grpc\src\core\lib\iomgr\tcp_server_windows.cc","file_line":508,"referenced_errors":[{"created":"@1541106272.9760000on":"Failed to add p0ort to0 server","file":"T:\src\github\tensorflow\cmake_bui"l,d\grpc\src\grpc\src\core\lib\iomgr\tcp_server_windows.cc","file_line":508,"referenced_errors":[{"crea"ted":"@1541106272.976000000","descriptdion":"OS Error","file":"T:\src\github\tensorflow\cmaeke_builds\grpc\src\grpc\src\core\lib\iomgr\tcp_secrirver_windows.cc","file_line":200,"os_error":"Only one usage option":"OS Error","file":"T:\src\github\tensorflow\cmake_build\grpc\src\grpc\src\core\lib\iomgr\tcp_server_windows.cc","file_line":200,"os_error":"Only one usage of eachf  seoach socket address (protocol/network address/port) is normally permitted.\r\n","syscall"c:"bind","wsa_error":10048}]}]}
ket addressProcess Process-2:
 (protocol/network addreTraceback (most recent call last):
ss  File "C:\Temp\Python\Python-3.6.5\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
/port) is normally permitted.\r\n","syscall":"bind","wsa_error"  File "C:\Temp\Python\Python-3.6.5\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
:10048}]}]}
  File "C:\Users\IMarroquin\Documents\My_Python_Scripts\MLP\Test_main_distributed.py", line 34, in find_amount_gpus
    server= tf.train.Server(spec, job_name= params.job_name, task_index= params.task_index)
  File "C:\Temp\Python\Python-3.6.5\lib\site-packages\tensorflow\python\training\server_lib.py", line 147, in __init__
    self._server_def.SerializeToString(), status)
Process Process-3:
  File "C:\Temp\Python\Python-3.6.5\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 519, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.UnknownError: Could not start gRPC server
Traceback (most recent call last):
  File "C:\Temp\Python\Python-3.6.5\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Temp\Python\Python-3.6.5\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\IMarroquin\Documents\My_Python_Scripts\MLP\Test_main_distributed.py", line 34, in find_amount_gpus
    server= tf.train.Server(spec, job_name= params.job_name, task_index= params.task_index)
  File "C:\Temp\Python\Python-3.6.5\lib\site-packages\tensorflow\python\training\server_lib.py", line 147, in __init__
    self._server_def.SerializeToString(), status)
  File "C:\Temp\Python\Python-3.6.5\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 519, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.UnknownError: Could not start gRPC server

**Describe the expected behavior**
I would like to be able to detect the video card and report it

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
Main.py file:

from multiprocessing import Process, Pipe
import tensorflow as tf
from tensorflow.contrib.training import HParams
from GPUs import gpus_configuration

N_workers= 3
SPEC_Second= {"ps": ["192.168.3.18:2222"], "worker": ["192.168.3.18:2222", "192.168.3.14:2222", "192.168.3.16:2222"]}

def find_amount_gpus(task, connection):
    spec= tf.train.ClusterSpec(SPEC_Second)
    
    params= HParams(cluster= spec, job_name= task[0], task_index= task[1])
    server= tf.train.Server(spec, job_name= params.job_name, task_index= params.task_index)
    
    if (params.job_name == "ps"):
        server.join()
    elif (params.job_name == "worker"):
        with tf.device(tf.train.replica_device_setter(worker_device= "/job:worker/task:%d" % params.task_index, cluster= spec)):
            gpus_configuration(connection)

if __name__ == '__main__':
    devices= [['ps', 0], ['worker', 0], ['worker', 1], ['worker', 2]]

jobs= []
    pipe_list= []
    
    for i in devices: #for i in range(0, 1):#N_workers):
        print("In loop to find GPUs {}\n".format(i))
        parent_conn, child_conn= Pipe()
        p= Process(target= find_amount_gpus, args=(i, child_conn))
        jobs.append(p)
        pipe_list.append(parent_conn)
        p.start()
    
    total_results= [out.recv() for out in pipe_list]
    
    Worker_1_gpus= total_results[0]['GPUs_info']
    Worker_1_ip= total_results[0]['IPaddr']
    print("Worker 1 {}\n".format(Worker_1_gpus))
    print("Worker 1 IP {}\n".format(Worker_1_ip))
    Worker_2_gpus= total_results[1]['GPUs_info']
    Worker_2_ip= total_results[1]['IPaddr']
    print("Worker 2 {}\n".format(Worker_2_gpus))
    print("Worker 2 IP {}\n".format(Worker_2_ip))
    Worker_3_gpus= total_results[2]['GPUs_info']
    Worker_3_ip= total_results[2]['IPaddr']
    print("Worker 3 {}\n".format(Worker_3_gpus))
    print("Worker 3 IP {}\n".format(Worker_3_ip))

GPUs.py file

import os
import tensorflow as tf
from tensorflow.python.client import device_lib
    
os.environ['TF_CPP_MIN_LOG_LEVEL'] = "3" # Turn off Tensorflow messages
os.environ["TF_MIN_GPU_MULTIPROCESSOR_COUNT"] = "4"

""" Determine presence of GPUs or CPUs
"""

def gpus_configuration(child_conn):
    import socket
    
    hostname= socket.gethostname()
    IPaddr= socket.gethostbyname(hostname)

    config= tf.ConfigProto()
    config.gpu_options.allow_growth= True            
    
    with tf.Session(config= config) as sess:
        local_device_protos= device_lib.list_local_devices()
        sess.close()

    gpus= len([x.name for x in local_device_protos if x.device_type == 'GPU'])
    
    total_results= {"GPUs_info": gpus,
                    "IPaddr": IPaddr}
    
    child_conn.send(total_results)

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by harshini-gadige** [comment]
@ivan-marroquin  -  PTAL at [this.](https://stackoverflow.com/questions/45269790/tensorflow-multoprocessing-unknownerror-could-not-start-grpc-server)

**Comment by ivan-marroquin** [comment]
Hi @harshini-gadige ,

Thanks for the suggestion to check the ticket. I will do so. About the suggestion of using the latest version of tensorflow. Are you referring to 1.11? Is this version compatible with cuda 9?

Ivan

**Comment by harshini-gadige** [comment]
@ivan-marroquin  - Yes. Try with the below combination.

![image](https://user-images.githubusercontent.com/42781361/47926427-c3ad6880-de7d-11e8-9fac-a422138755e1.png)

**Comment by ivan-marroquin** [comment]
Hi @harshini-gadige , I will give a try next Monday and let you know. By the way, does gRPC use a TCP/IP connection?

**Comment by ivan-marroquin** [comment]
Hi @harshini-gadige , I updated tensorflow to version 1.11 as suggested. Unfortunately, I still have the same issue. For some reason the gRPC can't be started. I went to examine code examples on tensorflow distributed - as per your suggestion, and I rewrote the main Python script as follows:

def find_amount_gpus(device, connection):
    spec= tf.train.ClusterSpec(SPEC_Second)
    server= tf.train.Server(spec, job_name= device[0], task_index= device[1])
   
    if (device[0] == "ps"):
        server.join()

    if (device[0] == "worker"):
        with tf.device(tf.train.replica_device_setter(worker_device= "/job:worker/task:%d" % device[1], cluster= spec)):
            gpus_configuration(connection)

if __name__ == '__main__':
    devices= [["ps", 0], ["worker", 0], ["worker", 1]]
    jobs= []
    pipe_list= []
    
    for i in devices: #for i in range(0, 1):#N_workers):
        parent_conn, child_conn= Pipe()
        p= Process(target= find_amount_gpus, args=(i, child_conn), daemon= True)
        jobs.append(p)
        pipe_list.append(parent_conn)
        p.start()
    
    total_results= [out.recv() for out in pipe_list]


Below you will find the entire error log:

E1105 15:50:49.242000000 17544 external/grpc/src/core/ext/transport/chttp2/server/insecure/server_chttp2.cc:40] {"created":"@1541454649.242000000","description":"No address added out of total 1 resolved","file":"external/grpc/src/core/ext/transport/chttp2/server/chttp2_server.cc","file_line":307,"referenced_errors":[{"created":"@1541454649.242000000","description":"Failed to add port to server","file":"external/grpc/src/core/lib/iomgr/tcp_server_windows.cc","file_line":509,"referenced_errors":[{"created":"@1541454649.242000000","description":"OS Error","file":"external/grpc/src/core/lib/iomgr/tcp_server_windows.cc","file_line":201,"os_error":"Only one usage of each socket address (protocol/network address/port) is normally permitted.\r\n","syscall":"bind","wsa_error":10048}]}]}
Process Process-3:
Traceback (most recent call last):
  File "C:\Temp\Python\Python-3.6.5\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Temp\Python\Python-3.6.5\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\IMarroquin\Documents\My_Python_Scripts\MLP\Test_main_distributed.py", line 35, in find_amount_gpus
    server= tf.train.Server(spec, job_name= device[0], task_index= device[1])
  File "C:\Temp\Python\Python-3.6.5\lib\site-packages\tensorflow\python\training\server_lib.py", line 148, in __init__
    self._server_def.SerializeToString(), status)
  File "C:\Temp\Python\Python-3.6.5\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 526, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.UnknownError: Could not start gRPC server
E1105 15:50:49.319000000 14416 external/grpc/src/core/ext/transport/chttp2/server/insecure/server_chttp2.cc:40] {"created":"@1541454649.319000000","description":"No address added out of total 1 resolved","file":"external/grpc/src/core/ext/transport/chttp2/server/chttp2_server.cc","file_line":307,"referenced_errors":[{"created":"@1541454649.319000000","description":"Failed to add port to server","file":"external/grpc/src/core/lib/iomgr/tcp_server_windows.cc","file_line":509,"referenced_errors":[{"created":"@1541454649.319000000","description":"OS Error","file":"external/grpc/src/core/lib/iomgr/tcp_server_windows.cc","file_line":201,"os_error":"Only one usage of each socket address (protocol/network address/port) is normally permitted.\r\n","syscall":"bind","wsa_error":10048}]}]}
Process Process-2:
Traceback (most recent call last):
  File "C:\Temp\Python\Python-3.6.5\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Temp\Python\Python-3.6.5\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\IMarroquin\Documents\My_Python_Scripts\MLP\Test_main_distributed.py", line 35, in find_amount_gpus
    server= tf.train.Server(spec, job_name= device[0], task_index= device[1])
  File "C:\Temp\Python\Python-3.6.5\lib\site-packages\tensorflow\python\training\server_lib.py", line 148, in __init__
    self._server_def.SerializeToString(), status)
  File "C:\Temp\Python\Python-3.6.5\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 526, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.UnknownError: Could not start gRPC server

**Comment by harshini-gadige** [comment]
@gunan  PTAL

**Comment by tensorflowbutler** [comment]
Nagging Assignee @gunan: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by gunan** [comment]
I do not really have experience with grpc server. @mrry any ideas?
I think this line is the actual error message (reformatting for readability):
```
E1105 15:50:49.319000000 14416 external/grpc/src/core/ext/transport/chttp2/server/insecure/server_chttp2.cc:40] 
{"created":"@1541454649.319000000",
  "description":"No address added out of total 1 resolved",
  "file":"external/grpc/src/core/ext/transport/chttp2/server/chttp2_server.cc","file_line":307,
  "referenced_errors":[{"created":"@1541454649.319000000",
  "description":"Failed to add port to server",
  "file":"external/grpc/src/core/lib/iomgr/tcp_server_windows.cc","file_line":509,
  "referenced_errors":[{"created":"@1541454649.319000000",
  "description":"OS Error","file":"external/grpc/src/core/lib/iomgr/tcp_server_windows.cc",
  "file_line":201,
   "os_error":"Only one usage of each socket address (protocol/network address/port) is normally permitted.\r\n","syscall":"bind","wsa_error":10048}]}]}
```

Maybe a socket is being reused somehow?

**Comment by ivan-marroquin** [comment]
Is it possible that the grpc server only works on Linux based systems?

**Comment by mrry** [comment]
The gRPC code works on Windows. As @gunan suggested, that error message indicates that you have something else on your system using the same port as you requested for the server.

**Comment by ivan-marroquin** [comment]
Hi @mrry 

Thanks for the clarification. I will talk to IT folks to find out what other processes are running on the same port.

Thanks to all for your help. Let's close the incident as it seems to be more related to a network issue.

Ivan
