### ISSUE TITLE
Tensorflow crashes on source building!!!

### ISSUE THREAD

**Issue by PanderBoy18** [tensorflow/tensorflow#23436]
**System information**
- Linux Ubuntu 18.04.1):
- No mobile problem
- https://github.com/tensorflow/tensorflow.git
- TensorFlow version: 1.11.0
- Python version: 2.7.15rc1
- Haven't done any pip installation
- Bazel version: Build label: 0.19.0
- GCC/Compiler version (if compiling from source): 7.3.0
- CUDA/cuDNN version:
- GPU model and memory: Not relevant

**I am trying to install Tensorflow, but I keep getting the same problem when I use this command to build it:
`bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package //tensorflow:libtensorflow_framework.so`**

**Command sequence:**
````
git clone https://github.com/tensorflow/tensorflow.git
cd tensorflow
./configure
bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package //tensorflow:libtensorflow_framework.so
````

**The output I get:**
ERROR: /root/tensorflow/tensorflow/python/BUILD:371:1: C++ compilation of rule '//tensorflow/python:ndarray_tensor' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -B/usr/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG ... (remaining 338 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
In file included from ./tensorflow/python/lib/core/ndarray_tensor.h:20:0,
                 from tensorflow/python/lib/core/ndarray_tensor.cc:16:
./tensorflow/python/lib/core/numpy.h:35:10: fatal error: Python.h: No such file or directory
 #include <Python.h>
          ^~~~~~~~~~
compilation terminated.

**Comment by harshini-gadige** [comment]
@PanderBoy18  -  Try with the below combination. 

![image](https://user-images.githubusercontent.com/42781361/47881189-af685d80-dde2-11e8-95bc-1f4305554c9f.png)

**Comment by PanderBoy18** [comment]
Everything is on the right version now, but now I get a new error. Ther error is:
ERROR: /root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/external/protobuf_archive/BUILD:260:1: C++ compilation of rule '@protobuf_archive//:js_embed' failed (Exit 1)
gcc: error trying to exec 'cc1plus': execvp: No such file or directory
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.

**Comment by PanderBoy18** [comment]
I did that all, and here is a bit of the code I use in python:
`#Model Building
model = Sequential()
model.add(CuDNNLSTM(128, input_shape=(train_x.shape[1:]), return_sequences=True))
model.add(Dropout(0.2))
model.add(BatchNormalization())

model = Sequential()
model.add(CuDNNLSTM(128, input_shape=(train_x.shape[1:]), return_sequences=True))
model.add(Dropout(0.1))
model.add(BatchNormalization())

model = Sequential()
model.add(CuDNNLSTM(128, input_shape=(train_x.shape[1:])))
model.add(Dropout(0.2))
model.add(BatchNormalization())

model.add(Dense(32, activation="relu"))
model.add(Dropout(0.2))

model.add(Dense(2, activation="softmax"))

opt = tf.keras.optimizers.Adam(lr=0.001, decay=1e-6)

model.compile(loss='sparse_categorical_crossentropy',
            optimizer=opt,
            metrics=['accuracy'])

tensorboard = TensorBoard(log_dir='logs/{NAME}')

#Unique file name that will include the epoch and the validation acc for that epoch
filepath = "RNN_Final-{epoch:02d }-{val_acc:.3f}"

#Saves only the best ones
checkpoint = ModelCheckpoint("models/{}.model".format(filepath, monitor='val_acc', verbose=1, save_best_only=True, mode='max'))

history = model.fit(
    train_x, train_y,
    batch_size=BATCH_SIZE,
    epochs=EPOCHS,
    validation_data=(validation_x, validation_y),
    callbacks=[tensorboard, checkpoint])`



But it gives the following error, when I execute it:
Train on 69188 samples, validate on 3062 samples
Traceback (most recent call last):
  File "/var/www/efy.nl/ai_crypto.py", line 161, in <module>
    callbacks=[tensorboard, checkpoint])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/engine/training.py", line 1605, in fit
    validation_steps=validation_steps)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/engine/training_arrays.py", line 127, in fit_loop
    count_mode=count_mode)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/callbacks.py", line 114, in configure_callbacks
    callback_list.set_model(callback_model)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/callbacks.py", line 189, in set_model
    callback.set_model(model)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/callbacks.py", line 944, in set_model
    self._init_writer()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/callbacks.py", line 881, in _init_writer
    self.writer = tf_summary.FileWriter(self.log_dir, K.get_session().graph)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/backend.py", line 465, in get_session
    _initialize_variables(session)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/backend.py", line 719, in _initialize_variables
    [variables_module.is_variable_initialized(v) for v in candidate_vars])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 887, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1110, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1286, in _do_run
    run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1308, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'CudnnRNN' with these attrs.  Registered devices: [CPU], Registered kernels:
  <no registered kernels>

         [[{{node cu_dnnlstm/CudnnRNN}} = CudnnRNN[T=DT_FLOAT, direction="unidirectional", dropout=0, input_mode="linear_input", is_training=true, rnn_mode="lstm", seed=0, seed2=0](cu_dnnlstm/transpose, cu_dnnlstm/ExpandDims, cu_dnnlstm/ExpandDims_1, cu_dnnlstm/concat)]]

Caused by op u'cu_dnnlstm/CudnnRNN', defined at:
  File "/var/www/efy.nl/ai_crypto.py", line 123, in <module>
    model.add(CuDNNLSTM(128, input_shape=(train_x.shape[1:]), return_sequences=True))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/checkpointable/base.py", line 426, in _method_wrapper
    method(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/engine/sequential.py", line 159, in add
    layer(x)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/layers/recurrent.py", line 619, in __call__
    return super(RNN, self).__call__(inputs, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 769, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/layers/cudnn_recurrent.py", line 109, in call
    output, states = self._process_batch(inputs, initial_state)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/layers/cudnn_recurrent.py", line 493, in _process_batch
    is_training=True)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_cudnn_rnn_ops.py", line 116, in cudnn_rnn
    is_training=is_training, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3272, in create_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1768, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): No OpKernel was registered to support Op 'CudnnRNN' with these attrs.  Registered devices: [CPU], Registered kernels:
  <no registered kernels>

         [[{{node cu_dnnlstm/CudnnRNN}} = CudnnRNN[T=DT_FLOAT, direction="unidirectional", dropout=0, input_mode="linear_input", is_training=true, rnn_mode="lstm", seed=0, seed2=0](cu_dnnlstm/transpose, cu_dnnlstm/ExpandDims, cu_dnnlstm/ExpandDims_1, cu_dnnlstm/concat)]]


What can I do????

**Comment by PanderBoy18** [comment]
I am using CPU Only btw!

**Comment by PanderBoy18** [comment]
I almost got it working, I am using this code at the end of my script:
```
filepath = "RNN_Final-{epoch:02d }-{val_acc:.3f}"

#Saves only the best ones
checkpoint = ModelCheckpoint("models/{}.model".format(filepath, monitor='val_acc', verbose=1, save_best_only=True, mode='max'))
```

And this is the error I get:
```
File "/var/www/efy.nl/ai_crypto.py", line 162, in <module>
    callbacks=[tensorboard, checkpoint])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/engine/training.py", line 1605, in fit
    validation_steps=validation_steps)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/engine/training_arrays.py", line 238, in fit_loop
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/callbacks.py", line 214, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/callbacks.py", line 568, in on_epoch_end
    filepath = self.filepath.format(epoch=epoch + 1, **logs)
ValueError: Invalid conversion specification
```

What can I do, or what am I doing wrong?

**Comment by tensorflowbutler** [comment]
Nagging Assignee @gunan: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by gunan** [comment]
The build seems to have succeeded, but this is an issue with using keras callbacks.

**Comment by harshini-gadige** [comment]
> The build seems to have succeeded, but this is an issue with using keras callbacks.

@fchollet  Any inputs on this please ?

**Comment by veselov** [comment]
Any help on how to fix the Python.h problem? I've fed "-isystem/usr/include/python2.7" to both `--cxxopts` for Bazel, or as extra flags to use when configuring Tensorflow, it's just missing in the compile command (as shown with `--verbose_failures`). I don't know enough about the tool chains here to understand where do I need to wrench it in...

**Comment by veselov** [comment]
For anybody else who gets stuck on the Python thing - yes, the python development package needs to be installed, but if it's done after configure was ran, you'd need to blow stuff away. I don't know how much stuff needed to be (blown away), I removed Bazel cache directory, and cloned Tensorflow again, that did it.

**Comment by byronyi** [comment]
Did you do ./configure again?

**Comment by veselov** [comment]
@byronyi as far as I can remember - yes.

**Comment by jvishnuvardhan** [comment]
@PanderBoy18 I know this is a stale issue. If this is still an issue, can you please share a simple standalone code to reproduce the issue? Thanks!
