### ISSUE TITLE
Current implementation does not yet support strides in the batch and depth dimensions.

### ISSUE THREAD

**Issue by xav12358** [tensorflow/tensorflow#23451]
Hello,

I try to design autoencoder in tensorflow that was previously made with tensorflow contrib tf.contrib.layer.
Here is the code : 
```
# An undercomplete autoencoder on MNIST dataset
from __future__ import division, print_function, absolute_import
import tensorflow.contrib.layers as lays

import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
from skimage import transform
from tensorflow.examples.tutorials.mnist import input_data

batch_size = 500  # Number of samples in each batch
epoch_num = 5     # Number of epochs to train the network
lr = 0.001        # Learning rate

def resize_batch(imgs):
    # A function to resize a batch of MNIST images to (32, 32)
    # Args:
    #   imgs: a numpy array of size [batch_size, 28 X 28].
    # Returns:
    #   a numpy array of size [batch_size, 32, 32].
    imgs = imgs.reshape((-1, 28, 28, 1))
    resized_imgs = np.zeros((imgs.shape[0], 32, 32, 1))
    for i in range(imgs.shape[0]):
        resized_imgs[i, ..., 0] = transform.resize(imgs[i, ..., 0], (32, 32))
    return resized_imgs


def autoencoder(inputs):
    # encoder
    # 32 x 32 x 1   ->  16 x 16 x 32
    # 16 x 16 x 32  ->  8 x 8 x 16
    # 8 x 8 x 16    ->  2 x 2 x 8
    # print('inputs {0}'.format(inputs))

    # net = lays.conv2d(inputs, 32, [5, 5], stride=2, padding='SAME')
    # print('net {0}'.format(net))

    # net = lays.conv2d(net, 16, [5, 5], stride=2, padding='SAME')
    # print('net {0}'.format(net))

    # net = lays.conv2d(net, 8, [5, 5], stride=4, padding='SAME')
    # print('net {0}'.format(net))

    # # decoder
    # # 2 x 2 x 8    ->  8 x 8 x 16
    # # 8 x 8 x 16   ->  16 x 16 x 32
    # # 16 x 16 x 32  ->  32 x 32 x 1
    # net = lays.conv2d_transpose(net, 16, [5, 5], stride=4, padding='SAME')
    # print('net {0}'.format(net))

    # net = lays.conv2d_transpose(net, 32, [5, 5], stride=2, padding='SAME')
    # print('net {0}'.format(net))

    # net = lays.conv2d_transpose(net, 1, [5, 5], stride=2, padding='SAME', activation_fn=tf.nn.tanh)

    # print('net {0}'.format(net))
    # return net

    xi = tf.nn.conv2d(ae_inputs,
                 filter=tf.Variable(tf.random_normal([5,5,1,32])),
                 strides=[1,2,2,1],
                 padding='SAME')
    xi = tf.nn.relu(xi)
    print("xi {0}".format(xi))

    xi = tf.nn.conv2d(xi,
                     filter=tf.Variable(tf.random_normal([5,5,32,16])),
                     strides=[1,2,2,32],
                     padding='SAME')
    xi = tf.nn.relu(xi)
    print("xi {0}".format(xi))

    xi = tf.nn.conv2d(xi,
                     filter=tf.Variable(tf.random_normal([5,5,16,8])),
                     strides=[1,4,4,16],
                     padding='SAME')
    xi = tf.nn.relu(xi)

    print("xi {0}".format(xi))






    xo = tf.nn.conv2d_transpose(xi,
                     filter=tf.Variable(tf.random_normal([5,5,16,8])),
                     output_shape=[tf.shape(xi)[0], 8, 8, 16],
                     strides=[1,4,4,1],
                     padding='SAME')
    xo = tf.nn.relu(xo)

    print("xo {0}".format(xo))

    xo = tf.nn.conv2d_transpose(xo,
                     filter=tf.Variable(tf.random_normal([5,5,32,16])),
                     output_shape=[tf.shape(xo)[0], 16, 16, 32],
                     strides=[1,2,2,1],
                     padding='SAME')
    xo = tf.nn.relu(xo)

    print("xo {0}".format(xo))

    xo = tf.nn.conv2d_transpose(xo,
                     filter=tf.Variable(tf.random_normal([5,5,1,32])),
                     output_shape=[tf.shape(xo)[0], 32, 32, 1],
                     strides=[1,2,2,1],
                     padding='SAME')
    xo = tf.nn.tanh(xo)


    print("xo {0}".format(xo))
    return xo
# read MNIST dataset
mnist = input_data.read_data_sets("MNIST_data", one_hot=True)

# calculate the number of batches per epoch
batch_per_ep = mnist.train.num_examples // batch_size

ae_inputs = tf.placeholder(tf.float32, (None, 32, 32, 1))  # input to the network (MNIST images)
ae_outputs = autoencoder(ae_inputs)  # create the Autoencoder network

# calculate the loss and optimize the network
loss = tf.reduce_mean(tf.square(ae_outputs - ae_inputs))  # claculate the mean square error loss
with tf.name_scope('train'):
    train_op = tf.train.AdamOptimizer(learning_rate=lr).minimize(loss)



# initialize the network
init = tf.global_variables_initializer()
saver = tf.train.Saver()
stddev = tf.sqrt(tf.reduce_mean(tf.square(ae_inputs - ae_outputs)))

with tf.name_scope('stddev'):
        tf.summary.scalar('accuracy', stddev)
with tf.Session() as sess:
    sess.run(init)
    train_writer = tf.summary.FileWriter('/tmp/autoencoder/', sess.graph)
    index = 0
    for ep in range(epoch_num):  # epochs loop
        for batch_n in range(batch_per_ep):  # batches loop
            batch_img, batch_label = mnist.train.next_batch(batch_size)  # read a batch
            batch_img = batch_img.reshape((-1, 28, 28, 1))               # reshape each sample to an (28, 28) image
            batch_img = resize_batch(batch_img)                          # reshape the images to (32, 32)
            run_options = tf.RunOptions(trace_level=tf.RunOptions.FULL_TRACE)
            run_metadata = tf.RunMetadata()
            accuracy, c = sess.run([train_op, loss], feed_dict={ae_inputs: batch_img},
                              options=run_options,
                              run_metadata=run_metadata)
            print('Epoch: {} - cost= {:.5f}'.format((ep + 1), c))
            if batch_n % 10 == 0:

              summ=tf.Summary()
              summ.value.add(tag='Cost', simple_value = c)
              summ.value.add(tag='Accuracy', simple_value = accuracy)
              #train_writer.add_run_metadata(run_metadata, 'step%03d' % batch_n)
              train_writer.add_summary(summ,index)
              index+=1
              train_writer.flush()
              save_path = saver.save(sess, "/tmp/autoencoder/model.ckpt")

              #file_writer = tf.summary.FileWriter(logdir='/tmp/autoencoder/')
              print("Model saved in path: %s" % save_path)

    train_writer.close()

    # test the trained network
    batch_img, batch_label = mnist.test.next_batch(50)
    batch_img = resize_batch(batch_img)
    recon_img = sess.run([ae_outputs], feed_dict={ae_inputs: batch_img})[0]

    # plot the reconstructed images and their ground truths (inputs)
    plt.figure(1)
    plt.title('Reconstructed Images')
    for i in range(50):
        plt.subplot(5, 10, i+1)
        plt.imshow(recon_img[i, ..., 0], cmap='gray')
    plt.figure(2)
    plt.title('Input Images')
    for i in range(50):
        plt.subplot(5, 10, i+1)
        plt.imshow(batch_img[i, ..., 0], cmap='gray')
    plt.show()


```

Where I run the code I get that error:

```
`WARNING:tensorflow:From ./simple_autoencoder.py:115: read_data_sets (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
WARNING:tensorflow:From /usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:260: maybe_download (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Please write your own downloading logic.
WARNING:tensorflow:From /usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:262: extract_images (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting MNIST_data/train-images-idx3-ubyte.gz
WARNING:tensorflow:From /usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:267: extract_labels (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting MNIST_data/train-labels-idx1-ubyte.gz
WARNING:tensorflow:From /usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:110: dense_to_one_hot (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
Instructions for updating:
Please use tf.one_hot on tensors.
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
WARNING:tensorflow:From /usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:290: DataSet.__init__ (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
xi Tensor("Relu:0", shape=(?, 16, 16, 32), dtype=float32)
xi Tensor("Relu_1:0", shape=(?, 8, 8, 16), dtype=float32)
xi Tensor("Relu_2:0", shape=(?, 2, 2, 8), dtype=float32)
xo Tensor("Relu_3:0", shape=(?, 8, 8, 16), dtype=float32)
xo Tensor("Relu_4:0", shape=(?, 16, 16, 32), dtype=float32)
xo Tensor("Tanh:0", shape=(?, 32, 32, 1), dtype=float32)
2018-11-02 09:21:05.882917: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
/usr/local/lib/python3.5/dist-packages/skimage/transform/_warps.py:84: UserWarning: The default mode, 'constant', will be changed to 'reflect' in skimage 0.15.
  warn("The default mode, 'constant', will be changed to 'reflect' in "
2018-11-02 09:21:06.345232: E tensorflow/core/common_runtime/executor.cc:630] Executor failed to create kernel. Invalid argument: Current implementation does not yet support strides in the batch and depth dimensions.
	 [[{{node Conv2D_1}} = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 2, 2, 32], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](Relu, Variable_1/read)]]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1292, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1277, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1367, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Current implementation does not yet support strides in the batch and depth dimensions.
	 [[{{node Conv2D_1}} = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 2, 2, 32], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](Relu, Variable_1/read)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./simple_autoencoder.py", line 150, in <module>
    run_metadata=run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 887, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1110, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1286, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1308, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Current implementation does not yet support strides in the batch and depth dimensions.
	 [[{{node Conv2D_1}} = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 2, 2, 32], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](Relu, Variable_1/read)]]

Caused by op 'Conv2D_1', defined at:
  File "./simple_autoencoder.py", line 121, in <module>
    ae_outputs = autoencoder(ae_inputs)  # create the Autoencoder network
  File "./simple_autoencoder.py", line 69, in autoencoder
    padding='SAME')
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_nn_ops.py", line 957, in conv2d
    data_format=data_format, dilations=dilations, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3272, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1768, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Current implementation does not yet support strides in the batch and depth dimensions.
	 [[{{node Conv2D_1}} = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 2, 2, 32], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](Relu, Variable_1/read)]]
`

```
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): 1.10
- Python version: 3.5
- Bazel version (if compiling from source): None
- GCC/Compiler version (if compiling from source): gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609

**Comment by harshini-gadige** [comment]
@yupbank   PTAL

**Comment by yupbank** [comment]
sure..

**Comment by yupbank** [comment]
Hey, so the equivalent operation of 
```
net = tf.placeholder(tf.float32, [10, 255, 255, 3])
net = lays.conv2d(net, 16, [5, 5], stride=2, padding='SAME')
```
in `tf.nn` is
```
filters = tf.get_variable('Conv/weights', [5, 5, 3, 16], tf.float32) 
biases =  tf.get_variable('Conv/bias', [16], tf.float32)
net = tf.nn.conv2d(net, filters, [1, 2, 2, 1], padding='SAME') + biases
``` 
since the first and last dimension of the net is batch_size and channel, when we do convolution, we don't put stride on them.

**Comment by harshini-gadige** [comment]
@xav12358  - Any update on this ?

**Comment by harshini-gadige** [comment]
In "awaiting response" status for more than 3 days. Hence closing this. Please post the updates here if any, we will reopen the issue. Thanks !
