### ISSUE TITLE
Eager: dtype not checked

### ISSUE THREAD

**Issue by meta-inf** [tensorflow/tensorflow#23452]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution: Ubuntu 16.04.4 LTS
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): `v1.11.0-0-gc19e29306c 1.11.0`
- Python version: 3.6.5 Anaconda
- CUDA/cuDNN version: Cuda 9.0
- GPU model and memory: does not apply - I used CPU

**Describe the current behavior**

The following code
```
import tensorflow as tf
tf.enable_eager_execution()
print(1.2*tf.constant(2))
```
does not crash and outputs `Tensor(2, dtype=int32)`. 

**Describe the expected behavior**

Either there should be an error indicating dtype not matched, or there should be an implicit cast.

**Code to reproduce the issue**

See above.

**Comment by yongtang** [comment]
@meta-inf With the latest tf-nightly the error is thrown correctly. I think this issue is resolved?


```
root@ubuntu:/v# python
Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> print(tf.VERSION)
1.13.0-dev20181103
>>> tf.enable_eager_execution()
>>> print(1.2*tf.constant(2))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/math_ops.py", line 893, in r_binary_op_wrapper
    x = ops.convert_to_tensor(x, dtype=y.dtype.base_dtype, name="x")
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1059, in convert_to_tensor
    as_ref=False)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1155, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/constant_op.py", line 229, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/constant_op.py", line 179, in constant
    t = convert_to_eager_tensor(value, ctx, dtype)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/constant_op.py", line 110, in convert_to_eager_tensor
    t = ops.EagerTensor(value, context=handle, device=device, dtype=dtype)
TypeError: Cannot convert value 1.2 to EagerTensor with requested dtype: 3
>>> 
```

**Comment by yongtang** [comment]
The only issue seems to be that the TypeError has `dtype: 3` which is not very descriptive. I have added a PR #23479 to fix it so that the output would be:
```
TypeError: Cannot convert value 1.2 to EagerTensor with requested dtype: int32
```
