### ISSUE TITLE
Error in tensorflow __init__: TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

### ISSUE THREAD

**Issue by mfeblowitz** [tensorflow/tensorflow#23470]
- TensorFlow version: v1.11.0-0-gc19e29306c 1.11.0
- Python version: 
    3.6.4, via Anaconda (Anaconda3-5.3.0-Linux-x86_64), and also 3.6.7, and 3.7 via Anaconda
    also 3.6.4 as a direct install
- Centos7, in a Docker container, with all dependencies pip installed

During \_\_init\_\_ on import of tensorflow,  seeing ```TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'`` - exception trace below

```
try:
    print("Importing tensorflow", flush=True)
    import tensorflow as tf
    print("Imported tensorflow", tf, flush=True)
   
except:
    pass
```
The circumstances are unusual and difficult to reproduce. The code runs fine except in situ installed to support a Streams python map operator. What's needed here is some guidance as to what could cause this specific failure at this specific location in the `__init__` method on import (specifically, at  `import tensorflow.python.ops import array_ops`), and what measures should be taken to address it.

**Other info / logs**
```
Importing tensorflow
02 Nov 2018 22:01:40.634-0400 [62] ERROR #splapplog,J[0],P[0],CandidateEvents.MinimalExtractedObjectsSRLNN,python M[splpy_general.h:importModule:352]  - CDIST0305E: Fatal error: missing module: CandidateEventsExtractor.
Traceback (most recent call last):
  File "/tmp/StorylineAggregator1.distributed/toolkits/com.ibm.btn.util.candidate_events_extractor/opt/python/streams/CandidateEventsExtractor.py", line 5, in <module>
    from SRLNN_Pipeline import SRLNN_Pipeline
  File "/tmp/StorylineAggregator1.distributed/toolkits/com.ibm.btn.util.candidate_events_extractor/opt/python/modules/SRLNN_Pipeline.py", line 9, in <module>
    from sentence_embeddings import read_corpus, do_faiss
  File "/tmp/StorylineAggregator1.distributed/toolkits/com.ibm.btn.util.candidate_events_extractor/opt/python/modules/sentence_embeddings.py", line 19, in <module>
    import tensorflow_hub as hub
  File "/opt/conda/envs/srl-nn/lib/python3.6/site-packages/tensorflow_hub/__init__.py", line 21, in <module>
    import tensorflow as tf
  File "/opt/conda/envs/srl-nn/lib/python3.6/site-packages/tensorflow/__init__.py", line 22, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/opt/conda/envs/srl-nn/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 63, in <module>
    from tensorflow.python.framework.framework_lib import *  # pylint: disable=redefined-builtin
  File "/opt/conda/envs/srl-nn/lib/python3.6/site-packages/tensorflow/python/framework/framework_lib.py", line 52, in <module>
    from tensorflow.python.framework.importer import import_graph_def
  File "/opt/conda/envs/srl-nn/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 27, in <module>
    from tensorflow.python.framework import function
  File "/opt/conda/envs/srl-nn/lib/python3.6/site-packages/tensorflow/python/framework/function.py", line 35, in <module>
    from tensorflow.python.ops import array_ops
  File "/opt/conda/envs/srl-nn/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 153, in <module>
    listdiff.__doc__ = gen_array_ops.list_diff.__doc__ + "\n" + listdiff.__doc__
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
02 Nov 2018 22:01:40.639-0400 [62] ERROR #splapplog,J[0],P[0],CandidateEvents.MinimalExtractedObjectsSRLNN,spl_pe M[PEImpl.cpp:logTerminatingException:2183]  - CDISR5033E: An exception occurred during the execution of the CandidateEvents.MinimalExtractedObjectsSRLNN operator. Processing element number 0 is terminating.
02 Nov 2018 22:01:40.639-0400 [62] ERROR #splapptrc,J[0],P[0],CandidateEvents.MinimalExtractedObjectsSRLNN,spl_operator M[PEImpl.cpp:handleOperatorFailure:661]  - CDISR5030E: An exception occurred during the execution of the CandidateEvents.MinimalExtractedObjectsSRLNN operator. The exception is: Unknown Python error

**Comment by mfeblowitz** [comment]
This turned out to be, as expected, an environment issue, resolved by proper setting of PYTHONPATH, among other steps.
