### ISSUE TITLE
tf.contrib.estimator.InMemoryEvaluatorHook does not work with MirroredStrategy

### ISSUE THREAD

**Issue by KDMueller** [tensorflow/tensorflow#23525]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux 3.10.0-862.9.1.el7.x86_64, CentOS 7.5
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): ('v1.9.0-rc2-2836-g05f8ea8', '1.10.0')
- Python version: 2.7
- Bazel version (if compiling from source): 0.16.1
- GCC/Compiler version (if compiling from source): c++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-28)
- CUDA/cuDNN version: 9.2.148
- GPU model and memory: 8x GTX 1080 Ti, 11178MiB

**Describe the current behavior**
When using tf.contrib.estimator.InMemoryEvaluatorHook together with tf.contrib.distribute.MirroredStrategy on more than 1 GPU I get an error as soon as evaluation starts:
RuntimeError: Graph is finalized and cannot be modified.

This does not occur when using OneDeviceStrategy. The documentation of InMemoryEvaluatorHook states: "It doesn't support multi-node distributed mode." However, I am on a single node and multi-GPU

**Describe the expected behavior**
The error should not occur. If multi-GPU support is not supported yet, will it be in the future? The documentation should also be updated then.

**Code to reproduce the issue**
distribution = tf.contrib.distribute.MirroredStrategy(num_gpus=2)
run_config = tf.estimator.RunConfig(train_distribute=distribution)
estimator = tf.estimator.Estimator(model.model_fn, config=run_config)
evaluator = tf.contrib.estimator.InMemoryEvaluatorHook(estimator, eval_input_fn, steps=20, every_n_iter=20)
estimator.train(train_input_fn, steps=100, hooks=[evaluator])

**Other info / logs**
Traceback (most recent call last):
  File "/home/xxx/.vscode/extensions/ms-python.python-2018.9.2/pythonFiles/experimental/ptvsd_launcher.py", line 115, in <module>
    vspd.run(filename, port_num, run_as, *sys.argv[1:])
  File "/home/xxx/.vscode/extensions/ms-python.python-2018.9.2/pythonFiles/experimental/ptvsd/ptvsd/debugger.py", line 43, in run
    run_main(address, filename, run_as, *args, **kwargs)
  File "/home/xxx/.vscode/extensions/ms-python.python-2018.9.2/pythonFiles/experimental/ptvsd/ptvsd/_local.py", line 52, in run_main
    runner(addr, name, kind == 'module', *extra, **kwargs)
  File "/home/xxx/.vscode/extensions/ms-python.python-2018.9.2/pythonFiles/experimental/ptvsd/ptvsd/runner.py", line 32, in run
    set_trace=False)
  File "/home/xxx/.vscode/extensions/ms-python.python-2018.9.2/pythonFiles/experimental/ptvsd/ptvsd/_vendored/pydevd/pydevd.py", line 1107, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "/home/xxx/.vscode/extensions/ms-python.python-2018.9.2/pythonFiles/experimental/ptvsd/ptvsd/_vendored/pydevd/pydevd.py", line 1114, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/xxx/test/mv_estimator/train.py", line 91, in <module>
    tf.app.run()
  File "/home/xxx/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/home/xxx/test/mv_estimator/train.py", line 80, in main
    estimator.train(train_input_fn, steps=100, hooks=[evaluator])
  File "/home/xxx/.local/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 354, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/xxx/.local/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 1177, in _train_model
    return self._train_model_distributed(input_fn, hooks, saving_listeners)
  File "/home/xxx/.local/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 1320, in _train_model_distributed
    saving_listeners)
  File "/home/xxx/.local/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 1400, in _train_with_estimator_spec
    log_step_count_steps=self._config.log_step_count_steps) as mon_sess:
  File "/home/xxx/.local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 504, in MonitoredTrainingSession
    stop_grace_period_secs=stop_grace_period_secs)
  File "/home/xxx/.local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 920, in __init__
    stop_grace_period_secs=stop_grace_period_secs)
  File "/home/xxx/.local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 643, in __init__
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "/home/xxx/.local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1106, in __init__
    _WrappedSession.__init__(self, self._create_session())
  File "/home/xxx/.local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1111, in _create_session
    return self._sess_creator.create_session()
  File "/home/xxx/.local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 806, in create_session
    hook.after_create_session(self.tf_sess, self.coord)
  File "/home/xxx/.local/lib/python2.7/site-packages/tensorflow/contrib/estimator/python/estimator/hooks.py", line 178, in after_create_session
    self._evaluate(session)
  File "/home/xxx/.local/lib/python2.7/site-packages/tensorflow/contrib/estimator/python/estimator/hooks.py", line 181, in _evaluate
    var_name_to_value = train_session.run(self._var_name_to_train_var)
  File "/home/xxx/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 887, in run
    run_metadata_ptr)
  File "/home/xxx/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1095, in _run
    self._graph, fetches, feed_dict_tensor, feed_handles=feed_handles)
  File "/home/xxx/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 429, in __init__
    self._fetch_mapper = _FetchMapper.for_fetch(fetches)
  File "/home/xxx/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 249, in for_fetch
    return _DictFetchMapper(fetch)
  File "/home/xxx/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 387, in __init__
    _FetchMapper.for_fetch(fetch) for fetch in fetches.values()
  File "/home/xxx/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 255, in for_fetch
    return _ElementFetchMapper(fetches, contraction_fn)
  File "/home/xxx/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 284, in __init__
    fetch, allow_tensor=True, allow_operation=True))
  File "/home/xxx/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3473, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/home/xxx/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3496, in _as_graph_element_locked
    temp_obj = _as_graph_element(obj)
  File "/home/xxx/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 148, in _as_graph_element
    return conv_fn()
  File "/home/xxx/.local/lib/python2.7/site-packages/tensorflow/contrib/distribute/python/values.py", line 513, in _as_graph_element
    return self._get_cross_tower()
  File "/home/xxx/.local/lib/python2.7/site-packages/tensorflow/contrib/distribute/python/values.py", line 505, in _get_cross_tower
    total = math_ops.add_n(all_components)
  File "/home/xxx/.local/lib/python2.7/site-packages/tensorflow/python/ops/math_ops.py", line 2145, in add_n
    inputs = ops.convert_n_to_tensor_or_indexed_slices(inputs)
  File "/home/xxx/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1355, in convert_n_to_tensor_or_indexed_slices
    values=values, dtype=dtype, name=name, as_ref=False)
  File "/home/xxx/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1326, in internal_convert_n_to_tensor_or_indexed_slices
    value, dtype=dtype, name=n, as_ref=as_ref))
  File "/home/xxx/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1285, in internal_convert_to_tensor_or_indexed_slices
    value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/xxx/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1124, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/xxx/.local/lib/python2.7/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 1258, in _dense_var_to_tensor
    return var._dense_var_to_tensor(dtype=dtype, name=name, as_ref=as_ref)  # pylint: disable=protected-access
  File "/home/xxx/.local/lib/python2.7/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 1213, in _dense_var_to_tensor
    return self.value()
  File "/home/xxx/.local/lib/python2.7/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 647, in value
    return self._read_variable_op()
  File "/home/xxx/.local/lib/python2.7/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 730, in _read_variable_op
    self._dtype)
  File "/home/xxx/.local/lib/python2.7/site-packages/tensorflow/python/ops/gen_resource_variable_ops.py", line 508, in read_variable_op
    "ReadVariableOp", resource=resource, dtype=dtype, name=name)
  File "/home/xxx/.local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/xxx/.local/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/home/xxx/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3232, in create_op
    self._check_not_finalized()
  File "/home/xxx/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2905, in _check_not_finalized
    raise RuntimeError("Graph is finalized and cannot be modified.")

**Comment by mrry** [comment]
@josh11b, since this bug is either in distribution strategies or estimators, can you please triage this?

**Comment by tensorflowbutler** [comment]
Nagging Assignee @josh11b: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by mohantym** [comment]
Hi @KDMueller! 
It seems you are using older versions(1.x versions) of Tensorflow which is not supported any more. Please visit these links to upgrade your codebase to latest versions.Ref [1](https://www.tensorflow.org/addons),[2](https://www.tensorflow.org/guide/migrate). Thanks!
