### ISSUE TITLE
Tensor flow is breaking with Failed to load the native TensorFlow runtime

### ISSUE THREAD

**Issue by AvinashTiwari** [tensorflow/tensorflow#23526]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Windows 8.1
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
No Mobile device used
- TensorFlow installed from (source or binary):
   Binary used Pip command
- TensorFlow version:
Name: tensorflow
Version: 1.11.0
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: opensource@google.com
License: Apache 2.0
Location: c:\users\avinash.t\anaconda3\lib\site-packages
Requires: tensorboard, numpy, six, keras-applications, setuptools, grpcio, gast,
 protobuf, termcolor, wheel, astor, absl-py, keras-preprocessing

- Python version:
C:\Users\avinash.t>python --version
Python 3.6.7 :: Anaconda, Inc.
- Installed using virtualenv? pip? conda?:
pip
- Bazel version (if compiling from source):
 Not complied from Source
- GCC/Compiler version (if compiling from source):
No use of GCC
- CUDA/cuDNN version:
No use of CUDA
- GPU model and memory:
No use o GPU

**Describe the problem**
Simple import is not working

**Provide the exact sequence of commands / steps that you executed before running into the problem**
C:\Users\avinash.t>python
Python 3.6.7 |Anaconda, Inc.| (default, Oct 28 2018, 19:44:12) [MSC v.1915 64 bi
t (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "C:\Users\avinash.t\Anaconda3\lib\site-packages\tensorflow\python\pywrap_
tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\avinash.t\Anaconda3\lib\site-packages\tensorflow\python\pywrap_
tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\avinash.t\Anaconda3\lib\site-packages\tensorflow\python\pywrap_
tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, descript
ion)
  File "C:\Users\avinash.t\Anaconda3\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\avinash.t\Anaconda3\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routin
e failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\avinash.t\Anaconda3\lib\site-packages\tensorflow\__init__.py",
line 22, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-im
port
  File "C:\Users\avinash.t\Anaconda3\lib\site-packages\tensorflow\python\__init_
_.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\avinash.t\Anaconda3\lib\site-packages\tensorflow\python\pywrap_
tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\avinash.t\Anaconda3\lib\site-packages\tensorflow\python\pywrap_
tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\avinash.t\Anaconda3\lib\site-packages\tensorflow\python\pywrap_
tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\avinash.t\Anaconda3\lib\site-packages\tensorflow\python\pywrap_
tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, descript
ion)
  File "C:\Users\avinash.t\Anaconda3\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\avinash.t\Anaconda3\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routin
e failed.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_probl
ems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
>>>

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
C:\Users\avinash.t>python
Python 3.6.7 |Anaconda, Inc.| (default, Oct 28 2018, 19:44:12) [MSC v.1915 64 bi
t (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "C:\Users\avinash.t\Anaconda3\lib\site-packages\tensorflow\python\pywrap_
tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\avinash.t\Anaconda3\lib\site-packages\tensorflow\python\pywrap_
tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\avinash.t\Anaconda3\lib\site-packages\tensorflow\python\pywrap_
tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, descript
ion)
  File "C:\Users\avinash.t\Anaconda3\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\avinash.t\Anaconda3\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routin
e failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\avinash.t\Anaconda3\lib\site-packages\tensorflow\__init__.py",
line 22, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-im
port
  File "C:\Users\avinash.t\Anaconda3\lib\site-packages\tensorflow\python\__init_
_.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\avinash.t\Anaconda3\lib\site-packages\tensorflow\python\pywrap_
tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\avinash.t\Anaconda3\lib\site-packages\tensorflow\python\pywrap_
tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\avinash.t\Anaconda3\lib\site-packages\tensorflow\python\pywrap_
tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\avinash.t\Anaconda3\lib\site-packages\tensorflow\python\pywrap_
tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, descript
ion)
  File "C:\Users\avinash.t\Anaconda3\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\avinash.t\Anaconda3\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routin
e failed.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_probl
ems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
>>>

**Comment by harshini-gadige** [comment]
@skye  PTAL

**Comment by skye** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since I suspect this is an environment issue. Thanks.
