### ISSUE TITLE
Convert to .tflite from saved checkpoint

### ISSUE THREAD

**Issue by letianxu** [tensorflow/tensorflow#23528]
**System information**
- TensorFlow version: 1.10.0
- Are you willing to contribute it  Yes:

**Describe the feature and the current behavior/state.**
tflite_convert --output_file=test.tflite --saved_model_dir=test_checkpoint_saved_data

output:
Traceback (most recent call last):
  File "/usr/local/bin/tflite_convert", line 11, in <module>
    sys.exit(main())
  File "/Library/Python/2.7/site-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 370, in main
    app.run(main=run_main, argv=sys.argv[:1])
  File "/Library/Python/2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/Library/Python/2.7/site-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 366, in run_main
    _convert_model(tflite_flags)
  File "/Library/Python/2.7/site-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 94, in _convert_model
    converter = _get_toco_converter(flags)
  File "/Library/Python/2.7/site-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 81, in _get_toco_converter
    return converter_fn(**converter_kwargs)
  File "/Library/Python/2.7/site-packages/tensorflow/contrib/lite/python/lite.py", line 268, in from_saved_model
    output_arrays, tag_set, signature_key)
  File "/Library/Python/2.7/site-packages/tensorflow/contrib/lite/python/convert_saved_model.py", line 239, in freeze_saved_model
    meta_graph = _get_meta_graph_def(saved_model_dir, tag_set)
  File "/Library/Python/2.7/site-packages/tensorflow/contrib/lite/python/convert_saved_model.py", line 61, in _get_meta_graph_def
    return loader.load(sess, tag_set, saved_model_dir)
  File "/Library/Python/2.7/site-packages/tensorflow/python/saved_model/loader_impl.py", line 211, in load
    loader = SavedModelLoader(export_dir)
  File "/Library/Python/2.7/site-packages/tensorflow/python/saved_model/loader_impl.py", line 230, in __init__
    self._saved_model = _parse_saved_model(export_dir)
  File "/Library/Python/2.7/site-packages/tensorflow/python/saved_model/loader_impl.py", line 80, in _parse_saved_model
    constants.SAVED_MODEL_FILENAME_PB))
IOError: SavedModel file does not exist at: test_checkpoint_saved_data/{saved_model.pbtxt|saved_model.pb}

**Will this change the current api? How?**

**Who will benefit with this feature?**

**Any Other info.**

**Comment by ymodak** [comment]
Please provide following information:
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Comment by letianxu** [comment]
Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No, just want to convert trained ckpt
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MAC OS 10.13.6
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Pixel XL
TensorFlow installed from (source or binary): binary
TensorFlow version (use command below): 1.11.0
Python version: 2.7
Bazel version (if compiling from source): not using Bazel
GCC/Compiler version (if compiling from source): not using GCC
CUDA/cuDNN version: don't know
GPU model and memory: NVIDIA GeForce GT 750M 2048 MB
                                            Intel Iris Pro 1536 MB

**Comment by ymodak** [comment]
I think the converter only supports SavedModel format, not the checkpoint + metadata format.

**Comment by ymodak** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by ymodak** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)

**Comment by lmy931** [comment]
Can we convert checkpoint to .tflite?
