### ISSUE TITLE
Python - Import Error of Tensorflow GPU in Ubuntu 

### ISSUE THREAD

**Issue by hfzarslan** [tensorflow/tensorflow#23524]
I am using python 3 with ubuntu 18.04 and have installed the following packages:
cuda 9.0
cudnn-9.0-linux-x64-v7.3.1.20 
tensorflow gpu 1.5

But I am still getting an error while importing tensorflow. 
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rafey/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/__init__.py", line 22, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/rafey/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 81, in <module>
    from tensorflow.python import keras
  File "/home/rafey/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/keras/__init__.py", line 24, in <module>
    from tensorflow.python.keras import activations
  File "/home/rafey/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/keras/activations/__init__.py", line 22, in <module>
    from tensorflow.python.keras._impl.keras.activations import elu
  File "/home/rafey/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/__init__.py", line 21, in <module>
    from tensorflow.python.keras._impl.keras import activations
  File "/home/rafey/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/activations.py", line 23, in <module>
    from tensorflow.python.keras._impl.keras import backend as K
  File "/home/rafey/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/backend.py", line 36, in <module>
    from tensorflow.python.layers import base as tf_base_layers
  File "/home/rafey/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 25, in <module>
    from tensorflow.python.keras.engine import base_layer
  File "/home/rafey/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/keras/engine/__init__.py", line 23, in <module>
    from tensorflow.python.keras.engine.base_layer import InputSpec
  File "/home/rafey/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 33, in <module>
    from tensorflow.python.keras import backend
  File "/home/rafey/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/keras/backend/__init__.py", line 22, in <module>
    from tensorflow.python.keras._impl.keras.backend import abs
ImportError: cannot import name 'abs'`

**Comment by ymodak** [comment]
Can you please try using the latest version of TensorFlow and build again.?
You can try TF 1.11.

**Comment by hfzarslan** [comment]
ok got it thanks

**Comment by ymodak** [comment]
Were you able to solve your issue?

**Comment by ymodak** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
