### ISSUE TITLE
Failed to load the native TensorFlow runtime error

### ISSUE THREAD

**Issue by eachabys** [tensorflow/tensorflow#23533]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Windows 10 Home
- TensorFlow installed from (source or binary): from cmd using command "pip install tensorflow"
- TensorFlow version:  tensorflow-1.11.0
- Python version: 3.6.7amd 64
- Installed using virtualenv? pip? conda?: pip install tensorflow
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Problem**
 I thought that was a problem due to my python version Python 3.7.1, so I deleted it and installed a new python 3.6.7.
Then I used cmd to get to script and run "pip install tensorflow"
Then I created a simple py file "import tensorflow as tf" 

I got so many mistakes, such as 
"ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.
Failed to load the native TensorFlow runtime.."

so I removed "pip uninstall tensorflow". Then, I tried "pip install --upgrade tensorflow" still same errors.
Then "pip3 install --upgrade tensorflow" Still cant use tensorflow
Please help me

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
Traceback (most recent call last):
  File "C:\Users\elmia\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\elmia\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\elmia\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\elmia\AppData\Local\Programs\Python\Python36\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\elmia\AppData\Local\Programs\Python\Python36\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\elmia\Desktop\python_test\deep_learning_tensorflow_sucks\1.py", line 1, in <module>
    import tensorflow as tf
  File "C:\Users\elmia\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\__init__.py", line 22, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\elmia\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\elmia\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\elmia\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\elmia\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\elmia\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\elmia\AppData\Local\Programs\Python\Python36\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\elmia\AppData\Local\Programs\Python\Python36\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by Kalevera** [comment]
Looks the same as this one. 

Tensor flow is breaking with Failed to load the native TensorFlow runtime #23526

The other user had to revert back to 1.5

My guess is the DLLs aren't found properly and that's why it's not showing the correct missing dll on dynamic_load()

Just curious but did you see any eager execution errors when trouble shooting?

**Comment by eachabys** [comment]
> Looks the same as this one.
> 
> Tensor flow is breaking with Failed to load the native TensorFlow runtime #23526
> 
> The other user had to revert back to 1.5
> 
> My guess is the DLLs aren't found properly and that's why it's not showing the correct missing dll on dynamic_load()
> 
> Just curious but did you see any eager execution errors when trouble shooting?

:(( Thanks, 
Thats too bad. I spent so much time downloading new version, then thinking may be my old version kind of brings problem to the new one.So I removed completely my old Python and had to reinstall all the libraries like pandas, numpy, etc.
Did you say the other user had to switch back to 3.5?
Like I mentioned I get "ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed."

**Comment by harshini-gadige** [comment]
Check if #19584 helps

**Comment by harshini-gadige** [comment]
> Check if #19584 helps

@eachabys  Any update ?

**Comment by harshini-gadige** [comment]
In "awaiting response" status for more than 3 days. Hence closing this. Please post the updates here if any, we will reopen the issue. Thanks !
