### ISSUE TITLE
Memmory leak Using tensorflow::NewSession , C++

### ISSUE THREAD

**Issue by Cameron-Chancey** [tensorflow/tensorflow#23557]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes.
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Linux Ubuntu 16.04
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:N/A
- **TensorFlow installed from (source or binary)**:Source
- **TensorFlow version (use command below)**: 1.12.0-rc0
- **Python version**: Python 2.7.12
- **Bazel version (if compiling from source)**: 0.18.0
- **GCC/Compiler version (if compiling from source)**: 5.4.0
- **CUDA/cuDNN version**: N/A. Using Cpu Only. 
- **GPU model and memory**: N/A. Using Cpu Only. 
- **Exact command to reproduce**:

## Code
```
class Temp
{
 public:
  Temp(){
    std::unique_ptr<tensorflow::Session> session(
      tensorflow::NewSession(tensorflow::SessionOptions()));
    };
};

int main(int argc, char **argv)
{
  Temp temp;
  return 0;
}
```

### Describe the problem
When creating a unique_ptr to a session using tensorflow::NewSession, a memory leak occurs according to address sanitizer. There is a similar closed issue posted here: [https://github.com/tensorflow/tensorflow/issues/19163](https://github.com/tensorflow/tensorflow/issues/19163) , however I am still having an issue. 

### Source code / logs

```
==259==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0x7f17c81b7532 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x99532)
    #1 0x7f17c1c1aca7 in tensorflow::RegisterXlaDeviceKernels(char const*, char const*) (/tensorflowincludes/bin/libtensorflow_cc.so+0x1cd2ca7)
    #2 0x7f17c1c0e19a in tensorflow::XlaCpuDeviceFactory::CreateDevices(tensorflow::SessionOptions const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<tensorflow::Device*, std::allocator<tensorflow::Device*> >*) (/tensorflowincludes/bin/libtensorflow_cc.so+0x1cc619a)
    #3 0x7f17bf851fe8 in tensorflow::DeviceFactory::AddDevices(tensorflow::SessionOptions const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<tensorflow::Device*, std::allocator<tensorflow::Device*> >*) (/tensorflowincludes/bin/libtensorflow_framework.so+0x62dfe8)
    #4 0x7f17c61ccea4 in tensorflow::DirectSessionFactory::NewSession(tensorflow::SessionOptions const&, tensorflow::Session**) (/tensorflowincludes/bin/libtensorflow_cc.so+0x6284ea4)
    #5 0x7f17bf8abfe8 in tensorflow::NewSession(tensorflow::SessionOptions const&, tensorflow::Session**) (/tensorflowincludes/bin/libtensorflow_framework.so+0x687fe8)
    #6 0x7f17bf8ac0ac in tensorflow::NewSession(tensorflow::SessionOptions const&) (/tensorflowincludes/bin/libtensorflow_framework.so+0x6880ac)
    #7 0x402bc2 in Temp::Temp() /var/jenkins_home/workspace/tensorflowleaktest_master-FVC6RQR2GX36IO3JBYVHBT3IJH3EQUQFR2B3OPUAPWVP7LOWN2WQ/tests/src/main.cpp:38
    #8 0x402245 in main /var/jenkins_home/workspace/tensorflowleaktest_master-FVC6RQR2GX36IO3JBYVHBT3IJH3EQUQFR2B3OPUAPWVP7LOWN2WQ/tests/src/main.cpp:44
    #9 0x7f17be6c582f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

Indirect leak of 4096 byte(s) in 1 object(s) allocated from:
    #0 0x7f17c81b7532 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x99532)
    #1 0x7f17c1c1ab50 in void std::vector<std::unique_ptr<tensorflow::kernel_factory::OpKernelRegistrar, std::default_delete<tensorflow::kernel_factory::OpKernelRegistrar> >, std::allocator<std::unique_ptr<tensorflow::kernel_factory::OpKernelRegistrar, std::default_delete<tensorflow::kernel_factory::OpKernelRegistrar> > > >::_M_emplace_back_aux<tensorflow::kernel_factory::OpKernelRegistrar*>(tensorflow::kernel_factory::OpKernelRegistrar*&&) (/tensorflowincludes/bin/libtensorflow_cc.so+0x1cd2b50)
    #2 0x7f17c1c1ae7e in tensorflow::RegisterXlaDeviceKernels(char const*, char const*) (/tensorflowincludes/bin/libtensorflow_cc.so+0x1cd2e7e)
    #3 0x7f17c1c0e19a in tensorflow::XlaCpuDeviceFactory::CreateDevices(tensorflow::SessionOptions const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<tensorflow::Device*, std::allocator<tensorflow::Device*> >*) (/tensorflowincludes/bin/libtensorflow_cc.so+0x1cc619a)
    #4 0x7f17bf851fe8 in tensorflow::DeviceFactory::AddDevices(tensorflow::SessionOptions const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<tensorflow::Device*, std::allocator<tensorflow::Device*> >*) (/tensorflowincludes/bin/libtensorflow_framework.so+0x62dfe8)
    #5 0x7f17c61ccea4 in tensorflow::DirectSessionFactory::NewSession(tensorflow::SessionOptions const&, tensorflow::Session**) (/tensorflowincludes/bin/libtensorflow_cc.so+0x6284ea4)
    #6 0x7f17bf8abfe8 in tensorflow::NewSession(tensorflow::SessionOptions const&, tensorflow::Session**) (/tensorflowincludes/bin/libtensorflow_framework.so+0x687fe8)
    #7 0x7f17bf8ac0ac in tensorflow::NewSession(tensorflow::SessionOptions const&) (/tensorflowincludes/bin/libtensorflow_framework.so+0x6880ac)
    #8 0x402bc2 in Temp::Temp() /var/jenkins_home/workspace/tensorflowleaktest_master-FVC6RQR2GX36IO3JBYVHBT3IJH3EQUQFR2B3OPUAPWVP7LOWN2WQ/tests/src/main.cpp:38
    #9 0x402245 in main /var/jenkins_home/workspace/tensorflowleaktest_master-FVC6RQR2GX36IO3JBYVHBT3IJH3EQUQFR2B3OPUAPWVP7LOWN2WQ/tests/src/main.cpp:44
    #10 0x7f17be6c582f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

Indirect leak of 323 byte(s) in 323 object(s) allocated from:
    #0 0x7f17c81b7532 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x99532)
    #1 0x7f17c1c1ad87 in tensorflow::RegisterXlaDeviceKernels(char const*, char const*) (/tensorflowincludes/bin/libtensorflow_cc.so+0x1cd2d87)
    #2 0x7f17c1c0e19a in tensorflow::XlaCpuDeviceFactory::CreateDevices(tensorflow::SessionOptions const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<tensorflow::Device*, std::allocator<tensorflow::Device*> >*) (/tensorflowincludes/bin/libtensorflow_cc.so+0x1cc619a)
    #3 0x7f17bf851fe8 in tensorflow::DeviceFactory::AddDevices(tensorflow::SessionOptions const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<tensorflow::Device*, std::allocator<tensorflow::Device*> >*) (/tensorflowincludes/bin/libtensorflow_framework.so+0x62dfe8)
    #4 0x7f17c61ccea4 in tensorflow::DirectSessionFactory::NewSession(tensorflow::SessionOptions const&, tensorflow::Session**) (/tensorflowincludes/bin/libtensorflow_cc.so+0x6284ea4)
    #5 0x7f17bf8abfe8 in tensorflow::NewSession(tensorflow::SessionOptions const&, tensorflow::Session**) (/tensorflowincludes/bin/libtensorflow_framework.so+0x687fe8)
    #6 0x7f17bf8ac0ac in tensorflow::NewSession(tensorflow::SessionOptions const&) (/tensorflowincludes/bin/libtensorflow_framework.so+0x6880ac)
    #7 0x402bc2 in Temp::Temp() /var/jenkins_home/workspace/tensorflowleaktest_master-FVC6RQR2GX36IO3JBYVHBT3IJH3EQUQFR2B3OPUAPWVP7LOWN2WQ/tests/src/main.cpp:38
    #8 0x402245 in main /var/jenkins_home/workspace/tensorflowleaktest_master-FVC6RQR2GX36IO3JBYVHBT3IJH3EQUQFR2B3OPUAPWVP7LOWN2WQ/tests/src/main.cpp:44
    #9 0x7f17be6c582f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

SUMMARY: AddressSanitizer: 4443 byte(s) leaked in 325 allocation(s).

```

**Comment by tensorflowbutler** [comment]
Nagging Assignee @cy89: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by sddi** [comment]
Hello, I met the same problem, my TF version is 1.3. Anybody could help us solve the problem?

**Comment by azaks2** [comment]
I do not think there is an actually leak. The relevant code:

 static XlaDeviceOpRegistrations* registrations =
      RegisterXlaDeviceKernels(DEVICE_TPU_NODE, DEVICE_TPU_XLA_JIT);
  (void)registrations;

So we should have a global reference to the objects but it is possible the variable gets optimized away.
Do you have exact instructions (like build command) so i can reproduce the error.

Thanks

**Comment by Cameron-Chancey** [comment]
The options are : 
/usr/bin/c++   
-I/usr/local/include
-I/home/developer/workspace/tensorflowleaktest/build/../projects/include 
-I/home/developer/workspace/tensorflowleaktest/build/../tests/include 
-I/home/developer/tensorflow -I/home/developer/tensorflowincludes/bin 
-I/home/developer/tensorflowincludes/genfiles 
-I/usr/local/lib/python3.5/dist-packages/tensorflow/include 
-I/usr/local/lib/python2.7/dist-packages/tensorflow/include 
-I/home/developer/tensorflowincludes/google 
-I/tensorflow 
-I/tensorflowincludes/bin 
-I/tensorflowincludes/genfiles 
-I/home/developer/workspace/tensorflowleaktest/build/../libs/abseil-cpp  
-Wall 
-fprofile-arcs 
-ftest-coverage 
-g 
-std=c++14 
-O0 
-Wall 
-fprofile-arcs
-ftest-coverage 
-g 
-std=c++14 
-O0 
-fsanitize=address 
-fno-omit-frame-pointer  
-pthread 
-std=gnu++14 
-o CMakeFiles/tensorflowleaktest.dir/home/developer/workspace/tensorflowleaktest/tests/src/main.cpp.o 
-c /home/developer/workspace/tensorflowleaktest/tests/src/main.cpp

The full output of the build command with the make can be found here attached. 

[build_text.txt](https://github.com/tensorflow/tensorflow/files/2857210/build_text.txt)

Additionally a pre-compiled .ii file is attached below in a zip file. (A command -save_temps was passed in to create this file. )
[precompiled.zip](https://github.com/tensorflow/tensorflow/files/2857230/precompiled.zip)

**Comment by xprotobeast2** [comment]
This problem seems to still exist on Tensorflow 1.15

**Comment by turowicz** [comment]
Problem exists in TF 2.x

**Comment by Ursanon** [comment]
Any updates on this?

**Comment by bhack** [comment]
Tensorflow 1.x is not supported anymore.

**Comment by turowicz** [comment]
@bhack I guess the best way of dealing with bugs is to wait for the EOL of the product.

**Comment by bhack** [comment]
The point is that TF has not a public EOL policy. 
Also the new bug fixes are available generally in nightly or in the next release as we don't have patch releases other then for security bugs.

**Comment by mihaimaruseac** [comment]
Is this still an issue? (In latest TF/patches)

**Comment by chunduriv** [comment]
@Cameron-Chancey,

Sorry for the late response. Can you please try with the latest stable version (TF2.9.1) and let us know if issue still persists? Thank you.
