### ISSUE TITLE
//tensorflow/contrib/lookup:lookup_ops_test fails on 1.12

### ISSUE THREAD

**Issue by MorganR** [tensorflow/tensorflow#23564]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): Source
- TensorFlow version: 1.12
- Python version: 3.6
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): 0.19.0
- GCC/Compiler version (if compiling from source): 7.3.0
- CUDA/cuDNN version: Using CPU
- GPU model and memory: Using CPU

**Describe the problem**

When running tests from source on r1.12, the test //tensorflow/contrib/lookup:lookup_ops_test fails.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

I'm following the steps at https://www.tensorflow.org/install/sourcepip. This error occurs when I run
`bazel test -c opt -- //tensorflow/... -//tensorflow/compiler/... -//tensorflow/contrib/lite/...`

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

[test.log](https://github.com/tensorflow/tensorflow/files/2555016/test.log)

**Comment by drpngx** [comment]
Could you try at head and see if that works?

**Comment by MorganR** [comment]
I ran `bazel clean` and tried again at head of Master, but I saw exactly the same array mismatch error.

Note that this time I compiled with CUDA 10.0 and cuDNN 7.3 support, using an NVIDIA RTX 2080 Ti (11GB). Everything else is the same.

**Comment by MorganR** [comment]
Here is the recent log.

Also here is my list of pip installs, if it's to do with a library version issue:

absl-py (0.6.1)
astor (0.7.1)
astroid (2.0.4)
contextlib2 (0.5.5)
dm-sonnet (1.26)
gast (0.2.0)
grpcio (1.16.0)
h5py (2.8.0)
isort (4.3.4)
Keras (2.2.4)
Keras-Applications (1.0.6)
Keras-Preprocessing (1.0.5)
lazy-object-proxy (1.3.1)
Markdown (3.0.1)
mccabe (0.6.1)
melee (0.1.0)
mock (2.0.0)
numpy (1.15.4)
pbr (5.1.1)
pip (9.0.1)
pkg-resources (0.0.0)
portpicker (1.2.0)
protobuf (3.6.1)
pylint (2.1.1)
PyYAML (3.13)
scikit-learn (0.20.0)
scipy (1.1.0)
semantic-version (2.6.0)
setuptools (39.0.1)
six (1.11.0)
sklearn (0.0)
tensorboard (1.12.0)
termcolor (1.1.0)
trfl (1.0)
typed-ast (1.1.0)
Werkzeug (0.14.1)
wheel (0.32.2)
wrapt (1.10.11)

[gputest.log](https://github.com/tensorflow/tensorflow/files/2601335/gputest.log)

**Comment by drpngx** [comment]
This test is consistently passing for us. Can you try running just `MutableHashTableOpTest.testMutableHashTableOfTensors`?

**Comment by MorganR** [comment]
If I'm reading the test right, it looks like the problem is just that `np.sort` is not sorting the result as intended, but that Tensorflow is doing the right things. `np.sort` is sorting the last axis, so it checks that each pair is sorted, which is satisfied. I think the test should be sorting the keys, so the following changes are needed:

```
sorted_values = np.sort(exported_values.eval(), axis=0)
...
self.assertAllEqual([[0, 1], [2, 3], [4, 5]], sorted_values)
```

JFYI, here are the latest tests I did: I've deleted all the other tests in `lookup_ops_test` except for `MutableHashTableOpTest.testMutableHashTableOfTensors`. It seems `--test_filter` doesn't work right now with python tests.

I've run it with the following commands:
`bazel test --config=opt --config=cuda --cache_test_results=no --test_output=all  //tensorflow/contrib/lookup:lookup_ops_test`
`bazel test --config=opt --config=cuda --cache_test_results=no --test_output=all  --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" //tensorflow/contrib/lookup:lookup_ops_test`

These each provide the same error output:
```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //tensorflow/contrib/lookup:lookup_ops_test
-----------------------------------------------------------------------------
2018-11-22 17:16:33.328021: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:964] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-11-22 17:16:33.328383: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.635
pciBusID: 0000:01:00.0
totalMemory: 10.73GiB freeMemory: 10.10GiB
2018-11-22 17:16:33.328393: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2018-11-22 17:16:33.528223: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-11-22 17:16:33.528243: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
2018-11-22 17:16:33.528247: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
2018-11-22 17:16:33.528371: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3295 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:01:00.0, compute capability: 7.5)
F.
======================================================================
FAIL: testMutableHashTableOfTensors (__main__.MutableHashTableOpTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/morgan/.cache/bazel/_bazel_morgan/a1bbb0cd5ee11ffbec286625841ddec2/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/contrib/lookup/lookup_ops_test.runfiles/org_tensorflow/tensorflow/contrib/lookup/lookup_ops_test.py", line 73, in testMutableHashTableOfTensors
    self.assertAllEqual([[4, 5], [2, 3], [0, 1]], sorted_values)
  File "/home/morgan/.cache/bazel/_bazel_morgan/a1bbb0cd5ee11ffbec286625841ddec2/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/contrib/lookup/lookup_ops_test.runfiles/org_tensorflow/tensorflow/python/framework/test_util.py", line 1691, in assertAllEqual
    np.testing.assert_array_equal(a, b, err_msg="\n".join(msgs))
  File "/home/morgan/.pyenv/smashgpu/lib/python3.6/site-packages/numpy/testing/_private/utils.py", line 865, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/home/morgan/.pyenv/smashgpu/lib/python3.6/site-packages/numpy/testing/_private/utils.py", line 789, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

not equal where = (array([1, 1, 2, 2]), array([0, 1, 0, 1]))
not equal lhs = [2 3 0 1]
not equal rhs = [0 1 2 3]
(mismatch 66.66666666666666%)
 x: array([4, 5, 2, 3, 0, 1])
 y: array([4, 5, 0, 1, 2, 3])

----------------------------------------------------------------------
Ran 2 tests in 0.353s

FAILED (failures=1)
```

**Comment by MorganR** [comment]
I created a pull request
https://github.com/tensorflow/tensorflow/pull/23927

**Comment by mihaimaruseac** [comment]
Is this still an issue?

**Comment by rmothukuru** [comment]
@MorganR,
Can you please let us know if it is still an issue and if we can close this? Thanks!

**Comment by mihaimaruseac** [comment]
1.12 is no longer supported, so we cannot operate on this anymore.
