### ISSUE TITLE
Ubuntu 18.04 bazel build from source fails

### ISSUE THREAD

**Issue by ArmaanBhullar** [tensorflow/tensorflow#23574]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution:   
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic

- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.12.0
- Python version: 3.6
- Installed using virtualenv? pip? conda?: NA
- Bazel version (if compiling from source): bazel release 0.18.1
- GCC/Compiler version (if compiling from source): gcc-6
- CUDA/cuDNN version: CUDA-9.1, cuDNN-7.1
- GPU model and memory: NVIDIA Corporation GP106M [GeForce GTX 1060 Mobile] (rev a1)

**Describe the problem**
Building from source, fails on executing bazel build instruction.
**Provide the exact sequence of commands / steps that you executed before running into the problem**
I'm trying to build tensorflow from source on my system, following https://medium.com/@asmello/how-to-install-tensorflow-cuda-9-1-into-ubuntu-18-04-b645e769f01d as my OS is ubuntu 18.04, following these steps I ran the ./configure and then "bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package" to build.
build goes on for a couple hours, everything seems fine until the very end when I get this error

**Any other info / logs**
ERROR: /home/armaan/software/tensorflow/tensorflow/BUILD:561:1: Executing genrule //tensorflow:tf_python_api_gen_v1 failed (Exit 1)
Traceback (most recent call last):
  File "/home/armaan/.cache/bazel/_bazel_armaan/68a0964576af93b9dcbb773eca5ca492/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/armaan/.cache/bazel/_bazel_armaan/68a0964576af93b9dcbb773eca5ca492/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/armaan/.cache/bazel/_bazel_armaan/68a0964576af93b9dcbb773eca5ca492/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /home/armaan/.cache/bazel/_bazel_armaan/68a0964576af93b9dcbb773eca5ca492/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: _ZTIN6icu_608ByteSinkE

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/armaan/.cache/bazel/_bazel_armaan/68a0964576af93b9dcbb773eca5ca492/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/python/tools/api/generator/create_python_api.py", line 27, in <module>
    from tensorflow.python.tools.api.generator import doc_srcs
  File "/home/armaan/.cache/bazel/_bazel_armaan/68a0964576af93b9dcbb773eca5ca492/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/armaan/.cache/bazel/_bazel_armaan/68a0964576af93b9dcbb773eca5ca492/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/armaan/.cache/bazel/_bazel_armaan/68a0964576af93b9dcbb773eca5ca492/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/armaan/.cache/bazel/_bazel_armaan/68a0964576af93b9dcbb773eca5ca492/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/armaan/.cache/bazel/_bazel_armaan/68a0964576af93b9dcbb773eca5ca492/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /home/armaan/.cache/bazel/_bazel_armaan/68a0964576af93b9dcbb773eca5ca492/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: _ZTIN6icu_608ByteSinkE

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 6680.706s, Critical Path: 297.19s
INFO: 14471 processes: 14471 local.
FAILED: Build did NOT complete successfully

**Comment by bjascob** [comment]
I believe the TF team is compiling 1.12.0 for Cuda 9.2.  Maybe there's some incompatibility with TF1.2 and Cuda 9.1??  I'm not sure your specific issue but I have a similar setup and I'm using Cuda 10.0 (and the associated cuDNN 7.3.1) installed from the official NVidia download, see [Cuda 10](https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&target_distro=Ubuntu&target_version=1804).  I've had issues in the past installing earlier gcc versions to overcome the Cuda compatibility issues.  This package is setup for 18.04 and so it works with gcc 7.0 (the default compiler).  No need to install gcc 6.

For my Ubuntu 18.04 with Cuda 10.0 with TF 1.12.0 compiling for source worked great.

**Comment by harshini-gadige** [comment]
@ArmaanBhullar  -  Please use Bazel 0.15.0 and GCC 4.8.

**Comment by ArmaanBhullar** [comment]
@harshini-gadige  thanks, I'll retry using Bazel 0.15.0 and GCC 4.8, and close this issues if it works :)
but just curious, is there any documentation which says to use these particular Bazel and GCC versions?

**Comment by ArmaanBhullar** [comment]
@harshini-gadige  I tried with the gcc and bazel versions you specified but faced the following error:
ERROR: /home/armaan/.cache/bazel/_bazel_armaan/68a0964576af93b9dcbb773eca5ca492/external/com_google_absl/absl/base/BUILD.bazel:58:1: C++ compilation of rule '@com_google_absl//absl/base:dynamic_annotations' failed (Exit 1)
gcc-4.8: error trying to exec 'cc1plus': execvp: No such file or directory
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.

**Comment by harshini-gadige** [comment]
@gunan  PTAL

**Comment by MingyaoLiu** [comment]
Here is a ubuntu 18.10 build (kernal 4.18), tensorflow r1.12 branch, python 3.6, CUDA 10.0, cuDNN 7.4.1.5, NCCL 2.3.7, tensorRT 5.0, compute capability 7.5, 6.1, for my RTX 2080 TI.
[tensorflow-1.12.0-cp36-cp36m-linux_x86_64.whl](https://app.box.com/s/jcw8uq6jannpg4myzighl166bq1zg07e)

It took me around 2 full day to get it built, so many issue among bazel version (I used 0.18.1 it works), python (3.6.7), gcc g++(I used 7.3), etc too many

**Comment by harshini-gadige** [comment]
@MingyaoLiu  Great and thanks for your support.

@ArmaanBhullar  -  Any update based on @MingyaoLiu  build ?

**Comment by harshini-gadige** [comment]
In "awaiting response" status for more than 3 days. Hence closing this. Please post the updates here if any, we will reopen the issue. Thanks !

**Comment by HappyCtest** [comment]
I got the similar issue:
```
ERROR: /home/charles/tensorflow-installation/tensorflow/tensorflow/BUILD:533:1: Executing genrule //tensorflow:tf_python_api_gen_v1 failed (Exit 1)
Traceback (most recent call last):
  File "/home/charles/.cache/bazel/_bazel_charles/f8def8956ae05eead7ef4aca6059934c/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/charles/.cache/bazel/_bazel_charles/f8def8956ae05eead7ef4aca6059934c/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/charles/.cache/bazel/_bazel_charles/f8def8956ae05eead7ef4aca6059934c/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/opt/anaconda3/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/opt/anaconda3/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /home/charles/.cache/bazel/_bazel_charles/f8def8956ae05eead7ef4aca6059934c/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: _ZTVN6icu_609ErrorCodeE

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/charles/.cache/bazel/_bazel_charles/f8def8956ae05eead7ef4aca6059934c/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/python/tools/api/generator/create_python_api.py", line 27, in <module>
    from tensorflow.python.tools.api.generator import doc_srcs
  File "/home/charles/.cache/bazel/_bazel_charles/f8def8956ae05eead7ef4aca6059934c/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/charles/.cache/bazel/_bazel_charles/f8def8956ae05eead7ef4aca6059934c/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/charles/.cache/bazel/_bazel_charles/f8def8956ae05eead7ef4aca6059934c/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/charles/.cache/bazel/_bazel_charles/f8def8956ae05eead7ef4aca6059934c/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/charles/.cache/bazel/_bazel_charles/f8def8956ae05eead7ef4aca6059934c/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/opt/anaconda3/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/opt/anaconda3/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /home/charles/.cache/bazel/_bazel_charles/f8def8956ae05eead7ef4aca6059934c/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: _ZTVN6icu_609ErrorCodeE


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 17185.854s, Critical Path: 1003.10s, Remote (0.00% of the time): [queue: 0.00%, setup: 0.00%, process: 0.00%]
INFO: 13895 processes: 13895 local.
FAILED: Build did NOT complete successfully
```

It is frustrating. Did you ever solve the problem? @nathanielhobbs @nathanielhobbs
