### ISSUE TITLE
Simplest WindowDataset usage not working even for the documented examples

### ISSUE THREAD

**Issue by antifriz** [tensorflow/tensorflow#23581]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): tensorflow/tensorflow:1.12.0 docker image, macOS 10.14
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: no
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.12.0
- Python version: 2.7
- Bazel version (if compiling from source): no
- GCC/Compiler version (if compiling from source): no
- CUDA/cuDNN version: no
- GPU model and memory: no

**Describe the current behavior**

`Dataset.window` documentation has a few examples of which all crash in the process of graph construction (i.e. this example `tf.data.Dataset.range(7).window(2)`).

**Describe the expected behavior**

I would like it not to crash.

**Code to reproduce the issue**

```python

from __future__ import absolute_import, division, print_function

import tensorflow as tf

tf.enable_eager_execution()

dataset = tf.data.Dataset.range(7).window(2)

it = dataset.make_one_shot_iterator()

```

The same error occurs when eager execution is disabled.

**Other info / logs**

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-4495120d82f9> in <module>()
      7 dataset = tf.data.Dataset.range(7).window(2)
      8 
----> 9 it = dataset.make_one_shot_iterator()

/usr/local/lib/python2.7/dist-packages/tensorflow/python/data/ops/dataset_ops.pyc in make_one_shot_iterator(self)
    178     """
    179     if context.executing_eagerly():
--> 180       return iterator_ops.EagerIterator(self)
    181     # NOTE(mrry): We capture by value here to ensure that `_make_dataset()` is
    182     # a 0-argument function.

/usr/local/lib/python2.7/dist-packages/tensorflow/python/data/ops/iterator_ops.pyc in __init__(self, dataset)
    531         self._resource = gen_dataset_ops.anonymous_iterator(
    532             output_types=self._flat_output_types,
--> 533             output_shapes=self._flat_output_shapes)
    534         gen_dataset_ops.make_iterator(ds_variant, self._resource)
    535         # Delete the resource when this object is deleted

/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_dataset_ops.pyc in anonymous_iterator(output_types, output_shapes, name)
     71       return anonymous_iterator_eager_fallback(
     72           output_types=output_types, output_shapes=output_shapes, name=name,
---> 73           ctx=_ctx)
     74     except _core._NotOkStatusException as e:
     75       if name is not None:

/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_dataset_ops.pyc in anonymous_iterator_eager_fallback(output_types, output_shapes, name, ctx)
     89         "Expected list for 'output_types' argument to "
     90         "'anonymous_iterator' Op, not %r." % output_types)
---> 91   output_types = [_execute.make_type(_t, "output_types") for _t in output_types]
     92   if not isinstance(output_shapes, (list, tuple)):
     93     raise TypeError(

/usr/local/lib/python2.7/dist-packages/tensorflow/python/eager/execute.pyc in make_type(v, arg_name)
    124   except TypeError:
    125     raise TypeError("Expected DataType for argument '%s' not %s." %
--> 126                     (arg_name, repr(v)))
    127   i = v.as_datatype_enum
    128   return i

TypeError: Expected DataType for argument 'output_types' not <tensorflow.python.data.ops.dataset_ops._NestedDatasetComponent object at 0x7feadf71f9d0>.
```

**Comment by ymodak** [comment]
I am able to execute your script by using latest tf-nightly build. Can you please confirm it?

**Comment by jsimsa** [comment]
@antifriz your interpretation of the examples in the `window` dataset documentation is incorrect.

The result of applying the `window` transformation is a nested dataset, which needs to be flattened before it can be evaluated. One such mechanism for flattening a dataset is `flat_map`.

For instance,

```
dataset = tf.data.Dataset.range(7).window(2).flat_map(lambda x: x.skip(1))
```

produces a dataset that skips all even elements of the original range.

**Comment by npuichigo** [comment]
@jsimsa So how can we group adjacent elements during sequence into windows using tf.data? Maybe like what tf.contrib.signal.frame does.

**Comment by jsimsa** [comment]
If by grouping, you mean creating a higher-dimensional element that groups input elements, then the simplest use case can be addressed by using `batch`. For instance, `tf.data.Dataset.range(4).batch(2)` produces `{[0, 1], [2, 3]}`. 

If you would like to customize the shift and stride used for grouping the elements, you can do so by the virtue of `window(size, shift, stride, drop_remainder).flat_map(lambda x: x.batch(size))`. For instance, `tf.data.Dataset.range(4).window(2, 1, 2, True).flat_map(lambda x: x.batch(2))` produces `{[0, 2], [1, 3]}`.

If I misunderstood your question, please provide an example of the input sequence and the desired output sequence.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by jsimsa** [comment]
Closing due to inactivity.

**Comment by Rangozhang** [comment]
@jsimsa Hey Jiri, thanks for the answers above. But I'm getting an error when I'm trying to do the same on a dictionary-like dataset:
```
tf.data.Dataset.from_tensor_slices({"a": [1,2,3,4]}).window(3).flat_map(lambda x: x.batch(3))
```

It'll give me the error of ```AttributeError: 'dict' object has no attribute 'batch'```

Do you know if there's a way to do it on a dictionary-like tf.data.Dataset?

Thanks

**Comment by jsimsa** [comment]
For a dataset of nested elements `window` creates a dataset of nested datasets of flat elements, not a dataset of datasets of nested elements.

In other words, the `x` in your `lambda` will be a dictionary mapping keys to datasets and if you wish to flatten it to a single dataset you will need to do:

```
flat_map_fn(x):
  result = {}
  for key in x.keys():
    result[key] = x[key].batch(3)
  return result

tf.data.Dataset.from_tensor_slices({"a": [1,2,3,4]}).window(3).flat_map(flat_map_fn)
```

**Comment by Rangozhang** [comment]
@jsimsa Hey Jiri, thank you very much for the prompt reply. But I still got the same error even with "tf.data.experimental.get_single_element" function:

I'm using tensorflow 1.14 and python3.
```
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    tf.data.Dataset.from_tensor_slices({"a": [1,2,3,4]}).window(3).flat_map(map_fn)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 1817, in flat_map
    return DatasetV1Adapter(super(DatasetV1, self).flat_map(map_func))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 1160, in flat_map
    return FlatMapDataset(self, map_func)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 3264, in __init__
    type(self._map_func.output_structure)))
TypeError: `map_func` must return a `Dataset` object. Got <class 'tensorflow.python.data.util.structure.NestedStructure'>

```

**Comment by jsimsa** [comment]
Try again, I have made changes to the example code and made sure it runs.

**Comment by Rangozhang** [comment]
@jsimsa Ah, got you. It works now with the tf.data.Dataset.map() function. Thanks for your help Jiri!

**Comment by zxbnjust** [comment]
> For a dataset of nested elements `window` creates a dataset of nested datasets of flat elements, not a dataset of datasets of nested elements.
> 
> In other words, the `x` in your `lambda` will be a dictionary mapping keys to datasets and if you wish to flatten it to a single dataset you will need to do:
> 
> ```
> def map_fn(x):
>   result = {}
>   for key in x.keys():
>     result[key] = tf.data.experimental.get_single_element(x[key].batch(3))
>   return result
> 
> dataset = tf.data.Dataset.from_tensor_slices({"a": [1,2,3,4]}).window(3).map(map_fn)
> ```

Hi,I think I got the same problem with Rangozhang,but I got the following wrong info.Can you help me?
NotImplementedError: The Dataset.map() transformation does not currently support nested datasets as inputs.
The code is as follows:
/////////////////////////////////////////////////////////////////////////////////////
dataset = tf.data.Dataset.from_tensor_slices(tfrecord_fpaths)       #extract data 
        if shuffle:
            dataset = dataset.shuffle(len(tfrecord_fpaths))

        # Use `Dataset.flat_map()` to transform each file as a separate nested dataset,
        # and then concatenate their contents sequentially into a single "flat" dataset.

        dataset = dataset.flat_map(lambda filename: tf.data.TFRecordDataset(filename,
                                                                            compression_type="GZIP",
                                                                            num_parallel_reads=num_parallel_reads,
                                                                            ),
                                   )
        

        


        # deserialize tfexamples
        dataset = dataset.map(lambda serialized: tf.parse_single_example(serialized, feature_schema),
                              num_parallel_calls=num_parallel_calls,
                              )




        for preprocessor in model_preprocessors or []:
            dataset = preprocessor.preprocess(dataset, mode)
        def map_fn(x):
            result = {}
            for key in x.keys():
                result[key] = tf.data.experimental.get_single_element(x[key].batch(4))
            return result
        dataset = dataset.window(4,1,1,drop_remainder=True).map(map_fn)
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
