### ISSUE TITLE
OSError and ImportError 

### ISSUE THREAD

**Issue by MMron** [tensorflow/tensorflow#23638]
**System information**
- OS Platform and Distribution: Windows 8.1
- TensorFlow installed from (source or binary): https://pypi.org/project/tensorflow-gpu/1.5.0/#files 
- TensorFlow version: 1.5.0
- Python version:3.6.5.final.0
- Installed using virtualenv? pip? conda?: installed on own computer with pip command 
- Bazel version (if compiling from source): (?)
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: v9.0/v7.4.1 (Nov 8, 2018), for CUDA 9.0
- GPU model and memory: GeForce GTX 960M 6MB 

**Describe the problem**
The problem seems to be that when i download the tensorflow-gpu, I do now have the tensorflow module do I also need to install tensorflow sepratly, tought that will destroy the setup. 
Also the environment does not recognize the cudart64_90.dll file in the folder described provided in the additional information

followed description from https://www.youtube.com/watch?v=uIm3DMprk7M 
- first installing CUDA v9.0 from https://developer.nvidia.com/cuda-90-download-archive
- then installing cuDNN version 7.4.1 for CUDA 9.0  from https://developer.nvidia.com/rdp/cudnn-download 
- then i downloaded tensorflow-gpu from https://pypi.org/project/tensorflow-gpu/1.5.0/?fbclid=IwAR3xogCL0DA4kdhIqLGCcXSYUka9n0CtBCxbpWzAh-rKrubLKQbJPIla8kA#files 
- lastly I opend python in anaconda navigator, then tried to import tensorflow 
output is printed below.

additional information: 
- cudart64_90.dll is located in the folder C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin . 
- comands are done on a new environment with following packages 
absl-py                   0.6.1
bleach                    1.5.0
certifi                   2018.10.15
html5lib                  0.9999999
Markdown                  3.0.1
numpy                     1.15.4
pip                       18.1
protobuf                  3.6.1
python                    3.6.7
setuptools                40.5.0
six                       1.11.0
tensorflow-gpu            1.5.0
tensorflow-tensorboard    1.5.1
vc                        14.1
vs2015_runtime            14.15.26706
Werkzeug                  0.14.1
wheel                     0.32.2
wincertstore              0.2

**Any other info / logs**
>>> import tensorflow
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\aienv1\lib\site-packages\tensorflow\python
\platform\self_check.py", line 75, in preload_check
    ctypes.WinDLL(build_info.cudart_dll_name)
  File "C:\ProgramData\Anaconda3\envs\aienv1\lib\ctypes\__init__.py", line 348,
in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\envs\aienv1\lib\site-packages\tensorflow\__init
__.py", line 24, in <module>
    from tensorflow.python import *
  File "C:\ProgramData\Anaconda3\envs\aienv1\lib\site-packages\tensorflow\python
\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\ProgramData\Anaconda3\envs\aienv1\lib\site-packages\tensorflow\python
\pywrap_tensorflow.py", line 30, in <module>
    self_check.preload_check()
  File "C:\ProgramData\Anaconda3\envs\aienv1\lib\site-packages\tensorflow\python
\platform\self_check.py", line 82, in preload_check
    % (build_info.cudart_dll_name, build_info.cuda_version_number))
ImportError: Could not find 'cudart64_90.dll'. TensorFlow requires that this DLL
 be installed in a directory that is named in your %PATH% environment variable.
Download and install CUDA 9.0 from this URL: https://developer.nvidia.com/cuda-t
oolkit

**Comment by MMron** [comment]
Needed to restart anaconda, everything seems fine now :)
