### ISSUE TITLE
run error when i use xla

### ISSUE THREAD

**Issue by dongAxis** [tensorflow/tensorflow#23648]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): centos 7.0
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version:  master branch and commit id is b300c78a889aa75b04f6bcff2a6a5fb5d0976b4d
- Python version: 3.6
- Installed using virtualenv? pip? conda?: no
- Bazel version (if compiling from source): 0.18.0
- GCC/Compiler version (if compiling from source): gcc 4.9.2
- CUDA/cuDNN version: no
- GPU model and memory: 131G

**Describe the problem**
The below is my building step:
1. bazel build --jobs 32  -c opt -c dbg --strip=never  //tensorflow/tools/pip_package:build_pip_package
or bazel build --jobs 32  -c opt -c dbg //tensorflow/tools/pip_package:build_pip_package

2. ./bazel-bin/tensorflow/tools/pip_package/build_pip_package ./tmp/tensorflow_pkg
3. pip3.6 install ./tensorflow-1.12.0rc0-cp36-cp36m-linux_x86_64.whl

But when i run the code with command：
TF_XLA_FLAGS="--xla_hlo_graph_path=/tmp --xla_generate_hlo_graph=.*" python3.6 mnist_softmax_xla.py
i got an error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/local/lib64/python3.6/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/local/lib64/python3.6/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /usr/local/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: _ZN10tensorflow19XlaCompilationCache28kDefaultCompilationThresholdE

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mnist_softmax_xla.py", line 26, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/local/lib64/python3.6/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/local/lib64/python3.6/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /usr/local/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: _ZN10tensorflow19XlaCompilationCache28kDefaultCompilationThresholdE

it is just like kDefaultCompilationThreshold dose not existed in tensorflow_framework.so

**Provide the exact sequence of commands / steps that you executed before running into the problem**
check the above 

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatatodd: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by mhsmith** [comment]
I got the same error when building TensorFlow 0.13.1 with Clang 7.0.2. It's caused by `kDefaultCompilationThreshold` being declared as `constexpr`. 

As described [here](https://stackoverflow.com/questions/48361845), I was able to work around it by adding the following line below `namespace tensorflow` in `xla_compilation_cache.cc`:

```
constexpr int64 XlaCompilationCache::kDefaultCompilationThreshold;
```

**Comment by sanatmpa1** [comment]
@dongAxis,

We see you were using an older version of tensorflow(1.x) which is officially considered as end of life. We recommend that you upgrade to latest stable version and let us know if the issue still persists in newer versions.we will get you the right help.Thanks!

**Comment by mhsmith** [comment]
For me, the issue was no longer present in TensorFlow 2.1.0.
