### ISSUE TITLE
r1.12 C++ tutorials_example_trainer failed to build on Windows

### ISSUE THREAD

**Issue by stakemura** [tensorflow/tensorflow#23655]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Windows 10 v1803 Pro 64bit English
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:N/A
- TensorFlow installed from (source or binary):source
- TensorFlow version:1.12
- Python version:3.6
- Installed using virtualenv? pip? conda?:pip
- Bazel version (if compiling from source):0.15
- GCC/Compiler version (if compiling from source):MSVC 2015 update 3
- CUDA/cuDNN version:N/A
- GPU model and memory:N/A

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

***Commands***
```
bazel build -c opt --verbose_failures //tensorflow/cc:tutorials_example_trainer
```

***Steps***
Setup as described in [official document](https://www.tensorflow.org/install/source_windows)

.bazelrc is customized in the following way.
```
import (YOUR_TENSORFLOW_FOLDER)/tf_configure.bazelrc
```
.tf_configure.bazelrc is customized in the following way.
```
build:ignite --define with_ignite_support=true
build:xla --define with_xla_support=false
build --action_env TF_NEED_OPENCL_SYCL="0"
build --action_env TF_NEED_ROCM="0"
build --action_env TF_NEED_CUDA="0"
build --action_env TF_DOWNLOAD_CLANG="0"
build:opt --copt=/arch:AVX2
build:opt --define with_default_optimizations=true
build --copt=-w --host_copt=-w
build --verbose_failures
build --distinct_host_configuration=false
build --experimental_shortened_obj_file_path=true
build --define=no_tensorflow_py_deps=true
build --define=override_eigen_strong_inline=true
build:v2 --define=tf_api_version=2
```

**Any other info / logs**
```
unicode_script_op.lo.lib(unicode_script_op.obj) : error LNK2019: unresolved external symbol "__declspec(dllimport) public: virtual __cdecl icu_62::ErrorCode::~ErrorCode(void)" (__imp_??1ErrorCode@icu_62@@UEAA@XZ) referenced in function "public: virtual void __cdecl tensorflow::UnicodeScriptOp::Compute(class tensorflow::OpKernelContext *)" (?Compute@UnicodeScriptOp@tensorflow@@UEAAXPEAVOpKernelContext@2@@Z)
unicode_script_op.lo.lib(unicode_script_op.obj) : error LNK2019: unresolved external symbol "__declspec(dllimport) public: signed char __cdecl icu_62::ErrorCode::isSuccess(void)const " (__imp_?isSuccess@ErrorCode@icu_62@@QEBACXZ) referenced in function "public: virtual void __cdecl tensorflow::UnicodeScriptOp::Compute(class tensorflow::OpKernelContext *)" (?Compute@UnicodeScriptOp@tensorflow@@UEAAXPEAVOpKernelContext@2@@Z)
unicode_script_op.lo.lib(unicode_script_op.obj) : error LNK2019: unresolved external symbol "__declspec(dllimport) public: enum UErrorCode __cdecl icu_62::ErrorCode::reset(void)" (__imp_?reset@ErrorCode@icu_62@@QEAA?AW4UErrorCode@@XZ) referenced in function "public: virtual void __cdecl tensorflow::UnicodeScriptOp::Compute(class tensorflow::OpKernelContext *)" (?Compute@UnicodeScriptOp@tensorflow@@UEAAXPEAVOpKernelContext@2@@Z)
unicode_script_op.lo.lib(unicode_script_op.obj) : error LNK2019: unresolved external symbol "__declspec(dllimport) const icu_62::ErrorCode::`vftable'" (__imp_??_7ErrorCode@icu_62@@6B@) referenced in function "public: virtual void __cdecl tensorflow::UnicodeScriptOp::Compute(class tensorflow::OpKernelContext *)" (?Compute@UnicodeScriptOp@tensorflow@@UEAAXPEAVOpKernelContext@2@@Z)
```
Similar to tutorials_example_trainer, build //tensorflow/examples/label_image:label_image also failed.

**Comment by cielavenir** [comment]
Took a look at this and the first build was done as the screenshot. [![Imgur](https://i.imgur.com/sQhvd0Wl.png)](https://imgur.com/sQhvd0W)

**Comment by cielavenir** [comment]
Materials (rev1) are in https://gist.github.com/cielavenir/4b55dce31bbf93f5fee5c5b2bfbebfda.

The main thing win.patch consists of two parts.

The first is ICU. I needed to add U_STATIC_IMPLEMENTATION flag to link to original symbols, not `__imp_`. This had to be added also to third_party/icu/BUILD.bazel because udata.cpp tries to link __imp_icudt62_dat, which also we don't want.

The second is disabling framework_shared_object. I came up with because `tensorflow_framework` [^1] should be from `-ltensorflow_framework` or `libtensorflow_framework.so`. I knew this disabling is a workaround. To understand why disabling this makes the build successful is the next step.

[^1]: `link.exe /nologo /OUT:bazel-out/host/bin/tensorflow/cc/ops/sparse_ops_gen_cc.exe tensorflow_framework /SUBSYSTEM:CONSOLE` # this tensorflow_framework is orphaned bad guy.

**Comment by stakemura** [comment]
@cielavenir I appreciate your kindness. I’m gonna try your modification.

*for everyone
I heard final configuration and initial error log directly from him and updated this issue.*

**Comment by cielavenir** [comment]
The ICU link error part was pasted, but tensorflow_framework.obj not found error is not pasted. So I'm pasting below.

```
ERROR: C:/users/*********/tensorflow/tensorflow/cc/BUILD:456:1:
Linking of rule '//tensorflow/cc:ops/data_flow_ops_gen_cc' failed
(Exit 1181): link.exe failed: error executing command
  cd D:/temp/_bazel_*********/kyctgnhj/execroot/org_tensorflow
 SET INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio
14.0\VC\INCLUDE;C:\Program Files (x86)\Microsoft Visual Studio
14.0\VC\ATLMFC\INCLUDE;C:\Program Files (x86)\Windows
Kits\10\include\10.0.14393.0\ucrt;C:\Program Files (x86)\Windows
Kits\NETFXSDK\4.6.1\include\um;C:\Program Files (x86)\Windows
Kits\10\include\10.0.14393.0\shared;C:\Program Files (x86)\Windows
Kits\10\include\10.0.14393.0\um;C:\Program Files (x86)\Windows
Kits\10\include\10.0.14393.0\winrt;
    SET LIB=C:\Program Files (x86)\Microsoft Visual Studio
14.0\VC\LIB\amd64;C:\Program Files (x86)\Microsoft Visual Studio
14.0\VC\ATLMFC\LIB\amd64;C:\Program Files (x86)\Windows
Kits\10\lib\10.0.14393.0\ucrt\x64;C:\Program Files (x86)\Windows
Kits\NETFXSDK\4.6.1\lib\um\x64;C:\Program Files (x86)\Windows
Kits\10\lib\10.0.14393.0\um\x64;
    SET PATH=C:\Program Files (x86)\Microsoft Visual Studio
14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program
Files (x86)\Microsoft Visual Studio
14.0\VC\BIN\amd64;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program
Files (x86)\Microsoft Visual Studio 14.0\VC\VCPackages;C:\Program
Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE;C:\Program Files
(x86)\Microsoft Visual Studio 14.0\Common7\Tools;C:\Program Files
(x86)\Microsoft Visual Studio 14.0\Team Tools\Performance
Tools\x64;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team
Tools\Performance Tools;C:\Program Files (x86)\Windows
Kits\10\bin\x64;C:\Program Files (x86)\Windows
Kits\10\bin\x86;C:\Program Files (x86)\Microsoft
SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\x64\;;C:\Windows\system32
    SET PWD=/proc/self/cwd
    SET PYTHON_BIN_PATH=C:/Python36/python.exe
    SET PYTHON_LIB_PATH=C:/Python36/lib/site-packages
    SET TEMP=D:\temp\
    SET TF_DOWNLOAD_CLANG=0
    SET TF_NEED_CUDA=0
    SET TF_NEED_OPENCL_SYCL=0
    SET TF_NEED_ROCM=0
    SET TMP=D:\temp\
    SET USE_LINKER=1
  C:/Program Files (x86)/Microsoft Visual Studio
14.0/VC/bin/amd64/link.exe /nologo
/OUT:bazel-out/x64_windows-opt/bin/tensorflow/cc/ops/data_flow_ops_gen_cc.exe
tensorflow_framework /SUBSYSTEM:CONSOLE /MACHINE:X64
@bazel-out/x64_windows-opt/bin/tensorflow/cc/ops/data_flow_ops_gen_cc.exe-2.params
LINK : fatal error LNK1181: cannot open input file 'tensorflow_framework.obj'
Target //tensorflow/cc:tutorials_example_trainer failed to build
```

**Comment by stakemura** [comment]
I found that the following option in .tf_configure.bazelrc raises the above LNK1181 error.
This option is automatically added by configure.py.
So we should manually remove this option before build.
``` 
build --config monolithic
```

**Comment by stbnps** [comment]
Hi

I've just reproduced @cielavenir solution.
In my case, I only had to use the ICU flags: `#define U_STATIC_IMPLEMENTATION` and `"-DU_STATIC_IMPLEMENTATION"` to get it working. **No further changes were needed!**

Thanks for sharing your patch!

My setup:
Tensorflow r1.12
Visual Studio 2015
Bazel 0.18.1

**Comment by cielavenir** [comment]
actually bazelrc was not required so I removed it from gist

**Comment by tensorflowbutler** [comment]
Nagging Assignee @harshini-gadige: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by matth79** [comment]
Probable duplicate

https://github.com/tensorflow/tensorflow/issues/24499

**Comment by cielavenir** [comment]
@hgadig now I see this issue is closed, may I have the relevant commit?

**Comment by jesen8** [comment]
@stakemura @cielavenir @stbnps  how do you success?  i only changed code below according to @cielavenir 's tutorial

1.  in D:\tf3\tensorflow-r1.12\third_party\icu\BUILD.bazel 
cc_library(
    name = "icuuc",
    srcs = glob(
        [
            "icu4c/source/common/*.c",
            "icu4c/source/common/*.cpp",
            "icu4c/source/stubdata/*.cpp",
        ],
    ),
    hdrs = glob([
        "icu4c/source/common/*.h",
    ]),
    copts = [
        "-DU_COMMcON_IMPLEMENTATION",
        **"-DU_STATIC_IMPLEMENTATION",**
        "-DU_HAVE_STD_ATOMICS",
    ] + select({
        ":android": [

2. in D:\tf3\tensorflow-r1.12\tensorflow\BUILD
# Crosses between framework_shared_object and a bunch of other configurations
# due to limitations in nested select() statements.
config_setting(
    name = "framework_shared_object",
    define_values = {
        **"framework_shared_object": "false",**
    },
    visibility = ["//visibility:public"],
)

3. in D:\tf3\tensorflow-r1.12\tensorflow\core\kernels\unicode_script_op.cc
==============================================================================*/

**#define U_STATIC_IMPLEMENTATION**

#include "unicode/errorcode.h"  // TF:icu
#include "unicode/uscript.h"  // TF:icu
#include "tensorflow/core/framework/op_kernel.h"

and then i run   "bazel build --config=opt --config=cuda  //tensorflow:libtensorflow_cc.so"

FAILED: Build did NOT complete successfully (94 packages loaded)
java.lang.RuntimeException: **Unrecoverable error while evaluating node** '//tensorflow/cc:ops/data_flow_ops_gen_cc BuildConfigurationValue.Key[40ef114e63aa727cdd3c39a233ab7f41] false' (requested by nodes '//tensorflow/cc:data_flow_ops_genrule BuildConfigurationValue.Key[40ef114e63aa727cdd3c39a233ab7f41] false')
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:497)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:368)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException
        at com.google.common.base.Preconditions.checkState(Preconditions.java:491)
        at com.google.devtools.build.lib.rules.cpp.LibrariesToLinkCollector.addDynamicInputLinkOptions(LibrariesToLinkCollector.java:290)
        at com.google.devtools.build.lib.rules.cpp.LibrariesToLinkCollector.addLinkerInputs(LibrariesToLinkCollector.java:258)
        at com.google.devtools.build.lib.rules.cpp.LibrariesToLinkCollector.collectLibrariesToLink(LibrariesToLinkCollector.java:203)
        at com.google.devtools.build.lib.rules.cpp.CppLinkActionBuilder.build(CppLinkActionBuilder.java:916)
        at com.google.devtools.build.lib.rules.cpp.CcBinary.init(CcBinary.java:413)
        at com.google.devtools.build.lib.rules.cpp.CcBinary.create(CcBinary.java:179)
        at com.google.devtools.build.lib.rules.cpp.CcBinary.create(CcBinary.java:71)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:320)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:205)
        at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:631)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:770)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:320)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:420)
        ... 4 more
java.lang.RuntimeException: Unrecoverable error while evaluating node '//tensorflow/cc:ops/data_flow_ops_gen_cc BuildConfigurationValue.Key[40ef114e63aa727cdd3c39a233ab7f41] false' (requested by nodes '//tensorflow/cc:data_flow_ops_genrule BuildConfigurationValue.Key[40ef114e63aa727cdd3c39a233ab7f41] false')
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:497)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:368)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException
        at com.google.common.base.Preconditions.checkState(Preconditions.java:491)
        at com.google.devtools.build.lib.rules.cpp.LibrariesToLinkCollector.addDynamicInputLinkOptions(LibrariesToLinkCollector.java:290)
        at com.google.devtools.build.lib.rules.cpp.LibrariesToLinkCollector.addLinkerInputs(LibrariesToLinkCollector.java:258)
        at com.google.devtools.build.lib.rules.cpp.LibrariesToLinkCollector.collectLibrariesToLink(LibrariesToLinkCollector.java:203)
        at com.google.devtools.build.lib.rules.cpp.CppLinkActionBuilder.build(CppLinkActionBuilder.java:916)
        at com.google.devtools.build.lib.rules.cpp.CcBinary.init(CcBinary.java:413)
        at com.google.devtools.build.lib.rules.cpp.CcBinary.create(CcBinary.java:179)
        at com.google.devtools.build.lib.rules.cpp.CcBinary.create(CcBinary.java:71)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:320)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:205)
        at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:631)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:770)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:320)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:420)
FAILED: Build did NOT complete successfully (94 packages loaded)

and now how can i to do correctly? thanks for a lot.

**Comment by cielavenir** [comment]
@jesen8 Perhaps your bazel is too new. Try 0.15.0.

**Comment by jesen8** [comment]
oh!, @cielavenir , thanks foy your help, but after i change bazel to 0.15, the new error has occurred,that's below:

D:/tf3/tensorflow-r1.12/tensorflow/cc/BUILD:456:1: Linking of rule '//tensorflow/cc:ops/state_ops_gen_cc' failed (Exit 1120): link.exe failed: error executing command
  cd C:/users/swls/_bazel_swls/5dz6uozl/execroot/org_tensorflow
  SET CUDA_TOOLKIT_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0
    SET CUDNN_INSTALL_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0
    SET INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE;C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared;C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt;
    SET LIB=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB\amd64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\ucrt\x64;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\um\x64;
    SET PATH=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Performance Tools\x64;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Performance Tools;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Windows Kits\10\bin\x86;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\x64\;;C:\Windows\system32
    SET PWD=/proc/self/cwd
    SET PYTHON_BIN_PATH=C:/Python35/python.exe
    SET PYTHON_LIB_PATH=C:/Python35/lib/site-packages
    SET TEMP=C:\Users\swls\AppData\Local\Temp
    SET TF_CUDA_CLANG=0
    SET TF_CUDA_COMPUTE_CAPABILITIES=6.1
    SET TF_CUDA_VERSION=10.0
    SET TF_CUDNN_VERSION=7
    SET TF_NEED_CUDA=1
    SET TF_NEED_OPENCL_SYCL=0
    SET TF_NEED_ROCM=0
    SET TMP=C:\Users\swls\AppData\Local\Temp
  C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/link.exe /nologo /OUT:bazel-out/x64_windows-opt/bin/tensorflow/cc/ops/state_ops_gen_cc /SUBSYSTEM:CONSOLE -Wl,-rpath,../local_config_cuda/cuda/lib64 -Wl,-rpath,../local_config_cuda/cuda/extras/CUPTI/lib64 /MACHINE:X64 @bazel-out/x64_windows-opt/bin/tensorflow/cc/ops/state_ops_gen_cc-2.params
LINK : warning LNK4044: unrecognized option '/Wl,-rpath,../local_config_cuda/cuda/lib64'; ignored
LINK : warning LNK4044: unrecognized option '/Wl,-rpath,../local_config_cuda/cuda/extras/CUPTI/lib64'; ignored
libstate_ops_op_lib.lo(state_ops.o) : error LNK2019: unresolved external symbol "public: virtual __cdecl tensorflow::internal::LogMessageFatal::~LogMessageFatal(void)" (??1LogMessageFatal@internal@tensorflow@@UEAA@XZ) referenced in function "public: void __cdecl tensorflow::internal::LogMessageFatal::`vbase destructor'(void)" (??_DLogMessageFatal@internal@tensorflow@@QEAAXXZ)
libcc_op_gen_main.a(cc_op_gen_main.o) : error LNK2001: unresolved external symbol "public: virtual __cdecl tensorflow::internal::LogMessageFatal::~LogMessageFatal(void)" (??1LogMessageFatal@internal@tensorflow@@UEAA@XZ)
libcc_op_gen_main.a(cc_op_gen.o) : error LNK2001: unresolved external symbol "public: virtual __cdecl tensorflow::internal::LogMessageFatal::~LogMessageFatal(void)" (??1LogMessageFatal@internal@tensorflow@@UEAA@XZ)
libop_gen_lib.a(op_gen_lib.o) : error LNK2001: unresolved external symbol "public: virtual __cdecl tensorflow::internal::LogMessageFatal::~LogMessageFatal(void)" (??1LogMessageFatal@internal@tensorflow@@UEAA@XZ)
.......
libop_gen_lib.a(op_gen_lib.o) : error LNK2019: unresolved external symbol "bool __cdecl tensorflow::str_util::EndsWith(class absl::string_view,class absl::string_view)" (?EndsWith@str_util@tensorflow@@YA_NVstring_view@absl@@0@Z) referenced in function "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl tensorflow::WordWrap(class absl::string_view,class absl::string_view,int)" (?WordWrap@tensorflow@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@Vstring_view@absl@@0H@Z)
libop_gen_lib.a(op_gen_lib.o) : error LNK2019: unresolved external symbol "public: static bool __cdecl google::protobuf::TextFormat::ParseFromString(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class google::protobuf::Message *)" (?ParseFromString@TextFormat@protobuf@google@@SA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVMessage@23@@Z) referenced in function "public: class tensorflow::Status __cdecl tensorflow::ApiDefMap::LoadApiDef(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?LoadApiDef@ApiDefMap@tensorflow@@QEAA?AVStatus@2@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)
libop_gen_lib.a(op_gen_lib.o) : error LNK2019: unresolved external symbol "class tensorflow::Status __cdecl tensorflow::ReadFileToString(class tensorflow::Env *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *)" (?ReadFileToString@tensorflow@@YA?AVStatus@1@PEAVEnv@1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAV45@@Z) referenced in function "public: class tensorflow::Status __cdecl tensorflow::ApiDefMap::LoadFile(class tensorflow::Env *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?LoadFile@ApiDefMap@tensorflow@@QEAA?AVStatus@2@PEAVEnv@2@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)
libop_gen_lib.a(op_gen_lib.o) : error LNK2019: unresolved external symbol "class tensorflow::OpDef_AttrDefDefaultTypeInternal tensorflow::_OpDef_AttrDef_default_instance_" (?_OpDef_AttrDef_default_instance_@tensorflow@@3VOpDef_AttrDefDefaultTypeInternal@1@A) referenced in function "void __cdecl tensorflow::`anonymous namespace'::InitApiDefFromOpDef(class tensorflow::OpDef const &,class tensorflow::ApiDef *)" (?InitApiDefFromOpDef@?A0x86251cb0@tensorflow@@YAXAEBVOpDef@2@PEAVApiDef@2@@Z)
bazel-out/x64_windows-opt/bin/tensorflow/cc/ops/state_ops_gen_cc : fatal error LNK1120: 102 unresolved externals
Target //tensorflow:libtensorflow_cc.so failed to build
INFO: Elapsed time: 2549.567s, Critical Path: 249.94s
INFO: 3296 processes: 3296 local.
FAILED: Build did NOT complete successfully

i'm so bad to build tf for five days all fialed...,i need your help,,,please

**Comment by cielavenir** [comment]
@tensorflow-copybara Sorry but this error has not been addressed yet.

```
ERROR: C:/users/stakemura/tensorflow/tensorflow/cc/BUILD:456:1: Linking of rule '//tensorflow/cc:ops/sparse_ops_gen_cc' failed (Exit 1181): link.exe failed: error executing command
  cd C:/users/stakemura/_bazel_stakemura/kyctgnhj/execroot/org_tensorflow
  SET INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE;C:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\ucrt;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\shared;C:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\winrt;
    SET LIB=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB\amd64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.14393.0\ucrt\x64;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.14393.0\um\x64;
    SET PATH=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Performance Tools\x64;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Performance Tools;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Windows Kits\10\bin\x86;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\x64\;;C:\Windows\system32
    SET PWD=/proc/self/cwd
    SET TEMP=C:\Users\STAKEM~1\AppData\Local\Temp
    SET TMP=C:\Users\STAKEM~1\AppData\Local\Temp
    SET USE_LINKER=1
  C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/link.exe /nologo /OUT:bazel-out/host/bin/tensorflow/cc/ops/sparse_ops_gen_cc.exe tensorflow_framework /SUBSYSTEM:CONSOLE /MACHINE:X64 @bazel-out/host/bin/tensorflow/cc/ops/sparse_ops_gen_cc.exe-2.params
LINK : fatal error LNK1181: cannot open input file 'tensorflow_framework.obj'
Target //tensorflow/cc:tutorials_example_trainer failed to build
```

It looks like I still need to force `"framework_shared_object": "false",`.

**Comment by jesen8** [comment]
@cielavenir you can try r1.11 version,it's no problem

**Comment by stakemura** [comment]
@jesen8 r1.11? The correct one is not r1.11 but r1.13,right? I believe the latest version should work.

**Comment by jesen8** [comment]
@stakemura  yeah,it's r1.13 right, i'm wrong

**Comment by stakemura** [comment]
@jesen8  Noted, thanks a lot!
