### ISSUE TITLE
Windows does not build tflite in anaconda environment : gives ModuleNotFoundError: No module named "tensorflow.contrib.lite.python.tflite_convert"

### ISSUE THREAD

**Issue by tahercoolguy** [tensorflow/tensorflow#23678]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):NO
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):WINDOWS 10
- TensorFlow installed from (source or binary):anaconda
- TensorFlow version (use command below):1.9
- Python version:3.6
- Bazel version (if compiling from source):NO
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:no
- GPU model and memory:no
-Exact Command:toco help

Describe the problem
I am trying to run the codelab tutorial of tensorflow lite. After installing Tensorflow for cpu in anaconda3 environment , when I try to run the command "toco --help", I get the error ModuleNotFoundError: No module named 'tensorflow.contrib.lite.toco.python.tflite_convert'.

source code/logs

Traceback (most recent call last):
  File "c:\users\hp\anaconda3\envs\tensorflow\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\hp\anaconda3\envs\tensorflow\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\hp\Anaconda3\envs\tensorflow\Scripts\toco.exe\__main__.py", line 5, in <module>
ModuleNotFoundError: No module named 'tensorflow.contrib.lite.python.tflite_convert'

**Comment by ymodak** [comment]
It should work with TensorFlow latest build. Can you please use tf-nightly and build again?

**Comment by tensorflowbutler** [comment]
Nagging Assignee @ymodak: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by eXisting** [comment]
Same problem for my experience with mentioned tutorial... Does anyone have any ideas on it? 

- Windows 10
- Anaconda env
- Tensorflow version 1.12
- Python 3.6.7
- Command: toco help

Traceback (most recent call last):
  File "D:\Work\ML\Anaconda\envs\my_env\Scripts\toco-script.py", line 6, in <module>
    from tensorflow.contrib.lite.python.tflite_convert import main
ModuleNotFoundError: No module named 'tensorflow.contrib.lite.python.tflite_convert'

**Comment by Jakejaga5** [comment]
> It should work with TensorFlow latest build. Can you please use tf-nightly and build again?

it just works fine with tf-nightly build of tensorflow....i converted my model successfully!!!!
please use this command to upgrade the existing tensorflow in your environment(conda)..
     pip install --ignore-installed --upgrade tf-nightly

**Comment by Jakejaga5** [comment]
> > It should work with TensorFlow latest build. Can you please use tf-nightly and build again?
> 
> it just works fine with tf-nightly build of tensorflow....i converted my model successfully!!!!
> please use this command to upgrade the existing tensorflow in your environment(conda)..
> pip install --ignore-installed --upgrade tf-nightly (p.s. i was using cpu build of tf-nightly)
> 
> #23678
> #25162
> @jdduke
> @eXisting
> @aselle
> @tahercoolguy
> @ymodak

![screenshots of newly obtained tflite model](https://user-images.githubusercontent.com/16951929/52522946-661b8a00-2cbe-11e9-92a4-df0856bee2ae.png)
![tflite conversion successfully completed](https://user-images.githubusercontent.com/16951929/52522947-661b8a00-2cbe-11e9-9eab-86eee30fb15c.png)

**Comment by BlueAnthony** [comment]
@Jakejaga5
I install TF==1.13.1 and I command "pip install --ignore-installed --upgrade tf-nightly".
But it seems that Tensorflow will conflict by itself.
![2019-04-18 20-31-01 的螢幕擷圖](https://user-images.githubusercontent.com/17959032/56361075-03dc8980-6219-11e9-8046-3b5fa2759587.png)

**Comment by ymodak** [comment]
(tf-lite convert) toco compilation/execution was fixed for Windows in TF 1.11 and continues to be available in later Tf versions as well.
See https://github.com/tensorflow/tensorflow/releases/tag/v1.11.0
