### ISSUE TITLE
ImportError: DLL load failed: The specified procedure could not be found.

### ISSUE THREAD

**Issue by darkmanAmazigh** [tensorflow/tensorflow#23686]
i got this message error
   
       ImportError: DLL load failed: The specified procedure could not be found.

i use this packages with python 3.6.0

$ pip list
Package              Version
-------------------- ------------------
absl-py              0.6.1
APScheduler          3.5.3
astor                0.7.1
attrs                18.2.0
Automat              0.7.0
boto3                1.9.42
botocore             1.12.42
certifi              2018.10.15
cffi                 1.11.5
chardet              3.0.4
Click                7.0
cloudpickle          0.6.1
colorama             0.4.0
colorclass           2.2.0
coloredlogs          10.0
colorhash            1.0.2
ConfigArgParse       0.13.0
constantly           15.1.0
cycler               0.10.0
cymem                2.0.2
cytoolz              0.9.0.1
decorator            4.3.0
dill                 0.2.8.2
docopt               0.6.2
docutils             0.14
en-core-web-md       2.0.0
fakeredis            0.10.3
fbmessenger          5.3.2
Flask                1.0.2
Flask-Cors           3.0.7
Flask-JWT-Simple     0.0.3
future               0.17.1
gast                 0.2.0
gevent               1.3.7
greenlet             0.4.15
grpcio               1.16.0
h5py                 2.8.0
humanfriendly        4.17
hyperlink            18.0.0
idna                 2.7
incremental          17.5.0
itsdangerous         1.1.0
Jinja2               2.10
jmespath             0.9.3
jsonpickle           0.9.6
jsonschema           2.6.0
Keras                2.2.4
Keras-Applications   1.0.6
Keras-Preprocessing  1.0.5
kiwisolver           1.0.1
klein                17.10.0
Markdown             3.0.1
MarkupSafe           1.1.0
matplotlib           2.2.3
mattermostwrapper    2.1
mock                 2.0.0
msgpack              0.5.6
msgpack-numpy        0.4.3.2
murmurhash           1.0.1
networkx             2.2
numpy                1.15.4
packaging            17.1
pathlib              1.0.1
pbr                  5.1.1
pika                 0.11.2
pip                  18.1
plac                 0.9.6
preshed              2.0.1
prompt-toolkit       1.0.14
protobuf             3.6.1
pycparser            2.19
pydot                1.2.4
Pygments             2.2.0
PyHamcrest           1.9.0
PyInquirer           1.0.2
PyJWT                1.6.4
pykwalify            1.6.0
pymongo              3.7.2
pyparsing            2.3.0
pyreadline           2.1
PySocks              1.6.8
python-crfsuite      0.9.6
python-dateutil      2.7.5
python-engineio      2.3.2
python-socketio      2.0.0
python-telegram-bot  10.1.0
pytz                 2018.7
PyYAML               3.13
rasa-core            0.12.0
rasa-core-sdk        0.12.1
rasa-nlu             0.13.7
redis                2.10.6
regex                2018.1.10
requests             2.20.1
requests-toolbelt    0.8.0
rocketchat-API       0.6.22
ruamel.yaml          0.15.77
s3transfer           0.1.13
scikit-learn         0.19.2
scipy                1.1.0
setuptools           39.1.0
simplejson           3.16.0
six                  1.11.0
sklearn-crfsuite     0.3.6
slackclient          1.3.0
spacy                2.0.16
tabulate             0.8.2
tb-nightly           1.13.0a20181112
tensorboard          1.10.0
tensorflow           1.10.0
tensorflow-estimator 1.10.12
termcolor            1.1.0
terminaltables       3.1.0
tf-nightly           1.13.0.dev20181111
thinc                6.12.0
toolz                0.9.0
tqdm                 4.28.1
twilio               6.19.2
Twisted              18.9.0
typing               3.6.6
tzlocal              1.5.1
ujson                1.35
urllib3              1.24.1
wcwidth              0.1.7
webexteamssdk        1.0.3
websocket-client     0.54.0
Werkzeug             0.14.1
wheel                0.32.2
wrapt                1.10.11
zope.interface       4.6.0

complet error stack

      python -m rasa_core.train -d domain.yml -s data/stories.md -o models/current/dialogue --epochs 
      200
     Traceback (most recent call last):
     File "C:\python36\lib\runpy.py", line 193, in _run_module_as_main
        "__main__", mod_spec)
       File "C:\python36\lib\runpy.py", line 85, in _run_code
        exec(code, run_globals)
       File "C:\python36\lib\site-packages\rasa_core\train.py", line 14, in <module>
         from rasa_core import config
       File "C:\python36\lib\site-packages\rasa_core\config.py", line 9, in <module>
         from rasa_core.policies import PolicyEnsemble
       File "C:\python36\lib\site-packages\rasa_core\policies\__init__.py", line 9, in <module>
        from rasa_core.policies.keras_policy import KerasPolicy
       File "C:\python36\lib\site-packages\rasa_core\policies\keras_policy.py", line 11, in <module>
        import tensorflow as tf
        File "C:\python36\lib\site-packages\tensorflow\__init__.py", line 22, in <module>
       from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
        File "C:\python36\lib\site-packages\tensorflow\python\__init__.py", line 52, in <module>
       from tensorflow.core.framework.graph_pb2 import *
       File "C:\python36\lib\site-packages\tensorflow\core\framework\graph_pb2.py", line 6, in <module>
       from google.protobuf import descriptor as _descriptor
        File "C:\python36\lib\site-packages\google\protobuf\descriptor.py", line 47, in <module>
       from google.protobuf.pyext import _message
       ImportError: DLL load failed: The specified procedure could not be found.

**Comment by darkmanAmazigh** [comment]
When i change tensorflow to 1.8.0 and protobuf to 3.5.2, i got an other error essage 

    		usage: train.py default [-h] [-o OUT] -d DOMAIN [--augmentation AUGMENTATION]
								-c [CONFIG [CONFIG ...]] [--dump_stories]
								[--debug_plots] (-s STORIES | --url URL | --core CORE)
								[-v] [-vv] [--quiet]
		train.py default: error: the following arguments are required: -c/--config
