### ISSUE TITLE
scatter_max doesn't work with MirroredStrategy since v1.11.0

### ISSUE THREAD

**Issue by ZhouYuChen** [tensorflow/tensorflow#23687]
**System information**
- Have I written custom code: yes
- OS Platform and Distribution: Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from: binary
- TensorFlow version: tensorflow-gpu v1.12.0-0-ga6d8ffae09, v1.11.0-0-gc19e29306c
- Python version: python 2.7.12
- Bazel version: N/A
- GCC/Compiler version: N/A 
- CUDA/cuDNN version: CUDA 9.0 / cuDNN 7.1.4.18-1+cuda9.0
- GPU model and memory: (GeForce GTX 1080Ti / 11172MiB) x 2

**Describe the current behavior**
scatter_max does not work with MirroredStrategy since v1.11.0.

**Describe the expected behavior**
scatter_max can work with MirroredStrategy in tensorflow-gpu 1.10.0

**Code to reproduce the issue**
```python
from __future__ import absolute_import, division, print_function
import tensorflow as tf
import os, sys

def model_func(features, labels, mode, params):
    tmp_var = tf.Variable(tf.zeros(shape=[2]), trainable=False)
    a=tf.get_variable('a', initializer=tf.ones(shape=[]), trainable=True, aggregation=tf.VariableAggregation.MEAN)
    with tf.control_dependencies([tmp_var.initializer]):
        y = tf.stop_gradient(tf.scatter_max(tmp_var, [0, 1], tf.random_uniform([2])))
        loss = tf.reduce_sum(y * a)
    opt = tf.train.AdamOptimizer().minimize(loss, tf.train.get_global_step())
    return tf.estimator.EstimatorSpec(mode=tf.estimator.ModeKeys.TRAIN, loss=loss, train_op=opt)

def input_fn():
    features =  tf.data.Dataset.from_tensors([[0.]]).repeat()
    labels = tf.data.Dataset.from_tensors(0.).repeat()
    return tf.data.Dataset.zip((features, labels))

def main(argv):
    os.environ['CUDA_VISIBLE_DEVICES'] = "0,1"
    run_config = tf.estimator.RunConfig(
        train_distribute=tf.contrib.distribute.MirroredStrategy(num_gpus=2),
        session_config=tf.ConfigProto(
            allow_soft_placement=True,
            gpu_options=tf.GPUOptions(force_gpu_compatible=True))
    )
    model = tf.estimator.Estimator(model_fn=model_func, config=run_config)

    model.train(input_fn=input_fn, steps=100)

tf.logging.set_verbosity(tf.logging.INFO)
tf.app.run(argv=[sys.argv[0]])
```

**Other info / logs**

error logs from up code running in v1.12.0
```
INFO:tensorflow:Initializing RunConfig with distribution strategies.
INFO:tensorflow:Not using Distribute Coordinator.
WARNING:tensorflow:Using temporary folder as model directory: /tmp/tmpiGysT0
INFO:tensorflow:Using config: {'_save_checkpoints_secs': 600, '_session_config': gpu_options {
  force_gpu_compatible: true
}
allow_soft_placement: true
, '_keep_checkpoint_max': 5, '_task_type': 'worker', '_train_distribute': <tensorflow.contrib.distribute.python.mirrored_strategy.MirroredStrategy object at 0x7f7bc01ee910>, '_is_chief': True, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f7bc01ee890>, '_model_dir': '/tmp/tmpiGysT0', '_protocol': None, '_save_checkpoints_steps': None, '_keep_checkpoint_every_n_hours': 10000, '_service': None, '_num_ps_replicas': 0, '_tf_random_seed': None, '_save_summary_steps': 100, '_device_fn': None, '_experimental_distribute': None, '_num_worker_replicas': 1, '_task_id': 0, '_log_step_count_steps': 100, '_evaluation_master': '', '_eval_distribute': None, '_global_id_in_cluster': 0, '_master': '', '_distribute_coordinator_mode': None}
WARNING:tensorflow:Estimator's model_fn (<function model_func at 0x7f7bc5e48578>) includes params argument, but params are not passed to Estimator.
2018-11-12 06:18:54.074313: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-11-12 06:18:55.364237: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:03:00.0
totalMemory: 10.91GiB freeMemory: 10.75GiB
2018-11-12 06:18:55.511370: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 1 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:04:00.0
totalMemory: 10.91GiB freeMemory: 10.75GiB
2018-11-12 06:18:55.512283: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0, 1
2018-11-12 06:18:55.949305: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-11-12 06:18:55.949341: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 1 
2018-11-12 06:18:55.949347: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N Y 
2018-11-12 06:18:55.949351: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 1:   Y N 
2018-11-12 06:18:55.949765: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/device:GPU:0 with 10400 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:03:00.0, compute capability: 6.1)
2018-11-12 06:18:55.950082: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/device:GPU:1 with 10400 MB memory) -> physical GPU (device: 1, name: GeForce GTX 1080 Ti, pci bus id: 0000:04:00.0, compute capability: 6.1)
INFO:tensorflow:Device is available but not used by distribute strategy: /device:CPU:0
INFO:tensorflow:Device is available but not used by distribute strategy: /device:XLA_GPU:0
INFO:tensorflow:Device is available but not used by distribute strategy: /device:XLA_CPU:0
INFO:tensorflow:Configured nccl all-reduce.
2018-11-12 06:18:55.968070: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0, 1
2018-11-12 06:18:55.968135: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-11-12 06:18:55.968145: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 1 
2018-11-12 06:18:55.968150: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N Y 
2018-11-12 06:18:55.968155: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 1:   Y N 
2018-11-12 06:18:55.968526: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10400 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:03:00.0, compute capability: 6.1)
2018-11-12 06:18:55.968672: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 10400 MB memory) -> physical GPU (device: 1, name: GeForce GTX 1080 Ti, pci bus id: 0000:04:00.0, compute capability: 6.1)
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Error reported to Coordinator: 
Traceback (most recent call last):
  File "/data/tf1.12/local/lib/python2.7/site-packages/tensorflow/python/training/coordinator.py", line 297, in stop_on_exception
    yield
  File "/data/tf1.12/local/lib/python2.7/site-packages/tensorflow/contrib/distribute/python/mirrored_strategy.py", line 795, in run
    self.main_result = self.main_fn(*self.main_args, **self.main_kwargs)
  File "/data/tf1.12/local/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 1195, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/tmp/model_test.py", line 9, in model_func
    y = tf.stop_gradient(tf.scatter_max(tmp_var, [0, 1], tf.random_uniform([2])))
  File "/data/tf1.12/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_state_ops.py", line 719, in scatter_max
    use_locking=use_locking, name=name)
  File "/data/tf1.12/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 510, in _apply_op_helper
    preferred_dtype=default_dtype)
  File "/data/tf1.12/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1146, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/data/tf1.12/local/lib/python2.7/site-packages/tensorflow/contrib/distribute/python/values.py", line 439, in _tensor_conversion_mirrored
    assert not as_ref
AssertionError
Traceback (most recent call last):
  File "/tmp/model_test.py", line 33, in <module>
    tf.app.run(argv=[sys.argv[0]])
  File "/data/tf1.12/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/tmp/model_test.py", line 30, in main
    model.train(input_fn=input_fn, steps=100)
  File "/data/tf1.12/local/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 354, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/data/tf1.12/local/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 1205, in _train_model
    return self._train_model_distributed(input_fn, hooks, saving_listeners)
  File "/data/tf1.12/local/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 1316, in _train_model_distributed
    self.config)
  File "/data/tf1.12/local/lib/python2.7/site-packages/tensorflow/python/training/distribute.py", line 721, in call_for_each_tower
    return self._call_for_each_tower(fn, *args, **kwargs)
  File "/data/tf1.12/local/lib/python2.7/site-packages/tensorflow/contrib/distribute/python/mirrored_strategy.py", line 556, in _call_for_each_tower
    return _call_for_each_tower(self, fn, *args, **kwargs)
  File "/data/tf1.12/local/lib/python2.7/site-packages/tensorflow/contrib/distribute/python/mirrored_strategy.py", line 183, in _call_for_each_tower
    coord.join(threads)
  File "/data/tf1.12/local/lib/python2.7/site-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/data/tf1.12/local/lib/python2.7/site-packages/tensorflow/python/training/coordinator.py", line 297, in stop_on_exception
    yield
  File "/data/tf1.12/local/lib/python2.7/site-packages/tensorflow/contrib/distribute/python/mirrored_strategy.py", line 795, in run
    self.main_result = self.main_fn(*self.main_args, **self.main_kwargs)
  File "/data/tf1.12/local/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 1195, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/tmp/model_test.py", line 9, in model_func
    y = tf.stop_gradient(tf.scatter_max(tmp_var, [0, 1], tf.random_uniform([2])))
  File "/data/tf1.12/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_state_ops.py", line 719, in scatter_max
    use_locking=use_locking, name=name)
  File "/data/tf1.12/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 510, in _apply_op_helper
    preferred_dtype=default_dtype)
  File "/data/tf1.12/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1146, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/data/tf1.12/local/lib/python2.7/site-packages/tensorflow/contrib/distribute/python/values.py", line 439, in _tensor_conversion_mirrored
    assert not as_ref
AssertionError
```

**Comment by hzshuai** [comment]
I've encountered the same problem, it only works in 1.10. Does anyone has better suggestion?

**Comment by junjieChen0608** [comment]
@ymodak 
scatter_add also cannot work with MirroredStrategy.

**Comment by guptapriya** [comment]
Can you please check if this works in 1.13 or latest nightly and let us know if it is still broken?

**Comment by ZhouYuChen** [comment]
@guptapriya, Both 1.13 and nightly still give AssertionError.
1.13
```
Traceback (most recent call last):
  File "test.py", line 32, in <module>
    tf.app.run(argv=[sys.argv[0]])
  File "/home/weride/test/tf1.13/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "test.py", line 29, in main
    model.train(input_fn=input_fn, steps=100)
  File "/home/weride/test/tf1.13/local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 358, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/weride/test/tf1.13/local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1122, in _train_model
    return self._train_model_distributed(input_fn, hooks, saving_listeners)
  File "/home/weride/test/tf1.13/local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1185, in _train_model_distributed
    self._config._train_distribute, input_fn, hooks, saving_listeners)
  File "/home/weride/test/tf1.13/local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1254, in _actual_train_model_distributed
    self.config))
  File "/home/weride/test/tf1.13/local/lib/python2.7/site-packages/tensorflow/python/distribute/distribute_lib.py", line 1199, in call_for_each_replica
    return self._call_for_each_replica(fn, args, kwargs)
  File "/home/weride/test/tf1.13/local/lib/python2.7/site-packages/tensorflow/python/distribute/mirrored_strategy.py", line 641, in _call_for_each_replica
    return _call_for_each_replica(self._container_strategy(), fn, args, kwargs)
  File "/home/weride/test/tf1.13/local/lib/python2.7/site-packages/tensorflow/python/distribute/mirrored_strategy.py", line 189, in _call_for_each_replica
    coord.join(threads)
  File "/home/weride/test/tf1.13/local/lib/python2.7/site-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/home/weride/test/tf1.13/local/lib/python2.7/site-packages/tensorflow/python/training/coordinator.py", line 297, in stop_on_exception
    yield
  File "/home/weride/test/tf1.13/local/lib/python2.7/site-packages/tensorflow/python/distribute/mirrored_strategy.py", line 852, in run
    self.main_result = self.main_fn(*self.main_args, **self.main_kwargs)
  File "/home/weride/test/tf1.13/local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1112, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "test.py", line 9, in model_func
    y = tf.stop_gradient(tf.scatter_max(tmp_var, [0, 1], tf.random_uniform([2])))
  File "/home/weride/test/tf1.13/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_state_ops.py", line 752, in scatter_max
    use_locking=use_locking, name=name)
  File "/home/weride/test/tf1.13/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 511, in _apply_op_helper
    preferred_dtype=default_dtype)
  File "/home/weride/test/tf1.13/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1175, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/weride/test/tf1.13/local/lib/python2.7/site-packages/tensorflow/python/distribute/values.py", line 451, in _tensor_conversion_mirrored
    assert not as_ref
AssertionError
```

nightly
```
Traceback (most recent call last):
  File "test.py", line 32, in <module>
    tf.app.run(argv=[sys.argv[0]])
  File "/home/weride/test/tf-ntl/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/weride/test/tf-ntl/local/lib/python2.7/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/weride/test/tf-ntl/local/lib/python2.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "test.py", line 29, in main
    model.train(input_fn=input_fn, steps=100)
  File "/home/weride/test/tf-ntl/local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 367, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/weride/test/tf-ntl/local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1156, in _train_model
    return self._train_model_distributed(input_fn, hooks, saving_listeners)
  File "/home/weride/test/tf-ntl/local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1219, in _train_model_distributed
    self._config._train_distribute, input_fn, hooks, saving_listeners)
  File "/home/weride/test/tf-ntl/local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1299, in _actual_train_model_distributed
    self.config))
  File "/home/weride/test/tf-ntl/local/lib/python2.7/site-packages/tensorflow/python/distribute/distribute_lib.py", line 1555, in call_for_each_replica
    return self._call_for_each_replica(fn, args, kwargs)
  File "/home/weride/test/tf-ntl/local/lib/python2.7/site-packages/tensorflow/python/distribute/mirrored_strategy.py", line 686, in _call_for_each_replica
    fn, args, kwargs)
  File "/home/weride/test/tf-ntl/local/lib/python2.7/site-packages/tensorflow/python/distribute/mirrored_strategy.py", line 195, in _call_for_each_replica
    coord.join(threads)
  File "/home/weride/test/tf-ntl/local/lib/python2.7/site-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/home/weride/test/tf-ntl/local/lib/python2.7/site-packages/tensorflow/python/training/coordinator.py", line 297, in stop_on_exception
    yield
  File "/home/weride/test/tf-ntl/local/lib/python2.7/site-packages/tensorflow/python/distribute/mirrored_strategy.py", line 904, in run
    self.main_result = self.main_fn(*self.main_args, **self.main_kwargs)
  File "/home/weride/test/tf-ntl/local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1146, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "test.py", line 9, in model_func
    y = tf.stop_gradient(tf.scatter_max(tmp_var, [0, 1], tf.random_uniform([2])))
  File "/home/weride/test/tf-ntl/local/lib/python2.7/site-packages/tensorflow/python/ops/state_ops.py", line 760, in scatter_max
    name=name)
  File "/home/weride/test/tf-ntl/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_state_ops.py", line 907, in scatter_max
    use_locking=use_locking, name=name)
  File "/home/weride/test/tf-ntl/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 527, in _apply_op_helper
    preferred_dtype=default_dtype)
  File "/home/weride/test/tf-ntl/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1224, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/weride/test/tf-ntl/local/lib/python2.7/site-packages/tensorflow/python/distribute/values.py", line 800, in _tensor_conversion_mirrored
    assert not as_ref
AssertionError
```

**Comment by ZhouYuChen** [comment]
@guptapriya, Both 1.13 and nightly still give same errors.

**Comment by guptapriya** [comment]
Thanks for the update. We will look into it.

**Comment by alldefector** [comment]
This still fails (`scatter_add`) in the latest v2.0. It's been more than half a year... Has anyone tried to fix it?

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this issue, as you are using an older version of tensorflow(1.x) which is officially considered as end of life. We recommend that you upgrade to 2.4 or later version and let us know if the issue still persists in newer versions. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, Please open a new issue for any help you need against 2.x, and we will get you the right help.
