### ISSUE TITLE
Can anyone help me with this import error:

### ISSUE THREAD

**Issue by Geomaan** [tensorflow/tensorflow#23685]
### System information
- **custom code from [here](https://www.datacamp.com/community/tutorials/cnn-tensorflow-python)
- **OS Platform and Distribution : winows 10
- **TensorFlow installed from (source or binary)**: coda install tensorflow
- **Python version**: v3.6
- **CUDA/cuDNN version**: v9. 0
- **GPU model and memory**: Quadro M1200 
 TensorFlow version : 'v1.9.0-0-g25c197e023' 1.9.0
......................................................
### Below is my code:

>```
 import numpy as np
> import matplotlib.pyplot as plt
> import tensorflow as tf
> from tensorflow.examples.tutorials.mnist import input_data
> import os
> os.environ["CUDA_VISIBLE_DEVICES"]="0" #for training on gpu
> 
> #import data
> data = input_data.read_data_sets('C:\...\deep learning by python\fashmnist',one_hot=True)
> 

```
............................................................
### Error of above code is: 
( the error is related to this line of source code: 
from tensorflow.examples.tutorials.mnist import input_data)
.........................................................
runfile('C:/.../deep learning by python/fashmnist/fashmnist.py', wdir='C:/.../deep learning by python/fashmnist')
Traceback (most recent call last):

  File "<ipython-input-19-7a288b4aec63>", line 1, in <module>
    runfile('C:/.../deep learning by python/fashmnist/fashmnist.py', wdir='C:/.../deep learning by python/fashmnist')

  File "C:\Users\...\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 668, in runfile
    execfile(filename, namespace)

  File "C:\Users\...\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 108, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/.../deep learning by python/fashmnist/fashmnist.py", line 12, in <module>
    from tensorflow.examples.tutorials.mnist import input_data

  File "C:\Users\...\Anaconda3\lib\site-packages\tensorflow\examples\tutorials\mnist\__init__.py", line 21, in <module>
    from tensorflow.examples.tutorials.mnist import input_data

  File "C:\Users\...\Anaconda3\lib\site-packages\tensorflow\examples\tutorials\mnist\input_data.py", line 30, in <module>
    from tensorflow.contrib.learn.python.learn.datasets.mnist import read_data_sets

  File "C:\Users\...\Anaconda3\lib\site-packages\tensorflow\contrib\__init__.py", line 36, in <module>
    from tensorflow.contrib import data

  File "C:\Users\...\Anaconda3\lib\site-packages\tensorflow\contrib\data\__init__.py", line 71, in <module>
    from tensorflow.contrib.data.python.ops.error_ops import ignore_errors

  File "C:\Users\...\Anaconda3\lib\site-packages\tensorflow\contrib\data\python\ops\error_ops.py", line 20, in <module>
    from tensorflow.contrib.data.python.ops import contrib_op_loader  # pylint: disable=unused-import

  File "C:\Users\...\Anaconda3\lib\site-packages\tensorflow\contrib\data\python\ops\contrib_op_loader.py", line 24, in <module>
    resource_loader.get_path_to_datafile("../../_dataset_ops.so"))

  File "C:\Users\...\Anaconda3\lib\site-packages\tensorflow\contrib\util\loader.py", line 56, in load_op_library
    ret = load_library.load_op_library(path)

  File "C:\Users\...\Anaconda3\lib\site-packages\tensorflow\python\framework\load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)

NotFoundError: C:\Users\...\Anaconda3\lib\site-packages\tensorflow\contrib\data\python\ops\..\..\_dataset_ops.so not found

**Comment by ymodak** [comment]
Can you try using this [thread]9https://stackoverflow.com/questions/50609845/tensorflow-1-8-0-with-python-3-6-4-in-anaconda-show-error-dataset-ops-so-not-fo/50942347) and check if solves the issue for you.? Thanks!

**Comment by ymodak** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
