### ISSUE TITLE
Failure to parse PYTHONPATH to find keras_preprocessing?

### ISSUE THREAD

**Issue by coreyjadams** [tensorflow/tensorflow#23695]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux variant
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version: (master branch, latest commit e84d75dd7429cdcbfa20518cce4a0e886271cfa0)
- Python version: 3.6.5.1
- Installed using virtualenv? pip? conda?: No
- Bazel version (if compiling from source): 0.18.1
- GCC/Compiler version (if compiling from source): gcc 7.3.0
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the problem**

I am trying to build tensorflow from source using mkl-dnn.  The command I use for compilation is 
```
../bazel-0.18.1/output/bazel build --config=mkl -c opt --copt=-g --strip=never --copt='-Wl,rpath=/opt/gcc/7.3.0/snos' --copt=-mavx --copt=-mavx2 --copt=-mfma --copt=-mavx512f --copt=-mavx512pf --copt=-mavx512cd --copt=-mavx512er --copt='-mtune=knl' --copt="-DEIGEN_USE_VML" //tensorflow/tools/pip_package:build_pip_package
```

I get the error eventually:
```
from tensorflow.python.keras.preprocessing.sequence import _remove_long_seq
  File "/gpfs/mira-home/cadams/.cache/bazel/_bazel_cadams/33ea5823a114d12c2a1643d7402e760f/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/python/keras/preprocessing/__init__.py", line 21, in <module>
    import keras_preprocessing
ModuleNotFoundError: No module named 'keras_preprocessing'
```

Following several leads on the internet (such as https://stackoverflow.com/questions/51771039/error-compiling-tensorflow-from-source-no-module-named-keras-applications/51774943#51774943), I installed keras_preprocessing, keras_applications, h5py and put them on PYTHONPATH. This did not work.   

Ultimately, the solution that *did* work was to manually edit the file tensorflow/python/keras/preprocessing/__init__.py to import sys and for the folder containing keras_preprocessing to be added using sys.path.append.

**Comment by coreyjadams** [comment]
Ok, I started from scratch to carefully test this, and my build still failed.  Below I've got a lot of the output so you can see if I configured tensorflow correctly, which I think I did.

1. I downloaded tensorflow fresh, bazel fresh, installed the necessary python packages fresh:
```bash
$ mkdir tf_second_install
$ cd tf_second_install/
$ git clone https://github.com/tensorflow/tensorflow.git
$ wget https://github.com/bazelbuild/bazel/releases/download/0.18.1/bazel-0.18.1-dist.zip
$ export TF_INSTALL=$PWD/tf_install
$ export PYTHONPATH=$TF_INSTALL
$ pip install --target=$TF_INSTALL --upgrade --no-deps keras-applications keras-preprocessing h5py
```

2. I built bazel with the following commands, which succeeded:
```bash
$ cd bazel-0.18.1
$ mv ../bazel-0.18.1-dist.zip ./
$ unzip bazel-0.18.1-dist.zip
$ bash ./compile.sh
$ cd ../
# Much output removed
Build successful! Binary is here: /projects/datascience/cadams/software/tf_second_install/bazel-0.18.1/output/bazel
$ export PATH=/projects/datascience/cadams/software/tf_second_install/bazel-0.18.1/output/:$PATH
```

3. Configuration of tensorflow:
```bash
Configuration of tensorflow:
$ ./configure 
WARNING: Processed legacy workspace file /lus/theta-fs0/projects/datascience/cadams/software/tf_second_install/tensorflow/tools/bazel.rc. This file will not be processed in the next release of Bazel. Please read https://github.com/bazelbuild/bazel/issues/6319 for further information, including how to upgrade.
Extracting Bazel installation...
WARNING: ignoring LD_PRELOAD in environment.
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
You have bazel 0.18.1- (@non-git) installed.
Please specify the location of python. [Default is /opt/python/3.6.5.3/bin/python]: 


Found possible Python library paths:
  /projects/datascience/cadams/software/tf_second_install/tf_install
  /opt/python/3.6.5.3/lib/python3.6/site-packages
Please input the desired Python library path to use.  Default is [/projects/datascience/cadams/software/tf_second_install/tf_install]

Do you wish to build TensorFlow with XLA JIT support? [Y/n]: y
XLA JIT support will be enabled for TensorFlow.

Do you wish to build TensorFlow with OpenCL SYCL support? [y/N]: n
No OpenCL SYCL support will be enabled for TensorFlow.

Do you wish to build TensorFlow with ROCm support? [y/N]: n
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: n
No CUDA support will be enabled for TensorFlow.

Do you wish to download a fresh release of clang? (Experimental) [y/N]: n
Clang will not be downloaded.

Do you wish to build TensorFlow with MPI support? [y/N]: 
No MPI support will be enabled for TensorFlow.

Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native -Wno-sign-compare]: 


Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]: n
Not configuring the WORKSPACE for Android builds.

Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See .bazelrc for more details.
        --config=mkl                 # Build with MKL support.
        --config=monolithic          # Config for mostly static monolithic build.
        --config=gdr                 # Build with GDR support.
        --config=verbs               # Build with libverbs support.
        --config=ngraph              # Build with Intel nGraph support.
        --config=dynamic_kernels        # (Experimental) Build kernels into separate shared objects.
Preconfigured Bazel build configs to DISABLE default on features:
        --config=noaws               # Disable AWS S3 filesystem support.
        --config=nogcp               # Disable GCP support.
        --config=nohdfs              # Disable HDFS support.
        --config=noignite            # Disable Apacha Ignite support.
        --config=nokafka             # Disable Apache Kafka support.
Configuration finished
```

I used the defaults for both the location of python and for python library paths, which I think is recorded correctly in the `.tf_configure.bazelrc` file:
```bash
$ cat .tf_configure.bazelrc
import %workspace%/tools/bazel.rc
build --action_env PYTHON_BIN_PATH="/opt/python/3.6.5.3/bin/python"
build --action_env PYTHON_LIB_PATH="/projects/datascience/cadams/software/tf_second_install/tf_install"
build --python_path="/opt/python/3.6.5.3/bin/python"
build:xla --define with_xla_support=true
build --config=xla
build --action_env TF_NEED_OPENCL_SYCL="0"
build --action_env TF_NEED_ROCM="0"
build --action_env TF_NEED_CUDA="0"
build --action_env TF_DOWNLOAD_CLANG="0"
build:opt --copt=-march=native
build:opt --copt=-Wno-sign-compare
build:opt --host_copt=-march=native
build:opt --define with_default_optimizations=true
build:v2 --define=tf_api_version=2
```

Looking at this, the PYTHON_LIB_PATH appears to be set correctly, and the packages are installed there:
```bash 
$ ls /projects/datascience/cadams/software/tf_second_install/tf_install
h5py                  Keras_Applications-1.0.6.dist-info
h5py-2.8.0.dist-info  keras_preprocessing
keras_applications    Keras_Preprocessing-1.0.5.dist-info
```

4. Still, the build fails at the same spot when it can not import keras_preprocessing:
```
ERROR: /lus/theta-fs0/projects/datascience/cadams/software/tf_second_install/tensorflow/tensorflow/BUILD:562:1: Executing genrule //tensorflow:tf_python_api_gen_v1 failed (Exit 1)
Traceback (most recent call last):
  File "/gpfs/mira-home/cadams/.cache/bazel/_bazel_cadams/5d2ab57ebd6673dd9517877558fa4b10/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/python/tools/api/generator/create_python_api.py", line 27, in <module>
    from tensorflow.python.tools.api.generator import doc_srcs
  File "/gpfs/mira-home/cadams/.cache/bazel/_bazel_cadams/5d2ab57ebd6673dd9517877558fa4b10/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 81, in <module>
    from tensorflow.python import keras
  File "/gpfs/mira-home/cadams/.cache/bazel/_bazel_cadams/5d2ab57ebd6673dd9517877558fa4b10/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/python/keras/__init__.py", line 29, in <module>
    from tensorflow.python.keras import datasets
  File "/gpfs/mira-home/cadams/.cache/bazel/_bazel_cadams/5d2ab57ebd6673dd9517877558fa4b10/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/python/keras/datasets/__init__.py", line 25, in <module>
    from tensorflow.python.keras.datasets import imdb
  File "/gpfs/mira-home/cadams/.cache/bazel/_bazel_cadams/5d2ab57ebd6673dd9517877558fa4b10/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/python/keras/datasets/imdb.py", line 25, in <module>
    from tensorflow.python.keras.preprocessing.sequence import _remove_long_seq
  File "/gpfs/mira-home/cadams/.cache/bazel/_bazel_cadams/5d2ab57ebd6673dd9517877558fa4b10/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/python/keras/preprocessing/__init__.py", line 21, in <module>
    import keras_preprocessing
ModuleNotFoundError: No module named 'keras_preprocessing'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1770.461s, Critical Path: 236.77s
INFO: 11483 processes: 11483 local.
FAILED: Build did NOT complete successfully
```

Do you spot something I am not doing right?  I can only get this section of the build to succeed by manually editing the __init__ file to add to the sys.path variable, as mentioned.

**Comment by wdirons** [comment]
Thank you @coreyjadams , I can confirm this a problem. I see now the same issue is being discussed in: https://github.com/tensorflow/tensorflow/issues/22395

I'm trying a few things on my end and might end up submitting a PR if I can fix it. [It's odd that configure parses PYTHONPATH, but then fails to pass PYTHONPATH into the bazel environment.]

**Comment by coreyjadams** [comment]
Great, I'm glad it's reproducible!  When/If you have a PR candidate, I can attempt a build on our system to see if it works for me too, if you like.

**Comment by wdirons** [comment]
Hi, @coreyjadams can you please try cherry-picking this fix: https://github.com/wdirons/tensorflow/commit/01c28a94e63edc8aa301ee377ca026107762858b

or using the branch from my fork.

**Comment by coreyjadams** [comment]
Hi @wdirons , this fix does let the build complete without problems, and none of the interventions I mentioned above were required.

Are you planning to submit this as a pull request?

**Comment by wdirons** [comment]
yes, thanks for verifying. I was going to ask the owner of the other defect (#22395), if he agreed with how I fixed it then submit a PR.
