### ISSUE TITLE
import_meta_graph fails: NcclAllReduce

### ISSUE THREAD

**Issue by sharvil** [tensorflow/tensorflow#23703]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04.5
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): v1.12.0-rc2-3-ga6d8ffa 1.12.0
- Python version: 3.5.2
- Bazel version (if compiling from source): 0.16.1
- GCC/Compiler version (if compiling from source): gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10)
- CUDA/cuDNN version: CUDA 9.1, cuDNN 7.1.3
- GPU model and memory: dual 1080Ti (11178MiB)

I trained a model with `MirroredStrategy` across two GPUs on a single machine using the `Estimator` API (custom `Estimator`). I'm unable to load the meta graph with the error:

```
$ python test.py
2018-11-12 22:16:59.061730: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties:
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:03:00.0
totalMemory: 10.92GiB freeMemory: 10.76GiB
2018-11-12 22:16:59.271191: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 1 with properties:
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:04:00.0
totalMemory: 10.91GiB freeMemory: 10.76GiB
2018-11-12 22:16:59.283574: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0, 1
2018-11-12 22:17:01.209999: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-11-12 22:17:01.210032: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 1
2018-11-12 22:17:01.210038: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N Y
2018-11-12 22:17:01.210042: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 1:   Y N
2018-11-12 22:17:01.210423: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10405 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:03:00.0, compute capability: 6.1)
2018-11-12 22:17:01.210742: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 10402 MB memory) -> physical GPU (device: 1, name: GeForce GTX 1080 Ti, pci bus id: 0000:04:00.0, compute capability: 6.1)
Traceback (most recent call last):
  File "test.py", line 13, in <module>
    tf.app.run()
  File "/home/sharvil/.virtualenv/tensorflow/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "test.py", line 6, in main
    saver = tf.train.import_meta_graph('trained_models/student/3/model.ckpt-59112.meta')
  File "/home/sharvil/.virtualenv/tensorflow/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1674, in import_meta_graph
    meta_graph_or_file, clear_devices, import_scope, **kwargs)[0]
  File "/home/sharvil/.virtualenv/tensorflow/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1696, in _import_meta_graph_with_return_elements
    **kwargs))
  File "/home/sharvil/.virtualenv/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/meta_graph.py", line 806, in import_scoped_meta_graph_with_return_elements
    return_elements=return_elements)
  File "/home/sharvil/.virtualenv/tensorflow/lib/python3.5/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/home/sharvil/.virtualenv/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/importer.py", line 391, in import_graph_def
    _RemoveDefaultAttrs(op_dict, producer_op_list, graph_def)
  File "/home/sharvil/.virtualenv/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/importer.py", line 158, in _RemoveDefaultAttrs
    op_def = op_dict[node.op]
KeyError: 'NcclAllReduce'
```

I'm using the following code to load the meta graph and checkpoint:

```
import tensorflow as tf


def main(args):
  with tf.Session() as sess:
    saver = tf.train.import_meta_graph('trained_models/student/3/model.ckpt-59112.meta')
    saver.restore('trained_models/student/3/model.ckpt-59112')

if __name__ == '__main__':
  tf.app.run()
```

**Comment by ymodak** [comment]
Apologies for the delay in responding. Is this still an issue?

**Comment by sharvil** [comment]
Yes, this is still an issue for me. Thanks for taking a look.

**Comment by adoudou2008** [comment]
I have the same problem. Have you solved this problem?

**Comment by aijunbai** [comment]
Same problem here.

**Comment by yuefengz** [comment]
Looks like the nccl op is not loaded when the meta_graph is loaded. @azaks2, do you have any clue?

**Comment by guptapriya** [comment]
@azaks2 should this issue happen if they built from source after nccl was moved to core?

**Comment by azaks2** [comment]
No the issue should not be happening in head.

**Comment by devkicks** [comment]
I was having the same issue in the main branch. @azaks2 solution worked simple need to import nccl_ops and call to **_maybe_load_nccl_ops_so()** solved it

**Comment by amirmgh1375** [comment]
you just need to add `*.so` compiled file generated by model implementation.
as follows add this line before session and import meta graph.
`tf.load_op_library('<compiled_filename>.so')`
this function add a new op in tensorflow runtime.
for example. i compiled a model that contains a `RoiPooling` layer and generated `roi_pooling.so` file. so that i added this line to my code
`tf.load_op_library('op/roi_pooling.so')`

and finally it works : )
