### ISSUE TITLE
Can't build TensorRT 5.0.10 within Tensorflow 1.12, Tensorflow still search for libnvinfer.so.4 not 5

### ISSUE THREAD

**Issue by oscarriddle** [tensorflow/tensorflow#23708]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS 7
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): source 
- TensorFlow version: r1.12
- Python version: 2.7
- Installed using virtualenv? pip? conda?: No
- Bazel version (if compiling from source): 0.15.0
- GCC/Compiler version (if compiling from source): 4.9.3
- CUDA/cuDNN version: 9.0/7.0.5
- GPU model and memory: TitanXP 12GB

**Describe the problem**
Since the TensorRT 5 is released, but official latest tensorflow is unable to import TRT5, because it still searches TRT4 (libnvinfer.so.4), I manually compiled the tensorflow r1.12 with gpu and with TRT5.0.

After setting the TRT5.0.10 location in ./configure, the compilation is successfully done. Then I generated the pip wheel file and pip installed it.

Then I tried to import tensorflow and from tensorflow.contrib import tensorrt, still got below error:
```
$ python
Python 2.7.13 (default, Jan  6 2017, 21:12:18) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
/home/web_server/dlpy72/dlpy.tensor1.12/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
>>> tf.__version__
'1.12.0'
>>> from tensorflow.contrib import tensorrt
**** Failed to initialize TensorRT. This is either because the TensorRT installation path is not in LD_LIBRARY_PATH, or because you do not have it installed. If not installed, please go to https://developer.nvidia.com/tensorrt to download and install TensorRT ****
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/web_server/dlpy72/dlpy.tensor1.12/lib/python2.7/site-packages/tensorflow/contrib/tensorrt/__init__.py", line 34, in <module>
    raise e
tensorflow.python.framework.errors_impl.NotFoundError: libnvinfer.so.4: cannot open shared object file: No such file or directory
>>> 

```
Hence the TensorRT 5 is not supported even if compiling it with tensorflow source.

Any idea will be welcome.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Configuration log:
```
$ ./configure 
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
You have bazel 0.15.0 installed.
Do you wish to build TensorFlow with Apache Ignite support? [Y/n]: n
No Apache Ignite support will be enabled for TensorFlow.

Do you wish to build TensorFlow with XLA JIT support? [Y/n]: n
No XLA JIT support will be enabled for TensorFlow.

Do you wish to build TensorFlow with OpenCL SYCL support? [y/N]: n
No OpenCL SYCL support will be enabled for TensorFlow.

Do you wish to build TensorFlow with ROCm support? [y/N]: n
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: y
CUDA support will be enabled for TensorFlow.

Please specify the CUDA SDK version you want to use. [Leave empty to default to CUDA 9.0]: 


Please specify the location where CUDA 9.0 toolkit is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: /home/web_server/xiaolun/cuda-9.0


Please specify the cuDNN version you want to use. [Leave empty to default to cuDNN 7]: 


Do you wish to build TensorFlow with TensorRT support? [y/N]: y
TensorRT support will be enabled for TensorFlow.

Please specify the location where TensorRT is installed. [Default is /usr/lib/x86_64-linux-gnu]:/home/web_server/xiaolun/TensorRT-5.0.0.10


Please specify the NCCL version you want to use. If NCCL 2.2 is not installed, then you can use version 1.3 that can be fetched automatically but it may have worse performance with multiple GPUs. [Default is 2.2]: 2.3


Assuming NCCL header path is /media/disk1/fordata/web_server/project/xiaolun/nccl_2.3.7/lib/../include/nccl.h
Please specify a list of comma-separated Cuda compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
Please note that each additional compute capability significantly increases your build time and binary size. [Default is: 6.1]: 


Do you want to use clang as CUDA compiler? [y/N]: n
nvcc will be used as CUDA compiler.

Please specify which gcc should be used by nvcc as the host compiler. [Default is /home/web_server/gcc-4.9.3/bin/gcc]: 


Do you wish to build TensorFlow with MPI support? [y/N]: n
No MPI support will be enabled for TensorFlow.

Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native]: 


Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]: n
Not configuring the WORKSPACE for Android builds.

Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See tools/bazel.rc for more details.
	--config=mkl         	# Build with MKL support.
	--config=monolithic  	# Config for mostly static monolithic build.
	--config=gdr         	# Build with GDR support.
	--config=verbs       	# Build with libverbs support.
	--config=ngraph      	# Build with Intel nGraph support.
Configuration finished

```
Compilation commands:
bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
./bazel-bin/tensorflow/tools/pip_package/build_pip_package ./mnt

**Comment by Jie-Fang** [comment]
Maybe you forget to set TensorRT-5 lib path to the $LD_LIBRARY_PATH.

**Comment by oscarriddle** [comment]
@Jie-Fang I have set the $LD_LIBRARY_PATH already. Did you succeed in compiling it? I think we shall wait for the response from samikama.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @samikama: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by oscarriddle** [comment]
@aaroey 
As below:
```
build --action_env PYTHON_BIN_PATH="/home/web_server/dlpy72/dlpy.tensor1.12/bin/python"
build --action_env PYTHON_LIB_PATH="/home/web_server/dlpy72/dlpy.tensor1.12/lib64/python2.7/site-packages"
build --python_path="/home/web_server/dlpy72/dlpy.tensor1.12/bin/python"
build:ignite --define with_ignite_support=true
build:xla --define with_xla_support=true
build --action_env TF_NEED_OPENCL_SYCL="0"
build --action_env TF_NEED_ROCM="0"
build --action_env TF_NEED_CUDA="1"
build --action_env CUDA_TOOLKIT_PATH="/home/web_server/xiaolun/cuda-9.0"
build --action_env TF_CUDA_VERSION="9.0"
build --action_env CUDNN_INSTALL_PATH="/media/disk1/fordata/web_server/project/xiaolun/cuda-9.0"
build --action_env TF_CUDNN_VERSION="7"
build --action_env TENSORRT_INSTALL_PATH="/media/disk1/fordata/web_server/project/xiaolun/TensorRT-5.0.0.10/targets/x86_64-linux-gnu/lib"
build --action_env TF_TENSORRT_VERSION="5.0.0"
build --action_env NCCL_INSTALL_PATH="/media/disk1/fordata/web_server/project/xiaolun/nccl_2.3.7/lib"
build --action_env NCCL_HDR_PATH="/media/disk1/fordata/web_server/project/xiaolun/nccl_2.3.7/lib/../include"
build --action_env TF_NCCL_VERSION="2"
build --action_env TF_CUDA_COMPUTE_CAPABILITIES="6.1"
build --action_env LD_LIBRARY_PATH="/home/web_server/gcc-4.9.3/lib64:/home/web_server/xiaolun/cuda-9.0/lib64/:/usr/lib/:/home/web_server/xiaolun/nccl_2.3.7/lib/:/home/web_server/xiaolun/cudnn-7.0.5/lib6\
4:/data/web_server/lib:/home/web_server/xiaolun/caffe/build/lib/:/home/web_server/xiaolun/lib_so/:/home/web_server/xiaolun/TensorRT-5.0.0.10/lib:/home/web_server/xiaolun/cuda-9.2/extras/CUPTI/lib64"
build --action_env TF_CUDA_CLANG="0"
build --action_env GCC_HOST_COMPILER_PATH="/home/web_server/gcc-4.9.3/bin/gcc"
build --config=cuda
test --config=cuda
build:opt --copt=-march=native
build:opt --host_copt=-march=native
build:opt --define with_default_optimizations=true
build:v2 --define=tf_api_version=2
```

**Comment by zcc720** [comment]
I have same problem,when import tensorflow.contrib.tensorrt(tensorflow1.9.0+Tensort5.0)
Traceback (most recent call last):
  File "classity.py", line 6, in <module>
    import tensorflow.contrib.tensorrt as trt
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/tensorrt/__init__.py", line 34, in <module>
    raise e
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/tensorrt/__init__.py", line 25, in <module>
    from tensorflow.contrib.tensorrt.python import *
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/tensorrt/python/__init__.py", line 22, in <module>
    from tensorflow.contrib.tensorrt.python.ops import trt_engine_op
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/tensorrt/python/ops/trt_engine_op.py", line 32, in <module>
    resource_loader.get_path_to_datafile("_trt_engine_op.so"))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/util/loader.py", line 56, in load_op_library
    ret = load_library.load_op_library(path)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: libnvinfer.so.4: cannot open shared object file: No such file or directory

**Comment by samikama** [comment]
@zcc720 You need to build tensorflow with TRT5 if you want to use it. You can't use pip installed tensorflow-gpu with trt5. Moreover, I would suggest you to upgrade a recent version of tensorflow since there are known bugs in TF1.9 that are fixed in recent releases.

@oscarriddle Could you please make sure that TRT5 you configured is for cuda9 and compatible cudnn7 and not cuda10. Selected TRT version **must** be compatible with configured cudnn and cuda. Also please make sure that there is no other TF installation in the system. You can test this by installing generated pip package in a virtualenv.

**Comment by oscarriddle** [comment]
@samikama I used the version TRT5.0.0.10 with CUDA9.0 and cuDNN7.0.5 compatible. The official site seems providing new version 5.0.2.6 now, I will try it soon. For the second one, I will uninstall the previously pip-installed-tf before installing the source built whl file.

**Comment by samikama** [comment]
@oscarriddle pip installed TF will always look for trt4 until default becomes trt5. You can try printing TF systeminfo to see whether the imported package is your build old an earlier build installed in the system. I have been using trt5 since quite some time now and never had this issue so I can't reproduce what you observe. If you still have the same problems I would suggest running bazel tftrt tests or starting from a clean system.

**Comment by yjiangling** [comment]
I installed TensorRT 5.1.5 and TensorFlow 1.12.0, when I use pip install the TensorRT module in tensorflow, It still can not work. Given the following error:

import tensorflow.contrib.tensorrt as trt
**** Failed to initialize TensorRT. This is either because the TensorRT installation path is not in LD_LIBRARY_PATH, or because you do not have it installed. If not installed, please go to https://developer.nvidia.com/tensorrt to download and install TensorRT ****
Traceback (most recent call last):
File "", line 1, in
File "/media/huaxin/tcl1/asr/yujiangling/lib/python3.6/site-packages/tensorflow/contrib/tensorrt/init.py", line 34, in
raise e
File "/media/huaxin/tcl1/asr/yujiangling/lib/python3.6/site-packages/tensorflow/contrib/tensorrt/init.py", line 25, in
from tensorflow.contrib.tensorrt.python import *
File "/media/huaxin/tcl1/asr/yujiangling/lib/python3.6/site-packages/tensorflow/contrib/tensorrt/python/init.py", line 22, in
from tensorflow.contrib.tensorrt.python.ops import trt_engine_op
File "/media/huaxin/tcl1/asr/yujiangling/lib/python3.6/site-packages/tensorflow/contrib/tensorrt/python/ops/trt_engine_op.py", line 32, in
resource_loader.get_path_to_datafile("_trt_engine_op.so"))
File "/media/huaxin/tcl1/asr/yujiangling/lib/python3.6/site-packages/tensorflow/contrib/util/loader.py", line 56, in load_op_library
ret = load_library.load_op_library(path)
File "/media/huaxin/tcl1/asr/yujiangling/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 60, in load_op_library
lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: libnvinfer.so.4: cannot open shared object file: No such file or directory

Finally, I have to use bazel to build the tensorflow source code and re-install it to solve this problem. But When I use TensorFlow 1.14.0 and TensorRT6.0, It works OK, doesn't need to build tensorflow source code. It's very strange!
