### ISSUE TITLE
Keras with Tensorflow backend stooped working ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found

### ISSUE THREAD

**Issue by sbhakat** [tensorflow/tensorflow#23712]
I am running Keras with Tensorflow backend and encountering a problem like 

```
/home/sbhakat/miniconda2/envs/py36/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Traceback (most recent call last):
  File "script.py", line 1, in <module>
    from keras.callbacks import TensorBoard, ModelCheckpoint
  File "/home/sbhakat/miniconda2/envs/py36/lib/python3.6/site-packages/keras/__init__.py", line 3, in <module>
    from . import utils
  File "/home/sbhakat/miniconda2/envs/py36/lib/python3.6/site-packages/keras/utils/__init__.py", line 27, in <module>
    from .multi_gpu_utils import multi_gpu_model
  File "/home/sbhakat/miniconda2/envs/py36/lib/python3.6/site-packages/keras/utils/multi_gpu_utils.py", line 7, in <module>
    from ..layers.merge import concatenate
  File "/home/sbhakat/miniconda2/envs/py36/lib/python3.6/site-packages/keras/layers/__init__.py", line 4, in <module>
    from ..engine.base_layer import Layer
  File "/home/sbhakat/miniconda2/envs/py36/lib/python3.6/site-packages/keras/engine/__init__.py", line 8, in <module>
    from .training import Model
  File "/home/sbhakat/miniconda2/envs/py36/lib/python3.6/site-packages/keras/engine/training.py", line 21, in <module>
    from . import training_arrays
  File "/home/sbhakat/miniconda2/envs/py36/lib/python3.6/site-packages/keras/engine/training_arrays.py", line 8, in <module>
    from scipy.sparse import issparse
  File "/home/sbhakat/miniconda2/envs/py36/lib/python3.6/site-packages/scipy/sparse/__init__.py", line 229, in <module>
    from .csr import *
  File "/home/sbhakat/miniconda2/envs/py36/lib/python3.6/site-packages/scipy/sparse/csr.py", line 15, in <module>
    from ._sparsetools import csr_tocsc, csr_tobsr, csr_count_blocks, \
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /home/sbhakat/miniconda2/envs/py36/lib/python3.6/site-packages/scipy/sparse/_sparsetools.cpython-36m-x86_64-linux-gnu.so)
```

I think this problem was quite similar to https://github.com/tensorflow/tensorflow/issues/5017 hence I tried the proposed method which is following

`cp /usr/lib/x86_64-linux-gnu/libstdc++.so.6 /home/sbhakat/miniconda2/envs/py36/lib/`

But now it seems the issue is similar to https://github.com/ContinuumIO/anaconda-issues/issues/5191

Any quick help to fix this. Sorry I am new with this.

**Comment by ymodak** [comment]
It looks like you haven't used a template to create this issue. Please resubmit your issue using a template from [here](https://github.com/tensorflow/tensorflow/issues/new/choose) if it still exists. We ask users to use the template because it reduces overall time to resolve a new issue by avoiding extra communication to get to the root of the issue. We will close this issue in lieu of the new one you will create from the template. Thank you for your cooperation.
