### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError: Expected begin[1] in [0, 8], but got -2

### ISSUE THREAD

**Issue by muneeb699** [tensorflow/tensorflow#23720]
**Error**
```
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1139, in _do_call
    return fn(*args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1121, in _run_fn
    status, run_metadata)
  File "C:\ProgramData\Anaconda3\lib\contextlib.py", line 88, in __exit__
    next(self.gen)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Expected begin[1] in [0, 8], but got -2
	 [[Node: Slice = Slice[Index=DT_INT32, T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](up_sampling2d/ResizeNearestNeighbor, Slice/begin, Slice/size)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:/VisionLearning/Segmentation/train.py", line 71, in <module>
    train(epochs,num_steps)
  File "E:/VisionLearning/Segmentation/train.py", line 47, in train
    sess.run(optimizer, feed_dict)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 789, in run
    run_metadata_ptr)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Expected begin[1] in [0, 8], but got -2
	 [[Node: Slice = Slice[Index=DT_INT32, T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](up_sampling2d/ResizeNearestNeighbor, Slice/begin, Slice/size)]]

Caused by op 'Slice', defined at:
  File "E:/VisionLearning/Segmentation/train.py", line 71, in <module>
    train(epochs,num_steps)
  File "E:/VisionLearning/Segmentation/train.py", line 28, in train
    logits = build_model(x, 0.5, 128)
  File "E:\VisionLearning\Segmentation\Model.py", line 153, in build_model
    up1_0 = crop_and_concat(layers.UpSampling2D(size=(2,2))(conv5), conv4_1)
  File "E:\VisionLearning\Segmentation\Model.py", line 22, in crop_and_concat
    x1_crop = tf.slice(x1, offsets, size)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\array_ops.py", line 547, in slice
    return gen_array_ops._slice(input_, begin, size, name=name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 2896, in _slice
    name=name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Expected begin[1] in [0, 8], but got -2
	 [[Node: Slice = Slice[Index=DT_INT32, T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](up_sampling2d/ResizeNearestNeighbor, Slice/begin, Slice/size)]]


Process finished with exit code 1
```

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):Yes

```
def crop_and_concat(x1,x2):

    x1_shape = tf.shape(x1)
    x2_shape = tf.shape(x2)

    x2_shape1 = x2.get_shape()
    x1_shape1 = x1.get_shape()

    # offsets for the top left corner of the crop
    offsets = [0, (x1_shape[1] - x2_shape[1]) // 2, (x1_shape[2] - x2_shape[2]) // 2, 0]
    print("offsets",offsets)
    print("x1",x1)

    #offsets = [0, (int(x1_shape1[1]) - int(x2_shape1[1])) // 2, (int(x1_shape1[2]) - int(x2_shape1[2])) // 2, 0]
    size = [-1, int(x2_shape1[1]), int(x2_shape1[2]), -1]
    print("size",size)
    #size = [-1, x2_shape[1], x2_shape[2], -1]
    x1_crop = tf.slice(x1, offsets, size)
    print("x1 crop",x1_crop)
    return tf.concat([x1_crop, x2], 3)

def build_model(x, keep_prob, batch_size):
    print(x.get_shape())
    conv1 = tf.layers.conv2d(
        inputs= x,
        filters=32,
        kernel_size=(3,3),
        padding='same',
        activation = tf.nn.relu
    )#256
    print("conv1", conv1)
    conv1_2 = tf.layers.conv2d(
        inputs=conv1,
        filters=32,
        kernel_size=(3,3),
        padding='same',
        activation=tf.nn.relu
    )#252
    print("conv1", conv1_2)
    pool1 = tf.layers.max_pooling2d(
        inputs=conv1_2,
        pool_size=(2,2),
        padding='same',
        strides = 2
    )#126
    print("pool1", pool1)
    conv2 = tf.layers.conv2d(
        inputs=pool1,
        filters=64,
        kernel_size=(3, 3),
        padding='same',
        activation=tf.nn.relu
    )#124
    print("conv2", conv2.get_shape())
    conv2 = tf.layers.conv2d(
        inputs=conv2,
        filters=64,
        kernel_size=3,
        activation=tf.nn.relu
    )#122
    print("conv2", conv2.get_shape())
    pool2 = tf.layers.max_pooling2d(
        inputs=conv2,
        pool_size=2,
        strides=2
    )#61
    print("pool2", pool2.get_shape())
    conv3 = tf.layers.conv2d(
        inputs=pool2,
        filters=128,
        kernel_size=(3, 3),
        padding='same',
        activation=tf.nn.relu
    )#59
    print("conv3", conv3.get_shape())
    conv3 = tf.layers.conv2d(
        inputs=conv3,
        filters=128,
        kernel_size=3,
        activation=tf.nn.relu
    )#57
    print("conv3", conv3.get_shape())
    pool3 = tf.layers.max_pooling2d(
        inputs=conv3,
        pool_size=2,
        strides=2
    )
    print("pool3", pool3.get_shape())
    conv4 = tf.layers.conv2d(
        inputs=pool3,
        filters=256,
        kernel_size=(3, 3),
        padding='same',
        activation=tf.nn.relu
    )
    print("conv4", conv4.get_shape())
    conv4 = tf.layers.conv2d(
        inputs=conv4,
        filters=256,
        kernel_size=3,
        activation=tf.nn.relu
    )
    print("conv4", conv4.get_shape())
    pool4 = tf.layers.max_pooling2d(
        inputs=conv4,
        pool_size=(2,2),
        strides=2
    )
    print("pool4", pool4.get_shape())

    conv4_1 = tf.layers.conv2d(
        inputs=pool4,
        filters=512,
        kernel_size=(3, 3),
        padding='same',
        activation=tf.nn.relu
    )
    print("conv41", conv4_1.get_shape())
    conv4_1 = tf.layers.conv2d(
        inputs=conv4_1,
        filters=512,
        kernel_size=3,
        activation=tf.nn.relu
    )
    print("conv41", conv4_1.get_shape())
    pool4_1 = tf.layers.max_pooling2d(
        inputs=conv4_1,
        pool_size=(2, 2),
        strides=2
    )
    print("pool41", pool4_1.get_shape())
    conv5 = tf.layers.conv2d(
        inputs=pool4_1,
        filters=1024,
        kernel_size=(3, 3),
        padding='same',
        activation=tf.nn.relu
    )
    print("conv5", conv5.get_shape())
    conv5 = tf.layers.conv2d(
        inputs=conv5,
        filters=1024,
        kernel_size=(3,3),
        activation=tf.nn.relu
    )
    print("conv5", conv5.get_shape())

    #up1_0 = layers.concatenate([layers.UpSampling2D(size=(2,2))(conv5),conv4_1])
    up1_0 = crop_and_concat(layers.UpSampling2D(size=(2,2))(conv5), conv4_1)

    print("up10", up1_0.get_shape())
    conv6 = tf.layers.conv2d(
        inputs=up1_0,
        filters=512,
        kernel_size=(3, 3),
        padding='same',
        activation=tf.nn.relu
    )
    print("conv6", conv6.get_shape())
    conv6 = tf.layers.conv2d(
        inputs=conv6,
        filters=512,
        kernel_size=(3, 3),
        padding='same',
        activation=tf.nn.relu
    )
    print("conv6", conv6.get_shape())
    #up1 = layers.concatenate([layers.UpSampling2D(size=(2, 2))(conv6), conv4])
    up1 = crop_and_concat(layers.UpSampling2D(size=(2,2))(conv6), conv4)
    print("up1", up1.get_shape())
    conv6_1 = tf.layers.conv2d(
        inputs=up1,
        filters=256,
        kernel_size=(3, 3),
        padding='same',
        activation=tf.nn.relu
    )
    print("conv61", conv6_1.get_shape())
    conv6_1 = tf.layers.conv2d(
        inputs=conv6_1,
        filters=256,
        kernel_size=(3, 3),
        padding='same',
        activation=tf.nn.relu
    )
    print("conv61", conv6_1.get_shape())
    #up2  = layers.concatenate([layers.UpSampling2D(size=2)(conv6_1),conv3])
    up2 = crop_and_concat(layers.UpSampling2D(size=(2,2))(conv6_1), conv3)
    print("up2", up2.get_shape())
    conv7 = tf.layers.conv2d(
        inputs=up2,
        filters=128,
        kernel_size=(3, 3),
        padding='same',
        activation=tf.nn.relu
    )
    print("conv7", conv7.get_shape())
    conv7 = tf.layers.conv2d(
        inputs=conv7,
        filters=128,
        kernel_size=(3, 3),
        padding='same',
        activation=tf.nn.relu
    )
    print("conv7", conv7.get_shape())
    #up3 =  layers.concatenate([layers.UpSampling2D(size=2)(conv7),conv2])
    up3 = crop_and_concat(layers.UpSampling2D(size=(2,2))(conv7), conv2)
    print("up3", up3.get_shape())
    conv8 = tf.layers.conv2d(
        inputs=up3,
        filters=64,
        kernel_size=(3, 3),
        padding='same',
        activation=tf.nn.relu
    )
    print("conv8", conv8.get_shape())
    conv8 = tf.layers.conv2d(
        inputs=conv8,
        filters=64,
        kernel_size=(3, 3),
        padding='same',
        activation=tf.nn.relu
    )
    print("conv8",conv8.get_shape())
    #up4 = layers.concatenate([layers.UpSampling2D(size=2)(conv8), conv1])
    up4 = crop_and_concat(layers.UpSampling2D(size=(4,4))(conv8), conv1)
    print("up4",up4.get_shape())
    conv9 = tf.layers.conv2d(
        inputs=up4,
        filters=32,
        kernel_size=(3, 3),
        padding='same',
        activation=tf.nn.relu
    )
    print("conv91",conv9.get_shape())
    conv9 = tf.layers.conv2d(
        inputs=conv9,
        filters=32,
        kernel_size=(3, 3),
        padding='same',
        activation=tf.nn.relu
    )
    print("conv9",conv9.get_shape())
    conv10 = tf.layers.conv2d(
        inputs=conv9,
        filters=1,
        kernel_size=1,
        activation= tf.nn.sigmoid
    )
    print("conv10",conv10.get_shape())
    return conv10
```

```
def train(epochs, num_steps):
    dir_images = "Dataset/JPEGImages/480p"
    dir_annotations = "Dataset/Annotations/480p"

    classes, classidx = find_classes(dir_images)
    datas = make_dataset(dir_images, dir_annotations)
    x = tf.placeholder(tf.float32, shape=[None, 256, 256, 3], name='X') #Need to define the shape of x
    y = tf.placeholder(tf.float32, shape=[None, 256,256, 1], name='Y')
    logits = build_model(x, 0.5, 128)
    model = tf.identity(logits, name='logits')
    Cost = tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(logits=logits, labels=y))
    optimizer = tf.train.AdamOptimizer(learning_rate=learning_rate).minimize(Cost)

    correct_pred = tf.equal(tf.argmax(logits, 1), tf.argmax(y, 1))
    accuracy = tf.reduce_mean(tf.cast(correct_pred, tf.float32))

    init = tf.global_variables_initializer()
    sess = tf.InteractiveSession()
    # Initialize all variables
    sess.run(init)
    saver = tf.train.Saver()
    with tf.Session() as sess:
        # variables need to be initialized before any sess.run() calls
        tf.global_variables_initializer().run()

        for X_batch, y_batch in generator(datas,32):
            feed_dict = {x: X_batch, y: y_batch}
            sess.run(optimizer, feed_dict)
```

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:NA
- TensorFlow installed from (source or binary):Source
- TensorFlow version (use command below):1.2.1
- Python version:3.6.4
- Bazel version (if compiling from source):NA
- GCC/Compiler version (if compiling from source):NA
- CUDA/cuDNN version:NA
- GPU model and memory:NA

**Describe the current behavior** Getting this error when I am tring to start the training in images.

**Describe the expected behavior**
It should start training
**Code to reproduce the issue**
Get Davis dataset and put it in respective folders

**Comment by PP-YE** [comment]
How to solve this problem?  Have you solved it?

**Comment by muneeb699** [comment]
Its a really old question but i will give you an idea. Check the shape after each output. THis is a shape problem.
