### ISSUE TITLE
tf.keras - Saving model ignores layers that aren't fed into other layers

### ISSUE THREAD

**Issue by harrismirza** [tensorflow/tensorflow#23722]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): **Yes**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Windows 10**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: **N/A**
- TensorFlow installed from (source or binary): **Binary**
- TensorFlow version (use command below): **b'v1.11.0-rc2-4-gc19e29306c' 1.11.0**
- Python version: **3.6.7**
- Bazel version (if compiling from source): **N/A**
- GCC/Compiler version (if compiling from source): **N/A**
- CUDA/cuDNN version: **N/A**
- GPU model and memory: **N/A**

**Describe the current behavior**
When I save and reload a model that has multiple inputs, but some aren't fed into any layers (they are used in a custom loss function), not all inputs are created in the new model.

Opening the HDF File of the saved model shows that the input layers aren't saved in the model configuration.

**Describe the expected behavior**
All layers should be correctly created

**Code to reproduce the issue**
```python
import tensorflow.keras as keras
import numpy as np


def custom_loss(loss_input):
    def loss(y_true, y_pred):
        return y_true * y_pred * loss_input
    return loss


# Create simple model
input_layer = keras.Input(shape=(1,))
loss_input_layer = keras.Input(shape=(1,))

output = keras.layers.Dense(1)(input_layer)

model = keras.Model(inputs=[input_layer, loss_input_layer], outputs=[output])

model.compile(optimizer=keras.optimizers.Adam(lr=1e4), loss=[custom_loss(loss_input_layer)])

# Train the model with some example data
input_data = np.random.random_sample(512)
loss_data = np.random.random_sample(512)
output_data = input_data * -1

model.train_on_batch(x=[input_data, loss_data], y=[output_data])

# Save and load model
model.save("test.h5")
model = keras.models.load_model("test.h5", custom_objects={"loss": custom_loss(loss_input_layer)})

# Test model
model.predict(x=[[np.random.random_sample(1)], [np.random.random_sample(1)]])
```

**Other info / logs**
```
Traceback (most recent call last):
  File "C:/Users/user/test/testTensorboard.py", line 31, in <module>
    model.predict(x=[[np.random.random_sample(1)], [np.random.random_sample(1)]])
  File "C:\ProgramData\Miniconda3\envs\SolitairePPO\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1752, in predict
    x, check_steps=True, steps_name='steps', steps=steps)
  File "C:\ProgramData\Miniconda3\envs\SolitairePPO\lib\site-packages\tensorflow\python\keras\engine\training.py", line 993, in _standardize_user_data
    class_weight, batch_size)
  File "C:\ProgramData\Miniconda3\envs\SolitairePPO\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1112, in _standardize_weights
    exception_prefix='input')
  File "C:\ProgramData\Miniconda3\envs\SolitairePPO\lib\site-packages\tensorflow\python\keras\engine\training_utils.py", line 286, in standardize_input_data
    str(len(data)) + ' arrays: ' + str(data)[:200] + '...')
ValueError: Error when checking model input: the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 1 array(s), but instead got the following list of 2 arrays: [array([[0.08552315]]), array([[0.11069975]])]...
```

**Comment by tensorflowbutler** [comment]
Nagging Assignee @ymodak: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by cataclysmus** [comment]
It looks like a bad written code. If you call `model.summary()` before saving it, you'll not see no second input in it. It is ignored because disconnected from other layers. Check [keras guide for multi-input model](https://keras.io/getting-started/functional-api-guide/#multi-input-and-multi-output-models) for the right implementation. The basic idea that you use `keras.layers.concatenate` to merge two inputs and then split them in loss function.

**Comment by harrismirza** [comment]
In this example, the inputs can be merged, but that is not always the case, for example when the inputs different shapes.

**Comment by ymodak** [comment]
Apologies for the delay in response.
I was able to execute your code snippet successfully using TF 1.13.rc0
Can you please confirm? Thanks!

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
