### ISSUE TITLE
"Invalid loop structure" for Cleverhans saliency map attack on Keras model with Dropout layers

### ISSUE THREAD

**Issue by AndrewFerr** [tensorflow/tensorflow#23746]
**System information**
- Have I written custom code: Yes
- OS Platform and Distribution: Fedora 29
- TensorFlow installed from: source
- TensorFlow version: v1.11.0-0-gc19e29306c
- Python version: 3.6.6
- Bazel version: 0.19.1- (@non-git)
- GCC/Compiler version: 7.3.0
- CUDA/cuDNN version: 9.2
- GPU model and memory: GeForce GTX 1050 3.95GiB

**Describe the current behavior**
- Prepared & trained a Keras Sequential model based on [this example script](https://github.com/keras-team/keras/blob/master/examples/cifar10_cnn.py), which contains Dropout layers
- Passed the trained model to a [KerasModelWrapper](https://github.com/tensorflow/cleverhans/blob/master/cleverhans_tutorials/mnist_tutorial_keras_tf.py), a class provided by the [Cleverhans](https://github.com/tensorflow/cleverhans) library
- Instantiated a [SaliencyMapMethod](https://github.com/tensorflow/cleverhans/blob/master/cleverhans_tutorials/mnist_tutorial_jsma.py) attack object on the wrapped model, and attempted to craft an adversarial example with it
- TensorFlow encounters this error:
```
tensorflow.python.framework.errors_impl.InternalError: Invalid loop structure: Mismatched parent frames for "while_1/while_context": "while_1/while_context" vs "". The node giving this error: {{node while_1/gradients/while_1/model_4/dropout_1/cond/mul_grad/Shape/Enter}}This is an internal bug, please file a bug report with instructions on how to reproduce the error.
```
- Removing the Dropout layers from the Keras model prevents this error from occuring.

**Describe the expected behavior**
Want the `generate_np` method of the SaliencyMapMethod object to return an adversarial example for the wrapped Keras model.

**Code to reproduce the issue**
```
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras.activations import relu, softmax

import cleverhans
from cleverhans.attacks import SaliencyMapMethod
from cleverhans.utils_keras import KerasModelWrapper

import numpy as np

dataset = keras.datasets.cifar10
num_classes = 10

(train_images, train_labels), (test_images, test_labels) = dataset.load_data()
input_shape = train_images.shape[1:]

train_images = train_images.astype('float32') / 255.0
test_images  = test_images.astype('float32') / 255.0

train_labels = keras.utils.to_categorical(train_labels, num_classes)
test_labels  = keras.utils.to_categorical(test_labels, num_classes)

model = Sequential([
    Conv2D(32, (3,3), padding='same', input_shape=input_shape, activation=relu),
    Conv2D(32, (3,3), activation=relu),
    MaxPooling2D(pool_size=(2,2)),
    Dropout(0.25),

    Conv2D(64, (3,3), padding='same', activation=relu),
    Conv2D(64, (3,3), activation=relu),
    MaxPooling2D(pool_size=(2, 2)),
    Dropout(0.25),

    Flatten(),
    Dense(512, activation=relu),
    Dropout(0.5),
    Dense(num_classes, activation=softmax)
])

model.compile(optimizer=keras.optimizers.SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True),
              loss=keras.losses.categorical_crossentropy,
              metrics=[keras.metrics.categorical_accuracy])

model.fit(train_images, train_labels)

jsma = SaliencyMapMethod(KerasModelWrapper(model), keras.backend.get_session())
jsma_params = {'theta': 1., 'gamma': 0.1,
               'clip_min': 0., 'clip_max': 1.,
               'y_target': None}

# Generate adversarial examples for first test sample
sample_ind = 0
samples = test_images[sample_ind:(sample_ind + 1)]
current_class = int(np.argmax(test_labels[sample_ind]))
for target in cleverhans.utils.other_classes(num_classes, current_class):
    one_hot_target = np.zeros((1, num_classes), dtype=np.float32)
    one_hot_target[0, target] = 1
    jsma_params['y_target'] = one_hot_target
    # Error happens here
    adversarial_images = jsma.generate_np(samples, **jsma_params)
    break
```

**Other info / logs**
- Keras version: 2.2.4 (from pip)
- Cleverhans version: 2.0.0-fe079e17fb307c71a4a413d8bd408d98 (from source, commit [0b22b1c](https://github.com/tensorflow/cleverhans/commit/0b22b1c523cd06efd93d3999c5118986819ac98e))
- Full traceback of the error when running the above code:
```
Traceback (most recent call last):
  File "~/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1292, in _do_call
    return fn(*args)
  File "~/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1277, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "~/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1367, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InternalError: Invalid loop structure: Mismatched parent frames for "while/while_context": "while/while_context" vs "". The node giving this error: {{node while/gradients/while/model_1/dropout_1/cond/mul_grad/Shape/Enter}}This is an internal bug, please file a bug report with instructions on how to reproduce the error.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "crash.py", line 62, in <module>
    adversarial_images = jsma.generate_np(samples, **jsma_params)
  File "~/cleverhans/cleverhans/attacks.py", line 203, in generate_np
    return self.sess.run(x_adv, feed_dict)
  File "~/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 887, in run
    run_metadata_ptr)
  File "~/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1110, in _run
    feed_dict_tensor, options, run_metadata)
  File "~/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1286, in _do_run
    run_metadata)
  File "~/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1308, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Invalid loop structure: Mismatched parent frames for "while/while_context": "while/while_context" vs "". The node giving this error: {{node while/gradients/while/model_1/dropout_1/cond/mul_grad/Shape/Enter}}This is an internal bug, please file a bug report with instructions on how to reproduce the error.
```

**Comment by tensorflowbutler** [comment]
Nagging Assignee @ymodak: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by ymodak** [comment]
I apologize for the delay in response. I think this issue is better suited for [tensorflow/cleverhans repo](https://github.com/tensorflow/cleverhans/issues). Please post it on cleverhans repo. Thanks!
