### ISSUE TITLE
ImportError: cannot import name 'cloud'

### ISSUE THREAD

**Issue by sadatnfs** [tensorflow/tensorflow#23758]
The latest build is giving me a weird Import Error on a module, even though I added extra stuff to the necessary __init__.py. Build command and trace below:

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): N/A
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): Master branch
- Python version: 3.6.5
- Bazel version (if compiling from source): 0.15.0
- GCC/Compiler version (if compiling from source): 8.2.0
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Code to reproduce the issue**
```bash 
wget https://github.com/bazelbuild/bazel/releases/download/0.15.0/bazel_0.15.0-linux-x86_64.deb && \
    sudo dpkg -i bazel_0.15.0-linux-x86_64.deb && \
    sudo apt-get install -f && \
    rm bazel_0.15.0-linux-x86_64.deb && \
    pip uninstall -y tensorflow-tensorboard tfp-nightly tensorflow_estimator tb-nightly tf-nightly tensorflow && \
    cd /opt && \
    git clone --recursive   https://github.com/tensorflow/tensorflow.git && \
    cd /opt/tensorflow && \
    sed -i 's/2018\.0\.3\.20180406/2019\.0\.1\.20180928/g' tensorflow/contrib/cmake/external/mkl.cmake && \
    sed -i 's/v0\.14/v0\.17\-rc/g' tensorflow/contrib/cmake/external/mkl.cmake && \
    sed -i 's/3063b2e4c943983f6bf5f2fb9a490d4a998cd291/21fb5f2af1dd14e132af4f1b79160977ee487818/g' tensorflow/contrib/cmake/external/mkldnn.cmake && \
    ln -s /usr/lib/libmkldnn.so /usr/lib/libiomp5.so /usr/lib/libmklml_gnu.so  /usr/lib/libmklml_intel.so $MKLROOT/lib/intel64_lin && \
    ln -s /usr/include/mkldnn* $MKLROOT/include && \
    ln -s $MKLROOT/lib/intel64_lin/* $MKLROOT/lib && \
    ln -s /usr/lib /usr/lib/lib && \
    echo "" > /usr/local/lib/license.txt && \
    echo "" > /usr/local/include/license.txt && \
    echo "from tensorflow.contrib import cloud" >> tensorflow/contrib/__init__.py && \
    echo "from tensorflow.contrib import *" >> tensorflow/contrib/__init__.py && \
    TF_MKL_ROOT=/usr/lib  \
    TF_MKL_DOWNLOAD=0 \
    USE_DEFAULT_PYTHON_LIB_PATH=1 \
    TF_NEED_MKL=1 \
    TF_NEED_JEMALLOC=1 \
    TF_NEED_GCP=0 \
    TF_NEED_HDFS=0 \
    TF_ENABLE_XLA=1 \
    TF_NEED_MPI=0 \
    TF_NEED_GDR=0 \
    TF_NEED_S3=1 \
    TF_NEED_KAFKA=0 \
    TF_SET_ANDROID_WORKSPACE=0 \
    TF_NEED_CUDA=0 \
    TF_MKL_ENABLED="true" \
    CI_BUILD_PYTHON=/opt/conda/bin/python \
    PYTHON_BIN_PATH=/opt/conda/bin/python \
    PYTHON_LIB_PATH=/opt/conda/lib/python3.6/site-packages \
    GCC_HOST_COMPILER_PATH=/usr/bin/gcc \
    CC_OPT_FLAGS="-msse4.2 -msse4.1 -mavx -msse2 -msse3 -mfpmath=sse -lmkl_gf_lp64 -Wl,--start-group -lmkldnn -lmklml_intel -lmkl_gnu_thread -lmkl_core -Wl,--end-group -dl -lpthread -lm " \
    /bin/bash ./configure \
    && \
    bazel build \
    --config=mkl --config=opt \
    --config=noaws --config=nogcp --config=verbs --config=noignite --config=nokafka \
    --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" \
    --copt=-msse4.2 --copt=-msse4.1 --copt=-mavx --copt=-msse2 --copt=-msse3  \
    --copt=-O3 --copt=-mfpmath=both \
    --copt="-DMKL_LP64" \
    --copt="-fPIC" \
    --linkopt="-lmkl_gf_lp64" \
    --linkopt="-lmkl_gnu_thread" \
    --linkopt="-dl" \
    --linkopt="-ldl" \
    --linkopt="-lpthread" \
    --linkopt="-lmkl_core" \
    --linkopt="-lm" \
    --linkopt="-lmkl_rt" \
    --linkopt="-lmkldnn" \
    tensorflow/tools/pip_package:build_pip_package && \
    bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/pip && \
    pip install --no-deps /tmp/pip/tensorflow-*.whl && \
    cd /opt && rm -rf /opt/tensorflow /tmp/* && \
    python -c "import tensorflow as tf; hello = tf.constant('Hello, TensorFlow!'); sess = tf.Session(); print(sess.run(hello))" && \

### Build TFP after this ###

    python -c "import tensorflow_probability"

```

** Trace **
```python 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/lib/python3.6/site-packages/tensorflow_probability/__init__.py", line 78, in <module>
    from tensorflow_probability.python import *  # pylint: disable=wildcard-import
  File "/opt/conda/lib/python3.6/site-packages/tensorflow_probability/python/__init__.py", line 22, in <module>
    from tensorflow_probability.python import distributions
  File "/opt/conda/lib/python3.6/site-packages/tensorflow_probability/python/distributions/__init__.py", line 66, in <module>
    from tensorflow_probability.python.distributions.multivariate_student_t import MultivariateStudentTLinearOperator
  File "/opt/conda/lib/python3.6/site-packages/tensorflow_probability/python/distributions/multivariate_student_t.py", line 25, in <module>
    from tensorflow_probability.python import math
  File "/opt/conda/lib/python3.6/site-packages/tensorflow_probability/python/math/__init__.py", line 22, in <module>
    from tensorflow_probability.python.math.diag_jacobian import diag_jacobian
  File "/opt/conda/lib/python3.6/site-packages/tensorflow_probability/python/math/diag_jacobian.py", line 24, in <module>
    tfe = tf.contrib.eager
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/util/lazy_loader.py", line 53, in __getattr__
    module = self._load()
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/util/lazy_loader.py", line 42, in _load
    module = importlib.import_module(self.__name__)
  File "/opt/conda/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/contrib/__init__.py", line 30, in <module>
    from tensorflow.contrib import cloud
ImportError: cannot import name 'cloud'

```

**Comment by phalexo** [comment]
I see the same issue. How did you resolve it?

**Comment by sadatnfs** [comment]
Oh I didn't know this issue popped up again. It was solved automatically on my end when I built from Master using Bazel 0.15. I have a few lines in my build call that I add to in the inits, but I haven't built in a recent while. I'll reopen this if my build fails again.

**Comment by sadatnfs** [comment]
Ooff can confirm that it's indeed back. Reopening.

**Comment by gunan** [comment]
which commit did you build the above version?
It looks like I made a mistake in our build files, which excluded cloud capabilities by mistake.
It is fixed in the last few days.

**Comment by sadatnfs** [comment]
I just built on whatever the latest commit was on Master 3 hours ago.

**Comment by phalexo** [comment]
I pulled the fresh master and was able to rebuild it.

**Comment by sadatnfs** [comment]
Closing then! Thanks!

**Comment by Nayana-ibm** [comment]
@gunan Could you please point to commit which resolves` ImportError: cannot import name cloud` issue?
I have observed this error on test cases failures for v1.12.0

**Comment by phalexo** [comment]
I just did "git checkout master" to make sure I have that fix. I also think
it may be a good idea to just delete "tensorflow" folder after a failed
build and pull a fresh one. I think "bazel clean" does not clean up
everything.

**Comment by Nayana-ibm** [comment]
@phalexo Thanks for your inputs.
 I wanted to know which commit fixes this issue in master so if possible I can apply that patch to v1.12.0 code and rerun test cases.

**Comment by gunan** [comment]
I think the same commits mentioned in https://github.com/tensorflow/tensorflow/issues/23771 should fix this

**Comment by sadatnfs** [comment]
@gunan reopening because it's back again.. :(

**Comment by gunan** [comment]
I think you need to build with GCP support on x86 system to avoid running into this problem
on ppc, we will slve this by disabling access to tf.contrib.cloud as described in #23976

**Comment by sadatnfs** [comment]
Aha! I just started the bulid with GCP, will report back! THanks!
