### ISSUE TITLE
Windows 10 Failed to load the native TensorFlow runtime

### ISSUE THREAD

**Issue by MohammadDabbas** [tensorflow/tensorflow#23755]
Please make sure that this is a bug. As per our GitHub Policy, we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template

System information

OS Platform and Distribution Windows 10 64 bit
TensorFlow installed from (source or binary): pip install tensorflow
TensorFlow version: 1.12.0
Python version:3.6.5
GPU model and memory: Geforce 150mx 4gb
Describe the problem
I'm unable to import keras using "Tensorflow backend"
when I try to import "from keras.models import Sequential" I get the error shown bellow

These are the steps that I did when I installed the libraries
1- conda create -n tensorflow python=3.5 anaconda.

2- activate tensorflow.

3- conda install theano.

4- conda install mingw libpython.

5-pip install tensorflow.

6- pip install keras.

7- conda update --all

8- pip install tensorflow-gpu

Other info / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

Error shown:

`from keras.models import Sequential
Using TensorFlow backend.
Traceback (most recent call last):

File "", line 1, in 
from keras.models import Sequential

File "C:\Users\MHD\Anaconda3\lib\site-packages\keras_init_.py", line 3, in 
from . import utils

File "C:\Users\MHD\Anaconda3\lib\site-packages\keras\utils_init_.py", line 6, in 
from . import conv_utils

File "C:\Users\MHD\Anaconda3\lib\site-packages\keras\utils\conv_utils.py", line 9, in 
from .. import backend as K

File "C:\Users\MHD\Anaconda3\lib\site-packages\keras\backend_init_.py", line 89, in 
from .tensorflow_backend import *

File "C:\Users\MHD\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py", line 5, in 
import tensorflow as tf

File "C:\Users\MHD\Anaconda3\lib\site-packages\tensorflow_init_.py", line 24, in 
from tensorflow.python import pywrap_tensorflow # pylint: disable=unused-import

File "C:\Users\MHD\Anaconda3\lib\site-packages\tensorflow\python_init_.py", line 49, in 
from tensorflow.python import pywrap_tensorflow

File "C:\Users\MHD\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in 
raise ImportError(msg)

ImportError: Traceback (most recent call last):
File "C:\Users\MHD\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in 
from tensorflow.python.pywrap_tensorflow_internal import *
File "C:\Users\MHD\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in 
_pywrap_tensorflow_internal = swig_import_helper()
File "C:\Users\MHD\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
_mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
File "C:\Users\MHD\Anaconda3\lib\imp.py", line 243, in load_module
return load_dynamic(name, filename, file)
File "C:\Users\MHD\Anaconda3\lib\imp.py", line 343, in load_dynamic
return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions. Include the entire stack trace
above this error message when asking for help.`

**Comment by ymodak** [comment]
Couple of things I would like to check. I see that you are using Python 3.X
Therefore you need to use pip3 to install TensorFlow and Keras
pip3 install tensorflow
pip3 install keras
Also are you able to start a TensorFlow session successfully?
What's the output of following in your python console?
  import tensorflow as tf

**Comment by MohammadDabbas** [comment]
I have installed python 3 but when I checked now I found that I have folder named `python_dateutil-2.7.5.dist-info`
also I tried    to import tensorflow from the console and I got this error:
`import tensorflow as tf
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
~\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py in <module>
     57 
---> 58   from tensorflow.python.pywrap_tensorflow_internal import *
     59   from tensorflow.python.pywrap_tensorflow_internal import __version__

~\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py in <module>
     27             return _mod
---> 28     _pywrap_tensorflow_internal = swig_import_helper()
     29     del swig_import_helper

~\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py in swig_import_helper()
     23             try:
---> 24                 _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
     25             finally:

~\Anaconda3\lib\imp.py in load_module(name, file, filename, details)
    242         else:
--> 243             return load_dynamic(name, filename, file)
    244     elif type_ == PKG_DIRECTORY:

~\Anaconda3\lib\imp.py in load_dynamic(name, path, file)
    342             name=name, loader=loader, origin=path)
--> 343         return _load(spec)
    344 

ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-1-64156d691fe5> in <module>
----> 1 import tensorflow as tf

~\Anaconda3\lib\site-packages\tensorflow\__init__.py in <module>
     22 
     23 # pylint: disable=g-bad-import-order
---> 24 from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
     25 
     26 try:

~\Anaconda3\lib\site-packages\tensorflow\python\__init__.py in <module>
     47 import numpy as np
     48 
---> 49 from tensorflow.python import pywrap_tensorflow
     50 
     51 from tensorflow.python.tools import component_api_helper

~\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py in <module>
     72 for some common reasons and solutions.  Include the entire stack trace
     73 above this error message when asking for help.""" % traceback.format_exc()
---> 74   raise ImportError(msg)
     75 
     76 # pylint: enable=wildcard-import,g-import-not-at-top,unused-import,line-too-long

ImportError: Traceback (most recent call last):
  File "C:\Users\MHD\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\MHD\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\MHD\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\MHD\Anaconda3\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\MHD\Anaconda3\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.`

**Comment by MohammadDabbas** [comment]
I installed tensorflow on my gpu and I didn't install CUDA Tool kit 9.0 , CUDNN and Tensorflow-GPU 1.5 
my question is: could that be the reason?

**Comment by ymodak** [comment]
Yes you need to install those drivers for [GPU support](https://www.tensorflow.org/install/gpu) and update [environment variables](https://www.tensorflow.org/install/gpu#windows_setup).

**Comment by tensorflowbutler** [comment]
Nagging Assignee @ymodak: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by ymodak** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by ibrahimabob** [comment]
conda create -n tfdeeplearning python=3.5
conda install jupyter
conda install numpy
conda install pandas
conda install scikit-learn
conda install matplotlib
pip install --upgrade tensorflow
give me error 
ImportError                               Traceback (most recent call last)
~\Anaconda3\envs\tfdeeplearning\lib\site-packages\tensorflow\python\pywrap_tensorflow.py in <module>()
     57 
---> 58   from tensorflow.python.pywrap_tensorflow_internal import *
     59   from tensorflow.python.pywrap_tensorflow_internal import __version__

~\Anaconda3\envs\tfdeeplearning\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py in <module>()
     27             return _mod
---> 28     _pywrap_tensorflow_internal = swig_import_helper()
     29     del swig_import_helper

~\Anaconda3\envs\tfdeeplearning\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py in swig_import_helper()
     23             try:
---> 24                 _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
     25             finally:

~\Anaconda3\envs\tfdeeplearning\lib\imp.py in load_module(name, file, filename, details)
    242         else:
--> 243             return load_dynamic(name, filename, file)
    244     elif type_ == PKG_DIRECTORY:

~\Anaconda3\envs\tfdeeplearning\lib\imp.py in load_dynamic(name, path, file)
    342             name=name, loader=loader, origin=path)
--> 343         return _load(spec)
    344 

ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-1-64156d691fe5> in <module>()
----> 1 import tensorflow as tf

~\Anaconda3\envs\tfdeeplearning\lib\site-packages\tensorflow\__init__.py in <module>()
     22 
     23 # pylint: disable=g-bad-import-order
---> 24 from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
     25 
     26 from tensorflow._api.v1 import app

~\Anaconda3\envs\tfdeeplearning\lib\site-packages\tensorflow\python\__init__.py in <module>()
     47 import numpy as np
     48 
---> 49 from tensorflow.python import pywrap_tensorflow
     50 
     51 # Protocol buffers

~\Anaconda3\envs\tfdeeplearning\lib\site-packages\tensorflow\python\pywrap_tensorflow.py in <module>()
     72 for some common reasons and solutions.  Include the entire stack trace
     73 above this error message when asking for help.""" % traceback.format_exc()
---> 74   raise ImportError(msg)
     75 
     76 # pylint: enable=wildcard-import,g-import-not-at-top,unused-import,line-too-long

ImportError: Traceback (most recent call last):
  File "C:\Users\ibr\Anaconda3\envs\tfdeeplearning\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\ibr\Anaconda3\envs\tfdeeplearning\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\ibr\Anaconda3\envs\tfdeeplearning\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\ibr\Anaconda3\envs\tfdeeplearning\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\ibr\Anaconda3\envs\tfdeeplearning\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

Kindly help .

**Comment by Saran-nns** [comment]
> conda create -n tfdeeplearning python=3.5
> conda install jupyter
> conda install numpy
> conda install pandas
> conda install scikit-learn
> conda install matplotlib
> pip install --upgrade tensorflow
> give me error
> ImportError Traceback (most recent call last)
> ~\Anaconda3\envs\tfdeeplearning\lib\site-packages\tensorflow\python\pywrap_tensorflow.py in ()
> 57
> ---> 58 from tensorflow.python.pywrap_tensorflow_internal import *
> 59 from tensorflow.python.pywrap_tensorflow_internal import **version**
> 
> ~\Anaconda3\envs\tfdeeplearning\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py in ()
> 27 return _mod
> ---> 28 _pywrap_tensorflow_internal = swig_import_helper()
> 29 del swig_import_helper
> 
> ~\Anaconda3\envs\tfdeeplearning\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py in swig_import_helper()
> 23 try:
> ---> 24 _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
> 25 finally:
> 
> ~\Anaconda3\envs\tfdeeplearning\lib\imp.py in load_module(name, file, filename, details)
> 242 else:
> --> 243 return load_dynamic(name, filename, file)
> 244 elif type_ == PKG_DIRECTORY:
> 
> ~\Anaconda3\envs\tfdeeplearning\lib\imp.py in load_dynamic(name, path, file)
> 342 name=name, loader=loader, origin=path)
> --> 343 return _load(spec)
> 344
> 
> ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.
> 
> During handling of the above exception, another exception occurred:
> 
> ImportError Traceback (most recent call last)
> in ()
> ----> 1 import tensorflow as tf
> 
> ~\Anaconda3\envs\tfdeeplearning\lib\site-packages\tensorflow__init__.py in ()
> 22
> 23 # pylint: disable=g-bad-import-order
> ---> 24 from tensorflow.python import pywrap_tensorflow # pylint: disable=unused-import
> 25
> 26 from tensorflow._api.v1 import app
> 
> ~\Anaconda3\envs\tfdeeplearning\lib\site-packages\tensorflow\python__init__.py in ()
> 47 import numpy as np
> 48
> ---> 49 from tensorflow.python import pywrap_tensorflow
> 50
> 51 # Protocol buffers
> 
> ~\Anaconda3\envs\tfdeeplearning\lib\site-packages\tensorflow\python\pywrap_tensorflow.py in ()
> 72 for some common reasons and solutions. Include the entire stack trace
> 73 above this error message when asking for help.""" % traceback.format_exc()
> ---> 74 raise ImportError(msg)
> 75
> 76 # pylint: enable=wildcard-import,g-import-not-at-top,unused-import,line-too-long
> 
> ImportError: Traceback (most recent call last):
> File "C:\Users\ibr\Anaconda3\envs\tfdeeplearning\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in 
> from tensorflow.python.pywrap_tensorflow_internal import *
> File "C:\Users\ibr\Anaconda3\envs\tfdeeplearning\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in 
> _pywrap_tensorflow_internal = swig_import_helper()
> File "C:\Users\ibr\Anaconda3\envs\tfdeeplearning\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
> _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
> File "C:\Users\ibr\Anaconda3\envs\tfdeeplearning\lib\imp.py", line 243, in load_module
> return load_dynamic(name, filename, file)
> File "C:\Users\ibr\Anaconda3\envs\tfdeeplearning\lib\imp.py", line 343, in load_dynamic
> return _load(spec)
> ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.
> 
> Failed to load the native TensorFlow runtime.
> 
> See https://www.tensorflow.org/install/errors
> 
> for some common reasons and solutions. Include the entire stack trace
> above this error message when asking for help.
> 
> Kindly help .

Did you found any solution; I am going through the same issue since yesterday?

**Comment by osama12sy** [comment]
I also have the same problem 
I have python 3.6.8
cpu version 
my operating system is windows 10 64bit

 ```
Traceback (most recent call last):
  File "C:\Users\حسين\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\حسين\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\حسين\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\حسين\AppData\Local\Programs\Python\Python36\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\حسين\AppData\Local\Programs\Python\Python36\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

```
`During handling of the above exception, another exception occurred:
`
```
Traceback (most recent call last):
  File "flow", line 4, in <module>
    from darkflow.cli import cliHandler
  File "C:\Users\حسين\Downloads\YOLO_Object_Detection-master\darkflow\cli.py", line 3, in <module>
    from .net.build import TFNet
  File "C:\Users\حسين\Downloads\YOLO_Object_Detection-master\darkflow\net\build.py", line 1, in <module>
    import tensorflow as tf
  File "C:\Users\حسين\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\حسين\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\حسين\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\حسين\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\حسين\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\حسين\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\حسين\AppData\Local\Programs\Python\Python36\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\حسين\AppData\Local\Programs\Python\Python36\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

```

Failed to load the native TensorFlow runtime.

**Comment by ibrahimabob** [comment]
> > conda create -n tfdeeplearning python=3.5
> > conda install jupyter
> > conda install numpy
> > conda install pandas
> > conda install scikit-learn
> > conda install matplotlib
> > pip install --upgrade tensorflow
> > give me error
> > ImportError Traceback (most recent call last)
> > ~\Anaconda3\envs\tfdeeplearning\lib\site-packages\tensorflow\python\pywrap_tensorflow.py in ()
> > 57
> > ---> 58 from tensorflow.python.pywrap_tensorflow_internal import *
> > 59 from tensorflow.python.pywrap_tensorflow_internal import **version**
> > ~\Anaconda3\envs\tfdeeplearning\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py in ()
> > 27 return _mod
> > ---> 28 _pywrap_tensorflow_internal = swig_import_helper()
> > 29 del swig_import_helper
> > ~\Anaconda3\envs\tfdeeplearning\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py in swig_import_helper()
> > 23 try:
> > ---> 24 _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
> > 25 finally:
> > ~\Anaconda3\envs\tfdeeplearning\lib\imp.py in load_module(name, file, filename, details)
> > 242 else:
> > --> 243 return load_dynamic(name, filename, file)
> > 244 elif type_ == PKG_DIRECTORY:
> > ~\Anaconda3\envs\tfdeeplearning\lib\imp.py in load_dynamic(name, path, file)
> > 342 name=name, loader=loader, origin=path)
> > --> 343 return _load(spec)
> > 344
> > ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.
> > During handling of the above exception, another exception occurred:
> > ImportError Traceback (most recent call last)
> > in ()
> > ----> 1 import tensorflow as tf
> > ~\Anaconda3\envs\tfdeeplearning\lib\site-packages\tensorflow__init__.py in ()
> > 22
> > 23 # pylint: disable=g-bad-import-order
> > ---> 24 from tensorflow.python import pywrap_tensorflow # pylint: disable=unused-import
> > 25
> > 26 from tensorflow._api.v1 import app
> > ~\Anaconda3\envs\tfdeeplearning\lib\site-packages\tensorflow\python__init__.py in ()
> > 47 import numpy as np
> > 48
> > ---> 49 from tensorflow.python import pywrap_tensorflow
> > 50
> > 51 # Protocol buffers
> > ~\Anaconda3\envs\tfdeeplearning\lib\site-packages\tensorflow\python\pywrap_tensorflow.py in ()
> > 72 for some common reasons and solutions. Include the entire stack trace
> > 73 above this error message when asking for help.""" % traceback.format_exc()
> > ---> 74 raise ImportError(msg)
> > 75
> > 76 # pylint: enable=wildcard-import,g-import-not-at-top,unused-import,line-too-long
> > ImportError: Traceback (most recent call last):
> > File "C:\Users\ibr\Anaconda3\envs\tfdeeplearning\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in
> > from tensorflow.python.pywrap_tensorflow_internal import *
> > File "C:\Users\ibr\Anaconda3\envs\tfdeeplearning\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in
> > _pywrap_tensorflow_internal = swig_import_helper()
> > File "C:\Users\ibr\Anaconda3\envs\tfdeeplearning\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
> > _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
> > File "C:\Users\ibr\Anaconda3\envs\tfdeeplearning\lib\imp.py", line 243, in load_module
> > return load_dynamic(name, filename, file)
> > File "C:\Users\ibr\Anaconda3\envs\tfdeeplearning\lib\imp.py", line 343, in load_dynamic
> > return _load(spec)
> > ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.
> > Failed to load the native TensorFlow runtime.
> > See https://www.tensorflow.org/install/errors
> > for some common reasons and solutions. Include the entire stack trace
> > above this error message when asking for help.
> > Kindly help .
> 
> Did you found any solution; I am going through the same issue since yesterday?

Sorry nothing new with me in my PC working but I am trying to install It in my Laptop give me this error Failed to load the native TensorFlow runtime.

**Comment by RajdeepPy** [comment]
I have the same problem


>>> import tensorflow
Traceback (most recent call last):
  File "C:\Users\princ\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tensorflow_internal', [dirname(__file__)])
  File "C:\Users\princ\Anaconda3\lib\imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\princ\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\princ\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\princ\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 20, in swig_import_helper
    import _pywrap_tensorflow_internal
ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\princ\Anaconda3\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\princ\Anaconda3\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\princ\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\princ\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tensorflow_internal', [dirname(__file__)])
  File "C:\Users\princ\Anaconda3\lib\imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\princ\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\princ\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\princ\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 20, in swig_import_helper
    import _pywrap_tensorflow_internal
ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by j0ck3r2004** [comment]
@RajdeepPy @ibrahimabob @osama12sy @Saran-nns @ymodak @MohammadDabbas
ok so i did a research on this erro and i found that tensorflow only support python 3.5x & 3.6x so download and install one of these 2 versions the install the packages you need and run the program. for me it worked

**Comment by ibrahimabob** [comment]
thank you so much

**Comment by j0ck3r2004** [comment]
@RajdeepPy @ibrahimabob @osama12sy @Saran-nns @ymodak @MohammadDabbas
# Current stable release for CPU-only
pip install tensorflow

# Preview nightly build for CPU-only (unstable)
pip install tf-nightly

# Install TensorFlow 2.0 Alpha
pip install tensorflow==2.0.0-alpha0

**Comment by apremgeorge** [comment]
Hi I have the same issue,
I have build the keras Sequential model, and I have Tornado API, when I run the API I get 
```
λ python Tornado6.0.py
Using TensorFlow backend.
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>

    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Anaconda3\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Anaconda3\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Tornado6.0.py", line 17, in <module>
    from keras.models import Sequential
  File "C:\Anaconda3\lib\site-packages\keras\__init__.py", line 3, in <module>
    from . import utils
  File "C:\Anaconda3\lib\site-packages\keras\utils\__init__.py", line 6, in <module>
    from . import conv_utils
  File "C:\Anaconda3\lib\site-packages\keras\utils\conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "C:\Anaconda3\lib\site-packages\keras\backend\__init__.py", line 89, in <module>
    from .tensorflow_backend import *
  File "C:\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf
  File "C:\Anaconda3\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>

    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Anaconda3\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Anaconda3\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

May I have some help please, Thanks

**Comment by ZlaaM** [comment]
@osama12sy 
I have faced the same problem, did you solve it?
please help

**Comment by ZlaaM** [comment]
@osama12sy

**Comment by osama12sy** [comment]
Sorry no

**Comment by hesamzakerirad** [comment]
Having the same problem and literally checked every website and found nothing!

**Comment by shrikantzarekar4** [comment]
Same issue... any suggestion?

**Comment by mihaimaruseac** [comment]
Please open new issues and fill in the template. Also, search for similar issues, they might have been already solved.

For Windows, please make sure the following are all checked:

1. your CPU supports AVX
1. you have installed the latest MSVC redistributable from Microsoft
1. you have a 64 bits Python
1. `pip` has been updated to the last version (`pip install --upgrade pip`)

Locking conversation to prevent further comments hiding solutions
