### ISSUE TITLE
The distribute strategy is not compatible with tf.contrib.slim.batch_norm() and tf.contrib.layers.batch_norm()

### ISSUE THREAD

**Issue by mzhaoshuai** [tensorflow/tensorflow#23770]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): **_no_**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): _**Ubuntu 16.04.5 LTS**_
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:**_no_**
- TensorFlow installed from (source or binary):**_binary_**
- TensorFlow version (use command below):**_1.12.0_**
- Python version: **_Python 3.5.2_**
- Bazel version (if compiling from source): _**None**_
- GCC/Compiler version (if compiling from source):  **_5.4.0_**
- CUDA/cuDNN version: **_cuda-9.0.176/cudnn-7.2.1_**
- GPU model and memory: **_2 same GTX Titan X (Pascal), 12GB_** 

I just use the offical docker image of the tensorflow, the tag is `1.12.0-devel-gpu-py3`

**Problem**

The code is shown below
```
#coding=utf-8

import tensorflow as tf
import numpy as np
import argparse


parser = argparse.ArgumentParser()
parser.add_argument('--num_gpus', type=int, default=2,
						help='The number of the GPUs.')
FLAGS, unparsed = parser.parse_known_args()


def input_fn():
    return (
        tf.data.Dataset.from_tensor_slices([0])
        .map(lambda _: tf.random_uniform([1], 0, np.pi * 2))
        .map(lambda x: (x, tf.sin(x)))
        .repeat()
        .batch(10)
    )

def model_fn(features, labels, mode):
    net = tf.layers.dense(features, units=20)
    net = tf.nn.tanh(net)
    
    #net = tf.contrib.layers.batch_norm(net)
    net = tf.contrib.slim.batch_norm(net)
    #net = tf.keras.layers.BatchNormalization()(net)
    #net = tf.layers.batch_normalization(inputs=net)

    net = tf.layers.dense(net, units=20)
    net = tf.nn.tanh(net)
    output = tf.layers.dense(net, units=1)

    if mode == tf.estimator.ModeKeys.TRAIN:
        loss = tf.reduce_mean(tf.pow(output - labels, 2))
        loss = tf.identity(loss, name='loss')
        train_op = tf.train.GradientDescentOptimizer(0.1).minimize(loss, global_step=tf.train.get_global_step())
        return tf.estimator.EstimatorSpec(tf.estimator.ModeKeys.TRAIN, loss=loss, train_op=train_op)

session_config = tf.ConfigProto(allow_soft_placement=True,
                                    gpu_options=tf.GPUOptions(allow_growth=True, 
                                                force_gpu_compatible=True))
distribution = tf.contrib.distribute.MirroredStrategy(num_gpus=FLAGS.num_gpus)
config = tf.estimator.RunConfig(keep_checkpoint_max=0, 
								train_distribute=distribution)
estimator = tf.estimator.Estimator(model_fn=model_fn, config=config)

tf.logging.set_verbosity(tf.logging.INFO)
tensors_to_log = {'loss':'loss'}
logging_hook = tf.train.LoggingTensorHook(
        			tensors=tensors_to_log, every_n_iter=100)
train_hooks=[logging_hook]
print('tensorflow version: %s' % tf.__version__)
estimator.train(input_fn=input_fn, steps=1000, hooks=train_hooks)
```

When use `tf.contrib.layers.batch_norm`  and `tf.contrib.slim.batch_norm` will raise error
```
 name: GeForce GTX TITAN X, pci bus id: 0000:18:00.0, compute capability: 5.2)
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Error reported to Coordinator:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/coordinator.py", line 297, in stop_on_exception
    yield
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/distribute/python/mirrored_strategy.py", line 795, in run
    self.main_result = self.main_fn(*self.main_args, **self.main_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 1195, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "estimator_multi_gpu.py", line 27, in model_fn
    net = tf.contrib.slim.batch_norm(net)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/layers/python/layers/layers.py", line 596, in batch_norm
    scope=scope)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/layers/python/layers/layers.py", line 416, in _fused_batch_norm
    is_training, _delay_updates, moving_vars_fn)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/layers/python/layers/utils.py", line 214, in smart_cond
    return static_cond(pred_value, fn1, fn2)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/layers/python/layers/utils.py", line 192, in static_cond
    return fn1()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/layers/python/layers/layers.py", line 410, in _delay_updates
    moving_mean, mean, decay, zero_debias=zero_debias_moving_mean)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/moving_averages.py", line 84, in assign_moving_average
    with ops.colocate_with(variable):
  File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 4094, in _colocate_with_for_gradient
    with self.colocate_with(op, ignore_existing):
  File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 4146, in colocate_with
    op = internal_convert_to_tensor_or_indexed_slices(op, as_ref=True).op
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1307, in internal_convert_to_tensor_or_indexed_slices
    value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1146, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/distribute/python/values.py", line 439, in _tensor_conversion_mirrored
    assert not as_ref
AssertionError
```

But if I use `tf.keras.layers.BatchNormalization()(net)` or   `tf.layers.batch_normalization(inputs=net)`,
it is totally OK.

I see the source code of the `tf.layers.batch_normalization` and find it is inherited form `keras.layers.BatchNormalization`
```
from tensorflow.python.keras import layers as keras_layers
from tensorflow.python.layers import base
from tensorflow.python.ops import init_ops
from tensorflow.python.util.tf_export import tf_export

@tf_export('layers.BatchNormalization')
class BatchNormalization(keras_layers.BatchNormalization, base.Layer):
```
And I also find some similar issues
https://github.com/tensorflow/tensorflow/issues/20509
https://github.com/tensorflow/tensorflow/issues/20874
https://github.com/tensorflow/tensorflow/issues/21968
https://github.com/tensorflow/tensorflow/issues/22399

_**There are many pretrained models in the model zoo of `slim`, the bn layer are all not compatible with the distribute stratege. It is not convinient for us to use them in other tasks with `tf.estimator`.**_

**Other info / logs**
There are also two samll problems in the docker images....

**_ONE:_**
```
__new__() got an unexpected keyword argument 'serialized_options'
```
I solvd it by 
```
RUN pip3 install --upgrade pip
```
when build the image.

The `pip install -U protobuf ` did not work.

**_TWO:_**
```

INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 0 into /tmp/tmpggc6_3sr/model.ckpt.
INFO:tensorflow:model.ckpt-0 is not in all_model_checkpoint_paths. Manually adding it.
Unexpected end of /proc/mounts line `overlay / overlay rw,relatime,lowerdir=/var/lib/docker/overlay2/l/GFPVUUB6DIRSEA556PJ7UZSB2U:/var/lib/docker/overlay2/l/Z7PKFCBJ2NCRWLDUMR7HOGXHY5:/var/lib/docker/overlay2/l/XJZAHQOGE7RXOAHTAKELNSYBZ5:/var/lib/docker/overlay2/l/ESG4TTNOTM5ZINQ5O4JCYNFODB:/var/lib/docker/overlay2/l/6ZQZQCRBLVJTIVAKYNIA2VNCNX:/var/lib/docker/overlay2/l/ZIWP422R2WQJXJQWA6BWTKSVP2:/var/lib/docker/overlay2/l/EZJIAHDCQ5P5GASJZR3GCECEE6:/var/lib/docker/overlay2/l/OA2WSFXRNJQI36B7ZILMTVTD5V:/var/lib/docker/overlay2/l/XITXCQNT5YIY7'
Unexpected end of /proc/mounts line `YSSGYLTAEXMQX:/var/lib/docker/overlay2/l/EHORMZU5A6H3H6NAL34XTIYBEA:/var/lib/docker/overlay2/l/E34DRW27EHWOG6HEQCYM2LKYJX:/var/lib/docker/overlay2/l/Y4SABJDSTVMRHZ2SC6QYSK4NP6:/var/lib/docker/overlay2/l/BWHO3NPMOZYCZ33PIH4XXQH3Z6:/var/lib/docker/overlay2/l/YLLBXOSS6TVCINXJNKTZX7J6PQ:/var/lib/docker/overlay2/l/QQ2FBR7QT4NFNYR4UZUXOBD2K3:/var/lib/docker/overlay2/l/SSP6MK4IQCUV2N5DSY5BO4EZO7:/var/lib/docker/overlay2/l/XUONJPPZG5ANA2ELQECHOIY7KU:/var/lib/docker/overlay2/l/ZOCEMSU7RIV6OH6QZNTKKIGACB:/var/lib/do'
```
It seems that this is harmless.
https://stackoverflow.com/questions/46138549/docker-openmpi-and-unexpected-end-of-proc-mounts-line

**Comment by xiaohu2015** [comment]
Why?

**Comment by varun19299** [comment]
Any updates on this? Till this is resolved fully, can a known list of ops to substitute with keras equivalents be put out?

The problem is that extensive network libraries used by object detection and quite a few other modules in `models` are based on slim. There doesn't seem to be any substitute for that.

**Comment by josh11b** [comment]
I don't think we have any current effort to add distribute strategy support to slim, and it seems unlikely to become a priority due to the general TF move away from contrib.

**Comment by mzhaoshuai** [comment]
> Any updates on this? Till this is resolved fully, can a known list of ops to substitute with keras equivalents be put out?
> 
> The problem is that extensive network libraries used by object detection and quite a few other modules in `models` are based on slim. There doesn't seem to be any substitute for that.

@varun19299 
I think you can place your variables and models manually like
https://github.com/tensorflow/models/blob/master/tutorials/image/cifar10/cifar10_multi_gpu_train.py
https://github.com/tensorflow/models/blob/master/tutorials/image/cifar10_estimator/cifar10_main.py

@josh11b 
Now I agree with you and I also think the contrib's compatibility with distribute strategy is not necessary.
It is also a hard work to make the contrib compatible with the distribute strategy.

I will close this issue soon.
