### ISSUE TITLE
TFLite can not set input shape and input_stats with 1.0/128

### ISSUE THREAD

**Issue by zh794390558** [tensorflow/tensorflow#23799]
```
converter = tf.contrib.lite.TFLiteConverter.from_saved_model(
  saved_model_dir=sys.argv[1],
  input_shapes={'input' :[5, 3000, 40, 3]}
  )
converter.dump_graphviz_dir='./lite_dump'
converter.inference_type=tf.contrib.lite.constants.QUANTIZED_UINT8
converter.quantized_input_stats={'inputs': (127, 1.0/128)}
converter.default_ranges_stats=(0, 6)
tflite_model = converter.convert()
```
```
inputs
Type: Uint8 [1×3000×40×3] 
MinMax: [-16256, 16384]
Quantization:
128 * (x - 127)
```

The batch_size is 1 , not 5.
the input var is 128 not 1.0/128

```
interpreter.resize_tensor_input(input_details[0]['index'], [2, 3000, 40, 3])
interpreter.allocate_tensors()
interpreter.invoke()
```
```
Inputs [{'name': 'inputs', 'index': 17, 'shape': array([   1, 3000,   40,    3], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0)}]
Outputs [{'name': 'softmax', 'index': 24, 'shape': array([1, 2], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0)}]
Inputs [{'name': 'inputs', 'index': 17, 'shape': array([   2, 3000,   40,    3], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0)}]
Traceback (most recent call last):
  File "tflite_run.py", line 15, in <module>
    interpreter.allocate_tensors()
  File "/nfs/project/tools/anaconda3/envs/tf1.12_py3.5/lib/python3.6/site-packages/tensorflow/contrib/lite/python/interpreter.py", line 71, in allocate_tensors
    return self._interpreter.AllocateTensors()
  File "/nfs/project/tools/anaconda3/envs/tf1.12_py3.5/lib/python3.6/site-packages/tensorflow/contrib/lite/python/interpreter_wrapper/tensorflow_wrap_interpreter_wrapper.py", line 106, in AllocateTensors
    return _tensorflow_wrap_interpreter_wrapper.InterpreterWrapper_AllocateTensors(self)
RuntimeError: tensorflow/contrib/lite/kernels/reshape.cc:58 num_input_elements != num_output_elements (1500 != 750)Node number 14 (RESHAPE) failed to prepare.
```

**Comment by andrehentz** [comment]
Hi @zh794390558  would you be able to try again with a super recent version? I change was submitted yesterday to help check for common shape mistakes. Is your input tensor called 'input' or 'inputs'?

**Comment by zh794390558** [comment]
@andrehentz Input tensor called 'inputs', and I will try.

**Comment by andrehentz** [comment]
Note that in your first comment you had:

input_shapes={'**input**' :[5, 3000, 40, 3]}

maybe change that to **inputs**?

**Comment by zh794390558** [comment]
@andrehentz That's my fault, thx. 

```
Inputs [{'name': 'inputs', 'index': 17, 'shape': array([   5, 2000,   40,    3], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0)}]
Outputs [{'name': 'softmax_output', 'index': 22, 'shape': array([5, 2], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0)}]
Inputs [{'name': 'inputs', 'index': 17, 'shape': array([   2, 2000,   40,    3], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0)}]
Traceback (most recent call last):
  File "tflite_run.py", line 15, in <module>
    interpreter.allocate_tensors()
  File "/nfs/project/tools/anaconda3/envs/tf1.12_py3.5/lib/python3.6/site-packages/tensorflow/contrib/lite/python/interpreter.py", line 71, in allocate_tensors
    return self._interpreter.AllocateTensors()
  File "/nfs/project/tools/anaconda3/envs/tf1.12_py3.5/lib/python3.6/site-packages/tensorflow/contrib/lite/python/interpreter_wrapper/tensorflow_wrap_interpreter_wrapper.py", line 106, in AllocateTensors
    return _tensorflow_wrap_interpreter_wrapper.InterpreterWrapper_AllocateTensors(self)
RuntimeError: tensorflow/contrib/lite/kernels/reshape.cc:58 num_input_elements != num_output_elements (786000 != 1965000)Node number 7 (RESHAPE) failed to prepare.
```

**Comment by zh794390558** [comment]
@andrehentz What's the meaning of MinMax and how to set Quantization to `1.0/128(x-127.0)`

```
inputs
Type: Uint8
[5×2000×40×3]
MinMax: [-16256, 16384]
Quantization:
128 * (x - 127)
```

**Comment by andrehentz** [comment]
They are the estimated mininum and maximum value of that tensor, usually during training. Quantization tells you how to convert from float to uint8. Note however, that you converted the model using:
  converter.quantized_input_stats={'inputs': (127, 1.0/128)}
  converter.default_ranges_stats=(0, 6)

Using default ranges is unlikely to produce an accurate model.

**Comment by mrgloom** [comment]
What does `converter.default_ranges_stats` mean?
