### ISSUE TITLE
Convert pb model to tflite model failed in docker environment

### ISSUE THREAD

**Issue by cruzsoma** [tensorflow/tensorflow#23807]
I m using the docker image pulled from here:
https://hub.docker.com/r/tensorflow/tensorflow/tags
the tag is nightly-devel-py3.
And then I upgrade the tf-nightly to  tf-nightly 1.13.0.dev20181116 using pip.

**System information**
- i7-8650U+16G+ 1060
- Windows Pro Docker Environment(CPU mode)
- tf-nightly 1.13.0.dev20181116
- Python version:

It failed when I trying to convert pb model to tflite model.
The error info says that some operators doesn't supported in the TFLiteConverter.
Can anyone help me to fix it?
Thanks.

**My Command Line**
tflite_convert --output_file='/data/fast-neural-style-train&test/models/result.tflite' --graph_def_file='/data/fast-neural-style-train&test/models/test_model.pb' --input_arrays=input --output_arrays=output_new --input_shapes=256,256,3

**Error Info**
2018-11-16 03:45:33.142433: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Traceback (most recent call last):
  File "/usr/local/bin/tflite_convert", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/lite/python/tflite_convert.py", line 421, in main
    app.run(main=run_main, argv=sys.argv[:1])
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/lite/python/tflite_convert.py", line 417, in run_main
    _convert_model(tflite_flags)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/lite/python/tflite_convert.py", line 170, in _convert_model
    output_data = converter.convert()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/lite/python/lite.py", line 456, in convert
    **converter_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/lite/python/convert.py", line 397, in toco_convert_impl
    input_data.SerializeToString())
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/lite/python/convert.py", line 172, in toco_convert_protos
    "TOCO failed. See console for info.\n%s\n%s\n" % (stdout, stderr))
tensorflow.lite.python.convert.ConverterError: TOCO failed. See console for info.
2018-11-16 03:45:34.088574: I tensorflow/lite/toco/import_tensorflow.cc:1280] Converting unsupported operation: Round
2018-11-16 03:45:34.095390: I tensorflow/lite/toco/import_tensorflow.cc:1280] Converting unsupported operation: Round
2018-11-16 03:45:34.095586: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 2
2018-11-16 03:45:34.095621: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 2
2018-11-16 03:45:34.095652: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 2
2018-11-16 03:45:34.095684: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 2
2018-11-16 03:45:34.095801: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 2
2018-11-16 03:45:34.095848: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 2
2018-11-16 03:45:34.095925: I tensorflow/lite/toco/import_tensorflow.cc:1280] Converting unsupported operation: MirrorPad
2018-11-16 03:45:34.096229: I tensorflow/lite/toco/import_tensorflow.cc:1280] Converting unsupported operation: MirrorPad
2018-11-16 03:45:34.096281: I tensorflow/lite/toco/import_tensorflow.cc:1280] Converting unsupported operation: SquaredDifference
2018-11-16 03:45:34.096329: I tensorflow/lite/toco/import_tensorflow.cc:1280] Converting unsupported operation: MirrorPad
2018-11-16 03:45:34.096374: I tensorflow/lite/toco/import_tensorflow.cc:1280] Converting unsupported operation: SquaredDifference
2018-11-16 03:45:34.096455: I tensorflow/lite/toco/import_tensorflow.cc:1280] Converting unsupported operation: MirrorPad
2018-11-16 03:45:34.096501: I tensorflow/lite/toco/import_tensorflow.cc:1280] Converting unsupported operation: SquaredDifference
2018-11-16 03:45:34.096631: I tensorflow/lite/toco/import_tensorflow.cc:1280] Converting unsupported operation: MirrorPad
2018-11-16 03:45:34.096783: I tensorflow/lite/toco/import_tensorflow.cc:1280] Converting unsupported operation: MirrorPad
2018-11-16 03:45:34.096957: I tensorflow/lite/toco/import_tensorflow.cc:1280] Converting unsupported operation: MirrorPad
2018-11-16 03:45:34.097208: I tensorflow/lite/toco/import_tensorflow.cc:1280] Converting unsupported operation: MirrorPad
2018-11-16 03:45:34.097403: I tensorflow/lite/toco/import_tensorflow.cc:1280] Converting unsupported operation: MirrorPad
2018-11-16 03:45:34.097626: I tensorflow/lite/toco/import_tensorflow.cc:1280] Converting unsupported operation: MirrorPad
2018-11-16 03:45:34.097862: I tensorflow/lite/toco/import_tensorflow.cc:1280] Converting unsupported operation: MirrorPad
2018-11-16 03:45:34.098174: I tensorflow/lite/toco/import_tensorflow.cc:1280] Converting unsupported operation: MirrorPad
2018-11-16 03:45:34.098459: I tensorflow/lite/toco/import_tensorflow.cc:1280] Converting unsupported operation: MirrorPad
2018-11-16 03:45:34.098733: I tensorflow/lite/toco/import_tensorflow.cc:1280] Converting unsupported operation: MirrorPad
2018-11-16 03:45:34.098940: I tensorflow/lite/toco/import_tensorflow.cc:1280] Converting unsupported operation: MirrorPad
2018-11-16 03:45:34.098991: I tensorflow/lite/toco/import_tensorflow.cc:1280] Converting unsupported operation: SquaredDifference
2018-11-16 03:45:34.099099: I tensorflow/lite/toco/import_tensorflow.cc:1280] Converting unsupported operation: MirrorPad
2018-11-16 03:45:34.099149: I tensorflow/lite/toco/import_tensorflow.cc:1280] Converting unsupported operation: SquaredDifference
2018-11-16 03:45:34.099194: I tensorflow/lite/toco/import_tensorflow.cc:1280] Converting unsupported operation: MirrorPad
2018-11-16 03:45:34.099242: I tensorflow/lite/toco/import_tensorflow.cc:1280] Converting unsupported operation: SquaredDifference
2018-11-16 03:45:34.100307: F tensorflow/lite/toco/tooling_util.cc:1020] Check failed: array->has_shape()
Aborted

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tofulawrence: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by autominded** [comment]
Errors are for:  convert the model into tflite compatible operations. 

My Docker file for this looks like this for comparison.

FROM python:3.6-slim
ARG UID
ARG TAG_NAME
ENV TERM linux
ENV DEBIAN_FRONTEND noninteractive
ARG proxy
ENV http_proxy $proxy
ENV https_proxy $proxy
COPY ZscalerRootCA.crt /usr/local/share/ca-certificates/
RUN chmod 644 /usr/local/share/ca-certificates/ZscalerRootCA.crt
RUN echo "check_certificate = off" >> ~/.wgetrc
#RUN apt-get install --allow-unauthenticated -y ca-certificates
#RUN update-ca-certificates 
RUN pip install --trusted-host pypi.python.org --trusted-host pypi.org --trusted-host files.pythonhosted.org tf_nightly
RUN apt-get update && apt-get -y install ffmpeg && rm -r /var/lib/apt/lists

ADD scripts/ /usr/local/bin/scripts

RUN chmod +x /usr/local/bin/scripts/convert_quantized_tflite.py
RUN chmod +x /usr/local/bin/scripts/count_ops.py
RUN chmod +x /usr/local/bin/scripts/dump_operations.py
RUN chmod +x /usr/local/bin/scripts/evaluate.py
RUN chmod +x /usr/local/bin/scripts/graph_pb2tb.py
RUN chmod +x /usr/local/bin/scripts/hello.py
RUN chmod +x /usr/local/bin/scripts/inspect.py
RUN chmod +x /usr/local/bin/scripts/label_image.py
RUN chmod +x /usr/local/bin/scripts/post_quantize_lite.py
RUN chmod +x /usr/local/bin/scripts/quantize_graph.py
RUN chmod +x /usr/local/bin/scripts/retrain.py
RUN chmod +x /usr/local/bin/scripts/show_image.py
RUN chmod +x /usr/local/bin/scripts/__init__.py
RUN chmod +x /usr/local/bin/scripts/__init__.pyc
RUN chmod +x /usr/local/bin/scripts/retrainV2.py

WORKDIR /usr/local/bin

**Comment by MeghnaNatraj** [comment]
Marking issue as resolved due to inactivity. Feel free to re-open this if it's unresolved or file a [new issue](https://github.com/tensorflow/tensorflow/issues/new/choose)
