### ISSUE TITLE
RuntimeWarning: compiletime version 3.4 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.5; uiltins.type size changed, may indicate binary incompatibility. Expected 432, got 412

### ISSUE THREAD

**Issue by sjkim04** [tensorflow/tensorflow#23840]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template </em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Raspbian 9
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary, I think? (_pip_ installed)
- TensorFlow version (use command below): 1.11.0
- Python version: 3.5.3
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A, no GPU
- GPU model and memory: N/A, no GPU

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**
As you know with the title, when I import tensorflow in shell window, I get a warning. (See code)
**Describe the expected behavior**
I recently saw some issues, and they says that it is OK to use tensorflow with this. But my question is: <strong>how can I get rid of this?</strong>
**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
```

>>> import tensorflow as tf

Warning (from warnings module):
  File "/usr/lib/python3.5/importlib/_bootstrap.py", line 222
    return f(*args, **kwds)
RuntimeWarning: compiletime version 3.4 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.5

Warning (from warnings module):
  File "/usr/lib/python3.5/importlib/_bootstrap.py", line 222
    return f(*args, **kwds)
RuntimeWarning: builtins.type size changed, may indicate binary incompatibility. Expected 432, got 412
>>> 
```
**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by sjkim04** [comment]
I know it is good to keep going, but I want to get rid of it. OK?

**Comment by harshini-gadige** [comment]
@sjkim04   Could you please try with Python 3.6 ?

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by harshini-gadige** [comment]
Closing as this issue is in "awaiting response" status for more than 7 days and did not hear back from the user. Please post your comments if any, we will reopen. Thanks !

**Comment by pechyonkin** [comment]
This issue still persists as of April 7, 2019. I installed Raspbian and then followed the instructions as per Tensorflow installation [guide](https://www.tensorflow.org/install/pip). Then, I got this error message.

**Comment by vegeta340** [comment]
the same error on rpi 3b+ with python 3.5

**Comment by vlasov01** [comment]
I've install Python 3.6.8 (Raspbian Stretch).
And I've got these warnings as well:
/usr/local/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.4 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
/usr/local/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: builtins.type size changed, may indicate binary incompatibility. Expected 432, got 412
  return f(*args, **kwds)

**Comment by din70** [comment]
the same error on rpi 2 with python 3.5

**Comment by jingw222** [comment]
I'm on Raspbian Stretch with Python 3.6, and got thess warnings upon installing `tensorflow-1.13.1-cp36-none-linux_armv7l.whl`:
```
pi@raspberrypi:~ $ python -c "import tensorflow as tf;print(tf.reduce_sum(tf.random.normal([1000, 1000])))"
/home/pi/.pyenv/versions/3.6.8/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.4 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
/home/pi/.pyenv/versions/3.6.8/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: builtins.type size changed, may indicate binary incompatibility. Expected 432, got 412
  return f(*args, **kwds)
Tensor("Sum:0", shape=(), dtype=float32)
```

**Comment by freegroup** [comment]
I have the very same problem with the latest RaspberryPi image and tensorflow  https://www.piwheels.org/simple/tensorflow/tensorflow-1.13.1-cp27-none-linux_armv7l.whl 

```
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: compiletime version 3.4 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.5
  return f(*args, **kwds)
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: builtins.type size changed, may indicate binary incompatibility. Expected 432, got 412
  return f(*args, **kwds)
^CTraceback (most recent call last):
  File "<frozen importlib._bootstrap_external>", line 88, in _path_is_mode_type
  File "<frozen importlib._bootstrap_external>", line 82, in _path_stat
FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/.local/lib/python3.5/site-packages/gast/__init__.cpython-35m-arm-linux-gnueabihf.so'

During handling of the above exception, another exception occurred:
```

**Comment by damooooooooooh** [comment]
Any fix for this same issue as below:


```
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: compiletime version 3.4 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.5
  return f(*args, **kwds)
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: builtins.type size changed, may indicate binary incompatibility. Expected 432, got 412
  return f(*args, **kwds)
```

**Comment by freegroup** [comment]
I tested different tensorflow version on the latest raspian and I have always the same error.
(tested with tf  1.9.0, 1.10.1, 1.11.0, 1.12.0, 1.13.1)

I think the ticket should reopend...or?

**Comment by damooooooooooh** [comment]
I installed the arm6 version from here and it works on a pi zero

https://github.com/lhelontra/tensorflow-on-arm/releases/tag/v1.13.1

**Comment by freegroup** [comment]
You saved my day. Many thanks. 

But I don't understand why I have to access third party sources to install tensorflow properly on a current Raspberry. Anyway - I have a solution and am happy. Mayn thanks again to you and the
provider of the tensorflow whl

```sh
wget https://github.com/lhelontra/tensorflow-on-arm/releases/download/v1.13.1/tensorflow-1.13.1-cp35-none-linux_armv7l.whl
sudo pip3 install ./tensorflow-1.13.1-cp35-none-linux_armv7l.whl
python3 -c 'import tensorflow as tf; print(tf.__version__)'
1.13.1

```

**Comment by bennuttall** [comment]
**@everyone this is not an error it is a warning. Tensorflow still works.**

**Comment by fabge** [comment]
@bennuttall I think this is more than a warning, right?

If you look at @jingw222 's log, it says:
`pi@raspberrypi:~ $ python -c "import tensorflow as tf;print(tf.reduce_sum(tf.random.normal([1000, 1000])))"
/home/pi/.pyenv/versions/3.6.8/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.4 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
/home/pi/.pyenv/versions/3.6.8/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: builtins.type size changed, may indicate binary incompatibility. Expected 432, got 412
  return f(*args, **kwds)
Tensor("Sum:0", shape=(), dtype=float32)`

A sum of 0 doesn't seem right to me. I get the exact same error.

**Comment by bennuttall** [comment]
> @bennuttall I think this is more than a warning, right?

```
RuntimeWarning: compiletime version 3.4 of module
```

You can turn warnings off: `python -W ignore -c "import tensorflow"`

> A sum of 0 doesn't seem right to me. I get the exact same error.

That's not output, that's the stack trace.

If Tensorflow isn't working for you. I'd suggest showing code examples.
