### ISSUE TITLE
Error occurs when importing metagraph that contains cudnnRNN cells

### ISSUE THREAD

**Issue by sjtuldl** [tensorflow/tensorflow#23898]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS 7.4
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pip install .whl
- TensorFlow version (use command below): 1.12.0
- Python version: 2.7.14
- Bazel version (if compiling from source): 
- GCC/Compiler version (if compiling from source): c++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-28)
- CUDA/cuDNN version: cuda: 9.0 cuDNN: 7.1.3
- GPU model and memory: GTX1050Ti/4GB
[tf_env.txt](https://github.com/tensorflow/tensorflow/files/2603030/tf_env.txt)

**Describe the current behavior**
I try to import graph from a MetaGraphDef proto that contains a CudnnRNN cell, the error below raises:

```
 Traceback (most recent call last):
  File "test.py", line 21, in <module>
    saver = tf.train.import_meta_graph(mgd)
  File "/root/anaconda2/envs/tf12/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1674, in import_meta_graph
    meta_graph_or_file, clear_devices, import_scope, **kwargs)[0]
  File "/root/anaconda2/envs/tf12/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1696, in _import_meta_graph_with_return_elements
    **kwargs))
  File "/root/anaconda2/envs/tf12/lib/python2.7/site-packages/tensorflow/python/framework/meta_graph.py", line 852, in import_scoped_meta_graph_with_return_elements
    ops.prepend_name_scope(value, scope_to_prepend_to_names))
  File "/root/anaconda2/envs/tf12/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3490, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/root/anaconda2/envs/tf12/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3550, in _as_graph_element_locked
    "graph." % repr(name))
KeyError: "The name 'cudnn_lstm/opaque_kernel_saveable' refers to an Operation not in the graph."
```

What I've done:
I've debuged the souce code and found out that a CudnnLSTMSaveable instance is created when cudnnRNN cell gets called and corresponding op was saved in tf.GraphKeys.SAVEABLE_OBJECTS collections with the name "cudnn_lstm/opaque_kernel_saveable".
when executing saver.import_meta_graph, in saver.save_op(line 189 of saver.py) function the saveable object mentioned above is somehow transfered into "cudnn_lstm/rnn/multi_rnn_cell/cell_0/cudnn_compatible_lstm_cell/kernel" and "cudnn_lstm/rnn/multi_rnn_cell/cell_0/cudnn_compatible_lstm_cell/bias" and gets saved. But the op named "cudnn_lstm/opaque_kernel_saveable" didn't gets saved. I'm wandering if this is a bug.

**Describe the expected behavior**
graph gets imported

**Code to reproduce the issue**
```
import tensorflow as tf
import numpy as np
num_layers = 1
num_units = 128
direction = "unidirectional"
inputs    = tf.placeholder(tf.float32, [None, None, 32], name="inputs")
convolved = tf.transpose(inputs, [1, 0, 2])

lstm      =  tf.contrib.cudnn_rnn.CudnnLSTM(num_layers, num_units, direction=direction)
outputs, output_states = lstm(convolved, training=True)
enc_output = tf.transpose(outputs, [1, 0, 2])
optimizer  = tf.train.AdamOptimizer(0.001)
optim = optimizer.minimize(enc_output)
saver     = tf.train.Saver()
init      = tf.global_variables_initializer()
with tf.Session() as session:
    session.run(init)
    # export MetaGraphDef proto to mgd
    mgd=saver.export_meta_graph()
with tf.Session(graph=tf.Graph()) as session:
    # import graph from mgd on another graph
    saver = tf.train.import_meta_graph(mgd)
```

**Comment by andrhua** [comment]
Getting the same issue while loading SavedModel with cudnn_lstm layer inside. I thought maybe I need to prune these nodes, but when I inspected graph with tensorboard it couldn't find any! Moreover, due to the same issue it's impossible to launch Graph Transform Tool on it. 
I think I'm close as never before to one more one-layer perceptron for university exam project...

**Comment by aslihn** [comment]
I'm struggling with the same issue. I have saved my network using CudnnLSTM.

`cudnn_lstm =tf.contrib.cudnn_rnn.CudnnLSTM(num_layers=2, num_units=36, dtype=tf.float32)  `

After that, using the code seen below, I'm trying to restore variables like input placeholder or accuracy.

`graph = tf.Graph()
with tf.Graph().as_default(), tf.device('/gpu:0'):
    with tf.Session() as sess:
        saver = tf.train.import_meta_graph('checkpoints/lstm.ckpt.meta')
        saver.restore(sess, tf.train.latest_checkpoint('checkpoints/.'))  

        input = graph.get_tensor_by_name('inputs:0')`
But I get this error, " The name 'cudnn_lstm/opaque_kernel_saveable' refers to an Operation not in the graph'.

**Comment by aslihn** [comment]
I'm struggling with the same problem. I'have saved my network with using CudnnLstm ;
`cudnn_lstm = tf.contrib.cudnn_rnn.CudnnLSTM(num_layers=2, num_units=36, dtype=tf.float32)`

I saved it in a checkpoint file. After that, using the code seen below, I'm trying to restore variables like input placeholder or accuracy.
```python
graph = tf.Graph()
with tf.Session(graph=graph) as sess:
    saver = tf.train.import_meta_graph('checkpoints-cnn/har.ckpt.meta')
    saver.restore(sess, tf.train.latest_checkpoint('checkpoints-cnn/.'))

    input = graph.get_tensor_by_name('inputs:0')
```
But I get this error " The name 'cudnn_lstm/opaque_kernel_saveable' refers to an Operation not in the graph'

**Comment by shahinkl** [comment]
Any update on this issue? Really stuck at this point.

**Comment by pmusta** [comment]
@protoget Anything new? I'm getting this exact same error but with cudnn_gru,
" The name 'cudnn_gru/opaque_kernel_saveable' refers to an Operation not in the graph'

**Comment by brennenhuang** [comment]
@protoget Anything new? I have the same problem

**Comment by sathyamoorthyrr** [comment]
When does **KeyError:The name 'something' refers to an Operation not in the graph** occur. facing similar issue. What operation is being performed(possibly in ops.py) that leads to this error?
Also, kindly look [this](https://github.com/tensorflow/tensorflow/pull/12759#issuecomment-467860111)

**Comment by shahinkl** [comment]
As a temporary work around I used tf.keras.layers.CuDNNLSTM to build my RNN layers.

**Comment by brennenhuang** [comment]
@shahinkl  I solved it, you should rebuild model and restore ckpt instead of using  import_meta_graph

**Comment by shahinkl** [comment]
@brennenhuang
We know it will work with restore ckpt. That is why we are able to do validation and testing while training the graph. We face the issue while exporting and deploying the saved_model

**Comment by sabrina-su** [comment]
Anything new? I have the same problem

**Comment by nl** [comment]
Same issue here. Any pointers?

**Comment by o20021106** [comment]
Same issue here

**Comment by corynezin** [comment]
Same issue

**Comment by clarkzhao** [comment]
same issue

**Comment by JOJORice** [comment]
same issue, any update?

**Comment by nmatare** [comment]
bump, same issue @drpngx @protoget

**Comment by sparkingarthur** [comment]
> As a temporary work around I used tf.keras.layers.CuDNNLSTM to build my RNN layers.

how to do this with eager execution off??

**Comment by HuizhenShu** [comment]
same issue, any update?

**Comment by wangye8899** [comment]
same issue,solved?

**Comment by HuizhenShu** [comment]
Using tensorflow serving to deploy metagraphdef proto does not have this issue

**Comment by zqlao** [comment]
same issue, any possible solution?

**Comment by mofeiyu** [comment]
I solve it like that:

`model = Autoencoder()
saver = tf.train.Saver(max_to_keep=5)
self.sess = tf.Session()
ckpt = tf.train.latest_checkpoint(self.checkpoints)
saver.restore(self.sess, ckpt)`

**Comment by zhufeijuanjuan** [comment]
same issue when importing graph from .meta file by using tf.train.import_meta_graph？ tensorflow version==1.14.0, looking forward to solve.

**Comment by wangxiang2713** [comment]
same issue, any possible solution?

**Comment by wangxiang2713** [comment]
I find this problem is because one node named 'cudnn_lstm/opaque_kernel_saveable' was added to graph.collection['saveable_objects'] but this node not added to saved model.
when i build saved model, i run print(sess.graph.get_collection('saveable_objects')), then i got:
[<tensorflow.contrib.cudnn_rnn.python.ops.cudnn_rnn_ops.CudnnLSTMSaveable object at 0x7fd0881535d0>]
so, i try this before building saved model: sess.graph.clear_collection('saveable_objects'), then i can restore saved model.
However, i am not sure whether this is right, and i can only delete all nodes in graph.collection['saveable_objects'], how can i only delete the node 'cudnn_lstm/opaque_kernel_saveable'?

**Comment by zhufeijuanjuan** [comment]
> I find this problem is because one node named 'cudnn_lstm/opaque_kernel_saveable' was added to graph.collection['saveable_objects'] but this node not added to saved model.
> when i build saved model, i run print(sess.graph.get_collection('saveable_objects')), then i got:
> [<tensorflow.contrib.cudnn_rnn.python.ops.cudnn_rnn_ops.CudnnLSTMSaveable object at 0x7fd0881535d0>]
> so, i try this before building saved model: sess.graph.clear_collection('saveable_objects'), then i can restore saved model.
> However, i am not sure whether this is right, and i can only delete all nodes in graph.collection['saveable_objects'], how can i only delete the node 'cudnn_lstm/opaque_kernel_saveable'?



> same issue, any possible solution?

i used keras.layers.CuDNNLSTM (tensorflow version:1.14) to avoid this issue

**Comment by wangxiang2713** [comment]
Update, i find the codes add node named 'cudnn_lstm/opaque_kernel_saveable' to graph.collection['saveable_objects'] in /usr/lib64/python2.7/site-packages/tensorflow_core/contrib/cudnn_rnn/python/layers/cudnn_rnn.py L372-L373(Tensorflow 1.15):
```
# Create saveable in the outer scope of the cudnn subgraph, such that
# alternative subgraph with platform-independent rnn cells can load the
# checkpoints directly.
if not (self.built or vs.get_variable_scope().reuse is True):
    self._create_saveable()
```

So i delete them to slove this problem.

**Comment by iamlockelightning** [comment]
same issue, any possible solution?

**Comment by mohantym** [comment]
@sjtuldl !
It seems you are using older versions(1.x versions) of Tensorflow which is not supported any more. We recommend that you upgrade to 2.8.0 and let us know if the issue still persists in newer versions .Thanks!

**Comment by mohantym** [comment]
@sjtuldl !
It seems you are using older versions(1.x versions) of Tensorflow which is not supported any more. We recommend that you upgrade to 2.8.0 and let us know if the issue still persists in newer versions .Thank you!
