### ISSUE TITLE
Error after correct (or so i suppose) installation, but nothing seems to work when i try to run "import tensorflow as tf"

### ISSUE THREAD

**Issue by EMJzero** [tensorflow/tensorflow#23905]
**System information**
- Windows 7 64bits (service pack 1) on AMD FX-8320E
- TensorFlow 1.12.0 (https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.12.0-cp36-cp36m-win_amd64.whl)
- Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 64 bit (AMD64)] on win32
- Installed using pip
- GTX 750 ti 2GB (not relevant cause i'm using the CPU only version)

After a fresh install of tensorflow after getting other problems for a few times, i get this log when running a simple.py with just the line "import tensorflow as tf", the console log is the following:

`Traceback (most recent call last):
  File "C:\Users\marco\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\marco\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\marco\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\marco\AppData\Local\Programs\Python\Python37\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\marco\AppData\Local\Programs\Python\Python37\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: Impossibile trovare il modulo specificato.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\marco\Desktop\This is a test!.py", line 1, in <module>
    import tensorflow as tf
  File "C:\Users\marco\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\marco\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\marco\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\marco\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\marco\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\marco\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\marco\AppData\Local\Programs\Python\Python37\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\marco\AppData\Local\Programs\Python\Python37\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: Impossibile trovare il modulo specificato.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.`

**Comment by harshini-gadige** [comment]
@EMJzero Hi, this could be due to Python 3.7.
We are maintaining a single issue i.e #20517 to track tensorflow compatibility and import errors with Python 3.7. Request you to refer it and post your comments there. Thank you !

**Comment by 392781** [comment]
@harshini-gadige Is there an ETA?  What are the issues with compatibility?

**Comment by harshini-gadige** [comment]
> @harshini-gadige Is there an ETA? What are the issues with compatibility?

I mean, tensorflow with Python 3.7. Did you get a chance to go through #20517 ?

**Comment by 392781** [comment]
@harshini-gadige Ran through it.  It's probably above my knowledge and/or I'm not seeing what the problems are.

**Comment by EMJzero** [comment]
One more thing....the error which came out in the #20517 isn’t the same of mine...i think because of Windows behaving differently than MAC OS, but that still seems to me a different thing! Mah e cause of something which isn’t just due to Python 3.7!

**Comment by harshini-gadige** [comment]
@gunan

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
