### ISSUE TITLE
TF-lite not supported Abs, ResizeNearestNeighbor？？

### ISSUE THREAD

**Issue by ToBigboss** [tensorflow/tensorflow#23937]
super@super-virtual-machine:~/Downloads/Onet-TF_to_caffe$ tflite_convert \
>   --output_file=/home/super/Downloads/Onet-TF_to_caffe/align.tflite \
>   --graph_def_file=/home/super/Downloads/Onet-TF_to_caffe/frozen_model.pb \
>   --input_arrays=alignmentnet/inputs \
>   --output_arrays=alignmentnet/add
2018-11-23 18:02:52.499590: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Traceback (most recent call last):
  File "/home/super/.local/bin/tflite_convert", line 11, in <module>
    sys.exit(main())
  File "/home/super/.local/lib/python2.7/site-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 412, in main
    app.run(main=run_main, argv=sys.argv[:1])
  File "/home/super/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/home/super/.local/lib/python2.7/site-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 408, in run_main
    _convert_model(tflite_flags)
  File "/home/super/.local/lib/python2.7/site-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 162, in _convert_model
    output_data = converter.convert()
  File "/home/super/.local/lib/python2.7/site-packages/tensorflow/contrib/lite/python/lite.py", line 453, in convert
    **converter_kwargs)
  File "/home/super/.local/lib/python2.7/site-packages/tensorflow/contrib/lite/python/convert.py", line 342, in toco_convert_impl
    input_data.SerializeToString())
  File "/home/super/.local/lib/python2.7/site-packages/tensorflow/contrib/lite/python/convert.py", line 135, in toco_convert_protos
    (stdout, stderr))
RuntimeError: TOCO failed see console for info.
2018-11-23 18:02:54.114501: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Abs
2018-11-23 18:02:54.114680: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Abs
2018-11-23 18:02:54.114763: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Abs
2018-11-23 18:02:54.114819: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Abs
2018-11-23 18:02:54.114875: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Abs
2018-11-23 18:02:54.114933: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Abs
2018-11-23 18:02:54.115020: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Abs
2018-11-23 18:02:54.115154: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Abs
2018-11-23 18:02:54.115213: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: ResizeNearestNeighbor
2018-11-23 18:02:54.115265: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Abs
2018-11-23 18:02:54.115308: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: ResizeNearestNeighbor
2018-11-23 18:02:54.115341: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Abs
2018-11-23 18:02:54.115377: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Abs
2018-11-23 18:02:54.123507: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Abs
2018-11-23 18:02:54.125172: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 162 operators, 227 arrays (0 quantized)
2018-11-23 18:02:54.126147: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 162 operators, 227 arrays (0 quantized)
2018-11-23 18:02:54.128320: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 1: 101 operators, 163 arrays (0 quantized)
2018-11-23 18:02:54.149382: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 2: 100 operators, 162 arrays (0 quantized)
2018-11-23 18:02:54.150311: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 3: 99 operators, 160 arrays (0 quantized)
2018-11-23 18:02:54.151169: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before dequantization graph transformations: 99 operators, 160 arrays (0 quantized)
2018-11-23 18:02:54.152134: I tensorflow/contrib/lite/toco/allocate_transient_arrays.cc:345] Total transient array allocated size: 2032128 bytes, theoretical optimal value: 2032128 bytes.
2018-11-23 18:02:54.152627: F tensorflow/contrib/lite/toco/tflite/export.cc:386] Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.contrib.lite.TFLiteConverter(). Here is a list of operators for which  you will need custom implementations: Abs, ResizeNearestNeighbor.
Aborted (core dumped)

**Comment by aselle** [comment]
ResizeNearesetNeighbor neighbor has been added (try the nightly or source). Abs is  currently being worked on internally and should hopefully land in a few days.

In the meantime you can try TensorFlow Lite with Select TensorFlow ops
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/using_select_tf_ops.md

**Comment by ToBigboss** [comment]
@aselle, Thank you for your reply, Now, I can build .tflite file using select_tf_ops

**Comment by youyou22222** [comment]
> @aselle, Thank you for your reply, Now, I can build .tflite file using select_tf_ops

hi, I met the same problem, how do you solve it?

**Comment by malgo1311** [comment]
@aselle What do you mean by 'try the nightly or source'? Am getting an error for ResizeNearesetNeighbor. I am using Tensorflow 1.12
