### ISSUE TITLE
Failed to load the native TensorFlow runtime.

### ISSUE THREAD

**Issue by mantues** [tensorflow/tensorflow#23930]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

Hi!
I worked with Tensorflow on without GPU. No I'm trying to run it on a device with following specs.
 I have get the follow error message, how I can solve it?

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Windows 10 Home
- Mobile device : ThinkPad X1 Yoga 1st, Intel(R)Core(TM)i7-6500U CPU@2.50GHz 2.59GHz
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.9.0
- Python version: 3.7.0

**Describe the problem**

ImportError: Traceback (most recent call last):
  File "C:\Users\y_pas\python\Anaconda3\envs\tensor\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\y_pas\python\Anaconda3\envs\tensor\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\y_pas\python\Anaconda3\envs\tensor\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\y_pas\python\Anaconda3\envs\tensor\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\y_pas\python\Anaconda3\envs\tensor\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: 指定されたモジュールが見つかりません。

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by byronyi** [comment]
Could you try to install the binary version from pip/conda? Thanks!
