### ISSUE TITLE
Tensorflow dense_image_warp Failed to convert object of type <type 'list'> to Tensor

### ISSUE THREAD

**Issue by crvogt** [tensorflow/tensorflow#23952]
Using up-to-date Keras and Tensorflow r1.12 on Ubuntu 16.04 and 14.04. For the following code:
   
    img2D = Input(shape=(100, 100, 3))
    refPosX = Input(shape=(100, 100, 1))
    refPosY = Input(shape=(100, 100, 1))

    depth_map = depth_net(dFeatures)
    curX = tf.multiply(depth_map, refPosX)
    curY = tf.multiply(depth_map, refPosY)
    dMove = tf.concat([curX, curY], axis=3)

    warped = tfc.image.dense_image_warp(img2D, dMove)

I'm receiving the error output:

    Using TensorFlow backend.
    Traceback (most recent call last):
    File "/home/carson/ws/dla/test_network_5/depth_and_color_nets.py", line 89, in <module>
    File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/image/python/ops/dense_image_warp.py", line 195, in dense_image_warp
    [batch_size, height * width, 2])
     File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 6482, in reshape
    "Reshape", tensor=tensor, shape=shape, name=name)
    File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 513, in _apply_op_helper
    raise err
    TypeError: Failed to convert object of type <type 'list'> to Tensor. Contents: [None, 10000, 2]. Consider casting elements to a supported type.

This seems to only be happening with this function, so unless I've missed something in the documentation, I'm not sure what's going on here :/

**Comment by crvogt** [comment]
So, I've tracked it so far just to array_ops (from tensorflow.python.ops import array_ops)

    batch_size, height, width, channels = img2D.get_shape().as_list()
    query_flat = array_ops.reshape(img2D, (batch_size, height*width, 2))

This returns the same error, but the type is now of course of type 'tuple' that throws the error. I don't quite understand what's happening in the reshape function in array ops.

**Comment by crvogt** [comment]
Now I've noticed that the most recent version of dense_image_warp changes the way in which shapes are obtained, going from 

    batch_size, height, width, channels = image.get_shape().as_list()

to 

    batch_size, height, width, channels = (array_ops.shape(image)[0],
                                  array_ops.shape(image)[1],
                                  array_ops.shape(image)[2],
                                  array_ops.shape(image)[3])

However, no shapes seem to be returned... just (?, ?, ?, ?)

**Comment by crvogt** [comment]
Got it, define batch_shape. :/
