### ISSUE TITLE
ImportError: cannot import name cloud

### ISSUE THREAD

**Issue by Nayana-ibm** [tensorflow/tensorflow#23976]
**System information**

    OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04, 18.04 s390x
    Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
    TensorFlow installed from (source or binary): source
    TensorFlow version: v1.12.0
    Python version: 2.7.x
    Installed using virtualenv? pip? conda?: Building from source
    Bazel version (if compiling from source): v0.15.0
    GCC/Compiler version (if compiling from source): 7.3.0 (Ubuntu 18.04)
    CUDA/cuDNN version: NA
    GPU model and memory: NA

**Describe the problem**

We have build TensorFlow v1.12.0 from source on Ubuntu 16.04, 18.04 on s390x platform. Observed test failures with an error: "ImportError: cannot import name cloud"

**Comment by Nayana-ibm** [comment]
For v1.12.0, we have disabled Apache Ignite support throgh ./configure and could build TensorFlow

`./configure`
```
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
You have bazel 0.15.0- (@non-git) installed.
Please specify the location of python. [Default is /usr/bin/python]:


Found possible Python library paths:
  /usr/local/lib/python2.7/dist-packages
  /usr/lib/python2.7/dist-packages
Please input the desired Python library path to use.  Default is [/usr/local/lib/python2.7/dist-packages]

Do you wish to build TensorFlow with Apache Ignite support? [Y/n]: N
No Apache Ignite support will be enabled for TensorFlow.

Do you wish to build TensorFlow with XLA JIT support? [Y/n]: N
No XLA JIT support will be enabled for TensorFlow.

Do you wish to build TensorFlow with OpenCL SYCL support? [y/N]: N
No OpenCL SYCL support will be enabled for TensorFlow.

Do you wish to build TensorFlow with ROCm support? [y/N]: N
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: N
No CUDA support will be enabled for TensorFlow.

Do you wish to download a fresh release of clang? (Experimental) [y/N]: N
Clang will not be downloaded.

Do you wish to build TensorFlow with MPI support? [y/N]: N
No MPI support will be enabled for TensorFlow.

Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native]:


Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]: N
Not configuring the WORKSPACE for Android builds.

Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See tools/bazel.rc for more details.
        --config=mkl            # Build with MKL support.
        --config=monolithic     # Config for mostly static monolithic build.
        --config=gdr            # Build with GDR support.
        --config=verbs          # Build with libverbs support.
        --config=ngraph         # Build with Intel nGraph support.
Configuration finished
```
**Executed tests using command:** 
`bazel --host_jvm_args="-Xms512m" --host_jvm_args="-Xmx1024m" test --test_timeout 300,450,1200,3600 --build_tests_only -- //tensorflow/... -//tensorflow/compiler/... -//tensorflow/core/platform/cloud/... -//tensorflow/contrib/lite/... -//tensorflow/contrib/cloud/... -//tensorflow/java/... `

* Excluding` //tensorflow/java` as it fails with an error '`Building Java resource jar failed`' [#19770]
* Excluding `//tensorflow/core/platform/cloud/` and `//tensorflow/contrib/cloud/` as it gives Boringssl issue for s390x. 

Howerver few tests are failing with an error:  `ImportError:   cannot import name cloud`

Failing Tests : 
```
//tensorflow/contrib/sparsemax:sparsemax_loss_test                      
//tensorflow/contrib/sparsemax:sparsemax_test                           
//tensorflow/contrib/timeseries/examples:known_anomaly_test            
//tensorflow/contrib/timeseries/examples:lstm_test                      
//tensorflow/contrib/timeseries/examples:multivariate_test              
//tensorflow/contrib/timeseries/examples:predict_test                   

All tests from //tensorflow/contrib/eager/python
```

**Comment by Nayana-ibm** [comment]
Could you please let us know if we need to enable some features here? Or any package to install.

**Comment by harshini-gadige** [comment]
@gunan  -  As per the chat in #23758, could you please post which commit fixes this issue ?

**Comment by gunan** [comment]
I think the same commits mentioned in #23771 should fix this
https://github.com/tensorflow/tensorflow/commit/3437098ba5b111817ef6ac5906d86934168704b7 and https://github.com/tensorflow/tensorflow/commit/3914ff714ba4561ecff329012d02c3de027ee4a5

**Comment by Nayana-ibm** [comment]
@gunan Thanks for your inputs. 
Today I have built master branch with steps mentioned in my earlier [comment](https://github.com/tensorflow/tensorflow/issues/23976#issuecomment-441598067)  , however facing same issue. 
Test `//tensorflow/contrib/eager/python/examples/densenet:densenet_test `failed with an error 
```
Traceback (most recent call last):
  File "/execroot/org_tensorflow/bazel-out/s390x-opt/bin/tensorflow/contrib/eager/python/examples/densenet/densenet_test.runfiles/org_tensorflow/tensorflow/contrib/eager/python/examples/densenet/densenet_test.py", line 24, in <module>
    import tensorflow.contrib.eager as tfe
  File "/execroot/org_tensorflow/bazel-out/s390x-opt/bin/tensorflow/contrib/eager/python/examples/densenet/densenet_test.runfiles/org_tensorflow/tensorflow/contrib/__init__.py", line 30, in <module>
    from tensorflow.contrib import cloud
ImportError: cannot import name cloud
```

**Comment by Nayana-ibm** [comment]
@gunan Could you please  suggest some workaround here?

**Comment by gunan** [comment]
I think we need to change this line to add checks for platform s390x:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/__init__.py#L29

Would you like to create a PR and assign it to me?

**Comment by Nayana-ibm** [comment]
@gunan Created a PR #24201 . Could you please review

**Comment by Nayana-ibm** [comment]
Closing this issue as https://github.com/tensorflow/tensorflow/pull/24201 is merged

**Comment by Nayana-ibm** [comment]
Thanks @gunan @meteorcloudy

**Comment by erwa** [comment]
This still seems to be an issue in the latest 1.13.1 and trunk code. If you build TF from source with `--nogcp`, that causes `tensorflow/contrib/cloud` NOT to be added to the pip package, but `tensorflow/contrib/__init__.py` will still try to run `from tensorflow.contrib import cloud`, which leads to the `ImportError: cannot import name 'cloud'` error.

**Comment by ppwwyyxx** [comment]
I'm running in the same issue, building TF r1.14 with the following flags:
```
--config=xla --config=mkl --config=noaws --config=nogcp --config=nohdfs --config=nokafka --config=noignite --config=numa
```
I can confirm that after I install the wheel I built, there is no "contrib/cloud" directory. Likely because I built it with nogcp.

@gunan
