### ISSUE TITLE
imac install failed.

### ISSUE THREAD

**Issue by brucewoo** [tensorflow/tensorflow#2398]
Installing collected packages: protobuf, wheel, numpy, tensorflow
  Found existing installation: numpy 1.8.0rc1
    DEPRECATION: Uninstalling a distutils installed project (numpy) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling numpy-1.8.0rc1:
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/req/req_set.py", line 736, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/req/req_install.py", line 742, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/tmp/pip-hgaRu9-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/numpy-1.8.0rc1-py2.7.egg-info'

**Comment by mrry** [comment]
It looks like the `pip` is trying to remove am old version of a system library. To avoid version clashes, we recommend that you follow the [virtualenv installation instructions](https://www.tensorflow.org/versions/r0.8/get_started/os_setup.html#virtualenv-installation).

**Comment by kiddjacky** [comment]
I got the same error, and even with virtualenv, I have the same error too. Any idea how to work around? Thanks,

**Comment by mrry** [comment]
One [suggestion from the FAQ](https://www.tensorflow.org/versions/r0.8/get_started/os_setup.html#mac-os-x-oserror-errno-1-operation-not-permitted) is to use the `--ignore-installed` flag when running `pip install`. Depending on the error message, you may need to pass `--ignore-installed six` or `--ignore-installed numpy` to ignore the appropriate package.

**Comment by pradeepprakhar** [comment]
@mrry it worked for me

**Comment by coreation** [comment]
@mrry worked for by adding the --ignore-installed numpy, but then when I try to run the test example (https://www.tensorflow.org/versions/r0.11/get_started/os_setup.html#test-the-tensorflow-installation) and try to import the tf library I get this

```
RuntimeError: module compiled against API version 0xa but this version of numpy is 0x9
```

Which is indeed what was done adding the --ignore option, ignoring the existing numpy version? I'm completely new to python, so you'll have to excuse any straight forward problems I can't see :).

**Comment by mrry** [comment]
@coreation It sounds like your version of NumPy is older than the version that TensorFlow requires (I think it's 0.10 or 0.11). If you upgrade your local version of NumPy (which may be easier to do in a virtualenv), TensorFlow should work.

**Comment by coreation** [comment]
@mrry ended up following the pip3 approach which worked very smoothly, thanks!
