### ISSUE TITLE
train.init_from_checkpoint does not support mirrorredStrategy and CollectiveAllReduceStrategy

### ISSUE THREAD

**Issue by libliang** [tensorflow/tensorflow#23986]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
   We are changing some code in https://github.com/google-research/bert run_classifier.py to make it can be run on machine with multiple GPUs

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
  Distributor ID:	Ubuntu
  Description:	Ubuntu 16.04.5 LTS
  Release:	16.04
  Codename:	xenial

- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
  NA

- TensorFlow installed from (source or binary):
  binary

- TensorFlow version (use command below):
  v1.11.0-0-gc19e29306c. and v1.12.0-0-ga6d8ffae09
- Python version:
  2.7.12

- Bazel version (if compiling from source):
  NA

- GCC/Compiler version (if compiling from source):
  NA

- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**
In Bert's source code, it will call tf.train.init_from_checkpoint(init_checkpoint, assignment_map) in the model_fn

we change some of the Bert's source code to make it can run on mirroredStrategy mode, but we met a failure with the call stack as below:

Traceback (most recent call last):
  File "run_classifier_collect.py", line 859, in <module>
    tf.app.run()
  File "/data/anaconda2/envs/py27tf12/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "run_classifier_collect.py", line 815, in main
    tf.estimator.train_and_evaluate(estimator, train_spec, eval_spec)
  File "/data/anaconda2/envs/py27tf12/lib/python2.7/site-packages/tensorflow/python/estimator/training.py", line 462, in train_and_evaluate
    estimator, train_spec, eval_spec, _TrainingExecutor)
  File "/data/anaconda2/envs/py27tf12/lib/python2.7/site-packages/tensorflow/python/distribute/estimator_training.py", line 279, in train_and_evaluate
    session_config=run_config.session_config)
  File "/data/anaconda2/envs/py27tf12/lib/python2.7/site-packages/tensorflow/python/distribute/distribute_coordinator.py", line 792, in run_distribute_coordinator
    task_id, session_config, rpc_layer)
  File "/data/anaconda2/envs/py27tf12/lib/python2.7/site-packages/tensorflow/python/distribute/distribute_coordinator.py", line 344, in _run_single_worker
    worker_fn(strategy)
  File "/data/anaconda2/envs/py27tf12/lib/python2.7/site-packages/tensorflow/python/distribute/estimator_training.py", line 246, in _worker_fn
    hooks=hooks)
  File "/data/anaconda2/envs/py27tf12/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2409, in train
    rendezvous.raise_errors()
  File "/data/anaconda2/envs/py27tf12/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/error_handling.py", line 128, in raise_errors
    six.reraise(typ, value, traceback)
  File "/data/anaconda2/envs/py27tf12/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2403, in train
    saving_listeners=saving_listeners
  File "/data/anaconda2/envs/py27tf12/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 354, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/data/anaconda2/envs/py27tf12/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 1205, in _train_model
    return self._train_model_distributed(input_fn, hooks, saving_listeners)
  File "/data/anaconda2/envs/py27tf12/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 1316, in _train_model_distributed
    self.config)
  File "/data/anaconda2/envs/py27tf12/lib/python2.7/site-packages/tensorflow/python/training/distribute.py", line 721, in call_for_each_tower
    return self._call_for_each_tower(fn, *args, **kwargs)
  File "/data/anaconda2/envs/py27tf12/lib/python2.7/site-packages/tensorflow/contrib/distribute/python/mirrored_strategy.py", line 556, in _call_for_each_tower
    return _call_for_each_tower(self, fn, *args, **kwargs)
  File "/data/anaconda2/envs/py27tf12/lib/python2.7/site-packages/tensorflow/contrib/distribute/python/mirrored_strategy.py", line 183, in _call_for_each_tower
    coord.join(threads)
  File "/data/anaconda2/envs/py27tf12/lib/python2.7/site-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/data/anaconda2/envs/py27tf12/lib/python2.7/site-packages/tensorflow/python/training/coordinator.py", line 297, in stop_on_exception
    yield
  File "/data/anaconda2/envs/py27tf12/lib/python2.7/site-packages/tensorflow/contrib/distribute/python/mirrored_strategy.py", line 177, in _call_for_each_tower
    **merge_kwargs)
  File "/data/anaconda2/envs/py27tf12/lib/python2.7/site-packages/tensorflow/python/training/checkpoint_utils.py", line 211, in _init_from_checkpoint
    var = _collect_partitioned_variable(current_var_or_name, store_vars)
  File "/data/anaconda2/envs/py27tf12/lib/python2.7/site-packages/tensorflow/python/training/checkpoint_utils.py", line 365, in _collect_partitioned_variable
    if name + "/part_0" in all_vars:
TypeError: unsupported operand type(s) for +: 'PerDevice' and 'str'

we can see  the code in init_from_checkpoint:
  if distribution_strategy_context.get_cross_tower_context():
    _init_from_checkpoint(None, ckpt_dir_or_file, assignment_map)
  else:
    distribution_strategy_context.get_tower_context().merge_call(
        _init_from_checkpoint, ckpt_dir_or_file, assignment_map)

seems that above code goes into the merge_call version

I think init_from_checkpoint is indent to support cross_tower scenario, and seems that above code goes into the merge_call version in BERT's scenario

but the function _init_from_checkpoint does not properly handle the parameter passed across tower?
 

**Describe the expected behavior**
init_from_checkpoint can be called successfully

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
1. Modified BERT's code to make it use MirrorredStrategy
2. Modified BERT's optimization.py to make it can be run in distribution environment

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by YangXuefeng** [comment]
I have the same issue.
raceback (most recent call last):
  File "run_squad.py", line 1285, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "run_squad.py", line 1212, in main
    estimator.train(input_fn=train_input_fn, max_steps=num_train_steps)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 354, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 1205, in _train_model
    return self._train_model_distributed(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 1316, in _train_model_distributed
    self.config)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/distribute.py", line 721, in call_for_each_tower
    return self._call_for_each_tower(fn, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/distribute/python/mirrored_strategy.py", line 556, in _call_for_each_tower
    return _call_for_each_tower(self, fn, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/distribute/python/mirrored_strategy.py", line 183, in _call_for_each_tower
    coord.join(threads)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/coordinator.py", line 297, in stop_on_exception
    yield
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/distribute/python/mirrored_strategy.py", line 177, in _call_for_each_tower
    **merge_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/checkpoint_utils.py", line 213, in _init_from_checkpoint
    var = _collect_partitioned_variable(current_var_or_name, store_vars)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/checkpoint_utils.py", line 368, in _collect_partitioned_variable
    if name + "/part_0" in all_vars:
TypeError: unsupported operand type(s) for +: 'PerDevice' and 'str'


Just like libliang said, There are some problems  in checkpoint_util.py
The assignment_map arg given to init_from_checkpoint are  {str:str} type,  but it is changed to {str:Perdevice} type in _init_from_checkpoint

How to handle the restore problem for PerDevice object ?

PerDevice:{'/replica:0/task:0/device:GPU:0': 'bert/embeddings/LayerNorm/beta', '/replica:0/task:0/device:GPU:1': 'bert/embeddings/LayerNorm/beta', '/replica:0/task:0/device:GPU:2': 'bert/embeddings/LayerNorm/beta'},<class 'tensorflow.contrib.distribute.python.values.PerDevice'>

**Comment by JayYip** [comment]
Some work around is, you can first create a checkpoint with warm start from BERT using one GPU, say, train 10 steps. Then disable the scaffold(or the warm start init op) and do multiple GPU training. It's ugly, but works.

First run with single GPU:
```python
warm_start = True

def scaffold():
    init_op = tf.train.init_from_checkpoint(
        self.config.init_checkpoint, assignment_map)
    return tf.train.Scaffold(init_op)

if not warm_start:
    train_scaffold = None
else:
    train_scaffold = scaffold()
```

Second run with MirroredStrategy:
```python
warm_start = False

def scaffold():
    init_op = tf.train.init_from_checkpoint(
        self.config.init_checkpoint, assignment_map)
    return tf.train.Scaffold(init_op)

if not warm_start:
    train_scaffold = None
else:
    train_scaffold = scaffold()
```

**Comment by YangXuefeng** [comment]
> I don't think it's an issue of TensorFlow.
> An alternative solution is modify modeling.py in BERT codes, generating assignment map as string->variable format, instead of string->string.
> Specifically, change line 338 of modeling.py from `assignment_map[name]=name` to `assignment_map[name]=name_to_variable[name]`, and mirroredStrategy works well.

That's PERFECT ！Thank you.

**Comment by ohwe** [comment]
@sunyerui thanks a lot for your fix! But right after that MirroredStrategy still fails with 

`ValueError: You must specify an aggregation method to update a MirroredVariable in Tower Context"`

(here's the entire error message if needed:

`INFO:tensorflow:Error reported to Coordinator: You must specify an aggregation method to update a MirroredVariable in Tower Context.
Traceback (most recent call last):
  File "/home/borislav/tf/local/lib/python2.7/site-packages/tensorflow/python/training/coordinator.py", line 297, in stop_on_exception
    yield
  File "/home/borislav/tf/local/lib/python2.7/site-packages/tensorflow/contrib/distribute/python/mirrored_strategy.py", line 795, in run
    self.main_result = self.main_fn(*self.main_args, **self.main_kwargs)
  File "/home/borislav/tf/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2195, in _call_model_fn
    features, labels, mode, config)
  File "/home/borislav/tf/local/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 1195, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/home/borislav/tf/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2479, in _model_fn
    features, labels, is_export_mode=is_export_mode)
  File "/home/borislav/tf/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 1259, in call_without_tpu
    return self._call_model_fn(features, labels, is_export_mode=is_export_mode)
  File "/home/borislav/tf/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 1533, in _call_model_fn
    estimator_spec = self._model_fn(features=features, **kwargs)
  File "run_pretraining.py", line 179, in model_fn
    total_loss, learning_rate, num_train_steps, num_warmup_steps, use_tpu)
  File "/home/borislav/bert/optimization.py", line 77, in create_optimizer
    zip(grads, tvars), global_step=global_step)
  File "/home/borislav/bert/optimization.py", line 151, in apply_gradients
    [param.assign(next_param),
  File "/home/borislav/tf/local/lib/python2.7/site-packages/tensorflow/contrib/distribute/python/values.py", line 402, in assign
    return self._assign_func(f=assign_fn, *args, **kwargs)
  File "/home/borislav/tf/local/lib/python2.7/site-packages/tensorflow/contrib/distribute/python/values.py", line 379, in _assign_func
    raise ValueError("You must specify an aggregation method to update a "
ValueError: You must specify an aggregation method to update a MirroredVariable in Tower Context.`

**Comment by JayYip** [comment]
> @sunyerui thanks a lot for your fix! But right after that MirroredStrategy still fails with
> 
> `ValueError: You must specify an aggregation method to update a MirroredVariable in Tower Context"`
> 
> (here's the entire error message if needed:
> 
> `INFO:tensorflow:Error reported to Coordinator: You must specify an aggregation method to update a MirroredVariable in Tower Context. Traceback (most recent call last): File "/home/borislav/tf/local/lib/python2.7/site-packages/tensorflow/python/training/coordinator.py", line 297, in stop_on_exception yield File "/home/borislav/tf/local/lib/python2.7/site-packages/tensorflow/contrib/distribute/python/mirrored_strategy.py", line 795, in run self.main_result = self.main_fn(*self.main_args, **self.main_kwargs) File "/home/borislav/tf/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2195, in _call_model_fn features, labels, mode, config) File "/home/borislav/tf/local/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 1195, in _call_model_fn model_fn_results = self._model_fn(features=features, **kwargs) File "/home/borislav/tf/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2479, in _model_fn features, labels, is_export_mode=is_export_mode) File "/home/borislav/tf/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 1259, in call_without_tpu return self._call_model_fn(features, labels, is_export_mode=is_export_mode) File "/home/borislav/tf/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 1533, in _call_model_fn estimator_spec = self._model_fn(features=features, **kwargs) File "run_pretraining.py", line 179, in model_fn total_loss, learning_rate, num_train_steps, num_warmup_steps, use_tpu) File "/home/borislav/bert/optimization.py", line 77, in create_optimizer zip(grads, tvars), global_step=global_step) File "/home/borislav/bert/optimization.py", line 151, in apply_gradients [param.assign(next_param), File "/home/borislav/tf/local/lib/python2.7/site-packages/tensorflow/contrib/distribute/python/values.py", line 402, in assign return self._assign_func(f=assign_fn, *args, **kwargs) File "/home/borislav/tf/local/lib/python2.7/site-packages/tensorflow/contrib/distribute/python/values.py", line 379, in _assign_func raise ValueError("You must specify an aggregation method to update a " ValueError: You must specify an aggregation method to update a MirroredVariable in Tower Context.`

This is not related this issue. You need to re-implement the optimizer.

**Comment by libliang** [comment]
@JayYip is right, in order to use mirroredStrategy, we need to re-implement the optimizer, because the  current version of optimizer in BERT does not support merge_call, which is required by mirroredStrategy

**Comment by libliang** [comment]
Thanks @sunyerui 's solution, which can work fine in the current model_fn code, but we still need to consider one thing is, the logic in model_fn will be executed in every tower, that means the variables will be initialized the as much as the number of gpu, I suspect we still have room to do more improvement to NOT make such redundant initialization

**Comment by JayYip** [comment]
> Thanks @sunyerui 's solution, which can work fine in the current model_fn code, but we still need to consider one thing is, the logic in model_fn will be executed in every tower, that means the variables will be initialized the as much as the number of gpu, I suspect we still have room to do more improvement to NOT make such redundant initialization

Please see my comment above. I think using a session run hook to restore variables will only initialize once. Please correct me if I am wrong.

**Comment by yuefengz** [comment]
Closing this bug since the PR is merged.

**Comment by kwonmha** [comment]
@yuefengz 
I'm sorry but I changed tensorflow/python/training/checkpoint_utils.py following your PR link.
But this issue still occurs.
I didn't modify tensorflow/contrib/distribute/python/checkpoint_utils_test.py as it seems that there is no such file included in pip tensorflow-gpu.
Anything more should I do or did I do in wrong way?

**Comment by megjoshi** [comment]
which version of tensorflow has this fix? I m trying 1.12.2 but still facing same error.

**Comment by xmy7216** [comment]
Hi, some question as above. I'm trying 1.14.0, but still facing the same error.

**Comment by zhaolulul** [comment]
> > @sunyerui thanks a lot for your fix! But right after that MirroredStrategy still fails with
> > `ValueError: You must specify an aggregation method to update a MirroredVariable in Tower Context"`
> > (here's the entire error message if needed:
> > `INFO:tensorflow:Error reported to Coordinator: You must specify an aggregation method to update a MirroredVariable in Tower Context. Traceback (most recent call last): File "/home/borislav/tf/local/lib/python2.7/site-packages/tensorflow/python/training/coordinator.py", line 297, in stop_on_exception yield File "/home/borislav/tf/local/lib/python2.7/site-packages/tensorflow/contrib/distribute/python/mirrored_strategy.py", line 795, in run self.main_result = self.main_fn(*self.main_args, **self.main_kwargs) File "/home/borislav/tf/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2195, in _call_model_fn features, labels, mode, config) File "/home/borislav/tf/local/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 1195, in _call_model_fn model_fn_results = self._model_fn(features=features, **kwargs) File "/home/borislav/tf/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2479, in _model_fn features, labels, is_export_mode=is_export_mode) File "/home/borislav/tf/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 1259, in call_without_tpu return self._call_model_fn(features, labels, is_export_mode=is_export_mode) File "/home/borislav/tf/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 1533, in _call_model_fn estimator_spec = self._model_fn(features=features, **kwargs) File "run_pretraining.py", line 179, in model_fn total_loss, learning_rate, num_train_steps, num_warmup_steps, use_tpu) File "/home/borislav/bert/optimization.py", line 77, in create_optimizer zip(grads, tvars), global_step=global_step) File "/home/borislav/bert/optimization.py", line 151, in apply_gradients [param.assign(next_param), File "/home/borislav/tf/local/lib/python2.7/site-packages/tensorflow/contrib/distribute/python/values.py", line 402, in assign return self._assign_func(f=assign_fn, *args, **kwargs) File "/home/borislav/tf/local/lib/python2.7/site-packages/tensorflow/contrib/distribute/python/values.py", line 379, in _assign_func raise ValueError("You must specify an aggregation method to update a " ValueError: You must specify an aggregation method to update a MirroredVariable in Tower Context.`
> 
> This is not related to this issue. You need to re-implement the optimizer.
> 
> You can take my implementation as a reference:
> https://github.com/JayYip/bert-multiple-gpu/blob/master/src/optimizer.py

hi,could give me your optimizer?? i have same question,thank you

**Comment by zhaolulul** [comment]
> > @sunyerui thanks a lot for your fix! But right after that MirroredStrategy still fails with
> > `ValueError: You must specify an aggregation method to update a MirroredVariable in Tower Context"`
> > (here's the entire error message if needed:
> > `INFO:tensorflow:Error reported to Coordinator: You must specify an aggregation method to update a MirroredVariable in Tower Context. Traceback (most recent call last): File "/home/borislav/tf/local/lib/python2.7/site-packages/tensorflow/python/training/coordinator.py", line 297, in stop_on_exception yield File "/home/borislav/tf/local/lib/python2.7/site-packages/tensorflow/contrib/distribute/python/mirrored_strategy.py", line 795, in run self.main_result = self.main_fn(*self.main_args, **self.main_kwargs) File "/home/borislav/tf/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2195, in _call_model_fn features, labels, mode, config) File "/home/borislav/tf/local/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 1195, in _call_model_fn model_fn_results = self._model_fn(features=features, **kwargs) File "/home/borislav/tf/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2479, in _model_fn features, labels, is_export_mode=is_export_mode) File "/home/borislav/tf/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 1259, in call_without_tpu return self._call_model_fn(features, labels, is_export_mode=is_export_mode) File "/home/borislav/tf/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 1533, in _call_model_fn estimator_spec = self._model_fn(features=features, **kwargs) File "run_pretraining.py", line 179, in model_fn total_loss, learning_rate, num_train_steps, num_warmup_steps, use_tpu) File "/home/borislav/bert/optimization.py", line 77, in create_optimizer zip(grads, tvars), global_step=global_step) File "/home/borislav/bert/optimization.py", line 151, in apply_gradients [param.assign(next_param), File "/home/borislav/tf/local/lib/python2.7/site-packages/tensorflow/contrib/distribute/python/values.py", line 402, in assign return self._assign_func(f=assign_fn, *args, **kwargs) File "/home/borislav/tf/local/lib/python2.7/site-packages/tensorflow/contrib/distribute/python/values.py", line 379, in _assign_func raise ValueError("You must specify an aggregation method to update a " ValueError: You must specify an aggregation method to update a MirroredVariable in Tower Context.`
> 
> This is not related to this issue. You need to re-implement the optimizer.
> 
> You can take my implementation as a reference:
> https://github.com/JayYip/bert-multiple-gpu/blob/master/src/optimizer.py

hi,i have same question,could you give me your optimizer.py ？？ Thanks you
