### ISSUE TITLE
Problems running the image example (Python 2.7.10, PyEnv, Xubuntu 14.04 64bit)

### ISSUE THREAD

**Issue by samuell** [tensorflow/tensorflow#24]
JFYI, I'm getting the following error when trying to execute the models/image/mnist/convolutional.py example (Python 2.7.10 in PyEnv, on Xubuntu 14.04, 64bit):

```bash
[samuel site-packages]$ pwd
/home/samuel/.pyenv/versions/2.7.10/lib/python2.7/site-packages
[samuel site-packages]$ python tensorflow/models/image/mnist/convolutional.py
Traceback (most recent call last):
  File "tensorflow/models/image/mnist/convolutional.py", line 12, in <module>
    import tensorflow.python.platform
  File "/home/samuel/.pyenv/versions/2.7.10/lib/python2.7/site-packages/tensorflow/__init__.py", line 4, in <module>
    from tensorflow.python import *
  File "/home/samuel/.pyenv/versions/2.7.10/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 22, in <module>
    from tensorflow.python.client.client_lib import *
  File "/home/samuel/.pyenv/versions/2.7.10/lib/python2.7/site-packages/tensorflow/python/client/client_lib.py", line 35, in <module>
    from tensorflow.python.client.session import InteractiveSession
  File "/home/samuel/.pyenv/versions/2.7.10/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 11, in <module>
    from tensorflow.python import pywrap_tensorflow as tf_session
  File "/home/samuel/.pyenv/versions/2.7.10/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/home/samuel/.pyenv/versions/2.7.10/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
ImportError: /home/samuel/.pyenv/versions/2.7.10/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so: undefined symbol: PyUnicodeUCS4_FromStringAndSize
```

Will see if I can figure out something, but thought to report in the meanwhile.

**Comment by samuell** [comment]
Ah, great description of the problem [here](http://effbot.org/pyfaq/when-importing-module-x-why-do-i-get-undefined-symbol-pyunicodeucs2.htm).

**Comment by ebrevdo** [comment]
For now, you can build your own pip package via instructions [here](http://tensorflow.org/get_started/os_setup.md); see "Create the pip package and install".  Let us know if that doesn't work.

**Comment by samuell** [comment]
Thanks @ebrevdo! Though, building the pip package also generates an error for me:

```bash
[samuel tensorflow]$ bazel build -c opt //tensorflow/tools/pip_package:build_pip_package
........
ERROR: /home/samuel/src/tensorflow/tensorflow/tensorflow/python/BUILD:1: Extension file not found: 'google/protobuf/protobuf.bzl'.
ERROR: /home/samuel/src/tensorflow/tensorflow/tensorflow/tensorboard/BUILD:40:1: error loading package 'tensorflow/python': Extension file not found: 'google/protobuf/protobuf.bzl' and referenced by '//tensorflow/tensorboard:tensorboard'.
ERROR: Loading failed; build aborted.
INFO: Elapsed time: 1.065s
```

**Comment by vrv** [comment]
Please re-open if there's something left to diagnose here!

**Comment by FreakTheMighty** [comment]
I'm seeing what might be a related error:

`_pywrap_tensorflow.so: undefined symbol: cudnnCreate`

Full traceback

```bash
jvanderdoes@ubuntu:~/Code/tensorflow/tensorflow/models/image/imagenet$ python ./classify_image.py 
I tensorflow/stream_executor/dso_loader.cc:101] successfully opened CUDA library libcublas.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:93] Couldn't open CUDA library libcudnn.so.6.5. LD_LIBRARY_PATH: /usr/local/cuda-7.0/lib64
I tensorflow/stream_executor/cuda/cuda_dnn.cc:1382] Unable to load cuDNN DSO
I tensorflow/stream_executor/dso_loader.cc:101] successfully opened CUDA library libcufft.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:101] successfully opened CUDA library libcuda.so locally
I tensorflow/stream_executor/dso_loader.cc:101] successfully opened CUDA library libcurand.so.7.0 locally
I tensorflow/core/common_runtime/local_device.cc:40] Local device intra op parallelism threads: 2
I tensorflow/core/common_runtime/gpu/gpu_init.cc:103] Found device 0 with properties: 
name: GeForce GTX 960
major: 5 minor: 2 memoryClockRate (GHz) 1.342
pciBusID 0000:03:00.0
Total memory: 4.00GiB
Free memory: 3.91GiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:127] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_init.cc:137] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:702] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 960, pci bus id: 0000:03:00.0)
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:42] Allocating 3.62GiB bytes.
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:52] GPU 0 memory begins at 0x402780000 extends to 0x4e9f61000
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:66] Creating bin of max chunk size 1.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:66] Creating bin of max chunk size 2.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:66] Creating bin of max chunk size 4.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:66] Creating bin of max chunk size 8.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:66] Creating bin of max chunk size 16.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:66] Creating bin of max chunk size 32.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:66] Creating bin of max chunk size 64.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:66] Creating bin of max chunk size 128.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:66] Creating bin of max chunk size 256.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:66] Creating bin of max chunk size 512.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:66] Creating bin of max chunk size 1.00MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:66] Creating bin of max chunk size 2.00MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:66] Creating bin of max chunk size 4.00MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:66] Creating bin of max chunk size 8.00MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:66] Creating bin of max chunk size 16.00MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:66] Creating bin of max chunk size 32.00MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:66] Creating bin of max chunk size 64.00MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:66] Creating bin of max chunk size 128.00MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:66] Creating bin of max chunk size 256.00MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:66] Creating bin of max chunk size 512.00MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:66] Creating bin of max chunk size 1.00GiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:66] Creating bin of max chunk size 2.00GiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:66] Creating bin of max chunk size 4.00GiB
I tensorflow/core/common_runtime/direct_session.cc:58] Direct session inter op parallelism threads: 2
F tensorflow/stream_executor/cuda/cuda_dnn.cc:207] could not find cudnnCreate in cudnn DSO; dlerror: /usr/local/lib/python2.7/dist-packages/tensorflow/python/_pywrap_tensorflow.so: undefined symbol: cudnnCreate
```

**Comment by FreakTheMighty** [comment]
My apologies, I was simply missing cudnn. :/

**Comment by drdozer** [comment]
@FreakTheMighty  I'm getting the exact same error. I've installed cudnn into /usr/local/cudnn-6.5-linux-x64-v2/ and have LD_LIBRARY_PATH=/usr/local/cuda-7.0/lib64:/usr/local/cudnn-6.5-linux-x64-v2/. Is there something I've missed?

**Comment by andongchen** [comment]
@FreakTheMighty
I have the same problem,but I don't understand what's your mean ,could express more clearly?

**Comment by andongchen** [comment]
@FreakTheMighty
I have the same problem,but I don't understand what's your mean'My apologies, I was simply missing cudnn. :/' ,could express more clearly?
