### ISSUE TITLE
i changed the "libtensorflow_demo.so" file. Even then am facing the same issue

### ISSUE THREAD

**Issue by sthuthyraj** [tensorflow/tensorflow#24000]
E/AndroidRuntime: FATAL EXCEPTION: IntentService[Prediction Service]
    Process: com.cognizant.oralclassifier, PID: 25426
    java.lang.RuntimeException: Native TF methods not found; check that the correct native libraries are present in the APK.
        at org.tensorflow.contrib.android.TensorFlowInferenceInterface.prepareNativeRuntime(TensorFlowInferenceInterface.java:544)
        at org.tensorflow.contrib.android.TensorFlowInferenceInterface.<init>(TensorFlowInferenceInterface.java:60)
        at com.cognizant.oralclassifier.analyze.PredictionService.onHandleIntent(PredictionService.java:66)
        at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:76)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)

_Originally posted by @sthuthyraj in https://github.com/tensorflow/tensorflow/issue_comments#issuecomment-442025141_

**Comment by ymodak** [comment]
It looks like you haven't used a template to create this issue. Please resubmit your issue using a template from [here](https://github.com/tensorflow/tensorflow/issues/new/choose). We ask users to use the template because it reduces overall time to resolve a new issue by avoiding extra communication to get to the root of the issue. We will close this issue in lieu of the new one you will create from the template. Thank you for your cooperation.
