### ISSUE TITLE
Unable to train a LinearClassifier with categorical columns and CollectiveAllReduce

### ISSUE THREAD

**Issue by nateagr** [tensorflow/tensorflow#24003]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS 7
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v1.12.0-0-ga6d8ffae09 1.12.0
- Python version: 3.6.6
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

I'm trying to train a simple model LinearClassifier (tf.estimator.LinearClassifier) with different distribution strategies. 
I've successfully managed to train a model with parameter servers with numeric columns (tf.feature_column.numeric_column) and categorical columns (tf.feature_column.categorical_column_with_*). 
I've also successfully managed to train a model with CollectiveAllReduce and only numeric columns. 
But unfortunately, I'm getting the following error whith the same model (with CollectiveAllReduce) but with one categorical column in place of a numeric column:

> ValueError: `IndexSlices` is not supported for Collective All-Reduce.

See below for the all traceback and logs.

Here is a part of the code I am running:

```
estimator = tf.estimator.LinearClassifier(
        feature_columns=[
            tf.feature_column.categorical_column_with_hash_bucket("partnerid", 13, dtype=tf.int64),
            tf.feature_column.numeric_column("campaignid", dtype=tf.int64)
        ],
        model_dir="my_path",
        n_classes=2,
        optimizer="Adam",
        config=tf.estimator.RunConfig(
            experimental_distribute=tf.contrib.distribute.DistributeConfig(
                train_distribute=tf.contrib.distribute.CollectiveAllReduceStrategy(),
                remote_cluster=cluster_spec
            )
        )
    )

    tf.estimator.train_and_evaluate(
        estimator,
        tf.estimator.TrainSpec(
            input_fn_train,
            max_steps=training_steps
        ),
        tf.estimator.EvalSpec(
            input_fn_test,
            steps=evaluation_steps,
            start_delay_secs=0,
            throttle_secs=evaluation_throttle_secs
        )
    )
```
Is it a known issue ? Are there current limitations with CollectiveAllReduce ?

```
INFO:tensorflow:Waiting for worker:0/init
tensorflow - Waiting for worker:0/init
INFO:tensorflow:Waiting for worker:1/init
tensorflow - Waiting for worker:1/init
cluster_spec: ClusterSpec({'worker': ['10.188.17.14:42897', '10.188.50.21:48063']})
INFO:tensorflow:CollectiveAllReduceStrategy with local_devices = ['/device:CPU:0']
tensorflow - CollectiveAllReduceStrategy with local_devices = ['/device:CPU:0']
INFO:tensorflow:Initializing RunConfig with distribution strategies.
tensorflow - Initializing RunConfig with distribution strategies.
INFO:tensorflow:RunConfig initialized for Distribute Coordinator with STANDALONE_CLIENT mode
tensorflow - RunConfig initialized for Distribute Coordinator with STANDALONE_CLIENT mode
INFO:tensorflow:Using config: {'_model_dir': 'hdfs://root/user/username/model_dir', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': <tensorflow.contrib.distribute.python.collective_all_reduce_strategy.CollectiveAllReduceStrategy object at 0x7f1c4a7bef60>, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': DistributeConfig(train_distribute=<tensorflow.contrib.distribute.python.collective_all_reduce_strategy.CollectiveAllReduceStrategy object at 0x7f1c4a7bef60>, eval_distribute=None, remote_cluster=<tensorflow.python.training.server_lib.ClusterSpec object at 0x7f1c4a7d3208>), '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f1c4a7d3208>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1, '_distribute_coordinator_mode': 'standalone_client'}
tensorflow - Using config: {'_model_dir': 'hdfs://root/user/username/model_dir', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': <tensorflow.contrib.distribute.python.collective_all_reduce_strategy.CollectiveAllReduceStrategy object at 0x7f1c4a7bef60>, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': DistributeConfig(train_distribute=<tensorflow.contrib.distribute.python.collective_all_reduce_strategy.CollectiveAllReduceStrategy object at 0x7f1c4a7bef60>, eval_distribute=None, remote_cluster=<tensorflow.python.training.server_lib.ClusterSpec object at 0x7f1c4a7d3208>), '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f1c4a7d3208>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1, '_distribute_coordinator_mode': 'standalone_client'}
INFO:tensorflow:Running `train_and_evaluate` with Distribute Coordinator.
tensorflow - Running `train_and_evaluate` with Distribute Coordinator.
INFO:tensorflow:Running Distribute Coordinator with mode = 'standalone_client', cluster_spec = {'worker': ['10.188.17.14:42897', '10.188.50.21:48063']}, task_type = None, task_id = None, environment = None, rpc_layer = 'grpc'
tensorflow - Running Distribute Coordinator with mode = 'standalone_client', cluster_spec = {'worker': ['10.188.17.14:42897', '10.188.50.21:48063']}, task_type = None, task_id = None, environment = None, rpc_layer = 'grpc'
WARNING:tensorflow:`eval_strategy` is not passed in. No distribution strategy will be used for evaluation.
tensorflow - `eval_strategy` is not passed in. No distribution strategy will be used for evaluation.
INFO:tensorflow:Multi-worker CollectiveAllReduceStrategy with cluster_spec = {'worker': ['10.188.17.14:42897', '10.188.50.21:48063']}, task_type = 'worker', task_id = 0, num_workers = 2, local_devices = ['/job:worker/task:0']
tensorflow - Multi-worker CollectiveAllReduceStrategy with cluster_spec = {'worker': ['10.188.17.14:42897', '10.188.50.21:48063']}, task_type = 'worker', task_id = 0, num_workers = 2, local_devices = ['/job:worker/task:0']
INFO:tensorflow:Multi-worker CollectiveAllReduceStrategy with cluster_spec = {'worker': ['10.188.17.14:42897', '10.188.50.21:48063']}, task_type = 'worker', task_id = 1, num_workers = 2, local_devices = ['/job:worker/task:1']
tensorflow - Multi-worker CollectiveAllReduceStrategy with cluster_spec = {'worker': ['10.188.17.14:42897', '10.188.50.21:48063']}, task_type = 'worker', task_id = 1, num_workers = 2, local_devices = ['/job:worker/task:1']
INFO:tensorflow:Updated config: {'_model_dir': 'hdfs://root/user/username/model_dir', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': <tensorflow.contrib.distribute.python.collective_all_reduce_strategy.CollectiveAllReduceStrategy object at 0x7f1c4a7d3710>, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': DistributeConfig(train_distribute=<tensorflow.contrib.distribute.python.collective_all_reduce_strategy.CollectiveAllReduceStrategy object at 0x7f1c4a7601d0>, eval_distribute=None, remote_cluster=<tensorflow.python.training.server_lib.ClusterSpec object at 0x7f1c4a760438>), '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f1c4a7603c8>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': 'grpc://10.188.17.14:42897', '_evaluation_master': 'grpc://10.188.17.14:42897', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 2, '_distribute_coordinator_mode': 'standalone_client'}
tensorflow - Updated config: {'_model_dir': 'hdfs://root/user/username/model_dir', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': <tensorflow.contrib.distribute.python.collective_all_reduce_strategy.CollectiveAllReduceStrategy object at 0x7f1c4a7d3710>, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': DistributeConfig(train_distribute=<tensorflow.contrib.distribute.python.collective_all_reduce_strategy.CollectiveAllReduceStrategy object at 0x7f1c4a7601d0>, eval_distribute=None, remote_cluster=<tensorflow.python.training.server_lib.ClusterSpec object at 0x7f1c4a760438>), '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f1c4a7603c8>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': 'grpc://10.188.17.14:42897', '_evaluation_master': 'grpc://10.188.17.14:42897', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 2, '_distribute_coordinator_mode': 'standalone_client'}INFO:tensorflow:Updated config: {'_model_dir': 'hdfs://root/user/username/model_dir', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': <tensorflow.contrib.distribute.python.collective_all_reduce_strategy.CollectiveAllReduceStrategy object at 0x7f1c4a7d3cc0>, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': DistributeConfig(train_distribute=<tensorflow.contrib.distribute.python.collective_all_reduce_strategy.CollectiveAllReduceStrategy object at 0x7f1c4a760630>, eval_distribute=None, remote_cluster=<tensorflow.python.training.server_lib.ClusterSpec object at 0x7f1c4a760898>), '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f1c4a760828>, '_task_type': 'worker', '_task_id': 1, '_global_id_in_cluster': 1, '_master': 'grpc://10.188.50.21:48063', '_evaluation_master': 'grpc://10.188.50.21:48063', '_is_chief': False, '_num_ps_replicas': 0, '_num_worker_replicas': 2, '_distribute_coordinator_mode': 'standalone_client'}

tensorflow - Updated config: {'_model_dir': 'hdfs://root/user/username/model_dir', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': <tensorflow.contrib.distribute.python.collective_all_reduce_strategy.CollectiveAllReduceStrategy object at 0x7f1c4a7d3cc0>, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': DistributeConfig(train_distribute=<tensorflow.contrib.distribute.python.collective_all_reduce_strategy.CollectiveAllReduceStrategy object at 0x7f1c4a760630>, eval_distribute=None, remote_cluster=<tensorflow.python.training.server_lib.ClusterSpec object at 0x7f1c4a760898>), '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f1c4a760828>, '_task_type': 'worker', '_task_id': 1, '_global_id_in_cluster': 1, '_master': 'grpc://10.188.50.21:48063', '_evaluation_master': 'grpc://10.188.50.21:48063', '_is_chief': False, '_num_ps_replicas': 0, '_num_worker_replicas': 2, '_distribute_coordinator_mode': 'standalone_client'}
2018-11-27 13:25:56.606318: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
INFO:tensorflow:Calling model_fn.
tensorflow - Calling model_fn.
WARNING:tensorflow:Partitioned variables are disabled when using DistributionStrategy.
tensorflow - Partitioned variables are disabled when using DistributionStrategy.
INFO:tensorflow:Calling model_fn.
tensorflow - Calling model_fn.
DEBUG:tensorflow:Transforming feature_column _NumericColumn(key='campaignid', shape=(1,), default_value=None, dtype=tf.int64, normalizer_fn=None).
tensorflow - Transforming feature_column _NumericColumn(key='campaignid', shape=(1,), default_value=None, dtype=tf.int64, normalizer_fn=None).
DEBUG:tensorflow:Transforming feature_column _NumericColumn(key='campaignid', shape=(1,), default_value=None, dtype=tf.int64, normalizer_fn=None).
tensorflow - Transforming feature_column _NumericColumn(key='campaignid', shape=(1,), default_value=None, dtype=tf.int64, normalizer_fn=None).
DEBUG:tensorflow:Transforming feature_column _HashedCategoricalColumn(key='partnerid', hash_bucket_size=13, dtype=tf.int64).
tensorflow - Transforming feature_column _HashedCategoricalColumn(key='partnerid', hash_bucket_size=13, dtype=tf.int64).
DEBUG:tensorflow:Transforming feature_column _HashedCategoricalColumn(key='partnerid', hash_bucket_size=13, dtype=tf.int64).
tensorflow - Transforming feature_column _HashedCategoricalColumn(key='partnerid', hash_bucket_size=13, dtype=tf.int64).
INFO:tensorflow:Error reported to Coordinator: `IndexSlices` is not supported for Collective All-Reduce.
Traceback (most recent call last):
  File "/home/username/miniconda3/envs/explorer2/lib/python3.6/site-packages/tensorflow/python/training/coordinator.py", line 297, in stop_on_exception
    yield
  File "/home/username/miniconda3/envs/explorer2/lib/python3.6/site-packages/tensorflow/contrib/distribute/python/mirrored_strategy.py", line 177, in _call_for_each_tower
    **merge_kwargs)
  File "/home/username/miniconda3/envs/explorer2/lib/python3.6/site-packages/tensorflow/python/training/optimizer.py", line 661, in _distributed_apply
    variable_scope.VariableAggregation.SUM, grads_and_vars)
  File "/home/username/miniconda3/envs/explorer2/lib/python3.6/site-packages/tensorflow/python/training/distribute.py", line 776, in batch_reduce
    return self._batch_reduce(aggregation, value_destination_pairs)
  File "/home/username/miniconda3/envs/explorer2/lib/python3.6/site-packages/tensorflow/contrib/distribute/python/mirrored_strategy.py", line 628, in _batch_reduce
    value_destination_pairs)
  File "/home/username/miniconda3/envs/explorer2/lib/python3.6/site-packages/tensorflow/contrib/distribute/python/cross_tower_ops.py", line 243, in batch_reduce
    return self._batch_reduce(aggregation, value_destination_pairs)
  File "/home/username/miniconda3/envs/explorer2/lib/python3.6/site-packages/tensorflow/contrib/distribute/python/cross_tower_ops.py", line 829, in _batch_reduce
    "`IndexSlices` is not supported for Collective All-Reduce.")
ValueError: `IndexSlices` is not supported for Collective All-Reduce.
tensorflow - Error reported to Coordinator: `IndexSlices` is not supported for Collective All-Reduce.
Traceback (most recent call last):
  File "/home/username/miniconda3/envs/explorer2/lib/python3.6/site-packages/tensorflow/python/training/coordinator.py", line 297, in stop_on_exception
    yield
  File "/home/username/miniconda3/envs/explorer2/lib/python3.6/site-packages/tensorflow/contrib/distribute/python/mirrored_strategy.py", line 177, in _call_for_each_tower
    **merge_kwargs)
  File "/home/username/miniconda3/envs/explorer2/lib/python3.6/site-packages/tensorflow/python/training/optimizer.py", line 661, in _distributed_apply
    variable_scope.VariableAggregation.SUM, grads_and_vars)
  File "/home/username/miniconda3/envs/explorer2/lib/python3.6/site-packages/tensorflow/python/training/distribute.py", line 776, in batch_reduce
    return self._batch_reduce(aggregation, value_destination_pairs)
  File "/home/username/miniconda3/envs/explorer2/lib/python3.6/site-packages/tensorflow/contrib/distribute/python/mirrored_strategy.py", line 628, in _batch_reduce
    value_destination_pairs)
  File "/home/username/miniconda3/envs/explorer2/lib/python3.6/site-packages/tensorflow/contrib/distribute/python/cross_tower_ops.py", line 243, in batch_reduce
    return self._batch_reduce(aggregation, value_destination_pairs)
  File "/home/username/miniconda3/envs/explorer2/lib/python3.6/site-packages/tensorflow/contrib/distribute/python/cross_tower_ops.py", line 829, in _batch_reduce
    "`IndexSlices` is not supported for Collective All-Reduce.")
ValueError: `IndexSlices` is not supported for Collective All-Reduce.
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/home/username/miniconda3/envs/explorer2/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/username/miniconda3/envs/explorer2/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/username/miniconda3/envs/explorer2/lib/python3.6/site-packages/tensorflow/python/distribute/distribute_coordinator.py", line 344, in _run_single_worker
    worker_fn(strategy)
  File "/home/username/miniconda3/envs/explorer2/lib/python3.6/site-packages/tensorflow/python/distribute/estimator_training.py", line 246, in _worker_fn
    hooks=hooks)
  File "/home/username/miniconda3/envs/explorer2/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 354, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/username/miniconda3/envs/explorer2/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1205, in _train_model
    return self._train_model_distributed(input_fn, hooks, saving_listeners)
  File "/home/username/miniconda3/envs/explorer2/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1316, in _train_model_distributed
    self.config)
  File "/home/username/miniconda3/envs/explorer2/lib/python3.6/site-packages/tensorflow/python/training/distribute.py", line 721, in call_for_each_tower
    return self._call_for_each_tower(fn, *args, **kwargs)
  File "/home/username/miniconda3/envs/explorer2/lib/python3.6/site-packages/tensorflow/contrib/distribute/python/mirrored_strategy.py", line 556, in _call_for_each_tower
    return _call_for_each_tower(self, fn, *args, **kwargs)
  File "/home/username/miniconda3/envs/explorer2/lib/python3.6/site-packages/tensorflow/contrib/distribute/python/mirrored_strategy.py", line 183, in _call_for_each_tower
    coord.join(threads)
  File "/home/username/miniconda3/envs/explorer2/lib/python3.6/site-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/home/username/miniconda3/envs/explorer2/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/username/miniconda3/envs/explorer2/lib/python3.6/site-packages/tensorflow/python/training/coordinator.py", line 297, in stop_on_exception
    yield
  File "/home/username/miniconda3/envs/explorer2/lib/python3.6/site-packages/tensorflow/contrib/distribute/python/mirrored_strategy.py", line 177, in _call_for_each_tower
    **merge_kwargs)
  File "/home/username/miniconda3/envs/explorer2/lib/python3.6/site-packages/tensorflow/python/training/optimizer.py", line 661, in _distributed_apply
    variable_scope.VariableAggregation.SUM, grads_and_vars)
  File "/home/username/miniconda3/envs/explorer2/lib/python3.6/site-packages/tensorflow/python/training/distribute.py", line 776, in batch_reduce
    return self._batch_reduce(aggregation, value_destination_pairs)
  File "/home/username/miniconda3/envs/explorer2/lib/python3.6/site-packages/tensorflow/contrib/distribute/python/mirrored_strategy.py", line 628, in _batch_reduce
    value_destination_pairs)
  File "/home/username/miniconda3/envs/explorer2/lib/python3.6/site-packages/tensorflow/contrib/distribute/python/cross_tower_ops.py", line 243, in batch_reduce
    return self._batch_reduce(aggregation, value_destination_pairs)
  File "/home/username/miniconda3/envs/explorer2/lib/python3.6/site-packages/tensorflow/contrib/distribute/python/cross_tower_ops.py", line 829, in _batch_reduce
    "`IndexSlices` is not supported for Collective All-Reduce.")
ValueError: `IndexSlices` is not supported for Collective All-Reduce.

INFO:tensorflow:Error reported to Coordinator: `IndexSlices` is not supported for Collective All-Reduce.
Traceback (most recent call last):
  File "/home/username/miniconda3/envs/explorer2/lib/python3.6/site-packages/tensorflow/python/training/coordinator.py", line 297, in stop_on_exception
    yield
  File "/home/username/miniconda3/envs/explorer2/lib/python3.6/site-packages/tensorflow/contrib/distribute/python/mirrored_strategy.py", line 177, in _call_for_each_tower
    **merge_kwargs)
  File "/home/username/miniconda3/envs/explorer2/lib/python3.6/site-packages/tensorflow/python/training/optimizer.py", line 661, in _distributed_apply
    variable_scope.VariableAggregation.SUM, grads_and_vars)
  File "/home/username/miniconda3/envs/explorer2/lib/python3.6/site-packages/tensorflow/python/training/distribute.py", line 776, in batch_reduce
    return self._batch_reduce(aggregation, value_destination_pairs)
  File "/home/username/miniconda3/envs/explorer2/lib/python3.6/site-packages/tensorflow/contrib/distribute/python/mirrored_strategy.py", line 628, in _batch_reduce
    value_destination_pairs)
  File "/home/username/miniconda3/envs/explorer2/lib/python3.6/site-packages/tensorflow/contrib/distribute/python/cross_tower_ops.py", line 243, in batch_reduce
    return self._batch_reduce(aggregation, value_destination_pairs)
  File "/home/username/miniconda3/envs/explorer2/lib/python3.6/site-packages/tensorflow/contrib/distribute/python/cross_tower_ops.py", line 829, in _batch_reduce
    "`IndexSlices` is not supported for Collective All-Reduce.")
ValueError: `IndexSlices` is not supported for Collective All-Reduce.
tensorflow - Error reported to Coordinator: `IndexSlices` is not supported for Collective All-Reduce.
Traceback (most recent call last):
  File "/home/username/miniconda3/envs/explorer2/lib/python3.6/site-packages/tensorflow/python/training/coordinator.py", line 297, in stop_on_exception
    yield
  File "/home/username/miniconda3/envs/explorer2/lib/python3.6/site-packages/tensorflow/contrib/distribute/python/mirrored_strategy.py", line 177, in _call_for_each_tower
    **merge_kwargs)
  File "/home/username/miniconda3/envs/explorer2/lib/python3.6/site-packages/tensorflow/python/training/optimizer.py", line 661, in _distributed_apply
    variable_scope.VariableAggregation.SUM, grads_and_vars)
  File "/home/username/miniconda3/envs/explorer2/lib/python3.6/site-packages/tensorflow/python/training/distribute.py", line 776, in batch_reduce
    return self._batch_reduce(aggregation, value_destination_pairs)
  File "/home/username/miniconda3/envs/explorer2/lib/python3.6/site-packages/tensorflow/contrib/distribute/python/mirrored_strategy.py", line 628, in _batch_reduce
    value_destination_pairs)
  File "/home/username/miniconda3/envs/explorer2/lib/python3.6/site-packages/tensorflow/contrib/distribute/python/cross_tower_ops.py", line 243, in batch_reduce
    return self._batch_reduce(aggregation, value_destination_pairs)
  File "/home/username/miniconda3/envs/explorer2/lib/python3.6/site-packages/tensorflow/contrib/distribute/python/cross_tower_ops.py", line 829, in _batch_reduce
    "`IndexSlices` is not supported for Collective All-Reduce.")
ValueError: `IndexSlices` is not supported for Collective All-Reduce.
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/home/username/miniconda3/envs/explorer2/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/username/miniconda3/envs/explorer2/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/username/miniconda3/envs/explorer2/lib/python3.6/site-packages/tensorflow/python/distribute/distribute_coordinator.py", line 344, in _run_single_worker
    worker_fn(strategy)
  File "/home/username/miniconda3/envs/explorer2/lib/python3.6/site-packages/tensorflow/python/distribute/estimator_training.py", line 246, in _worker_fn
    hooks=hooks)
  File "/home/username/miniconda3/envs/explorer2/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 354, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/username/miniconda3/envs/explorer2/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1205, in _train_model
    return self._train_model_distributed(input_fn, hooks, saving_listeners)
  File "/home/username/miniconda3/envs/explorer2/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1316, in _train_model_distributed
    self.config)
  File "/home/username/miniconda3/envs/explorer2/lib/python3.6/site-packages/tensorflow/python/training/distribute.py", line 721, in call_for_each_tower
    return self._call_for_each_tower(fn, *args, **kwargs)
  File "/home/username/miniconda3/envs/explorer2/lib/python3.6/site-packages/tensorflow/contrib/distribute/python/mirrored_strategy.py", line 556, in _call_for_each_tower
    return _call_for_each_tower(self, fn, *args, **kwargs)
  File "/home/username/miniconda3/envs/explorer2/lib/python3.6/site-packages/tensorflow/contrib/distribute/python/mirrored_strategy.py", line 183, in _call_for_each_tower
    coord.join(threads)
  File "/home/username/miniconda3/envs/explorer2/lib/python3.6/site-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/home/username/miniconda3/envs/explorer2/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/username/miniconda3/envs/explorer2/lib/python3.6/site-packages/tensorflow/python/training/coordinator.py", line 297, in stop_on_exception
    yield
  File "/home/username/miniconda3/envs/explorer2/lib/python3.6/site-packages/tensorflow/contrib/distribute/python/mirrored_strategy.py", line 177, in _call_for_each_tower
    **merge_kwargs)
  File "/home/username/miniconda3/envs/explorer2/lib/python3.6/site-packages/tensorflow/python/training/optimizer.py", line 661, in _distributed_apply
    variable_scope.VariableAggregation.SUM, grads_and_vars)
  File "/home/username/miniconda3/envs/explorer2/lib/python3.6/site-packages/tensorflow/python/training/distribute.py", line 776, in batch_reduce
    return self._batch_reduce(aggregation, value_destination_pairs)
  File "/home/username/miniconda3/envs/explorer2/lib/python3.6/site-packages/tensorflow/contrib/distribute/python/mirrored_strategy.py", line 628, in _batch_reduce
    value_destination_pairs)
  File "/home/username/miniconda3/envs/explorer2/lib/python3.6/site-packages/tensorflow/contrib/distribute/python/cross_tower_ops.py", line 243, in batch_reduce
    return self._batch_reduce(aggregation, value_destination_pairs)
  File "/home/username/miniconda3/envs/explorer2/lib/python3.6/site-packages/tensorflow/contrib/distribute/python/cross_tower_ops.py", line 829, in _batch_reduce
    "`IndexSlices` is not supported for Collective All-Reduce.")
ValueError: `IndexSlices` is not supported for Collective All-Reduce.
```

**Comment by Meiyim** [comment]
I have encounter the same issuse. Can anyone provide a runable demo for Collective All-Reduce?

**Comment by byronyi** [comment]
Gentle ping @yuefengz

**Comment by amazingyyc** [comment]
Hi also encounter this problem in training Bert use multi-machine. 
I set the use_one_hot_embeddings to be true than it will have no error.
Do not know why.

**Comment by yuefengz** [comment]
SparseTensor and IndexSlices are currently not supported since it requires all-gather. @poxvoculi @dubey

**Comment by fhoering** [comment]
The issue is still there in tf 1.13.1. 
Do you have any news ? 
@poxvoculi @dubey @yuefengz

**Comment by byronyi** [comment]
@fhoering could you try nightly TF? 1.13 release branch was cut last year and we can’t really introduce any new feature.

**Comment by fhoering** [comment]
@byronyi I tried with tf-nighly 1.14.1
Indeed I doesn't give the not implemented error anymore but now fails with grpc error:
```
2019-05-17 14:23:01.822779: E tensorflow/core/common_runtime/ring_alg.cc:279] Aborting RingGather with Internal: RecvBufResponse returned 48 bytes where to_tensor expected 56
2019-05-17 14:23:01.822834: W tensorflow/core/common_runtime/base_collective_executor.cc:216] BaseCollectiveExecutor::StartAbort Internal: RecvBufResponse returned 48 bytes where to_tensor expected 56
```

Side notes:
- I tried with slightly different model, all logs + source code attached
- When trying with NumericColumns only (that one that works) there are a lot of logs that disapeared. It doesn't seem to say that it is even useing CollectiveAllReduceStrategy/Standalone mode anymore, but finishes with success and model is created, metrics like loss/accuracy seem fine compared to ps strategy

[Code.zip](https://github.com/tensorflow/tensorflow/files/3191918/Code.zip)
[client.log](https://github.com/tensorflow/tensorflow/files/3191913/client.log)
[worker1.log](https://github.com/tensorflow/tensorflow/files/3191914/worker1.log)
[worker2.log](https://github.com/tensorflow/tensorflow/files/3191915/worker2.log)

**Comment by fhoering** [comment]
@byronyi 
I tried with another model and also post the error message:
```
tensorflow - Error reported to Coordinator: From /job:worker/replica:0/task:0:
RecvBufResponse returned 206400 bytes where to_tensor expected 194400
	 [[node allreduce_1/CollectiveGather_1 (defined at /threading.py:864) ]]
```

Maybe it is clearer than the attached logs of the previous model.

It fails in the reduce of gradients in tf.gather operation which seem returns a sparse tensor. 
https://github.com/tensorflow/tensorflow/blob/a5c387b5ed78c9126424618d5c70f51cd3799857/tensorflow/python/ops/array_ops.py#L3261

So the problem is still there but wit ha different form.
Can you please have a look ?

**Comment by rabintang** [comment]
any progress on this issue?

**Comment by yuefengz** [comment]
`IndexedSliced` has already been supported a while ago, could you try it out again?

**Comment by yuefengz** [comment]
Looks like there is some issue with the support for `IndexedSlices`. Right now there is some restriction that allgather requires all inputs have the same input sizes. If your `IndexedSlices` have different slices on different replicas, it will crash. @dubey

**Comment by dubey** [comment]
@fhoering can you confirm that it is indeed the case that your input tensors have different sizes on different replicas?

**Comment by nateagr** [comment]
We tried with only categorical features and only continuous features. For categorical features, there is indeed no guarantee that replicas have the same number of slices for allgather of sparse gradients. All worker process the same number of examples per iteration but the number of slices depend on the features included in batches

**Comment by fhoering** [comment]
Yes, I confirm. As mentioned by @nateagr. As each worker with shuffling each worker worker on Different examples, they see different categories and therefore different gradients are activated and the indexes of the sparse tensor are different. 
I don't see any case with categorical features where this can actually work, maybe when having only one category per features across all examples.

**Comment by eshaoliu** [comment]
Hi，can eager mode supported now when updating indices slices?

**Comment by sachinprasadhs** [comment]
> Hi，can eager mode supported now when updating indices slices?

There is an RFC to update Tensor indexes, you can refer this PR here https://github.com/tensorflow/community/blob/77aa8fd5ea9c54bf1f08e9d25113aaa1ea90ba20/rfcs/20221020-tensor-indexed-updates.md for more details, there are few issues linked in the PR which could be related to your request.

**Comment by sachinprasadhs** [comment]
Contrib has been deprecated, refer here for more details https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md.
Also, refer the document here https://www.tensorflow.org/guide/migrate for migrating guidelines. Thanks!
