### ISSUE TITLE
can't use tensorflow-gpu=1.12

### ISSUE THREAD

**Issue by xun6000** [tensorflow/tensorflow#24064]
I use anaconda and I both have cuda8 and cuda10 with the right cudnn. 
I tried 3.6.2 and 3.6.6. None of them works. 
Not only in the windows desk top. The tensorflow can't work on  linux cluster.

(py36) C:\Users\GUANGYUAN>python
Python 3.6.2 |Continuum Analytics, Inc.| (default, Jul 20 2017, 12:30:02) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
Traceback (most recent call last):
  File "C:\Users\GUANGYUAN\AppData\Local\conda\conda\envs\py36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\GUANGYUAN\AppData\Local\conda\conda\envs\py36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\GUANGYUAN\AppData\Local\conda\conda\envs\py36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\GUANGYUAN\AppData\Local\conda\conda\envs\py36\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\GUANGYUAN\AppData\Local\conda\conda\envs\py36\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\GUANGYUAN\AppData\Local\conda\conda\envs\py36\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\GUANGYUAN\AppData\Local\conda\conda\envs\py36\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\GUANGYUAN\AppData\Local\conda\conda\envs\py36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\GUANGYUAN\AppData\Local\conda\conda\envs\py36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\GUANGYUAN\AppData\Local\conda\conda\envs\py36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\GUANGYUAN\AppData\Local\conda\conda\envs\py36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\GUANGYUAN\AppData\Local\conda\conda\envs\py36\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\GUANGYUAN\AppData\Local\conda\conda\envs\py36\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by WhistleWhileYouWork** [comment]
[Tensorflow GPU Requirements:](https://www.tensorflow.org/install/gpu#software_requirements)
Nvidia drivers >= 384.x
CUDA 9.0 only
cuDNN >= 7.2

**Comment by FredVaugeois** [comment]
I highly suggest you try using CUDA v9.0 with cuDNN 7 as it's, from my experience, the most stable versions yet. I know that 10.0 and 8 are starting to be stable aswell, but as of right now, I still recommend the older versions. Also, make sure you have correctly installed tensorflow-gpu from pip with "pip3 install tensorflow-gpu --upgrade" or built it correctly from source following this [guide](https://www.tensorflow.org/install/source_windows). 

Also, make sure you have correctly set your PATH environment variable following this [guide](https://www.tensorflow.org/install/gpu). You will also be able to see if you have the correct hardware requirements to use tensorflow GPU.

**Comment by ymodak** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
