### ISSUE TITLE
InvalidArgumentError (see above for traceback): Got 88 frames, but animated gifs can only be decoded by tf.image.decode_gif or tf.image.decode_image

### ISSUE THREAD

**Issue by T-chuangxin** [tensorflow/tensorflow#24065]
I am trying to train a new model. Here is my code!

python /Users/tianchuangxin1/hub/examples/image_retraining/retrain.py --image_dir /Users/tianchuangxin1/tensorflow_image ----model_dir=/Users/tianchuangxin1/tensorflow_image --how_many_training_steps=6000 --flip_left_right Ture --testing_percentage=10 --train_batch_size=32 --validation_batch_size=-1 --random_brightness=30 --random_scale=30 --eval_step_interval=200

Then , get the error:

INFO:tensorflow:Looking for images in 'apple'
INFO:tensorflow:Looking for images in 'computer'
INFO:tensorflow:Looking for images in 'pants'
INFO:tensorflow:Looking for images in 'shoes'
INFO:tensorflow:Looking for images in 'watch'
INFO:tensorflow:Using /var/folders/85/qbnsnmfn5vn0r3x3nvr09w790pxfq6/T/tfhub_modules to cache modules.
2018-11-30 16:31:19.221881: W tensorflow/core/graph/graph_constructor.cc:1265] Importing a graph with a lower producer version 26 into an existing graph with producer version 27. Shape inference will have run different parts of the graph with different producer versions.
INFO:tensorflow:Saver not created because there are no variables in the graph to restore
2018-11-30 16:31:23.032847: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
WARNING:tensorflow:From /Users/tianchuangxin1/hub/examples/image_retraining/retrain.py:582: FastGFile.__init__ (from tensorflow.python.platform.gfile) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.gfile.GFile.
Traceback (most recent call last):
  File "/Users/tianchuangxin1/anaconda/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/Users/tianchuangxin1/anaconda/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/Users/tianchuangxin1/anaconda/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Got 88 frames, but animated gifs can only be decoded by tf.image.decode_gif or tf.image.decode_image
	 [[{{node DecodeJpeg_1}} = DecodeJpeg[acceptable_fraction=1, channels=3, dct_method="", fancy_upscaling=true, ratio=1, try_recover_truncated=false, _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_DistortJPGInput_0_0)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tianchuangxin1/hub/examples/image_retraining/retrain.py", line 1315, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/Users/tianchuangxin1/anaconda/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/Users/tianchuangxin1/hub/examples/image_retraining/retrain.py", line 1057, in main
    distorted_image_tensor, resized_image_tensor, bottleneck_tensor)
  File "/Users/tianchuangxin1/hub/examples/image_retraining/retrain.py", line 587, in get_random_distorted_bottlenecks
    {input_jpeg_tensor: jpeg_data})
  File "/Users/tianchuangxin1/anaconda/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/Users/tianchuangxin1/anaconda/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/Users/tianchuangxin1/anaconda/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/Users/tianchuangxin1/anaconda/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Got 88 frames, but animated gifs can only be decoded by tf.image.decode_gif or tf.image.decode_image
	 [[node DecodeJpeg_1 (defined at /Users/tianchuangxin1/hub/examples/image_retraining/retrain.py:671)  = DecodeJpeg[acceptable_fraction=1, channels=3, dct_method="", fancy_upscaling=true, ratio=1, try_recover_truncated=false, _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_DistortJPGInput_0_0)]]

Caused by op 'DecodeJpeg_1', defined at:
  File "/Users/tianchuangxin1/hub/examples/image_retraining/retrain.py", line 1315, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/Users/tianchuangxin1/anaconda/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/Users/tianchuangxin1/hub/examples/image_retraining/retrain.py", line 1024, in main
    FLAGS.random_brightness, module_spec)
  File "/Users/tianchuangxin1/hub/examples/image_retraining/retrain.py", line 671, in add_input_distortions
    decoded_image = tf.image.decode_jpeg(jpeg_data, channels=input_depth)
  File "/Users/tianchuangxin1/anaconda/lib/python3.5/site-packages/tensorflow/python/ops/gen_image_ops.py", line 954, in decode_jpeg
    name=name)
  File "/Users/tianchuangxin1/anaconda/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/Users/tianchuangxin1/anaconda/lib/python3.5/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/Users/tianchuangxin1/anaconda/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/Users/tianchuangxin1/anaconda/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Got 88 frames, but animated gifs can only be decoded by tf.image.decode_gif or tf.image.decode_image
	 [[node DecodeJpeg_1 (defined at /Users/tianchuangxin1/hub/examples/image_retraining/retrain.py:671)  = DecodeJpeg[acceptable_fraction=1, channels=3, dct_method="", fancy_upscaling=true, ratio=1, try_recover_truncated=false, _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_DistortJPGInput_0_0)]]

**Comment by FredVaugeois** [comment]
You've probably got a ".gif" file in your data folder which cannot actually be decoded as an image file. You can either remove the ".gif" file from the folder or add this kind of a code to detect multiple file encodings:

if imagePath.endswith(".png"):
    imageDecoded = tf.image.decode_png(...)

elif imagePath.endswith(".jpg"):
    imageDecoded = tf.image.decode_jpeg(...)

elif imagePath.endswith(".gif"):
    imageDecoded = tf.image.decode_gif(...)

This needs to be modifier in the part of the code that converts your image files to tensors.

**Comment by FredVaugeois** [comment]
This is where it should be modified:
![image](https://user-images.githubusercontent.com/26579806/49293818-2e52c380-f47f-11e8-9af7-e5e5121aaba0.png)

**Comment by T-chuangxin** [comment]
> You've probably got a ".gif" file in your data folder which cannot actually be decoded as an image file. You can either remove the ".gif" file from the folder or add this kind of a code to detect multiple file encodings:
> 
> if imagePath.endswith(".png"):
> imageDecoded = tf.image.decode_png(...)
> 
> elif imagePath.endswith(".jpg"):
> imageDecoded = tf.image.decode_jpeg(...)
> 
> elif imagePath.endswith(".gif"):
> imageDecoded = tf.image.decode_gif(...)
> 
> This needs to be modifier in the part of the code that converts your image files to tensors.


I have carefully checked the pictures I have trained, all the pictures are in JPG format. Very strange, I don't know if it is a version of my TensorFlow issue. After that, I deleted two more folders, just fine.

**Comment by ymodak** [comment]
This issue is more suitable on TensorFlow models repo. Please post it on TF models repo from [here](https://github.com/tensorflow/models/issues/new). Thanks!
