### ISSUE TITLE
quant_graph caonvert to .tflite:  Converting unsupported operation: Dequantize

### ISSUE THREAD

**Issue by ToBigboss** [tensorflow/tensorflow#24093]
I want to know where is wrong, please someone help me.

version:
Python 2.7.12 (default, Nov 12 2018, 14:36:49)

>>> import tensorflow as tf
>>> tf.__version__
'1.13.0-dev20181201'
>>> 

log:
super@super-virtual-machine:~/Downloads$ tflite_convert \
>   --output_file=/home/super/Downloads/mobilenet_v1_0.50_128/mobilenet_v1.tflite \
>   --graph_def_file=/home/super/Downloads/mobilenet_v1_0.50_128/quantized_graph.pb \
>   --inference_type=QUANTIZED_UINT8 \
>   --input_arrays=input \
>   --output_arrays=MobilenetV1/Predictions/Reshape_1 \
>   --mean_values=128 \
>   --std_dev_values=127
2018-12-01 22:45:07.489914: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Traceback (most recent call last):
  File "/usr/local/bin/tflite_convert", line 11, in <module>
    sys.exit(main())
  File "/home/super/.local/lib/python2.7/site-packages/tensorflow/lite/python/tflite_convert.py", line 442, in main
    app.run(main=run_main, argv=sys.argv[:1])
  File "/home/super/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/home/super/.local/lib/python2.7/site-packages/tensorflow/lite/python/tflite_convert.py", line 438, in run_main
    _convert_model(tflite_flags)
  File "/home/super/.local/lib/python2.7/site-packages/tensorflow/lite/python/tflite_convert.py", line 191, in _convert_model
    output_data = converter.convert()
  File "/home/super/.local/lib/python2.7/site-packages/tensorflow/lite/python/lite.py", line 455, in convert
    **converter_kwargs)
  File "/home/super/.local/lib/python2.7/site-packages/tensorflow/lite/python/convert.py", line 430, in toco_convert_impl
    input_data.SerializeToString())
  File "/home/super/.local/lib/python2.7/site-packages/tensorflow/lite/python/convert.py", line 204, in toco_convert_protos
    "TOCO failed. See console for info.\n%s\n%s\n" % (stdout, stderr))
tensorflow.lite.python.convert.ConverterError: TOCO failed. See console for info.
2018-12-01 22:45:08.455379: I tensorflow/lite/toco/import_tensorflow.cc:1299] Converting unsupported operation: Dequantize
2018-12-01 22:45:08.471418: I tensorflow/lite/toco/import_tensorflow.cc:1299] Converting unsupported operation: Dequantize
2018-12-01 22:45:08.476136: I tensorflow/lite/toco/import_tensorflow.cc:1299] Converting unsupported operation: Dequantize
2018-12-01 22:45:08.476205: I tensorflow/lite/toco/import_tensorflow.cc:1299] Converting unsupported operation: Dequantize
2018-12-01 22:45:08.476247: I tensorflow/lite/toco/import_tensorflow.cc:1299] Converting unsupported operation: Dequantize
2018-12-01 22:45:08.476287: I tensorflow/lite/toco/import_tensorflow.cc:1299] Converting unsupported operation: Dequantize
2018-12-01 22:45:08.476516: I tensorflow/lite/toco/import_tensorflow.cc:1299] Converting unsupported operation: Dequantize
2018-12-01 22:45:08.477495: I tensorflow/lite/toco/import_tensorflow.cc:1299] Converting unsupported operation: Dequantize
2018-12-01 22:45:08.481725: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 138 operators, 226 arrays (0 quantized)
2018-12-01 22:45:08.497846: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 138 operators, 226 arrays (0 quantized)
2018-12-01 22:45:08.499427: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 1: 57 operators, 132 arrays (1 quantized)
2018-12-01 22:45:08.506318: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before pre-quantization graph transformations: 57 operators, 132 arrays (1 quantized)
2018-12-01 22:45:08.506970: F tensorflow/lite/toco/tooling_util.cc:1698] Array MobilenetV1/MobilenetV1/Conv2d_0/Relu6, which is an input to the DepthwiseConv operator producing the output array MobilenetV1/MobilenetV1/Conv2d_1_depthwise/Relu6, is lacking min/max data, which is necessary for quantization. If accuracy matters, either target a non-quantized output format, or run quantized training with your model from a floating point checkpoint to change the input graph to contain min/max information. If you don't care about accuracy, you can pass --default_ranges_min= and --default_ranges_max= for easy experimentation.
Aborted (core dumped)

**Comment by ymodak** [comment]
It looks like you have some tflite unsupported ops in your model. Please refer [TensorFlow Lite & TensorFlow Compatibility Guide](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/tf_ops_compatibility.md#tensorflow-lite--tensorflow-compatibility-guide).

**Comment by ymodak** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
