### ISSUE TITLE
Tensorflow-gpu wont install Windows 10

### ISSUE THREAD

**Issue by Bstrum36** [tensorflow/tensorflow#24110]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- Windows 10  Home Ver 1803
- TensorFlow installed from pip
- TensorFlow version: 1.12.0 (tensorflow-gpu)
- Python version:3.6.3
- Installed using virtualenv? pip? conda?:pip
- CUDA/cuDNN version: 10.0.132
- GPU model and memory: GTX 1080

**Describe the problem**
Tensor flow-gpu is not properly installed.   

**Provide the exact sequence of commands / steps that you executed before running into the problem**
This is the only code
**import tensorflow**  
Thats it!!

If I install tensorflow-gpu and install tensor floe for the cpu it all works.

ImportError: DLL load failed: The specified module could not be found.

Failed to load the native TensorFlow runtime.

The entire traceback is listed below.
Installing the tensor flow 
That is as basic as you get  it states 
**Any other info / logs**
Python 3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 18:11:49) [MSC v.1900 64 bit (AMD64)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> 
 RESTART: C:\Users\BillS\AppData\Local\Programs\Python\Python36\tensorgputest.py 
Traceback (most recent call last):
  File "C:\Users\BillS\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\BillS\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\BillS\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\BillS\AppData\Local\Programs\Python\Python36\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\BillS\AppData\Local\Programs\Python\Python36\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\BillS\AppData\Local\Programs\Python\Python36\tensorgputest.py", line 1, in <module>
    import tensorflow
  File "C:\Users\BillS\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\BillS\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\BillS\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\BillS\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\BillS\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\BillS\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\BillS\AppData\Local\Programs\Python\Python36\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\BillS\AppData\Local\Programs\Python\Python36\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

Failed to load the native TensorFlow runtime.

**Comment by ymodak** [comment]
TensorFlow is tested against CUDA 9.0, to use CUDA 10.0 you have to build it yourself from the sources. The easier alternative would be to switch to CUDA 9.0 and build again. Thanks!

**Comment by Bstrum36** [comment]
OK,

Any idea when 10 will be supported.
Will there be any issues with reverting to an older version om my system.
Should I unistall Tensorflow-gpu before switching to ver - 9

**Comment by ymodak** [comment]
@Bstrum36 cuda 10 support is on our roadmap and it will be officially supported starting from TensorFlow 2.0. Thanks!
