### ISSUE TITLE
Android - Binary XML file line #*: Error inflating class com.android.internal.widget.ActionBarView

### ISSUE THREAD

**Issue by datomnurdin** [tensorflow/tensorflow#2411]
I got this issue when trying to test tensorflow demo on android device.

    05-18 10:25:44.494: E/AndroidRuntime(29965): FATAL EXCEPTION: main
    05-18 10:25:44.494: E/AndroidRuntime(29965): java.lang.RuntimeException: Unable to start activity ComponentInfo{org.tensorflow.demo/org.tensorflow.demo.CameraActivity}: android.view.InflateException: Binary XML file line #39: Error inflating class com.android.internal.widget.ActionBarView
    05-18 10:25:44.494: E/AndroidRuntime(29965): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2214)
    05-18 10:25:44.494: E/AndroidRuntime(29965): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2264)
    05-18 10:25:44.494: E/AndroidRuntime(29965): 	at android.app.ActivityThread.access$600(ActivityThread.java:144)
    05-18 10:25:44.494: E/AndroidRuntime(29965): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1259)
    05-18 10:25:44.494: E/AndroidRuntime(29965): 	at android.os.Handler.dispatchMessage(Handler.java:99)
    05-18 10:25:44.494: E/AndroidRuntime(29965): 	at android.os.Looper.loop(Looper.java:137)
    05-18 10:25:44.494: E/AndroidRuntime(29965): 	at android.app.ActivityThread.main(ActivityThread.java:5136)
    05-18 10:25:44.494: E/AndroidRuntime(29965): 	at java.lang.reflect.Method.invokeNative(Native Method)
    05-18 10:25:44.494: E/AndroidRuntime(29965): 	at java.lang.reflect.Method.invoke(Method.java:525)
    05-18 10:25:44.494: E/AndroidRuntime(29965): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
    05-18 10:25:44.494: E/AndroidRuntime(29965): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
    05-18 10:25:44.494: E/AndroidRuntime(29965): 	at dalvik.system.NativeStart.main(Native Method)
    05-18 10:25:44.494: E/AndroidRuntime(29965): Caused by: android.view.InflateException: Binary XML file line #39: Error inflating class com.android.internal.widget.ActionBarView
    05-18 10:25:44.494: E/AndroidRuntime(29965): 	at android.view.LayoutInflater.createView(LayoutInflater.java:620)
    05-18 10:25:44.494: E/AndroidRuntime(29965): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
    05-18 10:25:44.494: E/AndroidRuntime(29965): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
    05-18 10:25:44.494: E/AndroidRuntime(29965): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
    05-18 10:25:44.494: E/AndroidRuntime(29965): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
    05-18 10:25:44.494: E/AndroidRuntime(29965): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
    05-18 10:25:44.494: E/AndroidRuntime(29965): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
    05-18 10:25:44.494: E/AndroidRuntime(29965): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
    05-18 10:25:44.494: E/AndroidRuntime(29965): 	at com.android.internal.policy.impl.PhoneWindow.generateLayout(PhoneWindow.java:2825)
    05-18 10:25:44.494: E/AndroidRuntime(29965): 	at com.android.internal.policy.impl.PhoneWindow.installDecor(PhoneWindow.java:2888)
    05-18 10:25:44.494: E/AndroidRuntime(29965): 	at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:264)
    05-18 10:25:44.494: E/AndroidRuntime(29965): 	at android.app.Activity.setContentView(Activity.java:1895)
    05-18 10:25:44.494: E/AndroidRuntime(29965): 	at org.tensorflow.demo.CameraActivity.onCreate(CameraActivity.java:29)
    05-18 10:25:44.494: E/AndroidRuntime(29965): 	at android.app.Activity.performCreate(Activity.java:5133)
    05-18 10:25:44.494: E/AndroidRuntime(29965): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
    05-18 10:25:44.494: E/AndroidRuntime(29965): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2178)
    05-18 10:25:44.494: E/AndroidRuntime(29965): 	... 11 more
    05-18 10:25:44.494: E/AndroidRuntime(29965): Caused by: java.lang.reflect.InvocationTargetException
    05-18 10:25:44.494: E/AndroidRuntime(29965): 	at java.lang.reflect.Constructor.constructNative(Native Method)
    05-18 10:25:44.494: E/AndroidRuntime(29965): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
    05-18 10:25:44.494: E/AndroidRuntime(29965): 	at android.view.LayoutInflater.createView(LayoutInflater.java:594)
    05-18 10:25:44.494: E/AndroidRuntime(29965): 	... 26 more
    05-18 10:25:44.494: E/AndroidRuntime(29965): Caused by: android.view.InflateException: Binary XML file line #35: Error inflating class android.widget.TextView
    05-18 10:25:44.494: E/AndroidRuntime(29965): 	at android.view.LayoutInflater.createView(LayoutInflater.java:620)
    05-18 10:25:44.494: E/AndroidRuntime(29965): 	at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
    05-18 10:25:44.494: E/AndroidRuntime(29965): 	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:669)
    05-18 10:25:44.494: E/AndroidRuntime(29965): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:694)
    05-18 10:25:44.494: E/AndroidRuntime(29965): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
    05-18 10:25:44.494: E/AndroidRuntime(29965): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
    05-18 10:25:44.494: E/AndroidRuntime(29965): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
    05-18 10:25:44.494: E/AndroidRuntime(29965): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
    05-18 10:25:44.494: E/AndroidRuntime(29965): 	at com.android.internal.widget.ActionBarView.initTitle(ActionBarView.java:852)
    05-18 10:25:44.494: E/AndroidRuntime(29965): 	at com.android.internal.widget.ActionBarView.setDisplayOptions(ActionBarView.java:670)
    05-18 10:25:44.494: E/AndroidRuntime(29965): 	at com.android.internal.widget.ActionBarView.<init>(ActionBarView.java:254)
    05-18 10:25:44.494: E/AndroidRuntime(29965): 	... 29 more
    05-18 10:25:44.494: E/AndroidRuntime(29965): Caused by: java.lang.reflect.InvocationTargetException
    05-18 10:25:44.494: E/AndroidRuntime(29965): 	at java.lang.reflect.Constructor.constructNative(Native Method)
    05-18 10:25:44.494: E/AndroidRuntime(29965): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
    05-18 10:25:44.494: E/AndroidRuntime(29965): 	at android.view.LayoutInflater.createView(LayoutInflater.java:594)
    05-18 10:25:44.494: E/AndroidRuntime(29965): 	... 39 more
    05-18 10:25:44.494: E/AndroidRuntime(29965): Caused by: java.lang.UnsupportedOperationException: Can't convert to color: type=0x2
    05-18 10:25:44.494: E/AndroidRuntime(29965): 	at android.content.res.TypedArray.getColor(TypedArray.java:326)
    05-18 10:25:44.494: E/AndroidRuntime(29965): 	at android.widget.TextView.<init>(TextView.java:673)
    05-18 10:25:44.494: E/AndroidRuntime(29965): 	at android.widget.TextView.<init>(TextView.jav

CameraActivity.java

    package org.tensorflow.demo;
    
    import android.app.Activity;
    import android.os.Bundle;
    import android.view.WindowManager;
    
    public class CameraActivity extends Activity {
      @Override
      protected void onCreate(final Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);
    
        setContentView(R.layout.activity_camera);
        if (null == savedInstanceState) {
          getFragmentManager()
              .beginTransaction()
              .replace(R.id.container, CameraConnectionFragment.newInstance())
              .commit();
        }
      }
    }

activity_camera.xml

    <?xml version="1.0" encoding="utf-8"?><!--
    <FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:tools="http://schemas.android.com/tools"
        android:id="@+id/container"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="#000"
        tools:context="org.tensorflow.demo.CameraActivity" />

Please advice. Thank you.

**Comment by andrewharp** [comment]
Hi, 
A few questions first:
- have you made any changes to the code?
- which SDK build tools version are you using?
- how did you build the APK?
- What Android API level is the device you're testing it on?

My initial guess after a little googling is that it has something to do with API levels, themes, or Android support libraries (which we don't use -- did your IDE try to add one?).

**Comment by datomnurdin** [comment]
1. I convert into gradle format. No major changes except gradle file.
2. **23.0.2**
3. Build using android studio and upload it into device (not simulator).
4. **4.3**

My gradle setting

```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 21
    buildToolsVersion "23.0.2"

    defaultConfig {
        applicationId "org.tensorflow.demo"
        minSdkVersion 18
        targetSdkVersion 18
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
        }
    }
}

dependencies{
    compile 'com.android.support:appcompat-v7:22.2.1'
    compile 'com.android.support:design:22.2.0'
}
```

**Comment by andrewharp** [comment]
Android 4.3 is API level 18. The demo requires 21 due to the camera2 api. I'm not sure why Gradle allowed you to compile it for API 18 when the AndroidManifest.xml specifies 21 (did you change that?), but your errors are almost definitely related to the appcompat dependencies shown at the bottom of the gradle settings you provided.

Appcompat libraries should not be required for tensorflow, as we don't do any special theming or use any new UI elements in the demo. Try getting rid of those, and you'll also need to convert the camera code from the camera2 api to use android.hardware.Camera. You can see https://github.com/hamidb/tensorflow/tree/api20 for an example of this.

**Comment by datomnurdin** [comment]
I already use Android 5 but I got another error message

```
19406/org.tensorflow.demo E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: org.tensorflow.demo, PID: 19406
                                                                     java.lang.UnsatisfiedLinkError: com.android.tools.fd.runtime.IncrementalClassLoader$DelegateClassLoader[DexPathList[[dex file "/data/data/org.tensorflow.demo/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/org.tensorflow.demo/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/org.tensorflow.demo/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/org.tensorflow.demo/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/org.tensorflow.demo/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/org.tensorflow.demo/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/org.tensorflow.demo/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/org.tensorflow.demo/files/instant-run/dex/slice-slice_2-classes.dex", dex file "/data/data/org.tensorflow.demo/files/instant-run/dex/slice-slice_1-classes.dex", dex file "/data/data/org.tensorflow.demo/files/instant-run/dex/slice-slice_0-classes.dex"],nativeLibraryDirectories=[/vendor/lib, /system/lib, /vendor/lib, /system/lib]]] couldn't find "libtensorflow_demo.so"
                                                                         at java.lang.Runtime.loadLibrary(Runtime.java:366)
                                                                         at java.lang.System.loadLibrary(System.java:989)
                                                                         at org.tensorflow.demo.TensorflowClassifier.<clinit>(TensorflowClassifier.java:47)
                                                                         at org.tensorflow.demo.TensorflowImageListener.<init>(TensorflowImageListener.java:56)
                                                                         at org.tensorflow.demo.CameraConnectionFragment.<init>(CameraConnectionFragment.java:445)
                                                                         at org.tensorflow.demo.CameraConnectionFragment.newInstance(CameraConnectionFragment.java:266)
                                                                         at org.tensorflow.demo.CameraActivity.onCreate(CameraActivity.java:33)
                                                                         at android.app.Activity.performCreate(Activity.java:6289)
                                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2758)
                                                                         at android.app.ActivityThread.access$900(ActivityThread.java:177)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1448)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:145)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5942)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at java.lang.reflect.Method.invoke(Method.java:372)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1389)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1184)
```

**Comment by andrewharp** [comment]
I take it you were able to get past the original error? If so, was the fix removing the dependencies or something else?

**Comment by andrewharp** [comment]
Closing due to inactivity, please reopen if you're still experiencing the issue.
