### ISSUE TITLE
django tensorflow 

### ISSUE THREAD

**Issue by banbsyip** [tensorflow/tensorflow#24163]
django version:2.1.1
python version:3.5.2
tensorflow-gpu version:1.9.0
keras version:2.2.4
anaconda:4.5.11
I have a tensorflow project, I ran it with pycharm and it worked. then I want to run it in django ,but there have some import problem. through set source path or  append os.path, it didn't work.
the frame of the project:
tmp/
---ocr_django/
-------ocr_django/
----------ocr/
-------------ctpn/
-------------demo/
-------------densenet/
-------------train/
-------------__init__.py
-------------demo.py
-------------ocr.py
-------------recongnize.py
----------__init__.py      
----------original.py
----------setting.py
----------test.py
----------urls.py
----------view.py
----------wsgi.py

- the problem as follow:
Traceback (most recent call last):
  File "/home/cq/anaconda3/lib/python3.5/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/home/cq/anaconda3/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    self.check(display_num_errors=True)
  File "/home/cq/anaconda3/lib/python3.5/site-packages/django/core/management/base.py", line 379, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/cq/anaconda3/lib/python3.5/site-packages/django/core/management/base.py", line 366, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/cq/anaconda3/lib/python3.5/site-packages/django/core/checks/registry.py", line 71, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/cq/anaconda3/lib/python3.5/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/home/cq/anaconda3/lib/python3.5/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/home/cq/anaconda3/lib/python3.5/site-packages/django/urls/resolvers.py", line 396, in check
    for pattern in self.url_patterns:
  File "/home/cq/anaconda3/lib/python3.5/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/cq/anaconda3/lib/python3.5/site-packages/django/urls/resolvers.py", line 533, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/cq/anaconda3/lib/python3.5/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/cq/anaconda3/lib/python3.5/site-packages/django/urls/resolvers.py", line 526, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/cq/anaconda3/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/cq/桌面/tmp/ocr_django/ocr_django/urls.py", line 18, in <module>
    from . import view
  File "/home/cq/桌面/tmp/ocr_django/ocr_django/view.py", line 22, in <module>
    from .ocr.recognize import recognize
  File "/home/cq/桌面/tmp/ocr_django/ocr_django/ocr/recognize.py", line 7, in <module>
    from .ctpn.text_detect import text_detect
  File "/home/cq/桌面/tmp/ocr_django/ocr_django/ocr/ctpn/text_detect.py", line 7, in <module>
    from .lib.utils.timer import Timer
  File "/home/cq/桌面/tmp/ocr_django/ocr_django/ocr/ctpn/lib/__init__.py", line 4, in <module>
    from ocr_django.ocr.ctpn.lib import fast_rcnn
  File "/home/cq/桌面/tmp/ocr_django/ocr_django/ocr/ctpn/lib/fast_rcnn/__init__.py", line 5, in <module>
    from . import train
  File "/home/cq/桌面/tmp/ocr_django/ocr_django/ocr/ctpn/lib/fast_rcnn/train.py", line 5, in <module>
    from ..roi_data_layer.layer import RoIDataLayer
  File "/home/cq/桌面/tmp/ocr_django/ocr_django/ocr/ctpn/lib/roi_data_layer/__init__.py", line 4, in <module>
    from . import roidb
  File "/home/cq/桌面/tmp/ocr_django/ocr_django/ocr/ctpn/lib/roi_data_layer/roidb.py", line 5, in <module>
    from ocr_django.ocr.ctpn.lib.utils.bbox import bbox_overlaps
  File "/home/cq/桌面/tmp/ocr_django/ocr_django/ocr/ctpn/lib/utils/__init__.py", line 11, in <module>
    from ocr_django.ocr.ctpn.lib.utils import bbox
ImportError: cannot import name 'bbox'

there are three files named:"bbox.c", "bbox.pyx","bbox.cpython-36m-x86_64-linux-gnu.so" in the package of ocr/ctpn/lib/utils. I've found a lot of solutions online, but none of them succeeded.
the solutions include:
1.right-click the project name in pycharm - > Mark Directory as - > source root to set the package as sources root
2.file - >setting - >project structure to set the package as source
3.change the code "from . import bbox" in /home/cq/桌面/tmp/ocr_django/ocr_django/ocr/ctpn/lib/utils/__init__.py to "from ocr_django.ocr.ctpn.lib.utils import bbox"

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
