### ISSUE TITLE
Initiate ClusterSpec.as_dict failed with only chief and ps

### ISSUE THREAD

**Issue by DeliangFan** [tensorflow/tensorflow#24165]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Linux 4.4.95.x86_64 #1 SMP Tue Jun 5 16:07:34 CST 2018 x86_64 x86_64 x86_64 GNU/Linux
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
No
- TensorFlow installed from (source or binary):
 Binary by pip
- TensorFlow version (use command below):
1.11
- Python version:
2.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
9.0.176
- GPU model and memory:
Tesla V100, 32G

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**

When initiate the RunConfig in the following code with only chief and ps, a error happends.

INFO:tensorflow:TF_CONFIG environment variable: {u'environment': u'cloud', u'cluster': {u'ps': [u'10.50.219.105:2222'], u'chief': [u'10.50.219.11:2222'], u'worker': []}, u'task': {u'index': 0, u'type': u'ps'}}

```
    gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.8, allow_growth=True)
    config = tf.ConfigProto(gpu_options=gpu_options,
                            log_device_placement=True)
    run_config = tf.estimator.RunConfig(save_checkpoints_steps=FLAGS.train_step / 10,
                                        keep_checkpoint_max=FLAGS.train_epochs * 100,
                                        log_step_count_steps=int(FLAGS.train_step / 400),
                                        save_summary_steps=int(FLAGS.train_step / 10),
                                        session_config=config
                                        )
```

Error tracing,

```
Traceback (most recent call last):
File "DCN/wide_dcn_onehot.py", line 490, in
tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
File "/app/python_venv/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
_sys.exit(main(argv))
File "DCN/wide_dcn_onehot.py", line 464, in main
model = build_estimator(FLAGS.model_dir)
File "DCN/wide_dcn_onehot.py", line 412, in build_estimator
save_summary_steps=int(FLAGS.train_step / 10)
File "/app/python_venv/lib/python2.7/site-packages/tensorflow/python/estimator/run_config.py", line 528, in __init__
self._init_distributed_setting_from_environment_var(tf_config)
File "/app/python_venv/lib/python2.7/site-packages/tensorflow/python/estimator/run_config.py", line 597, in _init_distributed_setting_from_environment_var
self._num_ps_replicas = _count_ps(self._cluster_spec)
File "/app/python_venv/lib/python2.7/site-packages/tensorflow/python/estimator/run_config.py", line 136, in _count_ps
return len(cluster_spec.as_dict().get(TaskType.PS, []))
File "/app/python_venv/lib/python2.7/site-packages/tensorflow/python/training/server_lib.py", line 335, in as_dict
if max(task_indices) + 1 == len(task_indices):
ValueError: max() arg is an empty sequence
```

**Describe the expected behavior**

Initiate success.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by DeliangFan** [comment]
This has been fixed, please close.
