### ISSUE TITLE
LSTM's .h5 to .tflite

### ISSUE THREAD

**Issue by JamesZhangjp** [tensorflow/tensorflow#24188]
thanks for your reading.
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):source
- TensorFlow version (use command below):1.12.0
- Python version:3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**
1.used the tf.keras to train the LSTM's model, and get the model.h5 file.
2.want convert the .h5 file to .tflite file ,and coded:
```
converter = tf.lite.TFLiteConverter.from_keras_model_file("model.h5")
tflite_model = converter.convert()
open("_model.tflite", "wb").write(tflite_model)
```
and get the error:
```
WARNING:tensorflow:From D:\python\python3\lib\site-packages\tensorflow\python\framework\graph_util_impl.py:245: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.compat.v1.graph_util.extract_sub_graph
Traceback (most recent call last):
  File "D:/code/load_forecast/test/test1.py", line 5, in <module>
    tflite_model = converter.convert()
  File "D:\python\python3\lib\site-packages\tensorflow\lite\python\lite.py", line 456, in convert
    **converter_kwargs)
  File "D:\python\python3\lib\site-packages\tensorflow\lite\python\convert.py", line 397, in toco_convert_impl
    input_data.SerializeToString())
  File "D:\python\python3\lib\site-packages\tensorflow\lite\python\convert.py", line 172, in toco_convert_protos
    "TOCO failed. See console for info.\n%s\n%s\n" % (stdout, stderr))
tensorflow.lite.python.convert.ConverterError: TOCO failed. See console for info.
2018-12-06 13:41:26.456495: I tensorflow/lite/toco/import_tensorflow.cc:1280] Converting unsupported operation: TensorArrayV3
.........
2018-12-06 13:41:26.495220: I tensorflow/lite/toco/import_tensorflow.cc:1329] Unable to determine output type for op: TensorArrayGatherV3
2018-12-06 13:41:26.506452: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 120 operators, 212 arrays (0 quantized)
2018-12-06 13:41:26.508258: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 120 operators, 212 arrays (0 quantized)
2018-12-06 13:41:26.513681: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 1: 106 operators, 194 arrays (0 quantized)
2018-12-06 13:41:26.515613: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before dequantization graph transformations: 106 operators, 194 arrays (0 quantized)
2018-12-06 13:41:26.517624: F tensorflow/lite/toco/tooling_util.cc:625] Check failed: dim >= 1 (0 vs. 1)
```
3.but success to convert the linear's and cnn's .h5 file to .tflite 

want to ask the question: Did someone successfully transform the .h5 model to .tflite?

look forward to your answer.

**Comment by t-kuha** [comment]
How about adding the line:

```python
converter.allow_custom_ops=True
```

**Comment by JamesZhangjp** [comment]
> How about adding the line:
> 
> ```python
> converter.allow_custom_ops=True
> ```

get the same error...

**Comment by AntoineWeber** [comment]
Same problem here @t-kuha . Trying to convert a CRNN using LSTM layers .h5 model (saved with keras) to .tflite and also getting 
`F tensorflow/lite/toco/tooling_util.cc:627] Check failed: dim >= 1 (0 vs. 1)`

Any suggestion yet ?

**Comment by AntoineWeber** [comment]
Hi everyone,

A quick search and I guess I found the reason of this error. The LSTM layer is not yet supported for custom models 
https://www.tensorflow.org/lite/tf_ops_compatibility
bottom of the page.

**Comment by JamesZhangjp** [comment]
@AntoineWeber tk, I have asked some people to give me the same reply before, but I hope to support LSTM as soon as possible.

**Comment by nparikhsfn** [comment]
@AntoineWeber , to be precise, it is tf.tanh not supported or LSTM, you can use it but need to fall back on Linear? Is my understanding correct?

**Comment by pigubaoza** [comment]
> @AntoineWeber , to be precise, it is tf.tanh not supported or LSTM, you can use it but need to fall back on Linear? Is my understanding correct?

any updates on which part isn't supported?

**Comment by AntoineWeber** [comment]
@nparikhsfn 
I don't understand what you mean by linear. But I guess you could reimplement yourself an lstm layer trying to dodge the use of tanh layers. GRU is not listed on this list (?) and it also contains tanh.
Haven't retried since then to convert models to tflite. If you really need to use layers which are not supported you can always try to compile Tensorflow for your embedded platform if your memory permits but this can be a pain.

@pigubaoza I guess you should stick to the list on this link : https://www.tensorflow.org/lite/tf_ops_compatibility

**Comment by jvishnuvardhan** [comment]
@JamesZhangjp This is a stale issue. If anyone looking for `LSTM` example, you can check this [`TF resource`](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/experimental/examples/lstm) where you can find couple of examples.

I am providing one complete example with recent `tf-nightly`. Please take a look at the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/45719f8614338f24ac3e2b6d6a3b42a7/untitled.ipynb). Thanks!

I am closing this issue. Feel free to reopen if there is any issue. Thanks!
