### ISSUE TITLE
Building Tensorflow lite on ARM64

### ISSUE THREAD

**Issue by liorko87** [tensorflow/tensorflow#24197]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): source
- Python version: 2.7.15rc/3.6.7
- Bazel version (if compiling from source): 0.20.0- (@non-git)
- GCC/Compiler version (if compiling from source): gcc (Ubuntu/Linaro 7.3.0-27ubuntu1~18.04) 7.3.0

**Describe the problem**

I'm trying to install tensorflow lite using bazel. I'm trying to compile it on AWS ARM 64 bit machine. 
I compiled tehnsorflow using the command:
`bazel test -c opt -- //tensorflow/... -//tensorflow/compiler/... -//tensorflow/lite/... --incompatible_remove_native_http_archive=false`
During the compilation I received this error message:

```
ImportError: Traceback (most recent call last):
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/ad1e09741bb4109fbc70ef8216b59ee2/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/ad1e09741bb4109fbc70ef8216b59ee2/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/ad1e09741bb4109fbc70ef8216b59ee2/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: /home/ubuntu/.cache/bazel/_bazel_ubuntu/ad1e09741bb4109fbc70ef8216b59ee2/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: _ZN3Aws11Environment6GetEnvB5cxx11EPKc

Failed to load the native TensorFlow runtime.

```

**Comment by liorko87** [comment]
I don't have CUDA on the server. I just want to compile tensorflow lite for my ARM device (It has Cortex A72 processor).

**Comment by freedomtan** [comment]
@liorko87 you saw
```
ImportError: /home/ubuntu/.cache/bazel/_bazel_ubuntu/ad1e09741bb4109fbc70ef8216b59ee2/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: _ZN3Aws11Environment6GetEnvB5cxx11EPKc
```
because platform dependent part of AWS SDK is not enabled for ARM64. I have a patch for this, see the [PR](https://github.com/tensorflow/tensorflow/pull/22856). What you can do is to either disable AWS SDK or try my patch.

**Comment by liorko87** [comment]
@freedomtan I managed to build successfully using your PR and by executing 
`bazel build //tensorflow/tools/pip_package:build_pip_package`.
Where does the `.whl` package located?
