### ISSUE TITLE
Tensorflow-GPU ImportError: DLL load failed

### ISSUE THREAD

**Issue by Cavan09** [tensorflow/tensorflow#24209]
### System information
- *OS:* Windows 10
- **TensorFlow version**: Tensorflow v 1.12
- **Python version**: 3.6.0
- **CUDA/cuDNN version**: CUDA 10.0, cuDNN 7.4.1.5
- **GPU model and memory**: 2080 ti

I'm trying to get Tensorflow set-up on my machine. I've followed about 10 different tutorials but always come back to this same issue. I see that a bunch of other people have the same issue and just downgraded their CUDA to 9.0 due to Tensorflow not supporting 10.0. My problem is that the 2080 ti is only supported with CUDA 10.0

Is anyone else using one of the RTX cards and have they had any of the same issues? My log is below.

### Source code / logs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\cmacphail\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\cmacphail\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\cmacphail\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\cmacphail\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\cmacphail\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\cmacphail\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\cmacphail\AppData\Local\Programs\Python\Python36\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\cmacphail\AppData\Local\Programs\Python\Python36\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

**Comment by ymodak** [comment]
If you want to use CUDA 10, then you have to build TF from sources yourself. You can refer this [tutorial](https://www.python36.com/how-to-install-tensorflow-gpu-with-cuda-10-0-for-python-on-windows/) created by other user who attempts to do the same.

**Comment by baihualinxin** [comment]
@Cavan09 
I suggest you use CUDA 9.0

**Comment by Cavan09** [comment]
@baihualinxin Do you know if I can use 9.0 with a 2080 ti. When I install 9.0 Nvidia throws a warning that my GPU is not supported and required 10.0.

@ymodak I'll give this tutorial a try and let you know if it worked, thanks :)

**Comment by Cavan09** [comment]
@ymodak 
So I've finally got everything built after about 5 different configurations. Now when I hit the last step of the tutorial where I verify the install, I get the following error:

import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\cmacphail\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\cmacphail\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\__init__.py", line 59, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "C:\Users\cmacphail\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\core\framework\graph_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
  File "C:\Users\cmacphail\AppData\Local\Programs\Python\Python36\lib\site-packages\google\protobuf\descriptor.py", line 47, in <module>
    from google.protobuf.pyext import _message
ImportError: DLL load failed: The specified procedure could not be found.

Any ideas?

**Comment by tynefung** [comment]
> @Cavan09
> I suggest you use CUDA 9.0


I installed CUDA9 and got this issue too.

OS: Windows 10
TensorFlow version: Tensorflow v 1.12
Python version: 3.6
CUDA/cuDNN version: CUDA 9, cuDNN 7

Anyone know how to solve it?

**Comment by tynefung** [comment]
@Cavan09  
It worked after I rebooted.
I think my issue is just caused by PATH.       
T^T
Thank you for your kindly reply!
