### ISSUE TITLE
TensorflowLite conversion failed using embedding layer.

### ISSUE THREAD

**Issue by Darthremar** [tensorflow/tensorflow#24223]
**System information**
- Windows 10 version 1803 x64
- TensorFlow installed from pip
- tf-nightly 1.13.0.dev20181129

**Provide the text output from tflite_convert**

```
2018-12-07 12:30:04.392840: I tensorflow/lite/toco/import_tensorflow.cc:1280] Converting unsupported operation: ResourceGather
2018-12-07 12:30:04.393575: I tensorflow/lite/toco/import_tensorflow.cc:1329] Unable to determine output type for op: ResourceGather
2018-12-07 12:30:04.518747: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 18 operators, 28 arrays (0 quantized)
2018-12-07 12:30:04.519109: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 18 operators, 28 arrays (0 quantized)
2018-12-07 12:30:04.519819: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 1: 7 operators, 14 arrays (0 quantized)
2018-12-07 12:30:04.707328: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 2: 6 operators, 13 arrays (0 quantized)
2018-12-07 12:30:04.707811: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 3: 5 operators, 11 arrays (0 quantized)
2018-12-07 12:30:04.708213: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before dequantization graph transformations: 5 operators, 11 arrays (0 quantized)
2018-12-07 12:30:04.708689: I tensorflow/lite/toco/allocate_transient_arrays.cc:345] Total transient array allocated size: 1216 bytes, theoretical optimal value: 1216 bytes.
2018-12-07 12:30:04.709343: E tensorflow/lite/toco/toco_tooling.cc:420] We are continually in the process of adding support to TensorFlow Lite for more ops. It would be helpful if you could inform us of how this conversion went by opening a github issue at https://github.com/tensorflow/tensorflow/issues/new?template=40-tflite-op-request.md
 and pasting the following:

Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: CAST, FULLY_CONNECTED, LOGISTIC. Here is a list of operators for which you will need custom implementations: ResourceGather.
Traceback (most recent call last):
  File "c:\users\dorme\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\dorme\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Dorme\Anaconda3\Scripts\toco_from_protos.exe\__main__.py", line 9, in <module>
  File "c:\users\dorme\anaconda3\lib\site-packages\tensorflow\lite\toco\python\toco_from_protos.py", line 59, in main
    app.run(main=execute, argv=[sys.argv[0]] + unparsed)
  File "c:\users\dorme\anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "c:\users\dorme\anaconda3\lib\site-packages\tensorflow\lite\toco\python\toco_from_protos.py", line 33, in execute
    output_str = tensorflow_wrap_toco.TocoConvert(model_str, toco_str, input_str)
Exception: We are continually in the process of adding support to TensorFlow Lite for more ops. It would be helpful if you could inform us of how this conversion went by opening a github issue at https://github.com/tensorflow/tensorflow/issues/new?template=40-tflite-op-request.md
 and pasting the following:

Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: CAST, FULLY_CONNECTED, LOGISTIC. Here is a list of operators for which you will need custom implementations: ResourceGather.
```

Using an Embedding, Flatten, Dense and Dense layers for text seems impossible i'm also using the library tokenizer from keras for preprocessing the data.

**Comment by harshini-gadige** [comment]
@Darthremar  We understand that you are having difficulties in using embedding layer(and others as you mentioned) with TF Lite. As per the above exception, I do notice that it is due to the unsupported ops by TF Lite. For any native TF ops(which you want to use in Lite) could you please try using extended runtime by passing  --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter()
We would encourage you to go through
