### ISSUE TITLE
Problem importing Tensorflow

### ISSUE THREAD

**Issue by HYDesmondLiu** [tensorflow/tensorflow#24230]
**System information**
- OS Platform Windows 10 
- Dell Inspiron 5500
- TensorFlow installed from (source or binary): pip install
- TensorFlow version:  N/A
- Python version: Python 3.6.7 :: Anaconda custom (64-bit)
- Installed using virtualenv? pip? conda?: conda
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): 
- CUDA/cuDNN version: CUDA 9.0
- GPU model and memory: N/A

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**
 Go into Python shell and import tensorflow and it failed...

**Any other info / logs**
(tensorflow) C:\Users\user>python
Python 3.6.7 |Anaconda custom (64-bit)| (default, Oct 28 2018, 19:44:12) [MSC v.1915 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\user\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\user\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\__init__.py", line 88, in <module>
    from tensorflow.python import keras
  File "C:\Users\user\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\keras\__init__.py", line 24, in <module>
    from tensorflow.python.keras import activations
  File "C:\Users\user\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\keras\activations\__init__.py", line 22, in <module>
    from tensorflow.python.keras._impl.keras.activations import elu
  File "C:\Users\user\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\keras\_impl\keras\__init__.py", line 21, in <module>
    from tensorflow.python.keras._impl.keras import activations
  File "C:\Users\user\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\keras\_impl\keras\activations.py", line 23, in <module>
    from tensorflow.python.keras._impl.keras import backend as K
  File "C:\Users\user\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\keras\_impl\keras\backend.py", line 37, in <module>
    from tensorflow.python.layers import base as tf_base_layers
  File "C:\Users\user\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\layers\base.py", line 25, in <module>
    from tensorflow.python.keras.engine import base_layer
  File "C:\Users\user\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\keras\engine\__init__.py", line 23, in <module>
    from tensorflow.python.keras.engine.base_layer import InputSpec
  File "C:\Users\user\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 35, in <module>
    from tensorflow.python.keras import backend
  File "C:\Users\user\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\keras\backend\__init__.py", line 22, in <module>
    from tensorflow.python.keras._impl.keras.backend import abs
ImportError: cannot import name 'abs'
>>>

**Comment by ymodak** [comment]
https://github.com/tensorflow/tensorflow/issues/20778#issuecomment-410962482

**Comment by ymodak** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
