### ISSUE TITLE
couldn't find "libtensorflow_demo.so"

### ISSUE THREAD

**Issue by datomnurdin** [tensorflow/tensorflow#2424]
I got this error message after ran on Android 5

```
05-19 13:21:33.731 27653-27653/org.tensorflow.demo E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: org.tensorflow.demo, PID: 27653
                                                                     java.lang.UnsatisfiedLinkError: com.android.tools.fd.runtime.IncrementalClassLoader$DelegateClassLoader[DexPathList[[dex file "/data/data/org.tensorflow.demo/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/org.tensorflow.demo/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/org.tensorflow.demo/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/org.tensorflow.demo/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/org.tensorflow.demo/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/org.tensorflow.demo/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/org.tensorflow.demo/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/org.tensorflow.demo/files/instant-run/dex/slice-slice_2-classes.dex", dex file "/data/data/org.tensorflow.demo/files/instant-run/dex/slice-slice_1-classes.dex", dex file "/data/data/org.tensorflow.demo/files/instant-run/dex/slice-slice_0-classes.dex"],nativeLibraryDirectories=[/vendor/lib, /system/lib, /vendor/lib, /system/lib]]] couldn't find "libtensorflow_demo.so"
                                                                         at java.lang.Runtime.loadLibrary(Runtime.java:366)
                                                                         at java.lang.System.loadLibrary(System.java:989)
                                                                         at org.tensorflow.demo.TensorflowClassifier.<clinit>(TensorflowClassifier.java:47)
                                                                         at org.tensorflow.demo.TensorflowImageListener.<init>(TensorflowImageListener.java:56)
                                                                         at org.tensorflow.demo.CameraConnectionFragment.<init>(CameraConnectionFragment.java:445)
                                                                         at org.tensorflow.demo.CameraConnectionFragment.newInstance(CameraConnectionFragment.java:266)
                                                                         at org.tensorflow.demo.CameraActivity.onCreate(CameraActivity.java:33)
                                                                         at android.app.Activity.performCreate(Activity.java:6289)
                                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2758)
                                                                         at android.app.ActivityThread.access$900(ActivityThread.java:177)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1448)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:145)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5942)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at java.lang.reflect.Method.invoke(Method.java:372)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1389)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1184)
```

P.S: BTW i'm using android studio for this project (converted into gradle project based).

Please advice. Thank you.

**Comment by andrewharp** [comment]
Can you check and see if libtensorflow_demo.so is in the apk, and built for the correct target architecture? Just unzip -v to see the contents. It sounds like the native libraries (the .cc code) are either not getting built, or not getting packaged into the apk properly.

Gradle support is outside the scope of Tensorflow github issues, but I would suggest looking for differences between [this](https://github.com/miyosuda/TensorFlowAndroidDemo/tree/master/jni-build) known working Gradle/Android build of Tensorflow and yours to see if you can spot the difference.

**Comment by andrewharp** [comment]
Hi, were you able to resolve the issue?

**Comment by andrewharp** [comment]
Closing, please reopen if problem persists.

**Comment by riccitensor** [comment]
I am having this problem as well -- https://github.com/tensorflow/tensorflow/issues/2530

**Comment by sulc** [comment]
I encountered the same error when moving my project to Android Studio.
It can be resolved simply by extracting libtensorflow_demo.so from the APK built by bazel and copying it to the Android Studio project to app/src/main/jniLibs/armeabi-v7a/ .

**Comment by andrewharp** [comment]
You can find full instructions for building the Tensorflow demo in Android studio here: https://github.com/tensorflow/tensorflow/issues/3444

Bazel is still required, though.
