### ISSUE TITLE
Error on retraining flowers

### ISSUE THREAD

**Issue by DKP-90** [tensorflow/tensorflow#2427]
Creating bottleneck at /tmp/bottleneck/roses/8949720453_66e8304c30.jpg.txt
Traceback (most recent call last):
  File "/home/ubuntu/tensorflow/bazel-bin/tensorflow/examples/image_retraining/retrain.runfiles/tensorflow/examples/image_retraining/retrain.py", line 827, in <module>
    tf.app.run()
  File "/home/ubuntu/tensorflow/bazel-bin/tensorflow/examples/image_retraining/retrain.runfiles/tensorflow/python/platform/default/_app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "/home/ubuntu/tensorflow/bazel-bin/tensorflow/examples/image_retraining/retrain.runfiles/tensorflow/examples/image_retraining/retrain.py", line 754, in main
    bottleneck_tensor)
  File "/home/ubuntu/tensorflow/bazel-bin/tensorflow/examples/image_retraining/retrain.runfiles/tensorflow/examples/image_retraining/retrain.py", line 676, in add_final_training_ops
    bottleneck_input = tf.placeholder_with_default(
AttributeError: 'module' object has no attribute 'placeholder_with_default'

**Comment by mrry** [comment]
Which version of TensorFlow are you running? You will need to upgrade to version 0.8 for that example code to work.

**Comment by DKP-90** [comment]
Thanks @mrry
