### ISSUE TITLE
NameError: name 'disclaim_key_flags' is not defined

### ISSUE THREAD

**Issue by mksarker** [tensorflow/tensorflow#24270]
After update version 1.12 the error shows as below;
----> 1 import tensorflow as tf

~/anaconda3/lib/python3.6/site-packages/tensorflow/__init__.py in <module>()
     20
     21 # pylint: disable=g-bad-import-order
---> 22 from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
     23
     24 try:

~/anaconda3/lib/python3.6/site-packages/tensorflow/python/__init__.py in <module>()
     61
     62 # Framework
---> 63 from tensorflow.python.framework.framework_lib import *  # pylint: disable=redefined-builtin
     64 from tensorflow.python.framework.versions import *
     65 from tensorflow.python.framework import errors

~/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/framework_lib.py in <module>()
     23 # Classes used when building a Graph.
     24 from tensorflow.python.framework.device import DeviceSpec
---> 25 from tensorflow.python.framework.ops import Graph
     26 from tensorflow.python.framework.ops import Operation
     27 from tensorflow.python.framework.ops import Tensor

~/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py in <module>()
     53 from tensorflow.python.framework import versions
     54 from tensorflow.python.ops import control_flow_util
---> 55 from tensorflow.python.platform import app
     56 from tensorflow.python.platform import tf_logging as logging
     57 from tensorflow.python.util import compat

~/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py in <module>()
     22 import sys as _sys
     23
---> 24 from tensorflow.python.platform import flags
     25 from tensorflow.python.util.tf_export import tf_export
     26

~/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/flags.py in <module>()
     31 # Since we wrap absl.flags DEFINE functions, we need to declare this module
     32 # does not affect key flags.
---> 33 disclaim_key_flags()  # pylint: disable=undefined-variable
     34
     35

NameError: name 'disclaim_key_flags' is not defined

please help!!

**Comment by harshini-gadige** [comment]
Please upgrade pip version and retry. Also request you to fill this template which helps us to look into this in  detail. Thank you !

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
It has been 29 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by mksarker** [comment]
Thanks. The issue was solved.

**Comment by nirvaanGarg** [comment]
Hi i came across the same issue and haven't found the answer through pip upgrade and reinstall

here is what i got back 

Traceback (most recent call last):
  File "train.py", line 47, in <module>
    import tensorflow as tf
  File "C:\Users\Nirvaan Garg\Python\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\Nirvaan Garg\Python\lib\site-packages\tensorflow\python\__init__.py", line 63, in <module>
    from tensorflow.python.framework.framework_lib import *  # pylint: disable=redefined-builtin
  File "C:\Users\Nirvaan Garg\Python\lib\site-packages\tensorflow\python\framework\framework_lib.py", line 25, in <module>
    from tensorflow.python.framework.ops import Graph
  File "C:\Users\Nirvaan Garg\Python\lib\site-packages\tensorflow\python\framework\ops.py", line 53, in <module>
    from tensorflow.python.platform import app
  File "C:\Users\Nirvaan Garg\Python\lib\site-packages\tensorflow\python\platform\app.py", line 24, in <module>
    from tensorflow.python.platform import flags
  File "C:\Users\Nirvaan Garg\Python\lib\site-packages\tensorflow\python\platform\flags.py", line 33, in <module>
    disclaim_key_flags()  # pylint: disable=undefined-variable
NameError: name 'disclaim_key_flags' is not defined

(base) C:\Users\Nirvaan Garg\Documents\Python code for work\TI_OD\Object Detection>pip install -U pip
Requirement already up-to-date: pip in c:\users\nirvaan garg\python\lib\site-packages (19.0.3)

would love a response on this please, thank you for your help
