### ISSUE TITLE
[Tensorflow tutorial: speech commands] svdf model doesn't work in the demo app 

### ISSUE THREAD

**Issue by huHHhhuhu** [tensorflow/tensorflow#24309]
**Describe the current behavior**
Hi all,
I'm trying the speech commands tutorial of Tensorflow.
But when I run the low latency svdf model in the demo app, it doesn't work.
It showed the error as **Other info / logs** below.
I saw the same issue here: https://github.com/tensorflow/tensorflow/issues/13868
But it seems there's no specific and detailed solution.
Could anyone help me with this?
Thanks! 
David 

**Code to reproduce the issue**
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/speech_commands
https://www.tensorflow.org/versions/master/tutorials/audio_recognition

**Other info / logs**
E/zygote64: No implementation found for long org.tensorflow.contrib.android.RunStats.allocate() (tried Java_org_tensorflow_contrib_android_RunStats_allocate and Java_org_tensorflow_contrib_android_RunStats_allocate__)

E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: org.tensorflow.demo, PID: 13070
                  java.lang.RuntimeException: Unable to start activity ComponentInfo{org.tensorflow.demo/org.tensorflow.demo.SpeechActivity}: java.lang.RuntimeException: Failed to load model from 'file:///android_asset/low_latency_svdf-135000.pb'
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2904)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2979)
                      at android.app.ActivityThread.-wrap11(Unknown Source:0)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1643)
                      at android.os.Handler.dispatchMessage(Handler.java:105)
                      at android.os.Looper.loop(Looper.java:180)
                      at android.app.ActivityThread.main(ActivityThread.java:6944)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:853)
                   Caused by: java.lang.RuntimeException: Failed to load model from 'file:///android_asset/low_latency_svdf-135000.pb'
                      at org.tensorflow.contrib.android.TensorFlowInferenceInterface.<init>(TensorFlowInferenceInterface.java:113)
                      at org.tensorflow.demo.SpeechActivity.onCreate(SpeechActivity.java:152)
                      at android.app.Activity.performCreate(Activity.java:6986)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1232)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2857)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2979) 
                      at android.app.ActivityThread.-wrap11(Unknown Source:0) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1643) 
                      at android.os.Handler.dispatchMessage(Handler.java:105) 
                      at android.os.Looper.loop(Looper.java:180) 
                      at android.app.ActivityThread.main(ActivityThread.java:6944) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:853) 
                   Caused by: java.io.IOException: Not a valid TensorFlow Graph serialization: Value for attr 'T' of int64 is not in the list of allowed values: float, int32, qint8, quint8, qint32
                  	; NodeDef: {{node count_nonzero/Sum}} = Sum[T=DT_INT64, Tidx=DT_INT32, keep_dims=false](count_nonzero/ToInt64, count_nonzero/Const); Op<name=Sum; signature=input:T, reduction_indices:Tidx -> output:T; attr=keep_dims:bool,default=false; attr=T:type,allowed=[DT_FLOAT, DT_INT32, DT_QINT8, DT_QUINT8, DT_QINT32]; attr=Tidx:type,default=DT_INT32,allowed=[DT_INT32, DT_INT64]>
                      at org.tensorflow.contrib.android.TensorFlowInferenceInterface.loadGraph(TensorFlowInferenceInterface.java:561)
                      at org.tensorflow.contrib.android.TensorFlowInferenceInterface.<init>(TensorFlowInferenceInterface.java:105)
                      	... 13 more

**Comment by petewarden** [comment]
Passing to Rocky, since he's been looking at this.

**Comment by rockyrhodes** [comment]
Just checked in a small change to the svdf model that fixes this.
