### ISSUE TITLE
`import tensorflow` fails after `import pandas`; RUNPATH seemingly ignored

### ISSUE THREAD

**Issue by michaelgreenburg** [tensorflow/tensorflow#24346]
### System information
| Category | Info |
| --- | --- |
| Have I written custom code? | no |
| OS/distro | Linux, RHEL 7.4 |
| TF installed from | source |
| TF version | 1.9.0 |
| Python version | 3.6.5 |
| Bazel version | 0.14.1 |
| GCC version | 7.3.0 |
| CUDA/cuDNN version | 9.2.88 and 7.1.4 |
| GPU model/memory | 16 GB |
| Command to reporoduce | `import pandas; import tensorflow` |

### Problem description

The successful import of pandas and TensorFlow depends on the order in which they are loaded:

```python
# Works
import tensorflow
import pandas
```

```python
# Fails
import pandas
import tensorflow
```

The full error message is below, but here's an excerpt:

```
Traceback (most recent call last):
  File "/apps/python-3.6.5-tensorflow/1.9.0/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
...
  File "/apps/python/3.6.5/gcc-7.3.0/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /apps/python-3.6.5-tensorflow/1.9.0/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)
```

What's confusing for me: `_pywrap_tensorflow_internal.so`'s RUNPATH contains `/apps/gcc/7.3.0/lib64`, which has the version of `libstdc++.so.6` that should be (and normally is) used, and LD_LIBRARY_PATH is not set--so I'm confused as to why `/lib64/libstdc++.so.6` even enters the equation. It also seems wrong that the order of import dictates which `libstdc++.so.6` is used.

Just to be sure, I temporarily changed  `_pywrap_tensorflow_internal.so`'s RUNPATH to an RPATH in case pandas was (weirdly) setting LD_LIBRARY_PATH, but it made no difference--the same error persists.

Reproducing might be annoying/not worth the time, but in case anyone wants to try I built Python and TensorFlow from source using GCC 7.3.0 (which was itself built from source) and installed pandas with pip. I would be just as happy with a suggestion on what to try next/where to look around, though.

### Source code / logs

Full error message:

```
>>> import pandas
>>> import tensorflow
Traceback (most recent call last):
  File "/apps/python-3.6.5-tensorflow/1.9.0/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/apps/python-3.6.5-tensorflow/1.9.0/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/apps/python-3.6.5-tensorflow/1.9.0/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/apps/python/3.6.5/gcc-7.3.0/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/apps/python/3.6.5/gcc-7.3.0/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /apps/python-3.6.5-tensorflow/1.9.0/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/apps/python-3.6.5-tensorflow/1.9.0/lib/python3.6/site-packages/tensorflow/__init__.py", line 22, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/apps/python-3.6.5-tensorflow/1.9.0/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/apps/python-3.6.5-tensorflow/1.9.0/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/apps/python-3.6.5-tensorflow/1.9.0/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/apps/python-3.6.5-tensorflow/1.9.0/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/apps/python-3.6.5-tensorflow/1.9.0/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/apps/python/3.6.5/gcc-7.3.0/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/apps/python/3.6.5/gcc-7.3.0/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /apps/python-3.6.5-tensorflow/1.9.0/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

**Comment by harshini-gadige** [comment]
This should not happen with the latest tensorflow version. Could you please try with the TF version 1.12 and see if you are running into this issue. Also please upgrade pandas with pip install --upgrade pandas.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by michaelgreenburg** [comment]
Sorry for the late response. I went ahead and updated pandas and installed TF 1.12 with bazel 0.15, but ran into a similar (probably related?) issue:

```python
>>> import pandas 
>>> import tensorflow
Traceback (most recent call last):
  File "/apps/python-3.6.5-tensorflow/1.12.0/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/apps/python-3.6.5-tensorflow/1.12.0/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/apps/python-3.6.5-tensorflow/1.12.0/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/apps/python/3.6.5/gcc-7.3.0/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/apps/python/3.6.5/gcc-7.3.0/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /apps/python-3.6.5-tensorflow/1.12.0/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/apps/python-3.6.5-tensorflow/1.12.0/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/apps/python-3.6.5-tensorflow/1.12.0/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/apps/python-3.6.5-tensorflow/1.12.0/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/apps/python-3.6.5-tensorflow/1.12.0/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/apps/python-3.6.5-tensorflow/1.12.0/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/apps/python-3.6.5-tensorflow/1.12.0/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/apps/python/3.6.5/gcc-7.3.0/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/apps/python/3.6.5/gcc-7.3.0/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /apps/python-3.6.5-tensorflow/1.12.0/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)


Failed to load the native TensorFlow runtime.
```

As before, `ldd` shows that the libraries can find the right `libstdc++.so.6` rather than just using the one in `/lib64`:

```console
$ ldd $PFX/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so | grep libstdc++
	libstdc++.so.6 => /apps/gcc/7.3.0/lib64/libstdc++.so.6 (0x00007fe506c34000)
$ ldd $PFX/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so | grep libstdc++
	libstdc++.so.6 => /apps/gcc/7.3.0/lib64/libstdc++.so.6 (0x00007f4e48211000)
```

**Comment by gunan** [comment]
Thanks for the report.
Adding @allenlavoie @jhseu

**Comment by gunan** [comment]
Also adding @yifeif @hlopko 
Marcel, is it possible that when building from sources, bazel ends up using a different libstdc++ then pandas is configured to use?

**Comment by allenlavoie** [comment]
Could you try running something like:

`strace python3.6 -c "import tensorflow" 2>&1 | grep libstdc`

and 

`strace python3.6 -c "import pandas; import tensorflow" 2>&1 | grep libstdc`

It would be nice to know what ends up loading the lib64 one.

**Comment by allenlavoie** [comment]
Oh interesting, yeah the `-B15` is helpful there. So it looks like matplotlib is going straight for the /lib64/ version, then the linker uses the cached /lib64/ load for TensorFlow.

I'm not sure what TF can do in this case. Presumably it works if you `LD_PRELOAD=/apps/gcc/7.3.0/lib64/libstdc++.so.6 python3.6 -c "import pandas; import tensorflow"` ? That should be more or less equivalent to what happens when the imports are in the other order. Since the newer libstdc++ gets used and it's backwards compatible, both libraries are happy. Conversely, LD_PRELOAD with the /lib64/ version presumably fails because that version isn't forward compatible with the version TF was compiled against.

Maybe the thing to investigate then is why matplotlib is going for the /lib64/ version first. Maybe there's a way to configure its search paths so it goes for the newer libstdc++?

**Comment by michaelgreenburg** [comment]
Yeah, setting LD_PRELOAD/prepending to LD_LIBRARY_PATH works. I'll just do that for now, and report back here if I find a less [dangerous](http://xahlee.info/UnixResource_dir/_/ldpath.html) solution. I guess this doesn't really have to do with TF so much as the overall setup--sorry for the noise!
