### ISSUE TITLE
crash when run distributed training while using s3 tensorflow

### ISSUE THREAD

**Issue by mmuppidi** [tensorflow/tensorflow#24357]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): I wrote a custom estimator
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): tensorflow/tensorflow:1.11.0-gpu-py3 docker image
- TensorFlow version (use command below): tensorflow:1.11.0
- Python version: Python 3.5.2
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: cuda:9.0
- GPU model and memory: K80 (AWS EC2 P2.8xlarge instance)

I am using [s3 tensorflow](https://www.tensorflow.org/deploy/s3) for reading the data and writing models-checkpoints/logs 

**Other info / logs**
```
2018-12-14 01:07:09.544639: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1103] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10755 MB memory) -> physical GPU (device: 0, name: Tesla K80, pci bus id: 0000:00:0f.0, compute capability: 3.7)
2018-12-14 01:07:09.544952: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1103] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 10755 MB memory) -> physical GPU (device: 1, name: Tesla K80, pci bus id: 0000:00:10.0, compute capability: 3.7)
2018-12-14 01:07:09.545164: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1103] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:2 with 10755 MB memory) -> physical GPU (device: 2, name: Tesla K80, pci bus id: 0000:00:11.0, compute capability: 3.7)
2018-12-14 01:07:09.545382: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1103] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:3 with 10755 MB memory) -> physical GPU (device: 3, name: Tesla K80, pci bus id: 0000:00:12.0, compute capability: 3.7)
2018-12-14 01:07:09.545589: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1103] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:4 with 10755 MB memory) -> physical GPU (device: 4, name: Tesla K80, pci bus id: 0000:00:13.0, compute capability: 3.7)
2018-12-14 01:07:09.545833: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1103] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:5 with 10755 MB memory) -> physical GPU (device: 5, name: Tesla K80, pci bus id: 0000:00:14.0, compute capability: 3.7)
2018-12-14 01:07:09.546042: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1103] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:6 with 10755 MB memory) -> physical GPU (device: 6, name: Tesla K80, pci bus id: 0000:00:15.0, compute capability: 3.7)
2018-12-14 01:07:09.546242: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1103] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:7 with 10755 MB memory) -> physical GPU (device: 7, name: Tesla K80, pci bus id: 0000:00:16.0, compute capability: 3.7)
2018-12-14 01:07:09.546421: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1103] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:8 with 10755 MB memory) -> physical GPU (device: 8, name: Tesla K80, pci bus id: 0000:00:17.0, compute capability: 3.7)
2018-12-14 01:07:09.546635: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1103] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:9 with 10755 MB memory) -> physical GPU (device: 9, name: Tesla K80, pci bus id: 0000:00:18.0, compute capability: 3.7)
2018-12-14 01:07:09.546835: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1103] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:10 with 10755 MB memory) -> physical GPU (device: 10, name: Tesla K80, pci bus id: 0000:00:19.0, compute capability: 3.7)
2018-12-14 01:07:09.547045: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1103] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:11 with 10755 MB memory) -> physical GPU (device: 11, name: Tesla K80, pci bus id: 0000:00:1a.0, compute capability: 3.7)
2018-12-14 01:07:09.547274: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1103] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:12 with 10755 MB memory) -> physical GPU (device: 12, name: Tesla K80, pci bus id: 0000:00:1b.0, compute capability: 3.7)
2018-12-14 01:07:09.547484: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1103] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:13 with 10755 MB memory) -> physical GPU (device: 13, name: Tesla K80, pci bus id: 0000:00:1c.0, compute capability: 3.7)
2018-12-14 01:07:09.547688: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1103] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:14 with 10755 MB memory) -> physical GPU (device: 14, name: Tesla K80, pci bus id: 0000:00:1d.0, compute capability: 3.7)
2018-12-14 01:07:09.547886: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1103] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:15 with 10755 MB memory) -> physical GPU (device: 15, name: Tesla K80, pci bus id: 0000:00:1e.0, compute capability: 3.7)
2018-12-14 01:07:09.551770: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2018-12-14 01:07:09.627089: E tensorflow/core/platform/s3/aws_logging.cc:60] No response body. Response code: 404
2018-12-14 01:07:09.627194: W tensorflow/core/platform/s3/aws_logging.cc:57] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.
2018-12-14 01:07:09.627373: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2018-12-14 01:10:25.265510: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2018-12-14 01:10:25.330682: E tensorflow/core/platform/s3/aws_logging.cc:60] No response body. Response code: 404
2018-12-14 01:10:25.330719: W tensorflow/core/platform/s3/aws_logging.cc:57] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.
2018-12-14 01:10:25.330857: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2018-12-14 01:12:58.847158: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2018-12-14 01:13:06.793996: I tensorflow/core/platform/s3/aws_logging.cc:54] Deleting file: /tmp/s3_filesystem_XXXXXX20181214T0112571544749977988
2018-12-14 01:13:06.861344: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2018-12-14 01:13:06.883504: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2018-12-14 01:13:09.892293: E tensorflow/core/platform/s3/aws_logging.cc:60] Curl returned error code 28
2018-12-14 01:13:09.892400: W tensorflow/core/platform/s3/aws_logging.cc:57] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.
2018-12-14 01:13:09.892433: W tensorflow/core/platform/s3/aws_logging.cc:57] Request failed, now waiting 0 ms before attempting again.
2018-12-14 01:13:09.892867: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2018-12-14 01:13:13.899888: E tensorflow/core/platform/s3/aws_logging.cc:60] Curl returned error code 28
2018-12-14 01:13:13.899977: W tensorflow/core/platform/s3/aws_logging.cc:57] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.
2018-12-14 01:13:13.899996: W tensorflow/core/platform/s3/aws_logging.cc:57] Request failed, now waiting 50 ms before attempting again.
2018-12-14 01:13:13.950970: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2018-12-14 01:13:17.957128: E tensorflow/core/platform/s3/aws_logging.cc:60] Curl returned error code 28
2018-12-14 01:13:17.957192: W tensorflow/core/platform/s3/aws_logging.cc:57] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.
2018-12-14 01:13:17.957212: W tensorflow/core/platform/s3/aws_logging.cc:57] Request failed, now waiting 100 ms before attempting again.
2018-12-14 01:13:18.058715: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2018-12-14 01:13:22.065071: E tensorflow/core/platform/s3/aws_logging.cc:60] Curl returned error code 28
2018-12-14 01:13:22.065155: W tensorflow/core/platform/s3/aws_logging.cc:57] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.
2018-12-14 01:13:22.065181: W tensorflow/core/platform/s3/aws_logging.cc:57] Request failed, now waiting 200 ms before attempting again.
2018-12-14 01:13:22.266342: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2018-12-14 01:13:26.273044: E tensorflow/core/platform/s3/aws_logging.cc:60] Curl returned error code 28
2018-12-14 01:13:26.273111: W tensorflow/core/platform/s3/aws_logging.cc:57] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.
2018-12-14 01:13:26.273143: W tensorflow/core/platform/s3/aws_logging.cc:57] Request failed, now waiting 400 ms before attempting again.
2018-12-14 01:13:26.674870: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2018-12-14 01:13:30.681963: E tensorflow/core/platform/s3/aws_logging.cc:60] Curl returned error code 28
2018-12-14 01:13:30.682039: W tensorflow/core/platform/s3/aws_logging.cc:57] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.
2018-12-14 01:13:30.682059: W tensorflow/core/platform/s3/aws_logging.cc:57] Request failed, now waiting 800 ms before attempting again.
2018-12-14 01:13:31.483287: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2018-12-14 01:13:35.489697: E tensorflow/core/platform/s3/aws_logging.cc:60] Curl returned error code 28
2018-12-14 01:13:35.489748: W tensorflow/core/platform/s3/aws_logging.cc:57] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.
2018-12-14 01:13:35.489766: W tensorflow/core/platform/s3/aws_logging.cc:57] Request failed, now waiting 1600 ms before attempting again.
2018-12-14 01:13:37.090948: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2018-12-14 01:13:41.097136: E tensorflow/core/platform/s3/aws_logging.cc:60] Curl returned error code 28
2018-12-14 01:13:41.097251: W tensorflow/core/platform/s3/aws_logging.cc:57] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.
2018-12-14 01:13:41.097272: W tensorflow/core/platform/s3/aws_logging.cc:57] Request failed, now waiting 3200 ms before attempting again.
2018-12-14 01:13:44.299654: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2018-12-14 01:13:48.307090: E tensorflow/core/platform/s3/aws_logging.cc:60] Curl returned error code 28
2018-12-14 01:13:48.307182: W tensorflow/core/platform/s3/aws_logging.cc:57] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.
2018-12-14 01:13:48.307208: W tensorflow/core/platform/s3/aws_logging.cc:57] Request failed, now waiting 6400 ms before attempting again.
2018-12-14 01:13:54.709486: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2018-12-14 01:13:58.715801: E tensorflow/core/platform/s3/aws_logging.cc:60] Curl returned error code 28
2018-12-14 01:13:58.715869: W tensorflow/core/platform/s3/aws_logging.cc:57] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.
2018-12-14 01:13:58.715895: W tensorflow/core/platform/s3/aws_logging.cc:57] Request failed, now waiting 12800 ms before attempting again.
2018-12-14 01:14:11.518412: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2018-12-14 01:14:15.525502: E tensorflow/core/platform/s3/aws_logging.cc:60] Curl returned error code 28
2018-12-14 01:14:15.525595: W tensorflow/core/platform/s3/aws_logging.cc:57] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.
2018-12-14 01:14:15.526863: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
Traceback (most recent call last):
File "train.py", line 191, in <module>
tf.app.run()
File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 125, in run
_sys.exit(main(argv))
File "train.py", line 182, in main
cyclegan_estimator.train(train_input_fn, steps=FLAGS.steps_per_eval)
File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 356, in train
loss = self._train_model(input_fn, hooks, saving_listeners)
File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 1179, in _train_model
return self._train_model_distributed(input_fn, hooks, saving_listeners)
File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 1326, in _train_model_distributed
saving_listeners)
File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 1406, in _train_with_estimator_spec
log_step_count_steps=self._config.log_step_count_steps) as mon_sess:
File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 504, in MonitoredTrainingSession
stop_grace_period_secs=stop_grace_period_secs)
File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 921, in __init__
stop_grace_period_secs=stop_grace_period_secs)
File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 643, in __init__
self._sess = _RecoverableSession(self._coordinated_creator)
File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 1107, in __init__
_WrappedSession.__init__(self, self._create_session())
File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 1112, in _create_session
return self._sess_creator.create_session()
File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 807, in create_session
hook.after_create_session(self.tf_sess, self.coord)
File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/basic_session_run_hooks.py", line 558, in after_create_session
"graph.pbtxt")
File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/graph_io.py", line 71, in write_graph
text_format.MessageToString(graph_def))
File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/lib/io/file_io.py", line 436, in atomic_write_string_to_file
rename(temp_pathname, filename, overwrite)
File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/lib/io/file_io.py", line 415, in rename
compat.as_bytes(oldname), compat.as_bytes(newname), overwrite, status)
File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 526, in __exit__
c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.UnknownError: : Unable to connect to endpoint
```

**Comment by mmuppidi** [comment]
@cathybgyz  I am running this on AWS Batch and I am sure that credentials are properly setup. But you raised some good points, I am going to talk to AWS support and see why this is happening. Thanks for the insights.

**Comment by yw411** [comment]
@mmuppidi , I want to ask whether you solve this problem.

**Comment by mmuppidi** [comment]
@yw411 we had to increase the s3 request timeout to get this to work.

```
export S3_REQUEST_TIMEOUT_MSEC=60000
```
Ref: https://github.com/tensorflow/tensorflow/issues/15868

**Comment by rmothukuru** [comment]
@mmuppidi ,
Can you please confirm if we can close this issue, as it worked for you.

**Comment by xxllp** [comment]
have the same error  but does not solve
