### ISSUE TITLE
Exception ignored, Session closed

### ISSUE THREAD

**Issue by Ploppz** [tensorflow/tensorflow#24367]
**System information**
- Have I written custom code: Yes
- OS Platform and Distribution: Arch Linux
- TensorFlow installed from (source or binary): Official repository
- TensorFlow version: v1.11.0-0-gc19e29306c 1.11.0
- Python version: 3.6.6
- GPU model: AMD Radeon HD 7850

**Describe the current behavior (+ code)**
Here is my code: https://bpaste.net/show/82f2837ef498
It uses the environment `AcrobotForever-v1` which is really just a modification of the Acrobot env that never terminates. (additionally, I made it have 4 state variables: `(angle 1, angle 2, angle_vel 1, angle_vel 2)`. Code for the modified environment: https://github.com/Ploppz/gym-custom-envs

My code defines an agent acting in the Acrobot environment. It has 3 neural networks, but to make it all minimal I found that if it just takes random actions, I still get the errors. It still `fit`s those neural networks in the `think` function though.

While training I get this error after some random amount of time:

```
Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f1ec3fcd9e8>>
Traceback (most recent call last):
  File "/home/ploppz/.pyenv/versions/3.6.6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1415, in __del__
    self._session._session, self._handle, status)
  File "/home/ploppz/.pyenv/versions/3.6.6/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 526, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.
Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f1ec3497e10>>
Traceback (most recent call last):
  File "/home/ploppz/.pyenv/versions/3.6.6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1415, in __del__
    self._session._session, self._handle, status)
  File "/home/ploppz/.pyenv/versions/3.6.6/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 526, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.
Iter 5, timesteps=6000: coverage = 6.2595697434743025
Iter 6, timesteps=6000: coverage = 5.409617917650649
Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f1ec3670da0>>
Traceback (most recent call last):
  File "/home/ploppz/.pyenv/versions/3.6.6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1415, in __del__
    self._session._session, self._handle, status)
  File "/home/ploppz/.pyenv/versions/3.6.6/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 526, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.
```

**Comment by cathybgyz** [comment]
We may be able to find more insight into your issue if you can figure out what the exception was. It looks like the exception is caught but the descriptions was not provided when handled ("ignored").

**Comment by Ploppz** [comment]
How can I find the exception?

**Comment by jvishnuvardhan** [comment]
@Ploppz  Could you give more details and the context to find root-cause of the issue. Could you test with a very simple models and provide the code and the error log?

**Comment by jvishnuvardhan** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by Ploppz** [comment]
Sorry for the delay. I have a more or less minimal example that should run if you have all the dependencies. It consists of two files:
`experiment.py`:

```
from model_based import ModelBasedAgent
import gym
import numpy as np
from types import MethodType
import random
import tensorflow as tf
from matplotlib import pyplot as plt
import os
import datetime
import pickle

sample_period = 100 # How often to look at coverage for plotting
def experiment(env, agent, timesteps, render=False):
    global sample_period
    ob_space_dim = env.observation_space.shape[0]
    state = env.reset()
    state = np.array([state])
    scores =  []
    for t in range(1, timesteps+1):
        # Act
        action, v_pred = agent.act(state)
        # Step
        state_next, _reward, _terminal, _info = env.step(action)
        state_next = np.reshape(state_next, [1, ob_space_dim])
        # Think
        agent.think(state, action, state_next, v_pred)
        # Render
        if render:
            env.render()
        # Gather data
        if t % sample_period == 0:
            score = agent.covered_volume() * 100
            scores.append(score)
    return scores


#  def several_experiments(env, agent, n_experiments=18, timesteps=7000, color='blue'):
def several_experiments(env, agent, n_experiments=3, timesteps=800, color='blue'):
    global sample_period
    scores = np.zeros((n_experiments, int(timesteps/sample_period)))
    for i in range(n_experiments):
        with tf.Session() as sess:
            agent.reset()
            sess.run(tf.global_variables_initializer())
            # Scores
            scores[i, :] = experiment(env, agent, timesteps)
            print("Iter %s, timesteps=%s: coverage = %s" % (i, timesteps, scores[i, -1]))
        tf.reset_default_graph()

if __name__ == '__main__':
    ENV_NAME = "AcrobotForever-v1"
    env = gym.make(ENV_NAME)

    EPSILON = 0.1

    agent = ModelBasedAgent(env)
    agent.exploration_rate = EPSILON
    several_experiments(env, agent)
```

and `model_based.py` which contains the agent, using tensorflow:
```
import random
import gym
import acrobot_forever
import numpy as np
from collections import deque
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam
from matplotlib import pyplot as plt
from scipy.spatial import ConvexHull
import time
import tensorflow as tf

class ModelBasedAgent:
    def __init__(self, env, act=None):
        from types import MethodType
        if not act is None:
            self.act = MethodType(act, self)

        # Custom initializer
        from keras import backend as K
        def network_init(shape, dtype=None):
            return np.random.random(shape) * 10 - 5

        self.advantage_learning = None
        self.env = env
        self.states = []
        self.exploration_rate = 0.0
        self.n_actions = env.action_space.n
        self.ob_dim = env.observation_space.shape[0]

        # Model network n: (s, a) -> ds
        self.model_net = Sequential()
        self.model_net.add(Dense(12, input_shape=(self.ob_dim + 1,), activation="relu"))
        self.model_net.add(Dense(12, activation="relu"))
        self.model_net.add(Dense(self.ob_dim, activation="linear"))
        self.model_net.compile(loss="mse", optimizer=Adam(lr=0.001))

    def reset(self):
        self.__init__(self.env)

    def _predict_ds(self, state, action):
        sa = np.array([np.concatenate((state[0], [action]))])
        return self.model_net.predict(sa, 1)[0]

    def act(self, state):
        if np.random.rand() < self.exploration_rate:
            return random.randrange(self.n_actions), None

        # Sample a desired ds (delta state)
        target_dstate = np.random.normal(0.0, 1.0, self.ob_dim)
        # Make predictions for each possible action
        dstate = [self._predict_ds(state, a) for a in range(self.n_actions)]
        # Find best action by measuring how close ds are to target_ds (angle)
        def dist(ds1, ds2):
            dot = np.dot(ds1, ds2) / (np.linalg.norm(ds1) * np.linalg.norm(ds2))
            return 1 - dot    # from 0 (perfect match) to 2 (anti-parallel)
        ds_distance = [dist(target_dstate, ds) for ds in dstate]

        # Finally, return the action which results in a state change in a direction most similar to desired direction
        return np.argmin(ds_distance), None


    def think(self, state, action, state_next, _):
        self.states.append(state_next[0])

        # Train the model
        sa = np.array([np.concatenate((state[0], [action]))])
        self.model_net.fit(sa, state_next - state, verbose=0)

    # Approximate the covered area by convex hull
    def covered_volume(self):
        states = np.array(self.states)
        states = (states + self.env.observation_space.low)/(self.env.observation_space.high - self.env.observation_space.low)
        return ConvexHull(states).volume
```

The output I get when running `experiment.py`:
```
Using TensorFlow backend.
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
2019-02-14 17:06:11.273748: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Iter 0, timesteps=800: coverage = 0.5695444808537892
Iter 1, timesteps=800: coverage = 0.8073160099913885
Iter 2, timesteps=800: coverage = 5.202966470958516
Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f75287f8e10>>
Traceback (most recent call last):
  File "/home/ploppz/.pyenv/versions/3.6.6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1415, in __del__
  File "/home/ploppz/.pyenv/versions/3.6.6/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 526, in __exit__
tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.
Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f75117d2e80>>
Traceback (most recent call last):
  File "/home/ploppz/.pyenv/versions/3.6.6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1415, in __del__
  File "/home/ploppz/.pyenv/versions/3.6.6/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 526, in __exit__
tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.
```

This seems to always happen right after iteration 2.

**Comment by kangkang59812** [comment]
how to solve it ?
