### ISSUE TITLE
Tensor flow installation problem : Mac

### ISSUE THREAD

**Issue by prateektiwari7** [tensorflow/tensorflow#24365]
I have Mac 10.12 Sierra, My python version is 2.7. 

Installation steps are. 
```
$source ~/tensorflow/bin/activate
(tensorflow)$ pip install tensorflow
Requirement already satisfied: tensorflow in /usr/local/lib/python2.7/site-packages (1.12.0)
Requirement already satisfied: six>=1.10.0 in /usr/local/lib/python2.7/site-packages (from tensorflow) (1.11.0)
Requirement already satisfied: protobuf>=3.6.1 in /usr/local/Cellar/protobuf/3.6.1/libexec/lib/python2.7/site-packages (from tensorflow) (3.6.1)
Requirement already satisfied: enum34>=1.1.6 in /usr/local/lib/python2.7/site-packages (from tensorflow) (1.1.6)
Requirement already satisfied: gast>=0.2.0 in /usr/local/lib/python2.7/site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: keras-preprocessing>=1.0.5 in /usr/local/lib/python2.7/site-packages (from tensorflow) (1.0.5)
Requirement already satisfied: astor>=0.6.0 in /usr/local/lib/python2.7/site-packages (from tensorflow) (0.7.1)
Requirement already satisfied: grpcio>=1.8.6 in /usr/local/lib/python2.7/site-packages (from tensorflow) (1.17.0)
Requirement already satisfied: keras-applications>=1.0.6 in /usr/local/lib/python2.7/site-packages (from tensorflow) (1.0.6)
Requirement already satisfied: mock>=2.0.0 in /usr/local/lib/python2.7/site-packages (from tensorflow) (2.0.0)
Requirement already satisfied: numpy>=1.13.3 in /usr/local/lib/python2.7/site-packages (from tensorflow) (1.15.0)
Requirement already satisfied: tensorboard<1.13.0,>=1.12.0 in /usr/local/lib/python2.7/site-packages (from tensorflow) (1.12.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python2.7/site-packages (from tensorflow) (1.1.0)
Requirement already satisfied: wheel in ./python2.7/site-packages (from tensorflow) (0.32.3)
Requirement already satisfied: backports.weakref>=1.0rc1 in /usr/local/lib/python2.7/site-packages (from tensorflow) (1.0.post1)
Requirement already satisfied: absl-py>=0.1.6 in /usr/local/lib/python2.7/site-packages (from tensorflow) (0.6.1)
Requirement already satisfied: setuptools in ./python2.7/site-packages (from protobuf>=3.6.1->tensorflow) (40.6.3)
Requirement already satisfied: futures>=2.2.0 in /usr/local/lib/python2.7/site-packages (from grpcio>=1.8.6->tensorflow) (3.2.0)
Requirement already satisfied: h5py in /usr/local/lib/python2.7/site-packages (from keras-applications>=1.0.6->tensorflow) (2.8.0)
Requirement already satisfied: funcsigs>=1; python_version < "3.3" in /usr/local/lib/python2.7/site-packages (from mock>=2.0.0->tensorflow) (1.0.2)
Requirement already satisfied: pbr>=0.11 in /usr/local/lib/python2.7/site-packages (from mock>=2.0.0->tensorflow) (4.2.0)
Requirement already satisfied: werkzeug>=0.11.10 in /usr/local/lib/python2.7/site-packages (from tensorboard<1.13.0,>=1.12.0->tensorflow) (0.14.1)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python2.7/site-packages (from tensorboard<1.13.0,>=1.12.0->tensorflow) (3.0.1)

(tensorflow)$python
```

```
>>> import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 51, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 52, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: dlopen(/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 10): Library not loaded: @rpath/libcublas.8.0.dylib
  Referenced from: /usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
  Reason: image not found


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
>>> 
```

Please help me to install it over mac.

**Comment by prateektiwari7** [comment]
I solved this problem by going to root directory where it was installed. But now the new issue is coming as.
```
(cv)$ python
Python 3.7.1 (default, Nov 28 2018, 11:55:14) 
[Clang 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> x1 = tf.constant([1,2,3,4])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'tensorflow' has no attribute 'constant'
```


Please help me to solve this

**Comment by cathybgyz** [comment]
Run `python --version` should say 3.7.1, but you installed tensorflow in python2.7
Your pip must be associated with python2.7. on Mac OS the python modules for each version of python are kept in separate folders `site-packages`

On Mac OS you can press Command + G and enter `/Library/Python` to find your python versions and then locate the `site-packages`. Here I suspect you will discover tensorflow is not installed for python3.

So to install tensorflow for python 3, you will need to use the pip version associated with python 3.

`pip show tensorflow` will show which version of python the package is installed.

`pip3` is the python 3 package manager... Some people associate pip3 with the `pip` command. I don't like to do that because I often work without environment managers on smaller python scripts at times... so I maintain `pip3` and `pip` separate. 

`pip3 install tensorflow`

You may need to install `pip3` if you do not have it. There are multiple ways to do this.. Google around.

**Comment by harshini-gadige** [comment]
@prateektiwari7  Hi Prateek, what @cathybgyz  says is absolutely true. I can see that your system has Python 3.7 and you are using Python 2 version of pip. Please use pip3 and keep us posted. Thanks !

**Comment by prateektiwari7** [comment]
Hi @cathybgyz ,

Thanks for sharing this to me. It is working fine now. Thanks @harshini-gadige for your support. Can you guys help me how is there any sdk for Visual studio or any code editor for Tensorflow ?
