### ISSUE TITLE
AttributeError: 'int' object has no attribute 'node'  Bazel freeze graph error

### ISSUE THREAD

**Issue by ramreddyy** [tensorflow/tensorflow#24369]
**System information**
- Have I written custom code  : No
- OS Platform and Distribution : Linux Ubuntu 16.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.12
- Python version: Python3.5
- Bazel version (if compiling from source): Bazel-0.18.0

I have used tf.keras to build a model and set keras backend session as sess where sess=tf.Session()

Saved the graph_def file using below function 
tf.train.write_graph(sess.graph_def, '/tmp/model', 'model _graph.pbtxt')

When I am trying to generate frozen file using bazel I am getting below error

Traceback (most recent call last):
  File "/root/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/tools/freeze_graph.py", line 491, in <module>
    run_main()
  File "/root/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/tools/freeze_graph.py", line 488, in run_main
    app.run(main=my_main, argv=[sys.argv[0]] + unparsed)
  File "/root/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/root/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/tools/freeze_graph.py", line 487, in <lambda>
    my_main = lambda unused_args: main(unused_args, flags)
  File "/root/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/tools/freeze_graph.py", line 381, in main
    flags.saved_model_tags, checkpoint_version)
  File "/root/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/tools/freeze_graph.py", line 363, in freeze_graph
    checkpoint_version=checkpoint_version)
  File "/root/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/tools/freeze_graph.py", line 142, in freeze_graph_with_def_protos
    for node in input_graph_def.node:
AttributeError: 'int' object has no attribute 'node'

How to solve this Attribute Error ?

**Comment by cathybgyz** [comment]
So your title is a little misleading... Where are your getting the attribute error? I dont see it in the stack trace.. if Object is an `int`... `int` is a primitive type so obviously it does not have object `node` in it...

I have a hunch as to whats wrong... Can you provide the commands your are running around the area of freeze graph and bazel save? It sounds like you are not provided proper arguments to the functions you are calling.. Python can be a bit tricky wrt objects because everything is an "object".. So its not going to give you an error necessarily .. like "hey silly I want an array not an int".. or "hey silly I want a linked list of int with attribute node so I can traverse the list.

You probably are aware.. but errors are almost always terse.

**Comment by ramreddyy** [comment]
I have forgot to change the title . When I have used the freeze graph first I got Attribute error, after resolving that error now I am encountering this issue.

**Comment by zubairahmed-ai** [comment]
Exactly where I'm at right now and came here after Google (wow) 

`AttributeError: 'int' object has no attribute 'node'`

Anyone know the solution to this?

**Comment by zubairahmed-ai** [comment]
> So your title is a little misleading... Where are your getting the attribute error? I dont see it in the stack trace.. if Object is an `int`... `int` is a primitive type so obviously it does not have object `node` in it...
> 
> I have a hunch as to whats wrong... Can you provide the commands you're running around the area of freeze graph and save? It sounds like you are not providing proper arguments to the functions you are calling..
> 
> Python can be a bit tricky wrt objects because everything is an "object".. So its not going to give you an error necessarily .. like "hey silly I want an array not an int".. or "hey silly I want a linked list of int with attribute node so I can traverse the list."
> 
> You probably are aware.. but errors are almost always terse and oblivious of implementation requirements.

Until the OP replies here's my command which is resulting in the error above
`python E:\Documents\Projects\tensorflow\tensorflow\tensorflow\python\tools\freeze_graph.py --input_graph=/model/frozen_inference_graph.pb --input_checkpoint=model/model.ckpt-50000 --input_binary=true --output_graph=model/frozen_mobilenet_graph.pb --output_node_names=MobilenetV2/Logits/output:0`

**Comment by ramreddyy** [comment]
> > So your title is a little misleading... Where are your getting the attribute error? I dont see it in the stack trace.. if Object is an `int`... `int` is a primitive type so obviously it does not have object `node` in it...
> > I have a hunch as to whats wrong... Can you provide the commands you're running around the area of freeze graph and save? It sounds like you are not providing proper arguments to the functions you are calling..
> > Python can be a bit tricky wrt objects because everything is an "object".. So its not going to give you an error necessarily .. like "hey silly I want an array not an int".. or "hey silly I want a linked list of int with attribute node so I can traverse the list."
> > You probably are aware.. but errors are almost always terse and oblivious of implementation requirements.
> 
> Until the OP replies here's my command which is resulting in the error above
> `python E:\Documents\Projects\tensorflow\tensorflow\tensorflow\python\tools\freeze_graph.py --input_graph=/model/frozen_inference_graph.pb --input_checkpoint=model/model.ckpt-50000 --input_binary=true --output_graph=model/frozen_mobilenet_graph.pb --output_node_names=MobilenetV2/Logits/output:0`

Check whether you have specified correct path to protobuf file and checkpoint file in the command.

**Comment by ramreddyy** [comment]
> So your title is a little misleading... Where are your getting the attribute error? I dont see it in the stack trace.. if Object is an `int`... `int` is a primitive type so obviously it does not have object `node` in it...
> 
> I have a hunch as to whats wrong... Can you provide the commands you're running around the area of freeze graph and save? It sounds like you are not providing proper arguments to the functions you are calling..
> 
> Python can be a bit tricky wrt objects because everything is an "object".. So its not going to give you an error necessarily .. like "hey silly I want an array not an int".. or "hey silly I want a linked list of int with attribute node so I can traverse the list."
> 
> You probably are aware.. but errors are almost always terse and oblivious of implementation requirements.

I have forgot to change the title . When I have used the freeze graph first I got Attribute error, after resolving that error now I am encountering this issue.

**Comment by zubairahmed-ai** [comment]
@ramreddyy How did you find your output node, I found it very hard to find using Tensorboard so I used the script linked above in my answer?

**Comment by ramreddyy** [comment]
> @ramreddyy How did you find your output node, I found it very hard to find using Tensorboard so I used the script linked above in my answer?

@zubairahmed-ai  I have checked output node name using tensorboard and we can also use below code to get the node names as a list 
node_names=[n.name for n in tf.get_default_graph().as_graph_def().node]

Iterate over node_names and check the output name that you are providing to freeze_graph is present or not. 

If you have a protobuf file then you can use summarize_graph of bazel 
To use bazel tool go through below links
https://docs.bazel.build/versions/master/install.html
https://www.tensorflow.org/lite/tfmobile/prepare_models
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/graph_transforms/README.md

If you are using tf.keras to built the model and gave a name to output layer as 'output' it may not be same as output but something like output/Softmax so please do check out your output node name using tensorboard or graph_def or summarize_graph

**Comment by zubairahmed-ai** [comment]
Thanks
I will try out the script, my model is a custom trained SSD MobileNetv2 so TF.Keras won't work also I don't want to install Bazel just for doing this

**Comment by zubairahmed-ai** [comment]
@ramreddyy 

>node_names=[n.name for n in tf.get_default_graph().as_graph_def().node]

This gives me a node name that is this `MobilenetV2/Predictions/Reshape_1`

But when I try this I still get a `AssertionError: MobilenetV2/Predictions/Reshape_1 is not in graph`

Very confused right now

**Comment by trijiro** [comment]
@zubairahmed-ai
I had same problem.
I downloaded mobilenet_v2_1.4_224 from https://github.com/tensorflow/models/tree/master/research/slim/nets/mobilenet, and checked mobilenet_v2_1.4_224_info.txt.
`Model: mobilenet_v2_1.4_224`
`Input: input`
`Output: MobilenetV2/Predictions/Reshape_1`

However, `AssertionError: MobilenetV2/Predictions/Reshape_1 is not in graph` is occured.
Then, I inserted  below code to line 219 of freeze_graph.py .

`for v in sess.graph.get_operations():`
`  print(v.name)`

Result is
`…`
`InceptionV3/Predictions/Softmax`
`InceptionV3/Predictions/Shape`
`InceptionV3/Predictions/Reshape_1`
`…`

In my case, pb file had mismatched node name to pb.txt and info.txt.

**Comment by tritri-tktk** [comment]
> 
> 
> @zubairahmed-ai
> I had same problem.
> I downloaded mobilenet_v2_1.4_224 from https://github.com/tensorflow/models/tree/master/research/slim/nets/mobilenet, and checked mobilenet_v2_1.4_224_info.txt.
> 
> ```
> Model: mobilenet_v2_1.4_224
> Input: input
> Output: MobilenetV2/Predictions/Reshape_1
> ```
> 
> However, `AssertionError: MobilenetV2/Predictions/Reshape_1 is not in graph` is occured.
> Then, I inserted below code to line 219 of freeze_graph.py .
> 
> ```
> for v in sess.graph.get_operations():
>     print(v.name)
> ```
> 
> Result is
> 
> ```
> …
> InceptionV3/Predictions/Softmax
> InceptionV3/Predictions/Shape
> InceptionV3/Predictions/Reshape_1
> …
> ```
> 
> In my case, pb file had mismatched node name to .pbtxt file and info.txt file.

**Comment by Jayanth1812** [comment]
![image](https://user-images.githubusercontent.com/73299425/98220232-01b15b80-1f74-11eb-9006-24737f6d370e.png)

**Comment by mohantym** [comment]
Hi @ramreddyy!
It seems you are using older versions(1.x versions) of Tensorflow. We recommend that you upgrade  your code base to 2.x  versions as many features and bug fixes has been done in newer versions and let us know if the issue still persists in newer versions. Thanks!
