### ISSUE TITLE
Branch 1.13 build fails with undefined symbol: _ZNSaIPKN3xla14HloInstructionEEC1Ev

### ISSUE THREAD

**Issue by skeydan** [tensorflow/tensorflow#24373]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Fedora 28
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): source 
- TensorFlow version: 1.13
- Python version: 3.6.7
- Installed using virtualenv? pip? conda?: conda
- Bazel version (if compiling from source):  0.19.2
- GCC/Compiler version (if compiling from source): 7.3.0
- CUDA/cuDNN version: 9.2 / 7.1.4
- GPU model and memory: Quadro M2200

```
bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
```

fails:

```
  File "/home/key/.cache/bazel/_bazel_key/8de93c72df6c3fec3e289f10fadff72b/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/key/.cache/bazel/_bazel_key/8de93c72df6c3fec3e289f10fadff72b/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/key/.cache/bazel/_bazel_key/8de93c72df6c3fec3e289f10fadff72b/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/key/anaconda3/envs/tf-13-1213/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/home/key/anaconda3/envs/tf-13-1213/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /home/key/.cache/bazel/_bazel_key/8de93c72df6c3fec3e289f10fadff72b/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: _ZNSaIPKN3xla14HloInstructionEEC1Ev

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/key/.cache/bazel/_bazel_key/8de93c72df6c3fec3e289f10fadff72b/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/tools/api/generator/create_python_api.py", line 27, in <module>
    from tensorflow.python.tools.api.generator import doc_srcs
  File "/home/key/.cache/bazel/_bazel_key/8de93c72df6c3fec3e289f10fadff72b/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/key/.cache/bazel/_bazel_key/8de93c72df6c3fec3e289f10fadff72b/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/key/.cache/bazel/_bazel_key/8de93c72df6c3fec3e289f10fadff72b/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/key/.cache/bazel/_bazel_key/8de93c72df6c3fec3e289f10fadff72b/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/key/.cache/bazel/_bazel_key/8de93c72df6c3fec3e289f10fadff72b/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/key/anaconda3/envs/tf-13-1213/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/home/key/anaconda3/envs/tf-13-1213/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /home/key/.cache/bazel/_bazel_key/8de93c72df6c3fec3e289f10fadff72b/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: _ZNSaIPKN3xla14HloInstructionEEC1Ev


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 3986.489s, Critical Path: 241.90s, Remote (0.00% of the time): [queue: 0.00%, setup: 0.00%, process: 0.00%]
INFO: 5801 processes: 5801 local.
FAILED: Build did NOT complete successfully
```

**Comment by gunan** [comment]
@aselle FYI
1.13 branch is just cut last night. We will be going through such issues before we do the release.

**Comment by skeydan** [comment]
I get the same error trying to build current `master`:

```
ERROR: /home/key/code/tensorflow/tensorflow/BUILD:582:1: Executing genrule //tensorflow:tf_python_api_gen_v1 failed (Exit 1)
Traceback (most recent call last):
  File "/home/key/.cache/bazel/_bazel_key/8de93c72df6c3fec3e289f10fadff72b/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/key/.cache/bazel/_bazel_key/8de93c72df6c3fec3e289f10fadff72b/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/key/.cache/bazel/_bazel_key/8de93c72df6c3fec3e289f10fadff72b/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/key/anaconda3/envs/tf-13-1213/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/home/key/anaconda3/envs/tf-13-1213/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /home/key/.cache/bazel/_bazel_key/8de93c72df6c3fec3e289f10fadff72b/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: _ZNSaIPKN3xla14HloInstructionEEC1Ev

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/key/.cache/bazel/_bazel_key/8de93c72df6c3fec3e289f10fadff72b/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/tools/api/generator/create_python_api.py", line 27, in <module>
    from tensorflow.python.tools.api.generator import doc_srcs
  File "/home/key/.cache/bazel/_bazel_key/8de93c72df6c3fec3e289f10fadff72b/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/key/.cache/bazel/_bazel_key/8de93c72df6c3fec3e289f10fadff72b/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/key/.cache/bazel/_bazel_key/8de93c72df6c3fec3e289f10fadff72b/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/key/.cache/bazel/_bazel_key/8de93c72df6c3fec3e289f10fadff72b/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/key/.cache/bazel/_bazel_key/8de93c72df6c3fec3e289f10fadff72b/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/key/anaconda3/envs/tf-13-1213/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/home/key/anaconda3/envs/tf-13-1213/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /home/key/.cache/bazel/_bazel_key/8de93c72df6c3fec3e289f10fadff72b/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: _ZNSaIPKN3xla14HloInstructionEEC1Ev

```

**Comment by rootkitchao** [comment]
I suggest you try a lower CUDA version (9.0) and a lower bazel version (0.15.0).I am not sure if this will solve the problem. But following the documentation suggested configuration may avoid some surprises

**Comment by freedomtan** [comment]
```
> c++filt _ZNSaIPKN3xla14HloInstructionEEC1Ev
std::allocator<xla::HloInstruction const*>::allocator()
```
it seems a XLA related problem.

**Comment by skeydan** [comment]
@freedomtan thanks! I've tried compiling again because I saw new updates to that file on master, but it still fails. Next I'll try without XLA support.

@rootkitchao thanks, but these versions work when compiling other branches (1.10, 1.11, 1.12).

**Comment by skeydan** [comment]
Turns out it does indeed work when compiling without XLA!
But I guess I'll leave this open because it would be nice to be able to use XLA right?

Thx again @freedomtan!

**Comment by freedomtan** [comment]
@skeydan I built 1.13 (b40aeb9c66a4b96536cca493906c2af461e72ad0) with XLA enabled successfully on Ubuntu 16.04+virtualenv+Python 3.5.2+Cuda 9.2+cudnn 7.1.4 just now.

**Comment by alanpurple** [comment]
same error with or without XLA

python 3.7.1, CUDA10, ubuntu 16.04.4

**Comment by supercoolgreatcoder** [comment]
having same issue, master branch
python3.6.7 gcc7.3.0 cuda9.2 cudnn 7.2.1 ubuntu 18.04

**Comment by alain54** [comment]
master branch, same error with XLA; ok without XLA.
bazel master call:
env TMP=/tmp bazel build --config=opt --copt=-mavx --copt=-mavx2 --copt=-mfma --copt=-mfpmath=both --copt=-msse4.2 --cxxopt=-D_GLIBCXX_USE_CXX11_ABI=0 //tensorflow:libtensorflow.so //tensorflow/tools/pip_package:build_pip_package

Package versions: tensorflow1.13 bazel0.20 python2.7.15 gcc7.3.0 cuda10.0 cudnn7.4.2 fedora29

**Comment by skeydan** [comment]
Hi @alain54 - sorry for misusing this, but I plan to upgrade to F29 soon, and I see you have it working with cuda 10.
Might I ask you what version of the nvidia driver you're using, and which is your kernel version? (I also take it, from what you write, that we still need to custom-compile gcc7 for cuda 10...?)

Thanks!

**Comment by alain54** [comment]
Hi,
So, maybe this erreur comes from gcc 7.3.0-0, i.e the compiled source from https://gcc.gnu.org ?
With tensorflow Master, today, the 7.3.0-29 package from ubuntu 18.10 is OK; the compiled version 7.4.0 from gcc.gnu.org on my fedora 29 is also OK.
Package versions: tensorflowMaster bazel0.21 python2.7.15 gcc7.4.0 cuda10.0 cudnn7.4.2 fedora29 up to date.

**Comment by skeydan** [comment]
Thx @alain54! I was/am using gcc 7.3.0 (self-compiled). However, I'll be upgrading to F29 (including a newer kernel) this week. Would you mind indicating which is your kernel version, and the version of the nvidia driver? (The most "destructive" step in the whole procedure, for me, always being getting kernel and driver to match).

**Comment by skeydan** [comment]
I've upgraded to Fedora 29, kernel 4.20.3, cuda 1.10, and cannot reproduce that error now (still using gcc 7.3.0). I'll close the issue.
