### ISSUE TITLE
ImportError: DLL load failed: Не найден указанный модуль.

### ISSUE THREAD

**Issue by Ar4ikov** [tensorflow/tensorflow#24400]
**System information**
- OS: `Windows 10 Pro x64`
- TensorFlow installed from `pip`
- TensorFlow version: `1.12.1`
- Python version: `3.6.5`
- CUDA version: `10.0`, cuDNN version: `7`
- GPU: `940MX with GDDR5 memory`

Let's start do describe this.
I used to create some variables in tensorflow/python/platforms/build_info.py
```python
some_path = "C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/bin/"

msvcp_dll_name = 'C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/jre/bin/msvcp140.dll'
cudart_dll_name = some_path + 'cudart64_100.dll'
cuda_version_number = '10.0'
# nvcuda_dll_name = 'nvcuda.dll'
cudnn_dll_name = some_path + 'cudnn64_7.dll'
cudnn_version_number = '7'
```

But I'd got an error. Logs:
```
C:\Users\Ar4ikov\PycharmProjects\QTApp\similar_text>python similar_text.py
Traceback (most recent call last):
  File "C:\Users\Ar4ikov\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Ar4ikov\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Ar4ikov\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Ar4ikov\AppData\Local\Programs\Python\Python36\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Ar4ikov\AppData\Local\Programs\Python\Python36\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: Не найден указанный модуль.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "similar_text.py", line 8, in <module>
    import tflearn as tf
  File "C:\Users\Ar4ikov\AppData\Local\Programs\Python\Python36\lib\site-packages\tflearn\__init__.py", line 4, in <module>
    from . import config
  File "C:\Users\Ar4ikov\AppData\Local\Programs\Python\Python36\lib\site-packages\tflearn\config.py", line 3, in <module>
    import tensorflow as tf
  File "C:\Users\Ar4ikov\AppData\Roaming\Python\Python36\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\Ar4ikov\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Ar4ikov\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Ar4ikov\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Ar4ikov\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Ar4ikov\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Ar4ikov\AppData\Local\Programs\Python\Python36\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Ar4ikov\AppData\Local\Programs\Python\Python36\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: Не найден указанный модуль.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

What's wrong?

**Comment by ymodak** [comment]
I see that you are using CUDA 10. Unfortunately,Our have prebuilt binaries support CUDA 9 as of now. Therefore you have to build TF yourself from sources in order to use cuda 10.

**Comment by Ar4ikov** [comment]
I will turn back to CUDA 9, Thanks

**Comment by Ar4ikov** [comment]
Still not working.

**Comment by ymodak** [comment]
Did you update the environment variables as well? You have to [set env variables](https://www.tensorflow.org/install/gpu#windows_setup) to cuda 9.0.
Also you need to install the Microsoft Visual C++ 2015 Redistributable Update 3.

**Comment by harshini-gadige** [comment]
@Ar4ikov  What version of cuDNN are you using with CUDA 9 ? Generally  cuDNN >= 7.2 for CUDA 9.0  should be used.

**Comment by ymodak** [comment]
@Ar4ikov Is this still an issue for you?

**Comment by Ar4ikov** [comment]
yes it is

**Comment by ymodak** [comment]
Apologies for the delay in response. 

> @Ar4ikov What version of cuDNN are you using with CUDA 9 ? Generally cuDNN >= 7.2 for CUDA 9.0 should be used.

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
