### ISSUE TITLE
TOCO failed.Covert saved_model.pb to tflite

### ISSUE THREAD

**Issue by jennings1716** [tensorflow/tensorflow#24446]
### Describe the problem
I trained a [classification ](https://codelabs.developers.google.com/codelabs/mlimmersion-image-flowerstxf/index.html?index=..%2F..%2Fcloud#0)  model using ML engine.I got the model folder with saved model.pb and variables folder. Now I want to convert the saved_model.pb to tflite.I used the following code.
```
import tensorflow as tf

converter = tf.lite.TFLiteConverter.from_saved_model('/home/ubuntu/*****/model')
tflite_model = converter.convert()
open("converted_model.tflite", "wb").write(tflite_model)`
```

It gives the following error 
"TOCO failed. See console for info.\n%s\n%s\n" % (stdout, stderr))
tensorflow.lite.python.convert.ConverterError: TOCO failed."

### Source code / logs
2018-12-19 10:10:33.807941: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-12-19 10:10:33.812470: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2400070000 Hz
2018-12-19 10:10:33.812612: I tensorflow/compiler/xla/service/service.cc:161] XLA service 0x3a4e660 executing computations on platform Host. Devices:
2018-12-19 10:10:33.812633: I tensorflow/compiler/xla/service/service.cc:168]   StreamExecutor device (0): <undefined>, <undefined>
WARNING:tensorflow:From /home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/lite/python/convert_saved_model.py:61: load (from tensorflow.python.saved_model.loader_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.loader.load or tf.compat.v1.saved_model.load. There will be a new function for importing SavedModels in Tensorflow 2.0.
WARNING:tensorflow:The saved meta_graph is possibly from an older release:
'model_variables' collection should be of type 'byte_list', but instead is of type 'node_list'.
WARNING:tensorflow:From /home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
WARNING:tensorflow:The saved meta_graph is possibly from an older release:
'model_variables' collection should be of type 'byte_list', but instead is of type 'node_list'.
WARNING:tensorflow:From /home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/lite/python/convert_saved_model.py:275: convert_variables_to_constants (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.compat.v1.graph_util.convert_variables_to_constants
WARNING:tensorflow:From /home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/framework/graph_util_impl.py:245: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.compat.v1.graph_util.extract_sub_graph
Traceback (most recent call last):
  File "export_from_saved.py", line 4, in <module>
    tflite_model = converter.convert()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/lite/python/lite.py", line 455, in convert
    **converter_kwargs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/lite/python/convert.py", line 442, in toco_convert_impl
    input_data.SerializeToString())
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/lite/python/convert.py", line 205, in toco_convert_protos
    "TOCO failed. See console for info.\n%s\n%s\n" % (stdout, stderr))
tensorflow.lite.python.convert.ConverterError: TOCO failed. See console for info.
2018-12-19 10:10:40.009636: I tensorflow/lite/toco/import_tensorflow.cc:1324] Converting unsupported operation: TensorArrayV3
2018-12-19 10:10:40.020516: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2018-12-19 10:10:40.020613: I tensorflow/lite/toco/import_tensorflow.cc:1324] Converting unsupported operation: TensorArrayScatterV3
2018-12-19 10:10:40.020649: I tensorflow/lite/toco/import_tensorflow.cc:1324] Converting unsupported operation: TensorArrayV3
2018-12-19 10:10:40.020667: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2018-12-19 10:10:40.020678: I tensorflow/lite/toco/import_tensorflow.cc:1324] Converting unsupported operation: Enter
2018-12-19 10:10:40.020689: I tensorflow/lite/toco/import_tensorflow.cc:1324] Converting unsupported operation: Enter
2018-12-19 10:10:40.020710: I tensorflow/lite/toco/import_tensorflow.cc:1324] Converting unsupported operation: Enter
2018-12-19 10:10:40.020728: I tensorflow/lite/toco/import_tensorflow.cc:1324] Converting unsupported operation: LoopCond
2018-12-19 10:10:40.020748: I tensorflow/lite/toco/import_tensorflow.cc:1324] Converting unsupported operation: Enter
2018-12-19 10:10:40.020763: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2018-12-19 10:10:40.020772: I tensorflow/lite/toco/import_tensorflow.cc:1324] Converting unsupported operation: Enter
2018-12-19 10:10:40.020784: I tensorflow/lite/toco/import_tensorflow.cc:1324] Converting unsupported operation: TensorArrayReadV3
2018-12-19 10:10:40.020801: I tensorflow/lite/toco/import_tensorflow.cc:1324] Converting unsupported operation: DecodeJpeg
2018-12-19 10:10:40.020834: I tensorflow/lite/toco/import_tensorflow.cc:1324] Converting unsupported operation: Enter
2018-12-19 10:10:40.020851: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2018-12-19 10:10:40.020865: I tensorflow/lite/toco/import_tensorflow.cc:1324] Converting unsupported operation: TensorArrayWriteV3
2018-12-19 10:10:40.020885: I tensorflow/lite/toco/import_tensorflow.cc:1324] Converting unsupported operation: Exit
2018-12-19 10:10:40.020902: I tensorflow/lite/toco/import_tensorflow.cc:1324] Converting unsupported operation: TensorArraySizeV3
2018-12-19 10:10:40.020926: I tensorflow/lite/toco/import_tensorflow.cc:1324] Converting unsupported operation: TensorArrayGatherV3
2018-12-19 10:10:40.112748: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 1302 operators, 1816 arrays (0 quantized)
2018-12-19 10:10:40.176386: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 1302 operators, 1816 arrays (0 quantized)
2018-12-19 10:10:40.332638: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 1: 159 operators, 371 arrays (0 quantized)
2018-12-19 10:10:40.337273: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 2: 156 operators, 365 arrays (0 quantized)
2018-12-19 10:10:40.342033: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before dequantization graph transformations: 156 operators, 365 arrays (0 quantized)
2018-12-19 10:10:40.351531: I tensorflow/lite/toco/allocate_transient_arrays.cc:345] Total transient array allocated size: 0 bytes, theoretical optimal value: 0 bytes.
2018-12-19 10:10:40.352994: E tensorflow/lite/toco/toco_tooling.cc:421] We are continually in the process of adding support to TensorFlow Lite for more ops. It would be helpful if you could inform us of how this conversion went by opening a github issue at https://github.com/tensorflow/tensorflow/issues/new?template=40-tflite-op-request.md
 and pasting the following:

Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, AVERAGE_POOL_2D, CAST, CONCATENATION, CONV_2D, EXPAND_DIMS, FULLY_CONNECTED, LESS, LOGISTIC, MAX_POOL_2D, RANGE, RESHAPE, RESIZE_BILINEAR, SQUEEZE. Here is a list of operators for which you will need custom implementations: DecodeJpeg, Enter, Exit, LoopCond, Merge, Switch, TensorArrayGatherV3, TensorArrayReadV3, TensorArrayScatterV3, TensorArraySizeV3, TensorArrayV3, TensorArrayWriteV3.
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/toco_from_protos", line 11, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 59, in main
    app.run(main=execute, argv=[sys.argv[0]] + unparsed)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 33, in execute
    output_str = tensorflow_wrap_toco.TocoConvert(model_str, toco_str, input_str)
Exception: We are continually in the process of adding support to TensorFlow Lite for more ops. It would be helpful if you could inform us of how this conversion went by opening a github issue at https://github.com/tensorflow/tensorflow/issues/new?template=40-tflite-op-request.md
 and pasting the following:

Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, AVERAGE_POOL_2D, CAST, CONCATENATION, CONV_2D, EXPAND_DIMS, FULLY_CONNECTED, LESS, LOGISTIC, MAX_POOL_2D, RANGE, RESHAPE, RESIZE_BILINEAR, SQUEEZE. Here is a list of operators for which you will need custom implementations: DecodeJpeg, Enter, Exit, LoopCond, Merge, Switch, TensorArrayGatherV3, TensorArrayReadV3, TensorArrayScatterV3, TensorArraySizeV3, TensorArrayV3, TensorArrayWriteV3.

**Comment by jennings1716** [comment]
Any updates

**Comment by LeManhTruong** [comment]
Hi, i have problem with toco
"RuntimeError: TOCO failed see console for info.
2019-01-09 08:05:08.698392: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: TensorArrayV3
2019-01-09 08:05:08.698452: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1127] Op node missing output type attribute: question_encoding/rnn/TensorArray
2019-01-09 08:05:08.698462: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: TensorArrayV3
2019-01-09 08:05:08.698469: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1127] Op node missing output type attribute: question_encoding/rnn/TensorArray_1
2019-01-09 08:05:08.698620: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Enter
2019-01-09 08:05:08.698628: I tensorflow/contrib/lite/toco/import_tensorflow.cc:189] Unsupported data type in placeholder op: 20
(stdout, stderr))
RuntimeError: TOCO failed see console for info.
2019-01-09 08:05:08.698392: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: TensorArrayV3
2019-01-09 08:05:08.698452: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1127] Op node missing output type attribute: question_encoding/rnn/TensorArray
2019-01-09 08:05:08.698462: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: TensorArrayV3
2019-01-09 08:05:08.698469: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1127] Op node missing output type attribute: question_encoding/rnn/TensorArray_1
2019-01-09 08:05:08.698499: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: TensorArrayScatterV3
2019-01-09 08:05:08.698508: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1127] Op node missing output type attribute: question_encoding/rnn/TensorArrayUnstack/TensorArrayScatter/TensorArrayScatterV3
2019-01-09 08:05:08.698523: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Enter
2019-01-09 08:05:08.698534: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Enter
2019-01-09 08:05:08.698542: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Enter
2019-01-09 08:05:08.698550: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Enter
2019-01-09 08:05:08.698565: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Enter
2019-01-09 08:05:08.698576: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Enter
2019-01-09 08:05:08.698586: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: LoopCond
2019-01-09 08:05:08.698592: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1127] Op node missing output type attribute: question_encoding/rnn/while/LoopCond
2019-01-09 08:05:08.698620: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Enter
2019-01-09 08:05:08.698628: I tensorflow/contrib/lite/toco/import_tensorflow.cc:189] Unsupported data type in placeholder op: 20
2019-01-09 08:05:08.698634: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Enter
2019-01-09 08:05:08.698642: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: TensorArrayReadV3
2019-01-09 08:05:08.700531: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Enter
2019-01-09 08:05:08.700558: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Enter
2019-01-09 08:05:08.700583: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Enter
2019-01-09 08:05:08.700596: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Enter
2019-01-09 08:05:08.700618: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Enter
2019-01-09 08:05:08.700627: I tensorflow/contrib/lite/toco/import_tensorflow.cc:189] Unsupported data type in placeholder op: 20
2019-01-09 08:05:08.700634: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: TensorArrayWriteV3
2019-01-09 08:05:08.700641: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1127] Op node missing output type attribute: question_encoding/rnn/while/TensorArrayWrite/TensorArrayWriteV3
2019-01-09 08:05:08.700656: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Exit
2019-01-09 08:05:08.700665: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: TensorArraySizeV3
2019-01-09 08:05:08.700671: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1127] Op node missing output type attribute: question_encoding/rnn/TensorArrayStack/TensorArraySizeV3
2019-01-09 08:05:08.700687: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: TensorArrayGatherV3
2019-01-09 08:05:08.702429: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: TensorArrayV3
2019-01-09 08:05:08.702442: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1127] Op node missing output type attribute: input_fusion/bidirectional_rnn/fw/fw/TensorArray
2019-01-09 08:05:08.702450: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: TensorArrayV3
2019-01-09 08:05:08.702456: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1127] Op node missing output type attribute: input_fusion/bidirectional_rnn/fw/fw/TensorArray_1
2019-01-09 08:05:08.702482: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: TensorArrayScatterV3
2019-01-09 08:05:08.702490: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1127] Op node missing output type attribute: input_fusion/bidirectional_rnn/fw/fw/TensorArrayUnstack/TensorArrayScatter/TensorArrayScatterV3
2019-01-09 08:05:08.702502: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Enter
2019-01-09 08:05:08.702511: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Enter
2019-01-09 08:05:08.702518: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Enter
2019-01-09 08:05:08.702526: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Enter
2019-01-09 08:05:08.702539: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Enter
2019-01-09 08:05:08.702549: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Enter
2019-01-09 08:05:08.702558: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: LoopCond
2019-01-09 08:05:08.702563: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1127] Op node missing output type attribute: input_fusion/bidirectional_rnn/fw/fw/while/LoopCond
2019-01-09 08:05:08.702588: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Enter
2019-01-09 08:05:08.702595: I tensorflow/contrib/lite/toco/import_tensorflow.cc:189] Unsupported data type in placeholder op: 20
2019-01-09 08:05:08.702600: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Enter
2019-01-09 08:05:08.702608: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: TensorArrayReadV3
2019-01-09 08:05:08.704475: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Enter
2019-01-09 08:05:08.704495: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Enter
2019-01-09 08:05:08.704518: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Enter
2019-01-09 08:05:08.704529: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Enter
2019-01-09 08:05:08.704548: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Enter
2019-01-09 08:05:08.704556: I tensorflow/contrib/lite/toco/import_tensorflow.cc:189] Unsupported data type in placeholder op: 20
2019-01-09 08:05:08.704562: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: TensorArrayWriteV3
2019-01-09 08:05:08.704569: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1127] Op node missing output type attribute: input_fusion/bidirectional_rnn/fw/fw/while/TensorArrayWrite/TensorArrayWriteV3
2019-01-09 08:05:08.704583: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Exit
2019-01-09 08:05:08.704591: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: TensorArraySizeV3
2019-01-09 08:05:08.704597: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1127] Op node missing output type attribute: input_fusion/bidirectional_rnn/fw/fw/TensorArrayStack/TensorArraySizeV3
2019-01-09 08:05:08.704612: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: TensorArrayGatherV3
2019-01-09 08:05:08.704641: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: ReverseV2
2019-01-09 08:05:08.704698: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: TensorArrayV3
2019-01-09 08:05:08.704707: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1127] Op node missing output type attribute: input_fusion/bidirectional_rnn/bw/bw/TensorArray
2019-01-09 08:05:08.704715: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: TensorArrayV3
2019-01-09 08:05:08.704721: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1127] Op node missing output type attribute: input_fusion/bidirectional_rnn/bw/bw/TensorArray_1
2019-01-09 08:05:08.704748: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: TensorArrayScatterV3
2019-01-09 08:05:08.704756: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1127] Op node missing output type attribute: input_fusion/bidirectional_rnn/bw/bw/TensorArrayUnstack/TensorArrayScatter/TensorArrayScatterV3
2019-01-09 08:05:08.704768: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Enter
2019-01-09 08:05:08.704777: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Enter
2019-01-09 08:05:08.704784: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Enter
2019-01-09 08:05:08.704793: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Enter
2019-01-09 08:05:08.704806: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Enter
2019-01-09 08:05:08.704815: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Enter
2019-01-09 08:05:08.704825: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: LoopCond
2019-01-09 08:05:08.704829: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1127] Op node missing output type attribute: input_fusion/bidirectional_rnn/bw/bw/while/LoopCond
2019-01-09 08:05:08.704853: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Enter
2019-01-09 08:05:08.704859: I tensorflow/contrib/lite/toco/import_tensorflow.cc:189] Unsupported data type in placeholder op: 20
2019-01-09 08:05:08.704865: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Enter
2019-01-09 08:05:08.704872: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: TensorArrayReadV3
2019-01-09 08:05:08.706701: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Enter
2019-01-09 08:05:08.706720: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Enter
2019-01-09 08:05:08.706742: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Enter
2019-01-09 08:05:08.706752: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Enter
2019-01-09 08:05:08.706771: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Enter
2019-01-09 08:05:08.706778: I tensorflow/contrib/lite/toco/import_tensorflow.cc:189] Unsupported data type in placeholder op: 20
2019-01-09 08:05:08.706784: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: TensorArrayWriteV3
2019-01-09 08:05:08.706791: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1127] Op node missing output type attribute: input_fusion/bidirectional_rnn/bw/bw/while/TensorArrayWrite/TensorArrayWriteV3
2019-01-09 08:05:08.706804: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Exit
2019-01-09 08:05:08.706812: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: TensorArraySizeV3
2019-01-09 08:05:08.706817: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1127] Op node missing output type attribute: input_fusion/bidirectional_rnn/bw/bw/TensorArrayStack/TensorArraySizeV3
2019-01-09 08:05:08.706832: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: TensorArrayGatherV3
2019-01-09 08:05:08.706860: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: ReverseV2
2019-01-09 08:05:08.706936: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Abs
2019-01-09 08:05:08.706945: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Abs
2019-01-09 08:05:08.716294: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Abs
2019-01-09 08:05:08.716339: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Abs
2019-01-09 08:05:08.725842: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Abs
2019-01-09 08:05:08.725899: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Abs
2019-01-09 08:05:09.935688: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 10153 operators, 14372 arrays (0 quantized)
2019-01-09 08:05:11.575490: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 10153 operators, 14372 arrays (0 quantized)
2019-01-09 08:05:19.104584: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 1: 7633 operators, 12950 arrays (0 quantized)
2019-01-09 08:05:21.192942: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 2: 7630 operators, 12947 arrays (0 quantized)
2019-01-09 08:05:23.251206: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 3: 7627 operators, 12941 arrays (0 quantized)
2019-01-09 08:05:25.322947: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before dequantization graph transformations: 7627 operators, 12941 arrays (0 quantized)
2019-01-09 08:05:27.454312: F tensorflow/contrib/lite/toco/tooling_util.cc:618] Check faile😛 dim >= 1 (0 vs. 1)
Aborted (core dumped)"

Help me.

**Comment by jennings1716** [comment]
@LeManhTruong What model are you using ? Please give more details

**Comment by LeManhTruong** [comment]
> @LeManhTruong What model are you using ? Please give more details

I use model for VQA, link source <https://github.com/DeepRNN/visual_question_answering>. When I converting model into "tflite", I have problem with TOCO, error "unsupported operation".

**Comment by jennings1716** [comment]
> > @LeManhTruong What model are you using ? Please give more details
> 
> I use model for VQA, link source https://github.com/DeepRNN/visual_question_answering. When I converting model into "tflite", I have problem with TOCO, error "unsupported operation".

did you try with  Python 1.12 ?

**Comment by LeManhTruong** [comment]
> > > @LeManhTruong What model are you using ? Please give more details
> > 
> > 
> > I use model for VQA, link source https://github.com/DeepRNN/visual_question_answering. When I converting model into "tflite", I have problem with TOCO, error "unsupported operation".
> 
> did you try with Tensorflow 1.12 ?

yes, I try with Tensorflow 1.12

**Comment by gargn** [comment]
@LeManhTruong Please file a separate GitHub issue with all of the relevant information.

@jennings1716 It seems your model has ops that are not available as TFLite built-in ops. Can you try using our [experimental feature](https://www.tensorflow.org/lite/guide/ops_select) to try converting with a broader set of ops. There is some additional information about handling unsupported ops in our [FAQ](https://www.tensorflow.org/lite/guide/faq#why_are_some_operations_not_implemented_in_tensorflow_lite).

**Comment by jyotirmayghosh** [comment]
I just raised an issue:
https://github.com/tensorflow/tensorflow/issues/27278

I tried to convert the sample graphdef to .tflite. It converted successfully. I don't the there is any error in tensorflow version. 
but when I tried to convert another graphdef to .tflite, it is giving the same error as above.
please check the link above for details.

can anyone help me. 

thanks

**Comment by jennings1716** [comment]
Tensorflow till now didnt provide tflite function for all operations and hence you get this error. We have to write custom functions for unsupported operation
