### ISSUE TITLE
TypeError: Input 'split_dim' of 'Split' Op has type float32 that does not match expected type of int32.

### ISSUE THREAD

**Issue by j2233ack** [tensorflow/tensorflow#24444]
Hello,
I am using TF1.4,
Ubuntu16.04
I am implementing https://github.com/zhenkaiwang/im2txt_attention
I encountered during the training phase:
Traceback (most recent call last):
  File "/home/hsu/im2txt_attention-master/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/train.py", line 114, in <module>
    Tf.app.run()
  File "/home/hsu/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/hsu/im2txt_attention-master/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/train.py", line 65, in main
    Model.build()
  File "/home/hsu/im2txt_attention-master/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/show_and_tell_model.py", line 550, in build
    Self.build_model()
  File "/home/hsu/im2txt_attention-master/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/show_and_tell_model.py", line 392, in build_model
    _, initial_state = lstm_cell(self.image_embeddings, zero_state)
  File "/home/hsu/im2txt_attention-master/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/ops/rnn_cell_ops.py", line 805, in __call__
    Output, new_state, _,_,_ = self._cell(inputs, state, scope)
  File "/home/hsu/im2txt_attention-master/bazel-bin/im2txt/train.runfiles/im2txt/im2txt/ops/rnn_cell_ops.py", line 435, in __call__
    i, j, f, o = array_ops.split(1, 4, concat)
  File "/home/hsu/.local/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 1265, in split
    Split_dim=axis, num_split=num_or_size_splits, value=value, name=name)
  File "/home/hsu/.local/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 5094, in _split
    Name=name)
  File "/home/hsu/.local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 533, in _apply_op_helper
    (prefix, dtypes.as_dtype(input_arg.type).name))
TypeError: Input 'split_dim' of 'Split' Op has type float32 that does not match expected type of int32.
Then I found some solutions as follows
Original code
State_tuple = tf.split(split_dim=1, num_split=2, value=state_feed)
After modification
State_tuple = tf.split(value=state_feed, num_or_size_splits=2, axis=1

Error code still appears：
TypeError: Input 'split_dim' of 'Split' Op has type float32 that does not match expected type of int32.

Can someone help me?

**Comment by ymodak** [comment]
This question is better asked on [zhenkaiwang/im2txt_attention repo](https://github.com/zhenkaiwang/im2txt_attention/issues) since it is not a bug or feature request. If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as a repro example for your case. Thanks!
