### ISSUE TITLE
this graph contains an operator of type SquaredDifference for which the quantized form is not yet implemented

### ISSUE THREAD

**Issue by MrCary** [tensorflow/tensorflow#24497]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Ubuntu14.04
- TensorFlow installed from (source or binary):pip tf-nightly
- TensorFlow version (or github SHA if from source): tf-nightly1.13.0.dev20181216

**Provide the text output from tflite_convert**

```
I convert pb to lite use the following code:
`import tensorflow as tf
converter = tf.contrib.lite.TFLiteConverter.from_frozen_graph('tflite_graph.pb',["input_image"],["result"], input_shapes={"input_image":[1,626,360,3]})
converter.allow_custom_ops = True
converter.inference_type = tf.contrib.lite.constants.QUANTIZED_UINT8
converter.quantized_input_stats = {"input_image" : (0., 2.)}
converter.default_ranges_stats=(0, 6)
tflite_quantized_model=converter.convert()
open("model.tflite", "wb").write(tflite_quantized_model)`

I get the following error:
2018-12-21 11:26:06.351171: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-12-21 11:26:06.354986: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3392410000 Hz
2018-12-21 11:26:06.355300: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x53e0ee0 executing computations on platform Host. Devices:
2018-12-21 11:26:06.355325: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
Traceback (most recent call last):
  File "test.py", line 25, in <module>
    tflite_quantized_model=converter.convert()
  File "/home/zhoushaohuang/Virtualenv/python3.4/lib/python3.4/site-packages/tensorflow/lite/python/lite.py", line 455, in convert
    **converter_kwargs)
  File "/home/zhoushaohuang/Virtualenv/python3.4/lib/python3.4/site-packages/tensorflow/lite/python/convert.py", line 442, in toco_convert_impl
    input_data.SerializeToString())
  File "/home/zhoushaohuang/Virtualenv/python3.4/lib/python3.4/site-packages/tensorflow/lite/python/convert.py", line 205, in toco_convert_protos
    "TOCO failed. See console for info.\n%s\n%s\n" % (stdout, stderr))
tensorflow.lite.python.convert.ConverterError: TOCO failed. See console for info.
2018-12-21 11:26:07.312638: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 168 operators, 271 arrays (0 quantized)
2018-12-21 11:26:07.314127: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 168 operators, 271 arrays (0 quantized)
2018-12-21 11:26:07.323240: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 1: 102 operators, 183 arrays (1 quantized)
2018-12-21 11:26:07.324611: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 2: 96 operators, 171 arrays (1 quantized)
2018-12-21 11:26:07.325812: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before pre-quantization graph transformations: 96 operators, 171 arrays (1 quantized)
2018-12-21 11:26:07.326413: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After pre-quantization graph transformations pass 1: 90 operators, 165 arrays (1 quantized)
2018-12-21 11:26:07.327324: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before default min-max range propagation graph transformations: 90 operators, 165 arrays (1 quantized)
2018-12-21 11:26:07.327972: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After default min-max range propagation graph transformations pass 1: 90 operators, 165 arrays (1 quantized)
2018-12-21 11:26:07.328720: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before quantization graph transformations: 90 operators, 165 arrays (1 quantized)
2018-12-21 11:26:07.328791: W tensorflow/lite/toco/graph_transformations/quantize.cc:127] Constant array conv1/conv/weight lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2018-12-21 11:26:07.328936: F tensorflow/lite/toco/graph_transformations/quantize.cc:491] Unimplemented: this graph contains an operator of type SquaredDifference for which the quantized form is not yet implemented. Sorry, and patches welcome (that's a relatively fun patch to write, mostly providing the actual quantized arithmetic code for this op).
Aborted (core dumped)

```

Also, please include a link to a GraphDef or the model if possible.
I use SquaredDifference in following code:
`def instance_norm(x):
    epsilon = 1e-9

    mean = tf.reduce_mean(x,[1,2])
    mean = tf.expand_dims(mean,[1])
    mean = tf.expand_dims(mean,[1])
    s = x.get_shape()
    var = tf.reduce_sum(tf.squared_difference(x, mean), [1,2], keep_dims=True)/(s[1].value*s[2].value)
    result = tf.div(tf.subtract(x, mean), tf.sqrt(tf.add(var, epsilon)))
    return result`
![2018-12-21 15 18 10](https://user-images.githubusercontent.com/28701781/50329687-49bb6680-0533-11e9-9672-68c7d451a888.png)

**Any other info / logs**
I generate pb use the following code:
`input_saver_def = saver.as_saver_def()
 frozen_graph_def = freeze_graph.freeze_graph_with_def_protos(input_graph_def=tf.get_default_graph().as_graph_def(),input_saver_def=input_saver_def,input_checkpoint = FLAGS.model_file,output_node_names='result',restore_op_name='save/restore_all', filename_tensor_name='save/Const:0',clear_devices=True,output_graph='',initializer_nodes='')
binary_graph = 'tflite_graph.pb'
with tf.gfile.GFile(binary_graph, 'wb') as f:
       f.write(frozen_graph_def.SerializeToString())`

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by samuallin** [comment]
Hi, we met SquaredDifference is not supporting operator as well and check from Tensorflow 1.9 to 1.12, all have this problem.
Could you let us know if this is a bug? If yes, could you let us know do you have planning to fix this?
Thanks.

**Comment by ANSHUMAN87** [comment]
@MrCary, @samuallin  : Will it be possible for you to share sample code to reproduce the issue?
I believe your sample code is incomplete.
Otherwise you can share the model itself.
Thanks!

**Comment by MeghnaNatraj** [comment]
Marking issue as resolved due to inactivity. Feel free to re-open this if it's unresolved or file a [new issue](https://github.com/tensorflow/tensorflow/issues/new/choose)
