### ISSUE TITLE
failed to use toco to convert quantized pb file to tflite file

### ISSUE THREAD

**Issue by sxsxsx** [tensorflow/tensorflow#24506]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): NO
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:  NO
- TensorFlow installed from (source or binary):  pip install tensorflow-gpu==1.9
- TensorFlow version (use command below):  1.9 gpu
- Python version:
- Bazel version (if compiling from source):   NO
- GCC/Compiler version (if compiling from source):  gcc  5.4.0 
- CUDA/cuDNN version: cuda 9.0 cudnn 7.1
- GPU model and memory: gtx 1070

**Describe the current behavior**
       I used tf.contrib.quantize.create_eval_graph() to quantized trainning a cnn network,  , and used 
freeze_graph.py to generate frozen pb file  successfully
      but when I used toco to convert the pb to tflite  ,,error occured    shown below 

      Array Slice, which is an input to the Conv operator producing the output array conv1/Relu, is lacking min/max data, which is necessary for quantization. Either target a non-quantized output format, or change the input graph to contain min/max information, or pass --default_ranges_min= and --default_ranges_max= if you do not care about the accuracy of results

It seems that the toco can not support tf.slice op ???

**Code to reproduce the issue**

my network is  shown below  

def model(x, y, is_training, is_quantize):
    with slim.arg_scope([slim.conv2d, slim.fully_connected],
                        activation_fn=tf.nn.relu,
                        biases_initializer = tf.constant_initializer(0.0),						
                        normalizer_fn=slim.batch_norm,
                        normalizer_params={'is_training': is_training, 'epsilon':1e-5, 'scale': True, 'updates_collections': tf.GraphKeys.UPDATE_OPS}):
        print('x',x.get_shape())		
        data_slice  = tf.slice(x, [ 0, 0, 0, 0], [ train_batch, 64, 60, 3])
        conv1 = slim.conv2d(data_slice,  16,    [3, 3], scope='conv1')

**Other info / logs**
$ toco  --output_file=quant.tflite --graph_def_file=quant.pb --input_arrays=input  --output_arrays=fc2/act_quant/FakeQuantWithMinMaxVars  --output_format=TFLITE --inference_type=QUANTIZED_UINT8 --mean_values=0 --std_dev_values=1
2018-12-21 20:50:10.927248: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-12-21 20:50:11.011200: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:897] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-12-21 20:50:11.011620: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1392] Found device 0 with properties: 
name: GeForce GTX 1080 major: 6 minor: 1 memoryClockRate(GHz): 1.8225
pciBusID: 0000:01:00.0
totalMemory: 7.92GiB freeMemory: 7.77GiB
2018-12-21 20:50:11.011633: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1471] Adding visible gpu devices: 0
2018-12-21 20:50:11.194928: I tensorflow/core/common_runtime/gpu/gpu_device.cc:952] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-12-21 20:50:11.194963: I tensorflow/core/common_runtime/gpu/gpu_device.cc:958]      0 
2018-12-21 20:50:11.194970: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   N 
2018-12-21 20:50:11.195190: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7498 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080, pci bus id: 0000:01:00.0, compute capability: 6.1)
Traceback (most recent call last):
  File "/home/icare/.local/bin/toco", line 11, in <module>
    sys.exit(main())
  File "/home/icare/.local/lib/python2.7/site-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 320, in main
    app.run(main=run_main, argv=sys.argv[:1])
  File "/home/icare/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/home/icare/.local/lib/python2.7/site-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 316, in run_main
    _convert_model(tflite_flags)
  File "/home/icare/.local/lib/python2.7/site-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 121, in _convert_model
    output_data = converter.convert()
  File "/home/icare/.local/lib/python2.7/site-packages/tensorflow/contrib/lite/python/lite.py", line 309, in convert
    allow_custom_ops=self.allow_custom_ops)
  File "/home/icare/.local/lib/python2.7/site-packages/tensorflow/contrib/lite/python/convert.py", line 225, in toco_convert
    input_data.SerializeToString())
  File "/home/icare/.local/lib/python2.7/site-packages/tensorflow/contrib/lite/python/convert.py", line 107, in toco_convert_protos
    (stdout, stderr))
RuntimeError: TOCO failed see console for info.
2018-12-21 20:50:12.108082: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 113 operators, 173 arrays (0 quantized)
2018-12-21 20:50:12.108759: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 113 operators, 173 arrays (0 quantized)
2018-12-21 20:50:12.112645: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 1: 20 operators, 37 arrays (1 quantized)
2018-12-21 20:50:12.112836: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 2: 19 operators, 35 arrays (1 quantized)
2018-12-21 20:50:12.112978: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 3: 18 operators, 33 arrays (1 quantized)
2018-12-21 20:50:12.113106: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before pre-quantization graph transformations: 18 operators, 33 arrays (1 quantized)
2018-12-21 20:50:12.113179: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] After pre-quantization graph transformations pass 1: 12 operators, 27 arrays (1 quantized)
2018-12-21 20:50:12.113252: F tensorflow/contrib/lite/toco/tooling_util.cc:1589] Array Slice, which is an input to the Conv operator producing the output array conv1/Relu, is lacking min/max data, which is necessary for quantization. Either target a non-quantized output format, or change the input graph to contain min/max information, or pass --default_ranges_min= and --default_ranges_max= if you do not care about the accuracy of results.
Aborted (core dumped)

None

what should I do to solve the problem ???

**Comment by ymodak** [comment]
I see that you are using lower version of TF, likely a reason for TOCO converter failure. Can you please test it with TF-nightly version?

**Comment by ymodak** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
