### ISSUE TITLE
while install tensorflow 1.12 with cudnn 9  GETTING ERROR AS DLL:SPECIFIED PROCEDURE COUDN'T FIND

### ISSUE THREAD

**Issue by skanth859** [tensorflow/tensorflow#24500]
TENSORFLOW ISSUE GETTNG SPECIFIED PROCEDURE COUDN'T FIND 
WHIL COMUTER IS HAVING
 WINDOWS 7 OS , 
GRAPHIC IS NVIDIA GEFORCE 7025 
INSTALLED TENSORFLOW 1.12 WITH CUDNN 9
IN ANACONDA 1.9.6 LATEST 2018 NOV VERSION

GET ME HELP ..... 
(SRI) C:\Users\SRIKANTH>python -c "import tensorflow"
Traceback (most recent call last):
  File "C:\Users\SRIKANTH\Anaconda3\envs\SRI\lib\site-packages\tensorflow\python
\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\SRIKANTH\Anaconda3\envs\SRI\lib\site-packages\tensorflow\python
\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\SRIKANTH\Anaconda3\envs\SRI\lib\site-packages\tensorflow\python
\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, descript
ion)
  File "C:\Users\SRIKANTH\Anaconda3\envs\SRI\lib\imp.py", line 243, in load_modu
le
    return load_dynamic(name, filename, file)
  File "C:\Users\SRIKANTH\Anaconda3\envs\SRI\lib\imp.py", line 343, in load_dyna
mic
    return _load(spec)
ImportError: DLL load failed: The specified procedure could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\SRIKANTH\Anaconda3\envs\SRI\lib\site-packages\tensorflow\__init
__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-im
port
  File "C:\Users\SRIKANTH\Anaconda3\envs\SRI\lib\site-packages\tensorflow\python
\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\SRIKANTH\Anaconda3\envs\SRI\lib\site-packages\tensorflow\python
\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\SRIKANTH\Anaconda3\envs\SRI\lib\site-packages\tensorflow\python
\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\SRIKANTH\Anaconda3\envs\SRI\lib\site-packages\tensorflow\python
\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\SRIKANTH\Anaconda3\envs\SRI\lib\site-packages\tensorflow\python
\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, descript
ion)
  File "C:\Users\SRIKANTH\Anaconda3\envs\SRI\lib\imp.py", line 243, in load_modu
le
    return load_dynamic(name, filename, file)
  File "C:\Users\SRIKANTH\Anaconda3\envs\SRI\lib\imp.py", line 343, in load_dyna
mic
    return _load(spec)
ImportError: DLL load failed: The specified procedure could not be found.

Failed to load the native TensorFlow runtime.

**Comment by rootkitchao** [comment]
Have you installed cuDNN7 correctly?

**Comment by skanth859** [comment]
installed cudnn7. with cuda 9.0 
when i reinstall only tensorflow version i can import it 
but with tenosrflow -gpu version its getting error AS DLL : THE SPECIFIED PROCEDURE COUDN'T FOUND
my system is windows 7  , gpu version is nvidia geforce 7025  model

**Comment by rootkitchao** [comment]
> thanks @rootkitchao for replying
> yes installed cudnn7 with cuda 9 through anaconda
> installed cudnn7. with cuda 9.0
> when i reinstall only tensorflow version i can import it
> but with tenosrflow -gpu version its getting error AS DLL : THE SPECIFIED PROCEDURE COUDN'T FOUND
> my system is windows 7 , gpu version is nvidia geforce 7025 model

I would like to ask "gpu version is nvidia geforce 7025 model" means your GPU model is Nvidia Geforce 7025?NVIDIA Geforce 7025 is an integrated graphics processor introduced by NVIDIA in 2007. It is very old.This graphics processor was released even earlier than the original CUDA version.
Current version of Tensorflow-GPU requirements NVIDIA GPU card with CUDACompute Capability 3.5 or higher(see https://www.tensorflow.org/install/gpu).Obviously your hardware can't meet the requirements and there is no solution.

**Comment by ymodak** [comment]
Closing this issue since @rootkitchao is correct.
