### ISSUE TITLE
BUG: code throws exceptions when using COND_V2

### ISSUE THREAD

**Issue by ppwwyyxx** [tensorflow/tensorflow#24517]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):archlinux
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:n/a
- TensorFlow installed from (source or binary):binary
- TensorFlow version (use command below):v1.12.0-rc2-0-g748435b8ef 1.12.0-rc2
- Python version:3.6
- Bazel version (if compiling from source):n/a
- GCC/Compiler version (if compiling from source):n/a
- CUDA/cuDNN version:n/a
- GPU model and memory:n/a

**Code to reproduce the issue**
```python
import os
os.environ['TF_ENABLE_COND_V2'] = '1'
import tensorflow as tf
a = tf.placeholder(tf.float32, shape=[3])
u = tf.distributions.Normal(a, scale=1., validate_args=True)
```

**Other info / logs**
It fails with the following message. However the code works well without cond_v2.
```
Traceback (most recent call last):                                                                                                                                                                 
  File "/home/wyx/.local/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 933, in convert                                                                                    
    x = ops.convert_to_tensor_or_indexed_slices(x)                                                                                                                                                 
  File "/home/wyx/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1269, in convert_to_tensor_or_indexed_slices                                                        
    value=value, dtype=dtype, name=name, as_ref=False)                                                                                                                                             
  File "/home/wyx/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1307, in internal_convert_to_tensor_or_indexed_slices                                               
    value, dtype=dtype, name=name, as_ref=as_ref)                                                                                                                                                  
  File "/home/wyx/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1146, in internal_convert_to_tensor                                                                 
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)                                                                                                                            
  File "/home/wyx/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 6168, in _operation_conversion_error                                                                
    name, as_ref))                                                                                                                                                                                 
TypeError: Can't convert Operation 'NoOp' to Tensor (target dtype=None, name=None, as_ref=False)
                                                                                                                                                                                                   
During handling of the above exception, another exception occurred:
                                                                                                                                                                                                   
Traceback (most recent call last):
  File "a.py", line 8, in <module>                                                                                                                                                                 
    u = tf.distributions.Normal(a, scale=1., validate_args=True)
  File "/home/wyx/.local/lib/python3.6/site-packages/tensorflow/python/ops/distributions/normal.py", line 140, in __init__                                                                         
    validate_args else []):
  File "/home/wyx/.local/lib/python3.6/site-packages/tensorflow/python/ops/check_ops.py", line 204, in assert_positive                                                                             
    return assert_less(zero, x, data=data, summarize=summarize)
  File "/home/wyx/.local/lib/python3.6/site-packages/tensorflow/python/ops/check_ops.py", line 569, in assert_less                                                                                 
    return control_flow_ops.Assert(condition, data, summarize=summarize)
  File "/home/wyx/.local/lib/python3.6/site-packages/tensorflow/python/util/tf_should_use.py", line 189, in wrapped                                                                                
    return _add_should_use_warning(fn(*args, **kwargs))
  File "/home/wyx/.local/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 167, in Assert                                                                               
    guarded_assert = cond(condition, no_op, true_assert, name="AssertGuard")
  File "/home/wyx/.local/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func                                                                                 
    return func(*args, **kwargs)
  File "/home/wyx/.local/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2040, in cond                                                                                
    return cond_v2_impl.cond_v2(pred, true_fn, false_fn, name)
  File "/home/wyx/.local/lib/python3.6/site-packages/tensorflow/python/ops/cond_v2_impl.py", line 70, in cond_v2                                                                                   
    true_name, true_fn, [], {})
  File "/home/wyx/.local/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 947, in func_graph_from_py_func                                                                    
    func_outputs = nest.map_structure(convert, func_outputs)
  File "/home/wyx/.local/lib/python3.6/site-packages/tensorflow/python/util/nest.py", line 381, in map_structure                                                                                   
    structure[0], [func(*x) for x in entries])
  File "/home/wyx/.local/lib/python3.6/site-packages/tensorflow/python/util/nest.py", line 381, in <listcomp>                                                                                      
    structure[0], [func(*x) for x in entries])
  File "/home/wyx/.local/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 939, in convert
    (str(python_func), type(x)))
TypeError: To be compatible with tf.contrib.eager.defun, Python functions must return zero or more Tensors; in compilation of <function no_op at 0x7f64b06a7ea0>, found return value of type <class
'tensorflow.python.framework.ops.Operation'>, which is not a Tensor.
```

cc @skye, who seems to work on cond_v2 in https://github.com/tensorflow/tensorflow/issues/15874#issuecomment-436833266.

**Comment by ymodak** [comment]
I was able to run your code snippet successfully using TF 1.12. Can you try using https://colab.sandbox.google.com/notebooks/welcome.ipynb to execute your code and confirm?

**Comment by ppwwyyxx** [comment]
![1226-11 07 10](https://user-images.githubusercontent.com/1381301/50454757-6cb49480-08fe-11e9-96f2-6c34d0542594.png)
You may be executing my code in the wrong way (e.g. import tensorflow before setting envvar).

**Comment by ymodak** [comment]
Yes you are right.

**Comment by skye** [comment]
Hi, thanks for reporting this! Just to let you know, I'm working on some other control flow bugs at the moment so I haven't had a chance to take a look at this yet, but this is on my radar.

**Comment by saxenasaurabh** [comment]
I am unable to repro this at head so it's possible this has been fixed since. Please retry and reopen if this is still an issue.
