### ISSUE TITLE
Unexpected behaviour of tf.map_fn()

### ISSUE THREAD

**Issue by ParikhKadam** [tensorflow/tensorflow#24519]
- OS Platform and Distribution: Windows 10 
- TensorFlow installed from: source
- TensorFlow version: 1.10.0
- Python version: 3.6.6

I am using K.map_fn() in my custom loss function where I am passing both y_true and y_pred of shape (None, None) as elems argument of this function. But when the function specified in map_fn is called, elements obtained in that function are of different shapes. And that's the problem.

Here's the example:

My custom loss function:
```
def negative_avg_log_error(y_true, y_pred):

    def sum_of_log_probabilities(true_and_pred):
        y_true, y_pred = true_and_pred
        print(K.int_shape(y_true))
        print(K.int_shape(y_pred))
        start_index = int(y_true[0])
        end_index = int(y_true[1])
        start_probability = y_pred[start_index]
        end_probability = y_pred[end_index]
        return K.log(start_probability) + K.log(end_probability)

    print(K.int_shape(y_true))
    print(K.int_shape(y_pred))
    batch_probability_sum = K.map_fn(lambda x: sum_of_log_probabilities(x), elems=[y_true, y_pred], dtype='float32')
    return -K.mean(batch_probability_sum, axis=1)
```

Code from which this loss function is called:

`model.compile(loss=negative_avg_log_error, optimizer='adadelta', metrics='loss')`

Error log:

```
(None, None)
(None, None)
(None,)
(None, 1)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-15-807b6d06a435> in <module>()
----> 1 model.compile(loss=negative_avg_log_error, optimizer='adadelta', metrics='loss')

C:\Python36\lib\site-packages\keras\engine\training.py in compile(self, optimizer, loss, metrics, loss_weights, sample_weight_mode, weighted_metrics, target_tensors, **kwargs)
    331                 with K.name_scope(self.output_names[i] + '_loss'):
    332                     output_loss = weighted_loss(y_true, y_pred,
--> 333                                                 sample_weight, mask)
    334                 if len(self.outputs) > 1:
    335                     self.metrics_tensors.append(output_loss)

C:\Python36\lib\site-packages\keras\engine\training_utils.py in weighted(y_true, y_pred, weights, mask)
    401         """
    402         # score_array has ndim >= 2
--> 403         score_array = fn(y_true, y_pred)
    404         if mask is not None:
    405             # Cast the mask to floatX to avoid float64 upcasting in Theano

E:\Deep Learning Material\IMP for Project\model\scripts\loss_function.py in negative_avg_log_error(y_true, y_pred)
     16     print(K.int_shape(y_true))
     17     print(K.int_shape(y_pred))
---> 18     batch_probability_sum = K.map_fn(lambda x: sum_of_log_probabilities(x), elems=[y_true, y_pred], dtype='float32')
     19     return -K.mean(batch_probability_sum, axis=1)

C:\Python36\lib\site-packages\keras\backend\tensorflow_backend.py in map_fn(fn, elems, name, dtype)
   4229         Tensor with dtype `dtype`.
   4230     """
-> 4231     return tf.map_fn(fn, elems, name=name, dtype=dtype)
   4232 
   4233 

C:\Python36\lib\site-packages\tensorflow\python\ops\functional_ops.py in map_fn(fn, elems, dtype, parallel_iterations, back_prop, swap_memory, infer_shape, name)
    457         back_prop=back_prop,
    458         swap_memory=swap_memory,
--> 459         maximum_iterations=n)
    460     results_flat = [r.stack() for r in r_a]
    461 

C:\Python36\lib\site-packages\tensorflow\python\ops\control_flow_ops.py in while_loop(cond, body, loop_vars, shape_invariants, parallel_iterations, back_prop, swap_memory, name, maximum_iterations, return_same_structure)
   3230       ops.add_to_collection(ops.GraphKeys.WHILE_CONTEXT, loop_context)
   3231     result = loop_context.BuildLoop(cond, body, loop_vars, shape_invariants,
-> 3232                                     return_same_structure)
   3233     if maximum_iterations is not None:
   3234       return result[1]

C:\Python36\lib\site-packages\tensorflow\python\ops\control_flow_ops.py in BuildLoop(self, pred, body, loop_vars, shape_invariants, return_same_structure)
   2950       with ops.get_default_graph()._mutation_lock():  # pylint: disable=protected-access
   2951         original_body_result, exit_vars = self._BuildLoop(
-> 2952             pred, body, original_loop_vars, loop_vars, shape_invariants)
   2953     finally:
   2954       self.Exit()

C:\Python36\lib\site-packages\tensorflow\python\ops\control_flow_ops.py in _BuildLoop(self, pred, body, original_loop_vars, loop_vars, shape_invariants)
   2885         flat_sequence=vars_for_body_with_tensor_arrays)
   2886     pre_summaries = ops.get_collection(ops.GraphKeys._SUMMARY_COLLECTION)  # pylint: disable=protected-access
-> 2887     body_result = body(*packed_vars_for_body)
   2888     post_summaries = ops.get_collection(ops.GraphKeys._SUMMARY_COLLECTION)  # pylint: disable=protected-access
   2889     if not nest.is_sequence(body_result):

C:\Python36\lib\site-packages\tensorflow\python\ops\control_flow_ops.py in <lambda>(i, lv)
   3199         cond = lambda i, lv: (  # pylint: disable=g-long-lambda
   3200             math_ops.logical_and(i < maximum_iterations, orig_cond(*lv)))
-> 3201         body = lambda i, lv: (i + 1, orig_body(*lv))
   3202 
   3203     if context.executing_eagerly():

C:\Python36\lib\site-packages\tensorflow\python\ops\functional_ops.py in compute(i, tas)
    446       """
    447       packed_values = input_pack([elem_ta.read(i) for elem_ta in elems_ta])
--> 448       packed_fn_values = fn(packed_values)
    449       nest.assert_same_structure(dtype or elems, packed_fn_values)
    450       flat_fn_values = output_flatten(packed_fn_values)

E:\Deep Learning Material\IMP for Project\model\scripts\loss_function.py in <lambda>(x)
     16     print(K.int_shape(y_true))
     17     print(K.int_shape(y_pred))
---> 18     batch_probability_sum = K.map_fn(lambda x: sum_of_log_probabilities(x), elems=[y_true, y_pred], dtype='float32')
     19     return -K.mean(batch_probability_sum, axis=1)

E:\Deep Learning Material\IMP for Project\model\scripts\loss_function.py in sum_of_log_probabilities(true_and_pred)
      8         print(K.int_shape(y_true))
      9         print(K.int_shape(y_pred))
---> 10         start_index = int(y_true[0])
     11         end_index = int(y_true[1])
     12         start_probability = y_pred[start_index]

TypeError: int() argument must be a string, a bytes-like object or a number, not 'Tensor'
```

I am currently focusing on:
In negative_avg_log_error() => K.int_shape(y_true)=(None, None) and K.int_shape(y_pred)=(None, None)
In sum_of_log_probabilities() => K.int_shape(y_true)=(None,) and K.int_shape(y_pred)=(None, 1)

But I think that the shape of both these tensors in sum_of_log_probabilities() should be (None, ).

Need help as understanding this will help me solve this error.

**Comment by yongtang** [comment]
@ParikhKadam I am not able to reproduce with tf-nightly, can you try with tf-nightly or share your full minimal reproducible code that exposed the issue?

**Comment by ParikhKadam** [comment]
@yongtang Thank you for the response.. This is already the minimal code which should be able to reproduce this unexpected behaviour. If you want, I can upload my project on Github and share it with you.

Also, can you share your piece of code so that I can check if there are any implementation differences. I am in a hurry as I have to submit my project on Monday and everything relies on this loss function which is getting me wrong output.

I have also shared the same issue on stack, subreddits and keras-github with no response. Thank you..

**Comment by yongtang** [comment]
@ParikhKadam You are using 1.10.0 which is quite old. Can you try with tf-nightly or 1.12.0?

**Comment by ParikhKadam** [comment]
@yongtang Sure.. I will try that and update here.

By the way, will I also need to change the GPU version? Its because, I have already set up my computer with CUDA 9. And by installing another GPU version, I might also need to change CUDA version which is very time consuming.

**Comment by ParikhKadam** [comment]
@yongtang Updated tensorflow and still the problem persists.

By the way, updated tensorflow-gpu too and it needed the same version of CUDA. Saved me some time of reinstalling things.. But the problem still persists..

Need help..

**Comment by yongtang** [comment]
@ParikhKadam It would be helpful if you could provide the full example code that could reproduce the error.

**Comment by ParikhKadam** [comment]
@yongtang Sure... here is the file containing model architecture and the error:

https://github.com/ParikhKadam/bidaf-keras/blob/master/graph.ipynb

**Comment by ParikhKadam** [comment]
@yongtang Any updates? I have tried running an example code snippet and it worked as expected. That means, there is no problem with the tensorflow version or my environment. It's something different. Here it is..

```
import numpy as np 
from keras import backend as K 

A = np.random.random((32,6))
# B = np.moveaxis( A, 3, 1)
# C = np.transpose( A, (0,3,1,2))
B = np.random.random((32, 6))

print(A.shape)
print(B.shape)

def mul(x):
    A, B = x
    print(K.int_shape(A))
    print(K.int_shape(B))
    return A*B

A_t = K.variable(A)
B_t = K.variable(B)
# C_t = K.permute_dimensions(A_t, (0,3,1,2))

C = K.map_fn(mul, (A_t, B_t), dtype='float32')

y = K.eval(C)
```

Output:

```
(32, 6)
(32, 6)
(6,)
(6,)
```

And w.r.t to this snippet, looking at my real code, the iterated elements should have the shape (None, ). But I don't know why one of it is having shape (None, 1).

**Comment by ParikhKadam** [comment]
Tried shuffling the inputs to know if the way I am passing the inputs is affecting this! And no, it's not.. The problem only occurs with `y_pred` and `y_true` works fine.

And I don't know why as both are of same shapes..

**Comment by ParikhKadam** [comment]
@yongtang Something sparked in my mind which I had forgotten. My model is have two output tensors of shape (batch_size, num_of_words). So what would be the value/shape/structure of y_pred in this case?

**Comment by ParikhKadam** [comment]
Updated my code accordingly:
```

from keras import backend as K


def negative_avg_log_error(y_true, y_pred):

    def sum_of_log_probabilities(true_and_pred):
        y_true, y_pred_start, y_pred_end = true_and_pred

        print(K.int_shape(y_true))
        print(K.int_shape(y_pred_start))
        print(K.int_shape(y_pred_end))
        # ignore the below part, just a check for shapes
        start_index = int(y_true[0])
        end_index = int(y_true[1])
        start_probability = y_pred[start_index]
        end_probability = y_pred[end_index]
        return K.log(start_probability) + K.log(end_probability)

    print(K.int_shape(y_true))
    print(K.int_shape(y_pred[0]))
    print(K.int_shape(y_pred[1]))
    batch_probability_sum = K.map_fn(sum_of_log_probabilities, (y_true, y_pred[0], y_pred[1]), dtype='float32')
    return -K.mean(batch_probability_sum, axis=1)
```

And the outputs of the model are of shape (None, None). Here's its code snippet and output.
```

span_begin_probabilities = SpanBegin(name='span_begin')([merged_context, modeled_passage])
span_end_probabilities = SpanEnd(name='span_end')([encoded_passage, merged_context, modeled_passage, span_begin_probabilities])

model = Model([question_input, passage_input], [span_begin_probabilities, span_end_probabilities])
```

Last part of the output of model.summary():

```
__________________________________________________________________________________________________
span_begin (SpanBegin)          (None, None)         0           merged_context[0][0]             
                                                                 bidirectional_decoder_0[0][0]    
__________________________________________________________________________________________________
span_end (SpanEnd)              (None, None)         0           bidirectional_encoder[1][0]      
                                                                 merged_context[0][0]             
                                                                 bidirectional_decoder_0[0][0]    
                                                                 span_begin[0][0]                 
==================================================================================================
```

Output of model.compile():

```
(None, None)
(None, 1)
(None, 1)
(None,)
(1,)
(1,)
```

The problem now is, the shape of y_pred[0] and y_pred[1] should be (None, None) instead of (None, 1).

I think we are close to finding a solution. Please help...

By the way, just a thing I noticed -- int_shape() doesn't throw an error when called on a list instead of a tensor object. Why?

**Comment by ParikhKadam** [comment]
Hey.. the issue still persists. The link is referenced doesn't provide a solution either. I just requested there to provide a solution. That doesn't mean I got a solution.

**Comment by yongtang** [comment]
@ParikhKadam When I run the code (https://github.com/ParikhKadam/bidaf-keras/blob/master/graph.ipynb) I had the following error:
```
Traceback (most recent call last):
  File "graph.py", line 13, in <module>
    glove = Magnitude('data/magnitude/glove.6B.300d.magnitude')
  File "/usr/local/lib/python3.6/dist-packages/pymagnitude/__init__.py", line 352, in __init__
    self.path, log=self.log, _local=True)
  File "/usr/local/lib/python3.6/dist-packages/pymagnitude/__init__.py", line 2173, in download_model
    remote_file_path)
RuntimeError: The path to the Magnitude file at 'data/magnitude/glove.6B.300d.magnitude' could not be found. Also failed to find a valid remote model at the following URL: http://magnitude.plasticity.ai/data/magnitude/glove.6B.300d.magnitude
```

**Comment by ParikhKadam** [comment]
That can't be possible.. Maybe you haven't cloned the whole project. This file has its own dependencies which are already included in the project.

The module 'layers' is also a part of the project which is here:
https://github.com/ParikhKadam/bidaf-keras/tree/master/layers

**Comment by ParikhKadam** [comment]
@yongtang Bro.. As I said above, the issue was because of my model returning more than one outputs. And I tried to access them using a single loss function. As I google for a while, I came to know that I can combine both outputs using tf.stack() and use the returned tensor of this function as final output of my model. But I am still facing issues with shapes in the loss function.

I had two output tensors x and y of shape (None, None) which is combined using z=tf.stack([x,y], axis=0). Now, I have a single output tensor z of shape (2, None, None). I pass this tensor z to loss function and am trying to get the original output tensors x and y of shape (None, None) using slicing.

Here's the code snippet, the output and the error:

model.summary():

```
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
==================================================================================================
passage_input (InputLayer)      (None, None, 600)    0                                            
__________________________________________________________________________________________________
question_input (InputLayer)     (None, None, 600)    0                                            
__________________________________________________________________________________________________
highway_1_ptd (TimeDistributed) (None, None, 600)    0           passage_input[0][0]              
__________________________________________________________________________________________________
highway_1_qtd (TimeDistributed) (None, None, 600)    0           question_input[0][0]             
__________________________________________________________________________________________________
bidirectional_encoder (Bidirect (None, None, 1200)   5764800     highway_1_qtd[0][0]              
                                                                 highway_1_ptd[0][0]              
__________________________________________________________________________________________________
similarity_layer (Similarity)   (None, None, None)   3601        bidirectional_encoder[1][0]      
                                                                 bidirectional_encoder[0][0]      
__________________________________________________________________________________________________
context_to_query_attention (C2Q (None, None, 1200)   0           similarity_layer[0][0]           
                                                                 bidirectional_encoder[1][0]      
__________________________________________________________________________________________________
query_to_context_attention (Q2C (None, None, 1200)   0           similarity_layer[0][0]           
                                                                 bidirectional_encoder[0][0]      
__________________________________________________________________________________________________
merged_context (MergedContext)  (None, None, 4800)   0           bidirectional_encoder[1][0]      
                                                                 context_to_query_attention[0][0] 
                                                                 query_to_context_attention[0][0] 
__________________________________________________________________________________________________
bidirectional_decoder_0 (Bidire (None, None, 1200)   25924800    merged_context[0][0]             
__________________________________________________________________________________________________
span_begin (SpanBegin)          (None, None)         0           merged_context[0][0]             
                                                                 bidirectional_decoder_0[0][0]    
__________________________________________________________________________________________________
span_end (SpanEnd)              (None, None)         0           bidirectional_encoder[1][0]      
                                                                 merged_context[0][0]             
                                                                 bidirectional_decoder_0[0][0]    
                                                                 span_begin[0][0]                 
__________________________________________________________________________________________________
combine_outputs (CombineOutputs (2, None, None)      0           span_begin[0][0]                 
                                                                 span_end[0][0]                   
==================================================================================================
Total params: 31,693,201
Trainable params: 31,693,201
Non-trainable params: 0
__________________________________________________________________________________________________
```

loss function:

```
from keras import backend as K


def negative_avg_log_error(y_true, y_pred):

    def sum_of_log_probabilities(true_and_pred):
        y_true, y_pred_start, y_pred_end = true_and_pred

        print(K.int_shape(y_true))
        print(K.int_shape(y_pred_start))
        print(K.int_shape(y_pred_end))
        start_index = int(y_true[0])
        end_index = int(y_true[1])
        start_probability = y_pred_start[start_index]
        end_probability = y_pred_end[end_index]
        return K.log(start_probability) + K.log(end_probability)

    y_true = K.squeeze(y_true, axis=0)
    y_pred_start = y_pred[0]
    y_pred_end = y_pred[1]
    print(type(y_pred))
    print(K.int_shape(y_true))
    print(K.int_shape(y_pred))
    print(K.int_shape(y_pred_start))
    print(K.int_shape(y_pred_end))
    batch_probability_sum = K.map_fn(sum_of_log_probabilities, (y_true, y_pred_start, y_pred_end), dtype='float32')
    return -K.mean(batch_probability_sum, axis=0)
```

model.compile(loss=negative_avg_log_error, optimizer='adadelta', metrics='loss'):

```
<class 'tensorflow.python.framework.ops.Tensor'>
(None, None)
(2, None, None)
(None, None, 1)
(None, None, 1)
(None,)
(None, 1)
(None, 1)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-21-807b6d06a435> in <module>()
----> 1 model.compile(loss=negative_avg_log_error, optimizer='adadelta', metrics='loss')

C:\Python36\lib\site-packages\keras\engine\training.py in compile(self, optimizer, loss, metrics, loss_weights, sample_weight_mode, weighted_metrics, target_tensors, **kwargs)
    340                 with K.name_scope(self.output_names[i] + '_loss'):
    341                     output_loss = weighted_loss(y_true, y_pred,
--> 342                                                 sample_weight, mask)
    343                 if len(self.outputs) > 1:
    344                     self.metrics_tensors.append(output_loss)

C:\Python36\lib\site-packages\keras\engine\training_utils.py in weighted(y_true, y_pred, weights, mask)
    402         """
    403         # score_array has ndim >= 2
--> 404         score_array = fn(y_true, y_pred)
    405         if mask is not None:
    406             # Cast the mask to floatX to avoid float64 upcasting in Theano

E:\Deep Learning Material\IMP for Project\model\scripts\loss_function.py in negative_avg_log_error(y_true, y_pred)
     24     print(K.int_shape(y_pred_start))
     25     print(K.int_shape(y_pred_end))
---> 26     batch_probability_sum = K.map_fn(sum_of_log_probabilities, (y_true, y_pred_start, y_pred_end), dtype='float32')
     27     return -K.mean(batch_probability_sum, axis=0)

C:\Python36\lib\site-packages\keras\backend\tensorflow_backend.py in map_fn(fn, elems, name, dtype)
   4319         Tensor with dtype `dtype`.
   4320     """
-> 4321     return tf.map_fn(fn, elems, name=name, dtype=dtype)
   4322 
   4323 

C:\Python36\lib\site-packages\tensorflow\python\ops\functional_ops.py in map_fn(fn, elems, dtype, parallel_iterations, back_prop, swap_memory, infer_shape, name)
    457         back_prop=back_prop,
    458         swap_memory=swap_memory,
--> 459         maximum_iterations=n)
    460     results_flat = [r.stack() for r in r_a]
    461 

C:\Python36\lib\site-packages\tensorflow\python\ops\control_flow_ops.py in while_loop(cond, body, loop_vars, shape_invariants, parallel_iterations, back_prop, swap_memory, name, maximum_iterations, return_same_structure)
   3230       ops.add_to_collection(ops.GraphKeys.WHILE_CONTEXT, loop_context)
   3231     result = loop_context.BuildLoop(cond, body, loop_vars, shape_invariants,
-> 3232                                     return_same_structure)
   3233     if maximum_iterations is not None:
   3234       return result[1]

C:\Python36\lib\site-packages\tensorflow\python\ops\control_flow_ops.py in BuildLoop(self, pred, body, loop_vars, shape_invariants, return_same_structure)
   2950       with ops.get_default_graph()._mutation_lock():  # pylint: disable=protected-access
   2951         original_body_result, exit_vars = self._BuildLoop(
-> 2952             pred, body, original_loop_vars, loop_vars, shape_invariants)
   2953     finally:
   2954       self.Exit()

C:\Python36\lib\site-packages\tensorflow\python\ops\control_flow_ops.py in _BuildLoop(self, pred, body, original_loop_vars, loop_vars, shape_invariants)
   2885         flat_sequence=vars_for_body_with_tensor_arrays)
   2886     pre_summaries = ops.get_collection(ops.GraphKeys._SUMMARY_COLLECTION)  # pylint: disable=protected-access
-> 2887     body_result = body(*packed_vars_for_body)
   2888     post_summaries = ops.get_collection(ops.GraphKeys._SUMMARY_COLLECTION)  # pylint: disable=protected-access
   2889     if not nest.is_sequence(body_result):

C:\Python36\lib\site-packages\tensorflow\python\ops\control_flow_ops.py in <lambda>(i, lv)
   3199         cond = lambda i, lv: (  # pylint: disable=g-long-lambda
   3200             math_ops.logical_and(i < maximum_iterations, orig_cond(*lv)))
-> 3201         body = lambda i, lv: (i + 1, orig_body(*lv))
   3202 
   3203     if context.executing_eagerly():

C:\Python36\lib\site-packages\tensorflow\python\ops\functional_ops.py in compute(i, tas)
    446       """
    447       packed_values = input_pack([elem_ta.read(i) for elem_ta in elems_ta])
--> 448       packed_fn_values = fn(packed_values)
    449       nest.assert_same_structure(dtype or elems, packed_fn_values)
    450       flat_fn_values = output_flatten(packed_fn_values)

E:\Deep Learning Material\IMP for Project\model\scripts\loss_function.py in sum_of_log_probabilities(true_and_pred)
     10         print(K.int_shape(y_pred_start))
     11         print(K.int_shape(y_pred_end))
---> 12         start_index = int(y_true[0])
     13         end_index = int(y_true[1])
     14         start_probability = y_pred_start[start_index]

TypeError: int() argument must be a string, a bytes-like object or a number, not 'Tensor'
```

The problem:

y_pred_start = y_pred[0]
```
y_pred_end = y_pred[1]

print(K.int_shape(y_pred)) -> (2, None, None)
print(K.int_shape(y_pred_start)) -> (None, None, 1) instead of (None, None)
print(K.int_shape(y_pred_end)) -> (None, None, 1) instead of (None, None)
```

Where do this extra '1' come from after slicing?

**Comment by ParikhKadam** [comment]
Please help... @yongtang

**Comment by ParikhKadam** [comment]
An update.. There's no problem with slicing or tf.map_fn(). There seems to be a problem with y_pred.

Reason:
On iterating, tf.map_fn() returned elements of (None, 1) and slicing too returns this extra 1 at the end which is (None, None, 1). And this happens only with y_pred and not with y_true.

Question:
So, what's actually wrong with y_pred?

**Comment by ParikhKadam** [comment]
@bstriner Sir, I have read many issue threads on loss function in Keras and seen you provide a solution there.. Maybe you can help me here..
