### ISSUE TITLE
I get problem when I run my tensorflow codes on multi gpu

### ISSUE THREAD

**Issue by demeiyan** [tensorflow/tensorflow#24530]
I still have problem after I add

```
sess_config = tf.ConfigProto(allow_soft_placement=True, log_device_placement=True)
sess_config.gpu_options.allow_growth = True
with tf.Session(config=sess_config) as sess:
```

I use Tensorflow-gpu 1.12.0.I run BIDAF model on multi gpu and I get the problem below.

```

Device mapping:
/job:localhost/replica:0/task:0/device:XLA_CPU:0 -> device: XLA_CPU device
/job:localhost/replica:0/task:0/device:XLA_GPU:0 -> device: XLA_GPU device
/job:localhost/replica:0/task:0/device:GPU:0 -> device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:3b:00.0, compute capability: 6.1
Traceback (most recent call last):
  File "/home/home1/dmyan/.conda/envs/py_env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/home/home1/dmyan/.conda/envs/py_env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1317, in _run_fn
    self._extend_graph()
  File "/home/home1/dmyan/.conda/envs/py_env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1352, in _extend_graph
    tf_session.ExtendSession(self._session)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device for operation tower_0/passage_encoding/bidirectional_rnn/fw/fw/Assert/Assert: Could not satisfy explicit device specification '/device:GPU:0' because no supported kernel for GPU devices is available.
Registered kernels:
  device='CPU'

         [[{{node tower_0/passage_encoding/bidirectional_rnn/fw/fw/Assert/Assert}} = Assert[T=[DT_STRING,DT_INT32, DT_STRING, DT_INT32], summarize=3, _device="/device:GPU:0"](tower_0/passage_encoding/bidirectional_rnn/fw/fw/All, tower_0/passage_encoding/bidirectional_rnn/fw/fw/Assert/Assert/data_0, tower_0/passage_encoding/bidirectional_rnn/fw/fw/stack, tower_0/passage_encoding/bidirectional_rnn/fw/fw/Assert/Assert/data_2, tower_0/passage_encoding/bidirectional_rnn/fw/fw/Shape_1)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 408, in <module>
    run()
  File "run.py", line 399, in run
    multi_gpu_train(args)
  File "run.py", line 249, in multi_gpu_train
    model = RCModel_ngpus(args, data)
  File "/home/home1/dmyan/codes/tensorflow/rc_model_multi_gpu.py", line 80, in __init__
    self.sess.run(tf.global_variables_initializer())
  File "/home/home1/dmyan/.conda/envs/py_env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/home1/dmyan/.conda/envs/py_env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/home1/dmyan/.conda/envs/py_env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/home1/dmyan/.conda/envs/py_env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device for operation tower_0/passage_encoding/bidirectional_rnn/fw/fw/Assert/Assert: Could not satisfy explicit device specification '/device:GPU:0' because no supported kernel for GPU devices is available.
Registered kernels:
  device='CPU'

         [[node tower_0/passage_encoding/bidirectional_rnn/fw/fw/Assert/Assert (defined at /home/home1/dmyan/codes/tensorflow/layers/basic_rnn.py:51)  = Assert[T=[DT_STRING, DT_INT32, DT_STRING, DT_INT32], summarize=3, _device="/device:GPU:0"](tower_0/passage_encoding/bidirectional_rnn/fw/fw/All, tower_0/passage_encoding/bidirectional_rnn/fw/fw/Assert/Assert/data_0, tower_0/passage_encoding/bidirectional_rnn/fw/fw/stack, tower_0/passage_encoding/bidirectional_rnn/fw/fw/Assert/Assert/data_2, tower_0/passage_encoding/bidirectional_rnn/fw/fw/Shape_1)]]

Caused by op 'tower_0/passage_encoding/bidirectional_rnn/fw/fw/Assert/Assert', defined at:
  File "run.py", line 408, in <module>
    run()
  File "run.py", line 399, in run
    multi_gpu_train(args)
  File "run.py", line 249, in multi_gpu_train
    model = RCModel_ngpus(args, data)
  File "/home/home1/dmyan/codes/tensorflow/rc_model_multi_gpu.py", line 74, in __init__
    self._build_graph()
  File "/home/home1/dmyan/codes/tensorflow/rc_model_multi_gpu.py", line 87, in _build_graph
    self._encode()
  File "/home/home1/dmyan/codes/tensorflow/rc_model_multi_gpu.py", line 102, in _encode
    self.sep_p_encodes, _ = rnn('bi-lstm', self.p_emb, self.p_length, self.hidden_size)
  File "/home/home1/dmyan/codes/tensorflow/layers/basic_rnn.py", line 51, in rnn
    cell_bw, cell_fw, inputs, sequence_length=length, dtype=tf.float32
  File "/home/home1/dmyan/.conda/envs/py_env/lib/python3.6/site-packages/tensorflow/python/ops/rnn.py", line 439, in bidirectional_dynamic_rnn
    time_major=time_major, scope=fw_scope)
  File "/home/home1/dmyan/.conda/envs/py_env/lib/python3.6/site-packages/tensorflow/python/ops/rnn.py", line 651, in dynamic_rnn
    [_assert_has_shape(sequence_length, [batch_size])]):
  File "/home/home1/dmyan/.conda/envs/py_env/lib/python3.6/site-packages/tensorflow/python/ops/rnn.py", line 646, in _assert_has_shape
    packed_shape, " but saw shape: ", x_shape])
  File "/home/home1/dmyan/.conda/envs/py_env/lib/python3.6/site-packages/tensorflow/python/util/tf_should_use.py", line 189, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs))
  File "/home/home1/dmyan/.conda/envs/py_env/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 159, in Assert
    return gen_logging_ops._assert(condition, data, summarize, name="Assert")
  File "/home/home1/dmyan/.conda/envs/py_env/lib/python3.6/site-packages/tensorflow/python/ops/gen_logging_ops.py", line 52, in _assert
    name=name)
  File "/home/home1/dmyan/.conda/envs/py_env/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/home1/dmyan/.conda/envs/py_env/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/home/home1/dmyan/.conda/envs/py_env/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/home/home1/dmyan/.conda/envs/py_env/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Cannot assign a device for operation tower_0/passage_encoding/bidirectional_rnn/fw/fw/Assert/Assert: Could not satisfy explicit device specification '/device:GPU:0' because no supported kernel for GPU devices is available.
Registered kernels:
  device='CPU'

         [[node tower_0/passage_encoding/bidirectional_rnn/fw/fw/Assert/Assert (defined at /home/home1/dmyan/codes/tensorflow/layers/basic_rnn.py:51)  = Assert[T=[DT_STRING, DT_INT32, DT_STRING, DT_INT32], summarize=3, _device="/device:GPU:0"](tower_0/passage_encoding/bidirectional_rnn/fw/fw/All, tower_0/passage_encoding/bidirectional_rnn/fw/fw/Assert/Assert/data_0, tower_0/passage_encoding/bidirectional_rnn/fw/fw/stack, tower_0/passage_encoding/bidirectional_rnn/fw/fw/Assert/Assert/data_2, tower_0/passage_encoding/bidirectional_rnn/fw/fw/Shape_1)]]

```

**Comment by lxl910915** [comment]
AssertOp's registered kernel is CPU, so you can not assign it on GPU.

**Comment by msymp** [comment]
Hello @demeiyan , please let us know if @lxl910915 comments has addressed you query sufficiently. Thanks.

**Comment by demeiyan** [comment]
no,I can not run bi-lstm on multi gpu. And do not know how to run.

**Comment by demeiyan** [comment]
I don't set os.environ["CUDA_VISIBLE_DEVICES"] . I solve the problem. Thanks !

**Comment by hoangcuong2011** [comment]
@demeiyan : I wonder how you solved the problem then? Remove os.environ["CUDA_VISIBLE_DEVICES"] did not help for my case! 
Thx
