### ISSUE TITLE
Error ValueError: Unknown field group_norm

### ISSUE THREAD

**Issue by Vitax** [tensorflow/tensorflow#24544]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): v1.12.0-0-ga6d8ffae09 1.12.0
- Python version: 3.5.2
- Bazel version (if compiling from source): No
- GCC/Compiler version (if compiling from source): No
- CUDA/cuDNN version: 9.0
- GPU model and memory: GTX 1060

**Describe the current behavior**
I have a Docker instance of Cuda and Tensorflow which I run with a nvidia container.

This container is being started with the following command: sudo docker run --runtime=nvidia -it -v $(pwd):/code --rm -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=$DISPLAY -e QT_X11_NO_MITSHM=1 ce2d9c04faa2 bash

When executing the following command in the container : python3 model_main.py --pipeline_config_path ./train_results/rcnn_inception3/faster_rcnn_inception_v2_coco.config --model_dir ./train_results/rcnn_inception3/ --logstderr

I get the exception: 

Traceback (most recent call last):
  File "model_main.py", line 109, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "model_main.py", line 105, in main
    tf.estimator.train_and_evaluate(estimator, train_spec, eval_specs[0])
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/training.py", line 471, in train_and_evaluate
    return executor.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/training.py", line 610, in run
    return self.run_local()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/training.py", line 711, in run_local
    saving_listeners=saving_listeners)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 354, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 1207, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 1234, in _train_model_default
    input_fn, model_fn_lib.ModeKeys.TRAIN))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 1075, in _get_features_and_labels_from_input_fn
    self._call_input_fn(input_fn, mode))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 1162, in _call_input_fn
    return input_fn(**kwargs)
  File "/code/image_retrieval/tensorflow/models/research/object_detection/inputs.py", line 488, in _train_input_fn
    batch_size=params['batch_size'] if params else train_config.batch_size)
  File "/code/image_retrieval/tensorflow/models/research/object_detection/builders/dataset_builder.py", line 145, in build
    num_parallel_calls=num_parallel_calls)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 1040, in map
    return ParallelMapDataset(self, map_func, num_parallel_calls)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 2649, in __init__
    use_inter_op_parallelism)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 2611, in __init__
    map_func, "Dataset.map()", input_dataset)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 1860, in __init__
    self._function.add_to_graph(ops.get_default_graph())
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/function.py", line 479, in add_to_graph
    self._create_definition_if_needed()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/function.py", line 335, in _create_definition_if_needed
    self._create_definition_if_needed_impl()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/function.py", line 344, in _create_definition_if_needed_impl
    self._capture_by_value, self._caller_device)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/function.py", line 864, in func_graph_from_py_func
    outputs = func(*func_graph.inputs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 1794, in tf_data_structured_function_wrapper
    ret = func(*nested_args)
  File "/code/image_retrieval/tensorflow/models/research/object_detection/builders/dataset_builder.py", line 129, in process_fn
    processed_tensors = transform_input_data_fn(processed_tensors)
  File "/code/image_retrieval/tensorflow/models/research/object_detection/inputs.py", line 465, in transform_and_pad_input_data_fn
    model = model_builder.build(model_config, is_training=True)
  File "/code/image_retrieval/tensorflow/models/research/object_detection/builders/model_builder.py", line 122, in build
    add_summaries)
  File "/code/image_retrieval/tensorflow/models/research/object_detection/builders/model_builder.py", line 389, in _build_faster_rcnn_model
    frcnn_config.first_stage_box_predictor_conv_hyperparams, is_training)
  File "/code/image_retrieval/tensorflow/models/research/object_detection/builders/hyperparams_builder.py", line 218, in build
    if hyperparams_config.HasField('group_norm'):
ValueError: Unknown field group_norm.

My config file is the default one, with changed pathes to fit the environment

**Describe the expected behavior**

Tensorflow training session being started

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by Vitax** [comment]
I resolved this Error by deleting all my container / images and creating a fresh docker container. Funny thing is it worked a couple days ago, seems like I broke something while trying things out.
