### ISSUE TITLE
How to use the Indexdslice for sparse update ？

### ISSUE THREAD

**Issue by tTianyu** [tensorflow/tensorflow#24540]
Hi~everyone :)
I‘m try to use  sparsed gradients to the apply_gradient func and I have turn my gradients to IndexdSlice:
`grads[i] = tf.IndexedSlices(values = tf.gather_nd(grads[i], idx), indices = idx, dense_shape = tf.identity(grads[i].get_shape()))`
and with vars_list,
`vars_list = [v for _, v in grads_vars]
....
grads_vars[i]  = (grads[i], vars_list[i])`
the I put the grads_vars into the apply_gradient func , but it didn't work, this is the error msg:
`Traceback (most recent call last):
  File "12-13_linner.py", line 147, in <module>
    residual, new_grads_vars, grads, residual_mask, new_grads = grads_sparse(grads_vars, global_steps, residual_accum, sess)
  File "12-13_linner.py", line 63, in grads_sparse
    vars_list[i].scatter_sub(delta, use_locking=False)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variables.py", line 700, in scatter_sub
    use_locking=use_locking)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_state_ops.py", line 1141, in scatter_sub
    use_locking=use_locking, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3155, in create_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1731, in __init__
    control_input_ops)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1579, in _create_c_op
    raise ValueError(str(e))
ValueError: Shapes must be equal rank, but are 1 and 3 for 'ScatterSub' (op: 'ScatterSub') with input shapes: [1,10], [?,2], [?].
`  
then I print the grads , 
`[IndexedSlicesValue(values=array([ 0.15668039,  0.14776216, -0.15483621, -0.15541458,  0.14010738,
       -0.2145288 , -0.19674896], dtype=float32), indices=array([[0, 1],
       [0, 2],
       [0, 3],
       [0, 5],
       [0, 6],
       [0, 8],
       [0, 9]]), dense_shape=array([ 1, 10], dtype=int32)), 
IndexedSlicesValue(values=array([ 0.10107333, -0.17999038,  0.24159592, -0.18415265, -0.16449636,
       -0.15763052,  0.24781035, -0.11305401], dtype=float32), indices=array([[0, 0],
       [0, 1],
       [0, 2],
       [0, 3],
       [0, 5],
       [0, 6],
       [0, 8],
       [0, 9]]), dense_shape=array([ 1, 10], dtype=int32)), 
IndexedSlicesValue(values=array([-0.2975006 , -0.12903467, -0.1116452 , -0.15254416, -0.15824951,
       -0.33808792, -0.10385308], dtype=float32), indices=array([[0, 0],
       [2, 0],
       [3, 0],
       [6, 0],
       [7, 0],
       [8, 0],
       [9, 0]]), dense_shape=array([10,  1], dtype=int32)), 
IndexedSlicesValue(values=array([-0.53333503], dtype=float32), indices=array([[0, 0]]), dense_shape=array([1, 1], dtype=int32))]`
and var_list:
`[array([[ 0.62123364,  0.8572454 ,  0.64919454,  1.4851073 ,  1.0997279 ,
        -1.718374  ,  0.59419113, -1.4921925 ,  0.0046594 ,  1.0894274 ]],
      dtype=float32), 
 array([[0.1021007 , 0.03610747, 0.08513964, 0.08579567, 0.08281428,
        0.05231547, 0.04030512, 0.11618505, 0.14989284, 0.06900915]],
      dtype=float32), 
 array([[-0.57928437],
       [-2.0731926 ],
       [-1.3741436 ],
       [-0.32964215],
       [ 0.69279206],
       [ 0.22279441],
       [ 1.3773512 ],
       [-0.14758699],
       [-0.3795929 ],
       [ 1.3115551 ]], dtype=float32), 
 array([[-0.03738503]], dtype=float32)]`
it's seems that the have the same shape, can anyone help me how to fix it ? or tell me the right way to use the apply_gradients with the IndexdSlice, pls.

**Comment by hgadig** [comment]
Hi, request you to post any support related questions in [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow). We encourage users to post only bug/feature request here. If you think it is a bug/feature, please fill this template and open a new issue. Thank you !
