### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by toxicmender** [tensorflow/tensorflow#24554]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 Home 64-bit version: 1809
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 1.12.0 (gpu)
- Python version: 3.6.8 64-bit
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: CUDA 10.0.130/cuDNN 7.4.2.24
- GPU model and memory: Nvidia GeForce 940MX 4GB
- GPU Drivers: 417.35

**Describe the problem**
When importing tensorflow in python interpreter ImportError is encountered.
`CUDA toolkit 10.0` is installed & tested on visual studio using sample project builds.
`cuDNN 7.4.2.24` is installed & extracted in `C:\tools\` with `C:\tools\cuda\bin` containing `cudnn64_7.dll`
```cmd
SET PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin;%PATH%
SET PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\extras\CUPTI\libx64;%PATH%
SET PATH=C:\tools\cuda\bin;%PATH%
```
I haven't installed the following as they were required for installation from source rather than binary, although the newer versions of both (2017) are installed
```
Microsoft Visual C++ 2015 Redistributable Update 3
Microsoft Build Tools 2015 Update 3
```

**Provide the exact sequence of commands / steps that you executed before running into the problem**
```py
import tensorflow as tf
```

**Any other info / logs**
```
Traceback (most recent call last):
  File "C:\Users\Danis\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Danis\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Danis\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Danis\AppData\Local\Programs\Python\Python36\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Danis\AppData\Local\Programs\Python\Python36\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Danis\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\Danis\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Danis\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Danis\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Danis\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Danis\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Danis\AppData\Local\Programs\Python\Python36\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Danis\AppData\Local\Programs\Python\Python36\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

**Comment by toxicmender** [comment]
#22872 seems to bear the closest resemblance but I'd still like confirmation for tensorflow 1.12 as it was built against CUDA 10.0 (or maybe it's 1.13 onwards)?

**Comment by toxicmender** [comment]
Based on Nvidia's [Developer Guide](https://docs.nvidia.com/deeplearning/sdk/cudnn-install/index.html) for cuDNN:

Copy `<installpath>\cuda\bin\cudnn64_7.dll` to `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin`.
Copy `<installpath>\cuda\ include\cudnn.h` to `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\include`.
Copy `<installpath>\cuda\lib\x64\cudnn.lib` to `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\lib\x64`.

where `<installpath>` was `C:\tools\` in my case, while in default case `cudnn-10.0-windows10-x64-v7.4.2.24`

```cmd
SET CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0
```

Even this didn't help resolve the issue though

**Comment by toxicmender** [comment]
Just to confirm if the issue was with `tensorflow-gpu`==1.12.0, I uninstalled `tensorflow-gpu` from `pip` & installed `tensorflow`==1.12.0 instead to test if that worked. There were no `ImportError`s or any runtime errors from running sample code from site.

**Comment by toxicmender** [comment]
Apparently `tensorflow-gpu`==1.13 [ as on date of comment `tf-nightly-gpu`==1.13.0dev20181225] seems to work without `ImportError` for `CUDA toolkit` 10.0 with `cuDNN` 7.4.2.24. While `tensorflow-gpu`==1.12.0 seems to expect `CUDA` toolkit 9.0 or 9.2 [Have read about `CUDA` 9.0 being supported since `tensorflow`==1.5+ but haven't actually tested it]. 

There seems to be a lot of depreciated code in what I was using, though no such warning came when running `tensorflow`==1.12.0. The Example was an XLA compile API based example.

For anyone stumbling along later:

check for 
 - `nvcuda.dll` in your `c:\windows\system32` &/or `c:\windows\sysWOW64`. Should be present beforehand if you've installed the [`GPU drivers`](https://www.geforce.com/drivers) & your GPU supports `CUDA`.
 - `msvcp140.dll` in your `c:\windows\system32` &/or `c:\windows\sysWOW64`. Obtained from [`Microsoft Visual C++ 2015 Redistributable Update 3`](https://visualstudio.microsoft.com/vs/older-downloads/) though I had a recent version installed beforehand (2017) which works as well. 
 -  `cudart64_100.dll`[for CUDA v10.0] in your CUDA installation directory `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin`. Obtained from [`CUDA Toolkit`](https://developer.nvidia.com/cuda-downloads) installation.
 - `cudnn64_7.dll` in your CUDA installation directory `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin`. Obtained from [`cuDNN`](https://developer.nvidia.com/rdp/form/cudnn-download-survey) installation.
