### ISSUE TITLE
tf_python_api  build failed, ImportError: No module named '_pywrap_tensorflow_internal'

### ISSUE THREAD

**Issue by clooney2007** [tensorflow/tensorflow#24564]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
-  windows 10
- TensorFlow installed from: source 
- TensorFlow version: r1.8
- Python version: 3.5
- win10 + cmake +vs2015 source build, Debug X64
-  installed conda tensorflow 1.8
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 9.0 / 7.1
- GPU model and memory: GTX 1070

**Describe the problem**
I build 275 projects with Gpu-option, pywrap_tensorflow_internal.dll and tensorflow.dll is build out;  
All successful  except tf_python_api .  build error info :  ImportError: DLL load failed: 找不到指定的模块。ImportError: No module named '_pywrap_tensorflow_internal'.

I  try to fix it by copying pywrap_tensorflow_internal.dll and pywrap_tensorflow_internal.pyd into system32 dir, but it don't take effect.

Detail info:
259>------ 已启动生成: 项目: tf_python_api, 配置: Debug x64 ------
259>  Generating __init__.py files for Python API.
259>  Traceback (most recent call last):
259>    File "E:\TensorBuilds\tensorflow\tensorflow\contrib\cmake\build\tf_python\tensorflow\python\pywrap_tensorflow_internal.py", line 14, in swig_import_helper
259>      return importlib.import_module(mname)
259>    File "D:\AppProgram\Anaconda2\envs\py3\lib\importlib\__init__.py", line 126, in import_module
259>      return _bootstrap._gcd_import(name[level:], package, level)
259>    File "<frozen importlib._bootstrap>", line 986, in _gcd_import
259>    File "<frozen importlib._bootstrap>", line 969, in _find_and_load
259>    File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
259>    File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
259>    File "<frozen importlib._bootstrap>", line 577, in module_from_spec
259>    File "<frozen importlib._bootstrap_external>", line 906, in create_module
259>    File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
259>  ImportError: DLL load failed: 找不到指定的模块。
259>
259>  During handling of the above exception, another exception occurred:
259>
259>  Traceback (most recent call last):
259>    File "E:\TensorBuilds\tensorflow\tensorflow\contrib\cmake\build\tf_python\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
259>      from tensorflow.python.pywrap_tensorflow_internal import *
259>    File "E:\TensorBuilds\tensorflow\tensorflow\contrib\cmake\build\tf_python\tensorflow\python\pywrap_tensorflow_internal.py", line 17, in <module>
259>      _pywrap_tensorflow_internal = swig_import_helper()
259>    File "E:\TensorBuilds\tensorflow\tensorflow\contrib\cmake\build\tf_python\tensorflow\python\pywrap_tensorflow_internal.py", line 16, in swig_import_helper
259>      return importlib.import_module('_pywrap_tensorflow_internal')
259>    File "D:\AppProgram\Anaconda2\envs\py3\lib\importlib\__init__.py", line 126, in import_module
259>      return _bootstrap._gcd_import(name[level:], package, level)
259>  ImportError: No module named '_pywrap_tensorflow_internal'
259>
259>  During handling of the above exception, another exception occurred:
259>
259>  Traceback (most recent call last):
259>    File "E:/TensorBuilds/tensorflow/tensorflow/contrib/cmake/build/tf_python/tensorflow/tools/api/generator/create_python_api.py", line 26, in <module>
259>      from tensorflow.python.util import tf_decorator
259>    File "E:\TensorBuilds\tensorflow\tensorflow\contrib\cmake\build\tf_python\tensorflow\python\__init__.py", line 49, in <module>
259>      from tensorflow.python import pywrap_tensorflow
259>    File "E:\TensorBuilds\tensorflow\tensorflow\contrib\cmake\build\tf_python\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
259>      raise ImportError(msg)
259>  ImportError: Traceback (most recent call last):
259>    File "E:\TensorBuilds\tensorflow\tensorflow\contrib\cmake\build\tf_python\tensorflow\python\pywrap_tensorflow_internal.py", line 14, in swig_import_helper
259>      return importlib.import_module(mname)
259>    File "D:\AppProgram\Anaconda2\envs\py3\lib\importlib\__init__.py", line 126, in import_module
259>      return _bootstrap._gcd_import(name[level:], package, level)
259>    File "<frozen importlib._bootstrap>", line 986, in _gcd_import
259>    File "<frozen importlib._bootstrap>", line 969, in _find_and_load
259>    File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
259>    File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
259>    File "<frozen importlib._bootstrap>", line 577, in module_from_spec
259>    File "<frozen importlib._bootstrap_external>", line 906, in create_module
259>    File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
259>  ImportError: DLL load failed: 找不到指定的模块。
259>
259>  During handling of the above exception, another exception occurred:
259>
259>  Traceback (most recent call last):
259>    File "E:\TensorBuilds\tensorflow\tensorflow\contrib\cmake\build\tf_python\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
259>      from tensorflow.python.pywrap_tensorflow_internal import *
259>    File "E:\TensorBuilds\tensorflow\tensorflow\contrib\cmake\build\tf_python\tensorflow\python\pywrap_tensorflow_internal.py", line 17, in <module>
259>      _pywrap_tensorflow_internal = swig_import_helper()
259>    File "E:\TensorBuilds\tensorflow\tensorflow\contrib\cmake\build\tf_python\tensorflow\python\pywrap_tensorflow_internal.py", line 16, in swig_import_helper
259>      return importlib.import_module('_pywrap_tensorflow_internal')
259>    File "D:\AppProgram\Anaconda2\envs\py3\lib\importlib\__init__.py", line 126, in import_module
259>      return _bootstrap._gcd_import(name[level:], package, level)
259>  ImportError: No module named '_pywrap_tensorflow_internal'
259>
259>
259>  Failed to load the native TensorFlow runtime.
259>
259>  See https://www.tensorflow.org/install/install_sources#common_installation_problems
259>
259>  for some common reasons and solutions.  Include the entire stack trace
259>  above this error message when asking for help.
259>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6006: “cmd.exe”已退出，代码为 1。
========== 生成: 成功 0 个，失败 1 个，最新 0 个，跳过 258 个 ==========

**Comment by clooney2007** [comment]
cmake python version is wrong.
