### ISSUE TITLE
total_loss attribute not found when fitting a Sequential model using a validation dataset

### ISSUE THREAD

**Issue by ageron** [tensorflow/tensorflow#24577]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Mac OS X 10.13.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
N/A
- TensorFlow installed from (source or binary):
binary
- TensorFlow version (use command below):
VERSION=1.13.0-dev20181225
GIT_VERSION=b'v1.12.0-5131-gc6f3c5dc48'
- Python version:
3.6.6
- Bazel version (if compiling from source):
N/A
- GCC/Compiler version (if compiling from source):
N/A
- CUDA/cuDNN version:
N/A
- GPU model and memory:
N/A

**Describe the current behavior**
I try to fit a `Sequential` model with both a training dataset and a validation dataset. Works fine in TF 1.12, but the same code now fails in 1.13.0-dev20181225 (`total_loss` attribute not found).

**Describe the expected behavior**
Training should work fine.

**Code to reproduce the issue**

```python
import tensorflow as tf
from tensorflow import keras
import numpy as np

X_train = np.random.rand(1000, 2).astype(np.float32)
y_train = np.random.rand(1000).astype(np.float32)
X_valid = np.random.rand(200, 2).astype(np.float32)
y_valid = np.random.rand(200).astype(np.float32)
batch_size = 32
learning_rate = 0.01

train_set = tf.data.Dataset.from_tensor_slices((X_train, y_train)).repeat().batch(batch_size)
valid_set = tf.data.Dataset.from_tensor_slices((X_valid, y_valid)).repeat().batch(batch_size)

model = keras.models.Sequential([keras.layers.Dense(1)])
model.compile(loss="mse", optimizer=keras.optimizers.SGD(learning_rate))

model.fit(train_set, epochs=5,
          steps_per_epoch=len(X_train) // batch_size,
          validation_data=valid_set,
          validation_steps=len(X_valid) // batch_size)
```

**Other info / logs**
Here is the stacktrace:

```python
>>> model.fit(train_set, epochs=5,
...           steps_per_epoch=len(X_train) // batch_size,
...           validation_data=valid_set,
...           validation_steps=len(X_valid) // batch_size)
WARNING:tensorflow:From /Users/ageron/.virtualenvs/tf2/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py:1732: DatasetV1.make_one_shot_iterator (from tensorflow.python.data.ops.dataset_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `for ... in dataset:` to iterate over a dataset. If using `tf.estimator`, return the `Dataset` object directly from your input function. As a last resort, you can use `tf.compat.v1.data.make_one_shot_iterator(dataset)`.
WARNING:tensorflow:From /Users/ageron/.virtualenvs/tf2/lib/python3.6/site-packages/tensorflow/python/data/ops/iterator_ops.py:532: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/Users/ageron/.virtualenvs/tf2/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 829, in fit
    initial_epoch=initial_epoch)
  File "/Users/ageron/.virtualenvs/tf2/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1492, in fit_generator
    initial_epoch=initial_epoch)
  File "/Users/ageron/.virtualenvs/tf2/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_generator.py", line 149, in model_iteration
    mode=mode)
  File "/Users/ageron/.virtualenvs/tf2/lib/python3.6/site-packages/tensorflow/python/keras/callbacks.py", line 132, in configure_callbacks
    callback_model._make_eval_function()
  File "/Users/ageron/.virtualenvs/tf2/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 2063, in _make_eval_function
    '_eval_function', [self.total_loss] + metrics_tensors)
AttributeError: 'Sequential' object has no attribute 'total_loss'
```

**Comment by yongtang** [comment]
@ageron I tried the same tf-nightly on Ubuntu and it looks to be fine:
```
# python3
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> tf.VERSION
'1.13.0-dev20181225'
>>> tf.GIT_VERSION
"b'v1.12.0-5131-gc6f3c5dc48'"
>>> exit()
root@ubuntu:/v# python3 24577.py 
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/init_ops.py:1253: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/resource_variable_ops.py:439: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/dataset_ops.py:1761: DatasetV1.make_initializable_iterator (from tensorflow.python.data.ops.dataset_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `for ... in dataset:` to iterate over a dataset. If using `tf.estimator`, return the `Dataset` object directly from your input function. As a last resort, you can use `tf.compat.v1.data.make_initializable_iterator(dataset)`.
2018-12-26 20:48:23.241652: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2018-12-26 20:48:23.275192: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2499995000 Hz
2018-12-26 20:48:23.275687: I tensorflow/compiler/xla/service/service.cc:161] XLA service 0x25e4ce0 executing computations on platform Host. Devices:
2018-12-26 20:48:23.275715: I tensorflow/compiler/xla/service/service.cc:168]   StreamExecutor device (0): <undefined>, <undefined>
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/utils/losses_utils.py:170: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Epoch 1/5
31/31 [==============================] - 0s 9ms/step - loss: 0.1204 - val_loss: 0.1172
Epoch 2/5
31/31 [==============================] - 0s 2ms/step - loss: 0.1114 - val_loss: 0.1122
Epoch 3/5
31/31 [==============================] - 0s 1ms/step - loss: 0.1080 - val_loss: 0.1068
Epoch 4/5
31/31 [==============================] - 0s 1ms/step - loss: 0.1061 - val_loss: 0.1065
Epoch 5/5
31/31 [==============================] - 0s 1ms/step - loss: 0.1056 - val_loss: 0.1040
root@ubuntu:/v# 
```

I am wondering if you completely uninstall the tensorflow/tf-nightly then reinstall again (or delete packages from site-packages/tensorflow completely) might make a difference?

Or this could be specific to Mac only issue?

**Comment by ymodak** [comment]
I was able to run the script successfully in TF 1.13.0-dev20190117. @ageron I will close this issue, please let me know if you still see the error using latest TF build. Thanks!
