### ISSUE TITLE
Using MirroredStrategy for Multi-GPU Training Fails with DNNLinearCombinedClassifier using default FTRL optimizer

### ISSUE THREAD

**Issue by jlertle** [tensorflow/tensorflow#24586]
Many similar issues using MirroredStrategy with other optimizers have been filed. Looks like FTRL optimizer needs to be updated as well.

**Environment**
== cat /etc/issue ===============================================
Linux 1226-234618-hanks421-172-20-170-14 4.4.0-1072-aws #82-Ubuntu SMP Fri Nov 2 15:00:21 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
VERSION="16.04.5 LTS (Xenial Xerus)"
VERSION_ID="16.04"
VERSION_CODENAME=xenial

== are we in docker =============================================
No

== compiler =====================================================
c++ (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

== uname -a =====================================================
Linux 1226-234618-hanks421-172-20-170-14 4.4.0-1072-aws #82-Ubuntu SMP Fri Nov 2 15:00:21 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

== check pips ===================================================
numpy                              1.14.3                   
protobuf                           3.6.1                    
tensorflow                         1.12.0                   

== check for virtualenv =========================================
False

== tensorflow import ============================================
tf.VERSION = 1.12.0
tf.GIT_VERSION = unknown
tf.COMPILER_VERSION = unknown
Sanity check: array([1], dtype=int32)

== env ==========================================================
LD_LIBRARY_PATH /databricks/python/lib:
DYLD_LIBRARY_PATH is unset

== nvidia-smi ===================================================
Thu Dec 27 00:32:16 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 396.44                 Driver Version: 396.44                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  Off  | 00000000:00:1B.0 Off |                    0 |
| N/A   43C    P0    67W / 300W |    503MiB / 16160MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-SXM2...  Off  | 00000000:00:1C.0 Off |                    0 |
| N/A   42C    P0    54W / 300W |    503MiB / 16160MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla V100-SXM2...  Off  | 00000000:00:1D.0 Off |                    0 |
| N/A   42C    P0    56W / 300W |    503MiB / 16160MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla V100-SXM2...  Off  | 00000000:00:1E.0 Off |                    0 |
| N/A   42C    P0    57W / 300W |    503MiB / 16160MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+

== cuda libs  ===================================================
/usr/local/cuda-9.2/targets/x86_64-linux/lib/libcudart_static.a
/usr/local/cuda-9.2/targets/x86_64-linux/lib/libcudart.so.9.2.148
/usr/local/cuda-9.2/doc/man/man7/libcudart.7
/usr/local/cuda-9.2/doc/man/man7/libcudart.so.7

**Describe the current behavior**
Using MirroredStrategy for Multi-GPU Training fails with DNNLinearCombinedClassifier using default FTRL optimizer

**Other info / logs**
```
Traceback (most recent call last):
  File "/databricks/python/lib/python2.7/site-packages/tensorflow/python/training/coordinator.py", line 297, in stop_on_exception
    yield
  File "/databricks/python/lib/python2.7/site-packages/tensorflow/contrib/distribute/python/mirrored_strategy.py", line 177, in _call_for_each_tower
    **merge_kwargs)
  File "/databricks/python/lib/python2.7/site-packages/tensorflow/python/training/optimizer.py", line 665, in _distributed_apply
    self._create_slots(var_list)
  File "/databricks/python/lib/python2.7/site-packages/tensorflow/python/training/ftrl.py", line 125, in _create_slots
    with ops.colocate_with(v):
  File "/databricks/python/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/databricks/python/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 4094, in _colocate_with_for_gradient
    with self.colocate_with(op, ignore_existing):
  File "/databricks/python/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/databricks/python/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 4146, in colocate_with
    op = internal_convert_to_tensor_or_indexed_slices(op, as_ref=True).op
  File "/databricks/python/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1307, in internal_convert_to_tensor_or_indexed_slices
    value, dtype=dtype, name=name, as_ref=as_ref)
  File "/databricks/python/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1146, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/databricks/python/lib/python2.7/site-packages/tensorflow/contrib/distribute/python/values.py", line 439, in _tensor_conversion_mirrored
    assert not as_ref
AssertionError
```

**Comment by dustinbigham** [comment]
I have the same issue trying to use FTRL optimizer with MirroredStrategy on multiple GPUs.

**Comment by jlertle** [comment]
Also failing for ProximalAdagradOptimizer and AdagradDAOptimizer.

**Comment by isaprykin** [comment]
Dies this optimizer https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/optimizers/Ftrl work for you?

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by francotheengineer** [comment]
I am experiencing the same with `tf.train.RMSPropOptimizer()` and `tf.train.AdamOptimizer()`:

```
import tensorflow as tf
from tensorflow import keras

features = tf.data.Dataset.from_tensors([1.]).repeat(10000).batch(10)
labels = tf.data.Dataset.from_tensors([1.]).repeat(10000).batch(10)
train_dataset = tf.data.Dataset.zip((features, labels))

distribution = tf.contrib.distribute.MirroredStrategy()
with distribution.scope():
  inputs = tf.keras.layers.Input(shape=(1,))
  predictions = tf.keras.layers.Dense(1)(inputs)
  model = tf.keras.models.Model(inputs=inputs, outputs=predictions)
  model.compile(loss='mean_squared_error', optimizer=tf.train.AdamOptimizer(learning_rate=0.2))
model.fit(train_dataset, epochs=5, steps_per_epoch=10)
```
Yeilding:

```
2019-05-23 16:56:03.965220: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

WARNING:tensorflow:Not all devices in `tf.distribute.Strategy` are visible to TensorFlow.
WARNING:tensorflow:From /Users/francis/virtualenvs/tf_venv/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From /Users/francis/virtualenvs/tf_venv/lib/python3.6/site-packages/tensorflow/python/keras/utils/losses_utils.py:170: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
WARNING:tensorflow:From /Users/francis/virtualenvs/tf_venv/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Traceback (most recent call last):
  File "/Users/francis/holograb/next_gen_training/test.py", line 21, in <module>
    model.fit(train_dataset, epochs=5, steps_per_epoch=10)
  File "/Users/francis/virtualenvs/tf_venv/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 880, in fit
    validation_steps=validation_steps)
  File "/Users/francis/virtualenvs/tf_venv/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_arrays.py", line 195, in model_iteration
    f = _make_execution_function(model, mode)
  File "/Users/francis/virtualenvs/tf_venv/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_arrays.py", line 122, in _make_execution_function
    return model._make_execution_function(mode)
  File "/Users/francis/virtualenvs/tf_venv/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1983, in _make_execution_function
    self._make_fit_function()
  File "/Users/francis/virtualenvs/tf_venv/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1926, in _make_fit_function
    '_fit_function', [self.total_loss] + metrics_tensors)
  File "/Users/francis/virtualenvs/tf_venv/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1895, in _make_train_function_helper
    params=self._collected_trainable_weights, loss=self.total_loss)
  File "/Users/francis/virtualenvs/tf_venv/lib/python3.6/site-packages/tensorflow/python/keras/optimizers.py", line 763, in get_updates
    grads, global_step=self.iterations)
  File "/Users/francis/virtualenvs/tf_venv/lib/python3.6/site-packages/tensorflow/python/training/optimizer.py", line 612, in apply_gradients
    update_ops.append(processor.update_op(self, grad))
  File "/Users/francis/virtualenvs/tf_venv/lib/python3.6/site-packages/tensorflow/python/training/optimizer.py", line 171, in update_op
    update_op = optimizer._resource_apply_dense(g, self._v)
  File "/Users/francis/virtualenvs/tf_venv/lib/python3.6/site-packages/tensorflow/python/training/adam.py", line 164, in _resource_apply_dense
    m = self.get_slot(var, "m")
  File "/Users/francis/virtualenvs/tf_venv/lib/python3.6/site-packages/tensorflow/python/training/optimizer.py", line 766, in get_slot
    return mirrored_slot.get(device=var.device)
AttributeError: 'ResourceVariable' object has no attribute 'get'
```

**Comment by francotheengineer** [comment]
I solved all my issues with using` tf.keras `and `tf.contrib.distribute.MirroredStrategy()` by upgrading to tf 2.0 nightly. I would recommend the same. 
Note: Do not include `model.fit(..)` in the scope of `tf.contrib.distribute.MirroredStrategy()`.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by jvishnuvardhan** [comment]
Closing this out since I understand it to be resolved, but please let me know if I'm mistaken. Thanks!
