### ISSUE TITLE
Can't run tensorflow on PyCharm at Win10

### ISSUE THREAD

**Issue by CRichterLeipzig** [tensorflow/tensorflow#24606]
Hi, can anyone help me with this errors? I've tried varios Python installations an have installed Cuda 10.
I tried to run TensorFlow-GPU...
```

"C:\Users\Christoph Richter\PycharmProjects\NNV3\Scripts\python.exe" "C:/Users/Christoph Richter/PycharmProjects/NNV3/MNISTTest.py"
Using TensorFlow backend.
Traceback (most recent call last):
  File "C:\Users\Christoph Richter\PycharmProjects\NNV3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Christoph Richter\PycharmProjects\NNV3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Christoph Richter\PycharmProjects\NNV3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Program Files\Python35\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Program Files\Python35\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/Christoph Richter/PycharmProjects/NNV3/MNISTTest.py", line 1, in <module>
    import keras
  File "C:\Users\Christoph Richter\PycharmProjects\NNV3\lib\site-packages\keras\__init__.py", line 3, in <module>
    from . import utils
  File "C:\Users\Christoph Richter\PycharmProjects\NNV3\lib\site-packages\keras\utils\__init__.py", line 6, in <module>
    from . import conv_utils
  File "C:\Users\Christoph Richter\PycharmProjects\NNV3\lib\site-packages\keras\utils\conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "C:\Users\Christoph Richter\PycharmProjects\NNV3\lib\site-packages\keras\backend\__init__.py", line 89, in <module>
    from .tensorflow_backend import *
  File "C:\Users\Christoph Richter\PycharmProjects\NNV3\lib\site-packages\keras\backend\tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf
  File "C:\Users\Christoph Richter\PycharmProjects\NNV3\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\Christoph Richter\PycharmProjects\NNV3\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Christoph Richter\PycharmProjects\NNV3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Christoph Richter\PycharmProjects\NNV3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Christoph Richter\PycharmProjects\NNV3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Christoph Richter\PycharmProjects\NNV3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Program Files\Python35\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Program Files\Python35\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

Process finished with exit code 1
```

**Comment by ymodak** [comment]
Duplicate #22794

**Comment by AksBrijSandy** [comment]
@ymodak How to resolve this? #22794 does not mention any solution. In that issue, many people have stated that they faced the same issue. But what's the solution? Mine is not GPU version, rather I am using CPU version of tensorflow. Still I am getting error related to pywrap. Please help.

**Comment by ymodak** [comment]
@CRichterLeipzig @AksBrijSandy Can you please try setting a virtual environment and install TensorFlow?
Apparently there's an issue with other ide's used for installation.

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
