### ISSUE TITLE
Tensorflow docker image doesn't set correct `LD_LIBRARY_PATH` variable for CUDA libraries

### ISSUE THREAD

**Issue by xulongwu4** [tensorflow/tensorflow#24614]
I ran the tensorflow docker with GPU support with the following command:
```
docker run --runtime=nvidia -it --rm tensorflow/tensorflow:latest-devel-gpu-py3 python -c "import tensorflow as tf; tf.enable_eager_execution(); print(tf.reduce_sum(tf.random_normal([1000, 1000])))"
```

I got the following error message:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

It complains that the library `libcublas.so.9.0` cannot be found.

I then started a bash session with the following command:
```
docker run --runtime=nvidia -it --rm tensorflow/tensorflow:latest-devel-gpu-py3 bash
```
and checked the variable `LD_LIBRARY_PATH`:
```
$ echo $LD_LIBRARY_PATH
/usr/local/cuda/extras/CUPTI/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64

$ ls /usr/local/
bin  cuda  cuda-9.0  etc  games  include  lib  man  sbin  share  src
```

As we can see, there is no `/usr/local/nvidia` directory in the docker image. The `libcublas.so.9.0` library can be found at `/usr/local/cuda/lib64`.

To fix this problem, the `LD_LIBRARY_PATH` variable should be set to `/usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/lib:/usr/local/cuda/lib64`.

**Comment by jvishnuvardhan** [comment]
@xulongwu4 This is really helpful for people who are facing similar issues. Could you mention your system configuration? Thanks!

**Comment by xulongwu4** [comment]
I was running the tensorflow docker on Solus linux. The version of `docker` at the time I wrote the issue was 18.06.1. `nvidia-docker` was at version 2.0.3 (the latest release on github). The issue happened on both two laptops that I tried the tensorflow docker on. One laptop has an intel 7700HQ with NVIDIA GTX 1060. The other laptop has an intel 8700H with NVIDIA GTX 1060 MAX-Q.

Is there any other information that I can provide?

**Comment by angersson** [comment]
That's odd. @tfboyd, you had checked that these images were working, right?

**Comment by angersson** [comment]
I ran the provided command with no issues. If the latest "latest" images still don't work, you may have an outdated version of the NVidia drivers (from `nvidia-smi`:

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.78       Driver Version: 410.78       CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
```

Older versions of the drivers don't support CUDA 10.

**Comment by xulongwu4** [comment]
This is weird. I still see the same problem. The following is the output of `nvidia-smi` on my laptop:

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 415.27       Driver Version: 415.27       CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 106...  On   | 00000000:01:00.0 Off |                  N/A |
| N/A   47C    P3    18W /  N/A |    243MiB /  6078MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0       925      G   /usr/lib64/xorg-server/Xorg                  142MiB |
|    0      1335      G   budgie-wm                                     86MiB |
|    0      1572      G   ...quest-channel-token=1786131106816168071     8MiB |
|    0      1691      G   ...-token=772756EC82DA66D9E1D850ED9DAEFD9B     4MiB |
+-----------------------------------------------------------------------------+
```

**Comment by xulongwu4** [comment]
I tried the latest "latest" -- namely the "nightly-gpu" version. I still see the same problem -- this time it is complaining about `libcublas.so.10.0` though.

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory
```
