### ISSUE TITLE
TFLite App error with SSD_MobileNet V2 Quantized 300*300 CoCo

### ISSUE THREAD

**Issue by sachin-ranka** [tensorflow/tensorflow#24663]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Nexus 6 and Moto G5sPlus
- TensorFlow installed from (source or binary): binary (pip)
- TensorFlow version (use command below): 1.12.0
- Python version: 3.5.5 (anaconda)
- Bazel version (if compiling from source):N/A
- GCC/Compiler version (if compiling from source):N/A
- CUDA/cuDNN version:N/A
- GPU model and memory: 8GB Tesla K80 on VM

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**
TFLite app crashes with log shown below.

**Describe the expected behavior**
Runs and detects objects smoothly
**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
[Tensorflow lite convertion tutorial](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_on_mobile_tensorflowlite.md) and used android source code from [Tensorflow/lite/Java/Demo](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/java/demo), Changed classifier to ```ImageClassifierQuantizedMobileNet``` for Quantized model and ```ImageClassifierFloatMobileNet``` for Float model.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
Used steps as on [Tensorflow lite convertion tutorial](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_on_mobile_tensorflowlite.md), I generated both UNIT8 and FLOAT type tflite models. I've used [SSD_MobileNet_V2_COCO](https://github.com/tensorflow/models/blob/master/research/object_detection/samples/configs/ssd_mobilenet_v2_quantized_300x300_coco.config) to train my dataset for object detection.
Following are the errors I get while trying to build for android:

**Using Quantized (UINT8)**

```
01-02 14:41:39.721 5697-5697/? E/SchedPolicy: open of /dev/cpuctl/bg_non_interactive/tasks failed: No such file or directory
01-02 14:41:39.727 5697-5697/? I/zygote: Late-enabling -Xcheck:jni
01-02 14:41:39.789 5697-5707/? E/zygote: Failed sending reply to debugger: Broken pipe
01-02 14:41:39.790 5697-5707/? I/zygote: Debugger is no longer active
01-02 14:41:40.050 5697-5719/? D/TfLiteCameraDemo: Created a Tensorflow Lite Image Classifier.
01-02 14:41:40.069 5697-5725/? D/OpenGLRenderer: HWUI GL Pipeline
01-02 14:41:40.163 5697-5725/? I/Adreno: QUALCOMM build                   : 908a5ce, I77d3059488
    Build Date                       : 06/07/18
    OpenGL ES Shader Compiler Version: EV031.22.00.01_06
    Local Branch                     : 
    Remote Branch                    : refs/tags/AU_LINUX_ANDROID_LA.UM.6.5.R1.08.01.00.312.086
    Remote Branch                    : NONE
    Reconstruct Branch               : NOTHING
01-02 14:41:40.163 5697-5725/? D/vndksupport: Loading /vendor/lib/hw/gralloc.msm8953.so from current namespace instead of sphal namespace.
01-02 14:41:40.168 5697-5725/? I/Adreno: PFP: 0x005ff087, ME: 0x005ff063
01-02 14:41:40.173 5697-5725/? I/zygote: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
01-02 14:41:40.174 5697-5725/? I/OpenGLRenderer: Initialized EGL, version 1.4
01-02 14:41:40.174 5697-5725/? D/OpenGLRenderer: Swap behavior 2
01-02 14:41:40.258 5697-5705/? I/zygote: Do partial code cache collection, code=28KB, data=30KB
    After code cache collection, code=28KB, data=30KB
    Increasing code cache capacity to 128KB
01-02 14:41:40.395 5697-5705/? I/zygote: Do partial code cache collection, code=62KB, data=58KB
01-02 14:41:40.396 5697-5705/? I/zygote: After code cache collection, code=62KB, data=58KB
    Increasing code cache capacity to 256KB
01-02 14:41:40.523 5697-5697/? I/CameraManagerGlobal: Connecting to camera service
01-02 14:41:40.682 5697-5725/? D/vndksupport: Loading /vendor/lib/hw/android.hardware.graphics.mapper@2.0-impl.so from current namespace instead of sphal namespace.
01-02 14:41:40.683 5697-5725/? D/vndksupport: Loading /vendor/lib/hw/gralloc.msm8953.so from current namespace instead of sphal namespace.
01-02 14:41:40.746 5697-5724/? D/TfLiteCameraDemo: Timecost to put values into ByteBuffer: 67
01-02 14:41:41.101 5697-5724/android.example.com.tflitecamerademo E/AndroidRuntime: FATAL EXCEPTION: CameraBackground
    Process: android.example.com.tflitecamerademo, PID: 5697
    java.lang.IllegalArgumentException: Cannot convert between a TensorFlowLite tensor with type FLOAT32 and a Java object of type [[B (which is compatible with the TensorFlowLite type UINT8).
        at org.tensorflow.lite.Tensor.throwExceptionIfTypeIsIncompatible(Tensor.java:261)
        at org.tensorflow.lite.Tensor.copyTo(Tensor.java:141)
        at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:161)
        at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:275)
        at org.tensorflow.lite.Interpreter.run(Interpreter.java:249)
        at com.example.android.tflitecamerademo.ImageClassifierQuantizedMobileNet.runInference(ImageClassifierQuantizedMobileNet.java:95)
        at com.example.android.tflitecamerademo.ImageClassifier.classifyFrame(ImageClassifier.java:126)
        at com.example.android.tflitecamerademo.Camera2BasicFragment.classifyFrame(Camera2BasicFragment.java:815)
        at com.example.android.tflitecamerademo.Camera2BasicFragment.-wrap0(Unknown Source:0)
        at com.example.android.tflitecamerademo.Camera2BasicFragment$4.run(Camera2BasicFragment.java:710)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
01-02 14:41:41.806 5697-5697/? I/Choreographer: Skipped 73 frames!  The application may be doing too much work on its main thread.
01-02 14:41:41.809 5697-5707/? I/zygote: Ignoring second debugger -- accepting and dropping
```

**Using Float type**
```
01-02 14:39:44.097 5364-5364/? E/SchedPolicy: open of /dev/cpuctl/bg_non_interactive/tasks failed: No such file or directory
01-02 14:39:44.101 5364-5364/? I/zygote: Late-enabling -Xcheck:jni
01-02 14:39:44.164 5364-5371/? E/zygote: Failed sending reply to debugger: Broken pipe
01-02 14:39:44.165 5364-5371/? I/zygote: Debugger is no longer active
01-02 14:39:44.408 5364-5387/? D/TfLiteCameraDemo: Created a Tensorflow Lite Image Classifier.
01-02 14:39:44.427 5364-5395/? D/OpenGLRenderer: HWUI GL Pipeline
01-02 14:39:44.520 5364-5395/? I/Adreno: QUALCOMM build                   : 908a5ce, I77d3059488
    Build Date                       : 06/07/18
    OpenGL ES Shader Compiler Version: EV031.22.00.01_06
    Local Branch                     : 
    Remote Branch                    : refs/tags/AU_LINUX_ANDROID_LA.UM.6.5.R1.08.01.00.312.086
    Remote Branch                    : NONE
    Reconstruct Branch               : NOTHING
01-02 14:39:44.521 5364-5395/? D/vndksupport: Loading /vendor/lib/hw/gralloc.msm8953.so from current namespace instead of sphal namespace.
01-02 14:39:44.526 5364-5395/? I/Adreno: PFP: 0x005ff087, ME: 0x005ff063
01-02 14:39:44.532 5364-5395/? I/zygote: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
01-02 14:39:44.532 5364-5395/? I/OpenGLRenderer: Initialized EGL, version 1.4
01-02 14:39:44.533 5364-5395/? D/OpenGLRenderer: Swap behavior 2
01-02 14:39:44.615 5364-5369/? I/zygote: Do partial code cache collection, code=28KB, data=30KB
01-02 14:39:44.616 5364-5369/? I/zygote: After code cache collection, code=28KB, data=30KB
    Increasing code cache capacity to 128KB
01-02 14:39:44.752 5364-5369/? I/zygote: Do partial code cache collection, code=62KB, data=58KB
    After code cache collection, code=62KB, data=58KB
    Increasing code cache capacity to 256KB
01-02 14:39:44.865 5364-5364/? I/CameraManagerGlobal: Connecting to camera service
01-02 14:39:44.988 5364-5395/? D/vndksupport: Loading /vendor/lib/hw/android.hardware.graphics.mapper@2.0-impl.so from current namespace instead of sphal namespace.
01-02 14:39:44.989 5364-5395/? D/vndksupport: Loading /vendor/lib/hw/gralloc.msm8953.so from current namespace instead of sphal namespace.
01-02 14:39:45.072 5364-5392/? D/TfLiteCameraDemo: Timecost to put values into ByteBuffer: 87
01-02 14:39:45.900 5364-5392/android.example.com.tflitecamerademo E/AndroidRuntime: FATAL EXCEPTION: CameraBackground
    Process: android.example.com.tflitecamerademo, PID: 5364
    java.lang.IllegalArgumentException: Cannot copy between a TensorFlowLite tensor with shape [1, 10, 4] and a Java object with shape [1, 1].
        at org.tensorflow.lite.Tensor.throwExceptionIfTypeIsIncompatible(Tensor.java:270)
        at org.tensorflow.lite.Tensor.copyTo(Tensor.java:141)
        at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:161)
        at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:275)
        at org.tensorflow.lite.Interpreter.run(Interpreter.java:249)
        at com.example.android.tflitecamerademo.ImageClassifierFloatMobileNet.runInference(ImageClassifierFloatMobileNet.java:92)
        at com.example.android.tflitecamerademo.ImageClassifier.classifyFrame(ImageClassifier.java:126)
        at com.example.android.tflitecamerademo.Camera2BasicFragment.classifyFrame(Camera2BasicFragment.java:815)
        at com.example.android.tflitecamerademo.Camera2BasicFragment.-wrap0(Unknown Source:0)
        at com.example.android.tflitecamerademo.Camera2BasicFragment$4.run(Camera2BasicFragment.java:710)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
01-02 14:39:45.931 5364-5364/android.example.com.tflitecamerademo I/Choreographer: Skipped 60 frames!  The application may be doing too much work on its main thread.
```

Kindly let me know where I am wrong.

**Comment by msymp** [comment]
Hello @gargn , can you please let us know if the user's query has been reviewed and being addressed?

**Comment by gargn** [comment]
@msymp  It has not.

**Comment by freedomtan** [comment]
@sachin-ranka you are not supposed to run object detection models with image classifier code!

**Comment by sachin-ranka** [comment]
@freedomtan The sample app code link: [https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/lite/examples/android/BUILD](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/lite/examples/android/BUILD) file doesn't exists, only python code exists in that folder. ( as per the article provided) I've generated TFLite files using the same steps. Pls help me out here...

**Comment by freedomtan** [comment]
TFLite related code moved from tensorflow/contrib/lite into tensorflow/lite, use https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/examples/android/BUILD instead

**Comment by sachin-ranka** [comment]
I am getting this error while trying to follow the article (as suggested above) 
```
$bazel run -c opt tensorflow/lite/toco:toco -- \
--input_file=$OUTPUT_DIR/tflite_graph.pb --output_file=$OUTPUT_DIR/detect_Quant.tflite \
--input_shapes=1,300,300,3 --input_arrays=normalized_input_image_tensor \
--output_arrays='TFLite_Detection_PostProcess','TFLite_Detection_PostProcess:1','TFLite_Detection_PostProcess:2','TFLite_Detection_PostProcess:3' \
 --inference_type=QUANTIZED_UINT8 --mean_values=128 \
 --std_values=128 --change_concat_input_ranges=false --allow_custom_ops


2019-01-14 09:02:14.634927: F tensorflow/lite/toco/tooling_util.cc:1702] Array FeatureExtractor/MobilenetV2/Conv/Relu6, which is an input to the DepthwiseConv operator producing the output array FeatureExtractor/MobilenetV2/expanded_conv/depthwise/Relu6, is lacking min/max data, which is necessary for quantization. If accuracy matters, either target a non-quantized output format, or run quantized training with your model from a floating point checkpoint to change the input graph to contain min/max information. If you don't care about accuracy, you can pass --default_ranges_min= and --default_ranges_max= for easy experimentation.
Aborted (core dumped)
```

Not sure what to do further, pls help me out...

**Comment by zaichang** [comment]
@sachin-ranka As the error message mentions, try adding the `--default_ranges_min=` and `--default_ranges_max=` flags to the toco command. Say `0` and `6`.

In any case this isn't an issue with the tensorflow sample code but your modification of it, so it is out of scope for github. Try www.stackoverflow.com instead.

**Comment by jdduke** [comment]
Closing per latest advice.
