### ISSUE TITLE
Cannot reproduce tf.contrib.autograph's RNN Colorbot example

### ISSUE THREAD

**Issue by ktaebum** [tensorflow/tensorflow#24701]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No (Used script provided in Tensorflow)
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colab
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): r1.12
- Python version: 3.6

**Describe the current behavior**

I tried to test some autograph's features with RNN.
At first, I tried tensorflow's official [example](https://colab.research.google.com/github/tensorflow/tensorflow/blob/master/tensorflow/contrib/autograph/examples/notebooks/rnn_keras_estimator.ipynb) with Python 3.6 Colab Notebook with tensorflow version as r1.12.0.
However, it emits type error as
```
TypeError                                 Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py in _apply_op_helper(self, op_type_name, name, **keywords)
    454                 preferred_dtype=default_dtype,
--> 455                 as_ref=input_arg.is_ref)
    456             if input_arg.number_attr and len(

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py in internal_convert_n_to_tensor(values, dtype, name, as_ref, preferred_dtype, ctx)
   1210             preferred_dtype=preferred_dtype,
-> 1211             ctx=ctx))
   1212   return ret

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py in internal_convert_to_tensor(value, dtype, name, as_ref, preferred_dtype, ctx)
   1145     if ret is None:
-> 1146       ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
   1147 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/constant_op.py in _constant_tensor_conversion_function(v, dtype, name, as_ref)
    228   _ = as_ref
--> 229   return constant(v, dtype=dtype, name=name)
    230 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/constant_op.py in constant(value, dtype, shape, name, verify_shape)
    207       tensor_util.make_tensor_proto(
--> 208           value, dtype=dtype, shape=shape, verify_shape=verify_shape))
    209   dtype_value = attr_value_pb2.AttrValue(type=tensor_value.tensor.dtype)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/tensor_util.py in make_tensor_proto(values, dtype, shape, verify_shape)
    441     else:
--> 442       _AssertCompatible(values, dtype)
    443       nparray = np.array(values, dtype=np_dt)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/tensor_util.py in _AssertCompatible(values, dtype)
    352       raise TypeError("Expected %s, got %s of type '%s' instead." %
--> 353                       (dtype.name, repr(mismatch), type(mismatch).__name__))
    354 

TypeError: Expected int64, got range(0, 64) of type 'range' instead.

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
<ipython-input-8-e180019d193a> in <module>()
     14 regressor.train(
     15     input_fn=lambda: input_fn(data_dir, train_url, params),
---> 16     steps=100)
     17 eval_results = regressor.evaluate(
     18     input_fn=lambda: input_fn(data_dir, test_url, params, training=False),

/usr/local/lib/python3.6/dist-packages/tensorflow/python/estimator/estimator.py in train(self, input_fn, hooks, steps, max_steps, saving_listeners)
    352 
    353       saving_listeners = _check_listeners_type(saving_listeners)
--> 354       loss = self._train_model(input_fn, hooks, saving_listeners)
    355       logging.info('Loss for final step: %s.', loss)
    356       return self

/usr/local/lib/python3.6/dist-packages/tensorflow/python/estimator/estimator.py in _train_model(self, input_fn, hooks, saving_listeners)
   1205       return self._train_model_distributed(input_fn, hooks, saving_listeners)
   1206     else:
-> 1207       return self._train_model_default(input_fn, hooks, saving_listeners)
   1208 
   1209   def _train_model_default(self, input_fn, hooks, saving_listeners):

/usr/local/lib/python3.6/dist-packages/tensorflow/python/estimator/estimator.py in _train_model_default(self, input_fn, hooks, saving_listeners)
   1235       worker_hooks.extend(input_hooks)
   1236       estimator_spec = self._call_model_fn(
-> 1237           features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
   1238       global_step_tensor = training_util.get_global_step(g)
   1239       return self._train_with_estimator_spec(estimator_spec, worker_hooks,

/usr/local/lib/python3.6/dist-packages/tensorflow/python/estimator/estimator.py in _call_model_fn(self, features, labels, mode, config)
   1193 
   1194     logging.info('Calling model_fn.')
-> 1195     model_fn_results = self._model_fn(features=features, **kwargs)
   1196     logging.info('Done calling model_fn.')
   1197 

<ipython-input-6-eed6cb165519> in model_fn(features, labels, mode, params)
     10 
     11   if mode == tf.estimator.ModeKeys.TRAIN:
---> 12     predictions = colorbot(inputs, training=True)
     13     loss = loss_fn(labels, predictions)
     14 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py in __call__(self, inputs, *args, **kwargs)
    755       if not in_deferred_mode:
    756         self._in_call = True
--> 757         outputs = self.call(inputs, *args, **kwargs)
    758         self._in_call = False
    759         if outputs is None:

/tmp/tmpwq7vt5r_.py in call(self, inputs, training)
     83       seq = self._rnn_layer(seq, self.upper_cell, batch_size, training)
     84       indices = length - 1, ag__.range_(batch_size)
---> 85       indices = tf.stack(indices, 1)
     86       sequence_ends = tf.gather_nd(seq, indices)
     87       return self.relu_layer(sequence_ends)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/array_ops.py in stack(values, axis, name)
    872                                                       expanded_num_dims))
    873 
--> 874   return gen_array_ops.pack(values, axis=axis, name=name)
    875 
    876 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_array_ops.py in pack(values, axis, name)
   4873     axis = _execute.make_int(axis, "axis")
   4874     _, _, _op = _op_def_lib._apply_op_helper(
-> 4875         "Pack", values=values, axis=axis, name=name)
   4876     _result = _op.outputs[:]
   4877     _inputs_flat = _op.inputs

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py in _apply_op_helper(self, op_type_name, name, **keywords)
    481                                 (prefix, dtype.name))
    482               else:
--> 483                 raise TypeError("%s that don't all match." % prefix)
    484             else:
    485               raise TypeError("%s that are invalid." % prefix)

TypeError: Tensors in list passed to 'values' of 'Pack' Op have types [int64, <NOT CONVERTIBLE TO TENSOR>] that don't all match.
```

Moreover, if I try to run the original colab notebook example, which run tensorflow 1.13 dev in python2.7, it raises graph construction error as

```
GraphConstructionErrorTraceback (most recent call last)
<ipython-input-15-e180019d193a> in <module>()
     14 regressor.train(
     15     input_fn=lambda: input_fn(data_dir, train_url, params),
---> 16     steps=100)
     17 eval_results = regressor.evaluate(
     18     input_fn=lambda: input_fn(data_dir, test_url, params, training=False),

/usr/local/lib/python2.7/dist-packages/tensorflow_estimator/python/estimator/estimator.pyc in train(self, input_fn, hooks, steps, max_steps, saving_listeners)
    356 
    357       saving_listeners = _check_listeners_type(saving_listeners)
--> 358       loss = self._train_model(input_fn, hooks, saving_listeners)
    359       logging.info('Loss for final step: %s.', loss)
    360       return self

/usr/local/lib/python2.7/dist-packages/tensorflow_estimator/python/estimator/estimator.pyc in _train_model(self, input_fn, hooks, saving_listeners)
   1122       return self._train_model_distributed(input_fn, hooks, saving_listeners)
   1123     else:
-> 1124       return self._train_model_default(input_fn, hooks, saving_listeners)
   1125 
   1126   def _train_model_default(self, input_fn, hooks, saving_listeners):

/usr/local/lib/python2.7/dist-packages/tensorflow_estimator/python/estimator/estimator.pyc in _train_model_default(self, input_fn, hooks, saving_listeners)
   1152       worker_hooks.extend(input_hooks)
   1153       estimator_spec = self._call_model_fn(
-> 1154           features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
   1155       global_step_tensor = training_util.get_global_step(g)
   1156       return self._train_with_estimator_spec(estimator_spec, worker_hooks,

/usr/local/lib/python2.7/dist-packages/tensorflow_estimator/python/estimator/estimator.pyc in _call_model_fn(self, features, labels, mode, config)
   1110 
   1111     logging.info('Calling model_fn.')
-> 1112     model_fn_results = self._model_fn(features=features, **kwargs)
   1113     logging.info('Done calling model_fn.')
   1114 

<ipython-input-13-eed6cb165519> in model_fn(features, labels, mode, params)
     10 
     11   if mode == tf.estimator.ModeKeys.TRAIN:
---> 12     predictions = colorbot(inputs, training=True)
     13     loss = loss_fn(labels, predictions)
     14 

/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/engine/base_layer.pyc in __call__(self, inputs, *args, **kwargs)
    554           if not self.dynamic:
    555             try:
--> 556               outputs = self.call(inputs, *args, **kwargs)
    557             except TypeError as e:
    558               messages = ['`tf.Tensor` as a Python `bool` is not allowed',

/tmp/tmpxLZSMS.py in call(self, inputs, training)
    101         return ag__.converted_call('relu_layer', self, autograph.ConversionOptions(recursive=False, verbose=0, strip_decorators=(defun, autograph.convert, autograph.do_not_convert, autograph.converted_call), force_conversion=False, optional_features=(), internal_convert_user_code=True), sequence_ends)
    102     except:
--> 103       ag__.rewrite_graph_construction_error(ag_source_map__)
    104 
    105 

/usr/local/lib/python2.7/dist-packages/tensorflow/python/autograph/core/errors.pyc in rewrite_graph_construction_error(source_map)
    135     raise original_error
    136   else:
--> 137     raise new_error
    138   finally:
    139     # Addresses warning https://docs.python.org/2/library/sys.html#sys.exc_info.

GraphConstructionError: Traceback (most recent call last):
  File "<ipython-input-12-87e5f229a162>", line 59, in call
    seq = self._rnn_layer(seq, self.lower_cell, batch_size, training)
  File "<ipython-input-12-87e5f229a162>", line 27, in _rnn_layer
    cell_output, (state, output) = cell.call(ch, (state, output))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/autograph/impl/api.py", line 200, in converted_call
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/rnn/python/ops/lstm_ops.py", line 426, in call
    wci = wcf = wco = array_ops.zeros([self._num_units], dtype=self.dtype)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 1793, in zeros
    dtype = dtypes.as_dtype(dtype).base_dtype
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/dtypes.py", line 719, in as_dtype
    raise TypeError("Cannot convert value %r to a TensorFlow DType." % type_value)

Cannot convert value None to a TensorFlow DType.
```

It says that it cannot convert value **None** to a Tensorflow DType, but I cannot find any None value if I print values related to erroneous call stack.

**Describe the expected behavior**

In the original notebook example, it prints out evaluation loss without error

**Code to reproduce the issue**
[link](https://colab.research.google.com/drive/1fqr0wiNctLm0M07xss-Ra_iGC7DCojjs) to my python3 colab notebook

**Comment by ktaebum** [comment]
I found that for python 3.6 environment, autograph cannot convert range(batch_size) in 
call function of RnnColorbot.

It runs without error if change range(batch_size) into tf.Tensor via 
```
tf.convert_to_tensor(range(batch_size), tf.uint64)
```

However, still raise error in python 2.7, the original tutorial environment

**Comment by mdanatg** [comment]
Thank you for bringing this to our attention! I believe we fixed the problems in the master version - if you have a chance to give it another try, please reopen this thread if you encounter any more issues.
