### ISSUE TITLE
importing tf-nightly-gpu error

### ISSUE THREAD

**Issue by MatthiasRathbun** [tensorflow/tensorflow#24839]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): Wheel
- TensorFlow version: tf-nightly-gpu 1.13.0.dev20181225
- Python version: 3.6.8
- Installed using virtualenv? pip? conda?: pip on a clean conda env
- CUDA/cuDNN version: 10
- GPU model and memory: rtx 2070

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**
Created a new conda env, installed python 3.6.8 on it. Pip installed the windows wheel after clearing cache. Went into python in the console, imported tensorflow and got the following error.

**Any other info / logs**
Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 18:50:55) [MSC v.1915 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\tf\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\ProgramData\Anaconda3\envs\tf\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\ProgramData\Anaconda3\envs\tf\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\ProgramData\Anaconda3\envs\tf\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\ProgramData\Anaconda3\envs\tf\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\envs\tf\lib\site-packages\tensorflow\__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\ProgramData\Anaconda3\envs\tf\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\ProgramData\Anaconda3\envs\tf\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\tf\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\ProgramData\Anaconda3\envs\tf\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\ProgramData\Anaconda3\envs\tf\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\ProgramData\Anaconda3\envs\tf\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\ProgramData\Anaconda3\envs\tf\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by mhurliman** [comment]
Same here. +1

**Comment by rootkitchao** [comment]
I don't know if the nightly version of Tensorflow 1.13 supports CUDA10.0.However, the stable version of Tensorflow 1.13 installed via PIP does not support CUDA10.0.

**Comment by prachm** [comment]
Same error faced with same config and CUDA 10

**Comment by martinwicke** [comment]
We're still working on CUDA10 for some platforms. You can probably wait it out, shouldn't take much longer. 

@av8ramit FYI.

**Comment by av8ramit** [comment]
We are still working on adding CUDA 10 for Windows and the Ubuntu Python3.7 build for tf-nightly-gpu. Sorry for the delay and thank you for your patience. The official 1.13 will support CUDA 10.

**Comment by av8ramit** [comment]
Unfortunately, I believe until CUDA 10 is supported you'll see this import error with CUDA 10 out of the box

**Comment by MatthiasRathbun** [comment]
@av8ramit is there a tentative timeframe for the release of 1.13?

**Comment by prachm** [comment]
@martinwicke @av8ramit Any updates?

**Comment by av8ramit** [comment]
The rc0 will be out probably next week, and the official release 3 weeks after that.

**Comment by MatthiasRathbun** [comment]
@av8ramit the rc0 will support cuda 10, correct?

**Comment by av8ramit** [comment]
Yes we are adding CUDA 10 support to 1.13 rc0.
