### ISSUE TITLE
[Error, Quantization] tf.nn.quantized_conv2d with filter type tf.qint8

### ISSUE THREAD

**Issue by Vooblin** [tensorflow/tensorflow#24855]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 1.12.0, b'v1.12.0-5132-g02b966e'
- Python version: 3.5.2
- Bazel version (if compiling from source): 0.19.2
- GCC/Compiler version (if compiling from source): c++ (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
- CUDA/cuDNN version: No
- GPU model and memory: No

**Describe the current behavior**
Error with using `tf.nn.quantized_conv2d()`. If both input and filter have type `tf.quint8` then everything is fine. But if filter have type `tf.qint8` then error occurs. Tensorflow was built with `--config=mkl`. There is kernel for filter with type `tf.qint8`:
```
Registered devices: [CPU]
Registered kernels:
  device='CPU'; Tinput in [DT_QUINT8]; Tfilter in [DT_QINT8]; out_type in [DT_QINT32]
  device='CPU'; Tinput in [DT_QUINT8]; Tfilter in [DT_QUINT8]; out_type in [DT_QINT32]

         [[QuantizedConv2D]]
```

**Code to reproduce the issue**
```
import tensorflow as tf

A = tf.random_normal([100, 30, 30, 1])
min_A = tf.reduce_min(A)
max_A = tf.reduce_max(A)

W = tf.random_normal([3, 3, 1, 4])
min_W = tf.reduce_min(W)
max_W = tf.reduce_max(W)

qA = tf.quantize(A, min_A, max_A, tf.quint8, mode='MIN_FIRST')
qW = tf.quantize(W, min_W, max_W, tf.qint8, mode='MIN_FIRST')
qAW = tf.nn.quantized_conv2d(qA[0], qW[0], qA[1], qA[2], qW[1], qW[2], [1, 1, 1, 1], 'SAME')
AW = tf.dequantize(*qAW, mode='MIN_FIRST')

tf.Session().run(AW)
```

**Error log**
```
Traceback (most recent call last):
  File "/workspace/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/workspace/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/workspace/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InternalError: Missing 0-th output from {{node QuantizedConv2D}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 16, in <module>
    tf.Session().run(AW)
  File "/workspace/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/workspace/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/workspace/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/workspace/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Missing 0-th output from node QuantizedConv2D (defined at test.py:13)

Errors may have originated from an input operation.
Input Source operations connected to node QuantizedConv2D:
 Const_3 (defined at test.py:9)
 random_normal_1/stddev (defined at test.py:7)
 Const_1 (defined at test.py:5)
 random_normal/stddev (defined at test.py:3)
 Const (defined at test.py:4)
 Const_2 (defined at test.py:8)
```

**Comment by shoubhik** [comment]
I ran the stock code (installed from conda) on mac with tensorflow 1.12 and got the following error after running the above code
```import tensorflow as tf

A = tf.random_normal([100, 30, 30, 1])
min_A = tf.reduce_min(A)
max_A = tf.reduce_max(A)

W = tf.random_normal([3, 3, 1, 4])
min_W = tf.reduce_min(W)
max_W = tf.reduce_max(W)

qA = tf.quantize(A, min_A, max_A, tf.quint8, mode='MIN_FIRST')
qW = tf.quantize(W, min_W, max_W, tf.qint8, mode='MIN_FIRST')
qAW = tf.nn.quantized_conv2d(qA[0], qW[0], qA[1], qA[2], qW[1], qW[2], [1, 1, 1, 1], 'SAME')
AW = tf.dequantize(*qAW, mode='MIN_FIRST')

tf.Session().run(AW)
```

This is the **error log** I am getting, is this the expectation? Do I need to compile tensorflow with `mkl` to test the quantized ops?

```InvalidArgumentError: No OpKernel was registered to support Op 'QuantizedConv2D' with these attrs.  Registered devices: [CPU], Registered kernels:
  device='CPU'; Tinput in [DT_QUINT8]; Tfilter in [DT_QUINT8]; out_type in [DT_QINT32]

	 [[node QuantizedConv2D (defined at <ipython-input-1-64455ed8b073>:13)  = QuantizedConv2D[Tfilter=DT_QINT8, Tinput=DT_QUINT8, dilations=[1, 1, 1, 1], out_type=DT_QINT32, padding="SAME", strides=[1, 1, 1, 1]](QuantizeV2, QuantizeV2_1, QuantizeV2:1, QuantizeV2:2, QuantizeV2_1:1, QuantizeV2_1:2)]]

Caused by op u'QuantizedConv2D', defined at:
  File "/Users/shoubhik/anaconda/anaconda3/envs/tensorflow-1.12_p27/bin/ipython", line 11, in <module>
    sys.exit(start_ipython())
  File "/Users/shoubhik/anaconda/anaconda3/envs/tensorflow-1.12_p27/lib/python2.7/site-packages/IPython/__init__.py", line 119, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/Users/shoubhik/anaconda/anaconda3/envs/tensorflow-1.12_p27/lib/python2.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/Users/shoubhik/anaconda/anaconda3/envs/tensorflow-1.12_p27/lib/python2.7/site-packages/IPython/terminal/ipapp.py", line 355, in start
    self.shell.mainloop()
  File "/Users/shoubhik/anaconda/anaconda3/envs/tensorflow-1.12_p27/lib/python2.7/site-packages/IPython/terminal/interactiveshell.py", line 495, in mainloop
    self.interact()
  File "/Users/shoubhik/anaconda/anaconda3/envs/tensorflow-1.12_p27/lib/python2.7/site-packages/IPython/terminal/interactiveshell.py", line 486, in interact
    self.run_cell(code, store_history=True)
  File "/Users/shoubhik/anaconda/anaconda3/envs/tensorflow-1.12_p27/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2714, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/Users/shoubhik/anaconda/anaconda3/envs/tensorflow-1.12_p27/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2818, in run_ast_nodes
    if self.run_code(code, result):
  File "/Users/shoubhik/anaconda/anaconda3/envs/tensorflow-1.12_p27/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2878, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-1-64455ed8b073>", line 13, in <module>
    qAW = tf.nn.quantized_conv2d(qA[0], qW[0], qA[1], qA[2], qW[1], qW[2], [1, 1, 1, 1], 'SAME')
  File "/Users/shoubhik/anaconda/anaconda3/envs/tensorflow-1.12_p27/lib/python2.7/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 6329, in quantized_conv2d
    dilations=dilations, name=name)
  File "/Users/shoubhik/anaconda/anaconda3/envs/tensorflow-1.12_p27/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/Users/shoubhik/anaconda/anaconda3/envs/tensorflow-1.12_p27/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/Users/shoubhik/anaconda/anaconda3/envs/tensorflow-1.12_p27/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/Users/shoubhik/anaconda/anaconda3/envs/tensorflow-1.12_p27/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): No OpKernel was registered to support Op 'QuantizedConv2D' with these attrs.  Registered devices: [CPU], Registered kernels:
  device='CPU'; Tinput in [DT_QUINT8]; Tfilter in [DT_QUINT8]; out_type in [DT_QINT32]

	 [[node QuantizedConv2D (defined at <ipython-input-1-64455ed8b073>:13)  = QuantizedConv2D[Tfilter=DT_QINT8, Tinput=DT_QUINT8, dilations=[1, 1, 1, 1], out_type=DT_QINT32, padding="SAME", strides=[1, 1, 1, 1]](QuantizeV2, QuantizeV2_1, QuantizeV2:1, QuantizeV2:2, QuantizeV2_1:1, QuantizeV2_1:2)]] 
```

**Comment by shoubhik** [comment]
Could it be because of QuantizedConv2D being registered like this

```
// Right now we only support taking two eight bit inputs, and returning the
// results as signed 32-bit integers.
REGISTER_KERNEL_BUILDER(
    Name("QuantizedConv2D")
        .Device(DEVICE_CPU)
        .TypeConstraint<quint8>("Tinput")
        .TypeConstraint<quint8>("Tfilter")
        .TypeConstraint<qint32>("out_type"),
    QuantizedConv2DOp<quint8, quint8, qint32, Im2ColConvFunctor>);

```
[here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/quantized_conv_ops.cc#L587-L595)

**Comment by Vooblin** [comment]
@shoubhik There is another kernel for `quantized_conv2d()` with `mkl` in `tensorflow/core/kernels/mkl_conv_ops.cc`:
```
// INT8 kernel registration
// Register NoOp kernel for QunatizedConv2D for qint8 filter
REGISTER_KERNEL_BUILDER(Name("QuantizedConv2D")
                            .Device(DEVICE_CPU)
                            .TypeConstraint<quint8>("Tinput")
                            .TypeConstraint<qint8>("Tfilter")
                            .TypeConstraint<qint32>("out_type"),
                        NoOp);
--//--
// Register a templatized implementation of MklQuntizedConv2D.
REGISTER_KERNEL_BUILDER(
    Name("_MklQuantizedConv2D")
        .Device(DEVICE_CPU)
        .TypeConstraint<quint8>("Tinput")
        .TypeConstraint<qint8>("Tfilter")
        .TypeConstraint<qint32>("out_type")
        .Label(mkl_op_registry::kMklQuantizedOpLabel),
    MklQuantizedConv2DOp<CPUDevice, float, qint32, qint32, false>);
```

**Comment by mdfaijul** [comment]
@Vooblin Thanks for your error reporting. We appreciate your time trying out Intel CPU quantization works. However, the quantization work is still in progress. You could build with adding `--copt="-DINTEL_MKL_QUANTIZED"` to bazel build option in order to get it work.

You are getting the error [`tensorflow.python.framework.errors_impl.InternalError: Missing 0-th output from node QuantizedConv2D (defined at test.py:13)`], because of `NoOp` kernel registration with the operator. The computation graph needs to go through https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/graph/mkl_layout_pass.cc#L297-L319
to get the `NoOp` kernel replaced by `MklQuantizedConv2DOp`

**Comment by Vooblin** [comment]
@mdfaijul Thank you very much for your response! It helped me fix this error.
