### ISSUE TITLE
"Transient arrays with strings are not supported yet" when converting GraphDef to tflite file

### ISSUE THREAD

**Issue by Iamanorange** [tensorflow/tensorflow#24892]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.12
- Python version: 3.5
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: 9.0/7.4
- GPU model and memory: GTX1080Ti 11GB

**Describe the current behavior**
No file was created.

**Describe the expected behavior**
A .tflite file is converted.

**Code to reproduce the issue**
The model cann't be provided.

**Other info / logs**
```
 CUDA_VISIBLE_DEVICES="2" tflite_convert \
  --output_file=frozen.tflite \
  --graph_def_file=model.pb \
  --input_arrays=input_image \
  --output_arrays=train_net/recon_image
2019-01-14 17:09:08.298351: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-01-14 17:09:08.549870: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.6325
pciBusID: 0000:82:00.0
totalMemory: 10.92GiB freeMemory: 10.76GiB
2019-01-14 17:09:08.549910: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2019-01-14 17:09:08.874792: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-01-14 17:09:08.874835: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
2019-01-14 17:09:08.874846: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
2019-01-14 17:09:08.875110: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10409 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:82:00.0, compute capability: 6.1)
Traceback (most recent call last):
  File "/usr/local/bin/tflite_convert", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 412, in main
    app.run(main=run_main, argv=sys.argv[:1])
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 408, in run_main
    _convert_model(tflite_flags)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 162, in _convert_model
    output_data = converter.convert()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/lite/python/lite.py", line 453, in convert
    **converter_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/lite/python/convert.py", line 342, in toco_convert_impl
    input_data.SerializeToString())
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/lite/python/convert.py", line 135, in toco_convert_protos
    (stdout, stderr))
RuntimeError: TOCO failed see console for info.
b'2019-01-14 17:09:13.458649: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA\n2019-01-14 17:09:13.697666: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: \nname: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.6325\npciBusID: 0000:82:00.0\ntotalMemory: 10.92GiB freeMemory: 10.56GiB\n2019-01-14 17:09:13.697710: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0\n2019-01-14 17:09:14.017280: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:\n2019-01-14 17:09:14.017321: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 \n2019-01-14 17:09:14.017329: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N \n2019-01-14 17:09:14.018988: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10209 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:82:00.0, compute capability: 6.1)\n2019-01-14 17:09:14.053557: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: Round\n2019-01-14 17:09:14.061350: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1080] Converting unsupported operation: ImageSummary\n2019-01-14 17:09:14.061401: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1127] Op node missing output type attribute: train_net/recon_image\n2019-01-14 17:09:14.067392: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 168 operators, 287 arrays (0 quantized)\n2019-01-14 17:09:14.070050: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 168 operators, 287 arrays (0 quantized)\n2019-01-14 17:09:14.105968: W tensorflow/contrib/lite/toco/graph_transformations/resolve_constant_random_uniform.cc:85] RandomUniform op outputting "build_towers/tower_0/train_net_inference_one_pass/train_net/random_uniform_1/RandomUniform" is truly random (using /dev/random system entropy). Therefore, cannot resolve as constant. Set "seed" or "seed2" attr non-zero to fix this\n2019-01-14 17:09:14.135825: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 1: 47 operators, 89 arrays (0 quantized)\n2019-01-14 17:09:14.136127: W tensorflow/contrib/lite/toco/graph_transformations/resolve_constant_random_uniform.cc:85] RandomUniform op outputting "build_towers/tower_0/train_net_inference_one_pass/train_net/random_uniform_1/RandomUniform" is truly random (using /dev/random system entropy). Therefore, cannot resolve as constant. Set "seed" or "seed2" attr non-zero to fix this\n2019-01-14 17:09:14.136547: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before dequantization graph transformations: 47 operators, 89 arrays (0 quantized)\n2019-01-14 17:09:14.137116: F tensorflow/contrib/lite/toco/tooling_util.cc:1674] Transient arrays with strings are not supported yet\nAborted (core dumped)\n'
None
```

What does "Transient arrays with strings are not supported yet" means? What should I modify in my model?

**Comment by NorwoodChris** [comment]
I have the same issue too. Any updates?

**Comment by Iamanorange** [comment]
I am testing on a more simplified graph and the error disappears.

But I still want to know what caused the error and what does the error message means.

**Comment by Iamanorange** [comment]
Remove most of OPs. Almost leaving only convolution and basic math/logic OPs.

That's why I don't know where the error was.

**Comment by gargn** [comment]
Strings aren't fully supported by TensorFlow Lite. I recommend testing your original model with the `tf-nightly` since it's some thing we are actively working on. If your original model doesn't work with the latest nightly, can you provide your model (or a minimal model that reproduces the error) along with the command you used to try and convert that model.

Reassigning to @haozha111 who is working on adding support for HashTables (which is related to general string support).

**Comment by haozha111** [comment]
I'm seeing that you are still using tensorflow/contrib/lite/toco, probably you can update your tf repo to the latest and test if that helps. Also, a minimum model to reproduce the issue might be useful to debug. Thanks.

**Comment by Iamanorange** [comment]
Thank you for helping.

I gave up using tflite due to lack of  OP supports.
