### ISSUE TITLE
Buggy exit/termination after a couple of iterations 

### ISSUE THREAD

**Issue by kavasseri** [tensorflow/tensorflow#2491]
Buggy execution after a couple of iterations. I am running python3.5 on a mac and the model quits. Not sure if this is a compatibility issue with the Py3.5 site packages. Help appreciated! Thanks 

Average loss at step  100000 :  4.67189269698
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kg/anaconda/lib/python3.5/site-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 699, in runfile
 execfile(filename, namespace)
File "/Users/kg/anaconda/lib/python3.5/site-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 88, in execfile
    exec(compile(open(filename, 'rb').read(), filename, 'exec'), namespace)
  File "/Users/kg/TF/trial_cnn.py", line 243, in <module>
    low_dim_embs = tsne.fit_transform(final_embeddings[:plot_only,:])
  File "/Users/kg/anaconda/lib/python3.5/site-packages/sklearn/manifold/t_sne.py", line 866, in fit_transform
    embedding = self._fit(X)
  File "/Users/kg/anaconda/lib/python3.5/site-packages/sklearn/manifold/t_sne.py", line 777, in _fit
    skip_num_points=skip_num_points)
  File "/Users/kg/anaconda/lib/python3.5/site-packages/sklearn/manifold/t_sne.py", line 832, in _tsne
    params, error, it = _gradient_descent(obj_func, params, **opt_args)
  File "/Users/kg/anaconda/lib/python3.5/site-packages/sklearn/manifold/t_sne.py", line 387, in _gradient_descent
    grad_norm = linalg.norm(grad)
  File "/Users/kg/anaconda/lib/python3.5/site-packages/scipy/linalg/misc.py", line 129, in norm
    a = np.asarray_chkfinite(a)
  File "/Users/kg/anaconda/lib/python3.5/site-packages/numpy/lib/function_base.py", line 1022, in asarray_chkfinite
    "array must not contain infs or NaNs")
ValueError: array must not contain infs or NaNs

**Comment by vrv** [comment]
It looks like your embeddings have NaNs, most likely caused by your model training not being stable, which I suspect is not a TensorFlow bug.  You might get more help on StackOverflow for non-bugs like these (unless you can demonstrate to us that there's a bug here).

**Comment by kavasseri** [comment]
Thanks..Will look into it..

**Comment by kavasseri** [comment]
This is similar to issue #1839 and possible this is a numpy/scipy issue as reported by @zhongzyd
