### ISSUE TITLE
tf_upgrade_v2 AnnotationError 

### ISSUE THREAD

**Issue by zsdonghao** [tensorflow/tensorflow#24923]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac 10.14
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pip install tf-nightly
- TensorFlow version: 1.13
- Python version: 3.4.3
- Installed using virtualenv? pip? conda?: virtualenv 
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: no
- GPU model and memory: no

**Describe the problem**
Error found when run update the code for 2.0 preview

**Provide the exact sequence of commands / steps that you executed before running into the problem**

`tf_upgrade_v2 --intree tensorlayer --outtree tensorlayer2`

**Any other info / logs**
```bash
(env3)myhost:tensorlayer2 haodong$ tf_upgrade_v2 --intree tensorlayer --outtree tensorlayer2
/Users/haodong/Documents/Projects/python-workspace/env3/lib/python3.4/importlib/_bootstrap.py:321: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  return f(*args, **kwds)
Line 98:11: Added keywords to args of function 'tf.reduce_sum'
Line 117:9: Renamed 'tf.variable_scope' to 'tf.compat.v1.variable_scope'
Line 118:16: Added keywords to args of function 'tf.reduce_mean'
Line 118:31: Renamed 'tf.log' to 'tf.math.log'
Traceback (most recent call last):
  File "/Users/haodong/Documents/Projects/python-workspace/env3/bin/tf_upgrade_v2", line 11, in <module>
    sys.exit(main())
  File "/Users/haodong/Documents/Projects/python-workspace/env3/lib/python3.4/site-packages/tensorflow/tools/compatibility/tf_upgrade_v2_main.py", line 97, in main
    args.input_tree, args.output_tree, args.copy_other_files, args.in_place)
  File "/Users/haodong/Documents/Projects/python-workspace/env3/lib/python3.4/site-packages/tensorflow/tools/compatibility/ast_edits.py", line 570, in process_tree
    _, l_report, l_errors = self.process_file(input_path, output_path)
  File "/Users/haodong/Documents/Projects/python-workspace/env3/lib/python3.4/site-packages/tensorflow/tools/compatibility/ast_edits.py", line 441, in process_file
    temp_file)
  File "/Users/haodong/Documents/Projects/python-workspace/env3/lib/python3.4/site-packages/tensorflow/tools/compatibility/ast_edits.py", line 489, in process_opened_file
    self.update_string_pasta("".join(lines), in_filename))
  File "/Users/haodong/Documents/Projects/python-workspace/env3/lib/python3.4/site-packages/tensorflow/tools/compatibility/ast_edits.py", line 453, in update_string_pasta
    t = pasta.parse(text)
  File "/Users/haodong/Documents/Projects/python-workspace/env3/lib/python3.4/site-packages/pasta/__init__.py", line 25, in parse
    annotator.visit(t)
  File "/Users/haodong/Documents/Projects/python-workspace/env3/lib/python3.4/site-packages/pasta/base/annotate.py", line 1153, in visit
    super(AstAnnotator, self).visit(node)
  File "/Users/haodong/Documents/Projects/python-workspace/env3/lib/python3.4/site-packages/pasta/base/annotate.py", line 127, in visit
    super(BaseVisitor, self).visit(node)
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/ast.py", line 245, in visit
    return visitor(node)
  File "/Users/haodong/Documents/Projects/python-workspace/env3/lib/python3.4/site-packages/pasta/base/annotate.py", line 47, in wrapped
    f(self, node, *args, **kwargs)
  File "/Users/haodong/Documents/Projects/python-workspace/env3/lib/python3.4/site-packages/pasta/base/annotate.py", line 211, in visit_Module
    self.generic_visit(node)
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/ast.py", line 253, in generic_visit
    self.visit(item)
  File "/Users/haodong/Documents/Projects/python-workspace/env3/lib/python3.4/site-packages/pasta/base/annotate.py", line 1153, in visit
    super(AstAnnotator, self).visit(node)
  File "/Users/haodong/Documents/Projects/python-workspace/env3/lib/python3.4/site-packages/pasta/base/annotate.py", line 127, in visit
    super(BaseVisitor, self).visit(node)
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/ast.py", line 245, in visit
    return visitor(node)
  File "/Users/haodong/Documents/Projects/python-workspace/env3/lib/python3.4/site-packages/pasta/base/annotate.py", line 90, in wrapped
    f(self, node, *args, **kwargs)
  File "/Users/haodong/Documents/Projects/python-workspace/env3/lib/python3.4/site-packages/pasta/base/annotate.py", line 400, in visit_FunctionDef
    self.visit(stmt)
  File "/Users/haodong/Documents/Projects/python-workspace/env3/lib/python3.4/site-packages/pasta/base/annotate.py", line 1153, in visit
    super(AstAnnotator, self).visit(node)
  File "/Users/haodong/Documents/Projects/python-workspace/env3/lib/python3.4/site-packages/pasta/base/annotate.py", line 127, in visit
    super(BaseVisitor, self).visit(node)
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/ast.py", line 245, in visit
    return visitor(node)
  File "/Users/haodong/Documents/Projects/python-workspace/env3/lib/python3.4/site-packages/pasta/base/annotate.py", line 90, in wrapped
    f(self, node, *args, **kwargs)
  File "/Users/haodong/Documents/Projects/python-workspace/env3/lib/python3.4/site-packages/pasta/base/annotate.py", line 294, in visit_With
    return self.visit_With_3(node)
  File "/Users/haodong/Documents/Projects/python-workspace/env3/lib/python3.4/site-packages/pasta/base/annotate.py", line 344, in visit_With_3
    self.visit(stmt)
  File "/Users/haodong/Documents/Projects/python-workspace/env3/lib/python3.4/site-packages/pasta/base/annotate.py", line 1153, in visit
    super(AstAnnotator, self).visit(node)
  File "/Users/haodong/Documents/Projects/python-workspace/env3/lib/python3.4/site-packages/pasta/base/annotate.py", line 127, in visit
    super(BaseVisitor, self).visit(node)
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/ast.py", line 245, in visit
    return visitor(node)
  File "/Users/haodong/Documents/Projects/python-workspace/env3/lib/python3.4/site-packages/pasta/base/annotate.py", line 90, in wrapped
    f(self, node, *args, **kwargs)
  File "/Users/haodong/Documents/Projects/python-workspace/env3/lib/python3.4/site-packages/pasta/base/annotate.py", line 282, in visit_For
    self.visit(stmt)
  File "/Users/haodong/Documents/Projects/python-workspace/env3/lib/python3.4/site-packages/pasta/base/annotate.py", line 1153, in visit
    super(AstAnnotator, self).visit(node)
  File "/Users/haodong/Documents/Projects/python-workspace/env3/lib/python3.4/site-packages/pasta/base/annotate.py", line 127, in visit
    super(BaseVisitor, self).visit(node)
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/ast.py", line 245, in visit
    return visitor(node)
  File "/Users/haodong/Documents/Projects/python-workspace/env3/lib/python3.4/site-packages/pasta/base/annotate.py", line 90, in wrapped
    f(self, node, *args, **kwargs)
  File "/Users/haodong/Documents/Projects/python-workspace/env3/lib/python3.4/site-packages/pasta/base/annotate.py", line 219, in visit_If
    default=':\n')
  File "/Users/haodong/Documents/Projects/python-workspace/env3/lib/python3.4/site-packages/pasta/base/annotate.py", line 1334, in attr
    attr_parts.append(self.token(attr_val))
  File "/Users/haodong/Documents/Projects/python-workspace/env3/lib/python3.4/site-packages/pasta/base/annotate.py", line 1260, in token
    token_val, token.src, token.start[0], token.line))
pasta.base.annotate.AnnotationError: Expected ':' but found 'b":"'
line 564:             if line.startswith(b":"):  # Skip comments.
```

**Comment by yongtang** [comment]
@zsdonghao it will be more helpful if you could provide a `self-contained` code that could trigger the  error. 

Without the content of the `tensorlayer` the log you posted may not be very easy to see where the issue is.

**Comment by martinwicke** [comment]
I fixed this in google/pasta at head. I have to cut a new release of pasta and update the deps in TF.

**Comment by martinwicke** [comment]
Upgrading google_pasta (pip install -U google_pasta) should fix this. Give it a try? I'll update the deps in the night tf package.

**Comment by zsdonghao** [comment]
@yongtang @martinwicke Thanks, I successfully convert the codes one-by-one instead of converting the entire folder.
