### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'keras'(Tensorflow 1.4.0 has problem with new Model directory)

### ISSUE THREAD

**Issue by curious1me** [tensorflow/tensorflow#24954]
System information

Have I written custom code (as opposed to using a stock example script provided in TensorFlow): not custom code / object_detection

**OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04**

**TensorFlow installed from (source or binary): binary**

**TensorFlow version (use command below): 1.4.0**

**Python version: 3.5**

**CUDA/cuDNN version: 8.0/6.0**

Architecture        :   x86_64
CPU op-mode(s):   32-bit, 64-bit
Byte Order:            Little Endian
CPU(s)               :                6
On-line CPU(s) list:   0-5
Thread(s) per core:    1
Core(s) per socket:    6
Socket(s)              :    1
NUMA node(s)     :    1
Vendor ID            :  GenuineIntel
CPU family           :     6
Model:                 63
Model name:            Intel(R) Xeon(R) CPU E5-2603 v3 @ 1.60GHz
Stepping              :              2
CPU MHz            :               1596.347
CPU max MHz    :           1600.0000
CPU min MHz     :           1200.0000
BogoMIPS          :              3192.69
Virtualization      :        VT-x 
L1d cache          :             32K
L1i cache           :             32K
L2 cache            :              256K
L3 cache            :              15360K
NUMA node0 CPU(s):     0-5

Running `nvidia-smi` command :
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.130                Driver Version: 384.130                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Quadro K2200        Off  | 00000000:02:00.0  On |                  N/A |
| 42%   43C    P8     1W /  39W |    309MiB /  4040MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0       967      G   /usr/lib/xorg/Xorg                           178MiB |
|    0      1829      G   compiz                                       127MiB |
+-----------------------------------------------------------------------------+

```

Exact command to reproduce:
python object_detection/builders/model_builder_test.py
When i run the test program with tensorflow 1.4 i get the following error:

```
Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 23, in <module>
    from object_detection.builders import model_builder
  File "/home/models/research/object_detection/builders/model_builder.py", line 22, in <module>
    from object_detection.builders import box_predictor_builder
  File "/home/models/research/object_detection/builders/box_predictor_builder.py", line 21, in <module>
    from object_detection.predictors import convolutional_box_predictor
  File "/home/models/research/object_detection/predictors/convolutional_box_predictor.py", line 19, in <module>
    from object_detection.core import box_predictor
  File "/home/models/research/object_detection/core/box_predictor.py", line 137, in <module>
    class KerasBoxPredictor(tf.keras.Model):
AttributeError: module 'tensorflow.python.keras' has no attribute 'Model'
```

The solution i found when i searched was to update the tensorflow version.

But when I update tensorflow to the latest version(1.12) i get another error:
```
Traceback (most recent call last):
  File "/home/.virtualenvs/basic/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/.virtualenvs/basic/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/i.virtualenvs/basic/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/.virtualenvs/basic/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/.virtualenvs/basic/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 20, in <module>
    import tensorflow as tf
  File "/home/.virtualenvs/basic/lib/python3.5/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/.virtualenvs/basic/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/.virtualenvs/basic/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/.virtualenvs/basic/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/.virtualenvs/basic/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/.virtualenvs/basic/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/.virtualenvs/basic/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/.virtualenvs/basic/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory
```

Error seems like the higher tensorflow version is expecting CUDA 9.0.

So my inference is like the new tensorflow version doesnot support CUDA 8.0.
Downgrading the tensorflow version has problems with the new Models problem. 

What could be the solution?
Is this because  the CUDA runtime version is 9.0 (driver version 384.130) and the installed CUDA version is 8.0 and updating the CUDA version is the only solution?

NB: Is there any necessity for GPUs used in distributed training to have the same CUDA, tensorflow version?

**Comment by ymodak** [comment]
You are right you need to update to cuda 9.0 since you have switched to TF 1.12

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
