### ISSUE TITLE
install TensorFlow without using GPU

### ISSUE THREAD

**Issue by katoyu** [tensorflow/tensorflow#25006]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac OS Mojave 10.14
- TensorFlow installed from (source or binary): 
`pip install https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.10.1-py3-none-any.whl`
- TensorFlow version: 1.10.1
- Python version: 3.6.3
- Installed using virtualenv? pip? conda?: pip (and I also tried pip3)
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 
- GPU model and memory:

**Describe the problem**

I want to use TensorFlow in my laptop, and I would like to use TensorFlow without using GPU.

When I started Python on the command line, the following error occurred.
I have found a number of responses to similar errors, but they are all considered to be using GPUs because they are using CUDA.
In addition, although I got information that it operates by invalidating SIP by #19720, it did not solve my problem because I don't have directory like named 'cuda'.

Also, because of eGPU 's circumstances, mojave got information that GPEN version of TensorFlow will not work. I would like to ask about this as well.

```
Python 3.6.3 |Anaconda custom (64-bit)| (default, Oct  6 2017, 12:04:38) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> import tensorflow as tf
Traceback (most recent call last):
  File "/Users/yuichikato/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/Users/yuichikato/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/Users/yuichikato/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/Users/yuichikato/anaconda3/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/Users/yuichikato/anaconda3/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: dlopen(/Users/yuichikato/anaconda3/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 10): Library not loaded: @rpath/libcublas.8.0.dylib
  Referenced from: /Users/yuichikato/anaconda3/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
  Reason: image not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/yuichikato/anaconda3/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/Users/yuichikato/anaconda3/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 51, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/Users/yuichikato/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 52, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/Users/yuichikato/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/Users/yuichikato/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/Users/yuichikato/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/Users/yuichikato/anaconda3/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/Users/yuichikato/anaconda3/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: dlopen(/Users/yuichikato/anaconda3/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 10): Library not loaded: @rpath/libcublas.8.0.dylib
  Referenced from: /Users/yuichikato/anaconda3/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
  Reason: image not found


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

```

**Comment by katoyu** [comment]
@jvishnuvardhan 
Thanks for your reply.
Although this is a Japanese site,I referred to this page. https://qiita.com/tom_ato/items/bbdf4574b3ecb0048fa1
And I'm sorry but I confirmed that I did not have Bazel in my environment. I will install Bazel and install TensorFlow again.

**Comment by katoyu** [comment]
I tried to build Bazel with seeing [build configurations](https://www.tensorflow.org/install/source), but I failed it.
```
$ bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package
INFO: Invocation ID: d653837f-cc0b-497a-a45d-bcabfdf22e7e
ERROR: /private/var/tmp/_bazel_yuichikato/2f56da6d0e205256e4b3591a707923ab/external/local_config_cc/BUILD:58:5: in apple_cc_toolchain rule @local_config_cc//:cc-compiler-armeabi-v7a: Xcode version must be specified to use an Apple CROSSTOOL. If your Xcode version has changed recently, try: "bazel clean --expunge" to re-run Xcode configuration
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: Analysis of target '@local_config_cc//:cc-compiler-armeabi-v7a' failed; build aborted
INFO: Elapsed time: 25.019s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (164 packages loaded, 3136 targets\
 configured)
    currently loading: tensorflow/contrib/resampler
    Fetching @grpc; fetching
    Fetching @gif_archive; fetching
$ bazel clean --expunge
INFO: Invocation ID: 54ca3adf-f3f3-4fbf-96e0-c51e90344dee
INFO: Starting clean.
$ bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package
Starting local Bazel server and connecting to it...
INFO: Invocation ID: 1ef449d8-976c-427f-8ffc-66e48c45b98b
ERROR: /private/var/tmp/_bazel_yuichikato/2f56da6d0e205256e4b3591a707923ab/external/local_config_cc/BUILD:58:5: in apple_cc_toolchain rule @local_config_cc//:cc-compiler-armeabi-v7a: Xcode version must be specified to use an Apple CROSSTOOL. If your Xcode version has changed recently, try: "bazel clean --expunge" to re-run Xcode configuration
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: Analysis of target '@local_config_cc//:cc-compiler-armeabi-v7a' failed; build aborted
INFO: Elapsed time: 17.207s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (179 packages loaded, 3054 targets\
 configured)
    Fetching @com_google_absl; fetching 5s
```
I wrote the full text on the link below.
https://github.com/katoyu/about-install-tensorflow/blob/master/bazel-error

**Comment by AndreiMaga** [comment]
@katoyu 
Try installing Tensorflow by using ```pip install tensorflow==1.10.1```. 
It should work just fine.

**Comment by katoyu** [comment]
@AndreiMaga 
Thank you for your comments, and I maybe successed to use tensorflow owing to your advice.
```
$ cd
$ python
Python 3.6.3 (default, Jan 21 2019, 18:20:23) 
[GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.10.44.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
/Users/yuichikato/.pyenv/versions/3.6.3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
>>> hello = tf.constant('Hello, TensorFlow!')
>>> sess = tf.Session()
2019-01-21 21:28:04.749299: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
>>> print(sess.run(hello))
b'Hello, TensorFlow!'
>>> 
```
I would like to ask again with confirmation, but can I ignore this Runtime Warning sentence?
Can you also erase it?

**Comment by AndreiMaga** [comment]
@katoyu 
```I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA``` 
This is a warning "Tensorflow was not compiled to use your cpu's low level api". Basically it tells you that tensorflow can comunicate better with your cpu with  the ```AVX2``` and ```FMA``` flags. These flags are set when tensorflow is compiled.

It should work fine like this but "faster" with these flags set.
You cannot erase that unfortunately.

**Comment by katoyu** [comment]
@AndreiMaga 
Okay, it is not a big issue.
I'm grateful for a polite reply.
