### ISSUE TITLE
Test fail: //tensorflow_serving/session_bundle:session_bundle_py_test

### ISSUE THREAD

**Issue by hermione521** [tensorflow/tensorflow#2500]
http://ci.bazel.io/job/TensorFlow_Serving/BAZEL_VERSION=HEAD,PLATFORM_NAME=linux-x86_64/115/console

```
____From Testing //tensorflow_serving/session_bundle:session_bundle_py_test: 
====================
Test output for //tensorflow_serving/session_bundle:session_bundle_py_test: .E. 
====================================================================== 
ERROR: 
testBasic (__main__.SessionBundleLoadTest)
 ---------------------------------------------------------------------- 
Traceback (most recent call last): 
File "/home/ci/.cache/bazel/_bazel_ci/e409f7152fa45ddf3337f1660b5273b9/execroot/linux-x86_64/bazel-out/local-fastbuild/bin/tensorflow_serving/session_bundle/session_bundle_py_test.runfiles/tf_serving/tensorflow_serving/session_bundle/session_bundle_test.py", line 39, in testBasic base_path, target="", config=tf.ConfigProto(device_count={"CPU": 2})) 
File "/home/ci/.cache/bazel/_bazel_ci/e409f7152fa45ddf3337f1660b5273b9/execroot/linux-x86_64/bazel-out/local-fastbuild/bin/tensorflow_serving/session_bundle/session_bundle_py_test.runfiles/tf_serving/tensorflow_serving/session_bundle/session_bundle.py", line 57, in LoadSessionBundleFromPath meta_graph_filename) 
RuntimeError: Expected meta graph file missing /home/ci/.cache/bazel/_bazel_ci/e409f7152fa45ddf3337f1660b5273b9/execroot/linux-x86_64/bazel-out/local-fastbuild/bin/tensorflow_serving/session_bundle/session_bundle_py_test.runfiles/tensorflow_serving/session_bundle/example/half_plus_two/00000123/export.meta
 ---------------------------------------------------------------------- 
Ran 3 tests in 0.001s FAILED (errors=1) 
================================================================================
```

**Comment by mrry** [comment]
This issue tracker is for core TensorFlow issues. Please reopen this issue on the [TensorFlow Serving issues page](https://github.com/tensorflow/serving/issues).

**Comment by trinity77** [comment]
Trigger update_date
