### ISSUE TITLE
import tensorflow in python3 -> TypeError: __new__() got an unexpected keyword argument 'serialized_options'

### ISSUE THREAD

**Issue by swiss-knight** [tensorflow/tensorflow#25016]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**Describe the current behavior**

I have the following issue when importing tensorflow in python3 since some days ago:
```
>>> import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/__init__.py", line 59, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/core/framework/graph_pb2.py", line 15, in <module>
    from tensorflow.core.framework import node_def_pb2 as tensorflow_dot_core_dot_framework_dot_node__def__pb2
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/core/framework/node_def_pb2.py", line 15, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/core/framework/attr_value_pb2.py", line 15, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/core/framework/tensor_pb2.py", line 15, in <module>
    from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/core/framework/resource_handle_pb2.py", line 22, in <module>
    serialized_pb=_b('\n/tensorflow/core/framework/resource_handle.proto\x12\ntensorflow\"r\n\x13ResourceHandleProto\x12\x0e\n\x06\x64\x65vice\x18\x01 \x01(\t\x12\x11\n\tcontainer\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x11\n\thash_code\x18\x04 \x01(\x04\x12\x17\n\x0fmaybe_type_name\x18\x05 \x01(\tBn\n\x18org.tensorflow.frameworkB\x0eResourceHandleP\x01Z=github.com/tensorflow/tensorflow/tensorflow/go/core/framework\xf8\x01\x01\x62\x06proto3')
TypeError: __new__() got an unexpected keyword argument 'serialized_options'

```

**Describe the expected behavior**
```
>>> import tensorflow as tf
>>> 
```

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): NO
- OS Platform and Distribution: Ubuntu 18.04 (4.15.0-43-generic x86_64 GNU/Linux)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NO 
- TensorFlow installed from (source or binary): NO (using pip3)
- TensorFlow version (use command below): 1.12.0 (command below is not working as tf doesn't load)
- Python version: Python 3.6.7
- Bazel version (if compiling from source): NO
- GCC/Compiler version (if compiling from source): NO
- CUDA/cuDNN version: NO CUDA
- GPU model and memory: Intel HD Graphics 5500:
```
$ sudo lshw -C display
  *-display                 
       description: VGA compatible controller
       product: HD Graphics 5500
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 09
       width: 64 bits
       clock: 33MHz
       capabilities: msi pm vga_controller bus_master cap_list rom
       configuration: driver=i915 latency=0
       resources: irq:44 memory:f0000000-f0ffffff memory:e0000000-efffffff ioport:3000(size=64) memory:c0000-dffff

```

<em>You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)":</em>

This doesn't work as tf doesn't load.

**Code to reproduce the issue**
`>>> import tensorflow as tf`

**Other info / logs**
<em>Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.</em>

```
$ pip3 list | grep tensor
tensorboard                   1.12.0     
tensorflow                    1.12.0 
```
Everything is up-to-date for tensorflow:
```
$ sudo -H pip3 install --upgrade tensorflow
Requirement already up-to-date: tensorflow in /usr/local/lib/python3.6/dist-packages (1.12.0)
Requirement already satisfied, skipping upgrade: grpcio>=1.8.6 in /usr/local/lib/python3.6/dist-packages (from tensorflow) (1.16.1)
Requirement already satisfied, skipping upgrade: absl-py>=0.1.6 in /usr/local/lib/python3.6/dist-packages (from tensorflow) (0.6.1)
Requirement already satisfied, skipping upgrade: gast>=0.2.0 in /usr/local/lib/python3.6/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied, skipping upgrade: six>=1.10.0 in /usr/local/lib/python3.6/dist-packages (from tensorflow) (1.12.0)
Requirement already satisfied, skipping upgrade: keras-applications>=1.0.6 in /usr/local/lib/python3.6/dist-packages (from tensorflow) (1.0.6)
Requirement already satisfied, skipping upgrade: protobuf>=3.6.1 in /usr/local/lib/python3.6/dist-packages (from tensorflow) (3.6.1)
Requirement already satisfied, skipping upgrade: tensorboard<1.13.0,>=1.12.0 in /usr/local/lib/python3.6/dist-packages (from tensorflow) (1.12.0)
Requirement already satisfied, skipping upgrade: astor>=0.6.0 in /usr/local/lib/python3.6/dist-packages (from tensorflow) (0.7.1)
Requirement already satisfied, skipping upgrade: numpy>=1.13.3 in /usr/local/lib/python3.6/dist-packages (from tensorflow) (1.15.4)
Requirement already satisfied, skipping upgrade: termcolor>=1.1.0 in /usr/local/lib/python3.6/dist-packages (from tensorflow) (1.1.0)
Requirement already satisfied, skipping upgrade: keras-preprocessing>=1.0.5 in /usr/local/lib/python3.6/dist-packages (from tensorflow) (1.0.5)
Requirement already satisfied, skipping upgrade: wheel>=0.26 in /usr/lib/python3/dist-packages (from tensorflow) (0.30.0)
Requirement already satisfied, skipping upgrade: h5py in /usr/local/lib/python3.6/dist-packages (from keras-applications>=1.0.6->tensorflow) (2.8.0)
Requirement already satisfied, skipping upgrade: setuptools in /usr/lib/python3/dist-packages (from protobuf>=3.6.1->tensorflow) (39.0.1)
Requirement already satisfied, skipping upgrade: markdown>=2.6.8 in /usr/local/lib/python3.6/dist-packages (from tensorboard<1.13.0,>=1.12.0->tensorflow) (3.0.1)
Requirement already satisfied, skipping upgrade: werkzeug>=0.11.10 in /usr/local/lib/python3.6/dist-packages (from tensorboard<1.13.0,>=1.12.0->tensorflow) (0.14.1)

```

**Comment by swiss-knight** [comment]
Nothing more than the OS regular updates.

By diving more into it, i think some protobuf stuffs were required as a dependency from one of these and that they have "kind of" taken the priority over the protobuf I have manually installed using pip3.

What's wrong seems that:
1. 
```
$ protoc --version
libprotoc 3.0.0
```
2. In python3 now:
```
>>> from google import protobuf
>>> protobuf.__version__
'3.0.0'
>>> protobuf.__file__
'/usr/lib/python3/dist-packages/google/protobuf/__init__.py'
```

3. But I guess in python3 it was 3.6.x before because of:
```
$ pip3 list | grep proto
protobuf                      3.6.1 
```

and:

```
$ apt-cache policy libprotobuf10 
libprotobuf10:
  Installed: 3.0.0-9.1ubuntu1
  Candidate: 3.0.0-9.1ubuntu1
  Version table:
 *** 3.0.0-9.1ubuntu1 500
        500 http://ch.archive.ubuntu.com/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
```

Anyway, protobuf 3.6.1 (not 3.0.0!) seems installed properly in "/usr/local": 
```
$ find /usr/local/lib/python3.6/dist-packages -iname "*protobuf*"
/usr/local/lib/python3.6/dist-packages/torch/share/cmake/Caffe2/public/protobuf.cmake
/usr/local/lib/python3.6/dist-packages/protobuf-3.6.1.dist-info
/usr/local/lib/python3.6/dist-packages/protobuf-3.6.1-py3.6-nspkg.pth
/usr/local/lib/python3.6/dist-packages/google/protobuf
/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/protobuf
/usr/local/lib/python3.6/dist-packages/tensorflow/include/google/protobuf
/usr/local/lib/python3.6/dist-packages/tensorflow/include/external/protobuf_archive
/usr/local/lib/python3.6/dist-packages/tensorflow/include/external/protobuf_archive/python/google/protobuf
/usr/local/lib/python3.6/dist-packages/tensorflow/include/external/protobuf_archive/src/google/protobuf
/usr/local/lib/python3.6/dist-packages/tensorflow/include/tensorflow/core/platform/protobuf_internal.h
/usr/local/lib/python3.6/dist-packages/tensorflow/include/tensorflow/core/platform/protobuf.h
/usr/local/lib/python3.6/dist-packages/tensorflow/include/tensorflow/core/platform/protobuf_compiler.h
/usr/local/lib/python3.6/dist-packages/tensorflow/include/tensorflow/core/platform/default/protobuf.h
/usr/local/lib/python3.6/dist-packages/tensorflow/include/tensorflow/core/platform/default/protobuf_compiler.h
/usr/local/lib/python3.6/dist-packages/tensorflow/include/tensorflow/core/protobuf
```
This should override the /usr/local package if existing when loading in python3, but there is nothing in the system wide "/usr/lib" place:
```
$ find /usr/lib/python3.6/ -iname "*proto*"
$
```

So I guess it's coming from elsewhere, probably linked with the 'libprotobuf10' Ubuntu package that were installed. 

It's only a guess from my side, I may be wrong somewhere in my understanding of the situation.

**Comment by jvishnuvardhan** [comment]
@swiss-knight Could you follow the instructions [here](https://github.com/rnreich/ubuntu-tensorflow-gpu-all-versions) and let us know how it works. I recently used those steps and successfully installed tensorflow-gpu. If you had already resolved the issue, please close the issue or let us know. Thanks!
