### ISSUE TITLE
ImportError: cannot import name 'pywrap_tensorflow'

### ISSUE THREAD

**Issue by mikkokotila** [tensorflow/tensorflow#25029]
**NOTE:**  this is not related to the common case of being inside the tensorflow folder.

**System information**
- Mac OSX 10.11.6
- installed 1.5 with pip (I use old version because old Mac OSX version)
- TensorFlow version:
- Python version: 3.6.6
- Inside virtualenv and with pip

**Describe the problem**
I have flask app which I install as python package and TF is installed as part of the required packages. When I run the flask app, I get: 

```
Traceback (most recent call last):
  File "studio/app.py", line 9, in <module>
    from simple_neural_net import simple_neural_net
  File "/Users/mikko/dev/studio/simple_neural_net.py", line 3, in <module>
    from keras.models import Sequential
  File "/Users/mikko/dev/studio_test/lib/python3.6/site-packages/keras/__init__.py", line 3, in <module>
    from . import utils
  File "/Users/mikko/dev/studio_test/lib/python3.6/site-packages/keras/utils/__init__.py", line 6, in <module>
    from . import conv_utils
  File "/Users/mikko/dev/studio_test/lib/python3.6/site-packages/keras/utils/conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "/Users/mikko/dev/studio_test/lib/python3.6/site-packages/keras/backend/__init__.py", line 89, in <module>
    from .tensorflow_backend import *
  File "/Users/mikko/dev/studio_test/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf
  File "/Users/mikko/dev/studio_test/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/Users/mikko/dev/studio_test/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
ImportError: cannot import name 'pywrap_tensorflow'
```
The problem manifest in the environment regardless of how I try to import tensorflow (i.e. not just inside the flask app). On the same machine I have several envs (including one I installed yesterday) which work.

**Comment by mikkokotila** [comment]
This is resolved by installing 1.6.
