### ISSUE TITLE
eager execution numpy issues

### ISSUE THREAD

**Issue by cristipurdel** [tensorflow/tensorflow#25053]
<em>Please make sure that this is a documentation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:doc_template</em>

**System information**
- TensorFlow version: 1.12.0
- Doc Link: https://www.tensorflow.org/tutorials/eager/eager_basics#numpy_compatibility

**Describe the documentation issue**
Running the following code:
```
import tensorflow as tf
import numpy as np

tf.enable_eager_execution
#tf.enable_eager_execution()
# Gives following erro:    ValueError: tf.enable_eager_execution must be called at program startup.

ndarray = np.ones([3, 3])

print("TensorFlow operations convert numpy arrays to Tensors automatically")
tensor = tf.multiply(ndarray, 42)
print(tensor)


print("And NumPy operations convert Tensors to numpy arrays automatically")
print(np.add(tensor, 1))

print("The .numpy() method explicitly converts a Tensor to a numpy array")
print(tensor.numpy())
```

Traceback error:
```
Traceback (most recent call last):

  File "<ipython-input-33-4feddfe31f00>", line 1, in <module>
    runfile('****/t.py', wdir='****')

  File "C:\Users\****\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "C:\Users\****\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "****/t.py", line 21, in <module>
    print(tensor.numpy())

AttributeError: 'Tensor' object has no attribute 'numpy'
```

1st issue: 
In docs it says I should use 
tf.enable_eager_execution()
But if I use it I get following error:
ValueError: tf.enable_eager_execution must be called at program startup.

2nd issue:
Doc says I should get real tensorvalues for arrays, but I get:
```
TensorFlow operations convert numpy arrays to Tensors automatically
Tensor("Mul_10:0", shape=(3, 3), dtype=float64)
And NumPy operations convert Tensors to numpy arrays automatically
Tensor("add_10:0", shape=(3, 3), dtype=float64)
```

3rd issue:
Based on above Traceback issue:
AttributeError: 'Tensor' object has no attribute 'numpy'

I had to install tensorflow-eigen          1.12.0, since I could not run without it

**We welcome contributions by users. Will you be able to update submit a PR (use the [doc style guide](https://www.tensorflow.org/community/documentation)) to fix the doc Issue?**
No

**Comment by cristipurdel** [comment]
Apparently I still had to use 
`with tf.Session() as session:`
Closing.
