### ISSUE TITLE
AttributeError: module 'keras_applications' has no attribute 'set_keras_submodules'

### ISSUE THREAD

**Issue by Wade129** [tensorflow/tensorflow#25062]
### System information
- **Linux Ubuntu 16.04**
- **Firefly RK3399**:
- **TensorFlow version: 1.12.0**:
- **Python version: 3.5.2**:

### Describe the problem
I'm trying the objection_detection with opencv and tensorflow. The source code has been given at the last. When I python3 11.py, it comes error. 
Though it says "AttributeError: module 'keras_applications' has no attribute 'set_keras_submodules'", I find    'set_keras_submodules'exits in init.py of keras_applications. So it confuses me quite a long time. I try to update .pyc in pycache but it didn't work.
```
root@firefly:/usr/local/lib/python3.5/dist-packages/keras_applications# ls -l
total 200
-rw-r--r-- 1 root staff  3116 Jan 18 07:29 __init__.py
drwxr-sr-x 2 root staff  4096 Jan 21 02:53 __pycache__
-rw-r--r-- 1 root staff 13450 Jan 18 07:29 densenet.py
-rw-r--r-- 1 root staff 12632 Jan 18 07:29 imagenet_utils.py
-rw-r--r-- 1 root staff 14725 Jan 18 07:29 inception_resnet_v2.py
-rw-r--r-- 1 root staff 14586 Jan 18 07:29 inception_v3.py
-rw-r--r-- 1 root staff 20306 Jan 18 07:29 mobilenet.py
-rw-r--r-- 1 root staff 21720 Jan 18 07:29 mobilenet_v2.py
-rw-r--r-- 1 root staff 29931 Jan 18 07:29 nasnet.py
-rw-r--r-- 1 root staff 11860 Jan 18 07:29 resnet50.py
-rw-r--r-- 1 root staff  8504 Jan 18 07:29 vgg16.py
-rw-r--r-- 1 root staff  8985 Jan 18 07:29 vgg19.py
-rw-r--r-- 1 root staff 14008 Jan 18 07:29 xception.py
root@firefly:/usr/local/lib/python3.5/dist-packages/keras_applications# sudo vim __init__.py
```
'set_keras_submodules' exits
```
def set_keras_submodules(backend=None,
                         layers=None,
                         models=None,
                         utils=None,
                         engine=None):
    # Deprecated, will be removed in the future.
    global _KERAS_BACKEND
    global _KERAS_LAYERS
    global _KERAS_MODELS
    global _KERAS_UTILS
    _KERAS_BACKEND = backend
    _KERAS_LAYERS = layers
    _KERAS_MODELS = models
    _KERAS_UTILS = utils
```
```
root@firefly:/home/firefly/models/research/object_detection/models# python3 11.py
Traceback (most recent call last):
  File "11.py", line 5, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/__init__.py", line 88, in <module>
    from tensorflow.python import keras
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/__init__.py", line 25, in <module>
    from tensorflow.python.keras import applications
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/applications/__init__.py", line 37, in <module>
    keras_applications.set_keras_submodules)[0]:
AttributeError: module 'keras_applications' has no attribute 'set_keras_submodules'
```
### Source code / logs
11.py
```
import numpy as np
import os
import sys
import tarfile
import tensorflow as tf
import cv2
import time
from collections import defaultdict

sys.path.append("../..")

from object_detection.utils import label_map_util
from object_detection.utils import visualization_utils as vis_util


MODEL_NAME = 'ssd_mobilenet_v1_coco_2018_01_28'

PATH_TO_CKPT = MODEL_NAME + '/frozen_inference_graph.pb'

PATH_TO_LABELS = os.path.join('/home/firefly/models/research/object_detection/data', 'mscoco_label_map.pbtxt')

model_path = "/home/firefly/models/research/object_detection/models/ssd_mobilenet_v1_coco_2018_01_28/model.ckpt"

start = time.clock()
NUM_CLASSES = 90

end= time.clock()
print('load the model' ,(end -start))

## Load a (frozen) Tensorflow model into memory.
detection_graph = tf.Graph()
with detection_graph.as_default():
    od_graph_def = tf.GraphDef()
with tf.gfile.GFile(PATH_TO_CKPT, 'rb') as fid:
    serialized_graph = fid.read()
    od_graph_def.ParseFromString(serialized_graph)
    tf.import_graph_def(od_graph_def, name='')

## Loading label map
label_map = label_map_util.load_labelmap(PATH_TO_LABELS)
categories = label_map_util.convert_label_map_to_categories(label_map, max_num_classes=NUM_CLASSES, use_display_name=True)
category_index = label_map_util.create_category_index(categories)

cap = cv2.VideoCapture(1)
cap.set(3,640)
cap.set(4,480)
with detection_graph.as_default():
    with tf.Session(graph=detection_graph) as sess:
        writer = tf.summary.FileWriter("logs/", sess.graph)
        sess.run(tf.global_variables_initializer())

        loader = tf.train.import_meta_graph(model_path + '.meta')
        loader.restore(sess, model_path)
        while(1):
            start = time.clock()
            ret, frame = cap.read()
            if cv2.waitKey(1) & 0xFF == ord('q'):
                break
            image_np =frame

            image_np_expanded = np.expand_dims(image_np, axis=0)
            image_tensor = detection_graph.get_tensor_by_name('image_tensor:0')
            boxes = detection_graph.get_tensor_by_name('detection_boxes:0')
            scores = detection_graph.get_tensor_by_name('detection_scores:0')
            classes = detection_graph.get_tensor_by_name('detection_classes:0')
            num_detections = detection_graph.get_tensor_by_name('num_detections:0')

            (boxes, scores, classes, num_detections) = sess.run(
                [boxes, scores, classes, num_detections],
                feed_dict={image_tensor: image_np_expanded})

            vis_util.visualize_boxes_and_labels_on_image_array(
                image_np, np.squeeze(boxes),
                np.squeeze(classes).astype(np.int32),
                np.squeeze(scores),
                category_index,
                use_normalized_coordinates=True,
                line_thickness=6)
            end = time.clock()

            print ('One frame detect take time:' ,end - start)

            cv2.imshow("capture", image_np)
            print('after cv2 show')
            cv2.waitKey(1)
cap.release()
cv2.destroyAllWindows()
```

**Comment by sistemas3-mv** [comment]
Same problem here, did you solve it?

**Comment by Wade129** [comment]
@sistemas3-mv I have solved it. You can try to replace a new location to run the code. 
At first, I run the code at /home/firefly/models/research/object_detection/models. When I run the code, it went errors importing tensorflow. So I run it at /home or other place, and the errors was gone. 
Though I have solved the problem, but I didn't realize what the real problem is.
By the way, remember to move your model to the location you run the code.

**Comment by Kerinchen911** [comment]
Same problem,replacing a new location can not solve it

**Comment by serser** [comment]
Upgrade keras to 2.2.4 solved my problem.

**Comment by tired0408** [comment]
Same problem.At this env, keras==2.2.2, Keras-Applications==1.0.8  and keras_preprocessing==1.1.0,please upgrade  Keras-Applications==1.0.4 and keras_preprocessing==1.0.2 can solved the problem

**Comment by ChaosPredictor** [comment]
downgrade keras_applications to 1.0.7
