### ISSUE TITLE
ERROR: /tmp/tensorflow-1.9.0/tensorflow/BUILD:541:1: Executing genrule //tensorflow:python_api_gen failed (Exit 1) 

### ISSUE THREAD

**Issue by p2jindia** [tensorflow/tensorflow#25078]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Alpine 3.8
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): Source (https://github.com/tensorflow/tensorflow/archive/v${TENSORFLOW_VERSION}.tar.gz)
- TensorFlow version: 1.9.0
- Python version: 3.6
- Installed using virtualenv? pip? conda?:  Bazel
- Bazel version (if compiling from source): 0.17.2
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: NA. CPU only
- GPU model and memory: NA. CPU only

**Describe the problem**
Build fails with error
ERROR: /tmp/tensorflow-1.9.0/tensorflow/BUILD:541:1: Executing genrule //tensorflow:python_api_gen failed (Exit 1) 

**Provide the exact sequence of commands / steps that you executed before running into the problem**
PFA the docker
[Dockerfile.txt](https://github.com/tensorflow/tensorflow/files/2780053/Dockerfile.txt)
[build.log](https://github.com/tensorflow/tensorflow/files/2780059/build.log)

**Any other info / logs**
Traceback (most recent call last): File "/root/.cache/bazel/_bazel_root/7fa049be34bffde882bfd5021ad00c35/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/tools/api/generator/create_python_api.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow.py", line 58, in <module> from tensorflow.python.pywrap_tensorflow_internal import * File "/root/.cache/bazel/_bazel_root/7fa049be34bffde882bfd5021ad00c35/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/tools/api/generator/create_python_api.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module> _pywrap_tensorflow_internal = swig_import_helper() File "/root/.cache/bazel/_bazel_root/7fa049be34bffde882bfd5021ad00c35/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/tools/api/generator/create_python_api.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description) File "/usr/lib/python3.6/imp.py", line 243, in load_module return load_dynamic(name, filename, file) File "/usr/lib/python3.6/imp.py", line 343, in load_dynamic return _load(spec) ImportError: Error relocating /root/.cache/bazel/_bazel_root/7fa049be34bffde882bfd5021ad00c35/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/tools/api/generator/create_python_api.runfiles/org_tensorflow/tensorflow/python/../../_solib_k8/_U_S_Stensorflow_Spython_C_Upywrap_Utensorflow_Uinternal.so___Utensorflow/libtensorflow_framework.so: je_tsd_tls: initial-exec TLS resolves to dynamic definition in /root/.cache/bazel/_bazel_root/7fa049be34bffde882bfd5021ad00c35/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/tools/api/generator/create_python_api.runfiles/org_tensorflow/tensorflow/python/../../_solib_k8/_U_S_Stensorflow_Spython_C_Upywrap_Utensorflow_Uinternal.so___Utensorflow/libtensorflow_framework.so During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/root/.cache/bazel/_bazel_root/7fa049be34bffde882bfd5021ad00c35/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/tools/api/generator/create_python_api.runfiles/org_tensorflow/tensorflow/tools/api/generator/create_python_api.py", line 27, in <module> from tensorflow.python.util import tf_decorator File "/root/.cache/bazel/_bazel_root/7fa049be34bffde882bfd5021ad00c35/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/tools/api/generator/create_python_api.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 49, in <module> from tensorflow.python import pywrap_tensorflow File "/root/.cache/bazel/_bazel_root/7fa049be34bffde882bfd5021ad00c35/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/tools/api/generator/create_python_api.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow.py", line 74, in <module> raise ImportError(msg) ImportError: Traceback (most recent call last): File "/root/.cache/bazel/_bazel_root/7fa049be34bffde882bfd5021ad00c35/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/tools/api/generator/create_python_api.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow.py", line 58, in <module> from tensorflow.python.pywrap_tensorflow_internal import * File "/root/.cache/bazel/_bazel_root/7fa049be34bffde882bfd5021ad00c35/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/tools/api/generator/create_python_api.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module> _pywrap_tensorflow_internal = swig_import_helper() File "/root/.cache/bazel/_bazel_root/7fa049be34bffde882bfd5021ad00c35/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/tools/api/generator/create_python_api.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description) File "/usr/lib/python3.6/imp.py", line 243, in load_module return load_dynamic(name, filename, file) File "/usr/lib/python3.6/imp.py", line 343, in load_dynamic return _load(spec) ImportError: Error relocating /root/.cache/bazel/_bazel_root/7fa049be34bffde882bfd5021ad00c35/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/tools/api/generator/create_python_api.runfiles/org_tensorflow/tensorflow/python/../../_solib_k8/_U_S_Stensorflow_Spython_C_Upywrap_Utensorflow_Uinternal.so___Utensorflow/libtensorflow_framework.so: je_tsd_tls: initial-exec TLS resolves to dynamic definition in /root/.cache/bazel/_bazel_root/7fa049be34bffde882bfd5021ad00c35/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/tools/api/generator/create_python_api.runfiles/org_tensorflow/tensorflow/python/../../_solib_k8/_U_S_Stensorflow_Spython_C_Upywrap_Utensorflow_Uinternal.so___Utensorflow/libtensorflow_framework.so Failed to load the native TensorFlow runtime. See https://www.tensorflow.org/install/install_sources#common_installation_problems for some common reasons and solutions. Include the entire stack trace above this error message when asking for help.

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by jvishnuvardhan** [comment]
@p2jindia Please check the [tested build configurations](https://www.tensorflow.org/install/source#linux). For Tensorflow 1.9.0, Bazel 0.11.0 vesion is supported.  Could you downgrade your Bazel version and let us know how it progresses. Thanks!

**Comment by jvishnuvardhan** [comment]
@p2jindia Please check the [tested build configurations](https://www.tensorflow.org/install/source#linux). For Tensorflow 1.9.0, Bazel 0.11.0 vesion is supported.  Could you downgrade your Bazel version and let us know how it progresses. Thanks!

**Comment by jvishnuvardhan** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by sarnold** [comment]
This looks like an alpine/musl issue:  https://bugs.freedesktop.org/show_bug.cgi?id=35268
Getting rid of STATIC_TLS is the current workaround.
