### ISSUE TITLE
ImportError: DLL load failed with error code -1073741795

### ISSUE THREAD

**Issue by shyhtzonglee** [tensorflow/tensorflow#25094]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Windows 7 Home Premium 64-bit SP1
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:N/A
- TensorFlow installed from (source or binary):binary
- TensorFlow version (use command below):1.12.0
- Python version:3.6.8
- Bazel version (if compiling from source):N/A
- GCC/Compiler version (if compiling from source):N/A
- CUDA/cuDNN version:N/A
- GPU model and memory:ATI Mobility Radeon HD 6370

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**
It failed on importing tensorflow
**Describe the expected behavior**
It should be able to import tensorflow. I don't have problem in Anaconda.
**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
#install Python3.6.8
#install vc_redist.x64
pip install -U pip virtualenv
virtualenv --system-site-packages -p python ./keras
.\keras\Scripts\activate keras
(keras) pip install --upgrade pip
(keras) pip list
(keras) pip install --upgrade tensorflow
(keras) python
import tensorflow as tf
**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
Python 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
import tensorflow as tf
Traceback (most recent call last):
  File "C:\Users\Stlee\keras\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Stlee\keras\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Stlee\keras\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Stlee\keras\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Stlee\keras\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed with error code -1073741795

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import tensorflow as tf
  File "C:\Users\Stlee\keras\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\Stlee\keras\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Stlee\keras\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Stlee\keras\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Stlee\keras\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Stlee\keras\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Stlee\keras\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Stlee\keras\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed with error code -1073741795

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by ymodak** [comment]
>virtualenv --system-site-packages -p python ./keras
Can you try setting your python interpreter to Python3 and build virtual environment?
>virtualenv --system-site-packages -p python3 ./keras

**Comment by shyhtzonglee** [comment]
I got Python 3.6.8 only, if I type -p python3, it'll complain.

**Comment by shyhtzonglee** [comment]
Hi ymodak,

Thanks for your response.
I got Python 3.6.8 only. If I type -p python3, it will find no python
interpreter.

Shyhtzong Lee

ymodak <notifications@github.com> 於 2019年1月23日 週三 上午8:38寫道：

**Comment by ymodak** [comment]
Is this still an issue for you?
can you update your keras version, if not the latest? Thanks!

**Comment by shyhtzonglee** [comment]
It doesn't matter I install keras or not, it just failed me on "import
tensorflow".
I can run tensorflow and keras on Anaconda, it's got its own vs2015_runtime,
so I don't need to install vc_redist.x64 to run Anaconda.
But it's still a problem for me in the windows python.
Thanks.

ymodak <notifications@github.com> 於 2019年2月16日 週六 上午8:38寫道：

**Comment by rienath** [comment]
I had the same problem with python 3.6.0. Updating it to python 3.6.4 helped. Try downgrading to python 3.6.4

**Comment by shyhtzonglee** [comment]
No, python 3.6.4 does not work for me. Thanks anyway.

**Comment by SmirnovKol** [comment]
(venv) C:>python
Python 3.6.7 (v3.6.7:6ec5cf24b7, Oct 20 2018, 13:35:33) [MSC v.1900 64 bit (AMD6
4)] on win32
Type "help", "copyright", "credits" or "license" for more information.

import tensorflow
Traceback (most recent call last):
File "C:\Users\Administrator\venv\lib\site-packages\tensorflow\python\pywrap_t
ensorflow.py", line 58, in 
from tensorflow.python.pywrap_tensorflow_internal import *
File "C:\Users\Administrator\venv\lib\site-packages\tensorflow\python\pywrap_t
ensorflow_internal.py", line 28, in 
_pywrap_tensorflow_internal = swig_import_helper()
File "C:\Users\Administrator\venv\lib\site-packages\tensorflow\python\pywrap_t
ensorflow_internal.py", line 24, in swig_import_helper
_mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, descript
ion)
File "C:\Users\Administrator\venv\lib\imp.py", line 243, in load_module
return load_dynamic(name, filename, file)
File "C:\Users\Administrator\venv\lib\imp.py", line 343, in load_dynamic
return _load(spec)
ImportError: DLL load failed with error code -1073741795

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "", line 1, in 
File "C:\Users\Administrator\venv\lib\site-packages\tensorflow_init_.py", l
ine 24, in 
from tensorflow.python import pywrap_tensorflow # pylint: disable=unused-im
port
File "C:\Users\Administrator\venv\lib\site-packages\tensorflow\python_init_
.py", line 49, in 
from tensorflow.python import pywrap_tensorflow
File "C:\Users\Administrator\venv\lib\site-packages\tensorflow\python\pywrap_t
ensorflow.py", line 74, in 
raise ImportError(msg)
ImportError: Traceback (most recent call last):
File "C:\Users\Administrator\venv\lib\site-packages\tensorflow\python\pywrap_t
ensorflow.py", line 58, in 
from tensorflow.python.pywrap_tensorflow_internal import *
File "C:\Users\Administrator\venv\lib\site-packages\tensorflow\python\pywrap_t
ensorflow_internal.py", line 28, in 
_pywrap_tensorflow_internal = swig_import_helper()
File "C:\Users\Administrator\venv\lib\site-packages\tensorflow\python\pywrap_t
ensorflow_internal.py", line 24, in swig_import_helper
_mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, descript
ion)
File "C:\Users\Administrator\venv\lib\imp.py", line 243, in load_module
return load_dynamic(name, filename, file)
File "C:\Users\Administrator\venv\lib\imp.py", line 343, in load_dynamic
return _load(spec)
ImportError: DLL load failed with error code -1073741795

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions. Include the entire stack trace
above this error message when asking for help.

**Comment by SmirnovKol** [comment]
I use Windows 7(64 bit), choose tensorflow for CPU only, follow the instructions on https://tensorflow.google.cn/install/pip                  
step by step
I create a virtual environment and use virtualenv install

**Comment by SmirnovKol** [comment]
similar problem, I'm still waiting for a response , I'm  stuck here !!!!

**Comment by youngkiu** [comment]
I have same problem, when I import show error like this
--------------------------------------------------------------------------------
Start Server
Traceback (most recent call last):
  File "C:\Program Files\VATECH\Ez3D-i Auto Tooth Segmentation\pkgs\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Program Files\VATECH\Ez3D-i Auto Tooth Segmentation\pkgs\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Program Files\VATECH\Ez3D-i Auto Tooth Segmentation\pkgs\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "imp.py", line 243, in load_module
  File "imp.py", line 343, in load_dynamic
ImportError: DLL load failed with error code -1073741795

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\VATECH\Ez3D-i Auto Tooth Segmentation\Ez3D-i_Auto_Tooth_Segmentation.launch.pyw", line 32, in <module>
    serve()
  File "C:\Program Files\VATECH\Ez3D-i Auto Tooth Segmentation\pkgs\ai_server\aitoothseg_server.py", line 198, in serve
    teeth_center_image_inst, tooth_volume_mask_inst, sagittal_teeth_area_inst = create_runner_instance()
  File "build\bdist.win-amd64\egg\tooth_segmentation\__main__.py", line 37, in create_runner_instance
  File "build\bdist.win-amd64\egg\tooth_segmentation\common\VTUtil\VTTime.py", line 11, in wrapper
  File "build\bdist.win-amd64\egg\tooth_segmentation\processing\sagittal_teeth_area.py", line 15, in __init__
  File "build\bdist.win-amd64\egg\tooth_segmentation\common\VTUtil\VTImport.py", line 21, in runner
  File "build\bdist.win-amd64\egg\tooth_segmentation\eaf\runner.py", line 11, in <module>
  File "C:\Program Files\VATECH\Ez3D-i Auto Tooth Segmentation\pkgs\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Program Files\VATECH\Ez3D-i Auto Tooth Segmentation\pkgs\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Program Files\VATECH\Ez3D-i Auto Tooth Segmentation\pkgs\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Program Files\VATECH\Ez3D-i Auto Tooth Segmentation\pkgs\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Program Files\VATECH\Ez3D-i Auto Tooth Segmentation\pkgs\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Program Files\VATECH\Ez3D-i Auto Tooth Segmentation\pkgs\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "imp.py", line 243, in load_module
  File "imp.py", line 343, in load_dynamic
ImportError: DLL load failed with error code -1073741795


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by youngkiu** [comment]
I solved my problem.
Reference the below links
https://github.com/tensorflow/tensorflow/issues/17386#issuecomment-370129452
https://stackoverflow.com/questions/49113497/python-tensorflow-import-dll-load-failed

**Comment by ymodak** [comment]
@shyhtzonglee Have you installed the Microsoft Visual C++ 2015 Redistributable Update 3 https://www.tensorflow.org/install/pip#1.-install-the-python-development-environment-on-your-system

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by volkov-maxim** [comment]
> 
> 
> I solved my problem.
> Refer to the below links
> [#17386 (comment)](https://github.com/tensorflow/tensorflow/issues/17386#issuecomment-370129452)
> https://stackoverflow.com/questions/49113497/python-tensorflow-import-dll-load-failed

Thank you @youngkiu! https://stackoverflow.com/a/54702852/4439762 solved my question
