### ISSUE TITLE
facing this error while generating tfrecords in LabelImg

### ISSUE THREAD

**Issue by teffanymae** [tensorflow/tensorflow#25103]
**System information**

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 4.5.12
- Python version: 3.5.2
- GPU model and memory: GPU 0 - Intel(R) HD Graphics 620 |  GPU 1 - NVIDIA GeForce 920MX | 8gb RAM

**(tensorflow1) C:\tensorflow1\models\research\object_detection>python generate_tfrecord.py --csv_input=images\train_labels.csv --image_dir=images\train --output_path=train.record**

Traceback (most recent call last):
  File "C:\Users\New User\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\New User\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\New User\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\New User\Anaconda3\envs\tensorflow1\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\New User\Anaconda3\envs\tensorflow1\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "generate_tfrecord.py", line 17, in <module>
    import tensorflow as tf
  File "C:\Users\New User\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\New User\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\New User\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\New User\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\New User\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\New User\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\New User\Anaconda3\envs\tensorflow1\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\New User\Anaconda3\envs\tensorflow1\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by ymodak** [comment]
The error message says that TensorFlow installation was not successful. Please [install](https://www.tensorflow.org/install/) the latest version of TensorFlow and try again. Thanks!

**Comment by teffanymae** [comment]
but they are updated?

tensorboard                        1.12.2
tensorflow                         1.12.0
tensorflow-gpu                     1.12.0

**Comment by ymodak** [comment]
Can you import TensorFlow successfully in your session?
> import tensorflow as tf
Does this step execute successfully for you?

**Comment by teffanymae** [comment]
in my local python, it can. 

but in Anaconda python, this error appears 

>>> import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\New User\Anaconda3\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\New User\Anaconda3\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\New User\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\New User\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 102, in <module>
    _pywrap_tensorflow_internal.TFE_DEVICE_PLACEMENT_EXPLICIT_swigconstant(_pywrap_tensorflow_internal)
AttributeError: module '_pywrap_tensorflow_internal' has no attribute 'TFE_DEVICE_PLACEMENT_EXPLICIT_swigconstant'

**Comment by teffanymae** [comment]
new error occur when i tried this one

**(tensorflow1) C:\tensorflow1\models\research\object_detection>python generate_tfrecord.py --csv_input=images\train_labels.csv --image_dir=images\train --output_path=train.record**

Traceback (most recent call last):
  File "generate_tfrecord.py", line 17, in <module>
    import tensorflow as tf
  File "C:\tensorflow1\models\research\object_detection\tensorflow.py", line 84, in <module>
    detection_graph = tf.Graph()
AttributeError: module 'tensorflow' has no attribute 'Graph'

**Comment by ymodak** [comment]
Have you named any of python files as 'tensorflow.py'? If yes, Can you please change the name to something else and try again?

The first error is related incorrect loading of TensorFlow module. You can seek out to anaconda community to resolve it. Since TF is successfully loaded from your terminal session.

**Comment by teffanymae** [comment]
Ahh. Yeh, a while ago. But I already changed it.

**(tensorflow1) C:\tensorflow1\models\research\object_detection>python3 generate_tfrecord.py**
'python3' is not recognized as an internal or external command,
operable program or batch file.

**Comment by ymodak** [comment]
It's an environment variable issue. Please refer related stackoverflow links to resolve it.
https://stackoverflow.com/questions/13596505/python-not-working-in-command-prompt
https://github.com/spywhere/Terminality/issues/19
You can reach out to stackoverflow if the problems still persists.

**Comment by dksb** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
