### ISSUE TITLE
Failed to apply delegate: WARNING: op code #43 cannot be handled by this delegate.

### ISSUE THREAD

**Issue by ramtin2080** [tensorflow/tensorflow#25132]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 - Android 5.1
- Mobile device : Nexus  10 - Nexus 7 2012 Android 5.1
- TensorFlow installed from: Binary
- TensorFlow version : b'v1.12.0-rc2-3-ga6d8ffae09' 1.12.0 (0.0.0-gpu-experimental for mobile device)
- Python version: 3.6

**Describe the current behavior**
The tflite demo app crashes on Nexus 7 2012 and Nexus 10 when GPU is selected from device list. There was no such problem on the other devices I tested.

Logs:
```
01-01 05:23:50.161 6539-6558/android.example.com.tflitecamerademo E/AndroidRuntime: FATAL EXCEPTION: CameraBackground
    Process: android.example.com.tflitecamerademo, PID: 6539
    java.lang.IllegalArgumentException: Internal error: Failed to apply delegate: WARNING: op code #43 cannot be handled by this delegate.  Only the first 29 ops will run on the GPU, and the remaining 2 on the CPU.GpuDelegate Prepare: No EGL error, but eglChooseConfig failed.Node number 31 (GpuDelegate) failed to prepare.
    
        at org.tensorflow.lite.NativeInterpreterWrapper.applyDelegate(Native Method)
        at org.tensorflow.lite.NativeInterpreterWrapper.init(NativeInterpreterWrapper.java:83)
        at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:60)
        at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:224)
        at com.example.android.tflitecamerademo.ImageClassifier.recreateInterpreter(ImageClassifier.java:168)
        at com.example.android.tflitecamerademo.ImageClassifier.useGpu(ImageClassifier.java:176)
        at com.example.android.tflitecamerademo.Camera2BasicFragment.lambda$updateActiveModel$0$Camera2BasicFragment(Camera2BasicFragment.java:379)
        at com.example.android.tflitecamerademo.Camera2BasicFragment$$Lambda$0.run(Unknown Source)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.os.HandlerThread.run(HandlerThread.java:61)
01-01 05:23:50.242 6539-6556/android.example.com.tflitecamerademo E/BufferQueueProducer: [unnamed-6539-2] queueBuffer: BufferQueue has been abandoned
01-01 05:23:50.243 124-6580/? E/Surface: queueBuffer: error queuing buffer to SurfaceTexture, -19
01-01 05:23:50.243 124-6580/? E/NvOmxCamera: Queue Buffer Failed. Skipping buffer.
01-01 05:23:50.243 6539-6619/android.example.com.tflitecamerademo E/BufferQueueProducer: [unnamed-6539-2] dequeueBuffer: BufferQueue has been abandoned
01-01 05:23:50.244 124-6580/? E/NvOmxCamera: Dequeue Buffer Failed
01-01 05:23:50.275 6539-6555/android.example.com.tflitecamerademo E/BufferQueueProducer: [unnamed-6539-2] queueBuffer: BufferQueue has been abandoned
01-01 05:23:50.277 124-6580/? E/Surface: queueBuffer: error queuing buffer to SurfaceTexture, -19
01-01 05:23:50.277 124-6580/? E/NvOmxCamera: Queue Buffer Failed. Skipping buffer.
01-01 05:23:50.277 6539-6556/android.example.com.tflitecamerademo E/BufferQueueProducer: [unnamed-6539-2] dequeueBuffer: BufferQueue has been abandoned
01-01 05:23:50.277 124-6580/? E/NvOmxCamera: Dequeue Buffer Failed
01-01 05:23:50.278 6539-6619/android.example.com.tflitecamerademo E/BufferQueueProducer: [unnamed-6539-2] cancelBuffer: BufferQueue has been abandoned
01-01 05:23:50.279 6539-6555/android.example.com.tflitecamerademo E/BufferQueueProducer: [unnamed-6539-2] cancelBuffer: BufferQueue has been abandoned
01-01 05:23:50.380 124-565/? E/NvOmxCamera: Already called release()
01-01 05:25:48.050 473-554/? E/WifiStateMachine: cancelDelayedScan -> 6
```

**Comment by ramtin2080** [comment]
I belive the problem is from OpenGL ES unsupported version. I just noticed that the Nexus 10 OpenGL ES version is 3.0 and TensorFlow Lite delegate requires OpenGL ES 3.1 or higher.
https://www.notebookcheck.net/ARM-Mali-T604-MP4.116274.0.html
It will be great if the support for older versions is added in the future.
