### ISSUE TITLE
Contrib package initialization is broken in 1.13.0.rc0

### ISSUE THREAD

**Issue by dmitrievanthony** [tensorflow/tensorflow#25165]
When I try to use any functionality from `contrib` package I get an exception.

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): **No**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Ubuntu 17.04**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: **-**
- TensorFlow installed from (source or binary): **Binary**
- TensorFlow version (use command below): **b'v1.13.0-rc0-0-g6ce86799c8' 1.13.0-rc0**
- Python version: **3.6.3**
- Bazel version (if compiling from source): **-**
- GCC/Compiler version (if compiling from source): **-**
- CUDA/cuDNN version: **-**
- GPU model and memory: **-**

**Describe the current behavior**

When I try to run `tensorflow/contrib/ignite/python/tests/ignite_dataset_test.py` (and any other code that imports from `contrib`) I get the following exception:
```
Traceback (most recent call last):
  File "ignite_dataset_test.py", line 23, in <module>
    from tensorflow.contrib.ignite import IgniteDataset
  File "/home/gridgain/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/__init__.py", line 40, in <module>
    from tensorflow.contrib import distribute
  File "/home/gridgain/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/distribute/__init__.py", line 33, in <module>
    from tensorflow.contrib.distribute.python.tpu_strategy import TPUStrategy
  File "/home/gridgain/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/distribute/python/tpu_strategy.py", line 27, in <module>
    from tensorflow.contrib.tpu.python.ops import tpu_ops
  File "/home/gridgain/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/tpu/__init__.py", line 73, in <module>
    from tensorflow.contrib.tpu.python.tpu.keras_support import tpu_model as keras_to_tpu_model
  File "/home/gridgain/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/tpu/python/tpu/keras_support.py", line 62, in <module>
    from tensorflow.contrib.tpu.python.tpu import tpu
  File "/home/gridgain/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/tpu/python/tpu/tpu.py", line 24, in <module>
    from tensorflow.contrib.compiler import xla
  File "/home/gridgain/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/compiler/xla.py", line 28, in <module>
    from tensorflow.python.estimator import model_fn as model_fn_lib
  File "/home/gridgain/anaconda3/lib/python3.6/site-packages/tensorflow/python/estimator/__init__.py", line 26, in <module>
    from tensorflow_estimator.python import estimator
  File "/home/gridgain/anaconda3/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/__init__.py", line 25, in <module>
    import tensorflow_estimator.python.estimator.estimator_lib
  File "/home/gridgain/anaconda3/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator_lib.py", line 54, in <module>
    from tensorflow_estimator.python.estimator.mode_keys import ModeKeysV2
  File "/home/gridgain/anaconda3/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/mode_keys.py", line 22, in <module>
    from tensorflow.python.training.mode_keys import ModeKeys
ModuleNotFoundError: No module named 'tensorflow.python.training.mode_keys'
```

**Describe the expected behavior**
No exception

**Code to reproduce the issue**
Install last released version of TensorFlow, `pip3 install tensorflow=1.13.0rc0`. Then run `tensorflow/contrib/ignite/python/tests/start_ignite.sh` to start server. Then run `python3 tensorflow/contrib/ignite/python/tests/ignite_dataset_test.py` and get an exception.

**Other info / logs**
See above.

**Comment by dmitrievanthony** [comment]
Folks, seriously, release `1.13` just broke the whole `contrib` package, all functionality because of error in `contrib/__init__.py`. Can somebody have a look at this issue?

**Comment by jayfurmanek** [comment]
I opened this one: https://github.com/tensorflow/tensorflow/issues/25089
which I think is the root of the problem.

**Comment by jayfurmanek** [comment]
FYI I just closed #25089 . It looks like the Estimator 1.13 branch no longer has https://github.com/tensorflow/tensorflow/commit/8bcc801a7cd748e7d9d47f0f5d7ebd84a2f2eaea  and perhaps has been rebased altogether.

**Comment by dmitrievanthony** [comment]
Okay, @aselle, @case540 thanks for the explanation.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.

**Comment by sachinprasadhs** [comment]
Please do upgrade to a latest Tensorflow version.
Since `contrib` has been depreciated in `Tensorflow 2.x`, you can find the `ignite` under `tfio`.
For more details please visit the documentation on [tfio.ignite](https://www.tensorflow.org/io/api_docs/python/tfio/ignite).
Feel free to open a new issue, if you face any errors.
