### ISSUE TITLE
convert densenet169 model to .tflite model fails, report lack min/max data

### ISSUE THREAD

**Issue by Vincent630** [tensorflow/tensorflow#25191]
### System information
- TensorFlow-gpu 1.12
-OS Platform e.g., Linux Ubuntu 18.
-Python version3.5
- gtx1070
-bash scripts:
echo 'starting convert fake model into tflite model:'${model_name}.....

    tflite_path="./models/${model_name}/fake/model.tflite"

    test -f ${tflite_path} || tflite_convert --output_file=./models/${model_name}/fake/model.tflite \
                    --graph_def_file=./models/${model_name}/fake/model.pb \
                        --inference_type=QUANTIZED_UINT8 \
                            --input_arrays=input \
                            --output_arrays=${model_output} \
                            --mean_values=${mean_values} \
                            --std_dev_values=${std_dev_values}

-report nessage:
Traceback (most recent call last):
  File "/tflite_convert", line 11, in <module>
    sys.exit(main())
  File "/home/venv/lib/python3.5/site-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 412, in main
    app.run(main=run_main, argv=sys.argv[:1])
  File "/home/venv/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/home/venv/lib/python3.5/site-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 408, in run_main
    _convert_model(tflite_flags)
  File "/home/venv/lib/python3.5/site-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 162, in _convert_model
    output_data = converter.convert()
  File "/home/venv/lib/python3.5/site-packages/tensorflow/contrib/lite/python/lite.py", line 453, in convert
    **converter_kwargs)
  File "/home/venv/lib/python3.5/site-packages/tensorflow/contrib/lite/python/convert.py", line 342, in toco_convert_impl
    input_data.SerializeToString())
  File "/home/venv/lib/python3.5/site-packages/tensorflow/contrib/lite/python/convert.py", line 135, in toco_convert_protos
    (stdout, stderr))
RuntimeError: TOCO failed see console for info.
b"2019-01-24 11:24:42.409109: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 2871 operators, 4306 arrays (0 quantized)\n2019-01-24 11:24:42.496442: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 2871 operators, 4306 arrays (0 quantized)\n2019-01-24 11:24:43.560215: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 1: 514 operators, 1027 arrays (1 quantized)\n2019-01-24 11:24:43.575464: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before pre-quantization graph transformations: 514 operators, 1027 arrays (1 quantized)\n2019-01-24 11:24:43.584665: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] After pre-quantization graph transformations pass 1: 430 operators, 943 arrays (1 quantized)\n2019-01-24 11:24:43.594373: F tensorflow/contrib/lite/toco/tooling_util.cc:1634] Array densenet169/dense_block1/conv_block1/x1/BatchNorm/FusedBatchNorm_mul_0, which is an input to the Add operator producing the output array densenet169/dense_block1/conv_block1/x1/Relu, is lacking min/max data, which is necessary for quantization. If accuracy matters, either target a non-quantized output format, or run quantized training with your model from a floating point checkpoint to change the input graph to contain min/max information. If you don't care about accuracy, you can pass --default_ranges_min= and --default_ranges_max= for easy experimentation.\nAborted (core dumped)\n"
None

when i convert the densenet .pb file to .tflite and i failed ,maybe that because lack of min/max value but i not sure how to fix this ,i there anyone who have get this problem or have any solution for this problem ?please let me know and i will appriciate it.

**Comment by shashishekhar** [comment]
@Vincent630 : You are correct it is due to missing minimum and maximum values. For quantization you can get this information by:
1. Doing [quantized training](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/quantize/README.md) this maybe hard since you may need to change the training code and retrain your model but this will give you better accuracy.
2. The other option is [post training quantization](https://www.tensorflow.org/lite/performance/post_training_quantization] which is simpler but may not give you as good accuracy as quantized training can.

Since you are using densenet, we also have similar quantized models available in [model repo](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/models.md)

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by shashishekhar** [comment]
Closing due to inactivity, @Vincent630 : please ping back if this is still an issue.
