### ISSUE TITLE
ImportError: cannot import name abs

### ISSUE THREAD

**Issue by vyraun** [tensorflow/tensorflow#25207]
Hi, I am getting the error while importing tensorflow:

$ python
Python 2.7.15 |Anaconda custom (64-bit)| (default, Dec 14 2018, 19:04:19) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vraunak/anaconda2/envs/py27/lib/python2.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/vraunak/anaconda2/envs/py27/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 88, in <module>
    from tensorflow.python import keras
  File "/home/vraunak/anaconda2/envs/py27/lib/python2.7/site-packages/tensorflow/python/keras/__init__.py", line 24, in <module>
    from tensorflow.python.keras import activations
  File "/home/vraunak/anaconda2/envs/py27/lib/python2.7/site-packages/tensorflow/python/keras/activations/__init__.py", line 22, in <module>
    from tensorflow.python.keras._impl.keras.activations import elu
  File "/home/vraunak/anaconda2/envs/py27/lib/python2.7/site-packages/tensorflow/python/keras/_impl/keras/__init__.py", line 21, in <module>
    from tensorflow.python.keras._impl.keras import activations
  File "/home/vraunak/anaconda2/envs/py27/lib/python2.7/site-packages/tensorflow/python/keras/_impl/keras/activations.py", line 23, in <module>
    from tensorflow.python.keras._impl.keras import backend as K
  File "/home/vraunak/anaconda2/envs/py27/lib/python2.7/site-packages/tensorflow/python/keras/_impl/keras/backend.py", line 36, in <module>
    from tensorflow.python.layers import base as tf_base_layers
  File "/home/vraunak/anaconda2/envs/py27/lib/python2.7/site-packages/tensorflow/python/layers/base.py", line 25, in <module>
    from tensorflow.python.keras.engine import base_layer
  File "/home/vraunak/anaconda2/envs/py27/lib/python2.7/site-packages/tensorflow/python/keras/engine/__init__.py", line 23, in <module>
    from tensorflow.python.keras.engine.base_layer import InputSpec
  File "/home/vraunak/anaconda2/envs/py27/lib/python2.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 35, in <module>
    from tensorflow.python.keras import backend
  File "/home/vraunak/anaconda2/envs/py27/lib/python2.7/site-packages/tensorflow/python/keras/backend/__init__.py", line 22, in <module>
    from tensorflow.python.keras._impl.keras.backend import abs
ImportError: cannot import name abs

Removing protobuf and reinstalling still gives the same error.

**System information**
- Linux CentOS
- Python version: 2.7 tensorflow 1.12.0 
- Installed using conda

**Comment by ymodak** [comment]
Can you try,
``` python 
pip install --upgrade keras
```

**Comment by vyraun** [comment]
@ymodak thanks, it got resolved but now I am getting https://github.com/tensorflow/tensorflow/issues/25210. please take a look. thanks.
