### ISSUE TITLE
Native TF methods not found Exception (Installed as System Apps)

### ISSUE THREAD

**Issue by chetu97** [tensorflow/tensorflow#25229]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_templateem>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Galaxy S6 Edge

**Describe the problem**

<em>I am making an extension of the demo app which requires the app to be installed as a system app in the "priv-app" of the device. I have not changed anything in the demo app itself but I still get the following error whenever I open the TF detect app.</em>

```
2019-01-27 20:29:19.235 8201-8201/? E/art: No implementation found for long org.tensorflow.contrib.android.RunStats.allocate() (tried Java_org_tensorflow_contrib_android_RunStats_allocate and Java_org_tensorflow_contrib_android_RunStats_allocate__)
2019-01-27 20:29:19.236 8201-8201/? I/TensorFlowInferenceInterface: TensorFlow native methods not found, attempting to load via tensorflow_inference
2019-01-27 20:29:19.238 8201-8201/? D/AndroidRuntime: Shutting down VM
2019-01-27 20:29:19.239 8201-8201/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.tensorflow.demo, PID: 8201
    java.lang.RuntimeException: Native TF methods not found; check that the correct native libraries are present in the APK.
        at org.tensorflow.contrib.android.TensorFlowInferenceInterface.prepareNativeRuntime(TensorFlowInferenceInterface.java:544)
        at org.tensorflow.contrib.android.TensorFlowInferenceInterface.<init>(TensorFlowInferenceInterface.java:60)
        at org.tensorflow.demo.TensorFlowObjectDetectionAPIModel.create(TensorFlowObjectDetectionAPIModel.java:97)
        at org.tensorflow.demo.DetectorActivity.onPreviewSizeChosen(DetectorActivity.java:167)
        at org.tensorflow.demo.CameraActivity$5.onPreviewSizeChosen(CameraActivity.java:429)
        at org.tensorflow.demo.CameraConnectionFragment.setUpCameraOutputs(CameraConnectionFragment.java:454)
        at org.tensorflow.demo.CameraConnectionFragment.openCamera(CameraConnectionFragment.java:462)
        at org.tensorflow.demo.CameraConnectionFragment.access$000(CameraConnectionFragment.java:66)
        at org.tensorflow.demo.CameraConnectionFragment$1.onSurfaceTextureAvailable(CameraConnectionFragment.java:101)
        at android.view.TextureView.getHardwareLayer(TextureView.java:389)
        at android.view.TextureView.draw(TextureView.java:338)
        at android.view.View.updateDisplayListIfDirty(View.java:17296)
        at android.view.View.draw(View.java:18080)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3966)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3752)
        at android.view.View.updateDisplayListIfDirty(View.java:17291)
        at android.view.View.draw(View.java:18080)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3966)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3752)
        at android.view.View.draw(View.java:18321)
        at android.view.View.updateDisplayListIfDirty(View.java:17296)
        at android.view.View.draw(View.java:18080)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3966)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3752)
        at android.view.View.updateDisplayListIfDirty(View.java:17291)
        at android.view.View.draw(View.java:18080)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3966)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3752)
        at android.view.View.updateDisplayListIfDirty(View.java:17291)
        at android.view.View.draw(View.java:18080)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3966)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3752)
        at android.view.View.draw(View.java:18321)
        at com.android.internal.policy.DecorView.draw(DecorView.java:919)
        at android.view.View.updateDisplayListIfDirty(View.java:17296)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:692)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:698)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:806)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3128)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2924)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2516)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1515)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7091)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:927)
        at android.view.Choreographer.doCallbacks(Choreographer.java:702)
        at android.view.Choreographer.doFrame(Choreographer.java:638)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:913)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
2019-01-27 20:29:24.764 8201-8210/org.tensorflow.demo E/System: Uncaught exception thrown by finalizer
2019-01-27 20:29:24.768 8201-8210/org.tensorflow.demo E/System: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.tensorflow.Session.close()' on a null object reference
        at org.tensorflow.contrib.android.TensorFlowInferenceInterface.close(TensorFlowInferenceInterface.java:276)
        at org.tensorflow.contrib.android.TensorFlowInferenceInterface.finalize(TensorFlowInferenceInterface.java:287)
        at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:222)
        at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:209)
        at java.lang.Thread.run(Thread.java:762)
```

**Provide the exact sequence of commands / steps that you executed before running into the problem**
Steps :
1. Build Apk(s)
2. Copy the apk to the priv-app of the device
3. Restart the device
4. Error Occurs on opening of TF Detect app

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by jdduke** [comment]
You'll need to make sure the native shared libraries are in a location where they can be properly loaded. If you're using a custom shared library name, you'll need to manually call `System.loadLibrary()` first. In any case, TensorFlow Mobile has been officially deprecated in favor of TensorFlow Lite.
