### ISSUE TITLE
how to test data stream in speech_commands project?

### ISSUE THREAD

**Issue by ucasiggcas** [tensorflow/tensorflow#25242]
Dear,
I have a question,in the [project](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/speech_commands)
when I test the wave data decode by [librosa.load](https://github.com/librosa/librosa/blob/master/librosa/core/audio.py) not read by open in the row of 96 from the [script](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/speech_commands/label_wav.py)
it ups bug,
`Traceback (most recent call last):
  File "D:\python\lib\site-packages\tensorflow\python\client\session.py", line 1334, in _do_call
    return fn(*args)
  File "D:\python\lib\site-packages\tensorflow\python\client\session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "D:\python\lib\site-packages\tensorflow\python\client\session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InternalError: Unable to get element as bytes.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/python/speechtf/label_wav4_6.py", line 41, in <module>
    y_pred,_=run_graph(graph,y)
  File "D:/python/speechtf/label_wav4_6.py", line 14, in run_graph
    predictions, = sess.run(softmax_tensor, {'wav_data:0': wav_data})
  File "D:\python\lib\site-packages\tensorflow\python\client\session.py", line 929, in run
    run_metadata_ptr)
  File "D:\python\lib\site-packages\tensorflow\python\client\session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "D:\python\lib\site-packages\tensorflow\python\client\session.py", line 1328, in _do_run
    run_metadata)
  File "D:\python\lib\site-packages\tensorflow\python\client\session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Unable to get element as bytes.`

So how do I test data stream after decode by librosa.load but not wav file read by open ?
Could U help me,Please?
Any advice or suggestion will be great!
Thx

**Comment by jvishnuvardhan** [comment]
@ucasiggcas Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. Github is mainly for addressing bugs in installation and performance. Thanks!

If you think it is not a support question, then please fill system [template](https://github.com/tensorflow/tensorflow/issues/new?template=00-bug-performance-issue.md) and provide steps and a code to reproduce the error. Thanks
