### ISSUE TITLE
bazel build aot armeabi-v7a so failed

### ISSUE THREAD

**Issue by sundayxcn** [tensorflow/tensorflow#25275]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
macOS 10.13.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
binary
- TensorFlow version:
1.12.0
- Python version:
3.6.2
- Installed using virtualenv? pip? conda?:
conda
- Bazel version (if compiling from source):
0.21.0
- ndk version
14b
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
no
- GPU model and memory:

**Describe the problem**

I have tried to perform a simple demo in //tensorflow/compiler/aot/test/test_graph_tfmatmul.pb by using this command:
bazel build //tensorflow/compiler/aot/tests:my_library
and have succeeded in the building procedure.

However, when I tried to generate a .so file for an android project I got failed. The command I used is as below:
```text
bazel build --crosstool_top=@androidndk//:default_crosstool  --cpu=armeabi-v7a  --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --cxxopt="-std=c++11" //tensorflow/compiler/aot/tests:my_library
```
I don't know how to fix the problem. Please help.  The error message is as below:

```text
/private/var/tmp/_bazel_sunday/7a01d1437f77ea8b21ffc614971e2517/external/mkl_dnn/BUILD.bazel:71:1: C++ compilation of rule '@mkl_dnn//:mkldnn_single_threaded' failed (Exit 1)
In file included from external/mkl_dnn/src/common/utils.cpp:22:
In file included from external/androidndk/ndk/toolchains/llvm/prebuilt/darwin-x86_64/bin/../lib64/clang/3.8.275480/include/xmmintrin.h:27:
external/androidndk/ndk/toolchains/llvm/prebuilt/darwin-x86_64/bin/../lib64/clang/3.8.275480/include/mmintrin.h:47:5: error: use of undeclared identifier '__builtin_ia32_emms'; did you mean '__builtin_isless'?
    __builtin_ia32_emms();
    ^
external/androidndk/ndk/toolchains/llvm/prebuilt/darwin-x86_64/bin/../lib64/clang/3.8.275480/include/mmintrin.h:47:5: note: '__builtin_isless' declared here
external/androidndk/ndk/toolchains/llvm/prebuilt/darwin-x86_64/bin/../lib64/clang/3.8.275480/include/mmintrin.h:47:25: error: too few arguments to function call, expected 2, have 0
    __builtin_ia32_emms();
                        ^
external/androidndk/ndk/toolchains/llvm/prebuilt/darwin-x86_64/bin/../lib64/clang/3.8.275480/include/mmintrin.h:64:19: error: use of undeclared identifier '__builtin_ia32_vec_init_v2si'
    return (__m64)__builtin_ia32_vec_init_v2si(__i, 0);
                  ^
external/androidndk/ndk/toolchains/llvm/prebuilt/darwin-x86_64/bin/../lib64/clang/3.8.275480/include/mmintrin.h:81:12: error: use of undeclared identifier '__builtin_ia32_vec_ext_v2si'
    return __builtin_ia32_vec_ext_v2si((__v2si)__m, 0);
           ^
external/androidndk/ndk/toolchains/llvm/prebuilt/darwin-x86_64/bin/../lib64/clang/3.8.275480/include/mmintrin.h:143:19: error: use of undeclared identifier '__builtin_ia32_packsswb'
    return (__m64)__builtin_ia32_packsswb((__v4hi)__m1, (__v4hi)__m2);
                  ^
external/androidndk/ndk/toolchains/llvm/prebuilt/darwin-x86_64/bin/../lib64/clang/3.8.275480/include/mmintrin.h:173:19: error: use of undeclared identifier '__builtin_ia32_packssdw'
    return (__m64)__builtin_ia32_packssdw((__v2si)__m1, (__v2si)__m2);
                  ^
external/androidndk/ndk/toolchains/llvm/prebuilt/darwin-x86_64/bin/../lib64/clang/3.8.275480/include/mmintrin.h:203:19: error: use of undeclared identifier '__builtin_ia32_packuswb'
    return (__m64)__builtin_ia32_packuswb((__v4hi)__m1, (__v4hi)__m2);
                  ^
external/androidndk/ndk/toolchains/llvm/prebuilt/darwin-x86_64/bin/../lib64/clang/3.8.275480/include/mmintrin.h:230:19: error: use of undeclared identifier '__builtin_ia32_punpckhbw'
    return (__m64)__builtin_ia32_punpckhbw((__v8qi)__m1, (__v8qi)__m2);
                  ^
external/androidndk/ndk/toolchains/llvm/prebuilt/darwin-x86_64/bin/../lib64/clang/3.8.275480/include/mmintrin.h:253:19: error: use of undeclared identifier '__builtin_ia32_punpckhwd'
    return (__m64)__builtin_ia32_punpckhwd((__v4hi)__m1, (__v4hi)__m2);
                  ^
external/androidndk/ndk/toolchains/llvm/prebuilt/darwin-x86_64/bin/../lib64/clang/3.8.275480/include/mmintrin.h:274:19: error: use of undeclared identifier '__builtin_ia32_punpckhdq'
    return (__m64)__builtin_ia32_punpckhdq((__v2si)__m1, (__v2si)__m2);
                  ^
external/androidndk/ndk/toolchains/llvm/prebuilt/darwin-x86_64/bin/../lib64/clang/3.8.275480/include/mmintrin.h:301:19: error: use of undeclared identifier '__builtin_ia32_punpcklbw'
    return (__m64)__builtin_ia32_punpcklbw((__v8qi)__m1, (__v8qi)__m2);
                  ^
external/androidndk/ndk/toolchains/llvm/prebuilt/darwin-x86_64/bin/../lib64/clang/3.8.275480/include/mmintrin.h:324:19: error: use of undeclared identifier '__builtin_ia32_punpcklwd'
    return (__m64)__builtin_ia32_punpcklwd((__v4hi)__m1, (__v4hi)__m2);
                  ^
external/androidndk/ndk/toolchains/llvm/prebuilt/darwin-x86_64/bin/../lib64/clang/3.8.275480/include/mmintrin.h:345:19: error: use of undeclared identifier '__builtin_ia32_punpckldq'
    return (__m64)__builtin_ia32_punpckldq((__v2si)__m1, (__v2si)__m2);
                  ^
external/androidndk/ndk/toolchains/llvm/prebuilt/darwin-x86_64/bin/../lib64/clang/3.8.275480/include/mmintrin.h:366:19: error: use of undeclared identifier '__builtin_ia32_paddb'; did you mean '__builtin_arm_qadd'?
    return (__m64)__builtin_ia32_paddb((__v8qi)__m1, (__v8qi)__m2);
                  ^
external/androidndk/ndk/toolchains/llvm/prebuilt/darwin-x86_64/bin/../lib64/clang/3.8.275480/include/mmintrin.h:366:19: note: '__builtin_arm_qadd' declared here
external/androidndk/ndk/toolchains/llvm/prebuilt/darwin-x86_64/bin/../lib64/clang/3.8.275480/include/mmintrin.h:366:40: error: cannot initialize a parameter of type 'int' with an rvalue of type '__v8qi' (vector of 8 'char' values)
    return (__m64)__builtin_ia32_paddb((__v8qi)__m1, (__v8qi)__m2);
                                       ^~~~~~~~~~~~
external/androidndk/ndk/toolchains/llvm/prebuilt/darwin-x86_64/bin/../lib64/clang/3.8.275480/include/mmintrin.h:387:19: error: use of undeclared identifier '__builtin_ia32_paddw'; did you mean '__builtin_arm_qadd'?
    return (__m64)__builtin_ia32_paddw((__v4hi)__m1, (__v4hi)__m2);
                  ^
external/androidndk/ndk/toolchains/llvm/prebuilt/darwin-x86_64/bin/../lib64/clang/3.8.275480/include/mmintrin.h:366:19: note: '__builtin_arm_qadd' declared here
    return (__m64)__builtin_ia32_paddb((__v8qi)__m1, (__v8qi)__m2);
                  ^
external/androidndk/ndk/toolchains/llvm/prebuilt/darwin-x86_64/bin/../lib64/clang/3.8.275480/include/mmintrin.h:387:40: error: cannot initialize a parameter of type 'int' with an rvalue of type '__v4hi' (vector of 4 'short' values)
    return (__m64)__builtin_ia32_paddw((__v4hi)__m1, (__v4hi)__m2);
                                       ^~~~~~~~~~~~
external/androidndk/ndk/toolchains/llvm/prebuilt/darwin-x86_64/bin/../lib64/clang/3.8.275480/include/mmintrin.h:408:19: error: use of undeclared identifier '__builtin_ia32_paddd'; did you mean '__builtin_arm_qadd'?
    return (__m64)__builtin_ia32_paddd((__v2si)__m1, (__v2si)__m2);
                  ^
external/androidndk/ndk/toolchains/llvm/prebuilt/darwin-x86_64/bin/../lib64/clang/3.8.275480/include/mmintrin.h:366:19: note: '__builtin_arm_qadd' declared here
    return (__m64)__builtin_ia32_paddb((__v8qi)__m1, (__v8qi)__m2);
                  ^
external/androidndk/ndk/toolchains/llvm/prebuilt/darwin-x86_64/bin/../lib64/clang/3.8.275480/include/mmintrin.h:408:40: error: cannot initialize a parameter of type 'int' with an rvalue of type '__v2si' (vector of 2 'int' values)
    return (__m64)__builtin_ia32_paddd((__v2si)__m1, (__v2si)__m2);
                                       ^~~~~~~~~~~~
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
Target //tensorflow/compiler/aot/tests:my_library failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1.407s, Critical Path: 0.28s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```
the content of the bazel BUILD file:
```text
load("//tensorflow/compiler/aot:tfcompile.bzl", "tf_library")

tf_library(
    name = "test_graph_tfmatmul",
    cpp_class = "foo::bar::MatMulComp",
    graph = "test_graph_tfmatmul.pb",
    config = "test_graph_tfmatmul.config.pbtxt",
)

cc_library(
    name = "my_library",
    srcs = [
        "my_code.cc",  # include test_graph_tfmatmul.h to access the generated header
    ],
    hdrs = ["my_code.h"],
    deps = [
        ":test_graph_tfmatmul",  # link in the generated object file
        "//third_party/eigen3",
    ],
    linkopts = [
        "-lpthread",
    ]
)
```

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by jvishnuvardhan** [comment]
@sundayxcn Could you provide more details on the context and the issue? Thanks!

**Comment by sundayxcn** [comment]
@freedomtan , Hi, thanks for your quick reply. I have adopted your suggestions and built the .so library successfully a moment ago. However, while I am trying calling the **compare** method mentioned, see above **step 2.1** in before attached script. The Android Studio gives the error traceback like following:
```text
  Process: com.example.sunday.ndkdemo, PID: 28571
    java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "ceilf" referenced by "/data/app/com.example.sunday.ndkdemo-B05bPAF3wQDe9L865kV88Q==/lib/arm/libmylib.so"...
        at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
        at java.lang.System.loadLibrary(System.java:1672)
        at com.example.sunday.ndkdemo.MainActivity.<clinit>(MainActivity.java:11)
        at java.lang.Class.newInstance(Native Method)
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:69)
```
I believe this is caused by the lack of **ceilf** method in my .so library.  But in the **compare** method, I only easy imported ''foo::bar::MatMulComp matmul'' and did some simple calculations. Now, I am confused why there were concerned about the **ceilf** in my library. Could you help me to check this problem. please? Hope to hear from you soon! Thanks in advance!

**Comment by sundayxcn** [comment]
> `ceilf()` is a standard C library function, should be in `libm`. Add something like `linkopts="-lm"` to your `cc_binary(....)` could help. Add `-s` to your bazel build command:
> 
> ```
> bazel build --config android_arm \
> --cxxopt=-std=c++11 --cxxopt=-Wno-c++11-narrowing \
> //tensorflow/compiler/aot/tests:my_library -s
> ```
> Then you can learn why you got a huge .so.
@freedomtan  According to your advice, i change the cc_binary,
```text
cc_binary(
    name = "libmy_library.so",
    linkshared=True,
    srcs = [
        "my_code.cc", 
        "my_code.h", 
    ],
    deps = [
        ":test_graph_tfmatmul",
        "//third_party/eigen3",
    ],
    linkopts=["-lm"],
)
```

There are different error:
```text
java.lang.UnsatisfiedLinkError: dlopen failed: library "../../../../src/main/jniLibs/armeabi/libmy_library.so" not found
        at java.lang.Runtime.loadLibrary0(Runtime.java:989)
        at java.lang.System.loadLibrary(System.java:1562)
        at com.example.sunday.ndkdemo.MainActivity.<clinit>(MainActivity.java:12)
        at java.lang.Class.newInstance(Native Method)
```
but my android project  configuration files still unchanged,only change the libmy_library.so . 
I tested it several times. if i remove linkopts=["-lm"], 
errmsg:
```text
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "ceilf" referenced by "/data/app/com.example.sunday.ndkdemo-B05bPAF3wQDe9L865kV88Q==/lib/arm/libmylib.so"...
```
if i restore linkopts=["-lm"], 
errmsg:
```text
java.lang.UnsatisfiedLinkError: dlopen failed: library "../../../../src/main/jniLibs/armeabi/libmy_library.so" not found
```
so I'm sure there's still a problem about so. Please check it for me. thank you...

**Comment by jdduke** [comment]
Are there any additional logcat messages surrounding the dlopen failure?

**Comment by sundayxcn** [comment]
@jdduke @freedomtan 
the dlopen message has no more message. and i change the bazel command :
```text
bazel build --crosstool_top=//external:android/crosstool --cpu=armeabi-v7a --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --cxxopt=-std=c++11 --cxxopt=-Wno-c++11-narrowing //tensorflow/compiler/aot/tests:my_library
```
show linking error:
```text
note: 'CFURLCreateDataAndPropertiesFromResource' has been explicitly marked deprecated here
Boolean CFURLCreateDataAndPropertiesFromResource(CFAllocatorRef alloc, CFURLRef url, CFDataRef *resourceData, CFDictionaryRef *properties, CFArrayRef desiredProperties, SInt32 *errorCode) API_DEPRECATED("For resource data, use the CFReadStream API. For file resource properties, use CFURLCopyResourcePropertiesForKeys.", macos(10.0,10.9), ios(2.0,7.0), watchos(2.0,2.0), tvos(9.0,9.0));
        ^
1 warning generated.
INFO: From Linking external/curl/libcurl.a [for host]:
/Library/Developer/CommandLineTools/usr/bin/libtool: file: bazel-out/host/bin/external/curl/_objs/curl/asyn-ares.o has no symbols
/Library/Developer/CommandLineTools/usr/bin/libtool: file: bazel-out/host/bin/external/curl/_objs/curl/curl_multibyte.o has no symbols
/Library/Developer/CommandLineTools/usr/bin/libtool: file: bazel-out/host/bin/external/curl/_objs/curl/curl_rtmp.o has no symbols
/Library/Developer/CommandLineTools/usr/bin/libtool: file: bazel-out/host/bin/external/curl/_objs/curl/curl_sspi.o has no symbols
/Library/Developer/CommandLineTools/usr/bin/libtool: file: bazel-out/host/bin/external/curl/_objs/curl/curl_threads.o has no symbols
/Library/Developer/CommandLineTools/usr/bin/libtool: file: bazel-out/host/bin/external/curl/_objs/curl/hostasyn.o has no symbols
/Library/Developer/CommandLineTools/usr/bin/libtool: file: bazel-out/host/bin/external/curl/_objs/curl/hostcheck.o has no symbols
/Library/Developer/CommandLineTools/usr/bin/libtool: file: bazel-out/host/bin/external/curl/_objs/curl/hostip4.o has no symbols
/Library/Developer/CommandLineTools/usr/bin/libtool: file: bazel-out/host/bin/external/curl/_objs/curl/inet_pton.o has no symbols
/Library/Developer/CommandLineTools/usr/bin/libtool: file: bazel-out/host/bin/external/curl/_objs/curl/krb5.o has no symbols
/Library/Developer/CommandLineTools/usr/bin/libtool: file: bazel-out/host/bin/external/curl/_objs/curl/md4.o has no symbols
/Library/Developer/CommandLineTools/usr/bin/libtool: file: bazel-out/host/bin/external/curl/_objs/curl/memdebug.o has no symbols
/Library/Developer/CommandLineTools/usr/bin/libtool: file: bazel-out/host/bin/external/curl/_objs/curl/nwlib.o has no symbols
/Library/Developer/CommandLineTools/usr/bin/libtool: file: bazel-out/host/bin/external/curl/_objs/curl/nwos.o has no symbols
/Library/Developer/CommandLineTools/usr/bin/libtool: file: bazel-out/host/bin/external/curl/_objs/curl/security.o has no symbols
/Library/Developer/CommandLineTools/usr/bin/libtool: file: bazel-out/host/bin/external/curl/_objs/curl/strtok.o has no symbols
INFO: From Compiling tensorflow/core/grappler/optimizers/pin_to_host_optimizer.cc [for host]:
In file included from tensorflow/core/grappler/optimizers/pin_to_host_optimizer.cc:16:
./tensorflow/core/grappler/optimizers/pin_to_host_optimizer.h:56:26: warning: private field 'opt_level_' is not used [-Wunused-private-field]
  RewriterConfig::Toggle opt_level_;
                         ^
1 warning generated.
INFO: From Linking tensorflow/compiler/aot/tfcompile [for host]:
ld: warning: text-based stub file /System/Library/Frameworks//IOKit.framework/IOKit.tbd and library file /System/Library/Frameworks//IOKit.framework/IOKit are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks//CoreFoundation.framework/CoreFoundation.tbd and library file /System/Library/Frameworks//CoreFoundation.framework/CoreFoundation are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks//Security.framework/Security.tbd and library file /System/Library/Frameworks//Security.framework/Security are out of sync. Falling back to library file for linking.
INFO: From Executing genrule //tensorflow/compiler/aot/tests:gen_test_graph_tfmatmul:
2019-02-18 13:19:30.705553: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.2 AVX
ERROR: /Users/sunday/tensorflow/tensorflow/compiler/aot/tests/BUILD:15:1: Linking of rule '//tensorflow/compiler/aot/tests:my_library' failed (Exit 1)
clang: error: no such file or directory: 'libmy_library.so'
Target //tensorflow/compiler/aot/tests:my_library failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1399.023s, Critical Path: 231.09s
INFO: 2563 processes: 2563 local.

```
but the tensorflow binary is from resource code compile 
```text
bazel build  --copt=-msse4.1 --copt=-msse4.2 --copt=-mavx --copt=-mavx2 //tensorflow/tools/pip_package:build_pip_package
```

**Comment by freedomtan** [comment]
apparently, it failed because of this line
```
java.lang.UnsatisfiedLinkError: dlopen failed: library "../../../../src/main/jniLibs/armeabi/libmy_library.so" not found
```
This probably is caused by some link flag which wrote `../../../../src/main/jniLibs/armeabi/libmy_library.so` into your `libmy_library.so`. You may want to check what link flags are used (with `-s` in bazel command) and inspect your `libmy_library.so` (by something like `readelf -a`) before using it. If you don't how to do these, you may want to check with your local compile / tool chain expert to get quick response.

**Comment by sundayxcn** [comment]
@freedomtan  @jdduke please help my check my latest action,thank you !!
the message  
```text
2019-02-18 13:19:30.705553: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.2 AVX 
```
is that mean the aot cant support arm-v7a?

**Comment by jdduke** [comment]
> bazel build --crosstool_top=//external:android/crosstool --cpu=armeabi-v7a --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --cxxopt=-std=c++11 --cxxopt=-Wno-c++11-narrowing //tensorflow/compiler/aot/tests:my_library

Have you run `./configure` and located the Android toolchain from your root checkout directory?

> clang: error: no such file or directory: 'libmy_library.so'

This looks like an issue with your build rule, are you referring to the .so directly or indirectly from the .so target itself?

**Comment by freedomtan** [comment]
@sundayxcn I checked output .so of bazel, it won't cause
```
java.lang.UnsatisfiedLinkError: dlopen failed: library "../../../../src/main/jniLibs/armeabi/libmy_library.so" not found

```
Should be caused by your settings when you built your .so in Android Studio. Surely you won't find ``` "../../../../src/main/jniLibs/armeabi/libmy_library.so"``` on your Android devices. The path is supposed to be used during linking time on your host machine only.
