### ISSUE TITLE
tensorflow.python.framework.errors_impl.InternalError: tensorflow/core/kernels/cuda_solvers.cc:803: cuBlas call failed status = 13

### ISSUE THREAD

**Issue by OxInsky** [tensorflow/tensorflow#25274]
Hello ,I met a mistake when using tensorflow 1.10.0 as follows. I install tensorflow 1.10.0 with command `pip install tensorflow-gpu ==1.10.0` 
More information:
system:ubuntu 16.04
GPU：RTX2080
CUDA: 9.0
cudnn:7.4.1
python: 2.7/3.6
When run the code ,we get a mistake about cuBlas and the status is 13. We know little about  this and we try using docker to run this but failed.Can you help me? Thanks!  
Code:
```
def input_fn_train():
        return input_function(True, flags.data_dir, flags.batch_size,
                              flags.epochs_per_eval, flags.num_parallel_calls,
                              flags.multi_gpu)
    if flags.mode == tf.estimator.ModeKeys.EVAL:
        eval_results = estimator.evaluate(input_fn=input_fn_eval,steps=flags.max_train_steps)
        print(eval_results)

    if flags.mode == tf.estimator.ModeKeys.TRAIN:
        for _ in range(flags.train_epochs // flags.epochs_per_eval):
            train_hooks = hooks_helper.get_train_hooks(["LoggingTensorHook"], batch_size=flags.batch_size)

            print('Starting a training cycle.')
            estimator.train(input_fn=input_fn_train,
                            max_steps=flags.max_train_steps)

            print('Starting to evaluate.')
            eval_results = estimator.evaluate(input_fn=input_fn_eval,
                                                steps=flags.max_train_steps)
            print(eval_results)
```

Mistake:
```
2019-01-29 12:12:50.442014: I tensorflow/core/kernels/cuda_solvers.cc:159] Creating CudaSolver handles for stream 0x55bd7c128050
2019-01-29 12:12:53.677220: W tensorflow/core/framework/op_kernel.cc:1275] OP_REQUIRES failed at matrix_inverse_op.cc:191 : Internal: tensorflow/core/kernels/cuda_solvers.cc:803: cuBlas call failed status = 13
Traceback (most recent call last):
  File "/home/qiujia/.pyenv/versions/anaconda3-4.3.1/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1278, in _do_call
    return fn(*args)
  File "/home/qiujia/.pyenv/versions/anaconda3-4.3.1/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1263, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/qiujia/.pyenv/versions/anaconda3-4.3.1/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InternalError: tensorflow/core/kernels/cuda_solvers.cc:803: cuBlas call failed status = 13
	 [[Node: s2/MatrixInverse = MatrixInverse[T=DT_FLOAT, adjoint=false, _device="/job:localhost/replica:0/task:0/device:GPU:0"](s2/Reshape_2)]]
	 [[Node: s2/transform/ImageProjectiveTransform/_2343 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1510_s2/transform/ImageProjectiveTransform", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "DAN_V2.py", line 141, in <module>
    tf.app.run(argv=sys.argv)
  File "/home/qiujia/.pyenv/versions/anaconda3-4.3.1/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "DAN_V2.py", line 137, in main
    dan_run_loop.dan_main(flags,vgg16_model_fn,input_function)
  File "/home/qiujia/DAN/DAN_V2/dan_run_loop.py", line 203, in dan_main
    max_steps=flags.max_train_steps)
  File "/home/qiujia/.pyenv/versions/anaconda3-4.3.1/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 376, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/qiujia/.pyenv/versions/anaconda3-4.3.1/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1145, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/home/qiujia/.pyenv/versions/anaconda3-4.3.1/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1173, in _train_model_default
    saving_listeners)
  File "/home/qiujia/.pyenv/versions/anaconda3-4.3.1/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1451, in _train_with_estimator_spec
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/home/qiujia/.pyenv/versions/anaconda3-4.3.1/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 583, in run
    run_metadata=run_metadata)
  File "/home/qiujia/.pyenv/versions/anaconda3-4.3.1/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1059, in run
    run_metadata=run_metadata)
  File "/home/qiujia/.pyenv/versions/anaconda3-4.3.1/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1150, in run
    raise six.reraise(*original_exc_info)
  File "/home/qiujia/.pyenv/versions/anaconda3-4.3.1/lib/python3.6/site-packages/six.py", line 686, in reraise
    raise value
  File "/home/qiujia/.pyenv/versions/anaconda3-4.3.1/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1135, in run
    return self._sess.run(*args, **kwargs)
  File "/home/qiujia/.pyenv/versions/anaconda3-4.3.1/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1207, in run
    run_metadata=run_metadata)
  File "/home/qiujia/.pyenv/versions/anaconda3-4.3.1/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 987, in run
    return self._sess.run(*args, **kwargs)
  File "/home/qiujia/.pyenv/versions/anaconda3-4.3.1/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 877, in run
    run_metadata_ptr)
  File "/home/qiujia/.pyenv/versions/anaconda3-4.3.1/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1100, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/qiujia/.pyenv/versions/anaconda3-4.3.1/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1272, in _do_run
    run_metadata)
  File "/home/qiujia/.pyenv/versions/anaconda3-4.3.1/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1291, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: tensorflow/core/kernels/cuda_solvers.cc:803: cuBlas call failed status = 13
	 [[Node: s2/MatrixInverse = MatrixInverse[T=DT_FLOAT, adjoint=false, _device="/job:localhost/replica:0/task:0/device:GPU:0"](s2/Reshape_2)]]
	 [[Node: s2/transform/ImageProjectiveTransform/_2343 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1510_s2/transform/ImageProjectiveTransform", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 's2/MatrixInverse', defined at:
  File "DAN_V2.py", line 141, in <module>
    tf.app.run(argv=sys.argv)
  File "/home/qiujia/.pyenv/versions/anaconda3-4.3.1/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "DAN_V2.py", line 137, in main
    dan_run_loop.dan_main(flags,vgg16_model_fn,input_function)
  File "/home/qiujia/DAN/DAN_V2/dan_run_loop.py", line 203, in dan_main
    max_steps=flags.max_train_steps)
  File "/home/qiujia/.pyenv/versions/anaconda3-4.3.1/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 376, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/qiujia/.pyenv/versions/anaconda3-4.3.1/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1145, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/home/qiujia/.pyenv/versions/anaconda3-4.3.1/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1170, in _train_model_default
    features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
  File "/home/qiujia/.pyenv/versions/anaconda3-4.3.1/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1133, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "DAN_V2.py", line 131, in vgg16_model_fn
    multi_gpu=params['multi_gpu'])
  File "/home/qiujia/DAN/DAN_V2/dan_run_loop.py", line 102, in dan_model_fn
    mean_shape,imgs_mean,imgs_std)
  File "/home/qiujia/DAN/DAN_V2/dan_model.py", line 152, in __call__
    inputs = self.__affine_image(inputs_imgs,r,t)
  File "/home/qiujia/DAN/DAN_V2/dan_model.py", line 78, in __affine_image
    r = tf.matrix_inverse(r)
  File "/home/qiujia/.pyenv/versions/anaconda3-4.3.1/lib/python3.6/site-packages/tensorflow/python/ops/gen_linalg_ops.py", line 1049, in matrix_inverse
    "MatrixInverse", input=input, adjoint=adjoint, name=name)
  File "/home/qiujia/.pyenv/versions/anaconda3-4.3.1/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/qiujia/.pyenv/versions/anaconda3-4.3.1/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "/home/qiujia/.pyenv/versions/anaconda3-4.3.1/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3155, in create_op
    op_def=op_def)
  File "/home/qiujia/.pyenv/versions/anaconda3-4.3.1/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1717, in __init__
    self._traceback = tf_stack.extract_stack()

InternalError (see above for traceback): tensorflow/core/kernels/cuda_solvers.cc:803: cuBlas call failed status = 13
	 [[Node: s2/MatrixInverse = MatrixInverse[T=DT_FLOAT, adjoint=false, _device="/job:localhost/replica:0/task:0/device:GPU:0"](s2/Reshape_2)]]
	 [[Node: s2/transform/ImageProjectiveTransform/_2343 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1510_s2/transform/ImageProjectiveTransform", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
```

**Comment by jvishnuvardhan** [comment]
@OxInsky Could you follow the instructions [here](https://github.com/rnreich/ubuntu-tensorflow-gpu-all-versions) and let us know how it works. I recently used those steps and successfully installed tensorflow-gpu. If you had already resolved the issue, please close the issue or let us know. Thanks!

**Comment by jvishnuvardhan** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by dangjisheng** [comment]
Hello,have you solved this problem?I also meet the same problem.how do you solve this problem?

**Comment by Donald-Su** [comment]
Hi, I meet the same issue, did you solve this issue?

**Comment by cocoakang** [comment]
I met this problem about three moths ago. My trouble code is:
`tf.matrix_inverse(view_mat_model)`
Tensorflow will create a cublas solver for this, and it works well on 1080ti, but 2080ti.
I didn't find a good way to solve this problem, say, finding a good combination of cudnn and cuda version or installing a cudnn patch.
But I finally found a way to avoid that by:
```
with tf.device("/cpu:0"):
    view_mat_for_normal =tf.matrix_inverse(view_mat_model)
```
which move the computation  to cpu.
This works fine with my code and there was no obvious efficiency reduction.

If you got others computation code crashed with cublas, you can let them computed on cpu like above. 

Hope this may help you.

**Comment by cocoakang** [comment]
I discussed this problem with carlkulseng [here](https://devtalk.nvidia.com/default/topic/1049490/container-tensorflow/-op_requires-failed-at-matrix_inverse_op-cc-191-internal-tensorflow-core-kernels-cuda_solvers-cc-803-cublas-call-failed-status-13/?offset=6#5380467)

And the solution given by carlkulseng works fine with me.
@Donald-Su @longmalongma @OxInsky
