### ISSUE TITLE
Models produced by SavedModel.simple_save can't be loaded with saved_model.loader

### ISSUE THREAD

**Issue by csteegz** [tensorflow/tensorflow#25288]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Windows
- TensorFlow installed from (source or binary):
PIP
- TensorFlow version (use command below):
1.12.0/'v1.12.0-rc2-3-ga6d8ffae09'
- Python version:
3.6.2

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**
TF.saved_model.simple_save can't be loaded by tf.saved_model_loader  - it states
```
RuntimeError: MetaGraphDef associated with tags serve could not be found in SavedModel. To inspect available tag-sets in the SavedModel, please use the SavedModel CLI: `saved_model_cli`
```
**Describe the expected behavior**
a model created with tf.saved_model_simple_save can be loaded by using 
tf.saved_model.loader.load(sess, tf.saved_model.tag_constants.SERVING, "./model")

**Code to reproduce the issue**
```
import tensorflow as tf
import numpy

learning_rate = 0.01
training_epochs = 2

# Training Data
train_X = numpy.asarray([3.3, 4.4, 5.5, 6.71, 6.93, 4.168, 9.779, 6.182, 7.59, 2.167,
						 7.042, 10.791, 5.313, 7.997, 5.654, 9.27, 3.1])
train_Y = numpy.asarray([1.7, 2.76, 2.09, 3.19, 1.694, 1.573, 3.366, 2.596, 2.53, 1.221,
						 2.827, 3.465, 1.65, 2.904, 2.42, 2.94, 1.3])
n_samples = train_X.shape[0]

with tf.Session() as sess:
	X = tf.placeholder("float")
	Y = tf.placeholder("float")

	W = tf.Variable(1.0, name="weight")
	b = tf.Variable(2.0, name="bias")

	pred = tf.add(tf.multiply(X, W), b)
	cost = tf.reduce_sum(tf.pow(pred - Y, 2)) / (2 * n_samples)
	sess.run(tf.global_variables_initializer())

	optimizer = tf.train.GradientDescentOptimizer(learning_rate).minimize(cost)
	for epoch in range(training_epochs):
		for (x, y) in zip(train_X, train_Y):
			sess.run(optimizer, feed_dict={X: x, Y: y})

	tf.saved_model.simple_save(sess, "./model", inputs={"x": X, "y": Y},
							   outputs={"c": pred})
							  
with tf.Session() as sess:
	tf.saved_model.loader.load(sess, tf.saved_model.tag_constants.SERVING, "./model")
```

**Other info / logs**
When I go to check the model with 'saved_model_cli' - show lists the tag 'serve':
```
saved_model_cli.py show --dir . --all

MetaGraphDef with tag-set: 'serve' contains the following SignatureDefs:

signature_def['serving_default']:
  The given SavedModel SignatureDef contains the following input(s):
    inputs['x'] tensor_info:
        dtype: DT_FLOAT
        shape: unknown_rank
        name: Placeholder:0
    inputs['y'] tensor_info:
        dtype: DT_FLOAT
        shape: unknown_rank
        name: Placeholder_1:0
  The given SavedModel SignatureDef contains the following output(s):
    outputs['c'] tensor_info:
        dtype: DT_FLOAT
        shape: unknown_rank
        name: Add:0
  Method name is: tensorflow/serving/predict
```

but when I try to run it, I encounter the same issue:
```
saved_model_cli.py run --dir . --tag_set 'serve' --signature_def 'serving_default' --input_exprs x=[1];y=[2]
Traceback (most recent call last):
  File "C:\Users\coverste\AppData\Local\Continuum\anaconda3\Lib\site-packages\tensorflow\python\tools\saved_model_cli.py", line 827, in <module>
    sys.exit(main())
  File "C:\Users\coverste\AppData\Local\Continuum\anaconda3\Lib\site-packages\tensorflow\python\tools\saved_model_cli.py", line 823, in main
    args.func(args)
  File "C:\Users\coverste\AppData\Local\Continuum\anaconda3\Lib\site-packages\tensorflow\python\tools\saved_model_cli.py", line 644, in run
    init_tpu=args.init_tpu, tf_debug=args.tf_debug)
  File "C:\Users\coverste\AppData\Local\Continuum\anaconda3\Lib\site-packages\tensorflow\python\tools\saved_model_cli.py", line 304, in run_saved_model_with_feed_dict
    tag_set)
  File "C:\Users\coverste\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\tools\saved_model_utils.py", line 49, in get_meta_graph_def
    ' could not be found in SavedModel')
RuntimeError: MetaGraphDef associated with tag-set 'serve' could not be found in SavedModel
```

**Comment by karmel** [comment]
The tags to load should be a list in your last line:

```
	tf.saved_model.loader.load(sess, [tf.saved_model.tag_constants.SERVING], "./model")
```

When I run with that, everything works as expected. Closing this issue; please reopen if I have misunderstood.

**Comment by csteegz** [comment]
Thanks - that resolved my issue. It would be nice to have an example using simple saver in the API docs or type annotations or something.
