### ISSUE TITLE
Error in configure.py, MPI_HOME

### ISSUE THREAD

**Issue by EWouters** [tensorflow/tensorflow#25292]
**System information**
- OS Platform and Distribution: Linux Ubuntu (4.15.0-44-generic)
- TensorFlow installed from: Source
- TensorFlow version: r1.13 (e7f2979fc7bbbd491a5c1db2268d4ee67cc46f88)
- Python version: 3.5
- Installed using virtualenv? pip? conda?: Conda
- Bazel version (if compiling from source): 0.21.0
- GCC/Compiler version (if compiling from source) : gcc-7 (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
- CUDA/cuDNN version: 10.0/7.4.2.24-1+cuda10.0
- GPU model and memory: K1100M

**Describe the problem**
If you specify a location for the MPI Toolkit, or use the default location the `configure.py` script will throw and error instead of printing a help message.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
```
#!/bin/bash
git clone git@github.com:tensorflow/tensorflow.git
cd tensorflow
git checkout r1.13
PYTHON_BIN="${HOME}/anaconda3/envs/tf_dev_3.5/bin/python"
export PYTHON_BIN_PATH="${PYTHON_BIN}"
export PYTHON_LIB_PATH="${HOME}/anaconda3/envs/tf_dev_3.5/lib/python3.5/site-packages"
export TF_ENABLE_XLA=1
export TF_NEED_OPENCL_SYCL=0
export TF_NEED_ROCM=0
export TF_NEED_CUDA=1
export TF_CUDA_VERSION="10.0"
export CUDA_TOOLKIT_PATH="/usr/local/cuda-10.0"
export TF_CUDNN_VERSION="7"
export CUDNN_INSTALL_PATH="/usr/local/cuda-10.0"
export TF_NEED_TENSORRT=1
export TENSORRT_INSTALL_PATH="/usr/lib/x86_64-linux-gnu"
export TF_NCCL_VERSION="2.3" # 2.3.7
export TF_CUDA_COMPUTE_CAPABILITIES="3.0"
export TF_CUDA_CLANG=0
export GCC_HOST_COMPILER_PATH="/usr/bin/gcc-7" #"/usr/bin/gcc" #"$(which gcc)"

export TF_NEED_MPI=1
./configure
```

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

```
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
INFO: Invocation ID: c5371cf2-ec36-4f56-b7f9-c2355305c07e
You have bazel 0.21.0 installed.
NCCL libraries found in /usr/lib/x86_64-linux-gnu/libnccl.so
This looks like a system path.
Assuming NCCL header path is /usr/include

Please specify the MPI toolkit folder. [Default is /usr]: 


Traceback (most recent call last):
  File "./configure.py", line 1701, in <module>
    main()
  File "./configure.py", line 1663, in main
    set_other_mpi_vars(environ_cp)
  File "./configure.py", line 1483, in set_other_mpi_vars
    mpi_home, mpi_home, mpi_home)
TypeError: not enough arguments for format string
```

**Comment by EWouters** [comment]
Thanks for the quick reply. I applied the patch you suggested<sup>[1](#patch1)</sup>, it now gives me this error:

```
WARNING: Running Bazel server needs to be killed, because the startup options are different.
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
INFO: Invocation ID: db6d283a-8268-4090-97ab-5f610d611862
You have bazel 0.21.0 installed.
NCCL libraries found in /usr/lib/x86_64-linux-gnu/libnccl.so
This looks like a system path.
Assuming NCCL header path is /usr/include
Please specify the MPI toolkit folder. [Default is /usr]: 


Traceback (most recent call last):
  File "./configure.py", line 1701, in <module>
    main()
  File "./configure.py", line 1663, in main
    set_other_mpi_vars(environ_cp)
  File "./configure.py", line 1483, in set_other_mpi_vars
    (mpi_home, mpi_home, mpi_home))
ValueError: Cannot find the MPI library file in /usr/lib or /usr/lib64 or /usr/lib32
```

Which is the expected behaviour AFAK. I'll close this issue.

<a name="patch1"><sup>1</sup>patch</a>:
```
diff --git a/configure.py b/configure.py
index 4f8cae2c57..32ecd18ec2 100644
--- a/configure.py
+++ b/configure.py
@@ -1480,7 +1480,7 @@ def set_other_mpi_vars(environ_cp):
   else:
     raise ValueError(
         'Cannot find the MPI library file in %s/lib or %s/lib64 or %s/lib32' %
-        mpi_home, mpi_home, mpi_home)
+        (mpi_home, mpi_home, mpi_home))
 
 
 def set_system_libs_flag(environ_cp):
```
