### ISSUE TITLE
Error importing tensorflow.

### ISSUE THREAD

**Issue by ayush1999** [tensorflow/tensorflow#25315]
I installed tensorflow using `python3 -m pip install --upgrade https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.12.0-py3-none-any.whl`, but importing tensorflow gives me:
```
>>> import tensorflow
Traceback (most recent call last):
  File "/home/ayush99/anaconda3/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/ayush99/anaconda3/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/ayush99/anaconda3/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/ayush99/anaconda3/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/ayush99/anaconda3/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /home/ayush99/anaconda3/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: invalid ELF header

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ayush99/anaconda3/lib/python3.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/ayush99/anaconda3/lib/python3.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/ayush99/anaconda3/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/ayush99/anaconda3/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/ayush99/anaconda3/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/ayush99/anaconda3/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/ayush99/anaconda3/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/ayush99/anaconda3/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /home/ayush99/anaconda3/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: invalid ELF header


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

Python: 3.7
Linux(Ubuntu), trying to install tensorflow for CPU.

**Comment by SalihOsman1** [comment]
I tried pip install tf-nightly , but still getting same error, "no matching distribution found for tf-nightly"

**Comment by SalihOsman1** [comment]
Currently , I have python 2.7, 3,5, and 3,7 all installed in my machine (ubuntu) running on Oracle VM which is running on Windows 10 Laptop (have 12 GB, 4 Cores, VM has 100 GB assignd,,,,etc). Just to see if my setup is a factor. Many thanks for any help!

**Comment by mayou36** [comment]
Now TensorFlow 1.13 works with Python 3.7 (the normal version). But if you have 3 python versions installed, I can imagine quite a chaos. Are you using any kind of virtualization _inside_ the vm? Like virtualenv or conda?

Which python version is "pip"? Can you do `which pip` in a terminal and see (at the end of the output) which version is picked up?

**Comment by kavyavm** [comment]
> It seems like you are using python 3.7, but there is no (official) python 3.7 support (yet). If you want to workaround, you may have a look at the threads where people try that.
> See for example: #17022 or #20517
> 
> Otherwise: try to use python 3.6, this should work
> 
> (_sidenote: pip install could currently [fails due to a bug](https://github.com/keras-team/keras-preprocessing/pull/156) (just a few hours ago introduced) in another package. Make sure, if it fails with python 3.6, that you also install pandas (as a temporary hack)_)

Tried 3.6. It is giving the same error as well

**Comment by mayou36** [comment]
How did you install it exactly? Do you have the logs?

**Comment by Sivabanu** [comment]
> For future reference, installing tensorflow-nightly (`pip install tf-nightly`) fixes this issue.

No matching distribution found for tf-nightly
