### ISSUE TITLE
Can't launch TF Detect Android sample with Yolov3-tiny model

### ISSUE THREAD

**Issue by zolkiBy** [tensorflow/tensorflow#25317]
- OS Platform - Linux Ubuntu 16.04;
- Tools: Android Studio 3.3 (Android Studio 3.3 Build #AI-182.5107.16.33.5199772)
- Mobile device Huawei P20 lite, Android Emulator (Nexus 5X, API 28)
- use the TensorFlow from Jcenter
- TensorFlow android version 1.12.0
- Python version: Python 3.6.8

I converted Yolov3-tiny model (downloaded from https://pjreddie.com/darknet/yolo/) with [DW2TF](https://github.com/jinyu121/DW2TF). Then I put .pb file to assets and changed MODE == DetectorMode.YOLO in DetectorActivity.java.

When I start TF Detect app I have a crash:
```E/AndroidRuntime: FATAL EXCEPTION: inference
    Process: org.tensorflow.demo, PID: 4643
    java.lang.IllegalArgumentException: No Operation named [input] in the Graph
        at org.tensorflow.Session$Runner.operationByName(Session.java:372)
        at org.tensorflow.Session$Runner.feed(Session.java:142)
        at org.tensorflow.contrib.android.TensorFlowInferenceInterface.addFeed(TensorFlowInferenceInterface.java:577)
        at org.tensorflow.contrib.android.TensorFlowInferenceInterface.feed(TensorFlowInferenceInterface.java:318)
        at org.tensorflow.demo.TensorFlowYoloDetector.recognizeImage(TensorFlowYoloDetector.java:159)
        at org.tensorflow.demo.DetectorActivity$3.run(DetectorActivity.java:289)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
```
I added logs and i have params `inputName` and `inputSize`. Can you help me with this issue?

**Comment by xinyee1997** [comment]
Do you solve the problem?
