### ISSUE TITLE
ImportError: No module named 'pandas'

### ISSUE THREAD

**Issue by albertz** [tensorflow/tensorflow#25322]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 14.04.5 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): pip/binary
- TensorFlow version (use command below): 1.12.0
- Python version: 3.5.6
- Bazel version (if compiling from source): None
- GCC/Compiler version (if compiling from source): None
- CUDA/cuDNN version: None
- GPU model and memory: None

**Describe the current behavior**

```
$ python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 88, in <module>
    from tensorflow.python import keras
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/tensorflow/python/keras/__init__.py", line 29, in <module>
    from tensorflow.python.keras import datasets
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/tensorflow/python/keras/datasets/__init__.py", line 25, in <module>
    from tensorflow.python.keras.datasets import imdb
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/tensorflow/python/keras/datasets/imdb.py", line 25, in <module>
    from tensorflow.python.keras.preprocessing.sequence import _remove_long_seq
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/tensorflow/python/keras/preprocessing/__init__.py", line 30, in <module>
    from tensorflow.python.keras.preprocessing import image
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/tensorflow/python/keras/preprocessing/image.py", line 23, in <module>
    from keras_preprocessing import image
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/keras_preprocessing/image/__init__.py", line 8, in <module>
    from .dataframe_iterator import DataFrameIterator
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/keras_preprocessing/image/dataframe_iterator.py", line 11, in <module>
    from pandas.api.types import is_numeric_dtype
ImportError: No module named 'pandas'
```

**Describe the expected behavior**

`import tensorflow` should work.

**Code to reproduce the issue**

```
pip install tensorflow
```

**Other info / logs**

This is via Travis.
See [here](https://travis-ci.org/rwth-i6/returnn/jobs/486014809) for the full Travis log.

The TF package it installs is this:
```
$ pip install tensorflow
Collecting tensorflow
  Downloading https://files.pythonhosted.org/packages/b1/ad/48395de38c1e07bab85fc3bbec045e11ae49c02a4db0100463dd96031947/tensorflow-1.12.0-cp35-cp35m-manylinux1_x86_64.whl (83.1MB)
...
Installing collected packages: gast, protobuf, termcolor, astor, grpcio, werkzeug, markdown, tensorboard, keras-preprocessing, absl-py, keras-applications, tensorflow
Successfully installed absl-py-0.7.0 astor-0.7.1 gast-0.2.2 grpcio-1.18.0 keras-applications-1.0.7 keras-preprocessing-1.0.6 markdown-3.0.1 protobuf-3.6.1 tensorboard-1.12.2 tensorflow-1.12.0 termcolor-1.1.0 werkzeug-0.14.1
```

I guess the `pandas` dependency is just missing?

**Comment by rragundez** [comment]
This was an issue in the `keras-preprocessing` package. It has been fixed. In the minor release 1.0.7 

https://github.com/keras-team/keras-preprocessing/releases/tag/1.0.7

**Comment by ymodak** [comment]
Since you are using python3, can you try,
 >pip3 install tensorflow

And if the importing pandas error still persists, further you can try,
>pip3 install pandas

**Comment by fchollet** [comment]
This should be resolved at this time; try reinstalling TF from pip.

**Comment by fchollet** [comment]
Or just upgrade to the latest keras_preprocessing: `pip install keras_preprocessing --upgrade`.

**Comment by Shanky87** [comment]
I have tried installing both ways.
Now I have installed tensorflow-gpu by conda. It is installed in a new environment which I created for tensorflow.
And I did this - pip install keras_preprocessing --upgrade
As well as this - pip3 install pandas.
Still it shows the same error
Please help.
