### ISSUE TITLE
Unsupported Ops: RandomUniform, SoftmaxCrossEntropyWithLogits.

### ISSUE THREAD

**Issue by smohan10** [tensorflow/tensorflow#25331]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 
- TensorFlow installed from (source or binary): pip install
- TensorFlow version (or github SHA if from source): 1.13.0

**Provide the text output from tflite_convert**

```
Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, CONV_2D, DEPTHWISE_CONV_2D, FLOOR, FULLY_CONNECTED, MAX_POOL_2D, MUL, RESHAPE. Here is a list of operators for which you will need custom implementations: RandomUniform, SoftmaxCrossEntropyWithLogits.
```

Also, please include a link to a GraphDef or the model if possible.

**Any other info / logs**

Traceback (most recent call last):
  File "/home/smohan/bin/toco_from_protos", line 11, in <module>
    sys.exit(main())
  File "/home/smohan/.local/lib/python3.5/site-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 59, in main
    app.run(main=execute, argv=[sys.argv[0]] + unparsed)
  File "/home/smohan/.local/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/home/smohan/.local/lib/python3.5/site-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 33, in execute
    output_str = tensorflow_wrap_toco.TocoConvert(model_str, toco_str, input_str)

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ymodak** [comment]
As the output suggests you need to add custom operators since the operations are not supported by TF Lite. Please refer this document to know more about [adding custom operators](https://www.tensorflow.org/lite/custom_operators). Thanks!

**Comment by ymodak** [comment]
Automatically closing this issue due to lack of activity. Feel free to reopen when additional information is available. Thanks!

**Comment by dksb** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
