### ISSUE TITLE
Library Conversion: TensorRT

### ISSUE THREAD

**Issue by dynamicwebpaige** [tensorflow/tensorflow#25348]
`tf.contrib` will be deprecated in TF 2.0, which means that TensorRT must migrate to a new home! The purpose of this ticket will be to migrate NVIDIA's TF-TRT library to the TF 2.0 API.

- Convert TF-TRT library.
- Run unit tests.
- Ensure processes are well understood.

TensorFlow integration with TensorRT (TF-TRT) optimizes and executes compatible subgraphs, allowing TensorFlow to execute the remaining graph. While you can still use TensorFlow's wide and flexible feature set, TensorRT will parse the model and apply optimizations to the portions of the graph wherever possible. Therefore, the workflow includes importing a trained TensorFlow model (graph and weights), freezing the graph, creating an optimized graph with TensorRT, importing it back as the default graph, and running inference. [[0](https://docs.nvidia.com/deeplearning/dgx/integrate-tf-trt/index.html)]

For the TensorFlow 1.x implementation of TF-TRT, check [here](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/tensorrt).

[0] [NVIDIA Deep Learning Frameworks Documentation](https://docs.nvidia.com/deeplearning/dgx/integrate-tf-trt/index.html) (2019)

**Comment by aaroey** [comment]
TF-TRT is supported in TF 2.0 alpha, and here is a [simple example](https://github.com/aaroey/tensorflow/blob/tftrt20/tftrt20/test.py) for that.

**Comment by Pidem** [comment]
I tried to run the simple example from @aaroey with tensorflow 2.0.0-beta0 and this raises an error: 

Traceback (most recent call last):
  File "/anaconda3/envs/Deep2/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 427, in import_graph_def
    graph._c_graph, serialized, options)  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input 1 of node StatefulPartitionedCall was passed float from conv1/kernel:0 incompatible with expected resource.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tensorrt_test.py", line 50, in <module>
    converter.save(saved_model_dir_trt)
  File "/anaconda3/envs/Deep2/lib/python3.6/site-packages/tensorflow/python/compiler/tensorrt/trt_convert.py", line 822, in save
    super(TrtGraphConverter, self).save(output_saved_model_dir)
  File "/anaconda3/envs/Deep2/lib/python3.6/site-packages/tensorflow/python/compiler/tensorrt/trt_convert.py", line 432, in save
    importer.import_graph_def(self._converted_graph_def, name="")
  File "/anaconda3/envs/Deep2/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/anaconda3/envs/Deep2/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 431, in import_graph_def
    raise ValueError(str(e))
ValueError: Input 1 of node StatefulPartitionedCall was passed float from conv1/kernel:0 incompatible with expected resource.

did I miss something?

**Comment by nocotan** [comment]
I have the same issue as @Pidem have.

**Comment by Pidem** [comment]
My guess is that this is related to the TensorRT version that Tensorflow was build with ?@nocotan @aaroey

**Comment by aaroey** [comment]
@Pidem @nocotan we made some changes since  2.0-beta0, so I just updated the test script. Would you please retry with tf-nightly-gpu-2.0-preview? Thanks.

**Comment by Pidem** [comment]
@aaroey It does run ! thanks.

**Comment by Pidem** [comment]
on a similar note, @aaroey , I think the following lines of code should return the value "True". 

from tensorflow.compiler.tf2tensorrt.wrap_py_utils import is_tensorrt_enabled
print(is_tensorrt_enabled())

**Comment by sayakpaul** [comment]
@aaroey I tried running your example on [this Colab Notebook](https://colab.research.google.com/drive/14iTHCILtUDf3TxrfV6NfHkthoQYmKrgK) but surprisingly, Colab crashes. Your inputs here would be very helpful.

**Comment by aaroey** [comment]
@sayakpaul could you share the crash log?

**Comment by zohaibjan** [comment]
I tried using the sample from this[Colab](https://colab.research.google.com/github/vinhngx/tensorrt/blob/vinhn-tf20-notebook/tftrt/examples/image-classification/TFv2-TF-TRT-inference-from-Keras-saved-model.ipynb?hl=en#scrollTo=lFKQPoLO_ikd)

Structure of my inference graph is:

` print(infer.structured_outputs)
{'conv2d_101': TensorSpec(shape=<unknown>, dtype=tf.float32, name='conv2d_101'), 'conv2d_109': TensorSpec(shape=<unknown>, dtype=tf.float32, name='conv2d_109'), 'conv2d_93': TensorSpec(shape=<unknown>, dtype=tf.float32, name='conv2d_93')}`

I am trying to convert YoloV4 based on keras from this [repo](https://github.com/taipingeric/yolo-v4-tf.keras)

But as per the colab when I used infex(input_1= x)  i get the following error:

`  [[{{node StatefulPartitionedCall/model_1/conv2d/Conv2D}}]]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/d/Testing/research/yolo-v4/yolo-v4/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 1669, in __call__
    return self._call_impl(args, kwargs)
  File "/mnt/d/Testing/research/yolo-v4/yolo-v4/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 1679, in _call_impl
    cancellation_manager)
  File "/mnt/d/Testing/research/yolo-v4/yolo-v4/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 1762, in _call_with_structured_signature
    cancellation_manager=cancellation_manager)
  File "/mnt/d/Testing/research/yolo-v4/yolo-v4/lib/python3.6/site-packages/tensorflow/python/saved_model/load.py", line 116, in _call_flat
    cancellation_manager)
  File "/mnt/d/Testing/research/yolo-v4/yolo-v4/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 1919, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/mnt/d/Testing/research/yolo-v4/yolo-v4/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 560, in call
    ctx=ctx)
  File "/mnt/d/Testing/research/yolo-v4/yolo-v4/lib/python3.6/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.NotFoundError:  No algorithm worked!
         [[{{node StatefulPartitionedCall/model_1/conv2d/Conv2D}}]]
         [[PartitionedCall/TRTEngineOp_0_1]] [Op:__inference_signature_wrapper_130807]

Function call stack:
signature_wrapper`
