### ISSUE TITLE
tf.keras.utils.multi  does not work with WGAN-GP Model

### ISSUE THREAD

**Issue by KUASWoodyLIN** [tensorflow/tensorflow#25416]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.12.0
- Python version: 3.5
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

**Describe the current behavior**
tf.keras.utils.multi  does not work with WGAN-GP Model
I also try on Keras(not tf.keras) and it was work!

**Code to reproduce the issue**
discriminator model code:
```
generator = gan_generator()
discriminator = gen_discriminator()


# Image input (real sample)
real_img = tf.keras.Input(shape=img_shape)
# Noise input
z_disc = tf.keras.Input(shape=(100,))
# Generate image based of noise (fake sample)
fake_img = generator(z_disc)

# Discriminator determines validity of the real and fake images
fake = discriminator(fake_img)
valid = discriminator(real_img)

# Construct weighted average between real and fake images
interpolated_img = RandomWeightedAverage()([real_img, fake_img])
# Determine validity of weighted sample
validity_interpolated = discriminator(interpolated_img)

# Use Python partial to provide loss function with additional
# 'averaged_samples' argument
partial_gp_loss = partial(gradient_penalty_loss,
                          averaged_samples=interpolated_img)
partial_gp_loss.__name__ = 'gradient_penalty'   # Keras requires function names

discriminator_model = tf.keras.Model(inputs=[real_img, z_disc], outputs=[valid, fake, validity_interpolated])
parallel_discriminator_model = tf.keras.utils.multi_gpu_model(discriminator_model, gpus=2)
```

generator & dircriminator body
```
def gan_generator(self):
    inputs = tf.keras.Input(shape=(100,))

    x = tf.keras.layers.Dense(7 * 7 * self.dims * 4, activation='relu', input_dim=self.latent_dim)(inputs)
    x = tf.keras.layers.Reshape((7, 7, self.dims * 4))(x)

    x = tf.keras.layers.UpSampling2D()(x)
    x = tf.keras.layers.Conv2D(self.dims * 4, kernel_size=5, padding="same")(x)
    x = tf.keras.layers.BatchNormalization(momentum=0.8)(x)
    x = tf.keras.layers.Activation("relu")(x)

    x = tf.keras.layers.UpSampling2D()(x)
    x = tf.keras.layers.Conv2D(self.dims * 2, kernel_size=5, padding="same")(x)
    x = tf.keras.layers.BatchNormalization(momentum=0.8)(x)
    x = tf.keras.layers.Activation("relu")(x)

    # x = UpSampling2D()(x)
    # x = Conv2D(self.dims * 1, kernel_size=5, padding="same")(x)
    # x = BatchNormalization(momentum=0.8)(x)
    # x = Activation("relu")(x)

    x = tf.keras.layers.Conv2D(self.channels, kernel_size=5, padding="same")(x)
    x = tf.keras.layers.Activation("tanh")(x)

    return tf.keras.Model(inputs, x)

def gen_discriminator(self):
    inputs = tf.keras.Input(shape=self.img_shape)

    x = tf.keras.layers.Conv2D(self.dims, kernel_size=5, strides=2, padding="same", input_shape=self.img_shape)(inputs)
    x = tf.keras.layers.LeakyReLU(alpha=0.2)(x)
    x = tf.keras.layers.Dropout(0.25)(x)

    x = tf.keras.layers.Conv2D(self.dims * 2, kernel_size=5, strides=2, padding="same")(x)
    x = tf.keras.layers.ZeroPadding2D(padding=((0, 1), (0, 1)))(x)
    x = tf.keras.layers.BatchNormalization(momentum=0.8)(x)
    x = tf.keras.layers.LeakyReLU(alpha=0.2)(x)
    x = tf.keras.layers.Dropout(0.25)(x)

    x = tf.keras.layers.Conv2D(self.dims * 4, kernel_size=5, strides=2, padding="same")(x)
    x = tf.keras.layers.BatchNormalization(momentum=0.8)(x)
    x = tf.keras.layers.LeakyReLU(alpha=0.2)(x)
    x = tf.keras.layers.Dropout(0.25)(x)

    x = tf.keras.layers.Conv2D(self.dims * 4, kernel_size=5, strides=2, padding="same")(x)
    x = tf.keras.layers.BatchNormalization(momentum=0.8)(x)
    x = tf.keras.layers.LeakyReLU(alpha=0.2)(x)
    x = tf.keras.layers.Dropout(0.25)(x)
    x = tf.keras.layers.Flatten()(x)
    x = tf.keras.layers.Dense(1)(x)
    return tf.keras.Model(inputs, x)

```

**Other info / logs**
```
2019-02-01 10:23:31.330533: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-02-01 10:23:31.441144: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:964] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-02-01 10:23:31.441617: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
name: GeForce GTX 1070 major: 6 minor: 1 memoryClockRate(GHz): 1.797
pciBusID: 0000:01:00.0
totalMemory: 7.93GiB freeMemory: 7.18GiB
2019-02-01 10:23:31.530899: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:964] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-02-01 10:23:31.531436: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 1 with properties: 
name: GeForce GTX 1070 major: 6 minor: 1 memoryClockRate(GHz): 1.797
pciBusID: 0000:03:00.0
totalMemory: 7.93GiB freeMemory: 7.83GiB
2019-02-01 10:23:31.532281: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0, 1
2019-02-01 10:23:32.028009: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-02-01 10:23:32.028044: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 1 
2019-02-01 10:23:32.028053: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N Y 
2019-02-01 10:23:32.028061: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 1:   Y N 
2019-02-01 10:23:32.028301: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6920 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1070, pci bus id: 0000:01:00.0, compute capability: 6.1)
2019-02-01 10:23:32.028599: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 7558 MB memory) -> physical GPU (device: 1, name: GeForce GTX 1070, pci bus id: 0000:03:00.0, compute capability: 6.1)
Traceback (most recent call last):
  File "/home/share/user/John/WGAN_GP/tf_main.py", line 258, in <module>
    wgan = WGANGP()
  File "/home/share/user/John/WGAN_GP/tf_main.py", line 82, in __init__
    parallel_discriminator_model = tf.keras.utils.multi_gpu_model(self.discriminator_model, gpus=2)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/utils/multi_gpu_utils.py", line 252, in multi_gpu_model
    return Model(model.inputs, merged)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/training.py", line 121, in __init__
    super(Model, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/network.py", line 80, in __init__
    self._init_graph_network(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/checkpointable/base.py", line 474, in _method_wrapper
    method(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/network.py", line 268, in _init_graph_network
    self.inputs, self.outputs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/network.py", line 1833, in _map_graph_network
    str(all_names.count(name)) + ' times in the model. '
ValueError: The name "model_1" is used 3 times in the model. All layer names should be unique.
```

**Comment by rmothukuru** [comment]
@KUASWoodyLIN,
[Distribution Strategy](https://www.tensorflow.org/tutorials/distribute/keras) can be a good option if you want to run your model with Multiple GPUs. Can you please take a look and let us know if this resolves your issue? Also, please refer the documentation for [Distributed Training](https://www.tensorflow.org/guide/distributed_training), [tf.distribute](https://www.tensorflow.org/api_docs/python/tf/distribute) and [Custom Training with tf.distribute.strategy](https://www.tensorflow.org/tutorials/distribute/custom_training) Thanks!
