### ISSUE TITLE
tf-nightly-gpu-2.0 import ptoblem

### ISSUE THREAD

**Issue by michalkowalski94** [tensorflow/tensorflow#25419]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS 7
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): pip install tf-nightly-gpu-2.0-preview
- TensorFlow version: tf-nightly-gpu-2.0-preview 2.0.0.dev20190201
- Python version: 3.6.5
- Installed using virtualenv? pip? conda?: virtual env with pip
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: 9.0
- GPU model and memory: Tesla k40d 11GB

**Describe the problem**
Cannot import tensorflow in python

**Provide the exact sequence of commands / steps that you executed before running into the problem**
import tensorflow as tf

**Any other info / logs**
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'tensorflow2'
>>> import tensorflow
Traceback (most recent call last):
  File "/net/scratch/people/plgmkowalski94/master/new/yolo3_tf2/tf2/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/net/scratch/people/plgmkowalski94/master/new/yolo3_tf2/tf2/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/net/scratch/people/plgmkowalski94/master/new/yolo3_tf2/tf2/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/net/scratch/people/plgmkowalski94/master/new/yolo3_tf2/tf2/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/net/scratch/people/plgmkowalski94/master/new/yolo3_tf2/tf2/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/net/scratch/people/plgmkowalski94/master/new/yolo3_tf2/tf2/lib/python3.6/site-packages/tensorflow/__init__.py", line 27, in <module>
    from tensorflow._api.v2 import audio
  File "/net/scratch/people/plgmkowalski94/master/new/yolo3_tf2/tf2/lib/python3.6/site-packages/tensorflow/_api/v2/audio/__init__.py", line 8, in <module>
    from tensorflow.python.ops.gen_audio_ops import encode_wav
  File "/net/scratch/people/plgmkowalski94/master/new/yolo3_tf2/tf2/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/net/scratch/people/plgmkowalski94/master/new/yolo3_tf2/tf2/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/net/scratch/people/plgmkowalski94/master/new/yolo3_tf2/tf2/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/net/scratch/people/plgmkowalski94/master/new/yolo3_tf2/tf2/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/net/scratch/people/plgmkowalski94/master/new/yolo3_tf2/tf2/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/net/scratch/people/plgmkowalski94/master/new/yolo3_tf2/tf2/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/net/scratch/people/plgmkowalski94/master/new/yolo3_tf2/tf2/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.`

**Comment by darthdeus** [comment]
Based on what you've written in the report, you have CUDA/cuDNN version: 9.0, but tf-nightly-gpu-2.0 requires CUDA 10, as you can see from the error

```
ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory
```

**Comment by michalkowalski94** [comment]
then I've got huge problem due to cluster apps 
` plgrid/apps/cuda/5.5    plgrid/apps/cuda/7.0 (D)    plgrid/apps/cuda/8.0    plgrid/apps/cuda/9.1
   plgrid/apps/cuda/6.5    plgrid/apps/cuda/7.5        plgrid/apps/cuda/9.0`

**Comment by michalkowalski94** [comment]
No, I'm just pointing out that I have much bigger problem with cluster apps
due to availability of CUDA 10

Pt., 1 lut 2019, 14:28: Jakub Arnold <notifications@github.com> napisał(a):

**Comment by darthdeus** [comment]
If you need the nightly build with 9.0 you can try compiling it yourself on 9.0. Though I'm not sure if it uses 10.0 because it is backwards incompatible with 9.0 or just because it was more convenient to move to the current version.

**Comment by ymodak** [comment]
@gunan Can you PTAL? Thanks!
