### ISSUE TITLE
bazel tests r1.13rc0

### ISSUE THREAD

**Issue by EWouters** [tensorflow/tensorflow#25430]
**System information**
- OS Platform and Distribution: Linux Ubuntu (4.15.0-44-generic)
- TensorFlow installed from: Source
- TensorFlow version: r1.13 (e7f2979fc7bbbd491a5c1db2268d4ee67cc46f88)
- Python version: 3.5
- Installed using virtualenv? pip? conda?: Conda
- Bazel version (if compiling from source): 0.21.0
- GCC/Compiler version (if compiling from source) : gcc-7 (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
- CUDA/cuDNN version: 10.0/7.4.2.24-1+cuda10.0
- GPU model and memory: K1100M 2 GB

**Describe the problem**
Running the bazel tests for r1.13rc0 fails.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
```
#!/bin/bash

CONDA_ENV="tf_dev_3.5"
PYTHON_VERSION="3.5"
WORKDIR="${HOME}/GitHub"
PYTHON_BIN="${HOME}/anaconda3/envs/${CONDA_ENV}/bin/python"
TF_VERSION="r1.13"

if [ ! -d "${WORKDIR}/tensorflow" ]; then
  git clone git@github.com:tensorflow/tensorflow.git
  git --git-dir "${WORKDIR}"/tensorflow/.git checkout ${TF_VERSION}
fi
git --git-dir "${WORKDIR}"/tensorflow/.git pull

export PYTHON_BIN_PATH="${PYTHON_BIN}"
export PYTHON_LIB_PATH="${HOME}/anaconda3/envs/${CONDA_ENV}/lib/python${PYTHON_VERSION}/site-packages"
export TF_ENABLE_XLA=1
export TF_NEED_OPENCL_SYCL=0
export TF_NEED_ROCM=0
export TF_NEED_CUDA=1
export TF_CUDA_VERSION="10.0"
export CUDA_TOOLKIT_PATH="/usr/local/cuda-10.0"
export TF_CUDNN_VERSION="7"
export CUDNN_INSTALL_PATH="/usr/local/cuda-10.0"
export TF_NEED_TENSORRT=1
export TENSORRT_INSTALL_PATH="/usr/lib/x86_64-linux-gnu"
export TF_NCCL_VERSION="2.4" # 2.4.2
export TF_CUDA_COMPUTE_CAPABILITIES="3.0"
export TF_CUDA_CLANG=0
export GCC_HOST_COMPILER_PATH="/usr/bin/gcc-7" #"/usr/bin/gcc" #"$(which gcc)"
export TF_NEED_MPI=1
export MPI_HOME="/usr/lib/x86_64-linux-gnu/openmpi"
export CC_OPT_FLAGS="-march=native -Wno-sign-compare"
export TF_SET_ANDROID_WORKSPACE=0

cd "${WORKDIR}"/tensorflow/
./configure

bazel build --config=opt --config=cuda --config=mkl --config=ngraph //tensorflow/tools/pip_package:build_pip_package
./bazel-bin/tensorflow/tools/pip_package/build_pip_package "${WORKDIR}"/tensorflow_pkg

# ${PYTHON_BIN} -m pip uninstall tensorflow -y
# ${PYTHON_BIN} -m pip install "${WORKDIR}"/tensorflow_pkg/tensorflow-*
```

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

```
 ✘  ~/GitHub/tensorflow   r1.13  bazel test -c opt -- //tensorflow/... -//tensorflow/compiler/... -//tensorflow/lite/...
Starting local Bazel server and connecting to it...
WARNING: The following configs were expanded more than once: [cuda]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
INFO: Invocation ID: e5417977-f3f0-4c98-a6a3-729508e1bc94
DEBUG: /home/erik/.cache/bazel/_bazel_erik/28b1b744916e40d081909e8a1a165362/external/bazel_tools/tools/build_defs/pkg/pkg.bzl:246:17: @//tensorflow/tools/lib_package:libtensorflow_jni: you provided a non dictionary to the pkg_tar `files` attribute. This attribute was renamed to `srcs`. Consider renaming it in your BUILD file.
DEBUG: /home/erik/.cache/bazel/_bazel_erik/28b1b744916e40d081909e8a1a165362/external/bazel_tools/tools/build_defs/pkg/pkg.bzl:246:17: @//tensorflow/tools/lib_package:common_deps: you provided a non dictionary to the pkg_tar `files` attribute. This attribute was renamed to `srcs`. Consider renaming it in your BUILD file.
DEBUG: /home/erik/.cache/bazel/_bazel_erik/28b1b744916e40d081909e8a1a165362/external/bazel_tools/tools/build_defs/pkg/pkg.bzl:246:17: @//tensorflow/tools/lib_package:cheaders: you provided a non dictionary to the pkg_tar `files` attribute. This attribute was renamed to `srcs`. Consider renaming it in your BUILD file.
DEBUG: /home/erik/.cache/bazel/_bazel_erik/28b1b744916e40d081909e8a1a165362/external/bazel_tools/tools/build_defs/pkg/pkg.bzl:246:17: @//tensorflow/tools/lib_package:eager_cheaders: you provided a non dictionary to the pkg_tar `files` attribute. This attribute was renamed to `srcs`. Consider renaming it in your BUILD file.
DEBUG: /home/erik/.cache/bazel/_bazel_erik/28b1b744916e40d081909e8a1a165362/external/bazel_tools/tools/build_defs/pkg/pkg.bzl:246:17: @//tensorflow/tools/lib_package:clib: you provided a non dictionary to the pkg_tar `files` attribute. This attribute was renamed to `srcs`. Consider renaming it in your BUILD file.
DEBUG: /home/erik/.cache/bazel/_bazel_erik/28b1b744916e40d081909e8a1a165362/external/bazel_tools/tools/build_defs/pkg/pkg.bzl:246:17: @//tensorflow/tools/lib_package:clicenses: you provided a non dictionary to the pkg_tar `files` attribute. This attribute was renamed to `srcs`. Consider renaming it in your BUILD file.
WARNING: /home/erik/GitHub/tensorflow/tensorflow/contrib/session_bundle/BUILD:86:1: target '//tensorflow/contrib/session_bundle:constants' is deprecated: No longer supported. Switch to SavedModel immediately.
WARNING: /home/erik/GitHub/tensorflow/tensorflow/contrib/session_bundle/BUILD:94:1: target '//tensorflow/contrib/session_bundle:exporter' is deprecated: No longer supported. Switch to SavedModel immediately.
WARNING: /home/erik/GitHub/tensorflow/tensorflow/contrib/session_bundle/BUILD:138:1: target '//tensorflow/contrib/session_bundle:gc' is deprecated: No longer supported. Switch to SavedModel immediately.
WARNING: /home/erik/GitHub/tensorflow/tensorflow/contrib/session_bundle/BUILD:181:1: target '//tensorflow/contrib/session_bundle:session_bundle' is deprecated: No longer supported. Switch to SavedModel immediately.
WARNING: /home/erik/GitHub/tensorflow/tensorflow/contrib/session_bundle/BUILD:200:1: target '//tensorflow/contrib/session_bundle:session_bundle_lite' is deprecated: No longer supported. Switch to SavedModel immediately.
WARNING: /home/erik/GitHub/tensorflow/tensorflow/contrib/session_bundle/BUILD:244:1: target '//tensorflow/contrib/session_bundle:session_bundle_py' is deprecated: No longer supported. Switch to SavedModel immediately.
WARNING: /home/erik/GitHub/tensorflow/tensorflow/contrib/session_bundle/BUILD:312:1: target '//tensorflow/contrib/session_bundle:signature' is deprecated: No longer supported. Switch to SavedModel immediately.
WARNING: /home/erik/GitHub/tensorflow/tensorflow/contrib/session_bundle/BUILD:293:1: target '//tensorflow/contrib/session_bundle:signature_lite' is deprecated: No longer supported. Switch to SavedModel immediately.
WARNING: /home/erik/GitHub/tensorflow/tensorflow/contrib/session_bundle/BUILD:349:1: target '//tensorflow/contrib/session_bundle:test_util' is deprecated: No longer supported. Switch to SavedModel immediately.
WARNING: /home/erik/GitHub/tensorflow/tensorflow/contrib/distributions/BUILD:16:1: target '//tensorflow/contrib/distributions:bijectors_py' is deprecated: TensorFlow Distributions has migrated to TensorFlow Probability (https://github.com/tensorflow/probability). Deprecated copies remaining in tf.contrib.distributions are unmaintained, unsupported, and will be removed by late 2018. You should update all usage of `tf.contrib.distributions` to `tfp.distributions`.
WARNING: /home/erik/GitHub/tensorflow/tensorflow/contrib/distributions/BUILD:48:1: target '//tensorflow/contrib/distributions:distributions_py' is deprecated: TensorFlow Distributions has migrated to TensorFlow Probability (https://github.com/tensorflow/probability). Deprecated copies remaining in tf.contrib.distributions are unmaintained, unsupported, and will be removed by late 2018. You should update all usage of `tf.contrib.distributions` to `tfp.distributions`.
WARNING: /home/erik/GitHub/tensorflow/tensorflow/python/ops/distributions/BUILD:9:1: target '//tensorflow/python/ops/distributions:distributions' is deprecated: TensorFlow Distributions has migrated to TensorFlow Probability (https://github.com/tensorflow/probability). Deprecated copies remaining in tf.distributions will not receive new features, and will be removed by early 2019. You should update all usage of `tf.distributions` to `tfp.distributions`.
ERROR: /home/erik/GitHub/tensorflow/tensorflow/core/BUILD:255:1: every rule of type proto_library implicitly depends upon the target '@com_google_protobuf//:protoc', but this target could not be found because of: no such package '@com_google_protobuf//': The native http_archive rule is deprecated. load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive") for a drop-in replacement.
Use --incompatible_remove_native_http_archive=false to temporarily continue using the native rule.
ERROR: Analysis of target '//tensorflow/core:example_java_proto' failed; build aborted: Analysis failed
INFO: Elapsed time: 30.254s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (410 packages loaded, 3273 targets configured)
```

```
 ✘  ~/GitHub/tensorflow   r1.13  bazel test --incompatible_remove_native_http_archive=false -c opt -- //tensorflow/... -//tensorflow/compiler/... -//tensorflow/lite/...
WARNING: The following configs were expanded more than once: [cuda]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
INFO: Invocation ID: cbdcdc07-17f9-45a7-bb7e-ea87aeb364e1
DEBUG: /home/erik/.cache/bazel/_bazel_erik/28b1b744916e40d081909e8a1a165362/external/bazel_tools/tools/build_defs/pkg/pkg.bzl:246:17: @//tensorflow/tools/lib_package:libtensorflow_jni: you provided a non dictionary to the pkg_tar `files` attribute. This attribute was renamed to `srcs`. Consider renaming it in your BUILD file.
DEBUG: /home/erik/.cache/bazel/_bazel_erik/28b1b744916e40d081909e8a1a165362/external/bazel_tools/tools/build_defs/pkg/pkg.bzl:246:17: @//tensorflow/tools/lib_package:common_deps: you provided a non dictionary to the pkg_tar `files` attribute. This attribute was renamed to `srcs`. Consider renaming it in your BUILD file.
DEBUG: /home/erik/.cache/bazel/_bazel_erik/28b1b744916e40d081909e8a1a165362/external/bazel_tools/tools/build_defs/pkg/pkg.bzl:246:17: @//tensorflow/tools/lib_package:cheaders: you provided a non dictionary to the pkg_tar `files` attribute. This attribute was renamed to `srcs`. Consider renaming it in your BUILD file.
DEBUG: /home/erik/.cache/bazel/_bazel_erik/28b1b744916e40d081909e8a1a165362/external/bazel_tools/tools/build_defs/pkg/pkg.bzl:246:17: @//tensorflow/tools/lib_package:eager_cheaders: you provided a non dictionary to the pkg_tar `files` attribute. This attribute was renamed to `srcs`. Consider renaming it in your BUILD file.
DEBUG: /home/erik/.cache/bazel/_bazel_erik/28b1b744916e40d081909e8a1a165362/external/bazel_tools/tools/build_defs/pkg/pkg.bzl:246:17: @//tensorflow/tools/lib_package:clib: you provided a non dictionary to the pkg_tar `files` attribute. This attribute was renamed to `srcs`. Consider renaming it in your BUILD file.
DEBUG: /home/erik/.cache/bazel/_bazel_erik/28b1b744916e40d081909e8a1a165362/external/bazel_tools/tools/build_defs/pkg/pkg.bzl:246:17: @//tensorflow/tools/lib_package:clicenses: you provided a non dictionary to the pkg_tar `files` attribute. This attribute was renamed to `srcs`. Consider renaming it in your BUILD file.
WARNING: /home/erik/GitHub/tensorflow/tensorflow/contrib/session_bundle/BUILD:86:1: target '//tensorflow/contrib/session_bundle:constants' is deprecated: No longer supported. Switch to SavedModel immediately.
WARNING: /home/erik/GitHub/tensorflow/tensorflow/contrib/session_bundle/BUILD:94:1: target '//tensorflow/contrib/session_bundle:exporter' is deprecated: No longer supported. Switch to SavedModel immediately.
WARNING: /home/erik/GitHub/tensorflow/tensorflow/contrib/session_bundle/BUILD:138:1: target '//tensorflow/contrib/session_bundle:gc' is deprecated: No longer supported. Switch to SavedModel immediately.
WARNING: /home/erik/GitHub/tensorflow/tensorflow/contrib/session_bundle/BUILD:181:1: target '//tensorflow/contrib/session_bundle:session_bundle' is deprecated: No longer supported. Switch to SavedModel immediately.
WARNING: /home/erik/GitHub/tensorflow/tensorflow/contrib/session_bundle/BUILD:200:1: target '//tensorflow/contrib/session_bundle:session_bundle_lite' is deprecated: No longer supported. Switch to SavedModel immediately.
WARNING: /home/erik/GitHub/tensorflow/tensorflow/contrib/session_bundle/BUILD:244:1: target '//tensorflow/contrib/session_bundle:session_bundle_py' is deprecated: No longer supported. Switch to SavedModel immediately.
WARNING: /home/erik/GitHub/tensorflow/tensorflow/contrib/session_bundle/BUILD:312:1: target '//tensorflow/contrib/session_bundle:signature' is deprecated: No longer supported. Switch to SavedModel immediately.
WARNING: /home/erik/GitHub/tensorflow/tensorflow/contrib/session_bundle/BUILD:293:1: target '//tensorflow/contrib/session_bundle:signature_lite' is deprecated: No longer supported. Switch to SavedModel immediately.
WARNING: /home/erik/GitHub/tensorflow/tensorflow/contrib/session_bundle/BUILD:349:1: target '//tensorflow/contrib/session_bundle:test_util' is deprecated: No longer supported. Switch to SavedModel immediately.
WARNING: /home/erik/GitHub/tensorflow/tensorflow/contrib/distributions/BUILD:16:1: target '//tensorflow/contrib/distributions:bijectors_py' is deprecated: TensorFlow Distributions has migrated to TensorFlow Probability (https://github.com/tensorflow/probability). Deprecated copies remaining in tf.contrib.distributions are unmaintained, unsupported, and will be removed by late 2018. You should update all usage of `tf.contrib.distributions` to `tfp.distributions`.
WARNING: /home/erik/GitHub/tensorflow/tensorflow/contrib/distributions/BUILD:48:1: target '//tensorflow/contrib/distributions:distributions_py' is deprecated: TensorFlow Distributions has migrated to TensorFlow Probability (https://github.com/tensorflow/probability). Deprecated copies remaining in tf.contrib.distributions are unmaintained, unsupported, and will be removed by late 2018. You should update all usage of `tf.contrib.distributions` to `tfp.distributions`.
WARNING: /home/erik/GitHub/tensorflow/tensorflow/python/ops/distributions/BUILD:9:1: target '//tensorflow/python/ops/distributions:distributions' is deprecated: TensorFlow Distributions has migrated to TensorFlow Probability (https://github.com/tensorflow/probability). Deprecated copies remaining in tf.distributions will not receive new features, and will be removed by early 2019. You should update all usage of `tf.distributions` to `tfp.distributions`.
ERROR: /home/erik/.cache/bazel/_bazel_erik/28b1b744916e40d081909e8a1a165362/external/com_google_protobuf/BUILD:597:1: Traceback (most recent call last):
	File "/home/erik/.cache/bazel/_bazel_erik/28b1b744916e40d081909e8a1a165362/external/com_google_protobuf/BUILD", line 597
		internal_gen_well_known_protos_java(srcs = WELL_KNOWN_PROTOS)
	File "/home/erik/.cache/bazel/_bazel_erik/28b1b744916e40d081909e8a1a165362/external/com_google_protobuf/protobuf.bzl", line 266, in internal_gen_well_known_protos_java
		Label(("%s//protobuf_java" % REPOSITOR...))
	File "/home/erik/.cache/bazel/_bazel_erik/28b1b744916e40d081909e8a1a165362/external/com_google_protobuf/protobuf.bzl", line 266, in Label
		REPOSITORY_NAME
The value 'REPOSITORY_NAME' has been removed in favor of 'repository_name()', please use the latter (https://docs.bazel.build/versions/master/skylark/lib/native.html#repository_name). You can temporarily allow the old name by using --incompatible_package_name_is_a_function=false
ERROR: /home/erik/.cache/bazel/_bazel_erik/28b1b744916e40d081909e8a1a165362/external/com_google_protobuf/BUILD:380:1: Target '@com_google_protobuf//:android' contains an error and its package is in error and referenced by '@com_google_protobuf//:protoc'
ERROR: /home/erik/.cache/bazel/_bazel_erik/28b1b744916e40d081909e8a1a165362/external/com_google_protobuf/BUILD:380:1: Target '@com_google_protobuf//:windows' contains an error and its package is in error and referenced by '@com_google_protobuf//:protoc'
ERROR: /home/erik/.cache/bazel/_bazel_erik/28b1b744916e40d081909e8a1a165362/external/com_google_protobuf/BUILD:380:1: Target '@com_google_protobuf//:windows_msvc' contains an error and its package is in error and referenced by '@com_google_protobuf//:protoc'
ERROR: /home/erik/GitHub/tensorflow/tensorflow/core/BUILD:255:1: every rule of type proto_library implicitly depends upon the target '@com_google_protobuf//:protoc', but this target could not be found because of: Target '@com_google_protobuf//:protoc' contains an error and its package is in error
ERROR: Analysis of target '//tensorflow/core:example_java_proto' failed; build aborted: Analysis failed
INFO: Elapsed time: 73.304s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (483 packages loaded, 17762 targets configured)
```

```
 ✘  ~/GitHub/tensorflow   r1.13  bazel test --incompatible_remove_native_http_archive=false --incompatible_package_name_is_a_function=false -c opt -- //tensorflow/... -//tensorflow/compiler/... -//tensorflow/lite/...
WARNING: The following configs were expanded more than once: [cuda]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
INFO: Invocation ID: 9421f3f2-53c7-4490-8dc6-675ac7d12ab2
DEBUG: /home/erik/.cache/bazel/_bazel_erik/28b1b744916e40d081909e8a1a165362/external/bazel_tools/tools/build_defs/pkg/pkg.bzl:246:17: @//tensorflow/tools/lib_package:libtensorflow_jni: you provided a non dictionary to the pkg_tar `files` attribute. This attribute was renamed to `srcs`. Consider renaming it in your BUILD file.
DEBUG: /home/erik/.cache/bazel/_bazel_erik/28b1b744916e40d081909e8a1a165362/external/bazel_tools/tools/build_defs/pkg/pkg.bzl:246:17: @//tensorflow/tools/lib_package:common_deps: you provided a non dictionary to the pkg_tar `files` attribute. This attribute was renamed to `srcs`. Consider renaming it in your BUILD file.
DEBUG: /home/erik/.cache/bazel/_bazel_erik/28b1b744916e40d081909e8a1a165362/external/bazel_tools/tools/build_defs/pkg/pkg.bzl:246:17: @//tensorflow/tools/lib_package:cheaders: you provided a non dictionary to the pkg_tar `files` attribute. This attribute was renamed to `srcs`. Consider renaming it in your BUILD file.
DEBUG: /home/erik/.cache/bazel/_bazel_erik/28b1b744916e40d081909e8a1a165362/external/bazel_tools/tools/build_defs/pkg/pkg.bzl:246:17: @//tensorflow/tools/lib_package:eager_cheaders: you provided a non dictionary to the pkg_tar `files` attribute. This attribute was renamed to `srcs`. Consider renaming it in your BUILD file.
DEBUG: /home/erik/.cache/bazel/_bazel_erik/28b1b744916e40d081909e8a1a165362/external/bazel_tools/tools/build_defs/pkg/pkg.bzl:246:17: @//tensorflow/tools/lib_package:clib: you provided a non dictionary to the pkg_tar `files` attribute. This attribute was renamed to `srcs`. Consider renaming it in your BUILD file.
DEBUG: /home/erik/.cache/bazel/_bazel_erik/28b1b744916e40d081909e8a1a165362/external/bazel_tools/tools/build_defs/pkg/pkg.bzl:246:17: @//tensorflow/tools/lib_package:clicenses: you provided a non dictionary to the pkg_tar `files` attribute. This attribute was renamed to `srcs`. Consider renaming it in your BUILD file.
WARNING: /home/erik/GitHub/tensorflow/tensorflow/contrib/session_bundle/BUILD:86:1: target '//tensorflow/contrib/session_bundle:constants' is deprecated: No longer supported. Switch to SavedModel immediately.
WARNING: /home/erik/GitHub/tensorflow/tensorflow/contrib/session_bundle/BUILD:94:1: target '//tensorflow/contrib/session_bundle:exporter' is deprecated: No longer supported. Switch to SavedModel immediately.
WARNING: /home/erik/GitHub/tensorflow/tensorflow/contrib/session_bundle/BUILD:138:1: target '//tensorflow/contrib/session_bundle:gc' is deprecated: No longer supported. Switch to SavedModel immediately.
WARNING: /home/erik/GitHub/tensorflow/tensorflow/contrib/session_bundle/BUILD:181:1: target '//tensorflow/contrib/session_bundle:session_bundle' is deprecated: No longer supported. Switch to SavedModel immediately.
WARNING: /home/erik/GitHub/tensorflow/tensorflow/contrib/session_bundle/BUILD:200:1: target '//tensorflow/contrib/session_bundle:session_bundle_lite' is deprecated: No longer supported. Switch to SavedModel immediately.
WARNING: /home/erik/GitHub/tensorflow/tensorflow/contrib/session_bundle/BUILD:244:1: target '//tensorflow/contrib/session_bundle:session_bundle_py' is deprecated: No longer supported. Switch to SavedModel immediately.
WARNING: /home/erik/GitHub/tensorflow/tensorflow/contrib/session_bundle/BUILD:312:1: target '//tensorflow/contrib/session_bundle:signature' is deprecated: No longer supported. Switch to SavedModel immediately.
WARNING: /home/erik/GitHub/tensorflow/tensorflow/contrib/session_bundle/BUILD:293:1: target '//tensorflow/contrib/session_bundle:signature_lite' is deprecated: No longer supported. Switch to SavedModel immediately.
WARNING: /home/erik/GitHub/tensorflow/tensorflow/contrib/session_bundle/BUILD:349:1: target '//tensorflow/contrib/session_bundle:test_util' is deprecated: No longer supported. Switch to SavedModel immediately.
WARNING: /home/erik/GitHub/tensorflow/tensorflow/contrib/distributions/BUILD:16:1: target '//tensorflow/contrib/distributions:bijectors_py' is deprecated: TensorFlow Distributions has migrated to TensorFlow Probability (https://github.com/tensorflow/probability). Deprecated copies remaining in tf.contrib.distributions are unmaintained, unsupported, and will be removed by late 2018. You should update all usage of `tf.contrib.distributions` to `tfp.distributions`.
WARNING: /home/erik/GitHub/tensorflow/tensorflow/contrib/distributions/BUILD:48:1: target '//tensorflow/contrib/distributions:distributions_py' is deprecated: TensorFlow Distributions has migrated to TensorFlow Probability (https://github.com/tensorflow/probability). Deprecated copies remaining in tf.contrib.distributions are unmaintained, unsupported, and will be removed by late 2018. You should update all usage of `tf.contrib.distributions` to `tfp.distributions`.
WARNING: /home/erik/GitHub/tensorflow/tensorflow/python/ops/distributions/BUILD:9:1: target '//tensorflow/python/ops/distributions:distributions' is deprecated: TensorFlow Distributions has migrated to TensorFlow Probability (https://github.com/tensorflow/probability). Deprecated copies remaining in tf.distributions will not receive new features, and will be removed by early 2019. You should update all usage of `tf.distributions` to `tfp.distributions`.
ERROR: /home/erik/GitHub/tensorflow/tensorflow/contrib/BUILD:167:12: in deps attribute of cc_library rule //tensorflow/contrib:contrib_kernels: py_library rule '//tensorflow/contrib/mpi_collectives:mpi_collectives_py' is misplaced here (expected cc_library, objc_library, cc_proto_library or cc_import) and '//tensorflow/contrib/mpi_collectives:mpi_collectives_py' does not have mandatory providers: 'CcInfo'
ERROR: Analysis of target '//tensorflow/contrib:contrib_kernels' failed; build aborted: Analysis of target '//tensorflow/contrib:contrib_kernels' failed; build aborted
INFO: Elapsed time: 24.164s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (532 packages loaded, 72385 targets configured)
```

**Comment by martinwicke** [comment]
John, seems to be a problem with bazel 0.21, 0.22. I assume we're simply not ready for that yet?

**Comment by nebgru** [comment]
More info... Tests do not work, build does though, it completes in entirety with no problems. Bazel versioning is a problem. I modified configure file to accept 0.22.0 and it built fine with it, so you can probably remove the upper boundary.

**Comment by jakline** [comment]
Amit: We are using bazel 0.19.2.  Do we have any requirements to run with bazel 0.21 or 0.22?

**Comment by av8ramit** [comment]
Not at the moment, the recommended way is still only 0.19.2.

**Comment by av8ramit** [comment]
We have internally decided not to increase the upper limit.
