### ISSUE TITLE
TF1.13.0rc0 cuda10: ImportError: libcublas.so.9.0: cannot open shared object file

### ISSUE THREAD

**Issue by Tassfighter** [tensorflow/tensorflow#25458]
### System information
- **OS Platform and Distribution:  Linux Ubuntu 16.04 
- **TensorFlow installed from: Docker Tag 1.13.0rc0-gpu-py3
- **Python version**: 3.5
- **CUDA/cuDNN version**: cuda 10.0
- **GPU model and memory**: 2 * RTX 2080 TI and 2 * GTX 1080

### Describe the problem

With version 1.13.0rc0 (for gpu, py3) from dockerhub an error occurs on:

`import tensorflow as tf`

With version 1.13.0-dev20181228 (for gpu, py3) from dockerhub everything works well.

Environment variables seem to be ok:
LD_LIBRARY_PATH=/usr/local/cuda/extras/CUPTI/lib64 

### Source code / logs
---------------------------------------------------------------------------
```
ImportError                               Traceback (most recent call last)
/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py in <module>
     57 
---> 58   from tensorflow.python.pywrap_tensorflow_internal import *
     59   from tensorflow.python.pywrap_tensorflow_internal import __version__

/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py in <module>
     27             return _mod
---> 28     _pywrap_tensorflow_internal = swig_import_helper()
     29     del swig_import_helper

/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py in swig_import_helper()
     23             try:
---> 24                 _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
     25             finally:

/usr/lib/python3.5/imp.py in load_module(name, file, filename, details)
    241         else:
--> 242             return load_dynamic(name, filename, file)
    243     elif type_ == PKG_DIRECTORY:

/usr/lib/python3.5/imp.py in load_dynamic(name, path, file)
    341             name=name, loader=loader, origin=path)
--> 342         return _load(spec)
    343 

ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-1-59571c70a10d> in <module>
      8 get_ipython().run_line_magic('autoreload', '2')
      9 
---> 10 import tensorflow as tf
     11 print(tf.__version__)

/usr/local/lib/python3.5/dist-packages/tensorflow/__init__.py in <module>
     22 
     23 # pylint: disable=g-bad-import-order
---> 24 from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
     25 
     26 try:

/usr/local/lib/python3.5/dist-packages/tensorflow/python/__init__.py in <module>
     47 import numpy as np
     48 
---> 49 from tensorflow.python import pywrap_tensorflow
     50 
     51 from tensorflow.python.tools import component_api_helper

/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py in <module>
     72 for some common reasons and solutions.  Include the entire stack trace
     73 above this error message when asking for help.""" % traceback.format_exc()
---> 74   raise ImportError(msg)
     75 
     76 # pylint: enable=wildcard-import,g-import-not-at-top,unused-import,line-too-long

ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

**Comment by martinwicke** [comment]
@aselle this shouldn't try to load CUDA 9, right?

**Comment by Walkoss** [comment]
I'm facing this same issue with the `latest-gpu-py3` tag on dockerhub.
@Tassfighter which tag did you pulled to get a working version (which refers to `1.13.0-dev20181228`) ?

**Comment by Tassfighter** [comment]
@Walkoss I've pulled version 1.13.0-dev20181228 some days ago from a nightly build. So I assume it's not there anymore, sorry :(

**Comment by angersson** [comment]
A bug (which has been fixed) in our Docker release CI led to the `latest-` tagged images containing CUDA 10 libraries but TF 1.12 (which needs CUDA 9). The images have been updated so that they use CUDA 10 and TF 1.13rc1 (which needs CUDA 10). Sorry about the confusion.
