### ISSUE TITLE
usage of Dataset.window causes TypeError when creating iterator

### ISSUE THREAD

**Issue by tomzo** [tensorflow/tensorflow#25460]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution: Linux Ubuntu 16.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.12.0
- Python version: 3.5

**Describe the current behavior**

Following code is a snippet from [Dataset.window documentation](https://www.tensorflow.org/api_docs/python/tf/data/Dataset#window)
```
import tensorflow as tf
dataset = tf.data.Dataset.range(7).window(2)
iterator = dataset.make_one_shot_iterator()
next_element = iterator.get_next()
```

Calling `iterator.get_next()` throws following error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/eager/execute.py", line 123, in make_type
    v = dtypes.as_dtype(v).base_dtype
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/dtypes.py", line 712, in as_dtype
    raise TypeError("Cannot convert value %r to a TensorFlow DType." % type_value)
TypeError: Cannot convert value <tensorflow.python.data.ops.dataset_ops._NestedDatasetComponent object at 0x7fdf882319b0> to a TensorFlow DType.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py", line 3267, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-29-624c3010a782>", line 1, in <module>
```

**Describe the expected behavior**
```
next_element = iterator.get_next()
```
should create iterator object.

**Code to reproduce the issue**
See above.

**Comment by yongtang** [comment]
@tomzo I could reproduce the issue with `tensorflow==1.12.0` but not with `tf-nightly`. Looks like the issue has been fixed in the master branch. Could you try with `tf-nightly`?

**Comment by tomzo** [comment]
Tested in docker image `tensorflow/tensorflow:nightly`  
```
import tensorflow as tf
dataset = tf.data.Dataset.range(7).window(2)
iterator = dataset.make_one_shot_iterator()
next_element = iterator.get_next()
```
Does not throw errors anymore.

Thanks.
