### ISSUE TITLE
ImportError: DLL load failed with error code -1073741795

### ISSUE THREAD

**Issue by rachiteagles** [tensorflow/tensorflow#25468]
This template is for miscellaneous issues not covered by the other issue categories.

For questions on how to work with TensorFlow, or support for problems that are not verified bugs in TensorFlow, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).

If you are reporting a vulnerability, please use the [dedicated reporting process](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md).

For high-level discussions about TensorFlow, please post to discuss@tensorflow.org, for questions about the development or internal workings of TensorFlow, or if you would like to know how to contribute to TensorFlow, please post to developers@tensorflow.org.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by jvishnuvardhan** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by SmirnovKol** [comment]
(venv) C:\>python
Python 3.6.7 (v3.6.7:6ec5cf24b7, Oct 20 2018, 13:35:33) [MSC v.1900 64 bit (AMD6
4)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
Traceback (most recent call last):
  File "C:\Users\Administrator\venv\lib\site-packages\tensorflow\python\pywrap_t
ensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Administrator\venv\lib\site-packages\tensorflow\python\pywrap_t
ensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Administrator\venv\lib\site-packages\tensorflow\python\pywrap_t
ensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, descript
ion)
  File "C:\Users\Administrator\venv\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Administrator\venv\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed with error code -1073741795

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Administrator\venv\lib\site-packages\tensorflow\__init__.py", l
ine 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-im
port
  File "C:\Users\Administrator\venv\lib\site-packages\tensorflow\python\__init__
.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Administrator\venv\lib\site-packages\tensorflow\python\pywrap_t
ensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Administrator\venv\lib\site-packages\tensorflow\python\pywrap_t
ensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Administrator\venv\lib\site-packages\tensorflow\python\pywrap_t
ensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Administrator\venv\lib\site-packages\tensorflow\python\pywrap_t
ensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, descript
ion)
  File "C:\Users\Administrator\venv\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Administrator\venv\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed with error code -1073741795


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
>>>

**Comment by SmirnovKol** [comment]
I hava encountered exactly the same problem!!!!!

**Comment by SmirnovKol** [comment]
I use Windows 7(64 bit), choose tensorflow for CPU only,  follow the instructions on  https://tensorflow.google.cn/install/pip   step by step 
I create a virtual environment  and use  virtualenv install

**Comment by SmirnovKol** [comment]
of course, when  I  run  the command:
python -c "import tensorflow as tf; tf.enable_eager_execution(); print(tf.reduce_sum(tf.random_normal([1000, 1000])))"
it went wrong!!!

**Comment by SmirnovKol** [comment]
(venv) C:\>python3
'python3' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

(venv) C:\>python --version
Python 3.6.7

(venv) C:\>pip3 --version
pip 19.0.3 from c:\users\administrator\venv\lib\site-packages\pip (python 3.6)

(venv) C:\>virtualenv --version
16.4.3

**Comment by jvishnuvardhan** [comment]
@SmirnovKol Could you post entire commands you used?
Here are the commands that worked for me on Windows10

Creating Virtual Environment on your system
$ virtualenv -p python venv-tf
$ source venv-tf/bin/activate
$ pip install tensorflow-gpu
$ python
$ import tensorflow as tf
$ print(tf.__version__)
$ deactivate venv-tf


Please let me know how it progresses. Thanks!
