### ISSUE TITLE
Cannot import tensorflow-gpu in jupyter notebook.

### ISSUE THREAD

**Issue by shuuchen** [tensorflow/tensorflow#25507]
Hi,

I am using the following conda environment and jupyter notebook.

python==3.5
tensorflow-gpu==1.4.0
cuda==8.0
cudnn==6.0

While I can correctly import tensorflow in the cmd line:
```
(tensorflow) [dushu@ip-172-20-149-210 Mask_RCNN]$ python
Python 3.5.5 |Anaconda, Inc.| (default, May 13 2018, 21:12:35)
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as t
/home/dushu/anaconda3/envs/tensorflow/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
>>> t.test
<module 'tensorflow.python.platform.test' from '/home/dushu/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/platform/test.py'>
>>> t.test.gpu_device_name()
2019-02-05 04:08:32.393567: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2019-02-05 04:08:35.257250: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:892] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-02-05 04:08:35.257629: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties:
name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
pciBusID: 0000:00:1e.0
totalMemory: 11.17GiB freeMemory: 11.10GiB
2019-02-05 04:08:35.257662: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: Tesla K80, pci bus id: 0000:00:1e.0, compute capability: 3.7)
'/device:GPU:0'
```
 I can' t import it in the jupyter notebook:
```
ImportError: Traceback (most recent call last):
  File "/home/dushu/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/dushu/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/dushu/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/dushu/anaconda3/envs/tensorflow/lib/python3.5/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/home/dushu/anaconda3/envs/tensorflow/lib/python3.5/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.8.0: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

The jupyter seems cannot find cuda path. The other similar issues don' t work either.

Any help please ?

**Comment by shuuchen** [comment]
solved by specifying 
```
sudo ldconfig /usr/local/cuda-8.0/lib64
```

**Comment by robin-fusemachines** [comment]
any updated for windows 10 ? I am getting this same error
