### ISSUE TITLE
AttributeError: module 'tensorflow.python.ops.losses.losses_impl' has no attribute 'ReductionV2'

### ISSUE THREAD

**Issue by nd7141** [tensorflow/tensorflow#25517]
Installing tensorflow 1.12.0 with `pip install tensorflow` results in the following error:

```
Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/s.ivanov/miniconda3/envs/tf_env/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/s.ivanov/miniconda3/envs/tf_env/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 55, in <module>
    'tensorflow_estimator.python.estimator'))
  File "/home/s.ivanov/miniconda3/envs/tf_env/lib/python3.6/site-packages/tensorflow/python/tools/component_api_helper.py", line 56, in package_hook
    child_pkg = importlib.import_module(child_package_str)
  File "/home/s.ivanov/miniconda3/envs/tf_env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/s.ivanov/miniconda3/envs/tf_env/lib/python3.6/site-packages/tensorflow_estimator/__init__.py", line 8, in <module>
    from tensorflow_estimator._api.v2 import estimator
  File "/home/s.ivanov/miniconda3/envs/tf_env/lib/python3.6/site-packages/tensorflow_estimator/_api/v2/estimator/__init__.py", line 8, in <module>
    from tensorflow_estimator._api.v2.estimator import experimental
  File "/home/s.ivanov/miniconda3/envs/tf_env/lib/python3.6/site-packages/tensorflow_estimator/_api/v2/estimator/experimental/__init__.py", line 8, in <module>
    from tensorflow_estimator.python.estimator.canned.dnn import dnn_logit_fn_builder
  File "/home/s.ivanov/miniconda3/envs/tf_env/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/__init__.py", line 25, in <module>
    import tensorflow_estimator.python.estimator.estimator_lib
  File "/home/s.ivanov/miniconda3/envs/tf_env/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator_lib.py", line 22, in <module>
    from tensorflow_estimator.python.estimator.canned.baseline import BaselineClassifier
  File "/home/s.ivanov/miniconda3/envs/tf_env/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/canned/baseline.py", line 67, in <module>
    from tensorflow_estimator.python.estimator.head import head_utils
  File "/home/s.ivanov/miniconda3/envs/tf_env/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/head/head_utils.py", line 23, in <module>
    from tensorflow_estimator.python.estimator.head import binary_class_head
  File "/home/s.ivanov/miniconda3/envs/tf_env/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/head/binary_class_head.py", line 24, in <module>
    from tensorflow.python.keras.utils import metrics_utils
  File "/home/s.ivanov/miniconda3/envs/tf_env/lib/python3.6/site-packages/tensorflow/python/keras/utils/metrics_utils.py", line 31, in <module>
    from tensorflow.python.keras.utils.losses_utils import squeeze_or_expand_dimensions
  File "/home/s.ivanov/miniconda3/envs/tf_env/lib/python3.6/site-packages/tensorflow/python/keras/utils/losses_utils.py", line 144, in <module>
    weighted_losses, reduction=losses_impl.ReductionV2.SUM_OVER_BATCH_SIZE):
AttributeError: module 'tensorflow.python.ops.losses.losses_impl' has no attribute 'ReductionV2'
```

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux
- TensorFlow version: 1.12.0
- Python version: 3.6
- Installed using virtualenv? pip? conda?: pip

**Comment by jvishnuvardhan** [comment]
@nd7141 Did you follow the instructions on [tensorflow website](https://www.tensorflow.org/install/source). While installing from source, please also note that [tested build configuration](https://www.tensorflow.org/install/source#linux) for Linux system. Please let me know how it progresses. Thanks!

**Comment by fnielsen** [comment]
Will deleting the tensorflow directory help? If you are not in a virtual environment:
```bash
sudo pip3 uninstall tensorflow
sudo rm -r /usr/local/lib/python3.6/dist-packages/tensorflow/
sudo pip3 install tensorflow
python3 -c "import tensorflow as tf; tf.enable_eager_execution(); print(tf.reduce_sum(tf.random_normal([1000, 1000])))"
```
These commands apparently got my system working.

**Comment by jvishnuvardhan** [comment]
I think it was resolved. I am closing the issue. Open a new ticket if the bug persists. Thanks!
