### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow_estimator' in bazel tests

### ISSUE THREAD

**Issue by herbakamil** [tensorflow/tensorflow#25526]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution: 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version: master
- Python version: Python 3.6.6
- Installed using virtualenv? pip? conda?: N/A
- Bazel version (if compiling from source): 0.20.0
- GCC/Compiler version (if compiling from source): 7.3.0
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the problem**
According to https://www.tensorflow.org/install/source after downloading I should be able to run tests via:
bazel test -c opt -- //tensorflow/... -//tensorflow/compiler/... -//tensorflow/lite/...
But when I run this command a lot of tests fail like this one
bazel test tensorflow/contrib/eager/python/examples/gan:mnist_graph_test_gpu
fail on No module named 'tensorflow_estimator' even though later I've installed estimator.

Do I need to have some special environment? I've been even testing tensorflow/tensorflow docker image and it also fails with this error

**Provide the exact sequence of commands / steps that you executed before running into the problem**

git clone https://github.com/tensorflow/tensorflow.git
cd tensorflow
bazel test tensorflow/contrib/eager/python/examples/gan:mnist_graph_test_gpu
**Any other info / logs**

exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //tensorflow/contrib/eager/python/examples/gan:mnist_graph_test_gpu
-----------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tclbot/.cache/bazel/_bazel_tclbot/eee9defa2fa4c4fc557baa005719ebd9/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/contrib/eager/python/examples/gan/mnist_graph_test_gpu.runfiles/org_tensorflow/tensorflow/contrib/eager/python/examples/gan/mnist_graph_test.py", line 26, in <module>
    from tensorflow.contrib.eager.python.examples.gan import mnist
  File "/home/tclbot/.cache/bazel/_bazel_tclbot/eee9defa2fa4c4fc557baa005719ebd9/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/contrib/eager/python/examples/gan/mnist_graph_test_gpu.runfiles/org_tensorflow/tensorflow/contrib/__init__.py", line 41, in <module>
    from tensorflow.contrib import distribute
  File "/home/tclbot/.cache/bazel/_bazel_tclbot/eee9defa2fa4c4fc557baa005719ebd9/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/contrib/eager/python/examples/gan/mnist_graph_test_gpu.runfiles/org_tensorflow/tensorflow/contrib/distribute/__init__.py", line 33, in <module>
    from tensorflow.contrib.distribute.python.tpu_strategy import initialize_tpu_system
  File "/home/tclbot/.cache/bazel/_bazel_tclbot/eee9defa2fa4c4fc557baa005719ebd9/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/contrib/eager/python/examples/gan/mnist_graph_test_gpu.runfiles/org_tensorflow/tensorflow/contrib/distribute/python/tpu_strategy.py", line 27, in <module>
    from tensorflow.contrib.tpu.python.ops import tpu_ops
  File "/home/tclbot/.cache/bazel/_bazel_tclbot/eee9defa2fa4c4fc557baa005719ebd9/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/contrib/eager/python/examples/gan/mnist_graph_test_gpu.runfiles/org_tensorflow/tensorflow/contrib/tpu/__init__.py", line 73, in <module>
    from tensorflow.contrib.tpu.python.tpu.keras_support import tpu_model as keras_to_tpu_model
  File "/home/tclbot/.cache/bazel/_bazel_tclbot/eee9defa2fa4c4fc557baa005719ebd9/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/contrib/eager/python/examples/gan/mnist_graph_test_gpu.runfiles/org_tensorflow/tensorflow/contrib/tpu/python/tpu/keras_support.py", line 62, in <module>
    from tensorflow.contrib.tpu.python.tpu import tpu
  File "/home/tclbot/.cache/bazel/_bazel_tclbot/eee9defa2fa4c4fc557baa005719ebd9/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/contrib/eager/python/examples/gan/mnist_graph_test_gpu.runfiles/org_tensorflow/tensorflow/contrib/tpu/python/tpu/tpu.py", line 25, in <module>
    from tensorflow.contrib.compiler import xla
  File "/home/tclbot/.cache/bazel/_bazel_tclbot/eee9defa2fa4c4fc557baa005719ebd9/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/contrib/eager/python/examples/gan/mnist_graph_test_gpu.runfiles/org_tensorflow/tensorflow/contrib/compiler/xla.py", line 28, in <module>
    from tensorflow.python.estimator import model_fn as model_fn_lib
  File "/home/tclbot/.cache/bazel/_bazel_tclbot/eee9defa2fa4c4fc557baa005719ebd9/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/contrib/eager/python/examples/gan/mnist_graph_test_gpu.runfiles/org_tensorflow/tensorflow/python/estimator/__init__.py", line 26, in <module>
    from tensorflow_estimator.python import estimator
ModuleNotFoundError: No module named 'tensorflow_estimator'

**Comment by gunan** [comment]
could you try running `pip install tensorflow-estimator --pre` before running tests?

**Comment by herbakamil** [comment]
even though later I've installed estimator.

So of course I've tried to rerun with tensorflow-estimator installed but it didn't help
Inside ipython `from tensorflow_estimator.python import estimator` runs fine

**Comment by herbakamil** [comment]
Maybe this was the issue that I've tried to work with python3?
After installing python2 and tensorflow-estimator for python2 problem has disappeared
