### ISSUE TITLE
ImportError: cannot import name 'toco_flags_pb2'

### ISSUE THREAD

**Issue by someshbhalsing** [tensorflow/tensorflow#25530]
**System information**
- OS Platform : Windows 10 Home x64 version 1809
- TensorFlow installed from : pip
- TensorFlow version 1.12.0

**text output from tflite_convert**

```
# tflite_convert \ --output_file=/tmp/model.tflite \ --graph_def_file=/tmp/output_graph.pb \ --input_arrays=input \ --output_arrays=MobilenetV1/Predictions/Reshape_1
Traceback (most recent call last):
  File "c:\users\somesh\appdata\local\programs\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\somesh\appdata\local\programs\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\somesh\AppData\Local\Programs\Python\Python36\Scripts\tflite_convert.exe\__main__.py", line 5, in <module>
  File "c:\users\somesh\appdata\local\programs\python\python36\lib\site-packages\tensorflow\contrib\__init__.py", line 103, in <module>
    from tensorflow.contrib.lite.python import lite
  File "c:\users\somesh\appdata\local\programs\python\python36\lib\site-packages\tensorflow\contrib\lite\python\lite.py", line 40, in <module>
    from tensorflow.lite.python import lite_constants as constants
  File "c:\users\somesh\appdata\local\programs\python\python36\lib\site-packages\tensorflow\lite\python\lite_constants.py", line 21, in <module>
    from tensorflow.lite.toco import toco_flags_pb2 as _toco_flags_pb2
ImportError: cannot import name 'toco_flags_pb2 
```

**Comment by jvishnuvardhan** [comment]
@someshbhalsing Could you mention more details about the context and steps leading to this error? It is better if you can provide any code to reproduce the error. Thanks!

**Comment by someshbhalsing** [comment]
The issue is solved.
I installed tensorflow-nightly and then used the tflite convertor.

**Comment by jvishnuvardhan** [comment]
I am closing this as it was resolved. Thanks!

**Comment by dksb** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
