### ISSUE TITLE
Issue regarding import library for tensorflow-gpu 1.0.1 version

### ISSUE THREAD

**Issue by sahertariq07** [tensorflow/tensorflow#25581]
System information
- OS Platform: Linux Ubuntu 15.10
- TensorFlow installed from (source or binary):
- TensorFlow version: TensorFlow-GPU 1.0.1
- Python version: 3.7
- Installed using pip command: pip install tensorflow-gpu==1.0.1
- Using anaconda jupyter for programming
- CUDA/cuDNN version: 8
- GPU model and memory:NVIDIA Corporation GM204 [GeForce GTX 970]

I'm using tensorflow-gpu package to train seq2seq model on a dataset. But it gives error durring importing libraries.
----------------------------------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/comsats/yes/envs/my-rdkit-env/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 61, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/comsats/yes/envs/my-rdkit-env/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/home/comsats/yes/envs/my-rdkit-env/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
  File "/home/comsats/yes/envs/my-rdkit-env/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/home/comsats/yes/envs/my-rdkit-env/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libcudart.so.8.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/comsats/yes/envs/my-rdkit-env/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/comsats/yes/envs/my-rdkit-env/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/comsats/Desktop/saher_tariq/Panday_group/reaction_prediction_seq2seq-master/bin/train.py", line 29, in <module>
    import tensorflow as tf
  File "/home/comsats/yes/envs/my-rdkit-env/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/home/comsats/yes/envs/my-rdkit-env/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 72, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/comsats/yes/envs/my-rdkit-env/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 61, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/comsats/yes/envs/my-rdkit-env/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/home/comsats/yes/envs/my-rdkit-env/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
  File "/home/comsats/yes/envs/my-rdkit-env/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/home/comsats/yes/envs/my-rdkit-env/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libcudart.so.8.0: cannot open shared object file: No such file or directory

Failed to load the native TensorFlow runtime.

See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md#import_error

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
----------------------------------------------------------------------------------------------------------------------------------
I have tried after re-installation of tensorflow but it gives same error. Model works fine when i had used only tensorflow 1.0.1 only for cpu March issue, but was very slow in working. So then i tried for tensorflow-gpu which gives me this error. And also this model scripts are compatible to tensorflow-gpu 1.0.1 version. As i got help to install the package from the discussion for the model working. https://github.com/pandegroup/reaction_prediction_seq2seq/issues/1 
Any help relating to issue is appreciated. 
Thank you.

**Comment by jvishnuvardhan** [comment]
@sahertariq07 Please check tested [build configurations](https://www.tensorflow.org/install/source#linux). Python version you are using is not supported for the TF version you are using. Please check Bazel version also. Another thing I noticed was libcudart.so.8.0 error. This was one of the common error and there are [solutions](https://github.com/tensorflow/tensorflow/issues/5343) in the GitHub and Stackoverflow etc. Please search "ImportError: libcudart.so.8.0:" in GitHub or elsewhere, you can find the solution. I think the CUDA path has some issues. Please let me know how it progresses. Thanks!

**Comment by sahertariq07** [comment]
Thank you very much @jvishnuvardhan for your response. My issue is resolved. It was due to compatibility with my system's driver. I'm going to close this issue now.

**Comment by dksb** [comment]
Are you satisfied with the resolution of your issue?<br> [Yes](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=Yes&entry.2137816233=25581)<br> [No](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=No&entry.2137816233=25581)
