### ISSUE TITLE
Dll exception

### ISSUE THREAD

**Issue by aniketbote** [tensorflow/tensorflow#25597]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 
XPS 15 9570 specs --
Processor : Intel(r) Core(Tm) i7-8750H CPU @2.20GHz 2.21GHz
Ram : 16 Gb
System type : 64 bit, x64 based processor
Windows 10 Home single Language  --
version = 1803
OS Build 17134.523

- TensorFlow installed from (source or binary): 
Used pip install
- TensorFlow version:  
tensorflow-gpu = 1.12.0
- Python version: python 64bit 3.6.8
- Installed using virtualenv? pip? conda?: 
using pip
- CUDA/cuDNN version: 
Tried CUDA toolkit 9.2 and 10.0 with similar error. 
cudnn - 7.4.2 (Dec  14)

- GPU model and memory:
Nvidia : NVIDIA GeForce GTX 1050 Ti with Max-Q Design
Mem : 4GB GDDR5
Driver Version - 24.21.13.9793

**Describe the problem**
When I import tensorflow it gives me error:
ImportError: DLL load failed: The specified module could not be found.
Failed to load the native TensorFlow runtime.
**Provide the exact sequence of commands / steps that you executed before running into the problem**
I followed the path as shown [here](https://www.youtube.com/watch?v=HExRhnO5Mqs).
1. Uninstalled python
2. First I downloaded visual studio community version 17.
3. Then I downloaded and installed Cuda toolkit 9.2
4. Then downloaded cudnn 7.4.2. Added the path of folders bin,include,lib and all internal folder of path variable.
5. Installed python
6: Run command 'pip install --ignore-installed --upgrade tensorflow-gpu'
7. Ran python on command prompt and Imported tensorflow

**Any other info / logs**
Complete tracebook:
Python 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
Traceback (most recent call last):
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python36\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python36\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python36\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python36\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
>>>

Tried solution:
[This solution](https://stackoverflow.com/questions/42011070/on-windows-running-import-tensorflow-generates-no-module-named-pywrap-tenso)

**Comment by jvishnuvardhan** [comment]
@aniketbote Please check [Tested build supports](https://www.tensorflow.org/install/source_windows#gpu).    What OS you have in your system? What is your Bazel version? I have noticed that MSVC is higher verion. You might need to downgrade to 2015 version. There is another [issue](https://github.com/tensorflow/tensorflow/issues/24886) with WINDOWS10 where it limits the path length. Also, check whether CUDA location is referencing correctly.  Please let me know how it progresses. Thanks!

**Comment by aniketbote** [comment]
My OS as stated in issue is windows 10.
I don't have bazel since I am building it from source.
I have uninstalled Microsoft visual studio 2017 community edition, cuda and delete cudnn from system
I started fresh as per the tested build supports. 
1) Uninstalled python and deleted the site - packages folder from the system
2) Downloaded Microsoft visual studio 2015 community edition from [here](https://stackoverflow.com/questions/44290672/how-to-download-visual-studio-community-edition-2015-not-2017l)
3) Downloaded cuda 9.2 for windows from [here](https://developer.nvidia.com/cuda-toolkit-archive)
4) Downloaded cudnn 7.4.2 from [here](https://developer.nvidia.com/cuda-toolkit-archive)
5) set path in environment variable for user.
6) In cmd pip install tensorflw-gpu
7) import tensorflow

Result : Result was similar as previous.
>>> import tensorflow
Traceback (most recent call last):
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python36\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python36\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python36\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python36\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by jvishnuvardhan** [comment]
@aniketbote Did you remove the restriction on path length as mentioned in my earlier response. Thanks!

**Comment by aniketbote** [comment]
Yes, i followed the link provided by you.
My long path was already enabled (set to 1).

**Comment by jvishnuvardhan** [comment]
@aniketbote Thanks for the confirmation. I will try to install on my windows10 system and get back to you. Meanwhile, try to install CUDA 9.0 because some of the modules looking for a cuda9.0 path. This is one of the common error. So it is better to load 9.0 version or check whether all the paths (CUDA-->cuDNN, Python, tensorflow, other modules) are referenced correctly. Thanks!

**Comment by optimal16** [comment]
> Yes, i followed the link provided by you.
> My long path was already enabled (set to 1).

have you solved this problem ?  I meet the same one

**Comment by aniketbote** [comment]
> @aniketbote Thanks for the confirmation. I will try to install on my windows10 system and get back to you. Meanwhile, try to install CUDA 9.0 because some of the modules looking for a cuda9.0 path. This is one of the common error. So it is better to load 9.0 version or check whether all the paths (CUDA-->cuDNN, Python, tensorflow, other modules) are referenced correctly. Thanks!

When I try to install cuda 9.0 version in my system. 
I get this.
![capture](https://user-images.githubusercontent.com/38111546/52531047-3c517a00-2d35-11e9-824e-c1a95525287f.PNG)

However when I try to install 9.2 and 10 it works fine.
The above mentioned are the only two that works fine.

**Comment by jvishnuvardhan** [comment]
@aniketbote Thanks. Did you check whether all the paths to CUDA/cuDNN are set right? Thanks!

**Comment by aniketbote** [comment]
> @aniketbote Thanks. Did you check whether all the paths to CUDA/cuDNN are set right? Thanks!

Yes, the path is set.

**Comment by aniketbote** [comment]
I tried it on 
**cuda 9.0 
cudnn 7.05**

The path variables for this installation:
![capture](https://user-images.githubusercontent.com/38111546/52789680-88c8ec80-308a-11e9-990e-73cfc98cb8fa.PNG)

**Comment by jvishnuvardhan** [comment]
@aniketbote Could you uninstall python and tenosrflow, and try to reinstall everything using my instruction [here](https://github.com/jvishnuvardhan/Installing-TensorFlow-GPU-on-Windows-10-TF1.12). If you want to use CUDA10, then you can install TF1.13 following the same procedure listed there but use newer version of drivers. Please let me know how it progresses. Thanks!

**Comment by alvaroslm** [comment]
This could be the same problem as this other unresolved issue, see my comment there: https://github.com/tensorflow/tensorflow/issues/25552#issuecomment-470159497

**Comment by aniketbote** [comment]
Yes I think it is the same problem. Any particular way it could be resolved? @alvaroslm

**Comment by ymodak** [comment]
*TensorFlow release binaries (CPU/GPU) version 1.6 and higher are prebuilt with AVX instruction sets.*  
See [hardware requirements][1] to know more.  

Therefore on any CPU that does not have these instruction sets, either CPU or GPU version of TF will fail to load.
Apparently, your CPU model does not support AVX instruction sets. You can still use TensorFlow with the alternatives given below:  

* Try Google Colab to use TensorFlow.    
 * The easiest way to use TF will be to switch to [google colab](https://colab.sandbox.google.com/notebooks/welcome.ipynb#recent=true). You get pre-installed latest stable TF version. Also you can use ```pip install``` to install any other preferred TF version.  
    * It has an added advantage since you can you easily switch to different hardware accelerators (cpu, gpu, tpu) as per the task. 
    * All you need is a good internet connection and you are all set.  
* Try to build TF from sources by changing CPU optimization flags.


  [1]: https://www.tensorflow.org/install/pip#hardware-requirements
