### ISSUE TITLE
Batchnorm does not work in Eager mode in TF 1.12: InternalError: Could not find valid device for node

### ISSUE THREAD

**Issue by nizlas** [tensorflow/tensorflow#25601]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Linux based on Dockerfile tensorflow/tensorflow:1.12.0-devel-gpu-py3, that is Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
No
- TensorFlow installed from (source or binary):
Dockerfile tensorflow/tensorflow:1.12.0-devel-gpu-py3
- TensorFlow version (use command below):
1.12.0
- Python version:
Python 3.5.2
- Bazel version (if compiling from source):
No
- GCC/Compiler version (if compiling from source):
No
- CUDA/cuDNN version:
== cuda libs  ===================================================
/usr/local/lib/python3.5/dist-packages/torch/lib/libcudart-f7fdd8d7.so.9.0
/usr/local/cuda-9.0/targets/x86_64-linux/lib/libcudart.so.9.0.176
/usr/local/cuda-9.0/targets/x86_64-linux/lib/libcudart_static.a

- GPU model and memory:
GeForce GTX TITAN X 11.93GiB

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**
 File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_nn_ops.py", line 3496, in _fused_batch_norm
    _six.raise_from(_core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InternalError: Could not find valid device for node.
Node: {{node FusedBatchNorm}} = FusedBatchNorm[T=DT_DOUBLE, data_format="NHWC", epsilon=0.001, is_training=false](dummy_input, dummy_input, dummy_input, dummy_input, dummy_input)
All kernels registered for op FusedBatchNorm :
  device='XLA_GPU'; T in [DT_FLOAT]
  device='XLA_CPU'; T in [DT_FLOAT]
  device='XLA_CPU_JIT'; T in [DT_FLOAT]
  device='XLA_GPU_JIT'; T in [DT_FLOAT]
  device='CPU'; T in [DT_FLOAT]
  device='GPU'; T in [DT_FLOAT]
 [Op:FusedBatchNorm]
$ 

**Describe the expected behavior**
I expect Tensorflow to find that my GPU (or at least my CPU) is a valid device to execute a Batchnorm operation on. It is not.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import BatchNormalization
tf.enable_eager_execution()
x = np.random.rand(2,416,416,3) * 255
x = tf.convert_to_tensor(x)
bn = BatchNormalization()
x = bn(x)

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
Tensorflow version 1.12.0
Keras version 2.1.6-tf
2019-02-07 22:59:14.551505: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-02-07 22:59:14.678286: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
name: GeForce GTX TITAN X major: 5 minor: 2 memoryClockRate(GHz): 1.2155
pciBusID: 0000:05:00.0
totalMemory: 11.92GiB freeMemory: 7.08GiB
2019-02-07 22:59:14.781607: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 1 with properties: 
name: GeForce GTX TITAN X major: 5 minor: 2 memoryClockRate(GHz): 1.2155
pciBusID: 0000:09:00.0
totalMemory: 11.93GiB freeMemory: 11.81GiB
2019-02-07 22:59:14.782011: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0, 1
2019-02-07 22:59:15.310401: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-02-07 22:59:15.310438: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 1 
2019-02-07 22:59:15.310450: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N Y 
2019-02-07 22:59:15.310457: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 1:   Y N 
2019-02-07 22:59:15.311331: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6821 MB memory) -> physical GPU (device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:05:00.0, compute capability: 5.2)
2019-02-07 22:59:15.311691: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 11427 MB memory) -> physical GPU (device: 1, name: GeForce GTX TITAN X, pci bus id: 0000:09:00.0, compute capability: 5.2)
Traceback (most recent call last):
  File "/home/niclasdn/.vscode/extensions/ms-python.python-2019.1.0/pythonFiles/ptvsd_launcher.py", line 45, in <module>
    main(ptvsdArgs)
  File "/home/niclasdn/.vscode/extensions/ms-python.python-2019.1.0/pythonFiles/lib/python/ptvsd/__main__.py", line 348, in main
    run()
  File "/home/niclasdn/.vscode/extensions/ms-python.python-2019.1.0/pythonFiles/lib/python/ptvsd/__main__.py", line 253, in run_file
    runpy.run_path(target, run_name='__main__')
  File "/usr/lib/python3.5/runpy.py", line 254, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/usr/lib/python3.5/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/niclasdn/development/yolov3_pytorch/run_yolov3_minitest.py", line 70, in <module>
    x = bn(x)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 757, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/layers/normalization.py", line 514, in call
    outputs = self._fused_batch_norm(inputs, training=training)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/layers/normalization.py", line 401, in _fused_batch_norm
    training, _fused_batch_norm_training, _fused_batch_norm_inference)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/utils/tf_utils.py", line 52, in smart_cond
    pred, true_fn=true_fn, false_fn=false_fn, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/smart_cond.py", line 56, in smart_cond
    return false_fn()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/layers/normalization.py", line 398, in _fused_batch_norm_inference
    data_format=self._data_format)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/nn_impl.py", line 909, in fused_batch_norm
    name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_nn_ops.py", line 3496, in _fused_batch_norm
    _six.raise_from(_core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InternalError: Could not find valid device for node.
Node: {{node FusedBatchNorm}} = FusedBatchNorm[T=DT_DOUBLE, data_format="NHWC", epsilon=0.001, is_training=false](dummy_input, dummy_input, dummy_input, dummy_input, dummy_input)
All kernels registered for op FusedBatchNorm :
  device='XLA_GPU'; T in [DT_FLOAT]
  device='XLA_CPU'; T in [DT_FLOAT]
  device='XLA_CPU_JIT'; T in [DT_FLOAT]
  device='XLA_GPU_JIT'; T in [DT_FLOAT]
  device='CPU'; T in [DT_FLOAT]
  device='GPU'; T in [DT_FLOAT]
 [Op:FusedBatchNorm]
$

**Comment by jvishnuvardhan** [comment]
@nizlas I am not sure why you are not able to run. I was able to run the your code as follows. I had to change float type from float64 to float32 and removed brackets around enabling eager. Please check whether this will work on your computer.
 
import tensorflow as tf
tf.enable_eager_execution
import numpy as np
from tensorflow.keras.layers import BatchNormalization
bn = BatchNormalization()
x = np.random.rand(2,416,416,3) * 255
x=x.astype(np.float32)
x = tf.convert_to_tensor(x)

x = bn(x)

Thanks!

**Comment by nizlas** [comment]
Removing the parantheses seems to put everything on the CPU (at least my computer became extremely slow and the CPU was working 100%) so I would not recommend that. Not sure what it even means...replacing a function call with a variable?

My mistake was that numpy by default assigned float64 to the input tensor. However the error message is still quite confusing... I would have expected some warning that the layer has no implementation for float64. It becomes even more confusing since the convlayer DOES execute in float64 (but very slowly) so one does naturally interprets the differing behaviour between convolution2d and Batchnorm to be an error in the framework.

Also the documentation is very behind with respect to this. One would any kind of comment on datatype support in the documentation...

Anyway, with float32 it works. Thanks for the feedback!

**Comment by jvishnuvardhan** [comment]
@nizlas Thanks! I had to remove parentheses because Spyder was throwing error. But, it is just Spyder issue. In other places like Google colab, I need to use parentheses. 
Closing this out since I understand it to be resolved, but please let me know if I'm mistaken. Thanks!

**Comment by dksb** [comment]
Are you satisfied with the resolution of your issue?<br> [Yes](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=Yes&entry.2137816233=25601)<br> [No](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=No&entry.2137816233=25601)
