### ISSUE TITLE
examples/skflow/out_of_core_data_classification.py dose not work

### ISSUE THREAD

**Issue by sun9700** [tensorflow/tensorflow#2565]
/usr/bin/python2.7 /home/sun/tensorflow/tensorflow/examples/skflow/out_of_core_data_classification.py
Traceback (most recent call last):
  File "/home/sun/tensorflow/tensorflow/examples/skflow/out_of_core_data_classification.py", line 47, in <module>
    classifier.fit(X_train, y_train)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/base.py", line 168, in fit
    x, y, n_classes=self.n_classes, batch_size=self.batch_size)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/io/data_feeder.py", line 116, in setup_train_data_feeder
    X, y, n_classes, batch_size, shuffle=shuffle, epochs=epochs)
TypeError: __init__() got an unexpected keyword argument 'epochs'

Process finished with exit code 1

**Comment by ilblackdragon** [comment]
Examples was deleted as untested/unsupported one :(
