### ISSUE TITLE
Error running ./configure on Cuda 10 (Building from Source)

### ISSUE THREAD

**Issue by Ayshine** [tensorflow/tensorflow#25681]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 18.04):Linux Ubuntu 18.04)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: no
- TensorFlow installed from (source ): yes
- TensorFlow version: master branch
- Python version: 2.7
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source): 21.0
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10 
- GPU model and memory: 1080 

Having the following error when trying to run ./configure
Since I'm trying to use CUDA 10 with Tensorflow I need to build from the source 

**
```
Invalid SYCL 1.2 library path. /usr/local/computecpp/lib/libComputeCpp.so cannot be found
Traceback (most recent call last):
  File "./configure.py", line 1701, in <module>
    main()
  File "./configure.py", line 1595, in main
    set_computecpp_toolkit_path(environ_cp)
  File "./configure.py", line 1387, in set_computecpp_toolkit_path
    suppress_default_error=True)
  File "./configure.py", line 657, in prompt_loop_or_load_from_env
    'Assuming to be a scripting mistake.' % (var_name, n_ask_attempts))
__main__.UserInputError: Invalid COMPUTECPP_TOOLKIT_PATH setting was provided 10 times in a row. Assuming to be a scripting mistake.
```
**Provide the exact sequence of commands / steps that you executed before running into the problem**
I tried to complete installation starting from Tensorflow part of this blogpost https://medium.com/@vitali.usau/install-cuda-10-0-cudnn-7-3-and-build-tensorflow-gpu-from-source-on-ubuntu-18-04-3daf720b83fe but the first bazel version was not compatible with tensorflow so I needed to downgrade to 21 then this error poped out.

**Comment by Ayshine** [comment]
Closing this I continued my installation without SYCL.
