### ISSUE TITLE
freeze_graph gives Unexpected EOF from Bazel server (Scikit Flow) or gcc internal compiler error

### ISSUE THREAD

**Issue by codingyourlife** [tensorflow/tensorflow#2572]
I can't get the hang of exporting a scikit flow model to a model.pb file to use it with android.

### Environment info
Operating System:16.04 LTS

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
No such file or directory

If installed from binary pip package, provide:

1. Which pip package you installed. -?
2. The output from python -c "import tensorflow; print(tensorflow.__version__)".
0.8.0

### Steps to reproduce
1. classifier.save('model/')
2. copy contents of model folder to tensorflow root
3. cd tensorflow && bazel build tensorflow/python/tools:freeze_graph && bazel-bin/tensorflow/python/tools/freeze_graph --input_graph=graph.pbtxt --input_checkpoint=checkpoint --output_graph=/tmp/frozen_graph.pb --output_node_names=softmax --jobs 4 --verbose_failures > output.txt  2>&1

-> should compile a *.pb file from the *.pbtxt file. bazel build tensorflow/python/tools:freeze_graph fails already.

Result after a while of compiling:
Unexpected EOF from Bazel server or gcc internal compiler error

### What have you tried?
1. bazel clean -> only takes longer
2. adding RAM and increasing RAM of VM (11GB of 16GB)
3. --jobs 4

### Logs or other output that would be helpful
![bazel](https://cloud.githubusercontent.com/assets/10122382/15635531/ce333328-25e0-11e6-8b4d-4e753f0d47a5.PNG)
Traceback (most recent call last):
  File "/home/administrator/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/tensorflow/python/tools/freeze_graph.py", line 40, in <module>
    import tensorflow as tf
  File "/home/administrator/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/home/administrator/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/administrator/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/home/administrator/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/tensorflow/python/pywrap_tensorflow.py", line 20, in swig_import_helper
    import _pywrap_tensorflow
ImportError: No module named _pywrap_tensorflow

**Comment by codingyourlife** [comment]
Damn I might really have installed the Mac version on Ubuntu. Just creating a new VM, let's see if that helps. I'll post an update soon.

**Comment by codingyourlife** [comment]
Ok figured it out. The problem was that the --jobs 4 should also be at another of those statements. The right statement is:
`cd tensorflow && bazel build tensorflow/python/tools:freeze_graph --jobs 4 && bazel-bin/tensorflow/python/tools/freeze_graph --input_graph=graph.pbtxt --input_checkpoint=checkpoint --output_graph=/tmp/frozen_graph.pb --output_node_names=softmax --jobs 4 --verbose_failures` notice  bazel build tensorflow/python/tools:freeze_graph **--jobs 4**. I now have another problem but this one is closed.
