### ISSUE TITLE
ModuleNotFoundError: No module named 'numpy'

### ISSUE THREAD

**Issue by nickeys** [tensorflow/tensorflow#25732]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution : Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): source
- TensorFlow version: v1.12.0
- Python version: 3.6.8
- Installed using virtualenv? pip? conda?: pip without virtualenv
- Bazel version (if compiling from source): 0.15.0
- GCC/Compiler version (if compiling from source): I'm not sure what version I'm using but, I'm using VS2015 and _MSC_VER is 1900
- CUDA/cuDNN version: CUDA v9.0.176 / cuDNN v7.4.2.24
- GPU model and memory: GTX960M (2GB)

**Describe the problem**
I'm trying to install TF on my laptop from the source code.
I installed GPU driver, CUDA, cuDNN, python, bazel, MSYS2 and Visual Studio, following the official guide (https://www.tensorflow.org/install/source_windows).
Of course, I checked the system variables such as CUDA_PATH and BAZEL_SH.
Then, I cloned the git repository and attempted to build.
After I had launched the build, I saw the build working well.
So that, I just let it go and slept.
However, I found out the build failed in the morning.
I cannot understand why the build failed because I can see 'numpy' package installed when I type "pip3 list" as follows:

> C:\tensorflow>pip3 list
> Package             Version
> ------------------- -------
> absl-py             0.7.0
> astor               0.7.1
> gast                0.2.2
> grpcio              1.18.0
> h5py                2.9.0
> Keras-Applications  1.0.6
> Keras-Preprocessing 1.0.5
> Markdown            3.0.1
> numpy               1.16.1
> pip                 18.1
> protobuf            3.6.1
> setuptools          40.6.2
> six                 1.12.0
> tensorboard         1.12.2
> tensorflow-gpu      1.12.0
> termcolor           1.1.0
> Werkzeug            0.14.1
> wheel               0.32.3

And I have also searched similar issue by googling but I could not found proper solution for me.
Please give me any suggestion.

Thanks!

**Provide the exact sequence of commands / steps that you executed before running into the problem**

> C:\tensorflow>python configure.py
> WARNING: Running Bazel server needs to be killed, because the startup options are different.
> WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
> You have bazel 0.15.0 installed.
> Please specify the location of python. [Default is C:\Users\nickeys\AppData\Local\Programs\Python\Python36\python.exe]:
> 
> 
> Found possible Python library paths:
>   C:\Users\nickeys\AppData\Local\Programs\Python\Python36\lib\site-packages
> Please input the desired Python library path to use.  Default is [C:\Users\nickeys\AppData\Local\Programs\Python\Python36\lib\site-packages]
> 
> Do you wish to build TensorFlow with Apache Ignite support? [Y/n]: N
> No Apache Ignite support will be enabled for TensorFlow.
> 
> Do you wish to build TensorFlow with XLA JIT support? [y/N]: N
> No XLA JIT support will be enabled for TensorFlow.
> 
> Do you wish to build TensorFlow with ROCm support? [y/N]:
> No ROCm support will be enabled for TensorFlow.
> 
> Do you wish to build TensorFlow with CUDA support? [y/N]: Y
> CUDA support will be enabled for TensorFlow.
> 
> Please specify the CUDA SDK version you want to use. [Leave empty to default to CUDA 9.0]:
> 
> 
> Please specify the location where CUDA 9.0 toolkit is installed. Refer to README.md for more details. [Default is C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0]:
> 
> 
> Please specify the cuDNN version you want to use. [Leave empty to default to cuDNN 7]:
> 
> 
> Please specify the location where cuDNN 7 library is installed. Refer to README.md for more details. [Default is C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0]:
> 
> 
> Please specify a list of comma-separated Cuda compute capabilities you want to build with.
> You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
> Please note that each additional compute capability significantly increases your build time and binary size. [Default is: 3.5,7.0]: 5.0
> 
> 
> Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is /arch:AVX]:
> 
> Would you like to override eigen strong inline for some C++ compilation to reduce the compilation time? [Y/n]: N
> Not overriding eigen strong inline, some compilations could take more than 20 mins.

> C:\tensorflow>bazel build --config=opt --config=cuda --define=no_tensorflow_py_deps=true //tensorflow/tools/pip_package:build_pip_package

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
```
INFO: From Linking tensorflow/contrib/resampler/python/ops/_resampler_ops.so:
   Creating library bazel-out/x64_windows-opt/bin/tensorflow/contrib/resampler/python/ops/lib_resampler_ops.so.ifso and object bazel-out/x64_windows-opt/bin/tensorflow/contrib/resampler/python/ops/lib_resampler_ops.so.exp
ERROR: C:/tensorflow/tensorflow/BUILD:533:1: Executing genrule //tensorflow:tf_python_api_gen_v1 failed (Exit 1): bash.exe failed: error executing command
  cd C:/users/nickeys/_bazel_nickeys/xv6zejqw/execroot/org_tensorflow
  SET CUDA_TOOLKIT_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0
    SET CUDNN_INSTALL_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0
    SET PATH=C:\msys64\usr\bin;C:\msys64\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\libnvvp;C:\Users\nickeys\AppData\Local\Programs\Python\Python36\Scripts;C:\Users\nickeys\AppData\Local\Programs\Python\Python36;C:\Users\nickeys\apps;C:\msys64\usr\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\extras\CUPTI\libx64;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Program Files\Dell\DW WLAN Card;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\dotnet\;;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Users\nickeys\AppData\Local\Programs\Python\Python36\Scripts\;C:\Users\nickeys\AppData\Local\Programs\Python\Python36\;C:\Users\nickeys\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Bandizip\
    SET PYTHON_BIN_PATH=C:/Users/nickeys/AppData/Local/Programs/Python/Python36/python.exe
    SET PYTHON_LIB_PATH=C:/Users/nickeys/AppData/Local/Programs/Python/Python36/lib/site-packages
    SET TF_CUDA_CLANG=0
    SET TF_CUDA_COMPUTE_CAPABILITIES=5.0
    SET TF_CUDA_VERSION=9.0
    SET TF_CUDNN_VERSION=7
    SET TF_NEED_CUDA=1
    SET TF_NEED_OPENCL_SYCL=0
    SET TF_NEED_ROCM=0
  C:/msys64/usr/bin/bash.exe -c source external/bazel_tools/tools/genrule/genrule-setup.sh; bazel-out/x64_windows-opt/bin/tensorflow/create_tensorflow.python_api_1.exe --root_init_template=tensorflow/api_template.__init__.py --apidir=bazel-out/x64_windows-opt/genfiles/tensorflow_api/v1/ --apiname=tensorflow --apiversion=1 --package=tensorflow.python --output_package=tensorflow._api.v1 bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/app/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/bitwise/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/compat/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/data/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/data/experimental/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/debugging/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/distributions/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/dtypes/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/errors/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/feature_column/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/gfile/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/graph_util/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/image/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/io/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/initializers/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/keras/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/keras/activations/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/keras/applications/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/keras/applications/densenet/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/keras/applications/inception_resnet_v2/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/keras/applications/inception_v3/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/keras/applications/mobilenet/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/keras/applications/mobilenet_v2/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/keras/applications/nasnet/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/keras/applications/resnet50/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/keras/applications/vgg16/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/keras/applications/vgg19/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/keras/applications/xception/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/keras/backend/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/keras/callbacks/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/keras/constraints/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/keras/datasets/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/keras/datasets/boston_housing/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/keras/datasets/cifar10/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/keras/datasets/cifar100/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/keras/datasets/fashion_mnist/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/keras/datasets/imdb/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/keras/datasets/mnist/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/keras/datasets/reuters/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/keras/estimator/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/keras/initializers/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/keras/layers/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/keras/losses/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/keras/metrics/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/keras/models/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/keras/optimizers/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/keras/preprocessing/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/keras/preprocessing/image/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/keras/preprocessing/sequence/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/keras/preprocessing/text/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/keras/regularizers/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/keras/utils/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/keras/wrappers/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/keras/wrappers/scikit_learn/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/layers/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/linalg/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/logging/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/losses/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/manip/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/math/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/metrics/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/nn/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/nn/rnn_cell/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/profiler/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/python_io/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/quantization/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/random/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/resource_loader/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/strings/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/saved_model/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/saved_model/builder/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/saved_model/constants/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/saved_model/loader/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/saved_model/main_op/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/saved_model/signature_constants/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/saved_model/signature_def_utils/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/saved_model/tag_constants/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/saved_model/utils/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/sets/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/sparse/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/spectral/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/summary/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/sysconfig/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/test/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/train/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/train/queue_runner/__init__.py bazel-out/x64_windows-opt/genfiles/tensorflow/_api/v1/user_ops/__init__.py
Traceback (most recent call last):
  File "\\?\C:\Users\nickeys\AppData\Local\Temp\Bazel.runfiles_s3knfdzs\runfiles\org_tensorflow\tensorflow\python\tools\api\generator\create_python_api.py", line 27, in <module>
    from tensorflow.python.tools.api.generator import doc_srcs
  File "\\?\C:\Users\nickeys\AppData\Local\Temp\Bazel.runfiles_s3knfdzs\runfiles\org_tensorflow\tensorflow\python\__init__.py", line 47, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 3196.198s, Critical Path: 2857.14s
INFO: 992 processes: 992 local.
FAILED: Build did NOT complete successfully
```

**Comment by jvishnuvardhan** [comment]
@nickeys This looks to be an error in numpy.
Could you check your numpy version?
You may try uninstalling numpy, and installing 1.15.4.
```
pip uninstall numpy
pip install numpy==1.15.4
```
Please let us know whether it resolved or not. Thanks!

**Comment by nickeys** [comment]
@jvishnuvardhan OK~ Thanks. I'm about to initiate the build after change version of 'numpy' to 1.15.4. So, I'm going to tell you the result later because it will cost a lot of time, I suppose :-).

**Comment by nickeys** [comment]
Oh... the build failed again! BTW the result seems to be changed a little bit.

```
ERROR: C:/users/nickeys/_bazel_nickeys/xv6zejqw/external/local_config_python/BUILD:148:1: Executing genrule @local_config_python//:numpy_include failed (Exit 1): bash.exe failed: error executing command
  cd C:/users/nickeys/_bazel_nickeys/xv6zejqw/execroot/org_tensorflow
  SET CUDA_TOOLKIT_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0
    SET CUDNN_INSTALL_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0
    SET PATH=C:\msys64\usr\bin;C:\msys64\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\libnvvp;C:\Users\nickeys\AppData\Local\Programs\Python\Python36\Scripts;C:\Users\nickeys\AppData\Local\Programs\Python\Python36;C:\Users\nickeys\apps;C:\msys64\usr\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\extras\CUPTI\libx64;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Program Files\Dell\DW WLAN Card;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\dotnet\;;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Users\nickeys\AppData\Local\Programs\Python\Python36\Scripts\;C:\Users\nickeys\AppData\Local\Programs\Python\Python36\;C:\Users\nickeys\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Bandizip\
    SET PYTHON_BIN_PATH=C:/Users/nickeys/AppData/Local/Programs/Python/Python36/python.exe
    SET PYTHON_LIB_PATH=C:/Users/nickeys/AppData/Local/Programs/Python/Python36/lib/site-packages
    SET TF_CUDA_CLANG=0
    SET TF_CUDA_COMPUTE_CAPABILITIES=5.0
    SET TF_CUDA_VERSION=9.0
    SET TF_CUDNN_VERSION=7
    SET TF_NEED_CUDA=1
    SET TF_NEED_OPENCL_SYCL=0
    SET TF_NEED_ROCM=0
  C:/msys64/usr/bin/bash.exe -c source external/bazel_tools/tools/genrule/genrule-setup.sh;
cp -f "C:/Users/nickeys/AppData/Roaming/Python/Python36/site-packages/numpy/core/include/numpy/__multiarray_api.h" "bazel-out/x64_windows-opt/genfiles/external/local_config_python/numpy_include/numpy/__multiarray_api.h" && cp -f "C:/Users/nickeys/AppData/Roaming/Python/Python36/site-packages/numpy/core/include/numpy/__ufunc_api.h" "bazel-out/x64_windows-opt/genfiles/external/local_config_python/numpy_include/numpy/__ufunc_api.h" && cp -f "C:/Users/nickeys/AppData/Roaming/Python/Python36/site-packages/numpy/core/include/numpy/_neighborhood_iterator_imp.h" "bazel-out/x64_windows-opt/genfiles/external/local_config_python/numpy_include/numpy/_neighborhood_iterator_imp.h" && cp -f "C:/Users/nickeys/AppData/Roaming/Python/Python36/site-packages/numpy/core/include/numpy/_numpyconfig.h" "bazel-out/x64_windows-opt/genfiles/external/local_config_python/numpy_include/numpy/_numpyconfig.h" && cp -f "C:/Users/nickeys/AppData/Roaming/Python/Python36/site-packages/numpy/core/include/numpy/arrayobject.h" "bazel-out/x64_windows-opt/genfiles/external/local_config_python/numpy_include/numpy/arrayobject.h" && cp -f "C:/Users/nickeys/AppData/Roaming/Python/Python36/site-packages/numpy/core/include/numpy/arrayscalars.h" "bazel-out/x64_windows-opt/genfiles/external/local_config_python/numpy_include/numpy/arrayscalars.h" && cp -f "C:/Users/nickeys/AppData/Roaming/Python/Python36/site-packages/numpy/core/include/numpy/halffloat.h" "bazel-out/x64_windows-opt/genfiles/external/local_config_python/numpy_include/numpy/halffloat.h" && cp -f "C:/Users/nickeys/AppData/Roaming/Python/Python36/site-packages/numpy/core/include/numpy/multiarray_api.txt" "bazel-out/x64_windows-opt/genfiles/external/local_config_python/numpy_include/numpy/multiarray_api.txt" && cp -f "C:/Users/nickeys/AppData/Roaming/Python/Python36/site-packages/numpy/core/include/numpy/ndarrayobject.h" "bazel-out/x64_windows-opt/genfiles/external/local_config_python/numpy_include/numpy/ndarrayobject.h" && cp -f "C:/Users/nickeys/AppData/Roaming/Python/Python36/site-packages/numpy/core/include/numpy/ndarraytypes.h" "bazel-out/x64_windows-opt/genfiles/external/local_config_python/numpy_include/numpy/ndarraytypes.h" && cp -f "C:/Users/nickeys/AppData/Roaming/Python/Python36/site-packages/numpy/core/include/numpy/noprefix.h" "bazel-out/x64_windows-opt/genfiles/external/local_config_python/numpy_include/numpy/noprefix.h" && cp -f "C:/Users/nickeys/AppData/Roaming/Python/Python36/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h" "bazel-out/x64_windows-opt/genfiles/external/local_config_python/numpy_include/numpy/npy_1_7_deprecated_api.h" && cp -f "C:/Users/nickeys/AppData/Roaming/Python/Python36/site-packages/numpy/core/include/numpy/npy_3kcompat.h" "bazel-out/x64_windows-opt/genfiles/external/local_config_python/numpy_include/numpy/npy_3kcompat.h" && cp -f "C:/Users/nickeys/AppData/Roaming/Python/Python36/site-packages/numpy/core/include/numpy/npy_common.h" "bazel-out/x64_windows-opt/genfiles/external/local_config_python/numpy_include/numpy/npy_common.h" && cp -f "C:/Users/nickeys/AppData/Roaming/Python/Python36/site-packages/numpy/core/include/numpy/npy_cpu.h" "bazel-out/x64_windows-opt/genfiles/external/local_config_python/numpy_include/numpy/npy_cpu.h" && cp -f "C:/Users/nickeys/AppData/Roaming/Python/Python36/site-packages/numpy/core/include/numpy/npy_endian.h" "bazel-out/x64_windows-opt/genfiles/external/local_config_python/numpy_include/numpy/npy_endian.h" && cp -f "C:/Users/nickeys/AppData/Roaming/Python/Python36/site-packages/numpy/core/include/numpy/npy_interrupt.h" "bazel-out/x64_windows-opt/genfiles/external/local_config_python/numpy_include/numpy/npy_interrupt.h" && cp -f "C:/Users/nickeys/AppData/Roaming/Python/Python36/site-packages/numpy/core/include/numpy/npy_math.h" "bazel-out/x64_windows-opt/genfiles/external/local_config_python/numpy_include/numpy/npy_math.h" && cp -f "C:/Users/nickeys/AppData/Roaming/Python/Python36/site-packages/numpy/core/include/numpy/npy_no_deprecated_api.h" "bazel-out/x64_windows-opt/genfiles/external/local_config_python/numpy_include/numpy/npy_no_deprecated_api.h" && cp -f "C:/Users/nickeys/AppData/Roaming/Python/Python36/site-packages/numpy/core/include/numpy/npy_os.h" "bazel-out/x64_windows-opt/genfiles/external/local_config_python/numpy_include/numpy/npy_os.h" && cp -f "C:/Users/nickeys/AppData/Roaming/Python/Python36/site-packages/numpy/core/include/numpy/numpyconfig.h" "bazel-out/x64_windows-opt/genfiles/external/local_config_python/numpy_include/numpy/numpyconfig.h" && cp -f "C:/Users/nickeys/AppData/Roaming/Python/Python36/site-packages/numpy/core/include/numpy/old_defines.h" "bazel-out/x64_windows-opt/genfiles/external/local_config_python/numpy_include/numpy/old_defines.h" && cp -f "C:/Users/nickeys/AppData/Roaming/Python/Python36/site-packages/numpy/core/include/numpy/oldnumeric.h" "bazel-out/x64_windows-opt/genfiles/external/local_config_python/numpy_include/numpy/oldnumeric.h" && cp -f "C:/Users/nickeys/AppData/Roaming/Python/Python36/site-packages/numpy/core/include/numpy/ufunc_api.txt" "bazel-out/x64_windows-opt/genfiles/external/local_config_python/numpy_include/numpy/ufunc_api.txt" && cp -f "C:/Users/nickeys/AppData/Roaming/Python/Python36/site-packages/numpy/core/include/numpy/ufuncobject.h" "bazel-out/x64_windows-opt/genfiles/external/local_config_python/numpy_include/numpy/ufuncobject.h" && cp -f "C:/Users/nickeys/AppData/Roaming/Python/Python36/site-packages/numpy/core/include/numpy/utils.h" "bazel-out/x64_windows-opt/genfiles/external/local_config_python/numpy_include/numpy/utils.h"

cp: cannot stat 'C:/Users/nickeys/AppData/Roaming/Python/Python36/site-packages/numpy/core/include/numpy/__multiarray_api.h': No such file or directory
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 244.986s, Critical Path: 18.11s
INFO: 1346 processes: 1346 local.
FAILED: Build did NOT complete successfully
```

**Comment by nickeys** [comment]
At last, I could resolve the problem! Thanks to @jvishnuvardhan . I solved the other problem caused by the wrong reference to numpy package, by copying the numpy package from the original python library path.

**Comment by jvishnuvardhan** [comment]
I am closing this as it was resolved. Thanks!

**Comment by dksb** [comment]
Are you satisfied with the resolution of your issue?<br> [Yes](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=Yes&entry.2137816233=25732)<br> [No](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=No&entry.2137816233=25732)
