### ISSUE TITLE
Tensorflow 1.12.0 not working with CUDA 10.0

### ISSUE THREAD

**Issue by Rov67777** [tensorflow/tensorflow#25789]
**System information**
- OS Platform and Distribution: Linux Ubuntu 16.04
- TensorFlow installed from (source or binary): pip install tensorflow-gpu
- TensorFlow version: version 1.12.0
- Python version: 3.5.5
- Installed using virtualenv? pip? conda?: pip
- CUDA/cuDNN version: CUDA version 10.0
- GPU model and memory: Tesla V100

when I just try to import tensorflow I get this error message:

```
Python 3.5.5 |Anaconda custom (64-bit)| (default, May 13 2018, 21:12:35)
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
Traceback (most recent call last):
  File "/anaconda/envs/py35/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/anaconda/envs/py35/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/anaconda/envs/py35/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/anaconda/envs/py35/lib/python3.5/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/anaconda/envs/py35/lib/python3.5/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda/envs/py35/lib/python3.5/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/anaconda/envs/py35/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/anaconda/envs/py35/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/anaconda/envs/py35/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/anaconda/envs/py35/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/anaconda/envs/py35/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/anaconda/envs/py35/lib/python3.5/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/anaconda/envs/py35/lib/python3.5/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

**Comment by wdirons** [comment]
In order to use TensorFlow 1.12 with CUDA 10 you need to build TensorFlow from source. 
https://www.tensorflow.org/install/source

You may also try the 1.13.0rc1 release candidate build which is built with CUDA 10.

`pip install tensorflow-gpu==1.13.0rc1`

**Comment by ymodak** [comment]
Closing this issue since the wdiron's explanation is correct. Feel free to post a new issue if having problems  in installing TF 1.13.0-rc1/1.13.0-rc2 both are built with CUDA 10. Thanks!

**Comment by AthenaChara** [comment]
Hello, Tensorflow 1.14 worked for me! wouldn't suggest to use release canditate (rc) version. 

> pip install tensorflow-gpu==1.14
