### ISSUE TITLE
Please delete this

### ISSUE THREAD

**Issue by CraigMyles** [tensorflow/tensorflow#25823]
incredibly easy fix slightly unrelated to tensorflow

**Comment by CraigMyles** [comment]
I have now tried using tensorflow 1.10 and i am getting the following error: (hypergan) C:\Users\Craig\Documents\LLD>hypergan train sample -s 32x32x3 -f png -b 8 --config wgan-gp --sampler static_batch --sample_every 5 --save_samples
Traceback (most recent call last):
  File "C:\Users\Craig\.conda\envs\hypergan\lib\site-packages\tensorflow\python\platform\self_check.py", line 87, in preload_check
    ctypes.WinDLL(build_info.cudnn_dll_name)
  File "C:\Users\Craig\.conda\envs\hypergan\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Craig\.conda\envs\hypergan\Scripts\\hypergan", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\envs\hypergan\HyperGAN\bin\hypergan", line 7, in <module>
    import hypergan as hg
  File "c:\program files (x86)\microsoft visual studio\shared\anaconda3_64\envs\hypergan\hypergan\hypergan\__init__.py", line 17, in <module>
    from .gan import GAN
  File "c:\program files (x86)\microsoft visual studio\shared\anaconda3_64\envs\hypergan\hypergan\hypergan\gan.py", line 1, in <module>
    from hypergan.gans.standard_gan import StandardGAN
  File "c:\program files (x86)\microsoft visual studio\shared\anaconda3_64\envs\hypergan\hypergan\hypergan\gans\standard_gan.py", line 10, in <module>
    from hypergan.discriminators import *
  File "c:\program files (x86)\microsoft visual studio\shared\anaconda3_64\envs\hypergan\hypergan\hypergan\discriminators\autoencoder_discriminator.py", line 1, in <module>
    import tensorflow as tf
  File "C:\Users\Craig\.conda\envs\hypergan\lib\site-packages\tensorflow\__init__.py", line 22, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\Craig\.conda\envs\hypergan\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Craig\.conda\envs\hypergan\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 30, in <module>
    self_check.preload_check()
  File "C:\Users\Craig\.conda\envs\hypergan\lib\site-packages\tensorflow\python\platform\self_check.py", line 97, in preload_check
    % (build_info.cudnn_dll_name, build_info.cudnn_version_number))
ImportError: Could not find 'cudnn64_7.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Note that installing cuDNN is a separate step from installing CUDA, and this DLL is often found in a different directory from the CUDA DLLs. You may install the necessary DLL by downloading cuDNN 7 from this URL: https://developer.nvidia.com/cudnn

**Comment by CraigMyles** [comment]
fixed this with getting cudnn cuda stuff from nvidia dev site
