### ISSUE TITLE
CUDNN_STATUS_INTERNAL_ERROR while using tensorflow.keras.applications.VGG16

### ISSUE THREAD

**Issue by csakvarimate** [tensorflow/tensorflow#25830]
I am trying to use a pretrained network from tensorflow.keras.applications with 1.13rc2 and it crashes with a cudnn error.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 18.04):
- TensorFlow installed from source: 1.13.0-rc2
- TensorFlow version (use command below):
- Python version: 3.6.5
- Bazel version: 0.22
- GCC/Compiler version: 7.3
- CUDA/cuDNN version: 10.0 / 7.4.2
- GPU model and memory: GeForce RTX 2070 8GB

**Code to reproduce the issue**

Minimal working example:

```python
import numpy as np
from keras.applications import VGG16
if __name__ == "__main__":
    model = VGG16(weights='imagenet', include_top=True, input_shape=(224,224,3))
    model.compile(optimizer="rmsprop", loss="categorical_crossentropy")
    X_train = np.ones((2000, 224, 224, 3))
    y_train = np.ones((2000, 1000))
    model.fit(x=X_train, y=y_train, epochs=50, batch_size=16)
```
**Other info / logs**

Using TensorFlow backend.
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
2019-02-18 09:11:29.560595: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3399705000 Hz
2019-02-18 09:11:29.561392: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x2116980 executing computations on platform Host. Devices:
2019-02-18 09:11:29.561431: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
2019-02-18 09:11:30.251516: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:998] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-02-18 09:11:30.252153: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x2ddff10 executing computations on platform CUDA. Devices:
2019-02-18 09:11:30.252175: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): GeForce RTX 2070, Compute Capability 7.5
2019-02-18 09:11:30.252593: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties: 
name: GeForce RTX 2070 major: 7 minor: 5 memoryClockRate(GHz): 1.725
pciBusID: 0000:26:00.0
totalMemory: 7.76GiB freeMemory: 7.64GiB
2019-02-18 09:11:30.252614: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2019-02-18 09:11:30.253693: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-02-18 09:11:30.253709: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0 
2019-02-18 09:11:30.253716: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N 
2019-02-18 09:11:30.254007: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7436 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2070, pci bus id: 0000:26:00.0, compute capability: 7.5)
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Epoch 1/50
2019-02-18 09:11:34.331098: I tensorflow/stream_executor/dso_loader.cc:152] successfully opened CUDA library libcublas.so.10.0 locally
2019-02-18 09:11:35.167778: E tensorflow/stream_executor/cuda/cuda_dnn.cc:334] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-02-18 09:11:35.167818: W ./tensorflow/stream_executor/stream.h:2099] attempting to perform DNN operation using StreamExecutor without DNN support
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    model.fit(x=X_train, y=y_train, epochs=50, batch_size=16)
  File "/home/mate/dev/backend/env/backend/lib/python3.6/site-packages/keras/engine/training.py", line 1039, in fit
    validation_steps=validation_steps)
  File "/home/mate/dev/backend/env/backend/lib/python3.6/site-packages/keras/engine/training_arrays.py", line 199, in fit_loop
    outs = f(ins_batch)
  File "/home/mate/dev/backend/env/backend/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "/home/mate/dev/backend/env/backend/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1439, in __call__
    run_metadata_ptr)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InternalError: cuDNN launch failure : input shape([16,3,224,224]) filter shape([3,3,3,64])
	 [[{{node block1_conv1/convolution}}]]
	 [[{{node loss/mul}}]]

**Comment by ztoser** [comment]
Same issue here. It was even present on 1.13.0-rc1. I tried compiling rc2 without XLA, but it did not help.

**Comment by timshen91** [comment]
@Artem-B This looks like what we've seen internally. Do you want to take on this?

**Comment by ztoser** [comment]
Instead of
`from keras.applications import VGG16`
I used
`from tensorflow.keras.applications import VGG16`
and retested this under a self-compiled TensorFlow 1.13.1. It works without any issues now.

**Comment by sachinprasadhs** [comment]
@csakvarimate , I was able to run in  Tensorflow GPU version 2.4  successfully without any error by modifying code, please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/68467d5b386b4fc0819e5a88bda4c57b/25830.ipynb).
