### ISSUE TITLE
Error installing/running Tensorflow-GPU version

### ISSUE THREAD

**Issue by vinodk333** [tensorflow/tensorflow#25870]
Unable to install/run tensorflow-gpu in my system.  Below error am getting.  I tried with Python 3.7, then downgraded it to py 3.6.8 and then to 3.6.5, but the end result is the same.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): installed using pip3
- TensorFlow version: GPU version 1.12.0
- Python version: 3.7.x, 3.6.8, 3.6.5
- Installed using virtualenv? pip? conda?: pip
- CUDA/cuDNN version: Quadro M1200
- GPU model and memory: NVIDIA 4 GB

**Describe the problem**
Traceback (most recent call last):
File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in 
from tensorflow.python.pywrap_tensorflow_internal import *
File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in 
_pywrap_tensorflow_internal = swig_import_helper()
File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
_mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
File "C:\ProgramData\Anaconda3\lib\imp.py", line 242, in load_module
return load_dynamic(name, filename, file)
File "C:\ProgramData\Anaconda3\lib\imp.py", line 342, in load_dynamic
return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "chatbot.py", line 4, in 
import tensorflow as tf
File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow__init__.py", line 24, in 
from tensorflow.python import pywrap_tensorflow # pylint: disable=unused-import
File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python__init__.py", line 49, in 
from tensorflow.python import pywrap_tensorflow
File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in 
raise ImportError(msg)
ImportError: Traceback (most recent call last):
File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in 
from tensorflow.python.pywrap_tensorflow_internal import *
File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in 
_pywrap_tensorflow_internal = swig_import_helper()
File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
_mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
File "C:\ProgramData\Anaconda3\lib\imp.py", line 242, in load_module
return load_dynamic(name, filename, file)
File "C:\ProgramData\Anaconda3\lib\imp.py", line 342, in load_dynamic
return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by jvishnuvardhan** [comment]
@vinodk333 Please check [tested build config](https://www.tensorflow.org/install/source_windows#gpu). For your version you need to downgrade some modules, build and install the TF1.12 version. Thanks!

**Comment by jvishnuvardhan** [comment]
@vinodk333 Please also check there is a known issue with windows10 on character [limit](https://www.howtogeek.com/266621/how-to-make-windows-10-accept-file-paths-over-260-characters/). Thanks!

**Comment by jvishnuvardhan** [comment]
I think it was resolved. Closing due to lack of recent activity. Please open new ticket if you see similar issue. Thanks!
