### ISSUE TITLE
Model with mirror pad can run using Desktop tflite but can't run using Android tflite

### ISSUE THREAD

**Issue by PK15946** [tensorflow/tensorflow#25931]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Ubuntu16.04
- TensorFlow installed from (source or binary):binary
- TensorFlow version (or github SHA if from source):'1.13.0-dev20190215'

I notice that since 11/20/2018, [mirror pad](https://github.com/tensorflow/tensorflow/issues/23962#issuecomment-442147097) was supported in TFlite, and I can successfully convert and interpret the converted model with newest tensorflow on computer.

However, when I try to use that model on Android phone , it can't be interpreted. Here is message from Android studio:
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: android.example.com.tflitecamerademo, PID: 22917
    java.lang.RuntimeException: Unable to start activity ComponentInfo{android.example.com.tflitecamerademo/com.example.android.tflitecamerademo.CameraActivity}: java.lang.IllegalArgumentException: ByteBuffer is not a valid flatbuffer model
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2931)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1620)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:176)
        at android.app.ActivityThread.main(ActivityThread.java:6701)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:246)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
     Caused by: java.lang.IllegalArgumentException: ByteBuffer is not a valid flatbuffer model
        at org.tensorflow.lite.NativeInterpreterWrapper.createModelWithBuffer(Native Method)
        at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:59)
        at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:188)
        at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:176)
        at com.example.android.tflitecamerademo.ImageClassifier.<init>(ImageClassifier.java:106)
        at com.example.android.tflitecamerademo.Camera2BasicFragment.onActivityCreated(Camera2BasicFragment.java:303)
        at android.app.Fragment.performActivityCreated(Fragment.java:2620)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1296)
        at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2420)
        at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2199)
        at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2153)
        at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2054)
        at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3049)
        at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2996)
        at android.app.FragmentController.dispatchActivityCreated(FragmentController.java:178)
        at android.app.Activity.performCreateCommon(Activity.java:7044)
        at android.app.Activity.performCreate(Activity.java:7052)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2809)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2931) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1620) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:176) 
        at android.app.ActivityThread.main(ActivityThread.java:6701) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:246) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783) 
```
and this is part of  build.gradle:
```
repositories {
    maven {
        url 'https://google.bintray.com/tensorflow'
    }
    google()
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:25.2.0'
    compile 'com.android.support.constraint:constraint-layout:1.1.0'
    compile 'com.android.support:design:25.2.0'
    compile 'com.android.support:support-annotations:25.3.1'
    compile 'com.android.support:support-v13:25.2.0'

    compile 'org.tensorflow:tensorflow-lite:0.0.0-nightly'

    testCompile 'junit:junit:4.12'
}

```
Based on what I have experienced, `ByteBuffer is not a valid flatbuffer model` may caused by unsupported ops in model.

So I delete all the mirror pad(tf.pad), and use 'SAME' padding in conv, this time the model can run on both desktop and Android phone.

Because the tflite I use on android phone is `org.tensorflow:tensorflow-lite:0.0.0-nightly`, it should be the newest and should support mirror pad, then why it can't be interpreted?

Any suggestion would be appreciated !

**Comment by karimnosseir** [comment]
Hi,
Is it possible to share the model, or if you have mini model that can reproduce this failure. So we can check what is failing.

Thanks

**Comment by PK15946** [comment]
Thanks for your reply @karimnosseir , 

I am trying to reproduce the error with a mini model but fail. I suspect it was caused by the third party api(tensorlayer) I used, and I am rewriting the model using tf-slim, if the error persist, I will leave a comment.

**Comment by PK15946** [comment]
Hi, @karimnosseir 

With tf-slim, the `ByteBuffer is not a valid flatbuffer model` no longer exist.

But a strange thing still persist.

If I use "same" padding, a inference of an image use converted tflite model takes about 0.7g ram on my computer;  If I use "reflect + 'valid'" padding, the same process takes 5g ram.

Here is the mini model:
[issue.tar.gz](https://github.com/tensorflow/tensorflow/files/2926225/issue.tar.gz)
it is very shallow but needs 5g ram to run with reflect padding. As it goes deeper, even more memory is needed. Is that normal?

Thanks

**Comment by PK15946** [comment]
HI, @karimnosseir  
Is that issue reproducible?

**Comment by karimnosseir** [comment]
Hi PK15946,

Sorry for the delay. I didn't have time to check it. Will do next week and get back to you.
Sorry for the delay again.

**Comment by PK15946** [comment]
Ok, thank you in advance for your time @karimnosseir

**Comment by karimnosseir** [comment]
Hi PK15946

A fix was submitted earlier today. Can you try from master branch or nightly (after it includes the latest change) and let me know if you are still having problem.

I am going to close this bug now. Feel free to create new issue if you still facing problems and assign it to me.

Thanks
