### ISSUE TITLE
Tensorflow-gpu import error (solved)

### ISSUE THREAD

**Issue by CrabBucket** [tensorflow/tensorflow#26059]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Win 10

- TensorFlow installed from (source or binary):Source? Not to sure just using pip3
- TensorFlow version: tensorflow-gpu-1.12.0
- Python version: 3.6.8
- Installed using virtualenv? pip? conda?: pip3 inside a virtualenv environment.
- Bazel version (if compiling from source):N/A
- GCC/Compiler version (if compiling from source):N/A
- CUDA/cuDNN version:10.0
- GPU model and memory: GTX 1080 8192 MB

**Describe the problem**
When attempting to do anything involving tensorflow it errors.  Errors while running "import tensorflow as tf"  I looked at some older issues that were similar but trying to do what they said did not solve my problem.  First attempt was them saying use an older version of tensorflow but to do so I would need to downgrade CUDA to 9.0 not sure if that's what I should do.  I have tried to uninstall reinstall to no avail.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
```
C:\>pip install --upgrade pip
C:\>pip install virtualenv
C:\>virtualenv --system-site-packages -p "C:\Users\Kathy\AppData\Local\Programs\Python\Python36\python.exe" ./venv
C:\>.\venv\Scripts\activate
(venv) C:\>pip3 install tensorflow-gpu
(venv) C:\>python
>>>import tensorflow as tf
```

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
```

Traceback (most recent call last):
  File "C:\Users\Kathy\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Kathy\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Kathy\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Kathy\venv\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Kathy\venv\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Kathy\venv\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\Kathy\venv\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Kathy\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Kathy\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Kathy\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Kathy\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Kathy\venv\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Kathy\venv\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

```

**Comment by ymodak** [comment]
TensorFlow 1.13.0-rc2 has released which supports cuda 10. You might want to give it a try instead.

**Comment by CrabBucket** [comment]
```
>>> import tensorflow as tf
Traceback (most recent call last):
  File "C:\Users\Kathy\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Kathy\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Kathy\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Kathy\venv\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Kathy\venv\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Kathy\venv\lib\site-packages\tensorflow\__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\Kathy\venv\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Kathy\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Kathy\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Kathy\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Kathy\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Kathy\venv\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Kathy\venv\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

after running running pip3 uninstall tensorflow-gpu then pip3 install tf-nightly-gpu

**Comment by ymodak** [comment]
Did you update the path for cuda, cudnn as per the [windows setup guide](https://www.tensorflow.org/install/gpu#windows_setup)?

**Comment by CrabBucket** [comment]
I believe so https://i.imgur.com/bc9AImq.png

I tried adding them to the user variables as well.  cudnn64_7.dll is inside the CUDA bin folder do I need to create a separate folder for it and then path to that as well? Or do I need to name the dll files explicitly in the path?

**Comment by ymodak** [comment]
You need to sub folders: bin and lib to the path. I see that lib folder is not added to the path.

**Comment by rygo6** [comment]
I have this same exact issue too. Win10, only I am using CUDA 9 toolkit. 

I just added 
`C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\lib`
per ymodak's instruction, but that did not work. 

What else could it be?

**Comment by CrabBucket** [comment]
https://i.imgur.com/m4azsmP.png Thank you ymodak this was it for me.  rygo6 I would suggest you uninstall everything and follow the guide ymodak posted (https://www.tensorflow.org/install/gpu#windows_setup) from start to finish and if that doesn't work then create your own issue.

**Comment by ymodak** [comment]
@CrabBucket Glad it worked for you. I will close this issue now since its solved.
@rygo6 Can you please post issue by providing all the information asked in the [build/installation](https://github.com/tensorflow/tensorflow/issues/new?template=10-build-installation-issue.md) template? Thanks!

**Comment by ymodak** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
