### ISSUE TITLE
1.13.0-rc2 gpu doesnt work

### ISSUE THREAD

**Issue by Gytis123** [tensorflow/tensorflow#26077]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: no
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.13.0-rc2
- Python version: 3.6.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10 / 7.3.1
- GPU model and memory: NVIDIA GeForce GTX 1070 Ti
[trainingres.txt](https://github.com/tensorflow/tensorflow/files/2899440/trainingres.txt)

Image recognition error:

WARNING:tensorflow:From C:\Users\navickg\AppData\Local\Programs\Python\Python36\Image_NEW_GPU\tensorflow\python\ops\resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
Traceback (most recent call last):
  File "C:\Users\navickg\AppData\Local\Programs\Python\Python36\itemtestprediction.py", line 16, in <module>
    predictions, probabilities = predictionPet.predictImage("C:\\Users\\navickg\\AppData\\Local\\Programs\\Python\\Python36\\testimages\\lawnmower.jpg", result_count=5)
  File "C:\Users\navickg\AppData\Local\Programs\Python\Python36\Image_NEW_GPU\imageai\Prediction\Custom\__init__.py", line 588, in predictImage
    prediction = model.predict(x=image_to_predict, steps=1)
  File "C:\Users\navickg\AppData\Local\Programs\Python\Python36\Image_NEW_GPU\tensorflow\python\keras\engine\training.py", line 1113, in predict
    self, x, batch_size=batch_size, verbose=verbose, steps=steps)
  File "C:\Users\navickg\AppData\Local\Programs\Python\Python36\Image_NEW_GPU\tensorflow\python\keras\engine\training_arrays.py", line 266, in model_iteration
    batch_outs = f(actual_inputs)
  File "C:\Users\navickg\AppData\Local\Programs\Python\Python36\Image_NEW_GPU\tensorflow\python\keras\backend.py", line 3076, in __call__
    run_metadata=self.run_metadata)
  File "C:\Users\navickg\AppData\Local\Programs\Python\Python36\Image_NEW_GPU\tensorflow\python\client\session.py", line 1439, in __call__
    run_metadata_ptr)
  File "C:\Users\navickg\AppData\Local\Programs\Python\Python36\Image_NEW_GPU\tensorflow\python\framework\errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node conv2d/Conv2D}}]]
	 [[{{node dense/Softmax}}]]

While 1.12 built from source Tensorflow version works without any issues

**Comment by ymodak** [comment]
I suspect its due to version mismatch of  cuDNN for CUDA and NVIDIA Hardware. Please take look at [cuDNN Support Matrix](https://docs.nvidia.com/deeplearning/sdk/cudnn-support-matrix/index.html) to know more.

**Comment by Gytis123** [comment]
Thanks, I'll try to install newest cudnn version

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
