### ISSUE TITLE
ImportError: DLL load failed

### ISSUE THREAD

**Issue by flybikeGx** [tensorflow/tensorflow#26114]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): windows 10 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pip
- TensorFlow version: 1.12.0
- Python version: Python 3.6.8
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: cuda 9.2.148.1
- GPU model and memory: GTX 1060 6GB

**Describe the problem**

work well with tensorflow, but get error when change to tensorflow-gpu

I ran ```pip install tensorflow``` and all things goes OK, but then I ran ```pip install tensorflow-gpu```, get errors below

```
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: 找不到指定的模块。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: 找不到指定的模块。


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by flybikeGx** [comment]
cuDNN version is v7.5.0.56, and all three things added to path

**Comment by ymodak** [comment]
TF 1.12 supports cuda 9.0 . Please lower your cuda version to 9.0.

**Comment by rishi-rranjan** [comment]
I am getting this error while compiling TF GPU  v1,13,1 with windows 10.

**Comment by flybikeGx** [comment]
> TF 1.12 supports cuda 9.0 . Please lower your cuda version to 9.0.

problem solved, but when i run examples in https://www.tensorflow.org/tutorials/keras/basic_text_classification, its just nothing better than CPU only. I wonder if I get something wrong or it should be that?

**Comment by rishi-rranjan** [comment]
This issue is still there with v1.13.1, I am trying master branch to check if it compiles.

**Comment by rishi-rranjan** [comment]
master barnch keeps giving following error:

nvcc error   : 'cudafe++' died with status 0xC0000005 (ACCESS_VIOLATION)
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 4770.792s, Critical Path: 472.50s
INFO: 1547 processes: 1547 local.
FAILED: Build did NOT complete successfully

**Comment by ymodak** [comment]
@flybikeGx The training time for your model can be reduced drastically when computed on gpu compared to cpu computation. If you compare the training time elapsed for both you will find that gpu is much superior.
@rishi-rranjan Can you please post a [new issue](https://github.com/tensorflow/tensorflow/issues/new?template=10-build-installation-issue.md) by providing the information asked by the template?
The reason for this is we can focus on your specific configuration and problem since the root cause can be unrelated even though the error messages are similar. Thanks!

**Comment by rehadiri** [comment]
I have win 10 and Nvidia Geforce 920M on my laptop. I am using Python 3.6.4 and Pycharm as IDE.

I have also faced the same problem. After having tried several versions i could manage to solve the problem by installing the following versions:

Keras 2.2.4
Tensorflow 1.12.0
Cuda 9.0
CuDNN 7.4 ( Dnn for Cuda 9.0 )

You can find Cuda 9.0 and CuDNN in Nvidia Archive Site

Works Perfect !

**Comment by rehadiri** [comment]
Tensorflow is Tensorflow-gpu by the way
