### ISSUE TITLE
"The name 'input:0' refers to a Tensor which does not exist. The operation, 'input', does not exist in the graph."

### ISSUE THREAD

**Issue by sumit1212** [tensorflow/tensorflow#26129]
**I have same issue.
  I have doing real time face recognition using tensorflow. I'm follow this link "https://github.com/btwardow/tf-face-recognition" When I'm download clone repo it work in one system but try to run another one this show me error. Please help me out.**

`Traceback (most recent call last):
File "server.py", line 49, in detect
faces = recognize(detection.get_faces(image, threshold))
File "/home/bigblue/Music/Test/tf-face-recognition-master/tensorface/recognition.py", line 19, in recognize
X[i, :] = embedding(img_to_np(img))
File "/home/bigblue/Music/Test/tf-face-recognition-master/tensorface/embedding.py", line 43, in embedding
images_placeholder = tf.get_default_graph().get_tensor_by_name("input:0")
File "/home/bigblue/anaconda3/envs/my_env/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3666, in get_tensor_by_name
return self.as_graph_element(name, allow_tensor=True, allow_operation=False)
File "/home/bigblue/anaconda3/envs/my_env/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3490, in as_graph_element
return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
File "/home/bigblue/anaconda3/envs/my_env/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3532, in _as_graph_element_locked
"graph." % (repr(name), repr(op_name)))
**KeyError: "The name 'input:0' refers to a Tensor which does not exist. The operation, 'input', does not exist in the graph."**
[2019-02-26 11:28:06,532] ERROR in app: Exception on /detect [POST]
Traceback (most recent call last):
File "server.py", line 49, in detect
faces = recognize(detection.get_faces(image, threshold))
File "/home/bigblue/Music/Test/tf-face-recognition-master/tensorface/recognition.py", line 19, in recognize
X[i, :] = embedding(img_to_np(img))
File "/home/bigblue/Music/Test/tf-face-recognition-master/tensorface/embedding.py", line 43, in embedding
images_placeholder = tf.get_default_graph().get_tensor_by_name("input:0")
File "/home/bigblue/anaconda3/envs/my_env/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3666, in get_tensor_by_name
return self.as_graph_element(name, allow_tensor=True, allow_operation=False)
File "/home/bigblue/anaconda3/envs/my_env/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3490, in as_graph_element
return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
File "/home/bigblue/anaconda3/envs/my_env/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3532, in _as_graph_element_locked
"graph." % (repr(name), repr(op_name)))
KeyError: "The name 'input:0' refers to a Tensor which does not exist. The operation, 'input', does not exist in the graph."

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/bigblue/anaconda3/envs/my_env/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
response = self.full_dispatch_request()
File "/home/bigblue/anaconda3/envs/my_env/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/home/bigblue/anaconda3/envs/my_env/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/home/bigblue/anaconda3/envs/my_env/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
raise value
File "/home/bigblue/anaconda3/envs/my_env/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
rv = self.dispatch_request()
File "/home/bigblue/anaconda3/envs/my_env/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "server.py", line 69, in detect
print('POST /detect error: %e' % e)
TypeError: must be real number, not KeyError`

**Comment by jvishnuvardhan** [comment]
@sumit1212 I noticed this as a duplicate issue as you posted it on original "tf-face-recognition" Repo and that is correct place for this issue. This is not Build/Installation or Bug/Performance issue related to TF. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!

**Comment by archenroot** [comment]
@jvishnuvardhan - but this error occurs across multiple project in the wild...
