### ISSUE TITLE
[SOLVED] Failed to build 1.13.0-rc2 with CUDA in Windows 7

### ISSUE THREAD

**Issue by reinert** [tensorflow/tensorflow#26227]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): WINDOWS 7
- TensorFlow installed from (source or binary): SOURCE
- TensorFlow version: 1.13.0-rc2
- Python version: 3.7
- Installed using virtualenv? pip? conda?: building
- Bazel version (if compiling from source): 0.21
- GCC/Compiler version (if compiling from source): MSVS 2015 14.0.24215.1
- CUDA/cuDNN version: 10 / 7.4.2.24
- GPU model and memory: NVIDIA QUADRO k5000 4GB (3.0)

**Describe the problem**
Building from source in Windows 7 with CUDA 10 support for 3.0 computing capability, with a clean Python 3.7 installation, fails with the message: `ImportError: DLL load failed: The specified module could not be found.`

**Provide the exact sequence of commands / steps that you executed before running into the problem**
* Installed CUDA 10 and cuDnn 7.4.2.24
* Installed mysys64 in C:/mysys64
* Installed bazel 0.21
* Installed a fresh 3.7 Python in %APPDATA%/Programs/Python
* pip3 install six numpy wheel
* pip3 install keras_applications --no-deps
* pip3 install keras_preprocessing --no-deps
* configured all enviroment variables according to the tutorial
* downloaded and extracted tensorflow 1.13.0-rc2 release
* opened VS 2015 x64 Native Tools Command Prompt as Administrator
* entered the tensorflow source dir
* python ./configure.py
* bazel build --config=opt --config=cuda --define=no_tensorflow_py_deps=true //tensorflow/tools/pip_package:build_pip_package

**Any other info / logs**
```cmd
INFO: From Linking tensorflow/contrib/boosted_trees/python/ops/_boosted_trees_ops.so:
   Creating library bazel-out/x64_windows-opt/bin/tensorflow/contrib/boosted_trees/python/ops/python/ops/lib_boosted_trees_ops.so.ifso and object bazel-out/x64_windows-opt/bin/tensorflow/contrib/boosted_trees/python/ops/
INFO: From Linking tensorflow/contrib/tpu/python/ops/_tpu_ops.so:
   Creating library bazel-out/x64_windows-opt/bin/tensorflow/contrib/tpu/python/ops/python/ops/lib_tpu_ops.so.ifso and object bazel-out/x64_windows-opt/bin/tensorflow/contrib/tpu/python/ops/python/ops/lib_tpu_ops.so.exp
ERROR: C:/users/reinert/downloads/tensorflow-1.13.0-rc2/tensorflow/BUILD:573:1: Executing genrule //tensorflow:tf_python_api_gen_v1 failed (Exit 1): bash.exe failed: error executing command
  cd C:/users/reinert/_bazel_reinert/kbgdyy6s/execroot/org_tensorflow
  SET CUDA_TOOLKIT_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0
    SET CUDNN_INSTALL_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0
    SET PATH=C:\msys64\usr\bin;C:\msys64\bin
    SET PYTHON_BIN_PATH=C:/Users/reinert/AppData/Local/Programs/Python/Python37/python.exe
    SET PYTHON_LIB_PATH=C:/Users/reinert/AppData/Local/Programs/Python/Python37/lib/site-packages
    SET TF_CUDA_CLANG=0
    SET TF_CUDA_COMPUTE_CAPABILITIES=3.0
    SET TF_CUDA_VERSION=10.0
    SET TF_CUDNN_VERSION=7
    SET TF_NEED_CUDA=1
    SET TF_NEED_OPENCL_SYCL=0
    SET TF_NEED_ROCM=0
  C:/msys64/usr/bin/bash.exe bazel-out/x64_windows-opt/genfiles/tensorflow/tf_python_api_gen_v1.genrule_script.sh
Execution platform: @bazel_tools//platforms:host_platform
Traceback (most recent call last):
  File "\\?\C:\Users\reinert\AppData\Local\Temp\Bazel.runfiles_t5_pd1qh\runfiles\org_tensorflow\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "\\?\C:\Users\reinert\AppData\Local\Temp\Bazel.runfiles_t5_pd1qh\runfiles\org_tensorflow\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "\\?\C:\Users\reinert\AppData\Local\Temp\Bazel.runfiles_t5_pd1qh\runfiles\org_tensorflow\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\reinert\AppData\Local\Programs\Python\Python37\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\reinert\AppData\Local\Programs\Python\Python37\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "\\?\C:\Users\reinert\AppData\Local\Temp\Bazel.runfiles_t5_pd1qh\runfiles\org_tensorflow\tensorflow\python\tools\api\generator\create_python_api.py", line 27, in <module>
    from tensorflow.python.tools.api.generator import doc_srcs
  File "\\?\C:\Users\reinert\AppData\Local\Temp\Bazel.runfiles_t5_pd1qh\runfiles\org_tensorflow\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "\\?\C:\Users\reinert\AppData\Local\Temp\Bazel.runfiles_t5_pd1qh\runfiles\org_tensorflow\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "\\?\C:\Users\reinert\AppData\Local\Temp\Bazel.runfiles_t5_pd1qh\runfiles\org_tensorflow\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "\\?\C:\Users\reinert\AppData\Local\Temp\Bazel.runfiles_t5_pd1qh\runfiles\org_tensorflow\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "\\?\C:\Users\reinert\AppData\Local\Temp\Bazel.runfiles_t5_pd1qh\runfiles\org_tensorflow\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\reinert\AppData\Local\Programs\Python\Python37\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\reinert\AppData\Local\Programs\Python\Python37\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 2166,410s, Critical Path: 1238,93s
INFO: 4651 processes: 4651 local.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
```

**Comment by jvishnuvardhan** [comment]
@reinert Could you follow the instructions [here](https://github.com/jvishnuvardhan/Installing-TensorFlow-GPU-on-Windows-10-TF1.12/blob/master/README.md) to install TF. The instructions are mainly for installing TF1.12 with CUDA9.0 but you can follow the same approach but use updated files/drivers etc. Please let me know how it progresses. Thanks!

**Comment by reinert** [comment]
Hi, I followed the instructions and now the error is different (it seems to be in a later step):

```cmd
   Creating library bazel-out/x64_windows-opt/bin/tensorflow/cc/ops/nn_ops_gen_cc.lib and object bazel-out/x64_windows-opt/bin/tensorflow/cc/ops/nn_ops_gen_cc.exp
INFO: From Linking tensorflow/cc/ops/sparse_ops_gen_cc:
LINK : warning LNK4044: unrecognized option '/Wl,-rpath,../local_config_cuda/cuda/lib64'; ignored
LINK : warning LNK4044: unrecognized option '/Wl,-rpath,../local_config_cuda/cuda/extras/CUPTI/lib64'; ignored
   Creating library bazel-out/x64_windows-opt/bin/tensorflow/cc/ops/sparse_ops_gen_cc.lib and object bazel-out/x64_windows-opt/bin/tensorflow/cc/ops/sparse_ops_gen_cc.exp
INFO: From Linking tensorflow/cc/ops/logging_ops_gen_cc:
LINK : warning LNK4044: unrecognized option '/Wl,-rpath,../local_config_cuda/cuda/lib64'; ignored
LINK : warning LNK4044: unrecognized option '/Wl,-rpath,../local_config_cuda/cuda/extras/CUPTI/lib64'; ignored
   Creating library bazel-out/x64_windows-opt/bin/tensorflow/cc/ops/logging_ops_gen_cc.lib and object bazel-out/x64_windows-opt/bin/tensorflow/cc/ops/logging_ops_gen_cc.exp
ERROR: C:/tf2/tensorflow/contrib/tpu/BUILD:137:1: Executing genrule //tensorflow/contrib/tpu:tpu_ops_pygenrule failed (Exit 3): bash.exe failed: error executing command
  cd C:/users/reinert/_bazel_reinert/6gxwwe2m/execroot/org_tensorflow
  SET CUDA_TOOLKIT_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0
    SET CUDNN_INSTALL_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0
    SET PATH=C:\msys64\usr\bin;C:\msys64\bin
    SET PYTHON_BIN_PATH=C:/Users/reinert/AppData/Local/Programs/Python/Python37/python.exe
    SET PYTHON_LIB_PATH=C:/Users/reinert/AppData/Local/Programs/Python/Python37/lib/site-packages
    SET TF_CUDA_CLANG=0
    SET TF_CUDA_COMPUTE_CAPABILITIES=3.0
    SET TF_CUDA_VERSION=10.0
    SET TF_CUDNN_VERSION=7
    SET TF_NEED_CUDA=1
    SET TF_NEED_OPENCL_SYCL=0
    SET TF_NEED_ROCM=0
  C:/msys64/usr/bin/bash.exe -c source external/bazel_tools/tools/genrule/genrule-setup.sh; bazel-out/x64_windows-opt/bin/tensorflow/contrib/tpu/gen_tpu_ops_py_wrappers_cc , SendTPUEmbeddingGradients,EnqueueTPUEmbeddingIntegerBatch,En
PUEmbeddingSparseBatch,EnqueueTPUEmbeddingSparseTensorBatch 0 0 > bazel-out/x64_windows-opt/genfiles/tensorflow/contrib/tpu/ops/gen_tpu_ops.py
Execution platform: @bazel_tools//platforms:host_platform
[libprotobuf ERROR external/protobuf_archive/src/google/protobuf/descriptor_database.cc:318] Invalid file descriptor data passed to EncodedDescriptorDatabase::Add().
[libprotobuf FATAL external/protobuf_archive/src/google/protobuf/descriptor.cc:1358] CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size):
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 2064,588s, Critical Path: 591,08s
INFO: 4424 processes: 4424 local.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
```

**Comment by reinert** [comment]
After running again, I got the same initial error. It keeps crashing while creating this `lib_tpu_ops`. Is there anyway to disable TPU in the building process?

**Comment by reinert** [comment]
Maybe related to https://github.com/tensorflow/tensorflow/commit/cbe8172cba4f2ed05a0980585ba48ef257922c18 ?

**Comment by reinert** [comment]
Can I disable building the `contrib` directory?

**Comment by jvishnuvardhan** [comment]
@reinert Did you uninstall everything before installing TF with the instructions I provided? Thanks!

**Comment by reinert** [comment]
No, I didn't. But I've found the problem is not related to TPU contrib. Instead it's related to this `swig` lib. I found many issues regarding it. I'll dig deeper and report here what I can.

**Comment by gunan** [comment]
When building on windows ` --define=no_tensorflow_py_deps=true` should not be used.
That is an option we created for testing only.

**Comment by HarryHHung** [comment]
My "ImportError: DLL load failed" issue was solved after I downgraded to bazel 0.20.

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 7
- TensorFlow installed from (source or binary): Source
- TensorFlow version: 1.13.1
- Python version: 3.7.2
- Installed using virtualenv? pip? conda?: building
- Bazel version (if compiling from source): 0.20
- GCC/Compiler version (if compiling from source): MSVC 19.00.24215.1 for x64
- CUDA/cuDNN version: 10.1 / 7.5.0
- GPU model and memory: NVIDIA GeForce GTX 1060 6 GB

**Comment by ttdd11** [comment]
@HarryHHung did you build tensorflow_cc.dll for windows?

**Comment by HarryHHung** [comment]
No, I only have built a whl for python.

**Comment by reinert** [comment]
I finally got it! After 3 weeks trying :)

Thank you @gunan and @HarryHHung for the valuable tips.

I'm now haing an issue to build the whl. Here's the error:
```cmd
unzip:  cannot find zipfile directory in one of ./bazel-bin/tensorflow/tools/pip_package/simple_console_for_windows.zip or
        ./bazel-bin/tensorflow/tools/pip_package/simple_console_for_windows.zip.zip, and cannot find ./bazel-bin/tensorflow/tools/pip_package/simple_console_for_windows.zip.ZIP, period.
```

**Comment by HarryHHung** [comment]
I have seen the 0-byte issue before.

https://stackoverflow.com/questions/52394305/creating-pip-package-for-tensorflow-with-gpu-support-results-in-0-byte-simple-co/

**Comment by reinert** [comment]
And you were right again! Thank you very much @HarryHHung! Tensorflow with GPU support is now installed in my machine. My build environment is as follows:

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 7
- TensorFlow version: 1.13.1
- Python version: 3.7.2
- Bazel version: 0.20.0
- GCC/Compiler version: MSVC 19.00.24215.1 for x64 (MSVC 2015 Update 3)
- CUDA/cuDNN version: 10.0 / 7.4
- GPU model and memory: NVIDIA Quadro K5000 4GB

My two cents: After setting everything up and building for the first time, the build can fail, but you must try building again (`bazel build ...`). Sometimes the build passes on the second attempt.

**Comment by jvishnuvardhan** [comment]
Closing this out since I understand it to be resolved, but please let me know if I'm mistaken. Thanks!
