### ISSUE TITLE
Tensorboard 1.12 not working after upgrade from 1.8 to 1.12

### ISSUE THREAD

**Issue by sgvarsh** [tensorflow/tensorflow#26226]
I upgraded tensorflow to 1.12 which also upgraded tensorboard to 1.12 from 1.8 version but I get the error:
Traceback (most recent call last):
  File "/usr/local/bin/tensorboard", line 7, in <module>
    from tensorboard.main import run_main
  File "/usr/local/lib/python3.6/site-packages/tensorboard/main.py", line 44, in <module>
    from tensorboard import default
  File "/usr/local/lib/python3.6/site-packages/tensorboard/default.py", line 44, in <module>
    from tensorboard.plugins.interactive_inference import interactive_inference_plugin
  File "/usr/local/lib/python3.6/site-packages/tensorboard/plugins/interactive_inference/interactive_inference_plugin.py", line 27, in <module>
    from grpc.framework.interfaces.face.face import AbortionError
ModuleNotFoundError: No module named 'grpc.framework'

I unsintalled and reinstalled grpcio, I completely removed tensorflow and tensorboard and then re-installed 1.12 version but same error keeps coming back.

**Comment by ymodak** [comment]
This issue is more appropriate on **tensorflow/tensorboard repo**. Please post it on tensorboard from [here](https://github.com/tensorflow/tensorboard/issues/new) and provide all the information asked by the template. Thanks!
