### ISSUE TITLE
cannot import tensorflow

### ISSUE THREAD

**Issue by liuxinni0406** [tensorflow/tensorflow#26240]
**System information**
- Win10 X64 :
- pip install tensorflow-gpu==1.12.0
- TensorFlow version:
- Python version: 3.6
- Installed using  pip
- GCC/Compiler version (if compiling from source):
- CUDA: 9 
- cuDNN version: 7
- GPU model and memory: NVIDIA GeForce MX150

**Describe the problem**
cannot import tensorflow,  always this error: tensorflow.python.pywrap_tensorflow_internal import *,
I have checked therre is no related DLL existed, and i know it is an install issue. I have searched many same issue and tried to fix, but it does not work . 

PS: This issue only for tensorflow-gpu install, it's ok for tensorflow install on the same machine. But i want to use tensorflow-gpu.

>>> import tensorflow as tf
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Program Files\Python36\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Program Files\Python36\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: 找不到指定的模块。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Program Files\Python36\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Program Files\Python36\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: 找不到指定的模块。

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by ielenik** [comment]
Looks like TensorFlow have moved to Cuda 10
[screen](https://yadi.sk/i/zDgz_13_2UfY_Q)
But that is just the half of the problem
The real problem is that Cuda 10 is not available at nvidea web site (I found only 10.1)

**Comment by ielenik** [comment]
I have tried to make a copy of cublas64_10 with cublas64_100 name, tensorflow loaded but ended up with "unknown cuda error"

**Comment by jvishnuvardhan** [comment]
@liuxinni0406 Could try the instruction [here](https://github.com/jvishnuvardhan/Installing-TensorFlow-GPU-on-Windows-10-TF1.12) that worked for installing TF1.12_gpu successfully. Please uninstall python and tensorflow then follow the instruction to install the TF1.12. Please let me know how it progresses. Thanks!

**Comment by liuxinni0406** [comment]
> @liuxinni0406 Could try the instruction [here](https://github.com/jvishnuvardhan/Installing-TensorFlow-GPU-on-Windows-10-TF1.12) that worked for installing TF1.12_gpu successfully. Please uninstall python and tensorflow then follow the instruction to install the TF1.12. Please let me know how it progresses. Thanks!

Have tried as your step, but the same issue as before. I think there might be some environment issue, but i cannot find the problem. Thank you.

**Comment by Culeshovi** [comment]
@liuxinni0406 You can install tensorflow-gpu for windows easily on Anaconda. Here's the link https://anaconda.org/anaconda/tensorflow-gpu

**Comment by jvishnuvardhan** [comment]
There are solutions and workarounds presented in a similar issue #26182. Please go through them if your issue was not resolved. I am closing this issue. Thanks!
