### ISSUE TITLE
Failed to get device properties, error code: 30

### ISSUE THREAD

**Issue by Sawatdatta** [tensorflow/tensorflow#26255]
Failed to initialize GPU device #0: unknown error

Os: windows 10
Tensorflow version: 1.13.1
Keras Version: 2.1.6
CUDA version: 10(major)
Cudnn version: 7.5
python 3.6

I got following error:

WARNING:tensorflow:From C:\Users\SUS\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\backend\tensorflow_backend.py:3144: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
Created base network...
(1, 1)
Tensor("Shape:0", shape=(2,), dtype=int32)
Training started...
WARNING:tensorflow:From C:\Users\SUS\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Epoch 1/20
2019-03-01 16:54:42.970057: I tensorflow/stream_executor/dso_loader.cc:152] successfully opened CUDA library cublas64_100.dll locally
Traceback (most recent call last):
  File "C:\Users\SUS\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1334, in _do_call
    return fn(*args)
  File "C:\Users\SUS\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "C:\Users\SUS\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InternalError: CUB reduce errorinvalid configuration argument
	 [[{{node dense_1/Sum}}]]
	 [[{{node loss/add_1}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:/Implementation/Rtip2r_Conference18/siamese/signet_distance/SigNet_stat_measures_more.py", line 370, in <module>
    main(args)
  File "F:/Implementation/Rtip2r_Conference18/siamese/signet_distance/SigNet_stat_measures_more.py", line 333, in main
    callbacks=[checkpointer, tbpointer])  # KERAS 2
  File "C:\Users\SUS\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\SUS\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\training.py", line 2230, in fit_generator
    class_weight=class_weight)
  File "C:\Users\SUS\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\training.py", line 1883, in train_on_batch
    outputs = self.train_function(ins)
  File "C:\Users\SUS\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\backend\tensorflow_backend.py", line 2482, in __call__
    **self.session_kwargs)
  File "C:\Users\SUS\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 929, in run
    run_metadata_ptr)
  File "C:\Users\SUS\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\SUS\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1328, in _do_run
    run_metadata)
  File "C:\Users\SUS\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: CUB reduce errorinvalid configuration argument
	 [[node dense_1/Sum (defined at C:\Users\SUS\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\backend\tensorflow_backend.py:1269) ]]
	 [[node loss/add_1 (defined at C:\Users\SUS\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\training.py:848) ]]

Caused by op 'dense_1/Sum', defined at:
  File "F:/Implementation/Rtip2r_Conference18/siamese/signet_distance/SigNet_stat_measures_more.py", line 370, in <module>
    main(args)
  File "F:/Implementation/Rtip2r_Conference18/siamese/signet_distance/SigNet_stat_measures_more.py", line 274, in main
    base_network = create_base_network_signet(input_shape)
  File "F:/Implementation/Rtip2r_Conference18/siamese/signet_distance/SigNet_stat_measures_more.py", line 139, in create_base_network_signet
    seq.add(Dense(1024, kernel_regularizer=l2(0.0005), activation="relu", kernel_initializer="glorot_uniform"))
  File "C:\Users\SUS\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\models.py", line 522, in add
    output_tensor = layer(self.outputs[0])
  File "C:\Users\SUS\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\topology.py", line 592, in __call__
    self.build(input_shapes[0])
  File "C:\Users\SUS\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\layers\core.py", line 864, in build
    constraint=self.kernel_constraint)
  File "C:\Users\SUS\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\SUS\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\topology.py", line 418, in add_weight
    self.add_loss(regularizer(weight))
  File "C:\Users\SUS\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\regularizers.py", line 42, in __call__
    regularization += K.sum(self.l2 * K.square(x))
  File "C:\Users\SUS\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\backend\tensorflow_backend.py", line 1269, in sum
    return tf.reduce_sum(x, axis, keepdims)
  File "C:\Users\SUS\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\Users\SUS\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\math_ops.py", line 1286, in reduce_sum_v1
    return reduce_sum(input_tensor, axis, keepdims, name)
  File "C:\Users\SUS\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\util\dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "C:\Users\SUS\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\math_ops.py", line 1334, in reduce_sum
    name=name))
  File "C:\Users\SUS\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 10209, in _sum
    name=name)
  File "C:\Users\SUS\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\SUS\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\Users\SUS\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 3300, in create_op
    op_def=op_def)
  File "C:\Users\SUS\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

InternalError (see above for traceback): CUB reduce errorinvalid configuration argument
	 [[node dense_1/Sum (defined at C:\Users\SUS\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\backend\tensorflow_backend.py:1269) ]]
	 [[node loss/add_1 (defined at C:\Users\SUS\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\training.py:848) ]]

Process finished with exit code 1

I have tried updating tensorflow to 2.0-preview but that leads to other errors like module ConfigProto not found.

Please help to resolve this issue.

**Comment by jvishnuvardhan** [comment]
@Sawatdatta Could you provide more details on the issue and its context. If possible, provide a code to reproduce the bug. Thanks!

**Comment by Sawatdatta** [comment]
@jvishnuvardhan  I have updated the TensorFlow to 2.0-preview which resolved this issue but Keras backend is using updated TensorFlow and causing no module errors is there any way to force Keras to use compat.V1 modules

**Comment by jvishnuvardhan** [comment]
@Sawatdatta why do you want to force Keras to use compat.V1 modules? Thanks!

**Comment by Sawatdatta** [comment]
> 
> 
> @Sawatdatta why do you want to force Keras to use compat.V1 modules? Thanks!

Since Keras cannot find the modules(used in my code) in the 2.0-preview, and I don't want to change my existing code.

**Comment by stevehawley** [comment]
I'm also seeing this unknown error.
```
2019-04-19 13:16:22.838705: E tensorflow/core/grappler/clusters/utils.cc:83] Failed to get device properties, error code: 30
Failed to initialize GPU device #0: unknown error
```
My configuration:
Windows 10 Home
Tensorflow 1.13.1
Python 3.5
GTX 1060 Mobile Max-Q

It doesn't happen every time I run my program. I have localized it to running load_model from keras, before reaching that point I have imported tensorflow and verified that gpu is available.
```python
  if tf.test.is_gpu_available():
        logger.debug("GPU is available")
```
Switching to tensorflow 2 alpha is not an option for me at this time. 

Is there a way to catch this error or check for it and recover/attempt to reinitialize?

Thanks

**Comment by ijiroterunao** [comment]
i have the same problem,and at the end i found that because i use double GPU ,one is intel GPU,another one is nvidia GPU,so i opened nvidia control panel,changed my prefer graphic processor to nvidia GPU instead of auto choose(auto choose intel GPU or nvidia GPU),that works for me .

**Comment by crobertob** [comment]
Thanks @ijiroterunao ! I had the same problem and could not figure out a solution until I came upong your answer.
