### ISSUE TITLE
Failed to pip install tensorflow-gpu 

### ISSUE THREAD

**Issue by jiapei100** [tensorflow/tensorflow#26290]
```
# sudo pip install -U tensorflow-gpu --user
Collecting tensorflow-gpu
  Downloading https://files.pythonhosted.org/packages/7b/b1/0ad4ae02e17ddd62109cd54c291e311c4b5fd09b4d0678d3d6ce4159b0f0/tensorflow_gpu-1.13.1-cp36-cp36m-manylinux1_x86_64.whl (345.2MB)
    99% |████████████████████████████████| 345.2MB 53.0MB/s eta 0:00:01Exception:
Traceback (most recent call last):
  File "/root/.local/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 179, in main
    status = self.run(options, args)
  File "/root/.local/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 315, in run
    resolver.resolve(requirement_set)
  File "/root/.local/lib/python3.6/site-packages/pip/_internal/resolve.py", line 131, in resolve
    self._resolve_one(requirement_set, req)
  File "/root/.local/lib/python3.6/site-packages/pip/_internal/resolve.py", line 294, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/root/.local/lib/python3.6/site-packages/pip/_internal/resolve.py", line 242, in _get_abstract_dist_for
    self.require_hashes
  File "/root/.local/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 334, in prepare_linked_requirement
    progress_bar=self.progress_bar
  File "/root/.local/lib/python3.6/site-packages/pip/_internal/download.py", line 878, in unpack_url
    progress_bar=progress_bar
  File "/root/.local/lib/python3.6/site-packages/pip/_internal/download.py", line 702, in unpack_http_url
    progress_bar)
  File "/root/.local/lib/python3.6/site-packages/pip/_internal/download.py", line 946, in _download_http_url
    _download_url(resp, link, content_file, hashes, progress_bar)
  File "/root/.local/lib/python3.6/site-packages/pip/_internal/download.py", line 639, in _download_url
    hashes.check_against_chunks(downloaded_chunks)
  File "/root/.local/lib/python3.6/site-packages/pip/_internal/utils/hashes.py", line 62, in check_against_chunks
    for chunk in chunks:
  File "/root/.local/lib/python3.6/site-packages/pip/_internal/download.py", line 607, in written_chunks
    for chunk in chunks:
  File "/root/.local/lib/python3.6/site-packages/pip/_internal/utils/ui.py", line 159, in iter
    for x in it:
  File "/root/.local/lib/python3.6/site-packages/pip/_internal/download.py", line 596, in resp_read
    decode_content=False):
  File "/root/.local/lib/python3.6/site-packages/pip/_vendor/urllib3/response.py", line 494, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/root/.local/lib/python3.6/site-packages/pip/_vendor/urllib3/response.py", line 442, in read
    data = self._fp.read(amt)
  File "/root/.local/lib/python3.6/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 65, in read
    self._close()
  File "/root/.local/lib/python3.6/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 52, in _close
    self.__callback(self.__buf.getvalue())
  File "/root/.local/lib/python3.6/site-packages/pip/_vendor/cachecontrol/controller.py", line 300, in cache_response
    cache_url, self.serializer.dumps(request, response, body=body)
  File "/root/.local/lib/python3.6/site-packages/pip/_vendor/cachecontrol/serialize.py", line 72, in dumps
    return b",".join([b"cc=4", msgpack.dumps(data, use_bin_type=True)])
MemoryError
```

**Comment by kunakl07** [comment]
I would like to solve this error

**Comment by kunakl07** [comment]
@jiapei100 You are having a Memory Issue.The space is not getting allocated.
You will be able to run this command in google [colab](https://www.google.com/search?q=google+colab&oq=googlecol&aqs=chrome.1.69i57j0l5.3345j0j7&sourceid=chrome&ie=UTF-8) by typing the following command
"! sudo pip install -U tensorflow-gpu --user"
Thank you for asking questions and please do ask if you have anymore doubts 
Would be please to answer them

**Comment by jiapei100** [comment]
@kunakl07 
Hey, did you ever try to build tensorflow from source ?
[https://github.com/tensorflow/tensorflow/issues/26289](https://github.com/tensorflow/tensorflow/issues/26289)

**Comment by Mainak431** [comment]
You are having a memory error. If you are using a VM, make sure you allocate more RAM . Try to build tensorflow-gpu from source. Still if its not done. I prefer you try it on Google-Colab.

**Comment by jvishnuvardhan** [comment]
@jiapei100 I provided a solution in the other issue that you opened and referenced [here](https://github.com/tensorflow/tensorflow/issues/26289). Please let me know how it progresses. You could close this issue and we can resolve there in the other post. Thanks!

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by jvishnuvardhan** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will open a new issue. Thanks!
