### ISSUE TITLE
LookupError: No gradient defined for operation 'MatrixLogarithm'

### ISSUE THREAD

**Issue by ZhangXiao96** [tensorflow/tensorflow#26321]
**System information**
- OS Platform and Distribution :Linux Ununtu 14.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.13.1
- Python version: 3.6
- CUDA/cuDNN version: 10.0/7.4.2
- GPU model and memory: GeForce GTX 1080/ 8G

**Describe the current behavior**
There is no gradient defined for tf.linalg.logm(), therefore it could not be used in training procedures.

**Comment by ZhangXiao96** [comment]
Hello， I wonder if this issue has already been solved?
However, I found that if the input matrix is the symmetric matrix, then we could use the following way to replace tf.linalg.logm():

```
def logm(A):
    e, v = tf.linalg.eigh(A)
    e = tf.linalg.diag(tf.log(e))
    return tf.matmul(v, tf.matmul(e, tf.linalg.inv(v)))
```

and this operation is derivable.

**Comment by rmothukuru** [comment]
@ZhangXiao96,
Sorry for the delayed response. Can you please let us know if this is resolved so that we can close it? Thanks!

**Comment by Randl** [comment]
Not the OP, but tf 2.4.1 still lacks gradients for matrix logarithm:
```
>>> mat = tf.Variable([[5,2,3],
...                    [2,9,4],
...                    [3,2,6.]], dtype = tf.complex64)
>>> with tf.GradientTape() as tape:
...   loss = tf.reduce_sum(tf.linalg.logm(mat))
... 
>>> grad = tape.gradient(loss, mat)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/evgeniizh/.conda/envs/lstf/lib/python3.9/site-packages/tensorflow/python/eager/backprop.py", line 1080, in gradient
    flat_grad = imperative_grad.imperative_grad(
  File "/home/evgeniizh/.conda/envs/lstf/lib/python3.9/site-packages/tensorflow/python/eager/imperative_grad.py", line 71, in imperative_grad
    return pywrap_tfe.TFE_Py_TapeGradient(
  File "/home/evgeniizh/.conda/envs/lstf/lib/python3.9/site-packages/tensorflow/python/eager/backprop.py", line 151, in _gradient_function
    grad_fn = ops._gradient_registry.lookup(op_name)  # pylint: disable=protected-access
  File "/home/evgeniizh/.conda/envs/lstf/lib/python3.9/site-packages/tensorflow/python/framework/registry.py", line 98, in lookup
    raise LookupError(
LookupError: gradient registry has no entry for: MatrixLogarithm
```

**Comment by sanatmpa1** [comment]
Issue still persists in 2.6.0 and nightly. Here's the [gist](https://colab.research.google.com/gist/sanatmpa1/74dd60a85de8e6ecdc823e6bb99d4b9a/26321.ipynb)

**Comment by SuryanarayanaY** [comment]
Hi,
The issue replicated in both tf 2.10 and nightly versions.Please refer the attached [gist](https://colab.research.google.com/gist/SuryanarayanaY/935aaa12feee21c77766197089ae556e/26321.ipynb) here.
Thankyou!

**Comment by redwrasse** [comment]
Looks like derivative of matrix logarithm remains unimplemented. Is it computationally non-trivial to add in? I understand depending on what is being differentiated with respect to, commutation relations need to be considered, but am not an expert in the numerical methods.

Noting in `tf.linalg.logm` docs that derivatives are unsupported would probably be a good idea.

Here's a simple restricted case, resulting in the `LookupError: gradient registry has no entry for: MatrixLogarithm`:

```
import tensorflow as tf


# simple example: dlogA/dA = A^-1 for A invertible

# so dlogA/dA at A = I should be I^-1 = I


def sanity_check_matrix_log_derivative():

    A = tf.eye(2, 2, dtype=tf.complex64)

    with tf.GradientTape() as tape:
        tape.watch(A)
        logA = tf.linalg.logm(A)
        # log I = 0
        tf.assert_equal(logA, tf.zeros(shape=(2,2), dtype=tf.complex64))
        # dlogA/dA at A = I = I^-1 = I
        dlogA_dA = tape.gradient(logA, A)
        tf.assert_equal(dlogA_dA, tf.eye(2,2, dtype=tf.complex64))


sanity_check_matrix_log_derivative()

```

**Comment by cantonios** [comment]
Someone can create a PR for it if they like.  This is just not a high priority for the TF team.

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
