### ISSUE TITLE
Installation issues with cuda10.1

### ISSUE THREAD

**Issue by deepnarainsingh** [tensorflow/tensorflow#26416]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS  Linux Ubuntu 16.04:
- TensorFlow installed from (source or binary): pip install tensorflow-gpu==2.0.0-alpha0
- TensorFlow version:2.0.0-alpha0
- Python version:2.7
- Installed using virtualenv? pip? conda?:pip 
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:10.1
- GPU model and memory:Titan

**Describe the problem**

After the installation of tensorflow2.0 alpha package and running the python file
with 
*import tensorflow as tf*
getting below error :

"ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory
"

**Any other info / logs**
File "/home/deep/tf2.0/local/lib/python2.7/site-packages/tensorflow/__init__.py", line 27, in <module>
    from tensorflow._api.v2 import audio
  File "/home/deep/tf2.0/local/lib/python2.7/site-packages/tensorflow/_api/v2/audio/__init__.py", line 8, in <module>
    from tensorflow.python.ops.gen_audio_ops import decode_wav
  File "/home/deep/tf2.0/local/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/deep/tf2.0/local/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/deep/tf2.0/local/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/deep/tf2.0/local/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/deep/tf2.0/local/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory

**Comment by ymodak** [comment]
Please switch to cuda 10.0 and build again since the pre compiled TF 2.0 binaries support cuda 10. Thanks!

**Comment by deepnarainsingh** [comment]
@ymodak  Switching to cuda 10.0 resolved the issue. Didn't required a new tf 2.0 build.
Thanks.
