### ISSUE TITLE
ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[1711991009] and type int32 on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc

### ISSUE THREAD

**Issue by Sission** [tensorflow/tensorflow#26419]
I tried to run a VAE code in my new desktop. It can run the tensorflow with GPU. However, when I tried some code in github, the error comes.
Code source: https://github.com/hwalsuklee/tensorflow-mnist-VAE

System information

OS Platform and Distribution: Windows 10
TensorFlow installed from: source
TensorFlow version: 1.12
Python version: 3.6.8
Installed using virtualenv? pip? conda?: pip
Bazel version (if compiling from source): 0.17
CUDA/cuDNN version: cuda 10.0 cuDNN 7.4.2
GPU model and memory: Nvidia RTX 2080ti

Error:

G:\PythonLib\tensorflow-mnist-VAE-master>python run_main.py --dim_z 2
Extracting data\train-images-idx3-ubyte.gz
Extracting data\train-labels-idx1-ubyte.gz
Extracting data\t10k-images-idx3-ubyte.gz
Extracting data\t10k-labels-idx1-ubyte.gz
2019-03-06 21:47:07.963506: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2019-03-06 21:47:08.167281: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties:
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.635
pciBusID: 0000:01:00.0
totalMemory: 11.00GiB freeMemory: 9.03GiB
2019-03-06 21:47:08.173938: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2019-03-06 21:47:08.579713: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-03-06 21:47:08.584136: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0
2019-03-06 21:47:08.586602: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N
2019-03-06 21:47:08.588443: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8706 MB memory) -> physica
l GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:01:00.0, compute capability: 7.5)
Traceback (most recent call last):
  File "C:\Users\shica\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1334, in _do_call
    return fn(*args)
  File "C:\Users\shica\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "C:\Users\shica\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [2] vs. [0]
         [[{{node gradients/Sum_1_grad/floordiv}} = FloorDiv[T=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](gradients/Sum_1_grad/Shape, gradients/Sum_1_grad/Maximum)]]

         [[{{node Neg_1/_25}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_
device_incarnation=1, tensor_name="edge_823_Neg_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_main.py", line 323, in <module>
    main(args)
  File "run_main.py", line 291, in main
    feed_dict={x_hat: batch_xs_input, x: batch_xs_target, keep_prob : 0.9})
  File "C:\Users\shica\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 929, in run
    run_metadata_ptr)
  File "C:\Users\shica\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\shica\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1328, in _do_run
    run_metadata)
  File "C:\Users\shica\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [2] vs. [0]
         [[node gradients/Sum_1_grad/floordiv (defined at run_main.py:228)  = FloorDiv[T=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](gradients/Sum_1_grad/Shape, gradi
ents/Sum_1_grad/Maximum)]]
         [[{{node Neg_1/_25}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_
device_incarnation=1, tensor_name="edge_823_Neg_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'gradients/Sum_1_grad/floordiv', defined at:
  File "run_main.py", line 323, in <module>
    main(args)
  File "run_main.py", line 228, in main
    train_op = tf.train.AdamOptimizer(learn_rate).minimize(loss)
  File "C:\Users\shica\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\training\optimizer.py", line 400, in minimize
    grad_loss=grad_loss)
  File "C:\Users\shica\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\training\optimizer.py", line 519, in compute_gradients
    colocate_gradients_with_ops=colocate_gradients_with_ops)
  File "C:\Users\shica\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\gradients_impl.py", line 630, in gradients
    gate_gradients, aggregation_method, stop_gradients)
  File "C:\Users\shica\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\gradients_impl.py", line 814, in _GradientsHelper
    lambda: grad_fn(op, *out_grads))
  File "C:\Users\shica\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\gradients_impl.py", line 408, in _MaybeCompile
    return grad_fn()  # Exit early
  File "C:\Users\shica\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\gradients_impl.py", line 814, in <lambda>
    lambda: grad_fn(op, *out_grads))
  File "C:\Users\shica\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\math_grad.py", line 82, in _SumGrad
    tile_scaling = _safe_shape_div(input_shape, output_shape_kept_dims)
  File "C:\Users\shica\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\math_grad.py", line 35, in _safe_shape_div
    return x // math_ops.maximum(y, 1)
  File "C:\Users\shica\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\math_ops.py", line 866, in binary_op_wrapper
    return func(x, y, name=name)
  File "C:\Users\shica\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\math_ops.py", line 1111, in floordiv
    return gen_math_ops.floor_div(x, y, name=name)
  File "C:\Users\shica\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 3079, in floor_div
    "FloorDiv", x=x, y=y, name=name)
  File "C:\Users\shica\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\shica\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\util\deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "C:\Users\shica\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 3274, in create_op
    op_def=op_def)
  File "C:\Users\shica\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

...which was originally created as op 'Sum_1', defined at:
  File "run_main.py", line 323, in <module>
    main(args)
  File "run_main.py", line 225, in main
    y, z, loss, neg_marginal_likelihood, KL_divergence = vae.autoencoder(x_hat, x, dim_img, dim_z, n_hidden, keep_prob)
  File "G:\PythonLib\tensorflow-mnist-VAE-master\vae.py", line 82, in autoencoder
    KL_divergence = 0.5 * tf.reduce_sum(tf.square(mu) + tf.square(sigma) - tf.log(1e-8 + tf.square(sigma)) - 1, 1)
  File "C:\Users\shica\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\util\deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "C:\Users\shica\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\math_ops.py", line 1345, in reduce_sum
    name=name))
  File "C:\Users\shica\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 8389, in _sum
    name=name)
  File "C:\Users\shica\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\shica\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\util\deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "C:\Users\shica\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 3274, in create_op
    op_def=op_def)
  File "C:\Users\shica\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Incompatible shapes: [2] vs. [0]
         [[node gradients/Sum_1_grad/floordiv (defined at run_main.py:228)  = FloorDiv[T=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](gradients/Sum_1_grad/Shape, gradi
ents/Sum_1_grad/Maximum)]]
         [[{{node Neg_1/_25}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_
device_incarnation=1, tensor_name="edge_823_Neg_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

**Comment by jvishnuvardhan** [comment]
This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!
