### ISSUE TITLE
using TFlite: ModuleNotFoundError: No module named '_tensorflow_wrap_interpreter_wrapper'

### ISSUE THREAD

**Issue by HTelepathH** [tensorflow/tensorflow#26422]
**System information**
- Windows 10:
- TensorFlow installed from pip:
- TensorFlow version 1.12.0:
- Python 3.6.8:

Failed when trying to run a mobilenet_v1_1.0_224.tflite model using tflite. So I copy the interpreter_test.py and run it. End up with 10 fails in 12 tests, all with the same error of '_tensorflow_wrap_interpreter_wrapper'.

Also, my D:\Python 36\Lib\site-packages\tensorflow\contrib\lite\python\interpreter_wrapper folder only has : 
/__pycache__ , tensorflow_wrap_interpreter_wrapper.py , __init__py

I rename the tensorflow_wrap_interpreter_wrapper.py and uploaded it to see if some one can help me.
[tensorflow_wrap_interpreter_wrapper.txt](https://github.com/tensorflow/tensorflow/files/2939561/tensorflow_wrap_interpreter_wrapper.txt)

**Error log**
Traceback (most recent call last):
  File "D:\Python 36\lib\site-packages\tensorflow\contrib\lite\python\interpreter_wrapper\tensorflow
_wrap_interpreter_wrapper.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_tensorflow_wrap_interpreter_wrapper', [dirname(__f
ile__)])
  File "D:\Python 36\lib\imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_tensorflow_wrap_interpreter_wrapper'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_tflite.py", line 52, in <module>
    tflite_output = run(model_file, image_data)
  File "run_tflite.py", line 16, in run
    interpreter = interpreter_wrapper.Interpreter(model_path=model_file)
  File "D:\Python 36\lib\site-packages\tensorflow\contrib\lite\python\interpreter.py", line 52, in _
_init__
    _interpreter_wrapper.InterpreterWrapper_CreateWrapperCPPFromFile(
  File "D:\Python 36\lib\site-packages\tensorflow\python\util\lazy_loader.py", line 53, in __getattr
__
    module = self._load()
  File "D:\Python 36\lib\site-packages\tensorflow\python\util\lazy_loader.py", line 42, in _load
    module = importlib.import_module(self.__name__)
  File "D:\Python 36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\Python 36\lib\site-packages\tensorflow\contrib\lite\python\interpreter_wrapper\tensorflow
_wrap_interpreter_wrapper.py", line 28, in <module>
    _tensorflow_wrap_interpreter_wrapper = swig_import_helper()
  File "D:\Python 36\lib\site-packages\tensorflow\contrib\lite\python\interpreter_wrapper\tensorflow
_wrap_interpreter_wrapper.py", line 20, in swig_import_helper
    import _tensorflow_wrap_interpreter_wrapper
ModuleNotFoundError: No module named '_tensorflow_wrap_interpreter_wrapper'

**Comment by take-iwiw** [comment]
I faced the same error.
You can try `pip install tf-nightly`.
It solved the issue in my case.
You may also need to change `tf.contrib.lite.Interpreter` to `tf.lite.Interpreter`

**Comment by HTelepathH** [comment]
> I faced the same error.
> You can try `pip install tf-nightly`.
> It solved the issue in my case.
> You may also need to change `tf.contrib.lite.Interpreter` to `tf.lite.Interpreter`

It works in my case too ! Thanks a lot !

**Comment by jvishnuvardhan** [comment]
I think it was resolved. I am closing the issue. Please open a new ticket if you see similar issue again. Thanks!

**Comment by Drkstr** [comment]
So you need to install tf to use tfLite ? 

I have followed the instructions from here to install tfLIte on a RBPi https://www.tensorflow.org/lite/guide/build_rpi 


But, when I try to run some example code I get an "ImportError: No module named 'tensorflow' error  "

**Comment by n-yoda** [comment]
I'm not sure this is related, but when I installed tensorflow lite using https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/pip_package
I needed to add the following files to Extension(sources=[...]):
```
'interpreter_wrapper/numpy.cc',
'interpreter_wrapper/python_error_reporter.cc',
'interpreter_wrapper/python_utils.cc',
```
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/tools/pip_package/setup.py#L125

**Comment by macawile21** [comment]
> I faced the same error.
> You can try `pip install tf-nightly`.
> It solved the issue in my case.
> You may also need to change `tf.contrib.lite.Interpreter` to `tf.lite.Interpreter`

This works! You saved me. Thank you.
