### ISSUE TITLE
ImportError: librt.so.1: No such file or directory

### ISSUE THREAD

**Issue by kitmonisit** [tensorflow/tensorflow#26432]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): RHEL6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): `pip install tensorflow`
- TensorFlow version: 1.13.1
- Python version: 3.7.2
- Installed using virtualenv? pip? conda?: `pip`
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: 16GB RAM

**Describe the problem**
1. If I run python with `$ python3`, then `import tensorflow`, I get an `ImporError: librt.so.1: cannot open shared object file: No such file or directory`
2. If I run python with `$ LD_LIBRARY_PATH=/home/kmonisit/.linuxbrew/lib:$LD_LIBRARY_PATH python3`, then `import tensorflow`, it succeeds.
3. I will be using `tensorflow` from within C code, i.e. C code calls Python code calls tensorflow. I want to find a way where I can use `tensorflow` without having to specify `LD_LIBRARY_PATH`.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

```
$ brew install binutils linux-headers
$ brew install glibc --force-bottle
$ brew install gcc --force-bottle
$ brew install python3
$ pip3 install tensorflow
```

Now I have `glibc` in `$HOME/.linuxbrew/lib`. Next step is:

```
$ python3
>>> import tensorflow
```

```
Traceback (most recent call last):
  File "/home/kmonisit/.linuxbrew/Cellar/python/3.7.2_2/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/kmonisit/.linuxbrew/Cellar/python/3.7.2_2/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/kmonisit/.linuxbrew/Cellar/python/3.7.2_2/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/kmonisit/.linuxbrew/Cellar/python/3.7.2_2/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/kmonisit/.linuxbrew/Cellar/python/3.7.2_2/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: librt.so.1: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/kmonisit/.linuxbrew/Cellar/python/3.7.2_2/lib/python3.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/kmonisit/.linuxbrew/Cellar/python/3.7.2_2/lib/python3.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/kmonisit/.linuxbrew/Cellar/python/3.7.2_2/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/kmonisit/.linuxbrew/Cellar/python/3.7.2_2/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/kmonisit/.linuxbrew/Cellar/python/3.7.2_2/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/kmonisit/.linuxbrew/Cellar/python/3.7.2_2/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/kmonisit/.linuxbrew/Cellar/python/3.7.2_2/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/kmonisit/.linuxbrew/Cellar/python/3.7.2_2/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: librt.so.1: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

**Successful case**
If I do:
```
$ LD_LIBRARY_PATH=/home/kmonisit/.linuxbrew/lib:$LD_LIBRARY_PATH python3
>>> import tensorflow
>>> # import success!
```

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

Full traceback already included above.

**Comment by Ayush517** [comment]
Can you please let me know the output of following:
$ LD_LIBRARY_PATH=/home/kmonisit/.linuxbrew/lib:$LD_LIBRARY_PATH python3 -V

**Comment by kitmonisit** [comment]
```
$ LD_LIBRARY_PATH=/home/kmonisit/.linuxbrew/lib:$LD_LIBRARY_PATH python3 -V
Python 3.7.2
```

**Comment by kitmonisit** [comment]
Just came back to the office and the compilation I did last night completed successfully. To compile Tensorflow, here's what I did:

```
# LD_LIBRARY_PATH should be clean (does not have $HOME/.linuxbrew/lib)
# Download and compile bazel

$ cd ~
$ mkdir build-bazel
$ cd build-bazel
$ wget https://github.com/bazelbuild/bazel/releases/download/0.20.0/bazel-0.20.0-dist.zip
$ unzip bazel-0.20.0-dist.zip
$ env EXTRA_BAZEL_ARGS="--host_javabase=@local_jdk//:jdk" bash ./compile.sh

# At this point I now have bazel without jdk. That's sufficient to compile Tensorflow

# Let's get started with Tensorflow
$ cd ~
$ mkdir build-tensorflow
$ cd build-tensorflow
$ wget https://codeload.github.com/tensorflow/tensorflow/zip/v1.13.1 -O tensorflow-1.13.1.zip
$ unzip tensorflow-1.13.1.zip
$ cd tensorflow-1.13.1
$ ./configure
$ PATH=$HOME/build-bazel/output:$PATH bazel build --config=monolithic //tensorflow/tools/pip_package:build_pip_package

# Compilation will take a long time. I did this overnight.

$ ./bazel-bin/tensorflow/tools/pip_package/build_pip_package $HOME/tmp/tensorflow_pkg
$ cd $HOME/tmp/tensorflow_pkg
$ pip3 install tensorflow-1.13.1-cp37-cp37m-linux_x86_64.whl
$ python3
>>> import tensorflow
>>> :)
```

**Comment by ymodak** [comment]
Thanks for sharing the installation steps. I will close this issue now since its resolved. Thanks!
