### ISSUE TITLE
Tensorflow.js API documentation example issue line 19, incorect code, build error

### ISSUE THREAD

**Issue by raymondpittman** [tensorflow/tensorflow#26444]
In the object callback on **line 19** in the bottom example on this page:
[See-sample-code-for-node.js-usage](https://www.tensorflow.org/js/tutorials/setup#see-sample-code-for-node.js-usage) has a little error.

> Currently you have

`onEpochEnd: (epoch, log) => console.log(`Epoch ${epoch}: loss = ${log.loss}`);`

> You need to remove the ;

`onEpochEnd: (epoch, log) => console.log(`Epoch ${epoch}: loss = ${log.loss}`)`

> Compile error is as follows

```
SyntaxError: Unexpected token ;
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
    at Module._compile (internal/modules/cjs/loader.js:664:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
```

>  Node -v

`v11.11.0`

**Comment by rthadur** [comment]
This is working as expected , please check in latest version. Closing this issue. Thank you
