### ISSUE TITLE
TypeError in test files

### ISSUE THREAD

**Issue by nehaljwani** [tensorflow/tensorflow#26458]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): Source
- TensorFlow version (use command below): 1.13.1
- Python version: 3.7
- Bazel version (if compiling from source): 0.21.0
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

I encountered these when running tests after building tensorflow using bazel on Windows:
```
======================================================================
ERROR: testLossesForwarded (__main__.ListTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "%PREFIX%\lib\site-packages\tensorflow\python\framework\test_util.py", line 946, in decorated
    f(self, *args, **kwargs)
  File "%PREFIX%\lib\site-packages\tensorflow\python\framework\test_util.py", line 1105, in decorated
    f(self, *args, **kwargs)
  File "\\?\C:\Users\nwani\AppData\Local\Temp\Bazel.runfiles_iqsmzf36\runfiles\org_tensorflow\py_test_dir\tensorflow\python\training\checkpointable\data_structures_test.py", line 128, in testLossesForwarded
    model = HasList()
  File "\\?\C:\Users\nwani\AppData\Local\Temp\Bazel.runfiles_iqsmzf36\runfiles\org_tensorflow\py_test_dir\tensorflow\python\training\checkpointable\data_structures_test.py", line 60, in __init__
    list(sequence=[core.Dense(11)]) + [core.Dense(12)]))
TypeError: list() takes no keyword arguments

======================================================================
ERROR: testTracking (__main__.ListTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "%PREFIX%\lib\site-packages\tensorflow\python\framework\test_util.py", line 946, in decorated
    f(self, *args, **kwargs)
  File "%PREFIX%\lib\site-packages\tensorflow\python\framework\test_util.py", line 1105, in decorated
    f(self, *args, **kwargs)
  File "\\?\C:\Users\nwani\AppData\Local\Temp\Bazel.runfiles_iqsmzf36\runfiles\org_tensorflow\py_test_dir\tensorflow\python\training\checkpointable\data_structures_test.py", line 78, in testTracking
    model = HasList()
  File "\\?\C:\Users\nwani\AppData\Local\Temp\Bazel.runfiles_iqsmzf36\runfiles\org_tensorflow\py_test_dir\tensorflow\python\training\checkpointable\data_structures_test.py", line 60, in __init__
    list(sequence=[core.Dense(11)]) + [core.Dense(12)]))
TypeError: list() takes no keyword arguments
```

**Comment by jvishnuvardhan** [comment]
@nehaljwani Could you provide more details on the issue and context? Could you check whether it is persisting with the TF.20? Thanks!

**Comment by nehaljwani** [comment]
What is TF.20 ?

**Comment by nehaljwani** [comment]
I am curious, do you folks not test your builds before releasing making a release/releasing wheels? 

This is what I ran:
```
bazel --batch test -c opt $BUILD_OPTS -k --test_output=errors \
  --define=no_tensorflow_py_deps=true --test_lang_filters=py \
  --build_tag_filters=-no_pip,-no_windows,-no_oss --build_tests_only \
  --test_timeout 9999999 --test_tag_filters=-no_pip,-no_windows,-no_oss \
  -- //${PY_TEST_DIR}/tensorflow/python/... \
     //${PY_TEST_DIR}/tensorflow/contrib/... \
```

**Comment by jvishnuvardhan** [comment]
@nehaljwani Sorry for the typo. I meant TF 2.0. We do lot of testing before releasing. Thanks!

**Comment by gunan** [comment]
@nehaljwani Thanks for the report.
While we ran the tests, we sometimes skip such issues as this is only a bug in the test because of a recent change in python 3.7. Our larger scale tests showed that this does not affect any of the production code paths in tensorflow, so we decided to fix it after.
If you like to contribute a fix, we would be happy to accept.

**Comment by yongtang** [comment]
@nehaljwani I took a look at the master branch. It seems the issue has been fixed. I will close the issue for now but feel free to reopen if the issue persists.

**Comment by nehaljwani** [comment]
Thank you very much!
