### ISSUE TITLE
Java API can not create empty tensor

### ISSUE THREAD

**Issue by egolearner** [tensorflow/tensorflow#26466]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):MAC OS 10.14.1
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:NO
- TensorFlow installed from (source or binary):binary
- TensorFlow version (use command below):1.8
- Python version:None
- Bazel version (if compiling from source):None
- GCC/Compiler version (if compiling from source):None
- CUDA/cuDNN version:None
- GPU model and memory:None

C++ API is able to create empty tensor
```cpp
        Tensor ts_indices(tensorflow::DT_INT64, tensorflow::TensorShape(
                   { 0, 2 }));
```
However, Java API will raise Exception.
```java
        long[][] index = new long[0][2];
        Tensors.create(index);
 ```
> java.lang.IllegalArgumentException: cannot create Tensors with a 0 dimension
	at org.tensorflow.Tensor.fillShape(Tensor.java:703)
	at org.tensorflow.Tensor.create(Tensor.java:142)
	at org.tensorflow.Tensor.create(Tensor.java:115)
	at org.tensorflow.Tensors.create(Tensors.java:336)

**Comment by ymodak** [comment]
@asimshankar Can you PTAL? Thanks!

**Comment by egolearner** [comment]
hi @asimshankar please have a look

**Comment by egolearner** [comment]
I'm afraid I do not have the necessary environment to take a try.
And I do not need this for the moment.

**Comment by mohantym** [comment]
Ok @egolearner! Closing this issue for now ,Please create a new one if you need further assistance.Thanks!

**Comment by Saber-Altria** [comment]
try this:
long[] shape = {0,2};
Tensor.create(shape, LongBuffer.allocate(0));
