### ISSUE TITLE
TOCO reports SymbolAlreadyExposedError:  Symbol AttrValue is already exposed as ().

### ISSUE THREAD

**Issue by ajarthurs** [tensorflow/tensorflow#26488]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Arch Linux 4.20.1-arch1-1-ARCH
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary):
Source
- TensorFlow version (use command below):
`master` (reproduction instructions below)
- Python version:
3.7.2
- Bazel version (if compiling from source):
0.21.0-1
- GCC/Compiler version (if compiling from source):
8.2.1
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**
Running `toco` with or without arguments throws this traceback:
```
$ toco
Traceback (most recent call last):
  File "/auxiliary//home/ajarthurs/Development/data/python/bin/toco", line 6, in <module>
    from tensorflow.lite.python.tflite_convert import main
  File "/auxiliary/home/ajarthurs/Development/data/python/tensorflow/__init__.py", line 33, in <module>
    from tensorflow_estimator import __path__ as _new_path
  File "/auxiliary/home/ajarthurs/Development/data/python/tensorflow_estimator/__init__.py", line 8, in <module>
    from tensorflow_estimator._api.v1 import estimator
  File "/auxiliary/home/ajarthurs/Development/data/python/tensorflow_estimator/_api/v1/estimator/__init__.py", line 8, in <module>
    from tensorflow_estimator._api.v1.estimator import experimental
  File "/auxiliary/home/ajarthurs/Development/data/python/tensorflow_estimator/_api/v1/estimator/experimental/__init__.py", line 8, in <module>
    from tensorflow_estimator.python.estimator.canned.dnn import dnn_logit_fn_builder
  File "/auxiliary/home/ajarthurs/Development/data/python/tensorflow_estimator/python/estimator/canned/dnn.py", line 23, in <module>
    from tensorflow.python.feature_column import feature_column
  File "/auxiliary/home/ajarthurs/Development/data/python/tensorflow_core/python/__init__.py", line 157, in <module>
    tf_export(v1=['AttrValue'])(AttrValue)
  File "/auxiliary/home/ajarthurs/Development/data/python/tensorflow_core/python/util/tf_export.py", line 334, in __call__
    self.set_attr(undecorated_func, api_names_attr, self._names)
  File "/auxiliary/home/ajarthurs/Development/data/python/tensorflow_core/python/util/tf_export.py", line 346, in set_attr
    (func.__name__, getattr(func, api_names_attr)))  # pylint: disable=protected-access
tensorflow_core.python.util.tf_export.SymbolAlreadyExposedError: Symbol AttrValue is already exposed as ().
```

**Describe the expected behavior**
```
$ toco
usage: toco [-h] --output_file OUTPUT_FILE
            (--graph_def_file GRAPH_DEF_FILE | --saved_model_dir SAVED_MODEL_DIR | --keras_model_file KERAS_MODEL_FILE)
            [--output_format {TFLITE,GRAPHVIZ_DOT}]
            [--inference_type {FLOAT,QUANTIZED_UINT8}]
            [--inference_input_type {FLOAT,QUANTIZED_UINT8}]
            [--input_arrays INPUT_ARRAYS] [--input_shapes INPUT_SHAPES]
            [--output_arrays OUTPUT_ARRAYS]
            [--saved_model_tag_set SAVED_MODEL_TAG_SET]
            [--saved_model_signature_key SAVED_MODEL_SIGNATURE_KEY]
            [--std_dev_values STD_DEV_VALUES] [--mean_values MEAN_VALUES]
            [--default_ranges_min DEFAULT_RANGES_MIN]
            [--default_ranges_max DEFAULT_RANGES_MAX]
            [--post_training_quantize] [--drop_control_dependency]
            [--reorder_across_fake_quant]
            [--change_concat_input_ranges {TRUE,FALSE}] [--allow_custom_ops]
            [--target_ops TARGET_OPS] [--dump_graphviz_dir DUMP_GRAPHVIZ_DIR]
            [--dump_graphviz_video]
toco: error: the following arguments are required: --output_file
```

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

This issue first appeared when I switched to TF commit 13f022a946c7fbfeb1786488d278b675bd027a87. TOCO worked fine when I was on TF commit 12606ff846566dd842444f27f7fed4f911a58580.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ajarthurs** [comment]
Narrowed it down. This issue first appears in TF commit fc85579a2b4b689aa9c56d0434c3433479750d23.

**Comment by ajarthurs** [comment]
Reverted in 61f5a61d25f2d8ef422f14331584fb49af97e493. Fixed.
