### ISSUE TITLE
tflite_convert -- Unknown layer: VladPooling

### ISSUE THREAD

**Issue by emp-is-me** [tensorflow/tensorflow#26496]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac OSX 10.14.3
- TensorFlow installed from (source or binary): source
- TensorFlow version (or github SHA if from source): 1.13.1

**Provide the text output from tflite_convert**

```
ValueError: Unknown layer: VladPooling
```

Also, please include a link to a GraphDef or the model if possible.
https://drive.google.com/open?id=1M_SXoW1ceKm3LghItY2ENKKUn3cWYfZm
(from: https://github.com/WeidiXie/VGG-Speaker-Recognition)

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

Command line: tflite_convert --output_file=weights_keras.tflite --keras_model_file=weights_keras.h5 

Result:
Traceback (most recent call last):
  File "/anaconda3/bin/tflite_convert", line 11, in <module>
    sys.exit(main())
  File "/anaconda3/lib/python3.7/site-packages/tensorflow/lite/python/tflite_convert.py", line 442, in main
    app.run(main=run_main, argv=sys.argv[:1])
  File "/anaconda3/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/anaconda3/lib/python3.7/site-packages/tensorflow/lite/python/tflite_convert.py", line 438, in run_main
    _convert_model(tflite_flags)
  File "/anaconda3/lib/python3.7/site-packages/tensorflow/lite/python/tflite_convert.py", line 122, in _convert_model
    converter = _get_toco_converter(flags)
  File "/anaconda3/lib/python3.7/site-packages/tensorflow/lite/python/tflite_convert.py", line 109, in _get_toco_converter
    return converter_fn(**converter_kwargs)
  File "/anaconda3/lib/python3.7/site-packages/tensorflow/lite/python/lite.py", line 370, in from_keras_model_file
    keras_model = _keras.models.load_model(model_file)
  File "/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/saving.py", line 234, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/saving.py", line 324, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/layers/serialization.py", line 74, in deserialize
    printable_module_name='layer')
  File "/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 192, in deserialize_keras_object
    list(custom_objects.items())))
  File "/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/network.py", line 1263, in from_config
    process_layer(layer_data)
  File "/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/network.py", line 1249, in process_layer
    layer = deserialize_layer(layer_data, custom_objects=custom_objects)
  File "/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/layers/serialization.py", line 74, in deserialize
    printable_module_name='layer')
  File "/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 181, in deserialize_keras_object
    config, module_objects, custom_objects, printable_module_name)
  File "/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 166, in class_and_config_for_serialized_keras_object
    raise ValueError('Unknown ' + printable_module_name + ': ' + class_name)
ValueError: Unknown layer: VladPooling

**Comment by gargn** [comment]
This model requires the `custom_object` parameter when loading the model. This is only available through the Python API. The approach for using custom objects in 1.13 without Eager enabled is similar to the following (where `VladPooling` needs to be imported by your code):

```
# Load the Keras model into a session.
keras_model = tf.keras.models.load_model(
    keras_file, custom_objects={'VladPooling': VladPooling})
sess = tf.keras.backend.get_session()

# Convert the model.
converter = tf.lite.TFLiteConverter.from_session(sess, keras_model.inputs,
                                                 keras_model.outputs)
converter.convert()
```

Support for `custom_objects` will be added to `from_keras_model_file` shortly.

**Comment by gargn** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by Jbiloki** [comment]
Has this been solved?
