### ISSUE TITLE
Tensorflow segfaults with simple convolutional network

### ISSUE THREAD

**Issue by cjds** [tensorflow/tensorflow#26527]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux 18.04 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): Pip
- TensorFlow version (use command below): 
tensorflow                     1.13.1       
tensorflow-estimator     1.13.0       
b'v1.13.1-0-g6612da8951' 1.13.1
- Python version: 3.6.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: 1070 TI

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**
Receiving a segmentation fault when I run this code

**Describe the expected behavior**
Expected model to be filled

**Code to reproduce the issue**
```
def load_image_into_numpy_array(image_path):
  image = Image.open(image_path)
  (im_width, im_height) = image.size
  return np.array(image.getdata()).reshape(
      (im_height, im_width, 3)).astype(np.uint8)


if __name__ == "__main__":
    TEST_IMAGE_PATHS = 'train'
    output = {}
    model = keras.Sequential([
        keras.layers.Conv2D(64, kernel_size=3, activation=tf.nn.relu, input_shape=(360, 640,  3)),
        keras.layers.Flatten(),
        keras.layers.Dense(128, activation=tf.nn.relu),
        keras.layers.Dense(2, activation=tf.nn.softmax)
    ])
    model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])
    labels = {}
    print("Loaded labels")
    with open("labels.json") as label_f:
        labels = json.loads(''.join(label_f.readlines()))
    train_images = []
    train_labels = []
    count = 0
    for (dirpath, dirnames, filenames) in os.walk(TEST_IMAGE_PATHS):
        for filename in filenames:
            if filename in labels:
                img = load_image_into_numpy_array(os.path.join(dirpath, filename))
                train_images.append(img)
                train_labels.append([labels[filename]])
        else:
            continue
        break
    train_images = np.array(train_images)
    train_labels = np.array(train_labels)
    model.fit(train_images, train_labels, epochs=5, batch_size=396)
```

All images in TEST_IMAGE_PATHS are 360x640 

**Other info / logs**
Here's the gdb traceback

```

Thread 1 "python3" received signal SIGSEGV, Segmentation fault.
__memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:490
490	../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S: No such file or directory.
(gdb) bt
#0  __memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:490
#1  0x00007fffcdd033bd in TF_NewTensor () from /home/cjds/.local/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#2  0x00007fffcdc5b8d5 in tensorflow::PyArrayToTF_Tensor(_object*, std::unique_ptr<TF_Tensor, tensorflow::detail::TFTensorDeleter>*) ()
   from /home/cjds/.local/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#3  0x00007fffcdc5c5e5 in tensorflow::NdarrayToTensor(_object*, tensorflow::Tensor*) () from /home/cjds/.local/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#4  0x00007fffcdb06ad3 in tensorflow::(anonymous namespace)::RunCallableHelper(tensorflow::Session*, long, _object*, TF_Status*, absl::InlinedVector<_object*, 8ul, std::allocator<_object*> >*, TF_Buffer*) ()
   from /home/cjds/.local/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#5  0x00007fffcdb0765c in tensorflow::TF_SessionRunCallable(TF_Session*, long, _object*, TF_Status*, absl::InlinedVector<_object*, 8ul, std::allocator<_object*> >*, TF_Buffer*) ()
   from /home/cjds/.local/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#6  0x00007fffcdab59e0 in _wrap_TF_SessionRunCallable () from /home/cjds/.local/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
```

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
