### ISSUE TITLE
Unknown default keras 'categorical_crossentropy' loss function when converting with .h5 to .tflite 

### ISSUE THREAD

**Issue by jokerstudios** [tensorflow/tensorflow#26566]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
-> I used just default code from the rstudio/keras library, no custom loss function
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
-> Ubuntu 16.04.5 LTS (Xenial Xerus) debian
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
- **TensorFlow installed from (source or binary)**:
-> tensorflow installed via rstudio/keras and install.packages("tensorflow")
- **TensorFlow version (use command below)**:
->1.13.1
- **Python version**:
-> 2.7.12
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
-> Cuda compilation tools, release 9.0, V9.0.176
- **GPU model and memory**:
-> P2-Instance AWS EC"
     8*  K80-GPUs from NVIDIA, 64 vCPUs, 732 GiB Host-Speicher 
- **Exact command to reproduce**:
`import tensorflow as tf

converter = tf.lite.TFLiteConverter.from_keras_model_file("test.h5")
tflite_model = converter.convert()
open("converted_model.tflite", "wb").write(tflite_model)`

### Describe the problem
I am trying to convert a keras model from .h5 to .tflite file.
I created the model in R using rstudio/keras and everything works fine.
Once I saved the model as .h5 file, I'm switching to Python (because there is no R converter from .5 to .tflite). But when I'm trying to convert the keras model with the default code from the TensorFlow Lite documentation: [,](https://www.tensorflow.org/api_docs/python/tf/lite/TFLiteConverter) I am getting the following error:

`Traceback (most recent call last):
  File "/tmp/RtmpWIBDmu/chunk-code-849197e0a8f.txt", line 3, in <module>
    converter = tf.lite.TFLiteConverter.from_keras_model_file("test.h5")
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/lite/python/lite.py", line 370, in from_keras_model_file
    keras_model = _keras.models.load_model(model_file)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/engine/saving.py", line 266, in load_model
    sample_weight_mode=sample_weight_mode)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/checkpointable/base.py", line 442, in _method_wrapper
    method(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/engine/training.py", line 282, in compile
    loss_function = training_utils.get_loss_function(loss)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/engine/training_utils.py", line 873, in get_loss_function
    return losses.get(loss)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/losses.py", line 594, in get
    return deserialize(identifier)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/losses.py", line 585, in deserialize
    printable_module_name='loss function')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/utils/generic_utils.py", line 212, in deserialize_keras_object
    function_name)
ValueError: Unknown loss function:loss_categorical_crossentropy`

But as you can see in the source code, I am using the a default keras loss function?

### Source code / logs
This is the Code to create and train the model
`library(keras)
batch_size <- 128
num_classes <- 10
epochs <- 5

# Input image dimensions
img_rows <- 28
img_cols <- 28
fashion_mnist <- dataset_fashion_mnist()
train_images <- fashion_mnist$train$x
train_labels <- fashion_mnist$train$y
test_images <- fashion_mnist$test$x
test_labels <- fashion_mnist$test$y

train_images <- array_reshape(train_images, c(nrow(train_images), img_rows, img_cols, 1))
test_images <- array_reshape(test_images, c(nrow(test_images), img_rows, img_cols, 1))
input_shape <- c(img_rows, img_cols, 1)

# Transform RGB values into [0,1] range
train_images <- train_images / 255
test_images <- test_images / 255

train_labels <- to_categorical(train_labels, num_classes)
test_labels <- to_categorical(test_labels, num_classes)

model <- keras_model_sequential() %>%
  layer_conv_2d(filters = 32, kernel_size = c(3,3), activation = 'relu',input_shape = input_shape) %>% 
  layer_max_pooling_2d(pool_size = c(2, 2)) %>% 
  layer_flatten() %>% 
  layer_dense(units = 128, activation = 'relu') %>% 
  layer_dense(units = num_classes, activation = 'softmax')

model %>% compile(
  loss = loss_categorical_crossentropy,
  optimizer = optimizer_adadelta(),
  metrics = c('accuracy')
)

model %>% fit(
  train_images, train_labels,
  batch_size = batch_size,
  epochs = epochs,
  validation_split = 0.2,
  callbacks = list(callback_tensorboard(log_dir = "./logs/mnist")
))

score <- model %>% evaluate(test_images, test_labels)

cat('Test loss:', score$loss, "\n")
cat('Test accuracy:', score$acc, "\n")

save_model_hdf5(model,"test.h5")
`

**Comment by joyalbin** [comment]
@jokerstudios , could you please try with
model %>% compile(
loss = categorical_crossentropy,
optimizer = optimizer_adadelta(),
metrics = c('accuracy')
)

Hope this will help you

**Comment by jokerstudios** [comment]
@joyalbin thank you for your reply.
sadly if I try your solution, I get the following error whenI'm  trying to compile the model.
`Error in compile(., loss = categorical_crossentropy, optimizer = optimizer_adadelta(), : object 'categorical_crossentropy' not found`

**Comment by jvishnuvardhan** [comment]
@jokerstudios I understand that it was resolved by @joyalbin .
Could you reframe title of the issue so that it will be more helpful to the community? Thanks.
Close the issue if everything was resolved. Thanks!

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by jvishnuvardhan** [comment]
Closing the issue as it was resolved. thanks!
