### ISSUE TITLE
Cannot get tensorflow to work. DLL load failed and DLL initialization routine failed

### ISSUE THREAD

**Issue by JulietTeoh** [tensorflow/tensorflow#26593]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows OS 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.12.0
- Python version: 3.6
- Installed using virtualenv? pip? conda?: conda
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

I cant seem to import tensorflow even though I have supposedly installed CUDA and followed an online tutorial. 
This is my error when I type import tensorflow:

import tensorflow Traceback (most recent call last): File "C:\Users\User\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in from tensorflow.python.pywrap_tensorflow_internal import * File "C:\Users\User\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in _pywrap_tensorflow_internal = swig_import_helper() File "C:\Users\User\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description) File "C:\Users\User\AppData\Local\conda\conda\envs\tensorflow\lib\imp.py", line 243, in load_module return load_dynamic(name, filename, file) File "C:\Users\User\AppData\Local\conda\conda\envs\tensorflow\lib\imp.py", line 343, in load_dynamic return _load(spec)

ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last): File "", line 1, in File "C:\Users\User\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow__init__.py", line 24, in from tensorflow.python import pywrap_tensorflow # pylint: disable=unused-import File "C:\Users\User\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python__init__.py", line 49, in from tensorflow.python import pywrap_tensorflow File "C:\Users\User\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in raise ImportError(msg) ImportError: Traceback (most recent call last): File "C:\Users\User\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in from tensorflow.python.pywrap_tensorflow_internal import * File "C:\Users\User\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in _pywrap_tensorflow_internal = swig_import_helper() File "C:\Users\User\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description) File "C:\Users\User\AppData\Local\conda\conda\envs\tensorflow\lib\imp.py", line 243, in load_module return load_dynamic(name, filename, file) File "C:\Users\User\AppData\Local\conda\conda\envs\tensorflow\lib\imp.py", line 343, in load_dynamic return _load(spec)

ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed. Failed to load the native TensorFlow runtime.

This is what I get when I run tensorflow_self_check.py: ERROR: Failed to import the TensorFlow module.

Python version is 3.6.
TensorFlow is installed at: C:\Users\User\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow
Could not load 'cudart64_80.dll'. The GPU version of TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Download and install CUDA 8.0 from this URL: https://developer.nvidia.com/cuda-toolkit
Could not load 'nvcuda.dll'. The GPU version of TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Typically it is installed in 'C:\Windows\System32'. If it is not present, ensure that you have a CUDA-capable GPU with the correct driver installed.

**Comment by ymodak** [comment]
Apparently you have installed TF-GPU version and it looks like you haven't added cuda path to your environment variable.
Please refer this [windows setup guide](https://www.tensorflow.org/install/gpu#windows_setup) to know more or else you can always try to install TF cpu version instead. Note that you need to install cuda 9.0 for TF 1.12 in order to use pre built TF-gpu binaries.

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by UmutAlihan** [comment]
I am having the same issue is anybody able to solve this?
