### ISSUE TITLE
TypeError when using distributed TensorFlow

### ISSUE THREAD

**Issue by tobegit3hub** [tensorflow/tensorflow#2665]
I follow the document to run TensorFlow in distributed mode in https://www.tensorflow.org/versions/r0.8/how_tos/distributed/index.html . But I got this error "TypeError: 'str' object is not callable".

```
root@b8ff53209db2:/# python trainer.py \
>      --ps_hosts=ps0.example.com:2222,ps1.example.com:2222 \
>      --worker_hosts=worker0.example.com:2222,worker1.example.com:2222 \
>      --job_name=ps --task_index=0
Traceback (most recent call last):
  File "trainer.py", line 74, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.4/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "trainer.py", line 18, in main
    worker_hosts = FLAGS.worker_hosts(",")
TypeError: 'str' object is not callable
```

### Environment info
Operating System: Ubuntu, 4.4.0-22-generic

Installed version of CUDA and cuDNN: None

If installed from binary pip package, provide:

```
pip 8.1.2
Python 3.4.4
tensorflow 0.8.0
```

If installed from sources, provide the commit hash:

### Steps to reproduce
1. `python trainer.py --ps_hosts="ps0.example.com:2222,ps1.example.com:2222" --worker_hosts="worker0.example.com:2222,worker1.example.com:2222" --job_name="worker" --task_index=1`

### Logs or other output that would be helpful

```
Traceback (most recent call last):
  File "trainer.py", line 74, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.4/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "trainer.py", line 18, in main
    worker_hosts = FLAGS.worker_hosts(",")
TypeError: 'str' object is not callable
```

**Comment by mrry** [comment]
`FLAGS.worker_hosts` is the string (type `str`) value of the `--worker_hosts` flag. It doesn't define a `__call__()` method, hence the error you are seeing.

I think instead you want to have:

```python
worker_hosts = FLAGS.worker_hosts.split(",")
```

**Comment by tobegit3hub** [comment]
Thank @mrry for helping. But actually I have used `worker_hosts = FLAGS.worker_hosts.split(",")`, just like what the official document said. 

Here's the complete code.

```
import tensorflow as tf

# Flags for defining the tf.train.ClusterSpec
tf.app.flags.DEFINE_string("ps_hosts", "",
                           "Comma-separated list of hostname:port pairs")
tf.app.flags.DEFINE_string("worker_hosts", "",
                           "Comma-separated list of hostname:port pairs")

# Flags for defining the tf.train.Server
tf.app.flags.DEFINE_string("job_name", "", "One of 'ps', 'worker'")
tf.app.flags.DEFINE_integer("task_index", 0, "Index of task within the job")

FLAGS = tf.app.flags.FLAGS


def main(_):
  ps_hosts = FLAGS.ps_hosts.split(",")
  worker_hosts = FLAGS.worker_hosts(",")

  # Create a cluster from the parameter server and worker hosts.
  cluster = tf.train.ClusterSpec({"ps": ps_hosts, "worker": worker_hosts})
  
  # Create and start a server for the local task.
  server = tf.train.Server(cluster,
                           job_name=FLAGS.job_name,
                           task_index=FLAGS.task_index)

  if FLAGS.job_name == "ps":
    server.join()
  elif FLAGS.job_name == "worker":

    # Assigns ops to the local worker by default.
    with tf.device(tf.train.replica_device_setter(
        worker_device="/job:worker/task:%d" % FLAGS.task_index,
        cluster=cluster)):

      # Build model...
      loss = ...
      global_step = tf.Variable(0)

      train_op = tf.train.AdagradOptimizer(0.01).minimize(
          loss, global_step=global_step)

      saver = tf.train.Saver()
      summary_op = tf.merge_all_summaries()
      init_op = tf.initialize_all_variables()

    # Create a "supervisor", which oversees the training process.
    sv = tf.train.Supervisor(is_chief=(FLAGS.task_index == 0),
                             logdir="/tmp/train_logs",
                             init_op=init_op,
                             summary_op=summary_op,
                             saver=saver,
                             global_step=global_step,
                             save_model_secs=600)

    # The supervisor takes care of session initialization and restoring from
    # a checkpoint.
    sess = sv.prepare_or_wait_for_session(server.target)

    # Start queue runners for the input pipelines (if any).
    sv.start_queue_runners(sess)

    # Loop until the supervisor shuts down (or 1000000 steps have completed).
    step = 0
    while not sv.should_stop() and step < 1000000:
      # Run a training step asynchronously.
      # See `tf.train.SyncReplicasOptimizer` for additional details on how to
      # perform *synchronous* training.
      _, step = sess.run([train_op, global_step])


if __name__ == "__main__":
  tf.app.run()
```

**Comment by mrry** [comment]
It looks like the error is still present in the code snippet you posted:

![worker_hosts = FLAGS.worker_hosts(",")](http://i.imgur.com/7eH14HE.png)

**Comment by tobegit3hub** [comment]
Sorry for such a bother. It works after fixing this and I think we can fix the document in the TensorFlow site because we always copy-and-paste its code snippet.

Thank @mrry  again.
