### ISSUE TITLE
Installation issue with tensorflow : pywrap_tensorflow_internal 

### ISSUE THREAD

**Issue by OsamaNaeem1995** [tensorflow/tensorflow#26689]
**System information**
- Windows 10 64 bit 
- TensorFlow installed from (source or binary): pip install tensorflow
- TensorFlow version (or github SHA if from source): tensorflow 1.12.0

```
Using TensorFlow backend.
Traceback (most recent call last):
  File "C:\Users\Osama\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tensorflow_internal', [dirname(__file__)])
  File "C:\Program Files (x86)\Python37-32\lib\imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Osama\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Osama\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Osama\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 20, in swig_import_helper
    import _pywrap_tensorflow_internal
ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "FirstVideoDetection.py", line 1, in <module>
    from imageai.Detection import VideoObjectDetection
  File "C:\Users\Osama\AppData\Roaming\Python\Python37\site-packages\imageai\Detection\__init__.py", line 3, in <module>
    from imageai.Detection.keras_retinanet.models.resnet import resnet50_retinanet
  File "C:\Users\Osama\AppData\Roaming\Python\Python37\site-packages\imageai\Detection\keras_retinanet\models\resnet.py", line 19, in <module>
    import keras
  File "C:\Users\Osama\AppData\Roaming\Python\Python37\site-packages\keras\__init__.py", line 3, in <module>
    from . import utils
  File "C:\Users\Osama\AppData\Roaming\Python\Python37\site-packages\keras\utils\__init__.py", line 6, in <module>
    from . import conv_utils
  File "C:\Users\Osama\AppData\Roaming\Python\Python37\site-packages\keras\utils\conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "C:\Users\Osama\AppData\Roaming\Python\Python37\site-packages\keras\backend\__init__.py", line 89, in <module>
    from .tensorflow_backend import *
  File "C:\Users\Osama\AppData\Roaming\Python\Python37\site-packages\keras\backend\tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf
  File "C:\Users\Osama\AppData\Roaming\Python\Python37\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\Osama\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Osama\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Osama\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tensorflow_internal', [dirname(__file__)])
  File "C:\Program Files (x86)\Python37-32\lib\imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tensorflow_internal'
During handling of the above exception, another exception occurred:
```

I'm working on object detection in video, i've already installed the tensorflow packages, when i run the code it gives me an error stating

 **ModuleNotFoundError: No module named 'tensorflow.python._pywrap_tensorflow_internal'**

**_### How do i solve this error ? ? ?_**

**Comment by ymodak** [comment]
Are you trying to install TF-GPU version? Also what is your cpu model/make in your system?

**Comment by OsamaNaeem1995** [comment]
No I simply installed the basic version. I.e pip install tensorflow. Cpu
version is
Lenovo G40 - 80E400GTU S  5th Generation Intel Core i3-5005U 8 gb ram

**Comment by ymodak** [comment]
Can you please describe the steps you followed to install TF? Also did you take a look at [Install TensorFlow with pip](https://www.tensorflow.org/install/pip)?

**Comment by OsamaNaeem1995** [comment]
Yes I did. I just did 'pip install tensorflow ' nothing else

**Comment by ymodak** [comment]
What version of python are you using? Note that TF 1.12 is not compatible with 3.7 you may have to switch to Python 3.6 or lower.
Also TF 1.13 supports Python 3.7

**Comment by OsamaNaeem1995** [comment]
Ok thanks. I'll check

**Comment by ymodak** [comment]
@OsamaNaeem1995  Were you able to install TF successfully?

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by OsamaNaeem1995** [comment]
Yes. I just installed an older version and it works fine

**Comment by isnaayu** [comment]
hi, i my TF 1.14 and my python 3.9, should i downgrade my python version ? thanks
