### ISSUE TITLE
tensorflow.lite.python.convert.ConverterError: TOCO failed. See console for info.

### ISSUE THREAD

**Issue by yizhaoyanbo** [tensorflow/tensorflow#26696]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):  No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  ubuntu16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):  binary, tf-nightly
- TensorFlow version (use command below):   1.14.1
- Python version:  3.6.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:   no cuda, only cpu
- GPU model and memory:

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**

I wanna to convert .pb model to tflite model.

**Describe the expected behavior**

********************
the following errors occured:

Traceback (most recent call last):
  File "onnx2tf.py", line 33, in <module>
    main(sys.argv)
  File "onnx2tf.py", line 27, in main
    tflite_model = converter.convert()
  File "/home/riddick/.local/lib/python3.6/site-packages/tensorflow/lite/python/lite.py", line 762, in convert
    **converter_kwargs)
  File "/home/riddick/.local/lib/python3.6/site-packages/tensorflow/lite/python/convert.py", line 442, in toco_convert_impl
    input_data.SerializeToString())
  File "/home/riddick/.local/lib/python3.6/site-packages/tensorflow/lite/python/convert.py", line 205, in toco_convert_protos
    "TOCO failed. See console for info.\n%s\n%s\n" % (stdout, stderr))
tensorflow.lite.python.convert.ConverterError: TOCO failed. See console for info.
2019-03-14 03:21:21.151470: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: PyFunc
2019-03-14 03:21:21.316309: F tensorflow/lite/toco/import_tensorflow.cc:114] Check failed: attr.value_case() == AttrValue::kType (1 vs. 6)
Fatal Python error: Aborted

******************

**Code to reproduce the issue**

*******************************

    input_arrays = ["image"]
    output_arrays = ["Add"]
    converter = tf.lite.TFLiteConverter.from_frozen_graph(pbPath, input_arrays, output_arrays)
    tflite_model = converter.convert()
    open(tflitePath, "wb").write(tflite_model)

*****************************

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

my model has been uploaded to google drive:
[https://drive.google.com/open?id=1V4ovRkU6Tv78oxCHjLZRClnubnDz9YzC](url)

**Comment by ymodak** [comment]
Did you try using [TFLITE_BUILTINS, SELECT_TF_OPS](https://www.tensorflow.org/lite/guide/ops_select) to convert your model? Thanks!

**Comment by yizhaoyanbo** [comment]
@ymodak  I have tried using  TFLITE_BUILTINS, SELECT_TF_OPS  options. But the same error occurs.

    input_arrays = ["image"]
    output_arrays = ["Add"]
    converter = tf.lite.TFLiteConverter.from_frozen_graph(pbPath, input_arrays, output_arrays)
    converter.target_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,tf.lite.OpsSet.SELECT_TF_OPS]
    tflite_model = converter.convert()
    open(tflitePath, "wb").write(tflite_model)


if I only use the option TFLITE_BUILTINS. The Error is same to mentioned above. 
if I only use the option  SELECT_TF_OPS. The Error is as following:

tensorflow.lite.python.convert.ConverterError: TOCO failed. See console for info.
2019-03-14 19:22:41.572495: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Pad
2019-03-14 19:22:41.583638: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Transpose
2019-03-14 19:22:41.583764: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Conv2D
2019-03-14 19:22:41.583786: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Transpose
2019-03-14 19:22:41.583797: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Mul
2019-03-14 19:22:41.583808: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Add
2019-03-14 19:22:41.583821: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Relu
2019-03-14 19:22:41.583834: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: PyFunc
2019-03-14 19:22:41.583849: F tensorflow/lite/toco/import_tensorflow.cc:114] Check failed: attr.value_case() == AttrValue::kType (1 vs. 6)
Fatal Python error: Aborted

**Comment by SystemErrorWang** [comment]
get the same problem when trying to convert from session, code as below:
`

    converter = tf.lite.TFLiteConverter.from_session(
                        sess, [inputs], [outputs])converter.inference_type = tf.lite.constants.QUANTIZED_UINT8
    input_arrays = converter.get_input_arrays()
    converter.quantized_input_stats = {input_arrays[0] : (0., 1.)}  # mean, std_dev
    tflite_model = converter.convert()
    open("small_unet.tflite", "wb").write(tflite_model)`

**Comment by haozha111** [comment]
Based on the CHECK failure, my guess is that the type information in that particular NodeDef is missing. Could you check the attributes of that NodeDef? How is this graph generated?

**Comment by Queequeg92** [comment]
Any Update?

**Comment by JacobLau84** [comment]
Any Update?

**Comment by ragnariock** [comment]
same error, maybe, any update?)

**Comment by paolopiano1997** [comment]
Same error

**Comment by hope-yao** [comment]
Any update?

**Comment by haozha111** [comment]
Hi,

Sorry for the update. Could you try use tf-nightly which enables the new MLIR converter by default?

I believe this is an issue with the old TOCO converter which is deprecated. Thanks!

**Comment by taoja12** [comment]
Have you solved your problems? I have met the same question!

**Comment by speciallan** [comment]
I have met the same problem no solved

**Comment by Frapschen** [comment]
> get the same problem when trying to convert from session, code as below:
> `
> 
> ```
> converter = tf.lite.TFLiteConverter.from_session(
>                     sess, [inputs], [outputs])
> converter.inference_type = tf.lite.constants.QUANTIZED_UINT8
> input_arrays = converter.get_input_arrays()
> converter.quantized_input_stats = {input_arrays[0] : (0., 1.)}  # mean, std_dev
> tflite_model = converter.convert()
> open("small_unet.tflite", "wb").write(tflite_model)`
> ```

any update?

**Comment by Frapschen** [comment]
similarly, i ues python scripts to convert my SavedModel to lite format,but get the same error above,besides i use command line to convert,i get more error message:
```
2020-04-28 10:17:51.741003: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: Enter
2020-04-28 10:17:51.741526: E tensorflow/core/framework/op_kernel.cc:1426] OpKernel ('op: "NoOp" device_type: "CPU"') for unknown op: NoOp
2020-04-28 10:17:51.741785: E tensorflow/core/framework/op_kernel.cc:1426] OpKernel ('op: "NoOp" device_type: "GPU"') for unknown op: NoOp
2020-04-28 10:17:51.742032: E tensorflow/core/framework/op_kernel.cc:1426] OpKernel ('op: "_HostRecv" device_type: "GPU" host_memory_arg: "tensor"') for unknown op: _HostRecv
2020-04-28 10:17:51.742328: E tensorflow/core/framework/op_kernel.cc:1426] OpKernel ('op: "_Send" device_type: "CPU"') for unknown op: _Send
2020-04-28 10:17:51.742579: E tensorflow/core/framework/op_kernel.cc:1426] OpKernel ('op: "_HostRecv" device_type: "CPU"') for unknown op: _HostRecv
2020-04-28 10:17:51.742888: E tensorflow/core/framework/op_kernel.cc:1426] OpKernel ('op: "_Send" device_type: "GPU"') for unknown op: _Send
2020-04-28 10:17:51.743179: E tensorflow/core/framework/op_kernel.cc:1426] OpKernel ('op: "_Recv" device_type: "CPU"') for unknown op: _Recv
2020-04-28 10:17:51.743399: E tensorflow/core/framework/op_kernel.cc:1426] OpKernel ('op: "_HostSend" device_type: "GPU" host_memory_arg: "tensor"') for unknown op: _HostSend
2020-04-28 10:17:51.743697: E tensorflow/core/framework/op_kernel.cc:1426] OpKernel ('op: "_Recv" device_type: "GPU"') for unknown op: _Recv
2020-04-28 10:17:51.743994: E tensorflow/core/framework/op_kernel.cc:1426] OpKernel ('op: "_HostSend" device_type: "CPU"') for unknown op: _HostSend
2020-04-28 10:17:51.744290: E tensorflow/core/framework/op_kernel.cc:1426] OpKernel ('op: "WrapDatasetVariant" device_type: "CPU"') for unknown op: WrapDatasetVariant
2020-04-28 10:17:51.744547: E tensorflow/core/framework/op_kernel.cc:1426] OpKernel ('op: "WrapDatasetVariant" device_type: "GPU" host_memory_arg: "input_handle" host_memory_arg: "output_handle"') for unknown op: WrapDatasetVariant
2020-04-28 10:17:51.744915: E tensorflow/core/framework/op_kernel.cc:1426] OpKernel ('op: "UnwrapDatasetVariant" device_type: "CPU"') for unknown op: UnwrapDatasetVariant
2020-04-28 10:17:51.745166: E tensorflow/core/framework/op_kernel.cc:1426] OpKernel ('op: "UnwrapDatasetVariant" device_type: "GPU" host_memory_arg: "input_handle" host_memory_arg: "output_handle"') for unknown op: UnwrapDatasetVariant
2020-04-28 10:17:51.745559: I tensorflow/lite/toco/import_tensorflow.cc:1385] Unable to determine output type for op: Enter
2020-04-28 10:17:51.745775: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: Enter
2020-04-28 10:17:51.745986: I tensorflow/lite/toco/import_tensorflow.cc:1385] Unable to determine output type for op: Enter
2020-04-28 10:17:51.749493: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: NonMaxSuppressionV3
2020-04-28 10:17:51.749813: I tensorflow/lite/toco/import_tensorflow.cc:1385] Unable to determine output type for op: NonMaxSuppressionV3
2020-04-28 10:17:51.750256: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: CropAndResize
2020-04-28 10:17:51.750446: I tensorflow/lite/toco/import_tensorflow.cc:1385] Unable to determine output type for op: CropAndResize
2020-04-28 10:17:51.750635: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: CropAndResize
2020-04-28 10:17:51.750885: I tensorflow/lite/toco/import_tensorflow.cc:1385] Unable to determine output type for op: CropAndResize
2020-04-28 10:17:51.751075: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: CropAndResize
2020-04-28 10:17:51.751259: I tensorflow/lite/toco/import_tensorflow.cc:1385] Unable to determine output type for op: CropAndResize
2020-04-28 10:17:51.751449: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: CropAndResize
2020-04-28 10:17:51.751639: I tensorflow/lite/toco/import_tensorflow.cc:1385] Unable to determine output type for op: CropAndResize
2020-04-28 10:17:51.752170: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: DenseToDenseSetOperation
2020-04-28 10:17:51.752374: I tensorflow/lite/toco/import_tensorflow.cc:1385] Unable to determine output type for op: DenseToDenseSetOperation
2020-04-28 10:17:51.752614: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: Enter
2020-04-28 10:17:51.752883: I tensorflow/lite/toco/import_tensorflow.cc:1385] Unable to determine output type for op: Enter
2020-04-28 10:17:51.753200: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: Enter
2020-04-28 10:17:51.753378: I tensorflow/lite/toco/import_tensorflow.cc:1385] Unable to determine output type for op: Enter
2020-04-28 10:17:51.753555: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: Enter
2020-04-28 10:17:51.753809: I tensorflow/lite/toco/import_tensorflow.cc:1385] Unable to determine output type for op: Enter
2020-04-28 10:17:51.754059: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: TensorArrayV3
2020-04-28 10:17:51.754248: I tensorflow/lite/toco/import_tensorflow.cc:1385] Unable to determine output type for op: TensorArrayV3
2020-04-28 10:17:51.754448: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: TensorArrayV3
2020-04-28 10:17:51.754642: I tensorflow/lite/toco/import_tensorflow.cc:1385] Unable to determine output type for op: TensorArrayV3
2020-04-28 10:17:51.754866: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: Enter
2020-04-28 10:17:51.755043: I tensorflow/lite/toco/import_tensorflow.cc:1385] Unable to determine output type for op: Enter
2020-04-28 10:17:51.755228: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: Enter
2020-04-28 10:17:51.755405: I tensorflow/lite/toco/import_tensorflow.cc:1385] Unable to determine output type for op: Enter
2020-04-28 10:17:51.755581: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: Enter
2020-04-28 10:17:51.755824: I tensorflow/lite/toco/import_tensorflow.cc:1385] Unable to determine output type for op: Enter
2020-04-28 10:17:51.756000: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: Enter
2020-04-28 10:17:51.756178: I tensorflow/lite/toco/import_tensorflow.cc:1385] Unable to determine output type for op: Enter
2020-04-28 10:17:51.756357: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: TensorArrayScatterV3
2020-04-28 10:17:51.756561: I tensorflow/lite/toco/import_tensorflow.cc:1385] Unable to determine output type for op: TensorArrayScatterV3
2020-04-28 10:17:51.756843: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: Enter
2020-04-28 10:17:51.757028: I tensorflow/lite/toco/import_tensorflow.cc:1385] Unable to determine output type for op: Enter
2020-04-28 10:17:51.757201: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: Enter
2020-04-28 10:17:51.757381: I tensorflow/lite/toco/import_tensorflow.cc:1385] Unable to determine output type for op: Enter
2020-04-28 10:17:51.757568: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: LoopCond
2020-04-28 10:17:51.757818: I tensorflow/lite/toco/import_tensorflow.cc:1385] Unable to determine output type for op: LoopCond
2020-04-28 10:17:51.758011: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: Exit
2020-04-28 10:17:51.758182: I tensorflow/lite/toco/import_tensorflow.cc:1385] Unable to determine output type for op: Exit
2020-04-28 10:17:51.758421: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: TensorArrayReadV3
2020-04-28 10:17:51.758620: I tensorflow/lite/toco/import_tensorflow.cc:1385] Unable to determine output type for op: TensorArrayReadV3
2020-04-28 10:17:51.758896: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: TensorArraySizeV3
2020-04-28 10:17:51.759079: I tensorflow/lite/toco/import_tensorflow.cc:1385] Unable to determine output type for op: TensorArraySizeV3
2020-04-28 10:17:51.759284: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: TensorArrayGatherV3
2020-04-28 10:17:51.759473: I tensorflow/lite/toco/import_tensorflow.cc:1385] Unable to determine output type for op: TensorArrayGatherV3
2020-04-28 10:17:51.759756: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: NonMaxSuppressionV3
2020-04-28 10:17:51.759961: I tensorflow/lite/toco/import_tensorflow.cc:1385] Unable to determine output type for op: NonMaxSuppressionV3
2020-04-28 10:17:51.760172: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: DenseToDenseSetOperation
2020-04-28 10:17:51.760355: I tensorflow/lite/toco/import_tensorflow.cc:1385] Unable to determine output type for op: DenseToDenseSetOperation
2020-04-28 10:17:51.760588: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: TensorArrayWriteV3
2020-04-28 10:17:51.760812: I tensorflow/lite/toco/import_tensorflow.cc:1385] Unable to determine output type for op: TensorArrayWriteV3
2020-04-28 10:17:51.761182: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: CropAndResize
2020-04-28 10:17:51.761369: I tensorflow/lite/toco/import_tensorflow.cc:1385] Unable to determine output type for op: CropAndResize
2020-04-28 10:17:51.761563: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: CropAndResize
2020-04-28 10:17:51.761805: I tensorflow/lite/toco/import_tensorflow.cc:1385] Unable to determine output type for op: CropAndResize
2020-04-28 10:17:51.762121: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: CropAndResize
2020-04-28 10:17:51.762294: I tensorflow/lite/toco/import_tensorflow.cc:1385] Unable to determine output type for op: CropAndResize
2020-04-28 10:17:51.762476: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: CropAndResize
2020-04-28 10:17:51.762647: I tensorflow/lite/toco/import_tensorflow.cc:1385] Unable to determine output type for op: CropAndResize
2020-04-28 10:17:51.882698: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 1509 operators, 2776 arrays (0 quantized)
2020-04-28 10:17:51.972229: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 1509 operators, 2776 arrays (0 quantized)
2020-04-28 10:17:52.639779: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 1: 625 operators, 1351 arrays (0 quantized)
2020-04-28 10:17:52.676911: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 2: 617 operators, 1343 arrays (0 quantized)
2020-04-28 10:17:52.712779: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 3: 615 operators, 1339 arrays (0 quantized)
2020-04-28 10:17:52.748882: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Group bidirectional sequence lstm/rnn: 615 operators, 1339 arrays (0 quantized)
2020-04-28 10:17:52.777368: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before dequantization graph transformations: 615 operators, 1339 arrays (0 quantized)
2020-04-28 10:17:52.813057: I tensorflow/lite/toco/allocate_transient_arrays.cc:345] Total transient array allocated size: 1208238720 bytes, theoretical optimal value: 805306560 bytes.
2020-04-28 10:17:52.822540: E tensorflow/lite/toco/toco_tooling.cc:456] We are continually in the process of adding support to TensorFlow Lite for more ops. It would be helpful if you could inform us of how this conversion went by opening a github issue at https://github.com/tensorflow/tensorflow/issues/new?template=40-tflite-op-request.md
 and pasting the following:

Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, ARG_MAX, CAST, CONCATENATION, CONV_2D, DIV, EQUAL, EXP, EXPAND_DIMS, FULLY_CONNECTED, GATHER, GATHER_ND, GREATER, GREATER_EQUAL, LESS, LOG, LOGICAL_AND, LOGISTIC, MAXIMUM, MAX_POOL_2D, MINIMUM, MUL, PACK, PAD, PADV2, RANGE, REDUCE_MAX, RESHAPE, RESIZE_NEAREST_NEIGHBOR, ROUND, SHAPE, SOFTMAX, SPARSE_TO_DENSE, SPLIT, SQRT, SQUEEZE, STRIDED_SLICE, SUB, SUM, TOPK_V2, TRANSPOSE_CONV, UNIQUE, WHERE. Here is a list of operators for which you will need custom implementations: CropAndResize, DenseToDenseSetOperation, Enter, Exit, LoopCond, Merge, NonMaxSuppressionV3, Switch, TensorArrayGatherV3, TensorArrayReadV3, TensorArrayScatterV3, TensorArraySizeV3, TensorArrayV3, TensorArrayWriteV3.
Traceback (most recent call last):
  File "e:\anaconda3\envs\tensorflow-gpu-1-14\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "e:\anaconda3\envs\tensorflow-gpu-1-14\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\Anaconda3\envs\tensorflow-gpu-1-14\Scripts\toco_from_protos.exe\__main__.py", line 7, in <module>
  File "e:\anaconda3\envs\tensorflow-gpu-1-14\lib\site-packages\tensorflow\lite\toco\python\toco_from_protos.py", line 59, in main
    app.run(main=execute, argv=[sys.argv[0]] + unparsed)
  File "e:\anaconda3\envs\tensorflow-gpu-1-14\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "e:\anaconda3\envs\tensorflow-gpu-1-14\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "e:\anaconda3\envs\tensorflow-gpu-1-14\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "e:\anaconda3\envs\tensorflow-gpu-1-14\lib\site-packages\tensorflow\lite\toco\python\toco_from_protos.py", line 33, in execute
    output_str = tensorflow_wrap_toco.TocoConvert(model_str, toco_str, input_str)
Exception: We are continually in the process of adding support to TensorFlow Lite for more ops. It would be helpful if you could inform us of how this conversion went by opening a github issue at https://github.com/tensorflow/tensorflow/issues/new?template=40-tflite-op-request.md
 and pasting the following:

Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, ARG_MAX, CAST, CONCATENATION, CONV_2D, DIV, EQUAL, EXP, EXPAND_DIMS, FULLY_CONNECTED, GATHER, GATHER_ND, GREATER, GREATER_EQUAL, LESS, LOG, LOGICAL_AND, LOGISTIC, MAXIMUM, MAX_POOL_2D, MINIMUM, MUL, PACK, PAD, PADV2, RANGE, REDUCE_MAX, RESHAPE, RESIZE_NEAREST_NEIGHBOR, ROUND, SHAPE, SOFTMAX, SPARSE_TO_DENSE, SPLIT, SQRT, SQUEEZE, STRIDED_SLICE, SUB, SUM, TOPK_V2, TRANSPOSE_CONV, UNIQUE, WHERE. Here is a list of operators for which you will need custom implementations: CropAndResize, DenseToDenseSetOperation, Enter, Exit, LoopCond, Merge, NonMaxSuppressionV3, Switch, TensorArrayGatherV3, TensorArrayReadV3, TensorArrayScatterV3, TensorArraySizeV3, TensorArrayV3, TensorArrayWriteV3.
```
that maybe the real problem while using python scripts don't show

**Comment by sandeep22-v** [comment]
Update podungo

**Comment by maazullah96** [comment]
I am trying to convert yolov4.weights file to tflite file in colab but I am getting the same 
Can you guide me how to solve this issue
[error.txt](https://github.com/tensorflow/tensorflow/files/6823449/error.txt)

**Comment by junhui-ng** [comment]
Any update?
