### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by prayalankar2** [tensorflow/tensorflow#2677]
I am trying to import tensorflow (I have installed on 14.04 LTS and tensorflow 0.8) but it shows atributeError: module 'imp' has no attribute 'find_module'

Traceback (most recent call last): File "", line 1, in File "/home/prayalankar/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/init.py", line 23, in from tensorflow.python import * File "/home/prayalankar/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/init.py", line 45, in from tensorflow.python import pywrap_tensorflow File "/home/prayalankar/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in _pywrap_tensorflow = swig_import_helper() File "/home/prayalankar/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 18, in swig_import_helper fp, pathname, description = imp.find_module('_pywrap_tensorflow', [dirname(file)]) AttributeError: module 'imp' has no attribute 'find_module'

How to proceed.

**Comment by prayalankar2** [comment]
I got tensorflow  working but by installing on Python 2.7 on my conda platform without any error. Above problem is still there i checked it and i think Python has changed the find_module to reload() in 3.x so it might be the problem but i do not know how to fix this .
Still looking for solution (solid) for 3.x

**Comment by mrry** [comment]
In your Python 3.x shell, can you please run the following:

```python
import imp
print(dir(imp))
print(imp.__file__)
```

...and let us know what it prints. The `find_module()` function [should be available](https://docs.python.org/3/library/imp.html#imp.find_module) in Python 3.5, which you appear to be using, so I'm not sure why this would happen. (One possibility is that there's a file called `imp.py` in your PYTHONPATH, and that's causing it to get confused.)

**Comment by prayalankar2** [comment]
I am getting following output. I think there is no **find_module()**

>>> import imp
>>> print(dir(imp))
['Example', 'Flask', 'SQLAlchemy', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'app', 'db']
>>> print(imp.__file__)
/home/prayalankar/imp.py

**Comment by mrry** [comment]
The problem is that there's a file called `imp.py` in your PYTHONPATH. In particular, it looks like it's in `/home/prayalankar/imp.py`.

There are two options for fixing this:

1. Rename `/home/prayalankar/imp.py` to something else, so that it doesn't clash with the name of a built-in Python module, or
2. Change your PYTHONPATH so that it no longer includes `/home/prayalankar`.
