### ISSUE TITLE
1.13 ImportError when importing tf.contrib

### ISSUE THREAD

**Issue by jvdgoltz** [tensorflow/tensorflow#26794]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: -
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.13.1
- Python version: 3.6.7
- Bazel version (if compiling from source): -
- GCC/Compiler version (if compiling from source): -
- CUDA/cuDNN version: 10.1
- GPU model and memory:  GeForce 940MX, 4GB

**Describe the current behavior**
When I import tf.contrib I get the following Error:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/julian/tensorflow-gpu/lib/python3.6/site-packages/tensorflow/contrib/__init__.py", line 40, in <module>
    from tensorflow.contrib import distribute
  File "/home/julian/tensorflow-gpu/lib/python3.6/site-packages/tensorflow/contrib/distribute/__init__.py", line 33, in <module>
    from tensorflow.contrib.distribute.python.tpu_strategy import TPUStrategy
  File "/home/julian/tensorflow-gpu/lib/python3.6/site-packages/tensorflow/contrib/distribute/python/tpu_strategy.py", line 27, in <module>
    from tensorflow.contrib.tpu.python.ops import tpu_ops
  File "/home/julian/tensorflow-gpu/lib/python3.6/site-packages/tensorflow/contrib/tpu/__init__.py", line 73, in <module>
    from tensorflow.contrib.tpu.python.tpu.keras_support import tpu_model as keras_to_tpu_model
  File "/home/julian/tensorflow-gpu/lib/python3.6/site-packages/tensorflow/contrib/tpu/python/tpu/keras_support.py", line 62, in <module>
    from tensorflow.contrib.tpu.python.tpu import tpu
  File "/home/julian/tensorflow-gpu/lib/python3.6/site-packages/tensorflow/contrib/tpu/python/tpu/tpu.py", line 24, in <module>
    from tensorflow.contrib.compiler import xla
  File "/home/julian/tensorflow-gpu/lib/python3.6/site-packages/tensorflow/contrib/compiler/xla.py", line 28, in <module>
    from tensorflow.python.estimator import model_fn as model_fn_lib
  File "/home/julian/tensorflow-gpu/lib/python3.6/site-packages/tensorflow/python/estimator/model_fn.py", line 26, in <module>
    from tensorflow_estimator.python.estimator import model_fn
ImportError: cannot import name 'model_fn'

**Describe the expected behavior**

**Code to reproduce the issue**
`python -c "import tensorflow.contrib"`

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by BIGCRYPTO001** [comment]
What,

**Comment by jvdgoltz** [comment]
Problem disappeared after reinstallling tensorflow-estimator!

**Comment by plumtus** [comment]
@jvdgoltz This doesn't seem to work for me, when I reinstall tensorflow-estimator-1.13.0
