### ISSUE TITLE
ERROR!!! AttributeError: module '_pywrap_tensorflow_internal' has no attribute 'TF_ImportGraphDefOptionsSetDefaultDevice'

### ISSUE THREAD

**Issue by Rubinks** [tensorflow/tensorflow#26836]
my programm error!
Using TensorFlow backend.
Traceback (most recent call last):

  File "<ipython-input-2-658d4b6817ec>", line 1, in <module>
    runfile('C:/Users/svm2717/Desktop/test.py', wdir='C:/Users/svm2717/Desktop')

  File "D:\ANACONDA\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "D:\ANACONDA\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/svm2717/Desktop/test.py", line 8, in <module>
    from keras.datasets import mnist

  File "D:\ANACONDA\lib\site-packages\keras\__init__.py", line 3, in <module>
    from . import utils

  File "D:\ANACONDA\lib\site-packages\keras\utils\__init__.py", line 6, in <module>
    from . import conv_utils

  File "D:\ANACONDA\lib\site-packages\keras\utils\conv_utils.py", line 9, in <module>
    from .. import backend as K

  File "D:\ANACONDA\lib\site-packages\keras\backend\__init__.py", line 89, in <module>
    from .tensorflow_backend import *

  File "D:\ANACONDA\lib\site-packages\keras\backend\tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf

  File "D:\ANACONDA\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import

  File "D:\ANACONDA\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow

  File "D:\ANACONDA\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *

  File "D:\ANACONDA\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 1393, in <module>
    TF_ImportGraphDefOptionsSetDefaultDevice = _pywrap_tensorflow_internal.TF_ImportGraphDefOptionsSetDefaultDevice

AttributeError: module '_pywrap_tensorflow_internal' has no attribute 'TF_ImportGraphDefOptionsSetDefaultDevice'

CUDA:8.0

**Comment by Rubinks** [comment]
Decided to himself! For those who have the same error, just reinstall Tensorflow and everything will work!

**Comment by mihaimaruseac** [comment]
Closing as it seems solved. Please reopen if that's not the case
