### ISSUE TITLE
[TF2] tf.saved_model.save does not support type annotations

### ISSUE THREAD

**Issue by alanhdu** [tensorflow/tensorflow#26864]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): pip wheel
- TensorFlow version (use command below): `tf-nightly-2.0-preview==2.0.0.dev20190318`
- Python version: 3.7

**Describe the current behavior**
Given the following code:

```python
import tensorflow as tf

class A(tf.Module):
    @tf.function
    def func(self, x: int):
        pass


a = A() 
tf.saved_model.save(a, export_dir=".")
```

I get the following traceback:

```python
Traceback (most recent call last):
  File "scratch.py", line 10, in <module>
    tf.saved_model.save(a, export_dir=".")
  File "/opt/anaconda/envs/tf2/lib/python3.7/site-packages/tensorflow/python/saved_model/save.py", line 812, in save
    saveable_view, asset_info.asset_index)
  File "/opt/anaconda/envs/tf2/lib/python3.7/site-packages/tensorflow/python/saved_model/save.py", line 561, in _serialize_object_graph
    _write_object_proto(obj, obj_proto, asset_file_def_index)
  File "/opt/anaconda/envs/tf2/lib/python3.7/site-packages/tensorflow/python/saved_model/save.py", line 577, in _write_object_proto
    function_serialization.serialize_function(obj))
  File "/opt/anaconda/envs/tf2/lib/python3.7/site-packages/tensorflow/python/saved_model/function_serialization.py", line 81, in serialize_function
    function_spec_proto = _serialize_function_spec(function.function_spec, coder)
  File "/opt/anaconda/envs/tf2/lib/python3.7/site-packages/tensorflow/python/saved_model/function_serialization.py", line 29, in _serialize_function_spec
    proto.fullargspec.CopyFrom(coder.encode_structure(function_spec.fullargspec))
  File "/opt/anaconda/envs/tf2/lib/python3.7/site-packages/tensorflow/python/saved_model/nested_structure_coder.py", line 85, in encode_structure
    return self._map_structure(nested_structure, self._get_encoders())
  File "/opt/anaconda/envs/tf2/lib/python3.7/site-packages/tensorflow/python/saved_model/nested_structure_coder.py", line 69, in _map_structure
    return do(pyobj, recursion_fn)
  File "/opt/anaconda/envs/tf2/lib/python3.7/site-packages/tensorflow/python/saved_model/nested_structure_coder.py", line 224, in do_encode
    pair.value.CopyFrom(encode_fn(named_tuple_value._asdict()[key]))
  File "/opt/anaconda/envs/tf2/lib/python3.7/site-packages/tensorflow/python/saved_model/nested_structure_coder.py", line 69, in _map_structure
    return do(pyobj, recursion_fn)
  File "/opt/anaconda/envs/tf2/lib/python3.7/site-packages/tensorflow/python/saved_model/nested_structure_coder.py", line 193, in do_encode
    encoded_dict.dict_value.fields[key].CopyFrom(encode_fn(value))
  File "/opt/anaconda/envs/tf2/lib/python3.7/site-packages/tensorflow/python/saved_model/nested_structure_coder.py", line 71, in _map_structure
    "No encoder for object [%s] of type [%s]." % (str(pyobj), type(pyobj)))
tensorflow.python.saved_model.nested_structure_coder.NotEncodableError: No encoder for object [<class 'int'>] of type [<class 'type'>].
```

**Describe the expected behavior**

Ideally, saving this would work just fine and not crash on the type annotation.

**Comment by allenlavoie** [comment]
@vbardiovskyg do we need an extension of structure coding for type annotations? I guess stripping them would be slightly better than throwing an exception, but long-term it seems like we want to save them. We should be able to add a Python 3-only unit test suite.

**Comment by alanhdu** [comment]
One work-around for now is to use `str` annotations like:

```python
def func(self, x: "int"):
    ...
```

In Python 3.7, doing 
```
from __future__ import annotations
```

will also by-default make all the type annotations strings without having to manually quote them.

**Comment by allenlavoie** [comment]
Oh interesting, we do save annotations, we just don't have a case for "int". Seems easy to add.

On the other hand, passing non-Tensors (like Python "int"s) to tf.functions will re-trace each time (i.e. each value of the integer will get its own graph). Out of curiosity, what is the Python int argument there for?

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
It has been 29 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
It has been 44 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
We are closing this issue for now due to lack of activity. Please comment if this is still an issue for you. Thanks!

**Comment by depthwise** [comment]
I'm seeing this issue again in RC0 when I provide `tf.Tensor` type annotation in `call()`. The exact error is:
```
tensorflow.python.saved_model.nested_structure_coder.NotEncodableError: No encoder for object [<class 'tensorflow.python.framework.ops.Tensor'>] of type [<class 'type'>].
```
Removing type annotations resolves the issue. This is, quite obviously, not ideal, so I think the issue should be re-opened.

**Comment by mr-ubik** [comment]
I have the same bug as @depthwise. Definitely should be reopened.
