### ISSUE TITLE
Converting to TF Lite with tf.lite.OpsSet.SELECT_TF_OPS is bounded

### ISSUE THREAD

**Issue by osanwe** [tensorflow/tensorflow#26869]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Linux Ubuntu 16.04
- TensorFlow installed from (source or binary):
binary
- TensorFlow version (use command below):
v1.13.1-0-g6612da8951
- Python version:
3.5.6 (Anaconda)
- CUDA/cuDNN version:
CPU version

I am trying to export a very simple model (see code below) into TensorFlow Lite with loss function [1] and gradients [2] calculation support using the official tutorial [3].

**Describe the current behavior**
The model can be converted only when global step variable and custom cross entropy implementation are used (but it cannot be run on Android). Without one of them or both the converting process crashes.

**Describe the expected behavior**
The model should be converted with standard cross entropy implementation and without explicitly defined global step variable.

**Code to reproduce the issue**
```python
import numpy as np
import tensorflow as tf


use_custom_crossentropy = True
use_global_step = True


inputs = np.array([[0.0, 0.0], [0.0, 1.0], [1.0, 0.0], [1.0, 1.0]])
labels = np.array([[0.0], [1.0], [1.0], [0.0]])

global_step = tf.Variable(0, trainable=False, name='global_step')
x = tf.placeholder(tf.float32, shape=(None, 2), name='Input')
y = tf.placeholder(tf.float32, shape=(None, 1), name='Output')

with tf.name_scope('layer1'):
    w1 = tf.Variable(tf.random_uniform([2, 2], -1., 1.), name='w1')
    b1 = tf.Variable(tf.zeros([2]), name='b1')
    l1 = tf.add(tf.matmul(x, w1), b1, name='l1')
    l1 = tf.nn.sigmoid(l1)

with tf.name_scope('layer2'):
    w2 = tf.Variable(tf.random_uniform([2, 1], -1., 1.), name='w2')
    b2 = tf.Variable(tf.zeros([1]), name='b2')
    model = tf.add(tf.matmul(l1, w2), b2, name='model')

for variable in tf.trainable_variables():
    var_name = variable.name.split(':')[0].replace('/', '_')
    var_value_ph = tf.placeholder(tf.float32, shape=variable.shape, name='{}_ph'.format(var_name))
    var_value_assign = tf.assign(variable, var_value_ph, name='{}_assign'.format(var_name))
    print(var_name, var_value_ph.name, var_value_assign.name)

if use_custom_crossentropy:
    cost = tf.nn.sigmoid(model)
    cost = tf.maximum(cost, 0.0) - cost * y + tf.log(1 + tf.exp(-tf.abs(cost)))
    cost = tf.reduce_mean(cost, name='cost')
else:
    cost = tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(labels=y, logits=model),
                          name='cost')
optimizer = tf.train.AdamOptimizer(name='optimizer')
if use_global_step:
    train_op = optimizer.minimize(cost, global_step=global_step)
else:
    train_op = optimizer.minimize(cost)

init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)

for step in range(10000):
    sess.run(train_op, feed_dict={x: inputs, y: labels})
print(sess.run(model, feed_dict={x: inputs}))

converter = tf.lite.TFLiteConverter.from_session(sess,
                                                 [x, y], [model, cost, train_op])
converter.target_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,
                        tf.lite.OpsSet.SELECT_TF_OPS]
tflite_model = converter.convert()
with open('xor_old.tflite', 'wb') as f:
    f.write(tflite_model)
```

**Other info / logs**
```
use_custom_crossentropy = True
use_global_step = True
```
```
WARNING:tensorflow:From $HOME/miniconda3/envs/tf-cpu/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
layer1_w1 layer1_w1_ph:0 layer1_w1_assign:0
layer1_b1 layer1_b1_ph:0 layer1_b1_assign:0
layer2_w2 layer2_w2_ph:0 layer2_w2_assign:0
layer2_b2 layer2_b2_ph:0 layer2_b2_assign:0
2019-03-19 12:09:59.552926: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-03-19 12:09:59.586599: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2592000000 Hz
2019-03-19 12:09:59.587967: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x5601b1c8d640 executing computations on platform Host. Devices:
2019-03-19 12:09:59.587988: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
[[-6.7735147]
 [-7.4516478]
 [ 4.8298645]
 [-6.928589 ]]
WARNING:tensorflow:From $HOME/miniconda3/envs/tf-cpu/lib/python3.5/site-packages/tensorflow/lite/python/lite.py:591: convert_variables_to_constants (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.compat.v1.graph_util.convert_variables_to_constants
WARNING:tensorflow:From $HOME/miniconda3/envs/tf-cpu/lib/python3.5/site-packages/tensorflow/python/framework/graph_util_impl.py:245: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.compat.v1.graph_util.extract_sub_graph
```
```
use_custom_crossentropy = False
use_global_step = True
```
```
WARNING:tensorflow:From $HOME/miniconda3/envs/tf-cpu/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprec
ated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
layer1_w1 layer1_w1_ph:0 layer1_w1_assign:0
layer1_b1 layer1_b1_ph:0 layer1_b1_assign:0
layer2_w2 layer2_w2_ph:0 layer2_w2_assign:0
layer2_b2 layer2_b2_ph:0 layer2_b2_assign:0
2019-03-19 12:10:47.189917: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-03-19 12:10:47.214732: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2592000000 Hz
2019-03-19 12:10:47.215498: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x560ffe1fcd90 executing computations on platform Host. Devices:
2019-03-19 12:10:47.215538: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
[[-3.9300842]
 [ 3.913724 ]
 [ 3.9203634]
 [-3.8768034]]
WARNING:tensorflow:From $HOME/miniconda3/envs/tf-cpu/lib/python3.5/site-packages/tensorflow/lite/python/lite.py:591: convert_variables_to_constants (from tensorflow.python.framework.graph_util_i
mpl) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.compat.v1.graph_util.convert_variables_to_constants
WARNING:tensorflow:From $HOME/miniconda3/envs/tf-cpu/lib/python3.5/site-packages/tensorflow/python/framework/graph_util_impl.py:245: extract_sub_graph (from tensorflow.python.framework.graph_uti
l_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.compat.v1.graph_util.extract_sub_graph
Traceback (most recent call last):
  File "./training_old_version.py", line 58, in <module>
    tflite_model = converter.convert()
  File "$HOME/miniconda3/envs/tf-cpu/lib/python3.5/site-packages/tensorflow/lite/python/lite.py", line 455, in convert
    **converter_kwargs)
  File "$HOME/miniconda3/envs/tf-cpu/lib/python3.5/site-packages/tensorflow/lite/python/convert.py", line 442, in toco_convert_impl
    input_data.SerializeToString())
  File "$HOME/miniconda3/envs/tf-cpu/lib/python3.5/site-packages/tensorflow/lite/python/convert.py", line 205, in toco_convert_protos
    "TOCO failed. See console for info.\n%s\n%s\n" % (stdout, stderr))
tensorflow.lite.python.convert.ConverterError: TOCO failed. See console for info.
2019-03-19 12:10:51.425153: I tensorflow/lite/toco/import_tensorflow.cc:1324] Converting unsupported operation: Log1p
2019-03-19 12:10:51.434088: I tensorflow/lite/toco/import_tensorflow.cc:1324] Converting unsupported operation: BroadcastGradientArgs
2019-03-19 12:10:51.434177: I tensorflow/lite/toco/import_tensorflow.cc:1324] Converting unsupported operation: BroadcastGradientArgs
2019-03-19 12:10:51.434246: I tensorflow/lite/toco/import_tensorflow.cc:1324] Converting unsupported operation: Reciprocal
2019-03-19 12:10:51.434268: I tensorflow/lite/toco/import_tensorflow.cc:1324] Converting unsupported operation: BroadcastGradientArgs
2019-03-19 12:10:51.434696: I tensorflow/lite/toco/import_tensorflow.cc:1324] Converting unsupported operation: BroadcastGradientArgs
2019-03-19 12:10:51.434748: I tensorflow/lite/toco/import_tensorflow.cc:1324] Converting unsupported operation: SigmoidGrad
2019-03-19 12:10:51.434761: I tensorflow/lite/toco/import_tensorflow.cc:1324] Converting unsupported operation: BroadcastGradientArgs
2019-03-19 12:10:51.434834: I tensorflow/lite/toco/import_tensorflow.cc:1324] Converting unsupported operation: ApplyAdam
2019-03-19 12:10:51.434848: I tensorflow/lite/toco/import_tensorflow.cc:1324] Converting unsupported operation: ApplyAdam
2019-03-19 12:10:51.434860: I tensorflow/lite/toco/import_tensorflow.cc:1324] Converting unsupported operation: ApplyAdam
2019-03-19 12:10:51.434871: I tensorflow/lite/toco/import_tensorflow.cc:1324] Converting unsupported operation: ApplyAdam
2019-03-19 12:10:51.434884: I tensorflow/lite/toco/import_tensorflow.cc:1324] Converting unsupported operation: Assign
2019-03-19 12:10:51.434902: I tensorflow/lite/toco/import_tensorflow.cc:1324] Converting unsupported operation: Assign
2019-03-19 12:10:51.434918: I tensorflow/lite/toco/import_tensorflow.cc:1324] Converting unsupported operation: AssignAdd
2019-03-19 12:10:51.436899: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 110 operators, 148 arrays (0 quantized)
2019-03-19 12:10:51.437594: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After Removing unused ops pass 1: 21 operators, 30 arrays (0 quantized)
2019-03-19 12:10:51.438536: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 21 operators, 30 arrays (0 quantized)
2019-03-19 12:10:51.438758: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 1: 15 operators, 24 arrays (0 quantized)
2019-03-19 12:10:51.438853: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before dequantization graph transformations: 15 operators, 24 arrays (0 quantized)
2019-03-19 12:10:51.438930: I tensorflow/lite/toco/allocate_transient_arrays.cc:345] Total transient array allocated size: 256 bytes, theoretical optimal value: 192 bytes.
2019-03-19 12:10:51.439212: W tensorflow/lite/toco/tflite/operator.cc:1768] Op Log1p is a valid TensorFlow op but has not been whitelisted for the TensorFlow Lite flex op set.
2019-03-19 12:10:51.439273: W tensorflow/lite/toco/tflite/operator.cc:1768] Op Log1p is a valid TensorFlow op but has not been whitelisted for the TensorFlow Lite flex op set.
2019-03-19 12:10:51.439319: E tensorflow/lite/toco/toco_tooling.cc:421] We are continually in the process of adding support to TensorFlow Lite for more ops. It would be helpful if you could inform us of h
ow this conversion went by opening a github issue at https://github.com/tensorflow/tensorflow/issues/new?template=40-tflite-op-request.md
 and pasting the following:

Some of the operators in the model are not supported by the standard TensorFlow Lite runtime and are not recognized by TensorFlow. If you have a custom implementation for them you can disable this error w
ith --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, EXP, FULLY_CONNECTED, GREATER_EQUAL, LOGISTIC, M
EAN, MUL, NEG, SELECT, SUB, ZEROS_LIKE. Here is a list of operators for which you will need custom implementations: Log1p.
Traceback (most recent call last):
  File "$HOME/miniconda3/envs/tf-cpu/bin/toco_from_protos", line 11, in <module>
    sys.exit(main())
  File "$HOME/miniconda3/envs/tf-cpu/lib/python3.5/site-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 59, in main
    app.run(main=execute, argv=[sys.argv[0]] + unparsed)
  File "$HOME/miniconda3/envs/tf-cpu/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "$HOME/miniconda3/envs/tf-cpu/lib/python3.5/site-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 33, in execute
    output_str = tensorflow_wrap_toco.TocoConvert(model_str, toco_str, input_str)
Exception: We are continually in the process of adding support to TensorFlow Lite for more ops. It would be helpful if you could inform us of how this conversion went by opening a github issue at https://
github.com/tensorflow/tensorflow/issues/new?template=40-tflite-op-request.md
 and pasting the following:

Some of the operators in the model are not supported by the standard TensorFlow Lite runtime and are not recognized by TensorFlow. If you have a custom implementation for them you can disable this error w
ith --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, EXP, FULLY_CONNECTED, GREATER_EQUAL, LOGISTIC, M
EAN, MUL, NEG, SELECT, SUB, ZEROS_LIKE. Here is a list of operators for which you will need custom implementations: Log1p.
```
```
use_custom_crossentropy = True
use_global_step = False
```
```
WARNING:tensorflow:From $HOME/miniconda3/envs/tf-cpu/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprec
ated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
layer1_w1 layer1_w1_ph:0 layer1_w1_assign:0
layer1_b1 layer1_b1_ph:0 layer1_b1_assign:0
layer2_w2 layer2_w2_ph:0 layer2_w2_assign:0
layer2_b2 layer2_b2_ph:0 layer2_b2_assign:0
2019-03-19 12:13:04.851757: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-03-19 12:13:04.874754: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2592000000 Hz
2019-03-19 12:13:04.875673: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x55832b67a430 executing computations on platform Host. Devices:
2019-03-19 12:13:04.875706: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
[[-6.0365562]
 [-6.613834 ]
 [ 5.176443 ]
 [-6.16683  ]]
WARNING:tensorflow:From $HOME/miniconda3/envs/tf-cpu/lib/python3.5/site-packages/tensorflow/lite/python/lite.py:591: convert_variables_to_constants (from tensorflow.python.framework.graph_util_i
mpl) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.compat.v1.graph_util.convert_variables_to_constants
WARNING:tensorflow:From $HOME/miniconda3/envs/tf-cpu/lib/python3.5/site-packages/tensorflow/python/framework/graph_util_impl.py:245: extract_sub_graph (from tensorflow.python.framework.graph_uti
l_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.compat.v1.graph_util.extract_sub_graph
Traceback (most recent call last):
  File "./training_old_version.py", line 58, in <module>
    tflite_model = converter.convert()
  File "$HOME/miniconda3/envs/tf-cpu/lib/python3.5/site-packages/tensorflow/lite/python/lite.py", line 455, in convert
    **converter_kwargs)
  File "$HOME/miniconda3/envs/tf-cpu/lib/python3.5/site-packages/tensorflow/lite/python/convert.py", line 442, in toco_convert_impl
    input_data.SerializeToString())
  File "$HOME/miniconda3/envs/tf-cpu/lib/python3.5/site-packages/tensorflow/lite/python/convert.py", line 205, in toco_convert_protos
    "TOCO failed. See console for info.\n%s\n%s\n" % (stdout, stderr))
tensorflow.lite.python.convert.ConverterError: TOCO failed. See console for info.
2019-03-19 12:13:09.381975: I tensorflow/lite/toco/import_tensorflow.cc:1324] Converting unsupported operation: BroadcastGradientArgs
2019-03-19 12:13:09.391489: I tensorflow/lite/toco/import_tensorflow.cc:1324] Converting unsupported operation: BroadcastGradientArgs
2019-03-19 12:13:09.391555: I tensorflow/lite/toco/import_tensorflow.cc:1324] Converting unsupported operation: Reciprocal
2019-03-19 12:13:09.391587: I tensorflow/lite/toco/import_tensorflow.cc:1324] Converting unsupported operation: BroadcastGradientArgs
2019-03-19 12:13:09.391865: I tensorflow/lite/toco/import_tensorflow.cc:1324] Converting unsupported operation: BroadcastGradientArgs
2019-03-19 12:13:09.391898: I tensorflow/lite/toco/import_tensorflow.cc:1324] Converting unsupported operation: BroadcastGradientArgs
2019-03-19 12:13:09.391924: I tensorflow/lite/toco/import_tensorflow.cc:1324] Converting unsupported operation: Sign
2019-03-19 12:13:09.391942: I tensorflow/lite/toco/import_tensorflow.cc:1324] Converting unsupported operation: SigmoidGrad
2019-03-19 12:13:09.391957: I tensorflow/lite/toco/import_tensorflow.cc:1324] Converting unsupported operation: BroadcastGradientArgs
2019-03-19 12:13:09.391988: I tensorflow/lite/toco/import_tensorflow.cc:1324] Converting unsupported operation: SigmoidGrad
2019-03-19 12:13:09.392002: I tensorflow/lite/toco/import_tensorflow.cc:1324] Converting unsupported operation: BroadcastGradientArgs
2019-03-19 12:13:09.392080: I tensorflow/lite/toco/import_tensorflow.cc:1324] Converting unsupported operation: ApplyAdam
2019-03-19 12:13:09.392096: I tensorflow/lite/toco/import_tensorflow.cc:1324] Converting unsupported operation: ApplyAdam
2019-03-19 12:13:09.392108: I tensorflow/lite/toco/import_tensorflow.cc:1324] Converting unsupported operation: ApplyAdam
2019-03-19 12:13:09.392120: I tensorflow/lite/toco/import_tensorflow.cc:1324] Converting unsupported operation: ApplyAdam
2019-03-19 12:13:09.392134: I tensorflow/lite/toco/import_tensorflow.cc:1324] Converting unsupported operation: Assign
2019-03-19 12:13:09.392148: I tensorflow/lite/toco/import_tensorflow.cc:1324] Converting unsupported operation: Assign
2019-03-19 12:13:09.393103: F tensorflow/lite/toco/tooling_util.cc:905] Check failed: GetOpWithOutput(model, output_array) Specified output array "optimizer" is not produced by any op in this graph. Is it
 a typo? To silence this message, pass this flag:  allow_nonexistent_arrays
Aborted (core dumped)
```
Below presented a log from Android for the successfully converted model.
```
2019-03-19 11:24:38.739 32452-32452/com.example.tflite E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.tflite, PID: 32452
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.tflite/com.example.tflite.MainActivity}: java.lang.IllegalArgumentException: Internal error: Failed to run on the given Interpreter: cannot compute AssignAdd as input #0(zero-based) was expected to be a int32_ref tensor but is a int32 tensor
    	 (while executing 'AssignAdd' via Eager)Node number 15 (DELEGATE) failed to invoke.
    
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3086)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3229)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1926)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:213)
        at android.app.ActivityThread.main(ActivityThread.java:6981)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
     Caused by: java.lang.IllegalArgumentException: Internal error: Failed to run on the given Interpreter: cannot compute AssignAdd as input #0(zero-based) was expected to be a int32_ref tensor but is a int32 tensor
    	 (while executing 'AssignAdd' via Eager)Node number 15 (DELEGATE) failed to invoke.
    
        at org.tensorflow.lite.NativeInterpreterWrapper.run(Native Method)
        at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:149)
        at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:275)
        at com.example.tflite.MainActivity.onCreate(MainActivity.java:53)
        at android.app.Activity.performCreate(Activity.java:7326)
        at android.app.Activity.performCreate(Activity.java:7317)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3066)
        	... 11 more
```

[1] https://github.com/tensorflow/tensorflow/blob/v1.13.1/tensorflow/lite/toco/tflite/whitelisted_flex_ops.cc#L333-L334
[2] https://github.com/tensorflow/tensorflow/blob/v1.13.1/tensorflow/lite/toco/tflite/whitelisted_flex_ops.cc#L35
[3] https://www.tensorflow.org/lite/guide/ops_select#converting_the_model

**Comment by haozha111** [comment]
When you use the non-custom loss implementation, internally TF will call the log1p operator, which is not supported by TF Lite (it's neither built-in nor select). So this will crash the conversion process.

I'm wondering if you could strip loss/train_op from the model and then convert it to TF Lite. TF Lite models can't be used for training, since it doesn't support gradient ops or variable updates.

**Comment by haozha111** [comment]
Forgot the attach the code link where log1p is called:

**Comment by osanwe** [comment]
I kept in mind the following.

The difference between the operations set of this simple graph (it includes training and assigning operations) and the set of allowed select operations is an empty set [1]. So if I recompile TF Lite for Android with select operations support [2] it will be possible to train model with TF Lite.

[1] https://colab.research.google.com/drive/1rpKNTPZ4z914PNqGzXlH3pnUDQnr5pVe
[2] https://www.tensorflow.org/lite/guide/ops_select#android_aar

**Comment by miaout17** [comment]
Training in isn't supported in TensorFlow Lite. 
We're looking into supporting Training. Stay tuned.

**Comment by osanwe** [comment]
@haozha111, is it a not a good idea just to add `Log1p` operation into allowed Flex operations list?
It seems that the following modification works:
```
--- a/tensorflow/lite/toco/tflite/whitelisted_flex_ops.cc
+++ b/tensorflow/lite/toco/tflite/whitelisted_flex_ops.cc
@@ -170,6 +170,7 @@ bool IsWhitelistedFlexOp(const std::string& tensorflow_op_name) {
           "ListDiff",
           "_ListToArray",
           "Log",
+          "Log1p",
           "LogicalAnd",
           "LogicalNot",
           "LogicalOr",
```

**Comment by haozha111** [comment]
The conversion will probably succeed if you add that op into the whitelisted flex ops. However, I doubt it will work as expected if you want to train it on device. Because TF Lite graph can only be used for inference at the moment.

**Comment by osanwe** [comment]
Yes, conversion finished successfully, but after recompiling `*.aar` with `bazel build --cxxopt='--std=c++11' -c opt --config=android_arm --config=monolithic //tensorflow/lite/java:tensorflow-lite-with-select-tf-ops` I've got the error 
```
 Caused by: java.lang.IllegalArgumentException: Internal error: Failed to run on the given Interpreter: Could not find valid device for node.
Node: {{node Log1p}}
All kernels registered for op Log1p :
  <no registered kernels>

         (while executing 'Log1p' via Eager)Node number 14 (TfLiteFlexDelegate) failed to invoke.
```
It seems that some modifications in [`TfLiteFlexDelegate`](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/delegates/flex) are needed. Is it the right starting point?

> However, I doubt it will work as expected if you want to train it on device. Because TF Lite graph can only be used for inference at the moment.

I think it will be good starting point for expanding TfLite functionality.
