### ISSUE TITLE
Issue while importing tensorflow

### ISSUE THREAD

**Issue by rahulmonotype** [tensorflow/tensorflow#2689]
Facing issue while importing tensorflow. 
OS: Windows 8
Python version 2.7
Installation method anaconda. 
 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda2\envs\tensorflow_env\lib\site-packages\tensorflow\__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "C:\Anaconda2\envs\tensorflow_env\lib\site-packages\tensorflow\python\__init__.py", line 46, in <module>
    _default_dlopen_flags = sys.getdlopenflags()
AttributeError: 'module' object has no attribute 'getdlopenflags'

**Comment by girving** [comment]
Unfortunately, TensorFlow is not yet supported on Windows.

**Comment by jasoncwy** [comment]
Hi, may I know if your issue has been solved? since tensorflow is now supported on Windows
