### ISSUE TITLE
Tensorboard crashed when keras finish train in eager execution

### ISSUE THREAD

**Issue by fsx950223** [tensorflow/tensorflow#26973]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):binary
- TensorFlow version (use command below):1.13.1
- Python version:3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:10.0
- GPU model and memory:

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**
tensorboard crashed when keras finish training the model and do a record in tensorboard
**Describe the expected behavior**
tensorboard do the record normally
**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
``` python
  if True:
        model.compile(optimizer=tf.keras.optimizers.Adam(lr=1e-3), loss={
            # use custom yolo_loss Lambda layer.
            'yolo_loss': lambda y_true, y_pred: y_pred})

        model.fit_generator(data_generator(files,batch_size, input_shape, anchors, num_classes),
                    epochs=0, initial_epoch=0,
                    steps_per_epoch=max(1, sum // batch_size),
                    callbacks=[logging, checkpoint],
                    validation_data=data_generator(val_files, batch_size, input_shape, anchors,num_classes,train=False),
                    validation_steps=max(1, val_sum // batch_size))
        model.save_weights(log_dir + 'trained_weights_stage_1.h5')

    # Unfreeze and continue training, to fine-tune.
    # Train longer if the result is not good.
    if True:
        for i in range(len(model.layers)):
            model.layers[i].trainable = True
        model.compile(optimizer=tf.keras.optimizers.Adam(lr=1e-4),
                      loss={'yolo_loss': lambda y_true, y_pred: y_pred})  # recompile to apply the change
        print('Unfreeze all of the layers.')

        model.fit_generator(data_generator(files,batch_size, input_shape, anchors, num_classes),
                    epochs=1, initial_epoch=0, steps_per_epoch=max(1, sum // batch_size),
                    callbacks=[logging,checkpoint, reduce_lr, early_stopping],
                    validation_data=data_generator(val_files, batch_size, input_shape, anchors, num_classes,train=False),
                    validation_steps=max(1, val_sum // batch_size))
        model.save_weights(log_dir + 'trained_weights_final.h5')
```
**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
Traceback (most recent call last):
  File "/media/fangsixie/data/pycharm-2018.2.4/helpers/pydev/pydevd.py", line 1664, in <module>
    main()
  File "/media/fangsixie/data/pycharm-2018.2.4/helpers/pydev/pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/media/fangsixie/data/pycharm-2018.2.4/helpers/pydev/pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/media/fangsixie/data/pycharm-2018.2.4/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/media/fangsixie/data/keras-yolo3/train.py", line 192, in <module>
    _main()
  File "/media/fangsixie/data/keras-yolo3/train.py", line 78, in _main
    validation_steps=max(1, val_sum // batch_size))
  File "/home/fangsixie/.conda/envs/tensorflow1.12/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1426, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/fangsixie/.conda/envs/tensorflow1.12/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_generator.py", line 232, in model_iteration
    callbacks.on_epoch_end(epoch, epoch_logs, mode=mode)
  File "/home/fangsixie/.conda/envs/tensorflow1.12/lib/python3.6/site-packages/tensorflow/python/keras/callbacks.py", line 251, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/home/fangsixie/.conda/envs/tensorflow1.12/lib/python3.6/site-packages/tensorflow/python/keras/callbacks.py", line 1159, in on_epoch_end
    self._write_custom_summaries(step, logs)
  File "/home/fangsixie/.conda/envs/tensorflow1.12/lib/python3.6/site-packages/tensorflow/python/keras/callbacks.py", line 1106, in _write_custom_summaries
    summary_ops_v2.scalar(name, value, step=step)
  File "/home/fangsixie/.conda/envs/tensorflow1.12/lib/python3.6/site-packages/tensorflow/python/ops/summary_ops_v2.py", line 564, in scalar
    return summary_writer_function(name, tensor, function, family=family)
  File "/home/fangsixie/.conda/envs/tensorflow1.12/lib/python3.6/site-packages/tensorflow/python/ops/summary_ops_v2.py", line 508, in summary_writer_function
    should_record_summaries(), record, _nothing, name="")
  File "/home/fangsixie/.conda/envs/tensorflow1.12/lib/python3.6/site-packages/tensorflow/python/framework/smart_cond.py", line 54, in smart_cond
    return true_fn()
  File "/home/fangsixie/.conda/envs/tensorflow1.12/lib/python3.6/site-packages/tensorflow/python/ops/summary_ops_v2.py", line 501, in record
    with ops.control_dependencies([function(tag, scope)]):
  File "/home/fangsixie/.conda/envs/tensorflow1.12/lib/python3.6/site-packages/tensorflow/python/ops/summary_ops_v2.py", line 562, in function
    name=scope)
  File "/home/fangsixie/.conda/envs/tensorflow1.12/lib/python3.6/site-packages/tensorflow/python/ops/gen_summary_ops.py", line 675, in write_scalar_summary
    writer, step, tag, value, name=name, ctx=_ctx)
  File "/home/fangsixie/.conda/envs/tensorflow1.12/lib/python3.6/site-packages/tensorflow/python/ops/gen_summary_ops.py", line 706, in write_scalar_summary_eager_fallback
    attrs=_attrs, ctx=_ctx, name=name)
  File "/home/fangsixie/.conda/envs/tensorflow1.12/lib/python3.6/site-packages/tensorflow/python/eager/execute.py", line 66, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.NotFoundError: Resource localhost/logdir:logs/000//N10tensorflow22SummaryWriterInterfaceE does not exist. [Op:WriteScalarSummary] name: epoch_loss/

**Comment by fsx950223** [comment]
fixed
