### ISSUE TITLE
[TF2.0][FR] Skip TFRecord files with 'DataLossError: corrupted record at'

### ISSUE THREAD

**Issue by meyerjo** [tensorflow/tensorflow#26991]
**System information**
- TensorFlow version (you are using): 2.0.0-dev20190319

**Describe the feature and the current behavior/state.**

In this version of TF and prior versions, TFRecord files get corrupted or are detected as corrupt spontaneously during training. This is a problem already heavily discussed in e.g https://github.com/tensorflow/tensorflow/issues/13463 . Unfortunately, no one came up with an solution or a script triggering the problem, yet. This makes debugging what causes the files to change(?) during training quite hard.

Thus, it would be nice to be able to indicate to Tensorflow that such files should be ignored and only a warning is printed instead of canceling the whole training process. 

An exemplary error message:
```cmd
Traceback (most recent call last):
[...]
    obj = distributed_train(summary_writer)
  File "/home/meyerjo/code/kaggle/nuclei-detection-tf2/nucleidetection/train.py", line 297, in distributed_train
    lambda x: train_step(x, summary_writer), train_iterator)
  File "/home/meyerjo/code/testfield-tf-nightly/tf-nightly/lib/python3.5/site-packages/tensorflow/python/distribute/distribute_lib.py", line 470, in experimental_run
    args = (input_iterator.get_next(),) if input_iterator is not None else ()
  File "/home/meyerjo/code/testfield-tf-nightly/tf-nightly/lib/python3.5/site-packages/tensorflow/python/distribute/input_lib.py", line 145, in get_next
    self._iterators[i].get_next_as_list(new_name))
  File "/home/meyerjo/code/testfield-tf-nightly/tf-nightly/lib/python3.5/site-packages/tensorflow/python/distribute/input_lib.py", line 415, in get_next_as_list
    data_list = self._iterator.get_next_as_optional()
  File "/home/meyerjo/code/testfield-tf-nightly/tf-nightly/lib/python3.5/site-packages/tensorflow/python/data/ops/multi_device_iterator_ops.py", line 311, in get_next_as_optional
    self._device_iterators[i]))
  File "/home/meyerjo/code/testfield-tf-nightly/tf-nightly/lib/python3.5/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 689, in get_next_as_optional
    output_shapes=iterator._element_structure._flat_shapes),
  File "/home/meyerjo/code/testfield-tf-nightly/tf-nightly/lib/python3.5/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 1858, in iterator_get_next_as_optional
    _six.raise_from(_core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.DataLossError: corrupted record at 852968336
	 [[{{node MultiDeviceIteratorGetNextFromShard}}]]
	 [[RemoteCall]] [Op:IteratorGetNextAsOptional]

```

**Comment by mrry** [comment]
Reassigning to @jsimsa for triage (but maybe `tf.data.experimental.ignore_errors()` would solve the problem here?).

**Comment by jsimsa** [comment]
@meyerjo as per @mrry's suggestion, have you tried using [ignore_errors](https://www.tensorflow.org/api_docs/python/tf/data/experimental/ignore_errors)?

**Comment by meyerjo** [comment]
I think that has went under my radar. As in the other issues discussed it seems to work around the error message. Thanks!

May I leave this open, as TFRecord Files still get spontaneously corrupted during training? As training should be readonly regarding those files, this seems to be a bug.

**Comment by jsimsa** [comment]
@meyerjo thank you for your response. Unless you can provide us with an example that can be used to reproduce this issue, there is little value in keeping this issue open (as no further action will be taken).

**Comment by meyerjo** [comment]
Ok. Then I will close the issue
