### ISSUE TITLE
Cannot use load_model for a model with a DenseFeatures layer

### ISSUE THREAD

**Issue by janwendt** [tensorflow/tensorflow#27008]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no (https://www.tensorflow.org/alpha/tutorials/keras/feature_columns + model.save + load_model)
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: no
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0.0-alpha0
- Python version: 3.6.8
- CUDA/cuDNN version: 10.0.130/7.3.1
- GPU model and memory: GTX 1060 6GB

**Describe the current behavior**
loading a saved .h5 model which includes a DenseFeatures Layer fails:
`ValueError: Unknown layer: DenseFeatures`

**Describe the expected behavior**
model is loading

**Code to reproduce the issue**
```
import pandas as pd

# pip install -q tensorflow==2.0.0-alpha0
import tensorflow as tf
from tensorflow import feature_column
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split

URL = 'https://storage.googleapis.com/applied-dl/heart.csv'
dataframe = pd.read_csv(URL)
train, test = train_test_split(dataframe, test_size=0.2)
train, val = train_test_split(train, test_size=0.2)

# A utility method to create a tf.data dataset from a Pandas Dataframe
def df_to_dataset(dataframe, shuffle=True, batch_size=32):
  dataframe = dataframe.copy()
  labels = dataframe.pop('target')
  ds = tf.data.Dataset.from_tensor_slices((dict(dataframe), labels))
  if shuffle:
    ds = ds.shuffle(buffer_size=len(dataframe))
  ds = ds.batch(batch_size)
  return ds

feature_columns = []

# numeric cols
for header in ['age', 'trestbps', 'chol', 'thalach', 'oldpeak', 'slope', 'ca']:
  feature_columns.append(feature_column.numeric_column(header))

feature_layer = tf.keras.layers.DenseFeatures(feature_columns)

batch_size = 32
train_ds = df_to_dataset(train, batch_size=batch_size)
val_ds = df_to_dataset(val, shuffle=False, batch_size=batch_size)
test_ds = df_to_dataset(test, shuffle=False, batch_size=batch_size)

model = tf.keras.Sequential([
  feature_layer,
  layers.Dense(128, activation='relu'),
  layers.Dense(128, activation='relu'),
  layers.Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam',
              loss='binary_crossentropy')

model.fit(train_ds, 
          validation_data=val_ds, 
          epochs=5)


model.save('my_model.h5')
from tensorflow import keras
new_model = keras.models.load_model('my_model.h5')
```

**Other info / logs**
```
Traceback (most recent call last):
  File "error.py", line 67, in <module>
    new_model = keras.models.load_model('my_model.h5')
  File "C:\Anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\keras\saving\hdf5_format.py", line 215, in load_model
    custom_objects=custom_objects)
  File "C:\Anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\keras\saving\model_config.py", line 55, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "C:\Anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\keras\layers\serialization.py", line 95, in deserialize
    printable_module_name='layer')
  File "C:\Anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\keras\utils\generic_utils.py", line 192, in deserialize_keras_object
    list(custom_objects.items())))
  File "C:\Anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\keras\engine\sequential.py", line 351, in from_config
    custom_objects=custom_objects)
  File "C:\Anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\keras\layers\serialization.py", line 95, in deserialize
    printable_module_name='layer')
  File "C:\Anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\keras\utils\generic_utils.py", line 181, in deserialize_keras_object
    config, module_objects, custom_objects, printable_module_name)
  File "C:\Anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\keras\utils\generic_utils.py", line 166, in class_and_config_for_serialized_keras_object
    raise ValueError('Unknown ' + printable_module_name + ': ' + class_name)
ValueError: Unknown layer: DenseFeatures
```

**Comment by alimaan2935** [comment]
I have a similar problem. I am trying to load tensorflow_hub module into tf.keras model.
`
model = tf.keras.models.Sequential()
model.add(hub.KerasLayer(
			    "https://tfhub.dev/google/tf2-preview/nnlm-en-dim128/1",
				trainable=True,
			    output_shape=[128],  # Outputs a tensor with shape [batch_size, 20].
			    input_shape=[],     # Expects a tensor of shape [batch_size] as input.
			    dtype=tf.string))
`
It saves fine but when loading it gives this error:
`
Traceback (most recent call last):
  File "/mnt/dev_files/FeatureExtractor/training/text_class_training/nlp_training.py", line 103, in <module>
    train_nlp(config, data)
  File "/mnt/dev_files/FeatureExtractor/training/text_class_training/nlp_training.py", line 84, in train_nlp
    new_model = tf.keras.models.load_model('training/text_class_training/test1.h5')
  File "/home/ali1234/anaconda3/envs/tf2.0/lib/python3.6/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 215, in load_model
    custom_objects=custom_objects)
  File "/home/ali1234/anaconda3/envs/tf2.0/lib/python3.6/site-packages/tensorflow/python/keras/saving/model_config.py", line 55, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/home/ali1234/anaconda3/envs/tf2.0/lib/python3.6/site-packages/tensorflow/python/keras/layers/serialization.py", line 95, in deserialize
    printable_module_name='layer')
  File "/home/ali1234/anaconda3/envs/tf2.0/lib/python3.6/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 192, in deserialize_keras_object
    list(custom_objects.items())))
  File "/home/ali1234/anaconda3/envs/tf2.0/lib/python3.6/site-packages/tensorflow/python/keras/engine/sequential.py", line 351, in from_config
    custom_objects=custom_objects)
  File "/home/ali1234/anaconda3/envs/tf2.0/lib/python3.6/site-packages/tensorflow/python/keras/layers/serialization.py", line 95, in deserialize
    printable_module_name='layer')
  File "/home/ali1234/anaconda3/envs/tf2.0/lib/python3.6/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 181, in deserialize_keras_object
    config, module_objects, custom_objects, printable_module_name)
  File "/home/ali1234/anaconda3/envs/tf2.0/lib/python3.6/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 166, in class_and_config_for_serialized_keras_object
    raise ValueError('Unknown ' + printable_module_name + ': ' + class_name)
ValueError: Unknown layer: KerasLayer
`

Any help here would be really appreciated.

**Comment by ymodak** [comment]
duplicate #26835

**Comment by Mark-DelGrande** [comment]
I am having the same problem too. When I am trying to load my model with a feature layer it gives me:
ValueError: Unknown layer: DenseFeatures

**Comment by Jie-Yuan** [comment]
same problem

**Comment by Jie-Yuan** [comment]
ValueError: Unknown layer: DenseFeatures

**Comment by gogasca** [comment]
Same problem

**Comment by JonathanLehner** [comment]
same problem

**Comment by muzixizhu** [comment]
is there any solutions now ? I am also facing the same problem

**Comment by jswortz** [comment]
Did you try to load the custom class / code for `DenseFeatures` into the argument `custom_objects` for `load_model`? That has gotten me further...

Here's an example:

`BERT_model = load_model('bert_model.h5', custom_objects={'Bert': BertCustomClass})`

**Comment by caldudleya** [comment]
same problem
