### ISSUE TITLE
Why this error on tensorflow 1.13.1 with python 2.7 : ImportError: No module named model_utils

### ISSUE THREAD

**Issue by ChaoYue0307** [tensorflow/tensorflow#27079]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 1.13.1
- Python version: 2.7
- GCC/Compiler version (if compiling from source): 7.0
- CUDA/cuDNN version: 10.1
- GPU model and memory: RTX 2080Ti 11G

You can collect some of this information using our environment capture [script]
**Describe the current behavior**
Just got the import error
**Describe the expected behavior**
Should be able to run the code smoothly
**Other info / logs**
Traceback (most recent call last):
  File "official_tensorflow_phased_lstm.py", line 6, in <module>
    import tensorflow.contrib.slim as slim
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/__init__.py", line 40, in <module>
    from tensorflow.contrib import distribute
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/distribute/__init__.py", line 33, in <module>
    from tensorflow.contrib.distribute.python.tpu_strategy import TPUStrategy
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/distribute/python/tpu_strategy.py", line 27, in <module>
    from tensorflow.contrib.tpu.python.ops import tpu_ops
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/__init__.py", line 73, in <module>
    from tensorflow.contrib.tpu.python.tpu.keras_support import tpu_model as keras_to_tpu_model
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/keras_support.py", line 62, in <module>
    from tensorflow.contrib.tpu.python.tpu import tpu
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu.py", line 24, in <module>
    from tensorflow.contrib.compiler import xla
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/compiler/xla.py", line 28, in <module>
    from tensorflow.python.estimator import model_fn as model_fn_lib
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/__init__.py", line 26, in <module>
    from tensorflow_estimator.python import estimator
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_estimator/__init__.py", line 8, in <module>
    from tensorflow_estimator._api.v1 import estimator
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_estimator/_api/v1/estimator/__init__.py", line 8, in <module>
    from tensorflow_estimator._api.v1.estimator import experimental
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_estimator/_api/v1/estimator/experimental/__init__.py", line 8, in <module>
    from tensorflow_estimator.python.estimator.canned.dnn import dnn_logit_fn_builder
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_estimator/python/estimator/__init__.py", line 25, in <module>
    import tensorflow_estimator.python.estimator.estimator_lib
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_estimator/python/estimator/estimator_lib.py", line 22, in <module>
    from tensorflow_estimator.python.estimator.canned.baseline import BaselineClassifier
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_estimator/python/estimator/canned/baseline.py", line 64, in <module>
    from tensorflow_estimator.python.estimator import estimator
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 66, in <module>
    from tensorflow_estimator.python.estimator import model_fn as model_fn_lib
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_estimator/python/estimator/model_fn.py", line 36, in <module>
    from tensorflow_estimator.python.estimator.export import export_lib
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_estimator/python/estimator/export/export_lib.py", line 25, in <module>
    from tensorflow.python.saved_model.model_utils import build_all_signature_defs
ImportError: No module named model_utils

**Comment by matlust** [comment]
Same problem here..

**Comment by AxelWolf** [comment]
Same here with TF 1.13.1. Installed object_detection following https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md. Error shows when running model_builder_test.py.

**Comment by vladr11** [comment]
Same problem here with TF 1.13.1, Linux Ubuntu 18.04, Python 3.6 CUDA 10.0.

**Comment by derekmetcalf** [comment]
Same problem. TF 1.13.1, SwagArch GNU/Linux 4.20.12
Comes from the tensorflow_probability import

**Comment by skiler07** [comment]
Same here, when running Apache Beam pipelines:

TB:

```
Traceback (most recent call last):
  File "watson_retail_rnn.py", line 18, in <module>
    import tensorflow_transform as tft
  File "/anaconda3/envs/beam/lib/python2.7/site-packages/tensorflow_transform/__init__.py", line 19, in <module>
    from tensorflow_transform.analyzers import *
  File "/anaconda3/envs/beam/lib/python2.7/site-packages/tensorflow_transform/analyzers.py", line 39, in <module>
    from tensorflow_transform import tf_utils
  File "/anaconda3/envs/beam/lib/python2.7/site-packages/tensorflow_transform/tf_utils.py", line 24, in <module>
    from tensorflow.contrib.proto.python.ops import encode_proto_op
  File "/anaconda3/envs/beam/lib/python2.7/site-packages/tensorflow/contrib/__init__.py", line 40, in <module>
    from tensorflow.contrib import distribute
  File "/anaconda3/envs/beam/lib/python2.7/site-packages/tensorflow/contrib/distribute/__init__.py", line 33, in <module>
    from tensorflow.contrib.distribute.python.tpu_strategy import TPUStrategy
  File "/anaconda3/envs/beam/lib/python2.7/site-packages/tensorflow/contrib/distribute/python/tpu_strategy.py", line 27, in <module>
    from tensorflow.contrib.tpu.python.ops import tpu_ops
  File "/anaconda3/envs/beam/lib/python2.7/site-packages/tensorflow/contrib/tpu/__init__.py", line 73, in <module>
    from tensorflow.contrib.tpu.python.tpu.keras_support import tpu_model as keras_to_tpu_model
  File "/anaconda3/envs/beam/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/keras_support.py", line 62, in <module>
    from tensorflow.contrib.tpu.python.tpu import tpu
  File "/anaconda3/envs/beam/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/tpu.py", line 24, in <module>
    from tensorflow.contrib.compiler import xla
  File "/anaconda3/envs/beam/lib/python2.7/site-packages/tensorflow/contrib/compiler/xla.py", line 28, in <module>
    from tensorflow.python.estimator import model_fn as model_fn_lib
  File "/anaconda3/envs/beam/lib/python2.7/site-packages/tensorflow/python/estimator/__init__.py", line 26, in <module>
    from tensorflow_estimator.python import estimator
  File "/anaconda3/envs/beam/lib/python2.7/site-packages/tensorflow_estimator/__init__.py", line 8, in <module>
    from tensorflow_estimator._api.v1 import estimator
  File "/anaconda3/envs/beam/lib/python2.7/site-packages/tensorflow_estimator/_api/v1/estimator/__init__.py", line 8, in <module>
    from tensorflow_estimator._api.v1.estimator import experimental
  File "/anaconda3/envs/beam/lib/python2.7/site-packages/tensorflow_estimator/_api/v1/estimator/experimental/__init__.py", line 8, in <module>
    from tensorflow_estimator.python.estimator.canned.dnn import dnn_logit_fn_builder
  File "/anaconda3/envs/beam/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/__init__.py", line 25, in <module>
    import tensorflow_estimator.python.estimator.estimator_lib
  File "/anaconda3/envs/beam/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/estimator_lib.py", line 22, in <module>
    from tensorflow_estimator.python.estimator.canned.baseline import BaselineClassifier
  File "/anaconda3/envs/beam/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/canned/baseline.py", line 64, in <module>
    from tensorflow_estimator.python.estimator import estimator
  File "/anaconda3/envs/beam/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 66, in <module>
    from tensorflow_estimator.python.estimator import model_fn as model_fn_lib
  File "/anaconda3/envs/beam/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/model_fn.py", line 36, in <module>
    from tensorflow_estimator.python.estimator.export import export_lib
  File "/anaconda3/envs/beam/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/export/export_lib.py", line 25, in <module>
    from tensorflow.python.saved_model.model_utils import build_all_signature_defs
ImportError: No module named model_utils

```

**Comment by mastedm** [comment]
The same with Python 3.7.1:

```
In [1]: import tensorflow as tf                                                                                                          

In [2]: tf.__version__                                                                                                                   
Out[2]: '1.13.1'

In [3]: tf.contrib.tensor_forest.python.tensor_forest.ForestHParams                                                                      
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-ff9aa14a958c> in <module>
----> 1 tf.contrib.tensor_forest.python.tensor_forest.ForestHParams

~/.local/lib/python3.7/site-packages/tensorflow/python/util/lazy_loader.py in __getattr__(self, item)
     59 
     60   def __getattr__(self, item):
---> 61     module = self._load()
     62     return getattr(module, item)
     63 

~/.local/lib/python3.7/site-packages/tensorflow/python/util/lazy_loader.py in _load(self)
     42     """Load the module and insert it into the parent's globals."""
     43     # Import the target module and insert it into the parent's namespace
---> 44     module = importlib.import_module(self.__name__)
     45     self._parent_module_globals[self._local_name] = module
     46 

/opt/anaconda3/lib/python3.7/importlib/__init__.py in import_module(name, package)
    125                 break
    126             level += 1
--> 127     return _bootstrap._gcd_import(name[level:], package, level)
    128 
    129 

/opt/anaconda3/lib/python3.7/importlib/_bootstrap.py in _gcd_import(name, package, level)

/opt/anaconda3/lib/python3.7/importlib/_bootstrap.py in _find_and_load(name, import_)

/opt/anaconda3/lib/python3.7/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

/opt/anaconda3/lib/python3.7/importlib/_bootstrap.py in _load_unlocked(spec)

/opt/anaconda3/lib/python3.7/importlib/_bootstrap_external.py in exec_module(self, module)

/opt/anaconda3/lib/python3.7/importlib/_bootstrap.py in _call_with_frames_removed(f, *args, **kwds)

~/.local/lib/python3.7/site-packages/tensorflow/contrib/__init__.py in <module>
     38 from tensorflow.contrib import data
     39 from tensorflow.contrib import deprecated
---> 40 from tensorflow.contrib import distribute
     41 from tensorflow.contrib import distributions
     42 from tensorflow.contrib import estimator

~/.local/lib/python3.7/site-packages/tensorflow/contrib/distribute/__init__.py in <module>
     31 from tensorflow.contrib.distribute.python.parameter_server_strategy import ParameterServerStrategy
     32 from tensorflow.contrib.distribute.python.step_fn import *
---> 33 from tensorflow.contrib.distribute.python.tpu_strategy import TPUStrategy
     34 from tensorflow.python.distribute.cross_device_ops import *
     35 from tensorflow.python.distribute.distribute_config import DistributeConfig

~/.local/lib/python3.7/site-packages/tensorflow/contrib/distribute/python/tpu_strategy.py in <module>
     25 import functools
     26 
---> 27 from tensorflow.contrib.tpu.python.ops import tpu_ops
     28 from tensorflow.contrib.tpu.python.tpu import tpu
     29 from tensorflow.contrib.tpu.python.tpu import tpu_system_metadata as tpu_system_metadata_lib

~/.local/lib/python3.7/site-packages/tensorflow/contrib/tpu/__init__.py in <module>
     71 from tensorflow.contrib.tpu.python.tpu.bfloat16 import *
     72 from tensorflow.contrib.tpu.python.tpu.device_assignment import *
---> 73 from tensorflow.contrib.tpu.python.tpu.keras_support import tpu_model as keras_to_tpu_model
     74 from tensorflow.contrib.tpu.python.tpu.keras_support import TPUDistributionStrategy
     75 from tensorflow.contrib.tpu.python.tpu.topology import *

~/.local/lib/python3.7/site-packages/tensorflow/contrib/tpu/python/tpu/keras_support.py in <module>
     60 from tensorflow.contrib.tpu.python.ops import tpu_ops
     61 from tensorflow.contrib.tpu.python.tpu import keras_tpu_variables
---> 62 from tensorflow.contrib.tpu.python.tpu import tpu
     63 from tensorflow.contrib.tpu.python.tpu import tpu_function
     64 from tensorflow.contrib.tpu.python.tpu import tpu_optimizer

~/.local/lib/python3.7/site-packages/tensorflow/contrib/tpu/python/tpu/tpu.py in <module>
     22 from six.moves import xrange  # pylint: disable=redefined-builtin
     23 
---> 24 from tensorflow.contrib.compiler import xla
     25 from tensorflow.contrib.framework.python.framework import experimental
     26 from tensorflow.contrib.tpu.python.ops import tpu_ops

~/.local/lib/python3.7/site-packages/tensorflow/contrib/compiler/xla.py in <module>
     26 from tensorflow.compiler.jit.ops import xla_ops_grad  # pylint: disable=unused-import
     27 from tensorflow.core.framework import attr_value_pb2
---> 28 from tensorflow.python.estimator import model_fn as model_fn_lib
     29 from tensorflow.python.framework import ops
     30 from tensorflow.python.ops import array_ops

~/.local/lib/python3.7/site-packages/tensorflow/python/estimator/__init__.py in <module>
     24 from __future__ import print_function
     25 
---> 26 from tensorflow_estimator.python import estimator
     27 
     28 # Include attrs that start with single underscore.

~/.local/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/__init__.py in <module>
     23 from __future__ import print_function
     24 
---> 25 import tensorflow_estimator.python.estimator.estimator_lib

~/.local/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator_lib.py in <module>
     20 
     21 # pylint: disable=unused-import,line-too-long,wildcard-import
---> 22 from tensorflow_estimator.python.estimator.canned.baseline import BaselineClassifier
     23 from tensorflow_estimator.python.estimator.canned.baseline import BaselineEstimator
     24 from tensorflow_estimator.python.estimator.canned.baseline import BaselineRegressor

~/.local/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/canned/baseline.py in <module>
     62 from tensorflow.python.training import training_util
     63 from tensorflow.python.util.tf_export import estimator_export
---> 64 from tensorflow_estimator.python.estimator import estimator
     65 from tensorflow_estimator.python.estimator.canned import head as head_lib
     66 from tensorflow_estimator.python.estimator.canned import optimizers

~/.local/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py in <module>
     64 from tensorflow.python.util import nest
     65 from tensorflow.python.util.tf_export import estimator_export
---> 66 from tensorflow_estimator.python.estimator import model_fn as model_fn_lib
     67 from tensorflow_estimator.python.estimator import run_config
     68 from tensorflow_estimator.python.estimator import util as estimator_util

~/.local/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/model_fn.py in <module>
     34 from tensorflow.python.util import nest
     35 from tensorflow.python.util.tf_export import estimator_export
---> 36 from tensorflow_estimator.python.estimator.export import export_lib
     37 from tensorflow_estimator.python.estimator.mode_keys import ModeKeys
     38 

~/.local/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/export/export_lib.py in <module>
     23 
     24 # pylint: disable=unused-import,line-too-long, wildcard-import
---> 25 from tensorflow.python.saved_model.model_utils import build_all_signature_defs
     26 from tensorflow.python.saved_model.model_utils import export_outputs_for_mode
     27 from tensorflow.python.saved_model.model_utils import EXPORT_TAG_MAP

ModuleNotFoundError: No module named 'tensorflow.python.saved_model.model_utils'
```

**Comment by LucasSloan** [comment]
Same problem here with TF 1.13.1, Windows 10, Python 3.6 CUDA 10.0.

**Comment by AxelWolf** [comment]
This setup works for me (Ubuntu 16.04):

Python 2.7.12
Cuda 10.0 (Driver 418.56)
cuDNN 7.4.2
tensorflow-gpu 13.0.0rc2

object_detection/builders/model_builder_test.py passes (with a warning about contrib being removed in TF 2.0), quick start tutorial also works.

**Comment by ymodak** [comment]
@ChaoYue0307  @mastedm I am using Python 3.6.5 and TF 1.13.1 (cpu) I was able to import following modules successfully.
```python
import tensorflow.contrib.slim as slim
tf.contrib.tensor_forest.python.tensor_forest.ForestHParams
```
Can you please try executing your code in virtual env?

**Comment by patrick-ucr** [comment]
Same problem with TF 1.13.1 and master branch of "tensorflow/models"

**Comment by LucasSloan** [comment]
I was able to resolve the issue by blowing away all of my pip packages and reinstalling.

**Comment by patrick-ucr** [comment]
@LucasSloan How did you do that? Here is my output of pip freeze --local
Keras-Applications==1.0.6
Keras-Preprocessing==1.0.5
mock==2.0.0
numpy==1.16.2
object-detection==0.1
pbr==5.1.3
tb-nightly==1.13.0a20190225
tensorboard==1.13.1
tensorflow==1.13.1
tensorflow-estimator==1.13.0
tf-estimator-nightly==1.14.0.dev2019033001
tf-nightly==1.13.1

**Comment by LucasSloan** [comment]
@patrick-ucr 

I just got the list of all my installed packages `pip list`, and edited together a command `pip uninstall <ALL MY PACKAGES>`.

**Comment by patrick-ucr** [comment]
@LucasSloan I just installed Tensorflow from source, so "pip uninstall" would remove it and prevent other functions to work? I don't think this is an option for me.

**Comment by dsblank** [comment]
I was able to solve this under Python 3.6 on Linux with:

```
pip uninstall tensorflow_estimator
pip install tensorflow_estimator
```

**Comment by vladr11** [comment]
I was using pipenv as environment. I recreated the environment using virtualenv and pip and it works now.

**Comment by OuHangKresnik** [comment]
> I was able to solve this under Python 3.6 on Linux with:
> 
> ```
> pip uninstall tensorflow_estimator
> pip install tensorflow_estimator
> ```

So did I. This solves problem

**Comment by jasperchih** [comment]
> I was able to solve this under Python 3.6 on Linux with:
> 
> ```
> pip uninstall tensorflow_estimator
> pip install tensorflow_estimator
> ```

Yes, it works in my environment. thank you.

**Comment by ChaoYue0307** [comment]
> I was able to solve this under Python 3.6 on Linux with:
> 
> ```
> pip uninstall tensorflow_estimator
> pip install tensorflow_estimator
> ```

Thanks, solved for python 2.7 also

**Comment by ymodak** [comment]
Closing this issue since it is resolved. Feel free to reopen if have additional problems. Thanks!

**Comment by xavysp** [comment]
> I was able to solve this under Python 3.6 on Linux with:
> 
> ```
> pip uninstall tensorflow_estimator
> pip install tensorflow_estimator
> ```

This solved too in python 3.7.3
thanks

**Comment by punkproger** [comment]
> I was able to solve this under Python 3.6 on Linux with:
> 
> ```
> pip uninstall tensorflow_estimator
> pip install tensorflow_estimator
> ```

Doesn't help:(
When I run:
python3 -c "import tensorflow as tf; print(tf.contrib.eager.num_gpus())"

OS Platform and Distribution: Linux Ubuntu 16.04
TensorFlow installed from : pip3
TensorFlow version : 1.13.1
Python version: 3.5.2
CUDA/cuDNN version: 10.0
GPU model and memory: GTX 1080Ti 11G

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/lazy_loader.py", line 61, in __getattr__
    module = self._load()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/lazy_loader.py", line 44, in _load
    module = importlib.import_module(self.__name__)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/__init__.py", line 40, in <module>
    from tensorflow.contrib import distribute
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/distribute/__init__.py", line 33, in <module>
    from tensorflow.contrib.distribute.python.tpu_strategy import TPUStrategy
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/distribute/python/tpu_strategy.py", line 27, in <module>
    from tensorflow.contrib.tpu.python.ops import tpu_ops
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/tpu/__init__.py", line 73, in <module>
    from tensorflow.contrib.tpu.python.tpu.keras_support import tpu_model as keras_to_tpu_model
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/tpu/python/tpu/keras_support.py", line 62, in <module>
    from tensorflow.contrib.tpu.python.tpu import tpu
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu.py", line 24, in <module>
    from tensorflow.contrib.compiler import xla
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/compiler/xla.py", line 28, in <module>
    from tensorflow.python.estimator import model_fn as model_fn_lib
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/__init__.py", line 26, in <module>
    from tensorflow_estimator.python import estimator
  File "/home/punkproger/.local/lib/python3.5/site-packages/tensorflow_estimator/python/estimator/__init__.py", line 25, in <module>
    import tensorflow_estimator.python.estimator.estimator_lib
  File "/home/punkproger/.local/lib/python3.5/site-packages/tensorflow_estimator/python/estimator/estimator_lib.py", line 22, in <module>
    from tensorflow_estimator.python.estimator.canned.baseline import BaselineClassifier
  File "/home/punkproger/.local/lib/python3.5/site-packages/tensorflow_estimator/python/estimator/canned/baseline.py", line 64, in <module>
    from tensorflow_estimator.python.estimator import estimator
  File "/home/punkproger/.local/lib/python3.5/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 66, in <module>
    from tensorflow_estimator.python.estimator import model_fn as model_fn_lib
  File "/home/punkproger/.local/lib/python3.5/site-packages/tensorflow_estimator/python/estimator/model_fn.py", line 36, in <module>
    from tensorflow_estimator.python.estimator.export import export_lib
  File "/home/punkproger/.local/lib/python3.5/site-packages/tensorflow_estimator/python/estimator/export/export_lib.py", line 25, in <module>
    from tensorflow.python.saved_model.model_utils import build_all_signature_defs
ImportError: No module named 'tensorflow.python.saved_model.model_utils'

**Comment by wenredo** [comment]
> I was able to solve this under Python 3.6 on Linux with:
> 
> ```
> pip uninstall tensorflow_estimator
> pip install tensorflow_estimator
> ```
works also for me, dos anyone have any explanation to this?

**Comment by mayorovp** [comment]
@ymodak why you called this issue "resolved"? I see only workaround for this bug.

**Comment by lakshitha1629** [comment]
how to fix 


Use standard file APIs to check for files with this prefix.
WARNING:tensorflow:From C:\Users\HP\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\tools\freeze_graph.py:232: convert_variables_to_constants (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.compat.v1.graph_util.convert_variables_to_constants
WARNING:tensorflow:From C:\Users\HP\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\graph_util_impl.py:245: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.compat.v1.graph_util.extract_sub_graph
Traceback (most recent call last):
  File "export_inference_graph.py", line 156, in <module>
    tf.app.run()
  File "C:\Users\HP\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "export_inference_graph.py", line 152, in main
    write_inference_graph=FLAGS.write_inference_graph)
  File "C:\Users\HP\Desktop\RE\models\research\object_detection\exporter.py", line 465, in export_inference_graph
    write_inference_graph=write_inference_graph)
  File "C:\Users\HP\Desktop\RE\models\research\object_detection\exporter.py", line 421, in _export_inference_graph
    placeholder_tensor, outputs)
  File "C:\Users\HP\Desktop\RE\models\research\object_detection\exporter.py", line 264, in write_saved_model
    builder = tf.saved_model.builder.SavedModelBuilder(saved_model_path)
  File "C:\Users\HP\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\saved_model\builder_impl.py", line 425, in __init__
    super(SavedModelBuilder, self).__init__(export_dir=export_dir)
  File "C:\Users\HP\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\saved_model\builder_impl.py", line 100, in __init__
    "directory: %s" % export_dir)
AssertionError: Export directory already exists. Please specify a different export directory: inference_graph\saved_model

**Comment by wubin-ericsson** [comment]
solve with solution: 

```
> pip uninstall tensorflow_estimator
> pip install tensorflow_estimator
```

thanks a lot.

**Comment by sunn-e** [comment]
> 
> 
> I was able to solve this under Python 3.6 on Linux with:
> 
> ```
> pip uninstall tensorflow_estimator
> pip install tensorflow_estimator
> ```
Thank you so much. For those who missed this reply and scrolled past to last.

**Comment by SumNeuron** [comment]
doesn't work with conda

**Comment by sheck02** [comment]
> > I was able to solve this under Python 3.6 on Linux with:
> > ```
> > pip uninstall tensorflow_estimator
> > pip install tensorflow_estimator
> > ```
> 
> Thanks, solved for python 2.7 also

do you know how to do this for windows ?

**Comment by handongyexingren** [comment]
> I was able to solve this under Python 3.6 on Linux with:
> 
> ```
> pip uninstall tensorflow_estimator
> pip install tensorflow_estimator
> ```

I reinstalled, But again occur this error "cannot import name 'monitoring'
" ubuntu 18.04.1
python 3.6.8
tensorflow 1.13.1
tensorflow-estimator (1.14.0)

**Comment by kostyabakay** [comment]
If you are using TensorFlow 1.14.0 you should install using this command
`pip install tensorflow-estimator==1.14.0`

**Comment by swetabehera04** [comment]
> I was able to solve this under Python 3.6 on Linux with:
> 
> ```
> pip uninstall tensorflow_estimator
> pip install tensorflow_estimator
> ```

Its not working for me. 

My output : 

(base) sweta python $ pip uninstall tensorflow_estimator
Uninstalling tensorflow-estimator-2.0.1:
  Would remove:
    /home/sweta/anaconda3/lib/python3.7/site-packages/tensorflow_estimator-2.0.1.dist-info/*
    /home/sweta/anaconda3/lib/python3.7/site-packages/tensorflow_estimator/*
Proceed (y/n)? y
  Successfully uninstalled tensorflow-estimator-2.0.1

(base) sweta python $ pip install tensorflow_estimator
Collecting tensorflow_estimator
  Using cached https://files.pythonhosted.org/packages/fc/08/8b927337b7019c374719145d1dceba21a8bb909b93b1ad6f8fb7d22c1ca1/tensorflow_estimator-2.0.1-py2.py3-none-any.whl
Installing collected packages: tensorflow-estimator
Successfully installed tensorflow-estimator-2.0.1

(base) sweta python $ python3 train.py --dataset_name=number_plates --max_number_of_steps=6000
Traceback (most recent call last):
  File "train.py", line 24, in <module>
    from tensorflow.contrib import slim
ModuleNotFoundError: No module named 'tensorflow.contrib'

I am stuck here . :disappointed:

**Comment by vishalpentakota** [comment]
> I was able to solve this under Python 3.6 on Linux with:
> 
> ```
> pip uninstall tensorflow_estimator
> pip install tensorflow_estimator
> ```
Even after doing that, I get the same error!! 
Have a look at it.

rsml@rsml-01:~/darkflow$ pip uninstall tensorflow_estimator
Uninstalling tensorflow-estimator-2.0.0:
  Would remove:
    /home/rsml/anaconda3/envs/darkflow-env/lib/python3.6/site-packages/tensorflow_estimator-2.0.0.dist-info/*
    /home/rsml/anaconda3/envs/darkflow-env/lib/python3.6/site-packages/tensorflow_estimator/*
Proceed (y/n)? y
  Successfully uninstalled tensorflow-estimator-2.0.0
(darkflow-env) rsml@rsml-01:~/darkflow$ pip install tensorflow_estimator
Collecting tensorflow_estimator
  Downloading https://files.pythonhosted.org/packages/fc/08/8b927337b7019c374719145d1dceba21a8bb909b93b1ad6f8fb7d22c1ca1/tensorflow_estimator-2.0.1-py2.py3-none-any.whl (449kB)
     |████████████████████████████████| 450kB 2.5MB/s 
Installing collected packages: tensorflow-estimator
Successfully installed tensorflow-estimator-2.0.1
(darkflow-env) rsml@rsml-01:~/darkflow$ ./flow –model cfg/yolov2.cfg –load bin/yolov2.weights –/home/rsml/tensorflow1/models/research/object_detection/images –gpu 0.9
Traceback (most recent call last):
  File "./flow", line 4, in <module>
    from darkflow.cli import cliHandler
  File "/home/rsml/darkflow/darkflow/cli.py", line 3, in <module>
    from .net.build import TFNet
  File "/home/rsml/darkflow/darkflow/net/build.py", line 5, in <module>
    from .ops import op_create, identity
  File "/home/rsml/darkflow/darkflow/net/ops/__init__.py", line 1, in <module>
    from .simple import *
  File "/home/rsml/darkflow/darkflow/net/ops/simple.py", line 1, in <module>
    import tensorflow.contrib.slim as slim
ModuleNotFoundError: No module named 'tensorflow.contrib'

**Comment by solomonvimal** [comment]
Doesn't work for me! Python 3.6.6, tensorflow 2.0.0, tensorflow-estimator-2.0.1 in Ubuntu 16.04.

**Comment by PranshuTople** [comment]
@solomonvimal  Did you get any solution? I have same problem

**Comment by mihaimaruseac** [comment]
Please open a new issue if you have a problem, filling in the template.

For example, @solomonvimal mentions python 3.6, tf 2.0 whereas issue is about python 2.7, tf 1.13. Please don't conflate the issues, especially after the original is closed.

**Comment by barfi21** [comment]
I have the same problem....

OS Platform and Distribution: windows 10
TensorFlow installed from : pip
TensorFlow version : 1.13.2
Python version: 3.7.4
CUDA/cuDNN version: 10.0
GPU model and memory: GeForce 940MX

Traceback (most recent call last):
  File "C:\Users\abc\Anaconda3\Lib\site-packages\darkflow\Image detection 4.py", line 2, in <module>
    from darkflow.net.build import TFNet
  File "C:\Users\abc\Anaconda3\Lib\site-packages\darkflow\darkflow\net\build.py", line 5, in <module>
    from .ops import op_create, identity
  File "C:\Users\abc\Anaconda3\Lib\site-packages\darkflow\darkflow\net\ops\__init__.py", line 1, in <module>
    from .simple import *
  File "C:\Users\abc\Anaconda3\Lib\site-packages\darkflow\darkflow\net\ops\simple.py", line 1, in <module>
    import tensorflow.contrib.slim as slim
ModuleNotFoundError: No module named 'tensorflow.contrib'
[Finished in 3.8s]
