### ISSUE TITLE
Failed to load the native TensorFlow runtime

### ISSUE THREAD

**Issue by mohamadamirdliwati** [tensorflow/tensorflow#27116]
Exception has occurred: ImportError
Traceback (most recent call last):   File "C:\Users\moham\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>     from tensorflow.python.pywrap_tensorflow_internal import *   File "C:\Users\moham\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>     _pywrap_tensorflow_internal = swig_import_helper()   File "C:\Users\moham\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper     _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)   File "C:\Users\moham\AppData\Local\Programs\Python\Python37\lib\imp.py", line 242, in load_module     return load_dynamic(name, filename, file)   File "C:\Users\moham\AppData\Local\Programs\Python\Python37\lib\imp.py", line 342, in load_dynamic     return _load(spec) ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.   Failed to load the native TensorFlow runtime.  See https://www.tensorflow.org/install/errors  for some common reasons and solutions.  Include the entire stack trace above this error message when asking for help.
  File "D:\Dropbox\Ph.D\AMIR Ph.D\Python\Projects\Test_project\Machine_learning\Deep_learning\TensorFlowDL\First_example_TF.py", line 1, in <module>
    import tensorflow as ts

**Comment by achandraa** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by achandraa** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
