### ISSUE TITLE
Support for histogram_summary in either rnn() or dynamic_rnn()

### ISSUE THREAD

**Issue by zhengwy888** [tensorflow/tensorflow#2714]
Hello,
I am trying to add tf.historgram_summary() in my LSTM cells in order to visualize  the output. But currently
neither rnn() or dynamic_rnn() supports writing out summaries. 
For rnn(), The log indicates the summary tensor are invalid, which seems to due to the dynamic unrolling of the rnn loop.

```
Traceback (most recent call last):
  File "test_dynamic_rnn.py", line 55, in <module>
    summarys = sess.run(thing, feed_dict=feeds)
  File "/home/ezheng/tf_head/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 333, in run
    run_metadata_ptr)
  File "/home/ezheng/tf_head/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 573, in _run
    feed_dict_string, options, run_metadata)
  File "/home/ezheng/tf_head/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 648, in _do_run
    target_list, options, run_metadata)
  File "/home/ezheng/tf_head/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 668, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors.InvalidArgumentError: The tensor returned for dynamic_scope/RNN/cond_2/BasicLSTMCell/HistogramSummary_1:0 was not valid.
```

I am currently constructing rnn() like this

``` python
  outputs, state = tf.nn.rnn(
      cell, inputs, dtype=tf.float32, sequence_length=sequence_length)
```

For dynamic_rnn(), it just hangs when I am trying to obtain summaries with the session.run()
And this is how I am constructing dynamic_rnn()

``` python
  outputs, state = tf.nn.dynamic_rnn(
      cell, inputs=concat_inputs,
      time_major=True, dtype=tf.float32)
```

Wondering if there is plan to support histogram summary with either of these two RNNs. Thanks.

**Comment by girving** [comment]
@ebrevdo: Do summaries work inside control flow?

**Comment by ebrevdo** [comment]
I need to see the code where you add the summaries.

**Comment by zhengwy888** [comment]
in the __call__ function of LSTMCell

```python
  def __call__(self, inputs, state, scope=None):
    """Long short-term memory cell (LSTM)."""
    with vs.variable_scope(scope or self.scope or type(self).__name__):  # "BasicLSTMCell"
      # Parameters of gates are concatenated into one multiply for efficiency.
      c, h = array_ops.split(1, 2, state)
      concat = xnor_linear_tf([inputs, h], 4 * self._num_units, True,
              biasBinarized=False
              )

      # i = input_gate, j = new_input, f = forget_gate, o = output_gate
      i, j, f, o = array_ops.split(1, 4, concat)

      sig_activation = sigmoid
      new_c = tanh(c * sig_activation(f + self._forget_bias) + sig_activation(i) * (j))
      new_h = (new_c) * sig_activation(o)
      if self._is_training:
          timestep = get_timestep()
          tf.histogram_summary("i/%03d" % (timestep), i)
          tf.histogram_summary("j/%03d" % (timestep), j)
          tf.histogram_summary("f/%03d" % (timestep), f)
          tf.histogram_summary("o/%03d" % (timestep), o)
          tf.histogram_summary("c/%03d" % (timestep), c)
          tf.histogram_summary("h/%03d" % (timestep), h)
          tf.histogram_summary("x/%03d" % (timestep), inputs)

      return new_h, array_ops.concat(1, [new_c, new_h])

```

**Comment by ebrevdo** [comment]
can you paste more of the error trace?  need more context.

**Comment by zhengwy888** [comment]
Unfortunately there is not much output. I have added a minimal script to reproduce the hanging on dynamic_rnn and the exception on rnn().

```python
import numpy as np
import collections
import tensorflow as tf
from tensorflow.python.ops import variable_scope as vs
from tensorflow.python.ops.math_ops import sigmoid
from tensorflow.python.ops.math_ops import tanh
from tensorflow.python.ops import array_ops
from tensorflow.python.ops import init_ops

_LSTMStateTuple = collections.namedtuple("LSTMStateTuple", ("c", "h"))
class LSTMStateTuple(_LSTMStateTuple):
  """Tuple used by LSTM Cells for `state_size`, `zero_state`, and output state.
  Stores two elements: `(c, h)`, in that order.
  Only used when `state_is_tuple=True`.
  """
  __slots__ = ()

class BasicLSTMCell(tf.nn.rnn_cell.RNNCell):
  """Basic LSTM recurrent network cell.
  The implementation is based on: http://arxiv.org/abs/1409.2329.
  We add forget_bias (default: 1) to the biases of the forget gate in order to
  reduce the scale of forgetting in the beginning of the training.
  It does not allow cell clipping, a projection layer, and does not
  use peep-hole connections: it is the basic baseline.
  For advanced models, please use the full LSTMCell that follows.
  """

  def __init__(self, num_units, forget_bias=1.0, input_size=None, is_training=True,
               state_is_tuple=False, activation=tanh, add_summary=True):
    """Initialize the basic LSTM cell.
    Args:
      num_units: int, The number of units in the LSTM cell.
      forget_bias: float, The bias added to forget gates (see above).
      input_size: Deprecated and unused.
      state_is_tuple: If True, accepted and returned states are 2-tuples of
        the `c_state` and `m_state`.  By default (False), they are concatenated
        along the column axis.  This default behavior will soon be deprecated.
      activation: Activation function of the inner states.
    """
    if not state_is_tuple:
      tf.logging.warn(
          "%s: Using a concatenated state is slower and will soon be "
          "deprecated.  Use state_is_tuple=True." % self)
    if input_size is not None:
      tf.logging.warn("%s: The input_size parameter is deprecated." % self)
    self._input_size = num_units if input_size is None else input_size
    self._num_units = num_units
    self._forget_bias = forget_bias
    self._state_is_tuple = state_is_tuple
    self._activation = activation
    self._is_training = is_training
    self._add_summary = add_summary

  @property
  def input_size(self):
    return self._input_size
  @property
  def state_size(self):
    return (LSTMStateTuple(self._num_units, self._num_units)
            if self._state_is_tuple else 2 * self._num_units)

  @property
  def output_size(self):
    return self._num_units

  def __call__(self, inputs, state, scope=None):
    """Long short-term memory cell (LSTM)."""
    with vs.variable_scope(scope or type(self).__name__) as sc:  # "BasicLSTMCell"
      print("called with timestep" + sc.name + " reuse " + str(sc.reuse))
      # Parameters of gates are concatenated into one multiply for efficiency.
      if self._state_is_tuple:
        c, h = state
      else:
        c, h = array_ops.split(1, 2, state)
      concat = tf.nn.rnn_cell._linear([inputs, h], 4 * self._num_units, True)

      # i = input_gate, j = new_input, f = forget_gate, o = output_gate
      i, j, f, o = array_ops.split(1, 4, concat)

      new_c = (c * tf.nn.sigmoid(f + self._forget_bias) + sigmoid(i) *
               self._activation(j))
      new_h = self._activation(new_c) * sigmoid(o)
      if self._is_training:
          #timestep = get_timestep()
          timestep = 1
          tf.histogram_summary("i/%03d" % timestep, i)
          tf.histogram_summary("j/%03d" % timestep, j)
          tf.histogram_summary("f/%03d" % timestep, f)
          tf.histogram_summary("o/%03d" % timestep, o)
          tf.histogram_summary("c/%03d" % timestep, c)
          tf.histogram_summary("h/%03d" % timestep, h)

      if self._state_is_tuple:
        new_state = LSTMStateTuple(new_c, new_h)
      else:
        new_state = array_ops.concat(1, [new_c, new_h])
      return new_h, new_state

time_steps = 8
num_units = 3
input_size = 5
batch_size = 2

input_values = np.random.randn(time_steps, batch_size, input_size)

sequence_length = tf.placeholder(tf.int32, shape=(batch_size))
summary_writer = tf.train.SummaryWriter(
    'graph_test/')

concat_inputs = tf.placeholder(
  tf.float32, shape=(time_steps, batch_size, input_size))
inputs = [tf.placeholder(tf.float32, shape=(batch_size, input_size)) for _ in range(time_steps)]
cell = BasicLSTMCell(num_units, forget_bias=False, is_training=True, add_summary=True)

if False:
    # dynamic_rnn
    # this hangs
    outputs, state = tf.nn.dynamic_rnn(
      cell, inputs=concat_inputs, 
      time_major=True, dtype=tf.float32, sequence_length=sequence_length)
    feeds = {}
    feeds[concat_inputs] = input_values
    feeds[sequence_length] = np.array([2,5])    
else:
    # rnn
    # InvalidArgumentError
    outputs, state = tf.nn.rnn(
        cell, inputs, dtype=tf.float32, sequence_length=sequence_length)
    feeds = {}
    for var in inputs:
        feeds[var] = np.random.randn(batch_size, input_size)
    feeds[sequence_length] = np.array([2,5])    


merged_summary = tf.merge_all_summaries()
to_fetch = outputs
if isinstance(to_fetch, list):
    to_fetch.append(merged_summary)
else:
    to_fetch = [to_fetch, merged_summary]

with tf.Session("") as sess:
  # Initialize
  tf.initialize_all_variables().run()
  fetches = sess.run(to_fetch, feed_dict=feeds)
  summary = fetches[-1]
  summary_writer.add_summary(summary, 1)

```

**Comment by zhengwy888** [comment]
Do you need more information @ebrevdo ?

**Comment by ebrevdo** [comment]
What happens if you remove the "sequence_length" parameter to rnn?  to dynamic_rnn?

**Comment by zhengwy888** [comment]
if I removed the sequence_length, rnn() works, dynamic_rnn doesn't work. maybe just give empty values to histogram when the part of graph wasn't executed can fix this problem.

**Comment by ebrevdo** [comment]
It does indicate that histogram creation inside contexts, including cond
and while, is unsupported.  We can add it to rnn() but dynamic_rnn will be
difficult without help from Yuan.

**Comment by drpngx** [comment]
Closing due to inactivity. Feel free to open a new github issue if the problem still persists in recent versions.
