### ISSUE TITLE
std::terminate may be called when environment is misconfigured while using C API

### ISSUE THREAD

**Issue by nagisa** [tensorflow/tensorflow#27163]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- TensorFlow installed from (source or binary): Source
- TensorFlow version (use command below): 1.12
- Python version: N/A, C API is used
- Bazel version (if compiling from source): 0.16.1
- GCC/Compiler version (if compiling from source): 6.4.0/5.3.0
- CUDA/cuDNN version: libcuda comes from 418.43 drivers, cudnn 7.3.1
- GPU model and memory: nvidia, model/memory irrelevant

**Describe the current behavior**

When attempting to run a session via C API on a TensorRT-using graph, it is possible for exceptions to not get caught and abort the whole process via `std::terminate`. Stack-trace of one such exception, which happens when cudnn initialization fails, is provided below. Then the execution fails with:

```
terminate called after throwing an instance of 'nvinfer1::CudaError'
  what():  std::exception
fish: “./target/debug/rustwat-a51801bf…” terminated by signal SIGABRT (Abort)
```

**Describe the expected behavior**

I would expect C API for `TF_SessionRun` and similar to return an error and caller to have an option to handle the error in some way that does not involve crashing.

**Code to reproduce the issue**

N/A, this is a failure of libtensorflow to return an error for system configuration issue.

**Other info / logs**

```
#0  0x00007fffca5d7b60 in __cxa_throw () from libstdc++.so.6
#1  0x00007fffc494fc23 in nvinfer1::throwCudaError(char const*, char const*, int, int, char const*) () from libnvinfer.so.5
#2  0x00007fffc495578e in nvinfer1::rt::initializeCommonContext(nvinfer1::rt::CommonContext&, nvinfer1::IGpuAllocator&, void*, void*, int) () from libnvinfer.so.5
#3  0x00007fffc495a4d4 in nvinfer1::rt::Engine::initialize() () from libnvinfer.so.5
#4  0x00007fffc495dc04 in nvinfer1::rt::Engine::deserialize(void const*, unsigned long, nvinfer1::IGpuAllocator&, nvinfer1::IPluginFactory*) () from libnvinfer.so.5
#5  0x00007fffc4946b33 in nvinfer1::Runtime::deserializeCudaEngine(void const*, unsigned long, nvinfer1::IPluginFactory*) () from libnvinfer.so.5
#6  0x00007fffd4d001e1 in tensorflow::tensorrt::TRTEngineOp::GetEngine(int, tensorflow::OpKernelContext*) () from libtftrt.so
#7  0x00007fffd4d03b8b in tensorflow::tensorrt::TRTEngineOp::ComputeAsync(tensorflow::OpKernelContext*, std::function<void ()>) () from libtftrt.so
#8  0x00007fffd3bd9f11 in tensorflow::BaseGPUDevice::ComputeAsync(tensorflow::AsyncOpKernel*, tensorflow::OpKernelContext*, std::function<void ()>) () from libtensorflow_framework.so
#9  0x00007fffd3c20fbb in tensorflow::(anonymous namespace)::ExecutorState::Process(tensorflow::(anonymous namespace)::ExecutorState::TaggedNode, long long) () from libtensorflow_framework.so
#10 0x00007fffd3c212ef in std::_Function_handler<void (), tensorflow::(anonymous namespace)::ExecutorState::ScheduleReady(absl::InlinedVector<tensorflow::(anonymous namespace)::ExecutorState::TaggedNode, 8ul, std::allocator<tensorflow::(anonymous namespace)::ExecutorState::TaggedNode> > const&, tensorflow::(anonymous namespace)::ExecutorState::TaggedNodeReadyQueue*)::{lambda()#1}>::_M_invoke(std::_Any_data const&) () from libtensorflow_framework.so
#11 0x00007fffd3c8a4c1 in Eigen::NonBlockingThreadPoolTempl<tensorflow::thread::EigenEnvironment>::WorkerLoop(int) () from libtensorflow_framework.so
#12 0x00007fffd3c880e7 in std::_Function_handler<void (), tensorflow::thread::EigenEnvironment::CreateThread(std::function<void ()>)::{lambda()#1}>::_M_invoke(std::_Any_data const&) () from libtensorflow_framework.so
#13 0x00007fffca6026df in ?? () from libstdc++.so.6
#14 0x00007fffd5b11244 in start_thread () from libpthread.so.0
#15 0x00007fffd563bccf in clone () from libc.so.6
```

**Comment by alextp** [comment]
@azaks2 who is looking at tensorrt these days?

**Comment by aaroey** [comment]
@pooyadavoodi @trevor-m any thoughts?

**Comment by ujsyehao** [comment]
Can you solve the problem?

**Comment by trevor-m** [comment]
@aaroey Should TF-TRT try to catch exceptions from TRT library functions? Or this is more of TRT problem since they are not catching their exceptions?

**Comment by aaroey** [comment]
@trevor-m I think we should fix the problem in TRT library. In general TF prevents using exceptions.
