### ISSUE TITLE
InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'import/Placeholder' with dtype uint8 and shape [1,30,300,3]

### ISSUE THREAD

**Issue by infichen** [tensorflow/tensorflow#27173]
I try to convert a tensorflow model to tf-trt model ,but when running has errors:
Traceback (most recent call last):
  File "./tranTFtoTRT.py", line 27, in <module>
    sess.run(output_node)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'import/Placeholder' with dtype uint8 and shape [1,30,300,3]
	 [[node import/Placeholder (defined at ./tranTFtoTRT.py:26) ]]

Caused by op u'import/Placeholder', defined at:
  File "./tranTFtoTRT.py", line 26, in <module>
    return_elements=['AttentionOcr_v1/predicted_chars:0'])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/importer.py", line 442, in import_graph_def
    _ProcessNewOps(graph)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/importer.py", line 235, in _ProcessNewOps
    for new_op in graph._add_new_tf_operations(compute_devices=False):  # pylint: disable=protected-access
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3433, in _add_new_tf_operations
    for c_op in c_api_util.new_tf_operations(self)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3325, in _create_op_from_tf_operation
    ret = Operation(c_op, self)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'import/Placeholder' with dtype uint8 and shape [1,30,300,3]
	 [[node import/Placeholder (defined at ./tranTFtoTRT.py:26) ]]

Here is my code:

  1 #!/usr/bin/env python
  2 # -*- coding: utf-8 -*-
  3 
  4 # Import TensorFlow and TensorRT
  5 import tensorflow as tf
  6 import tensorflow.contrib.tensorrt as trt
  7 
  8 # Inference with TF-TRT 'SavedModel' workflow :
  9 graph = tf.Graph()
 10 with graph.as_default():
 11     with tf.Session() as sess:
 12         # Create a TensorRT inference graph from a SavedModel:
 13         trt_graph = trt.create_inference_graph(
 14             input_graph_def=None,
 15             outputs=None,
 16             input_saved_model_dir="/workspace/models/ocrmodel",
 17             input_saved_model_tags=["serve"],
 18             max_batch_size=1,
 19             #max_workspace_size_bytes=1 << 32,
 20             max_workspace_size_bytes=1 << 8,
 21             #precision_mode="FP32")
 22             precision_mode="INT8")
 23         # Import the TensorRT graph into a new graph and run:
 24         output_node = tf.import_graph_def(
 25             trt_graph,
 26             return_elements=['AttentionOcr_v1/predicted_chars:0'])
 27         sess.run(output_node)

Can anyone help me!

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose). Thanks!
