### ISSUE TITLE
tf learn bugs when running DNNClassifier examples

### ISSUE THREAD

**Issue by fayeshine** [tensorflow/tensorflow#2727]
from sklearn import datasets, metrics

iris = datasets.load_iris()
classifier = learn.DNNClassifier(hidden_units=[10, 20, 10], n_classes=3)
classifier.fit(iris.data, iris.target)
score = metrics.accuracy_score(iris.target, classifier.predict(iris.data))
print("Accuracy: %f" % score)

```
Traceback (most recent call last):

  File "<ipython-input-73-ae8986fb272b>", line 1, in <module>
    classifier.fit(iris.data, iris.target)

  File "/home/wenjian/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 181, in fit
    monitors=monitors)

  File "/home/wenjian/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 498, in _train_model
    monitors=monitors)

  File "/home/wenjian/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/graph_actions.py", line 225, in train
    monitor.begin(max_steps=start_step + steps)

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'
```

**Comment by fayeshine** [comment]
seems solved in the master branch now

**Comment by gunan** [comment]
Looks like this problem is resolved. Closing the issue.
