### ISSUE TITLE
[TF 2.0] two issues on v2 ctc_loss

### ISSUE THREAD

**Issue by SunQpark** [tensorflow/tensorflow#27270]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code: yes
- OS Platform and Distribution: Linux Ubuntu 16.04
- TensorFlow installed from: binary
- TensorFlow version (use command below): 2.0.0-alpha0
- Python version: 3.5.2
- CUDA/cuDNN version: 10.0
- GPU model and memory: Tesla V100, 32Gb

**Describe the current behavior**
 Hi, I'am working on a project and trying to migrate my code to use tf 2.0 preview, and discovered two issues using `ctc_loss`. One is about a missing keyword argument from v2, and the other is about weird behavior of gradient using v1. 

 Current version of `tf.nn.ctc_loss` raises an exception when it encounters outputs longer than label, saying that `ignore_longer_outputs_than_inputs` flag should be used to turn this exception into a warning. However, I noticed that this keyword argument was deleted from new version.
 
Hence I just decided to go back to v1 but another issue came out, which is model being trained to predict blank tokens only, just after one iteration. I'm aware that this could have happened due to other parts of my code, but I'm reporting this after several tests on that.   

**Describe the expected behavior** 
 The `ignore_longer_outputs_than_inputs` keyword should be added to the new `ctc_loss`, or set True by default. 

**Code to reproduce the issue**
I will provide code later in the comment

**Other info / logs**
```
2019-03-29 13:38:40.841685: W tensorflow/core/framework/op_kernel.cc:1431] OP_REQUIRES failed at ctc_loss_op.cc:168 : Invalid argument: Not enough time for target transition sequence (required: 49, available: 48)32You can turn this error into a warning by using the flag ignore_longer_outputs_than_inputs
2019-03-29 13:38:40.841912: W tensorflow/core/common_runtime/base_collective_executor.cc:214] BaseCollectiveExecutor::StartAbort Invalid argument: Not enough time for target transition sequence (required: 49, available: 48)32You can turn this error into a warning by using the flag ignore_longer_outputs_than_inputs
         [[{{node replica_2/CTCLoss}}]]
         [[Adam/group_deps/_1107]]
2019-03-29 13:38:40.841981: W tensorflow/core/common_runtime/base_collective_executor.cc:214] BaseCollectiveExecutor::StartAbort Invalid argument: Not enough time for target transition sequence (required: 49, available: 48)32You can turn this error into a warning by using the flag ignore_longer_outputs_than_inputs
         [[{{node replica_2/CTCLoss}}]]
         [[Adam/update_2_1/AssignAddVariableOp/_1091]]
2019-03-29 13:38:40.842035: W tensorflow/core/common_runtime/base_collective_executor.cc:214] BaseCollectiveExecutor::StartAbort Invalid argument: Not enough time for target transition sequence (required: 49, available: 48)32You can turn this error into a warning by using the flag ignore_longer_outputs_than_inputs
         [[{{node replica_2/CTCLoss}}]]
         [[GroupCrossDeviceControlEdges_0/Adam/update_2_1/Const/_1063]]
2019-03-29 13:38:40.842177: W tensorflow/core/common_runtime/base_collective_executor.cc:214] BaseCollectiveExecutor::StartAbort Invalid argument: Not enough time for target transition sequence (required: 49, available: 48)32You can turn this error into a warning by using the flag ignore_longer_outputs_than_inputs
         [[{{node replica_2/CTCLoss}}]]
         [[Adam/group_deps/_1103]]
2019-03-29 13:38:40.848029: E tensorflow/core/common_runtime/process_function_library_runtime.cc:764] Component function execution failed: Invalid argument: Not enough time for target transition sequence (required: 49, available: 48)32You can turn this error into a warning by using the flag ignore_longer_outputs_than_inputs
         [[{{node replica_2/CTCLoss}}]]
         [[GroupCrossDeviceControlEdges_0/Adam/update_2_1/Const/_1063]]
2019-03-29 13:38:40.848362: E tensorflow/core/common_runtime/process_function_library_runtime.cc:764] Component function execution failed: Invalid argument: Not enough time for target transition sequence (required: 49, available: 48)32You can turn this error into a warning by using the flag ignore_longer_outputs_than_inputs
         [[{{node replica_2/CTCLoss}}]]
         [[Adam/group_deps/_1107]]
2019-03-29 13:38:40.850240: E tensorflow/core/common_runtime/process_function_library_runtime.cc:764] Component function execution failed: Invalid argument: Not enough time for target transition sequence (required: 49, available: 48)32You can turn this error into a warning by using the flag ignore_longer_outputs_than_inputs
         [[{{node replica_2/CTCLoss}}]]
         [[Adam/group_deps/_1103]]
2019-03-29 13:38:40.852283: E tensorflow/core/common_runtime/process_function_library_runtime.cc:764] Component function execution failed: Invalid argument: Not enough time for target transition sequence (required: 49, available: 48)32You can turn this error into a warning by using the flag ignore_longer_outputs_than_inputs
         [[{{node replica_2/CTCLoss}}]]
         [[Adam/update_2_1/AssignAddVariableOp/_1091]]
2019-03-29 13:38:40.867602: W tensorflow/core/common_runtime/base_collective_executor.cc:214] BaseCollectiveExecutor::StartAbort Invalid argument: Not enough time for target transition sequence (required: 49, available: 48)32You can turn this error into a warning by using the flag ignore_longer_outputs_than_inputs
         [[{{node replica_2/CTCLoss}}]]
2019-03-29 13:38:40.881608: E tensorflow/core/common_runtime/process_function_library_runtime.cc:764] Component function execution failed: Invalid argument: Not enough time for target transition sequence (required: 49, available: 48)32You can turn this error into a warning by using the flag ignore_longer_outputs_than_inputs
         [[{{node replica_2/CTCLoss}}]]
Traceback (most recent call last):
  File "train.py", line 196, in <module>
    exp_fn = main(args, CONFIG)
  File "train.py", line 120, in main
    distributed_train()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/eager/def_function.py", line 414, in __call__
    return self._stateless_fn(*args, **kwds)  # pylint: disable=not-callable
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/eager/function.py", line 1288, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/eager/function.py", line 574, in _filtered_call
    (t for t in nest.flatten((args, kwargs))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/eager/function.py", line 627, in _call_flat
    outputs = self._inference_function.call(ctx, args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/eager/function.py", line 415, in call
    ctx=ctx)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/eager/execute.py", line 66, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: Not enough time for target transition sequence (required: 49, available: 48)32You can turn this error into a warning by using the flag ignore_longer_outputs_than_inputs
         [[{{node replica_2/CTCLoss}}]]
         [[GroupCrossDeviceControlEdges_0/Adam/update_2_1/Const/_1063]] [Op:__inference_distributed_train_49990]
```

**Comment by shashvatshahi1998** [comment]
loss, _ = gen_ctc_ops.ctc_loss(
      inputs,
      labels.indices,
      labels.values,
      sequence_length,
      preprocess_collapse_repeated=preprocess_collapse_repeated,
      ctc_merge_repeated=ctc_merge_repeated,
ignore_longer_outputs_than_inputs=ignore_longer_outputs_than_inputs)

you want this to be :

 loss, _ = gen_ctc_ops.ctc_loss(
      inputs,
      labels.indices,
      labels.values,
      sequence_length,
      preprocess_collapse_repeated=preprocess_collapse_repeated,
      ctc_merge_repeated=ctc_merge_repeated,
ignore_longer_outputs_than_inputs=True)

**Comment by SunQpark** [comment]
I think that will work for my case but will make `ignore_longer_outputs_than_inputs=False` not working in v1 ctc loss.

**Comment by jvishnuvardhan** [comment]
@SunQpark This is a stale issue. Can you try recent TF version (`TF2.0.0rc2` or `tf-nightly-2.0-preview`) and let us know if the issue still persists. If the issue is there, could you please share a small standalone code to reproduce the issue? If this was resolved, please close the issue. Thanks!

**Comment by SunQpark** [comment]
`ignore_longer_outputs_than_inputs` is still not there, but this could be considered as a reasonable decision. For the second point, model could be trained properly with ctc loss in recent `TF2.0.0rc2` version.
