### ISSUE TITLE
DLL load failure

### ISSUE THREAD

**Issue by YourFriendlyError** [tensorflow/tensorflow#27326]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Win 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): pip
- TensorFlow version: 1.12
- Python version: 3.6.4
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: CUDA v9.0
- GPU model and memory: GTX 1060 6gb

**Describe the problem**
Basically trying to import tensor results in an "ImportError: DLL load failure." I already have cudart64_90.dll installed to its destination along with other necessary files. A complete re-install of TensorFlow does not fix this problem. Checked the CUDA paths only to find no issues.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
`import tensorflow`

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

> Traceback (most recent call last):
>   File "C:\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
>     from tensorflow.python.pywrap_tensorflow_internal import *
>   File "C:\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
>     _pywrap_tensorflow_internal = swig_import_helper()
>   File "C:\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
>     _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
>   File "C:\Python\Python36\lib\imp.py", line 243, in load_module
>     return load_dynamic(name, filename, file)
>   File "C:\Python\Python36\lib\imp.py", line 343, in load_dynamic
>     return _load(spec)
> ImportError: DLL load failed: The specified module could not be found.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:/PycharmProjects/TensPlease/CanITens.py", line 7, in <module>
>     import tensorflow as tf
>   File "C:\Python\Python36\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
>     from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
>   File "C:\Python\Python36\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
>     from tensorflow.python import pywrap_tensorflow
>   File "C:\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
>     raise ImportError(msg)
> ImportError: Traceback (most recent call last):
>   File "C:\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
>     from tensorflow.python.pywrap_tensorflow_internal import *
>   File "C:\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
>     _pywrap_tensorflow_internal = swig_import_helper()
>   File "C:\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
>     _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
>   File "C:\Python\Python36\lib\imp.py", line 243, in load_module
>     return load_dynamic(name, filename, file)
>   File "C:\Python\Python36\lib\imp.py", line 343, in load_dynamic
>     return _load(spec)
> ImportError: DLL load failed: The specified module could not be found.

**Comment by YourFriendlyError** [comment]
Fixed the issue.
Downgraded to Tensorflow 1.5, for some reason it works, and restarted the system.
