### ISSUE TITLE
[ROCM] Build failed due to libhip_hcc.so, but HIP and HCC are installed

### ISSUE THREAD

**Issue by auyer** [tensorflow/tensorflow#27352]
**System information**
- OS Platform and Distribution : Manjaro Linux x86_64
- TensorFlow installed from (source or binary): Source
- TensorFlow version: 2.0.0-alpha0
- Python version: Python 3.7.2
- Installed using virtualenv? pip? conda?: No
- Bazel version (if compiling from source): Build label: 0.22.0- (@non-git)
- GCC/Compiler version : gcc 8.2.1 ; HCC clang version 9.0.0; clang version 7.0.1,
- CUDA/cuDNN version: NA / ROCm 2.2.0-1 ; ROCm-opencl-runtime 2.2.0-3, HIP version 2.2.0-1
- GPU model and memory: Vega 64, 8GB

**Describe the problem**
 Building with ROCm support fails.

Inside  2.0.0-alpha0 folder: 
- ./configure
- bazel build --config=opt --config=rocm //tensorflow/tools/pip_package:build_pip_package

**Any other info / logs**
```
INFO: Invocation ID: a35bccb9-a4af-40de-bede-9b7df9283be4
DEBUG: Rule 'build_bazel_rules_swift' modified arguments {"commit": "001736d056d7eae20f1f4da41bc9e6f036857296", "shallow_since": "1547844730 -0800"} and dropped ["tag"]
DEBUG: /home/auyer/.cache/bazel/_bazel_auyer/965b880f59234d9db802b221eaf21de8/external/build_bazel_rules_apple/apple/repositories.bzl:35:5:
WARNING: `build_bazel_rules_apple` depends on `bazel_skylib` loaded from https://github.com/bazelbuild/bazel-skylib.git (tag 0.6.0), but we have detected it already loaded into your workspace from None (tag None). You may run into compatibility issues. To silence this warning, pass `ignore_version_differences = True` to `apple_rules_dependencies()`.

ERROR: Skipping '//tensorflow/tools/pip_package:build_pip_package': error loading package 'tensorflow/tools/pip_package': in /home/auyer/tensorflow/tensorflow-2.0.0-alpha0/tensorflow/tensorflow.bzl: Encountered error while reading extension file 'rocm/build_defs.bzl': no such package '@local_config_rocm//rocm': Traceback (most recent call last):
	File "/home/auyer/tensorflow/tensorflow-2.0.0-alpha0/third_party/gpus/rocm_configure.bzl", line 755
		_create_local_rocm_repository(repository_ctx)
	File "/home/auyer/tensorflow/tensorflow-2.0.0-alpha0/third_party/gpus/rocm_configure.bzl", line 631, in _create_local_rocm_repository
		_find_libs(repository_ctx, rocm_config)
	File "/home/auyer/tensorflow/tensorflow-2.0.0-alpha0/third_party/gpus/rocm_configure.bzl", line 376, in _find_libs
		_find_rocm_lib("hip_hcc", repository_ctx, cpu_value, ...)
	File "/home/auyer/tensorflow/tensorflow-2.0.0-alpha0/third_party/gpus/rocm_configure.bzl", line 361, in _find_rocm_lib
		auto_configure_fail(("Cannot find rocm library %s" %...))
	File "/home/auyer/tensorflow/tensorflow-2.0.0-alpha0/third_party/gpus/rocm_configure.bzl", line 121, in auto_configure_fail
		fail(("\n%sROCm Configuration Error:%...)))

ROCm Configuration Error: Cannot find rocm library libhip_hcc.so
WARNING: Target pattern parsing failed.
ERROR: error loading package 'tensorflow/tools/pip_package': in /home/auyer/tensorflow/tensorflow-2.0.0-alpha0/tensorflow/tensorflow.bzl: Encountered error while reading extension file 'rocm/build_defs.bzl': no such package '@local_config_rocm//rocm': Traceback (most recent call last):
	File "/home/auyer/tensorflow/tensorflow-2.0.0-alpha0/third_party/gpus/rocm_configure.bzl", line 755
		_create_local_rocm_repository(repository_ctx)
	File "/home/auyer/tensorflow/tensorflow-2.0.0-alpha0/third_party/gpus/rocm_configure.bzl", line 631, in _create_local_rocm_repository
		_find_libs(repository_ctx, rocm_config)
	File "/home/auyer/tensorflow/tensorflow-2.0.0-alpha0/third_party/gpus/rocm_configure.bzl", line 376, in _find_libs
		_find_rocm_lib("hip_hcc", repository_ctx, cpu_value, ...)
	File "/home/auyer/tensorflow/tensorflow-2.0.0-alpha0/third_party/gpus/rocm_configure.bzl", line 361, in _find_rocm_lib
		auto_configure_fail(("Cannot find rocm library %s" %...))
	File "/home/auyer/tensorflow/tensorflow-2.0.0-alpha0/third_party/gpus/rocm_configure.bzl", line 121, in auto_configure_fail
		fail(("\n%sROCm Configuration Error:%...)))

ROCm Configuration Error: Cannot find rocm library libhip_hcc.so
INFO: Elapsed time: 0.066s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: tensorflow/tools/pip_package
    Fetching @local_config_rocm; fetching
```

**Comment by sunway513** [comment]
Hi @auyer, Manjaro Linux x86_64 is not in ROCm official support list, [here](https://github.com/RadeonOpenCompute/ROCm#supported-operating-systems---new-operating-systems-available) is the document for reference.
Althernatively, you can install upstream kernels (4.18 or newer) and use the ROCm pre-build docker images to try tensorflow on ROCm stack.

The following is the TF-ROCm docker registry, instructions are provided there for docker configurations:
https://cloud.docker.com/u/rocm/repository/docker/rocm/tensorflow

**Comment by auyer** [comment]
I know Arch is not an officialy supported OS, but I’ve built an older version of ROCm TF without problems before.

About the Docker image, your URL requires authentication, and renders 404 when autjenticated.
I managed to find this image on [docker hub](https://hub.docker.com/r/rocm/tensorflow/). If its the same, please edit your answer to help ones who decide to take this path. 

Feel free to close this issue if you fill fit. Thanks

**Comment by sunway513** [comment]
Thanks, @auyer , I've updated the link in my first comment.
Besides, I'd remind that not all the required code has been upstreamed to the main tensorflow repo till now - we are actively working on it. 
You can refer to our local fork at the moment for complete information and full support on ROCm-TF project:
https://github.com/ROCmSoftwarePlatform/tensorflow-upstream

**Comment by auyer** [comment]
Thanks!
I also tried building with the release downloaded from their repository, and got the same results.

Should I close this issue and post it in their repository then?

**Comment by jvishnuvardhan** [comment]
@auyer Please post it in that repo. This will get some visibility and most probably will get resolved soon.  Close the issue as soon as you post it there. Thanks!

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by jvishnuvardhan** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by baerbock** [comment]
@auyer @jvishnuvardhan I've just tried under Arch and observed the same issue.
