### ISSUE TITLE
# From tensorflow/models/research/ issue

### ISSUE THREAD

**Issue by jaysumona2019** [tensorflow/tensorflow#27376]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by jaysumona2019** [comment]
Hello, I have issue in the following steps:
# From tensorflow/models/research/
protoc object_detection/protos/*.proto --python_out=.

when I go to my MAC and change directory to tensorflow/models/research/ and enter. protoc object_detection/protos/*.proto --python_out=.  - I SEE OUT 'IS A DIRECTORY"
PLEASE SEE BELOW.  I am stuck at the step and can not move forward - please advise what I am doing wrong?  thanks.

/Applications/anaconda2/lib/python2.7/site-packages/tensorflow/models/research protoc object_detection/protos/*.proto --python_out=.
-bash: /Applications/anaconda2/lib/python2.7/site-packages/tensorflow/models/research: is a directory

**Comment by jaysumona2019** [comment]
I thought the problem is due to this :  make
cp -r pycocotools <path_to_tensorflow>/models/research/
so I tried
make cp -r pycocotools /Applications/anaconda2/lib/python2.7/site-packages/tensorflow/models/research/
make: *** No rule to make target `cp'.  Stop.

it is still not working.

**Comment by gadagashwini** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by gadagashwini** [comment]
@jaysumona2019 Please provide the details.

**Comment by ymodak** [comment]
This issue is more suitable on TF Models repo. Please post it on TF Models from [here](https://github.com/tensorflow/models/issues/new). Thanks!

**Comment by jaysumona2019** [comment]
Hello, after a lot of try I passed that stage, but still having issue with tensor flow.  below is my error, I am using MAC and python 2.7.  Can you please tell me why this error happens?

Last login: Wed Apr  3 20:38:52 on console
$ cd /Applications/anaconda2/lib/python2.7/site-packages/tensorflow/models/research 
$ export PYTHONPATH=$PYTHONPATH:`pwd`:`pwd`/slim
$ python object_detection/builders/model_builder_test.py
Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 23, in <module>
    from object_detection.builders import model_builder
  File "/Applications/anaconda2/lib/python2.7/site-packages/tensorflow/models/research/object_detection/builders/model_builder.py", line 22, in <module>
    from object_detection.builders import box_predictor_builder
  File "/Applications/anaconda2/lib/python2.7/site-packages/tensorflow/models/research/object_detection/builders/box_predictor_builder.py", line 20, in <module>
    from object_detection.predictors import convolutional_box_predictor
  File "/Applications/anaconda2/lib/python2.7/site-packages/tensorflow/models/research/object_detection/predictors/convolutional_box_predictor.py", line 22, in <module>
    slim = tf.contrib.slim
  File "/Applications/anaconda2/lib/python2.7/site-packages/tensorflow/python/util/lazy_loader.py", line 61, in __getattr__
    module = self._load()
  File "/Applications/anaconda2/lib/python2.7/site-packages/tensorflow/python/util/lazy_loader.py", line 44, in _load
    module = importlib.import_module(self.__name__)
  File "/Applications/anaconda2/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Applications/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/__init__.py", line 41, in <module>
    from tensorflow.contrib import distributions
  File "/Applications/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/distributions/__init__.py", line 44, in <module>
    from tensorflow.contrib.distributions.python.ops.estimator import *
  File "/Applications/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/distributions/python/ops/estimator.py", line 21, in <module>
    from tensorflow.contrib.learn.python.learn.estimators.head import _compute_weighted_loss
  File "/Applications/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/__init__.py", line 93, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/Applications/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/__init__.py", line 28, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/Applications/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/__init__.py", line 30, in <module>
    from tensorflow.contrib.learn.python.learn import estimators
  File "/Applications/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/__init__.py", line 302, in <module>
    from tensorflow.contrib.learn.python.learn.estimators.dnn import DNNClassifier
  File "/Applications/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/dnn.py", line 34, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import dnn_linear_combined
  File "/Applications/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/dnn_linear_combined.py", line 36, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import estimator
  File "/Applications/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 52, in <module>
    from tensorflow.contrib.learn.python.learn.learn_io import data_feeder
  File "/Applications/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/learn_io/__init__.py", line 26, in <module>
    from tensorflow.contrib.learn.python.learn.learn_io.dask_io import extract_dask_data
  File "/Applications/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/learn_io/dask_io.py", line 33, in <module>
    import dask.dataframe as dd
  File "/Applications/anaconda2/lib/python2.7/site-packages/dask/dataframe/__init__.py", line 4, in <module>
    from .core import (DataFrame, Series, Index, _Frame, map_partitions,
  File "/Applications/anaconda2/lib/python2.7/site-packages/dask/dataframe/core.py", line 19, in <module>
    from .. import array as da
  File "/Applications/anaconda2/lib/python2.7/site-packages/dask/array/__init__.py", line 9, in <module>
    from .routines import (take, choose, argwhere, where, coarsen, insert,
  File "/Applications/anaconda2/lib/python2.7/site-packages/dask/array/routines.py", line 256, in <module>
    @wraps(np.matmul)
  File "/Applications/anaconda2/lib/python2.7/functools.py", line 33, in update_wrapper
    setattr(wrapper, attr, getattr(wrapped, attr))
AttributeError: 'numpy.ufunc' object has no attribute '__module__'
$

**Comment by jaysumona2019** [comment]
Hello, the issue is not closed.

Hello, after a lot of try I passed that stage, but still having issue with
tensor flow. below is my error, I am using MAC and python 2.7. Can you
please tell me why this error happens?

Last login: Wed Apr 3 20:38:52 on console
$ cd
/Applications/anaconda2/lib/python2.7/site-packages/tensorflow/models/research
$ export PYTHONPATH=$PYTHONPATH:pwd:pwd/slim
$ python object_detection/builders/model_builder_test.py
Traceback (most recent call last):
File "object_detection/builders/model_builder_test.py", line 23, in
from object_detection.builders import model_builder
File
"/Applications/anaconda2/lib/python2.7/site-packages/tensorflow/models/research/object_detection/builders/model_builder.py",
line 22, in
from object_detection.builders import box_predictor_builder
File
"/Applications/anaconda2/lib/python2.7/site-packages/tensorflow/models/research/object_detection/builders/box_predictor_builder.py",
line 20, in
from object_detection.predictors import convolutional_box_predictor
File
"/Applications/anaconda2/lib/python2.7/site-packages/tensorflow/models/research/object_detection/predictors/convolutional_box_predictor.py",
line 22, in
slim = tf.contrib.slim
File
"/Applications/anaconda2/lib/python2.7/site-packages/tensorflow/python/util/lazy_loader.py",
line 61, in getattr
module = self._load()
File
"/Applications/anaconda2/lib/python2.7/site-packages/tensorflow/python/util/lazy_loader.py",
line 44, in _load
module = importlib.import_module(self.name)
File "/Applications/anaconda2/lib/python2.7/importlib/init.py", line 37, in
import_module
import(name)
File
"/Applications/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/init.py",
line 41, in
from tensorflow.contrib import distributions
File
"/Applications/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/distributions/
init.py", line 44, in
from tensorflow.contrib.distributions.python.ops.estimator import *
File
"/Applications/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/distributions/python/ops/estimator.py",
line 21, in
from tensorflow.contrib.learn.python.learn.estimators.head import
_compute_weighted_loss
File
"/Applications/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/
init.py", line 93, in
from tensorflow.contrib.learn.python.learn import *
File
"/Applications/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/
init.py", line 28, in
from tensorflow.contrib.learn.python.learn import *
File
"/Applications/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/
init.py", line 30, in
from tensorflow.contrib.learn.python.learn import estimators
File
"/Applications/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/
init.py", line 302, in
from tensorflow.contrib.learn.python.learn.estimators.dnn import
DNNClassifier
File
"/Applications/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/dnn.py",
line 34, in
from tensorflow.contrib.learn.python.learn.estimators import
dnn_linear_combined
File
"/Applications/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/dnn_linear_combined.py",
line 36, in
from tensorflow.contrib.learn.python.learn.estimators import estimator
File
"/Applications/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py",
line 52, in
from tensorflow.contrib.learn.python.learn.learn_io import data_feeder
File
"/Applications/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/learn_io/
init.py", line 26, in
from tensorflow.contrib.learn.python.learn.learn_io.dask_io import
extract_dask_data
File
"/Applications/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/learn_io/dask_io.py",
line 33, in
import dask.dataframe as dd
File "/Applications/anaconda2/lib/python2.7/site-packages/dask/dataframe/
init.py", line 4, in
from .core import (DataFrame, Series, Index, _Frame, map_partitions,
File
"/Applications/anaconda2/lib/python2.7/site-packages/dask/dataframe/core.py",
line 19, in
from .. import array as da
File "/Applications/anaconda2/lib/python2.7/site-packages/dask/array/init.py",
line 9, in
from .routines import (take, choose, argwhere, where, coarsen, insert,
File
"/Applications/anaconda2/lib/python2.7/site-packages/dask/array/routines.py",
line 256, in
@wraps <https://github.com/wraps>(np.matmul)
File "/Applications/anaconda2/lib/python2.7/functools.py", line 33, in
update_wrapper
setattr(wrapper, attr, getattr(wrapped, attr))
AttributeError: 'numpy.ufunc' object has no attribute 'module'
