### ISSUE TITLE
Using layer classes as attribute throw an exception

### ISSUE THREAD

**Issue by guillaumekln** [tensorflow/tensorflow#27431]
**System information**
- Have I written custom code: Yes
- OS Platform and Distribution: Ubuntu 16.04
- TensorFlow installed from: binary
- TensorFlow version: `2.0.0.dev20190402`
- Python version: 2.7.12

**Describe the current behavior**

When a layer class is used as attribute, the code will throw a `TypeError` exception when calling `self._gather_children_attribute`. It appears that the layer class is tracked.

**Describe the expected behavior**

Only layer instances should be tracked, not classes.

**Code to reproduce the issue**

```python
import tensorflow as tf

class Layer(tf.keras.layers.Layer):

    def __init__(self):
        super(Layer, self).__init__()
        self.layer_fn = tf.keras.layers.Dense

layer = Layer()
print(layer.variables)
```

**Other info / logs**

```text
Traceback (most recent call last):
  File "tf2/class.py", line 10, in <module>
    print(layer.variables)
  File "/tmp/tf2/local/lib/python2.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1330, in variables
    return self.weights
  File "/tmp/tf2/local/lib/python2.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 708, in weights
    return self.trainable_weights + self.non_trainable_weights
  File "/tmp/tf2/local/lib/python2.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 687, in trainable_weights
    nested = self._gather_children_attribute('trainable_weights')
  File "/tmp/tf2/local/lib/python2.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1850, in _gather_children_attribute
    getattr(layer, attribute) for layer in nested_layers))
TypeError: 'property' object is not iterable
```

**Comment by allenlavoie** [comment]
@qlzh727 this is a better project for someone working on TF Keras. I am realistically never going to get to it. (It's near code I've modified, but I don't think those modifications made the situation any worse.)

**Comment by qlzh727** [comment]
Ack, I will take it from here.

**Comment by qlzh727** [comment]
Should be fixed by https://github.com/tensorflow/tensorflow/commit/9d724a8e6034d321e97cdc9972d4d6e7adb3e3ca now.
