### ISSUE TITLE
Custom RNN cell's internal layers are not built properly

### ISSUE THREAD

**Issue by ageron** [tensorflow/tensorflow#27445]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
MaxOSX 10.13.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
N/A
- TensorFlow installed from (source or binary):
Binary
- TensorFlow version (use command below):
`tf.version.VERSION = '2.0.0-dev20190402'`
`tf.version.GIT_VERSION = 'v1.12.0-11462-gf6732b0261'`
- Python version:
3.6.8
- Bazel version (if compiling from source):
N/A
- GCC/Compiler version (if compiling from source):
N/A
- CUDA/cuDNN version:
N/A
- GPU model and memory:
N/A

**Describe the current behavior**
When creating a custom RNN cell containing a few layers (created in the constructor), these internal layers are not properly built the first time the cell is used.

**Describe the expected behavior**
I expect custom cells to behave like custom layers: the first time the cell is used, all of its internal layers should be automatically built.

**Code to reproduce the issue**
The following code fails because the internal `SimpleRNNCell` is not built before it is used. If you uncomment the two lines that define the `build()` method, then everything works fine. But this should not be required (just like it is not required for custom layers):

```python
import numpy as np
from tensorflow import keras

class MyCell(keras.layers.Layer):
    def __init__(self, units, **kwargs):
        super().__init__(**kwargs)
        self.units = units
        self.state_size = units
        self.simple_rnn_cell = keras.layers.SimpleRNNCell(self.units)
#    def build(self, step_input_shape):
#        self.simple_rnn_cell.build(step_input_shape)
    def call(self, inputs, states):
        outputs, new_states = self.simple_rnn_cell.call(inputs, states)
        return outputs, new_states

model = keras.models.Sequential([
    keras.layers.RNN(MyCell(20), return_sequences=True),
    keras.layers.RNN(MyCell(20), return_sequences=True),
    keras.layers.TimeDistributed(keras.layers.Dense(1))
])

X = np.random.randn(1000, 30, 10)
Y = np.random.randn(1000, 30, 1)
model.compile(loss="mse", optimizer="adam")
history = model.fit(X, Y) # <= AttributeError: 'SimpleRNNCell' object has no attribute 'kernel'
```

**Other info / logs**
Here is the full stacktrace:

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../tensorflow/python/keras/engine/training.py", line 807, in fit
    shuffle=shuffle)
  File ".../tensorflow/python/keras/engine/training.py", line 2417, in _standardize_user_data
    self._set_inputs(cast_inputs)
  File ".../tensorflow/python/keras/engine/training.py", line 2646, in _set_inputs
    outputs = self(inputs, **kwargs)
  File ".../tensorflow/python/keras/engine/base_layer.py", line 601, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File ".../tensorflow/python/keras/engine/sequential.py", line 256, in call
    outputs = layer(inputs, **kwargs)
  File ".../tensorflow/python/keras/layers/recurrent.py", line 639, in __call__
    return super(RNN, self).__call__(inputs, **kwargs)
  File ".../tensorflow/python/keras/engine/base_layer.py", line 601, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File ".../tensorflow/python/keras/layers/recurrent.py", line 764, in call
    zero_output_for_mask=self.zero_output_for_mask)
  File ".../tensorflow/python/keras/backend.py", line 3527, in rnn
    initial_states + constants)
  File ".../tensorflow/python/keras/layers/recurrent.py", line 749, in step
    output, new_states = self.cell.call(inputs, states, **kwargs)
  File "<stdin>", line 10, in call
  File ".../tensorflow/python/keras/layers/recurrent.py", line 1241, in call
    h = K.dot(inputs, self.kernel)
AttributeError: 'SimpleRNNCell' object has no attribute 'kernel'
```

**Comment by ageron** [comment]
Oops, my bad, I should have used:

```python
outputs, new_states = self.simple_rnn_cell(inputs, states)
```

instead of

```python
outputs, new_states = self.simple_rnn_cell.call(inputs, states)
```

Note to self: get more sleep. ;-)
