### ISSUE TITLE
TF 2.0 / `SequenceFeatures` shows an error when I put same sequence length of features.

### ISSUE THREAD

**Issue by seungbaeji** [tensorflow/tensorflow#27442]
`keras.experimental.SequenceFeatures` requires `SparseTensor` but it measures the sequence length without `0` values.

For example, sequence data [[0,0,1,2], [0,1,2,3]] has `4` sequence lengths but when it converted to `SparseTensor`, it has a `2` sequence length and a `3` sequence length.

It shows an error as below:
```
Traceback (most recent call last):
  File "pipeline2.py", line 280, in <module>
    seq_input, seq_len = seq_feature_layer(inputs)
  File "/Users/seungbaeji/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 660, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/Users/seungbaeji/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/feature_column/sequence_feature_column.py", line 140, in call
    sequence_length = _assert_all_equal_and_return(sequence_lengths)
  File "/Users/seungbaeji/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/feature_column/sequence_feature_column.py", line 489, in _assert_all_equal_and_return
    assert_equal_ops.append(check_ops.assert_equal(tensors[0], t))
  File "/Users/seungbaeji/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/ops/check_ops.py", line 496, in assert_equal
    (message or '', index_and_values_str, summary_msg)))
tensorflow.python.framework.errors_impl.InvalidArgumentError: 
Condition x == y did not hold.
Indices of first 3 different values:
[[0]
 [1]
 [2]]
Corresponding x values:
[95 94 93]
Corresponding y values:
[96 96 96]
First 3 elements of x:
[95 94 93]
First 3 elements of y:
[96 96 96]
```

**Comment by seungbaeji** [comment]
`tf.feature_columns.utils.sequence_length_from_sparse_tensor` doesn't count `0` value as an element of the sequence. Therefore, if you have a `0` in your sequence, you have to apply indices of `0`.
