### ISSUE TITLE
Import tensorflow not working on RHEL6

### ISSUE THREAD

**Issue by Abinayasandhiya** [tensorflow/tensorflow#27452]
**System information**
- Red Hat Enterprise Linux Server release 6.8 (Santiago)
- Install using Virtualenv : https://www.tensorflow.org/install/pip
- TensorFlow version: latest
- Python version: 3.6.4
- Installed using virtualenv
- Bazel version (if compiling from source): Not compiling from source
- GCC/Compiler version (if compiling from source): gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-18)

**Describe the problem**

We have installed Tensorflow using Virtualenv.
Below steps which we followed from our end:

virtualenv --system-site-packages -p python3 venv
[root@abi venv]$ ls
bin  include  lib  lib64  pip-selfcheck.json
source ~/tensorflow/venv/bin/activate
pip3 install --upgrade tensorflow // in venv environment
 
After installation we tried to import "tensorflow" in python like "import tensorflow".
Facing below issue:

`(venv) [root@abinaya-simics-r6 ~]$ python
Python 3.6.4 (default, Oct  8 2018, 06:53:21)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
Traceback (most recent call last):
  File "/root/tensorflow/venv/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/root/tensorflow/venv/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/root/tensorflow/venv/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/root/tensorflow/venv/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/root/tensorflow/venv/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /lib64/libc.so.6: version `GLIBC_2.16' not found (required by /root/tensorflow/venv/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/tensorflow/venv/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/root/tensorflow/venv/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/root/tensorflow/venv/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/root/tensorflow/venv/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/root/tensorflow/venv/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/root/tensorflow/venv/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/root/tensorflow/venv/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/root/tensorflow/venv/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /lib64/libc.so.6: version `GLIBC_2.16' not found (required by /root/tensorflow/venv/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
>>>
`

As per the issue we could understand that "/root/tensorflow/venv/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so" need "GLIBC 2.14 atleast.

But available GLIBC version in RHEL6 is:

`[root@abinaya-simics-r6 ~]$ strings /usr/lib64/libstdc++.so.6 | grep GLIBC_
GLIBC_2.2.5
GLIBC_2.3
GLIBC_2.4
GLIBC_2.3.2
`
Could you please confirm us whether the tensorflow really need latest version of GLIBC.
Provide some Doc on this case for better understand.

**Comment by jvishnuvardhan** [comment]
@Abinayasandhiya Could you follow the instructions listed in TF [website](https://www.tensorflow.org/install/pip). 
$virtualenv --system-site-packages -p python3 ./venv
$source ./venv/bin/activate  # sh, bash, ksh, or zsh
(venv) $pip install --upgrade tensorflow
(venv) $python
(venv) $import tensorflow as tf.

I tried the steps you followed and this (source ~/tensorflow/venv/bin/activate) step didn't work for me.
Please follow the instructions from TF website and let me know how it progresses. Thanks!

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by jvishnuvardhan** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
