### ISSUE TITLE
OOM ERROR  when computing_gradients on single gpu(TITAN Xp 12gb)

### ISSUE THREAD

**Issue by akshay951228** [tensorflow/tensorflow#27467]
I was trying to training network with 4k resolution and I'm using adam optimizer  and compute gradient are not fitting in single seperate gpu
**My system config is 4GPU(TITAN Xp 12gb) and 48 cpu processor and 128gb ram**

Can somebody help me to solve how compute gradient for single graph with batch 1 on multi gpu without getting OOM
Below is the stack trace of my error
**2019-04-03 16:43:30.883434: W tensorflow/core/common_runtime/bfc_allocator.cc:275] Allocator (GPU_2_bfc) ran out of memory trying to allocate 384.00MiB.  Current allocation summary follows.
2019-04-03 16:43:30.883548: I tensorflow/core/common_runtime/bfc_allocator.cc:630] Bin (256):   Total Chunks: 38, Chunks in use: 37. 9.5KiB allocated for chunks. 9.2KiB in use in bin. 6.3KiB client-reques
ted in use in bin.
2019-04-03 16:43:30.883579: I tensorflow/core/common_runtime/bfc_allocator.cc:630] Bin (512):   Total Chunks: 24, Chunks in use: 24. 12.0KiB allocated for chunks. 12.0KiB in use in bin. 12.0KiB client-req
uested in use in bin.
2019-04-03 16:43:30.883598: I tensorflow/core/common_runtime/bfc_allocator.cc:630] Bin (1024):  Total Chunks: 50, Chunks in use: 50. 50.2KiB allocated for chunks. 50.2KiB in use in bin. 50.0KiB client-req
uested in use in bin.
2019-04-03 16:43:30.883617: I tensorflow/core/common_runtime/bfc_allocator.cc:630] Bin (2048):  Total Chunks: 34, Chunks in use: 34. 68.0KiB allocated for chunks. 68.0KiB in use in bin. 68.0KiB client-req
uested in use in bin.
2019-04-03 16:43:30.883635: I tensorflow/core/common_runtime/bfc_allocator.cc:630] Bin (4096):  Total Chunks: 23, Chunks in use: 23. 94.8KiB allocated for chunks. 94.8KiB in use in bin. 94.8KiB client-req
uested in use in bin.
2019-04-03 16:43:30.883652: I tensorflow/core/common_runtime/bfc_allocator.cc:630] Bin (8192):  Total Chunks: 9, Chunks in use: 9. 72.0KiB allocated for chunks. 72.0KiB in use in bin. 72.0KiB client-requested in use in bin.
2019-04-03 16:43:30.883669: I tensorflow/core/common_runtime/bfc_allocator.cc:630] Bin (16384):         Total Chunks: 2, Chunks in use: 2. 36.0KiB allocated for chunks. 36.0KiB in use in bin. 36.0KiB client-requested in use in bin.
2019-04-03 16:43:30.883685: I tensorflow/core/common_runtime/bfc_allocator.cc:630] Bin (32768):         Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2019-04-03 16:43:30.883703: I tensorflow/core/common_runtime/bfc_allocator.cc:630] Bin (65536):         Total Chunks: 6, Chunks in use: 6. 384.0KiB allocated for chunks. 384.0KiB in use in bin. 384.0KiB client-requested in use in bin.
2019-04-03 16:43:30.883721: I tensorflow/core/common_runtime/bfc_allocator.cc:630] Bin (131072):        Total Chunks: 5, Chunks in use: 5. 704.0KiB allocated for chunks. 704.0KiB in use in bin. 704.0KiB client-requested in use in bin.
2019-04-03 16:43:30.883737: I tensorflow/core/common_runtime/bfc_allocator.cc:630] Bin (262144):        Total Chunks: 8, Chunks in use: 8. 2.03MiB allocated for chunks. 2.03MiB in use in bin. 2.03MiB client-requested in use in bin.
2019-04-03 16:43:30.883754: I tensorflow/core/common_runtime/bfc_allocator.cc:630] Bin (524288):        Total Chunks: 7, Chunks in use: 7. 3.81MiB allocated for chunks. 3.81MiB in use in bin. 3.81MiB client-requested in use in bin.
2019-04-03 16:43:30.883771: I tensorflow/core/common_runtime/bfc_allocator.cc:630] Bin (1048576):       Total Chunks: 11, Chunks in use: 11. 11.00MiB allocated for chunks. 11.00MiB in use in bin. 11.00MiB client-requested in use in bin.
2019-04-03 16:43:30.883795: I tensorflow/core/common_runtime/bfc_allocator.cc:630] Bin (2097152):       Total Chunks: 9, Chunks in use: 9. 19.50MiB allocated for chunks. 19.50MiB in use in bin. 19.50MiB client-requested in use in bin.
2019-04-03 16:43:30.883813: I tensorflow/core/common_runtime/bfc_allocator.cc:630] Bin (4194304):       Total Chunks: 15, Chunks in use: 15. 80.00MiB allocated for chunks. 80.00MiB in use in bin. 80.00MiB client-requested in use in bin.
2019-04-03 16:43:30.883830: I tensorflow/core/common_runtime/bfc_allocator.cc:630] Bin (8388608):       Total Chunks: 27, Chunks in use: 27. 311.00MiB allocated for chunks. 311.00MiB in use in bin. 311.00MiB client-requested in use in bin.
2019-04-03 16:43:30.883848: I tensorflow/core/common_runtime/bfc_allocator.cc:630] Bin (16777216):      Total Chunks: 24, Chunks in use: 23. 568.00MiB allocated for chunks. 544.00MiB in use in bin. 544.00MiB client-requested in use in bin.
2019-04-03 16:43:30.883864: I tensorflow/core/common_runtime/bfc_allocator.cc:630] Bin (33554432):      Total Chunks: 35, Chunks in use: 35. 1.67GiB allocated for chunks. 1.67GiB in use in bin. 1.65GiB client-requested in use in bin.
2019-04-03 16:43:30.883881: I tensorflow/core/common_runtime/bfc_allocator.cc:630] Bin (67108864):      Total Chunks: 16, Chunks in use: 16. 1.46GiB allocated for chunks. 1.46GiB in use in bin. 1.46GiB client-requested in use in bin.
2019-04-03 16:43:30.883897: I tensorflow/core/common_runtime/bfc_allocator.cc:630] Bin (134217728):     Total Chunks: 14, Chunks in use: 14. 2.56GiB allocated for chunks. 2.56GiB in use in bin. 2.56GiB client-requested in use in bin.
2019-04-03 16:43:30.883913: I tensorflow/core/common_runtime/bfc_allocator.cc:630] Bin (268435456):     Total Chunks: 8, Chunks in use: 7. 4.43GiB allocated for chunks. 4.12GiB in use in bin. 4.12GiB client-requested in use in bin.
2019-04-03 16:43:30.883930: I tensorflow/core/common_runtime/bfc_allocator.cc:646] Bin for 384.00MiB was 256.00MiB, Chunk State:
2019-04-03 16:43:30.883953: I tensorflow/core/common_runtime/bfc_allocator.cc:652]   Size: 312.18MiB | Requested Size: 0B | in_use: 0, prev:   Size: 384.00MiB | Requested Size: 384.00MiB | in_use: 1
2019-04-03 16:43:30.883970: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x7f2f3c000000 of size 1280
2019-04-03 16:43:30.883983: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x7f2f3c000500 of size 256
2019-04-03 16:43:30.883995: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x7f2f3c000600 of size 256
019-04-03 16:43:30.884175: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x7f2f84c25000 of size 6912
2019-04-03 16:43:30.884187: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x7f2f84c26b00 of size 589824
2019-04-03 16:43:30.884198: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x7f2f84cb6b00 of size 294912
2019-04-03 16:43:30.884210: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x7f2f84cfeb00 of size 256
2019-04-03 16:43:30.884221: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x7f2f84cfec00 of size 4096
2019-04-03 16:43:30.884233: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x7f2f84cffc00 of size 8388608
2019-04-03 16:43:30.884246: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x7f2f854ffc00 of size 8192
2019-04-03 16:43:30.884259: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x7f2f85501c00 of size 8192
2019-04-03 16:43:30.884271: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x7f2f85503c00 of size 20480
2019-04-03 16:43:30.884283: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x7f2f85508c00 of size 256
2019-04-03 16:43:30.884295: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x7f2f85508d00 of size 2097152
2019-04-03 16:43:30.884306: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x7f2f85708d00 of size 8192
2019-04-03 16:43:30.884318: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x7f2f8570ad00 of size 1024
2019-04-03 16:43:30.884331: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x7f2f8570b100 of size 16777216
2019-04-03 16:43:30.884343: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x7f2f8670b100 of size 2048
2019-04-03 16:43:30.884355: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x7f2f8670b900 of size 67108864
2019-04-03 16:43:30.884367: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x7f2f8a70b900 of size 4096
2019-04-03 16:43:30.884379: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x7f2f8a70c900 of size 134217728
2019-04-03 16:43:30.884391: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x7f2f9270c900 of size 4194304
2019-04-03 16:43:30.884402: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x7f2f92b0c900 of size 2048
2019-04-03 16:43:30.884414: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x7f2f92b0d100 of size 9437184
2019-04-03 16:43:30.884426: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x7f2f9340d100 of size 2048
2019-04-03 16:43:30.884437: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x7f2f9340d900 of size 4194304
2019-04-03 16:43:30.884449: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x7f2f9380d900 of size 4194304
2019-04-03 16:43:30.884460: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x7f2f93c0d900 of size 2048
2019-04-03 16:43:30.884471: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x7f2f93c0e100 of size 9437184
2019-04-03 16:43:30.884482: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x7f2f9450e100 of size 2048
2019-04-03 16:43:30.884493: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x7f2f9450e900 of size 4194304
2019-04-03 16:43:30.884505: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x7f2f9490e900 of size 2097152
2019-04-03 16:43:30.884516: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x7f2f94b0e900 of size 2048
2019-04-03 16:43:30.884527: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x7f2f94b0f100 of size 9437184
2019-04-03 16:43:30.884538: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x7f2f9540f100 of size 2048
2019-04-03 16:43:30.884549: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x7f2f9540f900 of size 4194304
2019-04-03 16:43:30.884561: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x7f2f9580f900 of size 1048576
2019-04-03 16:43:30.884572: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x7f2f9590f900 of size 1024
2019-04-03 16:43:30.884584: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x7f2f9590fd00 of size 2359296
2019-04-03 16:43:30.884595: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x7f2f95b4fd00 of size 1024
2019-04-03 16:43:30.884607: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x7f2f95b50100 of size 1048576
2019-04-03 16:43:30.884618: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x7f2f95c50100 of size 1048576
2019-04-03 16:43:30.884629: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x7f2f95d50100 of size 1024
2019-04-03 16:43:30.884640: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x7f2f95d50500 of size 2359296
2019-04-03 16:43:30.884651: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x7f2f95f90500 of size 1024
2019-04-03 16:43:30.884662: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x7f2f95f90900 of size 1048576
2019-04-03 16:43:30.884673: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x7f2f96090900 of size 1048576
2019-04-03 16:43:30.884684: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x7f2f96190900 of size 1024
2019-04-03 16:43:30.884695: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x7f2f96190d00 of size 2359296
2019-04-03 16:43:30.884706: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x7f2f963d0d00 of size 1024
2019-04-03 16:43:30.884717: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x7f2f963d1100 of size 1048576
2019-04-03 16:43:30.884728: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x7f2f964d1100 of size 1048576
2019-04-03 16:43:30.884739: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x7f2f965d1100 of size 1024
2019-04-03 16:43:30.884750: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x7f2f965d1500 of size 2359296
2019-04-03 16:43:30.884761: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x7f2f96811500 of size 1024
2019-04-03 16:43:30.884772: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x7f2f96811900 of size 1048576
2019-04-03 16:43:30.884783: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x7f2f96911900 of size 1048576
2019-04-03 16:43:30.884794: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x7f2f96a11900 of size 1024
2019-04-03 16:43:30.884805: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x7f2f96a11d00 of size 2359296
2019-04-03 16:43:30.884817: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x7f2f96c51d00 of size 1024
2019-04-03 16:43:30.884828: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x7f2f96c52100 of size 1048576
2019-04-03 16:43:30.884840: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x7f2f96d52100 of size 524288
2019-04-03 16:43:30.890317: I tensorflow/core/common_runtime/bfc_allocator.cc:674] 10 Chunks of size 6291456 totalling 60.00MiB
2019-04-03 16:43:30.890331: I tensorflow/core/common_runtime/bfc_allocator.cc:674] 1 Chunks of size 8388608 totalling 8.00MiB
2019-04-03 16:43:30.890344: I tensorflow/core/common_runtime/bfc_allocator.cc:674] 3 Chunks of size 9437184 totalling 27.00MiB
2019-04-03 16:43:30.890358: I tensorflow/core/common_runtime/bfc_allocator.cc:674] 23 Chunks of size 12582912 totalling 276.00MiB
2019-04-03 16:43:30.890371: I tensorflow/core/common_runtime/bfc_allocator.cc:674] 1 Chunks of size 16777216 totalling 16.00MiB
2019-04-03 16:43:30.890384: I tensorflow/core/common_runtime/bfc_allocator.cc:674] 22 Chunks of size 25165824 totalling 528.00MiB
2019-04-03 16:43:30.890398: I tensorflow/core/common_runtime/bfc_allocator.cc:674] 1 Chunks of size 50320896 totalling 47.99MiB
2019-04-03 16:43:30.890411: I tensorflow/core/common_runtime/bfc_allocator.cc:674] 31 Chunks of size 50331648 totalling 1.45GiB
2019-04-03 16:43:30.890425: I tensorflow/core/common_runtime/bfc_allocator.cc:674] 3 Chunks of size 62914560 totalling 180.00MiB
2019-04-03 16:43:30.890439: I tensorflow/core/common_runtime/bfc_allocator.cc:674] 1 Chunks of size 67108864 totalling 64.00MiB
2019-04-03 16:43:30.890452: I tensorflow/core/common_runtime/bfc_allocator.cc:674] 1 Chunks of size 88080384 totalling 84.00MiB
2019-04-03 16:43:30.890465: I tensorflow/core/common_runtime/bfc_allocator.cc:674] 14 Chunks of size 100663296 totalling 1.31GiB
2019-04-03 16:43:30.890479: I tensorflow/core/common_runtime/bfc_allocator.cc:674] 1 Chunks of size 134217728 totalling 128.00MiB
2019-04-03 16:43:30.890895: I tensorflow/core/common_runtime/bfc_allocator.cc:674] 13 Chunks of size 201326592 totalling 2.44GiB
2019-04-03 16:43:30.890927: I tensorflow/core/common_runtime/bfc_allocator.cc:674] 3 Chunks of size 402653184 totalling 1.12GiB
2019-04-03 16:43:30.890942: I tensorflow/core/common_runtime/bfc_allocator.cc:674] 4 Chunks of size 805306368 totalling 3.00GiB
2019-04-03 16:43:30.890958: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Sum Total of in-use chunks: 10.77GiB
2019-04-03 16:43:30.890975: I tensorflow/core/common_runtime/bfc_allocator.cc:680] Stats:
Limit:                 11916971213
InUse:                 11564461824
MaxInUse:              11564461824
NumAllocs:                     371
MaxAllocSize:            805306368

2019-04-03 16:43:30.891029: W tensorflow/core/common_runtime/bfc_allocator.cc:279] **************************************************************************************************__
Traceback (most recent call last):
  File "trianpy", line 216, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "trian.py", line 172, in main
    results = sess.run(fetches,options=run_options)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 877, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1100, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1272, in _do_run
    run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1291, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Dst tensor is not initialized.
         [[Node: percept_loss/perceptual_loss/vgg_19/Relu_19/_505 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:2", send_device="/job:localhost/replica:0/task:0/device:GPU:1", send_device_incarnation=1, tensor_name="edge_1462_percept_loss/perceptual_loss/vgg_19/Relu_19", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:2"]()]]
         [[Node: club_loss/add_1/_1623 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:1", send_device_incarnation=1, tensor_name="edge_6336_club_loss/add_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]**

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose). Thanks!
