### ISSUE TITLE
TFLiteConverter: converter.convert() does not work

### ISSUE THREAD

**Issue by ricardobnjunior** [tensorflow/tensorflow#27476]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 1.13.1
- Python version: 3.6.5
- Bazel version (if compiling from source): not applicable
- GCC/Compiler version (if compiling from source): not applicable
- CUDA/cuDNN version: not applicable
- GPU model and memory: not applicable

**Describe the current behavior**

I am trying make an new tflite quantized.
The code bellow run normally until the line:
`input_arrays = converter.get_input_arrays()`

Can you help me please?

**_Follows the error:_**

D:\quantization\venv\Scripts\python.exe D:/quantization/venv/quantization.py
TF VERSION:  1.13.1
2019-04-03 15:21:12.605076: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
WARNING:tensorflow:From D:/quantization/venv/quantization.py:25: FastGFile.__init__ (from tensorflow.python.platform.gfile) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.gfile.GFile.
Traceback (most recent call last):
  File "D:/quantization/venv/quantization.py", line 30, in <module>
    input_arrays = converter.get_input_arrays()
  File "D:\quantization\venv\lib\site-packages\tensorflow\lite\python\lite.py", line 471, in get_input_arrays
    return [_tensor_name(tensor) for tensor in self._input_tensors]
  File "D:\quantization\venv\lib\site-packages\tensorflow\lite\python\lite.py", line 471, in <listcomp>
Loading Graph
    return [_tensor_name(tensor) for tensor in self._input_tensors]
  File "D:\quantization\venv\lib\site-packages\tensorflow\lite\python\convert.py", line 217, in tensor_name
    return x.name.split(":")[0]
AttributeError: 'str' object has no attribute 'name'

**Describe the expected behavior**

**Code to reproduce the issue**

```
import numpy as np
import tensorflow as tf
from tensorflow.python.platform import gfile
tf.enable_eager_execution()

import sys
import os
if sys.version_info.major >= 3:
    import pathlib
else:
    import pathlib2 as pathlib

pbfiles_path = "D:\\Ricardo\\Ambientes Virtuals do Python\\virtualTFr1.13\\Scripts\\pbfiles"
saved_model_dir = str(sorted(pathlib.Path(pbfiles_path).glob("*.pbtxt" or "*.pb"))[-1])

os.environ['CUDA_VISIBLE_DEVICES'] = "-1"
with tf.Graph().as_default() as graph: 


    with tf.Session() as sess:
        print("Loading Graph")

        modelFile = '/pbfiles/saved_model.pb'
        with gfile.FastGFile(modelFile, 'rb') as f:
            converter = tf.lite.TFLiteConverter.from_session(sess,
                                                             input_tensors={"input_1"},
                                                             output_tensors={"conv2d_19/Sigmoid"})
            converter.inference_type = tf.lite.constants.QUANTIZED_UINT8
            input_arrays = converter.get_input_arrays()
            tflite_model = converter.convert()
            open("quant_converted_model.tflite", "wb").write(tflite_model)
```

**Comment by amitsrivastava78** [comment]
@ricardobnjunior you can try to define the minmax value and quantized_input_stats, hope this should help.


Regards
Amit

**Comment by jvishnuvardhan** [comment]
@ricardobnjunior Please let us know whether @amitsrivastava78 suggestion helped in resolving the issue? If it was resolved already, please close the issue. Thanks!

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by jvishnuvardhan** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will open a new issue. Thanks!
