### ISSUE TITLE
building pip package causes IndexError: list index out of range

### ISSUE THREAD

**Issue by preethivenkatesh** [tensorflow/tensorflow#27477]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: master branch
- Python version: 3.6
- Installed using virtualenv? pip? conda?: NA
- Bazel version (if compiling from source): 0.22
- GCC/Compiler version (if compiling from source): VC14
- CUDA/cuDNN version: NA
- GPU model and memory: NA

TensorFlow successfully compiles a windows version, but building a pip package fails

```
(tf_113) C:\Users\pvenkat2\Desktop\tensorflow>bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package

INFO: Elapsed time: 41316.964s, Critical Path: 35436.10s
INFO: 4534 processes: 4534 local.
INFO: Build completed successfully, 6007 total actions

(tf_113) C:\Users\pvenkat2\Desktop\tensorflow>bazel-bin\tensorflow\tools\pip_package\build_pip_package C:/Users/pvenkat2/Desktop/tensorflow_pkg
Wed Apr 3 09:43:33 PDT 2019 : === Preparing sources in dir: /tmp/tmp.sDKWoKSGMv
Unzipping simple_console_for_windows.zip to create runfiles tree...
Unzip finished.
/c/Users/pvenkat2/Desktop/tensorflow /c/Users/pvenkat2/Desktop/tensorflow
/c/Users/pvenkat2/Desktop/tensorflow
Wed Apr 3 10:43:07 PDT 2019 : === Building wheel
warning: no files found matching '*.pd' under directory '*'
warning: no files found matching '*.dll' under directory '*'
warning: no files found matching '*.h' under directory 'tensorflow\include\tensorflow'
warning: no files found matching '*' under directory 'tensorflow\include\Eigen'
warning: no files found matching '*.h' under directory 'tensorflow\include\google'
warning: no files found matching '*' under directory 'tensorflow\include\third_party'
warning: no files found matching '*' under directory 'tensorflow\include\unsupported'
Traceback (most recent call last):
  File "setup.py", line 304, in <module>
    keywords='tensorflow tensor machine learning',
  File "C:\Users\pvenkat2\AppData\Local\conda\conda\envs\tf_113\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\pvenkat2\AppData\Local\conda\conda\envs\tf_113\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Users\pvenkat2\AppData\Local\conda\conda\envs\tf_113\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\pvenkat2\AppData\Local\conda\conda\envs\tf_113\lib\site-packages\wheel\bdist_wheel.py", line 179, in run
    self.run_command('build')
  File "C:\Users\pvenkat2\AppData\Local\conda\conda\envs\tf_113\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\pvenkat2\AppData\Local\conda\conda\envs\tf_113\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\pvenkat2\AppData\Local\conda\conda\envs\tf_113\lib\distutils\command\build.py", line 135, in run
    self.run_command(cmd_name)
  File "C:\Users\pvenkat2\AppData\Local\conda\conda\envs\tf_113\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\pvenkat2\AppData\Local\conda\conda\envs\tf_113\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\pvenkat2\AppData\Local\conda\conda\envs\tf_113\lib\site-packages\setuptools\command\build_ext.py", line 75, in run
    _build_ext.run(self)
  File "C:\Users\pvenkat2\AppData\Local\conda\conda\envs\tf_113\lib\distutils\command\build_ext.py", line 339, in run
    self.build_extensions()
  File "C:\Users\pvenkat2\AppData\Local\conda\conda\envs\tf_113\lib\distutils\command\build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "C:\Users\pvenkat2\AppData\Local\conda\conda\envs\tf_113\lib\distutils\command\build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "C:\Users\pvenkat2\AppData\Local\conda\conda\envs\tf_113\lib\site-packages\setuptools\command\build_ext.py", line 196, in build_extension
    _build_ext.build_extension(self, ext)
  File "C:\Users\pvenkat2\AppData\Local\conda\conda\envs\tf_113\lib\distutils\command\build_ext.py", line 558, in build_extension
    target_lang=language)
  File "C:\Users\pvenkat2\AppData\Local\conda\conda\envs\tf_113\lib\distutils\ccompiler.py", line 717, in link_shared_object
    extra_preargs, extra_postargs, build_temp, target_lang)
  File "C:\Users\pvenkat2\AppData\Local\conda\conda\envs\tf_113\lib\distutils\_msvccompiler.py", line 461, in link
    build_temp = os.path.dirname(objects[0])
IndexError: list index out of range

```

**Comment by gunan** [comment]
on windows, you need to add this flag when running bazel build on the pip package:
`--define=no_tensorflow_py_deps=true`

So, the pip package build command becomes:
`bazel build --define=no_tensorflow_py_deps=true--config=opt //tensorflow/tools/pip_package:build_pip_package`
