### ISSUE TITLE
Unexpected UnicodeDecodeError: invalid continuation byte when reading lines from a file

### ISSUE THREAD

**Issue by alter-bug-tracer** [tensorflow/tensorflow#27537]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04.5 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.13.1
- Python version: 3.5.2
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

**Describe the current behavior**
Unexpected and undocumented runtime exception/error when handling malformed data.

**Describe the expected behavior**
Expected a "TypeError" or an empty list as a result.

**Code to reproduce the issue**
```
import csv
import sys
import tensorflow as tf

input_file_name = sys.argv[1]

with tf.gfile.Open(input_file_name, "r") as f:
  reader = csv.reader(f, delimiter="\t", quotechar=None)
  for line in reader:
    print(line)
```
Run with the path to the attached file as a command line argument.

**Other info / logs**

Traceback (most recent call last):
  File "tensorflow_bug.py", line 9, in <module>
    for line in reader:
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/lib/io/file_io.py", line 220, in \_\_next\_\_
    return self.next()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/lib/io/file_io.py", line 214, in next
    retval = self.readline()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/lib/io/file_io.py", line 184, in readline
    return self._prepare_value(self._read_buf.ReadLineAsString())
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/lib/io/file_io.py", line 100, in _prepare_value
    return compat.as_str_any(val)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/compat.py", line 107, in as_str_any
    return as_str(value)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/compat.py", line 80, in as_text
    return bytes_or_text.decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 0: invalid continuation byte

[corrupted_file1.zip](https://github.com/tensorflow/tensorflow/files/3047460/corrupted_file1.zip)

**Comment by ymodak** [comment]
In order to expedite the trouble-shooting process, please provide a complete code snippet to reproduce the issue reported here. Thanks!

**Comment by alter-bug-tracer** [comment]
This is the complete code snipped. Run it with the path to the attached file as its first argument.

```
import csv
import sys
import tensorflow as tf

input_file_name = sys.argv[1]

with tf.gfile.Open(input_file_name, "r") as f:
  reader = csv.reader(f, delimiter="\t", quotechar=None)
  for line in reader:
    print(line)
```

**Comment by yongtang** [comment]
@alter-bug-tracer If `tf.gfile.Open` is replaced with `open`, a similar error show up as well:
```
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xed in position 0: ordinal not in range(128)
```

It might be better to improve the error message in tf, though it seems the error message of `tf.gfile.Open` is inline with `open`?

**Comment by gregbillock** [comment]
This looks like it isn't an issue with the unicode ops. The file looks to me like it wishes it has a BOM (0xEF 0xBB 0xBF) at the start, but instead has (0xED 0xBB 0xBF). This is not a valid encoding, so python internals are throwing a unicode error when they try to convert it using decode().

I'm not sure how this is unexpected. It seems like throwing an error on corrupted input is a reasonable behavior here. Is the idea that gfile should trap it and throw a TypeError? That's the error thrown when there's an internal type mismatch, but everything here seems to be going to plan -- read type is `bytes` -- until the conversion to a unicode string is attempted.

If you want to use the unicode ops, you could read the file as bytes type and convert to unicode using substitution characters which will then load even corrupted data providing a substitution char if it finds corrupted unicode like this.

**Comment by gregbillock** [comment]
@rohan100jain

**Comment by mihaimaruseac** [comment]
Likely related to #33563

**Comment by sachinprasadhs** [comment]
Was able to reproduce the issue in Tensorflow 2.5, please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/18bb9100a51813086b6a434a9731b1a8/27537.ipynb).

**Comment by kumariko** [comment]
Was able to reproduce the issue in Tensorflow 2.6, please find the gist [**`here`**](https://colab.research.google.com/gist/kumariko/f15da65211c5ad2f892a32064337b8e1/27537.ipynb#scrollTo=zLBTcNFUN8dA).

**Comment by tilakrayal** [comment]
Was able to reproduce the issue in tensorflow v2.9.0. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/532c6c863dbee58343e7c3831248705e/untitled398.ipynb).

**Comment by huangliang0828** [comment]
The local Python files reported the following error in Chinese directory path, but was used normally in English directory/path. Python=3.9.13 or 3.9.16 Spyder=5.3.3 tensorflow=2.9.1 or 2.10.
I don't know what the problem is.
 File D:\ProgramData\miniconda3\envs\autokeras_1\lib\site-packages\tensorflow\python\eager\execute.py:54 in quick_execute   tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 205: invalid continuation byte

**Comment by 1011178l** [comment]
There are tons of "UnicodeDecodeError", will the Tensorflow team think about finding a better way to resolve this issue?
