### ISSUE TITLE
[TF 2.0]  tf.estimator.ProfilerHook... is not compatible with eager execution

### ISSUE THREAD

**Issue by lendle** [tensorflow/tensorflow#27545]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian 8.8
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): via pip
- TensorFlow version (use command below): `tf.__git_version__ : 'v1.12.0-9492-g2c319fb415', version tensorflow==2.0.0-alpha0`
- Python version: 3.6
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: NA
- GPU model and memory: NA

**Describe the current behavior**
When constructing a `tf.estimator.ProfilerHook` a error is thrown: `RuntimeError: tf.summary.FileWriter is not compatible with eager execution. Use tf.contrib.summary instead.`

**Describe the expected behavior**

**Code to reproduce the issue**

```
import tensorflow as tf
tf.estimator.ProfilerHook(10)
```

**Other info / logs**

I'm not very familiar with tf 2.0, so maybe this is just user error? Is it possible to use tf2 not in eager mode?

Full traceback: 

```
RuntimeError                              Traceback (most recent call last)
<ipython-input-7-4eefc50dcc45> in <module>
----> 1 tf.estimator.ProfilerHook(10)

~/tf2-venv/lib/python3.6/site-packages/tensorflow/python/training/basic_session_run_hooks.py in __init__(self, save_steps,save_secs, output_dir, show_dataflow, show_memory)
   1013     """
   1014     self._output_file = os.path.join(output_dir, "timeline-{}.json")
-> 1015     self._file_writer = SummaryWriterCache.get(output_dir)
   1016     self._show_dataflow = show_dataflow
   1017     self._show_memory = show_memory

~/tf2-venv/lib/python3.6/site-packages/tensorflow/python/summary/writer/writer_cache.py in get(logdir)
     61       if logdir not in FileWriterCache._cache:
     62         FileWriterCache._cache[logdir] = FileWriter(
---> 63             logdir, graph=ops.get_default_graph())
     64       return FileWriterCache._cache[logdir]

~/tf2-venv/lib/python3.6/site-packages/tensorflow/python/summary/writer/writer.py in __init__(self, logdir, graph, max_queue, flush_secs, graph_def, filename_suffix, session)
    358     if context.executing_eagerly():
    359       raise RuntimeError(
--> 360           "tf.summary.FileWriter is not compatible with eager execution. "
    361           "Use tf.contrib.summary instead.")
    362     if session is not None:

RuntimeError: tf.summary.FileWriter is not compatible with eager execution. Use tf.contrib.summary instead.
```

**Comment by jvishnuvardhan** [comment]
@lendle Could you try this to disable eager execution in 2.0
import tensorflow as tf
tf.compat.v1.disable_eager_execution()
tf.estimator.ProfilerHook(10)

Thanks!

**Comment by lendle** [comment]
@jvishnuvardhan `tf.compat.v1.disable_eager_execution()` worked, and then I was able to use the ProfilerHook with the estimator api. 

I was also able to get something working by copying the implementation of ProfilerHook and changing `self._file_writer = SummaryWriterCache.get(output_dir)` to `self._file_writer = create_file_writer(output_dir, name='my_profiler')` in the constructor and removing `self._file_writer.add_run_metadata` in `after_run`....Doesn't look like anything else references `_file_writer`, so that's probably not actually doing anything at all, but I was at least able to get tracing information from the profiler in eager mode that way.

**Comment by jvishnuvardhan** [comment]
@lendle looks like original issue was resolved and this is another issue. Could you open a new issue and add more details about the issue and its context. Please also mention overall goal. Thanks!

**Comment by lendle** [comment]
@jvishnuvardhan as far as I can tell the only way to disable eager execution is with `tf.compat.v1.disable_eager_execution()`. If I understand correctly, the purpose of the `tf.compat.v1` module is to help transition from legacy v1 to v2, right?

Given that `tf.estimator.ProfilerHook` is in the public API in TF 2.0, and it cannot be used without also using a legacy api, I would argue that this is not fixed.

**Comment by jvishnuvardhan** [comment]
@reedwm Could you please take a look at this issue? Thanks!

**Comment by EliotAndres** [comment]
I also have this problem. Moreover, since `RunOptions` has been moved to compat.v1, there seem to be no proper way of generating a profiling timeline in TensorFlow 2.

**Comment by reedwm** [comment]
[`tf.train.ProfilerHook`](https://github.com/tensorflow/tensorflow/blob/c4b61514434646defb4c17ab10afe0e83fb9e969/tensorflow/python/training/basic_session_run_hooks.py#L979) is only exposed in Tensorflow 1. But, [`tf.estimator.ProfilerHook`](https://github.com/tensorflow/estimator/blob/b47b26cb0ecbd816e2e47146636caf58c54e57d7/tensorflow_estimator/python/estimator/hooks/basic_session_run_hooks.py#L49) is also exposed in TensorFlow 2, despite not working with TensorFlow 2. Either `tf.estimator.ProfilerHook` should be made to work in TF 2, or should not be exposed in TF 2.

@rchao  can you take a look?

**Comment by rchao** [comment]
I think we should make it work in TF2. Will take a look what the options are here.

**Comment by eecshope** [comment]
The bug still exists in tensorflow==2.0.0-beta1
### System information

- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution: Ubuntu 18.04 
- TensorFlow installed from (source or binary): via pip
- TensorFlow version (use command below): tf.__git_version__ : 'v2.0.0-beta0-17-g8e423e3', version -- - tensorflow==2.0.0-beta1
- Python version: 3.6
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: 10.0
- GPU model and memory: NVIDIA Titan XP

### Code to reproduce the issue
    profiler_hook = tf.estimator.ProfilerHook(save_steps=2000, output_dir=MODEL_DIR + '/profiler/', show_memory=True)
    train_spec = tf.estimator.TrainSpec(lambda: train_input_fn(train_raw, BATCH_SIZE, EPOCH, TRAIN_BUFFER_SIZE),  hooks=[profiler_hook])
    eval_spec = tf.estimator.EvalSpec(lambda: test_input_fn(test_raw, BATCH_SIZE),
                                      throttle_secs=100)
    tf.estimator.train_and_evaluate(estimator, train_spec, eval_spec)
    model.summary()
### Other Info / Logs
The full traceback is listed as follows:
```
Traceback (most recent call last):
  File "main.py", line 124, in <module>
    main()
  File "main.py", line 110, in main
    profiler_hook = tf.estimator.ProfilerHook(save_steps=2000, output_dir=MODEL_DIR + '/profiler/', show_memory=True)
  File "/data/wangzejun/anadonda/envs/tf2.0/lib/python3.7/site-packages/tensorflow/python/training/basic_session_run_hooks.py", line 1024, in __init__
    self._file_writer = SummaryWriterCache.get(output_dir)
  File "/data/wangzejun/anadonda/envs/tf2.0/lib/python3.7/site-packages/tensorflow/python/summary/writer/writer_cache.py", line 63, in get
    logdir, graph=ops.get_default_graph())
  File "/data/wangzejun/anadonda/envs/tf2.0/lib/python3.7/site-packages/tensorflow/python/summary/writer/writer.py", line 360, in __init__
    "tf.summary.FileWriter is not compatible with eager execution. "
RuntimeError: tf.summary.FileWriter is not compatible with eager execution. Use tf.contrib.summary instead.
```

The instruction from compat.v1 still works fine, which makes the code a little bit ugly.  <br>
Thank for your attention.

**Comment by jvishnuvardhan** [comment]
@eecshope I could reproduce the issue with `!pip install tf-nightly-2.0-preview`. Here is a [gist](https://colab.sandbox.google.com/gist/jvishnuvardhan/1d4a46f570cf5c2447d45ac48661b1e0/untitled466.ipynb) with !pip install `tf-nightly-2.0-preview`. Thanks!

**Comment by Flamefire** [comment]
I'd also be curious how to use this with `model.fit` to generate a Chrome Trace.

**Comment by sseveran** [comment]
It is also not compatible with tf.distribute.MirroredStrategy.
```
2019-11-01 09:03:00.713665: I tensorflow/core/profiler/lib/profiler_session.cc:184] Profiler session started.
2019-11-01 09:03:00.714991: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcupti.so.10.0
2019-11-01 09:03:02.435473: I tensorflow/core/platform/default/device_tracer.cc:588] Collecting 2969 kernel records, 109 memcpy records.
Traceback (most recent call last):
  File "/home/steve/source/core/python/sonia/models/model/train.py", line 26, in <module>
    ds.triplet_training()
  File "/home/steve/source/core/python/sonia/models/model/model.py", line 160, in triplet_training
    steps=None))
  File "/home/steve/venv/sonia/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/training.py", line 473, in train_and_evaluate
    return executor.run()
  File "/home/steve/venv/sonia/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/training.py", line 613, in run
    return self.run_local()
  File "/home/steve/venv/sonia/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/training.py", line 714, in run_local
    saving_listeners=saving_listeners)
  File "/home/steve/venv/sonia/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 370, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/steve/venv/sonia/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1158, in _train_model
    return self._train_model_distributed(input_fn, hooks, saving_listeners)
  File "/home/steve/venv/sonia/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1221, in _train_model_distributed
    self._config._train_distribute, input_fn, hooks, saving_listeners)
  File "/home/steve/venv/sonia/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1332, in _actual_train_model_distributed
    saving_listeners)
  File "/home/steve/venv/sonia/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1493, in _train_with_estimator_spec
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/home/steve/venv/sonia/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 754, in run
    run_metadata=run_metadata)
  File "/home/steve/venv/sonia/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 1259, in run
    run_metadata=run_metadata)
  File "/home/steve/venv/sonia/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 1360, in run
    raise six.reraise(*original_exc_info)
  File "/home/steve/venv/sonia/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/steve/venv/sonia/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 1345, in run
    return self._sess.run(*args, **kwargs)
  File "/home/steve/venv/sonia/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 1418, in run
    run_metadata=run_metadata)
  File "/home/steve/venv/sonia/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 1176, in run
    return self._sess.run(*args, **kwargs)
  File "/home/steve/venv/sonia/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 959, in run
    run_metadata.ParseFromString(compat.as_bytes(proto_data))
google.protobuf.message.DecodeError: Error parsing message

Process finished with exit code 1```

**Comment by wangsiyu** [comment]
> It is also not compatible with tf.distribute.MirroredStrategy.
> 
> ```
> 2019-11-01 09:03:00.713665: I tensorflow/core/profiler/lib/profiler_session.cc:184] Profiler session started.
> 2019-11-01 09:03:00.714991: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcupti.so.10.0
> 2019-11-01 09:03:02.435473: I tensorflow/core/platform/default/device_tracer.cc:588] Collecting 2969 kernel records, 109 memcpy records.
> Traceback (most recent call last):
>   File "/home/steve/source/core/python/sonia/models/model/train.py", line 26, in <module>
>     ds.triplet_training()
>   File "/home/steve/source/core/python/sonia/models/model/model.py", line 160, in triplet_training
>     steps=None))
>   File "/home/steve/venv/sonia/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/training.py", line 473, in train_and_evaluate
>     return executor.run()
>   File "/home/steve/venv/sonia/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/training.py", line 613, in run
>     return self.run_local()
>   File "/home/steve/venv/sonia/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/training.py", line 714, in run_local
>     saving_listeners=saving_listeners)
>   File "/home/steve/venv/sonia/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 370, in train
>     loss = self._train_model(input_fn, hooks, saving_listeners)
>   File "/home/steve/venv/sonia/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1158, in _train_model
>     return self._train_model_distributed(input_fn, hooks, saving_listeners)
>   File "/home/steve/venv/sonia/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1221, in _train_model_distributed
>     self._config._train_distribute, input_fn, hooks, saving_listeners)
>   File "/home/steve/venv/sonia/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1332, in _actual_train_model_distributed
>     saving_listeners)
>   File "/home/steve/venv/sonia/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1493, in _train_with_estimator_spec
>     _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
>   File "/home/steve/venv/sonia/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 754, in run
>     run_metadata=run_metadata)
>   File "/home/steve/venv/sonia/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 1259, in run
>     run_metadata=run_metadata)
>   File "/home/steve/venv/sonia/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 1360, in run
>     raise six.reraise(*original_exc_info)
>   File "/home/steve/venv/sonia/lib/python3.6/site-packages/six.py", line 693, in reraise
>     raise value
>   File "/home/steve/venv/sonia/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 1345, in run
>     return self._sess.run(*args, **kwargs)
>   File "/home/steve/venv/sonia/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 1418, in run
>     run_metadata=run_metadata)
>   File "/home/steve/venv/sonia/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 1176, in run
>     return self._sess.run(*args, **kwargs)
>   File "/home/steve/venv/sonia/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 959, in run
>     run_metadata.ParseFromString(compat.as_bytes(proto_data))
> google.protobuf.message.DecodeError: Error parsing message
> 
> Process finished with exit code 1```
> ```

I am facing the same issue. Any update?

**Comment by sseveran** [comment]
@wangsiyu No. I still find it incomprehensible that TF 2.0 shipped without profiling working properly.

**Comment by airMeng** [comment]
facing the same problem. tf.estimator.profilehook must work in eager mode. but in eager mood, I get

> RuntimeError: tf.summary.FileWriter is not compatible with eager execution. Use tf.contrib.summary instead.

**Comment by Ir1d** [comment]
Is there any solution of this? Facing this same problem too.

**Comment by rchao** [comment]
Discussed with @reedwm and we think the best solution is to un-export ProfilerHook from TF2. Will send out a fix for this.

**Comment by eyalhir74** [comment]
@rchao  - What would be the replacement for the ProfilerHook in TF2? is it possible to see the chromo json logs in another way?

**Comment by rchao** [comment]
@eyalhir74 - training with profiling can be enabled with using [`tf.keras.callbacks.TensorBoard(profile_batch=...)`](https://www.tensorflow.org/api_docs/python/tf/keras/callbacks/TensorBoard?version=nightly). Can you check if this fits your needs?
