### ISSUE TITLE
tensorflow wont start windows 10 python 3.7.3

### ISSUE THREAD

**Issue by NagarjunaIkiu** [tensorflow/tensorflow#27628]
File "<ipython-input-2-0786882784e8>", line 1, in <module>
    runfile('C:/Users/Christophe/.spyder-py3/temp.py', wdir='C:/Users/Christophe/.spyder-py3')

  File "e:\program files\python3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 824, in runfile
    execfile(filename, namespace)

  File "e:\program files\python3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/Christophe/.spyder-py3/temp.py", line 7, in <module>
    import tensorflow as tf

  File "e:\program files\python3\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import

  File "e:\program files\python3\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow

  File "e:\program files\python3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)

ImportError: Traceback (most recent call last):
  File "e:\program files\python3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "e:\program files\python3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "e:\program files\python3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "e:\program files\python3\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "e:\program files\python3\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

Failed to load the native TensorFlow runtime.

**Comment by achandraa** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by NagarjunaIkiu** [comment]
Windows 10 it works in spyder but not in pycharm, installed the modules in pycharm downgraded to python 6, have my scripts folder in documents on other drive, maybe something to do  with environments? kinda new to scripting.

**Comment by NagarjunaIkiu** [comment]
tensorflow version 1.13.1

**Comment by NagarjunaIkiu** [comment]
can I maybe create environment in script folder, and how would I do that?

**Comment by NagarjunaIkiu** [comment]
Now I get this:
C:\Users\Christophe\Anaconda3\python.exe E:/Documents/PythonScripts/tensor.py
Traceback (most recent call last):
  File "E:/Documents/PythonScripts/tensor.py", line 1, in <module>
    import tensorflow as tf
  File "C:\Users\Christophe\Anaconda3\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\Christophe\Anaconda3\lib\site-packages\tensorflow\python\__init__.py", line 47, in <module>
    import numpy as np
  File "C:\Users\Christophe\Anaconda3\lib\site-packages\numpy\__init__.py", line 140, in <module>
    from . import _distributor_init
  File "C:\Users\Christophe\Anaconda3\lib\site-packages\numpy\_distributor_init.py", line 34, in <module>
    from . import _mklinit
ImportError: DLL load failed: The specified module could not be found.

Process finished with exit code 1

**Comment by NagarjunaIkiu** [comment]
This is the script i'm using:

import tensorflow as tf

mnist = tf.keras.datasets.mnist

(x_train, y_train),(x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(512, activation=tf.nn.relu),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation=tf.nn.softmax)
])
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(x_train, y_train, epochs=5)
model.evaluate(x_test, y_test)

**Comment by ymodak** [comment]
Can you import tensorflow successfully using the terminal?

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
