### ISSUE TITLE
Tensorflow speech commands error

### ISSUE THREAD

**Issue by harborinteractive** [tensorflow/tensorflow#27621]
<em>Im getting error when ı convert h5 file to tflite file in speech commands example</em>

**System information**
- Ubuntu 18.04

- TensorFlow version:1.10.0
- Python version:3.6.7
- Installed using pip
- CUDA/cuDNN version:
- GPU model and memory:

**
When I try to create tflite file Im getting that
https://github.com/tensorflow/examples/blob/master/lite/examples/speech_commands/android/README.md

My error:
(keras) eco@eco-1Y3-GNB1554A1I3:~/Masaüstü/yz/keras/ml/export$ python convert_keras_lite.py
WARNING:tensorflow:From convert_keras_lite.py:28: TocoConverter.from_keras_model_file (from tensorflow.contrib.lite.python.lite) is deprecated and will be removed in a future version.
Instructions for updating:
Use `lite.TFLiteConverter.from_keras_model_file` instead.
Traceback (most recent call last):
  File "convert_keras_lite.py", line 28, in <module>
    output_arrays)
  File "/home/eco/Masaüstü/yz/keras/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 306, in new_func
    return func(*args, **kwargs)
  File "/home/eco/Masaüstü/yz/keras/lib/python3.6/site-packages/tensorflow/contrib/lite/python/lite.py", line 556, in from_keras_model_file
    input_shapes, output_arrays)
  File "/home/eco/Masaüstü/yz/keras/lib/python3.6/site-packages/tensorflow/contrib/lite/python/lite.py", line 368, in from_keras_model_file
    keras_model = _keras.models.load_model(model_file)
  File "/home/eco/Masaüstü/yz/keras/lib/python3.6/site-packages/tensorflow/python/keras/engine/saving.py", line 230, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/home/eco/Masaüstü/yz/keras/lib/python3.6/site-packages/tensorflow/python/keras/engine/saving.py", line 310, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/home/eco/Masaüstü/yz/keras/lib/python3.6/site-packages/tensorflow/python/keras/layers/serialization.py", line 64, in deserialize
    printable_module_name='layer')
  File "/home/eco/Masaüstü/yz/keras/lib/python3.6/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 173, in deserialize_keras_object
    list(custom_objects.items())))
  File "/home/eco/Masaüstü/yz/keras/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 1292, in from_config
    process_layer(layer_data)
  File "/home/eco/Masaüstü/yz/keras/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 1278, in process_layer
    layer = deserialize_layer(layer_data, custom_objects=custom_objects)
  File "/home/eco/Masaüstü/yz/keras/lib/python3.6/site-packages/tensorflow/python/keras/layers/serialization.py", line 64, in deserialize
    printable_module_name='layer')
  File "/home/eco/Masaüstü/yz/keras/lib/python3.6/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 175, in deserialize_keras_object
    return cls.from_config(config['config'])
  File "/home/eco/Masaüstü/yz/keras/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1606, in from_config
    return cls(**config)
  File "/home/eco/Masaüstü/yz/keras/lib/python3.6/site-packages/tensorflow/python/keras/layers/core.py", line 330, in __init__
    self.activation = activations.get(activation)
  File "/home/eco/Masaüstü/yz/keras/lib/python3.6/site-packages/tensorflow/python/keras/activations.py", line 206, in get
    return deserialize(identifier)
  File "/home/eco/Masaüstü/yz/keras/lib/python3.6/site-packages/tensorflow/python/keras/activations.py", line 197, in deserialize
    printable_module_name='activation function')
  File "/home/eco/Masaüstü/yz/keras/lib/python3.6/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 193, in deserialize_keras_object
    function_name)
ValueError: Unknown activation function:relu6

**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ymodak** [comment]
Can you switch to latest stable TF version 1.13.1 and use [tflite converter](https://www.tensorflow.org/lite/convert/python_api#exporting_a_tfkeras_file_) instead.

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by DSKIM3** [comment]
I'm getting same error.
