### ISSUE TITLE
Passing a dictionary of tensors to py_function

### ISSUE THREAD

**Issue by eldar** [tensorflow/tensorflow#27679]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): YES
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian 9.0
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0.0 alpha
- Python version: 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

tf.data.Dataset supports dictionary as a valid type of its elements, which is convenient when your data source have multiple tensors and you want to assign a name to each of them. However if I want to manipulate these tensors by mapping the dataset to a tf.py_function, it complains that the dictionary is not compatible with the Tensor, even though its values are Tensors.

```python
import numpy as np
import tensorflow as tf


def make_dictionary(inp):
    out = {}
    out["image1"] = inp[0]
    out["image2"] = inp[1]
    out["image3"] = inp[2]
    return out


def process_data(data):
    print("image1", data["image1"])
    print("image2", data["image2"])
    print("image3", data["image3"])
    return 0.0


dataset = tf.data.Dataset.from_tensor_slices(np.arange(10))

dataset = tf.data.Dataset.zip((dataset, dataset, dataset))
dataset = dataset.map(lambda *stuff: make_dictionary(stuff))
# now each element in dataset is a dictionary
# processing the dictionary however is not supported by py_function:

dataset = dataset.map(
      lambda data: tf.py_function(
          process_data, [data], tf.float32))

for image in dataset.take(4):
    print(image)
```

The error I get is:
```
Traceback (most recent call last):
  File "/BS/eldar-3dshape/work/apps/miniconda3/envs/py36_tf20/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py", line 559, in make_tensor_proto
    str_values = [compat.as_bytes(x) for x in proto_values]
  File "/BS/eldar-3dshape/work/apps/miniconda3/envs/py36_tf20/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py", line 559, in <listcomp>
    str_values = [compat.as_bytes(x) for x in proto_values]
  File "/BS/eldar-3dshape/work/apps/miniconda3/envs/py36_tf20/lib/python3.6/site-packages/tensorflow/python/util/compat.py", line 61, in as_bytes
    (bytes_or_text,))
TypeError: Expected binary or unicode string, got {'image1': <tf.Tensor 'args_0:0' shape=() dtype=int64>, 'image2': <tf.Tensor 'args_1:0' shape=() dtype=int64>, 'image3': <tf.Tensor 'args_2:0' shape=() dtype=int64>}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/BS/eldar-3dshape/work/apps/miniconda3/envs/py36_tf20/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 471, in _apply_op_helper
    as_ref=input_arg.is_ref)
  File "/BS/eldar-3dshape/work/apps/miniconda3/envs/py36_tf20/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1251, in internal_convert_n_to_tensor
    ctx=ctx))
  File "/BS/eldar-3dshape/work/apps/miniconda3/envs/py36_tf20/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1186, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/BS/eldar-3dshape/work/apps/miniconda3/envs/py36_tf20/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 304, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/BS/eldar-3dshape/work/apps/miniconda3/envs/py36_tf20/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 245, in constant
    allow_broadcast=True)
  File "/BS/eldar-3dshape/work/apps/miniconda3/envs/py36_tf20/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 283, in _constant_impl
    allow_broadcast=allow_broadcast))
  File "/BS/eldar-3dshape/work/apps/miniconda3/envs/py36_tf20/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py", line 563, in make_tensor_proto
    "supported type." % (type(values), values))
TypeError: Failed to convert object of type <class 'dict'> to Tensor. Contents: {'image1': <tf.Tensor 'args_0:0' shape=() dtype=int64>, 'image2': <tf.Tensor 'args_1:0' shape=() dtype=int64>, 'image3': <tf.Tensor 'args_2:0' shape=() dtype=int64>}. Consider casting elements to a supported type.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tmp.py", line 28, in <module>
    lambda data: tf.py_function(
  File "/BS/eldar-3dshape/work/apps/miniconda3/envs/py36_tf20/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1012, in map
    return MapDataset(self, map_func, preserve_cardinality=True)
  File "/BS/eldar-3dshape/work/apps/miniconda3/envs/py36_tf20/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 2986, in __init__
    use_legacy_function=use_legacy_function)
  File "/BS/eldar-3dshape/work/apps/miniconda3/envs/py36_tf20/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 2388, in __init__
    self._function = wrapper_fn._get_concrete_function_internal()
  File "/BS/eldar-3dshape/work/apps/miniconda3/envs/py36_tf20/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 1319, in _get_concrete_function_internal
    *args, **kwargs)
  File "/BS/eldar-3dshape/work/apps/miniconda3/envs/py36_tf20/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 1313, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/BS/eldar-3dshape/work/apps/miniconda3/envs/py36_tf20/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 1580, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/BS/eldar-3dshape/work/apps/miniconda3/envs/py36_tf20/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 1512, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/BS/eldar-3dshape/work/apps/miniconda3/envs/py36_tf20/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py", line 694, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/BS/eldar-3dshape/work/apps/miniconda3/envs/py36_tf20/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 2381, in wrapper_fn
    ret = _wrapper_helper(*args)
  File "/BS/eldar-3dshape/work/apps/miniconda3/envs/py36_tf20/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 2326, in _wrapper_helper
    ret = func(*nested_args)
  File "tmp.py", line 29, in <lambda>
    process_data, [data], tf.float32))
  File "/BS/eldar-3dshape/work/apps/miniconda3/envs/py36_tf20/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 389, in eager_py_func
    return _internal_py_func(func=func, inp=inp, Tout=Tout, eager=True, name=name)
  File "/BS/eldar-3dshape/work/apps/miniconda3/envs/py36_tf20/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 278, in _internal_py_func
    input=inp, token=token, Tout=Tout, name=name)
  File "/BS/eldar-3dshape/work/apps/miniconda3/envs/py36_tf20/lib/python3.6/site-packages/tensorflow/python/ops/gen_script_ops.py", line 74, in eager_py_func
    "EagerPyFunc", input=input, token=token, Tout=Tout, name=name)
  File "/BS/eldar-3dshape/work/apps/miniconda3/envs/py36_tf20/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 502, in _apply_op_helper
    "%s that are invalid. Tensors: %s" % (prefix, values))
TypeError: Tensors in list passed to 'input' of 'EagerPyFunc' Op have types [<NOT CONVERTIBLE TO TENSOR>] that are invalid. Tensors: [{'image1': <tf.Tensor 'args_0:0' shape=() dtype=int64>, 'image2': <tf.Tensor 'args_1:0' shape=() dtype=int64>, 'image3': <tf.Tensor 'args_2:0' shape=() dtype=int64>}]
```

**Comment by sdll** [comment]
Any updates on this?

**Comment by jsimsa** [comment]
This is a limitation of `py_function` which only supports a list of `Tensor` inputs and I don't need see a straightforward way to extend its implementation to support dictionaries.

FWIW, you could deconstruct the dictionary structure ahead of invoking the `py_function`:

```
import tensorflow as tf

tf.enable_v2_behavior()

def deconstruct(x):
  return x['a'], x['b']

def process(*args):
  a, b = args
  return a + b

dataset = tf.data.Dataset.from_tensors({'a': 1, 'b': 2})
dataset = dataset.map(deconstruct)
dataset = dataset.map(lambda *args: tf.py_function(process, args, tf.int32))

for elem in dataset:
  print(elem.numpy())
```

**Comment by novog** [comment]
In a related feature request (Support Sparse Tensors in py_function, #27679), @alextp noted:

> I think now that we have compositetensor and typespec it should be straightforward to implement sparsetensor support in py_function by treating all composites generically.

Could the same mechanism provide a path to implementing dictionary handling by `py_function`?

**Comment by jsimsa** [comment]
Not until:
a) `CompositeTensor` inputs are supported to `py_function`
b) a subclass of `CompositeTensor` exists that can represent a dictionary

**Comment by edloper** [comment]
Most APIs that support composite tensors also support nested structures (as defined by [tf.nest](https://www.tensorflow.org/api_docs/python/tf/nest).  In particular, the tf.nest functions include an "expand_composites" argument that tells tf.nest that it should treat composite tensors as nested structures.

Therefore, we don't need a CompositeTensor for dictionaries -- we can just use dictionaries as is.  But what we do ned is to extend py_function to use tf.nest to do appropriate flattening and repacking of tensors at the input & output boundaries.  (Using "expand_composites=True" will ensure that this supports both "normal" nested structures and composite tensors.)

**Comment by edloper** [comment]
Here's an example showing how the existing py_function could be wrapped to handle nested structures, including "normal" nested structures like dictionaries or tuples and also composite tensors:

```
def new_py_function(func, inp, Tout, name=None):
  def wrapped_func(*flat_inp):
    reconstructed_inp = tf.nest.pack_sequence_as(inp, flat_inp,
                                                 expand_composites=True)
    out = func(*reconstructed_inp)
    return tf.nest.flatten(out, expand_composites=True)
  flat_Tout = tf.nest.flatten(Tout, expand_composites=True)
  flat_out = tf.py_function(
      func=wrapped_func, 
      inp=tf.nest.flatten(inp, expand_composites=True),
      Tout=[_tensor_spec_to_dtype(v) for v in flat_Tout],
      name=name)
  spec_out = tf.nest.map_structure(_dtype_to_tensor_spec, Tout, 
                                   expand_composites=True)
  out = tf.nest.pack_sequence_as(spec_out, flat_out, expand_composites=True)
  return out

def _dtype_to_tensor_spec(v):
  return tf.TensorSpec(None, v) if isinstance(v, tf.dtypes.DType) else v

def _tensor_spec_to_dtype(v):
  return v.dtype if isinstance(v, tf.TensorSpec) else v
```

(Warning: I tested this out on your example, but haven't done thorough testing, so there might be a bug or two in this code; but it should give you the basic idea of what needs to be done.)

**Comment by jvishnuvardhan** [comment]
@eldar Is this still an issue for you? did you try the suggestions from @jsimsa @edloper .
Can you try recently released `TF2.0` and let us know whether the issue persists with the latest version? Thanks!

**Comment by novog** [comment]
I just tested it using v2.0, and it still isn't possible to supply dictionaries to a `py_function` as inputs. Attempting to do so still results in:

> TypeError: Tensors in list passed to 'input' of 'EagerPyFunc' Op have types [<NOT CONVERTIBLE TO TENSOR>] that are invalid.

@edloper's workaround seems like it may work (at least for the simple case that I have tried it with so far), but I still believe that py_function itself should be modified to be able to accept (and return, for that matter) dictionaries and other composite tensors.

**Comment by edloper** [comment]
@novog If you're interested in submitting a pull request that updates `py_function` to support nested structures, it looks like you could probably fold the suggestions I made above into [_internal_py_func](https://github.com/tensorflow/tensorflow/blob/r2.0/tensorflow/python/ops/script_ops.py#L251).  (You'd need to add tests etc. as well.)

**Comment by novog** [comment]
@edloper Thanks again.

Your example code looks like it might be able to handle nested return types, but I can't make it work with a function that returns a `Dict[str, tf.Tensor]`. Should this work, and if so, what should be specified for Tout?

**Comment by edloper** [comment]
You can use something like: Tout={"foo": tf.int32, "bar": tf.float32}.

Note that you'll need to know the keys of the dict and the types of the tensor values statically.  In particular, if we're in graph mode, then we need to know what this structure looks like statically, so we can create the output tensors.  If the size/set of keys in the dict can change each time the python function is called, then there's no sensible way to hook it up to the output.

In the general case, you can use nested structure in your output, but only if the "structure" part of that nested structure is fixed and known in advance.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
It has been 29 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
It has been 44 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
We are closing this issue for now due to lack of activity. Please comment if this is still an issue for you. Thanks!

**Comment by minhtriet** [comment]
So, I created a patch thanks to @edloper suggestion [here](https://github.com/minhtriet/tensorflow/blob/master/tensorflow/python/ops/script_ops.py#L373). That is the only change

```
2019-12-14 21:35:12.013946: W tensorflow/core/framework/op_kernel.cc:1622] OP_REQUIRES failed at iterator_ops.cc:929 : Invalid argument: {{function_node __inference_Dataset_map_<lambda>_19}} 0-th value returned by pyfunc_0 is double, but expects float
	 [[{{node PyFuncStateless}}]]
Traceback (most recent call last):
  File "C:\Users\cool\Miniconda3\envs\tf_contrib_conda\lib\site-packages\tensorflow_core\python\data\ops\iterator_ops.py", line 666, in next
    return self._next_internal()
  File "C:\Users\cool\Miniconda3\envs\tf_contrib_conda\lib\site-packages\tensorflow_core\python\data\ops\iterator_ops.py", line 651, in _next_internal
    output_shapes=self._flat_output_shapes)
  File "C:\Users\cool\Miniconda3\envs\tf_contrib_conda\lib\site-packages\tensorflow_core\python\ops\gen_dataset_ops.py", line 2672, in iterator_get_next_sync
    _six.raise_from(_core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: {{function_node __inference_Dataset_map_<lambda>_19}} 0-th value returned by pyfunc_0 is double, but expects float
	 [[{{node PyFuncStateless}}]] [Op:IteratorGetNextSync]
```
`pyfunc_0` returns a double, but expects float, but I cannot debug this function. Could someone give me a pointer? Thank you

**Comment by alextp** [comment]
Add a tf.cast?

**Comment by Ceceu** [comment]
Hello @edloper,

I did like you pointed out in a similar case:
```python
Tout={"input_ids": tf.int32, "attention_mask": tf.int32}, {"input_ids": tf.int32, "attention_mask": tf.int32}
```
But I got the following error:

```python
ValueError: Attempt to convert a value 
({
'input_ids': [101, 13366, 2131, 1035, 6819, 2094, 1035, 2013, 1035, 24471, 2140, 1006, 24471, 2140, 1007, 102], 
'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
}) 
with an unsupported type (<class 'dict'>) to a Tensor.
```

Any suggestion?

**Comment by jeromerg** [comment]
I was just confronted to the same need to pass multiple tensor in single structure and found that it works with *namedtuple*. It may be a substitute.

```
@tf.function
def h(ab):
    print("AB")
    return ab.a + ab.b

AB = namedtuple("AB", ("a", "b"))
ab = AB(tf.constant(1), tf.constant(3))
h(ab) # --> prints AB 
h(ab) # --> no print
ab = AB(tf.constant(1), tf.constant(4))
h(ab) # --> no print and calculation is correct 
```

**Comment by edloper** [comment]
@jeromerg This issue was about passing values in & out of `tf.py_function`, and not about `tf.function`.  Passing nested dictionaries, namedtules, lists, and tuples of tensors in & out of `tf.function` should work fine.

**Comment by jeromerg** [comment]
@edloper thank you. indeed sorry. I remove my feedback

**Comment by edloper** [comment]
@Ceceu The following works fine for me, using the `new_py_function` defined above:

```
def my_function(x):
  return ({"input_ids": x, "atention_mask": x},
          {"input_ids": x, "atention_mask": x})
  
new_py_function(my_function, [tf.constant([5, 6, 7])], Tout=(
    {"input_ids": tf.int32, "attention_mask": tf.int32},
    {"input_ids": tf.int32, "attention_mask": tf.int32}))
```

**Comment by ismael-elatifi** [comment]
@edloper Thanks a lot for your new_py_function, which very very useful !!
It should definitely be integrated in Tensorflow ! 
I used it to pass input and output dicts, add new data to the output dict and return the 2 dicts, like this :
```
ds = ds.map(lambda dict_in, dict_out: new_py_function(my_py_func_adding_data,
                                                                                         inp=[(dict_in, dict_out)], 
										         Tout=({"img": tf.float32}, {"output1": tf.float32,
													                          "output2": tf.string})))
```

**Comment by murdockhou** [comment]
```
def tf_parser_func(img_id):
    (dict1, dict2) = tf.py_function(
        func = self.parser_func, 
        inp = [img_id],
        Tout = ({'input_1':tf.float32}, {'classification':tf.float32,'regression':tf.float32})
    )
    return dict1, dict2

def parser_func(img_id):
    if type(img_id) != int:
        img_id = int(img_id.numpy())
        assert type(img_id) == int 
    
    image = load_image(img_id) # get image based img_id
    annos = load_annotations(img_id) # get annos based img_id

    inputs, cls_targets, reg_targets = compute_inputs_targets(image, annos) # generate inputs and labels

    return ({'input_1':inputs}, {'classification':cls_targets,'regression':reg_targets})

def get_dataset(imgae_ids):
    dataset = tf.data.Dataset.from_tensor_slices(image_ids) # create dataset from a list
    dataset = dataset.map(tf_parser_func, num_parallel_calls=tf.data.experimental.AUTOTUNE)
    dataset = dataset.batch(1, drop_remainder=True).repeat(1)
    dataset = dataset.prefetch(buffer_size=tf.data.experimental.AUTOTUNE)
    return dataset
```

@ismael-elatifi  And could you help me find out where is wrong in above code? The dataset that I want to make is create a input and two ouput, and I want make every output has a name so I can pass this dataset into keras model.fit func.
