### ISSUE TITLE
KeyError in tensorflow\contrib\layers\python\layers\feature_column.py

### ISSUE THREAD

**Issue by Abonnen** [tensorflow/tensorflow#27683]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):  yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): win10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.13
- Python version: 3.6.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: CUDA 10.0 cuDNN 7.4.2
- GPU model and memory: GeForce GTX 960M totalMemory: 4.00GiB freeMemory: 3.34GiB

**Describe the current behavior**
Here is my code, I use a random forest estimator 

`feature_col = [real_valued_column(column_name="x", dimension=38)]`
`model = tf_random_forest.TensorForestEstimator(
    hparams,
    model_dir=dataset_path,
    feature_columns=feature_col,
    report_feature_importances=True)`

I have 38 features, when I train the model, I got a KeyError.

> Traceback (most recent call last):
  File "tf_dataset.py", line 130, in <module>
    model.train(input_fn=train_input_fn, steps=num_steps)
  File "D:\venv\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 358, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "D:\venv\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1124, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "D:\venv\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1154, in _train_model_default
    features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
  File "D:\venv\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1112, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "D:\venv\project\Malicious_TLS_Detection\machine_learning\tf_random_forest.py", line 162, in _model_fn
    layers.transform_features(features, feature_columns))
  File "D:\venv\lib\site-packages\tensorflow\contrib\layers\python\layers\feature_column_ops.py", line 656, in transform_features
    transformer.transform(column)
  File "D:\venv\lib\site-packages\tensorflow\contrib\layers\python\layers\feature_column_ops.py", line 848, in transform
    feature_column.insert_transformed_feature(self._columns_to_tensors)
  File "D:\venv\lib\site-packages\tensorflow\contrib\layers\python\layers\feature_column.py", line 1873, in insert_transformed_feature
    input_tensor = self._normalized_input_tensor(columns_to_tensors[self.name])
KeyError: 'x'

I followed the instructions below, but I got `KeyError: ''`
[KeyError_stackoverflow](https://stackoverflow.com/questions/39687554/keyerror-in-tensorflow-when-calling-predict-on-trained-model)

whatever I changed the column name, I always got a KeyError. Can someone explain why?

**Comment by achandraa** [comment]
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!
