### ISSUE TITLE
Failed to load the native TensorFlow runtime, Ubuntu 16.04, in virtualenv 

### ISSUE THREAD

**Issue by RatheeshRK** [tensorflow/tensorflow#27695]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Ubuntu 16.04
- TensorFlow installed from (source or binary): binary, using  pip3 install --upgrade --ignore-installed tensorflow-gpu==1.5

- TensorFlow version:1.5
- Python version: tried in both Python 2.7 and 3.5
- Installed using virtualenv? pip? conda?: virtualenv
- CUDA/cuDNN version: CUDA 10.0. cuDNN: cuDNN v7.5.0 (Feb 21, 2019), for CUDA 10.0
- GPU model and memory: NVIDIA TITAN Xp

**Describe the problem**

I**nstalled Tensorflow and tried to run it via python, and using "import tensorflow as tf". The error message details are shared below.**

Python 3.5.2 (default, Nov 12 2018, 13:43:14) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "/home/rrku16sys3/venv/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/rrku16sys3/venv/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/rrku16sys3/venv/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/rrku16sys3/venv/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/rrku16sys3/venv/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rrku16sys3/venv/lib/python3.5/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/home/rrku16sys3/venv/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/rrku16sys3/venv/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/rrku16sys3/venv/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/rrku16sys3/venv/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/rrku16sys3/venv/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/rrku16sys3/venv/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/rrku16sys3/venv/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
>>> 

**Need help.**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by armando-fandango** [comment]
seems like version 1.5 you are trying to install is looking for cublas 9.0. Did you install cublas 9.0 ? Install from here : https://developer.nvidia.com/cublas

**Comment by ymodak** [comment]
Please switch to cuda 9.0 since TF 1.5 pre built binaries support cuda 9.0 and cudnn 7. Also take a look at [release notes](https://github.com/tensorflow/tensorflow/blob/r1.5/RELEASE.md#breaking-changes) to know more.
