### ISSUE TITLE
Bug for tf.data.experimental.TFRecordWriter(filename)

### ISSUE THREAD

**Issue by eecshope** [tensorflow/tensorflow#27701]
Thanks for your attention! I'm using Windows and my tensorflow version is 1.13.1 installed using pip, and the following issue occurred: when I was testing the API tf.data.experimental.TFRecordWriter with the folloing codes:
```
filename = 'hello'
writer = tf.data.experimental.TFRecordWriter(filename)
```
my interpreter raised the following error information:

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "D:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\data\experimental\ops\writers.py", line 35, in __init__
    filename, dtypes.string, name="filename")
  File "D:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py", line 1039, in convert_to_tensor
    return convert_to_tensor_v2(value, dtype, preferred_dtype, name)
  File "D:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py", line 1097, in convert_to_tensor_v2
    as_ref=False)
  File "D:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py", line 1175, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "D:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\framework\constant_op.py", line 304, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "D:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\framework\constant_op.py", line 245, in constant
    allow_broadcast=True)
  File "D:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\framework\constant_op.py", line 283, in _constant_impl
    allow_broadcast=allow_broadcast))
  File "D:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\framework\tensor_util.py", line 501, in make_tensor_proto
    (dtype, nparray.dtype, values))
TypeError: Incompatible types: <dtype: 'string'> vs. object. Value is hello
```
I can't quite understand the difference between the type of 'hello' and "<dtype:'string'>". Then I tried the API tf.python_io.TFRecordWriter(filename) with the following codes:
```
tf.python_io.TFRecordWriter(filename)
```
no error information raised. 
So I'm pulling the issue to look for your help. Thanks for your time and attention again.

**Comment by amanp592** [comment]
@eecshope i ran this `filename = 'hello'
writer = tf.data.experimental.TFRecordWriter(filename)`
and my system didn't gave any error!!

Can you tell me your system specs like what tensorflow version you're using and everything?

**Comment by eecshope** [comment]
My system is Windows10 with python( version 3.7) installed using anaconda3. My TensorFlow version is 1.13.1. I ran the test program using the console provided by PyCharm Profession

**Comment by ymodak** [comment]
I was not able to reproduce the error reported using [google colab](https://colab.sandbox.google.com).  Please try using google colab or terminal. I suspect it is an ide issue. You can also try [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.Thanks!
