### ISSUE TITLE
[TF 2.0] Build issue for r2.0 branch

### ISSUE THREAD

**Issue by osanwe** [tensorflow/tensorflow#27708]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Linux Ubuntu 16.04
- TensorFlow installed from (source or binary):
Source
- TensorFlow version:
Branch r2.0
- Python version:
3.5.6 (from Anaconda)
- Installed using virtualenv? pip? conda?:
miniconda
- Bazel version (if compiling from source):
0.24.0
- GCC/Compiler version (if compiling from source):
5.4.0
- CUDA/cuDNN version:
CPU version
- Android SDK build tools version
28.0.3

**Describe the problem**

While building TensorFlow from `r2.0` branch the build fails because of problems with Basel build files (it seems like this).

**Provide the exact sequence of commands / steps that you executed before running into the problem**

`bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package`

**Any other info / logs**
```
DEBUG: Rule 'build_bazel_rules_swift' indicated that a canonical reproducible form can be obtained by modifying arguments commit = "001736d056d7eae20f1f4da41bc9e6f036857296", shallow_since = "1547844730 -0800" and dropping ["tag"]
DEBUG: /home/p.vytovtov/.cache/bazel/_bazel_p.vytovtov/bd2de6272d8995218e0b1ae22a8f3506/external/build_bazel_rules_apple/apple/repositories.bzl:35:5: 
WARNING: `build_bazel_rules_apple` depends on `bazel_skylib` loaded from https://github.com/bazelbuild/bazel-skylib.git (tag 0.6.0), but we have detected it already loaded into your workspace from None (tag None). You may run into compatibility issues. To silence this warning, pass `ignore_version_differences = True` to `apple_rules_dependencies()`.

ERROR: /home/p.vytovtov/.cache/bazel/_bazel_p.vytovtov/bd2de6272d8995218e0b1ae22a8f3506/external/hwloc/BUILD.bazel:189:54: The `+` operator for dicts is deprecated and no longer supported. Please use the `update` method instead. You can temporarily enable the `+` operator by passing the flag --incompatible_disallow_dict_plus=false
ERROR: /home/p.vytovtov/.cache/bazel/_bazel_p.vytovtov/bd2de6272d8995218e0b1ae22a8f3506/external/hwloc/BUILD.bazel:200:9: Traceback (most recent call last):
        File "/home/p.vytovtov/.cache/bazel/_bazel_p.vytovtov/bd2de6272d8995218e0b1ae22a8f3506/external/hwloc/BUILD.bazel", line 195
                template_rule(name = "include_private_hwloc_au...", <3 more arguments>)
        File "/home/p.vytovtov/.cache/bazel/_bazel_p.vytovtov/bd2de6272d8995218e0b1ae22a8f3506/external/hwloc/BUILD.bazel", line 199, in template_rule
                if_cuda(_INCLUDE_PRIVATE_HWLOC_AUTOIGEN_..., ...)
        File "/home/p.vytovtov/.cache/bazel/_bazel_p.vytovtov/bd2de6272d8995218e0b1ae22a8f3506/external/hwloc/BUILD.bazel", line 200, in if_cuda
                _INCLUDE_PRIVATE_HWLOC_AUTOIGEN_CONFIG_H_CUDA_SUBS
name '_INCLUDE_PRIVATE_HWLOC_AUTOIGEN_CONFIG_H_CUDA_SUBS' is not defined
ERROR: /home/p.vytovtov/Documents/tensorflow/tensorflow/core/BUILD:2319:1: Target '@hwloc//:hwloc' contains an error and its package is in error and referenced by '//tensorflow/core:lib_internal_impl'
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: Cannot compute config conditions
INFO: Elapsed time: 0.395s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded, 2 targets configured)
```

**Comment by Veronicacz** [comment]
I  have the same issues with you. Did you solve it?

**Comment by caissalover** [comment]
I build r2.0 with bazel 0.22.0 from the master with the following command.

bazel build --config=opt --config=cuda --config=v2 //tensorflow/tools/pip_package:build_pip_package

Built it today, worked. Guess the 2.0 branch is not fully stable. Tensorflow shows the version to be 1.13.1 but it's behavior will be like 2.0

**Comment by gunan** [comment]
It is possible that our branches do not become stable for all builds until the rc or final releases. Please try syncing with the tags on the branches if you need to build them.
