### ISSUE TITLE
error save keras model have Conv2D and dilation_rate=2 use tf.saved_model.save()

### ISSUE THREAD

**Issue by anhtu812** [tensorflow/tensorflow#27711]
install tensorflow2.0: pip install tf-nightly-2.0-preview==2.0.0.dev20190405

keras model have use Conv2D with dilation_rate=2.
tf.saved_model.save(model, OUTPUT_DIR) out error:

```
Traceback (most recent call last):
  File "convert_h5_to_tflite.py", line 146, in <module>
    tf.saved_model.save(model, OUTPUT_DIR)
  File "/docker_environment/home/docker/anaconda3/lib/python3.6/site-packages/tensorflow/python/saved_model/save.py", line 798, in save
    meta_graph_def, saveable_view, signatures)
  File "/docker_environment/home/docker/anaconda3/lib/python3.6/site-packages/tensorflow/python/saved_model/save.py", line 529, in _fill_meta_graph_def
    signatures = _generate_signatures(signature_functions, resource_map)
  File "/docker_environment/home/docker/anaconda3/lib/python3.6/site-packages/tensorflow/python/saved_model/save.py", line 407, in _generate_signatures
    function, mapped_inputs, resource_map)
  File "/docker_environment/home/docker/anaconda3/lib/python3.6/site-packages/tensorflow/python/saved_model/save.py", line 358, in _call_function_with_mapped_captures
    function.graph.captures, resource_map)
  File "/docker_environment/home/docker/anaconda3/lib/python3.6/site-packages/tensorflow/python/saved_model/save.py", line 280, in _map_captures_to_created_tensors
    .format(interior))
AssertionError: Tried to export a function which references untracked object Tensor("StatefulPartitionedCall/forward_6_1b_conv2D/stack:0", shape=(2, 2), dtype=int32).TensorFlow objects (e.g. tf.Variable) captured by functions must be tracked by assigning them to an attribute of a tracked object or assigned to an attribute of the main object directly.
```
dilation_rate=1 not error

**Comment by allenlavoie** [comment]
Could you put together code to reproduce? I tried exporting a Sequential that has a Conv2D with dilation_rate=2 and didn't run into the error:

```
root = tf.keras.Sequential([tf.keras.layers.Conv2D(filters=3, kernel_size=2, dilation_rate=2)])
initial_output = root.predict(tf.ones((1, 5, 5, 1)))
tf.saved_model.save(root, "/tmp/sm")
```

This was with 2.0.0-dev20190402 and at head.

**Comment by anhtu812** [comment]
code out error:
```
import tensorflow as tf


input_data = tf.keras.layers.Input(name='fts_input', shape=(None,None,3), dtype='float32')
inner = tf.keras.layers.Conv2D(filters=3, kernel_size=3, dilation_rate=2)(input_data)
model = tf.keras.models.Model(inputs=[input_data], outputs=inner)

initial_output = model.predict([tf.ones((2, 300, 300, 3))])
tf.saved_model.save(model, './')
```

**Comment by allenlavoie** [comment]
Thanks, that does reproduce nicely. I'll take a look.

**Comment by allenlavoie** [comment]
Ooo, I accidentally fixed this in https://github.com/tensorflow/tensorflow/commit/0d4d88c0514a6026fd90efc06e1adb5f8aa9255c

This is working for me in 2.0.0-dev20190416. I'll add a test to make sure it doesn't break in the future. Thanks for the report!
