### ISSUE TITLE
after freezing quantization aware training model , batchnorm create size node, cast node, and it's not supported to convert to tflite by tflite_convert

### ISSUE THREAD

**Issue by Sean0123456789** [tensorflow/tensorflow#27763]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):binary
- TensorFlow version (use command below):nightly(1.14)
- Python version:3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:9.2, cudnn7
- GPU model and memory:

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**
after freezing quantization aware training model, batchnorm create some new nodes, called size and cast, and they are not supported to convert to tllite by tflite_convert

2019-04-12 08:58:02.410692: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-04-12 08:58:02.430576: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2808000000 Hz
2019-04-12 08:58:02.431034: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55678114f760 executing computations on platform Host. Devices:
2019-04-12 08:58:02.431048: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
2019-04-12 08:58:02.648299: I tensorflow/core/grappler/devices.cc:53] Number of eligible GPUs (core count >= 8): 0 (Note: TensorFlow was not compiled with CUDA support)
2019-04-12 08:58:02.648376: I tensorflow/core/grappler/clusters/single_machine.cc:359] Starting new session
2019-04-12 08:58:02.902493: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:684] Optimization results for grappler item: graph_to_optimize
2019-04-12 08:58:02.902517: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:686]   model_pruner: Graph size after: 1684 nodes (-478), 1984 edges (-478), time = 14.17ms.
2019-04-12 08:58:02.902521: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:686]   implementation_selector: Graph size after: 1684 nodes (0), 1984 edges (0), time = 2.849ms.
2019-04-12 08:58:02.902525: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:686]   function_optimizer: Graph size after: 1684 nodes (0), 1984 edges (0), time = 2.628ms.
2019-04-12 08:58:02.902527: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:686]   constant folding: Graph size after: 1538 nodes (-146), 1834 edges (-150), time = 73.3ms.
2019-04-12 08:58:02.902530: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:686]   shape_optimizer: Graph size after: 1538 nodes (0), 1834 edges (0), time = 3.219ms.
2019-04-12 08:58:02.902533: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:686]   arithmetic_optimizer: Graph size after: 1085 nodes (-453), 1834 edges (0), time = 28.22ms.
2019-04-12 08:58:02.902536: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:686]   loop_optimizer: Graph size after: 1085 nodes (0), 1834 edges (0), time = 4.45ms.
2019-04-12 08:58:02.902539: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:686]   dependency_optimizer: Graph size after: 1081 nodes (-4), 1826 edges (-8), time = 9.244ms.
2019-04-12 08:58:02.902542: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:686]   memory_optimizer: Graph size after: 1081 nodes (0), 1826 edges (0), time = 30.734ms.
2019-04-12 08:58:02.902545: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:686]   model_pruner: Graph size after: 1081 nodes (0), 1826 edges (0), time = 4.841ms.
2019-04-12 08:58:02.902549: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:686]   implementation_selector: Graph size after: 1081 nodes (0), 1826 edges (0), time = 1.598ms.
2019-04-12 08:58:02.902553: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:686]   function_optimizer: Graph size after: 1081 nodes (0), 1826 edges (0), time = 1.4ms.
2019-04-12 08:58:02.902556: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:686]   constant folding: Graph size after: 1081 nodes (0), 1826 edges (0), time = 16.989ms.
2019-04-12 08:58:02.902559: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:686]   shape_optimizer: Graph size after: 1081 nodes (0), 1826 edges (0), time = 2.596ms.
2019-04-12 08:58:02.902562: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:686]   arithmetic_optimizer: Graph size after: 1081 nodes (0), 1826 edges (0), time = 15.685ms.
2019-04-12 08:58:02.902565: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:686]   dependency_optimizer: Graph size after: 1081 nodes (0), 1826 edges (0), time = 9.8ms.
Traceback (most recent call last):
  File "/home/syshang/anaconda3/envs/tfnightly0410/bin/tflite_convert", line 10, in <module>
    sys.exit(main())
  File "/home/syshang/anaconda3/envs/tfnightly0410/lib/python3.7/site-packages/tensorflow/lite/python/tflite_convert.py", line 448, in main
    app.run(main=run_main, argv=sys.argv[:1])
  File "/home/syshang/anaconda3/envs/tfnightly0410/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/syshang/anaconda3/envs/tfnightly0410/lib/python3.7/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/syshang/anaconda3/envs/tfnightly0410/lib/python3.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/home/syshang/anaconda3/envs/tfnightly0410/lib/python3.7/site-packages/tensorflow/lite/python/tflite_convert.py", line 444, in run_main
    _convert_model(tflite_flags)
  File "/home/syshang/anaconda3/envs/tfnightly0410/lib/python3.7/site-packages/tensorflow/lite/python/tflite_convert.py", line 192, in _convert_model
    output_data = converter.convert()
  File "/home/syshang/anaconda3/envs/tfnightly0410/lib/python3.7/site-packages/tensorflow/lite/python/lite.py", line 742, in convert
    **converter_kwargs)
  File "/home/syshang/anaconda3/envs/tfnightly0410/lib/python3.7/site-packages/tensorflow/lite/python/convert.py", line 410, in toco_convert_impl
    input_data.SerializeToString())
  File "/home/syshang/anaconda3/envs/tfnightly0410/lib/python3.7/site-packages/tensorflow/lite/python/convert.py", line 176, in toco_convert_protos
    "TOCO failed. See console for info.\n%s\n%s\n" % (stdout, stderr))
tensorflow.lite.python.convert.ConverterError: TOCO failed. See console for info.
2019-04-12 08:58:03.681724: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: Size
2019-04-12 08:58:03.688089: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 2
2019-04-12 08:58:03.688112: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 2
2019-04-12 08:58:03.688225: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: Size
2019-04-12 08:58:03.688236: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 2
2019-04-12 08:58:03.688242: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 2
2019-04-12 08:58:03.688274: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: Size
2019-04-12 08:58:03.688282: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 2
2019-04-12 08:58:03.688287: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 2
2019-04-12 08:58:03.688338: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: Size
2019-04-12 08:58:03.688345: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 2
2019-04-12 08:58:03.688351: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 2
2019-04-12 08:58:03.688521: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: Size
2019-04-12 08:58:03.688530: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 2
2019-04-12 08:58:03.688535: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 2
2019-04-12 08:58:03.688587: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: Size
2019-04-12 08:58:03.688595: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 2
2019-04-12 08:58:03.688600: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 2
2019-04-12 08:58:03.688631: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: Size
2019-04-12 08:58:03.688638: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 2
2019-04-12 08:58:03.688643: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 2
2019-04-12 08:58:03.688700: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: Size
2019-04-12 08:58:03.688708: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 2
2019-04-12 08:58:03.688713: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 2
2019-04-12 08:58:03.688745: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: Size
2019-04-12 08:58:03.688752: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 2
2019-04-12 08:58:03.688758: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 2
2019-04-12 08:58:03.688795: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: Size
2019-04-12 08:58:03.688802: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 2
2019-04-12 08:58:03.688808: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 2
2019-04-12 08:58:03.688838: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: Size
2019-04-12 08:58:03.688846: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 2
2019-04-12 08:58:03.688851: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 2
2019-04-12 08:58:03.688900: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: Size
2019-04-12 08:58:03.688907: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 2
2019-04-12 08:58:03.688913: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 2
2019-04-12 08:58:03.688942: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: Size
2019-04-12 08:58:03.688950: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 2
2019-04-12 08:58:03.688955: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 2
2019-04-12 08:58:03.688992: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: Size
2019-04-12 08:58:03.688999: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 2
2019-04-12 08:58:03.689005: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 2
2019-04-12 08:58:03.689034: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: Size
2019-04-12 08:58:03.689042: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 2
2019-04-12 08:58:03.689047: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 2
2019-04-12 08:58:03.689083: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: Size
2019-04-12 08:58:03.689091: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 2
2019-04-12 08:58:03.689096: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 2
2019-04-12 08:58:03.689126: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: Size
2019-04-12 08:58:03.689135: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 2
2019-04-12 08:58:03.689141: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 2
2019-04-12 08:58:03.689197: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: Size
2019-04-12 08:58:03.689209: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 2
2019-04-12 08:58:03.689222: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 2
2019-04-12 08:58:03.689265: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: Size
2019-04-12 08:58:03.689272: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 2
2019-04-12 08:58:03.689281: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 2
2019-04-12 08:58:03.689334: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: Size
2019-04-12 08:58:03.689342: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 2
2019-04-12 08:58:03.689347: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 2
2019-04-12 08:58:03.689378: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: Size
2019-04-12 08:58:03.689386: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 2
2019-04-12 08:58:03.689391: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 2
2019-04-12 08:58:03.689429: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: Size
2019-04-12 08:58:03.689436: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 2
2019-04-12 08:58:03.689441: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 2
2019-04-12 08:58:03.689472: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: Size
2019-04-12 08:58:03.689479: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 2
2019-04-12 08:58:03.689485: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 2
2019-04-12 08:58:03.689521: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: Size
2019-04-12 08:58:03.689529: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 2
2019-04-12 08:58:03.689534: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 2
2019-04-12 08:58:03.689564: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: Size
2019-04-12 08:58:03.689572: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 2
2019-04-12 08:58:03.689577: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 2
2019-04-12 08:58:03.689611: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: Size
2019-04-12 08:58:03.689618: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 2
2019-04-12 08:58:03.689624: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 2
2019-04-12 08:58:03.689666: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: Size
2019-04-12 08:58:03.689674: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 2
2019-04-12 08:58:03.689680: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 2
2019-04-12 08:58:03.689710: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: Size
2019-04-12 08:58:03.689717: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 2
2019-04-12 08:58:03.689723: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 2
2019-04-12 08:58:03.689759: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: Size
2019-04-12 08:58:03.689766: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 2
2019-04-12 08:58:03.689772: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 2
2019-04-12 08:58:03.689802: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: Size
2019-04-12 08:58:03.689809: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 2
2019-04-12 08:58:03.689814: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 2
2019-04-12 08:58:03.689850: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: Size
2019-04-12 08:58:03.689858: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 2
2019-04-12 08:58:03.689863: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 2
2019-04-12 08:58:03.689893: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: Size
2019-04-12 08:58:03.689901: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 2
2019-04-12 08:58:03.689906: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 2
2019-04-12 08:58:03.689942: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: Size
2019-04-12 08:58:03.689949: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 2
2019-04-12 08:58:03.689955: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 2
2019-04-12 08:58:03.690004: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: Size
2019-04-12 08:58:03.690012: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 2
2019-04-12 08:58:03.690018: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 2
2019-04-12 08:58:03.696569: F tensorflow/lite/toco/tooling_util.cc:1040] Check failed: array->has_shape() 
Fatal Python error: Aborted

Current thread 0x00007f8353181740 (most recent call first):
  File "/home/syshang/anaconda3/envs/tfnightly0410/lib/python3.7/site-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 33 in execute
  File "/home/syshang/anaconda3/envs/tfnightly0410/lib/python3.7/site-packages/absl/app.py", line 251 in _run_main
  File "/home/syshang/anaconda3/envs/tfnightly0410/lib/python3.7/site-packages/absl/app.py", line 300 in run
  File "/home/syshang/anaconda3/envs/tfnightly0410/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 40 in run
  File "/home/syshang/anaconda3/envs/tfnightly0410/lib/python3.7/site-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 59 in main
  File "/home/syshang/anaconda3/envs/tfnightly0410/bin/toco_from_protos", line 10 in <module>
Aborted (core dumped)

**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by Sean0123456789** [comment]
anyone can help?

**Comment by achandraa** [comment]
Did you get chance to look into some additional information in [FAQ](https://www.tensorflow.org/lite/guide/faq#why_are_some_operations_not_implemented_in_tensorflow_lite) or [experimental feature](https://www.tensorflow.org/lite/guide/ops_select). Let us know whether that helped or not.

**Comment by achandraa** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
