### ISSUE TITLE
Eager execution Blas SGEMM launch failed and GPU huge consumption.

### ISSUE THREAD

**Issue by zhangjh915** [tensorflow/tensorflow#27820]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No. Code based on [https://github.com/tensorflow/tensorflow/blob/r1.13/tensorflow/contrib/eager/python/examples/generative_examples/image_captioning_with_attention.ipynb](https://github.com/tensorflow/tensorflow/blob/r1.13/tensorflow/contrib/eager/python/examples/generative_examples/image_captioning_with_attention.ipynb).
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04.5 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Tensorflow docker image(tensorflow/tensorflow:latest-gpu-py3)
- TensorFlow version (use command below): 1.14.1-dev20190413
- Python version: 3.5.2(in docker image)
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.1
- GPU model and memory:  4 GeForce RTX 2080

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**
When eager execution is enabled, GPU resources are consumed significantly with only single calculation. Following are two simplified versions of the problem, the first one comes from [https://github.com/tensorflow/tensorflow/issues/25403 and the second one is my problem](https://github.com/tensorflow/tensorflow/issues/25403 and the second one is my problem).

1. 

**Describe the expected behavior**
Be able to run the scripts.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
docker run -it --runtime=nvidia --rm -e NVIDIA_VISIBLE_DEVICE="0,1,2,3" -v /usr/scratch:/usr/scratch tensorflow/tensorflow:latest-gpu-py3

1. import tensorflow as tf
tf.enable_eager_execution()
print(tf.matmul([[1., 2.],[3., 4.]], [[1., 2.],[3., 4.]]))
nvidia-smi

2. import tensorflow as tf
tf.enable_eager_execution()
image_model = tf.keras.applications.InceptionV3(include_top=False, weights='imagenet')
new_input = image_model.input
hidden_layer = image_model.layers[-1].output
image_features_extract_model = tf.keras.Model(new_input, hidden_layer)

x = tf.zeros([1, 299, 299, 3])  # just use a zero tensor instead of dataset tensor
image_features_extract_model(x)  # this will raise the error: "InternalError: Blas SGEMM launch failed : m=5329, n=80, k=64 [Op:Conv2D]"

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
1. vnivia-smi output before running code:
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.40.04    Driver Version: 418.40.04    CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 2080    Off  | 00000000:19:00.0 Off |                  N/A |
| 24%   39C    P0    41W / 215W |      0MiB /  7952MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 2080    Off  | 00000000:1A:00.0 Off |                  N/A |
| 24%   40C    P0    41W / 215W |      0MiB /  7952MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce RTX 2080    Off  | 00000000:67:00.0 Off |                  N/A |
| 22%   43C    P0    51W / 215W |      0MiB /  7952MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GeForce RTX 2080    Off  | 00000000:68:00.0 Off |                  N/A |
| 14%   45C    P0     1W / 215W |      0MiB /  7951MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
nvidia-smi after running the code:
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.40.04    Driver Version: 418.40.04    CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 2080    Off  | 00000000:19:00.0 Off |                  N/A |
| 24%   41C    P2    42W / 215W |   7633MiB /  7952MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 2080    Off  | 00000000:1A:00.0 Off |                  N/A |
| 23%   43C    P2    40W / 215W |    121MiB /  7952MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce RTX 2080    Off  | 00000000:67:00.0 Off |                  N/A |
| 24%   46C    P2    51W / 215W |    121MiB /  7952MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GeForce RTX 2080    Off  | 00000000:68:00.0 Off |                  N/A |
| 22%   48C    P2    51W / 215W |    121MiB /  7951MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     96311      C   python                                      7623MiB |
|    1     96311      C   python                                       111MiB |
|    2     96311      C   python                                       111MiB |
|    3     96311      C   python                                       111MiB |
+-----------------------------------------------------------------------------+
A simple matrix multiplcation consumes an entire GPU andsome in other three.

2. nvidia-smi before running the code:
same as 1, nothing running GPU.
nvidia-smi after running the code except for the last line of code of "image_features_extract_model(x)":
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.40.04    Driver Version: 418.40.04    CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 2080    Off  | 00000000:19:00.0 Off |                  N/A |
| 24%   40C    P2    42W / 215W |   7667MiB /  7952MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 2080    Off  | 00000000:1A:00.0 Off |                  N/A |
| 23%   41C    P8    13W / 215W |    121MiB /  7952MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce RTX 2080    Off  | 00000000:67:00.0 Off |                  N/A |
| 24%   44C    P8    24W / 215W |    121MiB /  7952MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GeForce RTX 2080    Off  | 00000000:68:00.0 Off |                  N/A |
| 22%   46C    P8    20W / 215W |    121MiB /  7951MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     96729      C   python                                      7657MiB |
|    1     96729      C   python                                       111MiB |
|    2     96729      C   python                                       111MiB |
|    3     96729      C   python                                       111MiB |
+-----------------------------------------------------------------------------+
Error when running the last line of code:
2019-04-13 15:52:15.698521: I tensorflow/stream_executor/dso_loader.cc:152] successfully opened CUDA library libcublas.so.10.0 locally
2019-04-13 15:52:15.724436: E tensorflow/stream_executor/cuda/cuda_blas.cc:510] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
2019-04-13 15:52:15.724477: W tensorflow/stream_executor/stream.cc:2130] attempting to perform BLAS operation using StreamExecutor without BLAS support
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 592, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/network.py", line 815, in call
    mask=masks)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/network.py", line 1000, in _run_internal_graph
    output_tensors = layer(computed_tensor, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 592, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/layers/convolutional.py", line 194, in call
    outputs = self._convolution_op(inputs, self.kernel)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/nn_ops.py", line 966, in __call__
    return self.conv_op(inp, filter)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/nn_ops.py", line 591, in __call__
    return self.call(inp, filter)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/nn_ops.py", line 208, in __call__
    name=self.name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_nn_ops.py", line 994, in conv2d
    name=name, ctx=_ctx)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_nn_ops.py", line 1072, in conv2d_eager_fallback
    ctx=_ctx, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/eager/execute.py", line 66, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InternalError: Blas SGEMM launch failed : m=5329, n=80, k=64 [Op:Conv2D]

**Comment by zhangjh915** [comment]
Just to provide an easier-to-read version of my problem.
I am using tensorflow gpu python3 docker image on Ubuntu. I have 4 GeForce RTX 2080 GPUs.
When I enable eager execution and run the code:

1. import tensorflow as tf
tf.enable_eager_execution()
print(tf.matmul([[1., 2.],[3., 4.]], [[1., 2.],[3., 4.]])),
there will be a huge consumption of GPU, which consumes an entire GPU and some of the other three. I am not sure if this is normal.

2. import tensorflow as tf
tf.enable_eager_execution()
image_model = tf.keras.applications.InceptionV3(include_top=False, weights='imagenet')
new_input = image_model.input
hidden_layer = image_model.layers[-1].output
image_features_extract_model = tf.keras.Model(new_input, hidden_layer)
x = tf.zeros([1, 299, 299, 3]) # just use a zero tensor instead of dataset tensor
image_features_extract_model(x),
before running the last line of code, the GPU consumption is like 1, it consumes an entire GPU and some of the other three. And after running the last line of code, it raises error of Blas SGEMM launch failed.

**Comment by zhangjh915** [comment]
Can someone help? :/

**Comment by ymodak** [comment]
Apologies for the delay in response. By default, TensorFlow maps nearly all of the GPU memory of all GPUs visible to the process.  Have you considered [Allowing GPU memory growth](https://www.tensorflow.org/guide/using_gpu#allowing_gpu_memory_growth) option.

**Comment by zhangjh915** [comment]
> Apologies for the delay in response. By default, TensorFlow maps nearly all of the GPU memory of all GPUs visible to the process. Have you considered [Allowing GPU memory growth](https://www.tensorflow.org/guide/using_gpu#allowing_gpu_memory_growth) option to limit gpu memory usage?.

Thank you for the response. Basically, my purpose is to run the code so I don't care if TensorFlow uses all GPUs. As in the problem description, I set "NVIDIA_VISIBLE_DEVICE="0,1,2,3"" when creating the docker image, and I attempted to let the script to use all GPUs if needed. What confused me was:
1. TensorFlow does not use all GPUs but fully consumes one GPU and a little of the other three. I am not sure if that is normal.
2. And it raised "Blas SGEMM launch failed" and with eager execution only.

**Comment by ymodak** [comment]
@smit-hinsu Can you PTAL? Thanks!

**Comment by alextp** [comment]
TensorFlow will by default only use a single GPU. To use multiple GPUs you need to either do data or model parallelism. The easiest way to do data parallelism is using distribution strategies; take a look at mirrored strategy or our [tf2 guide on distributed training](https://www.tensorflow.org/alpha/guide/distribute_strategy).

cc @guptapriya

**Comment by pige2nd** [comment]
I also met the same problem, where my tensorflow version is 1.12.0-gpu, have you solved this? @zhangjh915

**Comment by zhangjh915** [comment]
> I also met the same problem, where my tensorflow version is 1.12.0-gpu, have you solved this? @zhangjh915

Can you try TensorFlow 2 for your code? I did not solve this problem at that time. But I am now using TF2 a lot, and I have not encountered such issue anymore.
