### ISSUE TITLE
Tensorflow gpu import error

### ISSUE THREAD

**Issue by neilrod** [tensorflow/tensorflow#27824]
**System information**
- Windows 10
- Python version: conda python 3.6
- Installed using pip
- CUDA 10.1 /cuDNN 7.5.0 version:
- GPU 1050 Ti

**Describe the problem**
Traceback (most recent call last):
  File "C:\Users\clint\Anaconda3\envs\myenv\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\clint\Anaconda3\envs\myenv\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\clint\Anaconda3\envs\myenv\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\clint\Anaconda3\envs\myenv\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\clint\Anaconda3\envs\myenv\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\clint\Anaconda3\envs\myenv\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\clint\Anaconda3\envs\myenv\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\clint\Anaconda3\envs\myenv\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\clint\Anaconda3\envs\myenv\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\clint\Anaconda3\envs\myenv\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\clint\Anaconda3\envs\myenv\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\clint\Anaconda3\envs\myenv\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\clint\Anaconda3\envs\myenv\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

Failed to load the native TensorFlow runtime.

**Comment by rootkitchao** [comment]
You should use CUDA10.0,not 10.1.

**Comment by neilrod** [comment]
I installed CUDA 10.0 now, replaced the cuDNN cuda file.. however tensorflow gpu still doesnt work

it still returns the same error

**Comment by alanding1989** [comment]
> You should use CUDA10.0,not 10.1.

hi, I use 
`cuda_10.0.130_411.31_win10`, 
`cudnn-10.0-windows10-x64-v7.5.0.56`,
`python3.6`,
I activate conda env for python3.6, and then installed via pip,
 it also throw the same error when I import tensorflow, could you give some suggestions ?

**Comment by alanding1989** [comment]
> You should use CUDA10.0,not 10.1.

You should use CUDA10.0,not 10.1.
---------------------------------------------------
hi, I use
cuda_10.0.130_411.31_win10,
cudnn-10.0-windows10-x64-v7.5.0.56,
python3.6,
I activate conda env for python3.6, and then installed via pip,
it also throw the same error when I import tensorflow, could you give some suggestions ?

**Comment by neilrod** [comment]
I used visual studio 2017 community,
I also use tensorflow 13
