### ISSUE TITLE
BUG: tfdbg session cannot be used with SessionRunHooks

### ISSUE THREAD

**Issue by ppwwyyxx** [tensorflow/tensorflow#27847]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):ArchLinux
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):binary
- TensorFlow version (use command below):b'v1.13.0-rc2-5-g6612da8' 1.13.1
- Python version:3.7
- Bazel version (if compiling from source):n/a
- GCC/Compiler version (if compiling from source):n/a
- CUDA/cuDNN version:n/a
- GPU model and memory:n/a

The following code:
```python
#-*- coding: utf-8 -*-
#File:


import numpy as np
import tensorflow as tf
from tensorflow.python import debug as tf_debug

a = tf.placeholder(tf.float32, [10])
b = a + 1
c = b * 2

class Hook(tf.train.SessionRunHook):
    def before_run(self, _):
        return tf.train.SessionRunArgs(fetches=c)

class Hook2(tf.train.SessionRunHook):
    def before_run(self, _):
        return tf.train.SessionRunArgs(fetches=b)

sess = tf.Session()
sess = tf_debug.LocalCLIDebugWrapperSession(sess)

class SessionCreator():
    def create_session(self):
        return sess
final_sess = tf.train.MonitoredSession(session_creator=SessionCreator(), hooks=[Hook(), Hook2()])

final_sess.run(b, feed_dict={a:np.arange(10)})
```

Throws:
```
Traceback (most recent call last):
  File "tfdbg.py", line 30, in <module>
    final_sess.run(b, feed_dict={a:np.arange(10)})
  File "/home/wyx/.local/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 676, in run                                                                            
    run_metadata=run_metadata)
  File "/home/wyx/.local/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 1171, in run                                                                           
    run_metadata=run_metadata)
  File "/home/wyx/.local/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 1270, in run                                                                           
    raise six.reraise(*original_exc_info)
  File "/usr/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/wyx/.local/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 1255, in run                                                                           
    return self._sess.run(*args, **kwargs)
  File "/home/wyx/.local/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 1327, in run                                                                           
    run_metadata=run_metadata)
  File "/home/wyx/.local/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 1091, in run                                                                           
    return self._sess.run(*args, **kwargs)
  File "/home/wyx/.local/lib/python3.7/site-packages/tensorflow/python/debug/wrappers/framework.py", line 463, in run                                                                              
    empty_fetches = not nest.flatten(fetches)
  File "/home/wyx/.local/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 2156, in Flatten                                                                       
    return _pywrap_tensorflow_internal.Flatten(nested)
TypeError: '<' not supported between instances of 'Hook' and 'str'
```

I believe this issue was introduced in https://github.com/tensorflow/tensorflow/commit/1f26c65254268730b7409f517d1ed1b554d01e50 a year ago. `flatten` cannot handle fetches created by hooks.
The fix will be to obtain `empty_fetches` in a smarter way.

**Comment by caisq** [comment]
Fixed by https://github.com/tensorflow/tensorflow/commit/e2d269edb9217411fc4119338df949e1a741432b
