### ISSUE TITLE
ImportError: cannot import name 'abs'

### ISSUE THREAD

**Issue by ashisham** [tensorflow/tensorflow#27843]
os: ubuntu 16.04 LTS
processor : Intel® Xeon(R) CPU E5-1620 v4 @ 3.50GHz × 8 
GPU : GeForce GTX 1080 Ti/PCIe/SSE2 
python : 3.6 
tensorflow 1.13.1

https://github.com/hellochick/PSPNet-tensorflow

runfile('/data/segmentation-master/run_on_sequence.py', wdir='/data/segmentation-master')
Traceback (most recent call last):

  File "<ipython-input-3-914d8c6a3fac>", line 1, in <module>
    runfile('/data/segmentation-master/run_on_sequence.py', wdir='/data/segmentation-master')

  File "/home/dl-box/anaconda3/envs/tensorflow/lib/python3.6/site-packages/spyder_kernels/customize/spydercustomize.py", line 786, in runfile
    execfile(filename, namespace)

  File "/home/dl-box/anaconda3/envs/tensorflow/lib/python3.6/site-packages/spyder_kernels/customize/spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/data/segmentation-master/run_on_sequence.py", line 3, in <module>
    import tensorflow as tf

  File "/home/dl-box/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import

  File "/home/dl-box/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 88, in <module>
    from tensorflow.python import keras

  File "/home/dl-box/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/keras/__init__.py", line 24, in <module>
    from tensorflow.python.keras import activations

  File "/home/dl-box/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/keras/activations/__init__.py", line 22, in <module>
    from tensorflow.python.keras._impl.keras.activations import elu

  File "/home/dl-box/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/__init__.py", line 21, in <module>
    from tensorflow.python.keras._impl.keras import activations

  File "/home/dl-box/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/activations.py", line 23, in <module>
    from tensorflow.python.keras._impl.keras import backend as K

  File "/home/dl-box/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/backend.py", line 37, in <module>
    from tensorflow.python.layers import base as tf_base_layers

  File "/home/dl-box/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 25, in <module>
    from tensorflow.python.keras.engine import base_layer

  File "/home/dl-box/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/keras/engine/__init__.py", line 23, in <module>
    from tensorflow.python.keras.engine.base_layer import InputSpec

  File "/home/dl-box/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 35, in <module>
    from tensorflow.python.keras import backend

  File "/home/dl-box/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/keras/backend/__init__.py", line 22, in <module>
    from tensorflow.python.keras._impl.keras.backend import abs

ImportError: cannot import name 'abs'

**Comment by captain-pool** [comment]
Looks like a Tensorflow Version Problem, for that Specific Code. This is not a Tensorflow Related Problem. Raise an Issue in the repository stating this error, and ask the maintainer to provide the TF Version He/She used while building this.

**Comment by jvishnuvardhan** [comment]
@ashisham Could you check the following resources [1](https://stackoverflow.com/questions/51299194/importerror-cannot-import-name-abs) and [2](https://github.com/tensorflow/tensorflow/issues/20778) for any possible solution. Please check GitHub and Stackoverflow as there are many post describe solution to this issue. Please let me know how it progresses. Thanks!

**Comment by tensorflowbutler** [comment]
It has been 15 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by jvishnuvardhan** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will open a new issue. Thanks!
