### ISSUE TITLE
examples/get_started/regression/dnn_regression.py failed with ValueError (nightly build)

### ISSUE THREAD

**Issue by wdirons** [tensorflow/tensorflow#27872]
The above example has not been working for awhile now. (I don't believe it worked with 1.13.1) the code looks valid, what is wrong with the example code?

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): x86 Linux Ubuntu 18.04 container
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v1.12.0-12503-g5e52b70188 1.14.1-dev20190415
- Python version: 3.6.7
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
The example https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/get_started/regression/dnn_regression.py, fails with the following error:
ValueError: Tensor("buffer_size:0", shape=(), dtype=int64, device=/device:CPU:0) must be from the same graph as Tensor("MapDataset_2:0", shape=(), dtype=variant).

(Actually all 3 examples in that folder fail with the same error)

**Describe the expected behavior**
Provided examples should run without failure

**Code to reproduce the issue**
pip3 install tf-nightly
git clone http://github.com/tensorflow/tensorflow
cd tensorflow/tensorflow/examples/get_started/regression/
python3 dnn_regression.py

**Other info / logs**
```
root@c12a5b5766c5:~/tensorflow/tensorflow/examples/get_started/regression# python3 dnn_regression.py

WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

Downloading data from https://archive.ics.uci.edu/ml/machine-learning-databases/autos/imports-85.data
32768/25936 [=====================================] - 0s 1us/step
W0415 20:14:20.850975 140624720754496 deprecation.py:237] From /root/tensorflow/tensorflow/examples/get_started/regression/imports85.py:123: The name tf.string_to_hash_bucket_fast is deprecated. Please use tf.strings.to_hash_bucket_fast instead.

I0415 20:14:20.987369 140624720754496 estimator.py:1761] Using default config.
W0415 20:14:20.987863 140624720754496 estimator.py:1782] Using temporary folder as model directory: /tmp/tmpn4983vfs
I0415 20:14:20.988089 140624720754496 estimator.py:203] Using config: {'_model_dir': '/tmp/tmpn4983vfs', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7fe593747048>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
W0415 20:14:20.993491 140624720754496 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/training/training_util.py:238: Variable.initialized_value (from tensorflow.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.
Traceback (most recent call last):
  File "dnn_regression.py", line 105, in <module>
    tf.app.run(main=main)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "dnn_regression.py", line 85, in main
    model.train(input_fn=input_train, steps=STEPS)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 360, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1152, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1179, in _train_model_default
    input_fn, ModeKeys.TRAIN))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1016, in _get_features_and_labels_from_input_fn
    self._call_input_fn(input_fn, mode))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1107, in _call_input_fn
    return input_fn(**kwargs)
  File "dnn_regression.py", line 46, in input_train
    train.shuffle(1000).batch(128)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 1634, in shuffle
    buffer_size, seed, reshuffle_each_iteration))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 751, in shuffle
    return ShuffleDataset(self, buffer_size, seed, reshuffle_each_iteration)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 2743, in __init__
    **flat_structure(self))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_dataset_ops.py", line 4976, in shuffle_dataset
    name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py", line 366, in _apply_op_helper
    g = ops._get_graph_from_inputs(_Flatten(keywords.values()))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 6098, in _get_graph_from_inputs
    _assert_same_graph(original_graph_element, graph_element)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 6034, in _assert_same_graph
    original_item))
ValueError: Tensor("buffer_size:0", shape=(), dtype=int64, device=/device:CPU:0) must be from the same graph as Tensor("MapDataset_2:0", shape=(), dtype=variant).
root@c12a5b5766c5:~/tensorflow/tensorflow/examples/get_started/regression#

```

**Comment by wdirons** [comment]
In 1.13.1 this doesn't work either, it fails with the same error, but if you undo the last commit to the example (https://github.com/tensorflow/tensorflow/commit/e2b36c5026b856ca63041085c3183f0f7d490e71#diff-4cfd74ba277097d2966e281f8e8655b8) it works. 

That fix however doesn't work with the nightly builds.

**Comment by zhengxiawu** [comment]
The bug still exists in 1.14,  does any knows how to fix it?

**Comment by wdirons** [comment]
closing old issues I opened. I'm not sure if this test is still in 2.2.0

**Comment by MarkDaoust** [comment]
Thanks for closing.

Sorry about the confusion. I've deleted these example as they were no longer relevant.
