### ISSUE TITLE
could not create a dilated convolution forward descriptor, in file tensorflow/core/kernels/mkl_conv_ops.cc:1111

### ISSUE THREAD

**Issue by nm46nm** [tensorflow/tensorflow#27906]
When I tried to run some yolov3 codes, I always got the following error:
`Traceback (most recent call last):

  File "<ipython-input-16-cd2eeb60d39b>", line 1, in <module>
    runfile('C:/Users/10137/Desktop/learn/python/yolov3_keras_qwe/train.py', wdir='C:/Users/10137/Desktop/learn/python/yolov3_keras_qwe')

  File "C:\Users\10137\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 786, in runfile
    execfile(filename, namespace)

  File "C:\Users\10137\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/10137/Desktop/learn/python/yolov3_keras_qwe/train.py", line 190, in <module>
    _main()

  File "C:/Users/10137/Desktop/learn/python/yolov3_keras_qwe/train.py", line 65, in _main
    callbacks=[logging, checkpoint])

  File "C:\Users\10137\Anaconda3\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)

  File "C:\Users\10137\Anaconda3\lib\site-packages\keras\engine\training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)

  File "C:\Users\10137\Anaconda3\lib\site-packages\keras\engine\training_generator.py", line 217, in fit_generator
    class_weight=class_weight)

  File "C:\Users\10137\Anaconda3\lib\site-packages\keras\engine\training.py", line 1217, in train_on_batch
    outputs = self.train_function(ins)

  File "C:\Users\10137\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)

  File "C:\Users\10137\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)

  File "C:\Users\10137\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1439, in __call__
    run_metadata_ptr)

  File "C:\Users\10137\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))

AbortedError: Operation received an exception:Status: 3, message: could not create a dilated convolution forward descriptor, in file tensorflow/core/kernels/mkl_conv_ops.cc:1111
	 [[{{node conv2d_2/convolution}}]]`

**Comment by ianlokh** [comment]
I am also getting the same error on TensorFlow 1.13.1. There appears to be a similar issue (#24650) that was to be resolved in 1.13.1 but the error line was different in that case.

**Comment by ppwwyyxx** [comment]
#24650 was not resolved in 1.13.1

**Comment by nm46nm** [comment]
I downgraded the keras to 2.1.5 and the error didn't occur again. This may help.

**Comment by ianlokh** [comment]
Hi nm46nm, thanks it worked but TensorFlow got downgraded to 1.9. I will try to apply TF 1.12 and see if it works noting that this was a non-issue eventually (thanks Yuxin)

**Comment by achandraa** [comment]
@nm46nm and @ianlokh : Is this resolved? Please let us know. Thanks!

**Comment by rickantonais** [comment]
Downgrading to tensorflow 1.9 worked fine for me

**Comment by achandraa** [comment]
That's great. We will be closing the issue since it is resolved. Thanks!

**Comment by ianlokh** [comment]
Hi achandraa, yes downgrading to TF 1.9 resolved my issue. As a side note, I upgraded TF to 1.12 and it worked as well.

**Comment by nm46nm** [comment]
> @nm46nm and @ianlokh : Is this resolved? Please let us know. Thanks!

I just use the version 2.1.5 in which there is no error. Haven't tried new version again.

**Comment by mengxia1994** [comment]
According to commits above, i tried to downgrade tensorflow from 1.13 to 1.12 and it also worked for me.

**Comment by Isaryll** [comment]
I tried to update tensorflow from 1.13.1 to 1.14 and it work for me.
