### ISSUE TITLE
Following object-based saving guide on TensorFlow website leads to error

### ISSUE THREAD

**Issue by jpatts** [tensorflow/tensorflow#27936]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): binary? pip3 install tensorflow-gpu
- TensorFlow version (use command below): 1.13.1
- Python version: 3.6
- Bazel version (if compiling from source): No
- GCC/Compiler version (if compiling from source): No
- CUDA/cuDNN version: V10.0.130
- GPU model and memory: GTX 1060m, 6gb

**Describe the current behavior**
I am having issues saving and loading my models, so I tried the MVP example on the tensorflow website: https://www.tensorflow.org/guide/eager#object-based_saving
It has an error.
**Describe the expected behavior**
It should work.
**Code to reproduce the issue**
```
import tensorflow as tf

x = tf.Variable(10.)
checkpoint = tf.train.Checkpoint(x=x)

x.assign(2.)   # Assign a new value to the variables and save.
checkpoint_path = './ckpt/'
checkpoint.save('./ckpt/')

x.assign(11.)  # Change the variable after saving.

# Restore values from the checkpoint
checkpoint.restore(tf.train.latest_checkpoint(checkpoint_path))

print(x)  # => 2.0
```
**Other info / logs**
```
python3 test.py 
WARNING:tensorflow:From /home/jpatts/Documents/alpha-doom/env/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    checkpoint.save('./ckpt/')
  File "/home/jpatts/Documents/alpha-doom/env/lib/python3.6/site-packages/tensorflow/python/training/checkpointable/util.py", line 1856, in save
    session.run(self.save_counter.initializer)
AttributeError: 'NoneType' object has no attribute 'run'
```

**Comment by jpatts** [comment]
Nvm, I forgot to `tf.enable_eager_execution()`.
I probably should stop jumping between 2.0 and 1.3....
