### ISSUE TITLE
AttributeError: module 'tensorflow_estimator.python.estimator.api._v1.estimator' has no attribute '__file__'

### ISSUE THREAD

**Issue by sadatnfs** [tensorflow/tensorflow#27989]
Tensorflow builds through successfully but cannot import when I try (building off of Master branch):
```python
Successfully installed tensorflow-1.13.1
[91mYou are using pip version 10.0.1, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
[0m[91mTraceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/__init__.py", line 34, in <module>
    from tensorflow._api.v1 import compat
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/_api/v1/compat/__init__.py", line 21, in <module>
    from tensorflow._api.v1.compat import v1
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/_api/v1/compat/v1/__init__.py", line 643, in <module>
    'tensorflow_estimator.python.estimator.api._v1.estimator'))
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/tools/component_api_helper.py", line 85, in package_hook
    set_child_as_subpackage()
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/tools/component_api_helper.py", line 69, in set_child_as_subpackage
    os.path.join(os.path.dirname(child_pkg.__file__), ".."))]
AttributeError: module 'tensorflow_estimator.python.estimator.api._v1.estimator' has no attribute '__file__'
```

**System information**
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian: Buster
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
TensorFlow installed from (source or binary): Source
TensorFlow version: Master branch
Python version: 3.6.5
Installed using virtualenv? pip? conda?: Source build
Bazel version (if compiling from source): 0.24.1
GCC/Compiler version (if compiling from source): 8.3.0
CUDA/cuDNN version: NA
GPU model and memory: NA

** Call to build **
```bash
    cd /opt && \
    git clone --recursive https://github.com/tensorflow/tensorflow.git && \
    cd /opt/tensorflow && \
 TF_MKL_ROOT=/usr/lib  \
    TF_MKL_DOWNLOAD=0 \
    USE_DEFAULT_PYTHON_LIB_PATH=1 \
    TF_NEED_MKL=1 \
    TF_NEED_JEMALLOC=1 \
    TF_NEED_GCP=0 \
    TF_NEED_HDFS=0 \
    TF_ENABLE_XLA=1 \
    TF_NEED_MPI=0 \
    TF_NEED_GDR=0 \
    TF_NEED_S3=1 \
    TF_NEED_KAFKA=0 \
    TF_SET_ANDROID_WORKSPACE=0 \
    TF_NEED_CUDA=0 \
    TF_MKL_ENABLED="true" \
    CI_BUILD_PYTHON=/opt/conda/bin/python \
    PYTHON_BIN_PATH=/opt/conda/bin/python \
    PYTHON_LIB_PATH=/opt/conda/lib/python3.6/site-packages \
    GCC_HOST_COMPILER_PATH=/usr/bin/gcc \
    CC_OPT_FLAGS=" -mavx -msse2 -msse3 -msse4.2 -msse4.1 -mfpmath=sse -lmkl_gf_lp64 -Wl,--start-group -lmkldnn -lmklml_intel -lmkl_gnu_thread -lmkl_core -Wl,--end-group -dl -lpthread -lm " \
    /bin/bash ./configure && \
    bazel build \
    --config=mkl --config=opt \
    --config=noaws --config=noignite --config=nokafka --config=nonccl \
    --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" \
    --copt=-msse4.2 --copt=-msse4.1 --copt=-mavx --copt=-msse2 --copt=-msse3  \
    --copt=-O3 --copt=-mfpmath=both \
    --copt="-DMKL_LP64" \
    --copt="-fPIC" \
    --linkopt="-lmkl_gf_lp64" \
    --linkopt="-lmkl_gnu_thread" \
    --linkopt="-dl" \
    --linkopt="-ldl" \
    --linkopt="-lpthread" \
    --linkopt="-lmkl_core" \
    --linkopt="-lm" \
    --linkopt="-lmkl_rt" \
    --linkopt="-lmkldnn" \
    tensorflow/tools/pip_package:build_pip_package && \
    bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/pip && \
    pip install --no-deps /tmp/pip/tensorflow-*.whl && \
    cd /opt && rm -rf /opt/tensorflow /tmp/* && \
    python -c "import tensorflow as tf; hello = tf.constant('Hello, TensorFlow!'); sess = tf.Session(); print(sess.run(hello))" && \
    echo "\n\n TENSORFLOW DONEZO \n\n"
```

**Comment by achandraa** [comment]
@sadatnfs : Did you get chance to have a look on the [link](https://www.tensorflow.org/install/source). Let us know if that helps. Thanks!

**Comment by sadatnfs** [comment]
@achandraa the solution was to also build tensorflow-estimator and THEN import TF. That works.
