### ISSUE TITLE
Conversion of frozen graph .pb to .tflite error

### ISSUE THREAD

**Issue by Mowghli** [tensorflow/tensorflow#28069]
So I tried to convert a frozen graph that I got from [https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md](url) (the name of the model is "faster_rcnn_resnet101_fgvc"), to a tflite, by using the following command on google collab:

!tflite_convert --graph_def_file=frozen_inference_graph.pb --output_file=optimized_graph.lite --input_format=TENSORFLOW_GRAPHDEF --output_format=TFLITE --input_shape=1,1024,1024,3 --input_array=image_tensor --output_array=Softmax

I sort of guessed (probably incorrectly) the input and output arrays, and input_shape, because that information was not provided with the model. I got an error saying something like "2019-04-23 09:30:48.751842: F tensorflow/lite/toco/tooling_util.cc:627] Check failed: dim >= 1 (0 vs. 1)
Aborted (core dumped)". I am new to Tensorflow, so is there any way I can find out how that error occurred, and how I can resolve it?

**Comment by karimnosseir** [comment]
Hi Mowghli,

You can use summarize_graph tool to inspect the input and outputs of the graph
See
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/graph_transforms#inspecting-graphs

**Comment by Mowghli** [comment]
So I got this:

```
Amoghs-MacBook-Pro:tensorflow amoghbhabal$ bazel-bin/tensorflow/tools/graph_transforms/summarize_graph --in_graph=frozen_inference_graph.pb
Found 1 possible inputs: (name=image_tensor, type=uint8(4), shape=[?,?,?,3]) 
No variables spotted.
Found 4 possible outputs: (name=num_detections, op=Identity) (name=detection_classes, op=Identity) (name=detection_scores, op=Identity) (name=detection_boxes, op=Identity) 
Found 57548019 (57.55M) const parameters, 0 (0) variable parameters, and 65923 control_edges
Op types used: 66369 Const, 8603 Reshape, 5794 StridedSlice, 5772 Shape, 5733 GatherV2, 5714 Fill, 2898 Add, 2895 Mul, 2892 Pack, 2890 Sub, 2884 Range, 2874 Slice, 2872 ConcatV2, 2870 Minimum, 2865 Less, 2865 Select, 2858 ZerosLike, 2855 NonMaxSuppressionV3, 61 Enter, 58 BiasAdd, 56 Conv2D, 49 Relu, 34 Identity, 27 RealDiv, 25 Cast, 22 TensorArrayV3, 22 Switch, 21 Merge, 20 NextIteration, 13 Maximum, 12 TensorArrayReadV3, 12 TensorArrayScatterV3, 12 Greater, 11 Split, 10 TensorArraySizeV3, 10 Squeeze, 10 TensorArrayWriteV3, 10 Tile, 10 Exit, 10 Unpack, 10 TensorArrayGatherV3, 9 ExpandDims, 7 Pad, 6 LogicalAnd, 6 Assert, 6 Transpose, 5 LoopCond, 5 Equal, 4 GreaterEqual, 4 Exp, 4 Size, 4 MaxPool, 4 TopKV2, 4 Round, 3 Where, 2 MatMul, 2 Softmax, 2 Sum, 2 Mean, 1 All, 1 Placeholder, 1 Max, 1 Relu6, 1 ResizeBilinear, 1 CropAndResize
To use with tensorflow/tools/benchmark:benchmark_model try these arguments:
bazel run tensorflow/tools/benchmark:benchmark_model -- --graph=frozen_inference_graph.pb --show_flops --input_layer=image_tensor --input_layer_type=uint8 --input_layer_shape=-1,-1,-1,3 --output_layer=num_detections,detection_classes,detection_scores,detection_boxes
```

So I found the input and output layers, but the input_layer_shape is an issue. I tried running:

```
!tflite_convert --graph_def_file=frozen_inference_graph.pb --output_file=optimized_graph.lite --input_format=TENSORFLOW_GRAPHDEF --output_format=TFLITE --input_shape=-1,-1,-1,3 --input_array=image_tensor --output_array=num_detections,detection_classes,detection_scores,detection_boxes --allow_custom_ops
```


and I got the error

```
2019-04-25 23:06:13.427794: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2300000000 Hz
2019-04-25 23:06:13.428096: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x55705b2bac60 executing computations on platform Host. Devices:
2019-04-25 23:06:13.428154: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
Traceback (most recent call last):
  File "/usr/local/bin/tflite_convert", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/lite/python/tflite_convert.py", line 442, in main
    app.run(main=run_main, argv=sys.argv[:1])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/lite/python/tflite_convert.py", line 438, in run_main
    _convert_model(tflite_flags)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/lite/python/tflite_convert.py", line 122, in _convert_model
    converter = _get_toco_converter(flags)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/lite/python/tflite_convert.py", line 109, in _get_toco_converter
    return converter_fn(**converter_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/lite/python/lite.py", line 288, in from_frozen_graph
    _set_tensor_shapes(input_tensors, input_shapes)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/lite/python/convert_saved_model.py", line 220, in set_tensor_shapes
    raise ValueError(message)
ValueError: The shape of tensor 'image_tensor' cannot be changed from (?, ?, ?, 3) to [-1, -1, -1, 3]. Dimension -1 must be >= 0
```
Is there any way I can convert this model to .tflite format?
Also, are there any tensorflow lite sample models that perform object detection on animals and plants? I only found sample models trained on COCO dataset, and retraining them would involve using VMs, since the iNaturalist dataset is too large.

**Comment by lakshmipriya04** [comment]
Is this resolved? facing the same issue.
TIA

**Comment by gadagashwini** [comment]
@Mowghli  Is this still an issue?

**Comment by Mowghli** [comment]
Sorry for the late reply. I asked the owner of the repository that has the model, regarding the same issues. He replied that he is not sure if conversion of FasterRCNN models to TF Lite is supported yet. He suggested performing transfer learning using a much smaller subset of the iNaturalist Dataset. He also gave the following links:

1. [https://medium.com/tensorflow/training-and-serving-a-realtime-mobile-object-detector-in-30-minutes-with-cloud-tpus-b78971cf1193](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_on_mobile_tensorflowlite.md)
2. [https://medium.com/tensorflow/training-and-serving-a-realtime-mobile-object-detector-in-30-minutes-with-cloud-tpus-b78971cf1193](https://medium.com/tensorflow/training-and-serving-a-realtime-mobile-object-detector-in-30-minutes-with-cloud-tpus-b78971cf1193
)

The Faster RCNN model is also not trained with quantization enabled, so it might become inaccurate when deployed, assuming you can convert it to TFLite.
Also, I tried converting this model to TFLite, with the following command (I tried guessing the shape, I am not sure if it is correct):

```
!tflite_convert --graph_def_file=frozen_inference_graph.pb --output_file=optimized_graph.lite --input_format=TENSORFLOW_GRAPHDEF --output_format=TFLITE --input_shape=0,1024,1024,3 --input_array=image_tensor --output_array=Softmax --allow_custom_ops
```

I got the following output (This is output is not complete, it's just the end of the output text I got):

```
2019-04-23 09:06:30.883905: I tensorflow/lite/toco/import_tensorflow.cc:1324] Converting unsupported operation: Round
2019-04-23 09:06:30.883938: I tensorflow/lite/toco/import_tensorflow.cc:1324] Converting unsupported operation: Round
2019-04-23 09:06:30.884003: I tensorflow/lite/toco/import_tensorflow.cc:1324] Converting unsupported operation: TensorArrayWriteV3
2019-04-23 09:06:30.884051: I tensorflow/lite/toco/import_tensorflow.cc:1324] Converting unsupported operation: TensorArrayWriteV3
2019-04-23 09:08:50.422889: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 67000 operators, 136448 arrays (0 quantized)
2019-04-23 09:11:01.390182: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After Removing unused ops pass 1: 502 operators, 749 arrays (0 quantized)
2019-04-23 09:11:01.408409: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 502 operators, 749 arrays (0 quantized)
2019-04-23 09:11:01.594021: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 1: 207 operators, 447 arrays (0 quantized)
2019-04-23 09:11:01.600658: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before dequantization graph transformations: 207 operators, 447 arrays (0 quantized)
2019-04-23 09:11:01.614120: F tensorflow/lite/toco/tooling_util.cc:627] Check failed: dim >= 1 (0 vs. 1)
Aborted (core dumped)
```
Seems like there were a lot of unsupported operations.

**Comment by gadagashwini** [comment]
@Mowghli looks you have found an alternative. Can we close this?

**Comment by Mowghli** [comment]
Yes. The issue is resolved.

**Comment by gadagashwini** [comment]
Glad it resolved.
