### ISSUE TITLE
Tensorflow 2.0 GPU error: Failed to load the native TensorFlow runtime.

### ISSUE THREAD

**Issue by victorinno** [tensorflow/tensorflow#28134]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 64 bits
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): CONDA
- TensorFlow version (use command below): 2.0
- Python version: 3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.1
- GPU model and memory: Geforce 910m

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

**Describe the expected behavior**

**Code to reproduce the issue**
I just installed everything and got the error

**Other info / logs**

  File "<ipython-input-1-d36b20bff3cb>", line 1, in <module>
    runfile('C:/Users/victor/Documents/s4y/labeled-surgical-tools/preparar_dados.py', wdir='C:/Users/victor/Documents/s4y/labeled-surgical-tools')

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 786, in runfile
    execfile(filename, namespace)

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/victor/Documents/s4y/labeled-surgical-tools/preparar_dados.py", line 7, in <module>
    import tensorflow as tf

  File "C:\Users\victor\AppData\Roaming\Python\Python37\site-packages\tensorflow\__init__.py", line 27, in <module>
    from tensorflow._api.v2 import audio

  File "C:\Users\victor\AppData\Roaming\Python\Python37\site-packages\tensorflow\_api\v2\audio\__init__.py", line 8, in <module>
    from tensorflow.python.ops.gen_audio_ops import decode_wav

  File "C:\Users\victor\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow

  File "C:\Users\victor\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)

ImportError: Traceback (most recent call last):
  File "C:\Users\victor\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\victor\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\victor\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\ProgramData\Anaconda3\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\ProgramData\Anaconda3\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: Não foi possível encontrar o módulo especificado.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by jvishnuvardhan** [comment]
@victorinno Could you provide the steps you followed to install TF2.0 using conda? There are some known issue with python3.7 installed through Anaconda. Could you downgrade to Python3.6.6 or 3.6.8 and install TF2.0. There are useful resource on GitHub and Stackoverflow. Here is one [resource](https://github.com/tensorflow/tensorflow/issues/26182) and [here](https://github.com/tensorflow/tensorflow/issues/27935). Please let us know how it progresses. Thanks!

**Comment by victorinno** [comment]
@jvishnuvardhan I had to install it by Conda cmd, because it didn´t appeared in the environment option inside anacona navigator.

But I´ll try downgrading it.

**Comment by victorinno** [comment]
I´ve created another environment with python 3.6.

Instead of installing it throw python navigator I had installed throw conda cmd with the following command: pip install tensorflow-gpu==2.0.0-alpha0

The error persists.

Here follows the trace:

Traceback (most recent call last):

  File "<ipython-input-1-d36b20bff3cb>", line 1, in <module>
    runfile('C:/Users/victor/Documents/s4y/labeled-surgical-tools/preparar_dados.py', wdir='C:/Users/victor/Documents/s4y/labeled-surgical-tools')

  File "C:\Users\victor\.conda\envs\base 3.6\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\Users\victor\.conda\envs\base 3.6\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/victor/Documents/s4y/labeled-surgical-tools/preparar_dados.py", line 7, in <module>
    import tensorflow as tf

  File "C:\Users\victor\.conda\envs\base 3.6\lib\site-packages\tensorflow\__init__.py", line 27, in <module>
    from tensorflow._api.v2 import audio

  File "C:\Users\victor\.conda\envs\base 3.6\lib\site-packages\tensorflow\_api\v2\audio\__init__.py", line 8, in <module>
    from tensorflow.python.ops.gen_audio_ops import decode_wav

  File "C:\Users\victor\.conda\envs\base 3.6\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow

  File "C:\Users\victor\.conda\envs\base 3.6\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)

ImportError: Traceback (most recent call last):
  File "C:\Users\victor\.conda\envs\base 3.6\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\victor\.conda\envs\base 3.6\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\victor\.conda\envs\base 3.6\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\victor\.conda\envs\base 3.6\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\victor\.conda\envs\base 3.6\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: Não foi possível encontrar o módulo especificado.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by jvishnuvardhan** [comment]
@victorinno TF2.0 and TF1.13.1 pip binaries are built with CUDA10.0. So you need to downgrade to CUDA10.0 if you use pip binaries to install TF. Another thing is you need to download NVDIA drivers, CUDA toolkit before running pip install command. I have listed detailed steps in install TF1.12-gpu [here](https://stackoverflow.com/questions/38896424/tensorflow-not-found-using-pip/55787868#55787868). Please follow the steps overall but use update drivers to support TF2.0. If you want to use Conda to install TF, then please follow the steps listed in resource#1 of my earlier response. 

For installing, virtual env, please do this
1. (base) C:\Users\XXXX>conda create -n venv pip python=3.6
2. (base) C:\Users\XXXX>conda activate venv
3. Then go to Anaconda Navigator, select venv 
4. Change 'Applications on' to the virtual environment you just created ('venv')
5. Install a new spyder under 'venv' or you can go to command window, type conda install spyder --new-instance
6. Run the new spyder and test

Thanks

**Comment by victorinno** [comment]
@jvishnuvardhan Do I need to instal the normal version of tensorflow 2.0?

**Comment by jvishnuvardhan** [comment]
@victorinno It depends on your work. On day to day if you use multiple versions of TF, then it is better to use virtual environment and have and virtual env for each TF version. If you use single TF version, I would suggest to install NVIDIA drivers, CUDA, cuDNN, Visual studio, python, and tensorflow using pip. Some people uses Anaconda to install TF-gpu but as of now TF team doesn't support conda based installations.Thanks!

**Comment by jvishnuvardhan** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will open a new issue. Thanks!
