### ISSUE TITLE
ImportError: DLL load failed on Windows 10 using GPU

### ISSUE THREAD

**Issue by backrunner** [tensorflow/tensorflow#28142]
**System information**
- OS Platform and Distribution : Windows 10 1809
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.13.1
- Python version: 3.7.3/3.6.8
- Installed using virtualenv? pip? conda?: pip install tensorflow-gpu
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: tried 10.1/10.0/9.0, cudnn 7.5
- GPU model and memory: GTX 1060 6GB

**Describe the problem**

I have tried several different versions of CUDA/cuDNN, and added the bin/include/lib folders to PATH, but that doesn't work for my situation. Reinstall python and tensorflow doesn't work either. I tried the binary version of tensorflow and installed the corresponding CUDA/cuDNN, this error also appeared. I can't figure out what's wrong.

*VS 2015 C++ Redist is also installed

**Provide the exact sequence of commands / steps that you executed before running into the problem**

import tensorflow as tf

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

Traceback (most recent call last):
  File "F:\Python Environment\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "F:\Python Environment\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "F:\Python Environment\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "F:\Python Environment\Python37\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "F:\Python Environment\Python37\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: 找不到指定的模块。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "F:\Python Environment\Python37\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "F:\Python Environment\Python37\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "F:\Python Environment\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "F:\Python Environment\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "F:\Python Environment\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "F:\Python Environment\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "F:\Python Environment\Python37\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "F:\Python Environment\Python37\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: 找不到指定的模块。

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by backrunner** [comment]
That's a PATH error
