### ISSUE TITLE
TypeError: unsupported operand type(s) since TF 1.13

### ISSUE THREAD

**Issue by dmus** [tensorflow/tensorflow#28150]
```
import tensorflow as tf

tf.enable_eager_execution()

image_path = '6999_2_2047_690_44_93.png'
img_str = tf.read_file(image_path)

image = tf.image.decode_png(img_str)
image = image / 255.
```

**Describe the current behavior**

With tensorflow 1.12 this works fine. However with 1.13 this results in 

> Traceback (most recent call last):
>   File "test.py", line 9, in <module>
>     image = image / 255.
> TypeError: unsupported operand type(s) for /: 'tensorflow.python.framework.ops.EagerTensor' and 'float'

This is the same for graph mode:

> Traceback (most recent call last):
>   File "test.py", line 9, in <module>
>     image = image / 255.
> TypeError: unsupported operand type(s) for /: 'Tensor' and 'float'

This looks like a bug?

**Comment by yongtang** [comment]
@dmus With tf-nightly the error has been changed to:
```
>>> image = image / 255.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/math_ops.py", line 897, in binary_op_wrapper
    return func(x, y, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/math_ops.py", line 1009, in _div_python2
    y = ops.convert_to_tensor(y, name="y", dtype=x.dtype.base_dtype)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1080, in convert_to_tensor
    return convert_to_tensor_v2(value, dtype, preferred_dtype, name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1138, in convert_to_tensor_v2
    as_ref=False)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1160, in internal_convert_to_tensor
    value = _TensorTensorConversionFunction(value, dtype=dtype)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1011, in _TensorTensorConversionFunction
    (dtype.name, t.dtype.name, str(t)))
ValueError: Tensor conversion requested dtype uint8 for Tensor with dtype float32: 'tf.Tensor(255.0, shape=(), dtype=float32)'
```

I think the ValueError is relevant now. We could consider the issue has been fixed in tf-nightly?
