### ISSUE TITLE
Issue defining tf.function input_signature on class methods

### ISSUE THREAD

**Issue by MarcioPorto** [tensorflow/tensorflow#28165]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution: Linux Ubuntu 18.04
- TensorFlow installed from (source or binary): Binary
- TensorFlow version: tf-nightly-2.0-preview==2.0.0.dev20190426
- Python version: 3.7.0

I have defined the following Encoder class with a tf.function signature hoping to be able to save it using the SavedModel format.

```python
class Encoder(tf.keras.Model):
    # init and other functions...

    @tf.function(input_signature=[
        tf.TensorSpec([None, 50], tf.float32, name='x'),
        tf.TensorSpec([None, 1024], tf.float32, name='hidden')
    ])
    def call(self, x, hidden):
        x = self.embedding(x)
        output, state = self.gru(x, initial_state = hidden)        
        return output, state


# Some more code...

tf.saved_model.save(
    encoder,  # instance of Encoder
    './some/directory/',
    signatures=Encoder.call
)
```

I am not sure if this is the desired behavior, but I am getting this error when trying to save:

```
Traceback (most recent call last):
  File "train.py", line 244, in <module>
    signatures=Encoder.call
  File "/home/marcio/Workspace/projects/traduki/traduki-pipel
ine/venv/lib/python3.7/site-packages/tensorflow/python/saved_
model/save.py", line 801, in save
    signatures = signature_serialization.canonicalize_signatu
res(signatures)
  File "/home/marcio/Workspace/projects/traduki/traduki-pipel
ine/venv/lib/python3.7/site-packages/tensorflow/python/saved_
model/signature_serialization.py", line 95, in canonicalize_s
ignatures
    signature_function = _get_signature(function)
  File "/home/marcio/Workspace/projects/traduki/traduki-pipel
ine/venv/lib/python3.7/site-packages/tensorflow/python/saved_
model/signature_serialization.py", line 41, in _get_signature
    function = function.get_concrete_function()
  File "/home/marcio/Workspace/projects/traduki/traduki-pipeline/venv/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 702, in get_concrete_function
    self._initialize(args, kwargs, add_initializers_to=initializer_map)
  File "/home/marcio/Workspace/projects/traduki/traduki-pipeline/venv/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 379, in _initialize
    *args, **kwds))
  File "/home/marcio/Workspace/projects/traduki/traduki-pipeline/venv/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1331, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/home/marcio/Workspace/projects/traduki/traduki-pipeline/venv/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1594, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/home/marcio/Workspace/projects/traduki/traduki-pipeline/venv/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1527, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/home/marcio/Workspace/projects/traduki/traduki-pipeline/venv/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 713, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/marcio/Workspace/projects/traduki/traduki-pipeline/venv/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 329, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/home/marcio/Workspace/projects/traduki/traduki-pipeline/venv/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 436, in __call__
    self._initialize(args, kwds, add_initializers_to=initializer_map)
  File "/home/marcio/Workspace/projects/traduki/traduki-pipeline/venv/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 379, in _initialize
    *args, **kwds))
  File "/home/marcio/Workspace/projects/traduki/traduki-pipeline/venv/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1331, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/home/marcio/Workspace/projects/traduki/traduki-pipeline/venv/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1594, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/home/marcio/Workspace/projects/traduki/traduki-pipeline/venv/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1527, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/home/marcio/Workspace/projects/traduki/traduki-pipeline/venv/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 713, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/marcio/Workspace/projects/traduki/traduki-pipeline/venv/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 329, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/home/marcio/Workspace/projects/traduki/traduki-pipeline/venv/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 705, in wrapper
    ), args, kwargs)
  File "/home/marcio/Workspace/projects/traduki/traduki-pipeline/venv/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py", line 360, in converted_call
    result = converted_f(*effective_args, **kwargs)
TypeError: tf__call() missing 1 required positional argument: 'hidden'
```

When I remove the two TensorSpecs from the signature, I instead get a `TypeError: tf__call() missing 3 required positional arguments: 'self', 'x', and 'hidden'`, which means it's expecting me to provide a TensorSpec for `self`.

Based on [this guide](https://www.tensorflow.org/alpha/guide/saved_model#identifying_a_signature_to_export) I wouldn't expect to have to provide signature information for `self` in the `call` function, which leads me to believe the current behavior should be changed.

**Comment by allenlavoie** [comment]
This works if you pass `encoder.call` instead of `Encoder.call`. Is there something you could do passing the unbound method that you can't by passing the bound method?

**Comment by MarcioPorto** [comment]
@allenlavoie Good catch! I guess I don't need the unbound method after all. Thanks!
