### ISSUE TITLE
TPU + Keras doesn't support multiple input layers

### ISSUE THREAD

**Issue by NMAC427** [tensorflow/tensorflow#28176]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution: Google Colab

**Describe the current behavior**
When trying to train a model that has multiple input layers using Keras (eg. CTC) on a TPU, Tensorflow throws an InvalidArgumentError claiming that I didn't feed a value for a placeholder tensor. 

**Describe the expected behavior**
If I run the exact same model on a GPU, everything works as expected (eg. the model trains).

**Code to reproduce the issue**
All code required to reproduce this but can be found on Google Colab:
https://colab.research.google.com/drive/1rxKwCfDPS_2GPNN9yWAyQlQZy8Fg3deV

**Other info / logs**
Possibly related issue: https://github.com/tensorflow/tensorflow/issues/23659

```
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1333     try:
-> 1334       return fn(*args)
   1335     except errors.OpError as e:

13 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py in _run_fn(feed_dict, fetch_list, target_list, options, run_metadata)
   1318       return self._call_tf_sessionrun(
-> 1319           options, feed_dict, fetch_list, target_list, run_metadata)
   1320 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py in _call_tf_sessionrun(self, options, feed_dict, fetch_list, target_list, run_metadata)
   1406         self._session, options, feed_dict, fetch_list, target_list,
-> 1407         run_metadata)
   1408 

InvalidArgumentError: Combined status information from 9 operations:

Status code: Invalid argument [2x]
  You must feed a value for placeholder tensor 'label' with dtype int32 and shape [256,12]
  	 [[{{node label}}]] [1x]
  You must feed a value for placeholder tensor 'label' with dtype int32 and shape [256,12]
  	 [[{{node label}}]]
  	 [[{{node GroupCrossDeviceControlEdges_0/TPUReplicate/_compile/_11823778269055837323/_17}}]] [1x]
(7 successful operations.)

During handling of the above exception, another exception occurred:

InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-5-6495be1fe4ea> in <module>()
      3     x = feed_dict_x,
      4     y = feed_dict_y,
----> 5     batch_size = BATCH_SIZE
      6 )

/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/tpu/python/tpu/keras_support.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, **kwargs)
   1530                                   validation_split, validation_data, shuffle,
   1531                                   class_weight, sample_weight, initial_epoch,
-> 1532                                   steps_per_epoch, validation_steps, **kwargs)
   1533       finally:
   1534         self._numpy_to_infeed_manager_list = []

/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/tpu/python/tpu/keras_support.py in _pipeline_fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, **kwargs)
   1631         initial_epoch=initial_epoch,
   1632         steps_per_epoch=steps_per_epoch,
-> 1633         validation_steps=validation_steps)
   1634 
   1635   def _pipeline_fit_loop(self,

/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/tpu/python/tpu/keras_support.py in _pipeline_fit_loop(self, inputs, targets, sample_weights, batch_size, epochs, verbose, callbacks, val_inputs, val_targets, val_sample_weights, shuffle, initial_epoch, steps_per_epoch, validation_steps)
   1730             val_sample_weights=val_sample_weights,
   1731             validation_steps=validation_steps,
-> 1732             epoch_logs=epoch_logs)
   1733 
   1734       callbacks.on_epoch_end(epoch, epoch_logs)

/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/tpu/python/tpu/keras_support.py in _pipeline_fit_loop_sample_wise(self, ins, callbacks, index_array, shuffle, batch_size, num_training_samples, indices_for_conversion_to_dense, do_validation, val_inputs, val_targets, val_sample_weights, validation_steps, epoch_logs)
   1786 
   1787       outs = f.pipeline_run(
-> 1788           cur_step_inputs=ins_last_batch, next_step_inputs=ins_batch)
   1789       ins_last_batch = ins_batch
   1790 

/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/tpu/python/tpu/keras_support.py in pipeline_run(***failed resolving arguments***)
   1334           next_input_tensors)
   1335       next_tpu_model_ops = self._tpu_model_ops_for_input_specs(
-> 1336           next_input_specs, next_step_infeed_manager)
   1337       infeed_dict = next_infeed_instance.make_feed_dict(next_tpu_model_ops)
   1338 

/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/tpu/python/tpu/keras_support.py in _tpu_model_ops_for_input_specs(self, input_specs, infeed_manager)
   1169                                                  infeed_manager)
   1170       self._compilation_cache[shape_key] = new_tpu_model_ops
-> 1171       self._test_model_compiles(new_tpu_model_ops)
   1172 
   1173     return self._compilation_cache[shape_key]

/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/tpu/python/tpu/keras_support.py in _test_model_compiles(self, tpu_model_ops)
   1107     start_time = time.time()
   1108 
-> 1109     result = K.get_session().run(tpu_model_ops.compile_op)
   1110     proto = tpu_compilation_result.CompilationResultProto()
   1111     proto.ParseFromString(result)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py in run(self, fetches, feed_dict, options, run_metadata)
    927     try:
    928       result = self._run(None, fetches, feed_dict, options_ptr,
--> 929                          run_metadata_ptr)
    930       if run_metadata:
    931         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1150     if final_fetches or final_targets or (handle and feed_dict_tensor):
   1151       results = self._do_run(handle, final_targets, final_fetches,
-> 1152                              feed_dict_tensor, options, run_metadata)
   1153     else:
   1154       results = []

/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1326     if handle is None:
   1327       return self._do_call(_run_fn, feeds, fetches, targets, options,
-> 1328                            run_metadata)
   1329     else:
   1330       return self._do_call(_prun_fn, handle, feeds, fetches)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1346           pass
   1347       message = error_interpolation.interpolate(message, self._graph)
-> 1348       raise type(e)(node_def, op, message)
   1349 
   1350   def _extend_graph(self):

InvalidArgumentError: Combined status information from 9 operations:

Status code: Invalid argument [2x]
  You must feed a value for placeholder tensor 'label' with dtype int32 and shape [256,12]
  	 [[node label (defined at <ipython-input-2-85a234430d50>:9) ]] [1x]
  You must feed a value for placeholder tensor 'label' with dtype int32 and shape [256,12]
  	 [[node label (defined at <ipython-input-2-85a234430d50>:9) ]]
  	 [[{{node GroupCrossDeviceControlEdges_0/TPUReplicate/_compile/_11823778269055837323/_17}}]] [1x]
(7 successful operations.)

Caused by op 'label', defined at:
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/usr/local/lib/python3.6/dist-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/local/lib/python3.6/dist-packages/ipykernel/kernelapp.py", line 477, in start
    ioloop.IOLoop.instance().start()
  File "/usr/local/lib/python3.6/dist-packages/tornado/ioloop.py", line 832, in start
    self._run_callback(self._callbacks.popleft())
  File "/usr/local/lib/python3.6/dist-packages/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/usr/local/lib/python3.6/dist-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/zmq/eventloop/zmqstream.py", line 536, in <lambda>
    self.io_loop.add_callback(lambda : self._handle_events(self.socket, 0))
  File "/usr/local/lib/python3.6/dist-packages/zmq/eventloop/zmqstream.py", line 450, in _handle_events
    self._handle_recv()
  File "/usr/local/lib/python3.6/dist-packages/zmq/eventloop/zmqstream.py", line 480, in _handle_recv
    self._run_callback(callback, msg)
  File "/usr/local/lib/python3.6/dist-packages/zmq/eventloop/zmqstream.py", line 432, in _run_callback
    callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/usr/local/lib/python3.6/dist-packages/ipykernel/kernelbase.py", line 235, in dispatch_shell
    handler(stream, idents, msg)
  File "/usr/local/lib/python3.6/dist-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/usr/local/lib/python3.6/dist-packages/ipykernel/ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/usr/local/lib/python3.6/dist-packages/ipykernel/zmqshell.py", line 533, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py", line 2718, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py", line 2822, in run_ast_nodes
    if self.run_code(code, result):
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py", line 2882, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-18d98e7a13ff>", line 4, in <module>
    model = build_training_model(graph)
  File "<ipython-input-2-85a234430d50>", line 9, in build_training_model
    label        = Input(name = 'label',        batch_shape = [BATCH_SIZE, MAX_LABEL_LENGTH], dtype = 'int32')
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/input_layer.py", line 231, in Input
    input_tensor=tensor)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/input_layer.py", line 107, in __init__
    name=self.name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/backend.py", line 876, in placeholder
    x = array_ops.placeholder(dtype, shape=shape, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/array_ops.py", line 2077, in placeholder
    return gen_array_ops.placeholder(dtype=dtype, shape=shape, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 5791, in placeholder
    "Placeholder", dtype=dtype, shape=shape, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Combined status information from 9 operations:

Status code: Invalid argument [2x]
  You must feed a value for placeholder tensor 'label' with dtype int32 and shape [256,12]
  	 [[node label (defined at <ipython-input-2-85a234430d50>:9) ]] [1x]
  You must feed a value for placeholder tensor 'label' with dtype int32 and shape [256,12]
  	 [[node label (defined at <ipython-input-2-85a234430d50>:9) ]]
  	 [[{{node GroupCrossDeviceControlEdges_0/TPUReplicate/_compile/_11823778269055837323/_17}}]] [1x]
(7 successful operations.)
```

I also tried training the model using `model.fit_generator(...)` and `tf.keras.utils.Sequence`, but the same exception gets thrown.

**Comment by jvishnuvardhan** [comment]
I was able to reproduce the issue with TF1.13.1. No error when GPU was used but there is an `InvalidArgumentError` when TPU was used. Thanks!

**Comment by JunsW** [comment]
Is there any workaround for this issue? Really need TPU to save my life😭.

**Comment by jhseu** [comment]
We have improved Keras coverage in the when running a nightly version for your TPU (you'll have to also install tf-nightly in your VM). Also that API is deprecated, and the official usage is here:
https://github.com/tensorflow/tpu/tree/master/models/experimental/resnet50_keras

We haven't tested everything, so you may run into other issues.

**Comment by RunningDongxu** [comment]
has anyone solved this issue?

**Comment by sushreebarsa** [comment]
Hi There,

We are checking to see if you still need help on this issue, as you are using an older version of tensorflow(1.x) which is officially considered as end of life. We recommend that you upgrade to 2.4 or later version and let us know if the issue still persists in newer versions.we will get you the right help.Thanks!

**Comment by Saduf2019** [comment]
@NMAC427 

Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)
To know more see;
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999
