### ISSUE TITLE
install on mac gives ImportError: cannot import name symbol_database

### ISSUE THREAD

**Issue by evolu8** [tensorflow/tensorflow#282]
protobuf is not happy. What can I do?
```
import tensorflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/philipteare/anaconda/lib/python2.7/site-packages/tensorflow/__init__.py", line 4, in <module>
    from tensorflow.python import *
  File "/Users/philipteare/anaconda/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 13, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/Users/philipteare/anaconda/lib/python2.7/site-packages/tensorflow/core/framework/graph_pb2.py", line 9, in <module>
    from google.protobuf import symbol_database as _symbol_database
ImportError: cannot import name symbol_database
```

**Comment by vrv** [comment]
Most likely the runtime is selecting too old a version of protobuf -- we require protobuf 3.0.0.a3 or higher.

I'd see if any other installed version of protobuf is somehow interfering.

**Comment by evolu8** [comment]
I'm on a lower version. Anyone got tips on upgrading. Preferably on anaconda

**Comment by victorv** [comment]
If you have brew installed on OS X, you can use "brew reinstall --devel protobuf" to upgrade your protobuf to 3.0.x (experimental). This fixes the error.

**Comment by evolu8** [comment]
Thank you. Close, but:

/usr/local/Cellar/protobuf/3.0.0-alpha-2/include/google/protobuf/stubs/pbconfig.h:3:37:
note: expanded from macro 'GOOGLE_PROTOBUF_HASH_MAP_H'

 #define GOOGLE_PROTOBUF_HASH_MAP_H <unordered_map>

                                    ^

2 errors generated.

error: command 'clang' failed with exit status 1

________

Phil Teare
evolu8 Ltd
________

**Comment by victorv** [comment]
Did you do a "brew doctor" to see if you have a unlinked packages or pathing issues?
Did you "brew update"?
If these fail, try brew upgrade which will upgrade all installed packages to the latest versions.

**Comment by vrv** [comment]
Related to not having the right version of protobuf installed, closing due to inactivity.

**Comment by cybertk** [comment]
Fixed by upgrading protobuf, like @vrv pointed.
