### ISSUE TITLE
Migrating to 2.0 with confusing MultiRNNCell

### ISSUE THREAD

**Issue by nicoosokhan** [tensorflow/tensorflow#28216]
While upgrading my project to tensorflow 2.0, this part of the code is confusing me.

## In tensorflow 1.13.1
```
num_layers = 2
num_units = 128

rnn = tf.contrib.rnn.MultiRNNCell(
            [
                tf.contrib.rnn.BasicLSTMCell(
                    num_units,
                    forget_bias=0.0,
                    state_is_tuple=False,
                )
                for _ in range(num_layers)
            ],
            state_is_tuple=False,
        )

# x.shape == (?, 128)  and state.shape == (?, 512)

x, state = rnn(x, state)

# x.shape == (?, 128)  and state.shape == (?, 512)
```
Everey thing is working fine.

## Upgraded to tensorflow 2.0-alpha0

As documentation: 
https://www.tensorflow.org/api_docs/python/tf/keras/layers/StackedRNNCells

```
cells = [
        tf.keras.layers.LSTMCell(num_units) for _ in range(num_layers)
    ]
rnn = tf.keras.layers.RNN(cells)

# x.shape == (?, 128)  and state.shape == (?, 512)

x, state = rnn(x, state)


but here I got an error and I think is related to shapes of `x` and `state`:



Traceback (most recent call last):
  File "run.py", line 285, in <module>
    main()
  File "run.py", line 253, in main
    channels=parameters.channels,
  File "/home/nicoo/py/aocr/400/aocr/model/model.py", line 168, in __init__
    training=not self.forward_only,
  File "/home/nicoo/py/aocr/400/aocr/model/seq2seq_model.py", line 82, in __init__
    hidden_features,
  File "/home/nicoo/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 554, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/home/nicoo/py/aocr/400/aocr/model/Decoder.py", line 39, in call
    cell_output, state = self.cell(x, state)
  File "/home/nicoo/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/keras/layers/recurrent.py", line 750, in __call__
    return super(RNN, self).__call__(inputs, **kwargs)
  File "/home/nicoo/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 538, in __call__
    self._maybe_build(inputs)
  File "/home/nicoo/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1603, in _maybe_build
    self.build(input_shapes)
  File "/home/nicoo/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/keras/layers/recurrent.py", line 619, in build
    self.cell.build(step_input_shape)
  File "/home/nicoo/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/keras/utils/tf_utils.py", line 151, in wrapper
    output_shape = fn(instance, input_shape)
  File "/home/nicoo/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/keras/layers/recurrent.py", line 153, in build
    cell.build(input_shape)
  File "/home/nicoo/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/keras/utils/tf_utils.py", line 151, in wrapper
    output_shape = fn(instance, input_shape)
  File "/home/nicoo/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/keras/layers/recurrent.py", line 2022, in build
    constraint=self.kernel_constraint)
  File "/home/nicoo/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 349, in add_weight
    aggregation=aggregation)
  File "/home/nicoo/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/training/checkpointable/base.py", line 607, in _add_variable_with_custom_getter
    **kwargs_for_getter)
  File "/home/nicoo/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer_utils.py", line 145, in make_variable
    aggregation=aggregation)
  File "/home/nicoo/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 213, in __call__
    return cls._variable_v1_call(*args, **kwargs)
  File "/home/nicoo/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 176, in _variable_v1_call
    aggregation=aggregation)
  File "/home/nicoo/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 155, in <lambda>
    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
  File "/home/nicoo/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 2488, in default_variable_creator
    import_scope=import_scope)
  File "/home/nicoo/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 217, in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)
  File "/home/nicoo/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 294, in __init__
    constraint=constraint)
  File "/home/nicoo/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 406, in _init_from_args
    initial_value() if init_from_fn else initial_value,
  File "/home/nicoo/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer_utils.py", line 127, in <lambda>
    shape, dtype=dtype, partition_info=partition_info)
  File "/home/nicoo/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/ops/init_ops.py", line 499, in __call__
    scale /= max(1., (fan_in + fan_out) / 2.)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
```

**Comment by soloice** [comment]
`tf.contrib.rnn.MultiRNNCell` is an `RNNCell`, while `tf.keras.layers.RNN` is an `RNN API` (like `tf.nn.dynamic_rnn`) instead of a kind of `RNNCell`. An `RNNCell` defines how **a single time step** is computed, while an `RNN API` loops an `RNNCell` through **all time steps**.
So you need `tf.keras.layers.StackedRNNCells`(which is a kind of `RNNCell`)  instead of `tf.keras.layers.RNN`. The following code should work:

```
num_layers = 2
num_units = 128
batch_size = 20
embedding_size = 50

cells = [tf.keras.layers.LSTMCell(num_units) for _ in range(num_layers)]
rnn = tf.keras.layers.StackedRNNCells(cells)

# shape of x: [B, D]
x = tf.Variable(tf.random.normal([batch_size, embedding_size]), dtype=tf.float32)
# shape of state: (([B, H], [B, H]), ([B, H], [B, H]))
state = rnn.get_initial_state(x)

# shape of output: [B, H]
# shape of new_state: (([B, H], [B, H]), ([B, H], [B, H]))
output, new_state = rnn(x, state)

print(output)
print(new_state)

```

**Comment by nicoosokhan** [comment]
Thank you.

**Comment by gadagashwini** [comment]
@nicoosokhan Were you able to resolve this issue ?

**Comment by nicoosokhan** [comment]
> @nicoosokhan Were you able to resolve this issue ?

Yes, by using @soloice description I have rewritten this part of the code.
The main consideration was migrating to Tensorflow 2 without changing the network.

```
class MultiCellRNN(tf.keras.layers.Layer):

    def __init__(self, num_layers, num_units, **kwargs):
        super().__init__(**kwargs)

        self.cells = [
            tf.keras.layers.LSTMCell(
                num_units,
            )
            for _ in range(num_layers)
        ]

        self.cell = tf.keras.layers.StackedRNNCells(
            self.cells,
        )

    def call(self, x, state, **kwargs):

        state = tf.split(state, [128, 128, 128, 128], 1)
        x, state = self.cell(x, ([state[0], state[1]], [state[2], state[3]]))
        state = tf.concat([state[0][0], state[0][1], state[1][0], state[1][1]], 1)

        return x, state
```

I know that this is a dirty refactoring, but this was exactly what `tf.contrib.rnn.MultiRNNCell` old api do with `concatenated state` to have `tuple states`.

I hope to refactor this hardcoded section as soon as possible.

Thanks for the community.

**Comment by gadagashwini** [comment]
Closing since its resolved. Thanks!

**Comment by msinto93** [comment]
I'm not convinced this is resolved. The proposed solution means we now have to process the sequences on a step by step basis. What if we want to use the RNN API (i.e. process entire sequence) with StackedRNNCells?
