### ISSUE TITLE
python 3.6 unable to import tensorflow

### ISSUE THREAD

**Issue by pardeep3december** [tensorflow/tensorflow#28234]
Unable to import tensorflow in python 3.6
#######################
pip3 list 
:\Users\ADMIN>pip3 list
EPRECATION: The default format will switch to columns in the future. You can us
 --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.con
 under the [list] section) to disable this warning.
bsl-py (0.7.1)
stor (0.7.1)
ast (0.2.2)
rpcio (1.20.1)
5py (2.9.0)
eras-Applications (1.0.7)
eras-Preprocessing (1.0.9)
arkdown (3.1)
ock (2.0.0)
umpy (1.16.3)
br (5.2.0)
ip (9.0.1)
rotobuf (3.7.1)
etuptools (28.8.0)
ix (1.12.0)
ensorboard (1.13.1)
ensorflow (1.13.1)
ensorflow-estimator (1.13.0)
ermcolor (1.1.0)
erkzeug (0.15.2)
heel (0.33.1)
ou are using pip version 9.0.1, however version 19.1 is available.
ou should consider upgrading via the 'python -m pip install --upgrade pip' comm
nd.

:\Users\ADMIN>
#######################
C:\Users\ADMIN>python
Python 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AM
D64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "C:\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow
.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow
_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow
_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, descript
ion)
  File "C:\Python\Python36\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Python\Python36\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialisation routin
e failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python\Python36\lib\site-packages\tensorflow\__init__.py", line 24, i
n <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-im
port
  File "C:\Python\Python36\lib\site-packages\tensorflow\python\__init__.py", lin
e 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow
.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow
.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow
_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow
_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, descript
ion)
  File "C:\Python\Python36\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Python\Python36\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialisation routin
e failed.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
>>>

C:\Users\ADMIN>tensorflowpython -c "import tensorflow as tf; print(tf.version.GI
T_VERSION, tf.version.VERSION)
'tensorflowpython' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\ADMIN>tensorflow python -c "import tensorflow as tf; print(tf.version.G
IT_VERSION, tf.version.VERSION)
'tensorflow' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\ADMIN>python -c "import tensorflow as tf; print(tf.version.GIT_VERSION,
 tf.version.VERSION)
Traceback (most recent call last):
  File "C:\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow
.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow
_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow
_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, descript
ion)
  File "C:\Python\Python36\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Python\Python36\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialisation routin
e failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python\Python36\lib\site-packages\tensorflow\__init__.py", line 24, i
n <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-im
port
  File "C:\Python\Python36\lib\site-packages\tensorflow\python\__init__.py", lin
e 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow
.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow
.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow
_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow
_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, descript
ion)
  File "C:\Python\Python36\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Python\Python36\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialisation routin
e failed.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

C:\Users\ADMIN>

------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 8.1
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
- **TensorFlow installed from (source or binary)**: https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.13.1-cp36-cp36m-win_amd64.whl
- **TensorFlow version (use command below)**: pip3 install https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.13.1-cp36-cp36m-win_amd64.whl
- **Python version**: 3.6
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:

You can collect some of this information using our environment capture script:

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

You can obtain the TensorFlow version with:

```bash
python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"
```

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Comment by gadagashwini** [comment]
@pardeep3december, Please refer the similar issue on  [#23683](https://github.com/tensorflow/tensorflow/issues/23683). And let us know if that helps.  Thanks!

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by gadagashwini** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
