### ISSUE TITLE
autograph throwing "could not get source code" on recent nightlies

### ISSUE THREAD

**Issue by skeydan** [tensorflow/tensorflow#28316]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): linux fedora 29
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): e.g. , 2.0.0-dev20190501
- Python version: 3.6
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: NA
- GPU model and memory: NA

On recent nightly builds - v2 as well as v1 - the following fails:

```
# in p.py
@tf.function
def add(a,b): return(a+b)
```

```
# called in shell
In [2]: import tensorflow as tf                                                                                                                                                                                    

In [3]: exec(open("p.py").read()) 
   ...: add(1,2)  
```

Error stack:

```
2019-05-01 20:36:06.363503: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-05-01 20:36:06.401892: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2904000000 Hz
2019-05-01 20:36:06.402171: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x560bd15a4920 executing computations on platform Host. Devices:
2019-05-01 20:36:06.402190: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
Converted call: <function add at 0x7f56080b1400> 
    args: (1, 2)
    kwargs: {}

Entity <function add at 0x7f56080b1400> is not cached for key <code object add at 0x7f55ed2e68a0, file "<string>", line 1> subkey (<tensorflow.python.autograph.core.converter.ConversionOptions object at 0x7f55ed284978>, frozenset())
Converting <function add at 0x7f56080b1400>
Error transforming <function add at 0x7f56080b1400>
Traceback (most recent call last):
  File "/home/key/anaconda3/envs/r-tensorflow/lib/python3.6/site-packages/tensorflow/python/autograph/pyct/parser.py", line 53, in parse_entity
    source = inspect_utils.getimmediatesource(entity)
  File "/home/key/anaconda3/envs/r-tensorflow/lib/python3.6/site-packages/tensorflow/python/autograph/pyct/inspect_utils.py", line 124, in getimmediatesource
    lines, lnum = inspect.findsource(obj)
  File "/home/key/anaconda3/envs/r-tensorflow/lib/python3.6/inspect.py", line 786, in findsource
    raise OSError('could not get source code')
OSError: could not get source code

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/key/anaconda3/envs/r-tensorflow/lib/python3.6/site-packages/tensorflow/python/autograph/impl/api.py", line 440, in to_graph
    return conversion.convert(entity, program_ctx)
  File "/home/key/anaconda3/envs/r-tensorflow/lib/python3.6/site-packages/tensorflow/python/autograph/impl/conversion.py", line 309, in convert
    entity, program_ctx, free_nonglobal_var_names)
  File "/home/key/anaconda3/envs/r-tensorflow/lib/python3.6/site-packages/tensorflow/python/autograph/impl/conversion.py", line 232, in _convert_with_cache
    entity, program_ctx)
  File "/home/key/anaconda3/envs/r-tensorflow/lib/python3.6/site-packages/tensorflow/python/autograph/impl/conversion.py", line 440, in convert_entity_to_ast
    nodes, name, entity_info = convert_func_to_ast(o, program_ctx)
  File "/home/key/anaconda3/envs/r-tensorflow/lib/python3.6/site-packages/tensorflow/python/autograph/impl/conversion.py", line 603, in convert_func_to_ast
    node, source = parser.parse_entity(f, future_features=future_features)
  File "/home/key/anaconda3/envs/r-tensorflow/lib/python3.6/site-packages/tensorflow/python/autograph/pyct/parser.py", line 61, in parse_entity
    ' @tf.autograph.do_not_convert. Original error: {}'.format(entity, e))
ValueError: Unable to locate the source code of <function add at 0x7f56080b1400>. Note that functions defined in certain environments, like the interactive Python shell do not expose their source code. If that is the case, you should to define them in a .py source file. If you are certain the code is graph-compatible, wrap the call using @tf.autograph.do_not_convert. Original error: could not get source code
Error transforming entity <function add at 0x7f56080b1400>
Traceback (most recent call last):
  File "/home/key/anaconda3/envs/r-tensorflow/lib/python3.6/site-packages/tensorflow/python/autograph/pyct/parser.py", line 53, in parse_entity
    source = inspect_utils.getimmediatesource(entity)
  File "/home/key/anaconda3/envs/r-tensorflow/lib/python3.6/site-packages/tensorflow/python/autograph/pyct/inspect_utils.py", line 124, in getimmediatesource
    lines, lnum = inspect.findsource(obj)
  File "/home/key/anaconda3/envs/r-tensorflow/lib/python3.6/inspect.py", line 786, in findsource
    raise OSError('could not get source code')
OSError: could not get source code

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/key/anaconda3/envs/r-tensorflow/lib/python3.6/site-packages/tensorflow/python/autograph/impl/api.py", line 440, in to_graph
    return conversion.convert(entity, program_ctx)
  File "/home/key/anaconda3/envs/r-tensorflow/lib/python3.6/site-packages/tensorflow/python/autograph/impl/conversion.py", line 309, in convert
    entity, program_ctx, free_nonglobal_var_names)
  File "/home/key/anaconda3/envs/r-tensorflow/lib/python3.6/site-packages/tensorflow/python/autograph/impl/conversion.py", line 232, in _convert_with_cache
    entity, program_ctx)
  File "/home/key/anaconda3/envs/r-tensorflow/lib/python3.6/site-packages/tensorflow/python/autograph/impl/conversion.py", line 440, in convert_entity_to_ast
    nodes, name, entity_info = convert_func_to_ast(o, program_ctx)
  File "/home/key/anaconda3/envs/r-tensorflow/lib/python3.6/site-packages/tensorflow/python/autograph/impl/conversion.py", line 603, in convert_func_to_ast
    node, source = parser.parse_entity(f, future_features=future_features)
  File "/home/key/anaconda3/envs/r-tensorflow/lib/python3.6/site-packages/tensorflow/python/autograph/pyct/parser.py", line 61, in parse_entity
    ' @tf.autograph.do_not_convert. Original error: {}'.format(entity, e))
ValueError: Unable to locate the source code of <function add at 0x7f56080b1400>. Note that functions defined in certain environments, like the interactive Python shell do not expose their source code. If that is the case, you should to define them in a .py source file. If you are certain the code is graph-compatible, wrap the call using @tf.autograph.do_not_convert. Original error: could not get source code

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/key/anaconda3/envs/r-tensorflow/lib/python3.6/site-packages/tensorflow/python/autograph/impl/api.py", line 325, in converted_call
    experimental_optional_features=options.optional_features)
  File "/home/key/anaconda3/envs/r-tensorflow/lib/python3.6/site-packages/tensorflow/python/autograph/impl/api.py", line 442, in to_graph
    errors.report_internal_error(entity, e)
  File "/home/key/anaconda3/envs/r-tensorflow/lib/python3.6/site-packages/tensorflow/python/autograph/pyct/errors.py", line 99, in report_internal_error
    'report. Caused by: %s' % (entity, exception))
tensorflow.python.autograph.pyct.errors.AutoGraphError: Unexpected error transforming <function add at 0x7f56080b1400>. If you believe this is due to a bug, please set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output when filing the bug report. Caused by: Unable to locate the source code of <function add at 0x7f56080b1400>. Note that functions defined in certain environments, like the interactive Python shell do not expose their source code. If that is the case, you should to define them in a .py source file. If you are certain the code is graph-compatible, wrap the call using @tf.autograph.do_not_convert. Original error: could not get source code
WARNING: Logging before flag parsing goes to stderr.
W0501 20:36:06.408588 140007718111040 ag_logging.py:145] Entity <function add at 0x7f56080b1400> could not be transformed and will be executed as-is. Some features (e.g. tensor-dependent conditionals and loops) may not work as expected. Error details can be found in the logs when running with the env variable AUTOGRAPH_VERBOSITY >= 1. Please report this to the AutoGraph team. Cause: Unexpected error transforming <function add at 0x7f56080b1400>. If you believe this is due to a bug, please set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output when filing the bug report. Caused by: Unable to locate the source code of <function add at 0x7f56080b1400>. Note that functions defined in certain environments, like the interactive Python shell do not expose their source code. If that is the case, you should to define them in a .py source file. If you are certain the code is graph-compatible, wrap the call using @tf.autograph.do_not_convert. Original error: could not get source code
WARNING: Entity <function add at 0x7f56080b1400> could not be transformed and will be executed as-is. Some features (e.g. tensor-dependent conditionals and loops) may not work as expected. Error details can be found in the logs when running with the env variable AUTOGRAPH_VERBOSITY >= 1. Please report this to the AutoGraph team. Cause: Unexpected error transforming <function add at 0x7f56080b1400>. If you believe this is due to a bug, please set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output when filing the bug report. Caused by: Unable to locate the source code of <function add at 0x7f56080b1400>. Note that functions defined in certain environments, like the interactive Python shell do not expose their source code. If that is the case, you should to define them in a .py source file. If you are certain the code is graph-compatible, wrap the call using @tf.autograph.do_not_convert. Original error: could not get source code

```

Thanks!

**Comment by skeydan** [comment]
When I use

```
import(p)
```

to source the file instead of 

```
exec(open("p.py").read()) 
```

it works...

**Comment by muddham** [comment]
@skeydan Can you please let us know if you are happy to close this issue as in previous comment it says that after doing import(p), it worked.

**Comment by skeydan** [comment]
I can close it, I'd just be wondering why the first variant wouldn't work?

**Comment by captain-pool** [comment]
> I can close it, I'd just be wondering why the first variant wouldn't work?

Hey @skeydan , It actually worked both ways.
I'm using 2.0.0-alpha0

**Comment by muddham** [comment]
@skeydan As you confirmed its working, closing this issue
