### ISSUE TITLE
Max retries error with BigtableClient

### ISSUE THREAD

**Issue by cwbeitel** [tensorflow/tensorflow#28327]
For reference, pertains to [`tf.contrib.cloud.bigtable_api.py`](https://github.com/tensorflow/tensorflow/blob/r1.13/tensorflow/contrib/bigtable/python/ops/bigtable_api.py) and `BigtableClient`.

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Not really

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 'v1.13.1-0-g6612da8951' 1.13.1
- Python version: 3.6.4
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: None
- GPU model and memory: None

**Describe the current behavior**

Dataset constructed by way of `tf.contrib.cloud.BigtableClient` raises error that is primarily the following:

```bash
InternalError (see above for traceback): Error reading from Cloud Bigtable: No more retries allowed as per policy.
	 [[node IteratorGetNext (defined at <ipython-input-1-b90b20ec4e01>:10) ]]
```

This occurs both in graph and eager mode; occurs on a machine where the conventional bigtable python client apis function properly (appropriately credentialed); persists after alternatively activating a service account with the appropriate credentials via `gcloud auth activate-service-account ...`.

**Describe the expected behavior**

Iterator yields training examples from Dataset when iterated over without error.

**Code to reproduce the issue**

```python
from pcml.operations.tfrecord2bigtable import BigTableSelection
import tensorflow as tf

data = BigTableSelection(
    project="clarify",
    instance="clarify-cbt-instance",
    table="clarify-cbt-devtabl1",
    prefix="train",
    column_family="tfexample",
    column_qualifier="example")

client = tf.contrib.cloud.BigtableClient(data.project, data.instance)

table = client.table(data.table)

ds = table.parallel_scan_prefix(
    data.prefix, columns=[(data.column_family, data.column_qualifier)])

ds_data = ds.map(lambda index, data: data)

ds_data = ds_data.repeat()

iterator = ds_data.make_initializable_iterator()

next_element = iterator.get_next()

sess = tf.Session()

sess.run(iterator.initializer)

_ = sess.run(next_element)

```

**Other info / logs**

```bash
​
WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

INFO:tensorflow:Entry Point [tensor2tensor.envs.tic_tac_toe_env:TicTacToeEnv] registered with id [T2TEnv-TicTacToeEnv-v0]
WARNING:tensorflow:From /opt/conda/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py:1419: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
---------------------------------------------------------------------------
InternalError                             Traceback (most recent call last)
/opt/conda/lib/python3.6/site-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1333     try:
-> 1334       return fn(*args)
   1335     except errors.OpError as e:

/opt/conda/lib/python3.6/site-packages/tensorflow/python/client/session.py in _run_fn(feed_dict, fetch_list, target_list, options, run_metadata)
   1318       return self._call_tf_sessionrun(
-> 1319           options, feed_dict, fetch_list, target_list, run_metadata)
   1320 

/opt/conda/lib/python3.6/site-packages/tensorflow/python/client/session.py in _call_tf_sessionrun(self, options, feed_dict, fetch_list, target_list, run_metadata)
   1406         self._session, options, feed_dict, fetch_list, target_list,
-> 1407         run_metadata)
   1408 

InternalError: Error reading from Cloud Bigtable: No more retries allowed as per policy.
	 [[{{node IteratorGetNext}}]]

During handling of the above exception, another exception occurred:

InternalError                             Traceback (most recent call last)
<ipython-input-1-acb694909ee3> in <module>
     29 
     30 sess.run(iterator.initializer)
---> 31 _ = sess.run(next_element)
     32 

/opt/conda/lib/python3.6/site-packages/tensorflow/python/client/session.py in run(self, fetches, feed_dict, options, run_metadata)
    927     try:
    928       result = self._run(None, fetches, feed_dict, options_ptr,
--> 929                          run_metadata_ptr)
    930       if run_metadata:
    931         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

/opt/conda/lib/python3.6/site-packages/tensorflow/python/client/session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1150     if final_fetches or final_targets or (handle and feed_dict_tensor):
   1151       results = self._do_run(handle, final_targets, final_fetches,
-> 1152                              feed_dict_tensor, options, run_metadata)
   1153     else:
   1154       results = []

/opt/conda/lib/python3.6/site-packages/tensorflow/python/client/session.py in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1326     if handle is None:
   1327       return self._do_call(_run_fn, feeds, fetches, targets, options,
-> 1328                            run_metadata)
   1329     else:
   1330       return self._do_call(_prun_fn, handle, feeds, fetches)

/opt/conda/lib/python3.6/site-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1346           pass
   1347       message = error_interpolation.interpolate(message, self._graph)
-> 1348       raise type(e)(node_def, op, message)
   1349 
   1350   def _extend_graph(self):

InternalError: Error reading from Cloud Bigtable: No more retries allowed as per policy.
	 [[node IteratorGetNext (defined at <ipython-input-1-acb694909ee3>:26) ]]

Caused by op 'IteratorGetNext', defined at:
  File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/opt/conda/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/opt/conda/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 486, in start
    self.io_loop.start()
  File "/opt/conda/lib/python3.6/site-packages/tornado/platform/asyncio.py", line 127, in start
    self.asyncio_loop.run_forever()
  File "/opt/conda/lib/python3.6/asyncio/base_events.py", line 421, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.6/asyncio/base_events.py", line 1431, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/opt/conda/lib/python3.6/site-packages/tornado/platform/asyncio.py", line 117, in _handle_events
    handler_func(fileobj, events)
  File "/opt/conda/lib/python3.6/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 450, in _handle_events
    self._handle_recv()
  File "/opt/conda/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 480, in _handle_recv
    self._run_callback(callback, msg)
  File "/opt/conda/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 432, in _run_callback
    callback(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/opt/conda/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "/opt/conda/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/opt/conda/lib/python3.6/site-packages/ipykernel/ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/opt/conda/lib/python3.6/site-packages/ipykernel/zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/home/jovyan/.local/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2843, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "/home/jovyan/.local/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2869, in _run_cell
    return runner(coro)
  File "/home/jovyan/.local/lib/python3.6/site-packages/IPython/core/async_helpers.py", line 67, in _pseudo_sync_runner
    coro.send(None)
  File "/home/jovyan/.local/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3044, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "/home/jovyan/.local/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3209, in run_ast_nodes
    if (yield from self.run_code(code, result)):
  File "/home/jovyan/.local/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3291, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-1-acb694909ee3>", line 26, in <module>
    next_element = iterator.get_next()
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 414, in get_next
    output_shapes=self._structure._flat_shapes, name=name)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 1685, in iterator_get_next
    output_shapes=output_shapes, name=name)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

InternalError (see above for traceback): Error reading from Cloud Bigtable: No more retries allowed as per policy.
	 [[node IteratorGetNext (defined at <ipython-input-1-acb694909ee3>:26) ]]
```

**Comment by cwbeitel** [comment]
Further suggesting this is a credential issue the following modification to use `keys_by_prefix_dataset` gives an explicit error about credentials.

```python

import os
import tensorflow as tf
from pcml.operations.tfrecord2bigtable import BigTableSelection

data = BigTableSelection(
    project="clarify",
    instance="clarify-cbt-instance",
    table="clarify-cbt-devtable1",
    prefix="train",
    column_family="tfexample",
    column_qualifier="example")

client = tf.contrib.cloud.BigtableClient(data.project, data.instance)
table = client.table(data.table)
key_dataset = table.keys_by_prefix_dataset("train")
ds = key_dataset.apply(table.lookup_columns(("cf1", "tfexample")))
ds_data = ds.map(lambda index, data: data)
ds_data = ds_data.repeat()

iterator = ds_data.make_initializable_iterator()
next_element = iterator.get_next()

sess = tf.Session()
sess.run(iterator.initializer)
_ = sess.run(next_element)

```

with error:

```bash
UnauthenticatedError (see above for traceback): Error reading from Cloud Bigtable: Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
	 [[node IteratorGetNext_2 (defined at <ipython-input-26-f0eff0cf13a5>:36) ]]
```

This occurring with and without `GOOGLE_APPLICATION_CREDENTIALS` being set explicitly and verified application-default-credentials are indeed set (`gcloud auth application-default print-access-token` prints an access token).

As you can tell my intuition is that the issue has either to do with the compiled client op not properly discovering and using credentials or the client machine being mis-configured vis. credentials.

**Comment by cwbeitel** [comment]
So this appears to be resolved (at least on my end) by resolving issues with both parameterization and environment credentials. In the former case the retries error can be produced if e.g. a non-existent table name or the wrong column family is provided. In the latter case I'm seeing the error occur if I don't unset `GOOGLE_APPLICATION_CREDENTIALS` which in my case is pointing to a default GCP service account (which in my case does not have the necessary scopes) instead of the service account that is activated and being used otherwise.

```python

import os
import tensorflow as tf
from pcml.operations.tfrecord2bigtable import BigTableSelection

os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = ""

data = BigTableSelection(
    project="clarify",
    instance="clarify-cbt-instance",
    table="clarify-cbt-devtable",
    prefix="train",
    column_family="tfexample",
    column_qualifier="example")

client = tf.contrib.cloud.BigtableClient(data.project, data.instance)
table = client.table(data.table)

# ===
# Option 1
key_dataset = table.keys_by_prefix_dataset(data.prefix)
ds = key_dataset.apply(table.lookup_columns((data.column_family,
                                             data.column_qualifier)))
# ===
# Option 2
ds = table.parallel_scan_prefix(
    data.prefix, columns=[(data.column_family, data.column_qualifier)])
# ===

ds_data = ds.map(lambda index, data: data)
ds_data = ds_data.repeat()
iterator = ds_data.make_initializable_iterator()
next_element = iterator.get_next()

sess = tf.Session()
sess.run(iterator.initializer)
_ = sess.run(next_element)

```

**Comment by ymodak** [comment]
Closing this issue since its resolved. Feel free to reopen if still having problems. Thanks!
