### ISSUE TITLE
Cannot import tensorflow on yarn

### ISSUE THREAD

**Issue by alansplaza** [tensorflow/tensorflow#28419]
When I tried to upload all tensorflow and google.protocol pkgs to yarn, I come across a problem like this

```
Traceback (most recent call last):
  File "/data05/yarn/nmdata/usercache/tiger/appcache/application_1557054435006_18114/container_e117_1557054435006_18114_01_000009/./mapreduce_text.py", line 34, in <module>
    from extract_features_tmp import predict
  File "./bert/bin/extract_features_tmp.py", line 15, in <module>
    import tensorflow as tf
  File "./tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "./tensorflow/python/__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "./tensorflow/core/framework/graph_pb2.py", line 8, in <module>
    from google.protobuf import reflection as _reflection
  File "/data01/yarn/nmdata/usercache/tiger/filecache/88784/google.tar.gz/protobuf/reflection.py", line 62, in <module>
    GeneratedProtocolMessageType = message_impl.GeneratedProtocolMessageType
AttributeError: 'module' object has no attribute 'GeneratedProtocolMessageType'
```
Why this happened? I used `tar -czvf` to compress tensorflow and protobuf, used -archives to upload these pkgs.tar.gz to yarn.

**Comment by achandraa** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by achandraa** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
