### ISSUE TITLE
TF2.0 MirroredStrategy Example failed on windows if GPU > 1

### ISSUE THREAD

**Issue by ziyigogogo** [tensorflow/tensorflow#28430]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No, Using the sample code in tensorflow docs
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Win10
- TensorFlow installed from (source or binary): pip install tensorflow-gpu==2.0.0-alpha0
- TensorFlow version (use command below): 2.0.0-alpha0 
- Python version: 3.7
- CUDA/cuDNN version: cuda10/cudnn7.5
- GPU model and memory: 2*1080ti

**Describe the current behavior**
```
import tensorflow_datasets as tfds
import tensorflow as tf

import os
datasets, info = tfds.load(name='mnist', with_info=True, as_supervised=True)
mnist_train, mnist_test = datasets['train'], datasets['test']
strategy = tf.distribute.MirroredStrategy()
print ('Number of devices: {}'.format(strategy.num_replicas_in_sync))
# You can also do info.splits.total_num_examples to get the total
# number of examples in the dataset.

num_train_examples = info.splits['train'].num_examples
num_test_examples = info.splits['test'].num_examples

BUFFER_SIZE = 10000

BATCH_SIZE_PER_REPLICA = 64
BATCH_SIZE = BATCH_SIZE_PER_REPLICA * strategy.num_replicas_in_sync

def scale(image, label):
  image = tf.cast(image, tf.float32)
  image /= 255

  return image, label

# train_dataset = mnist_train.map(scale).shuffle(BUFFER_SIZE).batch(BATCH_SIZE)
train_dataset = mnist_train.repeat(2).map(scale).shuffle(BUFFER_SIZE).batch(BATCH_SIZE)

eval_dataset = mnist_test.map(scale).batch(BATCH_SIZE)

with strategy.scope():
    model = tf.keras.Sequential([
      tf.keras.layers.Conv2D(32, 3, activation='relu', input_shape=(28, 28, 1)),
      tf.keras.layers.MaxPooling2D(),
      tf.keras.layers.Flatten(),
      tf.keras.layers.Dense(64, activation='relu'),
      tf.keras.layers.Dense(10, activation='softmax')
    ])

    model.compile(loss='sparse_categorical_crossentropy',
                optimizer=tf.keras.optimizers.Adam(),
                metrics=['accuracy'])
model.fit(train_dataset, epochs=10)

```
The code above is what i copy from [tf docs](https://github.com/tensorflow/docs/blob/master/site/en/r2/tutorials/distribute/keras.ipynb)
Which will result an Error like:
```
InvalidArgumentError: No OpKernel was registered to support Op 'NcclAllReduce' used by {{node training/Adam/NcclAllReduce}}with these attrs: [reduction="sum", T=DT_FLOAT, num_devices=1, shared_name="c0"]
Registered devices: [CPU, GPU]
Registered kernels:
  <no registered kernels>
	 [[training/Adam/NcclAllReduce]] [Op:__inference_keras_scratch_graph_1495]
```
At first I thought I had a wrong build of tensorflow without GPU support. However, when i re-installed the whole env exactly as the guide in the official site. Still the same result. And I found that if I uncomment the mirror strategy part, the code is working good
```
# with strategy.scope():
model = tf.keras.Sequential([
  tf.keras.layers.Conv2D(32, 3, activation='relu', input_shape=(28, 28, 1)),
  tf.keras.layers.MaxPooling2D(),
  tf.keras.layers.Flatten(),
  tf.keras.layers.Dense(64, activation='relu'),
  tf.keras.layers.Dense(10, activation='softmax')
])
model.compile(loss='sparse_categorical_crossentropy',
            optimizer=tf.keras.optimizers.Adam(),
            metrics=['accuracy'])
model.fit(train_dataset, epochs=10)
```
And another found is that I myself only have 2 gpus however, when tensorflow init, it prints "adding devices" 3 times which i thought should be 2:
```
2019-05-06 16:38:55.635182: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1546] Adding visible gpu devices: 0, 1
2019-05-06 16:39:01.691770: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1015] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-05-06 16:39:01.694145: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1021]      0 1 
2019-05-06 16:39:01.694243: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1034] 0:   N N 
2019-05-06 16:39:01.704826: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1034] 1:   N N 
2019-05-06 16:39:01.705405: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1149] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8791 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
2019-05-06 16:39:01.706830: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1149] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 8791 MB memory) -> physical GPU (device: 1, name: GeForce GTX 1080 Ti, pci bus id: 0000:02:00.0, compute capability: 6.1)
2019-05-06 16:39:02.008523: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1546] Adding visible gpu devices: 0, 1
2019-05-06 16:39:02.008834: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1015] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-05-06 16:39:02.009000: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1021]      0 1 
2019-05-06 16:39:02.009103: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1034] 0:   N N 
2019-05-06 16:39:02.009207: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1034] 1:   N N 
2019-05-06 16:39:02.009398: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1149] Created TensorFlow device (/device:GPU:0 with 8791 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
2019-05-06 16:39:02.021524: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1149] Created TensorFlow device (/device:GPU:1 with 8791 MB memory) -> physical GPU (device: 1, name: GeForce GTX 1080 Ti, pci bus id: 0000:02:00.0, compute capability: 6.1)
2019-05-06 16:39:04.813463: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1546] Adding visible gpu devices: 0, 1
2019-05-06 16:39:04.813706: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1015] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-05-06 16:39:04.813870: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1021]      0 1 
2019-05-06 16:39:04.813975: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1034] 0:   N N 
2019-05-06 16:39:04.814077: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1034] 1:   N N 
2019-05-06 16:39:04.814274: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1149] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8791 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
2019-05-06 16:39:04.815618: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1149] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 8791 MB memory) -> physical GPU (device: 1, name: GeForce GTX 1080 Ti, pci bus id: 0000:02:00.0, compute capability: 6.1)
```

**Describe the expected behavior**
The mirror strategy should work well on machine that have more than one GPU otherwise it is useless right? I found other related issues like: https://github.com/tensorflow/tensorflow/issues/28372 and https://github.com/tensorflow/tensorflow/issues/28334
They all reported that the scripts can run for 1 gpu and failed on gpu>=2
Any thought is appreciated!
**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
```
Traceback (most recent call last):
  File "D:/ziyi/EastAI2/models/test.py", line 82, in <module>
    model.fit(train_data, epochs=2, steps_per_epoch=100)
  File "C:\Users\jerry\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\training.py", line 746, in fit
    validation_freq=validation_freq)
  File "C:\Users\jerry\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\training_distributed.py", line 131, in fit_distributed
    steps_name='steps_per_epoch')
  File "C:\Users\jerry\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\training_arrays.py", line 263, in model_iteration
    batch_outs = f(actual_inputs)
  File "C:\Users\jerry\Anaconda3\lib\site-packages\tensorflow\python\keras\backend.py", line 3217, in __call__
    outputs = self._graph_fn(*converted_inputs)
  File "C:\Users\jerry\Anaconda3\lib\site-packages\tensorflow\python\eager\function.py", line 558, in __call__
    return self._call_flat(args)
  File "C:\Users\jerry\Anaconda3\lib\site-packages\tensorflow\python\eager\function.py", line 627, in _call_flat
    outputs = self._inference_function.call(ctx, args)
  File "C:\Users\jerry\Anaconda3\lib\site-packages\tensorflow\python\eager\function.py", line 415, in call
    ctx=ctx)
  File "C:\Users\jerry\Anaconda3\lib\site-packages\tensorflow\python\eager\execute.py", line 66, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'NcclAllReduce' used by {{node training/Adam/NcclAllReduce}}with these attrs: [reduction="sum", T=DT_FLOAT, num_devices=2, shared_name="c0"]
Registered devices: [CPU, GPU]
Registered kernels:
  <no registered kernels>

	 [[training/Adam/NcclAllReduce]] [Op:__inference_keras_scratch_graph_2200]

```

**Comment by rootkitchao** [comment]
Are you using AMD CPUs? As far as I know, NCCL sometimes has some problems on AMD CPUs.

**Comment by ziyigogogo** [comment]
> Are you using AMD CPUs? As far as I know, NCCL sometimes has some problems on AMD CPUs.

No, I'm using Intel. One question here, if i need to install NCCL seperatly? I thought it was automatically set by previous installation?

**Comment by ziyigogogo** [comment]
hi there, after a day-long searching, I finally kind of understand the concept. NCCL is a native library for GPUs communication which is only official supported for Linux. Thus here are two solutions:

1. find windows non-official version of NCCL (not recommend)
2. custom reduction OP like the [example](https://github.com/tensorflow/tensorflow/issues/21470#issuecomment-422506263)

**Comment by uqyge** [comment]
hit the same problem with nvidia k80
