### ISSUE TITLE
NPM Install failing

### ISSUE THREAD

**Issue by d3x0r** [tensorflow/tensorflow#28434]
I do hope this is the right place for this; there's no `issues` enabled on tensorflow/tfjs-node...

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
   - Windows 10

**Describe the problem**

downloading and unzipping is failing; apparently the unzip utility is running out of memory.  Should add an additional argument 
installing with node 11.9.0  x86 version.  Produces ths output at the end.

```
M:\javascript\tensorflow>npm install @tensorflow/tfjs-node-gpu

> @tensorflow/tfjs-node-gpu@1.1.2 install M:\javascript\tensorflow\node_modules\@tensorflow\tfjs-node-gpu
> node scripts/install.js gpu download

* Downloading libtensorflow
[==============================] 21249429/bps 100% 0.0s
(node:17992) UnhandledPromiseRejectionWarning: RangeError: Array buffer allocation failed
    at new ArrayBuffer (<anonymous>)
    at new Uint8Array (<anonymous>)
    at new FastBuffer (internal/buffer.js:788:1)
    at Function.alloc (buffer.js:280:10)
    at decompress (M:\javascript\tensorflow\node_modules\adm-zip\zipEntry.js:56:27)
    at Object.getData (M:\javascript\tensorflow\node_modules\adm-zip\zipEntry.js:242:12)
    at M:\javascript\tensorflow\node_modules\adm-zip\adm-zip.js:438:25
    at Array.forEach (<anonymous>)
    at Object.extractAllTo (M:\javascript\tensorflow\node_modules\adm-zip\adm-zip.js:432:17)
    at WriteStream.response.on.pipe.on (M:\javascript\tensorflow\node_modules\@tensorflow\tfjs-node-gpu\scripts\resources.js:70:21)
(node:17992) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by
ing a promise which was not handled with .catch(). (rejection id: 1)
(node:17992) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js proc
th a non-zero exit code.
npm WARN rollup-plugin-visualizer@1.1.1 requires a peer of rollup@>=0.60.0 but none is installed. You must install peer dependencies yourself.
npm WARN tensorflow@1.0.0 No description
npm WARN tensorflow@1.0.0 No repository field.

+ @tensorflow/tfjs-node-gpu@1.1.2
removed 649 packages, updated 2 packages and audited 62 packages in 57.866s
found 0 vulnerabilities

```

As I was writing this, decided to try x64 version; and it got past that point.
(node-gyp couldn't find msbuild.exe; but that's a different issue)

When I fix those issues... I still get

```
290 verbose stack Error: @tensorflow/tfjs-node-gpu@1.1.2 install: `node scripts/install.js gpu download`
290 verbose stack Exit status 1
290 verbose stack     at EventEmitter.<anonymous> (C:\Users\Panther\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
290 verbose stack     at EventEmitter.emit (events.js:197:13)
290 verbose stack     at ChildProcess.<anonymous> (C:\Users\Panther\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
290 verbose stack     at ChildProcess.emit (events.js:197:13)
290 verbose stack     at maybeClose (internal/child_process.js:978:16)
290 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
291 verbose pkgid @tensorflow/tfjs-node-gpu@1.1.2
292 verbose cwd M:\javascript\tensorflow
293 verbose Windows_NT 10.0.17134
294 verbose argv "h:\\dev2\\nodejs\\node.exe" "C:\\Users\\Panther\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "@tensorflow/tfjs-node-gpu"
```

Redirecting output to a log seems to make the download fail too...  So THIS is what I get now; and don't understand what's missing.

```

* Downloading libtensorflow
[==============================] 22424948/bps 100% 0.0s
[==============================] 2118839/bps 100% 0.0s
* Building TensorFlow Node.js bindings
M:\javascript\tensorflow\node_modules\@tensorflow\tfjs-node-gpu\scripts\install.js:165
      throw new Error('node-gyp rebuild failed with: ' + err);
      ^

Error: node-gyp rebuild failed with: Error: Command failed: node-gyp rebuild
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Panther\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:197:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "h:\\dev2\\nodejs\\node.exe" "C:\\Users\\Panther\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd M:\javascript\tensorflow\node_modules\@tensorflow\tfjs-node-gpu
gyp ERR! node -v v11.9.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

    at cp.exec (M:\javascript\tensorflow\node_modules\@tensorflow\tfjs-node-gpu\scripts\install.js:165:13)
    at ChildProcess.exithandler (child_process.js:304:5)
    at ChildProcess.emit (events.js:197:13)
    at maybeClose (internal/child_process.js:978:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
npm WARN rollup-plugin-visualizer@1.1.1 requires a peer of rollup@>=0.60.0 but none is installed. You must install peer dependencies yourself.
npm WARN tensorflow@1.0.0 No description
npm WARN tensorflow@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @tensorflow/tfjs-node-gpu@1.1.2 install: `node scripts/install.js gpu download`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @tensorflow/tfjs-node-gpu@1.1.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Panther\AppData\Roaming\npm-cache\_logs\2019-05-06T10_57_50_660Z-debug.log
```

(and the mentioned debug.log)

```
279 warn rollup-plugin-visualizer@1.1.1 requires a peer of rollup@>=0.60.0 but none is installed. You must install peer dependencies yourself.
280 warn tensorflow@1.0.0 No description
281 warn tensorflow@1.0.0 No repository field.
282 verbose stack Error: @tensorflow/tfjs-node-gpu@1.1.2 install: `node scripts/install.js gpu download`
282 verbose stack Exit status 1
282 verbose stack     at EventEmitter.<anonymous> (C:\Users\Panther\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
282 verbose stack     at EventEmitter.emit (events.js:197:13)
282 verbose stack     at ChildProcess.<anonymous> (C:\Users\Panther\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
282 verbose stack     at ChildProcess.emit (events.js:197:13)
282 verbose stack     at maybeClose (internal/child_process.js:978:16)
282 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
283 verbose pkgid @tensorflow/tfjs-node-gpu@1.1.2
284 verbose cwd M:\javascript\tensorflow
285 verbose Windows_NT 10.0.17134
286 verbose argv "h:\\dev2\\nodejs\\node.exe" "C:\\Users\\Panther\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "@tensorflow/tfjs-node-gpu"
287 verbose node v11.9.0
288 verbose npm  v6.4.1
289 error code ELIFECYCLE
290 error errno 1
291 error @tensorflow/tfjs-node-gpu@1.1.2 install: `node scripts/install.js gpu download`
291 error Exit status 1
292 error Failed at the @tensorflow/tfjs-node-gpu@1.1.2 install script.
292 error This is probably not a problem with npm. There is likely additional logging output above.
293 verbose exit [ 1, true ]
```

**Comment by d3x0r** [comment]
I did manage to do `npm install --force @tensorflow/tfjs-node-gpu` and keep what was partially built.
This is the output from visual studio (second build; the first build had similar error, but deleted the lib/tensorflow.dll too; I had re-run `npm run install` to get the download again before... )

```
1>------ Build started: Project: tfjs_binding, Configuration: Debug x64 ------
1>deps-stage
1>(node:18672) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, rename 'M:\javascript\tensorflow\node_modules\@tensorflow\tfjs-node-gpu\deps\lib\tensorflow.dll' -> 'M:\javascript\tensorflow\node_modules\@tensorflow\tfjs-node-gpu\build\Debug\tensorflow.dll'
1>(node:18672) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
1>(node:18672) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
1>generate_def
1>CUSTOMBUILD : FATAL error : CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
1> 1: 00007FF61AD3D50A v8::internal::GCIdleTimeHandler::GCIdleTimeHandler+4618
1> 2: 00007FF61ACE4F86 uv_loop_fork+79446
1> 3: 00007FF61ACE5C21 uv_loop_fork+82673
1> 4: 00007FF61B1ECAEE v8::internal::FatalProcessOutOfMemory+798
1> 5: 00007FF61B1ECA27 v8::internal::FatalProcessOutOfMemory+599
1> 6: 00007FF61B4C5844 v8::internal::Heap::RootIsImmortalImmovable+14788
1> 7: 00007FF61B4C3608 v8::internal::Heap::RootIsImmortalImmovable+6024
1> 8: 00007FF61B0840DB v8::internal::Factory::AllocateRawWithImmortalMap+59
1> 9: 00007FF61B086B5D v8::internal::Factory::NewRawTwoByteString+77
1>10: 00007FF61B085CAC v8::internal::Factory::NewStringFromUtf8+236
1>11: 00007FF61B20C219 v8::String::NewFromUtf8+553
1>12: 00007FF61AD078DB node::Buffer::New+26843
1>13: 00007FF61B1D24FE v8::internal::ZoneVector<v8::internal::compiler::MoveOperands * __ptr64>::ZoneVector<v8::internal::compiler::MoveOperands * __ptr64>+59870
1>14: 00007FF61B1D3A60 v8::internal::ZoneVector<v8::internal::compiler::MoveOperands * __ptr64>::ZoneVector<v8::internal::compiler::MoveOperands * __ptr64>+65344
1>15: 00007FF61B1D29F9 v8::internal::ZoneVector<v8::internal::compiler::MoveOperands * __ptr64>::ZoneVector<v8::internal::compiler::MoveOperands * __ptr64>+61145
1>16: 00007FF61B1D28DB v8::internal::ZoneVector<v8::internal::compiler::MoveOperands * __ptr64>::ZoneVector<v8::internal::compiler::MoveOperands * __ptr64>+60859
1>17: 000000A9F1650461
1>Done building project "tfjs_binding.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

**Comment by d3x0r** [comment]
Find CUDA SDK 10.0 (not 10.0) re-patch with CDNN, and success.

 - Node x64 version.
  -     [Cuda SDK 10.0 (windows) ](https://developer.nvidia.com/cuda-10.0-download-archive?target_os=Windows&target_arch=x86_64)
  - [CDNN](https://developer.nvidia.com/cudnn)

```
npm install --force @tensorflow/tfjs-node-gpu
cd node_modules/@tensorflow/tfjs-node-gpu
# edit binding.gyp to fix the action (end of prior message).
npm run install
```

``` diff 
# under windows target
              'action': [
                'cmd',
---                '/c node <@(_inputs) > <@(_outputs)'
+++                '/c node --max-old-space-size=3096 <@(_inputs) > <@(_outputs)'
              ]
```
 - profit
