### ISSUE TITLE
Return better error message when using RefVariables with v2 control flow

### ISSUE THREAD

**Issue by ppwwyyxx** [tensorflow/tensorflow#28446]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):archlinux
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:n/a
- TensorFlow installed from (source or binary):binary
- TensorFlow version (use command below):v1.12.0-12395-g32b84a4 1.14.1-dev20190412  (this is the nightly at 20190412).
- Python version:3.7
- Bazel version (if compiling from source):n/a
- GCC/Compiler version (if compiling from source):n/a
- CUDA/cuDNN version:n/a
- GPU model and memory:n/a

The following code:
```python
import os
os.environ['TF_ENABLE_COND_V2'] = '1'
import tensorflow as tf

a = tf.get_variable("x", dtype=tf.float32, shape=[3])
loss = tf.reduce_sum(a)
opt = tf.train.GradientDescentOptimizer(0.1)
def f():
    train_op = opt.minimize(loss)
    return train_op
op = tf.cond(tf.greater(a[0], 0), f, tf.no_op)
print(op)
```
throws:
```
WARNING: Logging before flag parsing goes to stderr.
W0506 12:29:26.078263 140364116391744 deprecation.py:506] From /home/XXX/environments/tf1-nightly/lib/python3.7/site-packages/tensorflow/python/ops/init_ops.py:1257: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Tensor("x/Initializer/random_uniform/max:0", shape=(), dtype=float32) Tensor("x/Initializer/random_uniform/min:0", shape=(), dtype=float32)
Tensor("x/Initializer/random_uniform/RandomUniform:0", shape=(3,), dtype=float32) Tensor("x/Initializer/random_uniform/sub:0", shape=(), dtype=float32)
Traceback (most recent call last):
  File "a.py", line 20, in <module>
    op = tf.cond(tf.greater(a[0], 0), f, tf.no_op)
  File "/home/XXX/environments/tf1-nightly/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/XXX/environments/tf1-nightly/lib/python3.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 1921, in cond
    return cond_v2.cond_v2(pred, true_fn, false_fn, name)
  File "/home/XXX/environments/tf1-nightly/lib/python3.7/site-packages/tensorflow/python/ops/cond_v2.py", line 74, in cond_v2
    op_return_value=pred)
  File "/home/XXX/environments/tf1-nightly/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 710, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "a.py", line 16, in f
    train_op = opt.minimize(loss)
  File "/home/XXX/environments/tf1-nightly/lib/python3.7/site-packages/tensorflow/python/training/optimizer.py", line 412, in minimize
    name=name)
  File "/home/XXX/environments/tf1-nightly/lib/python3.7/site-packages/tensorflow/python/training/optimizer.py", line 594, in apply_gradients
    update_ops.append(processor.update_op(self, grad))
  File "/home/XXX/environments/tf1-nightly/lib/python3.7/site-packages/tensorflow/python/training/optimizer.py", line 118, in update_op
    update_op = optimizer._apply_dense(g, self._v)  # pylint: disable=protected-access
  File "/home/XXX/environments/tf1-nightly/lib/python3.7/site-packages/tensorflow/python/training/gradient_descent.py", line 60, in _apply_dense
    use_locking=self._use_locking).op
  File "/home/XXX/environments/tf1-nightly/lib/python3.7/site-packages/tensorflow/python/training/gen_training_ops.py", line 639, in apply_gradient_descent
    use_locking=use_locking, name=name)
  File "/home/XXX/environments/tf1-nightly/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/home/XXX/environments/tf1-nightly/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 461, in create_op
    compute_device=compute_device)
  File "/home/XXX/environments/tf1-nightly/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/XXX/environments/tf1-nightly/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3579, in create_op
    op_def=op_def)
  File "/home/XXX/environments/tf1-nightly/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1969, in __init__
    input_types))
TypeError: In op 'GradientDescent/update_x/ApplyGradientDescent', input types ([tf.float32, tf.float32, tf.float32]) are not compatible with expected types ([tf.float32_ref, tf.float32, tf.float32])
```

But it works without COND_V2. Similar to #24517.

**Comment by saxenasaurabh** [comment]
Could you try using [`tf.enable_resource_variables()`](https://www.tensorflow.org/api_docs/python/tf/enable_resource_variables) or `tf.get_variable("x", dtype=tf.float32, shape=[3], use_resource=True)`.

v2 control flow does not support RefVariables.

**Comment by ppwwyyxx** [comment]
Thanks! This does fix the issue. Perhaps this behavior should trigger a more clear error message?

**Comment by saxenasaurabh** [comment]
Yep, that would be useful. Let me look into that. Thanks!

**Comment by jvishnuvardhan** [comment]
@ppwwyyxx Is this still an issue for you? When I ran your code, the error message was clear as shown below. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/e655879c992dabf6b083af88d7d3cf50/untitled997.ipynb). Thanks!

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-5216065f60d8> in <module>()
      9     train_op = opt.minimize(loss)
     10     return train_op
---> 11 op = tf.cond(tf.greater(a[0], 0), f, tf.no_op)
     12 print(op)

13 frames
/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/framework/ops.py in __init__(self, node_def, g, inputs, output_types, control_inputs, input_types, original_op, op_def)
   1724         raise TypeError("In op '%s', input types (%s) are not compatible "
   1725                         "with expected types (%s)" %
-> 1726                         (node_def.name, [i.dtype for i in inputs], input_types))
   1727 
   1728     # Build the list of control inputs.

TypeError: In op 'GradientDescent/update_x/ApplyGradientDescent', input types ([tf.float32, tf.float32, tf.float32]) are not compatible with expected types ([tf.float32_ref, tf.float32, tf.float32])
```

The error was already resolved by @saxenasaurabh suggestion. Thanks!

**Comment by mohantym** [comment]
Hi @ppwwyyxx!  I have edited code and  issue is not replicating after multiple use . please find [GIST ](https://colab.research.google.com/gist/mohantym/b9c052452fa3f11504c1f0044f0b1bd5/untitled997.ipynb#scrollTo=yb2BJyV0HDCm)for reference.

**Comment by ppwwyyxx** [comment]
Thanks! It seems it was fixed.
