### ISSUE TITLE
ValueError when reading a frozen graph

### ISSUE THREAD

**Issue by fuzzyBatman** [tensorflow/tensorflow#28532]
**System information**
- Have I written custom code: No
- OS Platform and Distribution: Linux Fedora 30
- TensorFlow installed from: Binary
- TensorFlow version: 1.13.1
- Python version: 3.7.3 (64-bit)
- CUDA/cuDNN version: CUDA 10.0
- GPU model and memory: Nvidia GeForce GTX 1050M [4GB]

**Current behavior**

```
Traceback (most recent call last):
  File "/home/fuzzybatman/.local/lib/python3.7/site-packages/tensorflow/python/framework/importer.py", line 426, in import_graph_def
    graph._c_graph, serialized, options)  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: NodeDef expected inputs '' do not match 1 inputs specified; Op<name=Const; signature= -> output:dtype; attr=value:tensor; attr=dtype:type>; NodeDef: {{node bn_data/cond/ones_like/Shape}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fuzzybatman/Workspace/ET4399-Extra_Project_[Okotech]/09 - UNet/frozen_predict.py", line 30, in <module>
    tf.import_graph_def(trt_graph, name='')
  File "/home/fuzzybatman/.local/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/fuzzybatman/.local/lib/python3.7/site-packages/tensorflow/python/framework/importer.py", line 430, in import_graph_def
    raise ValueError(str(e))
ValueError: NodeDef expected inputs '' do not match 1 inputs specified; Op<name=Const; signature= -> output:dtype; attr=value:tensor; attr=dtype:type>; NodeDef: {{node bn_data/cond/ones_like/Shape}}
```

**Describe the expected behavior**

Load the graph so it can be used for inference.

**Code to reproduce the issue**

```
import tensorflow as tf

output_names = ['sigmod/Sigmoid']
input_names = ['data']

def get_frozen_graph(graph_file):
    """Read Frozen Graph file from disk."""
    with tf.gfile.FastGFile(graph_file, "rb") as f:
        graph_def = tf.GraphDef()
        graph_def.ParseFromString(f.read())
    return graph_def

trt_graph = get_frozen_graph('<PATH-TO-MODEL>')

# Create session and load graph
tf_config = tf.ConfigProto()
tf_config.gpu_options.allow_growth = True

tf_sess = tf.Session(config=tf_config)
tf_sess.run(tf.global_variables_initializer())

tf.import_graph_def(trt_graph, name='')
```

**Other info / logs**
The original model was built in keras

**Comment by fuzzyBatman** [comment]
I used **keras** and **tensorflow.keras** interchangeably.
So my answer to _Have you written custom code_ is a Yes.
