### ISSUE TITLE
Crashing on TF Detect Android sample with Yolov3-tiny model

### ISSUE THREAD

**Issue by androuino** [tensorflow/tensorflow#28540]
I converted Yolov3-tiny model (Trained from scratch) with [DW2TF](https://github.com/jinyu121/DW2TF). Then I put .pb file to assets and changed MODE == DetectorMode.YOLO in **[DetectorActivity.java](https://gist.github.com/androuino/2b67d88d00bc52ac181740fa475828c4)**.

When I start TF Detect app I have a crash:
```
--------- beginning of crash
05-09 17:07:39.959 13973-13999/org.tensorflow.demo E/AndroidRuntime: FATAL EXCEPTION: inference
    Process: org.tensorflow.demo, PID: 13973
    java.lang.IllegalArgumentException: No Operation named [input] in the Graph
        at org.tensorflow.Session$Runner.operationByName(Session.java:372)
        at org.tensorflow.Session$Runner.feed(Session.java:142)
        at org.tensorflow.contrib.android.TensorFlowInferenceInterface.addFeed(TensorFlowInferenceInterface.java:577)
        at org.tensorflow.contrib.android.TensorFlowInferenceInterface.feed(TensorFlowInferenceInterface.java:318)
        at org.tensorflow.demo.TensorFlowYoloDetector.recognizeImage(TensorFlowYoloDetector.java:154)
        at org.tensorflow.demo.DetectorActivity$3.run(DetectorActivity.java:297)
        at android.os.Handler.handleCallback(Handler.java:815)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at android.os.Looper.loop(Looper.java:207)
        at android.os.HandlerThread.run(HandlerThread.java:61)
```

Thank you in advance for the help.

**Comment by HWenTing** [comment]
hello，did you solve this problem？

**Comment by jdduke** [comment]
You need to update the input/output tensor names that are reference in the sample. Unfortunately, in-place swapping out models in inference code doesn't always "just work" due to how different models expose the input/output names.
