### ISSUE TITLE
TF 1.13.1 SequenceExample & Dataset/Estimator Saved Model: No attr named 'Ncontext_sparse' in NodeDef

### ISSUE THREAD

**Issue by jgung** [tensorflow/tensorflow#28570]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): OS X 10.14
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.13.1
- Python version: 3.6.5
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
In TF 1.13.1, using a Dataset API pipeline that parses a [SequenceExample](https://www.tensorflow.org/api_docs/python/tf/train/SequenceExample) with [parse_single_sequence_example](https://www.tensorflow.org/api_docs/python/tf/io/parse_single_sequence_example) exported as a SavedModel with `strip_default_attrs` set to `True` (which is the default behavior for Estimators) fails with the following error:
```
2019-05-09 16:55:22.618817: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at optimize_dataset_op.cc:67 : Not found: No attr named 'Ncontext_sparse' in NodeDef:
         [[{{node ParseSingleSequenceExample/ParseSingleSequenceExample}}]]
```
See the full stacktrace below.

**Describe the expected behavior**
The above error does not occur in TF 1.12, perhaps due to `DatasetV2` changes with `OptimizeDataset`. After some experimentation, I found the error does not occur when `strip_default_attrs` is set to `False` when exporting the SavedModel. Nor does it occur when using [Example](https://www.tensorflow.org/api_docs/python/tf/train/Example) in a similar capacity.

Though the example below is intentionally mundane, I've found the  Dataset API functions like `padded_batch` to be extremely nice and was disappointed when I found I couldn't immediately use 1.13.1 saved models as I had been in previous versions.

**Code to reproduce the issue**
```python
import tempfile

import tensorflow as tf

# Set to `False`, and the below script produces 'Hello, World!'
strip_default_attrs = True


# function to deserialize SequenceExample proto
def _parse_proto(proto):
    return tf.parse_single_sequence_example(
        serialized=proto,
        context_features={'f': tf.FixedLenFeature([], tf.dtypes.string)})[0]


# create a minimal SequenceExample
feature = tf.train.Feature(
    bytes_list=tf.train.BytesList(value=[bytes('Hello, World!', encoding='utf-8')]))
example = tf.train.SequenceExample(
    context=tf.train.Features(feature={'f': feature})).SerializeToString()

with tempfile.TemporaryDirectory() as tmp:
    export_dir = tmp + '/export'

    # build and export saved model to a temporary directory
    with tf.Session(graph=tf.Graph()) as sess:
        dataset = tf.data.Dataset.from_tensor_slices(tf.constant([example]))
        dataset = dataset.map(_parse_proto)
        dataset.make_one_shot_iterator().get_next(name='hello')

        builder = tf.saved_model.builder.SavedModelBuilder(export_dir)

        builder.add_meta_graph_and_variables(
            sess,
            tags=[tf.saved_model.tag_constants.SERVING],
            strip_default_attrs=strip_default_attrs)

        builder.save()

    # load and apply saved model
    with tf.Session(graph=tf.Graph()) as sess:
        tf.saved_model.loader.load(sess,
                                   tags=[tf.saved_model.tag_constants.SERVING],
                                   export_dir=export_dir)
        # get element from dataset
        result = sess.graph.get_tensor_by_name('hello:0')

        # if strip_default_attrs is True, fails with "NotFoundError: No attr named 'Ncontext_sparse' in NodeDef..." error
        print(str(sess.run(result), 'utf-8'))  # otherwise, will print 'Hello, World!'
```

**Other info / logs**
Full stacktrace:
```
2019-05-09 16:55:22.618817: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at optimize_dataset_op.cc:67 : Not found: No attr named 'Ncontext_sparse' in NodeDef:
         [[{{node ParseSingleSequenceExample/ParseSingleSequenceExample}}]]
2019-05-09 16:55:22.618916: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at iterator_ops.cc:1022 : Not found: No attr named 'Ncontext_sparse' in NodeDef:
         [[{{node ParseSingleSequenceExample/ParseSingleSequenceExample}}]]
         [[{{node OptimizeDataset}}]]
Traceback (most recent call last):
  File "/Users/jgung/.venv/tf/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/Users/jgung/.venv/tf/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/Users/jgung/.venv/tf/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: No attr named 'Ncontext_sparse' in NodeDef:
         [[{{node ParseSingleSequenceExample/ParseSingleSequenceExample}}]]
         [[{{node OptimizeDataset}}]]
         [[{{node OneShotIterator}}]]
```

**Comment by jgung** [comment]
For anyone experiencing this issue, you can work around it in the Estimator API by exporting your saved model using [export_savedmodel](https://www.tensorflow.org/api_docs/python/tf/estimator/Estimator#export_savedmodel) with `strip_default_attrs` set to `False`. This isn't ideal since it may hurt the forwards compatibility of your exported model.

**Comment by jgung** [comment]
Testing in later versions (1.14/1.15), this issue seems to be fixed now. Closing the ticket, thanks!
