### ISSUE TITLE
Unable to install tensorflow-gpu (python 3.6 windows)

### ISSUE THREAD

**Issue by sF0rman** [tensorflow/tensorflow#28607]
Where did I go wrong?

**System information**
- OS Platform and Distribution: Windows 10 Pro 10.0.17134 Build 17134
- CUDA Version: 10.1
- cuDNN version: 7.5.1
- TensorFlow version: tensorflow-gpu 1.13.1
- Python version: python-3.6.8-amd64 (64-bit version)
- Installed using pip in virtualenv
- GPU model and memory: NVIDIA GeForce GTX 980 4GB VRAM
(checked versions here: https://www.tensorflow.org/install/gpu)
(and step by step followed this: https://www.tensorflow.org/install/pip)

**Describe the problem**
TensorFlow GPU does not import correctly in Python 3.6 on Windows.
Cannot find any 

**Provide the exact sequence of commands / steps that you executed before running into the problem**
Installed cuda_10.1.105_418.96_win10.exe
Downloaded and copied the 3 folders from cudnn-10.1-windows10-x64-v7.5.1.10 into C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1 (replaced files)
Download and install the Microsoft Visual C++ 2015 Redistributable Update 3 from provided link
Clean install of Python 3.6.8 (added to path) (C:\Python36 & C:\Python36\Scripts)

```
C:\> pip --version
pip 19.1.1 from c:\python36\lib\site-packages\pip (python 3.6)
C:\> pip install -U pip virtualenv
C:\> virtualenv --system-site-package ./tfgpu
C:\>.\tfgpu\Scripts\activate

(tfgpu) C:\>pip list
Package    Version
---------- -------
pip        19.1.1
setuptools 41.0.1
virtualenv 16.5.0
wheel      0.33.3

(tfgpu) C:\> pip install --upgrade tensorflow-gpu
(tfgpu) C:\> pip list
Package              Version
-------------------- -------
absl-py              0.7.1
astor                0.7.1
gast                 0.2.2
grpcio               1.20.1
h5py                 2.9.0
Keras-Applications   1.0.7
Keras-Preprocessing  1.0.9
Markdown             3.1
mock                 3.0.5
numpy                1.16.3
pip                  19.1.1
protobuf             3.7.1
setuptools           41.0.1
six                  1.12.0
tensorboard          1.13.1
tensorflow-estimator 1.13.0
tensorflow-gpu       1.13.1
termcolor            1.1.0
virtualenv           16.5.0
Werkzeug             0.15.2
wheel                0.33.3

(tfgpu) C:\>python -c "import tensorflow as tf"
Traceback (most recent call last):
  File "C:\tfgpu\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\tfgpu\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\tfgpu\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\tfgpu\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\tfgpu\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\tfgpu\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\tfgpu\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\tfgpu\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\tfgpu\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\tfgpu\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\tfgpu\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\tfgpu\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\tfgpu\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

**Any other info / logs**
Also created a new project in PyCharm (project name: tfgpu) with the existing interpreter which successfully finds tensorflow after typing "import t" and lists it under Settings->Project: tfgpu -> Project Interpreter.

Run gives the exact same error as above.

**Comment by rootkitchao** [comment]
You are using CUDA10.1, the current version of Tensorflow GPU requires CUDA10.0(see https://www.tensorflow.org/install/gpu).Please reinstall the correct version of CUDA and cuDNN.

**Comment by sF0rman** [comment]
Thanks, got it working :)
