### ISSUE TITLE
Keras RNN example from docs does not support statefulness when multilayer

### ISSUE THREAD

**Issue by davisyoshida** [tensorflow/tensorflow#28614]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):

- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): 1.13.1
- Python version: 3.6.7 (Anaconda)
- CUDA/cuDNN version: 9.2/7.3.1
- GPU model and memory: GTX 1070 Ti

**Describe the current behavior**
Modifying the example code given [here](https://www.tensorflow.org/api_docs/python/tf/keras/layers/RNN) to have `stateful=True` leads to the following error:
```
Traceback (most recent call last):
  File "tmp.py", line 6, in <module>
    y = layer(x)
  File "/home/davis/software/anaconda3/envs/p36/lib/python3.6/site-packages/tensorflow/python/keras/layers/recurrent.py", line 701, in __call__                                                                                                                                
    return super(RNN, self).__call__(inputs, **kwargs)
  File "/home/davis/software/anaconda3/envs/p36/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 538, in __call__                                                                                                                               
    self._maybe_build(inputs)
  File "/home/davis/software/anaconda3/envs/p36/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1603, in _maybe_build                                                                                                                          
    self.build(input_shapes)
  File "/home/davis/software/anaconda3/envs/p36/lib/python3.6/site-packages/tensorflow/python/keras/layers/recurrent.py", line 636, in build                                                                                                                                   
    self.reset_states()
  File "/home/davis/software/anaconda3/envs/p36/lib/python3.6/site-packages/tensorflow/python/keras/layers/recurrent.py", line 906, in reset_states                                                                                                                            
    tensor_shape.as_shape(dim).as_list()))
  File "/home/davis/software/anaconda3/envs/p36/lib/python3.6/site-packages/tensorflow/python/keras/backend.py", line 2833, in set_value
    value = np.asarray(value, dtype=dtype(x))
  File "/home/davis/software/anaconda3/envs/p36/lib/python3.6/site-packages/tensorflow/python/keras/backend.py", line 1015, in dtype
    return x.dtype.base_dtype.name
AttributeError: 'list' object has no attribute 'dtype'
```

**Describe the expected behavior**
Code should run with no error

**Code to reproduce the issue**
```
cells = [tf.keras.layers.LSTMCell(32), tf.keras.layers.LSTMCell(64)]
x = tf.keras.Input(batch_shape=(42, None, 5)) 
layer = tf.keras.layers.RNN(cells, stateful=True)
y = layer(x)
```

**Comment by qlzh727** [comment]
Thank you for reporting the issue, will fix it soon.

**Comment by qlzh727** [comment]
This should be now fixed in https://github.com/tensorflow/tensorflow/commit/12250556493fe7757bd97f397e3483e7c0e022b1.
