### ISSUE TITLE
AttributeError: module 'tensorflow.python.saved_model.signature_constants' has no attribute 'DEFAULT_TRAIN_SIGNATURE_DEF_KEY'

### ISSUE THREAD

**Issue by makslevental** [tensorflow/tensorflow#28645]
```
Successfully installed tensorflow-1.13.1 tensorflow-probability-0.6.0

```
```
import tensorflow as tf
```
```
/home/maksim/dev_projects/rl/venv/bin/python /home/maksim/dev_projects/rl/racetrack.py
Traceback (most recent call last):
  File "/home/maksim/dev_projects/rl/racetrack.py", line 3, in <module>
    import tensorflow as tf
  File "/home/maksim/dev_projects/rl/venv/lib/python3.7/site-packages/tensorflow/__init__.py", line 29, in <module>
    from tensorflow._api.v1 import compat
  File "/home/maksim/dev_projects/rl/venv/lib/python3.7/site-packages/tensorflow/_api/v1/compat/__init__.py", line 21, in <module>
    from tensorflow._api.v1.compat import v1
  File "/home/maksim/dev_projects/rl/venv/lib/python3.7/site-packages/tensorflow/_api/v1/compat/v1/__init__.py", line 626, in <module>
    child_package_str=('tensorflow_estimator.python.estimator.api.estimator'))
  File "/home/maksim/dev_projects/rl/venv/lib/python3.7/site-packages/tensorflow/python/tools/component_api_helper.py", line 56, in package_hook
    child_pkg = importlib.import_module(child_package_str)
  File "/home/maksim/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/maksim/dev_projects/rl/venv/lib/python3.7/site-packages/tensorflow_estimator/__init__.py", line 8, in <module>
    from tensorflow_estimator._api.v1 import estimator
  File "/home/maksim/dev_projects/rl/venv/lib/python3.7/site-packages/tensorflow_estimator/_api/v1/estimator/__init__.py", line 8, in <module>
    from tensorflow_estimator._api.v1.estimator import experimental
  File "/home/maksim/dev_projects/rl/venv/lib/python3.7/site-packages/tensorflow_estimator/_api/v1/estimator/experimental/__init__.py", line 8, in <module>
    from tensorflow_estimator.python.estimator.canned.dnn import dnn_logit_fn_builder
  File "/home/maksim/dev_projects/rl/venv/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/__init__.py", line 25, in <module>
    import tensorflow_estimator.python.estimator.estimator_lib
  File "/home/maksim/dev_projects/rl/venv/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator_lib.py", line 22, in <module>
    from tensorflow_estimator.python.estimator.canned.baseline import BaselineClassifier
  File "/home/maksim/dev_projects/rl/venv/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/canned/baseline.py", line 64, in <module>
    from tensorflow_estimator.python.estimator import estimator
  File "/home/maksim/dev_projects/rl/venv/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 66, in <module>
    from tensorflow_estimator.python.estimator import model_fn as model_fn_lib
  File "/home/maksim/dev_projects/rl/venv/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/model_fn.py", line 36, in <module>
    from tensorflow_estimator.python.estimator.export import export_lib
  File "/home/maksim/dev_projects/rl/venv/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/export/export_lib.py", line 25, in <module>
    from tensorflow.python.saved_model.model_utils import build_all_signature_defs
  File "/home/maksim/dev_projects/rl/venv/lib/python3.7/site-packages/tensorflow/python/saved_model/model_utils/__init__.py", line 22, in <module>
    from tensorflow.python.saved_model.model_utils.export_utils import build_all_signature_defs
  File "/home/maksim/dev_projects/rl/venv/lib/python3.7/site-packages/tensorflow/python/saved_model/model_utils/export_utils.py", line 51, in <module>
    ModeKeys.TRAIN: signature_constants.DEFAULT_TRAIN_SIGNATURE_DEF_KEY,
AttributeError: module 'tensorflow.python.saved_model.signature_constants' has no attribute 'DEFAULT_TRAIN_SIGNATURE_DEF_KEY'

Process finished with exit code 1
```

**Comment by gadagashwini** [comment]
@makslevental Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary? Thanks!

**Comment by makslevental** [comment]
@gadagashwini ubuntu 19.04, x86_64. pip installed

must be something having to do with the pip package because https://github.com/tensorflow/tensorflow/blob/73640d97f67d6bd5ec84375449c6b9bba179606b/tensorflow/python/saved_model/signature_constants.py#L139

**Comment by sslavian812** [comment]
Hi,
Is there any news about this issue? I believe I have the same issue in `Ubuntu 16.04.3` with 
```
tensorflow==1.13.1
tensorflow-estimator==1.13.0
tensorflow-gpu==2.0.0a0
```

**Comment by jvishnuvardhan** [comment]
@makslevental and @sslavian812 Could you check the following things and share the details. I see more people are facing this issue. Thanks!
1. pip list
2. python3 --version
3. pip3 --version
4. virtualenv --version

Thanks!

**Comment by sslavian812** [comment]
Thank you for the response, @jvishnuvardhan 

The problem was about tensorflow versions, especially `tensorflow-gpu==2.0.0a0`.

With these versions, the error is gone:
```
tensorflow==1.12.2
tensorflow-estimator==1.13.0
tensorflow-gpu==1.13.1
```
regarding your quesion: 

python3 --version : **3.5.2**
pip3 --version: **pip 19.0.3**
virtualenv --version: **15.0.1**

**Comment by jvishnuvardhan** [comment]
@sslavian812 Sorry for the delay in my response? Can you check with latest versions TF1.14, TF1.15 (tf-nightly), and 2.0.0b1? Thanks!

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by jvishnuvardhan** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
