### ISSUE TITLE
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

### ISSUE THREAD

**Issue by lmiller210** [tensorflow/tensorflow#28713]
**System information**
Windows 10 Pro
Tensorflow 1.13.1 (didn't work with 2.0.0a0 or 1.10.0)
python 3.6.8
installed using pip

I installed using pip following the instructions on the website. The only solutions I could find told me that i need cuDNN, but this is CPU only, or they told me that I need an AVX-enabled processor, which I have. It gave me the following error when I tried importing it in the command prompt:

Traceback (most recent call last):
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python36\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python36\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python36\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python36\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

Failed to load the native TensorFlow runtime.

**Comment by AyushP123** [comment]
I tried to recreate this issue in anaconda: 
OS: Windows 10 home
Tensorflow 1.13.1
python 3.6.8
I used 'pip install tensorflow' in anaconda terminal to install tensorflow and was able to run 
`from tensorflow.python import pywrap_tensorflow`
`from tensorflow.python.pywrap_tensorflow_internal import *`

**Comment by AyushP123** [comment]
it doesn't require cuDNN, I removed cuDNN and checked.

**Comment by disposa1** [comment]
I have the same problem as you.
Windows 8.1
python3.7.3
tensorflow1.13.1
then I knew that my cpu didn't support aux. 
Because "Starting from 1.6 release, our prebuilt binaries will use AVX instructions.
This may break TF on older CPUs."  noted in [https://github.com/tensorflow/tensorflow/releases/tag/v1.5.0](url).

My solution:
1. Install the python3.6.8
2. virtualenv -p c:\python36\python.exe envname  #(if you have different python version and want to choose a python version what you want in a new virtualenv, just do it)
3. activate your new virtualenv
4. pip install tensorflow==1.5

Hope it can help you.

ps: for other one who is using python3.7 with older cpu.  Tensorflow1.5 doesn't support python3.7, you will encounter a problem with "pip install tensorflow==1.5"  if you still use python3.7.

**Comment by achandraa** [comment]
Just to verify, did you try the steps mentioned in [TensorFlow website](https://www.tensorflow.org/install/source_windows). Also can you try with lower tensorflow version as suggested by @disposa1 and let us know if that does not help. Thanks!

**Comment by Blubberblub** [comment]
Same problem here!

Windows 10
Python 3.6.0
CUDA 9.0
cudnn 7.5.1 for CUDA 9.0
tensorflow 1.13.1
tensorflow-gpu 1.13.1
GTX 1070
Intel i5-6600


CUDA is working fine since i build the device check from the samples and it worked fine. According to process monitor the last dll python loads is System32\kernell.appcore.dll so probably it is this one or the one after that fails to load. Someone has an idea what dll is causing the problem or probably missing?

**Comment by ankank30** [comment]
I encountered the same problem!

Windows: 10
Python: 3.7.3
Tensorflow: 1.31.1

My Solution: Downgrade Python to version 3.6.8

**Comment by Blubberblub** [comment]
There seemes to be and issue with python and protobuf. Using Python 3.6.1 fixed the issue with protobuf. I also hat to install CUDA 10.0 and the according cudnn library. On the tensorflow site it says tensorflow 1.13.1 is using CUDA 9 but 10 seems to be obligatory at least with the tensorflow i got from pip.

**Comment by achandraa** [comment]
@lmiller210 : Please have a look on #26899 and let us know if you have followed the same steps. Thanks!

**Comment by ymodak** [comment]
You need to Download and install the Microsoft Visual C++ 2015 Redistributable Update 3.
https://www.tensorflow.org/install/pip (select windows)

**Comment by lmiller210** [comment]
@achandraa @ymodak I followed all of those steps and its still giving me what appears to be the same error. I'll post it here just in case it is different:

C:\Users\Lucas>python
Python 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
Traceback (most recent call last):
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python36\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python36\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python36\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Lucas\AppData\Local\Programs\Python\Python36\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.


Failed to load the native TensorFlow runtime.

**Comment by ymodak** [comment]
Apologies for the delay in response. This issue slipped.
**TensorFlow release binaries version 1.6 and higher are prebuilt with AVX instruction sets.**
Therefore on any CPU that does not have these instruction sets, either CPU or GPU version of TF will fail to load.

Apparently, your CPU model does not support AVX instruction sets. You can still use TensorFlow with the alternatives given below:
* Try Google Colab to use TensorFlow.
    * The easiest way to use TF will be to switch to [google colab](https://colab.sandbox.google.com/notebooks/welcome.ipynb#recent=true). You get pre-installed latest stable TF version. Also you can use ```pip install``` to install any other preferred TF version.
    * It has an added advantage since you can you easily switch to different hardware accelerators     
      (cpu, gpu, tpu) as per the task. 
    * All you need is a good internet connection and you are all set.
* Try to build TF from sources by changing CPU optimization flags.

Please let us know if this helps.

**Comment by DusanRandD** [comment]
Python 3.6.8 + tensorflow1.5+ keras2.1.5 works fine on win10.
Thanks disposa1!
