### ISSUE TITLE
Failed to load the native TensorFlow runtime

### ISSUE THREAD

**Issue by jralfonsog** [tensorflow/tensorflow#28721]
I'm trying to run tensorflow in a venv managed on PyCharm, but is giving some trouble (I cant even check the version). I have another env, this one on conda, which works fine.

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): import tensorflow (for example)
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): pip install tensorflow-gpu
- TensorFlow version (use command below): 1.13.1
- Python version: 3.6.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.0
- GPU model and memory: GeForce 1080 Ti - 11Gb. Driver 430.64

**Traceback**

> Traceback (most recent call last):
>   File "C:\Python\Python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
>     from tensorflow.python.pywrap_tensorflow_internal import *
>   File "C:\Python\Python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
>     _pywrap_tensorflow_internal = swig_import_helper()
>   File "C:\Python\Python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
>     _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
>   File "C:\Python\Python-3.6.8\lib\imp.py", line 243, in load_module
>     return load_dynamic(name, filename, file)
>   File "C:\Python\Python-3.6.8\lib\imp.py", line 343, in load_dynamic
>     return _load(spec)
> ImportError: DLL load failed: No se puede encontrar el módulo especificado.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "C:\Python\Python-3.6.8\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
>     from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
>   File "C:\Python\Python-3.6.8\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
>     from tensorflow.python import pywrap_tensorflow
>   File "C:\Python\Python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
>     raise ImportError(msg)
> ImportError: Traceback (most recent call last):
>   File "C:\Python\Python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
>     from tensorflow.python.pywrap_tensorflow_internal import *
>   File "C:\Python\Python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
>     _pywrap_tensorflow_internal = swig_import_helper()
>   File "C:\Python\Python-3.6.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
>     _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
>   File "C:\Python\Python-3.6.8\lib\imp.py", line 243, in load_module
>     return load_dynamic(name, filename, file)
>   File "C:\Python\Python-3.6.8\lib\imp.py", line 343, in load_dynamic
>     return _load(spec)
> ImportError: DLL load failed: No se puede encontrar el módulo especificado.
> 
> 
> Failed to load the native TensorFlow runtime.
> 
> See https://www.tensorflow.org/install/errors
> 
> for some common reasons and solutions.  Include the entire stack trace
> above this error message when asking for help.
> 

I have already tried to include `bin`, `include` and `lib` (as in https://github.com/tensorflow/docs/pull/419)

**Comment by jralfonsog** [comment]
Dumb of me, forgot to install cuDNN. Feel free to delete the post.

Sorry for the inconvenience, and thanks for your time.
