### ISSUE TITLE
import issue tensorflow v2 and v1 

### ISSUE THREAD

**Issue by ivanjacobs** [tensorflow/tensorflow#28765]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- Windows Server 2016 Standard:
- CPU Xeon (R) CPU E5-2698 v4
- AVX2
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 2.0.0-alpha0 
- Python version: 3.6.8
- Installed using: Tried with: virtualenv, pip and  conda

**Describe the problem**
Installation works fine but  import tensorlfow does not work
**Provide the exact sequence of commands / steps that you executed before running into the problem**
import tensorflow as tf

**Any other info / logs**
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\envs\testtf\lib\site-packages\tensorflow\__init__.py", line 27, in <module>
    from tensorflow._api.v2 import audio
  File "C:\ProgramData\Anaconda3\envs\testtf\lib\site-packages\tensorflow\_api\v2\audio\__init__.py", line 8, in <module>
    from tensorflow.python.ops.gen_audio_ops import decode_wav
  File "C:\ProgramData\Anaconda3\envs\testtf\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\ProgramData\Anaconda3\envs\testtf\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\testtf\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\ProgramData\Anaconda3\envs\testtf\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\ProgramData\Anaconda3\envs\testtf\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\ProgramData\Anaconda3\envs\testtf\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\ProgramData\Anaconda3\envs\testtf\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.


Failed to load the native TensorFlow runtime.
```
See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by gadagashwini** [comment]
@ivanjacobs Did you Download and install the Microsoft Visual C++ 2015 Redistributable Update 3. Also have look https://www.tensorflow.org/install/pip (select windows). Thanks!

**Comment by ivanjacobs** [comment]
Installed Microsoft Visual C++ 2015 Redistributable Update 3  and did all the steps under  https://www.tensorflow.org/install/pip (select windows). 

reintsalled python,pip,virtualenv nothing helps. The only version that runs is the tensorflow==1.5



Log:
C:\code\tensorflowtest\tensorflowtest\Scripts\python.exe C:/code/tensorflowtest/test.py
Traceback (most recent call last):
  File "C:\code\tensorflowtest\tensorflowtest\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\code\tensorflowtest\tensorflowtest\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\code\tensorflowtest\tensorflowtest\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Program Files\Python\Python36\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Program Files\Python\Python36\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/code/tensorflowtest/test.py", line 2, in <module>
    import tensorflow as tf
  File "C:\code\tensorflowtest\tensorflowtest\lib\site-packages\tensorflow\__init__.py", line 27, in <module>
    from tensorflow._api.v2 import audio
  File "C:\code\tensorflowtest\tensorflowtest\lib\site-packages\tensorflow\_api\v2\audio\__init__.py", line 8, in <module>
    from tensorflow.python.ops.gen_audio_ops import decode_wav
  File "C:\code\tensorflowtest\tensorflowtest\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\code\tensorflowtest\tensorflowtest\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\code\tensorflowtest\tensorflowtest\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\code\tensorflowtest\tensorflowtest\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\code\tensorflowtest\tensorflowtest\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Program Files\Python\Python36\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Program Files\Python\Python36\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by gunan** [comment]
The only other reason I can think of is, if you installed the GPU version of TF without having a GPU. Other than that, CPU not having AVX and MSVC redistributable are the only cases I have seen this failure.

**Comment by gadagashwini** [comment]
@ivanjacobs  Is this still an issue?

**Comment by ivanjacobs** [comment]
@gadagashwini 
This is still an issue.
@gunan I am confident that I didn't install gpu version. 
the only version of tf I was able to install is the one compiled by intel
https://software.intel.com/en-us/articles/intel-optimization-for-tensorflow-installation-guide

**Comment by ymodak** [comment]
Your cpu does not support AVX instruction sets.
See https://ark.intel.com/content/www/us/en/ark/products/91753/intel-xeon-processor-e5-2698-v4-50m-cache-2-20-ghz.html
TF 1.6 and above binaries require AVX instruction sets.
See https://www.tensorflow.org/install/pip#hardware-requirements
