### ISSUE TITLE
ImportError: DLL load failed

### ISSUE THREAD

**Issue by tianjiaq** [tensorflow/tensorflow#28848]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Win10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.13
- Python version: 3.6.7
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source): 0.21.0
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.0/7.5.1
- GPU model and memory:RTX2070

**Describe the problem**
I'm installing tf from source using bazel and I'm trying to use CUDA, when I build pip package by using: bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package 
**Provide the exact sequence of commands / steps that you executed before running into the problem**

bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package 

**Any other info / logs**

ERROR: E:/tensorflow/tensorflow/BUILD:573:1: Executing genrule //tensorflow:tf_python_api_gen_v1 failed (Exit 1): bash.exe failed: error executing command
  cd C:/users/dylan/_bazel_dylan/4ejpfwyr/execroot/org_tensorflow
  SET CUDA_TOOLKIT_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0
    SET CUDNN_INSTALL_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0
    SET PATH=C:\msys64\usr\bin;C:\msys64\bin
    SET PYTHON_BIN_PATH=C:/Users/dylan/AppData/Local/Programs/Python/Python36/python.exe
    SET PYTHON_LIB_PATH=C:/Users/dylan/AppData/Local/Programs/Python/Python36/lib/site-packages
    SET TF_CUDA_CLANG=0
    SET TF_CUDA_COMPUTE_CAPABILITIES=5.0
    SET TF_CUDA_VERSION=10.0
    SET TF_CUDNN_VERSION=7
    SET TF_NEED_CUDA=1
    SET TF_NEED_OPENCL_SYCL=0
    SET TF_NEED_ROCM=0
  C:/msys64/usr/bin/bash.exe bazel-out/x64_windows-opt/genfiles/tensorflow/tf_python_api_gen_v1.genrule_script.sh
Execution platform: @bazel_tools//platforms:host_platform
Traceback (most recent call last):
  File "\\?\C:\Users\dylan\AppData\Local\Temp\Bazel.runfiles_gllyv2tm\runfiles\org_tensorflow\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "\\?\C:\Users\dylan\AppData\Local\Temp\Bazel.runfiles_gllyv2tm\runfiles\org_tensorflow\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "\\?\C:\Users\dylan\AppData\Local\Temp\Bazel.runfiles_gllyv2tm\runfiles\org_tensorflow\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python36\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python36\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "\\?\C:\Users\dylan\AppData\Local\Temp\Bazel.runfiles_gllyv2tm\runfiles\org_tensorflow\tensorflow\python\tools\api\generator\create_python_api.py", line 27, in <module>
    from tensorflow.python.tools.api.generator import doc_srcs
  File "\\?\C:\Users\dylan\AppData\Local\Temp\Bazel.runfiles_gllyv2tm\runfiles\org_tensorflow\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "\\?\C:\Users\dylan\AppData\Local\Temp\Bazel.runfiles_gllyv2tm\runfiles\org_tensorflow\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "\\?\C:\Users\dylan\AppData\Local\Temp\Bazel.runfiles_gllyv2tm\runfiles\org_tensorflow\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "\\?\C:\Users\dylan\AppData\Local\Temp\Bazel.runfiles_gllyv2tm\runfiles\org_tensorflow\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "\\?\C:\Users\dylan\AppData\Local\Temp\Bazel.runfiles_gllyv2tm\runfiles\org_tensorflow\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python36\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python36\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 2207.386s, Critical Path: 378.51s
INFO: 4635 processes: 4635 local.
FAILED: Build did NOT complete successfully

**Comment by tianjiaq** [comment]
Does it look like set path issue?

**Comment by achandraa** [comment]
Did you follow the instruction from [TensorFlow website](https://www.tensorflow.org/install/source_windows). You can have a look on similar issue #22794 and #10033 . let us know if that helps. Looks like you need to add path for CUDA and CuDNN.

**Comment by tianjiaq** [comment]
> Did you follow the instruction from [TensorFlow website](https://www.tensorflow.org/install/source_windows). You can have a look on similar issue #22794 and #10033 . let us know if that helps. Looks like you need to add path for CUDA and CuDNN.

Hi, thanks for reply. I have tried multiple solutions from previous similar issues, but it still gives the same error. And their error doesn't display the list of SET operations as well. The only difference I can see is i'm using cuda 10.0, but rtx 2070 requires cuda 10 i think. I have set all required path in system environment variable:
Path = c:\bazel;c:\msys64\usr\bin;C:\tools\cuda\bin;
C:\Users\dylan\AppData\Local\Programs\Python\Python36\Scripts\;C:\Users\dylan\AppData\Local\Programs\Python\Python36;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\extras\CUPTI\libx64;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\include;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin

BAZEL_SH = c:\msys64\usr\bin\bash.exe
BAZEL_VC = C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC
CUDA_PATH = C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0
CUDA_PATH_V10_0 = C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0
JAVA_HOME = C:\Program Files\Java\jdk1.8.0_201

**Comment by tianjiaq** [comment]
I have successfully installed tensorflow with gpu support through anaconda. But I don't know what's wrong with my build from source approach still. But I can see anaconda installs cuda 10.0.1 and cudnn 7.5 with tensorflow 1.13.1

**Comment by achandraa** [comment]
Just to verify did you follow exactly the same instructions from [TensorFlow website](https://www.tensorflow.org/install/source_windows) (with GPU support). Thanks!

**Comment by tianjiaq** [comment]
> Just to verify did you follow exactly the same instructions from [TensorFlow website](https://www.tensorflow.org/install/source_windows) (with GPU support). Thanks!

Yes, i did it exactly the same way. And used the same version of package if mentioned. But there are some packages version not specified, they might be the issue then.

**Comment by fengyoulin** [comment]
Open ...\Lib\site-packages\tensorflow\python\\_pywrap_tensorflow_internal.pyd use [Dependency Walker](http://www.dependencywalker.com/), it will show you the DLL dependency tree, you will find which DLL cause the problem. You can then install the needed CUDA or vcredist version, or add some path to system variable.

Here is the dependency tree look like:
![image](https://user-images.githubusercontent.com/10413780/58224686-43831d80-7d51-11e9-9610-9fa5820ffa7e.png)

**Comment by achandraa** [comment]
@tianjiaq : Give a try to fengyoulin's suggestion and let us know if that does not help. Thanks!

**Comment by alexcruz0202** [comment]
@tianjiaq. I am working on TF 1.13.1 and got same issue during the build from source.
How did you solve the problem?   thank you.

**Comment by tianjiaq** [comment]
> @tianjiaq. I am working on TF 1.13.1 and got same issue during the build from source.
> How did you solve the problem? thank you.

I installed with Anaconda and get install versions cuda 10.0.1 and cudnn 7.5. You can try these versions first, if not then you can try fengyoulin's solution. Please let me know if it works!

**Comment by alexcruz0202** [comment]
I have solved problem. My issue is nvcuda.dll missing during the cuda installation. 
Then I got nvcuda.dll and the related files from others. 
Thanks @tianjiaq and @fengyoulin.

**Comment by razzOn2calculus** [comment]
Got same problem,
As [Tensorflow website
![dll](https://user-images.githubusercontent.com/33541116/71784822-fc1b7a00-301f-11ea-80f4-d9dc484e7872.PNG)
](https://www.tensorflow.org/install/source_windows)
I did installed Microsoft Visual c++ 2015 Redistributable but again not working,

(base) C:\Users\SAMAN>python
**Python 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)] :: Ana
conda, Inc. on win32**
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow

Traceback (most recent call last):
  File "C:\Users\SAMAN\Anaconda3\lib\site-packages\tensorflow_core\python\pywrap
_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\SAMAN\Anaconda3\lib\site-packages\tensorflow_core\python\pywrap
_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\SAMAN\Anaconda3\lib\site-packages\tensorflow_core\python\pywrap
_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, descript
ion)
  File "C:\Users\SAMAN\Anaconda3\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\SAMAN\Anaconda3\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed with error code 3221225501

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\SAMAN\Anaconda3\lib\site-packages\tensorflow\__init__.py", line
 98, in <module>
    from tensorflow_core import *
  File "C:\Users\SAMAN\Anaconda3\lib\site-packages\tensorflow_core\__init__.py",
 line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\SAMAN\Anaconda3\lib\site-packages\tensorflow\__init__.py", line
 50, in __getattr__
    module = self._load()
  File "C:\Users\SAMAN\Anaconda3\lib\site-packages\tensorflow\__init__.py", line
 44, in _load
    module = _importlib.import_module(self.__name__)
  File "C:\Users\SAMAN\Anaconda3\lib\importlib\__init__.py", line 127, in import
_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\SAMAN\Anaconda3\lib\site-packages\tensorflow_core\python\__init
__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\SAMAN\Anaconda3\lib\site-packages\tensorflow_core\python\pywrap
_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\SAMAN\Anaconda3\lib\site-packages\tensorflow_core\python\pywrap
_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\SAMAN\Anaconda3\lib\site-packages\tensorflow_core\python\pywrap
_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\SAMAN\Anaconda3\lib\site-packages\tensorflow_core\python\pywrap
_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, descript
ion)
  File "C:\Users\SAMAN\Anaconda3\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\SAMAN\Anaconda3\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed with error code 3221225501


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
>>>
