### ISSUE TITLE
how to use tf.contrib.image.rotate in tensorflow 1.1

### ISSUE THREAD

**Issue by Alxemade** [tensorflow/tensorflow#28847]
Here, we want to use  **tensorflow.contrib.image.rotate** function in our code, it works well in the tensorflow 1.8 version, but does not works well in the tensorflow 1.1 version. Also, if we remove  the **tensorflow.contrib.image.rotate** function , it also works well in the 1.1 tensorflow.  So how can I use the tensorflow.contrib.image.rotate in tensorflow 1.1 version.

The tensorflow.contrib.image.rotate has changed with the tensorflow library. In 1.1 version, Click [tf.contrib.image.rotate](https://github.com/tensorflow/docs/blob/r1.1/site/en/api_docs/python/tf/contrib/image/rotate.md) 
```
rotate(
    images,
    angles
)

```
and in 1.8 version, click [tf.contrib.image.rotate](https://github.com/tensorflow/docs/blob/r1.8/site/en/api_docs/python/tf/contrib/image/rotate.md). 
```
tf.contrib.image.rotate(
    images,
    angles,
    interpolation='NEAREST',
    name=None
)
```
So we remove the **interpolation='BILINEAR** parameters.  

Here is some of my code:
```
# coding=utf-8

import os
import numpy as np

import tensorflow as tf
from tensorflow.contrib.image import rotate as images_rotate

slim = tf.contrib.slim

def image_rotation(x):
  rands = tf.truncated_normal([tf.shape(x)[0]], stddev=0.05)
  return images_rotate(x, rands)

def graph(x, y, i, x_max, x_min, grad):
    eps = 2.0 * 32 / 255.0
    num_iter = 15
    alpha = eps / num_iter
    momentum = 1
    num_classes = 110

    with slim.arg_scope(inception_v1.inception_v1_arg_scope()):
        logits_v1, end_points_v1 = inception_v1.inception_v1(
            image_rotation(x), num_classes=num_classes, is_training=False)

    one_hot = tf.one_hot(y, num_classes)
    logits = logits_v1

    cross_entropy = tf.losses.softmax_cross_entropy(one_hot,
                                                    logits,
                                                    label_smoothing=0.0,
                                                    weights=1.0)
    noise = tf.gradients(cross_entropy, x)[0]

    kernel = gkern(7, 4).astype(np.float32)
    stack_kernel = np.stack([kernel, kernel, kernel]).swapaxes(2, 0)
    stack_kernel = np.expand_dims(stack_kernel, 3)

    noise = tf.nn.depthwise_conv2d(noise, stack_kernel, strides=[1, 1, 1, 1], padding='SAME')

    x = x + 2 * tf.sign(noise)
    return x, y, i, x_max, x_min, noise


def stop(x, y, i, x_max, x_min, grad):
  num_iter = FLAGS.num_iter
  return tf.less(i, num_iter)


def main(input_dir, output_dir):

    eps = 2 * 32 / 255.0
    batch_shape = [1, 224, 224, 3]

    with tf.Graph().as_default():
        # Prepare graph
        x_input = tf.placeholder(tf.float32, shape=batch_shape)
        x_max = tf.clip_by_value(x_input + eps, -1.0, 1.0)
        x_min = tf.clip_by_value(x_input - eps, -1.0, 1.0)

        y = tf.constant(np.zeros([FLAGS.batch_size]), tf.int64)
        i = tf.cast(tf.constant(0), tf.float32)

        grad = tf.zeros(shape=batch_shape)

        x_adv, _, _, _, _, _ = tf.while_loop(stop, graph, [x_input, y, i, x_max, x_min, grad])

```

Our environment is：
> 1. cuda8.0 
> 2. tensorflow1.1

And the problems is attached here:
```
Traceback (most recent call last):
  File "attack_iter_notarge_attack_Grad_Rand.py", line 352, in <module>
    tf.app.run()
  File "/home/xuchao/anaconda3/envs/tensorflow1.1/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "attack_iter_notarge_attack_Grad_Rand.py", line 343, in main
    notarget_grad_rand_attack(FLAGS.input_dir, FLAGS.output_dir)
  File "attack_iter_notarge_attack_Grad_Rand.py", line 303, in notarget_grad_rand_attack
    x_adv, _, _, _, _, _ = tf.while_loop(stop, caad18_grad_rand_notarget_graph, [x_input, y, i, x_max, x_min, grad])
  File "/home/xuchao/anaconda3/envs/tensorflow1.1/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2623, in while_loop
    result = context.BuildLoop(cond, body, loop_vars, shape_invariants)
  File "/home/xuchao/anaconda3/envs/tensorflow1.1/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2456, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/home/xuchao/anaconda3/envs/tensorflow1.1/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2406, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "attack_iter_notarge_attack_Grad_Rand.py", line 258, in caad18_grad_rand_notarget_graph
    noise = tf.nn.depthwise_conv2d(noise, stack_kernel, strides=[1, 1, 1, 1], padding='SAME')
  File "/home/xuchao/anaconda3/envs/tensorflow1.1/lib/python3.6/site-packages/tensorflow/python/ops/nn_impl.py", line 372, in depthwise_conv2d
    input = ops.convert_to_tensor(input, name="tensor_in")
  File "/home/xuchao/anaconda3/envs/tensorflow1.1/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 639, in convert_to_tensor
    as_ref=False)
  File "/home/xuchao/anaconda3/envs/tensorflow1.1/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 704, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/xuchao/anaconda3/envs/tensorflow1.1/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 113, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/home/xuchao/anaconda3/envs/tensorflow1.1/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 102, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/home/xuchao/anaconda3/envs/tensorflow1.1/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py", line 360, in make_tensor_proto
    raise ValueError("None values not supported.")
ValueError: None values not supported.
```

I have searched for the problems on the website, and someones say it caused by the tf.contrib.image.rotate function can't work in the GPU environment in the tensorflow 1.1 version, so, I modify the image_rotation with:
```
def image_rotation(x):
  rands = tf.truncated_normal([tf.shape(x)[0]], stddev=0.05)
  with tf.device('/cpu:0'):
        input_tensor = tf.contrib.image.rotate(x, rands)
  return input_tensor
```
But it doesn't work well for me, look forward to your help. Thank you!

**Comment by muddham** [comment]
@Alxemade Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by Alxemade** [comment]
After using tensorflow1.2 it works fine.
