### ISSUE TITLE
How to set up TensorFlow in GPU machine only using CPU By Java code？

### ISSUE THREAD

**Issue by whaozl** [tensorflow/tensorflow#28858]
tensorflow version: 1.8.0 Java

```
        System.out.println("setting config");
        ConfigProto.Builder configBuilder=ConfigProto.newBuilder()
                .setAllowSoftPlacement(true)
                .setLogDevicePlacement(true)
                .clearLogDevicePlacement()
                //.setInterOpParallelismThreads(1)
        ;
        ConfigProto config;
        string visibleDevices="-1";

        config=configBuilder.setGpuOptions(GPUOptions.newBuilder()
                .clearVisibleDeviceList()
                .setVisibleDeviceList(visibleDevices)
                .setAllowGrowth(true)
        )
        .build();
        System.out.println("setting session");
        this.sess=new Session( this.graph, config.toByteArray() );
```
this visibleDevices="-1" throw a error:
```
2019-05-20 20:01:08.472129: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
2019-05-20 20:01:10.441081: E tensorflow/core/common_runtime/direct_session.cc:154] Invalid argument: 'visible_device_list' listed an invalid GPU id '-1' but visible device count is 3
Exception in thread "main" org.tensorflow.TensorFlowException: Failed to create session.
        at org.tensorflow.Session.allocate2(Native Method)
        at org.tensorflow.Session.<init>(Session.java:70)
```

this visibleDevices="0" Indicates that the 0th GPU is used, but my GPU is full and I want to use the CPU to make predictions.

**Comment by whaozl** [comment]
I had solved the problem. thank you.

**Comment by gadagashwini** [comment]
Glad it resolved. Thanks!

**Comment by whaozl** [comment]
CUDA_VISIBLE_DEVICES
modify the environment variables of the current program through Java built-in.

c++  import <stdlib.h> setenv(“{Name}={Value}”)

setenv can modify the environment variables of the current program.
