### ISSUE TITLE
AWS S3 implementation can't handle weird path containing an "=" sign

### ISSUE THREAD

**Issue by morgangiraud** [tensorflow/tensorflow#28921]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): YES
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): OSX
- TensorFlow version (use command below): 1.13.1
- Python version: 3.6

**Describe the current behaviour**
the AWS S3 implementation can't handle weird path

**Describe the expected behavior**
the AWS S3 implementation should be able to handle weird path

**Code to reproduce the issue**
```bash
export AWS_ACCESS_KEY_ID=XXX
export AWS_SECRET_ACCESS_KEY=XXX
export AWS_REGION=eu-west-1
export S3_ENDPOINT=XXX
export S3_USE_HTTPS=0
export S3_VERIFY_SSL=0

export S3_BUCKET=accesstest
export NORMAL_FILENAME=normal.txt
export WEIRD_FILENAME=weird=true.txt # Contains an "="


# Make bucket
if ! aws --endpoint-url http://$S3_ENDPOINT s3api head-bucket --bucket "$S3_BUCKET" 2>/dev/null
then
  echo "Creating bucket $S3_BUCKET"
  aws --endpoint-url http://$S3_ENDPOINT s3 mb s3://$S3_BUCKET
fi

echo "Creating file"
echo "test" > file.txt


echo "Upload a normal file"
aws --endpoint-url http://$S3_ENDPOINT s3 cp file.txt s3://$S3_BUCKET/$NORMAL_FILENAME
echo ""

echo "Upload a weird name file"
aws --endpoint-url http://$S3_ENDPOINT s3 cp file.txt s3://$S3_BUCKET/$WEIRD_FILENAME
echo ""

echo "Check that files exist"
aws --endpoint-url http://$S3_ENDPOINT s3 ls --human-readable s3://$S3_BUCKET/
echo ""


echo "Check TF access"
python bug.py

```
```python
import os
from tensorflow.python.lib.io import file_io

assert "AWS_ACCESS_KEY_ID" in os.environ
assert "AWS_SECRET_ACCESS_KEY" in os.environ
assert "S3_ENDPOINT" in os.environ
assert "S3_USE_HTTPS" in os.environ
assert "S3_VERIFY_SSL" in os.environ

assert "S3_BUCKET" in os.environ
assert "NORMAL_FILENAME" in os.environ
assert "WEIRD_FILENAME" in os.environ

print("Checking access to normal file {} \nShould return '<tensorflow.python.pywrap_tensorflow_internal.FileStatistics; proxy of <Swig Object of type 'tensorflow::FileStatistics *' at 0x10c2171b0> >'\n".format(os.environ["NORMAL_FILENAME"]))
print(file_io.stat('s3://{}/{}'.format(os.environ["S3_BUCKET"], os.environ["NORMAL_FILENAME"])))

print("\n")
print("Checking access to weird file {} \nShould return '<tensorflow.python.pywrap_tensorflow_internal.FileStatistics; proxy of <Swig Object of type 'tensorflow::FileStatistics *' at 0x10c2171b0> >'\n".format(os.environ["WEIRD_FILENAME"]))
print(file_io.stat('s3://{}/{}'.format(os.environ["S3_BUCKET"], os.environ["WEIRD_FILENAME"])))
```

**Other info / logs**
Results of the scripts:
```
Upload a normal file
upload: ./file.txt to s3://accesstest/normal.txt               

Upload a weird name file 
upload: ./file.txt to s3://accesstest/weird=true.txt          

Check that files exist
2019-05-22 10:04:32    5 Bytes normal.txt
2019-05-22 10:04:33    5 Bytes weird=true.txt

Check TF access
Checking access to normal file normal.txt 
Should return '<tensorflow.python.pywrap_tensorflow_internal.FileStatistics; proxy of <Swig Object of type 'tensorflow::FileStatistics *' at 0x10c2171b0> >'

2019-05-22 10:04:35.615026: I tensorflow/core/platform/s3/aws_logging.cc:54] Initializing config loader against fileName /Users/morgangiraud//.aws/config and using profilePrefix = 1
2019-05-22 10:04:35.615056: I tensorflow/core/platform/s3/aws_logging.cc:54] Initializing config loader against fileName /Users/morgangiraud//.aws/credentials and using profilePrefix = 0
2019-05-22 10:04:35.615074: I tensorflow/core/platform/s3/aws_logging.cc:54] Setting provider to read credentials from /Users/morgangiraud//.aws/credentials for credentials file and /Users/morgangiraud//.aws/config for the config file , for use with profile default
2019-05-22 10:04:35.615101: I tensorflow/core/platform/s3/aws_logging.cc:54] Creating HttpClient with max connections2 and scheme http
2019-05-22 10:04:35.615134: I tensorflow/core/platform/s3/aws_logging.cc:54] Initializing CurlHandleContainer with size 2
2019-05-22 10:04:35.615155: I tensorflow/core/platform/s3/aws_logging.cc:54] Creating Instance with default EC2MetadataClient and refresh rate 900000
2019-05-22 10:04:35.615178: I tensorflow/core/platform/s3/aws_logging.cc:54] Found secret key
2019-05-22 10:04:35.615462: I tensorflow/core/platform/s3/aws_logging.cc:54] Initializing CurlHandleContainer with size 25
2019-05-22 10:04:35.615566: I tensorflow/core/platform/s3/aws_logging.cc:54] Found secret key
2019-05-22 10:04:35.615716: I tensorflow/core/platform/s3/aws_logging.cc:54] Pool grown by 2
2019-05-22 10:04:35.615726: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2019-05-22 10:04:35.758012: I tensorflow/core/platform/s3/aws_logging.cc:54] Found secret key
2019-05-22 10:04:35.758177: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
<tensorflow.python.pywrap_tensorflow_internal.FileStatistics; proxy of <Swig Object of type 'tensorflow::FileStatistics *' at 0x122576990> >


Checking access to weird file weird=true.txt 
Should return '<tensorflow.python.pywrap_tensorflow_internal.FileStatistics; proxy of <Swig Object of type 'tensorflow::FileStatistics *' at 0x10c2171b0> >'

2019-05-22 10:04:35.827145: I tensorflow/core/platform/s3/aws_logging.cc:54] Found secret key
2019-05-22 10:04:35.827307: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2019-05-22 10:04:35.891635: E tensorflow/core/platform/s3/aws_logging.cc:60] No response body. Response code: 403
2019-05-22 10:04:35.891774: W tensorflow/core/platform/s3/aws_logging.cc:57] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.
2019-05-22 10:04:35.892084: I tensorflow/core/platform/s3/aws_logging.cc:54] Found secret key
2019-05-22 10:04:35.892314: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
Traceback (most recent call last):
  File "bug.py", line 19, in <module>
    print(file_io.stat('s3://{}/{}'.format(os.environ["S3_BUCKET"], os.environ["WEIRD_FILENAME"])))
  File "/Users/morgangiraud/miniconda3/envs/clever-tensorboard/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 735, in stat
    return stat_v2(filename)
  File "/Users/morgangiraud/miniconda3/envs/clever-tensorboard/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 754, in stat_v2
    return file_statistics
  File "/Users/morgangiraud/miniconda3/envs/clever-tensorboard/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: Object s3://accesstest/weird=true.txt does not exist
```

**Comment by jvishnuvardhan** [comment]
This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!

**Comment by morgangiraud** [comment]
Thanks for your answer.

I'm well aware of that fact but since the AWS API & CLI works fine, the only layer that looked suspicious to me was the TF layer and so it would introduce at least a limitation if not a bug.
I'm not familiar enough with this part of TF code to tell for sure though.

My bad if the bug comes from another 3rd-party.

**Comment by yongtang** [comment]
@morgangiraud On Linux with nightly build, I don't see an issue with file_io:
```
with file_io.FileIO('s3://test-xxx/weird=test.txt', "rb") as f:
    print(f.read())
```

**Comment by morgangiraud** [comment]
Hi Yong Tang,

Thanks for your feedback, I've just made more tests and it looks, it is not coming from TensorFlow:
- it works in docker nightly with official AWS S3 endpoint.
- it does not work in docker nightly with my 3rparty endpoint.

Sorry for this wrong report, have a nice day.
