### ISSUE TITLE
problem in checkpoint

### ISSUE THREAD

**Issue by MammadTavakoli** [tensorflow/tensorflow#2901]
I used tf 0.9. 

When I restore the checkpoint i get the error:

Traceback (most recent call last):

  File "<ipython-input-42-7082fb551371>", line 1, in <module>
    runfile('/media/m/E/Deep/proj/1/t.py', wdir='/media/m/E/Deep/proj/1')

  File "/home/m/anaconda3/lib/python3.5/site-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 714, in runfile
    execfile(filename, namespace)

  File "/home/m/anaconda3/lib/python3.5/site-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 89, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/media/m/E/Deep/proj/1/t.py", line 70, in <module>
    saver.restore(sess, ckpt.model_checkpoint_path) # restore all variables

  File "/home/m/anaconda3/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1105, in restore
    {self.saver_def.filename_tensor_name: save_path})

  File "/home/m/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 333, in run
    The optional `options` argument expects a [`RunOptions`] proto. The options

  File "/home/m/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 573, in _run
    elif isinstance(fetches, dict):

  File "/home/m/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 648, in _do_run
    for fetch, result in zip(unique_fetches, results):

  File "/home/m/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 668, in _do_call
    """Runs a step based on the given fetches and feeds.

NotFoundError: Tensor name "global_step_7" not found in checkpoint files ./ckpt_dir/model.ckpt-0
	 [[Node: save_18/restore_slice_438 = RestoreSlice[dt=DT_INT32, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save_18/Const_0, save_18/restore_slice_438/tensor_name, save_18/restore_slice_438/shape_and_slice)]]
Caused by op 'save_18/restore_slice_438', defined at:
  File "/home/m/anaconda3/lib/python3.5/site-packages/spyderlib/widgets/externalshell/start_ipython_kernel.py", line 205, in <module>
    __ipythonkernel__.start()
  File "/home/m/anaconda3/lib/python3.5/site-packages/ipykernel/kernelapp.py", line 442, in start
    ioloop.IOLoop.instance().start()
  File "/home/m/anaconda3/lib/python3.5/site-packages/zmq/eventloop/ioloop.py", line 162, in start
    super(ZMQIOLoop, self).start()
  File "/home/m/anaconda3/lib/python3.5/site-packages/tornado/ioloop.py", line 883, in start
    handler_func(fd_obj, events)
  File "/home/m/anaconda3/lib/python3.5/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/m/anaconda3/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "/home/m/anaconda3/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/m/anaconda3/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/home/m/anaconda3/lib/python3.5/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/m/anaconda3/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 276, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/home/m/anaconda3/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 228, in dispatch_shell
    handler(stream, idents, msg)
  File "/home/m/anaconda3/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 391, in execute_request
    user_expressions, allow_stdin)
  File "/home/m/anaconda3/lib/python3.5/site-packages/ipykernel/ipkernel.py", line 199, in do_execute
    shell.run_cell(code, store_history=store_history, silent=silent)
  File "/home/m/anaconda3/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2723, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/home/m/anaconda3/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2831, in run_ast_nodes
    if self.run_code(code, result):
  File "/home/m/anaconda3/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2885, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-42-7082fb551371>", line 1, in <module>
    runfile('/media/m/E/Deep/proj/1/t.py', wdir='/media/m/E/Deep/proj/1')
  File "/home/m/anaconda3/lib/python3.5/site-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 714, in runfile
    execfile(filename, namespace)
  File "/home/m/anaconda3/lib/python3.5/site-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 89, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)
  File "/media/m/E/Deep/proj/1/t.py", line 57, in <module>
    saver = tf.train.Saver()
  File "/home/m/anaconda3/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 845, in __init__
    restore_sequentially=restore_sequentially)
  File "/home/m/anaconda3/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 515, in build
    filename_tensor, vars_to_save, restore_sequentially, reshape)
  File "/home/m/anaconda3/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 271, in _AddRestoreOps
    values = self.restore_op(filename_tensor, vs, preferred_shard)
  File "/home/m/anaconda3/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 186, in restore_op
    preferred_shard=preferred_shard)
  File "/home/m/anaconda3/lib/python3.5/site-packages/tensorflow/python/ops/io_ops.py", line 201, in _restore_slice
    file_pattern, tensor_name, shape_and_slice, base_type,
  File "/home/m/anaconda3/lib/python3.5/site-packages/tensorflow/python/ops/gen_io_ops.py", line 325, in _restore_slice
    def _restore_slice(file_pattern, tensor_name, shape_and_slice, dt,
  File "/home/m/anaconda3/lib/python3.5/site-packages/tensorflow/python/ops/op_def_library.py", line 704, in apply_op
    op_def=op_def)
  File "/home/m/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2249, in create_op
    # specified for this op_type.
  File "/home/m/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1224, in __init__
    raise TypeError("Control input must be an Operation, "

how can i solve this problem?

**Comment by JohnAllen** [comment]
Are you sure that the ckpt_dir/model.ckpt-0 file exists in your checkpoint directory?  Normally a later step would be loaded, after some training had been done. But basically tf.restore is trying to restor me a specific file. Make sure the file you specify is there.

**Comment by MammadTavakoli** [comment]
Yes , this file exists.

This is my code:

`import tensorflow as tf
import input_data
import os 

checkpoint_dir='./ckpt_dir/'                
                
mnist = input_data.read_data_sets("MNIST_data", one_hot = True)

x = tf.placeholder(tf.float32, shape = [None , 784])
y_ = tf.placeholder(tf.float32, [None, 10])

sess = tf.InteractiveSession()

def load_model(sess, saver, checkpoint_dir ):        
        ckpt = tf.train.get_checkpoint_state(checkpoint_dir)
        if ckpt and ckpt.model_checkpoint_path:
            print(ckpt.model_checkpoint_path)    
            saver.restore(sess, ckpt.model_checkpoint_path)            
        else:
            if not os.path.exists(checkpoint_dir):
                os.makedirs(checkpoint_dir)
            sess.run(init)
        return
        
def weight_variable(shape):
    initial = tf.truncated_normal(shape, stddev = 0.1)
    return tf.Variable(initial)
    
def bias_variable(shape):
    initial = tf.constant(0.1, shape= shape)
    return tf.Variable(initial)
  
def conv2d(x, W):
    return tf.nn.conv2d(x, W, strides = [1, 1, 1, 1], padding = "SAME")

def max_pool_2x2(x):
    return tf.nn.max_pool(x, ksize = [1, 2, 2, 1], strides = [1, 2, 2, 1],
                          padding = "SAME")
  
W_conv1 = weight_variable([5, 5, 1, 32])
b_conv1 = bias_variable([32])

x_image = tf.reshape(x, [-1, 28, 28, 1])

#
h_conv1 = tf.nn.relu(conv2d(x_image, W_conv1))
h_pool1 = max_pool_2x2(h_conv1)

#
W_conv2 = weight_variable([5, 5, 32, 64])
b_conv2 = bias_variable([64])

h_conv2 = tf.nn.relu(conv2d(h_pool1, W_conv2))
h_pool2 = max_pool_2x2(h_conv2)

W_fc1 = weight_variable([7*7*64, 1024])
b_fc1 = bias_variable([1024])

h_pool2_flat = tf.reshape(h_pool2, [-1, 7*7*64])
h_fc1 = tf.nn.relu(tf.matmul(h_pool2_flat, W_fc1) + b_fc1)

#
keep_prob = tf.placeholder(tf.float32)
h_fc1_drop = tf.nn.dropout(h_fc1, keep_prob)

#
W_fc2 = weight_variable([1024, 10])
b_fc2 = bias_variable([10])

y_conv = tf.nn.softmax(tf.matmul(h_fc1_drop,W_fc2) +b_fc2)

#
cross_entropy = tf.reduce_mean(-tf.reduce_sum(y_ * tf.log(y_conv), reduction_indices = [1]))
train_step = tf.train.AdamOptimizer(1e-4).minimize(cross_entropy)

correct_prediction = tf.equal(tf.argmax(y_conv, 1), tf.argmax(y_, 1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

init = tf.initialize_all_variables()

saver = tf.train.Saver() 

load_model(sess, saver, checkpoint_dir)
 
for i in range(1):
    batch = mnist.train.next_batch(50)
    if i%10 == 0:
        train_accuracy = accuracy.eval(feed_dict = {x : batch[0] , y_ : batch[1], keep_prob : 1.0})
        print("step %d, training accuracy %g"%(i, train_accuracy))
        
    train_step.run(feed_dict = {x : batch[0], y_ : batch[1], keep_prob : 0.5})
    
print("test accuracy %g"%accuracy.eval(feed_dict={
    x: mnist.test.images, y_: mnist.test.labels, keep_prob: 1.0}))        
    
tf.scalar_summary("accuracy", accuracy)

saver.save(sess,checkpoint_dir+'model.ckpt')`

**Comment by sherrym** [comment]
1. You are repeatedly creating the Saver, that's why you have 8 global_steps. You can fix it by either explicitly creating a new graph tf.Graph(), or reset the default graph by calling tf.reset_default_graph().

If you print out your graph now by calling tf.train.write_graph, you will see that you have 8 copies of what you are building.

2. The saver should only be called once after you have created the graph, and must be called before init = tf.initializes_all_variable() because without arguments the Saver adds operations to the graph.

3. tf.initialize_all_variables() just creates an op. It doesn't initialize anything. You need to explicitly run it by calling

sess.run(init)
or
init.run()

Hope that helps.

Sherry

**Comment by prb12** [comment]
Please reopen if this doesn't fix the problem.

**Comment by MammadTavakoli** [comment]
@sherrym 
 i cant solve this problem. if you can do this with my code can you past it here?
