### ISSUE TITLE
"tensorflow.python.eager.core._FallbackException: Expecting int64_t value for attr strides, got numpy.int32" + "ValueError: Incompatible conversion from float32 to uint8" when calling fit() on my model

### ISSUE THREAD

**Issue by EmielBoss** [tensorflow/tensorflow#29063]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution: Linux Ubuntu 16.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.12.2
- Python version: 3.5
- CUDA/cuDNN version: V8.0.61
- GPU model and memory: Tesla P100-PCIE, 12193MiB

**Describe the current behavior**
When I call

```
model.fit(train, steps_per_epoch=int(np.ceil(num_train_samples / BATCH_SIZE)), epochs=NUM_EPOCHS, batch_size=BATCH_SIZE, validation_data=val, validation_steps=int(np.ceil(num_val_samples / BATCH_SIZE)))
```

I get the following error:

```
ValueError: Incompatible type conversion requested to type 'uint8' for variable of type 'float32'
```

This error occurs during handling of a first exception:

```
tensorflow.python.eager.core._FallbackException: Expecting int64_t value for attr strides, got numpy.int32
```

I only use NumPy to load ndarrays (using `np.load()`) after which they are immediately converted to TensorFlow tensors. I've also made sure those tensors contain TensorFlow data types, so I am puzzled as to how a NumPy datatypes manages to sneak through. I also couldn't find any variables with numpy.int32 type during debugging.

**Code to reproduce the issue**
My full script is as follows:

```
from __future__ import absolute_import, division, print_function
import tensorflow as tf
import numpy as np
import os

CLASSES = ["aluminium", "asphalt", "brick", "cloud", "concrete", "fabric", "foliage", "glass", "grass", "gravel", "iron", "living", "other", "plastic", "sky", "soil", "stone", "steel", "tile", "water", "wood"]
NUM_CLASSES = len(CLASSES)
DIR_DATASET = "/folder/to/numpyndarrays"
WIDTH = 512
HEIGHT = 512
BATCH_SIZE = 10
NUM_EPOCHS = 10
TRAIN_VAL_SPLIT = 0.9
num_samples = len([filename[:-4] for filename in os.listdir(DIR_DATASET + "ndarrays/")])
num_train_samples = round(num_samples * TRAIN_VAL_SPLIT)
num_val_samples = round(num_samples * (1 - TRAIN_VAL_SPLIT))

#os.environ["CUDA_VISIBLE_DEVICES"] = ""
tf.enable_eager_execution()

def train_sample_fetcher():
    return sample_fetcher()

def val_sample_fetcher():
    return sample_fetcher(is_validations=True)

def sample_fetcher(is_validations=False):
    sample_names = [filename[:-4] for filename in os.listdir(DIR_DATASET + "ndarrays/")]
    if not is_validations: sample_names = sample_names[:int(len(sample_names) * TRAIN_VAL_SPLIT)]
    else: sample_names = sample_names[int(len(sample_names) * TRAIN_VAL_SPLIT):]
    for sample_name in sample_names:
        rgb = tf.image.decode_jpeg(tf.read_file(DIR_DATASET + sample_name + ".jpg"))
        rgb = tf.image.resize_images(rgb, (HEIGHT, WIDTH))
        #d = tf.image.decode_jpeg(tf.read_file(DIR_DATASET + "depth/" + sample_name + ".jpg"))
        #d = tf.image.resize_images(d, (HEIGHT, WIDTH))
        #rgbd = tf.concat([rgb,d], axis=2)
        onehots = tf.convert_to_tensor(np.load(DIR_DATASET + "ndarrays/" + sample_name + ".npy"), dtype=tf.float32)
        yield rgb, onehots

def deconvolve(tensor, num_filters):
    tensor = tf.layers.Conv2DTranspose(num_filters, (2, 2), strides=(2, 2), padding='same')(tensor)
    tensor = tf.layers.BatchNormalization()(tensor)
    tensor = tf.keras.layers.Activation('relu')(tensor)
    tensor = tf.layers.Conv2D(num_filters, (3, 3), padding='same')(tensor)
    tensor = tf.layers.BatchNormalization()(tensor)
    tensor = tf.keras.layers.Activation('relu')(tensor)
    tensor = tf.layers.Conv2D(num_filters, (3, 3), padding='same')(tensor)
    tensor = tf.layers.BatchNormalization()(tensor)
    tensor = tf.keras.layers.Activation('relu')(tensor)
    return tensor

def dice_loss(y_true, y_pred):
    smooth = 1.
    y_true_f = tf.reshape(y_true, [-1]) # Flatten
    y_pred_f = tf.reshape(y_pred, [-1]) # Flatten
    intersection = tf.reduce_sum(y_true_f * y_pred_f)
    dice_coefficient = (2. * intersection + smooth) / (tf.reduce_sum(y_true_f) + tf.reduce_sum(y_pred_f) + smooth)
    loss = 1 - dice_coefficient
    return loss

train = tf.data.Dataset.from_generator(generator=train_sample_fetcher, output_types=(tf.uint8, tf.float32))
train = train.repeat()
train = train.batch(BATCH_SIZE)
train = train.shuffle(10)
val = tf.data.Dataset.from_generator(generator=val_sample_fetcher, output_types=(tf.uint8, tf.float32))

# i = 0
# for sample in train:
#     i = i + 1
#     print(sample[0].dtype)
#     print(sample[1].dtype)

input = tf.keras.Input(shape=(HEIGHT, WIDTH, 3))
resnet = tf.keras.applications.ResNet50(include_top=False, weights='imagenet', input_tensor=None, input_shape=(HEIGHT, WIDTH, 3), pooling=None, classes=1000)(input)
tensor = deconvolve(resnet, 512)
tensor = deconvolve(tensor, 256)
tensor = deconvolve(tensor, 128)
tensor = deconvolve(tensor, 64)
tensor = deconvolve(tensor, 32)
output = tf.layers.Conv2D(NUM_CLASSES, (1, 1), activation='sigmoid')(tensor)

model = tf.keras.models.Model(inputs=[input], outputs=[output])
adam = tf.train.AdamOptimizer()
model.compile(optimizer=adam, loss=dice_loss, metrics=[dice_loss])
history = model.fit(train, steps_per_epoch=int(np.ceil(num_train_samples / BATCH_SIZE)), epochs=NUM_EPOCHS, batch_size=BATCH_SIZE, validation_data=val, validation_steps=int(np.ceil(num_val_samples / BATCH_SIZE)))
```

**Other info / logs**
Here are some of the NumPy arrays I read: https://we.tl/t-aml3GBKorK

The full stacktrace I get:
```
2019-05-27 19:05:49.960354: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-05-27 19:05:50.173624: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
name: Tesla P100-PCIE-12GB major: 6 minor: 0 memoryClockRate(GHz): 1.3285
pciBusID: 0000:04:00.0
totalMemory: 11.91GiB freeMemory: 11.62GiB
2019-05-27 19:05:50.345182: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 1 with properties: 
name: Tesla P100-PCIE-12GB major: 6 minor: 0 memoryClockRate(GHz): 1.3285
pciBusID: 0000:82:00.0
totalMemory: 11.91GiB freeMemory: 11.62GiB
2019-05-27 19:05:50.345255: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0, 1
2019-05-27 19:05:50.969891: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-05-27 19:05:50.969933: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 1 
2019-05-27 19:05:50.969940: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N N 
2019-05-27 19:05:50.969943: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 1:   N N 
2019-05-27 19:05:50.970428: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 11241 MB memory) -> physical GPU (device: 0, name: Tesla P100-PCIE-12GB, pci bus id: 0000:04:00.0, compute capability: 6.0)
2019-05-27 19:05:50.970865: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 11241 MB memory) -> physical GPU (device: 1, name: Tesla P100-PCIE-12GB, pci bus id: 0000:82:00.0, compute capability: 6.0)
python3.5/site-packages/keras_applications/resnet50.py:265: UserWarning: The output shape of `ResNet50(include_top=False)` has been changed since Keras 2.2.0.
  warnings.warn('The output shape of `ResNet50(include_top=False)` '
Epoch 1/10
2019-05-27 19:06:03.844910: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:98] Filling up shuffle buffer (this may take a while): 5 of 10
2019-05-27 19:06:13.468298: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:98] Filling up shuffle buffer (this may take a while): 9 of 10
2019-05-27 19:06:15.918664: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:136] Shuffle buffer filled.
Traceback (most recent call last):
  File "python3.5/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 976, in conv2d
    "data_format", data_format, "dilations", dilations)
tensorflow.python.eager.core._FallbackException: Expecting int64_t value for attr strides, got numpy.int32

During handling of the above exception occurred:

Traceback (most recent call last):
  File "/dir/to/my/script.py", line 89, in <module>
    history = model.fit(train, steps_per_epoch=int(np.ceil(num_train_samples / BATCH_SIZE)), epochs=NUM_EPOCHS, batch_size=BATCH_SIZE, validation_data=val, validation_steps=int(np.ceil(num_val_samples / BATCH_SIZE)))
  File "python3.5/site-packages/tensorflow/python/keras/engine/training.py", line 1614, in fit
    validation_steps=validation_steps)
  File "python3.5/site-packages/tensorflow/python/keras/engine/training_eager.py", line 705, in fit_loop
    batch_size=batch_size)
  File "python3.5/site-packages/tensorflow/python/keras/engine/training_eager.py", line 251, in iterator_fit_loop
    model, x, y, sample_weights=sample_weights, training=True)
  File "python3.5/site-packages/tensorflow/python/keras/engine/training_eager.py", line 511, in _process_single_batch
    training=training)
  File "python3.5/site-packages/tensorflow/python/keras/engine/training_eager.py", line 90, in _model_loss
    outs, masks = model._call_and_compute_mask(inputs, **kwargs)
  File "python3.5/site-packages/tensorflow/python/keras/engine/network.py", line 856, in _call_and_compute_mask
    mask=masks)
  File "/home/local/CYCLOMEDIA001/ebos/Workspace/virtuele_omgevingen/python3/lib/python3.5/site-packages/tensorflow/python/keras/engine/network.py", line 1029, in _run_internal_graph
    computed_tensor, **kwargs)
  File "python3.5/site-packages/tensorflow/python/keras/engine/network.py", line 856, in _call_and_compute_mask
    mask=masks)
  File "/home/local/CYCLOMEDIA001/ebos/Workspace/virtuele_omgevingen/python3/lib/python3.5/site-packages/tensorflow/python/keras/engine/network.py", line 1031, in _run_internal_graph
    output_tensors = layer.call(computed_tensor, **kwargs)
  File "python3.5/site-packages/tensorflow/python/keras/layers/convolutional.py", line 194, in call
    outputs = self._convolution_op(inputs, self.kernel)
  File "python3.5/site-packages/tensorflow/python/ops/nn_ops.py", line 868, in __call__
    return self.conv_op(inp, filter)
  File "python3.5/site-packages/tensorflow/python/ops/nn_ops.py", line 520, in __call__
    return self.call(inp, filter)
  File "python3.5/site-packages/tensorflow/python/ops/nn_ops.py", line 204, in __call__
    name=self.name)
  File "python3.5/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 982, in conv2d
    name=name, ctx=_ctx)
  File "python3.5/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 1015, in conv2d_eager_fallback
    _attr_T, _inputs_T = _execute.args_to_matching_eager([input, filter], _ctx)
  File "python3.5/site-packages/tensorflow/python/eager/execute.py", line 195, in args_to_matching_eager
    ret = [internal_convert_to_tensor(t, dtype, ctx=ctx) for t in l]
  File "python3.5/site-packages/tensorflow/python/eager/execute.py", line 195, in <listcomp>
    ret = [internal_convert_to_tensor(t, dtype, ctx=ctx) for t in l]
  File "python3.5/site-packages/tensorflow/python/framework/ops.py", line 1146, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "python3.5/site-packages/tensorflow/python/ops/variables.py", line 828, in _TensorConversionFunction
    "of type '%s'" % (dtype.name, v.dtype.name))
ValueError: Incompatible type conversion requested to type 'uint8' for variable of type 'float32'
2019-05-27 19:06:16.022529: W tensorflow/core/kernels/data/generator_dataset_op.cc:78] Error occurred when finalizing GeneratorDataset iterator: Failed precondition: Python interpreter state is not initialized. The process may be terminated.
	 [[{{node PyFunc}} = PyFunc[Tin=[DT_INT64], Tout=[DT_INT64], token="pyfunc_2"](arg0)]]
```

**Comment by tommydino93** [comment]
Hi!
Did you manage to solve the issue? :)

**Comment by e-cortex** [comment]
Facing same issue, no clue what's going on.

**Comment by danmoller** [comment]
I'm almost completely giving up tf.keras.... Can't make a single model work. Original Keras didn't have such issues.

**Comment by danmoller** [comment]
@tommydino93 , Although the message is completely unrelated (strigs, int64, etc), I solved this by inspecting my input data and noticing they were of different types. Some inputs were float64, some were float32. Besides fixing this differente I also set the `dtype` arguments (not sure if necessary) and `tf.keras.backend.set_floatx(...)` to the type I was using.
