### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by Joey-Lou-Equinor** [tensorflow/tensorflow#29083]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Windows 7 Enterprise 64-bit (6.1, Build 7601)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): not sure
- TensorFlow version:  1.13.1
- Python version: 3.7.3
- Installed using virtualenv? pip? conda?: conda
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version:  cudatoolkit: 10.0.130/ cudnn: 7.3.1
- GPU model and memory: Intel(R) HD Graphics 520, 1888 MB

**Describe the problem**
I installed tensorflow from anaconda and first installed everything in base (root), upon running `import tensorflow` I encountered this issue.
Then per suggestions from #22794 , I followed the instructions from [link](https://www.pugetsystems.com/labs/hpc/The-Best-Way-to-Install-TensorFlow-with-GPU-Support-on-Windows-10-Without-Installing-CUDA-1187/) which is detailed below. But the same issue persisted.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

```
conda update conda
conda update anaconda
conda update python
conda update --all

conda create --name tf-gpu
cmd
conda activate tf-gpu

conda install tensorflow-gpu keras-gpu  
conda install -c aaronzs tensorflow-gpu
conda install -c anaconda cudatoolkit
conda install -c anaconda cudnn

python
import tensorflow as tf
```

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

> ImportError: Traceback (most recent call last):
>   File "C:\Users\JOLOU\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
>     from tensorflow.python.pywrap_tensorflow_internal import *
>   File "C:\Users\JOLOU\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
>     _pywrap_tensorflow_internal = swig_import_helper()
>   File "C:\Users\JOLOU\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
>     _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
>   File "C:\Users\JOLOU\AppData\Local\Continuum\anaconda3\lib\imp.py", line 242, in load_module
>     return load_dynamic(name, filename, file)
>   File "C:\Users\JOLOU\AppData\Local\Continuum\anaconda3\lib\imp.py", line 342, in load_dynamic
>     return _load(spec)
> ImportError: DLL load failed: The specified module could not be found.
> 
> 
> Failed to load the native TensorFlow runtime.
> 
> See https://www.tensorflow.org/install/errors
> 
> for some common reasons and solutions.  Include the entire stack trace
> above this error message when asking for help.
> 
>

**Comment by Joey-Lou-Equinor** [comment]
I have tried methods from #22872 by downgrading the packages, including tensorflow-gpu, cudatoolkit and cudnn, but the same error kept coming up.

**Comment by Joey-Lou-Equinor** [comment]
It worked after I removed tensorflow-gpu
