### ISSUE TITLE
How to use optimizers from Tensorflow probability in Tensorflow?

### ISSUE THREAD

**Issue by timudk** [tensorflow/tensorflow#29131]
I would like to use the BFGS optimizer from Tensorflow probability (https://www.tensorflow.org/probability/api_docs/python/tfp/optimizer/bfgs_minimize) in Tensorflow. Has anyone done this before and can tell me how to interface the BFGS optimizer?

**Comment by csuter** [comment]
Check out the usage examples in the unit tests: https://github.com/tensorflow/probability/blob/master/tensorflow_probability/python/optimizer/bfgs_test.py#L46

They're written in such a way as to abstract across TF1 and TF2 styles (`self.evaluate` runs the tensor in a session, for 1.x, and is essentially a no-op in 2.0). Otherwise, it should hopefully be clear how to use in some simple cases.

**Comment by csuter** [comment]
Also: feel free to file TFP inquiries in the TFP github issues (https://github.com/tensorflow/probability/issues). Closing this one in TF for now.

**Comment by timudk** [comment]
The usage examples in the unit tests fail: AttributeError: module 'tensorflow_probability.python.math' has no attribute 'value_and_gradient'

Module versions:
tensorboard (1.13.1)
tensorflow (1.13.1)
tensorflow-estimator (1.13.0)
tensorflow-probability (0.6.0)

`python3 bfgs_test.py 

WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

WARNING:tensorflow:From /usr/lib/python3.6/contextlib.py:60: TensorFlowTestCase.test_session (from tensorflow.python.framework.test_util) is deprecated and will be removed in a future version.
Instructions for updating:
Use `self.session()` or `self.cached_session()` instead.
2019-06-05 11:51:10.645988: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-06-05 11:51:10.669441: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2599905000 Hz
2019-06-05 11:51:10.669832: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x2d457a0 executing computations on platform Host. Devices:
2019-06-05 11:51:10.669862: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
WARNING:tensorflow:From /home/tudockho/.local/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py:3632: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
EEEEEEEEEEEEE/home/tudockho/.local/lib/python3.6/site-packages/numpy/lib/type_check.py:546: DeprecationWarning: np.asscalar(a) is deprecated since NumPy v1.16, use a.item() instead
  'a.item() instead', DeprecationWarning, stacklevel=1)
WARNING:tensorflow:From /home/tudockho/.local/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py:3528: setdiff1d (from tensorflow.python.ops.array_ops) is deprecated and will be removed after 2018-11-30.
Instructions for updating:
This op will be removed after the deprecation date. Please switch to tf.sets.difference().
.s
======================================================================
ERROR: test_asymmetric_inverse_hessian_spec (__main__.BfgsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tudockho/.local/lib/python3.6/site-packages/tensorflow/python/framework/test_util.py", line 946, in decorated
    f(self, *args, **kwargs)
  File "bfgs_test.py", line 117, in test_asymmetric_inverse_hessian_spec
    initial_inverse_hessian_estimate=bad_inv_hessian))
  File "/home/tudockho/.local/lib/python3.6/site-packages/tensorflow_probability/python/optimizer/bfgs.py", line 269, in minimize
    control_inputs)
  File "/home/tudockho/.local/lib/python3.6/site-packages/tensorflow_probability/python/optimizer/bfgs_utils.py", line 60, in get_initial_state_args
    f0, df0 = value_and_gradients_function(initial_position)
  File "bfgs_test.py", line 34, in val_and_grad
    return tfp.math.value_and_gradient(value_fn, x)
AttributeError: module 'tensorflow_probability.python.math' has no attribute 'value_and_gradient'

======================================================================
ERROR: test_bad_inverse_hessian_spec (__main__.BfgsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tudockho/.local/lib/python3.6/site-packages/tensorflow/python/framework/test_util.py", line 946, in decorated
    f(self, *args, **kwargs)
  File "bfgs_test.py", line 100, in test_bad_inverse_hessian_spec
    initial_inverse_hessian_estimate=bad_inv_hessian))
  File "/home/tudockho/.local/lib/python3.6/site-packages/tensorflow_probability/python/optimizer/bfgs.py", line 269, in minimize
    control_inputs)
  File "/home/tudockho/.local/lib/python3.6/site-packages/tensorflow_probability/python/optimizer/bfgs_utils.py", line 60, in get_initial_state_args
    f0, df0 = value_and_gradients_function(initial_position)
  File "bfgs_test.py", line 34, in val_and_grad
    return tfp.math.value_and_gradient(value_fn, x)
AttributeError: module 'tensorflow_probability.python.math' has no attribute 'value_and_gradient'

======================================================================
ERROR: test_data_fitting (__main__.BfgsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tudockho/.local/lib/python3.6/site-packages/tensorflow/python/framework/test_util.py", line 946, in decorated
    f(self, *args, **kwargs)
  File "bfgs_test.py", line 350, in test_data_fitting
    neg_log_likelihood, initial_position=start, tolerance=1e-6))
  File "/home/tudockho/.local/lib/python3.6/site-packages/tensorflow_probability/python/optimizer/bfgs.py", line 269, in minimize
    control_inputs)
  File "/home/tudockho/.local/lib/python3.6/site-packages/tensorflow_probability/python/optimizer/bfgs_utils.py", line 62, in get_initial_state_args
    f0, df0 = value_and_gradients_function(initial_position)
  File "bfgs_test.py", line 34, in val_and_grad
    return tfp.math.value_and_gradient(value_fn, x)
AttributeError: module 'tensorflow_probability.python.math' has no attribute 'value_and_gradient'

======================================================================
ERROR: test_determinism (__main__.BfgsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tudockho/.local/lib/python3.6/site-packages/tensorflow/python/framework/test_util.py", line 946, in decorated
    f(self, *args, **kwargs)
  File "bfgs_test.py", line 391, in test_determinism
    res1, res2 = get_results(), get_results()
  File "bfgs_test.py", line 389, in get_results
    rastrigin, initial_position=start, tolerance=1e-5))
  File "/home/tudockho/.local/lib/python3.6/site-packages/tensorflow_probability/python/optimizer/bfgs.py", line 269, in minimize
    control_inputs)
  File "/home/tudockho/.local/lib/python3.6/site-packages/tensorflow_probability/python/optimizer/bfgs_utils.py", line 62, in get_initial_state_args
    f0, df0 = value_and_gradients_function(initial_position)
  File "bfgs_test.py", line 34, in val_and_grad
    return tfp.math.value_and_gradient(value_fn, x)
AttributeError: module 'tensorflow_probability.python.math' has no attribute 'value_and_gradient'

======================================================================
ERROR: test_dynamic_shapes (__main__.BfgsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tudockho/.local/lib/python3.6/site-packages/tensorflow/python/framework/test_util.py", line 946, in decorated
    f(self, *args, **kwargs)
  File "bfgs_test.py", line 418, in test_dynamic_shapes
    quadratic, initial_position=start, tolerance=1e-8)
  File "/home/tudockho/.local/lib/python3.6/site-packages/tensorflow_probability/python/optimizer/bfgs.py", line 269, in minimize
    control_inputs)
  File "/home/tudockho/.local/lib/python3.6/site-packages/tensorflow_probability/python/optimizer/bfgs_utils.py", line 62, in get_initial_state_args
    f0, df0 = value_and_gradients_function(initial_position)
  File "bfgs_test.py", line 34, in val_and_grad
    return tfp.math.value_and_gradient(value_fn, x)
AttributeError: module 'tensorflow_probability.python.math' has no attribute 'value_and_gradient'

======================================================================
ERROR: test_himmelblau (__main__.BfgsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tudockho/.local/lib/python3.6/site-packages/tensorflow/python/framework/test_util.py", line 946, in decorated
    f(self, *args, **kwargs)
  File "bfgs_test.py", line 253, in test_himmelblau
    himmelblau, initial_position=start, tolerance=1e-8))
  File "/home/tudockho/.local/lib/python3.6/site-packages/tensorflow_probability/python/optimizer/bfgs.py", line 269, in minimize
    control_inputs)
  File "/home/tudockho/.local/lib/python3.6/site-packages/tensorflow_probability/python/optimizer/bfgs_utils.py", line 62, in get_initial_state_args
    f0, df0 = value_and_gradients_function(initial_position)
  File "bfgs_test.py", line 34, in val_and_grad
    return tfp.math.value_and_gradient(value_fn, x)
AttributeError: module 'tensorflow_probability.python.math' has no attribute 'value_and_gradient'

======================================================================
ERROR: test_himmelblau_batch_all (__main__.BfgsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tudockho/.local/lib/python3.6/site-packages/tensorflow/python/framework/test_util.py", line 946, in decorated
    f(self, *args, **kwargs)
  File "bfgs_test.py", line 278, in test_himmelblau_batch_all
    stopping_condition=tfp.optimizer.converged_all, tolerance=1e-8))
AttributeError: module 'tensorflow_probability.python.optimizer' has no attribute 'converged_all'

======================================================================
ERROR: test_himmelblau_batch_any (__main__.BfgsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tudockho/.local/lib/python3.6/site-packages/tensorflow/python/framework/test_util.py", line 946, in decorated
    f(self, *args, **kwargs)
  File "bfgs_test.py", line 308, in test_himmelblau_batch_any
    stopping_condition=tfp.optimizer.converged_any, tolerance=1e-8))
AttributeError: module 'tensorflow_probability.python.optimizer' has no attribute 'converged_any'

======================================================================
ERROR: test_inverse_hessian_spec (__main__.BfgsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tudockho/.local/lib/python3.6/site-packages/tensorflow/python/framework/test_util.py", line 946, in decorated
    f(self, *args, **kwargs)
  File "bfgs_test.py", line 78, in test_inverse_hessian_spec
    initial_inverse_hessian_estimate=test_inv_hessian))
  File "/home/tudockho/.local/lib/python3.6/site-packages/tensorflow_probability/python/optimizer/bfgs.py", line 269, in minimize
    control_inputs)
  File "/home/tudockho/.local/lib/python3.6/site-packages/tensorflow_probability/python/optimizer/bfgs_utils.py", line 60, in get_initial_state_args
    f0, df0 = value_and_gradients_function(initial_position)
  File "bfgs_test.py", line 34, in val_and_grad
    return tfp.math.value_and_gradient(value_fn, x)
AttributeError: module 'tensorflow_probability.python.math' has no attribute 'value_and_gradient'

======================================================================
ERROR: test_quadratic_bowl_10d (__main__.BfgsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tudockho/.local/lib/python3.6/site-packages/tensorflow/python/framework/test_util.py", line 946, in decorated
    f(self, *args, **kwargs)
  File "bfgs_test.py", line 132, in test_quadratic_bowl_10d
    quadratic, initial_position=start, tolerance=1e-8))
  File "/home/tudockho/.local/lib/python3.6/site-packages/tensorflow_probability/python/optimizer/bfgs.py", line 269, in minimize
    control_inputs)
  File "/home/tudockho/.local/lib/python3.6/site-packages/tensorflow_probability/python/optimizer/bfgs_utils.py", line 62, in get_initial_state_args
    f0, df0 = value_and_gradients_function(initial_position)
  File "bfgs_test.py", line 34, in val_and_grad
    return tfp.math.value_and_gradient(value_fn, x)
AttributeError: module 'tensorflow_probability.python.math' has no attribute 'value_and_gradient'

======================================================================
ERROR: test_quadratic_bowl_2d (__main__.BfgsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tudockho/.local/lib/python3.6/site-packages/tensorflow/python/framework/test_util.py", line 946, in decorated
    f(self, *args, **kwargs)
  File "bfgs_test.py", line 57, in test_quadratic_bowl_2d
    quadratic, initial_position=start, tolerance=1e-8))
  File "/home/tudockho/.local/lib/python3.6/site-packages/tensorflow_probability/python/optimizer/bfgs.py", line 269, in minimize
    control_inputs)
  File "/home/tudockho/.local/lib/python3.6/site-packages/tensorflow_probability/python/optimizer/bfgs_utils.py", line 62, in get_initial_state_args
    f0, df0 = value_and_gradients_function(initial_position)
  File "bfgs_test.py", line 34, in val_and_grad
    return tfp.math.value_and_gradient(value_fn, x)
AttributeError: module 'tensorflow_probability.python.math' has no attribute 'value_and_gradient'

======================================================================
ERROR: test_quadratic_with_skew (__main__.BfgsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tudockho/.local/lib/python3.6/site-packages/tensorflow/python/framework/test_util.py", line 946, in decorated
    f(self, *args, **kwargs)
  File "bfgs_test.py", line 156, in test_quadratic_with_skew
    quadratic, initial_position=start, tolerance=1e-8))
  File "/home/tudockho/.local/lib/python3.6/site-packages/tensorflow_probability/python/optimizer/bfgs.py", line 269, in minimize
    control_inputs)
  File "/home/tudockho/.local/lib/python3.6/site-packages/tensorflow_probability/python/optimizer/bfgs_utils.py", line 62, in get_initial_state_args
    f0, df0 = value_and_gradients_function(initial_position)
  File "bfgs_test.py", line 34, in val_and_grad
    return tfp.math.value_and_gradient(value_fn, x)
AttributeError: module 'tensorflow_probability.python.math' has no attribute 'value_and_gradient'

======================================================================
ERROR: test_quadratic_with_strong_skew (__main__.BfgsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tudockho/.local/lib/python3.6/site-packages/tensorflow/python/framework/test_util.py", line 946, in decorated
    f(self, *args, **kwargs)
  File "bfgs_test.py", line 179, in test_quadratic_with_strong_skew
    quadratic, initial_position=start, tolerance=1e-8))
  File "/home/tudockho/.local/lib/python3.6/site-packages/tensorflow_probability/python/optimizer/bfgs.py", line 269, in minimize
    control_inputs)
  File "/home/tudockho/.local/lib/python3.6/site-packages/tensorflow_probability/python/optimizer/bfgs_utils.py", line 62, in get_initial_state_args
    f0, df0 = value_and_gradients_function(initial_position)
  File "bfgs_test.py", line 34, in val_and_grad
    return tfp.math.value_and_gradient(value_fn, x)
AttributeError: module 'tensorflow_probability.python.math' has no attribute 'value_and_gradient'

----------------------------------------------------------------------
Ran 15 tests in 3.727s

FAILED (errors=13, skipped=1)
`

**Comment by csuter** [comment]
If you're running tests at HEAD in the repo, you'll need to install `tfp-nightly`, which is built at HEAD every night, or run the tests using `bazel`, which will run the test using the locally checked out code.

**Comment by timudk** [comment]
Which bazel version works to run the unit tests? I have 0.26.0 installed and get the error message:

`bazel run //tensorflow_probability/python/optimizer:bfgs_test
WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
/home/tudockho/Documents/probability/tools/bazel.rc
INFO: Analyzed target //tensorflow_probability/python/optimizer:bfgs_test (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //tensorflow_probability/python/optimizer:bfgs_test up-to-date:
  bazel-bin/tensorflow_probability/python/optimizer/bfgs_test
INFO: Elapsed time: 0.201s, Critical Path: 0.00s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //tensorflow_probability/python/optimizer:bfgs_test
-----------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tudockho/.cache/bazel/_bazel_tudockho/cdbef65d6dc64b4853df3d19fd83a76d/execroot/tensorflow_probability/bazel-out/k8-fastbuild/bin/tensorflow_probability/python/optimizer/bfgs_test.runfiles/tensorflow_probability/tensorflow_probability/python/optimizer/bfgs_test.py", line 27, in <module>
    import tensorflow_probability as tfp
  File "/home/tudockho/.cache/bazel/_bazel_tudockho/cdbef65d6dc64b4853df3d19fd83a76d/execroot/tensorflow_probability/bazel-out/k8-fastbuild/bin/tensorflow_probability/python/optimizer/bfgs_test.runfiles/tensorflow_probability/tensorflow_probability/__init__.py", line 68, in <module>
    _ensure_tf_install()
  File "/home/tudockho/.cache/bazel/_bazel_tudockho/cdbef65d6dc64b4853df3d19fd83a76d/execroot/tensorflow_probability/bazel-out/k8-fastbuild/bin/tensorflow_probability/python/optimizer/bfgs_test.runfiles/tensorflow_probability/tensorflow_probability/__init__.py", line 65, in _ensure_tf_install
    present=tf.__version__))
ImportError: This version of TensorFlow Probability requires TensorFlow version >= 1.13; Detected an installation of version 1.10.1. Please upgrade TensorFlow to proceed.
`

**Comment by csuter** [comment]
The error refers to the tensorflow version -- do you have multiple versions installed somehow?

The warning from bazel can be ignored here.

**Comment by timudk** [comment]
Ok, I just realized that bazel uses Python2 and that one needs to checkout branch r0.6 for Tensorflow Probability in order to run the tests.

It works now, thank you for your help @csuter.
