### ISSUE TITLE
iris_custom_decay_dnn.py does not work

### ISSUE THREAD

**Issue by d3vv3d** [tensorflow/tensorflow#2922]
The code below is the current version of iris_custom_decay_dnn.py. The custom decay portion of which does not appear to work as whenever I run it I get the Traceback below. Through so light testing I discovered that the code works when the custom decay portion is removed.
# iris_custom_decay_dnn.py
```python
from sklearn import datasets, metrics
from sklearn.cross_validation import train_test_split

import tensorflow as tf

iris = datasets.load_iris()
X_train, X_test, y_train, y_test = train_test_split(iris.data,
                                                    iris.target,
                                                    test_size=0.2,
                                                    random_state=42)
#setup exponential decay function
def exp_decay(global_step):
    return tf.train.exponential_decay(
        learning_rate=0.1, global_step=global_step,
        decay_steps=100, decay_rate=0.001)

# use customized decay function in learning_rate
optimizer = tf.train.AdagradOptimizer(learning_rate=exp_decay)
classifier = tf.contrib.learn.DNNClassifier(hidden_units=[10, 20, 10],
                                            n_classes=3,
                                            optimizer=optimizer)
classifier.fit(X_train, y_train, steps=800)
score = metrics.accuracy_score(y_test, classifier.predict(X_test))
```
# Traceback
Traceback (most recent call last):
  File "/home/d3v/Py/SkFlow Iris DNN.py", line 22, in <module>
    classifier.fit(X_train, y_train, steps=800)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 182, in fit
    monitors=monitors)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 449, in _train_model
    train_op, loss_op = self._get_train_ops(features, targets)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/estimators/dnn.py", line 113, in _get_train_ops
    return super(DNNClassifier, self)._get_train_ops(features, targets)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/estimators/dnn_linear_combined.py", line 170, in _get_train_ops
    dnn_vars)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/estimators/dnn_linear_combined.py", line 356, in _get_dnn_training_ops
    return [self._dnn_optimizer.apply_gradients(zip(dnn_grads, dnn_vars))]
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/optimizer.py", line 300, in apply_gradients
    self._prepare()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/adagrad.py", line 70, in _prepare
    name="learning_rate")
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 620, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/constant_op.py", line 179, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/constant_op.py", line 162, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/tensor_util.py", line 421, in make_tensor_proto
    tensor_proto.string_val.extend([compat.as_bytes(x) for x in proto_values])
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/tensor_util.py", line 421, in <listcomp>
    tensor_proto.string_val.extend([compat.as_bytes(x) for x in proto_values])
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/compat.py", line 44, in as_bytes
    raise TypeError('Expected binary or unicode string, got %r' % bytes_or_text)
TypeError: Expected binary or unicode string, got <function exp_decay at 0x7f84e7161e18>

**Comment by sherrym** [comment]
convert_to_tensor expects value to be "An object whose type has a registered `Tensor` conversion function.", not an op.

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/framework/ops.py#L572

**Comment by prb12** [comment]
More importantly, AdagradOptimizer's learning_rate parameter is supposed to be 
```
Construct a new Adagrad optimizer.
   Args:
      learning_rate: A `Tensor` or a floating point value.  The learning rate.
```
The example code above passes in a python function which returns a Tensor.

I'm pretty sure that convert_to_tensor doesn't accept a python function:
```
13:19:46 :~$ python
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> def foo():
...   return tf.constant(0.1)
... 
>>> tf.convert_to_tensor(foo)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 620, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/constant_op.py", line 179, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/constant_op.py", line 162, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_util.py", line 421, in make_tensor_proto
    tensor_proto.string_val.extend([compat.as_bytes(x) for x in proto_values])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/compat.py", line 44, in as_bytes
    raise TypeError('Expected binary or unicode string, got %r' % bytes_or_text)
TypeError: Expected binary or unicode string, got <function foo at 0x7f80b90b3140>
>>> tf.convert_to_tensor(foo())
<tf.Tensor 'Const:0' shape=() dtype=float32>
>>> 
```

**Comment by denson** [comment]
Is there currently a workaround? I have a good bit of skflow scripts that I need to update to the current version.

**Comment by ilblackdragon** [comment]
The way to pass anything to optimizer is by passing a `callable` function as optimizer, like this:

```
def get_optimizer():
  def exp_decay(global_step):
      return tf.train.exponential_decay(
          learning_rate=0.1, global_step=global_step,
          decay_steps=100, decay_rate=0.001)

  # use customized decay function in learning_rate
  return tf.train.AdagradOptimizer(learning_rate=exp_decay)

classifier = tf.contrib.learn.DNNClassifier(
    hidden_units=[10, 20, 10], optimizer=get_optimizer, ...)
```

**Comment by nateypants** [comment]
I followed the suggestion by @ilblackdragon to pass a callable function, however, it still results in the same Traceback (TypeError: Expected binary or unicode string, got <function exp_decay at 0x11e9fc410>) once fit is called. Replacing exp_decay with a float works. Does not appear to be working.

Relevant code:
`X_train,y_train,X_valid,y_valid,X_test,y_test,_,_ = loadData()

feature_columns = learn.infer_real_valued_columns_from_input(X_train)

def get_optimizer():
	def exp_decay(global_step):
	  return tf.train.exponential_decay(
	      learning_rate=0.00001, global_step=global_step,
          decay_steps=100, decay_rate=0.97, starcase=True)
  	# use customized decay function in learning_rate
	return tf.train.AdagradOptimizer(learning_rate=exp_decay)

estimator = learn.DNNRegressor(
	model_dir='./Model3/',
	hidden_units=[int(np.mean([X_train.shape[1],1]))],
	feature_columns=feature_columns,
	enable_centered_bias=True,
	optimizer=get_optimizer
	)

epochs=20

estimator.fit(X_train,y_train,steps=epochs*y_train.shape[0])`

**Comment by ilblackdragon** [comment]
Oh, this should work:
```
def get_optimizer():
    def exp_decay(global_step):
      return tf.train.exponential_decay(
          learning_rate=0.00001, global_step=global_step,
          decay_steps=100, decay_rate=0.97, staircase=True)
    # use customized decay function in learning_rate
    return tf.train.AdagradOptimizer(
         learning_rate=exp_decay(tf.contrib.framework.get_global_step()))
```
or just:
```
def get_optimizer():
    return tf.train.AdagradOptimizer(
          learning_rate=tf.train.exponential_decay(
               learning_rate=0.00001, global_step=tf.contrib.framework.get_global_step(),
               decay_steps=100, decay_rate=0.97, staircase=True))
```
