### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by alexcruz0202** [tensorflow/tensorflow#29343]
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 Pro
- TensorFlow installed from (source or binary): build from source
- TensorFlow version: 1.13.1
- Python version: 3.6.3
- Bazel version (if compiling from source): 0.19.2
- CUDA/cuDNN version: (v10.0), (cudnn-10.0-windows10-x64-v7.5.0.56)

**Any other info / logs**
....
....
Application\vs\tensorflow;C:\msys64\usr\bin;F:\Work\VS\DNN\cuda\bin
    SET PYTHON_BIN_PATH=E:/Application/python/Miniconda3/python.exe
    SET PYTHON_LIB_PATH=E:/Application/python/Miniconda3/lib/site-packages
    SET TF_CUDA_CLANG=0
    SET TF_CUDA_COMPUTE_CAPABILITIES=5.0
    SET TF_CUDA_VERSION=10.0
    SET TF_CUDNN_VERSION=7
    SET TF_NEED_CUDA=1
    SET TF_NEED_OPENCL_SYCL=0
    SET TF_NEED_ROCM=0
  C:/msys64/usr/bin/bash.exe bazel-out/x64_windows-opt/genfiles/tensorflow/tf_python_api_gen_v1.genrule_script.sh
Traceback (most recent call last):
  File "\\?\C:\Users\Dev\AppData\Local\Temp\Bazel.runfiles_aeo0bwxr\runfiles\org_tensorflow\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "\\?\C:\Users\Dev\AppData\Local\Temp\Bazel.runfiles_aeo0bwxr\runfiles\org_tensorflow\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "\\?\C:\Users\Dev\AppData\Local\Temp\Bazel.runfiles_aeo0bwxr\runfiles\org_tensorflow\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "E:\Application\python\Miniconda3\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "E:\Application\python\Miniconda3\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "\\?\C:\Users\Dev\AppData\Local\Temp\Bazel.runfiles_aeo0bwxr\runfiles\org_tensorflow\tensorflow\python\tools\api\generator\create_python_api.py", line 27, in <module>
    from tensorflow.python.tools.api.generator import doc_srcs
  File "\\?\C:\Users\Dev\AppData\Local\Temp\Bazel.runfiles_aeo0bwxr\runfiles\org_tensorflow\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "\\?\C:\Users\Dev\AppData\Local\Temp\Bazel.runfiles_aeo0bwxr\runfiles\org_tensorflow\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "\\?\C:\Users\Dev\AppData\Local\Temp\Bazel.runfiles_aeo0bwxr\runfiles\org_tensorflow\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "\\?\C:\Users\Dev\AppData\Local\Temp\Bazel.runfiles_aeo0bwxr\runfiles\org_tensorflow\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "\\?\C:\Users\Dev\AppData\Local\Temp\Bazel.runfiles_aeo0bwxr\runfiles\org_tensorflow\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "E:\Application\python\Miniconda3\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "E:\Application\python\Miniconda3\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

**Comment by alexcruz0202** [comment]
It works on https://github.com/tensorflow/tensorflow/issues/28848#issuecomment-498554319

**Comment by achandraa** [comment]
Good to know the issue is resolved.
