### ISSUE TITLE
Build Issues with bazel 0.15.0, branch r1.12,no GPU

### ISSUE THREAD

**Issue by viX-shaw** [tensorflow/tensorflow#29341]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Linux ubuntu 4.4.0-21-generic
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:N/A
- TensorFlow installed from (source or binary):source
- TensorFlow version: r1.12
- Python version:3.6.6
- Installed using virtualenv? pip? conda?:conda
- Bazel version (if compiling from source):N/A
- GCC/Compiler version (if compiling from source):gcc version 5.4.0 20160609
- CUDA/cuDNN version:N/A
- GPU model and memory:N/A

**Describe the problem**
Compilation fails for tensorflow branch r1.12 with the following stacktrace.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
1) Bazel installed version - 0.15.0
2)./configure 
    Compilation flags  "-march=native -mssse3 -mcx16 -msse4.1 -msse4.2 -mpopcnt"

3)bazel build --config=opt --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" //tensorflow/tools/pip_package:build_pip_package

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**ERROR: /root/tensorflow/tensorflow/BUILD:533:1: Executing genrule //tensorflow:tf_python_api_gen_v1 failed (Exit 1)
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/python/tools/api/generator/create_python_api.py", line 27, in <module>
    from tensorflow.python.tools.api.generator import doc_srcs
  File "/root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 55, in <module>
    'tensorflow_estimator.python.estimator'))
  File "/root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/python/tools/component_api_helper.py", line 85, in package_hook
    set_child_as_subpackage()
  File "/root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1.runfiles/org_tensorflow/tensorflow/python/tools/component_api_helper.py", line 69, in set_child_as_subpackage
    os.path.join(os.path.dirname(child_pkg.__file__), ".."))]
AttributeError: module **'tensorflow_estimator.python.estimator'** has no attribute '__file__'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1.055s, Critical Path: 0.55s
INFO: 0 processes.
FAILED: Build did NOT complete successfully**

**Comment by gadagashwini** [comment]
@viX-shaw Can you please let us know if you followed the steps mentioned in the tensorflow website [link](https://www.tensorflow.org/install/source#tested_build_configurations). Thanks!

**Comment by viX-shaw** [comment]
@gadagashwini Yes , I followed all the steps in that tutorial. After failing to build r1.12 with bazel 0.15 may times , I tried building r1.13 with 0.19 and it worked without any additional pip or lib dependencies.

**Comment by gadagashwini** [comment]
Good to know the issue is resolved.

**Comment by viX-shaw** [comment]
Sure
