### ISSUE TITLE
Error in Building of TFF on virtualenv Windows

### ISSUE THREAD

**Issue by AbbasiAYE** [tensorflow/tensorflow#29353]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version: tensorflow-1.13.1
- Python version :3.7
- Installed using virtualenv (16.6.0) and pip (19.1.1)
- Bazel version (if compiling from source):  bazel v0.26.0 already installed.

I want some new functions in TFF, that are not added to the compiled version, so I want to build the newest code. I cloned it with git, then I followed the steps in [https://github.com/tensorflow/federated/blob/master/docs/install.md](url) 
But stuck in step 7 when building with Bazel. The following is the error:

Error Track:
```
(venv) C:\Users\ezalaab\Documents\eclipse-workspace\MANA-FederatedLearning\location-based-federated-learning\Test\federated>bazel build //tensorflow_federated/tools:build_pip_package
Starting local Bazel server and connecting to it...
INFO: Call stack for the definition of repository 'local_config_cc' which is a cc_autoconf (rule definition at C:/users/ezalaab/_bazel_ezalaab/cixvmrpx/external/bazel_tools/tools/cpp/cc_configure.bzl:53:15):
 - C:/users/ezalaab/_bazel_ezalaab/cixvmrpx/external/bazel_tools/tools/cpp/cc_configure.bzl:91:5
 - /DEFAULT.WORKSPACE.SUFFIX:286:1
ERROR: An error occurred during the fetch of repository 'local_config_cc':
   Traceback (most recent call last):
        File "C:/users/ezalaab/_bazel_ezalaab/cixvmrpx/external/bazel_tools/tools/cpp/cc_configure.bzl", line 46
                configure_windows_toolchain(repository_ctx)
        File "C:/users/ezalaab/_bazel_ezalaab/cixvmrpx/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 349, in configure_windows_toolchain
                _find_missing_vc_tools(repository_ctx, vc_path)
        File "C:/users/ezalaab/_bazel_ezalaab/cixvmrpx/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 252, in _find_missing_vc_tools
                find_msvc_tool(repository_ctx, vc_path, tool)
        File "C:/users/ezalaab/_bazel_ezalaab/cixvmrpx/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 225, in find_msvc_tool
                repository_ctx.path((vc_path + "\\Tools\\MSVC")).readdir()
C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC (No such file or directory)
INFO: Call stack for the definition of repository 'benjaminp_six' which is a new_git_repository (rule definition at C:/users/ezalaab/_bazel_ezalaab/cixvmrpx/external/bazel_tools/tools/build_defs/repo/git.bzl:239:22):
 - C:/users/ezalaab/documents/eclipse-workspace/mana-federatedlearning/location-based-federated-learning/test/federated/WORKSPACE:20:1
ERROR: no such package '@local_config_cc//': Traceback (most recent call last):
        File "C:/users/ezalaab/_bazel_ezalaab/cixvmrpx/external/bazel_tools/tools/cpp/cc_configure.bzl", line 46
                configure_windows_toolchain(repository_ctx)
        File "C:/users/ezalaab/_bazel_ezalaab/cixvmrpx/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 349, in configure_windows_toolchain
                _find_missing_vc_tools(repository_ctx, vc_path)
        File "C:/users/ezalaab/_bazel_ezalaab/cixvmrpx/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 252, in _find_missing_vc_tools
                find_msvc_tool(repository_ctx, vc_path, tool)
        File "C:/users/ezalaab/_bazel_ezalaab/cixvmrpx/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 225, in find_msvc_tool
                repository_ctx.path((vc_path + "\\Tools\\MSVC")).readdir()
C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC (No such file or directory)
ERROR: Analysis of target '//tensorflow_federated/tools:build_pip_package' failed; build aborted: no such package '@local_config_cc//': Traceback (most recent call last):
        File "C:/users/ezalaab/_bazel_ezalaab/cixvmrpx/external/bazel_tools/tools/cpp/cc_configure.bzl", line 46
                configure_windows_toolchain(repository_ctx)
        File "C:/users/ezalaab/_bazel_ezalaab/cixvmrpx/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 349, in configure_windows_toolchain
                _find_missing_vc_tools(repository_ctx, vc_path)
        File "C:/users/ezalaab/_bazel_ezalaab/cixvmrpx/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 252, in _find_missing_vc_tools
                find_msvc_tool(repository_ctx, vc_path, tool)
        File "C:/users/ezalaab/_bazel_ezalaab/cixvmrpx/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 225, in find_msvc_tool
                repository_ctx.path((vc_path + "\\Tools\\MSVC")).readdir()
C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC (No such file or directory)
INFO: Elapsed time: 4.112s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (27 packages loaded, 226 targets conf\
igured)
```

**Comment by gadagashwini** [comment]
@AbbasiAYE Please have a look on this [link](https://www.tensorflow.org/install/source_windows) to install Tensorflow from source using bazel. Please let us know how it progresses. Thanks!

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
