### ISSUE TITLE
About can't use GPU to run programs, but I have GPU and CUDA environment

### ISSUE THREAD

**Issue by youthliuxi** [tensorflow/tensorflow#29362]
&emsp;&emsp;I have 4 GTX1080 graphics card. but I can't using tensorflow-gpu to run my code。
&emsp;&emsp;CUDA？ yes
&emsp;&emsp;Here are my CUDA information, my source code, error alerts, graphics card information
&emsp;&emsp;thanks for your help

## some information

OS Platform and Distribution: Ubuntu 14.04.5 LTS
TensorFlow installed from: pip install
TensorFlow version: 1.2.0
CUDA/cuDNN version: 8.0.61

## This is my "nvcc -V" tips

```bash
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2013 NVIDIA Corporation
Built on Wed_Jul_17_18:36:13_PDT_2013
Cuda compilation tools, release 5.5, V5.5.0
```

## This is my source code.

```python
import tensorflow as tf
with tf.device('/device:GPU:0'):
        a = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[2, 3], name='a')
        b = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[3, 2], name='b')
        c = tf.matmul(a, b)
sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))
# 运行这个 op.
print (sess.run(c))
sess.close()
```

## That is my error tip

```
2019-06-03 22:10:41.340072: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations. 2019-06-03 22:10:41.340118: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations. 2019-06-03 22:10:41.340136: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2019-06-03 22:10:41.340151: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2019-06-03 22:10:41.340167: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
Device mapping: no known devices.
2019-06-03 22:10:41.350495: I tensorflow/core/common_runtime/direct_session.cc:265] Device mapping:

Traceback (most recent call last):
  File "/home/leon/.conda/envs/leon/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1139, in _do_call
    return fn(*args)
  File "/home/leon/.conda/envs/leon/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1117, in _run_fn
    self._extend_graph()
  File "/home/leon/.conda/envs/leon/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1166, in _extend_graph
    self._session, graph_def.SerializeToString(), status)
  File "/home/leon/.conda/envs/leon/lib/python3.6/contextlib.py", line 89, in __exit__
    next(self.gen)
  File "/home/leon/.conda/envs/leon/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device for operation 'MatMul': Operation was explicitly assigned to /device:GPU:0 but available devices are [ /job:localhost/replica:0/task:0/cpu:0 ]. Make sure the device specification refers to a valid device.
         [[Node: MatMul = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=false, _device="/device:GPU:0"](a, b)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cpuOrGpu.py", line 11, in <module>
    print (sess.run(c))
  File "/home/leon/.conda/envs/leon/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/home/leon/.conda/envs/leon/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "/home/leon/.conda/envs/leon/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "/home/leon/.conda/envs/leon/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device for operation 'MatMul': Operation was explicitly assigned to /device:GPU:0 but available devices are [ /job:localhost/replica:0/task:0/cpu:0 ]. Make sure the device specification refers to a valid device.
         [[Node: MatMul = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=false, _device="/device:GPU:0"](a, b)]]

Caused by op 'MatMul', defined at:
  File "cpuOrGpu.py", line 7, in <module>
    c = tf.matmul(a, b)
  File "/home/leon/.conda/envs/leon/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 1816, in matmul
    a, b, transpose_a=transpose_a, transpose_b=transpose_b, name=name)
  File "/home/leon/.conda/envs/leon/lib/python3.6/site-packages/tensorflow/python/ops/gen_math_ops.py", line 1217, in _mat_mul
    transpose_b=transpose_b, name=name)
  File "/home/leon/.conda/envs/leon/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/home/leon/.conda/envs/leon/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/leon/.conda/envs/leon/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Cannot assign a device for operation 'MatMul': Operation was explicitly assigned to /device:GPU:0 but available devices are [ /job:localhost/replica:0/task:0/cpu:0 ]. Make sure the device specification refers to a valid device.
         [[Node: MatMul = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=false, _device="/device:GPU:0"](a, b)]]
```

## This is my NVIDIA graphics card tips

```bash
Mon Jun  3 22:18:34 2019
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.130                Driver Version: 384.130                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1080    Off  | 00000000:02:00.0  On |                  N/A |
|  0%   49C    P8    15W / 260W |      2MiB /  8105MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 1080    Off  | 00000000:03:00.0 Off |                  N/A |
|  0%   45C    P8    17W / 260W |      0MiB /  8114MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX 1080    Off  | 00000000:81:00.0 Off |                  N/A |
|  0%   45C    P8    12W / 260W |      0MiB /  8114MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GeForce GTX 1080    Off  | 00000000:82:00.0 Off |                  N/A |
|  0%   43C    P8    13W / 260W |      0MiB /  8114MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by gadagashwini** [comment]
@youthliuxi I would like to encourage you for using higher versions of Tensorflow since your system navidia driver supports CUDA 9.0. Its only going to get better moving forward and can provide more support. Thanks!

**Comment by youthliuxi** [comment]
> @youthliuxi I would like to encourage you for using higher versions of Tensorflow since your system navidia driver supports CUDA 9.0. Its only going to get better moving forward and can provide more support. Thanks!

So, it that the reason? I just us the CUDA 8.0, so I can't find my NVIDIA graphics card

**Comment by gadagashwini** [comment]
@youthliuxi The below list has the Navidia graphic driver versions and respective Cuda versions. Please Install accordingly.
![Selection_011](https://user-images.githubusercontent.com/48476109/59018314-3ee75a80-8863-11e9-8ac6-7115f9458552.png)
Let us know is that resolve your issue. Thanks!

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
