### ISSUE TITLE
Failed to convert object of type <class 'dict'> to Tensor

### ISSUE THREAD

**Issue by cvivesa** [tensorflow/tensorflow#29513]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

I'm writing some code to create a tf.estimator.BoostedTreeRegressor. I'm loading my data through pandas, so both my features and labels are pd frames. Due to this, my training function for the estimator is 
```python
tf.estimator.inputs.pandas_input_fn(x=X_train,y=y_train,shuffle= True, batch_size = batch_size)
```
and the testing function is 
```python
tf.estimator.inputs.pandas_input_fn(x=X_test,y=y_test, shuffle = False, batch_size = batch_size)
```
Whenever I run the train function, I get the following error:
```python
TypeError: Failed to convert object of type <class 'dict'> to Tensor. Contents: {'PP': <tf.Tensor 'random_shuffle_queue_DequeueUpTo:11' shape=(None,) dtype=float64>}. Consider casting elements to a supported type.
```

**Other info / logs**
```python
WARNING: Logging before flag parsing goes to stderr.
W0606 15:20:02.134926 11092 estimator.py:1799] Using temporary folder as model directory: C:\Users\CRISTI~1\AppData\Local\Temp\tmpeez4al44
W0606 15:20:02.150548 11092 deprecation.py:323] From C:\Users\CristianVives\.conda\envs\ml\lib\site-packages\tensorflow\python\training\training_util.py:238: Variable.initialized_value (from tensorflow.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.
W0606 15:20:02.166169 11092 deprecation.py:323] From C:\Users\CristianVives\.conda\envs\ml\lib\site-packages\tensorflow_estimator\python\estimator\inputs\queues\feeding_queue_runner.py:62: QueueRunner.__init__ (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
W0606 15:20:02.166169 11092 deprecation.py:323] From C:\Users\CristianVives\.conda\envs\ml\lib\site-packages\tensorflow_estimator\python\estimator\inputs\queues\feeding_functions.py:500: add_queue_runner (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
W0606 15:20:02.181790 11092 deprecation.py:323] From C:\Users\CristianVives\.conda\envs\ml\lib\site-packages\tensorflow\python\feature_column\feature_column.py:2121: NumericColumn._transform_feature (from tensorflow.python.feature_column.feature_column_v2) is deprecated and will be removed in a future version.
Instructions for updating:
The old _FeatureColumn APIs are being deprecated. Please use the new FeatureColumn APIs instead.
W0606 15:20:02.181790 11092 deprecation.py:323] From C:\Users\CristianVives\.conda\envs\ml\lib\site-packages\tensorflow\python\feature_column\feature_column_v2.py:2758: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.cast` instead.
Traceback (most recent call last):
  File "C:\Users\CristianVives\.conda\envs\ml\lib\site-packages\tensorflow\python\framework\tensor_util.py", line 559, in make_tensor_proto
    str_values = [compat.as_bytes(x) for x in proto_values]
  File "C:\Users\CristianVives\.conda\envs\ml\lib\site-packages\tensorflow\python\framework\tensor_util.py", line 559, in <listcomp>
    str_values = [compat.as_bytes(x) for x in proto_values]
  File "C:\Users\CristianVives\.conda\envs\ml\lib\site-packages\tensorflow\python\util\compat.py", line 61, in as_bytes
    (bytes_or_text,))
TypeError: Expected binary or unicode string, got {'PP': <tf.Tensor 'random_shuffle_queue_DequeueUpTo:11' shape=(None,) dtype=float64>}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/CristianVives/Documents/translation/scratch/driver.py", line 51, in <module>
    model.train(train_fun)
  File "C:\Users\CristianVives\.conda\envs\ml\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 359, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "C:\Users\CristianVives\.conda\envs\ml\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1139, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "C:\Users\CristianVives\.conda\envs\ml\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1169, in _train_model_default
    features, labels, ModeKeys.TRAIN, self.config)
  File "C:\Users\CristianVives\.conda\envs\ml\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1127, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "C:\Users\CristianVives\.conda\envs\ml\lib\site-packages\tensorflow_estimator\python\estimator\canned\boosted_trees.py", line 1924, in _model_fn
    train_in_memory=train_in_memory)
  File "C:\Users\CristianVives\.conda\envs\ml\lib\site-packages\tensorflow_estimator\python\estimator\canned\boosted_trees.py", line 1087, in _bt_model_fn
    batch_size = array_ops.shape(labels)[0]
  File "C:\Users\CristianVives\.conda\envs\ml\lib\site-packages\tensorflow\python\ops\array_ops.py", line 313, in shape
    return shape_internal(input, name, optimize=True, out_type=out_type)
  File "C:\Users\CristianVives\.conda\envs\ml\lib\site-packages\tensorflow\python\ops\array_ops.py", line 337, in shape_internal
    input_tensor = ops.convert_to_tensor(input)
  File "C:\Users\CristianVives\.conda\envs\ml\lib\site-packages\tensorflow\python\framework\ops.py", line 1050, in convert_to_tensor
    return convert_to_tensor_v2(value, dtype, preferred_dtype, name)
  File "C:\Users\CristianVives\.conda\envs\ml\lib\site-packages\tensorflow\python\framework\ops.py", line 1108, in convert_to_tensor_v2
    as_ref=False)
  File "C:\Users\CristianVives\.conda\envs\ml\lib\site-packages\tensorflow\python\framework\ops.py", line 1186, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "C:\Users\CristianVives\.conda\envs\ml\lib\site-packages\tensorflow\python\framework\constant_op.py", line 304, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "C:\Users\CristianVives\.conda\envs\ml\lib\site-packages\tensorflow\python\framework\constant_op.py", line 245, in constant
    allow_broadcast=True)
  File "C:\Users\CristianVives\.conda\envs\ml\lib\site-packages\tensorflow\python\framework\constant_op.py", line 283, in _constant_impl
    allow_broadcast=allow_broadcast))
  File "C:\Users\CristianVives\.conda\envs\ml\lib\site-packages\tensorflow\python\framework\tensor_util.py", line 563, in make_tensor_proto
    "supported type." % (type(values), values))
TypeError: Failed to convert object of type <class 'dict'> to Tensor. Contents: {'PP': <tf.Tensor 'random_shuffle_queue_DequeueUpTo:11' shape=(None,) dtype=float64>}. Consider casting elements to a supported type.
```

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow-tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
