### ISSUE TITLE
 DLL load failed: The specified module could not be found

### ISSUE THREAD

**Issue by omniaabo** [tensorflow/tensorflow#29575]
when running code with keras library 
it ran at the first time , but when running it at the second time this exception appeared

C:\ProgramData\Anaconda3\envs\tf-1-9-36\python.exe "C:/Users/TOSHIBA/PycharmProjects/omnia text detection/CNN.py"
Traceback (most recent call last):
  File "C:/Users/TOSHIBA/PycharmProjects/omnia text detection/CNN.py", line 4, in <module>
    import numpy as np
  File "C:\ProgramData\Anaconda3\envs\tf-1-9-36\lib\site-packages\numpy\__init__.py", line 140, in <module>
    from . import _distributor_init
  File "C:\ProgramData\Anaconda3\envs\tf-1-9-36\lib\site-packages\numpy\_distributor_init.py", line 34, in <module>
    from . import _mklinit
ImportError: DLL load failed: The specified module could not be found.

**Comment by gadagashwini** [comment]
@omniaabo Please provide TensorFlow version. Also, did you compile from source or install a binary? Thanks!

**Comment by omniaabo** [comment]
@gadagashwini  
thanks for replaying 
I used python version 3.6.8 instead of 3.7.1
it works

**Comment by gadagashwini** [comment]
@omniaabo Good to know that it resolved. Will close this issue. Thanks!
