### ISSUE TITLE
hi, anyone know how to fix this?

### ISSUE THREAD

**Issue by JZhou3083** [tensorflow/tensorflow#29570]
>>> import tensorflow as tf
Traceback (most recent call last):
  File "D:\Deep_Learning\envs\tensorflow\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "D:\Deep_Learning\envs\tensorflow\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "D:\Deep_Learning\envs\tensorflow\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "D:\Deep_Learning\envs\tensorflow\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "D:\Deep_Learning\envs\tensorflow\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: 找不到指定的模块。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Deep_Learning\envs\tensorflow\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "D:\Deep_Learning\envs\tensorflow\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "D:\Deep_Learning\envs\tensorflow\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "D:\Deep_Learning\envs\tensorflow\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "D:\Deep_Learning\envs\tensorflow\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "D:\Deep_Learning\envs\tensorflow\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "D:\Deep_Learning\envs\tensorflow\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "D:\Deep_Learning\envs\tensorflow\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: 找不到指定的模块。

Failed to load the native TensorFlow runtime.

**Comment by aligoren** [comment]
This related to #22794

There should be a helpful comment for your error.

Maybe you should use CUDA 10.0. You can look at this comment

https://github.com/tensorflow/tensorflow/issues/22794#issuecomment-500099017

**Comment by pishangujeniya** [comment]
https://github.com/tensorflow/tensorflow/issues/22794#issuecomment-500099017

Try this configurations, don't forget to set path in environment variables

**Comment by JZhou3083** [comment]
> This related to #22794
> 
> There should be a helpful comment for your error.
> 
> Maybe you should use CUDA 10.0. You can look at this comment
> 
> [#22794 (comment)](https://github.com/tensorflow/tensorflow/issues/22794#issuecomment-500099017)



> [#22794 (comment)](https://github.com/tensorflow/tensorflow/issues/22794#issuecomment-500099017)
> 
> Try this configurations, don't forget to set path in environment variables

Hey, thank you guys, I downgrade my Cudnn as you said and it worked out.
