### ISSUE TITLE
Compiling from source, can't find any working combination

### ISSUE THREAD

**Issue by tmsd2001** [tensorflow/tensorflow#29597]
GPU 1080Ti
cuda 10.1
cuDNN 7.6.0
nccl 2.4.7
Ubuntu 18.04.2
Python 3.6
Tensorflow r1.12, r1.13, r1.14
Bazel 0.17.2, 0.18.0, 0.25.2, 0.26.1

r1.14 + 0.26.1
downgrade bazle to 0.25.2

r1.14 + 0.25.2
This error:
`Traceback (most recent call last):
  File "third_party/gpus/find_cuda_config.py", line 497, in <module>
    main()
  File "third_party/gpus/find_cuda_config.py", line 489, in main
    for key, value in sorted(find_cuda_config().items()):
  File "third_party/gpus/find_cuda_config.py", line 448, in find_cuda_config
    _get_default_cuda_paths(cuda_version))
  File "third_party/gpus/find_cuda_config.py", line 164, in _get_default_cuda_paths
    ] + _get_ld_config_paths()
  File "third_party/gpus/find_cuda_config.py", line 144, in _get_ld_config_paths
    match = pattern.match(line.decode("ascii"))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 27: ordinal not in range(128)
Asking for detailed CUDA configuration...
`
I try any other combination of tensorflow ans bazel but I always get errors in different places.

r1.13 + 0.25.2
downgrate to 0.21.0

./configure work

Error at compiling:

`bazel build --config=opt --config=mkl --config=cuda //tensorflow/tools/pip_package:build_pip_package`

`ERROR: Skipping '//tensorflow/tools/pip_package:build_pip_package': error loading package 'tensorflow/tools/pip_package': in /home/thomasd/tensorflow/tensorflow/tensorflow.bzl: Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
	File "/home/thomasd/tensorflow/third_party/gpus/cuda_configure.bzl", line 1556
		_create_local_cuda_repository(repository_ctx)
	File "/home/thomasd/tensorflow/third_party/gpus/cuda_configure.bzl", line 1302, in _create_local_cuda_repository
		_find_libs(repository_ctx, cuda_config)
	File "/home/thomasd/tensorflow/third_party/gpus/cuda_configure.bzl", line 840, in _find_libs
		_find_cuda_lib("cublas", repository_ctx, cpu_value, c..., ...)
	File "/home/thomasd/tensorflow/third_party/gpus/cuda_configure.bzl", line 752, in _find_cuda_lib
		auto_configure_fail(("Cannot find cuda library %s" %...))
	File "/home/thomasd/tensorflow/third_party/gpus/cuda_configure.bzl", line 342, in auto_configure_fail
		fail(("\n%sCuda Configuration Error:%...)))

Cuda Configuration Error: Cannot find cuda library libcublas.so.10.1
WARNING: Target pattern parsing failed.
ERROR: error loading package 'tensorflow/tools/pip_package': in /home/thomasd/tensorflow/tensorflow/tensorflow.bzl: Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
	File "/home/thomasd/tensorflow/third_party/gpus/cuda_configure.bzl", line 1556
		_create_local_cuda_repository(repository_ctx)
	File "/home/thomasd/tensorflow/third_party/gpus/cuda_configure.bzl", line 1302, in _create_local_cuda_repository
		_find_libs(repository_ctx, cuda_config)
	File "/home/thomasd/tensorflow/third_party/gpus/cuda_configure.bzl", line 840, in _find_libs
		_find_cuda_lib("cublas", repository_ctx, cpu_value, c..., ...)
	File "/home/thomasd/tensorflow/third_party/gpus/cuda_configure.bzl", line 752, in _find_cuda_lib
		auto_configure_fail(("Cannot find cuda library %s" %...))
	File "/home/thomasd/tensorflow/third_party/gpus/cuda_configure.bzl", line 342, in auto_configure_fail
		fail(("\n%sCuda Configuration Error:%...)))

Cuda Configuration Error: Cannot find cuda library libcublas.so.10.1
INFO: Elapsed time: 5.369s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: tensorflow/tools/pip_package
    Fetching @local_config_cuda; fetching
`

r1.12 + 0.21.0

.configure work

Error at compiling:

`ERROR: error loading package '': Encountered error while reading extension file 'closure/defs.bzl': no such package '@io_bazel_rules_closure//closure': The native http_archive rule is deprecated. load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive") for a drop-in replacement.
Use --incompatible_remove_native_http_archive=false to temporarily continue using the native rule.
ERROR: error loading package '': Encountered error while reading extension file 'closure/defs.bzl': no such package '@io_bazel_rules_closure//closure': The native http_archive rule is deprecated. load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive") for a drop-in replacement.
Use --incompatible_remove_native_http_archive=false to temporarily continue using the native rule.
INFO: Elapsed time: 1.986s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    Fetching @io_bazel_rules_closure; fetching`

I try any other combination of tensorflow and bazel but I always get errors in different places.

**Comment by wdirons** [comment]
This fix in master: https://github.com/tensorflow/tensorflow/pull/28209, is needed for 1.14.

1.14 is the only release than can be compiled with CUDA 10.1, if you want to compile 1.13, you'll need to use CUDA 10.0
