### ISSUE TITLE
Realime webcam error

### ISSUE THREAD

**Issue by thenerdpoint60** [tensorflow/tensorflow#29634]
(tfpose) C:\Users\Prabhavi\Desktop\ml\tf-pose-estimation>python run_webcam.py --model=mobilenet_thin --resize=432x368 --camera=0
Traceback (most recent call last):
  File "C:\Users\Prabhavi\Anaconda3\envs\tfpose\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Prabhavi\Anaconda3\envs\tfpose\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Prabhavi\Anaconda3\envs\tfpose\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Prabhavi\Anaconda3\envs\tfpose\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Prabhavi\Anaconda3\envs\tfpose\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_webcam.py", line 8, in <module>
    from tf_pose.estimator import TfPoseEstimator
  File "C:\Users\Prabhavi\Desktop\ml\tf-pose-estimation\tf_pose\__init__.py", line 5, in <module>
    from tf_pose.runner import infer, Estimator, get_estimator
  File "C:\Users\Prabhavi\Desktop\ml\tf-pose-estimation\tf_pose\runner.py", line 7, in <module>
    from tf_pose import common
  File "C:\Users\Prabhavi\Desktop\ml\tf-pose-estimation\tf_pose\common.py", line 3, in <module>
    import tensorflow as tf
  File "C:\Users\Prabhavi\Anaconda3\envs\tfpose\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\Prabhavi\Anaconda3\envs\tfpose\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Prabhavi\Anaconda3\envs\tfpose\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Prabhavi\Anaconda3\envs\tfpose\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Prabhavi\Anaconda3\envs\tfpose\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Prabhavi\Anaconda3\envs\tfpose\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Prabhavi\Anaconda3\envs\tfpose\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Prabhavi\Anaconda3\envs\tfpose\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

**Comment by achandraa** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by thenerdpoint60** [comment]
> 
> 
> Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?
> 
> Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).
> 
> We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

I am using a GTX920 on my laptop with the tensorflow version 1.10 
I downloaded directly from the source.

**Comment by achandraa** [comment]
Did you try to follow steps from [TensorFlow website](https://www.tensorflow.org/install/source_windows) ? It is necessary to download proper Microsoft Visual C++ version. Also please verify the [CUDA compatibility matrix](https://www.tensorflow.org/install/source_windows#gpu) and let us know if that solves your problem. Thanks!

**Comment by thenerdpoint60** [comment]
> 
> 
> Did you try to follow steps from [TensorFlow website](https://www.tensorflow.org/install/source_windows) ? It is necessary to download proper Microsoft Visual C++ version. Also please verify the [CUDA compatibility matrix](https://www.tensorflow.org/install/source_windows#gpu) and let us know if that solves your problem. Thanks!

Yes I followed all the steps
Yes it necessary to download the proper c++ version and my CUDA compatibility is proper

**Comment by achandraa** [comment]
Please let us know which CUDA version you are using ? Also have a look on this [issue](https://github.com/tensorflow/tensorflow/issues/28848#issuecomment-495057676) and let us know if that helps. Thanks!

**Comment by achandraa** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
