### ISSUE TITLE
Scripts halts with make_initializable_iterator with non empty shared_name

### ISSUE THREAD

**Issue by FilatovArtm** [tensorflow/tensorflow#29695]
**System information**
- Custom code
- Linux Ubuntu 16.04
- TensorFlow installed from: source
- TensorFlow version: 1.12.0
- Python version: 2.7.12
- Bazel version: 0.25.1
- CUDA/cuDNN version: 9.0.176 / 7.0
- GPU model and memory: GeForce GTX 1080Ti

**Describe the current behavior**

The script doesn't finish. I discovered that it halts after TF_CloseSession and even KeyboardInterrupt can't stop the script. I also discovered that it exits normally if I pass `shared_name=""`. So it looks like that this place https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/data/iterator_ops.cc#L465
contains the bug. Possible deadlock or session can wait for iterator to free resources.

I also can reproduce the problem with MacOS without Cuda.

**Describe the expected behavior**

I expect this script to finish normally.

**Code to reproduce the issue**

```
import tensorflow as tf
import os
os.environ['CUDA_VISIBLE_DEVICES'] = ""


def generator():
    for i in range(10):
        yield [20.]


def main():
    config = tf.ConfigProto(intra_op_parallelism_threads=1,
                            inter_op_parallelism_threads=1)

    dataset = tf.data.Dataset.from_generator(
        generator,
        output_types=(tf.float32), output_shapes=(tf.TensorShape([1])))
    train_iterator = dataset.make_initializable_iterator(shared_name='g')

    with tf.Session(config=config) as session:
        session.run(train_iterator.initializer)

        data_producer = train_iterator.get_next()
        session.run(data_producer)
if __name__ == '__main__':
    main()
```

**Other info / logs**
Traceback from gdb:
```
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00007fffeafd62b1 in nsync::nsync_mu_semaphore_p(nsync::nsync_semaphore_s_*) () from /usr/lib/python2.7/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#2  0x00007fffeafd4028 in nsync::nsync_mu_lock_slow_(nsync::nsync_mu_s_*, nsync::waiter*, unsigned int, nsync::lock_type_s*) () from /usr/lib/python2.7/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#3  0x00007fffeafd411d in nsync::nsync_mu_lock(nsync::nsync_mu_s_*) () from /usr/lib/python2.7/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#4  0x00007fffe5618998 in tensorflow::ResourceMgr::Cleanup(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
   from /usr/lib/python2.7/dist-packages/tensorflow/python/../libtensorflow_framework.so
#5  0x00007fffe8a96fc0 in ?? () from /usr/lib/python2.7/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#6  0x00007fffe8a99ec5 in tensorflow::data::CapturedFunction::RunInstantiated(std::vector<tensorflow::Tensor, std::allocator<tensorflow::Tensor> > const&, std::vector<tensorflow::Tensor, std::allocator<tensorflow::Tensor> >*) ()
   from /usr/lib/python2.7/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#7  0x00007fffe894b13b in tensorflow::data::GeneratorDatasetOp::Dataset::Iterator::~Iterator() () from /usr/lib/python2.7/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#8  0x00007fffe894b211 in tensorflow::data::GeneratorDatasetOp::Dataset::Iterator::~Iterator() () from /usr/lib/python2.7/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#9  0x00007fffe8946ac5 in ?? () from /usr/lib/python2.7/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#10 0x00007fffe8966571 in tensorflow::data::IteratorResource::~IteratorResource() () from /usr/lib/python2.7/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#11 0x00007fffe5615d1c in tensorflow::ResourceMgr::Clear() () from /usr/lib/python2.7/dist-packages/tensorflow/python/../libtensorflow_framework.so
#12 0x00007fffea97826b in tensorflow::DirectSession::~DirectSession() () from /usr/lib/python2.7/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#13 0x00007fffea9787a1 in tensorflow::DirectSession::~DirectSession() () from /usr/lib/python2.7/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#14 0x00007fffe7903a07 in tensorflow::SessionRef::Close() () from /usr/lib/python2.7/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#15 0x00007fffe7ae2f0b in TF_CloseSession () from /usr/lib/python2.7/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#16 0x00007fffe789fae6 in ?? () from /usr/lib/python2.7/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#17 0x00000000004bc4aa in call_function (oparg=<optimized out>, pp_stack=0x7fffffffd260) at ../Python/ceval.c:4350
#18 PyEval_EvalFrameEx () at ../Python/ceval.c:2987
#19 0x00000000004b9b66 in PyEval_EvalCodeEx () at ../Python/ceval.c:3582
#20 0x00000000004c1f56 in fast_function (nk=<optimized out>, na=<optimized out>, n=1, pp_stack=0x7fffffffd460, func=<function at remote 0x7fffb659b578>) at ../Python/ceval.c:4445
#21 call_function (oparg=<optimized out>, pp_stack=0x7fffffffd460) at ../Python/ceval.c:4370
#22 PyEval_EvalFrameEx () at ../Python/ceval.c:2987
#23 0x00000000004b9b66 in PyEval_EvalCodeEx () at ../Python/ceval.c:3582
#24 0x00000000004d5669 in function_call.lto_priv () at ../Objects/funcobject.c:523
#25 0x00000000004eef5e in PyObject_Call (kw=0x0,
    arg=(<Session(_config=<ConfigProto at remote 0x7fffa22d57d0>, _graph=<Graph(_default_original_op=None, _handle_feeders={}, _stack_state_is_thread_local=False, _collections={'iterators': [<Tensor(_op=<Operation(_graph=<...>, _device_code_locations=[], _id_value=2, _control_flow_context=None, _outputs=[<...>], _original_op=None, _traceback=[('minimal_example.py', 30, '<module>', {'generator': <function at remote 0x7fffa22d56e0>, '__builtins__': <module at remote 0x7ffff7fb7b08>, '__file__': 'minimal_example.py', '__package__': None, 'tf': <module at remote 0x7ffff7ead2f0>, '__name__': '__main__', 'main': <function at remote 0x7fffa22d55f0>, 'os': <module at remote 0x7ffff7f8cd00>, '__doc__': None}, 3, None), ('minimal_example.py', 20, 'main', {...}, 13, None), ('/usr/lib/python2.7/dist-packages/tensorflow/python/data/ops/dataset_ops.py', 140, 'make_initializable_iterator', {'CacheDataset': <ABCMeta(__module__='tensorflow.python.data.ops.dataset_ops', _abc_negative_cache=<WeakSet(_remove=<function at remote 0x7fffb5...(truncated), func=<function at remote 0x7fffb659f140>) at ../Objects/abstract.c:2546
#26 instancemethod_call.lto_priv () at ../Objects/classobject.c:2602
#27 0x00000000004ae043 in PyObject_Call (kw=0x0, arg=(None, None, None), func=<instancemethod at remote 0x7fffa3329820>) at ../Objects/abstract.c:2546
#28 PyObject_CallFunctionObjArgs () at ../Objects/abstract.c:2773
#29 0x00000000004bed46 in PyEval_EvalFrameEx () at ../Python/ceval.c:2948
#30 0x00000000004c141f in fast_function (nk=<optimized out>, na=<optimized out>, n=0, pp_stack=0x7fffffffdb40, func=<function at remote 0x7fffa22d55f0>) at ../Python/ceval.c:4435
#31 call_function (oparg=<optimized out>, pp_stack=0x7fffffffdb40) at ../Python/ceval.c:4370
#32 PyEval_EvalFrameEx () at ../Python/ceval.c:2987
#33 0x00000000004b9b66 in PyEval_EvalCodeEx () at ../Python/ceval.c:3582
#34 0x00000000004eb69f in PyEval_EvalCode (
    locals={'generator': <function at remote 0x7fffa22d56e0>, '__builtins__': <module at remote 0x7ffff7fb7b08>, '__file__': 'minimal_example.py', '__package__': None, 'tf': <module at remote 0x7ffff7ead2f0>, '__name__': '__main__', 'main': <function at remote 0x7fffa22d55f0>, 'os': <module at remote 0x7ffff7f8cd00>, '__doc__': None},
    globals={'generator': <function at remote 0x7fffa22d56e0>, '__builtins__': <module at remote 0x7ffff7fb7b08>, '__file__': 'minimal_example.py', '__package__': None, 'tf': <module at remote 0x7ffff7ead2f0>, '__name__': '__main__', 'main': <function at remote 0x7fffa22d55f0>, 'os': <module at remote 0x7ffff7f8cd00>, '__doc__': None}, co=0x7ffff7eecd30) at ../Python/ceval.c:669
#35 run_mod.lto_priv () at ../Python/pythonrun.c:1376
#36 0x00000000004e58f2 in PyRun_FileExFlags () at ../Python/pythonrun.c:1362
#37 0x00000000004e41a6 in PyRun_SimpleFileExFlags () at ../Python/pythonrun.c:948
#38 0x00000000004938ce in Py_Main () at ../Modules/main.c:640
#39 0x00007ffff760b830 in __libc_start_main (main=0x493370 <main>, argc=2, argv=0x7fffffffdf88, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffdf78) at ../csu/libc-start.c:291
#40 0x0000000000493299 in _start ()
```

Looking at the `info threads`, we can see that all the threads are waiting for something:

```
* 1    Thread 0x7ffff7faf840 (LWP 27148) "python" syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
  2    Thread 0x7fffa2256700 (LWP 27153) "python" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  3    Thread 0x7fffa1a55700 (LWP 27154) "python" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  6    Thread 0x7fff93fff700 (LWP 27157) "python" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  7    Thread 0x7fffa0a53700 (LWP 27158) "python" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  8    Thread 0x7fffa1254700 (LWP 27159) "python" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
```

**Comment by gadagashwini** [comment]
I am able to reproduce the reported issue with Tensorflow 1.12.0 and 1.13.1. Thanks!

**Comment by feihugis** [comment]
I can reproduce this issue on the latest master branch. PR #30102 is submitted to try to fix this issue.
