### ISSUE TITLE
Can't import tensorflow

### ISSUE THREAD

**Issue by lmdrezende** [tensorflow/tensorflow#29713]
**System information**
- OS Platform and Distribution (Windows 7):
- TensorFlow installed from (source or binary):
- TensorFlow version: 1.13.1
- Python version: 3.6
- Installed using virtualenv? installed using pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 9.0
- GPU model and memory: Geforce GTX 550 Ti 2811mb

**Hello everyone. I just started to learn machine learning with python, and when I try to import tensorflow, I keep getting the same error:**

Python 3.6.8 |Anaconda, Inc.| (default, Feb 21 2019, 18:30:04) [MSC v.1916 64 bit (AMD64)] on win32
runfile('D:/Users/Lucas/PycharmProjects/TensorENV/test.py', wdir='D:/Users/Lucas/PycharmProjects/TensorENV')
Traceback (most recent call last):
  File "D:\Users\Lucas\Anaconda3\envs\tensor\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "D:\Program Files\JetBrains\PyCharm Community Edition 2019.1.3\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\Users\Lucas\Anaconda3\envs\tensor\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "D:\Users\Lucas\Anaconda3\envs\tensor\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "D:\Users\Lucas\Anaconda3\envs\tensor\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "D:\Users\Lucas\Anaconda3\envs\tensor\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed with error code -1073741795
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "D:\Program Files\JetBrains\PyCharm Community Edition 2019.1.3\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "D:\Program Files\JetBrains\PyCharm Community Edition 2019.1.3\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/Users/Lucas/PycharmProjects/TensorENV/test.py", line 1, in <module>
    import tensorflow
  File "D:\Program Files\JetBrains\PyCharm Community Edition 2019.1.3\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\Users\Lucas\Anaconda3\envs\tensor\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "D:\Program Files\JetBrains\PyCharm Community Edition 2019.1.3\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\Users\Lucas\Anaconda3\envs\tensor\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "D:\Program Files\JetBrains\PyCharm Community Edition 2019.1.3\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\Users\Lucas\Anaconda3\envs\tensor\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "D:\Users\Lucas\Anaconda3\envs\tensor\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "D:\Program Files\JetBrains\PyCharm Community Edition 2019.1.3\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\Users\Lucas\Anaconda3\envs\tensor\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "D:\Users\Lucas\Anaconda3\envs\tensor\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "D:\Users\Lucas\Anaconda3\envs\tensor\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "D:\Users\Lucas\Anaconda3\envs\tensor\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed with error code -1073741795
Failed to load the native TensorFlow runtime.

**Comment by gadagashwini** [comment]
@lmdrezende Just to verify, Did you follow the steps mentioned in official website of [Tensorflow](https://www.tensorflow.org/install/pip). Let us know if that helps. Thanks!

**Comment by lmdrezende** [comment]
Yeah. I installed the cpu-only version in a virtual environment for python 3.6 through pip install. But I just unistalled everything and I will try once more and get back here with the results. Thank you.

**Comment by mihaimaruseac** [comment]
Nit: When posting code, or errors, please wrap multiple lines of that with triple backquotes, so that formatting is nice and output is easy to read.

**Comment by lmdrezende** [comment]
I managed to get it to work. Instead of using pip to install tensorflow, I tried with conda install and somehow it worked. Thanks everyone.

**Comment by wayneotweezy** [comment]
What if I don't want to use conda
