### ISSUE TITLE
Cannot import tensor_util in TF 1.14.

### ISSUE THREAD

**Issue by leimao** [tensorflow/tensorflow#29723]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below): 1.14.0rc1
- Python version: 3.5
- Bazel version (if compiling from source): 0.25.2
- GCC/Compiler version (if compiling from source): 7.4.0
- CUDA/cuDNN version: 10.1
- GPU model and memory: TITAN V

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

Cannot import tensor_util.

```
$ python
Python 3.6.8 (default, Jan 14 2019, 11:02:34) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from tensorflow.python.framework import tensor_util
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'tensor_util'
```

**Describe the expected behavior**

We can import tensor_util in TF 1.13.

**Code to reproduce the issue**

See above.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by mihaimaruseac** [comment]
Cannot reproduce

```sh
mihaimaruseac@ankh:/tmp/5$ virtualenv . -p python3.5
Running virtualenv with interpreter /usr/bin/python3.5
Using base prefix '/usr'
New python executable in /tmp/5/bin/python3.5
Also creating executable in /tmp/5/bin/python
Installing setuptools, pkg_resources, pip, wheel...source bin/activate
pipdone.

mihaimaruseac@ankh:/tmp/5$ source bin/activate

(5) mihaimaruseac@ankh:/tmp/5$ pip install tensorflow==1.14.0rc1
Collecting tensorflow==1.14.0rc1
  Downloading https://files.pythonhosted.org/packages/d3/29/cd1f608f260addce161745be44e5696c3d4ef04a9974940bce32787b2711/tensorflow-1.14.0rc1-cp35-cp35m-manylinux1_x86_64.whl (109.2MB)
     |████████████████████████████████| 109.2MB 45.0MB/s 
Collecting gast>=0.2.0 (from tensorflow==1.14.0rc1)
Collecting tensorflow-estimator<1.15.0rc0,>=1.14.0rc0 (from tensorflow==1.14.0rc1)
  Using cached https://files.pythonhosted.org/packages/35/3c/c2ac7a2f56045adf1c94869fe012362b51bc8c94ac9e330823d207864904/tensorflow_estimator-1.14.0rc1-py2.py3-none-any.whl
Collecting protobuf>=3.6.1 (from tensorflow==1.14.0rc1)
  Using cached https://files.pythonhosted.org/packages/7c/d2/581ebc3c41879aca2c4fce5c37cdb8d779c4ea79109b6da7f640735ea0a2/protobuf-3.8.0-cp35-cp35m-manylinux1_x86_64.whl
Collecting keras-applications>=1.0.6 (from tensorflow==1.14.0rc1)
  Using cached https://files.pythonhosted.org/packages/71/e3/19762fdfc62877ae9102edf6342d71b28fbfd9dea3d2f96a882ce099b03f/Keras_Applications-1.0.8-py3-none-any.whl
Collecting keras-preprocessing>=1.0.5 (from tensorflow==1.14.0rc1)
  Using cached https://files.pythonhosted.org/packages/28/6a/8c1f62c37212d9fc441a7e26736df51ce6f0e38455816445471f10da4f0a/Keras_Preprocessing-1.1.0-py2.py3-none-any.whl
Collecting astor>=0.6.0 (from tensorflow==1.14.0rc1)
  Using cached https://files.pythonhosted.org/packages/d1/4f/950dfae467b384fc96bc6469de25d832534f6b4441033c39f914efd13418/astor-0.8.0-py2.py3-none-any.whl
Collecting absl-py>=0.7.0 (from tensorflow==1.14.0rc1)
Collecting six>=1.10.0 (from tensorflow==1.14.0rc1)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting wrapt>=1.11.1 (from tensorflow==1.14.0rc1)
Collecting google-pasta>=0.1.6 (from tensorflow==1.14.0rc1)
  Using cached https://files.pythonhosted.org/packages/d0/33/376510eb8d6246f3c30545f416b2263eee461e40940c2a4413c711bdf62d/google_pasta-0.1.7-py3-none-any.whl
Collecting termcolor>=1.1.0 (from tensorflow==1.14.0rc1)
Collecting numpy<2.0,>=1.14.5 (from tensorflow==1.14.0rc1)
  Using cached https://files.pythonhosted.org/packages/bb/ef/d5a21cbc094d3f4d5b5336494dbcc9550b70c766a8345513c7c24ed18418/numpy-1.16.4-cp35-cp35m-manylinux1_x86_64.whl
Collecting tensorboard<1.14.0,>=1.13.0 (from tensorflow==1.14.0rc1)
  Downloading https://files.pythonhosted.org/packages/0f/39/bdd75b08a6fba41f098b6cb091b9e8c7a80e1b4d679a581a0ccd17b10373/tensorboard-1.13.1-py3-none-any.whl (3.2MB)
     |████████████████████████████████| 3.2MB 33.4MB/s 
Collecting grpcio>=1.8.6 (from tensorflow==1.14.0rc1)
  Using cached https://files.pythonhosted.org/packages/14/19/f1858ed60786ff681a5f8681448b56bffaaa87a81e9a7ca5cd075a873b35/grpcio-1.21.1-cp35-cp35m-manylinux1_x86_64.whl
Requirement already satisfied: wheel>=0.26 in ./lib/python3.5/site-packages (from tensorflow==1.14.0rc1) (0.33.4)
Requirement already satisfied: setuptools in ./lib/python3.5/site-packages (from protobuf>=3.6.1->tensorflow==1.14.0rc1) (41.0.1)
Collecting h5py (from keras-applications>=1.0.6->tensorflow==1.14.0rc1)
  Using cached https://files.pythonhosted.org/packages/4c/77/c4933e12dca0f61bcdafc207c7532e1250b8d12719459fd85132f3daa9fd/h5py-2.9.0-cp35-cp35m-manylinux1_x86_64.whl
Collecting werkzeug>=0.11.15 (from tensorboard<1.14.0,>=1.13.0->tensorflow==1.14.0rc1)
  Using cached https://files.pythonhosted.org/packages/9f/57/92a497e38161ce40606c27a86759c6b92dd34fcdb33f64171ec559257c02/Werkzeug-0.15.4-py2.py3-none-any.whl
Collecting markdown>=2.6.8 (from tensorboard<1.14.0,>=1.13.0->tensorflow==1.14.0rc1)
  Using cached https://files.pythonhosted.org/packages/c0/4e/fd492e91abdc2d2fcb70ef453064d980688762079397f779758e055f6575/Markdown-3.1.1-py2.py3-none-any.whl
Installing collected packages: gast, tensorflow-estimator, six, protobuf, numpy, h5py, keras-applications, keras-preprocessing, astor, absl-py, wrapt, google-pasta, termcolor, werkzeug, grpcio, markdown, tensorboard, tensorflow
Successfully installed absl-py-0.7.1 astor-0.8.0 gast-0.2.2 google-pasta-0.1.7 grpcio-1.21.1 h5py-2.9.0 keras-applications-1.0.8 keras-preprocessing-1.1.0 markdown-3.1.1 numpy-1.16.4 protobuf-3.8.0 six-1.12.0 tensorboard-1.13.1 tensorflow-1.14.0rc1 tensorflow-estimator-1.14.0rc1 termcolor-1.1.0 werkzeug-0.15.4 wrapt-1.11.1

(5) mihaimaruseac@ankh:/tmp/5$ python
Python 3.5.4 (default, Sep  5 2017, 18:32:10) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from tensorflow.python.framework import tensor_util
>>> import tensorflow as tf
>>> tf.__version__
'1.14.0-rc1'
>>> tensor_util
<module 'tensorflow.python.framework.tensor_util' from '/tmp/5/lib/python3.5/site-packages/tensorflow/python/framework/tensor_util.py'>
>>> 
```

Most likely there's some issue on your system?

**Comment by gadagashwini** [comment]
@leimao Did you get chance to look on @mihaimaruseac comment. Let us know if that resolves your issue. Thanks!

**Comment by leimao** [comment]
Looks like the installation has some problems.
```
$ python3
Python 3.6.8 (default, Jan 14 2019, 11:02:34) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> tf.__version__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'tensorflow' has no attribute '__version__'
>>> 
```
I will try to install again.

**Comment by mihaimaruseac** [comment]
Can also try

```python
import tensorflow as tf
print(tf)
```

And that will give you the install location (something like `/tmp/1/lib/python3.6/site-packages/tensorflow/__init__.py`). Then, in the same directory you'll have a `tensorflow-${version}`/`tf-nightly-${version}` directory which gives you the version (for example `/tmp/1/lib/python3.6/site-package/tf-nightly...`)

**Comment by leimao** [comment]
> Can also try
> 
> ```python
> import tensorflow as tf
> print(tf)
> ```
> 
> And that will give you the install location (something like `/tmp/1/lib/python3.6/site-packages/tensorflow/__init__.py`). Then, in the same directory you'll have a `tensorflow-${version}`/`tf-nightly-${version}` directory which gives you the version (for example `/tmp/1/lib/python3.6/site-package/tf-nightly...`)

My output looks funny.

```
$ python3
Python 3.6.8 (default, Jan 14 2019, 11:02:34) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> tf.__version__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'tensorflow' has no attribute '__version__'
>>> print(tf)
<module 'tensorflow' (namespace)>
```

**Comment by mihaimaruseac** [comment]
what if you print `tf.VERSION` instead?

**Comment by leimao** [comment]
> what if you print `tf.VERSION` instead?

```
$ python3
Python 3.6.8 (default, Jan 14 2019, 11:02:34) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> tf.__version__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'tensorflow' has no attribute '__version__'
>>> print(tf)
<module 'tensorflow' (namespace)>
>>> print(tf.VERSION)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'tensorflow' has no attribute 'VERSION'
```

I will reinstall TensorFlow 1.14 anyway.

**Comment by gadagashwini** [comment]
Were you able to resolve this issue? Thanks!

**Comment by leimao** [comment]
> Were you able to resolve this issue? Thanks!

I have not got time to reinstall recently. I will try to make an install tomorrow. Which branch of the repository do you recommend me to use by the way? I am using Ubuntu 18.04 and CUDA 10.1. Thanks.

**Comment by mihaimaruseac** [comment]
For 1.14 should use the `r1.14` branch if you want to install from source.

Recommend doing a `pip install` if possible, though. Less chances for environment differences to cause issues

**Comment by leimao** [comment]
> For 1.14 should use the `r1.14` branch if you want to install from source.
> 
> Recommend doing a `pip install` if possible, though. Less chances for environment differences to cause issues

Looks like you guys have just uploaded a new wheel file for installation via pip. It seems to work for me now. Thanks.

```
$ python
Python 3.6.8 (default, Jan 14 2019, 11:02:34) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> tf.__version__
'1.14.0'
```

**Comment by periraviteja** [comment]
While running the object detection using tensorflow , i'm getting the below error. I uninstalled and installed the tensorflow and have the latest version. Any help in this regard is appreciated. 
Thanks much in advance.

"AttributeError: module 'wrapt' has no attribute 'ObjectProxy' "

**Comment by mihaimaruseac** [comment]
Please open a new issue, @periraviteja Please fill in all the details in the issue template and also provide a proper minified reproducer.

**Comment by DS-ejike** [comment]
@periraviteja have you been able to solve this error: "AttributeError: module 'wrapt' has no attribute 'ObjectProxy' "

**Comment by ChrisHRZ** [comment]
> @periraviteja您是否能够解决此错误：“ AttributeError：模块'wrapt'没有属性'ObjectProxy'“

我也遇到了这个问题

**Comment by shliang0603** [comment]
@DS-ejike , @periraviteja I have solved the problem, it due to wrapt using wrong version. Please install `wrapt==1.11.1`

>`pip install wrapt==1.11.1`
