### ISSUE TITLE
 Cannot copy between a TensorFlowLite tensor with shape

### ISSUE THREAD

**Issue by DurgaArunkumarSmitiv** [tensorflow/tensorflow#29735]
In Android , the sample as it is ,working fine.
But with my model which is having only 2 labels getting crashed.
Below is my crash description.

org.tensorflow.lite.examples.classification E/AndroidRuntime: FATAL EXCEPTION: inference
    Process: org.tensorflow.lite.examples.classification, PID: 31666
    java.lang.IllegalArgumentException: Cannot copy between a TensorFlowLite tensor with shape [1, 1001] and a Java object with shape [1, 2].
        at org.tensorflow.lite.Tensor.throwIfShapeIsIncompatible(Tensor.java:282)
        at org.tensorflow.lite.Tensor.throwIfDataIsIncompatible(Tensor.java:249)
        at org.tensorflow.lite.Tensor.copyTo(Tensor.java:141)
        at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:161)
        at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:275)
        at org.tensorflow.lite.Interpreter.run(Interpreter.java:249)
        at org.tensorflow.lite.examples.classification.tflite.ClassifierQuantizedMobileNet.runInference(ClassifierQuantizedMobileNet.java:94)
        at org.tensorflow.lite.examples.classification.tflite.Classifier.recognizeImage(Classifier.java:257)
        at org.tensorflow.lite.examples.classification.ClassifierActivity$1.run(ClassifierActivity.java:114)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by jvishnuvardhan** [comment]
This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!

**Comment by jvishnuvardhan** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
