### ISSUE TITLE
TFRecordDataset iterator not usuable in tf.keras .fit function (steps_per_epoch)

### ISSUE THREAD

**Issue by josefkorbel** [tensorflow/tensorflow#29743]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- TensorFlow installed from (source or binary): pip3 (binary)
- TensorFlow version (use command below): 1.13.1
- Python version: 3.6.7

**Describe the current behavior**
When using tf.Dataset (TFRecordDataset) API with new tf.keras API, I am passing the data iterator made from the dataset, however, before the first epoch finished, I got an `When using data tensors as input to a model, you should specify the `steps_per_epoch` argument.` exception, even though I've set this attribute in the fit method.

```
2019-06-13 14:22:25.393398: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 1995445000 Hz
2019-06-13 14:22:25.393681: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x2f7d120 executing computations on platform Host. Devices:
2019-06-13 14:22:25.393708: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
Epoch 1/2
19/20 [===========================>..] - ETA: 0s - loss: 1.1921e-07 - acc: 1.0000Traceback (most recent call last):
  File "TestServe.py", line 62, in <module>
    ts.train()
  File "TestServe.py", line 56, in train
    epochs=2, verbose=1, callbacks=callbacks, steps_per_epoch=20) #The steps_per_epoch is typically samples_per_epoch / batch_size
  File "/home/josef/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 880, in fit
    validation_steps=validation_steps)
  File "/home/josef/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_arrays.py", line 364, in model_iteration
    validation_in_fit=True)
  File "/home/josef/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_arrays.py", line 202, in model_iteration
    steps_per_epoch)
  File "/home/josef/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_arrays.py", line 76, in _get_num_samples_or_steps
    'steps_per_epoch')
  File "/home/josef/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_utils.py", line 230, in check_num_samples
    if check_steps_argument(ins, steps, steps_name):
  File "/home/josef/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_utils.py", line 960, in check_steps_argument
    input_type=input_type_str, steps_name=steps_name))
ValueError: When using data tensors as input to a model, you should specify the `steps_per_epoch` argument.
```

**Describe the expected behavior**
I would expect the epochs to to through smoothly, I actually suspect the validation part, because it is failing exactly before it.

**Code to reproduce the issue**
Here is my failing part:
```
import tensorflow as tf
import numpy as np
from typing import Union, List
from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping
from tensorflow.keras import layers
from tftools import TFTools


class TestServe():
    def __init__(self, tfrecords: Union[List[tf.train.Example], tf.train.Example], batch_size: int = 10, input_shape: tuple = (64, 23)) -> None:
        self.tfrecords = tfrecords
        self.batch_size = batch_size
        self.input_shape = input_shape

    def get_model(self):
        ins = layers.Input(shape=(64, 23))

        l = layers.Reshape((*self.input_shape, 1))(ins)
        l = layers.Conv2D(8, (30, 23), padding='same', activation='relu')(l)
        l = layers.MaxPool2D((4, 5), strides=(4, 5))(l)
        l = layers.Conv2D(16, (3, 3), padding='same', activation='relu')(l)
        l = layers.Conv2D(32, (3, 3), padding='same', activation='relu')(l)
        l = layers.MaxPool2D((2, 2), strides=(2, 2))(l)
        l = layers.Flatten()(l)

        out = layers.Dense(1, activation='softmax')(l)
        return tf.keras.models.Model(ins, out)

    def train(self):

        # Create Dataset
        dataset = TFTools.create_dataset(self.tfrecords)
        dataset = dataset.repeat(6).batch(self.batch_size)

        val_iterator = dataset.take(300).make_one_shot_iterator()
        train_iterator = dataset.skip(300).make_one_shot_iterator()

        model = self.get_model()
        model.summary()
        model.compile(optimizer='rmsprop',
                      loss='binary_crossentropy', metrics=['accuracy'])
        model.fit(train_iterator, validation_data=val_iterator,
                  epochs=10, verbose=1, steps_per_epoch=20)

    def predict(self, X: np.array) -> np.array:
        pass

ts = TestServe(['./ok.tfrecord', './nok.tfrecord'])
ts.train()
```

**Other info / logs**
I have ~ 1500 samples in those two tfrecord files, repeating it 6 times is 9.5k samples, so I dont think my generator ran out of samples.

I've even created [StackOverflow](https://stackoverflow.com/questions/56580538/tf-keras-api-with-tf-dataset-problem-steps-per-epoch-argument-problem) question as I am not entirely sure if this is a bug, but looks like it, since the tf.keras si relatively new, I cannot find much help elsewhere.

**Comment by josefkorbel** [comment]
I think I got it. The error message should be changed, because it is telling me to provide `steps_per_epoch` but I was actually missing `validation_steps` argument, later when looking into the TF source I found this.

```
validation_steps: Only relevant if `validation_data` is provided and
    is a dataset or dataset iterator. Total number of steps (batches of
    samples) to draw before stopping when performing validation
    at the end of every epoch.
```
So if I have 1000 samples with batch size of 10, I need to set 50 steps_per_epoch and 50 validation steps. however I have to repeat my dataset by number of epochs.

`number of samples / batchsize = steps_per_epoch + validation_steps`

But atleast I got it to train
```
2019-06-14 10:44:06.813409: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 1995425000 Hz
2019-06-14 10:44:06.813795: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x1f41520 executing computations on platform Host. Devices:
2019-06-14 10:44:06.813839: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
Epoch 1/5
49/50 [============================>.] - ETA: 0s - loss: 8.1339 - acc: 0.4898
Epoch 00001: val_loss improved from inf to 7.65234, saving model to cnn.hdf
50/50 [==============================] - 9s 174ms/step - loss: 8.2900 - acc: 0.4800 - val_loss: 7.6523 - val_acc: 0.5200
Epoch 2/5
```

**Comment by gadagashwini** [comment]
@josefkorbel Good to know that it resolved. We will close the issue now. Thanks!

**Comment by iteal** [comment]
@gadagashwini  I am using the tf.data.Dataset API and trying to convert Estimator to Keras fit function. I got this error because I use validation_steps=None (wait until the TFRecordDataset runs out of samples, which was ok with Estimator). Is there a way or I really need to know the number of samples?

**Comment by gadagashwini** [comment]
@iteal, Please open new issue and provide the all the information asked in the Template. Thanks!

**Comment by marchss** [comment]
@gadagashwini  if the data is very huge, we need to use tf.data dataset. Does this still require `validation_steps` and `steps_per_epoch` ? If yes, this defeat the purpose of using tf.data dataset, as it is impractical to obtain total number of samples in the training dataset.
