### ISSUE TITLE
Can't import Tensorflow GPU 2.0 beta on Win 7: DLL load failed with error code -1073741795

### ISSUE THREAD

**Issue by smbox** [tensorflow/tensorflow#29826]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Win 7 SP1**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: **N/A**
- TensorFlow installed from (source or binary): **Binary**
- TensorFlow version: **2.0 GPU Beta**
- Python version: **3.6.8**
- Installed using virtualenv? pip? conda?: **pip with no virtualenv**
- Bazel version (if compiling from source): **N/A**
- GCC/Compiler version (if compiling from source): **N/A**
- CUDA/cuDNN version: **10.0**
- GPU model and memory: **Geforce GTX 1050, 2GB memory**

**Describe the problem**
I am trying to install Tensorflow 2.0 GPU beta but it fails to download a DLL when trying to import the library.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

- Installed latest NVIDIA drivers
- Installed CUDA Toolkit 10.0 (Sept 2018)
- Installed cuDNN v7.6.0 (May 20, 2019), for CUDA 10.0
- Made sure that the following path are in the PATH variable:
```
SET PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin;%PATH%
SET PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\extras\CUPTI\libx64;%PATH%
SET PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\include;%PATH%
SET PATH=C:\tools\cuda\bin;%PATH%
```
- Installed Tensorflow:
```
pip install tensorflow-gpu==2.0.0-beta1
```
- Ran Python in command line and tried to import Tensorflow:
```
Python 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Program Files\Python36\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Program Files\Python36\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed with error code -1073741795

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Program Files\Python36\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Program Files\Python36\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed with error code -1073741795
```

**Any other info / logs**

Screenshots of my CUDA folders:
![cuda_bin_folder](https://user-images.githubusercontent.com/31602326/59554008-3e3d7b00-8f6b-11e9-8018-a52c0052192e.png)
![cuda_cupti_folder](https://user-images.githubusercontent.com/31602326/59554011-45648900-8f6b-11e9-83b8-d7ac84670695.png)
![cuda_include_path](https://user-images.githubusercontent.com/31602326/59554014-47c6e300-8f6b-11e9-9170-0400c4004478.png)
![cudnn_folder](https://user-images.githubusercontent.com/31602326/59554016-4a293d00-8f6b-11e9-8da2-8a8a6952b564.png)
![cudnn64_7](https://user-images.githubusercontent.com/31602326/59554039-9d02f480-8f6b-11e9-95de-c1738edc9ddd.png)

**Comment by achandraa** [comment]
Just to verify did you try to follow instructions from [TensorFlow website](https://www.tensorflow.org/install/pip) and downloaded [Microsoft Visual C++](pip3 install -U pip virtualenv). Also you can have a look on this [issue](https://github.com/tensorflow/tensorflow/issues/28848#issuecomment-495057676) and let us know if that helps. Thanks!

**Comment by smbox** [comment]
This is what I tried:

- I installed the Microsoft Visual C++ Redistributables and Build Tools: **Ok**

- I tried to install the Microsoft Visual C++ 2015 Redistributable Update 3 but it fails, the log revealed that a newer version already exist (not sure if it is really an issue?):

![vc_redist](https://user-images.githubusercontent.com/31602326/59606470-3dc5f100-90df-11e9-8841-3cd4e3f95b46.png)

```
[0624:1BF0][2019-06-17T08:34:09]i001: Burn v3.7.3813.0, Windows v6.1 (Build 7601: Service Pack 1), path: D:\Downloads\vc_redist.x64.exe, cmdline: ''
[0624:1BF0][2019-06-17T08:34:09]i000: Setting string variable 'WixBundleLog' to value 'C:\Users\Sam\AppData\Local\Temp\dd_vcredist_amd64_20190617083409.log'
[0624:1BF0][2019-06-17T08:34:09]i000: Setting string variable 'WixBundleOriginalSource' to value 'D:\Downloads\vc_redist.x64.exe'
[0624:1BF0][2019-06-17T08:34:09]i000: Setting string variable 'WixBundleOriginalSourceFolder' to value 'D:\Downloads\'
[0624:1BF0][2019-06-17T08:34:09]i000: Setting string variable 'WixBundleName' to value 'Microsoft Visual C++ 2015 Redistributable (x64) - 14.0.24215'
[0624:1BF0][2019-06-17T08:34:10]i100: Detect begin, 10 packages
[0624:1BF0][2019-06-17T08:34:10]i000: Setting version variable 'windows_uCRT_DetectKey' to value '10.0.10240.16390'
[0624:1BF0][2019-06-17T08:34:10]i000: Setting numeric variable 'windows_uCRT_DetectKeyExists' to value 1
[0624:1BF0][2019-06-17T08:34:10]i102: Detected related bundle: {5fb2083a-f3cc-4b78-93ff-bd9788b5de01}, type: Upgrade, scope: PerMachine, version: 14.16.27024.1, 

operation: Downgrade
[0624:1BF0][2019-06-17T08:34:10]i108: Detected compatible package: vcRuntimeMinimum_x64, provider: Microsoft.VS.VC_RuntimeMinimumVSU_amd64,v14, installed: {F1B0FB3A-

E0EA-47A6-9383-3650655403B0}, version: 14.16.27024, chained: {50A2BC33-C9CD-3BF1-A8FF-53C10A0B183C}
[0624:1BF0][2019-06-17T08:34:10]i103: Detected related package: {F1B0FB3A-E0EA-47A6-9383-3650655403B0}, scope: PerMachine, version: 14.16.27024.0, language: 0 operation: 

Downgrade
[0624:1BF0][2019-06-17T08:34:10]i108: Detected compatible package: vcRuntimeAdditional_x64, provider: Microsoft.VS.VC_RuntimeAdditionalVSU_amd64,v14, installed: 

{9D29FC96-9EEE-4253-943F-96B3BBFDD0B6}, version: 14.16.27024, chained: {EF1EC6A9-17DE-3DA9-B040-686A1E8A8B04}
[0624:1BF0][2019-06-17T08:34:10]i103: Detected related package: {9D29FC96-9EEE-4253-943F-96B3BBFDD0B6}, scope: PerMachine, version: 14.16.27024.0, language: 0 operation: 

Downgrade
[0624:1BF0][2019-06-17T08:34:10]i052: Condition '(VersionNT = v6.3 AND NOT VersionNT64) AND (windows_uCRT_DetectKeyExists AND windows_uCRT_DetectKey >= v10.0.10240.0)' 

evaluates to false.
[0624:1BF0][2019-06-17T08:34:10]i052: Condition '(VersionNT = v6.3 AND VersionNT64) AND (windows_uCRT_DetectKeyExists AND windows_uCRT_DetectKey >= v10.0.10240.0)' 

evaluates to false.
[0624:1BF0][2019-06-17T08:34:10]i052: Condition '(VersionNT = v6.2 AND NOT VersionNT64) AND (windows_uCRT_DetectKeyExists AND windows_uCRT_DetectKey >= v10.0.10240.0)' 

evaluates to false.
[0624:1BF0][2019-06-17T08:34:10]i052: Condition '(VersionNT = v6.2 AND VersionNT64) AND (windows_uCRT_DetectKeyExists AND windows_uCRT_DetectKey >= v10.0.10240.0)' 

evaluates to false.
[0624:1BF0][2019-06-17T08:34:10]i052: Condition '(VersionNT = v6.1 AND NOT VersionNT64) AND (windows_uCRT_DetectKeyExists AND windows_uCRT_DetectKey >= v10.0.10240.0)' 

evaluates to false.
[0624:1BF0][2019-06-17T08:34:10]i052: Condition '(VersionNT = v6.1 AND VersionNT64) AND (windows_uCRT_DetectKeyExists AND windows_uCRT_DetectKey >= v10.0.10240.0)' 

evaluates to true.
[0624:1BF0][2019-06-17T08:34:10]i052: Condition '(VersionNT = v6.0 AND NOT VersionNT64) AND (windows_uCRT_DetectKeyExists AND windows_uCRT_DetectKey >= v10.0.10240.0)' 

evaluates to false.
[0624:1BF0][2019-06-17T08:34:10]i052: Condition '(VersionNT = v6.0 AND VersionNT64) AND (windows_uCRT_DetectKeyExists AND windows_uCRT_DetectKey >= v10.0.10240.0)' 

evaluates to false.
[0624:1BF0][2019-06-17T08:34:10]i101: Detected package: vcRuntimeMinimum_x64, state: Obsolete, cached: None
[0624:1BF0][2019-06-17T08:34:10]i101: Detected package: vcRuntimeAdditional_x64, state: Obsolete, cached: None
[0624:1BF0][2019-06-17T08:34:10]i101: Detected package: Windows81_x86, state: Absent, cached: None
[0624:1BF0][2019-06-17T08:34:10]i101: Detected package: Windows81_x64, state: Absent, cached: None
[0624:1BF0][2019-06-17T08:34:10]i101: Detected package: Windows8_x86, state: Absent, cached: None
[0624:1BF0][2019-06-17T08:34:10]i101: Detected package: Windows8_x64, state: Absent, cached: None
[0624:1BF0][2019-06-17T08:34:10]i101: Detected package: Windows7_MSU_x86, state: Absent, cached: None
[0624:1BF0][2019-06-17T08:34:10]i101: Detected package: Windows7_MSU_x64, state: Present, cached: Complete
[0624:1BF0][2019-06-17T08:34:10]i101: Detected package: WindowsVista_MSU_x86, state: Absent, cached: None
[0624:1BF0][2019-06-17T08:34:10]i101: Detected package: WindowsVista_MSU_x64, state: Absent, cached: None
[0624:1BF0][2019-06-17T08:34:10]i052: Condition 'VersionNT64 >= v6.0 OR (VersionNT64 = v5.2 AND ServicePackLevel >= 1)' evaluates to true.
[0624:1BF0][2019-06-17T08:34:10]i199: Detect complete, result: 0x0
[0624:197C][2019-06-17T08:34:12]e000: Error 0x80070666: Cannot install a product when a newer version is installed.
```

- Make sure long paths are enabled on Windows.“Enable NTFS long paths policy” option does not exist on Windows 7, however I tried the suggestion to create a registry key at HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem\LongPathsEnabled] and setting the value (DWORD) to "1", didn't help:
https://social.msdn.microsoft.com/Forums/en-US/fc85630e-5684-4df6-ad2f-5a128de3deef/260-character-explorer-path-length-limit?forum=windowsgeneraldevelopmentissues

- pip3 install -U pip virtualenv

```
C:\>pip3 install -U pip virtualenv
Requirement already up-to-date: pip in c:\program files\python36\lib\site-packages (19.1.1)
Collecting virtualenv
  Using cached https://files.pythonhosted.org/packages/c4/9a/a3f62ac5122a65dec34ad4b5ed8d802633dae4bc06a0fc62e55fe3e96fe1/virtualenv-16.6.1-py2.py3-none-any.whl
Installing collected packages: virtualenv
Successfully installed virtualenv-16.6.1
```

- dependency walker:

![depends](https://user-images.githubusercontent.com/31602326/59606460-330b5c00-90df-11e9-891a-63b3a2d1f2a4.png)

**Comment by achandraa** [comment]
Looks like Microsoft Visual C++ is already installed on your system due to which lower version failed to install. Can you try uninstalling the software from your system and then try installing it through steps provided in [TensorFlow website](https://www.tensorflow.org/install/pip). Let us know. Thanks!

**Comment by smbox** [comment]
Which Microsoft Visual C++ should I uninstall? I have the regular Visual Studio Community 2017 and the Visual Studio Code along with their redists. See screenshot and please let me know. Also, if I uninstall something, some other program might break, this is one of my workstations.

![visual](https://user-images.githubusercontent.com/31602326/59764821-95449800-926a-11e9-949c-0f92432c41ee.png)

**Comment by achandraa** [comment]
Since from the comment it looks newer version of Microsoft Visual C++ is there while installing version 2015 and because of which the error appeared, you can try uninstalling 2017 and installing 2015 from the TensorFlow website. Let us know if that helps. Thanks!

**Comment by smbox** [comment]
I have uninstalled Visual Studio 2017 and both its rediststributables. I was then able to install the Microsoft Visual C++ 2015 Redistributable Update 3 successfully this time. However, I still have the same issue (DLL load failed). 
Is there a way to make Tensorflow more verbose, i.e. print out the DLL that failed to load? This seems to be a common issue and that would help significantly.

**Comment by achandraa** [comment]
Now, we can try with [Dependency Walker](http://www.dependencywalker.com/) to find out which DLL is causing problem. For reference check this [issue](https://github.com/tensorflow/tensorflow/issues/28848#issuecomment-495057676) and let us know if you are able to move forward. Thanks!

**Comment by smbox** [comment]
I tried dependency walker and the result looks the same as in the screenshot above that was done several days ago.

**Comment by ymodak** [comment]
TensorFlow release binaries version 1.6 and higher are prebuilt with AVX instruction sets. This means on any CPU that do not have these instruction sets either CPU or GPU version of TF will fail to load. I suspect that your CPU model does not support AVX instruction set. Can you please confirm?. Thanks!

**Comment by smbox** [comment]
Yes, I think you nailed the problem. My CPU is an Intel Core i7, but it's the first generation, from around 2011. I was hoping to use my GPU because of that. So I guess it won't work?

**Comment by ymodak** [comment]
You have couple of options;
1) The easiest way to use TF will be to switch to [google colab](https://colab.sandbox.google.com/notebooks/welcome.ipynb#recent=true). You get pre-installed stable TF version on it (currently running TF 1.14). Also you can use pip install to install any other preferred TF version if required.
It has added advantage since you can you easily switch to different hardware accelerators (cpu, gpu, tpu) as per the task. All you need is good internet connection and you are all set.
(2) You have build TF from sources by changing CPU optimization flags.

**Comment by ymodak** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
