### ISSUE TITLE
TensorFlow Lite Op Request

### ISSUE THREAD

**Issue by xuxiyang1993** [tensorflow/tensorflow#29887]
**System information**
- OS Platform and Distribution: (macOS Mojave 10.14.4)
- TensorFlow installed from: (pip3)
- TensorFlow version (or github SHA if from source): '1.13.1'

**Provide the text output from tflite_convert**

```
Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, CAST, CONCATENATION, CONV_2D, EXP, EXPAND_DIMS, FILL, GATHER, GREATER, LOGISTIC, MAX_POOL_2D, MUL, PACK, PAD, RELU, RESHAPE, RESIZE_BILINEAR, SHAPE, STRIDED_SLICE, SUB, TILE, TRANSPOSE. Here is a list of operators for which you will need custom implementations: GatherNd, NonMaxSuppressionV3, ScatterNd, Size, Where.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/toco_from_protos", line 10, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 59, in main
    app.run(main=execute, argv=[sys.argv[0]] + unparsed)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 33, in execute
    output_str = tensorflow_wrap_toco.TocoConvert(model_str, toco_str, input_str)
Exception: We are continually in the process of adding support to TensorFlow Lite for more ops. It would be helpful if you could inform us of how this conversion went by opening a github issue at https://github.com/tensorflow/tensorflow/issues/new?template=40-tflite-op-request.md
 and pasting the following:

Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, CAST, CONCATENATION, CONV_2D, EXP, EXPAND_DIMS, FILL, GATHER, GREATER, LOGISTIC, MAX_POOL_2D, MUL, PACK, PAD, RELU, RESHAPE, RESIZE_BILINEAR, SHAPE, STRIDED_SLICE, SUB, TILE, TRANSPOSE. Here is a list of operators for which you will need custom implementations: GatherNd, NonMaxSuppressionV3, ScatterNd, Size, Where.




Process finished with exit code 1

```

Also, please include a link to a GraphDef or the model if possible.

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ymodak** [comment]
Please take a look at https://www.tensorflow.org/lite/guide/faq#models_operations to know more.

**Comment by miaout17** [comment]
Could you provide more information about the model?
I saw `NonMaxSuppressionV3`, so it's likely a SSD model?
If that's the case, @achowdhery can comment more. Thanks

**Comment by xuxiyang1993** [comment]
Yes, it is a Retinanet model for object detection. It is performed on all the detections to remove the repetitious detections. Do you need any other information for the model? Thanks!
