### ISSUE TITLE
TensorflowJS cannot be installed properly

### ISSUE THREAD

**Issue by changkaizhao** [tensorflow/tensorflow#29956]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- MAC OS:
- TensorFlowJS version (1.2.1):
- Python version 3.6:

After installed `pip install tensorflowjs==1.2.1`
I use `tensorflowjs_converter --help` it gives the errors:
```
WARNING: Logging before flag parsing goes to stderr.
W0619 17:05:26.072402 140736116396928 __init__.py:309] Limited tf.compat.v2.summary API due to missing TensorBoard installation.
W0619 17:05:26.101637 140736116396928 __init__.py:336] Limited tf.summary API due to missing TensorBoard installation.
Traceback (most recent call last):
  File "~/anaconda3/lib/python3.6/site-packages/tensorflow_hub/tf_v1.py", line 30, in <module>
    from tensorflow_estimator import estimator
  File "~/anaconda3/lib/python3.6/site-packages/tensorflow_estimator/__init__.py", line 8, in <module>
    from tensorflow_estimator._api.v2 import estimator
  File "~/anaconda3/lib/python3.6/site-packages/tensorflow_estimator/_api/v2/estimator/__init__.py", line 31, in <module>
    from tensorflow_estimator.python.estimator.estimator_lib import BinaryClassHead
  File "~/anaconda3/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/__init__.py", line 25, in <module>
    import tensorflow_estimator.python.estimator.estimator_lib
  File "~/anaconda3/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator_lib.py", line 67, in <module>
    from tensorflow_estimator.python.estimator.tpu.tpu_estimator import TPUEstimator
  File "~/anaconda3/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 86, in <module>
    from tensorflow_estimator.python.estimator.tpu import _tpu_estimator_embedding
  File "~/anaconda3/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/_tpu_estimator_embedding.py", line 32, in <module>
    from tensorflow.python.tpu import feature_column_v2 as tpu_fc_v2
ImportError: cannot import name 'feature_column_v2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/anaconda3/bin/tensorflowjs_converter", line 6, in <module>
    from tensorflowjs.converters.converter import main
  File "~/anaconda3/lib/python3.6/site-packages/tensorflowjs/__init__.py", line 21, in <module>
    from tensorflowjs import converters
  File "~/anaconda3/lib/python3.6/site-packages/tensorflowjs/converters/__init__.py", line 24, in <module>
    from tensorflowjs.converters.tf_saved_model_conversion_v2 import convert_tf_saved_model
  File "~/anaconda3/lib/python3.6/site-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 38, in <module>
    import tensorflow_hub as hub
  File "~/anaconda3/lib/python3.6/site-packages/tensorflow_hub/__init__.py", line 30, in <module>
    from tensorflow_hub.estimator import LatestModuleExporter
  File "~/anaconda3/lib/python3.6/site-packages/tensorflow_hub/estimator.py", line 25, in <module>
    from tensorflow_hub import tf_utils
  File "~/anaconda3/lib/python3.6/site-packages/tensorflow_hub/tf_utils.py", line 28, in <module>
    from tensorflow_hub import tf_v1
  File "~/anaconda3/lib/python3.6/site-packages/tensorflow_hub/tf_v1.py", line 32, in <module>
    from tensorflow import add_to_collection
ImportError: cannot import name 'add_to_collection'
```

**Comment by changkaizhao** [comment]
I am so frustrated that I wasted too much time on this buggy stuff.

**Comment by changkaizhao** [comment]
After following operations :
```
$ pip uninstall tf-nightly-2.0-preview
$ pip install tensorflow==1.13.1
```
if gives the errors:
```Traceback (most recent call last):
  File "~/anaconda3/bin/tensorflowjs_converter", line 6, in <module>
    from tensorflowjs.converters.converter import main
  File "~/anaconda3/lib/python3.6/site-packages/tensorflowjs/__init__.py", line 21, in <module>
    from tensorflowjs import converters
  File "~/anaconda3/lib/python3.6/site-packages/tensorflowjs/converters/__init__.py", line 24, in <module>
    from tensorflowjs.converters.tf_saved_model_conversion_v2 import convert_tf_saved_model
  File "~/anaconda3/lib/python3.6/site-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 30, in <module>
    from tensorflow.python.framework import convert_to_constants
ImportError: cannot import name 'convert_to_constants'
```

**Comment by changkaizhao** [comment]
I think installed `tensorflow` version not match the `tensorflowjs`

**Comment by simoncozens** [comment]
I had the same issue (with tf2) - I deleted line 67 from `tensorflow_estimator/python/estimator/estimator_lib.py` and the conversion worked.

**Comment by changkaizhao** [comment]
After comparing the two branches `r1.13` and `r1.14`
I upgrade `tensorflow==1.13.1` to `tensorflow==1.14.0`
Everything works fine~~

**Comment by changkaizhao** [comment]
> I had the same issue (with tf2) - I deleted line 67 from `tensorflow_estimator/python/estimator/estimator_lib.py` and the conversion worked.

THANKS  FOR YOUR REPLY~ YOU SAVE ME~

**Comment by bubu98** [comment]
> I had the same issue (with tf2) - I deleted line 67 from `tensorflow_estimator/python/estimator/estimator_lib.py` and the conversion worked.

Works for me by commenting on line 69

```
#from tensorflow_estimator.python.estimator.tpu.tpu_estimator import TPUEstimator
```

**Comment by reuben** [comment]
This seems to be related to mixing `tensorflow` and `tf-nightly` in the same virtualenv... I started getting all kinds of bizarre errors after installing/uninstalling both packages, even though I never had them both installed at the same time. Could only fix it by wiping the virtualenv and reinstalling deps from scratch.
