### ISSUE TITLE
TensorflowJS converter cannot convert tf_saved_model to tfjs_model

### ISSUE THREAD

**Issue by changkaizhao** [tensorflow/tensorflow#29990]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MAC OS 
- TensorFlow installed from (source or binary): binray
- TensorFlow version (use command below): 1.14.0
- TensorFlowJS version: 1.2.1
- Python version: 3.6

When I using `tensorflowjs_converter` to convert a `tf_saved_model` to `tfjs_graph_model` it gives the errors as below:

```
2019-06-20 10:05:21.636174: I tensorflow/core/grappler/devices.cc:60] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0 (Note: TensorFlow was not compiled with CUDA support)
2019-06-20 10:05:21.636291: I tensorflow/core/grappler/clusters/single_machine.cc:359] Starting new session
2019-06-20 10:05:21.636529: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-06-20 10:05:21.648066: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:716] Optimization results for grappler item: graph_to_optimize
2019-06-20 10:05:21.648092: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   function_optimizer: function_optimizer did nothing. time = 0.004ms.
2019-06-20 10:05:21.648098: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   function_optimizer: function_optimizer did nothing. time = 0ms.
Traceback (most recent call last):
  File "~/anaconda3/bin/tensorflowjs_converter", line 10, in <module>
    sys.exit(main())
  File "~/anaconda3/lib/python3.6/site-packages/tensorflowjs/converters/converter.py", line 556, in main
    strip_debug_ops=FLAGS.strip_debug_ops)
  File "~/anaconda3/lib/python3.6/site-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 285, in convert_tf_saved_model
    concrete_func)
  File "~/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/convert_to_constants.py", line 203, in convert_variables_to_constants_v2
    tensor_util.make_tensor_proto(value))
  File "~/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py", line 466, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "~/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py", line 368, in _AssertCompatible
    raise TypeError("List of Tensors when single Tensor expected")
TypeError: List of Tensors when single Tensor expected
```

After debugging the source, I found that the inputs for `_AssertCompatible(values, dtype)` are: `values=Tensor("StatefulPartitionedCall_1:0", shape=(768, 1024), dtype=float32)` and `dtype=None`

The comments in the source indicate that the type of `values` is not supported!

**Comment by changkaizhao** [comment]
I located the problem in the file`convert_to_constants.py` 
```
  # Add identity node after the reference variable and get the tensor values
  # for them.
  if reference_variables:
    reference_variable_tensors = []
    with func.graph.as_default():
      for node in reference_variables:
        identity_node = array_ops.identity(
            func.graph.as_graph_element(node.name + ":0"))
        reference_variable_tensors.append(identity_node.name)

    reference_variable_values = func.prune([], reference_variable_tensors)()

    # Add values of reference variables as constant nodes.
    for node, value in zip(reference_variables, reference_variable_values):
      output_node = output_graph_def.node.add()
      dtype = attr_value_pb2.AttrValue()
      dtype.type = value.dtype.as_datatype_enum

      output_node.op = "Const"
      output_node.name = node.name
      output_node.attr["dtype"].CopyFrom(dtype)
      output_node.attr["value"].tensor.CopyFrom(
          tensor_util.make_tensor_proto(value))
      how_many_converted += 1

```
`tensor_util.make_tensor_proto` only accepts values of types (a python scalar, a python list, a
  numpy ndarray, or a numpy scalar) but this line code `output_node.attr["value"].tensor.CopyFrom(
          tensor_util.make_tensor_proto(value))` gives the value a type of `Tensor`!
How to solve this problem?

**Comment by changkaizhao** [comment]
What's the available version of `tensorflow` for `tensorflowjs` ?  
I tried `2.0`  `1.14` and `1.13` all are failed~
SO FRUSTRATED!

**Comment by changkaizhao** [comment]
***SOLUTION***   SEE ISSUE [#29956](https://github.com/tensorflow/tensorflow/issues/29956)

**Comment by changkaizhao** [comment]
Currently, **only** `tf-nightly-2.0-preview` is compatible with `tensorflowjs==1.2.1`.
if you meet the errors as in ISSUE [#29956](https://github.com/tensorflow/tensorflow/issues/29956), just fix it as it suggested.
