### ISSUE TITLE
error while converting MobileNet SSD tflite_graph.pb file to tflite format using tflite_convert 

### ISSUE THREAD

**Issue by redhood95** [tensorflow/tensorflow#30026]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): NO
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: no
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.14.0
- Python version:3.6.5
- Bazel version (if compiling from source):  None
- GCC/Compiler version (if compiling from source): 
- CUDA/cuDNN version: none 
- GPU model and memory: none

I am trying to convert a pretrained mobilenetSSD to tflite for deployment which is available in tensorflow detection model zoo.

**Code to reproduce the issue**
tflite_convert   --graph_def_file=ssd_mobilenet_v1_0.75_depth_quantized_300x300_coco14_sync_2018_07_18/tflite_graph.pb    --output_file=ssd_mobilenet_v1_0.75_depth_quantized_300x300_coco14_sync_2018_07_18/optimized_graph.lite   --input_format=TENSORFLOW_GRAPHDEF   --output_format=TFLITE   --input_shape=1,${224},${224},3   --input_array=input   --output_array=final_result   --inference_type=FLOAT   --input_data_type=FLOAT

**Other info / logs**
Traceback (most recent call last):
  File "/home/yash/anaconda3/envs/conversion/bin/tflite_convert", line 10, in <module>
    sys.exit(main())
  File "/home/yash/anaconda3/envs/conversion/lib/python3.6/site-packages/tensorflow/lite/python/tflite_convert.py", line 503, in main
    app.run(main=run_main, argv=sys.argv[:1])
  File "/home/yash/anaconda3/envs/conversion/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/yash/anaconda3/envs/conversion/lib/python3.6/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/yash/anaconda3/envs/conversion/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/home/yash/anaconda3/envs/conversion/lib/python3.6/site-packages/tensorflow/lite/python/tflite_convert.py", line 499, in run_main
    _convert_tf1_model(tflite_flags)
  File "/home/yash/anaconda3/envs/conversion/lib/python3.6/site-packages/tensorflow/lite/python/tflite_convert.py", line 193, in _convert_tf1_model
    output_data = converter.convert()
  File "/home/yash/anaconda3/envs/conversion/lib/python3.6/site-packages/tensorflow/lite/python/lite.py", line 904, in convert
    **converter_kwargs)
  File "/home/yash/anaconda3/envs/conversion/lib/python3.6/site-packages/tensorflow/lite/python/convert.py", line 373, in toco_convert_graph_def
    input_data.SerializeToString())
  File "/home/yash/anaconda3/envs/conversion/lib/python3.6/site-packages/tensorflow/lite/python/convert.py", line 172, in toco_convert_protos
    "TOCO failed. See console for info.\n%s\n%s\n" % (stdout, stderr))
tensorflow.lite.python.convert.ConverterError: TOCO failed. See console for info.
2019-06-21 03:51:18.946551: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: TFLite_Detection_PostProcess
2019-06-21 03:51:18.970221: I tensorflow/lite/toco/import_tensorflow.cc:1385] Unable to determine output type for op: TFLite_Detection_PostProcess
2019-06-21 03:51:18.994542: F tensorflow/lite/toco/tooling_util.cc:918] Check failed: GetOpWithOutput(model, output_array) Specified output array "final_result" is not produced by any op in this graph. Is it a typo? This should not happen. If you trigger this error please send a bug report (with code to reporduce this error), to the TensorFlow Lite team.
Fatal Python error: Aborted

Current thread 0x00007f9444831740 (most recent call first):
  File "/home/yash/anaconda3/envs/conversion/lib/python3.6/site-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 33 in execute
  File "/home/yash/anaconda3/envs/conversion/lib/python3.6/site-packages/absl/app.py", line 251 in _run_main
  File "/home/yash/anaconda3/envs/conversion/lib/python3.6/site-packages/absl/app.py", line 300 in run
  File "/home/yash/anaconda3/envs/conversion/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 40 in run
  File "/home/yash/anaconda3/envs/conversion/lib/python3.6/site-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 59 in main
  File "/home/yash/anaconda3/envs/conversion/bin/toco_from_protos", line 10 in <module>
Aborted (core dumped)

**Comment by gargn** [comment]
Please add the flag `--allow_custom_ops`.

**Comment by gargn** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
