### ISSUE TITLE
TypeError: Generator object is not an iterator

### ISSUE THREAD

**Issue by chinmayshah99** [tensorflow/tensorflow#30089]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 Home 64bit
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): 1.12.0
- Python version: Anaconda 3.7
- GPU model and memory: GTX 1050 2GB
Edit: With tensorflow CPU (tf version: 1.14), same issue occurs.

When I'm trying to do model.fit(), memoryerror occurs, resulting in using fit_generator. 
For fit_generator, since my input is a custom 512D embedding from a previous model, I wrote my custom generator function, but while running it, following error occurs:

```
Traceback (most recent call last):
  File "neural.py", line 244, in <module>
    model.fit_generator(mygenerator(neural_network_x_1, neural_network_x_2, neural_network_y), steps_per_epoch= 25,epochs=100)
  File "C:\Users\chinm\AppData\Local\conda\conda\envs\tensorflow_gpuenv\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\chinm\AppData\Local\conda\conda\envs\tensorflow_gpuenv\lib\site-packages\keras\engine\training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "C:\Users\chinm\AppData\Local\conda\conda\envs\tensorflow_gpuenv\lib\site-packages\keras\engine\training_generator.py", line 181, in fit_generator
    generator_output = next(output_generator)
  File "C:\Users\chinm\AppData\Local\conda\conda\envs\tensorflow_gpuenv\lib\site-packages\keras\utils\data_utils.py", line 709, in get
    six.reraise(*sys.exc_info())
  File "C:\Users\chinm\AppData\Local\conda\conda\envs\tensorflow_gpuenv\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\Users\chinm\AppData\Local\conda\conda\envs\tensorflow_gpuenv\lib\site-packages\keras\utils\data_utils.py", line 685, in get
    inputs = self.queue.get(block=True).get()
  File "C:\Users\chinm\AppData\Local\conda\conda\envs\tensorflow_gpuenv\lib\multiprocessing\pool.py", line 670, in get
    raise self._value
  File "C:\Users\chinm\AppData\Local\conda\conda\envs\tensorflow_gpuenv\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\chinm\AppData\Local\conda\conda\envs\tensorflow_gpuenv\lib\site-packages\keras\utils\data_utils.py", line 626, in next_sample
    return six.next(_SHARED_SEQUENCES[uid])
TypeError: 'mygenerator' object is not an iterator

```
The generator class mentioned below is in the order as mentioned in: https://www.tensorflow.org/api_docs/python/tf/keras/utils/Sequence

```
from tensorflow.python.keras.utils.data_utils import Sequence
class mygenerator(Sequence):
    def __init__(self, x_set_1, x_set_2, y_set, batch_size = 16):
        self.x1, self.x2, self.y = x_set_1, x_set_2, y_set
        self.batch_size = batch_size
        self.len_data = 0

    def __len__(self):
        return int(np.ceil(len(self.y) / float(self.batch_size)))

    def __getitem__(self, idx):
        batch_x1 = self.x1[idx * self.batch_size:(idx + 1) * self.batch_size]
        batch_x2 = self.x2[idx * self.batch_size:(idx + 1) * self.batch_size]
        batch_y = self.y[idx * self.batch_size:(idx + 1) * self.batch_size]

        # read your data here using the batch lists, batch_x and batch_y
        xi = [item for item in batch_x1] 
        xj = [item for item in batch_x2] 
        yi = [item for item in batch_y]
        return np.asarray([xi, xj], yi)

model.fit_generator(mygenerator(neural_network_x_1, neural_network_x_2, neural_network_y), steps_per_epoch= 25,epochs=100)

```

**Comment by ravikyram** [comment]
I am seeing model is not defined when reproducing the issue.Please provide us complete code to reproduce the issue.Thanks

**Comment by chinmayshah99** [comment]
Hi @ravikyram , here's the complete code to reproduce the issue:

```

import numpy as np
no_element = 10
x1 = np.random.rand(no_element ,512)
x2 = np.random.rand(no_element ,512)
x3 = np.random.randint(2, size=no_element)

from tensorflow.python.keras.utils.data_utils import Sequence

class mygenerator(Sequence):
    def __init__(self, x_set_1, x_set_2, y_set, batch_size = 16):
        self.x1, self.x2, self.y = x_set_1, x_set_2, y_set
        self.batch_size = batch_size
        self.len_data = 0

    def __len__(self):
        return int(np.ceil(len(self.y) / float(self.batch_size)))

    def __getitem__(self, idx):
        batch_x1 = self.x1[idx * self.batch_size:(idx + 1) * self.batch_size]
        batch_x2 = self.x2[idx * self.batch_size:(idx + 1) * self.batch_size]
        batch_y = self.y[idx * self.batch_size:(idx + 1) * self.batch_size]

        # read your data here using the batch lists, batch_x and batch_y
        xi = [item for item in batch_x1] 
        xj = [item for item in batch_x2] 
        yi = [item for item in batch_y]
        return np.asarray([xi, xj], yi)


from keras import Sequential
from keras import Input
from keras.layers import Dense, Concatenate
from keras import Model
# from keras import optimizers
from keras.optimizers import Adam

# define two sets of inputs
inputA = Input(shape=(512,))
inputB = Input(shape= (512,))

# the first branch operates on the first input
x = Dense(128, activation="relu")(inputA)
x = Model(inputs=inputA, outputs=x)

# the second branch opreates on the second input
y = Dense(128, activation="relu")(inputB)
y = Model(inputs=inputB, outputs=y)

# combine the output of the two branches
combined = Concatenate()([x.output, y.output])

# apply a FC layer and then a regression prediction on the
# combined outputs
z = Dense(16, activation="relu")(combined)
z = Dense(4, activation="relu")(combined)
z = Dense(2, activation="linear")(z)

model = Model(inputs=[x.input, y.input], outputs=z)
opt = Adam(lr=1e-3, decay=1e-3 / 200)
model.compile(loss="mean_absolute_percentage_error", optimizer=opt)


model.fit_generator(mygenerator(x1, x2, x3), steps_per_epoch= 25,epochs=100)

```

**Comment by ravikyram** [comment]
I have reproduced the issue in colab with TF version 1.12.0.Thanks

**Comment by Saduf2019** [comment]
I am facing a different issues, please find [gist here](https://colab.research.google.com/gist/Saduf2019/1fc5cd922e06200db7087126abfeb690/untitled.ipynb), the issue reported is resolved.
