### ISSUE TITLE
Tensorboard embeddings mnist example crashes

### ISSUE THREAD

**Issue by KevinWalker1000** [tensorflow/tensorflow#30115]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution Windows 10 Pro 64-bit
- TensorFlow installed from binary
- TensorFlow version: b'v1.13.1-0-g6612da8951' 1.13.1
- Python version: 3.6
- CUDA/cuDNN version: 10.0/7.6.0
- GPU model and memory: GeForce GTX 1070 8Mb

**Describe the current behavior**
When attempting to run the following example, https://keras.io/examples/tensorboard_embeddings_mnist/, I get a crash after the first epoch.

I get the following error message:

```
2019-06-25 11:33:16.177546: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at strided_slice_op.cc:308 : Not found: Resource localhost/features_embedding/class tensorflow::Var does not exist.
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda2\envs\py36new\lib\site-packages\tensorflow\python\client\session.py", line 1334, in _do_call
    return fn(*args)
  File "C:\ProgramData\Anaconda2\envs\py36new\lib\site-packages\tensorflow\python\client\session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "C:\ProgramData\Anaconda2\envs\py36new\lib\site-packages\tensorflow\python\client\session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: Resource localhost/features_embedding/class tensorflow::Var does not exist.
	 [[{{node strided_slice/_assign}}]]
	 [[{{node ReadVariableOp_1}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.2.4\helpers\pydev\pydevd.py", line 1664, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.2.4\helpers\pydev\pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.2.4\helpers\pydev\pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.2.4\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "X:/CoreTech/LTI791_FaceEncoding/Research/Python/Faces/Encoding/Scripts/MNISTExample.py", line 84, in <module>
    validation_data=(x_test, y_test))
  File "C:\ProgramData\Anaconda2\envs\py36new\lib\site-packages\tensorflow\python\keras\engine\training.py", line 880, in fit
    validation_steps=validation_steps)
  File "C:\ProgramData\Anaconda2\envs\py36new\lib\site-packages\tensorflow\python\keras\engine\training_arrays.py", line 370, in model_iteration
    callbacks.on_epoch_end(epoch, epoch_logs, mode=mode)
  File "C:\ProgramData\Anaconda2\envs\py36new\lib\site-packages\tensorflow\python\keras\callbacks.py", line 251, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "C:\ProgramData\Anaconda2\envs\py36new\lib\site-packages\tensorflow\python\keras\callbacks.py", line 1204, in on_epoch_end
    K.sess.run(self.assign_embeddings, feed_dict=feed_dict)
AttributeError: module 'tensorflow.python.keras.backend' has no attribute 'sess'
```

This was fixed using the following change set tensorflow/tensorflow@d994300

I now get the following error:

```
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.2.4\helpers\pydev\pydevd.py", line 1664, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.2.4\helpers\pydev\pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.2.4\helpers\pydev\pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.2.4\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "X:/CoreTech/LTI791_FaceEncoding/Research/Python/Faces/Encoding/Scripts/MNISTExample.py", line 84, in <module>
    validation_data=(x_test, y_test))
  File "C:\ProgramData\Anaconda2\envs\py36new\lib\site-packages\tensorflow\python\keras\engine\training.py", line 880, in fit
    validation_steps=validation_steps)
  File "C:\ProgramData\Anaconda2\envs\py36new\lib\site-packages\tensorflow\python\keras\engine\training_arrays.py", line 370, in model_iteration
    callbacks.on_epoch_end(epoch, epoch_logs, mode=mode)
  File "C:\ProgramData\Anaconda2\envs\py36new\lib\site-packages\tensorflow\python\keras\callbacks.py", line 251, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "C:\ProgramData\Anaconda2\envs\py36new\lib\site-packages\tensorflow\python\keras\callbacks.py", line 1204, in on_epoch_end
    sess.run(self.assign_embeddings, feed_dict=feed_dict)
  File "C:\ProgramData\Anaconda2\envs\py36new\lib\site-packages\tensorflow\python\client\session.py", line 929, in run
    run_metadata_ptr)
  File "C:\ProgramData\Anaconda2\envs\py36new\lib\site-packages\tensorflow\python\client\session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\ProgramData\Anaconda2\envs\py36new\lib\site-packages\tensorflow\python\client\session.py", line 1328, in _do_run
    run_metadata)
  File "C:\ProgramData\Anaconda2\envs\py36new\lib\site-packages\tensorflow\python\client\session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Resource localhost/features_embedding/class tensorflow::Var does not exist.
	 [[node strided_slice/_assign (defined at X:/CoreTech/LTI791_FaceEncoding/Research/Python/Faces/Encoding/Scripts/MNISTExample.py:84) ]]
	 [[node ReadVariableOp_1 (defined at X:/CoreTech/LTI791_FaceEncoding/Research/Python/Faces/Encoding/Scripts/MNISTExample.py:84) ]]

Caused by op 'strided_slice/_assign', defined at:
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.2.4\helpers\pydev\pydevd.py", line 1664, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.2.4\helpers\pydev\pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.2.4\helpers\pydev\pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.2.4\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "X:/CoreTech/LTI791_FaceEncoding/Research/Python/Faces/Encoding/Scripts/MNISTExample.py", line 84, in <module>
    validation_data=(x_test, y_test))
  File "C:\ProgramData\Anaconda2\envs\py36new\lib\site-packages\tensorflow\python\keras\engine\training.py", line 880, in fit
    validation_steps=validation_steps)
  File "C:\ProgramData\Anaconda2\envs\py36new\lib\site-packages\tensorflow\python\keras\engine\training_arrays.py", line 215, in model_iteration
    mode=mode)
  File "C:\ProgramData\Anaconda2\envs\py36new\lib\site-packages\tensorflow\python\keras\callbacks.py", line 106, in configure_callbacks
    callback_list.set_model(callback_model)
  File "C:\ProgramData\Anaconda2\envs\py36new\lib\site-packages\tensorflow\python\keras\callbacks.py", line 178, in set_model
    callback.set_model(model)
  File "C:\ProgramData\Anaconda2\envs\py36new\lib\site-packages\tensorflow\python\keras\callbacks.py", line 1051, in set_model
    embedding_input)
  File "C:\ProgramData\Anaconda2\envs\py36new\lib\site-packages\tensorflow\python\ops\state_ops.py", line 224, in assign
    return ref.assign(value, name=name)
  File "C:\ProgramData\Anaconda2\envs\py36new\lib\site-packages\tensorflow\python\ops\array_ops.py", line 844, in assign
    shrink_axis_mask=shrink_axis_mask)
  File "C:\ProgramData\Anaconda2\envs\py36new\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 1163, in _strided_slice_assign
    shrink_axis_mask=shrink_axis_mask))
  File "C:\ProgramData\Anaconda2\envs\py36new\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 8576, in resource_strided_slice_assign
    name=name)
  File "C:\ProgramData\Anaconda2\envs\py36new\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "C:\ProgramData\Anaconda2\envs\py36new\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\ProgramData\Anaconda2\envs\py36new\lib\site-packages\tensorflow\python\framework\ops.py", line 3300, in create_op
    op_def=op_def)
  File "C:\ProgramData\Anaconda2\envs\py36new\lib\site-packages\tensorflow\python\framework\ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

NotFoundError (see above for traceback): Resource localhost/features_embedding/class tensorflow::Var does not exist.
	 [[node strided_slice/_assign (defined at X:/CoreTech/LTI791_FaceEncoding/Research/Python/Faces/Encoding/Scripts/MNISTExample.py:84) ]]
	 [[node ReadVariableOp_1 (defined at X:/CoreTech/LTI791_FaceEncoding/Research/Python/Faces/Encoding/Scripts/MNISTExample.py:84) ]]
```

**Describe the expected behavior**
My aim is to find a working example that allows me to visualize weights/gradients etc in tensorboard. I would expect this example to run multiple epochs saving the embedding layer data to a log file for each epoch so I can visualize it using tensorboard. 

**Code to reproduce the issue**
https://keras.io/examples/tensorboard_embeddings_mnist/

plus the following fix:
tensorflow/tensorflow@d994300

**Other info / logs**
The example works fine if embeddings_freq is set to 0.

**Comment by nfelt** [comment]
cc @omalleyt12 do you have any idea what might be going awry here?

**Comment by benDavidson6** [comment]
Same in tf 1.14
```
Traceback (most recent call last):
  File "/home/ben/venvs/base/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/home/ben/venvs/base/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/ben/venvs/base/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: Resource localhost/features_embedding/N10tensorflow3VarE does not exist.
	 [[{{node strided_slice/_assign}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ben/.PyCharmCE2019.2/config/scratches/scratch_2.py", line 82, in <module>
    validation_data=(x_test, y_test))
  File "/home/ben/venvs/base/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 780, in fit
    steps_name='steps_per_epoch')
  File "/home/ben/venvs/base/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_arrays.py", line 419, in model_iteration
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/home/ben/venvs/base/lib/python3.6/site-packages/tensorflow/python/keras/callbacks.py", line 311, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/home/ben/venvs/base/lib/python3.6/site-packages/tensorflow/python/keras/callbacks_v1.py", line 446, in on_epoch_end
    sess.run(self.assign_embeddings, feed_dict=feed_dict)
  File "/home/ben/venvs/base/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/home/ben/venvs/base/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/ben/venvs/base/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/home/ben/venvs/base/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Resource localhost/features_embedding/N10tensorflow3VarE does not exist.
	 [[node strided_slice/_assign (defined at /.PyCharmCE2019.2/config/scratches/scratch_2.py:82) ]]

Original stack trace for 'strided_slice/_assign':
  File "/.PyCharmCE2019.2/config/scratches/scratch_2.py", line 82, in <module>
    validation_data=(x_test, y_test))
  File "/venvs/base/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 780, in fit
    steps_name='steps_per_epoch')
  File "/venvs/base/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_arrays.py", line 213, in model_iteration
    mode=mode)
  File "/venvs/base/lib/python3.6/site-packages/tensorflow/python/keras/callbacks.py", line 105, in configure_callbacks
    callback_list.set_model(callback_model)
  File "/venvs/base/lib/python3.6/site-packages/tensorflow/python/keras/callbacks.py", line 231, in set_model
    callback.set_model(model)
  File "/venvs/base/lib/python3.6/site-packages/tensorflow/python/keras/callbacks_v1.py", line 277, in set_model
    embedding_input)
  File "/venvs/base/lib/python3.6/site-packages/tensorflow/python/ops/state_ops.py", line 228, in assign
    return ref.assign(value, name=name)
  File "/venvs/base/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 885, in assign
    shrink_axis_mask=shrink_axis_mask)
  File "/venvs/base/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 1446, in _strided_slice_assign
    shrink_axis_mask=shrink_axis_mask))
  File "/venvs/base/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 7829, in resource_strided_slice_assign
    name=name)
  File "/venvs/base/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/venvs/base/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/venvs/base/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3616, in create_op
    op_def=op_def)
  File "/venvs/base/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()
```
```python

from __future__ import print_function

from os import makedirs
from os.path import exists, join

import tensorflow as tf
from tensorflow.keras.callbacks import TensorBoard
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Flatten
from tensorflow.keras.layers import Conv2D, MaxPooling2D
from tensorflow.keras import backend as K

import numpy as np

batch_size = 128
num_classes = 10
epochs = 12
log_dir = './logs'

if not exists(log_dir):
    makedirs(log_dir)

# input image dimensions
img_rows, img_cols = 28, 28

# the data, split between train and test sets
(x_train, y_train), (x_test, y_test) = mnist.load_data()

if K.image_data_format() == 'channels_first':
    x_train = x_train.reshape(x_train.shape[0], 1, img_rows, img_cols)
    x_test = x_test.reshape(x_test.shape[0], 1, img_rows, img_cols)
    input_shape = (1, img_rows, img_cols)
else:
    x_train = x_train.reshape(x_train.shape[0], img_rows, img_cols, 1)
    x_test = x_test.reshape(x_test.shape[0], img_rows, img_cols, 1)
    input_shape = (img_rows, img_cols, 1)

x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train /= 255
x_test /= 255
print('x_train shape:', x_train.shape)
print(x_train.shape[0], 'train samples')
print(x_test.shape[0], 'test samples')

# save class labels to disk to color data points in TensorBoard accordingly
with open(join(log_dir, 'metadata.tsv'), 'w') as f:
    np.savetxt(f, y_test)

# convert class vectors to binary class matrices
y_train = tf.keras.utils.to_categorical(y_train, num_classes)
y_test = tf.keras.utils.to_categorical(y_test, num_classes)

tensorboard = TensorBoard(batch_size=batch_size,
                          embeddings_freq=1,
                          embeddings_layer_names=['features'],
                          embeddings_metadata='metadata.tsv',
                          embeddings_data=x_test)

model = Sequential()
model.add(Conv2D(32, kernel_size=(3, 3),
                 activation='relu',
                 input_shape=input_shape))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(128, activation='relu', name='features'))
model.add(Dropout(0.5))
model.add(Dense(num_classes, activation='softmax'))

model.compile(loss=tf.keras.losses.categorical_crossentropy,
              optimizer=tf.keras.optimizers.Adadelta(),
              metrics=['accuracy'])

model.fit(x_train, y_train,
          batch_size=batch_size,
          callbacks=[tensorboard],
          epochs=epochs,
          verbose=1,
          validation_data=(x_test, y_test))
score = model.evaluate(x_test, y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])
```

**Comment by jingwb222** [comment]
Any updates or timeline for fix on this issue?

**Comment by gmartin001** [comment]
I'm experiencing the same problem. The Keras-only version works fine. However, the tensorflow.keras version does not. I've tensorflow versions 1.14.0 and 1.15.0 and they have the same problem.
Your help is greatly appreciated.

**Comment by suziW** [comment]
I have the same problem. Any solution?

**Comment by gmartin001** [comment]
No fix.
Needs to be fixed in Tensorboard.

A Hui Hou,
Greg Martin
gregory.james.martin@gmail.com

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.

**Comment by gmartin001** [comment]
I upgraded to TensorFlow 2.2.
No more issues.
Thanks!

A Hui Hou,
Greg Martin
gregory.james.martin@gmail.com
