### ISSUE TITLE
Variable sized input doesn't work with dilated convolutional layer

### ISSUE THREAD

**Issue by ellonde** [tensorflow/tensorflow#30167]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): **No**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Linux Ubuntu 18.10**
- TensorFlow installed from (source or binary): **binary**
- TensorFlow version (use command below): **v2.0.0-beta0-16-g1d91213fe7** -  **2.0.0-beta1**
- Python version: **3.6**
- CUDA/cuDNN version: **CPU**
- GPU model and memory: **CPU**

**Describe the current behavior**
I have variable sized axis on the input for a dilated conv layer which fails when inputting the second batch(data is padded batch wise). I have tried additional padding both for % dilation_rate == 0 and % 2 == 0 without luck. This allows for some of the layers to work but not all, so it might be a simple calculation I need to figure out what additional padding to use but I cant figure out what this is.

**Describe the expected behavior**
When running without dilation im able to handle the variable sized input. Also the fact that the conv layers with dilation can handle any input as long as its the first I would expect that no additional padding would be needed.

**Code to reproduce the issue**
```
import tensorflow as tf
bs = 5
text_len_1 = 772
text_len_2 = 741
embed_size = 300
in_channels = 1

test_in_1 = tf.random.normal((bs, text_len_1, embed_size, in_channels))
test_in_2 = tf.random.normal((bs, text_len_2, embed_size, in_channels))


dilated_convs = [tf.keras.layers.Conv2D(filters=10, kernel_size=(2, embed_size),
                                                    dilation_rate=(dilation, 1),
                                                    padding='valid')
                             for dilation in range(2, 23)]

for conv in dilated_convs:
    res = conv(test_in_1)

for conv in dilated_convs:
    # Fails here, regardless of test_in_1 or 2 is called first
    res = conv(test_in_2) 
```

**Other info / logs**
```
2019-06-25 13:50:33.329503: W tensorflow/core/framework/op_kernel.cc:1546] OP_REQUIRES failed at spacetobatch_op.cc:219 : Invalid argument: padded_shape[0]=741 is not divisible by block_shape[0]=2
Traceback (most recent call last):
  File "/home/name/anaconda3/envs/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-59b677f0b758>", line 1, in <module>
    runfile('/home/name/.PyCharm2019.1/config/scratches/dilated_conv_test.py', wdir='/home/name/.PyCharm2019.1/config/scratches')
  File "/snap/pycharm-professional/136/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/snap/pycharm-professional/136/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/name/.PyCharm2019.1/config/scratches/dilated_conv_test.py", line 22, in <module>
    res = conv(test_in_2)
  File "/home/name/anaconda3/envs/3.6/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 712, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/home/name/anaconda3/envs/3.6/lib/python3.6/site-packages/tensorflow/python/keras/layers/convolutional.py", line 196, in call
    outputs = self._convolution_op(inputs, self.kernel)
  File "/home/name/anaconda3/envs/3.6/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 1078, in __call__
    return self.conv_op(inp, filter)
  File "/home/name/anaconda3/envs/3.6/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 634, in __call__
    return self.call(inp, filter)
  File "/home/name/anaconda3/envs/3.6/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 617, in _with_space_to_batch_call
    input=inp, block_shape=dilation_rate, paddings=paddings)
  File "/home/name/anaconda3/envs/3.6/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 9246, in space_to_batch_nd
    _six.raise_from(_core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: padded_shape[0]=741 is not divisible by block_shape[0]=2 [Op:SpaceToBatchND]
```

**Comment by ravikyram** [comment]
I have reproduced the issue in Colab using TF 2.0.0-beta1. Thanks!

**Comment by ellonde** [comment]
Awesome, hope you can help :)

**Comment by ellonde** [comment]
Any updates on this?

**Comment by tanzhenyu** [comment]
The issue here is your kernels is size of (2, embed_size), while the input size is (...,...,embed_size,...),
so it is not feasible to dilate the input.
Set your kernel to a smaller size would fix it.

**Comment by ellonde** [comment]
How come its working for the first run then? And isn't it the kernel thats dialated?
Also the dilation_rate=(dilation, 1) so it should only dialate in the text_len dimension?

**Comment by JinLi711** [comment]
I'm having the same issue in Tensorflow 2.0.0-rc0, and it doesn't seem to have anything to do with the kernel size.

`
from tensorflow.keras import layers
convLayer = layers.Conv2D(
    4, 
    (2,2),
    data_format='channels_last',
    padding='valid',
    dilation_rate=3)
`

Running:

`
convLayer(np.random.random((3,6,6, 12)))
`
works fine.

But if I run this right after:

`
convLayer(np.random.random((3,7,7, 12)))
`

I receive the error message:

`
InvalidArgumentError: padded_shape[0]=7 is not divisible by block_shape[0]=3 [Op:SpaceToBatchND] 
`


Changing the kernel size will not remove the error. Is there any possible way of allowing dilations with various input sizes without having to pad the inputs?

**Comment by yuanyelele** [comment]
I'm still having this issue on tensorflow 2.2.0:

```
import tensorflow as tf

model = tf.keras.layers.Conv2D(filters=8, kernel_size=3, dilation_rate=3)

x1 = tf.ones((1, 12, 16, 1))
x2 = tf.ones((1, 13, 16, 1))

print(model(x1).shape)
print(model(x2).shape)
print(model(x1).shape)
```

Error logs:
```
(1, 6, 10, 8)
(1, 7, 10, 8)
2021-11-23 15:07:40.114251: W tensorflow/core/framework/op_kernel.cc:1753] OP_REQUIRES failed at spacetobatch_op.cc:219 : Invalid argument: padded_shape[0]=14 is not divisible by block_shape[0]=3
Traceback (most recent call last):
  File "bug.py", line 10, in <module>
    print(model(x1).shape)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 968, in __call__
    outputs = self.call(cast_inputs, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/layers/convolutional.py", line 207, in call
    outputs = self._convolution_op(inputs, self.kernel)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/nn_ops.py", line 1106, in __call__
    return self.conv_op(inp, filter)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/nn_ops.py", line 638, in __call__
    return self.call(inp, filter)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/nn_ops.py", line 621, in _with_space_to_batch_call
    input=inp, block_shape=dilation_rate, paddings=paddings)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 9491, in space_to_batch_nd
    _ops.raise_from_not_ok_status(e, name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 6653, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: padded_shape[0]=14 is not divisible by block_shape[0]=3 [Op:SpaceToBatchND]
```
