### ISSUE TITLE
Internal error has occurred when executing Firebase ML tasks fails on tensor allocation

### ISSUE THREAD

**Issue by thomas-coldwell** [tensorflow/tensorflow#30187]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Same error across OnePlus 6 (28) and Sony Xperia (21)
- TensorFlow installed from (source or binary): MLKit for Firebase 
- TensorFlow version (use command below): 'com.google.firebase:firebase-ml-model-interpreter:20.0.0'

Hi there folks, I've been setting up a Firebase MLKit project on Android to perform just simple image classification using a mobilenet model. I have been following the official guide given [here](https://firebase.google.com/docs/ml-kit/android/use-custom-models) for using a custom TF lite model which I have both locally in the android assets folder of my project and also hosted on a test firebase app as 'mobilenet'. The code gets a bitmap from the camera intent and then passes that to the run inference method where I have setup everything as per the guide. However, when it finally begins to run inference it throws an internal firebase ml error as well as some other bits in the stack trace.

The expected behaviour would be that it does indeed run the inference method and successfully prints a joyous "IT WORKED!!!". 

Here is my main activity kotilin file:
`package com.example.tflite

import android.content.Intent
import android.graphics.Bitmap
import android.graphics.Color
import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import android.provider.MediaStore
import android.util.Log
import android.view.View
import android.widget.ImageView
import android.widget.TextView
import android.widget.Toast
import com.google.firebase.ml.common.FirebaseMLException
import com.google.firebase.ml.common.modeldownload.FirebaseLocalModel
import com.google.firebase.ml.common.modeldownload.FirebaseModelDownloadConditions
import com.google.firebase.ml.common.modeldownload.FirebaseModelManager
import com.google.firebase.ml.common.modeldownload.FirebaseRemoteModel
import com.google.firebase.ml.custom.*

class MainActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
    }

    fun onPressAddImage(view: View) {
        // Dispatch an intent to the media store of the device to capture
        // an image with the requestCode id '1'
        Intent(MediaStore.ACTION_IMAGE_CAPTURE).also { takePictureIntent ->
            takePictureIntent.resolveActivity(packageManager)?.also {
                startActivityForResult(takePictureIntent, 1)
            }
        }
    }

    override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
        // Override the MainActivity function to check when a result is returned
        // from any intent - if the requestCode matches then draw the resulting
        // bitmap to the image view
        if (requestCode == 1 && resultCode == RESULT_OK) {
            val imageBitmap = data?.extras?.get("data") as Bitmap
            val imageView = findViewById<ImageView>(R.id.imageResult)
            imageView.setImageBitmap(imageBitmap)
            // Pass the bitmap result to the inference method
            runInference(imageBitmap)
        }
    }

    private fun runInference(bitmap: Bitmap) {
        // Scale the bitmap to the input size of the interpreter
        val scaledBitmap = Bitmap.createScaledBitmap(bitmap, 224, 224, true)
        // Create the input tensor of the image for the network
        val batchNum = 0
        val input = Array(1) { Array(224) { Array(224) { FloatArray(3) } } }
        for (x in 0..223) {
            for (y in 0..223) {
                val pixel = scaledBitmap.getPixel(x, y)
                // Normalize channel values to [-1.0, 1.0]. This requirement varies by
                // model. For example, some models might require values to be normalized
                // to the range [0.0, 1.0] instead.
                input[batchNum][x][y][0] = ((Color.red(pixel) - 127) / 255.0f)
                input[batchNum][x][y][1] = ((Color.green(pixel) - 127) / 255.0f)
                input[batchNum][x][y][2] = ((Color.blue(pixel) - 127) / 255.0f)
            }
        }
        // Define the Model download options before we attempt to e.g. that the device is charging and idle
        val conditionsBuilder = FirebaseModelDownloadConditions.Builder().requireWifi()
        val conditions = conditionsBuilder.build()
        // Build a remote model object by specifying the name you assigned the model
        // when you uploaded it in the Firebase console.
        val cloudSource = FirebaseRemoteModel.Builder("mobilenet")
            .enableModelUpdates(true)
            .setInitialDownloadConditions(conditions)
            .setUpdatesDownloadConditions(conditions)
            .build()

        // Register the local model too as a fall back in case the latest cannot be registered from Firebase
        val localSource = FirebaseLocalModel.Builder("mobilenet") 
            .setAssetFilePath("mobilenet_float_v2_1.0_299.tflite")
            .build()

        val manager = FirebaseModelManager.getInstance()
        manager.registerLocalModel(localSource)
        manager.registerRemoteModel(cloudSource)

        // Create the interpreter
        val options = FirebaseModelOptions.Builder()
            .setRemoteModelName("mobilenet")
            .setLocalModelName("mobilenet")
            .build()

        val interpreter = FirebaseModelInterpreter.getInstance(options)

        val textView = findViewById<TextView>(R.id.textView).apply {
            text = "loaded"
        }

        manager.downloadRemoteModelIfNeeded(cloudSource)
            .addOnCompleteListener { task ->
                if (task.isSuccessful) {
                    Toast.makeText(
                        this,
                        "Download remote AutoML model success.",
                        Toast.LENGTH_SHORT
                    )
                        .show()
                } else {
                    val downloadingError =
                        "Error downloading remote model."
                    Toast.makeText(this, downloadingError, Toast.LENGTH_SHORT).show()
                }
            }
        // Set the inputs and outputs of the interpreter
        // Set the input and output options of the model
        val interpreterOpts = FirebaseModelInputOutputOptions.Builder()
            .setInputFormat(0, FirebaseModelDataType.FLOAT32, intArrayOf(1, 224, 224, 3))
            .setOutputFormat(0, FirebaseModelDataType.FLOAT32, intArrayOf(1, 1001))
            .build()
        // Add the input to the interpreter and run inference
        val inputs = FirebaseModelInputs.Builder()
            .add(input) // add() as many input arrays as your model requires
            .build()
        interpreter!!.run(inputs, interpreterOpts)
            .addOnSuccessListener { result ->
                val output = result.getOutput<Array<IntArray>>(0)
                val probabilities = output[0]
                val textView = findViewById<TextView>(R.id.textView).apply {
                    text = "IT WORKED!!!"
                }

            }
            .addOnFailureListener { e ->
                Log.e("TFLite", "Failed: ${e.message}")
                e.printStackTrace()
            }
    }
}
`

And here is the logcat output from android studio:

`E/TFLite: Failed: Internal error has occurred when executing Firebase ML tasks
W/System.err: com.google.firebase.ml.common.FirebaseMLException: Internal error has occurred when executing Firebase ML tasks
        at com.google.android.gms.internal.firebase_ml.zznn.zza(Unknown Source:36)
        at com.google.android.gms.internal.firebase_ml.zznq.run(Unknown Source:2)
W/System.err:     at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.google.android.gms.internal.firebase_ml.zzf.dispatchMessage(Unknown Source:6)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
    Caused by: java.lang.IllegalStateException: Internal error: Unexpected failure when preparing tensor allocations: Invalid begin and size.Node number 0 (SLICE) failed to prepare.
        at org.tensorflow.lite.NativeInterpreterWrapper.allocateTensors(Native Method)
        at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:136)
        at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:250)
        at com.google.android.gms.internal.firebase_ml.zzpz.runForMultipleInputsOutputs(Unknown Source:4)
        at com.google.android.gms.internal.firebase_ml.zzpr.zza(Unknown Source:85)
        at com.google.android.gms.internal.firebase_ml.zzpr.zza(Unknown Source:125)
        at com.google.android.gms.internal.firebase_ml.zznt.call(Unknown Source:4)
        at com.google.android.gms.internal.firebase_ml.zznn.zza(Unknown Source:30)
    	... 6 more
`

In particular it seems to be failing when allocating the tensors and so could possibly be a memory allocation issue, but not entirely sure:

`Caused by: java.lang.IllegalStateException: Internal error: Unexpected failure when preparing tensor allocations: Invalid begin and size.Node number 0 (SLICE) failed to prepare.`

Any help on how to get around this issue would be great and I can't simply use the prebuilt APIs as this is a test for building a custom semantic segmentation model on.

**Comment by thomas-coldwell** [comment]
Issue fixed now - I had set the wrong input size of the model (should have been 299 *299) but was receiving 224 * 224 - could a better exception thrown to check that they are indeed the same corresponding size rather than just it being an internal error at the allocation stage?
