### ISSUE TITLE
Cannot Run Official TF2.0 Example in Official TF2.0 Docker Container

### ISSUE THREAD

**Issue by leimao** [tensorflow/tensorflow#30207]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 18.04 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Docker container tensorflow/tensorflow:2.0.0b1-gpu-py3
- TensorFlow version (use command below): 2.0.0-beta1
- Python version: 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: RTX 2080 Ti

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Running the the official example https://www.tensorflow.org/beta/tutorials/quickstart/advanced in the official container tensorflow/tensorflow:2.0.0b1-gpu-py3 got the following error:

```
> python advanced.py 
2019-06-27 17:09:34.195179: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcuda.so.1
2019-06-27 17:09:34.231111: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-06-27 17:09:34.231786: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.635
pciBusID: 0000:01:00.0
2019-06-27 17:09:34.232026: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.0
2019-06-27 17:09:34.232777: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10.0
2019-06-27 17:09:34.233391: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcufft.so.10.0
2019-06-27 17:09:34.233576: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcurand.so.10.0
2019-06-27 17:09:34.234366: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusolver.so.10.0
2019-06-27 17:09:34.235052: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusparse.so.10.0
2019-06-27 17:09:34.236947: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2019-06-27 17:09:34.237053: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-06-27 17:09:34.237643: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-06-27 17:09:34.238201: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1763] Adding visible gpu devices: 0
2019-06-27 17:09:34.238443: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-06-27 17:09:34.323017: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-06-27 17:09:34.324202: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x39cfd60 executing computations on platform CUDA. Devices:
2019-06-27 17:09:34.324217: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): GeForce RTX 2080 Ti, Compute Capability 7.5
2019-06-27 17:09:34.342363: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3600000000 Hz
2019-06-27 17:09:34.343364: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x3d629c0 executing computations on platform Host. Devices:
2019-06-27 17:09:34.343375: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
2019-06-27 17:09:34.343534: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-06-27 17:09:34.344103: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.635
pciBusID: 0000:01:00.0
2019-06-27 17:09:34.344121: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.0
2019-06-27 17:09:34.344128: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10.0
2019-06-27 17:09:34.344135: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcufft.so.10.0
2019-06-27 17:09:34.344141: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcurand.so.10.0
2019-06-27 17:09:34.344147: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusolver.so.10.0
2019-06-27 17:09:34.344153: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusparse.so.10.0
2019-06-27 17:09:34.344160: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2019-06-27 17:09:34.344188: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-06-27 17:09:34.344698: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-06-27 17:09:34.345203: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1763] Adding visible gpu devices: 0
2019-06-27 17:09:34.345217: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.0
2019-06-27 17:09:34.345897: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-06-27 17:09:34.345905: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1187]      0 
2019-06-27 17:09:34.345910: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 0:   N 
2019-06-27 17:09:34.346029: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-06-27 17:09:34.346619: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-06-27 17:09:34.347293: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7784 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:01:00.0, compute capability: 7.5)
2019-06-27 17:09:35.539500: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10.0
2019-06-27 17:09:35.696347: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2019-06-27 17:09:36.203198: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-06-27 17:09:36.209845: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-06-27 17:09:36.209897: W tensorflow/core/common_runtime/base_collective_executor.cc:216] BaseCollectiveExecutor::StartAbort Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node my_model/conv2d/Conv2D}}]]
	 [[my_model/dense_1/BiasAdd/_6]]
2019-06-27 17:09:36.209959: W tensorflow/core/common_runtime/base_collective_executor.cc:216] BaseCollectiveExecutor::StartAbort Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node my_model/conv2d/Conv2D}}]]
Traceback (most recent call last):
  File "advanced.py", line 84, in <module>
    train_step(images, labels)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 428, in __call__
    return self._stateless_fn(*args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 1335, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 589, in _filtered_call
    (t for t in nest.flatten((args, kwargs), expand_composites=True)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 671, in _call_flat
    outputs = self._inference_function.call(ctx, args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 445, in call
    ctx=ctx)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/execute.py", line 67, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node my_model/conv2d/Conv2D (defined at advanced.py:36) ]]
  (1) Unknown:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node my_model/conv2d/Conv2D (defined at advanced.py:36) ]]
	 [[my_model/dense_1/BiasAdd/_6]]
0 successful operations.
0 derived errors ignored. [Op:__inference_train_step_848]

Errors may have originated from an input operation.
Input Source operations connected to node my_model/conv2d/Conv2D:
 images (defined at advanced.py:84)

Input Source operations connected to node my_model/conv2d/Conv2D:
 images (defined at advanced.py:84)

Function call stack:
train_step -> train_step

```

**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by gadagashwini** [comment]
@leimao Just to verify, your CUDA version is 10.0 and cuDNN version is 7. Thanks!

**Comment by leimao** [comment]
Note that I was using your official container. My local environment is CUDA 10.1 and I did not install cuDNN.

**Comment by gadagashwini** [comment]
Looks like similar issue [#29632](https://github.com/tensorflow/tensorflow/issues/29632). Thanks

**Comment by angersson** [comment]
@ymodak Per #29632, this does not look like an issue directly related to the Dockerfiles.

**Comment by leimao** [comment]
Is this problem related? 
https://superuser.com/questions/1417842/tensorflow-gpu-was-working-but-is-not-working-anymore-error-failed-to-get-convo#new-answer

**Comment by ymodak** [comment]
Have you tried setting [Limiting GPU memory growth](https://www.tensorflow.org/beta/guide/using_gpu#limiting_gpu_memory_growth) option?
[tf.config.experimental.set_memory_growth](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/config/experimental/set_memory_growth)

**Comment by leimao** [comment]
I used some magic code which some other people have mentioned:
```
from tensorflow.compat.v1 import ConfigProto
from tensorflow.compat.v1 import InteractiveSession
config = ConfigProto()
config.gpu_options.allow_growth = True
session = InteractiveSession(config=config)
```
Somehow it worked and the code looks similar to yours. However I don't like the code since it does not make sense to me and there is session in the code. (TF 2.0 has no sessions!) I have a very small model (3 layers of conv) and running on 2080 TI, I don't think GPU memory is an issue here.

**Comment by leimao** [comment]
Can you please justify why I should use the above code (either yours or the ones I mentioned)?

**Comment by leimao** [comment]
This cuDNN open problem seems to be universal for both TF 1.x and 2.0.

**Comment by sanjoy** [comment]
Looks like a duplicate https://github.com/tensorflow/tensorflow/issues/24496.

Closing this issue for now, let's use https://github.com/tensorflow/tensorflow/issues/24496 as the canonical issue for this problem.  Please reopen if you don't think this is the same as https://github.com/tensorflow/tensorflow/issues/24496.
