### ISSUE TITLE
Unable to import  tensorflow

### ISSUE THREAD

**Issue by NUV13102001** [tensorflow/tensorflow#30266]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 x64 Up to date
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary I think
- TensorFlow version: r1.14
- Python version: 3.6.5
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.1/7.6.1
- GPU model and memory: GTX 1060 6GB

>>> import tensorflow as tf
Traceback (most recent call last):
  File "C:\Users\aanan\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\platform\self_check.py", line 75, in preload_check
    ctypes.WinDLL(build_info.cudart_dll_name)
  File "C:\Users\aanan\AppData\Local\Programs\Python\Python36\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\aanan\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\aanan\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\aanan\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 30, in <module>
    self_check.preload_check()
  File "C:\Users\aanan\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\platform\self_check.py", line 82, in preload_check
    % (build_info.cudart_dll_name, build_info.cuda_version_number))
ImportError: Could not find 'cudart64_100.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Download and install CUDA 10.0 from this URL: https://developer.nvidia.com/cuda-90-download-archive
>>>

Steps I followed. I'm new to Python commands but I should be able to follow.
https://github.com/jvishnuvardhan/Installing-TensorFlow-GPU-on-Windows-10-TF1.12

Should I remove 10.1, or is a parallel installation okay? Additionally, after reading the code, it seems there is a simple missing file or two that is causing this issue. Is my diagnosis correct? If not, please guide. My gratitude in advance.

PS. It appears to me that CUDA 10.0's absence is creating this entire mess. I shall install and report.

PSS. I cannot remove 10.1 for the following reason:
NVIDIA® GPU drivers —CUDA 10.0 requires 410.x or higher. CUDA® Toolkit —TensorFlow supports CUDA 10.0 **(TensorFlow >= 1._13_.0)** CUPTI ships with the CUDA Toolkit. cuDNN SDK **(>= 7.4.1)**

**Comment by NUV13102001** [comment]
I have resolved that error simply by installing CUDA 10.0 alongside 10.1, this solves both the requirements of Tensorflow. Now I am unable to test tensorflow with "import tensorflow as tf. Following is the result of my endeavour.

 C:\Users\aanan>python
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> hello=tf.constant(‘Hello World!’)
  File "<stdin>", line 1
    hello=tf.constant(‘Hello World!’)
                           ^
SyntaxError: invalid character in identifier
>>> ^Z


C:\Users\aanan>python

**Comment by NUV13102001** [comment]
Double quotes solved the problem. LOL
