### ISSUE TITLE
tf.nn.depthwise_conv2d does not preserve number of channels

### ISSUE THREAD

**Issue by adrianstaniec** [tensorflow/tensorflow#30317]
edit: _**you can skip reading this post, go to the next one directly**_

**System information**

- OS Platform and Distribution: Linux Ubuntu 18.04
- TensorFlow installed from: pip
- TensorFlow version (use command below): 1.13.1
- Python version: 1.13.1
- CUDA/cuDNN version: 10
- GPU model and memory: RTX 2080 Ti

**Describe the current behavior**
if I  look at the tensor before and after the depthwise_conv2d:
```
ic| x: <tf.Tensor 'fusion/upsample/transpose_1:0' shape=(?, 128, ?, ?) dtype=float32>
ic| x: <tf.Tensor 'fusion/dwconv1/BatchToSpaceND:0' shape=(?, ?, ?, ?) dtype=float32>
```

**Describe the expected behavior**
if I  look at the tensor before and after the depthwise_conv2d the channel number should be preserved, and look something like this:
```
ic| x: <tf.Tensor 'fusion/upsample/transpose_1:0' shape=(?, 128, ?, ?) dtype=float32>
ic| x: <tf.Tensor 'fusion/transpose_1:0' shape=(?, 128, ?, ?) dtype=float32>
```

so IMO depthwise_conv2d with dilations  and NCHW it's loosing the information about number of channels 

**Code to reproduce the issue**

because tf.layers.depthwise_conv2d is not implemented, I implemented this:

```
def _depthwise_conv2d(self, tensor, kernel_size, strides, rate=[1, 1], name='dwconv'):
    """Problem: doesn't support channel first + dilations"""
    c = self._n_channels(tensor)
    filter_shape = [kernel_size[0], kernel_size[1], c, 1]
    filter = tf.get_variable(name + "/filter", shape=filter_shape, dtype=tf.float32)
    strides = [1, 1, strides[0], strides[1]]
    tensor = tf.nn.depthwise_conv2d(tensor, filter, strides, padding='SAME',
                                    rate=rate, name=name, data_format='NCHW')
    return tensor
```
this works:
```
x = self._depthwise_conv2d(x, (3, 3), (1, 1), name='dwconv2')
```
but this does not:
(the difference is dilations or specifically dilations + NCHW data format)
```
x = self._depthwise_conv2d(x, (3, 3), (1, 1), [4, 4], name='dwconv1')
```

is gives following error on the batch_norm which follows the depthwise_conv2d
```
    x = tf.layers.batch_normalization(x, self.caxis, training=self.training)
  File "~/.local/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "~/.local/lib/python3.6/site-packages/tensorflow/python/layers/normalization.py", line 313, in batch_normalization
    return layer.apply(inputs, training=training)
  File "~/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1227, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "~/.local/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 530, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "~/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 538, in __call__
    self._maybe_build(inputs)
  File "~/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1603, in _maybe_build
    self.build(input_shapes)
  File "~/.local/lib/python3.6/site-packages/tensorflow/python/keras/layers/normalization.py", line 306, in build
    input_shape)
ValueError: ('Input has undefined `axis` dimension. Input shape: ', TensorShape([Dimension(None), Dimension(None), Dimension(None), Dimension(None)]))
```

**Comment by ravikyram** [comment]
Looks like the code is incomplete.Can you please provide full code snippet to reproduce it on our environment.Thanks!

**Comment by adrianstaniec** [comment]
ok, I came up with this minimal example:
```
import tensorflow as tf
from icecream import ic

ic(tf.__version__)

# channel last - OK - as expected
nhwc_tensor = tf.placeholder(tf.float32, (None, None, None, 3))
c = nhwc_tensor.get_shape().as_list()[-1]
filter_shape = [3, 3, c, 1]
filter = tf.get_variable("filter", shape=filter_shape, dtype=tf.float32)
strides = [1, 1, 1, 1]
rate = 4
ic(nhwc_tensor)
nhwc_tensor = tf.nn.depthwise_conv2d(nhwc_tensor, filter, strides, "SAME", [rate, rate], "ok_dwconv", "NHWC")
ic(nhwc_tensor)
nhwc_tensor = tf.layers.batch_normalization(nhwc_tensor, name='after_ok')

# channel first - BUG
nchw_tensor = tf.placeholder(tf.float32, (None, 3, None, None))
c = nchw_tensor.get_shape().as_list()[1]
filter_shape = [3, 3, c, 1]
filter2 = tf.get_variable("filter2", shape=filter_shape, dtype=tf.float32)
strides = [1, 1, 1, 1]
rate = 4
ic(nchw_tensor)
nchw_tensor = tf.nn.depthwise_conv2d(nchw_tensor, filter2, strides, "SAME", [rate, rate], "buggy_dwconv", "NCHW")
ic(nchw_tensor)
nchw_tensor = tf.layers.batch_normalization(nchw_tensor, name='after_bug')

```
it turns out that another necessary ingredient for the bug to occur is `None` for height and width

**Comment by adrianstaniec** [comment]
output of the code above on my machine:

```
ic| tf.__version__: '1.13.1'
WARNING:tensorflow:From /data/users/adrian.staniec/.local/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops)
is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
ic| nhwc_tensor: <tf.Tensor 'Placeholder:0' shape=(?, ?, ?, 3) dtype=float32>
ic| nhwc_tensor: <tf.Tensor 'ok_dwconv/BatchToSpaceND:0' shape=(?, ?, ?, 3) dtype=float32>
WARNING:tensorflow:From depthwise.py:16: batch_normalization (from tensorflow.python.layers.normalization) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.batch_normalization instead.
ic| nchw_tesnor: <tf.Tensor 'Placeholder_1:0' shape=(?, 3, ?, ?) dtype=float32>
ic| nchw_tesnor: <tf.Tensor 'buggy_dwconv/BatchToSpaceND:0' shape=(?, ?, ?, ?) dtype=float32>
Traceback (most recent call last):
  File "depthwise.py", line 28, in <module>
    nchw_tesnor = tf.layers.batch_normalization(nchw_tesnor, name='after_bug')
  File "/data/users/adrian.staniec/.local/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/data/users/adrian.staniec/.local/lib/python3.6/site-packages/tensorflow/python/layers/normalization.py", line 313, in batch_normalization
    return layer.apply(inputs, training=training)
  File "/data/users/adrian.staniec/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1227, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "/data/users/adrian.staniec/.local/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 530, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "/data/users/adrian.staniec/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 538, in __call__
    self._maybe_build(inputs)
  File "/data/users/adrian.staniec/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1603, in _maybe_build
    self.build(input_shapes)
  File "/data/users/adrian.staniec/.local/lib/python3.6/site-packages/tensorflow/python/keras/layers/normalization.py", line 306, in build
    input_shape)
ValueError: ('Input has undefined `axis` dimension. Input shape: ', TensorShape([Dimension(None), Dimension(None), Dimension(None), Dimension(None)]))
```

**Comment by ravikyram** [comment]
I have tried on colab with TF 1.13.1-version with GPU and was able to reproduce the issue.Thanks!

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
