### ISSUE TITLE
convert_to_records.py has maybe_download and other functions that are not found.

### ISSUE THREAD

**Issue by jackywang529** [tensorflow/tensorflow#3039]
When I ran convert_to_records.py without changing the file, it would complain maybe_download and other functions that are not found. If you look at the input_data that was imported, it doesn't include the maybe_download as well even with recursive imports. 

When I fixed that by copying and pasting from the mnist/convolution.py the download and extraction of the images and label, I ran the fully_connected_reader.py, then it would complain:
W tensorflow/core/framework/op_kernel.cc:909] Invalid argument: Shape mismatch in tuple component 0. Expected [784], got [3136]
Traceback (most recent call last):
  File "fully_connected_reader.py", line 203, in <module>
    tf.app.run()
  File "/Users/user/anaconda/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "fully_connected_reader.py", line 199, in main
    run_training()
  File "fully_connected_reader.py", line 194, in run_training
    coord.join(threads)
  File "/Users/user/anaconda/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/training/coordinator.py", line 322, in join
    six.reraise(*self._exc_info_to_raise)
  File "/Users/user/anaconda/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/training/queue_runner.py", line 185, in _run
    sess.run(enqueue_op)
  File "/Users/user/anaconda/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 372, in run
    run_metadata_ptr)
  File "/Users/user/anaconda/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 636, in _run
    feed_dict_string, options, run_metadata)
  File "/Users/user/anaconda/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 708, in _do_run
    target_list, options, run_metadata)
  File "/Users/user/anaconda/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 728, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors.InvalidArgumentError: Shape mismatch in tuple component 0. Expected [784], got [3136]
     [[Node: input/shuffle_batch/random_shuffle_queue_enqueue = QueueEnqueue[Tcomponents=[DT_FLOAT, DT_INT32], _class=["loc:@input/shuffle_batch/random_shuffle_queue"], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](input/shuffle_batch/random_shuffle_queue, input/sub, input/Cast_1)]]
Caused by op u'input/shuffle_batch/random_shuffle_queue_enqueue', defined at:
  File "fully_connected_reader.py", line 203, in <module>
    tf.app.run()
  File "/Users/user/anaconda/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "fully_connected_reader.py", line 199, in main
    run_training()
  File "fully_connected_reader.py", line 140, in run_training
    num_epochs=FLAGS.num_epochs)
  File "fully_connected_reader.py", line 126, in inputs
    min_after_dequeue=1000)
  File "/Users/user/anaconda/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/training/input.py", line 768, in shuffle_batch
    _enqueue(queue, tensor_list, num_threads, enqueue_many)
  File "/Users/user/anaconda/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/training/input.py", line 490, in _enqueue
    enqueue_ops = [queue.enqueue(tensor_list)] \* threads
  File "/Users/user/anaconda/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/data_flow_ops.py", line 296, in enqueue
    return gen_data_flow_ops._queue_enqueue(self._queue_ref, vals, name=scope)
  File "/Users/user/anaconda/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 542, in _queue_enqueue
    name=name)
  File "/Users/user/anaconda/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/op_def_library.py", line 711, in apply_op
    op_def=op_def)
  File "/Users/user/anaconda/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2260, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/Users/user/anaconda/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1230, in __init__
    self._traceback = _extract_stack()

Not sure if my fix to convert_to_records.py was wrong or the fully_connected_reader.py was off for some other reason.

**Comment by prb12** [comment]
**In future, could you please try to follow the issues submission template.**  

It is very difficult to reproduce errors when you do not provide the following basic information:

- What platform / OS are your running on?
- How did you install TensorFlow?
- Exactly what command lines did you use to build and execute the program?

**Comment by jackywang529** [comment]
Sorry about not specifying my situation clearly.

I am running on local OSX El Capitan and I installed Tensorflow using Anaconda with python 2.7 only on CPU mode so far, following https://www.tensorflow.org/versions/r0.9/get_started/os_setup.html#anaconda-installation, 
and downloaded the tensorflow wheel from https://storage.googleapis.com/tensorflow/mac/tensorflow-0.9.0-py2-none-any.whl (I'm guessing that's version 0.9.0, but I can be very wrong).

I have tried running in the mnist directory :
> source activate tensorflow
> python convolution.py 
This works perfectly!

Then I cloned the current tensorflow repository (with the latest commit of commit 84225a2b612fe748c9c923f0c1cb8471911c3b77), trying out the convert_to_records.py from https://github.com/tensorflow/tensorflow/blob/r0.9/tensorflow/examples/how_tos/reading_data/convert_to_records.py

I executed the following commands in tensorflow_tools/tensorflow/tensorflow/examples/how_tos/reading_data:
> source activate tensorflow
> python convert_to_records.py
python convert_to_records.py 
Traceback (most recent call last):
  File "convert_to_records.py", line 104, in <module>
    tf.app.run()
  File "/Users/chungyuwang/anaconda/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "convert_to_records.py", line 76, in main
    train_images_filename = input_data.maybe_download(
AttributeError: 'module' object has no attribute 'maybe_download'

To fix that, I updated the convert_to_records.py's main method to be similar to mnist/convolution.py's beginning part of the method
# Get the data.                                                               
train_data_filename = maybe_download('train-images-idx3-ubyte.gz')            
train_labels_filename = maybe_download('train-labels-idx1-ubyte.gz')          
test_data_filename = maybe_download('t10k-images-idx3-ubyte.gz')              
test_labels_filename = maybe_download('t10k-labels-idx1-ubyte.gz')            
# Extract it into numpy arrays.                                               
train_images = extract_data(train_data_filename, 60000)                       
train_labels = extract_labels(train_labels_filename, 60000)                   
test_images = extract_data(test_data_filename, 10000)                         
test_labels = extract_labels(test_labels_filename, 10000)     
and copied the maybe_download and extract_data directly from mnist/convolution.py

This change allowed the convert_to_records.py to run without problem, but when I tried to run
(tensorflow)> python fully_connected_reader.py, then the original post's stack trace/error occurred.

If there is anything else that I'm missing to help identify the issue, please definitely let me know, I'm really hoping to help out and learn from tensorflow! Thanks!

**Comment by mnuke** [comment]
Looking at this, it seems like in 5c9bc51857bc0c330d3ab976871ee3509647d1e7 the the maybe_download and extract_data methods (among others) were removed from input_data.py without checking that they were used outside the file. 

Not sure where else this affects but as @jackywang529 points out, models/image/mnist/convolutional.py has similar methods, so one solution might be to adapt maybe_download in convolutional.py and import those methods in input data. Another solution could be just to reinstate those methods even though we'd have two very similar methods in input_data and convolutional.py

**Comment by jackywang529** [comment]
Ya as @mnuke mentioned, those methods were removed from input_data.py. However, those methods are not exactly the same as the ones defined in the mnist/convolution.py, as the ones in mnist/convolution.py sets the data type to be float32 which shouldn't happen in this case, as the fully_connected_reader.py's read_and_decode method changes it to float32 again, thinking that it received int8 type. That's why I was getting the matrix mismatch issue reported earlier.

Although not highest priority, but it would definitely be kind to new users to update the input_data.py or other files soon. Thanks!

**Comment by drpngx** [comment]
This references code that might have changed substantially. Feel free to open a new issue if the problem persists with new code.
