### ISSUE TITLE
[TF 2.0] categorical_column_with_vocabulary_list not usable in custom training loop

### ISSUE THREAD

**Issue by IanQS** [tensorflow/tensorflow#30453]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Source
- TensorFlow version (use command below): v2.0.0-beta0-16-g1d91213fe7 2.0.0-beta1
- Python version: 3.6.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**

Outside of `fit`, e.g in a custom training loop, `categorical_column_with_vocabulary_list` results in an error. I have provided a modified version of [Classifying Structured data](https://www.tensorflow.org/beta/tutorials/keras/feature_columns) which demonstrates this.

The error is `ValueError: Column dtype and SparseTensors dtype must be compatible. key: thal, column dtype: <dtype: 'string'>, tensor dtype: <dtype: 'int32'>`

**Describe the expected behavior**

Code runs without causing an error

**Code to reproduce the issue**

It should be directly copy-paste-able 

```
import pandas as pd
import tensorflow as tf
from sklearn.model_selection import train_test_split


def df_to_dataset(df, shuffle=True, batch_size=32):
    df = df.copy()
    labels = df.pop('target')
    ds = tf.data.Dataset.from_tensor_slices(
        (dict(df), labels)
    )
    if shuffle:
        ds = ds.shuffle(buffer_size=len(df))
    ds = ds.batch(batch_size)
    return ds


def generate_features():
    feature_columns = []
    feature_layer_inputs = {}


    thal = tf.feature_column.categorical_column_with_vocabulary_list(
          'thal', ['fixed', 'normal', 'reversible'])
    thal_one_hot = tf.feature_column.indicator_column(thal)
    feature_columns.append(thal_one_hot)
    feature_layer_inputs['thal'] = tf.keras.Input(shape=(1,), name='thal', dtype=tf.string)

    return feature_columns, feature_layer_inputs


def create_model(feature_columns, feature_layer_inputs):
    input_layer = tf.keras.layers.DenseFeatures(feature_columns)
    inputs = input_layer(feature_layer_inputs)

    l1 = tf.keras.layers.Dense(128, activation='relu')(inputs)
    l2 = tf.keras.layers.Dense(128, activation='relu')(l1)

    output = tf.keras.layers.Dense(1, activation='sigmoid')(l2)

    model = tf.keras.Model(
        inputs=[v for v in feature_layer_inputs.values()],
        outputs=[output]
    )
    return model


def make_loss(loss_object):
    def loss(model, x, y):
        y_pred = model(x)
        return loss_object(y_true=y, y_pred=y_pred)
    return loss


def grad(model, inputs, targets, loss):
    with tf.GradientTape() as tape:
        loss_value = loss(model, inputs, targets)
    return loss_value, tape.gradient(loss_value, model.trainable_variables)


def fit(epochs, train_ds, model, optimizer, loss_obj):
    loss = make_loss(loss_obj)
    for epoch in range(epochs):
        for i, (x, y) in enumerate(train_ds):
            loss_values, grad_values = grad(model, x, y, loss)
            optimizer.apply_gradients(zip(grad_values, model.trainable_variables))


if __name__ == '__main__':
    URL = 'https://storage.googleapis.com/applied-dl/heart.csv'
    df = pd.read_csv(URL)
    CUSTOM_TRAINING = True

    train, test = train_test_split(df, test_size=0.2)
    train, val = train_test_split(train, test_size=0.2)

    # hardcoded stuff
    batch_size = 32
    train_ds = df_to_dataset(train, batch_size=batch_size)

    # Create model and features
    feature_columns, feature_layer_inputs = generate_features()
    model = create_model(feature_columns, feature_layer_inputs)

    if CUSTOM_TRAINING:
        print('Trying custom training')
        bce = tf.keras.losses.BinaryCrossentropy()
        adam = tf.keras.optimizers.Adam()
        fit(epochs=5, train_ds=train_ds,
            model=model, optimizer=adam, loss_obj=bce)
    else:
        print('Using pre-defined fit')
        model.compile(optimizer='adam',
                      loss='binary_crossentropy',
                      metrics=['accuracy'])
        model.fit(train_ds, epochs=5)
```

If you flip the `CUSTOM_TRAINING` variable between `True` and `False` (line 72) you'll see what I mean. 

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

1) The complete (relevant) stacktrace is 

```
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 1758, in <module>
    main()
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 1752, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 1147, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/ian.quah/PycharmProjects/tf2/datasets/issues.py", line 90, in <module>
    model=model, optimizer=adam, loss_obj=bce)
  File "/Users/ian.quah/PycharmProjects/tf2/datasets/issues.py", line 65, in fit
    loss_values, grad_values = grad(model, x, y, loss)
  File "/Users/ian.quah/PycharmProjects/tf2/datasets/issues.py", line 57, in grad
    loss_value = loss(model, inputs, targets)
  File "/Users/ian.quah/PycharmProjects/tf2/datasets/issues.py", line 50, in loss
    y_pred = model(x)
  File "/anaconda3/envs/mlpl/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 712, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/anaconda3/envs/mlpl/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 753, in call
    return self._run_internal_graph(inputs, training=training, mask=mask)
  File "/anaconda3/envs/mlpl/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 895, in _run_internal_graph
    output_tensors = layer(computed_tensors, **kwargs)
  File "/anaconda3/envs/mlpl/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 712, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/anaconda3/envs/mlpl/lib/python3.6/site-packages/tensorflow/python/feature_column/feature_column_v2.py", line 474, in call
    self._state_manager)
  File "/anaconda3/envs/mlpl/lib/python3.6/site-packages/tensorflow/python/feature_column/feature_column_v2.py", line 4299, in get_dense_tensor
    return transformation_cache.get(self, state_manager)
  File "/anaconda3/envs/mlpl/lib/python3.6/site-packages/tensorflow/python/feature_column/feature_column_v2.py", line 2562, in get
    transformed = column.transform_feature(self, state_manager)
  File "/anaconda3/envs/mlpl/lib/python3.6/site-packages/tensorflow/python/feature_column/feature_column_v2.py", line 4238, in transform_feature
    transformation_cache, state_manager)
  File "/anaconda3/envs/mlpl/lib/python3.6/site-packages/tensorflow/python/feature_column/feature_column_v2.py", line 3714, in get_sparse_tensors
    transformation_cache.get(self, state_manager), None)
  File "/anaconda3/envs/mlpl/lib/python3.6/site-packages/tensorflow/python/feature_column/feature_column_v2.py", line 2562, in get
    transformed = column.transform_feature(self, state_manager)
  File "/anaconda3/envs/mlpl/lib/python3.6/site-packages/tensorflow/python/feature_column/feature_column_v2.py", line 3692, in transform_feature
    return self._transform_input_tensor(input_tensor)
  File "/anaconda3/envs/mlpl/lib/python3.6/site-packages/tensorflow/python/feature_column/feature_column_v2.py", line 3668, in _transform_input_tensor
    self.key, self.dtype, input_tensor.dtype))
ValueError: Column dtype and SparseTensors dtype must be compatible. key: thal, column dtype: <dtype: 'string'>, tensor dtype: <dtype: 'int32'>
```

2)  Placing a debugger on line 50 leads me to `feature_column_v2.py` specifically `_transform_input_tensor`

The `input_tensor` arg to `_transform_input_tensor` is 

```
SparseTensor(indices=tf.Tensor(
[[ 0  0]
 [ 1  0]
 [ 2  0]
 [ 3  0]
 [ 4  0]
 [ 5  0]
 [ 6  0]
 [ 7  0]
 [ 8  0]
 [ 9  0]
 [10  0]
 [11  0]
 [12  0]
 [13  0]
 [14  0]
 [15  0]
 [16  0]
 [17  0]
 [18  0]
 [19  0]
 [20  0]
 [21  0]
 [22  0]
 [23  0]
 [24  0]
 [25  0]
 [26  0]
 [27  0]
 [28  0]
 [29  0]
 [30  0]
 [31  0]], shape=(32, 2), dtype=int64), values=tf.Tensor(
[49 34 58 46 59 47 55 58 41 68 62 51 61 46 39 48 37 41 51 59 51 70 60 57
 54 60 52 44 65 49 44 59], shape=(32,), dtype=int32), dense_shape=tf.Tensor([32  1], shape=(2,), dtype=int64))
```

which seems strange? It's like it forgot that it had transformed those variables?

**Comment by rmothukuru** [comment]
Reproduced the error with TF Version 2.0.beta1

**Comment by IanQS** [comment]
> Reproduced the error with TF Version 2.0.beta1

Not to question your judgement (proceeds to question) but is this a performance bug?

**Comment by IanQS** [comment]
Thanks! 

1) Does anyone have an intuition as to why this happens in a custom loop but not in `fit`?

2) Does anyone have a quick fix?

**Comment by dulm** [comment]
New error for 'tf-nightly-2.0-preview           2.0.0.dev20190714 ' with @tf.function
```
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1758, in <module>
    main()
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1752, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1147, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/lqk/project/PycharmProjects/TF2/shared_embedding.py", line 44, in <module>
    df = shared_embedding_column_with_hash_bucket(dic_data)
  File "/Users/lqk/anaconda2/envs/p36t2/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 429, in __call__
    return self._stateless_fn(*args, **kwds)
  File "/Users/lqk/anaconda2/envs/p36t2/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1661, in __call__
    graph_function, args, kwargs = self._maybe_define_function(args, kwargs)
  File "/Users/lqk/anaconda2/envs/p36t2/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1991, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/Users/lqk/anaconda2/envs/p36t2/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1877, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/Users/lqk/anaconda2/envs/p36t2/lib/python3.6/site-packages/tensorflow_core/python/framework/func_graph.py", line 791, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/Users/lqk/anaconda2/envs/p36t2/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 310, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/Users/lqk/anaconda2/envs/p36t2/lib/python3.6/site-packages/tensorflow_core/python/framework/func_graph.py", line 781, in wrapper
    raise e.ag_error_metadata.to_exception(type(e))
AttributeError: in converted code:
    relative to /Users/lqk:

    project/PycharmProjects/TF2/shared_embedding.py:36 shared_embedding_column_with_hash_bucket  *
        df = tf.keras.layers.DenseFeatures(color_column_embed)(dic_data)
    anaconda2/envs/p36t2/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py:758 __call__
        outputs = self.call(inputs, *args, **kwargs)
    anaconda2/envs/p36t2/lib/python3.6/site-packages/tensorflow_core/python/feature_column/feature_column_v2.py:508 call
        self._state_manager)
    anaconda2/envs/p36t2/lib/python3.6/site-packages/tensorflow_core/python/feature_column/feature_column_v2.py:3418 get_dense_tensor
        return self._get_dense_tensor_internal(transformation_cache, state_manager)
    anaconda2/envs/p36t2/lib/python3.6/site-packages/tensorflow_core/python/feature_column/feature_column_v2.py:3395 _get_dense_tensor_internal
        embedding_weights = self.shared_embedding_column_creator.embedding_weights
    anaconda2/envs/p36t2/lib/python3.6/site-packages/tensorflow_core/python/feature_column/feature_column_v2.py:3322 embedding_weights
        trainable=self._trainable)
    anaconda2/envs/p36t2/lib/python3.6/site-packages/tensorflow_core/python/ops/variable_scope.py:1500 get_variable
        aggregation=aggregation)
    anaconda2/envs/p36t2/lib/python3.6/site-packages/tensorflow_core/python/ops/variable_scope.py:1243 get_variable
        aggregation=aggregation)
    anaconda2/envs/p36t2/lib/python3.6/site-packages/tensorflow_core/python/ops/variable_scope.py:567 get_variable
        aggregation=aggregation)
    anaconda2/envs/p36t2/lib/python3.6/site-packages/tensorflow_core/python/ops/variable_scope.py:519 _true_getter
        aggregation=aggregation)
    anaconda2/envs/p36t2/lib/python3.6/site-packages/tensorflow_core/python/ops/variable_scope.py:861 _get_single_variable
        tb = var.op.traceback[::-1]
    anaconda2/envs/p36t2/lib/python3.6/site-packages/tensorflow_core/python/ops/resource_variable_ops.py:558 op
        return self._handle.op
    anaconda2/envs/p36t2/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:986 op
        "Tensor.op is meaningless when eager execution is enabled.")

    AttributeError: Tensor.op is meaningless when eager execution is enabled.
```

**Comment by pavithrasv** [comment]
Adding @rohan100jain who is the expert on feature columns.

**Comment by nilselde** [comment]
I think I've also reproduced this.

I'm trying to call `predict_classes` on a `tf.keras.Sequential` model that contains `categorical_column_with_vocabulary_list`, `categorical_column_with_hash_bucket`, and `numeric_column`. I'm passing `predict_classes` a list of NumPy arrays that contain the types `numpy.int64`, `numpy.float64`, and `str`.

I've reproduced the same error:
```
ValueError: Column dtype and SparseTensors dtype must be compatible. key: columnName, column dtype: <dtype: 'string'>, tensor dtype: <dtype: 'int64'>
```

`columnName` in the NumPy array is the correct type. It is a string in the form `\d+`, e.g. '1234' (it is categorical data that just so happens to be comprised of digits). The values in the NumPy array are in the correct order.

There are no problems with `compile`, `fit`, or `evaluate` from tf.keras.Sequential.

I was able to call `predict` when passing in a dataset instead of a list of NumPy arrays, but the output was a float. I was hoping for a binary classification, which is why I was trying `predict_classes`. (Any guidance here would also be tremendously appreciated).

**System information**
- Have I written custom code: Yes
- OS Platform and Distribution: macOS 10.14.6
- Mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version: v2.0.0-beta0-16-g1d91213fe7 2.0.0-beta1
- Python version: 3.7.3
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Comment by IanQS** [comment]
Is this still an open issue?

**Comment by luvneries** [comment]
facing same issue.

**Comment by nareshr8** [comment]
I am also facing the same issue. Any help...

**Comment by nareshr8** [comment]
This got resolved for me. The datatype of the vocabulary list passed to the method, the data in the column of the record and the data type that we specify in the model have to be the same. Was able to find the issue, it got resolved.

**Comment by WakerKQ** [comment]
same issue with tensorflow 1.14
    ValueError: Column dtype and SparseTensors dtype must be compatible. key: adt_sev_flag, column dtype: <dtype: 'int64'>, tensor dtype: <dtype: 'float64'>

**Comment by WakerKQ** [comment]
> This got resolved for me. The datatype of the vocabulary list passed to the method, the data in the column of the record and the data type that we specify in the model have to be the same. Was able to find the issue, it got resolved.

how did you solved it?

**Comment by nareshr8** [comment]
The have you checked if the datatype of the data in the vocab list, the datatype of the input data and the data type of the feature_column declaration are same. In my case, the vocab list that I passed had infered to a different datatype and I passed it into the categorical_column_with_vocabulary_list layer incorrectly.

**Comment by tanzhenyu** [comment]
I have tried this example in tf-nightly, which seems to have been resolved. It's probably a Keras issue instead of FeatureColumn. Can anyone help to verify?

**Comment by AKIvan** [comment]
I'm using 1.12 version and i have no problem. But today it just happen. I can't understand how and why im getting this error. From nowhere and no update no changes ? And what should be the fix?
