### ISSUE TITLE
can not convert tf model to tflite

### ISSUE THREAD

**Issue by Davari393** [tensorflow/tensorflow#30458]
Hi.i tried convert my tensorflow model to tensorflow lite with saved model of pretrained model such as:

import tensorflow as tf
converter=tf.lite.TFLiteConverter.from_saved_model("ssd_mobilenet_v1_0.75_depth_300x300_coco14_sync_2018_07_03/saved_model" ,input_arrays=None , input_shapes = (1,300,300,3),output_arrays=None, tag_set=None, signature_key=None)
tflite_model = converter.convert()
open("converted_model.tflite", "wb").write(tflite_model)

but i got this error:

2019-07-07 16:56:02.926259: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-07-07 16:56:02.948528: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3192640000 Hz
2019-07-07 16:56:02.948956: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x3ab6990 executing computations on platform Host. Devices:
2019-07-07 16:56:02.948982: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
WARNING: Logging before flag parsing goes to stderr.
W0707 16:56:02.949664 140418756732736 deprecation.py:323] From /home/davari/virtualenvironments/detection_on_mobile/lib/python3.6/site-packages/tensorflow_core/lite/python/convert_saved_model.py:60: load (from tensorflow.python.saved_model.loader_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.loader.load or tf.compat.v1.saved_model.load. There will be a new function for importing SavedModels in Tensorflow 2.0.
Traceback (most recent call last):
  File "TFlite_converter.py", line 30, in <module>
    converter = tf.lite.TFLiteConverter.from_saved_model("ssd_mobilenet_v1_0.75_depth_300x300_coco14_sync_2018_07_03/saved_model" ,input_arrays=None , input_shapes = (1,300,300,3),output_arrays=None, tag_set=None, signature_key=None)
  File "/home/davari/virtualenvironments/detection_on_mobile/lib/python3.6/site-packages/tensorflow_core/lite/python/lite.py", line 757, in from_saved_model
    output_arrays, tag_set, signature_key)
  File "/home/davari/virtualenvironments/detection_on_mobile/lib/python3.6/site-packages/tensorflow_core/lite/python/convert_saved_model.py", line 204, in freeze_saved_model
    util.set_tensor_shapes(in_tensors, input_shapes)
  File "/home/davari/virtualenvironments/detection_on_mobile/lib/python3.6/site-packages/tensorflow_core/lite/python/util.py", line 145, in set_tensor_shapes
    for name, shape in shapes.items():
AttributeError: 'tuple' object has no attribute 'items'

can any one helps me?

**Comment by vk1996** [comment]
The tflite works well for me in TF1.13. What's your tf version ?
Note: i work with hdf5 and not saved_model.

**Comment by Davari393** [comment]
> The tflite works well for me in TF1.13. What's your tf version ?
> Note: i work with hdf5 and not saved_model.

Thanks for your response.
my tf version is:1.15

which library and dependencies should i have?please tell me all of them

**Comment by vk1996** [comment]
@Davari393 I'm afraid the stable version is only till 1.14 from tensorflow. Kindly check the version and only use the latest stable version for best performance. Also before loading the model,check for custom objects for your model if any.
