### ISSUE TITLE
No module named '_pywrap_tensorflow' error even after installing Visual C++ and MSVCP140.dll.

### ISSUE THREAD

**Issue by SharawatChirag** [tensorflow/tensorflow#30480]
I'm trying to run the simple speech recognition network example of Tensorflow:

python tensorflow/examples/speech_commands/train.py

But I keep getting:

> Traceback (most recent call last):
  File "C:\Users\DELL 7000\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tensorflow', [dirname(__file__)])
  File "C:\Users\DELL 7000\AppData\Local\Programs\Python\Python37-32\lib\imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tensorflow'

>During handling of the above exception, another exception occurred:

>Traceback (most recent call last):
  File "C:\Users\DELL 7000\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tensorflow\python\__init__.py", line 66, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\DELL 7000\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "C:\Users\DELL 7000\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 20, in swig_import_helper
    import _pywrap_tensorflow
ModuleNotFoundError: No module named '_pywrap_tensorflow'

>During handling of the above exception, another exception occurred:

>Traceback (most recent call last):
  File "tensorflow/examples/speech_commands/train.py", line 79, in <module>
    import tensorflow as tf
  File "C:\Users\DELL 7000\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "C:\Users\DELL 7000\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tensorflow\python\__init__.py", line 72, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\DELL 7000\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tensorflow', [dirname(__file__)])
  File "C:\Users\DELL 7000\AppData\Local\Programs\Python\Python37-32\lib\imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tensorflow'

>During handling of the above exception, another exception occurred:

>Traceback (most recent call last):
  File "C:\Users\DELL 7000\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tensorflow\python\__init__.py", line 66, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\DELL 7000\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "C:\Users\DELL 7000\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 20, in swig_import_helper
    import _pywrap_tensorflow
ModuleNotFoundError: No module named '_pywrap_tensorflow'

>Failed to load the native TensorFlow runtime.

>See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md#import_error

>for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

Most of the solutions I found told me to reinstall visual c++ or to manually add MSVCP140.dll to the path. But neither of these solve my problem.
The github page it tells me to refer returns a 404.
I'm on python 3.7.2 and tensorflow 1.0.0.
Kindly help if possible.

**Comment by gadagashwini** [comment]
@SharawatChirag Does your CPU support AVX instruction set? Thanks!
