### ISSUE TITLE
Error importing tensorflow on windows 10 - OSError: [WinError 126] The specified module could not be found

### ISSUE THREAD

**Issue by yarin177** [tensorflow/tensorflow#30539]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): cmd 
- TensorFlow GPU  version:  1.14.0
- Python version: 3.6.4
- Installed using virtualenv? pip? conda?: pip
- CUDA/cuDNN version: 10.1, 7.6.0
- GPU model and memory: GTX 970 8GB RAM

Hey i've recently tried to installed tensorflow-gpu and before that i made sure that I have all Environment variables set up cuDNN, CUDA, drivers. 
eventually i installed tensorflow-gpu using pip (pip install --ignore-installed -- upgrade tensorflow-gpu

after the Installation I tried importing tensorflow as tf and It came up with this error:
>>> import tensorflow as tf
Traceback (most recent call last):
  File "C:\Users\ירין\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\platform\self_check.py", line 75, in preload_check
    ctypes.WinDLL(build_info.cudart_dll_name)
  File "C:\Users\ירין\AppData\Local\Programs\Python\Python36\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
>>> import tensorflow as tf
  File "<stdin>", line 1, in <module>
  File "C:\Users\ירין\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\ירין\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\ירין\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 30, in <module>
    self_check.preload_check()
  File "C:\Users\ירין\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\platform\self_check.py", line 82, in preload_check
    % (build_info.cudart_dll_name, build_info.cuda_version_number))
ImportError: Could not find 'cudart64_100.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Download and install CUDA 10.0 from this URL: https://developer.nvidia.com/cuda-90-download-archive

**it says it cannot find 'cudart64_100.dll' but I have in my cuda folder the following dll 'cudnn64_7'**

Here is a pic of my Environment variables : https://imgur.com/a/UXub3LR

**Comment by ymodak** [comment]
TF 1.14 GPU supports cuda 10.0 please switch to cuda 10.0 and update the environment variables. Thanks!

**Comment by yarin177** [comment]
> TF 1.14 GPU supports cuda 10.0 please switch to cuda 10.0 and update the environment variables. Thanks!

Thanks I did it but now I get this error:

>>> import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\ירין\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\ירין\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\__init__.py", line 83, in <module>
    from tensorflow.python import keras
  File "C:\Users\ירין\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\__init__.py", line 26, in <module>
    from tensorflow.python.keras import activations
  File "C:\Users\ירין\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\activations\__init__.py", line 22, in <module>
    from tensorflow.python.keras._impl.keras.activations import elu
  File "C:\Users\ירין\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\_impl\keras\__init__.py", line 21, in <module>
    from tensorflow.python.keras._impl.keras import activations
  File "C:\Users\ירין\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\_impl\keras\activations.py", line 23, in <module>
    from tensorflow.python.keras._impl.keras import backend as K
  File "C:\Users\ירין\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\_impl\keras\backend.py", line 37, in <module>
    from tensorflow.python.layers import base as tf_base_layers
  File "C:\Users\ירין\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\layers\base.py", line 25, in <module>
    from tensorflow.python.keras import backend
  File "C:\Users\ירין\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\backend\__init__.py", line 22, in <module>
    from tensorflow.python.keras._impl.keras.backend import abs
ImportError: cannot import name 'abs'

**Comment by ymodak** [comment]
Probably this can help,
https://github.com/tensorflow/tensorflow/issues/20778#issuecomment-410962482

**Comment by yarin177** [comment]
Yay I got it to work by uninstalling and installing tensor flow!

**Comment by ymodak** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
