### ISSUE TITLE
Transformer training error with evaluation/test dataset newstest2014.de 

### ISSUE THREAD

**Issue by Montantes** [tensorflow/tensorflow#30536]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes (only changed batch/filter size on modelparams.py)
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): https://hub.docker.com/r/tensorflow/tensorflow nightly-gpu-py3
- TensorFlow version (use command below): 1.15
- Python version: 3.6
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: 10.1
- GPU model and memory: NVIDIA RTX 8000 x2 (wNVLINK)

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
When following the transformer [walkthrough](https://github.com/tensorflow/models/tree/master/official/transformer#detailed-instructions) There seems to be an issue with the newstest2014.de 'Download and preprocess datasets' step the newstest2014.de doesn't appear to be in valid text format. When its unpacked it cannot be opened as a text file (looks like another archive file) as the newstest2014.en can and was in previous versions. 

For example: when I run the following command (after completing the rest of the requisite steps): 

_python3 transformer_main.py --data_dir=$DATA_DIR --model_dir=$MODEL_DIR --vocab_file=$VOCAB_FILE --param_set=$PARAM_SET --bleu_source=$DATA_DIR/newstest2014.en --bleu_ref=$DATA_DIR/newstest2014.de --train_steps=250000 --steps_between_evals=10000 --export_dir=$EXPORT_DIR_ 

I get the error ( see attached/below for traceback) **UnicodeDecodeError: 'utf8' codec can't decode byte 0x8b in position 1: invalid start byte**

**Describe the expected behavior**
compute_bleu.py should work, but does not (only when i replace newstest2014.de with an older version (text format)

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
Follow the example walkthrough, you'll get invalid newstest2014.de (as of  7/8/19)

**Other info / logs** see attached for traceback as well
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

As it currently stands, training only worked when i replaced the invalid newstest2014.de file with the older version, therefore i think thats the error.

I0708 18:55:13.764734 140267571169088 translate.py:133] Writing to file /tmp/tmpie7053oh
Traceback (most recent call last):
  File "transformer_main.py", line 670, in <module>
    absl_app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "transformer_main.py", line 664, in main
    run_transformer(flags.FLAGS)
  File "transformer_main.py", line 644, in run_transformer
    vocab_file=flags_obj.vocab_file)
  File "transformer_main.py", line 361, in run_loop
    estimator, bleu_source, bleu_ref, vocab_file)
  File "transformer_main.py", line 238, in evaluate_and_log_bleu
    estimator, subtokenizer, bleu_source, bleu_ref)
  File "transformer_main.py", line 222, in translate_and_compute_bleu
    uncased_score = compute_bleu.bleu_wrapper(bleu_ref, tmp_filename, False)
  File "/datasets/datasets/models/official/transformer/compute_bleu.py", line 91, in bleu_wrapper
    tf.io.gfile.GFile(ref_filename).read()).strip().splitlines()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/lib/io/file_io.py", line 128, in read
    pywrap_tensorflow.ReadFromStream(self._read_buf, length))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/lib/io/file_io.py", line 98, in _prepare_value
    return compat.as_str_any(val)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/util/compat.py", line 117, in as_str_any
    return as_str(value)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/util/compat.py", line 87, in as_text
    return bytes_or_text.decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

 
[traceback1.txt](https://github.com/tensorflow/tensorflow/files/3373946/traceback1.txt)

**Comment by Montantes** [comment]
moved to tensorflow/models issues, should be there, closing.
