### ISSUE TITLE
Share tf.distribute.strategy scopes across multiple sets of GPUs for multithreaded data gather and training

### ISSUE THREAD

**Issue by mjlbach** [tensorflow/tensorflow#30605]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 1.14/2.0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
In some RL models, an agent will gather data in one thread/process while an update loop in a second thread calculates the gradients/updates the model. Often for model-based RL, the time spent performing forward passes through the model can be large, so this has many advantages if it can be a non-blocking procedure in parallel with the update calls. It would be useful to be able to use the new tf.distribute strategies to share weights across multiple *sets* of GPUs (for instance, one GPU performs continual forward passes through the model while the remaining 7 on the node perform the updates on the model) across threads/processes. In the current parameter server model, I can simply pass the tf.Server configuration and build the graph in multiple workers, sharing the same set of variables on the parameter server.

**Will this change the current api? How?**

**Who will benefit with this feature?**

**Any Other info.**

**Comment by guptapriya** [comment]
What you're describing sounds like one way to do model parallelism and distribution strategy doesn't support that yet. So for now, you would have to manually copy the variables from one thread/process to another to achieve the above.

Here is the response from @tomhennigan who works with folks who do RL with TF:

For single machine multi-threaded training you can simply use eager mode to read parameter values from the learner in your actor threads. I suspect at some point you might want to scale your learner beyond one GPU, using MirroredStrategy to do that should hardly change the pseudocode below (add the strategy scope around model construction and using strategy.run to parallel apply the training step).

```
learner = MyModel()

def learner():
  while True:
    train(learner, ...)

def actor():
  actor = MyModel()

  while True:
    if should_copy_from_learner:
      for l, a in zip(learner.variables, actor.variables):
        a.assign(l)

    act(actor, ...)

run_in_thread(learner)
run_in_thread(actor)
```

**Comment by mjlbach** [comment]
Thanks for the idea! I'm currently building my model as a subclass of tf.Module containing keras layers across my actor and learner thread. I'd like to use Autograph as my model uses graph convolutions which seem to perform significantly more slowly in eager execution. Is this paradigm incompatible with autograph?

**Comment by anj-s** [comment]
"I've had difficulty getting the distributed strategy to work without decorating my train loop in tf.function" - can you share a code snippet to help us repro this issue? You should be able to use tf.distribute strategy without tf.function without errors.

**Comment by mjlbach** [comment]
> "I've had difficulty getting the distributed strategy to work without decorating my train loop in tf.function" - can you share a code snippet to help us repro this issue? You should be able to use tf.distribute strategy without tf.function without errors.

I'm working on a minimal example now... The main problem I have is that it's hard to debug exactly which operation is triggering the problem. It seems to be an incompatibility of the op with the GPU.

```
2019-07-24 11:40:07.065064: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10.0
Traceback (most recent call last):
  File "../physics/scripts/train_interaction.py", line 26, in <module>
    main()
  File "../physics/scripts/train_interaction.py", line 19, in main
    train_worker.distributed_train()
  File "/home/mjlbach/Repositories/tf2.0_box_physics/physics/physics/scripts/worker.py", line 246, in distributed_train
    train_res = distributed_train_step(
  File "/home/mjlbach/Repositories/tf2.0_box_physics/physics/physics/scripts/train_step.py", line 26, in distributed_train_step
    train_step, args=(inputs, world_model, world_optimizer)
  File "/home/mjlbach/.virtualenvs/physics3/lib/python3.6/site-packages/tensorflow/python/distribute/distribute_lib.py", line 708, in experimental_run_v2
    return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
  File "/home/mjlbach/.virtualenvs/physics3/lib/python3.6/site-packages/tensorflow/python/distribute/distribute_lib.py", line 1710, in call_for_each_replica
    return self._call_for_each_replica(fn, args, kwargs)
  File "/home/mjlbach/.virtualenvs/physics3/lib/python3.6/site-packages/tensorflow/python/distribute/mirrored_strategy.py", line 708, in _call_for_each_replica
    fn, args, kwargs)
  File "/home/mjlbach/.virtualenvs/physics3/lib/python3.6/site-packages/tensorflow/python/distribute/mirrored_strategy.py", line 195, in _call_for_each_replica
    coord.join(threads)
  File "/home/mjlbach/.virtualenvs/physics3/lib/python3.6/site-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/home/mjlbach/.virtualenvs/physics3/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/mjlbach/.virtualenvs/physics3/lib/python3.6/site-packages/tensorflow/python/training/coordinator.py", line 297, in stop_on_exception
    yield
  File "/home/mjlbach/.virtualenvs/physics3/lib/python3.6/site-packages/tensorflow/python/distribute/mirrored_strategy.py", line 189, in _call_for_each_replica
    **merge_kwargs)
  File "/home/mjlbach/.virtualenvs/physics3/lib/python3.6/site-packages/tensorflow/python/distribute/values.py", line 825, in merge_fn
    v = _apply_aggregation(strategy, value, self._aggregation, self)
  File "/home/mjlbach/.virtualenvs/physics3/lib/python3.6/site-packages/tensorflow/python/distribute/values.py", line 747, in _apply_aggregation
    return strategy.extended.reduce_to(reduce_op, value, destinations)
  File "/home/mjlbach/.virtualenvs/physics3/lib/python3.6/site-packages/tensorflow/python/distribute/distribute_lib.py", line 1388, in reduce_to
    return self._reduce_to(reduce_op, value, destinations)
  File "/home/mjlbach/.virtualenvs/physics3/lib/python3.6/site-packages/tensorflow/python/distribute/mirrored_strategy.py", line 750, in _reduce_to
    reduce_op, value, destinations=destinations)
  File "/home/mjlbach/.virtualenvs/physics3/lib/python3.6/site-packages/tensorflow/python/distribute/cross_device_ops.py", line 272, in reduce
    destinations)
  File "/home/mjlbach/.virtualenvs/physics3/lib/python3.6/site-packages/tensorflow/python/distribute/cross_device_ops.py", line 695, in reduce_implementation
    return self._batch_all_reduce(reduce_op, [per_replica_value])[0]
  File "/home/mjlbach/.virtualenvs/physics3/lib/python3.6/site-packages/tensorflow/python/distribute/cross_device_ops.py", line 715, in _batch_all_reduce
    dense_results = self._do_batch_all_reduce(reduce_op, dense_values)
  File "/home/mjlbach/.virtualenvs/physics3/lib/python3.6/site-packages/tensorflow/python/distribute/cross_device_ops.py", line 740, in _do_batch_all_reduce
    self._agg_small_grads_max_group)
  File "/home/mjlbach/.virtualenvs/physics3/lib/python3.6/site-packages/tensorflow/python/distribute/cross_device_ops.py", line 641, in _pack_tensors
    device_grad_packs = tensor_packer.pack(device_grads)
  File "/home/mjlbach/.virtualenvs/physics3/lib/python3.6/site-packages/tensorflow/python/distribute/cross_device_ops.py", line 547, in pack
    grad_packs = array_ops.split(concat_grads, split_sizes)
  File "/home/mjlbach/.virtualenvs/physics3/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 1564, in split
    value=value, size_splits=size_splits, axis=axis, num_split=num, name=name)
  File "/home/mjlbach/.virtualenvs/physics3/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 9566, in split_v
    _six.raise_from(_core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.NotFoundError: No registered 'SplitV' OpKernel for GPU devices compatible with node {{node SplitV}}
	 (OpKernel was found, but attributes didn't match) Requested Attributes: T=DT_INT64, Tlen=DT_INT32, num_split=1
	.  Registered:  device='XLA_CPU'; Tlen in [DT_INT32, DT_INT64]; T in [DT_FLOAT, DT_DOUBLE, DT_INT32, DT_UINT8, DT_INT8, ..., DT_BFLOAT16, DT_COMPLEX128, DT_HALF, DT_UINT32, DT_UINT64]
  device='XLA_GPU'; Tlen in [DT_INT32, DT_INT64]; T in [DT_FLOAT, DT_DOUBLE, DT_INT32, DT_UINT8, DT_INT8, ..., DT_QINT32, DT_BFLOAT16, DT_HALF, DT_UINT32, DT_UINT64]
  device='XLA_CPU_JIT'; Tlen in [DT_INT32, DT_INT64]; T in [DT_FLOAT, DT_DOUBLE, DT_INT32, DT_UINT8, DT_INT8, ..., DT_BFLOAT16, DT_COMPLEX128, DT_HALF, DT_UINT32, DT_UINT64]
  device='XLA_GPU_JIT'; Tlen in [DT_INT32, DT_INT64]; T in [DT_FLOAT, DT_DOUBLE, DT_INT32, DT_UINT8, DT_INT8, ..., DT_QINT32, DT_BFLOAT16, DT_HALF, DT_UINT32, DT_UINT64]
  device='CPU'; Tlen in [DT_INT64]; T in [DT_VARIANT]
  device='CPU'; Tlen in [DT_INT32]; T in [DT_VARIANT]
  device='CPU'; Tlen in [DT_INT64]; T in [DT_RESOURCE]
  device='CPU'; Tlen in [DT_INT32]; T in [DT_RESOURCE]
  device='CPU'; Tlen in [DT_INT64]; T in [DT_STRING]
  device='CPU'; Tlen in [DT_INT32]; T in [DT_STRING]
  device='CPU'; Tlen in [DT_INT64]; T in [DT_BOOL]
  device='CPU'; Tlen in [DT_INT32]; T in [DT_BOOL]
  device='CPU'; Tlen in [DT_INT64]; T in [DT_COMPLEX128]
  device='CPU'; Tlen in [DT_INT32]; T in [DT_COMPLEX128]
  device='CPU'; Tlen in [DT_INT64]; T in [DT_COMPLEX64]
  device='CPU'; Tlen in [DT_INT32]; T in [DT_COMPLEX64]
  device='CPU'; Tlen in [DT_INT64]; T in [DT_DOUBLE]
  device='CPU'; Tlen in [DT_INT32]; T in [DT_DOUBLE]
  device='CPU'; Tlen in [DT_INT64]; T in [DT_FLOAT]
  device='CPU'; Tlen in [DT_INT32]; T in [DT_FLOAT]
  device='CPU'; Tlen in [DT_INT64]; T in [DT_BFLOAT16]
  device='CPU'; Tlen in [DT_INT32]; T in [DT_BFLOAT16]
  device='CPU'; Tlen in [DT_INT64]; T in [DT_HALF]
  device='CPU'; Tlen in [DT_INT32]; T in [DT_HALF]
  device='CPU'; Tlen in [DT_INT64]; T in [DT_INT8]
  device='CPU'; Tlen in [DT_INT32]; T in [DT_INT8]
  device='CPU'; Tlen in [DT_INT64]; T in [DT_UINT8]
  device='CPU'; Tlen in [DT_INT32]; T in [DT_UINT8]
  device='CPU'; Tlen in [DT_INT64]; T in [DT_INT16]
  device='CPU'; Tlen in [DT_INT32]; T in [DT_INT16]
  device='CPU'; Tlen in [DT_INT64]; T in [DT_UINT16]
  device='CPU'; Tlen in [DT_INT32]; T in [DT_UINT16]
  device='CPU'; Tlen in [DT_INT64]; T in [DT_INT32]
  device='CPU'; Tlen in [DT_INT32]; T in [DT_INT32]
  device='CPU'; Tlen in [DT_INT64]; T in [DT_INT64]
  device='CPU'; Tlen in [DT_INT32]; T in [DT_INT64]
  device='GPU'; T in [DT_INT32]; Tlen in [DT_INT64]
  device='GPU'; T in [DT_INT32]; Tlen in [DT_INT32]
  device='GPU'; Tlen in [DT_INT64]; T in [DT_BFLOAT16]
  device='GPU'; Tlen in [DT_INT32]; T in [DT_BFLOAT16]
  device='GPU'; Tlen in [DT_INT64]; T in [DT_COMPLEX128]
  device='GPU'; Tlen in [DT_INT32]; T in [DT_COMPLEX128]
  device='GPU'; Tlen in [DT_INT64]; T in [DT_COMPLEX64]
  device='GPU'; Tlen in [DT_INT32]; T in [DT_COMPLEX64]
  device='GPU'; Tlen in [DT_INT64]; T in [DT_DOUBLE]
  device='GPU'; Tlen in [DT_INT32]; T in [DT_DOUBLE]
  device='GPU'; Tlen in [DT_INT64]; T in [DT_FLOAT]
  device='GPU'; Tlen in [DT_INT32]; T in [DT_FLOAT]
  device='GPU'; Tlen in [DT_INT64]; T in [DT_HALF]
  device='GPU'; Tlen in [DT_INT32]; T in [DT_HALF]
 [Op:SplitV] name: split
```
