### ISSUE TITLE
Additional command line arguments needed for tflite conversion of a very simple model

### ISSUE THREAD

**Issue by DocDriven** [tensorflow/tensorflow#30606]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: -
- TensorFlow installed from (source or binary): Docker image tensorflow/tensorflow:latest-gpu
- TensorFlow version (use command below): 1.14.0
- Python version: 2.7.15+
- Bazel version (if compiling from source): -
- GCC/Compiler version (if compiling from source): -
- CUDA/cuDNN version: 10.1
- GPU model and memory: GeForce RTX 2080 Ti

I am trying to deploy a simple, custom fully-quantized model with Coral Edge TPU support. When trying to convert the frozen graph into a tflite model, I run into errors, unless I provide more command line arguments. Considering how simple the model is (e.g. using very basic layers), I did not expect to run into problems.

**Code to reproduce the issue**

I create and train a model that fits the function f(x) = 2 x - 1 with the following code:

```
import tensorflow as tf
from tensorflow import keras
import numpy as np

print(tf.__version__)

train_input = np.array([ -1.0, 0.0, 1.0, 2.0, 3.0, 4.0], dtype=float)
train_truth = np.array([ -3.0, -1.0, 1.0, 3.0, 5.0, 7.0], dtype=float)

def build_keras_model():
	return keras.models.Sequential([
		keras.layers.Dense(units=1, input_shape=[1]),
	])

### train the model
train_graph = tf.Graph()
train_sess = tf.Session(graph=train_graph)

keras.backend.set_session(train_sess)

with train_graph.as_default():
	keras.backend.set_learning_phase(1)
	train_model = build_keras_model()

	tf.contrib.quantize.create_training_graph(input_graph=train_graph, quant_delay=100)
	train_sess.run(tf.global_variables_initializer())

	train_model.compile(
		optimizer='sgd',
		loss='mean_squared_error'
	)
	train_model.fit(train_input, train_truth, epochs=250)

	saver = tf.train.Saver()
	saver.save(train_sess, 'linear.ckpt')
```

Afterwards, I create an eval graph and freeze the model with the help of this script:

```
import tensorflow as tf
from tensorflow import keras
import numpy as np

def build_keras_model():
	return keras.models.Sequential([
		keras.layers.Dense(units=1, input_shape=[1]),
	])

# eval
eval_graph = tf.Graph()
eval_sess = tf.Session(graph=eval_graph)

keras.backend.set_session(eval_sess)

with eval_graph.as_default():
	keras.backend.set_learning_phase(0)
	eval_model = build_keras_model()

	tf.contrib.quantize.create_eval_graph(input_graph=eval_graph)

	eval_graph_def = eval_graph.as_graph_def()
	saver = tf.train.Saver()
	saver.restore(eval_sess, 'linear.ckpt')

	frozen_graph_def = tf.graph_util.convert_variables_to_constants(
		eval_sess,
		eval_graph_def,
		[eval_model.output.op.name]
	)

	with open('frozen_model.pb', 'wb') as f:
		f.write(frozen_graph_def.SerializeToString())
```

When I try to convert the frozen graph to a tflite model, using the following command

```
tflite_convert \
--output_file=model.tflite \
--graph_def_file=frozen_model.pb \
--inference_type=QUANTIZED_UINT8 \
--input_arrays=dense_input \
--output_arrays=dense/BiasAdd \
--mean_values=0 \
--std_dev_values=255
```
I run into an error:

```
Traceback (most recent call last):
  File "/usr/local/bin/tflite_convert", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/lite/python/tflite_convert.py", line 503, in main
    app.run(main=run_main, argv=sys.argv[:1])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/lite/python/tflite_convert.py", line 499, in run_main
    _convert_tf1_model(tflite_flags)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/lite/python/tflite_convert.py", line 193, in _convert_tf1_model
    output_data = converter.convert()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/lite/python/lite.py", line 898, in convert
    **converter_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/lite/python/convert.py", line 404, in toco_convert_impl
    input_data.SerializeToString())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/lite/python/convert.py", line 172, in toco_convert_protos
    "TOCO failed. See console for info.\n%s\n%s\n" % (stdout, stderr))
tensorflow.lite.python.convert.ConverterError: TOCO failed. See console for info.
2019-07-11 15:54:26.995204: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 7 operators, 12 arrays (0 quantized)
2019-07-11 15:54:26.995314: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 7 operators, 12 arrays (0 quantized)
2019-07-11 15:54:26.995465: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 1: 2 operators, 5 arrays (1 quantized)
2019-07-11 15:54:26.995497: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before pre-quantization graph transformations: 2 operators, 5 arrays (1 quantized)
2019-07-11 15:54:26.995512: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Group bidirectional sequence lstm/rnn: 2 operators, 5 arrays (1 quantized)
2019-07-11 15:54:26.995528: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before quantization graph transformations: 2 operators, 5 arrays (1 quantized)
2019-07-11 15:54:26.995558: F tensorflow/lite/toco/graph_transformations/quantize.cc:149] Array dense/BiasAdd does not have MinMax information, and is not a constant array. Cannot proceed with quantization.
Aborted (core dumped)
```

This error vanishes, when I provide two additional command line arguments with any value:
`--default_ranges_min=-128 --default_ranges_max=127`

First and foremost, shouldn't a simple model like this be convertible without these args? Also, I am still only guessing on how to determine the default ranges as well as the values for mean_values and std_dev_values. This should be added to the documentation for clarity.

**Comment by rmothukuru** [comment]
@DocDriven ,
The arguments, `--default_ranges_min and --default_ranges_max` are required as per the documentation provided in this [Tensorflow Website](https://www.tensorflow.org/lite/convert/cmdline_examples#use_dummy-quantization_to_try_out_quantized_inference_on_a_float_graph_)

**Comment by rmothukuru** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by DocDriven** [comment]
@rmothukuru 
I have read the docs, but they do not answer my questions. Is there any detailed documentation what these arguments are doing exactly?

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
