### ISSUE TITLE
‘scatter_nd_update’ doesn't work with string

### ISSUE THREAD

**Issue by SeekerYb** [tensorflow/tensorflow#30642]
**System information**
I Reproduced this issue in newest [tensorflow official docker image](https://hub.docker.com/r/tensorflow/tensorflow).
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Ubuntu 18.04
- TensorFlow installed from (source or binary):binary
- TensorFlow version (use command below):1.14.0
- Python version:2.7.15+

**Describe the current behavior**
In my model, I need to maintain an extremely long 2-D variable tensor，which has several columns and many rows, and its dtype is string. In every training step, I need to update only several individual rows of that tensor. [tf.scatter_nd_update](https://www.tensorflow.org/api_docs/python/tf/scatter_nd_update) meets my requirements perfectly,
except that it doesn't work with string in fact. As a contrast,  [tf.scatter_nd](https://www.tensorflow.org/api_docs/python/tf/scatter_nd) does work. Since the document doesn't mention that `ref` can't be string, I think it may be a bug.

**Describe the expected behavior**
I hope `tf.scatter_nd_update` support string `ref`,and I really need this feature in my project. So if it can't be fixed quickly, **any walk-around suggestions (include modify some source code) is also welcome.**  

**Code to reproduce the issue**
```
import tensorflow as tf
ref = tf.Variable([‘qq’,’ww’,’ee’,’rr’,’’,’’,’’,’’])
indices = tf.constant([[4], [3], [1] ,[7]])
updates = tf.constant(['aa', 'dd', 'cc', 'bb'])
update = tf.scatter_nd_update(ref, indices, updates)
with tf.Session() as sess:
    sess.run(tf.initialize_all_variables())
    print(sess.run(update))
```

**Other info / logs**
```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'ScatterNdUpdate' used by node ScatterNdUpdate (defined at <stdin>:1) with these attrs: [_class=["loc:@Variable"], use_locking=true, Tindices=DT_INT32, T=DT_STRING]
Registered devices: [CPU, XLA_CPU]
Registered kernels:
  device='CPU'; T in [DT_BOOL]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_BOOL]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_COMPLEX128]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_COMPLEX128]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_COMPLEX64]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_COMPLEX64]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_DOUBLE]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_DOUBLE]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_FLOAT]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_FLOAT]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_BFLOAT16]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_BFLOAT16]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_HALF]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_HALF]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_INT8]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_INT8]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_UINT8]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_UINT8]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_INT16]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_INT16]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_UINT16]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_UINT16]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_INT32]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_INT32]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_INT64]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_INT64]; Tindices in [DT_INT32]

	 [[ScatterNdUpdate]]
```

**Comment by anush-o** [comment]
Could reproduce the issue with TF version 1.14.Thanks
