### ISSUE TITLE
What's the state of RNNs and tf.lite for Tensorflow 2.0?

### ISSUE THREAD

**Issue by BeWe11** [tensorflow/tensorflow#30754]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS 10.14.5
- TensorFlow installed from (source or binary): binary
- TensorFlow version (or github SHA if from source): 2.0.0-beta1

**Provide the text output from tflite_convert**

```
Traceback (most recent call last):
  File "test_rnn_tflite.py", line 12, in <module>
    tflite_model = converter.convert()
  File "/Users/ben/miniconda3/envs/wakeword/lib/python3.6/site-packages/tensorflow/lite/python/lite.py", line 392, in convert                                                                                                  
    **converter_kwargs)
  File "/Users/ben/miniconda3/envs/wakeword/lib/python3.6/site-packages/tensorflow/lite/python/convert.py", line 404, in toco_convert_impl                                                                                     
    input_data.SerializeToString())
  File "/Users/ben/miniconda3/envs/wakeword/lib/python3.6/site-packages/tensorflow/lite/python/convert.py", line 172, in toco_convert_protos                                                                                   
    "TOCO failed. See console for info.\n%s\n%s\n" % (stdout, stderr))
tensorflow.lite.python.convert.ConverterError: TOCO failed. See console for info.
2019-07-16 14:25:07.645148: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20                                                                                                       
2019-07-16 14:25:07.645184: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20                                                                                                       
2019-07-16 14:25:07.645191: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20                                                                                                       
2019-07-16 14:25:07.645280: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: StatefulPartitionedCall                                                                                        
2019-07-16 14:25:07.653916: F tensorflow/lite/toco/import_tensorflow.cc:114] Check failed: attr.value_case() == AttrValue::kType (1 vs. 6)                                                                                     
Fatal Python error: Aborted

Current thread 0x00000001104045c0 (most recent call first):
  File "/Users/ben/miniconda3/envs/wakeword/lib/python3.6/site-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 33 in execute                                                                                   
  File "/Users/ben/miniconda3/envs/wakeword/lib/python3.6/site-packages/absl/app.py", line 251 in _run_main
  File "/Users/ben/miniconda3/envs/wakeword/lib/python3.6/site-packages/absl/app.py", line 300 in run
  File "/Users/ben/miniconda3/envs/wakeword/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 40 in run                                                                                                     
  File "/Users/ben/miniconda3/envs/wakeword/lib/python3.6/site-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 59 in main                                                                                      
  File "/Users/ben/miniconda3/envs/wakeword/bin/toco_from_protos", line 10 in <module>
```

Code to reproduce:
```python
import tensorflow as tf

model = tf.keras.Sequential(
    [tf.keras.layers.LSTM(10, input_shape=(16000, 40))]
)
model.build()

converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.target_spec.supported_ops = set(
    [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
)

tflite_model = converter.convert()
```

**Any other info / logs**

There are several issues about support of RNNs in tf.lite, most of them are rather old and about TF 1.x. What's the current state of supporting RNNs in tf.lite for TF 2.x?

**Comment by gargn** [comment]
There is currently limited support for LSTMs in TFLite. The documented path is available [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/experimental/examples/lstm/g3doc/README.md). We are working on improving our support of control flow based operations and models. We will update documentation and the GitHub issues as we make progress on this issue.

**Comment by haozha111** [comment]
Hi,

You can try to convert the keras RNN model using the new TF Lite converter now:

Try set converter.experimental_new_converter = True and then convert.

A known issue is that if the time step is very large, like 16000 in your example, the converted lstm could be slow. But it should generally be fine for small time steps. We are currently working on improving its performance.

Thanks.

**Comment by jvishnuvardhan** [comment]
@BeWe11 Is this still an issue? As mentioned by @haozha111, I tried `converter.experimental_new_converter = True`  and your code runs without any error. Please take a look at the [gist here](https://colab.sandbox.google.com/gist/jvishnuvardhan/fd8f60999881add469b1713d2b715ac9/untitled638.ipynb).

Please close this issue if it was resolved for you. Thanks!

**Comment by mattc-eostar** [comment]
@haozha111 
Are complex dtypes planned to be supported in the experimental converter? using nightly 1108 build and it is throwing an error. This is super useful for MFCC calculations.

```python
sample_rate = 16000.0
# A Tensor of [batch_size, num_samples] mono PCM samples in the range [-1, 1].
pcm = tf.compat.v1.placeholder(tf.float32, [None, None])

# A 1024-point STFT with frames of 64 ms and 75% overlap.
stfts = tf.signal.stft(pcm, frame_length=1024, frame_step=256,
                       fft_length=1024)
spectrograms = tf.abs(stfts)

# Warp the linear scale spectrograms into the mel-scale.
num_spectrogram_bins = stfts.shape[-1].value
lower_edge_hertz, upper_edge_hertz, num_mel_bins = 80.0, 7600.0, 80
linear_to_mel_weight_matrix = tf.signal.linear_to_mel_weight_matrix(
  num_mel_bins, num_spectrogram_bins, sample_rate, lower_edge_hertz,
  upper_edge_hertz)
mel_spectrograms = tf.tensordot(
  spectrograms, linear_to_mel_weight_matrix, 1)
mel_spectrograms.set_shape(spectrograms.shape[:-1].concatenate(
  linear_to_mel_weight_matrix.shape[-1:]))

# Compute a stabilized log to get log-magnitude mel-scale spectrograms.
log_mel_spectrograms = tf.math.log(mel_spectrograms + 1e-6)

# Compute MFCCs from log_mel_spectrograms and take the first 13.
mfccs = tf.signal.mfccs_from_log_mel_spectrograms(
  log_mel_spectrograms)[..., :13]
```

**Comment by jvishnuvardhan** [comment]
@mattc-eostar Can you please a new issue and provide a simple standalone code to reproduce the issue? Thanks!

**Comment by mattc-eostar** [comment]
#34324 Created here. Thanks!

**Comment by jvishnuvardhan** [comment]
I am closing this issue as it was resolved with the new converter `converter.experimental_new_converter = True`. Please feel free to reopen the issue if it persists again. Thanks!
