### ISSUE TITLE
IOError: [Errno socket error] [Errno 60] Operation timed out

### ISSUE THREAD

**Issue by Conxz** [tensorflow/tensorflow#308]
I used tensorflow with Mac. But when running the code convolutional.py, there is some unexpected error.

(cinos)➜  ~  python anaconda/envs/cinos/lib/python2.7/site-packages/tensorflow/models/image/mnist/convolutional.py

Traceback (most recent call last):
  File "anaconda/envs/cinos/lib/python2.7/site-packages/tensorflow/models/image/mnist/convolutional.py", line 270, in <module>
    tf.app.run()
  File "/Users/kk/anaconda/envs/cinos/lib/python2.7/site-packages/tensorflow/python/platform/default/_app.py", line 11, in run
    sys.exit(main(sys.argv))
  File "anaconda/envs/cinos/lib/python2.7/site-packages/tensorflow/models/image/mnist/convolutional.py", line 103, in main
    test_data_filename = maybe_download('t10k-images-idx3-ubyte.gz')
  File "anaconda/envs/cinos/lib/python2.7/site-packages/tensorflow/models/image/mnist/convolutional.py", line 39, in maybe_download
    filepath, _ = urllib.urlretrieve(SOURCE_URL + filename, filepath)
  File "/Users/kk/anaconda/envs/cinos/lib/python2.7/urllib.py", line 98, in urlretrieve
    return opener.retrieve(url, filename, reporthook, data)
  File "/Users/kk/anaconda/envs/cinos/lib/python2.7/urllib.py", line 245, in retrieve
    fp = self.open(url, data)
  File "/Users/kk/anaconda/envs/cinos/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/Users/kk/anaconda/envs/cinos/lib/python2.7/urllib.py", line 351, in open_http
    errcode, errmsg, headers = h.getreply()
  File "/Users/kk/anaconda/envs/cinos/lib/python2.7/httplib.py", line 1207, in getreply
    response = self._conn.getresponse()
  File "/Users/kk/anaconda/envs/cinos/lib/python2.7/httplib.py", line 1132, in getresponse
    response.begin()
  File "/Users/kk/anaconda/envs/cinos/lib/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/Users/kk/anaconda/envs/cinos/lib/python2.7/httplib.py", line 409, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/Users/kk/anaconda/envs/cinos/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
IOError: [Errno socket error] [Errno 60] Operation timed out

**Comment by vrv** [comment]
Most likely a transient issue, related to https://github.com/tensorflow/tensorflow/issues/209
