### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'init_scope'

### ISSUE THREAD

**Issue by VitalieStirbu** [tensorflow/tensorflow#30810]
**System information**

**Have I written custom code (as opposed to using a stock example script provided in TensorFlow):**
 -No
**OS Platform and Distribution (e.g., Linux Ubuntu 16.04):**
-Windows
**Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:**
-No
**TensorFlow installed from (source or binary):**
-Pip
**TensorFlow version (use command below):** 
-Tensorflow-gpu 1.9.0
**Python version:**
-Python 3.6.6
**CUDA/cuDNN version:**
-CUDA 10.0.0
-cuDNN 7.6.1
**GPU model and memory:**
-NVIDIA GeForce GTX 1070 Ti  (8gb dedicated)

**Describe the current behavior**
 - Try to train a model based on  faster_rcnn_nass_coco.config. Get an  - error AttributeError: module 'tensorflow' has no attribute 'init_scope'.
Same code works if I use ssd_mobilenet_v1_pets.config

**Code to reproduce the issue**
`python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_nass_coco.config`

**Other info / logs**
_Traceback (most recent call last):
  File "train.py", line 184, in <module>
    tf.app.run()
  File "C:\Users\Vitalie\Anaconda3\envs\python-cvcourse\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "C:\Users\Vitalie\Anaconda3\envs\python-cvcourse\lib\site-packages\tensorflow\python\util\deprecation.py", line 250, in new_func
    return func(*args, **kwargs)
  File "train.py", line 180, in main
    graph_hook_fn=graph_rewriter_fn)
  File "C:\Users\Vitalie\Downloads\models-master\research\object_detection\legacy\trainer.py", line 291, in train
    clones = model_deploy.create_clones(deploy_config, model_fn, [input_queue])
  File "C:\Users\Vitalie\Downloads\models-master\research\slim\deployment\model_deploy.py", line 193, in create_clones
    outputs = model_fn(*args, **kwargs)
  File "C:\Users\Vitalie\Downloads\models-master\research\object_detection\legacy\trainer.py", line 204, in _create_losses
    prediction_dict = detection_model.predict(images, true_image_shapes)
  File "C:\Users\Vitalie\Downloads\models-master\research\object_detection\meta_architectures\faster_rcnn_meta_arch.py", line 821, in predict
    prediction_dict = self._predict_first_stage(preprocessed_inputs)
  File "C:\Users\Vitalie\Downloads\models-master\research\object_detection\meta_architectures\faster_rcnn_meta_arch.py", line 872, in _predict_first_stage
    image_shape) = self._extract_rpn_feature_maps(preprocessed_inputs)
  File "C:\Users\Vitalie\Downloads\models-master\research\object_detection\meta_architectures\faster_rcnn_meta_arch.py", line 1250, in _extract_rpn_feature_maps
    feature_map_shape[2])]))
  File "C:\Users\Vitalie\Downloads\models-master\research\object_detection\core\anchor_generator.py", line 103, in generate
    anchors_list = self._generate(feature_map_shape_list, **params)
  File "C:\Users\Vitalie\Downloads\models-master\research\object_detection\anchor_generators\grid_anchor_generator.py", line 111, in _generate
    with tf.init_scope():
AttributeError: module 'tensorflow' has no attribute 'init_scope'_

**Comment by sidharthskumar** [comment]
how did solve?

**Comment by anush-o** [comment]
@VitalieStirbu ,
In order to expedite the trouble-shooting process, please provide complete code snippet to reproduce the issue reported here. Thanks!

**Comment by VitalieStirbu** [comment]
@anush-o,
What code snippet? train.py is the file from /models/research/object_detection/legacy folder. I didn't make any changes.  In faster_rcnn_nass_coco.config I changed only NUM_CLASSES to 1 and the path to my data.
I tried to follow the steps from this <a href="https://www.youtube.com/watch?v=K_mFnvzyLvc&list=PLQVvvaa0QuDcNK5GeCQnxYnSSaar2tpku&index=3">video</a>

**Comment by alfdnl** [comment]
I have the same Error

**System information**

**Have I written custom code (as opposed to using a stock example script provided in TensorFlow):**
-No
**OS Platform and Distribution (e.g., Linux Ubuntu 16.04):**
-Windows 10
**Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:**
-No
**TensorFlow installed from (source or binary):**
-Pip
**TensorFlow version (use command below):**
-Tensorflow 1.5.0
**Python version:**
-Python 3.6.8
**CUDA/cuDNN version:**
-No
**GPU model and memory:**
-No

Describe the current behavior

Try to train a model based on faster_rcnn_nass_coco.config. Get an - error AttributeError: module 'tensorflow' has no attribute 'init_scope'.
Same code works if I use ssd_mobilenet_v1_pets.config
Code to reproduce the issue
python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_nass_coco.config

Other info / logs
WARNING:tensorflow:Forced number of epochs for all eval validations to be 1.
WARNING:tensorflow:Expected number of evaluation epochs is 1, but instead encountered `eval_on_train_input_config.num_epochs` = 0. Overwriting `num_epochs` to 1.
WARNING:tensorflow:Using temporary folder as model directory: C:\Users\aliff\AppData\Local\Temp\tmp1_qeig4v
WARNING:tensorflow:Estimator's model_fn (<function create_model_fn.<locals>.model_fn at 0x000001FAB28D5158>) includes params argument, but params are not passed to Estimator.
WARNING:tensorflow:num_readers has been reduced to 1 to match input file shards.
Traceback (most recent call last):
  File "model_main.py", line 109, in <module>
    tf.app.run()
  File "C:\Users\aliff\Desktop\ObjectIdentifier\env\lib\site-packages\tensorflow\python\platform\app.py", line 124, in run
    _sys.exit(main(argv))
  File "model_main.py", line 105, in main
    tf.estimator.train_and_evaluate(estimator, train_spec, eval_specs[0])
  File "C:\Users\aliff\Desktop\ObjectIdentifier\env\lib\site-packages\tensorflow\python\estimator\training.py", line 432, in train_and_evaluate
    executor.run_local()
  File "C:\Users\aliff\Desktop\ObjectIdentifier\env\lib\site-packages\tensorflow\python\estimator\training.py", line 611, in run_local
    hooks=train_hooks)
  File "C:\Users\aliff\Desktop\ObjectIdentifier\env\lib\site-packages\tensorflow\python\estimator\estimator.py", line 314, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "C:\Users\aliff\Desktop\ObjectIdentifier\env\lib\site-packages\tensorflow\python\estimator\estimator.py", line 743, in _train_model
    features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
  File "C:\Users\aliff\Desktop\ObjectIdentifier\env\lib\site-packages\tensorflow\python\estimator\estimator.py", line 725, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "C:\Users\aliff\Desktop\models-master\models-master\research\object_detection\model_lib.py", line 301, in model_fn
    features[fields.InputDataFields.true_image_shape])
  File "C:\Users\aliff\Desktop\models-master\models-master\research\object_detection\meta_architectures\faster_rcnn_meta_arch.py", line 822, in predict
    prediction_dict = self._predict_first_stage(preprocessed_inputs)
  File "C:\Users\aliff\Desktop\models-master\models-master\research\object_detection\meta_architectures\faster_rcnn_meta_arch.py", line 873, in _predict_first_stage
    image_shape) = self._extract_rpn_feature_maps(preprocessed_inputs)
  File "C:\Users\aliff\Desktop\models-master\models-master\research\object_detection\meta_architectures\faster_rcnn_meta_arch.py", line 1252, in _extract_rpn_feature_maps
    feature_map_shape[2])]))
  File "C:\Users\aliff\Desktop\models-master\models-master\research\object_detection\core\anchor_generator.py", line 108, in generate
    anchors_list = self._generate(feature_map_shape_list, **params)
  File "C:\Users\aliff\Desktop\models-master\models-master\research\object_detection\anchor_generators\grid_anchor_generator.py", line 111, in _generate
    with tf.init_scope():
AttributeError: module 'tensorflow' has no attribute 'init_scope'

**Comment by aidenmj** [comment]
I'm having the same error, 

(tensorflow_gpu) C:\TensorFlow\workspace\training_demo>python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_inception_v2_pets.config
WARNING:tensorflow:From C:\Users\THIS PC\Anaconda3\envs\tensorflow_gpu\lib\site-packages\tensorflow\python\platform\app.py:125: main (from __main__) is deprecated and will be removed in a future version.
Instructions for updating:
Use object_detection/model_main.py.
WARNING:tensorflow:From C:\TensorFlow\models\research\object_detection\legacy\trainer.py:266: create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.create_global_step
WARNING:tensorflow:num_readers has been reduced to 1 to match input file shards.
Traceback (most recent call last):
  File "train.py", line 184, in <module>
    tf.app.run()
  File "C:\Users\THIS PC\Anaconda3\envs\tensorflow_gpu\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "C:\Users\THIS PC\Anaconda3\envs\tensorflow_gpu\lib\site-packages\tensorflow\python\util\deprecation.py", line 250, in new_func
    return func(*args, **kwargs)
  File "train.py", line 180, in main
    graph_hook_fn=graph_rewriter_fn)
  File "C:\TensorFlow\models\research\object_detection\legacy\trainer.py", line 291, in train
    clones = model_deploy.create_clones(deploy_config, model_fn, [input_queue])
  File "C:\TensorFlow\models\research\slim\deployment\model_deploy.py", line 193, in create_clones
    outputs = model_fn(*args, **kwargs)
  File "C:\TensorFlow\models\research\object_detection\legacy\trainer.py", line 204, in _create_losses
    prediction_dict = detection_model.predict(images, true_image_shapes)
  File "C:\TensorFlow\models\research\object_detection\meta_architectures\faster_rcnn_meta_arch.py", line 822, in predict
    prediction_dict = self._predict_first_stage(preprocessed_inputs)
  File "C:\TensorFlow\models\research\object_detection\meta_architectures\faster_rcnn_meta_arch.py", line 873, in _predict_first_stage
    image_shape) = self._extract_rpn_feature_maps(preprocessed_inputs)
  File "C:\TensorFlow\models\research\object_detection\meta_architectures\faster_rcnn_meta_arch.py", line 1252, in _extract_rpn_feature_maps
    feature_map_shape[2])]))
  File "C:\TensorFlow\models\research\object_detection\core\anchor_generator.py", line 108, in generate
    anchors_list = self._generate(feature_map_shape_list, **params)
  File "C:\TensorFlow\models\research\object_detection\anchor_generators\grid_anchor_generator.py", line 111, in _generate
    with tf.init_scope():
AttributeError: module 'tensorflow' has no attribute 'init_scope'

help me ASAP,

**Comment by jvishnuvardhan** [comment]
@VitalieStirbu This is more related to `TF models` repository. Please post it in https://github.com/tensorflow/models/issues. Thanks!

**Comment by VitalieStirbu** [comment]
@aidenmj ,  @alfdnl  this issue was resolved, please check this <a href="https://github.com/tensorflow/hub/issues/324#issuecomment-513847409">link</a>

**Comment by 0julio0** [comment]
> how did solve?
I solved delete the lines 174 till 178 of ../object_detection/utils/variables_helper.py


def get_global_variables_safely():
  """If not executing eagerly, returns tf.global_variables().

  Raises a ValueError if eager execution is enabled,
  because the variables are not tracked when executing eagerly.

  If executing eagerly, use a Keras model's .variables property instead.

  Returns:
    The result of tf.global_variables()
  """
  # with tf.init_scope():
  #   if tf.executing_eagerly():
  #     raise ValueError("Global variables collection is not tracked when "
  #                      "executing eagerly. Use a Keras model's `.variables` "
  #                      "attribute instead.")
  return tf.global_variables()

**Comment by ChenSi521** [comment]
I solved this problem in models/research/object_detection/export_inference_graph.py with tf1.8. I add these codes in the head of object_detection/anchor_genetators/grid_anchor_generator.py:

from tensorflow.python.util.tf_export import tf_export
from tensorflow.python.util import tf_contextlib
from tensorflow.python.eager import context
from tensorflow.python.eager import tape

@tf_export("init_scope")
@tf_contextlib.contextmanager
def init_scope():
if context.executing_eagerly():
    with tape.stop_recording():
        yield
else:
    default_graph = tf.get_default_graph()
    scope = default_graph.get_name_scope()
    if scope and scope[-1] != "/"
        scope = scope + "/"
    inner_device_stack = default_graph._device_function_stack

    outer_context = None
    for stack_entry in reversed(context.context().context_switches.stack):
        if not stack_entry.is_building_function:
            outer_context = stack_entry.enter_context_fn
            break

    if outer_context is None:
        outer_context = tf.Graph().as_default
    if outer_context is None:
        raise RuntimeError("All graphs are building functions, and no eager context was previously active")
    outer_graph = None
    outer_device_stack = None
    try:
        with outer_context(), tf.name_scope(scope), tf.control_dependencies(None), tape.stop_recording():
            if not context.executing_eagerly():
                outer_graph = tf.get_default_graph()
                outer_device_stack = outer_graph._device_function_stack
                outer_graph._device_function_stack = inner_device_stack
            yield
    finally:
        if outer_graph is not None:
            outer_graph._device_function_stack = outer_device_stack

I can't copy code from computer of company, so, i press every character by key board. Maybe it will have some mistakes in format.
I have verified that these modified codes is right in  ssd_resnet50_v1_fpn_shared_box_predictor_640x640_coco14_sync_2018_07_03 pretrained model.
If you have find some questions of this method, please contract me by my github.

**Comment by haseebi** [comment]
at lease give correct indent code

**Comment by anirudh2324** [comment]
(object_dection) C:\Users\pabhi\OneDrive\Desktop\object\workspace\training_demo>python export_inference_graph.py --input_type image_tensor --pipeline_config_path training/pipeline.config --trained_checkpoint_prefix training/model.ckpt-936 --output_directory inference_graph
C:\Users\pabhi\Anaconda3\envs\object_dection\lib\site-packages\tensorflow\python\framework\dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\pabhi\Anaconda3\envs\object_dection\lib\site-packages\tensorflow\python\framework\dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\pabhi\Anaconda3\envs\object_dection\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\pabhi\Anaconda3\envs\object_dection\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Users\pabhi\Anaconda3\envs\object_dection\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Users\pabhi\Anaconda3\envs\object_dection\lib\site-packages\tensorflow\python\framework\dtypes.py:532: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "export_inference_graph.py", line 162, in <module>
    tf.app.run()
  File "C:\Users\pabhi\Anaconda3\envs\object_dection\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "export_inference_graph.py", line 158, in main
    write_inference_graph=FLAGS.write_inference_graph)
  File "C:\Users\pabhi\OneDrive\Desktop\object\models\research\object_detection\exporter.py", line 510, in export_inference_graph
    write_inference_graph=write_inference_graph)
  File "C:\Users\pabhi\OneDrive\Desktop\object\models\research\object_detection\exporter.py", line 413, in _export_inference_graph
    graph_hook_fn=graph_hook_fn)
  File "C:\Users\pabhi\OneDrive\Desktop\object\models\research\object_detection\exporter.py", line 380, in build_detection_graph
    output_collection_name=output_collection_name)
  File "C:\Users\pabhi\OneDrive\Desktop\object\models\research\object_detection\exporter.py", line 356, in _get_outputs_from_inputs
    output_tensors, true_image_shapes)
  File "C:\Users\pabhi\OneDrive\Desktop\object\models\research\object_detection\meta_architectures\ssd_meta_arch.py", line 783, in postprocess
    with tf.init_scope():
AttributeError: module 'tensorflow' has no attribute 'init_scope'

**Comment by anirudh2324** [comment]
can any one solve this

**Comment by haseebi** [comment]
what is your goal TensorFlow object detection API or image classification?

>

**Comment by archithadge** [comment]
@ChenSi521 Can you please provide step-by-step explaination?

**Comment by superbelll** [comment]
> @ChenSi521 Can you please provide step-by-step explaination?

did u solve it ?

**Comment by archithadge** [comment]
Yes but not by the way you mentioned, I just installed Tensorflow 1.12 and it solved.
