### ISSUE TITLE
ValueError in tensorflow/examples/skflow/mnist_weights.py

### ISSUE THREAD

**Issue by tcfuji** [tensorflow/tensorflow#3083]
### Environment info
OS: OS X 10.11.5

Cuda version: 7.5.30

cuDNN version: v5.1rc (or 5103)

Tensorflow version: 0.9.0rc0

Installed with cuda support using these [instructions](https://medium.com/@fabmilo/how-to-compile-tensorflow-with-cuda-support-on-osx-fd27108e27e1#.mf4zcsmu3).

### Steps to reproduce:

1. cd tensorflow/examples/skflow/
2. $ python mnist_weights.py

### Output:
```
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.7.5.dylib locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.5.dylib locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.7.5.dylib locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.dylib locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.7.5.dylib locally
Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
WARNING:tensorflow:TensorFlowLinearClassifier class is deprecated. Please consider using LinearClassifier as an alternative.
Traceback (most recent call last):
  File "mnist_weights.py", line 37, in <module>
    classifier.fit(mnist.train.images, mnist.train.labels)
  File "/Users/tcf/.virtualenvs/dnn/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/base.py", line 458, in fit
    batch_size=batch_size or self.batch_size, monitors=monitors)
  File "/Users/tcf/.virtualenvs/dnn/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 182, in fit
    monitors=monitors)
  File "/Users/tcf/.virtualenvs/dnn/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 449, in _train_model
    train_op, loss_op = self._get_train_ops(features, targets)
  File "/Users/tcf/.virtualenvs/dnn/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/linear.py", line 97, in _get_train_ops
    return super(LinearClassifier, self)._get_train_ops(features, targets)
  File "/Users/tcf/.virtualenvs/dnn/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/dnn_linear_combined.py", line 158, in _get_train_ops
    targets, self._get_weight_tensor(features))]):
  File "/Users/tcf/.virtualenvs/dnn/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/dnn_linear_combined.py", line 282, in _centered_bias_step
    loss = self._loss(logits, targets, weight_tensor)
  File "/Users/tcf/.virtualenvs/dnn/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/dnn_linear_combined.py", line 316, in _loss
    loss_vec = self._loss_vec(logits, target)
  File "/Users/tcf/.virtualenvs/dnn/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/dnn_linear_combined.py", line 510, in _loss_vec
    "Instead got %s." % target.dtype)
ValueError: Target's dtype should be int32, int64 or compatible. Instead got <dtype: 'uint8'>.
```
### What have I tried?

I used the ndarray method `.astype` to change the type appropriately. That is, I replaced `mnist.train.images` with `mnist.train.images.astype(np.float32)` and `mnist.train.labels` with `mnist.train.images.astype(int)`.

**Comment by rmlarsen** [comment]
To sum up discussion with @martinwicke on the proposed PR: "This is an outdated example, it's in line to be updated, just has to wait its turn. If the new [tflearn] code cannot handle uint8s it should."

@ilblackdragon will you address this issue or assign to whoever will?

**Comment by ilblackdragon** [comment]
This example was removed recently. Probably we will update when we write new example :)
