### ISSUE TITLE
2.0.0-beta1 no op for reassign variable to different shape (e.g. a validate_shape=False option)

### ISSUE THREAD

**Issue by OlavHN** [tensorflow/tensorflow#30840]
```
import tensorflow as tf

print(tf.__version__)
tf.random.set_seed(0)

v = tf.Variable(
    tf.random_normal_initializer()(shape=(10,)),
    validate_shape=False) # Only for first initialization, not for reinitialization

v2 = tf.random.normal((5,))

print(v)

# tf.compat.v1.assign(v, v2, validate_shape=False)
v.assign(v2)

print(v)
```

Outputs:

```
2.0.0-beta1
2019-07-18 14:41:15.418014: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
<tf.Variable 'Variable:0' shape=(10,) dtype=float32, numpy=
array([ 0.07555313,  0.0211461 , -0.02098475, -0.05180186, -0.06184139,
        0.02351365, -0.00069874,  0.05944292,  0.03012667,  0.02998556],
      dtype=float32)>
Traceback (most recent call last):
  File "test.py", line 15, in <module>
    v.assign(v2)
  File "/Users/olanymoe/anaconda3/envs/tf2/lib/python3.5/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 1145, in assign
    self._shape.assert_is_compatible_with(value_tensor.shape)
  File "/Users/olanymoe/anaconda3/envs/tf2/lib/python3.5/site-packages/tensorflow/python/framework/tensor_shape.py", line 1110, in assert_is_compatible_with
    raise ValueError("Shapes %s and %s are incompatible" % (self, other))
ValueError: Shapes (10,) and (5,) are incompatible
```

Similarly, the `compat.v1` seems to ignore the `validate_shape` argument for variables in 2.0 ( https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/state_ops.py#L228 ).

I'm working on a model which is being served as a saved_model. Is there a way of changing shapes of variables in 2.0? In 1.14 it worked using assign ops with `validate_shape=False`. The 2.0 documentation seems to hint at this functionality, but I cannot find any compatible ops:

> If you want to change the shape of a variable later you have to use an assign Op with validate_shape=False.

https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/Variable

**Comment by OlavHN** [comment]
I found this similar issue: https://github.com/tensorflow/tensorflow/issues/26104 with instructions that solved my issues:

Explicitly setting shape information to `None`

```
v = tf.Variable(
    tf.random_normal_initializer()(shape=(10,)),
    shape=tf.TensorShape(None))
```

gives expected behaviour.
