### ISSUE TITLE
Can not Exporting a GraphDef from file

### ISSUE THREAD

**Issue by wendy518** [tensorflow/tensorflow#30851]
Hi, i used code provided in https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/convert/cmdline_examples.md. 

Convert a TensorFlow GraphDef 

```
curl https://storage.googleapis.com/download.tensorflow.org/models/mobilenet_v1_0.50_128_frozen.tgz \
  | tar xzv -C /tmp
tflite_convert \
  --output_file=/tmp/foo.tflite \
  --graph_def_file=/tmp/mobilenet_v1_0.50_128/frozen_graph.pb \
  --input_arrays=input \
  --output_arrays=MobilenetV1/Predictions/Reshape_1**
```

### error
 Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-07-18 17:14:34.558992: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2494150000 Hz
2019-07-18 17:14:34.559779: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x560a0f59d790 executing computations on platform Host. Devices:
2019-07-18 17:14:34.559868: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
2019-07-18 17:14:35.103189: I tensorflow/core/grappler/devices.cc:60] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0 (Note: TensorFlow was not compiled with CUDA support)
2019-07-18 17:14:35.103362: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2019-07-18 17:14:35.426148: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:716] Optimization results for grappler item: graph_to_optimize
2019-07-18 17:14:35.426184: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   constant folding: Graph size after: 174 nodes (-381), 173 edges (-408), time = 270.209ms.
2019-07-18 17:14:35.426195: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   constant folding: Graph size after: 174 nodes (0), 173 edges (0), time = 14.101ms.
Traceback (most recent call last):
  File "/home/wangxy/miniconda3/envs/ml/bin/tflite_convert", line 10, in <module>
    sys.exit(main())
  File "/home/wangxy/miniconda3/envs/ml/lib/python3.6/site-packages/tensorflow_core/lite/python/tflite_convert.py", line 515, in main
    app.run(main=run_main, argv=sys.argv[:1])
  File "/home/wangxy/miniconda3/envs/ml/lib/python3.6/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/wangxy/miniconda3/envs/ml/lib/python3.6/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/wangxy/miniconda3/envs/ml/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/home/wangxy/miniconda3/envs/ml/lib/python3.6/site-packages/tensorflow_core/lite/python/tflite_convert.py", line 511, in run_main
    _convert_tf1_model(tflite_flags)
  File "/home/wangxy/miniconda3/envs/ml/lib/python3.6/site-packages/tensorflow_core/lite/python/tflite_convert.py", line 199, in _convert_tf1_model
    output_data = converter.convert()
  File "/home/wangxy/miniconda3/envs/ml/lib/python3.6/site-packages/tensorflow_core/lite/python/lite.py", line 983, in convert
    **converter_kwargs)
  File "/home/wangxy/miniconda3/envs/ml/lib/python3.6/site-packages/tensorflow_core/lite/python/convert.py", line 437, in toco_convert_impl
    enable_mlir_converter=enable_mlir_converter)
  File "/home/wangxy/miniconda3/envs/ml/lib/python3.6/site-packages/tensorflow_core/lite/python/convert.py", line 155, in toco_convert_protos
    fp_debug.write(debug_info_str)
  File "/home/wangxy/miniconda3/envs/ml/lib/python3.6/tempfile.py", line 485, in func_wrapper
    return func(*args, **kwargs)
TypeError: a bytes-like object is required, not 'str'
Exception ignored in: <bound method _TensorCacheDeleter.__del__ of <tensorflow.python.eager.context._TensorCacheDeleter object at 0x7f484fd2c550>>
Traceback (most recent call last):
  File "/home/wangxy/miniconda3/envs/ml/lib/python3.6/site-packages/tensorflow_core/python/eager/context.py", line 316, in __del__
TypeError: argument of type 'NoneType' is not iterable

I also try code fromhttps://www.tensorflow.org/lite/convert/cmdline_examples?source=post_page
there still appears mistake and it can not get tflite

```
import tensorflow as tf
graph_def_file = "/path/to/Downloads/mobilenet_v1_1.0_224/frozen_graph.pb"
input_arrays = ["input"]
output_arrays = ["MobilenetV1/Predictions/Softmax"]

converter = tf.lite.TFLiteConverter.from_frozen_graph(
  graph_def_file, input_arrays, output_arrays)
tflite_model = converter.convert()
open("converted_model.tflite", "wb").write(tflite_model)
```

### error:
2019-07-18 17:51:00.100545: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-07-18 17:51:00.130812: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2494150000 Hz
2019-07-18 17:51:00.131427: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x564072ecb610 executing computations on platform Host. Devices:
2019-07-18 17:51:00.131468: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/wangxy/miniconda3/envs/ml/lib/python3.6/site-packages/tensorflow_core/lite/python/lite.py", line 668, in from_frozen_graph
    raise IOError("File '{0}' does not exist.".format(graph_def_file))
OSError: File '/home/python/frozen_graph.pb' does not exist.
>>> tflite_model = converter.convert()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'converter' is not defined
>>> open("converted_model.tflite", "wb").write(tflite_model)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'tflite_model' is not defined
>>> 
Exception ignored in: <bound method _TensorCacheDeleter.__del__ of <tensorflow.python.eager.context._TensorCacheDeleter object at 0x7fa9c5d9c278>>
TypeError: argument of type 'NoneType' is not iterable

**System information**
- OS Platform is Linux Ubuntu 18.04
- TensorFlow installed from binary and its version is 1.15.0-dev20190717 
- environment is anaconda  
- Python version:Python 3.6.8

So, if anyone have the solution please tell me, thank you very much

**Comment by haozha111** [comment]
hi, does this problem still exist? can you try in tf-nightly?
