### ISSUE TITLE
TensorRT INT8 Calibration Table is Missing

### ISSUE THREAD

**Issue by jiarongqiu** [tensorflow/tensorflow#30871]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- TensorFlow installed from (source or binary):binary
- TensorFlow version (use command below): v1.13.0-rc1-0-g54c5616308
- Python version:3.5.2
- CUDA/cuDNN version: CUDA 10
- GPU model and memory: Tesla V100 16GB

**Describe the current behavior**
TFTRT failed to collect calibration info and cannot create the INT8 inference graph. 

**Code to reproduce the issue**
Here is the model [link](https://drive.google.com/drive/folders/1hi23VeNomhHGj6Ai94Z44S6NRJ6uByJ5?usp=sharing).
```
def run_calibration(calib_graph, dataset):
    tf.reset_default_graph()
    tf_config = tf.ConfigProto()
    tf_config.gpu_options.allow_growth = True
    x = np.random.randint(0,10000,(1,40))
    with tf.Graph().as_default() as g:
        input, output = tf.import_graph_def(graph_def=calib_graph, return_elements=["X", "model/dense/BiasAdd"],
                                            name='')
        input = input.outputs[0]
        output = output.outputs[0]
        sess = tf.Session(config=tf_config, graph=g)

        for i in range(10):
            val = sess.run(output, {input: x})
        return calib_graph


def int8quant():
    with tf.Session() as sess:
        saver = tf.train.import_meta_graph("/workspace/exps/ptb/ptb_rnn_128/ptb_rnn_128-72600.meta")
        saver.restore(sess, "/workspace/exps/ptb/ptb_rnn_128/ptb_rnn_128-72600")
        your_outputs = ['model/dense/BiasAdd']
        frozen_graph = tf.graph_util.convert_variables_to_constants(
            sess,
            tf.get_default_graph().as_graph_def(),
            output_node_names=your_outputs)
        trt_graph = trt.create_inference_graph(
            input_graph_def=frozen_graph,
            outputs=your_outputs,
            max_batch_size=10,
            max_workspace_size_bytes=2 << 30,
            precision_mode='INT8',
            minimum_segment_size=2  # minimum number of nodes in an engine
       )
    int8graph = run_calibration(trt_graph, None)
    int8_graph = trt.calib_graph_to_infer_graph(int8graph)
```

**Other info / logs**
Here is the trace logs.
```
2019-07-19 03:47:34.167937: E tensorflow/contrib/tensorrt/log/trt_logger.cc:38] DefaultLogger Tensor TensorRTOutputPH_0cannot be both input and output
2019-07-19 03:47:34.167960: E tensorflow/contrib/tensorrt/log/trt_logger.cc:38] DefaultLogger Network must have at least one output
2019-07-19 03:47:38.553760: E tensorflow/contrib/tensorrt/log/trt_logger.cc:38] DefaultLogger Tensor (Unnamed ITensor* 3) is uniformly zero; network calibration failed.
2019-07-19 03:47:38.578654: E tensorflow/contrib/tensorrt/convert/convert_graph.cc:220] Calibration table is empty
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/workspace/code/rnnquant/trt/convert.py", line 99, in <module>
    main()
  File "/workspace/code/rnnquant/trt/convert.py", line 95, in main
    int8quant()
  File "/workspace/code/rnnquant/trt/convert.py", line 89, in int8quant
    int8_graph = trt.calib_graph_to_infer_graph(int8graph)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/tensorrt/python/trt_convert.py", line 416, in calib_graph_to_infer_graph
    int(msg[0]))
tensorflow.python.framework.errors_impl.UnknownError: Calibration table is missing. This shouldn't have happened!

```

**Comment by jvishnuvardhan** [comment]
@jiarongqiu Did you check whether the issue persists with latest versions (TF1.14, or nightly builds) of TF? Thanks!

**Comment by jiarongqiu** [comment]
> @jiarongqiu Did you check whether the issue persists with latest versions (TF1.14, or nightly builds) of TF? Thanks!

I haven't checked the other versions yet. I will check with TF 1.14.

**Comment by jiarongqiu** [comment]
> > @jiarongqiu Did you check whether the issue persists with latest versions (TF1.14, or nightly builds) of TF? Thanks!
> 
> I just tested on TF1.14 version following [trt_convert_test.py](https://github.com/tensorflow/tensorflow/blob/5912f51d580551e5cee2cfde4cb882594b4d3e60/tensorflow/python/compiler/tensorrt/trt_convert_test.py#L105). I succeedd in converting the graph but found a problem here. 
> I tested the converted graph with both calibration dataset and random data but got same result during the inference. I guessed my current conversion did not collection any info from the calibration dataset.
Is there somewhere that I could check the cache and the threshold T TensorRT chose for activations and weights?

**Comment by aaroey** [comment]
@jiarongqiu there is a problem in 1.14.0 and we're fixing that. Meanwhile, can you try with `tf-nightly-gpu` and follow [these](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/compiler/tensorrt/trt_convert.py#L316-L327) instructions to see if it works?

Thanks.

**Comment by jiarongqiu** [comment]
This is my current code. I import the graph through GraphDef.
```
    with tf.Session() as sess:
        saver = tf.train.import_meta_graph("/workspace/exps/ptb/ptb_rnn_128/ptb_rnn_128-72600.meta")
        saver.restore(sess, "/workspace/exps/ptb/ptb_rnn_128/ptb_rnn_128-72600")
        outputs = ['model/dense/BiasAdd']
        frozen_graph = tf.graph_util.convert_variables_to_constants(
            sess,
            tf.get_default_graph().as_graph_def(),
            output_node_names=outputs)
        converter = trt_convert.TrtGraphConverter(
            input_graph_def=frozen_graph,
            nodes_blacklist=outputs,
            precision_mode=trt_convert.TrtPrecisionMode.INT8,
        )

        class CalibrationData(object):

            def __init__(self,dataset=None):
                self.dataset = dataset

            def next(self):
                X =  np.random.randint(0, 10000, (1, 40))
                return {"X:0": X}

        calib_graph = converter.convert()
        calib_graph = converter.calibrate(
            fetch_names=["model/dense/BiasAdd:0"],
            num_runs=10,
            feed_dict_fn=CalibrationData().next)
        tf.train.write_graph(calib_graph, "/workspace/exps/ptb/ptb_rnn_128", "trt_model_int8.pb", as_text=False)
```
And, I tested it on the tf-nightly-gpu but got some errors during the conversion.
```
2019-07-24 06:16:59.855323: E tensorflow/compiler/tf2tensorrt/utils/trt_logger.cc:41] DefaultLogger Tensor (Unnamed ITensor* 3) is uniformly zero; network calibration failed.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/client/session.py", line 1352, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/client/session.py", line 1337, in _run_fn
    target_list, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/client/session.py", line 1430, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown: Calibration table is empty.
         [[{{node GetCalibrationDataOp}}]]
  (1) Unknown: Calibration table is empty.
         [[{{node GetCalibrationDataOp}}]]
         [[GetCalibrationDataOp/_7]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/workspace/code/rnnquant/trt/convert.py", line 142, in <module>
    main()
  File "/workspace/code/rnnquant/trt/convert.py", line 138, in main
    int8quantv2()
  File "/workspace/code/rnnquant/trt/convert.py", line 128, in int8quantv2
    feed_dict_fn=CalibrationData().next)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/compiler/tensorrt/trt_convert.py", line 643, in calibrate
    resource_name_input: _get_canonical_engine_name(node.name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/client/session.py", line 945, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/client/session.py", line 1168, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/client/session.py", line 1346, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/client/session.py", line 1371, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown: Calibration table is empty.
         [[node GetCalibrationDataOp (defined at usr/local/lib/python3.5/dist-packages/tensorflow_core/python/framework/ops.py:1657) ]]
  (1) Unknown: Calibration table is empty.
         [[node GetCalibrationDataOp (defined at usr/local/lib/python3.5/dist-packages/tensorflow_core/python/framework/ops.py:1657) ]]
         [[GetCalibrationDataOp/_7]]
0 successful operations.
0 derived errors ignored.

Original stack trace for 'GetCalibrationDataOp':
  File "usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "workspace/code/rnnquant/trt/convert.py", line 142, in <module>
    main()
  File "workspace/code/rnnquant/trt/convert.py", line 138, in main
    int8quantv2()
  File "workspace/code/rnnquant/trt/convert.py", line 128, in int8quantv2
    feed_dict_fn=CalibrationData().next)
  File "usr/local/lib/python3.5/dist-packages/tensorflow_core/python/compiler/tensorrt/trt_convert.py", line 635, in calibrate
    gen_trt_ops.get_calibration_data_op(resource_name_input))
  File "usr/local/lib/python3.5/dist-packages/tensorflow_core/compiler/tf2tensorrt/ops/gen_trt_ops.py", line 265, in get_calibration_data_op
    "GetCalibrationDataOp", resource_name=resource_name, name=name)
  File "usr/local/lib/python3.5/dist-packages/tensorflow_core/python/framework/op_def_library.py", line 793, in _apply_op_helper
    op_def=op_def)
  File "usr/local/lib/python3.5/dist-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "usr/local/lib/python3.5/dist-packages/tensorflow_core/python/framework/ops.py", line 3261, in create_op
    attrs, op_def, compute_device)
  File "usr/local/lib/python3.5/dist-packages/tensorflow_core/python/framework/ops.py", line 3330, in _create_op_internal
    op_def=op_def)
  File "usr/local/lib/python3.5/dist-packages/tensorflow_core/python/framework/ops.py", line 1657, in __init__
    self._traceback = tf_stack.extract_stack()

```

**Comment by aaroey** [comment]
@jiarongqiu this is what I got when running calibration:
```
2019-10-09 08:08:48.328837: W tensorflow/compiler/tf2tensorrt/utils/trt_logger.cc:37] DefaultLogger Tensor (Unnamed Layer* 2) [Constant]_output is uniformly zero; network calibration failed.
```
I'm running this with the latest TF r1.15.0rc3. It seems that the TRT portion of your model always output 0 regardless of the input. Can you double check the model and see if it's correct?

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
