### ISSUE TITLE
[TF 2.0 nightly] tf.keras.estimator.model_to_estimator with strategy=tf.distribute.MirroredStrategy() -> Method requires being in cross-replica context, use get_replica_context().merge_call()

### ISSUE THREAD

**Issue by tarrade** [tensorflow/tensorflow#30947]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac OS 10.14.5
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary from pip
- TensorFlow version (use command below): tf-nightly-2.0-preview==2.0.0.dev20190722
- Python version: 3.6.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

>>> import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)
v1.12.1-6737-gb4e5625437 2.0.0-dev20190722

**Describe the current behavior**
when using `strategy = tf.distribute.MirroredStrategy()`, `tf.keras.estimator.model_to_estimator()`

is crashing during training with 
`
RuntimeError: Method requires being in cross-replica context, use get_replica_context().merge_call()`

**Describe the expected behavior**
Should work as before and without any error messages

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```
import tensorflow as tf
import tensorflow_datasets as tfds
from absl import logging

logging.set_verbosity(logging.INFO)
# Define the estimator's input_fn
STEPS_PER_EPOCH = 5
BATCH_SIZE = 64
NUM_EPOCHS = 5


def input_fn():
    datasets, ds_info = tfds.load(name='mnist', with_info=True, as_supervised=True)
    mnist_train, mnist_test = datasets['train'], datasets['test']

    BUFFER_SIZE = 10000
    BATCH_SIZE = 64

    def scale(image, label):
        image = tf.cast(image, tf.float32)
        image /= 255
    
        return image, label[..., tf.newaxis]

    train_data = mnist_train.map(scale).shuffle(BUFFER_SIZE).batch(BATCH_SIZE)
    return train_data.repeat()

# Define train & eval specs
train_spec = tf.estimator.TrainSpec(input_fn=input_fn,
                                    max_steps=STEPS_PER_EPOCH * NUM_EPOCHS)
eval_spec = tf.estimator.EvalSpec(input_fn=input_fn,
                                  steps=STEPS_PER_EPOCH)

def make_model():
    return tf.keras.Sequential([
        tf.keras.layers.Conv2D(32, 3, activation='relu',
                               kernel_regularizer=tf.keras.regularizers.l2(0.02),
                               input_shape=(28, 28, 1)),
        tf.keras.layers.MaxPooling2D(),
        tf.keras.layers.Flatten(),
        tf.keras.layers.Dropout(0.1),
        tf.keras.layers.Dense(64, activation='relu'),
        tf.keras.layers.BatchNormalization(),
        tf.keras.layers.Dense(10, activation='softmax')
    ])

model = make_model()

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

#####
#strategy=None 
# crashing
strategy = tf.distribute.MirroredStrategy()

# config tf.estimator to use a give strategy
training_config = tf.estimator.RunConfig(train_distribute=strategy)
#####

estimator = tf.keras.estimator.model_to_estimator(
    keras_model = model,
    config=training_config
)

tf.estimator.train_and_evaluate(estimator, train_spec, eval_spec)
```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

```
W0723 11:29:42.079696 4746859968 cross_device_ops.py:1207] There is non-GPU devices in `tf.distribute.Strategy`, not using nccl allreduce.
I0723 11:29:42.087183 4746859968 run_config.py:554] Initializing RunConfig with distribution strategies.
I0723 11:29:42.088423 4746859968 estimator_training.py:167] Not using Distribute Coordinator.
W0723 11:29:42.097567 4746859968 estimator.py:1812] Using temporary folder as model directory: /var/folders/l7/00kxfwvs0vbbqxtrp3rpf3yh0000gn/T/tmp8lhzz88_
I0723 11:29:42.098804 4746859968 keras.py:527] Using the Keras model provided.
I0723 11:29:43.420326 4746859968 estimator.py:209] Using config: {'_model_dir': '/var/folders/l7/00kxfwvs0vbbqxtrp3rpf3yh0000gn/T/tmp8lhzz88_', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': <tensorflow.python.distribute.mirrored_strategy.MirroredStrategy object at 0xb3aa517b8>, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0xb3aa51a90>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1, '_distribute_coordinator_mode': None}
I0723 11:29:43.421994 4746859968 estimator_training.py:186] Not using Distribute Coordinator.
I0723 11:29:43.422926 4746859968 training.py:612] Running training and evaluation locally (non-distributed).
I0723 11:29:43.423843 4746859968 training.py:700] Start train and evaluate loop. The evaluate will happen after every checkpoint. Checkpoint frequency is determined based on RunConfig arguments: save_checkpoints_steps None or save_checkpoints_secs 600.
I0723 11:29:43.429722 4746859968 dataset_builder.py:184] Overwrite dataset info from restored data version.
I0723 11:29:43.434206 4746859968 dataset_info.py:380] Field info.location from disk and from code do not match. Keeping the one from code.
I0723 11:29:43.435199 4746859968 dataset_builder.py:253] Reusing dataset mnist (/Users/tarrade/tensorflow_datasets/mnist/1.0.0)
I0723 11:29:43.435896 4746859968 dataset_builder.py:399] Constructing tf.data.Dataset for split None, from /Users/tarrade/tensorflow_datasets/mnist/1.0.0
W0723 11:29:43.586170 4746859968 dataset_builder.py:439] Warning: Setting shuffle_files=True because split=TRAIN and shuffle_files=None. This behavior will be deprecated on 2019-08-06, at which point shuffle_files=False will be the default for all splits.
I0723 11:29:43.751439 4746859968 cross_device_ops.py:425] Reduce to /replica:0/task:0/device:CPU:0 then broadcast to ('/replica:0/task:0/device:CPU:0',).
I0723 11:29:43.764024 123145625903104 estimator.py:1145] Calling model_fn.
I0723 11:29:43.943940 4746859968 cross_device_ops.py:425] Reduce to /replica:0/task:0/device:CPU:0 then broadcast to ('/replica:0/task:0/device:CPU:0',).
I0723 11:29:43.948454 4746859968 cross_device_ops.py:425] Reduce to /replica:0/task:0/device:CPU:0 then broadcast to ('/replica:0/task:0/device:CPU:0',).
I0723 11:29:43.952039 4746859968 cross_device_ops.py:425] Reduce to /replica:0/task:0/device:CPU:0 then broadcast to ('/replica:0/task:0/device:CPU:0',).
I0723 11:29:43.954842 4746859968 cross_device_ops.py:425] Reduce to /replica:0/task:0/device:CPU:0 then broadcast to ('/replica:0/task:0/device:CPU:0',).
I0723 11:29:44.504832 123145625903104 coordinator.py:219] Error reported to Coordinator: Method requires being in cross-replica context, use get_replica_context().merge_call()
Traceback (most recent call last):
  File "/Users/tarrade/anaconda-release/conda-env/env_gcp_dl_2_0_nightly/lib/python3.6/site-packages/tensorflow_core/python/training/coordinator.py", line 297, in stop_on_exception
    yield
  File "/Users/tarrade/anaconda-release/conda-env/env_gcp_dl_2_0_nightly/lib/python3.6/site-packages/tensorflow_core/python/distribute/mirrored_strategy.py", line 865, in run
    self.main_result = self.main_fn(*self.main_args, **self.main_kwargs)
  File "/Users/tarrade/anaconda-release/conda-env/env_gcp_dl_2_0_nightly/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1146, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/Users/tarrade/anaconda-release/conda-env/env_gcp_dl_2_0_nightly/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/keras.py", line 326, in model_fn
    saver = saver_lib.Saver(var_list=var_list, sharded=True)
  File "/Users/tarrade/anaconda-release/conda-env/env_gcp_dl_2_0_nightly/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 828, in __init__
    self.build()
  File "/Users/tarrade/anaconda-release/conda-env/env_gcp_dl_2_0_nightly/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 840, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/Users/tarrade/anaconda-release/conda-env/env_gcp_dl_2_0_nightly/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 878, in _build
    build_restore=build_restore)
  File "/Users/tarrade/anaconda-release/conda-env/env_gcp_dl_2_0_nightly/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 497, in _build_internal
    per_device = self._GroupByDevices(saveables)
  File "/Users/tarrade/anaconda-release/conda-env/env_gcp_dl_2_0_nightly/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 404, in _GroupByDevices
    pydev.canonical_name(spec.tensor.device) for spec in saveable.specs)
  File "/Users/tarrade/anaconda-release/conda-env/env_gcp_dl_2_0_nightly/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 404, in <genexpr>
    pydev.canonical_name(spec.tensor.device) for spec in saveable.specs)
  File "/Users/tarrade/anaconda-release/conda-env/env_gcp_dl_2_0_nightly/lib/python3.6/site-packages/tensorflow_core/python/training/saving/saveable_object.py", line 52, in tensor
    return self._tensor() if callable(self._tensor) else self._tensor
  File "/Users/tarrade/anaconda-release/conda-env/env_gcp_dl_2_0_nightly/lib/python3.6/site-packages/tensorflow_core/python/distribute/values.py", line 1136, in tensor
    return strategy.extended.read_var(sync_on_read_variable)
  File "/Users/tarrade/anaconda-release/conda-env/env_gcp_dl_2_0_nightly/lib/python3.6/site-packages/tensorflow_core/python/distribute/mirrored_strategy.py", line 722, in read_var
    return replica_local_var._get_cross_replica()  # pylint: disable=protected-access
  File "/Users/tarrade/anaconda-release/conda-env/env_gcp_dl_2_0_nightly/lib/python3.6/site-packages/tensorflow_core/python/distribute/values.py", line 1222, in _get_cross_replica
    self, axis=None)
  File "/Users/tarrade/anaconda-release/conda-env/env_gcp_dl_2_0_nightly/lib/python3.6/site-packages/tensorflow_core/python/distribute/distribute_lib.py", line 794, in reduce
    _require_cross_replica_or_default_context_extended(self._extended)
  File "/Users/tarrade/anaconda-release/conda-env/env_gcp_dl_2_0_nightly/lib/python3.6/site-packages/tensorflow_core/python/distribute/distribute_lib.py", line 206, in _require_cross_replica_or_default_context_extended
    raise RuntimeError("Method requires being in cross-replica context, use "
RuntimeError: Method requires being in cross-replica context, use get_replica_context().merge_call()

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-3-f33ca3103e62> in <module>
     64 )
     65 
---> 66 tf.estimator.train_and_evaluate(estimator, train_spec, eval_spec)

~/anaconda-release/conda-env/env_gcp_dl_2_0_nightly/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/training.py in train_and_evaluate(estimator, train_spec, eval_spec)
    471         '(with task id 0).  Given task id {}'.format(config.task_id))
    472 
--> 473   return executor.run()
    474 
    475 

~/anaconda-release/conda-env/env_gcp_dl_2_0_nightly/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/training.py in run(self)
    611         config.task_type != run_config_lib.TaskType.EVALUATOR):
    612       logging.info('Running training and evaluation locally (non-distributed).')
--> 613       return self.run_local()
    614 
    615     # Distributed case.

~/anaconda-release/conda-env/env_gcp_dl_2_0_nightly/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/training.py in run_local(self)
    712         max_steps=self._train_spec.max_steps,
    713         hooks=train_hooks,
--> 714         saving_listeners=saving_listeners)
    715 
    716     eval_result = listener_for_eval.eval_result or _EvalResult(

~/anaconda-release/conda-env/env_gcp_dl_2_0_nightly/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py in train(self, input_fn, hooks, steps, max_steps, saving_listeners)
    365 
    366       saving_listeners = _check_listeners_type(saving_listeners)
--> 367       loss = self._train_model(input_fn, hooks, saving_listeners)
    368       logging.info('Loss for final step: %s.', loss)
    369       return self

~/anaconda-release/conda-env/env_gcp_dl_2_0_nightly/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py in _train_model(self, input_fn, hooks, saving_listeners)
   1154   def _train_model(self, input_fn, hooks, saving_listeners):
   1155     if self._train_distribution:
-> 1156       return self._train_model_distributed(input_fn, hooks, saving_listeners)
   1157     else:
   1158       return self._train_model_default(input_fn, hooks, saving_listeners)

~/anaconda-release/conda-env/env_gcp_dl_2_0_nightly/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py in _train_model_distributed(self, input_fn, hooks, saving_listeners)
   1217       self._config._train_distribute.configure(self._config.session_config)
   1218       return self._actual_train_model_distributed(
-> 1219           self._config._train_distribute, input_fn, hooks, saving_listeners)
   1220     # pylint: enable=protected-access
   1221 

~/anaconda-release/conda-env/env_gcp_dl_2_0_nightly/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py in _actual_train_model_distributed(self, strategy, input_fn, hooks, saving_listeners)
   1297                     labels,  # although this will be None it seems
   1298                     ModeKeys.TRAIN,
-> 1299                     self.config))
   1300           loss = strategy.reduce(
   1301               _get_loss_reduce_op_for_reporting(),

~/anaconda-release/conda-env/env_gcp_dl_2_0_nightly/lib/python3.6/site-packages/tensorflow_core/python/distribute/distribute_lib.py in call_for_each_replica(self, fn, args, kwargs)
   1769       kwargs = {}
   1770     with self._container_strategy().scope():
-> 1771       return self._call_for_each_replica(fn, args, kwargs)
   1772 
   1773   def _call_for_each_replica(self, fn, args, kwargs):

~/anaconda-release/conda-env/env_gcp_dl_2_0_nightly/lib/python3.6/site-packages/tensorflow_core/python/distribute/mirrored_strategy.py in _call_for_each_replica(self, fn, args, kwargs)
    645                           self._container_strategy().__class__.__name__, 5)
    646     return _call_for_each_replica(self._container_strategy(), self._device_map,
--> 647                                   fn, args, kwargs)
    648 
    649   def _configure(self,

~/anaconda-release/conda-env/env_gcp_dl_2_0_nightly/lib/python3.6/site-packages/tensorflow_core/python/distribute/mirrored_strategy.py in _call_for_each_replica(distribution, device_map, fn, args, kwargs)
    194     for t in threads:
    195       t.should_run.set()
--> 196     coord.join(threads)
    197 
    198   return values.regroup(device_map, tuple(t.main_result for t in threads))

~/anaconda-release/conda-env/env_gcp_dl_2_0_nightly/lib/python3.6/site-packages/tensorflow_core/python/training/coordinator.py in join(self, threads, stop_grace_period_secs, ignore_live_threads)
    387       self._registered_threads = set()
    388       if self._exc_info_to_raise:
--> 389         six.reraise(*self._exc_info_to_raise)
    390       elif stragglers:
    391         if ignore_live_threads:

~/anaconda-release/conda-env/env_gcp_dl_2_0_nightly/lib/python3.6/site-packages/six.py in reraise(tp, value, tb)
    691             if value.__traceback__ is not tb:
    692                 raise value.with_traceback(tb)
--> 693             raise value
    694         finally:
    695             value = None

~/anaconda-release/conda-env/env_gcp_dl_2_0_nightly/lib/python3.6/site-packages/tensorflow_core/python/training/coordinator.py in stop_on_exception(self)
    295     """
    296     try:
--> 297       yield
    298     except:  # pylint: disable=bare-except
    299       self.request_stop(ex=sys.exc_info())

~/anaconda-release/conda-env/env_gcp_dl_2_0_nightly/lib/python3.6/site-packages/tensorflow_core/python/distribute/mirrored_strategy.py in run(self)
    863               self._var_scope, reuse=self.replica_id > 0), \
    864           variable_scope.variable_creator_scope(self.variable_creator_fn):
--> 865         self.main_result = self.main_fn(*self.main_args, **self.main_kwargs)
    866         self.done = True
    867     finally:

~/anaconda-release/conda-env/env_gcp_dl_2_0_nightly/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py in _call_model_fn(self, features, labels, mode, config)
   1144 
   1145     logging.info('Calling model_fn.')
-> 1146     model_fn_results = self._model_fn(features=features, **kwargs)
   1147     logging.info('Done calling model_fn.')
   1148 

~/anaconda-release/conda-env/env_gcp_dl_2_0_nightly/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/keras.py in model_fn(features, labels, mode)
    324       object_graph = graph_view.ObjectGraphView(model)
    325       var_list = object_graph.frozen_saveable_objects()
--> 326       saver = saver_lib.Saver(var_list=var_list, sharded=True)
    327       saver._object_restore_saver = trackable_util.frozen_saver(model)
    328       scaffold = monitored_session.Scaffold(saver=saver)

~/anaconda-release/conda-env/env_gcp_dl_2_0_nightly/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py in __init__(self, var_list, reshape, sharded, max_to_keep, keep_checkpoint_every_n_hours, name, restore_sequentially, saver_def, builder, defer_build, allow_empty, write_version, pad_step_number, save_relative_paths, filename)
    826           time.time() + self._keep_checkpoint_every_n_hours * 3600)
    827     elif not defer_build:
--> 828       self.build()
    829     if self.saver_def:
    830       self._check_saver_def()

~/anaconda-release/conda-env/env_gcp_dl_2_0_nightly/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py in build(self)
    838     if context.executing_eagerly():
    839       raise RuntimeError("Use save/restore instead of build in eager mode.")
--> 840     self._build(self._filename, build_save=True, build_restore=True)
    841 
    842   def _build_eager(self, checkpoint_path, build_save, build_restore):

~/anaconda-release/conda-env/env_gcp_dl_2_0_nightly/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py in _build(self, checkpoint_path, build_save, build_restore)
    876           filename=checkpoint_path,
    877           build_save=build_save,
--> 878           build_restore=build_restore)
    879     elif self.saver_def and self._name:
    880       # Since self._name is used as a name_scope by builder(), we are

~/anaconda-release/conda-env/env_gcp_dl_2_0_nightly/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py in _build_internal(self, names_to_saveables, reshape, sharded, max_to_keep, keep_checkpoint_every_n_hours, name, restore_sequentially, filename, build_save, build_restore)
    495       # Add the save ops.
    496       if sharded:
--> 497         per_device = self._GroupByDevices(saveables)
    498         if build_save:
    499           save_tensor = self._AddShardedSaveOps(filename_tensor, per_device)

~/anaconda-release/conda-env/env_gcp_dl_2_0_nightly/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py in _GroupByDevices(self, saveables)
    402     for saveable in saveables:
    403       canonical_device = set(
--> 404           pydev.canonical_name(spec.tensor.device) for spec in saveable.specs)
    405       if len(canonical_device) != 1:
    406         raise ValueError("All tensors of a saveable object must be "

~/anaconda-release/conda-env/env_gcp_dl_2_0_nightly/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py in <genexpr>(.0)
    402     for saveable in saveables:
    403       canonical_device = set(
--> 404           pydev.canonical_name(spec.tensor.device) for spec in saveable.specs)
    405       if len(canonical_device) != 1:
    406         raise ValueError("All tensors of a saveable object must be "

~/anaconda-release/conda-env/env_gcp_dl_2_0_nightly/lib/python3.6/site-packages/tensorflow_core/python/training/saving/saveable_object.py in tensor(self)
     50   @property
     51   def tensor(self):
---> 52     return self._tensor() if callable(self._tensor) else self._tensor
     53 
     54 

~/anaconda-release/conda-env/env_gcp_dl_2_0_nightly/lib/python3.6/site-packages/tensorflow_core/python/distribute/values.py in tensor()
   1134     def tensor():
   1135       strategy = sync_on_read_variable._distribute_strategy  # pylint: disable=protected-access
-> 1136       return strategy.extended.read_var(sync_on_read_variable)
   1137 
   1138     spec = saver.BaseSaverBuilder.SaveSpec(

~/anaconda-release/conda-env/env_gcp_dl_2_0_nightly/lib/python3.6/site-packages/tensorflow_core/python/distribute/mirrored_strategy.py in read_var(self, replica_local_var)
    720     """Read the aggregate value of a replica-local variable."""
    721     if isinstance(replica_local_var, values.SyncOnReadVariable):
--> 722       return replica_local_var._get_cross_replica()  # pylint: disable=protected-access
    723     assert isinstance(replica_local_var, values.Mirrored)
    724     return array_ops.identity(replica_local_var.get())

~/anaconda-release/conda-env/env_gcp_dl_2_0_nightly/lib/python3.6/site-packages/tensorflow_core/python/distribute/values.py in _get_cross_replica(self)
   1220       return self._distribute_strategy.reduce(
   1221           reduce_util.ReduceOp.from_variable_aggregation(self.aggregation),
-> 1222           self, axis=None)
   1223 
   1224   def _as_graph_element(self):

~/anaconda-release/conda-env/env_gcp_dl_2_0_nightly/lib/python3.6/site-packages/tensorflow_core/python/distribute/distribute_lib.py in reduce(self, reduce_op, value, axis)
    792     """
    793     # TODO(josh11b): support `value` being a nest.
--> 794     _require_cross_replica_or_default_context_extended(self._extended)
    795     if isinstance(reduce_op, six.string_types):
    796       reduce_op = reduce_util.ReduceOp(reduce_op.upper())

~/anaconda-release/conda-env/env_gcp_dl_2_0_nightly/lib/python3.6/site-packages/tensorflow_core/python/distribute/distribute_lib.py in _require_cross_replica_or_default_context_extended(extended)
    204     _wrong_strategy_scope(strategy, context)
    205   assert cross_replica is None
--> 206   raise RuntimeError("Method requires being in cross-replica context, use "
    207                      "get_replica_context().merge_call()")
    208 

RuntimeError: Method requires being in cross-replica context, use get_replica_context().merge_call()

```

**Comment by ravikyram** [comment]
I have tried on colab with TF nightly version  and was able to reproduce the issue.Please, find the [gist](https://colab.research.google.com/drive/1h51lgpv27ro23gwjuz1yv0Sgbz0wQggG) here.Thanks!

**Comment by guptapriya** [comment]
Hi - this looks like a bug related to saving/checkpointing when using a batch norm layer + distribution strategy. While we look into fixing this, it is possible for you to try with these options to unblock yourself:
- use checkpoint_format = "saver"
- do not use batch norm layer

**Comment by tarrade** [comment]
Hi @guptapriya,

I try again with Tensorflow 2.1 and the issue is still there.

I confirm what you were saying:
- if I comment out bacht norm in my keras mode -> it is working
-  if I use checkpoint_format='saver' in with tf.keras.estimator.model_to_estimator

Thanks
Cheers
Fabien

**Comment by guptapriya** [comment]
Hi @tarrade thanks for confirming. We haven't had the bandwidth to fix this use case as we are focusing on native Keras training workflows. We have opened this for contributions if you or anyone would like to contribute a fix.

**Comment by tarrade** [comment]
Hi @guptapriya ,

Thanks for the follow up. I will be happy to contribute but I would like to be sure that this is useful.

Before TF 2.0, it was mention many time that tf.estimator will continue. Since TF 2.0 is out it seems that tf.estimator will not continue after 2.x. This was mention many time by Googlers. We can also see that tf.estimator still use v1.comp ops. Keras seems now to have all options that were provided by tf.estimator like distributed training and serving (in the same way as tf.estimator). TFX was until recently the only place were tf.estimator was the only option but now, since the migration to TF 2.1, TFX now provide support for Keras. Given that and if I am not wrong, it doesn't seems like tf.estimator will stay for very long. Maybe I am wrong but this is what I was told since I am discussing about tf.estimator and TF.2.x. I am also migration my code from tf.estimator to Keras to be sure  have all the functionalities I need.

**Comment by guptapriya** [comment]
@tarrade thanks for the follow up. tf.estimator is available in TF 2.x but your assessment is correct that there isn't much investment in improving it going forward, and all efforts are focused on Keras. If you're able to migrate your code to Keras, that is great and I would agree that you do not need to work on this fix. I was only suggesting that in case you could not move to estimator and were blocked by this bug. Thanks!

**Comment by xiankgx** [comment]
Hi, I'm also facing this problem, but I'm doing custom training loop and not using TF Estimator. I also have batch norm layers in my models.

**Comment by ZhuLingfeng1993** [comment]
I have the same problem in TF1.15, do you have any idea to solve it? @guptapriya

**Comment by guptapriya** [comment]
@xiankgx @ZhuLingfeng1993 are you guys using model_to_estimator? if not, please open a separate bug with code to repro the problem. Also , have you tried with latest TF versions already? TF 2.1 or nightly?

**Comment by ZhuLingfeng1993** [comment]
@guptapriya  Thank you for reply. I fix this bug when training mobilenetv2_ssd in tensorflow object detection API with TF1.15, by add `inplace_batchnorm_update: true` in pipeline.config.

**Comment by sushreebarsa** [comment]
Was able to reproduce this issue in TF v2.5 ,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/962fa7dceb43341f3fed97405513a6ca/untitled16.ipynb)..Thanks !

**Comment by kumariko** [comment]
Was able to reproduce this issue in TF v2.7 , please find the gist [here](https://colab.research.google.com/gist/kumariko/d96c1a3d6f042f049a73d962008401bc/untitled16.ipynb#scrollTo=zPU3hV5j2fJ5)..Thanks !

**Comment by sachinprasadhs** [comment]
Hi, Estimator will be deprecated from Tensorflow 2.12 since it uses Tensorflow V1 behavior.
Could you please migrate from Estimator to Keras API which will enable you to perform the aforementioned tasks, such as [model building](https://www.tensorflow.org/guide/keras/custom_layers_and_models), gradient application, [training](https://www.tensorflow.org/guide/keras/customizing_what_happens_in_fit), evaluation, and prediction.
Refer Migration guide here https://www.tensorflow.org/guide/migrate/migrating_estimator for more details. Thanks!
