### ISSUE TITLE
Fast python protocol buffers?

### ISSUE THREAD

**Issue by skearnes** [tensorflow/tensorflow#310]
This might be a better question for the protobuf team, but is there any way to get [fast python protocol buffers](https://developers.google.com/protocol-buffers/docs/reference/python-generated#cpp_impl) with TensorFlow? I have tried `bazel build --copt=-DPYTHON_PROTO2_CPP_IMPL_V2` but running with `PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION='cpp'` gives the following error:

``` python
Traceback (most recent call last):
  File "/home/kearnes/git/tensorflow/bazel-bin/deaps/test.runfiles/deaps/test.py", line 21, in <module>
    import tensorflow as tf
  File "/home/kearnes/git/tensorflow/bazel-bin/deaps/test.runfiles/tensorflow/__init__.py", line 8, in <module>
    from tensorflow.python import *
  File "/home/kearnes/git/tensorflow/bazel-bin/deaps/test.runfiles/tensorflow/python/__init__.py", line 24, in <module>
    raise ImportError(msg)
ImportError: Error importing tensorflow: you should not try to import
  tensorflow from its source directory; please exit the tensorflow source tree,
  and relaunch your python interpreter from there.
  Original ImportError: cannot import name _message
```

**Comment by ebrevdo** [comment]
This may be caused by incompatible versions of protobuf installed by python.  Are you using the python protobuf package version 3.0.0a3?

**Comment by skearnes** [comment]
@ebrevdo I'm using the version that comes with `git clone --recurse submodules`:
```
$ git submodule status 
 55ad57a235c009d0414aed1781072adda0c89137 google/protobuf (v3.0.0-alpha-4-179-g55ad57a)
```

**Comment by ebrevdo** [comment]
This is the same version you've got installed in your python interpreter?
Are you using blaze commands to run the scripts, or are you running python
yourself?

**Comment by skearnes** [comment]
I don't have a version installed in my interpreter at all. I'm just running bazel and then running the bazel-bin binary.

**Comment by ebrevdo** [comment]
This looks like a bug either on the protobuf side or somewhere in the tensorflow/protobuf build interaction.  I was able to replicate; we're working on a solution.

**Comment by skearnes** [comment]
@ebrevdo Any updates on this issue?

**Comment by ebrevdo** [comment]
Just to confirm; are you running bazel test?  (looks like it)

It may be that the wrong version of protobuf is being used.  Is this in linux?

Try *also* installing the protobuf package via pip and making sure you're using the right version in your system python.  Does that help the problem?

**Comment by skearnes** [comment]
I'm running bazel build, as described in OP. This is on Ubuntu 14.04. It seems that //google/protobuf/python/google/protobuf/pyext/... is not being built at all. Nothing in the BUILD references any of those files. I've been trying to hack the build rules, but that is quickly becoming a rabbit hole.

Following your suggestion, I have been able to install protobuf from the branch that comes with tensorflow into my python, but I'm still getting errors like `ImportError: cannot import name _message` when I try to use it with `PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=cpp`.

I'll note that `python setup.py test --cpp_implementation` (from the protobuf python install) also gives an error: `AttributeError: 'module' object has no attribute 'python_message'`.

**Comment by ebrevdo** [comment]
Sounds like this may be a bug in the version of protobuf we check out. Any
chance you could file a bug there and cross link it here? You can also try
using the master HEAD version for our submodule and see the problem has
been fixed.

**Comment by skearnes** [comment]
I've created an issue over at protobuf. In my experience so far, this issue has major performance implications for people using tf.Example protos for model input.

**Comment by keveman** [comment]
Sent PR https://github.com/google/protobuf/pull/1029 to google/protobuf.

**Comment by skearnes** [comment]
google/protobuf#1029 was merged; I'll leave the issue open pending update of the protobuf version that comes with TF.

**Comment by skearnes** [comment]
Protobuf version updated in https://github.com/tensorflow/tensorflow/commit/3116631f950a7de755c786fc954dc9cfb295d127.

**Comment by lemonzi** [comment]
@ebrevdo @skearnes I found this issue after some searching -- is this flag still required? It's not mentioned anywhere in the documentation; the only mention of fast protos is the pre-compiled protobuf wheel.

**Comment by yaroslavvb** [comment]
@lemonzi just do this

`python -c "from google.protobuf.internal import api_implementation; print(api_implementation._default_implementation_type)"`

If it prints "cpp" - good. If you prints "python" - bad.

**Comment by lemonzi** [comment]
@yaroslavvb It printed "python" after compiling from sources and installing the wheel, both compiling as instructed by the docs and adding the `use_fast_cpp_protos` flag. I had to install an older version of protobuf from the binary builds (https://storage.googleapis.com/tensorflow/mac/cpu/protobuf-3.0.0-cp27-cp27m-macosx_10_11_x86_64.whl). Since this is a flag for protobuf and not tensorflow, maybe it has to be added internally to the BUILD file for tensorflow?

**Comment by skearnes** [comment]
I'm seeing "python" from `python -c "from google.protobuf.internal import api_implementation; print(api_implementation._default_implementation_type)"` using a bazel build of TF 1.2.1.

**Comment by skearnes** [comment]
FYI downloading and installing the [latest cpp whl](https://pypi.python.org/pypi/protobuf/3.3.0) from pypi fixes the issue for me.

**Comment by yaroslavvb** [comment]
Also this https://www.tensorflow.org/versions/r0.12/get_started/os_setup#protobuf_library_related_issues

**Comment by dangbuzhudechaozi** [comment]
ImportError                               Traceback (most recent call last)
<ipython-input-5-41389fad42b5> in <module>()
----> 1 import tensorflow as tf

E:\Program Files\Anaconda3\lib\site-packages\tensorflow\__init__.py in <module>()
     22 
     23 # pylint: disable=wildcard-import
---> 24 from tensorflow.python import *
     25 # pylint: enable=wildcard-import
     26 

E:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\__init__.py in <module>()
     50 
     51 # Protocol buffers
---> 52 from tensorflow.core.framework.graph_pb2 import *
     53 from tensorflow.core.framework.node_def_pb2 import *
     54 from tensorflow.core.framework.summary_pb2 import *

E:\Program Files\Anaconda3\lib\site-packages\tensorflow\core\framework\graph_pb2.py in <module>()
      4 import sys
      5 _b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
----> 6 from google.protobuf import descriptor as _descriptor
      7 from google.protobuf import message as _message
      8 from google.protobuf import reflection as _reflection

ImportError: No module named 'google'

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by yaroslavvb** [comment]
BTW, it looks like official Mac packages for fast protobuf are no longer maintained, so the link I posted is out of date. You have to build protobuf yourself (see this comment https://github.com/tensorflow/tensorflow/issues/15417#issuecomment-352931701)

**Comment by tensorflowbutler** [comment]
Nagging Assigneee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by MoreYoungGavin** [comment]
i am also the problem ,i don't kown how to solve it in window
