### ISSUE TITLE
Backpropagation through the while-loop doesn't work if external tensors are used inside

### ISSUE THREAD

**Issue by rizar** [tensorflow/tensorflow#3114]
In the simple example below I copy `inputs` to `outputs` in a while loop. When I try to take gradient of the `outputs` w.r. to `inputs`, I get an error. It's worth noting that 1) the forward pass works 2) the gradient computation works if I made `inputs` a `TensorArray`, like it is done in the [scan implementation](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/functional_ops.py#L289)

The code:

```python
with tf.Graph().as_default(), tf.Session() as sess:
  num_steps = 9

  inputs = tf.placeholder(dtype='float32', shape=(num_steps))
  initial_outputs = tf.TensorArray(dtype=tf.float32, size=num_steps)
  initial_i = tf.constant(0, dtype='int32')
    
  def should_continue(i, *args):
    return i < num_steps
  
  def iteration(i, outputs_):
    outputs_ = outputs_.write(i, tf.gather(inputs, i))
    return i + 1, outputs_
  
  i, outputs = tf.while_loop(
    should_continue, iteration,
    [initial_i, initial_outputs])
  
  outputs = outputs.pack()
  grad_wr_inputs = tf.convert_to_tensor(tf.gradients([tf.reduce_sum(outputs)], [inputs])[0])
  print sess.run([outputs, grad_wr_inputs],
                 feed_dict={inputs: [4, 6, 0, 7, 0, 0, 1, 2, 0]})
```

The stack trace:

```
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-354-e1d117e742f9> in <module>()
     20   grad_wr_inputs = tf.convert_to_tensor(tf.gradients([tf.reduce_sum(outputs)], [inputs])[0])
     21   print sess.run([outputs, grad_wr_inputs],
---> 22                  feed_dict={inputs: [4, 6, 0, 7, 0, 0, 1, 2, 0]})

/google/data/ro/teams/colab/tensorflow/google3/third_party/tensorflow/python/client/session.py in run(self, fetches, feed_dict, options, run_metadata)
    366     try:
    367       result = self._run(None, fetches, feed_dict, options_ptr,
--> 368                          run_metadata_ptr)
    369       if run_metadata:
    370         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

/google/data/ro/teams/colab/tensorflow/google3/third_party/tensorflow/python/client/session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
    639     movers = self._update_with_movers(feed_dict_string, feed_map)
    640     results = self._do_run(handle, target_list, unique_fetches,
--> 641                            feed_dict_string, options, run_metadata)
    642 
    643     # User may have fetched the same tensor multiple times, but we

/google/data/ro/teams/colab/tensorflow/google3/third_party/tensorflow/python/client/session.py in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
    707     if handle is None:
    708       return self._do_call(_run_fn, self._session, feed_dict, fetch_list,
--> 709                            target_list, options, run_metadata)
    710     else:
    711       return self._do_call(_prun_fn, self._session, handle, feed_dict,

/google/data/ro/teams/colab/tensorflow/google3/third_party/tensorflow/python/client/session.py in _do_call(self, fn, *args)
    727         except KeyError:
    728           pass
--> 729       raise type(e)(node_def, op, message)
    730 
    731   def _extend_graph(self):

InvalidArgumentError: All inputs to node Slice must be from the same frame.
```

**Comment by yuanbyu** [comment]
This is a bug in the handling of IndexedSlices in while loop.  We seemed to handle the shape tensor incorrectly.  I need to talk to others about how the shape tensor should be updated within the loop. We should have a fix soon.

**Comment by ebrevdo** [comment]
Can you confirm this has been fixed at head?

**Comment by aselle** [comment]
Automatically closing due to lack of recent activity. Please reopen when further information becomes available.

**Comment by fchollet** [comment]
I get the same error at head when using a dynamic rnn:

`InvalidArgumentError: All inputs to node gradients/while_2/strided_slice_2_grad/StridedSliceGrad/StackPush must be from the same frame.`

So gradient computation does not work if you use slicing inside a while_loop?

**Comment by ebrevdo** [comment]
Are you using a nightly build? If not, try it

**Comment by 3rd3** [comment]
I'm getting the same error upon what seems to be the Assignment operation in the initial variable initialization of a variable inside a tf.scan. I'm using the latest official build from the TensorFlow website. Any idea?

**Comment by ebrevdo** [comment]
Have you tried a nightly build?

**Comment by link-er** [comment]
I have this error with scan too, on nightly build (version is 0.10.0)

**Comment by Fr-d-rik** [comment]
I am getting the exact same error for a very similar model (also on v0.10.0). Given that some time has passed since the last post, I'd be curious whether any of you have found a solution or workaround to this issue and would be willing to share.

**Comment by link-er** [comment]
@Fr-d-rik hi!
The way that I was able to found - remove Variable initialization from the scan step. I do not know is this a case for you, but I had something like
```
var = tf.Variable(...)
```
inside the step. Once I removed it outside the step, by announcing earlier and just accessing inside, error disappeared.
Hope it can help you

**Comment by ebrevdo** [comment]
It's common to access an external variable inside a while_loop.  For
example, RNN code does this all the time via tf.get_variable().  How are
you creating a variable?  Directly with tf.Variable?

**Comment by link-er** [comment]
Yes, I was doing it like this before and then I changed it to get_variable, that fixed the error
But still maybe the error message can be a little bit changed, because it is really hard to get what is causing it

**Comment by ebrevdo** [comment]
Can you create a new issue, appropriately named, with a small code snippet and the full error trace?   This bug is closed.

**Comment by link-er** [comment]
@ebrevdo actually it is already there, https://github.com/tensorflow/tensorflow/issues/4478

**Comment by Fr-d-rik** [comment]
Sweet! Thanks a lot! I made the variables on the first iteration of the while loop and accessed them from then on. I guess moving that bit out of the loop should fix my problem then.

**Comment by jungle-cat** [comment]
@fchollet I also get the same error when using dynamic_rnn, have you ever solved this problem?

Here's my snippet

```python
import numpy as np
import tensorflow as tf
import tflearn

def retrieve_sequence_length(data):
    with tf.name_scope('sequence_length'):
        used = tf.sign(tf.abs(data))
        length = tf.cast(tf.reduce_sum(used, reduction_indices=[1, 2]), tf.int32)
    return length 

def loss(x, y, sequence_length):
    with tf.name_scope('loss'):
        n_states = x.get_shape()[-1].value
        transition_params = tflearn.variable(name='transition_params', shape=[n_states, n_states], 
                                             initializer='xavier', dtype=tf.float32)
        loss = tf.contrib.crf.crf_log_norm(x, sequence_length, transition_params)
        # loss, _ = tf.contrib.crf.crf_log_likelihood(x, y, sequence_length, transition_params)
    return tf.reduce_mean(loss)

# Data settings.
num_examples = 10000
num_words = 20
num_features = 100
num_tags = 5

# Random features.
x = np.random.uniform(low=0.1, high=1.1, size=(num_examples, num_words, num_features)).astype(np.float32)

# Random tag indices representing the gold sequence.
y = np.random.randint(num_tags, size=[num_examples, num_words]).astype(np.int32)

# All sequences in this example have the same length, but they can be variable in a real model.
# sequence_lengths = np.full(num_examples, num_words - 1, dtype=np.int32)


input0 = tflearn.input_data(shape=[None, num_words, num_features], dtype=tf.float32)
sequence_length = retrieve_sequence_length(input0)
print 'sequence_length: ', sequence_length

unary_scores = tflearn.time_distributed(input0, tflearn.fully_connected, [num_tags, 'softmax'])
print 'unary_score: ', unary_scores

net = tflearn.regression(unary_scores,
                         placeholder=tf.placeholder(shape=[None, num_words], dtype=tf.int32),
                         learning_rate=0.001,
                         optimizer='sgd',
                         loss=lambda x, y: loss(x, y, sequence_length),
                         metric=None,
                         n_classes=num_tags,
                         to_one_hot=False)

model = tflearn.DNN(net)

model.fit(x, y, batch_size=32)
```

the stacktrace of the error:
```
--
Traceback (most recent call last):
  File "c.py", line 54, in <module>
    model.fit(x, y, batch_size=32)
  File "/home/weiguo.fwg/envs/tensorflow/lib/python2.7/site-packages/tflearn/models/dnn.py", line 214, in fit
    callbacks=callbacks)
  File "/home/weiguo.fwg/envs/tensorflow/lib/python2.7/site-packages/tflearn/helpers/trainer.py", line 304, in fit
    show_metric)
  File "/home/weiguo.fwg/envs/tensorflow/lib/python2.7/site-packages/tflearn/helpers/trainer.py", line 762, in _train
    feed_batch)
  File "/home/weiguo.fwg/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 717, in run
    run_metadata_ptr)
  File "/home/weiguo.fwg/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 915, in _run
    feed_dict_string, options, run_metadata)
  File "/home/weiguo.fwg/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 965, in _do_run
    target_list, options, run_metadata)
  File "/home/weiguo.fwg/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 985, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors.InvalidArgumentError: All inputs to node SGD/gradients/loss/RNN/while/expand_dims_state_grad/Reshape/StackPush must be from the same frame.
```
