### ISSUE TITLE
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

### ISSUE THREAD

**Issue by nicholas-2** [tensorflow/tensorflow#31172]
**System information**
- OS Platform and Distribution: Windows 10
- TensorFlow installed from (source or binary): no idea, likely binary
- TensorFlow version: 2.0.0b1
- Python version: Python 3.7.4
- Installed using pip
- CUDA/cuDNN version: using CPU
- GPU model and memory: using CPU

Running the testing in the object detection API sample models (@ https://github.com/tensorflow/models) gives me an error stating `ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed. Failed to load the native TensorFlow runtime.`

After creating an virtual environment with `venv`, I ran:

`git clone https://github.com/tensorflow/models.git`

`cd models/research`

`protoc object_detection/protos/*.proto --python_out=.`

`python object_detection/builders/model_builder_test.py`, which resulted in the following error:

```
Traceback (most recent call last):
  File "C:\Users\nick desktop\Desktop\Projects\MachineLearning\ObjectDetection\tensorflow-env-obj\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\nick desktop\Desktop\Projects\MachineLearning\ObjectDetection\tensorflow-env-obj\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\nick desktop\Desktop\Projects\MachineLearning\ObjectDetection\tensorflow-env-obj\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\nick desktop\AppData\Local\Programs\Python\Python37\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\nick desktop\AppData\Local\Programs\Python\Python37\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 20, in <module>
    import tensorflow as tf
  File "C:\Users\nick desktop\Desktop\Projects\MachineLearning\ObjectDetection\tensorflow-env-obj\lib\site-packages\tensorflow\__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\nick desktop\Desktop\Projects\MachineLearning\ObjectDetection\tensorflow-env-obj\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\nick desktop\Desktop\Projects\MachineLearning\ObjectDetection\tensorflow-env-obj\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\nick desktop\Desktop\Projects\MachineLearning\ObjectDetection\tensorflow-env-obj\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\nick desktop\Desktop\Projects\MachineLearning\ObjectDetection\tensorflow-env-obj\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\nick desktop\Desktop\Projects\MachineLearning\ObjectDetection\tensorflow-env-obj\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\nick desktop\AppData\Local\Programs\Python\Python37\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\nick desktop\AppData\Local\Programs\Python\Python37\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

Any ideas on how to fix this error? Thanks for the help ahead of time!

**Comment by nicholas-2** [comment]
I'm not using a GPU, so I thought I didn't need CUDA and cuDNN?

**Comment by ymodak** [comment]
From the template it looks like you are installing TensorFlow (TF) prebuilt binaries.
TensorFlow release binaries version 1.6 and higher are prebuilt with AVX instruction sets.
Therefore on any CPU that does not have these instruction sets, either CPU or GPU version of TF will fail to load.
Apparently, your CPU model does not support AVX instruction sets. You can still use TensorFlow with the alternatives given below:
Try Google Colab to use TensorFlow.
The easiest way to use TF will be to switch to google colab. You get pre-installed latest stable TF version. Also you can use pip install to install any other preferred TF version.
It has an added advantage since you can you easily switch to different hardware accelerators (cpu, gpu, tpu) as per the task.
All you need is a good internet connection and you are all set.
Try to build TF from sources by changing CPU optimization flags.
Please let us know if this helps.

**Comment by ymodak** [comment]
From the template it looks like you are installing **TensorFlow** (TF) prebuilt binaries.

**TensorFlow release binaries version 1.6 and higher are prebuilt with AVX instruction sets.**
Therefore on any CPU that does not have these instruction sets, either CPU or GPU version of TF will fail to load.

Apparently, your CPU model does not support AVX instruction sets. You can still use TensorFlow with the alternatives given below:
* Try Google Colab to use TensorFlow.
    * The easiest way to use TF will be to switch to [google colab](https://colab.sandbox.google.com/notebooks/welcome.ipynb#recent=true). You get pre-installed latest stable TF version. Also you can use ```pip install``` to install any other preferred TF version.
    * It has an added advantage since you can you easily switch to different hardware accelerators     
      (cpu, gpu, tpu) as per the task. 
    * All you need is a good internet connection and you are all set.
* Try to build TF from sources by changing CPU optimization flags.

Please let us know if this helps.

**Comment by nicholas-2** [comment]
Thanks @ymodak for the advice.

I'm using this tutorial by sentdex by the way: https://www.youtube.com/watch?v=COlbP62-B-U

I started by attempting to use Google Colab, but got an error with no solution I could find online:
```
/content/models/research
Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 23, in <module>
    from object_detection.builders import model_builder
  File "/usr/local/lib/python3.6/dist-packages/object_detection-0.1-py3.6.egg/object_detection/builders/model_builder.py", line 20, in <module>
    from object_detection.builders import anchor_generator_builder
  File "/usr/local/lib/python3.6/dist-packages/object_detection-0.1-py3.6.egg/object_detection/builders/anchor_generator_builder.py", line 22, in <module>
    from object_detection.protos import anchor_generator_pb2
ImportError: cannot import name 'anchor_generator_pb2'
```

I also seemed to get the same error after running `pip install tensorflow==1.14`:

```
Traceback (most recent call last):
  File "C:\Users\nick desktop\Desktop\Projects\MachineLearning\ObjectDetection\tensorflow-env-obj\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\nick desktop\Desktop\Projects\MachineLearning\ObjectDetection\tensorflow-env-obj\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\nick desktop\Desktop\Projects\MachineLearning\ObjectDetection\tensorflow-env-obj\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\nick desktop\AppData\Local\Programs\Python\Python37\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\nick desktop\AppData\Local\Programs\Python\Python37\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 20, in <module>
    import tensorflow as tf
  File "C:\Users\nick desktop\Desktop\Projects\MachineLearning\ObjectDetection\tensorflow-env-obj\lib\site-packages\tensorflow\__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\nick desktop\Desktop\Projects\MachineLearning\ObjectDetection\tensorflow-env-obj\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\nick desktop\Desktop\Projects\MachineLearning\ObjectDetection\tensorflow-env-obj\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\nick desktop\Desktop\Projects\MachineLearning\ObjectDetection\tensorflow-env-obj\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\nick desktop\Desktop\Projects\MachineLearning\ObjectDetection\tensorflow-env-obj\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\nick desktop\Desktop\Projects\MachineLearning\ObjectDetection\tensorflow-env-obj\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\nick desktop\AppData\Local\Programs\Python\Python37\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\nick desktop\AppData\Local\Programs\Python\Python37\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

so perhaps it's not a problem with TF >1.5?

Thanks for your help!

**Comment by ymodak** [comment]
You should be able to install TF less than 1.6 perhaps TF 1.5 however that won't solve your current issue. The reason being TF Object detection API requires TF 1.12 and above.
See https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md
You can try using google colab to execute object detection api however you need to setup the recommended environment.
See
https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md

**Comment by TheNewSound** [comment]
I literally have the same problem, tried every combination of CUDA10.0/Python3.7/Python3.6/cuDNN4.2/cuDNN7.5/cuDNN7.6 on win10

I eventually gave up on tensorflow-gpu and doing it in the browser now with tfjs.

**Comment by nicholas-2** [comment]
Sorry, I forgot to ask, are there any sample google colabs that run the object detection API? I followed all the instructions, here's my setup but still gives an error. https://colab.research.google.com/drive/1m6Cw38ldCMndeuIOwoMExd4EBxkDOkc4

**Comment by ymodak** [comment]
Sure, you can take a look at this;
https://github.com/tensorflow/hub/blob/master/examples/colab/object_detection.ipynb

**Comment by TheNewSound** [comment]
> cc TheNewSound Sorry to hear about this. Does your CPU support AVX instructions sets?
> -_-_-_-_-
> cc nicholas-2
> Sure, you can take a look at this;
> https://github.com/tensorflow/hub/blob/master/examples/colab/object_detection.ipynb
> I will close this issue now that original query has been answered. Feel free to follow up if need be. We can reopen the issue if required. Thanks!

I think it doesnt support AVX, could that be an issue?

**Comment by ymodak** [comment]
Yes that is true.

> **TensorFlow release binaries version 1.6 and higher are prebuilt with AVX instruction sets.**
> Therefore on any CPU that does not have these instruction sets, either CPU or GPU version of TF will fail to load.

**Comment by sebafonte** [comment]
Same problem here.
Cuda 10.0, python 3.6, cuDDN 7.5.0 (also tested with 7.6 and others). Desired tensorflow is 2.0.
Video card is rtx2060. Bough this nvidia specially to use with cuda and tensorflow.
I have a Phenom 2 1090t, does'nt support avx. This could be the cause of getting this error message after doing "import tensorflow" ?

Tried every combination of cuddn, also used cuda 10.2 and had to reinstall 10.0, no problems seems nvcc -v gives the correct version.

Google colab is SLOW.
