### ISSUE TITLE
Win 10 download mnist get SSL CERTIFICATE_VERIFY_FAILED error

### ISSUE THREAD

**Issue by yaradong** [tensorflow/tensorflow#31189]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): win 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.14.0
- Python version: 3.6.5
- Bazel version (if compiling from source): na
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: cuda 10.1
- GPU model and memory:
**Code to reproduce the issue**
Here is the error I get:
`>>> from tensorflow.examples.tutorials.mnist import input_data`
`C:\Anaconda\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from float to np.floating is deprecated. In future, it will be treated as np.float64 == np.dtype(float).type.
  from ._conv import register_converters as _register_converters`
`>>> mnist = input_data.read_data_sets("MNIST_data/", one_hot=True)`
`WARNING: Logging before flag parsing goes to stderr.
W0731 06:36:14.795812 11136 deprecation.py:323] From <stdin>:1: read_data_sets (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.`
`Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
W0731 06:36:14.795812 11136 deprecation.py:323] From C:\Users\demouser\AppData\Roaming\Python\Python36\site-packages\tensorflow\contrib\learn\python\learn\datasets\mnist.py:260: maybe_download (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.`
`Instructions for updating:
Please write your own downloading logic.`
`W0731 06:36:14.795812 11136 deprecation.py:323] From C:\Users\demouser\AppData\Roaming\Python\Python36\site-packages\tensorflow\contrib\learn\python\learn\datasets\base.py:252: _internal_retry.<locals>.wrap.<locals>.wrapped_fn (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.`
`Instructions for updating:
Please use urllib or similar directly.
Traceback (most recent call last):`
  `File "C:\Anaconda\lib\urllib\request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "C:\Anaconda\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Anaconda\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Anaconda\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Anaconda\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "C:\Anaconda\lib\http\client.py", line 964, in send
    self.connect()
  File "C:\Anaconda\lib\http\client.py", line 1400, in connect
    server_hostname=server_hostname)
  File "C:\Anaconda\lib\ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "C:\Anaconda\lib\ssl.py", line 814, in __init__
    self.do_handshake()
  File "C:\Anaconda\lib\ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "C:\Anaconda\lib\ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)`

`During handling of the above exception, another exception occurred:`

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\demouser\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\util\deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "C:\Users\demouser\AppData\Roaming\Python\Python36\site-packages\tensorflow\contrib\learn\python\learn\datasets\mnist.py", line 260, in read_data_sets
    source_url + TRAIN_IMAGES)
  File "C:\Users\demouser\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\util\deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "C:\Users\demouser\AppData\Roaming\Python\Python36\site-packages\tensorflow\contrib\learn\python\learn\datasets\base.py", line 252, in maybe_download
    temp_file_name, _ = urlretrieve_with_retry(source_url)
  File "C:\Users\demouser\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\util\deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "C:\Users\demouser\AppData\Roaming\Python\Python36\site-packages\tensorflow\contrib\learn\python\learn\datasets\base.py", line 205, in wrapped_fn
    return fn(*args, **kwargs)
  File "C:\Users\demouser\AppData\Roaming\Python\Python36\site-packages\tensorflow\contrib\learn\python\learn\datasets\base.py", line 233, in urlretrieve_with_retry
    return urllib.request.urlretrieve(url, filename)
  File "C:\Anaconda\lib\urllib\request.py", line 248, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "C:\Anaconda\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Anaconda\lib\urllib\request.py", line 526, in open
    response = self._open(req, data)
  File "C:\Anaconda\lib\urllib\request.py", line 544, in _open
    '_open', req)
  File "C:\Anaconda\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\Anaconda\lib\urllib\request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "C:\Anaconda\lib\urllib\request.py", line 1320, in do_open
    raise URLError(err)`
`urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)>`

**Describe the current behavior**
I reinstall the certifi, openssl, cryptography, ca-certificates. But it did not work.
I changed the mnist url from https to http. It worked. But I don't think this is a good solution. it just bypass ssl.
I use openssl s_client command checked the connect to the mnist url. I got the certificate information. So I guess the certification is installed and added to ssl. But why do I still get  SSL CERTIFICATE_VERIFY_FAILED error?
I also checked: 'conda config --show ssl_verify'  It showed the accert.pem file path

**Comment by gadagashwini** [comment]
@yaradong I executed the code on Colab and as well on local system it is working fine. Could you check once without changing http to https. Let us know how it progresses. Thanks!

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
