### ISSUE TITLE
Can not load tflite model

### ISSUE THREAD

**Issue by wugh** [tensorflow/tensorflow#31224]
# TF information
```
tf-nightly           1.15.0.dev20190730
```
# Model Information

I use the bert's `run_classifier.py` to export the classifier model
```
1141         name_to_features = {
1142             "input_ids": tf.VarLenFeature(tf.int64),
1143             "input_mask": tf.VarLenFeature(tf.int64),
1144             "segment_ids": tf.VarLenFeature(tf.int64),
1145             "label_ids": tf.FixedLenFeature([], tf.int64)
1146         }
1147         serving_input_receiver_fn = tf.estimator.export.build_parsing_serving_input_receiver_fn(name_to_features)
1148         estimator.export_savedmodel(FLAGS.output_dir, serving_input_receiver_fn)
```
Then the estimator to export model.

# Code to generate tflite model
```
import tensorflow as tf
import sys
saved_model_dir = sys.argv[1]
converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir)
converter.optimizations = [tf.lite.Optimize.OPTIMIZE_FOR_SIZE]
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,
                                       tf.lite.OpsSet.SELECT_TF_OPS]
tflite_quant_model = converter.convert()
open("converted_model.tflite", "wb").write(tflite_quant_model)
```

# Code to load tflite model
```import numpy as np
import tensorflow as tf

# Load TFLite model and allocate tensors.
interpreter = tf.lite.Interpreter(model_path="converted_model.tflite")
interpreter.allocate_tensors()

# Get input and output tensors.
input_details = interpreter.get_input_details()
print(input_details)
output_details = interpreter.get_output_details()
print(output_details)

# Test model on random input data.
input_shape = input_details[0]['shape']
input_data = np.array(np.random.random_sample(input_shape), dtype=np.float32)
interpreter.set_tensor(input_details[0]['index'], input_data)

interpreter.invoke()

# The function `get_tensor()` returns a copy of the tensor data.
# Use `tensor()` in order to get a pointer to the tensor.
output_data = interpreter.get_tensor(output_details[0]['index'])
print(output_data)
```
When load tflite load model path I get error message
```
$python test_quant.py
WARNING: Logging before flag parsing goes to stderr.
W0801 15:01:28.343195 140634983794496 __init__.py:328] Limited tf.compat.v2.summary API due to missing TensorBoard installation.
INFO: Initialized TensorFlow Lite runtime.
Traceback (most recent call last):
  File "test_quant.py", line 5, in <module>
    interpreter = tf.lite.Interpreter(model_path="converted_model.tflite")
  File "/home/guohuawu.wgh/miniconda3/envs/quant/lib/python3.6/site-packages/tensorflow_core/lite/python/interpreter.py", line 206, in __init__
    model_path))
ValueError: Input array not provided for operation 'reshape'.
```

**Comment by Hanoch666** [comment]
You can remove "the reshape layer", because the operation of "reshape" is  unsupported in tensorflow-1.15.0.

**Comment by ricardo-0x07** [comment]
@wugh  I'm having this same issues, where you able to resolve it

**Comment by ricardo-0x07** [comment]
@raziel Can we expect anything to be done about this
note for me only have this issue with the quantized version of the model

**Comment by raziel** [comment]
Hi.

Does the model convert if you don't set the quantization flag?
Meaning removing: converter.optimizations = [tf.lite.Optimize.OPTIMIZE_FOR_SIZE]

**Comment by ricardo-0x07** [comment]
@raziel and @suharshs Yes conversions completes successfully when the quantization flag is not set

**Comment by devarajnadiger** [comment]
Hi,
tf version-1.13
i created one tf lite model, to load this model i am using tensorflow code i.e

from __future__ import print_function
from absl import flags
import numpy as np
import tensorflow as tf

flags.DEFINE_string('model_path', None, 'Path to model.')
FLAGS = flags.FLAGS


def main(_):

  flags.mark_flag_as_required('model_path')

  # Load TFLite model and allocate tensors.
  interpreter = tf.lite.Interpreter(model_path=FLAGS.model_path)
  interpreter.allocate_tensors()

  # Get input and output tensors.
  input_details = interpreter.get_input_details()
  # print('input_details:', input_details)
  output_details = interpreter.get_output_details()
  # print('output_details:', output_details)

  # Test model on random input data.
  input_shape = input_details[0]['shape']
  # change the following line to feed into your own data.
  input_data = np.array(np.random.random_sample(input_shape), dtype=np.float32)
  interpreter.set_tensor(input_details[0]['index'], input_data)

  interpreter.invoke()
  output_data = interpreter.get_tensor(output_details[0]['index'])
  print(output_data)


if __name__ == '__main__':
  tf.app.run()


But i am getting error while running this code i.e:

   interpreter = tf.lite.Interpreter(model_path=FLAGS.model_path)
  File "/lib/python3.5/site-packages/tensorflow/lite/python/interpreter.py", line 55, in __init__
    model_path))
ValueError: Model provided has model identifier 'inpu', should be 'TFL3'

does anybody know about this error?
thanks in advance.

**Comment by raziel** [comment]
@devarajnadiger It seems your models is malformed. "TFL3" is the versioning info we include in the flatbuffer file. How did you created the model?
You should probably file another issue and include the model.

**Comment by devarajnadiger** [comment]
sorry @rachellj218. there was a mistake from my side i.e we should convert our checkpoints to pb twice to get tflite model as mentioned here: https://github.com/tensorflow/models/blob/master/research/lstm_object_detection/g3doc/exporting_models.md .
after following this, I was able to test my tflite model.

**Comment by TianHongZXY** [comment]
I have the same problem. Does tf2.0 support the reshape operation in tflite?

**Comment by zldrobit** [comment]
Hi all, I tried to debug the tensorflow source code to find the reason.
It seems that while quantizing the model, toco(tflite_convert)  misses putting the **new_shape** attribute in the ReshapeOptions of flatbuffers.
The only difference in ReshapeOptions between the unquantized and the quantized model is whether to have the **new_shape** attribute.
More interesting, the unquantized model barely has an empty list for new_shape.
By inserting an empty list for new_shape, I can successfully run my quantized model.
I also made a script  [fix_shape.py](https://github.com/zldrobit/onnx_tflite_yolov3/blob/master/fix_reshape.py) to temporarily fix the issue, plz refer to **Quantization** section in [onnx_tflite_yolov3](https://github.com/zldrobit/onnx_tflite_yolov3)

**Comment by neonbjb** [comment]
@zldrobit  - Thanks; your instructions worked to fix this issue for me.

@suharshs I can readily reproduce this issue on TF2. Feel free to contact me if you need any info. LDAP is jbetker.

**Comment by tabarkarajab** [comment]
> p
this code might help you.


import numpy as np
import tensorflow as tf

# Load TFLite model and allocate tensors.
interpreter = tf.lite.Interpreter(model_path="/content/drive/My Drive/Colab Notebooks/YOLO/optimized_pydnet++.tflite")
interpreter.allocate_tensors()

# Get input and output tensors.
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

# Test model on random input data.
input_shape = input_details[0]['shape']
input_data = np.array(np.random.random_sample(input_shape), dtype=np.float32)
interpreter.set_tensor(input_details[0]['index'], input_data)

interpreter.invoke()

# The function `get_tensor()` returns a copy of the tensor data.
# Use `tensor()` in order to get a pointer to the tensor.
output_data = interpreter.get_tensor(output_details[0]['index'])
#output_data.summary()
print(output_data)

**Comment by pchao6** [comment]
@wugh Hello, have you solved the problem? I met the same issue.

**Comment by mohantym** [comment]
Hi @wugh ! We are checking to see if you still need help in this issue or not .Have you tried latest versions yet ?

**Comment by dongtaishanybc** [comment]
tf information: tf.2.4.0  
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_dataset_gen
#converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
tflite_model = converter.convert()
open(output_model_filepath, "wb").write(tflite_model)


and 

interpreter = tf.lite.Interpreter(model_path=model_path)

 _interpreter_wrapper.CreateWrapperFromFile(
ValueError: Could not open("xx.tflite")


does anybody know about this error?
thanks in advance.

**Comment by zhangchucostel** [comment]
Hello  
he error message `interpreter = tf.lite.Interpreter(model_path=args.model)` occurs when TensorFlow Lite interpreter is unable to load the model at the specified `model_path`. Here are a few things you can try to fix this error:

1. Verify that the file exists:
Make sure that the model file exists at the specified path. If not, provide the correct path to the model in the `model_path` argument.

2. Check the file extension:
Ensure that you are specifying the correct file extension in the `model_path` argument. TensorFlow Lite models typically end with the extension `.tflite`.

3. Check TensorFlow Lite version:
Make sure that you are using the correct version of TensorFlow Lite that is compatible with your model. You may need to install a specific version of TensorFlow Lite to load your model.

Here's an example of loading a TensorFlow Lite model:

```
import tensorflow as tf

# Define the path to the TensorFlow Lite model file
model_path = "/path/to/tflite/model.tflite"

# Load the TensorFlow Lite model
try:
    interpreter = tf.lite.Interpreter(model_path=model_path)
    interpreter.allocate_tensors()

except ValueError as ve:
    print("Error loading the TensorFlow Lite model:", ve)
    exit()
```

In this example, we create an instance of the `tf.lite.Interpreter` class and pass in the `model_path` argument to load the model. We allocate tensors for the interpreter and catch any ValueError that may occur if there is an issue with the model file.
