### ISSUE TITLE
Specifying shapehandle's shape when creating new op in tensorflow (rank problem of the output tensor)

### ISSUE THREAD

**Issue by Kayee6** [tensorflow/tensorflow#31222]
System: Ubuntu 18.04
Tensorflow: 1.13.1
CuDNN: 7.4.2
CUDA: 10.2
NVIDIA: 430.26
Python: 3.6
GPU: 2080TI

I have successfully compiled the op registration file and tested when only using this file. But during training process, I tried to call the function defined in the op, these errors were encountered, which vary every time:

`Segmentation fault (core dumped)`

or

```
double free or corruption (!prev)
Aborted (core dumped)
```

or

```
Traceback (most recent call last):
  File "/home/tifo-kj/anaconda3/envs/tf13/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1659, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Shape must be rank 1 but is rank 99648624 for '...myop' (op: 'myop') with input shapes: [50,2048,3].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 327, in <module>
    network.build_graph(training=True)
  File "main.py", line 36, in build_graph
    reuse=None, bn_decay=self.bn_decay, up_ratio=opt.u)
  File "/home/.../graph.py", line 87, in graph
    p_out = myfunc(x)
  File "/home/.../myop.py", line 19, in myfunc
    return myop_module.myfunc(x)
  File "<string>", line 68, in myfunc
  File "/home/tifo-kj/anaconda3/envs/tf13/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/home/tifo-kj/anaconda3/envs/tf13/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/tifo-kj/anaconda3/envs/tf13/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/home/tifo-kj/anaconda3/envs/tf13/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1823, in __init__
    control_input_ops)
  File "/home/tifo-kj/anaconda3/envs/tf13/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1662, in _create_c_op
    raise ValueError(str(e))

ValueError: Shape must be rank 1 but is rank 99648624 for '...myop' (op: 'myop') with input shapes: [50, 1000, 3].
```

And please note the number `99648624` above is uncertain, sometimes it could be 0 or any weird number.

Below is the code for registering the op in tensorflow, where I specify the output's dimension as `(b,200,200,1)`:
 
````
.SetShapeFn([](::tensorflow::shape_inference::InferenceContext* c) {
        ::tensorflow::shape_inference::ShapeHandle input
        TF_RETURN_IF_ERROR(c->WithRank(c->input(0), 3, &input));   
        ::tensorflow::shape_inference::ShapeHandle dim2;
        TF_RETURN_IF_ERROR(c->MakeShapeFromShapeTensor(200, &dim2));    
        ::tensorflow::shape_inference::ShapeHandle dim3;
        TF_RETURN_IF_ERROR(c->MakeShapeFromShapeTensor(200, &dim3));    
        ::tensorflow::shape_inference::ShapeHandle dim4;
        TF_RETURN_IF_ERROR(c->MakeShapeFromShapeTensor(1, &dim4));    
        ::tensorflow::shape_inference::ShapeHandle output = c->MakeShape({c->Dim(input, 0), c->Dim(dim2, 0), c->Dim(dim3, 0), c->Dim(dim4, 0)});
        c->set_output(0, output);
        return Status::OK();
    });
````

I believe that in my code of op registration, the output shape has been already successfully determined. There is no similar question that I can find online. Please help!

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
