### ISSUE TITLE
auto-deeplab: nas_network runs into ValueError with personal data

### ISSUE THREAD

**Issue by lrizzello** [tensorflow/tensorflow#31329]
Hello,

I've been trying to use auto deeplab on my own dataset. The only part I touched is the stem creation. Instead of feeding a image set of dimension [?, y, x, 3] I feed data of dimension [?, y, x, 13]. The first 10 features of the last dimension correspond to character embeddings, and the last 3 are unrelated floats in the [0, 1] range. There are no NANs in this dataset.

To do this, I replace the beginning of the _nas_net function in nas_network.py. I get an array with shape [?, y, x, 4] as input, the first feature is a char ID to be replaced by a 10 dimensional embedding, the 3 other features stay as they are. This leads to a [?, y, x, 13] tensor which is then used by the rest of the code.

As my input seems sensible enough, I believe this may be a bug with the implementation. Could someone investigate this further, please?

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Tried on both ubuntu 18.04 and windows 10
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.13.1
- Python version: 3.7.3
- CUDA/cuDNN version: 10.1/ 7.6
- GPU model and memory: Nvidia Geforce GTX 1080TI 11GB on ubuntu, CPU on windows

**Describe the current behavior**
program crashes with error pasted at the bottom of this issue

**Describe the expected behavior**
auto deeplab keeps going as expected

**Code to reproduce the issue**
replace the content of /tensorflow/models/research/deeplab/core/nas_network.py by [this code](https://pastebin.com/jFu8EUxT) and run nas_network.py directly. The only modification I brought to this file, besides the new __main__ part at the bottom to run a simple fail case, can be found in the _nas_stem function.

**Other info / logs**
```
Traceback (most recent call last):
  File "C:/Users/lrizzello/source/repos/Company/Company.Python/deeplab/core/nas_network.py", line 308, in <module>
    hnasnet(all_features, pipeline_parameters, n_classes)
  File "C:/Users/lrizzello/source/repos/Company/Company.Python/deeplab/core/nas_network.py", line 294, in hnasnet
    final_endpoint=final_endpoint)
  File "C:/Users/lrizzello/source/repos/Company/Company.Python/deeplab/core/nas_network.py", line 183, in _build_nas_base
    cell_num=cell_num)
  File "C:\Users\lrizzello\source\repos\Company\Company.Python\deeplab\core\nas_cell.py", line 82, in __call__
    h = h1 + h2
  File "C:\Users\lrizzello\AppData\Local\Continuum\anaconda3\envs\py37\lib\site-packages\tensorflow\python\ops\math_ops.py", line 812, in binary_op_wrapper
    return func(x, y, name=name)
  File "C:\Users\lrizzello\AppData\Local\Continuum\anaconda3\envs\py37\lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 374, in add
    "Add", x=x, y=y, name=name)
  File "C:\Users\lrizzello\AppData\Local\Continuum\anaconda3\envs\py37\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\lrizzello\AppData\Local\Continuum\anaconda3\envs\py37\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\Users\lrizzello\AppData\Local\Continuum\anaconda3\envs\py37\lib\site-packages\tensorflow\python\framework\ops.py", line 3300, in create_op
    op_def=op_def)
  File "C:\Users\lrizzello\AppData\Local\Continuum\anaconda3\envs\py37\lib\site-packages\tensorflow\python\framework\ops.py", line 1823, in __init__
    control_input_ops)
  File "C:\Users\lrizzello\AppData\Local\Continuum\anaconda3\envs\py37\lib\site-packages\tensorflow\python\framework\ops.py", line 1662, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimensions must be equal, but are 14 and 13 for 'hnasnet/cell_5/comb_iter_0/combine/add' (op: 'Add') with input shapes: [?,14,25,40], [?,13,25,40].
```

**Comment by anush-o** [comment]
@lrizzello ,
After cloning and executing I got the following error `ModuleNotFoundError: No module named 'deeplab'` can you kindly help me resolving this?Thanks!

**Comment by lrizzello** [comment]
@anush-o 
Thanks for your reply, I just tried running my script directly from a clone of this repo and I can indeed see this error, even when moving the working directory to the right spot.

For now, the simplest way around this I can propose is to simply move the deeplab folder out of its parent folder. Fixed that error for me.

![image](https://user-images.githubusercontent.com/53616818/62537771-8c774800-b851-11e9-8bf0-a2f929b83bf1.png)

**Comment by oanush** [comment]
@lrizzello ,
Even after following the same steps as per your instruction with reference to screenshot below, same issue is being faced. 
![Mydetails](https://user-images.githubusercontent.com/52397990/62770423-a2d30d00-bab8-11e9-97f5-5da819673ec5.png)

**Comment by lrizzello** [comment]
If you're calling it from a command line, try adding

```
import sys
sys.path.append("")
```
to nas_network.py, before the deeplab imports

**Comment by jvishnuvardhan** [comment]
@lrizzello Please post this issue in models repo where the codeowners related to `deeplab` model will be able to resolve your issue. Thanks!

**Comment by lrizzello** [comment]
ok, I'll post it there
