### ISSUE TITLE
[freeze_graph]Node def expected inputs do not match with tf.keras layers

### ISSUE THREAD

**Issue by stefanpantic** [tensorflow/tensorflow#31358]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): Anaconda binary (```tensorflow-gpu```)
- TensorFlow version (use command below): ```b'unknown' 1.13.1```
- Python version: 3.6.7
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A (Because of conda binary)
- GPU model and memory: GTX 1080Ti, 11Gb

**Describe the current behavior**
When I try to freeze my TF graph that uses ```tf.keras``` layers I get the following exception.

```
Traceback (most recent call last):
  File "/home/stefan/miniconda3/envs/ds/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 426, in import_graph_def
    graph._c_graph, serialized, options)  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: NodeDef expected inputs '' do not match 1 inputs specified; Op<name=Const; signature= -> output:dtype; attr=value:tensor; attr=dtype:type>; NodeDef: {{node model/batch_normalization_v1/cond/Const_2}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stefan/Documents/work/asr/reproduce_bug/bug.py", line 100, in <module>
    export()
  File "/home/stefan/Documents/work/asr/reproduce_bug/bug.py", line 95, in export
    filename_tensor_name='')
  File "/home/stefan/miniconda3/envs/ds/lib/python3.6/site-packages/tensorflow/python/tools/freeze_graph.py", line 146, in freeze_graph_with_def_protos
    _ = importer.import_graph_def(input_graph_def, name="")
  File "/home/stefan/miniconda3/envs/ds/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/stefan/miniconda3/envs/ds/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 430, in import_graph_def
    raise ValueError(str(e))
ValueError: NodeDef expected inputs '' do not match 1 inputs specified; Op<name=Const; signature= -> output:dtype; attr=value:tensor; attr=dtype:type>; NodeDef: {{node model/batch_normalization_v1/cond/Const_2}}
```

It seems to be related to the ```tf.keras.layers.BatchNormalization```. When I pass the ```training=True``` or ```training=False``` to it the error goes away.

**Describe the expected behavior**
The graph should freeze no matter the ```training``` parameter.

**Code to reproduce the issue**
Standalone script required to reproduce.
```
import os

import tensorflow as tf
from tensorflow.python.keras.datasets import mnist
from tensorflow.python.tools import freeze_graph


class Model:
    def __init__(self):
        self._conv = tf.keras.layers.Conv2D(filters=64, kernel_size=5, activation=tf.nn.relu)
        self._batch_norm = tf.keras.layers.BatchNormalization()
        self._flatten = tf.keras.layers.Flatten()
        self._logits = tf.keras.layers.Dense(units=10)

    def forward(self, inputs):
        with tf.name_scope('model'):
            conv_out = self._conv(inputs)
            norm_out = self._batch_norm(conv_out)
            flat_out = self._flatten(norm_out)
            logits = self._logits(flat_out)

        return tf.identity(logits, name='logits')

    @staticmethod
    def loss(logits, labels):
        with tf.name_scope('loss'):
            loss = tf.losses.sparse_softmax_cross_entropy(labels=labels, logits=logits)

        return loss


def train():
    def map_fn(x, y):
        return tf.expand_dims(tf.math.divide(tf.cast(x, tf.float32), 255), axis=2), tf.cast(y, tf.int32)

    (x_train, y_train), (_, _) = mnist.load_data()

    dataset = tf.data.Dataset.from_tensor_slices((x_train, y_train))
    dataset = dataset.map(map_fn).batch(128).repeat(10)

    iterator = dataset.make_one_shot_iterator()
    inputs, labels = iterator.get_next()

    model = Model()
    logits = model.forward(inputs)
    loss = model.loss(logits, labels)

    with tf.name_scope('optimizer'):
        optimizer = tf.train.AdamOptimizer(learning_rate=1e4).minimize(loss,
                                                                       global_step=tf.train.get_or_create_global_step())

    with tf.train.MonitoredTrainingSession(checkpoint_dir='./tmp') as sess:
        while not sess.should_stop():
            print(sess.run([optimizer, loss])[1])


def export():
    tf.reset_default_graph()

    export_dir = './tmp/frozen'
    model = Model()

    inputs = tf.placeholder(dtype=tf.float32, shape=[None, 28, 28, 1], name='input_placeholder')
    _ = model.forward(inputs)

    with open('./tmp/checkpoint') as f:
        line = f.readline()
        checkpoint = line[line.find('"') + 1:line.rfind('"')]
        print(checkpoint)

    with tf.Session(graph=tf.get_default_graph()) as sess:
        saver = tf.train.Saver()

        sess.run(tf.global_variables_initializer())
        print(os.path.join('./tmp', checkpoint))
        saver.restore(sess, os.path.join('./tmp', checkpoint))

        builder = tf.saved_model.Builder('./tmp/frozen')
        builder.add_meta_graph_and_variables(sess, [tf.saved_model.tag_constants.SERVING], strip_default_attrs=True)
        builder.save()

        graph = tf.graph_util.remove_training_nodes(sess.graph.as_graph_def(), protected_nodes=['logits'])

        freeze_graph.freeze_graph_with_def_protos(
            input_graph_def=graph,
            input_saver_def=None,
            input_saved_model_dir=export_dir,
            saved_model_tags=[tf.saved_model.tag_constants.SERVING],
            input_checkpoint=os.path.join('./tmp', checkpoint),
            output_node_names='logits',
            output_graph=os.path.join('./tmp', 'frozen.pb'),
            clear_devices=True,
            initializer_nodes='',
            restore_op_name='',
            filename_tensor_name='')


if __name__ == '__main__':
    train()
    export()

```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ravikyram** [comment]
I have tried on colab with TF version 1.13.1 and was able to reproduce the issue.Please, find the [gist](https://colab.research.google.com/drive/1iQnd2Psdc__CByVhjj8yBsKcMaI2Q7pw) here.Tried reproducing the issue with TF 1.14,nightly versions and 2.0 beta versions we see the different errors.

**Comment by Piteryo** [comment]
I might be a bit late but setting `tf.keras.backend.set_learning_phase(0)` helps

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
