### ISSUE TITLE
provide custom library path

### ISSUE THREAD

**Issue by rakesh4osdd** [tensorflow/tensorflow#31475]
I have installed TensorFlow using "pip install tensorflow==1.13.1"
I am trying to run the TensorFlow with specific version 1.13.1
but it failed due to incompatible due to "ImportError: /lib64/libc.so.6: version `GLIBC_2.16' not found". 

I have already installed the glibc on path /opt/glibc_2.16/

If, I gave custom path using "export LD_LIBRARY_PATH=/opt/glibc_2.16/lib:$LD_LIBRARY_PATH"
Then "Segmentation fault (core dumped)" is shown.

How can I provide this path to tensorflow?
Please help.

(base) [rakesh@localhost rasax]$ ls /opt/glibc_2.16/
bin  etc  include  lib  libexec  sbin  share  var

For error reporting during run is given below:-

(base) [rakesh@localhost rasax]$ python -m tensorflow
Traceback (most recent call last):
  File "/home/rakesh/anaconda3/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/rakesh/anaconda3/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/rakesh/anaconda3/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/rakesh/anaconda3/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/rakesh/anaconda3/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /lib64/libc.so.6: version `GLIBC_2.16' not found (required by /home/rakesh/anaconda3/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rakesh/anaconda3/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/rakesh/anaconda3/lib/python3.7/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/home/rakesh/anaconda3/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/rakesh/anaconda3/lib/python3.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/rakesh/anaconda3/lib/python3.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/rakesh/anaconda3/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/rakesh/anaconda3/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/rakesh/anaconda3/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/rakesh/anaconda3/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/rakesh/anaconda3/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/rakesh/anaconda3/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /lib64/libc.so.6: version `GLIBC_2.16' not found (required by /home/rakesh/anaconda3/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by ymodak** [comment]
It looks like you are installing **TensorFlow** (TF) prebuilt binaries.

**TensorFlow release binaries version 1.6 and higher are prebuilt with AVX instruction sets.**
Therefore on any CPU that does not have these instruction sets, either CPU or GPU version of TF will fail to load.

Apparently, your CPU model does not support AVX instruction sets. You can still use TensorFlow with the alternatives given below:
* Try Google Colab to use TensorFlow.
    * The easiest way to use TF will be to switch to [google colab](https://colab.sandbox.google.com/notebooks/welcome.ipynb#recent=true). You get pre-installed latest stable TF version. Also you can use ```pip install``` to install any other preferred TF version.
    * It has an added advantage since you can you easily switch to different hardware accelerators     
      (cpu, gpu, tpu) as per the task. 
    * All you need is a good internet connection and you are all set.
* Try to build TF from sources by changing CPU optimization flags.

Please let us know if this helps.
