### ISSUE TITLE
saved_model_cli convert hub module to tensorRT model

### ISSUE THREAD

**Issue by vio-codes** [tensorflow/tensorflow#31518]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Colab Notebook
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:No
- TensorFlow installed from (source or binary): Provided by Colab
- TensorFlow version (use command below): Provided by Colab
- Python version: Provided by Colab
- Bazel version (if compiling from source): Provided by Colab
- GCC/Compiler version (if compiling from source): Provided by Colab
- CUDA/cuDNN version: Provided by Colab
- GPU model and memory: Provided by Colab

**Describe the current behavior**
I am saving the BigGan-Deep-512 module from the TF hub into a savedModel.
And when I try to convert it to a tensorRT module it fails

**Describe the expected behavior**
I expect that the **convert** should be applicable directly to the hub module.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
Code to save the hub module to a savedModel:

```
import os
import numpy as np
from datetime import datetime

import tensorflow as tf
import tensorflow_hub as hub
from tensorflow.python.summary import summary

print(tf.__version__)

with tf.Graph().as_default():
    module = hub.Module("https://tfhub.dev/deepmind/biggan-deep-512/1")
    initial_inputs = {k: tf.compat.v1.placeholder(v.dtype, v.get_shape().as_list(), k)
                      for k, v in module.get_input_info_dict().items()}
    output = module(initial_inputs)
    print(initial_inputs)
    print(output)
    init_op = tf.group([tf.global_variables_initializer(), tf.tables_initializer()])
    with tf.Session() as session:
        session.run(init_op)
        tf.saved_model.simple_save(
            session,
            "bg/serving_saved_model",
            inputs={'z': initial_inputs['z'], 'y': initial_inputs['y'], 'truncation': initial_inputs['truncation']},
            outputs={"output": output},
            legacy_init_op=tf.tables_initializer()
        )
```

Bash command to convert to tensorRT model:

```
%%bash

saved_model_dir=bg/serving_saved_model
opt_model_dir=bg/opt_saved_model

saved_model_cli convert --dir=${saved_model_dir} --output_dir=${opt_model_dir} --tag_set serve tensorrt --precision_mode FP32 --max_batch_size 1 --is_dynamic_op True
```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
Here are the logs: 

```
2019-08-11 11:52:49.646188: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2300000000 Hz
2019-08-11 11:52:49.646774: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5590ff396140 executing computations on platform Host. Devices:
2019-08-11 11:52:49.646832: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
2019-08-11 11:52:49.651856: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcuda.so.1
2019-08-11 11:52:49.799218: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-08-11 11:52:49.799757: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5590ff3979c0 executing computations on platform CUDA. Devices:
2019-08-11 11:52:49.799788: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Tesla T4, Compute Capability 7.5
2019-08-11 11:52:49.800013: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-08-11 11:52:49.800421: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties: 
name: Tesla T4 major: 7 minor: 5 memoryClockRate(GHz): 1.59
pciBusID: 0000:00:04.0
2019-08-11 11:52:49.800717: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.0
2019-08-11 11:52:49.801856: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10.0
2019-08-11 11:52:49.803002: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcufft.so.10.0
2019-08-11 11:52:49.803339: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcurand.so.10.0
2019-08-11 11:52:49.804771: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusolver.so.10.0
2019-08-11 11:52:49.805786: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusparse.so.10.0
2019-08-11 11:52:49.808901: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2019-08-11 11:52:49.809023: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-08-11 11:52:49.809465: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-08-11 11:52:49.809790: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1763] Adding visible gpu devices: 0
2019-08-11 11:52:49.814498: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.0
2019-08-11 11:52:49.815576: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-08-11 11:52:49.815605: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1187]      0 
2019-08-11 11:52:49.815613: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 0:   N 
2019-08-11 11:52:49.822976: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-08-11 11:52:49.823434: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-08-11 11:52:49.823790: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:40] Overriding allow_growth setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
2019-08-11 11:52:49.823830: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 13500 MB memory) -> physical GPU (device: 0, name: Tesla T4, pci bus id: 0000:00:04.0, compute capability: 7.5)
WARNING: Logging before flag parsing goes to stderr.
W0811 11:52:49.824687 139988375598976 deprecation.py:323] From /usr/local/lib/python2.7/dist-packages/tensorflow/python/compiler/tensorrt/trt_convert.py:245: load (from tensorflow.python.saved_model.loader_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.loader.load or tf.compat.v1.saved_model.load. There will be a new function for importing SavedModels in Tensorflow 2.0.
W0811 11:53:27.486973 139988375598976 deprecation.py:323] From /usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py:1276: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
W0811 11:53:48.502595 139988375598976 deprecation.py:323] From /usr/local/lib/python2.7/dist-packages/tensorflow/python/compiler/tensorrt/trt_convert.py:268: convert_variables_to_constants (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.convert_variables_to_constants`
W0811 11:53:48.502814 139988375598976 deprecation.py:323] From /usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/graph_util_impl.py:270: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.extract_sub_graph`
2019-08-11 11:53:54.431183: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-08-11 11:53:54.431681: I tensorflow/core/grappler/devices.cc:55] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 1
2019-08-11 11:53:54.431812: I tensorflow/core/grappler/clusters/single_machine.cc:359] Starting new session
2019-08-11 11:53:54.432418: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-08-11 11:53:54.432767: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties: 
name: Tesla T4 major: 7 minor: 5 memoryClockRate(GHz): 1.59
pciBusID: 0000:00:04.0
2019-08-11 11:53:54.432835: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.0
2019-08-11 11:53:54.432858: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10.0
2019-08-11 11:53:54.432869: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcufft.so.10.0
2019-08-11 11:53:54.432885: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcurand.so.10.0
2019-08-11 11:53:54.432900: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusolver.so.10.0
2019-08-11 11:53:54.432910: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusparse.so.10.0
2019-08-11 11:53:54.432920: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2019-08-11 11:53:54.432990: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-08-11 11:53:54.433378: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-08-11 11:53:54.433695: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1763] Adding visible gpu devices: 0
2019-08-11 11:53:54.433737: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-08-11 11:53:54.433754: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1187]      0 
2019-08-11 11:53:54.433762: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 0:   N 
2019-08-11 11:53:54.434036: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-08-11 11:53:54.434450: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-08-11 11:53:54.434793: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 13500 MB memory) -> physical GPU (device: 0, name: Tesla T4, pci bus id: 0000:00:04.0, compute capability: 7.5)
2019-08-11 11:54:02.561839: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:716] Optimization results for grappler item: tf_graph
2019-08-11 11:54:02.561909: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   constant folding: Graph size after: 7430 nodes (-10408), 12752 edges (-11753), time = 4901.51221ms.
2019-08-11 11:54:02.561918: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   layout: Graph size after: 7580 nodes (150), 13019 edges (267), time = 683.694ms.
2019-08-11 11:54:02.561924: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   constant folding: Graph size after: 7549 nodes (-31), 12986 edges (-33), time = 1578.22205ms.
Traceback (most recent call last):
  File "/usr/local/bin/saved_model_cli", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/tools/saved_model_cli.py", line 909, in main
    args.func(args)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/tools/saved_model_cli.py", line 680, in convert_with_tensorrt
    output_saved_model_dir=args.output_dir)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tensorrt/python/trt_convert.py", line 51, in create_inference_graph
    session_config=session_config)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/compiler/tensorrt/trt_convert.py", line 1148, in create_inference_graph
    trt_converter.save(output_saved_model_dir)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/compiler/tensorrt/trt_convert.py", line 825, in save
    super(TrtGraphConverter, self).save(output_saved_model_dir)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/compiler/tensorrt/trt_convert.py", line 432, in save
    importer.import_graph_def(self._converted_graph_def, name="")
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/importer.py", line 431, in import_graph_def
    raise ValueError(str(e))
ValueError: Input 0 of node module_apply_default/cond/AssignVariableOp/Switch was passed float from module/prev_truncation:0 incompatible with expected resource.

```

**Comment by ymodak** [comment]
I was able to reproduce the reported behavior with tf-nightly (1.15.0-dev20190812) as well.

**Comment by vio-codes** [comment]
@aaroey Any update on the issue?

**Comment by aaroey** [comment]
@vio-codes sorry for the late response. I think the root cause is not in TF-TRT but in the tool that freezes the graph. I can reproduce the problem with the following script:
```
ismdir = "the directory containing the saved hub model"
g = tf.Graph()
sess = tf.Session()
meta_graph_def = loader.load(sess, [tag_constants.SERVING], ismdir)
output_node_names = set()

def _gather_names(tensor_info):
  return set([tensor_info[key].name.split(":")[0] for key in tensor_info])

for key in meta_graph_def.signature_def:
  signature_def = meta_graph_def.signature_def[key]
  output_node_names.update(_gather_names(signature_def.inputs))
  output_node_names.update(_gather_names(signature_def.outputs))
frozen_graph_def = graph_util.convert_variables_to_constants(
    sess, sess.graph.as_graph_def(add_shapes=True), list(output_node_names))
g = tf.Graph()
with g.as_default():
  importer.import_graph_def(frozen_graph_def, name="")
```
Will need more time to investigate.

**Comment by aaroey** [comment]
The reason is, both `tf.compat.v1.graph_util.convert_variables_to_constants` and `convert_variables_to_constants_v2` doesn't update the datatype of the Switch nodes if their input was DT_RESOURCE before the variable->constant conversion. 

@gargn could you help to take a look at the v2 case? Thanks a lot.

**Comment by vio-codes** [comment]
Hello @gargn ,
Any update related to this issue?

**Comment by sushreebarsa** [comment]
Hi There,

We are checking to see if you still need help on this issue, as you are using an older version of tensorflow(1.x) which is officially considered as end of life. We recommend that you upgrade to 2.4 or later version and let us know if the issue still persists in newer versions.we will get you the right help.Thanks!
