### ISSUE TITLE
error while building wheel

### ISSUE THREAD

**Issue by alanpurple** [tensorflow/tensorflow#31523]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.3 x64
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version:  2.0.0-rc.0
- Python version: 3.7.4 x64
- Installed using virtualenv? pip? conda?: N/A
- Bazel version (if compiling from source): 0.26.1
- GCC/Compiler version (if compiling from source):  7.4.0
- CUDA/cuDNN version: 10.1/7.6.2
- GPU model and memory: GTX1080Ti GDDR5x 11GB X 6

**Describe the problem**
error while building wheels
**Provide the exact sequence of commands / steps that you executed before running into the problem**
```
bazel-bin/tensorflow/tools/pip_package/build_pip_package ~/tensorflow_pkgs/
```

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
```
Traceback (most recent call last):
  File "setup.py", line 308, in <module>
    keywords='tensorflow tensor machine learning',
  File "/home/wmind/anaconda3/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/home/wmind/anaconda3/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/wmind/anaconda3/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/wmind/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/wmind/anaconda3/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 230, in run
    impl_tag, abi_tag, plat_tag = self.get_tag()
  File "/home/wmind/anaconda3/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 179, in get_tag
    assert tag == supported_tags[0], "%s != %s" % (tag, supported_tags[0])
AssertionError: ('cp37', 'cp@pyvernodots@m', 'linux_x86_64') != ('cp37', 'cp@PYVERNODOTS@m', 'linux_x86_64')
```

**Comment by alanpurple** [comment]
I downgraded python to 3.7.3 and then no problem.

looks like an issue with python 3.7.4

**Comment by alanpurple** [comment]
fixed with conda python update and tensorflow sh update
