### ISSUE TITLE
model.fit_generator() multithreading is broken in tf.keras

### ISSUE THREAD

**Issue by Pyrestone** [tensorflow/tensorflow#31546]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): **YES**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Platform-independent
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): From pip
- TensorFlow version (use command below): 1.14.0 and 2.0
- Python version: 3.6.7

### **Summary**
fit_generator has an option called *workers*, setting this to >1 will use multithreading to queue up batches from a generator.

It raises an exception if the generator is not thread-safe. this is expected. However, **it does not accept thread-safe generators.**

### **Describe the current behavior**
Calling model.fit_generator on a keras model in tf 2.0 or compat.v2 **using a generator object, subclassed from collections.Generator** raises an exception that the given generator object does not have a shape attribute.

This is rooted in the calling of model_iteration which then unsuccessfully attempts to find out wether the generator is in fact a generator by using inspect.isgenerator(), which only recognizes native python generators (constructed by a function containing a yield statement)

however, **native python generators cannot be thread-safe**, thus fit_generator with workers>1 and use_multiprocessing is broken in tf.keras

### **Describe the expected behavior**
In keras 2.2.4, fit_generator simply calls the next(gen) function on the generator provided to fit_generator(). this is working as expected.

**Code to reproduce the issue**

```Python
import numpy as np

#switch here to switch between working keras and non-working tf.keras code
do_broken=True 

if do_broken:
    import tensorflow.compat.v2 as tf
    from tensorflow.compat.v2 import keras
    from tensorflow.compat.v2.keras.layers import Dense
    from tensorflow.compat.v2.keras.models import Sequential
    tf.enable_v2_behavior()
else:
    import keras
    from keras.layers import Dense
    from keras.models import Sequential

import threading
from collections import Generator

class mwe_gen(Generator):
    
    def __init__(self,train_data,train_labels,batch_size):
        self.train_data=train_data
        self.train_labels=train_labels
        self.batch_size=batch_size
        self.batch=0
        self.lock=threading.Lock()

    def __iter__(self):
        return self

    def __next__(self):
        return self.next()
    
    def next(self):
        with self.lock:
            batch=self.batch
            batch_size=self.batch_size
            self.batch=self.batch+self.batch_size
            if self.batch>len(self.train_data):
                self.batch=0
        batch_data=self.train_data[batch:batch+batch_size]
        batch_labels=self.train_labels[batch:batch+batch_size]
        return (batch_data,batch_labels)
    
    def send(self,arg):
        return self.next()
    
    def close(self):
        """Raise GeneratorExit inside generator.
        """
        try:
            self.throw(GeneratorExit)
        except (GeneratorExit, StopIteration):
            pass
        else:
            raise RuntimeError("generator ignored GeneratorExit")
    
    def throw(self, type=None, value=None, traceback=None):
        raise StopIteration
        
train_data=np.random.normal(size=(10,1))
train_labels=np.random.normal(size=(10,1))

gen=mwe_gen(train_data,train_labels,5)

model=Sequential()
model.add(Dense(1,input_shape=(1,)))

model.compile(loss="mse",optimizer="sgd")

model.fit_generator(gen,steps_per_epoch=2)

```

**Other info / logs**
```Python

Traceback (most recent call last):
  File "multithreaded_gen.py", line 72, in <module>
    model.fit_generator(gen,steps_per_epoch=2)
  File "C:\Users\PYRESTONE\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1433, in fit_generator
    steps_name='steps_per_epoch')
  File "C:\Users\PYRESTONE\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\engine\training_generator.py", line 144, in model_iteration
    shuffle=shuffle)
  File "C:\Users\PYRESTONE\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\engine\training_generator.py", line 480, in convert_to_generator_like
    num_samples = int(nest.flatten(data)[0].shape[0])
AttributeError: 'mwe_gen' object has no attribute 'shape'

```

**Comment by ravikyram** [comment]
I have tried on colab with TF version 1.14, nightly versions, 2.0.0-dev20190813 and was able to reproduce the issue.Please, find the [gist ](https://colab.research.google.com/drive/1yAK1iG0wdAo51uDk6YGifdV2-vpiEzqm)here.Thanks!

**Comment by mdew192837** [comment]
@robieta , Just to confirm, is this fixed with `tf` version `2.1.0`? (aka how do I check?)

Thanks!
