### ISSUE TITLE
tf.signal.stft does not work in eager execution mode

### ISSUE THREAD

**Issue by pplantinga** [tensorflow/tensorflow#31591]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Manjaro
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.14.0
- Python version: 3.7
- CUDA/cuDNN version: 10.1/7.6
- GPU model and memory: GTX 1060

**Describe the current behavior**
tf.signal.stft does not work in eager execution mode, producing the error:

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/site-packages/tensorflow/python/ops/signal/spectral_ops.py", line 83, in stft
    signals, frame_length, frame_step, pad_end=pad_end)
  File "/usr/lib/python3.7/site-packages/tensorflow/python/ops/signal/shape_ops.py", line 120, in frame
    num_outer_dimensions = array_ops.size(outer_dimensions)
  File "/usr/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py", line 416, in size
    return size_internal(input, name, optimize=True, out_type=out_type)
  File "/usr/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py", line 437, in size_internal
    num_elements = np.prod(input._shape_tuple(), dtype=np_out_type)  # pylint: disable=protected-access
  File "/usr/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 2772, in prod
    initial=initial)
  File "/usr/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'`

**Describe the expected behavior**
tf.signal.stft should work as it does without eager execution

**Code to reproduce the issue**
`import tensorflow as tf
tf.enable_eager_execution()
input = tf.keras.Input([None])
spec = tf.signal.stft(input, 400, 160)`

**Comment by gowthamkpr** [comment]
Was able to reproduce the error in [TF 2.0 Beta](https://colab.sandbox.google.com/gist/gowthamkpr/74a254946776db6e740d9a0ad9ed40c8/untitled89.ipynb) and also in [TF1.14](https://colab.sandbox.google.com/gist/gowthamkpr/6e84c9853c21172a507ba5c7267ebb3d/untitled87.ipynb).

**Comment by WindQAQ** [comment]
@pplantinga Hi, I think you just missed the lambda layer. Because the functional API is used to building graph, so the tensor operations have to be wrapped in `tf.keras.layers.Layer` instance. So, a workable example should be
```python
import tensorflow as tf

tf.enable_eager_execution()

input = tf.keras.Input([None])
spec = tf.keras.layers.Lambda(lambda x: tf.signal.stft(x, 400, 160))(input)
model = tf.keras.Model(inputs=input, outputs=spec)

y = model(tf.random.uniform(minval=-100, maxval=100, shape=(100, 10000), dtype=tf.float32))
print(y)
```
If you don't really want to build graph via functional API, the following example can manipulate `stft` result eagerly:
```python
import tensorflow as tf

tf.enable_eager_execution()

x = tf.random.uniform(minval=-100, maxval=100, shape=(100, 10000), dtype=tf.float32)
print(tf.signal.stft(x, 400, 160))
```

See more details about [functional API](https://www.tensorflow.org/beta/guide/keras/functional). Thanks!
