### ISSUE TITLE
cannot import tensorflow 

### ISSUE THREAD

**Issue by ongoing0217** [tensorflow/tensorflow#31630]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 Home 64 bit
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 1.14.0
- Python version: 3.7.0
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 9.0 / 6.0 *
- GPU model and memory: GeForce 940M (can't seem to find the memory of this card)

**Describe the problem**

importError is raised when I attempt to import tensorflow

**Provide the exact sequence of commands / steps that you executed before running into the problem**

>>>import tensorflow as tf

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\venv\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\venv\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: 找不到指定的模块。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\venv\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\venv\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: 找不到指定的模块。

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

*: I can't install CUDA 8.0 on my computer, because most of the modules failed to install, so I used 9.0 instead

**Comment by ongoing0217** [comment]
I tried to install CUDA 10.0 but failed to install most files

**Comment by gadagashwini** [comment]
@ongoing0217 Tensorflow version >=1.13 requires CUDA 10.0. Can you downgrade the Tensorflow version to 1.12 and check the import tensorflow. Thanks!

**Comment by ongoing0217** [comment]
How do you downgrade the version of tensorflow? Sorry for being a big noob :/

**Comment by gadagashwini** [comment]
@ongoing0217 Try the `pip install tensorflow-gpu==1.12.0`. Let us know how it progresses. Thanks!

**Comment by ongoing0217** [comment]
@gadagashwini the command prompt windows pops up from pip, saying "collecting tensorflow-gpu==1.12.0" then just closes, as if tensorflow is already installed--which is true, I still have 1.14.0 tf installed.
btw, I should be the one thanking you :P

**Comment by gadagashwini** [comment]
@ongoing0217 Try uninstalling the already installed Tensorflow by `pip uninstall tensorflow-gpu` . Later install tensorflow-gpu==1.12.0. Let us know if this helps. Thanks!

**Comment by ongoing0217** [comment]
@gadagashwini I tried uninstalling then reinstalling. Initially, pip started uninstalling tf and everything seemed fine, but when I install tf 1.12.0 the situation with the previous comment happened again. I tried installing tf 1.14.0 again and it said "requirements already installed" and repeated many times. I think pip didn't uninstall all the things, and so trying to install another tf won't work? is there any other way to get around this problem?

**Comment by gadagashwini** [comment]
@ongoing0217, Did you try creating virtual environment and install Tf there. If not try
`pip install virtualenv`. Thanks!

**Comment by gadagashwini** [comment]
@ongoing0217, Other option you can use conda. Please follow the instructions mentioned in this [link](https://github.com/jvishnuvardhan/Installing-TensorFlow-GPU-on-Windows-10-TF1.12). Let us know if that solves your problem. Thanks!

**Comment by ongoing0217** [comment]
@gadagashwini I was busy and could not respond, sorry
In this period, I downgraded tensorflow-gpu to 1.12.0 and reapplied my previous setup with CUDA 9.0, reinstalled cuDNN 7.5, and I can actually import tensorflow and error messages won't be raised. However, when I tried to test if the package was actually working using tf.Session(), my command prompt just stops working.

>>> hello=tf.constant('hello world')
>>> sess=tf.Session()
2019-08-24 13:26:29.884962: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2019-08-24 13:26:30.375610: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties:
name: GeForce 940M major: 5 minor: 0 memoryClockRate(GHz): 1.176
pciBusID: 0000:01:00.0
totalMemory: 2.00GiB freeMemory: 1.65GiB
2019-08-24 13:26:30.376042: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0

**Comment by ongoing0217** [comment]
@gadagashwini seems like the issue somehow sort itself out, so all my problems are solved. Thanks for answering my questions :D
