### ISSUE TITLE
Keras -> TfLite (AttributeError: 'Node' object has no attribute 'output_masks')

### ISSUE THREAD

**Issue by Jbiloki** [tensorflow/tensorflow#31649]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac OS
- TensorFlow installed from (source or binary): Source
- TensorFlow version (or github SHA if from source): 1.14.0

**Provide the text output from tflite_convert**

```
>>> converter = tf.lite.TFLiteConverter.from_keras_model_file('nlp-lite/app/src/main/python/deeplearning/models/parsing/en/Deep_CRF.h5', custom_objects=custom_objects)
WARNING: Logging before flag parsing goes to stderr.
W0814 17:56:27.203332 4401333696 deprecation.py:506] From /anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/keras/initializers.py:119: calling RandomUniform.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
W0814 17:56:27.470824 4401333696 deprecation_wrapper.py:119] From /anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/lite/python/lite.py", line 747, in from_keras_model_file
    keras_model = _keras.models.load_model(model_file, custom_objects)
  File "/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/keras/saving/save.py", line 146, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
  File "/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 212, in load_model_from_hdf5
    custom_objects=custom_objects)
  File "/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/keras/saving/model_config.py", line 55, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/keras/layers/serialization.py", line 89, in deserialize
    printable_module_name='layer')
  File "/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 192, in deserialize_keras_object
    list(custom_objects.items())))
  File "/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 1131, in from_config
    process_node(layer, node_data)
  File "/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 1087, in process_node
    layer(flat_input_tensors[0], **kwargs)
  File "/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/keras/engine/base_layer.py", line 443, in __call__
    previous_mask = _collect_previous_mask(inputs)
  File "/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/keras/engine/base_layer.py", line 1311, in _collect_previous_mask
    mask = node.output_masks[tensor_index]
AttributeError: 'Node' object has no attribute 'output_masks'
```

Model:

```
from keras_contrib.metrics import crf_viterbi_accuracy, crf_accuracy
from keras_contrib.losses import crf_loss
from keras_contrib.layers import CRF


from keras.preprocessing.sequence import pad_sequences
from keras.preprocessing.text import Tokenizer

from keras.callbacks import ModelCheckpoint, EarlyStopping, CSVLogger
from keras.utils import to_categorical
from keras import backend as K


# Defining the network dependencies
from keras.layers import LSTM, Dense, Embedding, Input, TimeDistributed, Flatten, Lambda
from keras.models import load_model, Model
def make_model():
        #layers comes from a pretrained model
        lm_model.layers[1].trainable = False
        lm_model.layers[1].input_length = None
        lm_model.layers[1].batch_input_shape = (None, None, 1)
        lm_model.layers[2].batch_input_shape = (1, None, 1)
        lm_model.layers[2].stateful = False
        crf_input = Input(batch_shape=(None, None, 1))
        crf_emb = lm_model.layers[1](crf_input)
        reshape = Lambda(lambda x: K.squeeze(x, 2))(crf_emb)
        crf_lstm = lm_model.layers[2](reshape)
        crf_dense1 = TimeDistributed(Dense(TD_nodes, activation='relu'))(crf_lstm)
        crf_out = CRF(n_tags, sparse_target=True)(crf_dense1)
        crf_model = Model(inputs=crf_input, outputs=crf_out)
        crf_model.compile(optimizer='rmsprop', loss=crf_loss, metrics=[crf_viterbi_accuracy, crf_accuracy, 'accuracy'])
```

I am using CRF from Keras Contrib

**Comment by gargn** [comment]
`TFLiteConverter.from_keras_model_file` only supports `tf.keras` models ([documentation](https://www.tensorflow.org/api_docs/python/tf/lite/TFLiteConverter#from_keras_model_file)). Therefore, your imports in the model generation code need to be `from tensorflow.keras...` instead of `from keras...`.

**Comment by Jbiloki** [comment]
@gargn I see, thanks!
