### ISSUE TITLE
AttributeError: 'Tensor' object has no attribute 'shape'

### ISSUE THREAD

**Issue by dtracers** [tensorflow/tensorflow#3165]
### Environment info
Operating System:  BashOn Windows

Installed version of CUDA and cuDNN: 
(doesnt matter CPU version only)

If installed from binary pip package, provide:
0.9.0

If installed from sources, provide the commit hash:

### Steps to reproduce

```
    def create_classifier(self):
        hiddenLayers = [self.num_points, self.num_points * 2, 10]
        self.classifier = tf.contrib.learn.DNNClassifier(hidden_units=hiddenLayers)
```

label is a string
point list is a list of an array of x, y values
ex:
```
[[1,2],[2,3],[3,4],...]
```
```
    def train(self, label, point_list):
        points = self.resample(point_list, self.num_points)
        utils.strip_ids_from_points(points)
        value_class = 1 if label == self.label else 0
        target = tf.reshape(tf.constant(value_class), [1])
        print 'training classifier to recognize value as: [' + str(value_class) + '] label is ' + label + ' class is ' + self.label
        point_tensor = tf.convert_to_tensor(points, dtype=tf.float32)
        reshaped_tensor = tf.reshape(point_tensor, [1, self.num_points * 2])
        print reshaped_tensor
        print target
        self.classifier.fit(x=reshaped_tensor, y=target, steps=1)
```

### What have you tried?
googling why a tensor would not have a shape attribute

### Logs or other output that would be helpful
```
Tensor("Reshape_1:0", shape=(1, 64), dtype=float32)
Tensor("Reshape:0", shape=(1,), dtype=int32)
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    connection.start_socket(8089, callback=handler.message_processor)
  File "/mnt/d/workspace/SketchRecognitionWithTensorFlow/src/main/python/connection/python_socket_server.py", line 13, in start_socket
    process_message(connection, callback=callback)
  File "/mnt/d/workspace/SketchRecognitionWithTensorFlow/src/main/python/connection/python_socket_server.py", line 38, in process_message
    result = callback(general_proto)
  File "/mnt/d/workspace/SketchRecognitionWithTensorFlow/src/main/python/recognition/proto_handler.py", line 39, in message_processor
    return train_shape(general_proto.template)
  File "/mnt/d/workspace/SketchRecognitionWithTensorFlow/src/main/python/recognition/proto_handler.py", line 23, in train_shape
    rec.add_training_data(recognition_template.interpretation.label, recognition_template.shape)
  File "/mnt/d/workspace/SketchRecognitionWithTensorFlow/src/main/python/recognition/recognition_manager.py", line 98, in add_training_data
    self.recognizers[label].train(label, points)
  File "/mnt/d/workspace/SketchRecognitionWithTensorFlow/src/main/python/recognition/simple/recognizer.py", line 78, in train
    self.classifier.fit(x=reshaped_tensor, y=target, steps=1)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 173, in fit
    input_fn, feed_fn = _get_input_fn(x, y, batch_size)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 67, in _get_input_fn
    x, y, n_classes=None, batch_size=batch_size)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/io/data_feeder.py", line 117, in setup_train_data_feeder
    X, y, n_classes, batch_size, shuffle=shuffle, epochs=epochs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/io/data_feeder.py", line 239, in __init__
    self.X.shape, None if self.y is None else self.y.shape, n_classes,
AttributeError: 'Tensor' object has no attribute 'shape'
```

**Comment by dtracers** [comment]
Okay figured it out.  Fit can not take a tensor as an input.  (it would be helpful if that was the error message instead)

**Comment by sguada** [comment]
Actually there is a bug in data_feeder.py it should use get_shape() instead .shape.

**Comment by Qululu** [comment]
I'm also having this issue. I'm using LinearClassifier. I tried passing the X argument as a tensor, Pandas dataframe, and NumPy matrix. None work and all attempts result in the same AttributeError.

Is there any progress with this? Thanks!

**Comment by martinwicke** [comment]
Have you tried at head? We know there's a bug in 0.9, but it should work at head.

**Comment by girving** [comment]
Closing for now since @martinwicke says this is fixed.
