### ISSUE TITLE
fully_connected_preloaded example: Attempting to use uninitialized value input/input_producer/input_producer/fraction_of_32_full/limit_epochs/epochs

### ISSUE THREAD

**Issue by MatthieuBizien** [tensorflow/tensorflow#3168]
I have the error `Attempting to use uninitialized value input/input_producer/input_producer/fraction_of_32_full/limit_epochs/epochs` when I load data in my code. I have found the same issue on the fully_connected_preloaded example, so I think it may be a regression.

### Environment info
Operating System: Ubuntu 16.04

Installed version of CUDA and cuDNN: Cuda 8.0 and CuDnn 8.0

```bash
$ ls -l /path/to/cuda/lib*/libcud*
-rw-r--r-- 1 root root   560184 juin  30 00:45 /usr/local/cuda/lib64/libcudadevrt.a
lrwxrwxrwx 1 root root       16 juin  30 00:45 /usr/local/cuda/lib64/libcudart.so -> libcudart.so.8.0
lrwxrwxrwx 1 root root       19 juin  30 00:45 /usr/local/cuda/lib64/libcudart.so.8.0 -> libcudart.so.8.0.27
-rwxr-xr-x 1 root root   394472 juin  30 00:45 /usr/local/cuda/lib64/libcudart.so.8.0.27
-rw-r--r-- 1 root root   737516 juin  30 00:45 /usr/local/cuda/lib64/libcudart_static.a
-rwxr-xr-x 1 root root 78065952 juin  30 01:08 /usr/local/cuda/lib64/libcudnn.so
-rwxr-xr-x 1 root root 78065952 juin  30 01:08 /usr/local/cuda/lib64/libcudnn.so.5
-rwxr-xr-x 1 root root 78065952 juin  30 01:08 /usr/local/cuda/lib64/libcudnn.so.5.0.5
-rw-r--r-- 1 root root 68709594 juin  30 01:08 /usr/local/cuda/lib64/libcudnn_static.a
```

If installed from sources, provide the commit hash: db90885e9f27b1e069dd689ddd2dd3b743ed1cb7

### Steps to reproduce
1. cd tensorflow/examples/how_tos/reading_data
2. python fully_connected_preloaded.py

### What have you tried?
1. `bazel run -c opt tensorflow/examples/how_tos/reading_data:fully_connected_preloaded``
2. `python fully_connected_preloaded.py`
3. My code, which is similar

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

```python
python fully_connected_preloaded.py
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
Extracting /tmp/data/train-images-idx3-ubyte.gz
Extracting /tmp/data/train-labels-idx1-ubyte.gz
Extracting /tmp/data/t10k-images-idx3-ubyte.gz
Extracting /tmp/data/t10k-labels-idx1-ubyte.gz
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 0 with properties:
name: GeForce GTX 1080
major: 6 minor: 1 memoryClockRate (GHz) 1.7335
pciBusID 0000:02:00.0
Total memory: 7.92GiB
Free memory: 7.52GiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:126] DMA: 0
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 0:   Y
I tensorflow/core/common_runtime/gpu/gpu_device.cc:838] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1080, pci bus id: 0000:02:00.0)
Saving
W tensorflow/core/framework/op_kernel.cc:936] Out of range: FIFOQueue '_1_input/input_producer/input_producer/fraction_of_32_full/fraction_of_32_full' is closed and has insufficient elements (requested 1, current size 0)
	 [[Node: input/input_producer/fraction_of_32_full_Dequeue = QueueDequeue[_class=["loc:@input/input_producer/input_producer/fraction_of_32_full/fraction_of_32_full"], component_types=[DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](input/input_producer/input_producer/fraction_of_32_full/fraction_of_32_full)]]
Done training for 2 epochs, 0 steps.
Traceback (most recent call last):
  File "fully_connected_preloaded.py", line 157, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "fully_connected_preloaded.py", line 153, in main
    run_training()
  File "fully_connected_preloaded.py", line 148, in run_training
    coord.join(threads)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/coordinator.py", line 333, in join
    six.reraise(*self._exc_info_to_raise)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/queue_runner.py", line 185, in _run
    sess.run(enqueue_op)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 382, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 655, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 723, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 743, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors.FailedPreconditionError: Attempting to use uninitialized value input/input_producer/input_producer/fraction_of_32_full/limit_epochs/epochs
	 [[Node: input/input_producer/input_producer/fraction_of_32_full/limit_epochs/CountUpTo = CountUpTo[T=DT_INT64, _class=["loc:@input/input_producer/input_producer/fraction_of_32_full/limit_epochs/epochs"], limit=2, _device="/job:localhost/replica:0/task:0/cpu:0"](input/input_producer/input_producer/fraction_of_32_full/limit_epochs/epochs)]]
Caused by op u'input/input_producer/input_producer/fraction_of_32_full/limit_epochs/CountUpTo', defined at:
  File "fully_connected_preloaded.py", line 157, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "fully_connected_preloaded.py", line 153, in main
    run_training()
  File "fully_connected_preloaded.py", line 73, in run_training
    [input_images, input_labels], num_epochs=FLAGS.num_epochs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/input.py", line 266, in slice_input_producer
    shared_name=shared_name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/input.py", line 223, in range_input_producer
    shared_name, name, "fraction_of_%d_full" % capacity)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/input.py", line 133, in input_producer
    input_tensor = limit_epochs(input_tensor, num_epochs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/input.py", line 84, in limit_epochs
    counter = epochs.count_up_to(num_epochs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variables.py", line 573, in count_up_to
    return state_ops.count_up_to(self._variable, limit=limit)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_state_ops.py", line 127, in count_up_to
    result = _op_def_lib.apply_op("CountUpTo", ref=ref, limit=limit, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 703, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2297, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1231, in __init__
    self._traceback = _extract_stack()
```

**Comment by aselle** [comment]
This appears to be a regression since r0.9. Can you try r0.9 and see if it works for you?

**Comment by aselle** [comment]
Assigning @josh11b as he is the original author of fully_connected_preloaded.py

**Comment by mariolew** [comment]
Same issue with cuda-7.0 cudnn v4 and tesla k40c.

**Comment by fengyang0317** [comment]
`init_op = tf.group(tf.initialize_all_variables(),
                           tf.initialize_local_variables())`
solves the issue

**Comment by TimZaman** [comment]
usage of `num_epochs` means you apparently _have_ to use `initialize_local_variables()`

**Comment by aselle** [comment]
@MatthieuBizien, could you confirm that your issue is resolved by using initialize_local_variables so we can close hte issue?

**Comment by TimZaman** [comment]
This issue is already closed though.

**Comment by llhe** [comment]
The issue resolved in my case by calling initialize_local_variables(). It's a regression compared with r0.9.

**Comment by aselle** [comment]
Thanks for the update.
