### ISSUE TITLE
How to append placeholder tf.gradient and things like that to a multiprocess.Manager.list

### ISSUE THREAD

**Issue by zkx741481546** [tensorflow/tensorflow#31685]
I want to share some objects between different process, but my class has some tensorflow object in it ,and triggered an error message

Process Process-7:
Traceback (most recent call last):
  File "C:\Users\zkx74\Anaconda3\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "C:\Users\zkx74\Anaconda3\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\zkx74\PycharmProjects\DDPG_QuantTrade\MADDPG.py", line 162, in init_nn
    agent_list.append(ACModel(actor, None, env, current_stock_state, current_agent_state))
  File "<string>", line 2, in append
  File "C:\Users\zkx74\Anaconda3\lib\multiprocessing\managers.py", line 795, in _callmethod
    conn.send((self._id, methodname, args, kwds))
  File "C:\Users\zkx74\Anaconda3\lib\multiprocessing\connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "C:\Users\zkx74\Anaconda3\lib\multiprocessing\reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: can't pickle _thread.RLock objects

the code is here: https://paste.ubuntu.com/p/Z54XbRkk8h/

**Comment by ravikyram** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
