### ISSUE TITLE
Debugging tf.Keras Models with TFDBG get TypeError: Fetch argument None has invalid type <class 'NoneType'>

### ISSUE THREAD

**Issue by zhen8838** [tensorflow/tensorflow#31681]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution ( Linux Ubuntu 18.04):
- TensorFlow installed from (source or binary):  binary
- TensorFlow version (use command below): tensorflow-gpu  1.14.0     
- Python version: python 3.7.1
- CUDA/cuDNN version: CUDA 10.1  cuDNN 7.5
- GPU model and memory: GTX 2060 

**Describe the current behavior**

I want to use debugging tf.keras model, but got an error message like:
```sh
Traceback (most recent call last):
  File "./debug_keras.py", line 82, in <module>
    vae.add_loss(loss_fn(x_in, x_out, μ, σ))
  File "/home/zqh/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 917, in add_loss
    new_layers = base_layer_utils.create_keras_history(symbolic_loss)
  File "/home/zqh/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer_utils.py", line 200, in create_keras_history
    _, created_layers = _create_keras_history_helper(tensors, set(), [])
  File "/home/zqh/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer_utils.py", line 244, in _create_keras_history_helper
    constants[i] = backend.function([], op_input)([])
  File "/home/zqh/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/backend.py", line 3292, in __call__
    run_metadata=self.run_metadata)
  File "/home/zqh/miniconda3/lib/python3.7/site-packages/tensorflow/python/debug/wrappers/framework.py", line 628, in wrapped_runner
    callable_runner_args=feed_values)
  File "/home/zqh/miniconda3/lib/python3.7/site-packages/tensorflow/python/debug/wrappers/framework.py", line 569, in run
    run_metadata=run_metadata)
  File "/home/zqh/miniconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/home/zqh/miniconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1158, in _run
    self._graph, fetches, feed_dict_tensor, feed_handles=feed_handles)
  File "/home/zqh/miniconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 474, in __init__
    self._fetch_mapper = _FetchMapper.for_fetch(fetches)
  File "/home/zqh/miniconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 261, in for_fetch
    type(fetch)))
TypeError: Fetch argument None has invalid type <class 'NoneType'>

```

**Describe the expected behavior**

It should be work...

**Code to reproduce the issue**

run this python script, then type in:` run -t 10` will get an error message...
```python
import tensorflow.python as tf
from tensorflow.python import keras as k
from tensorflow.python.keras import layers as kl
from tensorflow.python.keras import activations as ka
import matplotlib.pyplot as plt
import numpy as np
from scipy.stats import norm
from scipy.special import expit
from tensorflow.python import debug as tfdebug

config = tf.ConfigProto()
config.gpu_options.allow_growth = True

k.backend.set_session(tfdebug.LocalCLIDebugWrapperSession(tf.Session(config=config)))
# k.backend.set_session(tf.Session(config=config))

(x_train, y_train), (x_test, y_test) = k.datasets.fashion_mnist.load_data()
x_train = np.expand_dims(x_train, -1) / 255.
x_test = np.expand_dims(x_test, -1) / 255.

image_size = 28
input_shape = (image_size, image_size, 1)
batch_size = 100
kernel_size = 3
filters = 16
latent_dim = 2  # 隐变量取2维只是为了方便后面画图
epochs = 30
tf.set_random_seed(9102)


def encoder_fn(inputs, filters):
    x = inputs
    for i in range(2):
        filters *= 2
        x = kl.Conv2D(filters=filters, kernel_size=kernel_size, activation='relu', strides=2, padding='same')(x)
    x = kl.Flatten()(x)
    x = kl.Dense(32, activation='relu')(x)
    μ = kl.Dense(latent_dim)(x)
    σ = kl.Dense(latent_dim)(x)
    return μ, σ


def sampling(args):
    """ 重参数技巧 """
    μ, σ = args
    ε = tf.random_normal(shape=tf.shape(μ))
    return μ + tf.exp(σ / 2) * ε


def decoder_fn(z, filters):
    x = kl.Dense(7 * 7 * 32, activation='relu')(z)
    x = kl.Reshape((7, 7, 32))(x)
    for i in range(2):
        x = kl.Conv2DTranspose(filters=filters, kernel_size=kernel_size, activation='relu', strides=2, padding='same')(x)
        filters //= 2
    x = kl.Conv2DTranspose(1, kernel_size, activation=None, padding='same')(x)
    return x


def loss_fn(inputs, outputs, μ, σ):
    # 这里求和的时候先按每个样本求和，再按样本求平均
    xent_loss = tf.reduce_sum(tf.nn.sigmoid_cross_entropy_with_logits(labels=x_in, logits=x_out), axis=[1, 2, 3])
    # xent_loss = tf.reduce_sum(k.backend.binary_crossentropy(x_in, x_out), axis=[1, 2, 3])
    kl_loss = - 0.5 * tf.reduce_sum(1 + σ - tf.square(μ) - tf.exp(σ), axis=-1)
    vae_loss = tf.reduce_mean(xent_loss + kl_loss)
    return vae_loss


x_in = k.Input(shape=(image_size, image_size, 1))
μ, σ = encoder_fn(x_in, filters)
z = kl.Lambda(sampling, output_shape=(latent_dim,))([μ, σ])

latent_inputs = k.Input(shape=(latent_dim,), dtype=tf.float32)
outputs = decoder_fn(latent_inputs, filters)
decoder = k.Model(latent_inputs, outputs)
x_out = decoder(z)


encoder = k.Model(x_in, μ)

vae = k.Model(x_in, x_out)
vae.add_loss(loss_fn(x_in, x_out, μ, σ))
vae.compile(k.optimizers.Nadam(0.001))
vae.fit(x=x_train, batch_size=batch_size, epochs=epochs, shuffle=True, validation_data=(x_test, None))
```
**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by gadagashwini** [comment]
Was able to reproduce the issue with Tensorflow 1.14.0.

**Comment by dahjan** [comment]
@zhen8838, were you ever able to find a solution to this? I am running into the same issue!

**Comment by zhen8838** [comment]
> @zhen8838, were you ever able to find a solution to this? I am running into the same issue!

This is a bug. You should try tensorflow 1.15 or tensorflow 2.0.  I'm not sure which version of the bug was fixed yet.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
