### ISSUE TITLE
AttributeError: 'module' object has no attribute 'linear'

### ISSUE THREAD

**Issue by fobus42** [tensorflow/tensorflow#3169]
I'm trying to run this tutorial : https://medium.com/@ilblackdragon/tensorflow-tutorial-part-1-c559c63c0cb1#.1a7hit535

I have got some errors on this bug report : https://github.com/tensorflow/tensorflow/issues/3167

Then I have tried to fix it by modifying the TF Learn code. 

### Environment info
Operating System: Linux Mint 17.3 Rosa
$uname -a

Linux Pabeda 3.19.0-32-generic #37~14.04.1-Ubuntu SMP Thu Oct 22 09:41:40 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

$python -c "import tensorflow; print(tensorflow.version)"
0.9.0

### Steps to reproduce
1. $ git clone https://github.com/ilblackdragon/tf_examples.git
2. edit /usr/local/lib/python2.7/dist-packages/skflow/trainer.py

Line 146 

replace
`if summaries `
with
`if summaries is not None:`

Line 167

replace
`if summaries  and summary_writer and summ is not None`
with
`if summaries is not None and summary_writer is not None and summ is not None:`

3.$python titanic.py

### Errors

Traceback (most recent call last):
  File "titanic.py", line 41, in <module>
    classifier.fit(X_train, y_train)
  File "/usr/local/lib/python2.7/dist-packages/skflow/estimators/base.py", line 200, in fit
    self._setup_training()
  File "/usr/local/lib/python2.7/dist-packages/skflow/estimators/base.py", line 139, in _setup_training
    self._inp, self._out)
  File "/usr/local/lib/python2.7/dist-packages/skflow/estimators/dnn.py", line 82, in _model_fn
    models.logistic_regression)(X, y)
  File "/usr/local/lib/python2.7/dist-packages/skflow/models.py", line 99, in dnn_estimator
    layers = dnn(X, hidden_units)
  File "/usr/local/lib/python2.7/dist-packages/skflow/ops/dnn_ops.py", line 39, in dnn
    tensor_in = tf.nn.rnn_cell.linear(tensor_in, n_units, True)
AttributeError: 'module' object has no attribute 'linear'

**Comment by aselle** [comment]
Like #3167, I believe the problem here is that @ilblackdragon tutorial is not up to date for 0.9. So I am closing for now.
