### ISSUE TITLE
Import of TF Failed

### ISSUE THREAD

**Issue by HeyHoe95** [tensorflow/tensorflow#31690]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): with pip
- TensorFlow version: 1.14 and 2.0.0-beta
- Python version: 3.7
- Installed using virtualenv? pip? conda?: installed with pip
- Bazel version (if compiling from source): not installed
- GCC/Compiler version (if compiling from source): Not used
- CUDA/cuDNN version: just using CPU
- GPU model and memory:  just using CPU

**Describe the problem** I cant import tensorflow. I guess there have been installation issues. I have this problem with both the old and the new version.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
pip install tensorflow==2.0.0-beta1
python
import tensorflow as tf

**Any other info / logs**
Traceback (most recent call last):
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.2\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python37\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python37\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: Eine DLL-Initialisierungsroutine ist fehlgeschlagen.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.2\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.2\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.2\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.2\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python37\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python37\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: Eine DLL-Initialisierungsroutine ist fehlgeschlagen.
Failed to load the native TensorFlow runtime.
See https://www.tensorflow.org/install/errors
for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by HeyHoe95** [comment]
How exactly do I add tis path?
The Doc says execute "SET PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin;%PATH%'.
What exactly do I have to write in %PATH%?

**Comment by ymodak** [comment]
TensorFlow release binaries version 1.6 and higher are prebuilt with AVX instruction sets.
Therefore on any CPU that does not have these instruction sets, either CPU or GPU version of TF will fail to load.
Does your CPU model does not support AVX instruction sets?.

**Comment by HeyHoe95** [comment]
I Run an Intel(R) Core(TM) i7 CPU 860.
I think it does.

**Comment by ymodak** [comment]
Did you download and install the Microsoft Visual C++ 2015 Redistributable Update 3?
https://visualstudio.microsoft.com/vs/older-downloads/

**Comment by HeyHoe95** [comment]
Yes Microsoft Visual C++ 2015 Redistributable Update 3 is installed.
I have noticed that "python3 --version" does not work.
Only "python --version" works fine. Is that a problem?

**Comment by ymodak** [comment]
That's fine. The problem is that your cpu model doesn't support AVX instruction sets.
See https://ark.intel.com/content/www/us/en/ark/products/41316/intel-core-i7-860-processor-8m-cache-2-80-ghz.html
 You can still use TensorFlow with the alternatives given below:
* Try Google Colab to use TensorFlow.
  * The easiest way to use TF will be to switch to [google colab](https://colab.sandbox.google.com/notebooks/welcome.ipynb#recent=true).You get pre-installed latest stable TF version. Also you can use```pip install``` to install any other preferred TF version.
  * It has an added advantage since you can you easily switch to different hardware accelerators (cpu, gpu, tpu) as per the task.
  * All you need is a good internet connection and you are all set.
* Try to build TF from sources by changing CPU optimization flags.

**Comment by HeyHoe95** [comment]
I use Google Colab now.
Thank you very much for your help you're awesome.
