### ISSUE TITLE
Check failed: array->has_shape()

### ISSUE THREAD

**Issue by kezakool** [tensorflow/tensorflow#31694]
Hi,

First, Thanks for all your work! i'm struggling to export my tf model to tflite, seeing the error, i think i got 2 problems : 
- input format
- unsupported ops
I can't find a way to solve this, maybe the issue is to do a more compatible tflite export when freezing the graph (close to something you did for export_tflite_ssd_graph.py but not sure i can make something equivalent for my case) 

if you can help me for documentations and or good workaround...

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): googlecolab Window 10 x64 in conda venv
- TensorFlow installed from (source or binary): binary
- TensorFlow version (or github SHA if from source): 1.14.0

**Provide the text output from tflite_convert**

ConverterError: TOCO failed. See console for info.
2019-08-16 13:17:37.784025: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: Enter
2019-08-16 13:17:37.794406: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: Enter
2019-08-16 13:17:37.794453: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: Enter
2019-08-16 13:17:37.794480: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: Enter
2019-08-16 13:17:37.794526: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: Enter
2019-08-16 13:17:37.794563: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: Enter
2019-08-16 13:17:37.794592: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: Enter
2019-08-16 13:17:37.794619: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: Enter
2019-08-16 13:17:37.794644: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: Enter
2019-08-16 13:17:37.794669: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: Enter
2019-08-16 13:17:37.794689: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: Enter
2019-08-16 13:17:37.794714: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: Enter
2019-08-16 13:17:37.794740: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: Enter
2019-08-16 13:17:37.794765: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: Enter
2019-08-16 13:17:37.794790: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: Enter
2019-08-16 13:17:37.819192: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: RFFT
2019-08-16 13:17:37.819259: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: ComplexAbs
2019-08-16 13:17:37.819678: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: TensorArrayV3
2019-08-16 13:17:37.819727: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2019-08-16 13:17:37.819759: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: TensorArrayV3
2019-08-16 13:17:37.819787: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2019-08-16 13:17:37.819814: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: Enter
2019-08-16 13:17:37.819844: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: Enter
2019-08-16 13:17:37.819871: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: Enter
2019-08-16 13:17:37.819896: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: Enter
2019-08-16 13:17:37.819921: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: Enter
2019-08-16 13:17:37.819942: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2019-08-16 13:17:37.819963: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: Enter
2019-08-16 13:17:37.819983: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2019-08-16 13:17:37.820005: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: TensorArrayScatterV3
2019-08-16 13:17:37.820048: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: Enter
2019-08-16 13:17:37.820076: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: LoopCond
2019-08-16 13:17:37.820127: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: Exit
2019-08-16 13:17:37.820214: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: TensorArrayReadV3
2019-08-16 13:17:37.820241: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: TensorArraySizeV3
2019-08-16 13:17:37.820319: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: TensorArrayGatherV3
2019-08-16 13:17:37.820434: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: TensorArrayWriteV3
2019-08-16 13:17:37.829208: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 420 operators, 721 arrays (0 quantized)
2019-08-16 13:17:37.841887: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After Removing unused ops pass 1: 401 operators, 686 arrays (0 quantized)
2019-08-16 13:17:37.854995: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 401 operators, 686 arrays (0 quantized)
2019-08-16 13:17:37.897923: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 1: 171 operators, 321 arrays (0 quantized)
2019-08-16 13:17:37.903043: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 2: 153 operators, 287 arrays (0 quantized)
2019-08-16 13:17:37.905901: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 3: 150 operators, 281 arrays (0 quantized)
2019-08-16 13:17:37.908277: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Group bidirectional sequence lstm/rnn: 150 operators, 281 arrays (0 quantized)
2019-08-16 13:17:37.909972: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before dequantization graph transformations: 150 operators, 281 arrays (0 quantized)
2019-08-16 13:17:37.912697: I tensorflow/lite/toco/allocate_transient_arrays.cc:345] Total transient array allocated size: 704 bytes, theoretical optimal value: 512 bytes.
2019-08-16 13:17:37.913694: E tensorflow/lite/toco/toco_tooling.cc:456] We are continually in the process of adding support to TensorFlow Lite for more ops. It would be helpful if you could inform us of how this conversion went by opening a github issue at https://github.com/tensorflow/tensorflow/issues/new?template=40-tflite-op-request.md
 and pasting the following:

Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, CAST, CONCATENATION, CONV_2D, DIV, EQUAL, EXPAND_DIMS, FILL, FLOOR_DIV, FULLY_CONNECTED, GATHER, LESS, LOG, LOGICAL_AND, MAXIMUM, MAX_POOL_2D, MINIMUM, MUL, PACK, RANGE, REDUCE_MAX, REDUCE_MIN, RESHAPE, REVERSE_V2, SHAPE, SPARSE_TO_DENSE, SPLIT_V, STRIDED_SLICE, SUB, SUM, TANH, TILE, TRANSPOSE, ZEROS_LIKE. Here is a list of operators for which you will need custom implementations: CTC_BEAM_SEARCH_DECODER, ComplexAbs, Enter, Exit, LoopCond, Merge, RFFT, Switch, TensorArrayGatherV3, TensorArrayReadV3, TensorArrayScatterV3, TensorArraySizeV3, TensorArrayV3, TensorArrayWriteV3.
Traceback (most recent call last):
  File "/usr/local/bin/toco_from_protos", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 59, in main
    app.run(main=execute, argv=[sys.argv[0]] + unparsed)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 33, in execute
    output_str = tensorflow_wrap_toco.TocoConvert(model_str, toco_str, input_str)
Exception: We are continually in the process of adding support to TensorFlow Lite for more ops. It would be helpful if you could inform us of how this conversion went by opening a github issue at https://github.com/tensorflow/tensorflow/issues/new?template=40-tflite-op-request.md
 and pasting the following:

Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, CAST, CONCATENATION, CONV_2D, DIV, EQUAL, EXPAND_DIMS, FILL, FLOOR_DIV, FULLY_CONNECTED, GATHER, LESS, LOG, LOGICAL_AND, MAXIMUM, MAX_POOL_2D, MINIMUM, MUL, PACK, RANGE, REDUCE_MAX, REDUCE_MIN, RESHAPE, REVERSE_V2, SHAPE, SPARSE_TO_DENSE, SPLIT_V, STRIDED_SLICE, SUB, SUM, TANH, TILE, TRANSPOSE, ZEROS_LIKE. Here is a list of operators for which you will need custom implementations: CTC_BEAM_SEARCH_DECODER, ComplexAbs, Enter, Exit, LoopCond, Merge, RFFT, Switch, TensorArrayGatherV3, TensorArrayReadV3, TensorArrayScatterV3, TensorArraySizeV3, TensorArrayV3, TensorArrayWriteV3.

here is the link to the shared notebook : https://colab.research.google.com/drive/1FhMBJHynRVfd_o-q2JH6Wn867YmnomjY

the frozen model .pb is available there : https://we.tl/t-1mwjdnJfxe

Thank you for helping, you're doing a great job

Raphael

**Comment by wangtz** [comment]
It looks like you need to freeze the model first.

**Comment by kezakool** [comment]
Thanks for helping, did you looked at the shared notebook, the model is already frozen to a *.pb file, did i missed something?

**Comment by haozha111** [comment]
Sachin, do you mind taking a look on this (since this is related with exporting ssd graph)? Thanks!

**Comment by srjoglekar246** [comment]
@kezakool Looks like you have a bunch of ops that are not supported :-). The vanilla response would be for you to implement custom ops for all these. However, we are adding better support for Control Flow (Merge, Switch, etc) & TensorList ops by next year, with an improved converter & builtin TFLite ops. However, these structures are *usually* required when you have ambiguous shapes in the graph. If you are training/exporting this model to a `.pb`, you could try 'freezing' some of these shapes?
Also, if binary size isn't a factor for you, you could also try using the [Select TF Ops in TFLite](https://www.tensorflow.org/lite/guide/ops_select) option.

I know this isn't the ideal answer, but its usually better to work with a simpler model than try to convert a complex model, albeit at a loss of accuracy :-)

**Comment by kezakool** [comment]
@srjoglekar246, thanks for helping me! :)

 What do you mean with "you could try 'freezing' some of these shapes?" can you describe a bit please?, i'm not sure to get it

Also, with your suggestion, I tried to convert using  target_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
and i still get this error : 
Here is a list of operators for which you will need custom implementations: CTC_BEAM_SEARCH_DECODER, Merge, Switch.

and if i set allow_custom_ops = True, i get this error :  
Exception: TensorFlow Lite currently doesn't support control flow ops: Merge, Switch.

this come from the LSTM layer of my graph, do you now an implementation that doesn't have switch and merge ops?

Many thanks

**Comment by kezakool** [comment]
Thanks for investing this Sachin, is ControlFlow v2 compatible with Tensorflow 1.14?

Before seeing your answer, I dug into into the differents LSTM components availables, and using BasicLSTMCell with Static_rnn seems to be a solution (still have to tune it) and doesn't use Merge/Switch.
With that, the only piece missing is the CTC_BEAM_SEARCH_DECODER op, i saw this issue :
https://github.com/tensorflow/tensorflow/issues/28045
So it seems its a fixed bug, but i still got the issue...

here is the updated graph in case you need it : https://we.tl/t-dKBgCsXhHt

Thank you for your time

Raphael
