### ISSUE TITLE
tf.keras: Error in BinaryCrossentropy loss when output shape is determined by inputs

### ISSUE THREAD

**Issue by deasmhumhna** [tensorflow/tensorflow#31749]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ArchLinux 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): Source
- TensorFlow version (use command below): v2.0.0-beta1-4983-g65e6355ad9 2.0.0-rc0
- Python version:
- Bazel version (if compiling from source): bazel 26.1
- GCC/Compiler version (if compiling from source): 
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Shape mismatch for binary cross-entropy with logits for compiled Keras  when output shape is determined by model inputs (no error when using eager-evaluation):
```
ValueError: logits and labels must have the same shape ((None,) vs (None, 1))
```
**Describe the expected behavior**
No shape mismatch

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
```
import tensorflow as tf
import numpy as np

inputs = tf.keras.Input(shape=(1,), dtype=tf.int64)
outputs = tf.random.normal(shape=(inputs[0, 0],))

model = tf.keras.Model(inputs, outputs)
model.compile(optimizer='sgd', loss=tf.keras.losses.BinaryCrossentropy(from_logits=True))

dummy = np.zeros((10, 1))
shapes = np.random.randint(0, 11, 10).reshape(10, 1, 1)
dataset = tf.data.Dataset.from_tensor_slices(shapes)
dataset = dataset.map(lambda x: (x, tf.random.uniform(minval=0, maxval=2, shape=(x[0,0],), dtype=tf.int32)))

# eagar mode, works
loss = tf.keras.losses.BinaryCrossentropy(from_logits=True)
for inputs, true in dataset:
    pred = model(inputs)
    print(true)
    print(pred)
    print(loss(true, pred))
    break

# compiled model, fails
model.fit(dataset, epochs = 1, steps_per_epoch=1)
```
**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/tensorflow_core/python/framework/tensor_shape.py", line 928, in merge_with
    self.assert_same_rank(other)
  File "/usr/lib/python3.7/site-packages/tensorflow_core/python/framework/tensor_shape.py", line 983, in assert_same_rank
    (self, other))
ValueError: Shapes (None, 1) and (None,) must have the same rank

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/tensorflow_core/python/ops/nn_impl.py", line 168, in sigmoid_cross_entropy_with_logits
    labels.get_shape().merge_with(logits.get_shape())
  File "/usr/lib/python3.7/site-packages/tensorflow_core/python/framework/tensor_shape.py", line 934, in merge_with
    raise ValueError("Shapes %s and %s are not compatible" % (self, other))
ValueError: Shapes (None, 1) and (None,) are not compatible

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 25, in <module>
    model.fit(dataset, epochs = 1, steps_per_epoch=1)
  File "/usr/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 736, in fit
    use_multiprocessing=use_multiprocessing)
  File "/usr/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 307, in fit
    total_epochs=epochs)
  File "/usr/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 121, in run_one_epoch
    batch_outs = execution_function(iterator)
  File "/usr/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 84, in execution_function
    for out in distributed_function(input_fn)]
  File "/usr/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 427, in __call__
    self._initialize(args, kwds, add_initializers_to=initializer_map)
  File "/usr/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 370, in _initialize
    *args, **kwds))
  File "/usr/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 1834, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/usr/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 2134, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/usr/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 2025, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/usr/lib/python3.7/site-packages/tensorflow_core/python/framework/func_graph.py", line 884, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/usr/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 320, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/usr/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 71, in distributed_function
    per_replica_function, args=(model, x, y, sample_weights))
  File "/usr/lib/python3.7/site-packages/tensorflow_core/python/distribute/distribute_lib.py", line 760, in experimental_run_v2
    return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
  File "/usr/lib/python3.7/site-packages/tensorflow_core/python/distribute/distribute_lib.py", line 1787, in call_for_each_replica
    return self._call_for_each_replica(fn, args, kwargs)
  File "/usr/lib/python3.7/site-packages/tensorflow_core/python/distribute/distribute_lib.py", line 2132, in _call_for_each_replica
    return fn(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/api.py", line 292, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 299, in train_on_batch
    output_loss_metrics=model._output_loss_metrics)
  File "/usr/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_eager.py", line 307, in train_on_batch
    output_loss_metrics=output_loss_metrics))
  File "/usr/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_eager.py", line 252, in _process_single_batch
    training=training))
  File "/usr/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_eager.py", line 166, in _model_loss
    per_sample_losses = loss_fn.call(targets[i], outs[i])
  File "/usr/lib/python3.7/site-packages/tensorflow_core/python/keras/losses.py", line 216, in call
    return self.fn(y_true, y_pred, **self._fn_kwargs)
  File "/usr/lib/python3.7/site-packages/tensorflow_core/python/keras/losses.py", line 989, in binary_crossentropy
    K.binary_crossentropy(y_true, y_pred, from_logits=from_logits), axis=-1)
  File "/usr/lib/python3.7/site-packages/tensorflow_core/python/keras/backend.py", line 4449, in binary_crossentropy
    return nn.sigmoid_cross_entropy_with_logits(labels=target, logits=output)
  File "/usr/lib/python3.7/site-packages/tensorflow_core/python/ops/nn_impl.py", line 171, in sigmoid_cross_entropy_with_logits
    (logits.get_shape(), labels.get_shape()))
ValueError: logits and labels must have the same shape ((None,) vs (None, 1))
```

**Comment by srihari-humbarwadi** [comment]
@deasmhumhna
The code seems to work fine in 2.0.0-beta1
<img width="1217" alt="Screenshot 2019-08-19 at 10 56 45 AM" src="https://user-images.githubusercontent.com/24864163/63241259-b462a480-c270-11e9-980a-611763da674c.png">

**Comment by deasmhumhna** [comment]
I'm technically using Tensorflow 2.0.0-rc0, built from source.

Here's another, somewhat cleaner version using `dataset_from_generator`:
```
import numpy as np

print('Tensorflow', tf.__version__)

inputs = tf.keras.Input(shape=(1,), dtype=tf.int32)
outputs = tf.random.normal(
    shape=(tf.reduce_max(inputs) - tf.reduce_min(inputs) + 1,))

model = tf.keras.Model(inputs, outputs)
model.compile(optimizer='sgd',
              loss=tf.keras.losses.BinaryCrossentropy(from_logits=True))

x = np.random.randint(1, 10, 100).reshape(10, 10)
ysize = x.min(axis=-1)

def gen():
    while True:
        x = np.random.normal(5, 10, size=(5, 1)).astype('i4')
        y = np.random.randint(0, 2, size=int(np.ptp(x) + 1)).astype('i4')
        yield (x, y)

dataset = tf.data.Dataset.from_generator(
    gen, output_types=(tf.int32, tf.int32),
    output_shapes=(tf.TensorShape([5, 1]), tf.TensorShape([None])))

# eagar mode, works
loss = tf.keras.losses.BinaryCrossentropy(from_logits=True)
for inputs, true in dataset:
    pred = model(inputs)
    print(true.shape)
    print(pred.shape)
    print(loss(true, pred))
    break

# compiled model, fails
model.fit(dataset, epochs = 1, steps_per_epoch=1)
```

**Comment by deasmhumhna** [comment]
I'm re-building tensorflow right now. I'll see if that helps.

**Comment by oanush** [comment]
@deasmhumhna ,
When tried executing the code in TF-2.0.0beta1 and 1.14 worked fine. Any update on the issue after you re-building the TF?Thanks!

**Comment by deasmhumhna** [comment]
I haven't finished re-building yet, but I keep getting strange errors with `@tf.function` that aren't even consistent across models/files (simple models pass, but complex models break the same training loops, simple and complex nested models give different errors, etc). I suspect something might be wrong with the Autograph files in my build. In the meantime, I might just reinstall the `pip` build of Tensorflow 2.0.

**Comment by oanush** [comment]
@deasmhumhna ,
Any update after tried rebuilding TF?Thanks!

**Comment by oanush** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
