### ISSUE TITLE
dataset as input to estimator is broken.

### ISSUE THREAD

**Issue by aashudwivedi** [tensorflow/tensorflow#31758]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Does not depend on OS.
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v1.14.0-0-g87989f6959, 1.14.0
- Python version: 3.6.8
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: NA
- GPU model and memory: NA

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

Dataset input to estimator is broken

**Describe the expected behavior**

Passing the a dataset object to `estimator.fit` method results in the following  error: 

```
ValueError                                Traceback (most recent call last)

<ipython-input-6-1ed4dbb580ca> in <module>()
     14 est.fit(
     15     steps=1000,
---> 16     input_fn=lambda : csv_input_fn(train_path, batch_size))

2 frames

/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py in _train_model(self, input_fn, hooks)
   1036       random_seed.set_random_seed(self._config.tf_random_seed)
   1037       global_step = training_util.create_global_step(g)
-> 1038       features, labels = input_fn()
   1039       self._check_inputs(features, labels)
   1040       training_util._get_or_create_global_step_read()  # pylint: disable=protected-access

ValueError: too many values to unpack (expected 2)
```

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

Following example from the docs can be used to reproduce the problem. Check  the definition of the main function.
```
import pandas as pd
import tensorflow as tf

TRAIN_URL = "http://download.tensorflow.org/data/iris_training.csv"
TEST_URL = "http://download.tensorflow.org/data/iris_test.csv"

CSV_COLUMN_NAMES = ['SepalLength', 'SepalWidth',
                    'PetalLength', 'PetalWidth', 'Species']
SPECIES = ['Setosa', 'Versicolor', 'Virginica']

def maybe_download():
    train_path = tf.keras.utils.get_file(TRAIN_URL.split('/')[-1], TRAIN_URL)
    test_path = tf.keras.utils.get_file(TEST_URL.split('/')[-1], TEST_URL)

    return train_path, test_path

def load_data(y_name='Species'):
    """Returns the iris dataset as (train_x, train_y), (test_x, test_y)."""
    train_path, test_path = maybe_download()

    train = pd.read_csv(train_path, names=CSV_COLUMN_NAMES, header=0)
    train_x, train_y = train, train.pop(y_name)

    test = pd.read_csv(test_path, names=CSV_COLUMN_NAMES, header=0)
    test_x, test_y = test, test.pop(y_name)

    return (train_x, train_y), (test_x, test_y)


def train_input_fn(features, labels, batch_size):
    """An input function for training"""
    # Convert the inputs to a Dataset.
    dataset = tf.data.Dataset.from_tensor_slices((dict(features), labels))

    # Shuffle, repeat, and batch the examples.
    dataset = dataset.shuffle(1000).repeat().batch(batch_size)

    # Return the dataset.
    return dataset


def eval_input_fn(features, labels, batch_size):
    """An input function for evaluation or prediction"""
    features=dict(features)
    if labels is None:
        # No labels, use only features.
        inputs = features
    else:
        inputs = (features, labels)

    # Convert the inputs to a Dataset.
    dataset = tf.data.Dataset.from_tensor_slices(inputs)

    # Batch the examples
    assert batch_size is not None, "batch_size must not be None"
    dataset = dataset.batch(batch_size)

    # Return the dataset.
    return dataset


# The remainder of this file contains a simple example of a csv parser,
#     implemented using the `Dataset` class.

# `tf.parse_csv` sets the types of the outputs to match the examples given in
#     the `record_defaults` argument.
CSV_TYPES = [[0.0], [0.0], [0.0], [0.0], [0]]

def _parse_line(line):
    # Decode the line into its fields
    fields = tf.decode_csv(line, record_defaults=CSV_TYPES)

    # Pack the result into a dictionary
    features = dict(zip(CSV_COLUMN_NAMES, fields))

    # Separate the label from the features
    label = features.pop('Species')

    return features, label


def csv_input_fn(csv_path, batch_size):
    # Create a dataset containing the text lines.
    dataset = tf.data.TextLineDataset(csv_path).skip(1)

    # Parse each line.
    dataset = dataset.map(_parse_line)

    # Shuffle, repeat, and batch the examples.
    dataset = dataset.shuffle(1000).repeat().batch(batch_size)

    # Return the dataset.
    return dataset
  
  
def main():
  train_path, test_path = maybe_download()
  batch_size = 100
  CSV_COLUMN_NAMES = ['SepalLength', 'SepalWidth',
                      'PetalLength', 'PetalWidth', 'Species']

  est = tf.contrib.learn.LinearClassifier(
      CSV_COLUMN_NAMES,
      n_classes=3
  )

  est.fit(
      steps=1000,
      input_fn=lambda : csv_input_fn(train_path, batch_size))
  
main()
```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by oanush** [comment]
I was able to replicate the issue for TF-1.14 version, kindly find the [Gist](https://colab.research.google.com/drive/1i0lArKoDJRKJsUGqPj73diEnostxEJ6W) of colab.Thanks!

**Comment by aashudwivedi** [comment]
Meanwhile how do you suggest to input large datasets to the estimator API, I've tried using the `tf.Iterator` like this:  `tf.compat.v1.data.make_one_shot_iterator(dataset).get_next()` but that runs into another error : 
```
Traceback (most recent call last):
  File "tf_test.py", line 48, in <module>
    est.fit(steps=1, input_fn=input_fn)
  File "/Users/ashutdwi/.virtualenvs/benchmarks/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/Users/ashutdwi/.virtualenvs/benchmarks/lib/python3.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 524, in fit
    loss = self._train_model(input_fn=input_fn, hooks=hooks)
  File "/Users/ashutdwi/.virtualenvs/benchmarks/lib/python3.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 1041, in _train_model
    model_fn_ops = self._get_train_ops(features, labels)
  File "/Users/ashutdwi/.virtualenvs/benchmarks/lib/python3.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 1264, in _get_train_ops
    return self._call_model_fn(features, labels, model_fn_lib.ModeKeys.TRAIN)
  File "/Users/ashutdwi/.virtualenvs/benchmarks/lib/python3.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 1227, in _call_model_fn
    model_fn_results = self._model_fn(features, labels, **kwargs)
  File "/Users/ashutdwi/.virtualenvs/benchmarks/lib/python3.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/linear.py", line 251, in sdca_model_fn
    features.update(layers.transform_features(features, feature_columns))
  File "/Users/ashutdwi/.virtualenvs/benchmarks/lib/python3.7/site-packages/tensorflow/contrib/layers/python/layers/feature_column_ops.py", line 653, in transform_features
    check_feature_columns(feature_columns)
  File "/Users/ashutdwi/.virtualenvs/benchmarks/lib/python3.7/site-packages/tensorflow/contrib/layers/python/layers/feature_column_ops.py", line 777, in check_feature_columns
    key = f.key
AttributeError: 'str' object has no attribute 'key'
```

Here's a self contained program to demonstrate the error : 

```
import copy
import tempfile
import tensorflow as tf
tf.enable_eager_execution()

_, filename = tempfile.mkstemp()

cols = ["example_id", "sepal_len", "sepal_width", "petal_len", "petal_width", "label"]

data = "\n".join([
    #",".join(cols),
    "1,5.1,3.5,1.4,0.2,Iris-setosa",
    "2,4.9,3.0,1.4,0.2,Iris-setosa",
    "2,4.7,3.2,1.3,0.2,Iris-setosa",
    "4,4.6,3.1,1.5,0.2,Iris-setosa",
    "5,5.0,3.6,1.4,0.2,Iris-setosa",
    "6,5.7,2.5,5.0,2.0,Iris-virginica",
    "7,7.0,3.2,4.7,1.4,Iris-versicolor",
    "8,6.5,3.2,5.1,2.0,Iris-virginica",
    "9,6.4,2.7,5.3,1.9,Iris-virginica",
    "10,6.8,3.0,5.5,2.1,Iris-virginica",
    "11,5.4,3.9,1.7,0.4,Iris-setosa"
])

with open(filename, 'w') as f:
    f.write(data)

batch_size = 2

FIELD_DEFAULTS = [[0], [0.0], [0.0], [0.0], [0.0], [0]]

def _parse(line):
    fields = tf.io.decode_csv(line, FIELD_DEFAULTS)
    features = dict(zip(cols, fields))
    label = features.pop('label')
    return features, label

def input_fn():
    dataset = tf.data.TextLineDataset(filename).skip(1)
    dataset = dataset.map(_parse)
    # return dataset
    return tf.compat.v1.data.make_one_shot_iterator(dataset).get_next()


feature_cols = copy.copy(cols)
feature_cols.remove('example_id')
est = tf.contrib.learn.SVM(example_id_column='example_ids', feature_columns=feature_cols)
est.fit(steps=1, input_fn=input_fn)
out = est.predict(input_fn=test_input_fn, yield_single_examples=False)
assert(len(out['classes']) == len(data))
```

**Comment by jvishnuvardhan** [comment]
@aashudwivedi Sorry for the late response. Is this still an issue for you. Can you please go through the [tutorial](https://www.tensorflow.org/tutorials/estimator/linear) on TF website. Thanks!

**Comment by aashudwivedi** [comment]
No it's not I implemented my own SVM using tf instead.

**Comment by mihaimaruseac** [comment]
Closing as it is no longer an issue
