### ISSUE TITLE
ImportError: DLL load failed with error code -1073741795

### ISSUE THREAD

**Issue by grotos** [tensorflow/tensorflow#31763]
I follow installation instructions from tensorflow.org. I use CPU version.

I have seen many similar problems, but all of them were due to unsupported AVX. 
My CPU supports it, but tensorflow still doesn't work.

**System information**
- OS Platform and Distribution: Wisnows 7 64
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 1.14
- Python version: 3.7.3
- Installed using virtualenv? pip? conda?: pip in virtualenv
- CUDA/cuDNN version: CPU version
- GPU model and memory: CPU version

**Describe the problem**
After installation I try to run:

`python -c "import tensorflow as tf;print(tf.reduce_sum(tf.random.normal([1000, 1000])))"`

and I get error:
```
Traceback (most recent call last):
  File "C:\Users\S1614414\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\S1614414\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\S1614414\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\S1614414\venv\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\S1614414\venv\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed with error code -1073741795

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\S1614414\venv\lib\site-packages\tensorflow\__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\S1614414\venv\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\S1614414\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\S1614414\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\S1614414\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\S1614414\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\S1614414\venv\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\S1614414\venv\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed with error code -1073741795


Failed to load the native TensorFlow runtime.
```
What could be the issue?

Edit: I have found reason - I had AVX disabled on my system.
This issue can be closed.

**Comment by grotos** [comment]
I have found reason - I had AVX disabled on my system.
This issue can be closed.

**Comment by ravikyram** [comment]
Just to verify did you get chance to follow instructions from TensorFlow [website ](https://www.tensorflow.org/install/pip).Please, let us know. 
Also, please, go through below link and see if it helps you.Thanks!
https://github.com/tensorflow/tensorflow/issues/24882
