### ISSUE TITLE
In reference with issue https://github.com/tensorflow/tensorflow/issues/31533

### ISSUE THREAD

**Issue by VirRajpurohit** [tensorflow/tensorflow#31788]
For training model we are using
ssd_mobilenet_v2_coco

I have converted my model using following code: 

import tensorflow as tf
graph_def_file = "C:/tensorflow1/models/research/object_detection/inference_graph/tflite_graph.pb"
input_arrays = ["normalized_input_image_tensor"]
input_shaps = {"normalized_input_image_tensor":[1, 300, 300, 3]}
output_arrays = ["raw_outputs/box_encodings"]
converter = tf.lite.TFLiteConverter.from_frozen_graph(graph_def_file, input_arrays, output_arrays, input_shaps)
tflite_model = converter.convert()
open("detact.tflite", "wb").write(tflite_model)

**Comment by jdduke** [comment]
In TFLiteObjectDetectionAPIModel.java, the number of detections is hardcoded to 10. It looks like this is different in your model, so you need to change the `NUM_DETECTIONS` value.

**Comment by VirRajpurohit** [comment]
Changing NUM_DETECTIONS to 1917
throws error

 ```
java.lang.IllegalArgumentException: Invalid output Tensor index: 1
        at org.tensorflow.lite.NativeInterpreterWrapper.getOutputTensor(NativeInterpreterWrapper.java:305)
        at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:161)
        at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:275)
        at org.tensorflow.lite.examples.detection.tflite.TFLiteObjectDetectionAPIModel.recognizeImage(TFLiteObjectDetectionAPIModel.java:252)
        at org.tensorflow.lite.examples.detection.DetectorActivity$2.run(DetectorActivity.java:181)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:65)
```

**Comment by jdduke** [comment]
Unless you attach your converted model there's not much we can do to help without knowing more about its topology, inputs and outputs.

**Comment by VirRajpurohit** [comment]
Hello @jdduke 
I am defining the link below.
It has converted tflite file, label file and original .pb file from which model converted.

[THIS IS THE LINK](https://drive.google.com/open?id=174Bibbh3MiSzBdBRuSubQ_wp5cSDytDw
)
Please assist.

**Comment by VirRajpurohit** [comment]
@jdduke 
 Changing the output tensor did the trick.
 Can you please refer any doc which stats the usage of the each variable in detail.

As my question was revolving around the NUM_DETECTIONS? What exactly it means?

**Comment by jdduke** [comment]
I encourage you to use tools like our [.tflite visualizer](https://www.tensorflow.org/lite/guide/faq#how_do_i_inspect_a_tflite_file) to better understand your graph inputs/outputs, or the excellent [Netron](https://electronjs.org/apps/netron) model visualizer (that handles .tflite models as well as other model formats). NUM_DETECTIONS refers to the number of detected objects. In the model used by the sample, it's hardcoded to 10, but it can vary depending on the model.

**Comment by enorkus** [comment]
> @jdduke
> Changing the output tensor did the trick.
> Can you please refer any doc which stats the usage of the each variable in detail.
> 
> As my question was revolving around the NUM_DETECTIONS? What exactly it means?

I'm having the same problem (java.lang.IllegalArgumentException: Invalid output Tensor index: 1) after changing NUM_DETECTIONS and a few more things in the sample Android app.
What exactly did you change to solve it?

**Comment by VirRajpurohit** [comment]
@enorkus 
Actually as @jdduke suggested. Our model and the default code needs to be compatible with eachother. For that the input shape array needs to be matched. My input array from model was [1,1917,4] and the somehow code requires [1,10,4] where 10 is number of detection.   So I was supposed to change in model. Doing that helped me running this sample code.

**Comment by wnoussair** [comment]
> @enorkus
> Actually as @jdduke suggested. Our model and the default code needs to be compatible with eachother. For that the input shape array needs to be matched. My input array from model was [1,1917,4] and the somehow code requires [1,10,4] where 10 is number of detection. So I was supposed to change in model. Doing that helped me running this sample code.

How did you fix it please
