### ISSUE TITLE
tf.initialize_variables fails on missing Tensor initializer attribute

### ISSUE THREAD

**Issue by sjperkins** [tensorflow/tensorflow#3181]
### Environment info
Operating System: `Ubuntu 14.04.4`

Installed version of CUDA and cuDNN:  CUDA 7.5 and cuDNN 4.0.7
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

```bash
ls -l /usr/local/cuda-7.5/lib64/libcud*
-rw-r--r-- 1 root root    322936 Aug 15  2015 /usr/local/cuda-7.5/lib64/libcudadevrt.a
lrwxrwxrwx 1 root root        16 Aug 15  2015 /usr/local/cuda-7.5/lib64/libcudart.so -> libcudart.so.7.5
lrwxrwxrwx 1 root root        19 Aug 15  2015 /usr/local/cuda-7.5/lib64/libcudart.so.7.5 -> libcudart.so.7.5.18
-rwxr-xr-x 1 root root    383336 Aug 15  2015 /usr/local/cuda-7.5/lib64/libcudart.so.7.5.18
-rw-r--r-- 1 root root    720192 Aug 15  2015 /usr/local/cuda-7.5/lib64/libcudart_static.a
lrwxrwxrwx 1 3319 users       13 Feb  9 19:48 /usr/local/cuda-7.5/lib64/libcudnn.so -> libcudnn.so.4
lrwxrwxrwx 1 3319 users       17 Feb  9 19:48 /usr/local/cuda-7.5/lib64/libcudnn.so.4 -> libcudnn.so.4.0.7
-rwxrwxr-x 1 3319 users 61453024 Feb  9 00:12 /usr/local/cuda-7.5/lib64/libcudnn.so.4.0.7
-rw-rw-r-- 1 3319 users 62025862 Feb  9 00:12 /usr/local/cuda-7.5/lib64/libcudnn_static.a
```

If installed from binary pip package, provide:

1. Which pip package you installed. Nightly build, Ubuntu/Linux 64-bit, GPU enabled, Python 2.7 
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

```bash
$ python -c "import tensorflow; print(tensorflow.__version__)"
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
0.9.0
```

If installed from sources, provide the commit hash:

### Steps to reproduce
1. Running the following python script
```python
import tensorflow as tf

with tf.Session() as S:
    V = tf.linspace(0., 100., 10)
    S.run(tf.initialize_variables([V]))
```

produces the following output:

```python
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:924] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 0 with properties: 
name: GeForce GTX 850M
major: 5 minor: 0 memoryClockRate (GHz) 0.9015
pciBusID 0000:01:00.0
Total memory: 4.00GiB
Free memory: 3.56GiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:126] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:806] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 850M, pci bus id: 0000:01:00.0)
Traceback (most recent call last):
  File "test_init_fail.py", line 5, in <module>
    S.run(tf.initialize_variables([V]))
  File "/home/foobar/venv/mb/local/lib/python2.7/site-packages/tensorflow/python/ops/variables.py", line 907, in initialize_variables
    *[v.initializer for v in var_list], name=name)
AttributeError: 'Tensor' object has no attribute 'initializer'

```

### What have you tried?
1. See above

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

**Comment by sjperkins** [comment]
`tf.linspace` needed to be wrapped in a `tf.Variable` like so:

```python
import tensorflow as tf

with tf.Session() as S:
    V = tf.Variable(tf.linspace(0., 100., 10))
    S.run(tf.initialize_variables([V]))
```
