### ISSUE TITLE
When subclassing, keras converts SparseTensors to Tensors

### ISSUE THREAD

**Issue by pavanky** [tensorflow/tensorflow#31851]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

System information

Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
Yes

OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Ubuntu 18.04

Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
No

TensorFlow installed from (source or binary):
Binary

TensorFlow version (use command below):
1.14.0

**Describe the current behavior**

keras.Model.fit converts SparseTensors to tensors. 

**Describe the expected behavior**

keras.Model.fit passes SparseTensors as is.

**Code to reproduce the issue**

```
import numpy as np
import tensorflow.compat.v2 as tf

def dummy_parse_fn(iterable):
  features = {}
  # the input is always constant
  features['sparse_tensor'] = tf.SparseTensor(
    indices=tf.constant([[0,0],[1,1]], dtype=tf.int64),
    values=tf.constant([1.0, 1.0], dtype=tf.float32),
    dense_shape=tf.constant([2, 2], dtype=tf.int64))
  labels = tf.constant([1.0, 1.0], dtype=tf.float32)
  return features, labels


def get_dummy_dataset():
  iterable =  np.random.random((128, 1)).astype(np.float32)
  return (
    tf.data.Dataset
    .from_tensor_slices(iterable)
    .map(dummy_parse_fn)
    .take(1024)
  )


class SparseModel(tf.keras.Model):
  def call(self, features):
    sparse_tensor = features['sparse_tensor']
    assert isinstance(sparse_tensor, tf.sparse.SparseTensor), type(sparse_tensor)
    return sparse_tensor.values


if __name__ == "__main__":

  print(tf.__version__)

  model = SparseModel()
  optimizer = tf.keras.optimizers.SGD(learning_rate=0.1, momentum=0.9, nesterov=True)
  loss = tf.keras.losses.BinaryCrossentropy(from_logits=True)

  model.compile(optimizer=optimizer, loss=loss, metrics=['accuracy'])
  model.fit(get_dummy_dataset(), epochs=2)
```

**Comment by pavanky** [comment]
Closing this because `tf-nightly` is failing with a more explicit error:

```
1.15.0-dev20190821
W0821 10:51:25.285699 139658675762816 training_utils.py:1545] Expected a shuffled dataset but input dataset `x` is not shuffled. Please invoke `shuffle()` on input dataset.
2019-08-21 10:51:25.289208: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-08-21 10:51:25.307253: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2112500000 Hz
2019-08-21 10:51:25.308770: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55c6cbd07e50 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2019-08-21 10:51:25.308820: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Traceback (most recent call last):
  File "/tmp/sparse_model_v2.py", line 41, in <module>
    model.fit(get_dummy_dataset(), epochs=2)
  File "/home/pyalamanchili/.local/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 727, in fit
    use_multiprocessing=use_multiprocessing)
  File "/home/pyalamanchili/.local/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_arrays.py", line 643, in fit
    shuffle=shuffle)
  File "/home/pyalamanchili/.local/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 2418, in _standardize_user_data
    all_inputs, y_input, dict_inputs = self._build_model_with_inputs(x, y)
  File "/home/pyalamanchili/.local/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 2607, in _build_model_with_inputs
    (input_tensor,))
ValueError: All SparseTensor and RaggedTensor inputs must be explicitly declared using a keras.Input() with sparse=True or ragged=True. We found an undeclared input SparseTensor(indices=Tensor("DeserializeSparse:0", shape=(?, 2), dtype=int64), values=Tensor("DeserializeSparse:1", shape=(?,), dtype=float32), dense_shape=Tensor("DeserializeSparse:2", shape=(2,), dtype=int64)). For Sequential models, please add a keras.Input() as your first Layer. For subclassed models, please call self._set_inputs() on your input set, which you can create using keras.Input() for each input to your model.```

However the suggested alternative doesnt work either as seen here: https://github.com/tensorflow/tensorflow/issues/31819

**Comment by pavanky** [comment]
For posterity here is a link to a working sample in tf-nightly if someone else is looking: 
https://gist.github.com/pavanky/3e1635edb322c81436d66ac9d9bdf69f
