### ISSUE TITLE
Converting .pb to tflite GetOpWithOutput-Error

### ISSUE THREAD

**Issue by CDNova** [tensorflow/tensorflow#31880]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Linux Ubuntu
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
Binary
- TensorFlow version (use command below):
tf-nightly 1.15.0.dev20190819
- Python version:
2.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

I trained a object-detection model with my own dataset and I'm trying to convert the output to a tflite file for my mobile application

My code to convert the checkpoint to .pb:
python export_tflite_ssd_graph.py 
--pipeline_config_path /tensorflow/models/research/object_detection/training/ssd_mobilenet_v1.config 
--trained_checkpoint_prefix /tensorflow/models/research/object_detection/dataset/model.ckpt-50000 
--output_directory /tensorflow/models/research/object_detection/dataset/tflite --add_postprocessing_op=true

My code to convert .pb to tflite 

!tflite_convert --output_file /tensorflow/models/research/object_detection/dataset/tflite/tflite_graph.tflite \
                --graph_def_file /tensorflow/models/research/object_detection/dataset/tflite/tflite_graph.pb \
                --output_format TFLITE \
                --inference_type FLOAT \
                --input_arrays image_tensor \
                --input_shapes 1,300,300,3 \
                --output_arrays raw_detection_scores \
                --mean_values=128 \
                --std_dev_values=128 \
                --change_concat_input_ranges=false \
                --allow_nudging_weights_to_use_fast_gemm_kernel=true \
                --allow_custom_ops

The error from console:
2019-08-22 08:59:26.271136: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2019-08-22 08:59:26.275691: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2900000000 Hz
2019-08-22 08:59:26.277466: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x56240f206dc0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2019-08-22 08:59:26.277520: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Traceback (most recent call last):
  File "/usr/local/bin/tflite_convert", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/lite/python/tflite_convert.py", line 515, in main
    app.run(main=run_main, argv=sys.argv[:1])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/lite/python/tflite_convert.py", line 511, in run_main
    _convert_tf1_model(tflite_flags)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/lite/python/tflite_convert.py", line 199, in _convert_tf1_model
    output_data = converter.convert()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/lite/python/lite.py", line 989, in convert
    **converter_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/lite/python/convert.py", line 412, in toco_convert_graph_def
    enable_mlir_converter=enable_mlir_converter)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/lite/python/convert.py", line 200, in toco_convert_protos
    raise ConverterError("See console for info.\n%s\n%s\n" % (stdout, stderr))
tensorflow.lite.python.convert.ConverterError: See console for info.
WARNING: Logging before flag parsing goes to stderr.
W0822 08:59:27.571232 139982160922432 __init__.py:689] 

  TensorFlow's `tf-nightly` package will soon be updated to TensorFlow 2.0.

  Please upgrade your code to TensorFlow 2.0:
    * https://www.tensorflow.org/beta/guide/migration_guide

  Or install the latest stable TensorFlow 1.X release:
    * `pip install -U "tensorflow==1.*"`

  Otherwise your code may be broken by the change.

  
2019-08-22 08:59:27.633571: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TFLite_Detection_PostProcess
2019-08-22 08:59:27.640703: F tensorflow/lite/toco/tooling_util.cc:935] Check failed: GetOpWithOutput(model, output_array) Specified output array "raw_detection_scores" is not produced by any op in this graph. Is it a typo? This should not happen. If you trigger this error please send a bug report (with code to reporduce this error), to the TensorFlow Lite team.
Aborted (core dumped)

**Describe the expected behavior**

**Code to reproduce the issue**
[tflite_graph.zip](https://github.com/tensorflow/tensorflow/files/3528754/tflite_graph.zip)

Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ucasiggcas** [comment]
Dear,
how to set the four parameters
--mean_values
--std_dev_values
--default_ranges_min
--default_ranges_max

thx
https://github.com/tensorflow/tensorflow/issues/32611
