### ISSUE TITLE
//tensorflow/contrib/distributions/python/kernel_tests/independent_test.py fails  with assertion error

### ISSUE THREAD

**Issue by anujajakhade** [tensorflow/tensorflow#31887]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04 s390x
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): Source
- TensorFlow version (use command below): 1.14.0
- Python version: 2.7.15
- Bazel version (if compiling from source): 0.24.1
- GCC/Compiler version (if compiling from source): gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
- CUDA/cuDNN version: NA
- GPU model and memory: NA

**Describe the current behavior**
```
python tensorflow/contrib/distributions/python/kernel_tests/independent_test.py
======================================================================
FAIL: testMnistLikeDynamicShape (__main__.ProductDistributionTest)
testMnistLikeDynamicShape (__main__.ProductDistributionTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/test/.local/lib/python2.7/site-packages/absl/third_party/unittest3_backport/case.py", line 37, in testPartExecutor
    yield
  File "/home/test/.local/lib/python2.7/site-packages/absl/third_party/unittest3_backport/case.py", line 162, in run
    testMethod()
  File "tensorflow/contrib/distributions/python/kernel_tests/independent_test.py", line 275, in testMnistLikeDynamicShape
    self._testMnistLike(static_shape=False)
  File "tensorflow/contrib/distributions/python/kernel_tests/independent_test.py", line 269, in _testMnistLike
    rtol=1e-6, atol=0.)
  File "/home/test/.local/lib/python2.7/site-packages/tensorflow/python/framework/test_util.py", line 1073, in decorated
    return f(*args, **kwds)
  File "/home/test/.local/lib/python2.7/site-packages/tensorflow/python/framework/test_util.py", line 2303, in assertAllClose
    self._assertAllCloseRecursive(a, b, rtol=rtol, atol=atol, msg=msg)
  File "/home/test/.local/lib/python2.7/site-packages/tensorflow/python/framework/test_util.py", line 2272, in _assertAllCloseRecursive
    (path_str, path_str, msg)))
  File "/home/test/.local/lib/python2.7/site-packages/tensorflow/python/framework/test_util.py", line 2207, in _assertArrayLikeAllClose
    a, b, rtol=rtol, atol=atol, err_msg="\n".join(msgs), equal_nan=True)
  File "/home/test/.local/lib/python2.7/site-packages/numpy/testing/_private/utils.py", line 1501, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "/home/test/.local/lib/python2.7/site-packages/numpy/testing/_private/utils.py", line 827, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Not equal to tolerance rtol=1e-06, atol=0
Mismatched value: a is different from b.
not close where = (array([1, 2, 2, 2, 3]), array([3, 1, 2, 4, 4]), array([6, 1, 1, 8, 6]))
not close lhs = [-463.41407785 -467.87059292 -444.45405599 -469.33429804 -457.64799854]
not close rhs = [-463.41458 -467.87006 -444.45358 -469.3348  -457.6486 ]
not close dif = [0.00050345 0.00053677 0.00047323 0.00051031 0.00059155]
not close tol = [0.00046341 0.00046787 0.00044445 0.00046933 0.00045765]
dtype = float64, shape = (4, 5, 10)
Mismatch: 2.5%
Max absolute difference: 0.00059155
Max relative difference: 1.29257756e-06
 x: array([[[-465.912459, -448.916315, -457.207675, -486.805523,
         -456.784984, -448.14827 , -453.583166, -486.295655,
         -468.533898, -481.740375],...
 y: array([[[-465.9126 , -448.9159 , -457.20764, -486.8053 , -456.7849 ,
         -448.1483 , -453.5835 , -486.2955 , -468.53412, -481.74048],
        [-472.38965, -483.41187, -464.7721 , -467.14288, -478.4115 ,...

======================================================================
FAIL: testMnistLikeStaticShape (__main__.ProductDistributionTest)
testMnistLikeStaticShape (__main__.ProductDistributionTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/test/.local/lib/python2.7/site-packages/absl/third_party/unittest3_backport/case.py", line 37, in testPartExecutor
    yield
  File "/home/test/.local/lib/python2.7/site-packages/absl/third_party/unittest3_backport/case.py", line 162, in run
    testMethod()
  File "tensorflow/contrib/distributions/python/kernel_tests/independent_test.py", line 272, in testMnistLikeStaticShape
    self._testMnistLike(static_shape=True)
  File "tensorflow/contrib/distributions/python/kernel_tests/independent_test.py", line 269, in _testMnistLike
    rtol=1e-6, atol=0.)
  File "/home/test/.local/lib/python2.7/site-packages/tensorflow/python/framework/test_util.py", line 1073, in decorated
    return f(*args, **kwds)
  File "/home/test/.local/lib/python2.7/site-packages/tensorflow/python/framework/test_util.py", line 2303, in assertAllClose
    self._assertAllCloseRecursive(a, b, rtol=rtol, atol=atol, msg=msg)
  File "/home/test/.local/lib/python2.7/site-packages/tensorflow/python/framework/test_util.py", line 2272, in _assertAllCloseRecursive
    (path_str, path_str, msg)))
  File "/home/test/.local/lib/python2.7/site-packages/tensorflow/python/framework/test_util.py", line 2207, in _assertArrayLikeAllClose
    a, b, rtol=rtol, atol=atol, err_msg="\n".join(msgs), equal_nan=True)
  File "/home/test/.local/lib/python2.7/site-packages/numpy/testing/_private/utils.py", line 1501, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "/home/test/.local/lib/python2.7/site-packages/numpy/testing/_private/utils.py", line 827, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Not equal to tolerance rtol=1e-06, atol=0
Mismatched value: a is different from b.
not close where = (array([1, 2, 2, 2, 3]), array([3, 1, 2, 4, 4]), array([6, 1, 1, 8, 6]))
not close lhs = [-463.41407785 -467.87059292 -444.45405599 -469.33429804 -457.64799854]
not close rhs = [-463.41458 -467.87006 -444.45358 -469.3348  -457.6486 ]
not close dif = [0.00050345 0.00053677 0.00047323 0.00051031 0.00059155]
not close tol = [0.00046341 0.00046787 0.00044445 0.00046933 0.00045765]
dtype = float64, shape = (4, 5, 10)
Mismatch: 2.5%
Max absolute difference: 0.00059155
Max relative difference: 1.29257756e-06
 x: array([[[-465.912459, -448.916315, -457.207675, -486.805523,
         -456.784984, -448.14827 , -453.583166, -486.295655,
         -468.533898, -481.740375],...
 y: array([[[-465.9126 , -448.9159 , -457.20764, -486.8053 , -456.7849 ,
         -448.1483 , -453.5835 , -486.2955 , -468.53412, -481.74048],
        [-472.38965, -483.41187, -464.7721 , -467.14288, -478.4115 ,...

----------------------------------------------------------------------
Ran 10 tests in 1.036s

FAILED (failures=2)

```
**Describe the expected behavior**
```
The test should pass on s390x.
```
**Code to reproduce the issue**
```
python tensorflow/contrib/distributions/python/kernel_tests/independent_test.py
```

**Other info / logs**

The following solution resolves the issue.
``` diff
--- a/tensorflow/contrib/distributions/python/kernel_tests/independent_test.py
+++ b/tensorflow/contrib/distributions/python/kernel_tests/independent_test.py
@@ -20,7 +20,7 @@ from __future__ import print_function

 import importlib
 import numpy as np
-
+import sys
 from tensorflow.contrib.distributions.python.ops import independent as independent_lib
 from tensorflow.contrib.distributions.python.ops import mvn_diag as mvn_diag_lib
 from tensorflow.python.framework import dtypes
@@ -231,9 +231,15 @@ class ProductDistributionTest(test.TestCase):
     def expected_log_prob(x, logits):
       return (x * logits - np.log1p(np.exp(logits))).sum(-1).sum(-1).sum(-1)

-    with self.cached_session() as sess:
-      logits_ph = array_ops.placeholder(
-          dtypes.float32, shape=logits.shape if static_shape else None)
+      with self.cached_session() as sess:
+
+       if sys.byteorder == "big":
+            logits_ph = array_ops.placeholder(
+            dtypes.float64, shape=logits.shape if static_shape else None)
+       else:
+            logits_ph = array_ops.placeholder(
+            dtypes.float32, shape=logits.shape if static_shape else None)
+
       ind = independent_lib.Independent(
           distribution=bernoulli_lib.Bernoulli(logits=logits_ph))
       x = ind.sample(sample_shape, seed=42)
```
The test passes with the above change on s390x as well as x86.
Could you please comment if this change is appropriate?

**Comment by anujajakhade** [comment]
@martinwicke Can you please comment on this?

**Comment by anujajakhade** [comment]
Discussion going on a similar fix in this [PR ](https://github.com/tensorflow/tensorflow/pull/26692)
