### ISSUE TITLE
Handle AddV2 and FusedBatchNormV3 in tflite_convert

### ISSUE THREAD

**Issue by kevinthecheung** [tensorflow/tensorflow#31901]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS 10.14.6
- TensorFlow installed from (source or binary): binary
- TensorFlow version (or github SHA if from source): 2.0.0b1

**Provide the text output from tflite_convert**

```
Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: AVERAGE_POOL_2D, CONCATENATION, CONV_2D, EXPAND_DIMS, LOGISTIC, MAX_POOL_2D, MEAN, MIRROR_PAD, MUL, PACK, RELU, RELU6, RESIZE_NEAREST_NEIGHBOR, RSQRT, SHAPE, SQUARED_DIFFERENCE, SQUEEZE, STRIDED_SLICE, SUB. Here is a list of operators for which you will need custom implementations: AddV2, FusedBatchNormV3.
```

Also, please include a link to a GraphDef or the model if possible.

https://tfhub.dev/google/magenta/arbitrary-image-stylization-v1-256/1

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by kevinthecheung** [comment]
Looks like it's in master.

**Comment by Checkmate986212** [comment]
I have the same problem, but I have no idea what you do to solve this.

Here is my tracebacks:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\anaconda\envs\Face_Recognition\lib\site-packages\tensorflow\lite\python\lite.py", line 898, in convert
    **converter_kwargs)
  File "E:\anaconda\envs\Face_Recognition\lib\site-packages\tensorflow\lite\python\convert.py", line 404, in toco_convert_impl
    input_data.SerializeToString())
  File "E:\anaconda\envs\Face_Recognition\lib\site-packages\tensorflow\lite\python\convert.py", line 172, in toco_convert_protos
    "TOCO failed. See console for info.\n%s\n%s\n" % (stdout, stderr))
tensorflow.lite.python.convert.ConverterError: TOCO failed. See console for info.
2019-09-03 20:25:13.931495: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: AddV2
2019-09-03 20:25:13.932230: E tensorflow/core/framework/op_kernel.cc:1426] OpKernel ('op: "NoOp" device_type: "CPU"') for unknown op: NoOp
2019-09-03 20:25:13.932603: E tensorflow/core/framework/op_kernel.cc:1426] OpKernel ('op: "NoOp" device_type: "GPU"') for unknown op: NoOp
2019-09-03 20:25:13.932957: E tensorflow/core/framework/op_kernel.cc:1426] OpKernel ('op: "_HostRecv" device_type: "GPU" host_memory_arg: "tensor"') for unknown op: _HostRecv
2019-09-03 20:25:13.933454: E tensorflow/core/framework/op_kernel.cc:1426] OpKernel ('op: "_Send" device_type: "CPU"') for unknown op: _Send
2019-09-03 20:25:13.933827: E tensorflow/core/framework/op_kernel.cc:1426] OpKernel ('op: "_HostRecv" device_type: "CPU"') for unknown op: _HostRecv
2019-09-03 20:25:13.934313: E tensorflow/core/framework/op_kernel.cc:1426] OpKernel ('op: "_Send" device_type: "GPU"') for unknown op: _Send
2019-09-03 20:25:13.934666: E tensorflow/core/framework/op_kernel.cc:1426] OpKernel ('op: "_Recv" device_type: "CPU"') for unknown op: _Recv
2019-09-03 20:25:13.935109: E tensorflow/core/framework/op_kernel.cc:1426] OpKernel ('op: "_HostSend" device_type: "GPU" host_memory_arg: "tensor"') for unknown op: _HostSend
2019-09-03 20:25:13.935581: E tensorflow/core/framework/op_kernel.cc:1426] OpKernel ('op: "_Recv" device_type: "GPU"') for unknown op: _Recv
2019-09-03 20:25:13.935940: E tensorflow/core/framework/op_kernel.cc:1426] OpKernel ('op: "_HostSend" device_type: "CPU"') for unknown op: _HostSend
2019-09-03 20:25:13.936406: E tensorflow/core/framework/op_kernel.cc:1426] OpKernel ('op: "WrapDatasetVariant" device_type: "CPU"') for unknown op: WrapDatasetVariant
2019-09-03 20:25:13.936840: E tensorflow/core/framework/op_kernel.cc:1426] OpKernel ('op: "WrapDatasetVariant" device_type: "GPU" host_memory_arg: "input_handle" host_memory_arg: "output_handle"') for unknown op: WrapDatasetVariant
2019-09-03 20:25:13.937432: E tensorflow/core/framework/op_kernel.cc:1426] OpKernel ('op: "UnwrapDatasetVariant" device_type: "CPU"') for unknown op: UnwrapDatasetVariant
2019-09-03 20:25:13.937872: E tensorflow/core/framework/op_kernel.cc:1426] OpKernel ('op: "UnwrapDatasetVariant" device_type: "GPU" host_memory_arg: "input_handle" host_memory_arg: "output_handle"') for unknown op: UnwrapDatasetVariant
2019-09-03 20:25:13.938585: I tensorflow/lite/toco/import_tensorflow.cc:1385] Unable to determine output type for op: AddV2
2019-09-03 20:25:13.939038: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: AddV2
2019-09-03 20:25:13.939337: I tensorflow/lite/toco/import_tensorflow.cc:1385] Unable to determine output type for op: AddV2
2019-09-03 20:25:13.939688: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: AddV2
2019-09-03 20:25:13.940042: I tensorflow/lite/toco/import_tensorflow.cc:1385] Unable to determine output type for op: AddV2
2019-09-03 20:25:13.940503: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: AddV2
2019-09-03 20:25:13.940784: I tensorflow/lite/toco/import_tensorflow.cc:1385] Unable to determine output type for op: AddV2
2019-09-03 20:25:13.941269: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: AddV2
2019-09-03 20:25:13.941562: I tensorflow/lite/toco/import_tensorflow.cc:1385] Unable to determine output type for op: AddV2
2019-09-03 20:25:13.941985: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: AddV2
2019-09-03 20:25:13.942400: I tensorflow/lite/toco/import_tensorflow.cc:1385] Unable to determine output type for op: AddV2
2019-09-03 20:25:13.942873: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: AddV2
2019-09-03 20:25:13.943286: I tensorflow/lite/toco/import_tensorflow.cc:1385] Unable to determine output type for op: AddV2
2019-09-03 20:25:13.943748: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: AddV2
2019-09-03 20:25:13.944123: I tensorflow/lite/toco/import_tensorflow.cc:1385] Unable to determine output type for op: AddV2
2019-09-03 20:25:13.944613: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: AddV2
2019-09-03 20:25:13.945035: I tensorflow/lite/toco/import_tensorflow.cc:1385] Unable to determine output type for op: AddV2
2019-09-03 20:25:13.945454: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: AddV2
2019-09-03 20:25:13.945790: I tensorflow/lite/toco/import_tensorflow.cc:1385] Unable to determine output type for op: AddV2
2019-09-03 20:25:13.946425: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: IdentityN
2019-09-03 20:25:13.946883: I tensorflow/lite/toco/import_tensorflow.cc:1385] Unable to determine output type for op: IdentityN
2019-09-03 20:25:13.966304: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 378 operators, 701 arrays (0 quantized)
2019-09-03 20:25:13.997206: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 378 operators, 701 arrays (0 quantized)
2019-09-03 20:25:14.035854: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 1: 72 operators, 187 arrays (0 quantized)
2019-09-03 20:25:14.040310: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Group bidirectional sequence lstm/rnn: 72 operators, 187 arrays (0 quantized)
2019-09-03 20:25:14.044211: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before dequantization graph transformations: 72 operators, 187 arrays (0 quantized)
2019-09-03 20:25:14.051806: I tensorflow/lite/toco/allocate_transient_arrays.cc:345] Total transient array allocated size: 10523008 bytes, theoretical optimal value: 9720192 bytes.
2019-09-03 20:25:14.053806: E tensorflow/lite/toco/toco_tooling.cc:456] We are continually in the process of adding support to TensorFlow Lite for more ops. It would be helpful if you could inform us of how this conversion went by opening a github issue at https://github.com/tensorflow/tensorflow/issues/new?template=40-tflite-op-request.md
 and pasting the following:

Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: CONV_2D, DEPTHWISE_CONV_2D, FULLY_CONNECTED, MEAN, PAD, SOFTMAX. Here is a list of operators for which you will need custom implementations: AddV2, IdentityN.
Traceback (most recent call last):
  File "e:\anaconda\envs\face_recognition\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "e:\anaconda\envs\face_recognition\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\anaconda\envs\Face_Recognition\Scripts\toco_from_protos.exe\__main__.py", line 9, in <module>
  File "e:\anaconda\envs\face_recognition\lib\site-packages\tensorflow\lite\toco\python\toco_from_protos.py", line 59, in main
    app.run(main=execute, argv=[sys.argv[0]] + unparsed)
  File "e:\anaconda\envs\face_recognition\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "e:\anaconda\envs\face_recognition\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "e:\anaconda\envs\face_recognition\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "e:\anaconda\envs\face_recognition\lib\site-packages\tensorflow\lite\toco\python\toco_from_protos.py", line 33, in execute
    output_str = tensorflow_wrap_toco.TocoConvert(model_str, toco_str, input_str)
Exception: We are continually in the process of adding support to TensorFlow Lite for more ops. It would be helpful if you could inform us of how this conversion went by opening a github issue at https://github.com/tensorflow/tensorflow/issues/new?template=40-tflite-op-request.md
 and pasting the following:

Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: CONV_2D, DEPTHWISE_CONV_2D, FULLY_CONNECTED, MEAN, PAD, SOFTMAX. Here is a list of operators for which you will need custom implementations: AddV2, IdentityN.

I sincerely hope you could help me

**Comment by RobertBiehl** [comment]
Have the same problem, specifically with `AddV2`, which is nowhere to be found in the TFLiteConverter code.

**Comment by eaaarmah** [comment]
I also have the same problem

Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: CONV_2D, DEPTHWISE_CONV_2D, FULLY_CONNECTED, PAD, RELU6, SOFTMAX. Here is a list of operators for which you will need custom implementations: FusedBatchNormV3.

**Comment by chanakasandaruwan** [comment]
Uncaught (in promise) Error: Tensorflow Op is not supported: AddV2
    at t.mapNode (operation_mapper.ts:125)
    at operation_mapper.ts:86
    at Array.reduce (<anonymous>)
    at t.transformGraph (operation_mapper.ts:85)
    at t.<anonymous> (graph_model.ts:125)
    at callbacks.ts:17
    at Object.next (callbacks.ts:17)
    at a (callbacks.ts:17)

my error I can not figure out what the problem

**Comment by timothyb365** [comment]
Uncaught (in promise) Error: Tensorflow Op is not supported: AddV2
    at t.mapNode (operation_mapper.ts:125)
    at operation_mapper.ts:86
    at Array.reduce (<anonymous>)
    at t.transformGraph (operation_mapper.ts:85)
    at t.<anonymous> (graph_model.ts:125)
    at callbacks.ts:17
    at Object.next (callbacks.ts:17)
    at a (callbacks.ts:17)
Getting the same error  but I cant figure out what the problem  using the latest tensorflowjs 1.7.4

**Comment by chanakasandaruwan** [comment]
This error is mainly come your model is make by  separate version of
tensorflow coding,either 1 or 2 then, if you can make model using only one
version of coding then problem solved

If you don't figure out yet set me model code if you like I will figure out
it

**Comment by timothyb365** [comment]
Setup Tensorflow Graph

X = tf.placeholder(tf.float32, shape=[None, TOTAL_INPUTS], name='X')
y = tf.placeholder(tf.float32, shape=[None, NR_CLASSES], name='labels')

                          Neural Network Architecture
                           Hyperparameters

nr_epochs = 50
learning_rate = 1e-3
​
n_hidden1 = 512
n_hidden2 = 64
def setup_layer(input, weight_dim, bias_dim, name):
    with tf.name_scope(name):
        initial_w = tf.truncated_normal(shape=weight_dim, stddev=0.1, seed=42)
        w = tf.Variable(initial_value=initial_w, name='W')
​
        initial_b = tf.constant(value=0.0, shape=bias_dim)
        b = tf.Variable(initial_value=initial_b, name='B')
​
        layer_in = tf.matmul(input, w) + b
        
        if name=='out':
            layer_out = tf.nn.softmax(layer_in)
        else:
            layer_out = tf.nn.relu(layer_in)
        
        tf.summary.histogram('weights', w)
        tf.summary.histogram('biases', b)
        
        return layer_out
'
layer_1 = setup_layer(X, weight_dim=[TOTAL_INPUTS, n_hidden1],
                      bias_dim=[n_hidden1],name='layer_1' )
​
layer_drop = tf.nn.dropout(layer_1, keep_prob=0.8, name='dropout_layer')
​
layer_2 = setup_layer(layer_drop, weight_dim=[n_hidden1, n_hidden2],
                      bias_dim=[n_hidden2],name='layer_2' )
​
output = setup_layer(layer_2, weight_dim=[n_hidden2, NR_CLASSES],
                      bias_dim=[NR_CLASSES],name='out' )
model_name = f'{n_hidden1}-DO-{n_hidden2} LR{learning_rate} E{nr_epochs}'
Tensorboard Setup
# folder for tensorboard
folder_name = f'{model_name} at {strftime("%H%M")}'
directory = os.path.join(LOGGING_PATH, folder_name)
​
try:
    os.makedirs(directory)
except OSError as exception:
    print(exception.strerror)
else:
    print('successfully created directories!')
successfully created directories!
Loss Optimisation & Metrics
Defining Loss Function
with tf.name_scope('loss_calc'):
    loss = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(labels=y, logits=output))
Defining Optimiser
with tf.name_scope('optimiser'):
    optimiser = tf.train.AdamOptimizer(learning_rate=learning_rate)
    train_step = optimiser.minimize(loss)
Accuracy Metric
with tf.name_scope('accuracy_calc'):
    model_prediction=tf.argmax(output, axis=1, name='prediction')
    correct_pred = tf.equal(model_prediction, tf.argmax(y, axis=1))
    accuracy = tf.reduce_mean(tf.cast(correct_pred, tf.float32))
with tf.name_scope('perfomance'):
    tf.summary.scalar('accuracy', accuracy)
    tf.summary.scalar('cost', loss)
Check input images in Tensorboard
with tf.name_scope('show_image'):
    x_image = tf.reshape(X, [-1, 28, 28, 1])
    tf.summary.image('image_input', x_image, max_outputs=4)
​
​
Run Session
sess = tf.compat.v1.Session()
Setup Filewriter and Merge Summuries
merged_summary = tf.summary.merge_all()
​
train_writer = tf.summary.FileWriter(directory + '/train')
train_writer.add_graph(sess.graph)
​
validation_writer = tf.summary.FileWriter(directory + '/validation')
# intialise all the variables
init = tf.global_variables_initializer()
sess.run(init)
Batching the Data
size_of_batch = 1000
num_examples = y_train.shape[0]
nr_iterations = int(num_examples/size_of_batch)
​
index_in_epoch = 0
def next_batch(batch_size, data, labels):
    
    global num_examples
    global index_in_epoch
    
    start = index_in_epoch
    index_in_epoch += batch_size
    
    if index_in_epoch > num_examples:
        start = 0
        index_in_epoch = batch_size
    
    
    
    end = index_in_epoch
    
    return data[start:end], labels[start:end]
Training Loop
for epoch in range(nr_epochs):
    # ============== Training Dataset ======
    for i in range(nr_iterations):
        batch_x, batch_y = next_batch(batch_size=size_of_batch, data=x_train, labels=y_train)
        
        feed_dictionery = {X:batch_x, y:batch_y}
        
        sess.run(train_step, feed_dict=feed_dictionery)
        
    s, batch_accuracy = sess.run(fetches=[merged_summary, accuracy], feed_dict=feed_dictionery)
     
    train_writer.add_summary(s, epoch)    
    print(f'Epoch {epoch} \t! Training Accuracy = {batch_accuracy}')
    
    # ================ Validation =================
    
    summary = sess.run(fetches=merged_summary, feed_dict={X:x_val, y:y_val})
    validation_writer.add_summary(summary, epoch)
    
print('done training!')
for epoch in range(nr_epochs):
    # ============== Training Dataset ======
    for i in range(nr_iterations):
        batch_x, batch_y = next_batch(batch_size=size_of_batch, data=x_train, labels=y_train)
        
        feed_dictionery = {X:batch_x, y:batch_y}
        
        sess.run(train_step, feed_dict=feed_dictionery)
        
    s, batch_accuracy = sess.run(fetches=[merged_summary, accuracy], feed_dict=feed_dictionery)
     
    train_writer.add_summary(s, epoch)    
    print(f'Epoch {epoch} \t! Training Accuracy = {batch_accuracy}')
    
    # ================ Validation =================
    
    summary = sess.run(fetches=merged_summary, feed_dict={X:x_val, y:y_val})
    validation_writer.add_summary(summary, epoch)
    
print('done training!')
Saving the Model
outputs = {'accuracy_calc/prediction':model_prediction}
inputs = {'X':X}
tf.compat.v1.saved_model.simple_save(sess, 'SavedModel', inputs, outputs)

this is the model code @chanakasandaruwan

**Comment by timothyb365** [comment]
def setup_layer(input, weight_dim, bias_dim, name):
    with tf.name_scope(name):
        initial_w = tf.truncated_normal(shape=weight_dim, stddev=0.1, seed=42)
        w = tf.Variable(initial_value=initial_w, name='W')

        initial_b = tf.constant(value=0.0, shape=bias_dim)
        b = tf.Variable(initial_value=initial_b, name='B')

        layer_in = tf.matmul(input, w) + b
        
        if name=='out':
            layer_out = tf.nn.softmax(layer_in)
        else:
            layer_out = tf.nn.relu(layer_in)
        
        tf.summary.histogram('weights', w)
        tf.summary.histogram('biases', b)
        
        return layer_out

layer_1 = setup_layer(X, weight_dim=[TOTAL_INPUTS, n_hidden1],
                      bias_dim=[n_hidden1],name='layer_1' )

layer_drop = tf.nn.dropout(layer_1, keep_prob=0.8, name='dropout_layer')

layer_2 = setup_layer(layer_drop, weight_dim=[n_hidden1, n_hidden2],
                      bias_dim=[n_hidden2],name='layer_2' )

output = setup_layer(layer_2, weight_dim=[n_hidden2, NR_CLASSES],
                      bias_dim=[NR_CLASSES],name='out' )
model_name = f'{n_hidden1}-DO-{n_hidden2} LR{learning_rate} E{nr_epochs}'


def next_batch(batch_size, data, labels):
    
    global num_examples
    global index_in_epoch
    
    start = index_in_epoch
    index_in_epoch += batch_size
    
    if index_in_epoch > num_examples:
        start = 0
        index_in_epoch = batch_size
    
    
    
    end = index_in_epoch
    
    return data[start:end], labels[start:end]


for epoch in range(nr_epochs):
    # ============== Training Dataset ======
    for i in range(nr_iterations):
        batch_x, batch_y = next_batch(batch_size=size_of_batch, data=x_train, labels=y_train)
        
        feed_dictionery = {X:batch_x, y:batch_y}
        
        sess.run(train_step, feed_dict=feed_dictionery)
        
    s, batch_accuracy = sess.run(fetches=[merged_summary, accuracy], feed_dict=feed_dictionery)
     
    train_writer.add_summary(s, epoch)    
    print(f'Epoch {epoch} \t! Training Accuracy = {batch_accuracy}')
    
    # ================ Validation =================
    
    summary = sess.run(fetches=merged_summary, feed_dict={X:x_val, y:y_val})
    validation_writer.add_summary(summary, epoch)
    
print('done training!')


this is a bit clear code @chanakasandaruwan

**Comment by chanakasandaruwan** [comment]
Give me time I working with your information,if I figure out I will tell you

**Comment by chanakasandaruwan** [comment]
Setup Tensorflow Graph

#add this code before placeholder try it is working

import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

X = tf.placeholder(tf.float32, shape=[None, TOTAL_INPUTS], name='X')
y = tf.placeholder(tf.float32, shape=[None, NR_CLASSES], name='labels')

**Comment by timothyb365** [comment]
@chanakasandaruwan thanks so much the code is now working

**Comment by chanakasandaruwan** [comment]
💪Nice to help you Sir
