### ISSUE TITLE
TF2.0 from source crashes with optimizer specified as instance

### ISSUE THREAD

**Issue by seijikun** [tensorflow/tensorflow#31953]
**System information**
- Have I written custom code: **yes**
- OS Platform and Distribution: **OpenSUSE Tumbleweed**
- TensorFlow installed from: **source**
- TensorFlow version: **v2.0.0-rc0-0-gc75bb66a99 2.0.0-rc0**
- Python version: **3.7.3**
- Bazel version: **0.26**
- GCC/Compiler version: **gcc (SUSE Linux) 9.1.1 20190805 [gcc-9-branch revision 274114]**
- CUDA/cuDNN version: **-**
- GPU model and memory: **gfx803 - Ellesmere - AMD Radeon RX 580 - 8192MB**

**Describe the current behavior**
When the optimizer is specified in the form of a string (e.g. `adam`) in `model.compile(...)`, everything works as expected. When the optimizer is specified with non-default parameters, like:
```python
model.compile(loss='mse', optimizer=optimizers.Adam(lr=0.01337))
```
the application crashes with the following error:
```
Traceback (most recent call last):
  File "/home/seiji/.local/lib/python3.7/site-packages/tensorflow_core/python/framework/op_def_library.py", line 527, in _apply_op_helper
    preferred_dtype=default_dtype)
  File "/home/seiji/.local/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 1296, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/seiji/.local/lib/python3.7/site-packages/tensorflow_core/python/framework/constant_op.py", line 286, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/home/seiji/.local/lib/python3.7/site-packages/tensorflow_core/python/framework/constant_op.py", line 227, in constant
    allow_broadcast=True)
  File "/home/seiji/.local/lib/python3.7/site-packages/tensorflow_core/python/framework/constant_op.py", line 265, in _constant_impl
    allow_broadcast=allow_broadcast))
  File "/home/seiji/.local/lib/python3.7/site-packages/tensorflow_core/python/framework/tensor_util.py", line 437, in make_tensor_proto
    raise ValueError("None values not supported.")
ValueError: None values not supported.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/seiji/.local/lib/python3.7/site-packages/tensorflow_core/python/framework/op_def_library.py", line 541, in _apply_op_helper
    values, as_ref=input_arg.is_ref).dtype.name
  File "/home/seiji/.local/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 1296, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/seiji/.local/lib/python3.7/site-packages/tensorflow_core/python/framework/constant_op.py", line 286, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/home/seiji/.local/lib/python3.7/site-packages/tensorflow_core/python/framework/constant_op.py", line 227, in constant
    allow_broadcast=True)
  File "/home/seiji/.local/lib/python3.7/site-packages/tensorflow_core/python/framework/constant_op.py", line 265, in _constant_impl
    allow_broadcast=allow_broadcast))
  File "/home/seiji/.local/lib/python3.7/site-packages/tensorflow_core/python/framework/tensor_util.py", line 437, in make_tensor_proto
    raise ValueError("None values not supported.")
ValueError: None values not supported.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/seiji/.vscode/extensions/ms-python.python-2019.8.30787/pythonFiles/ptvsd_launcher.py", line 43, in <module>
    main(ptvsdArgs)
  File "/home/seiji/.vscode/extensions/ms-python.python-2019.8.30787/pythonFiles/lib/python/ptvsd/__main__.py", line 432, in main
    run()
  File "/home/seiji/.vscode/extensions/ms-python.python-2019.8.30787/pythonFiles/lib/python/ptvsd/__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "/usr/lib64/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/usr/lib64/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/mnt/data/Documents/seiji.li/FHWS/Master/SS2019/Masterarbeit/workspace/Autoencoder_Example/autoencoder_conv3.py", line 28, in <module>
    autoencoder.fit(train_features, train_features, verbose=1, shuffle=True)
  File "/home/seiji/.local/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 734, in fit
    use_multiprocessing=use_multiprocessing)
  File "/home/seiji/.local/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_arrays.py", line 674, in fit
    steps_name='steps_per_epoch')
  File "/home/seiji/.local/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_arrays.py", line 189, in model_iteration
    f = _make_execution_function(model, mode)
  File "/home/seiji/.local/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_arrays.py", line 565, in _make_execution_function
    return model._make_execution_function(mode)
  File "/home/seiji/.local/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 2149, in _make_execution_function
    self._make_train_function()
  File "/home/seiji/.local/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 2081, in _make_train_function
    params=self._collected_trainable_weights, loss=self.total_loss)
  File "/home/seiji/.local/lib/python3.7/site-packages/tensorflow_core/python/keras/optimizers.py", line 476, in get_updates
    grads = self.get_gradients(loss, params)
  File "/home/seiji/.local/lib/python3.7/site-packages/tensorflow_core/python/keras/optimizers.py", line 92, in get_gradients
    if None in grads:
  File "/home/seiji/.local/lib/python3.7/site-packages/tensorflow_core/python/ops/math_ops.py", line 1283, in tensor_equals
    return gen_math_ops.equal(self, other)
  File "/home/seiji/.local/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_math_ops.py", line 3629, in equal
    "Equal", x=x, y=y, name=name)
  File "/home/seiji/.local/lib/python3.7/site-packages/tensorflow_core/python/framework/op_def_library.py", line 545, in _apply_op_helper
    (input_name, err))
ValueError: Tried to convert 'y' to a tensor and failed. Error: None values not supported.
Terminated
```
This **only** happens, when using the tensorflow compiled from source. The version `2.0.0b1` as distributed through pip works as expected.
I have tested Tensorflow compiled from source **with** and **without** ROCm enabled. Both crash.

**Describe the expected behavior**
Specifying an optimizer as variable instead of with a string and default parameters should work.

**Code to reproduce the issue**
```python
import numpy as np
import tensorflow
from tensorflow.python.keras.layers import Input, Dense
from tensorflow.python.keras.models import Sequential
from tensorflow.python.keras import backend as K
from tensorflow.python.keras import optimizers

original_dim = 160
intermediate_dim = 32
# load data
train_features = np.random.rand(100000, original_dim).astype(np.float32)
test_features = np.random.rand(10000, original_dim).astype(np.float32)

############# BUILD MODEL #############
autoencoder = Sequential()
autoencoder.add( Input(shape=(original_dim,)) )
autoencoder.add( Dense(intermediate_dim) )
autoencoder.add( Dense(original_dim) )
autoencoder.build()
autoencoder.summary()

# crashes:
autoencoder.compile(loss='mse', optimizer=optimizers.Adam(lr=0.01337))
#works:
#autoencoder.compile(loss='mse', optimizer='adam')

# Train model
autoencoder.fit(train_features, train_features, verbose=1, shuffle=True)
```

**Comment by WindQAQ** [comment]
So the problem is that you access v1 style optimizer. If you use `tf.keras.optimizers.Adam` instead, you can get an `OptimizerV2` instance, which works fine in your example. My best practice is not to access private API, and try to run codes with public endpoints like `tf.*, tf.keras.*`. Workable colab is here: https://colab.research.google.com/drive/1ZlUU0fSmxtdBtJ3L4jdMOhI8WpbnZOnB

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/optimizers.py
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/python/keras/optimizer_v2

**Comment by seijikun** [comment]
That was the problem. Should be more carefull, copying code from Stackoverflow next time. :sweat_smile: 
Thank you!

**Comment by saitam757** [comment]
@seijikun Hi. Just out of curiosity, how do you run TF with AMD GPU acceleration on openSUSE TW ? Within a docker container or did you managed to compile and installed all ROCm stuff locally ? If the latter is the case, I definitely need to know how  :flushed:

**Comment by seijikun** [comment]
@saitam757 I am using it without docker. That's actually pretty easy. AMD provides RPM packages. Those are not meant for openSUSE (when installing normally, they will complain that stuff like the libc is missing). But if you install them like in this blog-post: https://www.clarenceho.net/2019/05/rocm-opencl-with-opensuse-tumbleweed.html, everything just works.

**Comment by saitam757** [comment]
@seijikun Thank you very much for this information. Just one question: For getting tensorflow to run you need all the libraries installed up to miopen. I guess, all rpms are installed in the same way ? Without dependencies ? Again, thanks a lot.

**Comment by seijikun** [comment]
@saitam757 I compiled tensorflow with ROCm myself. When doing that, the build fails one after another, stating what's missing. Packages that I remember installing are:
- rocrand
- rocfft
- hsa-amd-aqlprofile
- rocm-libs
- rocm-device-libs
- rocm-dev
- hip_hcc
- hip_base
- miopen-hip

**Comment by saitam757** [comment]
@seijikun The configuration sounds exciting. :smiley: Compiled for Fedora, with all those dependencies. Thanks for these information.
