### ISSUE TITLE
NotImplementedError in Distributed tensorflow with parameter_server

### ISSUE THREAD

**Issue by PlusWayne** [tensorflow/tensorflow#32010]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): linux
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.0.0rc
- Python version: 3.6.5
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:  cuda 10.0/ cudnn 7.6
- GPU model and memory: Tesla, 24gb per gpg

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Hi, i am using this script resnet_cifar_main.py in https://github.com/tensorflow/models/tree/master/official/vision/image_classification to test parameter distributed strategy. I have added some codes to configure cluster in this file as follows
```
import os
 import json
 tf.compat.v1.disable_eager_execution() # if not, it will raise error
os.environ["TF_CONFIG"] = json.dumps({
      'cluster': {
        'ps' : ["100.102.32.179:8080"],
        'worker':  ["100.102.33.40:8080"]
                  },
         'task': # {'type':'ps', 'index':0} # for the ps sever
            {'type': 'worker', 'index': 0}
          })
```
for the ps server, i have done the similar things. 
i use the following command to run .
`python resnet_cifar_main.py --data_dir cifar-10-batches-bin/ --distribution_strategy parameter_server`.
It works when i set only one gpu avaiable. that is,
```
export CUDA_VISIBLE_DEVICES=0
```
However, when i set all gpu avaiable, it fails with the following error log.
```
/data1/wayneweixu/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/data1/wayneweixu/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/data1/wayneweixu/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/data1/wayneweixu/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/data1/wayneweixu/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/data1/wayneweixu/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
2019-08-27 21:20:21.718509: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2019-08-27 21:20:21.771457: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: Tesla M40 24GB major: 5 minor: 2 memoryClockRate(GHz): 1.112
pciBusID: 0000:04:00.0
2019-08-27 21:20:21.772876: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 1 with properties: 
name: Tesla M40 24GB major: 5 minor: 2 memoryClockRate(GHz): 1.112
pciBusID: 0000:05:00.0
2019-08-27 21:20:21.774307: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 2 with properties: 
name: Tesla M40 24GB major: 5 minor: 2 memoryClockRate(GHz): 1.112
pciBusID: 0000:08:00.0
2019-08-27 21:20:21.775831: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 3 with properties: 
name: Tesla M40 24GB major: 5 minor: 2 memoryClockRate(GHz): 1.112
pciBusID: 0000:09:00.0
2019-08-27 21:20:21.777206: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 4 with properties: 
name: Tesla M40 24GB major: 5 minor: 2 memoryClockRate(GHz): 1.112
pciBusID: 0000:84:00.0
2019-08-27 21:20:21.778613: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 5 with properties: 
name: Tesla M40 24GB major: 5 minor: 2 memoryClockRate(GHz): 1.112
pciBusID: 0000:85:00.0
2019-08-27 21:20:21.780023: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 6 with properties: 
name: Tesla M40 24GB major: 5 minor: 2 memoryClockRate(GHz): 1.112
pciBusID: 0000:88:00.0
2019-08-27 21:20:21.781431: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 7 with properties: 
name: Tesla M40 24GB major: 5 minor: 2 memoryClockRate(GHz): 1.112
pciBusID: 0000:89:00.0
2019-08-27 21:20:21.781638: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2019-08-27 21:20:21.783058: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2019-08-27 21:20:21.784468: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2019-08-27 21:20:21.784759: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2019-08-27 21:20:21.786481: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2019-08-27 21:20:21.787803: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2019-08-27 21:20:21.791692: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2019-08-27 21:20:21.813851: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0, 1, 2, 3, 4, 5, 6, 7
2019-08-27 21:20:21.814258: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-08-27 21:20:21.823038: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2399910000 Hz
2019-08-27 21:20:21.824902: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7f1b04056a20 executing computations on platform Host. Devices:
2019-08-27 21:20:21.824934: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
2019-08-27 21:20:23.267705: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7f1b03884990 executing computations on platform CUDA. Devices:
2019-08-27 21:20:23.267737: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Tesla M40 24GB, Compute Capability 5.2
2019-08-27 21:20:23.267744: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (1): Tesla M40 24GB, Compute Capability 5.2
2019-08-27 21:20:23.267749: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (2): Tesla M40 24GB, Compute Capability 5.2
2019-08-27 21:20:23.267755: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (3): Tesla M40 24GB, Compute Capability 5.2
2019-08-27 21:20:23.267760: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (4): Tesla M40 24GB, Compute Capability 5.2
2019-08-27 21:20:23.267766: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (5): Tesla M40 24GB, Compute Capability 5.2
2019-08-27 21:20:23.267771: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (6): Tesla M40 24GB, Compute Capability 5.2
2019-08-27 21:20:23.267776: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (7): Tesla M40 24GB, Compute Capability 5.2
2019-08-27 21:20:23.277272: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: Tesla M40 24GB major: 5 minor: 2 memoryClockRate(GHz): 1.112
pciBusID: 0000:04:00.0
2019-08-27 21:20:23.278704: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 1 with properties: 
name: Tesla M40 24GB major: 5 minor: 2 memoryClockRate(GHz): 1.112
pciBusID: 0000:05:00.0
2019-08-27 21:20:23.280111: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 2 with properties: 
name: Tesla M40 24GB major: 5 minor: 2 memoryClockRate(GHz): 1.112
pciBusID: 0000:08:00.0
2019-08-27 21:20:23.281511: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 3 with properties: 
name: Tesla M40 24GB major: 5 minor: 2 memoryClockRate(GHz): 1.112
pciBusID: 0000:09:00.0
2019-08-27 21:20:23.282918: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 4 with properties: 
name: Tesla M40 24GB major: 5 minor: 2 memoryClockRate(GHz): 1.112
pciBusID: 0000:84:00.0
2019-08-27 21:20:23.284400: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 5 with properties: 
name: Tesla M40 24GB major: 5 minor: 2 memoryClockRate(GHz): 1.112
pciBusID: 0000:85:00.0
2019-08-27 21:20:23.285821: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 6 with properties: 
name: Tesla M40 24GB major: 5 minor: 2 memoryClockRate(GHz): 1.112
pciBusID: 0000:88:00.0
2019-08-27 21:20:23.287255: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 7 with properties: 
name: Tesla M40 24GB major: 5 minor: 2 memoryClockRate(GHz): 1.112
pciBusID: 0000:89:00.0
2019-08-27 21:20:23.287327: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2019-08-27 21:20:23.287349: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2019-08-27 21:20:23.287374: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2019-08-27 21:20:23.287398: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2019-08-27 21:20:23.287416: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2019-08-27 21:20:23.287434: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2019-08-27 21:20:23.287452: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2019-08-27 21:20:23.309337: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0, 1, 2, 3, 4, 5, 6, 7
2019-08-27 21:20:23.309395: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2019-08-27 21:20:23.321783: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-08-27 21:20:23.321864: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 1 2 3 4 5 6 7 
2019-08-27 21:20:23.321876: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N Y Y Y N N N N 
2019-08-27 21:20:23.321885: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 1:   Y N Y Y N N N N 
2019-08-27 21:20:23.321900: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 2:   Y Y N Y N N N N 
2019-08-27 21:20:23.321908: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 3:   Y Y Y N N N N N 
2019-08-27 21:20:23.321916: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 4:   N N N N N Y Y Y 
2019-08-27 21:20:23.321930: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 5:   N N N N Y N Y Y 
2019-08-27 21:20:23.321944: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 6:   N N N N Y Y N Y 
2019-08-27 21:20:23.321959: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 7:   N N N N Y Y Y N 
2019-08-27 21:20:23.337402: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 13843 MB memory) -> physical GPU (device: 0, name: Tesla M40 24GB, pci bus id: 0000:04:00.0, compute capability: 5.2)
2019-08-27 21:20:23.339205: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 16016 MB memory) -> physical GPU (device: 1, name: Tesla M40 24GB, pci bus id: 0000:05:00.0, compute capability: 5.2)
2019-08-27 21:20:23.340928: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:2 with 16166 MB memory) -> physical GPU (device: 2, name: Tesla M40 24GB, pci bus id: 0000:08:00.0, compute capability: 5.2)
2019-08-27 21:20:23.342575: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:3 with 15535 MB memory) -> physical GPU (device: 3, name: Tesla M40 24GB, pci bus id: 0000:09:00.0, compute capability: 5.2)
2019-08-27 21:20:23.344296: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:4 with 13420 MB memory) -> physical GPU (device: 4, name: Tesla M40 24GB, pci bus id: 0000:84:00.0, compute capability: 5.2)
2019-08-27 21:20:23.345968: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:5 with 16228 MB memory) -> physical GPU (device: 5, name: Tesla M40 24GB, pci bus id: 0000:85:00.0, compute capability: 5.2)
2019-08-27 21:20:23.347619: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:6 with 15985 MB memory) -> physical GPU (device: 6, name: Tesla M40 24GB, pci bus id: 0000:88:00.0, compute capability: 5.2)
2019-08-27 21:20:23.349287: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:7 with 16314 MB memory) -> physical GPU (device: 7, name: Tesla M40 24GB, pci bus id: 0000:89:00.0, compute capability: 5.2)
I0827 21:20:23.353662 139753917540160 parameter_server_strategy.py:250] Multi-worker ParameterServerStrategy with cluster_spec = {'ps': ['100.102.32.179:8080'], 'worker': ['100.102.33.40:8080']}, task_type = 'worker', task_id = 0, num_ps_replicas = 1, is_chief = True, device_map = ReplicaDeviceMap(['/job:worker/replica:0/task:0/device:GPU:0', '/job:worker/replica:0/task:0/device:GPU:1', '/job:worker/replica:0/task:0/device:GPU:2', '/job:worker/replica:0/task:0/device:GPU:3', '/job:worker/replica:0/task:0/device:GPU:4', '/job:worker/replica:0/task:0/device:GPU:5', '/job:worker/replica:0/task:0/device:GPU:6', '/job:worker/replica:0/task:0/device:GPU:7']), variable_device = <bound method _ReplicaDeviceChooser.device_function of <tensorflow.python.training.device_setter._ReplicaDeviceChooser object at 0x7f1a966e84e0>>
Contrib missing: Skip remove monkey patch tf.contrib.distribute.*
W0827 21:20:23.734989 139753917540160 deprecation.py:323] From /data1/wayneweixu/.local/lib/python3.6/site-packages/tensorflow_core/python/ops/image_ops_impl.py:1518: div (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Deprecated in favor of operator or tf.math.divide.
W0827 21:20:23.736282 139753917540160 deprecation.py:323] From /data1/wayneweixu/.local/lib/python3.6/site-packages/tensorflow_core/python/autograph/impl/api.py:332: sparse_to_dense (from tensorflow.python.ops.sparse_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Create a `tf.sparse.SparseTensor` and use `tf.sparse.to_dense` instead.
W0827 21:20:23.800738 139753917540160 deprecation.py:506] From /data1/wayneweixu/.local/lib/python3.6/site-packages/tensorflow_core/python/ops/resource_variable_ops.py:1630: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
Traceback (most recent call last):
  File "resnet_cifar_main_dist_ps_remote_0.py", line 260, in <module>
    absl_app.run(main)
  File "/data1/wayneweixu/.local/lib/python3.6/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/data1/wayneweixu/.local/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "resnet_cifar_main_dist_ps_remote_0.py", line 254, in main
    return run(flags.FLAGS)
  File "resnet_cifar_main_dist_ps_remote_0.py", line 173, in run
    model = resnet_cifar_model.resnet56(classes=cifar_preprocessing.NUM_CLASSES)
  File "/data1/wayneweixu/models/official/vision/image_classification/resnet_cifar_model.py", line 227, in resnet
    name='conv1')(x)
  File "/data1/wayneweixu/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 777, in __call__
    self._maybe_build(inputs)
  File "/data1/wayneweixu/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 2099, in _maybe_build
    self.build(input_shapes)
  File "/data1/wayneweixu/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/layers/convolutional.py", line 165, in build
    dtype=self.dtype)
  File "/data1/wayneweixu/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 2269, in __setattr__
    if val.trainable:
  File "/data1/wayneweixu/.local/lib/python3.6/site-packages/tensorflow_core/python/ops/variables.py", line 476, in trainable
    raise NotImplementedError
NotImplementedError
```
how can i fix this error? thanks a lot.
**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by PlusWayne** [comment]
> Parameter Server strategy is post 2.0. please look at the below link to find whats supported in 2.0 and Distribution Strategy.
> https://www.tensorflow.org/beta/guide/distribute_strategy#whats_supported_now

I see that 
> In TF 2.0 beta release, we support training with Keras using MirroredStrategy, CentralStorageStrategy and MultiWorkerMirroredStrategy. Both CentralStorageStrategy and MultiWorkerMirroredStrategy are currently experimental APIs and are subject to change. Support for other strategies will be coming soon. The API and how to use will be exactly the same as above.
However, i am using tf 2.0 rc. I am not sure that whether parameter server strategy is supported in tf2.0 rc. But i can run in ps strategy  when i let only one gpu avaiable. Could you explain why for one gpu it works, but failed with multiple gpus.

**Comment by PlusWayne** [comment]
> Hello,
> sorry if the earlier message was not clear, but Parameter Server support will be added in post 2.0.0 releases, so 2.0rc0 does not have it yet. That could be the reason why multi gpu is not working.

Thanks for you help :-).
I can close this issue now.
