### ISSUE TITLE
Tensorflow, Windows Server 2019 and WSL

### ISSUE THREAD

**Issue by nikigre** [tensorflow/tensorflow#32053]
**System information**
- Windows Server 2019 Essentials and Ubuntu 18.04 LTS in WSL
- TensorFlow installed with pip3 install
- TensorFlow version: All versions above 1.6.0 throw an error
- Python version: 3.6.8
- Installed using pip
- Only CPU

I am trying to use this GitHub repository: https://github.com/begeekmyfriend/tacotron. And all versions above 1.6.0 don't work. I get an error: core dumped. If I install older versions I get different errors like this: `AttributeError: module 'tensorflow.python.ops.rnn_cell_impl' has no attribute 'assert_like_rnncell'` -> On version 1.5.0
Google search didn't helped.

I ran this command:  `sudo python3 train.py`

Log after I run command above:
```
user@SERVER:/mnt/d/tts/tacotron-master$ sudo python3 train.py
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:493: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:494: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:495: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:496: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:497: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:502: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Checkpoint path: ./logs-tacotron/model.ckpt
Loading training data from: ./training/train.txt
Using model: tacotron
Hyperparameters:
  adam_beta1: 0.9
  adam_beta2: 0.999
  attention_depth: 128
  batch_size: 32
  cleaners: english_cleaners
  decay_learning_rate: True
  decoder_depth: 1024
  embed_depth: 512
  encoder_depth: 256
  fmax: 7600
  fmin: 125
  frame_length_ms: 50
  frame_shift_ms: 12.5
  griffin_lim_iters: 60
  initial_learning_rate: 0.001
  max_abs_value: 4
  max_frame_num: 1000
  max_iters: 300
  min_level_db: -100
  num_freq: 1025
  num_mels: 160
  outputs_per_step: 5
  postnet_depth: 512
  power: 1.2
  preemphasis: 0.97
  prenet_depths: [256, 256]
  ref_level_db: 20
  reg_weight: 1e-06
  sample_rate: 24000
  use_cmudict: False
Loaded metadata for 32 examples (0.09 hours)
Traceback (most recent call last):
  File "train.py", line 157, in <module>
    main()
  File "train.py", line 153, in main
    train(log_dir, args)
  File "train.py", line 66, in train
    model.initialize(feeder.inputs, feeder.input_lengths, feeder.mel_targets, feeder.linear_targets, feeder.stop_token_targets, global_step)
  File "/mnt/d/tts/tacotron-master/models/tacotron.py", line 77, in initialize
    CustomDecoder(decoder_cell, helper, decoder_init_state),
  File "/mnt/d/tts/tacotron-master/models/custom_decoder.py", line 46, in __init__
    rnn_cell_impl.assert_like_rnncell(type(cell), cell)
AttributeError: module 'tensorflow.python.ops.rnn_cell_impl' has no attribute 'assert_like_rnncell'
```

**Comment by gadagashwini** [comment]
@nikigre,
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by nikigre** [comment]
Hi!
The code for train process is here: https://github.com/begeekmyfriend/tacotron/blob/master/train.py
I am just wondering is there a problem with WSL and Windows Server 2019? Because similar code worked okay on my laptop running Windows 10 in WSL.

**Comment by gadagashwini** [comment]
@nikigre, I tried only importing the `from tensorflow.python.ops import rnn_cell_impl` with Tensorflow 1.14.0. I could import without any issue. Just to verify did you check with Tf latest version. Thanks

**Comment by nikigre** [comment]
Hi!
Yes, I checked. I checked with versions from 1.2.0 to 1.9.0 and the newest. And above 1.6.0 I get an error about core dumped.

**Comment by jvishnuvardhan** [comment]
This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!
