### ISSUE TITLE
ValueError: Dimensions must be equal, but are 19 and 39 for 'metrics/accuracy/Equal' (op: 'Equal') with input shapes: [?,19], [?,39].

### ISSUE THREAD

**Issue by neicureuil** [tensorflow/tensorflow#32060]
**System information**
- OS Platform and Distribution : Win10
- TensorFlow installed from (source or binary): pip3 install tensorflow==2.0.0-rc0 
- Python version: 3.7

**Describe the current behavior**
I have try to make a chatbot based on a transformer model.
But when I try to train the model, i have an error :
`ValueError: Dimensions must be equal, but are 19 and 39 for 'metrics/accuracy/Equal' (op: 'Equal') with input shapes: [?,19], [?,39].`

The entire error code: 

> PS C:\Users\Neicureuil\Workspace\Python\ChatBot Prototype> py .\train.py
Epoch 1/10
      1/Unknown - 3s 3s/stepTraceback (most recent call last):
  File "C:\Users\Neicureuil\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1610, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimensions must be equal, but are 19 and 39 for 'metrics/accuracy/Equal' (op: 'Equal') with input shapes: [?,19], [?,39].
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File ".\train.py", line 38, in <module>
    chatbot_model.fit(dataset_var, epochs=EPOCHS)
  File "C:\Users\Neicureuil\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 734, in fit
    use_multiprocessing=use_multiprocessing)
  File "C:\Users\Neicureuil\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py", line 324, in fit
    total_epochs=epochs)
  File "C:\Users\Neicureuil\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py", line 123, in run_one_epoch
    batch_outs = execution_function(iterator)
  File "C:\Users\Neicureuil\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\keras\engine\training_v2_utils.py", line 86, in execution_function
    distributed_function(input_fn))
  File "C:\Users\Neicureuil\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\eager\def_function.py", line 427, in __call__
    self._initialize(args, kwds, add_initializers_to=initializer_map)
  File "C:\Users\Neicureuil\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\eager\def_function.py", line 370, in _initialize
    *args, **kwds))
  File "C:\Users\Neicureuil\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\eager\function.py", line 1847, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "C:\Users\Neicureuil\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\eager\function.py", line 2147, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "C:\Users\Neicureuil\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\eager\function.py", line 2038, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "C:\Users\Neicureuil\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\framework\func_graph.py", line 915, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "C:\Users\Neicureuil\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\eager\def_function.py", line 320, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "C:\Users\Neicureuil\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\keras\engine\training_v2_utils.py", line 73, in distributed_function
    per_replica_function, args=(model, x, y, sample_weights))
  File "C:\Users\Neicureuil\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\distribute\distribute_lib.py", line 760, in experimental_run_v2
    return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
  File "C:\Users\Neicureuil\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\distribute\distribute_lib.py", line 1787, in call_for_each_replica
    return self._call_for_each_replica(fn, args, kwargs)
  File "C:\Users\Neicureuil\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\distribute\distribute_lib.py", line 2132, in _call_for_each_replica
    return fn(*args, **kwargs)
  File "C:\Users\Neicureuil\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\autograph\impl\api.py", line 292, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Neicureuil\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\keras\engine\training_v2_utils.py", line 264, in train_on_batch
    output_loss_metrics=model._output_loss_metrics)
  File "C:\Users\Neicureuil\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\keras\engine\training_eager.py", line 315, in train_on_batch
    model, outs, targets, sample_weights=sample_weights, masks=masks)
  File "C:\Users\Neicureuil\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\keras\engine\training_eager.py", line 74, in _eager_metrics_fn
    skip_target_masks=model._prepare_skip_target_masks())
  File "C:\Users\Neicureuil\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 2027, in _handle_metrics
    target, output, output_mask))
  File "C:\Users\Neicureuil\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 1978, in _handle_per_output_metrics
    metric_fn, y_true, y_pred, weights=weights, mask=mask)
  File "C:\Users\Neicureuil\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\keras\engine\training_utils.py", line 1066, in call_metric_function
    return metric_fn(y_true, y_pred, sample_weight=weights)
  File "C:\Users\Neicureuil\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\keras\metrics.py", line 194, in __call__
    replica_local_fn, *args, **kwargs)
  File "C:\Users\Neicureuil\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\keras\distribute\distributed_training_utils.py", line 1135, in call_replica_local_fn
    return fn(*args, **kwargs)
  File "C:\Users\Neicureuil\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\keras\metrics.py", line 177, in replica_local_fn
    update_op = self.update_state(*args, **kwargs)  # pylint: disable=not-callable
  File "C:\Users\Neicureuil\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\keras\utils\metrics_utils.py", line 75, in decorated
    update_op = update_state_fn(*args, **kwargs)
  File "C:\Users\Neicureuil\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\keras\metrics.py", line 582, in update_state
    matches = self._fn(y_true, y_pred, **self._fn_kwargs)
  File "C:\Users\Neicureuil\Workspace\Python\ChatBot Prototype\model.py", line 195, in accuracy
    accuracy_ = tf.metrics.SparseCategoricalAccuracy()(y_true, y_pred)
  File "C:\Users\Neicureuil\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\keras\metrics.py", line 194, in __call__
    replica_local_fn, *args, **kwargs)
  File "C:\Users\Neicureuil\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\keras\distribute\distributed_training_utils.py", line 1135, in call_replica_local_fn
    return fn(*args, **kwargs)
  File "C:\Users\Neicureuil\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\keras\metrics.py", line 177, in replica_local_fn
    update_op = self.update_state(*args, **kwargs)  # pylint: disable=not-callable
  File "C:\Users\Neicureuil\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\keras\utils\metrics_utils.py", line 75, in decorated
    update_op = update_state_fn(*args, **kwargs)
  File "C:\Users\Neicureuil\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\keras\metrics.py", line 582, in update_state
    matches = self._fn(y_true, y_pred, **self._fn_kwargs)
  File "C:\Users\Neicureuil\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\keras\metrics.py", line 2787, in sparse_categorical_accuracy
    return math_ops.cast(math_ops.equal(y_true, y_pred), K.floatx())
  File "C:\Users\Neicureuil\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\ops\gen_math_ops.py", line 3628, in equal
    "Equal", x=x, y=y, name=name)
  File "C:\Users\Neicureuil\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\framework\op_def_library.py", line 793, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\Neicureuil\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\framework\func_graph.py", line 548, in create_op
    compute_device)
  File "C:\Users\Neicureuil\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3429, in _create_op_internal
    op_def=op_def)
  File "C:\Users\Neicureuil\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1773, in __init__
    control_input_ops)
  File "C:\Users\Neicureuil\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1613, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimensions must be equal, but are 19 and 39 for 'metrics/accuracy/Equal' (op: 'Equal') with input shapes: [?,19], [?,39].

**Code to reproduce the issue**
dataset.py: [https://pastebin.com/pTVqZaiG](url)
model.py: [https://pastebin.com/pgnWRhEt](url)
train.py: [https://pastebin.com/FwJK9yDb](url)

**Comment by ravikyram** [comment]
@neicureuil 
I am not able to see the files in the links you have provided.Thanks!

**Comment by neicureuil** [comment]
> 
> 
> @neicureuil
> I am not able to see the files in the links you have provided.Thanks!

Fixed

**Comment by ravikyram** [comment]
I am getting the below error while trying to reproduce the issue.

`FileNotFoundError: [Errno 2] No such file or directory: './dataset.txt'`.

Can you please provide the `dataset.txt` file (or dummy data, if your data is confidential) so we can reproduce the issue and try for the resolution. Thanks!
