### ISSUE TITLE
Difference in graphdef binary between training and serving for tf.nn.embedding_lookup

### ISSUE THREAD

**Issue by CRSilkworth** [tensorflow/tensorflow#32066]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): custom code
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
NAME="Linux Mint"
VERSION="18 (Sarah)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 18"
VERSION_ID="18"
HOME_URL="http://www.linuxmint.com/"
SUPPORT_URL="http://forums.linuxmint.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/linuxmint/"
UBUNTU_CODENAME=xenial

- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): ('v1.14.0-rc1-22-gaf24dc91b5', '1.14.0')
- Python version: 2.7.12
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: V10.0.130/ v7.5.0
- GPU model and memory: GeForce GTX 1060 (x2) each with 6070MiB.

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
When trying to use tf.nn.embedding_lookup during a typical training workflow, everything seems to work fine. However when using the same code with the same tensorflow version/ tensorflow api version, etc. while trying to serve the model an error is thrown. The error seems to point to a mismatch in the way embedding_lookup was defined in tensorflow serving. One is expecting a batch_dims argument for gather_v2 while the other believes this is an invalid argument.

**Describe the expected behavior**
It's expected that, assuming the pasted code is correct that the predict() function should result in same output as the train() output. However, running predict() throws the error above. I have tested this on both tensorflow==1.14.0 and tensorflow-gpu==1.14.0 both with tensorflow-serving-api==1.14.0
**Code to reproduce the issue**

Running this works as expected. Prints out the result of sess.run and exports the 'model'
```python
import numpy as np
import tensorflow as tf
import os
import subprocess as sp
import grpc
from tensorflow_serving.apis import prediction_service_pb2_grpc
from tensorflow_serving.apis import predict_pb2

np.random.seed(0)


def model(indices):
  embeddings = tf.constant(np.random.rand(4, 5))
  embedding_vectors = tf.nn.embedding_lookup(
    embeddings,
    indices
  )
  weights = tf.constant(np.random.rand(5, 2))
  preds = tf.nn.softmax(tf.matmul(embedding_vectors, weights))
  return preds


def train():
  graph = tf.Graph()
  with graph.as_default():

    preds = model(tf.constant([0, 2, 1], dtype=tf.int32))

  with tf.Session(graph=graph) as sess:
    print sess.run(preds)


def export():
  graph = tf.Graph()
  with graph.as_default():

    ph = tf.placeholder(shape=[None], dtype=tf.int32)
    preds = model(ph)

  with tf.Session(graph=graph) as sess:
    inputs = {'input': tf.saved_model.utils.build_tensor_info(ph)}
    outputs = {'output': tf.saved_model.utils.build_tensor_info(preds)}
    signature = (
        tf.saved_model.signature_def_utils.build_signature_def(
            inputs=inputs,
            outputs=outputs,
            method_name="tensorflow/serving/classify"
        )
    )

    export_file_path = os.path.join('temp_export', '1')
    builder = tf.saved_model.builder.SavedModelBuilder(export_file_path)
    builder.add_meta_graph_and_variables(
        sess,
        [tf.saved_model.tag_constants.SERVING],
        signature_def_map={tf.saved_model.signature_constants.DEFAULT_SERVING_SIGNATURE_DEF_KEY: signature}
    )

    builder.save()

if __name__ == "__main__":
  train()
  export()
```

This is the complete output:
```
WARNING:tensorflow:From temp.py:29: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

2019-08-28 21:27:01.534749: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2100070000 Hz
2019-08-28 21:27:01.539551: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x3d285e0 executing computations on platform Host. Devices:
2019-08-28 21:27:01.539602: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
2019-08-28 21:27:01.550924: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1412] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set.  If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.
[[0.30251842 0.69748158]
 [0.2578716  0.7421284 ]
 [0.22793843 0.77206157]]
WARNING:tensorflow:From temp.py:37: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING:tensorflow:From temp.py:41: build_tensor_info (from tensorflow.python.saved_model.utils_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.utils.build_tensor_info or tf.compat.v1.saved_model.build_tensor_info.
WARNING:tensorflow:From temp.py:44: The name tf.saved_model.signature_def_utils.build_signature_def is deprecated. Please use tf.compat.v1.saved_model.signature_def_utils.build_signature_def instead.

WARNING:tensorflow:From temp.py:52: The name tf.saved_model.builder.SavedModelBuilder is deprecated. Please use tf.compat.v1.saved_model.builder.SavedModelBuilder instead.

WARNING:tensorflow:From temp.py:55: The name tf.saved_model.tag_constants.SERVING is deprecated. Please use tf.saved_model.SERVING instead.

WARNING:tensorflow:From temp.py:56: The name tf.saved_model.signature_constants.DEFAULT_SERVING_SIGNATURE_DEF_KEY is deprecated. Please use tf.saved_model.DEFAULT_SERVING_SIGNATURE_DEF_KEY instead.
```

The model is then served using docker via the command:
```
docker run -p 8505:8500 --mount type=bind,source=$(pwd)/temp_export,target=/models/temp_model -e MODEL_NAME=temp_model -t tensorflow/serving
```
This is the output of running the docker command:
```
2019-08-29 01:27:32.994250: I tensorflow_serving/model_servers/server.cc:82] Building single TensorFlow model file config:  model_name: temp_model model_base_path: /models/temp_model
2019-08-29 01:27:32.994514: I tensorflow_serving/model_servers/server_core.cc:461] Adding/updating models.
2019-08-29 01:27:32.994538: I tensorflow_serving/model_servers/server_core.cc:558]  (Re-)adding model: temp_model
2019-08-29 01:27:33.094892: I tensorflow_serving/core/basic_manager.cc:739] Successfully reserved resources to load servable {name: temp_model version: 1}
2019-08-29 01:27:33.094934: I tensorflow_serving/core/loader_harness.cc:66] Approving load for servable version {name: temp_model version: 1}
2019-08-29 01:27:33.094951: I tensorflow_serving/core/loader_harness.cc:74] Loading servable version {name: temp_model version: 1}
2019-08-29 01:27:33.094976: I external/org_tensorflow/tensorflow/contrib/session_bundle/bundle_shim.cc:363] Attempting to load native SavedModelBundle in bundle-shim from: /models/temp_model/1
2019-08-29 01:27:33.094991: I external/org_tensorflow/tensorflow/cc/saved_model/reader.cc:31] Reading SavedModel from: /models/temp_model/1
2019-08-29 01:27:33.095225: I external/org_tensorflow/tensorflow/cc/saved_model/reader.cc:54] Reading meta graph with tags { serve }
2019-08-29 01:27:33.117391: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:182] Restoring SavedModel bundle.
2019-08-29 01:27:33.117456: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:192] The specified SavedModel has no variables; no checkpoints were restored. File does not exist: /models/temp_model/1/variables/variables.index
2019-08-29 01:27:33.117481: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:285] SavedModel load for tags { serve }; Status: success. Took 22482 microseconds.
2019-08-29 01:27:33.117517: I tensorflow_serving/servables/tensorflow/saved_model_warmup.cc:101] No warmup data file found at /models/temp_model/1/assets.extra/tf_serving_warmup_requests
2019-08-29 01:27:33.117615: I tensorflow_serving/core/loader_harness.cc:86] Successfully loaded servable version {name: temp_model version: 1}
2019-08-29 01:27:33.130660: I tensorflow_serving/model_servers/server.cc:313] Running gRPC ModelServer at 0.0.0.0:8500 ...
[warn] getaddrinfo: address family for nodename not supported
2019-08-29 01:27:33.135024: I tensorflow_serving/model_servers/server.cc:333] Exporting HTTP/REST API at:localhost:8501 ...
[evhttp_server.cc : 237] RAW: Entering the event loop ...
```

However when this is run:
```python
import numpy as np
import tensorflow as tf
import os
import subprocess as sp
import grpc
from tensorflow_serving.apis import prediction_service_pb2_grpc
from tensorflow_serving.apis import predict_pb2

def predict():
  channel = grpc.insecure_channel('localhost:8505')
  stub = prediction_service_pb2_grpc.PredictionServiceStub(channel)

  request = predict_pb2.PredictRequest()
  request.model_spec.name = 'temp_model'
  request.model_spec.signature_name = tf.saved_model.signature_constants.DEFAULT_SERVING_SIGNATURE_DEF_KEY

  request.inputs['input'].CopyFrom(
    tf.make_tensor_proto([0, 2, 1])
  )

  response = stub.Predict(request)

  print response.outputs


if __name__ == "__main__":
  predict()
```

This error is thrown:
```
WARNING:tensorflow:From temp.py:68: The name tf.saved_model.signature_constants.DEFAULT_SERVING_SIGNATURE_DEF_KEY is deprecated. Please use tf.saved_model.DEFAULT_SERVING_SIGNATURE_DEF_KEY instead.

WARNING:tensorflow:From temp.py:71: The name tf.make_tensor_proto is deprecated. Please use tf.compat.v1.make_tensor_proto instead.

2019-08-29 01:28:35.360196: E external/org_tensorflow/tensorflow/core/common_runtime/executor.cc:624] Executor failed to create kernel. Invalid argument: NodeDef mentions attr 'batch_dims' not in Op<name=GatherV2; signature=params:Tparams, indices:Tindices, axis:Taxis -> output:Tparams; attr=Tparams:type; attr=Tindices:type,allowed=[DT_INT32, DT_INT64]; attr=Taxis:type,allowed=[DT_INT32, DT_INT64]>; NodeDef: {{node embedding_lookup}}. (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
	 [[{{node embedding_lookup}}]]
Traceback (most recent call last):
  File "temp.py", line 82, in <module>
    predict()
  File "temp.py", line 74, in predict
    response = stub.Predict(request)
  File "/home/crsilkworth/temp/venv/local/lib/python2.7/site-packages/grpc/_channel.py", line 565, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/crsilkworth/temp/venv/local/lib/python2.7/site-packages/grpc/_channel.py", line 467, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.INVALID_ARGUMENT
	details = "NodeDef mentions attr 'batch_dims' not in Op<name=GatherV2; signature=params:Tparams, indices:Tindices, axis:Taxis -> output:Tparams; attr=Tparams:type; attr=Tindices:type,allowed=[DT_INT32, DT_INT64]; attr=Taxis:type,allowed=[DT_INT32, DT_INT64]>; NodeDef: {{node embedding_lookup}}. (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
	 [[{{node embedding_lookup}}]]"
	debug_error_string = "{"created":"@1567042115.360651073","description":"Error received from peer ipv4:127.0.0.1:8505","file":"src/core/lib/surface/call.cc","file_line":1052,"grpc_message":"NodeDef mentions attr 'batch_dims' not in Op<name=GatherV2; signature=params:Tparams, indices:Tindices, axis:Taxis -> output:Tparams; attr=Tparams:type; attr=Tindices:type,allowed=[DT_INT32, DT_INT64]; attr=Taxis:type,allowed=[DT_INT32, DT_INT64]>; NodeDef: {{node embedding_lookup}}. (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).\n\t [[{{node embedding_lookup}}]]","grpc_status":3}"
```

**Other info / logs**
result of pip freeze -l:
```
absl-py==0.8.0
astor==0.8.0
backports.weakref==1.0.post1
enum34==1.1.6
funcsigs==1.0.2
futures==3.3.0
gast==0.2.2
google-pasta==0.1.7
grpcio==1.23.0
h5py==2.9.0
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
Markdown==3.1.1
mock==3.0.5
numpy==1.16.5
protobuf==3.9.1
six==1.12.0
tensorboard==1.14.0
tensorflow==1.14.0
tensorflow-estimator==1.14.0
tensorflow-serving-api==1.14.0
termcolor==1.1.0
Werkzeug==0.15.5
wrapt==1.11.2
```

**Comment by gadagashwini** [comment]
@CRSilkworth, 
This is more related to Tf serving Repo. Please post this issue in [Tf serving repo](https://github.com/tensorflow/serving/issues). Thanks!

**Comment by CRSilkworth** [comment]
ok, posted in tensorflow serving.

**Comment by gadagashwini** [comment]
@CRSilkworth, Thanks, Will close the issue here.
