### ISSUE TITLE
Initial read on nonexistent tf.gfile.GFile in w+ mode crashes

### ISSUE THREAD

**Issue by eirism** [tensorflow/tensorflow#32090]
**System information**
- Have I written custom code: Yes
- OS Platform and Distribution: Linux Ubuntu 18.04
- TensorFlow installed from: binary
- TensorFlow version: v1.14.0-rc1-22-gaf24dc9 1.14.0
- Python version: 3.7

**Describe the current behavior**
Python raises `tensorflow.python.framework.errors_impl.NotFoundError` when doing a first read (no writes before it) on a nonexistent `tf.gfile.GFile` in `w+` mode.

**Describe the expected behavior**
Read on an empty `w+` file should return an empty string.
One problem with the current behaviour is that numpy.savez() crashes when writing to a GFile.

**Code to reproduce the issue**
```
import tensorflow as tf

with tf.io.gfile.GFile('test.txt', 'w+') as f:
    f.read()
```

**Other info / logs**
```
Traceback (most recent call last):
  File "test_gfile.py", line 5, in <module>
    f.read()
  File "/VENV/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py", line 122, in read
    self._preread_check()
  File "/VENV/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py", line 84, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512)
tensorflow.python.framework.errors_impl.NotFoundError: test.txt; No such file or directory
```

**Comment by ravikyram** [comment]
`test.txt` is not in your current working directory. Please, make sure `test.txt` and `your python-file/jupyter-notebook` are in same directory.Thanks!

**Comment by eirism** [comment]
I expect that the `w` mode (and `w+`, `w+b`) should have similar semantics to Python `open`, where `w` means [truncate the file first](https://docs.python.org/3/library/functions.html#open).

Since this isn't the case it breaks things like `numpy.savez()`.

Workarounds are to either write something, e.g. `""`, to the file before reading so that the file is created, or manually create the file first as you suggest. But those are workarounds to a problem that I think should be solved in GFile.

**Comment by mihaimaruseac** [comment]
This happens on both nightly and 2.0.

As I'm working on [modularizing filesystem support](https://github.com/tensorflow/community/blob/master/rfcs/20190506-filesystem-plugin-modular-tensorflow.md), I'm assigning this to me, although it will take a while until I can get to the python side of things.

In the end, the expected behavior should be similar to Python's:

```python
>>> with open('this_file_does_not_exist_at_all', 'w+') as f: f.read()
... 
''
```

**Comment by eirism** [comment]
Related to the fact that GFile does not truncate files the same way as Python, reading an existing file opened with `w+` will return the text in the file instead of `""`.

Example:
```
import tensorflow as tf

with open('existing.txt', 'w') as f:
    f.write('txt')
    f.flush()

with tf.io.gfile.GFile('existing.txt', 'w+') as f:
    print(f.read())  # Prints txt, should print ""
```

**Comment by mihaimaruseac** [comment]
I'll have to handle that too, thanks for pointing it out

**Comment by eirism** [comment]
`f.seek()` also crashes in the same way as `f.read()`.

**Comment by lminer** [comment]
Any update on this? I'm running into this error trying to write to s3 with gfile and pysoundfile

**Comment by lgeiger** [comment]
@mihaimaruseac Any updates on this? This still seems to be an issue with TF 2.5 and prevent's the use of `GFile` together with `np.savez`.

**Comment by sanatmpa1** [comment]
issue still exists in `2.6.0` and `nightly`. Here's the [gist](https://colab.research.google.com/gist/sanatmpa1/985a559b4ff8e165576f2803457ad8d1/32090.ipynb#scrollTo=hRPeuchG--s3). Thanks!

**Comment by mihaimaruseac** [comment]
Problem is the modularization effort stalled since members left the team last year.

We onboarded new members recently, so we should pick up these items again. Apologies for the delays.

**Comment by cnsgsz** [comment]
a similar approach.
```
io_buffer = io.BytesIO()
np.savez(io_buffer, ...)
with gfile.Open(path, "wb") as f:
  f.write(io_buffer.getvalue())
```

**Comment by chunduriv** [comment]
I was able to replicate the issue in tf-nightly 2.10.0-dev20220719. Please find the [gist](https://colab.sandbox.google.com/gist/chunduriv/7d3acc444e57e5bdd90e262d3f98e868/32090.ipynb) for reference. Thank you.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.

**Comment by mihaimaruseac** [comment]
@tilakrayal , please try the code instead of just saying "he code/debug information for this issue may not be relevant with the current state of the code base."

Also, please don't ask people to do busy work to open a new issue when the current one is still relevant and has all the needed information. Opening  anew issue just loses context.

**Comment by Venkat6871** [comment]
Hi @eirism ,
Thank you so much for filing this bug request! We truly appreciate your support. At the moment, this request is not prioritized and mark it for community contributions. If you would like to contribute on a fix, please feel free to fork the repository and submit a pull request in accordance with the TensorFlow [CONTRIBUTION GUIDELINES](https://www.tensorflow.org/community/contribute/code) and link this issue in your PR to ensure the maintainers can easily review and collaborate.To avoid duplicate work, please leave a comment here if you decide to take it on!
Thank you again for your interest and we look forward to seeing your contributions!

**Comment by Venkat6871** [comment]
Hi @eirism ,
We are closing this issue due to inactivity. If this is still relevant and you would like to work on it, please feel free to reopen the issue or submit a pull request referencing it.

Thank you for your understanding.
