### ISSUE TITLE
Cannot use "sample_weight" in tf.data.Dataset along with a tf.keras model with customized loss

### ISSUE THREAD

**Issue by tiandeyu-github** [tensorflow/tensorflow#32119]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): **Yes**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Windows 10**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): **binary**
- TensorFlow version (use command below): **unknown 1.14.0**
- Python version: **3.7.3**
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**
If a tf.keras.models.Model uses customized loss added to the model by model.add_loss(loss), and  a tf.data.Dataset dataset which yields tuples (x, y, sample_weight) is used in model.fit(dataset), a TypeError will be raised.

**Describe the expected behavior**
The model should be trained normally.

**Code to reproduce the issue**
```python
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.layers import Input, Dense
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam

inputs = Input(shape = [1], dtype = tf.float32)
labels = Input(shape = [1], dtype = tf.float32)
outputs = Dense(1, use_bias = True, activation = None)(inputs)

model = Model([inputs, labels], outputs)
loss = tf.square(labels - outputs)
model.add_loss(loss)

model.compile(Adam(0.1))

rg = tf.data.Dataset.range(128)
rg = rg.map(lambda x: tf.cast(x, tf.float32))

'''
# This snippet works fine
ds2 = rg.map(lambda x: ((x, 2*x+1), 0))
ds2 = ds2.batch(16)
model.fit(ds2, epochs = 50)
print(model.predict(([-32], [0])))
'''

# This snippet causes exception
ds3 = rg.map(lambda x: ((x, 2*x+1), 0, 1))
ds3 = ds3.batch(16)
model.fit(ds3, epochs = 50)
```

**Other info / logs**
I encounter the problem in a real-world model. I omit the original model and give a simple model here. It is awkward; but it reproduces the bug in a few lines.

Here is the traceback:
```
C:\fakepath\Python37\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) o
r '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,
)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\fakepath\Python37\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) o
r '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,
)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\fakepath\Python37\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) o
r '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,
)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\fakepath\Python37\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type, 1) o
r '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,
)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\fakepath\Python37\lib\site-packages\tensorflow\python\framework\dtypes.py:520: FutureWarning: Passing (type, 1) o
r '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,
)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\fakepath\Python37\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) o
r '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,
)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
C:\fakepath\Python37\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:541: FutureWarning: Passing (typ
e, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,))
 / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\fakepath\Python37\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:542: FutureWarning: Passing (typ
e, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,))
 / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\fakepath\Python37\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:543: FutureWarning: Passing (typ
e, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,))
 / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\fakepath\Python37\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:544: FutureWarning: Passing (typ
e, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,))
 / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\fakepath\Python37\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:545: FutureWarning: Passing (typ
e, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,))
 / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\fakepath\Python37\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:550: FutureWarning: Passing (typ
e, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,))
 / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
WARNING:tensorflow:From C:\fakepath\Python37\lib\site-packages\tensorflow\python\ops\init_ops.py:1251: calling Varia
nceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future versi
on.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
WARNING:tensorflow:Output dense missing from loss dictionary. We assume this was done on purpose. The fit and evaluate A
PIs will not be expecting any data to be passed to dense.
WARNING:tensorflow:Expected a shuffled dataset but input dataset `x` is not shuffled. Please invoke `shuffle()` on input
 dataset.
2019-08-30 23:01:30.110552: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that thi
s TensorFlow binary was not compiled to use: AVX2
Traceback (most recent call last):
  File "main.py", line 31, in <module>
    model.fit(ds3, epochs = 50)
  File "C:\fakepath\Python37\lib\site-packages\tensorflow\python\keras\engine\training.py", line 780, in fit
    steps_name='steps_per_epoch')
  File "C:\fakepath\Python37\lib\site-packages\tensorflow\python\keras\engine\training_arrays.py", line 174, in mode
l_iteration
    ins = _prepare_feed_values(model, inputs, targets, sample_weights, mode)
  File "C:\fakepath\Python37\lib\site-packages\tensorflow\python\keras\engine\training_arrays.py", line 501, in _pre
pare_feed_values
    extract_tensors_from_dataset=True)
  File "C:\fakepath\Python37\lib\site-packages\tensorflow\python\keras\engine\training.py", line 2678, in _standardi
ze_user_data
    sample_weight, feed_output_names)
  File "C:\fakepath\Python37\lib\site-packages\tensorflow\python\keras\engine\training_utils.py", line 441, in stand
ardize_sample_weights
    'sample_weight')
  File "C:\fakepath\Python37\lib\site-packages\tensorflow\python\keras\engine\training_utils.py", line 431, in stand
ardize_sample_or_class_weights
    str(x_weight))
TypeError: The model has multiple outputs, so `sample_weight` should be either a list or a dict. Provided `sample_weight
` type not understood: Tensor("IteratorGetNext:3", shape=(?,), dtype=int32)
```

**Comment by gowthamkpr** [comment]
@tiandeyu-github The model doesn't accept multiple outputs. So, you have to use a list or dictionary. Make the small change as below and it works..!!

# This snippet causes exception
ds3 = rg.map(lambda x: ((x, 2*x+1), [0, 1]))
ds3 = ds3.batch(16)
model.fit(ds3, epochs = 50)

**Comment by tiandeyu-github** [comment]
@gowthamkpr Thanks for your reply.

In my opinion, the dataset used in model.fit(dataset) should generate tuples like (input, target, sample_weight), so in my code, the dataset generates tuples like ((x, 2\*x+1), 0, 1), where (x, 2\*x+1) is the input (i.e. "x" is the input for "inputs", "2\*x+1" is the input for "labels"), and 0 is the target (it is a placeholder here, because the model uses a cuotomized loss and do not need the target output), and 1 is the sample_weight. In your code, the dataset generate tuples like ((x, 2\*x+1), [0, 1]), which does not have a "sample_weight" field, and contains it in the "target" field. Now I think model.fit() will interpret the whole [0, 1] as the target and ignore it, which are not the behavior desired by us.

Here is some code to show the problem:
```python
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.layers import Input, Dense
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam

inputs = Input(shape = [1], dtype = tf.float32)
labels = Input(shape = [1], dtype = tf.float32)
outputs = Dense(1, use_bias = True, activation = None)(inputs)

model = Model([inputs, labels], outputs)
loss = tf.square(labels - outputs)
model.add_loss(loss)

model.compile(Adam(0.1))

rise = tf.data.Dataset.range(60)
rise = rise.map(lambda x: tf.cast(x, tf.float32))
rise = rise.map(lambda x: ((x, x), [0, 1]))

fall = tf.data.Dataset.range(4)
fall = fall.map(lambda x: tf.cast(x, tf.float32))
fall = fall.map(lambda x: ((x, -x), [0, 9999999]))

ds = rise.concatenate(fall)
ds = ds.batch(16)

model.fit(ds, epochs = 50)
p = model.predict(([-100], [0]))
print(p) # p is around [[-100]], which means that y=x is acturally learned.
```

By the way, in the above code, if you add ```tf.enable_eager_execution()``` at first, the model.fit() will raise an error:
```
C:\fakepath\Python37\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\fakepath\Python37\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\fakepath\Python37\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\fakepath\Python37\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\fakepath\Python37\lib\site-packages\tensorflow\python\framework\dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\fakepath\Python37\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
C:\fakepath\Python37\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\fakepath\Python37\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\fakepath\Python37\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\fakepath\Python37\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\fakepath\Python37\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\fakepath\Python37\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
WARNING:tensorflow:From tf_sample_weight_custom_loss.py:43: The name tf.enable_eager_execution is deprecated. Please use tf.compat.v1.enable_eager_execution instead.

2019-08-31 10:02:55.084110: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
WARNING:tensorflow:Output dense missing from loss dictionary. We assume this was done on purpose. The fit and evaluate APIs will not be expecting any data to be passed to dense.
WARNING:tensorflow:Expected a shuffled dataset but input dataset `x` is not shuffled. Please invoke `shuffle()` on input dataset.
Epoch 1/50
Traceback (most recent call last):
  File "main.py", line 65, in <module>
    model.fit(ds, epochs = 50)
  File "C:\fakepath\Python37\lib\site-packages\tensorflow\python\keras\engine\training.py", line 694, in fit
    initial_epoch=initial_epoch)
  File "C:\fakepath\Python37\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1433, in fit_generator
    steps_name='steps_per_epoch')
  File "C:\fakepath\Python37\lib\site-packages\tensorflow\python\keras\engine\training_generator.py", line 264, in model_iteration
    batch_outs = batch_function(*batch_data)
  File "C:\fakepath\Python37\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1153, in train_on_batch
    extract_tensors_from_dataset=True)
  File "C:\fakepath\Python37\lib\site-packages\tensorflow\python\keras\engine\training.py", line 2673, in _standardize_user_data
    exception_prefix='target')
  File "C:\fakepath\Python37\lib\site-packages\tensorflow\python\keras\engine\training_utils.py", line 305, in standardize_input_data
    'expected no data, but got:', data)
ValueError: ('Error when checking model target: expected no data, but got:', <tf.Tensor: id=95, shape=(16, 2), dtype=int32, numpy=
array([[0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1]])>)
```

**Comment by gowthamkpr** [comment]
@tiandeyu-github Are you still facing with the same issue or did you solve it?
