### ISSUE TITLE
ImportError: cannot import name 'dense_features' from 'tensorflow.python.feature_column'

### ISSUE THREAD

**Issue by aiwalter** [tensorflow/tensorflow#32111]
```
from tensorflow.python.feature_column import dense_features
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'dense_features' from 'tensorflow.python.feature_column'
```

tensorflow==1.14.0
Python==3.7.3

What is the issue in this case?

**Comment by SmoothJL** [comment]
I have the same issue with tensorflow 1.14.0, and trying to run a returnn config file

**Comment by oanush** [comment]
I am able to replicate the issue in [TF-1.14](https://colab.research.google.com/gist/oanush/959d6b296f0966051f69cb29c37b1769/32111.ipynb) also issue not replicating in [TF-Nightly](https://colab.research.google.com/gist/oanush/959d6b296f0966051f69cb29c37b1769/32111.ipynb).Thanks!

**Comment by aiwalter** [comment]
@oanush could you pls link the TF-Nightly colab  again correctly? :)

**Comment by mihaimaruseac** [comment]
Just to check, what versions of tensorflow and tensorflow_estimator are being used?

**Comment by jvishnuvardhan** [comment]
@aiwalter `Dense_feature` is not there in the TF1.14 repository.  You can check the `feature_column` folder [here](https://github.com/tensorflow/tensorflow/tree/release_1.14.0/tensorflow/python/feature_column).

I could import the `dense_features` without any issues using `tf-nightly` and `TF2.0rc0`. Here is the [gist](https://colab.sandbox.google.com/gist/jvishnuvardhan/a245978bea0a4eb8b36bf13d99a8f735/tfnightly_32111.ipynb) with `TF1.14`. [Here](https://colab.sandbox.google.com/gist/jvishnuvardhan/facb1ceb19dee592691a98060fba65de/tf20_32111.ipynb) is the gist with TF2.0. 

Did you see this with any TensorFlow tutorials on TF website? Thanks!

**Comment by NancyLele** [comment]
@aiwalter 
i have met the same question. Do you resovle it?

**Comment by NancyLele** [comment]
@mihaimaruseac 
python 3.6
tensorflow is 1.14.0
tensorflow.estimator is 1.14.0

And I have met the same problem.In morning ,my program can run.But now it not. I want to know reason

**Comment by NancyLele** [comment]
@aiwalter 
I resovle the problem.
Reinstall tensorflow  and tensorflow estimator

**Comment by aiwalter** [comment]
@NancyLele thx, it works now for me as well, however Ia am wondering because its the same tf and tf estimator version still
@jvishnuvardhan no, everything fine. I got this issue via `deeppavlov`

**Comment by mihaimaruseac** [comment]
Do you use nightly?

**Comment by iMSannob** [comment]
Fixed this issue by reinstall tensorflow_estimator:
sudo -H pip3 uninstall  tensorflow_estimator
sudo -H pip3 install  tensorflow_estimator

**Comment by Arithmeticjia** [comment]
> Fixed this issue by reinstall tensorflow_estimator:
> sudo -H pip3 uninstall tensorflow_estimator
> sudo -H pip3 install tensorflow_estimator

thx!

**Comment by jvishnuvardhan** [comment]
Automatically closing this out since I understand it to be resolved, but please let me know if I'm mistaken.Thanks!

**Comment by Arjuna197** [comment]
I hit this same issue with tf-nightly-gpu (tb-nightly-1.15.0a20190911, tf-nightly-gpu-1.15.0.dev20190730,  tf-estimator-nightly-1.14.0.dev2019092301) Also tried with tensorflow_estimator 2.0, same error.

>   File "/vol0/dan/tfn/lib/python3.6/site-packages/tensorflow_core/contrib/__init__.py", line 39, in <module>
    from tensorflow.contrib import compiler
  File "/vol0/dan/tfn/lib/python3.6/site-packages/tensorflow_core/contrib/compiler/__init__.py", line 21, in <module>
    from tensorflow.contrib.compiler import jit
  File "/vol0/dan/tfn/lib/python3.6/site-packages/tensorflow_core/contrib/compiler/__init__.py", line 22, in <module>
    from tensorflow.contrib.compiler import xla
  File "/vol0/dan/tfn/lib/python3.6/site-packages/tensorflow_core/contrib/compiler/xla.py", line 22, in <module>
    from tensorflow.python.estimator import model_fn as model_fn_lib
  File "/vol0/dan/tfn/lib/python3.6/site-packages/tensorflow_core/python/estimator/model_fn.py", line 26, in <module>
    from tensorflow_estimator.python.estimator import model_fn
  File "/vol0/dan/tfn/lib/python3.6/site-packages/tensorflow_estimator/__init__.py", line 10, in <module>
    from tensorflow_estimator._api.v1 import estimator
  File "/vol0/dan/tfn/lib/python3.6/site-packages/tensorflow_estimator/_api/v1/estimator/__init__.py", line 10, in <module>
    from tensorflow_estimator._api.v1.estimator import experimental
  File "/vol0/dan/tfn/lib/python3.6/site-packages/tensorflow_estimator/_api/v1/estimator/experimental/__init__.py", line 10, in <module>
    from tensorflow_estimator.python.estimator.canned.dnn import dnn_logit_fn_builder
  File "/vol0/dan/tfn/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/canned/dnn.py", line 23, in <module>
    from tensorflow.python.feature_column import dense_features
ImportError: cannot import name 'dense_features'

**Comment by mihaimaruseac** [comment]
That is because tf-nightly has been frozen at 9/11 whereas estimator nightly hasn't.

You can also use the 2.0 nightly preview instead, the 2.0 release candidate, or the 1.15 candidate.

Once 2.0 is fully released, nightlies will be unfrozen again.

**Comment by kvtheckrock** [comment]
I hit this issue with tf_1.14 and 1.15. And also tried this with tf_estimater 2.0. Tried reinstalling tensorflow too. But still could not resolve this issue.

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

Traceback (most recent call last):
  File "/home/vipin/.local/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3319, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-55-3e782cef657a>", line 4, in <module>
    from alexnet import AlexNet
  File "/home/vipin/Downloads/MT2019005/alexnet.py", line 2, in <module>
    import tensorflow as tf
  File "/home/vipin/.local/lib/python3.6/site-packages/tensorflow/__init__.py", line 99, in <module>
    from tensorflow_core import *
  File "/home/vipin/.local/lib/python3.6/site-packages/tensorflow_core/__init__.py", line 106, in <module>
    from tensorflow.python.data.ops.optional_ops import OptionalSpec
ImportError: cannot import name 'OptionalSpec'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vipin/.local/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2034, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'ImportError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vipin/.local/lib/python3.6/site-packages/IPython/core/ultratb.py", line 1151, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "/home/vipin/.local/lib/python3.6/site-packages/IPython/core/ultratb.py", line 319, in wrapped
    return f(*args, **kwargs)
  File "/home/vipin/.local/lib/python3.6/site-packages/IPython/core/ultratb.py", line 353, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "/usr/lib/python3.6/inspect.py", line 1490, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
  File "/usr/lib/python3.6/inspect.py", line 1448, in getframeinfo
    filename = getsourcefile(frame) or getfile(frame)
  File "/usr/lib/python3.6/inspect.py", line 696, in getsourcefile
    if getattr(getmodule(object, filename), '__loader__', None) is not None:
  File "/usr/lib/python3.6/inspect.py", line 733, in getmodule
    if ismodule(module) and hasattr(module, '__file__'):
  File "/home/vipin/.local/lib/python3.6/site-packages/tensorflow/__init__.py", line 50, in __getattr__
    module = self._load()
  File "/home/vipin/.local/lib/python3.6/site-packages/tensorflow/__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/vipin/.local/lib/python3.6/site-packages/tensorflow_core/__init__.py", line 106, in <module>
    from tensorflow.python.data.ops.optional_ops import OptionalSpec
ImportError: cannot import name 'OptionalSpec'

**Comment by mihaimaruseac** [comment]
@kvtheckrock `pip list` should display all packages from the ecosystem at the same version and not mixing nightly and releases. Please open a new issue if that is the case and you still have issues, and please fill in the issue template.

**Comment by rounit57** [comment]
ImportError                               Traceback (most recent call last)
<ipython-input-27-ff7d7ce981e2> in <module>
----> 1 from keras.models import load_model
      2 
      3 
      4 
      5 lbl=['Close','Open']

c:\users\hp\appdata\local\programs\python\python37\lib\site-packages\keras\__init__.py in <module>
      1 from __future__ import absolute_import
      2 
----> 3 from . import utils
      4 from . import activations
      5 from . import applications

c:\users\hp\appdata\local\programs\python\python37\lib\site-packages\keras\utils\__init__.py in <module>
      4 from . import data_utils
      5 from . import io_utils
----> 6 from . import conv_utils
      7 
      8 # Globally-importable utils.

c:\users\hp\appdata\local\programs\python\python37\lib\site-packages\keras\utils\conv_utils.py in <module>
      7 from six.moves import range
      8 import numpy as np
----> 9 from .. import backend as K
     10 
     11 

c:\users\hp\appdata\local\programs\python\python37\lib\site-packages\keras\backend\__init__.py in <module>
     85 elif _BACKEND == 'tensorflow':
     86     sys.stderr.write('Using TensorFlow backend.\n')
---> 87     from .tensorflow_backend import *
     88 else:
     89     # Try and load external backend.

c:\users\hp\appdata\local\programs\python\python37\lib\site-packages\keras\backend\tensorflow_backend.py in <module>
      4 
      5 import tensorflow as tf
----> 6 from tensorflow.python.framework import ops as tf_ops
      7 from tensorflow.python.training import moving_averages
      8 from tensorflow.python.ops import tensor_array_ops

ImportError: cannot import name 'ops' from 'tensorflow.python.framework' (unknown location)



can any one help me out?

**Comment by mihaimaruseac** [comment]
Please open new issue and fill in issue template
