### ISSUE TITLE
Cannot seek on write only tf.gfile.GFile

### ISSUE THREAD

**Issue by eirism** [tensorflow/tensorflow#32122]
**System information**

-  Have I written custom code: Yes
- OS Platform and Distribution: Linux Ubuntu 18.04
- TensorFlow installed from: binary
- TensorFlow version: v1.14.0-rc1-22-gaf24dc9 1.14.0
- Python version: 3.6

**Describe the current behavior**
Calling `seek()` on a `tf.gfile.GFile` opened in write only mode raises `tensorflow.python.framework.errors_impl.PermissionDeniedError`.

**Describe the expected behavior**
GFile should support the Python IO semantics that supports seeking on a write only file.

More generally it would be preferable if GFile followed the API of Python's [`io.IOBase`](https://docs.python.org/3/library/io.html#io.IOBase).

**Code to reproduce the issue**

```
import tensorflow as tf

with tf.io.gfile.GFile('test.txt', 'w') as f:
    f.seek(0)
```

**Other info / logs**
```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/VENV/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/VENV/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 146, in seek
    self._preread_check()
  File "/VENV/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 82, in _preread_check
    "File isn't open for reading")
tensorflow.python.framework.errors_impl.PermissionDeniedError: File isn't open for reading
```

**Comment by mihaimaruseac** [comment]
Related to #32090, right?

**Comment by eirism** [comment]
It is at least related in the sense that GFile does not behave as normal Python file like objects.

This specific bug seems to be caused by an assumption that only readable files can be seeked.
It seems that `tell()` had the same behaviour until [this commit](https://github.com/tensorflow/tensorflow/commit/3cee532afd32c2db28e9359765d88ad5f1567f5f).

**Comment by mihaimaruseac** [comment]
Well, yes, the API is incomplete.

My work on modular filesystems will first separate all filesystems into DSOs and then write a test for functionality requirements and then we can start completing the API and checking in every system to make sure it works. Maybe even fuzz the entire thing

**Comment by 372046933** [comment]
`test_seek_v1` works but `test_seek_v2` not
```python
def test_seek_v1():
  with open('file.txt', 'w+') as f:   # create a new file or truncates it
    f.write("test 1\n")
    f.write("test 2\n")
    f.write("test 3\n")             # now the file pointer is at the end
    f.seek(0)                       # move the file pointer to the beginning
    lines = f.read()                # read it, now we can read!
    print(lines)                    # print it

def test_seek_v2():
  with tf.io.gfile.GFile('file.txt', 'w+') as f:   # create a new file or truncates it
    f.write("test 1\n")
    f.write("test 2\n")
    f.write("test 3\n")             # now the file pointer is at the end
    f.seek(0)                       # move the file pointer to the beginning
    lines = f.read()                # read it, now we can read!
    print(lines)                    # print it
```

**Comment by mihaimaruseac** [comment]
I think `test_seek_v2` is actually correct. You are opening the file only for writing so of course you should not be able to read from it

**Comment by eirism** [comment]
The `+` argument to the built in `open()` function means that the file should be opened for updating (reading and writing), see the [docs](https://docs.python.org/3/library/functions.html#open). So the `w+` mode of the built in `open()` function means to open the file for reading and writing and truncating it first. I do not see any documentation of the `mode` parameter for `tf.io.gfile.GFile` in the [TF docs](https://www.tensorflow.org/api_docs/python/tf/io/gfile/GFile), so I can only assume that the semantics are supposed to be the same as the `mode` parameter for the built in `open()`.

This issue is about calling `.seek()` on a write only file (`w`), not about the behavior of the `w+` mode. So `test_seek_v1` and `test_seek_v2` are not relevant for this issue, but that behavior might be a separate issue.

**Comment by 372046933** [comment]
`test_seek_v2` open mode is reading and writing

https://github.com/tensorflow/tensorflow/blob/e0d5221071bdc741ec41125080d29869f5262112/tensorflow/python/lib/io/file_io.py#L40

**Comment by mihaimaruseac** [comment]
My bad, I misread the `+` meaning.

**Comment by sushreebarsa** [comment]
@eirism The provided code will trigger an error because you're attempting to call f.seek(0) on a file opened in write-only mode ('w'). Seeking is only supported for files opened in read or read/write modes.
Could you try to use it as follows;

```
with tf.io.gfile.GFile('test.txt', 'r+') as f:
  f.seek(0)
  # Your code that includes writing and seeking

```
Thank you!

**Comment by mihaimaruseac** [comment]
@sushreebarsa I had the same comment a while ago and got https://github.com/tensorflow/tensorflow/issues/32122#issuecomment-1302498735 as reply (which makes sense)

**Comment by eirism** [comment]
@sushreebarsa Normal Python file IO supports .seek() on files opened in write-only mode ('w'), so I expect GFile to also support it. In normal Python file IO .seek() moves the file object position and allows you to overwrite already written data. The following code using normal Python file IO will write "Hello" to the text file "test.txt" by using .seek() to overwrite the first character written to file:
```
with open("test.txt", "w") as f:
    f.write("hello")
    f.seek(0)  # Seek to start of file to overwrite characters from the start
    f.write("H")
```

**Comment by Venkat6871** [comment]
Hi @eirism  ,
Thank you so much for filing this bug request! We truly appreciate your support. At the moment, this request is not prioritized and mark it for community contributions. If you would like to contribute on a fix, please feel free to fork the repository and submit a pull request in accordance with the TensorFlow [CONTRIBUTION GUIDELINES](https://www.tensorflow.org/community/contribute/code) and link this issue in your PR to ensure the maintainers can easily review and collaborate.To avoid duplicate work, please leave a comment here if you decide to take it on!
Thank you again for your interest and we look forward to seeing your contributions!
