### ISSUE TITLE
XLA compilation fails in replica context of distribution strategy

### ISSUE THREAD

**Issue by hakos** [tensorflow/tensorflow#32187]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian GNU/Linux 9.9 (stretch)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v1.14.0-0-g87989f6 1.14.0
- Python version: Python 3.5.3
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: CUDA Version 10.0.130
- GPU model and memory: 2 x Nvidia Tesla K80

**Describe the current behavior**
Invoking `xla.compile` in the function passed to `strategy.experimental_run_v2` as in the code below raises the following exception (full traceback below):
```
ValueError: XLA compiled computations cannot be nested, (operator name: replica_1/input_0)
```
**Describe the expected behavior**
The expectation was to get one compiled XLA cluster for each replica.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
```python
import tensorflow as tf
from tensorflow.python.compiler.xla import xla

strategy = tf.distribute.experimental.CentralStorageStrategy(
    compute_devices=["/device:GPU:0", "/device:GPU:1"],
    parameter_device="/device:CPU:0"
)

with strategy.scope():
    def train_step(inputs):
        def step_fn(x):
            w = tf.get_variable(name="w", initializer=1.0)
            loss = w * x
            optimizer = tf.train.GradientDescentOptimizer(0.1)
            train_op = optimizer.minimize(loss)
            with tf.control_dependencies([train_op]):
                return tf.identity(loss)
        
        def compiled_step_fn(x):
            [out] = xla.compile(step_fn, inputs=[x])
            return out

        per_replica_losses = strategy.experimental_run_v2(
            compiled_step_fn, args=[inputs])
        sum_loss = strategy.reduce(
            tf.distribute.ReduceOp.SUM, per_replica_losses, axis=None)
        return sum_loss
    
    loss = train_step(1.0)
    with tf.Session() as sess:
        sess.run(tf.global_variables_initializer())
        for _ in range(10):
            print(sess.run(loss))
```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
```
Traceback (most recent call last):
  File "multi_gpu_strategy_xla.py", line 29, in <module>
    loss = train_step(1.0)
  File "multi_gpu_strategy_xla.py", line 24, in train_step
    compiled_step_fn, args=[inputs])
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/distribute/distribute_lib.py", line 511, in experimental_run_v2
    return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/distribute/distribute_lib.py", line 1555, in call_for_each_replica
    return self._call_for_each_replica(fn, args, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/distribute/parameter_server_strategy.py", line 407, in _call_for_each_replica
    self._container_strategy(), self._device_map, fn, args, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/distribute/mirrored_strategy.py", line 195, in _call_for_each_replica
    coord.join(threads)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/usr/local/lib/python3.5/dist-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/coordinator.py", line 297, in stop_on_exception
    yield
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/distribute/mirrored_strategy.py", line 911, in run
    self.main_result = self.main_fn(*self.main_args, **self.main_kwargs)
  File "multi_gpu_strategy_xla.py", line 20, in compiled_step_fn
    [out] = xla.compile(step_fn, inputs=[x])
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/compiler/xla/xla.py", line 110, in compile
    return _compile_internal(computation, inputs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/compiler/xla/xla.py", line 338, in _compile_internal
    for i, x in enumerate(flat_inputs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/compiler/xla/xla.py", line 338, in <listcomp>
    for i, x in enumerate(flat_inputs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/array_ops.py", line 86, in identity
    ret = gen_array_ops.identity(input, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 4253, in identity
    "Identity", input=input, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3616, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 2043, in __init__
    self._control_flow_post_processing()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 2054, in _control_flow_post_processing
    self._control_flow_context.AddOp(self)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/compiler/xla/xla.py", line 254, in AddOp
    self._outer_context.AddInnerOp(op)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/compiler/xla/xla.py", line 274, in AddInnerOp
    self.AddOp(op)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/compiler/xla/xla.py", line 202, in AddOp
    'name: %s)' % op.name)
ValueError: XLA compiled computations cannot be nested, (operator name: replica_1/input_0)
```

**Comment by oanush** [comment]
Issue replicating with TF-version [1.14](https://colab.sandbox.google.com/gist/oanush/7bc7560672e6df3d37a785f83bf601d0/32187.ipynb).

**Comment by sanjoy** [comment]
Yanan (ycao@google.com) is a better person to handle this.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
