### ISSUE TITLE
Inconsistent behavior of .shape when using sparse.placeholder

### ISSUE THREAD

**Issue by pavanky** [tensorflow/tensorflow#32193]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
No
- TensorFlow installed from (source or binary):
binary
- TensorFlow version (use command below):
1.15.0-dev20190821
- Python version:
3.7.4

**Describe the current behavior**

sparse.placeholder does loses the shape entirely when batch is not provided. This is inconstent with how tf.placeholder behaves.
**Describe the expected behavior**
tf.placeholder and tf.sparse.placeholder have the same behavior.

**Code to reproduce the issue**

```
import tensorflow as tf

print(tf.__version__)

print("Printing shape of sparse placeholder when using (None, 1024)")
print(tf.compat.v1.sparse.placeholder(dtype=tf.float32, shape=(None, 1024)).shape)

print("Printing shape of dense placeholder when using (None, 1024)")
print(tf.compat.v1.placeholder(dtype=tf.float32, shape=(None, 1024)).shape)

print("Printing shape of sparse placeholder when using (-1, 1024)")
print(tf.compat.v1.sparse.placeholder(dtype=tf.float32, shape=(-1, 1024)).shape)

print("Printing shape of dense placeholder when using (-1, 1024)")
print(tf.compat.v1.placeholder(dtype=tf.float32, shape=(-1, 1024)).shape)
```

**Other info / logs**

```
1.15.0-dev20190821
Printing shape of sparse placeholder when using (None, 1024)
(?, ?)
Printing shape of dense placeholder when using (None, 1024)
(?, 1024)
Printing shape of sparse placeholder when using (-1, 1024)
(?, 1024)
Printing shape of dense placeholder when using (-1, 1024)
Traceback (most recent call last):
  File "/home/pyalamanchili/.local/lib/python3.7/site-packages/tensorflow_core/python/eager/execute.py", line 206, in make_shape
    shape = tensor_shape.as_shape(v)
  File "/home/pyalamanchili/.local/lib/python3.7/site-packages/tensorflow_core/python/framework/tensor_shape.py", line 1216, in as_shape
    return TensorShape(shape)
  File "/home/pyalamanchili/.local/lib/python3.7/site-packages/tensorflow_core/python/framework/tensor_shape.py", line 776, in __init__
    self._dims = [as_dimension(d) for d in dims_iter]
  File "/home/pyalamanchili/.local/lib/python3.7/site-packages/tensorflow_core/python/framework/tensor_shape.py", line 776, in <listcomp>
    self._dims = [as_dimension(d) for d in dims_iter]
  File "/home/pyalamanchili/.local/lib/python3.7/site-packages/tensorflow_core/python/framework/tensor_shape.py", line 718, in as_dimension
    return Dimension(value)
  File "/home/pyalamanchili/.local/lib/python3.7/site-packages/tensorflow_core/python/framework/tensor_shape.py", line 198, in __init__
    raise ValueError("Dimension %d must be >= 0" % self._value)
ValueError: Dimension -1 must be >= 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/sparse_shape.py", line 15, in <module>
    print(tf.compat.v1.placeholder(dtype=tf.float32, shape=(-1, 1024)).shape)
  File "/home/pyalamanchili/.local/lib/python3.7/site-packages/tensorflow_core/python/ops/array_ops.py", line 2619, in placeholder
    return gen_array_ops.placeholder(dtype=dtype, shape=shape, name=name)
  File "/home/pyalamanchili/.local/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_array_ops.py", line 6667, in placeholder
    shape = _execute.make_shape(shape, "shape")
  File "/home/pyalamanchili/.local/lib/python3.7/site-packages/tensorflow_core/python/eager/execute.py", line 211, in make_shape
    e))
ValueError: Error converting shape to a TensorShape: Dimension -1 must be >= 0.

```

**Comment by pavanky** [comment]
This results in downstream bugs in keras. Should I create new tickets for them or should I include the bugs coming up in keras over here?

**Comment by oanush** [comment]
Issue replicating for TF version-[1.15.0-dev20190821](https://colab.research.google.com/gist/oanush/379564e09facc63f335a55bcb5319bfe/32193.ipynb).
Thanks!

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
