### ISSUE TITLE
ImportError: cannot import name 'Event' from 'tensorflow_core.python' (unknown location)

### ISSUE THREAD

**Issue by Full4me** [tensorflow/tensorflow#32196]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): with "pip install tensorflow-gpu==2.0.0-rc0"
- TensorFlow version:tensorflow-gpu==2.0.0-rc0
- Python version:3.7.3
- Installed using virtualenv? pip? conda?:pip
- Bazel version (if compiling from source):0.29.0
- CUDA/cuDNN version: CUDA 10.0 and 10.1/cuDNN 10.0 and 10.1
- GPU model and memory: NVIDIA GeForce GTX 1070/ 8 GB GDDR5

I'm using Jupyther notebook. I've installed tensorflow with 'pip install tensorflow-gpu==2.0.0-rc0' in my environment terminal. 
Now in Jupyter notebook trying to import with:
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Dense, Dropout, LSTM, BatchNormalization

And I've got this error:
`ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-167-72e06926552d>", line 11, in <module>
    from tensorflow.keras.models import Sequential
  File "C:\Anaconda3\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\Anaconda3\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "C:\Anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Anaconda3\lib\site-packages\tensorflow_core\__init__.py", line 45, in <module>
    from tensorflow._api.v2 import compat
  File "C:\Anaconda3\lib\site-packages\tensorflow_core\_api\v2\compat\__init__.py", line 23, in <module>
    from tensorflow._api.v2.compat import v1
  File "C:\Anaconda3\lib\site-packages\tensorflow_core\_api\v2\compat\v1\__init__.py", line 72, in <module>
    from tensorflow._api.v2.compat.v1 import summary
  File "C:\Anaconda3\lib\site-packages\tensorflow_core\_api\v2\compat\v1\summary\__init__.py", line 14, in <module>
    from tensorflow.python import Event
ImportError: cannot import name 'Event' from 'tensorflow_core.python' (unknown location)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2033, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'ImportError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\IPython\core\ultratb.py", line 1095, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "C:\Anaconda3\lib\site-packages\IPython\core\ultratb.py", line 313, in wrapped
    return f(*args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\IPython\core\ultratb.py", line 347, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "C:\Anaconda3\lib\inspect.py", line 1502, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
  File "C:\Anaconda3\lib\inspect.py", line 1460, in getframeinfo
    filename = getsourcefile(frame) or getfile(frame)
  File "C:\Anaconda3\lib\inspect.py", line 696, in getsourcefile
    if getattr(getmodule(object, filename), '__loader__', None) is not None:
  File "C:\Anaconda3\lib\inspect.py", line 733, in getmodule
    if ismodule(module) and hasattr(module, '__file__'):
  File "C:\Anaconda3\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\Anaconda3\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "C:\Anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Anaconda3\lib\site-packages\tensorflow_core\__init__.py", line 45, in <module>
    from tensorflow._api.v2 import compat
  File "C:\Anaconda3\lib\site-packages\tensorflow_core\_api\v2\compat\__init__.py", line 23, in <module>
    from tensorflow._api.v2.compat import v1
  File "C:\Anaconda3\lib\site-packages\tensorflow_core\_api\v2\compat\v1\__init__.py", line 72, in <module>
    from tensorflow._api.v2.compat.v1 import summary
  File "C:\Anaconda3\lib\site-packages\tensorflow_core\_api\v2\compat\v1\summary\__init__.py", line 14, in <module>
    from tensorflow.python import Event
ImportError: cannot import name 'Event' from 'tensorflow_core.python' (unknown location)

When I was using same code with Sublime Text it was working ok.
`

**Comment by oanush** [comment]
@Full4me ,
When tried running ```
 from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, LSTM, BatchNormalization 
```code,  I was able to execute without any issues.Thanks!

**Comment by Full4me** [comment]
@oanush 

reinstalled, restarted PC and now is working. 

Thx for You time.
