### ISSUE TITLE
Coral Board Demo example fails RuntimeError: Model provided has model identifier 'CTYP', should be 'TFL3'

### ISSUE THREAD

**Issue by mcanerim** [tensorflow/tensorflow#32204]
Traceback (most recent call last):
  File "/usr/bin/edgetpu_classify", line 11, in <module>
    load_entry_point('edgetpuvision==1.0', 'console_scripts', 'edgetpu_classify')()
  File "/usr/lib/python3/dist-packages/edgetpuvision/classify.py", line 162, in main
    run_app(add_render_gen_args, render_gen)
  File "/usr/lib/python3/dist-packages/edgetpuvision/apps.py", line 70, in run_app
    display=args.displaymode):
  File "/usr/lib/python3/dist-packages/edgetpuvision/gstreamer.py", line 240, in run_gen
    inference_size = render_overlay_gen.send(None)  # Initialize.
  File "/usr/lib/python3/dist-packages/edgetpuvision/classify.py", line 112, in render_gen
    engines, titles = utils.make_engines(args.model, ClassificationEngine)
  File "/usr/lib/python3/dist-packages/edgetpuvision/utils.py", line 53, in make_engines
    engine = engine_class(model_path)
  File "/usr/lib/python3/dist-packages/edgetpu/classification/engine.py", line 38, in __init__
    super().__init__(model_path)
  File "/usr/lib/python3/dist-packages/edgetpu/swig/edgetpu_cpp_wrapper.py", line 300, in __init__
    this = _edgetpu_cpp_wrapper.new_BasicEngine(*args)
RuntimeError: Model provided has model identifier 'CTYP', should be 'TFL3'

This is the output of Coral Board with the Coral Camera example. The given tflite model produces the above output. I couldn't figure out why.

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ravikyram** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the code snippet to reproduce the issue. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by kayak93** [comment]
same error trying to run the teachable demo on the coral board

**Comment by R4ZZ3** [comment]
I am having same problem.
RPI 4 and python 3.7.3
![image](https://user-images.githubusercontent.com/25264037/65900790-73a59180-e3bf-11e9-9678-47f84b8b6d03.png)

**Comment by mikkleini** [comment]
I get complains that my model is 'ion ':

`File "/usr/local/lib/python3.7/dist-packages/edgetpu/detection/engine.py", line 73, in __init__
    super().__init__(model_path)
  File "/usr/local/lib/python3.7/dist-packages/edgetpu/basic/basic_engine.py", line 40, in __init__
    self._engine = BasicEnginePythonWrapper.CreateFromFile(model_path)
RuntimeError: Model provided has model identifier 'ion ', should be 'TFL3'`

I trained quantized model and used the export_tflite_ssd_graph.py and tflite_convert to get the EdgeTPU compiled model.

**Comment by mikkleini** [comment]
My bad. Was sending model over Git LFS to RPi and forgot to do lfs sync. Also forgot to run the tflite through the edgetpu_compiler.

**Comment by chohk88** [comment]
@mikkleini 
I have similar error. 
> ERROR: Model provided has model identifier '', should be 'TFL3'
Could you explain how to resolve this error in detail?

**Comment by mikkleini** [comment]
@chohk88 - basically my problem was that I provided completely wrong type of file to inference engine.  Open your file with some text or binary editor and check if it reminds tflite file or not.
You should see "TFL3" in ASCII at 5th byte. If not then you could have wrong file or damaged file.

**Comment by paroque28** [comment]
Hi @mikkleini ,
I am using Git LFS as well but I am confused.
What is git LFS sync? 
I thought ` git lfs track "*.psd"` was enough

Do I need to install git LFS on the RPI4 as well and run some command?

**Comment by paroque28** [comment]
@mikkleini 
Yes running `git lfs pull` on the RPI4 solved my issue :)

**Comment by geogeorgiev** [comment]
I used to have a similar problem when downloading a `.tflite` file from github (the coral TPU detection demo). The reason was that I was not logged in on the remote device (no session creds on my RPI4) and was downloading not the buffer file but a `html` file :). As a result, I used to get `ValueError: Model provided has model identifier '<!D', should be 'TFL3'`. Please make sure the `.tflite` is holding a buffer and not something else.

**Comment by manisar2** [comment]
In my case, the `.tflite` files mentioned in the `install_requirements.sh` were not present in the repository (they were renamed). For example, `mobilenet_ssd_v2_coco_quant_postprocess.tflite` was not present, instead this was present - `ssd_mobilenet_v2_coco_quant_postprocess.tflite`.

Because of this, the `curl `command in `install_requirements.sh` simply got 404 HTML page from github, and that showed up as this error later - 
> ValueError: Model provided has model identifier '<!D', should be 'TFL3'

I changed the file names in both the installation script and the subsequent command, removed old `.tflite` file, rerun the installation scvript, and then it ran fine.

**Comment by leaprobots** [comment]
Hi,

Solution: For Coral_Edge_TPU

Actually install_requirements file downloads file with name of "${TEST_DATA_URL}/mobilenet_ssd_v2_coco_quant_postprocess_edgetpu.tflite" \
     -OL "${TEST_DATA_URL}/mobilenet_ssd_v2_coco_quant_postprocess.tflite" \
     -OL "${TEST_DATA_URL}/coco_labels.txt")

But above files do not exist currently in repository.

So download from https://github.com/google-coral/edgetpu/tree/master/test_data
**ssh_mobilenet v2_coco_quant_postprocess_edgetpu.tflite** and another file from the repository and replace in the model folder.
Run script with changed names then it works fine.
