### ISSUE TITLE
Weights that are SparseTensor values do not get gradients in eager execution mode

### ISSUE THREAD

**Issue by laci37** [tensorflow/tensorflow#32215]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v1.14.0-rc1-22-gaf24dc91b5 1.14.0 also reproduces on v2.0.0-beta1-5101-gc75bb66 2.0.0-rc0
- Python version: 3.6.7
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: None
- GPU model and memory: None

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

When trying to train a subclassed Keras model that has a trainable parameter that is the values Tensor of a SparseTensor weight matrix, the training fails with an error message saying that the parameter does not have gradients. This problem reproduces only in eager mode.

**Describe the expected behavior**

The values of non-zero elements in sparse weight matrices with fixed indices should be trainable.

**Code to reproduce the issue**

The code for the two versions only differs in enabling eager execution and the loss function.

```python
import tensorflow as tf
import numpy as np

#Without this line the script works in v1.14.
#comment out this line for v2.0-rc0
tf.enable_eager_execution()


def matmul_dense_sparse(a, b):
    ta = tf.transpose(a)
    tb = tf.sparse.transpose(b)
    return tf.transpose(tf.sparse.sparse_dense_matmul(tb, ta))


class SparseLayer(tf.keras.layers.Layer):
    def __init__(self, indices, shape):
        super().__init__()
        self.indices = indices
        self.shape = shape

    def build(self, input_shape):
        self.w = self.add_weight(name='w',
                        shape=(self.indices.shape[0],),
                        trainable=True)
        self.sparse_mat = tf.sparse.reorder(tf.sparse.SparseTensor(self.indices, self.w, self.shape))
        super().build(input_shape)

    def call(self, inputs):
        return matmul_dense_sparse(inputs, self.sparse_mat)


class SparseModel(tf.keras.Model):
    def __init__(self, indices, shape):
        super().__init__()
        self.l1 = SparseLayer(indices, shape)

    def call(self, inputs):
        return self.l1(inputs)

indices = np.array([[1, 2], [30, 1], [30, 3], [45, 2], [56, 2], [32, 4]])

ex_x = np.random.rand(20, 100)
ex_y = np.random.rand(20, 5)

model = SparseModel(indices, (100, 5))

#compile for v1.14
model.compile(tf.keras.optimizers.SGD(), tf.losses.mean_squared_error)
#compile for v2.0-rc0
#model.compile(tf.keras.optimizers.SGD(), tf.losses.MeanSquaredError())

model.fit(ex_x, ex_y)
```

**Other info / logs**
Traceback in v1.14:
```
Traceback (most recent call last):
  File "bug_reprod.py", line 43, in <module>
    model.fit(ex_x, ex_y)
  File "/home/mero/.ve/tfsim-P0VFtrg_/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 780, in fit
    steps_name='steps_per_epoch')
  File "/home/mero/.ve/tfsim-P0VFtrg_/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_arrays.py", line 157, in model_iteration
    f = _make_execution_function(model, mode)
  File "/home/mero/.ve/tfsim-P0VFtrg_/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_arrays.py", line 532, in _make_execution_function
    return model._make_execution_function(mode)
  File "/home/mero/.ve/tfsim-P0VFtrg_/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 2276, in _make_execution_function
    self._make_train_function()
  File "/home/mero/.ve/tfsim-P0VFtrg_/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 2219, in _make_train_function
    params=self._collected_trainable_weights, loss=self.total_loss)
  File "/home/mero/.ve/tfsim-P0VFtrg_/lib/python3.6/site-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py", line 491, in get_updates
    grads = self.get_gradients(loss, params)
  File "/home/mero/.ve/tfsim-P0VFtrg_/lib/python3.6/site-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py", line 398, in get_gradients
    "K.argmax, K.round, K.eval.".format(param))
ValueError: Variable <tf.Variable 'sparse_model/sparse_layer/w:0' shape=(6,) dtype=float32> has `None` for gradient. Please make sure that all of your ops have a gradient defined (i.e. are differentiable). Common ops without gradient: K.argmax, K.round, K.eval.
```

Traceback in 2.0-rc0:

```
Traceback (most recent call last):
  File "bug_reprod.py", line 42, in <module>
    model.fit(ex_x, ex_y)
  File "/home/mero/.ve/tfsim-8nc9BEC-/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py", line 734, in fit
    use_multiprocessing=use_multiprocessing)
  File "/home/mero/.ve/tfsim-8nc9BEC-/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 324, in fit
    total_epochs=epochs)
  File "/home/mero/.ve/tfsim-8nc9BEC-/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 123, in run_one_epoch
    batch_outs = execution_function(iterator)
  File "/home/mero/.ve/tfsim-8nc9BEC-/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 86, in execution_function
    distributed_function(input_fn))
  File "/home/mero/.ve/tfsim-8nc9BEC-/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 427, in __call__
    self._initialize(args, kwds, add_initializers_to=initializer_map)
  File "/home/mero/.ve/tfsim-8nc9BEC-/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 370, in _initialize
    *args, **kwds))
  File "/home/mero/.ve/tfsim-8nc9BEC-/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1847, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/home/mero/.ve/tfsim-8nc9BEC-/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2147, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/home/mero/.ve/tfsim-8nc9BEC-/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2038, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/home/mero/.ve/tfsim-8nc9BEC-/lib/python3.6/site-packages/tensorflow_core/python/framework/func_graph.py", line 915, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/mero/.ve/tfsim-8nc9BEC-/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 320, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/home/mero/.ve/tfsim-8nc9BEC-/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 73, in distributed_function
    per_replica_function, args=(model, x, y, sample_weights))
  File "/home/mero/.ve/tfsim-8nc9BEC-/lib/python3.6/site-packages/tensorflow_core/python/distribute/distribute_lib.py", line 760, in experimental_run_v2
    return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
  File "/home/mero/.ve/tfsim-8nc9BEC-/lib/python3.6/site-packages/tensorflow_core/python/distribute/distribute_lib.py", line 1787, in call_for_each_replica
    return self._call_for_each_replica(fn, args, kwargs)
  File "/home/mero/.ve/tfsim-8nc9BEC-/lib/python3.6/site-packages/tensorflow_core/python/distribute/distribute_lib.py", line 2132, in _call_for_each_replica
    return fn(*args, **kwargs)
  File "/home/mero/.ve/tfsim-8nc9BEC-/lib/python3.6/site-packages/tensorflow_core/python/autograph/impl/api.py", line 292, in wrapper
    return func(*args, **kwargs)
  File "/home/mero/.ve/tfsim-8nc9BEC-/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 264, in train_on_batch
    output_loss_metrics=model._output_loss_metrics)
  File "/home/mero/.ve/tfsim-8nc9BEC-/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_eager.py", line 311, in train_on_batch
    output_loss_metrics=output_loss_metrics))
  File "/home/mero/.ve/tfsim-8nc9BEC-/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_eager.py", line 272, in _process_single_batch
    model.optimizer.apply_gradients(zip(grads, trainable_weights))
  File "/home/mero/.ve/tfsim-8nc9BEC-/lib/python3.6/site-packages/tensorflow_core/python/keras/optimizer_v2/optimizer_v2.py", line 427, in apply_gradients
    grads_and_vars = _filter_grads(grads_and_vars)
  File "/home/mero/.ve/tfsim-8nc9BEC-/lib/python3.6/site-packages/tensorflow_core/python/keras/optimizer_v2/optimizer_v2.py", line 1025, in _filter_grads
    ([v.name for _, v in grads_and_vars],))
ValueError: No gradients provided for any variable: ['sparse_model/sparse_layer/w:0'].
```

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by tanzhenyu** [comment]
Passing variable as tensor and then try to get gradients is not supported. This will very likely error out even if you're using dense tensor as well. If you want to support sparse input, simply use tf.keras.layers.Dense since it already supports sparse input today (starting in TF 2.0 rc0)

**Comment by laci37** [comment]
If I understand @martinwicke 's comments on the issue #6998 well this is supposed to work this way. Replacing all sparse ops with their dense equivalent makes the above code work on 2.0-rc0.

**Comment by laci37** [comment]
I made a workaround for my use case with `tf.custom_gradient`. It is probably slow on the backward pass, but works. It can be found here: https://gist.github.com/laci37/b7bcb88a08ed09e298b6bf34393ad80b
