### ISSUE TITLE
tf.keras Sequence model looses final output when saved as frozen pb graph?

### ISSUE THREAD

**Issue by vade** [tensorflow/tensorflow#32241]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes and No. Both cases fail.
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux / Google Collaboratory runtime
- TensorFlow installed from (source or binary): No : Google Collab default runtime
- TensorFlow version (use command below): Google Collab default runtime / Tensorflow  1.14.0
tf.keras 2.2.4-tf
- Python version: Google Collab default runtime: 3.6.8 (default, Jan 14 2019, 11:02:34) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]

**Describe the current behavior**

I am able to successfully build a model train, evaluate and run prediticions on a Sequence model using NasNetMobile. I can save my model using model.save in tf.keras and have a well formed h5 file with a graph, weights and inputs and outputs as expected and verified in Netron.

I wish to convert this model to pb. Using various techniques I will describe below, I load the model using tf.keras, and introspecting the model summary and model inputs and outputs. All is as to be expected (save a slight difference in output tensor name).

Saving the PB does not error, and creates a valid PB file but it lacks the final graph output, and tools like tf_coreml and Netron complain of missing output.

**Describe the expected behavior**

Loading a save h5 file and saving the resulting Tensorflow pb results in a well formed PB that can be used for inference.

**Code to reproduce the issue**

**Model definition:**

```

base_model = tf.keras.applications.NASNetMobile(input_shape=(IMG_SIZE, IMG_SIZE, 3),
                                               include_top=False,
                                               weights='imagenet')
base_model.trainable = False

output = tf.keras.layers.Dense(num_labels, activation = 'sigmoid', name="output")
model = tf.keras.Sequential([
  base_model,
  tf.keras.layers.GlobalAveragePooling2D(),
  output])
model.summary()
```

Which prints:
```
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
NASNet (Model)               (None, 7, 7, 1056)        4269716   
_________________________________________________________________
global_average_pooling2d (Gl (None, 1056)              0         
_________________________________________________________________
output (Dense)               (None, 229)               242053    
=================================================================
Total params: 4,511,769
Trainable params: 242,053
Non-trainable params: 4,269,716
_________________________________________________________________
```

**Saving the model:**

```
#verify inputs and outputs
print(model.input.op.name)
print(model.output.op.name) 
tf.keras.models.save_model(model, model_path, overwrite=True,save_format="h5")
```

or alternatively;
```
#verify inputs and outputs
print(model.input.op.name)
print(model.output.op.name) 
 model.save(model_path)
```

Both mechanisms print the following inputs and output tensor names:

```
NASNet_input
output/Identity
```

**Loading said model in a different ipynb:**

```

import tensorflow as tf
import tensorflow.keras.backend as K
from tensorflow.python.tools import freeze_graph

# unclear if strictly necessary but git issues imply it may be defensive to add these lines
tf.reset_default_graph()
K.clear_session()
K.set_learning_phase(0)

restored_model = tf.keras.models.load_model(model_path, compile=True)
print(restored_model.inputs)
print(restored_model.outputs)

restored_model.summary()
```

Which prints:

```
[<tf.Tensor 'NASNet_input:0' shape=(?, 224, 224, 3) dtype=float32>]
[<tf.Tensor 'output/Sigmoid:0' shape=(?, 229) dtype=float32>]
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
NASNet (Model)               (None, 7, 7, 1056)        4269716   
_________________________________________________________________
global_average_pooling2d (Gl (None, 1056)              0         
_________________________________________________________________
output (Dense)               (None, 229)               242053    
=================================================================
Total params: 4,511,769
Trainable params: 242,053
Non-trainable params: 4,269,716
```

Notice the output tensor has changed its name / no longer identity / placeholder?

**Saving to PB**

The simplest incantation which does not do any graph cleaning / optimization

```
import datetime

output_model_name = model_name + ".pb"
output_model_path = "/tmp/" + output_model_name
save_dir = "./tmp_{:%Y-%m-%d_%H%M%S}".format(datetime.datetime.now())
tf.saved_model.simple_save(K.get_session(),
                           save_dir,
                           inputs={"input": restored_model.inputs[0]},
                           outputs={"output": restored_model.outputs[0]})

freeze_graph.freeze_graph(None,
                          None,
                          None,
                          None,
                          restored_model.outputs[0].op.name,
                          None,
                          None,
                           output_model_path,
                          False,
                          "",
                          input_saved_model_dir=save_dir)
```

Results in a PB that is missing the output layer.

**Other PB saving methods ive tried:**

All result with a PB missing output:
```
with tf.keras.backend.get_session() as session:
  graph = session.graph
  input_graph_def = graph.as_graph_def()
  
  # For demonstration purpose we show the first 15 ops the TF model
with graph.as_default() as g:
    tf.import_graph_def(input_graph_def, name='')
    
    ops = g.get_operations()
    for op in ops[0:15]:
        print('op name: {}, op type: "{}"'.format(op.name, op.type));
    for op in ops[::-1][0:15]:
        print('op name: {}, op type: "{}"'.format(op.name, op.type));

  

input_node_names = ['NASNet_input']
output_node_names = ['output/Sigmoid']
gdef = strip_unused_lib.strip_unused(
      input_graph_def = input_graph_def,
      input_node_names = input_node_names,
      output_node_names = output_node_names,
      placeholder_type_enum = dtypes.float32.as_datatype_enum)
  
with gfile.GFile(output_model_path, "wb") as f:
    f.write(gdef.SerializeToString())
```

And :

```
# from tensorflow.python.framework.graph_util import convert_variables_to_constants


def freeze_session(session, keep_var_names=None, output_names=None, clear_devices=True):
    """
    Freezes the state of a session into a pruned computation graph.

    Creates a new computation graph where variable nodes are replaced by
    constants taking their current value in the session. The new graph will be
    pruned so subgraphs that are not necessary to compute the requested
    outputs are removed.
    @param session The TensorFlow session to be frozen.
    @param keep_var_names A list of variable names that should not be frozen,
                          or None to freeze all the variables in the graph.
    @param output_names Names of the relevant graph outputs.
    @param clear_devices Remove the device directives from the graph for better portability.
    @return The frozen graph definition.
    """
    from tensorflow.python.framework.graph_util import convert_variables_to_constants
    graph = session.graph
    with graph.as_default():
        freeze_var_names = list(set(v.op.name for v in tf.global_variables()).difference(keep_var_names or []))
        output_names = output_names or []
        output_names += [v.op.name for v in tf.global_variables()]
        # Graph -> GraphDef ProtoBuf
        input_graph_def = graph.as_graph_def()
        if clear_devices:
            for node in input_graph_def.node:
                node.device = ""
        frozen_graph = convert_variables_to_constants(session, input_graph_def,
                                                      output_names, freeze_var_names)
        return frozen_graph



      
frozen_graph = freeze_session(K.get_session(),
                              output_names=[out.op.name for out in restored_model.outputs], 
                             clear_devices=True)

tf.train.write_graph(frozen_graph, "/tmp", model_name+".pb", as_text=False)

```

**Other info / logs**

Here is a link the my H5 file:

https://storage.cloud.google.com/synopsis_cinemanet/Synopsis_Models/Cinemanet-2019-09-04_21_57_48.h5

Here is a link to a resulting PB file ive tried to make, which lacks output:

https://storage.cloud.google.com/synopsis_cinemanet/Synopsis_Models/Cinemanet-2019-09-04_21_57_48.h5.pb

Thank you very much!

**Comment by vade** [comment]
Ok, looking further into this, it appears this bug was fixed in TF 2.0:

https://github.com/tensorflow/tensorflow/issues/28668

Switching Google Collab to use TF 2.0 now prints the `output/Identity` upon loading the model:

```
try:
  # %tensorflow_version only exists in Colab.
  %tensorflow_version 2.x
except Exception:
  pass


# import tensorflow.compat.v1 as tf
# tf.disable_v2_behavior()

import tensorflow as tf
import tensorflow.keras.backend as K
from tensorflow.python.tools import freeze_graph

restored_model = tf.keras.models.load_model(model_path, compile=True)
print(restored_model.input.op.name)
print(restored_model.output.op.name)
restored_model.summary()
```

prints

```
TensorFlow 2.x selected.
WARNING:tensorflow:No training configuration found in save file: the model was *not* compiled. Compile it manually.
NASNet_input
output/Identity
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
NASNet (Model)               (None, 7, 7, 1056)        4269716   
_________________________________________________________________
global_average_pooling2d (Gl (None, 1056)              0         
_________________________________________________________________
output (Dense)               (None, 229)               242053    
=================================================================
Total params: 4,511,769
Trainable params: 242,053
Non-trainable params: 4,269,716
```

However, its unclear if I can export a protocol buffer from TF 2.0 directly in Python anymore? The above code all relies of sessions which are gone, as well as other functions. Perusing the documentation doesn't reveal anything obvious but im new to TF 2.0 changes.

Thank you in advance.

**Comment by vade** [comment]
Using the new `tf.saved_model.save` function lets me save a pb file but, sadly, the PB file appears malformed or not appropriate for inference (Netron complains its very large - and once its loaded it appears very different than my h5).

**Comment by vade** [comment]
Ok, so, Freeze_graph from 2.0 branch does not appear to work either, even if I adjust tensor names from operation names, I consistently get output not in graph. Im using TF 2.0.0rc0, using the freeze_graph.py, and using 'output/Identity' as my output tensor name:

My freeze graph call:

`freeze_graph.py freeze_graph.py --input_saved_model_dir="Path/to/saved/model" --output_node_names="output/identity" --output_graph="/Path/To/Output.pb"`

Which results in

```
2019-09-05 17:14:15.542361: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-09-05 17:14:15.551903: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fd5b49f48e0 executing computations on platform Host. Devices:
2019-09-05 17:14:15.551919: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
W0905 17:14:17.094927 4566570432 deprecation.py:323] From freeze_graph.py:163: load (from tensorflow.python.saved_model.loader_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.loader.load or tf.compat.v1.saved_model.load. There will be a new function for importing SavedModels in Tensorflow 2.0.
I0905 17:14:19.887789 4566570432 saver.py:1284] Restoring parameters from ./CinemaNet_Saved_Model/1/variables/variables
W0905 17:14:23.509812 4566570432 deprecation.py:323] From freeze_graph.py:235: convert_variables_to_constants (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.convert_variables_to_constants`
W0905 17:14:23.509926 4566570432 deprecation.py:323] From /Library/Python/2.7/site-packages/tensorflow_core/python/framework/graph_util_impl.py:275: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.extract_sub_graph`
Traceback (most recent call last):
  File "freeze_graph.py", line 493, in <module>
    run_main()
  File "freeze_graph.py", line 489, in run_main
    app.run(main=my_main, argv=[sys.argv[0]] + unparsed)
  File "/Library/Python/2.7/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/Library/Python/2.7/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/Library/Python/2.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "freeze_graph.py", line 488, in <lambda>
    my_main = lambda unused_args: main(unused_args, flags)
  File "freeze_graph.py", line 380, in main
    flags.saved_model_tags, checkpoint_version)
  File "freeze_graph.py", line 363, in freeze_graph
    checkpoint_version=checkpoint_version)
  File "freeze_graph.py", line 235, in freeze_graph_with_def_protos
    variable_names_blacklist=variable_names_blacklist)
  File "/Library/Python/2.7/site-packages/tensorflow_core/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/tensorflow_core/python/framework/graph_util_impl.py", line 275, in convert_variables_to_constants
    inference_graph = extract_sub_graph(input_graph_def, output_node_names)
  File "/Library/Python/2.7/site-packages/tensorflow_core/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/tensorflow_core/python/framework/graph_util_impl.py", line 195, in extract_sub_graph
    _assert_nodes_are_present(name_to_node, dest_nodes)
  File "/Library/Python/2.7/site-packages/tensorflow_core/python/framework/graph_util_impl.py", line 150, in _assert_nodes_are_present
    assert d in name_to_node, "%s is not in graph" % d
AssertionError: output/Identity is not in graph
```

**Comment by vade** [comment]
Any help? 

Is freeze_graph.py officially supported in TF 2.0?

How do I get this TF 1.14 TF Keras Sequence model ACTUALLY EXPORTED WITH OUTPUT NODES?

This seems so trivial and yet, it isn't working. I must be missing something. Id really appreciate some help.

**Comment by gowthamkpr** [comment]
@vade Yes freeze_graph.py is officially supported by tensorflow 2.0. You can find it [here](https://github.com/tensorflow/tensorflow/blob/r2.0/tensorflow/python/tools/freeze_graph.py)

**Comment by vade** [comment]
Well, Ive tried it, and it doesn't work - as far as I can tell evoking the graph API for whatever reason, on this model removes the last output node. :( 

`python3 freeze_graph.py freeze_graph.py --input_saved_model_dir=Cinemanet-2019-09-06_13_59_49_Saved_Model_TF2 --output_node_names=cinemanet_output/Identity --output_graph=./CinemaNet.pb`

```
2.0.0-rc0
2019-09-06 13:37:57.762585: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-09-06 13:37:57.782132: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fe12823eec0 executing computations on platform Host. Devices:
2019-09-06 13:37:57.782153: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
WARNING:tensorflow:From freeze_graph.py:163: load (from tensorflow.python.saved_model.loader_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.loader.load or tf.compat.v1.saved_model.load. There will be a new function for importing SavedModels in Tensorflow 2.0.
W0906 13:37:59.396905 4518606272 deprecation.py:323] From freeze_graph.py:163: load (from tensorflow.python.saved_model.loader_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.loader.load or tf.compat.v1.saved_model.load. There will be a new function for importing SavedModels in Tensorflow 2.0.
INFO:tensorflow:Restoring parameters from Cinemanet-2019-09-06_13_59_49_Saved_Model_TF2/variables/variables
I0906 13:38:02.095875 4518606272 saver.py:1284] Restoring parameters from Cinemanet-2019-09-06_13_59_49_Saved_Model_TF2/variables/variables
WARNING:tensorflow:From freeze_graph.py:235: convert_variables_to_constants (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.convert_variables_to_constants`
W0906 13:38:06.049952 4518606272 deprecation.py:323] From freeze_graph.py:235: convert_variables_to_constants (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.convert_variables_to_constants`
WARNING:tensorflow:From /usr/local/lib/python3.7/site-packages/tensorflow_core/python/framework/graph_util_impl.py:275: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.extract_sub_graph`
W0906 13:38:06.050114 4518606272 deprecation.py:323] From /usr/local/lib/python3.7/site-packages/tensorflow_core/python/framework/graph_util_impl.py:275: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.extract_sub_graph`
Traceback (most recent call last):
  File "freeze_graph.py", line 493, in <module>
    run_main()
  File "freeze_graph.py", line 489, in run_main
    app.run(main=my_main, argv=[sys.argv[0]] + unparsed)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "freeze_graph.py", line 488, in <lambda>
    my_main = lambda unused_args: main(unused_args, flags)
  File "freeze_graph.py", line 380, in main
    flags.saved_model_tags, checkpoint_version)
  File "freeze_graph.py", line 363, in freeze_graph
    checkpoint_version=checkpoint_version)
  File "freeze_graph.py", line 235, in freeze_graph_with_def_protos
    variable_names_blacklist=variable_names_blacklist)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/framework/graph_util_impl.py", line 275, in convert_variables_to_constants
    inference_graph = extract_sub_graph(input_graph_def, output_node_names)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/framework/graph_util_impl.py", line 195, in extract_sub_graph
    _assert_nodes_are_present(name_to_node, dest_nodes)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/framework/graph_util_impl.py", line 150, in _assert_nodes_are_present
    assert d in name_to_node, "%s is not in graph" % d
AssertionError: cinemanet_output/Identity is not in graph
```

**Comment by gowthamkpr** [comment]
@vade  I don't have access to your h5 file and .pb file. Also can you please reproduce the issue in colab and share the github gist with me. Thanks!

**Comment by vade** [comment]
Hi, Apologies: Here is a my working google collaboration doc:

https://colab.research.google.com/drive/1-Mb8Smap__h9Ld2l_fuLuQn0wCB4WSs_

And here are some model files that may be pertinent:

The H5 has the output as expected and defined in the Sequence model created in tf.keras.

The output PB *does not* have an output at all.

However, I can find the named output of the model and use the resulting PB file.

Thank you

https://storage.cloud.google.com/synopsis_cinemanet/Synopsis_Models/Cinemanet-2019-09-17_15_28_53.json
https://storage.cloud.google.com/synopsis_cinemanet/Synopsis_Models/Cinemanet-2019-09-17_15_28_53-weights.h5
https://storage.cloud.google.com/synopsis_cinemanet/Synopsis_Models/Cinemanet-2019-09-17_15_28_53.h5
https://storage.cloud.google.com/synopsis_cinemanet/Synopsis_Models/Cinemanet-2019-09-17_15_28_53.pb

**Comment by vade** [comment]
Netron images of the h5 with output and the pb without for reference:

<img width="1136" alt="Screen Shot 2019-09-18 at 2 08 41 PM" src="https://user-images.githubusercontent.com/65011/65173932-e0af4380-da1d-11e9-8296-8893dd1570f1.png">
<img width="1136" alt="Screen Shot 2019-09-18 at 2 08 09 PM" src="https://user-images.githubusercontent.com/65011/65173933-e0af4380-da1d-11e9-84d9-3b92d4e255b4.png">

**Comment by gowthamkpr** [comment]
@vade I am unable to find the colab notebook. heres what I get
![image](https://user-images.githubusercontent.com/47574994/65193710-e8c4ae80-da30-11e9-9f3e-9efa3719b1af.png)

**Comment by vade** [comment]
@gowthamkpr - strange - I was able to open this collab link on Chrome and it worked (I was not logged into my account):

https://colab.research.google.com/drive/1-Mb8Smap__h9Ld2l_fuLuQn0wCB4WSs_

And also verified the GCS storage links worked (I also share these links with collaborators and they are able to view it, and the GCS bucket and contents are public)

<img width="1360" alt="image" src="https://user-images.githubusercontent.com/65011/65198743-44536400-da52-11e9-8d48-684065626aba.png">

Try these URLS - im not sure why they are different in the GCS console. 

https://storage.googleapis.com/synopsis_cinemanet/Synopsis_Models/Cinemanet-2019-09-17_15_28_53.json

https://storage.googleapis.com/synopsis_cinemanet/Synopsis_Models/Cinemanet-2019-09-17_15_28_53-weights.h5

https://storage.googleapis.com/synopsis_cinemanet/Synopsis_Models/Cinemanet-2019-09-17_15_28_53.h5

https://storage.googleapis.com/synopsis_cinemanet/Synopsis_Models/Cinemanet-2019-09-17_15_28_53.pb

Sorry for the back and forth!

**Comment by gowthamkpr** [comment]
@vade Thank you I had an issue with my browser. Will look into it

**Comment by sayakpaul** [comment]
@gowthamkpr `freeze_graph.py` is discontinued now, right? I am referring to this release note: https://github.com/tensorflow/tensorflow/releases/tag/v2.0.0/.

**Comment by gowthamkpr** [comment]
@sayakpaul Yes, freeze_graph.py is discontinued in Tensorflow 2.0.

**Comment by gowthamkpr** [comment]
Closing this issue as it has been inactive for more than 15 days. Please add additional comments and we can open the issue again. Thanks!

**Comment by BuiNgocHai** [comment]
Hi I'm trying to dumb frozen .pb graph from .hdf5 file but I my .pb have difference output with .h5 file 
### input and output name of .hdf5 file
```bash
All input nodes: [<tf.Tensor 'input_1:0' shape=(?, 256, 320, 3) dtype=float32>]
All output nodes: [<tf.Tensor 'fcn17/truediv:0' shape=(?, ?, ?, 4) dtype=float32>]
```
### and output value of hdf5 file like this: 
```bash
array([[[[0.95520484, 0.02454368, 0.01151993, 0.0087315 ],
         [0.96743697, 0.01915975, 0.00736554, 0.00603788],
         [0.97429854, 0.01614887, 0.00556678, 0.00398591],
         ...,
         [0.96292394, 0.01786121, 0.00704672, 0.01216816],
         [0.95855474, 0.02005052, 0.00870537, 0.0126894 ],
         [0.9483133 , 0.02560406, 0.01250436, 0.01357825]],
         ...,
         [0.6439966 , 0.33929765, 0.01019213, 0.00651362],
         [0.64723253, 0.3306629 , 0.01337334, 0.00873124],
         [0.649275  , 0.3211698 , 0.01852187, 0.0110333 ]]]],
      dtype=float32)
```
###  this is output of .pb file ( 'fcn17/truediv:0' ) : 
```bash
[[[0.24999999 0.25       0.25       0.25      ]
  [0.25       0.25       0.25       0.25      ]
  [0.25       0.25       0.24999999 0.24999999]
  ...
  [0.25       0.25       0.25       0.25      ]
  [0.25       0.25       0.25       0.25      ]
  [0.25       0.25       0.25       0.25      ]]]
```
and i see my output of hdf5 file difference pb file
### this is my code i try to dumb freeze graph from hdf5 file 
```bash
def freeze_session(session, keep_var_names=None, output_names=None, clear_devices=True):
    """
    Freezes the state of a session into a pruned computation graph.

    Creates a new computation graph where variable nodes are replaced by
    constants taking their current value in the session. The new graph will be
    pruned so subgraphs that are not necessary to compute the requested
    outputs are removed.
    @param session The TensorFlow session to be frozen.
    @param keep_var_names A list of variable names that should not be frozen,
                          or None to freeze all the variables in the graph.
    @param output_names Names of the relevant graph outputs.
    @param clear_devices Remove the device directives from the graph for better portability.
    @return The frozen graph definition.
    """
    graph = session.graph
    with graph.as_default():
        freeze_var_names = list(set(v.op.name for v in tf.global_variables()).difference(keep_var_names or []))
        output_names = output_names or []
        output_names += [v.op.name for v in tf.global_variables()]
        input_graph_def = graph.as_graph_def()
        if clear_devices:
            for node in input_graph_def.node:
                node.device = ""
        frozen_graph = tf.graph_util.convert_variables_to_constants(
            session, input_graph_def, output_names, freeze_var_names)
        return frozen_graph

def freeze_graph_keras(net, model_dir):
    """Extract the sub graph defined by the output nodes and convert 
    all its variables into constant 
    Args:
        model_dir: the root folder containing the checkpoint state file
        output_node_names: a string, containing all the output node's names, 
                            comma separated
    """

    # The export path contains the name and the version of the model
    tf.keras.backend.set_learning_phase(0)  # Ignore dropout at inference
    file_name = os.path.basename(model_dir).replace('.hdf5', '.pb')
    model_dir = os.path.dirname(model_dir)
    print(os.path.join(model_dir, file_name))
    with tf.keras.backend.get_session() as sess:
        tf.initialize_all_variables().run()
        frozen_graph = freeze_session(K.get_session(),
                                      output_names=[out.op.name for out in net.outputs])
        tf.train.write_graph(frozen_graph, model_dir,
                             file_name, as_text=False)
    print('All input nodes:', net.inputs)
    print('All output nodes:', net.outputs)


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument("--model_dir", type=str,
                        default="path.hdf5", help="Model folder to export")

    args = parser.parse_args()                    

    model = build_my_model((256,320,3), num_classes=4,
                    lr_init=1e-3, lr_decay=5e-4)

    freeze_graph_keras(model, args.model_dir)
```
I'm using tensorflow version 1.14.0 and keras 2.2.4
