### ISSUE TITLE
Cannot load fashion_mnist

### ISSUE THREAD

**Issue by ongoing0217** [tensorflow/tensorflow#32314]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 Home 64bit
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 1.12
- Python version: 3.6.6
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 9.0/7.5
- GPU model and memory: GeForce 940M

**Describe the problem**
when I try to use the fashion_mnist dataset, it starts to read the data from the website, but after a while, the website shuts down my connection because I am connecting too often (WinError 10054).

**Provide the exact sequence of commands / steps that you executed before running into the problem**

```
import tensorflow as tf
from tensorflow import keras

fashion_mnist = keras.datasets.fashion_mnist

(train_images, train_labels),(test_images, test_labels) = fashion_mnist.load_data()
```

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

(it's loading...)

```
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\working as intended\python pls\love_copying_code_instead_of_writing_it_urself.py", line 6, in <module>
    (train_images, train_labels),(test_images, test_labels) = fashion_mnist.load_data()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\datasets\fashion_mnist.py", line 52, in load_data
    paths.append(get_file(fname, origin=base + fname, cache_subdir=dirname))
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\utils\data_utils.py", line 249, in get_file
    urlretrieve(origin, fpath, dl_progress)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 277, in urlretrieve
    block = fp.read(bs)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 449, in read
    n = self.readinto(b)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 493, in readinto
    n = self.fp.readinto(b)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
```

**Comment by gadagashwini** [comment]
Was able to execute the given code without any error on colab with Tensorflow 1.12.0. Please see the gist [here](https://colab.sandbox.google.com/gist/gadagashwini/b865119741330d3fd1a5ebcbb4f4d157/untitled128.ipynb). Thanks!

**Comment by ongoing0217** [comment]
it's very weird because I can run the code in colab but not on my own computer, so do I just turn to colab from now on?

**Comment by ymodak** [comment]
This looks like a proxy configuration issue where you are trying to connect from firewall corporate network. 
The workaround can be;
You can download the data from this link
https://www.kaggle.com/zalando-research/fashionmnist
Later you can use ```tf.keras.utils.get_file``` to load the dataset.
See,
https://www.tensorflow.org/api_docs/python/tf/keras/utils/get_file

**Comment by matdadi** [comment]
is this issue has solved?

**Comment by ongoing0217** [comment]
no, when I run the code above with the newest version of tensorflow, it gives a different error:
`OSError: Not a gzipped file (b'\x00\x00')`
