### ISSUE TITLE
Poisson random variable samples float instead of int, fails in hierarchical modeling as result

### ISSUE THREAD

**Issue by daniel-s-cunha** [tensorflow/tensorflow#32331]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes, derived from tf example.
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS Mojave 10.14.4
- **TensorFlow installed from (source or binary)**: pip
- **TensorFlow version (use command below)**: v1.14.0-rc1-22-gaf24dc91b5 1.14.0
- **Python version**: Python 3.7.3
- **Exact command to reproduce**: I am implementing a hierarchical model, where the value of the Poisson sample is used to determine the batch size of the normal distribution. Since the Poisson sample is a float, the MCMC step function treats it as a float. This results in incorrect mathematics for MCMC to work. In general, I cannot get this code to run.  

```python
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions
tfb = tfp.bijectors

rv_m = tfd.Poisson(rate=1.)
m    = rv_m.sample()

def joint_log_prob(m):
    rv_m    = tfd.Poisson(rate=1.)
    m_int   = tf.cast(m,'int32')
    rv_norm = tfd.Normal(loc=tf.zeros(m_int),scale=1.)
    return (-1.)

number_of_steps = 1000
burnin          = 0

initial_chain_state      = [m]
log_prob                 = lambda *args: joint_log_prob(*args)
[post_m], kernel_results = tfp.mcmc.sample_chain(num_results=number_of_steps,num_burnin_steps=burnin,current_state=initial_chain_state,kernel=tfp.mcmc.RandomWalkMetropolis(target_log_prob_fn=log_prob,seed=4))
```
### Source code / logs
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/dcunha/mutatio/lib/python3.7/site-packages/tensorflow_probability/python/mcmc/sample.py", line 361, in sample_chain
    parallel_iterations=parallel_iterations)
  File "/Users/dcunha/mutatio/lib/python3.7/site-packages/tensorflow_probability/python/mcmc/internal/util.py", line 370, in trace_scan
    parallel_iterations=parallel_iterations)
  File "/Users/dcunha/mutatio/lib/python3.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3501, in while_loop
    return_same_structure)
  File "/Users/dcunha/mutatio/lib/python3.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3012, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/Users/dcunha/mutatio/lib/python3.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2937, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/Users/dcunha/mutatio/lib/python3.7/site-packages/tensorflow_probability/python/mcmc/internal/util.py", line 359, in _body
    state = loop_fn(state, elems_array.read(i))
  File "/Users/dcunha/mutatio/lib/python3.7/site-packages/tensorflow_probability/python/mcmc/sample.py", line 345, in _trace_scan_fn
    parallel_iterations=parallel_iterations)
  File "/Users/dcunha/mutatio/lib/python3.7/site-packages/tensorflow_probability/python/mcmc/internal/util.py", line 286, in smart_for_loop
    parallel_iterations=parallel_iterations
  File "/Users/dcunha/mutatio/lib/python3.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3501, in while_loop
    return_same_structure)
  File "/Users/dcunha/mutatio/lib/python3.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3012, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/Users/dcunha/mutatio/lib/python3.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2937, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/Users/dcunha/mutatio/lib/python3.7/site-packages/tensorflow_probability/python/mcmc/internal/util.py", line 284, in <lambda>
    body=lambda i, *args: [i + 1] + list(body_fn(*args)),
  File "/Users/dcunha/mutatio/lib/python3.7/site-packages/tensorflow_probability/python/mcmc/random_walk_metropolis.py", line 440, in one_step
    return self._impl.one_step(current_state, previous_kernel_results)
  File "/Users/dcunha/mutatio/lib/python3.7/site-packages/tensorflow_probability/python/mcmc/metropolis_hastings.py", line 194, in one_step
    previous_kernel_results.accepted_results)
  File "/Users/dcunha/mutatio/lib/python3.7/site-packages/tensorflow_probability/python/mcmc/random_walk_metropolis.py", line 533, in one_step
    dtype=next_target_log_prob.dtype.base_dtype),
AttributeError: 'float' object has no attribute 'dtype'
```

**Comment by mihaimaruseac** [comment]
One suggestion: can you try with the 2.0 release? There have been changes in the API which might have solved this issue

**Comment by daniel-s-cunha** [comment]
Sure, I installed and tried 2.0 release, and receive the same error.

**Comment by mihaimaruseac** [comment]
Seems to be an error from [TensorFlow Probability](https://github.com/tensorflow/probability). Can you please open an issue there instead?

**Comment by daniel-s-cunha** [comment]
Great, I logged the issue here:
https://github.com/tensorflow/probability/issues/553

Thank you for your help.
