### ISSUE TITLE
tensorboard gives ValueError: Duplicate plugins for name projector

### ISSUE THREAD

**Issue by ljstrnadiii** [tensorflow/tensorflow#32384]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS 10.14.5
- TensorFlow installed from (source or binary): `pip install tensorflow==1.14.0`
- TensorFlow version (use command below): 1.14.0
- Python version: 3.7.4 with virtualenv

**Describe the current behavior**
When I try to run `tensorboard --logdir=.` I get this ValueError: Duplicate plugins for name projector
**Describe the expected behavior**
Tensorboard should launch
**Code to reproduce the issue**
`tensorboard --logdir=.` 

**Other info / logs**
Ideally, I would ultimately like to run ` tensorboard --logdir=gs://[bucket_name]`, but I have not even been able to use tensorboard for models with logdirs that are local. 
```
Traceback (most recent call last):
  File "/Users/len/research/.venv/bin/tensorboard", line 10, in <module>
    sys.exit(run_main())
  File "/Users/len/research/.venv/lib/python3.7/site-packages/tensorboard/main.py", line 64, in run_main
    app.run(tensorboard.main, flags_parser=tensorboard.configure)
  File "/Users/len/research/.venv/lib/python3.7/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/Users/len/research/.venv/lib/python3.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/Users/len/research/.venv/lib/python3.7/site-packages/tensorboard/program.py", line 228, in main
    server = self._make_server()
  File "/Users/len/research/.venv/lib/python3.7/site-packages/tensorboard/program.py", line 309, in _make_server
    self.assets_zip_provider)
  File "/Users/len/research/.venv/lib/python3.7/site-packages/tensorboard/backend/application.py", line 161, in standard_tensorboard_wsgi
    reload_task)
  File "/Users/len/research/.venv/lib/python3.7/site-packages/tensorboard/backend/application.py", line 194, in TensorBoardWSGIApp
    return TensorBoardWSGI(plugins, path_prefix)
  File "/Users/len/research/.venv/lib/python3.7/site-packages/tensorboard/backend/application.py", line 245, in __init__
    raise ValueError('Duplicate plugins for name %s' % plugin.plugin_name)
ValueError: Duplicate plugins for name projector
```

**Comment by jvishnuvardhan** [comment]
@ljstrnadiii Please post tensorboard related questions in [tensorboard repo here](https://github.com/tensorflow/tensorboard/issues). When you post there, please post the issue and a standalone code to reproduce the issue. Thanks!

**Comment by GoingMyWay** [comment]
Refer to https://github.com/pytorch/pytorch/issues/22676
