### ISSUE TITLE
cudaGetDevice() failed. Status: cudaGetErrorString symbol not found.

### ISSUE THREAD

**Issue by thulani196** [tensorflow/tensorflow#32381]
After installing Cuda 10.1 and CuDNN, I am getting above error when testing if tensorflow 2.0 can recognize my GPU, I am using a GTX 1060, on Windows 10.

I am trying to run:
`tf.test.is_gpu_available(
    cuda_only=False,
    min_cuda_compute_capability=None
)`

**Comment by assulthoni** [comment]
CUDA 10.1 is still not working?

**Comment by FlashAJ** [comment]
> CUDA 10.1 is still not working?

No, bro.

**Comment by coffeeshop13** [comment]
> > CUDA 10.1 is still not working?
> 
> No, bro.

Same for the TF 1.14?

**Comment by marboe123** [comment]
I have the same error while running a deep-learning Keras R-script with tensorflow 2.0 using a GTX 1060, on Windows 10.

I don't know my CUDA version.

I did used these steps to install Tensorflow-GPU which was running correct with the Jupyter example:

https://www.thehardwareguy.co.uk/install-tensorflow-gpu

After this:
I installed rstudio in the environment.
I installed Keras
I runned the deep learing Keras R-script.

The resulting error is:

```
2019-11-12 20:29:52.578326: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce GTX 1060 6GB major: 6 minor: 1 memoryClockRate(GHz): 1.7715
pciBusID: 0000:01:00.0
2019-11-12 20:29:52.578649: I tensorflow/stream_executor/platform/default/dlopen_checker_stub.cc:25] GPU libraries are statically linked, skip dlopen check.
2019-11-12 20:29:52.579733: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
 Show Traceback
 
 Rerun with Debug
 Error in py_call_impl(callable, dots$args, dots$keywords) : 
  InternalError: cudaGetDevice() failed. Status: cudaGetErrorString symbol not found. 
> tf.test.is_gpu_available( cuda_only=False, min_cuda_compute_capability=None )
Error in tf.test.is_gpu_available(cuda_only = False, min_cuda_compute_capability = None) : 
  could not find function "tf.test.is_gpu_available"

```

**Comment by marboe123** [comment]
If I am correct my CUDA version is 10.020. Pls see below:


```
__Python Information__
Python Compiler                               : MSC v.1915 64 bit (AMD64)
Python Implementation                         : CPython
Python Version                                : 3.6.9
Python Locale                                 : en_NL cp1252

__LLVM information__
LLVM version                                  : 8.0.0

__CUDA Information__
Found 1 CUDA devices
id 0    b'GeForce GTX 1060 6GB'                              [SUPPORTED]
                      compute capability: 6.1
                           pci device id: 0
                              pci bus id: 1
Summary:
        1/1 devices are supported
CUDA driver version                           : 10020
CUDA libraries:
Finding cublas from <unavailable>
        ERROR: can't locate lib
Finding cusparse from <unavailable>
        ERROR: can't locate lib
Finding cufft from <unavailable>
        ERROR: can't locate lib
Finding curand from <unavailable>
        ERROR: can't locate lib
Finding nvvm from <unavailable>
        ERROR: can't locate lib
Finding libdevice from <unavailable>
        searching for compute_20...     ERROR: can't open libdevice for compute_20
        searching for compute_30...     ERROR: can't open libdevice for compute_30
        searching for compute_35...     ERROR: can't open libdevice for compute_35
        searching for compute_50...     ERROR: can't open libdevice for compute_50
```

**Comment by florianbaer** [comment]
Wtf seriously? When is support for cuda 10.1 planned?

**Comment by JasperGeurtz** [comment]
copying only `cudart64_100.dll` from a 10.0 installation into the 10.1 `bin` folder seems to work (as a workaround until 10.1 support is added)

**Comment by Meerer** [comment]
I have cuda 10.0.130 and I get the same error with a Gtx 1070 on Windows 10

**Comment by eemberda** [comment]
> copying only `cudart64_100.dll` from a 10.0 installation into the 10.1 `bin` folder seems to work (as a workaround until 10.1 support is added)

This worked for me too. Then for all other functions that are deprecated, I used tf.compat.v1 or tf.compat.v2

**Comment by abhinavg86** [comment]
> I have cuda with version 10.0.130 and I get the same error with a Gtx 1070 on Windows 10.

Were you able to fix it? I am facing the same problems, have the same config as yours.

**Comment by xufangda** [comment]
Same for me, please fix it

**Comment by Taif85** [comment]
i have the same error !! did any one fix it?

**Comment by Jwer-chen** [comment]
I have get the same error too!who can help me?

**Comment by yptheangel** [comment]
I got it working by using CUDA10.0 instead of CUDA10.1. Note that you can have two CUDA versions at the same time, make sure your CUDA_PATH is pointing to CUDA10.0.
![twoCUDAatTheSameTime](https://user-images.githubusercontent.com/30103695/71420615-3183a780-26b1-11ea-8fc1-90a36b5ddced.PNG)

You can download archived CUDA10.0 from [here](https://developer.nvidia.com/cuda-10.0-download-archive?target_os=Windows&target_arch=x86_64&target_version=10&target_type=exelocal)

you can verify if you GPU is available for training with this code snippet 

```
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())
```

reference [here](https://medium.com/@choowilson93/how-to-verify-cuda-and-cudnn-installation-d56a89bab0a8)

**Comment by lonelyXeno** [comment]
I got the same problem while running my Keras code in Jupyter Notebook....

**Comment by yanz20** [comment]
I have the same problem, using tensorflow-gpu==2.0 and CUDA10.0, Graphic card is RTX 2070:

print(device_lib.list_local_devices())
2020-02-14 00:35:15.639841: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties:
name: GeForce RTX 2070 major: 7 minor: 5 memoryClockRate(GHz): 1.62
pciBusID: 0000:01:00.0
2020-02-14 00:35:15.643490: I tensorflow/stream_executor/platform/default/dlopen_checker_stub.cc:25] GPU libraries are statically linked, skip dlopen check.
2020-02-14 00:35:15.646311: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\fredd\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\tensorflow_core\python\client\device_lib.py", line 41, in list_local_devices
    for s in pywrap_tensorflow.list_devices(session_config=session_config)
  File "C:\Users\fredd\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 2249, in list_devices
    return ListDevices()
tensorflow.python.framework.errors_impl.InternalError: cudaGetDevice() failed. Status: cudaGetErrorString symbol not found.

Can anybody help?
