### ISSUE TITLE
tensorflow installation windows 10 python idle 3.6

### ISSUE THREAD

**Issue by rahul21rajendran** [tensorflow/tensorflow#32388]
C:\WINDOWS\system32>python
Python 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
Traceback (most recent call last):
  File "C:\Users\RAHUL\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\pywrap_tensorflow.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tensorflow', [dirname(__file__)])
  File "C:\Users\RAHUL\AppData\Local\Programs\Python\Python36\lib\imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tensorflow'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\RAHUL\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\__init__.py", line 54, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\RAHUL\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "C:\Users\RAHUL\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\pywrap_tensorflow.py", line 20, in swig_import_helper
    import _pywrap_tensorflow
ModuleNotFoundError: No module named '_pywrap_tensorflow'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\RAHUL\AppData\Roaming\Python\Python36\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "C:\Users\RAHUL\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\__init__.py", line 60, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\RAHUL\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\pywrap_tensorflow.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tensorflow', [dirname(__file__)])
  File "C:\Users\RAHUL\AppData\Local\Programs\Python\Python36\lib\imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tensorflow'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\RAHUL\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\__init__.py", line 54, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\RAHUL\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "C:\Users\RAHUL\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\pywrap_tensorflow.py", line 20, in swig_import_helper
    import _pywrap_tensorflow
ModuleNotFoundError: No module named '_pywrap_tensorflow'

Error importing tensorflow.  Unless you are using bazel,
you should not try to import tensorflow from its source directory;
please exit the tensorflow source tree, and relaunch your python interpreter
from there.
>>> exit()

C:\WINDOWS\system32>rm -rf
'rm' is not recognized as an internal or external command,
operable program or batch file.

**Comment by oanush** [comment]
@rahul21rajendran ,
Looks like there is some issue with installation of python and tensorflow, can you uninstall and try reinstalling the both?

**Comment by roca77** [comment]
Hi guys, 
I am having a similar issue on Mac while using a virtualenv. Any help would be greatly appreaciated:
```

(mlocad) (base) youssouf-traores-macbook-pro:retraining Youssoufj$ python retrain.py --image_dir ~/flower_photos
Traceback (most recent call last):
  File "/Users/Youssoufj/Projects/tensorf/retrain/september/retraining/mlocad/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/Users/Youssoufj/Projects/tensorf/retrain/september/retraining/mlocad/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/Users/Youssoufj/Projects/tensorf/retrain/september/retraining/mlocad/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/Users/Youssoufj/Projects/tensorf/retrain/september/retraining/mlocad/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/Users/Youssoufj/Projects/tensorf/retrain/september/retraining/mlocad/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: dlopen(/Users/Youssoufj/Projects/tensorf/retrain/september/retraining/mlocad/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 6): Symbol not found: _SecKeyCopyExternalRepresentation
  Referenced from: /Users/Youssoufj/Projects/tensorf/retrain/september/retraining/mlocad/lib/python3.7/site-packages/tensorflow/python/../libtensorflow_framework.1.dylib
  Expected in: /System/Library/Frameworks/Security.framework/Versions/A/Security
 in /Users/Youssoufj/Projects/tensorf/retrain/september/retraining/mlocad/lib/python3.7/site-packages/tensorflow/python/../libtensorflow_framework.1.dylib

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "retrain.py", line 131, in <module>
    import tensorflow as tf
  File "/Users/Youssoufj/Projects/tensorf/retrain/september/retraining/mlocad/lib/python3.7/site-packages/tensorflow/__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/Users/Youssoufj/Projects/tensorf/retrain/september/retraining/mlocad/lib/python3.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/Users/Youssoufj/Projects/tensorf/retrain/september/retraining/mlocad/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/Users/Youssoufj/Projects/tensorf/retrain/september/retraining/mlocad/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/Users/Youssoufj/Projects/tensorf/retrain/september/retraining/mlocad/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/Users/Youssoufj/Projects/tensorf/retrain/september/retraining/mlocad/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/Users/Youssoufj/Projects/tensorf/retrain/september/retraining/mlocad/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/Users/Youssoufj/Projects/tensorf/retrain/september/retraining/mlocad/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: dlopen(/Users/Youssoufj/Projects/tensorf/retrain/september/retraining/mlocad/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 6): Symbol not found: _SecKeyCopyExternalRepresentation
  Referenced from: /Users/Youssoufj/Projects/tensorf/retrain/september/retraining/mlocad/lib/python3.7/site-packages/tensorflow/python/../libtensorflow_framework.1.dylib
  Expected in: /System/Library/Frameworks/Security.framework/Versions/A/Security
 in /Users/Youssoufj/Projects/tensorf/retrain/september/retraining/mlocad/lib/python3.7/site-packages/tensorflow/python/../libtensorflow_framework.1.dylib


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

**Comment by rahul21rajendran** [comment]
Thank you for your support

**Comment by oanush** [comment]
@rahul21rajendran,
Can you please let us know if the issue was resolved so that we can proceed for closure.Thanks!

**Comment by rahul21rajendran** [comment]
my issue is solved

**Comment by reliefs** [comment]
https://github.com/tensorflow/tensorflow/issues/32627
