### ISSUE TITLE
The name "resnet50" is used 2 times in the model.

### ISSUE THREAD

**Issue by Xie-Fangyuan** [tensorflow/tensorflow#32408]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): **yes**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Ubuntu 18.04**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): **binary**
- TensorFlow version (use command below): **tensorflow-gpu 1.14.0**
- Python version: **3.7.3**
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: 

---

when i try to use more than one `keras.application.ResNet50` in my model, there shows a `ValueError: The name "resnet50" is used 2 times in the model. All layer names should be unique.` and i checked tensorflow's source code, the model name is unchangable.

here is my test code:

```python
from tensorflow.compat.v1 import enable_eager_execution
from tensorflow.keras.layers import Concatenate, Dense, Input
from tensorflow.keras.models import Model
from tensorflow.keras.applications import ResNet50

import os

enable_eager_execution()
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"

res_net = ResNet50(include_top=False, input_shape=(224, 224, 3))
res_net2 = ResNet50(include_top=False, input_shape=(224, 224, 3))

x = Input(shape=(224, 224, 3), name='input')
y = res_net(x)
z = res_net2(x)
z = Dense(1, name='output')(Concatenate(axis=-1)([y, z]))

model = Model([x], [z])
```

and here is the logs:

```text
Traceback (most recent call last):
  File "draft.py", line 19, in <module>
    model = Model([x], [z])
  File "/home/xiefangyuan/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 129, in __init__
    super(Model, self).__init__(*args, **kwargs)
  File "/home/xiefangyuan/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/network.py", line 162, in __init__
    self._init_graph_network(*args, **kwargs)
  File "/home/xiefangyuan/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/home/xiefangyuan/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/network.py", line 315, in _init_graph_network
    self.inputs, self.outputs)
  File "/home/xiefangyuan/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/network.py", line 1862, in _map_graph_network
    str(all_names.count(name)) + ' times in the model. '
ValueError: The name "resnet50" is used 2 times in the model. All layer names should be unique.
```

and hee is tensorflow's source code at line 274 in `keras_applications\resnet50.py`:

```pyton
# Create model.
model = models.Model(inputs, x, name='resnet50')
```

i think sometimes we need to change the model's name.

**Comment by Xie-Fangyuan** [comment]
i think i just found the solution.

```python
from tensorflow.compat.v1 import enable_eager_execution
from tensorflow.keras.layers import Concatenate, Dense, Input
from tensorflow.keras.models import Model
from tensorflow.keras.applications import ResNet50

import os

enable_eager_execution()
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"

res_net = ResNet50(include_top=False, input_shape=(224, 224, 3), pooling='avg')

res_net = Model(inputs=res_net.input, outputs=res_net.get_layer('activation_39').output, name='resnet50_1')
res_net2 = Model(inputs=res_net.input, outputs=res_net.get_layer('activation_39').output,  name='resnet50_2')

x = Input(shape=(224, 224, 3), name='input')
y = res_net(x)
z = res_net2(x)
z = Dense(1, name='output')(Concatenate(axis=-1)([y, z]))

model = Model([x], [z])
```

i create new models and use the specific inputs layers and outputs layers. i can also change the name of my models.
