### ISSUE TITLE
AutoGraph could not transform pfor when using GradientTape.jacobian

### ISSUE THREAD

**Issue by dovahcrow** [tensorflow/tensorflow#32448]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): **Yes**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Linux Ubuntu 16.04.6 LTS**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): **source**
- TensorFlow version (use command below): **v2.0.0-rc0-0-gc75bb66**
- Python version: **3.7**
- Bazel version (if compiling from source): **0.25.2**
- GCC/Compiler version (if compiling from source): **5.4.0 20160609**
- CUDA/cuDNN version: **No**
- GPU model and memory: **No**

**Describe the current behavior**
`GradientTape.jacobian` is showing warnings about `WARNING:tensorflow:Entity <function pfor.<locals>.f at 0x7f5e7807af28> could not be transformed and will be executed as-is. `

**Describe the expected behavior**
No warnings shown.

**Code to reproduce the issue**

```python
import tensorflow as tf

W = tf.random.normal((6,1), dtype=tf.float32)
with tf.GradientTape() as tape:
    y = tf.reduce_sum(W ** 3)
tape.jacobian(y, W)
```
**Other info / logs**

logs by setting `AUTOGRAPH_VERBOSITY=10`

```
INFO:tensorflow:Converted call: <function pfor.<locals>.f at 0x7f5e7807af28>
    args: ()
    kwargs: {}

Converted call: <function pfor.<locals>.f at 0x7f5e7807af28>
    args: ()
    kwargs: {}

INFO:tensorflow:Entity <function pfor.<locals>.f at 0x7f5e7807af28> is not cached for key <code object f at 0x7f5deb7a2390, file "/home/youngw/.local/share/virtualenvs/DebugML-YyVGQQuJ/lib/python3.7/site-packages/tensorflow_core/python/ops/parallel_for/control_flow_ops.py", line 183> subkey (<tensorflow.python.autograph.core.converter.ConversionOptions object at 0x7f5dd8004eb8>, frozenset({'loop_fn', 'parallel_iterations', 'iters'}))
Entity <function pfor.<locals>.f at 0x7f5e7807af28> is not cached for key <code object f at 0x7f5deb7a2390, file "/home/youngw/.local/share/virtualenvs/DebugML-YyVGQQuJ/lib/python3.7/site-packages/tensorflow_core/python/ops/parallel_for/control_flow_ops.py", line 183> subkey (<tensorflow.python.autograph.core.converter.ConversionOptions object at 0x7f5dd8004eb8>, frozenset({'loop_fn', 'parallel_iterations', 'iters'}))
INFO:tensorflow:Converting <function pfor.<locals>.f at 0x7f5e7807af28>
Converting <function pfor.<locals>.f at 0x7f5e7807af28>
INFO:tensorflow:Source code of <function pfor.<locals>.f at 0x7f5e7807af28>:

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
def f():
  return _pfor_impl(loop_fn, iters, parallel_iterations=parallel_iterations)


Source code of <function pfor.<locals>.f at 0x7f5e7807af28>:

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
def f():
  return _pfor_impl(loop_fn, iters, parallel_iterations=parallel_iterations)


INFO:tensorflow:Error transforming entity <function pfor.<locals>.f at 0x7f5e7807af28>
Traceback (most recent call last):
  File "/home/youngw/.local/share/virtualenvs/DebugML-YyVGQQuJ/lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/api.py", line 506, in converted_call
    converted_f = conversion.convert(target_entity, program_ctx)
  File "/home/youngw/.local/share/virtualenvs/DebugML-YyVGQQuJ/lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/conversion.py", line 322, in convert
    free_nonglobal_var_names)
  File "/home/youngw/.local/share/virtualenvs/DebugML-YyVGQQuJ/lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/conversion.py", line 240, in _convert_with_cache
    entity, program_ctx)
  File "/home/youngw/.local/share/virtualenvs/DebugML-YyVGQQuJ/lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/conversion.py", line 469, in convert_entity_to_ast
    nodes, name, entity_info = convert_func_to_ast(o, program_ctx)
  File "/home/youngw/.local/share/virtualenvs/DebugML-YyVGQQuJ/lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/conversion.py", line 669, in convert_func_to_ast
    node = node_to_graph(node, context)
  File "/home/youngw/.local/share/virtualenvs/DebugML-YyVGQQuJ/lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/conversion.py", line 699, in node_to_graph
    node = converter.apply_(node, context, function_scopes)
  File "/home/youngw/.local/share/virtualenvs/DebugML-YyVGQQuJ/lib/python3.7/site-packages/tensorflow_core/python/autograph/core/converter.py", line 409, in apply_
    node = converter_module.transform(node, context)
  File "/home/youngw/.local/share/virtualenvs/DebugML-YyVGQQuJ/lib/python3.7/site-packages/tensorflow_core/python/autograph/converters/function_scopes.py", line 120, in transform
    return FunctionBodyTransformer(ctx).visit(node)
  File "/home/youngw/.local/share/virtualenvs/DebugML-YyVGQQuJ/lib/python3.7/site-packages/tensorflow_core/python/autograph/core/converter.py", line 346, in visit
    return super(Base, self).visit(node)
  File "/home/youngw/.local/share/virtualenvs/DebugML-YyVGQQuJ/lib/python3.7/site-packages/tensorflow_core/python/autograph/pyct/transformer.py", line 480, in visit
    result = super(Base, self).visit(node)
  File "/home/youngw/.pyenv/versions/3.7.2/lib/python3.7/ast.py", line 262, in visit
    return visitor(node)
  File "/home/youngw/.local/share/virtualenvs/DebugML-YyVGQQuJ/lib/python3.7/site-packages/tensorflow_core/python/autograph/converters/function_scopes.py", line 87, in visit_FunctionDef
    node = self.generic_visit(node)
  File "/home/youngw/.pyenv/versions/3.7.2/lib/python3.7/ast.py", line 317, in generic_visit
    value = self.visit(value)
  File "/home/youngw/.local/share/virtualenvs/DebugML-YyVGQQuJ/lib/python3.7/site-packages/tensorflow_core/python/autograph/core/converter.py", line 346, in visit
    return super(Base, self).visit(node)
  File "/home/youngw/.local/share/virtualenvs/DebugML-YyVGQQuJ/lib/python3.7/site-packages/tensorflow_core/python/autograph/pyct/transformer.py", line 480, in visit
    result = super(Base, self).visit(node)
  File "/home/youngw/.pyenv/versions/3.7.2/lib/python3.7/ast.py", line 262, in visit
    return visitor(node)
  File "/home/youngw/.local/share/virtualenvs/DebugML-YyVGQQuJ/lib/python3.7/site-packages/tensorflow_core/python/autograph/converters/function_scopes.py", line 44, in visit_Return
    value=node.value)
  File "/home/youngw/.local/share/virtualenvs/DebugML-YyVGQQuJ/lib/python3.7/site-packages/tensorflow_core/python/autograph/pyct/templates.py", line 261, in replace
    replacements[k] = _convert_to_ast(replacements[k])
  File "/home/youngw/.local/share/virtualenvs/DebugML-YyVGQQuJ/lib/python3.7/site-packages/tensorflow_core/python/autograph/pyct/templates.py", line 223, in _convert_to_ast
    return gast.Name(id=n, ctx=None, annotation=None)
  File "/home/youngw/.local/share/virtualenvs/DebugML-YyVGQQuJ/lib/python3.7/site-packages/gast/gast.py", line 19, in create_node
    format(Name, nbparam, len(Fields))
AssertionError: Bad argument number for Name: 3, expecting 4
Error transforming entity <function pfor.<locals>.f at 0x7f5e7807af28>
WARNING:tensorflow:Entity <function pfor.<locals>.f at 0x7f5e7807af28> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: Bad argument number for Name: 3, expecting 4
WARNING: Entity <function pfor.<locals>.f at 0x7f5e7807af28> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: Bad argument number for Name: 3, expecting 4
Traceback (most recent call last):
  File "/home/youngw/.local/share/virtualenvs/DebugML-YyVGQQuJ/lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/api.py", line 506, in converted_call
    converted_f = conversion.convert(target_entity, program_ctx)
  File "/home/youngw/.local/share/virtualenvs/DebugML-YyVGQQuJ/lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/conversion.py", line 322, in convert
    free_nonglobal_var_names)
  File "/home/youngw/.local/share/virtualenvs/DebugML-YyVGQQuJ/lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/conversion.py", line 240, in _convert_with_cache
    entity, program_ctx)
  File "/home/youngw/.local/share/virtualenvs/DebugML-YyVGQQuJ/lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/conversion.py", line 469, in convert_entity_to_ast
    nodes, name, entity_info = convert_func_to_ast(o, program_ctx)
  File "/home/youngw/.local/share/virtualenvs/DebugML-YyVGQQuJ/lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/conversion.py", line 669, in convert_func_to_ast
    node = node_to_graph(node, context)
  File "/home/youngw/.local/share/virtualenvs/DebugML-YyVGQQuJ/lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/conversion.py", line 699, in node_to_graph
    node = converter.apply_(node, context, function_scopes)
  File "/home/youngw/.local/share/virtualenvs/DebugML-YyVGQQuJ/lib/python3.7/site-packages/tensorflow_core/python/autograph/core/converter.py", line 409, in apply_
    node = converter_module.transform(node, context)
  File "/home/youngw/.local/share/virtualenvs/DebugML-YyVGQQuJ/lib/python3.7/site-packages/tensorflow_core/python/autograph/converters/function_scopes.py", line 120, in transform
    return FunctionBodyTransformer(ctx).visit(node)
  File "/home/youngw/.local/share/virtualenvs/DebugML-YyVGQQuJ/lib/python3.7/site-packages/tensorflow_core/python/autograph/core/converter.py", line 346, in visit
    return super(Base, self).visit(node)
  File "/home/youngw/.local/share/virtualenvs/DebugML-YyVGQQuJ/lib/python3.7/site-packages/tensorflow_core/python/autograph/pyct/transformer.py", line 480, in visit
    result = super(Base, self).visit(node)
  File "/home/youngw/.pyenv/versions/3.7.2/lib/python3.7/ast.py", line 262, in visit
    return visitor(node)
  File "/home/youngw/.local/share/virtualenvs/DebugML-YyVGQQuJ/lib/python3.7/site-packages/tensorflow_core/python/autograph/converters/function_scopes.py", line 87, in visit_FunctionDef
    node = self.generic_visit(node)
  File "/home/youngw/.pyenv/versions/3.7.2/lib/python3.7/ast.py", line 317, in generic_visit
    value = self.visit(value)
  File "/home/youngw/.local/share/virtualenvs/DebugML-YyVGQQuJ/lib/python3.7/site-packages/tensorflow_core/python/autograph/core/converter.py", line 346, in visit
    return super(Base, self).visit(node)
  File "/home/youngw/.local/share/virtualenvs/DebugML-YyVGQQuJ/lib/python3.7/site-packages/tensorflow_core/python/autograph/pyct/transformer.py", line 480, in visit
    result = super(Base, self).visit(node)
  File "/home/youngw/.pyenv/versions/3.7.2/lib/python3.7/ast.py", line 262, in visit
    return visitor(node)
  File "/home/youngw/.local/share/virtualenvs/DebugML-YyVGQQuJ/lib/python3.7/site-packages/tensorflow_core/python/autograph/converters/function_scopes.py", line 44, in visit_Return
    value=node.value)
  File "/home/youngw/.local/share/virtualenvs/DebugML-YyVGQQuJ/lib/python3.7/site-packages/tensorflow_core/python/autograph/pyct/templates.py", line 261, in replace
    replacements[k] = _convert_to_ast(replacements[k])
  File "/home/youngw/.local/share/virtualenvs/DebugML-YyVGQQuJ/lib/python3.7/site-packages/tensorflow_core/python/autograph/pyct/templates.py", line 223, in _convert_to_ast
    return gast.Name(id=n, ctx=None, annotation=None)
  File "/home/youngw/.local/share/virtualenvs/DebugML-YyVGQQuJ/lib/python3.7/site-packages/gast/gast.py", line 19, in create_node
    format(Name, nbparam, len(Fields))
AssertionError: Bad argument number for Name: 3, expecting 4
```

**Comment by mshlis** [comment]
getting same issue, any resolve? (though mine does run, and it runs way quicker than w/o tf.function but still annoying to see this each time)

**Comment by dovahcrow** [comment]
@mshlis I think I found the bug. The current Tensorflow implementation assumes `gast==0.2.2` but doesn't lock in the version. The newest `gast` is 0.3.0 which introduced some breaking changes. In order to fix this just run `pip install -U gast==0.2.2`.

**Comment by goldiegadde** [comment]
yes, gast version was updated on 9/7/19 and does introduce breaking changes. set to 0.2.2, but the next rc and final release will have this.  The r2.0 branch has been updated with the gast version set to 0.2.2. if you want to build again.

**Comment by oanush** [comment]
@dovahcrow ,
Just let us know can the issue be closed as the solution is found? Thanks!

**Comment by falaktheoptimist** [comment]
Similar problem faced, but with a different function being used in the onset_frames model (https://github.com/tensorflow/magenta/tree/master/magenta/models/onsets_frames_transcription) in magenta. Some sox functions are being called to transform wav data (See audio_transform.py at the above link). The full log with verbosity=10 is too long to paste in here, but the gist is as follows:

> WARNING:tensorflow:Entity <bound method Popen._communicate of <subprocess.Popen object at 0x7fdac7adaa20>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: 
W1104 14:27:51.073054 140575974086400 ag_logging.py:146] Entity <bound method Popen._communicate of <subprocess.Popen object at 0x7fdac7adaa20>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: 
output_file: /tmp/tmpldd7_qhn.wav already exists and will be overwritten on build
W1104 14:27:51.089764 140575974086400 api.py:546] output_file: /tmp/tmpldd7_qhn.wav already exists and will be overwritten on build
I1104 14:27:51.103564 140575974086400 api.py:546] Executing: sox -D -G -V2 /tmp/tmpsh85acsd.wav /tmp/tmpldd7_qhn.wav pitch -7.682483 contrast 78.521843 equalizer 32.158569 2.000000q -2.897976 equalizer 2681.614259 2.000000q -1.408564 reverb 5.793800 50.000000 100.000000 100.000000 0.000000 0.000000
WARNING:tensorflow:Entity <bound method Popen._communicate of <subprocess.Popen object at 0x7fdac7c41b38>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: 
W1104 14:27:51.188622 140575974086400 ag_logging.py:146] Entity <bound method Popen._communicate of <subprocess.Popen object at 0x7fdac7c41b38>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: 
I1104 14:27:51.221368 140575974086400 api.py:546] Created /tmp/tmpldd7_qhn.wav with effects: pitch contrast equalizer equalizer reverb

This goes on filling the buffer and finally results in OOM error on Nvidia Titan X
