### ISSUE TITLE
Unimplemented: this graph contains an operator of type Abs for which the quantized form is not yet implemented

### ISSUE THREAD

**Issue by dipali-ruchier** [tensorflow/tensorflow#32452]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No. Got Insightface trained model directly from https://drive.google.com/open?id=1Iw2Ckz_BnHZUi78USlaFreZXylJj7hnP
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: NA
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: v1.12.1-9365-gff401a6 1.15.0-dev20190821
- **Python version**: 3.5.2
- **Bazel version (if compiling from source)**: Not installed
- **GCC/Compiler version (if compiling from source)**: c++ (Ubuntu 8.1.0-5ubuntu1~16.04) 8.1.0
- **CUDA/cuDNN version**: CPU only
- **GPU model and memory**: CPU only
- **Exact command to reproduce**: tflite_convert \
--output_file=insightface_quant.tflite \
--graph_def_file=insightface.pb \
--inference_type=QUANTIZED_UINT8 \
--mean_values=128 \
--std_dev_values=128 \
--input_arrays=img_inputs \
--output_arrays=resnet_v1_50/E_BN2/Identity \
--default_range_min=0 \
--default_range_max=127

### Describe the problem
I am trying to convert insightface pre-trained model so that I can run it on EdgeTPU. First, I am trying to convert the .pb model into tflite model with both weights and activations quantized to 8bit integer. That's when I get the error below. Is the support for operator Abs coming soon?
2019-09-11 16:41:12.872535: W tensorflow/lite/toco/graph_transformations/quantize.cc:139] Constant array resnet_v1_50/conv1/W_conv2d lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2019-09-11 16:41:12.872690: F ./tensorflow/lite/toco/toco_tooling.h:38] Check failed: s.ok() Unimplemented: this graph contains an operator of type Abs for which the quantized form is not yet implemented. Sorry, and patches welcome (that's a relatively fun patch to write, mostly providing the actual quantized arithmetic code for this op).
Fatal Python error: Aborted

### Source code / logs
WARNING: Logging before flag parsing goes to stderr.
W0911 16:39:50.219565 140227897026304 __init__.py:690] 

  TensorFlow's `tf-nightly` package will soon be updated to TensorFlow 2.0.

  Please upgrade your code to TensorFlow 2.0:
    * https://www.tensorflow.org/beta/guide/migration_guide

  Or install the latest stable TensorFlow 1.X release:
    * `pip install -U "tensorflow==1.*"`

  Otherwise your code may be broken by the change.

  
2019-09-11 16:39:50.225242: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-09-11 16:39:50.246574: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3504000000 Hz
2019-09-11 16:39:50.246796: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x490a580 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2019-09-11 16:39:50.246817: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Traceback (most recent call last):
  File "/home/crossbar/.local/bin/tflite_convert", line 10, in <module>
    sys.exit(main())
  File "/home/crossbar/.local/lib/python3.5/site-packages/tensorflow_core/lite/python/tflite_convert.py", line 515, in main
    app.run(main=run_main, argv=sys.argv[:1])
  File "/home/crossbar/.local/lib/python3.5/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/crossbar/.local/lib/python3.5/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/crossbar/.local/lib/python3.5/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/home/crossbar/.local/lib/python3.5/site-packages/tensorflow_core/lite/python/tflite_convert.py", line 511, in run_main
    _convert_tf1_model(tflite_flags)
  File "/home/crossbar/.local/lib/python3.5/site-packages/tensorflow_core/lite/python/tflite_convert.py", line 199, in _convert_tf1_model
    output_data = converter.convert()
  File "/home/crossbar/.local/lib/python3.5/site-packages/tensorflow_core/lite/python/lite.py", line 983, in convert
    **converter_kwargs)
  File "/home/crossbar/.local/lib/python3.5/site-packages/tensorflow_core/lite/python/convert.py", line 449, in toco_convert_impl
    enable_mlir_converter=enable_mlir_converter)
  File "/home/crossbar/.local/lib/python3.5/site-packages/tensorflow_core/lite/python/convert.py", line 200, in toco_convert_protos
    raise ConverterError("See console for info.\n%s\n%s\n" % (stdout, stderr))
tensorflow.lite.python.convert.ConverterError: See console for info.
WARNING: Logging before flag parsing goes to stderr.
W0911 16:39:52.657464 140689256613632 __init__.py:690] 

  TensorFlow's `tf-nightly` package will soon be updated to TensorFlow 2.0.

  Please upgrade your code to TensorFlow 2.0:
    * https://www.tensorflow.org/beta/guide/migration_guide

  Or install the latest stable TensorFlow 1.X release:
    * `pip install -U "tensorflow==1.*"`

  Otherwise your code may be broken by the change.

  
2019-09-11 16:39:53.139500: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 1363 operators, 1866 arrays (0 quantized)
2019-09-11 16:39:53.171158: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 1363 operators, 1866 arrays (0 quantized)
2019-09-11 16:39:53.395100: W tensorflow/lite/toco/graph_transformations/resolve_constant_random_uniform.cc:88] RandomUniform op outputting "resnet_v1_50/E_Dropout/random_uniform/RandomUniform" is truly random (using /dev/random system entropy). Therefore, cannot resolve as constant. Set "seed" or "seed2" attr non-zero to fix this
2019-09-11 16:39:53.398795: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 1: 292 operators, 508 arrays (1 quantized)
2019-09-11 16:39:53.536832: W tensorflow/lite/toco/graph_transformations/resolve_constant_random_uniform.cc:88] RandomUniform op outputting "resnet_v1_50/E_Dropout/random_uniform/RandomUniform" is truly random (using /dev/random system entropy). Therefore, cannot resolve as constant. Set "seed" or "seed2" attr non-zero to fix this
2019-09-11 16:39:53.545258: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 2: 291 operators, 507 arrays (1 quantized)
2019-09-11 16:39:53.549759: W tensorflow/lite/toco/graph_transformations/resolve_constant_random_uniform.cc:88] RandomUniform op outputting "resnet_v1_50/E_Dropout/random_uniform/RandomUniform" is truly random (using /dev/random system entropy). Therefore, cannot resolve as constant. Set "seed" or "seed2" attr non-zero to fix this
2019-09-11 16:39:53.561449: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 3: 288 operators, 501 arrays (1 quantized)
2019-09-11 16:39:53.562454: W tensorflow/lite/toco/graph_transformations/resolve_constant_random_uniform.cc:88] RandomUniform op outputting "resnet_v1_50/E_Dropout/random_uniform/RandomUniform" is truly random (using /dev/random system entropy). Therefore, cannot resolve as constant. Set "seed" or "seed2" attr non-zero to fix this
2019-09-11 16:39:53.567925: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before pre-quantization graph transformations: 288 operators, 501 arrays (1 quantized)
2019-09-11 16:39:53.570066: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Group bidirectional sequence lstm/rnn: 288 operators, 501 arrays (1 quantized)
2019-09-11 16:39:53.573091: F tensorflow/lite/toco/tooling_util.cc:1728] Array resnet_v1_50/bn0/batchnorm/add_1, which is an input to the Abs operator producing the output array resnet_v1_50/prelu0/Abs, is lacking min/max data, which is necessary for quantization. If accuracy matters, either target a non-quantized output format, or run quantized training with your model from a floating point checkpoint to change the input graph to contain min/max information. If you don't care about accuracy, you can pass --default_ranges_min= and --default_ranges_max= for easy experimentation.
Fatal Python error: Aborted

Current thread 0x00007ff4c52a0700 (most recent call first):
  File "/home/crossbar/.local/lib/python3.5/site-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 52 in execute
  File "/home/crossbar/.local/lib/python3.5/site-packages/absl/app.py", line 251 in _run_main
  File "/home/crossbar/.local/lib/python3.5/site-packages/absl/app.py", line 300 in run
  File "/home/crossbar/.local/lib/python3.5/site-packages/tensorflow_core/python/platform/app.py", line 40 in run
  File "/home/crossbar/.local/lib/python3.5/site-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 89 in main
  File "/home/crossbar/.local/bin/toco_from_protos", line 10 in <module>
Aborted (core dumped)

**Comment by rushidesai** [comment]
Same error trying to convert MTCNN model for face detection on EdgeTPU.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
