### ISSUE TITLE
SIGSEGV

### ISSUE THREAD

**Issue by shlapfish** [tensorflow/tensorflow#32492]
```
import tensorflow as tf
from tensorflow_probability import distributions as tfd

mu = [1., 2., 3.]
mu = tf.stack([mu, mu], 0)
cov = [[ 0.36,  0.12,  0.06],
       [ 0.12,  0.29, -0.13],
       [ 0.06, -0.13,  0.26]]
cov = tf.stack([cov, cov], 0)
scale = tf.linalg.cholesky(cov)

mvn = tfd.MultivariateNormalTriL(
    loc=mu,
    scale_tril=scale)

l = mvn.bijector.scale.to_dense()
l = tf.linalg.triangular_solve(l, tf.eye(3))
```

**System information**
- Ubuntu 18.04
- TensorFlow installed from binary
- TensorFlow version: 2.0.0-dev20190913
- Python version: 3.7
- No GPU

git version: v1.12.1-11024-ge8506e0
tensorflow-probability version: 0.9.0-dev20190913

**Describe the current behavior**
`Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)`

Sometimes it hangs for a bit, sometimes it doesn't crash. But 2/3 times I get a SIGSEGV.
Most modifications to the posted code somehow solve the crash.

**Describe the expected behavior**
It should complain about dimensions that mismatch at the last operation.

**Comment by mihaimaruseac** [comment]
To determine if this is a bug of tf or tf_probability, can you change the script to

```python
import tensorflow as tf
from tensorflow_probability import distributions as tfd

mu = [1., 2., 3.]
mu = tf.stack([mu, mu], 0)
cov = [[ 0.36,  0.12,  0.06],
       [ 0.12,  0.29, -0.13],
       [ 0.06, -0.13,  0.26]]
cov = tf.stack([cov, cov], 0)
scale = tf.linalg.cholesky(cov)

mvn = tfd.MultivariateNormalTriL(
    loc=mu,
    scale_tril=scale)

l = mvn.bijector.scale.to_dense()
tf.print(l)


l = tf.linalg.triangular_solve(l, tf.eye(3))
```

Then run it in a loop until the first SIGSEGV and see the value of `l` tensor printed in the last run. Then use the following script

```python
import tensorflow as tf
l = ... # insert here the tensor that got printed
l = tf.linalg.triangular_solve(l, tf.eye(3))
```

Run it, if it still crashes, please post the code here. Otherwise, might need to open issue on tf-probability repo, but still please update here.

**Comment by joren-adhese** [comment]
No need to loop, code is deterministic.
I tried that. It doesn't crash.

**Comment by mihaimaruseac** [comment]
```python
import tensorflow as tf

l = [
     [[0.6,  0  , 0],
      [0.2,  0.5, 0],
      [0.1, -0.3, 0.4],
     ],
     [[0.6,  0  , 0],
      [0.2,  0.5, 0],
      [0.1, -0.3, 0.4],
     ],
    ]

l = tf.linalg.triangular_solve(l, tf.eye(3))
```

Out of 10 runs, the above segfaults 8 times and the other 2 times ends with

```
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    l = tf.linalg.triangular_solve(l, tf.eye(3))
  File "/tmp/gh/19/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_linalg_ops.py", line 1786, in matrix_triangular_solve
    matrix, rhs, lower=lower, adjoint=adjoint, name=name, ctx=_ctx)
  File "/tmp/gh/19/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_linalg_ops.py", line 1841, in matrix_triangular_solve_eager_fallback
    attrs=_attrs, ctx=ctx, name=name)
  File "/tmp/gh/19/lib/python3.7/site-packages/tensorflow_core/python/eager/execute.py", line 67, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: All input tensors must have the same rank. [Op:MatrixTriangularSolve]
```

The error makes sense, `tf.eye(3)` is a 2D tensor whereas `l` is a 3D one. The segfault though, that's something we'll have to look at.

**Comment by joren-adhese** [comment]
Heh, indeed, it crashes. I was apparently just extremely unlucky that I had a few non-crashing runs in a row :)

**Comment by joren-adhese** [comment]
One-linering the problem seems to make the crash much more consistent.
`tf.linalg.triangular_solve(2*(3*(3*[1])), tf.eye(3))`
SIGSEGVs 20/20 runs
The matrix is not even triagular.

**Comment by chunduriv** [comment]
@shlapfish,

Sorry for the late response. The crashing issue was fixed and it raises `InvalidArgumentError` 

```
import tensorflow as tf
tf.linalg.triangular_solve([1], tf.eye(3))
```

Output:

```
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
[<ipython-input-2-74df98b72d37>](https://localhost:8080/#) in <module>()
      1 import tensorflow as tf
      2 print(tf.__version__)
----> 3 tf.linalg.triangular_solve([1], tf.eye(3))

1 frames
[/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/execute.py](https://localhost:8080/#) in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     53     ctx.ensure_initialized()
     54     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
---> 55                                         inputs, attrs, num_outputs)
     56   except core._NotOkStatusException as e:
     57     if name is not None:

InvalidArgumentError: In[0] ndims must be >= 2: 1 [Op:MatrixTriangularSolve]

```
Thank you.
