### ISSUE TITLE
Installation exception in EI Capitan

### ISSUE THREAD

**Issue by l800891** [tensorflow/tensorflow#325]
Hi,
I am getting this errors after runing 
"pip install https://storage.googleapis.com/tensorflow/mac/tensorflow-0.5.0-py2-none-any.whl"
I am using OSX:10.11.1. Is it a permission problem? should I run sudo?
Thanks in advance!

Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-1.5.4-py2.7.egg/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-1.5.4-py2.7.egg/pip/commands/install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/Library/Python/2.7/site-packages/pip-1.5.4-py2.7.egg/pip/req.py", line 1435, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/pip-1.5.4-py2.7.egg/pip/req.py", line 671, in install
    self.move_wheel_files(self.source_dir, root=root)
  File "/Library/Python/2.7/site-packages/pip-1.5.4-py2.7.egg/pip/req.py", line 901, in move_wheel_files
    pycompile=self.pycompile,
  File "/Library/Python/2.7/site-packages/pip-1.5.4-py2.7.egg/pip/wheel.py", line 207, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/Library/Python/2.7/site-packages/pip-1.5.4-py2.7.egg/pip/wheel.py", line 194, in clobber
    os.makedirs(destsubdir)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/external'

Storing debug log for failure in /var/folders/ky/4cxqzftd7q1844xgkvvb_4dc0000gn/T/tmpcQCpeO

**Comment by cpagr** [comment]
It worked for me with the super user permission.

Try sudo.

**Comment by l800891** [comment]
Tried sudo, a different error:
>Exception:
>
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-1.5.4-py2.7.egg/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-1.5.4-py2.7.egg/pip/commands/install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/Library/Python/2.7/site-packages/pip-1.5.4-py2.7.egg/pip/req.py", line 1431, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip-1.5.4-py2.7.egg/pip/req.py", line 598, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip-1.5.4-py2.7.egg/pip/req.py", line 1836, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip-1.5.4-py2.7.egg/pip/util.py", line 295, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/tmp/pip-mLMP2F-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/numpy-1.8.0rc1-py2.7.egg-info'
>
Storing debug log for failure in /Users/Lin/Library/Logs/pip.log

**Comment by cpagr** [comment]
Operation not permitted, is usually a cause due to ownership issue. Try changing it and use the super user again.

**Comment by ebrevdo** [comment]
If you continue having trouble with sudo, consider using a virtualenv following instructions in the howto [here](http://tensorflow.org/get_started/os_setup.md#virtualenv-based_installation).

**Comment by atishpatel** [comment]
I had a similar issue. I believe it's because you are trying to update the system python version. This has issues with a feature Apple introduced called " System Integrity Protection". Instead, you should install a user version of Python and use that. 
Try something like this:
brew install python
brew doctor
(Read the errors, and fix issues related to python like linking issues) (I had to do 'brew link --overwrite python')
pip install --upgrade numpy
Then try installing TensorFlow.

**Comment by ad26kt** [comment]
I faced the same problem and I found that I can still import tensorflow and have no problem to run some simple code related to tensorflow.
will I face other problem later ?

**Comment by vrv** [comment]
@ad26kt: if you do, let us know.
