### ISSUE TITLE
Error when using stateful RNN with multiple inputs

### ISSUE THREAD

**Issue by drasmuss** [tensorflow/tensorflow#32501]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0.0rc0
- Python version: 3.6.8
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: 10.0.130/7.6.0
- GPU model and memory: GTX 980 Ti

**Describe the current behavior**

The stock example of RNNs with multiple inputs from here https://www.tensorflow.org/beta/guide/keras/rnn#rnns_with_listdict_inputs_or_nested_inputs produces an error if you set `stateful=True`.  This seems to be a problem with any multi-input RNN with stateful=True.

**Describe the expected behavior**

There should be no error, multi-input RNNs with stateful=True should work the same as with stateful=False (other than preserving state).

**Code to reproduce the issue**

Note, this code is copied from https://www.tensorflow.org/beta/guide/keras/rnn#rnns_with_listdict_inputs_or_nested_inputs, with the exception that I changed the line
```
rnn = tf.keras.layers.RNN(cell)
```
to
```
rnn = tf.keras.layers.RNN(cell, stateful=True)
```

``` python
import collections

import tensorflow as tf

NestedInput = collections.namedtuple("NestedInput", ["feature1", "feature2"])
NestedState = collections.namedtuple("NestedState", ["state1", "state2"])


class NestedCell(tf.keras.layers.Layer):
    def __init__(self, unit_1, unit_2, unit_3, **kwargs):
        self.unit_1 = unit_1
        self.unit_2 = unit_2
        self.unit_3 = unit_3
        self.state_size = NestedState(
            state1=unit_1, state2=tf.TensorShape([unit_2, unit_3])
        )
        self.output_size = (unit_1, tf.TensorShape([unit_2, unit_3]))
        super(NestedCell, self).__init__(**kwargs)

    def build(self, input_shapes):
        # expect input_shape to contain 2 items, [(batch, i1), (batch, i2, i3)]
        input_1 = input_shapes.feature1[1]
        input_2, input_3 = input_shapes.feature2[1:]

        self.kernel_1 = self.add_weight(
            shape=(input_1, self.unit_1), initializer="uniform", name="kernel_1"
        )
        self.kernel_2_3 = self.add_weight(
            shape=(input_2, input_3, self.unit_2, self.unit_3),
            initializer="uniform",
            name="kernel_2_3",
        )

    def call(self, inputs, states):
        # inputs should be in [(batch, input_1), (batch, input_2, input_3)]
        # state should be in shape [(batch, unit_1), (batch, unit_2, unit_3)]
        input_1, input_2 = tf.nest.flatten(inputs)
        s1, s2 = states

        output_1 = tf.matmul(input_1, self.kernel_1)
        output_2_3 = tf.einsum("bij,ijkl->bkl", input_2, self.kernel_2_3)
        state_1 = s1 + output_1
        state_2_3 = s2 + output_2_3

        output = [output_1, output_2_3]
        new_states = NestedState(state1=state_1, state2=state_2_3)

        return output, new_states


unit_1 = 10
unit_2 = 20
unit_3 = 30

input_1 = 32
input_2 = 64
input_3 = 32
batch_size = 64
num_batch = 100
timestep = 50

cell = NestedCell(unit_1, unit_2, unit_3)
rnn = tf.keras.layers.RNN(cell, stateful=True)

inp_1 = tf.keras.Input((None, input_1))
inp_2 = tf.keras.Input((None, input_2, input_3))

outputs = rnn(NestedInput(feature1=inp_1, feature2=inp_2))

model = tf.keras.models.Model([inp_1, inp_2], outputs)

model.compile(optimizer="adam", loss="mse", metrics=["accuracy"])
```

**Other info / logs**
```
Traceback (most recent call last):
  File ".../tmp2.py", line 70, in <module>
    outputs = rnn(NestedInput(feature1=inp_1, feature2=inp_2))
  File "...\site-packages\tensorflow_core\python\keras\layers\recurrent.py", line 623, in __call__
    return super(RNN, self).__call__(inputs, **kwargs)
  File "...\site-packages\tensorflow_core\python\keras\engine\base_layer.py", line 777, in __call__
    self._maybe_build(inputs)
  File "...\site-packages\tensorflow_core\python\keras\engine\base_layer.py", line 2099, in _maybe_build
    self.build(input_shapes)
  File "...\site-packages\tensorflow_core\python\keras\layers\recurrent.py", line 561, in build
    self.reset_states()
  File "...\site-packages\tensorflow_core\python\keras\layers\recurrent.py", line 809, in reset_states
    spec_shape = None if self.input_spec is None else self.input_spec[0].shape
AttributeError: 'NestedInput' object has no attribute 'shape'
```

**Comment by oanush** [comment]
Issue replicating for TF version-2.0rc0 and also 2.0rc1, please find the [gist](https://colab.sandbox.google.com/gist/oanush/8b07187ad22ba68f2bdd7f45a058d851/32501.ipynb) of the colab.Thanks!

**Comment by drasmuss** [comment]
This issue is present in 1.14.0 as well (and probably earlier, but the RNN api was different so the example doesn't run for other reasons).

**Comment by qlzh727** [comment]
Thanks for reporting the issue. Let me take a look.
