### ISSUE TITLE
Keras ModelCheckpoint callback fails to create directory when saving as SavedModel

### ISSUE THREAD

**Issue by idenc** [tensorflow/tensorflow#32505]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Windows 10 Pro Version 1903
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
N/A
- TensorFlow installed from (source or binary):
binary
- TensorFlow version (use command below):
TF 2.0.0rc1
- Python version: 3.6.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: Using CPU
- GPU model and memory:

**Describe the current behavior**
Using tf.keras.callbacks.ModelCheckpoint results in Failed to create a directory. I believe it's an issue with how paths are created in Tensorflow. Error does not occur if I use double backslash to join checkpoint_folder and model_filename instead of os.path.join. 
**Describe the expected behavior**
Directory for saved model is created and saved model is saved correctly
**Code to reproduce the issue**
```
model_filename = str(args.net) + "-Epoch-{epoch:02d}-Loss-{val_loss:.2f}"\
if args.save_format == 'h5':
    model_filename += '.h5'
checkpoint_path = os.path.join(args.checkpoint_folder, model_filename)

model_checkpoint = tf.keras.callbacks.ModelCheckpoint(
        filepath=checkpoint_path,
        monitor='val_loss',
        verbose=1,
        save_best_only=True,
        save_weights_only=False,
        mode='auto')
```

**Other info / logs**
```
Traceback (most recent call last):
  File "C:/Users/iden/PycharmProjects/PytorchSSD/tf_translate/train_ssd.py", line 307, in <module>
    workers=args.num_workers, max_queue_size=args.max_queue_size)
  File "C:\Users\iden\PycharmProjects\PytorchSSD\tf2venv\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 1297, in fit_generator
    steps_name='steps_per_epoch')
  File "C:\Users\iden\PycharmProjects\PytorchSSD\tf2venv\lib\site-packages\tensorflow_core\python\keras\engine\training_generator.py", line 332, in model_iteration
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "C:\Users\iden\PycharmProjects\PytorchSSD\tf2venv\lib\site-packages\tensorflow_core\python\keras\callbacks.py", line 297, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "C:\Users\iden\PycharmProjects\PytorchSSD\tf2venv\lib\site-packages\tensorflow_core\python\keras\callbacks.py", line 964, in on_epoch_end
    self._save_model(epoch=epoch, logs=logs)
  File "C:\Users\iden\PycharmProjects\PytorchSSD\tf2venv\lib\site-packages\tensorflow_core\python\keras\callbacks.py", line 1000, in _save_model
    self.model.save(filepath, overwrite=True)
  File "C:\Users\iden\PycharmProjects\PytorchSSD\tf2venv\lib\site-packages\tensorflow_core\python\keras\engine\network.py", line 1189, in save
    signatures, options)
  File "C:\Users\iden\PycharmProjects\PytorchSSD\tf2venv\lib\site-packages\tensorflow_core\python\keras\saving\save.py", line 115, in save_model
    signatures, options)
  File "C:\Users\iden\PycharmProjects\PytorchSSD\tf2venv\lib\site-packages\tensorflow_core\python\keras\saving\saved_model\save.py", line 74, in save
    save_lib.save(model, filepath, signatures, options)
  File "C:\Users\iden\PycharmProjects\PytorchSSD\tf2venv\lib\site-packages\tensorflow_core\python\saved_model\save.py", line 899, in save
    utils_impl.get_or_create_variables_dir(export_dir)
  File "C:\Users\iden\PycharmProjects\PytorchSSD\tf2venv\lib\site-packages\tensorflow_core\python\saved_model\utils_impl.py", line 183, in get_or_create_variables_dir
    file_io.recursive_create_dir(variables_dir)
  File "C:\Users\iden\PycharmProjects\PytorchSSD\tf2venv\lib\site-packages\tensorflow_core\python\lib\io\file_io.py", line 438, in recursive_create_dir
    recursive_create_dir_v2(dirname)
  File "C:\Users\iden\PycharmProjects\PytorchSSD\tf2venv\lib\site-packages\tensorflow_core\python\lib\io\file_io.py", line 453, in recursive_create_dir_v2
    pywrap_tensorflow.RecursivelyCreateDir(compat.as_bytes(path))
tensorflow.python.framework.errors_impl.NotFoundError: Failed to create a directory: models/mb1-ssd-Epoch-01-Loss-32.98\variables; No such file or directory

Process finished with exit code 1
```

**Comment by gadagashwini** [comment]
@idenc,
In order to expedite the trouble-shooting process, please provide a standalone code to reproduce the issue reported here. Thanks!

**Comment by idenc** [comment]
This code should reproduce the issue.
```
import os

import numpy as np
from tensorflow.python.keras.callbacks import ModelCheckpoint
from tensorflow.python.keras.layers import Dense, Activation
from tensorflow.python.keras.models import Sequential

model_filename = "test-Epoch-{epoch:02d}"
checkpoint_path = os.path.join('models/', model_filename)

model_checkpoint = ModelCheckpoint(
    filepath=checkpoint_path,
    monitor='val_loss',
    verbose=1,
    save_best_only=False,
    save_weights_only=False,
    mode='auto')

x_train, y_train = np.ones([1, 784]), np.ones([1, 10])
model = Sequential()
model.add(Dense(10, input_dim=784, kernel_initializer='uniform'))
model.add(Activation('softmax'))
model.compile(loss='categorical_crossentropy', optimizer='rmsprop')
model.fit(x_train, y_train, batch_size=128, epochs=20, verbose=0, callbacks=[model_checkpoint])
```

**Comment by gadagashwini** [comment]
@idenc, I tried replicating the issue on colab but executed without any error. Please see the [gist](https://colab.sandbox.google.com/gist/gadagashwini/421b3c03826a7b346b85e0d8703bfca9/untitled156.ipynb). Thanks!

**Comment by idenc** [comment]
@gadagashwini I think it may only occur on Windows. Running on my Windows 10 machine I get the error if I use a forward slash with the checkpoint directory. However, just removing any slashes and using os.path.join throws no errors. Can be closed.

**Comment by jwojcicki** [comment]
I bumped into this issue as well. In my case the problem was that the directory where the checkpoints were saved was also monitored by microsoft onedrive client and this seemed to have caused the problem. Possibly OneDrive trying to read  the checkpoint file when keras attempted to update it, hence the conflict. Not sure if this is the case of the problem mentioned in this issue, however possibly worth examining for conflicts with 3rd party application. Is it possible to have interference with source control software like git, as well?
