### ISSUE TITLE
tf-Java 1.14.0 can not open shared object file libtensorflow_frameword.so.1

### ISSUE THREAD

**Issue by doladola** [tensorflow/tensorflow#32539]
**System information**
- OS system: CentOS 7.3
- TensorFlow installed from binary: import tensorflow from maven repo
- TensorFlow version: 1.14.0
- Python version: 3.6.5
- CUDA/cuDNN version: cuda10-cudnn7

**Describe the current behavior**
We are using tensorflow java api to loaded a tensorflow model and a program exception is thrown. The exception information shows that the dependent resource file (libtensorflow_jni.so : libtensorflow_frameword.so.1) is missing.  We find that the tensorflow jar file contains this resource file, but the file failed to extract, resulting in an exception. We suspect this is due to the program filtering the files to be extracted by suffix names (.so).
**Describe the expected behavior**
The program can load model file successfully. 

**Code to reproduce the issue**
The maven setting:
```
<dependency>
            <groupId>org.tensorflow</groupId>
            <artifactId>tensorflow</artifactId>
            <version>1.14.0</version>
</dependency>
```
```
import org.tensorflow.SavedModelBundle;
import org.tensorflow.Tensor;

public static void main(String[] args){
        String dir = "xxx" // model path 
        savedModelBundle = SavedModelBundle.load(dir, "serve");
    }
}
```

**Other info / logs**
Exception in thread "main" java.lang.UnsatisfiedLinkError: /tmp/tensorflow_native_libraries-1568533726609-0/libtensorflow_jni.so: libtensorflow_framework.so.1: cannot open shared object file: No such file or directory
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
        at java.lang.Runtime.load0(Runtime.java:809)
        at java.lang.System.load(System.java:1086)
        at org.tensorflow.NativeLibrary.load(NativeLibrary.java:101)
        at org.tensorflow.TensorFlow.init(TensorFlow.java:66)
        at org.tensorflow.TensorFlow.<clinit>(TensorFlow.java:70)
        at org.tensorflow.SavedModelBundle.<clinit>(SavedModelBundle.java:170)

**Comment by marhlder** [comment]
We have a similar issue with the jar running with Ubuntu 18.04

**Comment by jvishnuvardhan** [comment]
@doladola Can you try with TF1.15.0rc1 and let us know whether the issue persists? Thanks!

**Comment by oliverhu** [comment]
I run into the same issue as well, @jvishnuvardhan could you refer a related commit so we could try it out?

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by jvishnuvardhan** [comment]
@oliverhu Finally `TF1.15.0` stable version was released. Can you try it and let us know how it progresses. Thanks!

**Comment by oliverhu** [comment]
@jvishnuvardhan  thanks, will try it out. Just curious what is the supporting model (priority) for 1.15? Is 1.15 a LTS version or it is just some temporary release?

**Comment by jvishnuvardhan** [comment]
@oliverhu `TF1.15` is a stable version. This is the final TF1.x version. I think this will be supported for an year only. We would suggest everyone to take a look at TF2.x which will be the only version going to be supported in future.  Thanks!

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by jvishnuvardhan** [comment]
Automatically closing this out since I understand it to be resolved, but please let me know if I'm mistaken.Thanks!

**Comment by tysm** [comment]
Hi, I just had the same problem following the getting started with [maven](https://www.tensorflow.org/install/lang_java) and changing from 1.14 to 1.15 solved.
