### ISSUE TITLE
TF2.0 Convolution  [10,128,128,9] -> [10,128,128,32]->[10,128,128,3] doesn't work.

### ISSUE THREAD

**Issue by MaryRodina** [tensorflow/tensorflow#32647]
**System information**

Python version: 3.6.8
TensorFlow-gpu version 2.0.rc0
CUDA/cuDNN version: 10.0
GPU model and memory: GeForce GTX 1080 Ti
**Describe the current behavior**
Running the provided code on GPUs leads to error message tensorflow.python.eager.core._SymbolicException: Inputs to eager execution function cannot be Keras symbolic tensors, but found [<tf.Tensor 'lambda_26_1/Identity:0' shape=(50, 128, 128, 3) dtype=float32>].

I created **keras** model with multiple keras layers and write  images in summary for tensorboard in function with attribute @tf.function: 
```
@tf.function
def write_to_summary(outputs, targets, writer)
    with writer.as_default():
        tf.summary.image(name="losses_aux/log_outputs",
                         data=outputs)
   ...
   ...
```
and get the error with such stack:
```
Traceback (most recent call last):
  File "D:/Work/1.0/tf2/train.2.0.py", line 255, in <module>
    _main()
  File "D:/Work/1.0/tf2/train.2.0.py", line 84, in _main
    _train_and_eval(config, train_dataset, eval_dataset, model, model_path)
  File "D:/Work/1.0/tf2/train.2.0.py", line 170, in _train_and_eval
    loss_value = loss_fn(outputs, target_batch_train, writer)
  File "D:\Work\1.0\tf2\autoencoder_losses2.py", line 62, in loss_fn
    gamma=losses_config.get_float('hfmae.gamma')),
  File "D:\Work\1.0\tf2\loss2.py", line 47, in high_frequency_mean_abs_error
    outputs, targets, writer, size, sigma, gamma)
  File "C:\venv_rc2.0\lib\site-packages\tensorflow_core\python\eager\def_function.py", line 445, in __call__
    return self._concrete_stateful_fn._filtered_call(canon_args, canon_kwds)  # pylint: disable=protected-access
  File "C:\venv_rc2.0\lib\site-packages\tensorflow_core\python\eager\function.py", line 1141, in _filtered_call
    self.captured_inputs)
  File "C:\venv_rc2.0\lib\site-packages\tensorflow_core\python\eager\function.py", line 1224, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager)
  File "C:\venv_rc2.0\lib\site-packages\tensorflow_core\python\eager\function.py", line 511, in call
    ctx=ctx)
  File "C:\venv_rc2.0\lib\site-packages\tensorflow_core\python\eager\execute.py", line 75, in quick_execute
    "tensors, but found {}".format(keras_symbolic_tensors))
tensorflow.python.eager.core._SymbolicException: Inputs to eager execution function cannot be Keras symbolic tensors, but found [<tf.Tensor 'lambda_26_1/Identity:0' shape=(50, 128, 128, 3) dtype=float32>]
```

Why keras tensor can't be input to eager execution function?!! 
Please, fix this bug, because images are very important for tensorboard.

**Comment by ravikyram** [comment]
In order to expedite the trouble-shooting process, please provide a minimal standalone code to reproduce the issue reported here. Thanks!

**Comment by MaryRodina** [comment]
Hi ! 
when i created standalone code (analog our production code), i get such error : 
```
2019-09-27 10:40:35.222352: W tensorflow/core/framework/op_kernel.cc:1622] OP_REQUIRES failed at conv_ops.cc:1069 : Not found: No algorithm worked!
Traceback (most recent call last):
  File "D:/Work/1.0/tf2/standalone_example.py", line 44, in <module>
    outputs = model(img)
  File "C:\venv_rc2.0\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py", line 851, in __call__
    outputs = self.call(cast_inputs, *args, **kwargs)
  File "C:\venv_rc2.0\lib\site-packages\tensorflow_core\python\keras\engine\network.py", line 697, in call
    return self._run_internal_graph(inputs, training=training, mask=mask)
  File "C:\venv_rc2.0\lib\site-packages\tensorflow_core\python\keras\engine\network.py", line 842, in _run_internal_graph
    output_tensors = layer(computed_tensors, **kwargs)
  File "C:\venv_rc2.0\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py", line 851, in __call__
    outputs = self.call(cast_inputs, *args, **kwargs)
  File "C:\venv_rc2.0\lib\site-packages\tensorflow_core\python\keras\layers\convolutional.py", line 197, in call
    outputs = self._convolution_op(inputs, self.kernel)
  File "C:\venv_rc2.0\lib\site-packages\tensorflow_core\python\ops\nn_ops.py", line 1134, in __call__
    return self.conv_op(inp, filter)
  File "C:\venv_rc2.0\lib\site-packages\tensorflow_core\python\ops\nn_ops.py", line 639, in __call__
    return self.call(inp, filter)
  File "C:\venv_rc2.0\lib\site-packages\tensorflow_core\python\ops\nn_ops.py", line 238, in __call__
    name=self.name)
  File "C:\venv_rc2.0\lib\site-packages\tensorflow_core\python\ops\nn_ops.py", line 2010, in conv2d
    name=name)
  File "C:\venv_rc2.0\lib\site-packages\tensorflow_core\python\ops\gen_nn_ops.py", line 1031, in conv2d
    data_format=data_format, dilations=dilations, name=name, ctx=_ctx)
  File "C:\venv_rc2.0\lib\site-packages\tensorflow_core\python\ops\gen_nn_ops.py", line 1130, in conv2d_eager_fallback
    ctx=_ctx, name=name)
  File "C:\venv_rc2.0\lib\site-packages\tensorflow_core\python\eager\execute.py", line 67, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.NotFoundError: No algorithm worked! [Op:Conv2D]
```
so i can't get error exactly same in start topic.

Standalone code for this example: 
```
import tensorflow as tf

H, W, C = 128, 128, 9
imgs = tf.zeros([10, H, W, C])
ds = tf.data.Dataset.from_tensor_slices(imgs).batch(2)
print(ds)


def construstor(inputs):
    shortcuts = []
    weights_initializer = tf.compat.v1.initializers.truncated_normal(
        mean=0.0,
        stddev=tf.math.sqrt(
            2.0 / ((3 ** 2) * 32))
    )
    activation_fn = tf.keras.layers.LeakyReLU()

    def _operation_convolutional(_filters):
        return tf.keras.layers.Conv2D(
            filters=_filters,
            strides=[1, 1],
            activation=activation_fn,
            kernel_initializer=weights_initializer,
            kernel_size=[3, 3],
            padding='SAME',
            kernel_regularizer=tf.keras.regularizers.l2(1.0),
            bias_regularizer=tf.keras.regularizers.l2(1.0))

    outputs = _operation_convolutional(32)(inputs)
    return _operation_convolutional(3)(outputs)

input_tensor = tf.keras.Input(shape=[None, None, 3])
model = tf.keras.Model(inputs=input_tensor,
                       outputs=construstor(input_tensor))
def run(img):
    tf.summary.image('img', img)

writer = tf.summary.create_file_writer(r"D:\tmp")
with writer.as_default():
    for i, img in enumerate(ds):
        tf.summary.experimental.set_step(i)
        print('iteration')
        outputs = model(img)
        run(outputs)

```
here you can see convolutional for tensor [10,128,128,9] -> [10,128,128,32]->[10,128,128,3] doesn't work.

**Comment by ravikyram** [comment]
I have tried on colab with TF version 2.0.rc0,2.0.0-rc2  and was able to reproduce the issue.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/c1171a6578fe3ab1dc77a2170d4086ca/untitled228.ipynb).Thanks!

**Comment by MaryRodina** [comment]
Please, excuse me i broken result of first paragraph in your Jupyter, i did it accidentally ! 
I think, for reproduce this error you must have identically versions of cuda/cudann, isn't it? 

Nevertheless, you can see what it doesn't work, because world "iteration" must print 5 times (dataset has 10 record - 5 batch with 2 records), but "iteration" prints only 1 time.

**Comment by jvishnuvardhan** [comment]
@MaryRodina Sorry for the delay in my response. I think there is a shape mismatch between input_data and the model_Expectation. Please check the error trace I am getting with `TF2.0`.

```
<BatchDataset shapes: (None, 128, 128, 9), types: tf.float32>
iteration
---------------------------------------------------------------------------
UnimplementedError                        Traceback (most recent call last)
<ipython-input-8-a1cee438968d> in <module>()
     41         tf.summary.experimental.set_step(i)
     42         print('iteration')
---> 43         outputs = model(img)
     44         print(outputs)
     45         run(outputs)

12 frames
/usr/local/lib/python3.6/dist-packages/six.py in raise_from(value, from_value)

UnimplementedError: The Conv2D op currently does not support grouped convolutions on the CPU. A grouped convolution was attempted to be run because the input depth of 9 does not match the filter input depth of 3 [Op:Conv2D]
```

When I changed input channels from `9` to `3`, everything worked without any issue. Please check the [gist here](https://colab.sandbox.google.com/gist/jvishnuvardhan/d5558fac1ff57e44ef36ab1d9288f2bf/untitled228.ipynb) for your reference. Thanks!

Please close the issue if it was already resolved. Thanks!

**Comment by jvishnuvardhan** [comment]
I am closing the issue as it was resolved. Please feel free to open it if the issue persists again. Thanks!

**Comment by philipperemy** [comment]
Usually those errors come when a change on channels happen in two different model calls. For example calling the model on (?, 28, 28, 1) followed by (?, 28, 28, 3). MNIST grayscale to MNIST colored.
