### ISSUE TITLE
[TF1.14] Network compiles localy but not on TPU with error 'InvalidArgumentError: Undeclared output of TPU computation.'

### ISSUE THREAD

**Issue by nsantavas** [tensorflow/tensorflow#32696]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Custom
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.14
- Python version: 3
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: TPU 

I created a DenseNet, which I succesfully compile it locally with GPU, but when I try to compile on  a TPU device, the following error appears
```
Traceback (most recent call last):
  File "attention_dense.py", line 258, in <module>
    model.fit(get_training_dataset(), validation_data=get_validation_dataset(),  initial_epoch=0, steps_per_epoch=steps_per_epoch ,validation_steps=val_steps, epochs=EPOCHS, verbose=1, callbacks=clbk)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/training.py", line 649, in fit
    validation_freq=validation_freq)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/training_distributed.py", line 128, in fit_distributed
    validation_freq=validation_freq)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/training_distributed.py", line 395, in experimental_tpu_fit_loop
    callbacks._call_begin_hook(mode)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/callbacks.py", line 262, in _call_begin_hook
    self.on_train_begin()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/callbacks.py", line 378, in on_train_begin
    callback.on_train_begin(logs)
  File "/home/frank_lab/clr.py", line 122, in on_train_begin
    K.set_value(self.model.optimizer.lr, self.base_lr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/backend.py", line 3038, in set_value
    get_session().run(assign_op, feed_dict={assign_placeholder: value})
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/backend.py", line 462, in get_session
    _initialize_variables(session)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/backend.py", line 879, in _initialize_variables
    [variables_module.is_variable_initialized(v) for v in candidate_vars])
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Undeclared output of TPU computation. A common cause of this error is variable initializers that depend on the TPU computation. Edge: node dense_1_2/re_lu_1/Relu (defined at attention_dense.py:258) :0 -> node tf_op_layer_add/add (defined at attention_dense.py:258) :0
```
The code is the following

```
def conv(input, kernel, filt, stride, dilation, pad='same'):
    x = layers.Conv2D(filters=filt, kernel_size=kernel, strides=stride, dilation_rate=dilation, padding=pad, kernel_regularizer=tf.keras.regularizers.l2(l=0.01))(input)
    return x

def conv_down(input, filters):
    x = conv(input, 3, filters, 2 ,1)
    x = layers.BatchNormalization(axis=-1, fused=True)(x)
    x = layers.LeakyReLU(alpha=0.1)(x) 
    return x

def conv_block(input, filters, stride=1, dilation=2, pad='same', bottleneck=True):
    x = layers.BatchNormalization(axis=-1, fused=True)(input)
    x = layers.LeakyReLU(alpha=0.1)(x) 
    if bottleneck:
        x = conv(x, kernel=1, filt=(filters*4), dilation=dilation, stride=1, pad=pad)
        x = layers.BatchNormalization(axis=-1, fused=True)(x)
        x = layers.LeakyReLU(alpha=0.1)(x) 
    x = conv(x, kernel=3, filt=filters, stride=stride, dilation=dilation, pad=pad)
    return x

def dense_block(x, filters, layers, bottleneck=True):
    x_list = [x]
    for i in range(layers):
        cb = conv_block(x, filters, dilation=2, bottleneck=True)
        x_list.append(cb)
        x = tf.keras.layers.concatenate([x, cb], axis=-1)
        x = attention(x)
    return x

def transition_block(input, filters, att=True):
    x = layers.BatchNormalization(axis=-1, fused=True)(input)
    x = layers.LeakyReLU(alpha=0.1)(x) 
    x = conv(x, kernel=1, filt=filters, stride=1, dilation=2, pad='same')
    x = layers.AveragePooling2D((2,2), strides=(2,2))(x)
    if att:
        x = attention(x)
    return x
    
def attention(input):
    x = channel_att(input)
    x = spatial_att(x)
    return x
    
def channel_att(input, ratio=8):
    channel = input.get_shape()[-1]
    ####
    avg_pool = tf.keras.layers.GlobalAveragePooling2D()(input)
    avg_pool = tf.keras.layers.Reshape((1,1,channel))(avg_pool)
    max_pool = tf.keras.layers.GlobalMaxPooling2D()(input)
    max_pool = tf.keras.layers.Reshape((1,1,channel))(max_pool)
    ####
    mlp_0 = layers.Dense(units=channel//ratio, activation=layers.ReLU())
    mlp_1 = layers.Dense(units=channel, activation=layers.ReLU())
    avg_ = mlp_1(mlp_0(avg_pool))
    max_ = mlp_1(mlp_0(max_pool))
    scale = keras.activations.sigmoid(avg_+max_)
    return input*scale

def spatial_att(input, kernel=7):
    avg_pool = tf.math.reduce_mean(input, axis=[3], keepdims=True)
    max_pool = tf.math.reduce_max(input, axis=[3], keepdims=True)
    concat = tf.concat([avg_pool, max_pool], axis=3)
    concat = layers.Conv2D(filters=1, kernel_size=kernel, padding='same',use_bias=False)(concat)
    concat = keras.activations.sigmoid(concat)
    return input*concat


def create_model():
    Input = layers.Input(shape=(540, 540, 3))
    x = conv(Input, kernel=3, filt=64, stride=1, dilation=2)
    for i in range(8):
        x = dense_block(x, filters=128, layers=3, bottleneck=True)
        x = transition_block(x, filters=128, att=True)
    x = dense_block(x, filters=128, layers=4, bottleneck=True)
    x = layers.BatchNormalization(axis=-1, fused=True)(x)
    x = conv(x, kernel=1, filt=45, stride=1, dilation=1)
    model = tf.keras.Model(inputs=Input, outputs=x)
    model.compile(optimizer=keras.optimizers.SGD(), loss=custom_loss)
    return model

with tpu_strategy.scope():
    model=create_model()

model.fit(get_training_dataset(), validation_data=get_validation_dataset(),  initial_epoch=0, steps_per_epoch=steps_per_epoch ,validation_steps=val_steps, epochs=EPOCHS, verbose=1, callbacks=clbk)
```

**Comment by ravikyram** [comment]
@nsantavas 
Looks like code is incomplete. I am seeing the error `NameError: name 'tpu_strategy' is not defined`. Can you please help us with simple standalone code to reproduce the issue in our environment. Thanks!

**Comment by nsantavas** [comment]
Hi, @ravikyram 

```
tpu=' '
resolver = tf.distribute.cluster_resolver.TPUClusterResolver(tpu=tpu)
tf.config.experimental_connect_to_host(resolver.master())
tf.tpu.experimental.initialize_tpu_system(resolver)
tpu_strategy = tf.distribute.experimental.TPUStrategy(resolver)
EPOCHS=250


def conv(input, kernel, filt, stride, dilation, pad='same'):
    x = layers.Conv2D(filters=filt, kernel_size=kernel, strides=stride, dilation_rate=dilation, padding=pad, kernel_regularizer=tf.keras.regularizers.l2(l=0.01))(input)
    return x

def conv_down(input, filters):
    x = conv(input, 3, filters, 2 ,1)
    x = layers.BatchNormalization(axis=-1, fused=True)(x)
    x = layers.LeakyReLU(alpha=0.1)(x) 
    return x

def conv_block(input, filters, stride=1, dilation=2, pad='same', bottleneck=True):
    x = layers.BatchNormalization(axis=-1, fused=True)(input)
    x = layers.LeakyReLU(alpha=0.1)(x) 
    if bottleneck:
        x = conv(x, kernel=1, filt=(filters*4), dilation=dilation, stride=1, pad=pad)
        x = layers.BatchNormalization(axis=-1, fused=True)(x)
        x = layers.LeakyReLU(alpha=0.1)(x) 
    x = conv(x, kernel=3, filt=filters, stride=stride, dilation=dilation, pad=pad)
    return x

def dense_block(x, filters, layers, bottleneck=True):
    x_list = [x]
    for i in range(layers):
        cb = conv_block(x, filters, dilation=2, bottleneck=True)
        x_list.append(cb)
        x = tf.keras.layers.concatenate([x, cb], axis=-1)
        x = attention(x)
    return x

def transition_block(input, filters, att=True):
    x = layers.BatchNormalization(axis=-1, fused=True)(input)
    x = layers.LeakyReLU(alpha=0.1)(x) 
    x = conv(x, kernel=1, filt=filters, stride=1, dilation=2, pad='same')
    x = layers.AveragePooling2D((2,2), strides=(2,2))(x)
    if att:
        x = attention(x)
    return x
    
def attention(input):
    x = channel_att(input)
    x = spatial_att(x)
    return x
    
def channel_att(input, ratio=8):
    channel = input.get_shape()[-1]
    ####
    avg_pool = tf.keras.layers.GlobalAveragePooling2D()(input)
    avg_pool = tf.keras.layers.Reshape((-1,1,1,channel))(avg_pool)
    max_pool = tf.keras.layers.GlobalMaxPooling2D()(input)
    max_pool = tf.keras.layers.Reshape((-1,1,1,channel))(max_pool)
    ####
    mlp_0 = layers.Dense(units=channel//ratio, activation=layers.ReLU())
    mlp_1 = layers.Dense(units=channel, activation=layers.ReLU())
    avg_ = mlp_1(mlp_0(avg_pool))
    max_ = mlp_1(mlp_0(max_pool))
    scale = keras.activations.sigmoid(avg_+max_)
    return input*scale

def spatial_att(input, kernel=7):
    avg_pool = tf.math.reduce_mean(input, axis=[3], keepdims=True)
    max_pool = tf.math.reduce_max(input, axis=[3], keepdims=True)
    concat = tf.concat([avg_pool, max_pool], axis=3)
    concat = layers.Conv2D(filters=1, kernel_size=kernel, padding='same',use_bias=False)(concat)
    concat = keras.activations.sigmoid(concat)
    return input*concat


def create_model():
    Input = layers.Input(shape=(540, 540, 3))
    x = conv(Input, kernel=3, filt=64, stride=1, dilation=2)
    for i in range(8):
        x = dense_block(x, filters=128, layers=3, bottleneck=True)
        x = transition_block(x, filters=128, att=True)
    x = dense_block(x, filters=128, layers=4, bottleneck=True)
    x = layers.BatchNormalization(axis=-1, fused=True)(x)
    x = conv(x, kernel=1, filt=45, stride=1, dilation=1)
    model = tf.keras.Model(inputs=Input, outputs=x)
    model.compile(optimizer=keras.optimizers.SGD(), loss=custom_loss)
    return model


with tpu_strategy.scope():
    model=create_model()


model.fit(get_training_dataset(), validation_data=get_validation_dataset(),  initial_epoch=0, steps_per_epoch=steps_per_epoch ,validation_steps=val_steps, epochs=EPOCHS, verbose=1, callbacks=clbk)

```

add random dataset (None, 540, 540, 3) dimensions

**Comment by ravikyram** [comment]
I tried to reproduce the issue. I am getting the error message` URLError: <urlopen error [Errno 110] Connection timed out>`. Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/78dfb933e940242780cc4e97e7fdf3e5/untitled212.ipynb).Thanks!

**Comment by nsantavas** [comment]
@ in colab you should not define tpu address. TPUClusterResolver must be empty
```
resolver = tf.distribute.cluster_resolver.TPUClusterResolver()
tf.config.experimental_connect_to_host(resolver.master())
tf.tpu.experimental.initialize_tpu_system(resolver)
tpu_strategy = tf.distribute.experimental.TPUStrategy(resolver)
```

**Comment by ravikyram** [comment]
I have tried on colab with TF version 1.14 and i am seeing the below error.`ValueError: Input 0 of layer conv2d_11 is incompatible with the layer: expected ndim=4, found ndim=5. Full shape received: [None, None, 540, 2, 192]`.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/92e178a10671bd6a27e6d6680c467fb9/untitled212.ipynb).Thanks!

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.

**Comment by ymodak** [comment]
The [notebook](https://colab.research.google.com/gist/ymodak/c7107543736696e679c2e996a3eb4ec1/untitled212.ipynb) throws error with gpu runtime as well.
