### ISSUE TITLE
Keras/tensorflow not working in Command Line 

### ISSUE THREAD

**Issue by vicky30mar82** [tensorflow/tensorflow#32703]
Hi Team, 

I am trying to execute my pyhton code using Keras and Numpy Library on command Prompt.
It is working fine with Jupyter Notebook.
[keras_prediction - Copy.txt](https://github.com/tensorflow/tensorflow/files/3638219/keras_prediction.-.Copy.txt)

I am facing the following error.

_D:\Vivek\Python\Sigmoid_basic>python keras_prediction.py
Using TensorFlow backend.
Traceback (most recent call last):
  File "D:\Vivek\Python\Python_64\lib\site-packages\tensorflow\python\platform\s
elf_check.py", line 47, in preload_check
    ctypes.WinDLL(build_info.msvcp_dll_name)
  File "D:\Vivek\Python\Python_64\lib\ctypes\__init__.py", line 364, in __init__

    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "keras_prediction.py", line 2, in <module>
    import keras as ks
  File "D:\Vivek\Python\Python_64\lib\site-packages\keras\__init__.py", line 3,
in <module>
    from . import utils
  File "D:\Vivek\Python\Python_64\lib\site-packages\keras\utils\__init__.py", li
ne 6, in <module>
    from . import conv_utils
  File "D:\Vivek\Python\Python_64\lib\site-packages\keras\utils\conv_utils.py",
line 9, in <module>
    from .. import backend as K
  File "D:\Vivek\Python\Python_64\lib\site-packages\keras\backend\__init__.py",
line 1, in <module>
    from .load_backend import epsilon
  File "D:\Vivek\Python\Python_64\lib\site-packages\keras\backend\load_backend.p
y", line 89, in <module>
    from .tensorflow_backend import *
  File "D:\Vivek\Python\Python_64\lib\site-packages\keras\backend\tensorflow_bac
kend.py", line 5, in <module>
    import tensorflow as tf
  File "D:\Vivek\Python\Python_64\lib\site-packages\tensorflow\__init__.py", lin
e 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-im
port
  File "D:\Vivek\Python\Python_64\lib\site-packages\tensorflow\python\__init__.p
y", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "D:\Vivek\Python\Python_64\lib\site-packages\tensorflow\python\pywrap_ten
sorflow.py", line 30, in <module>
    self_check.preload_check()
  File "D:\Vivek\Python\Python_64\lib\site-packages\tensorflow\python\platform\s
elf_check.py", line 55, in preload_check
    % build_info.msvcp_dll_name)
ImportError: Could not find 'msvcp140.dll'. TensorFlow requires that this DLL be
 installed in a directory that is named in your %PATH% environment variable. You
 may install this DLL by downloading Visual C++ 2015 Redistributable Update 3 fr
om this URL: https://www.microsoft.com/en-us/download/details.aspx?id=53587_

Please find my code attached.

Please advise

Thanks and Regards
Vivek Srivastava

**Comment by ravikyram** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

 If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by vicky30mar82** [comment]
Hi Ravi, 
I am using 
Windows 7 Platform 
Python 3.4 (64 Bit)
Tensorflow : 1.14.0

Regards
Vivek Srivastava

**Comment by ravikyram** [comment]
@vicky30mar82 

I tried executing in command line. Please,find the attached file for your reference.
[errorlog.tar.gz](https://github.com/tensorflow/tensorflow/files/3651913/errorlog.tar.gz)

**Comment by ravikyram** [comment]
@vicky30mar82 

Please, let us know if the issue still persists. Thanks!

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
