### ISSUE TITLE
TFLite: Converting 2 Operation Network[Slice, Transpose] results in converter error despite both ops being supported

### ISSUE THREAD

**Issue by TimCapes** [tensorflow/tensorflow#32740]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac OS Sierra 10.12.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0.0-rc1
- Python version: 3.7.1
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: CPU

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Model conversion from script errors unexpectedly with:
F tensorflow/lite/toco/tooling_util.cc:661] Check failed: dim >= 1 (0 vs. 1)
Fatal Python error: Aborted

Current thread 0x00007fffbc0853c0 (most recent call first):
  File "/Users/t.capes/miniconda3/lib/python3.7/site-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 52 in execute
  File "/Users/t.capes/miniconda3/lib/python3.7/site-packages/absl/app.py", line 251 in _run_main
  File "/Users/t.capes/miniconda3/lib/python3.7/site-packages/absl/app.py", line 300 in run
  File "/Users/t.capes/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/platform/app.py", line 40 in run
  File "/Users/t.capes/miniconda3/lib/python3.7/site-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 89 in main
  File "/Users/t.capes/miniconda3/bin/toco_from_protos", line 10 in <module>
**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
```
import tensorflow.compat.v1 as tf
import numpy as np

tf.disable_v2_behavior()
initial_input = tf.placeholder(dtype=tf.float32, shape=(None,5,1024))
cap_i = tf.slice(initial_input, [0,0,0], [0,5,1023])
cap_iT = tf.transpose(cap_i, perm=[0,2,1])

sess = tf.Session()
sess.run(tf.global_variables_initializer())
tf.io.write_graph(sess.graph_def, '', 'train.pbtxt')
converter = tf.lite.TFLiteConverter.from_session(sess, [initial_input], [cap_iT])
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
tflite_model = converter.convert()
open('converted_model.tflite', "wb").write(tflite_model)
sess.close()
```
**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
WARNING: Logging before flag parsing goes to stderr.
W0923 16:48:55.162434 140736348050368 deprecation.py:323] From /Users/t.capes/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/compat/v2_compat.py:65: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
2019-09-23 16:48:55.168686: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-09-23 16:48:55.186235: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7f8f68dba420 executing computations on platform Host. Devices:
2019-09-23 16:48:55.186260: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
2019-09-23 16:48:55.192597: I tensorflow/core/grappler/devices.cc:60] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0 (Note: TensorFlow was not compiled with CUDA support)
2019-09-23 16:48:55.192676: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2019-09-23 16:48:55.194251: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:716] Optimization results for grappler item: graph_to_optimize
2019-09-23 16:48:55.194270: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   function_optimizer: function_optimizer did nothing. time = 0.001ms.
2019-09-23 16:48:55.194277: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   function_optimizer: function_optimizer did nothing. time = 0ms.
2019-09-23 16:48:55.196041: I tensorflow/core/grappler/devices.cc:60] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0 (Note: TensorFlow was not compiled with CUDA support)
2019-09-23 16:48:55.196100: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2019-09-23 16:48:55.198204: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:716] Optimization results for grappler item: graph_to_optimize
2019-09-23 16:48:55.198218: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   constant folding: Graph size after: 6 nodes (-1), 5 edges (0), time = 0.619ms.
2019-09-23 16:48:55.198224: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   constant folding: Graph size after: 6 nodes (0), 5 edges (0), time = 0.175ms.
Traceback (most recent call last):
  File "tf_test_1.py", line 16, in <module>
    tflite_model = converter.convert()
  File "/Users/t.capes/miniconda3/lib/python3.7/site-packages/tensorflow_core/lite/python/lite.py", line 983, in convert
    **converter_kwargs)
  File "/Users/t.capes/miniconda3/lib/python3.7/site-packages/tensorflow_core/lite/python/convert.py", line 449, in toco_convert_impl
    enable_mlir_converter=enable_mlir_converter)
  File "/Users/t.capes/miniconda3/lib/python3.7/site-packages/tensorflow_core/lite/python/convert.py", line 200, in toco_convert_protos
    raise ConverterError("See console for info.\n%s\n%s\n" % (stdout, stderr))
tensorflow.lite.python.convert.ConverterError: See console for info.
2019-09-23 16:48:57.055966: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 2 operators, 6 arrays (0 quantized)
2019-09-23 16:48:57.056188: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 2 operators, 6 arrays (0 quantized)
2019-09-23 16:48:57.056303: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 1: 2 operators, 6 arrays (0 quantized)
2019-09-23 16:48:57.056347: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Group bidirectional sequence lstm/rnn: 2 operators, 6 arrays (0 quantized)
2019-09-23 16:48:57.056388: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before dequantization graph transformations: 2 operators, 6 arrays (0 quantized)
2019-09-23 16:48:57.056432: F tensorflow/lite/toco/tooling_util.cc:661] Check failed: dim >= 1 (0 vs. 1)
Fatal Python error: Aborted

Current thread 0x00007fffbc0853c0 (most recent call first):
  File "/Users/t.capes/miniconda3/lib/python3.7/site-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 52 in execute
  File "/Users/t.capes/miniconda3/lib/python3.7/site-packages/absl/app.py", line 251 in _run_main
  File "/Users/t.capes/miniconda3/lib/python3.7/site-packages/absl/app.py", line 300 in run
  File "/Users/t.capes/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/platform/app.py", line 40 in run
  File "/Users/t.capes/miniconda3/lib/python3.7/site-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 89 in main
  File "/Users/t.capes/miniconda3/bin/toco_from_protos", line 10 in <module>

**Comment by TimCapes** [comment]
Found issue, thought slice was supported but only strided_slice is.
```
import tensorflow.compat.v1 as tf
import numpy as np

tf.disable_v2_behavior()
initial_input = tf.placeholder(dtype=tf.float32, shape=(None,5,1024))
cap_i = tf.strided_slice(initial_input, [0,0,0], [0,5,1024], [1,1,1], shrink_axis_mask=1)
cap_i_reshaped =tf.reshape(cap_i,[1,5,1024])
cap_iT = tf.transpose(cap_i_reshaped, perm=[0,2,1])

sess = tf.Session()
sess.run(tf.global_variables_initializer())
tf.io.write_graph(sess.graph_def, '', 'train.pbtxt')
converter = tf.lite.TFLiteConverter.from_session(sess, [initial_input], [cap_iT])
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
tflite_model = converter.convert()
open('converted_model.tflite', "wb").write(tflite_model)
sess.close()
```
Works properly. Closing issue.
