### ISSUE TITLE
Mixnet graph freezing issue

### ISSUE THREAD

**Issue by dhananjaisharma10** [tensorflow/tensorflow#32791]
**System information**

- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 1.14.0
- Python version: 3.7.4
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
I have been trying to covert the [Mixnet](https://github.com/tensorflow/tpu/tree/master/models/official/mnasnet/mixnet) model to Core ML using the [tfcoreml](https://github.com/tf-coreml/tf-coreml) converter. I froze the graph, then tried converting it, and that's when I get thrown with the following error:
```
1199 ops in the final graph.

Loading the TF graph...
Graph Loaded.
Now finding ops in the TF graph that can be dropped for inference
Collecting all the 'Const' ops from the graph, by running it....
---------------------------------------------------------------------------
OutOfRangeError                           Traceback (most recent call last)
~/anaconda3/envs/tf/lib/python3.7/site-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1355     try:
-> 1356       return fn(*args)
   1357     except errors.OpError as e:

~/anaconda3/envs/tf/lib/python3.7/site-packages/tensorflow/python/client/session.py in _run_fn(feed_dict, fetch_list, target_list, options, run_metadata)
   1340       return self._call_tf_sessionrun(
-> 1341           options, feed_dict, fetch_list, target_list, run_metadata)
   1342 

~/anaconda3/envs/tf/lib/python3.7/site-packages/tensorflow/python/client/session.py in _call_tf_sessionrun(self, options, feed_dict, fetch_list, target_list, run_metadata)
   1428         self._session, options, feed_dict, fetch_list, target_list,
-> 1429         run_metadata)
   1430 

OutOfRangeError: Node 'mixnet-s/mixnet_model/stem/batch_normalization/FusedBatchNormV3' (type: 'Add', num of outputs: 1) does not have output 5

During handling of the above exception, another exception occurred:

OutOfRangeError                           Traceback (most recent call last)
<ipython-input-12-6b7b8d71599d> in <module>
     48                      mlmodel_path=ml_model,
     49                      output_feature_names=['logits'],
---> 50                      input_name_shape_dict={})

~/anaconda3/envs/tf/lib/python3.7/site-packages/tfcoreml/_tf_coreml_converter.py in convert(tf_model_path, mlmodel_path, output_feature_names, input_name_shape_dict, image_input_names, is_bgr, red_bias, green_bias, blue_bias, gray_bias, image_scale, class_labels, predicted_feature_name, predicted_probabilities_output, add_custom_layers, custom_conversion_functions, use_coreml_3)
    619       predicted_probabilities_output=predicted_probabilities_output,
    620       add_custom_layers=add_custom_layers,
--> 621       custom_conversion_functions=custom_conversion_functions)

~/anaconda3/envs/tf/lib/python3.7/site-packages/tfcoreml/_tf_coreml_converter.py in _convert_pb_to_mlmodel(tf_model_path, mlmodel_path, output_feature_names, input_name_shape_dict, image_input_names, is_bgr, red_bias, green_bias, blue_bias, gray_bias, image_scale, class_labels, predicted_feature_name, predicted_probabilities_output, add_custom_layers, custom_conversion_functions)
    260     else:
    261       const_tensor_names = []
--> 262     tensors_evaluated = sess.run(tensors, feed_dict=input_feed_dict)
    263     for i in range(len(tensor_names)):
    264       if tensor_names[i] not in SHAPE_DICT:

~/anaconda3/envs/tf/lib/python3.7/site-packages/tensorflow/python/client/session.py in run(self, fetches, feed_dict, options, run_metadata)
    948     try:
    949       result = self._run(None, fetches, feed_dict, options_ptr,
--> 950                          run_metadata_ptr)
    951       if run_metadata:
    952         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

~/anaconda3/envs/tf/lib/python3.7/site-packages/tensorflow/python/client/session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1171     if final_fetches or final_targets or (handle and feed_dict_tensor):
   1172       results = self._do_run(handle, final_targets, final_fetches,
-> 1173                              feed_dict_tensor, options, run_metadata)
   1174     else:
   1175       results = []

~/anaconda3/envs/tf/lib/python3.7/site-packages/tensorflow/python/client/session.py in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1348     if handle is None:
   1349       return self._do_call(_run_fn, feeds, fetches, targets, options,
-> 1350                            run_metadata)
   1351     else:
   1352       return self._do_call(_prun_fn, handle, feeds, fetches)

~/anaconda3/envs/tf/lib/python3.7/site-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1368           pass
   1369       message = error_interpolation.interpolate(message, self._graph)
-> 1370       raise type(e)(node_def, op, message)
   1371 
   1372   def _extend_graph(self):

OutOfRangeError: Node 'mixnet-s/mixnet_model/stem/batch_normalization/FusedBatchNormV3' (type: 'Add', num of outputs: 1) does not have output 5

```
I presume this is an issue with the way I am freezing the graph. The checkpoint was taken from the official [Mixnet](https://github.com/tensorflow/tpu/tree/master/models/official/mnasnet/mixnet) implementation. I am relatively new to TF and am still learning. Please help me resolve this issue and let me know in case further information is needed. Suggestions for converting to Core ML are also welcome. Thanks in advance!

**Code to reproduce the issue**
You might have to install TF 1.14.0
```python
import tensorflow as tf
import tfcoreml as tf_converter
from tensorflow.compat.v1 import graph_util

tf.logging.set_verbosity(tf.logging.ERROR)

# Download the checkpoint
model_name = 'mixnet-s'
!wget https://storage.googleapis.com/cloud-tpu-checkpoints/mixnet/{model_name}.tar.gz -O {model_name}.tar.gz
!tar -zxvf {model_name}.tar.gz
ckpt_dir = model_name

def _freeze_graph(model_folder):
    # Retrieve the checkpoint fullpath
    checkpoint = tf.train.get_checkpoint_state(model_folder)
    input_checkpoint = checkpoint.model_checkpoint_path
    
    # File fullname of the freezed graph
    absolute_model_folder = "/".join(input_checkpoint.split('/')[:-1])
    output_graph = absolute_model_folder + "/model.pb"

    # Before exporting the graph, get the output nodes
    output_node_names = "logits"

    # Clear devices to allow TF to control on which device it will load operations
    clear_devices = True
    
    # Import the meta graph and retrieve a Saver
    saver = tf.train.import_meta_graph(input_checkpoint + '.meta',
                                       clear_devices=clear_devices)

    # Retrieve the protobuf graph definition
    graph = tf.get_default_graph()
    input_graph_def = graph.as_graph_def()
    
    # Start a session and restore the graph weights
    with tf.Session() as sess:
        saver.restore(sess, input_checkpoint)

        # Use a built-in TF helper to export variables to constants
        output_graph_def = graph_util.convert_variables_to_constants(
            sess,
            input_graph_def, 
            output_node_names.split(",")
        ) 

        # Serialize and dump the output graph to the filesystem
        with tf.gfile.GFile(output_graph, "wb") as f:
            f.write(output_graph_def.SerializeToString())
        print("%d ops in the final graph." % len(output_graph_def.node))

_freeze_graph(ckpt_dir)

ml_model = 'mixnet-s/mixnet_core.mlmodel'
frozen_model = 'mixnet-s/model.pb'

tf_converter.convert(tf_model_path=frozen_model,
                     mlmodel_path=ml_model,
                     output_feature_names=['logits'],
                     input_name_shape_dict={})
```

**Comment by oanush** [comment]
@dhananjaisharma10,
Thanks for reporting the issue, Can you provide a simple and standalone code to reproduce the issue?

**Comment by dhananjaisharma10** [comment]
> @dhananjaisharma10,
> Thanks for reporting the issue, Can you provide a simple and standalone code to reproduce the issue?

**Comment by dhananjaisharma10** [comment]
> @dhananjaisharma10,
> Thanks for reporting the issue, Can you provide a simple and standalone code to reproduce the issue?

I have updated the "code to reproduce". Please let me know if you have trouble running it.

**Comment by oanush** [comment]
Thank you for updating the code,Issue replicating for TF-1.14 and TF-1.15rc1, kindly find the [gist](https://colab.sandbox.google.com/gist/oanush/d7823c31df1fdad9513663c91ee07528/32791.ipynb) of colab.Thanks!

**Comment by ymodak** [comment]
Have you considered using ```freeze_graph``` function to convert your checkpoint model to frozen model.
You can try,
```python
from tensorflow.python.tools import freeze_graph
```
https://github.com/tensorflow/tensorflow/blob/f718c5af3706d99d2acb70d27cb79231650e468b/tensorflow/python/tools/freeze_graph.py#L286

**Comment by dhananjaisharma10** [comment]
> Have you considered using `freeze_graph` function to convert your checkpoint model to frozen model.
> You can try,
> 
> ```python
> from tensorflow.python.tools import freeze_graph
> ```
> 
> https://github.com/tensorflow/tensorflow/blob/f718c5af3706d99d2acb70d27cb79231650e468b/tensorflow/python/tools/freeze_graph.py#L286

Yes, I have been using that as well, but was facing some issues. I was able to convert the model to Core ML without using the BN layers. I am yet to try this _with_ BN. Will update this soon.

**Comment by dhananjaisharma10** [comment]
> Have you considered using `freeze_graph` function to convert your checkpoint model to frozen model.
> You can try,
> 
> ```python
> from tensorflow.python.tools import freeze_graph
> ```
> 
> https://github.com/tensorflow/tensorflow/blob/f718c5af3706d99d2acb70d27cb79231650e468b/tensorflow/python/tools/freeze_graph.py#L286

Hi!

I tried freezing the graph with as you suggested, but I am getting the following error:
```
WARNING:tensorflow:From freeze.py:247: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

WARNING:tensorflow:From freeze.py:247: The name tf.logging.ERROR is deprecated. Please use tf.compat.v1.logging.ERROR instead.

2019-10-04 21:24:21.124841: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-10-04 21:24:21.147115: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3192000000 Hz
2019-10-04 21:24:21.148346: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5634b8da0430 executing computations on platform Host. Devices:
2019-10-04 21:24:21.148384: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
2019-10-04 21:24:21.522500: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1412] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set.  If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.
Traceback (most recent call last):
  File "freeze.py", line 263, in <module>
    feed_dict={'X:0': X})
  File "freeze.py", line 238, in _simple_run_and_freeze
    initializer_nodes="")
  File "/home/dhananjai/anaconda3/envs/tf/lib/python3.7/site-packages/tensorflow/python/tools/freeze_graph.py", line 361, in freeze_graph
    checkpoint_version=checkpoint_version)
  File "/home/dhananjai/anaconda3/envs/tf/lib/python3.7/site-packages/tensorflow/python/tools/freeze_graph.py", line 190, in freeze_graph_with_def_protos
    var_list=var_list, write_version=checkpoint_version)
  File "/home/dhananjai/anaconda3/envs/tf/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 825, in __init__
    self.build()
  File "/home/dhananjai/anaconda3/envs/tf/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 837, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/dhananjai/anaconda3/envs/tf/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 875, in _build
    build_restore=build_restore)
  File "/home/dhananjai/anaconda3/envs/tf/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 482, in _build_internal
    names_to_saveables)
  File "/home/dhananjai/anaconda3/envs/tf/lib/python3.7/site-packages/tensorflow/python/training/saving/saveable_object_util.py", line 342, in validate_and_slice_inputs
    for converted_saveable_object in saveable_objects_for_op(op, name):
  File "/home/dhananjai/anaconda3/envs/tf/lib/python3.7/site-packages/tensorflow/python/training/saving/saveable_object_util.py", line 205, in saveable_objects_for_op
    variable, "", name)
  File "/home/dhananjai/anaconda3/envs/tf/lib/python3.7/site-packages/tensorflow/python/training/saving/saveable_object_util.py", line 82, in __init__
    self.handle_op = var.op.inputs[0]
  File "/home/dhananjai/anaconda3/envs/tf/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 2410, in __getitem__
    return self._inputs[i]
IndexError: list index out of range
```

**Code to reproduce the error:**
```python
# You will have to work in the mixnet directory in tensorflow/tpu
import os.path as osp
import tempfile
import shutil

import numpy as np
import tensorflow as tf
from mixnet_builder import build_model
from tensorflow.python.tools.freeze_graph import freeze_graph


# A utility function to freeze rhe graph. It will be used later
def _simple_run_and_freeze(graph,
                           output_name,
                           frozen_model_file='',
                           feed_dict={}):
    model_dir = tempfile.mkdtemp()
    graph_def_file = osp.join(model_dir, 'tf_graph.pbtxt')
    checkpoint_file = osp.join(model_dir, 'tf_model.ckpt')

    tf.reset_default_graph()
    with graph.as_default() as g:
        saver = tf.train.Saver()
    with tf.Session(graph=graph) as sess:
        # initialize
        sess.run(tf.global_variables_initializer())
        # run the result
        fetch = graph.get_operation_by_name(output_name).outputs[0]
        tf_result = sess.run(fetch, feed_dict=feed_dict)
        # save graph definition somewhere
        tf.train.write_graph(sess.graph, model_dir, graph_def_file)
        # save the weights
        saver.save(sess, checkpoint_file)

    freeze_graph(input_graph=graph_def_file,
                 input_saver="",
                 input_binary=False,
                 input_checkpoint=checkpoint_file,
                 output_node_names=output_name,
                 restore_op_name="save/restore_all",
                 filename_tensor_name="save/Const:0",
                 output_graph=frozen_model_file,
                 clear_devices=True,
                 initializer_nodes="")

    if osp.exists(model_dir):
        shutil.rmtree(model_dir)

    return tf_result


if __name__ == '__main__':
    tf.logging.set_verbosity(tf.logging.ERROR)
    BATCH_SIZE = 20
    DIM1 = DIM2 = 224
    # define a TF graph: input -> MixNet -> output
    graph = tf.Graph()
    with graph.as_default() as g:
        inputs = tf.placeholder(tf.float32, shape=[BATCH_SIZE, DIM1, DIM2, 3],
                                name='X')
        logits, _ = build_model(inputs, 'mixnet-s', False)

    output_name = logits.op.name
    X = np.random.randn(BATCH_SIZE, DIM1, DIM2, 3)
    frozen_model_file = 'mixnet_s_graph.pb'
    out = _simple_run_and_freeze(graph,
                                 output_name,
                                 frozen_model_file,
                                 feed_dict={'X:0': X})

```
This seems something specific to the mixnet code, but please let me know if you have any pointers/

Thanks in advance!

**Comment by gargn** [comment]
Can you validate that the `feed_dict` is in the graph that is being passed to `freeze_graph` and that the input arrays didn't get renamed. If that doesn't work, can you provide the checkpoint and pbtxt files as well as visibility into the code that's in `build_model` (imported by `mixnet_builder`) so that we can reproduce this issue.

**Comment by dhananjaisharma10** [comment]
> Can you validate that the `feed_dict` is in the graph that is being passed to `freeze_graph` and that the input arrays didn't get renamed. If that doesn't work, can you provide the checkpoint and pbtxt files as well as visibility into the code that's in `build_model` (imported by `mixnet_builder`) so that we can reproduce this issue.

Hi sir! The `feed_dict` is still there. I visualized the `.pb` file and the input and output are indeed `X` and `logits`, respectively. You can find the checkpoint for the error in the first post in this page [here](https://storage.googleapis.com/cloud-tpu-checkpoints/mixnet/mixnet-s.tar.gz). I trained on normal distribution to get around that with the following script: [train.py.zip](https://github.com/tensorflow/tensorflow/files/3774270/train.py.zip). The code for `build_model` can be found [here](https://github.com/tensorflow/tpu/tree/master/models/official/mnasnet/mixnet). Looking forward to hearing from you.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
