### ISSUE TITLE
Send/Recv of collective_ops hangs in a distributed environment 

### ISSUE THREAD

**Issue by whhu** [tensorflow/tensorflow#32810]
**System information**
- Have I written custom code: Yes
- OS Platform and Distribution: Linux CentOS 7.6.1810
- Mobile device if the issue happens on mobile device: No
- TensorFlow installed from: Binary
- TensorFlow version: v1.13.1-0-g6612da8951
- Python version: 3.6.8
- Bazel version: None
- GCC/Compiler version: None
- CUDA/cuDNN version: None
- GPU model and memory: None

**Describe the current behavior**

The monitored session hangs in there fetching the send/recv tensors of `collective_ops`. The same code works well for fetching `all_reduce` tensors.

**Describe the expected behavior**

The send/recv tensors `tensors` gives proper answer on all workers.

**Code to reproduce the issue**
```python
"""Illustrate send/recv in collective_ops"""

MP_METHOD = 'fork'  # 'fork' (UNIX), 'spawn' (WINDOWS);
NUM_PROCESSES = 2
JOB = 'worker'

def process_fn(hosts, task_index):
    """process fn"""
    import time
    import tensorflow as tf
    from tensorflow.python.ops import collective_ops

    cluster_spec = tf.train.ClusterSpec({JOB: hosts})
    host_devices = list()
    for task, _ in enumerate(hosts):
        host_devices.append(tf.DeviceSpec(
            job=JOB, replica=0, task=task, device_type='cpu', device_index=0))
    chief_host_device = host_devices[0]

    # unconfigured collective_group_leader make each worker the leader
    # '/replica:0' is necessary in the configuration.
    collective_group_leader, _, _ = \
        chief_host_device.to_string().partition('/device')
    config = tf.ConfigProto()
    config.experimental.collective_group_leader = collective_group_leader
    server = tf.train.Server(cluster_spec, config=config,
                             job_name=JOB, task_index=task_index)
    run_options = tf.RunOptions()
    run_options.experimental.collective_graph_key = 1
    with tf.Graph().as_default():
        weights = list()
        tensors = list()
        instance_key = 1
        for task, device in enumerate(host_devices):
            with tf.device(device), tf.variable_scope('{}{}'.format(JOB, task)):
                weight = tf.get_variable('weight', shape=[])
                weights.append(weight)

                # send/recv
                if task == task_index:
                    tensor = collective_ops.broadcast_send(
                        weight, weight.shape, weight.dtype,
                        len(hosts), 1, instance_key)
                else:
                    tensor = collective_ops.broadcast_recv(
                        weight.shape, weight.dtype,
                        len(hosts), 1, instance_key)
                tensors.append(tensor)
                instance_key += 1

#                # allreduce
#                if task == task_index:
#                    tensor = collective_ops.all_reduce(
#                        weight, len(hosts), 0, instance_key, 'Add', 'Div')
#                    tensors.append(tensor)
#                    instance_key += 1

        if task_index == 0:
            session_creator = tf.train.ChiefSessionCreator(
                master=server.target)
        else:
            session_creator = tf.train.WorkerSessionCreator(
                master=server.target)
        with tf.train.MonitoredSession(session_creator=session_creator) \
                as mon_sess:
            print('task {} running.'.format(task_index))
            result_weights = mon_sess.run(weights, options=run_options)
            print('task {} sense {}'.format(task_index, result_weights))
            result_tensors = mon_sess.run(tensors, options=run_options)
            print('task {} broadcast {}'.format(task_index, result_tensors))
            time.sleep(10)

def start_process():
    """start process"""
    import time
    import multiprocessing as mp

    port = 60000
    host_fmt = 'localhost:{}'
    hosts = list()
    for process_index in range(NUM_PROCESSES):
        hosts.append(host_fmt.format(port + process_index))
    mp_ctx = mp.get_context(MP_METHOD)
    processes = list()
    for process_index in range(NUM_PROCESSES):
        process = mp_ctx.Process(target=process_fn,
                                 args=(hosts, process_index,))
        processes.append(process)
        process.start()
        time.sleep(0.1)
    for process in processes:
        process.join()

if __name__ == '__main__':
    start_process()
```

**Other info / logs**
```console
(tf-1.13-py3) [huwh1@huwh1-centos worksync]$ python tf_distribute_collective_ops_sendrecv.py 
2019-09-25 17:46:29.612863: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-09-25 17:46:29.625630: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3408000000 Hz
2019-09-25 17:46:29.625962: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x2c2e220 executing computations on platform Host. Devices:
2019-09-25 17:46:29.625984: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
2019-09-25 17:46:29.627731: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:252] Initialize GrpcChannelCache for job worker -> {0 -> localhost:60000, 1 -> localhost:60001}
2019-09-25 17:46:29.628640: I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:391] Started server with target: grpc://localhost:60000
WARNING:tensorflow:From /home/huwh1/virtualenv/tf-1.13-py3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
2019-09-25 17:46:29.696555: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-09-25 17:46:29.709593: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3408000000 Hz
2019-09-25 17:46:29.709906: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x2c2e410 executing computations on platform Host. Devices:
2019-09-25 17:46:29.709932: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
2019-09-25 17:46:29.711328: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:252] Initialize GrpcChannelCache for job worker -> {0 -> localhost:60000, 1 -> localhost:60001}
2019-09-25 17:46:29.712186: I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:391] Started server with target: grpc://localhost:60001
WARNING:tensorflow:From /home/huwh1/virtualenv/tf-1.13-py3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
2019-09-25 17:46:29.741447: I tensorflow/core/distributed_runtime/master_session.cc:1192] Start master session 22dc988b8d402f7f with config: experimental { collective_group_leader: "/job:worker/replica:0/task:0" }
task 0 running.
task 0 sense [-0.30021727, -0.797495]
2019-09-25 17:46:29.798887: I tensorflow/core/distributed_runtime/master_session.cc:1192] Start master session bedba16e0ccc4c27 with config: experimental { collective_group_leader: "/job:worker/replica:0/task:0" }
task 1 running.
2019-09-25 17:46:29.820772: I tensorflow/core/distributed_runtime/base_rendezvous_mgr.cc:159] Skipping rendezvous re-initialization.
2019-09-25 17:46:29.820874: I tensorflow/core/distributed_runtime/base_rendezvous_mgr.cc:159] Skipping rendezvous re-initialization.
2019-09-25 17:46:29.821341: W tensorflow/core/common_runtime/base_collective_executor.cc:203] BaseCollectiveExecutor::StartAbort Aborted: Cleanup 70896605979375878
	 [[{{node worker1/CollectiveBcastRecv}}]]
task 1 sense [-0.30021727, -0.797495]
```
There is a related issue #31913, which can be solved by specifying the `experimental.collective_group_leader` in [tf.ConfigProto](https://www.tensorflow.org/api_docs/python/tf/ConfigProto/Experimental#collective_group_leader).
An info about `rendezvous re-initialization` and a warning about`BaseCollectiveExecutor` are raised from the `send/recv`. Nevertheless, the script works fine for the commented `allreduce`.

**Comment by whhu** [comment]
Could you please take a look at this issue and the related #31913? @dubey

**Comment by dubey** [comment]
In this case it looks like you're actually creating 2 instances of broadcast collectives, but assigning both of them the same instance key.  A group defines a set of devices participating in a collective op, an instance is a specific collective, like a single all-reduce or a single broadcast.  In this case there is an instance in which task 0 sends and task 1 receives, and there is another instance in which task 0 receives and task 1 sends.  They should have separate instance keys.

**Comment by whhu** [comment]
Thank you very much for the fast reply! @dubey I improve the code and come across another problem. The script is simplified to keep only one variable named 'weight' on each worker, and every worker creates its own chief session to initialize the variable. The code of `send/recv` is improved by creating **a pair** of tensors of the sending and the receiving with **the same** `instance_key`. When worker0 sends and worker1 receives, it exits successfully without warnings.

Unfortunately and _ridiculously_, it fails with worker0 as the receiver and worker1 as the sender, with the error `Instance 0 found no source for broadcast`. It seems the `send_tensor` on worker1 is unregistered in the send/recv pair. If `collective_group_leader` is set to worker1, the process raises the same error when `if task_index == 0`, but hangs when `if task_index == 1`.

script snippet:
```python
        # send/recv
        instance_key = 0
        with tf.device(host_devices[task_index]), \
                tf.variable_scope('{}{}'.format(JOB, task_index)):
            weight = tf.get_variable('weight', shape=[])
            weights.append(weight)
            send_tensor = collective_ops.broadcast_send(
                weight, weight.shape, weight.dtype,
                len(hosts), 0, instance_key)
            recv_tensor = collective_ops.broadcast_recv(
                weight.shape, weight.dtype,
                len(hosts), 0, instance_key)
            instance_key += 1
            if task_index == 0:  # fails when 'task_index == 1'
                tensors.append(send_tensor)
            else:
                tensors.append(recv_tensor)
```

success log when `if task_index == 0:`:
```console
task 1 running.
task 1 sense [0.825487]
task 0 running.
task 0 sense [-1.5433102]
task 0 broadcast [-1.5433102]
task 1 broadcast [-1.5433102]
```

failure log when `if task_index == 1:`:
```console
task 1 running.
task 1 sense [1.0812124]
task 0 running.
task 0 sense [0.3877238]
2019-09-26 10:51:21.474402: W tensorflow/core/common_runtime/base_collective_executor.cc:203] BaseCollectiveExecutor::StartAbort Internal: Instance 0 found no source for broadcast.  This could mean that there were group_size=2 BcastRecvs but no BcastSend.
	 [[{{node worker0/CollectiveBcastRecv}}]]
2019-09-26 10:51:21.474438: W tensorflow/core/common_runtime/base_collective_executor.cc:203] BaseCollectiveExecutor::StartAbort Internal: Instance 0 found no source for broadcast.  This could mean that there were group_size=2 BcastRecvs but no BcastSend.
	 [[{{node worker1/CollectiveBcastSend}}]]
Process ForkProcess-1:
Process ForkProcess-2:
```
The full script and logs of success and failure are attached below.
```python
"""Illustrate send/recv in collective_ops"""

MP_METHOD = 'fork'  # 'fork' (UNIX), 'spawn' (WINDOWS);
NUM_PROCESSES = 2
JOB = 'worker'

def process_fn(hosts, task_index):
    """process fn"""
    import time
    import tensorflow as tf
    from tensorflow.python.ops import collective_ops

    cluster_spec = tf.train.ClusterSpec({JOB: hosts})
    host_devices = list()
    for task, _ in enumerate(hosts):
        host_devices.append(tf.DeviceSpec(
            job=JOB, replica=0, task=task, device_type='cpu', device_index=0))
    chief_host_device = host_devices[0]

    # unconfigured collective_group_leader make each worker the leader
    # '/replica:0' is necessary in the configuration.
    collective_group_leader, _, _ = \
        chief_host_device.to_string().partition('/device')
    config = tf.ConfigProto()
    config.experimental.collective_group_leader = collective_group_leader
    server = tf.train.Server(cluster_spec, config=config,
                             job_name=JOB, task_index=task_index)
    run_options = tf.RunOptions()
    run_options.experimental.collective_graph_key = 1
    with tf.Graph().as_default():
        weights = list()
        tensors = list()
        
        # send/recv
        instance_key = 0
        with tf.device(host_devices[task_index]), \
                tf.variable_scope('{}{}'.format(JOB, task_index)):
            weight = tf.get_variable('weight', shape=[])
            weights.append(weight)
            send_tensor = collective_ops.broadcast_send(
                weight, weight.shape, weight.dtype,
                len(hosts), 0, instance_key)
            recv_tensor = collective_ops.broadcast_recv(
                weight.shape, weight.dtype,
                len(hosts), 0, instance_key)
            instance_key += 1
            if task_index == 1:
                tensors.append(send_tensor)
            else:
                tensors.append(recv_tensor)

#        if task_index == 0:
#            session_creator = tf.train.ChiefSessionCreator(
#                master=server.target)
#        else:
#            session_creator = tf.train.WorkerSessionCreator(
#                master=server.target)
        session_creator = tf.train.ChiefSessionCreator(
            master=server.target)
        with tf.train.MonitoredSession(session_creator=session_creator) \
                as mon_sess:
            print('task {} running.'.format(task_index))
            result_weights = mon_sess.run(weights, options=run_options)
            print('task {} sense {}'.format(task_index, result_weights))
            result_tensors = mon_sess.run(tensors, options=run_options)
            print('task {} broadcast {}'.format(task_index, result_tensors))
            time.sleep(1)

def start_process():
    """start process"""
    import time
    import multiprocessing as mp

    port = 60000
    host_fmt = 'localhost:{}'
    hosts = list()
    for process_index in range(NUM_PROCESSES):
        hosts.append(host_fmt.format(port + process_index))
    mp_ctx = mp.get_context(MP_METHOD)
    processes = list()
    for process_index in range(NUM_PROCESSES):
        process = mp_ctx.Process(target=process_fn,
                                 args=(hosts, process_index,))
        processes.append(process)
        process.start()
        time.sleep(0.1)
    for process in processes:
        process.join()

if __name__ == '__main__':
    start_process()
```
full success log:
```console
(tf-1.13-py3) [huwh1@huwh1-centos worksync]$ python tf_distribute_collective_ops_sendrecv.py 
2019-09-26 10:32:41.825361: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-09-26 10:32:41.838175: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3408000000 Hz
2019-09-26 10:32:41.838505: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x2da1270 executing computations on platform Host. Devices:
2019-09-26 10:32:41.838533: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
2019-09-26 10:32:41.840395: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:252] Initialize GrpcChannelCache for job worker -> {0 -> localhost:60000, 1 -> localhost:60001}
2019-09-26 10:32:41.841263: I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:391] Started server with target: grpc://localhost:60000
WARNING:tensorflow:From /home/huwh1/virtualenv/tf-1.13-py3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
2019-09-26 10:32:41.913407: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-09-26 10:32:41.925525: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3408000000 Hz
2019-09-26 10:32:41.925829: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x2da1200 executing computations on platform Host. Devices:
2019-09-26 10:32:41.925857: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
2019-09-26 10:32:41.927326: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:252] Initialize GrpcChannelCache for job worker -> {0 -> localhost:60000, 1 -> localhost:60001}
2019-09-26 10:32:41.928167: I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:391] Started server with target: grpc://localhost:60001
WARNING:tensorflow:From /home/huwh1/virtualenv/tf-1.13-py3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
2019-09-26 10:32:41.998983: I tensorflow/core/distributed_runtime/master_session.cc:1192] Start master session e57a61876767fe8a with config: experimental { collective_group_leader: "/job:worker/replica:0/task:0" }
2019-09-26 10:32:42.918306: I tensorflow/core/distributed_runtime/master_session.cc:1192] Start master session d36eb78a8ccde9b9 with config: experimental { collective_group_leader: "/job:worker/replica:0/task:0" }
task 1 running.
task 1 sense [0.825487]
task 0 running.
task 0 sense [-1.5433102]
task 0 broadcast [-1.5433102]
task 1 broadcast [-1.5433102]
```
full failure log:
```console
(tf-1.13-py3) [huwh1@huwh1-centos worksync]$ python tf_distribute_collective_ops_sendrecv.py 
2019-09-26 10:51:20.319482: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-09-26 10:51:20.333906: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3408000000 Hz
2019-09-26 10:51:20.334383: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x31fed80 executing computations on platform Host. Devices:
2019-09-26 10:51:20.334424: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
2019-09-26 10:51:20.336501: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:252] Initialize GrpcChannelCache for job worker -> {0 -> localhost:60000, 1 -> localhost:60001}
2019-09-26 10:51:20.337508: I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:391] Started server with target: grpc://localhost:60000
WARNING:tensorflow:From /home/huwh1/virtualenv/tf-1.13-py3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
2019-09-26 10:51:20.404411: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-09-26 10:51:20.417182: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3408000000 Hz
2019-09-26 10:51:20.417500: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x31ff210 executing computations on platform Host. Devices:
2019-09-26 10:51:20.417536: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
2019-09-26 10:51:20.419285: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:252] Initialize GrpcChannelCache for job worker -> {0 -> localhost:60000, 1 -> localhost:60001}
2019-09-26 10:51:20.420258: I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:391] Started server with target: grpc://localhost:60001
WARNING:tensorflow:From /home/huwh1/virtualenv/tf-1.13-py3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
2019-09-26 10:51:20.490274: I tensorflow/core/distributed_runtime/master_session.cc:1192] Start master session 568c3548db581180 with config: experimental { collective_group_leader: "/job:worker/replica:0/task:0" }
2019-09-26 10:51:21.416032: I tensorflow/core/distributed_runtime/master_session.cc:1192] Start master session ff0f7c9a1e31db0d with config: experimental { collective_group_leader: "/job:worker/replica:0/task:0" }
task 1 running.
task 1 sense [1.0812124]
task 0 running.
task 0 sense [0.3877238]
2019-09-26 10:51:21.474402: W tensorflow/core/common_runtime/base_collective_executor.cc:203] BaseCollectiveExecutor::StartAbort Internal: Instance 0 found no source for broadcast.  This could mean that there were group_size=2 BcastRecvs but no BcastSend.
	 [[{{node worker0/CollectiveBcastRecv}}]]
2019-09-26 10:51:21.474438: W tensorflow/core/common_runtime/base_collective_executor.cc:203] BaseCollectiveExecutor::StartAbort Internal: Instance 0 found no source for broadcast.  This could mean that there were group_size=2 BcastRecvs but no BcastSend.
	 [[{{node worker1/CollectiveBcastSend}}]]
Process ForkProcess-1:
Process ForkProcess-2:
Traceback (most recent call last):
  File "/home/huwh1/virtualenv/tf-1.13-py3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/home/huwh1/virtualenv/tf-1.13-py3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/huwh1/virtualenv/tf-1.13-py3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InternalError: Instance 0 found no source for broadcast.  This could mean that there were group_size=2 BcastRecvs but no BcastSend.
	 [[{{node worker0/CollectiveBcastRecv}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/huwh1/virtualenv/tf-1.13-py3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/home/huwh1/virtualenv/tf-1.13-py3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/huwh1/virtualenv/tf-1.13-py3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "tf_distribute_collective_ops_sendrecv.py", line 129, in process_fn
    result_tensors = mon_sess.run(tensors, options=run_options)
  File "/home/huwh1/virtualenv/tf-1.13-py3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 676, in run
    run_metadata=run_metadata)
tensorflow.python.framework.errors_impl.InternalError: Instance 0 found no source for broadcast.  This could mean that there were group_size=2 BcastRecvs but no BcastSend.
	 [[{{node worker1/CollectiveBcastSend}}]]
  File "/home/huwh1/virtualenv/tf-1.13-py3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1171, in run
    run_metadata=run_metadata)
  File "/home/huwh1/virtualenv/tf-1.13-py3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1270, in run
    raise six.reraise(*original_exc_info)

During handling of the above exception, another exception occurred:

  File "/home/huwh1/virtualenv/tf-1.13-py3/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
Traceback (most recent call last):
  File "/home/huwh1/virtualenv/tf-1.13-py3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1255, in run
    return self._sess.run(*args, **kwargs)
  File "/home/huwh1/virtualenv/tf-1.13-py3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1327, in run
    run_metadata=run_metadata)
  File "/home/huwh1/virtualenv/tf-1.13-py3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1091, in run
    return self._sess.run(*args, **kwargs)
  File "/home/huwh1/virtualenv/tf-1.13-py3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/huwh1/virtualenv/tf-1.13-py3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/huwh1/virtualenv/tf-1.13-py3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/huwh1/virtualenv/tf-1.13-py3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
tensorflow.python.framework.errors_impl.InternalError: Instance 0 found no source for broadcast.  This could mean that there were group_size=2 BcastRecvs but no BcastSend.
	 [[node worker0/CollectiveBcastRecv (defined at tf_distribute_collective_ops_sendrecv.py:45) ]]

Caused by op 'worker0/CollectiveBcastRecv', defined at:
  File "tf_distribute_collective_ops_sendrecv.py", line 155, in <module>
    start_process()
  File "tf_distribute_collective_ops_sendrecv.py", line 149, in start_process
    process.start()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/lib64/python3.6/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/lib64/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib64/python3.6/multiprocessing/popen_fork.py", line 73, in _launch
    code = process_obj._bootstrap()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "tf_distribute_collective_ops_sendrecv.py", line 45, in process_fn
    len(hosts), 0, instance_key)
  File "/home/huwh1/virtualenv/tf-1.13-py3/lib/python3.6/site-packages/tensorflow/python/ops/collective_ops.py", line 133, in broadcast_recv
    instance_key=instance_key)
  File "/home/huwh1/virtualenv/tf-1.13-py3/lib/python3.6/site-packages/tensorflow/python/ops/gen_collective_ops.py", line 74, in collective_bcast_recv
    shape=shape, name=name)
  File "/home/huwh1/virtualenv/tf-1.13-py3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/home/huwh1/virtualenv/tf-1.13-py3/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/huwh1/virtualenv/tf-1.13-py3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/home/huwh1/virtualenv/tf-1.13-py3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

InternalError (see above for traceback): Instance 0 found no source for broadcast.  This could mean that there were group_size=2 BcastRecvs but no BcastSend.
	 [[node worker0/CollectiveBcastRecv (defined at tf_distribute_collective_ops_sendrecv.py:45) ]]

  File "/usr/lib64/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "tf_distribute_collective_ops_sendrecv.py", line 129, in process_fn
    result_tensors = mon_sess.run(tensors, options=run_options)
  File "/home/huwh1/virtualenv/tf-1.13-py3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 676, in run
    run_metadata=run_metadata)
  File "/home/huwh1/virtualenv/tf-1.13-py3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1171, in run
    run_metadata=run_metadata)
  File "/home/huwh1/virtualenv/tf-1.13-py3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1270, in run
    raise six.reraise(*original_exc_info)
  File "/home/huwh1/virtualenv/tf-1.13-py3/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/huwh1/virtualenv/tf-1.13-py3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1255, in run
    return self._sess.run(*args, **kwargs)
  File "/home/huwh1/virtualenv/tf-1.13-py3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1327, in run
    run_metadata=run_metadata)
  File "/home/huwh1/virtualenv/tf-1.13-py3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1091, in run
    return self._sess.run(*args, **kwargs)
  File "/home/huwh1/virtualenv/tf-1.13-py3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/huwh1/virtualenv/tf-1.13-py3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/huwh1/virtualenv/tf-1.13-py3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/huwh1/virtualenv/tf-1.13-py3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Instance 0 found no source for broadcast.  This could mean that there were group_size=2 BcastRecvs but no BcastSend.
	 [[node worker1/CollectiveBcastSend (defined at tf_distribute_collective_ops_sendrecv.py:42) ]]

Caused by op 'worker1/CollectiveBcastSend', defined at:
  File "tf_distribute_collective_ops_sendrecv.py", line 155, in <module>
    start_process()
  File "tf_distribute_collective_ops_sendrecv.py", line 149, in start_process
    process.start()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/lib64/python3.6/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/lib64/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib64/python3.6/multiprocessing/popen_fork.py", line 73, in _launch
    code = process_obj._bootstrap()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "tf_distribute_collective_ops_sendrecv.py", line 42, in process_fn
    len(hosts), 0, instance_key)
  File "/home/huwh1/virtualenv/tf-1.13-py3/lib/python3.6/site-packages/tensorflow/python/ops/collective_ops.py", line 105, in broadcast_send
    instance_key=instance_key)
  File "/home/huwh1/virtualenv/tf-1.13-py3/lib/python3.6/site-packages/tensorflow/python/ops/gen_collective_ops.py", line 152, in collective_bcast_send
    shape=shape, name=name)
  File "/home/huwh1/virtualenv/tf-1.13-py3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/home/huwh1/virtualenv/tf-1.13-py3/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/huwh1/virtualenv/tf-1.13-py3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/home/huwh1/virtualenv/tf-1.13-py3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

InternalError (see above for traceback): Instance 0 found no source for broadcast.  This could mean that there were group_size=2 BcastRecvs but no BcastSend.
	 [[node worker1/CollectiveBcastSend (defined at tf_distribute_collective_ops_sendrecv.py:42) ]]
```

**Comment by whhu** [comment]
It seems only the `collective_group_leader` can trigger the `broadcast_send` ...

**Comment by dubey** [comment]
Thanks for the report.  I'll look into this a bit more and get back to you.
