### ISSUE TITLE
TfLite ObjectDetection Demo crashed on Android with armeabi

### ISSUE THREAD

**Issue by WestbrookZero** [tensorflow/tensorflow#32830]
java.lang.UnsatisfiedLinkError: No implementation found for long org.tensorflow.lite.NativeInterpreterWrapper.createErrorReporter(int) (tried Java_org_tensorflow_lite_NativeInterpreterWrapper_createErrorReporter and Java_org_tensorflow_lite_NativeInterpreterWrapper_createErrorReporter__I)
        at org.tensorflow.lite.NativeInterpreterWrapper.createErrorReporter(Native Method)
        at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:71)
        at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:52)
        at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:114)
        at com.tfdetection.tflite.TFLiteObjectDetectionAPIModel.create(TFLiteObjectDetectionAPIModel.java:123)

**Comment by gadagashwini** [comment]
@WestbrookZero,
Provide the exact sequence of commands / steps that you executed before running into the problem. Thanks!

**Comment by gadagashwini** [comment]
@WestbrookZero, Please elaborate the issue with context. Thanks!
