### ISSUE TITLE
tf.lite not support Merge, RandomUniform, Switch

### ISSUE THREAD

**Issue by egolearner** [tensorflow/tensorflow#32898]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS 7
- TensorFlow installed from (source or binary): binary
- TensorFlow version (or github SHA if from source): 1.14.0

**Provide the text output from tflite_convert**

```
2019-09-29 11:27:27.677102: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 4963 operators, 8473 arrays (0 quantized)
2019-09-29 11:27:28.107098: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After Removing unused ops pass 1: 4959 operators, 8467 arrays (0 quantized)
2019-09-29 11:27:28.858936: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 4959 operators, 8467 arrays (0 quantized)
2019-09-29 11:27:29.762413: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 1: 4823 operators, 8044 arrays (0 quantized)
2019-09-29 11:27:30.695850: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Group bidirectional sequence lstm/rnn: 4823 operators, 8044 arrays (0 quantized)
2019-09-29 11:27:31.376652: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before dequantization graph transformations: 4823 operators, 8044 arrays (0 quantized)
2019-09-29 11:27:31.590536: I tensorflow/lite/toco/allocate_transient_arrays.cc:345] Total transient array allocated size: 19328 bytes, theoretical optimal value: 2048 bytes.
2019-09-29 11:27:31.918181: E tensorflow/lite/toco/toco_tooling.cc:456] We are continually in the process of adding support to TensorFlow Lite for more ops. It would be helpful if you could inform us of how this conversion went by opening a github issue at https://github.com/tensorflow/tensorflow/issues/new?template=40-tflite-op-request.md
 and pasting the following:

Some of the operators in the model are not supported by the standard TensorFlow Lite runtime and are not recognized by TensorFlow. If you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, CAST, CONCATENATION, FLOOR, FULLY_CONNECTED, GATHER, GREATER_EQUAL, LOGISTIC, MUL, PACK, REDUCE_PROD, RESHAPE, SELECT, SHAPE, SLICE, STRIDED_SLICE, SUM, TILE, UNIQUE, WHERE, ZEROS_LIKE. Here is a list of operators for which you will need custom implementations: Merge, RandomUniform, Switch.
Traceback (most recent call last):
  File "/home/user/.local/bin/toco_from_protos", line 11, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 59, in main
    app.run(main=execute, argv=[sys.argv[0]] + unparsed)
  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 33, in execute
    output_str = tensorflow_wrap_toco.TocoConvert(model_str, toco_str, input_str)
Exception: We are continually in the process of adding support to TensorFlow Lite for more ops. It would be helpful if you could inform us of how this conversion went by opening a github issue at https://github.com/tensorflow/tensorflow/issues/new?template=40-tflite-op-request.md
 and pasting the following:

Some of the operators in the model are not supported by the standard TensorFlow Lite runtime and are not recognized by TensorFlow. If you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, CAST, CONCATENATION, FLOOR, FULLY_CONNECTED, GATHER, GREATER_EQUAL, LOGISTIC, MUL, PACK, REDUCE_PROD, RESHAPE, SELECT, SHAPE, SLICE, STRIDED_SLICE, SUM, TILE, UNIQUE, WHERE, ZEROS_LIKE. Here is a list of operators for which you will need custom implementations: Merge, RandomUniform, Switch.
```

Also, please include a link to a GraphDef or the model if possible.

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

```python
converter = tf.lite.TFLiteConverter.from_saved_model(
    model_path, input_arrays=input_arrays, output_arrays=output_arrays)
converter.post_training_quantize=True
converter.target_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,
                                       tf.lite.OpsSet.SELECT_TF_OPS]
tflite_quantized_model = converter.convert()
open("quantized_model.tflite", "wb").write(tflite_quantized_model)
```

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
