### ISSUE TITLE
ImportError: /usr/local/lib/python3.5/dist-packages/tensorflow/python/_pywrap_tensorflow.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Srikanth-Kb** [tensorflow/tensorflow#32891]
This error is obtained while importing tensorflow in a program.

- OS Platform and Distribution : Linux raspberry 4.9.0-11-686 #1 SMP Debian 4.9.189-3+deb9u1 (2019-09-20) i686 GNU/Linux
- TensorFlow installed from (source or binary): using pip3 python package
- Python version: 3.5.3
- TensorFlow version = 0.11.0

"import tensorflow as tf"
The above command is throwing ImportError as follows:
>>> import tensorflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
  File "/usr/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /usr/local/lib/python3.5/dist-packages/tensorflow/python/_pywrap_tensorflow.so: cannot open shared object file: No such file or directory

**Comment by gadagashwini** [comment]
@Srikanth-Kb, Was the solution provided worked for you.  Thanks!

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
