### ISSUE TITLE
TensorFlow 1.14 self-compiled build installs successfully but fails at runtime with 'ParallelInterleaveDataset' object has no attribute '_flat_structure'

### ISSUE THREAD

**Issue by Atharex** [tensorflow/tensorflow#32947]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux CentOS 7.6
- TensorFlow installed from (source or binary): source
- TensorFlow version: "git clone --branch r1.14 https://github.com/tensorflow/tensorflow.git"
- Python version: "Python 3.6.8"
- Installed using virtualenv? pip? conda?: "bazel built pip package"
- Bazel version (if compiling from source): "https://github.com/bazelbuild/bazel/releases/download/0.24.1/bazel-0.24.1-installer-linux-x86_64.sh"
- GCC/Compiler version (if compiling from source): "gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)"
- CUDA/cuDNN version: CUDA "10.0", cuDNN "7-7.6.4.38-1.cuda10.0"
- GPU model and memory: "Tesla K80, 11441MiB"

**Describe the problem**
The problem occurs after a error-free tensorflow source build. Trying to use this self-built package with the Object Detection API "train.py" legacy script results in the error shown below. The script runs without problems when using the official pip tensorflow-gpu package. 

The error:
```
Use `tf.data.Dataset.interleave(map_func, cycle_length, block_length, num_parallel_calls=tf.data.experimental.AUTOTUNE)` instead. If sloppy execution is desired, use `tf.data.Options.experimental_determinstic`.
Traceback (most recent call last):
  File "/tensorflow/train.py", line 184, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/tensorflow/train.py", line 180, in main
    graph_hook_fn=graph_rewriter_fn)
  File "/tensorflow/models/research/object_detection/legacy/trainer.py", line 280, in train
    train_config.prefetch_queue_capacity, data_augmentation_options)
  File "/tensorflow/models/research/object_detection/legacy/trainer.py", line 59, in create_input_queue
    tensor_dict = create_tensor_dict_fn()
  File "/tensorflow/train.py", line 121, in get_next
    dataset_builder.build(config)).get_next()
  File "/tensorflow/models/research/object_detection/builders/dataset_builder.py", line 141, in build
    config.input_path[:], input_reader_config)
  File "/tensorflow/models/research/object_detection/builders/dataset_builder.py", line 86, in read_dataset
    sloppy=config.shuffle))
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1853, in apply
    return DatasetV1Adapter(super(DatasetV1, self).apply(transformation_func))
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1290, in apply
    dataset = transformation_func(self)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/data/experimental/ops/interleave_ops.py", line 94, in _apply_fn
    buffer_output_elements, prefetch_input_elements)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/data/ops/readers.py", line 253, in __init__
    **self._flat_structure)
AttributeError: 'ParallelInterleaveDataset' object has no attribute '_flat_structure'
```

Importing this self built package works without any apparent problems:
```
[root@b39e843663d1 tensorflow]# python3
Python 3.6.8 (default, Aug  7 2019, 17:28:10)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
2019-10-01 09:25:39.270112: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.0
>>> 
```

**Provide the exact sequence of commands / steps that you executed before running into the problem**
I've created a docker container to build the package with the following settings:

```
...
ENV PYTHON_BIN_PATH="/usr/bin/python3"
ENV PYTHON_LIB_PATH="/usr/local/lib64/python3.6/site-packages"
ENV TF_ENABLE_XLA="Y"
ENV TF_NEED_OPENCL_SYCL="N"
ENV TF_NEED_ROCM="N"
ENV TF_NEED_CUDA="Y"
ENV TF_NEED_TENSORRT="Y"
ENV TF_CUDA_VERSION="10"
ENV TF_CUDNN_VERSION="7"
ENV TF_NCCL_VERSION="2.4.8"
ENV TF_TENSORRT_VERSION="5"
ENV TF_CUDA_PATHS="/lib64,/usr/lib64,/usr/include,/usr/local/cuda-10.0"
ENV TF_CUDA_COMPUTE_CAPABILITIES="7.5,3.7"
ENV TF_CUDA_CLANG="N"
ENV GCC_HOST_COMPILER_PATH="/usr/bin/gcc"
ENV TF_NEED_MPI="N"
ENV CC_OPT_FLAGS="-mavx -mavx2 -mfma -mfpmath=both -msse4.2 -march=native"
ENV TF_SET_ANDROID_WORKSPACE="N"

RUN bash configure

RUN bazel build --config=opt --config=mkl --config=numa --config=noignite --config=nokafka //tensorflow/tools/pip_package:build_pip_package
RUN ./bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg
RUN pip3 install /tmp/tensorflow_pkg/tensorflow-*.whl
...
```

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

```
[root@b39e843663d1 tensorflow]# python3 /tensorflow/train.py --logtostderr --train_dir=/training_dataset/ --pipeline_config_path=/training_dataset/model.config
2019-10-01 09:23:10.704622: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.0
WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

WARNING:tensorflow:From /tensorflow/models/research/slim/nets/inception_resnet_v2.py:373: The name tf.GraphKeys is deprecated. Please use tf.compat.v1.GraphKeys instead.

WARNING:tensorflow:From /tensorflow/models/research/slim/nets/mobilenet/mobilenet.py:397: The name tf.nn.avg_pool is deprecated. Please use tf.nn.avg_pool2d instead.

WARNING:tensorflow:From /tensorflow/train.py:55: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

WARNING:tensorflow:From /tensorflow/train.py:184: The name tf.app.run is deprecated. Please use tf.compat.v1.app.run instead.

WARNING:tensorflow:From /usr/local/lib/python3.6/site-packages/absl/app.py:250: main (from __main__) is deprecated and will be removed in a future version.
Instructions for updating:
Use object_detection/model_main.py.
W1001 09:23:13.366838 140335641364288 deprecation.py:323] From /usr/local/lib/python3.6/site-packages/absl/app.py:250: main (from __main__) is deprecated and will be removed in a future version.
Instructions for updating:
Use object_detection/model_main.py.
WARNING:tensorflow:From /tensorflow/train.py:90: The name tf.gfile.MakeDirs is deprecated. Please use tf.io.gfile.makedirs instead.

W1001 09:23:13.367076 140335641364288 deprecation_wrapper.py:119] From /tensorflow/train.py:90: The name tf.gfile.MakeDirs is deprecated. Please use tf.io.gfile.makedirs instead.

WARNING:tensorflow:From /tensorflow/models/research/object_detection/legacy/trainer.py:266: create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.create_global_step
W1001 09:23:13.375600 140335641364288 deprecation.py:323] From /tensorflow/models/research/object_detection/legacy/trainer.py:266: create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.create_global_step
WARNING:tensorflow:num_readers has been reduced to 1 to match input file shards.
W1001 09:23:13.398977 140335641364288 dataset_builder.py:72] num_readers has been reduced to 1 to match input file shards.
WARNING:tensorflow:From /tensorflow/models/research/object_detection/builders/dataset_builder.py:86: parallel_interleave (from tensorflow.contrib.data.python.ops.interleave_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.experimental.parallel_interleave(...)`.
W1001 09:23:13.406527 140335641364288 deprecation.py:323] From /tensorflow/models/research/object_detection/builders/dataset_builder.py:86: parallel_interleave (from tensorflow.contrib.data.python.ops.interleave_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.experimental.parallel_interleave(...)`.
WARNING:tensorflow:From /usr/local/lib/python3.6/site-packages/tensorflow/contrib/data/python/ops/interleave_ops.py:77: parallel_interleave (from tensorflow.python.data.experimental.ops.interleave_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Dataset.interleave(map_func, cycle_length, block_length, num_parallel_calls=tf.data.experimental.AUTOTUNE)` instead. If sloppy execution is desired, use `tf.data.Options.experimental_determinstic`.
W1001 09:23:13.406693 140335641364288 deprecation.py:323] From /usr/local/lib/python3.6/site-packages/tensorflow/contrib/data/python/ops/interleave_ops.py:77: parallel_interleave (from tensorflow.python.data.experimental.ops.interleave_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Dataset.interleave(map_func, cycle_length, block_length, num_parallel_calls=tf.data.experimental.AUTOTUNE)` instead. If sloppy execution is desired, use `tf.data.Options.experimental_determinstic`.
Traceback (most recent call last):
  File "/tensorflow/train.py", line 184, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/tensorflow/train.py", line 180, in main
    graph_hook_fn=graph_rewriter_fn)
  File "/tensorflow/models/research/object_detection/legacy/trainer.py", line 280, in train
    train_config.prefetch_queue_capacity, data_augmentation_options)
  File "/tensorflow/models/research/object_detection/legacy/trainer.py", line 59, in create_input_queue
    tensor_dict = create_tensor_dict_fn()
  File "/tensorflow/train.py", line 121, in get_next
    dataset_builder.build(config)).get_next()
  File "/tensorflow/models/research/object_detection/builders/dataset_builder.py", line 141, in build
    config.input_path[:], input_reader_config)
  File "/tensorflow/models/research/object_detection/builders/dataset_builder.py", line 86, in read_dataset
    sloppy=config.shuffle))
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1853, in apply
    return DatasetV1Adapter(super(DatasetV1, self).apply(transformation_func))
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1290, in apply
    dataset = transformation_func(self)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/data/experimental/ops/interleave_ops.py", line 94, in _apply_fn
    buffer_output_elements, prefetch_input_elements)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/data/ops/readers.py", line 253, in __init__
    **self._flat_structure)
AttributeError: 'ParallelInterleaveDataset' object has no attribute '_flat_structure'
```

Haven't seen this error anywhere yet with googling, so not sure whether this is a fault of my own build or a bug :/ 

Any help with this will be very appreciated!

**Comment by jvishnuvardhan** [comment]
@Atharex Looks like an issue with building from source. Can you describe the steps you followed in building from source? Also, can you please try `TF1.15.0rc2` and let us know whether the issue persists with latest TF version. thanks!

**Comment by mihaimaruseac** [comment]
I would suggest skipping the `r1.14` branch as it is in a bad state. We tried to make a patch release there but it was too bad so we decided to make a 1.15 release instead.

**Comment by Atharex** [comment]
@mihaimaruseac thanks for the suggestion! I've tried `git clone --branch r1.15 https://github.com/tensorflow/tensorflow.git` and now I get a different error.

```
[root@b7b9b599c04b native]# bazel build --config=mkl --config=numa --config=noignite --config=nokafka //tensorflow/tools/pip_package:build_pip_package
Starting local Bazel server and connecting to it...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=239
INFO: Reading rc options for 'build' from /native/.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone --strategy=Genrule=standalone -c opt --announce_rc --define=grpc_no_ares=true --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include
INFO: Reading rc options for 'build' from /native/.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=/usr/bin/python3 --action_env PYTHON_LIB_PATH=/usr/local/lib64/python3.6/site-packages --python_path=/usr/bin/python3 --config=xla --config=tensorrt --action_env TF_CUDA_VERSION=10 --action_env TF_CUDNN_VERSION=7 --action_env TF_TENSORRT_VERSION=5 --action_env TF_NCCL_VERSION=2.4.8 --action_env TF_CUDA_PATHS=/lib64,/usr/lib64,/usr/include,/usr/local/cuda-10.0 --action_env CUDA_TOOLKIT_PATH=/usr/local/cuda-10.0 --action_env TF_CUDA_COMPUTE_CAPABILITIES=7.5,3.7 --action_env GCC_HOST_COMPILER_PATH=/usr/bin/gcc --config=cuda --action_env TF_CONFIGURE_IOS=0
INFO: Found applicable config definition build:xla in file /native/.tf_configure.bazelrc: --define with_xla_support=true
INFO: Found applicable config definition build:tensorrt in file /native/.bazelrc: --action_env TF_NEED_TENSORRT=1
INFO: Found applicable config definition build:cuda in file /native/.bazelrc: --config=using_cuda --define=using_cuda_nvcc=true
INFO: Found applicable config definition build:using_cuda in file /native/.bazelrc: --define=using_cuda=true --action_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain
INFO: Found applicable config definition build:mkl in file /native/.bazelrc: --define=build_with_mkl=true --define=enable_mkl=true --define=tensorflow_mkldnn_contraction_kernel=0 -c opt
INFO: Found applicable config definition build:numa in file /native/.bazelrc: --define=with_numa_support=true
INFO: Found applicable config definition build:noignite in file /native/.bazelrc: --define=no_ignite_support=true
INFO: Found applicable config definition build:nokafka in file /native/.bazelrc: --define=no_kafka_support=true

ERROR: error loading package '': Encountered error while reading extension file 'repositories/repositories.bzl': no such package '@io_bazel_rules_docker//repositories': Traceback (most recent call last):
        File "/root/.cache/bazel/_bazel_root/ce6b201fa2cce1ac8c0a389f89f76729/external/bazel_tools/tools/build_defs/repo/git.bzl", line 164
                _clone_or_update(ctx)
        File "/root/.cache/bazel/_bazel_root/ce6b201fa2cce1ac8c0a389f89f76729/external/bazel_tools/tools/build_defs/repo/git.bzl", line 74, in _clone_or_update
                fail(("error cloning %s:\n%s" % (ctx....)))
error cloning io_bazel_rules_docker:
+ cd /root/.cache/bazel/_bazel_root/ce6b201fa2cce1ac8c0a389f89f76729/external
+ rm -rf /root/.cache/bazel/_bazel_root/ce6b201fa2cce1ac8c0a389f89f76729/external/io_bazel_rules_docker /root/.cache/bazel/_bazel_root/ce6b201fa2cce1ac8c0a389f89f76729/external/io_bazel_rules_docker
+ git clone https://github.com/bazelbuild/rules_docker.git /root/.cache/bazel/_bazel_root/ce6b201fa2cce1ac8c0a389f89f76729/external/io_bazel_rules_docker
+ git -C /root/.cache/bazel/_bazel_root/ce6b201fa2cce1ac8c0a389f89f76729/external/io_bazel_rules_docker reset --hard 251f6a68b439744094faff800cd029798edf9faa
Unknown option: -C
usage: git [--version] [--help] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
+ git -C /root/.cache/bazel/_bazel_root/ce6b201fa2cce1ac8c0a389f89f76729/external/io_bazel_rules_docker fetch origin 251f6a68b439744094faff800cd029798edf9faa:251f6a68b439744094faff800cd029798edf9faa
Unknown option: -C
usage: git [--version] [--help] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
+ git -C /root/.cache/bazel/_bazel_root/ce6b201fa2cce1ac8c0a389f89f76729/external/io_bazel_rules_docker fetch origin 251f6a68b439744094faff800cd029798edf9faa:251f6a68b439744094faff800cd029798edf9faa
Unknown option: -C
usage: git [--version] [--help] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
ERROR: error loading package '': Encountered error while reading extension file 'repositories/repositories.bzl': no such package '@io_bazel_rules_docker//repositories': Traceback (most recent call last):
        File "/root/.cache/bazel/_bazel_root/ce6b201fa2cce1ac8c0a389f89f76729/external/bazel_tools/tools/build_defs/repo/git.bzl", line 164
                _clone_or_update(ctx)
        File "/root/.cache/bazel/_bazel_root/ce6b201fa2cce1ac8c0a389f89f76729/external/bazel_tools/tools/build_defs/repo/git.bzl", line 74, in _clone_or_update
                fail(("error cloning %s:\n%s" % (ctx....)))
error cloning io_bazel_rules_docker:
+ cd /root/.cache/bazel/_bazel_root/ce6b201fa2cce1ac8c0a389f89f76729/external
+ rm -rf /root/.cache/bazel/_bazel_root/ce6b201fa2cce1ac8c0a389f89f76729/external/io_bazel_rules_docker /root/.cache/bazel/_bazel_root/ce6b201fa2cce1ac8c0a389f89f76729/external/io_bazel_rules_docker
+ git clone https://github.com/bazelbuild/rules_docker.git /root/.cache/bazel/_bazel_root/ce6b201fa2cce1ac8c0a389f89f76729/external/io_bazel_rules_docker
+ git -C /root/.cache/bazel/_bazel_root/ce6b201fa2cce1ac8c0a389f89f76729/external/io_bazel_rules_docker reset --hard 251f6a68b439744094faff800cd029798edf9faa
Unknown option: -C
usage: git [--version] [--help] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
+ git -C /root/.cache/bazel/_bazel_root/ce6b201fa2cce1ac8c0a389f89f76729/external/io_bazel_rules_docker fetch origin 251f6a68b439744094faff800cd029798edf9faa:251f6a68b439744094faff800cd029798edf9faa
Unknown option: -C
usage: git [--version] [--help] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
+ git -C /root/.cache/bazel/_bazel_root/ce6b201fa2cce1ac8c0a389f89f76729/external/io_bazel_rules_docker fetch origin 251f6a68b439744094faff800cd029798edf9faa:251f6a68b439744094faff800cd029798edf9faa
Unknown option: -C
usage: git [--version] [--help] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
INFO: Elapsed time: 8.351s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

```

**Comment by Atharex** [comment]
@jvishnuvardhan here is a "high-level" docker file I'm using for the build. Some steps that involve private storage have been removed, but the main gist of the build steps is still there. 
[Dockerfile.txt](https://github.com/tensorflow/tensorflow/files/3689760/Dockerfile.txt)

**Comment by mihaimaruseac** [comment]
Please update git version, `-C` has been supported [since at least 2.2.0](https://git-scm.com/docs/git/2.2.0)

**Comment by Atharex** [comment]
Nice catch! Probably other default centos repo packages are also too old.
I'll do the updates and let you know afterwards if the problems are gone.

**Comment by Atharex** [comment]
Update: Newer versions of git (2.16.5) & gcc (6.5.0) solved the build problems.
Now I get an installable 1.15.0-rc3 pip package.

The package itself loads tensorflow normally and even correctly starts the Object Detection API scripts, however they die soon after startup (below an example of after 70 steps of training)

Does this look like a build problem or something connected to the release candidate of TF 1.15?
```
INFO:tensorflow:Running local_init_op.
I1005 16:35:40.917297 140617642202944 session_manager.py:500] Running local_init_op.
INFO:tensorflow:Done running local_init_op.
I1005 16:35:41.896291 140617642202944 session_manager.py:502] Done running local_init_op.
INFO:tensorflow:Starting Session.
I1005 16:35:52.812674 140617642202944 learning.py:754] Starting Session.
INFO:tensorflow:Saving checkpoint to path /training_dataset/model.ckpt
I1005 16:35:53.223033 140611315296000 supervisor.py:1117] Saving checkpoint to path /training_dataset/model.ckpt
INFO:tensorflow:Starting Queues.
...
I1005 16:37:26.352100 140617642202944 learning.py:507] global step 69: loss = 6.4212 (0.210 sec/step)
INFO:tensorflow:global step 70: loss = 5.3100 (0.210 sec/step)
I1005 16:37:26.564062 140617642202944 learning.py:507] global step 70: loss = 5.3100 (0.210 sec/step)
2019-10-05 16:37:28.040392: E tensorflow/stream_executor/cuda/cuda_event.cc:29] Error polling for event status: failed to query event: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2019-10-05 16:37:28.040429: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at non_max_suppression_op.cu.cc:649 : Internal: Cuda call failed with an illegal memory access was encountered
2019-10-05 16:37:28.040494: F tensorflow/core/common_runtime/gpu/gpu_event_mgr.cc:273] Unexpected Event status: 1
Fatal Python error: Aborted

Thread 0x00007fe25f006700 (most recent call first):
  File "/usr/lib64/python3.6/threading.py", line 295 in wait
  File "/usr/lib64/python3.6/threading.py", line 551 in wait
  File "/usr/local/lib64/python3.6/site-packages/tensorflow_core/python/training/coordinator.py", line 311 in wait_for_stop
  File "/usr/local/lib64/python3.6/site-packages/tensorflow_core/python/training/queue_runner_impl.py", line 293 in _close_on_stop
  File "/usr/lib64/python3.6/threading.py", line 864 in run
  File "/usr/lib64/python3.6/threading.py", line 916 in _bootstrap_inner
  File "/usr/lib64/python3.6/threading.py", line 884 in _bootstrap

Thread 0x00007fe290ff8700 (most recent call first):
  File "/usr/local/lib64/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1443 in _call_tf_sessionrun
  File "/usr/local/lib64/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1287 in _single_operation_run
  File "/usr/local/lib64/python3.6/site-packages/tensorflow_core/python/training/queue_runner_impl.py", line 257 in _run
  File "/usr/lib64/python3.6/threading.py", line 864 in run
  File "/usr/lib64/python3.6/threading.py", line 916 in _bootstrap_inner
  File "/usr/lib64/python3.6/threading.py", line 884 in _bootstrap

Thread 0x00007fe2917f9700 (most recent call first):
  File "/usr/lib64/python3.6/threading.py", line 295 in wait
  File "/usr/lib64/python3.6/threading.py", line 551 in wait
  File "/usr/local/lib64/python3.6/site-packages/tensorflow_core/python/training/coordinator.py", line 311 in wait_for_stop
  File "/usr/local/lib64/python3.6/site-packages/tensorflow_core/python/training/queue_runner_impl.py", line 293 in _close_on_stop
  File "/usr/lib64/python3.6/threading.py", line 864 in run
  File "/usr/lib64/python3.6/threading.py", line 916 in _bootstrap_inner
  File "/usr/lib64/python3.6/threading.py", line 884 in _bootstrap

Thread 0x00007fe291ffa700 (most recent call first):
  File "/usr/local/lib64/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1443 in _call_tf_sessionrun
  File "/usr/local/lib64/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1287 in _single_operation_run
  File "/usr/local/lib64/python3.6/site-packages/tensorflow_core/python/training/queue_runner_impl.py", line 257 in _run
  File "/usr/lib64/python3.6/threading.py", line 864 in run
  File "/usr/lib64/python3.6/threading.py", line 916 in _bootstrap_inner
  File "/usr/lib64/python3.6/threading.py", line 884 in _bootstrap

Thread 0x00007fe2927fb700 (most recent call first):
  File "/usr/local/lib64/python3.6/site-2019-10-05 16:37:28.042576: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at non_max_suppression_op.cu.cc:649 : Internal: Cuda call failed with an illegal memory access was encountered
packages/tensorflow_core/py2019-10-05 16:37:28.042619: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at non_max_suppression_op.cu.cc:649 : Internal: Cuda call failed with an illegal memory access was encountered
thon/client/session2019-10-05 16:37:28.042643: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at non_max_suppression_op.cu.cc:649 : Internal: Cuda call failed with an illegal memory access was encountered
.py", line 1443 in _call_tf_ses2019-10-05 16:37:28.042664: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at non_max_suppression_op.cu.cc:649 : Internal: Cuda call failed with an illegal memory access was encountered
sionrun
  File "/usr/local/lib64/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1287 in _single_operation_run
2019-10-05 16:37:28.042785: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at non_max_suppression_op.cu.cc:649 : Internal: Cuda call failed with an illegal memory access was encountered
  File "/usr/local/lib64/python3.6/site-packages/tensorflow_core/python/training/queue_runner_impl.py", line 257 in _run
  File "/usr/lib64/python3.6/threading.py", line 864 in run
  File "/usr/lib64/python3.6/threading.py", line 916 in _bootstrap_inner
  File "/usr/lib64/python3.6/threading.py", line 884 in _bootstrap

```

**Comment by mihaimaruseac** [comment]
That looks like a runtime error. Can you please open a new issue for that? And close this one as it seems solved?

**Comment by Atharex** [comment]
Sure! I'll create the new issue.

Thanks for the help!
