### ISSUE TITLE
doesn't support control flow ops

### ISSUE THREAD

**Issue by DSOCT18** [tensorflow/tensorflow#32941]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 18.04): Linux Ubuntu 18.04
- TensorFlow installed from (source or binary): source
- TensorFlow version (or github SHA if from source): '1.15.0-dev20190821'

**Provide the text output from tflite_convert**
2019-10-01 11:52:29.446292: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2019-10-01 11:52:29.446369: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2019-10-01 11:52:29.446391: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2019-10-01 11:52:29.446410: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2019-10-01 11:52:29.446431: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayV3
2019-10-01 11:52:29.446452: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2019-10-01 11:52:29.446470: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayV3
2019-10-01 11:52:29.446486: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2019-10-01 11:52:29.446503: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayV3
2019-10-01 11:52:29.446519: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2019-10-01 11:52:29.446538: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2019-10-01 11:52:29.446556: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2019-10-01 11:52:29.446575: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2019-10-01 11:52:29.446593: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2019-10-01 11:52:29.446611: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2019-10-01 11:52:29.446630: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2019-10-01 11:52:29.446649: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2019-10-01 11:52:29.446668: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2019-10-01 11:52:29.446686: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2019-10-01 11:52:29.446705: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2019-10-01 11:52:29.446723: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2019-10-01 11:52:29.446742: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2019-10-01 11:52:29.446760: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2019-10-01 11:52:29.446778: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2019-10-01 11:52:29.446799: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2019-10-01 11:52:29.446830: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2019-10-01 11:52:29.446850: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2019-10-01 11:52:29.446865: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2019-10-01 11:52:29.446879: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2019-10-01 11:52:29.446897: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2019-10-01 11:52:29.446912: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2019-10-01 11:52:29.446926: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2019-10-01 11:52:29.446944: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2019-10-01 11:52:29.446958: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2019-10-01 11:52:29.446973: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2019-10-01 11:52:29.447055: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2019-10-01 11:52:29.447091: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: LoopCond
2019-10-01 11:52:29.447124: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Exit
2019-10-01 11:52:29.447144: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Exit
2019-10-01 11:52:29.447162: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Exit
2019-10-01 11:52:29.447348: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayConcatV3
2019-10-01 11:52:29.447371: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayConcatV3
2019-10-01 11:52:29.447391: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayConcatV3
2019-10-01 11:52:29.447420: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: NonMaxSuppressionV3
2019-10-01 11:52:29.447953: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: CropAndResize
2019-10-01 11:52:29.448061: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: NonMaxSuppressionV3
2019-10-01 11:52:29.448096: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayWriteV3
2019-10-01 11:52:29.448115: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayWriteV3
2019-10-01 11:52:29.448133: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayWriteV3
2019-10-01 11:52:29.448321: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: NonMaxSuppressionV3
2019-10-01 11:52:29.448763: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: CropAndResize
2019-10-01 11:52:29.449086: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: NonMaxSuppressionV3
2019-10-01 11:52:29.456571: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 483 operators, 916 arrays (0 quantized)
2019-10-01 11:52:29.464789: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After Removing unused ops pass 1: 461 operators, 876 arrays (0 quantized)
2019-10-01 11:52:29.474610: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 461 operators, 876 arrays (0 quantized)
2019-10-01 11:52:29.484660: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 1: 435 operators, 814 arrays (0 quantized)
2019-10-01 11:52:29.495248: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Group bidirectional sequence lstm/rnn: 435 operators, 814 arrays (0 quantized)
2019-10-01 11:52:29.503154: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before dequantization graph transformations: 435 operators, 814 arrays (0 quantized)
2019-10-01 11:52:29.511581: I tensorflow/lite/toco/allocate_transient_arrays.cc:345] Total transient array allocated size: 2160448 bytes, theoretical optimal value: 2160320 bytes.
2019-10-01 11:52:29.513604: I tensorflow/lite/toco/toco_tooling.cc:454] Number of parameters: 496191
2019-10-01 11:52:29.664171: E tensorflow/lite/toco/toco_tooling.cc:481] We are continually in the process of adding support to TensorFlow Lite for more ops. It would be helpful if you could inform us of how this conversion went by opening a github issue at https://github.com/tensorflow/tensorflow/issues/new?template=40-tflite-op-request.md
 and pasting the following:

```
# Copy and paste here
```TensorFlow Lite currently doesn't support control flow ops: Enter, Exit, Merge, Switch. We are working on supporting control flow ops, please see github issue at https://github.com/tensorflow/tensorflow/issues/28485. Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, CAST, CONCATENATION, CONV_2D, DIV, EXPAND_DIMS, GATHER, GREATER, MAX_POOL_2D, MUL, PACK, REDUCE_MAX, REDUCE_PROD, RESHAPE, RESIZE_BILINEAR, SELECT, SHAPE, SOFTMAX, SQUEEZE, STRIDED_SLICE, SUB, TILE, WHERE. Here is a list of operators for which you will need custom implementations: CropAndResize, LoopCond, NonMaxSuppressionV3, TensorArrayConcatV3, TensorArrayV3, TensorArrayWriteV3.
Traceback (most recent call last):
  File "/home/konsultera/.local/bin/toco_from_protos", line 10, in <module>
    sys.exit(main())
  File "/home/konsultera/.local/lib/python3.6/site-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 89, in main
    app.run(main=execute, argv=[sys.argv[0]] + unparsed)
  File "/home/konsultera/.local/lib/python3.6/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/home/konsultera/.local/lib/python3.6/site-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 52, in execute
    enable_mlir_converter)
Exception: We are continually in the process of adding support to TensorFlow Lite for more ops. It would be helpful if you could inform us of how this conversion went by opening a github issue at https://github.com/tensorflow/tensorflow/issues/new?template=40-tflite-op-request.md
 and pasting the following:

TensorFlow Lite currently doesn't support control flow ops: Enter, Exit, Merge, Switch. We are working on supporting control flow ops, please see github issue at https://github.com/tensorflow/tensorflow/issues/28485. Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, CAST, CONCATENATION, CONV_2D, DIV, EXPAND_DIMS, GATHER, GREATER, MAX_POOL_2D, MUL, PACK, REDUCE_MAX, REDUCE_PROD, RESHAPE, RESIZE_BILINEAR, SELECT, SHAPE, SOFTMAX, SQUEEZE, STRIDED_SLICE, SUB, TILE, WHERE. Here is a list of operators for which you will need custom implementations: CropAndResize, LoopCond, NonMaxSuppressionV3, TensorArrayConcatV3, TensorArrayV3, TensorArrayWriteV3.

Also, please include a link to a GraphDef or the model if possible.

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ymodak** [comment]
Supporting control flow ops is a work in progress.
See https://github.com/tensorflow/tensorflow/issues/28485

**Comment by tensorflowbutler** [comment]
It has been 18 days with no activity and the `awaiting response` label was assigned. Is this still an issue?
