### ISSUE TITLE
tf.keras.layers.StackedRNNCells() doesn't work with tf.contrib.rnn.ConvLSTMCell()

### ISSUE THREAD

**Issue by msinto93** [tensorflow/tensorflow#32951]
Using tf.keras.layers.StackedRNNCells() with the ConvLSTM cell from tf.contrib.rnn.ConvLSTMCell() doesn't work.

```
enc_Conv2D_1 = tf.keras.layers.TimeDistributed(tf.keras.layers.Conv2D(16, 3, 2, 'same', activation=tf.nn.relu, 
                                                                                  kernel_initializer=tf.random_normal_initializer(stddev=math.sqrt(2.0/(kernel_size*kernel_size*16)))))
enc_Conv2D_2 = tf.keras.layers.TimeDistributed(tf.keras.layers.Conv2D(32, 3, 2, 'same', activation=tf.nn.relu, 
                                                                                  kernel_initializer=tf.random_normal_initializer(stddev=math.sqrt(2.0/(kernel_size*kernel_size*32)))))
enc_Conv2D_3 = tf.keras.layers.TimeDistributed(tf.keras.layers.Conv2D(64, 3, 2, 'same', activation=tf.nn.relu, 
                                                                                  kernel_initializer=tf.random_normal_initializer(stddev=math.sqrt(2.0/(kernel_size*kernel_size*64)))))
enc_Conv2D_4 = tf.keras.layers.TimeDistributed(tf.keras.layers.Conv2D(128, 3, 2, 'same', activation=tf.nn.relu, 
                                                                                  kernel_initializer=tf.random_normal_initializer(stddev=math.sqrt(2.0/(kernel_size*kernel_size*128)))))
   
enc_ConvLSTMCell = tf.contrib.rnn.ConvLSTMCell(2, [grid_size//16, grid_size//16, 128], 128, [5, 5])
enc_Stacked_ConvLSTMCells = tf.keras.layers.StackedRNNCells([enc_ConvLSTMCell]*2)
enc_ConvLSTMLayer = tf.keras.layers.RNN(enc_Stacked_ConvLSTMCells, return_state=True)

enc_conv1 = enc_Conv2D_1(enc_input_grids)
enc_conv2 = enc_Conv2D_2(enc_conv1)
enc_conv3 = enc_Conv2D_3(enc_conv2)
enc_conv4 = enc_Conv2D_4(enc_conv3)
                               
enc_output_and_state = enc_ConvLSTMLayer(enc_conv4)
```

When I run this code I get the following error:

```
Traceback (most recent call last):
  File "E:\Code\LSTM_Prediction\Conv_LSTM_Encoder_Decoder\network.py", line 349, in <module>
    net.build_network(map_grids, agent_enc_grids, other_vehs_grids, agent_dec_grids, grid_size, downsampling)   
  File "E:\Code\LSTM_Prediction\Conv_LSTM_Encoder_Decoder\network.py", line 217, in build_network
    enc_output_and_state = enc_ConvLSTMLayer(enc_conv4)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\keras\layers\recurrent.py", line 701, in __call__
    return super(RNN, self).__call__(inputs, **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 538, in __call__
    self._maybe_build(inputs)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 1603, in _maybe_build
    self.build(input_shapes)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\keras\layers\recurrent.py", line 633, in build
    for dim in state_size
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\keras\layers\recurrent.py", line 633, in <listcomp>
    for dim in state_size
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\framework\tensor_shape.py", line 1125, in as_shape
    return TensorShape(shape)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\framework\tensor_shape.py", line 690, in __init__
    self._dims = [as_dimension(d) for d in dims_iter]
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\framework\tensor_shape.py", line 690, in <listcomp>
    self._dims = [as_dimension(d) for d in dims_iter]
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\framework\tensor_shape.py", line 632, in as_dimension
    return Dimension(value)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\framework\tensor_shape.py", line 185, in __init__
    self._value = int(value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'TensorShapeV1'
```

This is clearly an issue with running StackedRNNCells() with the tf.contrib.rnn.ConvLSTMCell(), as if I modify the code to flatten the conv output and run with a standard LSTM cell, e.g. `tf.nn.rnn_cell.LSTMCell(state_size)`, it runs fine.

**Comment by bionicles** [comment]
Contrib is deprecated, have you tried upgrading to tf 2.0 and using tf.keras.layers.ConvLSTM2D ? https://www.tensorflow.org/api_docs/python/tf/keras/layers/ConvLSTM2D

**Comment by msinto93** [comment]
> Contrib is deprecated, have you tried upgrading to tf 2.0 and using tf.keras.layers.ConvLSTM2D ? https://www.tensorflow.org/api_docs/python/tf/keras/layers/ConvLSTM2D

If I understand correctly tf.keras.layers.ConvLSTM2D() is a **layer**, while StackedRNNCells() takes **cells** as input. Can you clarify this? Or give an example of usage of a stacked ConvLTSM layer?

**Comment by gowthamkpr** [comment]
To understand about ConVLSTM2D[1] and StackedRNNCells()[2] you can follow these tutorials.
[1] - https://machinelearningmastery.com/stacked-long-short-term-memory-networks/
[2] - https://srirangatarun.wordpress.com/2018/07/09/video-frame-prediction-with-keras/

For more clarification please post it in Stackoverflow. Thanks!
