### ISSUE TITLE
Report You must feed a value for placeholder when I do feed the value.

### ISSUE THREAD

**Issue by niumeng07** [tensorflow/tensorflow#32986]
Tensorflow works in parameter-server mode.
worker1 starts training success, but worker 0 reports an error.

OS: macOS
Python: 3.7.4
Tensorflow: 1.14.0

```
I1002 19:19:12.119244 123145589936128 coordinator.py:219] Error reported to Coordinator: From /job:worker/replica:0/task:0:
You must feed a value for placeholder tensor 'attention/onehot_c1' with dtype int64 and shape [?,?,?]
	 [[node attention/onehot_c1 (defined at /Users/liuda/Tencent/code/nlp/attention/transformer/model.py:38) ]]

Original stack trace for 'attention/onehot_c1':
  File "./train.py", line 224, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.7/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "./train.py", line 77, in main
    train(FLAGS)
  File "./train.py", line 135, in train
    model = Model(hidden_units, FLAGS, "train")
  File "/Users/liuda/Tencent/code/nlp/attention/transformer/model.py", line 38, in __init__
    input_placeholder = tf.placeholder(tf.int64, [None, None, None], name="onehot_" + fn)  # batchsize, seqsize, mfea
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py", line 2143, in placeholder
    return gen_array_ops.placeholder(dtype=dtype, shape=shape, name=name)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 6262, in placeholder
    "Placeholder", dtype=dtype, shape=shape, name=name)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3616, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: From /job:worker/replica:0/task:0:
You must feed a value for placeholder tensor 'attention/onehot_c1' with dtype int64 and shape [?,?,?]
	 [[{{node attention/onehot_c1}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/training/coordinator.py", line 297, in stop_on_exception
    yield
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/training/coordinator.py", line 495, in run
    self.run_loop()
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/training/supervisor.py", line 1045, in run_loop
    [self._sv.summary_op, self._sv.global_step])
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: From /job:worker/replica:0/task:0:
You must feed a value for placeholder tensor 'attention/onehot_c1' with dtype int64 and shape [?,?,?]
	 [[node attention/onehot_c1 (defined at /Users/liuda/Tencent/code/nlp/attention/transformer/model.py:38) ]]

Original stack trace for 'attention/onehot_c1':
  File "./train.py", line 224, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.7/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "./train.py", line 77, in main
    train(FLAGS)
  File "./train.py", line 135, in train
    model = Model(hidden_units, FLAGS, "train")
  File "/Users/liuda/Tencent/code/nlp/attention/transformer/model.py", line 38, in __init__
    input_placeholder = tf.placeholder(tf.int64, [None, None, None], name="onehot_" + fn)  # batchsize, seqsize, mfea
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py", line 2143, in placeholder
    return gen_array_ops.placeholder(dtype=dtype, shape=shape, name=name)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 6262, in placeholder
    "Placeholder", dtype=dtype, shape=shape, name=name)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3616, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()
```
I print the feed_dict, onehot_c1 was generated success as follows

```
attention/onehot_c1:0 <class 'numpy.ndarray'> (10, 15, 5) int64
```

Worker 1 trains normally and gives training info
```
train info 2019-10-02 19:20:16 epo 0 step 931 local_step 931 auc 0.6139 loss 0.0840
```

**Comment by sunanlin13174** [comment]
same issue,do you have slove it?

**Comment by deathrc** [comment]
same issue, can't trace where I haven't fed the placeholder(I'm convinced I fed them all)

**Comment by np-n** [comment]
Stuck on the same issue. How you have fixed it?
