### ISSUE TITLE
Error trying to predict using skflow example dnn_autoencoder_iris

### ISSUE THREAD

**Issue by NikunjBajaj-Reflektion** [tensorflow/tensorflow#3300]
I am trying to generate new data using trained construction layer using dnn autoencoder on iris data. I run into a couple issues detailed after the system and installation information. 

### Environment info
Operating System:

Mac OSx 10.11.5

I installed from the source code and the commit hash is- 
bef942ca38d03bda48e3f39d3473973f0219933a

**Error 1:** 
### Steps to reproduce
* Add the following line to the file `tensorflow/tensorflow/examples/skflow/dnn_autoencoder_iris.py`

```
new_data = autoencoder.generate()
print new_data
```
* Run the above file.
Error: `get_tensor_value()` is not a class method. 

I tried changing  the function name to `get_tensor()` which actually exists in the parent class. 

I get the following error trace 

```
WARNING:tensorflow:learn.ops.dnn is deprecated,     please use contrib.layers.dnn.
Traceback (most recent call last):
  File "/Users/nbajaj/tensorflow_git/tensorflow/tensorflow/examples/skflow/dnn_autoencoder_rfk.py", line 56, in <module>
    new_data = autoencoder.generate()
  File "/Users/nbajaj/tensorflow_git/tvenv/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/autoencoder.py", line 97, in generate
    "encoder/dnn/layer%d/Linear/Bias:0" % last_layer)
  File "/Users/nbajaj/tensorflow_git/tvenv/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/base.py", line 270, in get_tensor
    return self._graph.get_tensor_by_name(name)
  File "/Users/nbajaj/tensorflow_git/tvenv/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2519, in get_tensor_by_name
    return self.as_graph_element(name, allow_tensor=True, allow_operation=False)
  File "/Users/nbajaj/tensorflow_git/tvenv/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2373, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/Users/nbajaj/tensorflow_git/tvenv/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2415, in _as_graph_element_locked
    "graph." % (repr(name), repr(op_name)))
KeyError: "The name 'encoder/dnn/layer1/Linear/Bias:0' refers to a Tensor which does not exist. The operation, 'encoder/dnn/layer1/Linear/Bias', does not exist in the graph."
```

Then I changed the line 
`new_data = autoencoder.generate()` -> `new_data = autoencoder.generate(hideen=transformed)` so that the above code path doesn't get executed in the first place. 

Then I get the following error trace- 

```
Traceback (most recent call last):
  File "dnn_autoencoder_rfk.py", line 56, in <module>
    new_data = autoencoder.generate(hidden=[10, 20])
  File "/Users/nbajaj/tensorflow_git/tvenv/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/autoencoder.py", line 101, in generate
    return self._session.run(self.decoder, feed_dict={self.encoder: hidden})
AttributeError: 'TensorFlowDNNAutoencoder' object has no attribute '_session'
```

Please let me know if I could try something else or there is anyway I can help to fix this.

**Comment by jmchen-g** [comment]
@ilblackdragon Could you take a look at this please?

**Comment by NikunjBajaj-Reflektion** [comment]
Hi @ilblackdragon. Did you get a chance to look into this? I would be happy to help if I could.

**Comment by ilblackdragon** [comment]
Sorry I'm on vacation until next week. @wicke can you ask somebody to look
at this and related issues? Thanks

**Comment by NikunjBajaj-Reflektion** [comment]
Apologies for bothering again. Just checking in if someone got a chance.

**Comment by michaelisard** [comment]
@ilblackdragon could you take a look now? Thanks.

**Comment by ilblackdragon** [comment]
This example was removed as it is outdated. Closing this issue.
