### ISSUE TITLE
TF2.0.0: tensorflow.python.framework.errors_impl.UnknownError: CUDNN_STATUS_BAD_PARAM

### ISSUE THREAD

**Issue by HsinJhao** [tensorflow/tensorflow#33069]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):  **yes**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Windows Server 2019**
- TensorFlow installed from (source or binary): **pip install tensorflow-gpu**
- TensorFlow version (use command below): **2.0.0**
- Python version:**3.6.9**
- CUDA/cuDNN version:**10.1/7.6.4**
- GPU model and memory: **GTX1080Ti  x4**

**Describe the current behavior**

When I succeeded in debugging on my own host, I occured an error on windows server 2019 for debugging.The error message is below:

```cmd
2019-10-05 21:54:41.858023: W tensorflow/core/framework/op_kernel.cc:1622] OP_REQUIRES failed at cudnn_rnn_ops.cc:1498 : Unknown: CUDNN_STATUS_BAD_PARAM
in tensorflow/stream_executor/cuda/cuda_dnn.cc(1424): 'cudnnSetRNNDataDescriptor( data_desc.get(), data_type, layout, max_seq_length, batch_size, data_size, seq_lengths_array, (void*)&padding_fill)'
Traceback (most recent call last):
  File "E:/PythonProjects/Sequence-Labeling/bi-lstm_tf2.py", line 139, in <module>
    loss_value, grads = gradient_descent(model, train_x, train_y)
  File "E:/PythonProjects/Sequence-Labeling/bi-lstm_tf2.py", line 50, in gradient_descent
    y_predict = model(inputs)
  File "D:\ProgramData\Anaconda3\envs\py36-tf2\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py", line 891, in __call__
    outputs = self.call(cast_inputs, *args, **kwargs)
  File "D:\ProgramData\Anaconda3\envs\py36-tf2\lib\site-packages\tensorflow_core\python\keras\engine\sequential.py", line 256, in call
    return super(Sequential, self).call(inputs, training=training, mask=mask)
  File "D:\ProgramData\Anaconda3\envs\py36-tf2\lib\site-packages\tensorflow_core\python\keras\engine\network.py", line 708, in call
    convert_kwargs_to_constants=base_layer_utils.call_context().saving)
  File "D:\ProgramData\Anaconda3\envs\py36-tf2\lib\site-packages\tensorflow_core\python\keras\engine\network.py", line 860, in _run_internal_graph
    output_tensors = layer(computed_tensors, **kwargs)
  File "D:\ProgramData\Anaconda3\envs\py36-tf2\lib\site-packages\tensorflow_core\python\keras\layers\wrappers.py", line 528, in __call__
    return super(Bidirectional, self).__call__(inputs, **kwargs)
  File "D:\ProgramData\Anaconda3\envs\py36-tf2\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py", line 891, in __call__
    outputs = self.call(cast_inputs, *args, **kwargs)
  File "D:\ProgramData\Anaconda3\envs\py36-tf2\lib\site-packages\tensorflow_core\python\keras\layers\wrappers.py", line 642, in call
    initial_state=forward_state, **kwargs)
  File "D:\ProgramData\Anaconda3\envs\py36-tf2\lib\site-packages\tensorflow_core\python\keras\layers\recurrent.py", line 623, in __call__
    return super(RNN, self).__call__(inputs, **kwargs)
  File "D:\ProgramData\Anaconda3\envs\py36-tf2\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py", line 891, in __call__
    outputs = self.call(cast_inputs, *args, **kwargs)
  File "D:\ProgramData\Anaconda3\envs\py36-tf2\lib\site-packages\tensorflow_core\python\keras\layers\recurrent_v2.py", line 961, in call
    **cudnn_lstm_kwargs)
  File "D:\ProgramData\Anaconda3\envs\py36-tf2\lib\site-packages\tensorflow_core\python\keras\layers\recurrent_v2.py", line 1160, in cudnn_lstm
    rnn_mode='lstm', sequence_lengths=sequence_length)
  File "D:\ProgramData\Anaconda3\envs\py36-tf2\lib\site-packages\tensorflow_core\python\ops\gen_cudnn_rnn_ops.py", line 2008, in cudnn_rnnv3
    ctx=_ctx)
  File "D:\ProgramData\Anaconda3\envs\py36-tf2\lib\site-packages\tensorflow_core\python\ops\gen_cudnn_rnn_ops.py", line 2114, in cudnn_rnnv3_eager_fallback
    attrs=_attrs, ctx=_ctx, name=name)
  File "D:\ProgramData\Anaconda3\envs\py36-tf2\lib\site-packages\tensorflow_core\python\eager\execute.py", line 67, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
**tensorflow.python.framework.errors_impl.UnknownError: CUDNN_STATUS_BAD_PARAM**
**in tensorflow/stream_executor/cuda/cuda_dnn.cc(1424): 'cudnnSetRNNDataDescriptor( data_desc.get(), data_type, layout, max_seq_length, batch_size, data_size, seq_lengths_array, (void*)&padding_fill)' [Op:CudnnRNNV3]**
```

**Describe the expected behavior**

Code works fine

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```python
gpus = tf.config.experimental.list_physical_devices('GPU')
if gpus:
	# Currently, memory growth needs to be the same across GPUs
	try:
		for gpu in gpus:
			tf.config.experimental.set_memory_growth(gpu, True)
	except RuntimeError as e:
		print(e)

def gradient_descent(model, inputs, targets):
	with tf.GradientTape() as tape:
		# compute loss value
		y_predict = model(inputs)
		loss_value = tf.keras.losses.categorical_crossentropy(y_true = targets,
		                                                      y_pred = y_predict)
	return loss_value, tape.gradient(loss, model.trainable_variables)

with tf.device('/device:gpu:0'):
    model = tf.keras.Sequential([
		    tf.keras.Input(shape = (sequence_len, num_feature),
		                   name = 'InputLayer'),
		    tf.keras.layers.Masking(mask_value = 0.,
		                            input_shape = (sequence_len, num_feature)),
		    tf.keras.layers.Bidirectional(
			    tf.keras.layers.LSTM(units = 50, return_sequences = True),
			    name = 'BiLSTM-1'),
		    tf.keras.layers.Dense(units = 3, activation = 'softmax',
		                          name = 'Softmax')])

    train_x, train_y = train_dataset.next_batch()
    loss_value, grads = gradient_descent(model, train_x, train_y)
    optimizer.apply_gradients(zip(grads, model.trainable_variables))
```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by gadagashwini** [comment]
@HsinJhao, Please downgrade CUDA to 10.0 version and cuDNN version to 7.4 and check. And also provide the complete code to reproduce the issue. Thanks!

**Comment by HsinJhao** [comment]
Thanks your  reply! @gadagashwini 
I am trying to downgrade CUDA to  10.0 version and cuDNN version to 7.4.2.
The code and some data files is provided to you! Hope it can help! 
Thanks again!

[codeAndData.zip](https://github.com/tensorflow/tensorflow/files/3697284/codeAndData.zip)

**Comment by HsinJhao** [comment]
@gadagashwini 
I downgraded CUDA and cuDNN and Checked.
When i downgrade cuDNN to **7.4.2**,it will let me to upgrade cuDNN to 7.6.0 at least. 
After upgraded cuDNN to 7.6.4, the error remains same with the first time as below:
```cmd
tensorflow.python.framework.errors_impl.UnknownError: CUDNN_STATUS_BAD_PARAM
in tensorflow/stream_executor/cuda/cuda_dnn.cc(1424): 'cudnnSetRNNDataDescriptor( data_desc.get(), data_type, layout, max_seq_length, batch_size, data_size, seq_lengths_array, (void*)&padding_fill)' [Op:CudnnRNNV3]
```
:(

**Comment by HsinJhao** [comment]
@gadagashwini
Thanks your response!
I think i find what is wrong when i read this sentence:

> The requirements to use the cuDNN implementation are: 
> 6. Inputs are not masked or strictly right padded.

in [tf2.0api: tf.keras.layers.LSTM](https://www.tensorflow.org/api_docs/python/tf/keras/layers/LSTM)

The problem is that my input data existing all-zeros sequences. It will cause the input data will be all masked by Masking Layer.

Anyway, Thanks a lot! please close this issue right now!

**Comment by mihaimaruseac** [comment]
Closing per user request

**Comment by hankcs** [comment]
> The problem is that my input data existing all-zeros sequences. It will cause the input data will be all masked by Masking Layer.

Thanks a lot.
