### ISSUE TITLE
How to using batch norm with different T in every batch which input is  [B, T, D] shape tensor 

### ISSUE THREAD

**Issue by zh794390558** [tensorflow/tensorflow#33128]
```
Traceback (most recent call last):
  File "/tmp-data/zhanghui/env/py3.6_tf1.14pip/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/tmp-data/zhanghui/env/py3.6_tf1.14pip/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/tmp-data/zhanghui/env/py3.6_tf1.14pip/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: Cannot add tensor to the batch: number of elements does not match. Shapes are: [tensor]: [241,23,1], [batch]: [260,23,1]
         [[{{node MultiDeviceIteratorGetNextFromShard}}]]
         [[RemoteCall]]
         [[IteratorGetNext]]
         [[gradients/speaker_res_net_raw_model_1/model/resnet/resblock-4/bnb_branch2a/FusedBatchNorm_grad/FusedBatchNormGrad/_8463]]
  (1) Invalid argument: Cannot add tensor to the batch: number of elements does not match. Shapes are: [tensor]: [241,23,1], [batch]: [260,23,1]
         [[{{node MultiDeviceIteratorGetNextFromShard}}]]
         [[RemoteCall]]
         [[IteratorGetNext]]
0 successful operations.
3 derived errors ignored.
```

**Comment by gadagashwini** [comment]
@zh794390558, Please provide the standalone code to reproduce the reported issue. Thanks!

**Comment by gadagashwini** [comment]
@zh794390558, Any update on reproducible code.
