### ISSUE TITLE
Cannot find NvInfer.h with TensorRT install

### ISSUE THREAD

**Issue by Julius-ZCJ** [tensorflow/tensorflow#33130]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:1.12.0
- Python version:3.5
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):0.15
- GCC/Compiler version (if compiling from source):GCC
- CUDA/cuDNN version:9.0
- GPU model and memory:7.1.4

**Describe the problem**
  When I try to compile Tensorflow I met this issue. To solve this problem I first try to modify the TensorRT install path in perform ./configure, but I find path is not changed, for example:
           default path:  /usr/lib/x86_64-linux-gnu
           I set path is: /usr/local/TensorRT
 This is useless, I don't know why,
So, I second try to copy NvInfer.h to /usr/lib/x86_64-linux-gnu, but this problem stall exist, and I find NvInfer.h is exist in /usr/lib/x86_64-linux-gnu, why cody can't find this file, I feel confused.
 
**Provide the exact sequence of commands / steps that you executed before running into the problem**
bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

WARNING: The following configs were expanded more than once: [cuda]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
ERROR: Skipping '//tensorflow/tools/pip_package:build_pip_package': error loading package 'tensorflow/tools/pip_package': Encountered error while reading extension file 'build_defs.bzl': no such package '@local_config_tensorrt//': Traceback (most recent call last):
        File "/install_bar/tensorflow-1.12.0/third_party/tensorrt/tensorrt_configure.bzl", line 171
                _trt_lib_version(repository_ctx, trt_install_path)
        File "/install_bar/tensorflow-1.12.0/third_party/tensorrt/tensorrt_configure.bzl", line 81, in _trt_lib_version
                _find_trt_header_dir(repository_ctx, trt_install_path)
        File "/install_bar/tensorflow-1.12.0/third_party/tensorrt/tensorrt_configure.bzl", line 67, in _find_trt_header_dir
                auto_configure_fail(("Cannot find NvInfer.h with Ten...))
        File "/install_bar/tensorflow-1.12.0/third_party/gpus/cuda_configure.bzl", line 317, in auto_configure_fail
                fail(("\n%sCuda Configuration Error:%...)))

Cuda Configuration Error: Cannot find NvInfer.h with TensorRT install path /usr/lib/x86_64-linux-gnu
WARNING: Target pattern parsing failed.
ERROR: error loading package 'tensorflow/tools/pip_package': Encountered error while reading extension file 'build_defs.bzl': no such package '@local_config_tensorrt//': Traceback (most recent call last):
        File "/install_bar/tensorflow-1.12.0/third_party/tensorrt/tensorrt_configure.bzl", line 171
                _trt_lib_version(repository_ctx, trt_install_path)
        File "/install_bar/tensorflow-1.12.0/third_party/tensorrt/tensorrt_configure.bzl", line 81, in _trt_lib_version
                _find_trt_header_dir(repository_ctx, trt_install_path)
        File "/install_bar/tensorflow-1.12.0/third_party/tensorrt/tensorrt_configure.bzl", line 67, in _find_trt_header_dir
                auto_configure_fail(("Cannot find NvInfer.h with Ten...))
        File "/install_bar/tensorflow-1.12.0/third_party/gpus/cuda_configure.bzl", line 317, in auto_configure_fail
                fail(("\n%sCuda Configuration Error:%...)))

Cuda Configuration Error: Cannot find NvInfer.h with TensorRT install path /usr/lib/x86_64-linux-gnu

**Comment by oanush** [comment]
@Julius-ZCJ ,
Can you please provide `./configure `output ?thanks!

**Comment by Julius-ZCJ** [comment]
@oanush  Here is my ./configure set:
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
You have bazel 0.15.0 installed.
Please specify the location of python. [Default is /usr/bin/python]:


Found possible Python library paths:
  /usr/lib/python3/dist-packages
  /usr/local/lib/python3.5/dist-packages
Please input the desired Python library path to use.  Default is [/usr/lib/python3/dist-packages]

Do you wish to build TensorFlow with Apache Ignite support? [Y/n]: n
No Apache Ignite support will be enabled for TensorFlow.

Do you wish to build TensorFlow with XLA JIT support? [Y/n]: n
No XLA JIT support will be enabled for TensorFlow.

Do you wish to build TensorFlow with OpenCL SYCL support? [y/N]: n
No OpenCL SYCL support will be enabled for TensorFlow.

Do you wish to build TensorFlow with ROCm support? [y/N]: n
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: y
CUDA support will be enabled for TensorFlow.

Please specify the CUDA SDK version you want to use. [Leave empty to default to CUDA 9.0]:


Please specify the location where CUDA 9.0 toolkit is installed. Refer to README.md for more details. [Default is /usr/local/cuda]:


Please specify the cuDNN version you want to use. [Leave empty to default to cuDNN 7]:


Please specify the location where cuDNN 7 library is installed. Refer to README.md for more details. [Default is /usr/local/cuda]:


Do you wish to build TensorFlow with TensorRT support? [y/N]: y
TensorRT support will be enabled for TensorFlow.

Please specify the location where TensorRT is installed. [Default is /usr/lib/x86_64-linux-gnu]:


Please specify the NCCL version you want to use. If NCCL 2.2 is not installed, then you can use version 1.3 that can be fetched automatically but it may have worse performance with multiple GPUs. [Default is 2.2]: 1.3


Please specify a list of comma-separated Cuda compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
Please note that each additional compute capability significantly increases your build time and binary size. [Default is: 6.0]:


Do you want to use clang as CUDA compiler? [y/N]: n
nvcc will be used as CUDA compiler.

Please specify which gcc should be used by nvcc as the host compiler. [Default is /usr/bin/gcc]:


Do you wish to build TensorFlow with MPI support? [y/N]: n
No MPI support will be enabled for TensorFlow.

Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native]:


Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]: n
Not configuring the WORKSPACE for Android builds.

Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See tools/bazel.rc for more details.
        --config=mkl            # Build with MKL support.
        --config=monolithic     # Config for mostly static monolithic build.
        --config=gdr            # Build with GDR support.
        --config=verbs          # Build with libverbs support.
        --config=ngraph         # Build with Intel nGraph support.
Configuration finished

**Comment by angerson** [comment]
Thanks for your report. Can you please attach a complete log of ./configure and bazel build starting from a fresh environment on the `master` branch? I'm afraid we don't provide support for building older versions.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
It has been 29 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
It has been 44 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
We are closing this issue for now due to lack of activity. Please comment if this is still an issue for you. Thanks!
