### ISSUE TITLE
[TF2.0] tf.data.Dataset.from_generator raises `InvalidArgumentError` when using flow_from_directory

### ISSUE THREAD

**Issue by dhassault** [tensorflow/tensorflow#33133]
Hi,
I have an issue when creating tf.data.Dataset with  tf.keras.preprocessing.image.ImageDataGenerator() and flow_from_directory. Seems like the arguments are not passed in the right format. Or maybe I missed something...

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 2.0.0
- Python version: 3.7
- CUDA/cuDNN version: 10.0
- GPU model and memory: GeForce GTX 1050Ti Max-Q

**Code to reproduce the issue**
```
import tensorflow as tf

flowers = tf.keras.utils.get_file(
    'flower_photos',
    'https://storage.googleapis.com/download.tensorflow.org/example_images/flower_photos.tgz',
    untar=True)

img_gen = tf.keras.preprocessing.image.ImageDataGenerator()

BATCH_SIZE = 32
IMG_DIM = 224
NB_CLASSES = 5


ds = tf.data.Dataset.from_generator(
    img_gen.flow_from_directory, args=[flowers,(IMG_DIM, IMG_DIM),'rgb','categorical',BATCH_SIZE,False], 
    output_types=(tf.float32, tf.float32), 
    output_shapes = ([BATCH_SIZE,IMG_DIM,IMG_DIM,3],[BATCH_SIZE,NB_CLASSES]))

it = iter(ds)
batch = next(it)
```

**Other info / logs**
```
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-7-5cabd7ffcaf2> in <module>
----> 1 batch = next(it)

~/anaconda3/envs/classifier/lib/python3.7/site-packages/tensorflow_core/python/data/ops/iterator_ops.py in __next__(self)
    620 
    621   def __next__(self):  # For Python 3 compatibility
--> 622     return self.next()
    623 
    624   def _next_internal(self):

~/anaconda3/envs/classifier/lib/python3.7/site-packages/tensorflow_core/python/data/ops/iterator_ops.py in next(self)
    664     """Returns a nested structure of `Tensor`s containing the next element."""
    665     try:
--> 666       return self._next_internal()
    667     except errors.OutOfRangeError:
    668       raise StopIteration

~/anaconda3/envs/classifier/lib/python3.7/site-packages/tensorflow_core/python/data/ops/iterator_ops.py in _next_internal(self)
    649             self._iterator_resource,
    650             output_types=self._flat_output_types,
--> 651             output_shapes=self._flat_output_shapes)
    652 
    653       try:

~/anaconda3/envs/classifier/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_dataset_ops.py in iterator_get_next_sync(iterator, output_types, output_shapes, name)
   2671       else:
   2672         message = e.message
-> 2673       _six.raise_from(_core._status_to_exception(e.code, message), None)
   2674   # Add nodes to the TensorFlow graph.
   2675   if not isinstance(output_types, (list, tuple)):

~/anaconda3/envs/classifier/lib/python3.7/site-packages/six.py in raise_from(value, from_value)

InvalidArgumentError: ValueError: ('Invalid color mode:', b'rgb', '; expected "rgb", "rgba", or "grayscale".')
Traceback (most recent call last):

  File "/home/dhassault/anaconda3/envs/classifier/lib/python3.7/site-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 464, in get_iterator
    return self._iterators[iterator_id]

KeyError: 0


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/home/dhassault/anaconda3/envs/classifier/lib/python3.7/site-packages/tensorflow_core/python/ops/script_ops.py", line 221, in __call__
    ret = func(*args)

  File "/home/dhassault/anaconda3/envs/classifier/lib/python3.7/site-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 585, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "/home/dhassault/anaconda3/envs/classifier/lib/python3.7/site-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 466, in get_iterator
    iterator = iter(self._generator(*self._args.pop(iterator_id)))

  File "/home/dhassault/anaconda3/envs/classifier/lib/python3.7/site-packages/keras_preprocessing/image/image_data_generator.py", line 540, in flow_from_directory
    interpolation=interpolation

  File "/home/dhassault/anaconda3/envs/classifier/lib/python3.7/site-packages/keras_preprocessing/image/directory_iterator.py", line 93, in __init__
    interpolation)

  File "/home/dhassault/anaconda3/envs/classifier/lib/python3.7/site-packages/keras_preprocessing/image/iterator.py", line 176, in set_processing_attrs
    '; expected "rgb", "rgba", or "grayscale".')

ValueError: ('Invalid color mode:', b'rgb', '; expected "rgb", "rgba", or "grayscale".')


	 [[{{node PyFunc}}]] [Op:IteratorGetNextSync]
```

And especially:
```
ValueError: ('Invalid color mode:', b'rgb', '; expected "rgb", "rgba", or "grayscale".')
```

**Comment by lufol** [comment]
Hi, for me this did it:
```
import tensorflow as tf

flowers = tf.keras.utils.get_file(
    'flower_photos',
    'https://storage.googleapis.com/download.tensorflow.org/example_images/flower_photos.tgz',
    untar=True)
BATCH_SIZE = 32
IMG_DIM = 224
NB_CLASSES = 5

img_gen = tf.keras.preprocessing.image.ImageDataGenerator()
gen = img_gen.flow_from_directory(flowers,(IMG_DIM, IMG_DIM),'rgb',class_mode='categorical',batch_size=BATCH_SIZE,shuffle=False)

ds = tf.data.Dataset.from_generator(lambda: gen, 
    output_types=(tf.float32, tf.float32), 
    output_shapes = ([BATCH_SIZE,IMG_DIM,IMG_DIM,3],[BATCH_SIZE,NB_CLASSES]))

it = iter(ds)
batch = next(it)
print(batch)
```

**Comment by dhassault** [comment]
Thanks!! It works fine :) Is it an expected behavior? By reading https://www.tensorflow.org/guide/data#consuming_python_generators I felt what I was doing was logic.

**Comment by gadagashwini** [comment]
@dhassault, Looks like issue is resolved.Can you please let us know if you are happy to close if no issue persists. Thanks!

**Comment by kechan** [comment]
ds = tf.data.Dataset.from_generator(
    #lambda: gen,                   # This seems to work
    img_gen.flow_from_directory, args=[flowers],     #This doesn't work.
    output_types=(tf.float32, tf.float32), 
    output_shapes=([32,256,256,3], [32,5])
)

Anyone know why? According to code sample and doc, it should work for both.
