### ISSUE TITLE
AutoGraph error with XLA, MKL-DNN, Eager Execution, and custom keras layer

### ISSUE THREAD

**Issue by racinmat** [tensorflow/tensorflow#33149]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS Linux release 7.6.1810 (Core)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary, using conda
- TensorFlow version (use command below): unknown 1.14.0, with intel MKL
- Python version: 3.7.4
- CUDA/cuDNN version: no gpu
- GPU model and memory: no gpu

python build version: ('default', 'Aug 13 2019 20:35:49')
python compiler version: GCC 7.3.0
python implementation: CPython
os kernel version: #1 SMP Mon Jul 29 17:46:05 UTC 2019
os release version: 3.10.0-957.27.2.el7.x86_64
os platform: Linux-3.10.0-957.27.2.el7.x86_64-x86_64-with-centos-7.6.1810-Core
linux distribution: ('CentOS Linux', '7.6.1810', 'Core')
linux os distribution: ('centos', '7.6.1810', 'Core')
architecture: ('64bit', '')
machine: x86_64
== compiler =====================================================
c++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)
== check pips ===================================================
numpy                1.16.4   
protobuf             3.9.2    
tensorflow           1.14.0   
tensorflow-estimator 1.14.0   
gast                    0.3.2

**Describe the current behavior**
AutoGraph not working properly with custom Keras Layer and eager execution.
```
2019-10-08 17:22:48.398589: I tensorflow/core/platform/cpu_feature_guard.cc:145] This TensorFlow binary is optimized with Intel(R) MKL-DNN to use the following CPU instructions in performance critical operations:  SSE4.1 SSE4.2 AVX
To enable them in non-MKL-DNN operations, rebuild TensorFlow with the appropriate compiler flags.
2019-10-08 17:22:48.404575: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2399845000 Hz
2019-10-08 17:22:48.404752: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x56240ed9a1e0 executing computations on platform Host. Devices:
2019-10-08 17:22:48.404799: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
2019-10-08 17:22:48.404944: I tensorflow/core/common_runtime/process_util.cc:115] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
ERROR:tensorflow:Error converting <bound method SegmentedMean.call of <ml_utils.SegmentedMean object at 0x7f9d9e8e6610>>
Traceback (most recent call last):
  File "/home/matej.racinsky/anaconda3/envs/mil_tensorflow/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py", line 524, in to_graph
    return conversion.convert(entity, program_ctx)
  File "/home/matej.racinsky/anaconda3/envs/mil_tensorflow/lib/python3.7/site-packages/tensorflow/python/autograph/impl/conversion.py", line 306, in convert
    entity, program_ctx, free_nonglobal_var_names)
  File "/home/matej.racinsky/anaconda3/envs/mil_tensorflow/lib/python3.7/site-packages/tensorflow/python/autograph/impl/conversion.py", line 229, in _convert_with_cache
    entity, program_ctx)
  File "/home/matej.racinsky/anaconda3/envs/mil_tensorflow/lib/python3.7/site-packages/tensorflow/python/autograph/impl/conversion.py", line 433, in convert_entity_to_ast
    nodes, name, entity_info = convert_func_to_ast(o, program_ctx)
  File "/home/matej.racinsky/anaconda3/envs/mil_tensorflow/lib/python3.7/site-packages/tensorflow/python/autograph/impl/conversion.py", line 624, in convert_func_to_ast
    node = node_to_graph(node, context)
  File "/home/matej.racinsky/anaconda3/envs/mil_tensorflow/lib/python3.7/site-packages/tensorflow/python/autograph/impl/conversion.py", line 667, in node_to_graph
    node = converter.apply_(node, context, return_statements)
  File "/home/matej.racinsky/anaconda3/envs/mil_tensorflow/lib/python3.7/site-packages/tensorflow/python/autograph/core/converter.py", line 380, in apply_
    node = converter_module.transform(node, context)
  File "/home/matej.racinsky/anaconda3/envs/mil_tensorflow/lib/python3.7/site-packages/tensorflow/python/autograph/converters/return_statements.py", line 412, in transform
    node = transformer.visit(node)
  File "/home/matej.racinsky/anaconda3/envs/mil_tensorflow/lib/python3.7/site-packages/tensorflow/python/autograph/core/converter.py", line 317, in visit
    return super(Base, self).visit(node)
  File "/home/matej.racinsky/anaconda3/envs/mil_tensorflow/lib/python3.7/site-packages/tensorflow/python/autograph/pyct/transformer.py", line 480, in visit
    result = super(Base, self).visit(node)
  File "/home/matej.racinsky/anaconda3/envs/mil_tensorflow/lib/python3.7/ast.py", line 262, in visit
    return visitor(node)
  File "/home/matej.racinsky/anaconda3/envs/mil_tensorflow/lib/python3.7/site-packages/tensorflow/python/autograph/converters/return_statements.py", line 363, in visit_FunctionDef
    converted_body = self._visit_statement_block(node, node.body)
  File "/home/matej.racinsky/anaconda3/envs/mil_tensorflow/lib/python3.7/site-packages/tensorflow/python/autograph/converters/return_statements.py", line 287, in _visit_statement_block
    nodes = self.visit_block(nodes, after_visit=self._postprocess_statement)
  File "/home/matej.racinsky/anaconda3/envs/mil_tensorflow/lib/python3.7/site-packages/tensorflow/python/autograph/pyct/transformer.py", line 371, in visit_block
    replacement = self.visit(node)
  File "/home/matej.racinsky/anaconda3/envs/mil_tensorflow/lib/python3.7/site-packages/tensorflow/python/autograph/core/converter.py", line 317, in visit
    return super(Base, self).visit(node)
  File "/home/matej.racinsky/anaconda3/envs/mil_tensorflow/lib/python3.7/site-packages/tensorflow/python/autograph/pyct/transformer.py", line 480, in visit
    result = super(Base, self).visit(node)
  File "/home/matej.racinsky/anaconda3/envs/mil_tensorflow/lib/python3.7/ast.py", line 262, in visit
    return visitor(node)
  File "/home/matej.racinsky/anaconda3/envs/mil_tensorflow/lib/python3.7/site-packages/tensorflow/python/autograph/converters/return_statements.py", line 237, in visit_Return
    retval=retval)
  File "/home/matej.racinsky/anaconda3/envs/mil_tensorflow/lib/python3.7/site-packages/tensorflow/python/autograph/pyct/templates.py", line 260, in replace
    replacements[k] = _convert_to_ast(replacements[k])
  File "/home/matej.racinsky/anaconda3/envs/mil_tensorflow/lib/python3.7/site-packages/tensorflow/python/autograph/pyct/templates.py", line 222, in _convert_to_ast
    return gast.Name(id=n, ctx=None, annotation=None)
  File "/home/matej.racinsky/anaconda3/envs/mil_tensorflow/lib/python3.7/site-packages/gast/gast.py", line 19, in create_node
    format(Name, nbparam, len(Fields))
AssertionError: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <bound method SegmentedMean.call of <ml_utils.SegmentedMean object at 0x7f9d9e8e6610>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method SegmentedMean.call of <ml_utils.SegmentedMean object at 0x7f9d9e8e6610>>: AssertionError: Bad argument number for Name: 3, expecting 4
```

**Describe the expected behavior**
Error should not be raised, code should work.

**Code to reproduce the issue**
```
import pandas as pd
import tensorflow as tf
import numpy as np
from sklearn.preprocessing import MultiLabelBinarizer

class SegmentedMean(tf.keras.layers.Layer):
    def __init__(self, *args, **kwargs):
        super(SegmentedMean, self).__init__(*args, **kwargs)

    def call(self, inputs, **kwargs):
        features, segments = inputs
        return tf.math.segment_mean(features, segments)


df = pd.DataFrame({'list': [
    [[1, 2, 3, 4], [2, 3, 6]],
    [[1, 2], [1, 5, 8]],
    [[6, 7, 8], [2, 4, 10], [1, 6]],
    [[3, 4, 6, 8], [1, 8], [2]],
    [[3, 6, 8]],
],
    'label': [0, 0, 1, 1, 1]})
df['list_len'] = df['list'].apply(len)
batch_size = 8
# list of all unique numbers used
nums_used = list(set([i for j in df['list'].apply(lambda k: [i for j in k for i in j]) for i in j]))
list_enc = MultiLabelBinarizer().fit([[i] for i in nums_used])


def create_batch():
    batch_ub = df.sample(batch_size // 2)  # upper bound, will trim so the batch size is correct after expansion
    batch_end = (batch_ub['list_len'].cumsum() <= batch_size)[::-1].idxmax()
    batch = batch_ub.loc[:batch_end].copy()
    batch['id'] = np.arange(0, len(batch))
    feat_bags = batch['list'].apply(list_enc.transform)
    feats = np.concatenate(feat_bags.values)
    # so I know which data to group together during segmentation
    segments = batch['id'].repeat(batch['list_len']).values
    labels = batch['label'].values.astype(np.int32)
    return (feats, segments), labels


settings = {'k': 40, 'iterations': 10}
feats_len = len(nums_used)
inputs = tf.keras.Input(shape=(feats_len,), name='features')
segments = tf.keras.Input(shape=(), name='segments', dtype=tf.int32)
x = tf.keras.layers.Dense(settings['k'], activation=tf.nn.relu)(inputs)
x = tf.keras.layers.Dense(settings['k'])(x)

x = SegmentedMean()((x, segments))
x = tf.keras.layers.Dense(settings['k'], activation=tf.nn.relu)(x)
logits = tf.keras.layers.Dense(2, name='output_logits')(x)
probs = tf.keras.layers.Softmax()(logits)
model = tf.keras.Model(inputs=(inputs, segments), outputs=(logits, probs), name='mil_model')
optimizer = tf.keras.optimizers.Adam()
loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
for step in range(settings['iterations']):
    x_train, y_train = create_batch()
    with tf.GradientTape() as tape:
        logits, probs = model(x_train)
        loss_value = loss(y_train, logits)
    grads = tape.gradient(loss_value, model.trainable_weights)
    optimizer.apply_gradients(zip(grads, model.trainable_weights))
```

**Other info / logs**
Logs are included above.

**Comment by gadagashwini** [comment]
@racinmat, Looks like code is incomplete, please provide the complete code to replicate the issue. And also provide the `gast` version. Thanks!

**Comment by racinmat** [comment]
updated, runnable code with some dummy data and gast version added

**Comment by gadagashwini** [comment]
@racinmat, can you downgrade the `gast` version to 0.2.2 and try. Thanks!

**Comment by racinmat** [comment]
With gast version 0.2.2 it's working.

**Comment by gadagashwini** [comment]
@racinmat, Pip install pull all the compatible dependencies of Tensorflow. The latest version of gast has caused this problem. 
Glad it worked. 
Closing the issue. Thanks!
