### ISSUE TITLE
TPU has XLA compilation issue on TF 1.15rc3

### ISSUE THREAD

**Issue by elyasmehtabuddin** [tensorflow/tensorflow#33152]
**System information**
python: `3.7.3`
tensorflow version: `1.15.0rc3`
[tf_env.txt](https://github.com/tensorflow/tensorflow/files/3704020/tf_env.txt)

**Describe the current behavior**

Error message I get is the following:

```
WARNING:tensorflow:From /usr/local/lib/python3.7/site-packages/tensorflow_core/python/keras/initializers.py:119: calling RandomUniform.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
WARNING:tensorflow:From /usr/local/lib/python3.7/site-packages/tensorflow_core/python/ops/resource_variable_ops.py:1630: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
WARNING:tensorflow:From issue.py:19: The name tf.train.MomentumOptimizer is deprecated. Please use tf.compat.v1.train.MomentumOptimizer instead.

WARNING:tensorflow:From issue.py:30: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

2019-10-08 11:14:04.056451: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2019-10-08 11:14:04.056480: E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: UNKNOWN ERROR (303)
2019-10-08 11:14:04.056497: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (cs-6000-devshell-vm-8cf51c20-59fd-4dc8-ad36-465b49377d09): /proc/driver/nvidia/version does not exist
2019-10-08 11:14:04.056770: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-10-08 11:14:04.069196: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2200000000 Hz
2019-10-08 11:14:04.070092: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x560554da1f40 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2019-10-08 11:14:04.070105: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
WARNING:tensorflow:From issue.py:31: The name tf.global_variables_initializer is deprecated. Please use tf.compat.v1.global_variables_initializer instead.

2019-10-08 11:14:04.154903: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at xla_ops.cc:361 : Invalid argument: Detected unsupported operations when trying to compile graph cluster_3267298482081017018[] on XLA_CPU_JIT: Unique (No registered 'Unique' OpKernel for XLA_CPU_JIT devices compatible with node {{node sgd_momentum/update_embedding/embeddings/Unique}}
	.  Registered:  device='CPU'; T in [DT_BOOL]; out_idx in [DT_INT64]
  device='CPU'; T in [DT_BOOL]; out_idx in [DT_INT32]
  device='CPU'; T in [DT_STRING]; out_idx in [DT_INT64]
  device='CPU'; T in [DT_STRING]; out_idx in [DT_INT32]
  device='CPU'; T in [DT_DOUBLE]; out_idx in [DT_INT64]
  device='CPU'; T in [DT_DOUBLE]; out_idx in [DT_INT32]
  device='CPU'; T in [DT_FLOAT]; out_idx in [DT_INT64]
  device='CPU'; T in [DT_FLOAT]; out_idx in [DT_INT32]
  device='CPU'; T in [DT_BFLOAT16]; out_idx in [DT_INT64]
  device='CPU'; T in [DT_BFLOAT16]; out_idx in [DT_INT32]
  device='CPU'; T in [DT_HALF]; out_idx in [DT_INT64]
  device='CPU'; T in [DT_HALF]; out_idx in [DT_INT32]
  device='CPU'; T in [DT_INT8]; out_idx in [DT_INT64]
  device='CPU'; T in [DT_INT8]; out_idx in [DT_INT32]
  device='CPU'; T in [DT_UINT8]; out_idx in [DT_INT64]
  device='CPU'; T in [DT_UINT8]; out_idx in [DT_INT32]
  device='CPU'; T in [DT_INT16]; out_idx in [DT_INT64]
  device='CPU'; T in [DT_INT16]; out_idx in [DT_INT32]
  device='CPU'; T in [DT_UINT16]; out_idx in [DT_INT64]
  device='CPU'; T in [DT_UINT16]; out_idx in [DT_INT32]
  device='CPU'; T in [DT_INT32]; out_idx in [DT_INT64]
  device='CPU'; T in [DT_INT32]; out_idx in [DT_INT32]
  device='CPU'; T in [DT_INT64]; out_idx in [DT_INT64]
  device='CPU'; T in [DT_INT64]; out_idx in [DT_INT32]
  device='GPU'; T in [DT_INT64]; out_idx in [DT_INT64]
  device='GPU'; T in [DT_INT64]; out_idx in [DT_INT32]
  device='GPU'; T in [DT_INT32]; out_idx in [DT_INT64]
  device='GPU'; T in [DT_INT32]; out_idx in [DT_INT32]
){{node sgd_momentum/update_embedding/embeddings/Unique}}
	This error might be occurring with the use of xla.compile. If it is not necessary that every Op be compiled with XLA, an alternative is to use auto_jit with OptimizerOptions.global_jit_level = ON_2 or the environment variable TF_XLA_FLAGS="tf_xla_auto_jit=2" which will attempt to use xla to compile as much of the graph as the compiler is able to.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Detected unsupported operations when trying to compile graph cluster_3267298482081017018[] on XLA_CPU_JIT: Unique (No registered 'Unique' OpKernel for XLA_CPU_JIT devices compatible with node {{node sgd_momentum/update_embedding/embeddings/Unique}}
	.  Registered:  device='CPU'; T in [DT_BOOL]; out_idx in [DT_INT64]
  device='CPU'; T in [DT_BOOL]; out_idx in [DT_INT32]
  device='CPU'; T in [DT_STRING]; out_idx in [DT_INT64]
  device='CPU'; T in [DT_STRING]; out_idx in [DT_INT32]
  device='CPU'; T in [DT_DOUBLE]; out_idx in [DT_INT64]
  device='CPU'; T in [DT_DOUBLE]; out_idx in [DT_INT32]
  device='CPU'; T in [DT_FLOAT]; out_idx in [DT_INT64]
  device='CPU'; T in [DT_FLOAT]; out_idx in [DT_INT32]
  device='CPU'; T in [DT_BFLOAT16]; out_idx in [DT_INT64]
  device='CPU'; T in [DT_BFLOAT16]; out_idx in [DT_INT32]
  device='CPU'; T in [DT_HALF]; out_idx in [DT_INT64]
  device='CPU'; T in [DT_HALF]; out_idx in [DT_INT32]
  device='CPU'; T in [DT_INT8]; out_idx in [DT_INT64]
  device='CPU'; T in [DT_INT8]; out_idx in [DT_INT32]
  device='CPU'; T in [DT_UINT8]; out_idx in [DT_INT64]
  device='CPU'; T in [DT_UINT8]; out_idx in [DT_INT32]
  device='CPU'; T in [DT_INT16]; out_idx in [DT_INT64]
  device='CPU'; T in [DT_INT16]; out_idx in [DT_INT32]
  device='CPU'; T in [DT_UINT16]; out_idx in [DT_INT64]
  device='CPU'; T in [DT_UINT16]; out_idx in [DT_INT32]
  device='CPU'; T in [DT_INT32]; out_idx in [DT_INT64]
  device='CPU'; T in [DT_INT32]; out_idx in [DT_INT32]
  device='CPU'; T in [DT_INT64]; out_idx in [DT_INT64]
  device='CPU'; T in [DT_INT64]; out_idx in [DT_INT32]
  device='GPU'; T in [DT_INT64]; out_idx in [DT_INT64]
  device='GPU'; T in [DT_INT64]; out_idx in [DT_INT32]
  device='GPU'; T in [DT_INT32]; out_idx in [DT_INT64]
  device='GPU'; T in [DT_INT32]; out_idx in [DT_INT32]
){{node sgd_momentum/update_embedding/embeddings/Unique}}
	This error might be occurring with the use of xla.compile. If it is not necessary that every Op be compiled with XLA, an alternative is to use auto_jit with OptimizerOptions.global_jit_level = ON_2 or the environment variable TF_XLA_FLAGS="tf_xla_auto_jit=2" which will attempt to use xla to compile as much of the graph as the compiler is able to.
	 [[cluster]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "issue.py", line 32, in <module>
    sess.run(loss)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Detected unsupported operations when trying to compile graph cluster_3267298482081017018[] on XLA_CPU_JIT: Unique (No registered 'Unique' OpKernel for XLA_CPU_JIT devices compatible with node node sgd_momentum/update_embedding/embeddings/Unique (defined at /usr/local/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py:1748) 
	.  Registered:  device='CPU'; T in [DT_BOOL]; out_idx in [DT_INT64]
  device='CPU'; T in [DT_BOOL]; out_idx in [DT_INT32]
  device='CPU'; T in [DT_STRING]; out_idx in [DT_INT64]
  device='CPU'; T in [DT_STRING]; out_idx in [DT_INT32]
  device='CPU'; T in [DT_DOUBLE]; out_idx in [DT_INT64]
  device='CPU'; T in [DT_DOUBLE]; out_idx in [DT_INT32]
  device='CPU'; T in [DT_FLOAT]; out_idx in [DT_INT64]
  device='CPU'; T in [DT_FLOAT]; out_idx in [DT_INT32]
  device='CPU'; T in [DT_BFLOAT16]; out_idx in [DT_INT64]
  device='CPU'; T in [DT_BFLOAT16]; out_idx in [DT_INT32]
  device='CPU'; T in [DT_HALF]; out_idx in [DT_INT64]
  device='CPU'; T in [DT_HALF]; out_idx in [DT_INT32]
  device='CPU'; T in [DT_INT8]; out_idx in [DT_INT64]
  device='CPU'; T in [DT_INT8]; out_idx in [DT_INT32]
  device='CPU'; T in [DT_UINT8]; out_idx in [DT_INT64]
  device='CPU'; T in [DT_UINT8]; out_idx in [DT_INT32]
  device='CPU'; T in [DT_INT16]; out_idx in [DT_INT64]
  device='CPU'; T in [DT_INT16]; out_idx in [DT_INT32]
  device='CPU'; T in [DT_UINT16]; out_idx in [DT_INT64]
  device='CPU'; T in [DT_UINT16]; out_idx in [DT_INT32]
  device='CPU'; T in [DT_INT32]; out_idx in [DT_INT64]
  device='CPU'; T in [DT_INT32]; out_idx in [DT_INT32]
  device='CPU'; T in [DT_INT64]; out_idx in [DT_INT64]
  device='CPU'; T in [DT_INT64]; out_idx in [DT_INT32]
  device='GPU'; T in [DT_INT64]; out_idx in [DT_INT64]
  device='GPU'; T in [DT_INT64]; out_idx in [DT_INT32]
  device='GPU'; T in [DT_INT32]; out_idx in [DT_INT64]
  device='GPU'; T in [DT_INT32]; out_idx in [DT_INT32]
)node sgd_momentum/update_embedding/embeddings/Unique (defined at /usr/local/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py:1748) 
	This error might be occurring with the use of xla.compile. If it is not necessary that every Op be compiled with XLA, an alternative is to use auto_jit with OptimizerOptions.global_jit_level = ON_2 or the environment variable TF_XLA_FLAGS="tf_xla_auto_jit=2" which will attempt to use xla to compile as much of the graph as the compiler is able to.
	 [[cluster]]
```

**Describe the expected behavior**
If I used tf.train.GradientDescentOptimizer instead it would work, I expect using momentum optimizer to work as well.

**Code to reproduce the issue**
```
import os
import tensorflow as tf
from tensorflow.python.compiler.xla import xla
from tensorflow.keras.layers import Embedding

LEARNING_RATE = 0.1
VOCAB_SIZE = 100
HIDDEN_SIZE = 200
MAX_SEQ_LEN = 150

def my_model(features, labels):
    emb = Embedding(VOCAB_SIZE, HIDDEN_SIZE)(features)
    logits = tf.keras.layers.Dense(units=VOCAB_SIZE)(emb)
    crossent = tf.nn.sparse_softmax_cross_entropy_with_logits(
        labels=labels,
        logits=logits
    )
    loss = tf.reduce_mean(crossent)
    optimizer = tf.train.MomentumOptimizer(
        learning_rate=LEARNING_RATE,
        momentum=0.9,
        name='sgd_momentum')
    train_op = optimizer.minimize(loss)
    return loss

src = tf.constant(0, dtype=tf.int32, shape=[MAX_SEQ_LEN])
tgt = tf.constant(1, dtype=tf.int32, shape=[MAX_SEQ_LEN])
(loss,) = xla.compile(my_model, [src, tgt])

sess = tf.Session()
sess.run(tf.global_variables_initializer())
sess.run(loss)
sess.close()
```

**Other info / logs**

Issue occurs when using keras `Embedding` layer alongside an optimizer that is not sgd.
The issue can be fixed by modifying keras implementation by changing:
```
tf.gather(weights, inputs)
```
to
```
tf.gather(tf.multiply(weights,1), inputs)
```

The issue is in the weights being an IndexedSlice which causes any non-sgd optimizer to use the `unique` operation which is unsupported by XLA. However, if you do `tf.multiply(weights,1)` it makes that expression the IndexedSlice and weights itself doesn't become an IndexedSlice but rather a tensor so the optimizer implementation in tensorflow doesn't call `unique`.

**Comment by gadagashwini** [comment]
I Could reproduce the issue on colab with TF 1.15.0rc3. Please see the gist [here](https://colab.sandbox.google.com/gist/gadagashwini/28d349cf4f5b7b9a60254f0e1d25d747/untitled187.ipynb). Thanks!

**Comment by robieta** [comment]
An intermediate solution is to densify the gradients yourself. (I took the liberty of switching your example to use the keras SGD rather than the tf.train one.)
```
import os
import tensorflow as tf
from tensorflow.python.compiler.xla import xla
from tensorflow.keras.layers import Embedding

LEARNING_RATE = 0.1
VOCAB_SIZE = 100
HIDDEN_SIZE = 200
MAX_SEQ_LEN = 150

def my_model(features, labels):
    emb_layer = Embedding(VOCAB_SIZE, HIDDEN_SIZE)
    dense_layer = tf.keras.layers.Dense(units=VOCAB_SIZE)
    emb = emb_layer(features)
    logits = dense_layer(emb)

    crossent = tf.nn.sparse_softmax_cross_entropy_with_logits(
        labels=labels,
        logits=logits
    )
    loss = tf.reduce_mean(crossent)
    optimizer = tf.keras.optimizers.SGD(
        learning_rate=LEARNING_RATE,
        momentum=0.9,
        name='sgd_momentum')
    weights = emb_layer.trainable_weights + dense_layer.trainable_weights
    grads = optimizer.get_gradients(loss, weights)

    # This will "densify" the gradients
    grads = [tf.convert_to_tensor(i) for i in grads]
    optimizer.apply_gradients(zip(grads, weights))
    return loss

src = tf.constant(0, dtype=tf.int32, shape=[MAX_SEQ_LEN])
tgt = tf.constant(1, dtype=tf.int32, shape=[MAX_SEQ_LEN])
(loss,) = xla.compile(my_model, [src, tgt])

sess = tf.Session()
sess.run(tf.global_variables_initializer())
sess.run(loss)
sess.close()
```

@sanjoy How practical is it to support this more generally in XLA? Does the inherent dynamism of sparsity preclude it?

**Comment by sanjoy** [comment]
> @sanjoy How practical is it to support this more generally in XLA? Does the inherent dynamism of sparsity preclude it?

If you're asking about TF's `Unique` op, and if the output shape of `Unique` depends on the input _data_ then supporting it in XLA (as it is today) is not possible.  However, @yunxing might have something to say here.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
