### ISSUE TITLE
[tf2.0] tf.signal.fft2d causes an error when using @tf.function

### ISSUE THREAD

**Issue by ichae** [tensorflow/tensorflow#33173]
tf_version: 2.0.0-beta1
```
import numpy as np
import tensorflow as tf
from tensorflow.python.keras.layers import *
from tensorflow.python.keras import backend as K
from tensorflow.python.keras.models import Model

def build_fftNet(img_shape = (224, 512, 1)):
    input_f = Input(shape=(img_shape))
    
    ins = Lambda(lambda x: (K.mean(x, axis=3)+1)*127.5)(input_f)
    ins = Lambda(lambda x: tf.complex(tf.math.real(x), tf.zeros_like(x)))(ins) # float to complex
    
    fft = Lambda(lambda x: tf.signal.fft2d(ins))(ins)
    fftNet = Model([input_f], [fft], name='fft')

    return fftNet

img_shape = (224, 512, 1)
fftNet = build_fftNet(img_shape)

@tf.function
def fft(blur):
    fft_true = fftNet(blur, training=False)
    return fft_true

blur = np.zeros((1, *img_shape), np.float32)
fft(blur)
```
**@tf.function** gives the following error when using **tf.signal.fft2d**:
```
Traceback (most recent call last):

  File "<ipython-input-122-2efd6297c220>", line 21, in <module>
    fft(blur)

  File "C:\Users\user\Anaconda3\envs\tf20\lib\site-packages\tensorflow\python\eager\def_function.py", line 434, in __call__
    return self._concrete_stateful_fn._filtered_call(canon_args, canon_kwds)  # pylint: disable=protected-access

  File "C:\Users\user\Anaconda3\envs\tf20\lib\site-packages\tensorflow\python\eager\function.py", line 589, in _filtered_call
    (t for t in nest.flatten((args, kwargs), expand_composites=True)

  File "C:\Users\user\Anaconda3\envs\tf20\lib\site-packages\tensorflow\python\eager\function.py", line 671, in _call_flat
    outputs = self._inference_function.call(ctx, args)

  File "C:\Users\user\Anaconda3\envs\tf20\lib\site-packages\tensorflow\python\eager\function.py", line 445, in call
    ctx=ctx)

  File "C:\Users\user\Anaconda3\envs\tf20\lib\site-packages\tensorflow\python\eager\execute.py", line 70, in quick_execute
    raise core._SymbolicException

_SymbolicException
```

**Comment by gadagashwini** [comment]
I could reproduce the issue with TF 2.0.0.beta as well with latest Tf 2.0.0. Please see the colab [gist](https://colab.sandbox.google.com/gist/gadagashwini/bc03562ed4e574b76223e61f7825b314/untitled186.ipynb). Thanks!

**Comment by jvishnuvardhan** [comment]
@ichae I think there was a small typo in your code. When I changed it, everything worked as expected. 

I changed one line in your code from
`fft = Lambda(lambda x: tf.signal.fft2d(ins))(ins)`
to 
`fft = Lambda(lambda x: tf.signal.fft2d(x))(ins)`

Please take a look at the [gist here](https://colab.sandbox.google.com/gist/jvishnuvardhan/86ecdbaee77d1c029754f526eef908ac/tf_33173.ipynb). 

I am closing the issue as it was resolved. Please feel free to open it if the issue persists again. Thanks!
