### ISSUE TITLE
Duplicated Gradient issue during TF Lite conversion with 1.13.2

### ISSUE THREAD

**Issue by egolearner** [tensorflow/tensorflow#33188]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS 7
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): source with tag v1.13.2
- TensorFlow version (use command below): b'v1.13.2-0-g04256c89d8' 1.13.2
- Python version:3.6.5
- Bazel version (if compiling from source): 0.20.0
- GCC/Compiler version (if compiling from source): 4.9.2
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
The following error happened when I was convert my model to tf.lite. It's quite similar to #24525 .
```python
Traceback (most recent call last):
  File "tfconvert.py", line 18, in <module>
    tflite_quantized_model = converter.convert()
  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/lite/python/lite.py", line 455, in convert
    **converter_kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/lite/python/convert.py", line 442, in toco_convert_impl
    input_data.SerializeToString())
  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/lite/python/convert.py", line 205, in toco_convert_protos
    "TOCO failed. See console for info.\n%s\n%s\n" % (stdout, stderr))
tensorflow.lite.python.convert.ConverterError: TOCO failed. See console for info.
2019-10-10 10:12:14.730948: F tensorflow/core/framework/function.cc:1626] Check failed: GetOpGradFactory()->insert({op, func}).second Duplicated gradient for MapAccumulate
```

**Code to reproduce the issue**
```python
converter = tf.lite.TFLiteConverter.from_saved_model(
    model_path, input_arrays=input_arrays, output_arrays=output_arrays, input_shapes=input_shapes)
converter.post_training_quantize=True
converter.target_ops = [
    # tf.lite.OpsSet.TFLITE_BUILTINS,
    tf.lite.OpsSet.SELECT_TF_OPS
]
tflite_quantized_model = converter.convert()
open("quantized_model.tflite", "wb").write(tflite_quantized_model)
```

Any help will be appreciated! Thanks in advance.

**Comment by egolearner** [comment]
Sorry to bother you. Maybe there's sth. wrong with my environment.
