### ISSUE TITLE
TF2.0: TypeError when intializting Variable using constant_initializer

### ISSUE THREAD

**Issue by ibrahimsharaf** [tensorflow/tensorflow#33217]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): **Yes**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Ubuntu 18.04**
- TensorFlow installed from (source or binary): **binary (pip)**
- TensorFlow version (use command below): **2.0.0**
- Python version: **3.7**
- CUDA/cuDNN version: **10.2**
- GPU model and memory: **GTX 1060, 6GB**

**Describe the current behavior**

I get an a `TypeError` execption when I try to initialize `tf.Variable` using `constant_initializer`.
Error: `TypeError: __call__() missing 1 required positional argument: 'shape'`

**Code to reproduce the issue**
```
import tensorflow as tf
import numpy as np

input_init = tf.constant_initializer(np.random.uniform(low=-1, high=1, size=(300, 300)))
input_weights = tf.Variable(input_init, shape=(300, 300))
```

**Other info / logs (Traceback)**

```
Traceback (most recent call last):
  File "/home/ibrahimsharaf/workspace/GenSen/GenSen/garab.py", line 38, in <module>
    input_weights = tf.Variable(input_init, shape=(300, 300))
  File "/home/ibrahimsharaf/miniconda3/envs/gensen-tf/lib/python3.7/site-packages/tensorflow_core/python/ops/variables.py", line 260, in __call__
    return cls._variable_v2_call(*args, **kwargs)
  File "/home/ibrahimsharaf/miniconda3/envs/gensen-tf/lib/python3.7/site-packages/tensorflow_core/python/ops/variables.py", line 254, in _variable_v2_call
    shape=shape)
  File "/home/ibrahimsharaf/miniconda3/envs/gensen-tf/lib/python3.7/site-packages/tensorflow_core/python/ops/variables.py", line 235, in <lambda>
    previous_getter = lambda **kws: default_variable_creator_v2(None, **kws)
  File "/home/ibrahimsharaf/miniconda3/envs/gensen-tf/lib/python3.7/site-packages/tensorflow_core/python/ops/variable_scope.py", line 2556, in default_variable_creator_v2
    shape=shape)
  File "/home/ibrahimsharaf/miniconda3/envs/gensen-tf/lib/python3.7/site-packages/tensorflow_core/python/ops/variables.py", line 262, in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)
  File "/home/ibrahimsharaf/miniconda3/envs/gensen-tf/lib/python3.7/site-packages/tensorflow_core/python/ops/resource_variable_ops.py", line 1406, in __init__
    distribute_strategy=distribute_strategy)
  File "/home/ibrahimsharaf/miniconda3/envs/gensen-tf/lib/python3.7/site-packages/tensorflow_core/python/ops/resource_variable_ops.py", line 1537, in _init_from_args
    initial_value() if init_from_fn else initial_value,
TypeError: __call__() missing 1 required positional argument: 'shape'
```

**Comment by oanush** [comment]
Issue replicating for TF-2.0, kindly find the [gist](https://colab.sandbox.google.com/gist/oanush/b178e109b9b0269ae19aaf8b310d0083/33217.ipynb) of colab. Thanks!

**Comment by rmothukuru** [comment]
@ibrahimsharaf,
The error disappears if you use `tf.constant` instead of `tf.constant_initializer`. Here is the [Gist](https://colab.sandbox.google.com/gist/rmothukuru/d32c881d8ec26ce4a325a32f94a69b43/33217.ipynb). 

For more details about this concept, please refer [this link](https://stackoverflow.com/a/38820162/11530462). Thanks!

**Comment by ibrahimsharaf** [comment]
Thanks @oanush & @rmothukuru!
