### ISSUE TITLE
[TF2]'Tensor' object has no attribute '_keras_history'

### ISSUE THREAD

**Issue by SmileTM** [tensorflow/tensorflow#33215]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.0
- Python version: 3.7

### Problem
in TF2.0 use Keras to save model.h5 ,then load model.h5.

I have saved model.h5 from official.nlp.bert_models.py by use model.save("model.h5") .
everything is ok , but when I load the model.h5 there have some problems.
```python
model =tf.keras.models.load_model('./my_model1.h5', custom_objects={'BertModel':bert_modeling.BertModel})

```
emmmmm, how to solve this problem????
I am not sure this is BUG, but in this link someone say this maybe is a bug.
https://github.com/tensorflow/models/issues/7643

### Traceback
Traceback (most recent call last):
File "/Users/lollipop/Documents/tf2g/false_news/test.py", line 30, in
model =tf.keras.models.load_model('./my_model1.h5', custom_objects={'BertModel':bert_modeling.BertModel})
File "/Users/lollipop/.conda/envs/tf2/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/save.py", line 146, in load_model
return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
File "/Users/lollipop/.conda/envs/tf2/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/hdf5_format.py", line 168, in load_model_from_hdf5
custom_objects=custom_objects)
File "/Users/lollipop/.conda/envs/tf2/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/model_config.py", line 55, in model_from_config
return deserialize(config, custom_objects=custom_objects)
File "/Users/lollipop/.conda/envs/tf2/lib/python3.7/site-packages/tensorflow_core/python/keras/layers/serialization.py", line 102, in deserialize
printable_module_name='layer')
File "/Users/lollipop/.conda/envs/tf2/lib/python3.7/site-packages/tensorflow_core/python/keras/utils/generic_utils.py", line 191, in deserialize_keras_object
list(custom_objects.items())))
File "/Users/lollipop/.conda/envs/tf2/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/network.py", line 906, in from_config
config, custom_objects)
File "/Users/lollipop/.conda/envs/tf2/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/network.py", line 1852, in reconstruct_from_config
process_node(layer, node_data)
File "/Users/lollipop/.conda/envs/tf2/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/network.py", line 1802, in process_node
output_index = nest.flatten(output_tensors)[0]._keras_history.node_index
AttributeError: 'Tensor' object has no attribute '_keras_history'

Process finished with exit code 1

**Comment by gowthamkpr** [comment]
Did you try this [comment](https://github.com/tensorflow/models/issues/7643#issuecomment-540684664)? Let me know if it solves the issue. Thanks!

**Comment by saberkun** [comment]
Hi, even if tf format can be a workaround, this seems to be an issue that TF team need to take a look. @gowthamkpr could we find an owner?

**Comment by SmileTM** [comment]
@gowthamkpr  @saberkun 

yes, **tf.saved_model.save** successed save and load. but I think it is too complex. 
I hope **tf.keras.models.load_model**  can works.

### code
```python
tf.saved_model.save(model, "./outmodel/")

test_input_ids   = np.load('./data/test/input_ids.npy')[:10]
test_input_masks = np.load('./data/test/input_masks.npy')[:10]
test_segment_ids = np.load('./data/test/segment_ids.npy')[:10]

test_input_word_ids  =tf.convert_to_tensor(test_input_ids, dtype=tf.int32)
test_input_mask        =tf.convert_to_tensor(test_input_masks, dtype=tf.int32)
test_input_type_ids   =tf.convert_to_tensor(test_segment_ids, dtype=tf.int32)


loaded = tf.saved_model.load('./outmodel')

# print(list(loaded.signatures.keys()))
infer = loaded.signatures["serving_default"]
# print(infer.structured_outputs)
print(infer(input_mask=test_input_mask,input_type_ids=test_input_type_ids,input_word_ids=test_input_word_ids))
```

**Comment by gowthamkpr** [comment]
@SmileTM @saberkun Can you please try using tf-nightly and let me know if the issue still persists. Thanks!
