### ISSUE TITLE
tcmalloc: large alloc on  Colab and Tensorflow killed on local machine due to over consumption of RAM

### ISSUE THREAD

**Issue by arunumd** [tensorflow/tensorflow#33255]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): Conda
- TensorFlow version (use command below): tensorflow-gpu version 1.9.0
- Python version: 3.6
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): 7.4.0
- CUDA/cuDNN version:  V10.1.243
- GPU model and memory: Quadro RTX 5000; and 16 GB RAM

**Describe the current behavior**

The tensorflow API always tries to consume the maximum RAM even when I have a GPU and the kernel gets killed while training my deep learning algorithm. I referred online on multiple sources ([1](https://stackoverflow.com/questions/45077571/tensorflow-training-killed-by-system), [2](https://stackoverflow.com/questions/42205205/tensorflow-python-script-getting-killed), [3](https://stackoverflow.com/questions/49442670/my-process-being-killed-the-moment-it-start-training-tensorflow-object-detectio), [4](https://stackoverflow.com/questions/45150773/tensorflow-object-detection-training-killed-resource-starvation), [5](https://github.com/tensorflow/models/issues/3497), [6](https://github.com/tensorflow/tensorflow/issues/29365)) and tried the following things :

1.  Reduce the batch size
2. Change the optimizer from adam to momentum

However, none of these suggestions helped to solve the problem.

**Describe the expected behavior**

Be able to train without over consumption of memory and not cause the tensorflow kernel to get killed

**Code to reproduce the issue**

Provide a reproducible test case that is the bare minimum necessary to generate the problem.

I ran the following code in an ipython notebook in both my local machine (local GPU) and Google Colab :
```
!git clone https://github.com/charlesq34/pointnet.git
cd pointnet/sem_seg/
!sh download_data.sh
!python train.py --log_dir log6 --test_area 6
```
**Other info / logs**

The error log is very long and hence I am attaching it in a separate text file here : 
[ERROR_LOG.txt](https://github.com/tensorflow/tensorflow/files/3718556/ERROR_LOG.txt)

**Comment by gadagashwini** [comment]
@arunumd, You would like to try with latest Tenosrflow version 2.0.0. Thanks!

**Comment by arunumd** [comment]
@gadagashwini I tried to install tensorflow 2 using the following command `pip install --upgrade tensorflow==2.0.0-rc0` and then ran the ipython notebook. But the symptoms still don't seem to change. I get the same error still. As you can see below, the **_tcmalloc_** error still persists and there is also a new error related to lack of compatibility between tensorflow2 and tensorflow1

```
tcmalloc: large alloc 3477749760 bytes == 0xdbcc6000 @  0x7fdc37e4b1e7 0x7fdc33bf3d51 0x7fdc33c58a84 0x7fdc33c58bc3 0x7fdc33cf8ade 0x7fdc33cf9344 0x7fdc33cf9492 0x4f8925 0x4f98c7 0x4f6128 0x4f9023 0x6415b2 0x64166a 0x643730 0x62b26e 0x4b4cb0 0x7fdc37a48b97 0x5bdf6a
(23585, 4096, 9)
(23585, 4096)
tcmalloc: large alloc 2992029696 bytes == 0x1b0d8c000 @  0x7fdc37e4b1e7 0x7fdc33bf3d51 0x7fdc33c58a84 0x7fdc33c58bc3 0x7fdc33ce618a 0x7fdc33ce65d8 0x4f9ba9 0x4f6128 0x4f9023 0x6415b2 0x64166a 0x643730 0x62b26e 0x4b4cb0 0x7fdc37a48b97 0x5bdf6a
(20291, 4096, 9) (20291, 4096)
(3294, 4096, 9) (3294, 4096)
Traceback (most recent call last):
  File "train.py", line 276, in <module>
    train()
  File "train.py", line 126, in train
    pointclouds_pl, labels_pl = placeholder_inputs(BATCH_SIZE, NUM_POINT)
  File "/content/pointnet/sem_seg/model.py", line 13, in placeholder_inputs
    pointclouds_pl = tf.placeholder(tf.float32,
AttributeError: module 'tensorflow' has no attribute 'placeholder'
```

**Comment by gadagashwini** [comment]
@arunumd, Tensorflow supports manual device placement and limiting gpu memory growth. Please refer this link. Please let us know if that helps. Thanks!

**Comment by arunumd** [comment]
@gadagashwini After running through a bunch of problems with tensorflow during initial development stage, we felt it was better to look for another reliable API. Hence we made a decision to move to PyTorch. I will be glad to look into this problem again later when I will have time. For now the issue is not resolved.

**Comment by gowthamkpr** [comment]
@arunumd In Tensorflow 2.0, there is no placeholder. If you are using TF 1.x code, You need to update your TF1.x code to TF2.0 code and then run it. 

Please take a look at this [question.](https://stackoverflow.com/questions/56226284/why-do-i-get-attributeerror-module-tensorflow-has-no-attribute-placeholder).

**Comment by arunumd** [comment]
@gowthamkpr That suggestion sounds irrelevant to the problem. As per the description, the stated Tensorflow version is 1.x. So technically there is no necessity to upgrade code to TF 2.x when the installed Tensorflow version is 1.x

**Comment by gowthamkpr** [comment]
> I tried to install tensorflow 2 using the following command pip install --upgrade tensorflow==2.0.0-rc0 and then ran the ipython notebook. But the symptoms still don't seem to change. I get the same error still. As you can see below, the tcmalloc error still persists and there is also a new error related to lack of compatibility between tensorflow2 and tensorflow1

I was referring this comment @arunumd as there is no concept of palce holders in TF2.0

**Comment by arunumd** [comment]
> > I tried to install tensorflow 2 using the following command pip install --upgrade tensorflow==2.0.0-rc0 and then ran the ipython notebook. But the symptoms still don't seem to change. I get the same error still. As you can see below, the tcmalloc error still persists and there is also a new error related to lack of compatibility between tensorflow2 and tensorflow1
> 
> I was referring this comment @arunumd as there is no concept of palce holders in TF2.0

@gadagashwini suggested I try running the same code with TF2.0. So I tried. It didn't work neither. I am not sure if @gadagashwini also expected me to refactor the whole code ? I do not want to refactor anything.. I am interested in knowing whether or TF1.x is capable of running this code without the tmalloc error ? Why is this error being caused ? I think we have to focus on the root problem..

**Comment by gowthamkpr** [comment]
We cannot exactly trace what the error is but please take a look at this issue [here](https://stackoverflow.com/questions/9077457/how-to-trace-tcmalloc-large-alloc) and try to replicate it.

**Comment by gowthamkpr** [comment]
Closing this issue due to the lack of recent activity. Please add additional comments and we can open this issue again. Thanks!

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
It has been 29 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
It has been 44 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
We are closing this issue for now due to lack of activity. Please comment if this is still an issue for you. Thanks!

**Comment by ucalyptus** [comment]
@gowthamkpr i faced the same issue .
tensorflow-gpu==1.15.0
keras==2.2.4
in colab

**Comment by viva2202** [comment]
same here.
torch==1.4.0
in colab

**Comment by arunumd** [comment]
I am interested in seeing a long term solution for this issue which seems to be quite common for many people who are using Tensorflow 1.x. For what it is worth based on the face value of it, it seems like an API issue which cannot be fixed by users. This issue is not resolved until it is proven that there is a permanent fix to this problem.

**Comment by aliamiri1380** [comment]
it's because of loading a large file. I have the same problem but when I truncate my file error disappears

**Comment by henaff** [comment]
What about tensorflow-cpu ? There is no options to lower memory usage like tensorflow for gpu. I've 32GB RAM with a 5900x and it just kill when memory is full like a bad c program

**Comment by Kheem-Dh** [comment]
I am working on sentiBert :
https://github.com/WadeYin9712/SentiBERT

I am facing this issue, again and again, writing two files each one having 6GB and 3GB NumPy binary files.
using 
torch==1.1.0 
torchvision==0.3.0

Can anyone help me with that?

Thanks 
![Screenshot 2022-11-25 152329](https://user-images.githubusercontent.com/77248954/204062847-2764f526-e5cf-4044-96d6-d5425f1405c2.png)
