### ISSUE TITLE
keras.layers.LSTM does not work with model.evaluate after training

### ISSUE THREAD

**Issue by matthew-z** [tensorflow/tensorflow#33258]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian 9.11 (GCE DeepLearning image)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.0.0-rc2-26-g64c3d38 2.0.0
- Python version: 3.7.3 (anaconda3)
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: V10.0.130 + 7.6.4.38
- GPU model and memory: V100 16GB 

**Describe the current behavior**
model.evaluate raises this error after training
```Traceback (most recent call last):
  File "lstm.py", line 76, in <module>
    model.evaluate([left, right], labels)
  File "/home/zhaohaozeng/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 833, in evaluate
    use_multiprocessing=use_multiprocessing)
  File "/home/zhaohaozeng/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 456, in evaluate
import typing
    sample_weight=sample_weight, steps=steps, callbacks=callbacks, **kwargs)
  File "/home/zhaohaozeng/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 444, in _model_iteration
    total_epochs=1)
  File "/home/zhaohaozeng/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 123, in run_one_epoch
    batch_outs = execution_function(iterator)
  File "/home/zhaohaozeng/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 86, in execution_function
    distributed_function(input_fn))
  File "/home/zhaohaozeng/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 457, in __call__
    result = self._call(*args, **kwds)
  File "/home/zhaohaozeng/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 526, in _call
    return self._concrete_stateful_fn._filtered_call(canon_args, canon_kwds)  # pylint: disable=protected-access
  File "/home/zhaohaozeng/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 1141, in _filtered_call
    self.captured_inputs)
  File "/home/zhaohaozeng/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 1224, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager)
  File "/home/zhaohaozeng/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 511, in call
    ctx=ctx)
  File "/home/zhaohaozeng/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/eager/execute.py", line 67, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.NotFoundError: 2 root error(s) found.
  (0) Not found:  Resource AnonymousIterator/AnonymousIterator1/N10tensorflow4data16IteratorResourceE does not exist.
	 [[node IteratorGetNext (defined at /home/zhaohaozeng/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py:1751) ]]
	 [[IteratorGetNext/_45]]
  (1) Not found:  Resource AnonymousIterator/AnonymousIterator1/N10tensorflow4data16IteratorResourceE does not exist.
	 [[node IteratorGetNext (defined at /home/zhaohaozeng/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py:1751) ]]
0 successful operations.
0 derived errors ignored. [Op:__inference_distributed_function_11390]

Function call stack:
distributed_function -> distributed_function
```

**Describe the expected behavior**
`model.evaluate` should not raise this error after training.

**Code to reproduce the issue**
Code and log:  https://gist.github.com/matthew-z/e5848d545b60792dd84bfb9470ea541f

I tested with this machine on GCE:
* n1-standard-4 
* 1 x NVIDIA Tesla V100
* image: c1-deeplearning-common-cu100-20191003 (Google Deep Learning VM, common-dl-gpu)
* installed anaconda3, CUDNN 7.6.4.38 (got some errors with the original 7.4 CUDNN in the image), tensorflow-gpu 2.0

**Other info / logs**
The problem may not happen with CPU.

**Comment by ravikyram** [comment]
I have tried on colab with TF version 2.0  and was able to reproduce the issue.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/039e4a49146a41cc220c28b3e2b7cacb/untitled266.ipynb).Thanks!

**Comment by qlzh727** [comment]
I can reproduce this issue.

Somehow I don't think its a LSTM issue since the error log didn't indicate anything about LSTM. Also when I change the LSTM layer to SimpleRNN, the issue still persists.

The other experiment I did was change "experimental_run_tf_function=False" in model.compile(), which will let model run in func graph mode, and the issue goes away. So I think there is some issue for the training function in v2.

For now, you can set the "experimental_run_tf_function=False" to walk around the issue. We will dig deep to find the root cause.

Thanks.

**Comment by qlzh727** [comment]
Just tested tested same code again with the latest tf-nigthly and it runs fine now.
