### ISSUE TITLE
TensorFlow import error

### ISSUE THREAD

**Issue by dreddc** [tensorflow/tensorflow#33279]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):windows 7
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):binary
pip3 install --user tensorflow-gpu
- TensorFlow version:2.0
- Python version:3.7.3 64bit
- Installed using virtualenv? pip? conda?:pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:10.0,7.4.1
- GPU model and memory:

**Describe the problem**

Error after installing when importing tensorflow

C:\Users\Dr Edd>python -c "import tensorflow as tf"
Traceback (most recent call last):
  File "C:\Users\Dr Edd\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Dr Edd\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Dr Edd\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Dr Edd\AppData\Local\Programs\Python\Python37\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Dr Edd\AppData\Local\Programs\Python\Python37\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed with error code -1073741795

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Dr Edd\AppData\Roaming\Python\Python37\site-packages\tensorflow\__init__.py", line 98, in <module>
    from tensorflow_core import *
  File "C:\Users\Dr Edd\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\Dr Edd\AppData\Roaming\Python\Python37\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\Users\Dr Edd\AppData\Roaming\Python\Python37\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "C:\Users\Dr Edd\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\Dr Edd\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Dr Edd\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Dr Edd\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Dr Edd\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Dr Edd\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Dr Edd\AppData\Local\Programs\Python\Python37\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Dr Edd\AppData\Local\Programs\Python\Python37\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed with error code -1073741795

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
pip3 install --user tensorflow-gpu
python -c "import tensorflow as tf"

**Any other info / logs**

**Comment by mihaimaruseac** [comment]
Does your CPU support AVX?

**Comment by dreddc** [comment]
no it's an older corei7 architecture

**Comment by mihaimaruseac** [comment]
In this case, all you can do is install from source or find a community build that works on a non-AVX processor

**Comment by ymodak** [comment]
Installing **TensorFlow** (TF) CPU prebuilt binaries:

*TensorFlow release binaries version 1.6 and higher are prebuilt with AVX instruction sets.*  
See [hardware requirements][1] to know more.  

Therefore on any CPU that does not have these instruction sets, either CPU or GPU version of TF will fail to load.
Apparently, your CPU model does not support AVX instruction sets. You can still use TensorFlow with the alternatives given below:  

* Try Google Colab to use TensorFlow.    
 * The easiest way to use TF will be to switch to [google colab](https://colab.sandbox.google.com/notebooks/welcome.ipynb#recent=true). You get pre-installed latest stable TF version. Also you can use ```pip install``` to install any other preferred TF version.  
    * It has an added advantage since you can you easily switch to different hardware accelerators (cpu, gpu, tpu) as per the task. 
    * All you need is a good internet connection and you are all set.  
* Try to build TF from sources by changing CPU optimization flags.


  [1]: https://www.tensorflow.org/install/pip#hardware-requirements

**Comment by mihaimaruseac** [comment]
Also, see #19584

**Comment by ravikyram** [comment]
@dreddc 
Did you get a chance to go through @mihaimaruseac, @ymodak suggestions and let us know if that helps to resolve the issue. Thanks!

**Comment by ravikyram** [comment]
@dreddc 

Any update please. Thanks!

**Comment by dreddc** [comment]
Thanks for all your responses 

Decided to go down build from source option - been busy trying to build TF from sources by changing CPU optimization flags. 

Can't seem to get by TF configuration options stage to specify cuda/cudnn lib locations.
Seems always want to specify linux type setup locations and files
work in progress....

**Comment by ravikyram** [comment]
@dreddc 

Any update on this issue please. Please close this thread if it solves your question. Thanks!

**Comment by ravikyram** [comment]
@dreddc 
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by SadiqKhanRaza** [comment]
I had also the same issue which actually was occuring due to incompatibility of python and tensorflow versions. Tensorflow didn't support python 3.8 so, I downgraded it to python 3.5 and it worked like a charm..:)

**Comment by saicharan0304** [comment]
Using TensorFlow backend.
Traceback (most recent call last):
  File "C:/Users/SAI CHARAN.DESKTOP-44A9F0G/OneDrive/Desktop/new arya/edithnew.py", line 20, in <module>
    w = nltk.word_tokenize(pattern)
  File "C:\Users\SAI CHARAN.DESKTOP-44A9F0G\AppData\Local\Programs\Python\Python37\lib\site-packages\nltk\tokenize\__init__.py", line 129, in word_tokenize
    sentences = [text] if preserve_line else sent_tokenize(text, language)
  File "C:\Users\SAI CHARAN.DESKTOP-44A9F0G\AppData\Local\Programs\Python\Python37\lib\site-packages\nltk\tokenize\__init__.py", line 106, in sent_tokenize
    tokenizer = load("tokenizers/punkt/{0}.pickle".format(language))
  File "C:\Users\SAI CHARAN.DESKTOP-44A9F0G\AppData\Local\Programs\Python\Python37\lib\site-packages\nltk\data.py", line 752, in load
    opened_resource = _open(resource_url)
  File "C:\Users\SAI CHARAN.DESKTOP-44A9F0G\AppData\Local\Programs\Python\Python37\lib\site-packages\nltk\data.py", line 877, in _open
    return find(path_, path + [""]).open()
  File "C:\Users\SAI CHARAN.DESKTOP-44A9F0G\AppData\Local\Programs\Python\Python37\lib\site-packages\nltk\data.py", line 585, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource [93mpunkt[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('punkt')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mtokenizers/punkt/english.pickle[0m

  Searched in:
    - 'C:\\Users\\SAI CHARAN.DESKTOP-44A9F0G/nltk_data'
    - 'C:\\Users\\SAI CHARAN.DESKTOP-44A9F0G\\AppData\\Local\\Programs\\Python\\Python37\\nltk_data'
    - 'C:\\Users\\SAI CHARAN.DESKTOP-44A9F0G\\AppData\\Local\\Programs\\Python\\Python37\\share\\nltk_data'
    - 'C:\\Users\\SAI CHARAN.DESKTOP-44A9F0G\\AppData\\Local\\Programs\\Python\\Python37\\lib\\nltk_data'
    - 'C:\\Users\\SAI CHARAN.DESKTOP-44A9F0G\\AppData\\Roaming\\nltk_data'
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'
    - ''
**********************************************************************






i am getting the following error while training the chatbot

**Comment by rishikant2000** [comment]
(venv) C:\Users\Rishi.MSS2015\Desktop\FlaskApp>flask run
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Usage: flask run [OPTIONS]

Error: While importing "app", an ImportError was raised:

Traceback (most recent call last):
  File "c:\users\rishi.mss2015\desktop\flaskapp\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\rishi.mss2015\desktop\flaskapp\venv\lib\site-packages\flask\cli.py", line 240, in locate_app
    __import__(module_name)
  File "C:\Users\Rishi.MSS2015\Desktop\FlaskApp\app.py", line 5, in <module>
    import tensorflow as tf
  File "c:\users\rishi.mss2015\desktop\flaskapp\venv\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "c:\users\rishi.mss2015\desktop\flaskapp\venv\lib\site-packages\tensorflow\python\__init__.py", line 40, in <module>
    from tensorflow.python.eager import context
  File "c:\users\rishi.mss2015\desktop\flaskapp\venv\lib\site-packages\tensorflow\python\eager\context.py", line 35, in <module>
    from tensorflow.python import pywrap_tfe
  File "c:\users\rishi.mss2015\desktop\flaskapp\venv\lib\site-packages\tensorflow\python\pywrap_tfe.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "c:\users\rishi.mss2015\desktop\flaskapp\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 83, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "c:\users\rishi.mss2015\desktop\flaskapp\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed: The specified module could not be found.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

How to solve this, please help.
