### ISSUE TITLE
[tf2] isinstance(numeric_column, FeatureColumn)  == false

### ISSUE THREAD

**Issue by dulm** [tensorflow/tensorflow#33299]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): mac
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): tf2
- Python version: 3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
diffrent call code,  make `transformation_cache.get(self, state_manager)`  use different FeatureColumn, result in exception.

```python
transformation_cache.get(self, state_manager):
    if not isinstance(key, FeatureColumn):
      raise TypeError('"key" must be either a "str" or "FeatureColumn". '
                      'Provided: {}'.format(key))
```

**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
```python
import tensorflow as tf
from tensorflow import feature_column
import tensorflow.keras as keras
from tensorflow.python.feature_column.feature_column import _LazyBuilder
from tensorflow_core.python.feature_column.feature_column_v2 import _StateManagerImpl, FeatureTransformationCache



def tnumeric():
    price = {'price': [[1.], [2.], [3.], [4.]]} 
    builder = _LazyBuilder(price)

    def transform_fn(x):
        return x + 2

    price_column = feature_column.numeric_column('price', normalizer_fn=transform_fn)

    from tensorflow.python.feature_column.feature_column_v2 import FeatureColumn
    print(isinstance(price_column, FeatureColumn))  # true
    from tensorflow_core.python.feature_column.feature_column_v2 import FeatureColumn
    print(isinstance(price_column, FeatureColumn))   # false

    feature_layer = keras.layers.DenseFeatures([price_column])
    a = feature_layer(price)  # use tensorflow,  true

    sm = _StateManagerImpl(feature_layer, feature_layer.trainable)
    ff=  FeatureTransformationCache(price)
    dt = price_column.get_dense_tensor(ff, sm) # use tensorflow_core, false

tnumeric()
```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

```
Traceback (most recent call last):
  File "/Applications/PyCharm 2019.3 EAP.app/Contents/helpers/pydev/pydevd.py", line 1415, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm 2019.3 EAP.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/lqk/project/PycharmProjects/TF2/numeric.py", line 49, in <module>
  File "/Users/lqk/project/PycharmProjects/TF2/numeric.py", line 35, in tnumeric
    
  File "/Users/lqk/anaconda2/envs/p37t2/lib/python3.7/site-packages/tensorflow_core/python/feature_column/feature_column_v2.py", line 2845, in get_dense_tensor
    return transformation_cache.get(self, state_manager)
  File "/Users/lqk/anaconda2/envs/p37t2/lib/python3.7/site-packages/tensorflow_core/python/feature_column/feature_column_v2.py", line 2604, in get
    'Provided: {}'.format(key))
TypeError: "key" must be either a "str" or "FeatureColumn". Provided: NumericColumn(key='price', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=<function tnumeric.<locals>.transform_fn at 0x11aa0f170>)

```

**Comment by dulm** [comment]
from tensorflow_core.python.feature_column.feature_column_v2 import _StateManagerImpl, FeatureTransformationCache

change to 

from tensorflow.python.feature_column.feature_column_v2 import _StateManagerImpl, FeatureTransformationCache

suc.
but still don't  know why,  the code of FeatureColumn is same, no matter tensorflow or tensorflow_core.
