### ISSUE TITLE
ValueError when using AdamOptimizer

### ISSUE THREAD

**Issue by Mulns** [tensorflow/tensorflow#33323]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 2.0.0
- Python version: 3.7
- CUDA/cuDNN version: CUDA10.0 and cnDNN7.6

**Describe the current behavior**
I instantiate the Adam in two ways, one works but the another report the ValueError.

**Describe the expected behavior**
There should be no difference between two ways to instantiate the optimizers.

**Code to reproduce the issue**
```python
from tensorflow import keras
from tensorflow.python.keras import layers, optimizers
import tensorflow as tf

# model
inp = layers.Input((None, None, 3))
x = layers.Conv2D(32, 3, padding="same")(inp)
x = layers.Conv2D(3, 3, padding="same")(inp)
model = keras.Model(inp, x)

# compile
# opt = keras.optimizers.Adam() # This method works
opt = optimizers.Adam()  # This method doesn't work
model.compile(optimizer=opt, loss="mse")

# data
x = tf.ones((16, 48, 48, 3))
y = tf.zeros((16, 48, 48, 3))

# train
model.fit(x, y, batch_size=1)

```

**Other info / logs**

```
Traceback (most recent call last):
  File "/home/weitong/anaconda3/envs/tf2.0/lib/python3.7/site-packages/tensorflow_core/python/framework/op_def_library.py", line 527, in _apply_op_helper
    preferred_dtype=default_dtype)
  File "/home/weitong/anaconda3/envs/tf2.0/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 1296, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/weitong/anaconda3/envs/tf2.0/lib/python3.7/site-packages/tensorflow_core/python/framework/constant_op.py", line 286, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/home/weitong/anaconda3/envs/tf2.0/lib/python3.7/site-packages/tensorflow_core/python/framework/constant_op.py", line 227, in constant
    allow_broadcast=True)
  File "/home/weitong/anaconda3/envs/tf2.0/lib/python3.7/site-packages/tensorflow_core/python/framework/constant_op.py", line 265, in _constant_impl
    allow_broadcast=allow_broadcast))
  File "/home/weitong/anaconda3/envs/tf2.0/lib/python3.7/site-packages/tensorflow_core/python/framework/tensor_util.py", line 437, in make_tensor_proto
    raise ValueError("None values not supported.")
ValueError: None values not supported.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/weitong/anaconda3/envs/tf2.0/lib/python3.7/site-packages/tensorflow_core/python/framework/op_def_library.py", line 541, in _apply_op_helper
    values, as_ref=input_arg.is_ref).dtype.name
  File "/home/weitong/anaconda3/envs/tf2.0/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 1296, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/weitong/anaconda3/envs/tf2.0/lib/python3.7/site-packages/tensorflow_core/python/framework/constant_op.py", line 286, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/home/weitong/anaconda3/envs/tf2.0/lib/python3.7/site-packages/tensorflow_core/python/framework/constant_op.py", line 227, in constant
    allow_broadcast=True)
  File "/home/weitong/anaconda3/envs/tf2.0/lib/python3.7/site-packages/tensorflow_core/python/framework/constant_op.py", line 265, in _constant_impl
    allow_broadcast=allow_broadcast))
  File "/home/weitong/anaconda3/envs/tf2.0/lib/python3.7/site-packages/tensorflow_core/python/framework/tensor_util.py", line 437, in make_tensor_proto
    raise ValueError("None values not supported.")
ValueError: None values not supported.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "demo.py", line 21, in <module>
    model.fit(x, y, batch_size=1)
  File "/home/weitong/anaconda3/envs/tf2.0/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 728, in fit
    use_multiprocessing=use_multiprocessing)
  File "/home/weitong/anaconda3/envs/tf2.0/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_arrays.py", line 674, in fit
    steps_name='steps_per_epoch')
  File "/home/weitong/anaconda3/envs/tf2.0/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_arrays.py", line 189, in model_iteration
    f = _make_execution_function(model, mode)
  File "/home/weitong/anaconda3/envs/tf2.0/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_arrays.py", line 565, in _make_execution_function
    return model._make_execution_function(mode)
  File "/home/weitong/anaconda3/envs/tf2.0/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 2184, in _make_execution_function
    self._make_train_function()
  File "/home/weitong/anaconda3/envs/tf2.0/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 2116, in _make_train_function
    params=self._collected_trainable_weights, loss=self.total_loss)
  File "/home/weitong/anaconda3/envs/tf2.0/lib/python3.7/site-packages/tensorflow_core/python/keras/optimizers.py", line 476, in get_updates
    grads = self.get_gradients(loss, params)
  File "/home/weitong/anaconda3/envs/tf2.0/lib/python3.7/site-packages/tensorflow_core/python/keras/optimizers.py", line 92, in get_gradients
    if None in grads:
  File "/home/weitong/anaconda3/envs/tf2.0/lib/python3.7/site-packages/tensorflow_core/python/ops/math_ops.py", line 1336, in tensor_equals
    return gen_math_ops.equal(self, other)
  File "/home/weitong/anaconda3/envs/tf2.0/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_math_ops.py", line 3627, in equal
    name=name)
  File "/home/weitong/anaconda3/envs/tf2.0/lib/python3.7/site-packages/tensorflow_core/python/framework/op_def_library.py", line 545, in _apply_op_helper
    (input_name, err))
ValueError: Tried to convert 'y' to a tensor and failed. Error: None values not supported.
```

**Comment by Nephalen** [comment]
There is another post mentioning the implementation of these two are different.

**Comment by oanush** [comment]
Issue replicating for TF-2.0, kindly find the [gist](https://colab.sandbox.google.com/gist/oanush/ec7b69ab776f7d708a0d8de94900c6c7/33323.ipynb) of colab.Thanks!

**Comment by jvishnuvardhan** [comment]
@Mulns Anything under `tf.python.*` is private, intended for development only, rather than public use. Importing from tensorflow.python or any other modules (including import tensorflow_core...) is not supported, and can break unannounced. For full response on similar issue, you can check [here](https://github.com/tensorflow/tensorflow/issues/33075#issuecomment-539070546).

I am closing the issue as it was resolved. Please feel free to open it if the issue persists again. Thanks!
