### ISSUE TITLE
Error when Saving Whole Model Keras Model with LSTM / Embedding with Checkpoints 

### ISSUE THREAD

**Issue by TheLampshady** [tensorflow/tensorflow#33355]
When running the model with the model checkpoint callback and adding `save_weights_only=True`, it works. 

Install:
pip install tensorflow==2.0.0

Model:
```
    model = keras.Sequential([
        keras.layers.Embedding(vocab_size, embedding_dim,
                               batch_input_shape=[batch_size, None]),
        keras.layers.GRU(rnn_units,
                         return_sequences=True,
                         stateful=True,
                         recurrent_initializer='glorot_uniform'),
        keras.layers.Dense(vocab_size)
    ])
    def loss(labels, logits):
        return keras.losses.sparse_categorical_crossentropy(labels, logits, from_logits=True)

    optimizer = keras.optimizers.Adam(lr=learning_rate)
    model.compile(optimizer=optimizer, loss=loss)
```
Callback:
```
keras.callbacks.ModelCheckpoint(filepath=checkpoint_prefix)
```
Error
```
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/text_generator_tf2/trainer/task.py", line 112, in <module>
    train_and_evaluate(args)
  File "/text_generator_tf2/trainer/task.py", line 96, in train_and_evaluate
    history = training_model.fit(dataset, steps_per_epoch=2, epochs=args.num_epochs, callbacks=callbacks)
  File "/text_generator_tf2/venv/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 728, in fit
    use_multiprocessing=use_multiprocessing)
  File "/text_generator_tf2/venv/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 372, in fit
    prefix='val_')
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/text_generator_tf2/venv/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 685, in on_epoch
    self.callbacks.on_epoch_end(epoch, epoch_logs)
  File "/text_generator_tf2/venv/lib/python3.7/site-packages/tensorflow_core/python/keras/callbacks.py", line 298, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File text_generator_tf2/venv/lib/python3.7/site-packages/tensorflow_core/python/keras/callbacks.py", line 965, in on_epoch_end
    self._save_model(epoch=epoch, logs=logs)
  File "/text_generator_tf2/venv/lib/python3.7/site-packages/tensorflow_core/python/keras/callbacks.py", line 1012, in _save_model
    self.model.save(filepath, overwrite=True)
  File "/text_generator_tf2/venv/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/network.py", line 975, in save
    signatures, options)
  File "/text_generator_tf2/venv/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/save.py", line 115, in save_model
    signatures, options)
  File "/text_generator_tf2/venv/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/saved_model/save.py", line 74, in save
    save_lib.save(model, filepath, signatures, options)
  File "/text_generator_tf2/venv/lib/python3.7/site-packages/tensorflow_core/python/saved_model/save.py", line 893, in save
    meta_graph_def, saveable_view, signatures, options.namespace_whitelist)
  File "/text_generator_tf2/venv/lib/python3.7/site-packages/tensorflow_core/python/saved_model/save.py", line 593, in _fill_meta_graph_def
    signatures = _generate_signatures(signature_functions, resource_map)
  File "/text_generator_tf2/venv/lib/python3.7/site-packages/tensorflow_core/python/saved_model/save.py", line 465, in _generate_signatures
    function, mapped_inputs, resource_map)
  File "/text_generator_tf2/venv/lib/python3.7/site-packages/tensorflow_core/python/saved_model/save.py", line 417, in _call_function_with_mapped_captures
    function.graph.captures, resource_map)
  File "/text_generator_tf2/venv/lib/python3.7/site-packages/tensorflow_core/python/saved_model/save.py", line 339, in _map_captures_to_created_tensors
    .format(interior))
AssertionError: Tried to export a function which references untracked object Tensor("StatefulPartitionedCall/args_2:0", shape=(), dtype=resource).TensorFlow objects (e.g. tf.Variable) captured by functions must be tracked by assigning them to an attribute of a tracked object or assigned to an attribute of the main object directly.
```

**Comment by gadagashwini** [comment]
@TheLampshady, Please provide the standalone code to replicate the reported issue. Thanks!

**Comment by rmothukuru** [comment]
@TheLampshady,
The error occurs when you try Saving the Model in a Folder, like `model.save('model')`. Model is Saved Successfully if you use the code, `model.save('model.h5')`. Here is the [Gist](https://colab.sandbox.google.com/gist/rmothukuru/db7d5732ecad90087382e76cce4345d7/text_generation.ipynb).

Please refer the similar issue, #33247 for more information.

**Comment by TheLampshady** [comment]
thank you, @rmothukuru , it is similar. I was attempting to upgrade from `tf.keras.experimental.export_saved_model` for use on Googles AI Platform. 

Running with a different model, allows saving with adirectory. 

```
def create_simple_model(input_dim, rnn_units=None, learning_rate=DEFAULT_LR):
    RMSprop = keras.optimizers.RMSprop

    rnn_units = rnn_units or RNN_UNITS
    model = keras.Sequential()
    model.add(layers.LSTM(rnn_units, input_shape=input_dim))
    model.add(layers.Dense(input_dim[-1], activation='softmax'))

    optimizer = RMSprop(learning_rate=learning_rate)
    model.compile(loss='categorical_crossentropy', optimizer=optimizer, metrics=['accuracy'])
    return model
```

I also have a Colab for demo purposes. 

https://colab.research.google.com/drive/1CZvo9GzzGxJ5u7EIy2RQ5liuIOBSe3Ir#scrollTo=laOZb9L5VJdZ&uniqifier=2

**Comment by rmothukuru** [comment]
@TheLampshady,
As per my understanding, this issue is part of the issue, #33247. If so, can we close this issue and can we can follow up with #33247, in order to avoid duplication. I have updated Issue 33247 with your colab so that everything will be at one place. Please let me know your thoughts. Thanks!

**Comment by TheLampshady** [comment]
That works for me. Ty!
