### ISSUE TITLE
No float64 support with batch normalization in Tensorflow 2.0?

### ISSUE THREAD

**Issue by tb438** [tensorflow/tensorflow#33365]
Stock Ubuntu 19.04 with Cuda 10.0, Tensorflow 2.0.0 installed via pip3, Python 3.7.3, GTX1060.

I have a float64 valued dataset with a simple conv2d network that includes tf.keras.layers.BatchNormalization() which is where the error is being thrown I think.

The first set of issues:
```
WARNING:tensorflow:Layer conv2d is casting an input tensor from dtype float64 to the layer's dtype of float32, which is new behavior in TensorFlow 2.  The layer has dtype float32 because it's dtype defaults to floatx.

If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. 
```
After setting tf.keras.backend.set_floatx('float64'), next set of errors:
```
Traceback (most recent call last):
  File "/home/aj/ga.py", line 183, in <module>
    encoder = make_encoder_model(z_dim)
  File "/home/aj/ga.py", line 138, in make_encoder_model
    x = tf.keras.layers.BatchNormalization()(x)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/keras/engine/base_layer.py", line 842, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/keras/layers/normalization.py", line 659, in call
    outputs = self._fused_batch_norm(inputs, training=training)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/keras/layers/normalization.py", line 517, in _fused_batch_norm
    training, _fused_batch_norm_training, _fused_batch_norm_inference)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/keras/utils/tf_utils.py", line 59, in smart_cond
    pred, true_fn=true_fn, false_fn=false_fn, name=name)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/framework/smart_cond.py", line 59, in smart_cond
    name=name)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/ops/control_flow_ops.py", line 1174, in cond
    return cond_v2.cond_v2(pred, true_fn, false_fn, name)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/ops/cond_v2.py", line 84, in cond_v2
    op_return_value=pred)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/framework/func_graph.py", line 915, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/keras/layers/normalization.py", line 503, in _fused_batch_norm_training
    data_format=self._data_format)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/ops/nn_impl.py", line 1509, in fused_batch_norm
    name=name)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/ops/gen_nn_ops.py", line 4620, in fused_batch_norm_v3
    name=name)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/framework/op_def_library.py", line 631, in _apply_op_helper
    param_name=input_name)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/framework/op_def_library.py", line 60, in _SatisfiesTypeConstraint
    ", ".join(dtypes.as_dtype(x).name for x in allowed_list)))
TypeError: Value passed to parameter 'x' has DataType float64 not in list of allowed values: float16, bfloat16, float32
```
So is there perhaps another (hopefully drop in) method of batch normalization that supports float64? I don't want to go hacking at allowed_list and all that.

**Comment by ravikyram** [comment]
@tb438 

In order to expedite the trouble-shooting process, please provide a minimal standalone code to reproduce the issue reported here. Thanks!

**Comment by ravikyram** [comment]
@tb438 

Please, let us know any update on this issue. Thanks!

**Comment by tb438** [comment]
Yes give me another day and I'll upload sanitized code.

**Comment by Byshkin** [comment]
Hi. I have a similar problem. Are there working examples, where batch normalization works with float64 in TF 2?

**Comment by TrailBlazerAI** [comment]
Hi Ravikyram,

Here is code to replicate the issue:

```
Python 3.7.5rc1 (default, Oct  8 2019, 16:47:45) 
[GCC 9.2.1 20191008] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> import tensorflow as tf
>>> print(tf.__version__)
2.0.0
>>> tf.keras.backend.set_floatx('float64')
>>> inputs = tf.keras.layers.Input(shape=(223, 28, 1))
>>> x = tf.keras.layers.Conv2D(filters=32, kernel_size=3, strides=2, padding='same')(inputs)
x = tf.keras.layers.LeakyReLU(0.2)(x)
>>> x = tf.keras.layers.Conv2D(filters=64, kernel_size=3, strides=2, padding='same')(x)
>>> x = tf.keras.layers.BatchNormalization()(x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/keras/engine/base_layer.py", line 842, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/keras/layers/normalization.py", line 659, in call
    outputs = self._fused_batch_norm(inputs, training=training)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/keras/layers/normalization.py", line 517, in _fused_batch_norm
    training, _fused_batch_norm_training, _fused_batch_norm_inference)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/keras/utils/tf_utils.py", line 59, in smart_cond
    pred, true_fn=true_fn, false_fn=false_fn, name=name)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/framework/smart_cond.py", line 59, in smart_cond
    name=name)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/ops/control_flow_ops.py", line 1174, in cond
    return cond_v2.cond_v2(pred, true_fn, false_fn, name)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/ops/cond_v2.py", line 84, in cond_v2
    op_return_value=pred)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/framework/func_graph.py", line 915, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/keras/layers/normalization.py", line 503, in _fused_batch_norm_training
    data_format=self._data_format)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/ops/nn_impl.py", line 1509, in fused_batch_norm
    name=name)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/ops/gen_nn_ops.py", line 4620, in fused_batch_norm_v3
    name=name)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/framework/op_def_library.py", line 631, in _apply_op_helper
    param_name=input_name)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/framework/op_def_library.py", line 60, in _SatisfiesTypeConstraint
    ", ".join(dtypes.as_dtype(x).name for x in allowed_list)))
TypeError: Value passed to parameter 'x' has DataType float64 not in list of allowed values: float16, bfloat16, float32
```

**Comment by tb438** [comment]
Hi Ravikyram,

Here is the code and exception:

Python 3.7.5rc1 (default, Oct  8 2019, 16:47:45) 
[GCC 9.2.1 20191008] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> import tensorflow as tf
>>> print(tf.__version__)
2.0.0
>>> tf.keras.backend.set_floatx('float64')
>>> inputs = tf.keras.layers.Input(shape=(28, 28, 1))
>>> x = tf.keras.layers.Conv2D(filters=32, kernel_size=3, strides=2, padding='same')(inputs)
[...]
>>> x = tf.keras.layers.LeakyReLU(0.2)(x)
>>> x = tf.keras.layers.Conv2D(filters=64, kernel_size=3, strides=2, padding='same')(x)
>>> x = tf.keras.layers.BatchNormalization()(x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/keras/engine/base_layer.py", line 842, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/keras/layers/normalization.py", line 659, in call
    outputs = self._fused_batch_norm(inputs, training=training)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/keras/layers/normalization.py", line 517, in _fused_batch_norm
    training, _fused_batch_norm_training, _fused_batch_norm_inference)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/keras/utils/tf_utils.py", line 59, in smart_cond
    pred, true_fn=true_fn, false_fn=false_fn, name=name)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/framework/smart_cond.py", line 59, in smart_cond
    name=name)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/ops/control_flow_ops.py", line 1174, in cond
    return cond_v2.cond_v2(pred, true_fn, false_fn, name)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/ops/cond_v2.py", line 84, in cond_v2
    op_return_value=pred)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/framework/func_graph.py", line 915, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/keras/layers/normalization.py", line 503, in _fused_batch_norm_training
    data_format=self._data_format)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/ops/nn_impl.py", line 1509, in fused_batch_norm
    name=name)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/ops/gen_nn_ops.py", line 4620, in fused_batch_norm_v3
    name=name)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/framework/op_def_library.py", line 631, in _apply_op_helper
    param_name=input_name)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/framework/op_def_library.py", line 60, in _SatisfiesTypeConstraint
    ", ".join(dtypes.as_dtype(x).name for x in allowed_list)))
TypeError: Value passed to parameter 'x' has DataType float64 not in list of allowed values: float16, bfloat16, float32

**Comment by ravikyram** [comment]
I have tried on colab with TF version 2.0 , 2.1.0-dev20191029 and was able to reproduce the issue.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/e6adf13651041e582a832373063de997/untitled319.ipynb).Thanks!

**Comment by tb438** [comment]
Hi Ravikyram,

Thank you for the prompt response. Using your gist above on Colab, I am still getting the same error?

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-12-fffaff38b358> in <module>()
      5 x = tf.keras.layers.LeakyReLU(0.2)(x)
      6 x = tf.keras.layers.Conv2D(filters=64, kernel_size=3, strides=2, padding='same')(x)
----> 7 x = tf.keras.layers.BatchNormalization()(x)

13 frames
/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/op_def_library.py in _SatisfiesTypeConstraint(dtype, attr_def, param_name)
     58           "allowed values: %s" %
     59           (param_name, dtypes.as_dtype(dtype).name,
---> 60            ", ".join(dtypes.as_dtype(x).name for x in allowed_list)))
     61 
     62 

TypeError: Value passed to parameter 'x' has DataType float64 not in list of allowed values: float16, bfloat16, float32
```

**Comment by fightthepower** [comment]
I am also having the same problem

**Comment by TrailBlazerAI** [comment]
ARE YOU GOOGLE MOTHERFUCKERS GOING TO FIX THIS FLOAT64 ISSUE OR NOT. WHY IS FLOAT64 A SECOND CLASS CITIZEN WHEN IT COMES TO TENSORFLOW 2.0?

LEMME TELL YOU WHAT, THAT LITTLE FLOAT32-SOMETHING-OR-THE-OTHER AINT COMPARE WITH US IN OUR FLOAT64 VALUED DATASETS, AND THE GOOGLE IS STRAIGHT UP DISCRIMINATING() WITHOUT FLOAT64 AT THIS POINT

**Comment by TrailBlazerAI** [comment]
LOOK, AGAIN, YOUR REDUCED PRECISION INT8 AND INT16 AINT MEAN NOTHING TO US, DO YOU UNDERSTAND GOOGLE? YOUR GOOGLE TPU CAIN'T TRAIN, SO IMA GO WITH CUDA128 JUST AS SOON AS YOU BRING MY FLOAT64 BATCH NORMALIZATION BABY BACK

**Comment by kenseii** [comment]
Hello,
Is there a solution for this?
i am getting it when i call the model.predict on boolean data.
it also causes a segmentation fault.

i am using tf2`s keras

**Comment by jreinauld** [comment]
Hi all, supporting float64 would be really cool indeed :)

@TrailBlazerAI maybe consider a change of tone when asking for other people to help you?

**Comment by kenseii** [comment]
> Hello,
> Is there a solution for this?
> i am getting it when i call the model.predict on boolean data.
> it also causes a segmentation fault.
> 
> i am using tf2`s keras

I changed the data to np.float32 and it worked well with tf2, maybe it may help someone still having this issue.

Thanks

**Comment by jreinauld** [comment]
Hello,
Can anyone provide info on the matter?
Is it gonna be fixed? If no, why? Is there a timeline? Are there any blockers?
Many thanks,
- Julien

**Comment by sungholee95** [comment]
Are there any updates to this? I'm facing the same problem and I'm having to set BatchNorm's dtype to float32 for now but it'd be nice to be able to use float64

**Comment by karmel** [comment]
This appears to be an issue with fused batch norm in particular, and if you disable the fused kernel, the code above does not raise an error:

```
import numpy as np
import tensorflow as tf
print(tf.version)
tf.keras.backend.set_floatx('float64')
inputs = tf.keras.layers.Input(shape=(28, 28, 1))
x = tf.keras.layers.Conv2D(filters=32, kernel_size=3, strides=2, padding='same')(inputs)
x = tf.keras.layers.LeakyReLU(0.2)(x)
x = tf.keras.layers.Conv2D(filters=64, kernel_size=3, strides=2, padding='same')(x)
x = tf.keras.layers.BatchNormalization(fused=False)(x)
```

@reedwm / @qlzh727 -- this is an unfortunate hard edge for BatchNorm. Can we either add fp64 support to the fused kernel or not default to fusing for unsupported datatypes?

**Comment by reedwm** [comment]
I'll start by not defaulting to fused for unsupported datatypes. We can add fp64 support to the fused kernel later.
