### ISSUE TITLE
Problem with Keras, Tensorflow

### ISSUE THREAD

**Issue by christosiraklis** [tensorflow/tensorflow#33378]
**System information**
- Windows 10
- TensorFlow installed from anaconda
- Python version: 3.7
- Installed using conda
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: Nvidia GeForce GTX 260, Graphics memory 3GB

Code:

from keras.models import Sequential

Error:

Using TensorFlow backend.
ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

Traceback:

Traceback (most recent call last):
  File "C:\Users\chris\Anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\chris\Anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\chris\Anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\chris\Anaconda3\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\chris\Anaconda3\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\chris\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-1-9c5e0a19b646>", line 1, in <module>
    from keras.models import Sequential
  File "C:\Users\chris\Anaconda3\lib\site-packages\keras\__init__.py", line 3, in <module>
    from . import utils
  File "C:\Users\chris\Anaconda3\lib\site-packages\keras\utils\__init__.py", line 6, in <module>
    from . import conv_utils
  File "C:\Users\chris\Anaconda3\lib\site-packages\keras\utils\conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "C:\Users\chris\Anaconda3\lib\site-packages\keras\backend\__init__.py", line 1, in <module>
    from .load_backend import epsilon
  File "C:\Users\chris\Anaconda3\lib\site-packages\keras\backend\load_backend.py", line 90, in <module>
    from .tensorflow_backend import *
  File "C:\Users\chris\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf
  File "C:\Users\chris\Anaconda3\lib\site-packages\tensorflow\__init__.py", line 98, in <module>
    from tensorflow_core import *
  File "C:\Users\chris\Anaconda3\lib\site-packages\tensorflow_core\__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\chris\Anaconda3\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\Users\chris\Anaconda3\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "C:\Users\chris\Anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\chris\Anaconda3\lib\site-packages\tensorflow_core\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\chris\Anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\chris\Anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\chris\Anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\chris\Anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\chris\Anaconda3\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\chris\Anaconda3\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

Failed to load the native TensorFlow runtime.

**Comment by mihaimaruseac** [comment]
Does your CPU support AVX?

**Comment by christosiraklis** [comment]
Probably not. It's quite an old CPU, Intel Core 2 Quad Q9400. Could you please clarify what the problem is particularly? I tried to install keras several times but it hasn't worked yet.

**Comment by jubjamie** [comment]
The installed package will have been compiled for use with AVX. If you don't have AVX then you'll need to compile yourself for your machine.

See #19584 and #33279.

**Comment by ravikyram** [comment]
@christosiraklis 

TensorFlow release binaries version 1.6 and higher are prebuilt with AVX instruction sets.
Therefore on any CPU that does not have these instruction sets, either CPU or GPU version of TF will fail to load.

Apparently, your CPU model does not support AVX instruction sets. You can still use TensorFlow with the alternatives given below:

Try Google Colab to use TensorFlow.
The easiest way to use TF will be to switch to [google colab](https://colab.sandbox.google.com/notebooks/welcome.ipynb#recent=true). You get pre-installed latest stable TF version. Also you can use pip install to install any other preferred TF version.
It has an added advantage since you can you easily switch to different hardware accelerators
(cpu, gpu, tpu) as per the task.
All you need is a good internet connection and you are all set.
Try to build TF from sources by changing CPU optimization flags.
Please let us know if this helps.

**Comment by ravikyram** [comment]
@christosiraklis 

Please, let us know which TensorFlow version you are using?

TensorFlow release binaries version 1.6 and higher are prebuilt with AVX instruction sets.
Therefore on any CPU that does not have these instruction sets, either CPU or GPU version of TF will fail to load.

Apparently, your CPU model does not support AVX instruction sets. You can still use TensorFlow with the alternatives given below:

- Try Google Colab to use TensorFlow.

1.The easiest way to use TF will be to switch to [google colab](https://colab.sandbox.google.com/notebooks/welcome.ipynb#recent=). You get pre-installed latest stable TF version. Also you can use pip install to install any other preferred TF version.
2.It has an added advantage since you can you easily switch to different hardware accelerators
(cpu, gpu, tpu) as per the task.
3.All you need is a good internet connection and you are all set.

- Try to build TF from sources by changing CPU optimization flags.

Please let us know if this helps.

**Comment by christosiraklis** [comment]
Ok thanks guys. Understood.

**Comment by Ivangelion** [comment]
I am also having this issue but cannot find a way to solve it. Has anyone had this problem solved?

**Comment by christosiraklis** [comment]
Try installing older versions of keras and tensorflow or go with Google Colab.

**Comment by Ivangelion** [comment]
I managed to solved this problem: just following [this post](https://towardsdatascience.com/tensorflow-gpu-installation-made-easy-use-conda-instead-of-pip-52e5249374bc), i.e., creating a new environment with tensorflow-gpu 2.0 support, activating it, and installing all necessary packages (e.g. keras, scikit-learn, etc), will do the trick. 

`conda create --name tf_gpu tensorflow-gpu `
`activate tf_gpu`

I've spent hours trying to install tensorflow-gpu 2.0 in the base environment on Windows 10, but it just can't.

**Comment by Alankriti44** [comment]
i am also facing the same issue and my system is Intel(R) Core(TM) i5-2450M CPU @2.50GHz. I even checked that it supports AVX. And now not able detect the issue.

**Comment by mihaimaruseac** [comment]
@Alankriti44 did you install the latest MSVC redistributable?

**Comment by Alankriti44** [comment]
I have installed it and still not working. I have installed the tensorflow and keras via Anaconda. The error that I got was like this:

Using TensorFlow backend.
Traceback (most recent call last):

  File "<ipython-input-1-6dd4e6629230>", line 1, in <module>
    runfile('C:/Users/HP/Desktop/chatbot/train_chatbot.py', wdir='C:/Users/HP/Desktop/chatbot')

  File "C:\Users\HP\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\Users\HP\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/HP/Desktop/chatbot/train_chatbot.py", line 8, in <module>
    from keras.models import Sequential

  File "C:\Users\HP\Anaconda3\lib\site-packages\keras\__init__.py", line 3, in <module>
    from . import utils

  File "C:\Users\HP\Anaconda3\lib\site-packages\keras\utils\__init__.py", line 6, in <module>
    from . import conv_utils

  File "C:\Users\HP\Anaconda3\lib\site-packages\keras\utils\conv_utils.py", line 9, in <module>
    from .. import backend as K

  File "C:\Users\HP\Anaconda3\lib\site-packages\keras\backend\__init__.py", line 1, in <module>
    from .load_backend import epsilon

  File "C:\Users\HP\Anaconda3\lib\site-packages\keras\backend\load_backend.py", line 90, in <module>
    from .tensorflow_backend import *

  File "C:\Users\HP\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf

ModuleNotFoundError: No module named 'tensorflow'

**Comment by shivapower1985** [comment]
I solved this issue by downloading and installing 
"Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019". It worked for me.

Pre-requisite: Python + Jupyter notebook + tensorflow installation already done

You get this error when you "import tensorflow"

Follow the below steps:

Step 1: Download "Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019 - community edition"

Step 2: Select "Python Workload" while installing Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019

Step 3: Restart your computer once

Step 4: That's it now open Jupyter notebook and "import tensorflow" and the error will not occur

**Comment by Alankriti44** [comment]
I have "Microsoft Visual C++ 2015 Redistributable (x86)-14.0.23026" installed in my system. But still not working. Please guide me what is wrong with it.

**Comment by mihaimaruseac** [comment]
Latest is 2019, not 2015

**Comment by shivapower1985** [comment]
> I have "Microsoft Visual C++ 2015 Redistributable (x86)-14.0.23026" installed in my system. But still not working. Please guide me what is wrong with it.



Please install the latest from the below link.. 

Use community edition and select python workload while installation. 

https://visualstudio.microsoft.com/downloads/


Please restart you computer after the installation is over. 

Please try and let me know what you get.

**Comment by mailtohemantha** [comment]
Step 1: Create a new conda environment where we will install our modules to built our models
Step 2: Open Anaconda Prompt (Run as Administrator)
conda create --name deeplearning
Step 3: Activate the conda environment that we just created use
activate deeplearning
Step 4: Install Keras
conda install -c anaconda keras
Step 5: Install Jupyter 
conda install jupyter #very important if you work on Jupyter Notebook
Step 6: Update tensorflow
pip install --ignore-installed --upgrade tensorflow==2.0
Step 7: Install following 
conda install spyder #very important if you work on spyder
conda install matplotlib
conda install pandas
