### ISSUE TITLE
[TFLite, Converter] Converting error on unusual dense layer

### ISSUE THREAD

**Issue by Vooblin** [tensorflow/tensorflow#33381]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): GIT_VERSION: 'v1.12.1-15611-g025365a736', VERSION: '2.0.0''
- Python version: 3.6.8
- Bazel version (if compiling from source): 0.26.1
- GCC/Compiler version (if compiling from source): GCC 8.3.0
- CUDA/cuDNN version: No
- GPU model and memory: No

**Describe the current behavior**
When run the code below, conversion errors appear that are in the logs below.

**Code to reproduce the issue**
```
import tensorflow as tf

class MyDense(tf.keras.layers.Layer):
  def __init__(self, num_units, **kwargs):
    super(MyDense, self).__init__(**kwargs)
    self.num_units = num_units

  def build(self, input_shape):
    kernel_shape = [input_shape[-1], self.num_units * 2, self.num_units]
    bias_shape = [self.num_units]

    self.kernel = self.add_weight("kernel", shape=kernel_shape, trainable=True)
    self.bias = self.add_weight("bias", shape=bias_shape, trainable=True)
    super(MyDense, self).build(input_shape)

  def call(self, inputs):
    return tf.einsum("ac,cde->ade", inputs, self.kernel) + self.bias

inputs = tf.keras.Input(shape=(10,), dtype=tf.float32)
outputs = MyDense(15)(inputs)
model = tf.keras.Model(inputs=inputs, outputs=outputs)
model.summary()

converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()
print("SUCCESS!")
```

**Logs**
```
2019-10-15 14:43:59.548878: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
2019-10-15 14:43:59.566412: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3100000000 Hz
2019-10-15 14:43:59.567598: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x3502840 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2019-10-15 14:43:59.567616: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
input_1 (InputLayer)         [(None, 10)]              0
_________________________________________________________________
my_dense (MyDense)           (None, 30, 15)            4515
=================================================================
Total params: 4,515
Trainable params: 4,515
Non-trainable params: 0
_________________________________________________________________
2019-10-15 14:43:59.640959: I tensorflow/core/grappler/devices.cc:60] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0 (Note: TensorFlow was not compiled with CUDA support)
2019-10-15 14:43:59.641037: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2019-10-15 14:43:59.642744: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:829] Optimization results for grappler item: graph_to_optimize
2019-10-15 14:43:59.642759: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:831]   function_optimizer: function_optimizer did nothing. time = 0.003ms.
2019-10-15 14:43:59.642763: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:831]   function_optimizer: function_optimizer did nothing. time = 0ms.
2019-10-15 14:43:59.657830: I tensorflow/core/grappler/devices.cc:60] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0 (Note: TensorFlow was not compiled with CUDA support)
2019-10-15 14:43:59.657896: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2019-10-15 14:43:59.660184: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:829] Optimization results for grappler item: graph_to_optimize
2019-10-15 14:43:59.660198: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:831]   constant_folding: Graph size after: 21 nodes (-3), 23 edges (-4), time = 0.76ms.
2019-10-15 14:43:59.660203: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:831]   constant_folding: Graph size after: 21 nodes (0), 23 edges (0), time = 0.248ms.
Traceback (most recent call last):
 File "convert_error.py", line 25, in <module>
   tflite_model = converter.convert()
 File "/workspace/.local/lib/python3.6/site-packages/tensorflow_core/lite/python/lite.py", line 447, in convert
   **converter_kwargs)
 File "/workspace/.local/lib/python3.6/site-packages/tensorflow_core/lite/python/convert.py", line 449, in toco_convert_impl
   enable_mlir_converter=enable_mlir_converter)
 File "/workspace/.local/lib/python3.6/site-packages/tensorflow_core/lite/python/convert.py", line 200, in toco_convert_protos
   raise ConverterError("See console for info.\n%s\n%s\n" % (stdout, stderr))
tensorflow.lite.python.convert.ConverterError: See console for info.
2019-10-15 14:44:00.554744: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 10 operators, 19 arrays (0 quantized)
2019-10-15 14:44:00.554825: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 10 operators, 19 arrays (0 quantized)
2019-10-15 14:44:00.554930: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 1: 3 operators, 8 arrays (0 quantized)
2019-10-15 14:44:00.554945: F tensorflow/lite/toco/graph_transformations/propagate_fixed_sizes.cc:118] Check failed: dim_x == dim_y (450 vs. 15)Dimensions must match
Fatal Python error: Aborted
Current thread 0x00007f4cae2e4740 (most recent call first):
 File "/workspace/.local/lib/python3.6/site-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 52 in execute
 File "/workspace/.local/lib/python3.6/site-packages/absl/app.py", line 250 in _run_main
 File "/workspace/.local/lib/python3.6/site-packages/absl/app.py", line 299 in run
 File "/workspace/.local/lib/python3.6/site-packages/tensorflow_core/python/platform/app.py", line 40 in run
 File "/workspace/.local/lib/python3.6/site-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 89 in main
 File "/workspace/.local/bin//toco_from_protos", line 10 in <module>
Aborted (core dumped)
```

**Comment by oanush** [comment]
Issue replicating for TF-2.0,kindly find the [gist](https://colab.sandbox.google.com/gist/oanush/a016f0f856fc999081bfa50b99ee4f81/33381.ipynb) of colab.

**Comment by amahendrakar** [comment]
@Vooblin,
Could you please add the below two lines of code before converting the model and check if it works.
```
converter.experimental_new_converter = True
converter.target_spec.supported_ops =[tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS] 
```

I was able to run the code without any issues on TensorFlow v2.2.0-rc4. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/881306cb7e11cc4acc09e609dffc3550/33381.ipynb#scrollTo=WVmPWKimGbfq). Thanks!

**Comment by amahendrakar** [comment]
@Vooblin,
Is this still an issue? Please feel free to close the issue if resolved. Thanks!

**Comment by amahendrakar** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
