### ISSUE TITLE
keras.metrics.MeanSquaredError update_state, sample_weight not working as expected

### ISSUE THREAD

**Issue by ShaunSpinelli** [tensorflow/tensorflow#33399]
**System information**
- Have I written custom code: **Yes**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Linux Ubuntu 18.04**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: **N/A**
- TensorFlow installed from (source or binary): **pip**
- TensorFlow version (use command below): **Version: 2.0.0**
- Python version: **Python 3.6.8**
- Bazel version (if compiling from source):**N/A**
- GCC/Compiler version (if compiling from source): **N/A**
- CUDA/cuDNN version: **CUDA Version: 10.2**
- GPU model and memory: **GeForce GTX 1660 Ti, 6GB**

**Describe the current behavior**
Running `update_state` on `tf.keras.metrics.MeanSquaredError` ,raises exception when passing in `sample_weight` even if sample_weight and y_true shape are the same.

Weighting in other metrics works fine so not sure if this is a user error, in which case the docs could be updated, or an acutal bug. 
I haven't had time to look into this deeper but would be open too applying fixes if someone could point me in the right direction, thanks.

```python

m = tf.keras.metrics.MeanSquaredError()
m.update_state([0., 0., 1., 1.], [1., 1., 1., 0.], sample_weight=[1, 1, 1, 0])

```
Error:
`tensorflow.python.framework.errors_impl.InvalidArgumentError: Can not squeeze dim[0], expected a dimension of 1, got 4 [Op:Squeeze]`

**Describe the expected behavior**
Should work the same as all other weighted metrics.

eg:
```python
m = tf.keras.metrics.Mean()
m.update_state([1, 3, 5, 7], sample_weight=[1,1,1,0])

# output: <tf.Variable 'UnreadVariable' shape=() dtype=float32, numpy=3.0>

```

**Code to reproduce the issue**
See above

**Other info / logs**
```
m = tf.keras.metrics.MeanSquaredError()
m.update_state([0., 0., 1., 1.], [1., 1., 1., 0.], sample_weight=[1, 1, 1, 0])

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/shaun/src/tf2_env/lib/python3.6/site-packages/tensorflow_core/python/keras/losses.py", line 128, in __call__
    losses, sample_weight, reduction=self._get_reduction())
  File "/home/shaun/src/tf2_env/lib/python3.6/site-packages/tensorflow_core/python/keras/utils/losses_utils.py", line 107, in compute_weighted_loss
    losses, sample_weight)
  File "/home/shaun/src/tf2_env/lib/python3.6/site-packages/tensorflow_core/python/ops/losses/util.py", line 145, in scale_losses_by_sample_weight
    losses = math_ops.cast(losses, dtypes.float32)
  File "/home/shaun/src/tf2_env/lib/python3.6/site-packages/tensorflow_core/python/ops/losses/util.py", line 97, in squeeze_or_expand_dimensions
    # Use static rank.
  File "/home/shaun/src/tf2_env/lib/python3.6/site-packages/tensorflow_core/python/util/dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "/home/shaun/src/tf2_env/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/shaun/src/tf2_env/lib/python3.6/site-packages/tensorflow_core/python/ops/array_ops.py", line 3649, in squeeze
    return gen_array_ops.squeeze(input, axis, name)
  File "/home/shaun/src/tf2_env/lib/python3.6/site-packages/tensorflow_core/python/ops/gen_array_ops.py", line 10061, in squeeze
    _six.raise_from(_core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: Can not squeeze dim[0], expected a dimension of 1, got 4 [Op:Squeeze]

```

**Comment by gadagashwini** [comment]
Could replicate the issue with Tf 2.0.0. Please see the gist [here](https://colab.sandbox.google.com/gist/gadagashwini/4dcdd7b3b7a9d423c9f5a075465ae0fa/untitled202.ipynb). Thanks!

**Comment by pavithrasv** [comment]
@ShaunSpinelli Sorry that the docs on this are not very clear. Please take a look at the docs that we have for losses here, the same applies to metrics as well. https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/losses.py#L100. 

The input `y_true` and `y_pred` should atleast be 2D with the shape `[batch_size, d0, .. dN]`. 

Please see the test here:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/metrics_test.py#L746
