### ISSUE TITLE
Error: Executing cifar10_train.py on Ubuntu with Cuda

### ISSUE THREAD

**Issue by NexYY** [tensorflow/tensorflow#334]
I just went through the [cifar10 tensorflow tutorial][1] on my mac. This tutorial aroused my enthusiasm for NN so I set a Ubuntu Server up in order to train in large scale.

However I cant run the cifar10_train.py on my server. I always run into this error:

Path of the tensorflow source code:

    ~/python/tensorflow/tensorflow/tensorflow/

Path of the tensorflow virtualenv installation:

    ~/tensorflow/

**Cmd:**

    source ~/tensorflow/bin/activate #activate virtualenv
    python/tensorflow/tensorflow/tensorflow/models/image/cifar10/cifar10_train.py #the raw source code of tensorflow is in ~/python/tensorflow/tensorflow/tensorflow

**Error:**
   
    Traceback (most recent call last):
      File "python/tensorflow/tensorflow/tensorflow/models/image/cifar10/cifar10_train.py", line 28, in <module>
        import tensorflow.python.platform
      File "/home/it13095/tensorflow/local/lib/python2.7/site-packages/tensorflow/__init__.py", line 4, in <module>
        from tensorflow.python import *
      File "/home/it13095/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 22, in <module>
        from tensorflow.python.client.client_lib import *
      File "/home/it13095/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/client/client_lib.py", line 35, in <module>
        from tensorflow.python.client.session import InteractiveSession
      File "/home/it13095/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 11, in <module>
        from tensorflow.python import pywrap_tensorflow as tf_session
      File "/home/it13095/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
        _pywrap_tensorflow = swig_import_helper()
      File "/home/it13095/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
        _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)

I installed tensorflow just like on my mac in a virtualenv and activated it correctly before executing the script. 
As by many in other threads suggested I upgraded already six, however I still got the same error.

**Update 1**
After going the issue threads on github/tensorflow through I noticed this is a bug involving cuda. I added these to my path environment:

    export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/cuda/lib64"
    export CUDA_HOME=/usr/local/cuda

I still run into a error, however it has shortened down to the following:

    Traceback (most recent call last):
    File "cifar10_train.py", line 28, in <module>
    import tensorflow.python.platform
    ImportError: No module named tensorflow.python.platform

**Update 2** As someone suggested, I install protobuf via pip. The Error has once again change for some weird reason:

    Traceback (most recent call last):
      File "cifar10_train.py", line 28, in <module>
        import tensorflow.python.platform
      File "/home/it13095/tensorflow/local/lib/python2.7/site-packages/tensorflow/__init__.py", line 4, in <module>
        from tensorflow.python import *
      File "/home/it13095/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 13, in <module>
        from tensorflow.core.framework.graph_pb2 import *
      File "/home/it13095/tensorflow/local/lib/python2.7/site-packages/tensorflow/core/framework/graph_pb2.py", line 16, in <module>
        from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
      File "/home/it13095/tensorflow/local/lib/python2.7/site-packages/tensorflow/core/framework/attr_value_pb2.py", line 16, in <module>
        from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
      File "/home/it13095/tensorflow/local/lib/python2.7/site-packages/tensorflow/core/framework/tensor_pb2.py", line 16, in <module>
        from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2
      File "/home/it13095/tensorflow/local/lib/python2.7/site-packages/tensorflow/core/framework/tensor_shape_pb2.py", line 22, in <module>
        serialized_pb=_b('\n,tensorflow/core/framework/tensor_shape.proto\x12\ntensorflow\"d\n\x10TensorShapeProto\x12-\n\x03\x64im\x18\x02 \x03(\x0b\x32 .tensorflow.TensorShapeProto.Dim\x1a!\n\x03\x44im\x12\x0c\n\x04size\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\tb\x06proto3')
    TypeError: __init__() got an unexpected keyword argument 'syntax'

  [1]: http://www.tensorflow.org/tutorials/deep_cnn/index.md

**Comment by panmari** [comment]
Are you using python 2? On newer ubuntu releases  (14.04.3 for me), pip defaults to pip3, using python 3
```
pip --version
pip 7.1.2 from /usr/local/lib/python3.4/dist-packages (python 3.4)
```

So to correctly install the tensorflow wheel, you'd need to specifically call pip for python 2 with `pip2`

**Comment by NexYY** [comment]
I checked already on that but it seems to be the right package:
    
    pip --version
    pip 1.5.4 from /usr/lib/python2.7/dist-packages (python 2.7)

**Comment by panmari** [comment]
What's the protobuf version you're using? I had the exact same issue when I started, see https://github.com/tensorflow/tensorflow/issues/4. Maybe this also works for you?

**Comment by vrv** [comment]
De-duping with https://github.com/tensorflow/tensorflow/issues/4 -- also we have this as a common problem listed on our install website: http://www.tensorflow.org/get_started/os_setup.html#common_install_problems
