### ISSUE TITLE
tfliteGpuDelegate Invoke write to buffer failed source data is larger than buffer

### ISSUE THREAD

**Issue by manchengfenxu** [tensorflow/tensorflow#33410]
I followed the steps in https://www.tensorflow.org/lite/performance/gpu and added gpu to tflite interpreter. The mobilenet model given by an android project called tensorflow/lite/jave/demo can work using this project on Pixel 2. However, when it was put into another project with the follwing code. Here comes the errors: 
```
TfLiteGpuDelegate Invoke: Write to buffer failed. Source data is larger than buffer
Node number 31 (TfLiteGpuDelegateV2) failed to invoke.
```
imgData, outputClasses are already checked and have the same size with those in tensorflow/lite/jave/demo project.

Versions of TfLite and TfLiteGpu are also kept the same with that in tensorflow/lite/jave/demo project.

```
import  org.tensorflow.lite.TensorFlowLite;
import org.tensorflow.lite.gpu.GpuDelegate;

/**
 * Wrapper for frozen detection models trained using the Tensorflow Object Detection API:
 * github.com/tensorflow/models/tree/master/research/object_detection
 */
public class TFLiteObjectDetectionAPIModel implements Classifier {
  private static final Logger LOGGER = new Logger();

  // Only return this many results.
  private static final int NUM_DETECTIONS = 1001; // hand landmark ,21, mobilenet, 1001
  // Float model
  private static final float IMAGE_MEAN = 128.0f;
  private static final float IMAGE_STD = 128.0f;
  private boolean isModelQuantized;
  private int inputSize;
  private Vector<String> labels = new Vector<String>();
  private int[] intValues;
  private float[][][] outputLocations;
  private float[][] outputClasses;
  private float[][] outputScores;
  private float[] numDetections;

  private GpuDelegate gpuDelegate = new GpuDelegate();
  private final Interpreter.Options options = (new Interpreter.Options()).addDelegate(gpuDelegate);
  private ByteBuffer imgData;

  private Interpreter tfLite;
  private ArrayList<Recognition> recognitions = new ArrayList<Recognition>();

  private TFLiteObjectDetectionAPIModel() {}

  /** Memory-map the model file in Assets. */
  private static MappedByteBuffer loadModelFile(AssetManager assets, String modelFilename)
      throws IOException {
    FileInputStream inputStream = new FileInputStream(new File("/sdcard/sunny/data/"+modelFilename+".tflite"));

    FileChannel fileChannel = inputStream.getChannel();
    long startOffset = fileChannel.position();
    long declaredLength = fileChannel.size();
    return fileChannel.map(FileChannel.MapMode.READ_ONLY, startOffset, declaredLength);
  }

  /**
   * Initializes a native TensorFlow session for classifying images.
   *
   * @param assetManager The asset manager to be used to load assets.
   * @param modelFilename The filepath of the model GraphDef protocol buffer.
   * @param labelFilename The filepath of label file for classes.
   * @param inputSize The size of image input
   * @param isQuantized Boolean representing model is quantized or not
   */
  public static Classifier create(
      final AssetManager assetManager,
      final String modelFilename,
      final String labelFilename,
      final int inputSize,
      final boolean isQuantized)
      throws IOException {
    final TFLiteObjectDetectionAPIModel d = new TFLiteObjectDetectionAPIModel();

    InputStream labelsInput = null;
    String actualFilename = labelFilename.split("file:///android_asset/")[1];
    labelsInput = assetManager.open(actualFilename);
    BufferedReader br = null;
    br = new BufferedReader(new InputStreamReader(labelsInput));
    String line;
    while ((line = br.readLine()) != null) {
      LOGGER.w(line);
      d.labels.add(line);
    }
    br.close();

    d.inputSize = inputSize;
    try {
      d.tfLite = new Interpreter(loadModelFile(assetManager, modelFilename),d.options);
    } catch (Exception e) {
      throw new RuntimeException(e);
    }

    d.isModelQuantized = isQuantized;
    // Pre-allocate buffers.
    int numBytesPerChannel;
    if (isQuantized) {
      numBytesPerChannel = 1; // Quantized
    } else {
      numBytesPerChannel = 4; // Floating point
    }
    d.imgData = ByteBuffer.allocateDirect(1 * d.inputSize * d.inputSize * 3 * 4);
    d.imgData.order(ByteOrder.nativeOrder());
    d.intValues = new int[d.inputSize * d.inputSize];

    d.outputClasses = new float[1][NUM_DETECTIONS];

    return d;
  }

  @Override
  public List<Recognition> processImage(final AssetManager assetManager, Classifier.Recognition.inputFormat imageFormat, int[] intValues){
    Trace.beginSection("preprocessBitmap");

    imgData.rewind();
    for (int i = 0; i < inputSize; ++i) {
      for (int j = 0; j < inputSize; ++j) {
        int pixelValue = intValues[i * inputSize + j];
        if (isModelQuantized) {
          // Quantized model
          imgData.put((byte) ((pixelValue >> 16) & 0xFF));
          imgData.put((byte) ((pixelValue >> 8) & 0xFF));
          imgData.put((byte) (pixelValue & 0xFF));
        } else { // Float model
          imgData.putFloat((((pixelValue >> 16) & 0xFF) - IMAGE_MEAN) / IMAGE_STD);
          imgData.putFloat((((pixelValue >> 8) & 0xFF) - IMAGE_MEAN) / IMAGE_STD);
          imgData.putFloat(((pixelValue & 0xFF) - IMAGE_MEAN) / IMAGE_STD);
        }
      }
    }
    Trace.endSection(); // preprocessBitmap

    // Copy the input data into TensorFlow.
    Trace.beginSection("feed");
    outputClasses = new float[1][NUM_DETECTIONS];
    Trace.endSection();

    // Run the inference call.
    Trace.beginSection("run");
    tfLite.run(imgData, outputClasses);
    Trace.endSection();

    return recognitions;
  }


  @Override
  public void enableStatLogging(final boolean logStats) {}

  @Override
  public String getStatString() {
    return "";
  }

  @Override
  public void close() {
    tfLite.close();
    tfLite = null;
    recognitions.clear();
    recognitions=null;
    gpuDelegate.close();
    gpuDelegate = null;
}
```

**Comment by impjdi** [comment]
@manchengfenxu The error message is printed by `GlBuffer`.  I think you're trying to write more than what you can.  MobileNet IIRC has the input dimensions of size 224x224.  Is `inputSize = 224` ?

**Comment by manchengfenxu** [comment]
> 
> 
> @manchengfenxu The error message is printed by `GlBuffer`. I think you're trying to write more than what you can. MobileNet IIRC has the input dimensions of size 224x224. Is `inputSize = 224` ?

Yes，inputSize = 224，the same with that in tensorflow/lite/jave/demo. I also found this message "Write to buffer failed. Source data is larger than buffer" in source code of GlBuffer. That is why I checked the size of imgData, output Classes carefully and compared them with those in tensorflow/lite/jave/demo but didn't found any clue. Is it the problem of the wrong usage of openGl? I didn't find any code related to invoking OpenGL in tensorflow/lite/jave/demo, so no code was for invoking OpenGL in this project with errors.

**Comment by mhutti1** [comment]
I am having a similar issue. My model runs fine on CPU and GPU on my Galaxy S8 but only works on the CPU of my Nexus 5X.

I assume it is an issue with part of the OpenGL buffer.

``` Process: xyz.hutt.meng, PID: 12866
    java.lang.IllegalArgumentException: Internal error: Failed to run on the given Interpreter: OpenCL library not loaded - dlopen failed: library "libOpenCL-pixel.so" not found
    Falling back to OpenGL
    TfLiteGpuDelegate Invoke: Write to buffer failed. Source data is larger than buffer.
    Node number 51 (TfLiteGpuDelegateV2) failed to invoke.
    
        at org.tensorflow.lite.NativeInterpreterWrapper.run(Native Method)
        at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:154)
        at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:314)
        at org.tensorflow.lite.Interpreter.run(Interpreter.java:275)
        at xyz.hutt.meng.models.SonoNet.recognizeBuffer(SonoNet.kt:98)
        at xyz.hutt.meng.models.SonoNet.recognizeImage(SonoNet.kt:136)
        at xyz.hutt.meng.models.SonoNet.process(SonoNet.kt:74)
        at xyz.hutt.meng.BitmapProcessor.processBitmap(BitmapProcessor.kt:82)
        at xyz.hutt.meng.BitmapProcessor.processBitmap(BitmapProcessor.kt:19)
        at xyz.hutt.meng.BitmapCapture$start$1.invoke(BitmapCapture.kt:62)
        at xyz.hutt.meng.BitmapCapture$start$1.invoke(BitmapCapture.kt:15)
        at xyz.hutt.meng.BitmapCapture$ImageListener.onImageAvailable(BitmapCapture.kt:81)
        at android.media.ImageReader$ListenerHandler.handleMessage(ImageReader.java:812)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)```

**Comment by impjdi** [comment]
You could print out and see what the actual values are (how much it's trying to write vs how much you have allocated).  Maybe it can give you a hint what went wrong where.

**Comment by mhutti1** [comment]
@impjdi It works perfectly fine on all my other devices as well as when running fine on the CPU though. It's ```tflite.run(input, output)``` which is erroring. I am not really sure how to debug this.

**Comment by multiverse-tf** [comment]
Such "TfLiteGpuDelegate Invoke: Write to buffer failed. Source data is larger than buffer" also appears in more recent issues like https://github.com/tensorflow/tensorflow/issues/41839, https://github.com/tensorflow/tensorflow/issues/44659. Just wondering does more recent tflite build (tflite 2.3.0, tf-nightly etc.) fix the issue? Thx!
