### ISSUE TITLE
Can't Load tf.keras Saved h5 Model in TF 2.0 CPU Version

### ISSUE THREAD

**Issue by ydcjeff** [tensorflow/tensorflow#33474]
I can't load tf.keras h5 Model in TF 2.0 CPU Version.
* OS: MacOS Catalina 10.15
* Python version: 3.7.4
* Env: virtualenv as described in TF official website
* TF Version: 2.0 Stable **CPU** version installed with `pip install tensorflow`

![Screen Shot 2019-10-17 at 21 51 06](https://user-images.githubusercontent.com/32727188/67023093-3f083880-f128-11e9-9448-c9c898c0bf62.png)

First, I trained the model in google colab with **gpu** by installing `!pip install tensorflow-gpu` and saved the model in google colab with **`model.save(main.h5)`** 
And, I can load the saved h5 model in colab, so I downloaded the saved h5 model from google colab but I **cannot** load the saved h5 model in the local system with 
**`model = tf.keras.models.load_model("main.h5")`**

![Screen Shot 2019-10-17 at 21 10 35](https://user-images.githubusercontent.com/32727188/67022943-023c4180-f128-11e9-8918-2cefa7eda157.png)

[Colab Notebook Here](https://nbviewer.jupyter.org/github/ydcjeff/cvify/blob/master/main.ipynb)

Thank You

**Comment by gowthamkpr** [comment]
@ydcjeff Can you please share some reproducible code for us to expedite the process. Thanks!

**Comment by ydcjeff** [comment]
@gowthamkpr 
### Below is the code I used in **Google Colab** for training with **GPU** with TF 2.0 Stable
```py
!pip install tensorflow-gpu
import tensorflow as tf
import numpy as np
import pandas as pd

data = pd.read_csv('https://raw.githubusercontent.com/ydcjeff/cvify/master/dataset.csv', header=None)
X = data.sample(frac=1)
X = X.sample(frac=1)
X = X.sample(frac=1)
X = X.sample(frac=1)
X = X.sample(frac=1)

train_len = int(len(X) * 0.8)
test_len = int(len(X) - train_len)

train_df = X[0:train_len]
test_df = X[-test_len:]
print(train_df.shape)
print(test_df.shape)

# convert string to lower case 
train_texts = train_df[1].values 
train_texts = [s.lower() for s in train_texts]

test_texts = test_df[1].values 
test_texts = [s.lower() for s in test_texts]

#=======================Convert string to index================
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Tokenizer
tk = Tokenizer(num_words=None, char_level=True, oov_token='UNK')
tk.fit_on_texts(train_texts)
# If we already have a character list, then replace the tk.word_index
# If not, just skip below part

#-----------------------Skip part start--------------------------
# construct a new vocabulary 
alphabet="abcdefghijklmnopqrstuvwxyz0123456789 ,;.!?:'\"/\\|_@#$%^&*~`+-=<>()[]{}"
char_dict = {}
for i, char in enumerate(alphabet):
    char_dict[char] = i + 1
    
# Use char_dict to replace the tk.word_index
tk.word_index = char_dict.copy() 
# Add 'UNK' to the vocabulary 
tk.word_index[tk.oov_token] = max(char_dict.values()) + 1
#-----------------------Skip part end----------------------------

# Convert string to index 
train_sequences = tk.texts_to_sequences(train_texts)
test_texts = tk.texts_to_sequences(test_texts)

# Padding
train_data = pad_sequences(train_sequences, maxlen=1014, padding='post')
test_data = pad_sequences(test_texts, maxlen=1014, padding='post')

# Convert to numpy array
train_data = np.array(train_data, dtype='float32')
test_data = np.array(test_data, dtype='float32')

#=======================Get classes================
train_classes = train_df[0].values
train_class_list = [x-1 for x in train_classes]

test_classes = test_df[0].values
test_class_list = [x-1 for x in test_classes]

from tensorflow.keras.utils import to_categorical
train_classes = to_categorical(train_class_list)
test_classes = to_categorical(test_class_list)

print(tk.word_index)

vocab_size = len(tk.word_index)

from tensorflow.keras.layers import Input, Embedding, Activation, Flatten, Dense
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Dropout
from tensorflow.keras.models import Model

# =====================Char CNN in whole dataset=======================
# parameter
tf.keras.backend.clear_session()
#@tf.function
input_size = 1014
vocab_size = len(tk.word_index)
embedding_size = 70
conv_layers = [[256, 7, 3],
               [256, 7, 3],
               [256, 3, -1],
               [256, 3, -1],
               [256, 3, -1],
               [256, 3, 3]]

fully_connected_layers = [1024, 1024]
num_of_classes = 2
dropout_p = 0.5
optimizer = 'adam'
loss = 'binary_crossentropy'

# Embedding weights
embedding_weights = []  # (71, 70)
embedding_weights.append(np.zeros(vocab_size))  # (0, 70)

for char, i in tk.word_index.items():  # from index 1 to 70
    onehot = np.zeros(vocab_size)
    onehot[i - 1] = 1
    embedding_weights.append(onehot)

embedding_weights = np.array(embedding_weights)
print('Load')

# Embedding layer Initialization
embedding_layer = Embedding(vocab_size + 1,
                            embedding_size,
                            input_length=input_size,
                            weights=[embedding_weights])

# Model Construction
# Input
inputs = Input(shape=(input_size,), name='input', dtype='int64')  # shape=(?, 1014)
# Embedding
x = embedding_layer(inputs)
# Conv
for filter_num, filter_size, pooling_size in conv_layers:
    x = Conv1D(filter_num, filter_size)(x)
    x = Activation('relu')(x)
    if pooling_size != -1:
        x = MaxPooling1D(pool_size=pooling_size)(x)  # Final shape=(None, 34, 256)
x = Flatten()(x)  # (None, 8704)
# Fully connected layers
for dense_size in fully_connected_layers:
    x = Dense(dense_size, activation='relu')(x)  # dense_size == 1024
    x = Dropout(dropout_p)(x)
# Output Layer
predictions = Dense(num_of_classes, activation='sigmoid')(x)
# Build model
model = Model(inputs=inputs, outputs=predictions)
model.compile(optimizer=optimizer, loss=loss, metrics=['acc'])  # Adam, categorical_crossentropy
model.summary()

# Shuffle
indices = np.arange(train_data.shape[0])
np.random.shuffle(indices)

x_train = train_data[indices]
y_train = train_classes[indices]

x_test = test_data
y_test = test_classes

class myCallback(tf.keras.callbacks.Callback):
  def on_epoch_end(self, epoch, logs={}):
    if(logs.get('val_acc')>0.95):
      print("\nReached 95% validation accuracy so cancelling training!")
      self.model.stop_training = True

callbacks = myCallback()
# Training
hist = model.fit(x_train, y_train,
          validation_data=(x_test, y_test),
          epochs=15,
          verbose=1,
          callbacks = [callbacks])

model.save('main.h5') # Here I saved the model in h5 format

# Here I can load the h5 model in Colab with load_model, (TF 2.0 GPU Stable version)
model = tf.keras.models.load_model('main.h5')
model.summary() # It showed no error

print(tf.__version__) # 2.0.0
```
### And then, I downloaded the saved h5 model from colab into the local system in which I installed TF 2.0 CPU Stable version with `pip install tensorflow`
### Below is my app.py code I used my laptop
```py
from flask import Flask, jsonify, request, session
from flask_cors import CORS
import tensorflow as tf
import numpy as np
import pandas as pd
# from process import pdf2txt

print(tf.__version__)
app = Flask(__name__)
app.secret_key = "super_secret_key"
CORS(app)

# Here I can't load the downloaded h5 model in my local system (TF 2.0 CPU Stable version installed)
model = tf.keras.models.load_model('main.h5')

tk = tf.keras.preprocessing.text.Tokenizer(
    num_words=None, char_level=True, oov_token='UNK')
alphabet = "abcdefghijklmnopqrstuvwxyz0123456789 ,;.!?:'\"/\\|_@#$%^&*~`+-=<>()[]{}"
char_dict = {}

for i, char in enumerate(alphabet):
    char_dict[char] = i + 1

tk.word_index = char_dict.copy()
tk.word_index[tk.oov_token] = max(char_dict.values()) + 1


def prepare_text(data):
    Y = []
    for x in data.split('\n'):
        x.split(';')
        Y.append(x)

    df = pd.DataFrame(Y)
    val_texts = df[0].values
    val_texts = [s.lower() for s in val_texts]
    val_texts = tk.texts_to_sequences(val_texts)
    val_data = tf.keras.preprocessing.sequence.pad_sequences(
        val_texts, maxlen=1014, padding='post')
    val_data = np.array(val_data, dtype='float32')

    return val_data


@app.route('/api/tasks', method=['GET'])
def get_result():
    result = []
    data_result = session['my_result']
    result.append({'title': data_result['title'], 'tag': data_result['tag']})
    session.clear()

    return jsonify(result)


@app.route('/api/task', method=['POST'])
def input_predict_text():
    title = request.get_json()['title']
    text = pdf2txt(title)
    x = prepare_text(text)
    out = model.predict(x)
    print("The First argument in the lists is the accuracy of being Engineering CV")
    print("The Second argument in the lists is the accuracy of being Finance CV")

    return jsonify({'Result': out})


if __name__ == "__main__":
    app.run(debug=True)
```
### Here is the error message running app.py
```py
2.0.0
Traceback (most recent call last):
  File "python/app.py", line 13, in <module>
    model = tf.keras.models.load_model("main.h5")
  File "/Users/ydc/pyjsenv/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/save.py", line 149, in load_model
    loader_impl.parse_saved_model(filepath)
  File "/Users/ydc/pyjsenv/lib/python3.7/site-packages/tensorflow_core/python/saved_model/loader_impl.py", line 83, in parse_saved_model
    constants.SAVED_MODEL_FILENAME_PB))
OSError: SavedModel file does not exist at: main.h5/{saved_model.pbtxt|saved_model.pb}
```
### I don't save the model in ".pb" format and I don't have, I saved the model in ".h5" format
Thanks

**Comment by SumNeuron** [comment]
@gowthamkpr that linked comment seems irrelevant as that is for a different file format. 

I am also encountering a similar issue, which stems from an older issues that never got resolved that revolve around how device placement seems to be locked on export. 

1. [tf estimators imports are limited to no longer support `contrib` module](https://github.com/tensorflow/tensorflow/issues/23824)
2. [Relative device placement](https://github.com/tensorflow/tensorflow/issues/23834)
3. [No clear_device_placement](https://github.com/tensorflow/tensorflow/issues/23900)

```

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/backend.py in _get_session(op_input_list)
    453       else:
    454         _SESSION.session = session_module.Session(
--> 455             config=get_default_session_config())
    456     session = _SESSION.session
    457   return session

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py in __init__(self, target, graph, config)
   1583           protocol buffer with configuration options for the session.
   1584     """
-> 1585     super(Session, self).__init__(target, graph, config=config)
   1586     # NOTE(mrry): Create these on first `__enter__` to avoid a reference cycle.
   1587     self._default_graph_context_manager = None

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py in __init__(self, target, graph, config)
    697     try:
    698       # pylint: disable=protected-access
--> 699       self._session = tf_session.TF_NewSessionRef(self._graph._c_graph, opts) 
    700       # pylint: enable=protected-access
    701     finally:

InvalidArgumentError: device CUDA:0 not supported by XLA service
	while setting up XLA_GPU_JIT device number 0

```

notice line 699 where it creates a new session from the previous graph thereby having whatever devices the model was trained on being linked to the model.

**Comment by gowthamkpr** [comment]
@ydcjeff Can you please provide a **minimum** reproducible code to reproduce this issue. Thanks!

**Comment by ydcjeff** [comment]
@gowthamkpr 
Here! [Code](https://colab.research.google.com/github/ydcjeff/cvify/blob/master/main.ipynb) to reproduce
and then download the "main.h5" model to the local system which has python 3.7.4 and TF 2.0 CPU version installed.
You can try loading the "main.h5" model with `tf.keras.models.load_model()` in your local system with TF 2 CPU version.
It shows an error on mind. Error msg below
```py
OSError: SavedModel file does not exist at: main.h5/{saved_model.pbtxt|saved_model.pb}
```
Thanks!

**Comment by rmothukuru** [comment]
@ydcjeff,
Sorry for the delayed response. The issue is in the line, `model.save('model', save_format='tf')`.

As per this [Save_Format_Doc_String](https://github.com/tensorflow/tensorflow/blob/r2.0/tensorflow/python/keras/engine/network.py#L952-L954), `save_format='tf'` is currently disabled.

Working code is shown below:

```
model.save('model')
model = tf.keras.models.load_model('model')
```
 or 

```
model.save('test_model_tf.tf')
model = tf.keras.models.load_model('test_model_tf.tf')
```
Here is the [Gist](https://colab.sandbox.google.com/gist/rmothukuru/e8ca88a9882994ee9ae3ff08ee108b97/main.ipynb).

**Comment by rmothukuru** [comment]
@ydcjeff,
Can you please let us know if your issue is resolved. Thanks!

**Comment by ydcjeff** [comment]
@rmothukuru Thank you for your answer & sorry for late response!
It solved.
