### ISSUE TITLE
Cannot build libtensorflowlite_c.so -- problem with bazel build

### ISSUE THREAD

**Issue by lordalcol** [tensorflow/tensorflow#33513]
**System information**
- Windows 10 64-bit
- TensorFlow installed from (source or binary): source
- TensorFlow version: v2.0.0
- Python version: 3.7.4
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source): v1.0.0
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**

I am trying to build libtensorflowlite_c.so following the instructions at https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/experimental/examples/unity/TensorFlowLitePlugin/README.md but the build is failing the the following log.

**Any other info / logs**
First run log:
```
C:\Users\Lorenzo\Documents\tensorflow>bazel build -c opt --cxxopt=--std=c++11 \
INFO: Writing tracer profile to 'C:/users/lorenzo/_bazel_lorenzo/6xammqtc/command.profile.gz'
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=172
INFO: Options provided by the client:
  'build' options: --python_path=C:/Users/Lorenzo/AppData/Local/Programs/Python/Python37/python.exe
INFO: Reading rc options for 'build' from c:\users\lorenzo\documents\tensorflow\.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --java_toolchain=//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=//third_party/toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone --strategy=Genrule=standalone -c opt --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 --announce_rc --define=grpc_no_ares=true --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --config=v2
INFO: Found applicable config definition build:v2 in file c:\users\lorenzo\documents\tensorflow\.bazelrc: --define=tf_api_version=2
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/bazelbuild/bazel-toolchains/archive/92dd8a7a518a2fb7ba992d47c8b38299fe0be825.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
DEBUG: Rule 'io_bazel_rules_docker' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1556410077 -0400"
DEBUG: Call stack for the definition of repository 'io_bazel_rules_docker' which is a git_repository (rule definition at C:/users/lorenzo/_bazel_lorenzo/6xammqtc/external/bazel_tools/tools/build_defs/repo/git.bzl:195:18):
 - C:/users/lorenzo/_bazel_lorenzo/6xammqtc/external/bazel_toolchains/repositories/repositories.bzl:37:9
 - C:/users/lorenzo/documents/tensorflow/WORKSPACE:37:1
ERROR: Skipping '\': Bad target pattern '\': package names may contain A-Z, a-z, 0-9, or any of ' !"#$%&'()*+,-./;<=>?[]^_`{|}~' (most 7-bit ascii characters except 0-31, 127, ':', or '\')
WARNING: Target pattern parsing failed.
ERROR: Bad target pattern '\': package names may contain A-Z, a-z, 0-9, or any of ' !"#$%&'()*+,-./;<=>?[]^_`{|}~' (most 7-bit ascii characters except 0-31, 127, ':', or '\')
INFO: Elapsed time: 0.139s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```

Second run log:
```
C:\Users\Lorenzo\Documents\tensorflow>bazel build -c opt --cxxopt=--std=c++11 //tensorflow/lite/experimental/c:libtensorflowlite_c.so
INFO: Writing tracer profile to 'C:/users/lorenzo/_bazel_lorenzo/6xammqtc/command.profile.gz'
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=172
INFO: Options provided by the client:
  'build' options: --python_path=C:/Users/Lorenzo/AppData/Local/Programs/Python/Python37/python.exe
INFO: Reading rc options for 'build' from c:\users\lorenzo\documents\tensorflow\.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone --strategy=Genrule=standalone -c opt --announce_rc --define=grpc_no_ares=true --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --config=v2
INFO: Found applicable config definition build:v2 in file c:\users\lorenzo\documents\tensorflow\.bazelrc: --define=tf_api_version=2
INFO: Build options --cxxopt, --host_cxxopt, --host_java_toolchain, and 1 more have changed, discarding analysis cache.
INFO: Call stack for the definition of repository 'com_google_protobuf' which is a tf_http_archive (rule definition at C:/users/lorenzo/documents/tensorflow/third_party/repo.bzl:124:19):
 - C:/users/lorenzo/documents/tensorflow/tensorflow/workspace.bzl:432:5
 - C:/users/lorenzo/documents/tensorflow/WORKSPACE:19:1
INFO: Repository 'com_google_protobuf' used the following cache hits instead of downloading the corresponding file.
 * Hash 'b9e92f9af8819bbbc514e2902aec860415b70209f31dfc8c4fa72515a5df9d59' for https://storage.googleapis.com/mirror.tensorflow.org/github.com/protocolbuffers/protobuf/archive/310ba5ee72661c081129eb878c1bbcec936b20f0.tar.gz
If the definition of 'com_google_protobuf' was updated, verify that the hashes were also updated.
ERROR: An error occurred during the fetch of repository 'com_google_protobuf':
   Traceback (most recent call last):
        File "C:/users/lorenzo/documents/tensorflow/third_party/repo.bzl", line 104
                _apply_patch(ctx, ctx.attr.patch_file)
        File "C:/users/lorenzo/documents/tensorflow/third_party/repo.bzl", line 70, in _apply_patch
                _wrap_bash_cmd(ctx, patch_command)
        File "C:/users/lorenzo/documents/tensorflow/third_party/repo.bzl", line 28, in _wrap_bash_cmd
                fail("BAZEL_SH environment variable i...")
BAZEL_SH environment variable is not set
ERROR: Analysis of target '//tensorflow/lite/experimental/c:libtensorflowlite_c.so' failed; build aborted: no such package '@com_google_protobuf//': Traceback (most recent call last):
        File "C:/users/lorenzo/documents/tensorflow/third_party/repo.bzl", line 104
                _apply_patch(ctx, ctx.attr.patch_file)
        File "C:/users/lorenzo/documents/tensorflow/third_party/repo.bzl", line 70, in _apply_patch
                _wrap_bash_cmd(ctx, patch_command)
        File "C:/users/lorenzo/documents/tensorflow/third_party/repo.bzl", line 28, in _wrap_bash_cmd
                fail("BAZEL_SH environment variable i...")
BAZEL_SH environment variable is not set
INFO: Elapsed time: 4.906s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded, 0 targets configured)
    currently loading: tensorflow
```

**Comment by angerson** [comment]
@ravikyram, this looks like a TF Lite build issue. Can you re-triage to one of their experts, please?

@lordalcol This may not be the root of the problem, but I don't think that TF supports Bazel 1.0 yet. It may help to downgrade to the maximum supported version, which I think is currently 0.29.1.

**Comment by jdduke** [comment]
Also @lordalcol are you able to build any other targets in TensorFlow? The failure here looks more like a toolchain/dependency issue that is likely not specific to TensorFlow Lite.

**Comment by smaerdlatigid** [comment]
I have a similar issue. When I change the .so to a .dll and try to load it in unity after compiling with bazel I get an error

`
Failed to load 'Assets/TensorFlowLite/SDK/Plugins/libtensorflowlite_c.dll', expected x64 architecture, but was Unknown architecture. You must recompile your plugin for x64 architecture.`

**Comment by jdduke** [comment]
@smaerdlatigid can you share the exact build command that you used? And what version of Visual Studio is being used for compilation?

**Comment by smaerdlatigid** [comment]
The build command I am using: `bazel build -c opt --cxxopt=--std=c++11 \
  //tensorflow/lite/experimental/c:libtensorflowlite_c.so`

With visual studio v14.0 

I can compile the file into a `.so` file but I'm not sure how to compile it to a `.dll`

**Comment by amahendrakar** [comment]
> @lordalcol This may not be the root of the problem, but I don't think that TF supports Bazel 1.0 yet. It may help to downgrade to the maximum supported version, which I think is currently 0.29.1.

@lordalcol,
Any updates regarding this? Please take at @angerson's comment and let us know if you are still facing the same error. Thanks!

**Comment by jdduke** [comment]
Note, you should now be able to build using
```
bazel build -c opt //tensorflow/lite/c:tensorflowlite_c
```
and it should produce the shared library with a `.dll` suffix.
