### ISSUE TITLE
Using tf.data.Dataset.from_generator with tf.keras

### ISSUE THREAD

**Issue by sayakpaul** [tensorflow/tensorflow#33535]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colab
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below): 2.0.0
- Python version: 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**

I am referring to [this `tf.data` example](https://www.tensorflow.org/guide/data) where it has been shown how to wrap a `tf.keras.preprocessing.image.ImageDataGenerator` object with `tf.data.Dataset`. I am trying to supply this object to a Keras model and I am getting the following issue:

```
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-12-f2c206e4a521> in <module>()
      1 model.fit(ds, 
----> 2          steps_per_epoch=total_data//32)

11 frames
/usr/local/lib/python3.6/dist-packages/six.py in raise_from(value, from_value)

InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument:  TypeError: endswith first arg must be bytes or a tuple of bytes, not str
Traceback (most recent call last):

  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 464, in get_iterator
    return self._iterators[iterator_id]

KeyError: 2


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/script_ops.py", line 221, in __call__
    ret = func(*args)

  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 585, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 466, in get_iterator
    iterator = iter(self._generator(*self._args.pop(iterator_id)))

  File "/usr/local/lib/python3.6/dist-packages/keras_preprocessing/image/image_data_generator.py", line 540, in flow_from_directory
    interpolation=interpolation

  File "/usr/local/lib/python3.6/dist-packages/keras_preprocessing/image/directory_iterator.py", line 126, in __init__
    classes, filenames = res.get()

  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value

  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))

  File "/usr/local/lib/python3.6/dist-packages/keras_preprocessing/image/utils.py", line 216, in _list_valid_filenames_in_directory
    for root, fname in valid_files:

  File "/usr/local/lib/python3.6/dist-packages/keras_preprocessing/image/utils.py", line 172, in _iter_valid_files
    if fname.lower().endswith('.tiff'):

TypeError: endswith first arg must be bytes or a tuple of bytes, not str


	 [[{{node PyFunc}}]]
	 [[IteratorGetNext]]
	 [[IteratorGetNext/_4]]
  (1) Invalid argument:  TypeError: endswith first arg must be bytes or a tuple of bytes, not str
Traceback (most recent call last):

  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 464, in get_iterator
    return self._iterators[iterator_id]

KeyError: 2


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/script_ops.py", line 221, in __call__
    ret = func(*args)

  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 585, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 466, in get_iterator
    iterator = iter(self._generator(*self._args.pop(iterator_id)))

  File "/usr/local/lib/python3.6/dist-packages/keras_preprocessing/image/image_data_generator.py", line 540, in flow_from_directory
    interpolation=interpolation

  File "/usr/local/lib/python3.6/dist-packages/keras_preprocessing/image/directory_iterator.py", line 126, in __init__
    classes, filenames = res.get()

  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value

  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))

  File "/usr/local/lib/python3.6/dist-packages/keras_preprocessing/image/utils.py", line 216, in _list_valid_filenames_in_directory
    for root, fname in valid_files:

  File "/usr/local/lib/python3.6/dist-packages/keras_preprocessing/image/utils.py", line 172, in _iter_valid_files
    if fname.lower().endswith('.tiff'):

TypeError: endswith first arg must be bytes or a tuple of bytes, not str


	 [[{{node PyFunc}}]]
	 [[IteratorGetNext]]
0 successful operations.
0 derived errors ignored. [Op:__inference_distributed_function_1435]

Function call stack:
distributed_function -> distributed_function
```

**Describe the expected behavior**

How to use this type of `tf.data.Dataset` objects along with Keras?

**Code to reproduce the issue**
[Link](https://colab.research.google.com/drive/1evx-qKG1vPSUE5tfsFLgG8ukAEczJSkN) to the Colab notebook.

**Comment by sayakpaul** [comment]
Hi. The notebook is now updated with a worked example that:
- Shows the usage of tf.data.Dataset.from_generator along with Keras ImageDataGenerator for Keras models.
- Compares the performance between tf.data.Dataset.from_generator and ImageDtaGenerator.

**Comment by Rasinj** [comment]
Hi,

Just wanted to put this here that I had to use the lambda-trick referenced in the notebook with tf 2.1.0 to get the example at https://www.tensorflow.org/guide/data to work:

```
# Wrap the generator with tf.data
ds = tf.data.Dataset.from_generator(
    lambda: img_gen.flow_from_directory(flowers,
            target_size=(224, 224),
            shuffle=True),
    output_types=(tf.float32, tf.float32),
    output_shapes = ([None,224,224,3],[None,5])
)
```

**Comment by sayakpaul** [comment]
Yes, of course. I made a presentation to put together some common utility things: http://bit.ly/MLWeekend19.

**Comment by kuku1999** [comment]
> Hi. The notebook is now updated with a worked example that:
> 
>     * Shows the usage of tf.data.Dataset.from_generator along with Keras ImageDataGenerator for Keras models.
> 
>     * Compares the performance between tf.data.Dataset.from_generator and ImageDtaGenerator.

Hey Thanks a lot. Your notebook did a great help to me!!

**Comment by sayakpaul** [comment]
Glad you liked it. Here's a presentation that accompanies that code: bit.ly/MLWeekend19.

**Comment by bhaveshwadhwani** [comment]
Thanks Sayak for putting deck and code notebook here !!
