### ISSUE TITLE
[tflite] Support INT8 quantization for PACK with TFLITE_BUILTINS_INT8 OpsSet

### ISSUE THREAD

**Issue by dreamibor** [tensorflow/tensorflow#33572]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.14 
- Python version: 3.6

**Describe the current behavior**
Similar to the UNPACK node issue in https://github.com/tensorflow/tensorflow/issues/31902, the new TFLiteConverter post-training quantisation flow, as described in https://www.tensorflow.org/lite/performance/post_training_quantization#full_integer_quantization_of_weights_and_activations, does not support quantization of PACK/STACK operation when only integer operations are requested in the output model. When such conversion is attempted the following error is reported:
> RuntimeError: Quantization not yet supported for op: PACK

**Code to reproduce the issue**
For example, the script below:
```python
import tensorflow as tf
import numpy as np

def representative_dataset_gen():
	input_1 = np.ones([1, 10],dtype=np.float32)
	input_2 = np.ones([1, 10],dtype=np.float32)
	for _ in range(10):
		yield [input_1, input_2]

# tf Graph Input
foo = tf.compat.v1.placeholder("float32", [1, 10])
bar = tf.compat.v1.placeholder("float32", [1, 10])
out_stacked = tf.stack([foo, bar], axis=0)

with tf.compat.v1.Session() as sess:
	tf.io.write_graph(tf.compat.v1.get_default_graph(), '.','pack.pb', as_text=False)

input_name = ["Placeholder", "Placeholder_1"]
output_name = ["stack"]

tflite_model_name = "int8_pack.tflite"
converter = tf.lite.TFLiteConverter.from_frozen_graph("pack.pb", input_name, output_name)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.representative_dataset = representative_dataset_gen
tflite_model = converter.convert()
open(tflite_model_name, "wb").write(tflite_model)

# Load TFLite model and allocate tensors.
interpreter = tf.lite.Interpreter(tflite_model_name)
interpreter.allocate_tensors()

# Get input and output tensors.
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

# Test model on random input data.
input_shape = input_details[0]['shape']
input_data = np.array(np.random.random_sample(input_shape), dtype=np.float32)
interpreter.set_tensor(input_details[0]['index'], input_data)
interpreter.invoke()`
```
produces errors as follows:
```
2019-10-21 14:02:33.682706: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-10-21 14:02:33.708278: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3408000000 Hz
2019-10-21 14:02:33.708892: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x33f5a60 executing computations on platform Host. Devices:
2019-10-21 14:02:33.708924: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
2019-10-21 14:02:33.717107: I tensorflow/core/grappler/devices.cc:60] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0 (Note: TensorFlow was not compiled with CUDA support)
2019-10-21 14:02:33.717228: I tensorflow/core/grappler/clusters/single_machine.cc:359] Starting new session
INFO: Initialized TensorFlow Lite runtime.
Traceback (most recent call last):
  File "pack_example.py", line 26, in <module>
    tflite_model = converter.convert()
  File "/home/jaszha02/Work/venvs/audio/lib/python3.6/site-packages/tensorflow/lite/python/lite.py", line 908, in convert
    inference_output_type)
  File "/home/jaszha02/Work/venvs/audio/lib/python3.6/site-packages/tensorflow/lite/python/lite.py", line 200, in _calibrate_quantize_model
    inference_output_type, allow_float)
  File "/home/jaszha02/Work/venvs/audio/lib/python3.6/site-packages/tensorflow/lite/python/optimize/calibrator.py", line 78, in calibrate_and_quantize
    np.dtype(output_type.as_numpy_dtype()).num, allow_float)
  File "/home/jaszha02/Work/venvs/audio/lib/python3.6/site-packages/tensorflow/lite/python/optimize/tensorflow_lite_wrap_calibration_wrapper.py", line 115, in QuantizeModel
    return _tensorflow_lite_wrap_calibration_wrapper.CalibrationWrapper_QuantizeModel(self, input_py_type, output_py_type, allow_float)
RuntimeError: Quantization not yet supported for op: PACK
```
Both kTfLiteUInt8 and kTfLiteInt8 version of the PACK operator is already implemented in TFLite (see [pack.cc](https://github.com/tensorflow/tensorflow/blob/186e794d71c17b52deb52ace151ec5add8525f2c/tensorflow/lite/kernels/pack.cc)), so it should be straightforward to support PACK as well in the TFLite Converter.

**Comment by dreamibor** [comment]
Any updates?

**Comment by suharshs** [comment]
Hi, I have a CL in progress to fix this.

**Comment by tzekid** [comment]
Hey, I'm facing the same issue when converting `ssd_mobilenet_v1_fpn_coco` (see [model zoo](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf1_detection_zoo.md)) to quantized tflite.
Simple conversion to `float32` tflite works just fine.  

With TF 2 I can't even convert the model to tflite proper. 

Using `tensorflow_gpu` version 1.5.3 on google Colab, Ubuntu 18.04.  
Workflow is train network -> export_tflite_ssd_graph.py -> conversion script  

Any help would be much appreciated :pray: 

Conversion script looks like this: 
```python
import tensorflow as tf
import pathlib
import os
import cv2
from PIL import Image
import json
import numpy as np

frozen_model = './mobilenet_varroa_w_inputshape/frozen_inference_graph_00/tflite_graph.pb'
# TF 1
input_shapes = {'normalized_input_image_tensor':(1,896,896,3)}
input_arrays = ['normalized_input_image_tensor']
output_arrays = ['TFLite_Detection_PostProcess','TFLite_Detection_PostProcess:1','TFLite_Detection_PostProcess:2','TFLite_Detection_PostProcess:3']
converter = tf.lite.TFLiteConverter.from_frozen_graph(frozen_model, input_arrays, output_arrays, input_shapes)

converter.experimental_new_converter = False
converter.optimizations = [tf.lite.Optimize.DEFAULT]

def representative_dataset_gen():
    directory_images = "./rep_dataset/"
    for img in os.listdir(directory_images):
      tmp_img = Image.open(f"{directory_images}/{img}")
      tmp_img = np.array(tmp_img.getdata()).reshape((807, 807, 3)).astype(np.uint8)
      tmp_img = cv2.resize(tmp_img, (896, 896), interpolation=cv2.INTER_AREA)
      input_data = tmp_img.astype('float32')/255.0
      input_data = tf.expand_dims(input_data, 0)
      input_data = tf.convert_to_tensor(input_data, dtype=tf.float32)
      yield [input_data]

converter.representative_dataset = representative_dataset_gen
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.allow_custom_ops = True
converter.inference_input_type = tf.int8 
converter.inference_output_type = tf.int8 
tflite_quant_model = converter.convert() # crashes on this line
open("mobilenet_test.tflite", "wb").write(tflite_quant_model)
```
