### ISSUE TITLE
Cannot find the placeholder op that is an input to ReadVariableOp.

### ISSUE THREAD

**Issue by PolinaDemochkina** [tensorflow/tensorflow#33573]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux 4.15.0-62-generic
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: no
- TensorFlow installed from (source or binary): binary
- TensorFlow version: tensorflow-gpu 2.0.0
- Python version: 3.6
- Bazel version (if compiling from source): no
- GCC/Compiler version (if compiling from source): no
- CUDA/cuDNN version:  V10.0.130
- GPU model and memory: rtx 2060 6gb

**Describe the current behavior**
I'm unable to perform post-training quantization on my V2 model. 

**Code to reproduce the issue**
```
from tensorflow.keras import layers
from tensorflow.keras import optimizers
from tensorflow.keras.datasets import cifar100
import numpy as np
import tensorflow as tf
from tensorflow import keras
keras.backend.clear_session()
keras.backend.set_learning_phase(0)
from tensorflow.python.compiler.tensorrt import trt_convert as trt
import os

os.environ['CUDA_VISIBLE_DEVICES'] = '-1'

(x_train, y_train), (x_test, y_test) = cifar100.load_data()
x_train = np.float32(x_train)[:64*(x_train.shape[0]//64)]
x_train /= 255.0
i_shape = x_train[0].shape

inputs = layers.Input(i_shape)
base_model = keras.models.Sequential([
    layers.Conv2D(128, 3, padding='same', strides=(2, 2)),
    layers.BatchNormalization(),
    layers.LeakyReLU(0.2),

    layers.Conv2D(256, 3, padding='same', strides=(2, 2)),
    layers.BatchNormalization(),
    layers.LeakyReLU(0.2),

    layers.Conv2D(512*100, 3, padding='same', strides=(2, 2)),
    layers.BatchNormalization(),
    layers.LeakyReLU(0.2),
    layers.Flatten(),
    layers.Dense(5*128),
    layers.Reshape((5, 128)),
    layers.LSTM(128),
    layers.Flatten(),
])(inputs)

prediction = layers.Dense(100, activation='softmax')(base_model)
model = keras.Model(inputs=inputs, outputs=prediction)
optimizer = optimizers.Adam(0.00001)
model.compile(optimizer, 'categorical_crossentropy', metrics=['accuracy'])
print(model.summary())
saved_model_dir = os.getcwd()
output_directory = os.getcwd()
tf.saved_model.save(model, saved_model_dir)

# graph quantization
loaded = tf.saved_model.load(saved_model_dir)

params = trt.DEFAULT_TRT_CONVERSION_PARAMS._replace(
    precision_mode='FP16',
    is_dynamic_op=True,
    maximum_cached_engines=16)
converter = trt.TrtGraphConverterV2(
    input_saved_model_dir=saved_model_dir,
    input_saved_model_tags="serve",
    input_saved_model_signature_key="serving_default",
    conversion_params=params)
converter.convert()
saved_model_dir_trt = output_directory
converter.save(saved_model_dir_trt)
```

**Other info / logs**
```
Traceback (most recent call last):
  File "optimize_graphv2.py", line 33, in <module>
    main(args)
  File "optimize_graphv2.py", line 22, in main
    converter.convert()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/compiler/tensorrt/trt_convert.py", line 960, in convert
    frozen_func = convert_to_constants.convert_variables_to_constants_v2(func)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/convert_to_constants.py", line 479, in convert_variables_to_constants_v2
    raise ValueError("Cannot find the Placeholder op that is an input "
ValueError: Cannot find the Placeholder op that is an input to the ReadVariableOp.
```

**Comment by 1duo** [comment]
Got a similar issue. It seems converting the LSTM layer causes this `ValueError` error.

**Comment by luvwinnie** [comment]
any progress on this?

**Comment by audatic-henning** [comment]
I have the exact same issue, any insight into whats going on? A workaround / anything?

**Comment by Saduf2019** [comment]
@PolinaDemochkina 
I ran the shared code on tf nightly and do not face the value error, please refer to the [gist here](https://colab.research.google.com/gist/Saduf2019/f600487363649dc7aeaa1017345e7362/untitled356.ipynb)
