### ISSUE TITLE
TFLiteConverter StridedSlice Error for Transformer Example Notebook

### ISSUE THREAD

**Issue by mattc-eostar** [tensorflow/tensorflow#33616]
**System information**
- Linux Ubuntu 18.04.2
- Installed from binary
- TensorFlow version 2.0.0

**Provide the text output from tflite_convert**

```
---------------------------------------------------------------------------
ConverterError                            Traceback (most recent call last)
<ipython-input-82-0b556551beac> in <module>()
      3 
      4 converter = tf.lite.TFLiteConverter.from_concrete_functions([to_save])
----> 5 tflite_model = converter.convert()

~/anaconda3/envs/main/lib/python3.6/site-packages/tensorflow_core/lite/python/lite.py in convert(self)
    444         input_tensors=input_tensors,
    445         output_tensors=output_tensors,
--> 446         **converter_kwargs)
    447 
    448     if self._is_calibration_quantize():

~/anaconda3/envs/main/lib/python3.6/site-packages/tensorflow_core/lite/python/convert.py in toco_convert_impl(input_data, input_tensors, output_tensors, enable_mlir_converter, *args, **kwargs)
    447       input_data.SerializeToString(),
    448       debug_info_str=debug_info_str,
--> 449       enable_mlir_converter=enable_mlir_converter)
    450   return data
    451 

~/anaconda3/envs/main/lib/python3.6/site-packages/tensorflow_core/lite/python/convert.py in toco_convert_protos(model_flags_str, toco_flags_str, input_data_str, debug_info_str, enable_mlir_converter)
    198       stdout = _try_convert_to_unicode(stdout)
    199       stderr = _try_convert_to_unicode(stderr)
--> 200       raise ConverterError("See console for info.\n%s\n%s\n" % (stdout, stderr))
    201   finally:
    202     # Must manually cleanup files.

ConverterError: See console for info.
2019-10-22 12:59:50.304931: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 915 operators, 1487 arrays (0 quantized)
2019-10-22 12:59:50.337611: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 915 operators, 1487 arrays (0 quantized)
2019-10-22 12:59:50.397450: F tensorflow/lite/toco/graph_transformations/resolve_strided_slice_attributes.cc:95] Check failed: start_indices_size <= num_input_axes (4 vs. 2)StridedSlice op requires no more than 2 start indices
Fatal Python error: Aborted

Current thread 0x00007f2d4bb1e740 (most recent call first):
  File "/home/mattc/anaconda3/envs/main/lib/python3.6/site-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 52 in execute
  File "/home/mattc/anaconda3/envs/main/lib/python3.6/site-packages/absl/app.py", line 251 in _run_main
  File "/home/mattc/anaconda3/envs/main/lib/python3.6/site-packages/absl/app.py", line 300 in run
  File "/home/mattc/anaconda3/envs/main/lib/python3.6/site-packages/tensorflow_core/python/platform/app.py", line 40 in run
  File "/home/mattc/anaconda3/envs/main/lib/python3.6/site-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 89 in main
  File "/home/mattc/anaconda3/envs/main/bin/toco_from_protos", line 10 in <module>
Aborted (core dumped)
```

**Any other info / logs**

I am following this notebook: https://www.tensorflow.org/tutorials/text/transformer
I am interested in doing NMT on an Android device with TFLite. The NMT Attention notebook uses an LSTM which is not supported yet for TF Lite conversion so I am looking into this approach that only uses Attention, Embeddings, and Dense layers in hope that it is convertible. 

I haven't edited the code from that notebook at all, but created a new inference concrete function and am trying to convert it. I am getting this vague error about the StridedSlice op.

Looking for some guidance on what I can do from here.

```python
tf.random.set_seed(1234)

eval_step_signature = [
    tf.TensorSpec(shape=(BATCH_SIZE, 64), dtype=tf.int64),
    tf.TensorSpec(shape=(BATCH_SIZE, 26), dtype=tf.int64),
]

@tf.function(input_signature=eval_step_signature)
def eval_step(inp, tar):

    enc_padding_mask, combined_mask, dec_padding_mask = create_masks(inp, tar)
    
    predictions, _ = transformer(inp, tar, 
                                 True, 
                                 enc_padding_mask, 
                                 combined_mask, 
                                 dec_padding_mask)
    return predictions

ckpt.f = eval_step
to_save = ckpt.f.get_concrete_function()

converter = tf.lite.TFLiteConverter.from_concrete_functions([to_save])
tflite_model = converter.convert()
```

Thank you!

**Comment by renjithamadeus** [comment]
I have also encountered the same problem. Looks like it is from create_padding_mask function.

**Comment by jaeyoo** [comment]
Hi @mattc-eostar ,

I could resolve the issue with:
```python
ckpt.f = eval_step
to_save = ckpt.f.get_concrete_function()

converter = tf.lite.TFLiteConverter.from_concrete_functions([to_save])
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,
                                       tf.lite.OpsSet.SELECT_TF_OPS]
tflite_model = converter.convert()
```
Thank you.

**Comment by ravikyram** [comment]
@mattc-eostar 

Can you please check and confirm whether your issue was resolved by adding below 2 lines of code before converting

```
converter = tf.lite.TFLiteConverter.from_concrete_functions([to_save])
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,
                                       tf.lite.OpsSet.SELECT_TF_OPS]
```
Please, close this thread if your issue was resolved.Thanks!
