### ISSUE TITLE
Unable to execute python program  with Keras / Tensorflow 

### ISSUE THREAD

**Issue by Belgrath1900** [tensorflow/tensorflow#33619]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Windows
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
PC
- TensorFlow installed from (source or binary):
Keras                2.3.1
Keras-Applications   1.0.8
Keras-Preprocessing  1.1.0
tensorboard          2.0.0
tensorflow           2.0.0
tensorflow-estimator 2.0.1
Installed Python version from pip within Visual Studio
- TensorFlow version:  above
- Python version:   3.7.4 64-bit
- Installed using virtualenv? pip? conda?:   installed via pip
- Bazel version (if compiling from source):    n/a
- GCC/Compiler version (if compiling from source):  n/a
- CUDA/cuDNN version:   do not have Cuda installed, want to run this on the CPU as my GPA is a Nvid GTS-250
- GPU model and memory:
Nvid GTS-250 @ 2 cards
CPU is an i7 Intel 930 @ 2.8GHz, Quad Core
System has 12G of RAM

**Describe the problem**
I am able to import keras and numpy into my python program, however when I attempt to run the program I see the following error...

H:\Python\Projects\Machine_Learning>C:/Users/Userid/AppData/Local/Programs/Python/Python37/python.exe "h:/Python/Projects/Machine_Learning/44 - first_deep_learning_example.py"
Using TensorFlow backend.
Traceback (most recent call last):
  File "C:\Users\Userid\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Userid\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Userid\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Userid\AppData\Local\Programs\Python\Python37\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Userid\AppData\Local\Programs\Python\Python37\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed with error code 3221225501

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "h:/Python/Projects/Machine_Learning/44 - first_deep_learning_example.py", line 2, in <module>
    from keras.models import Sequential
  File "C:\Users\Userid\AppData\Local\Programs\Python\Python37\lib\site-packages\keras\__init__.py", line 3, in <module>
    from . import utils
  File "C:\Users\Userid\AppData\Local\Programs\Python\Python37\lib\site-packages\keras\utils\__init__.py", line 6, in <module>
    from . import conv_utils
  File "C:\Users\Userid\AppData\Local\Programs\Python\Python37\lib\site-packages\keras\utils\conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "C:\Users\Userid\AppData\Local\Programs\Python\Python37\lib\site-packages\keras\backend\__init__.py", line 1, in <module>
    from .load_backend import epsilon
  File "C:\Users\Userid\AppData\Local\Programs\Python\Python37\lib\site-packages\keras\backend\load_backend.py", line 90, in <module>
    from .tensorflow_backend import *
  File "C:\Users\Userid\AppData\Local\Programs\Python\Python37\lib\site-packages\keras\backend\tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf
  File "C:\Users\Userid\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\__init__.py", line 98, in <module>
    from tensorflow_core import *
  File "C:\Users\Userid\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\Userid\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\Users\Userid\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "C:\Users\Userid\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\Userid\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Userid\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Userid\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Userid\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Userid\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Userid\AppData\Local\Programs\Python\Python37\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Userid\AppData\Local\Programs\Python\Python37\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed with error code 3221225501

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by Belgrath1900** [comment]
perhaps my CPU doesn't support AVX?  apparently everything after tensorFlow 1.6 requires AVX.  I tried installing an older version with:

H:\Python\Projects\Machine_Learning>pip3 install tensorflow==1.5
ERROR: Could not find a version that satisfies the requirement tensorflow==1.5 (from versions: 1.13.0rc1, 1.13.0rc2, 1.13.1, 1.13.2, 1.14.0rc0, 1.14.0rc1, 1.14.0, 1.15.0rc0, 1.15.0rc1, 1.15.0rc2, 1.15.0rc3, 1.15.0, 2.0.0a0, 2.0.0b0, 2.0.0b1, 2.0.0rc0, 2.0.0rc1, 2.0.0rc2, 2.0.0)
ERROR: No matching distribution found for tensorflow==1.5

I'm also reading some posts that I should perhaps run Anaconda which I'm not really familiar with...

**Comment by Belgrath1900** [comment]
the version of tensorFlow that I have installed should be the CPU version.  As my video card is a GTS250, that would require CUDA and I don't think that it is supported on my GTS250 cards...

https://www.nvidia.com/en-us/geforce/forums/game-ready-drivers/13/227869/geforce-gts-250-cuda-drivers/

**Comment by gowthamkpr** [comment]
@Belgrath1900  The newest Tensorflow requires AVX2 support from the CPU. You can also refer to the following [link](https://devtalk.nvidia.com/default/topic/1057009/error-code-3221225501-when-trying-to-run-tensorflow/).

**Comment by Belgrath1900** [comment]
Thanks @gowthamkpr, is there a version of TensorFlow that I could use with either my GPU or CPU or is this machine about to be tossed out?

**Comment by gowthamkpr** [comment]
You can build tensorflow from source. Please refer to the following [link](url).

**Comment by Belgrath1900** [comment]
> You can build tensorflow from source. Please refer to the following [link](url).

I assume that this was the link:  https://www.tensorflow.org/install/source_windows

So by building my own version on this PC, it'll bypass any AVX support?  I see further on down in the above link that it talks about Python version 3.5.x is the issue my currently install python 3.7.. I've never compiled from source before so this is a bit of a new adventure :)

**Comment by gowthamkpr** [comment]
Yes @Belgrath1900 I am gonna close this issue as of now and if you face any issues while building Tensorflow from source, open a new one.
