### ISSUE TITLE
dnn_autoencoder_iris.py example error

### ISSUE THREAD

**Issue by rmasad** [tensorflow/tensorflow#3364]
The example in skflow folder gives this error:
```
Traceback (most recent call last):
  File "/home/rmasad/test/dnn_autoencoder_iris.py", line 33, in <module>
    transformed = autoencoder.fit_transform(iris.data)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/base.py", line 403, in fit_transform
    return self.fit(x, y, monitor=None, logdir=None).transform(x)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/base.py", line 394, in transform
    x, axis=1, batch_size=None))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/base.py", line 237, in predict
    return self._predict(x, axis=axis, batch_size=batch_size)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/base.py", line 211, in _predict
    feed_fn=predict_data_feeder.get_feed_dict_fn())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 566, in _infer_model
    predictions = self._get_predict_ops(features)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 720, in _get_predict_ops
    self._targets_info)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/tensor_signature.py", line 133, in create_placeholders_from_signatures
    return signatures.get_placeholder()
AttributeError: 'NoneType' object has no attribute 'get_placeholder'
```

**Comment by concretevitamin** [comment]
@wicke: assigning to you to redirect.  Who is the owner of the `tensorflow/examples/skflow` directory?

**Comment by martinwicke** [comment]
Sorry, the autoencoder example is terribly out of date and we haven't deprecated it properly. We need to clean up the examples. This should be converted to use a custom `Estimator` until we add a new DNNAutoencoder.

**Comment by martinwicke** [comment]
@sandersk has a change in progress which will fix this.
