### ISSUE TITLE
Can not build debug wheel due to OverflowError: Size does not fit in an unsigned int

### ISSUE THREAD

**Issue by yunxiangz** [tensorflow/tensorflow#33663]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): Source
- TensorFlow version: 1.13
- Python version: 3.5
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source): 0.19
- GCC/Compiler version (if compiling from source): 4.8
- CUDA/cuDNN version: 10.0
- GPU model and memory: 

**Describe the problem**

I cannot create the wheel file for a TensorFlow build with debug symbols. According to #25026, it seems that the target file is too big for pip to generate. I have to debug the TensorFlow inner c++ code, is there anyone know the solution for this problem plz?

command: 
bazel build --spawn_strategy=standalone --verbose_failures --config=cuda --copt="-fPIC" --copt="-DNDEBUG" --local_resources 11048,2.0,2.0 -c dbg --copt -g //tensorflow/tools/pip_package:build_pip_package
and then
./bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg

output:
data = co.compress(data) + co.flush()
OverflowError: Size does not fit in an unsigned int

Traceback (most recent call last):
  File "setup.py", line 294, in <module>
    keywords='tensorflow tensor machine learning',
  File "/usr/local/lib/python3.5/dist-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.5/dist-packages/wheel/bdist_wheel.py", line 250, in run
    wf.write_files(archive_root)
  File "/usr/local/lib/python3.5/dist-packages/wheel/wheelfile.py", line 122, in write_files
    self.write(path, arcname)
  File "/usr/local/lib/python3.5/dist-packages/wheel/wheelfile.py", line 136, in write
    self.writestr(zinfo, data, compress_type)
  File "/usr/local/lib/python3.5/dist-packages/wheel/wheelfile.py", line 139, in writestr
    ZipFile.writestr(self, zinfo_or_arcname, bytes, compress_type)
  File "/usr/lib/python3.5/zipfile.py", line 1573, in writestr
    data = co.compress(data) + co.flush()
OverflowError: Size does not fit in an unsigned int

**Comment by yunxiangz** [comment]
This might be the problem between Python 3.5 and CUDA. 
I upgrade the Python to 3.7 and downgrade CUDA to 9 (cuDNN to 7), then the error was gone.

**Comment by zgsbughammer** [comment]
upgrading your python version to 3.7+ will do
