### ISSUE TITLE
[tf2.0] LSTMCell get_initial_state went wrong when batch_size is a Tensor

### ISSUE THREAD

**Issue by Yablon** [tensorflow/tensorflow#33673]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 
Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: 
Not Clear
- TensorFlow installed from (source or binary):
binary
- TensorFlow version (use command below):
2.0.0
- Python version:
3.6.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
10.0
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
LSTMCell get_initial_state went wrong when batch_size is a Tensor
**Describe the expected behavior**
I think it should gives a good result
**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
import tensorflow as tf

a = tf.keras.Input(shape=(10,), batch_size=2)
batch_size = tf.shape(a)[0]
cell = tf.keras.layers.LSTMCell(units=1024)
b = cell.get_initial_state(batch_size=batch_size, dtype=tf.float32)

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/array_ops.py", line 2355, in zeros
    tensor_shape.TensorShape(shape))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/tensor_shape.py", line 776, in __init__
    self._dims = [as_dimension(d) for d in dims_iter]
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/tensor_shape.py", line 776, in <listcomp>
    self._dims = [as_dimension(d) for d in dims_iter]
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/tensor_shape.py", line 718, in as_dimension
    return Dimension(value)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/tensor_shape.py", line 193, in __init__
    self._value = int(value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'Tensor'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 1610, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Duplicate node name in graph: 'zeros/packed'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test7.py", line 10, in <module>
    b = cell.get_initial_state(batch_size=batch_size, dtype=tf.float32)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/layers/recurrent.py", line 2314, in get_initial_state
    self, inputs, batch_size, dtype))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/layers/recurrent.py", line 2752, in _generate_zero_filled_state_for_cell
    return _generate_zero_filled_state(batch_size, cell.state_size, dtype)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/layers/recurrent.py", line 2768, in _generate_zero_filled_state
    return nest.map_structure(create_zeros, state_size)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/util/nest.py", line 535, in map_structure
    structure[0], [func(*x) for x in entries],
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/util/nest.py", line 535, in <listcomp>
    structure[0], [func(*x) for x in entries],
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/layers/recurrent.py", line 2765, in create_zeros
    return array_ops.zeros(init_state_size, dtype=dtype)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/array_ops.py", line 2358, in zeros
    shape = ops.convert_to_tensor(shape, dtype=dtypes.int32)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 1184, in convert_to_tensor
    return convert_to_tensor_v2(value, dtype, preferred_dtype, name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 1242, in convert_to_tensor_v2
    as_ref=False)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 1296, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/array_ops.py", line 1278, in _autopacking_conversion_function
    return _autopacking_helper(v, dtype, name or "packed")
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/array_ops.py", line 1214, in _autopacking_helper
    return gen_array_ops.pack(elems_as_tensors, name=scope)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/gen_array_ops.py", line 6304, in pack
    "Pack", values=values, axis=axis, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/op_def_library.py", line 793, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/func_graph.py", line 548, in create_op
    compute_device)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 3429, in _create_op_internal
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 1773, in __init__
    control_input_ops)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 1613, in _create_c_op
    raise ValueError(str(e))
ValueError: Duplicate node name in graph: 'zeros/packed'

**Comment by gadagashwini** [comment]
I could reproduce the issue with TF 2.0 on colab. Please see colab [gist](https://colab.sandbox.google.com/gist/gadagashwini/bb4f6ac37f07b5246b6eeabe8cdabf10/untitled226.ipynb). Thanks!

**Comment by jvishnuvardhan** [comment]
@Yablon Why do you want to pass batch_size as a tensor? obviously it will throw an error as it was not expecting a tensor. Please let us know any reason behind that change? Thanks!

**Comment by Yablon** [comment]
@jvishnuvardhan my code is a little bit complicated and I try to simplify it like the following codes. 

I use the official tensorflow_addons module in my code, which is in the original tf.contrib module.

I have to get the initial input for the decoder, and I want to use the batch_size from the input data, because I don't want a fixed batch in my training.

My code goes wrong and I spend a day to find the lstmcell problem.

Does I use tf2 in a wrong way ? how can I make the following codes work ? 

Thank you for spending time on my issue. You are very appreciated, and I really want to benefit from the tensorflow 2.0. Hope you give me some advices one that issue.

`
from tensorflow import tf
from tensorflow_addons import seq2seq

from utils import SomeConvolutions, SomeRNNs

class Example(tf.keras.Model):
  def __init__(self, hparams):
    # hparams parameters saved here
    self.hparams = hparams
    # embedding
    self.embedding = tf.keras.layers.Embedding(hparams.symbol_len, hparams.embedding_size, mask_zero=True)
    # self defined convolution layer
    self.convolutions = SomeConvolutions(hparams)
    # self defined rnns layer
    self.rnns = SomeRNNs(hparams)
    # The official tensorflow_addons class.
    self.sampler = seq2seq.TrainingSampler()
    # The official tensorflow_addons class
    self.attention_mechanism = seq2seq.BahdanauAttention(hparams.units)
    # the official keras cell
    self.cell = tf.keras.LSTMCell(hparams.units)
    # official class that wraps a cell and attention mechanism as a cell
    self.attention_wrapper = seq2seq.AttentionWrapper(self.cell, self.attention_mechanism, output_attention=True)
    # the official decoder
    self.decoder = seq2seq.BasicDecoder(self.attention_wrapper, self.sampler)

  def call(self, inputs):
    # compute embedding
    embedded = self.embedding(inputs)
    # compute memories for attention
    memories = self.rnns(self.convolutions(embedded))
    # setup memories
    self.attention_mechanism(memories, setup_memory=True)
    # get batch_size and input_shape from input, to form initial_input and initial_state
    batch_size = tf.shape(embedded)[0]
    input_shape = [batch_size, self.hparams.input_dim]

    # get initial_state. In decoder wrapper, self.cell.get_initial_state is called, where my issue occurs
    initial_state = self.decoder_wrapper.get_initial_state(batch_size=batch_size, dtype=tf.float32)
    initial_input = tf.fill(input_shape, self.hparams.init_value)
    # calculate seq2seq result
    (output, _), _, _ = self.decoder(initial_input, initial_state=initial_state)
    return output

model = Example(hparams=hparams)
datasef = tf.data.Dataset(...)
model.compile(...)
model.fit(dataset, epochs=..., callbacks=...)

`

**Comment by jvishnuvardhan** [comment]
@Yablon Can you create a standalone code with some data? Thanks!

**Comment by Yablon** [comment]
@jvishnuvardhan Thank you for your reply ! 
After clearing my redundant codes, I think the problem is solved for now. I can train my model since 12 hours ago. I think TF2.0 is better to develop and debug than TF1.x.
Sorry for the interuption.

**Comment by niranjan8129** [comment]
lstm_cell =tf.keras.layers.LSTM(units=hidden_unit)
lstm_cell = tf.nn.RNNCellDropoutWrapper(lstm_cell, output_keep_prob=self.dropout_keep_prob)
self._initial_state = lstm_cell.get_initial_state(128, tf.float32)

Got  ERROR
**********************
ValueError: slice index 0 of dimension 0 out of bounds. for 'strided_slice' (op: 'StridedSlice') with input shapes: [0], [1], [1], [1] and with computed input tensors: input[1] = <0>, input[2] = <1>, input[3] = <1>.
may I know why I am getting this error?

**Comment by jvishnuvardhan** [comment]
@niranjan8129 Please open a new issue with details of issue and a simple standalone code to reproduce the issue. thanks!
