### ISSUE TITLE
TFLite Raspberry Pi object detection example code does not work with tensorflow.lite.python.interpreter, only works with tflite_runtime.interpreter

### ISSUE THREAD

**Issue by EdjeElectronics** [tensorflow/tensorflow#33671]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Raspbian Buster
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Raspberry Pi 4 4GB
- TensorFlow installed from (source or binary): Binary (pip3 install tensorflow)
- TensorFlow version (use command below): v1.12.1-3892-g127aae0 1.13.1
- Python version: 3.7.3
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

**Describe the behavior**
I am following the TFLite object detection on Raspberry Pi guide (https://github.com/tensorflow/examples/tree/master/lite/examples/object_detection/raspberry_pi) using a Raspberry Pi 4 4GB model. The guide says to download and install the tflite_runtime from the [Python quickstart page](https://www.tensorflow.org/lite/guide/python). However, I tried using it with my existing installation of TensorFlow since I already have it installed on my Pi 4, and the script exits with the error shown below.

It also doesn't work if I have regular TensorFlow and the tflite_runtime package installed at the same time. It does work if I uninstall TensorFlow using `pip3 uninstall tensorflow` and then install the tflite_runtime package. 

**Describe the expected behavior**
It would be nice if the object detection example code worked without having to remove my existing TensorFlow install.

**Code to reproduce the issue**
I used the example code given [here](https://github.com/tensorflow/examples/blob/master/lite/examples/object_detection/raspberry_pi/detect_picamera.py). When trying to use regular TensorFlow (rather than just the tflite_runtime package), I changed line 33 from `from tflite_runtime.interpreter import Interpreter` to `from tensorflow.lite.python.interpreter import Interpreter`.

I called the script using:
```
python3 detect_picamera.py \
  --model /tmp/detect.tflite \
  --labels /tmp/coco_labels.txt
```

**Other info / logs**
Traceback for the error I am getting:

Traceback (most recent call last):
  File "TFLite_detection_picamera.py", line 113, in <module>
    interpreter = Interpreter(model_path=PATH_TO_CKPT)
  File "/home/pi/.local/lib/python3.7/site-packages/tflite_runtime/interpreter.py", line 205, in __init__
    _interpreter_wrapper.InterpreterWrapper_CreateWrapperCPPFromFile(
  File "/home/pi/.local/lib/python3.7/site-packages/tensorflow_core/python/util/lazy_loader.py", line 62, in __getattr__
    module = self._load()
  File "/home/pi/.local/lib/python3.7/site-packages/tensorflow_core/python/util/lazy_loader.py", line 45, in _load
    module = importlib.import_module(self.__name__)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/pi/.local/lib/python3.7/site-packages/tensorflow_core/lite/python/interpreter_wrapper/tensorflow_wrap_interpreter_wrapper.py", line 28, in <module>
    _tensorflow_wrap_interpreter_wrapper = swig_import_helper()
  File "/home/pi/.local/lib/python3.7/site-packages/tensorflow_core/lite/python/interpreter_wrapper/tensorflow_wrap_interpreter_wrapper.py", line 24, in swig_import_helper
    _mod = imp.load_module('_tensorflow_wrap_interpreter_wrapper', fp, pathname, description)
  File "/usr/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 670, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 583, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1043, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: /home/pi/.local/lib/python3.7/site-packages/tensorflow_core/lite/python/interpreter_wrapper/_tensorflow_wrap_interpreter_wrapper.so: undefined symbol: _ZN6tflite12tensor_utils24NeonVectorScalarMultiplyEPKaifPf

**Comment by EdjeElectronics** [comment]
Update: I just tested this with TensorFlow v2.0 (downloaded and installed from https://github.com/lhelontra/tensorflow-on-arm/releases), and everything worked fine.

**Comment by LatinAmericanProgramer** [comment]
Thank you @EdjeElectronics, I had exactly the same issue and this solution also worked for me.

> Update: I just tested this with TensorFlow v2.0 (downloaded and installed from https://github.com/lhelontra/tensorflow-on-arm/releases), and everything worked fine.

**Comment by EdjeElectronics** [comment]
@petewarden will this get resolved any time soon? It looks like users are having this same error with TF v1.14, which is the latest version easily available for Raspbian Stretch (which uses Python 3.5 by default).

Seems there are two solutions:

1. Add wheel files for TF v2.0 on piwheels.org so users can easily install TF v2.0
2. Resolve the issue with TF v1.13 / TF v1.14.

A couple people following my guide for TF Lite on Raspberry Pi are encountering the same problem: https://github.com/EdjeElectronics/TensorFlow-Lite-Object-Detection-on-Android-and-Raspberry-Pi/issues/13

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
