### ISSUE TITLE
Unsure as to compile options for Intel i7 930, Bloomfield CPU for when rebuilding Tensorflow from source

### ISSUE THREAD

**Issue by Belgrath1900** [tensorflow/tensorflow#33687]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Windows 7

- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
PC

- TensorFlow installed from (source or binary):
Trying to recompile TensorFlow 2.0 for my older machine without AVX support

- TensorFlow version: 2
- Python version:  3.7
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): 0.28.1
- GCC/Compiler version (if compiling from source): latest
- CUDA/cuDNN version:  n/a I have an older GTS-250 card that does not support
- GPU model and memory:
CPU is an Intel i7 930 which I believe is a Bloomfield model

**Describe the problem**
I'm at the step during the rebuild that is asking me for optimization flags.  I want to make sure that I am picking the correct ones with my CPU and GPU.

some of the previous options were:

Found possible Python library paths:
  C:\Users\Bill\AppData\Local\Programs\Python\Python37\lib\site-packages
Please input the desired Python library path to use.  Default is [C:\Users\Bill\AppData\Local\Programs\Python\Python37\lib\site-packages]

Do you wish to build TensorFlow with XLA JIT support? [y/N]: y
XLA JIT support will be enabled for TensorFlow.

Do you wish to build TensorFlow with ROCm support? [y/N]: N
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: N
No CUDA support will be enabled for TensorFlow.

Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is /arch:AVX]:

So I'm at this point and I'm not sure if I should use --config-opt or something like -march core2 I checked to see if there was a -march bloomfield but no option exists... 

Would someone be able to spell out the exact options that I should be using.  Many thanks ahead of time!

**Provide the exact sequence of commands / steps that you executed before running into the problem**
listed above

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by Belgrath1900** [comment]
maybe just:
-march=nehalem    ?

or should it be:
--config=opt   -march=nehalem

**Comment by Belgrath1900** [comment]
I pushed forward with the compile and ended up seeing the following errors...

H:\Python\TensorFlowCompile\tensorflow>python ./configure.py
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
You have bazel 0.29.1 installed.
Please specify the location of python. [Default is C:\Users\Zeek\AppData\Local\Programs\Python\Python37\python.exe]:


Found possible Python library paths:
  C:\Users\Zeek\AppData\Local\Programs\Python\Python37\lib\site-packages
Please input the desired Python library path to use.  Default is [C:\Users\Zeek\AppData\Local\Programs\Python\Python37\lib\site-packages]

Do you wish to build TensorFlow with XLA JIT support? [y/N]: N
No XLA JIT support will be enabled for TensorFlow.

Do you wish to build TensorFlow with ROCm support? [y/N]: N
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: N
No CUDA support will be enabled for TensorFlow.

Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is /arch:AVX]: --config=v2 -march=nehalem


Would you like to override eigen strong inline for some C++ compilation to reduce the compilation time? [Y/n]: Y
Eigen strong inline overridden.

Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See .bazelrc for more details.
        --config=mkl            # Build with MKL support.
        --config=monolithic     # Config for mostly static monolithic build.
        --config=ngraph         # Build with Intel nGraph support.
        --config=numa           # Build with NUMA support.
        --config=dynamic_kernels        # (Experimental) Build kernels into separate shared objects.
        --config=v2             # Build TensorFlow 2.x instead of 1.x.
Preconfigured Bazel build configs to DISABLE default on features:
        --config=noaws          # Disable AWS S3 filesystem support.
        --config=nogcp          # Disable GCP support.
        --config=nohdfs         # Disable HDFS support.
        --config=nonccl         # Disable NVIDIA NCCL support.

H:\Python\TensorFlowCompile\tensorflow>bazel build //tensorflow/tools/pip_package:build_pip_package
Starting local Bazel server and connecting to it...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=0 --terminal_columns=269
INFO: Options provided by the client:
  'build' options: --python_path=C:/Users/Zeek/AppData/Local/Programs/Python/Python37/python.exe
INFO: Reading rc options for 'build' from h:\python\tensorflowcompile\tensorflow\.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --java_toolchain=//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=//third_party/toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone --strategy=Genrule=standalone -c opt --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 --announce_rc --define=grpc_no_ares=true --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --config=v2
INFO: Reading rc options for 'build' from h:\python\tensorflowcompile\tensorflow\.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=C:/Users/Zeek/AppData/Local/Programs/Python/Python37/python.exe --action_env PYTHON_LIB_PATH=C:/Users/Zeek/AppData/Local/Programs/Python/Python37/lib/site-packages --python_path=C:/Users/Zeek/AppData/Local/Programs/Python/Python37/python.exe --config monolithic --copt=-w --host_copt=-w --copt=-DWIN32_LEAN_AND_MEAN --host_copt=-DWIN32_LEAN_AND_MEAN --copt=-DNOGDI --host_copt=-DNOGDI --verbose_failures --distinct_host_configuration=false --define=override_eigen_strong_inline=true --action_env TF_CONFIGURE_IOS=0
INFO: Found applicable config definition build:v2 in file h:\python\tensorflowcompile\tensorflow\.bazelrc: --define=tf_api_version=2
INFO: Found applicable config definition build:monolithic in file h:\python\tensorflowcompile\tensorflow\.bazelrc: --define framework_shared_object=false
INFO: Found applicable config definition build:monolithic in file h:\python\tensorflowcompile\tensorflow\.bazelrc: --define framework_shared_object=false
Loading:
Loading: 0 packages loaded
Loading: 0 packages loaded
Analyzing: target //tensorflow/tools/pip_package:build_pip_package (1 packages loaded, 0 targets configured)
Analyzing: target //tensorflow/tools/pip_package:build_pip_package (6 packages loaded, 18 targets configured)
Analyzing: target //tensorflow/tools/pip_package:build_pip_package (6 packages loaded, 18 targets configured)
Analyzing: target //tensorflow/tools/pip_package:build_pip_package (6 packages loaded, 18 targets configured)
INFO: Call stack for the definition of repository 'com_google_protobuf' which is a tf_http_archive (rule definition at H:/python/tensorflowcompile/tensorflow/third_party/repo.bzl:121:19):
 - H:/python/tensorflowcompile/tensorflow/tensorflow/workspace.bzl:434:5
 - H:/python/tensorflowcompile/tensorflow/WORKSPACE:19:1
Analyzing: target //tensorflow/tools/pip_package:build_pip_package (6 packages loaded, 18 targets configured)
INFO: Repository 'com_google_protobuf' used the following cache hits instead of downloading the corresponding file.
 * Hash 'b9e92f9af8819bbbc514e2902aec860415b70209f31dfc8c4fa72515a5df9d59' for https://storage.googleapis.com/mirror.tensorflow.org/github.com/protocolbuffers/protobuf/archive/310ba5ee72661c081129eb878c1bbcec936b20f0.tar.gz
If the definition of 'com_google_protobuf' was updated, verify that the hashes were also updated.
ERROR: An error occurred during the fetch of repository 'com_google_protobuf':
   Traceback (most recent call last):
        File "H:/python/tensorflowcompile/tensorflow/third_party/repo.bzl", line 101
                _apply_patch(ctx, ctx.attr.patch_file)
        File "H:/python/tensorflowcompile/tensorflow/third_party/repo.bzl", line 68, in _apply_patch
                _execute_and_check_ret_code(ctx, cmd)
        File "H:/python/tensorflowcompile/tensorflow/third_party/repo.bzl", line 52, in _execute_and_check_ret_code
                fail("Non-zero return code({1}) when ...))
Non-zero return code(127) when executing 'C:\msys64\usr\bin\bash.exe -l -c "patch" "-p1" "-d" "C:/users/Zeek/_bazel_Zeek/hfhzrtpt/external/com_google_protobuf" "-i" "H:/python/tensorflowcompile/tensorflow/third_party/protobuf/protobuf.patch"':
Stdout:
Stderr: /usr/bin/bash: patch: command not found
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: no such package '@com_google_protobuf//': Traceback (most recent call last):
        File "H:/python/tensorflowcompile/tensorflow/third_party/repo.bzl", line 101
                _apply_patch(ctx, ctx.attr.patch_file)
        File "H:/python/tensorflowcompile/tensorflow/third_party/repo.bzl", line 68, in _apply_patch
                _execute_and_check_ret_code(ctx, cmd)
        File "H:/python/tensorflowcompile/tensorflow/third_party/repo.bzl", line 52, in _execute_and_check_ret_code
                fail("Non-zero return code({1}) when ...))
Non-zero return code(127) when executing 'C:\msys64\usr\bin\bash.exe -l -c "patch" "-p1" "-d" "C:/users/Zeek/_bazel_Zeek/hfhzrtpt/external/com_google_protobuf" "-i" "H:/python/tensorflowcompile/tensorflow/third_party/protobuf/protobuf.patch"':
Stdout:
Stderr: /usr/bin/bash: patch: command not found
INFO: Elapsed time: 19.298s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (6 packages loaded, 18 targets configured)
FAILED: Build did NOT complete successfully (6 packages loaded, 18 targets configured)

perhaps my Bazel options are incorrect?

**Comment by Belgrath1900** [comment]
looks like patch.exe isn't installed, have updated it and compile is getting farther... 

As a double check are my options correct above and are they going to take effect?
--config=v2 -march=nehalem

**Comment by Belgrath1900** [comment]
I got a bit closer and now PythonZipper is failing... 


INFO: Analyzed target //tensorflow/tools/pip_package:build_pip_package (0 packages loaded, 0 targets configured).
INFO: Found 1 target...

[0 / 23] [Prepa] PythonZipper tensorflow/python/keras/api/create_tensorflow.python_api_1_keras_python_api_gen_compat_v1.zip ... (3 actions, 0 running)
ERROR: H:/python/tensorflowcompile/tensorflow/tensorflow/lite/python/BUILD:46:1: PythonZipper tensorflow/lite/python/tflite_convert.zip failed (Exit 255)
FATAL: MappedOutputFile(bazel-out/x64_windows-opt/bin/tensorflow/lite/python/tflite_convert.zip): CreateFileMapping failed
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 38.195s, Critical Path: 4.35s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully

**Comment by Belgrath1900** [comment]
I ran the bezel config again and upon my second compile it now busts much sooner..

java.lang.RuntimeException: Unrecoverable error while evaluating node 'REPOSITORY_DIRECTORY:@local_config_cc' (requested by nodes 'REPOSITORY:@local_config_cc')
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:528)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:399)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.nio.file.InvalidPathException: Illegal char <*> at index 60: C:/users/bill/_bazel_bill/hfhzrtpt/external/local_config_cc/**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.0
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Auxiliary/Build/VCVARSALL.BAT
        at java.base/sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
        at java.base/sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at java.base/sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at java.base/sun.nio.fs.WindowsPath.parse(Unknown Source)
        at java.base/sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
        at java.base/java.nio.file.Path.of(Unknown Source)
        at java.base/java.nio.file.Paths.get(Unknown Source)
        at com.google.devtools.build.lib.vfs.JavaIoFileSystem.getNioPath(JavaIoFileSystem.java:84)
        at com.google.devtools.build.lib.vfs.JavaIoFileSystem.exists(JavaIoFileSystem.java:119)
        at com.google.devtools.build.lib.vfs.Path.exists(Path.java:356)
        at com.google.devtools.build.lib.bazel.repository.skylark.SkylarkPath.exists(SkylarkPath.java:79)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at com.google.devtools.build.lib.syntax.MethodDescriptor.call(MethodDescriptor.java:135)
        at com.google.devtools.build.lib.syntax.DotExpression.eval(DotExpression.java:126)
        at com.google.devtools.build.lib.syntax.DotExpression.doEval(DotExpression.java:51)
        at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:75)
        at com.google.devtools.build.lib.syntax.UnaryOperatorExpression.doEval(UnaryOperatorExpression.java:98)
        at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:75)
        at com.google.devtools.build.lib.syntax.Eval.execIf(Eval.java:139)
        at com.google.devtools.build.lib.syntax.Eval.execDispatch(Eval.java:214)
        at com.google.devtools.build.lib.syntax.Eval.exec(Eval.java:183)
        at com.google.devtools.build.lib.syntax.UserDefinedFunction.call(UserDefinedFunction.java:91)
        at com.google.devtools.build.lib.syntax.BaseFunction.callWithArgArray(BaseFunction.java:474)
        at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:436)
        at com.google.devtools.build.lib.syntax.FuncallExpression.callFunction(FuncallExpression.java:992)
        at com.google.devtools.build.lib.syntax.FuncallExpression.doEval(FuncallExpression.java:904)
        at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:75)
        at com.google.devtools.build.lib.syntax.UnaryOperatorExpression.doEval(UnaryOperatorExpression.java:98)
        at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:75)
        at com.google.devtools.build.lib.syntax.Eval.execIf(Eval.java:139)
        at com.google.devtools.build.lib.syntax.Eval.execDispatch(Eval.java:214)
        at com.google.devtools.build.lib.syntax.Eval.exec(Eval.java:183)
        at com.google.devtools.build.lib.syntax.UserDefinedFunction.call(UserDefinedFunction.java:91)
        at com.google.devtools.build.lib.syntax.BaseFunction.callWithArgArray(BaseFunction.java:474)
        at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:436)
        at com.google.devtools.build.lib.syntax.FuncallExpression.callFunction(FuncallExpression.java:992)
        at com.google.devtools.build.lib.syntax.FuncallExpression.doEval(FuncallExpression.java:904)
        at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:75)
        at com.google.devtools.build.lib.syntax.Eval.execAssignment(Eval.java:72)
        at com.google.devtools.build.lib.syntax.Eval.execDispatch(Eval.java:192)
        at com.google.devtools.build.lib.syntax.Eval.exec(Eval.java:183)
        at com.google.devtools.build.lib.syntax.Eval.execStatements(Eval.java:231)
        at com.google.devtools.build.lib.syntax.Eval.execIf(Eval.java:144)
        at com.google.devtools.build.lib.syntax.Eval.execDispatch(Eval.java:214)
        at com.google.devtools.build.lib.syntax.Eval.exec(Eval.java:183)
        at com.google.devtools.build.lib.syntax.UserDefinedFunction.call(UserDefinedFunction.java:91)
        at com.google.devtools.build.lib.syntax.BaseFunction.callWithArgArray(BaseFunction.java:474)
        at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:436)
        at com.google.devtools.build.lib.syntax.FuncallExpression.callFunction(FuncallExpression.java:992)
        at com.google.devtools.build.lib.syntax.FuncallExpression.doEval(FuncallExpression.java:904)
        at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:75)
        at com.google.devtools.build.lib.syntax.Eval.execAssignment(Eval.java:72)
        at com.google.devtools.build.lib.syntax.Eval.execDispatch(Eval.java:192)
        at com.google.devtools.build.lib.syntax.Eval.exec(Eval.java:183)
        at com.google.devtools.build.lib.syntax.UserDefinedFunction.call(UserDefinedFunction.java:91)
        at com.google.devtools.build.lib.syntax.BaseFunction.callWithArgArray(BaseFunction.java:474)
        at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:436)
        at com.google.devtools.build.lib.syntax.FuncallExpression.callFunction(FuncallExpression.java:992)
        at com.google.devtools.build.lib.syntax.FuncallExpression.doEval(FuncallExpression.java:904)
        at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:75)
        at com.google.devtools.build.lib.syntax.Eval.execDispatch(Eval.java:201)
        at com.google.devtools.build.lib.syntax.Eval.exec(Eval.java:183)
        at com.google.devtools.build.lib.syntax.Eval.execStatements(Eval.java:231)
        at com.google.devtools.build.lib.syntax.Eval.execIfBranch(Eval.java:83)
        at com.google.devtools.build.lib.syntax.Eval.execDispatch(Eval.java:198)
        at com.google.devtools.build.lib.syntax.Eval.exec(Eval.java:183)
        at com.google.devtools.build.lib.syntax.Eval.execIf(Eval.java:140)
        at com.google.devtools.build.lib.syntax.Eval.execDispatch(Eval.java:214)
        at com.google.devtools.build.lib.syntax.Eval.exec(Eval.java:183)
        at com.google.devtools.build.lib.syntax.UserDefinedFunction.call(UserDefinedFunction.java:91)
        at com.google.devtools.build.lib.syntax.BaseFunction.callWithArgArray(BaseFunction.java:474)
        at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:436)
        at com.google.devtools.build.lib.bazel.repository.skylark.SkylarkRepositoryFunction.fetch(SkylarkRepositoryFunction.java:173)
        at com.google.devtools.build.lib.rules.repository.RepositoryDelegatorFunction.fetchRepository(RepositoryDelegatorFunction.java:298)
        at com.google.devtools.build.lib.rules.repository.RepositoryDelegatorFunction.compute(RepositoryDelegatorFunction.java:225)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:451)
        ... 7 more
FAILED: Build did NOT complete successfully (231 packages loaded, 3779 targets configured)
WARNING: Waiting for server process to terminate (waited 5 seconds, waiting at most 60)

H:\Python\TensorFlowCompile\tensorflow>

**Comment by Belgrath1900** [comment]
I dunno what to do next at this point other than to wipe out any .o files that may have been created and start a fresh build all over again.  Is there a Python zip package that I need to install, is that why the pythonZipper failed?

I'm attempting to following the following windows compilation of tensorFlow to account for the fact that my windows machine lacks a CPU/GPU that support AVX commands...

https://www.tensorflow.org/install/source_windows

**Comment by gimtonic** [comment]
For old computers please use tensorflow 1.5 version and python <= 3.6 version.

**Comment by tilakrayal** [comment]
@Belgrath1900 ,
Is this still an issue?

Could you please update TensorFlow to the latest stable version v.2.6 and let us know if you are facing the same error. Thanks!
