### ISSUE TITLE
TypeError: Failed to convert object of type <class 'tuple'> to Tensor. Contents: (Dimension(None), -1, Dimension(2048)). Consider casting elements to a supported type.

### ISSUE THREAD

**Issue by anthonyatp** [tensorflow/tensorflow#33693]
I am getting these error when trying to run my model:

```
"Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/tensor_util.py", line 558, in make_tensor_proto
    str_values = [compat.as_bytes(x) for x in proto_values]
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/tensor_util.py", line 558, in <listcomp>
    str_values = [compat.as_bytes(x) for x in proto_values]
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/compat.py", line 65, in as_bytes
    (bytes_or_text,))
TypeError: Expected binary or unicode string, got Dimension(None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/.local/lib/python3.5/site-packages/trainer/image_captioning.py", line 123, in <module>
    (batch_features.shape[0], -1, batch_features.shape[3]))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 7715, in reshape
    "Reshape", tensor=tensor, shape=shape, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 530, in _apply_op_helper
    raise err
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 527, in _apply_op_helper
    preferred_dtype=default_dtype)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1224, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/constant_op.py", line 305, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/constant_op.py", line 246, in constant
    allow_broadcast=True)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/constant_op.py", line 284, in _constant_impl
    allow_broadcast=allow_broadcast))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/tensor_util.py", line 562, in make_tensor_proto
    "supported type." % (type(values), values))
TypeError: Failed to convert object of type <class 'tuple'> to Tensor. Contents: (Dimension(None), -1, Dimension(2048)). Consider casting elements to a supported type.
```

And i believe the issue is in this bit of code:

```
# Get unique images
encode_train = sorted(set(img_name_vector))

image_dataset = tf.data.Dataset.from_tensor_slices(encode_train)
image_dataset = image_dataset.map(
  load_image, num_parallel_calls=tf.data.experimental.AUTOTUNE).batch(16)

for img, path in image_dataset:
  batch_features = image_features_extract_model(img)
  batch_features = tf.reshape(batch_features,
                              (batch_features.shape[0], -1, batch_features.shape[3]))

  for bf, p in zip(batch_features, path):
    np.save(file_io.FileIO(IMG_PATH, 'w'), bf.numpy())
```

So it seems that batch_features.shape[0] is returning None - how can I handle this?

I have tried to use `tf.shape(batch_features)[0]` instead of `batch_features.shape[0]` but then the error is:
```
TypeError: Tensor objects are only iterable when eager execution is enabled. To iterate over this tensor use tf.map_fn.
```

**Comment by oanush** [comment]
@anthonyatp ,
Can you please provide a complete reproducible code snippet to reflect this issue? Also mention the TF version being used. Thanks!

**Comment by anthonyatp** [comment]
@oanush 
So im actually running the Image captioning tutorial: https://www.tensorflow.org/tutorials/text/image_captioning#download_and_prepare_the_ms-coco_dataset

the 2 main differences are I am using a different dataset of images and captions and I am running this on google ai platform:
```
gcloud ai-platform jobs submit training $JOB_NAME \
--staging-bucket $STAGING_BUCKET \
--module-name trainer.image_captioning \
--package-path ./trainer \
--region europe-west1 \
--config=trainer/cloudml_gpu.yaml \
--python-version 3.5 \
--runtime-version 1.14
```

I have tensorflow version 2.0 installed in my virtualenv

**Comment by anthonyatp** [comment]
when I run locally the shape of 'batch_features' is `(16, 8, 8, 2048)` but in the cloud it seems its `(?, 8, 8, 2048)` and therefore i am getting Dimension(None)

**Comment by anthonyatp** [comment]
maybe its the way I am loading the json file containing image ids and captions?

`with tf.io.gfile.GFile("gs://{BUCKET_NAME}/captions.json", 'r') as f: annotations = json.load(f)`

**Comment by anthonyatp** [comment]
ok I think I have narrowed down the problem to the version of tensorflow. I had no problems running locally because I have tf version 2 installed (with python 3.8), however, the latest supported version of tf on google ai platform is v1.14.

I downgraded locally to v1.14 and now I am getting the same error as when I run the model on the google ai platform. 

So I assume parts of the TensorFlow API I am using are only compatible with version 2. 

Any advice to get this running on google ai platform?

**Comment by YINGYINGHU1220** [comment]
I have the same issue when training a model on GCP AI-platform.. Did you solve it? Thanks!

**Comment by anthonyatp** [comment]
the issue is the model using tensorflow version 2.0, however, google ai platform does not support this version yet. To get around this, you can create a notebook instance with a tf v2.0 environment to train the model

**Comment by gowthamkpr** [comment]
I think the root of this issue is that version of tensorflow. @YINGYINGHU1220 Please follow the recommendation of @anthonyatp and it should solve your issue. I am closing this issue for now. 

If you have any more doubts, you can add additional comments and we can open this issue again. Thanks!
