### ISSUE TITLE
File "C:\Users\idzha\Anaconda3\lib\sqlite3\__init__.py", line 23, in <module> from sqlite3.dbapi2 import *   File "C:\Users\idzha\Anaconda3\lib\sqlite3\dbapi2.py", line 27, in <module>     from _sqlite3 import *ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by Idzhan94** [tensorflow/tensorflow#33705]

**Comment by Idzhan94** [comment]
Using cmder on windows 10:-
python manage.py runserver
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Users\idzha\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Users\idzha\Anaconda3\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\idzha\Anaconda3\lib\site-packages\django\utils\autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\idzha\Anaconda3\lib\site-packages\django\core\management\commands\runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "C:\Users\idzha\Anaconda3\lib\site-packages\django\utils\autoreload.py", line 77, in raise_last_exception
    raise _exception[1]
  File "C:\Users\idzha\Anaconda3\lib\site-packages\django\core\management\__init__.py", line 337, in execute
    autoreload.check_errors(django.setup)()
  File "C:\Users\idzha\Anaconda3\lib\site-packages\django\utils\autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\idzha\Anaconda3\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\idzha\Anaconda3\lib\site-packages\django\apps\registry.py", line 114, in populate
    app_config.import_models()
  File "C:\Users\idzha\Anaconda3\lib\site-packages\django\apps\config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "C:\Users\idzha\Anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\idzha\Anaconda3\lib\site-packages\django\contrib\auth\models.py", line 2, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "C:\Users\idzha\Anaconda3\lib\site-packages\django\contrib\auth\base_user.py", line 47, in <module>
    class AbstractBaseUser(models.Model):
  File "C:\Users\idzha\Anaconda3\lib\site-packages\django\db\models\base.py", line 117, in __new__
    new_class.add_to_class('_meta', Options(meta, app_label))
  File "C:\Users\idzha\Anaconda3\lib\site-packages\django\db\models\base.py", line 321, in add_to_class
    value.contribute_to_class(cls, name)
  File "C:\Users\idzha\Anaconda3\lib\site-packages\django\db\models\options.py", line 204, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "C:\Users\idzha\Anaconda3\lib\site-packages\django\db\__init__.py", line 28, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "C:\Users\idzha\Anaconda3\lib\site-packages\django\db\utils.py", line 201, in __getitem__
    backend = load_backend(db['ENGINE'])
  File "C:\Users\idzha\Anaconda3\lib\site-packages\django\db\utils.py", line 110, in load_backend
    return import_module('%s.base' % backend_name)
  File "C:\Users\idzha\Anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\idzha\Anaconda3\lib\site-packages\django\db\backends\sqlite3\base.py", line 13, in <module>
    from sqlite3 import dbapi2 as Database
  File "C:\Users\idzha\Anaconda3\lib\sqlite3\__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "C:\Users\idzha\Anaconda3\lib\sqlite3\dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: DLL load failed: The specified module could not be found.

**Comment by gadagashwini** [comment]
@Idzhan94, Does your CPU support the AVX instruction set, which is enabled by default since v1.6. To use TF on your system, either downgrade to TF 1.5, or build TF from [source](https://www.tensorflow.org/install/source_windows). Please let us know how it progresses. Thanks!

**Comment by gadagashwini** [comment]
@Idzhan94, Were you able to solve this issue? Thanks!

**Comment by gadagashwini** [comment]
Closing issue as it is not related to Tensorflow. Please feel free to reopen if this issue is from Tensorflow. Thanks!
