### ISSUE TITLE
Conversion to TFLite model does not work -error 

### ISSUE THREAD

**Issue by grewe** [tensorflow/tensorflow#33712]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes (but, from example at taken from https://colab.research.google.com/github/tensorflow/examples/blob/master/courses/udacity_intro_to_tensorflow_for_deep_learning/l05c02_dogs_vs_cats_with_augmentation.ipynb)
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:No
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):  2.0.0
- Python version: 3.6.1  (via Jupyter notebook)
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I can save the tensorflow keras model to an h5 file but, when subsequently try to convert to TFLite using code below it fails.   Following directions at https://www.tensorflow.org/tutorials/keras/save_and_load  to perform conversion to TFLite (see code below) 

**Describe the expected behavior**
Should save a TFLite file after conversion

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
`tflite_file  = os.path.join(BASE_DIRECTORY, 'my_tflite_model.h5')
print(" want to save tflite_file" + tflite_file)
# Convert the model.
converter = tf.lite.TFLiteConverter.from_keras_model(model)
print("converter = " + str(converter))
tflite_model = converter.convert()

#no save the tflight model to the file
tflite_model.save(tflite_file)`
**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

Error I am getting:-------------------------------
---------------------------------------------------------------------------
ConverterError                            Traceback (most recent call last)
<ipython-input-49-fc606e1e0a8b> in <module>()
      5 converter = tf.lite.TFLiteConverter.from_keras_model(model)
      6 print("converter = " + str(converter))
----> 7 tflite_model = converter.convert()
      8 
      9 #no save the tflight model to the file

~\AppData\Roaming\Python\Python36\site-packages\tensorflow_core\lite\python\lite.py in convert(self)
    444         input_tensors=input_tensors,
    445         output_tensors=output_tensors,
--> 446         **converter_kwargs)
    447 
    448     if self._is_calibration_quantize():

~\AppData\Roaming\Python\Python36\site-packages\tensorflow_core\lite\python\convert.py in toco_convert_impl(input_data, input_tensors, output_tensors, enable_mlir_converter, *args, **kwargs)
    447       input_data.SerializeToString(),
    448       debug_info_str=debug_info_str,
--> 449       enable_mlir_converter=enable_mlir_converter)
    450   return data
    451 

~\AppData\Roaming\Python\Python36\site-packages\tensorflow_core\lite\python\convert.py in toco_convert_protos(model_flags_str, toco_flags_str, input_data_str, debug_info_str, enable_mlir_converter)
    198       stdout = _try_convert_to_unicode(stdout)
    199       stderr = _try_convert_to_unicode(stderr)
--> 200       raise ConverterError("See console for info.\n%s\n%s\n" % (stdout, stderr))
    201   finally:
    202     # Must manually cleanup files.

ConverterError: See console for info.
Traceback (most recent call last):
  File "c:\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python36\Scripts\toco_from_protos.exe\__main__.py", line 5, in <module>
ModuleNotFoundError: No module named 'tensorflow.contrib'

**Comment by grewe** [comment]
Please note I have read the issue 25162 that I believe is related but, was not resolved.  Does this have something to do with running on Windows?
https://github.com/tensorflow/tensorflow/issues/25162
