### ISSUE TITLE
Generating Arduino Libraries error

### ISSUE THREAD

**Issue by DaveCalaway** [tensorflow/tensorflow#33720]
**System information**
- OS Platform and Distribution : macOS 10.14.6
- TensorFlow version: 1.15.0
- Python version: 2.7.10 and 3.7.4 

**Describe the problem**
When i run the command "sh test_arduino.sh" it gaves me that error:
```
...
Finished patching kissfft
Traceback (most recent call last):
  File "tensorflow/lite/experimental/micro/tools/make/generate_keil_project.py", line 121, in <module>
    parse_args()
  File "tensorflow/lite/experimental/micro/tools/make/generate_keil_project.py", line 117, in parse_args
    main(unparsed, flags)
  File "tensorflow/lite/experimental/micro/tools/make/generate_keil_project.py", line 39, in main
    six.ensure_str(flags.executable),
AttributeError: 'module' object has no attribute 'ensure_str'
make: *** [tensorflow/lite/experimental/micro/examples/person_detection/Makefile.inc:56: tensorflow/lite/experimental/micro/tools/make/gen/arduino_x86_64/prj/person_detection_test/keil/keil_project.uvprojx] Error 1
```
I tried to use python3, changing the line 304 in "/tensorflow/tensorflow/lite/experimental/micro/tools/make/Makefile", but nothing change.

**Comment by arashb** [comment]
upgrading the `six` package to 1.14 fixed the issue for me.
