### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by masapasa** [tensorflow/tensorflow#33730]
>>> import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/aswin/anaconda3/envs/tfgpu/lib/python3.7/site-packages/tensorflow/__init__.py", line 98, in <module>
    from tensorflow_core import *
  File "/home/aswin/anaconda3/envs/tfgpu/lib/python3.7/site-packages/tensorflow_core/__init__.py", line 45, in <module>
    from . _api.v2 import compat
  File "/home/aswin/anaconda3/envs/tfgpu/lib/python3.7/site-packages/tensorflow_core/_api/v2/compat/__init__.py", line 23, in <module>
    from . import v1
  File "/home/aswin/anaconda3/envs/tfgpu/lib/python3.7/site-packages/tensorflow_core/_api/v2/compat/v1/__init__.py", line 666, in <module>
    [_module_util.get_parent_dir(estimator)] + _current_module.__path__)
  File "/home/aswin/anaconda3/envs/tfgpu/lib/python3.7/site-packages/tensorflow_core/python/tools/module_util.py", line 24, in get_parent_dir
    return os.path.abspath(os.path.join(os.path.dirname(module.__file__), ".."))
  File "/home/aswin/anaconda3/envs/tfgpu/lib/python3.7/posixpath.py", line 156, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by gowthamkpr** [comment]
Can you please provide more context to the issue by filling the template thats being provided [here](https://github.com/tensorflow/tensorflow/issues/new/choose). Thanks!

**Comment by tehilden** [comment]
I have this same issue on Ubuntu 19.04. Only happens with venv install. Works with system Python.

**Comment by masapasa** [comment]
ok, i removed the current venv and created new venv. It is working now.
