### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by masapasa** [tensorflow/tensorflow#33738]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
pip install tensorflow-gpu
- TensorFlow version:
2
- Python version:
3.7
- Installed using virtualenv? pip? conda?:
pip in a conda env
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
cuda 10.0.1
- GPU model and memory:
GeForce GTX 1050 Ti with Max-Q Design/PCIe/SSE2

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**
import tensorflow as tf

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/aswin/anaconda3/envs/tfgpu/lib/python3.7/site-packages/tensorflow/__init__.py", line 98, in <module>
    from tensorflow_core import *
  File "/home/aswin/anaconda3/envs/tfgpu/lib/python3.7/site-packages/tensorflow_core/__init__.py", line 45, in <module>
    from . _api.v2 import compat
  File "/home/aswin/anaconda3/envs/tfgpu/lib/python3.7/site-packages/tensorflow_core/_api/v2/compat/__init__.py", line 23, in <module>
    from . import v1
  File "/home/aswin/anaconda3/envs/tfgpu/lib/python3.7/site-packages/tensorflow_core/_api/v2/compat/v1/__init__.py", line 666, in <module>
    [_module_util.get_parent_dir(estimator)] + _current_module.__path__)
  File "/home/aswin/anaconda3/envs/tfgpu/lib/python3.7/site-packages/tensorflow_core/python/tools/module_util.py", line 24, in get_parent_dir
    return os.path.abspath(os.path.join(os.path.dirname(module.__file__), ".."))
  File "/home/aswin/anaconda3/envs/tfgpu/lib/python3.7/posixpath.py", line 156, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by ymodak** [comment]
duplicate #33730

**Comment by Pathakvishnu** [comment]
en2de = torch.hub.load('pytorch/fairseq', 'transformer.wmt19.en-de.single_model', tokenizer='moses', bpe='fastbpe')
Using cache found in /home/glmr/.cache/torch/hub/pytorch_fairseq_master
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/glmr/anaconda3/envs/fairseq/lib/python3.6/site-packages/torch/hub.py", line 363, in load
    model = entry(*args, **kwargs)
  File "/home/glmr/.cache/torch/hub/pytorch_fairseq_master/fairseq/models/fairseq_model.py", line 190, in from_pretrained
    **kwargs,
  File "/home/glmr/.cache/torch/hub/pytorch_fairseq_master/fairseq/hub_utils.py", line 56, in from_pretrained
    kwargs['data'] = os.path.abspath(os.path.join(model_path, data_name_or_path))
  File "/home/glmr/anaconda3/envs/fairseq/lib/python3.6/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by Pathakvishnu** [comment]
Anyone pls help with this problem.
