### ISSUE TITLE
Tensorflow 2 Integer Labels

### ISSUE THREAD

**Issue by ziruizhuang** [tensorflow/tensorflow#33855]
From the docs, it says if I want to use labels without one_hot encoding in advance, I should use SparseCategoricalCrossentropy. And the result is strange. 

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 1903 18362.418
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.0.0-rc2-26-g64c3d382ca 2.0.0
- Python version: Python 3.7.3 (default, Mar 27 2019, 17:13:21) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc.
- Bazel version (if compiling from source): 
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: cudart64_100.dll
- GPU model and memory:

**Describe the current behavior**
the model won't compile
using from_logits=False, reporting TypeError: Expected int32, got 1e-07 of type 'float' instead.
using from_logits=True, get TypeError: Value passed to parameter 'features' has DataType int32 not in list of allowed values: float16, bfloat16, float32, float64

```
Traceback (most recent call last):
  File "C:\Users\user\Anaconda3\lib\site-packages\tensorflow_core\python\framework\tensor_util.py", line 324, in _AssertCompatible
    fn(values)
  File "C:\Users\user\Anaconda3\lib\site-packages\tensorflow_core\python\framework\tensor_util.py", line 263, in inner
    _ = [_check_failed(v) for v in nest.flatten(values)
  File "C:\Users\user\Anaconda3\lib\site-packages\tensorflow_core\python\framework\tensor_util.py", line 264, in <listcomp>
    if not isinstance(v, expected_types)]
  File "C:\Users\user\Anaconda3\lib\site-packages\tensorflow_core\python\framework\tensor_util.py", line 248, in _check_failed
    raise ValueError(v)
ValueError: 1e-07

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/user/OneDrive/UH/cvxtest/main2.py", line 84, in <module>
    metrics=[
  File "C:\Users\user\Anaconda3\lib\site-packages\tensorflow_core\python\training\tracking\base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "C:\Users\user\Anaconda3\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 373, in compile
    self._compile_weights_loss_and_weighted_metrics()
  File "C:\Users\user\Anaconda3\lib\site-packages\tensorflow_core\python\training\tracking\base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "C:\Users\user\Anaconda3\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 1653, in _compile_weights_loss_and_weighted_metrics
    self.total_loss = self._prepare_total_loss(masks)
  File "C:\Users\user\Anaconda3\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 1713, in _prepare_total_loss
    per_sample_losses = loss_fn.call(y_true, y_pred)
  File "C:\Users\user\Anaconda3\lib\site-packages\tensorflow_core\python\keras\losses.py", line 221, in call
    return self.fn(y_true, y_pred, **self._fn_kwargs)
  File "C:\Users\user\Anaconda3\lib\site-packages\tensorflow_core\python\keras\losses.py", line 978, in sparse_categorical_crossentropy
    y_true, y_pred, from_logits=from_logits, axis=axis)
  File "C:\Users\user\Anaconda3\lib\site-packages\tensorflow_core\python\keras\backend.py", line 4504, in sparse_categorical_crossentropy
    epsilon_ = _constant_to_tensor(epsilon(), output.dtype.base_dtype)
  File "C:\Users\user\Anaconda3\lib\site-packages\tensorflow_core\python\keras\backend.py", line 673, in _constant_to_tensor
    return constant_op.constant(x, dtype=dtype)
  File "C:\Users\user\Anaconda3\lib\site-packages\tensorflow_core\python\framework\constant_op.py", line 227, in constant
    allow_broadcast=True)
  File "C:\Users\user\Anaconda3\lib\site-packages\tensorflow_core\python\framework\constant_op.py", line 265, in _constant_impl
    allow_broadcast=allow_broadcast))
  File "C:\Users\user\Anaconda3\lib\site-packages\tensorflow_core\python\framework\tensor_util.py", line 449, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "C:\Users\user\Anaconda3\lib\site-packages\tensorflow_core\python\framework\tensor_util.py", line 331, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got 1e-07 of type 'float' instead.
```

```
Traceback (most recent call last):
  File "C:/Users/user/OneDrive/UH/cvxtest/main2.py", line 84, in <module>
    metrics=[
  File "C:\Users\user\Anaconda3\lib\site-packages\tensorflow_core\python\training\tracking\base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "C:\Users\user\Anaconda3\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 373, in compile
    self._compile_weights_loss_and_weighted_metrics()
  File "C:\Users\user\Anaconda3\lib\site-packages\tensorflow_core\python\training\tracking\base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "C:\Users\user\Anaconda3\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 1653, in _compile_weights_loss_and_weighted_metrics
    self.total_loss = self._prepare_total_loss(masks)
  File "C:\Users\user\Anaconda3\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 1713, in _prepare_total_loss
    per_sample_losses = loss_fn.call(y_true, y_pred)
  File "C:\Users\user\Anaconda3\lib\site-packages\tensorflow_core\python\keras\losses.py", line 221, in call
    return self.fn(y_true, y_pred, **self._fn_kwargs)
  File "C:\Users\user\Anaconda3\lib\site-packages\tensorflow_core\python\keras\losses.py", line 978, in sparse_categorical_crossentropy
    y_true, y_pred, from_logits=from_logits, axis=axis)
  File "C:\Users\user\Anaconda3\lib\site-packages\tensorflow_core\python\keras\backend.py", line 4546, in sparse_categorical_crossentropy
    labels=target, logits=output)
  File "C:\Users\user\Anaconda3\lib\site-packages\tensorflow_core\python\ops\nn_ops.py", line 3477, in sparse_softmax_cross_entropy_with_logits_v2
    labels=labels, logits=logits, name=name)
  File "C:\Users\user\Anaconda3\lib\site-packages\tensorflow_core\python\ops\nn_ops.py", line 3397, in sparse_softmax_cross_entropy_with_logits
    precise_logits, labels, name=name)
  File "C:\Users\user\Anaconda3\lib\site-packages\tensorflow_core\python\ops\gen_nn_ops.py", line 11842, in sparse_softmax_cross_entropy_with_logits
    labels=labels, name=name)
  File "C:\Users\user\Anaconda3\lib\site-packages\tensorflow_core\python\framework\op_def_library.py", line 631, in _apply_op_helper
    param_name=input_name)
  File "C:\Users\user\Anaconda3\lib\site-packages\tensorflow_core\python\framework\op_def_library.py", line 60, in _SatisfiesTypeConstraint
    ", ".join(dtypes.as_dtype(x).name for x in allowed_list)))
TypeError: Value passed to parameter 'features' has DataType int32 not in list of allowed values: float16, bfloat16, float32, float64
```

**Describe the expected behavior**
Compile and run. It is a pretty simple model after all.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
```
import numpy as np
import tensorflow as tf

from keras.datasets import fashion_mnist

tf.random.set_seed(1)
np.random.seed(1)


if __name__ == '__main__':
    (train_X, train_Y), (test_X, test_Y) = fashion_mnist.load_data()

    train_X = train_X.reshape(-1, 28, 28, 1)
    test_X = test_X.reshape(-1, 28, 28, 1)

    train_X = train_X.astype('float32')
    test_X = test_X.astype('float32')
    train_X = train_X / 255
    test_X = test_X / 255

    train_L = len(train_X)
    test_L = len(test_X)

    print(train_Y[0], type(train_Y[0]))

    x_input = tf.keras.Input(dtype=tf.dtypes.float32, shape=[28, 28, 1])
    y_input = tf.keras.Input(dtype=tf.dtypes.int32, shape=[1])
    
    x = tf.keras.layers.Flatten()(x_input)
    y_target = tf.one_hot(y_input, 10)
    y_logits = tf.keras.layers.Dense(10)(x)
    y_probability = tf.keras.layers.Softmax()(y_logits)
    y_output = tf.math.argmax(
        input=y_probability,
        axis=1,
        output_type=tf.dtypes.int32
    )

    model = tf.keras.Model(inputs=[x_input, y_input], outputs=y_output)

    model.compile(
        optimizer=tf.keras.optimizers.SGD(learning_rate=1e-3),
        loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=False),

        metrics=[
            # 'accuracy'
            #tf.keras.metrics.Accuracy()
        ]
    )

    # Trains for 5 epochs
    model.fit(x=train_X, y=train_Y, batch_size=32, epochs=5)

```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ziruizhuang** [comment]
it seems there is inconsistency between docs.
from https://www.tensorflow.org/api_docs/python/tf/keras/losses/CategoricalCrossentropy
> Use this crossentropy loss function when there are two or more label classes. We expect labels to be provided in a one_hot representation. If you want to provide labels as integers, please use SparseCategoricalCrossentropy loss. There should be # classes floating point values per feature.

However, from https://www.tensorflow.org/api_docs/python/tf/keras/losses/SparseCategoricalCrossentropy#__init__
> Use this crossentropy loss function when there are two or more label classes. We expect labels to be provided as integers. If you want to provide labels using one-hot representation, please use CategoricalCrossentropy loss. There should be # classes floating point values per feature for y_pred and a single floating point value per feature for y_true.
In the snippet below, there is a single floating point value per example for y_true and # classes floating pointing values per example for y_pred. The shape of y_true is [batch_size] and the shape of y_pred is [batch_size, num_classes].

The latter being said that where should always be # classes features for the input of SparseCategoricalCrossentropy.__call__ , whether it is in the form of probability distribution or logits. 

And here comes another question, if this is the case, how could I pass only integers as labels without the need one-hot encoding them first?

**Comment by captain-pool** [comment]
Hey @ziruizhuang I went through the issue and the gist that @gadagashwini  provided, It looked like casting the type of `y_output` to `float32` solves the problem. And another thing that I noticed, the value being shown is really really small, around 1e-07, so I can roughly guess there's some issue with the sparse_categorical_entropy kernel and it can't handle non-float data, may be trying to figure out the floating point alternative of the interger inputs, it breaks, because of some floating point error. Not sure if that's a bug, or a feature.
@vbardiovskyg @srjoglekar246 can you confirm?

**Comment by ziruizhuang** [comment]
@captain-pool Thanks for the suggestion. I tried to cast it to float32 but I got another error and it seems that it is related to the shape of the tensors.
```
    (train_X, train_Y), (test_X, test_Y) = fashion_mnist.load_data()

    train_X = train_X.reshape(-1, 28, 28, 1)
    test_X = test_X.reshape(-1, 28, 28, 1)

    train_X = train_X.astype('float32')
    test_X = test_X.astype('float32')
    train_X = train_X / 255
    test_X = test_X / 255

    train_L = len(train_X)
    test_L = len(test_X)

    x_input = tf.keras.Input(dtype=tf.dtypes.float32, shape=[28, 28, 1])

    x = tf.keras.layers.Flatten()(x_input)
    y_logits = tf.keras.layers.Dense(10)(x)
    y_probability = tf.keras.layers.Softmax()(y_logits)
    y_output = tf.math.argmax(
        input=y_probability,
        axis=1,
        output_type=tf.dtypes.int32
    )
    y_output = tf.dtypes.cast(y_output, tf.float32)

    model = tf.keras.Model(inputs=x_input, outputs=y_output)

    model.compile(
        optimizer=tf.keras.optimizers.SGD(learning_rate=1e-3),
        loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=False),

        metrics=[
            # 'accuracy'
            tf.keras.metrics.Accuracy()
        ]
    )

    # Trains for 5 epochs
    model.fit(x=train_X, y=train_Y, batch_size=32, epochs=5)
```
```
Traceback (most recent call last):
  File "C:/Users/user/OneDrive/UH/cvxtest/test3.py", line 56, in <module>
    model.fit(x=train_X, y=train_Y, batch_size=32, epochs=5)
  File "C:\Users\user\Miniconda3\envs\tf2\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 728, in fit
    use_multiprocessing=use_multiprocessing)
  File "C:\Users\user\Miniconda3\envs\tf2\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py", line 324, in fit
    total_epochs=epochs)
  File "C:\Users\user\Miniconda3\envs\tf2\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py", line 123, in run_one_epoch
    batch_outs = execution_function(iterator)
  File "C:\Users\user\Miniconda3\envs\tf2\lib\site-packages\tensorflow_core\python\keras\engine\training_v2_utils.py", line 86, in execution_function
    distributed_function(input_fn))
  File "C:\Users\user\Miniconda3\envs\tf2\lib\site-packages\tensorflow_core\python\eager\def_function.py", line 457, in __call__
    result = self._call(*args, **kwds)
  File "C:\Users\user\Miniconda3\envs\tf2\lib\site-packages\tensorflow_core\python\eager\def_function.py", line 503, in _call
    self._initialize(args, kwds, add_initializers_to=initializer_map)
  File "C:\Users\user\Miniconda3\envs\tf2\lib\site-packages\tensorflow_core\python\eager\def_function.py", line 408, in _initialize
    *args, **kwds))
  File "C:\Users\user\Miniconda3\envs\tf2\lib\site-packages\tensorflow_core\python\eager\function.py", line 1848, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "C:\Users\user\Miniconda3\envs\tf2\lib\site-packages\tensorflow_core\python\eager\function.py", line 2150, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "C:\Users\user\Miniconda3\envs\tf2\lib\site-packages\tensorflow_core\python\eager\function.py", line 2041, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "C:\Users\user\Miniconda3\envs\tf2\lib\site-packages\tensorflow_core\python\framework\func_graph.py", line 915, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "C:\Users\user\Miniconda3\envs\tf2\lib\site-packages\tensorflow_core\python\eager\def_function.py", line 358, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "C:\Users\user\Miniconda3\envs\tf2\lib\site-packages\tensorflow_core\python\keras\engine\training_v2_utils.py", line 73, in distributed_function
    per_replica_function, args=(model, x, y, sample_weights))
  File "C:\Users\user\Miniconda3\envs\tf2\lib\site-packages\tensorflow_core\python\distribute\distribute_lib.py", line 760, in experimental_run_v2
    return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
  File "C:\Users\user\Miniconda3\envs\tf2\lib\site-packages\tensorflow_core\python\distribute\distribute_lib.py", line 1787, in call_for_each_replica
    return self._call_for_each_replica(fn, args, kwargs)
  File "C:\Users\user\Miniconda3\envs\tf2\lib\site-packages\tensorflow_core\python\distribute\distribute_lib.py", line 2132, in _call_for_each_replica
    return fn(*args, **kwargs)
  File "C:\Users\user\Miniconda3\envs\tf2\lib\site-packages\tensorflow_core\python\autograph\impl\api.py", line 292, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\user\Miniconda3\envs\tf2\lib\site-packages\tensorflow_core\python\keras\engine\training_v2_utils.py", line 264, in train_on_batch
    output_loss_metrics=model._output_loss_metrics)
  File "C:\Users\user\Miniconda3\envs\tf2\lib\site-packages\tensorflow_core\python\keras\engine\training_eager.py", line 311, in train_on_batch
    output_loss_metrics=output_loss_metrics))
  File "C:\Users\user\Miniconda3\envs\tf2\lib\site-packages\tensorflow_core\python\keras\engine\training_eager.py", line 252, in _process_single_batch
    training=training))
  File "C:\Users\user\Miniconda3\envs\tf2\lib\site-packages\tensorflow_core\python\keras\engine\training_eager.py", line 166, in _model_loss
    per_sample_losses = loss_fn.call(targets[i], outs[i])
  File "C:\Users\user\Miniconda3\envs\tf2\lib\site-packages\tensorflow_core\python\keras\losses.py", line 221, in call
    return self.fn(y_true, y_pred, **self._fn_kwargs)
  File "C:\Users\user\Miniconda3\envs\tf2\lib\site-packages\tensorflow_core\python\keras\losses.py", line 978, in sparse_categorical_crossentropy
    y_true, y_pred, from_logits=from_logits, axis=axis)
  File "C:\Users\user\Miniconda3\envs\tf2\lib\site-packages\tensorflow_core\python\keras\backend.py", line 4546, in sparse_categorical_crossentropy
    labels=target, logits=output)
  File "C:\Users\user\Miniconda3\envs\tf2\lib\site-packages\tensorflow_core\python\ops\nn_ops.py", line 3477, in sparse_softmax_cross_entropy_with_logits_v2
    labels=labels, logits=logits, name=name)
  File "C:\Users\user\Miniconda3\envs\tf2\lib\site-packages\tensorflow_core\python\ops\nn_ops.py", line 3393, in sparse_softmax_cross_entropy_with_logits
    logits.get_shape()))
ValueError: Shape mismatch: The shape of labels (received (32,)) should equal the shape of logits except for the last dimension (received (1, 32)).
```

**Comment by kenseii** [comment]
Hello, how did you finally solve this issue?

**Comment by ziruizhuang** [comment]
Hi @kenseii ,
I choose to use low level API instead.

for your reference, the code works fine both using CategoricalCrossentropy and SparseCategoricalCrossentropy

```
import numpy as np
import tensorflow as tf

from mnist import train_images, test_images, train_labels, test_labels

tf.random.set_seed(1)
np.random.seed(1)

LOSS_TYPES = {
    'CE': tf.keras.losses.CategoricalCrossentropy(),
    'SCE': tf.keras.losses.SparseCategoricalCrossentropy()
}
LOSS_TYPE1 = 'CE'
LOSS_TYPE2 = LOSS_TYPES[LOSS_TYPE1]

DTYPES = {
    'float16': tf.float16,
    'float32': tf.float32,
    'float64': tf.float64
}

DTYPE1 = 'float32'
DTYPE2 = DTYPES[DTYPE1]

tf.keras.backend.set_floatx(DTYPE1)

EPOCHS = 50
NCLASS = 10
BATCH_SIZE = 256


class MNISTModel(tf.keras.Model):
    loss_object = LOSS_TYPE2

    optimizer = tf.keras.optimizers.Adam(learning_rate=1e-3)

    train_loss = tf.keras.metrics.Mean(name='train_loss')
    validate_loss = tf.keras.metrics.Mean(name='train_loss')
    test_loss = tf.keras.metrics.Mean(name='test_loss')

    train_acc = tf.keras.metrics.SparseCategoricalAccuracy(name='train_acc')
    validate_acc = tf.keras.metrics.SparseCategoricalAccuracy(name='train_acc')
    test_acc = tf.keras.metrics.SparseCategoricalAccuracy(name='test_acc')

    n_class = None

    def __init__(self, n_class):
        super(MNISTModel, self).__init__()
        self.n_class = n_class

        self.d0 = tf.keras.layers.Conv2D(16, [3, 3], 1, 'same', activation='relu')
        self.d1 = tf.keras.layers.Conv2D(16, [3, 3], 1, 'same', activation='relu')
        self.d2 = tf.keras.layers.Conv2D(16, [3, 3], 1, 'same', activation='relu')
        self.d3 = tf.keras.layers.Conv2D(16, [3, 3], 1, 'same', activation='relu')

        self.p0 = tf.keras.layers.MaxPooling2D((2, 2))
        self.p1 = tf.keras.layers.MaxPooling2D((2, 2))
        self.p2 = tf.keras.layers.MaxPooling2D((2, 2))
        self.p3 = tf.keras.layers.MaxPooling2D((2, 2))

        self.d_prior = tf.keras.layers.Dense(64, activation='relu')
        self.d_out = tf.keras.layers.Dense(self.n_class, activation='softmax')

    @tf.function
    def call(self, x, training):
        x = tf.dtypes.cast(
            tf.reshape(x, [-1, 28, 28, 1]),
            dtype=DTYPE2
        )

        x = self.d0(x)
        x = self.p0(x)

        x = self.d1(x)
        x = self.p1(x)

        x = self.d2(x)
        x = self.p2(x)

        x = self.d3(x)
        x = self.p3(x)

        x = tf.keras.layers.Flatten()(x)

        x = self.d_prior(x)
        x = self.d_out(x)
        return x

    @tf.function
    def train_step(self, x, y):
        with tf.GradientTape() as tape:
            predictions = self.call(x, training=True)

            if LOSS_TYPE1 == 'CE':
                y_one_hot = tf.one_hot(y, self.n_class)
                loss = self.loss_object(y_one_hot, predictions)
            elif LOSS_TYPE1 == 'SCE':
                loss = self.loss_object(y, predictions)

            # print('loss', loss)
        gradients = tape.gradient(loss, self.trainable_variables)
        # print([gvs.shape for gvs in gradients])

        # gradients = [
        #     tf.where(
        #         tf.math.is_nan(grad),
        #         tf.zeros_like(grad),
        #         grad
        #     )
        #     for grad in gradients
        # ]

        # print('gradients', gradients)
        self.optimizer.apply_gradients(zip(gradients, self.trainable_variables))
        self.train_loss(loss)
        self.train_acc.update_state(y, predictions)
        return loss

    @tf.function
    def test_step(self, x, y):
        predictions = self.call(x, training=False)
        if LOSS_TYPE1 == 'CE':
            y_one_hot = tf.one_hot(y, self.n_class)
            t_loss = self.loss_object(y_one_hot, predictions)
        elif LOSS_TYPE1 == 'SCE':
            t_loss = self.loss_object(y, predictions)
        # t_loss = tf.reduce_sum(t_loss) * (1. / BATCH_SIZE)
        self.test_loss(t_loss)
        self.test_acc.update_state(y, predictions)

    @tf.function
    def validate_step(self, x, y):
        predictions = self.call(x, training=False)
        if LOSS_TYPE1 == 'CE':
            y_one_hot = tf.one_hot(y, self.n_class)
            v_loss = self.loss_object(y_one_hot, predictions)
        elif LOSS_TYPE1 == 'CE':
            v_loss = self.loss_object(y, predictions)
        # t_loss = tf.reduce_sum(t_loss) * (1. / BATCH_SIZE)
        self.validate_loss(v_loss)
        self.validate_acc.update_state(y, predictions)


if __name__ == '__main__':
    x_train = train_images()
    y_train = train_labels()

    x_test = test_images()
    y_test = test_labels()

    print(np.shape(y_train))

    model = MNISTModel(NCLASS)

    train_ds = tf.data.Dataset.from_tensor_slices(
        (x_train, y_train)
    ).shuffle(10000).batch(BATCH_SIZE)

    test_ds = tf.data.Dataset.from_tensor_slices(
        (x_test, y_test)
    ).batch(BATCH_SIZE)

    for epoch in range(EPOCHS):
        for x, y in train_ds:
            model.train_step(x, y)

        for x, y in test_ds:
            model.test_step(x, y)

        template = 'Epoch {}, Train Loss: {}, Test Loss: {}, Train Acc: {}, Test Acc: {}'

        epoch_str = template.format(
            epoch + 1,
            model.train_loss.result(),
            model.test_loss.result(),
            model.train_acc.result(),
            model.test_acc.result()
        )
        print(epoch_str)

        # Reset the metrics for the next epoch
        model.train_loss.reset_states()
        model.test_loss.reset_states()
        model.train_acc.reset_states()
        model.test_acc.reset_states()

```

**Comment by jvishnuvardhan** [comment]
@ziruizhuang Sorry for the late reply. I have updated some parts of your code such as removing `y_input`, `one_hot` etc. Now the code works as expected. [Here](https://colab.sandbox.google.com/gist/jvishnuvardhan/11beee9505007770ab8a750b4a567fdf/untitled733.ipynb) is the gist for your reference. These modifications are good for `loss=tf.keras.losses.SparseCategoricalCrossentropy()` but you can do similar things for `loss=tf.keras.losses.CategoricalCrossentropy()`. Thanks!

I am closing this issue as it was resolved. Please feel free to open a new issue related to this work. Thanks!

**Comment by ziruizhuang** [comment]
@jvishnuvardhan Thank you for the gist. Now I see how to make it work using SparseCategoricalCrossentropy loss and keras model. 

Still, a little more discussion on this topic. Is it a designed behavior that a keras model always produce floating point output? I mean it would be more straightforward using the following two sets of configuration:

 * Config 1
   - train_y/test_y are one_hot/probability vector (float), and y_output is probability vector (float)
   - use CategoricalCrossentropy
 * Config 2
   - train_y/test_y are integers, and y_output is integer as well
   - use SparseCategoricalCrossentropy 

Basically, if a model learns to produce integers, it produces integers; and if a model learns to produce floats, it produces floats. 

However, the current behavior is
 * Config 3
   - train_y/test_y are integers, and y_output is probability vector (float)
   - use SparseCategoricalCrossentropy 

That is to say, the model learns to produce integers, but it produces floats instead. 

And the exception thrown out is confusing if we ever try with Config 2. it says
`TypeError: Expected int64, got 1e-07 of type 'float' instead.`
which intuitively means something in the code should be int64 but we gave a really small float instead? In that sense, we should debug and find if something else should be cast to int64 in our code, which is the quite opposite of the reality.

**Comment by jvishnuvardhan** [comment]
@ziruizhuang Model generally output probabilities in classification. Please check a [tutorial](https://www.tensorflow.org/tutorials/quickstart/beginner) on `TF website`. If you want to predict classes, you can do 

`predictions = model.predict_classes(x_train)`

or

```
y_pred = model.predict(x_train)
predictions = tf.argmax(y_pred,axis=1)
```

Please post further questions in Stackoverflow. We will answer there. We want to keep this GitHub repository to address mainly bug/performance issues. Thanks!
