### ISSUE TITLE
TF Real Op Not Supported for TFLite when generating MFCCs

### ISSUE THREAD

**Issue by mattc-eostar** [tensorflow/tensorflow#33897]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.2
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (or github SHA if from source): 2.1.0-dev20191023

Code throwing error is from TF2.0 docs about generating MFCCs from audio. Using the SELECT_TF_OPS flag helps with RFFT and ComplexAbs, but now Real (assuming tf.math.real) is not able to convert. Is there any way to add a custom op for this or is there something I am missing?

```python
def generate_mfcc_features(audio_tensor):
    sample_rate = 16000.0

    # A 1024-point STFT with frames of 64 ms and 75% overlap.
    stfts = tf.signal.stft(audio_tensor, frame_length=1024, frame_step=256,fft_length=1024)
    spectrograms = tf.cast(tf.abs(stfts), tf.float32)

    # Warp the linear scale spectrograms into the mel-scale.
    num_spectrogram_bins = stfts.shape[-1]
    lower_edge_hertz, upper_edge_hertz, num_mel_bins = 80.0, 7600.0, 80
    linear_to_mel_weight_matrix = tf.cast(tf.signal.linear_to_mel_weight_matrix(num_mel_bins, num_spectrogram_bins, sample_rate, lower_edge_hertz, upper_edge_hertz), tf.float32)
    mel_spectrograms = tf.tensordot(spectrograms, linear_to_mel_weight_matrix, 1)
    mel_spectrograms.set_shape(spectrograms.shape[:-1].concatenate(linear_to_mel_weight_matrix.shape[-1:]))

    # Compute a stabilized log to get log-magnitude mel-scale spectrograms.
    log_mel_spectrograms = tf.math.log(mel_spectrograms + 1e-6)

    # Compute MFCCs from log_mel_spectrograms and take the first 13.
    return tf.signal.mfccs_from_log_mel_spectrograms(log_mel_spectrograms)[..., :13]
```
when converting like this:
```python
converter = tf.lite.TFLiteConverter.from_concrete_functions([enc_to_save])
# converter.optimizations = [tf.lite.Optimize.OPTIMIZE_FOR_SIZE]
converter.target_spec.supported_ops = set([tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS])
tflite_model_enc = converter.convert()
```

```
---------------------------------------------------------------------------
ConverterError                            Traceback (most recent call last)
<ipython-input-275-096221475907> in <module>()
      6 # converter.optimizations = [tf.lite.Optimize.OPTIMIZE_FOR_SIZE]
      7 converter.target_spec.supported_ops = set([tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS])
----> 8 tflite_model_enc = converter.convert()
      9 
     10 converter = tf.lite.TFLiteConverter.from_concrete_functions([dec_to_save])

~/anaconda3/envs/main/lib/python3.6/site-packages/tensorflow_core/lite/python/lite.py in convert(self)
    460         input_tensors=input_tensors,
    461         output_tensors=output_tensors,
--> 462         **converter_kwargs)
    463 
    464     if self._is_calibration_quantize():

~/anaconda3/envs/main/lib/python3.6/site-packages/tensorflow_core/lite/python/convert.py in toco_convert_impl(input_data, input_tensors, output_tensors, enable_mlir_converter, *args, **kwargs)
    450       input_data.SerializeToString(),
    451       debug_info_str=debug_info_str,
--> 452       enable_mlir_converter=enable_mlir_converter)
    453   return data
    454 

~/anaconda3/envs/main/lib/python3.6/site-packages/tensorflow_core/lite/python/convert.py in toco_convert_protos(model_flags_str, toco_flags_str, input_data_str, debug_info_str, enable_mlir_converter)
    201       stdout = _try_convert_to_unicode(stdout)
    202       stderr = _try_convert_to_unicode(stderr)
--> 203       raise ConverterError("See console for info.\n%s\n%s\n" % (stdout, stderr))
    204   finally:
    205     # Must manually cleanup files.

ConverterError: See console for info.
2019-10-31 16:49:07.859294: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: RFFT
2019-10-31 16:49:07.859376: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: ComplexAbs
2019-10-31 16:49:07.859438: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: RFFT
2019-10-31 16:49:07.859470: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Real
2019-10-31 16:49:07.879329: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 403 operators, 705 arrays (0 quantized)
2019-10-31 16:49:07.897088: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 403 operators, 705 arrays (0 quantized)
2019-10-31 16:49:08.185116: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 1: 351 operators, 648 arrays (0 quantized)
2019-10-31 16:49:08.199468: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 2: 350 operators, 647 arrays (0 quantized)
2019-10-31 16:49:08.213695: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Group bidirectional sequence lstm/rnn: 350 operators, 647 arrays (0 quantized)
2019-10-31 16:49:08.224572: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before dequantization graph transformations: 350 operators, 647 arrays (0 quantized)
2019-10-31 16:49:08.307894: I tensorflow/lite/toco/allocate_transient_arrays.cc:345] Total transient array allocated size: 384 bytes, theoretical optimal value: 192 bytes.
2019-10-31 16:49:08.309673: I tensorflow/lite/toco/toco_tooling.cc:454] Number of parameters: 3677275
2019-10-31 16:49:08.310492: W tensorflow/lite/toco/tflite/operator.cc:2024] Op Real is a valid TensorFlow op but has not been whitelisted for the TensorFlow Lite flex op set.
2019-10-31 16:49:08.311448: W tensorflow/lite/toco/tflite/operator.cc:2024] Op Real is a valid TensorFlow op but has not been whitelisted for the TensorFlow Lite flex op set.
2019-10-31 16:49:08.312363: E tensorflow/lite/toco/toco_tooling.cc:481] We are continually in the process of adding support to TensorFlow Lite for more ops. It would be helpful if you could inform us of how this conversion went by opening a github issue at https://github.com/tensorflow/tensorflow/issues/new?template=40-tflite-op-request.md
 and pasting the following:

Some of the operators in the model are not supported by the standard TensorFlow Lite runtime and are not recognized by TensorFlow. If you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, CONCATENATION, CONV_2D, EXPAND_DIMS, FLOOR_DIV, FULLY_CONNECTED, GATHER, LEAKY_RELU, LOG, LOGISTIC, MAXIMUM, MAX_POOL_2D, MUL, PACK, PAD, RANGE, RESHAPE, SHAPE, SPLIT, SPLIT_V, SQUEEZE, STRIDED_SLICE, SUB, TANH, TRANSPOSE, UNPACK. Here is a list of operators for which you will need custom implementations: Real.
Traceback (most recent call last):
  File "/home/mattc/anaconda3/envs/main/bin/toco_from_protos", line 10, in <module>
    sys.exit(main())
  File "/home/mattc/anaconda3/envs/main/lib/python3.6/site-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 93, in main
    app.run(main=execute, argv=[sys.argv[0]] + unparsed)
  File "/home/mattc/anaconda3/envs/main/lib/python3.6/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/mattc/anaconda3/envs/main/lib/python3.6/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/mattc/anaconda3/envs/main/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/home/mattc/anaconda3/envs/main/lib/python3.6/site-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 56, in execute
    enable_mlir_converter)
Exception: We are continually in the process of adding support to TensorFlow Lite for more ops. It would be helpful if you could inform us of how this conversion went by opening a github issue at https://github.com/tensorflow/tensorflow/issues/new?template=40-tflite-op-request.md
 and pasting the following:

Some of the operators in the model are not supported by the standard TensorFlow Lite runtime and are not recognized by TensorFlow. If you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, CONCATENATION, CONV_2D, EXPAND_DIMS, FLOOR_DIV, FULLY_CONNECTED, GATHER, LEAKY_RELU, LOG, LOGISTIC, MAXIMUM, MAX_POOL_2D, MUL, PACK, PAD, RANGE, RESHAPE, SHAPE, SPLIT, SPLIT_V, SQUEEZE, STRIDED_SLICE, SUB, TANH, TRANSPOSE, UNPACK. Here is a list of operators for which you will need custom implementations: Real.
```

**Comment by mattc-eostar** [comment]
Able to get tf lite converter to convert mfcc function. I was not able to before, but I can now. But now, an error occurs when I try to invoke the model. I am using the simplest model I can think of to test this.

```python
def extract_features(inputs):
    sample_rate = 16000.0

    # A 1024-point STFT with frames of 64 ms and 75% overlap.
    stfts = tf.signal.stft(inputs, frame_length=1024, frame_step=256, fft_length=1024)
    spectrograms = tf.abs(stfts)

    # Warp the linear scale spectrograms into the mel-scale.
    num_spectrogram_bins = stfts.shape[-1]
    lower_edge_hertz, upper_edge_hertz, num_mel_bins = 80.0, 7600.0, 80
    linear_to_mel_weight_matrix = tf.signal.linear_to_mel_weight_matrix(num_mel_bins, num_spectrogram_bins, sample_rate, lower_edge_hertz,upper_edge_hertz)
    mel_spectrograms = tf.tensordot(spectrograms, linear_to_mel_weight_matrix, 1)
    mel_spectrograms.set_shape(spectrograms.shape[:-1].concatenate(linear_to_mel_weight_matrix.shape[-1:]))

    # Compute a stabilized log to get log-magnitude mel-scale spectrograms.
    log_mel_spectrograms = tf.math.log(mel_spectrograms + 1e-6)

    # Compute MFCCs from log_mel_spectrograms and take the first 13.
    mfccs = tf.signal.mfccs_from_log_mel_spectrograms(log_mel_spectrograms)[..., :40]
    
    return log_mel_spectrograms

class NN(tf.keras.Model):
    def __init__(self):
        super(NN, self).__init__()
        
        self.mfcc = tf.keras.layers.Lambda(extract_features)

    def call(self, x):    
        return self.mfcc(x)
    
nn = NN()
nn.build((None,40000))

@tf.function
def evaluate(inp):
    return nn(inp)

input_shape = tf.TensorSpec([None,40000], tf.float32)
to_save = evaluate.get_concrete_function(input_shape)

converter = tf.lite.TFLiteConverter.from_concrete_functions([to_save])
# converter.experimental_new_converter = True
# converter.optimizations = [tf.lite.Optimize.OPTIMIZE_FOR_LATENCY]
converter.target_spec.supported_ops = set([tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS])
tflite_model = converter.convert()

interpreter = tf.lite.Interpreter(model_content=tflite_model)

# Get input and output tensors.
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

interpreter.allocate_tensors()

interpreter.set_tensor(input_details[0]['index'], tf.convert_to_tensor(np.expand_dims(audio_data, 0), dtype=tf.float32))

interpreter.invoke()

output = interpreter.get_tensor(output_details[0]['index'])
```

Error:
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-614-9e00ca7d4c6c> in <module>()
     56 interpreter.set_tensor(input_details[0]['index'], tf.convert_to_tensor(np.expand_dims(audio_data, 0), dtype=tf.float32))
     57 
---> 58 interpreter.invoke()
     59 
     60 output = interpreter.get_tensor(output_details[0]['index'])

~/anaconda3/envs/main/lib/python3.6/site-packages/tensorflow_core/lite/python/interpreter.py in invoke(self)
    491     """
    492     self._ensure_safe()
--> 493     self._interpreter.Invoke()
    494 
    495   def reset_all_variables(self):

~/anaconda3/envs/main/lib/python3.6/site-packages/tensorflow_core/lite/python/interpreter_wrapper/tensorflow_wrap_interpreter_wrapper.py in Invoke(self)
    111 
    112     def Invoke(self):
--> 113         return _tensorflow_wrap_interpreter_wrapper.InterpreterWrapper_Invoke(self)
    114 
    115     def InputIndices(self):

RuntimeError: tensorflow/lite/kernels/reshape.cc:66 num_input_elements != num_output_elements (14400 != 39936)Node number 17 (RESHAPE) failed to invoke.
```

**Comment by tpeet** [comment]
Couldn't reproduce the latest error based on your code. Could you explain how did you get it working yourself? Which version of TF? Did you use a custom build? I still got the same error as you did in your first comment:
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-7-815c57e120e7> in <module>
     61 interpreter.set_tensor(input_details[0]['index'], tf.convert_to_tensor(np.expand_dims(audio_data, 0), dtype=tf.float32))
     62 
---> 63 interpreter.invoke()
     64 
     65 output = interpreter.get_tensor(output_details[0]['index'])

/opt/anaconda/anaconda3/lib/python3.6/site-packages/tensorflow_core/lite/python/interpreter.py in invoke(self)
    451     """
    452     self._ensure_safe()
--> 453     self._interpreter.Invoke()
    454 
    455   def reset_all_variables(self):

/opt/anaconda/anaconda3/lib/python3.6/site-packages/tensorflow_core/lite/python/interpreter_wrapper/tensorflow_wrap_interpreter_wrapper.py in Invoke(self)
    107 
    108     def Invoke(self):
--> 109         return _tensorflow_wrap_interpreter_wrapper.InterpreterWrapper_Invoke(self)
    110 
    111     def InputIndices(self):

RuntimeError: Regular TensorFlow ops are not supported by this interpreter. Make sure you invoke the Flex delegate before inference.Node number 23 (FlexRFFT) failed to prepare.
```


With regards to your last problem (num_input_elements != num_output_elements), I'm currently debugging the same problem in my code. I'm also using `tf.stft` and `abs` functions for preprocessing. 

By `interpreter.get_tensor_details()` you can list all the nodes in the model. What is your 17th node? The one that seems to cause problems in my case is `StridedSlice`:
```
{'name': 'conv/PreProc/audio/stft/frame/StridedSlice',
  'index': 17,
  'shape': array([], dtype=int32),
  'dtype': numpy.float32,
  'quantization': (0.0, 0)},
```

**Comment by mattc-eostar** [comment]
I am using version `2.1.0-dev20191108`, a tf-nightly build.

Tensor details:
```
[{'name': 'ConstantFolding/nn_10/lambda_10/stft/frame/concat/values_1_const_axis_0',
  'index': 0,
  'shape': array([1, 1], dtype=int32),
  'dtype': numpy.int32,
  'quantization': (0.0, 0)},
 {'name': 'Identity',
  'index': 1,
  'shape': array([], dtype=int32),
  'dtype': numpy.float32,
  'quantization': (0.0, 0)},
 {'name': 'inp',
  'index': 2,
  'shape': array([    1, 40000], dtype=int32),
  'dtype': numpy.float32,
  'quantization': (0.0, 0)},
 {'name': 'nn_10/lambda_10/Abs',
  'index': 3,
  'shape': array([], dtype=int32),
  'dtype': numpy.float32,
  'quantization': (0.0, 0)},
 {'name': 'nn_10/lambda_10/Tensordot',
  'index': 4,
  'shape': array([], dtype=int32),
  'dtype': numpy.float32,
  'quantization': (0.0, 0)},
 {'name': 'nn_10/lambda_10/Tensordot/Const_2',
  'index': 5,
  'shape': array([1], dtype=int32),
  'dtype': numpy.int32,
  'quantization': (0.0, 0)},
 {'name': 'nn_10/lambda_10/Tensordot/GatherV2',
  'index': 6,
  'shape': array([], dtype=int32),
  'dtype': numpy.int32,
  'quantization': (0.0, 0)},
 {'name': 'nn_10/lambda_10/Tensordot/MatMul',
  'index': 7,
  'shape': array([], dtype=int32),
  'dtype': numpy.float32,
  'quantization': (0.0, 0)},
 {'name': 'nn_10/lambda_10/Tensordot/MatMul_bias',
  'index': 8,
  'shape': array([80], dtype=int32),
  'dtype': numpy.float32,
  'quantization': (0.0, 0)},
 {'name': 'nn_10/lambda_10/Tensordot/Reshape_1/transpose',
  'index': 9,
  'shape': array([ 80, 513], dtype=int32),
  'dtype': numpy.float32,
  'quantization': (0.0, 0)},
 {'name': 'nn_10/lambda_10/Tensordot/Shape',
  'index': 10,
  'shape': array([], dtype=int32),
  'dtype': numpy.int32,
  'quantization': (0.0, 0)},
 {'name': 'nn_10/lambda_10/Tensordot/concat_1',
  'index': 11,
  'shape': array([], dtype=int32),
  'dtype': numpy.int32,
  'quantization': (0.0, 0)},
 {'name': 'nn_10/lambda_10/Tensordot/free',
  'index': 12,
  'shape': array([2], dtype=int32),
  'dtype': numpy.int32,
  'quantization': (0.0, 0)},
 {'name': 'nn_10/lambda_10/add',
  'index': 13,
  'shape': array([], dtype=int32),
  'dtype': numpy.float32,
  'quantization': (0.0, 0)},
 {'name': 'nn_10/lambda_10/add/y',
  'index': 14,
  'shape': array([], dtype=int32),
  'dtype': numpy.float32,
  'quantization': (0.0, 0)},
 {'name': 'nn_10/lambda_10/stft/frame/GatherV2',
  'index': 15,
  'shape': array([], dtype=int32),
  'dtype': numpy.float32,
  'quantization': (0.0, 0)},
 {'name': 'nn_10/lambda_10/stft/frame/Maximum',
  'index': 16,
  'shape': array([], dtype=int32),
  'dtype': numpy.int32,
  'quantization': (0.0, 0)},
 {'name': 'nn_10/lambda_10/stft/frame/Maximum/x',
  'index': 17,
  'shape': array([], dtype=int32),
  'dtype': numpy.int32,
  'quantization': (0.0, 0)},
 {'name': 'nn_10/lambda_10/stft/frame/Reshape',
  'index': 18,
  'shape': array([], dtype=int32),
  'dtype': numpy.int32,
  'quantization': (0.0, 0)},
 {'name': 'nn_10/lambda_10/stft/frame/Reshape/shape',
  'index': 19,
  'shape': array([], dtype=int32),
  'dtype': numpy.int32,
  'quantization': (0.0, 0)},
 {'name': 'nn_10/lambda_10/stft/frame/Reshape_1',
  'index': 20,
  'shape': array([], dtype=int32),
  'dtype': numpy.float32,
  'quantization': (0.0, 0)},
 {'name': 'nn_10/lambda_10/stft/frame/Reshape_2',
  'index': 21,
  'shape': array([], dtype=int32),
  'dtype': numpy.int32,
  'quantization': (0.0, 0)},
 {'name': 'nn_10/lambda_10/stft/frame/Reshape_2/shape',
  'index': 22,
  'shape': array([2], dtype=int32),
  'dtype': numpy.int32,
  'quantization': (0.0, 0)},
 {'name': 'nn_10/lambda_10/stft/frame/Reshape_2/shape/1',
  'index': 23,
  'shape': array([], dtype=int32),
  'dtype': numpy.int32,
  'quantization': (0.0, 0)},
 {'name': 'nn_10/lambda_10/stft/frame/Reshape_3',
  'index': 24,
  'shape': array([1, 4], dtype=int32),
  'dtype': numpy.int32,
  'quantization': (0.0, 0)},
 {'name': 'nn_10/lambda_10/stft/frame/Reshape_4',
  'index': 25,
  'shape': array([], dtype=int32),
  'dtype': numpy.float32,
  'quantization': (0.0, 0)},
 {'name': 'nn_10/lambda_10/stft/frame/Shape',
  'index': 26,
  'shape': array([2], dtype=int32),
  'dtype': numpy.int32,
  'quantization': (0.0, 0)},
 {'name': 'nn_10/lambda_10/stft/frame/StridedSlice',
  'index': 27,
  'shape': array([], dtype=int32),
  'dtype': numpy.float32,
  'quantization': (0.0, 0)},
 {'name': 'nn_10/lambda_10/stft/frame/add_1',
  'index': 28,
  'shape': array([], dtype=int32),
  'dtype': numpy.int32,
  'quantization': (0.0, 0)},
 {'name': 'nn_10/lambda_10/stft/frame/add_1/x',
  'index': 29,
  'shape': array([], dtype=int32),
  'dtype': numpy.int32,
  'quantization': (0.0, 0)},
 {'name': 'nn_10/lambda_10/stft/frame/add_2',
  'index': 30,
  'shape': array([], dtype=int32),
  'dtype': numpy.int32,
  'quantization': (0.0, 0)},
 {'name': 'nn_10/lambda_10/stft/frame/concat',
  'index': 31,
  'shape': array([2], dtype=int32),
  'dtype': numpy.int32,
  'quantization': (0.0, 0)},
 {'name': 'nn_10/lambda_10/stft/frame/concat/values_1',
  'index': 32,
  'shape': array([1], dtype=int32),
  'dtype': numpy.int32,
  'quantization': (0.0, 0)},
 {'name': 'nn_10/lambda_10/stft/frame/concat_1',
  'index': 33,
  'shape': array([3], dtype=int32),
  'dtype': numpy.int32,
  'quantization': (0.0, 0)},
 {'name': 'nn_10/lambda_10/stft/frame/concat_1/values_1',
  'index': 34,
  'shape': array([2], dtype=int32),
  'dtype': numpy.int32,
  'quantization': (0.0, 0)},
 {'name': 'nn_10/lambda_10/stft/frame/concat_2',
  'index': 35,
  'shape': array([3], dtype=int32),
  'dtype': numpy.int32,
  'quantization': (0.0, 0)},
 {'name': 'nn_10/lambda_10/stft/frame/concat_2/values_1',
  'index': 36,
  'shape': array([2], dtype=int32),
  'dtype': numpy.int32,
  'quantization': (0.0, 0)},
 {'name': 'nn_10/lambda_10/stft/frame/floordiv',
  'index': 37,
  'shape': array([], dtype=int32),
  'dtype': numpy.int32,
  'quantization': (0.0, 0)},
 {'name': 'nn_10/lambda_10/stft/frame/floordiv_3',
  'index': 38,
  'shape': array([], dtype=int32),
  'dtype': numpy.int32,
  'quantization': (0.0, 0)},
 {'name': 'nn_10/lambda_10/stft/frame/gcd/Const',
  'index': 39,
  'shape': array([], dtype=int32),
  'dtype': numpy.int32,
  'quantization': (0.0, 0)},
 {'name': 'nn_10/lambda_10/stft/frame/mul',
  'index': 40,
  'shape': array([], dtype=int32),
  'dtype': numpy.int32,
  'quantization': (0.0, 0)},
 {'name': 'nn_10/lambda_10/stft/frame/ones_like',
  'index': 41,
  'shape': array([2], dtype=int32),
  'dtype': numpy.int32,
  'quantization': (0.0, 0)},
 {'name': 'nn_10/lambda_10/stft/frame/packed',
  'index': 42,
  'shape': array([3], dtype=int32),
  'dtype': numpy.int32,
  'quantization': (0.0, 0)},
 {'name': 'nn_10/lambda_10/stft/frame/range_1',
  'index': 43,
  'shape': array([], dtype=int32),
  'dtype': numpy.int32,
  'quantization': (0.0, 0)},
 {'name': 'nn_10/lambda_10/stft/frame/range_1/delta',
  'index': 44,
  'shape': array([], dtype=int32),
  'dtype': numpy.int32,
  'quantization': (0.0, 0)},
 {'name': 'nn_10/lambda_10/stft/frame/range_1/start',
  'index': 45,
  'shape': array([], dtype=int32),
  'dtype': numpy.int32,
  'quantization': (0.0, 0)},
 {'name': 'nn_10/lambda_10/stft/frame/split',
  'index': 46,
  'shape': array([1], dtype=int32),
  'dtype': numpy.int32,
  'quantization': (0.0, 0)},
 {'name': 'nn_10/lambda_10/stft/frame/split/split_dim',
  'index': 47,
  'shape': array([], dtype=int32),
  'dtype': numpy.int32,
  'quantization': (0.0, 0)},
 {'name': 'nn_10/lambda_10/stft/frame/split:1',
  'index': 48,
  'shape': array([1], dtype=int32),
  'dtype': numpy.int32,
  'quantization': (0.0, 0)},
 {'name': 'nn_10/lambda_10/stft/frame/split:2',
  'index': 49,
  'shape': array([0], dtype=int32),
  'dtype': numpy.int32,
  'quantization': (0.0, 0)},
 {'name': 'nn_10/lambda_10/stft/frame/sub_2',
  'index': 50,
  'shape': array([], dtype=int32),
  'dtype': numpy.int32,
  'quantization': (0.0, 0)},
 {'name': 'nn_10/lambda_10/stft/frame/zeros_like',
  'index': 51,
  'shape': array([2], dtype=int32),
  'dtype': numpy.int32,
  'quantization': (0.0, 0)},
 {'name': 'nn_10/lambda_10/stft/frame_length',
  'index': 52,
  'shape': array([], dtype=int32),
  'dtype': numpy.int32,
  'quantization': (0.0, 0)},
 {'name': 'nn_10/lambda_10/stft/frame_step',
  'index': 53,
  'shape': array([], dtype=int32),
  'dtype': numpy.int32,
  'quantization': (0.0, 0)},
 {'name': 'nn_10/lambda_10/stft/hann_window/sub_2',
  'index': 54,
  'shape': array([1024], dtype=int32),
  'dtype': numpy.float32,
  'quantization': (0.0, 0)},
 {'name': 'nn_10/lambda_10/stft/mul',
  'index': 55,
  'shape': array([], dtype=int32),
  'dtype': numpy.float32,
  'quantization': (0.0, 0)},
 {'name': 'nn_10/lambda_10/stft/rfft',
  'index': 56,
  'shape': array([], dtype=int32),
  'dtype': numpy.complex64,
  'quantization': (0.0, 0)},
 {'name': 'nn_10/lambda_10/stft/rfft/packed',
  'index': 57,
  'shape': array([1], dtype=int32),
  'dtype': numpy.int32,
  'quantization': (0.0, 0)}]
```

**Comment by fmbao** [comment]
I face the same problem

**Comment by fmbao** [comment]
I solve the problem. I need set_tensor to two params .

**Comment by juunnn** [comment]
hey @fmbao how exactly you solve the problem? you set_tensor with what? thank you

**Comment by haozha111** [comment]
hi, does the original issue resolve?
