### ISSUE TITLE
custom object detection data set tflite_convert

### ISSUE THREAD

**Issue by ozzcet** [tensorflow/tensorflow#33952]
I have followed "https://medium.com/tensorflow/training-and-serving-a-realtime-mobile-object-detector-in-30-minutes-with-cloud-tpus-b78971cf1193" with "ssd_mobilenet_v1_quantized_300x300_coco14_sync_2018_07_18.tar.gz" model... Only thing I have changed bazel to tflite_convert . I have prepared 300x300x3 labeled images and trained. after trained i have generated frozen_graph. pb file to check on jupyter notebook and wola it runs ... After that I have used below code  to produce tflite_graph.pbtxt and tflite_graph.pb files . 

"python export_tflite_ssd_graph.py --pipeline_config_path training/pipeline.config --trained_checkpoint_prefix training/model.ckpt-2927 --output_directory export_tflite_ssd_graph/tflite --add_postprocessing_op true"

Finally I have used below code to get detect.tflite file and bomm. Nothing happen when I have started https://github.com/tensorflow/examples/tree/master/lite/examples/object_detection/android that project on android studio.  The project perfectly runs own original detect.tflite file....

"D:\First\Projects\visionApi\START\models\research\object_detection>tflite_convert  --output_file export_tflite_ssd_graph/tflite/detect.tflite --input_shapes 1,300,300,3 --input_arrays normalized_input_image_tensor --output_arrays "TFLite_Detection_PostProcess" "TFLite_Detection_PostProcess:1" "TFLite_Detection_PostProcess:2" "FLite_Detection_PostProcess:3" --mean_values 128 --std_dev_values 127 --allow_custom_ops --graph_def_file export_tflite_ssd_graph/tflite/tflite_graph.pb change_concat_input_ranges false --inference_type FLOAT "

Above code generate a detect.tflite file but it did not run on above android project. 

How could I do correctly ? please help.

After that I tried to change code as below.... and get that error...

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): windows 10 
- TensorFlow installed from (source or binary):  binary
- TensorFlow version (or github SHA if from source): 1.13.1

**Provide the text output from tflite_convert**

```
D:\First\Projects\visionApi\START\models\research\object_detection>tflite_convert  --output_file export_tflite_ssd_graph/tflite/detect.tflite --input_shapes 1,300,300,3 --input_arrays normalized_input_image_tensor --output_arrays "TFLite_Detection_PostProcess" "TFLite_Detection_PostProcess:1" "TFLite_Detection_PostProcess:2" "FLite_Detection_PostProcess:3" --mean_values 128 --std_dev_values 127 --allow_custom_ops --graph_def_file export_tflite_ssd_graph/tflite/tflite_graph.pb change_concat_input_ranges false --inference_type QUANTIZED_UINT8

2019-11-03 19:04:05.430457: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2019-11-03 19:04:06.351615: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties:
name: GeForce GTX 1060 major: 6 minor: 1 memoryClockRate(GHz): 1.6705
pciBusID: 0000:01:00.0
totalMemory: 6.00GiB freeMemory: 4.97GiB
2019-11-03 19:04:06.358836: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2019-11-03 19:04:06.856355: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-11-03 19:04:06.860494: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0
2019-11-03 19:04:06.863385: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N
2019-11-03 19:04:06.867189: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 4716 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1060, pci bus id: 0000:01:00.0, compute capability: 6.1)
Traceback (most recent call last):
  File "c:\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python\Python37\Scripts\tflite_convert.exe\__main__.py", line 9, in <module>
  File "c:\python\python37\lib\site-packages\tensorflow\lite\python\tflite_convert.py", line 442, in main
    app.run(main=run_main, argv=sys.argv[:1])
  File "c:\python\python37\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "c:\python\python37\lib\site-packages\tensorflow\lite\python\tflite_convert.py", line 438, in run_main
    _convert_model(tflite_flags)
  File "c:\python\python37\lib\site-packages\tensorflow\lite\python\tflite_convert.py", line 191, in _convert_model
    output_data = converter.convert()
  File "c:\python\python37\lib\site-packages\tensorflow\lite\python\lite.py", line 461, in convert
    **converter_kwargs)
  File "c:\python\python37\lib\site-packages\tensorflow\lite\python\convert.py", line 411, in toco_convert_graph_def
    input_data.SerializeToString())
  File "c:\python\python37\lib\site-packages\tensorflow\lite\python\convert.py", line 205, in toco_convert_protos
    "TOCO failed. See console for info.\n%s\n%s\n" % (stdout, stderr))
tensorflow.lite.python.convert.ConverterError: TOCO failed. See console for info.
2019-11-03 19:04:08.261635: I tensorflow/lite/toco/import_tensorflow.cc:1324] Converting unsupported operation: TFLite_Detection_PostProcess
2019-11-03 19:04:08.262132: E tensorflow/core/framework/op_kernel.cc:1325] OpKernel ('op: "WrapDatasetVariant" device_type: "CPU"') for unknown op: WrapDatasetVariant
2019-11-03 19:04:08.262371: E tensorflow/core/framework/op_kernel.cc:1325] OpKernel ('op: "WrapDatasetVariant" device_type: "GPU" host_memory_arg: "input_handle" host_memory_arg: "output_handle"') for unknown op: WrapDatasetVariant
2019-11-03 19:04:08.262670: E tensorflow/core/framework/op_kernel.cc:1325] OpKernel ('op: "UnwrapDatasetVariant" device_type: "CPU"') for unknown op: UnwrapDatasetVariant
2019-11-03 19:04:08.262925: E tensorflow/core/framework/op_kernel.cc:1325] OpKernel ('op: "UnwrapDatasetVariant" device_type: "GPU" host_memory_arg: "input_handle" host_memory_arg: "output_handle"') for unknown op: UnwrapDatasetVariant
2019-11-03 19:04:08.289925: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 878 operators, 1279 arrays (0 quantized)
2019-11-03 19:04:08.342088: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 878 operators, 1279 arrays (0 quantized)
2019-11-03 19:04:08.405873: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 1: 100 operators, 259 arrays (1 quantized)
2019-11-03 19:04:08.408766: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before pre-quantization graph transformations: 100 operators, 259 arrays (1 quantized)
2019-11-03 19:04:08.410769: F tensorflow/lite/toco/tooling_util.cc:1702] Array FeatureExtractor/MobilenetV2/Conv/Relu6, which is an input to the DepthwiseConv operator producing the output array FeatureExtractor/MobilenetV2/expanded_conv/depthwise/Relu6, is lacking min/max data, which is necessary for quantization. If accuracy matters, either target a non-quantized output format, or run quantized training with your model from a floating point checkpoint to change the input graph to contain min/max information. If you don't care about accuracy, you can pass --default_ranges_min= and --default_ranges_max= for easy experimentation.
```

**Comment by ozzcet** [comment]
Hi again,

I have tried again and again and nothing change. Last time what I have done with 600x800 labeled images data set.
 

(windows 10 operations)
Firstly, I have downloaded http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v2_coco_2018_03_29.tar.gz

And get https://github.com/tensorflow/models/tree/master/research/object_detection from githuband train it  with 
that code:
 "python train.py --logtostderr -train_dir=training/ --pipeline_config_path=inference_graph/pipeline.config"
 after over 19000 step ı have stoped it. And I have produce frozen graph
 with that code :
"python export_inference_graph.py --input_type image_tensor --pipeline_config_path training/ssd_mobilenet_v2_coco.config --trained_checkpoint_prefix training/model.ckpt-19410 --output_directory inference_graph"

after that I have got "frozen_inference_graph.pb" file in to the  "object_detection_tutorial.ipynb" note book where stay inside of  the object_detection folder to test my training working or not. Yes I see many times it is working wery well.

 Than, to produce *.tflite file  I have use 
that code:
"python export_tflite_ssd_graph.py --pipeline_config_path training/ssd_mobilenet_v2_coco.config --trained_checkpoint_prefix training/model.ckpt-19410 --output_directory export_tflite_ssd_graph/tflte --add_postprocessing_op true"
It produced two file in the drectory of "tflte" these are  "tflite_graph.pb" and "tflite_graph.pbtxt"

by taking that files ı have use that code to produce "detect.tflite" file 
"tflite_convert  --graph_def_file export_tflite_ssd_graph/tflte/tflite_graph.pb --output_file export_tflite_ssd_graph/tflte/detect.tflite  --input_shapes 1,300,300,3 --input_arrays "normalized_input_image_tensor" --output_arrays "TFLite_Detection_PostProcess" "TFLite_Detection_PostProcess:1" "TFLite_Detection_PostProcess:2" "TFLite_Detection_PostProcess:3" --inference_type FLOAT --allow_custom_ops"
that code  produce detect.tflite file in that drectory. After that I have get it android project from "https://github.com/tensorflow/examples/tree/master/lite/examples/object_detection/android"
and changed assets files with mine "detect.tflite" and "labelmap.txt" file  howewer nothing happen when i started android emulator. App appear on the emulator with tflite banner but nothing happen it acting like taking video, only i saw opening camera nothing detecting... 

On the other hand when i use that project "https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/android"
I could directly use "frozen_inference_graph.pb" file in that project and it is working.

But I have to generate tflite file to use it in the react native project. 

Please help me ...


Best regards.

**Comment by ozzcet** [comment]
Thank you so much... I have already solved that issue you can close it. 

Best Regards.

**Comment by vikas4707** [comment]
Hi did you solved the above issue , i did the same , got the detect.tflite , but when i am using in android , the detection is not showing result which i was getting in python . please help me
