### ISSUE TITLE
TensorFlow Lite currently doesn't support control flow ops: Merge, Switch. 

### ISSUE THREAD

**Issue by VanNamMan** [tensorflow/tensorflow#34034]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Ubuntu 18.04.3 LTS
- TensorFlow installed from (source or binary):source
- TensorFlow version (or github SHA if from source):1.15.0

**Provide the text output from tflite_convert**

2019-11-06 14:51:12.818885: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX
WARNING:tensorflow:From /home/mannam-pc/.local/lib/python3.6/site-packages/tensorflow_core/lite/python/convert_saved_model.py:60: load (from tensorflow.python.saved_model.loader_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.loader.load or tf.compat.v1.saved_model.load. There will be a new function for importing SavedModels in Tensorflow 2.0.
2019-11-06 14:51:14.238827: I tensorflow/core/grappler/devices.cc:60] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0 (Note: TensorFlow was not compiled with CUDA support)
2019-11-06 14:51:14.239039: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2019-11-06 14:51:14.342213: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:786] Optimization results for grappler item: graph_to_optimize
2019-11-06 14:51:14.342263: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:788]   function_optimizer: function_optimizer did nothing. time = 0.003ms.
2019-11-06 14:51:14.342276: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:788]   function_optimizer: function_optimizer did nothing. time = 0ms.
2019-11-06 14:51:17.338864: I tensorflow/core/grappler/devices.cc:60] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0 (Note: TensorFlow was not compiled with CUDA support)
2019-11-06 14:51:17.338999: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2019-11-06 14:51:17.758703: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:786] Optimization results for grappler item: graph_to_optimize
2019-11-06 14:51:17.758752: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:788]   constant_folding: Graph size after: 1632 nodes (-1290), 2168 edges (-1454), time = 256.269ms.
2019-11-06 14:51:17.758768: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:788]   constant_folding: Graph size after: 1632 nodes (0), 2168 edges (0), time = 73.402ms.
Traceback (most recent call last):
  File "tflite_converter.py", line 40, in <module>
    tflite_model_quant = converter.convert()
  File "/home/mannam-pc/.local/lib/python3.6/site-packages/tensorflow_core/lite/python/lite.py", line 983, in convert
    **converter_kwargs)
  File "/home/mannam-pc/.local/lib/python3.6/site-packages/tensorflow_core/lite/python/convert.py", line 449, in toco_convert_impl
    enable_mlir_converter=enable_mlir_converter)
  File "/home/mannam-pc/.local/lib/python3.6/site-packages/tensorflow_core/lite/python/convert.py", line 200, in toco_convert_protos
    raise ConverterError("See console for info.\n%s\n%s\n" % (stdout, stderr))
tensorflow.lite.python.convert.ConverterError: See console for info.
2019-11-06 14:51:20.478994: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2019-11-06 14:51:20.479075: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2019-11-06 14:51:20.479089: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2019-11-06 14:51:20.479101: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2019-11-06 14:51:20.479122: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2019-11-06 14:51:20.479135: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2019-11-06 14:51:20.479196: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayV3
2019-11-06 14:51:20.479212: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2019-11-06 14:51:20.479236: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayV3
2019-11-06 14:51:20.479245: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2019-11-06 14:51:20.479256: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2019-11-06 14:51:20.479270: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2019-11-06 14:51:20.479279: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2019-11-06 14:51:20.479287: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2019-11-06 14:51:20.479299: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2019-11-06 14:51:20.479309: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2019-11-06 14:51:20.479320: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayScatterV3
2019-11-06 14:51:20.479334: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2019-11-06 14:51:20.479345: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: LoopCond
2019-11-06 14:51:20.479366: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Exit
2019-11-06 14:51:20.479425: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayReadV3
2019-11-06 14:51:20.479439: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArraySizeV3
2019-11-06 14:51:20.479472: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: ParseSingleExample
2019-11-06 14:51:20.479499: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayGatherV3
2019-11-06 14:51:20.479541: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayV3
2019-11-06 14:51:20.479552: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2019-11-06 14:51:20.479564: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayV3
2019-11-06 14:51:20.479574: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2019-11-06 14:51:20.479586: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayV3
2019-11-06 14:51:20.479595: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2019-11-06 14:51:20.479606: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2019-11-06 14:51:20.479622: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2019-11-06 14:51:20.479632: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2019-11-06 14:51:20.479642: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2019-11-06 14:51:20.479654: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2019-11-06 14:51:20.479664: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2019-11-06 14:51:20.479673: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2019-11-06 14:51:20.479685: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2019-11-06 14:51:20.479695: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2019-11-06 14:51:20.479707: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayScatterV3
2019-11-06 14:51:20.479726: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2019-11-06 14:51:20.479740: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: LoopCond
2019-11-06 14:51:20.479763: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Exit
2019-11-06 14:51:20.479776: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Exit
2019-11-06 14:51:20.479804: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayReadV3
2019-11-06 14:51:20.479817: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArraySizeV3
2019-11-06 14:51:20.479827: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArraySizeV3
2019-11-06 14:51:20.479846: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayWriteV3
2019-11-06 14:51:20.479875: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayGatherV3
2019-11-06 14:51:20.479889: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayGatherV3
2019-11-06 14:51:20.479917: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayWriteV3
2019-11-06 14:51:20.479984: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: DecodeRaw
2019-11-06 14:51:20.480005: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Substr
2019-11-06 14:51:20.480058: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: DecodeJpeg
2019-11-06 14:51:20.480074: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Substr
2019-11-06 14:51:20.480086: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Substr
2019-11-06 14:51:20.480138: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Substr
2019-11-06 14:51:20.480161: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: DecodeJpeg
2019-11-06 14:51:20.480195: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: DecodePng
2019-11-06 14:51:20.480262: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Substr
2019-11-06 14:51:20.480284: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: DecodeGif
2019-11-06 14:51:20.480303: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: DecodeBmp
2019-11-06 14:51:20.480349: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayWriteV3
2019-11-06 14:51:20.481401: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayV3
2019-11-06 14:51:20.481417: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2019-11-06 14:51:20.481430: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayV3
2019-11-06 14:51:20.481441: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2019-11-06 14:51:20.481453: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayV3
2019-11-06 14:51:20.481463: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2019-11-06 14:51:20.481473: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayV3
2019-11-06 14:51:20.481483: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2019-11-06 14:51:20.481495: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayV3
2019-11-06 14:51:20.481504: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2019-11-06 14:51:20.481515: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayV3
2019-11-06 14:51:20.481525: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2019-11-06 14:51:20.481536: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayV3
2019-11-06 14:51:20.481546: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2019-11-06 14:51:20.481557: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayV3
2019-11-06 14:51:20.481566: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2019-11-06 14:51:20.481577: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayV3
2019-11-06 14:51:20.481587: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2019-11-06 14:51:20.481598: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayV3
2019-11-06 14:51:20.481607: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2019-11-06 14:51:20.481618: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2019-11-06 14:51:20.481633: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2019-11-06 14:51:20.481644: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2019-11-06 14:51:20.481653: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayScatterV3
2019-11-06 14:51:20.481665: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2019-11-06 14:51:20.481675: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2019-11-06 14:51:20.481685: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayScatterV3
2019-11-06 14:51:20.481696: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2019-11-06 14:51:20.481706: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2019-11-06 14:51:20.481716: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayScatterV3
2019-11-06 14:51:20.481727: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2019-11-06 14:51:20.481737: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2019-11-06 14:51:20.481746: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2019-11-06 14:51:20.481756: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2019-11-06 14:51:20.481766: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2019-11-06 14:51:20.481777: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2019-11-06 14:51:20.481787: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2019-11-06 14:51:20.481797: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2019-11-06 14:51:20.481808: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2019-11-06 14:51:20.481823: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2019-11-06 14:51:20.481833: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2019-11-06 14:51:20.481844: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2019-11-06 14:51:20.481855: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2019-11-06 14:51:20.481865: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2019-11-06 14:51:20.481877: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2019-11-06 14:51:20.481886: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2019-11-06 14:51:20.481896: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2019-11-06 14:51:20.481907: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2019-11-06 14:51:20.481917: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2019-11-06 14:51:20.481929: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayScatterV3
2019-11-06 14:51:20.481943: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2019-11-06 14:51:20.481955: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2019-11-06 14:51:20.481967: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2019-11-06 14:51:20.481998: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2019-11-06 14:51:20.482011: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: LoopCond
2019-11-06 14:51:20.482039: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Exit
2019-11-06 14:51:20.482053: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Exit
2019-11-06 14:51:20.482065: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Exit
2019-11-06 14:51:20.482077: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Exit
2019-11-06 14:51:20.482089: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Exit
2019-11-06 14:51:20.482462: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayReadV3
2019-11-06 14:51:20.482478: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayReadV3
2019-11-06 14:51:20.482490: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayReadV3
2019-11-06 14:51:20.482502: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayReadV3
2019-11-06 14:51:20.482513: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArraySizeV3
2019-11-06 14:51:20.482524: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArraySizeV3
2019-11-06 14:51:20.482534: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArraySizeV3
2019-11-06 14:51:20.482544: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArraySizeV3
2019-11-06 14:51:20.482555: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArraySizeV3
2019-11-06 14:51:20.482565: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayScatterV3
2019-11-06 14:51:20.482612: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2019-11-06 14:51:20.482629: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayGatherV3
2019-11-06 14:51:20.482642: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayGatherV3
2019-11-06 14:51:20.482655: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayGatherV3
2019-11-06 14:51:20.482667: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayGatherV3
2019-11-06 14:51:20.482680: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayGatherV3
2019-11-06 14:51:20.482691: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayReadV3
2019-11-06 14:51:20.482749: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: NonMaxSuppressionV5
2019-11-06 14:51:20.482798: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Size
2019-11-06 14:51:20.482893: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Size
2019-11-06 14:51:20.482945: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayWriteV3
2019-11-06 14:51:20.483080: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayWriteV3
2019-11-06 14:51:20.483096: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayWriteV3
2019-11-06 14:51:20.483113: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayWriteV3
2019-11-06 14:51:20.483125: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayWriteV3
2019-11-06 14:51:20.509188: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 1122 operators, 2035 arrays (0 quantized)
2019-11-06 14:51:20.575870: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After Removing unused ops pass 1: 1085 operators, 1966 arrays (0 quantized)
2019-11-06 14:51:20.648615: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 1085 operators, 1966 arrays (0 quantized)
2019-11-06 14:51:20.729953: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 1: 583 operators, 1191 arrays (0 quantized)
2019-11-06 14:51:20.751767: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Group bidirectional sequence lstm/rnn: 583 operators, 1191 arrays (0 quantized)
2019-11-06 14:51:20.769313: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before dequantization graph transformations: 583 operators, 1191 arrays (0 quantized)
2019-11-06 14:51:20.801282: I tensorflow/lite/toco/allocate_transient_arrays.cc:345] Total transient array allocated size: 896 bytes, theoretical optimal value: 896 bytes.
2019-11-06 14:51:20.804680: I tensorflow/lite/toco/toco_tooling.cc:454] Number of parameters: 4600257
2019-11-06 14:51:20.806064: W tensorflow/lite/toco/tflite/operator.cc:2706] Op DecodeRaw is a valid TensorFlow op but has not been whitelisted for the TensorFlow Lite flex op set.
2019-11-06 14:51:20.806081: W tensorflow/lite/toco/tflite/operator.cc:2706] Op Substr is a valid TensorFlow op but has not been whitelisted for the TensorFlow Lite flex op set.
2019-11-06 14:51:20.806102: W tensorflow/lite/toco/tflite/operator.cc:2706] Op DecodeJpeg is a valid TensorFlow op but has not been whitelisted for the TensorFlow Lite flex op set.
2019-11-06 14:51:20.806111: W tensorflow/lite/toco/tflite/operator.cc:2706] Op Substr is a valid TensorFlow op but has not been whitelisted for the TensorFlow Lite flex op set.
2019-11-06 14:51:20.806120: W tensorflow/lite/toco/tflite/operator.cc:2706] Op Substr is a valid TensorFlow op but has not been whitelisted for the TensorFlow Lite flex op set.
2019-11-06 14:51:20.806131: W tensorflow/lite/toco/tflite/operator.cc:2706] Op Substr is a valid TensorFlow op but has not been whitelisted for the TensorFlow Lite flex op set.
2019-11-06 14:51:20.806141: W tensorflow/lite/toco/tflite/operator.cc:2706] Op DecodeJpeg is a valid TensorFlow op but has not been whitelisted for the TensorFlow Lite flex op set.
2019-11-06 14:51:20.806150: W tensorflow/lite/toco/tflite/operator.cc:2706] Op DecodePng is a valid TensorFlow op but has not been whitelisted for the TensorFlow Lite flex op set.
2019-11-06 14:51:20.806161: W tensorflow/lite/toco/tflite/operator.cc:2706] Op DecodeGif is a valid TensorFlow op but has not been whitelisted for the TensorFlow Lite flex op set.
2019-11-06 14:51:20.806343: W tensorflow/lite/toco/tflite/operator.cc:2706] Op NonMaxSuppressionV5 is a valid TensorFlow op but has not been whitelisted for the TensorFlow Lite flex op set.
2019-11-06 14:51:20.806600: W tensorflow/lite/toco/tflite/operator.cc:2706] Op DecodeRaw is a valid TensorFlow op but has not been whitelisted for the TensorFlow Lite flex op set.
2019-11-06 14:51:20.806614: W tensorflow/lite/toco/tflite/operator.cc:2706] Op Substr is a valid TensorFlow op but has not been whitelisted for the TensorFlow Lite flex op set.
2019-11-06 14:51:20.806635: W tensorflow/lite/toco/tflite/operator.cc:2706] Op DecodeJpeg is a valid TensorFlow op but has not been whitelisted for the TensorFlow Lite flex op set.
2019-11-06 14:51:20.806644: W tensorflow/lite/toco/tflite/operator.cc:2706] Op Substr is a valid TensorFlow op but has not been whitelisted for the TensorFlow Lite flex op set.
2019-11-06 14:51:20.806653: W tensorflow/lite/toco/tflite/operator.cc:2706] Op Substr is a valid TensorFlow op but has not been whitelisted for the TensorFlow Lite flex op set.
2019-11-06 14:51:20.806664: W tensorflow/lite/toco/tflite/operator.cc:2706] Op Substr is a valid TensorFlow op but has not been whitelisted for the TensorFlow Lite flex op set.
2019-11-06 14:51:20.806674: W tensorflow/lite/toco/tflite/operator.cc:2706] Op DecodeJpeg is a valid TensorFlow op but has not been whitelisted for the TensorFlow Lite flex op set.
2019-11-06 14:51:20.806684: W tensorflow/lite/toco/tflite/operator.cc:2706] Op DecodePng is a valid TensorFlow op but has not been whitelisted for the TensorFlow Lite flex op set.
2019-11-06 14:51:20.806696: W tensorflow/lite/toco/tflite/operator.cc:2706] Op DecodeGif is a valid TensorFlow op but has not been whitelisted for the TensorFlow Lite flex op set.
2019-11-06 14:51:20.806892: W tensorflow/lite/toco/tflite/operator.cc:2706] Op NonMaxSuppressionV5 is a valid TensorFlow op but has not been whitelisted for the TensorFlow Lite flex op set.
2019-11-06 14:51:20.807143: E tensorflow/lite/toco/toco_tooling.cc:481] We are continually in the process of adding support to TensorFlow Lite for more ops. It would be helpful if you could inform us of how this conversion went by opening a github issue at https://github.com/tensorflow/tensorflow/issues/new?template=40-tflite-op-request.md
 and pasting the following:

TensorFlow Lite currently doesn't support control flow ops: Merge, Switch. We are working on supporting control flow ops, please see github issue at https://github.com/tensorflow/tensorflow/issues/28485. Some of the operators in the model are not supported by the standard TensorFlow Lite runtime and are not recognized by TensorFlow. If you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, CAST, CONCATENATION, CONV_2D, DEPTHWISE_CONV_2D, EQUAL, EXP, EXPAND_DIMS, FILL, GATHER, GREATER, GREATER_EQUAL, LESS, LOGICAL_AND, LOGICAL_OR, LOGISTIC, MAXIMUM, MINIMUM, MUL, PACK, PAD, RANGE, RESHAPE, RESIZE_BILINEAR, SELECT, SHAPE, SLICE, SPLIT, SQUEEZE, STRIDED_SLICE, SUB, SUM, TILE, TOPK_V2, TRANSPOSE, UNPACK, WHERE, ZEROS_LIKE. Here is a list of operators for which you will need custom implementations: DecodeGif, DecodeJpeg, DecodePng, DecodeRaw, NonMaxSuppressionV5, Substr.
Traceback (most recent call last):
  File "/home/mannam-pc/.local/bin/toco_from_protos", line 8, in <module>
    sys.exit(main())
  File "/home/mannam-pc/.local/lib/python3.6/site-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 89, in main
    app.run(main=execute, argv=[sys.argv[0]] + unparsed)
  File "/home/mannam-pc/.local/lib/python3.6/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/mannam-pc/.local/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/mannam-pc/.local/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/home/mannam-pc/.local/lib/python3.6/site-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 52, in execute
    enable_mlir_converter)
Exception: We are continually in the process of adding support to TensorFlow Lite for more ops. It would be helpful if you could inform us of how this conversion went by opening a github issue at https://github.com/tensorflow/tensorflow/issues/new?template=40-tflite-op-request.md
 and pasting the following:

TensorFlow Lite currently doesn't support control flow ops: Merge, Switch. We are working on supporting control flow ops, please see github issue at https://github.com/tensorflow/tensorflow/issues/28485. Some of the operators in the model are not supported by the standard TensorFlow Lite runtime and are not recognized by TensorFlow. If you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, CAST, CONCATENATION, CONV_2D, DEPTHWISE_CONV_2D, EQUAL, EXP, EXPAND_DIMS, FILL, GATHER, GREATER, GREATER_EQUAL, LESS, LOGICAL_AND, LOGICAL_OR, LOGISTIC, MAXIMUM, MINIMUM, MUL, PACK, PAD, RANGE, RESHAPE, RESIZE_BILINEAR, SELECT, SHAPE, SLICE, SPLIT, SQUEEZE, STRIDED_SLICE, SUB, SUM, TILE, TOPK_V2, TRANSPOSE, UNPACK, WHERE, ZEROS_LIKE. Here is a list of operators for which you will need custom implementations: DecodeGif, DecodeJpeg, DecodePng, DecodeRaw, NonMaxSuppressionV5, Substr.

Also, please include a link to a GraphDef or the model if possible.

https://drive.google.com/drive/folders/1gamFb0Lr6vJV7wYwHXJIhbFjk-jg_cpj?usp=sharing

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

Here is my source code :

https://drive.google.com/open?id=1EbJjiK6EAGqKhzrCXFBTZOuHcR6OiBdQ

**Comment by OriAlpha** [comment]
Hi, even I am facing these issues while converting the model to Tflite versions. Any solutions for this

**Comment by Boudegga** [comment]
hello, i have the same problem.
did you resolve this problem of unsupported control flow ops: Merge, Switch by tensorflow lite?

**Comment by VanNamMan** [comment]
> hello, i have the same problem.
> did you resolve this problem of unsupported control flow ops: Merge, Switch by tensorflow lite?

I have not been able to solve this problem yet

**Comment by haozha111** [comment]
TF Lite doesn't support v1 style control flow (switch, merge), but we support v2 control flow(while, if).

Can you rebuild your model with latest version of tensorflow and then try use our new mlir-based converter?

more details : https://groups.google.com/a/tensorflow.org/forum/#!topic/tflite/C7Ag0sUrLYg
