### ISSUE TITLE
Unsupported numpy type: NPY_LONGLONG

### ISSUE THREAD

**Issue by chrism0dwk** [tensorflow/tensorflow#34043]
**System information**
Linux Mint 19
Dell XPS 7590 laptop
Python 3.7.4 Anaconda
Tensorflow version: v2.0.0-rc2-26-g64c3d38 2.0.0 (pip tensorflow-gpu with GPU disabled)
Numpy version: 1.17.3

**Describe the current behavior**
Tensorflow 2.0 raises a ValueError if a Numpy array of type np.longlong is converted to a tf.Tensor.

**Describe the expected behavior**
A np.array(dtype=np.longlong) should automatically convert to tf.Tensor(dtype=np.int64), as was the case in Tensorflow 1.15.

**Code to reproduce the issue**
```python
>>> import numpy as np
>>> import tensorflow as tf
>>> x = np.ones(10, dtype=np.longlong)
>>> x_tf = tf.convert_to_tensor(x)
Traceback (most recent call last):
  File "/home/wibble/.conda/envs/drum-model/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-24-31172ca6f870>", line 1, in <module>
    tf.constant(x)
  File "/home/wibble/.conda/envs/drum-model/lib/python3.7/site-packages/tensorflow_core/python/framework/constant_op.py", line 227, in constant
    allow_broadcast=True)
  File "/home/wibble/.conda/envs/drum-model/lib/python3.7/site-packages/tensorflow_core/python/framework/constant_op.py", line 235, in _constant_impl
    t = convert_to_eager_tensor(value, ctx, dtype)
  File "/home/wibble/.conda/envs/drum-model/lib/python3.7/site-packages/tensorflow_core/python/framework/constant_op.py", line 96, in convert_to_eager_tensor
    return ops.EagerTensor(value, ctx.device_name, dtype)
ValueError: Failed to convert a NumPy array to a Tensor (Unsupported numpy type: NPY_LONGLONG).
```

**Comment by gadagashwini** [comment]
@chrism0dwk, Thanks for reporting this issue.
Issue is replicating on colab with Tf 2.0 and it is working as expected in Tf 1.15. 
Please take a look at [gist](https://colab.sandbox.google.com/gist/gadagashwini/c645c20cf82e371fbfd71690808dc9b8/untitled242.ipynb). Thanks!

**Comment by yongtang** [comment]
I tried with tf-nightly (`tf-nightly-2.1.0.dev20191106`) and it looks to be fine. Think this issue has been resolved.

**Comment by chrism0dwk** [comment]
Glad to know it's in the pipeline for the next release.  Thanks all.

**Comment by ymodak** [comment]
Closing this issue since its resolved with tf-nightly. Thanks!

**Comment by NaSed** [comment]
I am facing with this issue. What is the solution? Using tf-nighty?
