### ISSUE TITLE
tf.keras.model_to_estimator() fails with custom loss/custom metrics

### ISSUE THREAD

**Issue by JosPolfliet** [tensorflow/tensorflow#34040]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): YES
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS 10.14.4 
- TensorFlow installed from (source or binary): binary
```
numpy                              1.17.2     
numpydoc                           0.9.1      
protobuf                           3.9.2      
tensorflow                         2.0.0      
tensorflow-addons                  0.6.0      
tensorflow-estimator               2.0.0      
tensorflow-serving-api             2.0.0    
python                             3.7.4
```
**Describe the current behavior**
I am using a custom loss function that requires extra input (the number of words in the sentence). When compiling the model, the InputLayer used in the custom loss function does not get transferred into the new graph. Since the function is stateful, I receive the following error:
```Traceback (most recent call last):
  File "/src/automated-document-processing/nlp-tfx/bugreport.py", line 93, in <module>
    estimator = tf.keras.estimator.model_to_estimator(keras_model=model, model_dir=params["eval_dir"])
  File "/src/.anaconda/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/estimator/__init__.py", line 166, in model_to_estimator_v2
    use_v2_estimator=True)
  File "/src/.anaconda/anaconda3/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/keras.py", line 576, in model_to_estimator
    config, save_object_ckpt)
  File "/src/.anaconda/anaconda3/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/keras.py", line 381, in _save_first_checkpoint
    custom_objects)
  File "/src/.anaconda/anaconda3/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/keras.py", line 227, in _clone_and_build_model
    optimizer_config=optimizer_config)
  File "/src/.anaconda/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/models.py", line 679, in clone_and_build_model
    target_tensors=target_tensors)
  File "/src/.anaconda/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/training/tracking/base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/src/.anaconda/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 373, in compile
    self._compile_weights_loss_and_weighted_metrics()
  File "/src/.anaconda/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/training/tracking/base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/src/.anaconda/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 1653, in _compile_weights_loss_and_weighted_metrics
    self.total_loss = self._prepare_total_loss(masks)
  File "/src/.anaconda/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 1713, in _prepare_total_loss
    per_sample_losses = loss_fn.call(y_true, y_pred)
  File "/src/.anaconda/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/losses.py", line 221, in call
    return self.fn(y_true, y_pred, **self._fn_kwargs)
  File "/src/automated-document-processing/nlp-tfx/bugreport.py", line 80, in CRFLoss
    transition_params=transition_params,
  File "/src/.anaconda/anaconda3/lib/python3.7/site-packages/tensorflow_addons/text/crf.py", line 196, in crf_log_likelihood
    transition_params)
  File "/src/.anaconda/anaconda3/lib/python3.7/site-packages/tensorflow_addons/text/crf.py", line 68, in crf_sequence_score
    return _multi_seq_fn()
  File "/src/.anaconda/anaconda3/lib/python3.7/site-packages/tensorflow_addons/text/crf.py", line 59, in _multi_seq_fn
    unary_scores = crf_unary_score(tag_indices, sequence_lengths, inputs)
  File "/src/.anaconda/anaconda3/lib/python3.7/site-packages/tensorflow_addons/text/crf.py", line 232, in crf_unary_score
    sequence_lengths, maxlen=tf.shape(tag_indices)[1], dtype=tf.float32)
  File "/src/.anaconda/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/ops/array_ops.py", line 3568, in sequence_mask
    with ops.name_scope(name, "SequenceMask", [lengths, maxlen]):
  File "/src/.anaconda/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 6337, in __enter__
    g_from_inputs = _get_graph_from_inputs(self._values)
  File "/src/.anaconda/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 5982, in _get_graph_from_inputs
    _assert_same_graph(original_graph_element, graph_element)
  File "/src/.anaconda/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 5917, in _assert_same_graph
    (item, original_item))
ValueError: Tensor("loss/myscores_loss/strided_slice_3:0", shape=(), dtype=int32) must be from the same graph as Tensor("nwords:0", shape=(None,), dtype=int32).
```

**Describe the expected behavior**
Allow custom stateful loss/metrics functions in `model_to_estimator` or update the documentation that it is not supported. 

**Code to reproduce the issue**
```from typing import Any, Dict

import tensorflow as tf


from typing import Text, Tuple, List, Dict, Any, Union

import numpy as np
import tensorflow as tf
import tensorflow_addons as tfa
from tensorflow.python.ops import math_ops


def _split_iob_tag(tag: Text) -> Tuple[Text, Union[Text, None]]:
    """Handle tags <pad>, <unk>, O, B-foo, and I-foo."""
    if tag[:2] not in ["B-", "I-"]:
        return (tag, None)
    return tuple(tag.split("-", maxsplit=2))  # type: ignore


def iob_transition_params(tags: List[Text]) -> tf.constant:
    """Return transition matrix suitable for tf.contrib.crf.crf_decode."""
    mat = np.zeros((len(tags), len(tags)))
    for i, i_tag in enumerate(tags):
        i_type, i_name = _split_iob_tag(i_tag)
        for j, j_tag in enumerate(tags):
            j_type, j_name = _split_iob_tag(j_tag)
            if (i_type == "O" and j_type == "I") or (
                i_type in ["B", "I"] and j_type == "I" and i_name != j_name
            ):
                mat[i][j] = -np.inf
    return tf.constant(mat, dtype=tf.float32)


if __name__ == "__main__":
    params: Dict[str, Any] = {
        "dim": 300,
        "dropout": 0.5,
        "batch_size": 3,
        "buffer": 15000,
        "lstm_size": 10,
        "eval_dir": "../results/",
        "saved_model_dir": "../final_model/",
        "training_data": "some_data",
        "window_length": 512,
        "embedding_dimension": 300,
    }

    tags = {'I-tag1', 'B-tag1','I-tag2', 'B-tag2','I-tag3', 'B-tag3', 'O'}

    dropout = params["dropout"]

    embeddings = tf.keras.Input(
        shape=(params["window_length"], params["embedding_dimension"],),
        dtype=tf.float32,
        name="embedding_sequence",
    )
    nwords = tf.keras.Input(shape=(), dtype=tf.int32, name="nwords",)
    lstm_cell_fw = tf.keras.layers.LSTM(params["lstm_size"], return_sequences=True)(
        embeddings
    )
    output = tf.keras.layers.Dropout(rate=dropout)(lstm_cell_fw)
    logits = tf.keras.layers.Dense(len(tags), name="myscores")(output)

    # CRF
    transition_params = iob_transition_params(tags)

    def custom_loss(seqlen):
        def CRFLoss(y_true, y_pred):
            y_true = math_ops.cast(y_true, tf.int32)
            y_true = tf.reshape(y_true, [-1, 512])

            log_likelihood, _ = tfa.text.crf.crf_log_likelihood(
                inputs=y_pred,
                tag_indices=y_true,
                sequence_lengths=seqlen,
                transition_params=transition_params,
            )

            return tf.reduce_mean(-log_likelihood)

        return CRFLoss

    model = tf.keras.Model(
        inputs=[embeddings, nwords], outputs=logits, name="ner_simple"
    )

    model.compile(optimizer="adam", loss=custom_loss(nwords), metrics=["accuracy"])
    estimator = tf.keras.estimator.model_to_estimator(keras_model=model, model_dir=params["eval_dir"])
```
**Other info / logs**
Related to https://github.com/netrack/keras-metrics/issues/39

**Comment by gadagashwini** [comment]
I could reproduce the issue with Tf 2.0.
PTAL at colab [gist](https://colab.sandbox.google.com/gist/gadagashwini/d1bd904336b76d7beb9683f44a57a8e8/untitled241.ipynb). Thanks!

**Comment by ravikyram** [comment]
I have tried in colab with TF version 2.2, nightly version(`2.3.0-dev20200612`) and was able to reproduce the issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/4c408e7c7c0993b6428102ba38aaa7f4/untitled16.ipynb).Thanks!

**Comment by sushreebarsa** [comment]
Was able to reproduce the issue in TF v2.5 ,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/97544465634cfabf0be32f1f64f0407a/untitled27.ipynb)..Thanks !

**Comment by sushreebarsa** [comment]
Was able to replicate the issue with TF 2.6.0-dev20210606,please find the gist[ here](https://colab.research.google.com/gist/sushreebarsa/7c149d327fff5d7266c62ad38566de72/untitled243.ipynb) ..Thanks !

**Comment by sachinprasadhs** [comment]
I'm getting different error while reproducing your issue [here](https://colab.research.google.com/gist/sachinprasadhs/2cb8a59daa3d23e16e7456803ed3b736/untitled243.ipynb), could you please check and update the code. Thanks!
