### ISSUE TITLE
Error building 1.13

### ISSUE THREAD

**Issue by issanospam** [tensorflow/tensorflow#34042]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Source
- TensorFlow version: 1.13
- Python version: 2.7
- Installed using virtualenv? pip? conda?: Pip
- Bazel version (if compiling from source): 0.21
- GCC/Compiler version (if compiling from source): 5.4.0
- CUDA/cuDNN version: 10.0
- GPU model and memory: NVIDIA GeForce RTX 2080 TI (x2), 32GB RAM

**Describe the problem**
Error when trying to build Tensor Flow 1.13

**Provide the exact sequence of commands / steps that you executed before running into the problem**
sudo bazel build --config=opt --config=cuda --incompatible_strict_action_env=false //tensorflow/tools/pip_package:build_pip_package

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

`ERROR: /home/issa/Downloads/tensorflow/tensorflow/BUILD:579:1: Executing genrule //tensorflow:tf_python_api_gen_v1 failed (Exit 1)
Traceback (most recent call last):
  File "/home/issa/.cache/bazel/_bazel_root/ee4098cabb6d80cd53ff67b126befee0/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/tools/api/generator/create_python_api.py", line 27, in <module>
    from tensorflow.python.tools.api.generator import doc_srcs
  File "/home/issa/.cache/bazel/_bazel_root/ee4098cabb6d80cd53ff67b126befee0/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 63, in <module>
    from tensorflow.python.framework.framework_lib import *  # pylint: disable=redefined-builtin
  File "/home/issa/.cache/bazel/_bazel_root/ee4098cabb6d80cd53ff67b126befee0/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/framework/framework_lib.py", line 52, in <module>
    from tensorflow.python.framework.importer import import_graph_def
  File "/home/issa/.cache/bazel/_bazel_root/ee4098cabb6d80cd53ff67b126befee0/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/framework/importer.py", line 28, in <module>
    from tensorflow.python.framework import function
  File "/home/issa/.cache/bazel/_bazel_root/ee4098cabb6d80cd53ff67b126befee0/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/framework/function.py", line 36, in <module>
    from tensorflow.python.ops import resource_variable_ops
  File "/home/issa/.cache/bazel/_bazel_root/ee4098cabb6d80cd53ff67b126befee0/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/ops/resource_variable_ops.py", line 39, in <module>
    from tensorflow.python.ops import variables
  File "/home/issa/.cache/bazel/_bazel_root/ee4098cabb6d80cd53ff67b126befee0/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/ops/variables.py", line 133, in <module>
    "* `ONLY_FIRST_TOWER`: Deprecated alias for `ONLY_FIRST_REPLICA`.\n  ")
AttributeError: attribute '__doc__' of 'type' objects is not writable
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 2121.083s, Critical Path: 421.25s
INFO: 10541 processes: 10541 local.
FAILED: Build did NOT complete successfully
`

**Comment by oanush** [comment]
@issanospam ,
 Please take a look at the Tensorflow [tested build configuration](https://www.tensorflow.org/install/source#tested_build_configurations).Tensorflow 1.14.0 supports GCC 4.8. Thanks!

**Comment by issanospam** [comment]
Got a similar error when building Tensorflow 1.14 with GCC 4.8. Everything else seems to match the tested build configuration.

`ERROR: /home/issa/Downloads/tensorflow/tensorflow/BUILD:745:1: Executing genrule //tensorflow:tf_python_api_gen_v1 failed (Exit 1)
Traceback (most recent call last):
  File "/home/issa/.cache/bazel/_bazel_root/ee4098cabb6d80cd53ff67b126befee0/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/tools/api/generator/create_python_api.py", line 27, in <module>
    from tensorflow.python.tools.api.generator import doc_srcs
  File "/home/issa/.cache/bazel/_bazel_root/ee4098cabb6d80cd53ff67b126befee0/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 63, in <module>
    from tensorflow.python.framework.framework_lib import *  # pylint: disable=redefined-builtin
  File "/home/issa/.cache/bazel/_bazel_root/ee4098cabb6d80cd53ff67b126befee0/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/framework/framework_lib.py", line 52, in <module>
    from tensorflow.python.framework.importer import import_graph_def
  File "/home/issa/.cache/bazel/_bazel_root/ee4098cabb6d80cd53ff67b126befee0/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/framework/importer.py", line 28, in <module>
    from tensorflow.python.framework import function
  File "/home/issa/.cache/bazel/_bazel_root/ee4098cabb6d80cd53ff67b126befee0/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/framework/function.py", line 37, in <module>
    from tensorflow.python.ops import resource_variable_ops
  File "/home/issa/.cache/bazel/_bazel_root/ee4098cabb6d80cd53ff67b126befee0/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/ops/resource_variable_ops.py", line 41, in <module>
    from tensorflow.python.ops import variables
  File "/home/issa/.cache/bazel/_bazel_root/ee4098cabb6d80cd53ff67b126befee0/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/ops/variables.py", line 137, in <module>
    "* `ONLY_FIRST_TOWER`: Deprecated alias for `ONLY_FIRST_REPLICA`.\n  ")
AttributeError: attribute '__doc__' of 'type' objects is not writable
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 4661.374s, Critical Path: 341.79s
INFO: 17053 processes: 17053 local.
FAILED: Build did NOT complete successfully`

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
