### ISSUE TITLE
Using Cuda 10 and getting ImportError: libcublas.so.8.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by aarac** [tensorflow/tensorflow#34059]
I am running an instance of tensorflow and am having the issue of ImportError: libcublas.so.8.0: cannot open shared object file: No such file or directory

Is this because I am using CUDA version 10.1. Not quite sure how to proceed

**Code: sudo python2 train.py --hypes hypes/overfeat_rezoom.json --logdir output/ --gpu 0**

Traceback (most recent call last):
  File "train.py", line 4, in <module>
    import tensorflow.contrib.slim as slim
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 72, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
**ImportError: libcublas.so.8.0: cannot open shared object file: No such file or directory**

Failed to load the native TensorFlow runtime.

**System information**
- OS Platform and Distribution:  Linux Ubuntu 18.04:
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.4.1
- Python version: 2.7.15+
- Installed using: pip
- CUDA/cuDNN version: 10.1
- GPU model and memory: Tesla V100

**Comment by gadagashwini** [comment]
@aarac, Tensorflow version 1.4 supports CUDA 8. Please take a look at [tested build configuration](https://www.tensorflow.org/install/source#tested_build_configurations). Either downgrade the CUDA version to 8 or install Tensorflow version greater than 1.13.0. Let us know how it progresses. Thanks!

**Comment by gadagashwini** [comment]
@aarac, Were you able to resolve this issue. Thanks!

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
