### ISSUE TITLE
metrics = ['accuracy'] and metrics = [tf.metrics.Accuracy()] produces different results

### ISSUE THREAD

**Issue by canesqui** [tensorflow/tensorflow#34088]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: N/A
- **TensorFlow installed from (source or binary)**: Binary
- **TensorFlow version (use command below)**: v2.0.0-rc2-26-g64c3d38 2.0.0
- **Python version**: Python 3.6.8
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**: N/A

### Describe the problem
Declaring metrics as a list of tensorflow.python.keras.metrics.BinaryAccuracy or tensorflow.python.keras.metrics.Accuracy produces an error. Declaring the metrics as a string list works as expected.

### Source code / logs

Below is the source that can reproduce the issue.

```
import tensorflow as tf
import numpy as np

np.random.seed(1)
tf.random.set_seed(1)
BATCH_SIZE = 32

#Import mnist dataset as numpy arrays
(x_train, y_train), (_, _) = tf.keras.datasets.mnist.load_data()#Import
x_train = x_train / 255.0 #normalizing
y_train = y_train.astype(dtype='float32')
x_train = x_train.astype(dtype='float32')

x_train = np.reshape(x_train, (x_train.shape[0], x_train.shape[1]*x_train.shape[2]))#Reshaping the 2D picture

##############################################################################################
#THIS BLOCK CREATES A DATASET FROM THE NUMPY ARRAYS. IT WILL BE USED FOR THE CASE OF TF.DATA DATASET INPUTS
tfdata_dataset_train = tf.data.Dataset.from_tensor_slices((x_train, y_train))
tfdata_dataset_train = tfdata_dataset_train.batch(BATCH_SIZE).repeat()
##############################################################################################

#Create model
keras_model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(512, activation=tf.nn.relu),
    tf.keras.layers.Dropout(0.2, seed=1),
    tf.keras.layers.Dense(10, activation=tf.nn.softmax)
])

metrics = [tf.metrics.Accuracy()]
#metrics = ['accuracy']

#Compile the model
keras_model.compile(optimizer=tf.keras.optimizers.Adam(),
                    loss=tf.keras.losses.sparse_categorical_crossentropy,
                    metrics=metrics)


#Train with tf.data datasets
keras_training_history = keras_model.fit(tfdata_dataset_train,
                epochs=1,
                steps_per_epoch=60000//BATCH_SIZE
                )
########################
```

### Output using metrics=['accuracy']

```
2019-11-07 21:47:17.874727: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2199995000 Hz
2019-11-07 21:47:17.875199: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x49747e0 executing computations on platform Host. Devices:
2019-11-07 21:47:17.875253: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
2019-11-07 21:47:17.876808: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 188160000 exceeds 10% of system memory.
2019-11-07 21:47:18.324898: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 188160000 exceeds 10% of system memory.
Train for 1875 steps
2019-11-07 21:47:18.992644: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 188160000 exceeds 10% of system memory.
1875/1875 [==============================] - 26s 14ms/step - loss: 0.2265 - accuracy: 0.9329
```
### Output using metrics = [tf.metrics.Accuracy()]

```
2019-11-07 21:51:01.199548: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2199995000 Hz
2019-11-07 21:51:01.200090: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x4a91560 executing computations on platform Host. Devices:
2019-11-07 21:51:01.200143: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
2019-11-07 21:51:01.201813: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 188160000 exceeds 10% of system memory.
2019-11-07 21:51:01.721895: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 188160000 exceeds 10% of system memory.
Train for 1875 steps
2019-11-07 21:51:02.375751: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 188160000 exceeds 10% of system memory.
   1/1875 [..............................] - ETA: 23:32Traceback (most recent call last):
  File "bug.py", line 41, in <module>
    steps_per_epoch=60000//BATCH_SIZE
  File "/home/developer/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py", line 728, in fit
    use_multiprocessing=use_multiprocessing)
  File "/home/developer/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 324, in fit
    total_epochs=epochs)
  File "/home/developer/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 123, in run_one_epoch
    batch_outs = execution_function(iterator)
  File "/home/developer/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 86, in execution_function
    distributed_function(input_fn))
  File "/home/developer/.local/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 457, in __call__
    result = self._call(*args, **kwds)
  File "/home/developer/.local/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 503, in _call
    self._initialize(args, kwds, add_initializers_to=initializer_map)
  File "/home/developer/.local/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 408, in _initialize
    *args, **kwds))
  File "/home/developer/.local/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1848, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/home/developer/.local/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2150, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/home/developer/.local/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2041, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/home/developer/.local/lib/python3.6/site-packages/tensorflow_core/python/framework/func_graph.py", line 915, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/developer/.local/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 358, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/home/developer/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 73, in distributed_function
    per_replica_function, args=(model, x, y, sample_weights))
  File "/home/developer/.local/lib/python3.6/site-packages/tensorflow_core/python/distribute/distribute_lib.py", line 760, in experimental_run_v2
    return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
  File "/home/developer/.local/lib/python3.6/site-packages/tensorflow_core/python/distribute/distribute_lib.py", line 1787, in call_for_each_replica
    return self._call_for_each_replica(fn, args, kwargs)
  File "/home/developer/.local/lib/python3.6/site-packages/tensorflow_core/python/distribute/distribute_lib.py", line 2132, in _call_for_each_replica
    return fn(*args, **kwargs)
  File "/home/developer/.local/lib/python3.6/site-packages/tensorflow_core/python/autograph/impl/api.py", line 292, in wrapper
    return func(*args, **kwargs)
  File "/home/developer/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 264, in train_on_batch
    output_loss_metrics=model._output_loss_metrics)
  File "/home/developer/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_eager.py", line 315, in train_on_batch
    model, outs, targets, sample_weights=sample_weights, masks=masks)
  File "/home/developer/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_eager.py", line 74, in _eager_metrics_fn
    skip_target_masks=model._prepare_skip_target_masks())
  File "/home/developer/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py", line 2063, in _handle_metrics
    target, output, output_mask))
  File "/home/developer/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py", line 2014, in _handle_per_output_metrics
    metric_fn, y_true, y_pred, weights=weights, mask=mask)
  File "/home/developer/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_utils.py", line 1067, in call_metric_function
    return metric_fn(y_true, y_pred, sample_weight=weights)
  File "/home/developer/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/metrics.py", line 193, in __call__
    replica_local_fn, *args, **kwargs)
  File "/home/developer/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/distribute/distributed_training_utils.py", line 1135, in call_replica_local_fn
    return fn(*args, **kwargs)
  File "/home/developer/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/metrics.py", line 176, in replica_local_fn
    update_op = self.update_state(*args, **kwargs)  # pylint: disable=not-callable
  File "/home/developer/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/utils/metrics_utils.py", line 75, in decorated
    update_op = update_state_fn(*args, **kwargs)
  File "/home/developer/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/metrics.py", line 581, in update_state
    matches = self._fn(y_true, y_pred, **self._fn_kwargs)
  File "/home/developer/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/metrics.py", line 2750, in accuracy
    y_pred.shape.assert_is_compatible_with(y_true.shape)
  File "/home/developer/.local/lib/python3.6/site-packages/tensorflow_core/python/framework/tensor_shape.py", line 1115, in assert_is_compatible_with
    raise ValueError("Shapes %s and %s are incompatible" % (self, other))
ValueError: Shapes (None, 10) and (None, 1) are incompatible
```

**Comment by netw0rkf10w** [comment]
The meaning of `'accuracy'` depends on the loss function. The one that corresponds to `sparse_categorical_crossentropy` is `tf.keras.metrics.SparseCategoricalAccuracy()`, not `tf.metrics.Accuracy()`.

**Comment by ravikyram** [comment]
@canesqui 
Please use `metrics = [tf.keras.metrics.SparseCategoricalAccuracy()] `in place of `metrics = [tf.metrics.Accuracy()]` then you can see the same results.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/c31c3ed5a3e35e483fa34ac76b2ed48e/untitled350.ipynb). Thanks!

**Comment by canesqui** [comment]
Thank you @netw0rkf10w and @ravikyram for pointing that out. @netw0rkf10w, can you please share the documentation where I can find information on declaring metrics as a string array and how it would map to the loss function? Once again, thank you for your help.

**Comment by ravikyram** [comment]
@canesqui 

Can you please go through the below [link](https://www.tensorflow.org/api_docs/python/tf/keras/metrics/SparseCategoricalAccuracy) and see if it helps you.Thanks!

**Comment by bersbersbers** [comment]
I stumbled across a very similar issue today, and also earlier (where I noticed that `'mse'` and `tf.keras.metrics.mse` behaved differently, IIRC). Therefore, I have been resorting to using `tf.keras.metric.get()` to sanitize all inputs. However, with `accuracy`, I have now found that `'accuracy'` behaves differently from `keras.metrics.get('accuracy')`. This is super-unexpected, and as far as I can see, this is not documented, either. The link posted by @ravikyram does not address this issue.

Also, not only do the two versions behave differently in terms of accepting tensors different shapes (one does, the other does not, see OP), also the numerical results can differ between the two:

```
"""Bug."""
# import keras
import numpy as np
import tensorflow.keras as keras

X = np.empty([10, 224, 224, 3])
Y = np.empty([10, 2])

MODEL = keras.applications.vgg16.VGG16(weights=None, classes=2)

MODEL.compile(optimizer=keras.optimizers.Adam(),
              loss='categorical_crossentropy',
              metrics=['accuracy'])
MODEL.fit(X, Y, epochs=10)

MODEL.compile(optimizer=keras.optimizers.Adam(),
              loss='categorical_crossentropy',
              metrics=[keras.metrics.get('accuracy')])
MODEL.fit(X, Y, epochs=10)
```
gives (for example)
```
Train on 10 samples
Epoch 1/10

10/10 [==============================] - 4s 389ms/sample - loss: inf - accuracy: 0.9000
Epoch 2/10

10/10 [==============================] - 0s 8ms/sample - loss: nan - accuracy: 0.9000
Epoch 3/10

10/10 [==============================] - 0s 8ms/sample - loss: nan - accuracy: 0.9000
Epoch 4/10

10/10 [==============================] - 0s 8ms/sample - loss: nan - accuracy: 0.9000
Epoch 5/10

10/10 [==============================] - 0s 8ms/sample - loss: nan - accuracy: 0.9000
Epoch 6/10

10/10 [==============================] - 0s 8ms/sample - loss: nan - accuracy: 0.9000
Epoch 7/10

10/10 [==============================] - 0s 8ms/sample - loss: nan - accuracy: 0.9000
Epoch 8/10

10/10 [==============================] - 0s 8ms/sample - loss: nan - accuracy: 0.9000
Epoch 9/10

10/10 [==============================] - 0s 8ms/sample - loss: nan - accuracy: 0.9000
Epoch 10/10

10/10 [==============================] - 0s 8ms/sample - loss: nan - accuracy: 0.9000
Train on 10 samples
Epoch 1/10

10/10 [==============================] - 1s 131ms/sample - loss: nan - accuracy: 0.0000e+00
Epoch 2/10

10/10 [==============================] - 0s 8ms/sample - loss: nan - accuracy: 0.0000e+00
Epoch 3/10

10/10 [==============================] - 0s 8ms/sample - loss: nan - accuracy: 0.0000e+00
Epoch 4/10

10/10 [==============================] - 0s 8ms/sample - loss: nan - accuracy: 0.0000e+00
Epoch 5/10

10/10 [==============================] - 0s 8ms/sample - loss: nan - accuracy: 0.0000e+00
Epoch 6/10

10/10 [==============================] - 0s 8ms/sample - loss: nan - accuracy: 0.0000e+00
Epoch 7/10

10/10 [==============================] - 0s 8ms/sample - loss: nan - accuracy: 0.0000e+00
Epoch 8/10

10/10 [==============================] - 0s 8ms/sample - loss: nan - accuracy: 0.0000e+00
Epoch 9/10

10/10 [==============================] - 0s 8ms/sample - loss: nan - accuracy: 0.0000e+00
Epoch 10/10

10/10 [==============================] - 0s 8ms/sample - loss: nan - accuracy: 0.0000e+00
```

**Comment by ravikyram** [comment]
@bersbersbers 

Will it be possible for you to raise a new issue by filling [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).Thanks!

**Comment by netw0rkf10w** [comment]
> @netw0rkf10w, can you please share the documentation where I can find information on declaring metrics as a string array and how it would look for the corresponding metric according to the loss function?

Sorry for the late reply. Unfortunately I don't remember how I learned about that, but definitely not from the official documentation or tutorials!

**Comment by ravikyram** [comment]
@canesqui 
Please, let us know if this is still an issue?. Please, close this issue if it is already resolved.Thanks!

**Comment by bersbersbers** [comment]
@ravikyram I believe this is still an issue, at the least same issue (that I have been asked to re-file as #34451 and which was closed by accident) is still there in nightly.

**Comment by gowthamkpr** [comment]
@canesqui I am gonna close this issue as this issue is being tracked here(#34451)
