### ISSUE TITLE
ResourceScatterNdUpdate bug in graph mode and tape.gradient()

### ISSUE THREAD

**Issue by emailweixu** [tensorflow/tensorflow#34090]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.0.0-rc2-26-g64c3d38 2.0.0
- Python version: 3.6
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: 10.0.130
- GPU model and memory: GeForce RTX 2080 Ti

**Describe the current behavior**
Running the code gets the following error:
```
 ValueError: The inner -1 dimensions of input.shape=[] must match the inner 1 dimensions of updates.shape=[4,20]: Shapes must be equal rank, but are 0 and 1 for 'ResourceScatterNdUpdate' (op: 'ResourceScatterNdUpdate') with input shapes: [], [4,1], [4,20].
```
There is no error if running the code without @tf.function decoration, or without using while_loop, or without using tape.gradient()

**Describe the expected behavior**
Code should run without error

**Code to reproduce the issue**
```python
import tensorflow as tf

def main():
    dim = 20
    capacity = 256
    batch_size = 4
    buffer = tf.Variable(
            initial_value=tf.zeros((capacity, dim)),
            trainable=False)
    w = tf.Variable(
        initial_value=tf.zeros(()), trainable=True)

    def _loop_body(loss):
        loss += w.value()
        indices = tf.range(batch_size)
        indices = tf.expand_dims(indices, axis=-1)
        # Error disappears if running buffer.scatter_nd_update inside tf.cond
        # tf.cond(tf.shape(indices)[0] > 0, lambda:
        buffer.scatter_nd_update(indices, tf.zeros(shape=(batch_size, dim))),
        # lambda: buffer.value())
        return [loss]

    # Error disappears if @tf.function is removed
    @tf.function
    def _loop():
        unroll_length = 10
        loss = tf.zeros(())
        with tf.GradientTape() as tape:
            [loss] = tf.while_loop(
                cond=lambda *_: True,
                body=_loop_body,
                loop_vars=[loss],
                back_prop=True,
                maximum_iterations=unroll_length)
            # Error disappears if removing the previous while_loop()
            # and uncomment the following line
            # [loss] = _loop_body(loss)
        # Error disappears if removing tape.gradient()
        tape.gradient(loss, w)
        w.assign_add(loss)

    _loop()

if __name__ == '__main__':
    main()
```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

Full error message:
```
Traceback (most recent call last):
  File "scatter_nd_bug.py", line 45, in <module>
    main()
  File "scatter_nd_bug.py", line 42, in main
    _loop()
  File "/home/weixu/venvs/tf2/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 457, in __call__
    result = self._call(*args, **kwds)
  File "/home/weixu/venvs/tf2/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 503, in _call
    self._initialize(args, kwds, add_initializers_to=initializer_map)
  File "/home/weixu/venvs/tf2/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 408, in _initialize
    *args, **kwds))
  File "/home/weixu/venvs/tf2/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1848, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/home/weixu/venvs/tf2/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2150, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/home/weixu/venvs/tf2/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2041, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/home/weixu/venvs/tf2/lib/python3.6/site-packages/tensorflow_core/python/framework/func_graph.py", line 915, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/weixu/venvs/tf2/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 358, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/home/weixu/venvs/tf2/lib/python3.6/site-packages/tensorflow_core/python/framework/func_graph.py", line 905, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in converted code:

    scatter_nd_bug.py:39 _loop  *
        tape.gradient(loss, w)
    /home/weixu/venvs/tf2/lib/python3.6/site-packages/tensorflow_core/python/eager/backprop.py:1014 gradient
        unconnected_gradients=unconnected_gradients)
    /home/weixu/venvs/tf2/lib/python3.6/site-packages/tensorflow_core/python/eager/imperative_grad.py:76 imperative_grad
        compat.as_str(unconnected_gradients.value))
    /home/weixu/venvs/tf2/lib/python3.6/site-packages/tensorflow_core/python/eager/backprop.py:138 _gradient_function
        return grad_fn(mock_op, *out_grads)
    /home/weixu/venvs/tf2/lib/python3.6/site-packages/tensorflow_core/python/ops/while_v2.py:336 _WhileGrad
        body_graph = _get_graph(while_op, "body")
    /home/weixu/venvs/tf2/lib/python3.6/site-packages/tensorflow_core/python/ops/while_v2.py:557 _get_graph
        func_graph = function_def_to_graph.function_def_to_graph(fdef, input_shapes)
    /home/weixu/venvs/tf2/lib/python3.6/site-packages/tensorflow_core/python/framework/function_def_to_graph.py:65 function_def_to_graph
        importer.import_graph_def_for_function(graph_def, name="")
    /home/weixu/venvs/tf2/lib/python3.6/site-packages/tensorflow_core/python/framework/importer.py:412 import_graph_def_for_function
        graph_def, validate_colocation_constraints=False, name=name)
    /home/weixu/venvs/tf2/lib/python3.6/site-packages/tensorflow_core/python/framework/importer.py:505 _import_graph_def_internal
        raise ValueError(str(e))

    ValueError: The inner -1 dimensions of input.shape=[] must match the inner 1 dimensions of updates.shape=[4,20]: Shapes must be equal rank, but are 0 and 1 for 'ResourceScatterNdUpdate' (op: 'ResourceScatterNdUpdate') with input shapes: [], [4,1], [4,20].
```

**Comment by oanush** [comment]
@emailweixu ,
Can you try using latest - tf-nightly 2.1.0.dev20191110 version issue seemed to be fixed, kindly find the [gist](https://colab.sandbox.google.com/gist/oanush/188e307b70eaf4ddbb43fd26e8be1c87/34090.ipynb) of colab for the same.Thanks!

**Comment by emailweixu** [comment]
Yes, it works with tf-nightly

**Comment by oanush** [comment]
@emailweixu ,
Can you please try using the nightly version as the issue is fixed in the latest version? kindly close the issue if its resolved!

**Comment by emailweixu** [comment]
Thanks
