### ISSUE TITLE
ImportError: DLL load failed TF 1.13

### ISSUE THREAD

**Issue by sc20ka** [tensorflow/tensorflow#34116]
**System information**
- win 10 x64  18362 (1903):
- pc:
- VS community tensorflow-gpu 1.13.1:
- tensorflow-gpu 1.13.1:
- Python 3.7:
- pip in VS community:
- all version 9.0 10.1/cudnn-10.1-windows10-x64-v7.6.5.32:
- 1060 6gb:
```

```
> 
> Using TensorFlow backend.
> Traceback (most recent call last):
>   File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
>     from tensorflow.python.pywrap_tensorflow_internal import *
>   File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
>     _pywrap_tensorflow_internal = swig_import_helper()
>   File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
>     _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
>   File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\imp.py", line 242, in load_module
>     return load_dynamic(name, filename, file)
>   File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\imp.py", line 342, in load_dynamic
>     return _load(spec)
> ImportError: DLL load failed: Не найден указанный модуль.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\extensions\microsoft\python\core\ptvsd_launcher.py", line 119, in <module>
>     vspd.debug(filename, port_num, debug_id, debug_options, run_as)
>   File "c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\extensions\microsoft\python\core\Packages\ptvsd\debugger.py", line 39, in debug
>     run()
>   File "c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\extensions\microsoft\python\core\Packages\ptvsd\__main__.py", line 316, in run_file
>     runpy.run_path(target, run_name='__main__')
>   File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\runpy.py", line 263, in run_path
>     pkg_name=pkg_name, script_name=fname)
>   File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\runpy.py", line 96, in _run_module_code
>     mod_name, mod_spec, pkg_name, script_name)
>   File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\sc20k\source\repos\Test yay\Test yay\Test_yay.py", line 1, in <module>
>     from imageai.Detection import VideoObjectDetection
>   File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\imageai\Detection\__init__.py", line 2, in <module>
>     from imageai.Detection.keras_retinanet.models.resnet import resnet50_retinanet
>   File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\imageai\Detection\keras_retinanet\models\resnet.py", line 19, in <module>
>     import keras
>   File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\keras\__init__.py", line 3, in <module>
>     from . import utils
>   File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\keras\utils\__init__.py", line 6, in <module>
>     from . import conv_utils
>   File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\keras\utils\conv_utils.py", line 9, in <module>
>     from .. import backend as K
>   File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\keras\backend\__init__.py", line 1, in <module>
>     from .load_backend import epsilon
>   File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\keras\backend\load_backend.py", line 90, in <module>
>     from .tensorflow_backend import *
>   File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\keras\backend\tensorflow_backend.py", line 5, in <module>
>     import tensorflow as tf
>   File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
>     from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
>   File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
>     from tensorflow.python import pywrap_tensorflow
>   File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
>     raise ImportError(msg)
> ImportError: Traceback (most recent call last):
>   File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
>     from tensorflow.python.pywrap_tensorflow_internal import *
>   File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
>     _pywrap_tensorflow_internal = swig_import_helper()
>   File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
>     _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
>   File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\imp.py", line 242, in load_module
>     return load_dynamic(name, filename, file)
>   File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\imp.py", line 342, in load_dynamic
>     return _load(spec)
> ImportError: DLL load failed: Не найден указанный модуль.
> 
> 
> Failed to load the native TensorFlow runtime.
> 
> See https://www.tensorflow.org/install/errors
> 
> for some common reasons and solutions.  Include the entire stack trace
> above this error message when asking for help.
> 
> 
```

```

**Comment by ymodak** [comment]
You need to install cuda 10.0 and add cuda, cupti, cudnn path to the environment variable.
Please take a look at [gpu setup for windows guide](https://www.tensorflow.org/install/gpu#windows_setup) to know more.

**Comment by gadagashwini** [comment]
@sc20ka, Did you get a chance to try @ymodak's solution.
Thanks!

**Comment by gadagashwini** [comment]
@sc20ka, Install CUDA 10.0 and Follow the following steps to install Tensorflow. Also set the CUDA path. 
$pip install virtualenv
$virtualenv tf_1.13   # tf_1.13 is virtual env name
$source tf_1.13/bin/activate
tf_2.0.0 $ pip install tensorflow-gpu==1.13.1
Thanks!

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by Snickbrack** [comment]
I would like to reopen this issue as my problem is the same.

I have installed CUDA 10.1 and cudnn and added the things from here (https://www.tensorflow.org/install/gpu#windows_setup) into the PATH-Variable but I still get the error that "Failed to load the native TensorFlow runtime.".

This is my complete stack-trace:

```
Using TensorFlow backend.
Traceback (most recent call last):
  File "C:\Anaconda3\envs\imageai\lib\site-packages\tensorflow\pyth
on\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Anaconda3\envs\imageai\lib\site-packages\tensorflow\pyth
on\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Anaconda3\envs\imageai\lib\site-packages\tensorflow\pyth
on\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, descript
ion)
  File "C:\Anaconda3\envs\imageai\lib\imp.py", line 242, in load_mo
dule
    return load_dynamic(name, filename, file)
  File "C:\Anaconda3\envs\imageai\lib\imp.py", line 342, in load_dy
namic
    return _load(spec)
ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Documents\ImageAI\CustomDetectionTraining.py", line 1, i
n <module>
    from imageai.Detection.Custom import DetectionModelTrainer
  File "C:\Anaconda3\envs\imageai\lib\site-packages\imageai\Detecti
on\__init__.py", line 2, in <module>
    from imageai.Detection.keras_retinanet.models.resnet import resnet50_retinan
et
  File "C:\Anaconda3\envs\imageai\lib\site-packages\imageai\Detecti
on\keras_retinanet\models\resnet.py", line 19, in <module>
    import keras
  File "C:\Anaconda3\envs\imageai\lib\site-packages\keras\__init__.
py", line 3, in <module>
    from . import utils
  File "C:\Anaconda3\envs\imageai\lib\site-packages\keras\utils\__i
nit__.py", line 6, in <module>
    from . import conv_utils
  File "C:\Anaconda3\envs\imageai\lib\site-packages\keras\utils\con
v_utils.py", line 9, in <module>
    from .. import backend as K
  File "C:\Anaconda3\envs\imageai\lib\site-packages\keras\backend\_
_init__.py", line 1, in <module>
    from .load_backend import epsilon
  File "C:\Anaconda3\envs\imageai\lib\site-packages\keras\backend\l
oad_backend.py", line 90, in <module>
    from .tensorflow_backend import *
  File "C:\Anaconda3\envs\imageai\lib\site-packages\keras\backend\t
ensorflow_backend.py", line 5, in <module>
    import tensorflow as tf
  File "C:\Anaconda3\envs\imageai\lib\site-packages\tensorflow\__in
it__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-im
port
  File "C:\Anaconda3\envs\imageai\lib\site-packages\tensorflow\pyth
on\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Anaconda3\envs\imageai\lib\site-packages\tensorflow\pyth
on\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Anaconda3\envs\imageai\lib\site-packages\tensorflow\pyth
on\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Anaconda3\envs\imageai\lib\site-packages\tensorflow\pyth
on\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Anaconda3\envs\imageai\lib\site-packages\tensorflow\pyth
on\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, descript
ion)
  File "C:\Anaconda3\envs\imageai\lib\imp.py", line 242, in load_mo
dule
    return load_dynamic(name, filename, file)
  File "C:\Anaconda3\envs\imageai\lib\imp.py", line 342, in load_dy
namic
    return _load(spec)
ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

**Comment by gadagashwini** [comment]
@sc20ka, Does your CPU support AVX instruction sets.

**Comment by gadagashwini** [comment]
@Snickbrack, Closing issue due to no activity. Please free to open new issue with information asked in template. Thanks!
