### ISSUE TITLE
Have install future module, but still can not find builtins when Building from source

### ISSUE THREAD

**Issue by narutojxl** [tensorflow/tensorflow#34146]
<em>

**System information**
- OS Platform and Distribution (Linux Ubuntu 16.04, kerenl: Linux dell 4.15.0-54-generic):
- Mobile device (not)
- TensorFlow installed from: source
- TensorFlow version: master branch, git clone https://github.com/tensorflow/tensorflow.git
- Python version: 2.7.12
- Installed using virtualenv? pip? conda?: 
- Bazel version: 0.29.1
- GCC/Compiler version:  5.4.0
- CUDA/cuDNN version:  CUDA 9.0, cuDNN 7.3.1
- GPU model and memory: GeForce GT 730

**Configure info**

> 
	jxl@dell:~/third_softwares/tensorflow$ ./configure
	WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
	You have bazel 0.29.1 installed.
	Please specify the location of python. [Default is /usr/bin/python]: 

	Found possible Python library paths:
	  /opt/ros/kinetic/lib/python2.7/dist-packages
	  /usr/lib/python2.7/dist-packages
	  /usr/local/lib/python2.7/dist-packages
	  /home/jxl/kalibr_ws/devel/lib/python2.7/dist-packages
	  /home/jxl/third_softwares/Autoware/ros/install/rslidar_pointcloud/lib/python2.7/dist-packages
	Please input the desired Python library path to use.  Default is [/opt/ros/kinetic/lib/python2.7/dist-packages]

	Do you wish to build TensorFlow with XLA JIT support? [Y/n]: n
	No XLA JIT support will be enabled for TensorFlow.

	Do you wish to build TensorFlow with OpenCL SYCL support? [y/N]: n
	No OpenCL SYCL support will be enabled for TensorFlow.

	Do you wish to build TensorFlow with ROCm support? [y/N]: n
	No ROCm support will be enabled for TensorFlow.

	Do you wish to build TensorFlow with CUDA support? [y/N]: y
	CUDA support will be enabled for TensorFlow.

	Do you wish to build TensorFlow with TensorRT support? [y/N]: n
	No TensorRT support will be enabled for TensorFlow.

	Found CUDA 9.0 in:
	    /usr/local/cuda/lib64
	    /usr/local/cuda/include
	Found cuDNN 7 in:
	    /usr/lib/x86_64-linux-gnu
	    /usr/include

	Please specify a list of comma-separated CUDA compute capabilities you want to build with.
	You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
	Please note that each additional compute capability significantly increases your build time and binary size, and that TensorFlow only supports compute capabilities >= 3.5 [Default is: 3.5]: 

	Do you want to use clang as CUDA compiler? [y/N]: n
	nvcc will be used as CUDA compiler.

	Please specify which gcc should be used by nvcc as the host compiler. [Default is /usr/bin/gcc]: 

	Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native -Wno-sign-compare]: 

	Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]: n
	Not configuring the WORKSPACE for Android builds.

	Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See .bazelrc for more details.
		--config=mkl         	# Build with MKL support.
		--config=monolithic  	# Config for mostly static monolithic build.
		--config=ngraph      	# Build with Intel nGraph support.
		--config=numa        	# Build with NUMA support.
		--config=dynamic_kernels	# (Experimental) Build kernels into separate shared objects.
		--config=v2          	# Build TensorFlow 2.x instead of 1.x.
	Preconfigured Bazel build configs to DISABLE default on features:
		--config=noaws       	# Disable AWS S3 filesystem support.
		--config=nogcp       	# Disable GCP support.
		--config=nohdfs      	# Disable HDFS support.
		--config=nonccl      	# Disable NVIDIA NCCL support.
	Configuration finished
	jxl@dell:~/third_softwares/tensorflow$ 

**Describe the problem**
> 
	jxl@dell:~/third_softwares/tensorflow$ sudo pip  install future
	[sudo] jxl 的密码： 
	/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.
	  warnings.warn(warning, RequestsDependencyWarning)
	DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
	Requirement already satisfied: future in /home/jxl/.local/lib/python2.7/site-packages (0.18.2)
	jxl@dell:~/third_softwares/tensorflow$ 

	jxl@dell:~/third_softwares/tensorflow$ bazel build --config=opt --config=cuda  --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0"   //tensorflow/tools/pip_package:build_pip_package
	Starting local Bazel server and connecting to it...
	WARNING: The following configs were expanded more than once: [cuda, using_cuda]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
	INFO: Options provided by the client:
	  Inherited 'common' options: --isatty=1 --terminal_columns=231
	INFO: Reading rc options for 'build' from /home/jxl/third_softwares/tensorflow/.bazelrc:
	  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --java_toolchain=//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=//third_party/toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone --strategy=Genrule=standalone -c opt --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 --announce_rc --define=grpc_no_ares=true --incompatible_remove_legacy_whole_archive --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --config=v2
	INFO: Reading rc options for 'build' from /home/jxl/third_softwares/tensorflow/.tf_configure.bazelrc:
	  'build' options: --host_force_python=PY2 --action_env PYTHON_BIN_PATH=/usr/bin/python --action_env PYTHON_LIB_PATH=/opt/ros/kinetic/lib/python2.7/dist-packages --python_path=/usr/bin/python --action_env PYTHONPATH=/home/jxl/kalibr_ws/devel/lib/python2.7/dist-packages:/opt/ros/kinetic/lib/python2.7/dist-packages:/home/jxl/third_softwares/Autoware/ros/install/rslidar_pointcloud/lib/python2.7/dist-packages --action_env CUDA_TOOLKIT_PATH=/usr/local/cuda --action_env TF_CUDA_COMPUTE_CAPABILITIES=3.5 --action_env LD_LIBRARY_PATH=/home/jxl/kalibr_ws/devel/lib:/opt/ros/kinetic/lib:/opt/ros/kinetic/lib/x86_64-linux-gnu:/home/jxl/third_softwares/ssdcaffe/distribute/lib:/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64 --action_env GCC_HOST_COMPILER_PATH=/usr/bin/gcc-5 --config=cuda --action_env TF_CONFIGURE_IOS=0
	INFO: Found applicable config definition build:v2 in file /home/jxl/third_softwares/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
	INFO: Found applicable config definition build:cuda in file /home/jxl/third_softwares/tensorflow/.bazelrc: --config=using_cuda --define=using_cuda_nvcc=true
	INFO: Found applicable config definition build:using_cuda in file /home/jxl/third_softwares/tensorflow/.bazelrc: --define=using_cuda=true --action_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain
	INFO: Found applicable config definition build:opt in file /home/jxl/third_softwares/tensorflow/.tf_configure.bazelrc: --copt=-march=native --copt=-Wno-sign-compare --host_copt=-march=native --define with_default_optimizations=true
	INFO: Found applicable config definition build:cuda in file /home/jxl/third_softwares/tensorflow/.bazelrc: --config=using_cuda --define=using_cuda_nvcc=true
	INFO: Found applicable config definition build:using_cuda in file /home/jxl/third_softwares/tensorflow/.bazelrc: --define=using_cuda=true --action_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain
	DEBUG: Rule 'io_bazel_rules_docker' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1556410077 -0400"
	DEBUG: Call stack for the definition of repository 'io_bazel_rules_docker' which is a git_repository (rule definition at /home/jxl/.cache/bazel/_bazel_jxl/630c8d4015ad0c22430bd92a914b2e86/external/bazel_tools/tools/build_defs/repo/git.bzl:195:18):
	 - /home/jxl/.cache/bazel/_bazel_jxl/630c8d4015ad0c22430bd92a914b2e86/external/bazel_toolchains/repositories/repositories.bzl:37:9
	 - /home/jxl/third_softwares/tensorflow/WORKSPACE:37:1
	DEBUG: /home/jxl/.cache/bazel/_bazel_jxl/630c8d4015ad0c22430bd92a914b2e86/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:118:5: 
	Auto-Configuration Warning: 'TMP' environment variable is not set, using 'C:\Windows\Temp' as default
	Traceback (most recent call last):
	  File "/home/jxl/.cache/bazel/_bazel_jxl/630c8d4015ad0c22430bd92a914b2e86/external/org_tensorflow/tensorflow/tools/git/gen_git_source.py", line 32, in <module>
	    from builtins import bytes  # pylint: disable=redefined-builtin
	ImportError: No module named builtins
	INFO: Call stack for the definition of repository 'local_config_git' which is a git_configure (rule definition at /home/jxl/third_softwares/tensorflow/third_party/git/git_configure.bzl:66:17):
	 - /home/jxl/third_softwares/tensorflow/tensorflow/workspace.bzl:74:5
	 - /home/jxl/third_softwares/tensorflow/WORKSPACE:19:1
	ERROR: An error occurred during the fetch of repository 'local_config_git':
	   Traceback (most recent call last):
		File "/home/jxl/third_softwares/tensorflow/third_party/git/git_configure.bzl", line 64
			_fail(result.stderr)
		File "/home/jxl/third_softwares/tensorflow/third_party/git/git_configure.bzl", line 14, in _fail
			fail(("%sGit Configuration Error:%s %...)))
	Git Configuration Error: Traceback (most recent call last):
	  File "/home/jxl/.cache/bazel/_bazel_jxl/630c8d4015ad0c22430bd92a914b2e86/external/org_tensorflow/tensorflow/tools/git/gen_git_source.py", line 32, in <module>
	    from builtins import bytes  # pylint: disable=redefined-builtin
	ImportError: No module named builtins

**Comment by narutojxl** [comment]
Uninstall pip installed with get-pip.py, install pip with apt.
And then remove ~/.local/lib/python2.7/site-packages/  dir.
Then pip install future module.
