### ISSUE TITLE
tf.nn.moments with keras causes Invalid tape state

### ISSUE THREAD

**Issue by jackd** [tensorflow/tensorflow#34154]
### System information
- Have I written custom code: yes
- OS Platform and Distribution: Linux Ubuntu 16.04
- TensorFlow installed from : binary
- TensorFlow version: v1.12.1-8709-gddde447 2.0.0-dev20190813
- Python version: 3.6

Also reproducable with cuda 10.0 cudnn 7.something / GTX-1070 but I doubt it's a GPU issue...

### Current Behaviour
Using output of `tf.nn.moments` causes `Invalid tape state` when training keras models in manual loops (i.e. not using `fit`).

### Expected Behaviour
`mean, var = tf.nn.moments(x, axes, keepdims=True)` (and use thereafter) should be equivalent to 
```
mean = tf.reduce_mean(x, axis=axes, keepdims=True)
xs = x - mean
var = tf.reduce_mean(xs**2, axis=axes, keepdims=True)
```

# Code
```python
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import tensorflow as tf


def normalize_manual(x):
    mean = tf.reduce_mean(x, axis=-1, keepdims=True)
    x = x - mean
    var = tf.reduce_mean(tf.square(x), axis=-1, keepdims=True)
    return x / (tf.sqrt(var + 1e-6))


def normalize_with_moments(x):
    mean, var = tf.nn.moments(x, [-1], keepdims=True)
    x = x - mean
    return x / tf.sqrt(var + 1e-6)


def run_model_custom(normalize=normalize_with_moments):
    inp = tf.keras.layers.Input(shape=(8,))
    x = inp
    x = tf.keras.layers.Dense(8)(x)
    x = normalize(x)
    out = tf.squeeze(tf.keras.layers.Dense(1)(x), axis=-1)
    model = tf.keras.Model(inputs=inp, outputs=out)

    x = tf.random.normal(shape=((100, 8)))
    y = tf.random.normal(shape=((100,)))
    dataset = tf.data.Dataset.from_tensor_slices((x, y)).batch(5)

    for x, y in dataset.take(1):
        with tf.GradientTape() as tape:
            out = model(x)
            tape.gradient(out, model.trainable_weights)
        break
    print('passed run_model_custom with {}'.format(normalize.__name__))


def train_model_fit(normalize=normalize_with_moments):
    inp = tf.keras.layers.Input(shape=(8,))
    x = inp
    x = tf.keras.layers.Dense(8)(x)
    x = normalize(x)
    out = tf.squeeze(tf.keras.layers.Dense(1)(x), axis=-1)
    model = tf.keras.Model(inputs=inp, outputs=out)

    x = tf.random.normal(shape=((100, 8)))
    y = tf.random.normal(shape=((100,)))
    dataset = tf.data.Dataset.from_tensor_slices((x, y)).batch(5)
    model.compile(optimizer=tf.keras.optimizers.SGD(), loss='mse')
    model.fit(dataset, epochs=1, steps_per_epoch=2)
    print('passed train_model_fit with {}'.format(normalize.__name__))


def compute_graph_tf(normalize=normalize_with_moments):
    x = tf.random.normal((10, 5))
    with tf.GradientTape() as tape:
        layer = tf.keras.layers.Dense(2)
        y = layer(x)
        y = tf.reduce_sum(normalize(y))
        tape.gradient(y, layer.trainable_weights)
    print('passed compute_graph_tf with {}'.format(normalize.__name__))


run_model_custom(normalize_with_moments)  # <----- fails

###########
# the below work
###########
train_model_fit(normalize_with_moments)
compute_graph_tf(normalize_with_moments)
run_model_custom(normalize_manual)
train_model_fit(normalize_manual)
compute_graph_tf(normalize_manual)
```

# Logs
```
Traceback (most recent call last):
  File "norm_grad.py", line 67, in <module>
    run_model_custom(normalize_with_moments)  # <----- fails
  File "norm_grad.py", line 36, in run_model_custom
    tape.gradient(out, model.trainable_weights)
  File ".../python3.6/site-packages/tensorflow_core/python/eager/backprop.py", line 1008, in gradient
    unconnected_gradients=unconnected_gradients)
  File ".../python3.6/site-packages/tensorflow_core/python/eager/imperative_grad.py", line 76, in imperative_grad
    compat.as_str(unconnected_gradients.value))
tensorflow.python.framework.errors_impl.InternalError: Invalid tape state.
```

**Comment by dubesar** [comment]
```from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import tensorflow as tf
tf.enable_eager_execution()

def normalize_manual(x):
    mean = tf.reduce_mean(x, axis=-1, keepdims=True)
    x = x - mean
    var = tf.reduce_mean(tf.square(x), axis=-1, keepdims=True)
    return x / (tf.sqrt(var + 1e-6))


def normalize_with_moments(x):
    mean, var = tf.nn.moments(x, [-1], keepdims=True)
    x = x - mean
    return x / tf.sqrt(var + 1e-6)


def run_model_custom(normalize=normalize_with_moments):
    inp = tf.keras.layers.Input(shape=(8,))
    x = inp
    x = tf.keras.layers.Dense(8)(x)
    x = normalize(x)
    out = tf.squeeze(tf.keras.layers.Dense(1)(x), axis=-1)
    model = tf.keras.Model(inputs=inp, outputs=out)

    x = tf.random.normal(shape=((100, 8)))
    y = tf.random.normal(shape=((100,)))
    dataset = tf.data.Dataset.from_tensor_slices((x, y)).batch(5)

    for x, y in dataset.take(1):
        with tf.GradientTape() as tape:
            out = x
            tape.gradient(out, model.trainable_weights,unconnected_gradients=tf.UnconnectedGradients.NONE)
        break
    print('passed run_model_custom with {}'.format(normalize.__name__))


def train_model_fit(normalize=normalize_with_moments):
    inp = tf.keras.layers.Input(shape=(8,))
    x = inp
    x = tf.keras.layers.Dense(8)(x)
    x = normalize(x)
    out = tf.squeeze(tf.keras.layers.Dense(1)(x), axis=-1)
    model = tf.keras.Model(inputs=inp, outputs=out)

    x = tf.random.normal(shape=((100, 8)))
    y = tf.random.normal(shape=((100,)))
    dataset = tf.data.Dataset.from_tensor_slices((x, y)).batch(5)
    model.compile(optimizer=tf.keras.optimizers.SGD(), loss='mse')
    model.fit(dataset, epochs=1, steps_per_epoch=2)
    print('passed train_model_fit with {}'.format(normalize.__name__))


def compute_graph_tf(normalize=normalize_with_moments):
    x = tf.random.normal((10, 5))
    with tf.GradientTape() as tape:
        layer = tf.keras.layers.Dense(2)
        y = layer(x)
        y = tf.reduce_sum(normalize(y))
        tape.gradient(y, layer.trainable_weights)
    print('passed compute_graph_tf with {}'.format(normalize.__name__))


run_model_custom(normalize_with_moments)  # <----- fails

###########
# the below work
###########
train_model_fit(normalize_with_moments)
compute_graph_tf(normalize_with_moments)
run_model_custom(normalize_manual)
train_model_fit(normalize_manual)
compute_graph_tf(normalize_manual)
```

This code worked. Find the changes

**Comment by jackd** [comment]
Wrapping `normalize_with_moments` in  `tf.keras.layers.Lambda` makes this work, though it's still very surprising and difficult to identify the issue. I'm guessing that's due to `tf.nn.moments` being a single op with multiple outputs? How does `keras` handle this in `fit` differently?

**Comment by gowthamkpr** [comment]
The problem here is that if you don't wrap `normalize_with_moments` in `tf.keras.layers.Lambda`  here could be no differentiable path in the graph connecting input to output and thus the resulting error.

**Comment by jackd** [comment]
@gowthamkpr one of the nicest things about `tf2` is that most ops don't require a `tf.keras.layers.Lambda` wrapper. If a path cannot be found connecting inputs to outputs an informative error should be raised in model construction, not during gradient computation. It also doesn't answer the question of what `Model.fit` is doing.

**Comment by jvishnuvardhan** [comment]
@jackd Is this still an issue? When I ran your code with `tf-nightly`, I didn't see any error.  For the line that was throwing error for you, it didn't show any error with `tf-nightly`. Please add a line `!pip install tf-nightly-gpu` at the top to install `tf-nightly`.

For the following line 
`run_model_custom(normalize_with_moments)  # <----- fails`

It outputs

`passed run_model_custom with normalize_with_moments`

Please close the issue if this was resolved for you. Thanks!

**Comment by jvishnuvardhan** [comment]
@jackd I am closing this issue as it was resolved. Please feel free to reopen if the issue persists again. Thanks!
