### ISSUE TITLE
Distributed training with TensorFlow2.0 not working: "Aborting RingReduce with Invalid argument: Shape mismatch in the collective instance 106."

### ISSUE THREAD

**Issue by jessicadef** [tensorflow/tensorflow#34156]
We trying to build a multi-worker strategy based on tutorials: [Multi-worker training with Keras](https://www.tensorflow.org/tutorials/distribute/multi_worker_with_keras) and [distributed training with TF2](https://github.com/lambdal/TensorFlow2-tutorial/blob/master/05-distributed-training/worker.py). The code works with this configurations: 
- first node:
`os.environ['TF_CONFIG'] = json.dumps({ 'cluster': {  'worker': ["localhost:5006","localhost:5007"] },  'task': {'type': 'worker', 'index': 0}})`
- second node:
`os.environ['TF_CONFIG'] = json.dumps({ 'cluster': {  'worker': ["localhost:5006","localhost:5007"] },  'task': {'type': 'worker', 'index': 1}})`.

Then we tried to run the code from two devices with the following system information:
- OS: Linux Mint 19.1 Cinnamon, Cinnamon Version: 4.0.10
- python version: 3.6.8
- tensorflow version: 2.1.0

with the following configurations:
- on the first device:
`os.environ['TF_CONFIG'] = json.dumps({
    'cluster': {
        'worker': ["10.0.0.109:6006","10.0.0.148:6006"]
    },
    'task': {'type': 'worker', 'index': 0}
})`
- on the second device:
`os.environ['TF_CONFIG'] = json.dumps({
    'cluster': {
        'worker': ["10.0.0.109:6006","10.0.0.148:6006"]
    },
    'task': {'type': 'worker', 'index': 1}
})`.

The devices can navigate into each other through ssh without password. We report the used script and the [link](https://docs.aws.amazon.com/en_us/forecast/latest/dg/getting-started.html#gs-upload-data-to-s3) to the source data set.
Script:
```
def create_dataframe(data, time_field):
    data['time'] = pd.to_datetime(data[time_field])
    data = data.drop(columns=[time_field])
    data.sort_values('time')
    data = data.reset_index(drop=True)
    data.set_index('time', inplace=True)
    return data

def aggregate(df, freq , field, aggregation):
    df_count = df.groupby(pd.Grouper(level='time', freq=freq))[field].agg(aggregation)
    df_count.dropna(inplace=True)
    df_count = df_count.to_frame().reset_index()
    df = df.reset_index()
    df_count.set_index('time', inplace=True)
    return df_count

def split_sequence(sequence, n_steps):
    X, y = list(), list()
    for i in range(len(sequence)):
        end_ix = i + n_steps
        if end_ix > len(sequence)-1:
            break
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
        X.append(seq_x)
        y.append(seq_y)
    return array(X), array(y)

strategy = tf.distribute.experimental.MultiWorkerMirroredStrategy()

df=pd.read_csv("/path/to/electricityusagedata.csv")

df = create_dataframe(df, 'dt')
dfy = aggregate(df,freq = '1h', field = 'value', aggregation = 'mean')
n_steps = 10
n_features=1
value=df['value']

X, y = split_sequence(dfy.value, n_steps)

Xtrain = X.reshape(X.shape[0], X.shape[1], n_features)

with strategy.scope():

	inputs = tf.keras.layers.Input(shape=(n_steps, n_features))
	layer = tf.keras.layers.Dense(5, activation='relu')(inputs)
	layer = tf.keras.layers.Dense(1)(layer)

	lstm_stacked = tf.keras.Model(inputs=inputs, outputs=layer)
	lstm_stacked.compile(optimizer=tf.keras.optimizers.Adam(),loss=tf.keras.losses.MeanSquaredError())
	lstm_stacked.summary()

lstm_stacked.fit(Xtrain,y,epochs=10)
```

The complete output from the command line is
```
2019-11-11 11:44:33.962245: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcudart.so.10.0'; dlerror: libcudart.so.10.0: cannot open shared object file: No such file or directory
2019-11-11 11:44:33.962282: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2019-11-11 11:44:34.962335: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2019-11-11 11:44:34.962374: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: UNKNOWN ERROR (303)
2019-11-11 11:44:34.962394: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (keypartner): /proc/driver/nvidia/version does not exist
2019-11-11 11:44:34.962620: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-11-11 11:44:34.991840: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2294830000 Hz
2019-11-11 11:44:34.992692: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x57231a0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2019-11-11 11:44:34.992737: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2019-11-11 11:44:35.000579: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:300] Initialize GrpcChannelCache for job worker -> {0 -> localhost:6006, 1 -> 10.0.0.148:6006}
2019-11-11 11:44:35.001075: I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:390] Started server with target: grpc://localhost:6006
Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_1 (InputLayer)         [(None, 10, 1)]           0         
_________________________________________________________________
dense (Dense)                (None, 10, 5)             10        
_________________________________________________________________
dense_1 (Dense)              (None, 10, 1)             6         
=================================================================
Total params: 16
Trainable params: 16
Non-trainable params: 0
_________________________________________________________________
WARNING:tensorflow:`eval_fn` is not passed in. The `worker_fn` will be used if an "evaluator" task exists in the cluster.
WARNING:tensorflow:`eval_strategy` is not passed in. No distribution strategy will be used for evaluation.
WARNING:tensorflow:ModelCheckpoint callback is not provided. Workers will need to restart training if any fails.
2019-11-11 11:45:04.330943: W tensorflow/core/grappler/optimizers/data/auto_shard.cc:428] In AUTO-mode, and switching to DATA-based sharding, instead of FILE-based sharding as we cannot find appropriate reader dataset op(s) to shard. Error: Did not find a shardable source, walked to a node which is not a dataset: name: "FlatMapDataset/_9"
op: "FlatMapDataset"
input: "PrefetchDataset/_8"
attr {
  key: "Targuments"
  value {
    list {
    }
  }
}
attr {
  key: "f"
  value {
    func {
      name: "__inference_Dataset_flat_map_slice_batch_indices_173"
    }
  }
}
attr {
  key: "output_shapes"
  value {
    list {
      shape {
        dim {
          size: -1
        }
      }
    }
  }
}
attr {
  key: "output_types"
  value {
    list {
      type: DT_INT64
    }
  }
}
. Consider either turning off auto-sharding or switching the auto_shard_policy to DATA to shard this dataset. You can do this by creating a new `tf.data.Options()` object then setting `options.experimental_distribute.auto_shard_policy = AutoShardPolicy.DATA` before applying the options object to the dataset via `dataset.with_options(options)`.
Train on 8750 samples
Epoch 1/10
2019-11-11 11:45:07.181787: E tensorflow/core/common_runtime/ring_alg.cc:279] Aborting RingReduce with Invalid argument: Shape mismatch in the collective instance 106. Op at device /job:worker/replica:0/task:1/device:CPU:0 expected shape [49] but another member in the group expected shape [64]. This is likely due to different input shapes at different members of the collective op.
Additional GRPC error information:
{"created":"@1573469107.160620334","description":"Error received from peer","file":"external/grpc/src/core/lib/surface/call.cc","file_line":1039,"grpc_message":"Shape mismatch in the collective instance 106. Op at device /job:worker/replica:0/task:1/device:CPU:0 expected shape [49] but another member in the group expected shape [64]. This is likely due to different input shapes at different members of the collective op.","grpc_status":3}
	 [[{{node scoped_allocator_1_1_CollectiveReduce}}]]
Additional GRPC error information:
{"created":"@1573469107.181701406","description":"Error received from peer","file":"external/grpc/src/core/lib/surface/call.cc","file_line":1039,"grpc_message":"Shape mismatch in the collective instance 106. Op at device /job:worker/replica:0/task:1/device:CPU:0 expected shape [49] but another member in the group expected shape [64]. This is likely due to different input shapes at different members of the collective op.\nAdditional GRPC error information:\n{"created":"@1573469107.160620334","description":"Error received from peer","file":"external/grpc/src/core/lib/surface/call.cc","file_line":1039,"grpc_message":"Shape mismatch in the collective instance 106. Op at device /job:worker/replica:0/task:1/device:CPU:0 expected shape [49] but another member in the group expected shape [64]. This is likely due to different input shapes at different members of the collective op.","grpc_status":3}\n\t [[{{node scoped_allocator_1_1_CollectiveReduce}}]]","grpc_status":3}
2019-11-11 11:45:07.181854: W tensorflow/core/common_runtime/base_collective_executor.cc:217] BaseCollectiveExecutor::StartAbort Invalid argument: Shape mismatch in the collective instance 106. Op at device /job:worker/replica:0/task:1/device:CPU:0 expected shape [49] but another member in the group expected shape [64]. This is likely due to different input shapes at different members of the collective op.
Additional GRPC error information:
{"created":"@1573469107.160620334","description":"Error received from peer","file":"external/grpc/src/core/lib/surface/call.cc","file_line":1039,"grpc_message":"Shape mismatch in the collective instance 106. Op at device /job:worker/replica:0/task:1/device:CPU:0 expected shape [49] but another member in the group expected shape [64]. This is likely due to different input shapes at different members of the collective op.","grpc_status":3}
	 [[{{node scoped_allocator_1_1_CollectiveReduce}}]]
Additional GRPC error information:
{"created":"@1573469107.181701406","description":"Error received from peer","file":"external/grpc/src/core/lib/surface/call.cc","file_line":1039,"grpc_message":"Shape mismatch in the collective instance 106. Op at device /job:worker/replica:0/task:1/device:CPU:0 expected shape [49] but another member in the group expected shape [64]. This is likely due to different input shapes at different members of the collective op.\nAdditional GRPC error information:\n{"created":"@1573469107.160620334","description":"Error received from peer","file":"external/grpc/src/core/lib/surface/call.cc","file_line":1039,"grpc_message":"Shape mismatch in the collective instance 106. Op at device /job:worker/replica:0/task:1/device:CPU:0 expected shape [49] but another member in the group expected shape [64]. This is likely due to different input shapes at different members of the collective op.","grpc_status":3}\n\t [[{{node scoped_allocator_1_1_CollectiveReduce}}]]","grpc_status":3}
2019-11-11 11:45:07.181990: E tensorflow/core/common_runtime/ring_alg.cc:279] Aborting RingReduce with Cancelled: [_Derived_]Cancelled
Additional GRPC error information:
{"created":"@1573469107.181911798","description":"Error received from peer","file":"external/grpc/src/core/lib/surface/call.cc","file_line":1039,"grpc_message":"Cancelled","grpc_status":1}
2019-11-11 11:45:07.182013: W tensorflow/core/common_runtime/base_collective_executor.cc:217] BaseCollectiveExecutor::StartAbort Cancelled: [_Derived_]Cancelled
Additional GRPC error information:
{"created":"@1573469107.181911798","description":"Error received from peer","file":"external/grpc/src/core/lib/surface/call.cc","file_line":1039,"grpc_message":"Cancelled","grpc_status":1}
2019-11-11 11:45:07.182077: W tensorflow/core/framework/op_kernel.cc:1655] OP_REQUIRES failed at collective_ops.cc:253 : Invalid argument: Shape mismatch in the collective instance 106. Op at device /job:worker/replica:0/task:1/device:CPU:0 expected shape [49] but another member in the group expected shape [64]. This is likely due to different input shapes at different members of the collective op.
Additional GRPC error information:
{"created":"@1573469107.160620334","description":"Error received from peer","file":"external/grpc/src/core/lib/surface/call.cc","file_line":1039,"grpc_message":"Shape mismatch in the collective instance 106. Op at device /job:worker/replica:0/task:1/device:CPU:0 expected shape [49] but another member in the group expected shape [64]. This is likely due to different input shapes at different members of the collective op.","grpc_status":3}
	 [[{{node scoped_allocator_1_1_CollectiveReduce}}]]
Additional GRPC error information:
{"created":"@1573469107.181701406","description":"Error received from peer","file":"external/grpc/src/core/lib/surface/call.cc","file_line":1039,"grpc_message":"Shape mismatch in the collective instance 106. Op at device /job:worker/replica:0/task:1/device:CPU:0 expected shape [49] but another member in the group expected shape [64]. This is likely due to different input shapes at different members of the collective op.\nAdditional GRPC error information:\n{"created":"@1573469107.160620334","description":"Error received from peer","file":"external/grpc/src/core/lib/surface/call.cc","file_line":1039,"grpc_message":"Shape mismatch in the collective instance 106. Op at device /job:worker/replica:0/task:1/device:CPU:0 expected shape [49] but another member in the group expected shape [64]. This is likely due to different input shapes at different members of the collective op.","grpc_status":3}\n\t [[{{node scoped_allocator_1_1_CollectiveReduce}}]]","grpc_status":3}
2019-11-11 11:45:07.182133: W tensorflow/core/common_runtime/base_collective_executor.cc:217] BaseCollectiveExecutor::StartAbort Invalid argument: Shape mismatch in the collective instance 106. Op at device /job:worker/replica:0/task:1/device:CPU:0 expected shape [49] but another member in the group expected shape [64]. This is likely due to different input shapes at different members of the collective op.
Additional GRPC error information:
{"created":"@1573469107.160620334","description":"Error received from peer","file":"external/grpc/src/core/lib/surface/call.cc","file_line":1039,"grpc_message":"Shape mismatch in the collective instance 106. Op at device /job:worker/replica:0/task:1/device:CPU:0 expected shape [49] but another member in the group expected shape [64]. This is likely due to different input shapes at different members of the collective op.","grpc_status":3}
	 [[{{node scoped_allocator_1_1_CollectiveReduce}}]]
Additional GRPC error information:
{"created":"@1573469107.181701406","description":"Error received from peer","file":"external/grpc/src/core/lib/surface/call.cc","file_line":1039,"grpc_message":"Shape mismatch in the collective instance 106. Op at device /job:worker/replica:0/task:1/device:CPU:0 expected shape [49] but another member in the group expected shape [64]. This is likely due to different input shapes at different members of the collective op.\nAdditional GRPC error information:\n{"created":"@1573469107.160620334","description":"Error received from peer","file":"external/grpc/src/core/lib/surface/call.cc","file_line":1039,"grpc_message":"Shape mismatch in the collective instance 106. Op at device /job:worker/replica:0/task:1/device:CPU:0 expected shape [49] but another member in the group expected shape [64]. This is likely due to different input shapes at different members of the collective op.","grpc_status":3}\n\t [[{{node scoped_allocator_1_1_CollectiveReduce}}]]","grpc_status":3}
	 [[scoped_allocator_1_1_CollectiveReduce]]
2019-11-11 11:45:07.182123: W tensorflow/core/framework/op_kernel.cc:1655] OP_REQUIRES failed at collective_ops.cc:253 : Cancelled: [_Derived_]Cancelled
Additional GRPC error information:
{"created":"@1573469107.181911798","description":"Error received from peer","file":"external/grpc/src/core/lib/surface/call.cc","file_line":1039,"grpc_message":"Cancelled","grpc_status":1}
  32/8750 [..............................] - ETA: 12:56Traceback (most recent call last):
  File "worker1.py", line 91, in <module>
    lstm_stacked.fit(Xtrain,y,epochs=10)
  File "/home/keypartner/my_tutorial_env/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py", line 792, in fit
    use_multiprocessing=use_multiprocessing)
  File "/home/keypartner/my_tutorial_env/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_distributed.py", line 790, in fit
    *args, **kwargs)
  File "/home/keypartner/my_tutorial_env/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_distributed.py", line 777, in wrapper
    mode=dc.CoordinatorMode.INDEPENDENT_WORKER)
  File "/home/keypartner/my_tutorial_env/lib/python3.6/site-packages/tensorflow_core/python/distribute/distribute_coordinator.py", line 853, in run_distribute_coordinator
    task_id, session_config, rpc_layer)
  File "/home/keypartner/my_tutorial_env/lib/python3.6/site-packages/tensorflow_core/python/distribute/distribute_coordinator.py", line 360, in _run_single_worker
    return worker_fn(strategy)
  File "/home/keypartner/my_tutorial_env/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_distributed.py", line 772, in _worker_fn
    return method(model, **kwargs)
  File "/home/keypartner/my_tutorial_env/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 340, in fit
    total_epochs=epochs)
  File "/home/keypartner/my_tutorial_env/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 127, in run_one_epoch
    batch_outs = execution_function(iterator)
  File "/home/keypartner/my_tutorial_env/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 86, in execution_function
    distributed_function(input_fn))
  File "/home/keypartner/my_tutorial_env/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 568, in __call__
    result = self._call(*args, **kwds)
  File "/home/keypartner/my_tutorial_env/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 632, in _call
    return self._stateless_fn(*args, **kwds)
  File "/home/keypartner/my_tutorial_env/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2341, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/home/keypartner/my_tutorial_env/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1589, in _filtered_call
    self.captured_inputs)
  File "/home/keypartner/my_tutorial_env/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1670, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/home/keypartner/my_tutorial_env/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 523, in call
    ctx=ctx)
  File "/home/keypartner/my_tutorial_env/lib/python3.6/site-packages/tensorflow_core/python/eager/execute.py", line 67, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError:  Shape mismatch in the collective instance 106. Op at device /job:worker/replica:0/task:1/device:CPU:0 expected shape [49] but another member in the group expected shape [64]. This is likely due to different input shapes at different members of the collective op.
Additional GRPC error information:
{"created":"@1573469107.160620334","description":"Error received from peer","file":"external/grpc/src/core/lib/surface/call.cc","file_line":1039,"grpc_message":"Shape mismatch in the collective instance 106. Op at device /job:worker/replica:0/task:1/device:CPU:0 expected shape [49] but another member in the group expected shape [64]. This is likely due to different input shapes at different members of the collective op.","grpc_status":3}
	 [[{{node scoped_allocator_1_1_CollectiveReduce}}]]
Additional GRPC error information:
{"created":"@1573469107.181701406","description":"Error received from peer","file":"external/grpc/src/core/lib/surface/call.cc","file_line":1039,"grpc_message":"Shape mismatch in the collective instance 106. Op at device /job:worker/replica:0/task:1/device:CPU:0 expected shape [49] but another member in the group expected shape [64]. This is likely due to different input shapes at different members of the collective op.\nAdditional GRPC error information:\n{"created":"@1573469107.160620334","description":"Error received from peer","file":"external/grpc/src/core/lib/surface/call.cc","file_line":1039,"grpc_message":"Shape mismatch in the collective instance 106. Op at device /job:worker/replica:0/task:1/device:CPU:0 expected shape [49] but another member in the group expected shape [64]. This is likely due to different input shapes at different members of the collective op.","grpc_status":3}\n\t [[{{node scoped_allocator_1_1_CollectiveReduce}}]]","grpc_status":3}
	 [[scoped_allocator_1_1_CollectiveReduce]] [Op:__inference_distributed_function_843]

Function call stack:
distributed_function

2019-11-11 11:45:07.262512: W tensorflow/core/kernels/data/generator_dataset_op.cc:103] Error occurred when finalizing GeneratorDataset iterator: Cancelled: Operation was cancelled

```
We are wondering why the multi devices example doesn't work meanwhile it works on multi threads at localhost.

**Comment by gadagashwini** [comment]
@jessicadef, Please provide the complete standalone code replicate the reported issue. Thanks!

**Comment by jessicadef** [comment]
We provided the two python scripts to be run from the two machines. The dataset is available [here](https://docs.aws.amazon.com/en_us/forecast/latest/dg/getting-started.html#gs-upload-data-to-s3). Thanks.
[workers.tar.gz](https://github.com/tensorflow/tensorflow/files/3835310/workers.tar.gz)

**Comment by gadagashwini** [comment]
@jessicadef, Please paste the code snippet to localize the reported issue. Thanks!

**Comment by jessicadef** [comment]
@gadagashwini Thanks for your reply! I figured out where the issue was: one of the two machines was running the code in a virtualenv environment which did not allow the machines to communicate.

**Comment by gadagashwini** [comment]
@jessicadef,
Can you please let us know if you are happy to close if no issue persists. Thanks!

**Comment by robin-shaun** [comment]
I met this problem with tf 2.1, but after I upgraded it to tf 2.2, the problem was solved.
