### ISSUE TITLE
How to use golang to implement python's tf.train.Example().serializetostring.

### ISSUE THREAD

**Issue by atlantiswqq** [tensorflow/tensorflow#34186]
I'm trying to  using the python training model, deploy services with golang. However, the following problems arise when using golang for prediction.

predict with python:
```
    def predict_np(self):
        predict_fn = self.get_predict_fn(self.np_path)
        inputs = np.array([[6.4, 3.2, 4.5, 1.5], [6.4, 3.2, 4.5, 1.5]])
        for item in inputs:
            examples = []
            feature = {"your_input": tf.train.Feature(float_list=tf.train.FloatList(value=item))}
            example = tf.train.Example(features=tf.train.Features(feature=feature))
            examples.append(example.SerializeToString())
            print(type(example.SerializeToString()))
            predictions = predict_fn({"inputs": examples})
            print(predictions)
```
it works ok.

predict with golang
```
package main

import (
	"fmt"
	tg "github.com/galeone/tfgo"
	"github.com/gogo/protobuf/proto"
	tf "github.com/tensorflow/tensorflow/tensorflow/go"
	"github.com/tensorflow/tensorflow/tensorflow/go/core/example"
	"loadEstimator/train"
)

func main() {
	data := [][]float32{{6.4, 3.2, 4.5, 1.5}, {6.4, 3.2, 4.5, 1.5}}
	columnsName := []string{"a", "b", "c", "d"}
	for _, item := range data {
		// npData:numpy data like in python {"inputs":[6.4,3.2,4.5,1.5]}
		npData := make(map[string][]float32)
		npData["your_input"] = item
		predictNP(npData)
	}

}

func loadModeSavedPB(path string) (model *tg.Model) {
	model = tg.LoadModel(path, []string{"serve"}, nil)
	return
}

func predictNP(data map[string][]float32) {
	pdModePath := "./static/1"
	model := loadModeSavedPB(pdModePath)
	sequence := sequenceNP(data)
	fmt.Println(sequence)
	fakeInput, _ := tf.NewTensor([]string{sequence})
	results := model.Exec([]tf.Output{
		model.Op("dnn/head/Tile", 0),
	}, map[tf.Output]*tf.Tensor{
		model.Op("input_example_tensor", 0): fakeInput,
	})
	predictions := results[0].Value().([][]float32)
	fmt.Println(predictions)
}

func sequenceNP(featureInfo map[string][]float32) (seq string) {
	feature := make(map[string]*example.Feature)
	for k, v := range featureInfo {
		valFormat := train.Float32ToFeature(v)
		feature[k] = valFormat
	}
	Features := example.Features{Feature: feature}
	myExample := example.Example{Features: &Features}
	seq = proto.MarshalTextString(&myExample)
	return
}

```

```
package train

import "github.com/tensorflow/tensorflow/tensorflow/go/core/example"
func Float32ToFeature(value []float32) (exampleFeature *example.Feature) {
	floatList := example.FloatList{Value: value}
	featureFloatList := example.Feature_FloatList{FloatList: &floatList}
	exampleFeature = &example.Feature{Kind: &featureFloatList}
	return
}
```

There is an error
```
2019-11-12 11:42:05.021196: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at example_parsing_ops.cc:144 : Invalid argument: Could not parse example input, value: 'features: <
  feature: <
    key: "your_input"
    value: <
      float_list: <
        value: 6.4
        value: 3.2
        value: 4.5
        value: 1.5
      >
    >
  >
>
'
panic: Could not parse example input, value: 'features: <
  feature: <
    key: "your_input"
    value: <
      float_list: <
        value: 6.4
        value: 3.2
        value: 4.5
        value: 1.5
      >
    >
  >
>
'
	 [[{{node ParseExample/ParseExample}}]]
```

i'm using `proto.MarshalTextString(&myExample)`  in golang,and using 
`
example = tf.train.Example(features=tf.train.Features(feature=feature))
examples.append(example.SerializeToString())
`
in python.
I am not sure whether serialization in these two languages is equivalent, and if not, how can I implement `SerializeToString` in golang? pls

**Comment by atlantiswqq** [comment]
i'm sorry,in fact,i need use `seq,err = proto.Marshal(&myExample)`
i got []byte in golang is 
`[10 36 10 34 10 10 121 111 117 114 95 105 110 112 117 116 18 20 18 18 10 16 205 204 204 64 205 204 76 64 0 0 144 64 0 0 192 63]`
but got 
`b'\n$\n"\n\nyour_input\x12\x14\x12\x12\n\x10\xcd\xcc\xcc@\xcd\xccL@\x00\x00\x90@\x00\x00\xc0?'` in python
then golang panic
```
2019-11-12 15:50:31.436302: I tensorflow/cc/saved_model/reader.cc:31] Reading SavedModel from: ./static/1
2019-11-12 15:50:31.440917: I tensorflow/cc/saved_model/reader.cc:54] Reading meta graph with tags { serve }
2019-11-12 15:50:31.442798: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.2 AVX AVX2 FMA
2019-11-12 15:50:31.445938: I tensorflow/cc/saved_model/loader.cc:182] Restoring SavedModel bundle.
2019-11-12 15:50:31.461115: I tensorflow/cc/saved_model/loader.cc:132] Running initialization op on SavedModel bundle.
2019-11-12 15:50:31.465338: I tensorflow/cc/saved_model/loader.cc:285] SavedModel load for tags { serve }; Status: success. Took 29047 microseconds.
panic: Expects arg[0] to be string but uint8 is provided

goroutine 1 [running]:
github.com/galeone/tfgo.(*Model).Exec(0xc00000e028, 0xc0000b1c50, 0x1, 0x1, 0xc0000b1cb8, 0x0, 0x2, 0x400cd3f)
	/Users/wqq/go/src/github.com/galeone/tfgo/model.go:74 +0xd1
main.predictNP(0xc00008c6f0)
	/Users/wqq/go/src/loadEstimator/main.go:46 +0x34a
main.main()
	/Users/wqq/go/src/loadEstimator/main.go:19 +0x27f
```
So I think byte is different in golang and python

**Comment by atlantiswqq** [comment]
i sloved

**Comment by gao8954** [comment]
@atlantiswqq  how does sloved it ,i got the same error ! thank you very much

**Comment by gao8954** [comment]
@atlantiswqq

**Comment by prprprus** [comment]
> @atlantiswqq

https://github.com/galeone/tfgo#train-with-tfestimator-serve-in-go, tfgo might help you.

**Comment by roffe** [comment]
ping @atlantiswqq id love to know as well how you fixed it

**Comment by atlantiswqq** [comment]
In fact, I have added this serialization operation into [.](https://github.com/galeone/tfgo) In the source code of TensorFlow, I saw several Protobuf files, and I compiled them into the go version. I also wrote some methods to help you serialize the data in the form of array and dictionary.
@roffe @gao8954

**Comment by roffe** [comment]
@atlantiswqq do you have any writeup or similar on how to reproduce & build a image trainer in Go?

**Comment by atlantiswqq** [comment]
> @atlantiswqq do you have any writeup or similar on how to reproduce & build a image trainer in Go?

I don't recommend you use go for training, I just use go to train some models of natural language
