### ISSUE TITLE
OutOfRangeError when training estimator with filter in the input_fn

### ISSUE THREAD

**Issue by DenisUllmann** [tensorflow/tensorflow#34200]
**System information**
- Have I written custom code: YES
- OS Platform and Distribution: WINDOWS 10, 64-bits
- TensorFlow installed from (source or binary): conda install -c anaconda tensorflow-gpu
- TensorFlow version (use command below): 2.0.0
- Python version: 3.7.5
- CUDA/cuDNN version: from conda installation
- GPU model and memory: NVIDIA GE Force 730M, 4.8GB

**Describe the current behavior**
OutOfRangeError when training estimator with filter in the input_fn
When I remove the `.filter(lambda x: x['label'] == 0)` in the `input_fn`, everything works fine.
The same error appears if I use:
`tf.estimator.train_and_evaluate(KMeansEstimator, train_spec_kmeans, eval_spec_kmeans)`
or
`KMeansEstimator.train(input_fn = lambda: input_fn(data_files) , max_steps=10)`

**Describe the expected behavior**
No error during the training with the filtered dataset in the `input_fn` of the estimator

**Code to reproduce the issue**
tfrecords_path is the path to mnist dataset as TFRecords files with the features described bellow:
```
def parser(record):
    features={
            'label': tf.io.FixedLenFeature([], tf.int64),
            'height': tf.io.FixedLenFeature([], tf.int64),
            'width': tf.io.FixedLenFeature([], tf.int64),
            'depth': tf.io.FixedLenFeature([], tf.int64),
            'image_raw': tf.io.FixedLenFeature([], tf.string)
            }
    parsed = tf.io.parse_single_example(record, features)
    feats = tf.io.decode_raw(parsed['image_raw'], tf.float64)
    return {'image': feats, 'label': parsed['label']}

def input_fn(tfrecords_path):
    dataset = (
        tf.data.TFRecordDataset(tfrecords_path)
        .map(
            map_func=parser,
            num_parallel_calls=int(multiprocessing.cpu_count() * 0.75)
            )
        .filter(lambda x: x['label'] == 0)
        .batch(1024)
        .prefetch(1024)
     )
    iterator = tf.compat.v1.data.make_one_shot_iterator(dataset)
    batch_feats = iterator.get_next()
    return batch_feats

train_spec_kmeans = tf.estimator.TrainSpec(input_fn = lambda: input_fn(data_files) , max_steps=10)
eval_spec_kmeans = tf.estimator.EvalSpec(input_fn = lambda: input_fn(data_files) )

KMeansEstimator = tf.compat.v1.estimator.experimental.KMeans(
    num_clusters=number_of_clusters,
    feature_columns = [tf.feature_column.numeric_column(
        key='image',
        dtype=tf.float64,
        shape=(784,)
    )],
    use_mini_batch=True)

tf.estimator.train_and_evaluate(KMeansEstimator, train_spec_kmeans, eval_spec_kmeans)
```

**Other info / logs**
```
  File "C:\Users\CUI\.conda\envs\py3tf2_0\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 370, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "C:\Users\CUI\.conda\envs\py3tf2_0\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1160, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "C:\Users\CUI\.conda\envs\py3tf2_0\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1194, in _train_model_default
    saving_listeners)
  File "C:\Users\CUI\.conda\envs\py3tf2_0\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1489, in _train_with_estimator_spec
    log_step_count_steps=log_step_count_steps) as mon_sess:
  File "C:\Users\CUI\.conda\envs\py3tf2_0\lib\site-packages\tensorflow_core\python\training\monitored_session.py", line 584, in MonitoredTrainingSession
    stop_grace_period_secs=stop_grace_period_secs)
  File "C:\Users\CUI\.conda\envs\py3tf2_0\lib\site-packages\tensorflow_core\python\training\monitored_session.py", line 1014, in __init__
    stop_grace_period_secs=stop_grace_period_secs)
  File "C:\Users\CUI\.conda\envs\py3tf2_0\lib\site-packages\tensorflow_core\python\training\monitored_session.py", line 725, in __init__
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "C:\Users\CUI\.conda\envs\py3tf2_0\lib\site-packages\tensorflow_core\python\training\monitored_session.py", line 1207, in __init__
    _WrappedSession.__init__(self, self._create_session())
  File "C:\Users\CUI\.conda\envs\py3tf2_0\lib\site-packages\tensorflow_core\python\training\monitored_session.py", line 1212, in _create_session
    return self._sess_creator.create_session()
  File "C:\Users\CUI\.conda\envs\py3tf2_0\lib\site-packages\tensorflow_core\python\training\monitored_session.py", line 885, in create_session
    hook.after_create_session(self.tf_sess, self.coord)
  File "C:\Users\CUI\.conda\envs\py3tf2_0\lib\site-packages\tensorflow_estimator\python\estimator\canned\kmeans.py", line 105, in after_create_session
    session.run(self._init_op)
  File "C:\Users\CUI\.conda\envs\py3tf2_0\lib\site-packages\tensorflow_core\python\client\session.py", line 956, in run
    run_metadata_ptr)
  File "C:\Users\CUI\.conda\envs\py3tf2_0\lib\site-packages\tensorflow_core\python\client\session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\CUI\.conda\envs\py3tf2_0\lib\site-packages\tensorflow_core\python\client\session.py", line 1359, in _do_run
    run_metadata)
  File "C:\Users\CUI\.conda\envs\py3tf2_0\lib\site-packages\tensorflow_core\python\client\session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.OutOfRangeError: 2 root error(s) found.
  (0) Out of range: End of sequence
         [[node IteratorGetNext (defined at C:\Users\CUI\.conda\envs\py3tf2_0\lib\site-packages\tensorflow_core\python\framework\ops.py:1751) ]]
         [[Shape_1/_37]]
  (1) Out of range: End of sequence
         [[node IteratorGetNext (defined at C:\Users\CUI\.conda\envs\py3tf2_0\lib\site-packages\tensorflow_core\python\framework\ops.py:1751) ]]
0 successful operations.
0 derived errors ignored.

Original stack trace for 'IteratorGetNext':
  File ".\main.py", line 144, in <module>
    tf.compat.v1.app.run()
  File "C:\Users\CUI\.conda\envs\py3tf2_0\lib\site-packages\tensorflow_core\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Users\CUI\.conda\envs\py3tf2_0\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "C:\Users\CUI\.conda\envs\py3tf2_0\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File ".\main.py", line 136, in main
    launch_training_testing()
  File ".\main.py", line 100, in launch_training_testing
    km_ckpt, kmeans = train_test.train_quantizers(FLAGS)
  File "C:\Users\CUI\ML\Decentralized_class_V1_tf2\src\model\train_test_tf2TFR.py", line 334, in train_quantizers
    km_ckpt, kmeans = label_train_quantizers(label, q_c, kmeans, km_ckpt, config)
  File "C:\Users\CUI\ML\Decentralized_class_V1_tf2\src\model\train_test_tf2TFR.py", line 296, in label_train_quantizers
    kmeans[label][q_c].train(input_fn = lambda: kmtrain_input_fn(tfr_train_files) , max_steps=config.km_steps)
  File "C:\Users\CUI\.conda\envs\py3tf2_0\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 370, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "C:\Users\CUI\.conda\envs\py3tf2_0\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1160, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "C:\Users\CUI\.conda\envs\py3tf2_0\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1187, in _train_model_default
    input_fn, ModeKeys.TRAIN))
  File "C:\Users\CUI\.conda\envs\py3tf2_0\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1024, in _get_features_and_labels_from_input_fn
    self._call_input_fn(input_fn, mode))
  File "C:\Users\CUI\.conda\envs\py3tf2_0\lib\site-packages\tensorflow_estimator\python\estimator\util.py", line 65, in parse_input_fn_result
    result = iterator.get_next()
  File "C:\Users\CUI\.conda\envs\py3tf2_0\lib\site-packages\tensorflow_core\python\data\ops\iterator_ops.py", line 426, in get_next
    name=name)
  File "C:\Users\CUI\.conda\envs\py3tf2_0\lib\site-packages\tensorflow_core\python\ops\gen_dataset_ops.py", line 2500, in iterator_get_next
    output_shapes=output_shapes, name=name)
  File "C:\Users\CUI\.conda\envs\py3tf2_0\lib\site-packages\tensorflow_core\python\framework\op_def_library.py", line 793, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\CUI\.conda\envs\py3tf2_0\lib\site-packages\tensorflow_core\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\Users\CUI\.conda\envs\py3tf2_0\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3360, in create_op
    attrs, op_def, compute_device)
  File "C:\Users\CUI\.conda\envs\py3tf2_0\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3429, in _create_op_internal
    op_def=op_def)
  File "C:\Users\CUI\.conda\envs\py3tf2_0\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1751, in __init__
    self._traceback = tf_stack.extract_stack()
```

**Comment by oanush** [comment]
@DenisUllmann ,
Thank you for reporting the issue, looks like the code given is incomplete can you please provide standalone code to reproduce the issue? 
Also can you try reducing the `batch size `and see is if the error is not faced ?

**Comment by DenisUllmann** [comment]
@oanush ,
Please find bellow a standalone code with `tensorflow_datasets` that reproduces the same error with filtering, and that works fine without filtering (removing `.filter(lambda x: x['label'] == 0)`). If I put `batch size` to 1, the same error raises.

```
import tensorflow as tf
import tensorflow_datasets as tfds

from glob import glob

data_dir = "."
data_files_pat = "train.tfrecords"
number_of_clusters = 10
number_of_epochs = 10

data_files = glob(data_dir + "/" + data_files_pat)
print(len(data_files), 'files found')

def input_fn(tfrecords_path):
    data_builder = tfds.builder('mnist')
    data_builder.download_and_prepare()
    
    dataset = (
        data_builder.as_dataset(split=tfds.Split.TRAIN)
        .filter(lambda x: x['label'] == 0)
        .map(lambda x: {'image': tf.reshape(x['image'], [-1,]), 'label': x['label']})
        .batch(1024)
        .prefetch(1024)
     )
    iterator = tf.compat.v1.data.make_one_shot_iterator(dataset)
    batch_feats = iterator.get_next()
    return batch_feats

train_spec_kmeans = tf.estimator.TrainSpec(input_fn = lambda: input_fn(data_files) , max_steps=10)
eval_spec_kmeans = tf.estimator.EvalSpec(input_fn = lambda: input_fn(data_files) )

KMeansEstimator = tf.compat.v1.estimator.experimental.KMeans(
    num_clusters=number_of_clusters,
    feature_columns = [tf.feature_column.numeric_column(
        key='image',
        dtype=tf.float64,
        shape=(784,)
    )],
    use_mini_batch=True)

tf.estimator.train_and_evaluate(KMeansEstimator, train_spec_kmeans, eval_spec_kmeans)
```

Result without filtering:
```
INFO:tensorflow:Loss for final step: 2652678100.0.
({'loss': 2667317500.0, 'score': 2667317500.0, 'global_step': 10}, [])
```

With filtering:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\CUI\.conda\envs\py3tf2_0\lib\site-packages\tensorflow_estimator\python\estimator\training.py", line 473, in train_and_evaluate
    return executor.run()
  File "C:\Users\CUI\.conda\envs\py3tf2_0\lib\site-packages\tensorflow_estimator\python\estimator\training.py", line 613, in run
    return self.run_local()
  File "C:\Users\CUI\.conda\envs\py3tf2_0\lib\site-packages\tensorflow_estimator\python\estimator\training.py", line 714, in run_local
    saving_listeners=saving_listeners)
  File "C:\Users\CUI\.conda\envs\py3tf2_0\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 370, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "C:\Users\CUI\.conda\envs\py3tf2_0\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1160, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "C:\Users\CUI\.conda\envs\py3tf2_0\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1194, in _train_model_default
    saving_listeners)
  File "C:\Users\CUI\.conda\envs\py3tf2_0\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1489, in _train_with_estimator_spec
    log_step_count_steps=log_step_count_steps) as mon_sess:
  File "C:\Users\CUI\.conda\envs\py3tf2_0\lib\site-packages\tensorflow_core\python\training\monitored_session.py", line 584, in MonitoredTrainingSession
    stop_grace_period_secs=stop_grace_period_secs)
  File "C:\Users\CUI\.conda\envs\py3tf2_0\lib\site-packages\tensorflow_core\python\training\monitored_session.py", line 1014, in __init__
    stop_grace_period_secs=stop_grace_period_secs)
  File "C:\Users\CUI\.conda\envs\py3tf2_0\lib\site-packages\tensorflow_core\python\training\monitored_session.py", line 725, in __init__
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "C:\Users\CUI\.conda\envs\py3tf2_0\lib\site-packages\tensorflow_core\python\training\monitored_session.py", line 1207, in __init__
    _WrappedSession.__init__(self, self._create_session())
  File "C:\Users\CUI\.conda\envs\py3tf2_0\lib\site-packages\tensorflow_core\python\training\monitored_session.py", line 1212, in _create_session
    return self._sess_creator.create_session()
  File "C:\Users\CUI\.conda\envs\py3tf2_0\lib\site-packages\tensorflow_core\python\training\monitored_session.py", line 885, in create_session
    hook.after_create_session(self.tf_sess, self.coord)
  File "C:\Users\CUI\.conda\envs\py3tf2_0\lib\site-packages\tensorflow_estimator\python\estimator\canned\kmeans.py", line 105, in after_create_session
    session.run(self._init_op)
  File "C:\Users\CUI\.conda\envs\py3tf2_0\lib\site-packages\tensorflow_core\python\client\session.py", line 956, in run
    run_metadata_ptr)
  File "C:\Users\CUI\.conda\envs\py3tf2_0\lib\site-packages\tensorflow_core\python\client\session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\CUI\.conda\envs\py3tf2_0\lib\site-packages\tensorflow_core\python\client\session.py", line 1359, in _do_run
    run_metadata)
  File "C:\Users\CUI\.conda\envs\py3tf2_0\lib\site-packages\tensorflow_core\python\client\session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.OutOfRangeError: 2 root error(s) found.
  (0) Out of range: End of sequence
         [[node IteratorGetNext (defined at C:\Users\CUI\.conda\envs\py3tf2_0\lib\site-packages\tensorflow_core\python\framework\ops.py:1751) ]]
         [[IteratorGetNext/_33]]
  (1) Out of range: End of sequence
         [[node IteratorGetNext (defined at C:\Users\CUI\.conda\envs\py3tf2_0\lib\site-packages\tensorflow_core\python\framework\ops.py:1751) ]]
0 successful operations.
0 derived errors ignored.

Original stack trace for 'IteratorGetNext':
  File "<stdin>", line 1, in <module>
  File "C:\Users\CUI\.conda\envs\py3tf2_0\lib\site-packages\tensorflow_estimator\python\estimator\training.py", line 473, in train_and_evaluate
    return executor.run()
  File "C:\Users\CUI\.conda\envs\py3tf2_0\lib\site-packages\tensorflow_estimator\python\estimator\training.py", line 613, in run
    return self.run_local()
  File "C:\Users\CUI\.conda\envs\py3tf2_0\lib\site-packages\tensorflow_estimator\python\estimator\training.py", line 714, in run_local
    saving_listeners=saving_listeners)
  File "C:\Users\CUI\.conda\envs\py3tf2_0\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 370, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "C:\Users\CUI\.conda\envs\py3tf2_0\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1160, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "C:\Users\CUI\.conda\envs\py3tf2_0\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1187, in _train_model_default
    input_fn, ModeKeys.TRAIN))
  File "C:\Users\CUI\.conda\envs\py3tf2_0\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1024, in _get_features_and_labels_from_input_fn
    self._call_input_fn(input_fn, mode))
  File "C:\Users\CUI\.conda\envs\py3tf2_0\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1115, in _call_input_fn
    return input_fn(**kwargs)
  File "<stdin>", line 1, in <lambda>
  File "<stdin>", line 13, in input_fn
  File "C:\Users\CUI\.conda\envs\py3tf2_0\lib\site-packages\tensorflow_core\python\data\ops\iterator_ops.py", line 426, in get_next
    name=name)
  File "C:\Users\CUI\.conda\envs\py3tf2_0\lib\site-packages\tensorflow_core\python\ops\gen_dataset_ops.py", line 2500, in iterator_get_next
    output_shapes=output_shapes, name=name)
  File "C:\Users\CUI\.conda\envs\py3tf2_0\lib\site-packages\tensorflow_core\python\framework\op_def_library.py", line 793, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\CUI\.conda\envs\py3tf2_0\lib\site-packages\tensorflow_core\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\Users\CUI\.conda\envs\py3tf2_0\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3360, in create_op
    attrs, op_def, compute_device)
  File "C:\Users\CUI\.conda\envs\py3tf2_0\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3429, in _create_op_internal
    op_def=op_def)
  File "C:\Users\CUI\.conda\envs\py3tf2_0\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1751, in __init__
    self._traceback = tf_stack.extract_stack()
```

**Comment by oanush** [comment]
Issue replicating with given code for tf-2.0, kindly find the [gist](https://colab.sandbox.google.com/drive/14oludAJaWJD1YM6H_Tb7YbaJtB3_0nVh#scrollTo=eDPlqeEMazJe) colab.Thanks!

**Comment by gowthamkpr** [comment]
I used the filter function outside and the issue is not replicating. Please find the github gist [here](https://colab.sandbox.google.com/gist/gowthamkpr/c63e16d639e53c20f0723a54b0a77517/34200.ipynb). Thanks!

**Comment by xiejw** [comment]
I no longer work in this codebase. Please find appropriate owner.

**Comment by karmel** [comment]
This is possibly due to the ways in which the Kmeans estimator is trying to check the number of dataset steps, but we do not currently have the availability to dig into this. @DenisUllmann , is this something you can look into and submit a fix for?

**Comment by Saduf2019** [comment]
Issue replicating with given code for tf-2.3, please find [gist here](https://colab.research.google.com/gist/Saduf2019/b63e790d96b37fa0e4ee6bf758f80de3/untitled368.ipynb)

**Comment by sachinprasadhs** [comment]
I was able to reproduce the issue in Tensorflow 2.4, please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/7afb880722038a5aa0c844de049f7a96/34200.ipynb).

**Comment by sushreebarsa** [comment]
Was able to replicate the issue with TF [v2.5 ](https://colab.research.google.com/gist/sushreebarsa/a78535d14a346f427856e778e262a253/untitled244.ipynb#scrollTo=VuLjYwPPMRYT)& TF [2.6.0-dev20210606](https://colab.research.google.com/gist/sushreebarsa/0b398d7ec9debbf4c556aff7df8b6333/untitled245.ipynb),please find the gists here ..Thanks!

**Comment by kumariko** [comment]
I was able to reproduce the issue in Tensorflow 2.6, please find the gist [**`here`**](https://colab.research.google.com/gist/kumariko/e565a5148e12171e18c4f9529d98a96e/untitled245.ipynb#scrollTo=g7u0Qqz_sUuG).

**Comment by sachinprasadhs** [comment]
Hi, Could you please migrate from Estimator to Keras API which will enable you to perform the aforementioned tasks, such as [model building](https://www.tensorflow.org/guide/keras/custom_layers_and_models), gradient application, [training](https://www.tensorflow.org/guide/keras/customizing_what_happens_in_fit), evaluation, and prediction.
Refer Migration guide here https://www.tensorflow.org/guide/migrate/migrating_estimator for more details. Thanks!

Along with that you need to migrate feature columns to keras preprocessing.
For more details refer [Migrate tf.feature_columns to Keras preprocessing layers](https://www.tensorflow.org/guide/migrate/migrating_feature_columns)
Also, refer the list of API's fate under feature column here https://www.tensorflow.org/api_docs/python/tf/feature_column?version=nightly
