### ISSUE TITLE
Could not create cudnn handle: CUDNN_STATUS_NOT_INITIALIZED

### ISSUE THREAD

**Issue by ucasiggcas** [tensorflow/tensorflow#34214]
**System information**
- OS Platform and Distribution ( Linux Ubuntu 16.04):
- TensorFlow installed from (pip):
- TensorFlow version: 1.14.0 gpu
- Python version: 3.6.4
- Installed using virtualenv? pip? also have anaconda
- CUDA/cuDNN version: cuda 10.0 ,cudnn how to know the version ?
- GPU model and memory:
GPU RTX 2080 10989MiB

```
Train on 15285 samples, validate on 3822 samples
Epoch 1/100
2019-11-13 11:58:28.507273: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10.0
2019-11-13 11:58:28.790550: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2019-11-13 11:58:28.791219: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_NOT_INITIALIZED
2019-11-13 11:58:28.791275: E tensorflow/stream_executor/cuda/cuda_dnn.cc:337] Possibly insufficient driver version: 410.48.0
2019-11-13 11:58:28.791290: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_NOT_INITIALIZED
2019-11-13 11:58:28.791312: E tensorflow/stream_executor/cuda/cuda_dnn.cc:337] Possibly insufficient driver version: 410.48.0
Traceback (most recent call last):
  File "main_ResNet.py", line 229, in <module>
    shuffle=True)
  File "/./anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 1239, in fit
    validation_freq=validation_freq)
  File "/./anaconda3/lib/python3.6/site-packages/keras/engine/training_arrays.py", line 196, in fit_loop
    outs = fit_function(ins_batch)
  File "/./anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/backend.py", line 3292, in __call__
    run_metadata=self.run_metadata)
  File "/./anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1458, in __call__
    run_metadata_ptr)
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node conv2d_1/convolution}}]]
	 [[Mean/_417]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node conv2d_1/convolution}}]]
0 successful operations.
0 derived errors ignored.

```

any advice or suggestion will be appriciated.
Thx

**Comment by oanush** [comment]
@ucasiggcas ,
Can you please go through this [link](https://stackoverflow.com/questions/43147983/could-not-create-cudnn-handle-cudnn-status-internal-error) and let us know if it was useful?Thanks!

**Comment by ucasiggcas** [comment]
`sudo rm -rf ~/.nv/`
this is no use

**Comment by oanush** [comment]
@ucasiggcas ,
Can you share a simple and standalone code to reproduce the issue? thanks!

**Comment by ymodak** [comment]
First thing will be to check if compatible CUDA, cuDNN drivers are installed correctly. Then you may try gpu memory resources management by allowing gpu memory growth.  

**allow_growth** option, attempts to allocate only as much GPU memory based on runtime allocations: it starts out allocating very little memory, and as Sessions get run and more GPU memory is needed, it extend the GPU memory region needed by the TensorFlow process.
  
To know more see https://www.tensorflow.org/guide/using_gpu#allowing_gpu_memory_growth   
You can try Allowing GPU memory growth with:
```python
config = tf.ConfigProto()
config.gpu_options.allow_growth = True
sess = tf.Session(config=config)
```

**Comment by ucasiggcas** [comment]
@ymodak 
Thanks，
I have tried this,but not success
of course ,I check the Version of the CUDA and cuDNN, they are compatible,
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130
 NVIDIA-SMI 410.129      Driver Version: 410.129      CUDA Version: 10.0  
```
If you read chinese, see this [ blog](https://blog.csdn.net/SPESEG/article/details/103042752) for details.

thanks for your kind help

**Comment by ucasiggcas** [comment]
@oanush 
Sorry, this problem is about **Install tf-gpu** ,not the code

**Comment by ucasiggcas** [comment]
Today  I have tried again,
installed tf-gpu==1.14 by conda in new environment
but the error makes me confused,

but when I use tf-gpu==1.15, I got success, so I close the issue now
