### ISSUE TITLE
tensorflow java 1.15.0 failed to load native lib

### ISSUE THREAD

**Issue by sharkdtu** [tensorflow/tensorflow#34256]
**Describe the current behavior**
```
org.tensorflow.NativeLibrary: tryLoadLibraryFailed: no tensorflow_jni in java.library.path
org.tensorflow.NativeLibrary: jniResourceName: org/tensorflow/native/linux-x86_64/libtensorflow_jni.so
org.tensorflow.NativeLibrary: frameworkResourceName: org/tensorflow/native/linux-x86_64/libtensorflow_framework.so
org.tensorflow.NativeLibrary: org/tensorflow/native/linux-x86_64/libtensorflow_framework.so not found. This is fine assuming org/tensorflow/native/linux-x86_64/libtensorflow_jni.so is not built to depend on it.
org.tensorflow.NativeLibrary: extracting native library to: /xxx/tmp/tensorflow_native_libraries-1573652659702-0/libtensorflow_jni.so
org.tensorflow.NativeLibrary: copied 154073736 bytes to /xxx/tmp/tensorflow_native_libraries-1573652659702-0/libtensorflow_jni.so
java.lang.UnsatisfiedLinkError:/xxx/tmp/tensorflow_native_libraries-1573652659702-0/libtensorflow_jni.so: libtensorflow_framework.so.1: 无法打开共享对象文件: 没有那个文件或目录
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at org.tensorflow.NativeLibrary.load(NativeLibrary.java:101)
	at org.tensorflow.TensorFlow.init(TensorFlow.java:67)
	at org.tensorflow.TensorFlow.<clinit>(TensorFlow.java:82)
	at org.tensorflow.SavedModelBundle.<clinit>(SavedModelBundle.java:170)
```

**Describe the expected behavior**
no exceptions

**Comment by sharkdtu** [comment]
I found the tensorflow jar does not include `org/tensorflow/native/linux-x86_64/libtensorflow_framework.so`, but include `org/tensorflow/native/linux-x86_64/libtensorflow_framework.so.1`, so it failed to copy `libtensorflow_framework.so` to tmp directory when loading the native library.

**Comment by sharkdtu** [comment]
`NativeLibrary.getMajorVersionNumber` returns `null` when libtensorflow and libtensorflow_jni jar were shaded to my jar

**Comment by mttsndrs** [comment]
I had the same problem (using a shaded jar, `NativeLibrary.getMajorVersionNumber` returned null). But since your fix wasn't yet available in the 1.15 release, I worked around it by adding an `Implementation-Version` that starts with `1.` to the shaded jar's manifest using Maven's `ManifestResourceTransformer`.

**Comment by geometrikal** [comment]
@mttsndrs Could you share what you did with the manifest resource transformer? I'm having a similar problem.

**Comment by mttsndrs** [comment]
@geometrikal I added this to the pom.xml:
```
    <properties>
        <tensorflow.version>1.15.0</tensorflow.version>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <configuration>
                    <transformers combine.self="override">
                        <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                            <manifestEntries>
                                <!--
                                Note: When loaded from a jar, tensorflow will use the
                                "Implementation-Version" tag in the jar's manifest to identify the
                                tensorflow_framework lib to extract. When packaged in a shaded jar,
                                this can cause problems locating the correct version of the
                                tensorflow library.
                                By overriding the "Implementation-Version" tag here, we ensure that
                                the correct tensorflow_framework lib gets extracted at runtime.
                                -->
                                <Implementation-Version>${tensorflow.version}</Implementation-Version>
                            </manifestEntries>
                        </transformer>
                    </transformers>
                </configuration>
            </plugin>
        </plugins>
    </build>
```
