### ISSUE TITLE
speech_commands: Range cannot be empty (low >= high) unless no samples are taken

### ISSUE THREAD

**Issue by natepmay** [tensorflow/tensorflow#34278]
I'm using the speech_commands example and trying to load my own set of wav files, which I've organized according to the tutorial. Here's the command I'm entering on the terminal:
python3 /Users/etc/train.py \
--data_url= \
--data_dir=/Users/etc/trial_classes \
--wanted_words=randomclass1,randomclass2 \
--sample_rate=44100

It's finding the files (so I've truncated the filepaths with "etc" below & above), but raises this error:

Traceback (most recent call last):
  File "/Users/etc/speech_commands/train.py", line 508, in <module>
    tf.compat.v1.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/Users/etc/speech_commands/train.py", line 237, in main
    FLAGS.background_volume, time_shift_samples, 'training', sess)
  File "/Users/etc/speech_commands/input_data.py", line 575, in get_data
    background_index = np.random.randint(len(self.background_data))
  File "mtrand.pyx", line 992, in mtrand.RandomState.randint
ValueError: Range cannot be empty (low >= high) unless no samples are taken

I'm using
MacOs 10.13.6
Tensorflow version 2.0.0
Python version: 3.7.3

New to this so I appreciate the patience if I've done something dumb. Thanks!

**Comment by natepmay** [comment]
Okay figured this out. The _background_noise_ folder has to be included in the directory alongside the folders with the wav files. On further reading I probably could have assumed this from reading the tutorial, but maybe worth clarifying in the paragraph on "Custom Training Data." (Here's the tutorial I'm referring to: https://github.com/tensorflow/docs/blob/master/site/en/r1/tutorials/sequences/audio_recognition.md).
