### ISSUE TITLE
Couldn't quantize a model with QUANTIZED_UINT8 if output layer don't have activation

### ISSUE THREAD

**Issue by dojipkim** [tensorflow/tensorflow#34289]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- TensorFlow installed from (source or binary): installed a binary with Conda
- TensorFlow version (or github SHA if from source): 1.14.0

**Command used to run the converter or code if you’re using the Python API**

```
import tensorflow as tf
from tensorflow import keras

import numpy as np
import matplotlib.pyplot as plt

fashion_mnist = keras.datasets.fashion_mnist
(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()

train_images = train_images / 255.0
test_images = test_images / 255.0

def build_keras_model():
  return keras.Sequential([
    keras.layers.Flatten(input_shape=(28,28)),
    keras.layers.Dense(128, activation='relu'),
    keras.layers.BatchNormalization(),
    keras.layers.Dense(10)
  ])

train_graph = tf.Graph()
train_sess = tf.Session(graph=train_graph)

keras.backend.set_session(train_sess)
with train_graph.as_default():
  train_model = build_keras_model()

  tf.contrib.quantize.create_training_graph(input_graph=train_graph, quant_delay=100)
  train_sess.run(tf.global_variables_initializer())

  train_model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
  )
  train_model.fit(train_images, train_labels, epochs=5)

  saver = tf.train.Saver()
  saver.save(train_sess, 'checkpoints')

eval_graph = tf.Graph()
eval_sess = tf.Session(graph=eval_graph)

keras.backend.set_session(eval_sess)

with eval_graph.as_default():
  keras.backend.set_learning_phase(0)
  eval_model = build_keras_model()
  tf.contrib.quantize.create_eval_graph(input_graph=eval_graph)
  eval_graph_def = eval_graph.as_graph_def()
  saver = tf.train.Saver()
  saver.restore(eval_sess, 'checkpoints')

  frozen_graph_def = tf.graph_util.convert_variables_to_constants(
    eval_sess,
    eval_graph_def,
    [eval_model.output.op.name]
  )
  with open('frozen_model.pb', 'wb') as f:
    f.write(frozen_graph_def.SerializeToString())

converter = tf.lite.TFLiteConverter.from_frozen_graph(
  'frozen_model.pb',
  ['flatten_input'],
  ['dense_1/BiasAdd'])
converter.inference_type = tf.lite.constants.QUANTIZED_UINT8
input_arrays = converter.get_input_arrays()
converter.quantized_input_stats = {input_arrays[0] : (0, 255)}  # mean, std_dev
tflite_model = converter.convert()
open('model.tflite', 'wb').write(tflite_model)
```

**The output from the converter invocation**

```
---------------------------------------------------------------------------
ConverterError                            Traceback (most recent call last)
<ipython-input-18-c82690488195> in <module>
      6 input_arrays = converter.get_input_arrays()
      7 converter.quantized_input_stats = {input_arrays[0] : (0, 255)}  # mean, std_dev
----> 8 tflite_model = converter.convert()
      9 open('model.tflite', 'wb').write(tflite_model)

~/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/lite/python/lite.py in convert(self)
    896           input_tensors=self._input_tensors,
    897           output_tensors=self._output_tensors,
--> 898           **converter_kwargs)
    899     else:
    900       result = _toco_convert_graph_def(

~/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/lite/python/convert.py in toco_convert_impl(input_data, input_tensors, output_tensors, *args, **kwargs)
    402   data = toco_convert_protos(model_flags.SerializeToString(),
    403                              toco_flags.SerializeToString(),
--> 404                              input_data.SerializeToString())
    405   return data
    406 

~/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/lite/python/convert.py in toco_convert_protos(model_flags_str, toco_flags_str, input_data_str)
    170       stderr = _try_convert_to_unicode(stderr)
    171       raise ConverterError(
--> 172           "TOCO failed. See console for info.\n%s\n%s\n" % (stdout, stderr))
    173   finally:
    174     # Must manually cleanup files.

ConverterError: TOCO failed. See console for info.
2019-11-14 14:46:19.525955: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 39 operators, 63 arrays (0 quantized)
2019-11-14 14:46:19.526224: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 39 operators, 63 arrays (0 quantized)
2019-11-14 14:46:19.527392: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 1: 10 operators, 18 arrays (1 quantized)
2019-11-14 14:46:19.527775: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 2: 9 operators, 17 arrays (1 quantized)
2019-11-14 14:46:19.527893: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 3: 8 operators, 15 arrays (1 quantized)
2019-11-14 14:46:19.527982: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before pre-quantization graph transformations: 8 operators, 15 arrays (1 quantized)
2019-11-14 14:46:19.528015: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After pre-quantization graph transformations pass 1: 5 operators, 12 arrays (1 quantized)
2019-11-14 14:46:19.528050: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Group bidirectional sequence lstm/rnn: 5 operators, 12 arrays (1 quantized)
2019-11-14 14:46:19.528084: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before quantization graph transformations: 5 operators, 12 arrays (1 quantized)
2019-11-14 14:46:19.529767: W tensorflow/lite/toco/graph_transformations/quantize.cc:132] Constant array batch_normalization/batchnorm/mul lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2019-11-14 14:46:19.529796: W tensorflow/lite/toco/graph_transformations/quantize.cc:132] Constant array batch_normalization/batchnorm/sub lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2019-11-14 14:46:19.529847: F tensorflow/lite/toco/graph_transformations/quantize.cc:149] Array dense_1/BiasAdd does not have MinMax information, and is not a constant array. Cannot proceed with quantization.
Fatal Python error: Aborted

Current thread 0x00007f40e79dd700 (most recent call first):
  File "/home/dojip.kim/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 33 in execute
  File "/home/dojip.kim/anaconda3/envs/tensorflow/lib/python3.6/site-packages/absl/app.py", line 251 in _run_main
  File "/home/dojip.kim/anaconda3/envs/tensorflow/lib/python3.6/site-packages/absl/app.py", line 300 in run
  File "/home/dojip.kim/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 40 in run
  File "/home/dojip.kim/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 59 in main
  File "/home/dojip.kim/anaconda3/envs/tensorflow/bin/toco_from_protos", line 11 in <module>
```

**Also, please include a link to the saved model or GraphDef**

```
# Put link here or attach to the issue.
```

**Failure details**
I could quantize a model with QUNATIZED_UINT8 if output layer have activation like 'softmax'.  I want to quantize a model without the activation function for the final output. In that case, I couldn't quantize it.

2019-11-14 14:46:19.529847: F tensorflow/lite/toco/graph_transformations/quantize.cc:149] Array dense_1/BiasAdd does not have MinMax information, and is not a constant array. Cannot proceed with quantization.
Fatal Python error: Aborted

Please let me know how to quantize a model.

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by dojipkim** [comment]
Here are the node names and operations of the frozen_model.pb
```
flatten_input => Placeholder
flatten/Shape => Shape
flatten/strided_slice/stack => Const
flatten/strided_slice/stack_1 => Const
flatten/strided_slice/stack_2 => Const
flatten/strided_slice => StridedSlice
flatten/Reshape/shape/1 => Const
flatten/Reshape/shape => Pack
flatten/Reshape => Reshape
dense/kernel => Const
dense/bias => Const
dense/MatMul/ReadVariableOp => Identity
dense/MatMul => MatMul
dense/BiasAdd/ReadVariableOp => Identity
dense/BiasAdd => BiasAdd
dense/Relu => Relu
batch_normalization/gamma => Const
batch_normalization/beta => Const
batch_normalization/moving_mean => Const
batch_normalization/moving_variance => Const
batch_normalization/batchnorm/ReadVariableOp => Identity
batch_normalization/batchnorm/add/y => Const
batch_normalization/batchnorm/add => Add
batch_normalization/batchnorm/Rsqrt => Rsqrt
batch_normalization/batchnorm/mul/ReadVariableOp => Identity
batch_normalization/batchnorm/mul => Mul
batch_normalization/batchnorm/mul_1 => Mul
batch_normalization/batchnorm/ReadVariableOp_1 => Identity
batch_normalization/batchnorm/mul_2 => Mul
batch_normalization/batchnorm/ReadVariableOp_2 => Identity
batch_normalization/batchnorm/sub => Sub
batch_normalization/batchnorm/add_1 => Add
dense_1/kernel => Const
dense_1/bias => Const
dense_1/MatMul/ReadVariableOp => Identity
dense_1/MatMul => MatMul
dense_1/BiasAdd/ReadVariableOp => Identity
dense_1/BiasAdd => BiasAdd
dense/weights_quant/min => Const
dense/weights_quant/min/read => Identity
dense/weights_quant/max => Const
dense/weights_quant/max/read => Identity
dense/weights_quant/FakeQuantWithMinMaxVars => FakeQuantWithMinMaxVars
dense/act_quant/min => Const
dense/act_quant/min/read => Identity
dense/act_quant/max => Const
dense/act_quant/max/read => Identity
dense/act_quant/FakeQuantWithMinMaxVars => FakeQuantWithMinMaxVars
dense_1/weights_quant/min => Const
dense_1/weights_quant/min/read => Identity
dense_1/weights_quant/max => Const
dense_1/weights_quant/max/read => Identity
dense_1/weights_quant/FakeQuantWithMinMaxVars => FakeQuantWithMinMaxVars
batch_normalization/batchnorm/mul_1/activation_Mul_quant/min => Const
batch_normalization/batchnorm/mul_1/activation_Mul_quant/min/read => Identity
batch_normalization/batchnorm/mul_1/activation_Mul_quant/max => Const
batch_normalization/batchnorm/mul_1/activation_Mul_quant/max/read => Identity
batch_normalization/batchnorm/mul_1/activation_Mul_quant/FakeQuantWithMinMaxVars => FakeQuantWithMinMaxVars
batch_normalization/batchnorm/add_1/activation_Add_quant/min => Const
batch_normalization/batchnorm/add_1/activation_Add_quant/min/read => Identity
batch_normalization/batchnorm/add_1/activation_Add_quant/max => Const
batch_normalization/batchnorm/add_1/activation_Add_quant/max/read => Identity
batch_normalization/batchnorm/add_1/activation_Add_quant/FakeQuantWithMinMaxVars => FakeQuantWithMinMaxVars
```
