### ISSUE TITLE
tensorflow.lite.python.convert.ConverterError: TOCO failed. See console for info

### ISSUE THREAD

**Issue by fsy8515-dev** [tensorflow/tensorflow#34301]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary):
- TensorFlow version (or github SHA if from source):

**Command used to run the converter or code if you’re using the Python API**

```
# Copy and paste here the exact command
```

**The output from the converter invocation**

```
# Copy and paste the output here.
```

**Also, please include a link to the saved model or GraphDef**

```
# Put link here or attach to the issue.
```

**Failure details**
If the conversion is successful, but the generated model is wrong,
state what is wrong:
- Producing wrong results and/or decrease in accuracy
- Producing correct results, but the model is slower than expected (model generated from old converter)

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ravikyram** [comment]
Did you try using [TFLITE_BUILTINS, SELECT_TF_OPS ](https://www.tensorflow.org/lite/guide/ops_select)to convert your model? Thanks!

**Comment by mftun** [comment]
Same problem when run documentation example from [here](https://www.tensorflow.org/lite/convert/cmdline_examples#using_--output_formatgraphviz_dot_)

```
curl https://storage.googleapis.com/download.tensorflow.org/models/mobilenet_v1_0.50_128_frozen.tgz \
  | tar xzv -C /tmp

tflite_convert \
  --graph_def_file=/tmp/mobilenet_v1_0.50_128/frozen_graph.pb \
  --output_file=/tmp/foo.dot \
  --output_format=GRAPHVIZ_DOT \
  --input_shape=1,128,128,3 \
  --input_arrays=input \
  --output_arrays=MobilenetV1/Predictions/Reshape_1
```
Output

```
Traceback (most recent call last):
  File "/home/install/.local/bin/tflite_convert", line 11, in <module>
    sys.exit(main())
  File "/home/install/.local/lib/python2.7/site-packages/tensorflow/lite/python/tflite_convert.py", line 503, in main
    app.run(main=run_main, argv=sys.argv[:1])
  File "/home/install/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/install/.local/lib/python2.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/install/.local/lib/python2.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/home/install/.local/lib/python2.7/site-packages/tensorflow/lite/python/tflite_convert.py", line 499, in run_main
    _convert_tf1_model(tflite_flags)
  File "/home/install/.local/lib/python2.7/site-packages/tensorflow/lite/python/tflite_convert.py", line 193, in _convert_tf1_model
    output_data = converter.convert()
  File "/home/install/.local/lib/python2.7/site-packages/tensorflow/lite/python/lite.py", line 898, in convert
    **converter_kwargs)
  File "/home/install/.local/lib/python2.7/site-packages/tensorflow/lite/python/convert.py", line 404, in toco_convert_impl
    input_data.SerializeToString())
  File "/home/install/.local/lib/python2.7/site-packages/tensorflow/lite/python/convert.py", line 172, in toco_convert_protos
    "TOCO failed. See console for info.\n%s\n%s\n" % (stdout, stderr))
tensorflow.lite.python.convert.ConverterError: TOCO failed. See console for info.
/bin/sh: 1: toco_from_protos: not found
```

**Comment by mftun** [comment]
Check that `~/.local/bin` in PATH.

**Comment by ravikyram** [comment]
@fsy8515-dev 

Any update on this issue please? Thanks!

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
