### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow'

### ISSUE THREAD

**Issue by niccle27** [tensorflow/tensorflow#34318]
**System information**
- Linux Ubuntu 18.04
- TensorFlow-gpu installed from pip :
- TensorFlow-gpu version: 2.0.0

- Python version:3.6.8 
- Installed using pip
- CUDA/cuDNN version:10
- GPU model and memory: 1050 mobile

I followed the installation tutorial for tensorflow GPU, specified in
https://www.tensorflow.org/install/gpu

The command "pip3 show tensorflow-gpu " has the following output : 
 ```bash
Name: tensorflow-gpu
Version: 2.0.0
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: /home/niccle27/.local/lib/python3.6/site-packages
Requires: tensorflow-estimator, keras-preprocessing, astor, tensorboard, keras-applications, absl-py, six, protobuf, numpy, termcolor, gast, google-pasta, opt-einsum, grpcio, wheel, wrapt
Required-by: 
```

i made sure that cuda was working properly and it does.

when importing the tensorflow package, i'm getting the following error :
 
 ```python
import tensorflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'tensorflow'
```

**Comment by mihaimaruseac** [comment]
Please post the **full** output of (eventually in a virtualenv)

```
python -m pip install tensorflow && python -c "import tensorflow"
```

**Comment by niccle27** [comment]
Well that command would work. i have no problem installing and running the CPU version of tensorflow. My problem only concerns the GPU version. 

Here is your command output in my system : 
```bash
python -m pip install tensorflow-gpu && python -c "import tensorflow"
Requirement already satisfied: tensorflow-gpu in ./.local/lib/python3.6/site-packages (2.0.0)
Requirement already satisfied: numpy<2.0,>=1.16.0 in ./.local/lib/python3.6/site-packages (from tensorflow-gpu) (1.17.1)
Requirement already satisfied: opt-einsum>=2.3.2 in ./.local/lib/python3.6/site-packages (from tensorflow-gpu) (3.1.0)
Requirement already satisfied: six>=1.10.0 in ./.local/lib/python3.6/site-packages (from tensorflow-gpu) (1.12.0)
Requirement already satisfied: keras-preprocessing>=1.0.5 in ./.local/lib/python3.6/site-packages (from tensorflow-gpu) (1.1.0)
Requirement already satisfied: google-pasta>=0.1.6 in ./.local/lib/python3.6/site-packages (from tensorflow-gpu) (0.1.8)
Requirement already satisfied: tensorflow-estimator<2.1.0,>=2.0.0 in ./.local/lib/python3.6/site-packages (from tensorflow-gpu) (2.0.1)
Requirement already satisfied: protobuf>=3.6.1 in ./.local/lib/python3.6/site-packages (from tensorflow-gpu) (3.10.0)
Requirement already satisfied: keras-applications>=1.0.8 in ./.local/lib/python3.6/site-packages (from tensorflow-gpu) (1.0.8)
Requirement already satisfied: grpcio>=1.8.6 in ./.local/lib/python3.6/site-packages (from tensorflow-gpu) (1.24.3)
Requirement already satisfied: gast==0.2.2 in ./.local/lib/python3.6/site-packages (from tensorflow-gpu) (0.2.2)
Requirement already satisfied: wheel>=0.26 in /usr/lib/python3/dist-packages (from tensorflow-gpu) (0.30.0)
Requirement already satisfied: absl-py>=0.7.0 in ./.local/lib/python3.6/site-packages (from tensorflow-gpu) (0.8.1)
Requirement already satisfied: astor>=0.6.0 in ./.local/lib/python3.6/site-packages (from tensorflow-gpu) (0.8.0)
Requirement already satisfied: termcolor>=1.1.0 in ./.local/lib/python3.6/site-packages (from tensorflow-gpu) (1.1.0)
Requirement already satisfied: tensorboard<2.1.0,>=2.0.0 in ./.local/lib/python3.6/site-packages (from tensorflow-gpu) (2.0.1)
Requirement already satisfied: wrapt>=1.11.1 in ./.local/lib/python3.6/site-packages (from tensorflow-gpu) (1.11.2)
Requirement already satisfied: setuptools in ./.local/lib/python3.6/site-packages (from protobuf>=3.6.1->tensorflow-gpu) (41.2.0)
Requirement already satisfied: h5py in ./.local/lib/python3.6/site-packages (from keras-applications>=1.0.8->tensorflow-gpu) (2.10.0)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in ./.local/lib/python3.6/site-packages (from tensorboard<2.1.0,>=2.0.0->tensorflow-gpu) (0.4.1)
Requirement already satisfied: google-auth<2,>=1.6.3 in ./.local/lib/python3.6/site-packages (from tensorboard<2.1.0,>=2.0.0->tensorflow-gpu) (1.6.3)
Requirement already satisfied: werkzeug>=0.11.15 in ./.local/lib/python3.6/site-packages (from tensorboard<2.1.0,>=2.0.0->tensorflow-gpu) (0.16.0)
Requirement already satisfied: markdown>=2.6.8 in ./.local/lib/python3.6/site-packages (from tensorboard<2.1.0,>=2.0.0->tensorflow-gpu) (3.1.1)
Requirement already satisfied: requests-oauthlib>=0.7.0 in ./.local/lib/python3.6/site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.1.0,>=2.0.0->tensorflow-gpu) (1.2.0)
Requirement already satisfied: cachetools>=2.0.0 in ./.local/lib/python3.6/site-packages (from google-auth<2,>=1.6.3->tensorboard<2.1.0,>=2.0.0->tensorflow-gpu) (3.1.1)
Requirement already satisfied: rsa>=3.1.4 in ./.local/lib/python3.6/site-packages (from google-auth<2,>=1.6.3->tensorboard<2.1.0,>=2.0.0->tensorflow-gpu) (4.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in ./.local/lib/python3.6/site-packages (from google-auth<2,>=1.6.3->tensorboard<2.1.0,>=2.0.0->tensorflow-gpu) (0.2.7)
Requirement already satisfied: requests>=2.0.0 in ./.local/lib/python3.6/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.1.0,>=2.0.0->tensorflow-gpu) (2.22.0)
Requirement already satisfied: oauthlib>=3.0.0 in ./.local/lib/python3.6/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.1.0,>=2.0.0->tensorflow-gpu) (3.1.0)
Requirement already satisfied: pyasn1>=0.1.3 in ./.local/lib/python3.6/site-packages (from rsa>=3.1.4->google-auth<2,>=1.6.3->tensorboard<2.1.0,>=2.0.0->tensorflow-gpu) (0.4.7)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./.local/lib/python3.6/site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.1.0,>=2.0.0->tensorflow-gpu) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in ./.local/lib/python3.6/site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.1.0,>=2.0.0->tensorflow-gpu) (1.25.3)
Requirement already satisfied: certifi>=2017.4.17 in ./.local/lib/python3.6/site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.1.0,>=2.0.0->tensorflow-gpu) (2019.6.16)
Requirement already satisfied: idna<2.9,>=2.5 in ./.local/lib/python3.6/site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.1.0,>=2.0.0->tensorflow-gpu) (2.8)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'tensorflow'
```

**Comment by mihaimaruseac** [comment]
Can you try

```
python -m pip uninstall tensorflow tensorflow-gpu && python -m pip install tensorflow-gpu && python -c "import tensorflow"
```

It's possible the install have left bad files on your disk, so it's better to start fresh.

**Comment by niccle27** [comment]
Well, i tried at least 3 times to remove everything and restart from a clean environnement. Though it never worked. This time your command worked with a little trick (add --user to install otherwise i don't have the right to launch the command properly) : 

```bash
python -m pip uninstall tensorflow tensorflow-gpu && python -m pip install --user tensorflow-gpu && python -c "import tensorflow"
```
Thank you a lot !!

**Comment by mihaimaruseac** [comment]
This is interesting. Probably because there is not enough space left on superroot disk. Or probably because some files need normal permissions not root.

In any case, the following trick should always work:

```
$ python -m virtualenv .
$ source bin/activate
$ python -m pip install ...
```

As everything would get installed relative to current directory.

Since this is working now, I'm going ahead and closing this issue.
