### ISSUE TITLE
Complex dtype support tflite converter

### ISSUE THREAD

**Issue by mattc-eostar** [tensorflow/tensorflow#34324]
Are complex dtypes planned to be supported in the experimental converter? using nightly 1108 build and it is throwing an error. This is super useful for MFCC calculations.

```python
def generate_mfcc_features(audio_array):
    sample_rate = 16000.0

    # A 1024-point STFT with frames of 64 ms and 75% overlap.
    stfts = tf.signal.stft(audio_array, frame_length=1024, frame_step=256,fft_length=1024)
    spectrograms = tf.abs(stfts)
#     spectrograms = tf.cast(stfts + 1, tf.float32)

    # Warp the linear scale spectrograms into the mel-scale.
    num_spectrogram_bins = stfts.shape[-1]
    lower_edge_hertz, upper_edge_hertz, num_mel_bins = 80.0, 7600.0, 80
    linear_to_mel_weight_matrix = tf.cast(tf.signal.linear_to_mel_weight_matrix(num_mel_bins, num_spectrogram_bins, sample_rate, lower_edge_hertz, upper_edge_hertz), tf.float32)
    mel_spectrograms = tf.tensordot(spectrograms, linear_to_mel_weight_matrix, 1)
    mel_spectrograms.set_shape(spectrograms.shape[:-1].concatenate(linear_to_mel_weight_matrix.shape[-1:]))

    # Compute a stabilized log to get log-magnitude mel-scale spectrograms.
    log_mel_spectrograms = tf.math.log(mel_spectrograms + 1e-6)

    # Compute MFCCs from log_mel_spectrograms and take the first 13.
    return tf.signal.mfccs_from_log_mel_spectrograms(log_mel_spectrograms)[..., :13]

cnn = tf.keras.Sequential([
    tf.keras.layers.Lambda(generate_mfcc_features, input_shape=(40000,)),
    tf.keras.layers.Conv1D(filters=32, kernel_size=10, strides=2, padding='same', activation='relu')
])
```

Error:
```
---------------------------------------------------------------------------
ConverterError                            Traceback (most recent call last)
<ipython-input-295-26886e1134e8> in <module>()
      8 converter.optimizations = [tf.lite.Optimize.OPTIMIZE_FOR_LATENCY]
      9 converter.target_spec.supported_ops = set([tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS])
---> 10 tflite_model_enc = converter.convert()
     11 
     12 print('Converting decoder')

~/anaconda3/envs/main/lib/python3.6/site-packages/tensorflow_core/lite/python/lite.py in convert(self)
    462         input_tensors=input_tensors,
    463         output_tensors=output_tensors,
--> 464         **converter_kwargs)
    465 
    466     if self._is_calibration_quantize():

~/anaconda3/envs/main/lib/python3.6/site-packages/tensorflow_core/lite/python/convert.py in toco_convert_impl(input_data, input_tensors, output_tensors, enable_mlir_converter, *args, **kwargs)
    455       input_data.SerializeToString(),
    456       debug_info_str=debug_info_str,
--> 457       enable_mlir_converter=enable_mlir_converter)
    458   return data
    459 

~/anaconda3/envs/main/lib/python3.6/site-packages/tensorflow_core/lite/python/convert.py in toco_convert_protos(model_flags_str, toco_flags_str, input_data_str, debug_info_str, enable_mlir_converter)
    201       stdout = _try_convert_to_unicode(stdout)
    202       stderr = _try_convert_to_unicode(stderr)
--> 203       raise ConverterError("See console for info.\n%s\n%s\n" % (stdout, stderr))
    204   finally:
    205     # Must manually cleanup files.

ConverterError: See console for info.
2019-11-15 15:12:34.503239: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2019-11-15 15:12:34.503275: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2019-11-15 15:12:35.451940: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory
2019-11-15 15:12:35.452051: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory
2019-11-15 15:12:35.452072: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2019-11-15 15:12:36.763021: W tensorflow/compiler/mlir/lite/python/graphdef_to_tfl_flatbuffer.cc:89] Ignored output_format.
2019-11-15 15:12:36.763078: W tensorflow/compiler/mlir/lite/python/graphdef_to_tfl_flatbuffer.cc:95] Ignored drop_control_dependency.
2019-11-15 15:12:36.923578: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-11-15 15:12:36.930986: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2294685000 Hz
2019-11-15 15:12:36.931794: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55eb1a6ac800 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2019-11-15 15:12:36.931821: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2019-11-15 15:12:36.933506: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2019-11-15 15:12:36.933531: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: UNKNOWN ERROR (303)
2019-11-15 15:12:36.933572: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (VXML-Ubuntu): /proc/driver/nvidia/version does not exist
loc(callsite("sequential_5/lambda_4/mfccs_from_log_mel_spectrograms/dct/strided_slice"("/home/mattc/anaconda3/envs/main/lib/python3.6/site-packages/tensorflow_core/python/ops/signal/dct_ops.py":130:0) at callsite("/home/mattc/anaconda3/envs/main/lib/python3.6/site-packages/tensorflow_core/python/ops/signal/mfcc_ops.py":107:0 at callsite("<ipython-input-228-d9ade39d80ce>":20:0 at callsite("/home/mattc/anaconda3/envs/main/lib/python3.6/site-packages/tensorflow_core/python/keras/layers/core.py":827:0 at callsite("/home/mattc/anaconda3/envs/main/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py":778:0 at callsite("/home/mattc/anaconda3/envs/main/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/network.py":891:0 at callsite("/home/mattc/anaconda3/envs/main/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/network.py":717:0 at callsite("/home/mattc/anaconda3/envs/main/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/sequential.py":267:0 at callsite("/home/mattc/anaconda3/envs/main/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py":778:0 at "<ipython-input-290-205be255c740>":3:0)))))))))): error: 'tfl.strided_slice' op operand #0 must be tensor of 32-bit float or 32-bit integer or 64-bit integer or 8-bit integer or QI8 type or QUI8 type or 1-bit integer values, but got 'tensor<1x153x81xcomplex<f32>>'
Traceback (most recent call last):
  File "/home/mattc/anaconda3/envs/main/bin/toco_from_protos", line 10, in <module>
    sys.exit(main())
  File "/home/mattc/anaconda3/envs/main/lib/python3.6/site-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 93, in main
    app.run(main=execute, argv=[sys.argv[0]] + unparsed)
  File "/home/mattc/anaconda3/envs/main/lib/python3.6/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/mattc/anaconda3/envs/main/lib/python3.6/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/mattc/anaconda3/envs/main/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/home/mattc/anaconda3/envs/main/lib/python3.6/site-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 56, in execute
    enable_mlir_converter)
Exception: /home/mattc/anaconda3/envs/main/lib/python3.6/site-packages/tensorflow_core/python/ops/signal/dct_ops.py:130:15: error: 'tfl.strided_slice' op operand #0 must be tensor of 32-bit float or 32-bit integer or 64-bit integer or 8-bit integer or QI8 type or QUI8 type or 1-bit integer values, but got 'tensor<1x153x81xcomplex<f32>>'
              input, fft_length=[2 * axis_dim])[..., :axis_dim] * scale)
              ^
/home/mattc/anaconda3/envs/main/lib/python3.6/site-packages/tensorflow_core/python/ops/signal/mfcc_ops.py:107:5: note: called from
    dct2 = dct_ops.dct(log_mel_spectrograms, type=2)
    ^
<ipython-input-228-d9ade39d80ce>: note: called from
/home/mattc/anaconda3/envs/main/lib/python3.6/site-packages/tensorflow_core/python/keras/layers/core.py:827:7: note: called from
      return self.function(inputs, **arguments)
      ^
/home/mattc/anaconda3/envs/main/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py:778:19: note: called from
                  outputs = call_fn(cast_inputs, *args, **kwargs)
                  ^
/home/mattc/anaconda3/envs/main/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/network.py:891:11: note: called from
          output_tensors = layer(computed_tensors, **kwargs)
          ^
/home/mattc/anaconda3/envs/main/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/network.py:717:9: note: called from
        convert_kwargs_to_constants=base_layer_utils.call_context().saving)
        ^
/home/mattc/anaconda3/envs/main/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/sequential.py:267:7: note: called from
      return super(Sequential, self).call(inputs, training=training, mask=mask)
      ^
/home/mattc/anaconda3/envs/main/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py:778:19: note: called from
                  outputs = call_fn(cast_inputs, *args, **kwargs)
                  ^
<ipython-input-290-205be255c740>: note: called from
```

Is there a plan to support signal operations like this in a TFLite model?

**Comment by haozha111** [comment]
hi, does this problem still exist?

**Comment by sushreebarsa** [comment]
@mattc-eostar 
It looks like you are using an older Version of Tensorflow 2.0. Many bugs have been fixed in the latest version. Could you please try to execute using Latest Version of TF 2.6.0 and let us know if the issue still persists? Thanks!

**Comment by mattc-eostar** [comment]
The project related to this code has since been abandoned. I do not have the means currently to check if this is still an issue.
