### ISSUE TITLE
tensorflow.python.framework.errors_impl.InternalError: cudaGetDevice() failed. Status: cudaGetErrorString symbol not found

### ISSUE THREAD

**Issue by yangis1019** [tensorflow/tensorflow#34354]
hello = tf.constant('Hello, TensorFlow!')
----
Traceback (most recent call last):
  File "<pyshell#5>", line 1, in <module>
    hello = tf.constant('Hello, TensorFlow!')
  File "C:\Users\yang kil ho\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\framework\constant_op.py", line 227, in constant
    allow_broadcast=True)
  File "C:\Users\yang kil ho\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\framework\constant_op.py", line 235, in _constant_impl
    t = convert_to_eager_tensor(value, ctx, dtype)
  File "C:\Users\yang kil ho\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\framework\constant_op.py", line 95, in convert_to_eager_tensor
    ctx.ensure_initialized()
  File "C:\Users\yang kil ho\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\eager\context.py", line 492, in ensure_initialized
    self._context_handle = pywrap_tensorflow.TFE_NewContext(opts)
tensorflow.python.framework.errors_impl.InternalError: cudaGetDevice() failed. Status: cudaGetErrorString symbol not found.

I updated my CUDA version to 10.1, but it doesn't work.

**Comment by ymodak** [comment]
TensorFlow supports CUDA 10.0 (TensorFlow >= 1.13.0)
Please switch to cuda 10.0 and update cuda paths.
See [software requirements](https://www.tensorflow.org/install/gpu#software_requirements)
Also see which TF binary suits your case https://www.tensorflow.org/install/pip?lang=python3#older-versions-of-tensorflow

**Comment by yangis1019** [comment]
so... how to I downgrade CUDA to 10.0?

**Comment by oanush** [comment]
@yangis1019 ,
Please refer this [link](https://www.tensorflow.org/install/gpu).Thanks!

**Comment by yangis1019** [comment]
OK
