### ISSUE TITLE
build failed with cuda 10.2

### ISSUE THREAD

**Issue by alanpurple** [tensorflow/tensorflow#34429]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 18.04 x64
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.0.0
- Python version: 3.7.5 x64
- Installed using virtualenv? pip? conda?: N/A
- Bazel version (if compiling from source): 1.1.0 x64
- GCC/Compiler version (if compiling from source):  7.4.0
- CUDA/cuDNN version: 10.2 / 7.6.5
- GPU model and memory: GTX1080Ti GDDR5X 11GB

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**
bazel build

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

```
ERROR: /home/vai/.cache/bazel/_bazel_vai/964c7018fd2d0d2d2cf98e15f592d3c8/external/nccl_archive/BUILD.bazel:53:1: fatbinary external/nccl_archive/device_dlink_hdrs.fatbin failed (Exit 1)
fatbinary fatal   : Unknown option '-bin2c-path'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /home/vai/repo/tensorflow/tensorflow/python/tools/BUILD:81:1 fatbinary external/nccl_archive/device_dlink_hdrs.fatbin failed (Exit 1)
```

**Comment by alanpurple** [comment]
after set nccl version manually to 2.5.6, above error doen't appear, instead, another error as below came

```
ERROR: /home/vai/repo/tensorflow/tensorflow/python/keras/api/BUILD:115:1: Executing genrule //tensorflow/python/keras/api:keras_python_api_gen_compat_v1 failed (Exit 1)
2019-11-20 13:15:41.004621: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.2
Traceback (most recent call last):
  File "/home/vai/.cache/bazel/_bazel_vai/964c7018fd2d0d2d2cf98e15f592d3c8/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_1_keras_python_api_gen_compat_v1.runfiles/org_tensorflow/tensorflow/python/tools/api/generator/create_python_api.py", line 771, in <module>
    main()
  File "/home/vai/.cache/bazel/_bazel_vai/964c7018fd2d0d2d2cf98e15f592d3c8/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_1_keras_python_api_gen_compat_v1.runfiles/org_tensorflow/tensorflow/python/tools/api/generator/create_python_api.py", line 767, in main
    lazy_loading, args.use_relative_imports)
  File "/home/vai/.cache/bazel/_bazel_vai/964c7018fd2d0d2d2cf98e15f592d3c8/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_1_keras_python_api_gen_compat_v1.runfiles/org_tensorflow/tensorflow/python/tools/api/generator/create_python_api.py", line 625, in create_api_files
    api_version, compat_api_versions, lazy_loading, use_relative_imports)
  File "/home/vai/.cache/bazel/_bazel_vai/964c7018fd2d0d2d2cf98e15f592d3c8/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_1_keras_python_api_gen_compat_v1.runfiles/org_tensorflow/tensorflow/python/tools/api/generator/create_python_api.py", line 502, in get_api_init_text
    _, attr = tf_decorator.unwrap(attr)
  File "/home/vai/.cache/bazel/_bazel_vai/964c7018fd2d0d2d2cf98e15f592d3c8/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_1_keras_python_api_gen_compat_v1.runfiles/org_tensorflow/tensorflow/python/util/tf_decorator.py", line 219, in unwrap
    elif _has_tf_decorator_attr(cur):
  File "/home/vai/.cache/bazel/_bazel_vai/964c7018fd2d0d2d2cf98e15f592d3c8/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_1_keras_python_api_gen_compat_v1.runfiles/org_tensorflow/tensorflow/python/util/tf_decorator.py", line 124, in _has_tf_decorator_attr
    hasattr(obj, '_tf_decorator') and
  File "/home/vai/.cache/bazel/_bazel_vai/964c7018fd2d0d2d2cf98e15f592d3c8/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_1_keras_python_api_gen_compat_v1.runfiles/org_tensorflow/tensorflow/python/util/lazy_loader.py", line 62, in __getattr__
    module = self._load()
  File "/home/vai/.cache/bazel/_bazel_vai/964c7018fd2d0d2d2cf98e15f592d3c8/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_1_keras_python_api_gen_compat_v1.runfiles/org_tensorflow/tensorflow/python/util/lazy_loader.py", line 45, in _load
    module = importlib.import_module(self.__name__)
  File "/home/vai/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/vai/.cache/bazel/_bazel_vai/964c7018fd2d0d2d2cf98e15f592d3c8/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_1_keras_python_api_gen_compat_v1.runfiles/org_tensorflow/tensorflow/compiler/tf2tensorrt/wrap_py_utils.py", line 28, in <module>
    _wrap_py_utils = swig_import_helper()
  File "/home/vai/.cache/bazel/_bazel_vai/964c7018fd2d0d2d2cf98e15f592d3c8/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_1_keras_python_api_gen_compat_v1.runfiles/org_tensorflow/tensorflow/compiler/tf2tensorrt/wrap_py_utils.py", line 24, in swig_import_helper
    _mod = imp.load_module('_wrap_py_utils', fp, pathname, description)
  File "/home/vai/anaconda3/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/vai/anaconda3/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 670, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 583, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1043, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: /home/vai/.cache/bazel/_bazel_vai/964c7018fd2d0d2d2cf98e15f592d3c8/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_1_keras_python_api_gen_compat_v1.runfiles/org_tensorflow/tensorflow/compiler/tf2tensorrt/_wrap_py_utils.so: undefined symbol: _ZN10tensorflow3Env7DefaultEv
----------------
Note: The failure of target //tensorflow/python/keras/api:create_tensorflow.python_api_1_keras_python_api_gen_compat_v1 (with exit code 1) may have been caused by the fact that it is a Python 2 program that was built in the host configuration, which uses Python 3. You can change the host configuration (for the entire build) to instead use Python 2 by setting --host_force_python=PY2.

If this error started occurring in Bazel 0.27 and later, it may be because the Python toolchain now enforces that targets analyzed as PY2 and PY3 run under a Python 2 and Python 3 interpreter, respectively. See https://github.com/bazelbuild/bazel/issues/7899 for more information.
----------------
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /home/vai/repo/tensorflow/tensorflow/python/tools/BUILD:141:1 Executing genrule //tensorflow/python/keras/api:keras_python_api_gen_compat_v1 failed (Exit 1)
```

**Comment by ravikyram** [comment]
Can you downgrade to cuda 10.0 and see how it progress.Thanks!

**Comment by perfinion** [comment]
@ravikyram Cuda 10.0 and 10.1 are supported and have been for a fair while now, this looks new.

@yifeif have you tried cuda 10.2 yet?

**Comment by RicardasSim** [comment]
also failed build of version 1.15.0 with cuda-10.2

fatbinary fatal   : Unknown option '-bin2c-path'

here is a comparison of "fatbinary --help" output from cuda-10.0 and cuda-10.2

https://pastebin.com/E1SXpuqh

seems that there is no '-bin2c-path' option anymore

**Comment by PhilippJKratzer** [comment]
I was able to successfully compile on v2.0.0 with cuda-10.2.

I had the same error. My workaround was to remove the line `"--bin2c-path=%s" % bin2c.dirname,` from the file `third_party/nccl/build_defs.bzl.tpl`

seems this option is not required anymore.

**Comment by themikem** [comment]
> I was able to successfully compile on v2.0.0 with cuda-10.2.
> 
> I had the same error. My workaround was to remove the line `"--bin2c-path=%s" % bin2c.dirname,` from the file `third_party/nccl/build_defs.bzl.tpl`
> 
> seems the '-bin2c-path' option is not required anymore.

I've removed this, but now am getting a failure with it unable to find cupti.h.  I'm on the r2.0 branch though, as the last time I tried master I had other non-CUDA issues that failed the build.

Which branch did you use for this (r2.0 or the v2.0.0 tag?), and did you see this error at all?

Thanks!

**Comment by alanpurple** [comment]
@themikem 
use master, not r2.0

**Comment by themikem** [comment]
Here are the changes that were necessary to get r2.0 branch to build w/ my setup:

https://github.com/themikem/tensorflow/commit/cc5645f28312388d884a88b85b65e24f68488fb7

**Comment by alanpurple** [comment]
Here are today's list

python 3.8
cuda 10.2
gast 0.3.2
bazel 1.1


will 2.1.0-rc.1 be okay all of those?

**Comment by ahtik** [comment]
@alanpurple 2.1.0-rc1 is not yet released. With 2.1-rc0? No.

For Python 3.8 support, there also needs to be gprcio 3.8 wheels available, https://github.com/grpc/grpc/issues/20831 (especially affecting Windows where grpcio builds are very complicated).

cuda 10.2 - there's a recent work done on cuda 10.1: https://github.com/tensorflow/tensorflow/tree/4f11eb8e5389ffffa5d0e0ee9e1071b752564df4/third_party/toolchains/preconfig/ubuntu16.04/cuda10.1-cudnn7 that might land soon. I've also noticed a source saying tensorflow might eventually skip cuda 10.1 and move straight to 10.2/whatever is next, but I can no longer find the reference.

bazel - AFAIK build works with bazel 1.1.0, but not 1.2.1. I'd just use whatever is required, there is no reason to stress over getting it upgraded with apt.
```bash
apt-get install -y --no-install-recommends \
   bash-completion \
   g++ \
   zlib1g-dev \
 && curl -LO "https://github.com/bazelbuild/bazel/releases/download/1.1.0/bazel_1.1.0-linux-x86_64.deb" \
 && dpkg -i bazel_*.deb
```
There's also a single static fat binary version of bazel without the need for apt.

From a pragmatic perspective, the python 3.8 issue is the only "real" problem that affects the daily use and productivity. But yes, having cuda 10.2 would be very nice as it brings quite a few performance improvements over 10.0.

**Comment by alanpurple** [comment]
@ahtik 
thank you very much

**Comment by fbroda** [comment]
PhilippJKratzer's comment pointed me into the right direction. Just removing the line containing `--bin2c-path` didn't help. Without any deeper understanding of the problem I modified the original line 
 ` "--link --bin2c-path $$(dirname $(location %s)) " % bin2c +`
in tensorflow release 1.13.2 to  
  ``"--link `cat %s >/dev/null` " % bin2c +``
to get rid of the extra command line argument. That obviously did the trick to compile tensorflow for cuda 10.2 and libcudnn7_7.6.5.32 on ubuntu 18.04.3. (I had also to fix some symbolic links to cuda libraries; the resulting tensorflow package just completed the MRPC task on Google BERT as a first test)

**Comment by alanpurple** [comment]
@ahtik 

now grpc support python 3.8 in windows 10!!  good news

https://pypi.org/project/grpcio/1.26.0rc1/#files

**Comment by ahtik** [comment]
@alanpurple 
> @ahtik
> now grpc support python 3.8 in windows 10!! good news
> https://pypi.org/project/grpcio/1.26.0rc1/#files

Yes! Windows 10, grpcio==1.26.0rc1, Python 3.8 and Cuda 10.1 compiles and runs perfectly fine now without any tweaks with tensorflow v2.1.0-rc0.

It is worth mentioning that although tensorflow works now fine with Python 3.8, there are closely related projects like Hugging Face Transformers with it's own upstream and downstream dependencies waiting for the wheels.

The scope of this issue was cuda 10.2, but for now I'd still stay on cuda 10.0 or 10.1. Looking at the source and recent changes, simply removing bin2c could have it's own less visible consequences not worth the risk.

**Comment by alanpurple** [comment]
still failed with tensorrt,  no problem without tensorrt

**Comment by saikiran2603** [comment]
> still failed with tensorrt, no problem without tensorrt

I was able to get rid of tensorrt issue by installing 6.0.1 

https://docs.nvidia.com/deeplearning/sdk/tensorrt-install-guide/index.html

i am downgrading to cuda 10.1 for v2.1 , but surprisingly i was using v2.0-gpu with cuda 10.2 till now

**Comment by jiapei100** [comment]
@alanpurple 

Exactly the same **ERROR** from me:


```console
ERROR: ~/....../tensorflow/python/keras/api/BUILD:130:1: Executing genrule //tensorflow/python/keras/api:keras_python_api_gen_compat_v2 failed (Exit 1)
Traceback (most recent call last):
  File "~/.cache/bazel/_bazel_longervision/449dd09be7229482c168e6868d06849c/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen_compat_v2.runfiles/org_tensorflow/tensorflow/python/tools/api/generator/create_python_api.py", line 776, in <module>
    main()
  File "~/.cache/bazel/_bazel_longervision/449dd09be7229482c168e6868d06849c/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen_compat_v2.runfiles/org_tensorflow/tensorflow/python/tools/api/generator/create_python_api.py", line 772, in main
    lazy_loading, args.use_relative_imports)
  File "~/.cache/bazel/_bazel_longervision/449dd09be7229482c168e6868d06849c/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen_compat_v2.runfiles/org_tensorflow/tensorflow/python/tools/api/generator/create_python_api.py", line 629, in create_api_files
    compat_api_versions, lazy_loading, use_relative_imports)
  File "~/.cache/bazel/_bazel_longervision/449dd09be7229482c168e6868d06849c/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen_compat_v2.runfiles/org_tensorflow/tensorflow/python/tools/api/generator/create_python_api.py", line 503, in get_api_init_text
    _, attr = tf_decorator.unwrap(attr)
  File "~/.cache/bazel/_bazel_longervision/449dd09be7229482c168e6868d06849c/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen_compat_v2.runfiles/org_tensorflow/tensorflow/python/util/tf_decorator.py", line 219, in unwrap
    elif _has_tf_decorator_attr(cur):
  File "~/.cache/bazel/_bazel_longervision/449dd09be7229482c168e6868d06849c/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen_compat_v2.runfiles/org_tensorflow/tensorflow/python/util/tf_decorator.py", line 124, in _has_tf_decorator_attr
    hasattr(obj, '_tf_decorator') and
  File "~/.cache/bazel/_bazel_longervision/449dd09be7229482c168e6868d06849c/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen_compat_v2.runfiles/org_tensorflow/tensorflow/python/util/lazy_loader.py", line 62, in __getattr__
    module = self._load()
  File "~/.cache/bazel/_bazel_longervision/449dd09be7229482c168e6868d06849c/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen_compat_v2.runfiles/org_tensorflow/tensorflow/python/util/lazy_loader.py", line 45, in _load
    module = importlib.import_module(self.__name__)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "~/.cache/bazel/_bazel_longervision/449dd09be7229482c168e6868d06849c/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen_compat_v2.runfiles/org_tensorflow/tensorflow/compiler/tf2tensorrt/wrap_py_utils.py", line 28, in <module>
    _wrap_py_utils = swig_import_helper()
  File "~/.cache/bazel/_bazel_longervision/449dd09be7229482c168e6868d06849c/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen_compat_v2.runfiles/org_tensorflow/tensorflow/compiler/tf2tensorrt/wrap_py_utils.py", line 24, in swig_import_helper
    _mod = imp.load_module('_wrap_py_utils', fp, pathname, description)
  File "/usr/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: ~/.cache/bazel/_bazel_longervision/449dd09be7229482c168e6868d06849c/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen_compat_v2.runfiles/org_tensorflow/tensorflow/compiler/tf2tensorrt/_wrap_py_utils.so: undefined symbol: _ZN15stream_executor14StreamExecutor18EnablePeerAccessToEPS0_
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: ~/....../tensorflow/python/tools/BUILD:81:1 Executing genrule //tensorflow/python/keras/api:keras_python_api_gen_compat_v2 failed (Exit 1)
INFO: Elapsed time: 128.286s, Critical Path: 26.37s
INFO: 306 processes: 306 local.
FAILED: Build did NOT complete successfully
➜  tensorflow git:(master) ✗ 
```

**Comment by phemmer** [comment]
Just piping in with my own experience since there seem to be several people reporting errors even with the removal of the line `"--bin2c-path=%s" % bin2c.dirname,`.
For me, removing this line addressed the issue. I was able to complete the tensorflow build with no other issues. So I suspect the other issues being reported are likely unrelated.

**Comment by vistart** [comment]
This problem also occurs in Windows 10.

- Windows 10 Pro x64 18362
- Visual Studio 2017
- cuda 10.2, cudnn 7.6
- Python 2.7 or 3.5~3.8

**Comment by jiapei100** [comment]
@vistart 
What is the solution tho?

**Comment by vistart** [comment]
> @vistart
> What is the solution tho?

Sorry, I don't have any good way for now, I can only wait for the official update.

**Comment by nouiz** [comment]
It works for me with the master branch of TF.

**Comment by alanpurple** [comment]
this issue has been resolved at some point, closing

**Comment by odinsbane** [comment]
I used this "fix" with tensorflow 1.14 and cuda 10.2. It compiled and installed ok, but I cannot run previously working models. I get an out of memory error, or a failed to load CUDNN error. Seems somewhat random which one will occur.

**Comment by perfinion** [comment]
For the record, it was fixed in this commit:

commit 67edc16326d6328e7ef096e1b06f81dae1bfb816
Author: Sami <skama@nvidia.com>
Date:   Fri Dec 6 08:49:20 2019

    Make nccl bindings compilable with cuda 10.2

**Comment by jamesturner246** [comment]
Any chance the fix can be backported to r2.1 branch in the meantime? Thanks.

**Comment by JC1DA** [comment]
> I used this "fix" with tensorflow 1.14 and cuda 10.2. It compiled and installed ok, but I cannot run previously working models. I get an out of memory error, or a failed to load CUDNN error. Seems somewhat random which one will occur.
> 
> the crashing only happened once, now it seems as solid as the 10.1 version.

Somehow, with new cuda, you need to set TF_FORCE_GPU_ALLOW_GROWTH=true to solve the "failed to load CuDNN issue".

**Comment by rajb245** [comment]
> For the record, it was fixed in this commit:
> 
> commit [67edc16](https://github.com/tensorflow/tensorflow/commit/67edc16326d6328e7ef096e1b06f81dae1bfb816)
> Author: Sami [skama@nvidia.com](mailto:skama@nvidia.com)
> Date: Fri Dec 6 08:49:20 2019
> 
> ```
> Make nccl bindings compilable with cuda 10.2
> ```

The fix could be cherry-picked / backported into the 1.15 line. Will TF 1.15 continue to get updates like this to keep it supported as time goes on as the last version of TF1?

**Comment by mihaimaruseac** [comment]
Not really. Release branches only get security patches and build fixes on the same toolchain. This seems to change cuda toolchain, which I don't think is low risk enough to warrant cherry-picking
