### ISSUE TITLE
Error while building API docs

### ISSUE THREAD

**Issue by nikochiko** [tensorflow/tensorflow#34440]
## URL(s) with the issue:
https://www.tensorflow.org/api_docs/python/tf/compat/v1/flags/tf_decorator/tf_stack/FileAndLine

## Description of issue (what needs changing):
Get a `ValueError` while setting up to view TensorFlow-style HTML locally. (According to https://www.tensorflow.org/community/contribute/docs)

### Clear description
```
Traceback (most recent call last):
  File "generate2.py", line 284, in <module>
    app.run(main)
  File "C:\Users\ASPIRE\.conda\envs\tensorflow2\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "C:\Users\ASPIRE\.conda\envs\tensorflow2\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "generate2.py", line 280, in main
    search_hints=FLAGS.search_hints)
  File "generate2.py", line 273, in build_docs
    doc_generator.build(output_dir)
  File "C:\Users\ASPIRE\.conda\envs\tensorflow2\lib\site-packages\tensorflow_docs\api_generator\generate_lib.py", line 839, in build
    site_path=self._site_path)
  File "C:\Users\ASPIRE\.conda\envs\tensorflow2\lib\site-packages\tensorflow_docs\api_generator\generate_lib.py", line 507, in write_docs
    'Failed to generate docs for symbol: `{}`'.format(full_name))
ValueError: Failed to generate docs for symbol: `tf.compat.v1.flags.tf_decorator.tf_stack.FileAndLine`
```

**Comment by oanush** [comment]
@nikochiko ,
Can you provide code snippet to reproduce the error reported here?Thanks!

**Comment by nikochiko** [comment]
@oanush , this code on the TensorFlow documentation: https://www.tensorflow.org/community/contribute/docs#python_reference

**Comment by gowthamkpr** [comment]
@nikochiko Can you please attach a colab gist. Thanks!

**Comment by nikochiko** [comment]
I think this is a local error. This seems to work fine: https://colab.research.google.com/gist/nikochiko/2a6d87131461d9bc959f6c4e18138494/test-build-api-docs.ipynb

**Comment by gowthamkpr** [comment]
@nikochiko i am closing this issue as this issue has been resolved. Thanks!
