### ISSUE TITLE
tf.ragged.stack breaks with rank-1 regular tensors

### ISSUE THREAD

**Issue by RunOrVeith** [tensorflow/tensorflow#34455]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Linux Ubuntu 18.04
- TensorFlow installed from (source or binary): binary pip 
- TensorFlow version (use command below): v2.0.0-rc2-26-g64c3d38 2.0.0
- Python version: 3.6.5
- CUDA/cuDNN version: CUDA 10.1 cuDNN 7.6.2.24
- GPU model and memory: Quadro P2000

**Describe the current behavior**

When creating a ragged tensor by using `tf.ragged.stack` on several regular tensors on the 0-th axis, the function crashes when the rank of the input tensors is 1.

**Describe the expected behavior**

According to the [documentation](https://www.tensorflow.org/api_docs/python/tf/ragged/stack): `Given a list of tensors or ragged tensors with the same rank R (R >= axis) [...]`. Here, R=1 and  axis=0, so the preconditions should be fulfilled.

**Code to reproduce the issue**
```python
import tensorflow as tf
tf.ragged.stack([[1, 2, 3], [1, 2]], axis=0)
```

**Other info / logs**
Calling the 2 lines above results in:
```
Traceback (most recent call last):
  File "/home/veith/Projects/venvs/anontf2/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-14-488f6e6430bd>", line 1, in <module>
    tf.ragged.stack([[1, 2, 3], [1, 2]], axis=0)
  File "/home/veith/Projects/venvs/anontf2/lib/python3.6/site-packages/tensorflow_core/python/ops/ragged/ragged_concat_ops.py", line 113, in stack
    return _ragged_stack_concat_helper(values, axis, stack_values=True)
  File "/home/veith/Projects/venvs/anontf2/lib/python3.6/site-packages/tensorflow_core/python/ops/ragged/ragged_concat_ops.py", line 167, in _ragged_stack_concat_helper
    return array_ops.stack(rt_inputs, axis)
  File "/home/veith/Projects/venvs/anontf2/lib/python3.6/site-packages/tensorflow_core/python/util/dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "/home/veith/Projects/venvs/anontf2/lib/python3.6/site-packages/tensorflow_core/python/ops/array_ops.py", line 1154, in stack
    return ops.convert_to_tensor(values, name=name)
  File "/home/veith/Projects/venvs/anontf2/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 1184, in convert_to_tensor
    return convert_to_tensor_v2(value, dtype, preferred_dtype, name)
  File "/home/veith/Projects/venvs/anontf2/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 1242, in convert_to_tensor_v2
    as_ref=False)
  File "/home/veith/Projects/venvs/anontf2/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 1296, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/veith/Projects/venvs/anontf2/lib/python3.6/site-packages/tensorflow_core/python/ops/array_ops.py", line 1278, in _autopacking_conversion_function
    return _autopacking_helper(v, dtype, name or "packed")
  File "/home/veith/Projects/venvs/anontf2/lib/python3.6/site-packages/tensorflow_core/python/ops/array_ops.py", line 1184, in _autopacking_helper
    return gen_array_ops.pack(list_or_tuple, name=name)
  File "/home/veith/Projects/venvs/anontf2/lib/python3.6/site-packages/tensorflow_core/python/ops/gen_array_ops.py", line 6293, in pack
    _six.raise_from(_core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: Shapes of all inputs must match: values[0].shape = [3] != values[1].shape = [2] [Op:Pack] name: stack
```

**Workaround**

Expanding the rank-1 tensors to rank-2 tensors followed by squeezing the redundant dimension seems to work:
```python
import tensorflow as tf
x = tf.ragged.stack([[[1, 2, 3]], [[1, 2]]], axis=0)
print(x.bounding_shape())  # <tf.Tensor: id=929, shape=(3,), dtype=int64, numpy=array([2, 1, 3])>
x = tf.squeeze(x, axis=1) 
print(x.bounding_shape())  # <tf.Tensor: id=1109, shape=(2,), dtype=int64, numpy=array([2, 3])>
```

**Estimated cause**

I did not check the tensorflow source code for this, but the [general ragged documentation](https://www.tensorflow.org/guide/ragged_tensor#ragged_tensors_definitions) states:
![image](https://user-images.githubusercontent.com/12949211/69247798-544f0780-0bab-11ea-8ff0-3f6626a8e2f8.png)
I assume the issue is that there is no uniform dimension in the regular tensors before stacking them. Intuitively I would have assumed that I can use `tf.ragged.stack` to create this uniform dimension to form a ragged tensor from several non-ragged different-dimension tensors as above, similar to the regulat `tf.stack`, which creates a new dimension.
I am not sure whether this is considered a bug or an error in the documentation of `tf.ragged.stack`, but it feels like a bug from a user perspective.

**Comment by gowthamkpr** [comment]
This is not a bug @RunOrVeith As the uniform dimension is missing before the ragged dimensions, its throwing an error. Thanks!

**Comment by RunOrVeith** [comment]
Yes, I assumed that it is not a bug, but rather more unexpected behavior/missing documentation.
Maybe this could also be labeled as a feature request for `tf.ragged.stack`.
But it's not super urgent as the workaround with adding a dimension and then squeezing it works well enough.

**Comment by ymodak** [comment]
The code snippet works with TF 2.4.1
See [gist](https://colab.research.google.com/gist/ymodak/be4a1037e6b00dff8f159640d6613c2c/github_issue34455.ipynb) for reference. Thanks!
