### ISSUE TITLE
ValueError with tf.data.Dataset and model.fit and tf.distribute

### ISSUE THREAD

**Issue by Bidski** [tensorflow/tensorflow#34469]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Docker image
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: not mobile
- TensorFlow installed from (source or binary): Docker image: tensorflow/tensorflow:nightly-gpu-py3
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.0/7.6
- GPU model and memory: NVIDIA V100

**Describe the current behaviour**
I receive the following stack trace
```
Traceback (most recent call last):
  File "main.py", line 571, in <module>
    verbose=2,
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/training.py", line 792, in fit
    use_multiprocessing=use_multiprocessing)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/training_v2.py", line 264, in fit
    training_dataset)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/distribute/distribute_lib.py", line 677, in experimental_distribute_dataset
    return self._extended._experimental_distribute_dataset(dataset)  # pylint: disable=protected-access
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/distribute/mirrored_strategy.py", line 574, in _experimental_distribute_dataset
    split_batch_by=self._num_replicas_in_sync)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/distribute/input_lib.py", line 89, in get_distributed_dataset
    input_context=input_context)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/distribute/input_lib.py", line 509, in __init__
    dataset = distribute._RebatchDataset(dataset, split_batch_by)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/data/experimental/ops/distribute.py", line 110, in __init__
    rebatch, dataset_ops.get_structure(input_dataset))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/data/util/nest.py", line 245, in map_structure
    structure[0], [func(*x) for x in entries])
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/data/util/nest.py", line 245, in <listcomp>
    structure[0], [func(*x) for x in entries])
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/data/experimental/ops/distribute.py", line 105, in rebatch
    batch_size = recalculate_batch_size(type_spec._to_legacy_output_shapes())
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/data/experimental/ops/distribute.py", line 90, in recalculate_batch_size
    if len(output_shapes) < 1:
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/tensor_shape.py", line 823, in __len__
    raise ValueError("Cannot take the length of shape with unknown rank.")
ValueError: Cannot take the length of shape with unknown rank.
```

**Describe the expected behavior**
I expect training to proceed without issue.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

This is an excerpt of my code, hopefully it is sufficient to demonstrate what I am doing.
```
def parse_entry(entry):
    # Create a dictionary describing the features
    feature_description = {
        "num": tf.io.FixedLenFeature(shape=[], dtype=tf.string),
        "width": tf.io.FixedLenFeature(shape=[], dtype=tf.int64),
        "height": tf.io.FixedLenFeature(shape=[], dtype=tf.int64),
        "image_l": tf.io.FixedLenFeature(shape=[], dtype=tf.string),
        "image_r": tf.io.FixedLenFeature(shape=[], dtype=tf.string),
        "disparity_l": tf.io.FixedLenSequenceFeature(shape=[], dtype=tf.float32, allow_missing=True),
        "disparity_r": tf.io.FixedLenSequenceFeature(shape=[], dtype=tf.float32, allow_missing=True),
    }
    example = tf.io.parse_single_example(entry, feature_description)

    # Need to decode the image data
    example["image_l"] = tf.io.decode_image(example["image_l"], channels=0, dtype=tf.uint8)
    example["image_r"] = tf.io.decode_image(example["image_r"], channels=0, dtype=tf.uint8)

    # Disparities were flattened, need to recover their actual shape
    # Assuming that channels will be the last axis
    example["disparity_l"] = tf.reshape(example["disparity_l"], (example["width"], example["height"], 1))
    example["disparity_r"] = tf.reshape(example["disparity_r"], (example["width"], example["height"], 1))

    return (
        (example["num"], example["width"], example["height"], example["image_l"], example["image_r"],),
        (example["num"], example["width"], example["height"], example["disparity_l"], example["disparity_r"],),
    )

def create_dataset(path, args):
    # Create a stats aggregator for the dataset
    aggregator = tf.data.experimental.StatsAggregator()

    # Load in the dataset
    dataset = tf.data.TFRecordDataset(path)

    # Shuffle the elements
    if args.shuffle_size > 1:
        dataset = dataset.shuffle(args.shuffle_size, reshuffle_each_iteration=False)

    # Convert dataset to training format
    dataset = dataset.map(parse_entry)

    # Set up batch size
    dataset = dataset.batch(batch_size=args.batch_size, drop_remainder=False)

    # Set output shapes, types, and classes
    dataset.output_classes = (
        (tf.Tensor, tf.Tensor, tf.Tensor, tf.Tensor, tf.Tensor),
        (tf.Tensor, tf.Tensor, tf.Tensor, tf.Tensor, tf.Tensor),
    )
    dataset.output_types = (
        (tf.dtypes.string, tf.dtypes.int64, tf.dtypes.int64, tf.dtypes.uint8, tf.dtypes.uint8,),
        (tf.dtypes.string, tf.dtypes.int64, tf.dtypes.int64, tf.dtypes.float32, tf.dtypes.float32,),
    )
    dataset.output_shapes = (
        ([], [], [], tf.TensorShape([None, None, 3]), tf.TensorShape([None, None, 3]),),
        ([], [], [], tf.TensorShape([None, None, 1]), tf.TensorShape([None, None, 1]),),
    )

    # Extract the first element so we can retrieve image shapes
    for entry in tf.data.TFRecordDataset(path).take(1):
        element = parse_entry(entry)
        # shape = (element[0]["width"], element[0]["height"])
        shape = (element[0][2], element[0][1])

    return dataset, shape

train_dataset, input_resolution = create_dataset(args.train_dataset, args)
valid_dataset, _ = create_dataset(args.valid_dataset, args)

strategy = tf.distribute.MirroredStrategy()
with strategy.scope():
    # Create the model
    model = CustomKerasModel()

    # Compile the model, set optimiser, loss function, and metrics to use
    model.compile(optimizer=optimiser, loss=loss, metrics=metrics)

    # Train
    model.fit(
        x=train_dataset,
        validation_data=valid_dataset,
        validation_steps=None,
        validation_freq=1,
        callbacks=callbacks,
        epochs=args.num_epochs,
        verbose=2,
    )

    model.save(
        output_path,
        overwrite=True,
        include_optimizer=True,
        save_format="h5",
    )
```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

I think this problem is similar to #24520 but with `tf.distribute.MirroredStrategy` mixed in. I am using a TFRecordDataset and I am setting `output_classes`, `output_shapes`, and `output_types`, so I am not sure which tensor it is unable to get the shape of. Is there anything I can do to narrow down what is causing this bug? Keep in mind, I am running in a docker container, so code changes are a little difficult to achieve.

This may only happen when using `tf.distribute.MirriredStrategy` with a single GPU.

**Comment by rachellim** [comment]
The issue here seems to be that your dataset has some elements with (completely) unknown shape, and we fail to handle that case correctly. Thanks for flagging this, I have a fix in review. 


Side note: I don't expect the following code to work:
```
    # Set output shapes, types, and classes
    dataset.output_classes = (
        (tf.Tensor, tf.Tensor, tf.Tensor, tf.Tensor, tf.Tensor),
        (tf.Tensor, tf.Tensor, tf.Tensor, tf.Tensor, tf.Tensor),
    )
    dataset.output_types = (
        (tf.dtypes.string, tf.dtypes.int64, tf.dtypes.int64, tf.dtypes.uint8, tf.dtypes.uint8,),
        (tf.dtypes.string, tf.dtypes.int64, tf.dtypes.int64, tf.dtypes.float32, tf.dtypes.float32,),
    )
    dataset.output_shapes = (
        ([], [], [], tf.TensorShape([None, None, 3]), tf.TensorShape([None, None, 3]),),
        ([], [], [], tf.TensorShape([None, None, 1]), tf.TensorShape([None, None, 1]),),
    )
```
You'd get an error if you try to set dataset output shapes/types explicitly... unless you meant this as pseudocode?
