### ISSUE TITLE
Got "ValueError: Unable to create group (name already exists)" when saving a convolutional model

### ISSUE THREAD

**Issue by gekowa** [tensorflow/tensorflow#34479]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.0.0-rc2-26-g64c3d382ca
- Python version: 3.7.3
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
I'm currently building a YOLOv3 model, the training was good, but when I try to save the model to h5 format, it throws out the "ValueError: Unable to create group (name already exists)".

**Describe the expected behavior**
It should finish the save process successfully.

**Code to reproduce the issue**
```
tf.keras.models.save_model(model, "model.h5", save_format="h5")
```

**Other info / logs**
The log:
```
Traceback (most recent call last):
  File "image_demo.py", line 58, in <module>
    tf.keras.models.save_model(model, "model.h5", save_format="h5")
  File "/Users/xhguo/Workspace/TensorFlow2.0-Examples/4-Object_Detection/YOLOV3/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/save.py", line 112, in save_model
    model, filepath, overwrite, include_optimizer)
  File "/Users/xhguo/Workspace/TensorFlow2.0-Examples/4-Object_Detection/YOLOV3/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/hdf5_format.py", line 110, in save_model_to_hdf5
    save_weights_to_hdf5_group(model_weights_group, model_layers)
  File "/Users/xhguo/Workspace/TensorFlow2.0-Examples/4-Object_Detection/YOLOV3/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/hdf5_format.py", line 627, in save_weights_to_hdf5_group
    g = f.create_group(layer.name)
  File "/Users/xhguo/Workspace/TensorFlow2.0-Examples/4-Object_Detection/YOLOV3/lib/python3.7/site-packages/h5py/_hl/group.py", line 61, in create_group
    gid = h5g.create(self.id, name, lcpl=lcpl, gcpl=gcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5g.pyx", line 161, in h5py.h5g.create
ValueError: Unable to create group (name already exists)
```

**Comment by gadagashwini** [comment]
@gekowa, Please provide the complete standalone code to reproduce the reported issue.Thanks!

**Comment by gadagashwini** [comment]
@gekowa, Similar issue [#32672](https://github.com/tensorflow/tensorflow/issues/32672). Thanks

**Comment by tensorflowbutler** [comment]
It has been 15 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
It has been 30 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
We are closing this issue for now due to lack of activity. Please comment if this is still an issue for you. Thanks!

**Comment by GoingMyWay** [comment]
try to use tf.keras  `Lambda` if you do some op on Inputs.
