### ISSUE TITLE
fit_generator with use_multiprocessing=True causes runtime error when initializing worker pool

### ISSUE THREAD

**Issue by tonysung** [tensorflow/tensorflow#34473]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes.
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): This -> https://cloud.google.com/ml-engine/docs/runtime-version-list#1.14
- TensorFlow installed from (source or binary): Binary.
- TensorFlow version (use command below): 1.14
- Python version: 3.5

**Describe the current behavior**

Train a model with:

```
import multiprocessing as mp

if __name__ == '__main__':
    mp.set_start_method('spawn') # or 'forkserver'

    ...
    ...
    model.fit_generator(
        generator=train_seq,
        validation_data=val_seq,
        callbacks=callbacks,
        shuffle=True,
        initial_epoch=0,
        epochs=1000,
        max_queue_size=16,
        workers=4,
        use_multiprocessing=True,
        verbose=1,
    )
```

The following runtime error is usually raised in the middle of training (a few epochs has elapsed), near the end of an epoch, and training hanged:

```
ERROR	2019-11-21 10:20:18 +0800	master-replica-0		Exception in thread Thread-33:
ERROR	2019-11-21 10:20:18 +0800	master-replica-0		Traceback (most recent call last):
ERROR	2019-11-21 10:20:18 +0800	master-replica-0		  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
ERROR	2019-11-21 10:20:18 +0800	master-replica-0		    self.run()
ERROR	2019-11-21 10:20:18 +0800	master-replica-0		  File "/usr/lib/python3.5/threading.py", line 862, in run
ERROR	2019-11-21 10:20:18 +0800	master-replica-0		    self._target(*self._args, **self._kwargs)
ERROR	2019-11-21 10:20:18 +0800	master-replica-0		  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/utils/data_utils.py", line 748, in _run
ERROR	2019-11-21 10:20:18 +0800	master-replica-0		    with closing(self.executor_fn(_SHARED_SEQUENCES)) as executor:
ERROR	2019-11-21 10:20:18 +0800	master-replica-0		  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/utils/data_utils.py", line 727, in pool_fn
ERROR	2019-11-21 10:20:18 +0800	master-replica-0		    initargs=(seqs, None, get_worker_id_queue()))
ERROR	2019-11-21 10:20:18 +0800	master-replica-0		  File "/usr/lib/python3.5/multiprocessing/context.py", line 118, in Pool
ERROR	2019-11-21 10:20:18 +0800	master-replica-0		    context=self.get_context())
ERROR	2019-11-21 10:20:18 +0800	master-replica-0		  File "/usr/lib/python3.5/multiprocessing/pool.py", line 168, in __init__
ERROR	2019-11-21 10:20:18 +0800	master-replica-0		    self._repopulate_pool()
ERROR	2019-11-21 10:20:18 +0800	master-replica-0		  File "/usr/lib/python3.5/multiprocessing/pool.py", line 233, in _repopulate_pool
ERROR	2019-11-21 10:20:18 +0800	master-replica-0		    w.start()
ERROR	2019-11-21 10:20:18 +0800	master-replica-0		  File "/usr/lib/python3.5/multiprocessing/process.py", line 105, in start
ERROR	2019-11-21 10:20:18 +0800	master-replica-0		    self._popen = self._Popen(self)
ERROR	2019-11-21 10:20:18 +0800	master-replica-0		  File "/usr/lib/python3.5/multiprocessing/context.py", line 274, in _Popen
ERROR	2019-11-21 10:20:18 +0800	master-replica-0		    return Popen(process_obj)
ERROR	2019-11-21 10:20:18 +0800	master-replica-0		  File "/usr/lib/python3.5/multiprocessing/popen_spawn_posix.py", line 33, in __init__
ERROR	2019-11-21 10:20:18 +0800	master-replica-0		    super().__init__(process_obj)
ERROR	2019-11-21 10:20:18 +0800	master-replica-0		  File "/usr/lib/python3.5/multiprocessing/popen_fork.py", line 20, in __init__
ERROR	2019-11-21 10:20:18 +0800	master-replica-0		    self._launch(process_obj)
ERROR	2019-11-21 10:20:18 +0800	master-replica-0		  File "/usr/lib/python3.5/multiprocessing/popen_spawn_posix.py", line 48, in _launch
ERROR	2019-11-21 10:20:18 +0800	master-replica-0		    reduction.dump(process_obj, fp)
ERROR	2019-11-21 10:20:18 +0800	master-replica-0		  File "/usr/lib/python3.5/multiprocessing/reduction.py", line 59, in dump
ERROR	2019-11-21 10:20:18 +0800	master-replica-0		    ForkingPickler(file, protocol).dump(obj)
ERROR	2019-11-21 10:20:18 +0800	master-replica-0		RuntimeError: dictionary changed size during iteration
```

Similarly when using ```forkserver``` as the start method:

```
2019-11-20T16:54:34.389836549Z master-replica-0 Exception in thread Thread-33: E  master-replica-0
2019-11-20T16:54:34.390263319Z master-replica-0 Traceback (most recent call last): E  master-replica-0
2019-11-20T16:54:34.391031265Z master-replica-0   File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner E  master-replica-0
2019-11-20T16:54:34.391372919Z master-replica-0     self.run() E  master-replica-0
2019-11-20T16:54:34.391650676Z master-replica-0   File "/usr/lib/python3.5/threading.py", line 862, in run E  master-replica-0
2019-11-20T16:54:34.391963958Z master-replica-0     self._target(*self._args, **self._kwargs) E  master-replica-0
2019-11-20T16:54:34.392265796Z master-replica-0   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/utils/data_utils.py", line 748, in _run E  master-replica-0
2019-11-20T16:54:34.392584800Z master-replica-0     with closing(self.executor_fn(_SHARED_SEQUENCES)) as executor: E  master-replica-0
2019-11-20T16:54:34.392927646Z master-replica-0   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/utils/data_utils.py", line 727, in pool_fn E  master-replica-0
2019-11-20T16:54:34.393241405Z master-replica-0     initargs=(seqs, None, get_worker_id_queue())) E  master-replica-0
2019-11-20T16:54:34.393555641Z master-replica-0   File "/usr/lib/python3.5/multiprocessing/context.py", line 118, in Pool E  master-replica-0
2019-11-20T16:54:34.394298315Z master-replica-0     context=self.get_context()) E  master-replica-0
2019-11-20T16:54:34.394565820Z master-replica-0   File "/usr/lib/python3.5/multiprocessing/pool.py", line 168, in __init__ E  master-replica-0
2019-11-20T16:54:34.394963264Z master-replica-0     self._repopulate_pool() E  master-replica-0
2019-11-20T16:54:34.395295143Z master-replica-0   File "/usr/lib/python3.5/multiprocessing/pool.py", line 233, in _repopulate_pool E  master-replica-0
2019-11-20T16:54:34.395615577Z master-replica-0     w.start() E  master-replica-0
2019-11-20T16:54:34.395916461Z master-replica-0   File "/usr/lib/python3.5/multiprocessing/process.py", line 105, in start E  master-replica-0
2019-11-20T16:54:34.396240472Z master-replica-0     self._popen = self._Popen(self) E  master-replica-0
2019-11-20T16:54:34.396524190Z master-replica-0   File "/usr/lib/python3.5/multiprocessing/context.py", line 281, in _Popen E  master-replica-0
2019-11-20T16:54:34.396835565Z master-replica-0     return Popen(process_obj) E  master-replica-0
2019-11-20T16:54:34.397135734Z master-replica-0   File "/usr/lib/python3.5/multiprocessing/popen_forkserver.py", line 36, in __init__ E  master-replica-0
2019-11-20T16:54:34.397473096Z master-replica-0     super().__init__(process_obj) E  master-replica-0
2019-11-20T16:54:34.397750616Z master-replica-0   File "/usr/lib/python3.5/multiprocessing/popen_fork.py", line 20, in __init__ E  master-replica-0
2019-11-20T16:54:34.398015022Z master-replica-0     self._launch(process_obj) E  master-replica-0
2019-11-20T16:54:34.398270130Z master-replica-0   File "/usr/lib/python3.5/multiprocessing/popen_forkserver.py", line 48, in _launch E  master-replica-0
2019-11-20T16:54:34.398548603Z master-replica-0     reduction.dump(process_obj, buf) E  master-replica-0
2019-11-20T16:54:34.398846387Z master-replica-0   File "/usr/lib/python3.5/multiprocessing/reduction.py", line 59, in dump E  master-replica-0
2019-11-20T16:54:34.399111270Z master-replica-0     ForkingPickler(file, protocol).dump(obj) E  master-replica-0
2019-11-20T16:54:34.399379014Z master-replica-0 RuntimeError: dictionary changed size during iteration E  master-replica-0
```

**Comment by gadagashwini** [comment]
@tonysung, Please provide the complete standalone code to reproduce the reported issue. Thanks!

**Comment by gadagashwini** [comment]
@tonysung, Please post complete code snippet to analyze the issue. Thanks!

**Comment by tonysung** [comment]
Sorry, we wouldn't be able to provide a reduced test case. Please close.

**Comment by gadagashwini** [comment]
Closing the issue. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
