### ISSUE TITLE
tf.meshgrid bug: Duplicate node name in graph

### ISSUE THREAD

**Issue by kevinkingo** [tensorflow/tensorflow#34470]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): v2.0.0-rc2-26-g64c3d38 2.0.0
- Python version: 3.7.4
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: cuda 10.0, cudnn 7
- GPU model and memory: GTX 1080Ti

**Describe the current behavior**.
What I am trying to do is to warp a feature map (shape (N, H, W, C)) using an offset (shape (N, H, W, 2)). However, it doesn't compile. It seems there's some problem on name scopes inside tf.meshgrid.
```
Traceback (most recent call last):
  File "/home/kingo/Documents/projects/SunRelight/code/sun_relight/network_training/test.py", line 25, in <module>
    out = warp(x, offset)
  File "/home/kingo/Documents/projects/SunRelight/code/sun_relight/network_training/test.py", line 14, in warp
    base_coord2 = tf.stack(tf.meshgrid(tf.range(W), tf.range(H))[::-1], axis=-1)
  File "/home/kingo/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/ops/array_ops.py", line 2954, in meshgrid
    mult_fact = ones(shapes, output_dtype)
  File "/home/kingo/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/ops/array_ops.py", line 2583, in ones
    output = fill(shape, constant(one, dtype=dtype), name=name)
  File "/home/kingo/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/ops/array_ops.py", line 171, in fill
    result = gen_array_ops.fill(dims, value, name=name)
  File "/home/kingo/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_array_ops.py", line 3602, in fill
    "Fill", dims=dims, value=value, name=name)
  File "/home/kingo/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/framework/op_def_library.py", line 793, in _apply_op_helper
    op_def=op_def)
  File "/home/kingo/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/framework/func_graph.py", line 548, in create_op
    compute_device)
  File "/home/kingo/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3429, in _create_op_internal
    op_def=op_def)
  File "/home/kingo/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 1773, in __init__
    control_input_ops)
  File "/home/kingo/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 1613, in _create_c_op
    raise ValueError(str(e))
ValueError: Duplicate node name in graph: 'ones'
```

**Describe the expected behavior**
No error should happen.

**Code to reproduce the issue**
```
import cv2
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.python.keras import backend as K

def warp(inputs, offset):
  tensor_input_shape = K.shape(inputs)
  batch_size = tensor_input_shape[0]
  H = tensor_input_shape[1]
  W = tensor_input_shape[2]

  base_coord = tf.stack(tf.meshgrid(tf.range(W), tf.range(H))[::-1], axis=-1)
  base_coord2 = tf.stack(tf.meshgrid(tf.range(W), tf.range(H))[::-1], axis=-1) # Only to show the bug
  # base_coord = tf.tile(base_coord[tf.newaxis, :, :, :], [batch_size, 1, 1, 1])
  # target_coord = tf.cast(tf.cast(base_coord, tf.float32) + offset, tf.int32)
  # target_coord = tf.clip_by_value(
  #     target_coord, 0,
  #     tf.stack([H-1, W-1])[tf.newaxis, tf.newaxis, tf.newaxis, :])

  return tf.gather_nd(inputs, base_coord2, batch_dims=1)

x = keras.Input(shape=(None, None, 3))
offset = keras.Input(shape=(None, None, 2))
out = warp(x, offset)
net = keras.Model(inputs=[x, offset], outputs=out)
```

**Comment by ravikyram** [comment]
Can you try running the code in latest -tf-nightly `(!pip install tf-nightly-gpu==2.1.0dev20191121`).Issue seemed to be fixed, kindly find the [gist](https://colab.sandbox.google.com/gist/ravikyram/68cba0317e31a6aa835523edabc03d4b/untitled393.ipynb) of colab for the same.Thanks!

**Comment by ravikyram** [comment]
@kevinkingo 
Can you please confirm whether your issue got resolved with nightly versions.Please,confirm whether we can close this thread if the issue was already resolved. Thanks!

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by peteryuX** [comment]
There still have same error in the 2.1.0 ...
```
ValueError: Duplicate node name in graph: 'ones'
```
but the tf-nightly-gpu==2.1.0dev20191121 above is alright.
