### ISSUE TITLE
Concat within tf.range loop throwing error when converting to tflite: StatelessWhile custom implementation needed

### ISSUE THREAD

**Issue by m-ciniello** [tensorflow/tensorflow#34502]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): OSX 10.14.6
- TensorFlow installed from (source or binary): 
- TensorFlow version (or github SHA if from source): '2.0.0-dev20191002'

**Provide the text output from tflite_convert**

```
ConverterError: See console for info.
2019-11-21 19:25:54.528881: E tensorflow/core/platform/hadoop/hadoop_file_system.cc:132] HadoopFileSystem load error: dlopen(libhdfs.dylib, 6): image not found
2019-11-21 19:25:56.545440: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-11-21 19:25:56.559290: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7f9d67546760 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2019-11-21 19:25:56.559306: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2019-11-21 19:25:56.568668: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: StatelessWhile
2019-11-21 19:25:56.568994: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 4 operators, 19 arrays (0 quantized)
2019-11-21 19:25:56.569203: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 4 operators, 19 arrays (0 quantized)
2019-11-21 19:25:56.569378: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 1: 3 operators, 18 arrays (0 quantized)
2019-11-21 19:25:56.569450: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Group bidirectional sequence lstm/rnn: 3 operators, 18 arrays (0 quantized)
2019-11-21 19:25:56.569489: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before dequantization graph transformations: 3 operators, 18 arrays (0 quantized)
2019-11-21 19:25:56.569553: I tensorflow/lite/toco/allocate_transient_arrays.cc:345] Total transient array allocated size: 6769536 bytes, theoretical optimal value: 6769536 bytes.
2019-11-21 19:25:56.569584: I tensorflow/lite/toco/toco_tooling.cc:439] Estimated count of arithmetic ops: 0 ops, equivalently 0 MACs
2019-11-21 19:25:56.569588: I tensorflow/lite/toco/toco_tooling.cc:454] Number of parameters: 828
2019-11-21 19:25:56.569891: E tensorflow/lite/toco/toco_tooling.cc:481] We are continually in the process of adding support to TensorFlow Lite for more ops. It would be helpful if you could inform us of how this conversion went by opening a github issue at https://github.com/tensorflow/tensorflow/issues/new?template=40-tflite-op-request.md
 and pasting the following:

Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: RESHAPE, TRANSPOSE. Here is a list of operators for which you will need custom implementations: StatelessWhile.

```

Below is the function I am trying to convert to tflite (which will eventually be put into a custom layer). I'm trying to extract argmax coordinates from a series of filters. I was initially using **tf.tensor_scatter_nd_update** to accomplish this task, however tflite does not support that op either, so I went with the 'concat_with_padding' loop as described here:  https://www.tensorflow.org/tutorials/customization/performance. The function works fine, it only throws that error when trying to convert to tflite. 

```
@tf.function(input_signature=[tf.TensorSpec(shape=[1,24,34,61,17], dtype=tf.float32)])
def extract_points(heatmaps):
    batch_size = heatmaps.shape[0]
    timesteps = heatmaps.shape[1]
    filter_width = heatmaps.shape[2]
    filter_height = heatmaps.shape[3]
    keypoints = heatmaps.shape[-1]
    
    n = batch_size*timesteps*keypoints
    hm2 = tf.transpose(heatmaps, [0,1,4,2,3])
    hm3 = tf.reshape(hm2, (n,-1))
    x = tf.zeros([n, 2])

    for i in tf.range(n):
        X_argm = tf.argmax(hm3[i])
        coords = tf.reshape(tf.cast(tf.unravel_index(X_argm, (filter_width, filter_height)), 'float32'), (1,2))
        x = tf.concat([x[:i], coords, tf.zeros([n-1-i, 2])], axis=0)
        x = tf.reshape(x, [n, 2])
    return  x       

concrete_func = extract_points.get_concrete_function()
converter = tf.lite.TFLiteConverter.from_concrete_functions([concrete_func])
tflite_model = converter.convert()
```

**Comment by jianlijianli** [comment]
Adding haozha111 to triage the issue since this involves converting loops. Thanks.

**Comment by haozha111** [comment]
Hi,

can you try the new TF Lite converter by setting:
converter.experimental_new_converter = True.

Thanks.

**Comment by m-ciniello** [comment]
> Hi,
> 
> can you try the new TF Lite converter by setting:
> converter.experimental_new_converter = True.
> 
> Thanks.

I tried that as follows: 
```
converter = tf.lite.TFLiteConverter.from_concrete_functions([concrete_func])
converter.experimental_new_converter = True
tflite_model = converter.convert()
```

Got the same error:
```
Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: RESHAPE, TRANSPOSE. Here is a list of operators for which you will need custom implementations: StatelessWhile.
Traceback (most recent call last):
  File "/anaconda3/envs/posenet-v5/bin/toco_from_protos", line 8, in <module>
    sys.exit(main())
  File "/anaconda3/envs/posenet-v5/lib/python3.7/site-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 89, in main
    app.run(main=execute, argv=[sys.argv[0]] + unparsed)
  File "/anaconda3/envs/posenet-v5/lib/python3.7/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/anaconda3/envs/posenet-v5/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/anaconda3/envs/posenet-v5/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/anaconda3/envs/posenet-v5/lib/python3.7/site-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 52, in execute
    enable_mlir_converter)
```

**Comment by m-ciniello** [comment]
It actually appears to be "unravel_index" that is the main problem. However this still doesnt address the ''**StatelessWhile**" issue is:

```
@tf.function(input_signature=[tf.TensorSpec(shape=[1,24,34,61,17], dtype=tf.float32)])
def extract_points(heatmaps):
    batch_size = heatmaps.shape[0]
    timesteps = heatmaps.shape[1]
    filter_width = heatmaps.shape[2]
    filter_height = heatmaps.shape[3]
    keypoints = heatmaps.shape[-1]
    
    n = batch_size*timesteps*keypoints
    hm2 = tf.transpose(heatmaps, [0,1,4,2,3])
    hm3 = tf.reshape(hm2, (n,-1))
    x = tf.zeros([n, 2])
    y = tf.zeros([n, 2])
    
    X_argm = tf.argmax(hm3[0])
    coords = tf.unravel_index(X_argm, (filter_width, filter_height))
    return  coords    

concrete_func = extract_points.get_concrete_function()
converter = tf.lite.TFLiteConverter.from_concrete_functions([concrete_func])
converter.experimental_new_converter = True
tflite_model = converter.convert()
```
Here is the error:
```
Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ARG_MAX, RESHAPE, STRIDED_SLICE, TRANSPOSE. Here is a list of operators for which you will need custom implementations: UnravelIndex.
```

**Comment by haozha111** [comment]
from the error message, it seems that it's still using the old tflite converter. can you download the latest tf-nighly pip and then try (this could probably resolve the statelesswhile issue)?

for the `UnravelIndex` op, unfortunately currently it's not supported by TF Lite as a built-in op.
