### ISSUE TITLE
Failed to load the native TensorFlow runtime

### ISSUE THREAD

**Issue by christosiraklis** [tensorflow/tensorflow#34557]
**System information**
- Windows 10
- pip install tensorflow in Anaconda
- TensorFlow version: 2.0.0
- Python version: 3.6
- Installed using virtualenv? pip? conda?: pip

While trying to load keras.datasets,

Traceback (most recent call last):
  File "c:\users\chris\anaconda3\envs\ml\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "c:\users\chris\anaconda3\envs\ml\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "c:\users\chris\anaconda3\envs\ml\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "c:\users\chris\anaconda3\envs\ml\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "c:\users\chris\anaconda3\envs\ml\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\chris\anaconda3\envs\ml\lib\site-packages\IPython\core\interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-d6cb0ef8e627>", line 15, in <module>
    from keras import datasets
  File "c:\users\chris\anaconda3\envs\ml\lib\site-packages\keras\__init__.py", line 3, in <module>
    from . import utils
  File "c:\users\chris\anaconda3\envs\ml\lib\site-packages\keras\utils\__init__.py", line 6, in <module>
    from . import conv_utils
  File "c:\users\chris\anaconda3\envs\ml\lib\site-packages\keras\utils\conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "c:\users\chris\anaconda3\envs\ml\lib\site-packages\keras\backend\__init__.py", line 1, in <module>
    from .load_backend import epsilon
  File "c:\users\chris\anaconda3\envs\ml\lib\site-packages\keras\backend\load_backend.py", line 90, in <module>
    from .tensorflow_backend import *
  File "c:\users\chris\anaconda3\envs\ml\lib\site-packages\keras\backend\tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf
  File "c:\users\chris\anaconda3\envs\ml\lib\site-packages\tensorflow\__init__.py", line 98, in <module>
    from tensorflow_core import *
  File "c:\users\chris\anaconda3\envs\ml\lib\site-packages\tensorflow_core\__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "c:\users\chris\anaconda3\envs\ml\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "c:\users\chris\anaconda3\envs\ml\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "c:\users\chris\anaconda3\envs\ml\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "c:\users\chris\anaconda3\envs\ml\lib\site-packages\tensorflow_core\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "c:\users\chris\anaconda3\envs\ml\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "c:\users\chris\anaconda3\envs\ml\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "c:\users\chris\anaconda3\envs\ml\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "c:\users\chris\anaconda3\envs\ml\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "c:\users\chris\anaconda3\envs\ml\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "c:\users\chris\anaconda3\envs\ml\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

Failed to load the native TensorFlow runtime.

**Comment by christosiraklis** [comment]
Solved by installing tensorflow 1.5 version and keras 2.2 version.
