### ISSUE TITLE
Tensorflow 2.0  build fail in Windows 10

### ISSUE THREAD

**Issue by googincheng** [tensorflow/tensorflow#34552]
### Environment
Windows 10
gtx 1050Ti
CUDA driver 441
CUDA tool kit 10.0
CuDNN 7
Python 3.5
Bazel 0.27.1

### Action
follow the official instruction. https://www.tensorflow.org/install/source_windows

run :
`C:\Users\admin\tensorflow>bazel build //tensorflow/tools/pip_package:build_pip_package`
### ERROR INFO

> **ERROR: An error occurred during the fetch of repository 'local_config_cuda':**
   Traceback (most recent call last):
        File "C:/users/admin/tensorflow/third_party/gpus/cuda_configure.bzl", line 1304
                _create_local_cuda_repository(repository_ctx)
        File "C:/users/admin/tensorflow/third_party/gpus/cuda_configure.bzl", line 1132, in _create_local_cuda_repository
                find_cc(repository_ctx)
        File "C:/users/admin/tensorflow/third_party/gpus/cuda_configure.bzl", line 227, in find_cc
                _get_msvc_compiler(repository_ctx)
        File "C:/users/admin/tensorflow/third_party/gpus/cuda_configure.bzl", line 145, in _get_msvc_compiler
                find_msvc_tool(repository_ctx, vc_path, "cl.exe").replace("\\", "/")
type 'NoneType' has no method replace()
**ERROR: Skipping '//tensorflow/tools/pip_package:build_pip_package': error loading package 'tensorflow/tools/pip_package': Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda':** Traceback (most recent call last):
        File "C:/users/admin/tensorflow/third_party/gpus/cuda_configure.bzl", line 1304
                _create_local_cuda_repository(repository_ctx)
        File "C:/users/admin/tensorflow/third_party/gpus/cuda_configure.bzl", line 1132, in _create_local_cuda_repository
                find_cc(repository_ctx)
        File "C:/users/admin/tensorflow/third_party/gpus/cuda_configure.bzl", line 227, in find_cc
                _get_msvc_compiler(repository_ctx)
        File "C:/users/admin/tensorflow/third_party/gpus/cuda_configure.bzl", line 145, in _get_msvc_compiler
                find_msvc_tool(repository_ctx, vc_path, "cl.exe").replace("\\", "/")
type 'NoneType' has no method replace()
WARNING: Target pattern parsing failed.
**ERROR: error loading package 'tensorflow/tools/pip_package': Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda':** Traceback (most recent call last):
        File "C:/users/admin/tensorflow/third_party/gpus/cuda_configure.bzl", line 1304
                _create_local_cuda_repository(repository_ctx)
        File "C:/users/admin/tensorflow/third_party/gpus/cuda_configure.bzl", line 1132, in _create_local_cuda_repository
                find_cc(repository_ctx)
        File "C:/users/admin/tensorflow/third_party/gpus/cuda_configure.bzl", line 227, in find_cc
                _get_msvc_compiler(repository_ctx)
        File "C:/users/admin/tensorflow/third_party/gpus/cuda_configure.bzl", line 145, in _get_msvc_compiler
                find_msvc_tool(repository_ctx, vc_path, "cl.exe").replace("\\", "/")
type 'NoneType' has no method replace()
INFO: Elapsed time: 31.315s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: tensorflow/tools/pip_package

Hope for your help

**Comment by ravikyram** [comment]
@googincheng 
I think the problem is with Bazel and MSVC.Please, go through the [link](https://docs.bazel.build/versions/0.27.0/install-compile-source.html#bootstrap-windows-bootstrapp) and see if it helps you.Please, check whether you set the environment variable BAZEL_VS (or BAZEL_VC) correctly. Thanks!

**Comment by googincheng** [comment]
@ravikyram Thanks! Seems it would work.
