### ISSUE TITLE
operators in the model are not supported by the standard TensorFlow Lite runtime

### ISSUE THREAD

**Issue by jiraiyajr98** [tensorflow/tensorflow#34563]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Win 10 x64
- TensorFlow version (or github SHA if from source):  2.0

**Provide the text output from tflite_convert**

```
# CODE
```
----------------------------------------------------------------------------

import tensorflow as tf

filename = 'model_24_11_19_3'
model = tf.saved_model.load(filename)

concrete_func = model.signatures[
  tf.saved_model.DEFAULT_SERVING_SIGNATURE_DEF_KEY]

concrete_func.inputs[0].set_shape([1,8])
converter = tf.lite.TFLiteConverter.from_concrete_functions([concrete_func])

Tflite_model = converter.convert()
open("converted_model_new1.tflite", "wb").write(Tflite_model)

*LOGS* 

2019-11-25 02:07:37.676230: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2019-11-25 02:07:38.516215: I tensorflow/core/grappler/devices.cc:60] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0 (Note: TensorFlow was not compiled with CUDA support)
2019-11-25 02:07:38.516605: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2019-11-25 02:07:38.537041: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:814] Optimization results for grappler item: graph_to_optimize
2019-11-25 02:07:38.537143: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   function_optimizer: Graph size after: 243 nodes (231), 405 edges (393), time = 7.653ms.
2019-11-25 02:07:38.537239: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   function_optimizer: Graph size after: 243 nodes (0), 405 edges (0), time = 3.096ms.
2019-11-25 02:07:38.537326: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:814] Optimization results for grappler item: __inference_sequential_lstm_while_body_296488_706
2019-11-25 02:07:38.537407: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   function_optimizer: function_optimizer did nothing. time = 0.001ms.
2019-11-25 02:07:38.537479: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   function_optimizer: function_optimizer did nothing. time = 0ms.
2019-11-25 02:07:38.537555: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:814] Optimization results for grappler item: __inference_sequential_lstm_while_cond_296487_4136
2019-11-25 02:07:38.537652: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   function_optimizer: function_optimizer did nothing. time = 0ms.
2019-11-25 02:07:38.537730: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   function_optimizer: function_optimizer did nothing. time = 0ms.
2019-11-25 02:07:38.537821: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:814] Optimization results for grappler item: __inference_sequential_lstm_1_while_cond_296673_1329
2019-11-25 02:07:38.537908: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   function_optimizer: function_optimizer did nothing. time = 0ms.
2019-11-25 02:07:38.537982: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   function_optimizer: function_optimizer did nothing. time = 0ms.
2019-11-25 02:07:38.538056: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:814] Optimization results for grappler item: __inference_sequential_lstm_1_while_body_296674_505
2019-11-25 02:07:38.538147: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   function_optimizer: function_optimizer did nothing. time = 0.001ms.
2019-11-25 02:07:38.538697: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   function_optimizer: function_optimizer did nothing. time = 0ms.
2019-11-25 02:07:38.963864: I tensorflow/core/grappler/devices.cc:60] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0 (Note: TensorFlow was not compiled with CUDA support)
2019-11-25 02:07:38.964405: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2019-11-25 02:07:40.804458: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:814] Optimization results for grappler item: graph_to_optimize
2019-11-25 02:07:40.804545: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   constant_folding: Graph size after: 167 nodes (-77), 290 edges (-115), time = 1596.62ms.
2019-11-25 02:07:40.804631: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   constant_folding: Graph size after: 167 nodes (0), 290 edges (0), time = 168.831ms.
2019-11-25 02:07:40.804719: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:814] Optimization results for grappler item: __inference_sequential_lstm_while_cond_296487_4136_frozen
2019-11-25 02:07:40.804817: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   constant_folding: Graph size after: 16 nodes (0), 4 edges (0), time = 0.611ms.
2019-11-25 02:07:40.804907: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   constant_folding: Graph size after: 16 nodes (0), 4 edges (0), time = 0.151ms.
2019-11-25 02:07:40.804991: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:814] Optimization results for grappler item: __inference_sequential_lstm_1_while_body_296674_505_frozen
2019-11-25 02:07:40.805089: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   constant_folding: Graph size after: 53 nodes (-1), 71 edges (0), time = 1.521ms.
2019-11-25 02:07:40.805182: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   constant_folding: Graph size after: 53 nodes (0), 71 edges (0), time = 0.589ms.
2019-11-25 02:07:40.805618: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:814] Optimization results for grappler item: __inference_sequential_lstm_1_while_cond_296673_1329_frozen
2019-11-25 02:07:40.805734: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   constant_folding: Graph size after: 14 nodes (0), 4 edges (0), time = 0.561ms.
2019-11-25 02:07:40.805837: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   constant_folding: Graph size after: 14 nodes (0), 4 edges (0), time = 0.155ms.
2019-11-25 02:07:40.805941: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:814] Optimization results for grappler item: __inference_sequential_lstm_while_body_296488_706_frozen
2019-11-25 02:07:40.806047: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   constant_folding: Graph size after: 69 nodes (-1), 95 edges (0), time = 1.81ms.
2019-11-25 02:07:40.806125: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   constant_folding: Graph size after: 69 nodes (0), 95 edges (0), time = 0.815ms.
Traceback (most recent call last):
  File "D:/Projects/Test3/NMT.py", line 15, in <module>
    Tflite_model = converter.convert()
  File "C:\Users\Jiraiya\Anaconda3\envs\env_tensorflow2\lib\site-packages\tensorflow_core\lite\python\lite.py", line 474, in convert
    **converter_kwargs)
  File "C:\Users\Jiraiya\Anaconda3\envs\env_tensorflow2\lib\site-packages\tensorflow_core\lite\python\convert.py", line 475, in toco_convert_impl
    enable_mlir_converter=enable_mlir_converter)
  File "C:\Users\Jiraiya\Anaconda3\envs\env_tensorflow2\lib\site-packages\tensorflow_core\lite\python\convert.py", line 215, in toco_convert_protos
    raise ConverterError("See console for info.\n%s\n%s\n" % (stdout, stderr))
tensorflow.lite.python.convert.ConverterError: See console for info.
2019-11-25 02:07:42.853028: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2019-11-25 02:07:42.970994: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorListFromTensor
2019-11-25 02:07:42.971178: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 21
2019-11-25 02:07:42.971275: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorListFromTensor
2019-11-25 02:07:42.971504: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 21
2019-11-25 02:07:42.971600: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorListReserve
2019-11-25 02:07:42.971734: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 21
2019-11-25 02:07:42.971851: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: While
2019-11-25 02:07:42.971919: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 21
2019-11-25 02:07:42.972082: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 21
2019-11-25 02:07:42.972184: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 21
2019-11-25 02:07:42.972291: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorListStack
2019-11-25 02:07:42.972388: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorListFromTensor
2019-11-25 02:07:42.972463: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 21
2019-11-25 02:07:42.972543: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorListReserve
2019-11-25 02:07:42.972613: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 21
2019-11-25 02:07:42.972845: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: While
2019-11-25 02:07:42.972914: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 21
2019-11-25 02:07:42.973048: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 21
2019-11-25 02:07:42.973170: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorListStack
2019-11-25 02:07:42.992717: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 77 operators, 174 arrays (0 quantized)
2019-11-25 02:07:42.993725: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 77 operators, 174 arrays (0 quantized)
2019-11-25 02:07:43.009358: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 1: 53 operators, 139 arrays (0 quantized)
2019-11-25 02:07:43.012720: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 2: 51 operators, 136 arrays (0 quantized)
2019-11-25 02:07:43.013768: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Group bidirectional sequence lstm/rnn: 51 operators, 136 arrays (0 quantized)
2019-11-25 02:07:43.014716: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before dequantization graph transformations: 51 operators, 136 arrays (0 quantized)
2019-11-25 02:07:43.015495: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Identify nearest upsample.: 51 operators, 136 arrays (0 quantized)
2019-11-25 02:07:43.016573: I tensorflow/lite/toco/allocate_transient_arrays.cc:345] Total transient array allocated size: 32896 bytes, theoretical optimal value: 32768 bytes.
2019-11-25 02:07:43.016915: I tensorflow/lite/toco/toco_tooling.cc:471] Number of parameters: 8969974
2019-11-25 02:07:43.017550: E tensorflow/lite/toco/toco_tooling.cc:498] We are continually in the process of adding support to TensorFlow Lite for more ops. It would be helpful if you could inform us of how this conversion went by opening a github issue at https://github.com/tensorflow/tensorflow/issues/new?template=40-tflite-op-request.md
 and pasting the following:

Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, CAST, CONCATENATION, DIV, EXP, EXPAND_DIMS, FILL, FULLY_CONNECTED, GATHER, LOGISTIC, MUL, NOT_EQUAL, PACK, REDUCE_MAX, RESHAPE, SHAPE, SPLIT, STRIDED_SLICE, SUB, SUM, TANH, TILE, TRANSPOSE, ZEROS_LIKE. Here is a list of operators for which you will need custom implementations: TensorListFromTensor, TensorListReserve, TensorListStack, While.
Traceback (most recent call last):
  File "c:\users\jiraiya\anaconda3\envs\env_tensorflow2\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\jiraiya\anaconda3\envs\env_tensorflow2\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Jiraiya\Anaconda3\envs\env_tensorflow2\Scripts\toco_from_protos.exe\__main__.py", line 7, in <module>
  File "c:\users\jiraiya\anaconda3\envs\env_tensorflow2\lib\site-packages\tensorflow_core\lite\toco\python\toco_from_protos.py", line 93, in main
    app.run(main=execute, argv=[sys.argv[0]] + unparsed)
  File "c:\users\jiraiya\anaconda3\envs\env_tensorflow2\lib\site-packages\tensorflow_core\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "c:\users\jiraiya\anaconda3\envs\env_tensorflow2\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "c:\users\jiraiya\anaconda3\envs\env_tensorflow2\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "c:\users\jiraiya\anaconda3\envs\env_tensorflow2\lib\site-packages\tensorflow_core\lite\toco\python\toco_from_protos.py", line 56, in execute
    enable_mlir_converter)
Exception: We are continually in the process of adding support to TensorFlow Lite for more ops. It would be helpful if you could inform us of how this conversion went by opening a github issue at https://github.com/tensorflow/tensorflow/issues/new?template=40-tflite-op-request.md
 and pasting the following:

Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, CAST, CONCATENATION, DIV, EXP, EXPAND_DIMS, FILL, FULLY_CONNECTED, GATHER, LOGISTIC, MUL, NOT_EQUAL, PACK, REDUCE_MAX, RESHAPE, SHAPE, SPLIT, STRIDED_SLICE, SUB, SUM, TANH, TILE, TRANSPOSE, ZEROS_LIKE. Here is a list of operators for which you will need custom implementations: TensorListFromTensor, TensorListReserve, TensorListStack, While.

Process finished with exit code 1

**Comment by haozha111** [comment]
Hi,

Sorry for late reply. The missing ops could be supported by the new MLIR-based TF Lite converter. Can you download the latest tf-nightly and then set:
converter.experimental_new_converter = True

This should resolve your issue.

For detailed examples, please see:
https://groups.google.com/a/tensorflow.org/forum/#!topic/tflite/C7Ag0sUrLYg

Thanks.

**Comment by jiraiyajr98** [comment]
Thank You .Its working now.
