### ISSUE TITLE
Size and CombinedNMS Op support request for tflite

### ISSUE THREAD

**Issue by Brechard** [tensorflow/tensorflow#34693]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- TensorFlow installed from (source or binary): source
- TensorFlow version (or github SHA if from source): 2.0.0

Like in the issue https://github.com/tensorflow/tensorflow/issues/33059 i want to be able to convert my model to TFLite and I have tried changing to: tf.image.non_max_suppression_padded and tf.image.non_max_suppression_with_scores but with both I still get errors

**Provide the text output from tflite_convert**

```
2019-11-28 19:01:40.384887: I tensorflow/core/grappler/devices.cc:55] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2019-11-28 19:01:40.385067: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2019-11-28 19:01:40.408717: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:716] Optimization results for grappler item: graph_to_optimize
2019-11-28 19:01:40.408744: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   function_optimizer: Graph size after: 481 nodes (0), 688 edges (0), time = 4.814ms.
2019-11-28 19:01:40.408760: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   function_optimizer: Graph size after: 481 nodes (0), 688 edges (0), time = 5.216ms.
2019-11-28 19:01:40.408769: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:716] Optimization results for grappler item: Tiny_YOLOv3_inference_non_max_suppression_map_while_body_3226
2019-11-28 19:01:40.408775: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   function_optimizer: function_optimizer did nothing. time = 0.001ms.
2019-11-28 19:01:40.408781: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   function_optimizer: function_optimizer did nothing. time = 0ms.
2019-11-28 19:01:40.408788: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:716] Optimization results for grappler item: Tiny_YOLOv3_inference_non_max_suppression_map_while_cond_3225
2019-11-28 19:01:40.408794: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   function_optimizer: function_optimizer did nothing. time = 0.001ms.
2019-11-28 19:01:40.408802: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   function_optimizer: function_optimizer did nothing. time = 0ms.
2019-11-28 19:01:41.252079: I tensorflow/core/grappler/devices.cc:55] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2019-11-28 19:01:41.252177: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2019-11-28 19:01:41.456787: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:716] Optimization results for grappler item: graph_to_optimize
2019-11-28 19:01:41.456818: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   constant folding: Graph size after: 359 nodes (-58), 584 edges (-58), time = 111.647ms.
2019-11-28 19:01:41.456824: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   constant folding: Graph size after: 359 nodes (0), 584 edges (0), time = 26.561ms.
2019-11-28 19:01:41.456829: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:716] Optimization results for grappler item: Tiny_YOLOv3_inference_non_max_suppression_map_while_body_3226_frozen
2019-11-28 19:01:41.456833: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   constant folding: Graph size after: 52 nodes (0), 55 edges (0), time = 1.265ms.
2019-11-28 19:01:41.456838: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   constant folding: Graph size after: 52 nodes (0), 55 edges (0), time = 1.103ms.
2019-11-28 19:01:41.456842: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:716] Optimization results for grappler item: Tiny_YOLOv3_inference_non_max_suppression_map_while_cond_3225_frozen
2019-11-28 19:01:41.456846: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   constant folding: Graph size after: 14 nodes (0), 8 edges (0), time = 0.617ms.
2019-11-28 19:01:41.456850: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   constant folding: Graph size after: 14 nodes (0), 8 edges (0), time = 0.394ms.
Traceback (most recent call last):
  File "/home/brechard/miniconda3/envs/modeling/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-c548bab089a8>", line 1, in <module>
    tflite_model = converter.convert()
  File "/home/brechard/miniconda3/envs/modeling/lib/python3.7/site-packages/tensorflow_core/lite/python/lite.py", line 446, in convert
    **converter_kwargs)
  File "/home/brechard/miniconda3/envs/modeling/lib/python3.7/site-packages/tensorflow_core/lite/python/convert.py", line 449, in toco_convert_impl
    enable_mlir_converter=enable_mlir_converter)
  File "/home/brechard/miniconda3/envs/modeling/lib/python3.7/site-packages/tensorflow_core/lite/python/convert.py", line 200, in toco_convert_protos
    raise ConverterError("See console for info.\n%s\n%s\n" % (stdout, stderr))
tensorflow.lite.python.convert.ConverterError: See console for info.
2019-11-28 19:01:43.495379: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-11-28 19:01:43.517231: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2712000000 Hz
2019-11-28 19:01:43.518000: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55d1e210d680 executing computations on platform Host. Devices:
2019-11-28 19:01:43.518031: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
2019-11-28 19:01:43.520442: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2019-11-28 19:01:43.520471: E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: UNKNOWN ERROR (303)
2019-11-28 19:01:43.520503: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (nl1lxl-107914): /proc/driver/nvidia/version does not exist
2019-11-28 19:01:43.549801: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Size
2019-11-28 19:01:43.549850: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Size
2019-11-28 19:01:43.550020: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Size
2019-11-28 19:01:43.550039: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Size
2019-11-28 19:01:43.550121: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorListFromTensor
2019-11-28 19:01:43.550139: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 21
2019-11-28 19:01:43.550183: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorListFromTensor
2019-11-28 19:01:43.550193: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 21
2019-11-28 19:01:43.550205: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorListReserve
2019-11-28 19:01:43.550212: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 21
2019-11-28 19:01:43.550219: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorListReserve
2019-11-28 19:01:43.550225: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 21
2019-11-28 19:01:43.550232: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorListReserve
2019-11-28 19:01:43.550240: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 21
2019-11-28 19:01:43.550253: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: While
2019-11-28 19:01:43.550270: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 21
2019-11-28 19:01:43.550275: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 21
2019-11-28 19:01:43.550279: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 21
2019-11-28 19:01:43.550283: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 21
2019-11-28 19:01:43.550287: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 21
2019-11-28 19:01:43.550299: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorListStack
2019-11-28 19:01:43.550308: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorListStack
2019-11-28 19:01:43.550317: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorListStack
2019-11-28 19:01:43.554013: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 226 operators, 430 arrays (0 quantized)
2019-11-28 19:01:43.557143: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 226 operators, 430 arrays (0 quantized)
2019-11-28 19:01:43.648439: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 1: 111 operators, 212 arrays (0 quantized)
2019-11-28 19:01:43.650428: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 2: 111 operators, 212 arrays (0 quantized)
2019-11-28 19:01:43.652457: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Group bidirectional sequence lstm/rnn: 111 operators, 212 arrays (0 quantized)
2019-11-28 19:01:43.653866: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before dequantization graph transformations: 111 operators, 212 arrays (0 quantized)
2019-11-28 19:01:43.655915: I tensorflow/lite/toco/allocate_transient_arrays.cc:345] Total transient array allocated size: 22151168 bytes, theoretical optimal value: 22151168 bytes.
2019-11-28 19:01:43.656807: E tensorflow/lite/toco/toco_tooling.cc:466] We are continually in the process of adding support to TensorFlow Lite for more ops. It would be helpful if you could inform us of how this conversion went by opening a github issue at https://github.com/tensorflow/tensorflow/issues/new?template=40-tflite-op-request.md
 and pasting the following:
Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, CAST, CONCATENATION, CONV_2D, DIV, EXP, EXPAND_DIMS, FILL, LEAKY_RELU, LOGISTIC, MAX_POOL_2D, MUL, PACK, RESHAPE, RESIZE_NEAREST_NEIGHBOR, SHAPE, SPLIT_V, STRIDED_SLICE, SUB. Here is a list of operators for which you will need custom implementations: Size, TensorListFromTensor, TensorListReserve, TensorListStack, While.
Traceback (most recent call last):
  File "/home/brechard/miniconda3/envs/modeling/bin/toco_from_protos", line 10, in <module>
    sys.exit(main())
  File "/home/brechard/miniconda3/envs/modeling/lib/python3.7/site-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 89, in main
    app.run(main=execute, argv=[sys.argv[0]] + unparsed)
  File "/home/brechard/miniconda3/envs/modeling/lib/python3.7/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/brechard/miniconda3/envs/modeling/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/brechard/miniconda3/envs/modeling/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/home/brechard/miniconda3/envs/modeling/lib/python3.7/site-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 52, in execute
    enable_mlir_converter)
Exception: We are continually in the process of adding support to TensorFlow Lite for more ops. It would be helpful if you could inform us of how this conversion went by opening a github issue at https://github.com/tensorflow/tensorflow/issues/new?template=40-tflite-op-request.md
 and pasting the following:
Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, CAST, CONCATENATION, CONV_2D, DIV, EXP, EXPAND_DIMS, FILL, LEAKY_RELU, LOGISTIC, MAX_POOL_2D, MUL, PACK, RESHAPE, RESIZE_NEAREST_NEIGHBOR, SHAPE, SPLIT_V, STRIDED_SLICE, SUB. Here is a list of operators for which you will need custom implementations: Size, TensorListFromTensor, TensorListReserve, TensorListStack, While.
```

If it helps, the function that I am trying to modify can be found in: 
https://github.com/Brechard/computer-vision-tf2/blob/master/src/models/detection/yolov3.py#L240

my modification right now looks like this:

```
    def non_max_suppression(self, outputs):

        bboxes, confidence, class_prob = [], [], []
        for o in outputs:
            bboxes.append(tf.reshape(o[0], (tf.shape(o[0])[0], -1, tf.shape(o[0])[-1])))
            confidence.append(tf.reshape(o[1], (tf.shape(o[1])[0], -1, tf.shape(o[1])[-1])))
            class_prob.append(tf.reshape(o[2], (tf.shape(o[2])[0], -1, tf.shape(o[2])[-1])))

        bbox = tf.concat(bboxes, axis=1)
        confidence = tf.concat(confidence, axis=1)
        class_probs = tf.concat(class_prob, axis=1)

        scores = confidence * class_probs

        # Process for each image of the batch
        def _nms_single_image(args):
            image_bbox, image_scores = args[0], args[1]
            classes = tf.math.argmax(image_scores, axis=1)
            new_img_scores = tf.math.reduce_max(image_scores, axis=1)

            selected_items, selected_scores = tf.image.non_max_suppression_with_scores(
                boxes=tf.reshape(image_bbox, (-1, 4)),
                scores=new_img_scores,
                max_output_size=100,
                iou_threshold=self.iou_threshold,
                score_threshold=self.score_threshold
            )

            return [tf.gather(image_bbox, selected_items), tf.gather(new_img_scores, selected_items),
                    tf.gather(classes, selected_items)]

        bboxes, scores, classes = tf.map_fn(_nms_single_image, elems=[bbox, scores],
                                            dtype=[tf.float32, tf.float32, tf.int64])

        return bboxes, scores, classes
```

**Comment by DanKlarman** [comment]
any update on this?

**Comment by sushreebarsa** [comment]
@Brechard We see that you are using older version of tensorflow .Many bug have been fixed in latest version.  We recommend that you upgrade to latest stable version of tensorflow 2.6.0 and let us know if the issue still persists in newer versions .Thanks!

**Comment by srjoglekar246** [comment]
@Brechard If this is still relevant, can you try using [`non_max_suppression_padded`](https://www.tensorflow.org/api_docs/python/tf/image/non_max_suppression_padded)? It has better support in TFLite, and performs better too. See [this issue](https://github.com/tensorflow/tensorflow/issues/51629#issuecomment-905074446) for some details.
