### ISSUE TITLE
DenseToDenseSetOperation: Could not satisfy explicit device specification '/device:GPU:0' because no supported kernel for GPU devices is available?

### ISSUE THREAD

**Issue by ZeliangSu** [tensorflow/tensorflow#34774]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): conda -c anaconda
- TensorFlow version (use command below): 1.14
- Python version: 3.6
- Bazel version (if compiling from source): None
- GCC/Compiler version (if compiling from source): 7.4
- CUDA/cuDNN version: cuda10.1/cudnn7.6.4
- GPU model and memory: Quadro P5000

**Describe the current behavior**
tf.data.Dataset throws a error since I pass to tf114 from tf113. My following code can reproduce this error. 

**Describe the expected behavior**
I explain my code here. The Dataset takes a list of .h5 file names in string then shuffle this list.  A wrapper written with tf.py_func() will load the .h5 file (I know it's deprecated in TF2, but since it works well in my previous code). It's also my question. Is this bug exists only in TF1 or it does in TF2? Should I move to TF2?

**Code to reproduce the issue**
I wrote a small Seg-Net network to to reproduce the same bug. Everything goes well until I change the output and input of the NN by tf.data.

```
import tensorflow as tf
import numpy as np
from tqdm import tqdm
from tensorflow.python.tools.optimize_for_inference_lib import optimize_for_inference
from tensorflow.python.framework import dtypes
import os

def up_2by2_ind(input_layer, ind, name=''):
    with tf.name_scope(name):
        in_shape = input_layer.get_shape().as_list()
        out_shape = [tf.cast(tf.shape(input_layer), dtype=tf.int64)[0], in_shape[1] * 2, in_shape[2] * 2, in_shape[3]]

        # prepare
        _pool = tf.reshape(input_layer, [-1])
        _range = tf.reshape(tf.range(out_shape[0], dtype=ind.dtype), [out_shape[0], 1, 1, 1])
        tmp = tf.ones_like(ind) * _range
        tmp = tf.reshape(tmp, [-1, 1])
        _ind = tf.reshape(ind, [-1, 1])
        _ind = tf.concat([tmp, _ind], 1)

        # scatter
        unpool = tf.scatter_nd(_ind, _pool, [out_shape[0], out_shape[1] * out_shape[2] * out_shape[3]])

        # reshape
        unpool = tf.reshape(unpool, out_shape)
        return unpool

###################### input pipeline
def wrapper(a, b):
    return tf.py_func(
        wrawrapper,
        [a, b],
        [tf.float32, tf.float32],
    )

def wrawrapper(a, b):
    return np.ones((1, 50, 50, 1), dtype=np.float32), np.ones((1, 50, 50, 1), dtype=np.float32)

a_ph = tf.placeholder(tf.string, shape=[None], name='a_ph')
b_ph = tf.placeholder(tf.int32, shape=[None], name='b_ph')

batch = tf.data.Dataset.from_tensor_slices((a_ph, b_ph))
batch = batch.shuffle(tf.cast(tf.shape(a_ph)[0], tf.int64))
batch = batch.map(wrapper).prefetch(10).repeat()
it = tf.data.Iterator.from_structure(batch.output_types, batch.output_shapes)
iter_init_op = it.make_initializer(batch, name='iter_init_op')
X_it, y_it = it.get_next()

dropout = tf.placeholder(tf.float32, [], name='dropout')
BN_phase = tf.placeholder(tf.bool, [], name='BN_phase')
save_summary_step = 20
save_model_step = 100

##################### train graph on gpu1
with tf.device('/device:GPU:0'):
    with tf.name_scope('model'):
        with tf.name_scope('conv'):
            with tf.variable_scope('conv', reuse=False):
                w1 = tf.get_variable('w', shape=[3, 3, 1, 1], initializer=tf.initializers.glorot_normal())
            out1 = tf.nn.conv2d(X_it, w1, strides=[1, 1, 1, 1], padding='SAME', name='conv')
            with tf.variable_scope('conv', reuse=False):
                out1 = tf.layers.batch_normalization(out1, training=BN_phase, name='batch_norm')
            out1 = tf.nn.relu(out1, 'relu')
            out1, ind1 = tf.nn.max_pool_with_argmax(out1, ksize=[1, 2, 2, 1], strides=[1, 2, 2, 1], padding='SAME', name='maxpool')
        with tf.name_scope('dnn'):
            flat = tf.reshape(out1, [1, 625])
            with tf.variable_scope('dnn2', reuse=False):
                w2 = tf.get_variable('w2', shape=[625, 625], initializer=tf.initializers.glorot_normal())
            dnn_out = tf.matmul(flat, w2)
            dnn_out = tf.nn.dropout(dnn_out, keep_prob=dropout, name='do')
            dnn_out = tf.nn.relu(dnn_out, name='relu')
            dnn_out = tf.reshape(dnn_out, shape=[1, 25, 25, 1], name='dnn')

        with tf.name_scope('deconv'):
            out1 = up_2by2_ind(dnn_out, ind1, 'up1')
            with tf.variable_scope('deconv', reuse=False):
                w3 = tf.get_variable('w', shape=[3, 3, 1, 1], initializer=tf.initializers.glorot_normal())
            out1 = tf.nn.conv2d(out1, w3, strides=[1, 1, 1, 1], padding='SAME', name='deconv')
            with tf.variable_scope('deconv', reuse=False):
                out1 = tf.layers.batch_normalization(out1, training=BN_phase, name='batch_norm')
            logits = tf.nn.relu(out1, 'logits')

        #todo: here with tabulation with tf.name_scope('operation'):
    with tf.name_scope('operation'):
        update_ops = tf.get_collection(tf.GraphKeys.UPDATE_OPS)
        with tf.control_dependencies(update_ops):
            mse = tf.losses.mean_squared_error(labels=y_it, predictions=logits)
        opt = tf.train.AdamOptimizer(learning_rate=0.0001, name='Adam')

        grads = opt.compute_gradients(mse)
        train_op = opt.apply_gradients(grads, name='apply_grad')

with tf.name_scope('train_metrics'):
    acc_val_op, acc_update_op = tf.metrics.accuracy(labels=y_it, predictions=logits)
    summ_acc = tf.summary.merge([tf.summary.scalar('accuracy', acc_val_op)])
    grad_sum = tf.summary.merge([tf.summary.histogram('{}/grad'.format(g[1].name), g[0]) for g in grads])

with tf.name_scope('train_summary'):
    merged = tf.summary.merge([summ_acc, grad_sum, tf.summary.histogram("weights", w1)])

###################### test graph on gpu2
with tf.device('/device:GPU:1'):
    with tf.name_scope('model'):
        with tf.name_scope('conv'):
            with tf.variable_scope('conv', reuse=True):
                w1 = tf.get_variable('w', shape=[3, 3, 1, 1], initializer=tf.initializers.glorot_normal())
            out1 = tf.nn.conv2d(X_it, w1, strides=[1, 1, 1, 1], padding='SAME', name='conv')
            with tf.variable_scope('conv', reuse=True):
                out1 = tf.layers.batch_normalization(out1, training=BN_phase, name='batch_norm')
            out1 = tf.nn.relu(out1, 'relu')
            out1, ind1 = tf.nn.max_pool_with_argmax(out1, ksize=[1, 2, 2, 1], strides=[1, 2, 2, 1], padding='SAME', name='maxpool')
        with tf.name_scope('dnn'):
            flat = tf.reshape(out1, [1, 625])
            with tf.variable_scope('dnn2', reuse=True):
                w2 = tf.get_variable('w2', shape=[625, 625], initializer=tf.initializers.glorot_normal())
            dnn_out = tf.matmul(flat, w2)
            dnn_out = tf.nn.dropout(dnn_out, keep_prob=dropout, name='do')
            dnn_out = tf.nn.relu(dnn_out, name='relu')
            dnn_out = tf.reshape(dnn_out, shape=[1, 25, 25, 1], name='dnn')

        with tf.name_scope('deconv'):
            out1 = up_2by2_ind(dnn_out, ind1, 'up1')
            with tf.variable_scope('deconv', reuse=True):
                w3 = tf.get_variable('w', shape=[3, 3, 1, 1], initializer=tf.initializers.glorot_normal())
            out1 = tf.nn.conv2d(out1, w3, strides=[1, 1, 1, 1], padding='SAME', name='deconv')
            with tf.variable_scope('conv', reuse=True):
                out1 = tf.layers.batch_normalization(out1, training=BN_phase, name='batch_norm')
            logits = tf.nn.relu(out1, 'logits')


with tf.name_scope('test_metrics'):
    acc_val_op2, acc_update_op2 = tf.metrics.accuracy(labels=y_it, predictions=logits)
    summ_acc2 = tf.summary.merge([tf.summary.scalar('accuracy', acc_val_op2)])

with tf.name_scope('test_summary'):
    merged2 = tf.summary.merge([summ_acc2, tf.summary.histogram("weights", w1), tf.summary.histogram("weights", w2)])


##############################################
with tf.Session() as sess:
    sess.run([tf.global_variables_initializer(), tf.local_variables_initializer(), iter_init_op],
             feed_dict={a_ph: ['a'], b_ph: [10]})
    model_saver = tf.train.Saver(max_to_keep=100000)
    train_writer = tf.summary.FileWriter('./dummy/gpus/train/', sess.graph)
    test_writer = tf.summary.FileWriter('./dummy/gpus/test/', sess.graph)
    for i in tqdm(range(1000)):
        if i % save_summary_step == 0:
            _, rlt, summary, _ = sess.run([train_op, out1, merged, acc_update_op], feed_dict={
                dropout: 1,
                BN_phase: True,
            }
                                          )
            # print('train:', rlt)
            train_writer.add_summary(summary, global_step=i)
        else:
            _, rlt = sess.run([train_op, out1], feed_dict={dropout: 1, BN_phase: True})
            # print('train:', rlt)
        if i % save_model_step == 0:
            model_saver.save(sess, './dummy/ckpt/step{}'.format(i))
            if i != 0:
                for j in tqdm(range(5)):
                    rlt, summary = sess.run([logits, merged2], feed_dict={
                        dropout: 1,
                        BN_phase: False,
                    }
                                            )
                    # print('test:', rlt)
                    test_writer.add_summary(summary, global_step=j)
```

**Other info / logs**
```
Traceback (most recent call last):
  File "/home/anaconda3/envs/tf114/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/home/anaconda3/envs/tf114/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1339, in _run_fn
    self._extend_graph()
  File "/home/anaconda3/envs/tf114/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1374, in _extend_graph
    tf_session.ExtendSession(self._session)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device for operation operation/mean_squared_error/assert_broadcastable/is_valid_shape/has_valid_nonscalar_shape/has_invalid_dims/DenseToDenseSetOperation: Could not satisfy explicit device specification '/device:GPU:0' because no supported kernel for GPU devices is available.
Colocation Debug Info:
Colocation group had the following types and supported devices: 
Root Member(assigned_device_name_index_=-1 requested_device_name_='/device:GPU:0' assigned_device_name_='' resource_device_name_='' supported_device_types_=[CPU] possible_devices_=[]
DenseToDenseSetOperation: CPU 

Colocation members, user-requested devices, and framework assigned devices, if any:
  operation/mean_squared_error/assert_broadcastable/is_valid_shape/has_valid_nonscalar_shape/has_invalid_dims/DenseToDenseSetOperation (DenseToDenseSetOperation) /device:GPU:0

Op: DenseToDenseSetOperation
Node attrs: T=DT_INT32, validate_indices=true, set_operation="a-b"
Registered kernels:
  device='CPU'; T in [DT_STRING]
  device='CPU'; T in [DT_UINT16]
  device='CPU'; T in [DT_UINT8]
  device='CPU'; T in [DT_INT64]
  device='CPU'; T in [DT_INT32]
  device='CPU'; T in [DT_INT16]
  device='CPU'; T in [DT_INT8]

	 [[{{node operation/mean_squared_error/assert_broadcastable/is_valid_shape/has_valid_nonscalar_shape/has_invalid_dims/DenseToDenseSetOperation}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/snippet.py", line 1930, in <module>
    feed_dict={a_ph: ['a'], b_ph: [10]})
  File "/home/anaconda3/envs/tf114/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/home/anaconda3/envs/tf114/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/anaconda3/envs/tf114/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/home/anaconda3/envs/tf114/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device for operation operation/mean_squared_error/assert_broadcastable/is_valid_shape/has_valid_nonscalar_shape/has_invalid_dims/DenseToDenseSetOperation: Could not satisfy explicit device specification '/device:GPU:0' because no supported kernel for GPU devices is available.
Colocation Debug Info:
Colocation group had the following types and supported devices: 
Root Member(assigned_device_name_index_=-1 requested_device_name_='/device:GPU:0' assigned_device_name_='' resource_device_name_='' supported_device_types_=[CPU] possible_devices_=[]
DenseToDenseSetOperation: CPU 

Colocation members, user-requested devices, and framework assigned devices, if any:
  operation/mean_squared_error/assert_broadcastable/is_valid_shape/has_valid_nonscalar_shape/has_invalid_dims/DenseToDenseSetOperation (DenseToDenseSetOperation) /device:GPU:0

Op: DenseToDenseSetOperation
Node attrs: T=DT_INT32, validate_indices=true, set_operation="a-b"
Registered kernels:
  device='CPU'; T in [DT_STRING]
  device='CPU'; T in [DT_UINT16]
  device='CPU'; T in [DT_UINT8]
  device='CPU'; T in [DT_INT64]
  device='CPU'; T in [DT_INT32]
  device='CPU'; T in [DT_INT16]
  device='CPU'; T in [DT_INT8]

	 [[node operation/mean_squared_error/assert_broadcastable/is_valid_shape/has_valid_nonscalar_shape/has_invalid_dims/DenseToDenseSetOperation (defined at media/snippet.py:1875) ]]

Original stack trace for 'operation/mean_squared_error/assert_broadcastable/is_valid_shape/has_valid_nonscalar_shape/has_invalid_dims/DenseToDenseSetOperation':
  File "media/snippet.py", line 1875, in <module>
    mse = tf.losses.mean_squared_error(labels=y_it, predictions=logits)
  File "home/anaconda3/envs/tf114/lib/python3.6/site-packages/tensorflow/python/ops/losses/losses_impl.py", line 646, in mean_squared_error
    losses, weights, scope, loss_collection, reduction=reduction)
  File "home/anaconda3/envs/tf114/lib/python3.6/site-packages/tensorflow/python/ops/losses/losses_impl.py", line 181, in compute_weighted_loss
    weights_broadcast_ops.assert_broadcastable(weights, losses),)):
  File "home/anaconda3/envs/tf114/lib/python3.6/site-packages/tensorflow/python/ops/weights_broadcast_ops.py", line 132, in assert_broadcastable
    name="is_valid_shape")
  File "home/anaconda3/envs/tf114/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "home/anaconda3/envs/tf114/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 1988, in cond
    orig_res_f, res_f = context_f.BuildCondBranch(false_fn)
  File "home/anaconda3/envs/tf114/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 1814, in BuildCondBranch
    original_result = fn()
  File "home/anaconda3/envs/tf114/lib/python3.6/site-packages/tensorflow/python/ops/weights_broadcast_ops.py", line 131, in <lambda>
    weights_rank, weights_shape, values_rank, values_shape),
  File "home/anaconda3/envs/tf114/lib/python3.6/site-packages/tensorflow/python/ops/weights_broadcast_ops.py", line 57, in _has_valid_nonscalar_shape
    name=scope)
  File "home/anaconda3/envs/tf114/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "home/anaconda3/envs/tf114/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 1977, in cond
    orig_res_t, res_t = context_t.BuildCondBranch(true_fn)
  File "home/anaconda3/envs/tf114/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 1814, in BuildCondBranch
    original_result = fn()
  File "home/anaconda3/envs/tf114/lib/python3.6/site-packages/tensorflow/python/ops/weights_broadcast_ops.py", line 55, in <lambda>
    lambda: _has_valid_dims(weights_shape, values_shape),
  File "home/anaconda3/envs/tf114/lib/python3.6/site-packages/tensorflow/python/ops/weights_broadcast_ops.py", line 40, in _has_valid_dims
    invalid_dims = sets.set_difference(weights_shape_2d, valid_dims)
  File "home/anaconda3/envs/tf114/lib/python3.6/site-packages/tensorflow/python/ops/sets_impl.py", line 273, in set_difference
    return _set_operation(a, b, "a-b" if aminusb else "b-a", validate_indices)
  File "home/anaconda3/envs/tf114/lib/python3.6/site-packages/tensorflow/python/ops/sets_impl.py", line 132, in _set_operation
    a, b, set_operation, validate_indices)
  File "home/anaconda3/envs/tf114/lib/python3.6/site-packages/tensorflow/python/ops/gen_set_ops.py", line 98, in dense_to_dense_set_operation
    name=name)
  File "home/anaconda3/envs/tf114/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "home/anaconda3/envs/tf114/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "home/anaconda3/envs/tf114/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3616, in create_op
    op_def=op_def)
  File "home/anaconda3/envs/tf114/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()

```

**Comment by ZeliangSu** [comment]
Found the solution, I will close the issue. One shouldn't put `tf.losses.MSE(); tf.summary.merge()` inside GPU `tf.device('/device:GPU:X')` since means, update ops, or variables are in the RAM and operated by CPU. In contrast, gradient, loss and model are in GPU.
