### ISSUE TITLE
GRUCell is not compatible with its own initial state

### ISSUE THREAD

**Issue by guillaumekln** [tensorflow/tensorflow#34789]
**System information**
- Have I written custom code: Yes
- OS Platform and Distribution: Ubuntu 16.04
- TensorFlow installed from: binary
- TensorFlow version: 2.1.0rc0
- Python version: 3.5.2

**Describe the current behavior**

The initial state returned by `tf.keras.layers.GRUCell.get_initial_state()` can not be passed to the first cell call without error. It raises an `InvalidArgumentError` error.

**Describe the expected behavior**

RNN cells should accept their own initial states.

**Code to reproduce the issue**

```python
import tensorflow as tf
batch_size = 4
cell = tf.keras.layers.GRUCell(20)
initial_state = cell.get_initial_state(batch_size=batch_size, dtype=tf.float32)
output, state = cell(tf.random.uniform([batch_size, 10]), initial_state)
```

**Other info / logs**

```
Traceback (most recent call last):
  File "test/gru_incompat.py", line 5, in <module>
    output, state = cell(tf.random.uniform([batch_size, 10]), initial_state)
  File "/lib/python3.5/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 822, in __call__
    outputs = self.call(cast_inputs, *args, **kwargs)
  File "/lib/python3.5/site-packages/tensorflow_core/python/keras/layers/recurrent.py", line 1846, in call
    matrix_inner = K.dot(h_tm1, self.recurrent_kernel)
  File "/lib/python3.5/site-packages/tensorflow_core/python/keras/backend.py", line 1678, in dot
    out = math_ops.matmul(x, y)
  File "/lib/python3.5/site-packages/tensorflow_core/python/util/dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "/lib/python3.5/site-packages/tensorflow_core/python/ops/math_ops.py", line 2797, in matmul
    a, b, transpose_a=transpose_a, transpose_b=transpose_b, name=name)
  File "/lib/python3.5/site-packages/tensorflow_core/python/ops/gen_math_ops.py", line 5631, in mat_mul
    _ops.raise_from_not_ok_status(e, name)
  File "/lib/python3.5/site-packages/tensorflow_core/python/framework/ops.py", line 6598, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: In[0] is not a matrix. Instead it has shape [20] [Op:MatMul] name: gru_cell/MatMul/
```

**Comment by PanXiebit** [comment]
@guillaumekln hi, I met this error too, and I think here is a bug. I changed two line of codes, everything is ok.

https://github.com/tensorflow/tensorflow/blob/4235c011cf48daf64953895e844dba7b72b3edc0/tensorflow/python/keras/layers/recurrent.py#L1773
should be `h_tm1 = states  # previous memory`

https://github.com/tensorflow/tensorflow/blob/4235c011cf48daf64953895e844dba7b72b3edc0/tensorflow/python/keras/layers/recurrent.py#L1871
should be `return h, h`

**Comment by qlzh727** [comment]
Sorry for the breakage, will fix it very soon.
