### ISSUE TITLE
AttributeError: 'ImageDataGenerator' object has no attribute 'shape'

### ISSUE THREAD

**Issue by PanCakeConnaisseur** [tensorflow/tensorflow#34795]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): KDE neon, based on Ubuntu 18.04 LTS
- TensorFlow installed from (source or binary): via Anaconda 3
- TensorFlow version (use command below): 2.0.0 
- Python version: 3.7.5

**Anaconda environment**
Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_tflow_select             2.3.0                       mkl  
absl-py                   0.8.1                    py37_0  
astor                     0.8.0                    py37_0  
blas                      1.0                         mkl  
c-ares                    1.15.0            h7b6447c_1001  
ca-certificates           2019.10.16                    0  
certifi                   2019.9.11                py37_0  
gast                      0.2.2                    py37_0  
google-pasta              0.1.8                      py_0  
grpcio                    1.16.1           py37hf8bcb03_1  
h5py                      2.9.0            py37h7918eee_0  
hdf5                      1.10.4               hb1b8bf9_0  
intel-openmp              2019.4                      243  
keras-applications        1.0.8                      py_0  
keras-preprocessing       1.1.0                      py_1  
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libprotobuf               3.10.1               hd408876_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
markdown                  3.1.1                    py37_0  
mkl                       2019.4                      243  
mkl-service               2.3.0            py37he904b0f_0  
mkl_fft                   1.0.15           py37ha843d7b_0  
mkl_random                1.1.0            py37hd6b4f25_0  
ncurses                   6.1                  he6710b0_1  
numpy                     1.17.3           py37hd14ec0e_0  
numpy-base                1.17.3           py37hde5b4d6_0  
openssl                   1.1.1d               h7b6447c_3  
opt_einsum                3.1.0                      py_0  
pip                       19.3.1                   py37_0  
protobuf                  3.10.1           py37he6710b0_0  
python                    3.7.5                h0371630_0  
readline                  7.0                  h7b6447c_5  
scipy                     1.3.1            py37h7c811a0_0  
setuptools                41.6.0                   py37_0  
six                       1.13.0                   py37_0  
sqlite                    3.30.1               h7b6447c_0  
tensorboard               2.0.0              pyhb230dea_0  
tensorflow                2.0.0           mkl_py37h66b46cc_0  
tensorflow-base           2.0.0           mkl_py37h9204916_0  
tensorflow-estimator      2.0.0              pyh2649769_0  
tensorflow-mkl            2.0.0                h4fcabd2_0  
termcolor                 1.1.0                    py37_1  
tk                        8.6.8                hbc83047_0  
webencodings              0.5.1                    py37_1  
werkzeug                  0.16.0                     py_0  
wheel                     0.33.6                   py37_0  
wrapt                     1.11.2           py37h7b6447c_0  
xz                        5.2.4                h14c3975_4  
zlib                      1.2.11               h7b6447c_3

**Describe the current behavior**
Using only Keras methods I get the error:
> AttributeError: 'ImageDataGenerator' object has no attribute 'shape'

This seems to indicate that Keras code is expecting other data scructures in an object that it created itself.

**Describe the expected behavior**

No error message.

**Code to reproduce the issue**
```python
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import MaxPooling2D, Conv2D, Dense
from tensorflow.keras.preprocessing.image import ImageDataGenerator

model = Sequential([
    Conv2D(filters=32,
           input_shape=(10,10,3),
           kernel_size=(4,4),
           activation='relu'),

    MaxPooling2D(pool_size=(2, 2)),


    Dense(5),
])

model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

imageGenerator = ImageDataGenerator()

imageGenerator.flow_from_directory(
    directory='training data',
    target_size=(10, 10),
    batch_size=32,
    class_mode='categorical',
)

model.fit_generator(imageGenerator, steps_per_epoch=55)
```

The folder *training data* contains three folders each containing JPG images for the respective class.

**Output**
```
/home/user/anaconda3/envs/project/bin/python3.7 /home/user/.PyCharm2019.3/config/scratches/scratch_2.py
2019-12-03 14:11:23.807238: I tensorflow/core/platform/cpu_feature_guard.cc:145] This TensorFlow binary is optimized with Intel(R) MKL-DNN to use the following CPU instructions in performance critical operations:  SSE4.1 SSE4.2 AVX
To enable them in non-MKL-DNN operations, rebuild TensorFlow with the appropriate compiler flags.
2019-12-03 14:11:23.834757: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2593900000 Hz
2019-12-03 14:11:23.835094: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x558c62e752d0 executing computations on platform Host. Devices:
2019-12-03 14:11:23.835114: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
2019-12-03 14:11:23.835399: I tensorflow/core/common_runtime/process_util.cc:115] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
Found 6126 images belonging to 3 classes.
Traceback (most recent call last):
  File "/home/user/.PyCharm2019.3/config/scratches/scratch_2.py", line 31, in <module>
    model.fit_generator(imageGenerator, steps_per_epoch=55)
  File "/home/user/anaconda3/envs/project/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 1297, in fit_generator
    steps_name='steps_per_epoch')
  File "/home/user/anaconda3/envs/project/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_generator.py", line 144, in model_iteration
    shuffle=shuffle)
  File "/home/user/anaconda3/envs/project/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_generator.py", line 477, in convert_to_generator_like
    num_samples = int(nest.flatten(data)[0].shape[0])
AttributeError: 'ImageDataGenerator' object has no attribute 'shape'

Process finished with exit code 1
```

**Comment by PanCakeConnaisseur** [comment]
PEBCAK

```
imageGenerator.flow_from_directory.....
```
should be generator = imageGenerator.flow_from_directory.....

and `generator` must be the paramteter for `fit_generator()`
