### ISSUE TITLE
Missing default floating point values in single_image_random_dot_stereograms_ops.cc

### ISSUE THREAD

**Issue by pawel-ziecina** [tensorflow/tensorflow#34828]
- OS Platform and Distribution: Ubuntu 18.04
- TensorFlow version: 1.12+ gpu installed with pip
- CUDA/cuDNN version: 9.0/7.0
- GPU model and memory: GTX 1060 6GB / NVIDIA-SMI 390.116
- Exact command to reproduce: use code below in python3 script
- Mobile device: N/A

Code to reproduce:

```python
import carla
import tensorflow as tf
vol = tf.contrib.util.make_tensor_proto([256, 256])
```

Run with (carla egg package attached):

``` shell
PYTHONPATH=carla-0.9.6-py3.5-linux-x86_64.egg:$PYTHONPATH  python ./above_script.py
```

Observe:

```
Traceback (most recent call last):
  File "above_script.py", line 3, in <module>
    vol = tf.contrib.util.make_tensor_proto([256, 256])
  File "/home/pawel.ziecina/.virtualenvs/myvenv/lib/python3.6/site-packages/tensorflow/python/util/lazy_loader.py", line 53, in __getattr__
    module = self._load()
  File "/home/pawel.ziecina/.virtualenvs/myvenv/lib/python3.6/site-packages/tensorflow/python/util/lazy_loader.py", line 42, in _load
    module = importlib.import_module(self.__name__)
  File "/home/pawel.ziecina/.virtualenvs/myvenv/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/pawel.ziecina/.virtualenvs/myvenv/lib/python3.6/site-packages/tensorflow/contrib/__init__.py", line 57, in <module>
    from tensorflow.contrib import image
  File "/home/pawel.ziecina/.virtualenvs/myvenv/lib/python3.6/site-packages/tensorflow/contrib/image/__init__.py", line 70, in <module>
    from tensorflow.contrib.image.python.ops.single_image_random_dot_stereograms import single_image_random_dot_stereograms
  File "/home/pawel.ziecina/.virtualenvs/myvenv/lib/python3.6/site-packages/tensorflow/contrib/image/python/ops/single_image_random_dot_stereograms.py", line 27, in <module>
    "_single_image_random_dot_stereograms.so"))
  File "/home/pawel.ziecina/.virtualenvs/myvenv/lib/python3.6/site-packages/tensorflow/contrib/util/loader.py", line 56, in load_op_library
    ret = load_library.load_op_library(path)
  File "/home/pawel.ziecina/.virtualenvs/myvenv/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 77, in load_op_library
    exec(wrappers, module.__dict__)
  File "<string>", line 28
    def single_image_random_dot_stereograms(depth_values, hidden_surface_removal=True, convergence_dots_size=8, dots_per_inch=72, eye_separation=, mu=, normalize=True, normalize_max=, normalize_min=, border_level=, number_colors=256, output_image_shape=[1024, 768, 1], output_data_window=[1022, 757], name=None):
                                                                                                                                                 ^
SyntaxError: invalid syntax


```

Related with #21164 - there was bug with wrong decimal separator, here we observe missing default value for float type attrributes in generated python wrapper. 

Other observations:
1. Issue doesn't occur when switch order of imports i.e. import carla after tensorflow import
1. Issue doesn't occur on tf 1.11 - probably it was introduced with #22044

[carla_egg.tar.gz](https://github.com/tensorflow/tensorflow/files/3922153/carla_egg.tar.gz)

**Comment by yongtang** [comment]
There issue seems to be that, when `import carla` is presented, I/O operation fails for `std::ostringstream s`.

Created a PR #34847 so that in case of failure, fallback to normal conversion.
