### ISSUE TITLE
Mask-RCNN fails in TOCO Conversion: "Exception: Merge of two inputs that differ on more than one predicate"

### ISSUE THREAD

**Issue by parvizp** [tensorflow/tensorflow#34845]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (or github SHA if from source): 2.1.0-dev20191203

On the TF-Lite mailing list it was [announced](https://groups.google.com/a/tensorflow.org/forum/?utm_medium=email&utm_source=footer#!msg/tflite/C7Ag0sUrLYg/tHYfDHmNAAAJ) that the new MLIR-based TOCO converter:
```Enables conversion of new classes of models, including Mask R-CNN, ...```
However I was unable to get a version of Mask-RCNN converted to TF-Lite. It would be really helpful if additional notebooks like the [LSTM example](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/examples/experimental_new_converter/keras_lstm.ipynb) could be added. I attempted to create one below for others.

**Command used to run the converter or code if you’re using the Python API**
See the notebook modeled after the LSTM example: https://github.com/parvizp/tensorflow/blob/master/tensorflow/lite/examples/experimental_new_converter/maskrcnn.ipynb

**The output from the converter invocation**
```
ConverterError: See console for info.
2019-12-04 18:11:17.034818: W tensorflow/compiler/mlir/lite/python/graphdef_to_tfl_flatbuffer.cc:106] Ignored output_format.
2019-12-04 18:11:17.034844: W tensorflow/compiler/mlir/lite/python/graphdef_to_tfl_flatbuffer.cc:112] Ignored drop_control_dependency.
Traceback (most recent call last):
  File "/n_mounts/scr_ncore/parvizp/Git/tensorflow_public/tensorflow/lite/examples/experimental_new_converter/env/bin/toco_from_protos", line 8, in <module>
    sys.exit(main())
  File "/n_mounts/scr_ncore/parvizp/Git/tensorflow_public/tensorflow/lite/examples/experimental_new_converter/env/lib/python3.7/site-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 93, in main
    app.run(main=execute, argv=[sys.argv[0]] + unparsed)
  File "/n_mounts/scr_ncore/parvizp/Git/tensorflow_public/tensorflow/lite/examples/experimental_new_converter/env/lib/python3.7/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/n_mounts/scr_ncore/parvizp/Git/tensorflow_public/tensorflow/lite/examples/experimental_new_converter/env/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/n_mounts/scr_ncore/parvizp/Git/tensorflow_public/tensorflow/lite/examples/experimental_new_converter/env/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/n_mounts/scr_ncore/parvizp/Git/tensorflow_public/tensorflow/lite/examples/experimental_new_converter/env/lib/python3.7/site-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 56, in execute
    enable_mlir_converter)
Exception: Merge of two inputs that differ on more than one predicate {s(BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/Greater:0,else), s(BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/cond/cond/pred_id:0,then)} and {s(BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/Greater:0,else), s(BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/cond/cond/pred_id:0,else), s(BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/cond/Greater:0,else)}
	for node {{node BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/cond/cond/Merge}}
```

**Also, please include a link to the saved model or GraphDef**

http://download.tensorflow.org/models/object_detection/mask_rcnn_resnet50_atrous_coco_2018_01_28.tar.gz

**Comment by daverim** [comment]
Hi, @miaout17, could you take a look at this, it seems to be having issues converting the while loop.

**Comment by parvizp** [comment]
Is Mask-RCNN not yet supported on TF-Lite or perhaps the mailing list announcement was referencing another implementation?

**Comment by srjoglekar246** [comment]
Could you modify `pipeline.config` as follows:
Before:
```
faster_rcnn {
    number_of_stages: 3
    …
    second_stage_post_processing {
      batch_non_max_suppression {
        score_threshold: 0.300000011921
        iou_threshold: 0.600000023842
        max_detections_per_class: 100
        max_total_detections: 100
      }
      score_converter: SOFTMAX
    }
```

After:
```faster_rcnn {
    number_of_stages: 2
    …
    second_stage_post_processing {
      batch_non_max_suppression {
        score_threshold: 0.300000011921
        iou_threshold: 0.600000023842
        max_detections_per_class: 10
        max_total_detections: 10
        use_static_shapes: true
        use_class_agnostic_nms: true
      }
      score_converter: SOFTMAX
    }
```

This helps prune out a lot of dynamicism from the graph. You could play with `max_total_detections` & the thresholds to see what works for you.

Then we need to export only the inference part of the graph, since the original one contains training components. Run `tensorflow_models/object_detection/export_inference_graph.py` with the following arguments:
```
--input_type image_tensor --input_shape 1,800,1365,3 --pipeline_config_path /.../mask_rcnn_inception_v2_coco_2018_01_28/pipeline.config --trained_checkpoint_prefix .../model/mask_rcnn_inception_v2_coco_2018_01_28/model.ckpt --output_directory /.../mask_rcnn_inception_v2_coco_2018_01_28/exported
```

(I have mentioned a different model, please modify)

Then convert the resulting graph to TFLite using the converter. Make sure to enable 'Select TF ops' & set input tensor to `Preprocessor/sub` & outputs to `detection_boxes,detection_classes,detection_scores,num_detections`.

NOTE: The latency is very high, since the model is not made for mobile use-cases.

**Comment by parvizp** [comment]
@srjoglekar246 Thanks for looking at this -- I suspect your pipeline changes will reduce the graph complexity which why my main challenge.

What version of TF should I use? I tried to use the latest to get the MLIR-based TOCO but `master` of `models` fails, seems to expect `TF 1.X` in https://github.com/tensorflow/models/blob/master/research/object_detection/exporter.py#L20:
```
/n_mounts/scr_ncore/parvizp/Git/tensorflow_public/tensorflow/lite/examples/experimental_new_converter/models/research/object_detection/exporter.py in <module>
     18 import tempfile
     19 import tensorflow as tf
---> 20 from tensorflow.contrib.quantize.python import graph_matcher
     21 from tensorflow.core.protobuf import saver_pb2
     22 from tensorflow.python.tools import freeze_graph  # pylint: disable=g-direct-tensorflow-import

ModuleNotFoundError: No module named 'tensorflow.contrib'
```

**Comment by srjoglekar246** [comment]
I think that makes sense. Sorry about the weirdness of this :-/

**Comment by parvizp** [comment]
For anyone else trying to reproduce, I've successfully used `tensorflow==1.15` and @srjoglekar246 's tips to generate a relatively clean inference graph.
Then using a newer TF/TOCO (`2.2.0-dev20200122`)
I was able to:
```
converter = tf.lite.TFLiteConverter.from_saved_model('mask_rcnn_resnet50_atrous_coco_2018_01_28/exported_640_640/saved_model/')

# https://www.tensorflow.org/lite/guide/ops_select
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,
                                       tf.lite.OpsSet.SELECT_TF_OPS]
converter.experimental_new_converter = True # Must be true for Mask-RCNN.
tflite_model = converter.convert()

# Write TF-Lite to disk.
tflite_models_dir = pathlib.Path(os.path.join(os.getcwd(), "tflite_models"))
tflite_models_dir.mkdir(exist_ok=True, parents=True)
tflite_model_file = tflite_models_dir/"mask_rcnn_resnet50_atrous_coco_2018_01_28.exported_640_640.tflite"
tflite_model_file.write_bytes(tflite_model)
```

**Comment by srjoglekar246** [comment]
Thanks for confirming!

**Comment by lidaweironaldo** [comment]
@srjoglekar246 @parvizp Why does the output array only include: detection_boxes,detection_classes,detection_scores,num_detections? Is the mask head excluded?

**Comment by srjoglekar246** [comment]
@lidaweironaldo 
Yup. Sadly the model becomes too large to be any good, if you also include the mask head (if you are runningn on mobile). If you are running on a device like Raspberry Pi, things might be different. Feel free to try with `number_of_stages: 3` in `pipeline.config` (see my long comment above).

If that doesnt work well for you, Deeplabv3 is also a good option for segmentation cases.

**Comment by pglushkov** [comment]
Hi all! Tried to reproduce everything reported by @parvizp - all works fine regarding the conversion. Then when trying to run the inference with resulting TF-Lite model in Python - all crashes at attempt to create the tf.lite.Interpreter object: 

Traceback (most recent call last):
  File "convert_resnet_to_tflite.py", line 37, in <module>
    interpreter = tf.lite.Interpreter(model_path=tflite_model_file)
  File "/home/petglu01/anaconda3/envs/tst/lib/python3.7/site-packages/tensorflow_core/lite/python/interpreter.py", line 204, in __init__
    model_path, self._custom_op_registerers))
NotImplementedError: Wrong number or type of arguments for overloaded function 'InterpreterWrapper_CreateWrapperCPPFromFile'.
  Possible C/C++ prototypes are:
    tflite::interpreter_wrapper::InterpreterWrapper::CreateWrapperCPPFromFile(char const *,std::vector< std::string > const &,std::string *)
    tflite::interpreter_wrapper::InterpreterWrapper::tflite_interpreter_wrapper_InterpreterWrapper_CreateWrapperCPPFromFile__SWIG_1(char const *,PyObject *)

Tensorflow version :  tf-nightly  2.2.0.dev20200204

At page with information about 'selected TF ops' ( https://www.tensorflow.org/lite/guide/ops_select ) it is said, that TF-Lite interpreter with selected-ops support for Python is under active development. Is that related to the errors that I see?

Thanks!

**Comment by srjoglekar246** [comment]
I think so, yes :-(. Is your deployment environment Python-only? AFAIK things seem to work on C++ (which is what I usually use)

**Comment by pglushkov** [comment]
Hello @srjoglekar246 !
Yes, my use cases depend on the Python back-end. Hopefully support for that will come some time soon

**Comment by limsijie93** [comment]
Hi
I managed to get the same output as @parvizp. However, when I tried to test it using the TF Lite interpreter (using tf-nightly-cpu), I got the following error:
`RuntimeError: Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference.Node number 194 (FlexCropAndResize) failed to prepare.`

Code reference:
`model_path = "./tflite_models/mask_rcnn_resnet50_atrous_coco_2018_01_28.exported_1024_800.tflite"

# Load TFLite model and allocate tensors.
interpreter = tf.lite.Interpreter(model_path=model_path)
interpreter.allocate_tensors()

# Get input and output tensors.
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()`

**Comment by srjoglekar246** [comment]
@limsijie93 You need to make some building changes as per the [official documentation](https://www.tensorflow.org/lite/guide/ops_select#running_the_model) for things to run :-)

**Comment by limsijie93** [comment]
@srjoglekar246 Does  https://github.com/tensorflow/tensorflow/issues/34845#issuecomment-573156336 mean that we can't have instance segmentation for mobile inference at the moment? Or can it be done with some slight modification?

**Comment by srjoglekar246** [comment]
@limsijie93 There are other models you can use, such as DeepLabv3 which has a [TFLite example](https://www.tensorflow.org/lite/models/segmentation/overview)

**Comment by limsijie93** [comment]
@srjoglekar246 I see. TFLite only supports semantic segmentation for now? Any idea whether support for instance segementation is already in the pipeline?

**Comment by srjoglekar246** [comment]
@limsijie93 Its a matter of coming up with a TF model that is light-weight enough to run fast on edge devices :-). I think there are some versions of 'small' Mask-RCNNs out there, but there are none on the TF-Object Detection model page.

**Comment by limsijie93** [comment]
@srjoglekar246 I see. Does that mean that Mask-RCNN ops are already supported by TFLite? Previously I tried the conversion and it seems that some ops are not yet supported :(

**Comment by srjoglekar246** [comment]
You need to use [select TF ops](https://www.tensorflow.org/lite/guide/ops_select) to run all ops :-).

**Comment by limsijie93** [comment]
@srjoglekar246 
I tried turning on the select_tf_ops

```
converter = tf.lite.TFLiteConverter.from_frozen_graph(model_pb_path, input_arrays, output_arrays,input_shapes)

tf.enable_control_flow_v2()

converter.experimental_new_converter = True
converter.allow_custom_ops = True # will need to remove. Reference: https://github.com/tensorflow/tensorflow/issues/28485#issuecomment-574800279

converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS] 

print('Tflite model conversion starting')
tflite_model = converter.convert()
print('Tflite model conversion completed')

model_tflite_path = os.path.join(export_base_path, "converted_model_unoptimized.tflite")
```

But I ran into the following errors:
```
ConverterError: See console for info.
2020-04-15 02:12:22.185353: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: NonMaxSuppressionV3
2020-04-15 02:12:22.185553: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: CropAndResize
2020-04-15 02:12:22.185598: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: CropAndResize
2020-04-15 02:12:22.185645: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: CropAndResize
2020-04-15 02:12:22.185679: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: CropAndResize
2020-04-15 02:12:22.207749: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: DenseToDenseSetOperation
2020-04-15 02:12:22.207844: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayV3
2020-04-15 02:12:22.207866: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2020-04-15 02:12:22.207891: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayScatterV3
2020-04-15 02:12:22.207970: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayV3
2020-04-15 02:12:22.207978: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2020-04-15 02:12:22.207986: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-04-15 02:12:22.207999: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-04-15 02:12:22.208014: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-04-15 02:12:22.208030: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-04-15 02:12:22.208044: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: LoopCond
2020-04-15 02:12:22.208067: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-04-15 02:12:22.208084: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2020-04-15 02:12:22.208092: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-04-15 02:12:22.208103: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayReadV3
2020-04-15 02:12:22.208114: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-04-15 02:12:22.208140: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-04-15 02:12:22.208156: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-04-15 02:12:22.208178: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: NonMaxSuppressionV3
2020-04-15 02:12:22.208201: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-04-15 02:12:22.208261: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-04-15 02:12:22.208274: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2020-04-15 02:12:22.208281: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayWriteV3
2020-04-15 02:12:22.208309: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Exit
2020-04-15 02:12:22.208321: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArraySizeV3
2020-04-15 02:12:22.208345: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayGatherV3
2020-04-15 02:12:22.208388: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: DenseToDenseSetOperation
2020-04-15 02:12:22.208605: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: CropAndResize
2020-04-15 02:12:22.208641: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: CropAndResize
2020-04-15 02:12:22.208673: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: CropAndResize
2020-04-15 02:12:22.208705: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: CropAndResize
2020-04-15 02:12:22.408000: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 2239 operators, 3602 arrays (0 quantized)
2020-04-15 02:12:22.470324: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 2239 operators, 3602 arrays (0 quantized)
2020-04-15 02:12:23.086255: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 1: 626 operators, 1350 arrays (0 quantized)
2020-04-15 02:12:23.104595: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 2: 618 operators, 1342 arrays (0 quantized)
2020-04-15 02:12:23.122535: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 3: 616 operators, 1338 arrays (0 quantized)
2020-04-15 02:12:23.140117: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Group bidirectional sequence lstm/rnn: 616 operators, 1338 arrays (0 quantized)
2020-04-15 02:12:23.155104: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before dequantization graph transformations: 616 operators, 1338 arrays (0 quantized)
2020-04-15 02:12:23.184439: I tensorflow/lite/toco/allocate_transient_arrays.cc:345] Total transient array allocated size: 259686592 bytes, theoretical optimal value: 157286592 bytes.
2020-04-15 02:12:23.187524: I tensorflow/lite/toco/toco_tooling.cc:454] Number of parameters: 63458975
2020-04-15 02:12:23.188504: W tensorflow/lite/toco/tflite/operator.cc:2706] Op DenseToDenseSetOperation is a valid TensorFlow op but has not been whitelisted for the TensorFlow Lite flex op set.
2020-04-15 02:12:23.188571: W tensorflow/lite/toco/tflite/operator.cc:2706] Op DenseToDenseSetOperation is a valid TensorFlow op but has not been whitelisted for the TensorFlow Lite flex op set.
2020-04-15 02:12:23.188837: W tensorflow/lite/toco/tflite/operator.cc:2706] Op DenseToDenseSetOperation is a valid TensorFlow op but has not been whitelisted for the TensorFlow Lite flex op set.
2020-04-15 02:12:23.188887: W tensorflow/lite/toco/tflite/operator.cc:2706] Op DenseToDenseSetOperation is a valid TensorFlow op but has not been whitelisted for the TensorFlow Lite flex op set.
2020-04-15 02:12:23.189116: E tensorflow/lite/toco/toco_tooling.cc:481] Some of the operators in the model are not supported by TensorFlow Flex runtime: Enter, Exit.
Traceback (most recent call last):
  File "/usr/local/bin/toco_from_protos", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 89, in main
    app.run(main=execute, argv=[sys.argv[0]] + unparsed)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 52, in execute
    enable_mlir_converter)
Exception: Some of the operators in the model are not supported by TensorFlow Flex runtime: Enter, Exit.
```

**Comment by srjoglekar246** [comment]
@limsijie93 Can you [enable control flow V2](https://www.tensorflow.org/api_docs/python/tf/compat/v1/enable_control_flow_v2)? TFLite doesn't support control flow V1, since the ops (Enter/Merge, etc etc) are very difficult to pattern-match.

**Comment by limsijie93** [comment]
@srjoglekar246 I tried enabling control flow v2 with this
```
tf.enable_control_flow_v2()
```

Or do I need to do this?
```
tf.compat.v1.enable_control_flow_v2()
```

**Comment by srjoglekar246** [comment]
I think that should do. Do you get the same message as above? (i.e, ops like Merge, Switch etc?) In that case, your TF is not using Control Flow V2, so you might have to dig in why.

**Comment by limsijie93** [comment]
This was the output I got @srjoglekar246 

```
ConverterError: See console for info.
2020-04-15 02:12:22.185353: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: NonMaxSuppressionV3
2020-04-15 02:12:22.185553: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: CropAndResize
2020-04-15 02:12:22.185598: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: CropAndResize
2020-04-15 02:12:22.185645: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: CropAndResize
2020-04-15 02:12:22.185679: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: CropAndResize
2020-04-15 02:12:22.207749: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: DenseToDenseSetOperation
2020-04-15 02:12:22.207844: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayV3
2020-04-15 02:12:22.207866: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2020-04-15 02:12:22.207891: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayScatterV3
2020-04-15 02:12:22.207970: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayV3
2020-04-15 02:12:22.207978: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2020-04-15 02:12:22.207986: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-04-15 02:12:22.207999: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-04-15 02:12:22.208014: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-04-15 02:12:22.208030: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-04-15 02:12:22.208044: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: LoopCond
2020-04-15 02:12:22.208067: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-04-15 02:12:22.208084: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2020-04-15 02:12:22.208092: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-04-15 02:12:22.208103: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayReadV3
2020-04-15 02:12:22.208114: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-04-15 02:12:22.208140: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-04-15 02:12:22.208156: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-04-15 02:12:22.208178: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: NonMaxSuppressionV3
2020-04-15 02:12:22.208201: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-04-15 02:12:22.208261: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-04-15 02:12:22.208274: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2020-04-15 02:12:22.208281: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayWriteV3
2020-04-15 02:12:22.208309: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Exit
2020-04-15 02:12:22.208321: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArraySizeV3
2020-04-15 02:12:22.208345: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayGatherV3
2020-04-15 02:12:22.208388: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: DenseToDenseSetOperation
2020-04-15 02:12:22.208605: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: CropAndResize
2020-04-15 02:12:22.208641: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: CropAndResize
2020-04-15 02:12:22.208673: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: CropAndResize
2020-04-15 02:12:22.208705: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: CropAndResize
2020-04-15 02:12:22.408000: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 2239 operators, 3602 arrays (0 quantized)
2020-04-15 02:12:22.470324: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 2239 operators, 3602 arrays (0 quantized)
2020-04-15 02:12:23.086255: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 1: 626 operators, 1350 arrays (0 quantized)
2020-04-15 02:12:23.104595: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 2: 618 operators, 1342 arrays (0 quantized)
2020-04-15 02:12:23.122535: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 3: 616 operators, 1338 arrays (0 quantized)
2020-04-15 02:12:23.140117: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Group bidirectional sequence lstm/rnn: 616 operators, 1338 arrays (0 quantized)
2020-04-15 02:12:23.155104: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before dequantization graph transformations: 616 operators, 1338 arrays (0 quantized)
2020-04-15 02:12:23.184439: I tensorflow/lite/toco/allocate_transient_arrays.cc:345] Total transient array allocated size: 259686592 bytes, theoretical optimal value: 157286592 bytes.
2020-04-15 02:12:23.187524: I tensorflow/lite/toco/toco_tooling.cc:454] Number of parameters: 63458975
2020-04-15 02:12:23.188504: W tensorflow/lite/toco/tflite/operator.cc:2706] Op DenseToDenseSetOperation is a valid TensorFlow op but has not been whitelisted for the TensorFlow Lite flex op set.
2020-04-15 02:12:23.188571: W tensorflow/lite/toco/tflite/operator.cc:2706] Op DenseToDenseSetOperation is a valid TensorFlow op but has not been whitelisted for the TensorFlow Lite flex op set.
2020-04-15 02:12:23.188837: W tensorflow/lite/toco/tflite/operator.cc:2706] Op DenseToDenseSetOperation is a valid TensorFlow op but has not been whitelisted for the TensorFlow Lite flex op set.
2020-04-15 02:12:23.188887: W tensorflow/lite/toco/tflite/operator.cc:2706] Op DenseToDenseSetOperation is a valid TensorFlow op but has not been whitelisted for the TensorFlow Lite flex op set.
2020-04-15 02:12:23.189116: E tensorflow/lite/toco/toco_tooling.cc:481] Some of the operators in the model are not supported by TensorFlow Flex runtime: Enter, Exit.
Traceback (most recent call last):
  File "/usr/local/bin/toco_from_protos", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 89, in main
    app.run(main=execute, argv=[sys.argv[0]] + unparsed)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 52, in execute
    enable_mlir_converter)
Exception: Some of the operators in the model are not supported by TensorFlow Flex runtime: Enter, Exit.
```

**Comment by bmabir17** [comment]
I was able to convert the [mask-rcnn from matterport](https://github.com/matterport/) using [this script](https://gist.github.com/bmabir17/754a6e0450ec4fd5e25e462af949cde6 ) with tflite 1.3


But now i am facing a segmentation error, when i try to run inference with the tflite interpreter (Tried both 1.3 and 2.0 tflite versions)
```python
def load_tf_model(model_path="mask_rcnn_coco_256_exp.tflite"):
    interpreter = tf.lite.Interpreter(model_path)
    # Get input tensors.
    input_details = interpreter.get_input_details()
    interpreter.resize_tensor_input(input_details[0]['index'],(1,256,256,3))
    interpreter.allocate_tensors()

    # Get output tensors.
    output_details = interpreter.get_output_details()
    for input_detail in input_details:
        print(" input_detail", input_detail)
    for output_detail in output_details:
        print("output_detail",output_detail)

    # Test model on random input data.
    input_shape = input_details[0]['shape']
    print("input_shape tflite",input_shape)
    input_data = np.array(np.random.random_sample((1, 256, 256,3)), dtype=np.float32)
    interpreter.set_tensor(input_details[0]['index'], input_data)
    print(input_shape)
    interpreter.invoke()

    # The function `get_tensor()` returns a copy of the tensor data.
    # Use `tensor()` in order to get a pointer to the tensor.
    output_data = interpreter.get_tensor(output_details['index'])
    print(output_data)
```

**Comment by srjoglekar246** [comment]
What is the error?

**Comment by bmabir17** [comment]
Segmentation error

**Comment by Zakria96** [comment]
Is your model converted to tflite successfully ?
