### ISSUE TITLE
Can not load tflite model converted from pytorch

### ISSUE THREAD

**Issue by ambarion** [tensorflow/tensorflow#34860]
**System information**
- Win10:
- TensorFlow version=1.15:

**Code to generate tflite model**
Generate the tflite model with cmd
```
python tflite_convert.py 
--graph_def_file=./epoch10_model_toco.pb 
--output_file=./lite.tflite 
--inference_type=QUANTIZED_UINT8 
--mean_values=0 --std_dev_values=1 
--input_arrays=0 --output_arrays=Reshape_136 --input_shape=1,3,120,18,2 
--default_ranges_min=0 --default_ranges_max=6 --post_training_quantize
```

**Code to load tflite model**

```
import tensorflow as tf

# Load TFLite model and allocate tensors.
interpreter = tf.lite.Interpreter(model_path="converted_model.tflite")
interpreter.allocate_tensors()

# Get input and output tensors.
input_details = interpreter.get_input_details()
print(input_details)
output_details = interpreter.get_output_details()
print(output_details)

# Test model on random input data.
input_shape = input_details[0]['shape']
input_data = np.array(np.random.random_sample(input_shape), dtype=np.float32)
interpreter.set_tensor(input_details[0]['index'], input_data)

interpreter.invoke()

# The function `get_tensor()` returns a copy of the tensor data.
# Use `tensor()` in order to get a pointer to the tensor.
output_data = interpreter.get_tensor(output_details[0]['index'])
print(output_data)
```

**Error Message**

```
Traceback (most recent call last):
  File "demo.py", line 97, in <module>
    main()
  File "demo.py", line 59, in main
    interpreter = tf.lite.Interpreter(model_path=PATH_TO_TFLITE)
  File "C:\Users\Administrator\.conda\envs\stgcn\lib\site-packages\tensorflow_core\lite\python\interpreter.py", line 206, in __init__
    model_path))
ValueError: Input array not provided for operation 'reshape'.
```

**If i convert .pb to .tflite without uint8 quantized**

```
python tflite_convert.py 
--graph_def_file=./epoch10_model_toco.pb 
--output_file=./lite.tflite 
--input_arrays=0 --output_arrays=Reshape_136 --input_shape=1,3,120,18,2 
```

Then load the tflite without quantized as the same.
Still i got another error message.

```
Traceback (most recent call last):
  File "demo.py", line 97, in <module>
    main()
  File "demo.py", line 60, in main
    interpreter.allocate_tensors()
  File "C:\Users\Administrator\.conda\envs\stgcn\lib\site-packages\tensorflow_core\lite\python\interpreter.py", line 244, in allocate_tensors
    return self._interpreter.AllocateTensors()
  File "C:\Users\Administrator\.conda\envs\stgcn\lib\site-packages\tensorflow_core\lite\python\interpreter_wrapper\tensorflow_wrap_interpreter_wrapper.py", line 106, in AllocateTensors
    return _tensorflow_wrap_interpreter_wrapper.InterpreterWrapper_AllocateTensors(self)
RuntimeError: tensorflow/lite/kernels/transpose.cc Transpose op only supports 1D-4D input arrays.Node number 0 (TRANSPOSE) failed to prepare.
```

How can i convert the .pb to the .tflite, which could be loaded.
Is there something wrong in the .tflite layer?How to correct that?

**Comment by daverim** [comment]
Hi @ambarion, could you please try setting --experimental_new_converter=True to the tflite_convert command line?

**Comment by ambarion** [comment]
> Hi @ambarion, could you please try setting --experimental_new_converter=True to the tflite_convert command line?

Thanks for your reply, but i still got the same error.

**Comment by sanrahul** [comment]
Having same issue::
First converted pytorch model to onnx(model.onnx). And then converted onnx model to pb(model.pb). Then changed shape to NWHC(model_toco.pb) using https://github.com/paulbauriegel/tensorflow-tools/blob/master/convert-model-to-NWHC.py . Then used below code to convert to tflite.
`converter = tf.lite.TFLiteConverter.from_frozen_graph('model_toco.pb',
                                                          input_arrays=['input0'],
                                                          output_arrays=['output0'] 
    )`
    `converter.optimizations = [tf.lite.Optimize.DEFAULT]`
    `tf_lite_model = converter.convert() `
    `open('model_toco.tflite', 'wb').write(tf_lite_model)
`
When loading this tflite model on PC... gives the same error.
tf version:: 1.15(pip install)

Any solutions or way around??

**Comment by zldrobit** [comment]
@ambarion @sanrahul, by quantizing YOLO v3 for TF Lite, I also encounter ValueError: Input array not provided for operation 'reshape'.
I made a script to fix the reshape problems, plz refer to **Quantization** section in [onnx_tflite_yolov3](https://github.com/zldrobit/onnx_tflite_yolov3)

**Comment by MaratZakirov** [comment]
> @ambarion @sanrahul, by quantizing YOLO v3 for TF Lite, I also encounter ValueError: Input array not provided for operation 'reshape'.
> I made a script to fix the reshape problems, plz refer to **Quantization** section in [onnx_tflite_yolov3](https://github.com/zldrobit/onnx_tflite_yolov3)

Mine has problems of converting pytorch `F.interpolate ` and `torch.view()`. How did you converted `F.interpolate` (which is a part of yolo3 model) to TFlite?

**Comment by zldrobit** [comment]
@Mara

> > @ambarion @sanrahul, by quantizing YOLO v3 for TF Lite, I also encounter ValueError: Input array not provided for operation 'reshape'.
> > I made a script to fix the reshape problems, plz refer to **Quantization** section in [onnx_tflite_yolov3](https://github.com/zldrobit/onnx_tflite_yolov3)
> 
> Mine has problems of converting pytorch `F.interpolate ` and `torch.view()`. How did you converted `F.interpolate` (which is a part of yolo3 model) to TFlite?

TFLite does not  support *5-dimensional reshape*, so you have to change the output of  [`torch.view()` to 1-4D](https://github.com/zldrobit/onnx_tflite_yolov3/blob/master/models.py#L169) 
I haven't seen any problems with `F.interpolate`, what the error message?

**Comment by MaratZakirov** [comment]
@zldrobit 
Most interesting part of output
```
2020-05-13 11:02:11.573396: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: If
2020-05-13 11:02:11.573439: F tensorflow/lite/toco/import_tensorflow.cc:114] Check failed: attr.value_case() == AttrValue::kType (1 vs. 6)
```
All output
```
Traceback (most recent call last):
  File "/home/marat/OCR/yolo3/torch2tflite.py", line 127, in <module>
    tflite_model = converter.convert()
  File "/home/marat/anaconda3/envs/cexp/lib/python3.7/site-packages/tensorflow_core/lite/python/lite.py", line 1007, in convert
    **converter_kwargs)
  File "/home/marat/anaconda3/envs/cexp/lib/python3.7/site-packages/tensorflow_core/lite/python/convert.py", line 457, in toco_convert_impl
    enable_mlir_converter=enable_mlir_converter)
  File "/home/marat/anaconda3/envs/cexp/lib/python3.7/site-packages/tensorflow_core/lite/python/convert.py", line 203, in toco_convert_protos
    raise ConverterError("See console for info.\n%s\n%s\n" % (stdout, stderr))
tensorflow.lite.python.convert.ConverterError: See console for info.
2020-05-13 11:02:11.123019: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/lib64:/home/marat/anaconda3/lib
2020-05-13 11:02:11.123080: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/lib64:/home/marat/anaconda3/lib
2020-05-13 11:02:11.123089: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2020-05-13 11:02:11.557879: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-05-13 11:02:11.563803: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3407930000 Hz
2020-05-13 11:02:11.564214: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x56377f6b4ce0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-05-13 11:02:11.564240: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-05-13 11:02:11.565808: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-05-13 11:02:11.568053: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2020-05-13 11:02:11.568071: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: saturn
2020-05-13 11:02:11.568076: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: saturn
2020-05-13 11:02:11.568107: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 440.64.0
2020-05-13 11:02:11.568126: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 440.64.0
2020-05-13 11:02:11.568131: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:310] kernel version seems to match DSO: 440.64.0
2020-05-13 11:02:11.573396: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: If
2020-05-13 11:02:11.573439: F tensorflow/lite/toco/import_tensorflow.cc:114] Check failed: attr.value_case() == AttrValue::kType (1 vs. 6)
Fatal Python error: Aborted

Current thread 0x00007fa391a0b700 (most recent call first):
  File "/home/marat/anaconda3/envs/cexp/lib/python3.7/site-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 56 in execute
  File "/home/marat/anaconda3/envs/cexp/lib/python3.7/site-packages/absl/app.py", line 250 in _run_main
  File "/home/marat/anaconda3/envs/cexp/lib/python3.7/site-packages/absl/app.py", line 299 in run
  File "/home/marat/anaconda3/envs/cexp/lib/python3.7/site-packages/tensorflow_core/python/platform/app.py", line 40 in run
  File "/home/marat/anaconda3/envs/cexp/lib/python3.7/site-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 93 in main
  File "/home/marat/anaconda3/envs/cexp/bin/toco_from_protos", line 8 in <module>
Aborted (core dumped)
```

**Comment by zldrobit** [comment]
```
2020-05-13 11:02:11.573396: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: If
2020-05-13 11:02:11.573439: F tensorflow/lite/toco/import_tensorflow.cc:114] Check failed: attr.value_case() == AttrValue::kType (1 vs. 6)
```
It cannot be confirmed from above that `F.interpolate`  or `torch.view()` is causing the error.
You may have to check your computation graph with netron to locate the problematic op which is near `If`.
Even to debug Tensorflow/TFLite by yourself (including compilation of debug version code).

**Comment by pchao6** [comment]
@ambarion Hello, have you salved the problem?

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
