### ISSUE TITLE
ImportError: libcuda.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by rezaprince** [tensorflow/tensorflow#34872]
hi im beginner in tensorflow! i want  run my tensorflow code in ipm but i got this error :

Traceback (most recent call last):
  File "/share/Application/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/share/Application/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/share/Application/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/share/Application/anaconda3/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/share/Application/anaconda3/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libcuda.so.1: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 5, in <module>
    import VDSR.vdsr as vdsr
  File "../VDSR/vdsr.py", line 1, in <module>
    import tensorflow as tf
  File "/share/Application/anaconda3/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/share/Application/anaconda3/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/share/Application/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/share/Application/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/share/Application/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/share/Application/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/share/Application/anaconda3/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/share/Application/anaconda3/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libcuda.so.1: cannot open shared object file: No such file or directory

Failed to load the native TensorFlow runtime.

**Comment by rezaprince** [comment]
this is my .sh file:



#!/bin/sh
# Beginning of PBS batch script.
#PBS -l nodes=1:ppn=1
#PBS -o $PBS_JOBID.log
#PBS -e $PBS_JOBID.err
#PBS -N Python 
#PBS -q limited
#PBS -l walltime=700:00:00

export PATH=/share/Application/anaconda3/bin:$PATH
export LD_LIBRARY_PATH=/share/Application/anaconda3/lib:$LD_LIBRARY_PATH

cd $PBS_O_WORKDIR


#-------------------User Define ------------------
export InputName=main.py

python --version
python main.py

**Comment by phreakyphoenix** [comment]
It seems to me that the file libcuda.so.1 either does not exist on your system or your Tf installation fails to locate it. 
Please **add /path/to/libcuda.so.1 in the LD_LIBRARY_PATH and reboot.**
To fing the path run the commands:          
*sudo updatedb*       
*sudo locate libcuda.so.1*     
Then add the address of libcuda.so.1 to your $LD_LIBRARY_PATH env var and reboot.
(For example, for me the path is /usr/lib/)

PS: This is a common issue arising out of the multitude of ways Tf/CuDNN can be installed, very similar issues on #18482, #30670

**Comment by ymodak** [comment]
@rezaprince What version of TF are you installing? Does your CPU support AVX instruction sets?

**Comment by ravikyram** [comment]
@rezaprince 

Any update on this issue please. Thanks!

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
