### ISSUE TITLE
ValueError: Received a scalar value '512' as shape; require a statically known scalar with value '-1' to describe an unknown shape.

### ISSUE THREAD

**Issue by Fansgithub2019** [tensorflow/tensorflow#34886]
**System information**
- OS Platform and Distribution: Linux Ubuntu 16.04
- TensorFlow installed from :pip
- TensorFlow version : 1.3
- Python version: 2.7

**Code to reproduce the issue**
    stfts = tf.signal.rfft(frames, fft_length=512)

Traceback (most recent call last):
  File "pre_process_1.py", line 264, in <module>    feature_2,wav_lens_1,wav_lens,waveforms_0,waveforms_1,waveforms_2,waveforms,frames,stfts,stft_lens,masks = extract_features_tf(feature_1,target_sample_rate=16000)
  File "pre_process_1.py", line 86, in extract_features_tf    filter_banks_1,wav_lens_1,wav_lens,waveforms_0,waveforms_1,waveforms_2,waveforms,frames,stfts,stft_lens,masks = common_audio_tf.compute_mel_filterbank_features(signal, sample_rate=target_sample_rate,dither=0.0, frame_length=25, window_fn=None, lower_edge_hertz=0.0, upper_edge_hertz=8000.0, num_mel_bins=64)
  File "/home/fan/anaconda3/envs/tf_asr/lib/python2.7/site-packages/tensor2tensor/layers/common_audio_tf.py", line 130, in compute_mel_filterbank_features
    stfts = tf.signal.rfft(frames, fft_length=512)
  File "/home/fan/anaconda3/envs/tf_asr/lib/python2.7/site-packages/tensorflow/python/ops/signal/fft_ops.py", line 123, in _rfft
    input_tensor = _maybe_pad_for_rfft(input_tensor, fft_rank, fft_length)
  File "/home/fan/anaconda3/envs/tf_asr/lib/python2.7/site-packages/tensorflow/python/ops/signal/fft_ops.py", line 64, in _maybe_pad_for_rfft
    fft_shape = _tensor_util.constant_value_as_shape(fft_length)
  File "/home/fan/anaconda3/envs/tf_asr/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 888, in constant_value_as_shape
    "scalar with value '-1' to describe an unknown shape." % value)
ValueError: Received a scalar value '512' as shape; require a statically known scalar with value '-1' to describe an unknown shape.

**Comment by BlueBlaze6335** [comment]
@Fansgithub2019 can you please help me with this error. The issue is closed , but if there is any information related to this , it would be appreciated !!

**Comment by ToufiPF** [comment]
Since it's not *that* clear at all on the doc, and I had the same issue I'm leaving this here for the next ones:

For the doc:
fft_length: A Tensor of type int32. An int32 tensor of **shape [1]**. The FFT length.

You should wrap your fft_length in a list ():
```python
n = 512
tf.signal.rfft(acc, fft_length=[n]) # or tf.constant([n])
```
