### ISSUE TITLE
 android studio api19:   System.loadLibrary("tensorflow_demo"); <----what can i do ㅠㅠ

### ISSUE THREAD

**Issue by kimhyungjoo** [tensorflow/tensorflow#3496]
android studio api19:  
TensorflowClassifier.java: 
static {
    System.loadLibrary("tensorflow_demo");
  }
<----this is problem
plz helpㅠㅠ i am korean ㅠㅠ
Couldn't load tensorFlow_demo from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.tensorflow.demo-2.apk"],nativeLibraryDirectories=[/data/app-lib/org.tensorflow.demo-2, /vendor/lib, /system/lib]]]: findLibrary returned null

what should i do?ㅠㅠ plz

error log
-------------------------------------------------------------------------------------------------------------
07-25 14:15:28.049 3164-3164/org.tensorflow.demo E/AndroidRuntime: FATAL EXCEPTION: main
                                                                   Process: org.tensorflow.demo, PID: 3164
                                                                   java.lang.UnsatisfiedLinkError: Couldn't load tensorFlow_demo from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.tensorflow.demo-2.apk"],nativeLibraryDirectories=[/data/app-lib/org.tensorflow.demo-2, /vendor/lib, /system/lib]]]: findLibrary returned null
                                                                       at java.lang.Runtime.loadLibrary(Runtime.java:358)
                                                                       at java.lang.System.loadLibrary(System.java:526)
                                                                       at org.tensorflow.demo.TensorflowClassifier.<clinit>(TensorflowClassifier.java:46)
                                                                       at org.tensorflow.demo.TensorflowImageListener.<init>(TensorflowImageListener.java:54)
                                                                       at org.tensorflow.demo.CameraConnectionFragment.<init>(CameraConnectionFragment.java:240)
                                                                       at org.tensorflow.demo.CameraConnectionFragment.newInstance(CameraConnectionFragment.java:170)
                                                                       at org.tensorflow.demo.CameraActivity.onCreate(CameraActivity.java:30)
                                                                       at android.app.Activity.performCreate(Activity.java:5231)
                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159)
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
                                                                       at android.app.ActivityThread.access$800(ActivityThread.java:135)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:136)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5017)
                                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
                                                                       at dalvik.system.NativeStart.main(Native Method)
.
--------------------------------------------------------------------------------------------------------------

**Comment by kimhyungjoo** [comment]
plz helpㅠㅠ i am korean ㅠㅠ
Couldn't load tensorFlow_demo from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.tensorflow.demo-2.apk"],nativeLibraryDirectories=[/data/app-lib/org.tensorflow.demo-2, /vendor/lib, /system/lib]]]: findLibrary returned null

what should i do?ㅠㅠ plz

**Comment by wagonhelm** [comment]
I'm no expert but I beleive API 19 would of been used on a older version of Android SDK this is what my workspace file looked like.

`android_sdk_repository(
    name = "androidsdk",
    api_level = 24,
    build_tools_version = "24.0.0",
    path = "YOURPATH")

android_ndk_repository(
    name="androidndk",
    path="YOURPATH/android-ndk-r12b",
    api_level=21)`

Maybe try that?  If you could also mention what Operating System and what versions of the Android SDK & NDK you are trying to use and copy and paste what your WORKSPACE file looks like compared to what I pasted I imagine that could be helpful.

**Comment by andrewharp** [comment]
@kimhyungjoo Please see https://github.com/tensorflow/tensorflow/issues/3444, which contains instructions for building the native libs while using Android studio.

**Comment by petewarden** [comment]
Since there's not been an update for a while, closing this issue. Please reopen if you're still having problems.
