### ISSUE TITLE
DLL Load Failed in tensorflow-gpu

### ISSUE THREAD

**Issue by monilshah98** [tensorflow/tensorflow#34984]
Whenever i try to run my python script, i keep getting this error. My environment specifications are:

Python: 3.7.4
CUDA: 9.0
Tensorflow-gpu: 1.14.0

Error:

Traceback (most recent call last):
  File "O:\WinPython\WPy64-3741\python-3.7.4.amd64\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "O:\WinPython\WPy64-3741\python-3.7.4.amd64\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "O:\WinPython\WPy64-3741\python-3.7.4.amd64\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "O:\WinPython\WPy64-3741\python-3.7.4.amd64\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "O:\WinPython\WPy64-3741\python-3.7.4.amd64\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "demo_cli.py", line 3, in <module>
    from synthesizer.inference import Synthesizer
  File "C:\Users\DELL\Desktop\Project\Voice_Cloning\Real-Time-Voice-Cloning-master\synthesizer\inference.py", line 1, in <module>
    from synthesizer.tacotron2 import Tacotron2
  File "C:\Users\DELL\Desktop\Project\Voice_Cloning\Real-Time-Voice-Cloning-master\synthesizer\tacotron2.py", line 3, in <module>
    from synthesizer.models import create_model
  File "C:\Users\DELL\Desktop\Project\Voice_Cloning\Real-Time-Voice-Cloning-master\synthesizer\models\__init__.py", line 1, in <module>
    from .tacotron import Tacotron
  File "C:\Users\DELL\Desktop\Project\Voice_Cloning\Real-Time-Voice-Cloning-master\synthesizer\models\tacotron.py", line 1, in <module>
    import tensorflow as tf
  File "O:\WinPython\WPy64-3741\python-3.7.4.amd64\lib\site-packages\tensorflow\__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "O:\WinPython\WPy64-3741\python-3.7.4.amd64\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "O:\WinPython\WPy64-3741\python-3.7.4.amd64\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "O:\WinPython\WPy64-3741\python-3.7.4.amd64\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "O:\WinPython\WPy64-3741\python-3.7.4.amd64\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "O:\WinPython\WPy64-3741\python-3.7.4.amd64\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "O:\WinPython\WPy64-3741\python-3.7.4.amd64\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "O:\WinPython\WPy64-3741\python-3.7.4.amd64\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

Failed to load the native TensorFlow runtime.

**Comment by gadagashwini** [comment]
@monilshah98, 
Does your CPU support AVX instruction sets?
Check, MSVC 2015 redistributable update 3. It is listed here under windows:
https://www.tensorflow.org/install/pip. 
And also make sure you have installed cuDNN 7.4. Thanks!

**Comment by ymodak** [comment]
@monilshah98 Please use cuda 10.0 for TF 1.14.0
See https://www.tensorflow.org/install/gpu#software_requirements
Also add cuda, cudnn, cupti variables to your environment path.
https://www.tensorflow.org/install/gpu#windows_setup

**Comment by gadagashwini** [comment]
@monilshah98, Is this still an issue!

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
