### ISSUE TITLE
_pywrap_tensorflow_internal.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by gswebspace** [tensorflow/tensorflow#34991]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): [Ubuntu 18.04.3 LTS](https://wiki.odroid.com/odroid-c2/os_images/ubuntu/v3.1) on ODROID C2
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Not a mobile but the hardware is ODROID C2
- TensorFlow installed from (source or binary): source (cross-compiled for ODROID C2)
- TensorFlow version: 2.0.0
- Python version: 3.6.9
- Installed using virtualenv? pip? conda?: Using virtualenv, installed using pip, with a bazel built .whl file
- Bazel version (if compiling from source): 0.26.0
- GCC/Compiler version (if compiling from source): 7.4.0
- CUDA/cuDNN version: N/A
- GPU model and memory: Mali450MP3 (But GPU not used)

**Describe the problem**
Bazel build from source and pip install successful, but doing `import tensorflow` results in following error -
```
ImportError: /home/rmc/code/venv/lib/python3.6/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so: cannot open shared object file: No such file or directory
```
The file is not missing, it exists.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
- Setup a docker container for Ubuntu 18.04.3 and open a terminal into it
- Follow all instructions from [official build from source docs](https://www.tensorflow.org/install/source)
    - Use `python3-dev  python3-pip`
    - Use `virtualenv` to install python dependencies
    - Install Bazel binary directly (no bazelisk), version 0.26.0 and add it to your $PATH
    - Do not use GPU support
    - Clone Tensorflow from official Github repo, and use tag v2.0.0
    - During `./configure`, say Yes to `XLA JIT` and No to everything else
    - During `./configure`, Set the optimization flag to `-march=armv8-a+crc`
    - Use Bazel build command : `bazel build --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" //tensorflow/tools/pip_package:build_pip_package`
- Transfer the built `.whl` to ODROID C2 and rename `tensorflow-2.0.0-cp36-cp36m-linux_x86_64.whl` to `tensorflow-2.0.0-cp36-cp36m-linux_aarch64.whl`
- Setup Python on the device using `sudo apt-get install python3-dev python3-pip`
- Setup a virtualenv using `virtualenv -p python3.6 ./venv` and activate it
- Install Tensorflow using `pip install tensorflow-2.0.0-cp36-cp36m-linux_aarch64.whl`
    - Install HDF5 system package dependency using `sudo apt-get install pkg-config libhdf5-100 libhdf5-dev`
- Run Python interpreter and execute `import tensorflow`
- You will get the above error regarding `_pywrap_tensorflow_internal.so`

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

- The `/home/rmc/code/venv/lib/python3.6/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so` file exists and is 223M in size
- Output of `ldd /home/rmc/code/venv/lib/python3.6/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so` gives `not a dynamic executable`
- Full error Traceback
```
>>> import tensorflow
Traceback (most recent call last):
  File "/home/rmc/code/venv/lib/python3.6/site-packages/tensorflow_core/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/rmc/code/venv/lib/python3.6/site-packages/tensorflow_core/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/rmc/code/venv/lib/python3.6/site-packages/tensorflow_core/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/rmc/code/venv/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/home/rmc/code/venv/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /home/rmc/code/venv/lib/python3.6/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rmc/code/venv/lib/python3.6/site-packages/tensorflow/__init__.py", line 98, in <module>
    from tensorflow_core import *
  File "/home/rmc/code/venv/lib/python3.6/site-packages/tensorflow_core/__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/home/rmc/code/venv/lib/python3.6/site-packages/tensorflow/__init__.py", line 50, in __getattr__
    module = self._load()
  File "/home/rmc/code/venv/lib/python3.6/site-packages/tensorflow/__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "/home/rmc/code/venv/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/rmc/code/venv/lib/python3.6/site-packages/tensorflow_core/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/rmc/code/venv/lib/python3.6/site-packages/tensorflow_core/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/rmc/code/venv/lib/python3.6/site-packages/tensorflow_core/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/rmc/code/venv/lib/python3.6/site-packages/tensorflow_core/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/rmc/code/venv/lib/python3.6/site-packages/tensorflow_core/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/rmc/code/venv/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/home/rmc/code/venv/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /home/rmc/code/venv/lib/python3.6/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

**Comment by gswebspace** [comment]
Also sharing the Bazel logs as attachment.

[Bazel logs.zip](https://github.com/tensorflow/tensorflow/files/3944213/Bazel.logs.zip)

**Comment by Rbiessy** [comment]
I just had a similar error. The error message is misleading but it may be that `_pywrap_tensorflow_internal.so` is not compiled for the architecture you would expect i.e. the cross compilation went wrong. Can you check what is the output of `file /home/rmc/code/venv/lib/python3.6/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so`?

**Comment by gswebspace** [comment]
@Rbiessy I tried to inspect the file `/home/rmc/code/venv/lib/python3.6/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so`. Sharing the details -

- Output of `ldd _pywrap_tensorflow_internal.so` gives 
`not a dynamic executable`
- The file size is 223M.
- Output of `readelf -a _pywrap_tensorflow_internal.so` gives
```
ELF Header:
  Magic:   7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00 
  Class:                             ELF64
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              DYN (Shared object file)
  Machine:                           Advanced Micro Devices X86-64
  Version:                           0x1
  Entry point address:               0x0
  Start of program headers:          64 (bytes into file)
  Start of section headers:          233778704 (bytes into file)
  Flags:                             0x0
  Size of this header:               64 (bytes)
  Size of program headers:           56 (bytes)
  Number of program headers:         9
  Size of section headers:           64 (bytes)
  Number of section headers:         36
  Section header string table index: 35

Section Headers:
  [Nr] Name              Type             Address           Offset
       Size              EntSize          Flags  Link  Info  Align
  [ 0]                   NULL             0000000000000000  00000000
       0000000000000000  0000000000000000           0     0     0
  [ 1] .note.gnu.build-i NOTE             0000000000000238  00000238
       0000000000000024  0000000000000000   A       0     0     4
  [ 2] .dynsym           DYNSYM           0000000000000260  00000260
       000000000026cf40  0000000000000018   A       3     5     8
  [ 3] .dynstr           STRTAB           000000000026d1a0  0026d1a0
       0000000000ede6c5  0000000000000000   A       0     0     1
  [ 4] .gnu.hash         GNU_HASH         000000000114b868  0114b868
       00000000000c4940  0000000000000000   A       2     0     8
  [ 5] .gnu.version      VERSYM           00000000012101a8  012101a8
       0000000000033bf0  0000000000000002   A       2     0     2
  [ 6] .gnu.version_d    VERDEF           0000000001243d98  01243d98
       0000000000000038  0000000000000000   A       3     2     4
  [ 7] .gnu.version_r    VERNEED          0000000001243dd0  01243dd0
       0000000000000350  0000000000000000   A       3     8     4
  [ 8] .rela.dyn         RELA             0000000001244120  01244120
       00000000005f6718  0000000000000018   A       2     0     8
  [ 9] .rela.plt         RELA             000000000183a838  0183a838
       00000000001179d8  0000000000000018  AI       2    11     8
  [10] .init             PROGBITS         0000000001952210  01952210
       0000000000000017  0000000000000000  AX       0     0     4
  [11] .plt              PROGBITS         0000000001952230  01952230
       00000000000ba6a0  0000000000000010  AX       0     0     16
  [12] .text             PROGBITS         0000000001a0c900  01a0c900
       000000000722ca3f  0000000000000000  AX       0     0     64
  [13] text_env          PROGBITS         0000000008c39340  08c39340
       0000000000002c7f  0000000000000000  AX       0     0     16
  [14] malloc_hook       PROGBITS         0000000008c3bfc0  08c3bfc0
       0000000000000282  0000000000000000  AX       0     0     16
  [15] .fini             PROGBITS         0000000008c3c244  08c3c244
       0000000000000009  0000000000000000  AX       0     0     4
  [16] .rodata           PROGBITS         0000000008c3d000  08c3d000
       00000000010d5390  0000000000000000   A       0     0     4096
  [17] .gcc_except_table PROGBITS         0000000009d12390  09d12390
       00000000001ab801  0000000000000000   A       0     0     4
  [18] .eh_frame         PROGBITS         0000000009ebdb98  09ebdb98
       00000000007ed994  0000000000000000   A       0     0     8
  [19] .eh_frame_hdr     PROGBITS         000000000a6ab52c  0a6ab52c
       000000000016a54c  0000000000000000   A       0     0     4
  [20] .tbss             NOBITS           000000000a8170e0  0a8160e0
       0000000000000160  0000000000000000 WAT       0     0     8
  [21] .data.rel.ro.loca PROGBITS         000000000a8170e0  0a8160e0
       00000000001cf850  0000000000000000  WA       0     0     32
  [22] .fini_array       FINI_ARRAY       000000000a9e6930  0a9e5930
       0000000000000008  0000000000000008  WA       0     0     8
  [23] .init_array       INIT_ARRAY       000000000a9e6938  0a9e5938
       0000000000004d08  0000000000000008  WA       0     0     8
  [24] .data.rel.ro      PROGBITS         000000000a9eb640  0a9ea640
       000000000016ef78  0000000000000000  WA       0     0     32
  [25] .dynamic          DYNAMIC          000000000ab5a5b8  0ab595b8
       00000000000002b0  0000000000000010  WA       3     0     8
  [26] .got              PROGBITS         000000000ab5a868  0ab59868
       0000000000037428  0000000000000000  WA       0     0     8
  [27] .got.plt          PROGBITS         000000000ab91c90  0ab90c90
       000000000005d360  0000000000000000  WA       0     0     8
  [28] .tm_clone_table   PROGBITS         000000000abef000  0abee000
       0000000000000000  0000000000000000  WA       0     0     8
  [29] .data             PROGBITS         000000000abef000  0abee000
       0000000000020f4c  0000000000000000  WA       0     0     32
  [30] .bss              NOBITS           000000000ac0ff80  0ac0ef4c
       0000000000065ce8  0000000000000000  WA       0     0     64
  [31] .comment          PROGBITS         0000000000000000  0ac0ef4c
       000000000000002c  0000000000000001  MS       0     0     1
  [32] .note.gnu.gold-ve NOTE             0000000000000000  0ac0ef78
       000000000000001c  0000000000000000           0     0     4
  [33] .symtab           SYMTAB           0000000000000000  0ac0ef98
       0000000000744618  0000000000000018          34   211534     8
  [34] .strtab           STRTAB           0000000000000000  0b3535b0
       0000000002b9f6f0  0000000000000000           0     0     1
  [35] .shstrtab         STRTAB           0000000000000000  0def2ca0
       0000000000000170  0000000000000000           0     0     1
Key to Flags:
  W (write), A (alloc), X (execute), M (merge), S (strings), I (info),
  L (link order), O (extra OS processing required), G (group), T (TLS),
  C (compressed), x (unknown), o (OS specific), E (exclude),
  l (large), p (processor specific)

There are no section groups in this file.

Program Headers:
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  PHDR           0x0000000000000040 0x0000000000000040 0x0000000000000040
                 0x00000000000001f8 0x00000000000001f8  R      0x8
  LOAD           0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x000000000a815a78 0x000000000a815a78  R E    0x1000
  LOAD           0x000000000a8160e0 0x000000000a8170e0 0x000000000a8170e0
                 0x00000000003f8e6c 0x000000000045eb88  RW     0x1000
  DYNAMIC        0x000000000ab595b8 0x000000000ab5a5b8 0x000000000ab5a5b8
                 0x00000000000002b0 0x00000000000002b0  RW     0x8
  NOTE           0x0000000000000238 0x0000000000000238 0x0000000000000238
                 0x0000000000000024 0x0000000000000024  R      0x4
  GNU_EH_FRAME   0x000000000a6ab52c 0x000000000a6ab52c 0x000000000a6ab52c
                 0x000000000016a54c 0x000000000016a54c  R      0x4
  GNU_STACK      0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000000000 0x0000000000000000  RW     0x10
  TLS            0x000000000a8160e0 0x000000000a8170e0 0x000000000a8170e0
                 0x0000000000000000 0x0000000000000160  R      0x8
  GNU_RELRO      0x000000000a8160e0 0x000000000a8170e0 0x000000000a8170e0
                 0x00000000003d7f20 0x00000000003d7f20  RW     0x20

 Section to Segment mapping:
  Segment Sections...
   00     
   01     .note.gnu.build-id .dynsym .dynstr .gnu.hash .gnu.version .gnu.version_d .gnu.version_r .rela.dyn .rela.plt .init .plt .text text_env malloc_hook .fini .rodata .gcc_except_table .eh_frame .eh_frame_hdr 
   02     .data.rel.ro.local .fini_array .init_array .data.rel.ro .dynamic .got .got.plt .tm_clone_table .data .bss 
   03     .dynamic 
   04     .note.gnu.build-id 
   05     .eh_frame_hdr 
   06     
   07     .tbss 
   08     .data.rel.ro.local .fini_array .init_array .data.rel.ro .dynamic .got .got.plt 

Dynamic section at offset 0xab595b8 contains 38 entries:
  Tag        Type                         Name/Value
 0x0000000000000003 (PLTGOT)             0xab91c90
 0x0000000000000002 (PLTRELSZ)           1145304 (bytes)
 0x0000000000000017 (JMPREL)             0x183a838
 0x0000000000000014 (PLTREL)             RELA
 0x0000000000000007 (RELA)               0x1244120
 0x0000000000000008 (RELASZ)             6252312 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000006ffffff9 (RELACOUNT)          129300
 0x0000000000000006 (SYMTAB)             0x260
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000005 (STRTAB)             0x26d1a0
 0x000000000000000a (STRSZ)              15591109 (bytes)
 0x000000006ffffef5 (GNU_HASH)           0x114b868
 0x0000000000000001 (NEEDED)             Shared library: [libtensorflow_framework.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libdl.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [librt.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [ld-linux-x86-64.so.2]
 0x000000000000000e (SONAME)             Library soname: [_pywrap_tensorflow_internal.so]
 0x000000000000000c (INIT)               0x1952210
 0x000000000000000d (FINI)               0x8c3c244
 0x000000000000001a (FINI_ARRAY)         0xa9e6930
 0x000000000000001c (FINI_ARRAYSZ)       8 (bytes)
 0x0000000000000019 (INIT_ARRAY)         0xa9e6938
 0x000000000000001b (INIT_ARRAYSZ)       19720 (bytes)
 0x000000000000001d (RUNPATH)            Library runpath: [$ORIGIN/../../_solib_k8/_U_S_Stensorflow_Spython_C_Upywrap_Utensorflow_Uinternal.so___Utensorflow:$ORIGIN/:$ORIGIN/..]
 0x000000000000001e (FLAGS)              BIND_NOW
 0x000000006ffffffb (FLAGS_1)            Flags: NOW
 0x000000006ffffff0 (VERSYM)             0x12101a8
 0x000000006ffffffc (VERDEF)             0x1243d98
 0x000000006ffffffd (VERDEFNUM)          2
 0x000000006ffffffe (VERNEED)            0x1243dd0
 0x000000006fffffff (VERNEEDNUM)         8
 0x0000000000000000 (NULL)               0x0

Relocation section '.rela.dyn' at offset 0x1244120 contains 260513 entries:
  Offset          Info           Type           Sym. Value    Sym. Name + Addend
00000a8170e8  000000000008 R_X86_64_RELATIVE                    a9eb868
00000a8170f0  000000000008 R_X86_64_RELATIVE                    1ce5530
00000a8170f8  000000000008 R_X86_64_RELATIVE                    1ce4b10
00000a817100  000000000008 R_X86_64_RELATIVE                    1ceeb80
00000a817120  000000000008 R_X86_64_RELATIVE                    8c4416b
00000a817130  000000000008 R_X86_64_RELATIVE                    8c4365a
00000a817140  000000000008 R_X86_64_RELATIVE                    8c433c1
00000a817148  000000000008 R_X86_64_RELATIVE                    8c4416d
00000a817150  000000000008 R_X86_64_RELATIVE                    8c433e6
00000a817158  000000000008 R_X86_64_RELATIVE                    8c44176
00000a817160  000000000008 R_X86_64_RELATIVE                    8c43335
00000a817168  000000000008 R_X86_64_RELATIVE                    8c44188
00000a817170  000000000008 R_X86_64_RELATIVE                    8c43436
00000a817178  000000000008 R_X86_64_RELATIVE                    8c4418e
00000a817180  000000000008 R_X86_64_RELATIVE                    8c4346a
00000a817188  000000000008 R_X86_64_RELATIVE                    8c4419d
00000a817190  000000000008 R_X86_64_RELATIVE                    8c43488
00000a817198  000000000008 R_X86_64_RELATIVE                    8c441a5
00000a8171a0  000000000008 R_X86_64_RELATIVE                    8c434c0
00000a8171a8  000000000008 R_X86_64_RELATIVE                    8c441b6
00000a8171b0  000000000008 R_X86_64_RELATIVE                    8c434dc
00000a8171b8  000000000008 R_X86_64_RELATIVE                    8c441bd
00000a8171c0  000000000008 R_X86_64_RELATIVE                    8c4351d
00000a8171c8  000000000008 R_X86_64_RELATIVE                    8c441cd
00000a8171d0  000000000008 R_X86_64_RELATIVE                    8c43512
00000a8171d8  000000000008 R_X86_64_RELATIVE                    8c441d8
00000a8171e0  000000000008 R_X86_64_RELATIVE                    8c43564
00000a8171e8  000000000008 R_X86_64_RELATIVE                    8d05a18
00000a8171f0  000000000008 R_X86_64_RELATIVE                    8c43582
00000a8171f8  000000000008 R_X86_64_RELATIVE                    8d05a40
00000a817200  000000000008 R_X86_64_RELATIVE                    8c435ac
00000a817208  000000000008 R_X86_64_RELATIVE                    8c441ec
00000a817210  000000000008 R_X86_64_RELATIVE                    8c435cc
00000a817218  000000000008 R_X86_64_RELATIVE                    8d05a80
00000a817220  000000000008 R_X86_64_RELATIVE                    8c435d9
00000a817228  000000000008 R_X86_64_RELATIVE                    8d05aa8
.
.
.
.
.
.
.
.
.
.
19d08:   2 (tensorflow)    2 (tensorflow)    2 (tensorflow)    2 (tensorflow) 
19d0c:   2 (tensorflow)    2 (tensorflow)    2 (tensorflow)    2 (tensorflow) 
19d10:   2 (tensorflow)    2 (tensorflow)    2 (tensorflow)    2 (tensorflow) 
19d14:   2 (tensorflow)    2 (tensorflow)    2 (tensorflow)    2 (tensorflow) 
19d18:   2 (tensorflow)    2 (tensorflow)    2 (tensorflow)    2 (tensorflow) 
19d1c:   2 (tensorflow)    2 (tensorflow)    2 (tensorflow)    2 (tensorflow) 
19d20:   2 (tensorflow)    2 (tensorflow)    2 (tensorflow)    2 (tensorflow) 
19d24:   2 (tensorflow)    2 (tensorflow)    2 (tensorflow)    2 (tensorflow) 
19d28:   2 (tensorflow)    2 (tensorflow)    2 (tensorflow)    2 (tensorflow) 
19d2c:   2 (tensorflow)    2 (tensorflow)    2 (tensorflow)    2 (tensorflow) 
19d30:   2 (tensorflow)    2 (tensorflow)    2 (tensorflow)    2 (tensorflow) 
19d34:   2 (tensorflow)    2 (tensorflow)    2 (tensorflow)    2 (tensorflow) 
19d38:   2 (tensorflow)    2 (tensorflow)    2 (tensorflow)    2 (tensorflow) 
19d3c:   2 (tensorflow)    2 (tensorflow)    2 (tensorflow)    2 (tensorflow) 
19d40:   2 (tensorflow)    2 (tensorflow)    2 (tensorflow)    2 (tensorflow) 
19d44:   2 (tensorflow)    2 (tensorflow)    2 (tensorflow)    2 (tensorflow) 
19d48:   2 (tensorflow)    2 (tensorflow)    2 (tensorflow)    2 (tensorflow) 
19d4c:   2 (tensorflow)    2 (tensorflow)    2 (tensorflow)    2 (tensorflow) 
19d50:   2 (tensorflow)    2 (tensorflow)    2 (tensorflow)    2 (tensorflow) 
19d54:   2 (tensorflow)    2 (tensorflow)    2 (tensorflow)    2 (tensorflow) 
19d58:   2 (tensorflow)    2 (tensorflow)    2 (tensorflow)    2 (tensorflow) 
19d5c:   2 (tensorflow)    2 (tensorflow)    2 (tensorflow)    2 (tensorflow) 
19d60:   2 (tensorflow)    2 (tensorflow)    2 (tensorflow)    2 (tensorflow) 
19d64:   2 (tensorflow)    2 (tensorflow)    2 (tensorflow)    2 (tensorflow) 
19d68:   2 (tensorflow)    2 (tensorflow)    2 (tensorflow)    2 (tensorflow) 
19d6c:   2 (tensorflow)    2 (tensorflow)    2 (tensorflow)    2 (tensorflow) 
19d70:   2 (tensorflow)    2 (tensorflow)    2 (tensorflow)    2 (tensorflow) 
19d74:   2 (tensorflow)    2 (tensorflow)    2 (tensorflow)    2 (tensorflow) 
19d78:   2 (tensorflow)    2 (tensorflow)    2 (tensorflow)    2 (tensorflow) 
19d7c:   2 (tensorflow)    2 (tensorflow)    2 (tensorflow)    2 (tensorflow) 
19d80:   2 (tensorflow)    2 (tensorflow)    2 (tensorflow)    2 (tensorflow) 
19d84:   2 (tensorflow)    2 (tensorflow)    2 (tensorflow)    2 (tensorflow) 
19d88:   2 (tensorflow)    2 (tensorflow)    2 (tensorflow)    2 (tensorflow) 
19d8c:   2 (tensorflow)    2 (tensorflow)    2 (tensorflow)    2 (tensorflow) 
19d90:   2 (tensorflow)    2 (tensorflow)    2 (tensorflow)    2 (tensorflow) 
19d94:   2 (tensorflow)    2 (tensorflow)    2 (tensorflow)    2 (tensorflow) 
19d98:   2 (tensorflow)    2 (tensorflow)    2 (tensorflow)    2 (tensorflow) 
19d9c:   2 (tensorflow)    2 (tensorflow)    2 (tensorflow)    2 (tensorflow) 
19da0:   2 (tensorflow)    2 (tensorflow)    2 (tensorflow)    2 (tensorflow) 
19da4:   2 (tensorflow)    2 (tensorflow)    2 (tensorflow)    2 (tensorflow) 
19da8:   2 (tensorflow)    2 (tensorflow)    2 (tensorflow)    2 (tensorflow) 
19dac:   2 (tensorflow)    2 (tensorflow)    2 (tensorflow)    2 (tensorflow) 
19db0:   2 (tensorflow)    2 (tensorflow)    2 (tensorflow)    2 (tensorflow) 
19db4:   2 (tensorflow)    2 (tensorflow)    2 (tensorflow)    2 (tensorflow) 
19db8:   2 (tensorflow)    2 (tensorflow)    2 (tensorflow)    2 (tensorflow) 
19dbc:   2 (tensorflow)    2 (tensorflow)    2 (tensorflow)    2 (tensorflow) 
19dc0:   2 (tensorflow)    2 (tensorflow)    2 (tensorflow)    2 (tensorflow) 
19dc4:   2 (tensorflow)    2 (tensorflow)    2 (tensorflow)    2 (tensorflow) 
19dc8:   2 (tensorflow)    2 (tensorflow)    2 (tensorflow)    2 (tensorflow) 
19dcc:   2 (tensorflow)    2 (tensorflow)    2 (tensorflow)    2 (tensorflow) 
19dd0:   2 (tensorflow)    2 (tensorflow)    2 (tensorflow)    2 (tensorflow) 
19dd4:   2 (tensorflow)    2 (tensorflow)    2 (tensorflow)    2 (tensorflow) 
19dd8:   2 (tensorflow)    2 (tensorflow)    2 (tensorflow)    2 (tensorflow) 
19ddc:   2 (tensorflow)    2 (tensorflow)    2 (tensorflow)    2 (tensorflow) 
19de0:   2 (tensorflow)    2 (tensorflow)    2 (tensorflow)    2 (tensorflow) 
19de4:   2 (tensorflow)    2 (tensorflow)    2 (tensorflow)    2 (tensorflow) 
19de8:   2 (tensorflow)    2 (tensorflow)    2 (tensorflow)    2 (tensorflow) 
19dec:   2 (tensorflow)    2 (tensorflow)    2 (tensorflow)    2 (tensorflow) 
19df0:   2 (tensorflow)    2 (tensorflow)    2 (tensorflow)    2 (tensorflow) 
19df4:   2 (tensorflow)    2 (tensorflow)    2 (tensorflow)    2 (tensorflow) 

Version definition section '.gnu.version_d' contains 2 entries:
Addr: 0x0000000001243d98  Offset: 0x1243d98  Link: 3 (.dynstr)
000000: Rev: 1  Flags: BASE  Index: 1  Cnt: 1  Name: _pywrap_tensorflow_internal.so
0x001c: Rev: 1  Flags: none  Index: 2  Cnt: 1  Name: tensorflow

Version needs section '.gnu.version_r' contains 8 entries:
Addr: 0x0000000001243dd0  Offset: 0x1243dd0  Link: 3 (.dynstr)
000000: Version: 1  File: libc.so.6  Cnt: 15
0x0010:   Name: GLIBC_2.9  Flags: none  Version: 3
0x0020:   Name: GLIBC_2.17  Flags: none  Version: 4
0x0030:   Name: GLIBC_2.2.5  Flags: none  Version: 5
0x0040:   Name: GLIBC_2.10  Flags: none  Version: 6
0x0050:   Name: GLIBC_2.3.3  Flags: none  Version: 7
0x0060:   Name: GLIBC_2.16  Flags: none  Version: 8
0x0070:   Name: GLIBC_2.3  Flags: none  Version: 9
0x0080:   Name: GLIBC_2.6  Flags: none  Version: 10
0x0090:   Name: GLIBC_2.7  Flags: none  Version: 11
0x00a0:   Name: GLIBC_2.15  Flags: none  Version: 12
0x00b0:   Name: GLIBC_2.3.2  Flags: none  Version: 13
0x00c0:   Name: GLIBC_2.3.4  Flags: none  Version: 14
0x00d0:   Name: GLIBC_2.11  Flags: none  Version: 15
0x00e0:   Name: GLIBC_2.4  Flags: none  Version: 16
0x00f0:   Name: GLIBC_2.14  Flags: none  Version: 17
0x0100: Version: 1  File: libpthread.so.0  Cnt: 4
0x0110:   Name: GLIBC_2.3.3  Flags: none  Version: 18
0x0120:   Name: GLIBC_2.2.5  Flags: none  Version: 19
0x0130:   Name: GLIBC_2.12  Flags: none  Version: 20
0x0140:   Name: GLIBC_2.3.2  Flags: none  Version: 21
0x0150: Version: 1  File: libm.so.6  Cnt: 3
0x0160:   Name: GLIBC_2.23  Flags: none  Version: 22
0x0170:   Name: GLIBC_2.2.5  Flags: none  Version: 23
0x0180:   Name: GLIBC_2.27  Flags: none  Version: 24
0x0190: Version: 1  File: libstdc++.so.6  Cnt: 18
0x01a0:   Name: GLIBCXX_3.4.21  Flags: none  Version: 25
0x01b0:   Name: GLIBCXX_3.4  Flags: none  Version: 26
0x01c0:   Name: GLIBCXX_3.4.15  Flags: none  Version: 27
0x01d0:   Name: CXXABI_1.3  Flags: none  Version: 28
0x01e0:   Name: GLIBCXX_3.4.17  Flags: none  Version: 29
0x01f0:   Name: CXXABI_1.3.3  Flags: none  Version: 30
0x0200:   Name: GLIBCXX_3.4.14  Flags: none  Version: 31
0x0210:   Name: CXXABI_1.3.11  Flags: none  Version: 32
0x0220:   Name: GLIBCXX_3.4.11  Flags: none  Version: 33
0x0230:   Name: GLIBCXX_3.4.9  Flags: none  Version: 34
0x0240:   Name: CXXABI_1.3.2  Flags: none  Version: 35
0x0250:   Name: GLIBCXX_3.4.18  Flags: none  Version: 36
0x0260:   Name: CXXABI_1.3.7  Flags: none  Version: 37
0x0270:   Name: GLIBCXX_3.4.19  Flags: none  Version: 38
0x0280:   Name: GLIBCXX_3.4.22  Flags: none  Version: 39
0x0290:   Name: CXXABI_1.3.8  Flags: none  Version: 40
0x02a0:   Name: GLIBCXX_3.4.20  Flags: none  Version: 41
0x02b0:   Name: CXXABI_1.3.5  Flags: none  Version: 42
0x02c0: Version: 1  File: libdl.so.2  Cnt: 1
0x02d0:   Name: GLIBC_2.2.5  Flags: none  Version: 43
0x02e0: Version: 1  File: libgcc_s.so.1  Cnt: 2
0x02f0:   Name: GCC_3.3  Flags: none  Version: 44
0x0300:   Name: GCC_3.0  Flags: none  Version: 45
0x0310: Version: 1  File: librt.so.1  Cnt: 1
0x0320:   Name: GLIBC_2.2.5  Flags: none  Version: 46
0x0330: Version: 1  File: ld-linux-x86-64.so.2  Cnt: 1
0x0340:   Name: GLIBC_2.3  Flags: none  Version: 47

Displaying notes found in: .note.gnu.build-id
Owner                 Data size	Description
GNU                  0x00000014	NT_GNU_BUILD_ID (unique build ID bitstring)
  Build ID: 62b20b479c2f22f9ff04b7e42712e87bb3286629

Displaying notes found in: .note.gnu.gold-version
Owner                 Data size	Description
GNU                  0x00000009	NT_GNU_GOLD_VERSION (gold version)
  Version: gold 1.15

```

**Comment by tilakrayal** [comment]
@gswebspace ,
Is this still an issue?
Could you please update TensorFlow to the latest stable version v.2.7 and let us know if you are facing the same error. Thanks!

**Comment by gswebspace** [comment]
@tilakrayal I don't have access to the odroid hardware anymore, so can't really do much here. That also means that this issue is not longer relevant (for me at least) and can be closed.

I will close this issue for now. If anybody feels this issue is relevant to them, please feel free to open again. Thank you !

**Comment by Aismart20170718** [comment]
i still have this problem，does anyone know how to fix it？my environment is rk3588 ubuntu20.04 tensorflow2.6.2
