### ISSUE TITLE
How to convert ByteBuffer to Bitmap Image?

### ISSUE THREAD

**Issue by nauyan** [tensorflow/tensorflow#34992]
I am working on creating an image super-resolution application that uses a TensorFlow Lite model. The model gives the output Image in the form of ByteBuffer and I convert the ByteBuffer to Bitmap. Next, I display this Bitmap but nothing shows up. The code I am using can be seen below:

```
ByteBuffer out = ByteBuffer.allocate(4 * 384 * 384 * 3);
tflite.run(byteBuffer,out);

byte[] imageBytes= new byte[out.remaining()];
out.get(imageBytes);
final Bitmap outPut_Image = BitmapFactory.decodeByteArray(imageBytes,0,imageBytes.length);
//Toast.makeText(this,tflite.toString(),Toast.LENGTH_LONG).show();
Toast.makeText(this, "Working",Toast.LENGTH_LONG).show();
ImageView imageView = (ImageView) this.findViewById(R.id.imageView2);
imageView.setImageBitmap(outPut_Image);
```
Please advise me what I am doing wrong here.

**Comment by bilalsoomro** [comment]
This is how I convert ByteBuffer to Bitmap. Just convert it to Java and it should work.

```
private fun getOutputImage(): Bitmap {
    output?.rewind() // Rewind the output buffer after running.

    val bitmap = Bitmap.createBitmap(outputWidth, outputHeight, Bitmap.Config.ARGB_8888)
    val pixels = IntArray(outputWidth * outputHeight) // Set your expected output's height and width
    for (i in 0 until outputWidth * outputHeight) {
        val a = 0xFF
        val r: Float = output?.float!! * 255.0f
        val g: Float = output?.float!! * 255.0f
        val b: Float = output?.float!! * 255.0f
        pixels[i] = a shl 24 or (r.toInt() shl 16) or (g.toInt() shl 8) or b.toInt()
    }
    bitmap.setPixels(pixels, 0, outputWidth, 0, 0, outputWidth, outputHeight)

    return bitmap
}
```

**Comment by nauyan** [comment]
@bilalsoomro  I have converted the  above code to Java the code becomes

```
private Bitmap getBitmapFromAsset(Context context, String filePath) {
        AssetManager assetManager = context.getAssets();

        InputStream istr;
        Bitmap bitmap = null;
        try {
            istr = assetManager.open(filePath);
            bitmap = BitmapFactory.decodeStream(istr);
        } catch (IOException e) {
            // handle exception
        }

        return bitmap;
    }
```

After running this code I do get an output Image but the output isn't meaningful i.e output is a noisy image.

**Comment by nauyan** [comment]
I have posted the output on StackOverflow question have a look at it https://stackoverflow.com/questions/59284342/conversion-bytebuffer-to-image-give-noisy-output

**Comment by bilalsoomro** [comment]
@nauyan I am not entirely sure about your conversion. I gave it a shot. Try this....

```
private Bitmap getOutputImage(ByteBuffer output){
        output.rewind();

        int outputWidth = 384;
        int outputHeight = 384;
        Bitmap bitmap = Bitmap.createBitmap(outputWidth, outputHeight, Bitmap.Config.RGB_565);
        int [] pixels = new int[outputWidth * outputHeight];
        for (int i = 0; i < outputWidth * outputHeight; i++) {
            int a = 0xFF;

            float r = output.getFloat() * 255.0f;
            float g = output.getFloat() * 255.0f;
            float b = output.getFloat() * 255.0f;

            pixels[i] = a << 24 | ((int) r << 16) | ((int) g << 8) | (int) b;
        }
        bitmap.setPixels(pixels, 0, outputWidth, 0, 0, outputWidth, outputHeight);
        return bitmap;
    }
```

**Comment by nauyan** [comment]
@bilalsoomro I still I getting the same output of the generated image.

**Comment by terryheo** [comment]
@nauyan int is 32bit in Java. If you want to use int type for a pixel, you need to convert it to ARGB8888 instead of RGB565 which is 16bit.

**Comment by nauyan** [comment]
@terryheo still getting a noisy image.

**Comment by terryheo** [comment]
@nauyan could you share the code you used for ARGB8888?

**Comment by nauyan** [comment]
@terryheo here is the code

```
private Bitmap getOutputImage(ByteBuffer output){
        output.rewind();

        int outputWidth = 384;
        int outputHeight = 384;
        Bitmap bitmap = Bitmap.createBitmap(outputWidth, outputHeight, Bitmap.Config.ARGB_8888);
        int [] pixels = new int[outputWidth * outputHeight];
        for (int i = 0; i < outputWidth * outputHeight; i++) {
            int a = 0xFF;

            float r = output.getFloat() * 255.0f;
            float g = output.getFloat() * 255.0f;
            float b = output.getFloat() * 255.0f;

            pixels[i] = a << 24 | ((int) r << 16) | ((int) g << 8) | (int) b;
        }
        bitmap.setPixels(pixels, 0, outputWidth, 0, 0, outputWidth, outputHeight);
        return bitmap;
    }
```

**Comment by terryheo** [comment]
@nauyan I think you'd better check the output type and shape of your model again.

The following code might be helpful for you.
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/experimental/support/java/src/java/org/tensorflow/lite/support/image/ImageConversions.java#L44

**Comment by nauyan** [comment]
@terryheo  I did use functions that you have mentioned above my code is: 

```
       try {
            tflite = new Interpreter(loadModelFile(MainActivity.this, "model.tflite"));
            Bitmap testImage = getBitmapFromAsset(this,"Image.png");
            TensorBuffer test_tensor = TensorBuffer.createFixedSize(new int[]{96, 96, 3}, DataType.UINT8);
            Bitmap out =Bitmap.createBitmap(384,
                         384, Bitmap.Config.ARGB_8888);
            TensorBuffer output_tensor = TensorBuffer.createFixedSize(new int[]{384, 384, 3}, DataType.UINT8);
            tflite.run(test_tensor,output_tensor);
            convertTensorBufferToBitmap(output_tensor,out);
        } catch (IOException e) {
            Toast.makeText(this,"Error",Toast.LENGTH_LONG).show();
            e.printStackTrace();
        }

    static void convertTensorBufferToBitmap(TensorBuffer buffer, Bitmap bitmap) {
        if (buffer.getDataType() != DataType.UINT8) {
            // We will add support to FLOAT format conversion in the future, as it may need other configs.
            throw new UnsupportedOperationException(String.format(
                    "Converting TensorBuffer of type %s to Bitmap is not supported yet.",
                    buffer.getDataType()));
        }
        int[] shape = buffer.getShape();
        if (shape.length != 3 || shape[0] <= 0 || shape[1] <= 0 || shape[2] != 3) {
            throw new IllegalArgumentException(String.format(
                    "Buffer shape %s is not valid. 3D TensorBuffer with shape [w, h, 3] is required",
                    Arrays.toString(shape)));
        }
        int h = shape[0];
        int w = shape[1];
        if (bitmap.getWidth() != w || bitmap.getHeight() != h) {
            throw new IllegalArgumentException(String.format(
                    "Given bitmap has different width or height %s with the expected ones %s.",
                    Arrays.toString(new int[]{bitmap.getWidth(), bitmap.getHeight()}),
                    Arrays.toString(new int[]{w, h})));
        }
        if (!bitmap.isMutable()) {
            throw new IllegalArgumentException("Given bitmap is not mutable");
        }
        // TODO(b/138904567): Find a way to avoid creating multiple intermediate buffers every time.
        int[] intValues = new int[w * h];
        int[] rgbValues = buffer.getIntArray();
        for (int i = 0, j = 0; i < intValues.length; i++) {
            byte r = (byte) rgbValues[j++];
            byte g = (byte) rgbValues[j++];
            byte b = (byte) rgbValues[j++];
            intValues[i] = ((r << 16) | (g << 8) | b);
        }
        bitmap.setPixels(intValues, 0, w, 0, 0, w, h);
    }

    static void convertBitmapToTensorBuffer(Bitmap bitmap, TensorBuffer buffer) {
        int w = bitmap.getWidth();
        int h = bitmap.getHeight();
        int[] intValues = new int[w * h];
        bitmap.getPixels(intValues, 0, w, 0, 0, w, h);
        // TODO(b/138904567): Find a way to avoid creating multiple intermediate buffers every time.
        int[] rgbValues = new int[w * h * 3];
        for (int i = 0, j = 0; i < intValues.length; i++) {
            rgbValues[j++] = ((intValues[i] >> 16) & 0xFF);
            rgbValues[j++] = ((intValues[i] >> 8) & 0xFF);
            rgbValues[j++] = (intValues[i] & 0xFF);
        }
        int[] shape = new int[] {h, w, 3};
        buffer.loadArray(rgbValues, shape);
    }

```

This is a snippet of my code and I still am getting an error:
```

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.edsr, PID: 14650
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.edsr/com.example.edsr.MainActivity}: java.lang.IllegalArgumentException: DataType error: cannot resolve DataType of org.tensorflow.lite.support.tensorbuffer.TensorBufferUint8
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
     Caused by: java.lang.IllegalArgumentException: DataType error: cannot resolve DataType of org.tensorflow.lite.support.tensorbuffer.TensorBufferUint8
        at org.tensorflow.lite.Tensor.dataTypeOf(Tensor.java:255)
        at org.tensorflow.lite.Tensor.throwIfTypeIsIncompatible(Tensor.java:313)
        at org.tensorflow.lite.Tensor.getInputShapeIfDifferent(Tensor.java:218)
        at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:135)
        at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:296)
        at org.tensorflow.lite.Interpreter.run(Interpreter.java:259)
        at com.example.edsr.MainActivity.onCreate(MainActivity.java:97)
        at android.app.Activity.performCreate(Activity.java:6975)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6541) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
Process 14650 terminated.
```

**Comment by NEBOLISA** [comment]
I have a model of input type float 32 how can I convert bitmap to bytebuffer for such type of model. Cos I used the convertBitmapToByteBuffer method I got from here but it is giving an arrayoutofindexbound error. So I noticed that the input type for my model (flaot32) differed from most model input types(int)

**Comment by gowthamkpr** [comment]
@NEBOLISA  You cantake a look at the following [guide](https://www.codetd.com/en/article/13876629) to convert Bitmap to ByteBuffer in tensorflow lite android

**Comment by Junacik99** [comment]
Hopefully this will help someone. I was having trouble with displaying results from the mediapipe image segmentation in Kotlin. Segmentation results were in form of bytebuffer size height*width bytes. Each byte in the buffer represents a category mask, so transferring it to the bitmap of type ARGB would not work, since it requires 4 bytes per pixel. To change it to bitmap I had to assign a color to each pixel separately:
`
// Get mask as byte buffer
val mask = bundle.results
mask.rewind()

// Create final bitmap
// Assign colors to each pixel based on the category
val finalBitmap = createBitmap(width, height, Bitmap.Config.ARGB_8888)
for (i in 0 until finalBitmap.width * finalBitmap.height) {
    val color = /* logic for assigning the color */
    finalBitmap[i % finalBitmap.width, i / finalBitmap.width] = color
}
`
width and height are desired resolution of the bitmap

Also if I wouldn't need the color, just wanted to convert my bytearray to bitmap with only 1 Byte per pixel, I could use:
`val finalBitmap = createBitmap(width, height, Bitmap.Config.ALPHA_8)
finalBitmap.copyPixelsFromBuffer(mask)
`

Notice the bitmap config option. ARGB_8888 stands for 8 bites (1 byte) times 4 channels. But since in my case there is only 1 byte per pixel, I would need to either transform it to a ARGB color or use just one channel - ALPHA_8.
