### ISSUE TITLE
tensorflow 2.0 use ParameterServerStrategy error

### ISSUE THREAD

**Issue by Crisescode** [tensorflow/tensorflow#35017]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**

* **use tensorflow docker hub images:  tensorflow / tensorflow : 2.0.0-gpu**

**Describe the current behavior**
* when i use tf2.0 distributed training with ParameterServerStrategy,  the error occurred follow:
```
2019-12-11 14:53:27.569524: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2019-12-11 14:53:27.619245: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties:
name: Tesla P100-PCIE-16GB major: 6 minor: 0 memoryClockRate(GHz): 1.3285
pciBusID: 0000:2f:00.0
2019-12-11 14:53:27.621064: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 1 with properties:
name: Tesla P100-PCIE-16GB major: 6 minor: 0 memoryClockRate(GHz): 1.3285
pciBusID: 0000:86:00.0
2019-12-11 14:53:27.622349: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2019-12-11 14:53:27.627608: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2019-12-11 14:53:27.632513: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2019-12-11 14:53:27.634123: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2019-12-11 14:53:27.640466: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2019-12-11 14:53:27.643992: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2019-12-11 14:53:27.656264: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2019-12-11 14:53:27.660960: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0, 1
2019-12-11 14:53:27.661734: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2019-12-11 14:53:27.676662: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2600000000 Hz
2019-12-11 14:53:27.684246: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x565309993340 executing computations on platform Host. Devices:
2019-12-11 14:53:27.684288: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
2019-12-11 14:53:27.955807: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5653099f5a60 executing computations on platform CUDA. Devices:
2019-12-11 14:53:27.955947: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Tesla P100-PCIE-16GB, Compute Capability 6.0
2019-12-11 14:53:27.955978: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (1): Tesla P100-PCIE-16GB, Compute Capability 6.0
2019-12-11 14:53:27.958412: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties:
name: Tesla P100-PCIE-16GB major: 6 minor: 0 memoryClockRate(GHz): 1.3285
pciBusID: 0000:2f:00.0
2019-12-11 14:53:27.959282: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 1 with properties:
name: Tesla P100-PCIE-16GB major: 6 minor: 0 memoryClockRate(GHz): 1.3285
pciBusID: 0000:86:00.0
2019-12-11 14:53:27.959338: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2019-12-11 14:53:27.959361: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2019-12-11 14:53:27.959381: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2019-12-11 14:53:27.959391: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2019-12-11 14:53:27.959413: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2019-12-11 14:53:27.959423: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2019-12-11 14:53:27.959434: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2019-12-11 14:53:27.962606: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0, 1
2019-12-11 14:53:27.962639: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2019-12-11 14:53:27.964634: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-12-11 14:53:27.964653: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 1
2019-12-11 14:53:27.964663: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N Y
2019-12-11 14:53:27.964679: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 1:   Y N
2019-12-11 14:53:27.967224: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 15216 MB memory) -> physical GPU (device: 0, name: Tesla P100-PCIE-16GB, pci bus id: 0000:2f:00.0, compute capability: 6.0)
2019-12-11 14:53:27.968872: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 15216 MB memory) -> physical GPU (device: 1, name: Tesla P100-PCIE-16GB, pci bus id: 0000:86:00.0, compute capability: 6.0)
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/tensorflow_core/python/ops/resource_variable_ops.py:1630: calling __init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
Traceback (most recent call last):
  File "tf_mnist_ps_worker.py", line 136, in <module>
    main()
  File "tf_mnist_ps_worker.py", line 132, in main
    app.train(args)
  File "tf_mnist_ps_worker.py", line 85, in train
    model = Net().model
  File "tf_mnist_ps_worker.py", line 32, in __init__
    tf.keras.layers.Dense(10, activation='softmax')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/training/tracking/base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/keras/engine/sequential.py", line 114, in __init__
    self.add(layer)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/training/tracking/base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/keras/engine/sequential.py", line 196, in add
    output_tensor = layer(self.outputs[0])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/keras/engine/base_layer.py", line 817, in __call__
    self._maybe_build(inputs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/keras/engine/base_layer.py", line 2141, in _maybe_build
    self.build(input_shapes)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/keras/layers/core.py", line 1027, in build
    trainable=True)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/keras/engine/base_layer.py", line 2311, in __setattr__
    if val.trainable:
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/ops/variables.py", line 477, in trainable
    raise NotImplementedError
NotImplementedError
```

**Code to reproduce the issue**
* my demo code:
```
import os
import json
import argparse

import tensorflow as tf
from tensorflow.keras import datasets
from tensorflow.keras import layers, models
from tensorflow.keras import optimizers

class Net(object):
    def __init__(self):
        model = models.Sequential()
        model.add(layers.Conv2D(
            32, (3, 3), activation='relu', input_shape=(28, 28, 1)))
        model.add(layers.MaxPooling2D((2, 2)))
        model.add(layers.Conv2D(64, (3, 3), activation='relu'))
        model.add(layers.MaxPooling2D((2, 2)))
        model.add(layers.Conv2D(64, (3, 3), activation='relu'))

        model.add(layers.Flatten())
        model.add(layers.Dense(64, activation='relu'))
        model.add(layers.Dense(10, activation='softmax'))

        model.summary()

        self.model = model


# inital dateset
class DataSet(object):
    def __init__(self):
        data_path = os.path.dirname(os.path.realpath(__file__)) \
                    + '/../../datasets/mnist/mnist.npz'
        (train_images, train_labels), (test_images, test_labels) = \
            datasets.mnist.load_data(path=data_path)
        train_images = train_images.reshape((60000, 28, 28, 1))
        test_images = test_images.reshape((10000, 28, 28, 1))

        train_images, test_images = train_images / 255.0, test_images / 255.0

        self.train_images, self.train_labels = train_images, train_labels
        self.test_images, self.test_labels = test_images, test_labels


# train and val
class Train:
    def __init__(self):
        self.data = DataSet()

    def train(self, args):
        # Define the checkpoint directory to store the checkpoints
        checkpoint_dir = args.train_dir
        # Name of the checkpoint files
        checkpoint_path = os.path.join(checkpoint_dir, "ckpt_{epoch}")

        callbacks = [
            tf.keras.callbacks.TensorBoard(log_dir='./logs'),
            tf.keras.callbacks.ModelCheckpoint(filepath=checkpoint_path,
                                               save_weights_only=True),
        ]

        with strategy.scope():
            model = Net().model

            model.compile(optimizer=optimizers.Adam(),
                          loss='sparse_categorical_crossentropy',
                          metrics=['accuracy'])

        model.fit(self.data.train_images, self.data.train_labels,
                  batch_size=args.batch_size,
                  epochs=args.epochs,
                  callbacks=callbacks,
                  validation_data=(self.data.test_images, self.data.test_labels))

        # EVAL
        model.load_weights(tf.train.latest_checkpoint(checkpoint_dir))
        eval_loss, eval_acc = model.evaluate(
            self.data.test_images, self.data.test_labels, verbose=2)
        print('Eval loss: {}, Eval Accuracy: {}'.format(eval_loss, eval_acc))


def main():
    # training params settings
    parser = argparse.ArgumentParser(description='Tensorflow 2.0 MNIST Example,'
                                                 ' use Mirrorstrategy')
    parser.add_argument('--batch_size', '-b', type=int, default=64,
                        help='input batch size for training (default: 64)')
    parser.add_argument('--test_batchsize', '-tb', type=int, default=1000,
                        help='input batch size for testing (default: 1000)')
    parser.add_argument('--epochs', '-e', type=int, default=10,
                        help='number of epochs to train (default: 10)')
    parser.add_argument('--learning_rate', '-lr', type=float, default=0.01,
                        help='learning rate (default: 0.01)')
    parser.add_argument('--momentum', type=float, default=0.5,
                        help='SGD momentum (default: 0.5)')
    parser.add_argument('--log_interval', type=int, default=10,
                        help='how many batches to wait before logging training status')
    parser.add_argument('--save_model', '-sm', action='store_true', default=False,
                        help='For Saving the current Model')

    args = parser.parse_args()

    app = Train()
    app.train(args)


if __name__ == "__main__":
   main()
```

* and my cmd line:

```
TF_CONFIG='{"cluster": {"worker": ["10.240.208.106:12345", "10.240.208.108:12345"], "ps": ["10.240.208.106:12346", "10.240.208.108:12346"]}, "task": {"index": 1, "type": "worker"}}' python tf_mnist_ps_worker.py
```

**Comment by ymodak** [comment]
This should be fixed now that the associated PR has been merged. Thanks!

**Comment by Crisescode** [comment]
thanks for you comment. Please allow me to ask whether the above PR is merged by the current master branch? Should i use the master branch code to verify my issue?

**Comment by nikitamaia** [comment]
Hi @Crisescode, it looks like you are trying to use Keras with ParameterServerStrategy. Note that this is not currently possible, but is planned to be supported planned post 2.3. You can refer to the [chart here](https://www.tensorflow.org/guide/distributed_training#types_of_strategies) to see what is currently supported.
