### ISSUE TITLE
Error when no GPU available in TensorFlow 2.1.0rc1

### ISSUE THREAD

**Issue by drasmuss** [tensorflow/tensorflow#35036]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.1.0rc1
- Python version: 3.6.9
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**

Installing `tensorflow==2.1.0rc1` and trying to `import tensorflow` results in an error if there is no GPU set up on the machine.

**Describe the expected behavior**

In `tensorflow==2.1.0rc0` this simply results in a warning

```
2019-12-11 14:50:44.677649: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2019-12-11 14:50:44.684212: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
```

This should have the same warning message in 2.1.0rc1, rather than crashing.

**Code to reproduce the issue**

```
import tensorflow
```

**Other info / logs**
```
ImportError: Traceback (most recent call last):
  File "...\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "...\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "...\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "...\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "...\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

**Comment by gunan** [comment]
@yifeif @goldiegadde looks like we have a potential regression?
Could one of you confirm this?

**Comment by angerson** [comment]
I wasn't able to reproduce this on Windows 2019 Server on either Python 3.7.4 or Python 3.6.8, after uninstalling both CUDA and Visual Studio 2017 Build Tools.

```
$ /c/Python37/python -m pip install --user tensorflow==2.1.0rc1
$ /c/Python37/python
Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
2019-12-11 23:32:39.760755: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2019-12-11 23:32:39.766966: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
>>> tf.__version__
'2.1.0-rc1'
```

```
$ /c/Python36/python -m pip install --user tensorflow==2.1.0rc1
$ /c/Python36/python
Python 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
2019-12-11 23:36:16.730995: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2019-12-11 23:36:16.737279: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
>>> tf.__version__
'2.1.0-rc1'
```

I did have to install as `--user`, however. Perhaps there is an underlying permissions issue?

**Comment by drasmuss** [comment]
You can see the issue reproducing in this appveyor build, if that helps https://ci.appveyor.com/project/nengo/nengo-dl/builds/29482767/job/8054ac3871y174vn#L503

**Comment by micahr123** [comment]
Have the exact same issue.

**Comment by angerson** [comment]
That's very interesting. @micahr123, can you tell us the same system information as @drasmuss provided in the initial report?

**Comment by angerson** [comment]
Okay, I was able to reproduce this on a plainer image. It appears that building with VS 2019 updates the Windows-required Visual C++ Redistributable version to the one on the [latest redistibutable](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads) page, whereas older versions of the redistributable would work on older packages.

Didn't install anything:
```
>>> import tensorflow as tf
Traceback (most recent call last):
  File "C:\Users\kbuilder\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\platform\self_check.py", line 47, in preload_check
    ctypes.WinDLL(build_info.msvcp_dll_name)
  File "C:\Users\kbuilder\AppData\Local\Programs\Python\Python37\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\kbuilder\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\__init__.py", line 101, in <module>
    from tensorflow_core import *
  File "C:\Users\kbuilder\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\kbuilder\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\Users\kbuilder\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "C:\Users\kbuilder\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\kbuilder\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\kbuilder\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 30, in <module>
    self_check.preload_check()
  File "C:\Users\kbuilder\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\platform\self_check.py", line 55, in preload_check
    % build_info.msvcp_dll_name)
ImportError: Could not find 'msvcp140.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. You may install this DLL by downloading Visual C++ 2015 Redistributable Update 3 from this URL: https://www.microsoft.com/en-us/download/details.aspx?id=53587
```

Installed [Visual C++ 2015 Redistributable Update 3](https://www.microsoft.com/en-us/download/confirmation.aspx?id=53587)
```
>>> import tensorflow as tf
Traceback (most recent call last):
  File "C:\Users\kbuilder\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\kbuilder\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\kbuilder\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\kbuilder\AppData\Local\Programs\Python\Python37\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\kbuilder\AppData\Local\Programs\Python\Python37\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\kbuilder\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\__init__.py", line 101, in <module>
    from tensorflow_core import *
  File "C:\Users\kbuilder\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\__init__.py", line 42, in <module>
    from . _api.v2 import audio
  File "C:\Users\kbuilder\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\_api\v2\audio\__init__.py", line 10, in <module>
    from tensorflow.python.ops.gen_audio_ops import decode_wav
  File "C:\Users\kbuilder\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\ops\gen_audio_ops.py", line 9, in <module>
    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow
  File "C:\Users\kbuilder\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\Users\kbuilder\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "C:\Users\kbuilder\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\kbuilder\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\kbuilder\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\kbuilder\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\kbuilder\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\kbuilder\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\kbuilder\AppData\Local\Programs\Python\Python37\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\kbuilder\AppData\Local\Programs\Python\Python37\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

Installed [Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads)
```
>>> import tensorflow as tf
2019-12-13 20:29:52.375565: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2019-12-13 20:29:52.381257: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
>>>
```

@blamb The docs on tensorflow.org/install don't seem to mention anything about installing the redistributable, would that be a useful thing to add?

Unfortunately I don't understand the way this checker works myself, so I don't know what we need to do to additionally search for the correct .dll.

**Comment by angerson** [comment]
That is, you can resolve this by installing [the new redistributable package](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads), but we need to update TensorFlow to ensure it checks for all the necessary DLLs on import.

**Comment by micahr123** [comment]
It worked for me! Thanks.

**Comment by drasmuss** [comment]
So RC1 was built with VS 2019, which is what caused the change from RC0?

**Comment by angerson** [comment]
>So RC1 was built with VS 2019, which is what caused the change from RC0?
That's correct.

**Comment by ChristianOlmosUSA** [comment]
This didn't work for me? Any other ideas? ("you can resolve this by installing the new redistributable package, but we need to update TensorFlow to ensure it checks for all the necessary DLLs on import"). I don't have a GPU.

2020-07-23 23:23:51.875741: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-07-23 23:23:51.880431: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.

**Comment by gunan** [comment]
The log lines you see are simply informational. TF simply can run without issues despite those.

If you do not want to see those errors on machines without GPU, you can simply install tensorflow-cpu pip package.

**Comment by miladforte** [comment]
@gunan so i f i get these two lines i just don't care and continue with my work ? 
>>> import tensorflow as tf
W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
 I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
