### ISSUE TITLE
TF2.1 Unable to load model in h5-Format

### ISSUE THREAD

**Issue by fischeru** [tensorflow/tensorflow#35057]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian 9.11
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.1.0-rc1 CPU
- Python version: 3.5
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I create, compile, fit and then save a tf.keras.Model the following way:

```
import numpy as np
import tensorflow as tf
import tensorflow.keras.layers as layers
import tensorflow.keras.backend as K


def density_model(input_shape, n_clusters):

    input_layer = layers.Input(shape=input_shape)

    y = input_layer

    y = layers.Conv1D(32, 10, 2, padding='same', kernel_initializer='he_uniform')(y)
    y = layers.BatchNormalization()(y)
    y = layers.Activation('relu')(y)

    y = layers.Conv1D(32, 5, 2, padding='same', kernel_initializer='he_uniform')(y)
    y = layers.BatchNormalization()(y)
    y = layers.Activation('relu')(y)

    y = layers.Conv1D(16, 3, 2, padding='same', kernel_initializer='he_uniform')(y)
    y = layers.BatchNormalization()(y)
    y = layers.Activation('relu')(y)

    y = layers.Flatten()(y)

    # mixture coefficients
    alpha = layers.Dense(n_clusters, activation=None)(y)
    alpha = layers.Softmax(name='coeff')(alpha)

    # mean
    mu = layers.Dense(n_clusters, activation=None, name='mu')(y)

    # stddev
    sigma = layers.Dense(n_clusters, activation=None)(y)
    sigma = layers.Lambda(tf.keras.backend.exp, name='sigma')(sigma)

    out = layers.Concatenate(axis=1)([alpha, mu, sigma])

    model = tf.keras.models.Model(input_layer, out)

    return model


class LogLikelihood(tf.keras.losses.Loss):
    def __init__(self, n_clusters):
        super(LogLikelihood, self).__init__()
        self.n_clusters = n_clusters

    def call(self, y_true, y_pred):

        eps = 0.00001

        alpha = K.expand_dims(y_pred[:, 0:self.n_clusters], axis=1)
        mu = K.expand_dims(y_pred[:, self.n_clusters:2*self.n_clusters], axis=1)
        sigma = K.expand_dims(y_pred[:, 2*self.n_clusters:3*self.n_clusters], axis=1)

        y = K.expand_dims(y_true, axis=-1)

        # 1/(2*pi)**0.5 = 0.398...
        coeff = 0.4*alpha/sigma
        exponent = -0.5*K.square((y-mu)/sigma)

        density = K.sum(coeff*K.exp(exponent), axis=-1)
        log_density = -K.log(density+eps)
        log_likelihood = K.sum(log_density, axis=-1)

        return K.mean(log_likelihood)

if __name__ == '__main__':

    train_data = np.random.normal(loc=0.0, scale=1.0, size=1000*100).reshape((1000, 100, 1))
    train_target = np.random.normal(loc=1.0, scale=2.0, size=1000*100).reshape((1000, 100))

    model = density_model(input_shape=(100, 1), n_clusters=2)

    model.compile(
        optimizer=tf.keras.optimizers.SGD(learning_rate=0.001),
        loss=LogLikelihood(n_clusters=2)
    )

    model.fit(x=train_data, y=train_target, batch_size=32, epochs=1, verbose=0)

    model.save('./density_h5', save_format='h5', include_optimizer=False)
```

All works fine until here. Since I am using a custom Loss and I don't want to deal with the trouble of loading it, I am specifying 'include_optimizer=False' when saving. My model is pretty straightforward, apart from using a Lambda-Layer.

However I cannot load the model. 

```
import tensorflow as tf

model = tf.keras.models.load_model('./density_h5', custom_objects={'tf': tf}, compile=False)
```

gives the following error:

Traceback (most recent call last):
  File "/data1/fischeru/MY_PYTHON_PROJECTS/quar/env/lib/python3.5/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 842, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "/data1/fischeru/MY_PYTHON_PROJECTS/quar/env/lib/python3.5/site-packages/tensorflow_core/python/keras/layers/core.py", line 593, in call
    outputs.set_shape(self.compute_output_shape(inputs.shape))
  File "/data1/fischeru/MY_PYTHON_PROJECTS/quar/env/lib/python3.5/site-packages/tensorflow_core/python/keras/layers/core.py", line 601, in compute_output_shape
    if all(input_shape[1:]):
  File "/data1/fischeru/MY_PYTHON_PROJECTS/quar/env/lib/python3.5/site-packages/tensorflow_core/python/framework/ops.py", line 765, in __bool__
    self._disallow_bool_casting()
  File "/data1/fischeru/MY_PYTHON_PROJECTS/quar/env/lib/python3.5/site-packages/tensorflow_core/python/framework/ops.py", line 534, in _disallow_bool_casting
    self._disallow_in_graph_mode("using a `tf.Tensor` as a Python `bool`")
  File "/data1/fischeru/MY_PYTHON_PROJECTS/quar/env/lib/python3.5/site-packages/tensorflow_core/python/framework/ops.py", line 523, in _disallow_in_graph_mode
    " this function with @tf.function.".format(task))
tensorflow.python.framework.errors_impl.OperatorNotAllowedInGraphError: using a `tf.Tensor` as a Python `bool` is not allowed in Graph execution. Use Eager execution or decorate this function with @tf.function.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fischeru/.PyCharmCE2017.2/config/scratches/scratch_9.py", line 3, in <module>
    model = tf.keras.models.load_model('./density_h5', custom_objects={'tf': tf}, compile=False)
  File "/data1/fischeru/MY_PYTHON_PROJECTS/quar/env/lib/python3.5/site-packages/tensorflow_core/python/keras/saving/save.py", line 146, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
  File "/data1/fischeru/MY_PYTHON_PROJECTS/quar/env/lib/python3.5/site-packages/tensorflow_core/python/keras/saving/hdf5_format.py", line 168, in load_model_from_hdf5
    custom_objects=custom_objects)
  File "/data1/fischeru/MY_PYTHON_PROJECTS/quar/env/lib/python3.5/site-packages/tensorflow_core/python/keras/saving/model_config.py", line 55, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/data1/fischeru/MY_PYTHON_PROJECTS/quar/env/lib/python3.5/site-packages/tensorflow_core/python/keras/layers/serialization.py", line 102, in deserialize
    printable_module_name='layer')
  File "/data1/fischeru/MY_PYTHON_PROJECTS/quar/env/lib/python3.5/site-packages/tensorflow_core/python/keras/utils/generic_utils.py", line 191, in deserialize_keras_object
    list(custom_objects.items())))
  File "/data1/fischeru/MY_PYTHON_PROJECTS/quar/env/lib/python3.5/site-packages/tensorflow_core/python/keras/engine/network.py", line 906, in from_config
    config, custom_objects)
  File "/data1/fischeru/MY_PYTHON_PROJECTS/quar/env/lib/python3.5/site-packages/tensorflow_core/python/keras/engine/network.py", line 1852, in reconstruct_from_config
    process_node(layer, node_data)
  File "/data1/fischeru/MY_PYTHON_PROJECTS/quar/env/lib/python3.5/site-packages/tensorflow_core/python/keras/engine/network.py", line 1799, in process_node
    output_tensors = layer(input_tensors, **kwargs)
  File "/data1/fischeru/MY_PYTHON_PROJECTS/quar/env/lib/python3.5/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 854, in __call__
    str(e) + '\n"""')
TypeError: You are attempting to use Python control flow in a layer that was not declared to be dynamic. Pass `dynamic=True` to the class constructor.
Encountered error:
"""
using a `tf.Tensor` as a Python `bool` is not allowed in Graph execution. Use Eager execution or decorate this function with @tf.function.
"""

**Describe the expected behavior**
I expect to be able to load the model. As far as I know the "custom_objects={'tf': tf}" should take care of the Lambda-Layer. And since I explicitely did not include the optimizer, my custom loss should also not make any trouble. 

**Code to reproduce the issue**
see above

**Other info / logs**
see anove

**Comment by fischeru** [comment]
Sorry, found the problem. Seems that one must use tf.math.exp instead of tf.keras.backend.exp.
No clue why, but it solves the issue.
