### ISSUE TITLE
InvalidArgumentError: indices[6] = 3712 is not in [0, 3592)

### ISSUE THREAD

**Issue by allen-DM** [tensorflow/tensorflow#35074]
File "C:\Users\Allen\Anaconda3\lib\site-packages\tensorflow_core\python\client\session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)

InvalidArgumentError: indices[6] = 3712 is not in [0, 3592)

**Comment by allen-DM** [comment]
this all messages:

runfile('C:/Users/Allen/7-15  train.py', wdir='C:/Users/Allen')
Reloaded modules: 7-14  MKR, 7-16  data_loader
reading rating file ...
splitting dataset ...
reading KG file ...
data loaded.
Traceback (most recent call last):

  File "<ipython-input-22-55c5f394f6c2>", line 1, in <module>
    runfile('C:/Users/Allen/7-15  train.py', wdir='C:/Users/Allen')

  File "C:\Users\Allen\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\Users\Allen\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/Allen/7-15  train.py", line 149, in <module>
    train(args, data, show_loss, show_topk) #进行训练及评估

  File "C:/Users/Allen/7-15  train.py", line 33, in train
    _, loss = model.train_rs(sess, get_feed_dict_for_rs(model, train_data, start, start + args.batch_size))

  File "C:\Users\Allen\Desktop\TensorFlow_Engineering_Implementation-master\code\7-14  MKR.py", line 154, in train_rs
    return sess.run([self.optimizer_rs, self.loss_rs], feed_dict)

  File "C:\Users\Allen\Anaconda3\lib\site-packages\tensorflow_core\python\client\session.py", line 956, in run
    run_metadata_ptr)

  File "C:\Users\Allen\Anaconda3\lib\site-packages\tensorflow_core\python\client\session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)

  File "C:\Users\Allen\Anaconda3\lib\site-packages\tensorflow_core\python\client\session.py", line 1359, in _do_run
    run_metadata)

  File "C:\Users\Allen\Anaconda3\lib\site-packages\tensorflow_core\python\client\session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)

InvalidArgumentError: indices[6] = 3712 is not in [0, 3592)
	 [[node embedding_lookup_1 (defined at C:\Users\Allen\Anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py:1751) ]]

Original stack trace for 'embedding_lookup_1':
  File "C:\Users\Allen\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Allen\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Allen\Anaconda3\lib\site-packages\spyder_kernels\console\__main__.py", line 11, in <module>
    start.main()
  File "C:\Users\Allen\Anaconda3\lib\site-packages\spyder_kernels\console\start.py", line 318, in main
    kernel.start()
  File "C:\Users\Allen\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 505, in start
    self.io_loop.start()
  File "C:\Users\Allen\Anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 148, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\Allen\Anaconda3\lib\asyncio\base_events.py", line 539, in run_forever
    self._run_once()
  File "C:\Users\Allen\Anaconda3\lib\asyncio\base_events.py", line 1775, in _run_once
    handle._run()
  File "C:\Users\Allen\Anaconda3\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Allen\Anaconda3\lib\site-packages\tornado\ioloop.py", line 690, in <lambda>
    lambda f: self._run_callback(functools.partial(callback, future))
  File "C:\Users\Allen\Anaconda3\lib\site-packages\tornado\ioloop.py", line 743, in _run_callback
    ret = callback()
  File "C:\Users\Allen\Anaconda3\lib\site-packages\tornado\gen.py", line 787, in inner
    self.run()
  File "C:\Users\Allen\Anaconda3\lib\site-packages\tornado\gen.py", line 748, in run
    yielded = self.gen.send(value)
  File "C:\Users\Allen\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 365, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "C:\Users\Allen\Anaconda3\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\Users\Allen\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 272, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "C:\Users\Allen\Anaconda3\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\Users\Allen\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 542, in execute_request
    user_expressions, allow_stdin,
  File "C:\Users\Allen\Anaconda3\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\Users\Allen\Anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 294, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "C:\Users\Allen\Anaconda3\lib\site-packages\ipykernel\zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "C:\Users\Allen\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2854, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "C:\Users\Allen\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2880, in _run_cell
    return runner(coro)
  File "C:\Users\Allen\Anaconda3\lib\site-packages\IPython\core\async_helpers.py", line 68, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\Allen\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3057, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "C:\Users\Allen\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3248, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "C:\Users\Allen\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3325, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-22-55c5f394f6c2>", line 1, in <module>
    runfile('C:/Users/Allen/7-15  train.py', wdir='C:/Users/Allen')
  File "C:\Users\Allen\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)
  File "C:\Users\Allen\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)
  File "C:/Users/Allen/7-15  train.py", line 149, in <module>
    train(args, data, show_loss, show_topk) #进行训练及评估
  File "C:/Users/Allen/7-15  train.py", line 14, in train
    model = MKR(args, n_user, n_item, n_entity, n_relation)
  File "C:\Users\Allen\Desktop\TensorFlow_Engineering_Implementation-master\code\7-14  MKR.py", line 39, in __init__
    self._build_low_layers(args)
  File "C:\Users\Allen\Desktop\TensorFlow_Engineering_Implementation-master\code\7-14  MKR.py", line 74, in _build_low_layers
    self.item_embeddings = tf.nn.embedding_lookup(self.item_emb_matrix, self.item_indices)
  File "C:\Users\Allen\Anaconda3\lib\site-packages\tensorflow_core\python\ops\embedding_ops.py", line 364, in embedding_lookup_v2
    return embedding_lookup(params, ids, "div", name, max_norm=max_norm)
  File "C:\Users\Allen\Anaconda3\lib\site-packages\tensorflow_core\python\ops\embedding_ops.py", line 317, in embedding_lookup
    transform_fn=None)
  File "C:\Users\Allen\Anaconda3\lib\site-packages\tensorflow_core\python\ops\embedding_ops.py", line 135, in _embedding_lookup_and_transform
    array_ops.gather(params[0], ids, name=name), ids, max_norm)
  File "C:\Users\Allen\Anaconda3\lib\site-packages\tensorflow_core\python\util\dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "C:\Users\Allen\Anaconda3\lib\site-packages\tensorflow_core\python\ops\array_ops.py", line 3967, in gather
    return gen_array_ops.gather_v2(params, indices, axis, name=name)
  File "C:\Users\Allen\Anaconda3\lib\site-packages\tensorflow_core\python\ops\gen_array_ops.py", line 4081, in gather_v2
    batch_dims=batch_dims, name=name)
  File "C:\Users\Allen\Anaconda3\lib\site-packages\tensorflow_core\python\framework\op_def_library.py", line 793, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\Allen\Anaconda3\lib\site-packages\tensorflow_core\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\Users\Allen\Anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3360, in create_op
    attrs, op_def, compute_device)
  File "C:\Users\Allen\Anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3429, in _create_op_internal
    op_def=op_def)
  File "C:\Users\Allen\Anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1751, in __init__
    self._traceback = tf_stack.extract_stack()

**Comment by ravikyram** [comment]
@allen-DM 

Any update on this issue please. Thanks!

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
