### ISSUE TITLE
Failed to build TF2.0 with TensorRT: undefined symbol: _ZN15stream_executor14StreamExecutor18EnablePeerAccessToEPS0_

### ISSUE THREAD

**Issue by jiapei100** [tensorflow/tensorflow#35115]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 19.04
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.0
- Python version: 3.7.3
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): 1.1.0- (@non-git)
- GCC/Compiler version (if compiling from source): gcc (Ubuntu 8.3.0-6ubuntu1) 8.3.0
- CUDA/cuDNN version: 10.2/7.6.5
- GPU model and memory: 
```console
Device 0: "GeForce GTX 980M"
  CUDA Driver Version / Runtime Version          10.2 / 10.2
  CUDA Capability Major/Minor version number:    5.2
  Total amount of global memory:                 4035 MBytes (4231331840 bytes)
  (12) Multiprocessors, (128) CUDA Cores/MP:     1536 CUDA Cores
  GPU Max Clock rate:                            1126 MHz (1.13 GHz)
```

```console
WARNING: ....../tensorflow/python/BUILD:107:1: in py_library rule //tensorflow/python:no_contrib: target '//tensorflow/python:no_contrib' depends on deprecated target '//tensorflow/python/ops/distributions:distributions': TensorFlow Distributions has migrated to TensorFlow Probability (https://github.com/tensorflow/probability). Deprecated copies remaining in tf.distributions will not receive new features, and will be removed by early 2019. You should update all usage of `tf.distributions` to `tfp.distributions`.
INFO: Analyzed target //tensorflow/tools/pip_package:build_pip_package (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: ....../tensorflow/python/keras/api/BUILD:129:1: Executing genrule //tensorflow/python/keras/api:keras_python_api_gen_compat_v2 failed (Exit 1)
Traceback (most recent call last):
  File "~/.cache/bazel/_bazel_longervision/b29adcaa7335b5e3a52f33ba4b4f5496/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_2_keras_python_api_gen_compat_v2.runfiles/org_tensorflow/tensorflow/python/tools/api/generator/create_python_api.py", line 776, in <module>
    main()
  File "~/.cache/bazel/_bazel_longervision/b29adcaa7335b5e3a52f33ba4b4f5496/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_2_keras_python_api_gen_compat_v2.runfiles/org_tensorflow/tensorflow/python/tools/api/generator/create_python_api.py", line 772, in main
    lazy_loading, args.use_relative_imports)
  File "~/.cache/bazel/_bazel_longervision/b29adcaa7335b5e3a52f33ba4b4f5496/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_2_keras_python_api_gen_compat_v2.runfiles/org_tensorflow/tensorflow/python/tools/api/generator/create_python_api.py", line 629, in create_api_files
    compat_api_versions, lazy_loading, use_relative_imports)
  File "~/.cache/bazel/_bazel_longervision/b29adcaa7335b5e3a52f33ba4b4f5496/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_2_keras_python_api_gen_compat_v2.runfiles/org_tensorflow/tensorflow/python/tools/api/generator/create_python_api.py", line 503, in get_api_init_text
    _, attr = tf_decorator.unwrap(attr)
  File "~/.cache/bazel/_bazel_longervision/b29adcaa7335b5e3a52f33ba4b4f5496/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_2_keras_python_api_gen_compat_v2.runfiles/org_tensorflow/tensorflow/python/util/tf_decorator.py", line 219, in unwrap
    elif _has_tf_decorator_attr(cur):
  File "~/.cache/bazel/_bazel_longervision/b29adcaa7335b5e3a52f33ba4b4f5496/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_2_keras_python_api_gen_compat_v2.runfiles/org_tensorflow/tensorflow/python/util/tf_decorator.py", line 124, in _has_tf_decorator_attr
    hasattr(obj, '_tf_decorator') and
  File "~/.cache/bazel/_bazel_longervision/b29adcaa7335b5e3a52f33ba4b4f5496/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_2_keras_python_api_gen_compat_v2.runfiles/org_tensorflow/tensorflow/python/util/lazy_loader.py", line 62, in __getattr__
    module = self._load()
  File "~/.cache/bazel/_bazel_longervision/b29adcaa7335b5e3a52f33ba4b4f5496/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_2_keras_python_api_gen_compat_v2.runfiles/org_tensorflow/tensorflow/python/util/lazy_loader.py", line 45, in _load
    module = importlib.import_module(self.__name__)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "~/.cache/bazel/_bazel_longervision/b29adcaa7335b5e3a52f33ba4b4f5496/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_2_keras_python_api_gen_compat_v2.runfiles/org_tensorflow/tensorflow/compiler/tf2tensorrt/wrap_py_utils.py", line 28, in <module>
    _wrap_py_utils = swig_import_helper()
  File "~/.cache/bazel/_bazel_longervision/b29adcaa7335b5e3a52f33ba4b4f5496/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_2_keras_python_api_gen_compat_v2.runfiles/org_tensorflow/tensorflow/compiler/tf2tensorrt/wrap_py_utils.py", line 24, in swig_import_helper
    _mod = imp.load_module('_wrap_py_utils', fp, pathname, description)
  File "/usr/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 670, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 583, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1043, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: ~/.cache/bazel/_bazel_longervision/b29adcaa7335b5e3a52f33ba4b4f5496/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_2_keras_python_api_gen_compat_v2.runfiles/org_tensorflow/tensorflow/compiler/tf2tensorrt/_wrap_py_utils.so: undefined symbol: _ZN15stream_executor14StreamExecutor18EnablePeerAccessToEPS0_
Target //tensorflow/tools/pip_package:build_pip_package failed to build
ERROR: ....../tensorflow/python/tools/BUILD:98:1 Executing genrule //tensorflow/python/keras/api:keras_python_api_gen_compat_v2 failed (Exit 1)
INFO: Elapsed time: 3.987s, Critical Path: 2.78s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

**Comment by oanush** [comment]
@jiapei100 ,
Thank you for reporting the issue, can you please provide code to reproduce the above error ? Thanks!

**Comment by dbonner** [comment]
I am getting this too building with Ubuntu 18.04, gcc 7.4.0, bazel 1.1.0, CUDA 10.1, CUDNN 7.6.5, Python 3.7.3 conda virtual environment.

**Comment by freedomtan** [comment]
```
$ c++filt  _ZN15stream_executor14StreamExecutor18EnablePeerAccessToEPS0_
stream_executor::StreamExecutor::EnablePeerAccessTo(stream_executor::StreamExecutor*)
```

It seems `stream_executor::StreamExecutor::EnablePeerAccessTo(stream_executor::StreamExecutor*)` is needed but not there.

**Comment by sbaktha** [comment]
@freedomtan Any idea on where to add this?

**Comment by freedomtan** [comment]
@sbaktha I tried a bit, but failed. I was able to add `stream_executor::StreamExecutor::EnablePeerAccessTo(stream_executor::StreamExecutor*)` related binary, but that caused other undefined symbol. It seems building TensorFlow 2.x with TensorRT with bazel 1.x doesn't work. I was able to build and 2.0 and master branch with `bazel 0.2x` before the minimum required bazel version bumped (aaea5414317793a3eedc41f23cc5e619ee5941dc) to 1.0. 

tag @gunan  who increased bazel version according to `git log`

**Comment by gunan** [comment]
@aaroey for tensorrt and @scentini for bazel 1.x

**Comment by muglikar** [comment]
Any update on this?

**Comment by sujoyrc** [comment]
When I try downgrading by the following command 

`E: Couldn't find any package by regex 'bazel-0.29.0'`

I get the following error

`(base) antpc@ant-pc:~/tensorflow$ sudo apt install bazel-0.29.0
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package bazel-0.29.0
E: Couldn't find any package by glob 'bazel-0.29.0'
E: Couldn't find any package by regex 'bazel-0.29.0'`

How do I install bazel-0.2x

**Comment by freedomtan** [comment]
[Use the binary installer](https://docs.bazel.build/versions/master/install-ubuntu.html#install-with-installer-ubuntu)

[Compiling bazel from the source](https://docs.bazel.build/versions/master/install-compile-source.html)

**Comment by sujoyrc** [comment]
Thank you. I did that I am getting error on configuration.

> (base) antpc@ant-pc:~/tensorflow$ which bazel
/home/antpc/bin/bazel
(base) antpc@ant-pc:~/tensorflow$ bazel --version
bazel 0.29.1
(base) antpc@ant-pc:~/tensorflow$ ./configure
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
You have bazel 0.29.1 installed.
Please upgrade your bazel installation to version 1.0.0 or higher to build TensorFlow!

**Comment by 1zoom** [comment]
Please note the workaround for this in [related issue](https://github.com/tensorflow/tensorflow/issues/35584#issuecomment-570836764).

**Comment by sujoyrc** [comment]
Thanks it worked

**Comment by freedomtan** [comment]
For older releases (e.g., r1.14 or r2.0), I think bazel 0.2x should just work.

If you are using newer source, e.g., master branch after aaea541, you need workaround @1zoom  mentioned

**Comment by 1zoom** [comment]
I don't think it worked on 1.14. I was trying to build 1.14

**Comment by freedomtan** [comment]
@1zoom bazel 0.2x should work for r1.14. As you may know, r1.14 was released before TensorFlow switched to bazel 1.x. And you can see you don't need changes you made. See https://github.com/tensorflow/tensorflow/blob/r1.14/WORKSPACE#L84

**Comment by aaroey** [comment]
From the discussion this seems not related to TensorRT. Adding sanjoy@ to followup.

**Comment by 1zoom** [comment]
And yes, I was wrong about 1.14, I thought I'd switched branches.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by dbonner** [comment]
I encountered this exact same error building master (2.1.0), cuda 10.1, cudnn 7.6.5, and tensorrt support with python 3.8 using the specified bazel 1.2.1.
I am currently running a new build, this time using the [https://github.com/tensorflow/tensorflow/issues/35584#issuecomment-570836764](workaround) mentioned earlier in order to build with bazel 0.26.1.
I'll write another comment to update as to whether this ended up working.

**Comment by dbonner** [comment]
Yes, you still need to use bazel 0.26.1 to build master (2.1.0), cuda 10.1, cudnn 7.6.5, and tensorrt support with python 3.8.  Using bazel 0.26.1 my build completed successfully.

**Comment by ahtik** [comment]
@dbonner I had a very similar error a few times and what helped was to run `bazel clean --expunge`, not just `bazel clean` before the configure and build commands.

This error occurred when doing multiple builds with different cuda and python versions in a row (and possibly switching between tf 2.0, 2.1 and latest master, which resulted in bazel version switch).

**Comment by dbonner** [comment]
Thanks, I'll keep that in mind.  However, I think I got this error from a fresh git clone, so there was nothing for bazel to clean.

**Comment by ahtik** [comment]
Bazel keeps a cache of it's own outside the tensorflow git-cloned directory, but if also bazel was never used before then it's another issue.

**Comment by dbonner** [comment]
Oh, I see.  I'll try `bazel clean --expunge` and use the bazel version tensorflow recommends (1.2.1) next time I try to build.

**Comment by dbonner** [comment]
I just tried building after doing `bazel clean --expunge` and I still got the same error:
```
ImportError: /home/daniel/.cache/bazel/_bazel_daniel/79db702fc9f94af7d11e11c5d64854d0/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen.runfiles/org_tensorflow/tensorflow/compiler/tf2tensorrt/_wrap_py_utils.so: undefined symbol: _ZN15stream_executor14StreamExecutor18EnablePeerAccessToEPS0_
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /home/daniel/tensorflow/tensorflow/python/tools/BUILD:224:1 Executing genrule //tensorflow/python/keras/api:keras_python_api_gen failed (Exit 1)
INFO: Elapsed time: 5010.465s, Critical Path: 291.89s
INFO: 18919 processes: 18919 local.
FAILED: Build did NOT complete successfully
```

**Comment by freedomtan** [comment]
@sanjoy: FYI, as @alanpurple mentioned in #35922, TensorRT 7 doesn't have such problem. Unfortunately, not all people can use TensorRT 7, e.g., I have a Jetson Nano board which doesn't have TensorRT 7 (yet).

**Comment by dbonner** [comment]
@freedomtan, I'm on CUDA 10.1 and TensorRT 7 does not support this.  Do you
know if I can build tensorflow with CUDA 10.2?
Cheers,
Daniel

**Comment by freedomtan** [comment]
@dbonner interesting, actually I was using 10.0 + TensorRT 7 on an x86_64 machine (Jetson boards do not have newer CUDA 10.1 or 10.2, so I use 10.0 on x86_64 machine too).

**Comment by ahtik** [comment]
@freedomtan I parse the comment from alanpurple ("no problem without tensorrt suppot ( ver 7.0 )") as it was successful *without* tensorrt. v7 being mentioned simply added color.

Also https://github.com/tensorflow/tensorflow/issues/35653#issuecomment-576963272 confirms it (not yet confirmed if this issue and #35653 are related).

**Comment by freedomtan** [comment]
@ahtik oops, you are right. Let me check the configuration I used to build master branch with TensorRT 7 again.

**Comment by freedomtan** [comment]
@ahtik It turns out that it's a Python 2 vs Python 3 problem. Python 2.7 + Cuda 10.[0-2] + TensorRT + Bazel 1.2.1 works fine.

@sanjoy it seems bazel 1.2.1 + Python 3.x is problematic when TensorRT enabled.

**Comment by dbonner** [comment]
@freedomtan
This same error still occurs when building with Cuda 10.2 and TensorRT 7.

**Comment by freedomtan** [comment]
@dbonner with Python 2.7?

**Comment by ahtik** [comment]
@dbonner Confirming, also getting the build failed now with both TF 2.1 and latest master from yesterday, Ubuntu 18.04, python 3.8, cuda 10.1, tensorrt 6.
```
ImportError: /home/ak/.cache/bazel/_bazel_ak/8fab1cbad6992500fcb0a636536cab16/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen_compat_v2.runfiles/org_tensorflow/tensorflow/compiler/tf2tensorrt/_wrap_py_utils.so: undefined symbol: _ZN15stream_executor14StreamExecutor18EnablePeerAccessToEPS0_
```

To make the build succeed, have to disable tensorrt, easiest to `export TF_NEED_TENSORRT=1` before running `./configure`.

I had a suspicion that pybind11 might be involved after skimming https://github.com/tensorflow/tensorflow/issues/35709 and https://github.com/tensorflow/tensorflow/issues/35653 but simply removing `scipy` from the `tensorflow/tools/pip_package/setup.py` did't help, the same failure after 10315seconds.

**Comment by freedomtan** [comment]
@ahtik and @dbonner It seems bazel 1.x + Python 3 is problematic when building TensorRT is enabled. Workarounds:
1. use bazel 0.2.x, e.g., bazel 0.26.1, see comments in #35584
2. use Python 2.7.x instead of Python 3

**Comment by ahtik** [comment]
@freedomtan Thanks! Confirmed, linux build TF 2.1.0 works with TensorRT 6 after adjusting bazel requirement from bazel min v0.29.1 to v0.26.1 as described in https://github.com/tensorflow/tensorflow/issues/35584#issuecomment-570920203

I haven't figured out any set of versions that would build successfully Tensorflow with TensorRT under Windows (neither latest master nor TF 2.1.0).

**Comment by dbonner** [comment]
> @dbonner with Python 2.7?

Hi @freedomtan I was building with Python 3.8

**Comment by atoultaro** [comment]
I encountered the same error on the docker (tensorflow/tensorflow:devel-gpu-py3) that I can compile Tensorflow 2 for my own old machine without AVX. 

gcc 7.4.0
bazel 1.2.1
TensorRT 6.0.1
CUDA 10.1
Python 3.6.9

**Comment by MattConley** [comment]
I had run into this issue, and adding the bazel flag `--noincompatible_do_not_split_linking_cmdline` when using bazel 0.27.1 allowed the build to complete successfully, with python3 and TensorRT support enabled.

**Comment by scentini** [comment]
cc @oquenchil, seems like this failure is related to https://github.com/bazelbuild/bazel/issues/7687

**Comment by eugeneswalker** [comment]
I'm seeing this using
* Bazel 0.29.1
* Tensorflow checked out at v2.1.0
* TensorRT 7
* CUDA 10.2
* Python 3.7.4

**Comment by vk1z** [comment]
Can we fix this? It also causes a build break when trying to build tensorflow serving in a container. Until we know the root cause, why not build tensorflow 2.x with bazel 0.26.1 which is known to work (given the normal workarounds in WORKSPACE etc).

**Comment by oquenchil** [comment]
Can you try running with:
`BAZEL_LINKOPTS="" `  and  `BAZEL_LINKLIBS=-lstdc++:-lm`

**Comment by oquenchil** [comment]
Can you try running with:
`BAZEL_LINKOPTS="" `  and  `BAZEL_LINKLIBS=-lstdc++:-lm`

**Comment by eugeneswalker** [comment]
Yes, trying now. Will update with results when available. @oquenchil

**Comment by sanjoy** [comment]
> why not build tensorflow 2.x with bazel 0.26.1

Note: TensorFlow needs needs bazel 2.0 since daec6e0af0dfe39aada697275a76570da7f04608.

I have a general question for the folks on this issue: are you using [docker images](https://www.tensorflow.org/install/source#docker_linux_builds) to build TensorFlow?  If not, why not?

**Comment by jiapei100** [comment]
Alright everybody... I had Tensorflow 2.1.0 successfully built with bazel 2.0.0 ....

Now, I'm closing this issue.

**Comment by eugeneswalker** [comment]
> > why not build tensorflow 2.x with bazel 0.26.1
> 
> Note: TensorFlow needs bazel 2.0 since [daec6e0](https://github.com/tensorflow/tensorflow/commit/daec6e0af0dfe39aada697275a76570da7f04608).
> 
> I have a general question for the folks on this issue: are you using [docker images](https://www.tensorflow.org/install/source#docker_linux_builds) to build TensorFlow? If not, why not?

I am using docker image, yes. What is the deal with Bazel min version then? I thought we were supposed to be using bazel between 0.27.1 and 0.29.1 for v2.1.0 as specified by bazel MIN and MAX version? What is up with that?

**Comment by sanjoy** [comment]
> I am using docker image, yes. 

CC @gunan 

Looks like you're building TF 2.1, but we don't publish docker images capable of building TF 2.1 (we only publish docker images that can build TF @ head).

I'll try to see if we can change this and also release docker images that can be used to build various releases of TF from source.  That way you don't have to figure out the right build environment to build TF (say) 2.1.  @gunan WDYT?

**Comment by eugeneswalker** [comment]
@sanjoy 

I've been able to build TensorFlow 2.1 for both x86_64 and ppc64le using CUDA 10.1 and CuDNN 7 inside my own development Docker images. The problem is only when I try to include TensorRT. I've tried both TensorRT 6 and 7 and either way, TF 2.1 fails to build on BOTH x86_64 AND ppc64le, even in the presence of all the requisite libraries. Having the ability to build TF for ppc64le is a primary reason I'm creating my own development docker images. Do you know of any plans to make the devel images available for ppc64le in the future? Thanks for taking the time to help.

**Comment by eugeneswalker** [comment]
Since the author closed this issue, but since it is not resolved in my case, I have opened a standalone issue for this. https://github.com/tensorflow/tensorflow/issues/37076

**Comment by yaniv148** [comment]
pip3 install Keras-Preprocessing

Fixed it for me
