### ISSUE TITLE
[TF 2.1.0rc1] Fail to import package on Windows

### ISSUE THREAD

**Issue by seanpmorgan** [tensorflow/tensorflow#35140]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): 2.1.0rc1
- Python version: 3.7

**Describe the current behavior**
When trying to import tensorflow on a windows 10 machine with no GPU/CUDA setup I get a `DLL load failed` error. I suspect this is related to 2.1 now containing dynamic kernels (like in 1.15), but it doesn't seem to be falling back appropriately.

**Describe the expected behavior**
Able to import

**Code to reproduce the issue**
```
pip install tensorflow==2.0.0
(win-tf2.0) python -c "import tensorflow as tf; print(tf.__version__)"
2.0.0
```

```
pip install tensorflow==2.1.0rc1
(win-tf2.1) python -c "import tensorflow as tf; print(tf.__version__)"
```

```
Traceback (most recent call last):
  File "C:\Users\SeanM\Miniconda3\envs\win-tf2.1\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\SeanM\Miniconda3\envs\win-tf2.1\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\SeanM\Miniconda3\envs\win-tf2.1\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\SeanM\Miniconda3\envs\win-tf2.1\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\SeanM\Miniconda3\envs\win-tf2.1\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\SeanM\Miniconda3\envs\win-tf2.1\lib\site-packages\tensorflow\__init__.py", line 101, in <module>
    from tensorflow_core import *
  File "C:\Users\SeanM\Miniconda3\envs\win-tf2.1\lib\site-packages\tensorflow_core\__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\SeanM\Miniconda3\envs\win-tf2.1\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\Users\SeanM\Miniconda3\envs\win-tf2.1\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "C:\Users\SeanM\Miniconda3\envs\win-tf2.1\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\SeanM\Miniconda3\envs\win-tf2.1\lib\site-packages\tensorflow_core\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\SeanM\Miniconda3\envs\win-tf2.1\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\SeanM\Miniconda3\envs\win-tf2.1\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\SeanM\Miniconda3\envs\win-tf2.1\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\SeanM\Miniconda3\envs\win-tf2.1\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\SeanM\Miniconda3\envs\win-tf2.1\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\SeanM\Miniconda3\envs\win-tf2.1\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.
```

**Comment by yifeif** [comment]
Is this the same as  https://github.com/tensorflow/tensorflow/issues/35036

**Comment by hf-sky-hf** [comment]
I updated

**Comment by seanpmorgan** [comment]
Thanks @yifeif same issue! Closing.

**Comment by naoufelabs** [comment]
Install The latest Visual C++ Runtime: 
https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads
