### ISSUE TITLE
How to solve RuntimeError in Tensorflow 2.0?

### ISSUE THREAD

**Issue by ChristianISO** [tensorflow/tensorflow#35187]
I want to run a TF1.X programm in TF2.0 on a GPU (RTX 2080 TI) in Anaconda, so I changed the code a bit, but I'll get an error in the last line below.

```
train_dataset = tf.data.Dataset.from_tensor_slices((X_train, y_train))
train_dataset = train_dataset.apply(tf.data.experimental.shuffle_and_repeat(10000, seed=0))
train_dataset = train_dataset.batch(self.batchsize)
train_dataset = train_dataset.apply(tf.data.experimental.prefetch_to_device(device))
```

The error message is 

```
Traceback (most recent call last):
  File "train.py", line 77, in <module>
    reward = manager.get_rewards(ModelGenerator, state_space.parse_state_space_list(action))
  File "C:\Users\user\tf\tf2.0_gpu_test\manager.py", line 83, in get_rewards
    train_dataset = train_dataset.apply(tf.data.experimental.prefetch_to_device(device))
  File "C:\Users\user\AppData\Local\Continuum\anaconda3\envs\tf_env\lib\site-packages\tensorflow_core\python\data\ops\dataset_ops.py", line 1369, in apply
    dataset = transformation_func(self)
  File "C:\Users\user\AppData\Local\Continuum\anaconda3\envs\tf_env\lib\site-packages\tensorflow_core\python\data\experimental\ops\prefetching_ops.py", line 54, in _apply_fn
    copy_to_device(target_device=device)).prefetch(buffer_size)
  File "C:\Users\user\AppData\Local\Continuum\anaconda3\envs\tf_env\lib\site-packages\tensorflow_core\python\data\ops\dataset_ops.py", line 1369, in apply
    dataset = transformation_func(self)
  File "C:\Users\user\AppData\Local\Continuum\anaconda3\envs\tf_env\lib\site-packages\tensorflow_core\python\data\experimental\ops\prefetching_ops.py", line 78, in _apply_fn
    source_device=source_device).with_options(options)
  File "C:\Users\user\AppData\Local\Continuum\anaconda3\envs\tf_env\lib\site-packages\tensorflow_core\python\data\experimental\ops\prefetching_ops.py", line 102, in __init__
    self._source_device = ops.convert_to_tensor(source_device)
  File "C:\Users\user\AppData\Local\Continuum\anaconda3\envs\tf_env\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1184, in convert_to_tensor
    return convert_to_tensor_v2(value, dtype, preferred_dtype, name)
  File "C:\Users\user\AppData\Local\Continuum\anaconda3\envs\tf_env\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1242, in convert_to_tensor_v2
    as_ref=False)
  File "C:\Users\user\AppData\Local\Continuum\anaconda3\envs\tf_env\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1296, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "C:\Users\user\AppData\Local\Continuum\anaconda3\envs\tf_env\lib\site-packages\tensorflow_core\python\framework\constant_op.py", line 286, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "C:\Users\user\AppData\Local\Continuum\anaconda3\envs\tf_env\lib\site-packages\tensorflow_core\python\framework\constant_op.py", line 227, in constant
    allow_broadcast=True)
  File "C:\Users\user\AppData\Local\Continuum\anaconda3\envs\tf_env\lib\site-packages\tensorflow_core\python\framework\constant_op.py", line 235, in _constant_impl
    t = convert_to_eager_tensor(value, ctx, dtype)
  File "C:\Users\user\AppData\Local\Continuum\anaconda3\envs\tf_env\lib\site-packages\tensorflow_core\python\framework\constant_op.py", line 96, in convert_to_eager_tensor
    return ops.EagerTensor(value, ctx.device_name, dtype)
RuntimeError: Can't copy Tensor with type string to device /job:localhost/replica:0/task:0/device:GPU:0.
```

It would be awesome if someone could help me.

**Comment by oanush** [comment]
@ChristianISO ,
Hi,could you provide code snippet to replicate the above error ?Thanks!

**Comment by ChristianISO** [comment]
@oanush sure, but there isn't much more

train.py line 77:
```
reward = manager.get_rewards(ModelGenerator, state_space.parse_state_space_list(action))
```

manager.py line 80-83 (part of function `get_rewards()`):
```
train_dataset = tf.data.Dataset.from_tensor_slices((X_train, y_train))
train_dataset = train_dataset.apply(tf.data.experimental.shuffle_and_repeat(10000, seed=0))
train_dataset = train_dataset.batch(self.batchsize)
train_dataset = train_dataset.apply(tf.data.experimental.prefetch_to_device(device))
```

`reward` wasn't used before same as `train_dataset`.

`X_train` and `y_train` are from the dataset (CIFAR-10).

**Comment by gowthamkpr** [comment]
@ChristianISO Github is only meant for build/install, bug/performance, feature requests or docs related issues. Please post this question in stackoverflow as there is a bigger community to help

I am going to close this issue for now. Thanks!
