### ISSUE TITLE
DLL load failed for Tensorflow-GPU==1.14/1.13 but not Tensorflow-GPU==2.0

### ISSUE THREAD

**Issue by HStuart18** [tensorflow/tensorflow#35204]
**System information**
CUDA Version: 10.2
CUDNN Version: 7
OS: Windows 10
Conda Version: 4.8
Python version: 3.7.4

I understand that this issue is common, however, I believe my case is sufficiently unique to warrant a new issue. Using the above versions of CUDA and CUDNN, after running `pip install tensorflow-gpu==2.0` and then importing the library in my conda virtual env, everything works. However, after uninstalling `tensorflow-gpu==2.0` and running `pip install tensorflow-gpu==1.14`, when importing I get:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Harry\Anaconda3\envs\tfv1\lib\site-packages\tensorflow\__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\Harry\Anaconda3\envs\tfv1\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Harry\Anaconda3\envs\tfv1\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Harry\Anaconda3\envs\tfv1\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Harry\Anaconda3\envs\tfv1\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Harry\Anaconda3\envs\tfv1\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Harry\Anaconda3\envs\tfv1\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Harry\Anaconda3\envs\tfv1\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.
```

I am confused because both versions of tensorflow-GPU are supposed to work with these versions of CUDA and CUDNN according to: https://www.tensorflow.org/install/source_windows.

Why I am I not facing any issues with `Tensorflow-GPU==2.0` but I am with `Tensorflow-GPU==1.14`?

If it is a compatibility issue, exactly what downgrades are necessary and why?

I am trying to use an older version of Tensorflow so that I can follow along with: https://github.com/chrisdonahue/wavegan which is not written in version 2 of Tensorflow.

**Comment by ravikyram** [comment]
@HStuart18 

Please use cuda 10.0 against TF 1.13,1.14 and in addition to that make sure you add cuda, cudnn paths to your environment.Please, let us know how it progress. Thanks!

**Comment by HStuart18** [comment]
I actually just decided to bite the bullet and convert my TF1 code to TF2, so I better close this issue. But it does seem that doing what you suggested would fix the problem since it is a compatibility issue.

**Comment by ymodak** [comment]
@HStuart18 Reason you are able to use TF 2.0 gpu and not TF 1.14 gpu is because; For releases 1.14 and older, CPU and GPU packages are separate.
See https://www.tensorflow.org/install/pip?lang=python3#older-versions-of-tensorflow
