### ISSUE TITLE
tf.keras CANNOT use my custom metrics or loss function!

### ISSUE THREAD

**Issue by ZYHZ100** [tensorflow/tensorflow#35216]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**

Previously, I used Keras instead of tf.keras to run my code and it can work smoothly.
CCC is the function I implemented.

`
def CCC(y_true, y_pred, sample_weight=None, multioutput='uniform_average'):

    y_true = K.reshape(y_true, (-1,NB_LABELS))
    y_pred = K.reshape(y_pred, (-1,NB_LABELS))
    y_true = K.argmax(y_true, axis=1)
    y_pred = K.argmax(y_pred, axis=1)

    y_true = K.cast(y_true, K.floatx())
    y_pred = K.cast(y_pred, K.floatx())

    # covariance between y_true and y_pred

    s_xy = K.mean((y_true - K.mean(y_true)) * (y_pred - K.mean(y_pred)))
    # means
    x_m = K.mean(y_true)
    y_m = K.mean(y_pred)
    # variances
    s_x_sq = K.var(y_true)
    s_y_sq = K.var(y_pred)

    # condordance correlation coefficient
    ccc = (2.0 * s_xy) / (s_x_sq + s_y_sq + (x_m - y_m) ** 2 + K.epsilon())
    ccc = K.maximum(K.minimum(ccc, 1.0), -1.0)

    return ccc
`

- OS Platform and Distribution: Linux  Ubuntu 18.04.2
- TensorFlow version (use command below): tensorflow 2.1.0rc1   
- Python version: python3.7
- CUDA/cuDNN version:CUDA Version: 10.1   
- GPU model and memory:  Tesla T4 16GB Memory

**Other info / logs**
The reason why I tried to use tf.keras is that I want to use keras-tuner to tune my parameters.
These are errors when combining my code with keras-tuner, but it seems like tf.keras issue not keras-tuner issue..

`
TRAIN STEPS:
2
VAL STEPS:
2
class_weight
{0: 6.695558842629338, 1: 31.333890492832904, 2: 17.24165962151265, 3: 4.737384205783776, 4: 4.5054695617553095, 5: 7.342352322135755, 6: 5.259447664120839, 7: 7.3335032481388405, 8: 1.9969838777884066, 9: 11.858626198083067, 10: 3.5724254090471605}
x_array.shape, y_array.shape, sample_weight_array.shape:
(500, 2048) (500, 11)
WARNING:tensorflow:sample_weight modes were coerced from
  ...
    to  
  ['...']
x_array.shape, y_array.shape, sample_weight_array.shape:
(500, 2048) (500, 11)
WARNING:tensorflow:sample_weight modes were coerced from
  ...
    to  
  ['...']
Train for 2 steps, validate for 2 steps
x_array.shape, y_array.shape, sample_weight_array.shape:
(500, 2048) (500, 11)
1/2 [==============>...............] - ETA: 2sWARNING:tensorflow:Early stopping conditioned on metric 'val_CCC' which is not available. Available metrics are: 
WARNING:tensorflow:Can save best model only with val_CCC available, skipping.
WARNING:tensorflow:Can save best model only with val_CCC available, skipping.
Traceback (most recent call last):
  File "hp_tunning.py", line 297, in <module>
    tunning()
  File "hp_tunning.py", line 206, in tunning
    train_weight=train_weight)
  File "/home/i/i0000013/EmoPain2020-FinalVersion/train_tunning.py", line 144, in train_tunning
    class_weight=class_weight)
  File "/home/i/i0000013/miniconda3/envs/emopain-tf2/lib/python3.7/site-packages/kerastuner/engine/base_tuner.py", line 122, in search
    self.run_trial(trial, *fit_args, **fit_kwargs)
  File "/home/i/i0000013/miniconda3/envs/emopain-tf2/lib/python3.7/site-packages/kerastuner/engine/multi_execution_tuner.py", line 95, in run_trial
    history = model.fit(*fit_args, **fit_kwargs, callbacks=callbacks)
  File "/home/i/i0000013/miniconda3/envs/emopain-tf2/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 819, in fit
    use_multiprocessing=use_multiprocessing)
  File "/home/i/i0000013/miniconda3/envs/emopain-tf2/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 342, in fit
    total_epochs=epochs)
  File "/home/i/i0000013/miniconda3/envs/emopain-tf2/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 128, in run_one_epoch
    batch_outs = execution_function(iterator)
  File "/home/i/i0000013/miniconda3/envs/emopain-tf2/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 98, in execution_function
x_array.shape, y_array.shape, sample_weight_array.shape:
    distributed_function(input_fn))
(500, 2048) (500, 11)
  File "/home/i/i0000013/miniconda3/envs/emopain-tf2/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 568, in __call__
    result = self._call(*args, **kwds)
  File "/home/i/i0000013/miniconda3/envs/emopain-tf2/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 632, in _call
    return self._stateless_fn(*args, **kwds)
  File "/home/i/i0000013/miniconda3/envs/emopain-tf2/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 2363, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/home/i/i0000013/miniconda3/envs/emopain-tf2/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 1611, in _filtered_call
    self.captured_inputs)
  File "/home/i/i0000013/miniconda3/envs/emopain-tf2/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 1692, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/home/i/i0000013/miniconda3/envs/emopain-tf2/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 545, in call
    ctx=ctx)
  File "/home/i/i0000013/miniconda3/envs/emopain-tf2/lib/python3.7/site-packages/tensorflow_core/python/eager/execute.py", line 67, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument:  Can not squeeze dim[0], expected a dimension of 1, got 500
	 [[node metrics/CCC_1/Squeeze (defined at /home/i/i0000013/miniconda3/envs/emopain-tf2/lib/python3.7/site-packages/kerastuner/engine/multi_execution_tuner.py:95) ]]
	 [[metrics/mse_1/broadcast_weights/assert_broadcastable/is_valid_shape/else/_47/has_valid_nonscalar_shape/then/_285/has_invalid_dims/_68]]
  (1) Invalid argument:  Can not squeeze dim[0], expected a dimension of 1, got 500
	 [[node metrics/CCC_1/Squeeze (defined at /home/i/i0000013/miniconda3/envs/emopain-tf2/lib/python3.7/site-packages/kerastuner/engine/multi_execution_tuner.py:95) ]]
0 successful operations.
0 derived errors ignored. [Op:__inference_distributed_function_3424]

Function call stack:
distributed_function -> distributed_function
`

These are errors when running the code using tf.keras but that worked fine in Keras....

`
WARNING:tensorflow:From /home/i/i0000013/EmoPain2020-FinalVersion/train.py:117: Model.fit_generator (from tensorflow.python.keras.engine.training) is deprecated and will be removed in a future version.
Instructions for updating:
Please use Model.fit, which supports generators.
x_array.shape, y_array.shape, sample_weight_array.shape:
(500, 2048) (500, 11)
WARNING:tensorflow:sample_weight modes were coerced from
  ...
    to  
  ['...']
x_array.shape, y_array.shape, sample_weight_array.shape:
(500, 2048) (500, 11)
WARNING:tensorflow:sample_weight modes were coerced from
  ...
    to  
  ['...']
Train for 2 steps, validate for 2 steps
x_array.shape, y_array.shape, sample_weight_array.shape:
(500, 2048) (500, 11)
1/2 [==============>...............] - ETA: 2sWARNING:tensorflow:Early stopping conditioned on metric `val_CCC` which is not available. Available metrics are: 
WARNING:tensorflow:Can save best model only with val_CCC available, skipping.
Traceback (most recent call last):
  File "main.py", line 283, in <module>
    run()
  File "main.py", line 196, in run
    train_weight=train_weight)
  File "/home/i/i0000013/EmoPain2020-FinalVersion/train.py", line 117, in train
    class_weight=class_weight)
  File "/home/i/i0000013/miniconda3/envs/emopain-tf2/lib/python3.7/site-packages/tensorflow_core/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/home/i/i0000013/miniconda3/envs/emopain-tf2/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 1306, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/i/i0000013/miniconda3/envs/emopain-tf2/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 819, in fit
    use_multiprocessing=use_multiprocessing)
  File "/home/i/i0000013/miniconda3/envs/emopain-tf2/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 342, in fit
    total_epochs=epochs)
  File "/home/i/i0000013/miniconda3/envs/emopain-tf2/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 128, in run_one_epoch
    batch_outs = execution_function(iterator)
  File "/home/i/i0000013/miniconda3/envs/emopain-tf2/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 98, in execution_function
    distributed_function(input_fn))
  File "/home/i/i0000013/miniconda3/envs/emopain-tf2/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 568, in __call__
    result = self._call(*args, **kwds)
  File "/home/i/i0000013/miniconda3/envs/emopain-tf2/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 632, in _call
    return self._stateless_fn(*args, **kwds)
  File "/home/i/i0000013/miniconda3/envs/emopain-tf2/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 2363, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/home/i/i0000013/miniconda3/envs/emopain-tf2/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 1611, in _filtered_call
    self.captured_inputs)
  File "/home/i/i0000013/miniconda3/envs/emopain-tf2/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 1692, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/home/i/i0000013/miniconda3/envs/emopain-tf2/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 545, in call
    ctx=ctx)
  File "/home/i/i0000013/miniconda3/envs/emopain-tf2/lib/python3.7/site-packages/tensorflow_core/python/eager/execute.py", line 67, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument:  Can not squeeze dim[0], expected a dimension of 1, got 500
	 [[node metrics/CCC_1/Squeeze (defined at /home/i/i0000013/EmoPain2020-FinalVersion/train.py:117) ]]
	 [[metrics/acc_1/broadcast_weights/assert_broadcastable/is_valid_shape/else/_24/has_valid_nonscalar_shape/then/_275/has_invalid_dims/ExpandDims_1/_56]]
  (1) Invalid argument:  Can not squeeze dim[0], expected a dimension of 1, got 500
	 [[node metrics/CCC_1/Squeeze (defined at /home/i/i0000013/EmoPain2020-FinalVersion/train.py:117) ]]
0 successful operations.
0 derived errors ignored. [Op:__inference_distributed_function_3010]

Function call stack:
distributed_function -> distributed_function
`

**Comment by ZYHZ100** [comment]
When I set up my environment from scratch and used tensorflow-gpu 2.0.0, I still got errors as follows.

`
Traceback (most recent call last):
  File "main.py", line 283, in <module>
    run()
  File "main.py", line 196, in run
    train_weight=train_weight)
  File "/home/i/i0000013/EmoPain2020-FinalVersion/train.py", line 117, in train
    class_weight=class_weight)
  File "/home/i/i0000013/miniconda3/envs/emopain-tf2/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 1297, in fit_generator
    steps_name='steps_per_epoch')
  File "/home/i/i0000013/miniconda3/envs/emopain-tf2/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_generator.py", line 265, in model_iteration
    batch_outs = batch_function(*batch_data)
  File "/home/i/i0000013/miniconda3/envs/emopain-tf2/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 1018, in train_on_batch
    outputs = self.train_function(ins)  # pylint: disable=not-callable
  File "/home/i/i0000013/miniconda3/envs/emopain-tf2/lib/python3.7/site-packages/tensorflow_core/python/keras/backend.py", line 3740, in __call__
    outputs = self._graph_fn(*converted_inputs)
  File "/home/i/i0000013/miniconda3/envs/emopain-tf2/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 1081, in __call__
    return self._call_impl(args, kwargs)
  File "/home/i/i0000013/miniconda3/envs/emopain-tf2/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 1121, in _call_impl
    return self._call_flat(args, self.captured_inputs, cancellation_manager)
  File "/home/i/i0000013/miniconda3/envs/emopain-tf2/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 1224, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager)
  File "/home/i/i0000013/miniconda3/envs/emopain-tf2/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 511, in call
    ctx=ctx)
  File "/home/i/i0000013/miniconda3/envs/emopain-tf2/lib/python3.7/site-packages/tensorflow_core/python/eager/execute.py", line 67, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument:  Can not squeeze dim[0], expected a dimension of 1, got 500
	 [[node metrics_2/pearson_r_1/Squeeze (defined at /home/i/i0000013/miniconda3/envs/emopain-tf2/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py:1751) ]]
	 [[metrics_2/mse_1/broadcast_weights/assert_broadcastable/is_valid_shape/else/_80/has_valid_nonscalar_shape/then/_444/has_invalid_dims/concat/_48]]
  (1) Invalid argument:  Can not squeeze dim[0], expected a dimension of 1, got 500
	 [[node metrics_2/pearson_r_1/Squeeze (defined at /home/i/i0000013/miniconda3/envs/emopain-tf2/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py:1751) ]]
0 successful operations.
0 derived errors ignored. [Op:__inference_keras_scratch_graph_2525]

Function call stack:
keras_scratch_graph -> keras_scratch_graph

`

**Comment by Harmageddon** [comment]
@ZYHZ100 Did you find a solution for this? I'm having the same problem right now after migrating from `keras` to `tensorflow.keras` with a custom loss function.
