### ISSUE TITLE
tflite.load_delegate() failed when running Demo API on Google Coral mini PCIe

### ISSUE THREAD

**Issue by batulrangwala** [tensorflow/tensorflow#35214]
I am also facing a similar issue.
The demo API gives error at tflite.load_delegate.

```
pi@bpi-iot-ros-ai:~/coral/tflite/python/examples/classification$ python3 classify_image.py --model models/mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite --labels models/inat_bird_labels.txt --input images/parrot.jpg
E :248] HIB Error. hib_error_status = 0000000000000001, hib_first_error_status = 0000000000000001
E :248] HIB Error. hib_error_status = 0000000000000001, hib_first_error_status = 0000000000000001
INFO: Initialized TensorFlow Lite runtime.
----INFERENCE TIME----
Note: The first inference on Edge TPU is slow because it includes loading the model into Edge TPU memory.



pi@bpi-iot-ros-ai:~$ uname -a
Linux bpi-iot-ros-ai 5.4.0-bpi-r64 #1 SMP PREEMPT Mon Dec 16 16:00:08 IST 2019 aarch64 aarch64 aarch64 GNU/Linux
pi@bpi-iot-ros-ai:~$ lscpu
Architecture:          aarch64
Byte Order:            Little Endian
CPU(s):                2
On-line CPU(s) list:   0,1
Thread(s) per core:    1
Core(s) per socket:    2
Socket(s):             1
CPU max MHz:           1350.0000
CPU min MHz:           30.0000
pi@bpi-iot-ros-ai:~$ ls -l /usr/lib/aarch64-linux-gnu/libedge*
lrwxrwxrwx 1 root root     17 Sep 17 04:27 /usr/lib/aarch64-linux-gnu/libedgetpu.so.1 -> libedgetpu.so.1.0
-rwxrwxrwx 1 root root 792376 Sep 17 04:27 /usr/lib/aarch64-linux-gnu/libedgetpu.so.1.0
pi@bpi-iot-ros-ai:~$ lspci
00:00.0 PCI bridge: MEDIATEK Corp. Device 3258
01:00.0 System peripheral: Device 1ac1:089a
pi@bpi-iot-ros-ai:~$ ls /dev/apex_0 
/dev/apex_0
pi@bpi-iot-ros-ai:~$ sudo sh -c "echo 'SUBSYSTEM==\"apex\", MODE=\"0660\", GROUP=\"apex\"' >> /etc/udev/rules.d/65-apex.rules"
pi@bpi-iot-ros-ai:~$ sudo groupadd apex
groupadd: group 'apex' already exists
pi@bpi-iot-ros-ai:~$ sudo adduser $USER apex
The user `pi' is already a member of `apex'.
```

**Comment by batulrangwala** [comment]
As suggested by the Coral support and Troubleshooting https://coral.ai/docs/m2/get-started/#troubleshooting
The error still persist.

**Comment by batulrangwala** [comment]
I have now loaded the libedgetpu as per the instructions here https://coral.ai/news/updates-04-2019/.
Now I do not get the HIB error but the follwoing error
```

`Traceback (most recent call last):
  File "classify_image.py", line 122, in <module>
    main()
  File "classify_image.py", line 98, in main
    interpreter = make_interpreter(args.model)
  File "classify_image.py", line 71, in make_interpreter
    {'device': device[0]} if device else {})
  File "/usr/local/lib/python3.5/dist-packages/tflite_runtime/interpreter.py", line 165, in load_delegate
    delegate = Delegate(library, options)
  File "/usr/local/lib/python3.5/dist-packages/tflite_runtime/interpreter.py", line 89, in __init__
    self._library = ctypes.pydll.LoadLibrary(library)
  File "/usr/lib/python3.5/ctypes/__init__.py", line 425, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.5/ctypes/__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/lib/aarch64-linux-gnu/libc++abi.so.1: undefined symbol: _Unwind_GetRegionStart
Exception ignored in: <bound method Delegate.__del__ of <tflite_runtime.interpreter.Delegate object at 0x7f99af6550>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tflite_runtime/interpreter.py", line 124, in __del__
    if self._library is not None:
AttributeError: 'Delegate' object has no attribute '_library'
```
`
I have updated the g++ and gcc to version 6 and installed libunwind8. but the same error is still present.

**Comment by terryheo** [comment]
@batulrangwala is this still happening?

**Comment by batulrangwala** [comment]
Yes

**Comment by terryheo** [comment]
What's the target OS you're using?
If you're using Coral, could you update OS to 4.0 Day or later?
https://coral.ai/software/#mendel-linux

Could you also share the result of this command?

```
ldd -r /usr/lib/aarch64-linux-gnu/libedgetpu.so.1.0
```

**Comment by batulrangwala** [comment]
I am using BananaPi R64.
Kernel version 4.19 on Ubuntu 16

**Comment by mohantym** [comment]
Hi @batulrangwala !
Hi ! we are  checking to see if you are still looking for assistance in this issue.
Could you please try on latest stable version  TF 2.6  and let us know if this is still an issue.Thanks!
