### ISSUE TITLE
Crash on Hexagon Delegate

### ISSUE THREAD

**Issue by lcycoding** [tensorflow/tensorflow#35221]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Android
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Mi A2, Pixel3
- TensorFlow version (use command below): 1.15.0
- Python version: 
- Bazel version (if compiling from source): 1.1.0
- GCC/Compiler version (if compiling from source):

**Describe the current behavior**
I've built the dsp delegate aar.
But on my miA2, I always got the following crash in native code.
Is there anything I can do to debug with the cc files?
Also, I tried on Pixel3, it returned this device does not support hexagon delegate.
It doesn't seem to be normal for a snapdragon 845 device.
```
2019-12-18 18:30:38.484 18124-18510/com.ivuu I/tflite: Created TensorFlow Lite delegate for Hexagon.
2019-12-18 18:30:38.491 18124-18510/com.ivuu I/tflite: Initialized TensorFlow Lite runtime.
2019-12-18 18:30:38.952 18124-18510/com.ivuu A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x2 in tid 18510 (Thread-130), pid 18124
```

**Comment by lcycoding** [comment]
@jdduke Dear tensorflower,

After several tests, I found out that the release version does not compatible with hexagon delegate.
`0.0.0-nightly` actually worked.
First issue resolved, but here it comes next issue.
It seems the kernel registration is failed and lead to the following crash.
Any advice would be helpful, thanks!
```
tflite: Hexagon delegate: 61 nodes delegated out of 61 nodes.
tflite:hexagon_dsp: Hexagon delegate: 61 nodes delegated out of 61 nodes. (the android log I added in cc file)
tflite:hexagon_dsp: Hexagon Kernel was not initialized (the android log I added in cc file)
    java.lang.RuntimeException: java.lang.IllegalArgumentException: Internal error: Failed to apply delegate: hexagon_nn_config failed. Error: -1
    Hexagon Kernel was not initialized
    Node number 61 (TfLiteHexagonDelegate) failed to prepare.
```

**Comment by jdduke** [comment]
You're right, we should update the documentation to note the version compatibility requirements. I'll let Karim respond about the Hexagon failure. Does the latest init failure occur on both devices? or only the Pixel 3?

Unfortunately, Pixel devices do not support the Hexagon delegate. For the Pixel 3, you can use NNAPI to get DSP acceleration.

**Comment by karimnosseir** [comment]
Thanks @lcycoding for reporting the issue:

1) For the pixel devices as Jared mentioned, you can't use the delegate, you can only use NNAPI .
2) For the release, yes please use nightly till next release. Sorry for the confusion, i am updating the documentation with this now.
3) For the crash, i just tried it on mi A2 and working.
Can you please provide the details of your setup ?
including:
How are you creating the delegate ?
Which API (Java/C) are you using ?
Device/Android version ?
How you bundle the libraries in your app ?

Thanks

**Comment by freedomtan** [comment]
FYR. Dunno the situation of Pixel 3, but I was able to use Hexagon Delegate on Pixel 2, 3a, and 4 by 'setenforce 0', as far as I can remember.

**Comment by lcycoding** [comment]
@karimnosseir Thanks for promptly reply!

> How are you creating the delegate ?

By simply using the provided build script
`bazel build -c opt --config=android_arm64 tensorflow/lite/experimental/delegates/hexagon/java:tensorflow-lite-hexagon`

> Which API (Java/C) are you using ?

Java API 29, android ndk r20
For the C part, it's c++14 I believe... ( default by bazel 1.1.0 )

> Device/Android version ?

Mi A2 with Android 9

> How you bundle the libraries in your app ?

By putting `.aar` files into libs library, and the generated nn_skel.so into jniLibs folder.

**Comment by karimnosseir** [comment]
By which API i mean are you creating the delegate in C++ code or Java code ?
Also, can you include the logcat

Thanks

**Comment by lcycoding** [comment]
Ahh.. Sorry for the misunderstanding..
I'm creating delegate with Java Code.
The full logcat message is as followed
```
2019-12-20 10:13:52.016 11662-12221/com.ivuu V/com.ivuu: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/fastrpc_apps_user.c:1688: Searching for fastrpc_shell_0 ...
2019-12-20 10:13:52.046 11662-12221/com.ivuu V/com.ivuu: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/fastrpc_apps_user.c:1838: Successfully created user PD on domain 0 (attrs 0x0)
2019-12-20 10:13:52.050 11662-12231/com.ivuu V/com.ivuu: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/fastrpc_apps_user.c:270: rpc latency thread start
2019-12-20 10:13:52.050 11662-12221/com.ivuu I/tflite: Created TensorFlow Lite delegate for Hexagon.
2019-12-20 10:13:52.052 11662-12221/com.ivuu I/tflite: Hexagon delegate: 95 nodes delegated out of 96 nodes.
2019-12-20 10:13:52.053 11662-12221/com.ivuu V/com.ivuu: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/fastrpc_apps_user.c:1688: Searching for fastrpc_shell_3 ...
2019-12-20 10:13:52.053 11662-12229/com.ivuu E/com.ivuu: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/apps_std_imp.c:729:Error 45: fopen failed for oemconfig.so. (No such file or directory)
2019-12-20 10:13:52.066 11662-12221/com.ivuu D/com.ivuu: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/fastrpc_apps_user.c:1864: Error 0xffffffff: apps_dev_init failed for domain 3, errno Operation not permitted
2019-12-20 10:13:52.066 11662-12221/com.ivuu D/com.ivuu: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/fastrpc_apps_user.c:1956: Error ffffffff: open dev -1 for domain 3 failed
2019-12-20 10:13:52.066 11662-12221/com.ivuu D/com.ivuu: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/fastrpc_apps_user.c:999: Error 3b: remote handle64 open failed. name file:///libhexagon_nn_skel.so?hexagon_nn_domains_skel_handle_invoke&_modver=1.0&_dom=cdsp
2019-12-20 10:13:52.066 11662-12221/com.ivuu E/tflite:hexagon_dsp: Hexagon Kernel was not initialized in prepare
2019-12-20 10:13:52.067 11662-12221/com.ivuu E/AndroidRuntime: FATAL EXCEPTION: Thread-128
    Process: com.ivuu, PID: 11662
    java.lang.RuntimeException: java.lang.IllegalArgumentException: Internal error: Failed to apply delegate: hexagon_nn_config failed. Error: -1
    Hexagon Kernel was not initialized
    Node number 96 (TfLiteHexagonDelegate) failed to prepare.
    
    Restored previous execution plan after delegate application failure.
        at com.alfredcamera.plugin.objectdetector.TFLiteObjectDetectionAPIModel.doInit(TFLiteObjectDetectionAPIModel.java:121)
        at com.alfredcamera.plugin.objectdetector.TFLiteObjectDetectionAPIModel.recognizeImage(TFLiteObjectDetectionAPIModel.java:128)
        at com.alfredcamera.plugin.objectdetector.BoxPrediction.bBoxInference(BoxPrediction.java:70)
        at com.alfredcamera.plugin.objectdetector.TensorFlowThread.inference(TensorFlowThread.java:110)
        at com.alfredcamera.plugin.objectdetector.TensorFlowThread.run(TensorFlowThread.java:45)
     Caused by: java.lang.IllegalArgumentException: Internal error: Failed to apply delegate: hexagon_nn_config failed. Error: -1
    Hexagon Kernel was not initialized
    Node number 96 (TfLiteHexagonDelegate) failed to prepare.
    
    Restored previous execution plan after delegate application failure.
        at org.tensorflow.lite.NativeInterpreterWrapper.applyDelegate(Native Method)
        at org.tensorflow.lite.NativeInterpreterWrapper.modifyGraphWithDelegate(NativeInterpreterWrapper.java:195)
        at org.tensorflow.lite.Interpreter.modifyGraphWithDelegate(Interpreter.java:409)
        at com.alfredcamera.plugin.objectdetector.TFLiteObjectDetectionAPIModel.doInit(TFLiteObjectDetectionAPIModel.java:111)
        	... 4 more

```

**Comment by karimnosseir** [comment]
Thanks
Few more questions

In the initialize line for the delegate
  (e.g.) hexagonDelegate = new HexagonDelegate(activity);
Can you print 
  activity.getApplicationInfo().nativeLibraryDir
and check that the shared lib files are on the device under the same path.

adb shell ls -al <PATH_PRINTED_FROM_ABOVE>

**Comment by lcycoding** [comment]
Yes, I believe the files are there

```
total 19044
drwxr-xr-x 2 system system    4096 2019-12-20 10:18 .
drwxr-xr-x 3 system system    4096 2019-12-20 10:18 ..
-rwxr-xr-x 1 system system    5912 1979-11-30 00:00 libGLNativeBridge.so
-rwxr-xr-x 1 system system  297064 1979-11-30 00:00 libcrashlytics.so
-rwxr-xr-x 1 system system   81088 1979-11-30 00:00 libfaac.so
-rwxr-xr-x 1 system system   82832 1979-11-30 00:00 libhexagon_interface.so
-rwxr-xr-x 1 system system 1019196 1979-11-30 00:00 libhexagon_nn_skel.so
-rwxr-xr-x 1 system system 1035580 1979-11-30 00:00 libhexagon_nn_skel_v65.so
-rwxr-xr-x 1 system system 1035644 1979-11-30 00:00 libhexagon_nn_skel_v66.so
-rwxr-xr-x 1 system system 3509344 1979-11-30 00:00 libopencv_java3.so
-rwxr-xr-x 1 system system  943736 1979-11-30 00:00 libopenh264.so
-rwxr-xr-x 1 system system  461304 1979-11-30 00:00 libtensorflowlite_hexagon_jni.so
-rwxr-xr-x 1 system system 1825464 1979-11-30 00:00 libtensorflowlite_jni.so
```

**Comment by karimnosseir** [comment]
- Does it run on other devices, can you try ?
- If possible and you can share the code i can have a look - you can email if you don't want to share here.

Thanks

**Comment by lcycoding** [comment]
Hi Karim,
Sorry, the only compatible device I got is Mi A2. ( Pixel3 does not work )
Can I have your e-mail address to send you the java code?

**Comment by lcycoding** [comment]
Hi Karim,
After several tries, I decided to upgrade my A2's system.
It worked in the end!
So there's no problem here, thanks for your kindly help!

**Comment by karimnosseir** [comment]
Thanks @lcycoding for the update. Glad it worked.
