### ISSUE TITLE
Issue - Blas GEMM launch failed

### ISSUE THREAD

**Issue by MrDominikku** [tensorflow/tensorflow#35252]
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):

```
import math
import requests
import datetime
from config import config
from db_analysis import LotteryDatabase
import pandas as pd

from sklearn import model_selection

from sklearn.metrics import (accuracy_score,
                             recall_score,
                             precision_score,
                             f1_score,
                             roc_curve,
                             auc, roc_auc_score,
                             confusion_matrix)

from hyperopt import STATUS_OK, Trials, tpe, hp, fmin, space_eval

from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Activation

space = {'choice': hp.choice('num_layers',
                                         [{'layers': 'two', },
                                          {'layers': 'three',
                                           'units3': hp.choice('units3', range(64, 256)),
                                           'dropout3': hp.uniform('dropout3', .25, .75)}
                                          ]),
                     'units1': hp.choice('units1', range(64, 256)),
                     'units2': hp.choice('units2', range(64, 256)),

                     'dropout1': hp.uniform('dropout1', .25, .75),
                     'dropout2': hp.uniform('dropout2', .25, .75),

                     'batch_size': hp.choice('batch_size', range(5, 10)),

                     'nb_epochs': 100,
                     'optimizer': hp.choice('optimizer', ['adadelta', 'adam', 'rmsprop']),
                     'activation': 'relu'
                     }

class TestTF:

    def __init__(self):

        self.ldb = LotteryDatabase(config['database']) - connect to sqlite database

        self.x = None
        self.y = None

        self.x_train = None
        self.x_validation = None
        self.y_train = None
        self.y_validation = None

    def main_tf(self):

        dataset = pd.concat(self.generate_df_pieces(self.ldb.conn, 100000, offset=0, ids=5000)) - pull data from sqlite database in chunks total of 1.2 mln samples
        array = dataset.values

        self.x = array[:, :150]
        self.y = array[:, 150]

        self.x_train, self.x_validation, self.y_train, self.y_validation = model_selection.train_test_split(
            self.x, self.y, test_size=0.2, random_state=42)

        bayes_trials = Trials()

        best = fmin(fn=self.keras_objective, space=space, algo=tpe.suggest, max_evals=50, trials=bayes_trials)

        print(best)

        for bt in bayes_trials:
            print(bt['result']['loss'])
            print(bt['result']['params']

    def keras_objective(self, params):

        model = Sequential()
        model.add(Dense(output_dim=params['units1'], input_dim=int(self.x_train.shape[1])))
        model.add(Activation(params['activation']))
        model.add(Dropout(params['dropout1']))

        model.add(Dense(output_dim=params['units2'], init="glorot_uniform"))
        model.add(Activation(params['activation']))
        model.add(Dropout(params['dropout2']))

        if params['choice']['layers'] == 'three':
            model.add(Dense(output_dim=params['choice']['units3'], init="glorot_uniform"))
            model.add(Activation(params['activation']))
            model.add(Dropout(params['choice']['dropout3']))

        model.add(Dense(1))
        model.add(Activation('sigmoid'))
        model.compile(loss='binary_crossentropy', optimizer=params['optimizer'])

        model.fit(self.x_train, self.y_train, nb_epoch=params['nb_epochs'], batch_size=params['batch_size'], verbose=0)

        pred_auc = model.predict_proba(self.x_validation, batch_size=10, verbose=0)
        acc = roc_auc_score(self.y_validation, pred_auc)
        # print('AUC:', acc)
        # sys.stdout.flush()

        return {'loss': -acc, 'params': params}


if __name__ == '__main__':
    TF = TestTF()
    TF.main_tf()
```

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 7 Ultimate 64bit
- TensorFlow installed from (source or binary): pip install tensorflow-gpu
- TensorFlow version (use command below): v2.0.0-rc2-26-g64c3d382ca 2.0.0
- Python version: 3.7
- CUDA/cuDNN version:

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_19:32:27_Pacific_Daylight_Time_2019
Cuda compilation tools, release 10.2, V10.2.89

- GPU model and memory:

GTX 1050Ti 4GB

GPU Engine Specs
CUDA Cores
768
Graphics Clock (MHz)
1290
Processor Clock (MHz)
1392
Graphics Performance
high-6747
Memory Specs
Memory Clock
7 Gbps
Standard Memory Config
4 GB
Memory Interface
GDDR5
Memory Interface Width
128-bit
Memory Bandwidth (GB/sec)
112
Feature Support
Supported Technologies
CUDA, 3D Vision, PhysX, NVIDIA G-SYNC™, Ansel
Thermal and Power Specs
Maximum GPU Temperature (in C)
97
Maximum Graphics Card Power (W)
75
Minimum System Power Requirement (W)
300

**Describe the current behavior**

Testing keras with hyperopt on my model (total shape approx. [1200000, 150]

Receving error below (nvidia-smi below error code):

What I have tried so far:
-installing different CUDAA/cuDNN/tenserflow configurations
-updating packages
-checking for additional nvidia-smi processes
- batch_size manimulation range(1, 64)

```
E:/GitHub Repositories/MYOPM/test.py:139: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(input_dim=126, units=114)`
  model.add(Dense(output_dim=params['units1'], input_dim=int(self.x_train.shape[1])))

2019-12-19 06:49:34.323001: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2019-12-19 06:49:34.474001: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce GTX 1050 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.392
pciBusID: 0000:01:00.0
2019-12-19 06:49:34.474001: I tensorflow/stream_executor/platform/default/dlopen_checker_stub.cc:25] GPU libraries are statically linked, skip dlopen check.
2019-12-19 06:49:34.503001: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2019-12-19 06:49:34.516001: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2019-12-19 06:49:34.539001: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce GTX 1050 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.392
pciBusID: 0000:01:00.0
2019-12-19 06:49:34.539001: I tensorflow/stream_executor/platform/default/dlopen_checker_stub.cc:25] GPU libraries are statically linked, skip dlopen check.
2019-12-19 06:49:34.546001: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2019-12-19 06:49:46.336401: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-12-19 06:49:46.336401: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2019-12-19 06:49:46.337401: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2019-12-19 06:49:46.404401: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3374 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1050 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
WARNING:tensorflow:Large dropout rate: 0.592226 (>0.5). In TensorFlow 2.x, dropout() uses dropout rate instead of keep_prob. Please ensure that this is intended.
E:/Programowanie/GitHub Repositories/MYOPM/test.py:143: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=88, kernel_initializer="glorot_uniform")`
  model.add(Dense(output_dim=params['units2'], init="glorot_uniform"))

E:/GitHub Repositories/MYOPM/test.py:156: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  model.fit(self.x_train, self.y_train, nb_epoch=params['nb_epochs'], batch_size=params['batch_size'], verbose=0)

2019-12-19 06:49:49.410401: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cublas64_100.dll'; dlerror: cublas64_100.dll not found
2019-12-19 06:49:49.410401: E tensorflow/stream_executor/cuda/cuda_blas.cc:238] failed to create cublas handle: CUBLAS_STATUS_INTERNAL_ERROR
2019-12-19 06:49:49.515401: E tensorflow/stream_executor/cuda/cuda_blas.cc:238] failed to create cublas handle: CUBLAS_STATUS_INTERNAL_ERROR
2019-12-19 06:49:49.516401: E tensorflow/stream_executor/cuda/cuda_blas.cc:238] failed to create cublas handle: CUBLAS_STATUS_INTERNAL_ERROR
2019-12-19 06:49:49.577401: E tensorflow/stream_executor/cuda/cuda_blas.cc:238] failed to create cublas handle: CUBLAS_STATUS_INTERNAL_ERROR
2019-12-19 06:49:49.578401: E tensorflow/stream_executor/cuda/cuda_blas.cc:238] failed to create cublas handle: CUBLAS_STATUS_INTERNAL_ERROR
2019-12-19 06:49:49.586401: E tensorflow/stream_executor/cuda/cuda_blas.cc:238] failed to create cublas handle: CUBLAS_STATUS_INTERNAL_ERROR
2019-12-19 06:49:49.586401: E tensorflow/stream_executor/cuda/cuda_blas.cc:238] failed to create cublas handle: CUBLAS_STATUS_INTERNAL_ERROR
2019-12-19 06:49:49.587401: E tensorflow/stream_executor/cuda/cuda_blas.cc:238] failed to create cublas handle: CUBLAS_STATUS_INTERNAL_ERROR
2019-12-19 06:49:49.666401: E tensorflow/stream_executor/cuda/cuda_blas.cc:238] failed to create cublas handle: CUBLAS_STATUS_INTERNAL_ERROR
2019-12-19 06:49:49.667401: W tensorflow/stream_executor/stream.cc:1919] attempting to perform BLAS operation using StreamExecutor without BLAS support
2019-12-19 06:49:49.667401: W tensorflow/core/common_runtime/base_collective_executor.cc:216] BaseCollectiveExecutor::StartAbort Internal: Blas GEMM launch failed : a.shape=(9, 126), b.shape=(126, 114), m=9, n=114, k=126
	 [[{{node dense_1/MatMul}}]]
Traceback (most recent call last):
  0%|          | 0/50 [00:15<?, ?it/s, best loss: ?]
  File "E:/GitHub Repositories/MYOPM/test.py", line 168, in <module>
    TF.main_tf()
  File "E:/GitHub Repositories/MYOPM/test.py", line 104, in main_tf
    best = fmin(fn=self.keras_objective, space=space, algo=tpe.suggest, max_evals=50, trials=bayes_trials)
  File "D:\Programs\Python\lib\site-packages\hyperopt\fmin.py", line 403, in fmin
    show_progressbar=show_progressbar,
  File "D:\Programs\Python\lib\site-packages\hyperopt\base.py", line 651, in fmin
    show_progressbar=show_progressbar)
  File "D:\Programs\Python\lib\site-packages\hyperopt\fmin.py", line 422, in fmin
    rval.exhaust()
  File "D:\Programs\Python\lib\site-packages\hyperopt\fmin.py", line 276, in exhaust
    self.run(self.max_evals - n_done, block_until_done=self.asynchronous)
  File "D:\Programs\Python\lib\site-packages\hyperopt\fmin.py", line 241, in run
    self.serial_evaluate()
  File "D:\Programs\Python\lib\site-packages\hyperopt\fmin.py", line 141, in serial_evaluate
    result = self.domain.evaluate(spec, ctrl)
  File "D:\Programs\Python\lib\site-packages\hyperopt\base.py", line 856, in evaluate
    rval = self.fn(pyll_rval)
  File "E:/Programowanie/GitHub Repositories/MYOPM/test.py", line 156, in keras_objective
    model.fit(self.x_train, self.y_train, nb_epoch=params['nb_epochs'], batch_size=params['batch_size'], verbose=0)
  File "D:\Programs\Python\lib\site-packages\keras\engine\training.py", line 1239, in fit
    validation_freq=validation_freq)
  File "D:\Programs\Python\lib\site-packages\keras\engine\training_arrays.py", line 196, in fit_loop
    outs = fit_function(ins_batch)
  File "D:\Programs\Python\lib\site-packages\tensorflow_core\python\keras\backend.py", line 3740, in __call__
    outputs = self._graph_fn(*converted_inputs)
  File "D:\Programs\Python\lib\site-packages\tensorflow_core\python\eager\function.py", line 1081, in __call__
    return self._call_impl(args, kwargs)
  File "D:\Programs\Python\lib\site-packages\tensorflow_core\python\eager\function.py", line 1121, in _call_impl
    return self._call_flat(args, self.captured_inputs, cancellation_manager)
  File "D:\Programs\Python\lib\site-packages\tensorflow_core\python\eager\function.py", line 1224, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager)
  File "D:\Programs\Python\lib\site-packages\tensorflow_core\python\eager\function.py", line 511, in call
    ctx=ctx)
  File "D:\Programs\Python\lib\site-packages\tensorflow_core\python\eager\execute.py", line 67, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InternalError:  Blas GEMM launch failed : a.shape=(9, 126), b.shape=(126, 114), m=9, n=114, k=126
	 [[node dense_1/MatMul (defined at D:\Programs\Python\lib\site-packages\tensorflow_core\python\framework\ops.py:1751) ]] [Op:__inference_keras_scratch_graph_1201]

Function call stack:
keras_scratch_graph

Thu Dec 19 06:53:46 2019
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 441.22       Driver Version: 441.22       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 105... WDDM  | 00000000:01:00.0  On |                  N/A |
| 30%   30C    P8    N/A /  75W |    262MiB /  4096MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0       520    C+G   C:\Windows\system32\Dwm.exe                N/A      |
|    0      4016    C+G   ...6)\Google\Chrome\Application\chrome.exe N/A      |
+-----------------------------------------------------------------------------+

```

**Other info / logs**
Using hyperopt setup for keras NN from https://github.com/keras-team/keras/issues/1591

**Comment by ymodak** [comment]
As stack trace says `Could not load dynamic library 'cublas64_100.dll'; dlerror: cublas64_100.dll not found` it indicates that it fails to find `cuda` library.
You need to install cuda 10.0 for gpu support.
See https://www.tensorflow.org/install/gpu#software_requirements
Later add cuda path to environment variable see https://www.tensorflow.org/install/gpu#windows_setup

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by oanush** [comment]
@MrDominikku ,
Any update on the issue?Thanks!

**Comment by MrDominikku** [comment]
Apologies for late notice, @ymodak suggestion resolved issue. Thanks 🙂
