### ISSUE TITLE
TF 2.0 Custom Metric 'Tensor' object has no attribute 'numpy' 

### ISSUE THREAD

**Issue by Haakam21** [tensorflow/tensorflow#35393]
**System information**
- Have I written custom code: Yes
- OS Platform and Distribution: Windows 10
- TensorFlow installed from: pip
- TensorFlow version: tensorflow-gpu 2.0.0
- Python version: 3.7.3

**Code**

model.py
```
from metrics import r2_score


def create_model(input_shape, output_shape):
    model = models.Sequential([
        layers.LSTM(64, return_sequences=True, input_shape=input_shape),
        layers.LSTM(16, activation='relu'),
        layers.Dense(output_shape)
    ])

    model.compile(optimizer='adam', loss='mse', metrics=[r2_score])

    return model
```

metrics.py
```
from sklearn.metrics import r2_score as skl_r2_score


def r2_score(y_true, y_pred):
    return skl_r2_score(y_true.numpy(), y_pred.numpy())

```
**Current behavior**

```
Traceback (most recent call last):
  File "train.py", line 38, in <module>
    model = load_model(args.model_path, (history_length, len(series_features)), forecast_length)
  File "C:\Users\haaka\ML\goog\model.py", line 24, in load_model
    model = create_model(input_shape, output_shape)
  File "C:\Users\haaka\ML\goog\model.py", line 15, in create_model
    model.compile(optimizer='adam', loss='mse', metrics=[r2_score])
  File "C:\Users\haaka\ML\venv\lib\site-packages\tensorflow_core\python\training\tracking\base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "C:\Users\haaka\ML\venv\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 366, in compile
    masks=self._prepare_output_masks())
  File "C:\Users\haaka\ML\venv\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 2063, in _handle_metrics
    target, output, output_mask))
  File "C:\Users\haaka\ML\venv\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 2014, in _handle_per_output_metrics
    metric_fn, y_true, y_pred, weights=weights, mask=mask)
  File "C:\Users\haaka\ML\venv\lib\site-packages\tensorflow_core\python\keras\engine\training_utils.py", line 1067, in call_metric_function
    return metric_fn(y_true, y_pred, sample_weight=weights)
  File "C:\Users\haaka\ML\venv\lib\site-packages\tensorflow_core\python\keras\metrics.py", line 193, in __call__
    replica_local_fn, *args, **kwargs)
  File "C:\Users\haaka\ML\venv\lib\site-packages\tensorflow_core\python\keras\distribute\distributed_training_utils.py", line 1135, in call_replica_local_fn
    return fn(*args, **kwargs)
  File "C:\Users\haaka\ML\venv\lib\site-packages\tensorflow_core\python\keras\metrics.py", line 176, in replica_local_fn
    update_op = self.update_state(*args, **kwargs)  # pylint: disable=not-callable
  File "C:\Users\haaka\ML\venv\lib\site-packages\tensorflow_core\python\keras\utils\metrics_utils.py", line 75, in decorated
    update_op = update_state_fn(*args, **kwargs)
  File "C:\Users\haaka\ML\venv\lib\site-packages\tensorflow_core\python\keras\metrics.py", line 581, in update_state
    matches = self._fn(y_true, y_pred, **self._fn_kwargs)
  File "C:\Users\haaka\ML\goog\metrics.py", line 7, in r2_score
    return skl_r2_score(y_true.numpy(), y_pred.numpy())
AttributeError: 'Tensor' object has no attribute 'numpy'
```

In the issue [#27519](https://github.com/tensorflow/tensorflow/issues/27519) (which has been closed and does not offer a solution to my problem) others described a problem similar to mine where they were trying to implement a custom metric and encountered the error `'Tensor' object has no attribute 'numpy'`. I believe this is a bug because in TF 2.0 eager execution is enabled by default so I should not be receiving this error.

**Comment by edwardyehuang** [comment]
keras compile is run with graph mode in default

**Comment by edwardyehuang** [comment]
Try the custom train loop (confirmed work) or compile with eagerly = True (I don't know if it work), or, use py_function at graph mode.

**Comment by Haakam21** [comment]
Thank you for your response. I have solved the problem using a different method:

Replace
```
from sklearn.metrics import r2_score as skl_r2_score


def r2_score(y_true, y_pred):
    return skl_r2_score(y_true.numpy(), y_pred.numpy())
```
with
```
import tensorflow as tf


def r2(y_true, y_pred):
    total_error = tf.reduce_sum(tf.square(tf.subtract(y_true, tf.reduce_mean(y_true))))
    unexplained_error = tf.reduce_sum(tf.square(tf.subtract(y_true, y_pred)))
    r_squared = tf.subtract(tf.cast(1, tf.float32), tf.divide(unexplained_error, total_error))

    return r_squared
```

**Comment by bjarthur** [comment]
model.compile(..., run_eagerly=True) worked for me when creating a custom metric

**Comment by chuckhope** [comment]
> model.compile(..., run_eagerly=True) worked for me when creating a custom metric

In my multi_lable_classification task, I try to use numpy operation in the custom metric and I have added "run_eagerly = True", but still failed
