### ISSUE TITLE
Bijectors crash tf2.1 autograph in distributed mirrored multi-gpu mode

### ISSUE THREAD

**Issue by olegmyrk** [tensorflow/tensorflow#35416]
**System information**
* Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
* OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.3 LTS
* TensorFlow installed from (source or binary): binary
* TensorFlow version (use command below): v2.1.0-rc1-58-g9837ece 2.1.0-rc2 (python3 -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)")
* Python version: Python 3.6.8
* CUDA/cuDNN version: Driver Version: 440.33.01, CUDA Version: 10.2, cuDNN 7.6.2
* GPU model and memory: Tesla V100-SXM2-16GB

**Describe the current behavior**
I'm using Bijectors as a flexible prior for a VAE. 

In tf2.1 autograph distributed mirrored mode 
https://github.com/olegmyrk/SPADE-Tensorflow/blob/85b5fd7943296561dc3d54557fec5346c2adea58/SPADE.py#L1152
I am getting
```
google.protobuf.message.DecodeError: Error parsing message
```
when running with multiple GPUs (but not when running with single GPU):
```
bijectors = []
for i in range(16):
    bijectors.append(tfb.MaskedAutoregressiveFlow(
      shift_and_log_scale_fn=tfb.masked_autoregressive_default_template(
          code, hidden_layers=[1024, 1024], name=scope + "/maf_" + str(i))))

    bijectors.append(tfb.BatchNormalization(
        batchnorm_layer=tf.layers.BatchNormalization(
                            name=scope + '/batch_norm_' + str(i)),
        name=scope + '/batch_norm_bijector' + str(i)))

    permutation=tf.get_variable('permutation_'+str(i), initializer=np.random.permutation(out_channel).astype("int32"), trainable=False)
    bijectors.append(tfb.Permute(permutation))
    
flow_bijector = tfb.Chain(list(reversed(bijectors[:-1])))
```
https://github.com/olegmyrk/SPADE-Tensorflow/blob/85b5fd7943296561dc3d54557fec5346c2adea58/SPADE.py#L190

**Describe the expected behavior**
Should not crash

**Code to reproduce the issue**
TF2.x code:
https://github.com/olegmyrk/SPADE-Tensorflow/blob/85b5fd7943296561dc3d54557fec5346c2adea58/SPADE.py#L190

**Other info / logs**
```
Traceback (most recent call last):
  File "main.py", line 134, in <module>
    main()
  File "main.py", line 121, in main
    gan.train()
  File "/app/home/ubuntu/SPADE-Tensorflow.tf2/SPADE.py", line 1379, in train
    train_loop()
  File "/app/home/ubuntu/SPADE-Tensorflow.tf2/SPADE.py", line 1336, in train_loop
    counter, result_inputs, result_losses_det, result_outputs_det, result_outputs_resample_det, result_outputs_random_det, result_outputs_random_gen_det = train_det_grad_both(global_step, self.train_main, *inputs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 568, in __call__
    result = self._call(*args, **kwds)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 615, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 497, in _initialize
    *args, **kwds))
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2389, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2703, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2599, in _create_graph_function
    shared_func_graph=False)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1511, in __init__
    func_graph, self._attrs, self._garbage_collector)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 601, in __init__
    self._func_graph.inputs, self._func_graph.outputs, attrs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 466, in __init__
    function_def.ParseFromString(compat.as_bytes(proto_data))
google.protobuf.message.DecodeError: Error parsing message
```
[train.CelebAMask-HQ.tf21.4xgpu.maf.log](https://github.com/tensorflow/tensorflow/files/4001259/train.CelebAMask-HQ.tf21.4xgpu.maf.log)

**Comment by alextp** [comment]
This is an internal TF bug.

Can you give me a self-contained example to reproduce? Like, paste the code you need to trigger the error in a colab.research.google.com ?

**Comment by olegmyrk** [comment]
I will try to bisect my network into smallest possible example once this issue is resolved:
https://github.com/tensorflow/tensorflow/issues/35346
ATM I would have to wait for 30 minutes for each run of my network in multi-gpu mode.

**Comment by saikumarchalla** [comment]
Currently, we are unable to reproduce the issue.Please update the issue with proper details, and we will reopen the issue. Thanks!
