### ISSUE TITLE
TF 2.0 XLA JIT reporting error: "./bin/ptxas not found"

### ISSUE THREAD

**Issue by thincal** [tensorflow/tensorflow#35423]
**System information**
- OS Platform and Distribution: Ubuntu 16.04.6 LTS
- TensorFlow installed from (source or binary): pip3 install tensorflow-gpu
- TensorFlow version (use command below): 2.0.0
- Python version: 3.5.2
- CUDA/cuDNN version: 10.0
- GPU model and memory: TITAN Xp

**Describe the current behavior**

The test code is running with error as bellow:

```
2019-12-26 22:02:59.166382: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2019-12-26 22:02:59.166422: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2019-12-26 22:02:59.166453: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2019-12-26 22:02:59.166482: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2019-12-26 22:02:59.166512: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2019-12-26 22:02:59.166541: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2019-12-26 22:02:59.166573: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2019-12-26 22:02:59.171144: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2019-12-26 22:02:59.171311: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2019-12-26 22:02:59.174312: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-12-26 22:02:59.174418: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0
2019-12-26 22:02:59.174508: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N
2019-12-26 22:02:59.179990: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 11439 MB memory) -> physical GPU (device: 0, name: TITAN Xp, pci bus id: 0000:06:00.0, compute capability: 6.1)
sleep
2019-12-26 22:02:59.923393: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2019-12-26 22:03:00.348503: W tensorflow/stream_executor/cuda/redzone_allocator.cc:312] Not found: ./bin/ptxas not found
Relying on driver to perform ptx compilation. This message will be only logged once.
2019-12-26 22:03:00.355159: W tensorflow/core/framework/op_kernel.cc:1622] OP_REQUIRES failed at xla_compile_on_demand_op.cc:218 : Not found: ./bin/ptxas not found
Traceback (most recent call last):
  File "tf.py", line 8, in <module>
    c = tf.linalg.matmul(a, b)
  File "/home/thincal/.local/lib/python3.5/site-packages/tensorflow_core/python/util/dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "/home/thincal/.local/lib/python3.5/site-packages/tensorflow_core/python/ops/math_ops.py", line 2765, in matmul
    a, b, transpose_a=transpose_a, transpose_b=transpose_b, name=name)
  File "/home/thincal/.local/lib/python3.5/site-packages/tensorflow_core/python/ops/gen_math_ops.py", line 6126, in mat_mul
    _six.raise_from(_core._status_to_exception(e.code, message), None)
  File "<string>", line 2, in raise_from
tensorflow.python.framework.errors_impl.NotFoundError: ./bin/ptxas not found [Op:MatMul] name: MatMul/
```

**Describe the expected behavior**

The test code is running successfully.

**Code to reproduce the issue**

```
import tensorflow as tf
try:
  with tf.device('device:XLA_GPU:0'):
    a = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
    b = tf.constant([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]])
    c = tf.linalg.matmul(a, b)
    print(c)
except RuntimeError as e:
  print(e)
```

**Comment by ravikyram** [comment]
@thincal 
I have tried on colab with TF version 2.0 and i am not seeing any issue. Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/314697edacf06358aab91a9da67fb807/untitled507.ipynb). Thanks!

**Comment by wentixiaogege** [comment]
same issue with cudnn v7.6.5 ;upgrate from v7.5.0

**Comment by thincal** [comment]
And we install the cuda/cudnn in another folder then configure the PATH and LDPATH as bellow:

```
export PATH=/data/cuda/cuda-10.0/cuda/bin:$PATH
export LD_LIBRARY_PATH=/data/cuda/cuda-10.0/cuda/lib64:/data/cuda/cuda-10.0/cudnn/v7.5.0/lib64:$LD_LIBRARY_PATH
```

Is this caused by a similar issue that [ptxas ignores the PATH](https://github.com/tensorflow/tensorflow/issues/33375) ?

**Comment by sanjoy** [comment]
CC @Artem-B 

@cheshire Can we have open source documentation that we can link to as part of the error message?

**Comment by cheshire** [comment]
@thincal Do you want to try `tf-nightly-gpu` package? I'm not sure if the fix made it into 2.0.0.

@sanjoy I'll update the error message to suggest fixing the PATH.

**Comment by cheshire** [comment]
@thincal XLA:GPU devices are semi-deprecated, I do not recommend to use them. As an alternative, could you use `@tf.function(experimental_compile=True)` (with a nightly TF build).
Out of curiosity, where did you find the information about XLA:GPU devices? I don't think they are mentioned in the documentation anymore.
@Artem-B Any clues why do we fail here? It should fall back to the driver compilation.

**Comment by cheshire** [comment]
@thincal Also to get a more complete error message, could you re-run with environment variable `TF_CPP_VMODULE=status=5`?

**Comment by Artem-B** [comment]
The error reported shows a warning printed by `cuda/redzone_allocator.cc`. The file has been moved to `gpu/` some time back in early september  in #31908 , so this error is from a fairly old TF build.
I believe @cheshire did fair amount of changes since then to both the redzone checker and to the way PTX compilation is handled. I'd recommend to start with checking if this is still an issue with a nightly build.

**Comment by thincal** [comment]
> where did you find the information about XLA:GPU devices? I don't think they are mentioned in the documentation anymore.

@Artem-B device_lib.list_local_devices tells the GPU is XLA_GPU, so that we have to use `tf.device('device:XLA_GPU:0')`

**Comment by thincal** [comment]
@cheshire is there a way to disable the XLA explicitly when using TensorFlow 1.x and 2.0 ?

**Comment by thincal** [comment]
> Do you want to try `tf-nightly-gpu` package? I'm not sure if the fix made it into 2.0.0.

@cheshire 

a first try reports missing some library so that GPU can't be used:

```
tf-nightly-gpu: 2.1.0.dev20191227
cudnn: v7.5.0
cuda: v10.0
```

```
$ python3 tf.py
WARNING: Logging before flag parsing goes to stderr.
W1228 14:30:27.537421 140555689355008 tpu_cluster_resolver.py:35] Falling back to tensorflow client, its recommended to install the cloud tpu client directly with pip install cloud-tpu-client .
sleep
sleep
main thread end...
sleep
sleep
sleep
2019-12-28 14:30:34.308062: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2019-12-28 14:30:34.318080: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1558] Found device 0 with properties:
pciBusID: 0000:83:00.0 name: GeForce GTX 1080 Ti computeCapability: 6.1
coreClock: 1.582GHz coreCount: 28 deviceMemorySize: 10.92GiB deviceMemoryBandwidth: 451.17GiB/s
2019-12-28 14:30:34.320787: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /data/cuda/cuda-10.0/cuda/lib64:/data/cuda/cuda-10.0/cudnn/v7.5.0/lib64:/usr/local/nvidia/lib64
2019-12-28 14:30:34.321892: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcublas.so.10'; dlerror: libcublas.so.10: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /data/cuda/cuda-10.0/cuda/lib64:/data/cuda/cuda-10.0/cudnn/v7.5.0/lib64:/usr/local/nvidia/lib64
2019-12-28 14:30:34.323004: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcufft.so.10'; dlerror: libcufft.so.10: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /data/cuda/cuda-10.0/cuda/lib64:/data/cuda/cuda-10.0/cudnn/v7.5.0/lib64:/usr/local/nvidia/lib64
2019-12-28 14:30:34.324252: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcurand.so.10'; dlerror: libcurand.so.10: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /data/cuda/cuda-10.0/cuda/lib64:/data/cuda/cuda-10.0/cudnn/v7.5.0/lib64:/usr/local/nvidia/lib64
2019-12-28 14:30:34.325450: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcusolver.so.10'; dlerror: libcusolver.so.10: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /data/cuda/cuda-10.0/cuda/lib64:/data/cuda/cuda-10.0/cudnn/v7.5.0/lib64:/usr/local/nvidia/lib64
2019-12-28 14:30:34.326818: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcusparse.so.10'; dlerror: libcusparse.so.10: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /data/cuda/cuda-10.0/cuda/lib64:/data/cuda/cuda-10.0/cudnn/v7.5.0/lib64:/usr/local/nvidia/lib64
2019-12-28 14:30:34.379859: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2019-12-28 14:30:34.379948: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1595] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2019-12-28 14:30:34.380555: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-12-28 14:30:34.413199: I tensorflow/core/platform/profile_utils/cpu_utils.cc:101] CPU Frequency: 2100020000 Hz
2019-12-28 14:30:34.413769: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x65f6b20 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2019-12-28 14:30:34.413829: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2019-12-28 14:30:34.417437: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1099] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-12-28 14:30:34.417491: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1105]
/job:localhost/replica:0/task:0/device:XLA_GPU:0 unknown device.
```

**Comment by thincal** [comment]
> could you re-run with environment variable `TF_CPP_VMODULE=status=5`?

@cheshire 

```
$ python3 tf.py
sleep
sleep
main thread end...
sleep
2019-12-28 15:29:42.942770: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2019-12-28 15:29:42.952345: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties:
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:03:00.0
2019-12-28 15:29:42.955526: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2019-12-28 15:29:42.994875: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2019-12-28 15:29:43.042572: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2019-12-28 15:29:43.120622: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2019-12-28 15:29:43.172195: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2019-12-28 15:29:43.208427: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2019-12-28 15:29:43.279940: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2019-12-28 15:29:43.283625: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
sleep
2019-12-28 15:29:43.284274: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-12-28 15:29:43.318593: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2099990000 Hz
2019-12-28 15:29:43.319125: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5d6aeb0 executing computations on platform Host. Devices:
2019-12-28 15:29:43.319215: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
2019-12-28 15:29:43.472926: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5dde050 executing computations on platform CUDA. Devices:
2019-12-28 15:29:43.472993: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): GeForce GTX 1080 Ti, Compute Capability 6.1
2019-12-28 15:29:43.474631: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties:
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:03:00.0
2019-12-28 15:29:43.474727: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2019-12-28 15:29:43.474772: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2019-12-28 15:29:43.474812: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2019-12-28 15:29:43.474852: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2019-12-28 15:29:43.474891: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2019-12-28 15:29:43.474928: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2019-12-28 15:29:43.474966: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2019-12-28 15:29:43.478423: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2019-12-28 15:29:43.478508: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2019-12-28 15:29:43.480579: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-12-28 15:29:43.480616: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0
2019-12-28 15:29:43.480655: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N
2019-12-28 15:29:43.484205: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10481 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:03:00.0, compute capability: 6.1)
sleep
2019-12-28 15:29:45.430201: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2019-12-28 15:29:45.798750: W tensorflow/stream_executor/cuda/redzone_allocator.cc:312] Not found: ./bin/ptxas not found
Relying on driver to perform ptx compilation. This message will be only logged once.
2019-12-28 15:29:45.861278: W tensorflow/core/framework/op_kernel.cc:1622] OP_REQUIRES failed at xla_compile_on_demand_op.cc:218 : Not found: ./bin/ptxas not found
Traceback (most recent call last):
  File "tf.py", line 7, in <module>
    c = tf.linalg.matmul(a, b)
  File "/home/liusong02/.local/lib/python3.5/site-packages/tensorflow_core/python/util/dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "/home/liusong02/.local/lib/python3.5/site-packages/tensorflow_core/python/ops/math_ops.py", line 2765, in matmul
    a, b, transpose_a=transpose_a, transpose_b=transpose_b, name=name)
  File "/home/liusong02/.local/lib/python3.5/site-packages/tensorflow_core/python/ops/gen_math_ops.py", line 6126, in mat_mul
    _six.raise_from(_core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.NotFoundError: ./bin/ptxas not found [Op:MatMul] name: MatMul/
```

**Comment by sanjoy** [comment]
> **the third try**: after making a symbolic link for above missing libraries it is running well now:

JFYI, the correct fix is to install CUDA 10.1 since that's what tf-nightly is built against.

**Comment by netw0rkf10w** [comment]
@sanjoy @cheshire Same issue with **TensorFlow 2.1.0-rc2** and **CUDA 10.1**.

**Comment by netw0rkf10w** [comment]
> 2019-12-30 12:52:15.338250: W tensorflow/core/framework/op_kernel.cc:1655] OP_REQUIRES failed at xla_compile_on_demand_op.cc:220 : Not found: ./bin/ptxas not found

Instead of looking for `./bin/ptxas`, shouldn't it check to see if `ptxas` is available first? In my case:

```
$ which ptxas
/home/username/.local/cuda-10.1/bin/ptxas
```

**Comment by cheshire** [comment]
@thincal What are you actually trying to do and why are you using an XLA device? If you just would like your computation to run on GPU, simply removing the `with` line should be sufficient.

@netw0rkf10w What workflow are you using? 

> Same issue with TensorFlow 2.1.0-rc2 

Sorry I do not know which fix made into which release, I can only answer for behavior on nightly.

> Instead of looking for ./bin/ptxas, shouldn't it check to see if ptxas is available first? 

It shouldn't matter in which order do we look for ptxas, if it's in your $PATH, it will be found.

**Comment by ravikyram** [comment]
@thincal 
Any update on this issue please. Thanks!

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by nuqz** [comment]
> It shouldn't matter in which order do we look for ptxas, if it's in your $PATH, it will be found.

@cheshire, actually it matters, I have `ptxas` in my `$PATH`, but the error gone only after I've created symlynk to `./bin/ptxas`.

**Comment by lwcbobby** [comment]
> > It shouldn't matter in which order do we look for ptxas, if it's in your $PATH, it will be found.
> 
> @cheshire, actually it matters, I have `ptxas` in my `$PATH`, but the error gone only after I've created symlynk to `./bin/ptxas`.

can you show how to do that?

**Comment by nuqz** [comment]
> can you show how to do that?

The real `ptxas` path may differ on your system (just for info: I have Debian 10 installation with NVidia stuff from `buster-backports` repository). As far as I understand `tensorflow` library looks for `ptxas` in the `./bin` directory (note that the path is relative, i.e. the current working directory where you start your python script and `ln -s ...` is important). The commands are:
`mkdir ./bin`
`ln -s /usr/bin/ptxas ./bin/ptxas`

**Comment by shivampotdar** [comment]
Found a way.. You can pass an XLA flag with cuda location - 
```XLA_FLAGS="--xla_gpu_cuda_data_dir=/usr/local/cuda-11.0" python3 ./something.py```
