### ISSUE TITLE
TfLiteGpuDelegate Init: FULLY_CONNECTED: Amount of input data should match weights width

### ISSUE THREAD

**Issue by Kuloud** [tensorflow/tensorflow#35445]
**System information**
- Have I written custom code :
```java
private List<Delegate> mDelegates = new ArrayList<>();
mDelegates.add(new GpuDelegate());
```

```java
            Interpreter.Options options = null;
            if (interpreterOptions != null) {
                options = new Interpreter.Options().setNumThreads(interpreterOptions.getNumThreads());
            }
            if (!mDelegates.isEmpty()) {
                Iterator<Delegate> it = mDelegates.iterator();
                while (it.hasNext()) {
                    Delegate delegate = it.next();
                    mLogger.debug("addDelegate: " + delegate);
                    options.addDelegate(delegate);
                }
            }
            mInterpreter = new Interpreter(bb, options);
```

- Mobile device :
MI 8 / MIUI 11.0.4

- TensorFlow installed from (source or binary):
implementation 'org.tensorflow:tensorflow-lite:2.0.0'
implementation 'org.tensorflow:tensorflow-lite-gpu:2.0.0'

**Describe the current behavior**
crashed when load the attached file with 'GpuDelegate'

**Describe the expected behavior**
load the attached file correct

**Code to reproduce the issue**
N/A

**Other info / logs**
```text
    java.lang.IllegalStateException: Internal error: Unexpected failure when preparing tensor allocations: TfLiteGpuDelegate Init: FULLY_CONNECTED: Amount of input data should match weights width
    TfLiteGpuDelegate Prepare: delegate is not initialized
    Node number 3 (TfLiteGpuDelegateV2) failed to prepare.
    
    Restored previous execution plan after delegate application failure.
        at org.tensorflow.lite.NativeInterpreterWrapper.allocateTensors(Native Method)
        at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:162)
        at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:275)
        at com.didi.aoe.runtime.tensorflow.lite.TensorFlowMultipleInputsOutputsInterpreter.run(TensorFlowMultipleInputsOutputsInterpreter.java:159)
        at com.didi.aoe.library.core.NativeProcessorWrapper.run(NativeProcessorWrapper.java:40)
```

[mnist_cnn_keras.tflite.zip](https://github.com/tensorflow/tensorflow/files/4004963/mnist_cnn_keras.tflite.zip)

**Comment by tigert1998** [comment]
what does the model look like

**Comment by airyym** [comment]
@Kuloud is there workaround for this problem? I have same issue.

**Comment by Kuloud** [comment]
> @Kuloud is there workaround for this problem? I have same issue.

None, we changed the model.
