### ISSUE TITLE
`files_io.get_matching_files` fails for valid filenames that contain globs

### ISSUE THREAD

**Issue by silky** [tensorflow/tensorflow#35489]
the function `files_io.get_matching_files` says it takes a "filepath", but actually it takes a glob

this means that if you save your checkpoints to a folder like `x=[abc]`, then you can't load the previous checkpoint using something like:

```
def load_checkpoint(sess, checkpoint_path):
  saver = tf.train.Saver(tf.global_variables())
  ckpt = tf.train.get_checkpoint_state(checkpoint_path)
  tf.logging.info('Loading model %s.', ckpt.model_checkpoint_path)
  saver.restore(sess, ckpt.model_checkpoint_path)
```

where `checkpoint_path="./logs/x=[abc]"`.

**Comment by amahendrakar** [comment]
@silky,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and also the TensorFlow version you are using. Thanks!

**Comment by amahendrakar** [comment]
@silky,
Any updates regarding this issue? Thanks!

**Comment by silky** [comment]
@amahendrakar 

copying the example from here: https://www.tensorflow.org/tutorials/keras/save_and_load and just changing the checkpoint folder path

```
from __future__ import absolute_import, division, print_function, unicode_literals

import os

import tensorflow as tf
from tensorflow import keras

print(f"version = {tf.version.VERSION}")

(train_images, train_labels), (test_images, test_labels) = tf.keras.datasets.mnist.load_data()

train_labels = train_labels[:1000]
test_labels = test_labels[:1000]

train_images = train_images[:1000].reshape(-1, 28 * 28) / 255.0
test_images = test_images[:1000].reshape(-1, 28 * 28) / 255.0

# Define a simple sequential model
def create_model():
  model = tf.keras.models.Sequential([
    keras.layers.Dense(512, activation='relu', input_shape=(784,)),
    keras.layers.Dropout(0.2),
    keras.layers.Dense(10, activation='softmax')
  ])

  model.compile(optimizer='adam',
                loss='sparse_categorical_crossentropy',
                metrics=['accuracy'])

  return model

# Create a basic model instance
model = create_model()

# Display the model's architecture
model.summary()

checkpoint_path = "logs/x=[1,2]/cp.ckpt"
checkpoint_dir = os.path.dirname(checkpoint_path)

# Create a callback that saves the model's weights
cp_callback = tf.keras.callbacks.ModelCheckpoint(filepath=checkpoint_path,
                                                 save_weights_only=True,
                                                 verbose=1)

# Train the model with the new callback
model.fit(train_images, 
          train_labels,  
          epochs=1,
          validation_data=(test_images,test_labels),
          callbacks=[cp_callback])  # Pass callback to training


# Loads the weights
model.load_weights(checkpoint_path)

# Re-evaluate the model
loss,acc = model.evaluate(test_images,  test_labels, verbose=2)
print("Restored model, accuracy: {:5.2f}%".format(100*acc))
```

resulting error (note: hiding some tensorflow info messages that aren't relevant):

```
(tf-issue) 09:18 AM noon ∈ tf-issue TF_CPP_MIN_LOG_LEVEL=3 python glob_doom.py                                                                                                                                                                                                          1 ↵
version = 2.1.0
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
dense (Dense)                (None, 512)               401920    
_________________________________________________________________
dropout (Dropout)            (None, 512)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 10)                5130      
=================================================================
Total params: 407,050
Trainable params: 407,050
Non-trainable params: 0
_________________________________________________________________
Train on 1000 samples, validate on 1000 samples
 928/1000 [==========================>...] - ETA: 0s - loss: 1.1697 - accuracy: 0.6681
Epoch 00001: saving model to logs/x=[1,2]/cp.ckpt
1000/1000 [==============================] - 1s 614us/sample - loss: 1.1252 - accuracy: 0.6810 - val_loss: 0.6657 - val_accuracy: 0.8100
Traceback (most recent call last):
  File "/home/noon/tools/miniconda3/envs/tf-issue/lib/python3.6/site-packages/tensorflow_core/python/training/py_checkpoint_reader.py", line 95, in NewCheckpointReader
    return CheckpointReader(compat.as_bytes(filepattern))
RuntimeError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for logs/x=[1,2]/cp.ckpt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "glob_doom.py", line 55, in <module>
    model.load_weights(checkpoint_path)
  File "/home/noon/tools/miniconda3/envs/tf-issue/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py", line 234, in load_weights
    return super(Model, self).load_weights(filepath, by_name, skip_mismatch)
  File "/home/noon/tools/miniconda3/envs/tf-issue/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/network.py", line 1187, in load_weights
    py_checkpoint_reader.NewCheckpointReader(filepath)
  File "/home/noon/tools/miniconda3/envs/tf-issue/lib/python3.6/site-packages/tensorflow_core/python/training/py_checkpoint_reader.py", line 99, in NewCheckpointReader
    error_translator(e)
  File "/home/noon/tools/miniconda3/envs/tf-issue/lib/python3.6/site-packages/tensorflow_core/python/training/py_checkpoint_reader.py", line 35, in error_translator
    raise errors_impl.NotFoundError(None, None, error_message)
tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for logs/x=[1,2]/cp.ckpt
```

**Comment by amahendrakar** [comment]
Was able to reproduce the issue. Please find the Gist [here](https://colab.sandbox.google.com/gist/amahendrakar/b1d0c9a5e313790ec442199aed32e8a3/35489.ipynb). Thanks!

**Comment by allenlavoie** [comment]
Do you have a fix in mind? I doubt I'll get to this soon, but if you want to make changes I'm happy to discuss/review.

**Comment by silky** [comment]
@allenlavoie only fix i had in mind was to not use globs, and just match the path exactly, which may break some compat with people who are using the (as i see it, unintended) glob behaviour.

**Comment by mihaimaruseac** [comment]
But `get_matching_files` is supposed to allow globs.

**Comment by mihaimaruseac** [comment]
Is the documentation for the C++ `GetMatchingPaths` (which Python's `files_io.get_matching_files` ends up calling in the end) wrong?

https://github.com/tensorflow/tensorflow/blob/8ffef7b09555a65174632513069bd87d834c116c/tensorflow/core/platform/file_system.h#L123-L146

**Comment by silky** [comment]
@mihaimaruseac there's a documentation mismatch

maybe down that far in the call chain globs are okay, but the main api for checkpoints says _path_ *not* "glob".

see - https://www.tensorflow.org/api_docs/python/tf/keras/callbacks/ModelCheckpoint

**Comment by mihaimaruseac** [comment]
Seems to be a bug in the checkpoint reading code: it assumes end of path is a glob but doesn't check that no globbing characters are used in the path before that.

I have a roadmap to fix all of these filesystem issues but they are pending on [modularizing the filesystem support](https://github.com/tensorflow/community/pull/101) so it will be a while until I get here.

If you have a PR that fixes the behavior at the beginning of this comment, I'd be happy to review ahead of roadmap.

Sorry it takes too long to get to a fix on my side.

**Comment by silky** [comment]
@mihaimaruseac no prob; it's not urgent, glad it's on the _path_ to getting fixed :)

**Comment by sushreebarsa** [comment]
Was able to replicate the issue in TF v2.5 ,please find the gist [here ](https://colab.research.google.com/gist/sushreebarsa/a52944d6a7bc0f0e79e34f39b9337083/untitled122.ipynb)..Thanks !

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.

**Comment by silky** [comment]
@Venkat6871 this kind of automated response is not appreciated on such an old issue.
