### ISSUE TITLE
Error: Not in GZIP format

### ISSUE THREAD

**Issue by rajputashu** [tensorflow/tensorflow#35491]
Getting below exception while following "https://github.com/tensorflow/examples/tree/master/lite/examples/image_classification/android"

org.gradle.api.InvalidUserDataException: Cannot expand TAR 'D:\WorkSpaces\ML_WorkSpace\TF_Android\app\build\intermediates\mobilenet_v1_1.0_224.tgz'.
	at org.gradle.api.internal.file.archive.TarFileTree.cannotExpand(TarFileTree.java:133)
	... 56 more
Caused by: org.gradle.api.resources.ResourceException: Could not read D:\WorkSpaces\TF_Android\app\build\intermediates\mobilenet_v1_1.0_224.tgz.
	at org.gradle.internal.resource.ResourceExceptions.readFailed(ResourceExceptions.java:36)
	at org.gradle.api.internal.file.archive.compression.GzipArchiver.read(GzipArchiver.java:64)
	at org.gradle.api.internal.file.MaybeCompressedFileResource.read(MaybeCompressedFileResource.java:55)
	at org.gradle.api.internal.file.archive.TarFileTree.visit(TarFileTree.java:78)
	... 107 more
Caused by: java.util.zip.ZipException: Not in GZIP format
	at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:165)
	at org.gradle.api.internal.file.archive.compression.GzipArchiver.read(GzipArchiver.java:61)
	... 109 more

**Don't know, what could be the problem?**

**Comment by jdduke** [comment]
Possibly a Windows-specific issue. @lintian06 could you take a look?

**Comment by kumariko** [comment]
@rajputashu Could you please let us know if this issue still persists ? If it it resolved then please feel free to move this issue to close status ?Thanks!
