### ISSUE TITLE
Consuming sets of files :There are many datasets distributed as a set of files, where each file is an example.

### ISSUE THREAD

**Issue by nguyenxuanhau** [tensorflow/tensorflow#35495]
I test  and run code from: https://www.tensorflow.org/guide/data#applying_arbitrary_python_logic_with_tfpy_func
import pickle as pi
import os
import cv2
import numpy as np
import tensorflow as tf
import pathlib
flowers_root = tf.keras.utils.get_file(
    'flower_photos',
    'https://storage.googleapis.com/download.tensorflow.org/example_images/flower_photos.tgz',
    untar=True)
flowers_root = pathlib.Path(flowers_root)
for item in flowers_root.glob("*"):
  print(item.name)
#dir_training_data = '/laptrinh python/ket_qua'
#flowers_root = pathlib.Path('/laptrinh python/test_file_anh/training')
list_ds = tf.data.Dataset.list_files(str(flowers_root/'*/*'))

for f in list_ds.take(5):
  print(f.numpy())

def process_path(file_path):
  label = tf.strings.split(file_path, '/')[-2]
  return tf.io.read_file(file_path), label

labeled_ds = list_ds.map(process_path)  
for image_raw, label_text in labeled_ds.take(1):
  print(repr(image_raw.numpy()[:100]))
  print()
  print(label_text.numpy())

And happen the error as following:

Traceback (most recent call last):

  File "F:\laptrinh python\laptrinh_python_chinh_thuc\model_training.py", line 33, in <module>
    for image_raw, label_text in labeled_ds.take(1):

  File "C:\Users\Xuan Hau\.conda\envs\tf-gpu\lib\site-packages\tensorflow_core\python\data\ops\iterator_ops.py", line 622, in __next__
    return self.next()

  File "C:\Users\Xuan Hau\.conda\envs\tf-gpu\lib\site-packages\tensorflow_core\python\data\ops\iterator_ops.py", line 666, in next
    return self._next_internal()

  File "C:\Users\Xuan Hau\.conda\envs\tf-gpu\lib\site-packages\tensorflow_core\python\data\ops\iterator_ops.py", line 651, in _next_internal
    output_shapes=self._flat_output_shapes)

  File "C:\Users\Xuan Hau\.conda\envs\tf-gpu\lib\site-packages\tensorflow_core\python\ops\gen_dataset_ops.py", line 2673, in iterator_get_next_sync
    _six.raise_from(_core._status_to_exception(e.code, message), None)

  File "<string>", line 3, in raise_from

InvalidArgumentError: {{function_node __inference_Dataset_map_process_path_106}} slice index -1 of dimension 0 out of bounds.
	 [[{{node strided_slice}}]] [Op:IteratorGetNextSync]

**Comment by oanush** [comment]
@nguyenxuanhau ,
I was able to execute the code without any issue's as per the tutorial, please share us the gist of colab with error being faced. Thanks!

**Comment by oanush** [comment]
@nguyenxuanhau ,
Any update on the issue ?thanks!

**Comment by oanush** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
