### ISSUE TITLE
AutoGraph: "Entity could not be transformed and will be executed as-is"

### ISSUE THREAD

**Issue by mpundurs** [tensorflow/tensorflow#35504]
Got the following error output from Databricks; exported the notebook to the attached file; error occurs in cell 10.

INFO:tensorflow:Converted call: <function read.<locals>.<lambda> at 0x7fbde97eae18>
    args: (<tf.Tensor 'args_0:0' shape=() dtype=string>,)
    kwargs: {}

INFO:tensorflow:Not whitelisted: <method-wrapper '__call__' of function object at 0x7fbde97eae18>: default rule
INFO:tensorflow:Not whitelisted: <function read.<locals>.<lambda> at 0x7fbde97eae18>: default rule
INFO:tensorflow:Entity <function read.<locals>.<lambda> at 0x7fbde97eae18> is not cached for key <code object <lambda> at 0x7fbde9888f60, file "<command-608347>", line 138> subkey (<tensorflow.python.autograph.core.converter.ConversionOptions object at 0x7fbdddf7c0b8>, frozenset({'mean', 'var'}))
INFO:tensorflow:Converting <function read.<locals>.<lambda> at 0x7fbde97eae18>
INFO:tensorflow:Error transforming entity <function read.<locals>.<lambda> at 0x7fbde97eae18>
Traceback (most recent call last):
  File "/databricks/python/lib/python3.7/site-packages/tensorflow_core/python/autograph/pyct/parser.py", line 78, in parse_entity
    return parse_str(source, preamble_len=len(future_features)), source
  File "/databricks/python/lib/python3.7/site-packages/tensorflow_core/python/autograph/pyct/parser.py", line 139, in parse_str
    module_node = gast.parse(src)
  File "/databricks/python/lib/python3.7/site-packages/gast/gast.py", line 240, in parse
    return ast_to_gast(_ast.parse(*args, **kwargs))
  File "/usr/lib/python3.7/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 4
    .map(lambda x: decode(x, mean, var))
    ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/databricks/python/lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/api.py", line 506, in converted_call
    converted_f = conversion.convert(target_entity, program_ctx)
  File "/databricks/python/lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/conversion.py", line 322, in convert
    free_nonglobal_var_names)
  File "/databricks/python/lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/conversion.py", line 240, in _convert_with_cache
    entity, program_ctx)
  File "/databricks/python/lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/conversion.py", line 469, in convert_entity_to_ast
    nodes, name, entity_info = convert_func_to_ast(o, program_ctx)
  File "/databricks/python/lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/conversion.py", line 630, in convert_func_to_ast
    node, source = parser.parse_entity(f, future_features=future_features)
  File "/databricks/python/lib/python3.7/site-packages/tensorflow_core/python/autograph/pyct/parser.py", line 118, in parse_entity
    return parse_str(source, preamble_len=len(future_features)), source
  File "/databricks/python/lib/python3.7/site-packages/tensorflow_core/python/autograph/pyct/parser.py", line 145, in parse_str
    raise ValueError('expected exactly one node node, found {}'.format(nodes))
ValueError: expected exactly one node node, found []
WARNING:tensorflow:Entity <function read.<locals>.<lambda> at 0x7fbde97eae18> could not be transformed and will be executed as-is. Please report this to the AutoGraph
 team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: expected exactly one node node, found []
[v2_compute_ndcg_geov4.02.ipynb.zip](https://github.com/tensorflow/tensorflow/files/4011226/v2_compute_ndcg_geov4.02.ipynb.zip)

**Comment by gadagashwini** [comment]
@mpundurs, Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by mpundurs** [comment]
Tensorflow 2.0.0 (Git v2.0.0-rc2-26-g64c3d38), installed from PyPI
AWS i3.8xlarge nodes via Databricks (runtime 6.0)
Apache Spark 2.4.3

**Comment by mdanatg** [comment]
In this case autograph is unable to parse the source code of the lambda at which the error occurs:

```
.map(lambda x: decode(x, mean, var))
```

The reason is a limitation in Python, which doesn't offer enough information to completely delimit the lambda function from its surrounding code. Anyway, the workaround is straightforward - you just need to writhe the lambda in a separate line, like so:

```
decode_x = lambda x: decode(x, mean, var)
...
.map(decode_x)
```

Alternatively, you might be able to use functools.partial - no lambda required:

```
import functools
...
.map(functools.partial(decode, feat_mean=mean, feat_var=var))
```

**Comment by amahendrakar** [comment]
@mpundurs,
Is this still an issue? Please take a look at @mdanatg's workaround and let us know if the issue is resolved. Thanks!
