### ISSUE TITLE
Building with OMP support compiles, but causes runtime error "undefined symbol: omp_get_thread_num"

### ISSUE THREAD

**Issue by ChristopherBrix** [tensorflow/tensorflow#35517]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04.6 LTS (Xenial Xerus)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.15
- Python version: 3.5
- Installed using virtualenv? pip? conda?: from source, within a virtualenv. Bazel creates a pip wheels which is then installed.
- Bazel version (if compiling from source): 0.26.1
- GCC/Compiler version (if compiling from source): gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.12) 
- CUDA/cuDNN version: not used, CPU only
- GPU model and memory: not used, CPU only

**Describe the problem**
I am trying to build TF from source with support for `omp simd`. Compiling, creating and installing the pip wheel works fine using bazel. However, as soon as I try to import tensorflow, I get the error `ImportError: /work/venv/t2t/lib/python3.5/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so: undefined symbol: omp_get_thread_num` 

**Provide the exact sequence of commands / steps that you executed before running into the problem**
As described in https://www.tensorflow.org/install/source, I first run `bazel clean`. Then I run `./configure` and always select the default values:

```
(t2t) brix@cluster:/work/tensorflow$ ./configure 
WARNING: Running Bazel server needs to be killed, because the startup options are different.
WARNING: Waiting for server process to terminate (waited 5 seconds, waiting at most 60)
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
You have bazel 0.26.1 installed.
Please specify the location of python. [Default is /work/venv/t2t/bin/python]: 

Found possible Python library paths:
  /work/venv/t2t/lib/python3.5/site-packages
Please input the desired Python library path to use.  Default is [/work/venv/t2t/lib/python3.5/site-packages]
Do you wish to build TensorFlow with XLA JIT support? [Y/n]: XLA JIT support will be enabled for TensorFlow.

Do you wish to build TensorFlow with OpenCL SYCL support? [y/N]: No OpenCL SYCL support will be enabled for TensorFlow.

Do you wish to build TensorFlow with ROCm support? [y/N]: No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: No CUDA support will be enabled for TensorFlow.

Do you wish to download a fresh release of clang? (Experimental) [y/N]: Clang will not be downloaded.

Do you wish to build TensorFlow with MPI support? [y/N]: No MPI support will be enabled for TensorFlow.

Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native -Wno-sign-compare]: 

Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]: 
Not configuring the WORKSPACE for Android builds.

Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See .bazelrc for more details.
        --config=mkl            # Build with MKL support.
        --config=monolithic     # Config for mostly static monolithic build.
        --config=gdr            # Build with GDR support.
        --config=verbs          # Build with libverbs support.
        --config=ngraph         # Build with Intel nGraph support.
        --config=numa           # Build with NUMA support.
        --config=dynamic_kernels        # (Experimental) Build kernels into separate shared objects.
        --config=v2             # Build TensorFlow 2.x instead of 1.x.
Preconfigured Bazel build configs to DISABLE default on features:
        --config=noaws          # Disable AWS S3 filesystem support.
        --config=nogcp          # Disable GCP support.
        --config=nohdfs         # Disable HDFS support.
        --config=noignite       # Disable Apache Ignite support.
        --config=nokafka        # Disable Apache Kafka support.
        --config=nonccl         # Disable NVIDIA NCCL support.
Configuration finished

```

Afterwards, I run `bazel build -s --config=opt --copt="-fopenmp" --copt="-lgomp" //tensorflo
w/tools/pip_package:build_pip_package`. Note that I've added `--copt="-fopenmp" --copt="-lgomp"` to ensure that `omp` is linked. This was suggested by the comment in this SO question: https://stackoverflow.com/questions/45667374/import-tensorlfow-failed-with-errors-undefined-symbol-omp-get-num-threads

Finally, I create the pip package using `./bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg` and install it.

Unfortunately, when I then run `python -c "import tensorflow"`, I get the following stack trace:

```
Traceback (most recent call last):
  File "/work/venv/t2t/lib/python3.5/site-packages/tensorflow_core/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/work/venv/t2t/lib/python3.5/site-packages/tensorflow_core/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/work/venv/t2t/lib/python3.5/site-packages/tensorflow_core/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /work/venv/t2t/lib/python3.5/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so: undefined symbol: omp_get_thread_num

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/work/venv/t2t/lib/python3.5/site-packages/tensorflow/__init__.py", line 99, in <module>
    from tensorflow_core import *
  File "/work/venv/t2t/lib/python3.5/site-packages/tensorflow_core/__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/work/venv/t2t/lib/python3.5/site-packages/tensorflow/__init__.py", line 50, in __getattr__
    module = self._load()
  File "/work/venv/t2t/lib/python3.5/site-packages/tensorflow/__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/work/venv/t2t/lib/python3.5/site-packages/tensorflow_core/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/work/venv/t2t/lib/python3.5/site-packages/tensorflow_core/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/work/venv/t2t/lib/python3.5/site-packages/tensorflow_core/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/work/venv/t2t/lib/python3.5/site-packages/tensorflow_core/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/work/venv/t2t/lib/python3.5/site-packages/tensorflow_core/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /work/venv/t2t/lib/python3.5/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so: undefined symbol: omp_get_thread_num


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

**Comment by Leslie-Fang** [comment]
omp_get_thread_num should be one of the functions in openmp.
Did you install openmp before the build process?

**Comment by Wrzlprmft** [comment]
It seems that your problem is the same as the one I am describing [here](https://stackoverflow.com/q/60567645/2127008).

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
