### ISSUE TITLE
tf.argmax(x, axis=-1) breaks TFLite exporter

### ISSUE THREAD

**Issue by tailsu** [tensorflow/tensorflow#35615]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS Mojave
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.0.0-rc2-26-g64c3d382ca 2.0.0
- Python version: 3.7.5
- CUDA/cuDNN version: none
- GPU model and memory: none

**Code to reproduce the issue**
```python
def build_model():
    from tensorflow.keras.layers import Lambda, Input
    from tensorflow.keras.models import Model

    a = Input(shape=(16, 16, 4))
    b = Input(shape=(4,))

    def f(inputs):
        a, b = inputs
        print('b.shape', b.shape)
        b = tf.one_hot(tf.argmax(b, axis=-1), 4)
        return tf.einsum('bhwc,bc->bhw', a, b)

    x = Lambda(f)([a, b])
    model = Model(inputs=[a, b], outputs=x)
    return model

_model = build_model()
print(_model.predict([np.ones((1, 16, 16, 4)), np.ones((1, 4))]))

tf.saved_model.save(_model, 'argmax_model')
converter = tf.lite.TFLiteConverter.from_saved_model('argmax_model')
graph = converter.convert()
```

**Describe the current behavior**
_model.predict` returns the correct result.

The TFLite converter falls over with the following error:

```
Traceback (most recent call last):
  ...
  File "/Users/stefan/Documents/dc-form-model/src/scratch.py", line 29, in <module>
    graph = converter.convert()
  File "/Users/stefan/.virtualenvs/dc-form-model/lib/python3.7/site-packages/tensorflow_core/lite/python/lite.py", line 446, in convert
    **converter_kwargs)
  File "/Users/stefan/.virtualenvs/dc-form-model/lib/python3.7/site-packages/tensorflow_core/lite/python/convert.py", line 449, in toco_convert_impl
    enable_mlir_converter=enable_mlir_converter)
  File "/Users/stefan/.virtualenvs/dc-form-model/lib/python3.7/site-packages/tensorflow_core/lite/python/convert.py", line 200, in toco_convert_protos
    raise ConverterError("See console for info.\n%s\n%s\n" % (stdout, stderr))
tensorflow.lite.python.convert.ConverterError: See console for info.
2020-01-06 18:33:19.342565: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 18 operators, 36 arrays (0 quantized)
2020-01-06 18:33:19.343757: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 18 operators, 36 arrays (0 quantized)
2020-01-06 18:33:19.344782: F tensorflow/lite/toco/graph_transformations/propagate_fixed_sizes.cc:460] Check failed: input_flat_size == RequiredBufferSizeForShape(output_shape) (16 vs. 4)Input cannot be reshaped to requested dimensions for Reshape op with output "PartitionedCall/model/lambda/einsum/Reshape_1". Are your input shapes correct?
Fatal Python error: Aborted

Current thread 0x00000001151fa5c0 (most recent call first):
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 52 in execute
  File "/usr/local/lib/python3.7/site-packages/absl/app.py", line 250 in _run_main
  File "/usr/local/lib/python3.7/site-packages/absl/app.py", line 299 in run
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/platform/app.py", line 40 in run
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 89 in main
  File "/usr/local/bin/toco_from_protos", line 8 in <module>
```

**Describe the expected behavior**
Expected for it to work correctly.

If I replace `tf.argmax(b, axis=-1)` with `tf.argmax(b, axis=1)`, which indexes exactly the same axis but with a non-negative index (`b` is a rank-2 tensor), then the export finishes successfully.

**Comment by jvishnuvardhan** [comment]
@tailsu You need to enable `tensorflow` supported ops as follows. 

`converter.target_spec.supported_ops =[tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]`

With that modification, code works without any error. [Here](https://colab.sandbox.google.com/gist/jvishnuvardhan/cc7a88b02d9e078170552441d9581967/untitled732.ipynb) is the gist for your reference.

Please close the issue if it was resolved for you. Thanks!

**Comment by tailsu** [comment]
I see in your gist that you set

```
converter.experimental_new_converter = True
```

I'm guessing that the bug is inside the old TOCO converter which is already deprecated in the tf-nightly version. I'm guessing this means that the bug won't be fixed.

**Comment by jvishnuvardhan** [comment]
@tailsu I am not sure what you meant by 

> I'm guessing this means that the bug won't be fixed.

This bug was fixed in the recent `tf-nightly`  by this `converter.target_spec.supported_ops =[tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]`.

If you use recently `tf-nightly`, we don't need to use `converter.experimental_new_converter = True` as that is selected by default.
