### ISSUE TITLE
TFLite 2.0.0 compilation errors in block_map.cc

### ISSUE THREAD

**Issue by rdepew** [tensorflow/tensorflow#35626]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution: Linux Debian buster
  uname -a output: Linux freewave-ib 4.14.79-g3438de3474 #22 PREEMPT Mon Nov 4 20:16:15 UTC 2019 armv7l GNU/Linux
- Mobile device: N/A
- TensorFlow version: 2.0
- Python version: 3.7.3
- Installed using virtualenv? pip? conda?: none of the above
- Bazel version (if compiling from source): Don't know
- GCC/Compiler version (if compiling from source): g++ (Debian 8.3.0-6) 8.3.0, 
  GNU Make 4.2.1
  Built for arm-unknown-linux-gnueabihf
- CUDA/cuDNN version: Don't know
- GPU model and memory: none

**Describe the problem**

When building the Pip package for TFLite, I ran across two bugs in the file `tensorflow/lite/experimental/ruy/block_map.cc` that caused the compilation to exit with an error. 

- The first bug was a missing header file,` profiling/instrumentation.h`.
- The second bug was that the object `gemmlowp` was not declared before it was used.
- There may be additional bugs as well. I stopped looking after I found these two, since I don't know 
  the code well enough to know what to look for.

(Peripheral to this issue, the two relevant scripts needed minor edits before they would work. I've included this information here for completeness, but the C++ source file is the larger, more important issue.
1. I edited the curl commands in `download_dependencies.sh`. The curl commands in lines 63 and 65 were edited to `curl -Lsk`, and the star-zip in line 65 was wrapped in double quotes, `"*zip"` .
2. I inserted the line `TENSORFLOW_TARGET=rpi` in `build_pip_package.sh`, just before line 42, to ensure that it compiled for an armv7l.
)

**Commands used to replicate the issue**

```
git clone -b master --depth=1 http://github.com/tensorflow/tensorflow
cd tensorflow
./tensorflow/lite/tools/make/download_dependencies.sh
./tensorflow/lite/tools/pip_package/build_pip_package.sh
```

**Any other info / logs**

I'm only including the relevant part of stdout/stderr. I can include the entire output upon request.

1. The missing header file: output from build_pip_package.sh
```
[...]
python3 setup.py bdist --plat-name=linux-armv7l bdist_wheel --plat-name=linux-armv7l
running bdist
running bdist_dumb
running build
running build_py
running build_ext
make: Entering directory '/ptp/tensorflow'
g++ -O3 -DNDEBUG -fPIC  --std=c++11 -fPIC -DGEMMLOWP_ALLOW_SLOW_SCALAR_FALLBACK -pthread -I. -I/ptp/tensorflow/tensorflow/lite/tools/make/../../../../../ -I/ptp/tensorflow/tensorflow/lite/tools/make/../../../../../../ -I/ptp/tensorflow/tensorflow/lite/tools/make/downloads/ -I/ptp/tensorflow/tensorflow/lite/tools/make/downloads/eigen -I/ptp/tensorflow/tensorflow/lite/tools/make/downloads/absl -I/ptp/tensorflow/tensorflow/lite/tools/make/downloads/gemmlowp -I/ptp/tensorflow/tensorflow/lite/tools/make/downloads/neon_2_sse -I/ptp/tensorflow/tensorflow/lite/tools/make/downloads/farmhash/src -I/ptp/tensorflow/tensorflow/lite/tools/make/downloads/flatbuffers/include -I -I/usr/local/include -c tensorflow/lite/experimental/ruy/block_map.cc -o /ptp/tensorflow/tensorflow/lite/tools/make/gen/linux_armv7l/obj/tensorflow/lite/experimental/ruy/block_map.o
tensorflow/lite/experimental/ruy/block_map.cc:27:10: fatal error: profiling/instrumentation.h: No such file or directory
 #include "profiling/instrumentation.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [tensorflow/lite/tools/make/Makefile:254: /ptp/tensorflow/tensorflow/lite/tools/make/gen/linux_armv7l/obj/tensorflow/lite/experimental/ruy/block_map.o] Error 1
make: Leaving directory '/ptp/tensorflow'
Traceback (most recent call last):
  File "setup.py", line 188, in <module>
    'build_py': CustomBuildPy,
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.7/distutils/command/bdist.py", line 143, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.7/distutils/command/bdist_dumb.py", line 81, in run
    self.run_command('build')
  File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.7/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 123, in run
    self.run_command('build_ext')
  File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 115, in run
    make()
  File "setup.py", line 95, in make
    subprocess.check_call(make_args(quiet=False))
  File "/usr/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', 'SHELL=/bin/bash', 'BUILD_WITH_NNAPI=false', '-C', '/ptp/tensorflow/tensorflow/lite/tools/pip_package/../../../..', '-f', 'tensorflow/lite/tools/make/Makefile', '-j', '1']' returned non-zero exit status 2.
```

2. The undeclared object: output from build_pip_package.sh
```
[...]
+ python3 setup.py bdist --plat-name=linux-armv7l bdist_wheel --plat-name=linux-armv7l
running bdist
running bdist_dumb
running build
running build_py
running build_ext
make: Entering directory '/ptp/tensorflow'
g++ -O3 -DNDEBUG -fPIC  --std=c++11 -fPIC -DGEMMLOWP_ALLOW_SLOW_SCALAR_FALLBACK -pthread -I. -I/ptp/tensorflow/tensorflow/lite/tools/make/../../../../../ -I/ptp/tensorflow/tensorflow/lite/tools/make/../../../../../../ -I/ptp/tensorflow/tensorflow/lite/tools/make/downloads/ -I/ptp/tensorflow/tensorflow/lite/tools/make/downloads/eigen -I/ptp/tensorflow/tensorflow/lite/tools/make/downloads/absl -I/ptp/tensorflow/tensorflow/lite/tools/make/downloads/gemmlowp -I/ptp/tensorflow/tensorflow/lite/tools/make/downloads/neon_2_sse -I/ptp/tensorflow/tensorflow/lite/tools/make/downloads/farmhash/src -I/ptp/tensorflow/tensorflow/lite/tools/make/downloads/flatbuffers/include -I -I/usr/local/include -c tensorflow/lite/experimental/ruy/block_map.cc -o /ptp/tensorflow/tensorflow/lite/tools/make/gen/linux_armv7l/obj/tensorflow/lite/experimental/ruy/block_map.o
tensorflow/lite/experimental/ruy/block_map.cc: In function ‘void ruy::GetBlockByIndex(const ruy::BlockMap&, int, ruy::SidePair<int>*)’:
tensorflow/lite/experimental/ruy/block_map.cc:36:3: error: ‘gemmlowp’ has not been declared
   gemmlowp::ScopedProfilingLabel label("GetBlockByIndex");
   ^~~~~~~~
tensorflow/lite/experimental/ruy/block_map.cc: In function ‘void ruy::MakeBlockMap(int, int, int, int, int, int, int, int, ruy::Path, int, ruy::BlockMap*)’:
tensorflow/lite/experimental/ruy/block_map.cc:273:3: error: ‘gemmlowp’ has not been declared
   gemmlowp::ScopedProfilingLabel label("MakeBlockMap");
   ^~~~~~~~
tensorflow/lite/experimental/ruy/block_map.cc: In function ‘void ruy::GetBlockMatrixCoords(ruy::Side, const ruy::BlockMap&, int, int*, int*)’:
tensorflow/lite/experimental/ruy/block_map.cc:412:3: error: ‘gemmlowp’ has not been declared
   gemmlowp::ScopedProfilingLabel label("GetBlockMatrixCoords");
   ^~~~~~~~
make: *** [tensorflow/lite/tools/make/Makefile:254: /ptp/tensorflow/tensorflow/lite/tools/make/gen/linux_armv7l/obj/tensorflow/lite/experimental/ruy/block_map.o] Error 1
make: Leaving directory '/ptp/tensorflow'
Traceback (most recent call last):
  File "setup.py", line 188, in <module>
    'build_py': CustomBuildPy,
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.7/distutils/command/bdist.py", line 143, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.7/distutils/command/bdist_dumb.py", line 81, in run
    self.run_command('build')
  File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.7/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 123, in run
    self.run_command('build_ext')
  File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 115, in run
    make()
  File "setup.py", line 95, in make
    subprocess.check_call(make_args(quiet=False))
  File "/usr/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', 'SHELL=/bin/bash', 'BUILD_WITH_NNAPI=false', '-C', '/ptp/tensorflow/tensorflow/lite/tools/pip_package/../../../..', '-f', 'tensorflow/lite/tools/make/Makefile', '-j', '1']' returned non-zero exit status 2.

```

**Comment by terryheo** [comment]
@rdepew could you try it with Docker build?

https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/pip_package

`make BASE_IMAGE=debian:buster PYTHON=python3 TENSORFLOW_TARGET=rpi docker-build`

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by ravikyram** [comment]
@rdepew 

Any update on this issue please. Thanks!

**Comment by terryheo** [comment]
Let's close this. Please reopen this if you still have the issue.
