### ISSUE TITLE
ValueError: Expected scalar shape for softmax_cross_entropy_with_logits_sg/Reshape_2:0, saw shape: (?,).

### ISSUE THREAD

**Issue by yongzhuo** [tensorflow/tensorflow#35631]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): pip install tensorflow-gpu==1.12.0
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 9.0
- GPU model and memory: 2G

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Traceback (most recent call last):
  File "D:/workspace/nlp_plat/nlp-platform/algorithm/text_classification/base/workflow_dl.py", line 769, in <module>
    _tet_fit()
  File "D:/workspace/nlp_plat/nlp-platform/algorithm/text_classification/base/workflow_dl.py", line 726, in _tet_fit
    wf_dl.fit()
  File "D:/workspace/nlp_plat/nlp-platform/algorithm/text_classification/base/workflow_dl.py", line 183, in fit
    self._fit()
  File "D:/workspace/nlp_plat/nlp-platform/algorithm/text_classification/base/workflow_dl.py", line 271, in _fit
    model = self.Graph(self.params)
  File "D:\workspace\nlp_plat\nlp-platform\algorithm\text_classification\text_cnn\graph.py", line 15, in __init__
    super().__init__(params)
  File "D:\workspace\nlp_plat\nlp-platform\algorithm\text_classification\base\graph_dl.py", line 43, in __init__
    self.build()
  File "D:\workspace\nlp_plat\nlp-platform\algorithm\text_classification\base\graph_dl.py", line 55, in build
    self.build_optimize()
  File "D:\workspace\nlp_plat\nlp-platform\algorithm\text_classification\base\graph_dl.py", line 202, in build_optimize
    self.optimize = tf.contrib.layers.optimize_loss(self.loss, global_step=self.global_step, learning_rate=self.learning_rate, optimizer="Adam")
  File "D:\code\anaconda3\envs\tensorflow13\lib\site-packages\tensorflow\contrib\layers\python\layers\optimizers.py", line 155, in optimize_loss
    contrib_framework.assert_scalar(loss)
  File "D:\code\anaconda3\envs\tensorflow13\lib\site-packages\tensorflow\python\ops\check_ops.py", line 1264, in assert_scalar
    % (tensor.name, shape))
ValueError: Expected scalar shape for softmax_cross_entropy_with_logits_sg/Reshape_2:0, saw shape: (?,).

**Comment by yongzhuo** [comment]
self.loss must be scalar, shape is (1), you can use 'tf.reduce_sum' or 'tf.reduce_mean'

**Comment by xuChenSJTU** [comment]
@yongzhuo Hi, I also met this problem. I tried  'tf.reduce_mean', but it does not work

**Comment by xuChenSJTU** [comment]
@yongzhuo Do you have other advice? Thanks~
