### ISSUE TITLE
Determine input_arrays and output_arrays values for tflite_convert

### ISSUE THREAD

**Issue by batulrangwala** [tensorflow/tensorflow#35690]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version:1.14
- Python version:3.7.4
- Installed using virtualenv? pip? conda?:conda
- Bazel version (if compiling from source):NA
- GCC/Compiler version (if compiling from source):7.4
- CUDA/cuDNN version:10.2
- GPU model and memory:GeForce GTX 960M/PCIe/SSE2, 16GB

**Describe the problem**
tflite_convert : need to know the values for inout_arrays and --output_arrays
**Provide the exact sequence of commands / steps that you executed before running into the problem**
I have created a tflite_graph.pb from export_tflite_ssd_graph.py, quantized checkpoint and config files succesfully.

My task is to generate a .tflite file using the generated graph_def_file using the tflite_convert command. And then use this to generate a edgetpu.tflite file to run on Google coral.
following is the log of the command

```
(tf_gpu_clone) ridlr@ridlr107:~/TensorFlow/exported_model_12k_quantized$ tflite_convert --output_file tflite_graph.tflite --graph_def_file tflite_graph.pb --input_arrays image_tensor --output_arrays detection_boxes --input_shapes 1,576,720,3
2020-01-09 11:05:56.913487: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-01-09 11:05:56.934582: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2808000000 Hz
2020-01-09 11:05:56.935469: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5569f40357d0 executing computations on platform Host. Devices:
2020-01-09 11:05:56.935514: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
Traceback (most recent call last):
  File "/home/ridlr/anaconda3/bin/tflite_convert", line 10, in <module>
    sys.exit(main())
  File "/home/ridlr/anaconda3/lib/python3.7/site-packages/tensorflow/lite/python/tflite_convert.py", line 503, in main
    app.run(main=run_main, argv=sys.argv[:1])
  File "/home/ridlr/anaconda3/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/ridlr/anaconda3/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/ridlr/anaconda3/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/home/ridlr/anaconda3/lib/python3.7/site-packages/tensorflow/lite/python/tflite_convert.py", line 499, in run_main
    _convert_tf1_model(tflite_flags)
  File "/home/ridlr/anaconda3/lib/python3.7/site-packages/tensorflow/lite/python/tflite_convert.py", line 193, in _convert_tf1_model
    output_data = converter.convert()
  File "/home/ridlr/anaconda3/lib/python3.7/site-packages/tensorflow/lite/python/lite.py", line 904, in convert
    **converter_kwargs)
  File "/home/ridlr/anaconda3/lib/python3.7/site-packages/tensorflow/lite/python/convert.py", line 373, in toco_convert_graph_def
    input_data.SerializeToString())
  File "/home/ridlr/anaconda3/lib/python3.7/site-packages/tensorflow/lite/python/convert.py", line 172, in toco_convert_protos
    "TOCO failed. See console for info.\n%s\n%s\n" % (stdout, stderr))
tensorflow.lite.python.convert.ConverterError: TOCO failed. See console for info.
2020-01-09 11:05:58.375534: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: TFLite_Detection_PostProcess
2020-01-09 11:05:58.456167: F tensorflow/lite/toco/tooling_util.cc:918] Check failed: GetOpWithOutput(model, output_array) Specified output array "detection_boxes" is not produced by any op in this graph. Is it a typo? This should not happen. If you trigger this error please send a bug report (with code to reporduce this error), to the TensorFlow Lite team.
Fatal Python error: Aborted

Current thread 0x00007f347d2e6740 (most recent call first):
  File "/home/ridlr/anaconda3/lib/python3.7/site-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 33 in execute
  File "/home/ridlr/anaconda3/lib/python3.7/site-packages/absl/app.py", line 250 in _run_main
  File "/home/ridlr/anaconda3/lib/python3.7/site-packages/absl/app.py", line 299 in run
  File "/home/ridlr/anaconda3/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 40 in run
  File "/home/ridlr/anaconda3/lib/python3.7/site-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 59 in main
  File "/home/ridlr/anaconda3/bin/toco_from_protos", line 10 in <module>
Aborted (core dumped)
```

How do I determine the correct value of --output_array.

**Any other info / logs**
If I use the specifier --inference_type=QUANTIZED_UINT8
How do I determine the values of following specifiers?
--std_dev_values 
--mean_values 
--default_ranges_min 
--default_ranges_max

**Comment by jvishnuvardhan** [comment]
@batulrangwala Did you try using [`netron`](https://github.com/lutzroeder/netron) or tensorboard to visualize input/outputs of the model .pb file? You can check couple of resources [1](https://medium.com/@daj/how-to-inspect-a-pre-trained-tensorflow-model-5fd2ee79ced0) or [a colab gist here](https://colab.sandbox.google.com/drive/1A9X34s4LkhtkcoFqB6PYCCaGCLAcJRbp#scrollTo=5d7KEDIr6a_t). Thanks!

**Comment by batulrangwala** [comment]
I have used tensorflow/tools/graph_transforms/summarize_graph_main.cc from tensorflow (github : https://github.com/tensorflow/tensorflow) to determine the inputs/outputs of the model (.pb) file

https://colab.sandbox.google.com/drive/1A9X34s4LkhtkcoFqB6PYCCaGCLAcJRbp#scrollTo=5d7KEDIr6a_t
I have requested access now for this. have to wait!

https://medium.com/@daj/how-to-inspect-a-pre-trained-tensorflow-model-5fd2ee79ced0
I am unable to view this link currently. 

How can I use netron to determine the input/output of the model (.pb) file. 
Currently I am using following vales (determined from tensorflow tool summarize_graph).
--input_arrays image_tensor --output_arrays TFLite_Detection_PostProcess --input_shapes 1,576,720,3

But to convert to a quantized model (.tflite) I have to add the following parameters
--inference_type=QUANTIZED_UINT8
--std_dev_values
--mean_values
--default_ranges_min
--default_ranges_max

How do I determine the values of following specifiers? will these be available from netron?
--std_dev_values
--mean_values
--default_ranges_min
--default_ranges_max

When I use dummy values it leads me to  2020-01-09 12:25:17.491189: F tensorflow/lite/toco/graph_transformations/quantize.cc:611] Check failed: is_rnn_state_array #35695

**Comment by batulrangwala** [comment]
Using a docker resolved this issue. The Docker is provided by Coral and has all the necessary environment set.
Docker Link :
https://coral.ai/docs/edgetpu/retrain-detection/#set-up-the-docker-container
