### ISSUE TITLE
tf.range fails when `limit` is type of `tf.int32` and `dtype` is `tf.int64`

### ISSUE THREAD

**Issue by hartikainen** [tensorflow/tensorflow#35710]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macos Catalina
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): `2.1.0`
- Python version: `3.7`
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

**Describe the current behavior**
The behavior of `tf.range` changed between `2.0.0` and `2.1.0`, such that `tf.range(limit, dtype=dtype)` fails when `limit` is type of `tf.int32` and `dtype` is `tf.int64`. Not sure if this is a bug or a feature but I would expect this to still work.

The documentation nor the `2.1.0` release notes don't explicitly mention anything about this.

**Describe the expected behavior**
The behavior as it was in `2.0.0`, i.e. no exception is raised.

**Code to reproduce the issue**
```python
import tensorflow as tf
tf.range(tf.constant(4, dtype=tf.int32), dtype=tf.int64)
```

**Other info / logs**

With `tensorflow == 2.1.0`:
```bash
$ python -c "import tensorflow as tf; print(tf.__version__); print(tf.range(tf.constant(4, dtype=tf.int32), dtype=tf.int64))"
2.1.0
2020-01-09 16:45:39.137901: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-01-09 16:45:39.151651: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fa652c190b0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-01-09 16:45:39.151667: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/hartikainen/conda/envs/bae/lib/python3.7/site-packages/tensorflow_core/python/ops/math_ops.py", line 1430, in range
    limit = ops.convert_to_tensor(limit, dtype=dtype, name="limit")
  File "/Users/hartikainen/conda/envs/bae/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 1290, in convert_to_tensor
    (dtype.name, value.dtype.name, value))
ValueError: Tensor conversion requested dtype int64 for Tensor with dtype int32: <tf.Tensor: shape=(), dtype=int32, numpy=4>
```

With `tensorflow==2.0.0`
```bash
$ python -c "import tensorflow as tf; print(tf.__version__); print(tf.range(tf.constant(4, dtype=tf.int32), dtype=tf.int64))"
2.0.0
2020-01-09 16:40:11.425955: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-01-09 16:40:11.439063: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7f8c6ccdfd00 executing computations on platform Host. Devices:
2020-01-09 16:40:11.439079: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
tf.Tensor([0 1 2 3], shape=(4,), dtype=int64)
```

**Comment by hartikainen** [comment]
https://github.com/tensorflow/tensorflow/issues/29867 seems related but it's from time before this feature worked.

**Comment by ravikyram** [comment]
@hartikainen 
I have tried on colab with TF version 2.1 and was able to reproduce the issue.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/99ab8383b4ad24661d44b476fd4a903e/untitled545.ipynb).However i am not seeing any issue with TF 2.0. Thanks!

**Comment by hartikainen** [comment]
@ravikyram Yeah, my point was that this seems like a regression from 2.0 to 2.1, since it behaves as I would expect on 2.0. Is the "regression" is expected or not?

**Comment by yongtang** [comment]
Added a PR #35821 for the fix.

**Comment by hartikainen** [comment]
The @tensorflow-bot's survey messages are completely useless, since once you have answered it once in another issue, you always just get a message saying "You've already responded". Is there a way to fix that?

**Comment by jvishnuvardhan** [comment]
@hartikainen Thanks for bringing this @tensorflow-bot's survey issue. We will work on it soon. Thanks!
