### ISSUE TITLE
unknown option '--proto-format' when make a TensorFlow Lite AAR

### ISSUE THREAD

**Issue by aijiart** [tensorflow/tensorflow#35711]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**
I nearly finished the build ！but finally met this error

```
ERROR: /Users/norly/Documents/github/android/tensorflow-r1.15/tensorflow/lite/java/BUILD:28:1: Processing Android resources for //tensorflow/lite/java:tensorflow-lite-with-select-tf-ops_dummy_app_for_so failed (Exit 1): ResourceProcessorBusyBox failed: error executing command 
  (cd /private/var/tmp/_bazel_root/c472abc5e7a3fc0cf3c1a120192310f1/execroot/org_tensorflow && \
  exec env - \
    ANDROID_BUILD_TOOLS_VERSION=26.0.2 \
    ANDROID_NDK_API_LEVEL=18 \
    ANDROID_NDK_HOME=/Users/norly/Documents/github/android/android-ndk-r17c \
    ANDROID_SDK_API_LEVEL=26 \
    ANDROID_SDK_HOME=/Users/norly/library/Android/Sdk \
    PATH='/Applications/anaconda3/envs/android/bin:/Users/norly/opt/anaconda3/condabin:/anaconda3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/Library/TeX/texbin:usr/bin:/Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home/bin:Users/daredos/Swig/bin:/Users/norly/bin' \
    PYTHON_BIN_PATH=/Applications/anaconda3/envs/android/bin/python \
    PYTHON_LIB_PATH=/Applications/anaconda3/envs/android/lib/python3.6/site-packages \
    TF_CONFIGURE_IOS=0 \
  bazel-out/host/bin/external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/ResourceProcessorBusyBox --tool AAPT2_PACKAGE -- --aapt2 bazel-out/host/bin/external/androidsdk/aapt2_binary --directData ::bazel-out/android-armeabi-v7a-opt/bin/tensorflow/lite/java/tensorflowlite_flex_processed_manifest/AndroidManifest.xml:bazel-out/android-armeabi-v7a-opt/bin/tensorflow/lite/java/tensorflowlite_flex_symbols/R.aapt2.txt:bazel-out/android-armeabi-v7a-opt/bin/tensorflow/lite/java/tensorflowlite_flex_symbols/symbols.zip --useCompiledResourcesForMerge --primaryData ::bazel-out/armeabi-v7a-opt/bin/tensorflow/lite/java/_merged/tensorflow-lite-with-select-tf-ops_dummy_app_for_so/AndroidManifest.xml --buildToolsVersion 26.0.2 --androidJar external/androidsdk/platforms/android-26/android.jar --rOutput bazel-out/armeabi-v7a-opt/bin/tensorflow/lite/java/tensorflow-lite-with-select-tf-ops_dummy_app_for_so_symbols/R.txt --symbolsOut bazel-out/armeabi-v7a-opt/bin/tensorflow/lite/java/tensorflow-lite-with-select-tf-ops_dummy_app_for_so_symbols/merged.bin --srcJarOutput bazel-out/armeabi-v7a-opt/bin/tensorflow/lite/java/tensorflow-lite-with-select-tf-ops_dummy_app_for_so.srcjar --proguardOutput bazel-out/armeabi-v7a-opt/bin/tensorflow/lite/java/proguard/tensorflow-lite-with-select-tf-ops_dummy_app_for_so/_tensorflow-lite-with-select-tf-ops_dummy_app_for_so_proguard.cfg --mainDexProguardOutput bazel-out/armeabi-v7a-opt/bin/tensorflow/lite/java/proguard/tensorflow-lite-with-select-tf-ops_dummy_app_for_so/main_dex_tensorflow-lite-with-select-tf-ops_dummy_app_for_so_proguard.cfg --manifestOutput bazel-out/armeabi-v7a-opt/bin/tensorflow/lite/java/tensorflow-lite-with-select-tf-ops_dummy_app_for_so_processed_manifest/AndroidManifest.xml --resourcesOutput bazel-out/armeabi-v7a-opt/bin/tensorflow/lite/java/tensorflow-lite-with-select-tf-ops_dummy_app_for_so_files/resource_files.zip --packagePath bazel-out/armeabi-v7a-opt/bin/tensorflow/lite/java/tensorflow-lite-with-select-tf-ops_dummy_app_for_so.ap_ --packageForR dummy.package.for.so)
Execution platform: @bazel_tools//platforms:host_platform
1月 10, 2020 2:04:41 上午 com.google.devtools.build.android.ResourceProcessorBusyBox processRequest
严重: Error during processing
java.lang.RuntimeException: Error during Linking bazel-out/armeabi-v7a-opt/bin/tensorflow/lite/java/_merged/tensorflow-lite-with-select-tf-ops_dummy_app_for_so/AndroidManifest.xml:
Command: bazel-out/host/bin/external/androidsdk/aapt2_binary\
	link\
	--no-version-vectors\
	--no-static-lib-packages\
	--manifest\
	bazel-out/armeabi-v7a-opt/bin/tensorflow/lite/java/_merged/tensorflow-lite-with-select-tf-ops_dummy_app_for_so/AndroidManifest.xml\
	--auto-add-overlay\
	--proto-format\
	--custom-package\
	dummy.package.for.so\
	-I\
	external/androidsdk/platforms/android-26/android.jar\
	-R\
	/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/android_resources_tmp17238626937439459235/linked/filtered/bazel-out/android-armeabi-v7a-opt/bin/tensorflow/lite/java/tensorflowlite_flex_symbols/symbols.zip\
	-R\
	/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/android_resources_tmp17238626937439459235/linked/filtered/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/android_resources_tmp17238626937439459235/compiled/compiled.zip\
	-0\
	.apk\
	--output-text-symbols\
	/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/android_resources_tmp17238626937439459235/linked/R.txt\
	--emit-ids\
	/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/android_resources_tmp17238626937439459235/linked/ids.txt\
	--java\
	/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/android_resources_tmp17238626937439459235/linked/java\
	--proguard\
	/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/android_resources_tmp17238626937439459235/linked/proguard.cfg\
	--proguard-main-dex\
	/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/android_resources_tmp17238626937439459235/linked/proguard.maindex.cfg\
	-o\
	/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/android_resources_tmp17238626937439459235/linked/bin.-pb.apk
Output:
unknown option '--proto-format'.

aapt2 link [options] -o arg --manifest arg files...

Options:
 -o arg                                            Output path.
 --manifest arg                                    Path to the Android manifest to build.
 -I arg                                            Adds an Android APK to link against.
 -A arg                                            An assets directory to include in the APK. These are unprocessed.
 -R arg                                            Compilation unit to link, using `overlay` semantics.
                                                   The last conflicting resource given takes precedence.
 --package-id arg                                  Specify the package ID to use for this app. Must be greater or equal to
                                                   0x7f and can't be used with --static-lib or --shared-lib.
 --java arg                                        Directory in which to generate R.java.
 --proguard arg                                    Output file for generated Proguard rules.
 --proguard-main-dex arg                           Output file for generated Proguard rules for the main dex.
 --no-auto-version                                 Disables automatic style and layout SDK versioning.
 --no-version-vectors                              Disables automatic versioning of vector drawables. Use this only
                                                   when building with vector drawable support library.
 --no-version-transitions                          Disables automatic versioning of transition resources. Use this only
                                                   when building with transition support library.
 --no-resource-deduping                            Disables automatic deduping of resources with
                                                   identical values across compatible configurations.
 --enable-sparse-encoding                          Enables encoding sparse entries using a binary search tree.
                                                   This decreases APK size at the cost of resource retrieval performance.
 -x                                                Legacy flag that specifies to use the package identifier 0x01.
 -z                                                Require localization of strings marked 'suggested'.
 -c arg                                            Comma separated list of configurations to include. The default
                                                   is all configurations.
 --preferred-density arg                           Selects the closest matching density and strips out all others.
 --product arg                                     Comma separated list of product names to keep
 --output-to-dir                                   Outputs the APK contents to a directory specified by -o.
 --no-xml-namespaces                               Removes XML namespace prefix and URI information from
                                                   AndroidManifest.xml and XML binaries in res/*.
 --min-sdk-version arg                             Default minimum SDK version to use for AndroidManifest.xml.
 --target-sdk-version arg                          Default target SDK version to use for AndroidManifest.xml.
 --version-code arg                                Version code (integer) to inject into the AndroidManifest.xml if none is
                                                   present.
 --version-name arg                                Version name to inject into the AndroidManifest.xml if none is present.
 --shared-lib                                      Generates a shared Android runtime library.
 --static-lib                                      Generate a static Android library.
 --no-static-lib-packages                          Merge all library resources under the app's package.
 --non-final-ids                                   Generates R.java without the final modifier. This is implied when
                                                   --static-lib is specified.
 --stable-ids arg                                  File containing a list of name to ID mapping.
 --emit-ids arg                                    Emit a file at the given path with a list of name to ID mappings,
                                                   suitable for use with --stable-ids.
 --private-symbols arg                             Package name to use when generating R.java for private symbols.
                                                   If not specified, public and private symbols will use the application's
                                                   package name.
 --custom-package arg                              Custom Java package under which to generate R.java.
 --extra-packages arg                              Generate the same R.java but with different package names.
 --add-javadoc-annotation arg                      Adds a JavaDoc annotation to all generated Java classes.
 --output-text-symbols arg                         Generates a text file containing the resource symbols of the R class in
                                                   the specified folder.
 --auto-add-overlay                                Allows the addition of new resources in overlays without
                                                   <add-resource> tags.
 --rename-manifest-package arg                     Renames the package in AndroidManifest.xml.
 --rename-instrumentation-target-package arg       Changes the name of the target package for instrumentation. Most useful
                                                   when used in conjunction with --rename-manifest-package.
 -0 arg                                            File extensions not to compress.
 --split arg                                       Split resources matching a set of configs out to a Split APK.
                                                   Syntax: path/to/output.apk:<config>[,<config>[...]].
                                                   On Windows, use a semicolon ';' separator instead.
 -v                                                Enables verbose logging.
 -h                                                Displays this help menu

	at com.google.devtools.build.android.AaptCommandBuilder.execute(AaptCommandBuilder.java:318)
	at com.google.devtools.build.android.aapt2.ResourceLinker.linkProtoApk(ResourceLinker.java:423)
	at com.google.devtools.build.android.aapt2.ResourceLinker.link(ResourceLinker.java:531)
	at com.google.devtools.build.android.Aapt2ResourcePackagingAction.main(Aapt2ResourcePackagingAction.java:185)
	at com.google.devtools.build.android.ResourceProcessorBusyBox$Tool$14.call(ResourceProcessorBusyBox.java:144)
	at com.google.devtools.build.android.ResourceProcessorBusyBox.processRequest(ResourceProcessorBusyBox.java:240)
	at com.google.devtools.build.android.ResourceProcessorBusyBox.main(ResourceProcessorBusyBox.java:203)
```

**Provide the exact sequence of commands / steps that you executed before running into the problem**

.tf_configure.bazelrc
```
build --action_env PYTHON_BIN_PATH="/Applications/anaconda3/envs/android/bin/python"
build --action_env PYTHON_LIB_PATH="/Applications/anaconda3/envs/android/lib/python3.6/site-packages"
build --python_path="/Applications/anaconda3/envs/android/bin/python"
build:xla --define with_xla_support=true
build:opt --copt=-march=native
build:opt --copt=-Wno-sign-compare
build:opt --host_copt=-march=native
build:opt --define with_default_optimizations=true
build:v2 --define=tf_api_version=2
build --action_env ANDROID_NDK_HOME="/Users/norly/Documents/github/android/android-ndk-r17c"
build --action_env ANDROID_NDK_API_LEVEL="18"
build --action_env ANDROID_BUILD_TOOLS_VERSION="26.0.2"
build --action_env ANDROID_SDK_API_LEVEL="26"
build --action_env ANDROID_SDK_HOME="/Users/norly/library/Android/Sdk"
test --flaky_test_attempts=3
test --test_size_filters=small,medium
test --test_tag_filters=-benchmark-test,-no_oss,-oss_serial
test --build_tag_filters=-benchmark-test,-no_oss
test --test_tag_filters=-gpu,-nomac,-no_mac
test --build_tag_filters=-gpu,-nomac,-no_mac
build --action_env TF_CONFIGURE_IOS="0"
```

`sudo bazel build --cxxopt='--std=c++11' -c opt --config=android_arm --config=monolithic //tensorflow/lite/java:tensorflow-lite-with-select-tf-ops`

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by terryheo** [comment]
aapt2 tool of SDK level 26 doesn't look support the "--proto-format" option.
Could you try it again with SDK tool 28+ version?

**Comment by aijiart** [comment]
> aapt2 tool of SDK level 26 doesn't look support the "--proto-format" option.
> Could you try it again with SDK tool 28+ version?

Yes , I noticed yesterday.  It is supported from 28, Thanks

**Comment by nikzdevz** [comment]
@aijiart  How have you installed aapt version 28 on ubuntu as i dont know command
