### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices = -1 is not in [0, 4) [Op:GatherV2]

### ISSUE THREAD

**Issue by tomshalini** [tensorflow/tensorflow#35729]
I am getting InvalidArgumentError while running below code:

![Code](https://user-images.githubusercontent.com/59674741/72132628-b47a5280-337f-11ea-9dfb-f60609156f4f.jpeg)

### System information
- **OS Platform:Ubuntu 18.04
- **TensorFlow version: v2.0.0-rc2-26-g64c3d38 and tensorflow2.0.0
- **Python version**: Python 3.7.4

This code is failing while running for first epoch. It has to run for 400 steps in first epoch but getting failed at 256, 300 or sometimes any no of iteration.
Below is the error i am getting:
256/400 [==================>...........] - ETA: 3:40 - loss: 0.6932 - accuracy: 0.4968Traceback (most recent call last):
  File "train_model_latest.py", line 196, in <module>
    train_model()
  File "train_model_latest.py", line 168, in train_model
    callbacks=callbacks)
  File "/u/s/shalinis/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 1297, in fit_generator
    steps_name='steps_per_epoch')
  File "/u/s/shalinis/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_generator.py", line 265, in model_iteration
    batch_outs = batch_function(*batch_data)
  File "/u/s/shalinis/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 973, in train_on_batch
    class_weight=class_weight, reset_metrics=reset_metrics)
  File "/u/s/shalinis/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 264, in train_on_batch
    output_loss_metrics=model._output_loss_metrics)
  File "/u/s/shalinis/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_eager.py", line 311, in train_on_batch
    output_loss_metrics=output_loss_metrics))
  File "/u/s/shalinis/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_eager.py", line 252, in _process_single_batch
    training=training))
  File "/u/s/shalinis/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_eager.py", line 127, in _model_loss
    outs = model(inputs, **kwargs)
  File "/u/s/shalinis/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 891, in __call__
    outputs = self.call(cast_inputs, *args, **kwargs)
  File "/u/s/shalinis/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/sequential.py", line 256, in call
    return super(Sequential, self).call(inputs, training=training, mask=mask)
  File "/u/s/shalinis/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/network.py", line 708, in call
    convert_kwargs_to_constants=base_layer_utils.call_context().saving)
  File "/u/s/shalinis/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/network.py", line 860, in _run_internal_graph
    output_tensors = layer(computed_tensors, **kwargs)
  File "/u/s/shalinis/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 891, in __call__
    outputs = self.call(cast_inputs, *args, **kwargs)
  File "/u/s/shalinis/.local/lib/python3.7/site-packages/tensorflow_model_optimization/python/core/sparsity/keras/pruning_wrapper.py", line 233, in call
    update_op = tf_utils.smart_cond(training, add_update, no_op)
  File "/u/s/shalinis/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/utils/tf_utils.py", line 59, in smart_cond
    pred, true_fn=true_fn, false_fn=false_fn, name=name)
  File "/u/s/shalinis/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/framework/smart_cond.py", line 54, in smart_cond
    return true_fn()
  File "/u/s/shalinis/.local/lib/python3.7/site-packages/tensorflow_model_optimization/python/core/sparsity/keras/pruning_wrapper.py", line 227, in add_update
    [self.pruning_obj.conditional_mask_update()]):
  File "/u/s/shalinis/.local/lib/python3.7/site-packages/tensorflow_model_optimization/python/core/sparsity/keras/pruning_impl.py", line 245, in conditional_mask_update
    mask_update_distributed)
  File "/u/s/shalinis/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/distribute/distribute_lib.py", line 1917, in merge_call
    return self._merge_call(merge_fn, args, kwargs)
  File "/u/s/shalinis/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/distribute/distribute_lib.py", line 1924, in _merge_call
    return merge_fn(self._strategy, *args, **kwargs)
  File "/u/s/shalinis/.local/lib/python3.7/site-packages/tensorflow_model_optimization/python/core/sparsity/keras/pruning_impl.py", line 241, in mask_update_distributed
    no_update)
  File "/u/s/shalinis/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/u/s/shalinis/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/ops/control_flow_ops.py", line 1202, in cond
    result = true_fn()
  File "/u/s/shalinis/.local/lib/python3.7/site-packages/tensorflow_model_optimization/python/core/sparsity/keras/pruning_impl.py", line 232, in update_distributed
    new_threshold, new_mask = self._maybe_update_block_mask(weight)
  File "/u/s/shalinis/.local/lib/python3.7/site-packages/tensorflow_model_optimization/python/core/sparsity/keras/pruning_impl.py", line 128, in _maybe_update_block_mask
    return self._update_mask(weights)
  File "/u/s/shalinis/.local/lib/python3.7/site-packages/tensorflow_model_optimization/python/core/sparsity/keras/pruning_impl.py", line 102, in _update_mask
    current_threshold = array_ops.gather(values, k - 1)
  File "/u/s/shalinis/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/util/dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "/u/s/shalinis/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/ops/array_ops.py", line 3967, in gather
    return gen_array_ops.gather_v2(params, indices, axis, name=name)
  File "/u/s/shalinis/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_array_ops.py", line 4075, in gather_v2
    _six.raise_from(_core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices = -1 is not in [0, 4) [Op:GatherV2]

**Comment by amahendrakar** [comment]
@tomshalini,
In order to expedite the trouble-shooting process, could you please copy the complete code and paste it here (instead of the screenshot), so that it would be easy for us to reproduce it. Also, can you provide the saved model (Model_9Jan11AM.h5) you are using in your code. Thanks!

**Comment by tomshalini** [comment]
Please find below code for your reference:

from os import path, makedirs
from utility_files import model_utils
import local_configuration as config
from utility_files import tfrecords_utils as tfutils
import numpy as np
import tempfile
import zipfile
import os
from tensorflow_model_optimization.sparsity import keras as sparsity
from tensorflow import keras

'''
This file prunes the pre-trained model and save the pruned model to the location specified in the configuration file and 
validates the model on the complete validation data set.
Please set the pretrained model name along with its path to the variable - "keras_file" .
'''

################################ Hyper parameters of the model #################################

sequence_length = 60000                      # Number of samples per channel. A predetermined number.
training_examples = 12800                       # Number of files to be used for training. Maximum allowed number is the combined number in Sinus and AF folder
validation_examples = 3200                     # Number of files to be used for testing. Maximum allowed number is the combined number in Sinus and AF testing folder
batch_size = 32                              # Batch size for training and testing
batch_size_to_write_or_read_value = 2 * (1600)  # Number of examples to read from TF record for "tests" for final evaluation. (Max = validation_examples = 2 * (validation_examples/2))
lr = 1e-4                                    # Learning rate for the model
decay = 1e-3                                 # Decay rate for the model
number_of_channels = 2                       # Number of channels

def prune_model():

    tf_record_train = config.tf_record_file_base_path + "ecg_data_tf_CNN_float_60000.tfrecord"
    tf_record_test = config.tf_record_file_base_path + "ecg_data_tf_CNN_test_float_60000.tfrecord"
    tf_reader_train = tfutils.TFrecords(tf_record_train)                        # tfutils instance for training
    tf_reader_test = tfutils.TFrecords(tf_record_test)                          # tfutils instance for testing
    opt = keras.optimizers.Adam(lr=lr, decay=decay)

    validation_steps = int(validation_examples // batch_size)
    steps_per_epoch = int(training_examples // batch_size)

    keras_file = "/u/s/shalinis/PycharmProjects/half/Model_26_Nov_10AM_lr_0_0001_decay_0_001_sparse_dense_layers_epoch_15.h5"   #Path of Pre-trained model.
    model = keras.models.load_model(keras_file)
    print('Original Model Summary:')
    model.summary()

    end_step = np.ceil(1.0 * training_examples / batch_size).astype(np.int32) * 2
    pruning_params = {
        'pruning_schedule': sparsity.PolynomialDecay(initial_sparsity=0.50,
                                                     final_sparsity=0.90,
                                                     begin_step=0,
                                                     end_step=end_step,
                                                     frequency=100)
    }
    model = sparsity.prune_low_magnitude(model, **pruning_params)
    model.compile(optimizer=opt,  # Compile the model
                  loss='binary_crossentropy',
                  metrics=['accuracy'])
    model.summary()
    logdir = "/m/scratch/hive/shalini/logs/"
    print('Writing training logs to ' + logdir)
    callbacks = [
        sparsity.UpdatePruningStep(),
        sparsity.PruningSummaries(log_dir=logdir)
    ]
    model.fit_generator(
        model_utils._data_generator(tf_reader_train, batch_size=batch_size, sequence_length=sequence_length),
        validation_data=model_utils._data_generator(tf_reader_test, batch_size=batch_size,
                                                    sequence_length=sequence_length),
        validation_steps=validation_steps,
        steps_per_epoch=steps_per_epoch,
        epochs=2, verbose=1, shuffle=str,
        callbacks=callbacks,
        use_multiprocessing=False, workers=0)

    model_utils.final_model_validation(model, tf_record_test, batch_size_to_write_or_read_value)
    pruned_keras_file = "/m/scratch/hive/shalini/Model CheckPoints/SparPrunedModel_10Jan1730PM.h5"
    print('Saving model to: ', pruned_keras_file)
    keras.models.save_model(model, pruned_keras_file,
                            include_optimizer=False)

    final_model = sparsity.strip_pruning(model)
    final_model.summary()
    Finalpruned_keras_file = "/m/scratch/hive/shalini/Model CheckPoints/FinPrunedModel_10Jan1730PM.h5"
    print('Saving model to: ', Finalpruned_keras_file)
    keras.models.save_model(model, Finalpruned_keras_file,
                            include_optimizer=False)




    _, zip3 = tempfile.mkstemp('.zip')
    with zipfile.ZipFile(zip3, 'w', compression=zipfile.ZIP_DEFLATED) as f:
        f.write(keras_file)
    print("Size of the original model before compression: %.2f Mb"
          % (os.path.getsize(keras_file) / float(2 ** 20)))
    print("Size of the original model after compression: %.2f Mb"
          % (os.path.getsize(zip3) / float(2 ** 20)))

    _, zip3 = tempfile.mkstemp('.zip')
    with zipfile.ZipFile(zip3, 'w', compression=zipfile.ZIP_DEFLATED) as f:
        f.write(Finalpruned_keras_file)
    print("Size of the pruned model before compression: %.2f Mb"
          % (os.path.getsize(Finalpruned_keras_file) / float(2 ** 20)))
    print("Size of the pruned model after compression: %.2f Mb"
          % (os.path.getsize(zip3) / float(2 ** 20)))

if __name__ == "__main__":
    prune_model()

--------------------------------------------------------------------------------------------
Attached is the pretrained model. Please unzip this file first before using.

[Model_26_Nov_10AM_lr_0_0001_decay_0_001_sparse_dense_layers_epoch_15.h5.tar.gz](https://github.com/tensorflow/tensorflow/files/4047358/Model_26_Nov_10AM_lr_0_0001_decay_0_001_sparse_dense_layers_epoch_15.h5.tar.gz)

**Comment by amahendrakar** [comment]
@tomshalini,
Seems like you are importing user-defined/custom modules and config files in your code, hence I am facing [an error](https://colab.sandbox.google.com/gist/amahendrakar/5bc10431993d2cfd40774de21cd8fcd1/35729.ipynb) while reproducing the issue.

I'd suggest you to use [this](https://colab.sandbox.google.com/notebook#create=true&language=python3) link to run the code and share the Gist (File -> Save a copy as Github gist) with us. Thanks!

**Comment by amahendrakar** [comment]
Any updates regarding this issue? Thanks!

**Comment by tomshalini** [comment]
Could you please tell me reason of increasing model's parameter by prunning wrapper?

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
Thanks!
