### ISSUE TITLE
tensorflow-gpu Importerror: DLL load failed: DLL initialization routine failed.

### ISSUE THREAD

**Issue by heyheyheyheyhey1** [tensorflow/tensorflow#35766]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): windows 10 pro 1909
- TensorFlow installed from (source or binary): https://files.pythonhosted.org/packages/
- TensorFlow version:1.8.0
- Python version:3.6.8
- Installed using virtualenv? pip? conda?: pip
- CUDA/cuDNN version:CUDA 9.0/cuDNN7.0(and cuDNN7.1)
- GPU model and memory:GTX1050 (4GB)

**Describe the problem**

Import tensorflow error ,it reads  DLL initialization routine failed,i have changed  vc++ 2015  runtime libs(both x64 and x86) and using Nvidia display driver version 385.54(CUDA9.0 default)

If I use tensorflow-gpu 2.1.0 and import tensorflow, python will crash immediately, but if it is 1.8.0 or 1.7.0, python will run for a few seconds or so, and then the above error occurs

**Any other info / logs**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

```
Traceback (most recent call last):
File "C:\Users\Hasee\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
from tensorflow.python.pywrap_tensorflow_internal import *
File "C:\Users\Hasee\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 18, in <module>  
_pywrap_tensorflow_internal = swig_import_helper()
File "C:\Users\Hasee\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 17, in swig_import_helper
return importlib.import_module(mname)
File "C:\Users\Hasee\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
Importerror: DLL load failed: DLL initialization routine failed.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "f:/DL/1 hello world/index.py", line 1, in <module>
import tensorflow as tf
File "C:\Users\Hasee\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
File "C:\Users\Hasee\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
from tensorflow.python import pywrap_tensorflow
File "C:\Users\Hasee\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
raise ImportError(msg)
ImportError: Traceback (most recent call last):
File "C:\Users\Hasee\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
from tensorflow.python.pywrap_tensorflow_internal import *
File "C:\Users\Hasee\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 18, in <module>  
_pywrap_tensorflow_internal = swig_import_helper()
File "C:\Users\Hasee\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 17, in swig_import_helper
return importlib.import_module(mname)
File "C:\Users\Hasee\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
Importerror: DLL load failed: DLL initialization routine failed.
Failed to load the native TensorFlow runtime.
 DLL initialization routine failed
```

**Comment by TyrionWarMage** [comment]
Please try to install the correct VisualC++ Redist. - depending on which version, you have installed, you need a newer one - see https://github.com/tensorflow/tensorflow/issues/35036#issuecomment-565605748

**Comment by heyheyheyheyhey1** [comment]
OK guys,i currently solved this problem,It is because of my CPU is Pentium G5420 and it doesnt support AVX2 instruction set. So do not install tensorflow by pip and download tensorflow for SSE2 at  https://github.com/fo40225/tensorflow-windows-wheel

**Comment by ravikyram** [comment]
@heyheyheyheyhey1 

Please, see [hardware requirements](https://www.tensorflow.org/install/pip?lang=python3#hardware-requirements). Uninstall tensorflow using pip and reinstall using "`conda install TensorFlow" ` and check. Can we close this thread if your issue got resolved. Thanks!

**Comment by heyheyheyheyhey1** [comment]
> @heyheyheyheyhey1
> 
> Please, see [hardware requirements](https://www.tensorflow.org/install/pip?lang=python3#hardware-requirements). Uninstall tensorflow using pip and reinstall using "`conda install TensorFlow" ` and check. Can we close this thread if your issue got resolved. Thanks!

Bro, is there any differences using conda or pip?(I am sure my problem originate from my CPU's dosent support AVX)

**Comment by ravikyram** [comment]
@heyheyheyheyhey1 
Please, go through the [article](https://towardsdatascience.com/stop-installing-tensorflow-using-pip-for-performance-sake-5854f9d9eb0c) and # 23683.Can we close this thread as it looks like you already solved the problem. Thanks!

**Comment by heyheyheyheyhey1** [comment]
> @heyheyheyheyhey1
> Please, go through the [article](https://towardsdatascience.com/stop-installing-tensorflow-using-pip-for-performance-sake-5854f9d9eb0c) and #23683.Can we close this thread as it looks like you already solved the problem. Thanks!

yes,please
