### ISSUE TITLE
A Subclass of Custom Loss Function Is not Trackable as an Argument in Checkpoint

### ISSUE THREAD

**Issue by yourtheron** [tensorflow/tensorflow#35763]
Tf Version: 2.0.0
Python: 3.7.5
IDE: Spyder
OS: Windows

I wrote a subclass of custom loss function and tried to list it in the arguments of a checkpoint as follows. The model is an arbitrary one
```
class SoftDiceLoss(tf.keras.losses.Loss):
    '''
    SoftDiceLoss calculates multi-class soft dice loss
    loss = avg_batch(1-(sum(W_k*sum(yPred.*yTrue)))/(sum(W_ksum(yPred^2+yTrue^2))))
    where W_k = 1/(number of voxels in class k)^wPow
    Class number of segmented regions includes background
    Args:
        yPred/yTrue: prediced and desired outputs shaped as [mbSize, classNum, tensor dimensions]. Also, both must be float-point
    	wPow, power of weiight. A higher one favours classes with a smaller number of voxels
    Return:
        loss: a scalar tensor
    '''
    def __init__(self, wPow=2.0, name='SoftDiceLoss'):
        super().__init__(name=name)
        self.epsilon = 1e-16 
        self.wPow = wPow

    def call(self, yPred, yTrue):
        yTrue =tf.dtypes.cast(yTrue, dtype=yPred.dtype)
		# Dot product yPred and yTrue and sum them up for each datum and class
        crossProd=tf.multiply(yPred, yTrue)
		# As a symbolic tensor, dimensions and shapes etc. cannot be extracted from data, nor can it be used in subroutines.
        crossProdSum=tf.math.reduce_sum(crossProd, axis=np.arange(2, 5)) #tf.rank(yTrue)))
		# Calculate weight for each datum and class 
        weight = tf.math.reduce_sum(yTrue, axis=np.arange(2, 5))#tf.rank(yTrue)))
		#weight = tf.math.divide(1, tf.math.square(weight)+self.epsilon)
        weight = tf.math.divide(1, tf.math.pow(weight, self.wPow)+self.epsilon)
		# Weighted sum over classes
        numerator = 2*tf.math.reduce_sum(tf.multiply(crossProdSum, weight), axis=1)
		# Saquared summation 
        yySum = tf.math.reduce_sum(tf.math.square(yPred) + tf.math.square(yTrue), axis=np.arange(2, 5))#tf.rank(yTrue)))
		# Weighted sum over classes
        denominator = tf.math.reduce_sum(tf.multiply(weight, yySum), axis=1)
		# Get individual loss and average over minibatch
        loss = tf.math.reduce_mean(1 - tf.math.divide(numerator, denominator+self.epsilon))
			
        return loss
    
    def get_config(self):
        config = super(SoftDiceLoss, self).get_config()
        return config

curOpt = tf.keras.optimizers.Adam(learning_rate=1e-4)	
lossFunc=SoftDiceLoss(2.0)
ckpt = tf.train.Checkpoint(model=myModel(...), optimizer=curOpt, lossFunc=lossFunc, accFunc=accFunc)

```

I got the following error
```
ckpt = tf.train.Checkpoint(model=myModel(...), optimizer=curOpt, lossFunc=lossFunc, accFunc=accFunc)
Traceback (most recent call last):

  File "<ipython-input-17-a4d9163bdda3>", line 2, in <module>
    optimizer=curOpt, lossFunc=lossFunc, accFunc=accFunc)

  File "D:\TProgramFiles\Anaconda3\envs\keras-gpu\lib\site-packages\tensorflow_core\python\training\tracking\util.py", line 1779, in __init__
    % (v,))

ValueError: `Checkpoint` was expecting a trackable object (an object derived from `TrackableBase`), got <SoftDiceLoss object at 0x0000000011F6F7C8>. If you believe this object should be trackable (i.e. it is part of the TensorFlow Python API and manages state), please open an issue.
```
I am not sure if a subclass is trackable or not. Is that an intention of design? Or shall such a feature be added? 
By the way, if I change the subclass into a normal function, it works fine. Actually, my accFunc(...) is just a normal function.

**Comment by oanush** [comment]
@yourtheron ,
Can you please please provide complete reproducible code to reflect this issue?Thanks!

**Comment by yourtheron** [comment]
@oanush Sure. The following code snippet can reproduce the issue, and I have verified it on Colab
```
import tensorflow as tf
from tensorflow.keras import layers, activations

class C3BR(tf.keras.Model):
    def __init__(self, filterNum, kSize, strSize, padMode, dFormat='channels_first'):
        super(C3BR, self).__init__()
        if dFormat == 'channels_first':
            self.conAx = 1
        else:
            self.conAx = -1
        self.kSize = (kSize, kSize, kSize)
        self.conv = layers.Conv3D(filters=filterNum, kernel_size=self.kSize, strides=strSize, padding=padMode, data_format=dFormat)
        self.BN = layers.BatchNormalization(axis=self.conAx)
        self.Relu = layers.ReLU()
    
    def call(self, inputs, ifTrain=False):
        x = self.conv(inputs)
        x= self.BN(x, training=ifTrain)
        outputs = self.Relu(x)
        return outputs

    def build_model(self, input_shape):
        ''' A work-around to define dimensions of signals through the NN'''
        self.build(input_shape)
        inputs = tf.keras.Input(shape=input_shape[1:])
        _ = self.call(inputs, True) 


class lossExample(tf.keras.losses.Loss):

    def __init__(self, name='lossExample'):
        super().__init__(name=name)
		
    def call(self, yPred, yTrue):
			
        returntf.redyuce_mean(yPred - yTrue)
    

curOpt = tf.keras.optimizers.Adam(learning_rate=1e-4)	
lossFunc=lossExample()
ckpt = tf.train.Checkpoint(model=C3BR(32, 3, 1, 'valid'), optimizer=curOpt, lossFunc=lossFunc)

```

**Comment by oanush** [comment]
Issue replicating for [tf-nightly](https://colab.sandbox.google.com/gist/oanush/9bfa54eea4b310293ecb54ce9297556a/35888.ipynb).Thanks!

**Comment by jvishnuvardhan** [comment]
This is still reproducing same error. Here is the full error trace for our reference. Thanks!

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-70b3948a7d11> in <module>()
     39 curOpt = tf.keras.optimizers.Adam(learning_rate=1e-4)
     40 lossFunc=lossExample()
---> 41 ckpt = tf.train.Checkpoint(model=C3BR(32, 3, 1, 'valid'), optimizer=curOpt, lossFunc=lossFunc)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/tracking/util.py in __init__(self, **kwargs)
   1816              "object should be trackable (i.e. it is part of the "
   1817              "TensorFlow Python API and manages state), please open an issue.")
-> 1818             % (v,))
   1819     self._save_counter = None  # Created lazily for restore-on-create.
   1820     self._save_assign_op = None

ValueError: `Checkpoint` was expecting a trackable object (an object derived from `TrackableBase`), got <__main__.lossExample object at 0x7ff535468cf8>. If you believe this object should be trackable (i.e. it is part of the TensorFlow Python API and manages state), please open an issue.
```

**Comment by allenlavoie** [comment]
Does the loss have any variables? It doesn't look like it, in which case there isn't anything to checkpoint.

Basically, what should the Checkpoint object do with the loss object?

**Comment by rmothukuru** [comment]
@yourtheron,
Can you please respond to the [above comment](https://github.com/tensorflow/tensorflow/issues/35763#issuecomment-595392657)? Thanks!
