### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found

### ISSUE THREAD

**Issue by igururaman** [tensorflow/tensorflow#35773]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information** 64 bit operating system
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 Home Single Language
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):not sure
- TensorFlow version:
- Python version:3.7.6
- Installed using virtualenv? pip? conda?:pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**

conda create -n tensorflow python=3.7
activate tensorflow
pip install --ignore-installed --upgrade tensorflow
python
import tensorflow as tf

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

Traceback (most recent call last):
  File "C:\Users\Asus Pc\AppData\Local\conda\conda\envs\tensorflow_cpu\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Asus Pc\AppData\Local\conda\conda\envs\tensorflow_cpu\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Asus Pc\AppData\Local\conda\conda\envs\tensorflow_cpu\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Asus Pc\AppData\Local\conda\conda\envs\tensorflow_cpu\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Asus Pc\AppData\Local\conda\conda\envs\tensorflow_cpu\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Asus Pc\AppData\Local\conda\conda\envs\tensorflow_cpu\lib\site-packages\tensorflow\__init__.py", line 101, in <module>
    from tensorflow_core import *
  File "C:\Users\Asus Pc\AppData\Local\conda\conda\envs\tensorflow_cpu\lib\site-packages\tensorflow_core\__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\Asus Pc\AppData\Local\conda\conda\envs\tensorflow_cpu\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\Users\Asus Pc\AppData\Local\conda\conda\envs\tensorflow_cpu\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "C:\Users\Asus Pc\AppData\Local\conda\conda\envs\tensorflow_cpu\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\Asus Pc\AppData\Local\conda\conda\envs\tensorflow_cpu\lib\site-packages\tensorflow_core\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Asus Pc\AppData\Local\conda\conda\envs\tensorflow_cpu\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Asus Pc\AppData\Local\conda\conda\envs\tensorflow_cpu\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Asus Pc\AppData\Local\conda\conda\envs\tensorflow_cpu\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Asus Pc\AppData\Local\conda\conda\envs\tensorflow_cpu\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Asus Pc\AppData\Local\conda\conda\envs\tensorflow_cpu\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Asus Pc\AppData\Local\conda\conda\envs\tensorflow_cpu\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

**Comment by TyrionWarMage** [comment]
Please try to install the correct VisualC++ Redist. - see https://github.com/tensorflow/tensorflow/issues/35036#issuecomment-565605748

**Comment by ravikyram** [comment]
Just to verify did you get chance to follow instructions from [TensorFlow website ](https://www.tensorflow.org/install/source_windows).Please, let us know how it progress. 
What is make/model of your cpu?
I suspect your cpu model does not support AVX instructions sets.See [hardware requirements](https://www.tensorflow.org/install/pip?lang=python3#hardware-requirements)
Thanks!

**Comment by igururaman** [comment]
Thanks Ravi, you are correct so i setup account on GCP to work on tensorflow

regards
Guru

**Comment by ravikyram** [comment]
@igururaman 
Thanks Guru for the prompt response. Can we close this thread if it solves your question. Thanks!

**Comment by igururaman** [comment]
Yes please

Regards.
Guru

**Comment by mihaimaruseac** [comment]
Closing per request
