### ISSUE TITLE
Tensorflow import issue

### ISSUE THREAD

**Issue by arnabnag2000** [tensorflow/tensorflow#35772]
error code

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\USER\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "C:\Users\USER\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "C:\Users\USER\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\core\framework\graph_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
  File "C:\Users\USER\AppData\Local\Programs\Python\Python36\lib\site-packages\google\protobuf\descriptor.py", line 47, in <module>
    from google.protobuf.pyext import _message
ImportError: DLL load failed: The specified procedure could not be found.

python version 3.6
tensorflow version 1.5(installed via pip)
visual studio c++ installed
using a 64 bit machine

**Comment by TyrionWarMage** [comment]
Are you sure, you installed the correct VisualC++ Redist? - see https://github.com/tensorflow/tensorflow/issues/35036#issuecomment-565605748

**Comment by arnabnag2000** [comment]
yes VisualC++ Redist is already installed

**Comment by oanush** [comment]
@arnabnag2000 ,
I see that you are trying to install tf-1.5 version which is very old, please try installing latest version of TF  like 1.15. Also follow the instruction from[ TensorFlow website](https://www.tensorflow.org/install/source_windows). You can have a look on similar issue #[22794](https://github.com/tensorflow/tensorflow/issues/22794)  and #[10033](https://github.com/tensorflow/tensorflow/issues/10033) . let us know if that helps. Looks like you need to add path for CUDA and CuDNN.Thanks!

**Comment by arnabnag2000** [comment]
installed tensorflow 1.15 and cuda and cudnn
>>> import tensorflow
2020-01-13 12:01:28.089835: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\USER\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\__init__.py", line 99, in <module>
    from tensorflow_core import *
  File "C:\Users\USER\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_core\__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\USER\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_core\python\__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "C:\Users\USER\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_core\core\framework\graph_pb2.py", line 7, in <module>
    from google.protobuf import descriptor as _descriptor
  File "C:\Users\USER\AppData\Local\Programs\Python\Python36\lib\site-packages\google\protobuf\descriptor.py", line 47, in <module>
    from google.protobuf.pyext import _message
ImportError: DLL load failed: The specified procedure could not be found.

**Comment by oanush** [comment]
> installed tensorflow 1.15 and cuda and cudnn
> and visual studio 2017
> 
> > > > import tensorflow
> > > > 2020-01-13 12:01:28.089835: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
> > > > Traceback (most recent call last):
> > > > File "", line 1, in 
> > > > File "C:\Users\USER\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow__init__.py", line 99, in 
> > > > from tensorflow_core import *
> > > > File "C:\Users\USER\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_core__init__.py", line 28, in 
> > > > from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
> > > > File "C:\Users\USER\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow__init__.py", line 50, in **getattr**
> > > > module = self._load()
> > > > File "C:\Users\USER\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow__init__.py", line 44, in _load
> > > > module = _importlib.import_module(self.**name**)
> > > > File "C:\Users\USER\AppData\Local\Programs\Python\Python36\lib\importlib__init__.py", line 126, in import_module
> > > > return _bootstrap._gcd_import(name[level:], package, level)
> > > > File "C:\Users\USER\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_core\python__init__.py", line 52, in 
> > > > from tensorflow.core.framework.graph_pb2 import *
> > > > File "C:\Users\USER\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_core\core\framework\graph_pb2.py", line 7, in 
> > > > from google.protobuf import descriptor as _descriptor
> > > > File "C:\Users\USER\AppData\Local\Programs\Python\Python36\lib\site-packages\google\protobuf\descriptor.py", line 47, in 
> > > > from google.protobuf.pyext import _message
> > > > ImportError: DLL load failed: The specified procedure could not be found.

@arnabnag2000 ,
Is the issue resolved ?if no mentiond CUDA and CuDNN versions.Thanks!

**Comment by arnabnag2000** [comment]
no its not resolved
CUDA VS 10.0
CuDNN VS 7.64

**Comment by oanush** [comment]
@arnabnag2000 ,
Can you check the [issue](https://github.com/tensorflow/tensorflow/issues/28095) and let us know if its helped? Thanks!

**Comment by oanush** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
