### ISSUE TITLE
DLL load failed even though I have everything installed and I only upgraded tensorflow to 2.10

### ISSUE THREAD

**Issue by rajcivils** [tensorflow/tensorflow#35789]
Hello I am using tensorflow gpu version. I had tf 2.0 gpu version but tensorboard was giving me some trouble. It was using tf1.4 tensorboard. So I uninstalled tf1.4 and tensorboard1.4 and then upgraded tf2.0 gpu version to tf2.1 gpu version but when I do it it gives me some problems. Here is my system information.
**System information**
- OS - Windows 10
- TensorFlow version: 2.1(after upgrading)
- Python version:3.6.9
- I am using conda environment which I have named tensorflow_gpuenv
- CUDA version: 10.0.130
-CUDNN version: 7.6.0
- GPU model: NVIDIA 1080 TI
So now I have been using gpu version of tensorflow since a long time. I have everything installed and I also have vs if you are wondering I do not have that and vs 2017 more specifically. And by the way my tf 1 was installed using conda and tf 2 using pip and then tf 2.1 also using pip. So know when I 
```py
import tensorflow
```
it gives me the following error - 

```py
Traceback (most recent call last):
  File "C:\Users\Tejas\Anaconda3\envs\tensorflow_gpuenv\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Tejas\Anaconda3\envs\tensorflow_gpuenv\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Tejas\Anaconda3\envs\tensorflow_gpuenv\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Tejas\Anaconda3\envs\tensorflow_gpuenv\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Tejas\Anaconda3\envs\tensorflow_gpuenv\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Tejas\Anaconda3\envs\tensorflow_gpuenv\lib\site-packages\tensorflow\__init__.py", line 101, in <module>
    from tensorflow_core import *
  File "C:\Users\Tejas\Anaconda3\envs\tensorflow_gpuenv\lib\site-packages\tensorflow_core\__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\Tejas\Anaconda3\envs\tensorflow_gpuenv\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\Users\Tejas\Anaconda3\envs\tensorflow_gpuenv\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "C:\Users\Tejas\Anaconda3\envs\tensorflow_gpuenv\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\Tejas\Anaconda3\envs\tensorflow_gpuenv\lib\site-packages\tensorflow_core\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Tejas\Anaconda3\envs\tensorflow_gpuenv\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Tejas\Anaconda3\envs\tensorflow_gpuenv\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Tejas\Anaconda3\envs\tensorflow_gpuenv\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Tejas\Anaconda3\envs\tensorflow_gpuenv\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Tejas\Anaconda3\envs\tensorflow_gpuenv\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Tejas\Anaconda3\envs\tensorflow_gpuenv\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.
```

**Comment by gadagashwini** [comment]
@rajcivils, Can you check CPU model does your CPU support AVX instruction sets?
Please take a look at issue [#19584](https://github.com/tensorflow/tensorflow/issues/19584). 
https://www.tensorflow.org/install/pip?lang=python3#hardware-requirements. Thanks!

**Comment by rajcivils** [comment]
@gadagashwini You can close this issue. I want to make a new issue as I installed tensorflow from start.

**Comment by mihaimaruseac** [comment]
Closing as requested
