### ISSUE TITLE
[TF2]     tf.TensorArray Error with Keras

### ISSUE THREAD

**Issue by XMaster96** [tensorflow/tensorflow#35798]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): YES
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04 LTS
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): v2.1.0-rc2-17-ge5bf8de 2.1.0
- Python version: 3.6

I took a `tf.TensorArray` [sample](https://www.tensorflow.org/guide/function#batching) from the documentation and wrapt it in a custom Keras Layer. The Layer works fine when I directly call the layer or the model, but when I user `model.predict` I get an error.

Code sample:
```
import tensorflow as tf

class Test_Layer(tf.keras.layers.Layer):

    def __init__(self):
        super(Test_Layer, self).__init__()

    @tf.function
    def call(self, x):
        result = tf.TensorArray(tf.int32, size=x.shape[0])
        for i in tf.range(x.shape[0]):
            if x[i] > 0:
                result = result.write(i, x[i] ** 2)
            else:
                result = result.write(i, x[i])
        return result.stack()



test_layer = Test_Layer()

out = test_layer(tf.range(-5, 5))
print(out) #works fine:= tf.Tensor([-5 -4 -3 -2 -1  0  1  4  9 16], shape=(10,), dtype=int32)


test_model = tf.keras.models.Sequential([test_layer])
test_model.compile(loss=tf.losses.mse)


out = test_model(tf.range(-5, 5))
print(out) #works fine:= tf.Tensor([-5 -4 -3 -2 -1  0  1  4  9 16], shape=(10,), dtype=int32)


out = test_model.predict(tf.range(-5, 5))
print(out) #ERROR
```

Traceback:
```
Traceback (most recent call last):
  File "/media/jan/buffer/RNN/test_2.py", line 34, in <module>
    out = test_model.predict(tf.range(-5, 5))
  File "lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py", line 1013, in predict
    use_multiprocessing=use_multiprocessing)
  File "lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 498, in predict
    workers=workers, use_multiprocessing=use_multiprocessing, **kwargs)
  File "lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 426, in _model_iteration
    use_multiprocessing=use_multiprocessing)
  File "lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 646, in _process_inputs
    x, y, sample_weight=sample_weights)
  File "lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py", line 2346, in _standardize_user_data
    all_inputs, y_input, dict_inputs = self._build_model_with_inputs(x, y)
  File "lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py", line 2572, in _build_model_with_inputs
    self._set_inputs(cast_inputs)
  File "lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py", line 2659, in _set_inputs
    outputs = self(inputs, **kwargs)
  File "lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 773, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "lib/python3.6/site-packages/tensorflow_core/python/keras/engine/sequential.py", line 281, in call
    outputs = layer(inputs, **kwargs)
  File "lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 773, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 568, in __call__
    result = self._call(*args, **kwds)
  File "lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 606, in _call
    results = self._stateful_fn(*args, **kwds)
  File "lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2362, in __call__
    graph_function, args, kwargs = self._maybe_define_function(args, kwargs)
  File "lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2703, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2593, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "lib/python3.6/site-packages/tensorflow_core/python/framework/func_graph.py", line 978, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 439, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 3211, in bound_method_wrapper
    return wrapped_fn(*args, **kwargs)
  File "lib/python3.6/site-packages/tensorflow_core/python/framework/func_graph.py", line 968, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in converted code:

    test_2.py:10 call  *
        result = tf.TensorArray(tf.int32, size=x.shape[0])
    lib/python3.6/site-packages/tensorflow_core/python/ops/tensor_array_ops.py:1078 __init__
        name=name)
    lib/python3.6/site-packages/tensorflow_core/python/ops/tensor_array_ops.py:444 __init__
        raise ValueError("Size must be provided if flow is not provided")

    ValueError: Size must be provided if flow is not provided

```

**Comment by ravikyram** [comment]
I have tried on colab with TF version 2.1.0-rc2, 2.2.0-dev20200113 and was able to reproduce the issue.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/240c734bb97240517cb6208aa5c0fbb4/untitled554.ipynb). Thanks!

**Comment by qlzh727** [comment]
Thanks for reporting the issue.

The root cause is not because of TensorArray, but the way it is used. The important part here is "x.shape[0]". Note that x.shape returns the static shape of x. In the case of model.predict, since the batch size is not configured on the model, we tend to build the graph with a dynamic batch size, so that the same tf.function can be used with different batch size inputs. The result of x.shape is [None, 1] and then cause the tensorarray to fail to init.

If you change it to "tf.shape(x)[0]", which is the dynamic shape, tensorarray will correctly init even the batch is not known at the time. Hope this can be a workaround for you.
