### ISSUE TITLE
Creating outputs from the final_state returned by dynamic_rnn causes conversion to fail

### ISSUE THREAD

**Issue by xkr1** [tensorflow/tensorflow#35818]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS 7
- TensorFlow installed from (source or binary): binary
- TensorFlow version (or github SHA if from source): r1.14

**Command used to run the converter or code if you’re using the Python API**
import tensorflow as tf

converter = tf.lite.TFLiteConverter.from_saved_model('./savedmodel')
tflite_model = converter.convert()
open("lstm.tflite", "wb").write(tflite_model)

**The output from the converter invocation**

Traceback (most recent call last):
  File "saved2lite.py", line 4, in <module>
    tflite_model = converter.convert()
  File "/workdir/env-cpu/lib/python2.7/site-packages/tensorflow/lite/python/lite.py", line 898, in convert
    **converter_kwargs)
  File "/workdir/env-cpu/lib/python2.7/site-packages/tensorflow/lite/python/convert.py", line 404, in toco_convert_impl
    input_data.SerializeToString())
  File "/workdir/env-cpu/lib/python2.7/site-packages/tensorflow/lite/python/convert.py", line 172, in toco_convert_protos
    "TOCO failed. See console for info.\n%s\n%s\n" % (stdout, stderr))
tensorflow.lite.python.convert.ConverterError: TOCO failed. See console for info.
2020-01-13 14:56:27.199876: F tensorflow/lite/toco/tooling_util.cc:918] Check failed: GetOpWithOutput(model, output_array) Specified output array "lstm/body/encoder/rnn/while/Identity_4" is not produced by any op in this graph. Is it a typo? This should not happen. If you trigger this error please send a bug report (with code to reporduce this error), to the TensorFlow Lite team.

**Failure details**

Model conversion fails when final_state is returned as an output

**Any other info / logs**

relevant code in model definition:

output, next_state = tf.compat.v1.lite.experimental.nn.dynamic_rnn(...)
c_out = next_state[0].c
h_out = next_state[0].h

relevant code in conversion to SavedModel (which does work):

tensor_info_c_out = tf.saved_model.utils.build_tensor_info(c_out)
tensor_info_h_out = tf.saved_model.utils.build_tensor_info(h_out)

prediction_signature = tf.saved_model.signature_def_utils.build_signature_def(inputs = {'x': x}, outputs = {'y': output, 'c_out': c_out, 'h_out':h_out), method_name=tf.saved_model.signature_constants.PREDICT_METHOD_NAME)

The TFLite conversion works if I don't return the next state variables, c_out and h_out, but I need those to run the next step of the prediction.

If I run the conversion with tfnightly (using the same SavedModel file saved using 1.14) I get a different, seemingly unrelated, error:

Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: CAST, FULLY_CONNECTED, GATHER, MUL, NOT_EQUAL, RESHAPE, SOFTMAX, SQUEEZE, TOPK_V2. Here is a list of operators for which you will need custom implementations: TensorListFromTensor, TensorListReserve, TensorListStack, While.

**Comment by gargn** [comment]
Can you try using the new experimental converter on the `tf-nightly` or on 2.1 branch which has more comprehensive support for `dynamic_rnn`. You can enable the experimental converter by setting `converter.experimental_new_converter = True` when converting the model. The code will look something like the following:

```
converter = tf.lite.TFLiteConverter(saved_model_dir)
converter.experimental_new_converter = True
converter.convert()
```

**Comment by xkr1** [comment]
Hi gargn, thanks for taking the time to respond, much appreciated.

I installed tf-nightly-cpu, with tf.__version__: 2.1.0-dev20200102 and enabled the new converter.

I now see different error, but it's not clear to me exactly what the error is this time:

WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'lstm/symbol_modality_4099_512/target_emb/weights_0:0' shape=(4099, 512) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'lstm/symbol_modality_4099_512/softmax/weights_0:0' shape=(4099, 512) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'lstm/symbol_modality_4099_512/target_emb/weights_0:0' shape=(4099, 512) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'lstm/symbol_modality_4099_512/softmax/weights_0:0' shape=(4099, 512) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().
2020-01-14 08:53:56.676776: I tensorflow/core/grappler/devices.cc:60] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0 (Note: TensorFlow was not compiled with CUDA support)
2020-01-14 08:53:56.676908: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2020-01-14 08:53:57.025281: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:815] Optimization results for grappler item: graph_to_optimize
2020-01-14 08:53:57.025320: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:817]   constant_folding: Graph size after: 65 nodes (-37), 66 edges (-39), time = 209.377ms.
2020-01-14 08:53:57.025331: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:817]   constant_folding: Graph size after: 65 nodes (0), 66 edges (0), time = 62.395ms.
2020-01-14 08:53:57.025342: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:815] Optimization results for grappler item: __inference_lstm_body_encoder_rnn_while_body_226_118_frozen
2020-01-14 08:53:57.025353: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:817]   constant_folding: Graph size after: 109 nodes (-1), 110 edges (-2), time = 4.845ms.
2020-01-14 08:53:57.025364: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:817]   constant_folding: Graph size after: 109 nodes (0), 110 edges (0), time = 2.665ms.
2020-01-14 08:53:57.025374: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:815] Optimization results for grappler item: __inference_lstm_body_encoder_rnn_while_cond_225_27_frozen
2020-01-14 08:53:57.025385: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:817]   constant_folding: Graph size after: 25 nodes (0), 7 edges (0), time = 0.522ms.
2020-01-14 08:53:57.025395: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:817]   constant_folding: Graph size after: 25 nodes (0), 7 edges (0), time = 0.458ms.
Traceback (most recent call last):
  File "saved2lite.py", line 5, in <module>
    tflite_model = converter.convert()
  File "/workdir/exp/lstm/tf-nightly-env/lib/python2.7/site-packages/tensorflow_core/lite/python/lite.py", line 490, in convert
    **converter_kwargs)
  File "/workdir/exp/lstm/tf-nightly-env/lib/python2.7/site-packages/tensorflow_core/lite/python/convert.py", line 476, in toco_convert_impl
    enable_mlir_converter=enable_mlir_converter)
  File "/workdir/exp/lstm/tf-nightly-env/lib/python2.7/site-packages/tensorflow_core/lite/python/convert.py", line 215, in toco_convert_protos
    raise ConverterError("See console for info.\n%s\n%s\n" % (stdout, stderr))
tensorflow.lite.python.convert.ConverterError: See console for info.
WARNING:tensorflow:Falling back to tensorflow client, its recommended to install the cloud tpu client directly with pip install cloud-tpu-client .
2020-01-14 08:53:59.632245: W tensorflow/compiler/mlir/lite/python/graphdef_to_tfl_flatbuffer.cc:108] Ignored output_format.
2020-01-14 08:53:59.632389: W tensorflow/compiler/mlir/lite/python/graphdef_to_tfl_flatbuffer.cc:114] Ignored drop_control_dependency.
2020-01-14 08:53:59.768696: I tensorflow/core/platform/profile_utils/cpu_utils.cc:101] CPU Frequency: 2593685000 Hz
2020-01-14 08:53:59.771053: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x57b6950 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-01-14 08:53:59.771071: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version

The return code of the process called on line 201 of tensorflow_core/lite/python/convert.py is -11 if that helps.

--

I tried backing off to the conversion that works in 1.14 (without returning the LSTM state) and see a different error with the new converter in tf-nightly:

error: Convert ophint failed, malformed inputs or outputs.
Traceback (most recent call last):
  File "/workdir/exp/lstm/tf-nightly-env/bin/toco_from_protos", line 8, in <module>
    sys.exit(main())
  File "/workdir/exp/lstm/tf-nightly-env/lib/python2.7/site-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 93, in main
    app.run(main=execute, argv=[sys.argv[0]] + unparsed)
  File "/workdir/exp/lstm/tf-nightly-env/lib/python2.7/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/workdir/exp/lstm/tf-nightly-env/lib/python2.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/workdir/exp/lstm/tf-nightly-env/lib/python2.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/workdir/exp/lstm/tf-nightly-env/lib/python2.7/site-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 56, in execute
    enable_mlir_converter)
Exception: <unknown>:0: error: Convert ophint failed, malformed inputs or outputs.

This example works in 1.14, which leads me to suspect that there may be an incompatibility between SavedModel files created with 1.14 and the tflite converter in tf-nightly?

**Comment by gargn** [comment]
@renjie-liu Any insight into this error?

**Comment by renjie-liu** [comment]
yeah, the final_state is not supported for the fused lstm op.

Can you use normal keras lstm instead? please see the example here: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/examples/experimental_new_converter/keras_lstm.ipynb

**Comment by xkr1** [comment]
Thanks, I'm able to run that example.

My end-goal is to have an LSTM that I can run in streaming mode using TFLite. That example runs offline, but is it possible to return the state from the LSTM such that the LSTM can be fed one sample at a time (with the corresponding previous state) to give equivalent results to the offline mode?

Is there any documentation as to how this could be achieved, and if it is possible, is there a similar solution that would work with the non-eager execution workflow (i.e. TF1.14).

Thanks again for your help

**Comment by xkr1** [comment]
To answer my own question (and help anyone that may be looking for the same info), I think I'm at least partially there after familiarising myself a little with the Keras layers.

I modified the code as follows (maybe this is possible also within the tf.keras.models.Sequential function but I haven't looked in detail at that):

inputs = tf.keras.layers.Input(shape=(28, 28), name='input')
output_lstm, **state_h, state_c** = tf.keras.layers.LSTM(20, **return_state=True**, name='encoder')(inputs)
output_flatten = tf.keras.layers.Flatten()(output_lstm)
output = tf.keras.layers.Dense(10, activation=tf.nn.softmax, name='output')(output_flatten)

model = tf.keras.Model([inputs], [output])
**model2 = tf.keras.Model([inputs], [output, state_h, state_c])**

...

converter = tf.lite.TFLiteConverter.from_keras_model(**model2**)

gives a TFLite model that provides the output class distribution and c/h elements of the LSTM state. Next step is to feed these back in to the model, but that looks to be the easier part.

**Comment by renjie-liu** [comment]
great, looks like you got an answer already! :)
