### ISSUE TITLE
Bazel build fail: ModuleNotFoundError: No module named 'google.protobuf'

### ISSUE THREAD

**Issue by karasjoh000** [tensorflow/tensorflow#35877]
**System: MacOS Mojave version 10.14.4**

**Description:** 
compiled from master branch and got error `ModuleNotFoundError: No module named 'google.protobuf'`

**Commands followed:** 
```shell
pip install -U --user pip six numpy wheel setuptools mock 'future>=0.17.1'
pip install -U --user keras_applications --no-deps
pip install -U --user keras_preprocessing --no-deps
git clone https://github.com/tensorflow/tensorflow.git
cd tensorflow # defaults to master branch -> compiled from master branch. 
./configure 
bazel build //tensorflow/tools/pip_package:build_pip_package
```
**Error:** 
```shell 
ERROR: /Users/johnkarasev/PycharmProjects/untitled/tensorflow/tensorflow/BUILD:866:1: Executing genrule //tensorflow:tf_python_api_gen_v2 failed (Exit 1)
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_johnkarasev/ecc035b543493d4fee11271827f64626/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_tf_python_api_gen_v2.ru
nfiles/org_tensorflow/tensorflow/python/tools/api/generator/create_python_api.py", line 27, in <module>
    from tensorflow.python.tools.api.generator import doc_srcs
  File "/private/var/tmp/_bazel_johnkarasev/ecc035b543493d4fee11271827f64626/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_tf_python_api_gen_v2.ru
nfiles/org_tensorflow/tensorflow/python/__init__.py", line 64, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/private/var/tmp/_bazel_johnkarasev/ecc035b543493d4fee11271827f64626/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_tf_python_api_gen_v2.ru
nfiles/org_tensorflow/tensorflow/core/framework/graph_pb2.py", line 7, in <module>
    from google.protobuf import descriptor as _descriptor
ModuleNotFoundError: No module named 'google.protobuf'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
ERROR: /Users/johnkarasev/PycharmProjects/untitled/tensorflow/tensorflow/tools/pip_package/BUILD:41:1 Executing genrule //tensorflow/python/keras/api:keras_python_api_gen failed (Exit
 1)
INFO: Elapsed time: 6.212s, Critical Path: 1.12s
INFO: 12 processes: 12 local.
FAILED: Build did NOT complete successfully
```

**Comment by karasjoh000** [comment]
**graph_pb2.py**
```python
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensorflow/core/framework/graph.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message # <- ERROR HERE
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

```

**Comment by karasjoh000** [comment]
`pip3 install protobuf` duh lol

**Comment by karasjoh000** [comment]
👆 that fixed it

**Comment by berndporr** [comment]
Protobuf is installed but I still get this error message.
```
ERROR: /home/bernd/tensorflow/tensorflow/BUILD:1397:19: Executing genrule //tensorflow:tf_python_api_gen_v2 failed: (Exit 1): bash failed: error executing command /bin/bash -c ... (remaining 1 argument skipped)
2022-10-21 21:31:14.939452: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE3 SSE4.1 SSE4.2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-10-21 21:31:15.169373: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
Traceback (most recent call last):
  File "/home/bernd/.cache/bazel/_bazel_bernd/2716ba2e215c041a26405d6ef9e43b69/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/create_tensorflow.python_api_tf_python_api_gen_v2.runfiles/org_tensorflow/tensorflow/python/tools/api/generator/create_python_api.py", line 22, in <module>
    from tensorflow.python.tools.api.generator import doc_srcs
  File "/home/bernd/.cache/bazel/_bazel_bernd/2716ba2e215c041a26405d6ef9e43b69/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/create_tensorflow.python_api_tf_python_api_gen_v2.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 37, in <module>
    from tensorflow.python.eager import context
  File "/home/bernd/.cache/bazel/_bazel_bernd/2716ba2e215c041a26405d6ef9e43b69/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/create_tensorflow.python_api_tf_python_api_gen_v2.runfiles/org_tensorflow/tensorflow/python/eager/context.py", line 29, in <module>
    from tensorflow.core.framework import function_pb2
  File "/home/bernd/.cache/bazel/_bazel_bernd/2716ba2e215c041a26405d6ef9e43b69/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/create_tensorflow.python_api_tf_python_api_gen_v2.runfiles/org_tensorflow/tensorflow/core/framework/function_pb2.py", line 7, in <module>
    from google.protobuf import descriptor as _descriptor
ModuleNotFoundError: No module named 'google.protobuf'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
```
I'm using the latest stable release:
~/tensorflow$ git branch
* (HEAD detached at v2.10.0)
  master
Ubuntu LTS jammy with cuda enabled. It compiles fine up this point but then stops. If I run:
```
bernd@bp-dst5:~/tensorflow$ python /home/bernd/.cache/bazel/_bazel_bernd/2716ba2e215c041a26405d6ef9e43b69/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/create_tensorflow.python_api_tf_python_api_gen_v2.runfiles/org_tensorflow/tensorflow/core/framework/function_pb2.py
Traceback (most recent call last):
  File "/home/bernd/.cache/bazel/_bazel_bernd/2716ba2e215c041a26405d6ef9e43b69/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/create_tensorflow.python_api_tf_python_api_gen_v2.runfiles/org_tensorflow/tensorflow/core/framework/function_pb2.py", line 16, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
ModuleNotFoundError: No module named 'tensorflow'

```
then the module protobuf is certainly loaded but not tensorflow which has only been freshly compiled. So basically then it loads correctly protobuf but not the tensorflow environment. Looks like a virtual environment is not set properly? Do I need to have miniconda enabled?
