### ISSUE TITLE
Unable to use tensorflow gpu 

### ISSUE THREAD

**Issue by soumilkanwal80** [tensorflow/tensorflow#35880]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution: Windows 10 Home v1903
- TensorFlow installed from (source or binary):Source
- TensorFlow version:2.1.0
- Python version: 3.5.6
- Installed using virtualenv? pip? conda?: pip
- CUDA/cuDNN version: 7.1.0
- GPU model and memory: RTX 2080 Super

**Describe the problem**
import tensorflow as tf not working

**Provide the exact sequence of commands / steps that you executed before running into the problem**
import tensorflow as tf

**Any other info / logs**

Traceback (most recent call last):
  File "C:\Users\soumi\.conda\envs\soumil\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\soumi\.conda\envs\soumil\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\soumi\.conda\envs\soumil\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\soumi\.conda\envs\soumil\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\soumi\.conda\envs\soumil\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The file cannot be accessed by the system.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\soumi\.conda\envs\soumil\lib\site-packages\tensorflow\__init__.py", line 101, in <module>
    from tensorflow_core import *
  File "C:\Users\soumi\.conda\envs\soumil\lib\site-packages\tensorflow_core\__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\soumi\.conda\envs\soumil\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\Users\soumi\.conda\envs\soumil\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "C:\Users\soumi\.conda\envs\soumil\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\soumi\.conda\envs\soumil\lib\site-packages\tensorflow_core\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\soumi\.conda\envs\soumil\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\soumi\.conda\envs\soumil\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\soumi\.conda\envs\soumil\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\soumi\.conda\envs\soumil\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\soumi\.conda\envs\soumil\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\soumi\.conda\envs\soumil\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The file cannot be accessed by the system.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by ReinforcedMan** [comment]
Hey @soumilkanwal80, this seems similar to #35618 which was solved, did you test the proposed solution ?

**Comment by gowthamkpr** [comment]
@soumilkanwal80 As mentioned in the above comment this issue has been solved. You can refer to this comment [here](https://github.com/tensorflow/tensorflow/issues/35618#issuecomment-573740837) for more details.
