### ISSUE TITLE
Problem converting model to tensorflow lite (LSTM model)

### ISSUE THREAD

**Issue by suha-glal** [tensorflow/tensorflow#35885]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
**I have used google colab**

- TensorFlow version (or github SHA if from source):
TensorFlow 2.x selected.

**Provide the text output from tflite_convert**

```
---------------------------------------------------------------------------
ConverterError                            Traceback (most recent call last)
<ipython-input-73-6a5821dcb9ed> in <module>()
      1 converter = tf.lite.TFLiteConverter.from_keras_model(model)
----> 2 tflite_model = converter.convert()
      3 
      4 # Save the model to disk
      5 #open("/content/gdrive/My Drive/detect_car_model.tflite", "wb").write(tflite_model)

2 frames
/tensorflow-2.1.0/python3.6/tensorflow_core/lite/python/convert.py in toco_convert_protos(model_flags_str, toco_flags_str, input_data_str, debug_info_str, enable_mlir_converter)
    201       stdout = _try_convert_to_unicode(stdout)
    202       stderr = _try_convert_to_unicode(stderr)
--> 203       raise ConverterError("See console for info.\n%s\n%s\n" % (stdout, stderr))
    204   finally:
    205     # Must manually cleanup files.

ConverterError: See console for info.
2020-01-15 04:01:36.499502: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:39] Overriding allow_growth setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
2020-01-15 04:01:36.510161: E tensorflow/lite/toco/toco_tooling.cc:498] We are continually in the process of adding support to TensorFlow Lite for more ops. It would be helpful if you could inform us of how this conversion went by opening a github issue at https://github.com/tensorflow/tensorflow/issues/new?template=40-tflite-op-request.md
 and pasting the following:

Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: CONCATENATION, FULLY_CONNECTED, RESHAPE, REVERSE_V2, SOFTMAX, STRIDED_SLICE. Here is a list of operators for which you will need custom implementations: TensorListFromTensor, TensorListReserve, TensorListStack, While.
Traceback (most recent call last):
  File "/tensorflow-2.1.0/python3.6/bin/toco_from_protos", line 8, in <module>
    sys.exit(main())
  File "/tensorflow-2.1.0/python3.6/tensorflow_core/lite/toco/python/toco_from_protos.py", line 93, in main
    app.run(main=execute, argv=[sys.argv[0]] + unparsed)
  File "/tensorflow-2.1.0/python3.6/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/tensorflow-2.1.0/python3.6/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/tensorflow-2.1.0/python3.6/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/tensorflow-2.1.0/python3.6/tensorflow_core/lite/toco/python/toco_from_protos.py", line 56, in execute
    enable_mlir_converter)
Exception: We are continually in the process of adding support to TensorFlow Lite for more ops. It would be helpful if you could inform us of how this conversion went by opening a github issue at https://github.com/tensorflow/tensorflow/issues/new?template=40-tflite-op-request.md
 and pasting the following:

Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: CONCATENATION, FULLY_CONNECTED, RESHAPE, REVERSE_V2, SOFTMAX, STRIDED_SLICE. Here is a list of operators for which you will need custom implementations: TensorListFromTensor, TensorListReserve, TensorListStack, While.


```

** info / logs**

I have tried to convert the following model:

```

model = keras.Sequential()
model.add(
    keras.layers.Bidirectional(
      keras.layers.LSTM(
          units=128,
          input_shape=[x_train.shape[1], x_train.shape[2]]
      )
    )
)
model.add(keras.layers.Dropout(rate=0.5))
model.add(keras.layers.Dense(units=128, activation='relu'))
model.add(keras.layers.Dense(y_train.shape[1], activation='softmax'))

model.compile(
  loss='categorical_crossentropy',
  optimizer='adam',
  metrics=['acc']
)
```

**Comment by gargn** [comment]
Can you try using the following flag `converter.experimental_new_converter = True` when converting the model?

**Comment by jvishnuvardhan** [comment]
@suha-glal Did you follow @gargn's suggestion in converting the model? Please close the issue if it was resolved. If not, please share a standalone code to reproduce the issue. Thanks!

**Comment by suha-glal** [comment]
Thanks for your help.
I will try it soon and tell you the outcomes.

I will close the issue for now.
