### ISSUE TITLE
AlphaDropout & mixed_float16 - Op has type float32 that does not match type float16

### ISSUE THREAD

**Issue by phemmer** [tensorflow/tensorflow#35883]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Fedora 31
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): Source
- TensorFlow version (use command below): v2.1.0-1-ga9af83a149 2.1.0
- Python version: 3.7.5
- Bazel version (if compiling from source): 0.29.1
- GCC/Compiler version (if compiling from source): 8.3.1
- CUDA/cuDNN version: 10.2.89 / 7.6.5.33
- GPU model and memory: Nvidia GeForce GTX 1070 TI 8GB

**Describe the current behavior**
```
Traceback (most recent call last):
  File "/home/phemmer/.local/lib/python3.7/site-packages/tensorflow_core/python/framework/op_def_library.py", line 468, in _apply_op_helper
    preferred_dtype=default_dtype)
  File "/home/phemmer/.local/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 1290, in convert_to_tensor
    (dtype.name, value.dtype.name, value))
ValueError: Tensor conversion requested dtype float16 for Tensor with dtype float32: <tf.Tensor 'Cast:0' shape=(None, 1) dtype=float32>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/test.py", line 6, in <module>
    dropout = tf.keras.layers.AlphaDropout(0.5)(input)
  File "/home/phemmer/.local/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 773, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "/home/phemmer/.local/lib/python3.7/site-packages/tensorflow_core/python/keras/layers/noise.py", line 202, in call
    return K.in_train_phase(dropped_inputs, inputs, training=training)
  File "/home/phemmer/.local/lib/python3.7/site-packages/tensorflow_core/python/keras/backend.py", line 4303, in in_train_phase
    x = switch(training, x, alt)
  File "/home/phemmer/.local/lib/python3.7/site-packages/tensorflow_core/python/keras/backend.py", line 4236, in switch
    x = control_flow_ops.cond(condition, then_expression_fn, else_expression_fn)
  File "/home/phemmer/.local/lib/python3.7/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/phemmer/.local/lib/python3.7/site-packages/tensorflow_core/python/ops/control_flow_ops.py", line 1174, in cond
    return cond_v2.cond_v2(pred, true_fn, false_fn, name)
  File "/home/phemmer/.local/lib/python3.7/site-packages/tensorflow_core/python/ops/cond_v2.py", line 83, in cond_v2
    op_return_value=pred)
  File "/home/phemmer/.local/lib/python3.7/site-packages/tensorflow_core/python/framework/func_graph.py", line 978, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/phemmer/.local/lib/python3.7/site-packages/tensorflow_core/python/keras/layers/noise.py", line 197, in dropped_inputs
    x = inputs * kept_idx + alpha_p * (1 - kept_idx)
  File "/home/phemmer/.local/lib/python3.7/site-packages/tensorflow_core/python/ops/math_ops.py", line 902, in binary_op_wrapper
    return func(x, y, name=name)
  File "/home/phemmer/.local/lib/python3.7/site-packages/tensorflow_core/python/ops/math_ops.py", line 1201, in _mul_dispatch
    return gen_math_ops.mul(x, y, name=name)
  File "/home/phemmer/.local/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_math_ops.py", line 6125, in mul
    "Mul", x=x, y=y, name=name)
  File "/home/phemmer/.local/lib/python3.7/site-packages/tensorflow_core/python/framework/op_def_library.py", line 504, in _apply_op_helper
    inferred_from[input_arg.type_attr]))
TypeError: Input 'y' of 'Mul' Op has type float32 that does not match type float16 of argument 'x'.
```
**Describe the expected behavior**
No exception

**Code to reproduce the issue**
```
import tensorflow as tf
from tensorflow.keras.mixed_precision import experimental as mixed_precision
mixed_precision.set_policy(mixed_precision.Policy('mixed_float16'))

input = tf.keras.Input(shape=(1))
dropout = tf.keras.layers.AlphaDropout(0.5)(input)
```

**Comment by amahendrakar** [comment]
@phemmer,
Could you please try using float32 instead of mixed_float16. It works for me, please find the Gist [here](https://colab.sandbox.google.com/gist/amahendrakar/aa47f7d48407e665500f9c24c16fb1a8/35883.ipynb).
For more information refer to [this](https://github.com/tensorflow/tensorflow/issues/34782#issuecomment-562350888) issue.

**Comment by phemmer** [comment]
Yes, it works, but I'm not quite sure what the intent of that test is. Tensorflow has worked with float32 for ever.
I'm also not seeing any relation to the linked issue. That issue is about compiling the model, which isn't being done in this issue (compiling will happen eventually, but error occurs before we get to that point), and the documentation already covers the need for the final layer in a model to be float32.
Lastly other layers, like Dropout and GaussianDropout, work fine with `mixed_float16`. It's only AlphaDropout which blows up.
...Unless the linked issue is just to refer to the immaturity of support for `mixed_float16` in general, and not specifically about compilation, or loss precision.

Apologies if I'm misunderstanding something though.

**Comment by reedwm** [comment]
You're not misunderstanding anything, as any layer which does not work with `mixed_float16` is a serious bug. Thanks for the report and short example to reproduce! I will address.
