### ISSUE TITLE
tensorflow program crashes with `CUDA_ERROR_ILLEGAL_ADDRESS` with `tf.boolean_mask` used.

### ISSUE THREAD

**Issue by leckie-chn** [tensorflow/tensorflow#35897]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): docker image `nvcr.io/nvidia/tensorflow:19.09-py3`
- ~Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:~
- TensorFlow installed from (source or binary): see docker image
- TensorFlow version (use command below): 1.14.0+nv
- Python version: 3.6.8
- ~Bazel version (if compiling from source):~
- ~GCC/Compiler version (if compiling from source):~
- CUDA/cuDNN version: 10.1
- GPU model and memory: **Tesla V100-PCIE-16GB**

**Describe the current behavior**
with the following code added in `model_fn`, program crashes with `CUDA_ERROR_ILLEGAL_ADDRESS`:
```python
           def create_mean_metrics(t_logits, t_label, v_label):
                t_filtered = tf.boolean_mask(t_logits, tf.equal(t_map_label, v_label))
                return tf.metrics.mean_tensor(tf.reduce_mean(t_filtered), tf.size(t_filtered))

            eval_metrics = {
                'mean_perfect': create_mean_metrics(t_logits, t_map_label, 0),
                'mean_excellent': create_mean_metrics(t_logits, t_map_label, 1),
                'mean_good': create_mean_metrics(t_logits, t_map_label, 2),
                'mean_fair': create_mean_metrics(t_logits, t_map_label, 3),
                'mean_bad': create_mean_metrics(t_logits, t_map_label, 5),
            }

            return tf.estimator.EstimatorSpec(
                mode=mode,
                loss=t_eval_loss,
                eval_metric_ops=eval_metrics,
            )
```
if the `eval_metrics` part removed, the program will run without crashes.

**Describe the expected behavior**
program run without crashing.

**Other info / logs**
```
2020-01-15 11:07:08.705510: I tensorflow/stream_executor/cuda/ptxas_utils.cc:202] 
2020-01-15 11:07:11.712068: E tensorflow/stream_executor/cuda/cuda_driver.cc:1048] Internal: could not synchronize on CUDA stream: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered :: *** Begin stack trace ***
        tensorflow::CurrentStackTrace()
        stream_executor::gpu::GpuDriver::SynchronizeStream(stream_executor::gpu::GpuContext*, CUstream_st*)
        stream_executor::gpu::GpuExecutor::BlockHostUntilDone(stream_executor::Stream*)
        stream_executor::StreamExecutor::BlockHostUntilDone(stream_executor::Stream*)
        stream_executor::Stream::BlockHostUntilDone()





        tensorflow::XlaRunOp::Compute(tensorflow::OpKernelContext*)
        tensorflow::BaseGPUDevice::ComputeHelper(tensorflow::OpKernel*, tensorflow::OpKernelContext*)
        tensorflow::BaseGPUDevice::Compute(tensorflow::OpKernel*, tensorflow::OpKernelContext*)


        Eigen::ThreadPoolTempl<tensorflow::thread::EigenEnvironment>::WorkerLoop(int)
        std::_Function_handler<void (), tensorflow::thread::EigenEnvironment::CreateThread(std::function<void ()>)::{lambda()#1}>::_M_invoke(std::_Any_data const&)


        clone
*** End stack trace ***

2020-01-15 11:07:11.765522: E tensorflow/stream_executor/cuda/cuda_driver.cc:1032] could not synchronize on CUDA context: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered :: *** Begin stack trace ***
        tensorflow::CurrentStackTrace()
        stream_executor::gpu::GpuDriver::SynchronizeContext(stream_executor::gpu::GpuContext*)
        stream_executor::StreamExecutor::SynchronizeAllActivity()
        tensorflow::XlaCompilationCache::~XlaCompilationCache()
        tensorflow::XlaCompilationCache::~XlaCompilationCache()
        tensorflow::ResourceMgr::Clear()
        tensorflow::DirectSession::~DirectSession()
        tensorflow::DirectSession::~DirectSession()
        tensorflow::SessionRef::Close()
        TF_CloseSession


        _PyEval_EvalFrameDefault


        _PyEval_EvalFrameDefault


        _PyEval_EvalFrameDefault


        _PyEval_EvalFrameDefault


        _PyEval_EvalFrameDefault


        _PyEval_EvalFrameDefault



        _PyEval_EvalFrameDefault
        _PyFunction_FastCallDict

        _PyObject_FastCallDict
        PyObject_CallFunctionObjArgs
        _PyEval_EvalFrameDefault



        _PyEval_EvalFrameDefault



        _PyEval_EvalFrameDefault



        _PyEval_EvalFrameDefault



        _PyEval_EvalFrameDefault


        _PyEval_EvalFrameDefault


        _PyEval_EvalFrameDefault
        _PyFunction_FastCallDict



        _PyObject_FastCallKeywords

        _PyEval_EvalFrameDefault



        _PyEval_EvalFrameDefault

        _PyFunction_FastCallDict



        _PyObject_FastCallKeywords

        _PyEval_EvalFrameDefault



        _PyEval_EvalFrameDefault


        _PyEval_EvalFrameDefault


        _PyEval_EvalFrameDefault


        _PyEval_EvalFrameDefault



        _PyEval_EvalFrameDefault


        _PyEval_EvalFrameDefault


        _PyEval_EvalFrameDefault



        _PyEval_EvalFrameDefault


        _PyEval_EvalFrameDefault

        PyEval_EvalCode

        PyRun_FileExFlags
        PyRun_SimpleFileExFlags
        Py_Main
        main
        __libc_start_main
        _start
*** End stack trace ***

2020-01-15 11:07:11.765871: E tensorflow/compiler/jit/xla_compilation_cache.cc:53] Error synchronizing activity while waiting for all programs to complete
2020-01-15 11:07:11.768797: E tensorflow/stream_executor/cuda/cuda_driver.cc:763] failed to unload module 0x7f66709c3ec0; leaking: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2020-01-15 11:07:11.776140: E tensorflow/stream_executor/cuda/cuda_driver.cc:763] failed to unload module 0x7f66748a71f0; leaking: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InternalError: 2 root error(s) found.
  (0) Internal: Failed to complete all kernels launched on stream 0x1f50d730: could not synchronize on CUDA stream: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
         [[{{node cluster_0_1/xla_run}}]]
         [[Identity/_941]]
  (1) Internal: Failed to complete all kernels launched on stream 0x1f50d730: could not synchronize on CUDA stream: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
         [[{{node cluster_0_1/xla_run}}]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hvd_combine_model_train_fidelity.py", line 684, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "hvd_combine_model_train_fidelity.py", line 464, in main
    max_steps=num_train_steps, hooks=training_hooks)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 367, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1158, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1192, in _train_model_default
    saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1480, in _train_with_estimator_spec
    log_step_count_steps=log_step_count_steps) as mon_sess:
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py", line 584, in MonitoredTrainingSession
    stop_grace_period_secs=stop_grace_period_secs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py", line 1007, in __init__
    stop_grace_period_secs=stop_grace_period_secs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py", line 725, in __init__
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py", line 1200, in __init__
    _WrappedSession.__init__(self, self._create_session())
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py", line 1205, in _create_session
    return self._sess_creator.create_session()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py", line 878, in create_session
    hook.after_create_session(self.tf_sess, self.coord)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/hooks/hooks.py", line 180, in after_create_session
    self._evaluate(session)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/hooks/hooks.py", line 203, in _evaluate
    output_dir=self._eval_dir)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1609, in _evaluate_run
    config=self._session_config)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/evaluation.py", line 272, in _evaluate_once
    session.run(eval_ops, feed_dict)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py", line 754, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py", line 1252, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py", line 1353, in run
    raise six.reraise(*original_exc_info)
  File "/usr/local/lib/python3.6/dist-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py", line 1338, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py", line 1411, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py", line 1169, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: 2 root error(s) found.
  (0) Internal: Failed to complete all kernels launched on stream 0x1f50d730: could not synchronize on CUDA stream: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
         [[{{node cluster_0_1/xla_run}}]]
         [[Identity/_941]]
  (1) Internal: Failed to complete all kernels launched on stream 0x1f50d730: could not synchronize on CUDA stream: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
         [[{{node cluster_0_1/xla_run}}]]
0 successful operations.
0 derived errors ignored.
```

**Comment by ymodak** [comment]
Apologies for the delay in response. Is this still an issue? 
TF 1.14 supports cuda 10.0

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?
