### ISSUE TITLE
Could not find matching function to call loaded from the SavedModel

### ISSUE THREAD

**Issue by mrinalsardar** [tensorflow/tensorflow#35932]
My code works in `GPU` based tensorflow environment without any fuss but fails in `CPU` based environments. Some other people also are facing the same issue. `Training` works without any issues but it's the `predict` method that's failing.

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- TensorFlow installed from (source or binary): Source
- Other system related information below:

```
Collecting system information...
/tmp/check_os.py:18: DeprecationWarning: dist() and linux_distribution() functions are deprecated in Python 3.5
  platform.linux_distribution(),
/tmp/check_os.py:19: DeprecationWarning: dist() and linux_distribution() functions are deprecated in Python 3.5
  platform.dist(),
cat: /proc/1/cgroup: No such file or directory
2020-01-16 15:58:53.661018: I tensorflow/core/platform/cpu_feature_guard.cc:145] This TensorFlow binary is optimized with Intel(R) MKL-DNN to use the following CPU instructions in performance critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in non-MKL-DNN operations, rebuild TensorFlow with the appropriate compiler flags.
2020-01-16 15:58:53.661360: I tensorflow/core/common_runtime/process_util.cc:115] Creating new thread pool with default inter op setting: 12. Tune using inter_op_parallelism_threads for best performance.
')
architecture: ('64bit', '')
machine: x86_64


== are we in docker =============================================
No

== compiler =====================================================
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

== check pips ===================================================
numpy                         1.17.4             
protobuf                      3.11.2             
tensorflow                    2.1.0              
tensorflow-estimator          2.1.0              
tensorflow-hub                0.7.0              

== check for virtualenv =========================================
False

== tensorflow import ============================================
tf.version.VERSION = 2.0.0
tf.version.GIT_VERSION = unknown
tf.version.COMPILER_VERSION = 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)
Sanity check: array([1], dtype=int32)

== env ==========================================================
LD_LIBRARY_PATH is unset
DYLD_LIBRARY_PATH is unset

== nvidia-smi ===================================================
tf_env_cololect.sh: line 147: nvidia-smi: command not found

== cuda libs  ===================================================

== tensorflow installed from info ==================
Name: tensorflow
Version: 2.1.0
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: /Users/sardarmrinal/anaconda3/lib/python3.7/site-packages
Required-by: 

== python version  ==============================================
(major, minor, micro, releaselevel, serial)
(3, 7, 6, 'final', 0)

== bazel version  ===============================================
Build label: 1.2.1
Build time: Tue Nov 26 15:27:31 2019 (1574782051)
Build timestamp: 1574782051
Build timestamp as int: 1574782051
```

**Describe the current behavior**
The code is running successfully in `GPU` based environment and failing in `CPU` based environments.

**Describe the expected behavior**
It should run/fail in the same way in both `GPU` and `CPU` based environments.

**Code to reproduce the issue**
Code in the following link has the same behavior:
https://www.kaggle.com/xhlulu/disaster-nlp-keras-bert-using-tfhub

And also people are talking about this issue in the comments.

**Other info / logs**
```
Making predictions
Traceback (most recent call last):
  File "/Users/sardarmrinal/Egnyte/Private/sardar.mrinal/workspace/competitions/kaggle_nlp_disaster/working/NLP_disaster_bert.py", line 218, in <module>
    df_sub = model_bert.predict(df_eval)
  File "/Users/sardarmrinal/Egnyte/Private/sardar.mrinal/workspace/competitions/kaggle_nlp_disaster/working/NLP_disaster_bert.py", line 186, in predict
    prediction = self.model.predict(x=X)
  File "/Users/sardarmrinal/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 909, in predict
    use_multiprocessing=use_multiprocessing)
  File "/Users/sardarmrinal/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 462, in predict
    steps=steps, callbacks=callbacks, **kwargs)
  File "/Users/sardarmrinal/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 444, in _model_iteration
    total_epochs=1)
  File "/Users/sardarmrinal/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 123, in run_one_epoch
    batch_outs = execution_function(iterator)
  File "/Users/sardarmrinal/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 86, in execution_function
    distributed_function(input_fn))
  File "/Users/sardarmrinal/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 457, in __call__
    result = self._call(*args, **kwds)
  File "/Users/sardarmrinal/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 503, in _call
    self._initialize(args, kwds, add_initializers_to=initializer_map)
  File "/Users/sardarmrinal/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 408, in _initialize
    *args, **kwds))
  File "/Users/sardarmrinal/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 1848, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/Users/sardarmrinal/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 2150, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/Users/sardarmrinal/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 2041, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/Users/sardarmrinal/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/framework/func_graph.py", line 915, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/Users/sardarmrinal/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 358, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/Users/sardarmrinal/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 73, in distributed_function
    per_replica_function, args=(model, x, y, sample_weights))
  File "/Users/sardarmrinal/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/distribute/distribute_lib.py", line 760, in experimental_run_v2
    return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
  File "/Users/sardarmrinal/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/distribute/distribute_lib.py", line 1787, in call_for_each_replica
    return self._call_for_each_replica(fn, args, kwargs)
  File "/Users/sardarmrinal/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/distribute/distribute_lib.py", line 2132, in _call_for_each_replica
    return fn(*args, **kwargs)
  File "/Users/sardarmrinal/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/api.py", line 292, in wrapper
    return func(*args, **kwargs)
  File "/Users/sardarmrinal/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 162, in _predict_on_batch
    return predict_on_batch(model, x)
  File "/Users/sardarmrinal/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 370, in predict_on_batch
    return model(inputs)  # pylint: disable=not-callable
  File "/Users/sardarmrinal/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 847, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "/Users/sardarmrinal/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/network.py", line 708, in call
    convert_kwargs_to_constants=base_layer_utils.call_context().saving)
  File "/Users/sardarmrinal/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/network.py", line 860, in _run_internal_graph
    output_tensors = layer(computed_tensors, **kwargs)
  File "/Users/sardarmrinal/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 847, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "/Users/sardarmrinal/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/api.py", line 292, in wrapper
    return func(*args, **kwargs)
  File "/Users/sardarmrinal/anaconda3/lib/python3.7/site-packages/tensorflow_hub/keras_layer.py", line 218, in call
    lambda: f(training=False))
  File "/Users/sardarmrinal/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/framework/smart_cond.py", line 56, in smart_cond
    return false_fn()
  File "/Users/sardarmrinal/anaconda3/lib/python3.7/site-packages/tensorflow_hub/keras_layer.py", line 218, in <lambda>
    lambda: f(training=False))
  File "/Users/sardarmrinal/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/saved_model/load.py", line 436, in _call_attribute
    return instance.__call__(*args, **kwargs)
  File "/Users/sardarmrinal/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 457, in __call__
    result = self._call(*args, **kwds)
  File "/Users/sardarmrinal/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 494, in _call
    results = self._stateful_fn(*args, **kwds)
  File "/Users/sardarmrinal/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 1822, in __call__
    graph_function, args, kwargs = self._maybe_define_function(args, kwargs)
  File "/Users/sardarmrinal/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 2150, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/Users/sardarmrinal/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 2041, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/Users/sardarmrinal/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/framework/func_graph.py", line 915, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/Users/sardarmrinal/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 358, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/Users/sardarmrinal/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/saved_model/function_deserialization.py", line 262, in restored_function_body
    "\n\n".join(signature_descriptions)))
ValueError: Could not find matching function to call loaded from the SavedModel. Got:
  Positional arguments (3 total):
    * [<tf.Tensor 'inputs:0' shape=(None, 3) dtype=int64>, <tf.Tensor 'inputs_1:0' shape=(None, 3) dtype=int64>, <tf.Tensor 'inputs_2:0' shape=(None, 3) dtype=int64>]
    * False
    * None
  Keyword arguments: {}

Expected these arguments to match one of the following 4 option(s):

Option 1:
  Positional arguments (3 total):
    * [TensorSpec(shape=(None, None), dtype=tf.int32, name='input_word_ids'), TensorSpec(shape=(None, None), dtype=tf.int32, name='input_mask'), TensorSpec(shape=(None, None), dtype=tf.int32, name='input_type_ids')]
    * True
    * None
  Keyword arguments: {}

Option 2:
  Positional arguments (3 total):
    * [TensorSpec(shape=(None, None), dtype=tf.int32, name='input_word_ids'), TensorSpec(shape=(None, None), dtype=tf.int32, name='input_mask'), TensorSpec(shape=(None, None), dtype=tf.int32, name='input_type_ids')]
    * False
    * None
  Keyword arguments: {}

Option 3:
  Positional arguments (3 total):
    * [TensorSpec(shape=(None, None), dtype=tf.int32, name='inputs/0'), TensorSpec(shape=(None, None), dtype=tf.int32, name='inputs/1'), TensorSpec(shape=(None, None), dtype=tf.int32, name='inputs/2')]
    * True
    * None
  Keyword arguments: {}

Option 4:
  Positional arguments (3 total):
    * [TensorSpec(shape=(None, None), dtype=tf.int32, name='inputs/0'), TensorSpec(shape=(None, None), dtype=tf.int32, name='inputs/1'), TensorSpec(shape=(None, None), dtype=tf.int32, name='inputs/2')]
    * False
    * None
  Keyword arguments: {}
```

**Comment by oanush** [comment]
@mrinalsardar ,
Can you please provide the code used by you to replicate the above reported error?Thanks!

**Comment by mrinalsardar** [comment]
Here it goes:


```
import re
import string
import logging

import numpy as np
import pandas as pd
from datetime import datetime

from spellchecker import SpellChecker
import tokenization

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

import tensorflow as tf
import tensorflow_hub as hub
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import ModelCheckpoint, TensorBoard


# Logger setup
logging.basicConfig(
    format="%(asctime)s {} %(levelname)s: %(message)s".format(__name__),
    level=logging.DEBUG,
)
logger = logging.getLogger(name=__name__)
logging.getLogger("py4j").setLevel(logging.ERROR)


class ModelBERT(object):
    def __init__(
        self, 
        pre_train_handle, 
        column_text="text", 
        column_target="target", 
        data_prep=False,
        vector_len=200,
        tokenizer=None
    ):
        logger.info("Initialize ModelBERT along with regex pattarens")
        self.pre_train_handle = pre_train_handle
        self.column_text = column_text
        self.column_target = column_target
        self.data_prep = data_prep
        self.vector_len = vector_len
        self.tokenizer = tokenizer
        self.model_weight_path = "model.h5"
        self.func_list = [self.translate_smiley, self.remove_things]

        self.pattern_hashtag = re.compile(pattern=r"#\w+", flags=re.IGNORECASE)
        self.pattern_uppercase_words = re.compile(pattern=r"[A-Z]+")
        self.pattern_lowercase_words = re.compile(pattern=r"[a-z]+")
        self.pattern_url = re.compile(
            pattern=r"\b[.*]?http[s]?[a-zA-Z0-9_:/\.]+\b", 
            flags=re.IGNORECASE
        )
        self.pattern_handle = re.compile(pattern=r"@\w+", flags=re.IGNORECASE)
        self.pattern_smiley_happy = re.compile(pattern=r"[:|;]\)+")
        self.pattern_smiley_sad = re.compile(pattern=r"[:|;]\(+")
        self.pattern_punctuation = re.compile(r"[{}]".format(string.punctuation))


    def translate_smiley(self, df):
        logger.info("Translating smileys")
        df[self.column_text] = df[self.column_text] \
            .apply(lambda t: self.pattern_smiley_happy.sub(repl="happy", string=t)) \
            .apply(lambda t: self.pattern_smiley_sad.sub(repl="sad", string=t))

        return df


    def remove_things(self, df):
        """Remove URL | handles | punctuations"""
        logger.info("Remove URL, handles and punctuations")
        df[self.column_text] = df[self.column_text] \
            .apply(lambda t: self.pattern_url.sub(repl="", string=t)) \
            .apply(lambda t: self.pattern_handle.sub(repl="", string=t)) \
            .apply(lambda t: self.pattern_punctuation.sub(repl="", string=t))
        
        return df


    def correct_spelling(self, df):
        logger.info("Correcting spellings")
        corrector = SpellChecker().correction
        def correct_me(text):
            return " ".join(list(map(corrector, text.split())))
        df[self.column_text] = df[self.column_text].apply(correct_me)
        
        return df


    def setup_pre_train_layer(self):
        logger.info("Setting up pretrain BERT layer")
        self.pre_train_layer = hub.KerasLayer(handle=self.pre_train_handle, trainable=True)
        logger.debug(f"Pre trained layer: {self.pre_train_layer}")


    def setup_tokenizer(self):
        logger.info("Setting up tokenizer")
        self.setup_pre_train_layer()
        
        vocab_file = self.pre_train_layer.resolved_object.vocab_file.asset_path.numpy()
        do_lower_case = self.pre_train_layer.resolved_object.do_lower_case.numpy()

        logger.debug(f"vocab_file: {vocab_file}")
        logger.debug(f"do_lower_case: {do_lower_case}")

        self.tokenizer = tokenization.FullTokenizer(
            vocab_file=vocab_file, 
            do_lower_case=do_lower_case
        )


    def encode_text(self, texts):
        if not self.tokenizer:
            self.setup_tokenizer()

        logger.debug(f"Encoding text with vector length: {self.vector_len}")
        all_tokens = []
        all_masks = []
        all_segments = []

        for text in texts:
            text = self.tokenizer.tokenize(text)

            text = text[:self.vector_len - 2]
            input_sequence = ["[CLS]"] + text + ["[SEP]"]
            pad_len = self.vector_len - len(input_sequence)

            tokens = self.tokenizer.convert_tokens_to_ids(input_sequence)
            tokens += [0] * pad_len
            pad_masks = [1] * len(input_sequence) + [0] * pad_len
            segmen_ids = [0] * self.vector_len

            all_tokens.append(tokens)
            all_masks.append(pad_masks)
            all_segments.append(segmen_ids)

        return np.array(all_tokens), np.array(all_masks), np.array(all_segments)


    def create_model(self):
        logger.info("Creating model")
        input_word_ids = Input(shape=(self.vector_len,), name="input_word_ids", dtype=tf.int32)
        input_masks = Input(shape=(self.vector_len,), name="input_masks", dtype=tf.int32)
        segment_ids = Input(shape=(self.vector_len,), name="segment_ids", dtype=tf.int32)

        _, sequence_output = self.pre_train_layer([input_word_ids, input_masks, segment_ids])
        clf_output = sequence_output[:, 0, :]
        outputs = Dense(1, activation="sigmoid")(clf_output)

        self.model = Model(inputs=[input_word_ids, input_masks, segment_ids], outputs=outputs)
        self.model.compile(
            optimizer=Adam(learning_rate=3e-6), 
            loss="binary_crossentropy", 
            metrics=["accuracy"]
        )
        logger.info(self.model.summary())


    def prepare_data(self, df):
        if self.func_list:
            for func in self.func_list:
                logger.debug(f"Applying function: {str(func)}")
                df = func(df)

        return df


    def train_model(self, X, y, batch_size=10, epochs=1, verbose=1, validation_split=0.2):
        if self.data_prep:
            df = self.prepare_data(df)

        X = self.encode_text(X[self.column_text].values)
        y = np.asarray(y)

        logger.debug(f"Model checkpoint: {self.model_weight_path}")
        self.checkpoint = ModelCheckpoint(
            filepath=self.model_weight_path, 
            monitor="val_loss", 
            save_best_only=True
        )

        # log_dir="logs/fit/" + datetime.now().strftime("%Y%m%d-%H%M%S")
        # tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

        self.create_model()
        logger.info("Training model")
        self.model.fit(
            x=X, 
            y=y, 
            batch_size=batch_size, 
            epochs=epochs, 
            verbose=verbose, 
            callbacks=[self.checkpoint],
            validation_split=validation_split
        )


    def predict(self, X):
        if self.data_prep:
            X = self.prepare_data(X)

        X = self.encode_text(X[self.column_text].values)
        self.model.load_weights(self.model_weight_path)

        logger.info("Making predictions")
        prediction = self.model.predict(x=X)

        return prediction



path_train = "input/nlp-getting-started/train.csv"
path_test = "input/nlp-getting-started/test.csv"

df_train = pd.read_csv(path_train)

X_train, X_test, y_train, y_test = train_test_split(
    df_train.drop("target", axis=1), 
    df_train["target"], 
    test_size=0.1, 
    random_state=999
)

# pre_train_handle = "https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/1"
pre_train_handle = "/Users/sardarmrinal/Downloads/bert_en_uncased_L-12_H-768_A-12"

model_bert = ModelBERT(pre_train_handle=pre_train_handle)
model_bert.vector_len = 2
# model_bert.data_prep = True
model_bert.func_list = [model_bert.translate_smiley, model_bert.remove_things]

# model_bert.train_model(df_train)
model_bert.train_model(
    X=X_train, 
    y=y_train, 
    batch_size=500, 
    epochs=1, 
    verbose=1, 
    validation_split=0.1
)

y_predict = model_bert.predict(X=X_test)
print(f"Test accuracy score: {accuracy_score(y_test, y_predict)}")



# Preparing submission
df_eval = pd.read_csv(path_test)

prediction = model_bert.predict(df_eval)

df_sub = pd.DataFrame(
    data={
        "id": df_eval["id"].values,
        "target": prediction.round().astype(int).reshape(df_eval.shape[0])
    }
)

df_sub.to_csv("./submission_bert.csv", header=True, index=False)
```

NB: The tokenizer came from here - 
https://raw.githubusercontent.com/tensorflow/models/master/official/nlp/bert/tokenization.py

**Comment by gowthamkpr** [comment]
@mrinalsardar Please provide us a minimal sample to reproduce this issue. Thanks!

**Comment by mrinalsardar** [comment]
@gowthamkpr here you go:
[tf_sample_input.zip](https://github.com/tensorflow/tensorflow/files/4101475/tf_sample_input.zip)

**Comment by gowthamkpr** [comment]
I am running into multiple errors while running on colab. Please find the gist [here](https://colab.sandbox.google.com/gist/gowthamkpr/5877ce3a0d443f94ed482ec7ea82c41a/untitled18.ipynb). Please correct them. Thanks!

**Comment by mrinalsardar** [comment]
The  `pyspellchecker` library is not installed in Colab/Kaggle `docker` image.

You just have to do a `python -m pip install pyspellchecker` and that's it.

**Comment by gowthamkpr** [comment]
@mrinalsardar Please go ahead and make changes in the colab and share the gist. Thank you!

**Comment by gowthamkpr** [comment]
@mrinalsardar Please correct the gist and share it so that we can take a look at your issue. Thanks!

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by hepbc** [comment]
Hi @mrinalsardar 
I was facing a similar issue. What worked for me was changing the way I was saving and loading the model as suggested by another user. Instead of model.save(), I saved the weights and then loaded the model as per guidelines in Part II-Approach 1 here: https://www.tensorflow.org/guide/keras/save_and_serialize.
Seems to be working now.

**Comment by gowthamkpr** [comment]
Yes I tested it as mentioned in the above comment and it is working now. Thanks for sharing @hepbc

**Comment by mrinalsardar** [comment]
@gowthamkpr @hepbc 
It did not resolve the issue for me. Can it be specific to `Mac`?

**Comment by gowthamkpr** [comment]
Did you follow the approach 1 as mentioned [here](https://www.tensorflow.org/guide/keras/save_and_serialize#approach_1) @mrinalsardar

**Comment by gowthamkpr** [comment]
Closing this issue as it has been inactive for more than 2 weeks. Please add additional comments for us to open this issue again. Thanks!

**Comment by GoingMyWay** [comment]
Same issue, TF 2.1, using SavedModel format to restore and failed. You can save the model with h5 format 

![image](https://user-images.githubusercontent.com/9346460/81286714-14fe6f80-9094-11ea-9953-55b8078f9742.png)

**Comment by JakobLS** [comment]
I seem to get the same error when incorrectly formatted data is fed into a loaded model. Using TF 2.5.0. I get this both on CPU and GPU.

<img width="1281" alt="Screenshot 2021-06-28 at 11 39 40" src="https://user-images.githubusercontent.com/32125321/123615492-a59e8e80-d805-11eb-8935-3224744a8836.png">

`test_row` look like this:

<img width="1274" alt="Screenshot 2021-06-28 at 11 40 26" src="https://user-images.githubusercontent.com/32125321/123615676-d2eb3c80-d805-11eb-8542-b37a34e0fff7.png">

In this case it can easily be solved by converting `test_row` into a list before feeding it into the model. 

`result = loaded_model(list(test_row))`

**Comment by ahmedalmindelawy93** [comment]
I am facing the same error and I am using my laptop not the colab!
