### ISSUE TITLE
failed to convert attention-ocr frozen graph to tflite

### ISSUE THREAD

**Issue by vladdders** [tensorflow/tensorflow#35953]
**System information**
- OS Platform and Distribution Linux Ubuntu 18.04
- TensorFlow installed from binary
- TensorFlow version 1.15.0

**I am using the following chunk of code to convert attention-ocr frozen graph to tflite**

```
import tensorflow as tf


PATH_TO_MODEL = "./exported-model/frozen_graph.pb"


input_arrays = ['input_image_as_bytes']
output_arrays = ['prediction']

converter = tf.lite.TFLiteConverter.from_frozen_graph(graph_def_file=PATH_TO_MODEL,
                                                      input_arrays=input_arrays,
                                                      output_arrays=output_arrays,
                                                      input_shapes= {"input_image_as_bytes" : (1, 128, 32)})

tflite_model = converter.convert()

open("converted_model.tflite", "wb").write(tflite_model)
```

**The output from the converter invocation**

```
2020-01-16 21:04:14.913210: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:786] Optimization results for grappler item: graph_to_optimize
2020-01-16 21:04:14.913239: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:788]   constant_folding: Graph size after: 2801 nodes (-133), 3997 edges (-163), time = 2018.08203ms.
2020-01-16 21:04:14.913245: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:788]   constant_folding: Graph size after: 2801 nodes (0), 3997 edges (0), time = 159.867ms.
Traceback (most recent call last):
  File "converter.py", line 18, in <module>
    tflite_model = converter.convert()
  File "venv/lib/python3.6/site-packages/tensorflow_core/lite/python/lite.py", line 983, in convert
    **converter_kwargs)
  File "venv/lib/python3.6/site-packages/tensorflow_core/lite/python/convert.py", line 449, in toco_convert_impl
    enable_mlir_converter=enable_mlir_converter)
  File "venv/lib/python3.6/site-packages/tensorflow_core/lite/python/convert.py", line 200, in toco_convert_protos
    raise ConverterError("See console for info.\n%s\n%s\n" % (stdout, stderr))
tensorflow.lite.python.convert.ConverterError: See console for info.
2020-01-16 21:04:16.445609: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: MutableHashTableV2
2020-01-16 21:04:16.445658: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2020-01-16 21:04:16.445688: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-01-16 21:04:16.445702: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-01-16 21:04:16.445710: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 2
2020-01-16 21:04:16.445724: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-01-16 21:04:16.445734: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-01-16 21:04:16.445743: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: LookupTableInsertV2
2020-01-16 21:04:16.445867: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-01-16 21:04:16.445878: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2020-01-16 21:04:16.445885: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-01-16 21:04:16.445948: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-01-16 21:04:16.445959: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-01-16 21:04:16.445968: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-01-16 21:04:16.445976: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2020-01-16 21:04:16.445986: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-01-16 21:04:16.445995: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-01-16 21:04:16.446013: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-01-16 21:04:16.446081: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayV3
2020-01-16 21:04:16.446095: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2020-01-16 21:04:16.446105: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayV3
2020-01-16 21:04:16.446114: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2020-01-16 21:04:16.446122: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-01-16 21:04:16.446135: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-01-16 21:04:16.446143: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2020-01-16 21:04:16.446151: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-01-16 21:04:16.446161: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-01-16 21:04:16.446169: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2020-01-16 21:04:16.446180: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayScatterV3
2020-01-16 21:04:16.446194: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-01-16 21:04:16.446204: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: LoopCond
2020-01-16 21:04:16.446221: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Exit
2020-01-16 21:04:16.446310: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayReadV3
2020-01-16 21:04:16.446323: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArraySizeV3
2020-01-16 21:04:16.446345: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: DecodePng
2020-01-16 21:04:16.446388: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayGatherV3
2020-01-16 21:04:16.446430: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 2
2020-01-16 21:04:16.446440: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 2
2020-01-16 21:04:16.446553: F tensorflow/lite/toco/import_tensorflow.cc:1585] Check failed: data_type == DT_FLOAT 
Fatal Python error: Aborted

Current thread 0x00007fe7d035f740 (most recent call first):
  File "venv/lib/python3.6/site-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 52 in execute
  File "venv/lib/python3.6/site-packages/absl/app.py", line 250 in _run_main
  File "venv/lib/python3.6/site-packages/absl/app.py", line 299 in run
  File "venv/lib/python3.6/site-packages/tensorflow_core/python/platform/app.py", line 40 in run
  File "venv/lib/python3.6/site-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 89 in main
  File "venv/bin/toco_from_protos", line 8 in <module>
Aborted (core dumped)
```

**Here you can find a link to the frozen graph**

```
https://drive.google.com/open?id=1fD8PbgszlBscxyV2qVFqyEWFVlMcQvCd
```

**Failure details**
I am attempting to convert this frozen graph to tflite.I tried all the possibilities, a) using a SavedModel for conversion, b) the tflite_convert command, c) using bazel to run the toco file but all produced the same file. I had found the following [issue](https://github.com/emedvedev/attention-ocr/issues/136) referenced on the aocr github repo page but it doesn't seem to take me anywhere.

Any help is much appreciated!

**Comment by OctaM** [comment]
@jvishnuvardhan any idea how to solve this?

**Comment by jvishnuvardhan** [comment]
@vladdders I can reproduce the issue with `TF1.15` as well as `tf-nightly`. [Here](https://colab.sandbox.google.com/gist/jvishnuvardhan/f98dc30ec4ddbd421127bc5f99f639ec/untitled799.ipynb) is the gist with `tf-nightly` for our reference. 

Do you have access to the code that was used to create the model? I think the `input` to the model was used as `tf.float64` which was not supported in `tf_lite`. Can you cast the input to `tf.float32` and save the model, convert the model to *.pb. Please let us know what you think? Thanks!

**Comment by vladdders** [comment]
@jvishnuvardhan The code is in the aocr package, you can obtain it by `pip install aocr` or by visiting [this](https://github.com/emedvedev/attention-ocr). Below is the part that I think it pre-processes the data:

```
self.height = tf.constant(DataGen.IMAGE_HEIGHT, dtype=tf.int32)
self.height_float = tf.constant(DataGen.IMAGE_HEIGHT, dtype=tf.float64)

self.img_pl = tf.placeholder(tf.string, name='input_image_as_bytes')
self.img_data = tf.cond(
    tf.less(tf.rank(self.img_pl), 1),
    lambda: tf.expand_dims(self.img_pl, 0),
    lambda: self.img_pl
)
self.img_data = tf.map_fn(self._prepare_image, self.img_data, dtype=tf.float32)
num_images = tf.shape(self.img_data)[0]
```

When I try to change the type from float32 to float64 in line 2 I get the following:
`ValueError: Tensor conversion requested dtype float64 for Tensor with dtype float32: <tf.Tensor 'Const_1:0' shape=() dtype=float32>`. Any idea why that might be? Thanks you!

**Comment by jvishnuvardhan** [comment]
@vladdders What command you used to convert dtype? You can use this [tf.cast](https://www.tensorflow.org/api_docs/python/tf/cast) command to convert dtype. May be you need to convert dtype later in the code. May be you can post it in that repo so that you can get faster resolution. If you can make any standalone code, I will try to help. Thanks!

**Comment by vladdders** [comment]
I managed to solve the issue by casting those `float64` data types to `float32`. Thanks for your guidance!

**Comment by kylechang523** [comment]
@vladdders 
Hi I'm facing the same problem while converting the Attention-based OCR model into tflite, and have almost same unsupported op such as TensorArrayV3. How do you solve this? 

Thank you so much for helping!

**Comment by sirius0503** [comment]
> I managed to solve the issue by casting those `float64` data types to `float32`. Thanks for your guidance!

Hi @vladdders : I tried converting my .pb file from float64 dtype to float32, by using the following code:

```
def load_pb(path_to_pb):
    with tf.gfile.GFile(path_to_pb, 'rb') as f:
        graph_def = tf.GraphDef()
        graph_def.ParseFromString(f.read())
    with tf.Graph().as_default() as graph:
        tf.import_graph_def(graph_def, name='')
        return graph

#For loading the .pb file
tf_graph = load_pb('fbank_net/weights/triplet_loss_trained_model.pb')
sess = tf.Session(graph=tf_graph)

# To get the tensors, I used the following line
all_tensors = [tensor for op in tf_graph.as_graphdef() for tensor in op.values()]
# I iterated over all the tensors then cast them to tf.float32
for i, tensor in enumerate(all_tensors):
    all_tensors[i] = tf.cast(tensor, tf.float32)
# And saved the .pb file using
tf.io.write_graph(tf_graph, '.', 'myfloat32m.pb')
```

But when I use tf.lite.TFLiteConverter and then converter.convert() as shown below:
```
converter = tf.lite.TFLiteConverter.from_frozen_graph('./myfloat32m.pb', input
   ...: _arrays=['main_input'], output_arrays=['add_17'])
converter.optimizations = [tf.lite.Optimize.DEFAULT]
tf_lite_model = converter.convert()

# I get valueError dtype float64
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-9-92f300cb4b59> in <module>
----> 1 tf_lite_model = converter.convert()

~/.virtualenvs/pytorch2tensorflow/lib/python3.7/site-packages/tensorflow_core/lite/python/lite.py in convert(self)
    981           input_tensors=self._input_tensors,
    982           output_tensors=self._output_tensors,
--> 983           **converter_kwargs)
    984     else:
    985       result = _toco_convert_graph_def(

~/.virtualenvs/pytorch2tensorflow/lib/python3.7/site-packages/tensorflow_core/lite/python/convert.py in toco_convert_impl(input_data, input_tensors, output_tensors, enable_mlir_converter, *args, **kwargs)
    440   """
    441   model_flags, toco_flags, debug_info = build_toco_convert_protos(
--> 442       input_tensors, output_tensors, *args, **kwargs)
    443   debug_info_str = debug_info.SerializeToString() if debug_info else None
    444   data = toco_convert_protos(

~/.virtualenvs/pytorch2tensorflow/lib/python3.7/site-packages/tensorflow_core/lite/python/convert.py in build_toco_convert_protos(input_tensors, output_tensors, inference_type, inference_input_type, input_format, input_shapes, output_format, quantized_input_stats, default_ranges_stats, drop_control_dependency, reorder_across_fake_quant, allow_custom_ops, change_concat_input_ranges, post_training_quantize, quantize_to_float16, dump_graphviz_dir, dump_graphviz_video, target_ops, allow_nonexistent_arrays, debug_info)
    337     input_array.name = util.get_tensor_name(input_tensor)
    338     input_array.data_type = util.convert_dtype_to_tflite_type(
--> 339         input_tensor.dtype)
    340 
    341     if toco.inference_input_type == _types_pb2.QUANTIZED_UINT8:

~/.virtualenvs/pytorch2tensorflow/lib/python3.7/site-packages/tensorflow_core/lite/python/util.py in convert_dtype_to_tflite_type(tf_dtype)
     62   result = _MAP_TF_TO_TFLITE_TYPES.get(tf_dtype)
     63   if result is None:
---> 64     raise ValueError("Unsupported tf.dtype {0}".format(tf_dtype))
     65   return result
     66 

ValueError: Unsupported tf.dtype <dtype: 'float64'>

```

Can you please help me out @vladdders  @jvishnuvardhan . Thanks a lot!

**Comment by vladdders** [comment]
@kylechang523 yeah I think that is because of the `map` operation. Check in `model.py`. You will have to remove all the operations that are not supported in tf lite, especially control flow operations.

@sirius0503 it seems like for whatever reason you still have some float64 operations. Try to read your new graph and print the layers' datatypes to see where these could occur.

**Comment by barrypitman** [comment]
@vladdders did you ever manage to export a tflite model from attention-ocr?
