### ISSUE TITLE
"ImportError: DLL load failed: The specified module could not be found." while trying to import tensorflow in tensorflow_cpu environment.

### ISSUE THREAD

**Issue by Shivani29sheth** [tensorflow/tensorflow#35988]
Traceback (most recent call last):   File "C:\Users\Shivani\Anaconda3\envs\tensorflow_cpu\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>     from tensorflow.python.pywrap_tensorflow_internal import *   File "C:\Users\Shivani\Anaconda3\envs\tensorflow_cpu\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>     _pywrap_tensorflow_internal = swig_import_helper()   File "C:\Users\Shivani\Anaconda3\envs\tensorflow_cpu\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper     _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)   File "C:\Users\Shivani\Anaconda3\envs\tensorflow_cpu\lib\imp.py", line 243, in load_module     return load_dynamic(name, filename, file)   File "C:\Users\Shivani\Anaconda3\envs\tensorflow_cpu\lib\imp.py", line 343, in load_dynamic     return _load(spec) ImportError: DLL load failed: The specified module could not be found.  During handling of the above exception, another exception occurred:  Traceback (most recent call last):   File "<stdin>", line 1, in <module>   File "C:\Users\Shivani\Anaconda3\envs\tensorflow_cpu\lib\site-packages\tensorflow\__init__.py", line 101, in <module>     from tensorflow_core import *   File "C:\Users\Shivani\Anaconda3\envs\tensorflow_cpu\lib\site-packages\tensorflow_core\__init__.py", line 40, in <module>     from tensorflow.python.tools import module_util as _module_util   File "C:\Users\Shivani\Anaconda3\envs\tensorflow_cpu\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__     module = self._load()   File "C:\Users\Shivani\Anaconda3\envs\tensorflow_cpu\lib\site-packages\tensorflow\__init__.py", line 44, in _load     module = _importlib.import_module(self.__name__)   File "C:\Users\Shivani\Anaconda3\envs\tensorflow_cpu\lib\importlib\__init__.py", line 126, in import_module     return _bootstrap._gcd_import(name[level:], package, level)   File "C:\Users\Shivani\Anaconda3\envs\tensorflow_cpu\lib\site-packages\tensorflow_core\python\__init__.py", line 49, in <module>     from tensorflow.python import pywrap_tensorflow   File "C:\Users\Shivani\Anaconda3\envs\tensorflow_cpu\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 74, in <module>     raise ImportError(msg) ImportError: Traceback (most recent call last):   File "C:\Users\Shivani\Anaconda3\envs\tensorflow_cpu\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>     from tensorflow.python.pywrap_tensorflow_internal import *   File "C:\Users\Shivani\Anaconda3\envs\tensorflow_cpu\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>     _pywrap_tensorflow_internal = swig_import_helper()   File "C:\Users\Shivani\Anaconda3\envs\tensorflow_cpu\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper     _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)   File "C:\Users\Shivani\Anaconda3\envs\tensorflow_cpu\lib\imp.py", line 243, in load_module     return load_dynamic(name, filename, file)   File "C:\Users\Shivani\Anaconda3\envs\tensorflow_cpu\lib\imp.py", line 343, in load_dynamic     return _load(spec) ImportError: DLL load failed: The specified module could not be found.

**Comment by brian1985** [comment]
Having the same issue with what appears to be the same trace. My setup is Pycharm 2019.2 although I have had other versions working previously using Pycharm. Interpreters I have tried are conda and pip through pycharm

**Comment by ymodak** [comment]
@Shivani29sheth @brian1985  What is your cpu make/model? TF 1.6 and above requires support for AVX instructions sets.

**Comment by ashcrok** [comment]
I am experiencing the same issue, running TF 1.2, tho previously (a few days ago) this was working fine. Any updates?

**Comment by brian1985** [comment]
It works now. I am not sure what caused the issue but I believe it was somehow related to Pycharm. I closed the program, restarted Pycharm AND then closed the Ipython terminal at the bottom. After that I assume it forced Pycharm to do something because it then worked.

**Comment by ashcrok** [comment]
I have switched temporarily to TF-CPU. I will re-switch to GPU in the following days and post here an update.

**Comment by gadagashwini** [comment]
@Shivani29sheth  and @brian1985, Please take a look at support [hardware requirements](https://www.tensorflow.org/install/pip#hardware-requirements) of Tensorflow.
Use [Dependency Walker](http://www.dependencywalker.com/), it will show you the DLL dependency tree, you will find which DLL cause the problem. You can then install the needed library or vcredist version, or add some path to system variable.

**Comment by gadagashwini** [comment]
@Shivani29sheth, Is this still an issue

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by ashcrok** [comment]
> I have switched temporarily to TF-CPU. I will re-switch to GPU in the following days and post here an update.

Re-installed CUDA and CuDNn and everything is fine now. Not sure what was the problem before, as I re-installed the same versions + same tf gpu version.
