### ISSUE TITLE
ImportError: DLL Load failed on tensorflow 2.1

### ISSUE THREAD

**Issue by brian1985** [tensorflow/tensorflow#36003]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (Windows10 64 bit):

- TensorFlow installed from (source or binary):pip
- TensorFlow version:2.1
- Python version:3.7
- Installed using virtualenv? pip? conda?: pip

- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: I have cuda runtime 8.0 and 10.1 (don't see cuDNN installed in the list, but at one point I could run tensorflow. Not sure what broke since that was months ago that I last needed it.
- GPU model and memory:

**Describe the problem**
Encountered the problem using Anaconda to create my environment as well. Anaconda has been uninstalled, so these steps were to try and fix the issue by starting at ground 0.

I installed Python 3.7 from the python.org site (after uninstalling Anaconda which also had this issue)
Used command prompt to create virtual env using python -m venv name
pip install packagename one line per package in this order pandas, numpy, wheel, six, scikit-learn, tensorflow
also pip is version 19.3
So now my virutal env should be ready to go and I activated it.
pip list provides:
(envNoShow) C:\Users\USERNAME\AllProjects\noShow>pip list
Package              Version
-------------------- ----------
absl-py              0.9.0
astor                0.8.1
cachetools           4.0.0
certifi              2019.11.28
chardet              3.0.4
gast                 0.2.2
google-auth          1.10.1
google-auth-oauthlib 0.4.1
google-pasta         0.1.8
grpcio               1.26.0
h5py                 2.10.0
idna                 2.8
joblib               0.14.1
Keras-Applications   1.0.8
Keras-Preprocessing  1.1.0
Markdown             3.1.1
numpy                1.18.1
oauthlib             3.1.0
opt-einsum           3.1.0
pandas               0.25.3
pip                  19.3.1
protobuf             3.11.2
pyasn1               0.4.8
pyasn1-modules       0.2.8
python-dateutil      2.8.1
pytz                 2019.3
requests             2.22.0
requests-oauthlib    1.3.0
rsa                  4.0
scikit-learn         0.22.1
scipy                1.4.1
setuptools           41.2.0
six                  1.14.0
tensorboard          2.1.0
tensorflow           2.1.0
tensorflow-estimator 2.1.0
termcolor            1.1.0
urllib3              1.25.7
virtualenv           16.7.9
Werkzeug             0.16.0
wheel                0.33.6
wrapt                1.11.2

ran the command python -c "import tensorflow as tf" and get error in the log file.

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
(envNoShow) C:\Users\USERNAME\AllProjects\noShow>python -c "import tensorflow as tf"
Traceback (most recent call last):
  File "C:\Users\USERNAME\AllProjects\noShow\envNoShow\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\USERNAME\AllProjects\noShow\envNoShow\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\USERNAME\AllProjects\noShow\envNoShow\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python37\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python37\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\USERNAME\AllProjects\noShow\envNoShow\lib\site-packages\tensorflow\__init__.py", line 101, in <module>
    from tensorflow_core import *
  File "C:\Users\USERNAME\AllProjects\noShow\envNoShow\lib\site-packages\tensorflow_core\__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\USERNAME\AllProjects\noShow\envNoShow\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\Users\USERNAME\AllProjects\noShow\envNoShow\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\USERNAME\AllProjects\noShow\envNoShow\lib\site-packages\tensorflow_core\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\USERNAME\AllProjects\noShow\envNoShow\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\USERNAME\AllProjects\noShow\envNoShow\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\USERNAME\AllProjects\noShow\envNoShow\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\USERNAME\AllProjects\noShow\envNoShow\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python37\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python37\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by ymodak** [comment]
Did you install Microsoft Visual C++ Redistributable for Visual Studio 2019?
See https://visualstudio.microsoft.com/vs/older-downloads/

**Comment by ravikyram** [comment]
@brian1985 

Any update on this issue please. Thanks!

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by sunvina** [comment]
protobuf 版本降低3.6.0，就可以导入啦
