### ISSUE TITLE
Error optimizing my TFLite model for GPU usage

### ISSUE THREAD

**Issue by aboerzel** [tensorflow/tensorflow#36016]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 Pro for Workstations (Build: 18363.592)
- TensorFlow installed from (source or binary): pip install tf-nightly
- TensorFlow version (or github SHA if from source): 2.2.0-dev20200115

**Command used to run the converter or code if you’re using the Python API**

```
tf_lite_converter.py :

import tensorflow as tf
from tensorflow_core.lite.python.interpreter import Interpreter
from tensorflow_core.lite.python.lite import TFLiteConverter, Optimize

MODEL_PATH = <path to keras model file>
TFLITE_MODEL_PATH = <path to optimized TFLite model file>

converter = TFLiteConverter.from_keras_model_file(MODEL_PATH)
converter.optimizations.append(Optimize.DEFAULT)
converter.target_spec.supported_types.append(tf.float16)
converter.experimental_new_converter = True
tflite_model = converter.convert()

open(TFLITE_MODEL_PATH, "wb").write(tflite_model)

```

**The output from the converter invocation**

```
(tf-n) D:\development\tensorflow\ANPR>python tf_lite_converter.py
2020-01-18 14:20:47.702258: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
Optimizer:    adagrad
Model path:   output\adagrad\glpr-model.h5
2020-01-18 14:20:53.240667: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2020-01-18 14:20:53.279154: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1558] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: GeForce RTX 2070 computeCapability: 7.5
coreClock: 1.83GHz coreCount: 36 deviceMemorySize: 8.00GiB deviceMemoryBandwidth: 417.29GiB/s
2020-01-18 14:20:53.287304: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
2020-01-18 14:20:53.361116: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_10.dll
2020-01-18 14:20:53.421716: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_10.dll
2020-01-18 14:20:53.447055: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_10.dll
2020-01-18 14:20:53.530899: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_10.dll
2020-01-18 14:20:53.570409: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_10.dll
2020-01-18 14:20:53.702842: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-01-18 14:20:53.708873: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1700] Adding visible gpu devices: 0
2020-01-18 14:20:53.715765: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2020-01-18 14:20:53.723989: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1558] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: GeForce RTX 2070 computeCapability: 7.5
coreClock: 1.83GHz coreCount: 36 deviceMemorySize: 8.00GiB deviceMemoryBandwidth: 417.29GiB/s
2020-01-18 14:20:53.734035: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
2020-01-18 14:20:53.739179: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_10.dll
2020-01-18 14:20:53.744328: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_10.dll
2020-01-18 14:20:53.749625: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_10.dll
2020-01-18 14:20:53.754539: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_10.dll
2020-01-18 14:20:53.759888: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_10.dll
2020-01-18 14:20:53.764633: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-01-18 14:20:53.768758: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1700] Adding visible gpu devices: 0
2020-01-18 14:20:56.460164: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1099] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-01-18 14:20:56.464829: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1105]      0
2020-01-18 14:20:56.467340: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1118] 0:   N
2020-01-18 14:20:56.485286: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1244] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6302 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2070, pci bus id: 0000:01:00.0, compute capability: 7.5)
WARNING:tensorflow:No training configuration found in save file: the model was *not* compiled. Compile it manually.
2020-01-18 14:20:58.024625: I tensorflow/core/grappler/devices.cc:55] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 1
2020-01-18 14:20:58.029712: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2020-01-18 14:20:58.039753: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1558] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: GeForce RTX 2070 computeCapability: 7.5
coreClock: 1.83GHz coreCount: 36 deviceMemorySize: 8.00GiB deviceMemoryBandwidth: 417.29GiB/s
2020-01-18 14:20:58.049235: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
2020-01-18 14:20:58.055409: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_10.dll
2020-01-18 14:20:58.061247: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_10.dll
2020-01-18 14:20:58.066364: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_10.dll
2020-01-18 14:20:58.072194: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_10.dll
2020-01-18 14:20:58.077274: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_10.dll
2020-01-18 14:20:58.081844: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-01-18 14:20:58.086684: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1700] Adding visible gpu devices: 0
2020-01-18 14:20:58.090252: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1099] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-01-18 14:20:58.094291: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1105]      0
2020-01-18 14:20:58.097674: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1118] 0:   N
2020-01-18 14:20:58.101224: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1244] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6302 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2070, pci bus id: 0000:01:00.0, compute capability: 7.5)
2020-01-18 14:20:58.210900: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:815] Optimization results for grappler item: graph_to_optimize
2020-01-18 14:20:58.215597: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:817]   function_optimizer: Graph size after: 402 nodes (0), 510 edges (0), time = 12.053ms.
2020-01-18 14:20:58.223386: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:817]   function_optimizer: Graph size after: 402 nodes (0), 510 edges (0), time = 3.914ms.
2020-01-18 14:20:58.228466: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:815] Optimization results for grappler item: model_1_bidirectional_1_forward_gru_1_while_body_1537
2020-01-18 14:20:58.234325: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:817]   function_optimizer: function_optimizer did nothing. time = 0ms.
2020-01-18 14:20:58.239123: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:817]   function_optimizer: function_optimizer did nothing. time = 0ms.
2020-01-18 14:20:58.243351: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:815] Optimization results for grappler item: model_1_bidirectional_1_forward_gru_1_while_cond_1536
2020-01-18 14:20:58.249016: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:817]   function_optimizer: function_optimizer did nothing. time = 0.001ms.
2020-01-18 14:20:58.253361: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:817]   function_optimizer: function_optimizer did nothing. time = 0ms.
2020-01-18 14:20:58.257939: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:815] Optimization results for grappler item: model_1_bidirectional_1_backward_gru_1_while_body_1693
2020-01-18 14:20:58.263220: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:817]   function_optimizer: function_optimizer did nothing. time = 0ms.
2020-01-18 14:20:58.267683: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:817]   function_optimizer: function_optimizer did nothing. time = 0ms.
2020-01-18 14:20:58.271917: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:815] Optimization results for grappler item: model_1_bidirectional_backward_gru_while_body_1380
2020-01-18 14:20:58.277337: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:817]   function_optimizer: function_optimizer did nothing. time = 0ms.
2020-01-18 14:20:58.281620: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:817]   function_optimizer: function_optimizer did nothing. time = 0.001ms.
2020-01-18 14:20:58.286374: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:815] Optimization results for grappler item: model_1_bidirectional_backward_gru_while_cond_1379
2020-01-18 14:20:58.291542: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:817]   function_optimizer: function_optimizer did nothing. time = 0ms.
2020-01-18 14:20:58.296176: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:817]   function_optimizer: function_optimizer did nothing. time = 0ms.
2020-01-18 14:20:58.300253: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:815] Optimization results for grappler item: model_1_bidirectional_forward_gru_while_body_1224
2020-01-18 14:20:58.305713: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:817]   function_optimizer: function_optimizer did nothing. time = 0ms.
2020-01-18 14:20:58.309768: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:817]   function_optimizer: function_optimizer did nothing. time = 0ms.
2020-01-18 14:20:58.314440: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:815] Optimization results for grappler item: model_1_bidirectional_forward_gru_while_cond_1223
2020-01-18 14:20:58.319815: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:817]   function_optimizer: function_optimizer did nothing. time = 0ms.
2020-01-18 14:20:58.323996: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:817]   function_optimizer: function_optimizer did nothing. time = 0ms.
2020-01-18 14:20:58.328567: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:815] Optimization results for grappler item: model_1_bidirectional_1_backward_gru_1_while_cond_1692
2020-01-18 14:20:58.333697: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:817]   function_optimizer: function_optimizer did nothing. time = 0ms.
2020-01-18 14:20:58.338136: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:817]   function_optimizer: function_optimizer did nothing. time = 0ms.
Traceback (most recent call last):
  File "tf_lite_converter.py", line 30, in <module>
    tflite_model = converter.convert()
  File "C:\Users\Andreas\Anaconda3\lib\site-packages\tensorflow_core\lite\python\lite.py", line 1051, in convert
    **converter_kwargs)
  File "C:\Users\Andreas\Anaconda3\lib\site-packages\tensorflow_core\lite\python\convert.py", line 476, in toco_convert_impl
    enable_mlir_converter=enable_mlir_converter)
  File "C:\Users\Andreas\Anaconda3\lib\site-packages\tensorflow_core\lite\python\convert.py", line 215, in toco_convert_protos
    raise ConverterError("See console for info.\n%s\n%s\n" % (stdout, stderr))
tensorflow.lite.python.convert.ConverterError: See console for info.
2020-01-18 14:20:59.719318: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
2020-01-18 14:21:01.906381: W tensorflow/compiler/mlir/lite/python/graphdef_to_tfl_flatbuffer.cc:108] Ignored output_format.
2020-01-18 14:21:01.906537: W tensorflow/compiler/mlir/lite/python/graphdef_to_tfl_flatbuffer.cc:111] Ignored drop_control_dependency.
2020-01-18 14:21:02.036186: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2020-01-18 14:21:02.040149: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2020-01-18 14:21:02.059114: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1558] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: GeForce RTX 2070 computeCapability: 7.5
coreClock: 1.83GHz coreCount: 36 deviceMemorySize: 8.00GiB deviceMemoryBandwidth: 417.29GiB/s
2020-01-18 14:21:02.059504: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
2020-01-18 14:21:02.062864: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_10.dll
2020-01-18 14:21:02.065500: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_10.dll
2020-01-18 14:21:02.066696: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_10.dll
2020-01-18 14:21:02.069723: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_10.dll
2020-01-18 14:21:02.071795: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_10.dll
2020-01-18 14:21:02.076283: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-01-18 14:21:02.076923: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1700] Adding visible gpu devices: 0
2020-01-18 14:21:02.582665: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1099] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-01-18 14:21:02.582866: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1105]      0
2020-01-18 14:21:02.582978: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1118] 0:   N
2020-01-18 14:21:02.583637: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1244] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6287 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2070, pci bus id: 0000:01:00.0, compute capability: 7.5)
2020-01-18 14:21:05.868343: E tensorflow/lite/tools/optimize/quantize_weights.cc:474] Quantize weights tool only supports tflite models with one subgraph.
Traceback (most recent call last):
  File "c:\users\andreas\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\andreas\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Andreas\Anaconda3\Scripts\toco_from_protos.exe\__main__.py", line 7, in <module>
  File "c:\users\andreas\anaconda3\lib\site-packages\tensorflow_core\lite\toco\python\toco_from_protos.py", line 93, in main
    app.run(main=execute, argv=[sys.argv[0]] + unparsed)
  File "c:\users\andreas\anaconda3\lib\site-packages\tensorflow_core\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "c:\users\andreas\anaconda3\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "c:\users\andreas\anaconda3\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "c:\users\andreas\anaconda3\lib\site-packages\tensorflow_core\lite\toco\python\toco_from_protos.py", line 56, in execute
    enable_mlir_converter)
Exception: Quantize weights transformation failed.
```

**Also, please include a link to the saved model or GraphDef**

[download keras-model](https://drive.google.com/open?id=1GpQkBigddPvprAdplkr8ksT2nYRiAQNQ)

[download saved_model](https://drive.google.com/open?id=1uEpnjYdWuC9yni9iqS4-Lt-A2sA-l4WB)

**Failure details**

**Any other info / logs**

Without using the GPU optimization I can convert the Keras model to a TFLite model. This works correctly, but under Android unfortunately only very slowly!

[GitHub-Project](https://github.com/aboerzel/ALPR-keras)

**Comment by jvishnuvardhan** [comment]
@aboerzel Can you please share the keras model. I could not access the model from your links. Thanks!

**Comment by aboerzel** [comment]
I had made a mistake in the file sharing - sorry!

Here the link to download the [keras-model](https://drive.google.com/open?id=1GpQkBigddPvprAdplkr8ksT2nYRiAQNQ)

**Comment by jvishnuvardhan** [comment]
@aboerzel I am able to reproduce the issue. Thanks. [Here](https://colab.sandbox.google.com/gist/jvishnuvardhan/e0b2d59dbf6a2e1887711b935e460c9d/untitled790.ipynb) is the gist for our reference. Thanks!

**Comment by aboerzel** [comment]
Hello,
I would like to ask briefly what the chances are that the problem will be solved in the near future. A short information would help me a lot in my time planning for my project! It would also be interesting to know if there is a workaround how I can optimize the Keras model for GPU usage?

Many thanks in advance,
Andreas

**Comment by ahmedalesh** [comment]
Hello,

I am stuck on my project with this problem. The error comes up when I apply any optimization to the TFLite converter. Model has some custom ops, so had to set the allow_custom_ops flag True. Please do provide an update if there is any workaround or fix for this issue.

Thanks,
Ahmed

**Comment by jvishnuvardhan** [comment]
@aboerzel I was able to convert your keras model after some modifications to your conversion code. Please take a look at the [gist](https://colab.research.google.com/gist/jvishnuvardhan/af99913bf322928a48c084b0a6d5df57/36016.ipynb). Please check the instructions [here](https://www.tensorflow.org/lite/performance/post_training_float16_quant) for more details.

Pelase verify it and close the issue if this was resolved for you. Thanks!

**Comment by jvishnuvardhan** [comment]
@ahmedalesh Looks like your issue might be different from this issue. Can you please open a new issue with a standalone code. Thanks! You can ping me in that issue. Thanks!

**Comment by ahmedalesh** [comment]
hi @jvishnuvardhan, 

this is the issue https://github.com/tensorflow/tensorflow/issues/39564.

Regards,
Ahmed

**Comment by aboerzel** [comment]
Hi @jvishnuvardhan,
thank you for the good news. I'm currently very busy, but I will try to check the solution as soon as possible and close the issue.

Thanks, 
Andreas

**Comment by aboerzel** [comment]
Hi @jvishnuvardhan,
I tried your solution and was now able to successfully convert my keras-model into a tflite-model with GPU optimization. 

Thank you very much for your help! 👍 

Andreas
