### ISSUE TITLE
Failed build on windows wtih MKL

### ISSUE THREAD

**Issue by Korsar13** [tensorflow/tensorflow#36054]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 Pro
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.1 master branch, git rev-parse HEAD : 6bc6e8df2c515c229735c4bd85b7ff5084dfccef
- Python version: 3.8
- Installed using virtualenv? pip? conda?: virtualenv
- Bazel version (if compiling from source): 1.2.1
- GCC/Compiler version (if compiling from source): msvc 2019
- CUDA/cuDNN version: disabled
- GPU model and memory: 

configure: No XLA/Cuda/RocM, no "disable Eigen strong inline"
optimization flags: -O2 -fp:fast -Ob3

applied patch from https://github.com/tensorflow/tensorflow/issues/25213#issuecomment-501564390

build command:
`bazel --output_base=C:\Lib\.bazel\tf-noavx-mkl build --jobs 6 --config=mkl --config=monolithic --config=opt --config=v2 //tensorflow/tools/pip_package:build_pip_package`

build error:
```
ERROR: F:/lib/tensorflow/tensorflow/BUILD:868:1: Executing genrule //tensorflow:tf_python_api_gen_v2 failed (Exit 1)
Traceback (most recent call last):
  File "\\?\F:\Temp\Bazel.runfiles_ejm1kz55\runfiles\org_tensorflow\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "\\?\F:\Temp\Bazel.runfiles_ejm1kz55\runfiles\org_tensorflow\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "\\?\F:\Temp\Bazel.runfiles_ejm1kz55\runfiles\org_tensorflow\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\K13\tf-noavx\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\K13\tf-noavx\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "\\?\F:\Temp\Bazel.runfiles_ejm1kz55\runfiles\org_tensorflow\tensorflow\python\tools\api\generator\create_python_api.py", line 27, in <module>
    from tensorflow.python.tools.api.generator import doc_srcs
  File "\\?\F:\Temp\Bazel.runfiles_ejm1kz55\runfiles\org_tensorflow\tensorflow\python\__init__.py", line 50, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "\\?\F:\Temp\Bazel.runfiles_ejm1kz55\runfiles\org_tensorflow\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "\\?\F:\Temp\Bazel.runfiles_ejm1kz55\runfiles\org_tensorflow\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "\\?\F:\Temp\Bazel.runfiles_ejm1kz55\runfiles\org_tensorflow\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "\\?\F:\Temp\Bazel.runfiles_ejm1kz55\runfiles\org_tensorflow\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\K13\tf-noavx\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\K13\tf-noavx\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: The specified module could not be found.


Failed to load the native TensorFlow runtime.

```

**Comment by preethivenkatesh** [comment]
@Korsar13 Did you happen to build successfully without mkl flag?

**Comment by Korsar13** [comment]
> @Korsar13 Did you happen to build successfully without mkl flag?

@preethivenkatesh Yes

**Comment by amahendrakar** [comment]
> @preethivenkatesh Yes

@Korsar13,
This this still an issue?

Could you please update TensorFlow to the latest stable version v2.4.1 and check if you are facing the same error. Thanks!
