### ISSUE TITLE
tensorflow nightly still has a problem reported at #35029

### ISSUE THREAD

**Issue by breadbread1984** [tensorflow/tensorflow#36088]
I am using 2.2.0-dev20200119 with CUDA 10.1 on 1080Ti. I still meet the problem #35029  when I run the following code.

```python
#!/usr/bin/python3
import numpy as np;
import tensorflow as tf;
gpus = tf.config.experimental.list_physical_devices('GPU');
tf.config.experimental.set_memory_growth(gpus[0], True);
a=tf.constant(np.random.normal(size=(8,100)), dtype = tf.float32);
b=tf.keras.layers.Dense(units=200)(a);
```

**Comment by jvishnuvardhan** [comment]
@breadbread1984 I don't see any issue with your code. May be there is some cuda initialization issue. Can you please restart your system and run your code. Also, paste the full trace of the error. Thanks!

**Comment by breadbread1984** [comment]
i keep getting the following error

>2020-01-23 07:49:01.813088: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/xieyi/.mujoco/mjpro150/bin:/home/xieyi/opt/nccl2/lib:/home/xieyi/opt/dlib/lib:/usr/local/cuda/lib64:
2020-01-23 07:49:01.813219: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/xieyi/.mujoco/mjpro150/bin:/home/xieyi/opt/nccl2/lib:/home/xieyi/opt/dlib/lib:/usr/local/cuda/lib64:
2020-01-23 07:49:01.813239: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2020-01-23 07:49:02.771859: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-01-23 07:49:02.802388: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-01-23 07:49:02.803359: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties: 
pciBusID: 0000:02:00.0 name: GeForce GTX 1080 Ti computeCapability: 6.1
coreClock: 1.645GHz coreCount: 28 deviceMemorySize: 10.91GiB deviceMemoryBandwidth: 451.17GiB/s
2020-01-23 07:49:02.803587: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-01-23 07:49:02.805465: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-01-23 07:49:02.807003: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-01-23 07:49:02.807307: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-01-23 07:49:02.809246: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-01-23 07:49:02.810396: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-01-23 07:49:02.814600: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-01-23 07:49:02.814733: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-01-23 07:49:02.815611: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-01-23 07:49:02.816410: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1697] Adding visible gpu devices: 0
2020-01-23 07:49:02.842086: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 1995490000 Hz
2020-01-23 07:49:02.843554: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x608ff40 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-01-23 07:49:02.843593: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-01-23 07:49:02.949456: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-01-23 07:49:02.950412: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x60f5700 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-01-23 07:49:02.950479: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce GTX 1080 Ti, Compute Capability 6.1
2020-01-23 07:49:02.950816: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-01-23 07:49:02.952118: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties: 
pciBusID: 0000:02:00.0 name: GeForce GTX 1080 Ti computeCapability: 6.1
coreClock: 1.645GHz coreCount: 28 deviceMemorySize: 10.91GiB deviceMemoryBandwidth: 451.17GiB/s
2020-01-23 07:49:02.952206: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-01-23 07:49:02.952249: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-01-23 07:49:02.952306: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-01-23 07:49:02.952348: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-01-23 07:49:02.952389: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-01-23 07:49:02.952442: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-01-23 07:49:02.952497: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-01-23 07:49:02.952632: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-01-23 07:49:02.954021: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-01-23 07:49:02.961920: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1697] Adding visible gpu devices: 0
2020-01-23 07:49:02.962037: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-01-23 07:49:02.964481: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1096] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-01-23 07:49:02.964534: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102]      0 
2020-01-23 07:49:02.964555: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] 0:   N 
2020-01-23 07:49:02.964815: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-01-23 07:49:02.966321: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-01-23 07:49:02.967706: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1241] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10390 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:02:00.0, compute capability: 6.1)
WARNING: Logging before flag parsing goes to stderr.
W0123 07:49:03.801364 139757452814144 base_layer.py:1790] Layer dense is casting an input tensor from dtype float64 to the layer's dtype of float32, which is new behavior in TensorFlow 2.  The layer has dtype float32 because it's dtype defaults to floatx.

>If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

>To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.

>2020-01-23 07:49:03.802421: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-01-23 07:49:03.802942: E tensorflow/stream_executor/cuda/cuda_blas.cc:238] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
2020-01-23 07:49:03.802996: E tensorflow/stream_executor/cuda/cuda_blas.cc:238] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
2020-01-23 07:49:03.803014: W tensorflow/stream_executor/stream.cc:2041] attempting to perform BLAS operation using StreamExecutor without BLAS support
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/xieyi/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 822, in __call__
    outputs = self.call(cast_inputs, *args, **kwargs)
  File "/home/xieyi/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/layers/core.py", line 1142, in call
    outputs = gen_math_ops.mat_mul(inputs, self.kernel)
  File "/home/xieyi/.local/lib/python3.6/site-packages/tensorflow_core/python/ops/gen_math_ops.py", line 5616, in mat_mul
    _ops.raise_from_not_ok_status(e, name)
  File "/home/xieyi/.local/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 6606, in raise_from_not_ok_status
    >six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InternalError: Blas GEMM launch failed : a.shape=(8, 100), b.shape=(100, 200), m=8, n=200, k=100 [Op:MatMul]

**Comment by breadbread1984** [comment]
I reinstalled cuda 10.1 and solved the problem. sorry for the false alarm
