### ISSUE TITLE
Frozen Graph generation warning lead to error in running the model

### ISSUE THREAD

**Issue by batulrangwala** [tensorflow/tensorflow#36089]
**System information**
- OS Platform and Distribution:Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version: tensorflow-gpu       1.15.0
- Python version: 3.6.10
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): 0.26.1
- GCC/Compiler version (if compiling from source): 7.4
- CUDA/cuDNN version:10.2
- GPU model and memory: GEFORCE GTX 960M - 16GB

**Describe the problem**
Aim is to convert .ckpt and .config files to .tflite for ssd_mobilenet_v2_quantized_coco model.
Following error is seen when converting from .ckpt and .config files to .pb
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/Conv/add_fold

**Provide the exact sequence of commands / steps that you executed before running into the problem**

Following is the sequence of commands

`(py36_tf_gpu) ridlr@ridlr107:~/TensorFlow/models-master/research/object_detection$ python export_tflite_ssd_graph.py --pipeline_config_path /home/ridlr/TensorFlow/base_model/ssd_mobilenet_v2_quantized_300x300_coco_2019_01_03/pipeline.config --trained_checkpoint_prefix /home/ridlr/TensorFlow/base_model/ssd_mobilenet_v2_quantized_300x300_coco_2019_01_03/model.ckpt --output_directory /home/ridlr/TensorFlow/base_model/ssd_mobilenet_v2_quantized_300x300_coco_2019_01_03/tflite_graph_export_tflite/`

The above command generated a tflite_graph.pb file

`tflite_convert --output_file tflite_graph.tflite --graph_def_file tflite_graph.pb --input_arrays normalized_input_image_tensor --output_arrays TFLite_Detection_PostProcess --input_shapes 1,300,300,3 --inference_type QUANTIZED_UINT8 --std_dev_values 0 --mean_values 1 --default_ranges_min 0 --default_ranges_max 6 --allow_custom_ops
`
The above command generated a tflite_graph.tflite file

```
(py36_tf_gpu) ridlr@ridlr107:~/TensorFlow/base_model/ssd_mobilenet_v2_quantized_300x300_coco_2019_01_03/tflite_graph_export_tflite$ edgetpu_compiler tflite_graph.tflite 
Edge TPU Compiler version 2.0.267685300
ERROR: :106 std::abs(input_product_scale - bias_scale) <= 1e-6 * std::min(input_product_scale, bias_scale) was not true.
ERROR: Node number 0 (CONV_2D) failed to prepare.


Model compiled successfully in 11 ms.

Input model: tflite_graph.tflite
Input size: 5.89MiB
Output model: tflite_graph_edgetpu.tflite
Output size: 5.88MiB
On-chip memory available for caching model parameters: 0.00B
On-chip memory used for caching model parameters: 0.00B
Off-chip memory used for streaming uncached model parameters: 0.00B
Number of Edge TPU subgraphs: 0
Total number of operations: 0
Operation log: tflite_graph_edgetpu.log
See the operation log file for individual operation details.
```

The above command generated a tflite_grapf_edgetpu.tflite file inspite of the error. When I run this model on the Coral I get the following error

```
INFO: Initialized TensorFlow Lite runtime.
Traceback (most recent call last):
  File "detect_image.py", line 124, in <module>
    main()
  File "detect_image.py", line 91, in main
    interpreter.allocate_tensors()
  File "/home/ankit/anaconda3/envs/py35/lib/python3.5/site-packages/tflite_runtime/interpreter.py", line 244, in allocate_tensors
    return self._interpreter.AllocateTensors()
  File "/home/ankit/anaconda3/envs/py35/lib/python3.5/site-packages/tflite_runtime/interpreter_wrapper.py", line 114, in AllocateTensors
    return _interpreter_wrapper.InterpreterWrapper_AllocateTensors(self)
RuntimeError: tensorflow/lite/kernels/kernel_util.cc:119 std::abs(input_product_scale - bias_scale) <= 1e-6 * std::min(input_product_scale, bias_scale) was not true.Node number 0 (CONV_2D) failed to prepare.

```

I suspect that there is warning/Info displayed when generating the tflite_graph.pb file which is leading to the above error. The build log for the same is below. The line from the beolow log that concerns me is 
`INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/Conv/add_fold
`
How Can I resolve this warning?
```
(py36_tf_gpu) ridlr@ridlr107:~/TensorFlow/models-master/research/object_detection$ python export_tflite_ssd_graph.py --pipeline_config_path /home/ridlr/TensorFlow/base_model/ssd_mobilenet_v2_quantized_300x300_coco_2019_01_03/pipeline.config --trained_checkpoint_prefix /home/ridlr/TensorFlow/base_model/ssd_mobilenet_v2_quantized_300x300_coco_2019_01_03/model.ckpt --output_directory /home/ridlr/TensorFlow/base_model/ssd_mobilenet_v2_quantized_300x300_coco_2019_01_03/tflite_graph_export_tflite/
WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

WARNING:tensorflow:From /home/ridlr/TensorFlow/models-master/research/slim/nets/inception_resnet_v2.py:374: The name tf.GraphKeys is deprecated. Please use tf.compat.v1.GraphKeys instead.

WARNING:tensorflow:From /home/ridlr/TensorFlow/models-master/research/slim/nets/mobilenet/mobilenet.py:397: The name tf.nn.avg_pool is deprecated. Please use tf.nn.avg_pool2d instead.

WARNING:tensorflow:From export_tflite_ssd_graph.py:143: The name tf.app.run is deprecated. Please use tf.compat.v1.app.run instead.

WARNING:tensorflow:From export_tflite_ssd_graph.py:133: The name tf.gfile.GFile is deprecated. Please use tf.io.gfile.GFile instead.

W0121 12:09:58.011585 140284674922304 module_wrapper.py:139] From export_tflite_ssd_graph.py:133: The name tf.gfile.GFile is deprecated. Please use tf.io.gfile.GFile instead.

WARNING:tensorflow:From /home/ridlr/TensorFlow/models-master/research/object_detection/export_tflite_ssd_graph_lib.py:193: The name tf.gfile.MakeDirs is deprecated. Please use tf.io.gfile.makedirs instead.

W0121 12:09:58.016252 140284674922304 module_wrapper.py:139] From /home/ridlr/TensorFlow/models-master/research/object_detection/export_tflite_ssd_graph_lib.py:193: The name tf.gfile.MakeDirs is deprecated. Please use tf.io.gfile.makedirs instead.

WARNING:tensorflow:From /home/ridlr/TensorFlow/models-master/research/object_detection/export_tflite_ssd_graph_lib.py:237: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0121 12:09:58.016631 140284674922304 module_wrapper.py:139] From /home/ridlr/TensorFlow/models-master/research/object_detection/export_tflite_ssd_graph_lib.py:237: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING:tensorflow:From /home/ridlr/TensorFlow/models-master/research/object_detection/meta_architectures/ssd_meta_arch.py:597: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

W0121 12:09:58.020018 140284674922304 module_wrapper.py:139] From /home/ridlr/TensorFlow/models-master/research/object_detection/meta_architectures/ssd_meta_arch.py:597: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

WARNING:tensorflow:From /home/ridlr/anaconda3/envs/py36_tf_gpu/lib/python3.6/site-packages/tensorflow_core/contrib/layers/python/layers/layers.py:1057: Layer.apply (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.__call__` method instead.
W0121 12:09:58.022555 140284674922304 deprecation.py:323] From /home/ridlr/anaconda3/envs/py36_tf_gpu/lib/python3.6/site-packages/tensorflow_core/contrib/layers/python/layers/layers.py:1057: Layer.apply (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.__call__` method instead.
WARNING:tensorflow:From /home/ridlr/TensorFlow/models-master/research/object_detection/core/anchor_generator.py:171: The name tf.assert_equal is deprecated. Please use tf.compat.v1.assert_equal instead.

W0121 12:09:59.660506 140284674922304 module_wrapper.py:139] From /home/ridlr/TensorFlow/models-master/research/object_detection/core/anchor_generator.py:171: The name tf.assert_equal is deprecated. Please use tf.compat.v1.assert_equal instead.

WARNING:tensorflow:From /home/ridlr/TensorFlow/models-master/research/object_detection/predictors/convolutional_box_predictor.py:150: The name tf.logging.info is deprecated. Please use tf.compat.v1.logging.info instead.

W0121 12:09:59.668454 140284674922304 module_wrapper.py:139] From /home/ridlr/TensorFlow/models-master/research/object_detection/predictors/convolutional_box_predictor.py:150: The name tf.logging.info is deprecated. Please use tf.compat.v1.logging.info instead.

INFO:tensorflow:depth of additional conv before box predictor: 0
I0121 12:09:59.668638 140284674922304 convolutional_box_predictor.py:151] depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
I0121 12:09:59.696758 140284674922304 convolutional_box_predictor.py:151] depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
I0121 12:09:59.722609 140284674922304 convolutional_box_predictor.py:151] depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
I0121 12:09:59.747994 140284674922304 convolutional_box_predictor.py:151] depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
I0121 12:09:59.774057 140284674922304 convolutional_box_predictor.py:151] depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
I0121 12:09:59.801787 140284674922304 convolutional_box_predictor.py:151] depth of additional conv before box predictor: 0
WARNING:tensorflow:From /home/ridlr/TensorFlow/models-master/research/object_detection/export_tflite_ssd_graph_lib.py:52: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

W0121 12:09:59.837386 140284674922304 module_wrapper.py:139] From /home/ridlr/TensorFlow/models-master/research/object_detection/export_tflite_ssd_graph_lib.py:52: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

2020-01-21 12:09:59.838240: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-01-21 12:09:59.847343: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-01-21 12:09:59.847611: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce GTX 960M major: 5 minor: 0 memoryClockRate(GHz): 1.176
pciBusID: 0000:01:00.0
2020-01-21 12:09:59.847750: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcudart.so.10.0'; dlerror: libcudart.so.10.0: cannot open shared object file: No such file or directory
2020-01-21 12:09:59.847852: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcublas.so.10.0'; dlerror: libcublas.so.10.0: cannot open shared object file: No such file or directory
2020-01-21 12:09:59.847962: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcufft.so.10.0'; dlerror: libcufft.so.10.0: cannot open shared object file: No such file or directory
2020-01-21 12:09:59.848044: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcurand.so.10.0'; dlerror: libcurand.so.10.0: cannot open shared object file: No such file or directory
2020-01-21 12:09:59.848109: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcusolver.so.10.0'; dlerror: libcusolver.so.10.0: cannot open shared object file: No such file or directory
2020-01-21 12:09:59.848188: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcusparse.so.10.0'; dlerror: libcusparse.so.10.0: cannot open shared object file: No such file or directory
2020-01-21 12:09:59.851251: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-01-21 12:09:59.851275: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1641] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2020-01-21 12:09:59.851543: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-01-21 12:09:59.875285: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2808000000 Hz
2020-01-21 12:09:59.876004: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x559d0e122aa0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-01-21 12:09:59.876041: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-01-21 12:09:59.903778: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-01-21 12:09:59.904104: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x559d0e124900 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-01-21 12:09:59.904122: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce GTX 960M, Compute Capability 5.0
2020-01-21 12:09:59.904227: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-01-21 12:09:59.904235: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      
WARNING:tensorflow:From /home/ridlr/TensorFlow/models-master/research/object_detection/export_tflite_ssd_graph_lib.py:267: The name tf.train.get_or_create_global_step is deprecated. Please use tf.compat.v1.train.get_or_create_global_step instead.

W0121 12:10:00.032385 140284674922304 module_wrapper.py:139] From /home/ridlr/TensorFlow/models-master/research/object_detection/export_tflite_ssd_graph_lib.py:267: The name tf.train.get_or_create_global_step is deprecated. Please use tf.compat.v1.train.get_or_create_global_step instead.

WARNING:tensorflow:From /home/ridlr/TensorFlow/models-master/research/object_detection/builders/graph_rewriter_builder.py:41: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0121 12:10:00.034862 140284674922304 module_wrapper.py:139] From /home/ridlr/TensorFlow/models-master/research/object_detection/builders/graph_rewriter_builder.py:41: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/Conv/add_fold
I0121 12:10:01.108431 140284674922304 quantize.py:299] Skipping quant after FeatureExtractor/MobilenetV2/Conv/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv/depthwise/add_fold
I0121 12:10:01.108743 140284674922304 quantize.py:299] Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv/depthwise/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_1/expand/add_fold
I0121 12:10:01.108995 140284674922304 quantize.py:299] Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_1/expand/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_1/depthwise/add_fold
I0121 12:10:01.109181 140284674922304 quantize.py:299] Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_1/depthwise/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_2/expand/add_fold
I0121 12:10:01.109415 140284674922304 quantize.py:299] Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_2/expand/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_2/depthwise/add_fold
I0121 12:10:01.109586 140284674922304 quantize.py:299] Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_2/depthwise/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_3/expand/add_fold
I0121 12:10:01.109818 140284674922304 quantize.py:299] Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_3/expand/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_3/depthwise/add_fold
I0121 12:10:01.109977 140284674922304 quantize.py:299] Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_3/depthwise/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_4/expand/add_fold
I0121 12:10:01.110195 140284674922304 quantize.py:299] Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_4/expand/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_4/depthwise/add_fold
I0121 12:10:01.110363 140284674922304 quantize.py:299] Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_4/depthwise/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_5/expand/add_fold
I0121 12:10:01.110591 140284674922304 quantize.py:299] Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_5/expand/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_5/depthwise/add_fold
I0121 12:10:01.110761 140284674922304 quantize.py:299] Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_5/depthwise/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_6/expand/add_fold
I0121 12:10:01.111005 140284674922304 quantize.py:299] Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_6/expand/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_6/depthwise/add_fold
I0121 12:10:01.111187 140284674922304 quantize.py:299] Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_6/depthwise/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_7/expand/add_fold
I0121 12:10:01.111420 140284674922304 quantize.py:299] Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_7/expand/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_7/depthwise/add_fold
I0121 12:10:01.111594 140284674922304 quantize.py:299] Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_7/depthwise/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_8/expand/add_fold
I0121 12:10:01.111815 140284674922304 quantize.py:299] Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_8/expand/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_8/depthwise/add_fold
I0121 12:10:01.112004 140284674922304 quantize.py:299] Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_8/depthwise/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_9/expand/add_fold
I0121 12:10:01.112233 140284674922304 quantize.py:299] Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_9/expand/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_9/depthwise/add_fold
I0121 12:10:01.112395 140284674922304 quantize.py:299] Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_9/depthwise/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_10/expand/add_fold
I0121 12:10:01.112610 140284674922304 quantize.py:299] Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_10/expand/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_10/depthwise/add_fold
I0121 12:10:01.112753 140284674922304 quantize.py:299] Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_10/depthwise/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_11/expand/add_fold
I0121 12:10:01.112978 140284674922304 quantize.py:299] Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_11/expand/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_11/depthwise/add_fold
I0121 12:10:01.113132 140284674922304 quantize.py:299] Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_11/depthwise/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_12/expand/add_fold
I0121 12:10:01.113349 140284674922304 quantize.py:299] Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_12/expand/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_12/depthwise/add_fold
I0121 12:10:01.113510 140284674922304 quantize.py:299] Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_12/depthwise/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_13/expand/add_fold
I0121 12:10:01.113732 140284674922304 quantize.py:299] Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_13/expand/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_13/depthwise/add_fold
I0121 12:10:01.113906 140284674922304 quantize.py:299] Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_13/depthwise/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_14/expand/add_fold
I0121 12:10:01.114142 140284674922304 quantize.py:299] Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_14/expand/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_14/depthwise/add_fold
I0121 12:10:01.114297 140284674922304 quantize.py:299] Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_14/depthwise/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_15/expand/add_fold
I0121 12:10:01.114525 140284674922304 quantize.py:299] Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_15/expand/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_15/depthwise/add_fold
I0121 12:10:01.114687 140284674922304 quantize.py:299] Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_15/depthwise/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_16/expand/add_fold
I0121 12:10:01.114912 140284674922304 quantize.py:299] Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_16/expand/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_16/depthwise/add_fold
I0121 12:10:01.115073 140284674922304 quantize.py:299] Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_16/depthwise/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/Conv_1/add_fold
I0121 12:10:01.115322 140284674922304 quantize.py:299] Skipping quant after FeatureExtractor/MobilenetV2/Conv_1/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/layer_19_1_Conv2d_2_1x1_256/add_fold
I0121 12:10:01.115458 140284674922304 quantize.py:299] Skipping quant after FeatureExtractor/MobilenetV2/layer_19_1_Conv2d_2_1x1_256/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/layer_19_2_Conv2d_2_3x3_s2_512/add_fold
I0121 12:10:01.115600 140284674922304 quantize.py:299] Skipping quant after FeatureExtractor/MobilenetV2/layer_19_2_Conv2d_2_3x3_s2_512/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/layer_19_1_Conv2d_3_1x1_128/add_fold
I0121 12:10:01.115738 140284674922304 quantize.py:299] Skipping quant after FeatureExtractor/MobilenetV2/layer_19_1_Conv2d_3_1x1_128/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/layer_19_2_Conv2d_3_3x3_s2_256/add_fold
I0121 12:10:01.115870 140284674922304 quantize.py:299] Skipping quant after FeatureExtractor/MobilenetV2/layer_19_2_Conv2d_3_3x3_s2_256/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/layer_19_1_Conv2d_4_1x1_128/add_fold
I0121 12:10:01.116004 140284674922304 quantize.py:299] Skipping quant after FeatureExtractor/MobilenetV2/layer_19_1_Conv2d_4_1x1_128/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/layer_19_2_Conv2d_4_3x3_s2_256/add_fold
I0121 12:10:01.116144 140284674922304 quantize.py:299] Skipping quant after FeatureExtractor/MobilenetV2/layer_19_2_Conv2d_4_3x3_s2_256/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/layer_19_1_Conv2d_5_1x1_64/add_fold
I0121 12:10:01.116278 140284674922304 quantize.py:299] Skipping quant after FeatureExtractor/MobilenetV2/layer_19_1_Conv2d_5_1x1_64/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/layer_19_2_Conv2d_5_3x3_s2_128/add_fold
I0121 12:10:01.116429 140284674922304 quantize.py:299] Skipping quant after FeatureExtractor/MobilenetV2/layer_19_2_Conv2d_5_3x3_s2_128/add_fold
2020-01-21 12:10:01.121862: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-01-21 12:10:01.121904: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      
WARNING:tensorflow:From /home/ridlr/TensorFlow/models-master/research/object_detection/exporter.py:111: The name tf.train.Saver is deprecated. Please use tf.compat.v1.train.Saver instead.

W0121 12:10:01.122092 140284674922304 module_wrapper.py:139] From /home/ridlr/TensorFlow/models-master/research/object_detection/exporter.py:111: The name tf.train.Saver is deprecated. Please use tf.compat.v1.train.Saver instead.

INFO:tensorflow:Restoring parameters from /home/ridlr/TensorFlow/base_model/ssd_mobilenet_v2_quantized_300x300_coco_2019_01_03/model.ckpt
I0121 12:10:01.465342 140284674922304 saver.py:1284] Restoring parameters from /home/ridlr/TensorFlow/base_model/ssd_mobilenet_v2_quantized_300x300_coco_2019_01_03/model.ckpt
WARNING:tensorflow:From /home/ridlr/anaconda3/envs/py36_tf_gpu/lib/python3.6/site-packages/tensorflow_core/python/tools/freeze_graph.py:127: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
W0121 12:10:03.793860 140284674922304 deprecation.py:323] From /home/ridlr/anaconda3/envs/py36_tf_gpu/lib/python3.6/site-packages/tensorflow_core/python/tools/freeze_graph.py:127: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
2020-01-21 12:10:04.520189: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-01-21 12:10:04.520234: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      
INFO:tensorflow:Restoring parameters from /tmp/tmpkmw_fvex
I0121 12:10:04.521256 140284674922304 saver.py:1284] Restoring parameters from /tmp/tmpkmw_fvex
WARNING:tensorflow:From /home/ridlr/anaconda3/envs/py36_tf_gpu/lib/python3.6/site-packages/tensorflow_core/python/tools/freeze_graph.py:233: convert_variables_to_constants (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.convert_variables_to_constants`
W0121 12:10:05.583929 140284674922304 deprecation.py:323] From /home/ridlr/anaconda3/envs/py36_tf_gpu/lib/python3.6/site-packages/tensorflow_core/python/tools/freeze_graph.py:233: convert_variables_to_constants (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.convert_variables_to_constants`
WARNING:tensorflow:From /home/ridlr/anaconda3/envs/py36_tf_gpu/lib/python3.6/site-packages/tensorflow_core/python/framework/graph_util_impl.py:277: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.extract_sub_graph`
W0121 12:10:05.584106 140284674922304 deprecation.py:323] From /home/ridlr/anaconda3/envs/py36_tf_gpu/lib/python3.6/site-packages/tensorflow_core/python/framework/graph_util_impl.py:277: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.extract_sub_graph`
INFO:tensorflow:Froze 632 variables.
I0121 12:10:06.121339 140284674922304 graph_util_impl.py:334] Froze 632 variables.
INFO:tensorflow:Converted 632 variables to const ops.
I0121 12:10:06.188232 140284674922304 graph_util_impl.py:394] Converted 632 variables to const ops.
2020-01-21 12:10:06.305956: I tensorflow/tools/graph_transforms/transform_graph.cc:317] Applying strip_unused_nodes

```

**Comment by batulrangwala** [comment]
Using a docker resolved this issue. The Docker is provided by Coral and has all the necessary environment set.
Docker Link : 
https://coral.ai/docs/edgetpu/retrain-detection/#set-up-the-docker-container
