### ISSUE TITLE
Error in pywrap_tensorflow.py after installing tensorflow

### ISSUE THREAD

**Issue by andreap9** [tensorflow/tensorflow#36151]
Hi!
I have this error after installing Tensor Flow. I downgraded my python version to python 3.6.9 and it still doesn't work. 

ImportError: Traceback (most recent call last):
  File "C:\Anaconda3_x64\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Anaconda3_x64\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Anaconda3_x64\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Anaconda3_x64\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Anaconda3_x64\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

I also tried to uninstall it and after installing  tf-nightly and it gives the same error when importing tensorflow.

**Comment by ravikyram** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by andreap9** [comment]
I am using Windows 10 and I have installed TensorFlow ( Version: 2.2.0.dev20200121) using the command 'pip install tf-nightly' in the Anaconda Prompt . The error appears when I import tensor flow:

import tensorflow
Traceback (most recent call last):

  File "C:\Anaconda3_x64\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *

  File "C:\Anaconda3_x64\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()

  File "C:\Anaconda3_x64\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)

  File "C:\Anaconda3_x64\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)

  File "C:\Anaconda3_x64\lib\imp.py", line 343, in load_dynamic
    return _load(spec)

ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "<ipython-input-1-d6579f534729>", line 1, in <module>
    import tensorflow

  File "C:\Anaconda3_x64\lib\site-packages\tensorflow\__init__.py", line 101, in <module>
    from tensorflow_core import *

  File "C:\Anaconda3_x64\lib\site-packages\tensorflow_core\__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util

  File "C:\Anaconda3_x64\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()

  File "C:\Anaconda3_x64\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)

  File "C:\Anaconda3_x64\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)

  File "C:\Anaconda3_x64\lib\site-packages\tensorflow_core\python\__init__.py", line 50, in <module>
    from tensorflow.python import pywrap_tensorflow

  File "C:\Anaconda3_x64\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)

ImportError: Traceback (most recent call last):
  File "C:\Anaconda3_x64\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Anaconda3_x64\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Anaconda3_x64\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Anaconda3_x64\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Anaconda3_x64\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

Error in callback <bound method AutoreloadMagics.post_execute_hook of <autoreload.AutoreloadMagics object at 0x000002C0F6ABC0F0>> (for post_execute):

**Comment by andreap9** [comment]
> Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?
> 
> Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).
> 
> We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!


I am using Windows 10 and I have installed TensorFlow ( Version: 2.2.0.dev20200121) using the command 'pip install tf-nightly' in the Anaconda Prompt . The error appears when I import tensor flow:

import tensorflow
Traceback (most recent call last):

File "C:\Anaconda3_x64\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in
from tensorflow.python.pywrap_tensorflow_internal import *

File "C:\Anaconda3_x64\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in
_pywrap_tensorflow_internal = swig_import_helper()

File "C:\Anaconda3_x64\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
_mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)

File "C:\Anaconda3_x64\lib\imp.py", line 243, in load_module
return load_dynamic(name, filename, file)

File "C:\Anaconda3_x64\lib\imp.py", line 343, in load_dynamic
return _load(spec)

ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

File "", line 1, in
import tensorflow

File "C:\Anaconda3_x64\lib\site-packages\tensorflow_init_.py", line 101, in
from tensorflow_core import *

File "C:\Anaconda3_x64\lib\site-packages\tensorflow_core_init_.py", line 40, in
from tensorflow.python.tools import module_util as _module_util

File "C:\Anaconda3_x64\lib\site-packages\tensorflow_init_.py", line 50, in getattr
module = self._load()

File "C:\Anaconda3_x64\lib\site-packages\tensorflow_init_.py", line 44, in _load
module = _importlib.import_module(self.name)

File "C:\Anaconda3_x64\lib\importlib_init_.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)

File "C:\Anaconda3_x64\lib\site-packages\tensorflow_core\python_init_.py", line 50, in
from tensorflow.python import pywrap_tensorflow

File "C:\Anaconda3_x64\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 74, in
raise ImportError(msg)

ImportError: Traceback (most recent call last):
File "C:\Anaconda3_x64\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in
from tensorflow.python.pywrap_tensorflow_internal import *
File "C:\Anaconda3_x64\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in
_pywrap_tensorflow_internal = swig_import_helper()
File "C:\Anaconda3_x64\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
_mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
File "C:\Anaconda3_x64\lib\imp.py", line 243, in load_module
return load_dynamic(name, filename, file)
File "C:\Anaconda3_x64\lib\imp.py", line 343, in load_dynamic
return _load(spec)
ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions. Include the entire stack trace
above this error message when asking for help.

Error in callback <bound method AutoreloadMagics.post_execute_hook of <autoreload.AutoreloadMagics object at 0x000002C0F6ABC0F0>> (for post_execute):

**Comment by ravikyram** [comment]
What is make/model of your cpu?
I suspect your cpu model does not support AVX instructions sets.See [hardware requirements](https://www.tensorflow.org/install/pip?lang=python3#hardware-requirements).Make sure to download the [latest microsoft visual c++ redistributable from here.](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads).Make sure you update environment path for cuda.Make sure if there is a library that is in a different location/not installed on your system that cannot be loaded.Also, please follow the instructions from [Tensorflow website]( https://www.tensorflow.org/install/gpu#windows_setup).Thanks!

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by Nayanasalur** [comment]
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
~\anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py in <module>
     63   try:
---> 64     from tensorflow.python._pywrap_tensorflow_internal import *
     65   # This try catch logic is because there is no bazel equivalent for py_extension.

ImportError: DLL load failed while importing _pywrap_tensorflow_internal: The specified module could not be found.

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-4-5e619db9b532> in <module>
      2 import seaborn as sns
      3 
----> 4 from tensorflow.keras.preprocessing.text import Tokenizer
      5 from tensorflow.keras.preprocessing.sequence import pad_sequences
      6 from sklearn.preprocessing import StandardScaler

~\anaconda3\lib\site-packages\tensorflow\__init__.py in <module>
     39 import sys as _sys
     40 
---> 41 from tensorflow.python.tools import module_util as _module_util
     42 from tensorflow.python.util.lazy_loader import LazyLoader as _LazyLoader
     43 

~\anaconda3\lib\site-packages\tensorflow\python\__init__.py in <module>
     38 # pylint: disable=wildcard-import,g-bad-import-order,g-import-not-at-top
     39 
---> 40 from tensorflow.python.eager import context
     41 
     42 # pylint: enable=wildcard-import

~\anaconda3\lib\site-packages\tensorflow\python\eager\context.py in <module>
     33 from tensorflow.core.protobuf import config_pb2
     34 from tensorflow.core.protobuf import rewriter_config_pb2
---> 35 from tensorflow.python import pywrap_tfe
     36 from tensorflow.python import tf2
     37 from tensorflow.python.client import pywrap_tf_session

~\anaconda3\lib\site-packages\tensorflow\python\pywrap_tfe.py in <module>
     26 
     27 # pylint: disable=invalid-import-order,g-bad-import-order, wildcard-import, unused-import
---> 28 from tensorflow.python import pywrap_tensorflow
     29 from tensorflow.python._pywrap_tfe import *

~\anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py in <module>
     81 for some common reasons and solutions.  Include the entire stack trace
     82 above this error message when asking for help.""" % traceback.format_exc()
---> 83   raise ImportError(msg)
     84 
     85 # pylint: enable=wildcard-import,g-import-not-at-top,unused-import,line-too-long

ImportError: Traceback (most recent call last):
  File "C:\Users\Gaganu\anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: The specified module could not be found.


Failed to load the native TensorFlow runtime.

**Comment by Nayanasalur** [comment]
getting these errors while importing tensorflow..using python 3-8-3 and Tensorflow==2.2

**Comment by MdKamranUddin** [comment]
same error as above I am getting

**Comment by MdKamranUddin** [comment]
any suggestions or solution will greatly help, thank you in advance
