### ISSUE TITLE
Error while converting to quantized tflite.

### ISSUE THREAD

**Issue by shashank-industrail** [tensorflow/tensorflow#36154]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04.3 LTS
- TensorFlow installed from (source or binary): binary
- TensorFlow version (or github SHA if from source): 2.1.0
- Python version : 3.5.6 anaconda

**Describe the Problem**
I implemented lite-weight custom model based on SSD Paper to detect just one Object, Person.
I want to run that model on Coral EdgeTpu which is connected to Raspberry Pi 4 B.
I follow this doc (https://coral.ai/docs/accelerator/get-started/)  to set up coral on rpi and 
follow this doc (https://coral.ai/docs/edgetpu/compiler/) to install EdgeTpu Compiler on my laptop.
Want to convert tflite to edgetpu_tflite, but tflite need to be quantized so follow that doc
(https://www.tensorflow.org/lite/performance/post_training_integer_quant) to do that.

**Command used to run the converter or code if you’re using the Python API**

```
import tensorflow as tf
import cv2
import numpy as np
import os

converter = tf.lite.TFLiteConverter.from_saved_model('./frozen_models/ssd_tf/')
# fitst set the optimizations flag to optimize for size
converter.optimizations = [tf.lite.Optimize.OPTIMIZE_FOR_SIZE]

train_data_dir = '/home/shashank/Documents/SSD7_tf/Training-data/test/'

images = []
for each_img in os.listdir(train_data_dir):
    read_img = cv2.imread(train_data_dir + each_img).astype(np.float32)
    norm_img = (read_img - np.min(read_img, axis=(0,1,2), keepdims=True))/ (np.max(read_img, axis=(0,1,2), keepdims=True) - np.min(read_img, axis=(0,1,2), keepdims=True))
    images.append(norm_img)

images = np.array(images)
images_ds = tf.data.Dataset.from_tensor_slices((images)).batch(1)

def representative_data_gen():
    for input_value in images_ds.take(100):
        yield [input_value]

converter.representative_dataset = representative_data_gen
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8

tflite_model_quant = converter.convert()
tflite_model_quant_file = 'model_quant_io.tflite'
tflite_model_quant_file.write_bytes(tflite_model_quant)
print('Done!')
```

**The output from the converter invocation**

```
2020-01-23 15:15:34.464864: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory
2020-01-23 15:15:34.464958: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory
2020-01-23 15:15:34.464974: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2020-01-23 15:15:35.849036: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2020-01-23 15:15:35.849060: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: UNKNOWN ERROR (303)
2020-01-23 15:15:35.849095: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (shashank): /proc/driver/nvidia/version does not exist
2020-01-23 15:15:35.849245: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-01-23 15:15:35.873039: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 1800000000 Hz
2020-01-23 15:15:35.873694: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x559e284c8740 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-01-23 15:15:35.873733: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-01-23 15:15:38.481817: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 544320000 exceeds 10% of system memory.
2020-01-23 15:15:38.675897: I tensorflow/core/grappler/devices.cc:55] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2020-01-23 15:15:38.676034: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2020-01-23 15:15:38.717217: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:814] Optimization results for grappler item: graph_to_optimize
2020-01-23 15:15:38.717254: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   function_optimizer: Graph size after: 543 nodes (474), 995 edges (926), time = 12.469ms.
2020-01-23 15:15:38.717260: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   function_optimizer: Graph size after: 543 nodes (0), 995 edges (0), time = 8.12ms.
2020-01-23 15:15:38.717264: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:814] Optimization results for grappler item: __inference_model_1_decoded_predictions_cond_true_2404_6083
2020-01-23 15:15:38.717287: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   function_optimizer: function_optimizer did nothing. time = 0.001ms.
2020-01-23 15:15:38.717290: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   function_optimizer: function_optimizer did nothing. time = 0ms.
2020-01-23 15:15:38.717294: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:814] Optimization results for grappler item: __inference_cond_1_false_2596_2599
2020-01-23 15:15:38.717298: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   function_optimizer: function_optimizer did nothing. time = 0ms.
2020-01-23 15:15:38.717301: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   function_optimizer: function_optimizer did nothing. time = 0ms.
2020-01-23 15:15:38.717305: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:814] Optimization results for grappler item: __inference_cond_false_2547_5852
2020-01-23 15:15:38.717308: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   function_optimizer: function_optimizer did nothing. time = 0.001ms.
2020-01-23 15:15:38.717312: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   function_optimizer: function_optimizer did nothing. time = 0ms.
2020-01-23 15:15:38.717315: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:814] Optimization results for grappler item: __inference_cond_true_2546_1326
2020-01-23 15:15:38.717319: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   function_optimizer: function_optimizer did nothing. time = 0.001ms.
2020-01-23 15:15:38.717323: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   function_optimizer: function_optimizer did nothing. time = 0ms.
2020-01-23 15:15:38.717326: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:814] Optimization results for grappler item: __inference_model_1_decoded_predictions_loop_over_batch_while_cond_2488_1300
2020-01-23 15:15:38.717331: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   function_optimizer: function_optimizer did nothing. time = 0ms.
2020-01-23 15:15:38.717335: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   function_optimizer: function_optimizer did nothing. time = 0ms.
2020-01-23 15:15:38.717339: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:814] Optimization results for grappler item: __inference_cond_2_false_2652_4375
2020-01-23 15:15:38.717343: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   function_optimizer: function_optimizer did nothing. time = 0ms.
2020-01-23 15:15:38.717346: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   function_optimizer: function_optimizer did nothing. time = 0.001ms.
2020-01-23 15:15:38.717350: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:814] Optimization results for grappler item: __inference_model_1_decoded_predictions_loop_over_batch_while_body_2489_5925
2020-01-23 15:15:38.717354: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   function_optimizer: Graph size after: 80 nodes (0), 85 edges (0), time = 1.227ms.
2020-01-23 15:15:38.717357: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   function_optimizer: Graph size after: 80 nodes (0), 85 edges (0), time = 1.357ms.
2020-01-23 15:15:38.717361: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:814] Optimization results for grappler item: __inference_cond_2_true_2651_2758
2020-01-23 15:15:38.717365: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   function_optimizer: function_optimizer did nothing. time = 0.001ms.
2020-01-23 15:15:38.717369: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   function_optimizer: function_optimizer did nothing. time = 0ms.
2020-01-23 15:15:38.717372: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:814] Optimization results for grappler item: __inference_cond_1_true_2595_4150
2020-01-23 15:15:38.717377: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   function_optimizer: function_optimizer did nothing. time = 0ms.
2020-01-23 15:15:38.717381: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   function_optimizer: function_optimizer did nothing. time = 0ms.
2020-01-23 15:15:38.717384: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:814] Optimization results for grappler item: __inference_model_1_decoded_predictions_cond_false_2405_759
2020-01-23 15:15:38.717388: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   function_optimizer: function_optimizer did nothing. time = 0.001ms.
2020-01-23 15:15:38.717392: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   function_optimizer: function_optimizer did nothing. time = 0ms.
2020-01-23 15:15:39.008345: I tensorflow/core/grappler/devices.cc:55] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2020-01-23 15:15:39.008521: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2020-01-23 15:15:39.071925: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:814] Optimization results for grappler item: graph_to_optimize
2020-01-23 15:15:39.071961: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   constant_folding: Graph size after: 435 nodes (-60), 804 edges (-126), time = 21.02ms.
2020-01-23 15:15:39.071983: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   constant_folding: Graph size after: 435 nodes (0), 804 edges (0), time = 11.699ms.
2020-01-23 15:15:39.071987: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:814] Optimization results for grappler item: __inference_model_1_decoded_predictions_cond_true_2404_6083_frozen
2020-01-23 15:15:39.071992: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   constant_folding: Graph size after: 26 nodes (0), 24 edges (0), time = 0.477ms.
2020-01-23 15:15:39.072011: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   constant_folding: Graph size after: 26 nodes (0), 24 edges (0), time = 0.382ms.
2020-01-23 15:15:39.072016: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:814] Optimization results for grappler item: __inference_model_1_decoded_predictions_cond_false_2405_759_frozen
2020-01-23 15:15:39.072020: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   constant_folding: Graph size after: 22 nodes (0), 16 edges (0), time = 0.366ms.
2020-01-23 15:15:39.072023: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   constant_folding: Graph size after: 22 nodes (0), 16 edges (0), time = 0.293ms.
2020-01-23 15:15:39.072026: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:814] Optimization results for grappler item: __inference_cond_2_false_2652_4375_frozen
2020-01-23 15:15:39.072030: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   constant_folding: Graph size after: 22 nodes (0), 24 edges (0), time = 0.473ms.
2020-01-23 15:15:39.072033: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   constant_folding: Graph size after: 22 nodes (0), 24 edges (0), time = 0.391ms.
2020-01-23 15:15:39.072037: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:814] Optimization results for grappler item: __inference_cond_true_2546_1326_frozen
2020-01-23 15:15:39.072040: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   constant_folding: Graph size after: 4 nodes (-1), 1 edges (-1), time = 0.226ms.
2020-01-23 15:15:39.072044: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   constant_folding: Graph size after: 4 nodes (0), 1 edges (0), time = 0.066ms.
2020-01-23 15:15:39.072047: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:814] Optimization results for grappler item: __inference_model_1_decoded_predictions_loop_over_batch_while_cond_2488_1300_frozen
2020-01-23 15:15:39.072051: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   constant_folding: Graph size after: 14 nodes (0), 8 edges (0), time = 0.255ms.
2020-01-23 15:15:39.072055: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   constant_folding: Graph size after: 14 nodes (0), 8 edges (0), time = 0.179ms.
2020-01-23 15:15:39.072059: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:814] Optimization results for grappler item: __inference_cond_2_true_2651_2758_frozen
2020-01-23 15:15:39.072062: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   constant_folding: Graph size after: 11 nodes (0), 11 edges (0), time = 0.284ms.
2020-01-23 15:15:39.072066: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   constant_folding: Graph size after: 11 nodes (0), 11 edges (0), time = 0.188ms.
2020-01-23 15:15:39.072069: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:814] Optimization results for grappler item: __inference_cond_1_true_2595_4150_frozen
2020-01-23 15:15:39.072073: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   constant_folding: Graph size after: 4 nodes (-1), 1 edges (-1), time = 0.21ms.
2020-01-23 15:15:39.072077: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   constant_folding: Graph size after: 4 nodes (0), 1 edges (0), time = 0.078ms.
2020-01-23 15:15:39.072081: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:814] Optimization results for grappler item: __inference_cond_1_false_2596_2599_frozen
2020-01-23 15:15:39.072084: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   constant_folding: Graph size after: 39 nodes (0), 43 edges (0), time = 0.726ms.
2020-01-23 15:15:39.072088: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   constant_folding: Graph size after: 39 nodes (0), 43 edges (0), time = 0.745ms.
2020-01-23 15:15:39.072092: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:814] Optimization results for grappler item: __inference_model_1_decoded_predictions_loop_over_batch_while_body_2489_5925_frozen
2020-01-23 15:15:39.072096: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   constant_folding: Graph size after: 81 nodes (1), 87 edges (2), time = 2.628ms.
2020-01-23 15:15:39.072100: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   constant_folding: Graph size after: 81 nodes (0), 87 edges (0), time = 1.5ms.
2020-01-23 15:15:39.072103: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:814] Optimization results for grappler item: __inference_cond_false_2547_5852_frozen
2020-01-23 15:15:39.072107: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   constant_folding: Graph size after: 37 nodes (1), 41 edges (2), time = 1.256ms.
2020-01-23 15:15:39.072111: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   constant_folding: Graph size after: 37 nodes (0), 41 edges (0), time = 0.653ms.
Traceback (most recent call last):
  File "generate_quant_tflite.py", line 30, in <module>
    tflite_model_quant = converter.convert()
  File "/home/shashank/ENTER/envs/dl_py35/lib/python3.5/site-packages/tensorflow_core/lite/python/lite.py", line 464, in convert
    **converter_kwargs)
  File "/home/shashank/ENTER/envs/dl_py35/lib/python3.5/site-packages/tensorflow_core/lite/python/convert.py", line 457, in toco_convert_impl
    enable_mlir_converter=enable_mlir_converter)
  File "/home/shashank/ENTER/envs/dl_py35/lib/python3.5/site-packages/tensorflow_core/lite/python/convert.py", line 203, in toco_convert_protos
    raise ConverterError("See console for info.\n%s\n%s\n" % (stdout, stderr))
tensorflow.lite.python.convert.ConverterError: See console for info.
2020-01-23 15:15:40.457472: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory
2020-01-23 15:15:40.457547: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory
2020-01-23 15:15:40.457557: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2020-01-23 15:15:41.229352: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-01-23 15:15:41.253051: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 1800000000 Hz
2020-01-23 15:15:41.253841: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55f574b1d500 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-01-23 15:15:41.253867: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-01-23 15:15:41.255187: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2020-01-23 15:15:41.255200: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: UNKNOWN ERROR (303)
2020-01-23 15:15:41.255215: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (shashank): /proc/driver/nvidia/version does not exist
2020-01-23 15:15:41.266040: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: StatelessIf
2020-01-23 15:15:41.266100: F tensorflow/lite/toco/import_tensorflow.cc:114] Check failed: attr.value_case() == AttrValue::kType (1 vs. 6)
Fatal Python error: Aborted

Current thread 0x00007f4c7a502740 (most recent call first):
  File "/home/shashank/ENTER/envs/dl_py35/lib/python3.5/site-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 56 in execute
  File "/home/shashank/ENTER/envs/dl_py35/lib/python3.5/site-packages/absl/app.py", line 250 in _run_main
  File "/home/shashank/ENTER/envs/dl_py35/lib/python3.5/site-packages/absl/app.py", line 299 in run
  File "/home/shashank/ENTER/envs/dl_py35/lib/python3.5/site-packages/tensorflow_core/python/platform/app.py", line 40 in run
  File "/home/shashank/ENTER/envs/dl_py35/lib/python3.5/site-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 93 in main
  File "/home/shashank/ENTER/envs/dl_py35/bin/toco_from_protos", line 8 in <module>
Aborted (core dumped)
```

**Also, please include a link to the saved model or GraphDef**

```
Please copy and paste this link to browser.
(https://github.com/tensorflow/tensorflow/files/4102761/tflite_bug_related_folder.zip)
This folder contains source code to generate the saved model folder.
It also contain saved model folder also.
run python ssd7_inference.py
```

**Comment by shashank-industrail** [comment]
@ymodak Could you Please take a look of this issue.

**Comment by shashank-industrail** [comment]
@haozha111  Could you please take a look of this issue.

**Comment by shashank-industrail** [comment]
@haozha111 Could you please take a look of this issue.

**Comment by haozha111** [comment]
Have you tried using the new MLIR tflite converter?

add this line after you construct the converter object:
converter.experimental_new_converter = True

**Comment by shashank-industrail** [comment]
@haozha111  Thanks for quick reply.

**Now i'm getting this error.**
Traceback (most recent call last):
  File "generate_quant_tflite.py", line 38, in <module>
    tflite_model_quant = converter.convert()
  File "/home/shashank/ENTER/envs/dl_py35/lib/python3.5/site-packages/tensorflow_core/lite/python/lite.py", line 469, in convert
    self.experimental_new_quantizer)
  File "/home/shashank/ENTER/envs/dl_py35/lib/python3.5/site-packages/tensorflow_core/lite/python/lite.py", line 243, in _calibrate_quantize_model
    inference_output_type, allow_float, enable_mlir_quantizer)
  File "/home/shashank/ENTER/envs/dl_py35/lib/python3.5/site-packages/tensorflow_core/lite/python/optimize/calibrator.py", line 81, in calibrate_and_quantize
    enable_mlir_quantizer)
  File "/home/shashank/ENTER/envs/dl_py35/lib/python3.5/site-packages/tensorflow_core/lite/python/optimize/tensorflow_lite_wrap_calibration_wrapper.py", line 115, in QuantizeModel
    return _tensorflow_lite_wrap_calibration_wrapper.CalibrationWrapper_QuantizeModel(self, *args)
RuntimeError: Quantization not yet supported for op: REDUCE_MAX

If i comment this line then this error get disappear.
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]

It mean the converted model is not fully quantize.

**my model is **
    x = Input(shape=(img_height, img_width, img_channels))

    conv1 = Conv2D(48, (5, 5), strides=(1, 1), padding="same", kernel_regularizer=l2(l2_reg), name='conv1')(x)
    conv1 = BatchNormalization(axis=3, momentum=0.99, name='bn1')(conv1) # Tensorflow uses filter format [filter_height, filter_width, in_channels, out_channels], hence axis = 3
    conv1 = ReLU(name='relu1')(conv1)
    pool1 = MaxPooling2D(pool_size=(2, 2), name='pool1')(conv1) #150x150

    conv2 = Conv2D(48, (5, 5), strides=(1, 1), padding="same", kernel_regularizer=l2(l2_reg), name='conv2')(pool1)
    conv2 = BatchNormalization(axis=3, momentum=0.99, name='bn2')(conv2) # Tensorflow uses filter format [filter_height, filter_width, in_channels, out_channels], hence axis = 3
    conv2 = ReLU(name='relu2')(conv2)

    conv3 = Conv2D(48, (3, 3), strides=(1, 1), padding="same", kernel_regularizer=l2(l2_reg), name='conv3')(conv2)
    conv3 = BatchNormalization(axis=3, momentum=0.99, name='bn3')(conv3)
    conv3 = ReLU(name='relu3')(conv3)
    pool2 = MaxPooling2D(pool_size=(2, 2), name='pool2')(conv3) #75x75

    conv4 = Conv2D(64, (3, 3), strides=(1, 1), padding="same", kernel_regularizer=l2(l2_reg), name='conv4')(pool2)
    conv4 = BatchNormalization(axis=3, momentum=0.99, name='bn4')(conv4)
    conv4 = ReLU(name='relu4')(conv4)

    conv5 = Conv2D(64, (3, 3), strides=(1, 1), padding="same", kernel_regularizer=l2(l2_reg), name='conv5')(conv4)
    conv5 = BatchNormalization(axis=3, momentum=0.99, name='bn5')(conv5)
    conv5 = ReLU(name='relu5')(conv5)
    pool3 = MaxPooling2D(pool_size=(2, 2), name='pool3')(conv5) #37x37

    conv6 = Conv2D(64, (3, 3), strides=(1, 1), padding="same", kernel_regularizer=l2(l2_reg), name='conv6')(pool3)
    conv6 = BatchNormalization(axis=3, momentum=0.99, name='bn6')(conv6)
    conv6 = ReLU(name='relu6')(conv6)

    conv7 = Conv2D(64, (3, 3), strides=(1, 1), padding="same", kernel_regularizer=l2(l2_reg), name='conv7')(conv6)
    conv7 = BatchNormalization(axis=3, momentum=0.99, name='bn7')(conv7)
    conv7 = ReLU(name='relu7')(conv7)
    pool4 = MaxPooling2D(pool_size=(2, 2), name='pool4')(conv7) #18x18

    conv8 = Conv2D(64, (3, 3), strides=(1, 1), padding="same", kernel_regularizer=l2(l2_reg), name='conv8')(pool4)
    conv8 = BatchNormalization(axis=3, momentum=0.99, name='bn8')(conv8)
    conv8 = ReLU(name='relu8')(conv8)

    classes6 = Conv2D(n_boxes[0] * n_classes, (3, 3), strides=(1, 1), padding="same", kernel_regularizer=l2(l2_reg), name='classes6')(conv6)
    classes7 = Conv2D(n_boxes[1] * n_classes, (3, 3), strides=(1, 1), padding="same", kernel_regularizer=l2(l2_reg), name='classes7')(conv7)
    classes8 = Conv2D(n_boxes[2] * n_classes, (3, 3), strides=(1, 1), padding="same", kernel_regularizer=l2(l2_reg), name='classes8')(conv8)
    # Output shape of `boxes`: `(batch, height, width, n_boxes * 4)`
    boxes6 = Conv2D(n_boxes[0] * 4, (3, 3), strides=(1, 1), padding="same", kernel_regularizer=l2(l2_reg), name='boxes6')(conv6)
    boxes7 = Conv2D(n_boxes[1] * 4, (3, 3), strides=(1, 1), padding="same", kernel_regularizer=l2(l2_reg), name='boxes7')(conv7)
    boxes8 = Conv2D(n_boxes[2] * 4, (3, 3), strides=(1, 1), padding="same", kernel_regularizer=l2(l2_reg), name='boxes8')(conv8)

    def tile_op(anchor_and_box):
      return tf.tile(anchor_and_box[0], (tf.shape(anchor_and_box[1])[0], 1, 1, 1, 1))

    load_anchor6 = pickle.load(open('anchor6.pkl', 'rb')).astype(np.float32)
    anchors6 = Lambda(lambda x : tile_op(x))([load_anchor6, boxes6])

    load_anchor7 = pickle.load(open('anchor7.pkl', 'rb')).astype(np.float32)
    anchors7 = Lambda(lambda x : tile_op(x))([load_anchor7, boxes7])

    load_anchor8 = pickle.load(open('anchor8.pkl', 'rb')).astype(np.float32)
    anchors8 = Lambda(lambda x : tile_op(x))([load_anchor8, boxes8])
    
    classes6_reshaped = Reshape((-1, n_classes), name='classes6_reshape')(classes6)
    classes7_reshaped = Reshape((-1, n_classes), name='classes7_reshape')(classes7)
    classes8_reshaped = Reshape((-1, n_classes), name='classes8_reshape')(classes8)
    # Reshape the box coordinate predictions, yielding 3D tensors of shape `(batch, height * width * n_boxes, 4)`
    # We want the four box coordinates isolated in the last axis to compute the smooth L1 loss
    
    boxes6_reshaped = Reshape((-1, 4), name='boxes6_reshape')(boxes6)
    boxes7_reshaped = Reshape((-1, 4), name='boxes7_reshape')(boxes7)
    boxes8_reshaped = Reshape((-1, 4), name='boxes8_reshape')(boxes8)
    # Reshape the anchor box tensors, yielding 3D tensors of shape `(batch, height * width * n_boxes, 8)`
    
    anchors6_reshaped = Reshape((-1, 8), name='anchors6_reshape')(anchors6)
    anchors7_reshaped = Reshape((-1, 8), name='anchors7_reshape')(anchors7)
    anchors8_reshaped = Reshape((-1, 8), name='anchors8_reshape')(anchors8)

    # Concatenate the predictions from the different layers and the assosciated anchor box tensors
    # Axis 0 (batch) and axis 2 (n_classes or 4, respectively) are identical for all layer predictions,
    # so we want to concatenate along axis 1
    # Output shape of `classes_concat`: (batch, n_boxes_total, n_classes)
    classes_concat = Concatenate(axis=1, name='classes_concat')([classes6_reshaped,
                                                                 classes7_reshaped,
                                                                 classes8_reshaped])

    # Output shape of `boxes_concat`: (batch, n_boxes_total, 4)
    boxes_concat = Concatenate(axis=1, name='boxes_concat')([boxes6_reshaped,
                                                             boxes7_reshaped,
                                                             boxes8_reshaped])

    # Output shape of `anchors_concat`: (batch, n_boxes_total, 8)
    anchors_concat = Concatenate(axis=1, name='anchors_concat')([anchors6_reshaped,
                                                                 anchors7_reshaped,
                                                                 anchors8_reshaped])

    # The box coordinate predictions will go into the loss function just the way they are,
    # but for the class predictions, we'll apply a softmax activation layer first
    classes_softmax = Activation('softmax', name='classes_softmax')(classes_concat)

    # Concatenate the class and box coordinate predictions and the anchors to one large predictions tensor
    # Output shape of `predictions`: (batch, n_boxes_total, n_classes + 4 + 8)
    predictions = Concatenate(axis=2, name='predictions')([classes_softmax, boxes_concat, anchors_concat])
    
    model = Model(inputs=x, outputs=predictions)

**Comment by haozha111** [comment]
Suharsh, could you take a look at this issue? Thanks!

**Comment by shashank-industrail** [comment]
@suharshs , I'm waiting for your response.Thanks!

**Comment by suharshs** [comment]
Have you tried converting the model without any optimizations specified? Want to make sure first that your model can convert successfully for the float version before trying to add quantization.

Thanks!
-Suharsh

**Comment by shashank-industrail** [comment]
Hi suharshs, Thanks for quick reply.
This is the result.

pb_file = frozen_model.pb'
input_arrays = ['input_1']
output_arrays = ['predictions/concat']

converter = tf.lite.TFLiteConverter.from_frozen_graph(pb_file, input_arrays, output_arrays)

tflite_model = converter.convert()
open("converted_model_decode_slow.tflite", "wb").write(tflite_model)

Yes, it did convert to float version.
When i comment this line then it also successfully convert to tflite, but i don't know which OP is
remains in float32 format.
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]

# fitst set the optimizations flag to optimize for size
converter = tf.lite.TFLiteConverter.from_saved_model('./frozen_models/ssd_tf/')
converter.optimizations = [tf.lite.Optimize.OPTIMIZE_FOR_SIZE]

train_data_dir = '/home/shashank/Documents/IndusTrail/SSD7_tf_batchnorm_version/Training-data/test/'

images = []
for each_img in os.listdir(train_data_dir):
    read_img = cv2.imread(train_data_dir + each_img).astype(np.float32)
    norm_img = (read_img - np.min(read_img, axis=(0,1,2), keepdims=True))/ (np.max(read_img, axis=(0,1,2), keepdims=True) - np.min(read_img, axis=(0,1,2), keepdims=True))
    images.append(norm_img)

images = np.array(images)
images_ds = tf.data.Dataset.from_tensor_slices((images)).batch(1)

def representative_data_gen():
    for input_value in images_ds.take(100):
        yield [input_value]

converter.representative_dataset = representative_data_gen
#converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8

tflite_model_quant = converter.convert()
tflite_model_quant_file = 'model_quant_io.tflite'
tflite_model_quant_file.write_bytes(tflite_model_quant)
print('Done!')

Thanks!
-Shashank

**Comment by suharshs** [comment]
Hmm, yes it seems that REDUCE_MAX doesn't yet have a quantized implementation, can you print all ops in your tensorflow graph and see is Max is in there for some reason?

**Comment by j-o-d-o** [comment]
For anybody wondering. Most probably the reduce_max op was used in the loss function (some sort of cross entropy loss) and not in the model itself.

**Comment by j-o-d-o** [comment]
In case anybody wonders. It's keras' softmax activation which uses the tf.reduce_max.
