### ISSUE TITLE
Tensorflow issue

### ISSUE THREAD

**Issue by sirajbb** [tensorflow/tensorflow#36166]
I am getting this error when I run in PyCharm

Using TensorFlow backend.
Traceback (most recent call last):
  File "C:\Users\Siraj\PycharmProjects\cnn\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tensorflow', [dirname(__file__)])
  File "C:\Users\Siraj\PycharmProjects\cnn\venv\lib\imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tensorflow'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Siraj\PycharmProjects\cnn\venv\lib\site-packages\tensorflow\python\__init__.py", line 54, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Siraj\PycharmProjects\cnn\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "C:\Users\Siraj\PycharmProjects\cnn\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 20, in swig_import_helper
    import _pywrap_tensorflow
ModuleNotFoundError: No module named '_pywrap_tensorflow'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/Siraj/PycharmProjects/cnn/cnn.py", line 1, in <module>
    from keras import layers
  File "C:\Users\Siraj\PycharmProjects\cnn\venv\lib\site-packages\keras\__init__.py", line 3, in <module>
    from . import utils
  File "C:\Users\Siraj\PycharmProjects\cnn\venv\lib\site-packages\keras\utils\__init__.py", line 6, in <module>
    from . import conv_utils
  File "C:\Users\Siraj\PycharmProjects\cnn\venv\lib\site-packages\keras\utils\conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "C:\Users\Siraj\PycharmProjects\cnn\venv\lib\site-packages\keras\backend\__init__.py", line 1, in <module>
    from .load_backend import epsilon
  File "C:\Users\Siraj\PycharmProjects\cnn\venv\lib\site-packages\keras\backend\load_backend.py", line 90, in <module>
    from .tensorflow_backend import *
  File "C:\Users\Siraj\PycharmProjects\cnn\venv\lib\site-packages\keras\backend\tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf
  File "C:\Users\Siraj\PycharmProjects\cnn\venv\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "C:\Users\Siraj\PycharmProjects\cnn\venv\lib\site-packages\tensorflow\python\__init__.py", line 60, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Siraj\PycharmProjects\cnn\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tensorflow', [dirname(__file__)])
  File "C:\Users\Siraj\PycharmProjects\cnn\venv\lib\imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tensorflow'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Siraj\PycharmProjects\cnn\venv\lib\site-packages\tensorflow\python\__init__.py", line 54, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Siraj\PycharmProjects\cnn\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "C:\Users\Siraj\PycharmProjects\cnn\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 20, in swig_import_helper
    import _pywrap_tensorflow
ModuleNotFoundError: No module named '_pywrap_tensorflow'

Error importing tensorflow.  Unless you are using bazel,
you should not try to import tensorflow from its source directory;
please exit the tensorflow source tree, and relaunch your python interpreter
from there.

Process finished with exit code 1

The following Code
-----------------------------------
`from keras import layers
from keras import models
from keras import regularizers

model = models.Sequential()
model.add(layers.Conv2D(32, (3, 3), activation='relu',input_shape=(150, 150, 1)))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(64, (3, 3), activation='relu'))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(128, (3, 3), activation='relu'))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(256, (3, 3), activation='relu'))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Flatten())
model.add(layers.Dropout(0.65))
model.add(layers.Dense(128, activation='relu' ,kernel_regularizer=regularizers.l2(0.002)))
model.add(layers.Dense(6, activation='softmax'))

model.summary()`

**Comment by mihaimaruseac** [comment]
Please fill in the issue template and use ` ``` ` around code and error blocks.

**Comment by gadagashwini** [comment]
@sirajbb, Provide all the information asked in [Template](https://github.com/tensorflow/tensorflow/issues/new/choose). Thanks

**Comment by gadagashwini** [comment]
@sirajbb, Any update

**Comment by gadagashwini** [comment]
@sirajbb, From the error trace it looks like Tensorflow installed incorrectly. Please follow the instructions to install Tensorflow from [here](https://www.tensorflow.org/install). Closing this issue as no activity. Feel free to open if issue still persists.
