### ISSUE TITLE
Error importing tensorflow

### ISSUE THREAD

**Issue by prpeixoto** [tensorflow/tensorflow#36162]
**System information**
- My code has been custom made
- Windows 10
- TensorFlow installed from pip
- TensorFlow version 2.1.0
- Python version 3.7
- h5py version 2.10

**Brief Description**
I am part of a team that develops a standalone software for Windows that encountered an error when trying to import TensorFlow.
The software, called "Hera", is developed in Python and we are now trying to use a previously trained and saved model of a Neural Network to predict a specific feature. For this TensorFlow was used to create, train and save a neural network (outside of the Hera software), and now, when trying to implement TensorFlow on the software we are experiencing some issues.

**Current behavior**
When trying to use the library, importing it as "import tensorflow as tf", we get an error message related to h5py, which the program did not use before TensorFlow was added. 

**Things I have tried**
- _Downgrading to TensorFlow to 2.0:_ Another error occurs, this being: ImportError("cannot import name 'Layer' from 'tensorflow.python.keras.engine.base_layer' (C:\\Development\\Hera3\\hera.dependencies\\OSGEO4W\\apps\\Python37\\lib\\site-packages\\tensorflow_core\\python\\keras\\engine\\base_layer.py)")

- _Downgrading h5py to 2.8:_ The same error continued to occur, without change.

- _Uninstalling h5py:_ The program loads without a problem, however when trying to load the model, that is saved in an h5 file (the format that TensorFlow saves as), it is unable to do so since it does not possess the h5py module.

**Error log line**
AttributeError("type object 'h5py.h5.H5PYConfig' has no attribute '__reduce_cython__'")

**Full log**
```
2020-01-22 17:41:05 INFO: Config.configEnvironment - Configuring environment
2020-01-22 17:41:05 INFO: Config.configEnvironment - Checking GRASS path
2020-01-22 17:41:05 INFO: Config.configEnvironment - Checking QGis path
2020-01-22 17:41:05 INFO: Config.configEnvironment - Setting locale directory
2020-01-22 17:41:05 INFO: Config.configEnvironment - Setting resource directory
2020-01-22 17:41:05 INFO: Config.configEnvironment - Setting plugins directory
2020-01-22 17:41:05 INFO: Config.configEnvironment - Setting documentation directory
2020-01-22 17:41:05 INFO: Config.configEnvironment - Initializing GRASS
2020-01-22 17:41:05 DEBUG: Config.configEnvironment - Setting PSRClasses directory: C:\Development\Hera3\hera.dependencies\psrclassesinterfacepython
2020-01-22 17:41:05 INFO: Config.configEnvironment - Initializing PSRClasses
2020-01-22 17:41:05 INFO: Config.configEnvironment - Initializing QGis
2020-01-22 17:41:05 INFO: Config.configEnvironment -   Creating QgsApplication
2020-01-22 17:41:05 INFO: Config.configEnvironment -   Calling initQgis() - Prefix path: C:\Development\Hera3\hera.dependencies\OSGEO4W\apps\qgis
2020-01-22 17:41:05 DEBUG: Config.configEnvironment - Setting environment variables: 
2020-01-22 17:41:05 DEBUG: Config.configEnvironment - GDAL_DATA: C:\Development\Hera3\hera.dependencies\OSGEO4W\share\gdal
2020-01-22 17:41:05 DEBUG: Config.configEnvironment - PATH: C:\DEVELO~1\Hera3\HERA~1.DEP\OSGEO4W\apps\qgis\bin;C:\DEVELO~1\Hera3\HERA~1.DEP\OSGEO4W\apps\Python37;C:\DEVELO~1\Hera3\HERA~1.DEP\OSGEO4W\apps\Python37\Scripts;C:\DEVELO~1\Hera3\HERA~1.DEP\OSGEO4W\apps\qt5\bin;C:\DEVELO~1\Hera3\HERA~1.DEP\OSGEO4W\apps\Python37\Scripts;C:\DEVELO~1\Hera3\HERA~1.DEP\OSGEO4W\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\system32\WBem

2020-01-22 17:41:05 DEBUG: Config.configEnvironment - PATHEXT: .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW;.py
2020-01-22 17:41:05 DEBUG: Config.configEnvironment - LD_LIBRARY_PATH: C:\Development\Hera3\hera.dependencies\OSGEO4W\apps\grass\grass78\lib
2020-01-22 17:41:05 DEBUG: Config.configEnvironment - GISBASE: C:\Development\Hera3\hera.dependencies\OSGEO4W\apps\grass\grass78
2020-01-22 17:41:05 DEBUG: Config.configEnvironment - GRASS_SH: C:\Development\Hera3\hera.dependencies\OSGEO4W\apps\msys\bin\sh.exe
2020-01-22 17:41:05 DEBUG: Config.configEnvironment - PYTHONPATH: C:\Users\pedro\.p2\pool\plugins\org.python.pydev.core_7.3.0.201908161924\pysrc\pydev_sitecustomize;C:\Development\Hera3\hera.application\src;C:\Development\Hera3\hera.application\src\plugins;C:\Development\Hera3\hera.application\test;C:\Development\Hera3\hera.dependencies\OSGEO4W\apps\qgis\python;C:\Development\Hera3\hera.dependencies\OSGEO4W\apps\grass\grass78\bin;C:\Development\Hera3\hera.dependencies\OSGEO4W\apps\grass\grass78\etc;C:\Development\Hera3\hera.dependencies\OSGEO4W\apps\grass\grass78\etc\python;C:\Development\Hera3\hera.dependencies\OSGEO4W\apps\Python37\DLLs;C:\Development\Hera3\hera.dependencies\OSGEO4W\apps\Python37\lib;C:\Development\Hera3\hera.dependencies\OSGEO4W\apps\Python37;C:\Development\Hera3\hera.dependencies\OSGEO4W\apps\Python37\lib\site-packages;C:\Development\Hera3\hera.dependencies\OSGEO4W\apps\grass\grass78\etc\python;C:\Development\Hera3\hera.dependencies\OSGEO4W\apps\grass\grass78\etc;C:\Development\Hera3\hera.dependencies\OSGEO4W\apps\grass\grass78\bin
2020-01-22 17:41:05 INFO: Config.configEnvironment - Loading language messages
2020-01-22 17:41:05 INFO: Config.configEnvironment - Finished application initialization
2020-01-22 17:41:06 DEBUG: __init__.wrapper - $HOME=C:\Users\pedro
2020-01-22 17:41:06 DEBUG: __init__.wrapper - CONFIGDIR=C:\Users\pedro\.matplotlib
2020-01-22 17:41:06 DEBUG: __init__.wrapper - matplotlib data path: C:\Development\Hera3\hera.dependencies\OSGEO4W\apps\Python37\lib\site-packages\matplotlib\mpl-data
2020-01-22 17:41:06 DEBUG: __init__.rc_params_from_file - loaded rc file C:\Development\Hera3\hera.dependencies\OSGEO4W\apps\Python37\lib\site-packages\matplotlib\mpl-data\matplotlibrc
2020-01-22 17:41:06 DEBUG: __init__.<module> - matplotlib version 3.0.0
2020-01-22 17:41:06 DEBUG: __init__.<module> - interactive is False
2020-01-22 17:41:06 DEBUG: __init__.<module> - platform is win32
2020-01-22 17:41:06 DEBUG: __init__.<module> - loaded modules: ['sys', 'builtins', '_frozen_importlib', '_imp', '_thread', '_warnings', '_weakref', 'zipimport', '_frozen_importlib_external', '_io', 'marshal', 'nt', 'winreg', 'encodings', 'codecs', '_codecs', 'encodings.aliases', 'encodings.utf_8', '_signal', '__main__', 'encodings.latin_1', 'io', 'abc', '_abc', 'encodings.cp1252', 'site', 'os', 'stat', '_stat', 'ntpath', 'genericpath', 'os.path', '_collections_abc', '_sitebuiltins', '_bootlocale', '_locale', 'types', 'importlib', 'importlib._bootstrap', 'importlib._bootstrap_external', 'warnings', 'importlib.util', 'importlib.abc', 'importlib.machinery', 'contextlib', 'collections', 'operator', '_operator', 'keyword', 'heapq', '_heapq', 'itertools', 'reprlib', '_collections', 'functools', '_functools', 'google', 'mpl_toolkits', 'ruamel', 'sitecustomize', 'getpass', 'msvcrt', 'HeraDevEnv', 'hera', 'hera.Config', 'hera.PathManager', 'logging', 'time', 'traceback', 'linecache', 'tokenize', 're', 'enum', 'sre_compile', '_sre', 'sre_parse', 'sre_constants', 'copyreg', 'token', 'weakref', '_weakrefset', 'collections.abc', 'string', '_string', 'threading', 'atexit', 'PSRClassesIO', 'ctypes', '_ctypes', 'struct', '_struct', 'ctypes._endian', 'distutils', 'distutils.sysconfig', 'distutils.errors', 'PSRClasses', 'qgis', 'pathlib', 'fnmatch', 'posixpath', 'errno', 'urllib', 'urllib.parse', 'qgis.PyQt', 'qgis.PyQt.QtCore', 'PyQt5', 'sip', 'PyQt5.QtCore', 'qgis.gui', 'PyQt5.QtGui', 'PyQt5.QtWidgets', 'PyQt5.QtPrintSupport', 'PyQt5.Qsci', 'PyQt5.QtXml', 'PyQt5.QtSql', 'PyQt5.QtNetwork', 'qgis._core', 'qgis._gui', 'qgs25drendererwidget', 'qgsabstractdatasourcewidget', 'qgsabstractfilecontentsourcelineedit', 'qgsabstractprocessingparameterwidgetwrapper', 'qgsactionmenu', 'qgsadvanceddigitizingcanvasitem', 'qgsadvanceddigitizingdockwidget', 'qgsadvanceddigitizingfloater', 'qgsaggregatetoolbutton', 'qgsalignmentcombobox', 'qgsarrowsymbollayerwidget', 'qgsattributedialog', 'qgsattributeeditorcontext', 'qgsattributeform', 'qgsattributeformeditorwidget', 'qgsattributeforminterface', 'qgsattributeformrelationeditorwidget', 'qgsattributeformwidget', 'qgsattributetableaction', 'qgsattributetabledelegate', 'qgsattributetablefiltermodel', 'qgsattributetablemaplayeraction', 'qgsattributetablemodel', 'qgsattributetableview', 'qgsattributetypeloaddialog', 'qgsauthauthoritieseditor', 'qgsauthcerteditors', 'qgsauthcertinfo', 'qgsauthcertinfodialog', 'qgsauthcertmanager', 'qgsauthcerttrustpolicycombobox', 'qgsauthconfigeditor', 'qgsauthconfigselect', 'qgsauthconfiguriedit', 'qgsautheditorwidgets', 'qgsauthidentitieseditor', 'qgsauthimportcertdialog', 'qgsauthimportidentitydialog', 'qgsauthmethodedit', 'qgsauthmethodplugins', 'qgsauthserverseditor', 'qgsauthsettingswidget', 'qgsauthsslconfigdialog', 'qgsauthsslconfigwidget', 'qgsauthsslerrorsdialog', 'qgsauthsslimportdialog', 'qgsauthtrustedcasdialog', 'qgsblendmodecombobox', 'qgsblurwidget', 'qgsbrowserdockwidget', 'qgsbrowsertreeview', 'qgsbrushstylecombobox', 'qgsbusyindicatordialog', 'qgscategorizedsymbolrendererwidget', 'qgscentroidfillsymbollayerwidget', 'qgscharacterselectordialog', 'qgscheckablecombobox', 'qgscheckboxsearchwidgetwrapper', 'qgscodeeditor', 'qgscodeeditorcss', 'qgscodeeditorexpression', 'qgscodeeditorhtml', 'qgscodeeditorpython', 'qgscodeeditorsql', 'qgscollapsiblegroupbox', 'qgscollapsiblegroupboxbasic', 'qgscolorbox', 'qgscolorbrewercolorrampdialog', 'qgscolorbrewercolorrampwidget', 'qgscolorbutton', 'qgscolordialog', 'qgscoloreffectwidget', 'qgscolorpreviewwidget', 'qgscolorrampbutton', 'qgscolorrampshaderwidget', 'qgscolorrampwidget', 'qgscolorschemelist', 'qgscolorschememodel', 'qgscolorsliderwidget', 'qgscolorswatchdelegate', 'qgscolorswatchgrid', 'qgscolorswatchgridaction', 'qgscolortextwidget', 'qgscolorwheel', 'qgscolorwidget', 'qgscolorwidgetaction', 'qgscompoundcolorwidget', 'qgsconfigureshortcutsdialog', 'qgscoordinateboundspreviewmapwidget', 'qgscptcitycolorrampdialog', 'qgscredentialdialog', 'qgscurveeditorwidget', 'qgscustomdrophandler', 'qgscustomlayerorderwidget', 'qgsdashspacedialog', 'qgsdashspacewidget', 'qgsdatadefinedrotationdialog', 'qgsdatadefinedsizedialog', 'qgsdatadefinedsizelegendwidget', 'qgsdatadefinedvaluedialog', 'qgsdatadefinedwidthdialog', 'qgsdataitemguicontext', 'qgsdataitemguiprovider', 'qgsdataitemguiproviderregistry', 'qgsdatasourceselectdialog', 'qgsdatetimeedit', 'qgsdatetimesearchwidgetwrapper', 'qgsdefaultsearchwidgetwrapper', 'qgsdetaileditemdata', 'qgsdetaileditemdelegate', 'qgsdetaileditemwidget', 'qgsdial', 'qgsdialog', 'qgsdockwidget', 'qgsdoublespinbox', 'qgsdrawsourcewidget', 'qgsdualview', 'qgseditorconfigwidget', 'qgseditorwidgetautoconfplugin', 'qgseditorwidgetfactory', 'qgseditorwidgetregistry', 'qgseditorwidgetwrapper', 'qgseffectdrawmodecombobox', 'qgseffectstackcompactwidget', 'qgseffectstackpropertiesdialog', 'qgseffectstackpropertieswidget', 'qgsellipsesymbollayerwidget', 'qgsencodingfiledialog', 'qgsencodingselectiondialog', 'qgserrordialog', 'qgsexpressionbuilderdialog', 'qgsexpressionbuilderwidget', 'qgsexpressionhighlighter', 'qgsexpressionitem', 'qgsexpressionitemsearchproxy', 'qgsexpressionlineedit', 'qgsexpressionselectiondialog', 'qgsextentgroupbox', 'qgsexternalresourcewidget', 'qgsfeaturelistcombobox', 'qgsfeaturelistmodel', 'qgsfeaturelistview', 'qgsfeaturelistviewdelegate', 'qgsfeaturemodel', 'qgsfeatureselectiondlg', 'qgsfeatureselectionmodel', 'qgsfieldcombobox', 'qgsfieldconditionalformatwidget', 'qgsfieldexpressionwidget', 'qgsfieldvalidator', 'qgsfieldvalueslineedit', 'qgsfiledownloaderdialog', 'qgsfilewidget', 'qgsfilledmarkersymbollayerwidget', 'qgsfilterlineedit', 'qgsfindfilesbypatterndialog', 'qgsfindfilesbypatternwidget', 'qgsfloatingwidget', 'qgsfocuswatcher', 'qgsfontbutton', 'qgsfontmarkersymbollayerwidget', 'qgsformannotation', 'qgsgeometrygeneratorsymbollayerwidget', 'qgsgeometryrubberband', 'qgsglowwidget', 'qgsgradientcolorrampdialog', 'qgsgradientfillsymbollayerwidget', 'qgsgradientstopeditor', 'qgsgraduatedhistogramwidget', 'qgsgraduatedsymbolrendererwidget', 'qgsgroupboxcollapsebutton', 'qgsgroupwmsdatadialog', 'qgsgui', 'qgshashedlinesymbollayerwidget', 'qgsheatmaprendererwidget', 'qgshelp', 'qgshighlight', 'qgshillshaderendererwidget', 'qgshistogramwidget', 'qgshtmlwidgetwrapper', 'qgsifeatureselectionmanager', 'qgsidentifymenu', 'qgsimagesourcelineedit', 'qgsinvertedpolygonrendererwidget', 'qgskeyvaluewidget', 'qgsludialog', 'qgslayerpropertieswidget', 'qgslayertreeembeddedconfigwidget', 'qgslayertreeembeddedwidgetprovider', 'qgslayertreeembeddedwidgetregistry', 'qgslayertreemapcanvasbridge', 'qgslayertreeview', 'qgslayertreeviewdefaultactions', 'qgslayertreeviewindicator', 'qgslayertreeviewmenuprovider', 'qgslayoutcombobox', 'qgslayoutconfigobject', 'qgslayoutcustomdrophandler', 'qgslayoutdesignerinterface', 'qgslayoutitemabstractguimetadata', 'qgslayoutitembasewidget', 'qgslayoutitemcombobox', 'qgslayoutitemguigroup', 'qgslayoutitemguiregistry', 'qgslayoutitempropertiesdialog', 'qgslayoutitempropertieswidget', 'qgslayoutruler', 'qgslayoutunitscombobox', 'qgslayoutview', 'qgslayoutviewellipticalrubberband', 'qgslayoutviewmenuprovider', 'qgslayoutviewmouseevent', 'qgslayoutviewrectangularrubberband', 'qgslayoutviewrubberband', 'qgslayoutviewtool', 'qgslayoutviewtooladditem', 'qgslayoutviewtooladdnodeitem', 'qgslayoutviewtooleditnodes', 'qgslayoutviewtoolmoveitemcontent', 'qgslayoutviewtoolpan', 'qgslayoutviewtoolselect', 'qgslayoutviewtooltemporarykeypan', 'qgslayoutviewtooltemporarykeyzoom', 'qgslayoutviewtooltemporarymousepan', 'qgslayoutviewtoolzoom', 'qgslayoutviewtrianglerubberband', 'qgslegendfilterbutton', 'qgslimitedrandomcolorrampdialog', 'qgslimitedrandomcolorrampwidget', 'qgslinepatternfillsymbollayerwidget', 'qgslistwidget', 'qgslocatorwidget', 'qgslonglongvalidator', 'qgsmanageconnectionsdialog', 'qgsmapcanvas', 'qgsmapcanvasannotationitem', 'qgsmapcanvasitem', 'qgsmapcanvassnappingutils', 'qgsmapcanvastracer', 'qgsmaplayeraction', 'qgsmaplayeractionregistry', 'qgsmaplayercombobox', 'qgsmaplayerconfigwidget', 'qgsmaplayerconfigwidgetfactory', 'qgsmaplayerstylemanagerwidget', 'qgsmapmouseevent', 'qgsmapoverviewcanvas', 'qgsmaptip', 'qgsmaptool', 'qgsmaptooladvanceddigitizing', 'qgsmaptoolcapture', 'qgsmaptooledit', 'qgsmaptoolemitpoint', 'qgsmaptoolextent', 'qgsmaptoolidentify', 'qgsmaptoolidentifyfeature', 'qgsmaptoolpan', 'qgsmaptoolzoom', 'qgsmapunitscaledialog', 'qgsmapunitscalewidget', 'qgsmarkerlinesymbollayerwidget', 'qgsmenuheader', 'qgsmenuheaderwidgetaction', 'qgsmessagebar', 'qgsmessagebaritem', 'qgsmessagelogviewer', 'qgsmessageviewer', 'qgsmetadatawidget', 'qgsmultibandcolorrendererwidget', 'qgsmultiedittoolbutton', 'qgsnewauxiliaryfielddialog', 'qgsnewauxiliarylayerdialog', 'qgsnewgeopackagelayerdialog', 'qgsnewhttpconnection', 'qgsnewmemorylayerdialog', 'qgsnewnamedialog', 'qgsnewvectorlayerdialog', 'qgsnullsymbolrendererwidget', 'qgsowssourceselect', 'qgsopacitywidget', 'qgsoptionsdialogbase', 'qgsoptionsdialoghighlightbutton', 'qgsoptionsdialoghighlightcheckbox', 'qgsoptionsdialoghighlightgroupbox', 'qgsoptionsdialoghighlightlabel', 'qgsoptionsdialoghighlighttree', 'qgsoptionsdialoghighlightwidget', 'qgsoptionspagewidget', 'qgsoptionswidgetfactory', 'qgsorderbydialog', 'qgsorganizetablecolumnsdialog', 'qgspainteffectpropertieswidget', 'qgspainteffectwidget', 'qgspalettedrendererwidget', 'qgspanelwidget', 'qgspanelwidgetstack', 'qgspanelwidgetwrapper', 'qgspasswordlineedit', 'qgspencapstylecombobox', 'qgspenjoinstylecombobox', 'qgspenstylecombobox', 'qgspixmaplabel', 'qgspluginmanagerinterface', 'qgspointclusterrendererwidget', 'qgspointdisplacementrendererwidget', 'qgspointpatternfillsymbollayerwidget', 'qgspresetcolorrampdialog', 'qgspresetcolorrampwidget', 'qgsprevieweffect', 'qgsprocessingalgorithmconfigurationwidget', 'qgsprocessingalgorithmconfigurationwidgetfactory', 'qgsprocessingalgorithmdialogbase', 'qgsprocessingcontextgenerator', 'qgsprocessinggui', 'qgsprocessingguiregistry', 'qgsprocessingmaplayercombobox', 'qgsprocessingmodelerparameterwidget', 'qgsprocessingmultipleselectiondialog', 'qgsprocessingparameterwidgetcontext', 'qgsprocessingparameterwidgetfactoryinterface', 'qgsprocessingrecentalgorithmlog', 'qgsprocessingtoolboxmodel', 'qgsprocessingtoolboxmodelalgorithmnode', 'qgsprocessingtoolboxmodelgroupnode', 'qgsprocessingtoolboxmodelnode', 'qgsprocessingtoolboxmodelprovidernode', 'qgsprocessingtoolboxmodelrecentnode', 'qgsprocessingtoolboxproxymodel', 'qgsprocessingtoolboxtreeview', 'qgsprojectionselectiondialog', 'qgsprojectionselectiontreewidget', 'qgsprojectionselectionwidget', 'qgspropertyassistantwidget', 'qgspropertyoverridebutton', 'qgsproxystyle', 'qgsqmlwidgetwrapper', 'qgsquerybuilder', 'qgsrasterbandcombobox', 'qgsrasterfillsymbollayerwidget', 'qgsrasterformatsaveoptionswidget', 'qgsrasterhistogramwidget', 'qgsrasterlayersaveasdialog', 'qgsrastermarkersymbollayerwidget', 'qgsrasterminmaxwidget', 'qgsrasterpyramidsoptionswidget', 'qgsrasterrendererwidget', 'qgsrastertransparencywidget', 'qgsratiolockbutton', 'qgsrelationaggregatesearchwidgetwrapper', 'qgsrelationeditorwidget', 'qgsrelationreferencesearchwidgetwrapper', 'qgsrelationreferencewidget', 'qgsrelationreferencewidgetwrapper', 'qgsrelationwidgetwrapper', 'qgsrendererpropertiesdialog', 'qgsrendererrasterpropertieswidget', 'qgsrendererrulepropsdialog', 'qgsrendererrulepropswidget', 'qgsrendererwidget', 'qgsrubberband', 'qgsrulebasedrenderermodel', 'qgsrulebasedrendererwidget', 'qgssvgfillsymbollayerwidget', 'qgsscalecombobox', 'qgsscalerangewidget', 'qgsscalevisibilitydialog', 'qgsscalewidget', 'qgssearchquerybuilder', 'qgssearchwidgettoolbutton', 'qgssearchwidgetwrapper', 'qgsshadoweffectwidget', 'qgsshapeburstfillsymbollayerwidget', 'qgsshortcutsmanager', 'qgssimplefillsymbollayerwidget', 'qgssimplelinesymbollayerwidget', 'qgssimplemarkersymbollayerwidget', 'qgssinglebandgrayrendererwidget', 'qgssinglebandpseudocolorrendererwidget', 'qgssinglesymbolrendererwidget', 'qgsslider', 'qgssmartgroupcondition', 'qgssmartgroupeditordialog', 'qgssnapindicator', 'qgssnaptogridcanvasitem', 'qgssourceselectprovider', 'qgssourceselectproviderregistry', 'qgsspinbox', 'qgsstatusbar', 'qgsstyleexportimportdialog', 'qgsstylegroupselectiondialog', 'qgsstylemanagerdialog', 'qgsstylesavedialog', 'qgssublayersdialog', 'qgssubstitutionlistdialog', 'qgssubstitutionlistwidget', 'qgssvgmarkersymbollayerwidget', 'qgssvgselectordialog', 'qgssvgselectorgroupsmodel', 'qgssvgselectorlistmodel', 'qgssvgselectorwidget', 'qgssvgsourcelineedit', 'qgssymbolbutton', 'qgssymbollayerwidget', 'qgssymbollevelsdialog', 'qgssymbollevelswidget', 'qgssymbolselectordialog', 'qgssymbolselectorwidget', 'qgssymbolwidgetcontext', 'qgssymbolslistwidget', 'qgstabwidget', 'qgstablewidgetbase', 'qgstablewidgetitem', 'qgstaskmanagerwidget', 'qgstextformatdialog', 'qgstextformatpanelwidget', 'qgstextformatwidget', 'qgstextpreview', 'qgstransformwidget', 'qgstreewidgetitem', 'qgstreewidgetitemobject', 'qgsunitselectionwidget', 'qgsuserinputwidget', 'qgsvscrollarea', 'qgsvaliditycheckresultsmodel', 'qgsvaliditycheckresultswidget', 'qgsvaluemapsearchwidgetwrapper', 'qgsvaluerelationsearchwidgetwrapper', 'qgsvariableeditorwidget', 'qgsvectorfieldsymbollayerwidget', 'qgsvertexmarker', 'qgswidgetwrapper', 'qgswindowmanagerinterface', 'qgis.core', 'qgis.core.additions', 'qgis.core.additions.edit', 'qgis.core.additions.fromfunction', 'qgis.core.additions.qgstaskwrapper', 'qgis.core.additions.markerlinesymbollayer', 'qgis.core.additions.metaenum', 'qgis.core.additions.processing', 'qgis.core.additions.projectdirtyblocker', 'qgis.core.additions.qgsfeature', 'qgis.core.additions.qgsfunction', 'inspect', 'dis', 'opcode', '_opcode', 'qgis.core.additions.qgsgeometry', 'qgis.core.additions.qgssettings', 'qgis.core.additions.readwritecontextentercategory', 'qgis.core.additions.validitycheck', 'hera.I18N', 'gettext', 'locale', 'unicodedata', 'hera.PropertyManager', 'hera.EntityModel', 'json', 'json.decoder', 'json.scanner', '_json', 'json.encoder', 'hera.FileUtils', 'osgeo', 'imp', 'swig_runtime_data4', '_gdal', 'osgeo.ogr', 'osgeo._ogr', 'osgeo.osr', 'osgeo._osr', 'shutil', 'zlib', 'bz2', '_compression', '_bz2', 'lzma', '_lzma', 'tempfile', 'random', 'math', 'hashlib', '_hashlib', '_blake2', '_sha3', 'bisect', '_bisect', '_random', 'hera.DataModel', 'datetime', '_datetime', 'copy', 'psrl', 'psrl.psrl', 'hera.PluginManager', 'hera.DynamicGui', 'matplotlib', 'distutils.version', 'pprint', 'subprocess', 'signal', '_winapi', 'urllib.request', 'base64', 'binascii', 'email', 'http', 'http.client', 'email.parser', 'email.feedparser', 'email.errors', 'email._policybase', 'email.header', 'email.quoprimime', 'email.base64mime', 'email.charset', 'email.encoders', 'quopri', 'email.utils', 'socket', '_socket', 'selectors', 'select', 'email._parseaddr', 'calendar', 'email.message', 'uu', 'email._encoded_words', 'email.iterators', 'ssl', '_ssl', 'urllib.error', 'urllib.response', 'nturl2path', 'matplotlib.cbook', 'glob', 'gzip', 'numbers', 'numpy', '__future__', 'numpy._globals', 'numpy.__config__', 'numpy.version', 'numpy._distributor_init', 'numpy.core', 'numpy.core.info', 'numpy.core.multiarray', 'numpy.core.overrides', 'numpy.core._multiarray_umath', 'numpy.compat', 'numpy.compat._inspect', 'numpy.compat.py3k', 'numpy.core.umath', 'numpy.core.numerictypes', 'numpy.core._string_helpers', 'numpy.core._type_aliases', 'numpy.core._dtype', 'numpy.core.numeric', 'numpy.core._internal', 'pickle', '_compat_pickle', '_pickle', 'numpy.core.fromnumeric', 'numpy.core._methods', 'numpy.core.arrayprint', 'numpy.core.defchararray', 'numpy.core.records', 'numpy.core.memmap', 'numpy.core.function_base', 'numpy.core.machar', 'numpy.core.getlimits', 'numpy.core.shape_base', 'numpy.core.einsumfunc', 'numpy.core._add_newdocs', 'numpy.core._multiarray_tests', 'numpy.core._dtype_ctypes', 'numpy._pytesttester', 'numpy.lib', 'numpy.lib.info', 'numpy.lib.type_check', 'numpy.lib.ufunclike', 'numpy.lib.index_tricks', 'numpy.matrixlib', 'numpy.matrixlib.defmatrix', 'ast', '_ast', 'numpy.linalg', 'numpy.linalg.info', 'numpy.linalg.linalg', 'numpy.lib.twodim_base', 'numpy.linalg.lapack_lite', 'numpy.linalg._umath_linalg', 'numpy.lib.function_base', 'numpy.lib.utils', 'numpy.lib.histograms', 'numpy.lib.stride_tricks', 'numpy.lib.mixins', 'numpy.lib.nanfunctions', 'numpy.lib.shape_base', 'numpy.lib.scimath', 'numpy.lib.polynomial', 'numpy.lib.arraysetops', 'numpy.lib.npyio', 'numpy.lib.format', 'numpy.lib._datasource', 'numpy.lib._iotools', 'numpy.lib.financial', 'decimal', '_decimal', 'numpy.lib.arrayterator', 'numpy.lib.arraypad', 'numpy.lib._version', 'numpy.fft', 'numpy.fft.info', 'numpy.fft.fftpack', 'numpy.fft.fftpack_lite', 'numpy.fft.helper', 'numpy.polynomial', 'numpy.polynomial.polynomial', 'numpy.polynomial.polyutils', 'numpy.polynomial._polybase', 'numpy.polynomial.chebyshev', 'numpy.polynomial.legendre', 'numpy.polynomial.hermite', 'numpy.polynomial.hermite_e', 'numpy.polynomial.laguerre', 'numpy.random', 'numpy.random.mtrand', 'cython_runtime', 'mtrand', 'numpy.ctypeslib', 'numpy.ma', 'numpy.ma.core', 'textwrap', 'numpy.ma.extras', 'numpy.testing', 'unittest', 'unittest.result', 'unittest.util', 'unittest.case', 'difflib', 'unittest.suite', 'unittest.loader', 'unittest.main', 'argparse', 'unittest.runner', 'unittest.signals', 'numpy.testing._private', 'numpy.testing._private.utils', 'gc', 'numpy.testing._private.decorators', 'numpy.testing._private.nosetester', 'matplotlib.cbook.deprecation', 'matplotlib.rcsetup', 'matplotlib.fontconfig_pattern', 'pyparsing', 'matplotlib.colors', 'matplotlib._color_data', 'cycler', 'six', 'six.moves', 'matplotlib._version', 'dateutil', 'dateutil._version']
2020-01-22 17:41:06 DEBUG: __init__.wrapper - CACHEDIR=C:\Users\pedro\.matplotlib
2020-01-22 17:41:06 DEBUG: font_manager.<module> - Using fontManager instance from C:\Users\pedro\.matplotlib\fontlist-v300.json
2020-01-22 17:41:06 DEBUG: pyplot.switch_backend - Loaded backend Qt5Agg version unknown.
2020-01-22 17:41:06 INFO: PluginManager.findAndLoadPlugins - Looking for plugins
2020-01-22 17:41:06 INFO: PluginManager.findAndLoadPlugins - Loading plugin DevTools
2020-01-22 17:41:06.767810: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-01-22 17:41:06.768117: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2020-01-22 17:41:07 INFO: PluginManager.findAndLoadPlugins - Loaded module: DevTools.PHSAlgorithms
2020-01-22 17:41:07 INFO: PluginManager.findAndLoadPlugins - Loaded module: DevTools.ReservoirTool
Traceback (most recent call last):
  File "C:\Development\Hera3\hera.application\src\HeraDev.py", line 1, in <module>
    import HeraDevEnv
  File "C:\Development\Hera3\hera.application\src\HeraDevEnv.py", line 29, in <module>
    PluginManager.findAndLoadPlugins()
  File "C:\Development\Hera3\hera.application\src\hera\PluginManager.py", line 39, in findAndLoadPlugins
    raise Exception('Could not import plugin modules: {:}. Exceptions: {:}'.format([n for _,n,_ in nextModules], exceptions))
Exception: Could not import plugin modules: ['Config', 'RiverDataTool']. Exceptions: [AttributeError("type object 'h5py.h5.H5PYConfig' has no attribute '__reduce_cython__'"), AttributeError("type object 'h5py.h5.H5PYConfig' has no attribute '__reduce_cython__'")]
```

**Comment by gadagashwini** [comment]
@prpeixoto, can you provide the versions of 
```
keras-applications
keras-preprocessing
```
Thanks

**Comment by prpeixoto** [comment]
@gadagashwini , these are the versions that are currently installed.

keras
2.2.4-tf
keras-applications
1.0.8
keras-preprocessing
1.1.0

**Comment by colt18** [comment]
Are Hera and tf under the same virtuel-env. There may be some conflicts version-wise.

**Comment by gadagashwini** [comment]
@prpeixoto, Tensorflow 2.1 support, `keras-applications 1.0.8`, `keras-preprocessing 1.1.0`.

Can you follow below instructions to install Tensorflow 2.1 using PIP by creating virtual env.

#Install tensorflow using pip virtual env 
$pip install virtualenv
$virtualenv tf_2.1   # tf_2.1 is virtual env name
$source tf_2.1/bin/activate
tf_2.1 $ pip install tensorflow==2.1
tf_2.1 $ python
>>import tensorflow as tf
>>tf.__version__
2.1
Let us know how it progresses. Thanks!

**Comment by prpeixoto** [comment]
Firstly, thank you for your responses. I tried the recommended actions and it didn't work. However, downgrading the H5py module to 2.9 seems to have done the trick. I had previously tried downgrading to 2.8 but, for some reason, skipped 2.9. I am very curious to know why this isn't an issue on the 2.9 but is in 2.10, something that if continues on future versions, will be a problem. 
Thank you again @gadagashwini  and @colt18
