### ISSUE TITLE
Help! I have an issue when importing TF!

### ISSUE THREAD

**Issue by Brayden1000** [tensorflow/tensorflow#36167]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
no, it is custom code but I did not write it https://medium.com/swlh/nvidia-jetson-nano-custom-object-detection-from-scratch-using-tensorflow-and-opencv-113fe4dba134 I got it from here and the TF conversion script
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 x64
- TensorFlow installed from (source or binary): I installed with pip install Tensorflow and Tensorflow-gpu
- TensorFlow version (use command below): 2.1.0
- Python version: 3.7.6
- CUDA/cuDNN version: 10.1
- GPU model and memory: 960M 4gb

**Describe the current behavior**
When I run the script I get the error Failed to load the native TensorFlow runtime. with a bunch of other errors that I will paste down bellow.

**Describe the expected behavior**
To run the script lol

**Code to reproduce the issue**
I am just running python and then the directory to the .py file

Any help is appreciated thanks!!!!

**Other info / logs**
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Python37\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Python37\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\minec\Desktop\Robotics_stuff\TFconvert.py", line 4, in <module>
    import tensorflow as tf
  File "C:\Python37\lib\site-packages\tensorflow\__init__.py", line 101, in <module>
    from tensorflow_core import *
  File "C:\Python37\lib\site-packages\tensorflow_core\__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Python37\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\Python37\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "C:\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Python37\lib\site-packages\tensorflow_core\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Python37\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Python37\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by mihaimaruseac** [comment]
This issue shows up in multiple places #36167 #36151 #36138 #36054 #36045 #36020 #36003 #35988 #35903 #35880 #35865 #35805 #35789 #35773 #35772 #35767 #35766 #35749 #35721 #35618 #35204
 
No such place mentions which DLL fails or differentiates from the others.

**Comment by Brayden1000** [comment]
> This issue shows up in multiple places #36167 #36151 #36138 #36054 #36045 #36020 #36003 #35988 #35903 #35880 #35865 #35805 #35789 #35773 #35772 #35767 #35766 #35749 #35721 #35618 #35204
> 
> No such place mentions which DLL fails or differentiates from the others.

Yeah I've seen that it had been mentioned a lot of times any solutions that you have found or no?

**Comment by mihaimaruseac** [comment]
There are at least 3 possible scenarios:

1. You need to install the MSVC 2019 redistributable
2. Your CPU does not support AVX2 instructions
3. Your CPU/Python is on 32 bits
4. There is a library that is in a different location/not installed on your system that cannot be loaded.

**Comment by gunan** [comment]
Could you share your CPU make and model?

**Comment by bmzhao** [comment]
Hi @Brayden1000, 

Did you install the Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017, and 2019?

According to the docs at https://www.tensorflow.org/install/pip,

> Install the Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017, and 2019. Starting with the TensorFlow 2.1.0 version, the msvcp140_1.dll file is required from this package (which may not be provided from older redistributable packages). The redistributable comes with Visual Studio 2019 but can be installed separately:

> Go to the [Microsoft Visual C++ downloads](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads),
Scroll down the page to the Visual Studio 2015, 2017 and 2019 section.
Download and install the Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019 for your platform.
Make sure [long paths](https://superuser.com/questions/1119883/windows-10-enable-ntfs-long-paths-policy-option-missing) are enabled on Windows.

> Install the [64-bit Python 3 release](https://www.python.org/downloads/windows/) for Windows (select pip as an optional feature).

Tensorflow 2.1.0 is compiled using MSVC 2019, which appears to require an additional DLL.
