### ISSUE TITLE
Op Request

### ISSUE THREAD

**Issue by echu87** [tensorflow/tensorflow#36160]
**System information**
- Windows 10
- TensorFlow installed from source:
- TensorFlow version 2.1 (cpu)

```
Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, CONCATENATION, CONV_2D, DEPTHWISE_CONV_2D, DIV, EXP, FILL, FULLY_CONNECTED, GATHER, LOGISTIC, MAX_POOL_2D, MUL, PACK, PRELU, REDUCE_MAX, RESHAPE, REVERSE_V2, SHAPE, STRIDED_SLICE, SUB, SUM, TRANSPOSE. Here is a list of operators for which you will need custom implementations: TensorListFromTensor, TensorListReserve, TensorListStack, While.
Traceback (most recent call last):
  File "c:\users\evan.chu$\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\evan.chu$\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Evan.Chu$\AppData\Local\Programs\Python\Python37\Scripts\toco_from_protos.exe\__main__.py", line 9, in <module>
  File "c:\users\evan.chu$\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\lite\toco\python\toco_from_protos.py", line 93, in main
    app.run(main=execute, argv=[sys.argv[0]] + unparsed)
  File "c:\users\evan.chu$\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "c:\users\evan.chu$\appdata\local\programs\python\python37\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "c:\users\evan.chu$\appdata\local\programs\python\python37\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "c:\users\evan.chu$\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\lite\toco\python\toco_from_protos.py", line 56, in execute
    enable_mlir_converter)

```
Also, please include a link to a GraphDef or the model if possible.
https://github.com/arthurflor23/handwritten-text-recognition/blob/master/src/network/model.py (Flor implementation, not Bluche or Puigcerver)

**Comment by echu87** [comment]
Hi, I just followed the advice that @oanush gave in #36152, and it seems that it has fixed the issue. 

"Please try including the code before tflite=converter.convert()

converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,
                                       tf.lite.OpsSet.SELECT_TF_OPS]
For more information refer #35590
If the issue is still not resolved please provide us the complete code snippet used.Thanks!"

**Comment by echu87** [comment]
One additional issue, when I try to load the TFLite model I run into the issue:

Traceback (most recent call last):
  File "details.py", line 4, in <module>
    interpreter.allocate_tensors()
  File "C:\Users\Evan.Chu$\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\lite\python\interpreter.py", line 247, in allocate_tensors
    return self._interpreter.AllocateTensors()
  File "C:\Users\Evan.Chu$\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\lite\python\interpreter_wrapper\tensorflow_wrap_interpreter_wrapper.py", line 110, in AllocateTensors
    return _tensorflow_wrap_interpreter_wrapper.InterpreterWrapper_AllocateTensors(self)
RuntimeError: Encountered unresolved custom op: TensorListFromTensor.Node number 53 (TensorListFromTensor) failed to prepare.

Clearly the issue is still related to the previous issue, and I'm wondering if there is a permanent fix rather than the "band-aid" fix that I commented earlier that doesn't involve creating a custom op?

**Comment by ymodak** [comment]
Can you also ad `experimental_converter` flag?
`converter.experimental_new_converter = True`

**Comment by echu87** [comment]
Hi, forgot to update the issue earlier but I did try that and it was able to convert and load using the interpreter. Thanks for the help!

**Comment by 2696120622** [comment]
> Hi, forgot to update the issue earlier but I did try that and it was able to convert and load using the interpreter. Thanks for the help!

@ech
Hello, which model did you converted? I encountered one similar issue when converting efficientdet model. The issue is detailed in this 

> https://github.com/tensorflow/tensorflow/issues/37003#issue-569633708

.

Can you help me?
