### ISSUE TITLE
tf.data.Dataset.from_tensor_slices throws error when using an array of numbers instead of a string

### ISSUE THREAD

**Issue by Ansreng360** [tensorflow/tensorflow#36185]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 (64 bit), Windows-10-10.0.18362-SP0
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary (pip)
- TensorFlow version (use command below): 2.0.0
- Python version: 3.7.0
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**

I'm using tf.data.Dataset.from_tensor_slices to create a dataset from a dataframe. The dataframe has a column called "Text", which usually contains strings as entries. Executing it like that works fine. However, when I encode those strings to arrays of number, the function throws an error.

The number of the failed arrays is 2312, while the complete number of arrays is actually around 3600. So not every array is failing.

**Describe the expected behavior**
It should work without error.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
```
def df_to_dataset(dataframe):
  dataframe = dataframe.copy()
  labels = dataframe.pop('Emotion')
  ds = tf.data.Dataset.from_tensor_slices((dict(dataframe), labels))
  return ds
```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

```
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\data\util\structure.py", line 91, in normalize_element
    spec = type_spec_from_value(t, use_fallback=False)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\data\util\structure.py", line 457, in type_spec_from_value
    (element, type(element).__name__))
TypeError: Could not build a TypeSpec for 2666    [1424, 11572, 1372, 11572, 2289, 11584, 11572,...
2091    [11637, 11572, 690, 11572, 11, 11572, 3376, 11...
832     [11613, 11572, 72, 11572, 65, 11572, 472, 1157...
2572    [355, 11572, 11613, 11572, 36, 11572, 11645, 1...
2187              [182, 11572, 405, 11572, 1, 11572, 335]
                              ...
3427    [4416, 11572, 37, 11572, 4408, 11572, 2, 11572...
2868    [20, 11572, 23, 11572, 11637, 11572, 254, 1157...
1806    [6870, 11572, 9118, 11572, 5883, 11572, 5190, ...
1266    [44, 11572, 525, 11572, 702, 11572, 63, 11572,...
3047    [1795, 11572, 46, 11572, 503, 11572, 5, 11572,...
Name: Text, Length: 2312, dtype: object with type Series

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\Mood recognition.py", line 85, in <module>
    train_ds = df_to_dataset(train, batch_size=batch_size)
  File ".\Mood recognition.py", line 70, in df_to_dataset
    ds = tf.data.Dataset.from_tensor_slices((dict(dataframe), labels))
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\data\ops\dataset_ops.py", line 435, in from_tensor_slices
    return TensorSliceDataset(tensors)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\data\ops\dataset_ops.py", line 2354, in __init__
    element = structure.normalize_element(element)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\data\util\structure.py", line 96, in normalize_element
    ops.convert_to_tensor(t, name="component_%d" % i))
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1184, in convert_to_tensor
    return convert_to_tensor_v2(value, dtype, preferred_dtype, name)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1242, in convert_to_tensor_v2
    as_ref=False)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1296, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\framework\constant_op.py", line 286, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\framework\constant_op.py", line 227, in constant
    allow_broadcast=True)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\framework\constant_op.py", line 235, in _constant_impl
    t = convert_to_eager_tensor(value, ctx, dtype)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\framework\constant_op.py", line 96, in convert_to_eager_tensor
    return ops.EagerTensor(value, ctx.device_name, dtype)
ValueError: Can't convert non-rectangular Python sequence to Tensor.
```

**Comment by Ansreng360** [comment]
It's probably an issue with the different length of the arrayy.

**Comment by Firyuza** [comment]
Or if you have duplicated columns (the same names) in dataframe.

**Comment by ajaceves** [comment]
Having this issue with 2.3, no duplicate columns or ragged arrays.

**Comment by joenipko** [comment]
I'm having the same issue with the same version of tensorflow  (2.3)

**Comment by joenipko** [comment]
Turns out I had a null value in one of the rows for the numeric columns in my data that was causing the issue

**Comment by mobinalhassan** [comment]
> Turns out I had a null value in one of the rows for the numeric columns in my data that was causing the issue

This works for me...

**Comment by rajattan** [comment]
I am running into the same issue, but there isn't any null value
