### ISSUE TITLE
ModuleNotFoundError: No module named 'pycocotools._mask' PLEASE HELP ME!!!!

### ISSUE THREAD

**Issue by Brayden1000** [tensorflow/tensorflow#36205]
I am running a Windows 10 x64 machine and I do find the _mask.pyx file in the path specified but it still can't find it for some reason! I have followed the instructions off of this website. Any help is much appreciated, I have run the build.py off of the cocoAPI since I am on windows. I have tried to install pycotools through pip. I have gone through every website with this issue mentioned and nothing has worked!!!! Thanks!

**Describe the current behavior**
its giving me this error:

    Traceback (most recent call last):
    File "model_main.py", line 25, in <module>
    from object_detection import model_lib
    File "C:\Python37\models\research\object_detection\model_lib.py", line 27, in <module>
    from object_detection import eval_util
    File "C:\Python37\models\research\object_detection\eval_util.py", line 33, in <module>
    from object_detection.metrics import coco_evaluation
    File "C:\Python37\models\research\object_detection\metrics\coco_evaluation.py", line 25, in <module>
    from object_detection.metrics import coco_tools
    File "C:\Python37\models\research\object_detection\metrics\coco_tools.py", line 51, in <module>
    from pycocotools import coco
    File "C:\Python37\models\research\pycocotools\coco.py", line 55, in <module>
    from . import mask as maskUtils
    File "C:\Python37\models\research\pycocotools\mask.py", line 3, in <module>
    import pycocotools._mask as _mask
    ModuleNotFoundError: No module named 'pycocotools._mask'

**Describe the expected behavior**
It should run this command:
`python model_main.py --logtostderr --train_dir=training/ --pipeline_config_path=training/ssdlite_mobilenet_v2_coco.config`

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
Idk

**Other info / logs**
I included the logs above I really need help soon!!!

**Comment by mihaimaruseac** [comment]
Please provide the information required by the issue template.

**Comment by oanush** [comment]
@Brayden1000 ,
Any update on the issue ?Thanks!

**Comment by oanush** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
