### ISSUE TITLE
Issue on importing tensorflow

### ISSUE THREAD

**Issue by Timothee56** [tensorflow/tensorflow#36212]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac Catalina version 10.15.2
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): installed from source
- TensorFlow version: 2.1
- Python version: 3.7
- Installed using virtualenv? pip? conda?: virtualenv
- Bazel version (if compiling from source): 
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**I've installed tensorflow on a virtual environment but I can't import to use it**

** I've Followed the installation instructions from the tensorflow website on https://www.tensorflow.org/install/pip **

**I don't know if this is linked but I can't find tensorflow on the Anaconda list of package after creating a new environment in the Anaconda Navigator **

----------------------------------------------- 
(venvtensorflow) tim@MacBook-Pro-de-Timothee ~ % pip list
Package              Version   
_________.           ___________
absl-py              0.9.0     
astor                0.8.1     
cachetools           4.0.0     
certifi              2019.11.28
chardet              3.0.4     
gast                 0.2.2     
google-auth          1.11.0    
google-auth-oauthlib 0.4.1     
google-pasta         0.1.8     
grpcio               1.26.0    
h5py                 2.10.0    
idna                 2.8       
Keras-Applications   1.0.8     
Keras-Preprocessing  1.1.0     
Markdown             3.1.1     
numpy                1.18.1    
oauthlib             3.1.0     
opt-einsum           3.1.0     
pip                  20.0.2    
protobuf             3.11.2    
pyasn1               0.4.8     
pyasn1-modules       0.2.8     
requests             2.22.0    
requests-oauthlib    1.3.0     
rsa                  4.0       
scipy                1.4.1     
setuptools           45.1.0    
six                  1.12.0    
tensorboard          2.1.0     
tensorflow           2.1.0                         <- Tensorflow seems installed
tensorflow-estimator 2.1.0     
termcolor            1.1.0     
urllib3              1.25.8    
Werkzeug             0.16.0    
wheel                0.33.6    
wrapt                1.11.2  

----------------------------------------------- 
(venvtensorflow) tim@MacBook-Pro-de-Timothee ~ % python
Python 3.7.3 (default, Dec 13 2019, 19:58:14) 
[Clang 11.0.0 (clang-1100.0.33.17)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tim/venvtensorflow/lib/python3.7/site-packages/tensorflow/__init__.py", line 101, in <module>
    from tensorflow_core import *
  File "/Users/tim/venvtensorflow/lib/python3.7/site-packages/tensorflow_core/__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 959, in _find_and_load_unlocked
  File "/Users/tim/venvtensorflow/lib/python3.7/site-packages/tensorflow/__init__.py", line 50, in __getattr__
    module = self._load()
  File "/Users/tim/venvtensorflow/lib/python3.7/site-packages/tensorflow/__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "/Users/tim/venvtensorflow/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/tim/venvtensorflow/lib/python3.7/site-packages/tensorflow_core/python/__init__.py", line 64, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/Users/tim/venvtensorflow/lib/python3.7/site-packages/tensorflow_core/core/framework/graph_pb2.py", line 7, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/Users/tim/venvtensorflow/lib/python3.7/site-packages/google/protobuf/__init__.py", line 37, in <module>
    __import__('pkg_resources').declare_namespace(__name__)
  File "/Users/tim/venvtensorflow/lib/python3.7/site-packages/pkg_resources/__init__.py", line 84, in <module>
    __import__('pkg_resources.extern.packaging.requirements')
  File "/Users/tim/venvtensorflow/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 9, in <module>
    from pkg_resources.extern.pyparsing import stringStart, stringEnd, originalTextFor, ParseException
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/Users/tim/venvtensorflow/lib/python3.7/site-packages/pkg_resources/extern/__init__.py", line 43, in load_module
    __import__(extant)
  File "/Users/tim/venvtensorflow/lib/python3.7/site-packages/pkg_resources/_vendor/pyparsing.py", line 4756, in <module>
    _escapedPunc = Word( _bslash, r"\[]-*.$+^?()~ ", exact=2 ).setParseAction(lambda s,l,t:t[0][1])
  File "/Users/tim/venvtensorflow/lib/python3.7/site-packages/pkg_resources/_vendor/pyparsing.py", line 1284, in setParseAction
    self.parseAction = list(map(_trim_arity, list(fns)))
  File "/Users/tim/venvtensorflow/lib/python3.7/site-packages/pkg_resources/_vendor/pyparsing.py", line 1066, in _trim_arity
    this_line = extract_stack(limit=2)[-1]
  File "/Users/tim/venvtensorflow/lib/python3.7/site-packages/pkg_resources/_vendor/pyparsing.py", line 1050, in extract_stack
    frame_summary = traceback.extract_stack(limit=-offset+limit-1)[offset]
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/traceback.py", line 211, in extract_stack
    stack = StackSummary.extract(walk_stack(f), limit=limit)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/traceback.py", line 363, in extract
    f.line
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/traceback.py", line 285, in line
    self._line = linecache.getline(self.filename, self.lineno).strip()
  File "/Users/tim/venvtensorflow/lib/python3.7/linecache.py", line 16, in getline
    lines = getlines(filename, module_globals)
  File "/Users/tim/venvtensorflow/lib/python3.7/linecache.py", line 48, in getlines
    for mod in sys.modules.values():
RuntimeError: dictionary changed size during iteration

**Comment by mihaimaruseac** [comment]
This seems to be an ssue with the macos python. See also #33183

**Comment by mihaimaruseac** [comment]
Since this is not a TF issue, we'll close this issue.
