### ISSUE TITLE
tf.lite.converter.convert() Erroe

### ISSUE THREAD

**Issue by pramodjayram** [tensorflow/tensorflow#36219]
**System information**
- OS Platform and Distribution Ubuntu 18.04
- TensorFlow version (or github SHA if from source):2.0.0b1

I am trying to test LSTM/GRU code using TensorFlow 2.0.0b1 in ubuntu 18.04.
Below you can find my simple model and converter code

```
def create_gru_model():
    model = tf.keras.models.Sequential();
    model.add(tf.keras.layers.GRU(128))
    model.add(tf.keras.layers.Flatten())
    model.add(tf.keras.layers.Dense(49,activation=tf.nn.softmax))
    model.compile(optimizer='adam',loss=customLoss,metrics = ['accuracy'])
    return model
model = create_gru_model()
model.fit(x_train, y_train, epochs = 3, callbacks = [cp_callback], validation_data = (x_valid,y_valid), verbose=0)
converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.experimental_new_converter=True
tflite_model = converter.convert()
```

I get the following error

```
Traceback (most recent call last):
  File "test.py", line 148, in <module>
    tflite_model = converter.convert()
  File "/home/pramod/.local/lib/python3.7/site-packages/tensorflow/lite/python/lite.py", line 392, in convert
    **converter_kwargs)
  File "/home/pramod/.local/lib/python3.7/site-packages/tensorflow/lite/python/convert.py", line 404, in toco_convert_impl
    input_data.SerializeToString())
  File "/home/pramod/.local/lib/python3.7/site-packages/tensorflow/lite/python/convert.py", line 172, in toco_convert_protos
    "TOCO failed. See console for info.\n%s\n%s\n" % (stdout, stderr))
tensorflow.lite.python.convert.ConverterError: TOCO failed. See console for info.
/home/pramod/.local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/pramod/.local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/pramod/.local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/pramod/.local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/pramod/.local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/pramod/.local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/home/pramod/.local/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/pramod/.local/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/pramod/.local/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/pramod/.local/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/pramod/.local/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/pramod/.local/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
2020-01-26 12:56:17.818849: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2020-01-26 12:56:17.818886: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2020-01-26 12:56:17.818892: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2020-01-26 12:56:17.818987: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: StatefulPartitionedCall
2020-01-26 12:56:17.827230: F tensorflow/lite/toco/import_tensorflow.cc:114] Check failed: attr.value_case() == AttrValue::kType (1 vs. 6)
Fatal Python error: Aborted

Current thread 0x00007f4c3f6b7740 (most recent call first):
  File "/home/pramod/.local/lib/python3.7/site-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 33 in execute
  File "/home/pramod/.local/lib/python3.7/site-packages/absl/app.py", line 250 in _run_main
  File "/home/pramod/.local/lib/python3.7/site-packages/absl/app.py", line 299 in run
  File "/home/pramod/.local/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 40 in run
  File "/home/pramod/.local/lib/python3.7/site-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 59 in main
  File "/home/pramod/.local/bin/toco_from_protos", line 11 in <module>
Aborted (core dumped)



Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 24, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "test.py", line 148, in <module>
    tflite_model = converter.convert()
  File "/home/pramod/.local/lib/python3.7/site-packages/tensorflow/lite/python/lite.py", line 392, in convert
    **converter_kwargs)
  File "/home/pramod/.local/lib/python3.7/site-packages/tensorflow/lite/python/convert.py", line 404, in toco_convert_impl
    input_data.SerializeToString())
  File "/home/pramod/.local/lib/python3.7/site-packages/tensorflow/lite/python/convert.py", line 172, in toco_convert_protos
    "TOCO failed. See console for info.\n%s\n%s\n" % (stdout, stderr))
tensorflow.lite.python.convert.ConverterError: TOCO failed. See console for info.
/home/pramod/.local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/pramod/.local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/pramod/.local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/pramod/.local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/pramod/.local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/pramod/.local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/home/pramod/.local/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/pramod/.local/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/pramod/.local/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/pramod/.local/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/pramod/.local/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/pramod/.local/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
2020-01-26 12:56:17.818849: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2020-01-26 12:56:17.818886: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2020-01-26 12:56:17.818892: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2020-01-26 12:56:17.818987: I tensorflow/lite/toco/import_tensorflow.cc:1336] Converting unsupported operation: StatefulPartitionedCall
2020-01-26 12:56:17.827230: F tensorflow/lite/toco/import_tensorflow.cc:114] Check failed: attr.value_case() == AttrValue::kType (1 vs. 6)
Fatal Python error: Aborted

Current thread 0x00007f4c3f6b7740 (most recent call first):
  File "/home/pramod/.local/lib/python3.7/site-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 33 in execute
  File "/home/pramod/.local/lib/python3.7/site-packages/absl/app.py", line 250 in _run_main
  File "/home/pramod/.local/lib/python3.7/site-packages/absl/app.py", line 299 in run
  File "/home/pramod/.local/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 40 in run
  File "/home/pramod/.local/lib/python3.7/site-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 59 in main
  File "/home/pramod/.local/bin/toco_from_protos", line 11 in <module>
Aborted (core dumped)

```

**Comment by mihaimaruseac** [comment]
Why not switch to a final release? 2.0 or 2.1?

**Comment by oanush** [comment]
@pramodjayram,
Please switch to latest versions of tf 2.0 or 2.1 and try adding 
```
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,
                                       tf.lite.OpsSet.SELECT_TF_OPS]
``` 
in the code, and let us know if it helps. Please find refer #[35590](https://github.com/tensorflow/tensorflow/issues/35590) similar issue.Thanks!

**Comment by pramodjayram** [comment]
I switched to the latest version of tf 2.1 and added the above lines. It perfectly created the tflite file. But when I use the GRU model on the board, I get an error message on the serial console of the board.
```
Only 1 subgraph is currently supported.
AllocateTensors() failed
```
If I remove the GRU layer from the model above, it works perfectly. But when GRU is included it ends up with this error.
It would be quite helpful if somebody knows the solution or an explanation for this following error report.

**Comment by ymodak** [comment]
Are you performing an optimizations on tf lite file? If so, then can you try without optimizations?
See https://github.com/tensorflow/tensorflow/issues/35194

**Comment by pramodjayram** [comment]
I tried with optimization and without but both resulted in the same error.

**Comment by pramodjayram** [comment]
Below is the exact code that I am running

```
def customLoss(yTrue,yPred):

    return tf.nn.softmax_cross_entropy_with_logits(labels=yTrue,logits=yPred)


def create_gru_model():
    model = tf.keras.models.Sequential([
        tf.keras.layers.Input(shape=(1, 49), name='input'),
        tf.keras.layers.GRU(2),
        tf.keras.layers.Flatten(),
        tf.keras.layers.Dense(49, activation=tf.nn.softmax, name='output')
    ])
    model.compile(optimizer = 'adam',
                  loss = customLoss,
                  metrics = ['accuracy'])
    return model
x_train = tf.keras.utils.normalize(x_train, axis = 1)
x_test = tf.keras.utils.normalize(x_test, axis = 1)

checkpoint_path = "training_gru/cp-{epoch:04d}.ckpt"
checkpoint_dir = os.path.dirname(checkpoint_path)
model = create_gru_model()
model.fit(x_train, y_train, epochs = 1)
converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.experimental_new_converter = True
tflite_model = converter.convert()
open("gru3.tflite", "wb").write(tflite_model)
```
It results in following error on the device serial console
```
Only 1 subgraph is currently supported.
AllocateTensors() failed
```
If I remove the GRU layer or replace it with another one then the code works well.
It would be quite helpful if somebody knows the solution or an explanation for this following error report.

**Comment by ymodak** [comment]
The code looks incomplete, x_train and y_train are undefined.

**Comment by pramodjayram** [comment]
I have defined x_train and y_train before. I just haven't included in the code above. The code is working perfectly. The error occurs when I try to use the converted model on the ARM device.

**Comment by AlexVaith** [comment]
I get the exact same error, when I try to convert a model with lstm layers into tf lite and use post training optimization in form of: 
```
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = custom_generator
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,
                                      tf.lite.OpsSet.SELECT_TF_OPS]
```
I get this error:
```
RuntimeError: Only models with a single subgraph are supported, model had 5 subgraphs
```
When I do not use optimizations, it works. 
I am using tf 2.1.0 and tf-nightly version from 10.02.2020

**Comment by pramodjayram** [comment]
Is it possible to share the code?

**Comment by miaout17** [comment]
> I switched to the latest version of tf 2.1 and added the above lines. It perfectly created the tflite file.
The `experimental_new_converter` attribute only work on TF 2.1 and above. When doing this in 2.0 it doesn't change anything. 

> But when I use the GRU model on the board, I get an error message on the serial console of the board.
```
Only 1 subgraph is currently supported.
AllocateTensors() failed
```

It seems you're running the [microcontroller version of TFLite](https://www.tensorflow.org/lite/microcontrollers). At this moment it only support a subset of TFLite features, and control flow isn't supported yet. 

At this moment it's working as intended. @petewarden do you have any comment about GRU support?

**Comment by amahendrakar** [comment]
@pramodjayram,
Is this still an issue?

I was able to run the code with TF v2.4.1, without any errors. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/eb4e7fbe3b73e7290c64c768febaab54/36219.ipynb). Thanks!

**Comment by expeon07** [comment]
Hi, anybody else experiencing the same problem? I have the following error when trying to run my TFLite micro model on an ESP32
`Only 1 subgraph is currently supported.
AllocateTensors() failed`
My model is a 3-layer LSTM.
