### ISSUE TITLE
tensor flow instlaling error

### ISSUE THREAD

**Issue by jedrendelima** [tensorflow/tensorflow#36223]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 2.0
- Python version: 3.7.6
- Installed using virtualenv? pip? conda?: conda
- CUDA/cuDNN version: 10.1
- GPU model and memory: Nvidia GEFORCE GTX 1050

**Describe the problem**
Im trying to demo image detection in darkflow and it lead to this error

**Provide the exact sequence of commands / steps that you executed before running into the problem**:
(darkflow-env) C:\Binod\Deep_Learning\Object_Detection\YOLO_Detection\darkflow-master>python flow --model cfg --load bin\yolov2.weights --imgdir sample_dog --gpu 0.7
Traceback (most recent call last):
  File "flow", line 4, in <module>
    from darkflow.cli import cliHandler
  File "C:\Binod\Deep_Learning\Object_Detection\YOLO_Detection\darkflow-master\darkflow\cli.py", line 3, in <module>
    from .net.build import TFNet
  File "C:\Binod\Deep_Learning\Object_Detection\YOLO_Detection\darkflow-master\darkflow\net\build.py", line 1, in <module>
    import tensorflow as tf
  File "C:\darkflow\lib\site-packages\tensorflow\__init__.py", line 101, in <module>
    from tensorflow_core import *
  File "C:\darkflow\lib\site-packages\tensorflow_core\__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\darkflow\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\darkflow\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "C:\darkflow\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\darkflow\lib\site-packages\tensorflow_core\python\__init__.py", line 47, in <module>
    import numpy as np
  File "C:\darkflow\lib\site-packages\numpy\__init__.py", line 140, in <module>
    from . import _distributor_init
  File "C:\darkflow\lib\site-packages\numpy\_distributor_init.py", line 34, in <module>
    from . import _mklinit
ImportError: DLL load failed: The specified module could not be found.

**Comment by mihaimaruseac** [comment]
https://github.com/tensorflow/tensorflow/issues/36167#issuecomment-577886156

#36167 #36151 #36138 #36054 #36045 #36020 #36003 #35988 #35903 #35880 #35865 #35805 #35789 #35773 #35772 #35767 #35766 #35749 #35721 #35618 #35204

**Comment by mihaimaruseac** [comment]
Closing as duplicate
