### ISSUE TITLE
SpeechRecognition android example

### ISSUE THREAD

**Issue by B0yma** [tensorflow/tensorflow#36234]
**System information**
- OS Platform - macOS mojave:
- TensorFlow version - master

**Failure details**
im trying to build example from tensorflow/tensorflow/examples/speech_commands/
so i save model by freeze.py and get savedModel then i build android app from tensorflow/tensorflow/examples/android/
so my quesion is how to use savedModel in mobile in this example?

another question is how to convert savedModel to Tflite?

**Command used to run the converter**

```
import tensorflow as tf

converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir)
tflite_model = converter.convert()
open("converted_model.tflite", "wb").write(tflite_model)
```

this code produce some errors

**Comment by ravikyram** [comment]
@B0yma 
Can you please go through this [link](https://www.tensorflow.org/lite/guide/ops_select), [link2 ](https://www.tensorflow.org/lite/guide/android) and see if it helps you. Thanks!

**Comment by B0yma** [comment]
> @B0yma
> Can you please go through this [link](https://www.tensorflow.org/lite/guide/ops_select), [link2 ](https://www.tensorflow.org/lite/guide/android) and see if it helps you. Thanks!

from the 1st link:

```
import tensorflow as tf

converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir)
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,
                                       tf.lite.OpsSet.SELECT_TF_OPS]
tflite_model = converter.convert()
open("converted_model.tflite", "wb").write(tflite_model)
```

after above code I get error :
```
python tensorflow/examples/speech_commands/freezemobile.py
2020-01-29 21:15:58.919574: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7f9db96ebfe0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-01-29 21:15:58.919603: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
WARNING:tensorflow:From /usr/local/lib/python2.7/site-packages/tensorflow_core/lite/python/convert_saved_model.py:60: load (from tensorflow.python.saved_model.loader_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.loader.load or tf.compat.v1.saved_model.load. There will be a new function for importing SavedModels in Tensorflow 2.0.
Traceback (most recent call last):
  File "tensorflow/examples/speech_commands/freezemobile.py", line 3, in <module>
    converter = tf.lite.TFLiteConverter.from_saved_model("/tmp")
  File "/usr/local/lib/python2.7/site-packages/tensorflow_core/lite/python/lite.py", line 762, in from_saved_model
    output_arrays, tag_set, signature_key)
  File "/usr/local/lib/python2.7/site-packages/tensorflow_core/lite/python/convert_saved_model.py", line 187, in freeze_saved_model
    meta_graph = get_meta_graph_def(saved_model_dir, tag_set)
  File "/usr/local/lib/python2.7/site-packages/tensorflow_core/lite/python/convert_saved_model.py", line 60, in get_meta_graph_def
    return loader.load(sess, tag_set, saved_model_dir)
  File "/usr/local/lib/python2.7/site-packages/tensorflow_core/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/tensorflow_core/python/saved_model/loader_impl.py", line 269, in load
    return loader.load(sess, tags, import_scope, **saver_kwargs)
  File "/usr/local/lib/python2.7/site-packages/tensorflow_core/python/saved_model/loader_impl.py", line 422, in load
    **saver_kwargs)
  File "/usr/local/lib/python2.7/site-packages/tensorflow_core/python/saved_model/loader_impl.py", line 349, in load_graph
    meta_graph_def = self.get_meta_graph_def_from_tags(tags)
  File "/usr/local/lib/python2.7/site-packages/tensorflow_core/python/saved_model/loader_impl.py", line 327, in get_meta_graph_def_from_tags
    "\navailable_tags: " + str(available_tags))
RuntimeError: MetaGraphDef associated with tags set(['serve']) could not be found in SavedModel. To inspect available tag-sets in the SavedModel, please use the SavedModel CLI: `saved_model_cli`
available_tags: [set([])]
```

and after this code:
```
tflite_convert \
  --output_file=/tmp/foo.tflite \
  --graph_def_file=/tmp/foo.pb \
  --input_arrays=input \
  --output_arrays=MobilenetV1/Predictions/Reshape_1 \
  --target_ops=TFLITE_BUILTINS,SELECT_TF_OPS
```

get error:
```
2020-01-29 21:20:13.917241: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fb909751660 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-01-29 21:20:13.917270: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Traceback (most recent call last):
  File "/usr/local/bin/tflite_convert", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/tensorflow_core/lite/python/tflite_convert.py", line 515, in main
    app.run(main=run_main, argv=sys.argv[:1])
  File "/usr/local/lib/python2.7/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python2.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python2.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/usr/local/lib/python2.7/site-packages/tensorflow_core/lite/python/tflite_convert.py", line 511, in run_main
    _convert_tf1_model(tflite_flags)
  File "/usr/local/lib/python2.7/site-packages/tensorflow_core/lite/python/tflite_convert.py", line 124, in _convert_tf1_model
    converter = _get_toco_converter(flags)
  File "/usr/local/lib/python2.7/site-packages/tensorflow_core/lite/python/tflite_convert.py", line 111, in _get_toco_converter
    return converter_fn(**converter_kwargs)
  File "/usr/local/lib/python2.7/site-packages/tensorflow_core/lite/python/lite.py", line 705, in from_frozen_graph
    sess.graph, input_arrays)
  File "/usr/local/lib/python2.7/site-packages/tensorflow_core/lite/python/util.py", line 122, in get_tensors_from_tensor_names
    ",".join(invalid_tensors)))
ValueError: Invalid tensors 'input' were found.
```

**Comment by ymodak** [comment]
Your input_array argument is not correct. You may want to use tensorboard and visualize what your inputs look like.
Another approach can be to try https://github.com/tensorflow/examples/tree/master/lite/examples/speech_commands/android#tensorflow-lite-speech-command-recognition-android-demo
