### ISSUE TITLE
TFLite FP16 network Fully connected layer failing on gpu in android

### ISSUE THREAD

**Issue by jkparuchuri** [tensorflow/tensorflow#36270]
Using tensorflow 2.1 on both python as well as android. Quantized the model to fp16 in python and successfully run inference tests with python interpretor on ubuntu/mac.

But when I deployed the same network on android edge device with tflite java 2.1 pre-built and enabled gpu delegate, its failing with below error. 

tensorflow/lite/kernels/fully_connected.cc:105 filter->type != kTfLiteFloat32 (10 != 1)
    Node number 187 (FULLY_CONNECTED) failed to prepare.
    
    tensorflow/lite/kernels/conv.cc:272 bias->type != input_type (1
        at org.tensorflow.lite.NativeInterpreterWrapper.applyDelegate(Native Method)
        at org.tensorflow.lite.NativeInterpreterWrapper.applyDelegates(NativeInterpreterWrapper.java:336)
        at org.tensorflow.lite.NativeInterpreterWrapper.init(NativeInterpreterWrapper.java:82)
        at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:48)
        at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:175)

**Comment by amahendrakar** [comment]
@jkparuchuri,
Is this still an issue?

Could you please update TensorFlow to the latest stable version v2.4.1 and check if you are facing the same error. Thanks!

**Comment by madhavarora2002** [comment]
Hi @amahendrakar , Similar issue being faced.
The gpu is not working with movenet on android giving an on device fps of 20 instead of 50 expected with movenet lightning.
Issue can be seen by simply running the official app: https://github.com/tensorflow/examples/tree/master/lite/examples/pose_estimation/android
