### ISSUE TITLE
Keras: Unable to load SavedModel that includes tf.keras.backend.not_equal call

### ISSUE THREAD

**Issue by gustavgransbo** [tensorflow/tensorflow#36280]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Linux Ubuntu 18.04**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: **No**
- TensorFlow installed from (source or binary): **binary**
- TensorFlow version (use command below): **2.1.0-rc2**
- Python version: **3.7.4**

**Describe the current behavior**
Loading a Keras model including a call to `tf.keras.backend.not_equal` gives an error:
`ValueError: Could not find matching function to call loaded from the SavedModel`.

Works fine on 2.0.0.

**Describe the expected behavior**
It should be possible to load a model that includes a call to `tf.keras.backend.not_equal`.

**Code to reproduce the issue**
``` python
import tensorflow as tf

inp = tf.keras.layers.Input((1,1))
mask = tf.keras.backend.not_equal(inp, 0)
gru = tf.keras.layers.GRU(1, name='my-output')(inp, mask=mask)

model = tf.keras.Model(inp, gru)

model.save('my-saved-model')
model2 = tf.keras.models.load_model('my-saved-model')
```

**Other info / logs**
The snippet above results in the following traceback:
```
Traceback (most recent call last):
  File "/home/gustavg/.PyCharm2019.3/config/scratches/scratch_90.py", line 10, in <module>
    model2 = tf.keras.models.load_model('my-saved-model')
  File "/home/gustavg/.virtualenvs/dq2/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/save.py", line 150, in load_model
    return saved_model_load.load(filepath, compile)
  File "/home/gustavg/.virtualenvs/dq2/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/saved_model/load.py", line 89, in load
    model = tf_load.load_internal(path, loader_cls=KerasObjectLoader)
  File "/home/gustavg/.virtualenvs/dq2/lib/python3.7/site-packages/tensorflow_core/python/saved_model/load.py", line 552, in load_internal
    export_dir)
  File "/home/gustavg/.virtualenvs/dq2/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/saved_model/load.py", line 119, in __init__
    self._finalize()
  File "/home/gustavg/.virtualenvs/dq2/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/saved_model/load.py", line 157, in _finalize
    created_layers={layer.name: layer for layer in node.layers})
  File "/home/gustavg/.virtualenvs/dq2/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/network.py", line 1903, in reconstruct_from_config
    process_node(layer, node_data)
  File "/home/gustavg/.virtualenvs/dq2/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/network.py", line 1851, in process_node
    output_tensors = layer(input_tensors, **kwargs)
  File "/home/gustavg/.virtualenvs/dq2/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 773, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "/home/gustavg/.virtualenvs/dq2/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/saved_model/utils.py", line 59, in return_outputs_and_add_losses
    outputs, losses = fn(inputs, *args, **kwargs)
  File "/home/gustavg/.virtualenvs/dq2/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 568, in __call__
    result = self._call(*args, **kwds)
  File "/home/gustavg/.virtualenvs/dq2/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 615, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/home/gustavg/.virtualenvs/dq2/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 497, in _initialize
    *args, **kwds))
  File "/home/gustavg/.virtualenvs/dq2/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 2389, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/home/gustavg/.virtualenvs/dq2/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 2703, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/home/gustavg/.virtualenvs/dq2/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 2593, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/home/gustavg/.virtualenvs/dq2/lib/python3.7/site-packages/tensorflow_core/python/framework/func_graph.py", line 978, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/gustavg/.virtualenvs/dq2/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 439, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/home/gustavg/.virtualenvs/dq2/lib/python3.7/site-packages/tensorflow_core/python/saved_model/function_deserialization.py", line 262, in restored_function_body
    "\n\n".join(signature_descriptions)))
ValueError: Could not find matching function to call loaded from the SavedModel. Got:
  Positional arguments (1 total):
    * Tensor("inputs:0", shape=(None, 1, 1), dtype=float32)
  Keyword arguments: {}

Expected these arguments to match one of the following 1 option(s):

Option 1:
  Positional arguments (1 total):
    * [TensorSpec(shape=(None, 1, 1), dtype=tf.float32, name='inputs/0')]
  Keyword arguments: {}
```

**Comment by Saduf2019** [comment]
@gustavgransbo Was able to reproduce the issue. Please find the [Gist](https://colab.research.google.com/gist/Saduf2019/4e7c6c479f6124be187dbda990df259c/untitled8.ipynb) here. Thanks!

**Comment by ymodak** [comment]
The code snippet executes successfully with latest tf nightly version '2.2.0-dev20200129'. Thanks!
