### ISSUE TITLE
ImportError: DLL load failed:

### ISSUE THREAD

**Issue by Mr-Bigworth** [tensorflow/tensorflow#36286]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution :win10
- TensorFlow installed from (source or binary):http://pypi.douban.com/simple
- TensorFlow version:2.1.0
- Python version:3.6.8
- Installed using virtualenv? pip? conda?:anaconda
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:10.1.152
- GPU model and memory:Geforce GTX 1060

**Describe the problem**

**after import tensorflow as tf **

**Any other info / logs**
Traceback (most recent call last):
  File "G:\anaconda\envs\basecopy\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "G:\anaconda\envs\basecopy\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "G:\anaconda\envs\basecopy\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "G:\anaconda\envs\basecopy\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "G:\anaconda\envs\basecopy\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: 找不到指定的模块。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:/pyexercise/pyexercise7(tensor).py", line 2, in <module>
    import tensorflow as tf
  File "G:\anaconda\envs\basecopy\lib\site-packages\tensorflow\__init__.py", line 101, in <module>
    from tensorflow_core import *
  File "G:\anaconda\envs\basecopy\lib\site-packages\tensorflow_core\__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "G:\anaconda\envs\basecopy\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "G:\anaconda\envs\basecopy\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "G:\anaconda\envs\basecopy\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "G:\anaconda\envs\basecopy\lib\site-packages\tensorflow_core\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "G:\anaconda\envs\basecopy\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "G:\anaconda\envs\basecopy\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "G:\anaconda\envs\basecopy\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "G:\anaconda\envs\basecopy\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "G:\anaconda\envs\basecopy\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "G:\anaconda\envs\basecopy\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: 找不到指定的模块。

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by mihaimaruseac** [comment]
Closing as duplicate.

https://github.com/tensorflow/tensorflow/issues/36167#issuecomment-577886156

#36167 #36151 #36138 #36054 #36045 #36020 #36003 #35988 #35903 #35880 #35865 #35805 #35789 #35773 #35772 #35767 #35766 #35749 #35721 #35618 #35204
