### ISSUE TITLE
I want to open spyder. Error show from . import (constants, error, message, context, ImportError: DLL load failed: The specified module could not be found. 

### ISSUE THREAD

**Issue by vimalkumarmdb** [tensorflow/tensorflow#36296]
C:\Users\bimalgupta>spyder
Traceback (most recent call last):
  File "C:\Anaconda3\Scripts\spyder-script.py", line 6, in <module>
    from spyder.app.start import main
  File "C:\Anaconda3\lib\site-packages\spyder\app\start.py", line 22, in <module>
    import zmq
  File "C:\Anaconda3\lib\site-packages\zmq\__init__.py", line 47, in <module>
    from zmq import backend
  File "C:\Anaconda3\lib\site-packages\zmq\backend\__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "C:\Anaconda3\lib\site-packages\zmq\utils\sixcerpt.py", line 34, in reraise
    raise value
  File "C:\Anaconda3\lib\site-packages\zmq\backend\__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "C:\Anaconda3\lib\site-packages\zmq\backend\select.py", line 27, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "C:\Anaconda3\lib\site-packages\zmq\backend\cython\__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: DLL load failed: The specified module could not be found.

kindly help me.

**Comment by gadagashwini** [comment]
@vimalkumarmdb, Please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose). Thanks

**Comment by gadagashwini** [comment]
@vimalkumarmdb, Please fill the issue template to analyze the issue. Thanks

**Comment by gadagashwini** [comment]
@vimalkumarmdb, From the error trace it looks like installation issue.
Please follow the steps mentioned in the [doc](https://www.tensorflow.org/install). Closing this issue as no activity. Thanks!
