### ISSUE TITLE
Error message is unclear when we failed to load tflite model.

### ISSUE THREAD

**Issue by w4-hyunseok** [tensorflow/tensorflow#36300]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 
   Darwin 19.2.0 
   Android Pixel2 API 29
- TensorFlow installed from (source or binary):
   binary (pip)
- TensorFlow version (or github SHA if from source):
   1.15.0

**Provide the text output from tflite_convert**
tflite_convert succeeded without any error. 
```
$ tflite_convert --saved_model_dir ./tts/exported/more-kss-spk10-tflite \
    --output_file ./tts/tflite/more-kss-spk10.tflite

...
WARNING:tensorflow:From /Users/hyunseok/.venv/py36/lib/python3.6/site-packages/tensorflow_core/lite/python/util.py:208: convert_variables_to_constants (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.convert_variables_to_constants`
W0129 17:08:51.578040 140734888230336 deprecation.py:323] From /Users/hyunseok/.venv/py36/lib/python3.6/site-packages/tensorflow_core/lite/python/util.py:208: convert_variables_to_constants (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.convert_variables_to_constants`
WARNING:tensorflow:From /Users/hyunseok/.venv/py36/lib/python3.6/site-packages/tensorflow_core/python/framework/graph_util_impl.py:277: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.extract_sub_graph`
W0129 17:08:51.578234 140734888230336 deprecation.py:323] From /Users/hyunseok/.venv/py36/lib/python3.6/site-packages/tensorflow_core/python/framework/graph_util_impl.py:277: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.extract_sub_graph`
INFO:tensorflow:Froze 198 variables.
I0129 17:08:53.582584 140734888230336 graph_util_impl.py:334] Froze 198 variables.
INFO:tensorflow:Converted 198 variables to const ops.
I0129 17:08:53.853986 140734888230336 graph_util_impl.py:394] Converted 198 variables to const ops.
WARNING:tensorflow:From /Users/hyunseok/.venv/py36/lib/python3.6/site-packages/tensorflow_core/lite/python/util.py:210: remove_training_nodes (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.remove_training_nodes`
W0129 17:11:05.991335 140734888230336 deprecation.py:323] From /Users/hyunseok/.venv/py36/lib/python3.6/site-packages/tensorflow_core/lite/python/util.py:210: remove_training_nodes (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.remove_training_nodes`
```

But when I tried to load this model on both my local machine and android, I got the below message. 
```
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    interpreter = tf.lite.Interpreter(model_path='more-kss-spk10.tflite')
  File "/Users/hyunseok/.venv/py36/lib/python3.6/site-packages/tensorflow_core/lite/python/interpreter.py", line 206, in __init__
    model_path))
ValueError: Tensor 2711 is a variable tensor with buffer. It's not supported now.
```
I can't guess the Tensor 2711. 
May I delete all get_variable or tf.Variable statements on my model?

**Comment by jvishnuvardhan** [comment]
@w4-hyunseok Can you please share a standalone code to reproduce the issue? Thanks!

**Comment by w4-hyunseok** [comment]
@jvishnuvardhan Thanks to reply. 
My execution code is below and I want to share our tflite file or saved_model if you want. 
If you give me an email address to get our tflite file or saved_model, I'll send them ASAP. 

```
#!/usr/bin/env python3
"""
Before run this, we need to prepare .tflite file.

The tflite file can be generated by `tflite_convert` tool.
For example, if you have saved model, run belows:

    $ tflite_convert --saved_model_dir <input saved model directory> \
        --output_file <output tflite file>

And then, run this with above output tflite file.
"""

import numpy as np
import tensorflow as tf

flags = tf.flags
flags.DEFINE_string('model_path', None, 'The input tflite model path.')
FLAGS = flags.FLAGS


def main(argv):
    del argv    # Unused

    # Load TFLite model and allocate tensors.
    tf.logging.info('Try to load %s', FLAGS.model_path)
    interpreter = tf.lite.Interpreter(model_path=FLAGS.model_path)
    tf.logging.info('Model loaded: %s', FLAGS.model_path)
    interpreter.allocate_tensors()

    # Get input and output tensors.
    input_details = interpreter.get_input_details()
    output_details = interpreter.get_output_details()
    print(input_details)
    print(output_details)


if __name__ == '__main__':
    flags.mark_flag_as_required('model_path')
    tf.app.run(main)
```

**Comment by jvishnuvardhan** [comment]
@w4-hyunseok Please share the link to saved_model and tf_lite model so that it is easy to share, if needed, with other developers. Thanks!

**Comment by jdduke** [comment]
@miaout17 is there a reason we're allowing conversion of this model, only to fail at runtime?

**Comment by w4-hyunseok** [comment]
@jvishnuvardhan I share the link to download both saved_model and tflite file. For convenience, I exported our model to .pbtxt. If you prefer .pb, please tell me again. Thank you. 
https://goto.wisefour.com/tfissue_3600.tar.gz

**Comment by tensorflowbutler** [comment]
It has been 21 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by w4-hyunseok** [comment]
I still have the same issue and I didn't get any feedback after I shared my model.

**Comment by miaout17** [comment]
Sorry for the delayed response, @w4-hyunseok 

First, your TensorFlow version seems very old (1.15.0). Could you try to upgrade to the newest version and try it again?

I tried to reproduce the issue with the [model](https://github.com/tensorflow/tensorflow/issues/36300#issuecomment-580559088) you uploaded, but I'm running into an irrelevant error:
```
KeyError: u'Generator/decoder1_14/attention_decoder/rnn/while/Identity_8'
```
Could you double check if you can reproduce the issue with the same model?

We are working on replacing the old TensorFlow Lite converter backend with a new one, and I think it has a great chance to solve this issue (because we completely reworked relevant code). To use it, just add `--experimental_new_converter` argument to the command line, like:
```
tflite_convert --experimental_new_converter \
    --saved_model_dir ./tts/exported/more-kss-spk10-tflite \
    --output_file ./tts/tflite/more-kss-spk10.tflite
```
However it only works in TensorFlow 2.1.0+, or tf-nightly pip. 

cc @renjie-liu @ashwinmurthy -- It seems a buffer is incorrectly attached to a variable tensor of an op generated by OpHints, but this was the old converter. I'm hoping the new converter can just solve this issue.

**Comment by w4-hyunseok** [comment]
Thanks to reply, @miaout17 

I checked the shared link again which md5 values are below:
```
e56c54a24b4c0967e8292e587ade68cc saved_model/saved_model.pbtxt
c7f2e8785625a13d0d7a9664e0b61467 saved_model/variables/variables.data-00000-of-00001
6205b5126e2ae6bcfa3dc136e2df9370  saved_model/variables/variables.index
```
And I got a same results again(I can't see any error messages on **my mac with tf 1.15.0**
```
tflite_convert --saved_model_dir ./tfissue_36300/saved_model --output_file ./temp.tflite
```

The transition from tf 1.15.0 to tf 2.1 needs more time because our model uses tf.contrib APIs and we need to succeed to train our model with tf 2.1.  When I just tried a new converter to our current tf 1.15 model, I got the below errors. (Just for a curious)
```
File "/Users/hyunseok/.venv/tf/lib/python3.6/site-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 56, in execute
   enable_mlir_converter)
Exception: <unknown>:0: error: Found malformed ophint regions: missing inputs or outputs
``` 
If you give any quick hint about the above message before I dig, it will be really helpful for me.

**Comment by renjie-liu** [comment]
Hi,

Indeed I can see some usage of ophint and seems the conversion failed because of the rnn state.

I think two options:

1) if you are using ophinted lstm (lite.experimental.nn.dynamic_rnn), please don't set initial state, and the new converter support is WIP. (so you need to disable new_experimental_converter)

2) if you are not using ophinted lstm, preferably, keras lstm, you can try  new_experimental_converter

Thanks

**Comment by w4-hyunseok** [comment]
Thank you. @renjie-liu 

Our case is #1. (We used ophinted lstm and we also set the initial state, unfortunately) 
I understand the current status of new_experiemental_converter. And I'll try to remove the initial state and succeed to train.

Does the tensorflow lite team have the roadmap to support 'initial state' in the future?

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
