### ISSUE TITLE
tensorboard installation issue 

### ISSUE THREAD

**Issue by kuppas** [tensorflow/tensorflow#36303]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution: Linux Ubuntu 16.04
- TensorFlow installed from (source or binary): terminal
- TensorFlow version: tensorflow                         2.1.0              
                                   tensorflow-estimator               2.1.0
- Python version: 3.6.7

**Describe the problem**
am done by following steps in this link https://www.tensorflow.org/tensorboard/get_started  but it gives an error message like that 

**Provide the exact sequence of commands / steps that you executed before running into the problem**

tensorboard --logdir logs/fit

**Any other info / logs**
2020-01-29 15:42:56.124384: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory
2020-01-29 15:42:56.124520: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory
2020-01-29 15:42:56.124541: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Traceback (most recent call last):
  File "/home/kuppa/anaconda3/bin/tensorboard", line 8, in <module>
    sys.exit(run_main())
  File "/home/kuppa/anaconda3/lib/python3.6/site-packages/tensorboard/main.py", line 59, in run_main
    default.get_plugins() + default.get_dynamic_plugins(),
  File "/home/kuppa/anaconda3/lib/python3.6/site-packages/tensorboard/default.py", line 115, in get_dynamic_plugins
    for entry_point in pkg_resources.iter_entry_points('tensorboard_plugins')
  File "/home/kuppa/anaconda3/lib/python3.6/site-packages/tensorboard/default.py", line 115, in <listcomp>
    for entry_point in pkg_resources.iter_entry_points('tensorboard_plugins')
  File "/home/kuppa/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2443, in load
    self.require(*args, **kwargs)
  File "/home/kuppa/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2466, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/kuppa/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 792, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (grpcio 1.16.1 (/home/kuppa/anaconda3/lib/python3.6/site-packages), Requirement.parse('grpcio>=1.24.3'))

**Comment by gadagashwini** [comment]
@kuppas, Just to verify, did you install GPU support Tensorflow? If so install TensorRT as well to get rid of this error. Please refer the similar issue [#35968](https://github.com/tensorflow/tensorflow/issues/35968#issuecomment-577327358). Thanks!

**Comment by kuppas** [comment]
I just verified GPU version is not installed and current TensorFlow details are
$ pip freeze | grep tensorflow
tensorflow==2.1.0
tensorflow-estimator==2.1.0

**Comment by gowthamkpr** [comment]
@kuppas Yes that example should be modified. I have modified that example and its running successfully. The problem is the grpcio version 1.16.1. I changed it to 1.24.3 and then I ran into an other problem which is shown [here](https://colab.research.google.com/gist/gowthamkpr/b8100d83e51a0a17424f41d6f02e4cbf/copy-of-get_started.ipynb) and if you uninstall tensorboard at the start, it should fix the error.

Please take a look at the final working version of the model [here](https://colab.research.google.com/gist/gowthamkpr/04d772b61745e60a12242c675446028c/get_started.ipynb).

Thanks for reporting.

**Comment by tensorflowbutler** [comment]
It has been 15 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by ymodak** [comment]
The example works successfully now. Tested with default colab TF version 2.4.1. Thanks!
