### ISSUE TITLE
Unable to convert DeeplabV3 - "xception_65" frozen graph to TFLite

### ISSUE THREAD

**Issue by aaguiar96** [tensorflow/tensorflow#36339]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 18.04
- TensorFlow installed from (source or binary): source
- TensorFlow version (or github SHA if from source): 1.13

**Command used to run the converter or code if you’re using the Python API**

```
#!/bin/bash

set -e
set -x

python3 models/research/deeplab/export_model.py \
  --logtostderr \
  --checkpoint_path="train/train_res/deeplav_v3_cityscapes_xception65_trunks_DS_AG-30/ckpt/model.ckpt-3000" \
  --export_path="train/train_res/deeplav_v3_cityscapes_xception65_trunks_DS_AG-30/frozen_inference_graph.pb" \
  --model_variant="xception_65" \
  --num_classes=2 \
  --atrous_rates=6 \
  --atrous_rates=12 \
  --atrous_rates=18 \
  --output_stride=4 \
  --decoder_output_stride=4 \
  --train_crop_size=312 \
  --train_crop_size=312 \
  --train_batch_size=1 \
  --fine_tune_batch_norm=False \
  --initialize_last_layer=False \
  --last_layers_contain_logits_only=False \
  --quantize_delay_step=0 \
  --dataset="trunks_seg"                                              

tflite_convert \
  --graph_def_file="train/train_res/deeplav_v3_cityscapes_xception65_trunks_DS_AG-30/frozen_inference_graph.pb" \
  --output_file="train/train_res/deeplav_v3_cityscapes_xception65_trunks_DS_AG-30/frozen_inference_graph.tflite" \
  --input_format=TENSORFLOW_GRAPHDEF  \
  --output_format=TFLITE \
  --inference_type=QUANTIZED_UINT8 \
  --mean_values=128 \
  --std_dev_values=128 \
  --input_arrays=ImageTensor \
  --output_arrays=SemanticPredictions \
  --input_shapes=1,312,312,3 \
  --allow_custom_ops
```

**The output from the converter invocation**

```
+ python3 models/research/deeplab/export_model.py --logtostderr --checkpoint_path=train/train_res/deeplav_v3_cityscapes_xception65_trunks_DS_AG-30/ckpt/model.ck
pt-3000 --export_path=train/train_res/deeplav_v3_cityscapes_xception65_trunks_DS_AG-30/frozen_inference_graph.pb --model_variant=xception_65 --num_classes=2 --a
trous_rates=6 --atrous_rates=12 --atrous_rates=18 --output_stride=4 --decoder_output_stride=4 --train_crop_size=312 --train_crop_size=312 --train_batch_size=1 -
-fine_tune_batch_norm=False --initialize_last_layer=False --last_layers_contain_logits_only=False --quantize_delay_step=0 --dataset=trunks_seg
INFO:tensorflow:Prepare to export model to: train/train_res/deeplav_v3_cityscapes_xception65_trunks_DS_AG-30/frozen_inference_graph.pb
INFO:tensorflow:Exported model performs single-scale inference.
WARNING:tensorflow:From /home/andre-criis/Source/coral-deeplearning-ros/detect/models/research/deeplab/core/feature_extractor.py:160: to_float (from tensorflow.
python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
WARNING:tensorflow:From /home/andre-criis/.local/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.p
ython.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From /home/andre-criis/.local/lib/python3.6/site-packages/tensorflow/python/tools/freeze_graph.py:127: checkpoint_exists (from tensorflow.pyt
hon.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
INFO:tensorflow:Restoring parameters from train/train_res/deeplav_v3_cityscapes_xception65_trunks_DS_AG-30/ckpt/model.ckpt-3000
WARNING:tensorflow:From /home/andre-criis/.local/lib/python3.6/site-packages/tensorflow/python/tools/freeze_graph.py:232: convert_variables_to_constants (from t
ensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.compat.v1.graph_util.convert_variables_to_constants
WARNING:tensorflow:From /home/andre-criis/.local/lib/python3.6/site-packages/tensorflow/python/framework/graph_util_impl.py:245: extract_sub_graph (from tensorf
low.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.compat.v1.graph_util.extract_sub_graph
INFO:tensorflow:Froze 732 variables.
INFO:tensorflow:Converted 732 variables to const ops.
+ tflite_convert --graph_def_file=train/train_res/deeplav_v3_cityscapes_xception65_trunks_DS_AG-30/frozen_inference_graph.pb --output_file=train/train_res/deepl
av_v3_cityscapes_xception65_trunks_DS_AG-30/frozen_inference_graph.tflite --input_format=TENSORFLOW_GRAPHDEF --output_format=TFLITE --inference_type=QUANTIZED_U
INT8 --mean_values=128 --std_dev_values=128 --input_arrays=ImageTensor --output_arrays=SemanticPredictions --input_shapes=1,312,312,3 --allow_custom_ops
Traceback (most recent call last):
  File "/home/andre-criis/.local/bin/tflite_convert", line 8, in <module>
    sys.exit(main())
  File "/home/andre-criis/.local/lib/python3.6/site-packages/tensorflow/lite/python/tflite_convert.py", line 442, in main
    app.run(main=run_main, argv=sys.argv[:1])
  File "/home/andre-criis/.local/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/home/andre-criis/.local/lib/python3.6/site-packages/tensorflow/lite/python/tflite_convert.py", line 438, in run_main
    _convert_model(tflite_flags)
  File "/home/andre-criis/.local/lib/python3.6/site-packages/tensorflow/lite/python/tflite_convert.py", line 191, in _convert_model
    output_data = converter.convert()
  File "/home/andre-criis/.local/lib/python3.6/site-packages/tensorflow/lite/python/lite.py", line 455, in convert
    **converter_kwargs)
  File "/home/andre-criis/.local/lib/python3.6/site-packages/tensorflow/lite/python/convert.py", line 442, in toco_convert_impl
    input_data.SerializeToString())
  File "/home/andre-criis/.local/lib/python3.6/site-packages/tensorflow/lite/python/convert.py", line 205, in toco_convert_protos
    "TOCO failed. See console for info.\n%s\n%s\n" % (stdout, stderr))
tensorflow.lite.python.convert.ConverterError: TOCO failed. See console for info.
2020-01-30 15:30:08.786078: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 1898 operators, 3080 arrays (0 quantized)
2020-01-30 15:30:08.866046: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After Removing unused ops pass 1: 1888 operators, 3061 arrays (0 quantized)
2020-01-30 15:30:08.974668: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 1888 operators, 3061 arrays (0 quantized)
2020-01-30 15:30:09.328460: F tensorflow/lite/toco/graph_transformations/propagate_fixed_sizes.cc:625] Check failed: input_shape.dims().size() == op->size.size() (4 vs. 3)
Aborted (core dumped)
```

**Link to the saved GraphDef**

```
https://drive.google.com/file/d/1Cvb2LDUHlsSYKds0gev2wDWLdSVJZavi/view?usp=sharing
```

Thanks in advance.

**Comment by ymodak** [comment]
You may refer #23747
