### ISSUE TITLE
Unable to run unit tests on util_nest

### ISSUE THREAD

**Issue by punndcoder28** [tensorflow/tensorflow#36382]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS 10.15.2
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Source
- TensorFlow version: 2.0
- Python version: 3.7.3
- Installed using virtualenv? pip? conda?: 
- Bazel version (if compiling from source): 1.2.1
- GCC/Compiler version (if compiling from source): 4 (gotten from the command gcc -dumpversion | cut -f1 -d.)
- CUDA/cuDNN version: None
- GPU model and memory: Intel Iris Plus Graphics 640 1.5GB

**Describe the problem**
Unable to run bazel tests using the command `bazel test //tensorflow/python:util_nest_test`.
**Provide the exact sequence of commands / steps that you executed before running into the problem**
I built tensorflow from the source by doing the following in sequence:
1. Installed the tensorflow pip packages as stated in the documentation [here](https://www.tensorflow.org/install/source)
2. Ran `./configure`command (with a success message which I will be posting in the logs).
3. Ran `bazel build` and was shown a success message.
4. Ran `bazel test //tensorflow/python:util_nest_test` and it got terminated with an error message
```
ERROR: /Users/puneethk/Desktop/Projects/Open-Source/tensorflow/tensorflow/core/util/BUILD:338:1: Executing genrule //tensorflow/core/util:version_info_gen failed (Exit 1)
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_puneethk/4c7f735167707afd63484e296f46e040/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/tools/git/gen_git_source.runfiles/org_tensorflow/tensorflow/tools/git/gen_git_source.py", line 340, in <module>
    generate(args.generate, args.git_tag_override)
  File "/private/var/tmp/_bazel_puneethk/4c7f735167707afd63484e296f46e040/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/tools/git/gen_git_source.runfiles/org_tensorflow/tensorflow/tools/git/gen_git_source.py", line 272, in generate
    git_version = get_git_version(data["path"], git_tag_override)
  File "/private/var/tmp/_bazel_puneethk/4c7f735167707afd63484e296f46e040/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/tools/git/gen_git_source.runfiles/org_tensorflow/tensorflow/tools/git/gen_git_source.py", line 172, in get_git_version
    str("--work-tree=" + six.ensure_str(git_base_path)), "describe",
AttributeError: 'module' object has no attribute 'ensure_str'
Target //tensorflow/python:util_nest_test failed to build
```

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

1. Output of running `./configure`:
```
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
You have bazel 1.2.1 installed.
Please specify the location of python. [Default is /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python]: 


Found possible Python library paths:
  /Library/Python/2.7/site-packages
Please input the desired Python library path to use.  Default is [/Library/Python/2.7/site-packages]
/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/site-packages
Do you wish to build TensorFlow with XLA JIT support? [Y/n]: 
XLA JIT support will be enabled for TensorFlow.

Do you wish to build TensorFlow with OpenCL SYCL support? [y/N]: 
No OpenCL SYCL support will be enabled for TensorFlow.

Do you wish to build TensorFlow with ROCm support? [y/N]: 
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: 
No CUDA support will be enabled for TensorFlow.

Do you wish to download a fresh release of clang? (Experimental) [y/N]: 
Clang will not be downloaded.

Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native -Wno-sign-compare]: 


Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]: 
Not configuring the WORKSPACE for Android builds.

Do you wish to build TensorFlow with iOS support? [y/N]: 
No iOS support will be enabled for TensorFlow.

Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See .bazelrc for more details.
	--config=mkl         	# Build with MKL support.
	--config=monolithic  	# Config for mostly static monolithic build.
	--config=ngraph      	# Build with Intel nGraph support.
	--config=numa        	# Build with NUMA support.
	--config=dynamic_kernels	# (Experimental) Build kernels into separate shared objects.
	--config=v2          	# Build TensorFlow 2.x instead of 1.x.
Preconfigured Bazel build configs to DISABLE default on features:
	--config=noaws       	# Disable AWS S3 filesystem support.
	--config=nogcp       	# Disable GCP support.
	--config=nohdfs      	# Disable HDFS support.
	--config=nonccl      	# Disable NVIDIA NCCL support.
Configuration finished
```
2. Output after running `bazel build`:
```
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=130
INFO: Reading rc options for 'build' from /Users/puneethk/Desktop/Projects/Open-Source/tensorflow/.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --java_toolchain=//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=//third_party/toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --enable_platform_specific_config --config=v2
INFO: Reading rc options for 'build' from /Users/puneethk/Desktop/Projects/Open-Source/tensorflow/.tf_configure.bazelrc:
  'build' options: --host_force_python=PY2 --action_env PYTHON_BIN_PATH=/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python --action_env PYTHON_LIB_PATH=/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/site-packages --python_path=/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python --config=xla --action_env TF_CONFIGURE_IOS=0
INFO: Found applicable config definition build:v2 in file /Users/puneethk/Desktop/Projects/Open-Source/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:xla in file /Users/puneethk/Desktop/Projects/Open-Source/tensorflow/.bazelrc: --action_env=TF_ENABLE_XLA=1 --define=with_xla_support=true
INFO: Found applicable config definition build:xla in file /Users/puneethk/Desktop/Projects/Open-Source/tensorflow/.tf_configure.bazelrc: --define with_xla_support=true
INFO: Found applicable config definition build:macos in file /Users/puneethk/Desktop/Projects/Open-Source/tensorflow/.bazelrc: --copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --cxxopt=-std=c++14 --host_cxxopt=-std=c++14
WARNING: Usage: bazel build <options> <targets>.
Invoke `bazel help build` for full description of usage and options.
Your request is correct, but requested an empty set of targets. Nothing will be built.
INFO: Analyzed 0 targets (0 packages loaded, 0 targets configured).
INFO: Found 0 targets...
INFO: Deleting stale sandbox base /private/var/tmp/_bazel_puneethk/4c7f735167707afd63484e296f46e040/sandbox
INFO: Elapsed time: 1.643s, Critical Path: 0.03s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
```

If anyone has run into similar problem and fixed it, could you guide me resolve this?

**Comment by wisefool769** [comment]
I think six module version is too old. It needs to be at least 1.12. Your issue looks similar to [this](https://stackoverflow.com/questions/57251430/attributeerror-module-object-has-no-attribute-ensure-str).

**Comment by punndcoder28** [comment]
I'll look into this and then try the tests. Thanks.

**Comment by gadagashwini** [comment]
@punndcoder28, Did you try @wisefool769's workaround.

**Comment by punndcoder28** [comment]
I updated six to 1.14 and ran the tests. Still getting the same error. I'll try the tests on a different machine and let you know.

**Comment by punndcoder28** [comment]
I ran the tests on a different machine and the tests passed. Maybe it is an issue with MacOS and the  packages there? I couldn't figure it out but the tests run fine.

**Comment by gadagashwini** [comment]
@punndcoder28, Are you happy to close this issue, since its resolved. Thanks!

**Comment by punndcoder28** [comment]
Yes. I'll be closing this issue now. Thanks for the inputs.
