### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found.  OS Windows 10 , Tensorflow cpu version

### ISSUE THREAD

**Issue by MISSEY** [tensorflow/tensorflow#36407]
python -c "import tensorflow as tf;print(tf.reduce_sum(tf.random.normal([1000, 1000])))"
Traceback (most recent call last):
  File "C:\Users\skmishra\AppData\Local\Continuum\anaconda3\envs\FOODRECOGNITION\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\skmishra\AppData\Local\Continuum\anaconda3\envs\FOODRECOGNITION\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\skmishra\AppData\Local\Continuum\anaconda3\envs\FOODRECOGNITION\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\skmishra\AppData\Local\Continuum\anaconda3\envs\FOODRECOGNITION\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\skmishra\AppData\Local\Continuum\anaconda3\envs\FOODRECOGNITION\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\skmishra\AppData\Local\Continuum\anaconda3\envs\FOODRECOGNITION\lib\site-packages\tensorflow\__init__.py", line 101, in <module>
    from tensorflow_core import *
  File "C:\Users\skmishra\AppData\Local\Continuum\anaconda3\envs\FOODRECOGNITION\lib\site-packages\tensorflow_core\__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\skmishra\AppData\Local\Continuum\anaconda3\envs\FOODRECOGNITION\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\Users\skmishra\AppData\Local\Continuum\anaconda3\envs\FOODRECOGNITION\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "C:\Users\skmishra\AppData\Local\Continuum\anaconda3\envs\FOODRECOGNITION\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\skmishra\AppData\Local\Continuum\anaconda3\envs\FOODRECOGNITION\lib\site-packages\tensorflow_core\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\skmishra\AppData\Local\Continuum\anaconda3\envs\FOODRECOGNITION\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\skmishra\AppData\Local\Continuum\anaconda3\envs\FOODRECOGNITION\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\skmishra\AppData\Local\Continuum\anaconda3\envs\FOODRECOGNITION\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\skmishra\AppData\Local\Continuum\anaconda3\envs\FOODRECOGNITION\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\skmishra\AppData\Local\Continuum\anaconda3\envs\FOODRECOGNITION\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\skmishra\AppData\Local\Continuum\anaconda3\envs\FOODRECOGNITION\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by zkx741481546** [comment]
same problem with TF 2.1.0 and cuda10.0 or cuda10.1

**Comment by Swapnil99007** [comment]
Try these methods :
1. Try using Python 3.7
2. Try using 64 bit version of Python 3.7
3. Use "conda install tensorflow" in the specific environment.

**Comment by av8ramit** [comment]
What version of TensorFlow is this? Is this 2.1, nightly, are you building from source etc.?

**Comment by av8ramit** [comment]
Looks like [this comment](https://github.com/tensorflow/tensorflow/issues/36167#issuecomment-577886156) can help and is related?

**Comment by bmzhao** [comment]
Hi @MISSEY,

Did you install the Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017, and 2019?

According to the docs at https://www.tensorflow.org/install/pip,

> Install the Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017, and 2019. Starting with the TensorFlow 2.1.0 version, the msvcp140_1.dll file is required from this package (which may not be provided from older redistributable packages). The redistributable comes with Visual Studio 2019 but can be installed separately:

> Go to the [Microsoft Visual C++ downloads](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads),
Scroll down the page to the Visual Studio 2015, 2017 and 2019 section.
Download and install the Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019 for your platform.
Make sure [long paths](https://superuser.com/questions/1119883/windows-10-enable-ntfs-long-paths-policy-option-missing) are enabled on Windows.

> Install the [64-bit Python 3 release](https://www.python.org/downloads/windows/) for Windows (select pip as an optional feature).

Tensorflow 2.1.0 is compiled using MSVC 2019, which appears to require an additional DLL.

**Comment by zkx741481546** [comment]
I installed C++ 2019 and fixed this problem
