### ISSUE TITLE
Error while training object detection model

### ISSUE THREAD

**Issue by masoudnick** [tensorflow/tensorflow#36416]
Hi,
I am gonna to train a model for object detection with ssdlite_mobilenet_v2_coco (training images:30000,testing images:2000). But in almost 24000 itrations, I will be faced a problem.
What's the meaning of this error and how can i fix it?
### System information

- OS Platform and Distribution (Google Colab Ubuntu):

- TensorFlow version (1.15)

INFO:tensorflow:Finished training! Saving model to disk.
I0201 18:58:21.724251 140376424556416 learning.py:785] Finished training! Saving model to disk.
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/saver.py:963: remove_checkpoint (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to delete files with this prefix.
W0201 18:58:22.325520 140376424556416 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/saver.py:963: remove_checkpoint (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to delete files with this prefix.
/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/summary/writer/writer.py:386: UserWarning: Attempting to use a closed FileWriter. The operation will be a noop unless the FileWriter is explicitly reopened.
  warnings.warn("Attempting to use a closed FileWriter. "
Traceback (most recent call last):
  File "/content/gdrive/My Drive/Tensorflow/3_train_ssdlite.py", line 185, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/content/gdrive/My Drive/Tensorflow/3_train_ssdlite.py", line 181, in main
    graph_hook_fn=graph_rewriter_fn)
  File "/content/models/research/object_detection/legacy/trainer.py", line 417, in train
    saver=saver)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/contrib/slim/python/slim/learning.py", line 790, in train
    ignore_live_threads=ignore_live_threads)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/supervisor.py", line 839, in stop
    ignore_live_threads=ignore_live_threads)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/usr/local/lib/python3.6/dist-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/queue_runner_impl.py", line 257, in _run
    enqueue_callable()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1287, in _single_operation_run
    self._call_tf_sessionrun(None, {}, [], target_list, None)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.UnknownError: /content/gdrive/My Drive/Tensorflow/training_data/train.tfrecord; Input/output error
	 [[{{node IteratorGetNext}}]]

**Comment by amahendrakar** [comment]
@masoudnick,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here.

You can also share your Google Colab Gist. Please go to 'File' -> 'Save a copy as a GitHub Gist'  and share the link of the new window with us. Thanks!

**Comment by masoudnick** [comment]
@amahendrakar,
ok,here you are.
https://gist.github.com/masoudnick/9df13f4b4cb91ea4003a1c80b3a15192

**Comment by gowthamkpr** [comment]
@masoudnick As the error implies, this is an issue with reading your own dataset's tfrecords. You should first check the integrity of your TFRecords (e.g. see if you can extract the image data from tfrecord -> image tensor -> reading image out in numpy format to verify).

**Comment by gowthamkpr** [comment]
@masoudnick Is it still an issue or did you resolve it?
