### ISSUE TITLE
Error when importing tensorflow 2

### ISSUE THREAD

**Issue by VegardIversen** [tensorflow/tensorflow#36432]
Have pip installed tensorflow on my windows. 
When i try and import it, i get this error message.

Traceback (most recent call last):
  File "C:\Users\vegar\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\vegar\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\vegar\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\vegar\AppData\Local\Programs\Python\Python37\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\vegar\AppData\Local\Programs\Python\Python37\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: module not found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 6, in <module>
    import tensorflow as tf
  File "C:\Users\vegar\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\__init__.py", line 101, in <module>
    from tensorflow_core import *
  File "C:\Users\vegar\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\vegar\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\Users\vegar\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "C:\Users\vegar\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\vegar\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\vegar\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\vegar\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\vegar\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\vegar\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\vegar\AppData\Local\Programs\Python\Python37\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\vegar\AppData\Local\Programs\Python\Python37\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: module not found

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by amahendrakar** [comment]
@VegardIversen,
Could you please check [this](https://github.com/tensorflow/tensorflow/issues/36167#issuecomment-577886156) comment on a similar issue and let us know if it helps. Thanks!

**Comment by siAyush** [comment]
Hi @VegardIversen 
First install the Microsoft Visual C++ 
From here : [Microsoft Visual C++](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads)
And then try to install it again.
Thank you

**Comment by amahendrakar** [comment]
@VegardIversen,
Any updates regarding this issue? Thanks!

**Comment by VegardIversen** [comment]
@amahendrakar Worked when I installed MSVC 2019 redistributable.

**Comment by amahendrakar** [comment]
Closing the issue as it is resolved.

**Comment by bernardocortez** [comment]
I have the exact same problem but it didn't work just by installing VS code.... Any other suggestions @amahendrakar ?

Thanks

**Comment by VegardIversen** [comment]
Are you sure you have downloaded the correct version. Here is the link I used. https://support.microsoft.com/nb-no/help/2977003/the-latest-supported-visual-c-downloads

**Comment by bernardocortez** [comment]
I did! Only Visual Studio Code or the whole IDE package?

**Comment by Ozturk470** [comment]
Berna selamm bireyler oluyor ama ne anlamıyorum yardımcı olur musun

4 Nis 2020 Cmt 18:19 tarihinde bernardocortez <notifications@github.com>
şunu yazdı:

**Comment by VegardIversen** [comment]
Only this: x64: vc_redist.x64.exe (for 64 bit) via the link i sent

**Comment by bernardocortez** [comment]
Thanks! This solved the problem
