### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow_core.python'

### ISSUE THREAD

**Issue by mshmsh1234** [tensorflow/tensorflow#36441]
**System information**
- TensorFlow version: 2.1.0
- Python version: 3.7.4

Tensorflow is installed on the computer. When I try to import (import tensorflow as tf) I get this error

ModuleNotFoundError: No module named 'tensorflow_core.python'

What's causing this error? I've tried downgrading TF to below version 2 and still received the error.

**Comment by mihaimaruseac** [comment]
Please fill in the issue template. Also, please post output of `pip freeze` using ` ``` ` around computer generated messages (so the formatting is preserved)

**Comment by mshmsh1234** [comment]
This is the output of pip freeze

absl-py==0.9.0
astor==0.8.1
attrs==19.3.0
backcall==0.1.0
beautifulsoup4==4.8.2
bleach==3.1.0
blis==0.4.1
boto==2.49.0
boto3==1.11.9
botocore==1.14.9
bs4==0.0.1
bz2file==0.98
cachetools==4.0.0
catalogue==1.0.0
certifi==2019.11.28
cffi==1.13.2
chardet==3.0.4
colorama==0.4.3
conda==4.8.2
conda-package-handling==1.6.0
cryptography==2.8
cymem==2.0.3
Cython==0.29.14
decorator==4.4.1
defusedxml==0.6.0
docutils==0.15.2
entrypoints==0.3
gast==0.2.2
gensim==3.8.1
google-auth==1.11.0
google-auth-oauthlib==0.4.1
google-pasta==0.1.8
grpcio==1.26.0
h5py==2.10.0
idna==2.8
importlib-metadata==1.4.0
ipykernel==5.1.3
ipython==7.11.1
ipython-genutils==0.2.0
ipywidgets==7.5.1
jedi==0.15.2
Jinja2==2.10.3
jmespath==0.9.4
joblib==0.14.1
jsonschema==3.2.0
jupyter==1.0.0
jupyter-client==5.3.4
jupyter-console==6.1.0
jupyter-core==4.6.1
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
lxml==4.4.2
Markdown==3.1.1
MarkupSafe==1.1.1
menuinst==1.4.16
mistune==0.8.4
mkl-service==2.3.0
more-itertools==8.1.0
murmurhash==1.0.2
nbconvert==5.6.1
nbformat==5.0.4
nltk==3.4.5
notebook==6.0.3
numpy==1.17.5
oauthlib==3.1.0
opt-einsum==3.1.0
pandas==0.25.3
pandocfilters==1.4.2
parso==0.5.2
pickleshare==0.7.5
plac==1.1.3
preshed==3.0.2
prometheus-client==0.7.1
prompt-toolkit==3.0.2
protobuf==3.11.2
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycosat==0.6.3
pycparser==2.19
Pygments==2.5.2
pyOpenSSL==19.1.0
pyrsistent==0.15.7
PySocks==1.7.1
python-dateutil==2.8.1
pytz==2019.3
pywin32==225
pywinpty==0.5.7
pyzmq==18.1.1
qtconsole==4.6.0
requests==2.22.0
requests-oauthlib==1.3.0
rsa==4.0
ruamel-yaml==0.15.80
s3transfer==0.3.2
scikit-learn==0.22.1
scipy==1.4.1
Send2Trash==1.5.0
six==1.14.0
sklearn==0.0
smart-open==1.9.0
soupsieve==1.9.5
spacy==2.2.3
srsly==1.0.1
tensorflow==2.1.0
tensorflow-estimator==2.1.0
tensorflow-gpu-estimator==2.1.0
tensorflow-hub==0.7.0
termcolor==1.1.0
terminado==0.8.3
testpath==0.4.4
thinc==7.3.1
torch==1.3.1
tornado==6.0.3
tqdm==4.41.1
traitlets==4.3.3
urllib3==1.25.7
wasabi==0.6.0
wcwidth==0.1.8
webencodings==0.5.1
Werkzeug==0.16.0
widgetsnbextension==3.5.1
win-inet-pton==1.1.0
wincertstore==0.2
wrapt==1.11.2
zipp==2.0.1

**Comment by mshmsh1234** [comment]
Where can I find issue template

**Comment by mihaimaruseac** [comment]
The issue template is the stuff you see already there when you fill in the issue for the first time. You can also see it at https://github.com/tensorflow/tensorflow/tree/master/.github/ISSUE_TEMPLATE

You forgot to add ` ``` ` before and after the `pip freeze` dump above. I went ahead and added it for you, but please do use proper markdown in the future.

**Comment by mshmsh1234** [comment]
System information

Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): windows 10
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: no
TensorFlow installed from (source or binary): conda install?
TensorFlow version (use command below): 2.1.0
Python version: 3.7.4
Bazel version (if compiling from source): no
GCC/Compiler version (if compiling from source): no
CUDA/cuDNN version: no
GPU model and memory: intel 620
You can collect some of this information using our environment capture script You can also obtain the TensorFlow version with: 1. TF 1.0: python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)" 2. TF 2.0: python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"

Describe the current behavior: No module named 'tensorflow_core.python' 

Describe the expected behavior: imports without error

Code to reproduce the issue Provide a reproducible test case that is the bare minimum necessary to generate the problem.: import tensorflow

Other info / logs Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by mihaimaruseac** [comment]
Can you try the following?

```
import tensorflow_core as tfc
print(tfc.__path__)
```

**Comment by mshmsh1234** [comment]
Traceback (most recent call last):
  File "c:\users\myname\appdata\local\continuum\miniconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3319, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-12-9f0e6ea0081c>", line 1, in <module>
    import tensorflow_core as tfc
  File "C:\Users\myname\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\myname\AppData\Roaming\Python\Python37\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\Users\myname\AppData\Roaming\Python\Python37\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "c:\users\myname\appdata\local\continuum\miniconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'tensorflow_core.python'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\myname\appdata\local\continuum\miniconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2034, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'ModuleNotFoundError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\myname\appdata\local\continuum\miniconda3\lib\site-packages\IPython\core\ultratb.py", line 1151, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "c:\users\myname\appdata\local\continuum\miniconda3\lib\site-packages\IPython\core\ultratb.py", line 319, in wrapped
    return f(*args, **kwargs)
  File "c:\users\myname\appdata\local\continuum\miniconda3\lib\site-packages\IPython\core\ultratb.py", line 353, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "c:\users\myname\appdata\local\continuum\miniconda3\lib\inspect.py", line 1502, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
  File "c:\users\myname\appdata\local\continuum\miniconda3\lib\inspect.py", line 1460, in getframeinfo
    filename = getsourcefile(frame) or getfile(frame)
  File "c:\users\myname\appdata\local\continuum\miniconda3\lib\inspect.py", line 696, in getsourcefile
    if getattr(getmodule(object, filename), '__loader__', None) is not None:
  File "c:\users\myname\appdata\local\continuum\miniconda3\lib\inspect.py", line 733, in getmodule
    if ismodule(module) and hasattr(module, '__file__'):
  File "C:\Users\myname\AppData\Roaming\Python\Python37\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\Users\myname\AppData\Roaming\Python\Python37\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "c:\users\myname\appdata\local\continuum\miniconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\myname\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\myname\AppData\Roaming\Python\Python37\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\Users\myname\AppData\Roaming\Python\Python37\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "c:\users\myname\appdata\local\continuum\miniconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'tensorflow_core.python'

**Comment by mshmsh1234** [comment]
I get the same error as before with trying to import tf when I try what you posted

**Comment by StanHR** [comment]
Facing this same issue

**Comment by mihaimaruseac** [comment]
@mshmsh1234 please reformat your dump of error message to start and end with ` ``` ` so the formatting is preserved. As it is now, it is unreadable.

**Comment by StanHR** [comment]
I was trying to package a python app, which uses tensorflow, using PyInstaller. That's where I faced this same issue. I'm using tensorflow-cpu==1.15 

```(packer) C:\Users\harsh\Desktop\dtoxd-demo\dist\server>server.exe
Traceback (most recent call last):
  File "server.py", line 2, in <module>
  File "c:\users\harsh\anaconda3\envs\packer\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\tensorflow\__init__.py", line 99, in <module>
  File "c:\users\harsh\anaconda3\envs\packer\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\tensorflow_core\__init__.py", line 28, in <module>
  File "site-packages\tensorflow\__init__.py", line 50, in __getattr__
  File "site-packages\tensorflow\__init__.py", line 44, in _load
  File "importlib\__init__.py", line 126, in import_module
ImportError: No module named 'tensorflow_core.python'
[14776] Failed to execute script server```

**Comment by seung2jin** [comment]
I think you should downgrade tensorflow 1.14

**Comment by mihaimaruseac** [comment]
> I think you should downgrade tensorflow 1.14

This is a terrible advice. First, because TF 1.14 is no longer receiving new features and new security updates. Second, because it just hides the error under the rug.

**Comment by mshmsh1234** [comment]
Downgrading doesn't help to make TF usable/the error go away, regardless

**Comment by aayusharora** [comment]
Cant package tensorflow=1.15 with Pyinstaller because of the same error.

**Comment by mihaimaruseac** [comment]
@mshmsh1234 You said you tried to downgrade below TF 2.0 but your `pip freeze` output still lists TF 2.1.

Probably your environment is in a bad state. Can you please make sure you clean it? Using `virtualenv` is recommended.

**Comment by mihaimaruseac** [comment]
Please also say how the issue got fixed so other people searching for their issue and reaching here can use the same fix if their issue is similar.

**Comment by mshmsh1234** [comment]
> Please also say how the issue got fixed so other people searching for their issue and reaching here can use the same fix if their issue is similar.

I switched computers at work and this issue stop occurring on my new computer. Unfortunately can't offer a solution for others to replicate.

**Comment by StanHR** [comment]
@aayusharora  I had to switch to TF1.14 and that ended up creating a lot more problems because Ragged tensors were introduced in TF1.15. I then had to convert that model to be compatible to TF1.14

**Comment by mihaimaruseac** [comment]
[As said](https://github.com/tensorflow/tensorflow/issues/36441#issuecomment-583480775), switching to 1.14 was a terrible advice.

**Comment by StanHR** [comment]
I understand that very well. But sometimes, terrible option is better than no option at all.

**Comment by eclipse-du** [comment]
So it means TF 1.15 can not packaged by pyinstaller right now? i face the same problem, too.

**Comment by Ben-Epstein** [comment]
I'm running into the same issue with TF 2.2.0rc3
Are there any fixes for this?

**Comment by mihaimaruseac** [comment]
Locking conversation as original issue has been solved.

Please make sure `pip list` has `tensorflow`, `tensorboard` and `tensorflow_estimator` at the same (major,minor) version and no nightly packages installed. If that does not happen, please uninstall all packages and install again / install in a new virtualenv.

Note that:
* `tensorflow_core` only exists in 1.15, 2.0 and 2.1
* `tensorflow.contrib` only exists in 1.15
* tensorflow before 1.15 is no longer supported so it's recommended to not downgrade to it.
