### ISSUE TITLE
Predicting on custom model fails

### ISSUE THREAD

**Issue by moono** [tensorflow/tensorflow#36457]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): YES
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): bunary
- TensorFlow version (use command below): 2.1.0
- Python version: 3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.1 / 7.6.4.38-1
- GPU model and memory: RTX 2080 Ti 11GB

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
* While I was trying to train some model (keras subclassed model) and export that model for tensorflow serving, I encountered this error.
* So I tried to mimc same error with different but smaller code as below.
* error is that ... 
  * using tf.saved_model.save() with model that outputs image tensor (not scalar - it works) not working in tf 2.1, but works in tf 2.0
  * debug trace shows this error is related to distribute training, but I'm not using it.. or maybe I'm misleading it.
  * in official package's `training_v2_utils.py` and `_aggregate_predict_results(strategy, batch_outs, model)` function, something seems wrong on `model.output`

**Describe the expected behavior**
* should work on tf 2.1 too

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```python

import time
import numpy as np
import tensorflow as tf

import matplotlib.pyplot as plt

# https://www.tensorflow.org/tutorials/generative/dcgan

def set_gpu_memory_growth():
    gpus = tf.config.list_physical_devices('GPU')
    if gpus:
        try:
            # Currently, memory growth needs to be the same across GPUs
            for gpu in gpus:
                tf.config.experimental.set_memory_growth(gpu, True)
            logical_gpus = tf.config.list_logical_devices('GPU')
            print(len(gpus), "Physical GPUs,", len(logical_gpus), "Logical GPUs")
        except RuntimeError as e:
            # Memory growth must be set before GPUs have been initialized
            print(e)
    return


def generate_and_save_images(model, epoch, test_input):
    # Notice `training` is set to False.
    # This is so all layers run in inference mode (batchnorm).
    predictions = model(test_input, training=False)

    fig = plt.figure(figsize=(4, 4))

    for i in range(predictions.shape[0]):
        plt.subplot(4, 4, i + 1)
        plt.imshow(predictions[i, :, :, 0] * 127.5 + 127.5, cmap='gray')
        plt.axis('off')

    plt.savefig('./results/dcgan/image_at_epoch_{:04d}.png'.format(epoch))
    plt.close(fig)
    return


class Dense(tf.keras.layers.Layer):
    def __init__(self, units, **kwargs):
        super(Dense, self).__init__(**kwargs)
        self.units = units

    def build(self, input_shape):
        fin = np.prod(input_shape[1:])
        weight_shape = [fin, self.units]

        w_init = tf.random.normal(shape=weight_shape, mean=0.0, stddev=0.01)
        self.w = tf.Variable(w_init, name='w', trainable=True)

    def call(self, inputs, training=None, mask=None):
        x = tf.keras.layers.Flatten()(inputs)
        x = tf.matmul(x, self.w)
        return x

    def get_config(self):
        config = super(Dense, self).get_config()
        config.update({'units': self.units})
        return config


class LeakyReLU(tf.keras.layers.Layer):
    def __init__(self, **kwargs):
        super(LeakyReLU, self).__init__(**kwargs)
        self.alpha = 0.2

        self.act = tf.keras.layers.LeakyReLU(alpha=self.alpha)

    def call(self, inputs, training=None, mask=None):
        x = self.act(inputs)
        return x

    def get_config(self):
        config = super(LeakyReLU, self).get_config()
        config.update({'alpha': self.alpha})
        return config


class Generator(tf.keras.Model):
    def __init__(self, kernel, **kwargs):
        super(Generator, self).__init__(**kwargs)

        self.kernel = kernel

        self.dense0 = Dense(units=7 * 7 * 256)
        self.bn0 = tf.keras.layers.BatchNormalization()
        self.lrelu0 = LeakyReLU()

        self.convt1 = tf.keras.layers.Conv2DTranspose(128, self.kernel, strides=(1, 1), padding='same', use_bias=False)
        self.bn1 = tf.keras.layers.BatchNormalization()
        self.lrelu1 = LeakyReLU()

        self.convt2 = tf.keras.layers.Conv2DTranspose(64, self.kernel, strides=(2, 2), padding='same', use_bias=False)
        self.bn2 = tf.keras.layers.BatchNormalization()
        self.lrelu2 = LeakyReLU()

        self.convt3 = tf.keras.layers.Conv2DTranspose(1, self.kernel, strides=(2, 2), padding='same', use_bias=False,
                                                      activation='tanh')

    @tf.function
    def call(self, inputs, training=None, mask=None):
        z = inputs

        x = self.dense0(z)
        x = self.bn0(x, training=training)
        x = self.lrelu0(x)

        x = tf.reshape(x, shape=[-1, 7, 7, 256])

        x = self.convt1(x)
        x = self.bn1(x, training=training)
        x = self.lrelu1(x)

        x = self.convt2(x)
        x = self.bn2(x, training=training)
        x = self.lrelu2(x)

        x = self.convt3(x)
        return x

    def get_config(self):
        config = super(Generator, self).get_config()
        config.update({'kernel': self.kernel})
        return config

    def compute_output_shape(self, input_shape):
        print('[Generator] - compute_output_shape() input_shape: {}'.format(input_shape))
        return input_shape[0], 28, 28, 1

    @tf.function
    def serve(self, z):
        x = self.dense0(z)
        x = self.bn0(x, training=False)
        x = self.lrelu0(x)

        x = tf.reshape(x, shape=[-1, 7, 7, 256])

        x = self.convt1(x)
        x = self.bn1(x, training=False)
        x = self.lrelu1(x)

        x = self.convt2(x)
        x = self.bn2(x, training=False)
        x = self.lrelu2(x)

        x = self.convt3(x)
        return x


def make_discriminator_model():
    model = tf.keras.Sequential()
    model.add(tf.keras.layers.Conv2D(64, (5, 5), strides=(2, 2), padding='same', input_shape=[28, 28, 1]))
    model.add(tf.keras.layers.LeakyReLU())
    model.add(tf.keras.layers.Dropout(0.3))

    model.add(tf.keras.layers.Conv2D(128, (5, 5), strides=(2, 2), padding='same'))
    model.add(tf.keras.layers.LeakyReLU())
    model.add(tf.keras.layers.Dropout(0.3))

    model.add(tf.keras.layers.Flatten())
    model.add(tf.keras.layers.Dense(1))
    return model


def load_mnist(batch_size):
    (train_images, train_labels), (_, _) = tf.keras.datasets.mnist.load_data()
    train_images = train_images.reshape(train_images.shape[0], 28, 28, 1).astype('float32')
    train_images = (train_images - 127.5) / 127.5  # Normalize the images to [-1, 1]

    # Batch and shuffle the data
    train_dataset = tf.data.Dataset.from_tensor_slices(train_images).shuffle(60000).batch(batch_size)
    return train_dataset


def discriminator_loss(real_output, fake_output, cross_entropy):
    real_loss = cross_entropy(tf.ones_like(real_output), real_output)
    fake_loss = cross_entropy(tf.zeros_like(fake_output), fake_output)
    total_loss = real_loss + fake_loss
    return total_loss


def generator_loss(fake_output, cross_entropy):
    return cross_entropy(tf.ones_like(fake_output), fake_output)


# Notice the use of `tf.function`
# This annotation causes the function to be "compiled".
@tf.function
def train_step(images, batch_size, noise_dim, generator, discriminator,
               cross_entropy, generator_optimizer, discriminator_optimizer):
    noise = tf.random.normal([batch_size, noise_dim])

    with tf.GradientTape() as gen_tape, tf.GradientTape() as disc_tape:
        generated_images = generator(noise, training=True)

        real_output = discriminator(images, training=True)
        fake_output = discriminator(generated_images, training=True)

        gen_loss = generator_loss(fake_output, cross_entropy)
        disc_loss = discriminator_loss(real_output, fake_output, cross_entropy)

    gradients_of_generator = gen_tape.gradient(gen_loss, generator.trainable_variables)
    gradients_of_discriminator = disc_tape.gradient(disc_loss, discriminator.trainable_variables)

    generator_optimizer.apply_gradients(zip(gradients_of_generator, generator.trainable_variables))
    discriminator_optimizer.apply_gradients(zip(gradients_of_discriminator, discriminator.trainable_variables))


def train_loop():
    batch_size = 256
    epochs = 30
    noise_dim = 100
    num_examples_to_generate = 16

    dataset = load_mnist(batch_size)

    # create models
    generator = Generator(kernel=5)
    discriminator = make_discriminator_model()

    # loss
    cross_entropy = tf.keras.losses.BinaryCrossentropy(from_logits=True)

    # optimizer
    generator_optimizer = tf.keras.optimizers.Adam(1e-4)
    discriminator_optimizer = tf.keras.optimizers.Adam(1e-4)

    checkpoint_dir = './models/dcgan'
    checkpoint = tf.train.Checkpoint(generator_optimizer=generator_optimizer,
                                     discriminator_optimizer=discriminator_optimizer,
                                     generator=generator,
                                     discriminator=discriminator)
    manager = tf.train.CheckpointManager(checkpoint, checkpoint_dir, max_to_keep=2)

    # We will reuse this seed overtime (so it's easier)
    # to visualize progress in the animated GIF)
    seed = tf.random.normal([num_examples_to_generate, noise_dim])

    for epoch in range(epochs):
        start = time.time()

        for image_batch in dataset:
            train_step(image_batch, batch_size, noise_dim, generator, discriminator,
                       cross_entropy, generator_optimizer, discriminator_optimizer)

        # Save the model every 10 epochs
        if (epoch + 1) % 10 == 0:
            # Produce images for the GIF as we go
            generate_and_save_images(generator, epoch + 1, seed)
            manager.save(checkpoint_number=epoch + 1)

        print('Time for epoch {} is {} sec'.format(epoch + 1, time.time() - start))

    # Generate after the final epoch
    generate_and_save_images(generator, epochs, seed)
    return


def export_model():
    # restore generator model only
    noise_dim = 100
    generator = Generator(kernel=5, dynamic=True)
    test_x = tf.random.normal([1, noise_dim])
    _ = generator(test_x, training=False)

    checkpoint_dir = './models/dcgan'
    checkpoint = tf.train.Checkpoint(generator=generator)
    manager = tf.train.CheckpointManager(checkpoint, checkpoint_dir, max_to_keep=2)
    checkpoint.restore(manager.latest_checkpoint).expect_partial()
    if manager.latest_checkpoint:
        print('Restored from {}'.format(manager.latest_checkpoint))
        _ = generator.predict(test_x)
    else:
        raise ValueError()

    # export generator model
    export_dir = './models/dcgan/1'
    tf.saved_model.save(
        generator,
        export_dir,
        signatures=generator.serve.get_concrete_function(
            z=tf.TensorSpec(shape=[None, noise_dim], dtype=tf.float32)
        )
    )
    return


def main():
    set_gpu_memory_growth()

    train_loop()

    export_model()
    return


if __name__ == '__main__':
    main()

```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

/home/moono/anaconda3/envs/tf-2.1/bin/python /mnt/data_ssd/git-repos/tensorflow-serving-2.x/custom_training_dcgan.py
2020-02-04 17:07:07.806587: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer.so.6
2020-02-04 17:07:07.807381: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer_plugin.so.6
2020-02-04 17:07:08.226664: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-02-04 17:07:08.252985: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-02-04 17:07:08.253267: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce RTX 2080 Ti computeCapability: 7.5
coreClock: 1.575GHz coreCount: 68 deviceMemorySize: 10.75GiB deviceMemoryBandwidth: 573.69GiB/s
2020-02-04 17:07:08.253285: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-02-04 17:07:08.253303: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-02-04 17:07:08.254301: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-02-04 17:07:08.254520: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-02-04 17:07:08.255463: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-02-04 17:07:08.255982: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-02-04 17:07:08.256001: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-02-04 17:07:08.256046: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-02-04 17:07:08.256327: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-02-04 17:07:08.256572: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1697] Adding visible gpu devices: 0
2020-02-04 17:07:08.256776: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-02-04 17:07:08.277755: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3000000000 Hz
2020-02-04 17:07:08.278023: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55a541a20050 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-02-04 17:07:08.278034: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-02-04 17:07:08.343779: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-02-04 17:07:08.344115: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55a54215a3e0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-02-04 17:07:08.344127: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce RTX 2080 Ti, Compute Capability 7.5
2020-02-04 17:07:08.344226: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-02-04 17:07:08.344839: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce RTX 2080 Ti computeCapability: 7.5
coreClock: 1.575GHz coreCount: 68 deviceMemorySize: 10.75GiB deviceMemoryBandwidth: 573.69GiB/s
2020-02-04 17:07:08.344861: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-02-04 17:07:08.344868: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-02-04 17:07:08.344878: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-02-04 17:07:08.344884: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-02-04 17:07:08.344891: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-02-04 17:07:08.344898: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-02-04 17:07:08.344903: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-02-04 17:07:08.344935: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-02-04 17:07:08.345190: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-02-04 17:07:08.345429: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1697] Adding visible gpu devices: 0
2020-02-04 17:07:08.345473: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-02-04 17:07:08.509396: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1096] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-02-04 17:07:08.509447: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102]      0 
2020-02-04 17:07:08.509452: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] 0:   N 
2020-02-04 17:07:08.509580: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-02-04 17:07:08.509854: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-02-04 17:07:08.510101: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1241] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 9565 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:01:00.0, compute capability: 7.5)
1 Physical GPUs, 1 Logical GPUs
2020-02-04 17:07:10.728256: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-02-04 17:07:10.847845: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
Time for epoch 1 is 7.408124208450317 sec
Time for epoch 2 is 4.247774362564087 sec
Time for epoch 3 is 4.300286054611206 sec
Time for epoch 4 is 4.301387786865234 sec
Time for epoch 5 is 4.302702188491821 sec
Time for epoch 6 is 4.3085198402404785 sec
Time for epoch 7 is 4.314511060714722 sec
Time for epoch 8 is 4.3180766105651855 sec
Time for epoch 9 is 4.276162147521973 sec
Time for epoch 10 is 4.594261884689331 sec
Time for epoch 11 is 4.290403127670288 sec
Time for epoch 12 is 4.332635164260864 sec
Time for epoch 13 is 4.34122896194458 sec
Time for epoch 14 is 4.342823505401611 sec
Time for epoch 15 is 4.30718469619751 sec
Time for epoch 16 is 4.350044012069702 sec
Time for epoch 17 is 4.3491082191467285 sec
Time for epoch 18 is 4.352354049682617 sec
Time for epoch 19 is 4.318714618682861 sec
Time for epoch 20 is 4.648451089859009 sec
Time for epoch 21 is 4.324911117553711 sec
Time for epoch 22 is 4.33571720123291 sec
Time for epoch 23 is 4.367572069168091 sec
Time for epoch 24 is 4.363953351974487 sec
Time for epoch 25 is 4.342392683029175 sec
Time for epoch 26 is 4.374950647354126 sec
Time for epoch 27 is 4.375419616699219 sec
Time for epoch 28 is 4.3764965534210205 sec
Time for epoch 29 is 4.358669757843018 sec
Time for epoch 30 is 4.596313714981079 sec
Restored from ./models/dcgan/ckpt-30
[Generator] - compute_output_shape() input_shape: (None, 100)
Traceback (most recent call last):
  File "/mnt/data_ssd/git-repos/tensorflow-serving-2.x/custom_training_dcgan.py", line 322, in <module>
    main()
  File "/mnt/data_ssd/git-repos/tensorflow-serving-2.x/custom_training_dcgan.py", line 317, in main
    export_model()
  File "/mnt/data_ssd/git-repos/tensorflow-serving-2.x/custom_training_dcgan.py", line 296, in export_model
    _ = generator.predict(test_x)
  File "/home/moono/anaconda3/envs/tf-2.1/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 1013, in predict
    use_multiprocessing=use_multiprocessing)
  File "/home/moono/anaconda3/envs/tf-2.1/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 498, in predict
    workers=workers, use_multiprocessing=use_multiprocessing, **kwargs)
  File "/home/moono/anaconda3/envs/tf-2.1/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 475, in _model_iteration
    total_epochs=1)
  File "/home/moono/anaconda3/envs/tf-2.1/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 168, in run_one_epoch
    strategy, batch_outs, model)
  File "/home/moono/anaconda3/envs/tf-2.1/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 264, in _aggregate_predict_results
    nest.flatten(nested_outs))
  File "/home/moono/anaconda3/envs/tf-2.1/lib/python3.7/site-packages/tensorflow_core/python/keras/distribute/distributed_training_utils.py", line 1199, in concat_along_batch_dimension
    if isinstance(outputs[0], sparse_tensor.SparseTensor):
IndexError: list index out of range

Process finished with exit code 1

**Comment by amahendrakar** [comment]
Was able to reproduce the issue. Please find the Gist [here](https://colab.sandbox.google.com/gist/amahendrakar/3117af743b141fd4fa629dc130ab6143/36457.ipynb). Thanks!

**Comment by moono** [comment]
Forgot to mention one important thing.
To reproduce this issue, one needs to set `dynamic=True` before export the model.
As in sample code I provided,

```python
def export_model():
    # restore generator model only
    noise_dim = 100
    generator = Generator(kernel=5, dynamic=True)
```

**Comment by k-w-w** [comment]
When dynamic is set to True, it means the model is only able to run in eager mode (and thus incompatible with graphs). The SavedModel format tries to serialize the model in a graph, so this is fundamentally incompatible.

The error being raised here is actually related to `generator.predict(test_x)`.  (try calling this right after the generator and test_x are created). I've attached the error logs below. @qlzh727  Can you take a look and see if it's an error with the `_aggregate_predict_results`? If there's no issue, how can the error be improved?

```
<ipython-input-4-4f5b3ec7f8fa> in export_model()
    265     test_x = tf.random.normal([1, noise_dim])
    266     _ = generator(test_x, training=False)
--> 267     _ = generator.predict(test_x)
    268     checkpoint_dir = './models/dcgan'
    269     checkpoint = tf.train.Checkpoint(generator=generator)

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/training.py in predict(self, x, batch_size, verbose, steps, callbacks, max_queue_size, workers, use_multiprocessing)
   1011         max_queue_size=max_queue_size,
   1012         workers=workers,
-> 1013         use_multiprocessing=use_multiprocessing)
   1014 
   1015   def reset_metrics(self):

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/training_v2.py in predict(self, model, x, batch_size, verbose, steps, callbacks, max_queue_size, workers, use_multiprocessing, **kwargs)
    496         model, ModeKeys.PREDICT, x=x, batch_size=batch_size, verbose=verbose,
    497         steps=steps, callbacks=callbacks, max_queue_size=max_queue_size,
--> 498         workers=workers, use_multiprocessing=use_multiprocessing, **kwargs)
    499 
    500 

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/training_v2.py in _model_iteration(self, model, mode, x, y, batch_size, verbose, sample_weight, steps, callbacks, max_queue_size, workers, use_multiprocessing, **kwargs)
    473               mode=mode,
    474               training_context=training_context,
--> 475               total_epochs=1)
    476           cbks.make_logs(model, epoch_logs, result, mode)
    477 

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/training_v2.py in run_one_epoch(model, iterator, execution_function, dataset_size, batch_size, strategy, steps_per_epoch, num_samples, mode, training_context, total_epochs)
    166       else:
    167         batch_outs = training_v2_utils._aggregate_predict_results(
--> 168             strategy, batch_outs, model)
    169 
    170       if step == 0:

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/training_v2_utils.py in _aggregate_predict_results(strategy, batch_outs, model)
    262     nested_outs = batch_outs[i * num_replicas:i * num_replicas + num_replicas]
    263     per_output_result = dist_utils.concat_along_batch_dimension(
--> 264         nest.flatten(nested_outs))
    265 
    266     if need_batch_index_gather:

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/distribute/distributed_training_utils.py in concat_along_batch_dimension(outputs)
   1197 def concat_along_batch_dimension(outputs):
   1198   """Concats prediction outputs along the batch dimension."""
-> 1199   if isinstance(outputs[0], sparse_tensor.SparseTensor):
   1200     return sparse_ops.sparse_concat_v2(axis=0, sp_inputs=outputs)
   1201   if isinstance(outputs[0], ragged_tensor.RaggedTensor):

IndexError: list index out of range
```

**Comment by qlzh727** [comment]
Digging more into details, I think the issue is caused by how we build model input/output on a dynamic model. It is using the result of model.compute_output_shape to build a symbolic output, and incorrectly use nest.map_structure, which in this case expand a 4D shape into 4 outputs. The number of wrong outputs cause the error down the stream.

https://github.com/tensorflow/tensorflow/blob/af38219818b1b677277018468c089593965d8c24/tensorflow/python/keras/engine/base_layer.py#L2219

**Comment by qlzh727** [comment]
The walk around so far is to update your compute_output_shape method with the wrapper of tf.TensorShape(), so that the nest lib will not try to expand it. We will fix the issue on our side in the meantime.

```python
  def compute_output_shape(self, input_shape):
    print('[Generator] - compute_output_shape() input_shape: {}'.format(input_shape))
    return tf.TensorShape([input_shape[0], 28, 28, 1])
```

**Comment by moono** [comment]
Thank you for the reply!!
I'll try the workaround. And hope to see the fixes in next release.
