### ISSUE TITLE
import tensorflow (v2.1.0) fails

### ISSUE THREAD

**Issue by constructor-igor** [tensorflow/tensorflow#36486]
**System information**
- Windows 10
- TensorFlow installed from (pip install tensorflow):
- TensorFlow version: 2.1.0
- Python version: 3.7.1
- Installed using virtualenv:

**Describe the problem**
```import tensorflow as tf``` fails

```
(tf2) D:\@Temp\@Issues\2020-02-04-tf\tf2>python -c "import tensorflow as tf;print(tf.reduce_sum(tf.random.normal([1000, 1000])))"
Traceback (most recent call last):
  File "D:\@Temp\@Issues\2020-02-04-tf\tf2\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "D:\@Temp\@Issues\2020-02-04-tf\tf2\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "D:\@Temp\@Issues\2020-02-04-tf\tf2\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\igor-z\AppData\Local\Continuum\anaconda3\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\igor-z\AppData\Local\Continuum\anaconda3\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\@Temp\@Issues\2020-02-04-tf\tf2\lib\site-packages\tensorflow\__init__.py", line 101, in <module>
    from tensorflow_core import *
  File "D:\@Temp\@Issues\2020-02-04-tf\tf2\lib\site-packages\tensorflow_core\__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "D:\@Temp\@Issues\2020-02-04-tf\tf2\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "D:\@Temp\@Issues\2020-02-04-tf\tf2\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "C:\Users\igor-z\AppData\Local\Continuum\anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "D:\@Temp\@Issues\2020-02-04-tf\tf2\lib\site-packages\tensorflow_core\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "D:\@Temp\@Issues\2020-02-04-tf\tf2\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "D:\@Temp\@Issues\2020-02-04-tf\tf2\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "D:\@Temp\@Issues\2020-02-04-tf\tf2\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "D:\@Temp\@Issues\2020-02-04-tf\tf2\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\igor-z\AppData\Local\Continuum\anaconda3\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\igor-z\AppData\Local\Continuum\anaconda3\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

tf (v1.15.0) in other virtual environment shows next:
```
(tf1) D:\@Temp\@Issues\2020-02-04-tf\tf1>python
Python 3.7.1 (default, Dec 10 2018, 22:54:23) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
2020-02-05 15:31:28.406892: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_100.dll'; dlerror: cudart64_100.dll not found
2020-02-05 15:31:28.411004: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
>>> tf.__version__
'1.15.0'
>>>
```

**Comment by gadagashwini** [comment]
@constructor-igor, Suspecting that you have installed tensorflow-gpu 2.1 version. Please check and install `pip install tensorflow==2.1`. Thanks!

**Comment by constructor-igor** [comment]
@gadagashwini 
I checked and found next installed "tensorflow" packages:
```
six                  1.14.0
tensorboard          2.1.0
tensorflow           2.1.0
tensorflow-estimator 2.1.0
termcolor            1.1.0
```

**Comment by gadagashwini** [comment]
@constructor-igor,
Open ...\Lib\site-packages\tensorflow\python\_pywrap_tensorflow_internal.pyd use Dependency Walker, it will show you the 
DLL dependency tree, you will find which DLL cause the problem. You can then install the needed version, 
or add some path to system variable.
Dependency Walker link : http://www.dependencywalker.com/.
Thanks!

**Comment by constructor-igor** [comment]
@gadagashwini 
folder ...\Lib\site-packages\tensorflow doesn't contain any .pyd file.

![image](https://user-images.githubusercontent.com/1849690/74111438-14d9fb00-4b9d-11ea-8267-d63137f134ba.png)

I found .pyd files in ...\Lib\site-packages\tensorflow_core\python folder only.

![image](https://user-images.githubusercontent.com/1849690/74111460-510d5b80-4b9d-11ea-8bfb-2b3d7666913e.png)

Dependency Walker shows next (see below).
Please, could you explain what should be installed for TF2?

![image](https://user-images.githubusercontent.com/1849690/74111478-6bdfd000-4b9d-11ea-96df-1b05f47d7244.png)

**Comment by mihaimaruseac** [comment]
Closing as duplicate.

https://github.com/tensorflow/tensorflow/issues/36167#issuecomment-577886156

#36167 #36151 #36138 #36054 #36045 #36020 #36003 #35988 #35903 #35880 #35865 #35805 #35789 #35773 #35772 #35767 #35766 #35749 #35721 #35618 #35204

**Comment by constructor-igor** [comment]
**solution**:
download and install **Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019** package from 
https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

Windows 10 x64 requires **vc_redist.x64.exe**.
