### ISSUE TITLE
Error when converting my_frozen_graph.pb to .tflite for Speech Commands example app TF Speech

### ISSUE THREAD

**Issue by Kamanica** [tensorflow/tensorflow#36500]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (or github SHA if from source): Tensorflow 2.0.1

**Command used to run the converter or code if you’re using the Python API**
tflite_convert.py
```

# Copy and paste here the exact command
```
python tensorflow/lite/python/tflite_convert.py --enable_v1_converter --output_file=/tmp/foo.tflite --graph_def_file=/tmp/my_frozen_graph_anika_26000.pb --input_arrays=wav_data --output_arrays=labels_softmax --input_shapes=1,3920

**The output from the converter invocation**
```
Here is a list of operators for which you will need custom implementations: AudioSpectrogram, DecodeWav, Mfcc.

# Copy and paste the output here.
```
Traceback (most recent call last):
  File "tensorflow_core/lite/python/tflite_convert.py", line 598, in <module>
    main()
  File "tensorflow_core/lite/python/tflite_convert.py", line 594, in main
    app.run(main=run_main, argv=sys.argv[:1])
  File "C:\Anaconda3\envs\tf-gpu\lib\site-packages\tensorflow_core\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Anaconda3\envs\tf-gpu\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "C:\Anaconda3\envs\tf-gpu\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "tensorflow_core/lite/python/tflite_convert.py", line 580, in run_main
    _convert_tf1_model(tflite_flags)
  File "tensorflow_core/lite/python/tflite_convert.py", line 210, in _convert_tf1_model
    output_data = converter.convert()
  File "C:\Anaconda3\envs\tf-gpu\lib\site-packages\tensorflow_core\lite\python\lite.py", line 1007, in convert
    **converter_kwargs)
  File "C:\Anaconda3\envs\tf-gpu\lib\site-packages\tensorflow_core\lite\python\convert.py", line 457, in toco_convert_impl
    enable_mlir_converter=enable_mlir_converter)
  File "C:\Anaconda3\envs\tf-gpu\lib\site-packages\tensorflow_core\lite\python\convert.py", line 203, in toco_convert_protos
    raise ConverterError("See console for info.\n%s\n%s\n" % (stdout, stderr))
tensorflow.lite.python.convert.ConverterError: See console for info.
2020-02-05 20:57:48.272648: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-02-05 20:57:48.273069: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2020-02-05 20:57:49.877294: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: DecodeWav
2020-02-05 20:57:49.877602: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: AudioSpectrogram
2020-02-05 20:57:49.877911: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Mfcc
2020-02-05 20:57:49.883065: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 24 operators, 36 arrays (0 quantized)
2020-02-05 20:57:49.883549: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 24 operators, 36 arrays (0 quantized)
2020-02-05 20:57:49.884589: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 1: 11 operators, 22 arrays (0 quantized)
2020-02-05 20:57:49.887081: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 2: 10 operators, 21 arrays (0 quantized)
2020-02-05 20:57:49.887552: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 3: 9 operators, 19 arrays (0 quantized)
2020-02-05 20:57:49.888012: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Group bidirectional sequence lstm/rnn: 9 operators, 19 arrays (0 quantized)
2020-02-05 20:57:49.888461: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before dequantization graph transformations: 9 operators, 19 arrays (0 quantized)
2020-02-05 20:57:49.888891: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Identify nearest upsample.: 9 operators, 19 arrays (0 quantized)
2020-02-05 20:57:49.889328: I tensorflow/lite/toco/allocate_transient_arrays.cc:345] Total transient array allocated size: 0 bytes, theoretical optimal value: 0 bytes.
2020-02-05 20:57:49.889717: I tensorflow/lite/toco/toco_tooling.cc:471] Number of parameters: 926865
2020-02-05 20:57:49.890164: E tensorflow/lite/toco/toco_tooling.cc:498] We are continually in the process of adding support to TensorFlow Lite for more ops. It would be helpful if you could inform us of how this conversion went by opening a github issue at https://github.com/tensorflow/tensorflow/issues/new?template=40-tflite-op-request.md
 and pasting the following:

Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: CONV_2D, FULLY_CONNECTED, MAX_POOL_2D, RESHAPE, SOFTMAX. Here is a list of operators for which you will need custom implementations: AudioSpectrogram, DecodeWav, Mfcc.
Traceback (most recent call last):
  File "c:\anaconda3\envs\tf-gpu\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\anaconda3\envs\tf-gpu\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda3\envs\tf-gpu\Scripts\toco_from_protos.exe\__main__.py", line 7, in <module>
  File "c:\anaconda3\envs\tf-gpu\lib\site-packages\tensorflow_core\lite\toco\python\toco_from_protos.py", line 93, in main
    app.run(main=execute, argv=[sys.argv[0]] + unparsed)
  File "c:\anaconda3\envs\tf-gpu\lib\site-packages\tensorflow_core\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "c:\anaconda3\envs\tf-gpu\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "c:\anaconda3\envs\tf-gpu\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "c:\anaconda3\envs\tf-gpu\lib\site-packages\tensorflow_core\lite\toco\python\toco_from_protos.py", line 56, in execute
    enable_mlir_converter)
Exception: We are continually in the process of adding support to TensorFlow Lite for more ops. It would be helpful if you could inform us of how this conversion went by opening a github issue at https://github.com/tensorflow/tensorflow/issues/new?template=40-tflite-op-request.md
 and pasting the following:

Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: CONV_2D, FULLY_CONNECTED, MAX_POOL_2D, RESHAPE, SOFTMAX. Here is a list of operators for which you will need custom implementations: AudioSpectrogram, DecodeWav, Mfcc.

**Also, please include a link to the saved model or GraphDef**

```
# Put link here or attach to the issue.
```

**Failure details**
If the conversion is successful, but the generated model is wrong,
state what is wrong:
- Producing wrong results and/or decrease in accuracy
- Producing correct results, but the model is slower than expected (model generated from old converter)
When I try to convert without '--target_ops=TFLITE_BUILTINS,SELECT_TF_OPS', I get the error saying Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. These are: AudioSpectrogram, DecodeWav, Mfcc.
When I use '--target_ops=TFLITE_BUILTINS,SELECT_TF_OPS', I do get a .tflite file, but that file fails to run on Andriod, and gives the error message: "Unexpected failure when preparing tensor allocations: Regular TensorFlow ops are not supported by this interpreter"

**Any other info / logs**
Complete Error when running a .tflite file (that was created using the SELECT_TF_OPS option) on Andriod: 
error running on android:
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.tensorflow.lite.examples.speech/org.tensorflow.lite.examples.speech.SpeechActivity}: java.lang.RuntimeException: java.lang.IllegalStateException: Internal error: Unexpected failure when preparing tensor allocations: Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference.

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by vihari1729** [comment]
Try this
tflite_convert \
--output_file=/output.tflite \
--graph_def_file /path/to/my_frozen_graph.pb \
--input_arrays decoded_sample_data,decoded_sample_data:1 \
--output_arrays labels_softmax \
--allow_custom_ops

**Comment by Kamanica** [comment]
Thanks! I will try it out soon and let you know.

**Comment by ymodak** [comment]
You need to create custom implementations: AudioSpectrogram, DecodeWav, Mfcc. as they are not currently covered by the tflite ops.
See https://www.tensorflow.org/lite/guide/ops_custom

**Comment by Kamanica** [comment]
> Try this
> tflite_convert
> --output_file=/output.tflite
> --graph_def_file /path/to/my_frozen_graph.pb
> --input_arrays decoded_sample_data,decoded_sample_data:1
> --output_arrays labels_softmax
> --allow_custom_ops

Thanks it works with above. I only needed to add --enable_v1_converter

**Comment by Kamanica** [comment]
> You need to create custom implementations: AudioSpectrogram, DecodeWav, Mfcc. as they are not currently covered by the tflite ops.
> See https://www.tensorflow.org/lite/guide/ops_custom

Thanks! The command mentioned above worked, but I want to know why you think I will need to do the custom implementations. And if I do need to, is it already not available in GitHub by someone?

**Comment by vihari1729** [comment]
> > Try this
> > tflite_convert
> > --output_file=/output.tflite
> > --graph_def_file /path/to/my_frozen_graph.pb
> > --input_arrays decoded_sample_data,decoded_sample_data:1
> > --output_arrays labels_softmax
> > --allow_custom_ops
> 
> Thanks it works with above. I only needed to add --enable_v1_converter

Did you try the tflite model in android studio?Is it working there?.could you please send the images of the tflite model and graphdef model by opening it in https://lutzroeder.github.io/netron/

**Comment by Kamanica** [comment]
Thanks for providing the link to open the model. I am finding some differences between the original tflite model from the Android example app (conv_actions_frozen.tflite.png) and the new one I created using the tflite_convert command you provided (foo1.tflite.png)

![conv_actions_frozen tflite](https://user-images.githubusercontent.com/30161253/75095814-fbef2380-5566-11ea-8bde-d450fa75fe39.png)

![foo1 tflite](https://user-images.githubusercontent.com/30161253/75095821-145f3e00-5567-11ea-9f57-e339a80a1db8.png)

Any idea why the two tflite models differ, and how to get the new model to be the same as original model? The tensorflow model (pb file) I am using was created using the example speech_commands app, and I had only changed the wav files to customize them, and used the original train.py file to create the model (tensorflow/examples/speech_commands/train.py).

**Comment by vihari1729** [comment]
> Thanks for providing the link to open the model. I am finding some differences between the original tflite model from the Android example app (conv_actions_frozen.tflite.png) and the new one I created using the tflite_convert command you provided (foo1.tflite.png)
> 
> ![conv_actions_frozen tflite](https://user-images.githubusercontent.com/30161253/75095814-fbef2380-5566-11ea-8bde-d450fa75fe39.png)
> 
> ![foo1 tflite](https://user-images.githubusercontent.com/30161253/75095821-145f3e00-5567-11ea-9f57-e339a80a1db8.png)
> 
> Any idea why the two tflite models differ, and how to get the new model to be the same as original model? The tensorflow model (pb file) I am using was created using the example speech_commands app, and I had only changed the wav files to customize them, and used the original train.py file to create the model (tensorflow/examples/speech_commands/train.py).

i dont know ,but the new tflite model which u got will work in android studio

**Comment by ymodak** [comment]
Closing this issue since it's resolved. Thanks.
