### ISSUE TITLE
Win10 install: ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by meowcat** [tensorflow/tensorflow#36532]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 Education, Version 1903 (OS Build 18362.592)
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 2.1
- Python version: 3.7.6
- Installed using virtualenv? pip? conda?: pip (in a conda environment, conda 4.8.2)
- CUDA/cuDNN version: -
- GPU model and memory: none

**Steps to reproduce:**

I ran into the issue after installing regular `tensorflow`. Since some reports seem to indicate that cudnn/cuda version incompatibility could be an issue (even though I don't actually have a GPU on this system), I then installed `tensorflow-cpu` (in a fresh environment). The problem persists.

```
conda create -n tf-cpu-test python=3.7
conda activate tf-cpu-test
pip -V
pip install tensorflow_cpu
python
```
Also tried with `pip install tensorflow`, `pip install tensorflow-cpu`
In Python: 
```
import tensorflow as tf
```

**Any other info / logs**
```
Traceback (most recent call last):
  File "C:\Software\Anaconda37\envs\tf-cpu-test\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Software\Anaconda37\envs\tf-cpu-test\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Software\Anaconda37\envs\tf-cpu-test\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Software\Anaconda37\envs\tf-cpu-test\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Software\Anaconda37\envs\tf-cpu-test\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Software\Anaconda37\envs\tf-cpu-test\lib\site-packages\tensorflow\__init__.py", line 101, in <module>
    from tensorflow_core import *
  File "C:\Software\Anaconda37\envs\tf-cpu-test\lib\site-packages\tensorflow_core\__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Software\Anaconda37\envs\tf-cpu-test\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\Software\Anaconda37\envs\tf-cpu-test\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "C:\Software\Anaconda37\envs\tf-cpu-test\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Software\Anaconda37\envs\tf-cpu-test\lib\site-packages\tensorflow_core\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Software\Anaconda37\envs\tf-cpu-test\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Software\Anaconda37\envs\tf-cpu-test\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Software\Anaconda37\envs\tf-cpu-test\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Software\Anaconda37\envs\tf-cpu-test\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Software\Anaconda37\envs\tf-cpu-test\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Software\Anaconda37\envs\tf-cpu-test\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

**Comment by ravikyram** [comment]
@meowcat 
What is make/model of your cpu?
I suspect your cpu model does not support AVX instructions sets.See [hardware requirements](https://www.tensorflow.org/install/pip?lang=python3#hardware-requirements).Please, refer #36167 and see if it helps you . Thanks!

**Comment by meowcat** [comment]
Thanks! The vc2019 redist was the issue. Problem solved
