### ISSUE TITLE
ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type NAType).

### ISSUE THREAD

**Issue by MaUt89** [tensorflow/tensorflow#36594]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 64-bit
- TensorFlow installed from (source or binary): PyCharm
- TensorFlow version (use command below): 2.0.0
- Python version: 3.7.6

**Describe the current behavior**
I more or less tried to follow the instructions to load pandas.DataFrame (https://www.tensorflow.org/tutorials/load_data/pandas_dataframe) using my own dataset. Unfortunately the tf.data.Dataset.from_tensor_slices() function returns the following error:

ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type NAType).

The only difference in comparision with the tutorial is, that I used Strings as input in my pandas dataframe.

**Describe the expected behavior**
The Tensorflow dataset is created correctly.

**Code to reproduce the issue**
from __future__ import absolute_import, division, print_function, unicode_literals

import numpy as np
import tensorflow as tf
import pandas as pd

def data_preprocessing():
    print(tf.__version__)

    train_file_path = 'Learning Data Input/TrainingData.csv'

    pandas_data = pd.read_csv(train_file_path, delimiter=';', dtype='string')
    for column in pandas_data:
        if pandas_data[column].dtype != 'string':
            print(column)
    print(pandas_data.head())
    print(pandas_data.dtypes)
    
    # Feature to be predicted
    label_column = pandas_data.pop('PARTSET0')  

    raw_training_data = get_dataset(pandas_data, label_column)

def get_dataset(pandas_data, label_column):
    dataset = tf.data.Dataset.from_tensor_slices((pandas_data.values, label_column.values))

    return dataset

**Other info / logs**
My data set looks as follows:
 CC_ENDCUSTOMERNAME CC_ENDCUSTOMERCOUNTRY  ...     PARTSET7     PARTSET8
0  xxx                  THA  ...  123456  123456
1  yyy                   GER  ...  123456  123456
2  zzz                   US ...  123456  123456

and has round about 1000 rows and 190 columns. Please note that the numeric values in the csv are intentionally impported as Strings and this should be persisted.

Thanks for your help!

**Comment by Saduf2019** [comment]
@MaUt89 Please provide stand alone implementable code with the csv file used.

**Comment by MaUt89** [comment]
The code is already stand alone implementable, the def data_preprocessing() is only called in my main function and nothing else happens. The csv includes company sensitive data and I'm not able to provide it. Here is the complete error message for further information:

2020-02-10 13:25:05.197725: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
Traceback (most recent call last):
  File "C:\Users\Z002P84D\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\data\util\structure.py", line 111, in normalize_element
    ops.convert_to_tensor(t, name="component_%d" % i))
  File "C:\Users\Z002P84D\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1184, in convert_to_tensor
    return convert_to_tensor_v2(value, dtype, preferred_dtype, name)
  File "C:\Users\Z002P84D\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1242, in convert_to_tensor_v2
    as_ref=False)
  File "C:\Users\Z002P84D\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1296, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "C:\Users\Z002P84D\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\framework\tensor_conversion_registry.py", line 52, in _default_conversion_function
    return constant_op.constant(value, dtype, name=name)
  File "C:\Users\Z002P84D\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\framework\constant_op.py", line 227, in constant
    allow_broadcast=True)
  File "C:\Users\Z002P84D\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\framework\constant_op.py", line 235, in _constant_impl
    t = convert_to_eager_tensor(value, ctx, dtype)
  File "C:\Users\Z002P84D\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\framework\constant_op.py", line 96, in convert_to_eager_tensor
    return ops.EagerTensor(value, ctx.device_name, dtype)
ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type NAType).

And here some debug information of one column:
![image](https://user-images.githubusercontent.com/53083678/74149947-45f01500-4c09-11ea-944f-14f94f104c98.png)

**Comment by ymodak** [comment]
@MaUt89 Since the tutorial you are referring works fine we don't suspect it to be a bug at this point. If you can provide a dummy csv file which gives you same error as you see in your actual case will help us validate the issue and work on its fix. Apologies we cannot help you debug/fix the error without complete minimal repro code. 
You can also try posting this question on StackOverFlow. Thanks!
