### ISSUE TITLE
Import issue tensorflow 2.1.0 using Windows 10 AMD Radeon processor with GPU

### ISSUE THREAD

**Issue by shivamspj** [tensorflow/tensorflow#36618]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): bin
- TensorFlow version: 2.1.0
- Python version: 3.5.2
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: None
- GPU model and memory: AMD Radeon 1 GB

**Describe the problem**

Cannot import tensorflow after installation

**Provide the exact sequence of commands / steps that you executed before running into the problem**

pip install tensorflow

**Any other info / logs**
import tensorflow
Traceback (most recent call last):
  File "C:\Users\kumar.shivam\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\kumar.shivam\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\kumar.shivam\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\kumar.shivam\AppData\Local\Programs\Python\Python35\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\kumar.shivam\AppData\Local\Programs\Python\Python35\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\kumar.shivam\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\__init__.py", line 101, in <module>
    from tensorflow_core import *
  File "C:\Users\kumar.shivam\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow_core\__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\kumar.shivam\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\Users\kumar.shivam\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "C:\Users\kumar.shivam\AppData\Local\Programs\Python\Python35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\kumar.shivam\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow_core\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\kumar.shivam\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\kumar.shivam\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\kumar.shivam\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\kumar.shivam\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\kumar.shivam\AppData\Local\Programs\Python\Python35\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\kumar.shivam\AppData\Local\Programs\Python\Python35\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by amahendrakar** [comment]
@shivamspj,
Could you please check [this](https://github.com/tensorflow/tensorflow/issues/36167#issuecomment-577886156) comment from a similar issue and let us know if it helps. Thanks!

**Comment by shivamspj** [comment]
@amahendrakar
Thanks for the prompt reply. I could solve the issue by reinstalling python version 3.5. MSVC reinstallation. And corresponding libraries(tensorflow).
