### ISSUE TITLE
unspecified errors while building tensorflow

### ISSUE THREAD

**Issue by themusmus** [tensorflow/tensorflow#36682]
**System information**

- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): window 10 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:N/A
- TensorFlow installed from (source or binary): build from source
- TensorFlow version (use command below):2.1.0
- Python version: python 3.8.1
- Bazel version (if compiling from source):0.29.1
- CUDA/cuDNN version:N/A
- GPU model and memory:N/A

**Describe the current behavior**

While building tensorflow/examples/label_image,build process fails with unspecified error code changing everytime i build. I think this error is due to lack of memory of my laptop. but can't find the reason of it with error code i got from it.
Attaching three error codes i got while building.

ERROR: C:/users/gyuhwan/_bazel_gyuhwan/qrf5imf6/external/com_google_protobuf/BUILD:759:1: ProtoCompile external/com_google_protobuf/python/google/protobuf/field_mask_pb2.py failed (Exit -1). Note: Remote connection/protocol failed with: execution failed
Action failed to execute: java.io.IOException: ERROR: src/main/native/windows/process.cc(199): CreateProcessW("C:\users\gyuhwan\_bazel_gyuhwan\qrf5imf6\execroot\org_tensorflow\bazel-out\x64_windows-opt\bin\external\com_google_protobuf\protoc.exe" --python_out=bazel-out/x64_windows-py2-opt/bin/external/com_google_protobuf/python -Iexternal/com_google_protobuf/python -Ibazel-out/x64_windows-py2-opt/bin/external/com_google_protobuf/python bazel-out/x64_windows-py2-opt/bin/external/com_google_protobuf/python/google/protobuf/field_mask.proto): ?≪꽭?ㅺ? 嫄곕??섏뿀?듬땲??

ERROR: C:/users/gyuhwan/tensor_flow/tensorflow/tensorflow/core/kernels/boosted_trees/BUILD:22:1: ProtoCompile tensorflow/core/kernels/boosted_trees/boosted_trees.pb.h failed (Exit -1). Note: Remote connection/protocol failed with: execution failed
Action failed to execute: java.io.IOException: ERROR: src/main/native/windows/process.cc(199): CreateProcessW("C:\users\gyuhwan\_bazel_gyuhwan\qrf5imf6\execroot\org_tensorflow\bazel-out\x64_windows-opt\bin\external\com_google_protobuf\protoc.exe" --cpp_out=bazel-out/x64_windows-py2-opt/bin -I. -Iexternal/com_google_protobuf/src -Ibazel-out/x64_windows-py2-opt/bin/external/com_google_protobuf/src tensorflow/core/kernels/boosted_trees/boosted_trees.proto): ?≪꽭?ㅺ? 嫄곕??섏뿀?듬땲??
 (error: 5)

ERROR: C:/users/gyuhwan/tensor_flow/tensorflow/tensorflow/core/BUILD:2499:1: ProtoCompile tensorflow/core/protobuf/saved_model_pb2.py failed due to unexpected I/O exception: C:\users\gyuhwan\_bazel_gyuhwan\qrf5imf6\execroot\org_tensorflow\bazel-out\_tmp\action_outs\stderr-3 (?? ????? ??? ?? ??? ??? ????? ??? ? ? ????)
java.io.FileNotFoundException: C:\users\gyuhwan\_bazel_gyuhwan\qrf5imf6\execroot\org_tensorflow\bazel-out\_tmp\action_outs\stderr-3 (?? ????? ??? ?? ??? ??? ????? ??? ? ? ????)
        at java.base/java.io.FileOutputStream.open0(Native Method)
        at java.base/java.io.FileOutputStream.open(Unknown Source)
        at java.base/java.io.FileOutputStream.<init>(Unknown Source)
        at java.base/java.io.FileOutputStream.<init>(Unknown Source)
        at com.google.devtools.build.lib.vfs.AbstractFileSystem$ProfiledFileOutputStream.<init>(AbstractFileSystem.java:153)
        at com.google.devtools.build.lib.vfs.AbstractFileSystem.createFileOutputStream(AbstractFileSystem.java:89)
        at com.google.devtools.build.lib.vfs.AbstractFileSystem.getOutputStream(AbstractFileSystem.java:101)
        at com.google.devtools.build.lib.vfs.Path.getOutputStream(Path.java:535)
        at com.google.devtools.build.lib.vfs.Path.getOutputStream(Path.java:523)
        at com.google.devtools.build.lib.util.io.FileOutErr$FileRecordingOutputStream.getOutputStream(FileOutErr.java:353)
        at com.google.devtools.build.lib.util.io.FileOutErr$FileRecordingOutputStream.write(FileOutErr.java:460)
        at com.google.devtools.build.lib.exec.local.LocalSpawnRunner$SubprocessHandler.start(LocalSpawnRunner.java:365)
        at com.google.devtools.build.lib.exec.local.LocalSpawnRunner$SubprocessHandler.run(LocalSpawnRunner.java:192)
        at com.google.devtools.build.lib.exec.local.LocalSpawnRunner.exec(LocalSpawnRunner.java:153)
        at com.google.devtools.build.lib.exec.SpawnRunner.execAsync(SpawnRunner.java:225)
        at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:123)
        at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:88)
        at com.google.devtools.build.lib.actions.SpawnActionContext.beginExecution(SpawnActionContext.java:41)
        at com.google.devtools.build.lib.exec.ProxySpawnActionContext.beginExecution(ProxySpawnActionContext.java:60)
        at com.google.devtools.build.lib.actions.SpawnContinuation$1.execute(SpawnContinuation.java:80)
        at com.google.devtools.build.lib.analysis.actions.SpawnAction$SpawnActionContinuation.execute(SpawnAction.java:1344)
        at com.google.devtools.build.lib.analysis.actions.SpawnAction.beginExecution(SpawnAction.java:314)
        at com.google.devtools.build.lib.actions.Action.execute(Action.java:123)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$4.execute(SkyframeActionExecutor.java:851)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.continueAction(SkyframeActionExecutor.java:985)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.run(SkyframeActionExecutor.java:957)
        at com.google.devtools.build.lib.skyframe.ActionExecutionState.runStateMachine(ActionExecutionState.java:116)
        at com.google.devtools.build.lib.skyframe.ActionExecutionState.getResultOrDependOnFuture(ActionExecutionState.java:77)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:577)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:760)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:275)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:451)        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:399)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)

**Describe the expected behavior**

it would be helpful if error code notice the user that error is because of insufficient memory or notification of expected performance of computer

**Code to reproduce the issue**

bazel build /tensorflow/examples/label_image/...

**Other info / logs**

CPU of my computer is i7 1065G7 and memory is 8G

**Comment by gadagashwini** [comment]
@themusmus, Provide the exact sequence of commands / steps that you executed before running into the problem. Thanks!

**Comment by themusmus** [comment]
following steps of [https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/label_image](url)
executed the
`$ curl -L "https://storage.googleapis.com/download.tensorflow.org/models/inception_v3_2016_08_28_frozen.pb.tar.gz" |
  tar -C tensorflow/examples/label_image/data -xz`
code and run
`$ bazel build tensorflow/examples/label_image/...`
which keeps making errors wrote above

**Comment by ymodak** [comment]
Python 3.8 is a work in progress and not supported yet. Thanks!
For more info. duplicate #36790
