### ISSUE TITLE
TFLiteConverter: segmentation fault when dilation is not (1,1) in CONV_2D

### ISSUE THREAD

**Issue by wwwind** [tensorflow/tensorflow#36692]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): tf-nightly
- TensorFlow version (use command below): v1.12.1-24656-g0ec37eb 2.2.0-dev20200212
- Python version: 3.6.9
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I have segmentaion fault when I run the script.

**Describe the expected behavior**
No crashes.

**Code to reproduce the issue**

```
import numpy
import tensorflow
import tensorflow.keras
import tensorflow.lite

def representative_dataset_gen():
    yield [numpy.random.uniform(low=-1, high=1, size=(1,28,28,16)).astype(numpy.float32)]


model=tensorflow.keras.Sequential()
model.add(
    tensorflow.keras.layers.Conv2D(
        filters=16, kernel_size=7, dilation_rate=(2,2), input_shape=(28,28,16),
        use_bias=True, bias_initializer='ones'
    )
)

converter = tensorflow.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tensorflow.lite.Optimize.DEFAULT]
converter.target_spec.supported_ops = [tensorflow.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.representative_dataset = representative_dataset_gen
converter.experimental_new_converter = False

tflite_model = converter.convert()
```
**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

If I set experimental_new_converter = True, it works
If I set use_bias = False, it works
If I set dilation_rate=(1,1), it works

Logs:

2020-02-12 11:18:37.697439: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1118] 0:   N 
2020-02-12 11:18:37.701589: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:797] Optimization results for grappler item: graph_to_optimize
2020-02-12 11:18:37.701631: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:799]   constant_folding: Graph size after: 12 nodes (-7), 13 edges (-2), time = 0.839ms.
2020-02-12 11:18:37.701648: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:799]   constant_folding: Graph size after: 12 nodes (0), 13 edges (0), time = 0.249ms.
WARNING:absl:Please consider switching to use new converter by setting experimental_new_converter to true. Old converter (TOCO) is deprecated and flow will be switched on by default to use new converter soon.
Traceback (most recent call last):
  File "/home/elezhe01/work/scripts/test_crash.py", line 24, in <module>
    tflite_model = converter.convert()
  File "/home/elezhe01/.local/lib/python3.6/site-packages/tensorflow_core/lite/python/lite.py", line 513, in convert
    **converter_kwargs)
  File "/home/elezhe01/.local/lib/python3.6/site-packages/tensorflow_core/lite/python/convert.py", line 496, in toco_convert_impl
    enable_mlir_converter=enable_mlir_converter)
  File "/home/elezhe01/.local/lib/python3.6/site-packages/tensorflow_core/lite/python/convert.py", line 227, in toco_convert_protos
    raise ConverterError("See console for info.\n%s\n%s\n" % (stdout, stderr))
tensorflow.lite.python.convert.ConverterError: See console for info.
2020-02-12 11:18:39.730113: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 6 operators, 13 arrays (0 quantized)
2020-02-12 11:18:39.730252: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 6 operators, 13 arrays (0 quantized)
Fatal Python error: Segmentation fault

Current thread 0x00007f8f78473740 (most recent call first):
  File "/home/elezhe01/.local/lib/python3.6/site-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 56 in execute
  File "/home/elezhe01/.local/lib/python3.6/site-packages/absl/app.py", line 250 in _run_main
  File "/home/elezhe01/.local/lib/python3.6/site-packages/absl/app.py", line 299 in run
  File "/home/elezhe01/.local/lib/python3.6/site-packages/tensorflow_core/python/platform/app.py", line 40 in run
  File "/home/elezhe01/.local/lib/python3.6/site-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 93 in main
  File "/home/elezhe01/.local/bin/toco_from_protos", line 8 in <module>
Segmentation fault (core dumped)

**Comment by wwwind** [comment]
The version of TF is actually 2.2
I put output of the command v1.12.1-24656-g0ec37eb 2.2.0-dev20200212 - TF Git version is the first number and the second is the version of TF

**Comment by amahendrakar** [comment]
@wwwind,
Sorry for the incorrect label, fixed it.
I was able to reproduce the issue on [TF-nightly](https://colab.sandbox.google.com/gist/amahendrakar/0c0c73823cc734da006e2af211424186/36692_nightly.ipynb) v2.2.0-dev20200212. However, the code runs on [TF 2.1](https://colab.sandbox.google.com/gist/amahendrakar/913ccc0dcca84a1d51189b3c76f34d7f/36692.ipynb) without any issues. Please find the attached Gist. Thanks!

**Comment by wwwind** [comment]
@amahendrakar Thanks for the investigation! 
We are using tf-night, so I would like to confirm: it will be fixed in the tf-night, right ?

**Comment by wwwind** [comment]
This change https://github.com/tensorflow/tensorflow/pull/36856 fixed the crash

**Comment by amahendrakar** [comment]
@wwwind,
Is this still an issue? Please feel free to close the issue if it is resolved. Thanks!

**Comment by wwwind** [comment]
No, the fix has been merged.
