### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by ChrisJH1** [tensorflow/tensorflow#36702]
Hi,

I keep hitting an import error shown below

setup is Windows 10 64 bit - Processor	Intel(R) Core(TM) i7-7820HQ - GPU Nividia Quadro M1200, 

Running Spyder version 4.0 (tried 4.01 also) with python 3.7.6 (also tried 3.8) via virtual env  with tensorflow 2.  Despite a weeks worth of various combinations I am having no luck. Any help much appreciated 

Home setup works fine but I need it working on my work PC. I have a local install as I don't have admin rights.

ImportError: Traceback (most recent call last):
  File "C:\Users\user.user\Python 3.7.6 64bit\3.7.6\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\user.user\Python 3.7.6 64bit\3.7.6\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\user.user\Python 3.7.6 64bit\3.7.6\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\user.user\AppData\Local\Programs\Python\Python37\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\user.user\AppData\Local\Programs\Python\Python37\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by mihaimaruseac** [comment]
Closing as duplicate.

https://github.com/tensorflow/tensorflow/issues/36167#issuecomment-577886156

Just to sample over 100 similar issues: #36167 #36151 #36138 #36054 #36045 #36020 #36003 #35988 #35903 #35880 #35865 #35805 #35789 #35773 #35772 #35767 #35766 #35749 #35721 #35618 #35204

Please make sure you do a search in the future.
