### ISSUE TITLE
Bug: Cannot load model with tf.keras.layers.Lambda & eager functions enabled

### ISSUE THREAD

**Issue by phemmer** [tensorflow/tensorflow#36722]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Fedora 31
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): Source
- TensorFlow version (use command below): v2.1.0-1-ga9af83a149 2.1.0
- Python version: 3.7.5
- Bazel version (if compiling from source): 0.29.1
- GCC/Compiler version (if compiling from source): 8.3.1
- CUDA/cuDNN version: 10.2.89 / 7.6.5.33
- GPU model and memory: Nvidia GeForce GTX 1070 TI 8GB

**Describe the current behavior**
When attempting to load a saved model that contains a `tf.keras.layers.Lambda` and eager functions are enabled, it throws the following exception
```
Traceback (most recent call last):
  File "/tmp/test.py", line 13, in <module>
    tf.keras.models.load_model("/tmp/foo")
  File "/home/phemmer/.local/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/save.py", line 150, in load_model
    return saved_model_load.load(filepath, compile)
  File "/home/phemmer/.local/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/saved_model/load.py", line 89, in load
    model = tf_load.load_internal(path, loader_cls=KerasObjectLoader)
  File "/home/phemmer/.local/lib/python3.7/site-packages/tensorflow_core/python/saved_model/load.py", line 552, in load_internal
    export_dir)
  File "/home/phemmer/.local/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/saved_model/load.py", line 119, in __init__
    self._finalize()
  File "/home/phemmer/.local/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/saved_model/load.py", line 157, in _finalize
    created_layers={layer.name: layer for layer in node.layers})
  File "/home/phemmer/.local/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/network.py", line 1903, in reconstruct_from_config
    process_node(layer, node_data)
  File "/home/phemmer/.local/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/network.py", line 1851, in process_node
    output_tensors = layer(input_tensors, **kwargs)
  File "/home/phemmer/.local/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 773, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "/home/phemmer/.local/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/saved_model/utils.py", line 59, in return_outputs_and_add_losses
    outputs, losses = fn(inputs, *args, **kwargs)
  File "/home/phemmer/.local/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/saved_model/utils.py", line 113, in wrap_with_training_arg
    lambda: replace_training_and_call(False))
  File "/home/phemmer/.local/lib/python3.7/site-packages/tensorflow_core/python/keras/utils/tf_utils.py", line 59, in smart_cond
    pred, true_fn=true_fn, false_fn=false_fn, name=name)
  File "/home/phemmer/.local/lib/python3.7/site-packages/tensorflow_core/python/framework/smart_cond.py", line 59, in smart_cond
    name=name)
  File "/home/phemmer/.local/lib/python3.7/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/phemmer/.local/lib/python3.7/site-packages/tensorflow_core/python/ops/control_flow_ops.py", line 1174, in cond
    return cond_v2.cond_v2(pred, true_fn, false_fn, name)
  File "/home/phemmer/.local/lib/python3.7/site-packages/tensorflow_core/python/ops/cond_v2.py", line 83, in cond_v2
    op_return_value=pred)
  File "/home/phemmer/.local/lib/python3.7/site-packages/tensorflow_core/python/framework/func_graph.py", line 978, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/phemmer/.local/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/saved_model/utils.py", line 112, in <lambda>
    lambda: replace_training_and_call(True),
  File "/home/phemmer/.local/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/saved_model/utils.py", line 108, in replace_training_and_call
    return wrapped_call(*args, **kwargs)
  File "/home/phemmer/.local/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 555, in __call__
    return self._python_function(*args, **kwds)
  File "/home/phemmer/.local/lib/python3.7/site-packages/tensorflow_core/python/saved_model/function_deserialization.py", line 262, in restored_function_body
    "\n\n".join(signature_descriptions)))
ValueError: Could not find matching function to call loaded from the SavedModel. Got:
  Positional arguments (1 total):
    * Tensor("input_1_1:0", shape=(None, 3), dtype=float32)
  Keyword arguments: {'training': True}

Expected these arguments to match one of the following 2 option(s):

Option 1:
  Positional arguments (3 total):
    * TensorSpec(shape=(None, 3), dtype=tf.float32, name='inputs')
    * None
    * True
  Keyword arguments: {}

Option 2:
  Positional arguments (3 total):
    * TensorSpec(shape=(None, 3), dtype=tf.float32, name='inputs')
    * None
    * False
  Keyword arguments: {}
```
**Describe the expected behavior**
No exception

This issue does kinda make sense, in that eager means to run native python instead of as a graph, in which case the python lambda can't be created from a saved model. But I think there's probably a better way to handle it than this. Maybe forcing this one part of the model to run as a graph.

**Code to reproduce the issue**
```python
import tensorflow as tf

tf.config.experimental_run_functions_eagerly(True)

ds = tf.data.Dataset.from_tensor_slices([[1,2,3],[4,5,6],[7,8,9]])

input = tf.keras.Input(shape=ds.element_spec.shape)

output = tf.keras.layers.Lambda(lambda tb: tb)(input)

model = tf.keras.Model(inputs=[input],outputs=[output])
model.save("/tmp/foo")
tf.keras.models.load_model("/tmp/foo")
```

**Comment by amahendrakar** [comment]
@phemmer,
Was able to reproduce the error in [TF 2.1](https://colab.sandbox.google.com/gist/amahendrakar/2fe3544585360b1152ede567878dccc3/36722.ipynb). Works without any issues in nightly version [TF 2.2.0.dev20200212](https://colab.sandbox.google.com/gist/amahendrakar/aad6174deb95ae40bc122f784322a3c7/36722_nightly.ipynb). Please find the Gist attached. Thanks!

**Comment by phemmer** [comment]
Thanks. I'll try again once the next release following 2.1.0 is out.
