### ISSUE TITLE
Can't open the camera/webcam due to a tensorflow installation problem.

### ISSUE THREAD

**Issue by Zayr0** [tensorflow/tensorflow#36725]
Hello, i have some problems with the installation of tensorflow and the opening of the webcam. Now i am nowhere near experienced with tensorflow, let alone the anaconda prompt menu. I hope you guys could provide me with some help. Thank you in advanced.

(tfpose) C:\Users\gebruiker\Desktop\tf-pose-estimation>python run_webcam.py --model=mobilenet_thin --resize=432x368 --camera=0
Traceback (most recent call last):
  File "C:\Users\gebruiker\Anaconda3\envs\tfpose\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\gebruiker\Anaconda3\envs\tfpose\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\gebruiker\Anaconda3\envs\tfpose\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\gebruiker\Anaconda3\envs\tfpose\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\gebruiker\Anaconda3\envs\tfpose\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: Kan opgegeven module niet vinden.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_webcam.py", line 8, in <module>
    from tf_pose.estimator import TfPoseEstimator
  File "C:\Users\gebruiker\Desktop\tf-pose-estimation\tf_pose\__init__.py", line 5, in <module>
    from tf_pose.runner import infer, Estimator, get_estimator
  File "C:\Users\gebruiker\Desktop\tf-pose-estimation\tf_pose\runner.py", line 7, in <module>
    from tf_pose import common
  File "C:\Users\gebruiker\Desktop\tf-pose-estimation\tf_pose\common.py", line 3, in <module>
    import tensorflow as tf
  File "C:\Users\gebruiker\Anaconda3\envs\tfpose\lib\site-packages\tensorflow\__init__.py", line 101, in <module>
    from tensorflow_core import *
  File "C:\Users\gebruiker\Anaconda3\envs\tfpose\lib\site-packages\tensorflow_core\__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\gebruiker\Anaconda3\envs\tfpose\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\Users\gebruiker\Anaconda3\envs\tfpose\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "C:\Users\gebruiker\Anaconda3\envs\tfpose\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\gebruiker\Anaconda3\envs\tfpose\lib\site-packages\tensorflow_core\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\gebruiker\Anaconda3\envs\tfpose\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\gebruiker\Anaconda3\envs\tfpose\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\gebruiker\Anaconda3\envs\tfpose\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\gebruiker\Anaconda3\envs\tfpose\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\gebruiker\Anaconda3\envs\tfpose\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\gebruiker\Anaconda3\envs\tfpose\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: Kan opgegeven module niet vinden.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by amahendrakar** [comment]
@Zayr0,
Could you please check [this](https://github.com/tensorflow/tensorflow/issues/36167#issuecomment-577886156) comment on a similar issue and let us know if it works. Thanks!

**Comment by amahendrakar** [comment]
@Zayr0,
Any updates regarding this issue? Thanks!

**Comment by amahendrakar** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
