### ISSUE TITLE
tensorflow-gpu=2.1.0 AttributeError: module 'tensorflow' has no attribute 'placeholder'

### ISSUE THREAD

**Issue by PingYufeng** [tensorflow/tensorflow#36730]
when I used the tensorflow-gpu=2.1.0 to run in keras-python3.6 env, it said:

Using TensorFlow backend.
2020-02-13 21:47:27.592762: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
WARNING:tensorflow:From D:\Anaconda3\envs\keras36\lib\site-packages\tensorflow_core\python\compat\v2_compat.py:65: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
Traceback (most recent call last):
  File "i:/Git_Lip/XWLip_lite/DC_kares_LipReading_P70_R18/code/network.py", line 574, in <module>
    models=Lip_net(**params)
  File "i:/Git_Lip/XWLip_lite/DC_kares_LipReading_P70_R18/code/network.py", line 367, in Lip_net
    input_data = Input(name='the_input', shape=(24,112,112,3), dtype='float32')
  File "D:\Anaconda3\envs\keras36\lib\site-packages\keras\engine\input_layer.py", line 178, in Input
    input_tensor=tensor)
  File "D:\Anaconda3\envs\keras36\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "D:\Anaconda3\envs\keras36\lib\site-packages\keras\engine\input_layer.py", line 87, in __init__
    name=self.name)
  File "D:\Anaconda3\envs\keras36\lib\site-packages\keras\backend\tensorflow_backend.py", line 517, in placeholder
    x = tf.placeholder(dtype, shape=shape, name=name)
AttributeError: module 'tensorflow' has no attribute 'placeholder'

how can I  sovle the problem?Thanks for replying.

**Comment by Saduf2019** [comment]
@PingYufeng  please share implementable stand alone code for the issue faced by you, for us to help you resolve the issue.

**Comment by pandrey-fr** [comment]
From your error stack, it looks like you are trying to execute TensorFlow 1 code (e.g. creating placeholder tensors) whose syntax is no longer supported in TensorFlow 2, which introduced numerous non-backward-compatible API changes.

Please [read about the API changes](https://www.tensorflow.org/guide/effective_tf2) to upgrade your code, or run your code with TensorFlow 1.15.

**Comment by Saduf2019** [comment]
@PingYufeng Please let us know if the above comment helps resolve the issue.

**Comment by Saduf2019** [comment]
@PingYufeng Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
