### ISSUE TITLE
Image Classification pretrained model breaks for batch size 1 with BaseCollectiveExecutor::StartAbort error

### ISSUE THREAD

**Issue by mankeyboy** [tensorflow/tensorflow#36740]
**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): No, code used from https://github.com/tensorflow/tensorrt/tftrt/examples/image-classification
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): RHEL 7.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if
the issue happens on mobile device: 
- TensorFlow installed from (source or
binary): Binary
- TensorFlow version (use command below): 2.1
- Python version: - Bazel
version (if compiling from source): 
- GCC/Compiler version (if compiling from
source): 7.3.0
- CUDA/cuDNN version: 10.2/7.6.5
- GPU model and memory: Tesla T4

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Related issue: https://github.com/tensorflow/tensorrt/issues/169: Link: https://github.com/tensorflow/tensorrt/issues/169#issuecomment-572383212 
This example uses a frozen graph that was downloaded from here: http://download.tensorflow.org/models/official/resnet_v1_imagenet_savedmodel.tar.gz

This issue happens for synthetic as well as a validation runs. I was making my runs using this call:
```
python image_classification.py --input_saved_model_dir data/resnet_v1_50/1523293981 --data_dir /home/mayroy13/Mayank/Mayank/test/imagenet --calib_data_dir /home/mayroy13/Mayank/Mayank/test/imagenet --minimum_segment_size 3 --output_saved_model_dir trt_engine --batch_size 1 --use_trt --num_iterations 100 --precision FP16 --mode validation --max_workspace_size $((2**32))
```
And it fails with the following error:
```
Benchmark arguments:
  batch_size: 1
  calib_data_dir: /home/mayroy13/Mayank/Mayank/test/imagenet
  data_dir: /home/mayroy13/Mayank/Mayank/test/imagenet
  display_every: 100
  gpu_mem_cap: 0
  input_saved_model_dir: data/resnet_v1_50/1523293981
  input_size: 224
  max_workspace_size: 4294967296
  minimum_segment_size: 3
  mode: validation
  num_calib_inputs: 50
  num_classes: 1001
  num_iterations: 100
  num_warmup_iterations: 50
  optimize_offline: False
  output_saved_model_dir: trt_engine
  precision: FP16
  preprocess_method: vgg
  target_duration: None
  use_synthetic: False
  use_trt: True
TensorRT Conversion Params:
  is_dynamic_op: True
  max_batch_size: 1
  max_workspace_size_bytes: 4294967296
  maximum_cached_engines: 100
  minimum_segment_size: 3
  precision_mode: FP16
  rewriter_config_template: None
  use_calibration: False
Conversion times:
  conversion: 40.5s
2020-02-13 22:40:45.510560: W tensorflow/core/common_runtime/base_collective_executor.cc:217] BaseCollectiveExecutor::StartAbort Invalid argument: Number of ways to split should evenly divide the split dimension, but got split_dim 0 (size = 1) and num_split 2
         [[{{node PartitionedCall/split_inputs/split}}]]
2020-02-13 22:40:45.510560: W tensorflow/core/common_runtime/base_collective_executor.cc:217] BaseCollectiveExecutor::StartAbort Invalid argument: Number of ways to split should evenly divide the split dimension, but got split_dim 0 (size = 1) and num_split 2
         [[{{node PartitionedCall/split_inputs/split}}]]
         [[PartitionedCall/split_inputs/split/_2]]
2020-02-13 22:40:45.511446: W tensorflow/core/common_runtime/base_collective_executor.cc:217] BaseCollectiveExecutor::StartAbort Invalid argument: Number of ways to split should evenly divide the split dimension, but got split_dim 0 (size = 1) and num_split 2
         [[{{node PartitionedCall/split_inputs/split}}]]
         [[PartitionedCall/TRTEngineOp_0/_6]]
Traceback (most recent call last):
  File "image_classification.py", line 464, in <module>
    target_duration=args.target_duration)
  File "image_classification.py", line 231, in run_inference
    batch_preds = graph_func(batch_images)[0].numpy()
  File "/home/mayroy13/anaconda3/envs/wml17/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 1551, in __call__
    return self._call_impl(args, kwargs)
  File "/home/mayroy13/anaconda3/envs/wml17/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 1591, in _call_impl
    return self._call_flat(args, self.captured_inputs, cancellation_manager)
  File "/home/mayroy13/anaconda3/envs/wml17/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 1692, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/home/mayroy13/anaconda3/envs/wml17/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 545, in call
    ctx=ctx)
  File "/home/mayroy13/anaconda3/envs/wml17/lib/python3.7/site-packages/tensorflow_core/python/eager/execute.py", line 67, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument:  Number of ways to split should evenly divide the split dimension, but got split_dim 0 (size = 1) and num_split 2
         [[node PartitionedCall/split_inputs/split (defined at image_classification.py:134) ]]
         [[PartitionedCall/split_inputs/split/_2]]
  (1) Invalid argument:  Number of ways to split should evenly divide the split dimension, but got split_dim 0 (size = 1) and num_split 2
         [[node PartitionedCall/split_inputs/split (defined at image_classification.py:134) ]]
0 successful operations.
1 derived errors ignored. [Op:__inference_pruned_25839]

Function call stack:
pruned -> pruned
```
**Describe the expected behavior**
The expected behaviour would be for the code to complete and print metrics for the run.

**Comment by sanjoy** [comment]
Unfortunately the original author of image_classification.py has moved on to other things.  @DEKHTIARJonathan do you want to take a look?

**Comment by mankeyboy** [comment]
@DEKHTIARJonathan did you get a chance to have a look at this?

**Comment by DEKHTIARJonathan** [comment]
Hi sorry,
I'm not able to look into this one currently

**Comment by sushreebarsa** [comment]
@mankeyboy  Could you please try on latest stable version of tf 2.5 or 2.4.1 and let us know if this is still an issue.Thanks!
