### ISSUE TITLE
Error converting GraphDef to tflite - Check failed: GetOpWithOutput(model, output_array) Specified output array "'TFLite_Detection_PostProcess'" is not produced by any op in this graph

### ISSUE THREAD

**Issue by Jack-Hewson** [tensorflow/tensorflow#36772]
**System information**
- OS Platform and Distribution = Win10
- TensorFlow installed from binary - pip
- TensorFlow version 1.13.1

**Command used to run the converter or code if you’re using the Python API**

```
# Copy and paste here the exact command
tflite_convert \
 --output_file=/tmp/detect.tflite \ 
 --graph_def_file=tflite2/tflite_graph.pb \ 
 --input_shapes=1,300,300,3 \
 --input_arrays=image_tensor \ 
--output_arrays='TFLite_Detection_PostProcess','TFLite_Detection_PostProcess:1','TFLite_Detection_PostProcess:2','TFLite_Detection_PostProcess:3'

**The output from the converter invocation**

```
# Copy and paste the output here.
(tensorflow1) C:\tensorflow1\models\research\object_detection>tflite_convert \ --output_file=/tmp/fuck.tflite \ --graph_def_file=tflite2/tflite_graph.pb \ --input_shapes=1,300,300,3 \ --input_arrays=image_tensor \ --output_arrays='TFLite_Detection_PostProcess','TFLite_Detection_PostProcess:1','TFLite_Detection_PostProcess:2','TFLite_Detection_PostProcess:3'
2020-02-15 00:33:22.884597: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-02-15 00:33:24.579223: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2020-02-15 00:33:24.608227: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties:
name: GeForce RTX 2080 SUPER major: 7 minor: 5 memoryClockRate(GHz): 1.845
pciBusID: 0000:2d:00.0
2020-02-15 00:33:24.611885: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-02-15 00:33:24.616006: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-02-15 00:33:24.621212: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-02-15 00:33:24.623686: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-02-15 00:33:24.628228: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-02-15 00:33:24.631880: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-02-15 00:33:24.640338: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-02-15 00:33:24.642489: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-02-15 00:33:24.644141: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
2020-02-15 00:33:24.649750: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties:
name: GeForce RTX 2080 SUPER major: 7 minor: 5 memoryClockRate(GHz): 1.845
pciBusID: 0000:2d:00.0
2020-02-15 00:33:24.653135: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-02-15 00:33:24.656487: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-02-15 00:33:24.658613: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-02-15 00:33:24.660695: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-02-15 00:33:24.662859: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-02-15 00:33:24.665900: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-02-15 00:33:24.670329: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-02-15 00:33:24.672979: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-02-15 00:33:25.178111: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-02-15 00:33:25.179912: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0
2020-02-15 00:33:25.181515: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N
2020-02-15 00:33:25.184222: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6269 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 SUPER, pci bus id: 0000:2d:00.0, compute capability: 7.5)
Traceback (most recent call last):
  File "C:\Users\jacks\Anaconda3\envs\tensorflow1\Scripts\tflite_convert-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\jacks\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow_core\lite\python\tflite_convert.py", line 515, in main
    app.run(main=run_main, argv=sys.argv[:1])
  File "C:\Users\jacks\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow_core\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Users\jacks\Anaconda3\envs\tensorflow1\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "C:\Users\jacks\Anaconda3\envs\tensorflow1\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "C:\Users\jacks\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow_core\lite\python\tflite_convert.py", line 511, in run_main
    _convert_tf1_model(tflite_flags)
  File "C:\Users\jacks\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow_core\lite\python\tflite_convert.py", line 199, in _convert_tf1_model
    output_data = converter.convert()
  File "C:\Users\jacks\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow_core\lite\python\lite.py", line 989, in convert
    **converter_kwargs)
  File "C:\Users\jacks\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow_core\lite\python\convert.py", line 412, in toco_convert_graph_def
    enable_mlir_converter=enable_mlir_converter)
  File "C:\Users\jacks\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow_core\lite\python\convert.py", line 200, in toco_convert_protos
    raise ConverterError("See console for info.\n%s\n%s\n" % (stdout, stderr))
tensorflow.lite.python.convert.ConverterError: See console for info.
2020-02-15 00:33:25.515637: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-02-15 00:33:27.222702: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TFLite_Detection_PostProcess
2020-02-15 00:33:27.230047: F tensorflow/lite/toco/tooling_util.cc:935] Check failed: GetOpWithOutput(model, output_array) Specified output array "'TFLite_Detection_PostProcess'" is not produced by any op in this graph. Is it a typo? This should not happen. If you trigger this error please send a bug report (with code to reporduce this error), to the TensorFlow Lite team.
Fatal Python error: Aborted

Current thread 0x00002c24 (most recent call first):
  File "C:\Users\jacks\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow_core\lite\toco\python\toco_from_protos.py", line 52 in execute
  File "C:\Users\jacks\Anaconda3\envs\tensorflow1\lib\site-packages\absl\app.py", line 250 in _run_main
  File "C:\Users\jacks\Anaconda3\envs\tensorflow1\lib\site-packages\absl\app.py", line 299 in run
  File "C:\Users\jacks\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow_core\python\platform\app.py", line 40 in run
  File "C:\Users\jacks\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow_core\lite\toco\python\toco_from_protos.py", line 89 in main
  File "C:\Users\jacks\Anaconda3\envs\tensorflow1\Scripts\toco_from_protos-script.py", line 10 in <module>

**Comment by jvishnuvardhan** [comment]
@Jack-Hewson Did you try recent `TF1.15` version?. Can you please share a standalone code to reproduce the issue? share the model also. Thanks!

**Comment by Jack-Hewson** [comment]
Sorry I made the mistake in creating an inference graph and not the graph for tflite

**Comment by xaing123** [comment]
How do you solve it?

**Comment by xaing123** [comment]
@Jack-Hewson
