### ISSUE TITLE
TFTRT Int8 calibrate cost all of memory and Fail

### ISSUE THREAD

**Issue by doublexxking** [tensorflow/tensorflow#36778]
**System information** 
Hardware : i7 + 1660ti 
TensorFlow installed from source using bazel
The tf_env.txt is shown :

== check python ===================================================
python version: 3.5.2
python branch: 
python build version: ('default', 'Oct  8 2019 13:06:37')
python compiler version: GCC 5.4.0 20160609
python implementation: CPython

== check os platform ===============================================
os: Linux
os kernel version: #30~18.04.1-Ubuntu SMP Fri Jan 17 06:14:09 UTC 2020
os release version: 5.3.0-28-generic
os platform: Linux-5.3.0-28-generic-x86_64-with-Ubuntu-16.04-xenial
linux distribution: ('Ubuntu', '16.04', 'xenial')
linux os distribution: ('Ubuntu', '16.04', 'xenial')
mac version: ('', ('', '', ''), '')
uname: uname_result(system='Linux', node='xuxin', release='5.3.0-28-generic', version='#30~18.04.1-Ubuntu SMP Fri Jan 17 06:14:09 UTC 2020', machine='x86_64', processor='x86_64')
architecture: ('64bit', 'ELF')
machine: x86_64

== are we in docker =============================================
Yes

== compiler =====================================================
c++ (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

== check pips ===================================================
numpy                1.17.3                
protobuf             3.10.0                
tensorflow           1.15.0                
tensorflow-estimator 1.15.1                

== check for virtualenv =========================================
False
== env ==========================================================
LD_LIBRARY_PATH is unset
DYLD_LIBRARY_PATH is unset

== nvidia-smi ===================================================
Sat Feb 15 07:29:47 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.59       Driver Version: 440.59       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 166...  Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   41C    P0    28W /  N/A |    346MiB /  5944MiB |     13%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+

== cuda libs  ===================================================
/usr/local/lib/python3.5/dist-packages/torch/lib/libcudart-1b201d85.so.10.1
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudart.so.10.1.243
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudart_static.a

== tensorflow installed from info ==================
Name: tensorflow
Version: 1.15.0
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: /usr/local/lib/python3.5/dist-packages
Required-by: 

== python version  ==============================================
(major, minor, micro, releaselevel, serial)
(2, 7, 12, 'final', 0)

== bazel version  ===============================================
Build label: 0.24.1
Build time: Tue Apr 2 16:29:26 2019 (1554222566)
Build timestamp: 1554222566
Build timestamp as int: 1554222566

**Describe the current behavior**

I use tftrt module to calibrate int8 model.
I can convert() the model successfully and cost a little memory.
But, as I do calibrate(), the memory increase crazily and use the whole memory.
I set config as following and send to init TrtGraphConverter:
        config = tf.ConfigProto()
        config.gpu_options.per_process_gpu_memory_fraction = 0.5
        config.gpu_options.allow_growth = True
        config.allow_soft_placement = True
        config.log_device_placement = False

But it is useless.
By the way, I can use my PC to infer the model normally but calibrate always fail. 

**Code to reproduce the issue**
```
        config = tf.ConfigProto()
        config.gpu_options.per_process_gpu_memory_fraction = 0.5
        config.gpu_options.allow_growth = True
        config.allow_soft_placement = True
        config.log_device_placement = False

        tftrt_graph = tftrt.TrtGraphConverter(
            input_graph_def=graph.frozen_graph,
            nodes_blacklist=graph.y_name,
            session_config=config,
            max_batch_size=1,
            max_workspace_size_bytes=1 << 32,
            precision_mode='INT8',
            is_dynamic_op=True,
            minimum_segment_size=5)

      engine_graph = tftrt_graph.convert()
      engine_graph = tftrt_graph.calibrate(
                fetch_names=[x + ':0' for x in graph.y_name],
                num_runs=1,
                feed_dict_fn=feed_dict_fn)
```

**Other info / logs** 

The TFTRT output :
2020-02-15 07:03:29.178998: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-02-15 07:03:29.179482: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce GTX 1660 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.59
pciBusID: 0000:01:00.0
2020-02-15 07:03:29.179549: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-02-15 07:03:29.179572: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-02-15 07:03:29.179608: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-02-15 07:03:29.179642: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-02-15 07:03:29.179652: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-02-15 07:03:29.179701: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-02-15 07:03:29.179715: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-02-15 07:03:29.179777: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-02-15 07:03:29.180161: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-02-15 07:03:29.180449: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-02-15 07:03:29.180472: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-02-15 07:03:29.180498: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-02-15 07:03:29.180525: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-02-15 07:03:29.180604: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-02-15 07:03:29.180926: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-02-15 07:03:29.181202: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 5214 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1660 Ti, pci bus id: 0000:01:00.0, compute capability: 7.5)
2020-02-15 07:03:30.620789: I tensorflow/compiler/tf2tensorrt/kernels/trt_engine_op.cc:812] Starting calibration thread on device 0, Calibration Resource @ 0x7f1be40085e0
2020-02-15 07:03:30.621001: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer.so.6
2020-02-15 07:03:30.621392: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer_plugin.so.6
2020-02-15 07:03:36.767786: E tensorflow/compiler/tf2tensorrt/utils/trt_logger.cc:41] DefaultLogger ../rtSafe/safeContext.cpp (105) - Cudnn Error in initializeCommonContext: 4 (Could not initialize cudnn, please check cudnn installation.)
2020-02-15 07:03:36.768004: E tensorflow/compiler/tf2tensorrt/utils/trt_logger.cc:41] DefaultLogger ../rtSafe/safeContext.cpp (105) - Cudnn Error in initializeCommonContext: 4 (Could not initialize cudnn, please check cudnn installation.)
2020-02-15 07:03:36.768058: E tensorflow/compiler/tf2tensorrt/kernels/trt_engine_op.cc:838] Calibration failed: Internal: Failed to build TensorRT engine
terminate called without an active exception
Aborted (core dumped)

**Comment by sanjoy** [comment]
These lines from the log look pertinent:

```
2020-02-15 07:03:36.767786: E tensorflow/compiler/tf2tensorrt/utils/trt_logger.cc:41] DefaultLogger ../rtSafe/safeContext.cpp (105) - Cudnn Error in initializeCommonContext: 4 (Could not initialize cudnn, please check cudnn installation.)
2020-02-15 07:03:36.768004: E tensorflow/compiler/tf2tensorrt/utils/trt_logger.cc:41] DefaultLogger ../rtSafe/safeContext.cpp (105) - Cudnn Error in initializeCommonContext: 4 (Could not initialize cudnn, please check cudnn installation.)
2020-02-15 07:03:36.768058: E tensorflow/compiler/tf2tensorrt/kernels/trt_engine_op.cc:838] Calibration failed: Internal: Failed to build TensorRT engine
terminate called without an active exception
Aborted (core dumped)
```

Are you sure you have a cuDNN installation?

You could consider using the [TensorFlow GPU docker images](https://www.tensorflow.org/install/docker#examples_using_gpu-enabled_images) to guarantee that the right versions of libraries like cuDNN are available.

**Comment by wangxiang2713** [comment]
I meet the same problem when calibrate some models, and succeed when calibrate other models, it seems not a cuDNN problem.

**Comment by sanjoy** [comment]
> I meet the same problem when calibrate some models, and succeed when calibrate other models, it seems not a cuDNN problem.

Are you sure this is the same problem?  @double344931987 's logs don't have "out of memory" errors.

Can you try using [`set_memory_growth`](https://www.tensorflow.org/guide/gpu#limiting_gpu_memory_growth) to prevent TF from allocating all of the GPU memory on startup? Does that address this issue?

**Comment by wangxiang2713** [comment]
I try using set_memory_growth but the error still happens, @sanjoy. My code is:
```
config = tf.ConfigProto()
config.gpu_options.per_process_gpu_memory_fraction = 0.5
config.gpu_options.allow_growth = True
 converter = trt.TrtGraphConverter(input_graph_def=original_graph_def,
                                        nodes_blacklist=preserve_nodes,
                                        session_config=config,
                                        max_batch_size=self.max_batch_size,
                                         max_workspace_size_bytes=(1 << 30) * 8,
                                         precision_mode="INT8",
                                        minimum_segment_size=self.minimum_segment_size,
                                         is_dynamic_op=self.is_dynamic_op,
                                         maximum_cached_engines=self.maximum_cached_engines,
                                         use_calibration=True)
```

**Comment by sanjoy** [comment]
@wangxiang2713 Thanks.  Do you mind opening a separate github issue, with a reproducer (i.e. a script I can run to reproduce the problem)?

**Comment by wangxiang2713** [comment]
I am very sorry that i can't provide the code and model because of authority, but i find that i can calibrate the model successfully with 16G GPU, but 'out of memory' log still esits. Can i control the GPU the function uses?

**Comment by sanjoy** [comment]
> Can i control the GPU the function uses?

Yes, see [here](https://www.tensorflow.org/guide/gpu#using_a_single_gpu_on_a_multi-gpu_system).

**Comment by wangxiang2713** [comment]
> > Can i control the GPU the function uses?
> 
> Yes, see [here](https://www.tensorflow.org/guide/gpu#using_a_single_gpu_on_a_multi-gpu_system).

Thankyou, I get the answer. TensorFlo GPU memory allocator is created once (per GPU device) - the first time a session is created in the process. Changing per_process_gpu_memory_fraction in the following sessions will not have any effect.

That's why i can't control the GPU.

**Comment by kitterive** [comment]
I also met this error during calibrate, follow is my test script, I use tf1.15 and tf2.0 ,they all have the same error:
import os
  2 import sys
  3 import time
  4 
  5 import numpy as np
  6 import tensorflow as tf
  7 from tensorflow.python.compiler.tensorrt import trt_convert as trt
  8 
  9 sys.path.append(".")
 10 from preprocessing import vgg_preprocess as vgg_preprocessing
 11 
 12 BATCH_SIZE = 1
 13 NUM_CALIB_IMAGES = 1
 14 
 15 SAVED_MODEL_DIR = "../models/resnet_v1_fp32/saved_model"
 16 # SAVED_MODEL_DIR = "../models/ssd_mobilenet-v2/saved_model"
 17 INT8_SAVED_MODEL_DIR = SAVED_MODEL_DIR + "_TFTRT_INT8/2"
 18 
 19 data_directory = "../imagenet-data/Calibration_data"
 20 
 21 calibration_files = [os.path.join(path, name) for path, _, files in os.walk(data_directory) for name in files]
 22 print('There are %d calibration files. \n%s\n%s\n...' % (
 23     len(calibration_files), calibration_files[0], calibration_files[-1]))
 24 calibration_files = calibration_files[:NUM_CALIB_IMAGES]
 25 
 26 
 27 def parse_file(filepath):
 28     image = tf.io.read_file(filepath)
 29     image = tf.image.decode_jpeg(image, channels=3)
 30     image = vgg_preprocessing(image, 224, 224)
 31     return image
 32     
 33 
 34 num_calibration_batches = 2
 35 
 36 dataset = tf.data.Dataset.from_tensor_slices(calibration_files)
 37 dataset = dataset.map(map_func=parse_file, num_parallel_calls=20)
 38 dataset = dataset.batch(batch_size=BATCH_SIZE)
 39 dataset = dataset.repeat(None)
 40 calibration_dataset = dataset.take(num_calibration_batches)
 41 
42 
 43 def calibration_input_fn():
 44     for x in calibration_dataset:
 45     ¦   yield (x,)
 46 
 47 
 48 conversion_params = trt.DEFAULT_TRT_CONVERSION_PARAMS._replace(
 49     precision_mode=trt.TrtPrecisionMode.INT8)
 50 
 51 converter = trt.TrtGraphConverterV2(
 52     input_saved_model_dir=SAVED_MODEL_DIR,
 53     conversion_params=conversion_params)
 54 
 55 converter.convert(calibration_input_fn=calibration_input_fn)
 56 
 57 converter.save(INT8_SAVED_MODEL_DIR)

# and get this error:
name: GeForce RTX 2080 major: 7 minor: 5 memoryClockRate(GHz): 1.71
pciBusID: 0000:01:00.0
2020-03-19 10:37:47.218951: I tensorflow/stream_executor/platform/default/dlopen_checker_stub.cc:25] GPU libraries are statically linked, skip dlopen check.
2020-03-19 10:37:47.219014: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-03-19 10:37:47.219244: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-03-19 10:37:47.219454: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-03-19 10:37:47.219485: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-03-19 10:37:47.219489: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-03-19 10:37:47.219493: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-03-19 10:37:47.219553: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-03-19 10:37:47.219783: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-03-19 10:37:47.219996: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6970 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080, pci bus id: 0000:01:00.0, compute capability: 7.5)
2020-03-19 10:37:47.985509: I tensorflow/compiler/tf2tensorrt/segment/segment.cc:460] There are 5 ops of 4 different types in the graph that are not converted to TensorRT: Softmax, ArgMax, Placeholder, NoOp, (For more information see https://docs.nvidia.com/deeplearning/frameworks/tf-trt-user-guide/index.html#supported-ops).
2020-03-19 10:37:48.002648: I tensorflow/compiler/tf2tensorrt/convert/convert_graph.cc:633] Number of TensorRT candidate segments: 1
2020-03-19 10:37:48.120657: I tensorflow/compiler/tf2tensorrt/convert/convert_graph.cc:734] TensorRT node resnet_model/TRTEngineOp_0 added for segment 0 consisting of 465 nodes succeeded.
2020-03-19 10:37:48.557035: W tensorflow/compiler/tf2tensorrt/convert/trt_optimization_pass.cc:183] TensorRTOptimizer is probably called on funcdef! This optimizer must *NOT* be called on function objects.
2020-03-19 10:37:48.684367: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:716] Optimization results for grappler item: tf_graph
2020-03-19 10:37:48.684399: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   constant folding: Graph size after: 470 nodes (-267), 485 edges (-267), time = 204.18ms.
2020-03-19 10:37:48.684404: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   layout: Graph size after: 476 nodes (6), 491 edges (6), time = 131.973ms.
2020-03-19 10:37:48.684407: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   constant folding: Graph size after: 472 nodes (-4), 487 edges (-4), time = 114.032ms.
2020-03-19 10:37:48.684411: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   TensorRTOptimizer: Graph size after: 8 nodes (-464), 4 edges (-483), time = 294.006ms.
2020-03-19 10:37:48.684414: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   constant folding: Graph size after: 5 nodes (-3), 4 edges (0), time = 60.511ms.
2020-03-19 10:37:48.684417: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:716] Optimization results for grappler item: resnet_model/TRTEngineOp_0_native_segment
2020-03-19 10:37:48.684420: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   constant folding: Graph size after: 467 nodes (0), 482 edges (0), time = 83.015ms.
2020-03-19 10:37:48.684423: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   layout: Graph size after: 467 nodes (0), 482 edges (0), time = 103.606ms.
2020-03-19 10:37:48.684426: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   constant folding: Graph size after: 467 nodes (0), 482 edges (0), time = 75.662ms.
2020-03-19 10:37:48.684431: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   TensorRTOptimizer: Graph size after: 467 nodes (0), 482 edges (0), time = 13.073ms.
2020-03-19 10:37:48.684434: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   constant folding: Graph size after: 467 nodes (0), 482 edges (0), time = 75.931ms.
2020-03-19 10:37:51.852897: I tensorflow/compiler/tf2tensorrt/kernels/trt_engine_op.cc:812] Starting calibration thread on device 0, Calibration Resource @ 0x7fdd3000b8d0
2020-03-19 10:37:52.727164: E tensorflow/compiler/tf2tensorrt/utils/trt_logger.cc:41] DefaultLogger ../rtSafe/safeContext.cpp (105) - Cudnn Error in initializeCommonContext: 4 (Could not initialize cudnn, please check cudnn installation.)
2020-03-19 10:37:52.727317: E tensorflow/compiler/tf2tensorrt/utils/trt_logger.cc:41] DefaultLogger ../rtSafe/safeContext.cpp (105) - Cudnn Error in initializeCommonContext: 4 (Could not initialize cudnn, please check cudnn installation.)
2020-03-19 10:37:52.727569: E tensorflow/compiler/tf2tensorrt/kernels/trt_engine_op.cc:838] Calibration failed: Internal: Failed to build TensorRT engine
2020-03-19 10:37:52.727656: W tensorflow/core/common_runtime/base_collective_executor.cc:216] BaseCollectiveExecutor::StartAbort Internal: Failed to feed calibration data
	 [[{{node resnet_model/TRTEngineOp_0}}]]
Traceback (most recent call last):
  File "V2ConvertTFTRTInt8.py", line 63, in <module>
    converter.convert(calibration_input_fn=calibration_input_fn)
  File "/home/guo/runprogram/Envs/py36tf20/lib/python3.6/site-packages/tensorflow_core/python/compiler/tensorrt/trt_convert.py", line 984, in convert
    self._converted_func(*map(ops.convert_to_tensor, inp))
  File "/home/guo/runprogram/Envs/py36tf20/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1081, in __call__
    return self._call_impl(args, kwargs)
  File "/home/guo/runprogram/Envs/py36tf20/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1121, in _call_impl
    return self._call_flat(args, self.captured_inputs, cancellation_manager)
  File "/home/guo/runprogram/Envs/py36tf20/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1224, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager)
  File "/home/guo/runprogram/Envs/py36tf20/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 511, in call
    ctx=ctx)
  File "/home/guo/runprogram/Envs/py36tf20/lib/python3.6/site-packages/tensorflow_core/python/eager/execute.py", line 67, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InternalError:  Failed to feed calibration data
	 [[node resnet_model/TRTEngineOp_0 (defined at /home/guo/runprogram/Envs/py36tf20/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1751) ]] [Op:__inference_pruned_8870]

Function call stack:
pruned

terminate called without an active exception
已放弃

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
