### ISSUE TITLE
tflite save issue

### ISSUE THREAD

**Issue by JaeinKim85** [tensorflow/tensorflow#36791]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary):
- TensorFlow version (or github SHA if from source):

**Provide the text output from tflite_convert**

```
2020-02-16 21:52:52.869005: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory
2020-02-16 21:52:52.869341: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory
2020-02-16 21:52:52.869351: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2020-02-16 21:52:55.481557: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Size
2020-02-16 21:52:55.497984: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Size
2020-02-16 21:52:55.498578: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Size
2020-02-16 21:52:55.498607: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Size
2020-02-16 21:52:55.499028: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Size
2020-02-16 21:52:55.499052: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Size
2020-02-16 21:52:55.499231: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: CombinedNonMaxSuppression
2020-02-16 21:52:55.535714: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 735 operators, 1368 arrays (0 quantized)
2020-02-16 21:52:55.561395: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 735 operators, 1368 arrays (0 quantized)
2020-02-16 21:52:56.057040: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 1: 284 operators, 533 arrays (0 quantized)
2020-02-16 21:52:56.062129: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 2: 284 operators, 533 arrays (0 quantized)
2020-02-16 21:52:56.067209: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Group bidirectional sequence lstm/rnn: 284 operators, 533 arrays (0 quantized)
2020-02-16 21:52:56.071019: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before dequantization graph transformations: 284 operators, 533 arrays (0 quantized)
2020-02-16 21:52:56.073859: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Identify nearest upsample.: 284 operators, 533 arrays (0 quantized)
2020-02-16 21:52:56.083033: I tensorflow/lite/toco/allocate_transient_arrays.cc:345] Total transient array allocated size: 66560128 bytes, theoretical optimal value: 44408960 bytes.
2020-02-16 21:52:56.083962: I tensorflow/lite/toco/toco_tooling.cc:471] Number of parameters: 61503185
2020-02-16 21:52:56.091894: E tensorflow/lite/toco/toco_tooling.cc:498] We are continually in the process of adding support to TensorFlow Lite for more ops. It would be helpful if you could inform us of how this conversion went by opening a github issue at https://github.com/tensorflow/tensorflow/issues/new?template=40-tflite-op-request.md
 and pasting the following:

Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, CAST, CONCATENATION, CONV_2D, DIV, EXP, EXPAND_DIMS, FILL, LEAKY_RELU, LOGISTIC, MUL, PACK, PAD, RESHAPE, RESIZE_NEAREST_NEIGHBOR, SHAPE, SPLIT_V, STRIDED_SLICE, SUB. Here is a list of operators for which you will need custom implementations: CombinedNonMaxSuppression, Size.
Traceback (most recent call last):
  File "/home/kji/anaconda3/envs/py37_tf/bin/toco_from_protos", line 8, in <module>
    sys.exit(main())
  File "/home/kji/anaconda3/envs/py37_tf/lib/python3.7/site-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 93, in main
    app.run(main=execute, argv=[sys.argv[0]] + unparsed)
  File "/home/kji/anaconda3/envs/py37_tf/lib/python3.7/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/kji/anaconda3/envs/py37_tf/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/kji/anaconda3/envs/py37_tf/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/home/kji/anaconda3/envs/py37_tf/lib/python3.7/site-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 56, in execute
    enable_mlir_converter)
Exception: We are continually in the process of adding support to TensorFlow Lite for more ops. It would be helpful if you could inform us of how this conversion went by opening a github issue at https://github.com/tensorflow/tensorflow/issues/new?template=40-tflite-op-request.md
 and pasting the following:

Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, CAST, CONCATENATION, CONV_2D, DIV, EXP, EXPAND_DIMS, FILL, LEAKY_RELU, LOGISTIC, MUL, PACK, PAD, RESHAPE, RESIZE_NEAREST_NEIGHBOR, SHAPE, SPLIT_V, STRIDED_SLICE, SUB. Here is a list of operators for which you will need custom implementations: CombinedNonMaxSuppression, Size.```

Also, please include a link to a GraphDef or the model if possible.

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

I don't know changing input size in tensorflow 2.1 tflite

**Comment by gadagashwini** [comment]
@JaeinKim85, Can you provide the standalone code to replicate the reported issue. Thanks!

**Comment by gadagashwini** [comment]
@JaeinKim85 ,
If you are using the [Python converter](https://www.tensorflow.org/lite/convert/python_api), with the latest version of TF/TFLite (nightly maybe?) could you try adding the following line pre-conversion:

converter.experimental_new_converter = True

If that doesn't work, it looks like we don't support the op yet :-(. You could try using [Select TF ops](https://www.tensorflow.org/lite/guide/ops_select) if you are using our C++/Java APIs. Thanks!
