### ISSUE TITLE
Tensorlfow with Pycharm

### ISSUE THREAD

**Issue by HelpMePlz1234** [tensorflow/tensorflow#36842]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): Source
- TensorFlow version: Latest to today
- Python version:3.7
- Installed using virtualenv? pip? conda?:Conda
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: idk
- GPU model and memory: 16gb intel core i5

Conda create -n tensor python=3.7
y
activate tensor
pip install tensorflow
pip install keras

logs
C:\Users\HP\Anaconda3\envs\tensor\pythonw.exe C:/Users/HP/PycharmProjects/TensorENV/Test.py
Traceback (most recent call last):
  File "C:\Users\HP\Anaconda3\envs\tensor\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\HP\Anaconda3\envs\tensor\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\HP\Anaconda3\envs\tensor\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\HP\Anaconda3\envs\tensor\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\HP\Anaconda3\envs\tensor\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/HP/PycharmProjects/TensorENV/Test.py", line 1, in <module>
    import tensorflow
  File "C:\Users\HP\Anaconda3\envs\tensor\lib\site-packages\tensorflow\__init__.py", line 101, in <module>
    from tensorflow_core import *
  File "C:\Users\HP\Anaconda3\envs\tensor\lib\site-packages\tensorflow_core\__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\HP\Anaconda3\envs\tensor\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\Users\HP\Anaconda3\envs\tensor\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "C:\Users\HP\Anaconda3\envs\tensor\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\HP\Anaconda3\envs\tensor\lib\site-packages\tensorflow_core\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\HP\Anaconda3\envs\tensor\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\HP\Anaconda3\envs\tensor\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\HP\Anaconda3\envs\tensor\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\HP\Anaconda3\envs\tensor\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\HP\Anaconda3\envs\tensor\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\HP\Anaconda3\envs\tensor\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

Failed to load the native TensorFlow runtime.

**Comment by gadagashwini** [comment]
@HelpMePlz1234,
TensorFlow release binaries version 1.6 and higher are prebuilt with AVX instruction sets.
Therefore on any CPU that does not have these instruction sets, either CPU or GPU version of TF will fail to load. Please check does your CPU supports AVX instruction sets or not. Thanks!

**Comment by HelpMePlz1234** [comment]
It is an i5-6300u. Also it is a Q3 so I think it supports it.

**Comment by gadagashwini** [comment]
@HelpMePlz1234, Did you install the Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017, and 2019. Starting with the TensorFlow 2.1.0 version, the msvcp140_1.dll file is required from this package (which may not be provided from older redistributable packages). The redistributable comes with Visual Studio 2019 but can be installed separately from https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads. Thanks!

**Comment by HelpMePlz1234** [comment]
Thank you I will do this now and see what happens

**Comment by HelpMePlz1234** [comment]
It works now but I got two new errors

2020-02-19 21:54:58.529308: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-02-19 21:54:58.529658: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.

**Comment by gadagashwini** [comment]
@HelpMePlz1234,Are you installing GPU support tensorflow with CUDA and cuDNN? as 
`pip install tensorflow-gpu==2.1`
Thanks!

**Comment by HelpMePlz1234** [comment]
no just cup

**Comment by HelpMePlz1234** [comment]
CPU
