### ISSUE TITLE
Tensorflow-gpu 2.1 Cuda 10.2, ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by Anto95** [tensorflow/tensorflow#36859]
**System information**
- OS Platform and Distribution: Windows 10
- TensorFlow installed from: pip install tensorflow-gpu
- TensorFlow version: tensorflow-gpu-2.1.0
- Python version: python 3.7.6
- Visual_Studio_Community 2019
- CUDA/cuDNN version: Cuda 10.2.89, cudnn-10.2-windows10-x64-v7.6.5.32
- GPU model and memory: NVIDIA GeForce 940MX 2GB

**Describe the problem**

I followed all the steps to install tensroflow-gpu today.
I downloaded Visual Studio 2019 and installed it.
Then I downloaded and installed NVIDIA CUDA 10.2 Toolkit and NVIDIA cuDNN 7.6.5.32 following compatibilities recommendations.
CUDA and CUDANN are in my environment variables, so no problems with that.
I installed today python 3.7.6 and tensorflow-gpu with pip inside a virtual environment, which took automatically version 2.1.
Pip install tensorflow-gpu runs smoothly but I get an error when I try to import it.
I open a new post because, in the opened one, the proposed solutions are:
* Downloading and installing visual studio 2015-2019 x86 and x64: it wouldn't work for me as I have already installed it.
* Downgrade to tensorflow 2.0: I would like to keep tensorflow 2.1, on top of this, even downgrading I get another run-time error, which is solvable by downgrading to CUDA 10.1, which I don't want to do.

**Any other info / logs**

This is the errror message: 
```
>>> import tensorflow as tf
Traceback (most recent call last):
  File "C:\Users\apaladini\OneDrive - Amadeus Workplace\Desktop\Work\2020\Tensorflow-gpu\venvs\py37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\apaladini\OneDrive - Amadeus Workplace\Desktop\Work\2020\Tensorflow-gpu\venvs\py37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\apaladini\OneDrive - Amadeus Workplace\Desktop\Work\2020\Tensorflow-gpu\venvs\py37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\apaladini\AppData\Local\Programs\Python\Python37\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\apaladini\AppData\Local\Programs\Python\Python37\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\apaladini\OneDrive - Amadeus Workplace\Desktop\Work\2020\Tensorflow-gpu\venvs\py37\lib\site-packages\tensorflow\__init__.py", line 101, in <module>
    from tensorflow_core import *
  File "C:\Users\apaladini\OneDrive - Amadeus Workplace\Desktop\Work\2020\Tensorflow-gpu\venvs\py37\lib\site-packages\tensorflow_core\__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\apaladini\OneDrive - Amadeus Workplace\Desktop\Work\2020\Tensorflow-gpu\venvs\py37\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\Users\apaladini\OneDrive - Amadeus Workplace\Desktop\Work\2020\Tensorflow-gpu\venvs\py37\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "C:\Users\apaladini\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\apaladini\OneDrive - Amadeus Workplace\Desktop\Work\2020\Tensorflow-gpu\venvs\py37\lib\site-packages\tensorflow_core\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\apaladini\OneDrive - Amadeus Workplace\Desktop\Work\2020\Tensorflow-gpu\venvs\py37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\apaladini\OneDrive - Amadeus Workplace\Desktop\Work\2020\Tensorflow-gpu\venvs\py37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\apaladini\OneDrive - Amadeus Workplace\Desktop\Work\2020\Tensorflow-gpu\venvs\py37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\apaladini\OneDrive - Amadeus Workplace\Desktop\Work\2020\Tensorflow-gpu\venvs\py37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\apaladini\AppData\Local\Programs\Python\Python37\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\apaladini\AppData\Local\Programs\Python\Python37\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```
I didn't find a way to find out what dll file the error is referring to.

How can I make this work?
Thanks in advance!

**Comment by av8ramit** [comment]
Any chance this comment helps:

https://github.com/tensorflow/tensorflow/issues/36167#issuecomment-577886156

I notice you already have Visual_Studio_Community 2019.

**Comment by gadagashwini** [comment]
@Anto95, Did you get a chance to look at @av8ramit's comment.Thanks

**Comment by mihaimaruseac** [comment]
Closing as duplicate.

https://github.com/tensorflow/tensorflow/issues/36167#issuecomment-577886156

#36167 #36151 #36138 #36054 #36045 #36020 #36003 #35988 #35903 #35880 #35865 #35805 #35789 #35773 #35772 #35767 #35766 #35749 #35721 #35618 #35204
