### ISSUE TITLE
missing ops

### ISSUE THREAD

**Issue by steven807** [tensorflow/tensorflow#36866]
**System information**
- MacOS Mojave: 10.14.6
- TensorFlow installed from binary
- TensorFlow version: 2.1.0

**Provide the text output from tflite_convert**

```
Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: CONV_2D, FULLY_CONNECTED, RESHAPE, SOFTMAX, STRIDED_SLICE, TANH. Here is a list of operators for which you will need custom implementations: TensorListFromTensor, TensorListReserve, TensorListStack, While.
```

Also, please include a link to a GraphDef or the model if possible.

**Any other info / logs**

Full output:
```
2020-02-18 12:08:47.613890: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-02-18 12:08:47.641459: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fb45f7d55d0 executing computations on platform Host. Devices:
2020-02-18 12:08:47.641499: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
WARNING:tensorflow:Error in loading the saved optimizer state. As a result, your model is starting with a freshly initialized optimizer.
W0218 12:08:48.275663 4679718336 hdf5_format.py:198] Error in loading the saved optimizer state. As a result, your model is starting with a freshly initialized optimizer.
2020-02-18 12:08:48.596718: I tensorflow/core/grappler/devices.cc:60] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0 (Note: TensorFlow was not compiled with CUDA support)
2020-02-18 12:08:48.596828: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2020-02-18 12:08:48.620729: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:716] Optimization results for grappler item: graph_to_optimize
2020-02-18 12:08:48.620755: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   function_optimizer: Graph size after: 125 nodes (0), 151 edges (0), time = 7.053ms.
2020-02-18 12:08:48.620760: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   function_optimizer: Graph size after: 125 nodes (0), 151 edges (0), time = 3.511ms.
2020-02-18 12:08:48.620765: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:716] Optimization results for grappler item: sequential_gru_while_cond_1874
2020-02-18 12:08:48.620769: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   function_optimizer: function_optimizer did nothing. time = 0.005ms.
2020-02-18 12:08:48.620773: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   function_optimizer: function_optimizer did nothing. time = 0ms.
2020-02-18 12:08:48.620778: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:716] Optimization results for grappler item: sequential_gru_while_body_1875
2020-02-18 12:08:48.620871: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   function_optimizer: function_optimizer did nothing. time = 0.001ms.
2020-02-18 12:08:48.620884: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   function_optimizer: function_optimizer did nothing. time = 0ms.
2020-02-18 12:08:48.704099: I tensorflow/core/grappler/devices.cc:60] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0 (Note: TensorFlow was not compiled with CUDA support)
2020-02-18 12:08:48.704194: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2020-02-18 12:08:48.742007: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:716] Optimization results for grappler item: graph_to_optimize
2020-02-18 12:08:48.742026: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   constant folding: Graph size after: 60 nodes (-5), 70 edges (-9), time = 19.624ms.
2020-02-18 12:08:48.742030: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   constant folding: Graph size after: 60 nodes (0), 70 edges (0), time = 4.102ms.
2020-02-18 12:08:48.742033: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:716] Optimization results for grappler item: sequential_gru_while_body_1875_frozen
2020-02-18 12:08:48.742035: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   constant folding: Graph size after: 79 nodes (0), 98 edges (0), time = 1.601ms.
2020-02-18 12:08:48.742038: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   constant folding: Graph size after: 79 nodes (0), 98 edges (0), time = 1.559ms.
2020-02-18 12:08:48.742040: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:716] Optimization results for grappler item: sequential_gru_while_cond_1874_frozen
2020-02-18 12:08:48.742144: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   constant folding: Graph size after: 14 nodes (0), 4 edges (0), time = 0.29ms.
2020-02-18 12:08:48.742148: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   constant folding: Graph size after: 14 nodes (0), 4 edges (0), time = 0.202ms.
Traceback (most recent call last):
  File "/usr/local/bin/tflite_convert", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/lite/python/tflite_convert.py", line 515, in main
    app.run(main=run_main, argv=sys.argv[:1])
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/lite/python/tflite_convert.py", line 502, in run_main
    _convert_tf2_model(tflite_flags)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/lite/python/tflite_convert.py", line 221, in _convert_tf2_model
    tflite_model = converter.convert()
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/lite/python/lite.py", line 446, in convert
    **converter_kwargs)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/lite/python/convert.py", line 449, in toco_convert_impl
    enable_mlir_converter=enable_mlir_converter)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/lite/python/convert.py", line 200, in toco_convert_protos
    raise ConverterError("See console for info.\n%s\n%s\n" % (stdout, stderr))
tensorflow.lite.python.convert.ConverterError: See console for info.
2020-02-18 12:08:52.222650: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-02-18 12:08:52.242018: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fd921cfa1b0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-02-18 12:08:52.242031: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-02-18 12:08:52.271859: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorListFromTensor
2020-02-18 12:08:52.271902: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 21
2020-02-18 12:08:52.271961: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorListReserve
2020-02-18 12:08:52.271971: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 21
2020-02-18 12:08:52.272009: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: While
2020-02-18 12:08:52.272030: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 21
2020-02-18 12:08:52.272035: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 21
2020-02-18 12:08:52.272059: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorListStack
2020-02-18 12:08:52.274986: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 26 operators, 67 arrays (0 quantized)
2020-02-18 12:08:52.279519: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 26 operators, 67 arrays (0 quantized)
2020-02-18 12:08:52.281200: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 1: 22 operators, 65 arrays (0 quantized)
2020-02-18 12:08:52.281569: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 2: 21 operators, 63 arrays (0 quantized)
2020-02-18 12:08:52.282014: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 3: 12 operators, 45 arrays (0 quantized)
2020-02-18 12:08:52.282246: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 4: 11 operators, 43 arrays (0 quantized)
2020-02-18 12:08:52.282451: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Group bidirectional sequence lstm/rnn: 11 operators, 43 arrays (0 quantized)
2020-02-18 12:08:52.282591: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before dequantization graph transformations: 11 operators, 43 arrays (0 quantized)
2020-02-18 12:08:52.282698: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Identify nearest upsample.: 11 operators, 43 arrays (0 quantized)
2020-02-18 12:08:52.282938: I tensorflow/lite/toco/allocate_transient_arrays.cc:345] Total transient array allocated size: 2304 bytes, theoretical optimal value: 1920 bytes.
2020-02-18 12:08:52.283040: I tensorflow/lite/toco/toco_tooling.cc:471] Number of parameters: 401825
2020-02-18 12:08:52.287920: E tensorflow/lite/toco/toco_tooling.cc:498] We are continually in the process of adding support to TensorFlow Lite for more ops. It would be helpful if you could inform us of how this conversion went by opening a github issue at https://github.com/tensorflow/tensorflow/issues/new?template=40-tflite-op-request.md
 and pasting the following:

Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: CONV_2D, FULLY_CONNECTED, RESHAPE, SOFTMAX, STRIDED_SLICE, TANH. Here is a list of operators for which you will need custom implementations: TensorListFromTensor, TensorListReserve, TensorListStack, While.
Traceback (most recent call last):
  File "/Users/grady/work/tensorflow/venv/bin/toco_from_protos", line 8, in <module>
    sys.exit(main())
  File "/Users/grady/work/tensorflow/venv/lib/python3.7/site-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 93, in main
    app.run(main=execute, argv=[sys.argv[0]] + unparsed)
  File "/Users/grady/work/tensorflow/venv/lib/python3.7/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/Users/grady/work/tensorflow/venv/lib/python3.7/site-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 56, in execute
    enable_mlir_converter)
Exception: We are continually in the process of adding support to TensorFlow Lite for more ops. It would be helpful if you could inform us of how this conversion went by opening a github issue at https://github.com/tensorflow/tensorflow/issues/new?template=40-tflite-op-request.md
 and pasting the following:

Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: CONV_2D, FULLY_CONNECTED, RESHAPE, SOFTMAX, STRIDED_SLICE, TANH. Here is a list of operators for which you will need custom implementations: TensorListFromTensor, TensorListReserve, TensorListStack, While.
```

**Comment by gadagashwini** [comment]
@steven807,You may try converting your model using `Select TensorFlow Ops`
Please take a look at similar [#35605](https://github.com/tensorflow/tensorflow/issues/35605#issuecomment-571737987) issue comment. Thanks!

**Comment by gadagashwini** [comment]
@steven807, any update?

**Comment by steven807** [comment]
Sorry, I didn't realize you were waiting a response.  I just tried running the converter (from the command line) as:
`tflite_convert --output_file=/tmp/foo.tflite --keras_model_file=model.hdf5 --target_ops=`_options_
with _options_ as all three recommended possibilities:

* TFLITE_BUILTINS
* TFLITE_BUILTINS,SELECT_TF_OPS
* SELECT_TF_OPS

and got the same result in each case:
`Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: CONV_2D, FULLY_CONNECTED, RESHAPE, SOFTMAX, STRIDED_SLICE, TANH. Here is a list of operators for which you will need custom implementations: TensorListFromTensor, TensorListReserve, TensorListStack, While.`

**Comment by ymodak** [comment]
Set`experimental_new_converter` flag to `True` to for `implementations: TensorListFromTensor, TensorListReserve, TensorListStack, While`.
See https://www.tensorflow.org/api_docs/python/tf/lite/TFLiteConverter?version=nightly#attributes
```python
# Assuming converting a tf.Keras model to a TensorFlow Lite model.
converter = lite.TFLiteConverter.from_keras_model(model)
converter.experimental_new_converter = True  #Set`experimental_new_converter` flag to `True`
tflite_model = converter.convert()
```
