### ISSUE TITLE
trouble importing tensorflow_hub

### ISSUE THREAD

**Issue by mshmsh1234** [tensorflow/tensorflow#36863]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Microsoft Windows 10 pro
- TensorFlow installed from (source or binary): binary (?) pip install
- TensorFlow version: tensorflow - 2.1.0,   tensorflow-hub       0.7.0 
- Python version: 3.7.6
- Installed using virtualenv? pip? conda?: Installed using pip within virtualenv.

**Describe the problem**
Cannot import tensorflow_hub due to the error in the output below. tensorflow_hub is installed successfully and tensorflow is able to import.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
import tensorflow_hub as hub

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

```ImportError                               Traceback (most recent call last)
~\AppData\Local\Continuum\miniconda3\envs\pya\lib\site-packages\tensorflow\python\pywrap_tensorflow.py in <module>
     57 
---> 58   from tensorflow.python.pywrap_tensorflow_internal import *
     59 

~\AppData\Local\Continuum\miniconda3\envs\pya\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py in <module>
     27             return _mod
---> 28     _pywrap_tensorflow_internal = swig_import_helper()
     29     del swig_import_helper

~\AppData\Local\Continuum\miniconda3\envs\pya\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py in swig_import_helper()
     23             try:
---> 24                 _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
     25             finally:

~\AppData\Local\Continuum\miniconda3\envs\pya\lib\imp.py in load_module(name, file, filename, details)
    241         else:
--> 242             return load_dynamic(name, filename, file)
    243     elif type_ == PKG_DIRECTORY:

~\AppData\Local\Continuum\miniconda3\envs\pya\lib\imp.py in load_dynamic(name, path, file)
    341             name=name, loader=loader, origin=path)
--> 342         return _load(spec)
    343 

ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-22-85533c25c7ee> in <module>
----> 1 import tensorflow_hub as hub
      2 #import tensorflow as tf
      3 
      4 #elmo = hub.Module("https://tfhub.dev/google/elmo/2", trainable=True)

~\AppData\Local\Continuum\miniconda3\envs\pya\lib\site-packages\tensorflow_hub\__init__.py in <module>
     21 from absl import logging
     22 from distutils.version import LooseVersion
---> 23 import tensorflow as tf
     24 
     25 # pylint: disable=g-import-not-at-top

~\AppData\Local\Continuum\miniconda3\envs\pya\lib\site-packages\tensorflow\__init__.py in <module>
     39 import sys as _sys
     40 
---> 41 from tensorflow.python.tools import module_util as _module_util
     42 from tensorflow.python.util.lazy_loader import LazyLoader as _LazyLoader
     43 

~\AppData\Local\Continuum\miniconda3\envs\pya\lib\site-packages\tensorflow\python\__init__.py in <module>
     48 import numpy as np
     49 
---> 50 from tensorflow.python import pywrap_tensorflow
     51 from tensorflow.python import _pywrap_utils
     52 from tensorflow.python import _pywrap_tfprof

~\AppData\Local\Continuum\miniconda3\envs\pya\lib\site-packages\tensorflow\python\pywrap_tensorflow.py in <module>
     67 for some common reasons and solutions.  Include the entire stack trace
     68 above this error message when asking for help.""" % traceback.format_exc()
---> 69   raise ImportError(msg)
     70 
     71 # pylint: enable=wildcard-import,g-import-not-at-top,unused-import,line-too-long

ImportError: Traceback (most recent call last):
  File "C:\Users\myname\AppData\Local\Continuum\miniconda3\envs\pya\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\myname\AppData\Local\Continuum\miniconda3\envs\pya\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\myname\AppData\Local\Continuum\miniconda3\envs\pya\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\myname\AppData\Local\Continuum\miniconda3\envs\pya\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\myname\AppData\Local\Continuum\miniconda3\envs\pya\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.```

**Comment by Saduf2019** [comment]
@mshmsh1234 
What is make/model of your cpu?. Does your cpu supports AVX instructions sets.Thanks!

Make sure to download the latest microsoft visual c++ redistributable from here.
 Make sure if there is a library that is in a different location/not installed on your system that cannot be loaded.Also, please follow the instructions from Tensorflow website.

Please, refer #36167 and see if it helps you. Thanks!
Also please include "import tensorflow as tf" in your code and let us know if it helps resolve the issue.

**Comment by Saduf2019** [comment]
@mshmsh1234
please update on the above comment.

**Comment by Saduf2019** [comment]
@mshmsh1234 
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
