### ISSUE TITLE
TensorFlow Lite Op Request

### ISSUE THREAD

**Issue by spate141** [tensorflow/tensorflow#36865]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (or github SHA if from source): 2.1.0

**Code** (https://www.tensorflow.org/lite/performance/post_training_quantization#weight_quantization)
```python
import tensorflow as tf
saved_model_dir = '/opt/model/my_model'
converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir)
converter.optimizations = [tf.lite.Optimize.OPTIMIZE_FOR_SIZE]
tflite_quant_model = converter.convert()
```

**Provide the text output from tflite_convert**

```
2020-02-18 19:24:22.977058: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer.so.6
2020-02-18 19:24:22.978737: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer_plugin.so.6
2020-02-18 19:24:24.105775: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-02-18 19:24:24.128869: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2300070000 Hz
2020-02-18 19:24:24.129146: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5567cc4fa770 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-02-18 19:24:24.129174: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-02-18 19:24:24.131587: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-02-18 19:24:24.187720: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-02-18 19:24:24.188106: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5567cc57c4f0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-02-18 19:24:24.188130: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Tesla M60, Compute Capability 5.2
2020-02-18 19:24:24.188279: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-02-18 19:24:24.188558: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties: 
pciBusID: 0000:00:1e.0 name: Tesla M60 computeCapability: 5.2
coreClock: 1.1775GHz coreCount: 16 deviceMemorySize: 7.44GiB deviceMemoryBandwidth: 149.31GiB/s
2020-02-18 19:24:24.188610: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-02-18 19:24:24.188649: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-02-18 19:24:24.189979: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-02-18 19:24:24.190280: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-02-18 19:24:24.192086: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-02-18 19:24:24.193471: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-02-18 19:24:24.193524: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-02-18 19:24:24.193599: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-02-18 19:24:24.193921: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-02-18 19:24:24.194179: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1697] Adding visible gpu devices: 0
2020-02-18 19:24:24.194214: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-02-18 19:24:24.541245: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1096] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-02-18 19:24:24.541292: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102]      0 
2020-02-18 19:24:24.541301: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] 0:   N 
2020-02-18 19:24:24.541515: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-02-18 19:24:24.541855: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-02-18 19:24:24.542145: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1241] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 159 MB memory) -> physical GPU (device: 0, name: Tesla M60, pci bus id: 0000:00:1e.0, compute capability: 5.2)
2020-02-18 19:24:24.589548: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorListFromTensor
2020-02-18 19:24:24.589614: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 21
2020-02-18 19:24:24.589679: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorListFromTensor
2020-02-18 19:24:24.589696: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 21
2020-02-18 19:24:24.589715: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorListReserve
2020-02-18 19:24:24.589729: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 21
2020-02-18 19:24:24.589746: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorListReserve
2020-02-18 19:24:24.589759: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 21
2020-02-18 19:24:24.589789: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: While
2020-02-18 19:24:24.589820: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 21
2020-02-18 19:24:24.589832: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 21
2020-02-18 19:24:24.589853: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: While
2020-02-18 19:24:24.589876: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 21
2020-02-18 19:24:24.589888: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 21
2020-02-18 19:24:24.589899: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorListStack
2020-02-18 19:24:24.589916: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorListStack
2020-02-18 19:24:24.592612: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 79 operators, 169 arrays (0 quantized)
2020-02-18 19:24:24.593771: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 79 operators, 169 arrays (0 quantized)
2020-02-18 19:24:24.595059: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 1: 44 operators, 121 arrays (0 quantized)
2020-02-18 19:24:24.595863: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Group bidirectional sequence lstm/rnn: 44 operators, 121 arrays (0 quantized)
2020-02-18 19:24:24.596433: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before dequantization graph transformations: 44 operators, 121 arrays (0 quantized)
2020-02-18 19:24:24.596939: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Identify nearest upsample.: 44 operators, 121 arrays (0 quantized)
2020-02-18 19:24:24.597844: I tensorflow/lite/toco/allocate_transient_arrays.cc:345] Total transient array allocated size: 18048 bytes, theoretical optimal value: 12032 bytes.
2020-02-18 19:24:24.598043: I tensorflow/lite/toco/toco_tooling.cc:471] Number of parameters: 5372617
2020-02-18 19:24:24.598566: E tensorflow/lite/toco/toco_tooling.cc:498] We are continually in the process of adding support to TensorFlow Lite for more ops. It would be helpful if you could inform us of how this conversion went by opening a github issue at https://github.com/tensorflow/tensorflow/issues/new?template=40-tflite-op-request.md
 and pasting the following:

Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. 
If those are native TensorFlow operators, you might be able to use the extended runtime by 
passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS 
when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them 
you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True 
when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: 
ADD, CONCATENATION, CONV_2D, EXPAND_DIMS, FULLY_CONNECTED, GATHER, 
MAX_POOL_2D, MUL, REDUCE_MAX, RESHAPE, REVERSE_V2, SOFTMAX, SQUEEZE, 
TRANSPOSE. Here is a list of operators for which you will need custom implementations:
TensorListFromTensor, TensorListReserve, TensorListStack, While.

Traceback (most recent call last):
  File "/opt/anaconda3/bin/toco_from_protos", line 8, in <module>
    sys.exit(main())
  File "/opt/anaconda3/lib/python3.6/site-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 93, in main
    app.run(main=execute, argv=[sys.argv[0]] + unparsed)
  File "/opt/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/opt/anaconda3/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/opt/anaconda3/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/opt/anaconda3/lib/python3.6/site-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 56, in execute
    enable_mlir_converter)
```

**Comment by spate141** [comment]
Solved:

**Updated code:**

```python
import tensorflow as tf
saved_model_dir = '/opt/model/my_model'
converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir)
converter.optimizations = [tf.lite.Optimize.OPTIMIZE_FOR_SIZE]

# update
converter.allow_custom_ops = True

tflite_quant_model = converter.convert()
```
