### ISSUE TITLE
How to quant TFLite model in int8 format

### ISSUE THREAD

**Issue by rayeh5** [tensorflow/tensorflow#36872]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
   -- x86 Linux Ubuntu 16.04
- TensorFlow installed from (source or binary):
   -- binary
- Tensorflow version (commit SHA if source):
   -- 2.1.0
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.):
   -- x86 Linux

**Describe the problem**
   -- How to quant TF model to int8 format so that I can use CMSIS-NN int8 APIs
**Please provide the exact sequence of commands/steps when you ran into the problem**
   -- I try the toco command:
       toco --saved_model_dir /home/swai01/tfl-m_speech_model --output_file=./conv_int8.tflite --input_shapes=1,49,40,1 --input_arrays=Reshape_2 --output_arrays='labels_softmax' --inference_type=QUANTIZED_INT8 --mean_values=0 --std_dev_values=9.8077
      but got the error message:
          ValueError: This converter can only convert a single ConcreteFunction. Converting multiple functions is under development.
   Thanks for your time.

ruey-an

**Comment by amahendrakar** [comment]
@rayeh5,
Could you please check [this](https://github.com/tensorflow/tensorflow/issues/34350#issuecomment-576786774) comment on a similar issue and let us know if it works. Thanks!

**Comment by rayeh5** [comment]
@amahendrakar, thanks for your feedback.
The model file is trained via tensorflow/examples/speech_commands.
I try the following python code:
----------
import tensorflow as tf
model = tf.saved_model.load('/home/swai01/tfl-m_speech_model')
print(model.signatures.keys())
concrete_func = model.signatures[tf.saved_model.DEFAULT_SERVING_SIGNATURE_DEF_KEY]
concrete_func.inputs[0].set_shape([1, 49, 40, 1])
converter = TFLiteConverter.from_concrete_functions([concrete_func])
converter.experimental_new_converter = True
converter.optimizations = [tf.lite.Optimize.OPTIMIZE_FOR_SIZE]
tflite_quant_model = converter.convert()
-----------------
I got the error message:
---------------------
KeysView(_SignatureMap({}))
Traceback (most recent call last):
  File "my_quant.py", line 4, in <module>
    concrete_func = model.signatures[tf.saved_model.DEFAULT_SERVING_SIGNATURE_DEF_KEY]
  File "/home/swai01/tf20_venv/lib/python3.5/site-packages/tensorflow_core/python/saved_model/signature_serialization.py", line 207, in __getitem__
    return self._signatures[key]
KeyError: 'serving_default'
--------------
   My main purpose is to quant a model to int8, so that I can run this model on TF-Lite micro for CMSIS-NN library.
   Thanks for your time.

ruey-an

**Comment by jvishnuvardhan** [comment]
@rayeh5 can you please share a standalone code to reproduce the issue? thanks!

**Comment by rayeh5** [comment]
[tfl-m_speech_model.zip](https://github.com/tensorflow/tensorflow/files/4233814/tfl-m_speech_model.zip)
The zip file contains checkpoint and save_model (via freeze.py) format. The my_quant.py is the script use to quant the model.
When use toco command, I got the same error message.
Thanks for your time.

ruey-an

**Comment by rayeh5** [comment]
Any suggestion for this problem?
I try to train the speech_command model (tensorflow/examples/speech_commands), and got the same error message. The followings are the python scripts:
python train.py \
 --model_architecture conv --window_size_ms 40 --window_stride_ms 20 \
 --learning_rate 0.0005,0.0001,0.00002 --how_many_training_steps 10000,10000,10000 \
 --summaries_dir work/retrain_logs --train_dir work/training \
 --data_dir=/home/swai01/rayeh/kws/wave_test_data \
 --preprocess=micro  --silence_percentage=25 --unknown_percentage=25

python freeze.py \
--model_architecture=conv --window_size_ms 40 --window_stride=20 \
--preprocess=micro  --silence_percentage=25 --unknown_percentage=25 \
--output_file=conv.pb --start_checkpoint=work/training/conv.ckpt-30000

toco \
--saved_model_dir=my_model --output_file=my_model/conv_u8.tflite \
--input_shapes=1,49,40,1 --input_arrays=Reshape_2 --output_arrays='labels_soft
max' --inference_type=QUANTIZED_UINT8 --mean_values=0 --std_dev_values=9.8077
