### ISSUE TITLE
Executing genrule //tensorflow/python/keras/api:keras_python_api_gen failed 

### ISSUE THREAD

**Issue by Tockra** [tensorflow/tensorflow#36903]
**System information**
- Dockerimage: nvidia/cuda-ppc64le:10.1-cudnn7-devel-ubuntu18.04
- TensorFlow installed from (source or binary): source
- TensorFlow version: r2.1 (branch)
- Python version: Python 3.6.9 (also setted /usr/bin/python3 while ./configure)
- Installed using virtualenv? pip? conda?: no, github repository and build
- Bazel version (if compiling from source): 0.27
- GCC/Compiler version (if compiling from source): gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
- CUDA/cuDNN version: 10.1, 7.0 
- GPU model and memory: compute capability 6.0 nvidia tesla P100, GPU Memory 12GB, RAM 256GB

While building it throws a error.
```bash
 bazel build --config=opt --config=cuda --discard_analysis_cache --nokeep_state_after_build --notrack_incremental_state //tensorflow/tools/pip_package:build_pip_package
```
Error:
```bash
ERROR: /root/tensorflow/tensorflow/python/keras/api/BUILD:102:1: Executing genrule //tensorflow/python/keras/api:keras_python_api_gen failed (Exit 1)
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_1_keras_python_api_gen.runfiles/org_tensorflow/tensorflow/python/tools/api/generator/create_python_api.py", line 777, in <module>
    main()
  File "/root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_1_keras_python_api_gen.runfiles/org_tensorflow/tensorflow/python/tools/api/generator/create_python_api.py", line 756, in main
    importlib.import_module(package)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_1_keras_python_api_gen.runfiles/org_tensorflow/tensorflow/python/keras/datasets/imdb.py", line 25, in <module>
    from tensorflow.python.keras.preprocessing.sequence import _remove_long_seq
  File "/root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_1_keras_python_api_gen.runfiles/org_tensorflow/tensorflow/python/keras/preprocessing/__init__.py", line 23, in <module>
    import keras_preprocessing
ModuleNotFoundError: No module named 'keras_preprocessing'
----------------
Note: The failure of target //tensorflow/python/keras/api:create_tensorflow.python_api_1_keras_python_api_gen (with exit code 1) may have been caused by the fact that it is a Python 2 program that was built in the host configuration, which uses Python 3. You can change the host configuration (for the entire build) to instead use Python 2 by setting --host_force_python=PY2.

If this error started occurring in Bazel 0.27 and later, it may be because the Python toolchain now enforces that targets analyzed as PY2 and PY3 run under a Python 2 and Python 3 interpreter, respectively. See https://github.com/bazelbuild/bazel/issues/7899 for more information.
----------------
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /root/tensorflow/tensorflow/tools/pip_package/BUILD:49:1 Executing genrule //tensorflow/python/keras/api:keras_python_api_gen failed (Exit 1)
INFO: Elapsed time: 480.332s, Critical Path: 366.40s
INFO: 2627 processes: 2627 local.
FAILED: Build did NOT complete successfully
```

**Comment by DFuller134** [comment]
@Tockra : What was your solution to this issue?

**Comment by hansi-b** [comment]
I get the same error trying to build tf2 with gpu from sources using a Python3 venv.

**Comment by Tockra** [comment]
It was stupid. I hadn't install "keras_preprocessing".

**Comment by minsky-1** [comment]
> It was stupid. I hadn't install "keras_preprocessing".

I have the same error, and keras_preprocessing is in tensorflow/python/keras/preprocessing/
Because when I  ls this directory I get:

 ls tensorflow/python/keras/preprocessing/
BUILD              image_pipeline_test.py  image_test.py  sequence.py       text.py
image_pipeline.py  image.py                __init__.py    sequence_test.py  text_test.py


What do you mean you hadn't installed?

**Comment by minsky-1** [comment]
The error I got is actually:
-----------------------------------------------------------------------------------------------------------------------
/home/msky/tensorflow/tensorflow/python/keras/api/BUILD:104:1: Executing genrule //tensorflow/python/keras/api:keras_python_api_gen failed (Exit 1)
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/349bb11648069f0a9b13bec970961d74/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen.runfiles/org_tensorflow/tensorflow/python/tools/api/generator/create_python_api.py", line 776, in <module>
    main()
  File "/root/.cache/bazel/_bazel_root/349bb11648069f0a9b13bec970961d74/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen.runfiles/org_tensorflow/tensorflow/python/tools/api/generator/create_python_api.py", line 755, in main
    importlib.import_module(package)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/.cache/bazel/_bazel_root/349bb11648069f0a9b13bec970961d74/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen.runfiles/org_tensorflow/tensorflow/python/keras/datasets/imdb.py", line 25, in <module>
    from tensorflow.python.keras.preprocessing.sequence import _remove_long_seq
  File "/root/.cache/bazel/_bazel_root/349bb11648069f0a9b13bec970961d74/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen.runfiles/org_tensorflow/tensorflow/python/keras/preprocessing/__init__.py", line 23, in <module>
    import keras_preprocessing
ModuleNotFoundError: No module named 'keras_preprocessing'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /home/msnky/tensorflow/tensorflow/tools/pip_package/BUILD:62:1 Executing genrule //tensorflow/python/keras/api:keras_python_api_gen_compat_v2 failed (Exit 1)
INFO: Elapsed time: 56.888s, Critical Path: 40.18s

I have bazel 2.0, and python3.6.10. 

Could you please get me an idea of what is the problem?

**Comment by amahendrakar** [comment]
@minsky-1,
Could you please submit a new issue from [this link](https://github.com/tensorflow/tensorflow/issues/new/choose) and fill in the template, so that we can track the issue there. Thanks!
