### ISSUE TITLE
typo or bug in documentation

### ISSUE THREAD

**Issue by tsgouros** [tensorflow/tensorflow#36940]
https://www.tensorflow.org/tutorials/quickstart/advanced

This page has an example class "MyModel".  When it is invoked further down the page, it is invoked with a "training" keyword argument that does not appear to be in the definition.

Slavishly copying the code produces this error:

```
TypeError: in converted code:

    tf/tutorial.py:61 train_step *
        predictions = model(images, training=True)
    /usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/engine/base_layer.py:634 __call__
        outputs = call_fn(inputs, *args, **kwargs)

    TypeError: tf__call() got an unexpected keyword argument 'training'
```

**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): NO, this is as appears on doc page.
Using singularity, with docker://tensorflow/tensorflow.

When I remove the 'training' keyword, the operation executes, though I don't know if it's going to come out correctly or not. What is it supposed to do?

```
Singularity tf-py3.simg:~/projects> python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)" 
('v1.14.0-rc1-22-gaf24dc91b5', '1.14.0')
Singularity tf-py3.simg:~/projects> 
```

- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if
the issue happens on mobile device: 
- TensorFlow installed from (source or
binary): - TensorFlow version (use command below): 
- Python version: - Bazel
version (if compiling from source):
- GCC/Compiler version (if compiling from
source): 
- CUDA/cuDNN version: - GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

**Describe the expected behavior**

**Standalone code to reproduce the issue** 
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by saikumarchalla** [comment]
@tsgouros  Was able to run the code with out any errors. Please find the [gist](https://colab.sandbox.google.com/gist/saikumarchalla/6779bea9e27bb17b304c26502c88ca23/advanced.ipynb) here.Thanks!

**Comment by tsgouros** [comment]
Thank you. Yes, it runs in that gist, but it still doesn't run for me. 

I constructed the script by copying and pasting, so I'm relatively sure there aren't typos. But more important, when I examine the gist code, I'm unable to see where the 'training' keyword is defined for the example model class. Perhaps that's part of the parent 'Model' class? But it isn't mentioned here: [https://keras.io/models/model/](https://keras.io/models/model/). Is there some version of Keras:Model that has this defined?

More detail here: I get some ominous warnings when I follow the instructions carefully. To me, they don't seem relevant to this problem, which just seems like a basic Python coding issue, but maybe they contain clues?

```
>>> class MyModel(Model):
...     def __init__(self):
...             super(MyModel, self).__init__()
...             self.conv1 = Conv2D(32, 3, activation='relu')
...             self.flatten = Flatten()
...             self.d1 = Dense(128, activation='relu')
...             self.d2 = Dense(10)
...     def call(self,x):
...             x = self.conv1(x)
...             x = self.flatten(x)
...             x=self.d1(x)
...             return self.d2(x)
... 
>>> (x_train, y_train), (x_test, y_test) = mnist.load_data()
>>> x_train, x_test = x_train / 255.0, x_test / 255.0
>>> x_train = x_train[..., tf.newaxis]
>>> x_test = x_test[..., tf.newaxis]
>>> train_ds = tf.data.Dataset.from_tensor_slices((x_train, y_train)).shuffle(10000).batch(32)
>>> test_ds = tf.data.Dataset.from_tensor_slices((x_test, y_test)).batch(32)
>>> model=MyModel()
WARNING: Logging before flag parsing goes to stderr.
W0224 08:39:02.590373 140374803265344 deprecation.py:506] From /usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/init_ops.py:1251: calling __init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
>>> train_ds
<DatasetV1Adapter shapes: ((?, 28, 28, 1), (?,)), types: (tf.float64, tf.uint8)>
>>> for images, labels in train_ds:
...     p = model(images, training=True)
... 
W0224 08:43:44.608691 140374803265344 ag_logging.py:145] Entity <bound method MyModel.call of <__main__.MyModel object at 0x7fab8436f910>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method MyModel.call of <__main__.MyModel object at 0x7fab8436f910>>: ValueError: Unable to locate the source code of <bound method MyModel.call of <__main__.MyModel object at 0x7fab8436f910>>. Note that functions defined in certain environments, like the interactive Python shell do not expose their source code. If that is the case, you should to define them in a .py source file. If you are certain the code is graph-compatible, wrap the call using @tf.autograph.do_not_convert. Original error: could not get source code
WARNING: Entity <bound method MyModel.call of <__main__.MyModel object at 0x7fab8436f910>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method MyModel.call of <__main__.MyModel object at 0x7fab8436f910>>: ValueError: Unable to locate the source code of <bound method MyModel.call of <__main__.MyModel object at 0x7fab8436f910>>. Note that functions defined in certain environments, like the interactive Python shell do not expose their source code. If that is the case, you should to define them in a .py source file. If you are certain the code is graph-compatible, wrap the call using @tf.autograph.do_not_convert. Original error: could not get source code
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 634, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/autograph/impl/api.py", line 149, in wrapper
    raise e.ag_error_metadata.to_exception(type(e))
TypeError: in converted code:


    TypeError: call() got an unexpected keyword argument 'training'

>>> 
```

I did try this as a script, with the verbosity set to 10:

```
Singularity tf-py3.simg:~/projects/tf> export AUTOGRAPH_VERBOSITY=10
Singularity tf-py3.simg:~/projects/tf> ./tutorial.py
WARNING: Logging before flag parsing goes to stderr.
W0224 08:48:42.010809 140518177331008 deprecation.py:506] From /usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/init_ops.py:1251: calling __init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
2020-02-24 08:48:42.061510: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2600075000 Hz
2020-02-24 08:48:42.065871: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x56487af63e70 executing computations on platform Host. Devices:
2020-02-24 08:48:42.065931: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
2020-02-24 08:48:42.082351: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1412] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set.  If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.
Traceback (most recent call last):
  File "./tutorial.py", line 89, in <module>
    train_step(images, labels)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/eager/def_function.py", line 414, in __call__
    self._initialize(args, kwds, add_initializers_to=initializer_map)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/eager/def_function.py", line 357, in _initialize
    *args, **kwds))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/eager/function.py", line 1349, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/eager/function.py", line 1652, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/eager/function.py", line 1545, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/func_graph.py", line 715, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/eager/def_function.py", line 307, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/func_graph.py", line 705, in wrapper
    raise e.ag_error_metadata.to_exception(type(e))
TypeError: in converted code:

    ./tutorial.py:61 train_step *
        predictions = model(images, training=True)
    /usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/engine/base_layer.py:634 __call__
        outputs = call_fn(inputs, *args, **kwargs)

    TypeError: tf__call() got an unexpected keyword argument 'training'
```

**Comment by saikumarchalla** [comment]
@tsgouros  I tried to execute the code which you have provided but not getting any errors. please find the [gist](https://colab.sandbox.google.com/gist/saikumarchalla/4d99177cc6473ce579616e4adab61ba8/36940.ipynb) here.Thanks!

**Comment by tsgouros** [comment]
Fair enough, but the error I'm getting is very specific. The 'training' keyword argument that's tripping me up is not defined in this example code, so it must be inherited from the Model object of Keras, no? How would I check for a version mismatch? I don't see it in the Keras documentation I linked to. Where did it come from? The docker tensorflow thing equipped me with Python 2.7.15. Could that be an issue? 

Obviously the code runs for some people. Any clues about why it might not run for me are welcome. Thanks.

**Comment by gowthamkpr** [comment]
Now I get it, you are using Tensorflow 1.14 for this tutorial. Please use tensorflow 2.0 as this tutorial is supposed to run in Tensorflow 2.0.

To check your tensorflow version, please use 
```
import tensorflow as tf
tf.__version__
```
Closing this issue as it has been resolved.

**Comment by tsgouros** [comment]
Thank you, that does appear to be the problem. Fixed now.
