### ISSUE TITLE
Fail to build from source 

### ISSUE THREAD

**Issue by AlvinChen13** [tensorflow/tensorflow#3694]
Hi all,

I just try to build tensorflow from source according to the steps described step by step, but I get the following error, anyone can help on it?
Thanks!

alvin@hal-dev:~/tensorflow-r0.9$ bazel build -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer
Found stale PID file (pid=29629). Server probably died abruptly, continuing...
.
unexpected pipe read status: Connection refused
Server presumed dead. Now printing '/home/alvin/.cache/bazel/_bazel_alvin/098c27509f757cf22af83c9a7d1d8ec7/server/jvm.out':
java.lang.AssertionError: java.security.NoSuchAlgorithmException: MD5 MessageDigest not available
	at com.google.common.hash.MessageDigestHashFunction.getMessageDigest(MessageDigestHashFunction.java:79)
	at com.google.common.hash.MessageDigestHashFunction.<init>(MessageDigestHashFunction.java:40)
	at com.google.common.hash.Hashing$Md5Holder.<clinit>(Hashing.java:191)
	at com.google.common.hash.Hashing.md5(Hashing.java:187)
	at com.google.devtools.build.lib.analysis.BlazeDirectories.checkMD5(BlazeDirectories.java:95)
	at com.google.devtools.build.lib.analysis.BlazeDirectories.<init>(BlazeDirectories.java:74)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.newRuntime(BlazeRuntime.java:926)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.createBlazeRPCServer(BlazeRuntime.java:781)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.serverMain(BlazeRuntime.java:726)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.main(BlazeRuntime.java:519)
	at com.google.devtools.build.lib.bazel.BazelMain.main(BazelMain.java:56)
Caused by: java.security.NoSuchAlgorithmException: MD5 MessageDigest not available
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:159)
	at java.security.Security.getImpl(Security.java:695)
	at java.security.MessageDigest.getInstance(MessageDigest.java:167)
	at com.google.common.hash.MessageDigestHashFunction.getMessageDigest(MessageDigestHashFunction.java:77)
	... 10 more

**Comment by girving** [comment]
This looks like a bazel issue.  @damienmg Do you know what's going wrong?

**Comment by AlvinChen13** [comment]
while bazel is running, will it connect to google server?

**Comment by girving** [comment]
@AlvinChen13 Bazel uses a client/server architecture for distributed builds, but both the client and the server are on your local machine in this case.

**Comment by AlvinChen13** [comment]
@girving Is that to say I need run a bazel server in my local firstly? But after I install bazel, I haven't got server application.

**Comment by girving** [comment]
@AlvinChen13 No, running bazel starts both client and server.  This seems like a bazel issue, which is why I'm checking with @damienmg.

**Comment by AlvinChen13** [comment]
Anyone can help on it? Very appreciated!

**Comment by kchodorow** [comment]
This is a Bazel issue, tracking on https://github.com/bazelbuild/bazel/issues/1638.

**Comment by AlvinChen13** [comment]
Solve the issue by re-install the JDK instead of deb.
