### ISSUE TITLE
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

### ISSUE THREAD

**Issue by kurisa12** [tensorflow/tensorflow#36957]
#Import the libraries
import tensorflow as tf

**System information**

OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 64-bit
TensorFlow installed from (source or binary): pip package manager (20.0.2)
TensorFlow version (use command below): 2.1.0
Python version: Python 3.6.8 64-bit (python-3.6.8-amd64)
CUDA/cuDNN version: No GPU
GPU model and memory: No GPU
You can collect some of this information using our environment capture script
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**
Just to test after installation, I tried importing Tensorflow in Python, but got an unexpected error (see Code section) .

**Describe the expected behavior**
Needs fixing the problem......

E:\Development\iShaft\iShaft-Trading-Bot\iShaft.Python>python prototype.py
C:\Program Files (x86)\Python36\lib\site-packages\pandas_datareader\compat\__init__.py:7: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  from pandas.util.testing import assert_frame_equal

E:\Development\iShaft\iShaft-Trading-Bot\iShaft.Python>python prototype.py
C:\Program Files (x86)\Python36\lib\site-packages\pandas_datareader\compat\__init__.py:7: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  from pandas.util.testing import assert_frame_equal
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python36\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Program Files (x86)\Python36\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Program Files (x86)\Python36\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Program Files (x86)\Python36\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Program Files (x86)\Python36\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "prototype.py", line 12, in <module>
    from tensorflow import keras
  File "C:\Program Files (x86)\Python36\lib\site-packages\tensorflow\__init__.py", line 101, in <module>
    from tensorflow_core import *
  File "C:\Program Files (x86)\Python36\lib\site-packages\tensorflow_core\__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Program Files (x86)\Python36\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\Program Files (x86)\Python36\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "C:\Program Files (x86)\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Program Files (x86)\Python36\lib\site-packages\tensorflow_core\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Program Files (x86)\Python36\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Program Files (x86)\Python36\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Program Files (x86)\Python36\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Program Files (x86)\Python36\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Program Files (x86)\Python36\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Program Files (x86)\Python36\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by kurisa12** [comment]
**Install log:**

E:\Development\iShaft\iShaft-Trading-Bot\iShaft.Python>pip3 install tensorflow
Collecting tensorflow
  Using cached tensorflow-2.1.0-cp36-cp36m-win_amd64.whl (355.9 MB)
Requirement already satisfied: tensorflow-estimator<2.2.0,>=2.1.0rc0 in c:\program files (x86)\python37\lib\site-packages (from tensorflow) (2.1.0)
Requirement already satisfied: numpy<2.0,>=1.16.0 in c:\program files (x86)\python37\lib\site-packages (from tensorflow) (1.18.1)
Requirement already satisfied: grpcio>=1.8.6 in c:\program files (x86)\python37\lib\site-packages (from tensorflow) (1.27.2)
Requirement already satisfied: opt-einsum>=2.3.2 in c:\program files (x86)\python37\lib\site-packages (from tensorflow) (3.1.0)
Requirement already satisfied: keras-applications>=1.0.8 in c:\program files (x86)\python37\lib\site-packages (from tensorflow) (1.0.8)
Requirement already satisfied: wrapt>=1.11.1 in c:\program files (x86)\python37\lib\site-packages (from tensorflow) (1.12.0)
Requirement already satisfied: six>=1.12.0 in c:\program files (x86)\python37\lib\site-packages (from tensorflow) (1.14.0)
Requirement already satisfied: google-pasta>=0.1.6 in c:\program files (x86)\python37\lib\site-packages (from tensorflow) (0.1.8)
Requirement already satisfied: protobuf>=3.8.0 in c:\program files (x86)\python37\lib\site-packages (from tensorflow) (3.11.3)
Requirement already satisfied: scipy==1.4.1; python_version >= "3" in c:\program files (x86)\python37\lib\site-packages (from tensorflow) (1.4.1)
Requirement already satisfied: gast==0.2.2 in c:\program files (x86)\python37\lib\site-packages (from tensorflow) (0.2.2)
Requirement already satisfied: astor>=0.6.0 in c:\program files (x86)\python37\lib\site-packages (from tensorflow) (0.8.1)
Requirement already satisfied: tensorboard<2.2.0,>=2.1.0 in c:\program files (x86)\python37\lib\site-packages (from tensorflow) (2.1.0)
Requirement already satisfied: wheel>=0.26; python_version >= "3" in c:\program files (x86)\python37\lib\site-packages (from tensorflow) (0.34.2)
Requirement already satisfied: keras-preprocessing>=1.1.0 in c:\program files (x86)\python37\lib\site-packages (from tensorflow) (1.1.0)
Requirement already satisfied: absl-py>=0.7.0 in c:\program files (x86)\python37\lib\site-packages (from tensorflow) (0.9.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\program files (x86)\python37\lib\site-packages (from tensorflow) (1.1.0)
Requirement already satisfied: h5py in c:\program files (x86)\python37\lib\site-packages (from keras-applications>=1.0.8->tensorflow) (2.10.0)
Requirement already satisfied: setuptools in c:\program files (x86)\python37\lib\site-packages (from protobuf>=3.8.0->tensorflow) (45.2.0)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in c:\program files (x86)\python37\lib\site-packages (from tensorboard<2.2.0,>=2.1.0->tensorflow) (0.4.1)
Requirement already satisfied: google-auth<2,>=1.6.3 in c:\program files (x86)\python37\lib\site-packages (from tensorboard<2.2.0,>=2.1.0->tensorflow) (1.11.2)
Requirement already satisfied: werkzeug>=0.11.15 in c:\program files (x86)\python37\lib\site-packages (from tensorboard<2.2.0,>=2.1.0->tensorflow) (1.0.0)
Requirement already satisfied: requests<3,>=2.21.0 in c:\program files (x86)\python37\lib\site-packages (from tensorboard<2.2.0,>=2.1.0->tensorflow) (2.23.0)
Requirement already satisfied: markdown>=2.6.8 in c:\program files (x86)\python37\lib\site-packages (from tensorboard<2.2.0,>=2.1.0->tensorflow) (3.2.1)
Requirement already satisfied: requests-oauthlib>=0.7.0 in c:\program files (x86)\python37\lib\site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.2.0,>=2.1.0->tensorflow) (1.3.0)
Requirement already satisfied: rsa<4.1,>=3.1.4 in c:\program files (x86)\python37\lib\site-packages (from google-auth<2,>=1.6.3->tensorboard<2.2.0,>=2.1.0->tensorflow) (4.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\program files (x86)\python37\lib\site-packages (from google-auth<2,>=1.6.3->tensorboard<2.2.0,>=2.1.0->tensorflow) (0.2.8)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in c:\program files (x86)\python37\lib\site-packages (from google-auth<2,>=1.6.3->tensorboard<2.2.0,>=2.1.0->tensorflow) (4.0.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\program files (x86)\python37\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.2.0,>=2.1.0->tensorflow) (2019.11.28)
Requirement already satisfied: chardet<4,>=3.0.2 in c:\program files (x86)\python37\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.2.0,>=2.1.0->tensorflow) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\program files (x86)\python37\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.2.0,>=2.1.0->tensorflow) (1.25.8)
Requirement already satisfied: idna<3,>=2.5 in c:\program files (x86)\python37\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.2.0,>=2.1.0->tensorflow) (2.9)
Requirement already satisfied: oauthlib>=3.0.0 in c:\program files (x86)\python37\lib\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.2.0,>=2.1.0->tensorflow) (3.1.0)
Requirement already satisfied: pyasn1>=0.1.3 in c:\program files (x86)\python37\lib\site-packages (from rsa<4.1,>=3.1.4->google-auth<2,>=1.6.3->tensorboard<2.2.0,>=2.1.0->tensorflow) (0.4.8)
Installing collected packages: tensorflow
Successfully installed tensorflow-2.1.0
