### ISSUE TITLE
 doesn't support control flow ops:

### ISSUE THREAD

**Issue by yuanlida** [tensorflow/tensorflow#36964]
**System information**
- OS Platform and Distribution (MAC 10.15.3 (19D76)):
- TensorFlow installed from (binary):
- TensorFlow version (1.15.0):

**Provide the text output from tflite_convert**

```
# Copy and paste here
```

**Standalone code to reproduce the issue** 
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

Also, please include a link to a GraphDef or the model if possible.

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem.
If including tracebacks, please include the full traceback. Large logs and files
should be attached.
2020-02-22 01:14:04.085039: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-02-22 01:14:04.094983: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fa5fe943ce0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-02-22 01:14:04.094997: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
WARNING:tensorflow:From /Users/lidayuan/opt/anaconda3/envs/py371/lib/python3.7/site-packages/tensorflow_core/lite/python/convert_saved_model.py:60: load (from tensorflow.python.saved_model.loader_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.loader.load or tf.compat.v1.saved_model.load. There will be a new function for importing SavedModels in Tensorflow 2.0.
W0222 01:14:04.095364 4577779136 deprecation.py:323] From /Users/lidayuan/opt/anaconda3/envs/py371/lib/python3.7/site-packages/tensorflow_core/lite/python/convert_saved_model.py:60: load (from tensorflow.python.saved_model.loader_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.loader.load or tf.compat.v1.saved_model.load. There will be a new function for importing SavedModels in Tensorflow 2.0.
INFO:tensorflow:Restoring parameters from ./model/variables/variables
I0222 01:14:04.311928 4577779136 saver.py:1284] Restoring parameters from ./model/variables/variables
INFO:tensorflow:The given SavedModel MetaGraphDef contains SignatureDefs with the following keys: {'serving_default'}
I0222 01:14:04.437039 4577779136 convert_saved_model.py:80] The given SavedModel MetaGraphDef contains SignatureDefs with the following keys: {'serving_default'}
INFO:tensorflow:input tensors info: 
I0222 01:14:04.437269 4577779136 convert_saved_model.py:99] input tensors info: 
INFO:tensorflow:Tensor's key in saved_model's tensor_map: word_ids
I0222 01:14:04.437363 4577779136 convert_saved_model.py:41] Tensor's key in saved_model's tensor_map: word_ids
INFO:tensorflow: tensor name: word_ids:0, shape: (-1, 64), type: DT_INT32
I0222 01:14:04.437431 4577779136 convert_saved_model.py:43]  tensor name: word_ids:0, shape: (-1, 64), type: DT_INT32
INFO:tensorflow:Tensor's key in saved_model's tensor_map: labels
I0222 01:14:04.437486 4577779136 convert_saved_model.py:41] Tensor's key in saved_model's tensor_map: labels
INFO:tensorflow: tensor name: labels:0, shape: (-1, 64), type: DT_INT32
I0222 01:14:04.437530 4577779136 convert_saved_model.py:43]  tensor name: labels:0, shape: (-1, 64), type: DT_INT32
INFO:tensorflow:Tensor's key in saved_model's tensor_map: sequence_lengths
I0222 01:14:04.437580 4577779136 convert_saved_model.py:41] Tensor's key in saved_model's tensor_map: sequence_lengths
INFO:tensorflow: tensor name: sequence_lengths:0, shape: (-1), type: DT_INT32
I0222 01:14:04.437623 4577779136 convert_saved_model.py:43]  tensor name: sequence_lengths:0, shape: (-1), type: DT_INT32
INFO:tensorflow:output tensors info: 
I0222 01:14:04.437661 4577779136 convert_saved_model.py:101] output tensors info: 
INFO:tensorflow:Tensor's key in saved_model's tensor_map: labels_softmax_
I0222 01:14:04.437716 4577779136 convert_saved_model.py:41] Tensor's key in saved_model's tensor_map: labels_softmax_
INFO:tensorflow: tensor name: Cast:0, shape: (-1, -1), type: DT_INT32
I0222 01:14:04.437761 4577779136 convert_saved_model.py:43]  tensor name: Cast:0, shape: (-1, -1), type: DT_INT32
INFO:tensorflow:Restoring parameters from ./model/variables/variables
I0222 01:14:04.642255 4577779136 saver.py:1284] Restoring parameters from ./model/variables/variables
2020-02-22 01:14:04.806073: I tensorflow/core/grappler/devices.cc:60] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0 (Note: TensorFlow was not compiled with CUDA support)
2020-02-22 01:14:04.806140: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2020-02-22 01:14:04.847576: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:786] Optimization results for grappler item: graph_to_optimize
2020-02-22 01:14:04.847595: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:788]   function_optimizer: function_optimizer did nothing. time = 0.003ms.
2020-02-22 01:14:04.847599: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:788]   function_optimizer: function_optimizer did nothing. time = 0ms.
WARNING:tensorflow:From /Users/lidayuan/opt/anaconda3/envs/py371/lib/python3.7/site-packages/tensorflow_core/lite/python/util.py:249: convert_variables_to_constants (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.convert_variables_to_constants`
W0222 01:14:04.920840 4577779136 deprecation.py:323] From /Users/lidayuan/opt/anaconda3/envs/py371/lib/python3.7/site-packages/tensorflow_core/lite/python/util.py:249: convert_variables_to_constants (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.convert_variables_to_constants`
WARNING:tensorflow:From /Users/lidayuan/opt/anaconda3/envs/py371/lib/python3.7/site-packages/tensorflow_core/python/framework/graph_util_impl.py:277: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.extract_sub_graph`
W0222 01:14:04.921000 4577779136 deprecation.py:323] From /Users/lidayuan/opt/anaconda3/envs/py371/lib/python3.7/site-packages/tensorflow_core/python/framework/graph_util_impl.py:277: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.extract_sub_graph`
INFO:tensorflow:Froze 8 variables.
I0222 01:14:04.977573 4577779136 graph_util_impl.py:334] Froze 8 variables.
INFO:tensorflow:Converted 8 variables to const ops.
I0222 01:14:05.001580 4577779136 graph_util_impl.py:394] Converted 8 variables to const ops.
2020-02-22 01:14:05.044424: I tensorflow/core/grappler/devices.cc:60] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0 (Note: TensorFlow was not compiled with CUDA support)
2020-02-22 01:14:05.044509: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2020-02-22 01:14:05.068744: E tensorflow/core/grappler/grappler_item_builder.cc:650] Fetch node labels doesn't exist in graph
Traceback (most recent call last):
  File "/Users/lidayuan/opt/anaconda3/envs/py371/bin/tflite_convert", line 8, in <module>
    sys.exit(main())
  File "/Users/lidayuan/opt/anaconda3/envs/py371/lib/python3.7/site-packages/tensorflow_core/lite/python/tflite_convert.py", line 515, in main
    app.run(main=run_main, argv=sys.argv[:1])
  File "/Users/lidayuan/opt/anaconda3/envs/py371/lib/python3.7/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/Users/lidayuan/opt/anaconda3/envs/py371/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/Users/lidayuan/opt/anaconda3/envs/py371/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/Users/lidayuan/opt/anaconda3/envs/py371/lib/python3.7/site-packages/tensorflow_core/lite/python/tflite_convert.py", line 511, in run_main
    _convert_tf1_model(tflite_flags)
  File "/Users/lidayuan/opt/anaconda3/envs/py371/lib/python3.7/site-packages/tensorflow_core/lite/python/tflite_convert.py", line 199, in _convert_tf1_model
    output_data = converter.convert()
  File "/Users/lidayuan/opt/anaconda3/envs/py371/lib/python3.7/site-packages/tensorflow_core/lite/python/lite.py", line 983, in convert
    **converter_kwargs)
  File "/Users/lidayuan/opt/anaconda3/envs/py371/lib/python3.7/site-packages/tensorflow_core/lite/python/convert.py", line 449, in toco_convert_impl
    enable_mlir_converter=enable_mlir_converter)
  File "/Users/lidayuan/opt/anaconda3/envs/py371/lib/python3.7/site-packages/tensorflow_core/lite/python/convert.py", line 200, in toco_convert_protos
    raise ConverterError("See console for info.\n%s\n%s\n" % (stdout, stderr))
tensorflow.lite.python.convert.ConverterError: See console for info.
2020-02-22 01:14:07.404666: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-02-22 01:14:07.404703: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-02-22 01:14:07.404722: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-02-22 01:14:07.404731: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-02-22 01:14:07.404784: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-02-22 01:14:07.404792: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-02-22 01:14:07.404812: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-02-22 01:14:07.404822: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-02-22 01:14:07.404938: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayV3
2020-02-22 01:14:07.404951: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2020-02-22 01:14:07.404960: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayV3
2020-02-22 01:14:07.404965: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2020-02-22 01:14:07.404974: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-02-22 01:14:07.405028: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-02-22 01:14:07.405037: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-02-22 01:14:07.405041: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2020-02-22 01:14:07.405047: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-02-22 01:14:07.405050: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2020-02-22 01:14:07.405065: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayScatterV3
2020-02-22 01:14:07.405086: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayV3
2020-02-22 01:14:07.405091: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2020-02-22 01:14:07.405099: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayV3
2020-02-22 01:14:07.405104: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2020-02-22 01:14:07.405111: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-02-22 01:14:07.405140: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-02-22 01:14:07.405159: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-02-22 01:14:07.405168: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-02-22 01:14:07.405172: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2020-02-22 01:14:07.405178: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-02-22 01:14:07.405182: I tensorflow/lite/toco/import_tensorflow.cc:193] Unsupported data type in placeholder op: 20
2020-02-22 01:14:07.405196: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayScatterV3
2020-02-22 01:14:07.405204: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-02-22 01:14:07.405211: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-02-22 01:14:07.405228: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-02-22 01:14:07.405249: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-02-22 01:14:07.405266: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-02-22 01:14:07.405274: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-02-22 01:14:07.405287: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-02-22 01:14:07.405300: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-02-22 01:14:07.405324: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-02-22 01:14:07.405337: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-02-22 01:14:07.405351: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Enter
2020-02-22 01:14:07.405362: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: LoopCond
2020-02-22 01:14:07.405388: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: LoopCond
2020-02-22 01:14:07.405399: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Exit
2020-02-22 01:14:07.405442: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayReadV3
2020-02-22 01:14:07.405453: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArraySizeV3
2020-02-22 01:14:07.405466: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Exit
2020-02-22 01:14:07.405506: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayReadV3
2020-02-22 01:14:07.405516: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArraySizeV3
2020-02-22 01:14:07.405535: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayGatherV3
2020-02-22 01:14:07.405573: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayGatherV3
2020-02-22 01:14:07.405683: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayWriteV3
2020-02-22 01:14:07.405704: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayWriteV3
2020-02-22 01:14:07.410286: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 238 operators, 398 arrays (0 quantized)
2020-02-22 01:14:07.411855: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After Removing unused ops pass 1: 228 operators, 382 arrays (0 quantized)
2020-02-22 01:14:07.413998: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 228 operators, 382 arrays (0 quantized)
2020-02-22 01:14:07.414578: W tensorflow/lite/toco/graph_transformations/resolve_constant_random_uniform.cc:88] RandomUniform op outputting "dropout_1/random_uniform/RandomUniform" is truly random (using /dev/random system entropy). Therefore, cannot resolve as constant. Set "seed" or "seed2" attr non-zero to fix this
2020-02-22 01:14:07.416732: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 1: 152 operators, 242 arrays (0 quantized)
2020-02-22 01:14:07.417601: W tensorflow/lite/toco/graph_transformations/resolve_constant_random_uniform.cc:88] RandomUniform op outputting "dropout_1/random_uniform/RandomUniform" is truly random (using /dev/random system entropy). Therefore, cannot resolve as constant. Set "seed" or "seed2" attr non-zero to fix this
2020-02-22 01:14:07.418410: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 2: 151 operators, 241 arrays (0 quantized)
2020-02-22 01:14:07.418796: W tensorflow/lite/toco/graph_transformations/resolve_constant_random_uniform.cc:88] RandomUniform op outputting "dropout_1/random_uniform/RandomUniform" is truly random (using /dev/random system entropy). Therefore, cannot resolve as constant. Set "seed" or "seed2" attr non-zero to fix this
2020-02-22 01:14:07.419965: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 3: 150 operators, 239 arrays (0 quantized)
2020-02-22 01:14:07.420736: W tensorflow/lite/toco/graph_transformations/resolve_constant_random_uniform.cc:88] RandomUniform op outputting "dropout_1/random_uniform/RandomUniform" is truly random (using /dev/random system entropy). Therefore, cannot resolve as constant. Set "seed" or "seed2" attr non-zero to fix this
2020-02-22 01:14:07.421508: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Group bidirectional sequence lstm/rnn: 150 operators, 239 arrays (0 quantized)
2020-02-22 01:14:07.422579: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before dequantization graph transformations: 150 operators, 239 arrays (0 quantized)
2020-02-22 01:14:07.424002: I tensorflow/lite/toco/allocate_transient_arrays.cc:345] Total transient array allocated size: 231040 bytes, theoretical optimal value: 231040 bytes.
2020-02-22 01:14:07.424390: I tensorflow/lite/toco/toco_tooling.cc:454] Number of parameters: 3808024
2020-02-22 01:14:07.424903: E tensorflow/lite/toco/toco_tooling.cc:481] We are continually in the process of adding support to TensorFlow Lite for more ops. It would be helpful if you could inform us of how this conversion went by opening a github issue at https://github.com/tensorflow/tensorflow/issues/new?template=40-tflite-op-request.md
 and pasting the following:

TensorFlow Lite currently doesn't support control flow ops: Enter, Exit, Merge, Switch. We are working on supporting control flow ops, please see github issue at https://github.com/tensorflow/tensorflow/issues/28485. Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, ARG_MAX, CAST, CONCATENATION, FULLY_CONNECTED, GATHER, GREATER_EQUAL, LESS, LOGICAL_AND, LOGISTIC, MAXIMUM, MINIMUM, MUL, PACK, RANGE, REDUCE_MAX, RESHAPE, REVERSE_SEQUENCE, SELECT, SHAPE, SPLIT, STRIDED_SLICE, TANH, TRANSPOSE. Here is a list of operators for which you will need custom implementations: LoopCond, RandomUniform, TensorArrayGatherV3, TensorArrayReadV3, TensorArrayScatterV3, TensorArraySizeV3, TensorArrayV3, TensorArrayWriteV3.
Traceback (most recent call last):
  File "/Users/lidayuan/opt/anaconda3/envs/py371/bin/toco_from_protos", line 8, in <module>
    sys.exit(main())
  File "/Users/lidayuan/opt/anaconda3/envs/py371/lib/python3.7/site-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 89, in main
    app.run(main=execute, argv=[sys.argv[0]] + unparsed)
  File "/Users/lidayuan/opt/anaconda3/envs/py371/lib/python3.7/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/Users/lidayuan/opt/anaconda3/envs/py371/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/Users/lidayuan/opt/anaconda3/envs/py371/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/Users/lidayuan/opt/anaconda3/envs/py371/lib/python3.7/site-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 52, in execute
    enable_mlir_converter)
Exception: We are continually in the process of adding support to TensorFlow Lite for more ops. It would be helpful if you could inform us of how this conversion went by opening a github issue at https://github.com/tensorflow/tensorflow/issues/new?template=40-tflite-op-request.md
 and pasting the following:

TensorFlow Lite currently doesn't support control flow ops: Enter, Exit, Merge, Switch. We are working on supporting control flow ops, please see github issue at https://github.com/tensorflow/tensorflow/issues/28485. Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, ARG_MAX, CAST, CONCATENATION, FULLY_CONNECTED, GATHER, GREATER_EQUAL, LESS, LOGICAL_AND, LOGISTIC, MAXIMUM, MINIMUM, MUL, PACK, RANGE, REDUCE_MAX, RESHAPE, REVERSE_SEQUENCE, SELECT, SHAPE, SPLIT, STRIDED_SLICE, TANH, TRANSPOSE. Here is a list of operators for which you will need custom implementations: LoopCond, RandomUniform, TensorArrayGatherV3, TensorArrayReadV3, TensorArrayScatterV3, TensorArraySizeV3, TensorArrayV3, TensorArrayWriteV3.

**Comment by Saduf2019** [comment]
@yuanlida 
Supporting control flow ops is a work in progress.
See #[28485](https://github.com/tensorflow/tensorflow/issues/28485)
