### ISSUE TITLE
SPLIT_V operator support

### ISSUE THREAD

**Issue by wwwind** [tensorflow/tensorflow#36965]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary):
- TensorFlow version (or github SHA if from source):

**Provide the text output from tflite_convert**

```
WARNING:absl:Please consider switching to use new converter by setting experimental_new_converter to true. Old converter (TOCO) is deprecated and flow will be switched on by default to use new converter soon.
Traceback (most recent call last):
  File "/home/elezhe01/work/scripts/test_gru_cell.py", line 23, in <module>
    tflite_model = converter.convert()
  File "/home/elezhe01/.local/lib/python3.6/site-packages/tensorflow/lite/python/lite.py", line 518, in convert
    self.experimental_new_quantizer)
  File "/home/elezhe01/.local/lib/python3.6/site-packages/tensorflow/lite/python/lite.py", line 262, in _calibrate_quantize_model
    inference_output_type, allow_float, enable_mlir_quantizer)
  File "/home/elezhe01/.local/lib/python3.6/site-packages/tensorflow/lite/python/optimize/calibrator.py", line 81, in calibrate_and_quantize
    enable_mlir_quantizer)
  File "/home/elezhe01/.local/lib/python3.6/site-packages/tensorflow/lite/python/optimize/tensorflow_lite_wrap_calibration_wrapper.py", line 115, in QuantizeModel
    return _tensorflow_lite_wrap_calibration_wrapper.CalibrationWrapper_QuantizeModel(self, *args)
RuntimeError: Quantization not yet supported for op: SPLIT_V
```

**Standalone code to reproduce the issue** 
```
import tensorflow as tf
import numpy as numpy

model = tf.keras.Sequential()

model.add(tf.keras.layers.Input(shape=(1, 1,)))

cell = tf.keras.layers.GRUCell(10)

model.add(tf.keras.layers.RNN(cell, unroll=True))

model.save("test_gru_cell.h5", save_format='h5')

def representative_dataset_gen():
    yield [numpy.random.uniform(low=-1, high=1, size=(1,1,1)).astype(numpy.float32)]

converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.representative_dataset = representative_dataset_gen
converter.experimental_new_converter = False

tflite_model = converter.convert()

open("test_gru_cell.tflite", 'wb').write(tflite_model)
```

**Comment by ravikyram** [comment]
@wwwind 

You need to enable tensorflow supported ops as follows.

converter.target_spec.supported_ops =[tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]

With that modification, code works without any error. Here is the [gist](https://colab.sandbox.google.com/gist/ravikyram/a06afd2784199f46e47dec66cc984f30/untitled664.ipynb) for your reference.

Please close the issue if it was resolved for you. Thanks!

**Comment by wwwind** [comment]
Thanks! This option allows to do a proper quantization, but the operator SPLIT_V uses float. There are Quantize and Dequantize nodes around it.
![split_v_quantized](https://user-images.githubusercontent.com/1513336/75151674-2d9af280-56ff-11ea-97ee-50ae5022600e.png)

**Comment by wwwind** [comment]
This PR https://github.com/tensorflow/tensorflow/pull/37016 solved my problem.
