### ISSUE TITLE
Failed to load the native Tensorflow runtime.

### ISSUE THREAD

**Issue by leoAshu** [tensorflow/tensorflow#36976]
**System information**
- OS Platform and Distribution: Windows 10 (x64), i7 - 7th Gen
- TensorFlow installed from (source or binary): installed via pip
- TensorFlow version: 2.1.0 - tensorflow-gpu
- Python version: 3.7.x
- CUDA/cuDNN version: tried with CUDA 10.1, 9.0, 9.2 with respective cuDNNs
- GPU model and memory: GTX 1050ti - 4gb

**Unable to import the tensorflow library after succesfully installing it.**

1. Installed tensorflow-gpu==2.1.0
2. Installed CUDA and cuDNN 
3. Fails to import tensorflow.

**Error Stack Trace:**

> Traceback (most recent call last):
>   File "C:\Users\ashut\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
>     from tensorflow.python.pywrap_tensorflow_internal import *
>   File "C:\Users\ashut\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
>     _pywrap_tensorflow_internal = swig_import_helper()
>   File "C:\Users\ashut\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
>     _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
>   File "C:\Users\ashut\AppData\Local\Programs\Python\Python37\lib\imp.py", line 242, in load_module
>     return load_dynamic(name, filename, file)
>   File "C:\Users\ashut\AppData\Local\Programs\Python\Python37\lib\imp.py", line 342, in load_dynamic
>     return _load(spec)
> ImportError: DLL load failed: The specified module could not be found.
> 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\ashut\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\__init__.py", line 101, in <module>
    from tensorflow_core import *
  File "C:\Users\ashut\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\ashut\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\Users\ashut\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "C:\Users\ashut\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\ashut\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\ashut\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\ashut\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\ashut\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\ashut\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\ashut\AppData\Local\Programs\Python\Python37\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\ashut\AppData\Local\Programs\Python\Python37\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by av8ramit** [comment]
I think this may be a duplicate of https://github.com/tensorflow/tensorflow/issues/36167#issuecomment-577886156

What Visual Studio are you running?

**Comment by Saduf2019** [comment]
@leoAshu Make sure to download the latest microsoft visual c++ redistributable f[rom here.](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads)
 Make sure if there is a library that is in a different location/not installed on your system that cannot be loaded.Also, please follow the instructions from [Tensorflow website](https://www.tensorflow.org/install/gpu#windows_setup).

Please, check Your CPU/Python is on 32 bits?Please, refer #[36167](https://github.com/tensorflow/tensorflow/issues/36167) and see if it helps you. Thanks!

**Comment by leoAshu** [comment]
Thanks @Saduf2019. Updating the VIsual Studio helped.
