### ISSUE TITLE
Converting unsupported operation: IdentityN

### ISSUE THREAD

**Issue by Shashankwer** [tensorflow/tensorflow#36978]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary):
- TensorFlow version (or github SHA if from source):
Google Colab
tensorflow version:'1.15.0'

**Provide the text output from tflite_convert**
File not created
```
# Copy and paste here
```
ConverterError: See console for info.
2020-02-22 12:33:05.427036: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: IdentityN
2020-02-22 12:33:05.427232: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 15 operators, 18 arrays (0 quantized)
2020-02-22 12:33:05.427378: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 15 operators, 18 arrays (0 quantized)
2020-02-22 12:33:05.427577: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 1: 2 operators, 5 arrays (0 quantized)
2020-02-22 12:33:05.427619: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Group bidirectional sequence lstm/rnn: 2 operators, 5 arrays (0 quantized)
2020-02-22 12:33:05.427646: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before dequantization graph transformations: 2 operators, 5 arrays (0 quantized)
2020-02-22 12:33:05.427684: I tensorflow/lite/toco/allocate_transient_arrays.cc:345] Total transient array allocated size: 64 bytes, theoretical optimal value: 64 bytes.
2020-02-22 12:33:05.427712: I tensorflow/lite/toco/toco_tooling.cc:439] Estimated count of arithmetic ops: 3 ops, equivalently 1 MACs
2020-02-22 12:33:05.427726: I tensorflow/lite/toco/toco_tooling.cc:454] Number of parameters: 2
2020-02-22 12:33:05.427933: E tensorflow/lite/toco/toco_tooling.cc:481] We are continually in the process of adding support to TensorFlow Lite for more ops. It would be helpful if you could inform us of how this conversion went by opening a github issue at https://github.com/tensorflow/tensorflow/issues/new?template=40-tflite-op-request.md
 and pasting the following:

Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: FULLY_CONNECTED. Here is a list of operators for which you will need custom implementations: IdentityN.
Traceback (most recent call last):
  File "/usr/local/bin/toco_from_protos", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 89, in main
    app.run(main=execute, argv=[sys.argv[0]] + unparsed)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 52, in execute
    enable_mlir_converter)

**Standalone code to reproduce the issue** 
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
https://colab.research.google.com/drive/1clPmDDCmcO7my2spTm2H_cj1PRW6YpYk#scrollTo=7x-p-H9A2EB7

x = [-1,0,1,2,3,4]
y = [-3,-1,1,3,5,7]

model = tf.keras.models.Sequential(
    [tf.keras.layers.Dense(units=1,input_shape=[1])]
)
model.compile(optimizer='sgd',loss = 'mean_squared_error')
model.fit(x,y,epochs=100)

import pathlib
#export the Saved Model

export_dir = '/content/model'
tf.saved_model.save(model,export_dir)

converter = tf.lite.TFLiteConverter.from_saved_model(export_dir)
tflite_model = converter.convert()

#Save the model

tflite_model_file = pathlib.Path('foo.tflite')
tflite_model_file.write_bytes(tflite_model)

Also, please include a link to a GraphDef or the model if possible.

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem.
If including tracebacks, please include the full traceback. Large logs and files
should be attached.

**Comment by Shashankwer** [comment]
The code worked with  tensorflow 2.0 on colab
