### ISSUE TITLE
 Here is a list of operators for which you will need custom implementations: RandomUniform.

### ISSUE THREAD

**Issue by yuanlida** [tensorflow/tensorflow#37009]
**System information**
- OS Platform and Distribution (MacOS 10.15.3):
- TensorFlow installed from (binary):
- TensorFlow version (1.15.2):

**Provide the text output from tflite_convert**

```

Some of the operators in the model are not supported by the standard TensorFlow Lite runtime and are not recognized by TensorFlow. If you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ARG_MAX, BIDIRECTIONAL_SEQUENCE_LSTM, CAST, FULLY_CONNECTED, GATHER, GREATER_EQUAL, MUL, RESHAPE. Here is a list of operators for which you will need custom implementations: RandomUniform.
Traceback (most recent call last):
  File "/Users/lidayuan/opt/anaconda3/envs/py371/bin/toco_from_protos", line 8, in <module>
    sys.exit(main())
  File "/Users/lidayuan/opt/anaconda3/envs/py371/lib/python3.7/site-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 89, in main
    app.run(main=execute, argv=[sys.argv[0]] + unparsed)
  File "/Users/lidayuan/opt/anaconda3/envs/py371/lib/python3.7/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/Users/lidayuan/opt/anaconda3/envs/py371/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/Users/lidayuan/opt/anaconda3/envs/py371/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/Users/lidayuan/opt/anaconda3/envs/py371/lib/python3.7/site-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 52, in execute
    enable_mlir_converter)
Exception: We are continually in the process of adding support to TensorFlow Lite for more ops. It would be helpful if you could inform us of how this conversion went by opening a github issue at https://github.com/tensorflow/tensorflow/issues/new?template=40-tflite-op-request.md
 and pasting the following:

Some of the operators in the model are not supported by the standard TensorFlow Lite runtime and are not recognized by TensorFlow. If you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ARG_MAX, BIDIRECTIONAL_SEQUENCE_LSTM, CAST, FULLY_CONNECTED, GATHER, GREATER_EQUAL, MUL, RESHAPE. Here is a list of operators for which you will need custom implementations: RandomUniform.

```

**Standalone code to reproduce the issue** 
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

Also, please include a link to a GraphDef or the model if possible.

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem.
If including tracebacks, please include the full traceback. Large logs and files
should be attached.

converter = tf.compat.v1.lite.TFLiteConverter.from_saved_model("../model", tag_set=[tf.saved_model.tag_constants.SERVING])
# converter.target_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,
#                         tf.lite.OpsSet.SELECT_TF_OPS]
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,
                                       tf.lite.OpsSet.SELECT_TF_OPS]

tflite_model = converter.convert()
open("./result/edison_model.tflite", "wb").write(tflite_model)

**Comment by yuanlida** [comment]
Thanks

**Comment by amahendrakar** [comment]
@yuanlida,
Could you please check [this](https://github.com/tensorflow/tensorflow/issues/35449#issuecomment-570318723) comment on a similar issue and let us know if it works. Thanks!

**Comment by yuanlida** [comment]
I think I have resolve this problem.
I added an initial value to the dropout parameter:seed.
        self.word_embeddings = tf.nn.dropout(word_embeddings, self.dropout_pl, seed=time.time())

**Comment by yuanlida** [comment]
This is the logs:
2020-02-24 16:00:00.602358: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 47 operators, 115 arrays (0 quantized)
2020-02-24 16:00:00.602705: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 47 operators, 115 arrays (0 quantized)
2020-02-24 16:00:00.602838: W tensorflow/lite/toco/graph_transformations/resolve_constant_random_uniform.cc:88] RandomUniform op outputting "dropout_1/random_uniform/RandomUniform" is truly random (using /dev/random system entropy). Therefore, cannot resolve as constant. Set "seed" or "seed2" attr non-zero to fix this
2020-02-24 16:00:00.603229: W tensorflow/lite/toco/graph_transformations/resolve_constant_random_uniform.cc:88] RandomUniform op outputting "bi-lstm/dropout/random_uniform/RandomUniform" is truly random (using /dev/random system entropy). Therefore, cannot resolve as constant. Set "seed" or "seed2" attr non-zero to fix this
2020-02-24 16:00:00.603455: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 1: 22 operators, 67 arrays (0 quantized)
2020-02-24 16:00:00.603598: W tensorflow/lite/toco/graph_transformations/resolve_constant_random_uniform.cc:88] RandomUniform op outputting "bi-lstm/dropout/random_uniform/RandomUniform" is truly random (using /dev/random system entropy). Therefore, cannot resolve as constant. Set "seed" or "seed2" attr non-zero to fix this
2020-02-24 16:00:00.603642: W tensorflow/lite/toco/graph_transformations/resolve_constant_random_uniform.cc:88] RandomUniform op outputting "dropout_1/random_uniform/RandomUniform" is truly random (using /dev/random system entropy). Therefore, cannot resolve as constant. Set "seed" or "seed2" attr non-zero to fix this
2020-02-24 16:00:00.603741: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 2: 21 operators, 66 arrays (0 quantized)
2020-02-24 16:00:00.603833: W tensorflow/lite/toco/graph_transformations/resolve_constant_random_uniform.cc:88] RandomUniform op outputting "dropout_1/random_uniform/RandomUniform" is truly random (using /dev/random system entropy). Therefore, cannot resolve as constant. Set "seed" or "seed2" attr non-zero to fix this
2020-02-24 16:00:00.603875: W tensorflow/lite/toco/graph_transformations/resolve_constant_random_uniform.cc:88] RandomUniform op outputting "bi-lstm/dropout/random_uniform/RandomUniform" is truly random (using /dev/random system entropy). Therefore, cannot resolve as constant. Set "seed" or "seed2" attr non-zero to fix this
2020-02-24 16:00:00.603994: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 3: 20 operators, 64 arrays (0 quantized)
2020-02-24 16:00:00.604102: W tensorflow/lite/toco/graph_transformations/resolve_constant_random_uniform.cc:88] RandomUniform op outputting "bi-lstm/dropout/random_uniform/RandomUniform" is truly random (using /dev/random system entropy). Therefore, cannot resolve as constant. Set "seed" or "seed2" attr non-zero to fix this
2020-02-24 16:00:00.604145: W tensorflow/lite/toco/graph_transformations/resolve_constant_random_uniform.cc:88] RandomUniform op outputting "dropout_1/random_uniform/RandomUniform" is truly random (using /dev/random system entropy). Therefore, cannot resolve as constant. Set "seed" or "seed2" attr non-zero to fix this
2020-02-24 16:00:00.604242: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Group bidirectional sequence lstm/rnn: 20 operators, 64 arrays (0 quantized)
2020-02-24 16:00:00.604376: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After Group bidirectional sequence lstm/rnn pass 1: 16 operators, 58 arrays (0 quantized)
2020-02-24 16:00:00.604559: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before dequantization graph transformations: 16 operators, 58 arrays (0 quantized)
2020-02-24 16:00:00.604838: I tensorflow/lite/toco/allocate_transient_arrays.cc:345] Total transient array allocated size: 537600 bytes, theoretical optimal value: 537600 bytes.
2020-02-24 16:00:00.604929: I tensorflow/lite/toco/toco_tooling.cc:439] Estimated count of arithmetic ops: 653248 ops, equivalently 326624 MACs
2020-02-24 16:00:00.604935: I tensorflow/lite/toco/toco_tooling.cc:454] Number of parameters: 3807621

**Comment by yuanlida** [comment]
Thanks.

**Comment by amahendrakar** [comment]
@yuanlida,
Is this still an issue? Please feel free to close the issue if it is resolved. Thanks!
