### ISSUE TITLE
Not able to perform tflite inferences for batch sizes beyond 1 (COCO SSD MobileNet v1)

### ISSUE THREAD

**Issue by kamathhrishi** [tensorflow/tensorflow#37012]
**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or
binary): - TensorFlow version (use command below): 2.1.0 binary

Basically I imported the COCO SSD mobile net model. I want to perform inference for batch sizes more than 1.

This is my code 

```import numpy as np
import tensorflow as tf

# Load TFLite model and allocate tensors.
interpreter = tf.lite.Interpreter(model_path="detect.tflite")
interpreter.allocate_tensors()

# Get input and output tensors.
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

# Test model on random input data.
input_shape = input_details[0]['shape']
input_shape=[100,300,300,3]

interpreter.resize_tensor_input(input_details[0]['index'],[100,300,300,3])

print(output_details[0])

interpreter.allocate_tensors()

input_data = np.array(np.random.random_sample(input_shape), dtype=np.uint8)
print("INPUT SHAPE: ",input_data.shape)
interpreter.set_tensor(input_details[0]['index'],input_data)

interpreter.invoke()

# The function `get_tensor()` returns a copy of the tensor data.
# Use `tensor()` in order to get a pointer to the tensor.
output_data = interpreter.get_tensor(output_details[0]['index'])
print(output_data)
``` 

I ended up getting this error

```{'name': 'TFLite_Detection_PostProcess', 'index': 167, 'shape': array([ 1, 10,  4], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0)}
Traceback (most recent call last):
  File "tflite.py", line 20, in <module>
    interpreter.allocate_tensors()
  File "/home/hrishikesh/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow_core/lite/python/interpreter.py", line 247, in allocate_tensors
    return self._interpreter.AllocateTensors()
  File "/home/hrishikesh/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow_core/lite/python/interpreter_wrapper/tensorflow_wrap_interpreter_wrapper.py", line 110, in AllocateTensors
    return _tensorflow_wrap_interpreter_wrapper.InterpreterWrapper_AllocateTensors(self)
RuntimeError: tensorflow/lite/kernels/reshape.cc:66 num_input_elements != num_output_elements (433200 != 4332)Node number 36 (RESHAPE) failed to prepare.```

**Comment by amahendrakar** [comment]
Was able to reproduce the issue. Please find the Gist [here](https://colab.sandbox.google.com/gist/amahendrakar/cb02f279e0aecd0b2c2f97ae662a95e8/37012.ipynb). Thanks!

**Comment by kamathhrishi** [comment]
@amahendrakar Thank you. I would love to have a solution to this problem.

**Comment by ymodak** [comment]
Not all models inputs can be resized. The input should be [1,300,300,3]
See https://www.tensorflow.org/lite/models/object_detection/overview#input
The code executes successfully with following changes;
```python
input_shape=[1,300,300,3]
interpreter.resize_tensor_input(input_details[0]['index'],[1,300,300,3])
```
Thanks!

**Comment by xross** [comment]
You should resize the output tensor as well was the input tensor.

Something like :

```
output_details = interpreter.get_output_details()
output_shape = output_details[0]['shape']
interpreter.resize_tensor_input(output_details[0]['index'],[100, output_shape[1], output_shape[2], output_shape[3]])
```

**Comment by alfarok** [comment]
Hey @ymodak, @xross, your previous replies have been very informative!  I am running TFLite from the 2.2 release on Linux and hitting a similar issue.

I am able to resize my input tensor to recognize a dynamic value for the batch dimension (batch_size, 512, 512, 3), which was originally failing prior to resizing the tensor.  However, my output values seemed to be fixed at (1, 512, 512, 3) despite resizing and allocating as described above for both the input and outputs.

Sample:
```python
# Concatenate the images to a single numpy array
batch_input = np.vstack(ARRAY_OF_NP_IMAGES) #(batch, 512, 512, 3)

# Get input/output information
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

# Adjust graph input to handle batch tensor
interpreter.resize_tensor_input(input_details[0]['index'], batch_input.shape) #(batch_size, 512, 512, 3)

# Adjust output #1 in graph to handle batch tensor
interpreter.resize_tensor_input(output_details[0]['index'], batch_input.shape) #(batch_size, 512, 512, 3)

# Adjust output #2 in graph to handle batch tensor
output_shape = output_details[1]['shape']
interpreter.resize_tensor_input(output_details[1]['index'], (batch_input.shape[0], output_shape[1], output_shape[2], output_shape[3])) #(batch_size, 512, 512, 18)

# Allocate for the resizing operations
interpreter.allocate_tensors()

# Set input tensor
interpreter.set_tensor(input_details[0]['index'], batch_input)

# Run
interpreter.invoke()

print(output_details[0]) # Shape and shape signature are always (1, 512, 512, 3)
print(output_details[1]) # Shape and shape signature are always (1, 512, 512, 3)
```

I tested the code above using an input array containing 2 images but always get a single result returned for both output tensors:
```
{'name': 'Identity', 'index': 244, 'shape': array([  1, 512, 512,   3], dtype=int32), 'shape_signature': array([  1, 512, 512,   3], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}

{'name': 'Identity_1', 'index': 288, 'shape': array([  1, 512, 512,  18], dtype=int32), 'shape_signature': array([  1, 512, 512,  18], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}
```

I also verified that the resizing shapes before callling allocate are correct `(2, 512, 512, 3)` and `(2, 512, 512, 18)`.

Any suggestions or help would be greatly appreciated!

**Comment by karimnosseir** [comment]
@alfarok You should have your model converted again with supporting dynamic batch size. Looks like you specified static size during conversion.

**Comment by alfarok** [comment]
Thanks @kamathhrishi!

I originally converted the model using python and did not specify the model `input_shape` or `output_shape`.  Since my inputs and outputs displayed correctly on the original model when using `model.summary()` I didn't think I would have to manually reset them during the conversion.

Running the CLI tool with just the `input_shape` flag seems to fix the issue as suggested:
```
tflite_convert --input_shape=None,512,512,3 --saved_model_dir=models/my_model --output_file=models/batch_model.tflite 
```

Output results with 2 input images (`shape_signature` now updates the dimension in the first axis to `-1`):
```python
print(output_details[0])

{'name': 'Identity', 'index': 312, 'shape': array([  1, 512, 512,   3], dtype=int32), 'shape_signature': array([ -1, 512, 512,   3], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}

print(output_details[1])

{'name': 'Identity_1', 'index': 360, 'shape': array([  1, 512, 512,  18], dtype=int32), 'shape_signature': array([ -1, 512, 512,  18], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}
```
