### ISSUE TITLE
RNN unrolled, wrong quantization graph

### ISSUE THREAD

**Issue by wwwind** [tensorflow/tensorflow#37023]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- TensorFlow installed from (source or binary): source
- TensorFlow version (or github SHA if from source):
version is 2.2.0-dev20200218, git version is v1.12.1-25080-gca585e7

**Command used to run the converter or code if you’re using the Python API**
If possible, please share a link to Colab/Jupyter/any notebook.

The problem has appeared on much bigger model, but I can demonstrate it on the MNIST example.
```
import numpy as np
import tensorflow as tf

print("version is {}, git version is {}".format(tf.version.VERSION, tf.version.GIT_VERSION))


from model import Model

class SimpleModel(Model):
    def __init__(self):
        super().__init__()
        self.model_name = "mnist"
        self.train_data = None
        self.test_data = None
        self.calib_data = None
        self.num_calib = 1000
        # (data preprocessing) Normalize the input image so that
        # each pixel value is between 0 to 1.
        self.pre_process = lambda x: x / 255.0

        self._load_data()
        self._set_path()

    def _load_data(self):
        # Load MNIST dataset
        mnist = tf.keras.datasets.mnist

        # _data: (images, labels)
        self.train_data, self.test_data = mnist.load_data()
        self.calib_data = self.pre_process(
            self.train_data[0][0 : self.num_calib].astype(np.float32)
        )

    def train(self):
        cell = tf.keras.layers.GRUCell(3)

        model = tf.keras.models.Sequential([
            tf.keras.layers.Input(shape=(28, 28), name='input'),
            #tf.keras.layers.LSTM(32),
            tf.keras.layers.RNN(cell, unroll=True),
            tf.keras.layers.Flatten(),
            tf.keras.layers.Dense(10, activation=tf.nn.softmax, name='output')
        ])
        model.summary()

        train_images = self.pre_process(self.train_data[0])
        train_labels = self.train_data[1]
        test_images = self.pre_process(self.test_data[0])
        test_labels = self.test_data[1]
        # Train the digit classification model
        model.compile(
            optimizer="adam",
            loss="sparse_categorical_crossentropy",
            metrics=["accuracy"],
        )
        model.fit(
            train_images,
            train_labels,
            epochs=1,
            validation_data=(test_images, test_labels),
        )
        # dump SavedModel - ANOTHER BUG HERE!
        #model.save(str(self.savedModel_dir))

        return model

    def eval(self, tflite_model_path: str):
        interpreter = tf.lite.Interpreter(model_path=str(tflite_model_path))
        interpreter.allocate_tensors()

        input_index = interpreter.get_input_details()[0]["index"]
        output_index = interpreter.get_output_details()[0]["index"]

        # (data preprocessing) Normalize the input image so that
        # each pixel value is between 0 to 1.
        test_images = self.pre_process(self.test_data[0])
        test_labels = self.test_data[1]
        # Run predictions on every image in the "test" dataset.
        prediction_digits = []
        for test_image in test_images:
            # Pre-processing: add batch dimension and convert to float32 to match with
            # the model's input data format.
            test_image = np.expand_dims(test_image, axis=0).astype(np.float32)
            interpreter.set_tensor(input_index, test_image)

            # Run inference.
            interpreter.invoke()

            # Post-processing: remove batch dimension and find the digit with highest
            # probability.
            output = interpreter.tensor(output_index)
            digit = np.argmax(output()[0])
            prediction_digits.append(digit)

        # Compare prediction results with ground truth labels to calculate accuracy.
        accurate_count = 0
        for index, _ in enumerate(prediction_digits):
            if prediction_digits[index] == test_labels[index]:
                accurate_count += 1
        accuracy = accurate_count * 1.0 / len(prediction_digits)

        return accuracy

    def _get_calib_data_func(self):
        def representative_data_gen():
            for input_value in self.calib_data:
                input_value = np.expand_dims(input_value, axis=0).astype(np.float32)
                yield [input_value]

        return representative_data_gen


if __name__ == "__main__":
    temp = SimpleModel()
    model = temp.train()

    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.representative_dataset = temp._get_calib_data_func()

    # save INT8 tflite
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8,
        tf.lite.OpsSet.SELECT_TF_OPS]
    converter.experimental_new_converter = True
    tflite_model_INT8 = converter.convert()
    open("lstm_unrolled_int8.tflite", "wb").write(tflite_model_INT8)

    print("INT8 model eval results: {:f}".format(temp.eval("lstm_unrolled_int8")))

```

**The output from the converter invocation**

```
Traceback (most recent call last):
  File "/home/elezhe01/work/discovery/int16_crosstest/model/SimpleModelLSTM_self.py", line 132, in <module>
    print("INT8 model eval results: {:f}".format(temp.eval("lstm_unrolled_int8")))
  File "/home/elezhe01/work/discovery/int16_crosstest/model/SimpleModelLSTM_self.py", line 69, in eval
    interpreter.allocate_tensors()
  File "/home/elezhe01/.local/lib/python3.6/site-packages/tensorflow/lite/python/interpreter.py", line 242, in allocate_tensors
    return self._interpreter.AllocateTensors()
  File "/home/elezhe01/.local/lib/python3.6/site-packages/tensorflow/lite/python/interpreter_wrapper/tensorflow_wrap_interpreter_wrapper.py", line 110, in AllocateTensors
    return _tensorflow_wrap_interpreter_wrapper.InterpreterWrapper_AllocateTensors(self)
RuntimeError: tensorflow/lite/kernels/kernel_util.cc:129 std::abs(input_product_scale - bias_scale) <= 1e-6 * std::min(input_product_scale, bias_scale) was not true.Node number 3 (FULLY_CONNECTED) failed to prepare.
```

**Also, please include a link to the saved model or GraphDef**

```
Another bug: The model with unrolled RNN cell can't be saved - see above
```

**Failure details**

The error above means that the scale of bias is not equal to the scale of activations * the scale of weights as it should be. As far as I can see, after unroll operation the bias is shared, but it should be quantized for each layer separately.

**Comment by wwwind** [comment]
Hi @jianlijianli ! Sorry to bother you, but could you please take a look ?
The main problem here is that for an unrolled RNN cell the bias is shared and it has the same quantization for all layers, but it must have different quantizations for different layers: param scale should be scale of activations * scale of weights. Is it a known issue ? Are there plans to fix it ? 
We have a bunch of models that hit this problem/exceptions.
Thanks!

**Comment by sushreebarsa** [comment]
@wwwind  It looks like you are using an older Version of Tensorflow. Many bugs have been fixed in the latest version. Could you please execute your code using Latest Version 2.4.1 or 2.5 and let us know if the issue still persists? Thanks!
