### ISSUE TITLE
RuntimeError: Inputs and outputs not all float|uint8|int16 types.Node number 2 (ADD) failed to invoke.

### ISSUE THREAD

**Issue by stev3** [tensorflow/tensorflow#37099]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): source
- TensorFlow version (or github SHA if from source): 1.15

**Command used to run the converter or code if you’re using the Python API**
If possible, please share a link to Colab/Jupyter/any notebook.

```
import numpy as np
import tensorflow as tf
from PIL import Image

interpreter = tf.lite.Interpreter(model_path="out.tflite")
interpreter.allocate_tensors()
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()
print(input_details)
[{'name': 'image', 'index': 21904, 'shape': array([  3, 270, 480], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0)}]
print(output_details)
[{'name': 'action', 'index': 7204, 'shape': array([], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0)}]
input_shape = input_details[0]['shape']
input_data = np.array(np.random.random_sample(input_shape), dtype=np.float32)
interpreter.set_tensor(input_details[0]['index'], input_data)
interpreter.invoke()
output_data = interpreter.get_tensor(output_details[0]['index'])
print(output_data)
```

**The output from the converter invocation**

```
RuntimeError: Inputs and outputs not all float|uint8|int16 types.Node number 2 (ADD) failed to invoke.
```

**Also, please include a link to the saved model or GraphDef**

```
https://we.tl/t-lWH3XmYihS <-- .pb
https://we.tl/t-Bkid4ThzN1 <-- .tflite
```

**Failure details**
The conversion is successful and I can run inference on the .pb, but I get the following error when I run inference on the tflite file.

```
RuntimeError: Inputs and outputs not all float|uint8|int16 types.Node number 2 (ADD) failed to invoke.
```

**Any other info / logs**

Model trained on pytorch mobilenetV2 arch, converted to onnx, and converted to tensorflow.

**Comment by amahendrakar** [comment]
Was able to reproduce the issue. Please find the Gist [here](https://colab.sandbox.google.com/gist/amahendrakar/df7024e8e3f3204c171a586a1c671dab/37099.ipynb). Thanks!

**Comment by jvishnuvardhan** [comment]
@stev3 Looks like some op (ADD) at node #2 is of different dtype than what is accepted. Can you please check what is the dtype supplied at node #2? Thanks!

**Comment by stev3** [comment]
This may be the issue:

```
{'name': 'add_10', 'index': 7205, 'shape': array([2], dtype=int32), 'dtype': <class 'numpy.int64'>, 'quantization': (0.0, 0)}
```

Is it possible to edit the graph and cast the type to numpy.int32?

**Comment by codeislife99** [comment]
Bumping this since I am facing the same issue. The tf graph when visualized in netron seems to be fine (all float32). However my conclusion is that the TFLite converter is probably mistakenly converting the ADD node to float 64.

**Comment by codeislife99** [comment]
Can someone comment on why the conversion from frozen graph to TFLite model changes the node to float64 which is originally float32.

**Comment by codeislife99** [comment]
I solved this issue by using the experimental MLIR converter as shown here:
https://groups.google.com/a/tensorflow.org/forum/#!topic/tflite/C7Ag0sUrLYg
It just needed one line of change. 
`converter.experimental_new_converter = True  # Add this line
`
 The error is not there anymore. I also verified that the PyTorch output and TFLite interpreter outputs match within tolerance values.

**Comment by mtngld** [comment]
I am using the MLIR convertor and still see this issue.

**Comment by stev3** [comment]
This fix didn't work for me either, but I'm working with a frozen graph and not a saved model. I overhauled my training pipeline to avoid this conversion. You can close it if you'd like, but seems others are experiencing a similar problem.

**Comment by jvishnuvardhan** [comment]
@stev3 Can you share the *.pb file and the conversion code you used or input_shape, output
_shape arguments that need to be supplied for the conversion. The link you provided to *.pb doesn't work anymore. Thanks!

**Comment by taoja12** [comment]
How can I get all the tensor names in the tflite model?

**Comment by sdu2011** [comment]
same issue
my tensorflow version is 2.2.0-dev20200325

i convert .pb to .tflite as:
```
def pb_to_tflite2(pb_path, tflite_path,input_arrays,output_arrays,quant):
    converter = tf.compat.v1.lite.TFLiteConverter.from_frozen_graph(
        pb_path, input_arrays, output_arrays)
    converter.experimental_new_converter = True #no effect
    if quant:
        converter.optimizations = [tf.lite.Optimize.DEFAULT]
    tflite_model = converter.convert()
    f = open(tflite_path, 'wb')
    f.write(tflite_model)

input_arrays = ['pillar_x','pillar_y','pillar_z','pillar_i',
                'num_points_per_pillar',
                'x_sub_shaped',
                'y_sub_shaped',
                'mask'
               ]
output_arrays = ['174']
pb_to_tflite2('./pfe_graph.pb','./pfe_quant.tflite',input_arrays,output_arrays,True)
```

**i can do inference on .pb file successfully.**

when i do infrence on .tflite
```
def do_tflite_inference(model_file_path):
    # Load TFLite model and allocate tensors.
    interpreter = tf.lite.Interpreter(model_path=model_file_path)
    interpreter.allocate_tensors()
    print('build interpreter success!')

    # Get input and output tensors.
    input_details = interpreter.get_input_details()
    output_details = interpreter.get_output_details()
    print(input_details)
    print(output_details)

    #　对每一个input赋值
    for input in input_details:
        print(input['dtype'])
        input_shape = input['shape'] #每一个input都是一个dict 有name,index,shape属性
        input_data = np.array(np.random.random_sample(input_shape), dtype=np.float32)

        input_index = input['index']
        interpreter.set_tensor(input_index,input_data)

    interpreter.invoke()
```
i outputs:
```
Traceback (most recent call last):
  File "tf_inference.py", line 35, in <module>
    do_tflite_inference('./pfe.tflite')
  File "tf_inference.py", line 26, in do_tflite_inference
    interpreter.invoke()
  File "/home/sc/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/lite/python/interpreter.py", line 511, in invoke
    self._interpreter.Invoke()
RuntimeError: Inputs and outputs not all float|uint8|int16 types.Node number 3 (ADD) failed to invoke.
```

when i do above things on tensorflow1.14,when do inference on .tflite,it crash in tflite::ops::builtin::sparse_to_dense::SparseToDenseImp
[https://github.com/tensorflow/tensorflow/issues/35987#issuecomment-604207418](url)

i think there may be bugs in tflite code,when convert .pb to .tflite,the generated .tflite file is not correct at all．

**Comment by codeislife99** [comment]
This is the code that works for me on `tensorflow 2.1.0 ` CPU Version, with onnx-tf built from master branch. 
  ```
 graph_def = tf.compat.v1.GraphDef()
    graph_def.ParseFromString(open(tf_model_path, 'rb').read())
    concrete_func = wrap_frozen_graph(graph_def, inputs=input_tensor, outputs=["scores:0", "boxes:0"])
    converter = tf.lite.TFLiteConverter.from_concrete_functions([concrete_func])
    converter.experimental_new_converter = True
    converter.target_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8, tf.lite.OpsSet.SELECT_TF_OPS]
    tflite_model = converter.convert()
```

**Comment by codeislife99** [comment]
Can you share the pytorch, onnx, and the .pb file so that I can try to convert it using my environment setup and see if it works ?

**Comment by kiapour** [comment]
@codeislife99 Thanks for the tips above! I am also facing the mismatching type error when trying to run my .tflite model.
`RuntimeError: Inputs and outputs not all float|uint8|int16 types.Node number 4 (ADD) failed to invoke.`

Can you please provide the definition (and perhaps an example) of the `wrap_frozen_graph` function above?

I converted a model from onnx to frozen graph using with [onnx-tensorflow](https://github.com/onnx/onnx-tensorflow) built from master.

Next I converted the .pb to .tflite. The converter runs successfully, but I see the error when invoking the tflite model.

```
converter = tf.compat.v1.lite.TFLiteConverter.from_frozen_graph(path/to/frozen_graph.pb, input_arrays, output_arrays)
converter.experimental_new_converter = True
# converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS] # makes no difference
converter.optimizations = [tf.lite.Optimize.DEFAULT]
tf_lite_model = converter.convert()
open('path/to/model.tflite', 'wb').write(tf_lite_model)
```

**Comment by kiapour** [comment]
@codeislife99 Thanks for the tip above! Using the wrap_frozen_graph worked for me.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by JimKimHome** [comment]
@codeislife99 Thanks for the tip above! Using the wrap_frozen_graph worked for me,too.I use the same tensorflow version as your's, and conver the .pb model to .tflite model and load it in andriod, the interpreter can do the inference now!At first I find that the wrap_frozen_graph func can not be recognized ,then I find it on 'https://leimao.github.io/blog/Save-Load-Inference-From-TF2-Frozen-Graph/' ,and I worked out. The full edition of the convert code is list below:
`import tensorflow as tf

def wrap_frozen_graph(graph_def, inputs, outputs, print_graph=False):
    def _imports_graph_def():
        tf.compat.v1.import_graph_def(graph_def, name="")

    wrapped_import = tf.compat.v1.wrap_function(_imports_graph_def, [])
    import_graph = wrapped_import.graph

    print("-" * 50)
    print("Frozen model layers: ")
    layers = [op.name for op in import_graph.get_operations()]
    if print_graph == True:
        for layer in layers:
            print(layer)
    print("-" * 50)

    return wrapped_import.prune(
        tf.nest.map_structure(import_graph.as_graph_element, inputs),
        tf.nest.map_structure(import_graph.as_graph_element, outputs))
if __name__ == '__main__':
    tf_model_path = "model.pb"
    graph_def = tf.compat.v1.GraphDef()
    graph_def.ParseFromString(open(tf_model_path, 'rb').read())
    concrete_func = wrap_frozen_graph(graph_def, inputs=["input:0"], outputs=["boxes:0","scores:0"])
    converter = tf.lite.TFLiteConverter.from_concrete_functions([concrete_func])
    converter.experimental_new_converter = True
    converter.target_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8, tf.lite.OpsSet.SELECT_TF_OPS]
    tflite_model = converter.convert()
    open("converted_model.tflite", "wb").write(tflite_model)
    print("tfltie model saved!!")`

**Comment by JimKimHome** [comment]
@codeislife99 Thanks for the tip above! Using the wrap_frozen_graph worked for me,too.I use the same tensorflow version as your's, and conver the .pb model to .tflite model and load it in andriod, the interpreter can do the inference now!
      At first I find that the wrap_frozen_graph func can not be recognized ,then I find it on 'https://leimao.github.io/blog/Save-Load-Inference-From-TF2-Frozen-Graph/' ,and I worked out. The full edition of the convert code is uploaded.
[pb_to_tflite.txt](https://github.com/tensorflow/tensorflow/files/4479471/pb_to_tflite.txt)

**Comment by Wheest** [comment]
I have also encountered this issue, with models which are successfully exported with:

```
import tensorflow as tf

# make a converter object from the saved tensorflow file
converter = tf.compat.v1.lite.TFLiteConverter.from_frozen_graph(
    model_file,
    input_arrays=[input_name],  # input arrays
    output_arrays=[
        output_name
    ],
)
converter.target_spec.supported_ops = [
    tf.lite.OpsSet.TFLITE_BUILTINS,
    tf.lite.OpsSet.SELECT_TF_OPS,
]
# tell converter which type of optimization techniques to use
converter.optimizations = [tf.lite.Optimize.DEFAULT]

# to view the best option for optimization read documentation of tflite about optimization go to this link https://www.tensorflow.org/lite/guide/get_started#4_optimize_your_model_optional

# convert the model
tf_lite_model = converter.convert()
```

However running in TFLite gives error.

`RuntimeError: Inputs and outputs not all float|uint8|int16 types.Node number 3 (ADD) failed to invoke.`

I've tried to follow the export process using the experimental MLIR converter, which seems to side-step the bug.

However, the export process fails with `ValueError: Feeds must be tensors.`

The traceback is:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-23-d3dc2f63cbd6> in <module>
     25     graph_def = tf.compat.v1.GraphDef()
     26     graph_def.ParseFromString(open(model_file, 'rb').read())
---> 27     concrete_func = wrap_frozen_graph(graph_def, inputs=input_name, outputs=[output_name])
     28     converter = tf.lite.TFLiteConverter.from_concrete_functions([concrete_func])
     29     converter.experimental_new_converter = True

<ipython-input-21-1fc724505eae> in wrap_frozen_graph(graph_def, inputs, outputs, print_graph)
     16     return wrapped_import.prune(
     17         tf.nest.map_structure(import_graph.as_graph_element, inputs),
---> 18         tf.nest.map_structure(import_graph.as_graph_element, outputs))

~/.virtualenvs/tf-lite/lib/python3.7/site-packages/tensorflow/python/eager/wrap_function.py in prune(self, feeds, fetches, name, input_signature)
--> 262         raise ValueError("Feeds must be tensors.")
    263 
    264     # Ignoring all feeds that are captures allows prune to be called
```


The values I'm passing for `input_name` and `output_name` are just string names of the tensors.  I've confirmed in netron that these are the correct names.

I've added a print statement before the value error in `wrap_function.py` to learn more about the error:

```
print('wrap_function.py', f)
print(type(f))
```

This gives the output:

```
--------------------------------------------------
Frozen model layers: 
--------------------------------------------------
wrap_function.py name: "input_tens"
op: "Placeholder"
attr {
  key: "dtype"
  value {
    type: DT_FLOAT
  }
}
attr {
  key: "shape"
  value {
    shape {
      dim {
        size: 1
      }
      dim {
        size: 3
      }
      dim {
        size: 224
      }
      dim {
        size: 224
      }
    }
  }
}

<class 'tensorflow.python.framework.ops.Operation'>
```

The error is raised because we are checking if `isinstance(f, ops.Tensor)` fails.

I'm following through to see why this is being cast as an "Operation", rather than a "Tensor".  Is there something glaringly wrong with my function calling?

**Comment by jaggernaut007** [comment]
Im at this exact same errror. Stil lgetting the error which says 
RuntimeError: Inputs and outputs not all float|uint8|int16 types.Node number 4 (ADD) failed to invoke.

**Comment by Wheest** [comment]
@jaggernaut007 Try [this notebook](https://gist.github.com/Wheest/d8400c73a7795298d1cdd45f247544cc), or the file provided by @JimKimHome .  The new MLIR based model convertor could avoid this bug.  

I'm still trying to get the `wrap_frozen_graph()` working for my case.

**Comment by jaggernaut007** [comment]
I have a feeling the error is due to , providing the wrong output tensor.
Checking out the notebook now

**Comment by jaggernaut007** [comment]
> 
> 
> @jaggernaut007 Try [this notebook](https://gist.github.com/Wheest/d8400c73a7795298d1cdd45f247544cc), or the file provided by @JimKimHome . The new MLIR based model convertor could avoid this bug.
> 
> I'm still trying to get the `wrap_frozen_graph()` working for my case.

https://www.tensorflow.org/lite/guide/inference#load_and_run_a_model_in_python
Notebook is same as this.

**Comment by jaggernaut007** [comment]
*This is my input and output tensor info*

```
[{
	'name': 'input.1',
	'index': 0,
	'shape': array([1, 3, 256, 256], dtype = int32),
	'shape_signature': array([1, 3, 256, 256], dtype = int32),
	'dtype': < class 'numpy.float32' > ,
	'quantization': (0.0, 0),
	'quantization_parameters': {
		'scales': array([], dtype = float32),
		'zero_points': array([], dtype = int32),
		'quantized_dimension': 0
	},
	'sparsity_parameters': {}
}]
[{
	'name': '4358',
	'index': 4138,
	'shape': array([1, 17, 3], dtype = int32),
	'shape_signature': array([1, 17, 3], dtype = int32),
	'dtype': < class 'numpy.float32' > ,
	'quantization': (0.0, 0),
	'quantization_parameters': {
		'scales': array([], dtype = float32),
		'zero_points': array([], dtype = int32),
		'quantized_dimension': 0
	},
	'sparsity_parameters': {}
}]
```
*This is stack trace of the error *

> > Traceback (most recent call last):
>   File "test_graph.py", line 20, in <module>
>     interpreter.invoke()
>   File "/home/shreyas/.local/lib/python3.8/site-packages/tensorflow/lite/python/interpreter.py", line 511, in invoke
>     self._interpreter.Invoke()
>   File "/home/shreyas/.local/lib/python3.8/site-packages/tensorflow/lite/python/interpreter_wrapper/tensorflow_wrap_interpreter_wrapper.py", line 113, in Invoke
>     return _tensorflow_wrap_interpreter_wrapper.InterpreterWrapper_Invoke(self)
> RuntimeError: Inputs and outputs not all float|uint8|int16 types.Node number 4 (ADD) failed to invoke.

>

**Comment by Wheest** [comment]
Could you share `test_graph.py` @jaggernaut007?   Are you trying the experimental MLIR convertor?

The issue seems to be that there is a bug in the normal conversion process:

> However my conclusion is that the TFLite converter is probably mistakenly converting the ADD node to float 64.

> I solved this issue by using the experimental MLIR converter as shown here:

**Comment by jaggernaut007** [comment]
> 
> 
> @codeislife99 Thanks for the tip above! Using the wrap_frozen_graph worked for me,too.I use the same tensorflow version as your's, and conver the .pb model to .tflite model and load it in andriod, the interpreter can do the inference now!
> At first I find that the wrap_frozen_graph func can not be recognized ,then I find it on 'https://leimao.github.io/blog/Save-Load-Inference-From-TF2-Frozen-Graph/' ,and I worked out. The full edition of the convert code is uploaded.
> [pb_to_tflite.txt](https://github.com/tensorflow/tensorflow/files/4479471/pb_to_tflite.txt)

What are the input and output tensors you have provided?

**Comment by jaggernaut007** [comment]
> 
> 
> Could you share `test_graph.py` @jaggernaut007? Are you trying the experimental MLIR convertor?
> 
> The issue seems to be that there is a bug in the normal conversion process:
> 
> > However my conclusion is that the TFLite converter is probably mistakenly converting the ADD node to float 64.
> 
> > I solved this issue by using the experimental MLIR converter as shown here:

Have mentioned this in #39790 
Using the new MLIRconvertor has no difference. Still the same result.
This error is because of the numpy.float32 in node 4 Trying to figure out how to correct that.
Here is the test code for checking it out.

`import numpy as np                                                                                                                                                                                   import tensorflow as tf                                                                                                                                                                                                                                                                                                                                                                                   # Load TFLite model and allocate tensors.                                                                                                                                                            interpreter = tf.lite.Interpreter(model_path="margipose2.tflite")                                                                                                                                    interpreter.allocate_tensors()                                                                                                                                                                                                                                                                                                                                                                            # Get input and output tensors.                                                                                                                                                                      input_details = interpreter.get_input_details()                                                                                                                                                      output_details = interpreter.get_output_details()                                                                                                                                                                                                                                                                                                                                                         print(input_details)                                                                                                                                                                                 print(output_details)                                                                                                                                                                                                                                                                                                                                                                                     # Test model on random input data.                                                                                                                                                                   input_shape = input_details[0]['shape']                                                                                                                                                              input_data = np.array(np.random.random_sample(input_shape), dtype=np.float32)                                                                                                                        interpreter.set_tensor(input_details[0]['index'], input_data)                                                                                                                                                                                                                                                                                                                                             interpreter.invoke()                                                                                                                                                                                                                                                                                                                                                                                      # The function `get_tensor()` returns a copy of the tensor data.                                                                                                                                     # Use `tensor()` in order to get a pointer to the tensor.                                                                                                                                            output_data = interpreter.get_tensor(output_details[0]['index'])                                                                                                                                     print(output_data)   `

**Comment by Wheest** [comment]
Yeah, can confirm that the problem (`RuntimeError: Inputs and outputs not all float|uint8|int16 types.Node number 3 (ADD) failed to invoke.`) still occurs even when using the MLIR exporter.

Using the `wrap_frozen_graph()` approach didn't work for me, I exported using:
```
    # make a converter object from the saved tensorflow file
    converter = tf.compat.v1.lite.TFLiteConverter.from_frozen_graph(
        model_file,
        input_arrays=[input_tensor],  # input arrays
        output_arrays=[output_tensor],  # output arrays
    )
    converter.target_spec.supported_ops = [
        tf.lite.OpsSet.TFLITE_BUILTINS,
        tf.lite.OpsSet.SELECT_TF_OPS,
    ]
    # tell converter which type of optimization techniques to use
    converter.optimizations = [tf.lite.Optimize.DEFAULT]

    converter.experimental_new_converter = True
    
    # convert the model
    tf_lite_model = converter.convert()
```

**Comment by jaggernaut007** [comment]
> 
> 
> Yeah, can confirm that the problem (`RuntimeError: Inputs and outputs not all float|uint8|int16 types.Node number 3 (ADD) failed to invoke.`) still occurs even when using the MLIR exporter.
> 
> Using the `wrap_frozen_graph()` approach didn't work for me, I exported using:
> 
> ```
>     # make a converter object from the saved tensorflow file
>     converter = tf.compat.v1.lite.TFLiteConverter.from_frozen_graph(
>         model_file,
>         input_arrays=[input_tensor],  # input arrays
>         output_arrays=[output_tensor],  # output arrays
>     )
>     converter.target_spec.supported_ops = [
>         tf.lite.OpsSet.TFLITE_BUILTINS,
>         tf.lite.OpsSet.SELECT_TF_OPS,
>     ]
>     # tell converter which type of optimization techniques to use
>     converter.optimizations = [tf.lite.Optimize.DEFAULT]
> 
>     converter.experimental_new_converter = True
>     
>     # convert the model
>     tf_lite_model = converter.convert()
> ```

I can export the tflite model too. But I am unable to run the model on tflite.
tf-nightly changes the error.
Are you able to run the model?

**Comment by Wheest** [comment]
Am currently debugging TFLite.  Have confirmed that in the TFLite model file, the Add operation has inputs and output of type float32 (consistent with the rest of the model.

However, during runtime, calling the `Eval()` function in `tensorflow/lite/kernels/add.cc`, the type of the output tensor is actually 4 (`kTfLiteInt64`).  It is because of this that `Eval()` throws the error.

Am currently trying to understand why the type is set to this.

**Comment by parthisultimate** [comment]
Following is the colab link attached, it would be great if anyone could help resolve it.
I had converted my code from pytorch model to onnx file, then from onnx to .pb file and finally from pb file to tflite.
This is my collab link

https://colab.research.google.com/drive/1hEFdsl_OIHyfC0fZBKcIt8V0t8X1m07h?usp=sharing

**Comment by Wheest** [comment]
I think I solved the issue from my side.  I found that using the `out.view()` method in my PyTorch model, before the fully connected layer, it caused this issue in the TFLite model.  Inspecting the models, I haven't been able to figure out why this happens.

However, if I replace the `view` method with the `torch.flatten()` function, which is functionally equivalent, the TF-Lite model does not have this issue.

It's a totally weird problem.  I can tidy-up and share my mini-version if anyone is interested.  But hopefully this will help.  Whether or not it's in the ONNX to TF pipeline, or in the TF to TF-Lite pipeline I am unsure.  Perhaps someone more motivated can figure it out.

**Comment by parthisultimate** [comment]
Thanks a lot @Wheest 
I have used .view() a lot of times to reshape my arrays in the pytorch code rather than flatten, need to search alternatives for this.

**Comment by ShiyongL** [comment]
> I think I solved the issue from my side. I found that using the `out.view()` method in my PyTorch model, before the fully connected layer, it caused this issue in the TFLite model. Inspecting the models, I haven't been able to figure out why this happens.
> 
> However, if I replace the `view` method with the `torch.flatten()` function, which is functionally equivalent, the TF-Lite model does not have this issue.
> 
> It's a totally weird problem. I can tidy-up and share my mini-version if anyone is interested. But hopefully this will help. Whether or not it's in the ONNX to TF pipeline, or in the TF to TF-Lite pipeline I am unsure. Perhaps someone more motivated can figure it out.

@Wheest Do you mind share your code snippet on how to replace .view() with flatten()? I am dealing with the following .view() usage:

`bbox_regressions = torch.cat([o.view(o.size(0), -1, 4) for o in loc], 1)`

Thanks a lot!

**Comment by karanbirchahal-bc** [comment]
Thank you @codeislife99 !

**Comment by Wheest** [comment]
@ShiyongL my code was thus:

`out = out.view(out.size(0), -1) --> x = torch.flatten(x, 1)`

Your invocation seems a bit more complex than mine, I'm not sure what the 4 is used for in yours.  Unsure if you could get an equivalent operation via flatten.
