### ISSUE TITLE
Build from source(python2.7 ubuntu 16.04) has error:  AttributeError: attribute '__doc__' of 'type' objects is not writable

### ISSUE THREAD

**Issue by gms2009** [tensorflow/tensorflow#37109]
**System information** 
Linux Ubuntu 16.04): 

- TensorFlow installed from (source or
binary): - TensorFlow version 1.13.2
- Python version: 2.7.12
- Bazel version 0.22.0
- GCC  5.4.0
- CUDA/cuDNN version: - 10.0/7.6.4
cuda-repo-ubuntu1604-10-0-local-10.0.130-410.48_1.0-1_amd64.deb
cuda-repo-ubuntu1604-10-0-local-nvjpeg-update-1_1.0-1_amd64.deb

libcudnn7_7.6.4.38-1+cuda10.0_amd64.deb
libcudnn7-dev_7.6.4.38-1+cuda10.0_amd64.deb
libnvinfer5_5.0.2-1+cuda10.0_amd64.deb
libnvinfer-dev_5.0.2-1+cuda10.0_amd64.deb
libnvinfer-samples_5.0.2-1+cuda10.0_all.deb
tensorrt_5.0.2.6-1+cuda10.0_amd64.deb
./configure    cuda  yes    tensorrt yes

also tried on ubuntu 18.04  
tensorflow 1.15.2
bazel 0.24.1
cuda/cudnn   10.2/7.6.5 same problem
tensorrt  nv-tensorrt-repo-cuda10.2-trt6.0.1.8-ga-20191108
--------------------------------
     return *(float*)&ilane;
                      ^
tensorflow/lite/toco/tflite/import.cc: At global scope:
tensorflow/lite/toco/tflite/import.cc:195:6: warning: 'bool toco::tflite::{anonymous}::Verify(const void*, size_t)' defined but not used [-Wunused-function]
 bool Verify(const void* buf, size_t len) {
      ^
ERROR: /home/weilo/tensorflow-1.13.2/tensorflow/BUILD:579:1: Executing genrule //tensorflow:tf_python_api_gen_v1 failed (Exit 1)
Traceback (most recent call last):
  File "/home/weilo/.cache/bazel/_bazel_weilo/5dc966cf5c885efffef93d319484bf56/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/tools/api/generator/create_python_api.py", line 27, in <module>
    from tensorflow.python.tools.api.generator import doc_srcs
  File "/home/weilo/.cache/bazel/_bazel_weilo/5dc966cf5c885efffef93d319484bf56/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 63, in <module>
    from tensorflow.python.framework.framework_lib import *  # pylint: disable=redefined-builtin
  File "/home/weilo/.cache/bazel/_bazel_weilo/5dc966cf5c885efffef93d319484bf56/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/framework/framework_lib.py", line 52, in <module>
    from tensorflow.python.framework.importer import import_graph_def
  File "/home/weilo/.cache/bazel/_bazel_weilo/5dc966cf5c885efffef93d319484bf56/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/framework/importer.py", line 28, in <module>
    from tensorflow.python.framework import function
  File "/home/weilo/.cache/bazel/_bazel_weilo/5dc966cf5c885efffef93d319484bf56/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/framework/function.py", line 36, in <module>
    from tensorflow.python.ops import resource_variable_ops
  File "/home/weilo/.cache/bazel/_bazel_weilo/5dc966cf5c885efffef93d319484bf56/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/ops/resource_variable_ops.py", line 39, in <module>
    from tensorflow.python.ops import variables
  File "/home/weilo/.cache/bazel/_bazel_weilo/5dc966cf5c885efffef93d319484bf56/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/ops/variables.py", line 133, in <module>
    "* `ONLY_FIRST_TOWER`: Deprecated alias for `ONLY_FIRST_REPLICA`.\n  ")
AttributeError: attribute '__doc__' of 'type' objects is not writable
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 16309.185s, Critical Path: 310.76s
INFO: 15104 processes: 15104 local.
FAILED: Build did NOT complete successfully

**Comment by ravikyram** [comment]
@gms2009 

Provide the exact sequence of commands / steps that you executed before running into the problem. Also, looks like Tensorflow not installed properly.please try with [tested build configurations](https://www.tensorflow.org/install/source#gpu) for installing tensorflow.Thanks!

**Comment by gms2009** [comment]
tensorflow with python3(build from source in the same machine) has been installed.  that might be the problem?

**Comment by gms2009** [comment]
bazel version is 0.20.0
build configure is   cuda yes   tensorrt yes      all others default
error is around 19xxx
fresh install ubuntu 16.04.06
following is .bash_history unmodified, so has some trash

sudo apt update
sudo apt upgrade
sudo mount /dev/sda5 /mnt/
sudo dpkg -i /mnt/extra/cuda-repo-ubuntu1604-10-0-local-10.0.130-410.48_1.0-1_amd64.deb 
sudo apt-key add /var/cuda-repo-10-0-local-10.0.130-410.48/7fa2af80.pub
sudo apt update
sudo apt install cuda
vi vvv
nvidia-smi 
sudo mount /dev/sda5
sudo mount /dev/sda5 /mnt/
sudo dpkg -i /mnt/extra/u16/cuda-repo-ubuntu1604-10-0-local-nvjpeg-update-1_1.0-1_amd64.deb 
sudo dpkg -i /mnt/extra/nv-tensorrt-repo-ubuntu1604-cuda10.0-trt5.0.2.6-ga-20181009_1-1_amd64.deb 
cd /var/nv-tensorrt-repo-cuda10.0-trt5.0.2.6-ga-20181009/
ls
sudo dpkg -i libcudnn7_7.3.1.20-1+cuda10.0_amd64.deb libcudnn7-dev_7.3.1.20-1+cuda10.0_amd64.deb libnvinfer5_5.0.2-1+cuda10.0_amd64.deb libnvinfer-dev_5.0.2-1+cuda10.0_amd64.deb libnvinfer-samples_5.0.2-1+cuda10.0_all.deb tensorrt_5.0.2.6-1+cuda10.0_amd64.deb 
sudo apt update
sudo apt upgrade
cd
cp /mnt/extra/tensorflow-1.13.2.zip  ./
unzip tensorflow-1.13.2.zip 
cd tensorflow-1.13.2/
./configure 
sudo dpkg -i /mnt/extra/bazel_0.22.0-linux-x86_64.deb 
sudo apt install zlib1g-dev
./configure 
sudo apt install python-dev python-pip
pip install six numpy wheel setuptools mock future keras_applications keras_preprocessing enum
pip install --upgrade pip
pip install six numpy wheel setuptools mock future keras_applications keras_preprocessing enum
./configure 
ls /mnt/extra/bazel
sudo dpkg -i /mnt/extra/bazel_0.20.0-linux-x86_64.deb 
sudo apt install java8-sdk-headless java8-sdk
sudo apt install openjdk-8-sdk-headless openjdk-8-sdk
sudo apt install openjdk-8-jdk-headless openjdk-8-jdk
./configure 
bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package

**Comment by gms2009** [comment]
unable to open tested build configurations, hope you can put some info here, like version for cuda cudnn tensorrt tensorflow bazel, for python2 not 3

**Comment by ravikyram** [comment]
@gms2009 
![image](https://user-images.githubusercontent.com/51902062/75515712-bb891d00-5a20-11ea-857c-8c9941b9947a.png)

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
