### ISSUE TITLE
MUL doesn't work on gpu delegate with error: Dimension can not be reduced to linear

### ISSUE THREAD

**Issue by Richard-Yang-Bose** [tensorflow/tensorflow#37102]
**System information**

Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac OS 10.14.6
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: iPhone XR, iPhone Xs
TensorFlow installed from (source or binary): installed from source.
TensorFlow version (use command below): 1.14.0
Python version: 3.6
Bazel version (if compiling from source): 1.2.1
GCC/Compiler version (if compiling from source): 4.2.1

**Describe the current behavior**
`Mul` doesn't work with multiple axis while using gpu delegate. (no issue while using cpu).

Tried to create a dummy tflite graph with simply a multiply operation on input of shape of `[1, 1, n, m]` and variable with the same shape. While verifying with TFLite iOS benchmark app with GPU delegate, the benchmark app reports "failed to apply GPU delegate" on the mul operation. Note that the model runs fine without gpu delegate.

**Describe the expected behavior**

Mul operation works on gpu delegate and supports multiple axis.

**Code to reproduce the issue**
Here's the dummy model that should reproduce the issue in the TFLite ios benchmark app:
[dummy_model.tflite](https://drive.google.com/file/d/1383fCIA0-Uhlmbo8zR16KW3C6FYDX5un/view?usp=sharing)

**Other info / logs**
```
Graph: [/private/var/containers/Bundle/Application/DD8D26F4-6BC1-4EFB-A444-EA2FB7F411D9/TFLiteBenchmark.app/dummy_model_2.tflite]
Input layers: [input_feature_placeholder]
Input shapes: [1,1,2,80]
Input value ranges: []
Allow fp16 : [0]
Require full delegation : [0]
Enable op profiling: [0]
Max profiling buffer entries: [1024]
CSV File to export profiling data to: []
Use gpu : [1]
Allow lower precision in gpu : [1]
GPU delegate wait type : [aggressive]
Loaded model /private/var/containers/Bundle/Application/DD8D26F4-6BC1-4EFB-A444-EA2FB7F411D9/TFLiteBenchmark.app/dummy_model_2.tflite
2020-02-26 15:16:14.857526-0500 TFLiteBenchmark[444:628154] Initialized TensorFlow Lite runtime.
2020-02-26 15:16:14.857843-0500 TFLiteBenchmark[444:628154] Created TensorFlow Lite delegate for Metal.
2020-02-26 15:16:14.858337-0500 TFLiteBenchmark[444:628154] Metal GPU Frame Capture Enabled
2020-02-26 15:16:14.859181-0500 TFLiteBenchmark[444:628154] Metal API Validation Enabled
2020-02-26 15:16:14.932455-0500 TFLiteBenchmark[444:628154] TfLiteGpuDelegate Prepare: MUL: Dimension can not be reduced to linear.
2020-02-26 15:16:14.932670-0500 TFLiteBenchmark[444:628154] Node number 2 (TfLiteMetalDelegate) failed to prepare.
2020-02-26 15:16:14.932800-0500 TFLiteBenchmark[444:628154] tensorflow/lite/kernels/mul.cc:74 input1->type != input2->type (1 != 10)
2020-02-26 15:16:14.932891-0500 TFLiteBenchmark[444:628154] Node number 1 (MUL) failed to prepare.
Failed to apply GPU delegate.
```

**Comment by Saduf2019** [comment]
@Richard-Yang-Bose 
please note i am unable to access the file shared by you, please share a simple stand alone code so i could replicate the issue faced by you in my local.

**Comment by Richard-Yang-Bose** [comment]
Thanks for the reply, here's the code for generating the dummy model, after the tflite dummy model is generated, I try to run it with the TFLite ios benchmark app, with the param: `"use_gpu" : "1",
    "gpu_wait_type" : "aggressive",`
```
import os
import numpy as np
import tensorflow as tf

with tf.Graph().as_default():
    x = tf.placeholder(tf.float32, shape=(1, 1, 2, 80), name='array_input_feature')
    y = tf.Variable(initial_value=tf.ones([1, 1, 2, 80]))
    x = tf.math.multiply(x, y * 2)
    x = tf.identity(x, name='output')

    with tf.Session() as sess:

        tf.contrib.quantize.create_training_graph()
        sess.run(tf.global_variables_initializer())
        tf.contrib.quantize.create_eval_graph()
        saver = tf.train.Saver()
        saver.save(sess, 'dummy_model')


def prepare_graph():
    with tf.Session() as sess:
        new_saver = tf.train.import_meta_graph('dummy_model.meta')
        new_saver.restore(sess, tf.train.latest_checkpoint('./'))
        graph = tf.get_default_graph()
        output_names = 'output:0'
        output_tensor = graph.get_tensor_by_name(output_names)
        output_node_names = ["output"]
        frozen_graph_def = tf.graph_util.convert_variables_to_constants(sess, sess.graph_def, output_node_names)
        return frozen_graph_def, output_tensor


def tfliteConvert(graph, outputs, tflite_model_file, quantize=True):
    tf.reset_default_graph()
    # Turn the input into placeholder
    tflite_input = tf.placeholder(
    "float32", [1, 1, 2, 80], name="array_input_feature")
    tf.import_graph_def(graph, name="", input_map={"array_input_feature": tflite_input})
    # prepare the graph for conversion, convert op_hint wrapper
    with tf.Session() as sess:
        curr = sess.graph_def
    converter = tf.lite.TFLiteConverter(curr, [tflite_input], [outputs])
    converter.experimental_new_converter = True
    converter.target_spec.supported_types = [tf.lite.constants.FLOAT16]
    converter.optimizations = [tf.lite.Optimize.DEFAULT]

    tflite = converter.convert()    

    # save TFLite model
    open(tflite_model_file, "wb").write(tflite)


def main():
    frozen_graph_def, outputs = prepare_graph()
    tfliteConvert(frozen_graph_def, outputs, 'dummy_model.tflite')

if __name__ == "__main__":
    main()
```

**Comment by freedomtan** [comment]
@Richard-Yang-Bose in the log you pasted, there is `2020-02-26 15:16:14.932800-0500 TFLiteBenchmark[444:628154] tensorflow/lite/kernels/mul.cc:74 input1->type != input2->type (1 != 10)`, the type mismatch is between `kTfLiteFloat32 = 1` and `TfLiteFloat16 = 10`

**Comment by Richard-Yang-Bose** [comment]
> @Richard-Yang-Bose in the log you pasted, there is `2020-02-26 15:16:14.932800-0500 TFLiteBenchmark[444:628154] tensorflow/lite/kernels/mul.cc:74 input1->type != input2->type (1 != 10)`, the type mismatch is between `kTfLiteFloat32 = 1` and `TfLiteFloat16 = 10`

@freedomtan Thanks for pointing this out, I'm aware of this and have also tried the following setups:
1. Set `allow_fp16` as `1` in the benchmark too: still got the same error log. 
2. Use float32 model (without setting float16 and optimization during the tflite model conversion): still failed to apply GPU delegate, but without the type mismatch error.
Also note that the the benchmark app is able to run mobilenet provided [here](https://www.tensorflow.org/lite/performance/benchmarks) on gpu delegate.
```
2020-03-02 10:21:08.174624-0500 TFLiteBenchmark[10532:2225388] Initialized TensorFlow Lite runtime.
2020-03-02 10:21:08.175107-0500 TFLiteBenchmark[10532:2225388] Created TensorFlow Lite delegate for Metal.
2020-03-02 10:21:08.176624-0500 TFLiteBenchmark[10532:2225388] Metal GPU Frame Capture Enabled
2020-03-02 10:21:08.177811-0500 TFLiteBenchmark[10532:2225388] Metal API Validation Enabled
2020-03-02 10:21:08.294492-0500 TFLiteBenchmark[10532:2225388] TfLiteGpuDelegate Prepare: MUL: Dimension can not be reduced to linear.
2020-03-02 10:21:08.294760-0500 TFLiteBenchmark[10532:2225388] Node number 1 (TfLiteMetalDelegate) failed to prepare.
2020-03-02 10:21:08.294908-0500 TFLiteBenchmark[10532:2225388] Restored previous execution plan after delegate application failure.
Failed to apply GPU delegate.
```

**Comment by freedomtan** [comment]
@Richard-Yang-Bose interesting. It seems you hit a limitation of GPU delegate. Maybe @impjdi might have the right answer.

**Comment by Richard-Yang-Bose** [comment]
@freedomtan Thanks again for the insight and appreciate all the great work!

**Comment by impjdi** [comment]
That error message `Dimension can not be reduced to linear.` is printed at `//tensorflow/lite/delegates/gpu/common/model_builder.cc`.  Not sure why it's trying to use `SetAllDimensions<Linear>`.  Can you attach the TFLite model?

**Comment by Richard-Yang-Bose** [comment]
> That error message `Dimension can not be reduced to linear.` is printed at `//tensorflow/lite/delegates/gpu/common/model_builder.cc`. Not sure why it's trying to use `SetAllDimensions<Linear>`. Can you attach the TFLite model?

here's the model (fp16):
[dummy_model.tflite](https://drive.google.com/file/d/1383fCIA0-Uhlmbo8zR16KW3C6FYDX5un/view?usp=sharing)

**Comment by impjdi** [comment]
Thank you for attaching the model.  Found the issue.  I'll prepare a fix and will let you know.

**Comment by impjdi** [comment]
Are you okay with a fix that requires you to do

>    y = tf.Variable(initial_value=tf.ones([1, 2, 80]))  # without the batch dimension

instead of

>     y = tf.Variable(initial_value=tf.ones([1, 1, 2, 80]))

?

**Comment by Richard-Yang-Bose** [comment]
@impjdi  Thanks for finding the issue!
Yeah that could be a work around, however it's not ideal since I believe some network structure has MUL with 4D tensor required inside the implementation (e.g. [convlstm).](https://github.com/tensorflow/tensorflow/blob/e5bf8de410005de06a7ff5393fafdf832ef1d4ad/tensorflow/python/keras/layers/convolutional_recurrent.py#L703)
Do you think it's possible to have MUL operation compatible with 4D tensor in the future fix?
Thanks again for helping out!

**Comment by impjdi** [comment]
While it's not technically impossible (extending it to the batch dimension is trivial), I think you will have a much bigger problem as it won't be just `MUL` that doesn't support your particular use case; the majority, if not all, of TFLite GPU ops are not designed in a batch-friendly fashion.  We will have a lot more plumbing to do to accommodate the batch size we will investigate more in the coming months.

**Comment by Richard-Yang-Bose** [comment]
Yeah, that make sense, especially inference use cases usually have the batch-dimension fixed to 1 or a constant. 
I'm not familiar with how the GPU ops are implemented, but I guess as a first cut, it would be nice to have `MUL` to allow 4D input, while the first dimension only supports to be set as 1 ?

**Comment by stalex91** [comment]
Any progress here? How should I use MUL for multidim tensors, lets say [1,257,257,3] so I won't get Init: MUL: 1x257x257x3  cannot be reduced to linear?

**Comment by impjdi** [comment]
@stalex91 I think I don't understand your question.  Shouldn't [1, 257, 257, 3] x [1, 257, 257, 3] work fine as elementwise multiplication?

**Comment by stalex91** [comment]
@impjdi Have met the same problem listed in description but actual reason was before it. So yes, works for me now, thank you.

**Comment by zldrobit** [comment]
@impjdi could you help me to check this model: [yolov5s.tflite](https://drive.google.com/file/d/14PKOXoYt75UqP3Dc4ZWzmORo2WUAXJnq/view?usp=sharing)?
I am using TF 2.3.0 and TFLite 2.3.0 with GPU delegate.


It has 3 element-wise multiplications: [1, 3, 400, 2] x [1, 3, 400, 2], [1, 3, 1600, 2] x [1, 3, 1600, 2], and [1, 3, 6400, 2] x [1, 3, 6400, 2].
When I run the model with GPU delegate, it complains: 
```
E/AndroidRuntime: FATAL EXCEPTION: inference
    Process: org.tensorflow.lite.examples.detection, PID: 10947
    java.lang.IllegalArgumentException: Internal error: Failed to apply delegate: TfLiteGpuDelegate Init: MUL: 1x3x400x2  cannot be reduced to linear.
    TfLiteGpuDelegate Prepare: delegate is not initialized
    Node number 227 (TfLiteGpuDelegateV2) failed to prepare.
    
    Restored original execution plan after delegate application failure.
        at org.tensorflow.lite.NativeInterpreterWrapper.applyDelegate(Native Method)
        at org.tensorflow.lite.NativeInterpreterWrapper.applyDelegates(NativeInterpreterWrapper.java:351)
        at org.tensorflow.lite.NativeInterpreterWrapper.init(NativeInterpreterWrapper.java:82)
        at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:63)
        at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:266)
        at org.tensorflow.lite.examples.detection.tflite.YoloV5Classifier.recreateInterpreter(YoloV5Classifier.java:174)
        at org.tensorflow.lite.examples.detection.tflite.YoloV5Classifier.useGpu(YoloV5Classifier.java:182)
        at org.tensorflow.lite.examples.detection.DetectorActivity.lambda$updateActiveModel$0$DetectorActivity(DetectorActivity.java:213)
        at org.tensorflow.lite.examples.detection.-$$Lambda$DetectorActivity$lqWWUAbeU1gjsHY5oEBIKbdpe60.run(Unknown Source:8)
        at android.os.Handler.handleCallback(Handler.java:793)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:173)
        at android.os.HandlerThread.run(HandlerThread.java:65)
```

**Comment by impjdi** [comment]
I *think* it's coming from the fact that the 2nd tensor is of shape [1, h, w, c].  Can you make a modification to the model and make the 2nd tensor take the shape of [h, w, c] (without the 1st dimension of size 1)?

**Comment by zldrobit** [comment]
@impjdi I updated [my model](https://drive.google.com/file/d/1RQvue0VWb2pD84evjL32dxkQbndSIn10/view?usp=sharing)  according to your suggestion.
The modified MUL op can be inspected in netron:
![image](https://user-images.githubusercontent.com/3896992/93542551-e1a9e680-f98b-11ea-9ac8-5c43da4d4b98.png)


TFLite still complains
```
E/AndroidRuntime: FATAL EXCEPTION: inference
    Process: org.tensorflow.lite.examples.detection, PID: 14431
    java.lang.IllegalArgumentException: Internal error: Failed to apply delegate: TfLiteGpuDelegate Init: MUL: 3x400x2  cannot be reduced to linear.
    TfLiteGpuDelegate Prepare: delegate is not initialized
    Node number 227 (TfLiteGpuDelegateV2) failed to prepare.
    
    Restored original execution plan after delegate application failure.
        at org.tensorflow.lite.NativeInterpreterWrapper.applyDelegate(Native Method)
        at org.tensorflow.lite.NativeInterpreterWrapper.applyDelegates(NativeInterpreterWrapper.java:351)
        at org.tensorflow.lite.NativeInterpreterWrapper.init(NativeInterpreterWrapper.java:82)
        at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:63)
        at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:266)
        at org.tensorflow.lite.examples.detection.tflite.YoloV5Classifier.recreateInterpreter(YoloV5Classifier.java:174)
        at org.tensorflow.lite.examples.detection.tflite.YoloV5Classifier.useGpu(YoloV5Classifier.java:182)
        at org.tensorflow.lite.examples.detection.DetectorActivity.lambda$updateActiveModel$0$DetectorActivity(DetectorActivity.java:208)
        at org.tensorflow.lite.examples.detection.-$$Lambda$DetectorActivity$lqWWUAbeU1gjsHY5oEBIKbdpe60.run(Unknown Source:8)
        at android.os.Handler.handleCallback(Handler.java:793)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:173)
        at android.os.HandlerThread.run(HandlerThread.java:65)
```

**Comment by impjdi** [comment]
Thanks for trying and attaching the updated model!  Will took a deeper look.

**Comment by lei522** [comment]
@impjdi  could you help me to use the multiply op in tflite model with metal delegate？ i am using tf1.15.4 and tflite 1.15.4 with  metal metal delegate

when there is a scalar multiplier it works well,otherwise, the error occurs. i also use resize_bilinear to ensure both inputs have the same shape, it dosen't work.
When I run the model with GPU delegate, it complains:

`2020-12-11 10:41:56.881639+0800 tflite_camera_example[34564:5652810] Initialized TensorFlow Lite runtime.
2020-12-11 10:41:56.881729+0800 tflite_camera_example[34564:5652810] Created TensorFlow Lite delegate for Metal.
2020-12-11 10:41:56.881924+0800 tflite_camera_example[34564:5652810] Metal GPU Frame Capture Enabled
2020-12-11 10:41:56.882223+0800 tflite_camera_example[34564:5652810] Metal API Validation Enabled
2020-12-11 10:41:56.949605+0800 tflite_camera_example[34564:5652810] TfLiteGpuDelegate Prepare: Unsupported op type: apply_mask; custom registry error: Unsupported op: apply_mask; primary registry error: Unsupported op: apply_mask;
`
The modified MUL op can be inspected in netron:
![image](https://user-images.githubusercontent.com/49243657/101855261-1fd73080-3b9e-11eb-8f16-27e99118d0cb.png)

**Comment by lei522** [comment]
@impjdi @impjdi could you help me to use the multiply op in tflite model with metal delegate？ i am using tf1.15.4 and tflite 1.15.4 with metal metal delegate

when there is a scalar multiplier it works well,otherwise, the error occurs. i also use resize_bilinear to ensure both inputs have the same shape, it dosen't work.

When I run the model with GPU delegate, it complains:

`2020-12-11 10:41:56.881639+0800 tflite_camera_example[34564:5652810] Initialized TensorFlow Lite runtime.
2020-12-11 10:41:56.881729+0800 tflite_camera_example[34564:5652810] Created TensorFlow Lite delegate for Metal.
2020-12-11 10:41:56.881924+0800 tflite_camera_example[34564:5652810] Metal GPU Frame Capture Enabled
2020-12-11 10:41:56.882223+0800 tflite_camera_example[34564:5652810] Metal API Validation Enabled
2020-12-11 10:41:56.949605+0800 tflite_camera_example[34564:5652810] TfLiteGpuDelegate Prepare: Unsupported op type: apply_mask; custom registry error: Unsupported op: apply_mask; primary registry error: Unsupported op: apply_mask;
2020-12-11 10:41:56.949691+0800 tflite_camera_example[34564:5652810] Node number 12 (TfLiteMetalDelegate) failed to prepare.
2020-12-11 10:41:56.949741+0800 tflite_camera_example[34564:5652810] Restored previous execution plan after delegate application failure.`

The modified MUL op can be inspected in netron:
![image](https://user-images.githubusercontent.com/49243657/101856044-8577ec80-3b9f-11eb-87ea-de7146014a2d.png)

**Comment by impjdi** [comment]
@lei522 I'm not familiar with the versions, but we removed `apply_mask` quite some time back.  Is it possible for you to try the latest code?

**Comment by lei522** [comment]
@impjdi  Hey:) I have tried the latest code, it works well. thanks for your suggestion! Have a good day!

**Comment by uchihaltachi** [comment]
Excuse me, how can this problem be solved?
TfLiteGpuDelegate Init: MUL: 1x1088x1x1  cannot be reduced to linear.
TfLiteGpuDelegate Prepare: delegate is not initialized
Node number 23608 (TfLiteGpuDelegateV2) failed to prepare.

**Comment by impjdi** [comment]
@uchihaltachi for whatever reason, `MUL` is expecting the input tensor to be a linear tensor.  maybe insert a `RESHAPE` to match the other dimension?  In GPU, `1x1088x1x1` is not the same as `1x1x1x1088`; each dimension has to match.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
