### ISSUE TITLE
module 'tensorflow.python.framework.op_def_registry' has no attribute 'register_op_list'

### ISSUE THREAD

**Issue by thesrisri** [tensorflow/tensorflow#37117]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary):
- TensorFlow version (or github SHA if from source):

**Provide the text output from tflite_convert**
```
(tfpose) C:\Users\S V J KUMAR\Downloads\tf-pose-estimation-master (1)\tf-pose-estimation-master>python run.py --image=p1.jpg
Traceback (most recent call last):
  File "run.py", line 7, in <module>
    from tf_pose import common
  File "C:\Users\S V J KUMAR\Downloads\tf-pose-estimation-master (1)\tf-pose-estimation-master\tf_pose\__init__.py", line 5, in <module>
    from tf_pose.runner import infer, Estimator, get_estimator
  File "C:\Users\S V J KUMAR\Downloads\tf-pose-estimation-master (1)\tf-pose-estimation-master\tf_pose\runner.py", line 8, in <module>
    from tf_pose import eval
  File "C:\Users\S V J KUMAR\Downloads\tf-pose-estimation-master (1)\tf-pose-estimation-master\tf_pose\eval.py", line 13, in <module>
    from tf_pose.estimator import TfPoseEstimator
  File "C:\Users\S V J KUMAR\Downloads\tf-pose-estimation-master (1)\tf-pose-estimation-master\tf_pose\estimator.py", line 14, in <module>
    import tensorflow.contrib.tensorrt as trt
  File "C:\Users\S V J KUMAR\Anaconda3\envs\tfpose\lib\site-packages\tensorflow\contrib\__init__.py", line 22, in <module>
    from tensorflow.contrib import bayesflow
  File "C:\Users\S V J KUMAR\Anaconda3\envs\tfpose\lib\site-packages\tensorflow\contrib\bayesflow\__init__.py", line 24, in <module>
    from tensorflow.contrib.bayesflow.python.ops import csiszar_divergence
  File "C:\Users\S V J KUMAR\Anaconda3\envs\tfpose\lib\site-packages\tensorflow\contrib\bayesflow\python\ops\csiszar_divergence.py", line 26, in <module>
    from tensorflow.contrib.bayesflow.python.ops.csiszar_divergence_impl import *
  File "C:\Users\S V J KUMAR\Anaconda3\envs\tfpose\lib\site-packages\tensorflow\contrib\bayesflow\python\ops\csiszar_divergence_impl.py", line 43, in <module>
    from tensorflow.contrib import framework as contrib_framework
  File "C:\Users\S V J KUMAR\Anaconda3\envs\tfpose\lib\site-packages\tensorflow\contrib\framework\__init__.py", line 93, in <module>
    from tensorflow.contrib.framework.python.ops import *
  File "C:\Users\S V J KUMAR\Anaconda3\envs\tfpose\lib\site-packages\tensorflow\contrib\framework\python\ops\__init__.py", line 28, in <module>
    from tensorflow.contrib.framework.python.ops.variables import *
  File "C:\Users\S V J KUMAR\Anaconda3\envs\tfpose\lib\site-packages\tensorflow\contrib\framework\python\ops\variables.py", line 26, in <module>
    from tensorflow.contrib.framework.python.ops import gen_variable_ops
  File "C:\Users\S V J KUMAR\Anaconda3\envs\tfpose\lib\site-packages\tensorflow\contrib\framework\python\ops\gen_variable_ops.py", line 95, in <module>
    _op_def_lib = _InitOpDefLibrary(b"\nR\n\017ZeroInitializer\022\013\n\003ref\"\001T\200\001\001\032\022\n\noutput_ref\"\001T\200\001\001\"\033\n\001T\022\004type:\020\n\0162\014\001\002\003\t\004\005\006\021\023\026\027\016\230\001\001")
  File "C:\Users\S V J KUMAR\Anaconda3\envs\tfpose\lib\site-packages\tensorflow\contrib\framework\python\ops\gen_variable_ops.py", line 57, in _InitOpDefLibrary
    _op_def_registry.register_op_list(op_list)
AttributeError: module 'tensorflow.python.framework.op_def_registry' has no attribute 'register_op_list'

```

**Standalone code to reproduce the issue** 

import argparse
import logging
import sys
import time
import os

from tf_pose import common
import cv2
import numpy as np
from tf_pose.estimator import TfPoseEstimator
from tf_pose.networks import get_graph_path, model_wh

logger = logging.getLogger('TfPoseEstimatorRun')
logger.handlers.clear()
logger.setLevel(logging.DEBUG)
ch = logging.StreamHandler()
ch.setLevel(logging.DEBUG)
formatter = logging.Formatter('[%(asctime)s] [%(name)s] [%(levelname)s] %(message)s')
ch.setFormatter(formatter)
logger.addHandler(ch)

if __name__ == '__main__':
    os.chdir('..')
    parser = argparse.ArgumentParser(description='tf-pose-estimation run')
    parser.add_argument('--image', type=str, default='./images/p1.jpg')
    parser.add_argument('--model', type=str, default='cmu',
                        help='cmu / mobilenet_thin / mobilenet_v2_large / mobilenet_v2_small')
    parser.add_argument('--resize', type=str, default='0x0',
                        help='if provided, resize images before they are processed. '
                             'default=0x0, Recommends : 432x368 or 656x368 or 1312x736 ')
    parser.add_argument('--resize-out-ratio', type=float, default=4.0,
                        help='if provided, resize heatmaps before they are post-processed. default=1.0')

    args = parser.parse_args()

    w, h = model_wh(args.resize)
    if w == 0 or h == 0:
        e = TfPoseEstimator(get_graph_path(args.model), target_size=(432, 368))
    else:
        e = TfPoseEstimator(get_graph_path(args.model), target_size=(w, h))

    # estimate human poses from a single image !
    image = common.read_imgfile(args.image, None, None)
    if image is None:
        logger.error('Image can not be read, path=%s' % args.image)
        sys.exit(-1)

    t = time.time()
    humans = e.inference(image, resize_to_default=(w > 0 and h > 0), upsample_size=args.resize_out_ratio)
    elapsed = time.time() - t

    logger.info('inference image: %s in %.4f seconds.' % (args.image, elapsed))

    image = TfPoseEstimator.draw_humans(image, humans, imgcopy=False)

    try:
        import matplotlib.pyplot as plt

        fig = plt.figure()
        a = fig.add_subplot(2, 2, 1)
        a.set_title('Result')
        plt.imshow(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))

        bgimg = cv2.cvtColor(image.astype(np.uint8), cv2.COLOR_BGR2RGB)
        bgimg = cv2.resize(bgimg, (e.heatMat.shape[1], e.heatMat.shape[0]), interpolation=cv2.INTER_AREA)

        # show network output
        a = fig.add_subplot(2, 2, 2)
        plt.imshow(bgimg, alpha=0.5)
        tmp = np.amax(e.heatMat[:, :, :-1], axis=2)
        plt.imshow(tmp, cmap=plt.cm.gray, alpha=0.5)
        plt.colorbar()

        tmp2 = e.pafMat.transpose((2, 0, 1))
        tmp2_odd = np.amax(np.absolute(tmp2[::2, :, :]), axis=0)
        tmp2_even = np.amax(np.absolute(tmp2[1::2, :, :]), axis=0)

        a = fig.add_subplot(2, 2, 3)
        a.set_title('Vectormap-x')
        # plt.imshow(CocoPose.get_bgimg(inp, target_size=(vectmap.shape[1], vectmap.shape[0])), alpha=0.5)
        plt.imshow(tmp2_odd, cmap=plt.cm.gray, alpha=0.5)
        plt.colorbar()

        a = fig.add_subplot(2, 2, 4)
        a.set_title('Vectormap-y')
        # plt.imshow(CocoPose.get_bgimg(inp, target_size=(vectmap.shape[1], vectmap.shape[0])), alpha=0.5)
        plt.imshow(tmp2_even, cmap=plt.cm.gray, alpha=0.5)
        plt.colorbar()
        plt.show()
    except Exception as e:
        logger.warning('matplitlib error, %s' % e)
        cv2.imshow('result', image)
        cv2.waitKey()

Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

Also, please include a link to a GraphDef or the model if possible.

**Any other info / logs**
i am using openpose code to find the 3D coordinates of a person in 2D image . by the tutorial i found this code and when running this in python 3 . 

any other way for the accomplishment of the objective can also be entertained. 
will be grateful  for the help 
Include any logs or source code that would be helpful to diagnose the problem.
If including tracebacks, please include the full traceback. Large logs and files
should be attached.

**Comment by ravikyram** [comment]
@thesrisri 

Can you help us with the colab link or simple standalone code with proper indentation and supporting files to reproduce the issue in our environment. It helps us in localizing the issue faster. Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version? Please fill the [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose). Thanks!

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by sumannelli** [comment]
I am also facing the above mentioned issues.
I am running the train.py for object detection with tensorflow 2.1.0 .
@thesrisri: If you got the solution please help me. 
Thanks

**Comment by k-sashank** [comment]
@thesrisri Did your issue get resolved?
If so, please help me out as well.
