### ISSUE TITLE
Unsupported object type float

### ISSUE THREAD

**Issue by damnedOperator** [tensorflow/tensorflow#37123]
**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): Ubuntu 18.10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if
the issue happens on mobile device: N/A
- TensorFlow installed from (source or
binary): binary 
- TensorFlow version (use command below): 2.1.0
- Python version: 3.7.3
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from
source): N/A
- CUDA/cuDNN version: nvcc version 10.1 (V10.1.105)
- GPU model and memory: NVIDIA Quadro P2000 5GB

**Describe the current behavior**
I am loading in a concatenation of two user data sources (one script generated and on read in via `pd.read_csv`).
I paid attention to have both datasources have the same dtypes, column names, etc. 
I concatenate via 
```
fakedata = td.generate_data(40000)
realdata = pd.read_csv("DS.csv")
data = fakedata.append(realdata).reset_index()[fakedata.columns]
```
DataFrame structure is as follows:
| firstname | lastname | company | country | email | fake |
| Lorem | ipsum | Loremcorp | USA | lorem.ipsum@sit.amet | 1 |

whereas `data["fake"]` is the target column having either 0 or 1 as state.
dtypes of the are object and of `data["fake"]` is `int64`.

train input fn:
```
train_input_fn = tf.compat.v1.estimator.inputs.pandas_input_fn(
    data, data["fake"], num_epochs=None, shuffle=True
)
```
training:
```
estimator = tf.estimator.DNNClassifier(
    hidden_units=[500, 100],
    feature_columns=[email_feature_column, 
                     firstname_feature_column, 
                     lastname_feature_column, 
                     country_feature_column, 
                     company_feature_column],
    n_classes=2,
    optimizer=tf.keras.optimizers.Adagrad(lr=0.003))

estimator.train(input_fn=train_input_fn, steps=5000)
```
Feature columns are created via the `text_embedding_column` from tfhub.

When I now try to run the code this error keeps happening:
```
Traceback (most recent call last):
  File "/home/damned/.local/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1367, in _do_call
    return fn(*args)
  File "/home/damned/.local/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1352, in _run_fn
    target_list, run_metadata)
  File "/home/damned/.local/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1445, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InternalError: Unsupported object type float

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tensorflow_model.py", line 67, in <module>
    estimator.train(input_fn=train_input_fn, steps=100000)
  File "/home/damned/.local/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 374, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/damned/.local/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1164, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/home/damned/.local/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1198, in _train_model_default
    saving_listeners)
  File "/home/damned/.local/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1498, in _train_with_estimator_spec
    any_step_done = True
  File "/home/damned/.local/lib/python3.7/site-packages/tensorflow_core/python/training/monitored_session.py", line 885, in __exit__
    self._close_internal(exception_type)
  File "/home/damned/.local/lib/python3.7/site-packages/tensorflow_core/python/training/monitored_session.py", line 923, in _close_internal
    self._sess.close()
  File "/home/damned/.local/lib/python3.7/site-packages/tensorflow_core/python/training/monitored_session.py", line 1190, in close
    self._sess.close()
  File "/home/damned/.local/lib/python3.7/site-packages/tensorflow_core/python/training/monitored_session.py", line 1358, in close
    ignore_live_threads=True)
  File "/home/damned/.local/lib/python3.7/site-packages/tensorflow_core/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/usr/lib/python3/dist-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/home/damned/.local/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/inputs/queues/feeding_queue_runner.py", line 94, in _run
    sess.run(enqueue_op, feed_dict=feed_dict)
  File "/home/damned/.local/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 960, in run
    run_metadata_ptr)
  File "/home/damned/.local/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1183, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/damned/.local/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1361, in _do_run
    run_metadata)
  File "/home/damned/.local/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1386, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Unsupported object type float
```
even if there is no float in the dataset.

**Describe the expected behavior**
`estimator.train(input_fn=train_input_fn, steps=5000)`
Works as expected and trains.

**Comment by damnedOperator** [comment]
Had broken values in the dataframe. Checking the dataframe with `np.unique(df[column]` and `df[df.isnan()]` helped solving the issue.
