### ISSUE TITLE
Structure type Errors in TensorFlow

### ISSUE THREAD

**Issue by rehanmahmood** [tensorflow/tensorflow#37149]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow):  **YES**
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): **`Mac OS Catalina`**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if
the issue happens on mobile device: 
- TensorFlow installed from (source or
binary): **`binary`**
- TensorFlow version (use command below): **`2.1`**
- Python version: **`3.7.2`**
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from
source): 
- CUDA/cuDNN version: **10.2**
- GPU model and memory: **4gb ram**   Graphics:  **Intel HD Graphics 4000 1536 MB**

**Describe the current behavior**
I am attempting to build a stock prediction model using LSTM
Here are a list of my import statements:

```
import requests
import math
import numpy as np
import pandas as pd
import pandas_datareader as web
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import LSTM, Dense
from sklearn.preprocessing import MinMaxScaler
from bs4 import BeautifulSoup
import matplotlib.pyplot as plt
from datetime import datetime, date
```

Here is the code for the model itself:

```

#split the data into x-train and y-train datasets
x_train = []
y_train = []

for i in range(20, len(train_data)):
    x_train.append(train_data[i-20:i, 0])
    y_train.append(train_data[i, 0])

    if i<= 20:
        print(x_train)
        print(y_train)

#convert x-train and y-train to numpy arrays to train models
x_train, y_train = np.array(x_train), np.array(y_train)

#reshape the data, LSTM model expects 3D dataset
x_train = np.reshape(x_train, (x_train.shape[0], x_train.shape[1], 1))

#Build LSTM MODEL
model = tf.keras.Sequential([
    tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(64)),
    tf.keras.layers.Dense(25, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

model.compile(loss='mean_squared_error',
              optimizer=tf.keras.optimizers.Adam(1e-4),
              metrics=['accuracy'])

model.fit(x_train, y_train, batch_size=1, epochs=1)

#create testing data set
#creat new array containing scaled values
test_data = scaled_data[training_data_len - 20: , :]

#create the datasets x-test and y-test
x_test=[]
y_test=dataset[training_data_len:, :]
for i in range(20, len(test_data)):
    x_test.append(test_data[i-20:i, 0])

#convert data to numpy array
x_test = np.array(x_test)

#reshape data to 3D
x_test = np.reshape(x_test, (x_test.shape[0], x_test.shape[1], 1))

#Get predicted price values
predictions = model.predict(x_test)
predictions = scaler.inverse_transform(predictions)

#get root mean squared error
rmse=np.sqrt(np.mean(((predictions- y_test)**2)))
print(rmse)

```
Executing this code returns the error:

```
Traceback (most recent call last):
  File "/Users/owner/Desktop/algo/predict.py", line 98, in <module>
    x_test = np.reshape(x_test, (x_test.shape[0], x_test.shape[1], 1))
IndexError: tuple index out of range
```
**Describe the expected behavior**
`print(rmse)` should return the average.

I am new to tensorflow and neural programming so I am not completely sure what to do here.
If I try `x_test = np.reshape(x_test, (x_test.shape[0]))`

I get this error:

```
Traceback (most recent call last):
  File "/Users/owner/Desktop/algo/predict.py", line 103, in <module>
    predictions = model.predict(x_test)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 1013, in predict
    use_multiprocessing=use_multiprocessing)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 498, in predict
    workers=workers, use_multiprocessing=use_multiprocessing, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 475, in _model_iteration
    total_epochs=1)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 128, in run_one_epoch
    batch_outs = execution_function(iterator)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 98, in execution_function
    distributed_function(input_fn))
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 568, in __call__
    result = self._call(*args, **kwds)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 615, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 497, in _initialize
    *args, **kwds))
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 2389, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 2703, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 2593, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/framework/func_graph.py", line 978, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 439, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 85, in distributed_function
    per_replica_function, args=args)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/distribute/distribute_lib.py", line 763, in experimental_run_v2
    return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/distribute/distribute_lib.py", line 1819, in call_for_each_replica
    return self._call_for_each_replica(fn, args, kwargs)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/distribute/distribute_lib.py", line 2164, in _call_for_each_replica
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/api.py", line 292, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 212, in _predict_on_batch
    result = predict_on_batch(model, x)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 556, in predict_on_batch
    return predict_on_batch_fn(inputs)  # pylint: disable=not-callable
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 737, in __call__
    self.name)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/input_spec.py", line 177, in assert_input_compatibility
    str(x.shape.as_list()))
ValueError: Input 0 of layer sequential is incompatible with the layer: expected ndim=3, found ndim=2. Full shape received: [32, 1]
```

Any help will be greatly appreciated, I am dying to learn what is wrong!
Thankyou,
RRR.

**Comment by SivamPillai** [comment]
It seems like your x_test is not of the size you expect it to be. Are you able to provide the following values:
`test_data.shape, x_test.shape, scaled_data.shape, training_data_len`

Note that `.shape` does not work on lists. So obtain the values after conversion to numpy.

**Comment by rehanmahmood** [comment]
training_data_len = 50 . This also prints 311 sometimes
test_data.shape = (20, 1)
scaled_data.shape = (311, 1)
x_test.shape = (0,)

Sometimes the model tests with a sample of 30 and sometimes with a sample of 291

**Comment by SivamPillai** [comment]
> training_data_len = 50 . This also prints 311 sometimes
> test_data.shape = (20, 1)
> scaled_data.shape = (311, 1)
> x_test.shape = (0,)
> 
> Sometimes the model tests with a sample of 30 and sometimes with a sample of 291

Here, what do you mean by **sometimes**?

When training_data_len = 311, test_data.shape will be (20,1). If this happens x_test will end up being empty (shape=(0,)), based on your code.

In that case, the error you have is expected. 
```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-74-83e32771dadc> in <module>
----> 1 x_test = np.reshape(x_test, (x_test.shape[0], x_test.shape[1], 1))

IndexError: tuple index out of range
```

**Now the issue is how you compute training_data_len.**

**Comment by rehanmahmood** [comment]
This is how I compute training data len:

Regarding the sometimes,  when I printed( training_data_len) the only modification i made to the code was to add `print(training_data_len)` When I ran the program the length was 291.
I went back to the code and added `print(scaled_data.shape)` the sample size was 30.

```

#get closing price
data = df.filter(['Close'])

#get closing price values
dataset = data.values

#set training data length to len of total data set
training_data_len = math.ceil(len(dataset))
print(training_data_len)

#Scale the data
scaler = MinMaxScaler(feature_range=(0,1))
scaled_data = scaler.fit_transform(dataset)

```

**Comment by SivamPillai** [comment]
I think there is a problem with your for loop where you are trying to generate a sequence data of window size 20 for the test data. Assuming the training_data_len is 311, Can you run your code by updating, the range of for loop:

```
for i in range(20, len(test_data)+1):
    x_test.append(test_data[i-20:i, 0])
```
Otherwise, `len(test_data) = 20 `and the for loop will not happen.

**Comment by rehanmahmood** [comment]
Okay Thank you,  I ran the code with the update and this error returned.

```
Traceback (most recent call last):
  File "/Users/owner/Desktop/algo/predict.py", line 103, in <module>
    x_test = np.reshape(x_test, (x_test.shape[0]))
  File "<__array_function__ internals>", line 6, in reshape
  File "/usr/local/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 301, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/usr/local/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 61, in _wrapfunc
    return bound(*args, **kwds)
ValueError: cannot reshape array of size 20 into shape (1,)
```
Any ideas?

**Comment by SivamPillai** [comment]
As the error reports... your test data is of size 20, so it cannot be reshaped to size 1. I believe, you should be using the reshape as in the original code you shared:

`
x_test = np.reshape(x_test, (x_test.shape[0], x_test.shape[1], 1))`

**Comment by rehanmahmood** [comment]
Yes Thank you sir, that fixed the error, however it did present me with a new error.

https://github.com/tensorflow/tensorflow/issues/37159
