### ISSUE TITLE
Plotting Data Using model.predict

### ISSUE THREAD

**Issue by rehanmahmood** [tensorflow/tensorflow#37159]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): **YES**
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): **MacOS CATALINA**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if
the issue happens on mobile device: 
- TensorFlow installed from (source or
binary): **BINARY**
- TensorFlow version (use command below): 2.1
- Python version: 3.7.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from
source): 
- CUDA/cuDNN version: 10.2
- GPU model and memory:

**Describe the current behavior**

I am attempting to plot the prediction values .  However predictions is 2-D and the data must be one dimensional. 

Here is the predictions code:
```
#Get predicted price values
predictions = model.predict(x_test)
predictions = scaler.inverse_transform(predictions)
print(predictions.shape)

#get root mean squared error
rmse = np.sqrt(((predictions - y_test) ** 2).mean())
print(rmse)

#Plot the data
train = data[:training_data_len]
valid = data[training_data_len:]
valid['Predictions'] = predictions

#Visualize the data
plt.figure(figsize=(16,8))
plt.title('Model')
plt.xlabel('Date', fontsize=18)
plt.ylabel('Close Price USD ($)', fontsize=18)
plt.plot(train['Close'])
plt.plot(valid[['Close', 'Predictions']])
plt.legend(['Train', 'Val', 'Predictions'], loc='lower right')
plt.show()
```
**Describe the expected behavior**

This should just return a graph of the predicted values.  Instead I receive the following error.
```
Traceback (most recent call last):
  File "/Users/owner/Desktop/algo/predict.py", line 120, in <module>
    valid['Predictions'] = predictions
  File "/usr/local/lib/python3.7/site-packages/pandas/core/frame.py", line 3487, in __setitem__
    self._set_item(key, value)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/frame.py", line 3563, in _set_item
    self._ensure_valid_index(value)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/frame.py", line 3540, in _ensure_valid_index
    value = Series(value)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/series.py", line 314, in __init__
    data = sanitize_array(data, index, dtype, copy, raise_cast_failure=True)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 729, in sanitize_array
    raise Exception("Data must be 1-dimensional")
Exception: Data must be 1-dimensional
```

How can I change predictions to make it 1-D?
Thank You,
RRR.

**Comment by amahendrakar** [comment]
@rehanmahmood,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here. Thanks!

**Comment by rehanmahmood** [comment]
Yess for sure here it is:
```
import requests
import math
import numpy as np
import pandas as pd
import pandas_datareader as web
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import LSTM, Embedding
from tensorflow.keras.layers import Dense
from sklearn.preprocessing import MinMaxScaler
from bs4 import BeautifulSoup
import matplotlib.pyplot as plt
from datetime import datetime, date
plt.style.use('fivethirtyeight')
today = date.today()

df = web.DataReader('GC=F', data_source='yahoo', start='2019-02-14', end=str(today))

#print(df)

plt.figure(figsize=(16,8))
plt.title('GOLD PRICE HISTORY')
plt.plot(df['Close'])
plt.xlabel('Date', fontsize=18)
plt.ylabel('Close price USD($)', fontsize=18)
#plt.show()

#get closing price
data = df.filter(['Close'])
#get closing price values
dataset = data.values
#set training data length to 91% of total data set
training_data_len = math.ceil(len(dataset))
print(training_data_len)
#Scale the data
scaler = MinMaxScaler(feature_range=(0,1))
scaled_data = scaler.fit_transform(dataset)

#create training data set
#create the scaled training data set
train_data = scaled_data[0: training_data_len , :]

#split the data into x-train and y-train datasets
x_train = []
y_train = []

for i in range(20, len(train_data)):
    x_train.append(train_data[i-20:i, 0])
    y_train.append(train_data[i, 0])

    if i<= 20:
        
        #print(x_train)
        #print(y_train)
        pass

#convert x-train and y-train to numpy arrays to train models
x_train, y_train = np.array(x_train), np.array(y_train)

#reshape the data, LSTM model expects 3D dataset
x_train = np.reshape(x_train, (x_train.shape[0], x_train.shape[1], 1))

#Build LSTM MODEL
model = tf.keras.Sequential([
    #tf.keras.layers.Embedding(encoder.vocab_size, 64),
    tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(64)),
    tf.keras.layers.Dense(25, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

model.compile(loss='mean_squared_error',
              optimizer=tf.keras.optimizers.Adam(1e-4),
              metrics=['accuracy'])

model.fit(x_train, y_train, batch_size=1, epochs=1)

#create testing data set
#creat new array containing scaled values
test_data = scaled_data[training_data_len - 20: , :]
print(test_data.shape)

#create the datasets x-test and y-test
x_test=[]
y_test=dataset[training_data_len:, :]
for i in range(20, len(test_data)+1):
    x_test.append(test_data[i-20:i, 0])

#convert data to numpy array
x_test = np.array(x_test)

#reshape data to 3D
x_test = np.reshape(x_test, (x_test.shape[0], x_test.shape[1], 1))
print(x_test.shape)

#Get predicted price values
predictions = model.predict(x_test)
predictions = scaler.inverse_transform(predictions)
print(predictions.shape)


#get root mean squared error
rmse = np.sqrt(((predictions - y_test) ** 2).mean())
print(rmse)

#Plot the data
train = data[:training_data_len]
valid = data[training_data_len:]
valid['Predictions'] = predictions

#Visualize the data
plt.figure(figsize=(16,8))
plt.title('Model')
plt.xlabel('Date', fontsize=18)
plt.ylabel('Close Price USD ($)', fontsize=18)
plt.plot(train['Close'])
plt.plot(valid[['Close', 'Predictions']])
plt.legend(['Train', 'Val', 'Predictions'], loc='lower right')
plt.show()

**Comment by rehanmahmood** [comment]
@amahendrakar Any idea mate?

**Comment by amahendrakar** [comment]
@rehanmahmood,
I tried to reproduce the issue and looks like the error is related to Pandas. Even the error log shows the same. Please take a look at the gist [here](https://colab.sandbox.google.com/gist/amahendrakar/f33ede73992cee3c941d1625304638d9/37159.ipynb).

This question is better asked on StackOverflow since it is not a Tensorflow bug or feature request. There is also a larger community that reads questions there.Thanks!

**Comment by rehanmahmood** [comment]
How do you know the issue is with pandas?  Am I not using numpy to reshape my variables into different dimensions?

**Comment by amahendrakar** [comment]
@rehanmahmood,

The error log you have submitted shows that there is an issue with the line `valid['Predictions'] = predictions`, which is a Pandas operation on the dataframe named `valid`.

The stack trace also shows that the error occurred while performing a Pandas operation.   
  File "/usr/local/lib/python3.7/site-packages/**pandas**/core/frame.py", line 3487, in __setitem__
    self._set_item(key, value)
  File "/usr/local/lib/python3.7/site-packages/**pandas**/core/frame.py", line 3563, in _set_item
    self._ensure_valid_index(value)
  File "/usr/local/lib/python3.7/site-packages/**pandas**/core/frame.py", line 3540, in _ensure_valid_index

**Comment by rehanmahmood** [comment]
Ohh okok yes that makes sense.  Thank you for all your help, much appreciated.
