### ISSUE TITLE
using tensorflow-hub model elmo ensorflow.python.framework.errors_impl.ResourceExhaustedError

### ISSUE THREAD

**Issue by DavidInWuhanChina** [tensorflow/tensorflow#37162]
Python 3.6.10 
tensorflow 1.12.0 gpu_py36he68c306_0
tensorflow-base 1.12.0 gpu_py36h8e0ae2d_0
tensorflow-gpu 1.12.0 h0d30ee6_0
tensorflow-hub 0.5.0 pypi_0 pypi cudatoolkit 9.0 h13b8566_0
cudnn 7.6.5  cuda9.0_0

NVIDIA-SMI 418.87.01 Driver Version: 418.87.01 CUDA Version: 10.1
0 Tesla V100-SXM2... Off | 00000000:18:00.0 Off | 0 | | N/A 37C P0 43W / 300W | 11MiB / 32480MiB | 0% Default | +-------------------------------+----------------------+----------------------+ | 1 Tesla V100-SXM2... Off | 00000000:3B:00.0 Off | 0 | | N/A 34C P0 42W / 300W | 11MiB / 32480MiB | 0% Default | +-------------------------------+----------------------+----------------------+ | 2 Tesla V100-SXM2... Off | 00000000:86:00.0 Off | 0 | | N/A 34C P0 43W / 300W | 11MiB / 32480MiB | 0% Default | +-------------------------------+----------------------+----------------------+ | 3 Tesla V100-SXM2... Off | 00000000:AF:00.0 Off | 0 | | N/A 38C P0 43W / 300W | 11MiB / 32480MiB | 0% Default

error: Using TensorFlow backend. /share/nishome/19930072_0/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'. _np_qint8 = np.dtype([("qint8", np.int8, 1)]) /share/nishome/19930072_0/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'. _np_quint8 = np.dtype([("quint8", np.uint8, 1)]) /share/nishome/19930072_0/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'. _np_qint16 = np.dtype([("qint16", np.int16, 1)]) /share/nishome/19930072_0/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'. _np_quint16 = np.dtype([("quint16", np.uint16, 1)]) /share/nishome/19930072_0/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'. _np_qint32 = np.dtype([("qint32", np.int32, 1)]) /share/nishome/19930072_0/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:532: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'. np_resource = np.dtype([("resource", np.ubyte, 1)]) INFO:bert_bilstm_softmax.py:running bert_bilstm_softmax.py INFO:root:loading data... INFO:absl:Using /tmp/tfhub_modules to cache modules. INFO:tensorflow:Saver not created because there are no variables in the graph to restore INFO:tensorflow:Saver not created because there are no variables in the graph to restore INFO:tensorflow:Saver not created because there are no variables in the graph to restore INFO:tensorflow:Saver not created because there are no variables in the graph to restore 38 7 (2742, 38, 1024) (392, 38, 1024) (2742, 38, 2) (392, 38, 2)

Layer (type) Output Shape Param #
input_1 (InputLayer) (None, 38, 1024) 0

batch_normalization_1 (Batch (None, 38, 1024) 4096

masking_1 (Masking) (None, 38, 1024) 0

bidirectional_1 (Bidirection (None, 38, 256) 1180672

bidirectional_2 (Bidirection (None, 38, 256) 394240

dropout_1 (Dropout) (None, 38, 256) 0

dense_1 (Dense) (None, 38, 2) 514
Total params: 1,579,522 Trainable params: 1,577,474 Non-trainable params: 2,048

Train on 2742 samples, validate on 392 samples Epoch 1/30 2020-02-28 19:42:36.337714: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA 2020-02-28 19:42:36.787351: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: name: Tesla V100-SXM2-32GB major: 7 minor: 0 memoryClockRate(GHz): 1.53 pciBusID: 0000:18:00.0 totalMemory: 31.72GiB freeMemory: 31.41GiB 2020-02-28 19:42:36.957634: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 1 with properties: name: Tesla V100-SXM2-32GB major: 7 minor: 0 memoryClockRate(GHz): 1.53 pciBusID: 0000:3b:00.0 totalMemory: 31.72GiB freeMemory: 31.41GiB 2020-02-28 19:42:37.143501: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 2 with properties: name: Tesla V100-SXM2-32GB major: 7 minor: 0 memoryClockRate(GHz): 1.53 pciBusID: 0000:86:00.0 totalMemory: 31.72GiB freeMemory: 31.41GiB 2020-02-28 19:42:37.336031: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 3 with properties: name: Tesla V100-SXM2-32GB major: 7 minor: 0 memoryClockRate(GHz): 1.53 pciBusID: 0000:af:00.0 totalMemory: 31.72GiB freeMemory: 31.41GiB 2020-02-28 19:42:37.336143: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0, 1, 2, 3 2020-02-28 19:42:41.617032: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix: 2020-02-28 19:42:41.617079: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988] 0 1 2 3 2020-02-28 19:42:41.617090: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0: N Y Y Y 2020-02-28 19:42:41.617122: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 1: Y N Y Y 2020-02-28 19:42:41.617132: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 2: Y Y N Y 2020-02-28 19:42:41.617158: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 3: Y Y Y N 2020-02-28 19:42:41.617526: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 30472 MB memory) -> physical GPU (device: 0, name: Tesla V100-SXM2-32GB, pci bus id: 0000:18:00.0, compute capability: 7.0) 2020-02-28 19:42:41.634656: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 30472 MB memory) -> physical GPU (device: 1, name: Tesla V100-SXM2-32GB, pci bus id: 0000:3b:00.0, compute capability: 7.0) 2020-02-28 19:42:41.635333: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:2 with 30472 MB memory) -> physical GPU (device: 2, name: Tesla V100-SXM2-32GB, pci bus id: 0000:86:00.0, compute capability: 7.0) 2020-02-28 19:42:41.635518: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:3 with 30472 MB memory) -> physical GPU (device: 3, name: Tesla V100-SXM2-32GB, pci bus id: 0000:af:00.0, compute capability: 7.0) 2020-02-28 19:43:06.568339: W tensorflow/core/common_runtime/bfc_allocator.cc:267] Allocator (GPU_0_bfc) ran out of memory trying to allocate 8.94GiB. Current allocation summary follows. 2020-02-28 19:43:06.568442: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (256): Total Chunks: 147, Chunks in use: 145. 36.8KiB allocated for chunks. 36.2KiB in use in bin. 1.1KiB client-requested in use in bin.

2020-02-28 19:43:06.568541: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (65536): Total Chunks: 36, Chunks in use: 36. 2.27MiB allocated for chunks. 2.27MiB in use in bin. 2.25MiB client-requested in use in bin. 2020-02-28 19:43:06.568552: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (131072): Total Chunks: 18, Chunks in use: 18. 2.42MiB allocated for chunks. 2.42MiB in use in bin. 2.38MiB client-requested in use in bin. 2020-02-28 19:43:06.568564: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (262144): Total Chunks: 19, Chunks in use: 18. 5.06MiB allocated for chunks. 4.69MiB in use in bin. 4.69MiB client-requested in use in bin. 2020-02-28 19:43:06.568577: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (524288): Total Chunks: 31, Chunks in use: 28. 16.48MiB allocated for chunks. 14.59MiB in use in bin. 14.59MiB client-requested in use in bin. 2020-02-28 19:43:06.568588: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (1048576): Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin. 2020-02-28 19:43:06.568600: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (2097152): Total Chunks: 7, Chunks in use: 7. 14.00MiB allocated for chunks. 14.00MiB in use in bin. 14.00MiB client-requested in use in bin. 2020-02-28 19:43:06.568611: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (4194304): Total Chunks: 2, Chunks in use: 1. 8.00MiB allocated for chunks. 4.00MiB in use in bin. 4.00MiB client-requested in use in bin. 2020-02-28 19:43:06.568624: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (8388608): Total Chunks: 4, Chunks in use: 4. 32.00MiB allocated for chunks. 32.00MiB in use in bin. 32.00MiB client-requested in use in bin. 2020-02-28 19:43:06.568636: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (16777216): Total Chunks: 5, Chunks in use: 4. 80.00MiB allocated for chunks. 64.00MiB in use in bin. 64.00MiB client-requested in use in bin. 2020-02-28 19:43:06.568648: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (33554432): Total Chunks: 1, Chunks in use: 0. 32.02MiB allocated for chunks. 0B in use in bin. 0B client-requested in use in bin. 2020-02-28 19:43:06.568661: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (67108864): Total Chunks: 5, Chunks in use: 4. 340.04MiB allocated for chunks. 256.00MiB in use in bin. 256.00MiB client-requested in use in bin. 2020-02-28 19:43:06.568670: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (134217728): Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin. 2020-02-28 19:43:06.568679: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (268435456): Total Chunks: 13, Chunks in use: 7. 29.24GiB allocated for chunks. 18.58GiB in use in bin. 18.58GiB client-requested in use in bin. 2020-02-28 19:43:06.568687: I tensorflow/core/common_runtime/bfc_allocator.cc:613] Bin for 8.94GiB was 256.00MiB, Chunk State: 2020-02-28 19:43:06.568701: I tensorflow/core/common_runtime/bfc_allocator.cc:619] Size: 317.98MiB | Requested Size: 317.98MiB | in_use: 0, prev: Size: 256B | Requested Size: 4B | in_use: 1, next: Size: 317.98MiB | Requested Size: 317.98MiB | in_use: 1 2020-02-28 19:43:06.568712: I tensorflow/core/common_runtime/bfc_allocator.cc:619] Size: 635.96MiB | Requested Size: 623.24MiB | in_use: 0, prev: Size: 317.98MiB | Requested Size: 317.98MiB | in_use: 1, next: Size: 635.96MiB | Requested Size: 635.96MiB | in_use: 1 2020-02-28 19:43:06.568721: I tensorflow/core/common_runtime/bfc_allocator.cc:619] Size: 1.19GiB | Requested Size: 1.17GiB | in_use: 0, prev: Size: 623.24MiB | Requested Size: 623.24MiB | in_use: 1, next: Size: 1.19GiB | Requested Size: 1.19GiB | in_use: 1 2020-02-28 19:43:06.568729: I tensorflow/core/common_runtime/bfc_allocator.cc:619] Size: 1.62GiB | Requested Size: 80.0KiB | in_use: 0, prev: Size: 8.94GiB | Requested Size: 8.94GiB | in_use: 1 2020-02-28 19:43:06.568739: I tensorflow/core/common_runtime/bfc_allocator.cc:619] Size: 2.33GiB | Requested Size: 1.43GiB | in_use: 0, prev: Size: 1.19GiB | Requested Size: 1.19GiB | in_use: 1, next: Size: 2.33GiB | Requested Size: 2.33GiB | in_use: 1 2020-02-28 19:43:06.568776: I tensorflow/core/common_runtime/bfc_allocator.cc:619] Size: 4.57GiB | Requested Size: 4.57GiB | in_use: 0, prev: Size: 2.33GiB | Requested Size: 2.33GiB | in_use: 1, next: Size: 4.57GiB | Requested Size: 4.57GiB | in_use: 1 2020-02-28 19:43:06.568791: I tensorflow/core/common_runtime/bfc_allocator.cc:632] Chunk at 0x7f566e000000 of size 1280 0x7f568efea100 of size 65536 2020-02-28 19:43:06.570830: I tensorflow/core/common_runtime/bfc_allocator.cc:632] Chunk at 0x7f568effa100 of size 65536 2020-02-28 19:43:06.570835: I tensorflow/core/common_runtime/bfc_allocator.cc:632] Chunk at 0x7f568f00a100 of size 65536 2020x7f568f3ea100 of size 524288 2020-02-28 19:43:06.571038: I tensorflow/core/common_runtime/bfc_allocator.cc:632] Chunk at 0x7f568f46a100 of size 65536 202 2507372544 totalling 2.33GiB 2020-02-28 19:43:06.571302: I tensorflow/core/common_runtime/bfc_allocator.cc:641] 1 Chunks of size 4908048384 totalling 4.57GiB 2020-02-28 19:43:06.571308: I tensorflow/core/common_runtime/bfc_allocator.cc:641] 1 Chunks of size 9602703360 totalling 8.94GiB 2020-02-28 19:43:06.571314: I tensorflow/core/common_runtime/bfc_allocator.cc:645] Sum Total of in-use chunks: 18.97GiB 2020-02-28 19:43:06.571322: I tensorflow/core/common_runtime/bfc_allocator.cc:647] Stats: Limit: 31952542106 InUse: 20365600256 MaxInUse: 20365600256 NumAllocs: 582 MaxAllocSize: 9602703360

2020-02-28 19:43:06.571344: W tensorflow/core/common_runtime/bfc_allocator.cc:271] ****_******___*****______*********_______________**********************************************_____ 2020-02-28 19:43:06.571376: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at conv_ops.cc:746 : Resource exhausted: OOM when allocating tensor with shape[2742,512,38,45] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc 2020-02-28 19:43:16.573348: W tensorflow/core/common_runtime/bfc_allocator.cc:267] Allocator (GPU_0_bfc) ran out of memory trying to allocate 17.49GiB. Current allocation summary follows. 2020-02-28 19:43:16.573412: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (256): Total Chunks: 147, Chunks in use: 145. 36.8KiB allocated for chunks. 36.2KiB in use in bin. 1.1KiB client-requested in use in bin. 2020-02-28 19:43:16.573425: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (512): Total Chunks: 19, Chunks in use: 17. 9.5KiB allocated for chunks. 8.5KiB in use in bin. 8.5KiB client-requested in use in bin. 2020-02-28 19:43:16.573434: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (1024): Total Chunks: 2, Chunks in use: 2. 2.2KiB allocated for chunks. 2.2KiB in use in bin. 2.0KiB client-requested in use in bin. 2020-02-28 19:43:16.573443: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (2048): Total Chunks: 24, Chunks in use: 22. 48.2KiB allocated for chunks. 44.0KiB in use in bin. 44.0KiB client-requested in use in bin. 2020-02-28 19:43:16.573453: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (4096): Total Chunks: 15, Chunks in use: 15. 60.0KiB allocated for chunks. 60.0KiB in use in bin. 60.0KiB client-requested in use in bin. 2020-02-28 19:43:16.573468: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (8192): Total Chunks: 11, Chunks in use: 6. 111.5KiB allocated for chunks. 53.5KiB in use in bin. 53.4KiB client-requested in use in bin. 2020-02-28 19:43:16.573478: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (16384): Total Chunks: 1, Chunks in use: 0. 16.2KiB allocated for chunks. 0B in use in bin. 0B client-requested in use in bin. 2020-02-28 19:43:16.573486: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (32768): Total Chunks: 3, Chunks in use: 0. 96.2KiB allocated for chunks. 0B in use in bin. 0B client-requested in use in bin. 2020-02-28 19:43:16.573494: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (65536): Total Chunks: 36, Chunks in use: 36. 2.27MiB allocated for chunks. 2.27MiB in use in bin. 2.25MiB client-requested in use in bin. 2020-02-28 19:43:16.573503: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (131072): Total Chunks: 17, Chunks in use: 16. 2.24MiB allocated for chunks. 2.00MiB in use in bin. 2.00MiB client-requested in use in bin. 2020-02-28 19:43:16.573512: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (262144): Total Chunks: 18, Chunks in use: 18. 4.69MiB allocated for chunks. 4.69MiB in use in bin. 4.69MiB client-requested in use in bin. 2020-02-28 19:43:16.573520: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (524288): Total Chunks: 30, Chunks in use: 28. 15.60MiB allocated for chunks. 14.59MiB in use in bin. 14.59MiB client-requested in use in bin. 2020-02-28 19:43:16.573528: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (1048576): Total Chunks: 1, Chunks in use: 0. 1.44MiB allocated for chunks. 0B in use in bin. 0B client-requested in use in bin. 2020-02-28 19:43:16.573537: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (2097152): Total Chunks: 7, Chunks in use: 7. 14.00MiB allocated for chunks. 14.00MiB in use in bin. 14.00MiB client-requested in use in bin. 2020-02-28 19:43:16.573545: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (4194304): Total Chunks: 2, Chunks in use: 1. 8.00MiB allocated for chunks. 4.00MiB in use in bin. 4.00MiB client-requested in use in bin. 2020-02-28 19:43:16.573553: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (8388608): Total Chunks: 4, Chunks in use: 4. 32.00MiB allocated for chunks. 32.00MiB in use in bin. 32.00MiB client-requested in use in bin. 2020-02-28 19:43:16.573562: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (16777216): Total Chunks: 5, Chunks in use: 4. 80.00MiB allocated for chunks. 64.00MiB in use in bin. 64.00MiB client-requested in use in bin. 2020-02-28 19:43:16.573570: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (33554432): Total Chunks: 1, Chunks in use: 0. 32.02MiB allocated for chunks. 0B in use in bin. 0B client-requested in use in bin. 2020-02-28 19:43:16.573579: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (67108864): Total Chunks: 5, Chunks in use: 4. 340.04MiB allocated for chunks. 256.00MiB in use in bin. 256.00MiB client-requested in use in bin. 2020-02-28 19:43:16.573587: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (134217728): Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin. 2020-02-28 19:43:16.573595: I tensorflow/core/common_runtime/bfc_allocator.cc:597] Bin (268435456): Total Chunks: 12, Chunks in use: 6. 29.24GiB allocated for chunks. 9.64GiB in use in bin. 9.64GiB client-requested in use in bin. 2020-02-28 19:43:16.573604: I tensorflow/core/common_runtime/bfc_allocator.cc:613] Bin for 17.49GiB was 256.00MiB, Chunk State: 2020-02-28 19:43:16.573618: I tensorflow/core/common_runtime/bfc_allocator.cc:619] Size: 317.98MiB | Requested Size: 317.98MiB | in_use: 0, prev: Size: 256B | Requested Size: 4B | in_use: 1, next: Size: 317.98MiB | Requested Size: 317.98MiB | in_use: 1 2020-02-28 19:43:16.573630: I tensorflow/core/common_runtime/bfc_allocator.cc:619] Size: 635.96MiB | Requested Size: 623.24MiB | in_use: 0, prev: Size: 317.98MiB | Requested Size: 317.98MiB | in_use: 1, next: Size: 635.96MiB | Requested Size: 635.96MiB | in_use: 1 2020-02-28 19:43:16.573641: I tensorflow/core/common_runtime/bfc_allocator.cc:619] Size: 1.19GiB | Requested Size: 1.17GiB | in_use: 0, prev: Size: 623.24MiB | Requested Size: 623.24MiB | in_use: 1, next: Size: 1.19GiB | Requested Size: 1.19GiB | in_use: 1 2020-02-28 19:43:16.573650: I tensorflow/core/common_runtime/bfc_allocator.cc:619] Size: 2.33GiB | Requested Size: 1.43GiB | in_use: 0, prev: Size: 1.19GiB | Requested Size: 1.19GiB | in_use: 1, next: Size: 2.33GiB | Requested Size: 2.33GiB | in_use: 1 2020-02-28 19:43:16.573695: I tensorflow/core/common_runtime/bfc_allocator.cc:619] Size: 4.57GiB | Requested Size: 4.57GiB | in_use: 0, prev: Size: 2.33GiB | Requested Size: 2.33GiB | in_use: 1, next: Size: 4.57GiB | Requested Size: 4.57GiB | in_use: 1 2020-02-28 19:43:16.573704: I tensorflow/core/common_runtime/bfc_allocator.cc:619] Size: 10.57GiB | Requested Size: 8.94GiB | in_use: 0, prev: Size: 4.57GiB | Requested Size: 4.57GiB | in_use: 1 2020-02-28 19:43:16.573714: I tensorflow/core/common_runtime/bfc_allocator.cc:632] Chunk at 0x7f566e000000 of size 1280 2020-02-28 19:43:16.573720: I tensorflow/core/common_runtime/bfc_allocator.cc:632] Chunk at 0x7f566e000500 of size 256

2020-02-28 19:43:16.576222: I tensorflow/core/common_runtime/bfc_allocator.cc:641] 1 Chunks of size 1024 totalling 1.0KiB 666854400 totalling 635.96MiB 2020-02-28 19:43:16.576352: I tensorflow/core/common_runtime/bfc_allocator.cc:641] 1 Chunks of size 1280360448 totalling 1.19GiB 2020-02-28 19:43:16.576358: I tensorflow/core/common_runtime/bfc_allocator.cc:641] 1 Chunks of size 2507372544 totalling 2.33GiB 2020-02-28 19:43:16.576364: I tensorflow/core/common_runtime/bfc_allocator.cc:641] 1 Chunks of size 4908048384 totalling 4.57GiB 2020-02-28 19:43:16.576371: I tensorflow/core/common_runtime/bfc_allocator.cc:645] Sum Total of in-use chunks: 10.02GiB 2020-02-28 19:43:16.576380: I tensorflow/core/common_runtime/bfc_allocator.cc:647] Stats: Limit: 31952542106 InUse: 10762452480 MaxInUse: 20365600256 NumAllocs: 582 MaxAllocSize: 9602703360

2020-02-28 19:43:16.576403: W tensorflow/core/common_runtime/bfc_allocator.cc:271] ***************______*********_______________****************___________________________________ 2020-02-28 19:43:16.576430: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at conv_ops.cc:446 : Resource exhausted: OOM when allocating tensor with shape[2742,1024,38,44] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc Traceback (most recent call last): File "bert_bilstm_softmax.py", line 321, in model.fit(train_vectors, val_train_labels, epochs=nb_epoch,steps_per_epoch=1,validation_data=[test_vectors, val_test_labels],validation_steps=1) File "/share/nishome/19930072_0/anaconda3/envs/py36/lib/python3.6/site-packages/keras/engine/training.py", line 1039, in fit validation_steps=validation_steps) File "/share/nishome/19930072_0/anaconda3/envs/py36/lib/python3.6/site-packages/keras/engine/training_arrays.py", line 154, in fit_loop outs = f(ins) File "/share/nishome/19930072_0/anaconda3/envs/py36/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2715, in __call return self._call(inputs) File "/share/nishome/19930072_0/anaconda3/envs/py36/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2675, in _call fetched = self._callable_fn(*array_vals) File "/share/nishome/19930072_0/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1439, in call run_metadata_ptr) File "/share/nishome/19930072_0/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in exit c_api.TF_GetCode(self.status.status)) tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[2742,512,38,45] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [[{{node module_apply_default/bilm/CNN/Conv2D_5}} = Conv2D[T=DT_FLOAT, data_format="NCHW", dilations=[1, 1, 1, 1], padding="VALID", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](module_apply_default/bilm/CNN/Conv2D-0-TransposeNHWCToNCHW-LayoutOptimizer, module_apply_default/bilm/CNN/Conv2D_5/ReadVariableOp/_299)]] Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

 [[{{node bidirectional_2/transpose_4/_313}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1962_bidirectional_2/transpose_4", tensor_type=DT_BOOL, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

**Comment by amahendrakar** [comment]
@DavidInWuhanChina,
Looks like the issue is related to TensorFlow-Hub. Could you please open a new issue in the Tensorflow-Hub repository from [this](https://github.com/tensorflow/hub/issues/new) link. Thanks!

**Comment by amahendrakar** [comment]
Any updates regarding this issue? Thanks!

**Comment by DavidInWuhanChina** [comment]
I have solve this problem，thanks！
