### ISSUE TITLE
Serialization fails for nested models (models containing another model)

### ISSUE THREAD

**Issue by ArnoSchaepe** [tensorflow/tensorflow#37184]
Looks like a duplicate of #37158

**System information** 
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):  Custom code, Auto-encoder sample, based on a tutorial:
https://www.pyimagesearch.com/2020/02/17/autoencoders-with-keras-tensorflow-and-deep-learning/

- OS Platform and Distribution 
Windows 10
- TensorFlow installed from (source orbinary): 
pip install tensorflow-gpu
- TensorFlow version (use command below): 
v2.1.0-rc2-17-ge5bf8de410 2.1.0
- Python version:
3.7.6
 - Bazel version (if compiling from source):
not used
- GCC/Compiler version (if compiling from source): 
not used
- CUDA/cuDNN version: - GPU model and memory:
CUDA Version 10.1.243
cudnn-10.1-windows10-x64-v7.6.5.32

**Describe the current behavior**
saving autoencoder throws
`WARNING:tensorflow:AutoGraph could not transform <function canonicalize_signatures.<locals>.signature_wrapper at 0x000002065515D678> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, export AUTOGRAPH_VERBOSITY=10) and attach the full output.
Cause: WARNING: AutoGraph could not transform <function canonicalize_signatures.<locals>.signature_wrapper at 0x000002065515D678> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, export AUTOGRAPH_VERBOSITY=10) and attach the full output.
Cause: INFO:tensorflow:Assets written to: test\assets`

loading the saved model fails with the message
`keras.models.load_model('run/autoencoder/')
Traceback (most recent call last):
  File "<ipython-input-39-0e89c2f914ad>", line 1, in <module>
    keras.models.load_model('run/autoencoder/')
  File "c:\python37\lib\site-packages\tensorflow_core\python\keras\saving\save.py", line 150, in load_model
    return saved_model_load.load(filepath, compile)
  File "c:\python37\lib\site-packages\tensorflow_core\python\keras\saving\saved_model\load.py", line 89, in load
    model = tf_load.load_internal(path, loader_cls=KerasObjectLoader)
  File "c:\python37\lib\site-packages\tensorflow_core\python\saved_model\load.py", line 552, in load_internal
    export_dir)
  File "c:\python37\lib\site-packages\tensorflow_core\python\keras\saving\saved_model\load.py", line 119, in __init__
    self._finalize()
  File "c:\python37\lib\site-packages\tensorflow_core\python\keras\saving\saved_model\load.py", line 157, in _finalize
    created_layers={layer.name: layer for layer in node.layers})
  File "c:\python37\lib\site-packages\tensorflow_core\python\keras\engine\network.py", line 1903, in reconstruct_from_config
    process_node(layer, node_data)
  File "c:\python37\lib\site-packages\tensorflow_core\python\keras\engine\network.py", line 1851, in process_node
    output_tensors = layer(input_tensors, **kwargs)
  File "c:\python37\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py", line 773, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "c:\python37\lib\site-packages\tensorflow_core\python\keras\engine\network.py", line 712, in call
    raise NotImplementedError('When subclassing the Model class, you should'
NotImplementedError: When subclassing the Model class, you should implement a call method.`

saving and loading of encode/decoder models works, but for autoencoder it fails, therefor I suspect that this is related to nested models

**Describe the expected behavior**
save / load cycle works without error message

**Standalone code to reproduce the issue** 

[train_auto_encoder_mnist.py.txt](https://github.com/tensorflow/tensorflow/files/4270255/train_auto_encoder_mnist.py.txt)

Code is based on a tutorial form
https://www.pyimagesearch.com/2020/02/17/autoencoders-with-keras-tensorflow-and-deep-learning/

**Comment by amahendrakar** [comment]
@ArnoSchaepe,
I was able to run the code from the given link without any issues. Please find the gist of it [here](https://colab.sandbox.google.com/gist/amahendrakar/016664986b3a85397336150d03e37d19/37184-from-tutorial.ipynb). Thanks!

**Comment by ArnoSchaepe** [comment]
Sorry the code I uploaded does not reproduce the issue correctly. As it really seems to be a duplicate of 37158 I would propose to close this issue.
