### ISSUE TITLE
"Cannot take the length of shape with unknown rank" error

### ISSUE THREAD

**Issue by MikhailMashukov** [tensorflow/tensorflow#37193]
**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): Ubuntu 18.04.3
- TensorFlow installed from (source or
binary): pip
- TensorFlow version (use command below): tensorflow-addons==0.8.2
tensorflow-estimator==2.1.0
tensorflow-gpu==2.1.0
tensorflow-probability==0.9.0
- Python version: 3.6.9
- CUDA/cuDNN version:  10.1.243 / 7.6.5
- GPU model and memory: Tesla V100-SXM2 32 GB

**Describe the current behavior**
I’m trying to switch from keras to tensorflow.keras (actually only to add TensorBoard callback to model.fit_generator and to be able to profile performance). 
Now I am getting 
```
ValueError                                Traceback (most recent call last)
<ipython-input-6-70f0d0a1e94e> in <module>
…
~/Visual_Z2/ImageNet.py in _doLearning(self, epochCount, learningCallback, otherParams, initialEpochNum)
 #                             self.model.fit_generator
    430                                  validation_steps=testImageCount // self.batchSize,
    431                                  workers=2,
--> 432                                  verbose=2, callbacks=[tensorBoardCallback])
    433             #, summaryCallback])
    434             # Without make_one_shot_iterator - error fused convolution not supported

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/util/deprecation.py in new_func(*args, **kwargs)
    322               'in a future version' if date is None else ('after %s' % date),
    323               instructions)
--> 324       return func(*args, **kwargs)
    325     return tf_decorator.make_decorator(
    326         func, new_func, 'deprecated',
…
ValueError: in converted code:

    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/training_v2.py:677 map_fn
        batch_size=None)
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/training.py:2469 _standardize_tensors
        exception_prefix='target')
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/training_utils.py:529 standardize_input_data
…
ValueError: Cannot take the length of shape with unknown rank.

```
**Describe the expected behavior**
Everything worked on keras with tensorflow as backend.

**Other info / logs**
I read this can happen because of PyFunction, I really have it, but adding reshape/image.set_shape don't fix the error.
I build input dataset like this

```
def _loadTestImage(imageNum, label):
    imageData = self.imageDataset.getImage(imageNum, 'net', 'test')       # Returns numpy array (227, 227, 3) of floats
    return (imageData, keras.utils.to_categorical(label, num_classes=classCount))

def _tfLoadTestImage(imageNum, label):
    image, label = tf.py_function(_loadTestImage, [imageNum, label], [tf.float32, tf.int32]) 
    # Adding image.set_shape(crop_size + (3, ))
    # or tf.reshape(image, shape=crop_size + (3, ))
    # here doesn’t help
    return image, label

numDs = tf.data.Dataset.from_tensor_slices(imageNums)       # Shuffled indices of images [15, 22, 3, …] 
label_ds = tf.data.Dataset.from_tensor_slices(self.imageNumLabels)
ds = tf.data.Dataset.zip((numDs, label_ds))
ds = ds.repeat()
tfTestDataset = ds.shuffle(buffer_size=max(epochImageCount, 2000))
tfTestDataset = tfTestDataset.map(_tfLoadTestImage, num_parallel_calls=4)
tfTestDataset = tfTestDataset.batch(self.batchSize)
```

The problem looks identical to https://github.com/tensorflow/tensorflow/issues/24520#issuecomment-589119295 so I tried nightly build today (2.2.0-dev20200229) and still getting error, only 

```
ValueError: in user code:

    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py:499 train_function  *
        outputs = self.distribute_strategy.experimental_run_v2(
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/distribute_lib.py:856 experimental_run_v2  **
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/distribute_lib.py:2112 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/distribute_lib.py:2470 _call_for_each_replica
        return fn(*args, **kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py:471 train_step  **
        self.compiled_metrics.update_state(y, y_pred, sample_weight)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/compile_utils.py:348 update_state
        self._build(y_pred, y_true)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/compile_utils.py:267 _build
        self._metrics, y_true, y_pred)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/util/nest.py:1118 map_structure_up_to
        **kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/util/nest.py:1214 map_structure_with_tuple_paths_up_to
        *flat_value_lists)]
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/util/nest.py:1213 <listcomp>
        results = [func(*args, **kwargs) for args in zip(flat_path_list,
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/util/nest.py:1116 <lambda>
        lambda _, *values: func(*values),  # Discards the path arg.
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/compile_utils.py:377 _get_metric_objects
        return [self._get_metric_object(m, y_t, y_p) for m in metrics]
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/compile_utils.py:377 <listcomp>
        return [self._get_metric_object(m, y_t, y_p) for m in metrics]
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/compile_utils.py:398 _get_metric_object
        y_t_rank = len(y_t.shape.as_list())
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/tensor_shape.py:1173 as_list
        raise ValueError("as_list() is not defined on an unknown TensorShape.")

    ValueError: as_list() is not defined on an unknown TensorShape.
```

**Comment by gadagashwini** [comment]
@MikhailMashukov, Thanks for reporting this issue.
Please provide the complete standalone code to reproduce the reported issue.
Thanks

**Comment by gadagashwini** [comment]
@MikhailMashukov, Can you update the issue with standalone code. Thanks

**Comment by MikhailMashukov** [comment]
Oh, I'm afraid I don't know how to do this in reasonable amount of time. Needs endless iterations of cutting code and retesting whether it still reproduces.

Maybe some additional logging instead?

**Comment by gadagashwini** [comment]
It would be helpful if we get the sample standalone code to analyze this issue. Thanks!

**Comment by gadagashwini** [comment]
@MikhailMashukov, `Any update

**Comment by MikhailMashukov** [comment]
No, I will write here if I have what to write

**Comment by gadagashwini** [comment]
@MikhailMashukov, Please update the code snippet.

**Comment by Saduf2019** [comment]
@MikhailMashukov, 
please update  on the above comment

**Comment by ismael-elatifi** [comment]
I still have this issue with TF2.1 and you can find my workaround [here](https://github.com/tensorflow/tensorflow/issues/31373#issuecomment-573663963)

**Comment by MikhailMashukov** [comment]
> I still have this issue with TF2.1 and you can find my workaround [here](https://github.com/tensorflow/tensorflow/issues/31373#issuecomment-573663963)

Thank you Ismael! 
And I have already forgot what I tried to do and have moved to PyTorch... Hope it will help to other people.

**Comment by Saduf2019** [comment]
@MikhailMashukov
please confirm if we may move this to closed status.

**Comment by luvwinnie** [comment]
an normal LSTM with None shape still cannot train? is this will be fix?

```
if (x.shape is not None and len(x.shape) == 1 and
    /usr/local/var/pyenv/versions/3.7.6/lib/python3.7/site-packages/tensorflow_core/python/framework/tensor_shape.py:822 __len__
        raise ValueError("Cannot take the length of shape with unknown rank.")
    ValueError: Cannot take the length of shape with unknown rank.
```

**Comment by 336655asd** [comment]
You can solve this issue by adding "set_shape()" under map_fn like this:
```
def map_fn(x, label):
    x = tf.py_function(your_fn, inp=[x], Tout=(tf.float32))
    x.set_shape([shape])
    return x, label
dataset = dataset.map(map_fn).batch(batch_size)
```
The better performerance is setting map after batch, so you can do this:
```
def map_fn(x, label):
    x = tf.py_function(your_fn, inp=[x], Tout=(tf.float32))
    x.set_shape([batch_size, shape])
    return x, label
dataset = dataset.batch(batch_size).map(map_fn)
```

**Comment by MegaCreater** [comment]
Issue Type -> Bug
Have you reproduced the bug with TF nightly? -> No
Tensorflow Version -> v2.11.0-rc2-17-gd5b57ca93e5,  2.11.0
Custom Code -> Yes
OS Platform and Distribution -> Google colab 

#### Standalone code to reproduce the issue
```python3
import numpy as np,tensorflow as tf 
@tf.function
def sample(inputs:tf.Tensor):                                                   # some sample function 

  def numpy_method(inputs:np.ndarray):
    # some complex method 
    return np.sqrt(inputs)# example code 

  inputs=tf.numpy_function(numpy_method,[inputs],inputs.dtype,name='outputs')   # make apply numpy method 
  inputs=tf.keras.layers.AvgPool2D()(inputs)                                    # ERROR !!!!!

  return inputs

sample(tf.random.uniform((1,32,32,3)))
```

#### Relevant log output

```shell

.....

ValueError: in user code:

    File "<ipython-input-189-8001acaa2b43>", line 10, in sample  *
        inputs=tf.keras.layers.AvgPool2D()(inputs)                                    # ERROR !!!!!
    File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 70, in error_handler  **
        raise e.with_traceback(filtered_tb) from None

    ValueError: Exception encountered when calling layer 'average_pooling2d' (type AveragePooling2D).
    
    Cannot take the length of shape with unknown rank.
    
    Call arguments received by layer 'average_pooling2d' (type AveragePooling2D):
      • inputs=tf.Tensor(shape=<unknown>, dtype=float32)
```

#### But works fine if we reverse the order (i.e. tf.numpy_function cannot properly cast back outputs to tensors)
```python3
import numpy as np,tensorflow as tf 
@tf.function
def sample(inputs:tf.Tensor):                                                   # some sample function 

  def numpy_method(inputs:np.ndarray):
    # some complex method 
    return np.sqrt(inputs)# example code 

  inputs=tf.keras.layers.AvgPool2D()(inputs)                                    # works fine 
  inputs=tf.numpy_function(numpy_method,[inputs],inputs.dtype,name='outputs')   # make apply numpy method 

  return inputs

sample(tf.random.uniform((1,32,32,3)))
```
#### Output 
```shell
<tf.Tensor: shape=(1, 16, 16, 3), dtype=float32, numpy=
array([[[[0.7783269 , 0.6260437 , 0.81261575] ......
```
#### Temporary solution (as told by @336655asd )
```python3 
import numpy as np,tensorflow as tf 
@tf.function
def sample(inputs:tf.Tensor):                                                   # some sample function 

  def numpy_method(inputs:np.ndarray):
    # some complex method 
    return np.sqrt(inputs)# example code 

  inputs_shape=inputs.shape                                                     # store shape
  inputs=tf.numpy_function(numpy_method,[inputs],inputs.dtype,name='outputs')   # make apply numpy method 
  inputs.set_shape(inputs_shape)                                              # restore shape 
  inputs=tf.keras.layers.AvgPool2D()(inputs)                              # work fine !!!!!!!!!!!!!!!!!!!

  return inputs

sample(tf.random.uniform((1,32,32,3))) 
```

#### Output (with temporary solution) 
```shell
<tf.Tensor: shape=(1, 16, 16, 3), dtype=float32, numpy=
array([[[[0.62680405, 0.5303471 , 0.6314228 ], .....
```
