### ISSUE TITLE
Cannot import tensorflow 1.15

### ISSUE THREAD

**Issue by WallbangJocrod** [tensorflow/tensorflow#37203]
**System information**
- OS Platform and Distribution (Windows 10 pro):
-Lenovo ideapad 520-15iKB
- TensorFlow installed from ("pip install tensorflow==1.15"):
- TensorFlow version: 1.15 (cpu-only)
- Python version: 3.6.0
- Installed using pip
- GPU model and memory: GeForce 940MX 4GB

**Describe the problem**

i installed tensoflow == 1.15 and i can't import

`Python 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
2020-03-01 03:36:32.916332: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_100.dll'; dlerror: cudart64_100.dll not found
2020-03-01 03:36:32.921892: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Jose\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\__init__.py", line 99, in <module>
    from tensorflow_core import *
  File "C:\Users\Jose\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_core\__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\Jose\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\Users\Jose\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "C:\Users\Jose\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\Jose\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_core\python\__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "C:\Users\Jose\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_core\core\framework\graph_pb2.py", line 7, in <module>
    from google.protobuf import descriptor as _descriptor
  File "C:\Users\Jose\AppData\Local\Programs\Python\Python36\lib\site-packages\google\protobuf\descriptor.py", line 47, in <module>
    from google.protobuf.pyext import _message
ImportError: DLL load failed: No se encontró el proceso especificado.`

i don't know what is going on, please help me.

**Comment by ravikyram** [comment]
@WallbangJocrod 

Please, check Your CPU/Python is on 32 bits?Please, refer #36167 and see if it helps you. Just to verify did you follow the instructions to install from pip using [Tensorflow website](https://www.tensorflow.org/install/pip).Thanks

**Comment by mihaimaruseac** [comment]
Closing as duplicate.

https://github.com/tensorflow/tensorflow/issues/36167#issuecomment-577886156

#36167 #36151 #36138 #36054 #36045 #36020 #36003 #35988 #35903 #35880 #35865 #35805 #35789 #35773 #35772 #35767 #35766 #35749 #35721 #35618 #35204
