### ISSUE TITLE
TFLite model not running in spite of using SELECT_TF_OPS for Mean operation

### ISSUE THREAD

**Issue by kafan1986** [tensorflow/tensorflow#37242]
**System information**
- Android 9/TOCO ran on MAC OS (Tensorflow 2.1.0)

-  implementation 'org.tensorflow:tensorflow-lite:0.0.0-nightly'
    implementation 'org.tensorflow:tensorflow-lite-gpu:0.0.0-nightly'
    implementation 'org.tensorflow:tensorflow-lite-support:0.0.0-nightly'
    implementation 'org.tensorflow:tensorflow-lite-select-tf-ops:0.0.0-nightly'

Toco command (with allow custom ops and to use select tf ops), converted with **tensorflow 2.1.0**:

`toco --input_file=/Users/debasish/Downloads/tfdir/agegendermultitaskspcnn.pb --output_file=/Users/debasish/Downloads/tfdir/agegendermultitaskspcnn.tflite --input_format=TENSORFLOW_GRAPHDEF --output_format=TFLITE --input_arrays=input --output_arrays=ageprob,genderprob --input_shapes=1,227,227,3 --mean_values=117 --std_values=1 --allow_custom_ops --target_ops=TFLITE_BUILTINS,SELECT_TF_OPS`

The model builds OK with this command. But while running on Android at the below statement, I get following error while creating a interpreter.

`        tflite = new Interpreter(tfliteModel, tfliteOptions);`

Error Message:

```
java.lang.IllegalStateException: Internal error: Unexpected failure when preparing tensor allocations: Encountered unresolved custom op: Mean.
    Node number 4 (Mean) failed to prepare
```

Graph
![agegendermultitaskspcnn](https://user-images.githubusercontent.com/7953422/75726912-9db20580-5d09-11ea-94e0-c043e5e7673f.png)

**Comment by kafan1986** [comment]
@ymodak  Any help?

**Comment by kafan1986** [comment]
@haozha111 Any help?

**Comment by haozha111** [comment]
Can you try using the tf-nightly  (it will use the new TF Lite converter).

**Comment by kafan1986** [comment]
@haozha111 I installed latest tf-nightly and tried converting my model. It is giving me error.

**TOCO Command**
`toco --saved_model_dir=/Users/debasish/Downloads/tfdir/ --graph_def_file=/Users/debasish/Downloads/tfdir/agegendermultitaskdpcnn_2_1.pb --output_format=TFLITE --inference_type=FLOAT --inference_input_type=FLOAT --output_file=/Users/debasish/Downloads/tfdir/agegendermultitaskdpcnn_2_1.tflite --output_format=TFLITE --input_arrays=input --output_arrays=ageprob,genderprob --input_shapes=1,227,227,3 --mean_values=117 --std_dev_values=1 --allow_custom_ops --target_ops=TFLITE_BUILTINS,SELECT_TF_OPS --experimental_new_converter`

**Error**
```
INFO:tensorflow:Saver not created because there are no variables in the graph to restore
I0307 01:01:41.570394 4577048000 saver.py:1512] Saver not created because there are no variables in the graph to restore
2020-03-07 01:01:41.596349: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fe0ce6f6e30 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-03-07 01:01:41.596378: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Traceback (most recent call last):
  File "/usr/local/bin/toco", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/tensorflow/lite/python/tflite_convert.py", line 638, in main
    app.run(main=run_main, argv=sys.argv[:1])
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/Users/debasish/Library/Python/3.7/lib/python/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/Users/debasish/Library/Python/3.7/lib/python/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/usr/local/lib/python3.7/site-packages/tensorflow/lite/python/tflite_convert.py", line 621, in run_main
    _convert_tf2_model(tflite_flags)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/lite/python/tflite_convert.py", line 237, in _convert_tf2_model
    tflite_model = converter.convert()
  File "/usr/local/lib/python3.7/site-packages/tensorflow/lite/python/lite.py", line 483, in convert
    raise ValueError("This converter can only convert a single "
ValueError: This converter can only convert a single ConcreteFunction. Converting multiple functions is under development.
```

**Comment by sahil1dotgupta** [comment]
@kafan1986 Can you share how you solved the issue?
