### ISSUE TITLE
Tensorflow import issue after new install ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by sandeepmcr** [tensorflow/tensorflow#37265]
Python 3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 00:42:30) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tF
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Python37\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Python37\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python37\lib\site-packages\tensorflow\__init__.py", line 101, in <module>
    from tensorflow_core import *
  File "C:\Python37\lib\site-packages\tensorflow_core\__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Python37\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\Python37\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "C:\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Python37\lib\site-packages\tensorflow_core\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Python37\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Python37\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by ravikyram** [comment]
@sandeepmcr 

What is make/model of your cpu?
I suspect your cpu model does not support AVX instructions sets.See [hardware requirements](https://www.tensorflow.org/install/pip?lang=python3#hardware-requirements)
Make sure to download the [latest microsoft visual c++ redistributable from here.](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads)
.Also, please follow the instructions from to install from [Tensorflow website](https://www.tensorflow.org/install).

Please, check Your CPU/Python is on 32 bits?Please, refer #36167 and see if it helps you. 

Please, fill the issue template  [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).So we will know details about what platform you are using (operating system, architecture),TensorFlow version, which  in turn helps us in finding root cause of the issue.Thanks!

**Comment by sandeepmcr** [comment]
> @sandeepmcr
> 
> What is make/model of your cpu?
> I suspect your cpu model does not support AVX instructions sets.See [hardware requirements](https://www.tensorflow.org/install/pip?lang=python3#hardware-requirements)
> Make sure to download the [latest microsoft visual c++ redistributable from here.](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads)
> .Also, please follow the instructions from to install from [Tensorflow website](https://www.tensorflow.org/install).
> 
> Please, check Your CPU/Python is on 32 bits?Please, refer #36167 and see if it helps you.
> 
> Please, fill the issue template [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).So we will know details about what platform you are using (operating system, architecture),TensorFlow version, which in turn helps us in finding root cause of the issue.Thanks!

Apologize for late resonse ravi:

I have Thinkpad mobile workstation with Intel Core i7 2.8 Ghz, 64-bit,  64GB RAM , Windows 10
NIVDIA Quadro M620 
i installed Python 64bit both 3.7 and 3.8.

**Comment by sandeepmcr** [comment]
I updated VC++ distributable as per link provided by you.  Now when import tensorflow i get this specific error. Should ignore it because at least tensorflow seems to load.

2020-03-08 10:40:29.002371: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-03-08 10:40:29.006704: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.

**Comment by mihaimaruseac** [comment]
@sandeepmcr that is just a warning that cuda couldn't be loaded on your system. As the second line says, you can ignore that if you don't need GPU.

If you do, then you have to make sura CUDA 10.1 libs are available.

**Comment by sandeepmcr** [comment]
> @sandeepmcr that is just a warning that cuda couldn't be loaded on your system. As the second line says, you can ignore that if you don't need GPU.
> 
> If you do, then you have to make sura CUDA 10.1 libs are available.

This has got resolved now after I installed CUDA 10.2 toolkit . Tensorflow is getting imported without error .
