### ISSUE TITLE
CombinedNonMaxSuppression is not whitelisted operator

### ISSUE THREAD

**Issue by timzatko** [tensorflow/tensorflow#37301]
Hi! CombinedNonMaxSuppression is not whitelisted operator. Is it possible to add it as a whitelisted operator?

**System information**
- Linux Ubuntu 16.04
- TensorFlow installed from Docker Image
- TensorFlow version 2.1.0

**Provide the text output from tflite_convert**

```
2020-03-04 15:50:57.748145: I tensorflow/core/grappler/devices.cc:55] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2020-03-04 15:50:57.748972: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2020-03-04 15:50:57.771173: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:814] Optimization results for grappler item: graph_to_optimize
2020-03-04 15:50:57.771259: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   function_optimizer: function_optimizer did nothing. time = 0.018ms.
2020-03-04 15:50:57.771283: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   function_optimizer: function_optimizer did nothing. time = 0.011ms.
2020-03-04 15:50:59.782146: I tensorflow/core/grappler/devices.cc:55] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2020-03-04 15:50:59.782403: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2020-03-04 15:51:00.470079: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:814] Optimization results for grappler item: graph_to_optimize
2020-03-04 15:51:00.470148: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   constant_folding: Graph size after: 360 nodes (-59), 639 edges (-59), time = 377.824ms.
2020-03-04 15:51:00.470167: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   constant_folding: Graph size after: 360 nodes (0), 639 edges (0), time = 39.896ms.
Traceback (most recent call last):
  File "./to_tf_lite.py", line 54, in <module>
    app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "./to_tf_lite.py", line 44, in main
    tflite_model = converter.convert()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/lite/python/lite.py", line 464, in convert
    **converter_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/lite/python/convert.py", line 457, in toco_convert_impl
    enable_mlir_converter=enable_mlir_converter)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/lite/python/convert.py", line 203, in toco_convert_protos
    raise ConverterError("See console for info.\n%s\n%s\n" % (stdout, stderr))
tensorflow.lite.python.convert.ConverterError: See console for info.
2020-03-04 15:51:02.143649: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer.so.6
2020-03-04 15:51:02.146593: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer_plugin.so.6
2020-03-04 15:51:03.291126: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Size
2020-03-04 15:51:03.291210: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Size
2020-03-04 15:51:03.291322: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Size
2020-03-04 15:51:03.291357: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Size
2020-03-04 15:51:03.291468: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: CombinedNonMaxSuppression
2020-03-04 15:51:03.297057: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 223 operators, 426 arrays (0 quantized)
2020-03-04 15:51:03.299828: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 223 operators, 426 arrays (0 quantized)
2020-03-04 15:51:03.400832: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 1: 105 operators, 198 arrays (0 quantized)
2020-03-04 15:51:03.402525: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 2: 105 operators, 198 arrays (0 quantized)
2020-03-04 15:51:03.404185: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Group bidirectional sequence lstm/rnn: 105 operators, 198 arrays (0 quantized)
2020-03-04 15:51:03.405338: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before dequantization graph transformations: 105 operators, 198 arrays (0 quantized)
2020-03-04 15:51:03.406273: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Identify nearest upsample.: 105 operators, 198 arrays (0 quantized)
2020-03-04 15:51:03.407942: I tensorflow/lite/toco/allocate_transient_arrays.cc:345] Total transient array allocated size: 22151168 bytes, theoretical optimal value: 22151168 bytes.
2020-03-04 15:51:03.408239: I tensorflow/lite/toco/toco_tooling.cc:471] Number of parameters: 8849370
2020-03-04 15:51:03.408888: W tensorflow/lite/toco/tflite/operator.cc:2024] Op CombinedNonMaxSuppression is a valid TensorFlow op but has not been whitelisted for the TensorFlow Lite flex op set.
2020-03-04 15:51:03.409165: W tensorflow/lite/toco/tflite/operator.cc:2024] Op CombinedNonMaxSuppression is a valid TensorFlow op but has not been whitelisted for the TensorFlow Lite flex op set.
2020-03-04 15:51:03.409257: E tensorflow/lite/toco/toco_tooling.cc:498] We are continually in the process of adding support to TensorFlow Lite for more ops. It would be helpful if you could inform us of how this conversion went by opening a github issue at https://github.com/tensorflow/tensorflow/issues/new?template=40-tflite-op-request.md
 and pasting the following:

Some of the operators in the model are not supported by the standard TensorFlow Lite runtime and are not recognized by TensorFlow. If you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, CAST, CONCATENATION, CONV_2D, DIV, EXP, EXPAND_DIMS, FILL, LEAKY_RELU, LOGISTIC, MAX_POOL_2D, MUL, PACK, RESHAPE, RESIZE_NEAREST_NEIGHBOR, SHAPE, SPLIT_V, STRIDED_SLICE, SUB. Here is a list of operators for which you will need custom implementations: CombinedNonMaxSuppression.
Traceback (most recent call last):
  File "/usr/local/bin/toco_from_protos", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 93, in main
    app.run(main=execute, argv=[sys.argv[0]] + unparsed)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 56, in execute
    enable_mlir_converter)
Exception: We are continually in the process of adding support to TensorFlow Lite for more ops. It would be helpful if you could inform us of how this conversion went by opening a github issue at https://github.com/tensorflow/tensorflow/issues/new?template=40-tflite-op-request.md
 and pasting the following:

Some of the operators in the model are not supported by the standard TensorFlow Lite runtime and are not recognized by TensorFlow. If you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, CAST, CONCATENATION, CONV_2D, DIV, EXP, EXPAND_DIMS, FILL, LEAKY_RELU, LOGISTIC, MAX_POOL_2D, MUL, PACK, RESHAPE, RESIZE_NEAREST_NEIGHBOR, SHAPE, SPLIT_V, STRIDED_SLICE, SUB. Here is a list of operators for which you will need custom implementations: CombinedNonMaxSuppression.
```

**Standalone code to reproduce the issue** 

--

**Any other info / logs**

--

**Comment by Saduf2019** [comment]
@timzatko 
Could you please share simple standalone code that you executed before facing this issue.

**Comment by timzatko** [comment]
I did not try to add converter.allow_custom_ops, if I add it, I have to implement that operator in c, right? Since it is tensorflow operator, I would like to avoid that.

Steps to reproduce:
1. Clone this repository:
https://github.com/zzh8829/yolov3-tf2
2. Download model and copy it to `checkpoints` path https://drive.google.com/open?id=1gl4JY4sbyjFXOFiz9MZsd84PL4vuhy3Q
3. Create this script in the root of the repository and run it

```
import tensorflow as tf

from absl import app, flags, logging
from absl.flags import FLAGS

from yolov3_tf2.models import YoloV3, YoloV3Tiny

flags.DEFINE_string('weights', './checkpoints/yolov3-tiny.tf', 'path to weights file')
flags.DEFINE_boolean('tiny', True, 'yolov3 or yolov3-tiny')
flags.DEFINE_integer('num_classes', 80, 'number of classes in the model')
flags.DEFINE_integer('input_size', 416, 'image size')


# https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/delegates/flex/whitelisted_flex_ops.cc
# https://www.tensorflow.org/api_docs/python/tf/image/non_max_suppression
# https://www.tensorflow.org/s/results/?q=combined_non_max_suppression

def main(_argv):
    if FLAGS.tiny:
        yolo = YoloV3Tiny(FLAGS.input_size, classes=FLAGS.num_classes)
    else:
        yolo = YoloV3(FLAGS.input_size, classes=FLAGS.num_classes)

    yolo.load_weights(FLAGS.weights).expect_partial()
    logging.info('weights loaded')

    path = 'tmp/yolov3.h5'
    out_path = 'tmp/yolov3.tflite'

    if FLAGS.tiny:
        path = 'tmp/yolov3-tiny.h5'
        out_path = 'tmp/yolov3-tiny.tflite'

    yolo.save(path)

    logging.info(f'keras model saved to location {path}')

    converter = tf.lite.TFLiteConverter.from_keras_model(yolo)
    converter.target_spec.supported_ops = [
        tf.lite.OpsSet.TFLITE_BUILTINS,
        tf.lite.OpsSet.SELECT_TF_OPS
    ]
    # converter.experimental_new_converter = True
    # converter.experimental_new_quantizer = True
    # converter.allow_custom_ops = True

    tflite_model = converter.convert()
    logging.info(f'model converted')

    open(out_path, 'wb').write(tflite_model)

    logging.info(f'tflite model saved to location {out_path}')


if __name__ == '__main__':
    try:
        app.run(main)
    except SystemExit:
        pass
```

I tried setting `converter.experimental_new_converter = True` and here is the result.

```
2020-03-05 07:00:50.823406: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer.so.6
2020-03-05 07:00:50.834836: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer_plugin.so.6
2020-03-05 07:00:51.577175: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-03-05 07:00:51.577237: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: UNKNOWN ERROR (-1)
2020-03-05 07:00:51.577259: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (c807e06a611a): /proc/driver/nvidia/version does not exist
2020-03-05 07:00:51.578259: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-03-05 07:00:51.589959: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3096000000 Hz
2020-03-05 07:00:51.591151: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x58cdd60 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-03-05 07:00:51.591490: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
I0305 07:00:52.946302 139749900048192 to_tf_lite.py:25] weights loaded
I0305 07:00:53.313143 139749900048192 to_tf_lite.py:36] keras model saved to location tmp/yolov3-tiny.h5
2020-03-05 07:00:53.590270: I tensorflow/core/grappler/devices.cc:55] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2020-03-05 07:00:53.590894: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2020-03-05 07:00:53.602172: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:814] Optimization results for grappler item: graph_to_optimize
2020-03-05 07:00:53.602322: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   function_optimizer: function_optimizer did nothing. time = 0.005ms.
2020-03-05 07:00:53.602341: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   function_optimizer: function_optimizer did nothing. time = 0.001ms.
2020-03-05 07:00:54.439903: I tensorflow/core/grappler/devices.cc:55] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2020-03-05 07:00:54.440240: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2020-03-05 07:00:54.700659: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:814] Optimization results for grappler item: graph_to_optimize
2020-03-05 07:00:54.700721: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   constant_folding: Graph size after: 360 nodes (-59), 639 edges (-59), time = 132.996ms.
2020-03-05 07:00:54.700740: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   constant_folding: Graph size after: 360 nodes (0), 639 edges (0), time = 36.936ms.
Traceback (most recent call last):
  File "to_tf_lite.py", line 56, in <module>
    app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "to_tf_lite.py", line 46, in main
    tflite_model = converter.convert()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/lite/python/lite.py", line 464, in convert
    **converter_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/lite/python/convert.py", line 457, in toco_convert_impl
    enable_mlir_converter=enable_mlir_converter)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/lite/python/convert.py", line 203, in toco_convert_protos
    raise ConverterError("See console for info.\n%s\n%s\n" % (stdout, stderr))
tensorflow.lite.python.convert.ConverterError: See console for info.
2020-03-05 07:00:55.882389: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer.so.6
2020-03-05 07:00:55.883827: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer_plugin.so.6
2020-03-05 07:00:56.553882: W tensorflow/compiler/mlir/lite/python/graphdef_to_tfl_flatbuffer.cc:89] Ignored output_format.
2020-03-05 07:00:56.553939: W tensorflow/compiler/mlir/lite/python/graphdef_to_tfl_flatbuffer.cc:95] Ignored drop_control_dependency.
2020-03-05 07:00:56.863763: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-03-05 07:00:56.868908: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3096000000 Hz
2020-03-05 07:00:56.869444: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x605b620 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-03-05 07:00:56.869491: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-03-05 07:00:56.870769: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-03-05 07:00:56.870813: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: UNKNOWN ERROR (-1)
2020-03-05 07:00:56.870833: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (c807e06a611a): /proc/driver/nvidia/version does not exist
loc(callsite("yolov3_tiny/yolo_nms/combined_non_max_suppression/CombinedNonMaxSuppression"("/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/gen_image_ops.py":378:0) at callsite("/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/image_ops_impl.py":3958:0 at callsite("/home/src/yolov3_tf2/models.py":198:0 at callsite("/home/src/yolov3_tf2/models.py":254:0 at callsite("/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/layers/core.py":846:0 at callsite("/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/base_layer.py":778:0 at callsite("/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/network.py":891:0 at callsite("/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/network.py":717:0 at callsite("/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/base_layer.py":778:0 at "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/saving/saving_utils.py":150:0)))))))))): error: 'tf.CombinedNonMaxSuppression' op is neither a custom op nor a flex op
error: failed while converting: 'main'
Ops that need custom implementation (enabled via setting the -emit-custom-ops flag): CombinedNonMaxSuppression
Traceback (most recent call last):
  File "/usr/local/bin/toco_from_protos", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 93, in main
    app.run(main=execute, argv=[sys.argv[0]] + unparsed)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 56, in execute
    enable_mlir_converter)
Exception: /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/gen_image_ops.py:378:38: error: 'tf.CombinedNonMaxSuppression' op is neither a custom op nor a flex op
                                     clip_boxes=clip_boxes, name=name)
                                     ^
/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/image_ops_impl.py:3958:9: note: called from
        score_threshold, pad_per_class, clip_boxes)
        ^
/home/src/yolov3_tf2/models.py:198:9: note: called from
        score_threshold=FLAGS.yolo_score_threshold
        ^
/home/src/yolov3_tf2/models.py:254:5: note: called from
    outputs = Lambda(lambda x: yolo_nms(x, anchors, masks, classes),
    ^
/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/layers/core.py:846:7: note: called from
      result = self.function(inputs, **kwargs)
      ^
/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/base_layer.py:778:19: note: called from
                  outputs = call_fn(cast_inputs, *args, **kwargs)
                  ^
/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/network.py:891:11: note: called from
          output_tensors = layer(computed_tensors, **kwargs)
          ^
/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/network.py:717:9: note: called from
        convert_kwargs_to_constants=base_layer_utils.call_context().saving)
        ^
/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/base_layer.py:778:19: note: called from
                  outputs = call_fn(cast_inputs, *args, **kwargs)
                  ^
/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/saving/saving_utils.py:150:7: note: called from
      outputs_list = nest.flatten(model(inputs=inputs, training=False))
      ^
<unknown>:0: error: failed while converting: 'main'
Ops that need custom implementation (enabled via setting the -emit-custom-ops flag): CombinedNonMaxSuppression
```

**Comment by anspire** [comment]
I am also getting similar error [notebook link](https://github.com/anspire/Notebooks/blob/master/yolov3_tiny_keras.ipynb)
`RuntimeError: Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference.Node number 41 (FlexSize) failed to prepare.
`

log test file of converted model while running on android native c++
[android_native_log.txt](https://github.com/tensorflow/tensorflow/files/4292321/android_native_log.txt)

**Comment by Saduf2019** [comment]
@anspire 
We have tried to replicate the link shared by you,  find the gist for the[ errors faced](https://colab.sandbox.google.com/gist/Saduf2019/d548215265cbbae3042f1cde381dab05/37301.ipynb), please share all dependencies for us to resolve the issue.

if possible share a colab gist with us.

**Comment by amahendrakar** [comment]
@timzatko,
Could you please un-comment these three lines from your code and then try to convert the model.
```
# converter.experimental_new_converter = True
# converter.experimental_new_quantizer = True
# converter.allow_custom_ops = True
```

I was able to create the .tflite file after removing the comments. Please check the attached screenshot for the output.
![37301](https://user-images.githubusercontent.com/57165142/76396663-9e006f80-639f-11ea-8b45-ded650c65085.png)

[37301_complete_logs.txt](https://github.com/tensorflow/tensorflow/files/4316878/37301_complete_logs.txt)

**Comment by timzatko** [comment]
Hi! When I uncomment this line

`# converter.allow_custom_ops = True`

I'm able to convert the model.

However, I need to provide an implementation of that operator to the TensorFlow Lite.

> allow_custom_ops: Boolean indicating whether to allow custom operations. When false any unknown operation is an error. When true, custom ops are created for any op that is unknown. **The developer will need to provide these to the TensorFlow Lite runtime with a custom resolver**. (default False)

https://www.tensorflow.org/api_docs/python/tf/lite/TFLiteConverter

Since the `CombinedNonMaxSuppression` operator is a Tensorflow operator I believe it can be whitelisted in `lite/delegates/flex/whitelisted_flex_ops.cc` (https://www.tensorflow.org/lite/guide/ops_select) so will not need to provide that implementation of that operator.

I forked the repository and added it there by myself, I was able to convert the model then. https://github.com/timzatko/tensorflow (https://hub.docker.com/layers/timzatko/tensorflow/2.1.0-gpu-py3/images/sha256-f1838218fc5d333153a4594c0c76925aab334ee83e7de97700bc91b36b613d30?context=repo) However, I did not try to run inference on it yet since I need to build interpreter for my use-case - https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/experimental/examples/unity/TensorFlowLitePlugin.

**Comment by thran** [comment]
@timzatko any luck with converting the model?

**Comment by timzatko** [comment]
> @timzatko any luck with converting the model?

Hi, I was able to convert the model by whitelisting that operator. There's a docker image of TensorFlow with my fix above, you can use it to convert a model.

I also tried to do inference in my app (it's a Unity app based on this example https://github.com/asus4/tf-lite-unity-sample/tree/master/Assets/Samples/SSD), however, it does not work for some reason (I don't remember why). Maybe I did a conversion with the wrong settings. Then I decided to use another model and don't waste my time with this.

**Comment by thran** [comment]
@timzatko Thx, I'm heading similar direction. Can I ask which model are you using?

**Comment by timzatko** [comment]
> @timzatko Thx, I'm heading similar direction. Can I ask which model are you using?

**ssd_mobilenet_v1_coco** (http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v1_coco_2018_01_28.tar.gz)
from tensorflow model zoo https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md

Here is the tutorial how to train it on GCP https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_pets.md

**Comment by edurenye** [comment]
@timzatko seems like adding the operator to the whitelisted operators solves the issue, can you make a PR from your repo, please

**Comment by haozha111** [comment]
Hi, seems like we have a solution here. Can we close this issue?

**Comment by edurenye** [comment]
The PR was never done, this was never committed or at least there is no reference in this issue that this was fixed, so until the issue is fixed I don't think we can close it. And @timzatko fork seems to not exist anymore.

**Comment by haozha111** [comment]
Actually the `CombinedNonMaxSuppression` is already in the allowlist of the flex delegate for a while:
https://github.com/tensorflow/tensorflow/blob/b333031345c13c3d9b7a0f06d8a5871e76d89571/tensorflow/lite/delegates/flex/allowlisted_flex_ops.cc#L119

Since this is already added, I would recommend the user to try it with the most recent tf release, or we just close this issue since the main concern is addressed.

**Comment by timzatko** [comment]
Yeah, the issue has been addressed, I believe that it can be closed now :)
