### ISSUE TITLE
ValueError: Input 0 of layer dense_1 is incompatible with the layer: expected axis -1 of input shape to have value 2 but received input with shape [None, 5]

### ISSUE THREAD

**Issue by Rogersjk** [tensorflow/tensorflow#37338]
**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): 
- OS Platform and Distribution :  Windows 10
- TensorFlow installed from: pip, tf 2.1.0,  cpu
- Python version: - 3.7.4

**build a simple network**
```
import tensorflow as tf
from tensorflow.keras import layers
class Model():
    def __init__(self):
        self.build_model()

    def build_model(self):
        input1 = layers.Input(shape=5)

        net = tf.keras.models.Sequential([
            layers.Dense(2),
            layers.Dense(1),
        ])

        out1 = net(input1)
        """
        out1 = layers.Dense(2)(input1)
        out1 = layers.Dense(1)(out1)
        """

        self.model = tf.keras.Model(inputs=input1, outputs=out1)
```

**Test Code**
```
model = Model()
s1 = "exp\\model"
model.model.save(s1)
model2 = tf.keras.models.load_model(s1)
```

**Error Info**
```
Traceback (most recent call last):
  File "e:\workspace\work\Study\pytorch_demos\demo5.py", line 26, in <module>
    model2 = tf.keras.models.load_model(s1)
  File "C:\Users\Administrator\Anaconda3\Lib\site-packages\tensorflow_core\python\keras\saving\save.py", line 150, in load_model
    return saved_model_load.load(filepath, compile)
  File "C:\Users\Administrator\Anaconda3\Lib\site-packages\tensorflow_core\python\keras\saving\saved_model\load.py", line 89, in load
    model = tf_load.load_internal(path, loader_cls=KerasObjectLoader)
  File "C:\Users\Administrator\Anaconda3\Lib\site-packages\tensorflow_core\python\saved_model\load.py", line 552, in load_internal
    export_dir)
  File "C:\Users\Administrator\Anaconda3\Lib\site-packages\tensorflow_core\python\keras\saving\saved_model\load.py", line 119, in __init__
    self._finalize()
  File "C:\Users\Administrator\Anaconda3\Lib\site-packages\tensorflow_core\python\keras\saving\saved_model\load.py", line 151, in _finalize
    node.add(layer)
  File "C:\Users\Administrator\Anaconda3\Lib\site-packages\tensorflow_core\python\training\tracking\base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "C:\Users\Administrator\Anaconda3\Lib\site-packages\tensorflow_core\python\keras\engine\sequential.py", line 203, in add
    output_tensor = layer(self.outputs[0])
  File "C:\Users\Administrator\Anaconda3\Lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py", line 737, in __call__
    self.name)
  File "C:\Users\Administrator\Anaconda3\Lib\site-packages\tensorflow_core\python\keras\engine\input_spec.py", line 213, in assert_input_compatibility
    ' but received input with shape ' + str(shape))
ValueError: Input 0 of layer dense_1 is incompatible with the layer: expected axis -1 of input shape to have value 2 but received input with shape [None, 5]
```

**But following usage will not cause the error** 
```
# Correct if not using tf.keras.Sequential
out1 = layers.Dense(2)(input1)
out1 = layers.Dense(1)(out1)
```

**Comment by ravikyram** [comment]
@Rogersjk 
Can you try running the code in latest -tf-nightly version(`!pip install tf-nightly`). I am not seeing any issue in Nightly version. Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/f642d14fddacae3d59be20b354406c37/untitled705.ipynb).Thanks!

**Comment by Rogersjk** [comment]
> @Rogersjk
> Can you try running the code in latest -tf-nightly version(`!pip install tf-nightly`). I am not seeing any issue in Nightly version. Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/f642d14fddacae3d59be20b354406c37/untitled705.ipynb).Thanks!

Thank you @ravikyram , I change the tensorflow version to 2.0.1, the error also disappears. So I guess it's the problem of tensorflow version 2.1.0

**Comment by ravikyram** [comment]
@Rogersjk 

You could use tf-nightly for now and in the next couple of months new stable version will be released. I am closing the issue for now. Please feel free to open the issue if it persists with the new version. Thanks!

**Comment by Rogersjk** [comment]
> @Rogersjk
> 
> You could use tf-nightly for now and in the next couple of months new stable version will be released. I am closing the issue for now. Please feel free to open the issue if it persists with the new version. Thanks!

Thanks for your help.
