### ISSUE TITLE
No module named tensorflow.python.platform

### ISSUE THREAD

**Issue by hiro106** [tensorflow/tensorflow#374]
Hi, I am running tensorflow/g3doc/tutorials/mnist/fully_connected_feed.py. I get:

hiro106@hiro106-virtual-machine:~$ python tensorflow/tensorflow/g3doc/tutorials/mnist/fully_connected_feed.py
Traceback (most recent call last):
  File "tensorflow/tensorflow/g3doc/tutorials/mnist/fully_connected_feed.py", line 33, in <module>
    import tensorflow.python.platform
ImportError: No module named tensorflow.python.platform

If you have any idea, please help me.
Thanks,

**Comment by girving** [comment]
Have you installed tensorflow?  Does `import tensorflow` work in a Python shell?

**Comment by girving** [comment]
Closing due to lack of activity.  Please reopen if you're still having issues.

**Comment by technologiclee** [comment]
I get the same error trying this example on a Docker install.
I am able to see TensorBoard so  I know TensorFlow is working.
https://www.tensorflow.org/versions/master/tutorials/seq2seq/index.html
`python translate.py --data_dir [your_data_directory]`

technologiclee@docker-playground:~/mytensorflow/tensorflow/tensorflow/models/rnn/translate$ python translate.py 
--data_dir [your_data_directory]
Traceback (most recent call last):
  File "translate.py", line 40, in <module>
    import tensorflow.python.platform
ImportError: No module named tensorflow.python.platform
technologiclee@docker-playground:~/mytensorflow/tensorflow/tensorflow/models/rnn/translate$ python
Python 2.7.3 (default, Mar 13 2014, 11:03:55) 
[GCC 4.7.2] on linux2
>>> import tensorflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named tensorflow

**Comment by technologiclee** [comment]
I think this is the same error, but did not solve the problem for me in Docker.

https://github.com/tensorflow/tensorflow/issues/265

PYTHONPATH="${PYTHONPATH}:/usr/local/lib/python2.7/dist-packages/"
export PYTHONPATH

Make sure to check your path with this: echo $PYTHONPATH

**Comment by ushnish** [comment]
Actually I had this issue because I was trying to import tensorflow from a python session inside the tensorflow repo folder, going to some other folder and starting python and importing tensorflow worked for me.

**Comment by adam-dziedzic** [comment]
Somehow, the same advice was given when installing tensorflow from the the source code https://www.tensorflow.org/install/install_sources :

Validate your TensorFlow installation by doing the following:

Start a terminal.

Change directory (cd) to any directory on your system other than the tensorflow subdirectory from which you invoked the configure command.

Invoke python:

$ python

**Comment by lukaszlew** [comment]
Same problem here.

**Comment by KingRando95** [comment]
agpl.fsf.org/emailselfdefense.fsf.org/edward.pub<https://drive.google.com/uc?id=1ap2a-LnApeVd6SVmW9auxxV-oBh26SSN&export=download>

Get Outlook for Android<https://aka.ms/ghei36>

**Comment by subashp** [comment]
weird and @ushnish solution works. Anyone with idea why it happens so?

**Comment by knsong** [comment]
@ushnish  It does work! But why?

**Comment by ailias** [comment]
GodMan:~ ailias$ python   <== on my home dir
Python 2.7.10 (default, Feb  7 2017, 00:08:15) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
dyld: warning, LC_RPATH $ORIGIN/../../_solib_darwin_x86_64/_U_S_Stensorflow_Spython_C_Upywrap_Utensorflow_Uinternal.so___Utensorflow in /Library/Python/2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so being ignored in restricted program because it is a relative path
>>> tf.__version__
'1.4.0'
>>> exit()   <== import success
GodMan:~ ailias$ cd Documents/tensorflow     <== on my tensorflow source code dir and build success
GodMan:tensorflow ailias$ python
Python 2.7.10 (default, Feb  7 2017, 00:08:15) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "tensorflow/python/pywrap_tensorflow.py", line 25, in <module>
    from tensorflow.python.platform import self_check
ImportError: No module named platform
>>>   <== import error.

Why do we get the error on different directory ? Due to tensorflow root dir has same name 'tensorflow' subdirectory, so if we import tensorflow from root dir, actually we import these dir to our module not our built tensorflow framework. So I think the subdir name should not be the same name with tensorflow. You can have a try.

**Comment by kannadaraj** [comment]
Ushnish.. That's just brilliant..

**Comment by Elmirrah** [comment]
@ushnish . please give an example . i don't get it

**Comment by ushnish** [comment]
@Elmirrah you can start python interpreter (in your terminal) from any folder except the tensorflow repo folder itself, and then you can import tensorflow

**Comment by bufistov** [comment]
Acording to @ailias you would run into this or another issue when there is a "tensorflow" folder in your current directory:
$ mkdir tensorflow
$ touch tensorflow/__init__.py
$ python -c 'import tensorflow; print(tensorflow.__version__)'

Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute '__version__'

**Comment by baregawi** [comment]
I put a local bazel build of TensorFlow in my `PYTHONPATH` and got this issue. I'll update if I solve this bug.

**Comment by venuswu** [comment]
@ushnish ,it works, and why, so brillant.

**Comment by Chloejay** [comment]
why I deploy the tensorflow object-detection models on aws p3 instance, I got the `ModuleNotFoundError: No module named 'tensorflow.python.platform'` when ran the train.py, is any steps I missing when config? 
<img width="1099" alt="Screen Shot 2019-03-29 at 16 32 01" src="https://user-images.githubusercontent.com/24205486/55219943-12024000-5241-11e9-9918-a7c4270c8610.png">

**Comment by Chloejay** [comment]
@ushnish is that also working on the aws instance?

**Comment by Jona2jef** [comment]
Chaning directory not working for me.
Running pip3 list returns the following:

Package              Version
-------------------- -------
absl-py              0.8.0
astor                0.8.0
astroid              2.3.1
gast                 0.3.2
google-pasta         0.1.7
grpcio               1.16.1
h5py                 2.8.0
isort                4.3.21
Keras-Applications   1.0.8
Keras-Preprocessing  1.1.0
lazy-object-proxy    1.4.2
Markdown             3.1.1
mccabe               0.6.1
numpy                1.16.2
pip                  19.2.3
protobuf             3.9.2
pylint               2.4.2
python-apt           1.8.4
setuptools           41.2.0
six                  1.12.0
tensorboard          1.14.0
tensorflow           1.14.0
tensorflow-estimator 1.14.0
termcolor            1.1.0
typed-ast            1.4.0
Werkzeug             0.16.0
wheel                0.33.6
wrapt                1.11.2

OS:DietPi on Orange Pi Zero ARMV7

**Comment by Viibrant** [comment]
`Error: While importing "web", an ImportError was raised:

Traceback (most recent call last):
  File "/home/connor/.local/lib/python3.7/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/home/connor/programming/python/Automated-Checkout/web.py", line 3, in <module>
    from prediction import NeuralNetwork
  File "/home/connor/programming/python/Automated-Checkout/prediction.py", line 2, in <module>
    from keras.preprocessing.image import img_to_array
  File "/home/connor/.local/lib/python3.7/site-packages/keras/__init__.py", line 3, in <module>
    from . import utils
  File "/home/connor/.local/lib/python3.7/site-packages/keras/utils/__init__.py", line 6, in <module>
    from . import conv_utils
  File "/home/connor/.local/lib/python3.7/site-packages/keras/utils/conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "/home/connor/.local/lib/python3.7/site-packages/keras/backend/__init__.py", line 1, in <module>
    from .load_backend import epsilon
  File "/home/connor/.local/lib/python3.7/site-packages/keras/backend/load_backend.py", line 90, in <module>
    from .tensorflow_backend import *
  File "/home/connor/.local/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 25, in <module>
    from tensorflow.python.platform import self_check
ModuleNotFoundError: No module named 'tensorflow.python.platform'
`
I am also getting the same error on Tensorflow 2.1.0 and Python 3.7.6

**Comment by mohlondon** [comment]
>>> import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kali/.conda/envs/chatbot/lib/python3.6/site-packages/tensorflow/__init__.py", line 101, in <module>
    from tensorflow_core import *
  File "/home/kali/.conda/envs/chatbot/lib/python3.6/site-packages/tensorflow_core/__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/home/kali/.conda/envs/chatbot/lib/python3.6/site-packages/tensorflow/__init__.py", line 50, in __getattr__
    module = self._load()
  File "/home/kali/.conda/envs/chatbot/lib/python3.6/site-packages/tensorflow/__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "/home/kali/.conda/envs/chatbot/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/kali/.conda/envs/chatbot/lib/python3.6/site-packages/tensorflow_core/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/kali/.conda/envs/chatbot/lib/python3.6/site-packages/tensorflow_core/python/pywrap_tensorflow.py", line 25, in <module>
    from tensorflow.python.platform import self_check
ModuleNotFoundError: No module named 'tensorflow.python.platform'
i got the same problem when i try to import tensorflow 
i guess this heppend when i installed tensorflow-gpu
any help ??

**Comment by Jona2jef** [comment]
I too got several errors after installing TensorFlow-GPU. There wasn't any other way but to reinstall tensorflow and tensorflow-gpu:
pip3 install --user --upgrade --force-reinstall tensorflow tensorflow-gpu (--user flag not required when using a conda or virtualenv virtual environment)

**Comment by Navya-reddy-r** [comment]
> pip3 install --user --upgrade --force-reinstall tensorflow tensorflow-gpu

it still didn't work for me

**Comment by mbgpriyanka** [comment]
Hi,
I am encountering the same error-
    from tensorflow.python.platform import self_check
ModuleNotFoundError: No module named 'tensorflow.python.platform'

I am on windows 10 system and have tf =1.5.2 installed
any solution to this ?

**Comment by vidstige** [comment]
I got the same, but fixed it by installing `tensorflow-gpu` as well (`pip install tensorflow-gpu`)

**Comment by ardaeerol** [comment]
relevant import error: 

>>> import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/Downloads/tfederated/lib/python3.7/site-packages/tensorflow/__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/home/user/Downloads/tfederated/lib/python3.7/site-packages/tensorflow/python/__init__.py", line 36, in <module>
    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow
  File "/home/user/Downloads/tfederated/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 21, in <module>
    from tensorflow.python.platform import self_check
ModuleNotFoundError: No module named 'tensorflow.python.platform'

Raspberry Pi OS
Python                                      3.7.16
tensorboard                              2.11.2
tensorboard-data-server           0.6.1
tensorboard-plugin-wit              1.8.1
tensorflow                                 2.11.0
tensorflow-cpu-aws                   2.11.0
tensorflow-estimator                 2.11.0
tensorflow-federated                 0.1.0
tensorflow-io-gcs-filesystem     0.29.0

I am trying to implement tensorflow federated on raspi and finally find a stable Python version that can execute tf federated on raspi. (So i used python 3.7.16) But now, i take an import error.
