### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [3,3,3,32] rhs shape= [3,3,1,32] 	 [[{{node save/Assign_78}}]]

### ISSUE THREAD

**Issue by saqibshakeel035** [tensorflow/tensorflow#37417]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Mint 19.1
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 1.14
- Python version: 3.7
- Installed using virtualenv? pip? conda?: conda
- Bazel version (if compiling from source):N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the problem**
Model: ssd_mobilenet_v2_quantized_300x300_coco.config

I am facing the issue of converting a custom trained model from checkpoint into inference graphs using the following commands:
`python export_tflite_ssd_graph.py \`
`--pipeline_config_path=/training/ssd_mobilenet_v2_quantized_300x300_coco.config \`
`--trained_checkpoint_prefix=/training/model.ckpt-1000 \`
`--output_directory=/inference_graph/ \`
`--add_postprocessing_op=true`

**Following is how my config file looks like:**
 ```
model {
  ssd {
    num_classes: 6
    box_coder {
      faster_rcnn_box_coder {
        y_scale: 10.0
        x_scale: 10.0
        height_scale: 5.0
        width_scale: 5.0
      }
    }
    matcher {
      argmax_matcher {
        matched_threshold: 0.5
        unmatched_threshold: 0.5
        ignore_thresholds: false
        negatives_lower_than_unmatched: true
        force_match_for_each_row: true
      }
    }
    similarity_calculator {
      iou_similarity {
      }
    }
    anchor_generator {
      ssd_anchor_generator {
        num_layers: 6
        min_scale: 0.2
        max_scale: 0.95
        aspect_ratios: 1.0
        aspect_ratios: 2.0
        aspect_ratios: 0.5
        aspect_ratios: 3.0
        aspect_ratios: 0.3333
      }
    }
    image_resizer {
      fixed_shape_resizer {
        height: 300
        width: 300
      }
    }
    box_predictor {
      convolutional_box_predictor {
        min_depth: 0
        max_depth: 0
        num_layers_before_predictor: 0
        use_dropout: false
        dropout_keep_probability: 0.8
        kernel_size: 1
        box_code_size: 4
        apply_sigmoid_to_scores: false
        conv_hyperparams {
          activation: RELU_6,
          regularizer {
            l2_regularizer {
              weight: 0.00004
            }
          }
          initializer {
            truncated_normal_initializer {
              stddev: 0.03
              mean: 0.0
            }
          }
          batch_norm {
            train: true,
            scale: true,
            center: true,
            decay: 0.9997,
            epsilon: 0.001,
          }
        }
      }Following is how my config file looks like:
    }
    feature_extractor {
      type: 'ssd_mobilenet_v2'
      min_depth: 16
      depth_multiplier: 1.0
      conv_hyperparams {
        activation: RELU_6,
        regularizer {
          l2_regularizer {
            weight: 0.00004
          }
        }
        initializer {
          truncated_normal_initializer {
            stddev: 0.03
            mean: 0.0
          }
        }
        batch_norm {
          train: true,
          scale: true,
          center: true,
          decay: 0.9997,
          epsilon: 0.001,
        }
      }
    }
    loss {
      classification_loss {
        weighted_sigmoid {
        }
      }
      localization_loss {
        weighted_smooth_l1 {
        }
      }
      hard_example_miner {
        num_hard_examples: 3000
        iou_threshold: 0.99
        loss_type: CLASSIFICATION
        max_negatives_per_positive: 3
        min_negatives_per_image: 3
      }
      classification_weight: 1.0
      localization_weight: 1.0
    }
    normalize_loss_by_num_matches: true
    post_processing {
      batch_non_max_suppression {
        score_threshold: 1e-8
        iou_threshold: 0.6
        max_detections_per_class: 100
        max_total_detections: 100
      }
      score_converter: SIGMOID
    }
  }
}

train_config: {
  batch_size: 5
  optimizer {
    rms_prop_optimizer: {
      learning_rate: {
        exponential_decay_learning_rate {
          initial_learning_rate: 0.004
          decay_steps: 800720
          decay_factor: 0.95
        }
      }
      momentum_optimizer_value: 0.9
      decay: 0.9
      epsilon: 1.0
    }
  }
  fine_tune_checkpoint: "/object_detection/ssd_mobilenet_v2_quantized_300x300_coco_2019_01_03/model.ckpt"
  fine_tune_checkpoint_type:  "detection"
  num_steps: 1000
  data_augmentation_options {
    random_horizontal_flip {
    }
  }
  data_augmentation_options {
    ssd_random_crop {
    }
  }
  data_augmentation_options {
    random_rgb_to_gray {
    }
  }

 data_augmentation_options {
    random_adjust_brightness {
    }
  }

 data_augmentation_options {
    random_adjust_contrast {
    }
  }
  
 data_augmentation_options {
    random_adjust_hue {
    }
  }
  
  
 data_augmentation_options {
    random_adjust_saturation {
    }
  }
  
  
 data_augmentation_options {
    rgb_to_gray {
    }
  }
}

train_input_reader: {
  tf_record_input_reader {
    input_path: "/object_detection/train.record"
  }
  label_map_path: "/object_detection/training/labelmap.pbtxt"
}

eval_config: {
  num_examples: 3
  max_evals: 10
}

eval_input_reader: {
  tf_record_input_reader {
    input_path: "/object_detection/test.record"
  }
  label_map_path: "/object_detection/training/labelmap.pbtxt"
  shuffle: false
  num_readers: 1
}

graph_rewriter {
  quantization {
    delay: 48000
    weight_bits: 8
    activation_bits: 8
  }
} 
```
**Provide the exact sequence of commands / steps that you executed before running into the problem**
I have added the following lines of code for augmentation in the config file:
 ```
 data_augmentation_options {
    random_rgb_to_gray {
    }
  }

 data_augmentation_options {
    random_adjust_brightness {
    }
  }

 data_augmentation_options {
    random_adjust_contrast {
    }
  }
  
 data_augmentation_options {
    random_adjust_hue {
    }
  }
  
  
 data_augmentation_options {
    random_adjust_saturation {
    }
  }
  
  
 data_augmentation_options {
    rgb_to_gray {
    }
  }

```

**Any other info / logs**
Here is the error, I want to know the cause of the error and that, does addition of augmentation in config  also requires any other change?
 ```
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/Conv/add_fold
I0307 23:21:08.443011 140338966099776 quantize.py:298] Skipping quant after FeatureExtractor/MobilenetV2/Conv/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv/depthwise/add_fold
I0307 23:21:08.443283 140338966099776 quantize.py:298] Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv/depthwise/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_1/expand/add_fold
I0307 23:21:08.443521 140338966099776 quantize.py:298] Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_1/expand/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_1/depthwise/add_fold
I0307 23:21:08.443677 140338966099776 quantize.py:298] Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_1/depthwise/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_2/expand/add_fold
I0307 23:21:08.443905 140338966099776 quantize.py:298] Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_2/expand/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_2/depthwise/add_fold
I0307 23:21:08.444058 140338966099776 quantize.py:298] Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_2/depthwise/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_3/expand/add_fold
I0307 23:21:08.444283 140338966099776 quantize.py:298] Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_3/expand/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_3/depthwise/add_fold
I0307 23:21:08.444431 140338966099776 quantize.py:298] Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_3/depthwise/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_4/expand/add_fold
I0307 23:21:08.444655 140338966099776 quantize.py:298] Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_4/expand/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_4/depthwise/add_fold
I0307 23:21:08.444802 140338966099776 quantize.py:298] Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_4/depthwise/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_5/expand/add_fold
I0307 23:21:08.445024 140338966099776 quantize.py:298] Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_5/expand/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_5/depthwise/add_fold
I0307 23:21:08.445170 140338966099776 quantize.py:298] Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_5/depthwise/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_6/expand/add_fold
I0307 23:21:08.445389 140338966099776 quantize.py:298] Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_6/expand/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_6/depthwise/add_fold
I0307 23:21:08.445536 140338966099776 quantize.py:298] Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_6/depthwise/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_7/expand/add_fold
I0307 23:21:08.445757 140338966099776 quantize.py:298] Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_7/expand/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_7/depthwise/add_fold
I0307 23:21:08.445903 140338966099776 quantize.py:298] Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_7/depthwise/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_8/expand/add_fold
I0307 23:21:08.446130 140338966099776 quantize.py:298] Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_8/expand/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_8/depthwise/add_fold
I0307 23:21:08.446278 140338966099776 quantize.py:298] Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_8/depthwise/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_9/expand/add_fold
I0307 23:21:08.446502 140338966099776 quantize.py:298] Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_9/expand/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_9/depthwise/add_fold
I0307 23:21:08.446648 140338966099776 quantize.py:298] Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_9/depthwise/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_10/expand/add_fold
I0307 23:21:08.446869 140338966099776 quantize.py:298] Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_10/expand/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_10/depthwise/add_fold
I0307 23:21:08.447014 140338966099776 quantize.py:298] Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_10/depthwise/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_11/expand/add_fold
I0307 23:21:08.447235 140338966099776 quantize.py:298] Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_11/expand/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_11/depthwise/add_fold
I0307 23:21:08.447381 140338966099776 quantize.py:298] Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_11/depthwise/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_12/expand/add_fold
I0307 23:21:08.447600 140338966099776 quantize.py:298] Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_12/expand/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_12/depthwise/add_fold
I0307 23:21:08.447747 140338966099776 quantize.py:298] Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_12/depthwise/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_13/expand/add_fold
I0307 23:21:08.447968 140338966099776 quantize.py:298] Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_13/expand/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_13/depthwise/add_fold
I0307 23:21:08.448114 140338966099776 quantize.py:298] Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_13/depthwise/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_14/expand/add_fold
I0307 23:21:08.448335 140338966099776 quantize.py:298] Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_14/expand/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_14/depthwise/add_fold
I0307 23:21:08.448482 140338966099776 quantize.py:298] Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_14/depthwise/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_15/expand/add_fold
I0307 23:21:08.448699 140338966099776 quantize.py:298] Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_15/expand/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_15/depthwise/add_fold
I0307 23:21:08.448843 140338966099776 quantize.py:298] Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_15/depthwise/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_16/expand/add_fold
I0307 23:21:08.449064 140338966099776 quantize.py:298] Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_16/expand/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_16/depthwise/add_fold
I0307 23:21:08.449210 140338966099776 quantize.py:298] Skipping quant after FeatureExtractor/MobilenetV2/expanded_conv_16/depthwise/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/Conv_1/add_fold
I0307 23:21:08.449432 140338966099776 quantize.py:298] Skipping quant after FeatureExtractor/MobilenetV2/Conv_1/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/layer_19_1_Conv2d_2_1x1_256/add_fold
I0307 23:21:08.449569 140338966099776 quantize.py:298] Skipping quant after FeatureExtractor/MobilenetV2/layer_19_1_Conv2d_2_1x1_256/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/layer_19_2_Conv2d_2_3x3_s2_512/add_fold
I0307 23:21:08.449709 140338966099776 quantize.py:298] Skipping quant after FeatureExtractor/MobilenetV2/layer_19_2_Conv2d_2_3x3_s2_512/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/layer_19_1_Conv2d_3_1x1_128/add_fold
I0307 23:21:08.449849 140338966099776 quantize.py:298] Skipping quant after FeatureExtractor/MobilenetV2/layer_19_1_Conv2d_3_1x1_128/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/layer_19_2_Conv2d_3_3x3_s2_256/add_fold
I0307 23:21:08.449984 140338966099776 quantize.py:298] Skipping quant after FeatureExtractor/MobilenetV2/layer_19_2_Conv2d_3_3x3_s2_256/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/layer_19_1_Conv2d_4_1x1_128/add_fold
I0307 23:21:08.450125 140338966099776 quantize.py:298] Skipping quant after FeatureExtractor/MobilenetV2/layer_19_1_Conv2d_4_1x1_128/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/layer_19_2_Conv2d_4_3x3_s2_256/add_fold
I0307 23:21:08.450264 140338966099776 quantize.py:298] Skipping quant after FeatureExtractor/MobilenetV2/layer_19_2_Conv2d_4_3x3_s2_256/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/layer_19_1_Conv2d_5_1x1_64/add_fold
I0307 23:21:08.450404 140338966099776 quantize.py:298] Skipping quant after FeatureExtractor/MobilenetV2/layer_19_1_Conv2d_5_1x1_64/add_fold
INFO:tensorflow:Skipping quant after FeatureExtractor/MobilenetV2/layer_19_2_Conv2d_5_3x3_s2_128/add_fold
I0307 23:21:08.450541 140338966099776 quantize.py:298] Skipping quant after FeatureExtractor/MobilenetV2/layer_19_2_Conv2d_5_3x3_s2_128/add_fold
WARNING:tensorflow:From /root/anaconda3/envs/tensorflow1/lib/python3.6/site-packages/object_detection-0.1-py3.6.egg/object_detection/export_tflite_ssd_graph_lib.py:259: The name tf.train.Saver is deprecated. Please use tf.compat.v1.train.Saver instead.

W0307 23:21:08.452883 140338966099776 deprecation_wrapper.py:119] From /root/anaconda3/envs/tensorflow1/lib/python3.6/site-packages/object_detection-0.1-py3.6.egg/object_detection/export_tflite_ssd_graph_lib.py:259: The name tf.train.Saver is deprecated. Please use tf.compat.v1.train.Saver instead.

WARNING:tensorflow:From /root/anaconda3/envs/tensorflow1/lib/python3.6/site-packages/tensorflow/python/tools/freeze_graph.py:127: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
W0307 23:21:08.877874 140338966099776 deprecation.py:323] From /root/anaconda3/envs/tensorflow1/lib/python3.6/site-packages/tensorflow/python/tools/freeze_graph.py:127: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
INFO:tensorflow:Restoring parameters from /home/models/research/object_detection/training/model.ckpt-0
I0307 23:21:09.683899 140338966099776 saver.py:1280] Restoring parameters from /home/models/research/object_detection/training/model.ckpt-0
Traceback (most recent call last):
  File "/root/anaconda3/envs/tensorflow1/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/root/anaconda3/envs/tensorflow1/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/root/anaconda3/envs/tensorflow1/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [3,3,3,32] rhs shape= [3,3,1,32]
	 [[{{node save/Assign_78}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/envs/tensorflow1/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1286, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/root/anaconda3/envs/tensorflow1/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/root/anaconda3/envs/tensorflow1/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/root/anaconda3/envs/tensorflow1/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/root/anaconda3/envs/tensorflow1/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [3,3,3,32] rhs shape= [3,3,1,32]
	 [[node save/Assign_78 (defined at /root/anaconda3/envs/tensorflow1/lib/python3.6/site-packages/object_detection-0.1-py3.6.egg/object_detection/export_tflite_ssd_graph_lib.py:259) ]]

Errors may have originated from an input operation.
Input Source operations connected to node save/Assign_78:
 FeatureExtractor/MobilenetV2/Conv/weights (defined at /root/anaconda3/envs/tensorflow1/lib/python3.6/site-packages/slim-0.1-py3.6.egg/nets/mobilenet/mobilenet.py:277)

Original stack trace for 'save/Assign_78':
  File "export_tflite_ssd_graph.py", line 137, in <module>
    tf.app.run(main)
  File "/root/anaconda3/envs/tensorflow1/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/root/anaconda3/envs/tensorflow1/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/root/anaconda3/envs/tensorflow1/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "export_tflite_ssd_graph.py", line 133, in main
    FLAGS.max_classes_per_detection)
  File "/root/anaconda3/envs/tensorflow1/lib/python3.6/site-packages/object_detection-0.1-py3.6.egg/object_detection/export_tflite_ssd_graph_lib.py", line 259, in export_tflite_graph
    saver = tf.train.Saver(**saver_kwargs)
  File "/root/anaconda3/envs/tensorflow1/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 825, in __init__
    self.build()
  File "/root/anaconda3/envs/tensorflow1/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 837, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/root/anaconda3/envs/tensorflow1/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 875, in _build
    build_restore=build_restore)
  File "/root/anaconda3/envs/tensorflow1/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 508, in _build_internal
    restore_sequentially, reshape)
  File "/root/anaconda3/envs/tensorflow1/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 350, in _AddRestoreOps
    assign_ops.append(saveable.restore(saveable_tensors, shapes))
  File "/root/anaconda3/envs/tensorflow1/lib/python3.6/site-packages/tensorflow/python/training/saving/saveable_object_util.py", line 72, in restore
    self.op.get_shape().is_fully_defined())
  File "/root/anaconda3/envs/tensorflow1/lib/python3.6/site-packages/tensorflow/python/ops/state_ops.py", line 227, in assign
    validate_shape=validate_shape)
  File "/root/anaconda3/envs/tensorflow1/lib/python3.6/site-packages/tensorflow/python/ops/gen_state_ops.py", line 66, in assign
    use_locking=use_locking, name=name)
  File "/root/anaconda3/envs/tensorflow1/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/root/anaconda3/envs/tensorflow1/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/root/anaconda3/envs/tensorflow1/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3616, in create_op
    op_def=op_def)
  File "/root/anaconda3/envs/tensorflow1/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "export_tflite_ssd_graph.py", line 137, in <module>
    tf.app.run(main)
  File "/root/anaconda3/envs/tensorflow1/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/root/anaconda3/envs/tensorflow1/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/root/anaconda3/envs/tensorflow1/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "export_tflite_ssd_graph.py", line 133, in main
    FLAGS.max_classes_per_detection)
  File "/root/anaconda3/envs/tensorflow1/lib/python3.6/site-packages/object_detection-0.1-py3.6.egg/object_detection/export_tflite_ssd_graph_lib.py", line 273, in export_tflite_graph
    initializer_nodes='')
  File "/root/anaconda3/envs/tensorflow1/lib/python3.6/site-packages/tensorflow/python/tools/freeze_graph.py", line 151, in freeze_graph_with_def_protos
    saver.restore(sess, input_checkpoint)
  File "/root/anaconda3/envs/tensorflow1/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1322, in restore
    err, "a mismatch between the current graph and the graph")
tensorflow.python.framework.errors_impl.InvalidArgumentError: Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Assign requires shapes of both tensors to match. lhs shape= [3,3,3,32] rhs shape= [3,3,1,32]
	 [[node save/Assign_78 (defined at /root/anaconda3/envs/tensorflow1/lib/python3.6/site-packages/object_detection-0.1-py3.6.egg/object_detection/export_tflite_ssd_graph_lib.py:259) ]]

Errors may have originated from an input operation.
Input Source operations connected to node save/Assign_78:
 FeatureExtractor/MobilenetV2/Conv/weights (defined at /root/anaconda3/envs/tensorflow1/lib/python3.6/site-packages/slim-0.1-py3.6.egg/nets/mobilenet/mobilenet.py:277)

Original stack trace for 'save/Assign_78':
  File "export_tflite_ssd_graph.py", line 137, in <module>
    tf.app.run(main)
  File "/root/anaconda3/envs/tensorflow1/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/root/anaconda3/envs/tensorflow1/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/root/anaconda3/envs/tensorflow1/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "export_tflite_ssd_graph.py", line 133, in main
    FLAGS.max_classes_per_detection)
  File "/root/anaconda3/envs/tensorflow1/lib/python3.6/site-packages/object_detection-0.1-py3.6.egg/object_detection/export_tflite_ssd_graph_lib.py", line 259, in export_tflite_graph
    saver = tf.train.Saver(**saver_kwargs)
  File "/root/anaconda3/envs/tensorflow1/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 825, in __init__
    self.build()
  File "/root/anaconda3/envs/tensorflow1/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 837, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/root/anaconda3/envs/tensorflow1/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 875, in _build
    build_restore=build_restore)
  File "/root/anaconda3/envs/tensorflow1/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 508, in _build_internal
    restore_sequentially, reshape)
  File "/root/anaconda3/envs/tensorflow1/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 350, in _AddRestoreOps
    assign_ops.append(saveable.restore(saveable_tensors, shapes))
  File "/root/anaconda3/envs/tensorflow1/lib/python3.6/site-packages/tensorflow/python/training/saving/saveable_object_util.py", line 72, in restore
    self.op.get_shape().is_fully_defined())
  File "/root/anaconda3/envs/tensorflow1/lib/python3.6/site-packages/tensorflow/python/ops/state_ops.py", line 227, in assign
    validate_shape=validate_shape)
  File "/root/anaconda3/envs/tensorflow1/lib/python3.6/site-packages/tensorflow/python/ops/gen_state_ops.py", line 66, in assign
    use_locking=use_locking, name=name)
  File "/root/anaconda3/envs/tensorflow1/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/root/anaconda3/envs/tensorflow1/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/root/anaconda3/envs/tensorflow1/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3616, in create_op
    op_def=op_def)
  File "/root/anaconda3/envs/tensorflow1/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()
```

**Comment by lintian06** [comment]
Hi @saqibshakeel035,

I don't know whether you have figured it out yourself. 

The script export_tflite_ssd_graph.py is from [tensorflow/models/research/object_detection](https://github.com/tensorflow/models/blob/80444539849453d45fa2ecfcce7fbeb47d863897/research/object_detection/g3doc/running_on_mobile_tensorflowlite.md), and maintained by the owners of the research project. It seems that your script is related to how to use the script from project [object_detection](https://github.com/tensorflow/models/tree/9bbf8015dba2133ab2343ec6d6b5096033504e36/research/object_detection) in particular. Would it be better to ask maintainers of the project there. 

Thx! :-)

**Comment by saqibshakeel035** [comment]
> Hi @saqibshakeel035,
> 
> I don't know whether you have figured it out yourself.
> 
> The script export_tflite_ssd_graph.py is from [tensorflow/models/research/object_detection](https://github.com/tensorflow/models/blob/80444539849453d45fa2ecfcce7fbeb47d863897/research/object_detection/g3doc/running_on_mobile_tensorflowlite.md), and maintained by the owners of the research project. It seems that your script is related to how to use the script from project [object_detection](https://github.com/tensorflow/models/tree/9bbf8015dba2133ab2343ec6d6b5096033504e36/research/object_detection) in particular. Would it be better to ask maintainers of the project there.
> 
> Thx! :-)

I came to know that the error is because of the augmentation 
```
data_augmentation_options {
   random_rgb_to_gray {
   }
```
Grey contains only 1 channel whereas RGB contains 3 color channels. I didn't dig out how to rectify this issue but removing this augmentation resolved this issue of shape mismatch.
