### ISSUE TITLE
AttributeError: module 'tensorboard' has no attribute 'lazy'

### ISSUE THREAD

**Issue by PreVizsla** [tensorflow/tensorflow#37433]
I've been trying to import tensorflow, downloading Anaconda 3, creating virtual environment, use pip install tensorflow, pip install keras and when I try to import tensorflow an error occured  "Failed to load the native TensorFlow runtime." then I tried to resolve it by downloading cygwin to update the gcc. After that, another error occured 

```
2020-01-21 16:18:17.197417: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-01-21 16:18:17.197832: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
```

Tried to solve it by downloading CUDA 10.1 version and now the problem is

```
2020-03-09 14:17:07.528838: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
```

This is a problem because after that all process finished with exit code 1 and print('test') cannot even be processed after this.

System information:
Anaconda 3
Windows 10
Tensorflow 2.1
Inteil Core I5
Gtx 1050 ti
CUDA version 10.1
python version 3.6.1

Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.

The errors when I try to import tensorflow:

```
2020-03-09 14:17:07.528838: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
Traceback (most recent call last):
  File "C:/Users/User/PycharmProjects/tensortest/test.py", line 1, in <module>
    import tensorflow
  File "C:\Users\User\Anaconda3\envs\tensortest\lib\site-packages\tensorflow\__init__.py", line 101, in <module>
    from tensorflow_core import *
  File "C:\Users\User\Anaconda3\envs\tensortest\lib\site-packages\tensorflow_core\__init__.py", line 46, in <module>
    from . _api.v2 import compat
  File "C:\Users\User\Anaconda3\envs\tensortest\lib\site-packages\tensorflow_core\_api\v2\compat\__init__.py", line 39, in <module>
    from . import v1
  File "C:\Users\User\Anaconda3\envs\tensortest\lib\site-packages\tensorflow_core\_api\v2\compat\v1\__init__.py", line 32, in <module>
    from . import compat
  File "C:\Users\User\Anaconda3\envs\tensortest\lib\site-packages\tensorflow_core\_api\v2\compat\v1\compat\__init__.py", line 39, in <module>
    from . import v1
  File "C:\Users\User\Anaconda3\envs\tensortest\lib\site-packages\tensorflow_core\_api\v2\compat\v1\compat\v1\__init__.py", line 29, in <module>
    from tensorflow._api.v2.compat.v1 import app
  File "C:\Users\User\Anaconda3\envs\tensortest\lib\site-packages\tensorflow_core\_api\v2\compat\__init__.py", line 39, in <module>
    from . import v1
  File "C:\Users\User\Anaconda3\envs\tensortest\lib\site-packages\tensorflow_core\_api\v2\compat\v1\__init__.py", line 32, in <module>
    from . import compat
  File "C:\Users\User\Anaconda3\envs\tensortest\lib\site-packages\tensorflow_core\_api\v2\compat\v1\compat\__init__.py", line 40, in <module>
    from . import v2
  File "C:\Users\User\Anaconda3\envs\tensortest\lib\site-packages\tensorflow_core\_api\v2\compat\v1\compat\v2\__init__.py", line 30, in <module>
    from tensorflow._api.v2.compat.v2 import audio
  File "C:\Users\User\Anaconda3\envs\tensortest\lib\site-packages\tensorflow_core\_api\v2\compat\v2\__init__.py", line 33, in <module>
    from . import compat
  File "C:\Users\User\Anaconda3\envs\tensortest\lib\site-packages\tensorflow_core\_api\v2\compat\v2\compat\__init__.py", line 40, in <module>
    from . import v2
  File "C:\Users\User\Anaconda3\envs\tensortest\lib\site-packages\tensorflow_core\_api\v2\compat\v2\compat\v2\__init__.py", line 320, in <module>
    from tensorboard.summary._tf import summary
  File "C:\Users\User\Anaconda3\envs\tensortest\lib\site-packages\tensorboard\summary\__init__.py", line 31, in <module>
    from tensorboard.summary import v2
  File "C:\Users\User\Anaconda3\envs\tensortest\lib\site-packages\tensorboard\summary\v2.py", line 24, in <module>
    from tensorboard.plugins.audio.summary_v2 import audio
  File "C:\Users\User\Anaconda3\envs\tensortest\lib\site-packages\tensorboard\plugins\audio\summary_v2.py", line 30, in <module>
    from tensorboard.compat import tf2 as tf
  File "C:\Users\User\Anaconda3\envs\tensortest\lib\site-packages\tensorboard\compat\__init__.py", line 28, in <module>
    import tensorboard.lazy as _lazy
AttributeError: module 'tensorboard' has no attribute 'lazy'

Process finished with exit code 1
```

**Comment by gadagashwini** [comment]
@PreVizsla, Did you install cuDNN? If not install cuDNN >=7.6 version. 
Please take a look at the [Tensorflow doc](https://www.tensorflow.org/install/gpu#software_requirements). Thanks

**Comment by PreVizsla** [comment]
yes, followed this https://www.easy-tensorflow.com/tf-tutorials/install/cuda-cudnn
and downloaded the 7.6 cuDNN and still same error

**Comment by PreVizsla** [comment]
Will installing an older version of tensorflow helps the problem? Since I have no idea what kind of problem makes this error

**Comment by hhakangull** [comment]
i have like this problem and i checked cudnn version but i have still this problem how i can fix ?

**Comment by A-i-q-o** [comment]
I also have this problem

**Comment by Jvdahemad** [comment]
Hi, did anyone find a solution to this? I am having the same trouble.

**Comment by Mehieddine44** [comment]
trying to run : 
from keras.preprocessing.image import load_img, img_to_array

and getting the same error

**Comment by yi-xu** [comment]
same thing here, any one has any solutions?

**Comment by rachitdev** [comment]
I am facing the same thing, can anyone please help!

**Comment by Seroveah** [comment]
Yep facing same issues, installed it and worked before in the past but with this fresh install I'm running into the same problems others are having.

**Comment by mihaimaruseac** [comment]
There is more than just errors printed to stderr. The log format is

```
date time: FEWID message
```

where `FEWID` is one of `F` (fatal error, program stops), `E` (error, program continues but with different behavior), `W` (warning), `I` (info), `D` (debug). The last 3 steps are useful for understanding behavior but are **NOT** errors

Thus:

```
2020-01-21 16:18:17.197417: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-01-21 16:18:17.197832: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
```

Doesn't mean that you need to install CUDA to use TF. You can use TF without having CUDA, it will just use CPU.

Also,

```
2020-03-09 14:17:07.528838: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
```

only means that the CUDA library was loaded. It is not an error.

The real error is 

```
...
  File "C:\Users\User\Anaconda3\envs\tensortest\lib\site-packages\tensorboard\compat\__init__.py", line 28, in <module>
    import tensorboard.lazy as _lazy
AttributeError: module 'tensorboard' has no attribute 'lazy'

Process finished with exit code 1
```

which makes me think you have an mismatched version of tensorboard and tensorflow. What does `pip list` print?

**Comment by awal-ahmed** [comment]
Update your 'NVIDIA Graphics Driver' with latest and compatible version for your PC.
Download Driver: https://www.nvidia.com/Download/index.aspx#
To find out required driver: https://youtu.be/a6ZdiNBPCC8

**Comment by DiptanshuMalviya** [comment]
please give the solution., I am also facing same issue
please.....
>>> import tensorflow
2020-05-20 17:55:45.825216: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\dipta\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\dipta\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\__init__.py", line 84, in <module>
    from tensorflow.python import keras
  File "C:\Users\dipta\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\keras\__init__.py", line 27, in <module>
    from tensorflow.python.keras import models
  File "C:\Users\dipta\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\keras\models.py", line 23, in <module>
    from tensorflow.python.keras import backend as K
  File "C:\Users\dipta\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\keras\backend.py", line 5948, in <module>
    assert _image_data_format in {'channels_last', 'channels_first'}
AssertionError

**Comment by gunan** [comment]
@nfelt could you take a look?
We suspect this is due to a mismatched TF/tensorboard version, but could not confirm.

**Comment by Farbum** [comment]
Had the same problem with anaconda with a fresh installation of Tensorflow 2.1.
Somehow fixed it by uninstalling tensorboard with pip and re-installing it:
pip uninstall tensorflow-tensorboard and then pip install tensorboard

**Comment by brandonssmith** [comment]
I'm getting the same error:
2020-06-10 20:15:45.369670: W tensorflow/stream_executor/platform/default/dso_loader.cc:

**Comment by PreVizsla** [comment]
actually I can now use the older version of tensor flow with no problem, I am using tensorflow 1.7 right now. But I haven't try to use the 2.0 version again.

**Comment by mihaimaruseac** [comment]
@johnLIC You should use the same versions for TF, estimator and tensorboard

@brandonssmith that's a warning, not an error

@PreVizsla yes, you can use any released TF but if you encounter a bug in a version we no longer support we won't be able to help you. And we won't issue security updates and patches to old versions.

**Comment by PreVizsla** [comment]
@mihaimaruseac how to check tensorboard verison? And do we need the exact same version for both TF and tensorboard?

**Comment by PreVizsla** [comment]
Surprisingly, After creating new conda virtual environment and downloading tensorflow and keras, I am able to run tensorflow 2.1 in pycharm with 20 Info notice in the console, but the script and tf works fine.

**Comment by brandonssmith** [comment]
holy crap I forgot how pedantic programmers can be

**Comment by brandonssmith** [comment]
@mihaimaruseac If it keeps me from progressing it's an error, I could care less how it is classified.

**Comment by gunan** [comment]
@brandonssmith What @mihaimaruseac meant was that message will not block your progress. There must be another issue that is blocking your progress. If you need help, please file a new issue providing all the details in the template.

Also, please make sure to abide by our community guidelines in your comments (referring to your deleted comment).

**Comment by mihaimaruseac** [comment]
@PreVizsla sorry, was away. `pip list` should display the version of all installed pip packages.

Installing in a new environment ensures that all dependencies are installed at a corresponding version

**Comment by irinawetransfer** [comment]
I have a similar issue in google colab:

- tensorflow version 2.2.0
- tensorboard version 2.2.2

```
%tensorboard --logdir drive/...
```

gives `AttributeError: module 'tensorboard' has no attribute 'lazy'`

**Comment by mihaimaruseac** [comment]
@irinawetransfer can you please post output of `pip list` and `pip debug --verbose`? Also, if possible, a minimal code that reproduces the issue?

**Comment by GhassenBenMakhlouf** [comment]
I have the same problem.
the output of pip list:
___________________________________________________________________________________________________________________________________
Package                  Version
------------------------ -----------
absl-py                  0.9.0
astunparse               1.6.3
cachetools               4.1.0
certifi                  2020.6.20
chardet                  3.0.4
gast                     0.3.3
google-auth              1.18.0
google-auth-oauthlib     0.4.1
google-pasta             0.2.0
grpcio                   1.30.0
h5py                     2.10.0
idna                     2.9
Keras-Preprocessing      1.1.2
Markdown                 3.2.2
numpy                    1.19.0
oauthlib                 3.1.0
opt-einsum               3.2.1
pip                      19.2.3
protobuf                 3.12.2
pyasn1                   0.4.8
pyasn1-modules           0.2.8
requests                 2.24.0
requests-oauthlib        1.3.0
rsa                      4.6
scipy                    1.4.1
setuptools               41.2.0
six                      1.15.0
tensorboard              2.2.2
tensorboard-plugin-wit   1.6.0.post3
tensorflow-gpu           2.2.0
tensorflow-gpu-estimator 2.2.0
termcolor                1.1.0
urllib3                  1.25.9
Werkzeug                 1.0.1
wheel                    0.34.2
wrapt                    1.12.1
_______________________________________________________________________________________________________________________

the output of pip debug --verbose:
_______________________________________________________________________________________________________________________

pip version: pip 19.2.3 from c:\users\ghassen\downloads\lisadetection\lisadetection\venv2\lib\site-packages\pip (python 3.8)
sys.version: 3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:37:02) [MSC v.1924 64 bit (AMD64)]
sys.executable: c:\users\ghassen\downloads\lisadetection\lisadetection\venv2\scripts\python.exe
sys.getdefaultencoding: utf-8
sys.getfilesystemencoding: utf-8
locale.getpreferredencoding: cp1252
sys.platform: win32
sys.implementation:
  name: cpython
Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
Compatible tags: 15
  cp38-cp38-win_amd64
  cp38-none-win_amd64
  py3-none-win_amd64
  cp38-none-any
  cp3-none-any
  py38-none-any
  py3-none-any
  py37-none-any
  py36-none-any
  py35-none-any
  py34-none-any
  py33-none-any
  py32-none-any
  py31-none-any
  py30-none-any
_______________________________________________________________________________________________________________________
the code that  produce that:
`import tensorflow as tf`

this is the output:
_______________________________________________________________________________________________________________________

2020-06-24 14:50:11.230153: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-06-24 14:50:11.236957: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
_______________________________________________________________________________________________________________________

and for this code:
`tf.test.is_gpu_available()`

this is the output:
_______________________________________________________________________________________________________________________

WARNING:tensorflow:From <stdin>:1: is_gpu_available (from tensorflow.python.framework.test_util) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.
2020-06-24 14:51:00.146205: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2020-06-24 14:51:00.171655: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x21868deee70 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-06-24 14:51:00.182635: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-06-24 14:51:00.190956: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2020-06-24 14:51:01.031439: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: GeForce GTX 960M computeCapability: 5.0
coreClock: 1.176GHz coreCount: 5 deviceMemorySize: 4.00GiB deviceMemoryBandwidth: 74.65GiB/s
2020-06-24 14:51:01.045344: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-06-24 14:51:01.051842: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cublas64_10.dll'; dlerror: cublas64_10.dll not found
2020-06-24 14:51:01.058515: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cufft64_10.dll'; dlerror: cufft64_10.dll not found
2020-06-24 14:51:01.065241: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'curand64_10.dll'; dlerror: curand64_10.dll not found
2020-06-24 14:51:01.072266: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cusolver64_10.dll'; dlerror: cusolver64_10.dll not found
2020-06-24 14:51:01.080353: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cusparse64_10.dll'; dlerror: cusparse64_10.dll not found
2020-06-24 14:51:01.087954: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudnn64_7.dll'; dlerror: cudnn64_7.dll not found
2020-06-24 14:51:01.095638: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1598] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2020-06-24 14:51:01.186835: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-06-24 14:51:01.194906: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      0
2020-06-24 14:51:01.198498: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 0:   N
2020-06-24 14:51:01.206694: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x21876e35be0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-06-24 14:51:01.214517: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce GTX 960M, Compute Capability 5.0
False
_______________________________________________________________________________________________________________________

**Comment by mihaimaruseac** [comment]
@GhassenBenMakhlouf I don't see the `AttributeError: module 'tensorboard' has no attribute 'lazy'` error in your post. All I see are warning and information logs, not errors. The other log messages can be safely ignored, they are there to provide you with context about what is happening and to help debugging.

**Comment by GhassenBenMakhlouf** [comment]
@mihaimaruseac the problem is that I can not use GPU because this error: Could not load dynamic library 'cudart64_101.dll' 

I know it is an information log or warning because the program can still use the CPU.
But I want to use GPU, please help me solve this issue. please refer me to another issue if you have the solution somewhere.

**Comment by mihaimaruseac** [comment]
That is not the same problem and it should actually be opened as a new issue. Let's keep this issue to the `AttributeError: module 'tensorboard' has no attribute 'lazy'` error

**Comment by GhassenBenMakhlouf** [comment]
> That is not the same problem and it should actually be opened as a new issue. Let's keep this issue to the `AttributeError: module 'tensorboard' has no attribute 'lazy'` error
here you are:
https://github.com/tensorflow/tensorflow/issues/40804

**Comment by ymodak** [comment]
For more context please refer [comment](https://github.com/tensorflow/tensorboard/issues/1862#issuecomment-782518739)
