### ISSUE TITLE
Cannot build tensorflow from docker image tensorflow/tensorflow:devel-gpu

### ISSUE THREAD

**Issue by lezh** [tensorflow/tensorflow#37523]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**

Base image: [tensorflow/tensorflow:devel-gpu](https://hub.docker.com/layers/tensorflow/tensorflow/devel-gpu/images/sha256-a29a94004f4f9fbf2a3810d4e9fcd2cd4caa5f18c179a7dea7b1b0db6e3fdbde?context=explore)
Image hash: a29a94004f4f9fbf2a3810d4e9fcd2cd4caa5f18c179a7dea7b1b0db6e3fdbde

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version: master
- Python version: v3.6
- Bazel version (if compiling from source): 2.0.0 
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.0 
- GPU model and memory: Tesla V100

**Describe the problem**

Docker image [tensorflow/tensorflow:devel-gpu](https://hub.docker.com/layers/tensorflow/tensorflow/devel-gpu/images/sha256-a29a94004f4f9fbf2a3810d4e9fcd2cd4caa5f18c179a7dea7b1b0db6e3fdbde?context=explore) is expected to provide a reliable environment to build tensorflow from source code with bazel. 

However, the bazel build fails in the container from either `docker build` or `docker run`. 

**Provide the exact sequence of commands / steps that you executed before running into the problem**

(1) Make sure the host has nvidia drivers support. 
```
$ nvidia-smi
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.104      Driver Version: 410.104      CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
```
```
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130
```
(2) Download the latest devel-gpu image:
```
$ docker image pull tensorflow/tensorflow:devel-gpu
devel-gpu: Pulling from tensorflow/tensorflow
Digest: sha256:a29a94004f4f9fbf2a3810d4e9fcd2cd4caa5f18c179a7dea7b1b0db6e3fdbde
Status: Image is up to date for tensorflow/tensorflow:devel-gpu
docker.io/tensorflow/tensorflow:devel-gpu
```
(3) Build a new docker image which builds tensorflow
```
$ cat Dockerfile
FROM tensorflow/tensorflow:devel-gpu
WORKDIR /tensorflow_src
RUN bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
```
```
$ docker build .
```

(4) Notice the link error from bazel
```
ImportError: /root/.cache/bazel/_bazel_root/43801f1e35f242fb634ebbc6079cf6c5/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen.runfiles/org_tensorflow/tensorflow/compiler/tf2tensorrt/_pywrap_py_utils.so: undefined symbol: _ZN10tensorflow8internal10LogMessageC1EPKcii
Target //tensorflow/tools/pip_package:build_pip_package failed to build
```
Full error log could be found at the end. 

(5) Alternative: build from docker container
Instead of running `docker build`, this error can be reproducible from `docker run` and `bazel build` from the container as well.

```
$ docker run -it tensorflow/tensorflow:devel-gpu bash
#  bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
```

(6) Alternative: other devel-gpu images
This error is reproducible to other images from the past week.  

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

```
RROR: /tensorflow_src/tensorflow/python/keras/api/BUILD:103:1: Executing genrule //tensorflow/python/keras/api:keras_python_api_gen failed (Exit 1)
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/43801f1e35f242fb634ebbc6079cf6c5/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen.runfiles/org_tensorflow/tensorflow/python/tools/api/generator/create_python_api.py", line 776, in <module>
    main()
  File "/root/.cache/bazel/_bazel_root/43801f1e35f242fb634ebbc6079cf6c5/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen.runfiles/org_tensorflow/tensorflow/python/tools/api/generator/create_python_api.py", line 772, in main
    lazy_loading, args.use_relative_imports)
  File "/root/.cache/bazel/_bazel_root/43801f1e35f242fb634ebbc6079cf6c5/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen.runfiles/org_tensorflow/tensorflow/python/tools/api/generator/create_python_api.py", line 629, in create_api_files
    compat_api_versions, lazy_loading, use_relative_imports)
  File "/root/.cache/bazel/_bazel_root/43801f1e35f242fb634ebbc6079cf6c5/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen.runfiles/org_tensorflow/tensorflow/python/tools/api/generator/create_python_api.py", line 503, in get_api_init_text
    _, attr = tf_decorator.unwrap(attr)
  File "/root/.cache/bazel/_bazel_root/43801f1e35f242fb634ebbc6079cf6c5/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen.runfiles/org_tensorflow/tensorflow/python/util/tf_decorator.py", line 219, in unwrap
    elif _has_tf_decorator_attr(cur):
  File "/root/.cache/bazel/_bazel_root/43801f1e35f242fb634ebbc6079cf6c5/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen.runfiles/org_tensorflow/tensorflow/python/util/tf_decorator.py", line 124, in _has_tf_decorator_attr
    hasattr(obj, '_tf_decorator') and
  File "/root/.cache/bazel/_bazel_root/43801f1e35f242fb634ebbc6079cf6c5/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen.runfiles/org_tensorflow/tensorflow/python/util/lazy_loader.py", line 62, in __getattr__
    module = self._load()
  File "/root/.cache/bazel/_bazel_root/43801f1e35f242fb634ebbc6079cf6c5/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen.runfiles/org_tensorflow/tensorflow/python/util/lazy_loader.py", line 45, in _load
    module = importlib.import_module(self.__name__)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: /root/.cache/bazel/_bazel_root/43801f1e35f242fb634ebbc6079cf6c5/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen.runfiles/org_tensorflow/tensorflow/compiler/tf2tensorrt/_pywrap_py_utils.so: undefined symbol: _ZN10tensorflow8internal10LogMessageC1EPKcii
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /tensorflow_src/tensorflow/tools/pip_package/BUILD:62:1 Executing genrule //tensorflow/python/keras/api:keras_python_api_gen failed (Exit 1)
INFO: Elapsed time: 1622.950s, Critical Path: 719.42s
INFO: 19283 processes: 19283 local.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
```

**Comment by freedomtan** [comment]
it seems some dependency is missed.

```diff
diff --git a/tensorflow/compiler/tf2tensorrt/BUILD b/tensorflow/compiler/tf2tensorrt/BUILD
index 9da873a..371a580 100644
--- a/tensorflow/compiler/tf2tensorrt/BUILD
+++ b/tensorflow/compiler/tf2tensorrt/BUILD
@@ -560,6 +560,9 @@ pybind_extension(
     module_name = "_pywrap_py_utils",
     deps = [
         ":py_utils",
+        "//tensorflow/core/platform:env",
+        "//tensorflow/core/platform:logging",
+        "//tensorflow/core/platform:status",
         "@pybind11",
     ],
 )

```

**Comment by sshrdp** [comment]
Is building from -devel docker image supported workflow? It seems important enough for developer productivity to deserve an integration test.

**Comment by Saduf2019** [comment]
@freedomtan 
As there is a pr to monitor this issue, please confirm if  we may move this issue to closed status.

**Comment by freedomtan** [comment]
@Saduf2019 you should @lezh who opened this issue, not me :)
