### ISSUE TITLE
When using MirroredStrategy, the training process is stuck

### ISSUE THREAD

**Issue by FLming** [tensorflow/tensorflow#37561]
**System information** 
- OS Platform and Distribution: Ubuntu 18.04
- Python version: 3.6.9
- CUDA/cuDNN version: 2x1080 Ti
- Tensorflow version: 2.2.0

**Describe the current behavior**
I built a CRNN model for recognize the text, a CNN-RNN-CTC model, it work well without tf.distribute.Strategy, but when I follow the guide to move the creation and compiling of Keras model inside strategy.scope, It does not start distributed training like the guide. here is the output:
```
2020-03-13 06:19:04.839700: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-03-13 06:19:04.874256: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce GTX 1080 Ti computeCapability: 6.1
coreClock: 1.582GHz coreCount: 28 deviceMemorySize: 10.91GiB deviceMemoryBandwidth: 451.17GiB/s
2020-03-13 06:19:04.875077: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 1 with properties: 
pciBusID: 0000:02:00.0 name: GeForce GTX 1080 Ti computeCapability: 6.1
coreClock: 1.582GHz coreCount: 28 deviceMemorySize: 10.92GiB deviceMemoryBandwidth: 451.17GiB/s
2020-03-13 06:19:04.875273: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-03-13 06:19:04.876811: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-03-13 06:19:04.878155: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-03-13 06:19:04.878383: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-03-13 06:19:04.879998: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-03-13 06:19:04.881014: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-03-13 06:19:04.884664: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-03-13 06:19:04.887439: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0, 1
2020-03-13 06:19:04.887722: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-03-13 06:19:04.892905: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 3598110000 Hz
2020-03-13 06:19:04.893743: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7f1224000b20 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-03-13 06:19:04.893784: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-03-13 06:19:05.147750: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x59b91e0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-03-13 06:19:05.147778: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce GTX 1080 Ti, Compute Capability 6.1
2020-03-13 06:19:05.147788: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (1): GeForce GTX 1080 Ti, Compute Capability 6.1
2020-03-13 06:19:05.150073: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce GTX 1080 Ti computeCapability: 6.1
coreClock: 1.582GHz coreCount: 28 deviceMemorySize: 10.91GiB deviceMemoryBandwidth: 451.17GiB/s
2020-03-13 06:19:05.150888: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 1 with properties: 
pciBusID: 0000:02:00.0 name: GeForce GTX 1080 Ti computeCapability: 6.1
coreClock: 1.582GHz coreCount: 28 deviceMemorySize: 10.92GiB deviceMemoryBandwidth: 451.17GiB/s
2020-03-13 06:19:05.150926: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-03-13 06:19:05.150943: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-03-13 06:19:05.150958: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-03-13 06:19:05.150972: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-03-13 06:19:05.150986: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-03-13 06:19:05.151000: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-03-13 06:19:05.151015: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-03-13 06:19:05.154118: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0, 1
2020-03-13 06:19:05.154160: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-03-13 06:19:05.156174: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-03-13 06:19:05.156195: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      0 1 
2020-03-13 06:19:05.156206: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 0:   N Y 
2020-03-13 06:19:05.156214: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 1:   Y N 
2020-03-13 06:19:05.158304: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 9569 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
2020-03-13 06:19:05.159295: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 10369 MB memory) -> physical GPU (device: 1, name: GeForce GTX 1080 Ti, pci bus id: 0000:02:00.0, compute capability: 6.1)
Epoch 1/5
```
The training process seems to be interrupted without any output, but the program runs out of graphics card memory and the program does not exit.

**Describe the expected behavior**
Start training just like without distributed strategy.

**Standalone code to reproduce the issue** 
The full code can be view [here](https://github.com/FLming/CRNN.tf2)

**Comment by crccw** [comment]
Could you try tf.experimental.output_all_intermediates(True)?

It would be also easier if you can provide a smaller reproduction.

**Comment by FLming** [comment]
The code is available in [CRNN.tf2](https://github.com/FLming/CRNN.tf2), To reproduce this error, clone it, add MirroredStrategy, then run it with example data by:
```bash
python train.py -ta example/annotation.txt -tf example -va example/annotation.txt -vf example -t example/table.txt
```
The error after add tf.compat.v1.experimental.output_all_intermediates(True):
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py", line 470, in _apply_op_helper
    preferred_dtype=default_dtype)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 1317, in convert_to_tensor
    (dtype.name, value.dtype.name, value))
ValueError: Tensor conversion requested dtype float32 for Tensor with dtype resource: <tf.Tensor 'Identity/ReadVariableOp/resource:0' shape=() dtype=resource>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 61, in <module>
    model = crnn(train_dl.num_classes)
  File "/workspace/model.py", line 152, in crnn
    x = original(img_input)
  File "/workspace/model.py", line 37, in original
    x = layers.BatchNormalization()(x)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 921, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/layers/normalization.py", line 735, in call
    outputs = self._fused_batch_norm(inputs, training=training)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/layers/normalization.py", line 598, in _fused_batch_norm
    _fused_batch_norm_inference)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/utils/tf_utils.py", line 65, in smart_cond
    pred, true_fn=true_fn, false_fn=false_fn, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/smart_cond.py", line 59, in smart_cond
    name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 1177, in cond
    return cond_v2.cond_v2(pred, true_fn, false_fn, name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/cond_v2.py", line 101, in cond_v2
    name=scope)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/cond_v2.py", line 235, in _build_cond
    true_intermediates = _get_intermediates(true_graph)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/cond_v2.py", line 443, in _get_intermediates
    if t in func_graph.inputs: continue
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/math_ops.py", line 1491, in tensor_equals
    return gen_math_ops.equal(self, other, incompatible_shape_error=False)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_math_ops.py", line 3224, in equal
    name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py", line 506, in _apply_op_helper
    inferred_from[input_arg.type_attr]))
TypeError: Input 'y' of 'Equal' Op has type resource that does not match type float32 of argument 'x'.
```
Is batch normalization not available in distributed training?

**Comment by FLming** [comment]
For me, this issue is because I forgot to add drop_remainder=True in Dataset.batch function.

**Comment by FLming** [comment]
This problem still exists, I can't find a way to solve it. There are no errors, and the GPU is not calculating, but it takes up GPU memory.

**Comment by jvishnuvardhan** [comment]
@FLming Can you please try adding `steps_per_epoch` and `validation_steps` to `model.fit` and then test whether the error persists or not? Thanks!

**Comment by FLming** [comment]
I set `steps_per_epoch` to `number of training samples // batch size` and `validation_steps` to `number of val samples // batch size`, the problem still exists.

**Comment by FLming** [comment]
One more thing, although it’s a digression. Once I used DepthwiseConv2D to build the model, the same thing happened, there was no progress bar, no error, and the output was only 
```
...
Epoch 1/x
```
By chance I switched the program from GPU to CPU, the error raised, that said `current implementation only supports equal length strides in the row and column dimensions`. Follow this tip, the program worked on GPU.
Will tensorflow lose some output prompts when running on the GPU?

**Comment by jvishnuvardhan** [comment]
@FLming Code that is running on CPU and GPU are similar but they are little different from implementation side so that the GPU accelerators are optimally used.  

If this is resolved for you, then please close the issue. Thanks!

**Comment by FLming** [comment]
@jvishnuvardhan No, the problem still exists. The above is another problem that `DepthwiseConv2D` is't support different stride setting, and on GPU, the prompt doesn't appear.

**Comment by FLming** [comment]
Things have progressed. I removed custom `Metric` class in model.fit, the distributed training works normally, but why? Here is the definition
```
class WordAccuracy(keras.metrics.Metric):
    """
    Calculate the word accuracy between y_true and y_pred.
    """
    def __init__(self, name='word_accuracy', **kwargs):
        super().__init__(name=name, **kwargs)
        self.total = self.add_weight(name='total', dtype=tf.int32, 
                                     initializer=tf.zeros_initializer())
        self.count = self.add_weight(name='count', dtype=tf.int32, 
                                     initializer=tf.zeros_initializer())
                
    def update_state(self, y_true, y_pred, sample_weight=None):
        """
        Maybe have more fast implementation.
        """
        b = tf.shape(y_true)[0]
        max_width = tf.maximum(tf.shape(y_true)[1], tf.shape(y_pred)[1])
        logit_length = tf.fill([tf.shape(y_pred)[0]], tf.shape(y_pred)[1])        
        decoded, _ = tf.nn.ctc_greedy_decoder(
            inputs=tf.transpose(y_pred, perm=[1, 0, 2]),
            sequence_length=logit_length)
        y_true = tf.sparse.reset_shape(y_true, [b, max_width])
        y_pred = tf.sparse.reset_shape(decoded[0], [b, max_width])
        y_true = tf.sparse.to_dense(y_true, default_value=-1)
        y_pred = tf.sparse.to_dense(y_pred, default_value=-1)
        y_true = tf.cast(y_true, tf.int32)
        y_pred = tf.cast(y_pred, tf.int32)
        values = tf.math.reduce_any(tf.math.not_equal(y_true, y_pred), axis=1)
        values = tf.cast(values, tf.int32)
        values = tf.reduce_sum(values)
        self.total.assign_add(b)
        self.count.assign_add(b - values)

    def result(self):
        return self.count / self.total

    def reset_states(self):
        self.count.assign(0)
        self.total.assign(0)
```

**Comment by FLming** [comment]
I found the reason, that is because I use dtype=tf.int32 in self.add_weight function.

**Comment by boggis30** [comment]
> I found the reason, that is because I use dtype=tf.int32 in self.add_weight function.
@FLming can you please share your experience how you found the root cause?

**Comment by FLming** [comment]
Comment and run, step by step, narrow the scope.

**Comment by dtlam26** [comment]
Just a little sharing about this incident. Most of the problem take place by the loss and metric after running a step.
Make sure custom loss match this requirement for 2.x version:
`If using tf.keras.losses classes (as in the example below), the loss reduction needs to be explicitly specified to be one of NONE or SUM. AUTO and SUM_OVER_BATCH_SIZE are disallowed when used with tf.distribute.Strategy. AUTO is disallowed because the user should explicitly think about what reduction they want to make sure it is correct in the distributed case. SUM_OVER_BATCH_SIZE is disallowed because currently it would only divide by per replica batch size, and leave the dividing by number of replicas to the user, which might be easy to miss. So instead we ask the user do the reduction themselves explicitly.`
