### ISSUE TITLE
How to use our own tflite model ?

### ISSUE THREAD

**Issue by RomitGandhi07** [tensorflow/tensorflow#37613]
This template is for miscellaneous issues not covered by the other issue categories.

For questions on how to work with TensorFlow, or support for problems that are not verified bugs in TensorFlow, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).

If you are reporting a vulnerability, please use the [dedicated reporting process](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md).

For high-level discussions about TensorFlow, please post to discuss@tensorflow.org, for questions about the development or internal workings of TensorFlow, or if you would like to know how to contribute to TensorFlow, please post to developers@tensorflow.org.

**Comment by amahendrakar** [comment]
@RomitGandhi07,
Could you please elaborate your query? Do you need help building the tflite model or implementing it on your mobile device?

Also, while submitting your query, please fill in the issue template along with the TensorFlow version you are using. Thanks!

**Comment by RomitGandhi07** [comment]
Hello sir, 
I have retrained my model and generated .lite file. Now, I want to use it in the android application, So I put the .lite file and labels.txt file in asset folder and change the file name in the java file as well but whenever I run my app the model associated with the app is detecting the objects. So, please tell me how to use the .lite model in the android app. Thanks for helping.

**Comment by amahendrakar** [comment]
Could you please check out [this](https://www.tensorflow.org/lite/guide/android) quick start guide for Android and let us know if it helps? Thanks!

**Comment by RomitGandhi07** [comment]
I have used the same example but for the defined model, it is working perfectly, I want to use my own model and for that, I uploaded my zip file contains .lite & label file on Google Drive and share it publicly and specify that link in download.gradle file but when I run the app the error showing that .lite file not found.

In download.gradle file:   src 'https://drive.google.com/file/d/1h0ugvgkmLRdeSvV-cugYHIGAVi5zs6tt/view?usp=sharing', this is the link provided

![Error](https://user-images.githubusercontent.com/46276226/76766005-56258200-67bd-11ea-9a6d-2299f20d14f0.jpg)

**Comment by jvishnuvardhan** [comment]
@RomitGandhi07 Are you trying classification or object detection. If you want to classify those three classes, you can use classification model described [here](https://codelabs.developers.google.com/codelabs/recognize-flowers-with-tensorflow-on-android/#1).  If you are trying to develop object detection model, then please check this [resource](https://codelabs.developers.google.com/codelabs/mlkit-android-custom-model/#0). These two tutorials will give you more detailed instructions on building your own tflite model and deploy on Android. 

Please close the issue if this was resolved for you. Thanks!

**Comment by dsblind** [comment]
Hi, I'm also experiencing difficulties with running my own tflite model - please see details [here](https://stackoverflow.com/questions/60758929/trying-to-load-a-tflite-model-fails-with-java-io-filenotfoundexception-what-am)

**Comment by jvishnuvardhan** [comment]
@RomitGandhi07 I tried your files in object_detection tflite_model. I am getting different error when I used `quantization = True` by using this command `TF_OD_API_IS_QUANTIZED = true;`. The following is the error trace.

```
2020-03-25 18:57:08.025 10944-10944/? W/main: type=1400 audit(0.0:17): avc: granted { read } for name="u:object_r:net_dns_prop:s0" dev="tmpfs" ino=14616 scontext=u:r:untrusted_app_25:s0:c512,c768 tcontext=u:object_r:net_dns_prop:s0 tclass=file
2020-03-25 18:57:08.031 10944-10944/? I/mples.detectio: Late-enabling -Xcheck:jni
2020-03-25 18:57:08.077 10944-10944/? E/mples.detectio: Unknown bits set in runtime_flags: 0x8000
2020-03-25 18:57:08.133 10944-10944/? I/mples.detectio: The ClassLoaderContext is a special shared library.
2020-03-25 18:57:08.286 10944-10944/? D/tensorflow: CameraActivity: onCreate org.tensorflow.lite.examples.detection.DetectorActivity@8b487a
2020-03-25 18:57:08.340 10944-10944/? W/mples.detectio: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (greylist, reflection, allowed)
2020-03-25 18:57:08.341 10944-10944/? W/mples.detectio: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
2020-03-25 18:57:08.445 10944-10944/? I/CameraManagerGlobal: Connecting to camera service
2020-03-25 18:57:08.458 10944-10944/? I/tensorflow: CameraActivity: Camera API lv2?: true
2020-03-25 18:57:08.479 10944-10944/? D/tensorflow: CameraActivity: onStart org.tensorflow.lite.examples.detection.DetectorActivity@8b487a
2020-03-25 18:57:08.481 10944-10944/? D/tensorflow: CameraActivity: onResume org.tensorflow.lite.examples.detection.DetectorActivity@8b487a
2020-03-25 18:57:08.527 10944-10980/? I/Adreno: QUALCOMM build                   : 4a00b69, I4e7e888065
    Build Date                       : 04/09/19
    OpenGL ES Shader Compiler Version: EV031.26.06.00
    Local Branch                     : mybranche95ae4c8-d77f-f18d-a9ef-1458d0b52ae8
    Remote Branch                    : quic/gfx-adreno.lnx.1.0
    Remote Branch                    : NONE
    Reconstruct Branch               : NOTHING
2020-03-25 18:57:08.527 10944-10980/? I/Adreno: Build Config                     : S L 8.0.5 AArch64
2020-03-25 18:57:08.530 10944-10980/? I/Adreno: PFP: 0x005ff110, ME: 0x005ff066
2020-03-25 18:57:08.556 10944-10944/? I/tensorflow: CameraConnectionFragment: Desired size: 640x480, min size: 480x480
2020-03-25 18:57:08.556 10944-10944/? I/tensorflow: CameraConnectionFragment: Valid preview sizes: [4048x3036, 4000x3000, 3840x2160, 3264x2448, 3200x2400, 2976x2976, 2592x1944, 2688x1512, 2048x1536, 1920x1080, 1600x1200, 1440x1080, 1280x960, 1280x720, 1024x768, 800x600, 720x480, 640x480]
2020-03-25 18:57:08.556 10944-10944/? I/tensorflow: CameraConnectionFragment: Rejected preview sizes: [640x360, 480x360, 480x320, 352x288, 320x240, 176x144, 160x120]
2020-03-25 18:57:08.556 10944-10944/? I/tensorflow: CameraConnectionFragment: Exact size match found.
2020-03-25 18:57:08.561 10944-10944/? W/tensorflow: TFLiteObjectDetectionAPIModel: lunchbox
2020-03-25 18:57:08.561 10944-10944/? W/tensorflow: TFLiteObjectDetectionAPIModel: mouse
2020-03-25 18:57:08.562 10944-10944/? W/tensorflow: TFLiteObjectDetectionAPIModel: breadboard
2020-03-25 18:57:08.566 10944-10944/? I/tflite: Initialized TensorFlow Lite runtime.
2020-03-25 18:57:08.568 10944-10944/? I/tensorflow: DetectorActivity: Camera orientation relative to screen canvas: 90
2020-03-25 18:57:08.568 10944-10944/? I/tensorflow: DetectorActivity: Initializing at size 640x480
2020-03-25 18:57:08.608 10944-10984/? I/tensorflow: CameraConnectionFragment: Opening camera preview: 640x480
2020-03-25 18:57:08.618 10944-10980/? W/Gralloc3: mapper 3.x is not supported
2020-03-25 18:57:08.728 10944-10968/? W/Gralloc3: allocator 3.x is not supported
2020-03-25 18:57:08.927 10944-10984/? D/tensorflow: CameraActivity: Initializing buffer 0 at size 307200
2020-03-25 18:57:08.927 10944-10984/? D/tensorflow: CameraActivity: Initializing buffer 1 at size 153599
2020-03-25 18:57:08.928 10944-10984/? D/tensorflow: CameraActivity: Initializing buffer 2 at size 153599
2020-03-25 18:57:08.928 10944-10984/? I/tensorflow: DetectorActivity: Preparing image 1 for detection in bg thread.
2020-03-25 18:57:08.955 10944-10983/? I/tensorflow: DetectorActivity: Running detection on image 1
2020-03-25 18:57:08.990 10944-10983/? E/AndroidRuntime: FATAL EXCEPTION: inference
    Process: org.tensorflow.lite.examples.detection, PID: 10944
    java.lang.IllegalArgumentException: Cannot convert between a TensorFlowLite buffer with 602112 bytes and a Java Buffer with 1080000 bytes.
        at org.tensorflow.lite.Tensor.throwIfShapeIsIncompatible(Tensor.java:402)
        at org.tensorflow.lite.Tensor.throwIfDataIsIncompatible(Tensor.java:369)
        at org.tensorflow.lite.Tensor.setTo(Tensor.java:187)
        at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:150)
        at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:314)
        at org.tensorflow.lite.examples.detection.tflite.TFLiteObjectDetectionAPIModel.recognizeImage(TFLiteObjectDetectionAPIModel.java:193)
        at org.tensorflow.lite.examples.detection.DetectorActivity$2.run(DetectorActivity.java:181)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)
```

As I am not sure about your model whether it is quantized or not, so I changed the option to `quantization = false`. Then I got much smaller error trace as follows.

```
2020-03-25 18:57:09.181 10944-10944/org.tensorflow.lite.examples.detection D/tensorflow: CameraActivity: onPause org.tensorflow.lite.examples.detection.DetectorActivity@8b487a
2020-03-25 18:57:10.096 10944-10959/org.tensorflow.lite.examples.detection W/System: A resource failed to call close. 
2020-03-25 18:57:10.096 10944-10959/org.tensorflow.lite.examples.detection W/System: A resource failed to call close. 
```

Questions to you.
1) Did you copy the tflite model and label.txt to the asset folder?
2) did you quantize the model? Pre or post training quantization? Thanks!

**Comment by RomitGandhi07** [comment]
Yes, I copied tflite model and label.txt in the asset folder and I quantized the model by converting to model to tflite model.

I'm sending you the zip file which contains .lite file and .txt file, it also has .pb file. So can you try this? 



[Tensorflow Lite Retrained Model.zip](https://github.com/tensorflow/tensorflow/files/4384949/Tensorflow.Lite.Retrained.Model.zip)

**Comment by jvishnuvardhan** [comment]
@RomitGandhi07 Did you disabling the model downloading part from build.gradle by commenting `apply from:'download_model.gradle` as `// apply from:'download_model.gradle`. I will also point you to good instructions [here](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_on_mobile_tensorflowlite.md). Try to follow and update your codes so that there is no `FileNotFoundError`.  Lets try it and see whether you can resolve. We will spend some time to resolve if there are any more updates we need to do. Thanks!

**Comment by RomitGandhi07** [comment]
Ok, I am trying it.

**Comment by RomitGandhi07** [comment]
Can you please tell me which example are you working on because in my example in build.gradle I haven't found to apply from:'download_model.gradle.
Can you please share the link from where you download the example?
Thanks in advance.

**Comment by RomitGandhi07** [comment]
Ok Found it, I'm trying now whether its working or not

**Comment by jvishnuvardhan** [comment]
@RomitGandhi07 You need to clone this [repo](git clone https://github.com/tensorflow/examples). Complete instructions are [here](https://github.com/tensorflow/examples/tree/master/lite/examples/image_classification/android). Thanks!

**Comment by RomitGandhi07** [comment]
So, simply I have to disable apply line from build.gradle and put my own .lite model and label file in the asset folder.
and please can you tell me in which java file in this example I have to change the file name of model and label ?

**Comment by jvishnuvardhan** [comment]
@RomitGandhi07 `DetectorActivity.java` is the file name where you need to change. Instructions are there in the doc I shared. Thanks!

**Comment by RomitGandhi07** [comment]
I had done the same steps, now I neither getting any error nor object is detected. Can you help me to find out why it's happened?

I'm attaching zip file which contains .lite model file, label file and .pb file.

[assets.zip](https://github.com/tensorflow/tensorflow/files/4389199/assets.zip)

**Comment by jvishnuvardhan** [comment]
@RomitGandhi07 Can you please post the complete log you are noticing in the android studio? Is this model crashing in monile? Thanks!

**Comment by RomitGandhi07** [comment]
Sorry for the delayed response, no model is not crashing in the device, I have tested the .pb file in google colab it is perfectly detecting the object (Means gives perfect probability value), so after that, I convert that into .lite file but when I use it in the android app it isn't detecting the object.

**Comment by jvishnuvardhan** [comment]
@RomitGandhi07 Is this still an issue? Can you share the colab where it is perfectly detecting? how many images per category you have used? what is the accuracy you are getting with the colab. Thanks!

If this was resolved for you, please feel free to close the issue. Thanks!

**Comment by jvishnuvardhan** [comment]
@RomitGandhi07 I found that you saved your model to `graph.lite`. Can you please change that to  `graph.tflite` and check the classification? Your tflite model extension was not correct. After changing that extension, I tested on my phone. It was detecting `lunchbox` with 99.96% accuracy. Here is an image for you.

I am closing this issue as this was resolved for you. Thanks!
![tflite_lunchbox_detection](https://user-images.githubusercontent.com/46058173/81326592-ea3df800-904e-11ea-837a-0043d4f247df.jpg)
