### ISSUE TITLE
Sparce Tensor wrong exeption Message when passing argument with wrong Type

### ISSUE THREAD

**Issue by bela127** [tensorflow/tensorflow#37640]
System information

    Have I written custom code (as opposed to using a stock
    example script provided in TensorFlow): No
    OS Platform and Distribution (e.g.,
    Linux Ubuntu 16.04): Linux Mint 19.3 (ubuntu)
    TensorFlow installed from (source or
    binary): binatry
    TensorFlow version (use command below): both tf-nightly and tf-2.1
    Python version: 3.8 and 3.6

**Describe the current behavior**
when passing an int32 tensor to Sparce Tensor
last Error displayed is:
```
ValueError: Unable to create eager SparseTensor. Check that your shape is correctly defined. Eager SparseTensors don't support unknown dimesions.
got shape:
    [4 4 4 4]
```
when looking back in stack trace, the right error is raced:

`ValueError: Tensor conversion requested dtype int64 for Tensor with dtype int32: <tf.Tensor: shape=(4,), dtype=int32, numpy=array([4, 4, 4, 4], dtype=int32)>`

**Describe the expected behavior**
one of the following:
1) conversion should not fail
2) last Error should be:
expected int64 tensor for shape argument got int32 tensor

**Standalone code to reproduce the issue** 
```
import tensorflow as tf

indices = tf.cast([[1,1,1,1],[1,3,1,1]],dtype=tf.int64)
shape = tf.cast([4,4,4,4],dtype=tf.int64)

heat_map = tf.SparseTensor(indices = indices, values = tf.ones(tf.shape(indices)[0]), dense_shape = shape)

indices = tf.cast([[1,1,1,1],[1,3,1,1]],dtype=tf.int64)
shape = tf.cast([4,4,4,4],dtype=tf.int32)

heat_map = tf.SparseTensor(indices = indices, values = tf.ones(tf.shape(indices)[0]), dense_shape = shape)
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

```
Traceback (most recent call last):
  File "/home/bhb/Cloud/Code/Git/3D_Person_Pose_Estimation_from_2D_Singelview_Image_Data/src/venv/lib/python3.6/site-packages/tensorflow/python/framework/sparse_tensor.py", line 142, in __init__
    dense_shape, name="dense_shape", dtype=dtypes.int64)
  File "/home/bhb/Cloud/Code/Git/3D_Person_Pose_Estimation_from_2D_Singelview_Image_Data/src/venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1317, in convert_to_tensor
    (dtype.name, value.dtype.name, value))
ValueError: Tensor conversion requested dtype int64 for Tensor with dtype int32: <tf.Tensor: shape=(4,), dtype=int32, numpy=array([4, 4, 4, 4], dtype=int32)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bhb/.vscode/extensions/ms-python.python-2020.2.64397/pythonFiles/ptvsd_launcher.py", line 48, in <module>
    main(ptvsdArgs)
  File "/home/bhb/.vscode/extensions/ms-python.python-2020.2.64397/pythonFiles/lib/python/old_ptvsd/ptvsd/__main__.py", line 432, in main
    run()
  File "/home/bhb/.vscode/extensions/ms-python.python-2020.2.64397/pythonFiles/lib/python/old_ptvsd/ptvsd/__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "/usr/lib/python3.6/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/usr/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/bhb/Cloud/Code/Git/3D_Person_Pose_Estimation_from_2D_Singelview_Image_Data/src/test_sparce_tensor.py", line 11, in <module>
    heat_map = tf.SparseTensor(indices = indices, values = tf.ones(tf.shape(indices)[0]), dense_shape = shape)
  File "/home/bhb/Cloud/Code/Git/3D_Person_Pose_Estimation_from_2D_Singelview_Image_Data/src/venv/lib/python3.6/site-packages/tensorflow/python/framework/sparse_tensor.py", line 148, in __init__
    "got shape:\n    {}".format(dense_shape))
ValueError: Unable to create eager SparseTensor. Check that your shape is correctly defined. Eager SparseTensors don't support unknown dimesions.
got shape:
    [4 4 4 4]
Beendet
```

**Comment by amahendrakar** [comment]
@bela127,
On running the above code with [TF-nightly](https://colab.research.google.com/gist/amahendrakar/d1fd04827fc673713a0b728c20bc15a1/37640-tf-nightly.ipynb), I got an error stating
`ValueError: Unable to create eager SparseTensor. Check that your shape is correctly defined. Eager SparseTensors don't support unknown dimesions.
got shape:
    [4 4 4 4]`

However, with [TF2.1](https://colab.research.google.com/gist/amahendrakar/6bde0978e3a5a9ace8b36a36c40d4432/37640.ipynb), the error states 
`ValueError: Tensor conversion requested dtype int64 for Tensor with dtype int32: <tf.Tensor: shape=(4,), dtype=int32, numpy=array([4, 4, 4, 4], dtype=int32)>`

Is the behavior for 2.1 as expected. Please find the attached gist. Thanks!

**Comment by bela127** [comment]
2.1 behavior seems to be as expected.
So only nightly has the miss leading Message.

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF-2.2-rc0. Please find the gist [here](https://colab.research.google.com/gist/amahendrakar/1161b25237908e9a7d95aec53b2a0eb6/37640-2-2.ipynb). Thanks!

**Comment by rushabh-v** [comment]
I would like to fix this.
will be opening a PR soon.
