### ISSUE TITLE
tf.Keras BatchNormalization layer causing impossible loss/accuracy in GAN training

### ISSUE THREAD

**Issue by ConorLazarou** [tensorflow/tensorflow#37673]
**System information** 
- Have I written custom code: yes
- OS Platform and Distribution: Windows 10, version 1809, os build 17763.1098
- Mobile device if the issue happens on mobile device: N/A
- TensorFlow installed from:  binary
- TensorFlow version: 2.0.0
- Python version: Python 3.7.6
- Bazel version: N/A
- GCC/Compiler version: N/A
- CUDA/cuDNN version: 10.1, V10.1.105
- GPU model and memory: GeForce RTX 2080 Ti, 11GB

I've been getting unusual losses and accuracies when training GANs with batch normalization layers in the discriminator using tf.keras. GANs have an optimal objective function value of log(4), which occurs when the discriminator is completely unable to discern real samples from fakes and hence predicts 0.5 for all samples. When I include BatchNormalization layers in my discriminator, both the generator and the discriminator achieve near perfect scores (high accuracy, low loss), which is impossible in an adversarial setting.

Without BatchNorm:
[This figure](https://i.stack.imgur.com/4F7l8.png) shows the losses (y) per epoch (x) when BN is not used. Note that occasional values below the theoretical minimum are due to the training being an iterative process. [This figure](https://i.stack.imgur.com/YGGCt.png) shows the accuracies when BN is not used, which settle at about 50% each. Both of these figures show reasonable values.

With BatchNorm:
[This figure](https://i.stack.imgur.com/HRzyc.png) shows the losses (y) per epoch (x) when BN is used. See how the GAN objective, which shouldn't fall below log(4), approaches 0. [This figure](https://i.stack.imgur.com/jS5XN.png) shows the accuracies when BN is used, with both approaching 100%. GANs are adversarial; the generator and discriminator can't both have 100% accuracy.

I suspect this has something to do with setting `model.trainable = False`.

Standalone code to reproduce and visualize can be found [here](https://gist.github.com/ConorLazarou/584af3f87a9a14503b9714580c567dab).

**Comment by gadagashwini** [comment]
@ConorLazarou, Will it be possible to provide the sample code snippet. Thanks!

**Comment by HopefulRational** [comment]
hi @ConorLazarou . I haven't looked at your code yet but there is this paper 
TOWARDS PRINCIPLED METHODS FOR TRAINING
GENERATIVE ADVERSARIAL NETWORKS
that talks about discriminator having a theoretically impossible loss. could you please have a look at that... 
thanks.

**Comment by ConorLazarou** [comment]
@gadagashwini here it is
```
import numpy as np
from tensorflow.keras.layers import Input, Dense, BatchNormalization, Activation, LeakyReLU
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam
import tensorflow as tf
import matplotlib.pyplot as plt

def build_G(batchnorm_momentum=0.9):
    input_layer = Input(shape=(2,))
    for i in range(4):
        X = Dense(64)(input_layer)
        X = Activation('relu')(X)
    output_layer = Dense(2)(X)
    model = Model(input_layer, output_layer)
    return model


def build_D(batchnorm_momentum=0.9):
    input_layer = Input(shape=(2,))
    for i in range(4):
        X = Dense(64)(input_layer)
        if batchnorm_momentum:
            X = BatchNormalization(momentum=batchnorm_momentum)(X)
        X = Activation('relu')(X)
    output_layer = Dense(1, activation='sigmoid')(X)
    model = Model(input_layer, output_layer)
    model.compile(Adam(lr=0.001, beta_1=0.5),
                  loss='binary_crossentropy',
                  metrics=['accuracy'],)
    return model


def build_GAN(G, D):
    D.trainable=False
    input_layer = Input(shape=(2,))
    X = G(input_layer)
    output_layer = D(X)
    model = Model(input_layer, output_layer)
    model.compile(Adam(lr=0.0002, beta_1=0.5),
                  loss='binary_crossentropy',
                  metrics=['accuracy'],)
    return model


def get_noise(num):
    return np.random.random((num, 2)) * 2 - 1


def get_samples(num):
    return np.random.normal(0, 1, (num, 2))


BATCHNORM_MOMENTUM = 0.9
# BATCHNORM_MOMENTUM = None
G = build_G()
D = build_D(batchnorm_momentum=BATCHNORM_MOMENTUM)
GAN = build_GAN(G, D)


EPOCHS = 100
BATCH_SIZE = 32
BATCHES_PER_EPOCH = 100
g_loss = []
g_accuracy = []
d_real_loss = []
d_real_accuracy = []
d_fake_loss = []
d_fake_accuracy = []
for epoch in range(EPOCHS):
    g_running_loss = 0
    g_running_accuracy = 0
    d_real_running_loss = 0
    d_real_running_accuracy = 0
    d_fake_running_loss = 0
    d_fake_running_accuracy = 0
    for batch in range(BATCHES_PER_EPOCH):
        real = get_samples(BATCH_SIZE)
        fake = G.predict(get_noise(BATCH_SIZE))
        l, a = D.train_on_batch(real, np.ones((BATCH_SIZE, 1)))
        d_real_running_loss += l
        d_real_running_accuracy += a
        l, a = D.train_on_batch(fake, np.zeros((BATCH_SIZE, 1)))
        d_fake_running_loss += l
        d_fake_running_accuracy += a

        l, a = GAN.train_on_batch(get_noise(BATCH_SIZE), np.ones((BATCH_SIZE, 1)))
        g_running_loss += l
        g_running_accuracy += a

        print(f'Epoch {epoch+1} [{batch+1}/{BATCHES_PER_EPOCH}]: '
              f'G={g_running_loss/(batch+1):.4f} [{g_running_accuracy/(batch+1):.2%}]; '
              f'Dr={d_real_running_loss/(batch+1):.4f} [{d_real_running_accuracy/(batch+1):.2%}]; '
              f'Df={d_fake_running_loss/(batch+1):.4f} [{d_fake_running_accuracy/(batch+1):.2%}]; '
              f'Overall={(g_running_loss + (d_real_running_loss + d_fake_running_loss) / 2) / (batch+1):.4f}',
              end='\r'
              )
    g_loss.append(g_running_loss / BATCHES_PER_EPOCH)
    g_accuracy.append(g_running_accuracy / BATCHES_PER_EPOCH)
    d_real_loss.append(d_real_running_loss / BATCHES_PER_EPOCH)
    d_real_accuracy.append(d_real_running_accuracy / BATCHES_PER_EPOCH)
    d_fake_loss.append(d_fake_running_loss / BATCHES_PER_EPOCH)
    d_fake_accuracy.append(d_fake_running_accuracy / BATCHES_PER_EPOCH)
    print()

g_loss = np.array(g_loss)
d_real_loss = np.array(d_real_loss)
d_fake_loss = np.array(d_fake_loss)
d_loss = (d_real_loss + d_fake_loss) / 2
plt.plot(np.arange(len(g_loss)) + 1, g_loss, label='G Loss')
plt.plot(np.arange(len(d_loss)) + 1, d_loss, label='D Loss')
plt.plot(np.arange(len(d_loss)) + 1, g_loss + d_loss, label='GAN Objective')
plt.plot([1, len(d_loss)], [np.log(4), np.log(4)], label='GAN Objective Theoretical Minimum')
plt.plot([1, len(d_loss)], [np.log(4)/2, np.log(4)/2], label='Equilibrium')
plt.title("With BatchNorm" if BATCHNORM_MOMENTUM else "Without BatchNorm")
plt.legend(loc='lower left')
plt.show()

g_accuracy = np.array(g_accuracy)
d_real_accuracy = np.array(d_real_accuracy)
d_fake_accuracy = np.array(d_fake_accuracy)
d_accuracy = (d_real_accuracy + d_fake_accuracy) / 2
plt.plot(np.arange(len(g_accuracy)) + 1, g_accuracy, label='G accuracy')
plt.plot(np.arange(len(d_accuracy)) + 1, d_accuracy, label='D accuracy')
plt.plot([1, len(d_accuracy)], [1, 1], label='100%')
plt.title("With BatchNorm" if BATCHNORM_MOMENTUM else "Without BatchNorm")
plt.ylim(-0.05, 1.05)
plt.legend(loc='lower left')
plt.show()
```

**Comment by ConorLazarou** [comment]
Hi @HopefulRational ,
I skimmed the paper but I'm not sure I understand what you're referring to. The problem here is that the GAN objective function, `-log(D(x)) - log(1-D(G(z)))` (where the range of D is [0, 1]) has a global minimum of log(4) (when D returns 0.5 for all inputs), but BatchNormalization results in values below much lower than the globabl minimum.

**Comment by HopefulRational** [comment]
@ConorLazarou i was just referring to thing that even in the paper the issue with which the author starts discussion is that discriminator attains a loss far lower than the actual value...  please see the **third page first paragraph**  . so i thought maybe you can try the ideas mentioned in the paper like adding noise (if I remember it well) and tell us what is happening... 
thanks for considering my option... 
and  sorry for the confusion..

**Comment by ConorLazarou** [comment]
Ah yes thanks for pointing that out. Unfortunately, this issue has nothing to do with GAN stability. The issue that Arjovsky and Bottou describe results in the discriminator loss approaching 0 while the generator loss approaches infinity; the issue I'm describing involves the discriminator loss and the generator loss approaching 0, which shouldn't be possible.

**Comment by HopefulRational** [comment]
@ConorLazarou oh yeah.... sorry I missed that.. we having an adversarial setting here. 
so silly of me... ok will look at your code as well as tensorflow bn... 
sorry again... 
thanks for patience...

**Comment by HopefulRational** [comment]
Hi @ConorLazarou . I ran the code as it was given by you. I get this error : 
```
Traceback (most recent call last):
  File "GAN_issue.py", line 93, in <module>
    l, a = GAN.train_on_batch(get_noise(BATCH_SIZE), np.ones((BATCH_SIZE, 1)))
  File "/home/vsairaam/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 1188, in train_on_batch
    outputs = self.train_function(ins)  # pylint: disable=not-callable
  File "/home/vsairaam/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/backend.py", line 3076, in __call__
    run_metadata=self.run_metadata)
  File "/home/vsairaam/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1439, in __call__
    run_metadata_ptr)
  File "/home/vsairaam/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'input_2' with dtype float and shape [?,2]
	 [[{{node input_2}}]]
	 [[{{node _arg_model_1_target_0_1}}]]

```
Tensorflow : 1.13.1
device 0 with properties: name: GeForce GTX TITAN X major: 5 minor: 2 memoryClockRate(GHz): 1.076

**Comment by HopefulRational** [comment]
Hi @ConorLazarou . verified your claim. Yes, there is some issue. But it works well on tf 1.15 (current default version on colab).

**Comment by ConorLazarou** [comment]
Oh interesting, I suppose I'll downgrade. I did a bit more testing, and have confirmed what you found, that this does not occur when using tf 1.15 (on a CPU and on a GPU). 

And that this does occur when using tf 2.1 (on a CPU and on a GPU).

Thank you so much for finding this workaround for me!

**Comment by gadagashwini** [comment]
@ConorLazarou,
I tried with Tf 2.1.Please take a look at the colab [gist](https://colab.sandbox.google.com/gist/gadagashwini/9deefe1cc9a6831964848b3882779b62/untitled471.ipynb) and confirm whether the reported issue is reproduced or not. Thanks!

**Comment by ConorLazarou** [comment]
@gadagashwini 
Yeah that's it reproduced. The objective shouldn't ever go much below the theoretical minimum.

**Comment by karmel** [comment]
There were some changes in the way trainable behaves between 1.x and 2.x; please take a look at the BatchNorm docs [here](https://www.tensorflow.org/api_docs/python/tf/keras/layers/BatchNormalization) under "About setting layer.trainable = False on a BatchNormalization layer", as this may be causing the discrepancy.

**Comment by ConorLazarou** [comment]
@karmel interesting. Using `tensorflow.compat.v1.keras.layers.BatchNormalization` instead appears to resolve the problem (although I haven't tested it extensively).

**Comment by cecabert** [comment]
@ConorLazarou thanks for the info. It might be one workaround when working with Gan, however when using any type of `tf.keras.Model` you will run into issue, apparently you can not mix `v1` and `v2` layers in a model which kinda make sense.
But there is definitely something wrong with `BatchNormalization` layer.

**Comment by taki0112** [comment]
Hello

when I train a GAN_model with `tf.keras.layers.BatchNormalization`(training=True), It is OK.
![image](https://user-images.githubusercontent.com/26713992/81525738-a4f03200-9390-11ea-88b2-ab1d8a4a065f.png)

But, when I test the model (training=False), It is failed... 
![image](https://user-images.githubusercontent.com/26713992/81525782-ca7d3b80-9390-11ea-8b23-264e0c10cb0c.png)


Is it related to this?

I think, In TF 2.1, for Inference mode in batch normalization(training=False), the model do not use `moving_statistics` learned during training.

**Comment by sachinprasadhs** [comment]
Was able to reproduce your issue in Tf Nightly 2.6.0-dev20210524, please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/c1fbc77d9d8ff72102113ad4eed4eafb/untitled7.ipynb). Thanks!

**Comment by kumariko** [comment]
Was able to reproduce your issue in Tf 2.7.0, please find the gist [here](https://colab.research.google.com/gist/kumariko/4ada2f3ca53e79db6462296a82634a10/untitled7.ipynb#scrollTo=fPzJ0Pz_8T8A). Thanks!

**Comment by tensorflowbutler** [comment]
Hi There,

 This is a stale issue. As you are using an older version of tensorflow, we are checking to see if you still need help on this issue. Please test the issue with the latest TensorFlow (TF2.7 and tf-nightly). If the issue still persists with the newer versions of TF, please feel free to open it in [keras-team/keras](https://github.com/keras-team/keras/issues) repository by providing details about the issue and a standalone code to reproduce the issue. Thanks! 

 Please note that Keras development has moved to a separate Keras-team/keras repository to focus entirely on only Keras. Thanks!
