### ISSUE TITLE
problem with batch processing for tflite in android java

### ISSUE THREAD

**Issue by TanDatDo** [tensorflow/tensorflow#37706]
java.lang.IllegalStateException: Internal error: Unexpected failure when preparing tensor allocations: tensorflow/lite/kernels/reshape.cc:66 num_input_elements != num_output_elements (800 != 400)
    Node number 0 (RESHAPE) failed to prepare.
  
        at org.tensorflow.lite.NativeInterpreterWrapper.allocateTensors(Native Method)
        at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:162)
        at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:275)
        at org.tensorflow.lite.Interpreter.run(Interpreter.java:249)
        at id.unify.gait_sample_app.gait.GaitInferenceManager.getRawScore(GaitInferenceManager.java:55)
        at id.unify.gait_sample_app.gait.Gait.score(Gait.java:160)
        at id.unify.gait_sample_app.ui.main.MainFragment$2.onChanged(MainFragment.java:127)
        at id.unify.gait_sample_app.ui.main.MainFragment$2.onChanged(MainFragment.java:115)
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:113)
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:131)
        at androidx.lifecycle.LiveData.setValue(LiveData.java:289)
        at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:33)
        at androidx.lifecycle.LiveData$1.run(LiveData.java:91)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6776)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

It works with one single input with the dimension [1,1,4,100]
But crashing when trying to process multiple inputs. For example [2,1,4,100]
// dimension [batchsize, 1, 4, 100]
float[][][][] modelInput = convertWalkCycleTo4DFloatArray(walkCycles);
modelOutput = new float[batch.size()][1001];
model.resizeInput(0, [batchsize,1,4, 100]);
model.run(modelInput, modelOutput);

I check method getInputTensor, and clearly the resizing has been successful.
This same tflite model can process inputs in batch in iOS and python

**Comment by gadagashwini** [comment]
@TanDatDo,
Please provide the Tensorflow version and Provide the exact sequence of commands / steps that you executed before running into the problem. Thanks!

**Comment by TanDatDo** [comment]
I use  'org.tensorflow:tensorflow-lite:2.1.0'

Steps I have been through:
``` 
Interpreter.Options options = new Interpreter.Options();
 options.setNumThreads(3);
 options.setUseNNAPI(true);
 Interpreter model = new Interpreter(mappedByteBuffer, options);
//NOTE assign the modelInput to float array with dimension of [batchSize, 1, 4, 100]
float[][][][] modelInput = convertWalkCycleTo4DFloatArray(walkCycles);
modelOutput = new float[batchSize][1001];
int[] dimensions= new int[4];
dimensions[0]=batchSize
dimensions[1]=1;
dimensions[2]=4;
dimensions[3]=100;
model.resizeInput(0, dimensions);
model.run(modelInput, modelOutput);
```
Working when batchsize=1, but crashing when batchSize> 1

**Comment by jdduke** [comment]
Until recently, there were no real guarantees that a model could be successfully resized at runtime. However, we've added the ability to convert models with proper batch dimension placeholders, such that you can now successfully resize at runtime.

Can you try converting your model with the latest TF nightly build, leaving the value of the batch dimension as None?

**Comment by TanDatDo** [comment]
Oh sure! Let me try that, btw, should we use tflite nightly version for production, in general?
https://www.tensorflow.org/lite/guide/android

**Comment by jdduke** [comment]
We try to maintain a pretty high bar for our nightly builds in terms of stability, but still encourage use of our versioned release builds in production. It's good for prototyping and development, though. 

> Oh wait, in java, it requires to use float[] instead of Float[]
> and float require non-null value.

Right, when I mentioned a None dimension, I was referring to model *conversion*. You still need to give explicit dimensions during model *execution*.

**Comment by TanDatDo** [comment]
thanks will try that when I can!

**Comment by TanDatDo** [comment]
Hi! it does not accept none for version 2.0.2 onward
And nightly doesn't accept our usage of selu activation.

**Comment by jdduke** [comment]
> And nightly doesn't accept our usage of selu activation.

Can you speak more to this? What is the exact failure?

**Comment by TanDatDo** [comment]
Yup, the converter does not allow selu
when running converter.convert

**Comment by jdduke** [comment]
The `selu` activation has never been supported, have you tried using a different activation in your graph?

**Comment by jdduke** [comment]
In particular, `selu` requires certain initialization parameters that aren't supported by TFLite for inference (see https://www.tensorflow.org/api_docs/python/tf/keras/initializers/lecun_normal). If you'd like to run this model natively in TFLite your best bet is to find an alternative.

**Comment by sirius0503** [comment]
> Until recently, there were no real guarantees that a model could be successfully resized at runtime. However, we've added the ability to convert models with proper batch dimension placeholders, such that you can now successfully resize at runtime.
> 
> Can you try converting your model with the latest TF nightly build, leaving the value of the batch dimension as None?

Hi @jdduke , this seems to work on android `cpu`, but gives me an error for **gpu** and **nnapi** delegate. the error is same as [Attempting to use a delegate that only supports static-sized tensors with a graph that has dynamic-sized tensors](https://github.com/tensorflow/tensorflow/issues/38036)

**Comment by jdduke** [comment]
Hi @sirius0503 , any chance you could share your model (or a minimal .tflite model repro) that we can use for testing?

**Comment by sirius0503** [comment]
Sure, here is the [tflite model](https://drive.google.com/file/d/1l37Ta6kcQMkEAHKlWL9dwPx3-U411xhv/view?usp=sharing), plz use this model for testing.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by jdduke** [comment]
We're still working on this, hoping to have a fix for the next TF release (2.3). Will post here when a fix makes it into the nightlies.

**Comment by limjq45** [comment]
> Until recently, there were no real guarantees that a model could be successfully resized at runtime. However, we've added the ability to convert models with proper batch dimension placeholders, such that you can now successfully resize at runtime.
> 
> Can you try converting your model with the latest TF nightly build, leaving the value of the batch dimension as None?

Hi @jdduke , may I ask how do we specify the input shape during conversion?I know in tensorflow.compat.v1, you can do this.

```
 converter = tf.lite.TFLiteConverter.from_keras_model_file(
     'model.h5',
     input_shapes={'embedding_input': [128, 300]}
    
)
```

what about the latest nightly build?

**Comment by rmothukuru** [comment]
@TanDatDo,
Sorry for the delayed response. From the documentation of [Post Training Quantization](https://www.tensorflow.org/lite/performance/post_training_quantization) and [RNN TF Lite Converter Guide](https://www.tensorflow.org/lite/convert/rnn), **`Batch Processing`** seems to be implemented for **`TF Lite`**. Can you please check? Thanks!

**Comment by amitmate** [comment]
@jdduke i am also trying to get batch processing to work in Android java, but faced the same issue as reported earlier in this thread. i tried to follow your instructions regarding conversion of the model and keeping batch_size as None, but i get the following error

ValueError: invalid literal for int() with base 10: 'None'


Pls note that my model graph was generated using 1.x , so for conversion i still have to use  1.x

**Comment by jdduke** [comment]
@karimnosseir and @miaout17 should be able to assist further.

**Comment by amitmate** [comment]
thanks @jdduke , @karimnosseir and @miaout17  let me know if you need any more information on this

**Comment by karimnosseir** [comment]
@amitmate if you didn't convert the model with None shape for the dynamic shape, then resizing can be invalid. You have to convert it with dynamic shape.

to verify that it converted as you expect. You can use input_details
```
interpreter  = tf.lite.Interpreter(model_path="model.tflite")
interpreter.get_input_details()
```

This should print the details for all inputs, one of fields is shape_signature, if it doesn't have '-1' in the dimension you are trying to reshape then it is an invalid reshape.

If you're using python calling
```
interpreter.resize_input_tensor with strict=True 
```
will validate that the resizing is valid for you (by default it is not).
Same argument is also available in Java resizeInput method.


For the conversion, you need to keep the 'None' in shape in your original model (not part of conversion). Can you please how are you trying to convert your model, or when are you getting this error.

Thanks

**Comment by amitmate** [comment]
@karimnosseir  thanks for your response. This particular model for which we are trying, we had generated (trained) the frozen graph using the tf1 scripts and  the default checkpoints in tensorflow repo. To convert, we use the "tflite_convert --input_shape=.. " command , seems like the original model in tensorflow repo may be the problem, any idea on how to resolve this?

**Comment by amitmate** [comment]
@karimnosseir , do you need any more information on this?

**Comment by karimnosseir** [comment]
Can you verify that the original TF graph you're converting has dynamic shape, if not you might want to look in how to modify the graph - no idea how easy/hard this is.

**Comment by amitmate** [comment]
it does not have dynamic shape. also it was a tf1 graph (from tf1 modelzoo). It seems like only option is to choose a new dynamic graph from tf2 modelzoo and retrain it..is this understanding  correct?

if so, the there is no information to identify which of the tf2 models (object detection) supports dynamic batch size..https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md

the tf2 version of the ssd model in the modelzoo has dynamic shape for img width and height , but not for batch size..

so, the question really morphs to , can you pls point us to some ssd models in the modelzoo that support dynamic batch size?

**Comment by amitmate** [comment]
@karimnosseir  any suggestions on tf2 models for SSD that have dynamic batch size?

**Comment by rishikakohli11** [comment]
I am working on retraining/fine-tuning trained models (autoencoder and MLP) converted to tflite on android device.  I want to finetune on batch size>1. The input details of autoencoder tflite model are:
**[{'name': 'infer_inputs:0', 'index': 0, 'shape': array([  1, 692, 384], dtype=int32), 'shape_signature': array([ -1, 692, 384], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}]**

It is getting finetuned in python successfully with batch>1, but when i try on android (kotlin), it gives error; 
**Cannot copy to a TensorFlowLite tensor (retrain_x:0) with 1062912 bytes from a Java Buffer with 5314560 bytes.**

My kotlin code is 
    fun trainAutoencoder(sampleEmbedding: FloatArray): Pair<FloatArray, Float> {

        val inputShape = intArrayOf(1, 692, 384) // Single sample shape
        val inputBuffer = TensorBuffer.createFixedSize(inputShape, DataType.FLOAT32)
        inputBuffer.loadArray(sampleEmbedding)

        val encodedShape = intArrayOf(1, 692, 32)  // Compressed 32-dim representation
        val outputBuffer = TensorBuffer.createFixedSize(encodedShape, DataType.FLOAT32)
        val lossBuffer = TensorBuffer.createFixedSize(intArrayOf(1), DataType.FLOAT32)
     
        val inputs = mapOf("x" to inputBuffer.buffer, "y" to inputBuffer.buffer)

        val outputs: MutableMap<String, Any> = mutableMapOf(
            "encoded" to outputBuffer.buffer.rewind(),
            "loss" to lossBuffer.buffer.rewind()
        )
        modelAE.runSignature(inputs, outputs, "train")

        val loss = lossBuffer.floatArray[0]
        val encodedEmbedding = outputBuffer.floatArray

        return Pair(encodedEmbedding, loss)
    }
Can anyone help on this, where I am wrong?
