### ISSUE TITLE
ImportError: DLL load failed: Une routine d’initialisation d’une bibliothèque de liens dynamiques (DLL) a échoué.

### ISSUE THREAD

**Issue by Thomas-Galtier** [tensorflow/tensorflow#37715]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Windows 10 
- TensorFlow installed from (source or binary):  ?
- TensorFlow version: 2.1.0
- Python version: 3.7
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): ?
- GCC/Compiler version (if compiling from source): ?
- CUDA/cuDNN version: 10.2
- GPU model and memory: NVIDA Geforce GTX 950, 2Go

**  the problem**
Hello I installed tensorflow this morning, but the import does not work. Can anyone help me here? Thx

```
import tensorflow as tf
Traceback (most recent call last):
  File "C:\Users\tgalt\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\tgalt\.p2\pool\plugins\org.python.pydev.core_7.5.0.202001101138\pysrc\_pydev_bundle\pydev_import_hook.py", line 24, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\tgalt\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\tgalt\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\tgalt\AppData\Local\Programs\Python\Python37\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\tgalt\AppData\Local\Programs\Python\Python37\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: Une routine d’initialisation d’une bibliothèque de liens dynamiques (DLL) a échoué.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\tgalt\.p2\pool\plugins\org.python.pydev.core_7.5.0.202001101138\pysrc\_pydev_bundle\pydev_import_hook.py", line 24, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\tgalt\AppData\Roaming\Python\Python37\site-packages\tensorflow\__init__.py", line 101, in <module>
    from tensorflow_core import *
  File "C:\Users\tgalt\.p2\pool\plugins\org.python.pydev.core_7.5.0.202001101138\pysrc\_pydev_bundle\pydev_import_hook.py", line 24, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\tgalt\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\__init__.py", line 42, in <module>
    from . _api.v2 import audio
  File "C:\Users\tgalt\.p2\pool\plugins\org.python.pydev.core_7.5.0.202001101138\pysrc\_pydev_bundle\pydev_import_hook.py", line 24, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\tgalt\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\_api\v2\audio\__init__.py", line 10, in <module>
    from tensorflow.python.ops.gen_audio_ops import decode_wav
  File "C:\Users\tgalt\.p2\pool\plugins\org.python.pydev.core_7.5.0.202001101138\pysrc\_pydev_bundle\pydev_import_hook.py", line 24, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\tgalt\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\ops\gen_audio_ops.py", line 9, in <module>
    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow
  File "C:\Users\tgalt\.p2\pool\plugins\org.python.pydev.core_7.5.0.202001101138\pysrc\_pydev_bundle\pydev_import_hook.py", line 24, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\tgalt\AppData\Roaming\Python\Python37\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\Users\tgalt\AppData\Roaming\Python\Python37\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "C:\Users\tgalt\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\tgalt\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\tgalt\.p2\pool\plugins\org.python.pydev.core_7.5.0.202001101138\pysrc\_pydev_bundle\pydev_import_hook.py", line 24, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\tgalt\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\tgalt\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\tgalt\.p2\pool\plugins\org.python.pydev.core_7.5.0.202001101138\pysrc\_pydev_bundle\pydev_import_hook.py", line 24, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\tgalt\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\tgalt\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\tgalt\AppData\Local\Programs\Python\Python37\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\tgalt\AppData\Local\Programs\Python\Python37\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: Une routine d’initialisation d’une bibliothèque de liens dynamiques (DLL) a échoué.


Failed to load the native TensorFlow runtime.
```

Previous steps :
I had a problem of dll before this bug so I followed the log instrusction and I installed some stuff to have msvcp140_1.dll 
then i notice I did not have CUDA installed so I installed cuda, then i got this bug.

**Comment by Saduf2019** [comment]
@Thomas-Galtier 
Could please downgrade the cuda version and try, please refer to [this link](https://github.com/tensorflow/tensorflow/issues/36167) to help you resolve the issue, please confirm if it helps.

below are list of similar issues
#36167 #36151 #36138 #36054 #36045 #36020 #36003 #35988 #35903 #35880 #35865 #35805 #35789 #35773 #35772 #35767 #35766 #35749 #35721 #35618 #35204#22823

**Comment by Thomas-Galtier** [comment]
I downgraded to CUDA 10.0. Now I have the error message `ImportError: cannot import name 'audio' from 'tensorflow_core._api.v2' (C:\Users\tgalt\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\_api\v2\__init__.py)
`

**Comment by Thomas-Galtier** [comment]
I tried cuda 10.0 and 10.1 it did not help.

**Comment by Saduf2019** [comment]
@Thomas-Galtier 
Did you install the Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017, and 2019?

According to the docs at https://www.tensorflow.org/install/pip,

Install the Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017, and 2019. Starting with the TensorFlow 2.1.0 version, the msvcp140_1.dll file is required from this package (which may not be provided from older redistributable packages). The redistributable comes with Visual Studio 2019 but can be installed separately:

Go to the [Microsoft Visual C++ downloads](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads),
Scroll down the page to the Visual Studio 2015, 2017 and 2019 section.
Download and install the Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019 for your platform.
Make sure long paths are [enabled on Windows.
](https://superuser.com/questions/1119883/windows-10-enable-ntfs-long-paths-policy-option-missing)
Install the [64-bit Python 3 release](https://www.python.org/downloads/windows/) for Windows (select pip as an optional feature).

Tensorflow 2.1.0 is compiled using MSVC 2019, which appears to require an additional DLL.

**Comment by Thomas-Galtier** [comment]
Yes i did. The msvcp140_1.dll is on my computer...

**Comment by mihaimaruseac** [comment]
Is your python 64 bits? Does your CPU support AVX?

Closing as duplicate.

https://github.com/tensorflow/tensorflow/issues/36167#issuecomment-577886156

#36167 #36151 #36138 #36054 #36045 #36020 #36003 #35988 #35903 #35880 #35865 #35805 #35789 #35773 #35772 #35767 #35766 #35749 #35721 #35618 #35204

**Comment by mihaimaruseac** [comment]
Sorry, closed by mistake. I see you already installed the latest MSVC.

So questions left to triage are: are you using a 64 bits Python? Does your CPU support AVX?

**Comment by Thomas-Galtier** [comment]
Yes its a python 64 bits. How do I know is my CPU support AVX?

**Comment by Saduf2019** [comment]
@Thomas-Galtier 
please let us know if this is still an issue

**Comment by Saduf2019** [comment]
@Thomas-Galtier
please update as per above comment

**Comment by Thomas-Galtier** [comment]
I did not manage to make it work on windows so I switched to linux and it worked

**Comment by maledh** [comment]
Is there any update about this issue. I still have it and no able to use tensorflow. Thanks
