### ISSUE TITLE
sparse_placeholder missing tensor name in SavedModel

### ISSUE THREAD

**Issue by junshi15** [tensorflow/tensorflow#37755]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): mac-osx
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if
the issue happens on mobile device: n/a
- TensorFlow installed from (source or
binary): - TensorFlow version (use command below): 1.14
- Python version: - Bazel
version (if compiling from source): n/a
- GCC/Compiler version (if compiling from
source): n/a
- CUDA/cuDNN version: - GPU model and memory: n/a

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
If a sparse_placeholder is used in ServingInputReceiver, the SavedModel does not contain the name of the sparse_placeholder. This causes issues when the SavedModel is loaded by SavedModelEstimator, as shown below.
**Describe the expected behavior**
The tensor represented by sparse_placeholder should be assigned a name in the SavedModel.
**Standalone code to reproduce the issue** 
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

Save the code below as a file, test.py. 
then run `python test.py`

```python
import tensorflow as tf
from pathlib import Path

tf.compat.v1.logging.set_verbosity(tf.compat.v1.logging.INFO)

DIM = 4
FEATURE_NAME = "myfeature"
LABEL_NAME = "mylabel"


def train_input_fn():
    dataset = tf.data.Dataset.from_tensors((
        {FEATURE_NAME: tf.SparseTensor(indices=[[0], [2]],
                        values=[1.0, 2.0],
                        dense_shape=[DIM])},[1.0, 2.3]))
    dataset = dataset.repeat(9).batch(3)
    return dataset


def serving_input_receiver_fn():
    """Serving input_fn that builds features from placeholders

    Returns
    -------
    tf.estimator.export.ServingInputReceiver
    """
    feature = tf.compat.v1.sparse_placeholder(dtype=tf.float32, shape=[None, DIM], name=FEATURE_NAME)
    receiver_tensors = {FEATURE_NAME: feature}
    return tf.estimator.export.ServingInputReceiver(receiver_tensors, receiver_tensors)


def model_fn(features, labels, mode):
    w = tf.compat.v1.get_variable(
        name='w',
        initializer=tf.compat.v1.random.truncated_normal((DIM,1), stddev=1))
    predictions = tf.compat.v1.sparse.sparse_dense_matmul(features[FEATURE_NAME], w)

    if mode == tf.estimator.ModeKeys.PREDICT:
        return tf.estimator.EstimatorSpec(mode, predictions=predictions)
    else:
        loss = tf.nn.l2_loss(predictions - labels)
        if mode == tf.estimator.ModeKeys.EVAL:
            return tf.estimator.EstimatorSpec(
                mode, loss=loss)

        elif mode == tf.estimator.ModeKeys.TRAIN:
            train_op = tf.compat.v1.train.AdamOptimizer(learning_rate=0.5).minimize(
                loss, global_step=tf.compat.v1.train.get_global_step())
            return tf.estimator.EstimatorSpec(
                mode, loss=loss, train_op=train_op)
        else:
            raise NotImplementedError()


def find_latest(export_dir):
    subdirs = [x for x in Path(export_dir).iterdir()
               if x.is_dir() and 'temp' not in str(x)]
    latest = str(sorted(subdirs)[-1])
    return latest


if __name__ == '__main__':
    config = tf.estimator.RunConfig(save_summary_steps=1,
                                    save_checkpoints_steps=5,
                                    log_step_count_steps=1)
    export_dir = '/tmp/saved_model'
    checkpoint_dir = '/tmp/checkpoint'

    # train
    estimator = tf.estimator.Estimator(model_fn, checkpoint_dir, config=config)
    estimator.train(train_input_fn)

    # export
    estimator.export_saved_model(export_dir, serving_input_receiver_fn)

    # load
    latest_model = find_latest(export_dir)
    print(latest_model)

    # predict, tf 1.x
    estimator = tf.contrib.estimator.SavedModelEstimator(latest_model)
    predictions = estimator.predict(train_input_fn)
    for x in predictions:
        print(x)
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
Traceback
```
INFO:tensorflow:Using config: {'_model_dir': '/tmp/checkpoint', '_tf_random_seed': None, '_save_summary_steps': 1, '_save_checkpoints_steps': 5, '_save_checkpoints_secs': None, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x12caa1eb8>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
WARNING:tensorflow:From /envs/py3.6/lib/python3.6/site-packages/tensorflow/python/training/training_util.py:236: Variable.initialized_value (from tensorflow.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
WARNING:tensorflow:From /envs/py3.6/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py:1354: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
INFO:tensorflow:Graph was finalized.
2020-03-20 08:09:40.379515: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 0 into /tmp/checkpoint/model.ckpt.
INFO:tensorflow:loss = 5.3372154, step = 1
INFO:tensorflow:global_step/sec: 732.118
INFO:tensorflow:loss = 1.6047388, step = 2 (0.002 sec)
INFO:tensorflow:global_step/sec: 713.317
INFO:tensorflow:loss = 4.220809, step = 3 (0.001 sec)
INFO:tensorflow:Saving checkpoints for 3 into /tmp/checkpoint/model.ckpt.
INFO:tensorflow:Loss for final step: 4.220809.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
WARNING:tensorflow:From /envs/py3.6/lib/python3.6/site-packages/tensorflow/python/saved_model/signature_def_utils_impl.py:201: build_tensor_info (from tensorflow.python.saved_model.utils_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.utils.build_tensor_info or tf.compat.v1.saved_model.build_tensor_info.
INFO:tensorflow:Signatures INCLUDED in export for Classify: None
INFO:tensorflow:Signatures INCLUDED in export for Regress: None
INFO:tensorflow:Signatures INCLUDED in export for Predict: ['serving_default']
INFO:tensorflow:Signatures INCLUDED in export for Train: None
INFO:tensorflow:Signatures INCLUDED in export for Eval: None
WARNING:tensorflow:From /envs/py3.6/lib/python3.6/site-packages/tensorflow/python/training/saver.py:1276: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
INFO:tensorflow:Restoring parameters from /tmp/checkpoint/model.ckpt-3
INFO:tensorflow:Assets added to graph.
INFO:tensorflow:No assets to write.
INFO:tensorflow:SavedModel written to: /tmp/saved_model/temp-b'1584716980'/saved_model.pb
/tmp/saved_model/1584716980
WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

INFO:tensorflow:Using default config.
WARNING:tensorflow:Using temporary folder as model directory: /var/folders/vr/_8gkdt4s3wb88ncn_jmhk8hc000wcr/T/tmp1criy16p
INFO:tensorflow:Using config: {'_model_dir': '/var/folders/vr/_8gkdt4s3wb88ncn_jmhk8hc000wcr/T/tmp1criy16p', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x130e7eeb8>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
INFO:tensorflow:Checking available modes for SavedModelEstimator.
WARNING:tensorflow:train mode not found in SavedModel.
WARNING:tensorflow:eval mode not found in SavedModel.
INFO:tensorflow:Available modes for Estimator: ['infer']
INFO:tensorflow:Could not find trained model in model_dir: /var/folders/vr/_8gkdt4s3wb88ncn_jmhk8hc000wcr/T/tmp1criy16p, running initialization to predict.
WARNING:tensorflow:Input graph does not use tf.data.Dataset or contain a QueueRunner. That means predict yields forever. This is probably a mistake.
INFO:tensorflow:Calling model_fn.
Traceback (most recent call last):
  File "test_savedmodel.py", line 83, in <module>
    for x in predictions:
  File "/envs/py3.6/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 619, in predict
    features, None, ModeKeys.PREDICT, self.config)
  File "/envs/py3.6/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1146, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/envs/py3.6/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/canned/saved_model_estimator.py", line 243, in _model_fn_from_saved_model
    g, tags, input_map=input_map, return_elements=output_tensor_names)
  File "/envs/py3.6/lib/python3.6/site-packages/tensorflow/python/saved_model/loader_impl.py", line 352, in load_graph
    meta_graph_def, import_scope=import_scope, **saver_kwargs)
  File "/envs/py3.6/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1473, in _import_meta_graph_with_return_elements
    **kwargs))
  File "/envs/py3.6/lib/python3.6/site-packages/tensorflow/python/framework/meta_graph.py", line 857, in import_scoped_meta_graph_with_return_elements
    return_elements=return_elements)
  File "/envs/py3.6/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/envs/py3.6/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 412, in import_graph_def
    input_map = _ConvertInputMapValues(name, input_map)
  File "/envs/py3.6/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 193, in _ConvertInputMapValues
    'tf.import_graph_def() requires a non-empty `name` if `input_map` '
ValueError: tf.import_graph_def() requires a non-empty `name` if `input_map` contains non-Tensor values. Try calling tf.convert_to_tensor() on `input_map` values before calling tf.import_graph_def().
```

Further examine the savedmodel with cli `saved_model_cli show --dir /tmp/saved_model/1584716980 --all`

```
MetaGraphDef with tag-set: 'serve' contains the following SignatureDefs:

signature_def['serving_default']:
  The given SavedModel SignatureDef contains the following input(s):
    inputs['myfeature'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, -1)
        name:
  The given SavedModel SignatureDef contains the following output(s):
    outputs['output'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 1)
        name: SparseTensorDenseMatMul/SparseTensorDenseMatMul:0
  Method name is: tensorflow/serving/predict
```
Note: `name` is missing from inputs['myfeature'] tensor_info

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with [TF-1.14](https://colab.research.google.com/gist/amahendrakar/acf0094fe5f26740e7338f827441c8c9/37755-1-14.ipynb) and [TF-1.15.2](https://colab.research.google.com/gist/amahendrakar/5659e56ae2ab72c7faa1c3df71c67490/37755-1-15.ipynb). Please find the attached gist. Thanks!

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
