### ISSUE TITLE
AttributeError when attempting to import Tensorflow on Windows 10

### ISSUE THREAD

**Issue by gragundier** [tensorflow/tensorflow#37756]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 2.1.0
- Python version: 3.7.7
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: None just CPU
- GPU model and memory: Just CPU

**Describe the problem**
When importing tensorflow, there seems to be a problem with compat not existing for datasetinitializerhook...
**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
Python 3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 10:41:24) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.

```
>>> import tensorflow
2020-03-20 16:51:15.881191: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-03-20 16:51:15.884479: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\gragundier\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\__init__.py", line 101, in <module>
    from tensorflow_core import *
  File "C:\Users\gragundier\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\__init__.py", line 46, in <module>
    from . _api.v2 import compat
  File "C:\Users\gragundier\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\_api\v2\compat\__init__.py", line 39, in <module>
    from . import v1
  File "C:\Users\gragundier\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\_api\v2\compat\v1\__init__.py", line 32, in <module>
    from . import compat
  File "C:\Users\gragundier\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\_api\v2\compat\v1\compat\__init__.py", line 39, in <module>
    from . import v1
  File "C:\Users\gragundier\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\_api\v2\compat\v1\compat\v1\__init__.py", line 29, in <module>
    from tensorflow._api.v2.compat.v1 import app
  File "C:\Users\gragundier\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\_api\v2\compat\__init__.py", line 39, in <module>
    from . import v1
  File "C:\Users\gragundier\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\_api\v2\compat\v1\__init__.py", line 32, in <module>
    from . import compat
  File "C:\Users\gragundier\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\_api\v2\compat\v1\compat\__init__.py", line 39, in <module>
    from . import v1
  File "C:\Users\gragundier\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\_api\v2\compat\v1\compat\v1\__init__.py", line 667, in <module>
    from tensorflow_estimator.python.estimator.api._v1 import estimator
  File "C:\Users\gragundier\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_estimator\__init__.py", line 10, in <module>
    from tensorflow_estimator._api.v1 import estimator
  File "C:\Users\gragundier\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_estimator\_api\v1\estimator\__init__.py", line 10, in <module>
    from tensorflow_estimator._api.v1.estimator import experimental
  File "C:\Users\gragundier\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_estimator\_api\v1\estimator\experimental\__init__.py", line 10, in <module>
    from tensorflow_estimator.python.estimator.canned.dnn import dnn_logit_fn_builder
  File "C:\Users\gragundier\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_estimator\python\estimator\canned\dnn.py", line 33, in <module>
    from tensorflow_estimator.python.estimator import estimator
  File "C:\Users\gragundier\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 53, in <module>
    from tensorflow_estimator.python.estimator import util as estimator_util
  File "C:\Users\gragundier\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_estimator\python\estimator\util.py", line 75, in <module>
    class _DatasetInitializerHook(tf.compat.v1.train.SessionRunHook):
AttributeError: module 'tensorflow' has no attribute 'compat'
>>>
```

**Comment by gragundier** [comment]
Just to add and prove that I've at least looked at previous posts similar to this:
CPU: i7-4790k
I do indeed have VS 2015-2019 x64 installed.  
From what I can tell this CPU supports AVX2

**Comment by mihaimaruseac** [comment]
Can you please post the output of `pip list`?

**Comment by gragundier** [comment]
`Package                Version
---------------------- -------------------
absl-py                0.9.0
astor                  0.8.1
astunparse             1.6.3
cachetools             4.0.0
certifi                2019.11.28
chardet                3.0.4
gast                   0.2.2
google-auth            1.11.3
google-auth-oauthlib   0.4.1
google-pasta           0.2.0
grpcio                 1.27.2
h5py                   2.10.0
idna                   2.9
Keras-Applications     1.0.8
Keras-Preprocessing    1.1.0
keyboard               0.13.4
Markdown               3.2.1
mss                    5.0.0
numpy                  1.18.2
oauthlib               3.1.0
opt-einsum             3.2.0
pip                    20.0.2
protobuf               3.11.3
pyasn1                 0.4.8
pyasn1-modules         0.2.8
requests               2.23.0
requests-oauthlib      1.3.0
rsa                    4.0
scipy                  1.4.1
setuptools             41.2.0
six                    1.14.0
tb-nightly             2.2.0a20200320
tensorboard            2.1.1
tensorboard-plugin-wit 1.6.0.post2
tensorflow             2.1.0
tensorflow-estimator   2.1.0
termcolor              1.1.0
tf-estimator-nightly   2.3.0.dev2020032001
urllib3                1.25.8
Werkzeug               1.0.0
wheel                  0.34.2
wrapt                  1.12.1`

**Comment by mihaimaruseac** [comment]
So you have both nightly and released versions. Can you try the following two commands please?

```
pip uninstall -y tb-nightly tensorboard tensorboard-plugin-wit tensorflow tensorflow-estimator tf-estimator-nightly
pip install tensorflow
```

**Comment by gragundier** [comment]
Thank you.  Closing issue.

**Comment by abiring** [comment]
> So you have both nightly and released versions. Can you try the following two commands please?
> 
> ```
> pip uninstall -y tb-nightly tensorboard tensorboard-plugin-wit tensorflow tensorflow-estimator tf-estimator-nightly
> pip install tensorflow
> ```

thank you

**Comment by erolgerceker** [comment]
> So you have both nightly and released versions. Can you try the following two commands please?
> 
> ```
> pip uninstall -y tb-nightly tensorboard tensorboard-plugin-wit tensorflow tensorflow-estimator tf-estimator-nightly
> pip install tensorflow
> ```

thanks a lot
