### ISSUE TITLE
error with wide_n_deep_tutorial.py

### ISSUE THREAD

**Issue by tranlm** [tensorflow/tensorflow#3776]
I'm running into problems when trying to run the wide and deep tutorial code example. Here's my info:

### Environment info
Operating System: OSX 10.11.4 

Installed version of CUDA and cuDNN: CUDA-7.5,
-rwxr-xr-x@ 2 root  wheel      8280 Apr 12 23:02 /usr/local/cuda/lib/libcuda.1.dylib
-rwxr-xr-x@ 2 root  wheel      8280 Apr 12 23:02 /usr/local/cuda/lib/libcuda.dylib
lrwxr-xr-x@ 1 root  wheel        45 Apr 12 23:03 /usr/local/cuda/lib/libcudadevrt.a -> /Developer/NVIDIA/CUDA-7.5/lib/libcudadevrt.a
lrwxr-xr-x@ 1 root  wheel        50 Apr 12 23:03 /usr/local/cuda/lib/libcudart.7.5.dylib -> /Developer/NVIDIA/CUDA-7.5/lib/libcudart.7.5.dylib
lrwxr-xr-x@ 1 root  wheel        46 Apr 12 23:03 /usr/local/cuda/lib/libcudart.dylib -> /Developer/NVIDIA/CUDA-7.5/lib/libcudart.dylib
lrwxr-xr-x@ 1 root  wheel        49 Apr 12 23:03 /usr/local/cuda/lib/libcudart_static.a -> /Developer/NVIDIA/CUDA-7.5/lib/libcudart_static.a
-rwxr-xr-x@ 1 root  admin  58270280 Aug  2 21:26 /usr/local/cuda/lib/libcudnn.5.dylib
-rwxr-xr-x@ 1 root  admin  58270280 Aug  2 21:26 /usr/local/cuda/lib/libcudnn.dylib
-rw-r--r--@ 1 root  admin  55551064 Aug  2 21:26 /usr/local/cuda/lib/libcudnn_static.a

### Steps to reproduce
1. Open the script, set the "model_type" FLAG to "deep" or to "wide_n_deep", and run interactively with an open Python compiler.

### What have you tried?
1. Running it with FLAGS.model_type = "wide" works fine. 

### Logs or other output that would be helpful
Here is the log from running it with FLAGS.model_type = "deep"
```
Training data is downloaded to /var/folders/_x/ssxr2t2144v_2vr8w0yywpvw0000gn/T/tmpbVSoKV
Test data is downloaded to /var/folders/_x/ssxr2t2144v_2vr8w0yywpvw0000gn/T/tmp8ojlXf
model directory = .
WARNING:tensorflow:Setting feature info to {'hours_per_week': TensorSignature(dtype=tf.int64, shape=TensorShape([Dimension(32561)]), is_sparse=False), 'workclass': TensorSignature(dtype=tf.string, shape=None, is_sparse=True), 'relationship': TensorSignature(dtype=tf.string, shape=None, is_sparse=True), 'gender': TensorSignature(dtype=tf.string, shape=None, is_sparse=True), 'age': TensorSignature(dtype=tf.int64, shape=TensorShape([Dimension(32561)]), is_sparse=False), 'marital_status': TensorSignature(dtype=tf.string, shape=None, is_sparse=True), 'race': TensorSignature(dtype=tf.string, shape=None, is_sparse=True), 'education_num': TensorSignature(dtype=tf.int64, shape=TensorShape([Dimension(32561)]), is_sparse=False), 'native_country': TensorSignature(dtype=tf.string, shape=None, is_sparse=True), 'capital_loss': TensorSignature(dtype=tf.int64, shape=TensorShape([Dimension(32561)]), is_sparse=False), 'education': TensorSignature(dtype=tf.string, shape=None, is_sparse=True), 'capital_gain': TensorSignature(dtype=tf.int64, shape=TensorShape([Dimension(32561)]), is_sparse=False), 'occupation': TensorSignature(dtype=tf.string, shape=None, is_sparse=True)}
WARNING:tensorflow:Setting targets info to TensorSignature(dtype=tf.int64, shape=TensorShape([Dimension(32561)]), is_sparse=False)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:839] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GT 750M, pci bus id: 0000:01:00.0)
W tensorflow/core/framework/op_kernel.cc:936] Not found: Tensor name "hiddenlayer_1/biases/Adagrad" not found in checkpoint files ./model.ckpt-200-?????-of-00001
	 [[Node: save/restore_slice_12 = RestoreSlice[dt=DT_FLOAT, preferred_shard=0, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_12/tensor_name, save/restore_slice_12/shape_and_slice)]]
W tensorflow/core/framework/op_kernel.cc:936] Not found: Tensor name "hiddenlayer_1/biases/Adagrad" not found in checkpoint files ./model.ckpt-200-?????-of-00001
	 [[Node: save/restore_slice_12 = RestoreSlice[dt=DT_FLOAT, preferred_shard=0, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_12/tensor_name, save/restore_slice_12/shape_and_slice)]]
W tensorflow/core/framework/op_kernel.cc:936] Not found: Tensor name "hiddenlayer_1/biases/Adagrad" not found in checkpoint files ./model.ckpt-200-?????-of-00001
	 [[Node: save/restore_slice_12 = RestoreSlice[dt=DT_FLOAT, preferred_shard=0, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_12/tensor_name, save/restore_slice_12/shape_and_slice)]]
E tensorflow/core/client/tensor_c_api.cc:485] Tensor name "hiddenlayer_1/biases/Adagrad" not found in checkpoint files ./model.ckpt-200-?????-of-00001
	 [[Node: save/restore_slice_12 = RestoreSlice[dt=DT_FLOAT, preferred_shard=0, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_12/tensor_name, save/restore_slice_12/shape_and_slice)]]
	 [[Node: save/Assign_22/_84 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_179_save/Assign_22", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 23, in train_and_eval
  File "/usr/local/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 240, in fit
    max_steps=max_steps)
  File "/usr/local/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 578, in _train_model
    max_steps=max_steps)
  File "/usr/local/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/graph_actions.py", line 276, in _supervised_train
    scaffold=scaffold) as super_sess:
  File "/usr/local/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/supervised_session.py", line 212, in __init__
    self._sess = recoverable_session.RecoverableSession(self._create_session)
  File "/usr/local/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/recoverable_session.py", line 46, in __init__
    WrappedSession.__init__(self, sess_factory())
  File "/usr/local/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/supervised_session.py", line 232, in _create_session
    init_fn=self._scaffold.init_fn)
  File "/usr/local/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/session_manager.py", line 164, in prepare_session
    max_wait_secs=max_wait_secs, config=config)
  File "/usr/local/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/session_manager.py", line 224, in recover_session
    saver.restore(sess, ckpt.model_checkpoint_path)
  File "/usr/local/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1129, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 382, in run
    run_metadata_ptr)
  File "/usr/local/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 655, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 723, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 743, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors.NotFoundError: Tensor name "hiddenlayer_1/biases/Adagrad" not found in checkpoint files ./model.ckpt-200-?????-of-00001
	 [[Node: save/restore_slice_12 = RestoreSlice[dt=DT_FLOAT, preferred_shard=0, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_12/tensor_name, save/restore_slice_12/shape_and_slice)]]
	 [[Node: save/Assign_22/_84 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_179_save/Assign_22", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
Caused by op u'save/restore_slice_12', defined at:
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 23, in train_and_eval
  File "/usr/local/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 240, in fit
    max_steps=max_steps)
  File "/usr/local/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 578, in _train_model
    max_steps=max_steps)
  File "/usr/local/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/graph_actions.py", line 252, in _supervised_train
    keep_checkpoint_max=keep_checkpoint_max)
  File "/usr/local/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/supervised_session.py", line 152, in __init__
    lambda: training_saver.Saver(sharded=True,
  File "/usr/local/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/supervised_session.py", line 164, in _get_or_default
    op = default_constructor()
  File "/usr/local/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/supervised_session.py", line 153, in <lambda>
    max_to_keep=keep_checkpoint_max))
  File "/usr/local/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 861, in __init__
    restore_sequentially=restore_sequentially)
  File "/usr/local/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 515, in build
    filename_tensor, per_device, restore_sequentially, reshape)
  File "/usr/local/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 312, in _AddShardedRestoreOps
    name="restore_shard"))
  File "/usr/local/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 272, in _AddRestoreOps
    values = self.restore_op(filename_tensor, vs, preferred_shard)
  File "/usr/local/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 187, in restore_op
    preferred_shard=preferred_shard)
  File "/usr/local/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/io_ops.py", line 203, in _restore_slice
    preferred_shard, name=name)
  File "/usr/local/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/gen_io_ops.py", line 359, in _restore_slice
    preferred_shard=preferred_shard, name=name)
  File "/usr/local/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 703, in apply_op
    op_def=op_def)
  File "/usr/local/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2310, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1232, in __init__
    self._traceback = _extract_stack()

```

**Comment by prb12** [comment]
This looks to me like the code it trying to restore a saved checkpoint.  Did you perhaps run with one configuration, long enough to save a checkpoint, and then start with different parameters (but without deleting the old checkpoints?)

**Comment by aselle** [comment]
Automatically closing due to lack of recent activity. Please reopen if further information becomes available.
