### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by kalkoby** [tensorflow/tensorflow#37797]
**

> SOLVED ===>  I installed Visual Studio 2009.  The root of the problem is that I need clean C++ redistributable files available.  WHEW!

**

Thanks Sreerag-ibtl for jumping into my issue.  I tried reinstall using pip, conda then use anaconda interface several times.

**Comment by kalkoby** [comment]
I am learning how to use NLP.  One of the package, tensorflow is required to be used for my activity.   I have uninstall and install tensorflow repeatedly with no success.

== check python ===================================================
python version: 3.7.6
python branch:
python build version: ('default', 'Jan  8 2020 20:23:39')
python compiler version: MSC v.1916 64 bit (AMD64)
python implementation: CPython


== check os platform ===============================================
os: Windows
os kernel version: 10.0.18362
os release version: 10
os platform: Windows-10-10.0.18362-SP0
linux distribution: ('', '', '')
linux os distribution: ('', '', '')
mac version: ('', ('', '', ''), '')
uname: uname_result(system='Windows', node='Karen8700', release='10', version='10.0.18362', machine='AMD64', processor='Intel64 Family 6 Model 60 Stepping 3, GenuineIntel')
architecture: ('64bit', 'WindowsPE')
machine: AMD64


== are we in docker =============================================
No

== compiler =====================================================
/c/Users/karen/anaconda3/envs/pythondata/lib/tf_env_collect.sh: line 100: c++: command not found

== check pips ===================================================
numpy                              1.18.2
numpydoc                           0.9.2
protobuf                           3.11.3
tensorflow                         2.1.0
tensorflow-estimator               2.1.0

== check for virtualenv =========================================
False

== tensorflow import ============================================
Traceback (most recent call last):
  File "C:\Users\karen\anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\karen\anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\karen\anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\karen\anaconda3\envs\pythondata\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\karen\anaconda3\envs\pythondata\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\karen\anaconda3\lib\site-packages\tensorflow\__init__.py", line 101, in <module>
    from tensorflow_core import *
  File "C:\Users\karen\anaconda3\lib\site-packages\tensorflow_core\__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\karen\anaconda3\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\Users\karen\anaconda3\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "C:\Users\karen\anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\karen\anaconda3\lib\site-packages\tensorflow_core\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\karen\anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\karen\anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\karen\anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\karen\anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\karen\anaconda3\envs\pythondata\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\karen\anaconda3\envs\pythondata\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

== env ==========================================================
LD_LIBRARY_PATH is unset
DYLD_LIBRARY_PATH is unset

== nvidia-smi ===================================================
/c/Users/karen/anaconda3/envs/pythondata/lib/tf_env_collect.sh: line 145: nvidia-smi: command not found

== cuda libs  ===================================================

== tensorflow installed from info ==================
Name: tensorflow
Version: 2.1.0
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: c:\users\karen\anaconda3\lib\site-packages
Required-by:

== python version  ==============================================
(major, minor, micro, releaselevel, serial)
(3, 7, 6, 'final', 0)

== bazel version  ===============================================

karen@Karen8700 MINGW64 ~/anaconda3/envs/pythondata/lib
$ ^C

**Comment by Sreerag-ibtl** [comment]
I had similar issue with `pip install tensorflow`. Resolved with a fresh `conda install tensorflow`.

**Comment by mihaimaruseac** [comment]
closing and locking as this just duplicates a resolved issue only to say "works"/"thanks"

**Comment by mihaimaruseac** [comment]
If it is a new issue, please fill in issue template in a new issue
