### ISSUE TITLE
tf.fill(), This function does not handle the case of the path where all inputs are not already EagerTensors

### ISSUE THREAD

**Issue by xiaoyangnihao** [tensorflow/tensorflow#37822]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information** 
- TensorFlow installed from (source or
binary): - TensorFlow version (use command below): 2.20rc0
- Python version: 3.7.6
- CUDA/cuDNN version: - GPU model and memory:CPU only

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

**Describe the expected behavior**

**Standalone code to reproduce the issue** 
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
```
# I run this in eager mode
# input: [batch_size, features]
def get_indices(self, input, batch_size, max_len):
	num_phones = input.get_shape().as_list()[1]

	out = []
	for i in range(batch_size):
		cur_len = tf.reduce_sum(input[i])
		indices = tf.concat([tf.fill([input[i][idx]], idx)
							 for idx in range(num_phones)], axis=-1)
							 
	return out
```
**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
```
Traceback (most recent call last):
  File "/home/yhb/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3307, in fill
    dims, value)
tensorflow.python.eager.core._FallbackException: This function does not handle the case of the path where all inputs are not already EagerTensors.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/SourceCode/tacotron-tf2/train.py", line 168, in <module>
    main()
  File "/mnt/c/SourceCode/tacotron-tf2/train.py", line 164, in main
    train(log_dir, args)
  File "/mnt/c/SourceCode/tacotron-tf2/train.py", line 98, in train
    mel_targets, linear_targets)
  File "/mnt/c/SourceCode/tacotron-tf2/train.py", line 30, in train_step
    mel_outputs, linear_outputs = model((sequences, durations), training=True)
  File "/home/yhb/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 967, in __call__
    outputs = self.call(cast_inputs, *args, **kwargs)
  File "/mnt/c/SourceCode/tacotron-tf2/models/tacotron.py", line 567, in call
    training=training)
  File "/home/yhb/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 967, in __call__
    outputs = self.call(cast_inputs, *args, **kwargs)
  File "/mnt/c/SourceCode/tacotron-tf2/models/tacotron.py", line 229, in call
    indices = self.get_indices(durations, batch_size, max_len)
  File "/mnt/c/SourceCode/tacotron-tf2/models/tacotron.py", line 245, in get_indices
    for idx in range(num_phones)], axis=-1)
  File "/mnt/c/SourceCode/tacotron-tf2/models/tacotron.py", line 245, in <listcomp>
    for idx in range(num_phones)], axis=-1)
  File "/home/yhb/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py", line 234, in fill
    result = gen_array_ops.fill(dims, value, name=name)
  File "/home/yhb/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3312, in fill
    dims, value, name=name, ctx=_ctx)
  File "/home/yhb/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3339, in fill_eager_fallback
    ctx=ctx, name=name)
  File "/home/yhb/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimension -14 must be >= 0 [Op:Fill]
```
Process finished with exit code 1

**Comment by ravikyram** [comment]
@xiaoyangnihao 

Looks like code is incomplete. Please, share colab link or simple standalone code to reproduce the issue in our environment. It helps us in localizing the issue faster. Thanks!

**Comment by joaossmacedo** [comment]
Why was this issue closed? Does anyone have a solution?
