### ISSUE TITLE
Issue with installation of Tensorflow in Windows10

### ISSUE THREAD

**Issue by indranibose1981** [tensorflow/tensorflow#37825]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution:Windows
- TensorFlow installed from (source or binary): https://www.tensorflow.org/install
- TensorFlow version:2.0
- Python version:3.6
- Installed using virtualenv? pip? conda?: Created virtualenv using conda. used pip to install tensorflow
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:10.1
- GPU model and memory: GTX 1650

**Describe the problem**
Tensorflow is getting installed in virtual environment but cannot import it.When I try to import, I get the following error

Traceback (most recent call last):
  File "C:\Users\indra\anaconda3\envs\imgreco\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\indra\anaconda3\envs\imgreco\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\indra\anaconda3\envs\imgreco\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\indra\anaconda3\envs\imgreco\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\indra\anaconda3\envs\imgreco\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\indra\anaconda3\envs\imgreco\lib\site-packages\tensorflow\__init__.py", line 101, in <module>
    from tensorflow_core import *
  File "C:\Users\indra\anaconda3\envs\imgreco\lib\site-packages\tensorflow_core\__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\indra\anaconda3\envs\imgreco\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\Users\indra\anaconda3\envs\imgreco\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "C:\Users\indra\anaconda3\envs\imgreco\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\indra\anaconda3\envs\imgreco\lib\site-packages\tensorflow_core\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\indra\anaconda3\envs\imgreco\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\indra\anaconda3\envs\imgreco\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\indra\anaconda3\envs\imgreco\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\indra\anaconda3\envs\imgreco\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\indra\anaconda3\envs\imgreco\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\indra\anaconda3\envs\imgreco\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.
Failed to load the native TensorFlow runtime.
See https://www.tensorflow.org/install/errors

TensorFlowTensorF
*Steps followed**
1. Uninstall all NVIDIA Drivers/Software and delete all NVIDIA files from program files (x86 aswell)

2. Install Visual Studio 2017 (from link above)

3. Install CUDA (first check compatible versions using link above)

4. Download cuDNN (again check version is same as CUDA version)

5. Extract the cuDNN zip folder to your desktop. Open a new windows explorer and navigate to C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\Vx.x\ . Now copy the contents of the downloaded and extracted cuDNN folder into the appropriate folders (files from cuDNN bin go into the new windows explorer bin folder etc.).

6. Navigate to your system enviorment variables and edit the path. Add the following two directories into your path:
-  C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin
- C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\libnvvp

7. Download and Install Anaconda (from link above)

8. Set up a virtual enviorment using python 3.5
- conda create -n [name] python=3.5

9. Activate the virtual enviorment
- activate [name]

10. Install packages
- pip install --ignore-installed --upgrade tensorflow-gpu
- pip install keras

**Any other info / logs**
Traceback (most recent call last):
  File "C:\Users\indra\anaconda3\envs\imgreco\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\indra\anaconda3\envs\imgreco\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\indra\anaconda3\envs\imgreco\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\indra\anaconda3\envs\imgreco\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\indra\anaconda3\envs\imgreco\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\indra\anaconda3\envs\imgreco\lib\site-packages\tensorflow\__init__.py", line 101, in <module>
    from tensorflow_core import *
  File "C:\Users\indra\anaconda3\envs\imgreco\lib\site-packages\tensorflow_core\__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\indra\anaconda3\envs\imgreco\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\Users\indra\anaconda3\envs\imgreco\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "C:\Users\indra\anaconda3\envs\imgreco\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\indra\anaconda3\envs\imgreco\lib\site-packages\tensorflow_core\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\indra\anaconda3\envs\imgreco\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\indra\anaconda3\envs\imgreco\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\indra\anaconda3\envs\imgreco\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\indra\anaconda3\envs\imgreco\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\indra\anaconda3\envs\imgreco\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\indra\anaconda3\envs\imgreco\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.
Failed to load the native TensorFlow runtime.
See https://www.tensorflow.org/install/errors

**Comment by ravikyram** [comment]
@indranibose1981 

What is make/model of your cpu?
I suspect your cpu model does not support AVX instructions sets.See [hardware requirements](https://www.tensorflow.org/install/pip?lang=python3#hardware-requirements)
Make sure to download the [latest microsoft visual c++ redistributable from here.](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads)
.Also, please follow the instructions from to install from [Tensorflow website](https://www.tensorflow.org/install/source_windows).

Please, check Your CPU/Python is on 32 bits?Please, refer #36167 and see if it helps you.Thanks!

**Comment by mihaimaruseac** [comment]
Please use ` ``` ` around code blocks on future issue reports. Also, please check for duplicates.

Closing as duplicate.

https://github.com/tensorflow/tensorflow/issues/36167#issuecomment-577886156

#36167 #36151 #36138 #36054 #36045 #36020 #36003 #35988 #35903 #35880 #35865 #35805 #35789 #35773 #35772 #35767 #35766 #35749 #35721 #35618 #35204

**Comment by indranibose1981** [comment]
I am using a GPU. I was able to install 1.5 version but 2.0 of tensor flow still does not work.
