### ISSUE TITLE
windows build with r2.2 failed

### ISSUE THREAD

**Issue by alanpurple** [tensorflow/tensorflow#37888]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows10 x64 1909
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.2.0rc2
- Python version: 3.8.1
- Installed using virtualenv? pip? conda?: N/A
- Bazel version (if compiling from source): 2.0.0
- GCC/Compiler version (if compiling from source): Visual Studio 2019
- CUDA/cuDNN version: 10.2/7.6.5
- GPU model and memory:
RTX2080Ti GDDR6 11GB

**Describe the problem**
build failed
**Provide the exact sequence of commands / steps that you executed before running into the problem**
bazel build

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
```
INFO: Call stack for the definition of repository 'local_config_python' which is a python_configure (rule definition at D:/repo/tensorflow/third_party/py/python_configure.bzl:280:20):
 - D:/repo/tensorflow/tensorflow/workspace.bzl:97:5
 - D:/repo/tensorflow/WORKSPACE:19:1
ERROR: An error occurred during the fetch of repository 'local_config_python':
   Traceback (most recent call last):
        File "D:/repo/tensorflow/third_party/py/python_configure.bzl", line 263
                _create_local_python_repository(<1 more arguments>)
        File "D:/repo/tensorflow/third_party/py/python_configure.bzl", line 209, in _create_local_python_repository
                _check_python_bin(<2 more arguments>)
        File "D:/repo/tensorflow/third_party/py/python_configure.bzl", line 143, in _check_python_bin
                raw_exec(repository_ctx, <1 more arguments>)
        File "D:/repo/tensorflow/third_party/py/python_configure.bzl", line 143, in raw_exec
                get_bash_bin(repository_ctx)
        File "D:/repo/tensorflow/third_party/remote_config/common.bzl", line 66, in get_bash_bin
                which(repository_ctx, "bash")
        File "D:/repo/tensorflow/third_party/remote_config/common.bzl", line 27, in which
                execute(repository_ctx, <1 more arguments>)
        File "D:/repo/tensorflow/third_party/remote_config/common.bzl", line 208, in execute
                fail(<1 more arguments>)
Repository command failed
INFO: Could not find files for the given pattern(s).
ERROR: While resolving toolchains for target //third_party/eigen3:eigen3: invalid registered toolchain '@local_config_python//:py_toolchain': no such package '@local_config_python//': Traceback (most recent call last):
        File "D:/repo/tensorflow/third_party/py/python_configure.bzl", line 263
                _create_local_python_repository(<1 more arguments>)
        File "D:/repo/tensorflow/third_party/py/python_configure.bzl", line 209, in _create_local_python_repository
                _check_python_bin(<2 more arguments>)
        File "D:/repo/tensorflow/third_party/py/python_configure.bzl", line 143, in _check_python_bin
                raw_exec(repository_ctx, <1 more arguments>)
        File "D:/repo/tensorflow/third_party/py/python_configure.bzl", line 143, in raw_exec
                get_bash_bin(repository_ctx)
        File "D:/repo/tensorflow/third_party/remote_config/common.bzl", line 66, in get_bash_bin
                which(repository_ctx, "bash")
        File "D:/repo/tensorflow/third_party/remote_config/common.bzl", line 27, in which
                execute(repository_ctx, <1 more arguments>)
        File "D:/repo/tensorflow/third_party/remote_config/common.bzl", line 208, in execute
                fail(<1 more arguments>)
Repository command failed
INFO: Could not find files for the given pattern(s).
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: invalid registered toolchain '@local_config_python//:py_toolchain': no such package '@local_config_python//': Traceback (most recent call last):
        File "D:/repo/tensorflow/third_party/py/python_configure.bzl", line 263
                _create_local_python_repository(<1 more arguments>)
        File "D:/repo/tensorflow/third_party/py/python_configure.bzl", line 209, in _create_local_python_repository
                _check_python_bin(<2 more arguments>)
        File "D:/repo/tensorflow/third_party/py/python_configure.bzl", line 143, in _check_python_bin
                raw_exec(repository_ctx, <1 more arguments>)
        File "D:/repo/tensorflow/third_party/py/python_configure.bzl", line 143, in raw_exec
                get_bash_bin(repository_ctx)
        File "D:/repo/tensorflow/third_party/remote_config/common.bzl", line 66, in get_bash_bin
                which(repository_ctx, "bash")
        File "D:/repo/tensorflow/third_party/remote_config/common.bzl", line 27, in which
                execute(repository_ctx, <1 more arguments>)
        File "D:/repo/tensorflow/third_party/remote_config/common.bzl", line 208, in execute
                fail(<1 more arguments>)
Repository command failed
INFO: Could not find files for the given pattern(s).
INFO: Elapsed time: 6.220s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (101 packages loaded, 322 targets configured)
```

**Comment by mihaimaruseac** [comment]
Did you run `./configure`? Can you try `bazel clean --expunge`, followed by `python configure.py` and then the build command?

**Comment by mihaimaruseac** [comment]
Also, see #37802 in case these have the same root cause

**Comment by alanpurple** [comment]
@mihaimaruseac 

I've built tensorflow image more than 100 times, clean bazel and configure are very basic

and #37802 seems not to be relaeted


2.2.0rc1 was built successfully.



I'm not sure but  Nvidia updated their drivers recently(2 times), that's the only difference since my last successful build
