### ISSUE TITLE
Build Fail Due to "ImportError: No module named enum" (python 3.7)

### ISSUE THREAD

**Issue by wanglei18** [tensorflow/tensorflow#37880]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (macOS Mojave, version 10.14.6):
- TensorFlow installed from (source, https://github.com/tensorflow/tensorflow.git):
- TensorFlow version: 2
- Python version: 3.7
- Installed using pip
- Bazel version (if compiling from source): 2.2.0
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**
Following the extract instruction here: https://www.tensorflow.org/install/source 
Specified python 3.7 in ./configure

Run:  **bazel build //tensorflow/tools/pip_package:build_pip_package --host_force_python=PY3**

The build failed, saying "ImportError: No module named enum". See the detail below. 
**Already googled and tried  pip install --upgrade pip enum34, but still not working.**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
ERROR: /Users/leiwang/GoogleDrive/models/tensorflow/tensorflow/python/keras/api/BUILD:133:1: Executing genrule //tensorflow/python/keras/api:keras_python_api_gen_compat_v2 failed (Exit 1)
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_leiwang/db84a35c42355241097f16166c7580af/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen_compat_v2.runfiles/org_tensorflow/tensorflow/python/tools/api/generator/create_python_api.py", line 27, in <module>
    from tensorflow.python.tools.api.generator import doc_srcs
  File "/private/var/tmp/_bazel_leiwang/db84a35c42355241097f16166c7580af/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen_compat_v2.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 64, in <module>
    from tensorflow.python.framework.framework_lib import *  # pylint: disable=redefined-builtin
  File "/private/var/tmp/_bazel_leiwang/db84a35c42355241097f16166c7580af/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen_compat_v2.runfiles/org_tensorflow/tensorflow/python/framework/framework_lib.py", line 52, in <module>
    from tensorflow.python.framework.importer import import_graph_def
  File "/private/var/tmp/_bazel_leiwang/db84a35c42355241097f16166c7580af/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen_compat_v2.runfiles/org_tensorflow/tensorflow/python/framework/importer.py", line 28, in <module>
    from tensorflow.python.framework import function
  File "/private/var/tmp/_bazel_leiwang/db84a35c42355241097f16166c7580af/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen_compat_v2.runfiles/org_tensorflow/tensorflow/python/framework/function.py", line 37, in <module>
    from tensorflow.python.ops import resource_variable_ops
  File "/private/var/tmp/_bazel_leiwang/db84a35c42355241097f16166c7580af/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen_compat_v2.runfiles/org_tensorflow/tensorflow/python/ops/resource_variable_ops.py", line 46, in <module>
    from tensorflow.python.ops import variables
  File "/private/var/tmp/_bazel_leiwang/db84a35c42355241097f16166c7580af/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_keras_python_api_gen_compat_v2.runfiles/org_tensorflow/tensorflow/python/ops/variables.py", line 20, in <module>
    import enum  # pylint: disable=g-bad-import-order
ImportError: No module named enum
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /Users/leiwang/GoogleDrive/models/tensorflow/tensorflow/tools/pip_package/BUILD:65:1 Executing genrule //tensorflow/python/keras/api:keras_python_api_gen failed (Exit 1)
INFO: Elapsed time: 1.875s, Critical Path: 1.19s
INFO: 0 processes.
FAILED: Build did NOT complete successfully

**Comment by wanglei18** [comment]
solved
