### ISSUE TITLE
Issue: install 

### ISSUE THREAD

**Issue by GauAnhViDai** [tensorflow/tensorflow#3790]
I am trying to install tensorflow on Fedora 23. I use python 3.4. So, I follow the guide:
$export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.10.0rc0-cp34-cp34m-linux_x86_64.whl
$pip3 install --upgrade $TF_BINARY_URL

But it doesn't work. Here is the log:

Collecting tensorflow==0.10.0rc0 from https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.10.0rc0-cp34-cp34m-linux_x86_64.whl
  Using cached https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.10.0rc0-cp34-cp34m-linux_x86_64.whl
Collecting numpy>=1.8.2 (from tensorflow==0.10.0rc0)
  Using cached numpy-1.11.1.zip
Requirement already up-to-date: wheel>=0.26 in /usr/lib/python3.4/site-packages (from tensorflow==0.10.0rc0)
Requirement already up-to-date: six>=1.10.0 in /usr/lib/python3.4/site-packages (from tensorflow==0.10.0rc0)
Requirement already up-to-date: protobuf==3.0.0b2 in /usr/lib/python3.4/site-packages (from tensorflow==0.10.0rc0)
Collecting setuptools (from protobuf==3.0.0b2->tensorflow==0.10.0rc0)
  Using cached setuptools-25.2.0-py2.py3-none-any.whl
Building wheels for collected packages: numpy
  Running setup.py bdist_wheel for numpy
  Complete output from command /usr/bin/python3 -c "import setuptools;__file__='/tmp/pip-build-vtpn0vsk/numpy/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpo1ev1azppip-wheel-:
  blas_opt_info:
  blas_mkl_info:
    libraries mkl,vml,guide not found in ['/usr/local/lib64', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']
    NOT AVAILABLE
  
  openblas_info:
    libraries openblas not found in ['/usr/local/lib64', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']
    NOT AVAILABLE
  
  atlas_3_10_blas_threads_info:
  Setting PTATLAS=ATLAS
    libraries tatlas not found in ['/usr/local/lib64', '/usr/local/lib', '/usr/lib64/sse2', '/usr/lib64', '/usr/lib/sse2', '/usr/lib', '/usr/lib/sse2', '/usr/lib/']
    NOT AVAILABLE
  
  atlas_3_10_blas_info:
    libraries satlas not found in ['/usr/local/lib64', '/usr/local/lib', '/usr/lib64/sse2', '/usr/lib64', '/usr/lib/sse2', '/usr/lib', '/usr/lib/sse2', '/usr/lib/']
    NOT AVAILABLE
  
  atlas_blas_threads_info:
  Setting PTATLAS=ATLAS
    libraries ptf77blas,ptcblas,atlas not found in ['/usr/local/lib64', '/usr/local/lib', '/usr/lib64/sse2', '/usr/lib64', '/usr/lib/sse2', '/usr/lib', '/usr/lib/sse2', '/usr/lib/']
    NOT AVAILABLE
  
  atlas_blas_info:
    libraries f77blas,cblas,atlas not found in ['/usr/local/lib64', '/usr/local/lib', '/usr/lib64/sse2', '/usr/lib64', '/usr/lib/sse2', '/usr/lib', '/usr/lib/sse2', '/usr/lib/']
    NOT AVAILABLE
  
  blas_info:
  customize UnixCCompiler
  C compiler: gcc -pthread -Wno-unused-result -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC
  
  creating /tmp/tmpwhgndlax/tmp
  creating /tmp/tmpwhgndlax/tmp/tmpwhgndlax
  compile options: '-I/usr/local/include -I/usr/include -c'
  gcc: /tmp/tmpwhgndlax/source.c
  gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No such file or directory
  gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No such file or directory
    libraries blas not found in ['', '']
  Runtime library blas was not found. Ignoring
    FOUND:
      libraries = ['blas', 'blas']
      library_dirs = ['/usr/lib64']
  
    FOUND:
      define_macros = [('NO_ATLAS_INFO', 1)]
      libraries = ['blas', 'blas']
      library_dirs = ['/usr/lib64']
  
  non-existing path in 'numpy/distutils': 'site.cfg'
  F2PY Version 2
  lapack_opt_info:
  openblas_lapack_info:
    libraries openblas not found in ['/usr/local/lib64', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']
    NOT AVAILABLE
  
  lapack_mkl_info:
  mkl_info:
    libraries mkl,vml,guide not found in ['/usr/local/lib64', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']
    NOT AVAILABLE
  
    NOT AVAILABLE
  
  atlas_3_10_threads_info:
  Setting PTATLAS=ATLAS
    libraries tatlas,tatlas not found in /usr/local/lib64
    libraries lapack_atlas not found in /usr/local/lib64
    libraries tatlas,tatlas not found in /usr/local/lib
    libraries lapack_atlas not found in /usr/local/lib
    libraries tatlas,tatlas not found in /usr/lib64/sse2
    libraries lapack_atlas not found in /usr/lib64/sse2
    libraries tatlas,tatlas not found in /usr/lib64
    libraries lapack_atlas not found in /usr/lib64
    libraries tatlas,tatlas not found in /usr/lib/sse2
    libraries lapack_atlas not found in /usr/lib/sse2
    libraries tatlas,tatlas not found in /usr/lib
    libraries lapack_atlas not found in /usr/lib
    libraries tatlas,tatlas not found in /usr/lib/sse2
    libraries lapack_atlas not found in /usr/lib/sse2
    libraries tatlas,tatlas not found in /usr/lib/
    libraries lapack_atlas not found in /usr/lib/
  <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
    NOT AVAILABLE
  
  atlas_3_10_info:
    libraries satlas,satlas not found in /usr/local/lib64
    libraries lapack_atlas not found in /usr/local/lib64
    libraries satlas,satlas not found in /usr/local/lib
    libraries lapack_atlas not found in /usr/local/lib
    libraries satlas,satlas not found in /usr/lib64/sse2
    libraries lapack_atlas not found in /usr/lib64/sse2
    libraries satlas,satlas not found in /usr/lib64
    libraries lapack_atlas not found in /usr/lib64
    libraries satlas,satlas not found in /usr/lib/sse2
    libraries lapack_atlas not found in /usr/lib/sse2
    libraries satlas,satlas not found in /usr/lib
    libraries lapack_atlas not found in /usr/lib
    libraries satlas,satlas not found in /usr/lib/sse2
    libraries lapack_atlas not found in /usr/lib/sse2
    libraries satlas,satlas not found in /usr/lib/
    libraries lapack_atlas not found in /usr/lib/
  <class 'numpy.distutils.system_info.atlas_3_10_info'>
    NOT AVAILABLE
  
  atlas_threads_info:
  Setting PTATLAS=ATLAS
    libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib64
    libraries lapack_atlas not found in /usr/local/lib64
    libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib
    libraries lapack_atlas not found in /usr/local/lib
    libraries ptf77blas,ptcblas,atlas not found in /usr/lib64/sse2
    libraries lapack_atlas not found in /usr/lib64/sse2
    libraries ptf77blas,ptcblas,atlas not found in /usr/lib64
    libraries lapack_atlas not found in /usr/lib64
    libraries ptf77blas,ptcblas,atlas not found in /usr/lib/sse2
    libraries lapack_atlas not found in /usr/lib/sse2
    libraries ptf77blas,ptcblas,atlas not found in /usr/lib
    libraries lapack_atlas not found in /usr/lib
    libraries ptf77blas,ptcblas,atlas not found in /usr/lib/sse2
    libraries lapack_atlas not found in /usr/lib/sse2
    libraries ptf77blas,ptcblas,atlas not found in /usr/lib/
    libraries lapack_atlas not found in /usr/lib/
  <class 'numpy.distutils.system_info.atlas_threads_info'>
    NOT AVAILABLE
  
  atlas_info:
    libraries f77blas,cblas,atlas not found in /usr/local/lib64
    libraries lapack_atlas not found in /usr/local/lib64
    libraries f77blas,cblas,atlas not found in /usr/local/lib
    libraries lapack_atlas not found in /usr/local/lib
    libraries f77blas,cblas,atlas not found in /usr/lib64/sse2
    libraries lapack_atlas not found in /usr/lib64/sse2
    libraries f77blas,cblas,atlas not found in /usr/lib64
    libraries lapack_atlas not found in /usr/lib64
    libraries f77blas,cblas,atlas not found in /usr/lib/sse2
    libraries lapack_atlas not found in /usr/lib/sse2
    libraries f77blas,cblas,atlas not found in /usr/lib
    libraries lapack_atlas not found in /usr/lib
    libraries f77blas,cblas,atlas not found in /usr/lib/sse2
    libraries lapack_atlas not found in /usr/lib/sse2
    libraries f77blas,cblas,atlas not found in /usr/lib/
    libraries lapack_atlas not found in /usr/lib/
  <class 'numpy.distutils.system_info.atlas_info'>
    NOT AVAILABLE
  
  lapack_info:
    libraries lapack not found in ['', '']
  Runtime library lapack was not found. Ignoring
    FOUND:
      libraries = ['lapack', 'lapack']
      library_dirs = ['/usr/lib64']
      language = f77
  
    FOUND:
      define_macros = [('NO_ATLAS_INFO', 1)]
      libraries = ['lapack', 'lapack', 'blas', 'blas']
      library_dirs = ['/usr/lib64']
      language = f77
  
  running bdist_wheel
  running build
  running config_cc
  unifing config_cc, config, build_clib, build_ext, build commands --compiler options
  running config_fc
  unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
  running build_src
  build_src
  building py_modules sources
  creating build
  creating build/src.linux-x86_64-3.4
  creating build/src.linux-x86_64-3.4/numpy
  creating build/src.linux-x86_64-3.4/numpy/distutils
  building library "npymath" sources
  customize Gnu95FCompiler
  Found executable /usr/bin/gfortran
  customize Gnu95FCompiler
  customize Gnu95FCompiler using config
  C compiler: gcc -pthread -Wno-unused-result -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC
  
  compile options: '-Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/usr/include/python3.4m -c'
  gcc: _configtest.c
  gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No such file or directory
  gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No such file or directory
  failure.
  removing: _configtest.c _configtest.o
  Running from numpy source directory.
  /tmp/pip-build-vtpn0vsk/numpy/numpy/distutils/system_info.py:1646: UserWarning:
      Atlas (http://math-atlas.sourceforge.net/) libraries not found.
      Directories to search for the libraries can be specified in the
      numpy/distutils/site.cfg file (section [atlas]) or by setting
      the ATLAS environment variable.
    warnings.warn(AtlasNotFoundError.__doc__)
  /tmp/pip-build-vtpn0vsk/numpy/numpy/distutils/system_info.py:1548: UserWarning:
      Atlas (http://math-atlas.sourceforge.net/) libraries not found.
      Directories to search for the libraries can be specified in the
      numpy/distutils/site.cfg file (section [atlas]) or by setting
      the ATLAS environment variable.
    warnings.warn(AtlasNotFoundError.__doc__)
  /usr/lib64/python3.4/distutils/dist.py:260: UserWarning: Unknown distribution option: 'define_macros'
    warnings.warn(msg)
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-vtpn0vsk/numpy/setup.py", line 386, in <module>
      setup_package()
    File "/tmp/pip-build-vtpn0vsk/numpy/setup.py", line 378, in setup_package
      setup(**metadata)
    File "/tmp/pip-build-vtpn0vsk/numpy/numpy/distutils/core.py", line 169, in setup
      return old_setup(**new_attr)
    File "/usr/lib64/python3.4/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib64/python3.4/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/lib64/python3.4/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.4/site-packages/wheel/bdist_wheel.py", line 179, in run
      self.run_command('build')
    File "/usr/lib64/python3.4/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib64/python3.4/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-vtpn0vsk/numpy/numpy/distutils/command/build.py", line 47, in run
      old_build.run(self)
    File "/usr/lib64/python3.4/distutils/command/build.py", line 126, in run
      self.run_command(cmd_name)
    File "/usr/lib64/python3.4/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib64/python3.4/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-vtpn0vsk/numpy/numpy/distutils/command/build_src.py", line 147, in run
      self.build_sources()
    File "/tmp/pip-build-vtpn0vsk/numpy/numpy/distutils/command/build_src.py", line 158, in build_sources
      self.build_library_sources(*libname_info)
    File "/tmp/pip-build-vtpn0vsk/numpy/numpy/distutils/command/build_src.py", line 293, in build_library_sources
      sources = self.generate_sources(sources, (lib_name, build_info))
    File "/tmp/pip-build-vtpn0vsk/numpy/numpy/distutils/command/build_src.py", line 376, in generate_sources
      source = func(extension, build_dir)
    File "numpy/core/setup.py", line 654, in get_mathlib_info
      raise RuntimeError("Broken toolchain: cannot link a simple C program")
  RuntimeError: Broken toolchain: cannot link a simple C program
  
  ----------------------------------------
Failed to build numpy
Installing collected packages: numpy, tensorflow, setuptools
  Running setup.py install for numpy
    Complete output from command /usr/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip-build-vtpn0vsk/numpy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-ong2pih1-record/install-record.txt --single-version-externally-managed --compile:
    
    Note: if you need reliable uninstall behavior, then install
    with pip instead of using `setup.py install`:
    
      - `pip install .`       (from a git repo or downloaded source
                               release)
      - `pip install numpy`   (last Numpy release on PyPi)
    
    
    blas_opt_info:
    blas_mkl_info:
      libraries mkl,vml,guide not found in ['/usr/local/lib64', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']
      NOT AVAILABLE
    
    openblas_info:
      libraries openblas not found in ['/usr/local/lib64', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']
      NOT AVAILABLE
    
    atlas_3_10_blas_threads_info:
    Setting PTATLAS=ATLAS
      libraries tatlas not found in ['/usr/local/lib64', '/usr/local/lib', '/usr/lib64/sse2', '/usr/lib64', '/usr/lib/sse2', '/usr/lib', '/usr/lib/sse2', '/usr/lib/']
      NOT AVAILABLE
    
    atlas_3_10_blas_info:
      libraries satlas not found in ['/usr/local/lib64', '/usr/local/lib', '/usr/lib64/sse2', '/usr/lib64', '/usr/lib/sse2', '/usr/lib', '/usr/lib/sse2', '/usr/lib/']
      NOT AVAILABLE
    
    atlas_blas_threads_info:
    Setting PTATLAS=ATLAS
      libraries ptf77blas,ptcblas,atlas not found in ['/usr/local/lib64', '/usr/local/lib', '/usr/lib64/sse2', '/usr/lib64', '/usr/lib/sse2', '/usr/lib', '/usr/lib/sse2', '/usr/lib/']
      NOT AVAILABLE
    
    atlas_blas_info:
      libraries f77blas,cblas,atlas not found in ['/usr/local/lib64', '/usr/local/lib', '/usr/lib64/sse2', '/usr/lib64', '/usr/lib/sse2', '/usr/lib', '/usr/lib/sse2', '/usr/lib/']
      NOT AVAILABLE
    
    blas_info:
    customize UnixCCompiler
    C compiler: gcc -pthread -Wno-unused-result -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC
    
    creating /tmp/tmpf19ke2cs/tmp
    creating /tmp/tmpf19ke2cs/tmp/tmpf19ke2cs
    compile options: '-I/usr/local/include -I/usr/include -c'
    gcc: /tmp/tmpf19ke2cs/source.c
    gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No such file or directory
    gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No such file or directory
      libraries blas not found in ['', '']
    Runtime library blas was not found. Ignoring
      FOUND:
        libraries = ['blas', 'blas']
        library_dirs = ['/usr/lib64']
    
      FOUND:
        libraries = ['blas', 'blas']
        define_macros = [('NO_ATLAS_INFO', 1)]
        library_dirs = ['/usr/lib64']
    
    non-existing path in 'numpy/distutils': 'site.cfg'
    F2PY Version 2
    lapack_opt_info:
    openblas_lapack_info:
      libraries openblas not found in ['/usr/local/lib64', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']
      NOT AVAILABLE
    
    lapack_mkl_info:
    mkl_info:
      libraries mkl,vml,guide not found in ['/usr/local/lib64', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']
      NOT AVAILABLE
    
      NOT AVAILABLE
    
    atlas_3_10_threads_info:
    Setting PTATLAS=ATLAS
      libraries tatlas,tatlas not found in /usr/local/lib64
      libraries lapack_atlas not found in /usr/local/lib64
      libraries tatlas,tatlas not found in /usr/local/lib
      libraries lapack_atlas not found in /usr/local/lib
      libraries tatlas,tatlas not found in /usr/lib64/sse2
      libraries lapack_atlas not found in /usr/lib64/sse2
      libraries tatlas,tatlas not found in /usr/lib64
      libraries lapack_atlas not found in /usr/lib64
      libraries tatlas,tatlas not found in /usr/lib/sse2
      libraries lapack_atlas not found in /usr/lib/sse2
      libraries tatlas,tatlas not found in /usr/lib
      libraries lapack_atlas not found in /usr/lib
      libraries tatlas,tatlas not found in /usr/lib/sse2
      libraries lapack_atlas not found in /usr/lib/sse2
      libraries tatlas,tatlas not found in /usr/lib/
      libraries lapack_atlas not found in /usr/lib/
    <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
      NOT AVAILABLE
    
    atlas_3_10_info:
      libraries satlas,satlas not found in /usr/local/lib64
      libraries lapack_atlas not found in /usr/local/lib64
      libraries satlas,satlas not found in /usr/local/lib
      libraries lapack_atlas not found in /usr/local/lib
      libraries satlas,satlas not found in /usr/lib64/sse2
      libraries lapack_atlas not found in /usr/lib64/sse2
      libraries satlas,satlas not found in /usr/lib64
      libraries lapack_atlas not found in /usr/lib64
      libraries satlas,satlas not found in /usr/lib/sse2
      libraries lapack_atlas not found in /usr/lib/sse2
      libraries satlas,satlas not found in /usr/lib
      libraries lapack_atlas not found in /usr/lib
      libraries satlas,satlas not found in /usr/lib/sse2
      libraries lapack_atlas not found in /usr/lib/sse2
      libraries satlas,satlas not found in /usr/lib/
      libraries lapack_atlas not found in /usr/lib/
    <class 'numpy.distutils.system_info.atlas_3_10_info'>
      NOT AVAILABLE
    
    atlas_threads_info:
    Setting PTATLAS=ATLAS
      libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib64
      libraries lapack_atlas not found in /usr/local/lib64
      libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib
      libraries lapack_atlas not found in /usr/local/lib
      libraries ptf77blas,ptcblas,atlas not found in /usr/lib64/sse2
      libraries lapack_atlas not found in /usr/lib64/sse2
      libraries ptf77blas,ptcblas,atlas not found in /usr/lib64
      libraries lapack_atlas not found in /usr/lib64
      libraries ptf77blas,ptcblas,atlas not found in /usr/lib/sse2
      libraries lapack_atlas not found in /usr/lib/sse2
      libraries ptf77blas,ptcblas,atlas not found in /usr/lib
      libraries lapack_atlas not found in /usr/lib
      libraries ptf77blas,ptcblas,atlas not found in /usr/lib/sse2
      libraries lapack_atlas not found in /usr/lib/sse2
      libraries ptf77blas,ptcblas,atlas not found in /usr/lib/
      libraries lapack_atlas not found in /usr/lib/
    <class 'numpy.distutils.system_info.atlas_threads_info'>
      NOT AVAILABLE
    
    atlas_info:
      libraries f77blas,cblas,atlas not found in /usr/local/lib64
      libraries lapack_atlas not found in /usr/local/lib64
      libraries f77blas,cblas,atlas not found in /usr/local/lib
      libraries lapack_atlas not found in /usr/local/lib
      libraries f77blas,cblas,atlas not found in /usr/lib64/sse2
      libraries lapack_atlas not found in /usr/lib64/sse2
      libraries f77blas,cblas,atlas not found in /usr/lib64
      libraries lapack_atlas not found in /usr/lib64
      libraries f77blas,cblas,atlas not found in /usr/lib/sse2
      libraries lapack_atlas not found in /usr/lib/sse2
      libraries f77blas,cblas,atlas not found in /usr/lib
      libraries lapack_atlas not found in /usr/lib
      libraries f77blas,cblas,atlas not found in /usr/lib/sse2
      libraries lapack_atlas not found in /usr/lib/sse2
      libraries f77blas,cblas,atlas not found in /usr/lib/
      libraries lapack_atlas not found in /usr/lib/
    <class 'numpy.distutils.system_info.atlas_info'>
      NOT AVAILABLE
    
    lapack_info:
      libraries lapack not found in ['', '']
    Runtime library lapack was not found. Ignoring
      FOUND:
        libraries = ['lapack', 'lapack']
        library_dirs = ['/usr/lib64']
        language = f77
    
      FOUND:
        libraries = ['lapack', 'lapack', 'blas', 'blas']
        define_macros = [('NO_ATLAS_INFO', 1)]
        library_dirs = ['/usr/lib64']
        language = f77
    
    running install
    running build
    running config_cc
    unifing config_cc, config, build_clib, build_ext, build commands --compiler options
    running config_fc
    unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
    running build_src
    build_src
    building py_modules sources
    building library "npymath" sources
    customize Gnu95FCompiler
    Found executable /usr/bin/gfortran
    customize Gnu95FCompiler
    customize Gnu95FCompiler using config
    C compiler: gcc -pthread -Wno-unused-result -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC
    
    compile options: '-Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/usr/include/python3.4m -c'
    gcc: _configtest.c
    gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No such file or directory
    gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No such file or directory
    failure.
    removing: _configtest.c _configtest.o
    Running from numpy source directory.
    /tmp/pip-build-vtpn0vsk/numpy/numpy/distutils/system_info.py:1646: UserWarning:
        Atlas (http://math-atlas.sourceforge.net/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [atlas]) or by setting
        the ATLAS environment variable.
      warnings.warn(AtlasNotFoundError.__doc__)
    /tmp/pip-build-vtpn0vsk/numpy/numpy/distutils/system_info.py:1548: UserWarning:
        Atlas (http://math-atlas.sourceforge.net/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [atlas]) or by setting
        the ATLAS environment variable.
      warnings.warn(AtlasNotFoundError.__doc__)
    /usr/lib64/python3.4/distutils/dist.py:260: UserWarning: Unknown distribution option: 'define_macros'
      warnings.warn(msg)
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-vtpn0vsk/numpy/setup.py", line 386, in <module>
        setup_package()
      File "/tmp/pip-build-vtpn0vsk/numpy/setup.py", line 378, in setup_package
        setup(**metadata)
      File "/tmp/pip-build-vtpn0vsk/numpy/numpy/distutils/core.py", line 169, in setup
        return old_setup(**new_attr)
      File "/usr/lib64/python3.4/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib64/python3.4/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib64/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-vtpn0vsk/numpy/numpy/distutils/command/install.py", line 62, in run
        r = self.setuptools_run()
      File "/tmp/pip-build-vtpn0vsk/numpy/numpy/distutils/command/install.py", line 36, in setuptools_run
        return distutils_install.run(self)
      File "/usr/lib64/python3.4/distutils/command/install.py", line 539, in run
        self.run_command('build')
      File "/usr/lib64/python3.4/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib64/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-vtpn0vsk/numpy/numpy/distutils/command/build.py", line 47, in run
        old_build.run(self)
      File "/usr/lib64/python3.4/distutils/command/build.py", line 126, in run
        self.run_command(cmd_name)
      File "/usr/lib64/python3.4/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib64/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-vtpn0vsk/numpy/numpy/distutils/command/build_src.py", line 147, in run
        self.build_sources()
      File "/tmp/pip-build-vtpn0vsk/numpy/numpy/distutils/command/build_src.py", line 158, in build_sources
        self.build_library_sources(*libname_info)
      File "/tmp/pip-build-vtpn0vsk/numpy/numpy/distutils/command/build_src.py", line 293, in build_library_sources
        sources = self.generate_sources(sources, (lib_name, build_info))
      File "/tmp/pip-build-vtpn0vsk/numpy/numpy/distutils/command/build_src.py", line 376, in generate_sources
        source = func(extension, build_dir)
      File "numpy/core/setup.py", line 654, in get_mathlib_info
        raise RuntimeError("Broken toolchain: cannot link a simple C program")
    RuntimeError: Broken toolchain: cannot link a simple C program
    
    ----------------------------------------

Well, I also installed blas-devel and lapack-devel. 
Thanks for your help.

**Comment by GauAnhViDai** [comment]
Done. I just need to install numpy from dnf.
