### ISSUE TITLE
No module named '_pywrap_tensorflow_internal'

### ISSUE THREAD

**Issue by gcovillo** [tensorflow/tensorflow#37906]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

_**System information**_
**- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):** Windows 10
**- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:** No
**- TensorFlow installed from (source or binary):** python -m pip install --upgrade https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.12.0-py3-none-any.whl
(doing a regular pip installation does not work for me)
- **TensorFlow version:** 1.12.0
- **Python** version: 3.6.0
- **Installed using virtualenv? pip? conda?**: pip
- **Bazel version (if compiling from source):** ?? I dont think I have this
- **GCC/Compiler version (if compiling from source):** ?? I dont think I have this
- **CUDA/cuDNN version: ??** I dont think I have this
- **GPU model and memory:** None. I was told I could do this without a gpu. 

**Describe the problem**

I want to run DarkFlow. Specifically I want to run this: 
----------------------------------------------
from darkflow.net.build import TFNet

options = {"model": "cfg/yolo.cfg", 
           "load": "bin/yolo.weights", 
           "threshold": 0.1, 
           "gpu": 0.0}

tfnet = TFNet(options)
----------------------------------------------

**Provide the exact sequence of commands / steps that you executed before running into the problem**

1. I installed tensorflow in the aforementioned manner

2. I Tried to run the aforementioned code:

C:\Users\gcovillo\darkflow-master>python darkflowEx.py
Traceback (most recent call last):
  File "C:\Users\gcovillo\AppData\Local\Programs\Python\Python36-32\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tensorflow_internal', [dirname(__file__)])
  File "C:\Users\gcovillo\AppData\Local\Programs\Python\Python36-32\lib\imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gcovillo\AppData\Local\Programs\Python\Python36-32\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\gcovillo\AppData\Local\Programs\Python\Python36-32\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\gcovillo\AppData\Local\Programs\Python\Python36-32\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 20, in swig_import_helper
    import _pywrap_tensorflow_internal
ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "darkflowEx.py", line 2, in <module>
    from darkflow.net.build import TFNet
  File "C:\Users\gcovillo\darkflow-master\darkflow\net\build.py", line 1, in <module>
    import tensorflow as tf
  File "C:\Users\gcovillo\AppData\Local\Programs\Python\Python36-32\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\gcovillo\AppData\Local\Programs\Python\Python36-32\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\gcovillo\AppData\Local\Programs\Python\Python36-32\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\gcovillo\AppData\Local\Programs\Python\Python36-32\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tensorflow_internal', [dirname(__file__)])
  File "C:\Users\gcovillo\AppData\Local\Programs\Python\Python36-32\lib\imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gcovillo\AppData\Local\Programs\Python\Python36-32\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\gcovillo\AppData\Local\Programs\Python\Python36-32\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\gcovillo\AppData\Local\Programs\Python\Python36-32\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 20, in swig_import_helper
    import _pywrap_tensorflow_internal
ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errorshefor some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

Any Help would be appreciated. I know there is already a closed case with this but I really have no clue what that guy was saying.

**Comment by Saduf2019** [comment]
@gcovillo 
please refer to these existing [issues](https://github.com/tensorflow/tensorflow/issues/37863) on the same error faced

#36167 (comment)

#36167 #36151 #36138 #36054 #36045 #36020 #36003 #35988 #35903 #35880 #35865 #35805 #35789 #35773 #35772 #35767 #35766 #35749 #35721 #35618 #35204

**Comment by gcovillo** [comment]
@Saduf2019 Thank you. I thought I had checked most of these but found that I was running 32 bit instead of 64. This has led to an error about DLLS but I have downloaded Microsoft visual studio 2015 already.

Traceback (most recent call last):
  File "darkflowEx.py", line 2, in <module>
    from darkflow.net.build import TFNet
  File "C:\Users\gcovillo\darkflow-master\darkflow\net\build.py", line 1, in <module>
    import tensorflow as tf
  File "C:\Users\gcovillo\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\__init__.py", line 101, in <module>
    from tensorflow_core import *
  File "C:\Users\gcovillo\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_core\__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\gcovillo\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\Users\gcovillo\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "C:\Users\gcovillo\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\gcovillo\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_core\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\gcovillo\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 30, in <module>
    self_check.preload_check()
  File "C:\Users\gcovillo\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_core\python\platform\self_check.py", line 60, in preload_check
    % " or ".join(missing))
ImportError: Could not find the DLL(s) 'msvcp140.dll or msvcp140_1.dll'. TensorFlow requires that these DLLs be installed in a directory that is named in your %PATH% environment variable. You may install these DLLs by downloading "Microsoft C++ Redistributable for Visual Studio 2015, 2017 and 2019" for your platform from this URL: https://support.microsoft.com/help/2977003/the-latest-supported-visual-c-downloads

**Comment by gcovillo** [comment]
Traceback (most recent call last):
  File "darkflowEx.py", line 2, in <module>
    from darkflow.net.build import TFNet
  File "C:\Users\gcovillo\darkflow-master\darkflow\net\build.py", line 1, in <module>
    import tensorflow as tf
  File "C:\Users\gcovillo\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\__init__.py", line 101, in <module>
    from tensorflow_core import *
  File "C:\Users\gcovillo\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_core\__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\gcovillo\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\Users\gcovillo\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "C:\Users\gcovillo\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\gcovillo\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_core\python\__init__.py", line 64, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "C:\Users\gcovillo\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_core\core\framework\graph_pb2.py", line 7, in <module>
    from google.protobuf import descriptor as _descriptor
  File "C:\Users\gcovillo\AppData\Local\Programs\Python\Python36\lib\site-packages\google\protobuf\descriptor.py", line 47, in <module>
    from google.protobuf.pyext import _message
ImportError: DLL load failed: The specified procedure could not be found.


now its doing this.

**Comment by gcovillo** [comment]
C:\Users\gcovillo\darkflow-master>python darkflowEx.py
2020-03-26 10:50:43.178108: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-03-26 10:50:43.185108: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "darkflowEx.py", line 2, in <module>
    from darkflow.net.build import TFNet
  File "C:\Users\gcovillo\darkflow-master\darkflow\net\build.py", line 5, in <module>
    from .ops import op_create, identity
  File "C:\Users\gcovillo\darkflow-master\darkflow\net\ops\__init__.py", line 1, in <module>
    from .simple import *
  File "C:\Users\gcovillo\darkflow-master\darkflow\net\ops\simple.py", line 1, in <module>
    import tensorflow.contrib.slim as slim
ModuleNotFoundError: No module named 'tensorflow.contrib'

NEW ERROR!!!! This feels like a puzzle.

**Comment by gcovillo** [comment]
File "darkflowEx.py", line 2, in <module>
    from darkflow.net.build import TFNet
  File "C:\Users\gcovillo\darkflow-master\darkflow\net\build.py", line 7, in <module>
    from .framework import create_framework
  File "C:\Users\gcovillo\darkflow-master\darkflow\net\framework.py", line 1, in <module>
    from . import yolo
  File "C:\Users\gcovillo\darkflow-master\darkflow\net\yolo\__init__.py", line 2, in <module>
    from . import predict
  File "C:\Users\gcovillo\darkflow-master\darkflow\net\yolo\predict.py", line 7, in <module>
    from ...cython_utils.cy_yolo_findboxes import yolo_box_constructor
ModuleNotFoundError: No module named 'darkflow.cython_utils.cy_yolo_findboxes'

next error to solve

**Comment by gcovillo** [comment]
WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

WARNING:tensorflow:From C:\Users\gcovillo\darkflow-master\darkflow\net\build.py:15: The name tf.train.RMSPropOptimizer is deprecated. Please use tf.compat.v1.train.RMSPropOptimizer instead.

WARNING:tensorflow:From C:\Users\gcovillo\darkflow-master\darkflow\net\build.py:16: The name tf.train.AdadeltaOptimizer is deprecated. Please use tf.compat.v1.train.AdadeltaOptimizer instead.

WARNING:tensorflow:From C:\Users\gcovillo\darkflow-master\darkflow\net\build.py:17: The name tf.train.AdagradOptimizer is deprecated. Please use tf.compat.v1.train.AdagradOptimizer instead.

WARNING:tensorflow:From C:\Users\gcovillo\darkflow-master\darkflow\net\build.py:18: The name tf.train.AdagradDAOptimizer is deprecated. Please use tf.compat.v1.train.AdagradDAOptimizer instead.

WARNING:tensorflow:From C:\Users\gcovillo\darkflow-master\darkflow\net\build.py:19: The name tf.train.MomentumOptimizer is deprecated. Please use tf.compat.v1.train.MomentumOptimizer instead.

WARNING:tensorflow:From C:\Users\gcovillo\darkflow-master\darkflow\net\build.py:20: The name tf.train.AdamOptimizer is deprecated. Please use tf.compat.v1.train.AdamOptimizer instead.

WARNING:tensorflow:From C:\Users\gcovillo\darkflow-master\darkflow\net\build.py:21: The name tf.train.FtrlOptimizer is deprecated. Please use tf.compat.v1.train.FtrlOptimizer instead.

WARNING:tensorflow:From C:\Users\gcovillo\darkflow-master\darkflow\net\build.py:22: The name tf.train.GradientDescentOptimizer is deprecated. Please use tf.compat.v1.train.GradientDescentOptimizer instead.

Traceback (most recent call last):
  File "darkflowEx.py", line 9, in <module>
    tfnet = TFNet(options)
  File "C:\Users\gcovillo\darkflow-master\darkflow\net\build.py", line 58, in __init__
    darknet = Darknet(FLAGS)
  File "C:\Users\gcovillo\darkflow-master\darkflow\dark\darknet.py", line 13, in __init__
    self.get_weight_src(FLAGS)
  File "C:\Users\gcovillo\darkflow-master\darkflow\dark\darknet.py", line 47, in get_weight_src
    '{} not found'.format(FLAGS.load)
AssertionError: bin/yolo.weights not found

yay! were getting closer!

**Comment by gcovillo** [comment]
Took this issue to this: 

https://github.com/thtrieu/darkflow/issues/1155
