### ISSUE TITLE
Python 2 pip install fails with CERTIFICATE_VERIFY_FAILED - fixed by using http instead of https

### ISSUE THREAD

**Issue by jay-johnson** [tensorflow/tensorflow#3791]
GitHub issues are for bugs / installation problems / feature requests.  
For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System:

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

If installed from binary pip package, provide:

1. Which pip package you installed. 

The install is failing from CentOS 7 with:
```
Step 10 : RUN pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.10.0rc0-cp27-none-linux_x86_64.whl
 ---> Running in 882f8c6e9398
Collecting tensorflow==0.10.0rc0 from https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.10.0rc0-cp27-none-linux_x86_64.whl
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/site-packages/pip/commands/install.py", line 299, in run
    requirement_set.prepare_files(finder)
  File "/usr/lib/python2.7/site-packages/pip/req/req_set.py", line 370, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/site-packages/pip/req/req_set.py", line 587, in _prepare_file
    session=self.session, hashes=hashes)
  File "/usr/lib/python2.7/site-packages/pip/download.py", line 810, in unpack_url
    hashes=hashes
  File "/usr/lib/python2.7/site-packages/pip/download.py", line 649, in unpack_http_url
    hashes)
  File "/usr/lib/python2.7/site-packages/pip/download.py", line 842, in _download_http_url
    stream=True,
  File "/usr/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 487, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/site-packages/pip/download.py", line 378, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/pip/_vendor/cachecontrol/adapter.py", line 46, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/usr/lib/python2.7/site-packages/pip/_vendor/requests/adapters.py", line 477, in send
    raise SSLError(e, request=request)
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:765)
```

2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

If installed from source, provide 

Tensorflow was not installed.

### Steps to reproduce
1. 
```pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.10.0rc0-cp27-none-linux_x86_64.whl```

### What have you tried?
1. The fix for me was to use **http://** instead of **https://**

```
Step 10 : RUN pip install --upgrade http://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.10.0rc0-cp27-none-linux_x86_64.whl
 ---> Running in 064f19cad960
Collecting tensorflow==0.10.0rc0 from http://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.10.0rc0-cp27-none-linux_x86_64.whl
  Downloading http://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.10.0rc0-cp27-none-linux_x86_64.whl (33.3MB)
Requirement already up-to-date: six>=1.10.0 in /usr/lib/python2.7/site-packages (from tensorflow==0.10.0rc0)
Collecting protobuf==3.0.0b2 (from tensorflow==0.10.0rc0)
  Downloading protobuf-3.0.0b2-py2.py3-none-any.whl (326kB)
Collecting wheel (from tensorflow==0.10.0rc0)
  Downloading wheel-0.29.0-py2.py3-none-any.whl (66kB)
Collecting mock>=2.0.0 (from tensorflow==0.10.0rc0)
  Downloading mock-2.0.0-py2.py3-none-any.whl (56kB)
Requirement already up-to-date: numpy>=1.8.2 in /usr/lib64/python2.7/site-packages (from tensorflow==0.10.0rc0)
Requirement already up-to-date: setuptools in /usr/lib/python2.7/site-packages (from protobuf==3.0.0b2->tensorflow==0.10.0rc0)
Requirement already up-to-date: funcsigs>=1; python_version < "3.3" in /usr/lib/python2.7/site-packages (from mock>=2.0.0->tensorflow==0.10.0rc0)
Requirement already up-to-date: pbr>=0.11 in /usr/lib/python2.7/site-packages (from mock>=2.0.0->tensorflow==0.10.0rc0)
Installing collected packages: protobuf, wheel, mock, tensorflow
Successfully installed mock-2.0.0 protobuf-3.0.0b2 tensorflow-0.10.0rc0 wheel-0.29.0
 ---> a374951fbf58
```

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

**Comment by jay-johnson** [comment]
Some more debugging help:

```
$ openssl s_client -connect storage.googleapis.com:443
CONNECTED(00000003)
139978079770488:error:140790E5:SSL routines:SSL23_WRITE:ssl handshake failure:s23_lib.c:184:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 207 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
---
```

**Comment by aselle** [comment]
This is not a TensorFlow problem, it is a problem with pip's configuration (possibly specifically to CentOS). you can fix it by telling it to use the openssl certificate authorites. Googling the error yields:

http://stackoverflow.com/questions/19377045/pip-cert-failed-but-curl-works
http://stackoverflow.com/questions/32772895/python-pip-install-error-ssl-certificate-verify-failed

I wouldn't recommend using http instead of https as then pip will not authenticate the package source.

**Comment by jay-johnson** [comment]
For those looking in the future it's not a pip problem. 

It was the cert on storage.googleapis.com failing. 

Looks good now: 

```
$ openssl s_client -connect storage.googleapis.com:443
CONNECTED(00000003)
depth=3 C = US, O = Equifax, OU = Equifax Secure Certificate Authority
verify return:1
depth=2 C = US, O = GeoTrust Inc., CN = GeoTrust Global CA
verify return:1
depth=1 C = US, O = Google Inc, CN = Google Internet Authority G2
verify return:1
depth=0 C = US, ST = California, L = Mountain View, O = Google Inc, CN = *.storage.googleapis.com
verify return:1
---
Certificate chain
 0 s:/C=US/ST=California/L=Mountain View/O=Google Inc/CN=*.storage.googleapis.com
   i:/C=US/O=Google Inc/CN=Google Internet Authority G2
 1 s:/C=US/O=Google Inc/CN=Google Internet Authority G2
   i:/C=US/O=GeoTrust Inc./CN=GeoTrust Global CA
 2 s:/C=US/O=GeoTrust Inc./CN=GeoTrust Global CA
   i:/C=US/O=Equifax/OU=Equifax Secure Certificate Authority
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIGAjCCBOqgAwIBAgIIbtC8GTXuml0wDQYJKoZIhvcNAQELBQAwSTELMAkGA1UE
BhMCVVMxEzARBgNVBAoTCkdvb2dsZSBJbmMxJTAjBgNVBAMTHEdvb2dsZSBJbnRl
cm5ldCBBdXRob3JpdHkgRzIwHhcNMTYwODEwMTgxMjAwWhcNMTYxMTAyMTgxMjAw
WjByMQswCQYDVQQGEwJVUzETMBEGA1UECAwKQ2FsaWZvcm5pYTEWMBQGA1UEBwwN
TW91bnRhaW4gVmlldzETMBEGA1UECgwKR29vZ2xlIEluYzEhMB8GA1UEAwwYKi5z
dG9yYWdlLmdvb2dsZWFwaXMuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB
CgKCAQEApxdcD3TrOd56MqMq2LTdddTuoNW5eLFSLVm25zmQj70UX99RxnG9q+A1
GDPU4iB+AHSxn8DJUHVatqKBsGgsBEYEmM7fcCEhZG7eDC+l+hv6VqESI620wCm2
OkigokFNMVcJKPW21rVI8hQUZNw+OQHZOKccOQ7F9hLjOlDi999M6UJOgnhUv8cx
5HGJMCKtKW7e0fz94Tc7D04xUDwhI2TisrIAGFKX5KrrfbrEu4MQYwNDe6CtttYV
fADFng8PEBu4BpeqYolt5ehRf0O5gRtb7NUX8hKHA/xMg3qfouVXvUlRR8qXl5Zm
bF9QzjSFtsPgHgZxM/n3WBm+/9xYtQIDAQABo4ICwzCCAr8wHQYDVR0lBBYwFAYI
KwYBBQUHAwEGCCsGAQUFBwMCMIIBjwYDVR0RBIIBhjCCAYKCGCouc3RvcmFnZS5n
b29nbGVhcGlzLmNvbYIiKi5jb21tb25kYXRhc3RvcmFnZS5nb29nbGVhcGlzLmNv
bYIpKi5jb250ZW50LXN0b3JhZ2UtZG93bmxvYWQuZ29vZ2xlYXBpcy5jb22CJyou
Y29udGVudC1zdG9yYWdlLXVwbG9hZC5nb29nbGVhcGlzLmNvbYIgKi5jb250ZW50
LXN0b3JhZ2UuZ29vZ2xlYXBpcy5jb22CECouZ29vZ2xlYXBpcy5jb22CISouc3Rv
cmFnZS1kb3dubG9hZC5nb29nbGVhcGlzLmNvbYIfKi5zdG9yYWdlLXVwbG9hZC5n
b29nbGVhcGlzLmNvbYIgY29tbW9uZGF0YXN0b3JhZ2UuZ29vZ2xlYXBpcy5jb22C
K3N0YXRpYy5wYW5vcmFtaW8uY29tLnN0b3JhZ2UuZ29vZ2xlYXBpcy5jb22CFnN0
b3JhZ2UuZ29vZ2xlYXBpcy5jb22CD3VuZmlsdGVyZWQubmV3czBoBggrBgEFBQcB
AQRcMFowKwYIKwYBBQUHMAKGH2h0dHA6Ly9wa2kuZ29vZ2xlLmNvbS9HSUFHMi5j
cnQwKwYIKwYBBQUHMAGGH2h0dHA6Ly9jbGllbnRzMS5nb29nbGUuY29tL29jc3Aw
HQYDVR0OBBYEFO8YwVjvG+7IvdYxN/ZYXZObx5+/MAwGA1UdEwEB/wQCMAAwHwYD
VR0jBBgwFoAUSt0GFhu89mi1dvWBtrtiGrpagS8wIQYDVR0gBBowGDAMBgorBgEE
AdZ5AgUBMAgGBmeBDAECAjAwBgNVHR8EKTAnMCWgI6Ahhh9odHRwOi8vcGtpLmdv
b2dsZS5jb20vR0lBRzIuY3JsMA0GCSqGSIb3DQEBCwUAA4IBAQBNGzfnlGPD8MRc
PVsH7eIjVLIVLJbKIA0q5q5WNhweUcEvz5Q1TJ4reTivVukLwn2JAqOL6oFm5+Aq
2Ofc+1/GWLW2TXHXrPx+sw/RXIbgolallVnfqzArMrr/Nb3NU8FtLw03CIRuoOiV
7EBNAROdVxN+PDGt9xFiNEwSdhnMcBZq9xHeWDQM0AoST+N6Wx+RiaHv9EAvRN8z
olU+S33j4L29k8MuELyDMt6aVeKxh3YtF7PyN9G+54Wr3y2Ul7NUB5IfS6c/6QW1
1QRjmwA06yi0b3hOLJj3JHyB7aPBEES2JTo04aYCopYgd/eBRiW/mDW/Nz5bO3UP
i0onAvuz
-----END CERTIFICATE-----
subject=/C=US/ST=California/L=Mountain View/O=Google Inc/CN=*.storage.googleapis.com
issuer=/C=US/O=Google Inc/CN=Google Internet Authority G2
---
No client certificate CA names sent
Server Temp Key: ECDH, prime256v1, 256 bits
---
SSL handshake has read 4113 bytes and written 333 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES128-GCM-SHA256
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES128-GCM-SHA256
    Session-ID: 6B5BF03E3F6362912A14AFA0C5ABF9D9DA9E93F49937ACDB715FD3576FAD0AF4
    Session-ID-ctx: 
    Master-Key: B023D51CECAA588515119296C4C564673844E312EAAD5CD93D13867E5F2C29AC7E536A056C91038C0918CCB622F5196B
    Key-Arg   : None
    Krb5 Principal: None
    PSK identity: None
    PSK identity hint: None
    TLS session ticket lifetime hint: 100800 (seconds)
    TLS session ticket:
    0000 - c2 77 a0 2d ce 0a c3 c0-9a 5e 7a 43 69 32 a7 74   .w.-.....^zCi2.t
    0010 - 9e f6 b3 2c aa ba 02 bf-e1 af 5b 89 34 c4 7d 2b   ...,......[.4.}+
    0020 - ca 90 28 b7 6a 50 04 83-fb d9 14 6a 8a a6 b6 e8   ..(.jP.....j....
    0030 - 85 53 be 45 4d 64 fa 74-d4 5f 72 cc 5b e4 31 70   .S.EMd.t._r.[.1p
    0040 - 0d 9d bd df 1a c1 20 51-ad b5 34 3f 6c 94 67 c1   ...... Q..4?l.g.
    0050 - f7 7f f4 fa eb d2 e4 dc-6a 88 ab 3f c7 f4 95 37   ........j..?...7
    0060 - b4 73 47 2f ca 5d b9 e2-9a ef a2 7e 31 9d b5 3d   .sG/.].....~1..=
    0070 - a7 8c c1 a4 e2 ea 68 6a-94 a7 f3 30 86 a7 67 b7   ......hj...0..g.
    0080 - 6a 02 22 da 4d 4b 26 75-62 80 b7 a5 50 be 94 db   j.".MK&ub...P...
    0090 - fe 22 b8 68 a3 16 c0 a9-f9 17 c4 50 92 6e b2 04   .".h.......P.n..
    00a0 - c3 f7 57 df                                       ..W.

    Start Time: 1471559044
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---
```

**Comment by aselle** [comment]
Thanks for the post clarifying the issue. Sorry for misdirecting you!  Glad you got it to work.
