### ISSUE TITLE
Building TensorFlow Lite NNAPI with C/C++ for Android: runtime link error libnnapi_delegate.so not found

### ISSUE THREAD

**Issue by lackhole** [tensorflow/tensorflow#37928]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS 10.15.4
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Samsung Galaxy Fold, Samsung Galaxy S10, Oppo ... etc Android Devices
- TensorFlow installed from (source or binary): source
- TensorFlow version: latest (cloned 3 days ago)
- Python version: 2.7
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source): 2.0.0
- GCC/Compiler version (if compiling from source): Apple clang version 11.0.0 (clang-1100.0.33.17)
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**
I'm building TensorFlow Lite with C/C++ to run on Android devices. Building C, GPU delegate works well, but when I tried to link NNAPI delegate(```libnnapi_delegate.so```), library open fail on runtime.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
Got ```nnapi_delegate.so``` from
```
bazel build -c opt --config=android_arm64 //tensorflow/lite/delegates/nnapi:nnapi_delegate
```

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

### Error Log
```
2020-03-26 15:37:26.311 20452-20452/com.example.hellolibs E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.hellolibs, PID: 20452
    java.lang.UnsatisfiedLinkError: dlopen failed: library "/Users/yonggyulee/Documents/GitHub/AI-Kit/tflite/c/hello-libs/app/src/main/cpp/../../../../distribution/tflite/lib/arm64-v8a/libnnapi_delegate.so" not found
        at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
        at java.lang.System.loadLibrary(System.java:1669)
        at com.example.hellolibs.MainActivity.<clinit>(MainActivity.java:32)
        at java.lang.Class.newInstance(Native Method)
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:69)
        at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:41)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1219)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3040)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3292)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1980)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7168)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
```

### CMakeLists.txt
```
cmake_minimum_required(VERSION 3.4.1)

# configure import libs
set(distribution_DIR ${CMAKE_CURRENT_SOURCE_DIR}/../../../../distribution)

add_subdirectory("${CMAKE_CURRENT_SOURCE_DIR}/opencv")

add_library(lib_tflite SHARED IMPORTED)
set_target_properties(lib_tflite PROPERTIES IMPORTED_LOCATION
        ${distribution_DIR}/tflite/lib/arm64-v8a/libtensorflowlite_c.so)

add_library(lib_tflite_gpu SHARED IMPORTED)
set_target_properties(lib_tflite_gpu PROPERTIES IMPORTED_LOCATION
        ${distribution_DIR}/tflite/lib/arm64-v8a/libtensorflowlite_gpu_delegate.so)

add_library(lib_nnapi SHARED IMPORTED)
set_target_properties(lib_nnapi PROPERTIES IMPORTED_LOCATION
        ${distribution_DIR}/tflite/lib/arm64-v8a/libnnapi_delegate.so)

# build application's shared lib
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=gnu++11")

add_library(hello-libs SHARED
        hello-libs.cpp)

target_include_directories(hello-libs PRIVATE
        ${distribution_DIR}/tflite/include
        ${distribution_DIR}/tflite/include/tensorflow/lite/tools/make/downloads
        ${distribution_DIR}/tflite/include/tensorflow/lite/tools/make/downloads/flatbuffers/include
)

target_link_libraries(hello-libs
        android
        lib_tflite
        lib_tflite_gpu
        neuralnetworks
        lib_nnapi  # If i remove this line, there is no error, and everything including inference works well.
        opencv
        log)
```

**Comment by lackhole** [comment]
Solved with *static* library. But NNAPI delegate is slower than CPU or GPU.

**Comment by ymodak** [comment]
If the NNAPI delegate does not support some of the ops or parameter combinations in a model then it fallback on cpu for computing. This can cause it to execute slow performance than cpu.
See https://www.tensorflow.org/lite/performance/nnapi#use_supported_models_and_ops to know more.
I will close this issue since the original problem is solved. Thanks!
