### ISSUE TITLE
when using tensorflow inside flask server, I am getting localhost container not found error.

### ISSUE THREAD

**Issue by Kiranendra** [tensorflow/tensorflow#37943]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 7
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.15.0
- Python version: 3.7.6
- Installed using virtualenv? pip? conda?: pip in a virtual environment

**Describe the problem**

I am trying to make a flask server and deploy my model there and connect that server to my android application. Without deploying the model in the server, the flask server and android app are connected successfully. But, after writing my model code in the flask server it gives the following error:

-----------------------
2020-03-26 17:52:10.868137: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-03-26 17:52:10.868137: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      
2020-03-26 17:52:11.075640: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at resource_variable_ops.cc:660 : Not found: Container localhost does not exist. (Could not find resource: localhost/encoder_embedding/embeddings)
[2020-03-26 17:52:11,075] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "H:\PYTHON\Environments\Flask_env_PyCharm\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "H:\PYTHON\Environments\Flask_env_PyCharm\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "H:\PYTHON\Environments\Flask_env_PyCharm\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "H:\PYTHON\Environments\Flask_env_PyCharm\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "H:\PYTHON\Environments\Flask_env_PyCharm\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "H:\PYTHON\Environments\Flask_env_PyCharm\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "H:\PYTHON\PyCharm Projects\FlaskServer\app.py", line 302, in hello_world
    reply = convert("Hi")
  File "H:\PYTHON\PyCharm Projects\FlaskServer\app.py", line 267, in convert
    initial_state = model_encoder.predict(input_tokens)
  File "H:\PYTHON\Environments\Flask_env_PyCharm\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 908, in predict
    use_multiprocessing=use_multiprocessing)
  File "H:\PYTHON\Environments\Flask_env_PyCharm\lib\site-packages\tensorflow_core\python\keras\engine\training_arrays.py", line 723, in predict
    callbacks=callbacks)
  File "H:\PYTHON\Environments\Flask_env_PyCharm\lib\site-packages\tensorflow_core\python\keras\engine\training_arrays.py", line 394, in model_iteration
    batch_outs = f(ins_batch)
  File "H:\PYTHON\Environments\Flask_env_PyCharm\lib\site-packages\tensorflow_core\python\keras\backend.py", line 3476, in __call__
    run_metadata=self.run_metadata)
  File "H:\PYTHON\Environments\Flask_env_PyCharm\lib\site-packages\tensorflow_core\python\client\session.py", line 1472, in __call__
    run_metadata_ptr)
tensorflow.python.framework.errors_impl.NotFoundError: Container localhost does not exist. (Could not find resource: localhost/encoder_embedding/embeddings)
	 [[{{node encoder_embedding/embedding_lookup}}]]
127.0.0.1 - - [26/Mar/2020 17:52:11] "GET / HTTP/1.1" 500 -

-------------------------------

I opened an issue previously for ".tflite" conversion. But, as an alternative, I created a flask server. And now this is the only error I am facing. Before I tried with TensorFlow 2.0.0. But, as I had to use 3 or 4 lines of version 1 code, I installed 1.15.0.

P.S: This issue is related to this [issue](https://github.com/tensorflow/tensorflow/issues/30352). I've tried it in many ways. But, ultimately I face failure. Please, help me fix this error so that I could close both the issues. You need not worry about the responses or results of the trained model. 

--------

The code and dataset are in this file:
[code.zip](https://github.com/tensorflow/tensorflow/files/4387137/code.zip)

I am also placing my drive link for checkpoint files so that you need not train the model.
https://drive.google.com/open?id=1wdHQRGMMealZv2ygrSK5LKWGyNgxVNPT

**Comment by gowthamkpr** [comment]
This is duplicate of the issue #30352 Can you please take a look at this issue and let me know if it helps. Thanks!

**Comment by Kiranendra** [comment]
Yes, I also mentioned that I've tried it already. He used LSTM layers while I've used GRU layers. I also tried with graphs like him but, the outcome is only error.

**Comment by Kiranendra** [comment]
The issue was solved now. The duplicate issue was incomplete for mine. So, I followed [this](https://stackoverflow.com/questions/54652536/keras-tensorflow-backend-error-tensor-input-10-specified-in-either-feed-de) from StackOverflow and it worked.
