### ISSUE TITLE
AttributeError: 'ObjectDetectionResult' object has no attribute 'image_id'

### ISSUE THREAD

**Issue by Sicongzai** [tensorflow/tensorflow#37951]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04.4
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: None
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.15.2
- Python version: 3.6.2
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source) : 0.24.1
- GCC/Compiler version (if compiling from source): None
- CUDA/cuDNN version: None
- GPU model and memory: None

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

I try to evaluate my TensorFlow Lite model using the tool in https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/evaluation/tasks/coco_object_detection: But when I try to process the dataset, I met some problem. Firstly, I use t the large dataset and limited RAM of my computer. Then I used the 2017 val COCO dataset and not met the memory problem now. But I meet the problem:  AttributeError: 'ObjectDetectionResult' object has no attribute 'image_id'.

My code for running :
bazel run //tensorflow/lite/tools/evaluation/tasks/coco_object_detection:preprocess_coco_minival -- \
  --images_folder=/home/sicong/Documents/datasets/COCO/for_tflite_evaluation/val2014 \
  --instances_file=/home/sicong/Documents/datasets/COCO/annotations_trainval2017/annotations/instances_val2017.json \
  --whitelist_file=/home/sicong/Documents/datasets/udacity/Udacity_coco/image_id.txt \
  --output_folder=/home/sicong/Documents/datasets/COCO/for_tflite_evaluation \
  --num_images=1000

Error Information:
INFO: Build completed successfully, 305 total actions
Traceback (most recent call last):
  File "/home/sicong/.cache/bazel/_bazel_sicong/7b2e833de2ecb2ea31568e76c69b68a8/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/lite/tools/evaluation/tasks/coco_object_detection/preprocess_coco_minival.runfiles/org_tensorflow/tensorflow/lite/tools/evaluation/tasks/coco_object_detection/preprocess_coco_minival.py", line 211, in <module>
    _dump_data(ground_truths, args.images_folder, args.output_folder)
  File "/home/sicong/.cache/bazel/_bazel_sicong/7b2e833de2ecb2ea31568e76c69b68a8/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/lite/tools/evaluation/tasks/coco_object_detection/preprocess_coco_minival.runfiles/org_tensorflow/tensorflow/lite/tools/evaluation/tasks/coco_object_detection/preprocess_coco_minival.py", line 152, in _dump_data
    detection_result.image_id = image_dict['id']
AttributeError: 'ObjectDetectionResult' object has no attribute 'image_id'

Is there any solution? Thank you!

**Comment by ravikyram** [comment]
In order to expedite the trouble-shooting process, please provide a minimal standalone code to reproduce the issue reported here. Thanks!

**Comment by Sicongzai** [comment]
Thank you for responses. 
I didn't  change any code and use the python binary as follows:
bazel run //tensorflow/lite/tools/evaluation/tasks/coco_object_detection:preprocess_coco_minival --
--images_folder=/home/sicong/Documents/datasets/COCO/for_tflite_evaluation/val2014
--instances_file=/home/sicong/Documents/datasets/COCO/annotations_trainval2017/annotations/instances_val2017.json
--whitelist_file=/home/sicong/Documents/datasets/udacity/Udacity_coco/image_id.txt
--output_folder=/home/sicong/Documents/datasets/COCO/for_tflite_evaluation
--num_images=1000

**Comment by srjoglekar246** [comment]
hey @Sicongzai, I see that you have used the 2014 images with 2017 instances. That won't work, since the annotations don't correspond to the images in the folder. Try using the [2014 set](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/evaluation/tasks/coco_object_detection#preprocessing-the-minival-dataset) files if it works, or 2017 versions of both images & annotations. Mix-and-match will fail :-)

**Comment by Sicongzai** [comment]
hey @srjoglekar246  Thank you for your response.

I try to use 2017 images with 2017 instances. But still met the same problem. The detail can be seen below:
INFO: Running command line: bazel-bin/tensorflow/lite/tools/evaluation/tasks/coco_object_detection/preprocess_coco_minival '--images_folder=/home/sicong/Documents/datasets/COCO/val2017' '--instances_file=/home/sicong/Documents/datasets/COCO/annotations_trainval2017/annotations/instances_val2017.json' '--whitelist_file=/home/sicong/Documents/datasets/COCO/coco_val_2017_image_id.txt' '--output_foldeINFO: Build completed successfully, 305 total actions
Traceback (most recent call last):
  File "/home/sicong/.cache/bazel/_bazel_sicong/7b2e833de2ecb2ea31568e76c69b68a8/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/lite/tools/evaluation/tasks/coco_object_detection/preprocess_coco_minival.runfiles/org_tensorflow/tensorflow/lite/tools/evaluation/tasks/coco_object_detection/preprocess_coco_minival.py", line 211, in <module>
    _dump_data(ground_truths, args.images_folder, args.output_folder)
  File "/home/sicong/.cache/bazel/_bazel_sicong/7b2e833de2ecb2ea31568e76c69b68a8/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/lite/tools/evaluation/tasks/coco_object_detection/preprocess_coco_minival.runfiles/org_tensorflow/tensorflow/lite/tools/evaluation/tasks/coco_object_detection/preprocess_coco_minival.py", line 152, in _dump_data
    detection_result.image_id = image_dict['id']
AttributeError: 'ObjectDetectionResult' object has no attribute 'image_id'

When I try to use 2014 set, I met the memory problem: (I use CPU with about 4G Memory)
INFO: Running command line: bazel-bin/tensorflow/lite/tools/evaluation/tasks/coco_object_detection/preprocess_coco_minival '--images_folder=/home/sicong/Documents/datasets/COCO/for_tflite_evaluation/val2014' '--instances_file=/home/sicong/Documents/datasets/COCO/for_tflite_evaluation/annotations_trainval2014/annotations/instances_val2014.json' '--whitelist_file=/home/sicong/Documents/model_zoo/models/research/object_detection/data/mscoco_minival_ids.txt' '--output_folder=/homINFO: Build completed successfully, 1 total action
Traceback (most recent call last):
  File "/home/sicong/.cache/bazel/_bazel_sicong/7b2e833de2ecb2ea31568e76c69b68a8/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/lite/tools/evaluation/tasks/coco_object_detection/preprocess_coco_minival.runfiles/org_tensorflow/tensorflow/lite/tools/evaluation/tasks/coco_object_detection/preprocess_coco_minival.py", line 210, in <module>
    args.num_images)
  File "/home/sicong/.cache/bazel/_bazel_sicong/7b2e833de2ecb2ea31568e76c69b68a8/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/lite/tools/evaluation/tasks/coco_object_detection/preprocess_coco_minival.runfiles/org_tensorflow/tensorflow/lite/tools/evaluation/tasks/coco_object_detection/preprocess_coco_minival.py", line 64, in _get_ground_truth_detections
    data_dict = ast.literal_eval(annotation_dump.readline())
  File "/home/sicong/anaconda3/envs/venv/lib/python3.6/ast.py", line 48, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "/home/sicong/anaconda3/envs/venv/lib/python3.6/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
MemoryError

Or if the codes are only fit to 2014 set? I also use another dataset like Udacity in COCO format, but still meet the first problem.

**Comment by srjoglekar246** [comment]
Looks like the [BUILD rule](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/tools/evaluation/tasks/coco_object_detection/BUILD#L16) for that script is unable to link in the proto dependency. The proto does have the `image_id` attribute, as seen [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/tools/evaluation/proto/evaluation_stages.proto#L234). You could try setting the python version in the BUILD rule to `PY2`, or run the script with python (instead of blaze).

**Comment by Sicongzai** [comment]
Both setting the pythonV2 and using python to run the script directly don't work. But, I am successful to do the evaluation after I reinstall tensorflow for source.

Thank you for all the help!
