### ISSUE TITLE
distributed tensorflow on localhosts failed by “socket error, connection refused”

### ISSUE THREAD

**Issue by tonyrivermsfly** [tensorflow/tensorflow#3799]
I am experimenting distributed tensorflow using a slight modification of an [official example](https://www.tensorflow.org/versions/r0.10/how_tos/distributed/index.html).

My experiment code is (you can skip this for now and scroll down to the problem),

```
import tensorflow as tf
import numpy as np

# Flags for defining the tf.train.ClusterSpec
tf.app.flags.DEFINE_string("ps_hosts", "",
                           "Comma-separated list of hostname:port pairs")
tf.app.flags.DEFINE_string("worker_hosts", "",
                           "Comma-separated list of hostname:port pairs")

# Flags for defining the tf.train.Server
tf.app.flags.DEFINE_string("job_name", "", "One of 'ps', 'worker'")
tf.app.flags.DEFINE_integer("task_index", 0, "Index of task within the job")

FLAGS = tf.app.flags.FLAGS


def main(_):
    ps_hosts = FLAGS.ps_hosts.split(",")
    worker_hosts = FLAGS.worker_hosts.split(",")

    # Create a cluster from the parameter server and worker hosts.
    cluster = tf.train.ClusterSpec({"ps": ps_hosts, "worker": worker_hosts})

    # Create and start a server for the local task.
    server = tf.train.Server(cluster,
                             job_name=FLAGS.job_name,
                             task_index=FLAGS.task_index)

    if FLAGS.job_name == "ps":
        server.join()
    elif FLAGS.job_name == "worker":
        # Assigns ops to the local worker by default.
        with tf.device(tf.train.replica_device_setter(
                worker_device="/job:worker/task:%d" % FLAGS.task_index,
                cluster=cluster)):

            # Build model...
            x = tf.placeholder("float", [10, 10], name="x")
            y = tf.placeholder("float", [10, 1], name="y")
            initial_w = np.zeros((10, 1))
            w = tf.Variable(initial_w, name="w", dtype="float32")
            loss = tf.pow(tf.add(y,-tf.matmul(x,w)),2,name="loss")
            global_step = tf.Variable(0)

            saver = tf.train.Saver()
            summary_op = tf.merge_all_summaries()
            init_op = tf.initialize_all_variables()

        # Create a "supervisor", which oversees the training process.
        sv = tf.train.Supervisor(is_chief=(FLAGS.task_index == 0),
                                 logdir="/tmp/train_logs",
                                 init_op=init_op,
                                 summary_op=summary_op,
                                 saver=saver,
                                 global_step=global_step,
                                 save_model_secs=600)

        # The supervisor takes care of session initialization, restoring from
        # a checkpoint, and closing when done or an error occurs.
        with sv.managed_session(server.target) as sess:
            # Loop until the supervisor shuts down or 1000000 steps have completed.
            step = 0
            while not sv.should_stop() and step < 1000000:
                # Run a training step asynchronously.
                # See `tf.train.SyncReplicasOptimizer` for additional details on how to
                # perform *synchronous* training.
                _, step = sess.run([loss, global_step])
                print("job_name: %s; task_index: %s; step: %d" % (FLAGS.job_name,FLAGS.task_index,step))

        # Ask for all the services to stop.
        sv.stop()


if __name__ == "__main__":
    tf.app.run()
```
Then I run the following commands as instructed by the official document, changing the example host names to "localhost" (the script is named hello_distributed.py),

```
localhost:2223 --worker_hosts=localhost:2777,localhost:2778 --job_name=ps --task_index=0

sudo python3 hello_distributed.py --ps_hosts=localhost:2222,localhost:2223 --worker_hosts=localhost:2777,localhost:2778 --job_name=ps --task_index=1

sudo python3 hello_distributed.py --ps_hosts=localhost:2222,localhost:2223 --worker_hosts=localhost:2777,localhost:2778 --job_name=worker --task_index=0

sudo python3 hello_distributed.py --ps_hosts=localhost:2222,localhost:2223 --worker_hosts=localhost:2777,localhost:2778 --job_name=worker --task_index=1
```

The first two lines for running "ps" are good. The last two lines get the following "connection refused" error.

![image](https://cloud.githubusercontent.com/assets/18235797/17646308/036f3360-6192-11e6-9e1a-4a4ef88f8264.png)

Anyone can help with this? Thank you!

**Comment by avostryakov** [comment]
It looks like you didn't start the second worker. And you can start only one parameter server and two workers to simplify the situation a bit.

**Comment by hholst80** [comment]
It might help to have a script that launches all your processes. Adapt to your needs and run the entire script with `sudo`:
```
#!/bin/bash
NUM_PS_HOSTS=2
PS_HOSTS=localhost:2222,localhost:2223
NUM_WORKER_HOSTS=2
WORKER_HOSTS=localhost:2777,localhost:2778

for INDEX in `seq 0 $(expr $COUNT_PS_HOSTS - 1)`
do
    python3 hello_distributed.py \
            --ps_hosts=$PS_HOSTS \
            --worker_hosts=$WORKER_HOSTS \
            --job_name=ps \
            --task_index=$INDEX |& tee ps.${INDEX}.log &
done

for INDEX in `seq 0 $(expr $COUNT_WORKER_HOSTS - 1)`
do
    python3 hello_distributed.py \
            --ps_hosts=$PS_HOSTS \
            --worker_hosts=$WORKER_HOSTS \
            --job_name=ps \
            --task_index=$INDEX |& tee worker.${INDEX}.log &
done
```

**Comment by sherrym** [comment]
Thanks @hholst80 and @avostryakov for the responses. @tonyrivermsfly , is the problem resolved? Thanks.

**Comment by dzhwinter** [comment]
When I run the example code, I get this error

```
Traceback (most recent call last):
  File "hello_distributed.py", line 75, in <module>
    tf.app.run()
  File "/home/work/.jumbo/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "hello_distributed.py", line 67, in main
    _, step = sess.run([loss, global_step])
  File "/home/work/.jumbo/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 382, in run
    run_metadata_ptr)
  File "/home/work/.jumbo/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 655, in _run
    feed_dict_string, options, run_metadata)
  File "/home/work/.jumbo/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 723, in _do_run
    target_list, options, run_metadata)
  File "/home/work/.jumbo/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 743, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors.InvalidArgumentError: You must feed a value for placeholder tensor 'y' with dtype float and shape [10,1]
	 [[Node: y = Placeholder[dtype=DT_FLOAT, shape=[10,1], _device="/job:worker/replica:0/task:0/cpu:0"]()]]
Caused by op u'y', defined at:
  File "hello_distributed.py", line 75, in <module>
    tf.app.run()
  File "/home/work/.jumbo/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "hello_distributed.py", line 39, in main
    y = tf.placeholder("float", [10, 1], name="y")
  File "/home/work/.jumbo/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 1173, in placeholder
    name=name)
  File "/home/work/.jumbo/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 1322, in _placeholder
    name=name)
  File "/home/work/.jumbo/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 703, in apply_op
    op_def=op_def)
  File "/home/work/.jumbo/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2297, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/work/.jumbo/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1231, in __init__
    self._traceback = _extract_stack()
```

**Comment by tonyrivermsfly** [comment]
Hi guys, thank you for all your help!

Yes, when it says "connection refused", it actually means the program has crashed, and that means there could be some error in the code. It turns out I forgot to feed sess.run function.

In the script I use

`_, step = sess.run([loss, global_step])`

which has no feed for loss. The correct code is

```
                _, step = sess.run([loss, global_step],
                {
                  x: np.random.rand(10,10),
                  y: np.random.rand(10).reshape(-1,1)
                })
```

Now everything works! Thank you guys! Special thank you to @hholst80 for providing the script.

**Comment by tonyrivermsfly** [comment]
@sherrym  Yes the problem is now solved. Thank you!
