### ISSUE TITLE
Bazel is not able to detect CUDA 10.2 header files when building from source

### ISSUE THREAD

**Issue by kuriringohankamehameha** [tensorflow/tensorflow#37995]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): Source
- TensorFlow version: 2.1
- Python version: 3.6.8
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): 2.0.0
- GCC/Compiler version (if compiling from source): MSVC 2019 (Visual Studio 2019)
- CUDA/cuDNN version: CUDA Version: 10.2, cuDNN Version: 7
- GPU model and memory: NVIDIA Geforce GTX 940MX 2GB VRAM with Cuda Compatibility 5.0 (Lenovo IdeaPad Flex 5)

**Describe the problem**
Bazel is not able to detect the CUDA library files while building tensorflow, even though everything is included in the PATH, and the configure script is also detecting all relevant CUDA library files and includes.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

1. I was following the steps building from source as the official Documentation showed. While it mentioned CUDA 10.1, I wanted to test my installation with CUDA 10.2, since I have issues with working with CUDA 10.1.
2. I ensured that I set all relevant Bazel PATH environment variables before running the configure script `configure.py`.
3. I successfully configured bazel using `./config.py`.
4. Now, I ran the following command,
```
bazel build --config=opt --config=cuda --define=no_tensorflow_py_deps=true //tensorflow/tools/pip_package:build_pip_package
```
This gave me different errors, which I initially resolved using the following links:
1. I had the same issue as the poster in this link, which is resolved using [this ](https://github.com/tensorflow/tensorflow/issues/35253#issuecomment-570895670)patch.
Now, I'm stuck with the following error. Apparently, bazel isn't able to find the CUDA header files, even though the relevant path is included in the `.tf_configure.bazelrc` file.

For reference, here is the `.tf_configure.bazelrc` file:
```
build --action_env PYTHON_BIN_PATH="C:/Users/$USER/AppData/Local/Programs/Python/Python36/python.exe"
build --action_env PYTHON_LIB_PATH="C:/Users/$USER/AppData/Local/Programs/Python/Python36/lib/site-packages"
build --python_path="C:/Users/$USER/AppData/Local/Programs/Python/Python36/python.exe"
build --config=xla
build --action_env CUDA_TOOLKIT_PATH="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.2"
build --action_env TF_CUDA_COMPUTE_CAPABILITIES="5.0"
build --config=cuda
build:opt --copt=/arch:AVX
build:opt --define with_default_optimizations=true
build --define=override_eigen_strong_inline=true
test --flaky_test_attempts=3
test --test_size_filters=small,medium
test:v1 --test_tag_filters=-benchmark-test,-no_oss,-no_windows,-no_windows_gpu,-no_gpu,-oss_serial
test:v1 --build_tag_filters=-benchmark-test,-no_oss,-no_windows,-no_windows_gpu,-no_gpu
test:v2 --test_tag_filters=-benchmark-test,-no_oss,-no_windows,-no_windows_gpu,-no_gpu,-oss_serial,-v1only
test:v2 --build_tag_filters=-benchmark-test,-no_oss,-no_windows,-no_windows_gpu,-no_gpu,-v1only
build --action_env TF_CONFIGURE_IOS="0"
```

Here is the bazel command I used for buliding:
*Build Command*:
```
bazel build --config=opt --config=cuda --define=no_tensorflow_py_deps=true //tensorflow/tools/pip_package:build_pip_package
```

The log is mentioned below.

**Any other info / logs**
```
E:\Tensorflow\tensorflow-master\tensorflow-master>bazel build --config=opt --config=cuda --define=no_tensorflow_py_deps=true //tensorflow/tools/pip_package:build_pip_package
WARNING: The following configs were expanded more than once: [cuda, using_cuda]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=120
INFO: Reading rc options for 'build' from e:\tensorflow\tensorflow-master\tensorflow-master\.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Options provided by the client:
  'build' options: --python_path=C:/Users/srira/AppData/Local/Programs/Python/Python36/python.exe
INFO: Reading rc options for 'build' from e:\tensorflow\tensorflow-master\tensorflow-master\.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --java_toolchain=//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=//third_party/toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --enable_platform_specific_config --config=v2
INFO: Reading rc options for 'build' from e:\tensorflow\tensorflow-master\tensorflow-master\.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=C:/Users/srira/AppData/Local/Programs/Python/Python36/python.exe --action_env PYTHON_LIB_PATH=C:/Users/srira/AppData/Local/Programs/Python/Python36/lib/site-packages --python_path=C:/Users/srira/AppData/Local/Programs/Python/Python36/python.exe --config=xla --action_env CUDA_TOOLKIT_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.2 --action_env TF_CUDA_COMPUTE_CAPABILITIES=5.0 --config=cuda --define=override_eigen_strong_inline=true --action_env TF_CONFIGURE_IOS=0
INFO: Found applicable config definition build:v2 in file e:\tensorflow\tensorflow-master\tensorflow-master\.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:xla in file e:\tensorflow\tensorflow-master\tensorflow-master\.bazelrc: --action_env=TF_ENABLE_XLA=1 --define=with_xla_support=true
INFO: Found applicable config definition build:cuda in file e:\tensorflow\tensorflow-master\tensorflow-master\.bazelrc: --config=using_cuda --define=using_cuda_nvcc=true
INFO: Found applicable config definition build:using_cuda in file e:\tensorflow\tensorflow-master\tensorflow-master\.bazelrc: --define=using_cuda=true --action_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain
INFO: Found applicable config definition build:opt in file e:\tensorflow\tensorflow-master\tensorflow-master\.tf_configure.bazelrc: --copt=/arch:AVX --define with_default_optimizations=true
INFO: Found applicable config definition build:cuda in file e:\tensorflow\tensorflow-master\tensorflow-master\.bazelrc: --config=using_cuda --define=using_cuda_nvcc=true
INFO: Found applicable config definition build:using_cuda in file e:\tensorflow\tensorflow-master\tensorflow-master\.bazelrc: --define=using_cuda=true --action_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain
INFO: Found applicable config definition build:windows in file e:\tensorflow\tensorflow-master\tensorflow-master\.bazelrc: --copt=/w --copt=/D_USE_MATH_DEFINES --host_copt=/D_USE_MATH_DEFINES --cxxopt=/std:c++14 --host_cxxopt=/std:c++14 --config=monolithic --copt=-DWIN32_LEAN_AND_MEAN --host_copt=-DWIN32_LEAN_AND_MEAN --copt=-DNOGDI --host_copt=-DNOGDI --linkopt=/DEBUG --host_linkopt=/DEBUG --linkopt=/OPT:REF --host_linkopt=/OPT:REF --linkopt=/OPT:ICF --host_linkopt=/OPT:ICF --experimental_strict_action_env=true --verbose_failures --distinct_host_configuration=false
INFO: Found applicable config definition build:monolithic in file e:\tensorflow\tensorflow-master\tensorflow-master\.bazelrc: --define framework_shared_object=false
INFO: Call stack for the definition of repository 'local_config_cuda' which is a cuda_configure (rule definition at E:/tensorflow/tensorflow-master/tensorflow-master/third_party/gpus/cuda_configure.bzl:1243:18):
 - E:/tensorflow/tensorflow-master/tensorflow-master/tensorflow/workspace.bzl:91:5
 - E:/tensorflow/tensorflow-master/tensorflow-master/WORKSPACE:26:1
ERROR: An error occurred during the fetch of repository 'local_config_cuda':
   Traceback (most recent call last):
        File "E:/tensorflow/tensorflow-master/tensorflow-master/third_party/gpus/cuda_configure.bzl", line 1213
                _create_local_cuda_repository(<1 more arguments>)
        File "E:/tensorflow/tensorflow-master/tensorflow-master/third_party/gpus/cuda_configure.bzl", line 1075, in _create_local_cuda_repository
                to_list_of_strings(<1 more arguments>)
        File "E:/tensorflow/tensorflow-master/tensorflow-master/third_party/gpus/cuda_configure.bzl", line 1076, in to_list_of_strings
                _cuda_include_path(<2 more arguments>)
        File "E:/tensorflow/tensorflow-master/tensorflow-master/third_party/gpus/cuda_configure.bzl", line 365, in _cuda_include_path
                inc_entries.append(<1 more arguments>)
        File "E:/tensorflow/tensorflow-master/tensorflow-master/third_party/gpus/cuda_configure.bzl", line 365, in inc_entries.append
                realpath(repository_ctx, <1 more arguments>)
        File "E:/tensorflow/tensorflow-master/tensorflow-master/third_party/remote_config/common.bzl", line 268, in realpath
                execute(repository_ctx, <1 more arguments>)
        File "E:/tensorflow/tensorflow-master/tensorflow-master/third_party/remote_config/common.bzl", line 208, in execute
                fail(<1 more arguments>)
Repository command failed
realpath: 'C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.2/include': No such file or directory
ERROR: Skipping '//tensorflow/tools/pip_package:build_pip_package': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
        File "E:/tensorflow/tensorflow-master/tensorflow-master/third_party/gpus/cuda_configure.bzl", line 1213
                _create_local_cuda_repository(<1 more arguments>)
        File "E:/tensorflow/tensorflow-master/tensorflow-master/third_party/gpus/cuda_configure.bzl", line 1075, in _create_local_cuda_repository
                to_list_of_strings(<1 more arguments>)
        File "E:/tensorflow/tensorflow-master/tensorflow-master/third_party/gpus/cuda_configure.bzl", line 1076, in to_list_of_strings
                _cuda_include_path(<2 more arguments>)
        File "E:/tensorflow/tensorflow-master/tensorflow-master/third_party/gpus/cuda_configure.bzl", line 365, in _cuda_include_path
                inc_entries.append(<1 more arguments>)
        File "E:/tensorflow/tensorflow-master/tensorflow-master/third_party/gpus/cuda_configure.bzl", line 365, in inc_entries.append
                realpath(repository_ctx, <1 more arguments>)
        File "E:/tensorflow/tensorflow-master/tensorflow-master/third_party/remote_config/common.bzl", line 268, in realpath
                execute(repository_ctx, <1 more arguments>)
        File "E:/tensorflow/tensorflow-master/tensorflow-master/third_party/remote_config/common.bzl", line 208, in execute
                fail(<1 more arguments>)
Repository command failed
realpath: 'C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.2/include': No such file or directory
WARNING: Target pattern parsing failed.
ERROR: no such package '@local_config_cuda//cuda': Traceback (most recent call last):
        File "E:/tensorflow/tensorflow-master/tensorflow-master/third_party/gpus/cuda_configure.bzl", line 1213
                _create_local_cuda_repository(<1 more arguments>)
        File "E:/tensorflow/tensorflow-master/tensorflow-master/third_party/gpus/cuda_configure.bzl", line 1075, in _create_local_cuda_repository
                to_list_of_strings(<1 more arguments>)
        File "E:/tensorflow/tensorflow-master/tensorflow-master/third_party/gpus/cuda_configure.bzl", line 1076, in to_list_of_strings
                _cuda_include_path(<2 more arguments>)
        File "E:/tensorflow/tensorflow-master/tensorflow-master/third_party/gpus/cuda_configure.bzl", line 365, in _cuda_include_path
                inc_entries.append(<1 more arguments>)
        File "E:/tensorflow/tensorflow-master/tensorflow-master/third_party/gpus/cuda_configure.bzl", line 365, in inc_entries.append
                realpath(repository_ctx, <1 more arguments>)
        File "E:/tensorflow/tensorflow-master/tensorflow-master/third_party/remote_config/common.bzl", line 268, in realpath
                execute(repository_ctx, <1 more arguments>)
        File "E:/tensorflow/tensorflow-master/tensorflow-master/third_party/remote_config/common.bzl", line 208, in execute
                fail(<1 more arguments>)
Repository command failed
realpath: 'C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.2/include': No such file or directory
INFO: Elapsed time: 2.717s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: tensorflow/tools/pip_package
```

**Additional Information**
CUDA 10.2 works perfectly fine on my system, and I've tested programs using CUDA. Pytorch 1.4 with CUDA also runs fine on my system. I have Visual Studio 2019 installed, and I've included all relevant paths for both CUDA and Bazel.

**Comment by kuriringohankamehameha** [comment]
It seems that the I only have the Linux `patch` command as a subset of the WSL `bash`, and not from a separate Linux Environment. At first, I thought that the issue could be resolved by converting the Unix style paths back into Windows, but then I realised that Bazel needs Unix pathnames anyway.

So the solution was to install `patch` from a separate Linux environment. One of the recommendations from the official Docs was the Arch environment for Windows, *MSYS*. I set it up according to the docs, and now the problems seem to have been resolved.

**Comment by SagaraBattousai** [comment]
> It seems that the I only have the Linux `patch` command as a subset of the WSL `bash`, and not from a separate Linux Environment. At first, I thought that the issue could be resolved by converting the Unix style paths back into Windows, but then I realised that Bazel needs Unix pathnames anyway.
> 
> So the solution was to install `patch` from a separate Linux environment. One of the recommendations from the official Docs was the Arch environment for Windows, _MSYS_. I set it up according to the docs, and now the problems seem to have been resolved.

----------------------------------------------------------------------------------------------------------------------------------------------

I've got the same issue even though I have both ```patch``` and ```realpath``` installed with msys2 (using ```pacman -S patch realpath```) and they're on my path as well as msys2.exe. Is it possible that by having the wsl versions too it is causing an issue?
