### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found.   Failed to load the native TensorFlow runtime.

### ISSUE THREAD

**Issue by sathwikreddy56** [tensorflow/tensorflow#38014]
- windows 10 home 
- TensorFlow installed from source :
- TensorFlow version: 2.0.0
- Python version: 3.6.2
- Installed using  conda:
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: cuda9.0/cudnn-9.0
- GPU model and memory: Nvidea 1050 ti

**Describe the problem**
cant import tensorflow after its installation 
import tensorflow as tf
and give the following error

**Any other info / logs**
Using TensorFlow backend.
Traceback (most recent call last):

  File "C:\Users\sathw\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *

  File "C:\Users\sathw\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()

  File "C:\Users\sathw\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)

  File "G:\anaconda\envs\machinelearning\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)

  File "G:\anaconda\envs\machinelearning\lib\imp.py", line 343, in load_dynamic
    return _load(spec)

ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "D:\programms\teleuniv ques\untitled0.py", line 1, in <module>
    from keras.preprocessing import image

  File "G:\anaconda\envs\machinelearning\lib\site-packages\keras\__init__.py", line 3, in <module>
    from . import utils

  File "G:\anaconda\envs\machinelearning\lib\site-packages\keras\utils\__init__.py", line 6, in <module>
    from . import conv_utils

  File "G:\anaconda\envs\machinelearning\lib\site-packages\keras\utils\conv_utils.py", line 9, in <module>
    from .. import backend as K

  File "G:\anaconda\envs\machinelearning\lib\site-packages\keras\backend\__init__.py", line 1, in <module>
    from .load_backend import epsilon

  File "G:\anaconda\envs\machinelearning\lib\site-packages\keras\backend\load_backend.py", line 90, in <module>
    from .tensorflow_backend import *

  File "G:\anaconda\envs\machinelearning\lib\site-packages\keras\backend\tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf

  File "C:\Users\sathw\AppData\Roaming\Python\Python36\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util

  File "C:\Users\sathw\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\__init__.py", line 50, in <module>
    from tensorflow.python import pywrap_tensorflow

  File "C:\Users\sathw\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\pywrap_tensorflow.py", line 69, in <module>
    raise ImportError(msg)

ImportError: Traceback (most recent call last):
  File "C:\Users\sathw\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\sathw\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\sathw\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "G:\anaconda\envs\machinelearning\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "G:\anaconda\envs\machinelearning\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by sathwikreddy56** [comment]
not rectified its already done

**Comment by amahendrakar** [comment]
@sathwikreddy56,
Could you please check [this](https://github.com/tensorflow/tensorflow/issues/36167#issuecomment-577886156) comment from a similar issue and let us know if it works? Thanks!

**Comment by mihaimaruseac** [comment]
Closing as duplicate.

https://github.com/tensorflow/tensorflow/issues/36167#issuecomment-577886156

#36167 #36151 #36138 #36054 #36045 #36020 #36003 #35988 #35903 #35880 #35865 #35805 #35789 #35773 #35772 #35767 #35766 #35749 #35721 #35618 #35204
