### ISSUE TITLE
Couldn't match files for checkpoint

### ISSUE THREAD

**Issue by izhangzhihao** [tensorflow/tensorflow#38035]
Tensorflow can't load weight from a folder with a `+` symbol such as `a+b`, but if I simply change the folder name to `a`, it works well. See the [notebook](https://colab.research.google.com/drive/1CrWIySL6kofS7CEJgN72l8yrpgohIavJ) to reproduce this issue yourself.

**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): no
- OS Platform and Distribution:  MacOS 10.15.2
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if
the issue happens on mobile device: no
- TensorFlow installed from (source or
binary): - TensorFlow version (use command below):  v2.2.0-rc0-43-gacf4951a2f 2.2.0-rc1
- Python version: Python 3.7.7 (default, Mar 10 2020, 15:43:33)

**Describe the current behavior**

```
>>> model.load_weights("data/dev/checkpoint/a+b/cp1.ckpt")
Traceback (most recent call last):
  File "/Users/izhangzhihao/Library/Caches/pypoetry/virtualenvs/ve-0MKN22N3-py3.7/lib/python3.7/site-packages/tensorflow/python/training/py_checkpoint_reader.py", line 95, in NewCheckpointReader
    return CheckpointReader(compat.as_bytes(filepattern))
RuntimeError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for data/dev/checkpoint/a+b/cp1.ckpt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/izhangzhihao/Library/Caches/pypoetry/virtualenvs/ve-0MKN22N3-py3.7/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 249, in load_weights
    return super(Model, self).load_weights(filepath, by_name, skip_mismatch)
  File "/Users/izhangzhihao/Library/Caches/pypoetry/virtualenvs/ve-0MKN22N3-py3.7/lib/python3.7/site-packages/tensorflow/python/keras/engine/network.py", line 1226, in load_weights
    py_checkpoint_reader.NewCheckpointReader(filepath)
  File "/Users/izhangzhihao/Library/Caches/pypoetry/virtualenvs/ve-0MKN22N3-py3.7/lib/python3.7/site-packages/tensorflow/python/training/py_checkpoint_reader.py", line 99, in NewCheckpointReader
    error_translator(e)
  File "/Users/izhangzhihao/Library/Caches/pypoetry/virtualenvs/ve-0MKN22N3-py3.7/lib/python3.7/site-packages/tensorflow/python/training/py_checkpoint_reader.py", line 35, in error_translator
    raise errors_impl.NotFoundError(None, None, error_message)
tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for data/dev/checkpoint/a+b/cp1.ckpt
```

**Describe the expected behavior**

```
>>> model.load_weights("data/dev/checkpoint/a/cp1.ckpt")
<tensorflow.python.training.tracking.util.CheckpointLoadStatus object at 0x148b5c250>
```

**Standalone code to reproduce the issue** 

https://colab.research.google.com/drive/1CrWIySL6kofS7CEJgN72l8yrpgohIavJ

**Comment by simmalik** [comment]
I can work on this as well with @shahshriya

**Comment by simmalik** [comment]
We tried to replicate this issue using the same code that the author indicated that created this issue, but the program was able to execute successfully.  The load weights function was able to find the file in the same manner it finds files without "+" signs.  We tested additional file names ("c+d", "e+f+") and these cases also ran successfully.  Please let us know if this still appears to be an issue for you @izhangzhihao

**Comment by izhangzhihao** [comment]
Yup, it seems works as expected now with version `2.2.0-rc2`.
