### ISSUE TITLE
Using SavedModels with low-level API in TF 2.x

### ISSUE THREAD

**Issue by ongun-kanat** [tensorflow/tensorflow#38041]
I am not exactly sure whether this is a bug but it seems so

**System information** 
* I have custom code
* OS: Windows
* Tensorflow 2.1.0, Conda MKL version
* Python 3.7

**Describe the current behavior**
I am developing a system that uses Tensorflow SavedModel format to serve models in a custom embedded environment. So I want to create a basic computational graph and move on from there to test my toolchain and find bugs easily. For that I tried to create a simple graph as below:

**Standalone code to reproduce the issue** 

```python3
import tensorflow as tf
import tensorflow_core as tfcore
import pathlib

graph = tf.Graph()

with graph.as_default():
    A = tf.raw_ops.Placeholder(dtype=tf.dtypes.float32, shape=None, name="A")
    B = tf.raw_ops.Placeholder(dtype=tf.dtypes.float32, shape=None, name="B")
    Result = tf.raw_ops.Add(x=A, y=B, name="Result")


with tfcore.python.Session(graph=graph) as sess:
    script_dir = pathlib.Path(__file__).resolve().parent
    builder = tfcore.python.saved_model.builder.SavedModelBuilder(str(script_dir / "saved_model"))
    save_signature = tfcore.python.saved_model.signature_def_utils.predict_signature_def(
        inputs={"A": A, "B": B},
        outputs={"Result": Result})
    builder.add_meta_graph_and_variables(sess=sess,
                                         signature_def_map={"predict": save_signature},
                                         tags=["test_tag"],
                                         main_op=Result)
    builder.save(as_text=True) 
```

However this throws an exception when executed:

```
2020-03-30 13:10:56.894798: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
2020-03-30 13:10:56.897115: I tensorflow/core/common_runtime/process_util.cc:147] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
WARNING:tensorflow:From C:\Users\ongun\miniconda3\envs\npu_tf\lib\site-packages\tensorflow_core\python\saved_model\signature_def_utils_impl.py:201: build_tensor_info (from tensorflow.python.saved_model.utils_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.utils.build_tensor_info or tf.compat.v1.saved_model.build_tensor_info.
Traceback (most recent call last):
  File "C:/Users/ongun/code/02_npu/simple_tf_model/sum_graph.py", line 25, in <module>
    main_op=Result)
  File "C:\Users\ongun\miniconda3\envs\npu_tf\lib\site-packages\tensorflow_core\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\Users\ongun\miniconda3\envs\npu_tf\lib\site-packages\tensorflow_core\python\saved_model\builder_impl.py", line 582, in add_meta_graph_and_variables
    main_op = main_op or legacy_init_op
  File "C:\Users\ongun\miniconda3\envs\npu_tf\lib\site-packages\tensorflow_core\python\framework\ops.py", line 757, in __bool__
    self._disallow_bool_casting()
  File "C:\Users\ongun\miniconda3\envs\npu_tf\lib\site-packages\tensorflow_core\python\framework\ops.py", line 526, in _disallow_bool_casting
    self._disallow_in_graph_mode("using a `tf.Tensor` as a Python `bool`")
  File "C:\Users\ongun\miniconda3\envs\npu_tf\lib\site-packages\tensorflow_core\python\framework\ops.py", line 515, in _disallow_in_graph_mode
    " this function with @tf.function.".format(task))
tensorflow.python.framework.errors_impl.OperatorNotAllowedInGraphError: using a `tf.Tensor` as a Python `bool` is not allowed in Graph execution. Use Eager execution or decorate this function with @tf.function.
```

I traced the bug a little bit and the line https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/saved_model/builder_impl.py#L537 seems to cause the error by trying to treat  `main_op` as a boolean.

A simple fix seems to be viable by changing the line to:

```python3
main_op = main_op if main_op is not None else legacy_init_op
```

I can create a PR if that's an appropriate fix.

**Comment by amahendrakar** [comment]
@ongun-kanat,
I tried to reproduce the error, but I am facing an error stating `NameError: name '__file__' is not defined`. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/fc4c5821238be70114a666c8c4ead564/38041-2-1.ipynb).

In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here. Thanks!

**Comment by ongun-kanat** [comment]
Script is not designed to be run in a notebook. `__file__` is obviously undefined since you're not running it in a script called by python executable. 

I don't know if users have write permission for files in collab notebooks but you can try it with a hardcoded file name.

```python3
import tensorflow as tf
import tensorflow_core as tfcore
import pathlib

graph = tf.Graph()

with graph.as_default():
    A = tf.raw_ops.Placeholder(dtype=tf.dtypes.float32, shape=None, name="A")
    B = tf.raw_ops.Placeholder(dtype=tf.dtypes.float32, shape=None, name="B")
    Result = tf.raw_ops.Add(x=A, y=B, name="Result")


with tfcore.python.Session(graph=graph) as sess:
    builder = tfcore.python.saved_model.builder.SavedModelBuilder("saved_model")
    save_signature = tfcore.python.saved_model.signature_def_utils.predict_signature_def(
        inputs={"A": A, "B": B},
        outputs={"Result": Result})
    builder.add_meta_graph_and_variables(sess=sess,
                                         signature_def_map={"predict": save_signature},
                                         tags=["test_tag"],
                                         main_op=Result)
    builder.save(as_text=True) 
```

**Comment by amahendrakar** [comment]
Was able to reproduce the issue. Please find the Gist [here](https://colab.research.google.com/gist/amahendrakar/e391040cc4d3fe2064732d0741f18d55/38041-2-1.ipynb). Thanks!

**Comment by k-w-w** [comment]
The suggested fix should work -- can you submit a PR (with a test)? Thank you!

**Comment by Saduf2019** [comment]
@ongun-kanat 
Can you please update on the above comment.
Is this still an issue?

**Comment by ongun-kanat** [comment]
@Saduf2019 I submitted a PR for the issue. Sorry, I had forgotten it.
