### ISSUE TITLE
Reloading Tensorflow 2.1.0 without restarting interpreter

### ISSUE THREAD

**Issue by tianhuat** [tensorflow/tensorflow#38129]
In the production system  preinstalled with `tensorflow-gpu==1.13.1`, if I need to run `tensorflow-gpu==2.1.0`, I can only install and reload the library, without restarting the system, but reloading the tensorflow library gives me error, how should I resolve it?

To reproduce the problem on a client computer:

1.First

    pip install tensorflow-gpu==1.13.1

2.Then run the following code

    import tensorflow
    print(tensorflow.__version__) 

it will print

    1.13.1
3. Now run

    pip install tensorflow-gpu==2.1.0 

4.If you run the following code (what I run on production system to reload the module)

    import tensorflow
    from importlib import reload
    tensorflow=reload(tensorflow)
    print(tensorflow.__version__) 

You will get error as follows throw by `reload`, how should I resolve it?

    Traceback (most recent call last):
      File "/home/user/anaconda3/envs/tf1/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3326, in run_code
        exec(code_obj, self.user_global_ns, self.user_ns)
      File "<ipython-input-9-453567e02c5c>", line 3, in <module>
        tensorflow=reload(tensorflow)
      File "/home/user/anaconda3/envs/tf1/lib/python3.7/importlib/__init__.py", line 169, in reload
        _bootstrap._exec(spec, module)
      File "<frozen importlib._bootstrap>", line 630, in _exec
      File "<frozen importlib._bootstrap_external>", line 728, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/home/user/anaconda3/envs/tf1/lib/python3.7/site-packages/tensorflow/__init__.py", line 101, in <module>
        from tensorflow_core import *
      File "/home/user/anaconda3/envs/tf1/lib/python3.7/site-packages/tensorflow_core/__init__.py", line 40, in <module>
        from tensorflow.python.tools import module_util as _module_util
    ImportError: cannot import name 'module_util' from 'tensorflow.python.tools' (/home/user/anaconda3/envs/tf1/lib/python3.7/site-packages/tensorflow/python/tools/__init__.py)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/user/anaconda3/envs/tf1/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2040, in showtraceback
        stb = value._render_traceback_()
    AttributeError: 'ImportError' object has no attribute '_render_traceback_'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/user/anaconda3/envs/tf1/lib/python3.7/site-packages/IPython/core/ultratb.py", line 1101, in get_records
        return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
      File "/home/user/anaconda3/envs/tf1/lib/python3.7/site-packages/IPython/core/ultratb.py", line 319, in wrapped
        return f(*args, **kwargs)
      File "/home/user/anaconda3/envs/tf1/lib/python3.7/site-packages/IPython/core/ultratb.py", line 353, in _fixed_getinnerframes
        records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
      File "/home/user/anaconda3/envs/tf1/lib/python3.7/inspect.py", line 1502, in getinnerframes
        frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
      File "/home/user/anaconda3/envs/tf1/lib/python3.7/inspect.py", line 1460, in getframeinfo
        filename = getsourcefile(frame) or getfile(frame)
      File "/home/user/anaconda3/envs/tf1/lib/python3.7/inspect.py", line 696, in getsourcefile
        if getattr(getmodule(object, filename), '__loader__', None) is not None:
      File "/home/user/anaconda3/envs/tf1/lib/python3.7/inspect.py", line 733, in getmodule
        if ismodule(module) and hasattr(module, '__file__'):
      File "/home/user/anaconda3/envs/tf1/lib/python3.7/site-packages/tensorflow/__init__.py", line 50, in __getattr__
        module = self._load()
      File "/home/user/anaconda3/envs/tf1/lib/python3.7/site-packages/tensorflow/__init__.py", line 44, in _load
        module = _importlib.import_module(self.__name__)
      File "/home/user/anaconda3/envs/tf1/lib/python3.7/importlib/__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
      File "<frozen importlib._bootstrap>", line 983, in _find_and_load
      File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
      File "<frozen importlib._bootstrap>", line 983, in _find_and_load
      File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 728, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/home/user/anaconda3/envs/tf1/lib/python3.7/site-packages/tensorflow_core/__init__.py", line 40, in <module>
        from tensorflow.python.tools import module_util as _module_util
    ImportError: cannot import name 'module_util' from 'tensorflow.python.tools' (/home/user/anaconda3/envs/tf1/lib/python3.7/site-packages/tensorflow/python/tools/__init__.py)

**Comment by khimraj** [comment]
@tianhuat, you need to upgrade tensorflow to 2.x.

**Comment by tianhuat** [comment]
@khimraj The issue is not about upgrading, it's about can't restart the production environment after upgrading, I can only do a reloading of tensorflow library

**Comment by khimraj** [comment]
@tianhuat, I think currently it is not possible to reload Tensorflow 2.1.0 without restarting interpreter . You have to restart the runtime to change versions.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by ravikyram** [comment]
@tianhuat 

Any update on this issue please. Thanks!

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
