### ISSUE TITLE
wide_n_deep model deal with large dataset got ValueError: GraphDef cannot be larger than 2GB.

### ISSUE THREAD

**Issue by xinyuwuhenZZ** [tensorflow/tensorflow#3813]
wide_n_deep seems like unable to fit large dataset, when I put 1 million data, I got:

```
Traceback (most recent call last):
  File "search_click.py", line 207, in <module>
    tf.app.run()
  File "/usr/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "search_click.py", line 204, in main
    train_and_eval()
  File "search_click.py", line 181, in train_and_eval
    m.fit(input_fn=lambda: input_fn(df_train), steps=FLAGS.train_steps)
  File "/usr/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 182, in fit
    monitors=monitors)
  File "/usr/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 458, in _train_model
    summary_writer=graph_actions.get_summary_writer(self._model_dir))
  File "/usr/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/graph_actions.py", line 76, in get_summary_writer
    graph=ops.get_default_graph())
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/summary_io.py", line 113, in __init__
    self.add_graph(graph=graph, graph_def=graph_def)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/summary_io.py", line 204, in add_graph
    true_graph_def = graph.as_graph_def(add_shapes=True)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2117, in as_graph_def
    raise ValueError("GraphDef cannot be larger than 2GB.")
ValueError: GraphDef cannot be larger than 2GB.
```

```
def input_fn(df):
  """Input builder function."""
  # Creates a dictionary mapping from each continuous feature column name (k) to
  # the values of that column stored in a constant Tensor.
  continuous_cols = {k: tf.constant(df[k].values) for k in CONTINUOUS_COLUMNS}
  # Creates a dictionary mapping from each categorical feature column name (k)
  # to the values of that column stored in a tf.SparseTensor.
  categorical_cols = {k: tf.SparseTensor(
      indices=[[i, 0] for i in range(df[k].size)],
      values=df[k].values,
      shape=[df[k].size, 1])
                      for k in CATEGORICAL_COLUMNS}
  # Merges the two dictionaries into one.
  feature_cols = dict(continuous_cols)
  feature_cols.update(categorical_cols)
  # Converts the label column into a constant Tensor.
  label = tf.constant(df[LABEL_COLUMN].values)
  # Returns the feature columns and the label.
  return feature_cols, label
```

Is there a replacement of tf.constant and tf.SparseTensor, so we can load a batch once a time?
Any help would be appreciated!

**Comment by terrytangyuan** [comment]
@xinyuwuhenZZ You can use `partial_fit()` found [here](https://github.com/terrytangyuan/tensorflow/blob/3ee6afa12c30816b20d638a95945c49a59bae5f0/tensorflow/contrib/learn/python/learn/estimators/estimator.py#L236).

**Comment by xinyuwuhenZZ** [comment]
Thanks, but seems like no difference between fit() and partial_fit().

**Comment by xinyuwuhenZZ** [comment]
Thanks, but seems like no difference between ```fit()``` and ```partial_fit()```.

**Comment by terrytangyuan** [comment]
You are right. The implementation is quite different now and many functionalities may not work anymore. Perhaps @martinwicke can advise on this better.

**Comment by martinwicke** [comment]
Large datasets should not be put as constants into the graph. Use queues. You can check on the tutorials page, or on StackOverflow on how to use it.

**Comment by renwaiyouren** [comment]
@martinwicke Can you give an example? Thank you very much. I am a freshman to tensorflow.

**Comment by martinwicke** [comment]
Please check out this howto: https://www.tensorflow.org/how_tos/reading_data/

**Comment by renwaiyouren** [comment]
@martinwicke Thank you for your time. How to edit the function `input_fn` below to fix the ValueError: GraphDef cannot be larger than 2GB? Can you give another version of function `input_fn`? Thanks a lot. I am not very clear of how to do this edition with the link https://www.tensorflow.org/how_tos/reading_data/ after trying a lot with a lot of errors.
```python
def input_fn(df):
  """Input builder function."""
  # Creates a dictionary mapping from each continuous feature column name (k) to
  # the values of that column stored in a constant Tensor.
  continuous_cols = {k: tf.constant(df[k].values) for k in CONTINUOUS_COLUMNS}
  # Creates a dictionary mapping from each categorical feature column name (k)
  # to the values of that column stored in a tf.SparseTensor.
  categorical_cols = {k: tf.SparseTensor(
      indices=[[i, 0] for i in range(df[k].size)],
      values=df[k].values,
      shape=[df[k].size, 1])
                      for k in CATEGORICAL_COLUMNS}
  # Merges the two dictionaries into one.
  feature_cols = dict(continuous_cols)
  feature_cols.update(categorical_cols)
  # Converts the label column into a constant Tensor.
  label = tf.constant(df[LABEL_COLUMN].values)
  # Returns the feature columns and the label.
  return feature_cols, label
```

**Comment by martinwicke** [comment]
Please ask this type of question on StackOverflow.

Avoid calling tf.constant. Use tf.batch instead.
