### ISSUE TITLE
With .experimental_run_functions_eagerly(True), tf.functions run by Dataset doesn't get eager tensors

### ISSUE THREAD

**Issue by csachs** [tensorflow/tensorflow#38170]
**System information** 
- Have I written custom code: Yes 
- OS Platform and Distribution: Ubuntu 18.04 
- Mobile device: N/A 
- TensorFlow installed from: binary 
 - TensorFlow version (use command below): 2.1.0 / 2.2.0rc2
- Python version: 3.7.6

The manual suggests switching eager computation on for  `tf.function`s if debugging is desired, via `tf.config.experimental_run_functions_eagerly(True)`. However, this is not possible in situations like shown below.

To me it seems, that the in case of running eagerly, the function passed to `.map` would need to be executed with `tensorflow.python.framework.ops.EagerTensor` tensor arguments, not a regular `tensorflow.python.framework.ops.Tensor`.

**Describe the current behavior**
The example below outputs the following, failing with an exception:
```
[<tf.Tensor: shape=(), dtype=float32, numpy=1.0>, <tf.Tensor: shape=(), dtype=float32, numpy=0.0>]
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    perform_test()
  File "test.py", line 8, in perform_test
    print(list(tf.data.Dataset.from_tensor_slices([1.0,-1.0]).map(non_negative)))
  File "…tensorflow/python/data/ops/dataset_ops.py", line 1621, in map
    return MapDataset(self, map_func, preserve_cardinality=True)
  File "…tensorflow/python/data/ops/dataset_ops.py", line 3974, in __init__
    use_legacy_function=use_legacy_function)
  File "…tensorflow/python/data/ops/dataset_ops.py", line 3221, in __init__
    self._function = wrapper_fn.get_concrete_function()
  File "…tensorflow/python/eager/function.py", line 2532, in get_concrete_function
    *args, **kwargs)
  File "…tensorflow/python/eager/function.py", line 2496, in _get_concrete_function_garbage_collected
    graph_function, args, kwargs = self._maybe_define_function(args, kwargs)
  File "…tensorflow/python/eager/function.py", line 2777, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "…tensorflow/python/eager/function.py", line 2667, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "…tensorflow/python/framework/func_graph.py", line 981, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "…tensorflow/python/data/ops/dataset_ops.py", line 3214, in wrapper_fn
    ret = _wrapper_helper(*args)
  File "…tensorflow/python/data/ops/dataset_ops.py", line 3156, in _wrapper_helper
    ret = autograph.tf_convert(func, ag_ctx)(*nested_args)
  File "…tensorflow/python/eager/def_function.py", line 564, in __call__
    return self._python_function(*args, **kwds)
  File "test.py", line 5, in non_negative
    return 1.0 if value > 0.0 else 0.0
  File "…tensorflow/python/framework/ops.py", line 778, in __bool__
    self._disallow_bool_casting()
  File "…tensorflow/python/framework/ops.py", line 542, in _disallow_bool_casting
    "using a `tf.Tensor` as a Python `bool`")
  File "…tensorflow/python/framework/ops.py", line 527, in _disallow_when_autograph_disabled
    " Try decorating it directly with @tf.function.".format(task))
tensorflow.python.framework.errors_impl.OperatorNotAllowedInGraphError: using a `tf.Tensor` as a Python `bool` is not allowed: AutoGraph is disabled in this function. Try decorating it directly with @tf.function.
``` 
**Describe the expected behavior**
The example below working as desired, outputting: 
``` 
[<tf.Tensor: shape=(), dtype=float32, numpy=1.0>, <tf.Tensor: shape=(), dtype=float32, numpy=0.0>]
[<tf.Tensor: shape=(), dtype=float32, numpy=1.0>, <tf.Tensor: shape=(), dtype=float32, numpy=0.0>]
```

**Standalone code to reproduce the issue** 
```python
import tensorflow as tf

@tf.function
def non_negative(value):
    return 1.0 if value > 0.0 else 0.0

def perform_test():
    print(list(tf.data.Dataset.from_tensor_slices([1.0,-1.0]).map(non_negative)))

perform_test()

tf.config.experimental_run_functions_eagerly(True)

perform_test()
```

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with [TF v2.2.0-rc2](https://colab.research.google.com/gist/amahendrakar/03bf4471653ba67f0387aebd9469f68a/38170-2-2.ipynb) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/f7a7583cf73c4500517d2bea2feddf94/38170-tf-nightly.ipynb). Please find the attached gist. Thanks!

**Comment by mdanatg** [comment]
@jsimsa 
This is a known limitation: tf.data operations only support graph execution. We plan to document this more clearly.

**Comment by ccrusius** [comment]
This should not work, but the documentation wasn't clear. The new documentation should make this explicit: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/eager/def_function.py#L352 and https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/data/ops/dataset_ops.py#L3273
