### ISSUE TITLE
Tensorflow and Pip Error

### ISSUE THREAD

**Issue by HardworkingPig** [tensorflow/tensorflow#38235]
**System information**
- Windows 10 Basic Updated 
- TensorFlow installed from (source or binary): Anaconda 4.8.2
- TensorFlow version: 2.1
- Python version: 3.5
- Installed using Pip

```
(tensorflow1) c:\>pip install --ignore-installed --upgrade tensorflow
Collecting tensorflow
  Downloading tensorflow-2.1.0-cp35-cp35m-win_amd64.whl (355.8 MB)
     |██████                          | 67.7 MB 62 kB/s eta 1:16:58ERROR: Exception:
Traceback (most recent call last):
  File "c:\users\acer\anaconda3\envs\tensorflow1\lib\site-packages\pip\_vendor\urllib3\response.py", line 425, in _error_catcher
    yield
  File "c:\users\acer\anaconda3\envs\tensorflow1\lib\site-packages\pip\_vendor\urllib3\response.py", line 507, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "c:\users\acer\anaconda3\envs\tensorflow1\lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 62, in read
    data = self.__fp.read(amt)
  File "c:\users\acer\anaconda3\envs\tensorflow1\lib\http\client.py", line 448, in read
    n = self.readinto(b)
  File "c:\users\acer\anaconda3\envs\tensorflow1\lib\http\client.py", line 488, in readinto
    n = self.fp.readinto(b)
  File "c:\users\acer\anaconda3\envs\tensorflow1\lib\socket.py", line 576, in readinto
    return self._sock.recv_into(b)
  File "c:\users\acer\anaconda3\envs\tensorflow1\lib\ssl.py", line 937, in recv_into
    return self.read(nbytes, buffer)
  File "c:\users\acer\anaconda3\envs\tensorflow1\lib\ssl.py", line 799, in read
    return self._sslobj.read(len, buffer)
  File "c:\users\acer\anaconda3\envs\tensorflow1\lib\ssl.py", line 583, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\acer\anaconda3\envs\tensorflow1\lib\site-packages\pip\_internal\cli\base_command.py", line 186, in _main
    status = self.run(options, args)
  File "c:\users\acer\anaconda3\envs\tensorflow1\lib\site-packages\pip\_internal\commands\install.py", line 331, in run
    resolver.resolve(requirement_set)
  File "c:\users\acer\anaconda3\envs\tensorflow1\lib\site-packages\pip\_internal\legacy_resolve.py", line 177, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "c:\users\acer\anaconda3\envs\tensorflow1\lib\site-packages\pip\_internal\legacy_resolve.py", line 333, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "c:\users\acer\anaconda3\envs\tensorflow1\lib\site-packages\pip\_internal\legacy_resolve.py", line 282, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(req)
  File "c:\users\acer\anaconda3\envs\tensorflow1\lib\site-packages\pip\_internal\operations\prepare.py", line 482, in prepare_linked_requirement
    hashes=hashes,
  File "c:\users\acer\anaconda3\envs\tensorflow1\lib\site-packages\pip\_internal\operations\prepare.py", line 287, in unpack_url
    hashes=hashes,
  File "c:\users\acer\anaconda3\envs\tensorflow1\lib\site-packages\pip\_internal\operations\prepare.py", line 159, in unpack_http_url
    link, downloader, temp_dir.path, hashes
  File "c:\users\acer\anaconda3\envs\tensorflow1\lib\site-packages\pip\_internal\operations\prepare.py", line 303, in _download_http_url
    for chunk in download.chunks:
  File "c:\users\acer\anaconda3\envs\tensorflow1\lib\site-packages\pip\_internal\utils\ui.py", line 160, in iter
    for x in it:
  File "c:\users\acer\anaconda3\envs\tensorflow1\lib\site-packages\pip\_internal\network\utils.py", line 39, in response_chunks
    decode_content=False,
  File "c:\users\acer\anaconda3\envs\tensorflow1\lib\site-packages\pip\_vendor\urllib3\response.py", line 564, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "c:\users\acer\anaconda3\envs\tensorflow1\lib\site-packages\pip\_vendor\urllib3\response.py", line 529, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "c:\users\acer\anaconda3\envs\tensorflow1\lib\contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "c:\users\acer\anaconda3\envs\tensorflow1\lib\site-packages\pip\_vendor\urllib3\response.py", line 430, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
```

New Conda Environment

```
(base) c:\>conda create -n tensorflow1 pip python=3.5
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: done

  added / updated specs:
    - pip
    - python=3.5

The following NEW packages will be INSTALLED:

  certifi            pkgs/main/win-64::certifi-2018.8.24-py35_1
  pip                pkgs/main/win-64::pip-10.0.1-py35_0
  python             pkgs/main/win-64::python-3.5.6-he025d50_0
  setuptools         pkgs/main/win-64::setuptools-40.2.0-py35_0
  vc                 pkgs/main/win-64::vc-14.1-h0510ff6_4
  vs2015_runtime     pkgs/main/win-64::vs2015_runtime-14.16.27012-hf0eaf9b_1
  wheel              pkgs/main/win-64::wheel-0.31.1-py35_0
  wincertstore       pkgs/main/win-64::wincertstore-0.2-py35hfebbdb8_0

(base) c:\>activate tensorflow1
```

**Comment by mihaimaruseac** [comment]
This is not a coding issue. It is caused by your network connectivity getting interrupted during a large download. The only option is to retry or download from a different network connection.

**Comment by ankur-rana99** [comment]
Try to set socket timeout to a higher value:

pip3 install -U --upgrade --timeout 10000 tensorflow

it worked for me while installing jupyter
