### ISSUE TITLE
/home/myubuntu/tensorflow/tensorflow/examples/android/BUILD:47:1: Processing Android resources for //tensorflow/examples/android:tensorflow_demo failed: linux-sandbox failed: error executing command 

### ISSUE THREAD

**Issue by zwb88008** [tensorflow/tensorflow#3833]
ubuntu 14.04 
bazel build give the error:
/home/myubuntu/tensorflow/tensorflow/examples/android/BUILD:47:1: Processing Android resources for //tensorflow/examples/android:tensorflow_demo failed: linux-sandbox failed: error executing command

**Comment by zwb88008** [comment]
the error of detail is 
ERROR: /home/zwb/tensorflow/tensorflow/examples/android/BUILD:47:1: Processing Android resources for //tensorflow/examples/android:tensorflow_demo failed: linux-sandbox failed: error executing command 
  (cd /home/zwb/.cache/bazel/_bazel_zwb/0c95949bd08d065b0b8ae2967e52ee42/execroot/tensorflow && \
  exec env - \
  /home/zwb/.cache/bazel/_bazel_zwb/0c95949bd08d065b0b8ae2967e52ee42/execroot/tensorflow/_bin/linux-sandbox @/home/zwb/.cache/bazel/_bazel_zwb/0c95949bd08d065b0b8ae2967e52ee42/execroot/tensorflow/bazel-sandbox/1406bb67-c527-4333-9864-896c2a7476b6-0.params -- bazel-out/host/bin/external/bazel_tools/tools/android/resources_processor --buildToolsVersion 24.0.1 --aapt bazel-out/host/bin/external/androidsdk/aapt_binary --annotationJar external/androidsdk/tools/support/annotations.jar --androidJar external/androidsdk/platforms/android-24/android.jar --primaryData tensorflow/examples/android/res::tensorflow/examples/android/AndroidManifest.xml --rOutput bazel-out/local-fastbuild/bin/tensorflow/examples/android/tensorflow_demo_symbols/R.txt --srcJarOutput bazel-out/local-fastbuild/bin/tensorflow/examples/android/tensorflow_demo.srcjar --proguardOutput bazel-out/local-fastbuild/bin/tensorflow/examples/android/proguard/tensorflow_demo/_tensorflow_demo_proguard.cfg --mainDexProguardOutput bazel-out/local-fastbuild/bin/tensorflow/examples/android/proguard/tensorflow_demo/main_dex_tensorflow_demo_proguard.cfg --manifestOutput bazel-out/local-fastbuild/bin/tensorflow/examples/android/tensorflow_demo_processed_manifest/AndroidManifest.xml --resourcesOutput bazel-out/local-fastbuild/bin/tensorflow/examples/android/tensorflow_demo_files/resource_files.zip --packagePath bazel-out/local-fastbuild/bin/tensorflow/examples/android/tensorflow_demo.ap_ --debug --packageForR org.tensorflow.demo).
Error: bazel-out/host/bin/external/androidsdk/aapt_binary: line 4: /home/zwb/.cache/bazel/_bazel_zwb/0c95949bd08d065b0b8ae2967e52ee42/execroot/tensorflow/bazel-out/host/bin/external/androidsdk/aapt_binary.runfiles/androidsdk/build-tools/24.0.1/aapt: Permission denied
Error: bazel-out/host/bin/external/androidsdk/aapt_binary: line 4: /home/zwb/.cache/bazel/_bazel_zwb/0c95949bd08d065b0b8ae2967e52ee42/execroot/tensorflow/bazel-out/host/bin/external/androidsdk/aapt_binary.runfiles/androidsdk/build-tools/24.0.1/aapt: Permission denied
Error: bazel-out/host/bin/external/androidsdk/aapt_binary: line 4: /home/zwb/.cache/bazel/_bazel_zwb/0c95949bd08d065b0b8ae2967e52ee42/execroot/tensorflow/bazel-out/host/bin/external/androidsdk/aapt_binary.runfiles/androidsdk/build-tools/24.0.1/aapt: Permission denied
Error: bazel-out/host/bin/external/androidsdk/aapt_binary: line 4: /home/zwb/.cache/bazel/_bazel_zwb/0c95949bd08d065b0b8ae2967e52ee42/execroot/tensorflow/bazel-out/host/bin/external/androidsdk/aapt_binary.runfiles/androidsdk/build-tools/24.0.1/aapt: Permission denied
Error: bazel-out/host/bin/external/androidsdk/aapt_binary: line 4: /home/zwb/.cache/bazel/_bazel_zwb/0c95949bd08d065b0b8ae2967e52ee42/execroot/tensorflow/bazel-out/host/bin/external/androidsdk/aapt_binary.runfiles/androidsdk/build-tools/24.0.1/aapt: Permission denied
Aug 16, 2016 2:54:25 PM com.google.devtools.build.android.AndroidResourceProcessingAction main
SEVERE: Error during merging resources
Error: Failed to run command:
	bazel-out/host/bin/external/androidsdk/aapt_binary s -i /tmp/android_resources_tmp6549436154600677783/tmp-deduplicated/tensorflow/examples/android/res/drawable-hdpi/ic_launcher.png -o /tmp/android_resources_tmp6549436154600677783/merged_resources/drawable-hdpi-v4/ic_launcher.png
Error Code:
	1
Output:
	bazel-out/host/bin/external/androidsdk/aapt_binary: line 4: /home/zwb/.cache/bazel/_bazel_zwb/0c95949bd08d065b0b8ae2967e52ee42/execroot/tensorflow/bazel-out/host/bin/external/androidsdk/aapt_binary.runfiles/androidsdk/build-tools/24.0.1/aapt: Permission denied

	at com.android.ide.common.res2.MergeWriter.end(MergeWriter.java:54)
	at com.android.ide.common.res2.MergedResourceWriter.end(MergedResourceWriter.java:113)
	at com.android.ide.common.res2.DataMerger.mergeData(DataMerger.java:291)
	at com.android.ide.common.res2.ResourceMerger.mergeData(ResourceMerger.java:48)
	at com.google.devtools.build.android.AndroidResourceProcessor.mergeData(AndroidResourceProcessor.java:932)
	at com.google.devtools.build.android.AndroidResourceProcessingAction.main(AndroidResourceProcessingAction.java:257)
Caused by: com.android.ide.common.internal.LoggedErrorException: Failed to run command:
	bazel-out/host/bin/external/androidsdk/aapt_binary s -i /tmp/android_resources_tmp6549436154600677783/tmp-deduplicated/tensorflow/examples/android/res/drawable-hdpi/ic_launcher.png -o /tmp/android_resources_tmp6549436154600677783/merged_resources/drawable-hdpi-v4/ic_launcher.png
Error Code:
	1
Output:
	bazel-out/host/bin/external/androidsdk/aapt_binary: line 4: /home/zwb/.cache/bazel/_bazel_zwb/0c95949bd08d065b0b8ae2967e52ee42/execroot/tensorflow/bazel-out/host/bin/external/androidsdk/aapt_binary.runfiles/androidsdk/build-tools/24.0.1/aapt: Permission denied

	at com.android.ide.common.internal.CommandLineRunner.runCmdLine(CommandLineRunner.java:123)
	at com.android.ide.common.internal.CommandLineRunner.runCmdLine(CommandLineRunner.java:96)
	at com.android.ide.common.internal.AaptCruncher.crunchPng(AaptCruncher.java:58)
	at com.android.ide.common.res2.MergedResourceWriter$1.call(MergedResourceWriter.java:188)
	at com.android.ide.common.res2.MergedResourceWriter$1.call(MergedResourceWriter.java:139)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Exception in thread "main" Error: Failed to run command:
	bazel-out/host/bin/external/androidsdk/aapt_binary s -i /tmp/android_resources_tmp6549436154600677783/tmp-deduplicated/tensorflow/examples/android/res/drawable-hdpi/ic_launcher.png -o /tmp/android_resources_tmp6549436154600677783/merged_resources/drawable-hdpi-v4/ic_launcher.png
Error Code:
	1
Output:
	bazel-out/host/bin/external/androidsdk/aapt_binary: line 4: /home/zwb/.cache/bazel/_bazel_zwb/0c95949bd08d065b0b8ae2967e52ee42/execroot/tensorflow/bazel-out/host/bin/external/androidsdk/aapt_binary.runfiles/androidsdk/build-tools/24.0.1/aapt: Permission denied

	at com.android.ide.common.res2.MergeWriter.end(MergeWriter.java:54)
	at com.android.ide.common.res2.MergedResourceWriter.end(MergedResourceWriter.java:113)
	at com.android.ide.common.res2.DataMerger.mergeData(DataMerger.java:291)
	at com.android.ide.common.res2.ResourceMerger.mergeData(ResourceMerger.java:48)
	at com.google.devtools.build.android.AndroidResourceProcessor.mergeData(AndroidResourceProcessor.java:932)
	at com.google.devtools.build.android.AndroidResourceProcessingAction.main(AndroidResourceProcessingAction.java:257)
Caused by: com.android.ide.common.internal.LoggedErrorException: Failed to run command:
	bazel-out/host/bin/external/androidsdk/aapt_binary s -i /tmp/android_resources_tmp6549436154600677783/tmp-deduplicated/tensorflow/examples/android/res/drawable-hdpi/ic_launcher.png -o /tmp/android_resources_tmp6549436154600677783/merged_resources/drawable-hdpi-v4/ic_launcher.png
Error Code:
	1
Output:
	bazel-out/host/bin/external/androidsdk/aapt_binary: line 4: /home/zwb/.cache/bazel/_bazel_zwb/0c95949bd08d065b0b8ae2967e52ee42/execroot/tensorflow/bazel-out/host/bin/external/androidsdk/aapt_binary.runfiles/androidsdk/build-tools/24.0.1/aapt: Permission denied

	at com.android.ide.common.internal.CommandLineRunner.runCmdLine(CommandLineRunner.java:123)
	at com.android.ide.common.internal.CommandLineRunner.runCmdLine(CommandLineRunner.java:96)
	at com.android.ide.common.internal.AaptCruncher.crunchPng(AaptCruncher.java:58)
	at com.android.ide.common.res2.MergedResourceWriter$1.call(MergedResourceWriter.java:188)
	at com.android.ide.common.res2.MergedResourceWriter$1.call(MergedResourceWriter.java:139)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Target //tensorflow/examples/android:tensorflow_demo failed to build
INFO: Elapsed time: 3.245s, Critical Path: 1.61s

**Comment by drpngx** [comment]
Closing due to inactivity. Feel free to open a new github issue if the problem still persists in recent versions.
