### ISSUE TITLE
ImportError: No module named numpy

### ISSUE THREAD

**Issue by ayushmankumar7** [tensorflow/tensorflow#38350]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): No
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if
the issue happens on mobile device: 
- TensorFlow installed from (source or
binary): - TensorFlow version (use command below):  2.1.0
- Python version: - Bazel
version (if compiling from source): 2.0.0
- GCC/Compiler version (if compiling from
source): 
- CUDA/cuDNN version: - GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/api/tests
Numpy is installed still numpy Import Error .

**Describe the expected behavior**

**Standalone code to reproduce the issue** 
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

bazel run tensorflow/tools/api/tests:api_compatibility_test -- --update_goldens True

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

ERROR: An error occurred during the fetch of repository 'local_config_python':
   Traceback (most recent call last):
	File "/home/ayushman/Documents/github/tensorflow/third_party/py/python_configure.bzl", line 263
		_create_local_python_repository(<1 more arguments>)
	File "/home/ayushman/Documents/github/tensorflow/third_party/py/python_configure.bzl", line 213, in _create_local_python_repository
		_get_numpy_include(<2 more arguments>)
	File "/home/ayushman/Documents/github/tensorflow/third_party/py/python_configure.bzl", line 187, in _get_numpy_include
		execute(repository_ctx, <3 more arguments>)
	File "/home/ayushman/Documents/github/tensorflow/third_party/remote_config/common.bzl", line 208, in execute
		fail(<1 more arguments>)
Problem getting numpy include path.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named numpy
Is numpy installed?
ERROR: While resolving toolchains for target //tensorflow/tools/api/tests:api_compatibility_test: invalid registered toolchain '@local_config_python//:py_toolchain': no such package '@local_config_python//': Traceback (most recent call last):
	File "/home/ayushman/Documents/github/tensorflow/third_party/py/python_configure.bzl", line 263
		_create_local_python_repository(<1 more arguments>)
	File "/home/ayushman/Documents/github/tensorflow/third_party/py/python_configure.bzl", line 213, in _create_local_python_repository
		_get_numpy_include(<2 more arguments>)
	File "/home/ayushman/Documents/github/tensorflow/third_party/py/python_configure.bzl", line 187, in _get_numpy_include
		execute(repository_ctx, <3 more arguments>)
	File "/home/ayushman/Documents/github/tensorflow/third_party/remote_config/common.bzl", line 208, in execute
		fail(<1 more arguments>)
Problem getting numpy include path.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named numpy
Is numpy installed?
ERROR: Analysis of target '//tensorflow/tools/api/tests:api_compatibility_test' failed; build aborted: invalid registered toolchain '@local_config_python//:py_toolchain': no such package '@local_config_python//': Traceback (most recent call last):
	File "/home/ayushman/Documents/github/tensorflow/third_party/py/python_configure.bzl", line 263
		_create_local_python_repository(<1 more arguments>)
	File "/home/ayushman/Documents/github/tensorflow/third_party/py/python_configure.bzl", line 213, in _create_local_python_repository
		_get_numpy_include(<2 more arguments>)
	File "/home/ayushman/Documents/github/tensorflow/third_party/py/python_configure.bzl", line 187, in _get_numpy_include
		execute(repository_ctx, <3 more arguments>)
	File "/home/ayushman/Documents/github/tensorflow/third_party/remote_config/common.bzl", line 208, in execute
		fail(<1 more arguments>)
Problem getting numpy include path.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named numpy
Is numpy installed?
INFO: Elapsed time: 0.357s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)

**Comment by Saduf2019** [comment]
@ayushmankumar7
please refer to below issues and let us know if it helps
#37888 #30465  #[link](https://github.com/tensorflow/tensorflow/issues/29845#issuecomment-521006935)  #[link](https://github.com/tensorflow/tensorflow/issues/22794)

**Comment by ayushmankumar7** [comment]
Thanks for the help.. it was resolved.

**Comment by Saduf2019** [comment]
@ayushmankumar7 
Glad to help, moving this issue to closed as it is resolved

**Comment by Saduf2019** [comment]
@ayushmankumar7
please confirm if i may move this to closed status as its resolved.

**Comment by ayushmankumar7** [comment]
Yes.. It worked for me .. My problem is solved.
