### ISSUE TITLE
[TF 2.1] Jacobian / Hessian with Conv1D layers

### ISSUE THREAD

**Issue by Qottmann** [tensorflow/tensorflow#38391]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.1.0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
Can only compute 2nd derivatives (Jacobian of Gradient) with convolutional layers (Dense works fine) when experimental_use_pfor is set to False, while for Dense layers this is not necessary and seems to be faster (hard to compare though). Here is an executable code building a model and computing Hessian as Jacobian of Gradient as discussed here [[TF 2.0] tf.hessians #29781](https://github.com/tensorflow/tensorflow/issues/29781#issuecomment-611312435)

**Executable example**

```
import tensorflow as tf
print(tf.__version__)

loss_object = tf.keras.losses.MeanSquaredError()
def loss_function(real, pred):
    return tf.reduce_mean(loss_object(real, pred))

x_train = tf.random.normal((10,20,1))

inp = tf.keras.layers.Input(shape=x_train.shape[1:])
x1 = tf.keras.layers.Conv1D(32, 3, activation="relu", padding='same')(inp)
x1 = tf.keras.layers.Conv1D(1,3,activation="relu",padding="same")(x1)
cnn = tf.keras.models.Model(inp, x1)
cnn.compile(loss="mse",optimizer="sgd")

# hessian computation via jacobian
with tf.GradientTape(persistent=True) as tape:
    prediction = cnn(x_train)
    loss = loss_function(x_train,prediction)
    grads = tape.gradient(loss, cnn.trainable_variables)

hessians = [tape.jacobian(grad, cnn.trainable_variables) for grad in grads]
del tape
```

produces 

```
2.1.0
WARNING:tensorflow:Calling GradientTape.gradient on a persistent tape inside its context is significantly less efficient than calling it outside the context (it causes the gradient ops to be recorded on the tape, leading to increased CPU and memory usage). Only call GradientTape.gradient inside the context if you actually want to trace the gradient in order to compute higher order derivatives.
ERROR:tensorflow:Got error while pfor was converting op name: "loop_body/Conv2D"
op: "Conv2D"
input: "loop_body/Shape_3/17537"
input: "loop_body/Reshape_3"
attr {
  key: "T"
  value {
    type: DT_FLOAT
  }
}
attr {
  key: "data_format"
  value {
    s: "NHWC"
  }
}
attr {
  key: "dilations"
  value {
    list {
      i: 1
      i: 1
      i: 1
      i: 1
    }
  }
}
attr {
  key: "explicit_paddings"
  value {
    list {
    }
  }
}
attr {
  key: "padding"
  value {
    s: "SAME"
  }
}
attr {
  key: "strides"
  value {
    list {
      i: 1
      i: 1
      i: 1
      i: 1
    }
  }
}
attr {
  key: "use_cudnn_on_gpu"
  value {
    b: true
  }
}
with inputs (<tf.Tensor 'loop_body/Shape_3/17537:0' shape=(10, 1, 20, 1) dtype=float32>, <tf.Tensor 'loop_body/Reshape_3:0' shape=(1, 3, 1, 32) dtype=float32>)
, converted inputs [WrappedTensor(t=<tf.Tensor 'loop_body/Conv2D/pfor/Tile:0' shape=(96, 10, 1, 20, 1) dtype=float32>, is_stacked=True, is_sparse_stacked=False), WrappedTensor(t=<tf.Tensor 'loop_body/Reshape_3/pfor/Reshape:0' shape=(96, 1, 3, 1, 32) dtype=float32>, is_stacked=True, is_sparse_stacked=False)]
Input "filter" of op "Conv2D" expected to be loop invariant
Here are the pfor conversion stack traces:
ERROR:tensorflow:name: "loop_body/Conv2D"
op: "Conv2D"
input: "loop_body/Shape_3/17537"
input: "loop_body/Reshape_3"
attr {
  key: "T"
  value {
    type: DT_FLOAT
  }
}
attr {
  key: "data_format"
  value {
    s: "NHWC"
  }
}
attr {
  key: "dilations"
  value {
    list {
      i: 1
      i: 1
      i: 1
      i: 1
    }
  }
}
attr {
  key: "explicit_paddings"
  value {
    list {
    }
  }
}
attr {
  key: "padding"
  value {
    s: "SAME"
  }
}
attr {
  key: "strides"
  value {
    list {
      i: 1
      i: 1
      i: 1
      i: 1
    }
  }
}
attr {
  key: "use_cudnn_on_gpu"
  value {
    b: true
  }
}

created at:
    File "/home/kkottmann/anaconda3/envs/tftwo/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
    File "/home/kkottmann/anaconda3/envs/tftwo/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
    File "/home/kkottmann/anaconda3/envs/tftwo/lib/python3.7/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
    File "/home/kkottmann/anaconda3/envs/tftwo/lib/python3.7/site-packages/traitlets/config/application.py", line 664, in launch_instance
    app.start()
    File "/home/kkottmann/anaconda3/envs/tftwo/lib/python3.7/site-packages/ipykernel/kernelapp.py", line 583, in start
    self.io_loop.start()
    File "/home/kkottmann/anaconda3/envs/tftwo/lib/python3.7/site-packages/tornado/platform/asyncio.py", line 153, in start
    self.asyncio_loop.run_forever()
    File "/home/kkottmann/anaconda3/envs/tftwo/lib/python3.7/asyncio/base_events.py", line 538, in run_forever
    self._run_once()
    File "/home/kkottmann/anaconda3/envs/tftwo/lib/python3.7/asyncio/base_events.py", line 1782, in _run_once
    handle._run()
    File "/home/kkottmann/anaconda3/envs/tftwo/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
    File "/home/kkottmann/anaconda3/envs/tftwo/lib/python3.7/site-packages/tornado/ioloop.py", line 690, in <lambda>
    lambda f: self._run_callback(functools.partial(callback, future))
    File "/home/kkottmann/anaconda3/envs/tftwo/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
    File "/home/kkottmann/anaconda3/envs/tftwo/lib/python3.7/site-packages/tornado/gen.py", line 787, in inner
    self.run()
    File "/home/kkottmann/anaconda3/envs/tftwo/lib/python3.7/site-packages/tornado/gen.py", line 748, in run
    yielded = self.gen.send(value)
    File "/home/kkottmann/anaconda3/envs/tftwo/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 361, in process_one
    yield gen.maybe_future(dispatch(*args))
    File "/home/kkottmann/anaconda3/envs/tftwo/lib/python3.7/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
    File "/home/kkottmann/anaconda3/envs/tftwo/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 268, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
    File "/home/kkottmann/anaconda3/envs/tftwo/lib/python3.7/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
    File "/home/kkottmann/anaconda3/envs/tftwo/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 541, in execute_request
    user_expressions, allow_stdin,
    File "/home/kkottmann/anaconda3/envs/tftwo/lib/python3.7/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
    File "/home/kkottmann/anaconda3/envs/tftwo/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 300, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
    File "/home/kkottmann/anaconda3/envs/tftwo/lib/python3.7/site-packages/ipykernel/zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
    File "/home/kkottmann/anaconda3/envs/tftwo/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2858, in run_cell
    raw_cell, store_history, silent, shell_futures)
    File "/home/kkottmann/anaconda3/envs/tftwo/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2886, in _run_cell
    return runner(coro)
    File "/home/kkottmann/anaconda3/envs/tftwo/lib/python3.7/site-packages/IPython/core/async_helpers.py", line 68, in _pseudo_sync_runner
    coro.send(None)
    File "/home/kkottmann/anaconda3/envs/tftwo/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3063, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
    File "/home/kkottmann/anaconda3/envs/tftwo/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3254, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
    File "/home/kkottmann/anaconda3/envs/tftwo/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
    File "<ipython-input-32-9fcc71f67cfa>", line 22, in <module>
    hessians = [tape.jacobian(grad, cnn.trainable_variables) for grad in grads]
    File "<ipython-input-32-9fcc71f67cfa>", line 22, in <listcomp>
    hessians = [tape.jacobian(grad, cnn.trainable_variables) for grad in grads]
    File "/home/kkottmann/anaconda3/envs/tftwo/lib/python3.7/site-packages/tensorflow_core/python/eager/backprop.py", line 1113, in jacobian
    parallel_iterations=parallel_iterations)
    File "/home/kkottmann/anaconda3/envs/tftwo/lib/python3.7/site-packages/tensorflow_core/python/ops/parallel_for/control_flow_ops.py", line 189, in pfor
    return f()
    File "/home/kkottmann/anaconda3/envs/tftwo/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 2362, in __call__
    graph_function, args, kwargs = self._maybe_define_function(args, kwargs)
    File "/home/kkottmann/anaconda3/envs/tftwo/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 2703, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
    File "/home/kkottmann/anaconda3/envs/tftwo/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 2593, in _create_graph_function
    capture_by_value=self._capture_by_value),
    File "/home/kkottmann/anaconda3/envs/tftwo/lib/python3.7/site-packages/tensorflow_core/python/framework/func_graph.py", line 978, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
    File "/home/kkottmann/anaconda3/envs/tftwo/lib/python3.7/site-packages/tensorflow_core/python/framework/func_graph.py", line 964, in wrapper
    user_requested=True,
    File "/home/kkottmann/anaconda3/envs/tftwo/lib/python3.7/site-packages/tensorflow_core/python/ops/parallel_for/control_flow_ops.py", line 183, in f
    return _pfor_impl(loop_fn, iters, parallel_iterations=parallel_iterations)
    File "/home/kkottmann/anaconda3/envs/tftwo/lib/python3.7/site-packages/tensorflow_core/python/ops/parallel_for/control_flow_ops.py", line 224, in _pfor_impl
    loop_fn_outputs = loop_fn(loop_var)
    File "/home/kkottmann/anaconda3/envs/tftwo/lib/python3.7/site-packages/tensorflow_core/python/eager/backprop.py", line 1103, in loop_fn
    unconnected_gradients=unconnected_gradients)
    File "/home/kkottmann/anaconda3/envs/tftwo/lib/python3.7/site-packages/tensorflow_core/python/eager/backprop.py", line 1029, in gradient
    unconnected_gradients=unconnected_gradients)
    File "/home/kkottmann/anaconda3/envs/tftwo/lib/python3.7/site-packages/tensorflow_core/python/eager/imperative_grad.py", line 77, in imperative_grad
    compat.as_str(unconnected_gradients.value))
    File "/home/kkottmann/anaconda3/envs/tftwo/lib/python3.7/site-packages/tensorflow_core/python/eager/backprop.py", line 141, in _gradient_function
    return grad_fn(mock_op, *out_grads)
    File "/home/kkottmann/anaconda3/envs/tftwo/lib/python3.7/site-packages/tensorflow_core/python/ops/nn_grad.py", line 92, in _Conv2DBackpropFilterGrad
    data_format=op.get_attr("data_format").decode())
    File "/home/kkottmann/anaconda3/envs/tftwo/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_nn_ops.py", line 969, in conv2d
    data_format=data_format, dilations=dilations, name=name)
    File "/home/kkottmann/anaconda3/envs/tftwo/lib/python3.7/site-packages/tensorflow_core/python/framework/op_def_library.py", line 742, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)
    File "/home/kkottmann/anaconda3/envs/tftwo/lib/python3.7/site-packages/tensorflow_core/python/framework/func_graph.py", line 595, in _create_op_internal
    compute_device)
    File "/home/kkottmann/anaconda3/envs/tftwo/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3322, in _create_op_internal
    op_def=op_def)
    File "/home/kkottmann/anaconda3/envs/tftwo/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 1756, in __init__
    self._traceback = tf_stack.extract_stack()

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~/anaconda3/envs/tftwo/lib/python3.7/site-packages/tensorflow_core/python/eager/backprop.py in jacobian(self, target, sources, unconnected_gradients, parallel_iterations, experimental_use_pfor)
   1112         output = pfor_ops.pfor(loop_fn, target_size,
-> 1113                                parallel_iterations=parallel_iterations)
   1114       except ValueError as err:

~/anaconda3/envs/tftwo/lib/python3.7/site-packages/tensorflow_core/python/ops/parallel_for/control_flow_ops.py in pfor(loop_fn, iters, parallel_iterations)
    188     f = function.defun(f)
--> 189   return f()
    190 

~/anaconda3/envs/tftwo/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py in __call__(self, *args, **kwargs)
   2361     with self._lock:
-> 2362       graph_function, args, kwargs = self._maybe_define_function(args, kwargs)
   2363     return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access

~/anaconda3/envs/tftwo/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py in _maybe_define_function(self, args, kwargs)
   2702       self._function_cache.missed.add(call_context_key)
-> 2703       graph_function = self._create_graph_function(args, kwargs)
   2704       self._function_cache.primary[cache_key] = graph_function

~/anaconda3/envs/tftwo/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py in _create_graph_function(self, args, kwargs, override_flat_arg_shapes)
   2592             override_flat_arg_shapes=override_flat_arg_shapes,
-> 2593             capture_by_value=self._capture_by_value),
   2594         self._function_attributes,

~/anaconda3/envs/tftwo/lib/python3.7/site-packages/tensorflow_core/python/framework/func_graph.py in func_graph_from_py_func(name, python_func, args, kwargs, signature, func_graph, autograph, autograph_options, add_control_dependencies, arg_names, op_return_value, collections, capture_by_value, override_flat_arg_shapes)
    977 
--> 978       func_outputs = python_func(*func_args, **func_kwargs)
    979 

~/anaconda3/envs/tftwo/lib/python3.7/site-packages/tensorflow_core/python/framework/func_graph.py in wrapper(*args, **kwargs)
    967             if hasattr(e, "ag_error_metadata"):
--> 968               raise e.ag_error_metadata.to_exception(e)
    969             else:

ValueError: in converted code:

    /home/kkottmann/anaconda3/envs/tftwo/lib/python3.7/site-packages/tensorflow_core/python/ops/parallel_for/control_flow_ops.py:183 f  *
        return _pfor_impl(loop_fn, iters, parallel_iterations=parallel_iterations)
    /home/kkottmann/anaconda3/envs/tftwo/lib/python3.7/site-packages/tensorflow_core/python/ops/parallel_for/control_flow_ops.py:256 _pfor_impl
        outputs.append(converter.convert(loop_fn_output))
    /home/kkottmann/anaconda3/envs/tftwo/lib/python3.7/site-packages/tensorflow_core/python/ops/parallel_for/pfor.py:1280 convert
        output = self._convert_helper(y)
    /home/kkottmann/anaconda3/envs/tftwo/lib/python3.7/site-packages/tensorflow_core/python/ops/parallel_for/pfor.py:1482 _convert_helper
        six.reraise(e.__class__, e, sys.exc_info()[2])
    /home/kkottmann/anaconda3/envs/tftwo/lib/python3.7/site-packages/six.py:703 reraise
        raise value
    /home/kkottmann/anaconda3/envs/tftwo/lib/python3.7/site-packages/tensorflow_core/python/ops/parallel_for/pfor.py:1466 _convert_helper
        new_outputs = converter(pfor_inputs)
    /home/kkottmann/anaconda3/envs/tftwo/lib/python3.7/site-packages/tensorflow_core/python/ops/parallel_for/pfor.py:902 _f
        return converter(pfor_input, self.op_type, *self._args, **self._kw_args)
    /home/kkottmann/anaconda3/envs/tftwo/lib/python3.7/site-packages/tensorflow_core/python/ops/parallel_for/pfor.py:1592 _convert_flatten_batch
        inputs = _inputs_with_flattening(pfor_input, dims)
    /home/kkottmann/anaconda3/envs/tftwo/lib/python3.7/site-packages/tensorflow_core/python/ops/parallel_for/pfor.py:1576 _inputs_with_flattening
        inp = pfor_input.unstacked_input(i)
    /home/kkottmann/anaconda3/envs/tftwo/lib/python3.7/site-packages/tensorflow_core/python/ops/parallel_for/pfor.py:776 unstacked_input
        input_name, op_type))

    ValueError: Input "filter" of op "Conv2D" expected to be loop invariant


During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-32-9fcc71f67cfa> in <module>
     20     grads = tape.gradient(loss, cnn.trainable_variables)
     21 
---> 22 hessians = [tape.jacobian(grad, cnn.trainable_variables) for grad in grads]
     23 del tape

<ipython-input-32-9fcc71f67cfa> in <listcomp>(.0)
     20     grads = tape.gradient(loss, cnn.trainable_variables)
     21 
---> 22 hessians = [tape.jacobian(grad, cnn.trainable_variables) for grad in grads]
     23 del tape

~/anaconda3/envs/tftwo/lib/python3.7/site-packages/tensorflow_core/python/eager/backprop.py in jacobian(self, target, sources, unconnected_gradients, parallel_iterations, experimental_use_pfor)
   1119                 "jacobian computation. Vectorization can be disabled by setting"
   1120                 " experimental_use_pfor to False."),
-> 1121             sys.exc_info()[2])
   1122     else:
   1123       if context.executing_eagerly() and not self._persistent:

~/anaconda3/envs/tftwo/lib/python3.7/site-packages/six.py in reraise(tp, value, tb)
    700                 value = tp()
    701             if value.__traceback__ is not tb:
--> 702                 raise value.with_traceback(tb)
    703             raise value
    704         finally:

~/anaconda3/envs/tftwo/lib/python3.7/site-packages/tensorflow_core/python/eager/backprop.py in jacobian(self, target, sources, unconnected_gradients, parallel_iterations, experimental_use_pfor)
   1111       try:
   1112         output = pfor_ops.pfor(loop_fn, target_size,
-> 1113                                parallel_iterations=parallel_iterations)
   1114       except ValueError as err:
   1115         six.reraise(

~/anaconda3/envs/tftwo/lib/python3.7/site-packages/tensorflow_core/python/ops/parallel_for/control_flow_ops.py in pfor(loop_fn, iters, parallel_iterations)
    187   if context.executing_eagerly() or _is_under_xla_context():
    188     f = function.defun(f)
--> 189   return f()
    190 
    191 

~/anaconda3/envs/tftwo/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py in __call__(self, *args, **kwargs)
   2360     """Calls a graph function specialized to the inputs."""
   2361     with self._lock:
-> 2362       graph_function, args, kwargs = self._maybe_define_function(args, kwargs)
   2363     return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
   2364 

~/anaconda3/envs/tftwo/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py in _maybe_define_function(self, args, kwargs)
   2701 
   2702       self._function_cache.missed.add(call_context_key)
-> 2703       graph_function = self._create_graph_function(args, kwargs)
   2704       self._function_cache.primary[cache_key] = graph_function
   2705       return graph_function, args, kwargs

~/anaconda3/envs/tftwo/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py in _create_graph_function(self, args, kwargs, override_flat_arg_shapes)
   2591             arg_names=arg_names,
   2592             override_flat_arg_shapes=override_flat_arg_shapes,
-> 2593             capture_by_value=self._capture_by_value),
   2594         self._function_attributes,
   2595         # Tell the ConcreteFunction to clean up its graph once it goes out of

~/anaconda3/envs/tftwo/lib/python3.7/site-packages/tensorflow_core/python/framework/func_graph.py in func_graph_from_py_func(name, python_func, args, kwargs, signature, func_graph, autograph, autograph_options, add_control_dependencies, arg_names, op_return_value, collections, capture_by_value, override_flat_arg_shapes)
    976                                           converted_func)
    977 
--> 978       func_outputs = python_func(*func_args, **func_kwargs)
    979 
    980       # invariant: `func_outputs` contains only Tensors, CompositeTensors,

~/anaconda3/envs/tftwo/lib/python3.7/site-packages/tensorflow_core/python/framework/func_graph.py in wrapper(*args, **kwargs)
    966           except Exception as e:  # pylint:disable=broad-except
    967             if hasattr(e, "ag_error_metadata"):
--> 968               raise e.ag_error_metadata.to_exception(e)
    969             else:
    970               raise

ValueError: in converted code:

    /home/kkottmann/anaconda3/envs/tftwo/lib/python3.7/site-packages/tensorflow_core/python/ops/parallel_for/control_flow_ops.py:183 f  *
        return _pfor_impl(loop_fn, iters, parallel_iterations=parallel_iterations)
    /home/kkottmann/anaconda3/envs/tftwo/lib/python3.7/site-packages/tensorflow_core/python/ops/parallel_for/control_flow_ops.py:256 _pfor_impl
        outputs.append(converter.convert(loop_fn_output))
    /home/kkottmann/anaconda3/envs/tftwo/lib/python3.7/site-packages/tensorflow_core/python/ops/parallel_for/pfor.py:1280 convert
        output = self._convert_helper(y)
    /home/kkottmann/anaconda3/envs/tftwo/lib/python3.7/site-packages/tensorflow_core/python/ops/parallel_for/pfor.py:1482 _convert_helper
        six.reraise(e.__class__, e, sys.exc_info()[2])
    /home/kkottmann/anaconda3/envs/tftwo/lib/python3.7/site-packages/six.py:703 reraise
        raise value
    /home/kkottmann/anaconda3/envs/tftwo/lib/python3.7/site-packages/tensorflow_core/python/ops/parallel_for/pfor.py:1466 _convert_helper
        new_outputs = converter(pfor_inputs)
    /home/kkottmann/anaconda3/envs/tftwo/lib/python3.7/site-packages/tensorflow_core/python/ops/parallel_for/pfor.py:902 _f
        return converter(pfor_input, self.op_type, *self._args, **self._kw_args)
    /home/kkottmann/anaconda3/envs/tftwo/lib/python3.7/site-packages/tensorflow_core/python/ops/parallel_for/pfor.py:1592 _convert_flatten_batch
        inputs = _inputs_with_flattening(pfor_input, dims)
    /home/kkottmann/anaconda3/envs/tftwo/lib/python3.7/site-packages/tensorflow_core/python/ops/parallel_for/pfor.py:1576 _inputs_with_flattening
        inp = pfor_input.unstacked_input(i)
    /home/kkottmann/anaconda3/envs/tftwo/lib/python3.7/site-packages/tensorflow_core/python/ops/parallel_for/pfor.py:776 unstacked_input
        input_name, op_type))

    ValueError: Input "filter" of op "Conv2D" expected to be loop invariant

Encountered an exception while vectorizing the jacobian computation. Vectorization can be disabled by setting experimental_use_pfor to False.
```

**Comment by Qottmann** [comment]
Hi, just wanted to ask whether this was the right way to give attention to this and also whether it can be expected that `experimental_use_pfor = True` for convolutional layers will be implemented in some future version?

**Comment by jvishnuvardhan** [comment]
@Qottmann Is there any actionable item like a PR?

Please note that Keras development moved to another repository to focus entirely on only keras. Could you please repost this issue on [keras-team/keras repo](https://github.com/keras-team/keras/issues). Thanks!
