### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by Mostalk** [tensorflow/tensorflow#38424]
**System information** 
- csv2TFrecords
- Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if
the issue happens on mobile device: 
- TensorFlow installed from: pip install tensorflow==2.2.0rc2
- TensorFlow version : 2.2.0-rc2
- Python version: 3.8.2
 - GPU model: AMD HD 7950

**Traceback (most recent call last):
  File "tf.py", line 100, in <module>
    tf.app.run()
  File "C:\Users\Mostalk\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Users\Mostalk\AppData\Roaming\Python\Python38\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "C:\Users\Mostalk\AppData\Roaming\Python\Python38\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "tf.py", line 91, in main
    tf_example = create_tf_example(group, path)
  File "tf.py", line 46, in create_tf_example
    encoded_jpg = fid.read()
  File "C:\Users\Mostalk\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\lib\io\file_io.py", line 116, in read
    self._preread_check()
  File "C:\Users\Mostalk\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\lib\io\file_io.py", line 78, in _preread_check
    self._read_buf = _pywrap_file_io.BufferedInputStream(
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcd in position 123: invalid continuation byte**

**Comment by gadagashwini** [comment]
@Mostalk, Can you provide the complete standalone code to reproduce the issue. Thanks!

**Comment by Saduf2019** [comment]
@Mostalk, please update as per above comment
