### ISSUE TITLE
PySpark Deep Learning Pipeline - ClassNotFoundException: org.tensorframes.ShapeDescription

### ISSUE THREAD

**Issue by tsharma82** [tensorflow/tensorflow#38442]
I am getting the following exception while running Deep Learning Pipeline in Spark.
Versions of 

tensorflow and tensorframes : 2.0.0
conda : 4.8.3
pip : 20.0.2
python: 3.6

The exception comes while calling fit method of the pipeline:

    p = Pipeline(stages=[featurizer, lr])
    p_model = p.fit(train_df)

**Stack Trace**

   ```
 Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/opt/spark/python/pyspark/ml/base.py", line 132, in fit
        return self._fit(dataset)
      File "/opt/spark/python/pyspark/ml/pipeline.py", line 107, in _fit
        dataset = stage.transform(dataset)
      File "/opt/spark/python/pyspark/ml/base.py", line 173, in transform
        return self._transform(dataset)
      File "/opt/spark/python/pyspark/ml/wrapper.py", line 312, in _transform
        return DataFrame(self._java_obj.transform(dataset._jdf), dataset.sql_ctx)
      File "/opt/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1257, in __call__
      File "/opt/spark/python/pyspark/sql/utils.py", line 63, in deco
        return f(*a, **kw)
      File "/opt/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py", line 328, in get_return_value
    py4j.protocol.Py4JJavaError: An error occurred while calling o56.transform.
    : java.lang.NoClassDefFoundError: org/tensorframes/ShapeDescription
            at com.databricks.sparkdl.DeepImageFeaturizer.transform(DeepImageFeaturizer.scala:124)
            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.lang.reflect.Method.invoke(Method.java:498)
            at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
            at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
            at py4j.Gateway.invoke(Gateway.java:282)
            at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
            at py4j.commands.CallCommand.execute(CallCommand.java:79)
            at py4j.GatewayConnection.run(GatewayConnection.java:238)
            at java.lang.Thread.run(Thread.java:748)
    Caused by: java.lang.ClassNotFoundException: org.tensorframes.ShapeDescription
            at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
            ... 12 more

```
Any suggestions to solve this?

**Comment by khimraj** [comment]
@tsharma82, This is not a tensorflow issue. Please try to post on respective [community](https://github.com/apache/spark/tree/master/python/pyspark).

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
