### ISSUE TITLE
depends on @local_config_cc//:cc-compiler-x64_windows in repository @local_config_cc which failed to fetch. no such package 

### ISSUE THREAD

**Issue by danedang** [tensorflow/tensorflow#38492]
bazel build :hello_main
INFO: Call stack for the definition of repository 'local_config_cc' which is a cc_autoconf (rule definition at C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/cc_configure.bzl:143:15):
 - <builtin>
 - C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/cc_configure.bzl:179:5
 - /DEFAULT.WORKSPACE.SUFFIX:317:1
ERROR: An error occurred during the fetch of repository 'local_config_cc':
   Traceback (most recent call last):
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/cc_configure.bzl", line 120
                configure_windows_toolchain(<1 more arguments>)
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 690, in configure_windows_toolchain
                _get_msvc_vars(repository_ctx, <1 more arguments>)
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 503, in _get_msvc_vars
                _find_missing_vc_tools(<2 more arguments>)
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 387, in _find_missing_vc_tools
                find_msvc_tool(repository_ctx, <2 more arguments>)
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 367, in find_msvc_tool
                _get_vc_full_version(<2 more arguments>)
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 357, in _get_vc_full_version
                _get_latest_subversion(<2 more arguments>)
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 336, in _get_latest_subversion
                repository_ctx.path((vc_path + "\\Tools\\MSVC")).readdir()
C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC (No such file or directory)
ERROR: E:/tensorflow/02/BUILD:8:1: //:hello_main depends on @local_config_cc//:cc-compiler-x64_windows in repository @local_config_cc which failed to fetch. no such package '@local_config_cc//': Traceback (most recent call last):
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/cc_configure.bzl", line 120
                configure_windows_toolchain(<1 more arguments>)
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 690, in configure_windows_toolchain
                _get_msvc_vars(repository_ctx, <1 more arguments>)
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 503, in _get_msvc_vars
                _find_missing_vc_tools(<2 more arguments>)
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 387, in _find_missing_vc_tools
                find_msvc_tool(repository_ctx, <2 more arguments>)
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 367, in find_msvc_tool
                _get_vc_full_version(<2 more arguments>)
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 357, in _get_vc_full_version
                _get_latest_subversion(<2 more arguments>)
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 336, in _get_latest_subversion
                repository_ctx.path((vc_path + "\\Tools\\MSVC")).readdir()
C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC (No such file or directory)
ERROR: Analysis of target '//:hello_main' failed; build aborted: no such package '@local_config_cc//': Traceback (most recent call last):  
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/cc_configure.bzl", line 120
                configure_windows_toolchain(<1 more arguments>)
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 690, in configure_windows_toolchain
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 503, in _                _find_missing_vc_tools(<2 more arguments>)
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 387, in _find_missing_vc_tools
                find_msvc_tool(repository_ctx, <2 more arguments>)
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 367, in find_msvc_tool
                _get_vc_full_version(<2 more arguments>)
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 357, in _get_vc_full_version
                _get_latest_subversion(<2 more arguments>)
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 336, in _get_latest_subversion
                repository_ctx.path((vc_path + "\\Tools\\MSVC")).readdir()
C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC (No such file or directory)
INFO: Elapsed time: 1.231s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
PS E:\TensorFlow\02> bazel clean --expunge
INFO: Starting clean.
PS E:\TensorFlow\02> bazel build :hello_main
Starting local Bazel server and connecting to it...
INFO: Call stack for the definition of repository 'local_config_cc' which is a cc_autoconf (rule definition at C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/cc_configure.bzl:143:15):
 - <builtin>
 - C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/cc_configure.bzl:179:5
 - /DEFAULT.WORKSPACE.SUFFIX:317:1
ERROR: An error occurred during the fetch of repository 'local_config_cc':
   Traceback (most recent call last):
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/cc_configure.bzl", line 120
                configure_windows_toolchain(<1 more arguments>)
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 690, in configure_windows_toolchain
                _get_msvc_vars(repository_ctx, <1 more arguments>)
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 503, in _get_msvc_vars
                _find_missing_vc_tools(<2 more arguments>)
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 387, in _find_missing_vc_tools
                find_msvc_tool(repository_ctx, <2 more arguments>)
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 367, in find_msvc_tool
                _get_vc_full_version(<2 more arguments>)
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 357, in _get_vc_full_version
                _get_latest_subversion(<2 more arguments>)
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 336, in _get_latest_subversion
                repository_ctx.path((vc_path + "\\Tools\\MSVC")).readdir()
C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC (No such file or directory)
ERROR: E:/tensorflow/02/BUILD:8:1: //:hello_main depends on @local_config_cc//:cc-compiler-x64_windows in repository @local_config_cc which failed to fetch. no such package '@local_config_cc//': Traceback (most recent call last):
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/cc_configure.bzl", line 120
                configure_windows_toolchain(<1 more arguments>)
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 690, in configure_windows_toolchain
                _get_msvc_vars(repository_ctx, <1 more arguments>)
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 503, in _get_msvc_vars
                _find_missing_vc_tools(<2 more arguments>)
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 387, in _find_missing_vc_tools
                find_msvc_tool(repository_ctx, <2 more arguments>)
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 367, in find_msvc_tool
                _get_vc_full_version(<2 more arguments>)
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 357, in _get_vc_full_version
                _get_latest_subversion(<2 more arguments>)
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 336, in _get_latest_subversion
                repository_ctx.path((vc_path + "\\Tools\\MSVC")).readdir()
C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC (No such file or directory)
ERROR: Analysis of target '//:hello_main' failed; build aborted: no such package '@local_config_cc//': Traceback (most recent call last):  
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/cc_configure.bzl", line 120
                configure_windows_toolchain(<1 more arguments>)
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 690, in configure_windows_toolchain
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 503, in _get_msvc_vars
                _find_missing_vc_tools(<2 more arguments>)
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 387, in _find_missing_vc_tools
                find_msvc_tool(repository_ctx, <2 more arguments>)
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 367, in find_msvc_tool
                _get_vc_full_version(<2 more arguments>)
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 357, in _get_vc_full_version
                _get_latest_subversion(<2 more arguments>)
        File "C:/users/administrator/_bazel_administrator/gtw4qbxk/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 336, in _get_latest_subversion
                repository_ctx.path((vc_path + "\\Tools\\MSVC")).readdir()
C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC (No such file or directory)
INFO: Elapsed time: 7.744s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (12 packages loaded, 18 targets configured)
PS E:\TensorFlow\02> bazel
                                                           [bazel release 3.0.0]
Usage: bazel <command> <options> ...

Available commands:
  analyze-profile     Analyzes build profile data.
  aquery              Analyzes the given targets and queries the action graph.
  build               Builds the specified targets.
  canonicalize-flags  Canonicalizes a list of bazel options.
  clean               Removes output files and optionally stops the server.
  coverage            Generates code coverage report for specified test targets.
  cquery              Loads, analyzes, and queries the specified targets w/ configurations.
  dump                Dumps the internal state of the bazel server process.
  fetch               Fetches external repositories that are prerequisites to the targets.
  help                Prints help for commands, or the index.
  license             Prints the license of this software.
  mobile-install      Installs targets to mobile devices.
  print_action        Prints the command line args for compiling a file.
  query               Executes a dependency graph query.
  run                 Runs the specified target.
  shutdown            Stops the bazel server.
  sync                Syncs all repositories specified in the workspace file
  test                Builds and runs the specified test targets.
  version             Prints version information for bazel.

Getting more help:
  bazel help <command>
                   Prints help and options for <command>.
  bazel help startup_options
                   Options for the JVM hosting bazel.
  bazel help target-syntax
                   Explains the syntax for specifying targets.
  bazel help info-keys
                   Displays a list of keys used by the info command.
PS E:\TensorFlow\02> bazel version
Build label: 3.0.0
Build target: bazel-out/x64_windows-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Apr 6 12:56:01 2020 (1586177761)
Build timestamp: 1586177761
Build timestamp as int: 1586177761
PS E:\TensorFlow\02>

**Comment by ravikyram** [comment]
@danedang 

Which version of Tensorflow you are using. Request you to fill [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).Provide the exact sequence of commands / steps that you executed before running into the problem.Thanks!

**Comment by ravikyram** [comment]
@danedang 

Any update on this issue please. Thanks!

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by danedang** [comment]
@ravikyram  2.0
