### ISSUE TITLE
Failed to load the Native tensorflow routine

### ISSUE THREAD

**Issue by Sarvagya2009** [tensorflow/tensorflow#38552]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04 LTS 
- TensorFlow installed from (source or binary):  https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.5.0-py3-none-any.whl
- TensorFlow version: Tensorflow 1.5.0
- Python version: Python 2.7.12
- Installed using virtualenv? pip? conda?: pip

**Describe the problem**
I tried running : 

```
import tensorflow as tf
print(tf.reduce_sum(tf.random.normal([1000, 1000])))
```

**Any other info / logs**
The following is the error I get.

```
Traceback (most recent call last):
  File "/home/sarva/.local/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/sarva/.local/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/sarva/.local/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /home/sarva/.local/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: invalid ELF header

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "wtf.py", line 2, in <module>
    import tensorflow as tf
  File "/home/sarva/.local/lib/python3.5/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/home/sarva/.local/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/sarva/.local/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/sarva/.local/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/sarva/.local/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/sarva/.local/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /home/sarva/.local/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: invalid ELF header


Failed to load the native TensorFlow runtime.
```

**additional info**
 Can someone please guide on how to properly install tensorflow for my system. I am running ubuntu in VirtualBox on Windows 10 if that helps.

On typing uname -a: the system info returned is Linux ubuntu 4.4.0-177-generic #207-Ubuntu SMP Mon Mar 16 01:15:50 UTC 2020 i686 i686 i686 GNU/Linux

**Comment by ravikyram** [comment]
@Sarvagya2009 
Just to verify did you follow the instructions in [tensorflow website](https://www.tensorflow.org/install/source?hl=en) . Please, see tested build configurations from [here.](https://www.tensorflow.org/install/source?hl=en#tested_build_configurations). Tensorlow 1.5.0 is very older version .Request you to go for latest versions of Tensorflow for better support.Thanks!

**Comment by Sarvagya2009** [comment]
@ravikyram 
On following the website's instructions and installing bazelisk, I get the following error:
**Exception: Unsupported machine architecture "i686". Bazel currently only supports x86_64.**

So bazel is not compatible with my architecture. Any other method of installing tensorflow?

**Comment by mihaimaruseac** [comment]
Just to verify, did you use TensorFlow 1.5.0? That is very old and not supported

Do you need to use that version? Or is switching to 1.15 or later possible?

**Comment by Sarvagya2009** [comment]
@mihaimaruseac 
I changed it to a later version but still same thing and on trying to build from source and installing bazel, I got the aforementioned error.

**Comment by Sarvagya2009** [comment]
On trying on a different machine with x86_64, tensor-flow was installed successfully. So I think this problem was because of i686 architecture.

**Comment by ravikyram** [comment]
@Sarvagya2009 

Glad to know it worked.Please close this thread if it solves your question. Thanks!

**Comment by mihaimaruseac** [comment]
Yes, we only build for 64 bits architectures. Our code is too complex and building also for 32 bits will require at least 2-3 years of work (since we have so many numerics code assuming 64bits architectures which will result in a lot of security issues due to overflows if not handled properly). Since most of the processors in use are now on 64 bits, we are not prioritizing the work to support 32 bits (see also #32315).

You can use codelab if you don't have access to a 64-bits CPU.
