### ISSUE TITLE
Keras Model in SavedModel format Errors on Loading -ValueError('Model inputs are already set.')

### ISSUE THREAD

**Issue by tripathysa** [tensorflow/tensorflow#38550]
**System information**

Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
No
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ProductName:	Mac OS X, ProductVersion:	10.15.2, BuildVersion:	19C57
TensorFlow installed from (source or binary): pip
TensorFlow version (use command below): 2.1.0
Python version: 3.6.8
CUDA/cuDNN version: None
GPU model and memory: None

**Describe the current behavior**

When trying to load one of my SavedModel format models (saved using 1.15.0) using` tf.keras.models.load_model `an error is thrown at the following location:

```
  File "/Users/saurabh/.pyenv/versions/emotion-python/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py", line 2671, in _set_input_attrs
    raise ValueError('Model inputs are already set.')
```
**I can successfully load and run this model using TensorFlow versions 2.0.0, 1.15.0 and 1.14.0.**

**Describe the expected behavior**

Can successfully load a model from a SMB(SavedModel format) file.

**Code to reproduce the issue:**

```
import tensorflow as tf

model_smb = tf.keras.models.load_model('smbnew', compile=False)
```

**Other info / logs:**

**_I am also attaching a dummy SavedModel model below which can be used to test.**

Complete Stacktrace of the error:

```
Traceback (most recent call last):
  File "setup.py", line 9, in <module>
    model_smb = tf.keras.models.load_model('smbnew', compile=False)
  File "python3.6/site-packages/tensorflow_core/python/keras/saving/save.py", line 150, in load_model
    return saved_model_load.load(filepath, compile)
  File "python3.6/site-packages/tensorflow_core/python/keras/saving/saved_model/load.py", line 89, in load
    model = tf_load.load_internal(path, loader_cls=KerasObjectLoader)
  File "python3.6/site-packages/tensorflow_core/python/saved_model/load.py", line 552, in load_internal
    export_dir)
  File "python3.6/site-packages/tensorflow_core/python/keras/saving/saved_model/load.py", line 119, in __init__
    self._finalize()
  File "python3.6/site-packages/tensorflow_core/python/keras/saving/saved_model/load.py", line 165, in _finalize
    node._set_inputs(inputs)
  File "python3.6/site-packages/tensorflow_core/python/keras/engine/training.py", line 2647, in _set_inputs
    inputs = self._set_input_attrs(inputs)
  File "python3.6/site-packages/tensorflow_core/python/training/tracking/base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "python3.6/site-packages/tensorflow_core/python/keras/engine/training.py", line 2671, in _set_input_attrs
    raise ValueError('Model inputs are already set.')
ValueError: Model inputs are already set.

```
When loaded with tf.keras in v2.0.0 the layers, model config, inputs, outputs, summary etc. are all parsed correctly, as well as being able to run data through the model.

**Comment by tripathysa** [comment]
[smbnew.zip](https://github.com/tensorflow/tensorflow/files/4478031/smbnew.zip)

**Comment by gadagashwini** [comment]
Was able to replicate the issue with Tf 2.1.
Please find the gist [here](https://colab.sandbox.google.com/gist/gadagashwini/f90b3abd21f828db1212f4dab2a1c5d7/untitled512.ipynb). Thanks!

**Comment by jvishnuvardhan** [comment]
@tripathysa I think this was resolved in recent `tf-nightly`. Please take a look at the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/75bb1d6f47dace0e45c272dfb5428ff0/untitled512.ipynb). If you want to use a stable version, `TF2.2` will be released in near future and this update will reflect in `TF2.2`. 

Please verify once and close the issue if this was resolved for you. Thanks!

**Comment by tripathysa** [comment]
@jvishnuvardhan : Will it be patched in 2.1 as well?

**Comment by jvishnuvardhan** [comment]
@tripathysa I don't think so. But I guess `TF2.2` may be released soon as the last release candidate (rc3) was a week back. Thanks!

**Comment by jvishnuvardhan** [comment]
I am closing the issue as this was resolved. I think stable `TF2.2` will be released in near future. Please feel free to reopen if it persists again later. Thanks!
