### ISSUE TITLE
Error occurs when bazel building the example

### ISSUE THREAD

**Issue by ChenHaoHere** [tensorflow/tensorflow#38568]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Windows 10
- TensorFlow installed from (source or binary):
- TensorFlow version:2.1.0
- Python version:3.7.7
- Installed using virtualenv? pip? conda?:pip
- Bazel version (if compiling from source):2.0.0

**Describe the problem**
Recently I'm studying tensorflow-lite. After cloning the repo and install Bazel2.0.0, I'm trying to build the tf-lite hello-world example. 
**Here's the command**
```shell
cd E:\tensorflow\tensorflow\lite\micro\examples\hello_world
bazel build :sine_model_data
```
**Here's the error message:**
```shell
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=120
INFO: Reading rc options for 'build' from e:\tensorflow\.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Options provided by the client:
  'build' options: --python_path=D:/Anaconda3/envs/tf2.0/python.exe
INFO: Reading rc options for 'build' from e:\tensorflow\.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --java_toolchain=//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=//third_party/toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --enable_platform_specific_config --config=v2
INFO: Found applicable config definition build:v2 in file e:\tensorflow\.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:windows in file e:\tensorflow\.bazelrc: --copt=/w --copt=/D_USE_MATH_DEFINES --host_copt=/D_USE_MATH_DEFINES --cxxopt=/std:c++14 --host_cxxopt=/std:c++14 --config=monolithic --copt=-DWIN32_LEAN_AND_MEAN --host_copt=-DWIN32_LEAN_AND_MEAN --copt=-DNOGDI --host_copt=-DNOGDI --linkopt=/DEBUG --host_linkopt=/DEBUG --linkopt=/OPT:REF --host_linkopt=/OPT:REF --linkopt=/OPT:ICF --host_linkopt=/OPT:ICF --experimental_strict_action_env=true --verbose_failures --distinct_host_configuration=false
INFO: Found applicable config definition build:monolithic in file e:\tensorflow\.bazelrc: --define framework_shared_object=false
INFO: Call stack for the definition of repository 'flatbuffers' which is a third_party_http_archive (rule definition at E:/tensorflow/third_party/repo.bzl:219:28):
 - E:/tensorflow/third_party/flatbuffers/workspace.bzl:6:5
 - E:/tensorflow/tensorflow/workspace.bzl:53:5
 - E:/tensorflow/tensorflow/workspace.bzl:100:5
 - E:/tensorflow/WORKSPACE:19:1
INFO: Repository 'flatbuffers' used the following cache hits instead of downloading the corresponding file.
 * Hash '62f2223fb9181d1d6338451375628975775f7522185266cd5296571ac152bc45' for https://storage.googleapis.com/mirror.tensorflow.org/github.com/google/flatbuffers/archive/v1.12.0.tar.gz
If the definition of 'flatbuffers' was updated, verify that the hashes were also updated.
ERROR: An error occurred during the fetch of repository 'flatbuffers':
   java.io.IOException: Could not create symlink from E:/tensorflow/third_party/flatbuffers/build_defs.bzl to C:/users/chenhao/_bazel_chenhao/3rb265pl/external/flatbuffers/build_defs.bzl: C:/users/chenhao/_bazel_chenhao/3rb265pl/external/flatbuffers/build_defs.bzl (File exists)
DEBUG: Rule 'io_bazel_rules_docker' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1556410077 -0400"
DEBUG: Call stack for the definition of repository 'io_bazel_rules_docker' which is a git_repository (rule definition at C:/users/chenhao/_bazel_chenhao/3rb265pl/external/bazel_tools/tools/build_defs/repo/git.bzl:195:18):
 - C:/users/chenhao/_bazel_chenhao/3rb265pl/external/bazel_toolchains/repositories/repositories.bzl:37:9
 - E:/tensorflow/WORKSPACE:37:1
ERROR: Skipping ':sine_model_data': no such package '@flatbuffers//': java.io.IOException: Could not create symlink from E:/tensorflow/third_party/flatbuffers/build_defs.bzl to C:/users/chenhao/_bazel_chenhao/3rb265pl/external/flatbuffers/build_defs.bzl: C:/users/chenhao/_bazel_chenhao/3rb265pl/external/flatbuffers/build_defs.bzl (File exists)
WARNING: Target pattern parsing failed.
ERROR: no such package '@flatbuffers//': java.io.IOException: Could not create symlink from E:/tensorflow/third_party/flatbuffers/build_defs.bzl to C:/users/chenhao/_bazel_chenhao/3rb265pl/external/flatbuffers/build_defs.bzl: C:/users/chenhao/_bazel_chenhao/3rb265pl/external/flatbuffers/build_defs.bzl (File exists)
INFO: Elapsed time: 2.267s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: tensorflow/lite/micro/examples/hello_world
```

According to the Error, I try to build the flatbuffer first(I don't know whether it'll work, just have a try)
Here's the command
```shell
cd E:\tensorflow\third_party\flatbuffers
bazel build :flatbuffers
```
Here's the output
```shell
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=120
INFO: Reading rc options for 'build' from e:\tensorflow\.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Options provided by the client:
  'build' options: --python_path=D:/Anaconda3/envs/tf2.0/python.exe
INFO: Reading rc options for 'build' from e:\tensorflow\.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --java_toolchain=//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=//third_party/toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --enable_platform_specific_config --config=v2
INFO: Found applicable config definition build:v2 in file e:\tensorflow\.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:windows in file e:\tensorflow\.bazelrc: --copt=/w --copt=/D_USE_MATH_DEFINES --host_copt=/D_USE_MATH_DEFINES --cxxopt=/std:c++14 --host_cxxopt=/std:c++14 --config=monolithic --copt=-DWIN32_LEAN_AND_MEAN --host_copt=-DWIN32_LEAN_AND_MEAN --copt=-DNOGDI --host_copt=-DNOGDI --linkopt=/DEBUG --host_linkopt=/DEBUG --linkopt=/OPT:REF --host_linkopt=/OPT:REF --linkopt=/OPT:ICF --host_linkopt=/OPT:ICF --experimental_strict_action_env=true --verbose_failures --distinct_host_configuration=false
INFO: Found applicable config definition build:monolithic in file e:\tensorflow\.bazelrc: --define framework_shared_object=false
DEBUG: Rule 'io_bazel_rules_docker' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1556410077 -0400"
DEBUG: Call stack for the definition of repository 'io_bazel_rules_docker' which is a git_repository (rule definition at C:/users/chenhao/_bazel_chenhao/3rb265pl/external/bazel_tools/tools/build_defs/repo/git.bzl:195:18):
 - C:/users/chenhao/_bazel_chenhao/3rb265pl/external/bazel_toolchains/repositories/repositories.bzl:37:9
 - E:/tensorflow/WORKSPACE:37:1
INFO: Call stack for the definition of repository 'local_config_python' which is a python_configure (rule definition at E:/tensorflow/third_party/py/python_configure.bzl:280:20):
 - E:/tensorflow/tensorflow/workspace.bzl:96:5
 - E:/tensorflow/WORKSPACE:19:1
ERROR: An error occurred during the fetch of repository 'local_config_python':
   Traceback (most recent call last):
        File "E:/tensorflow/third_party/py/python_configure.bzl", line 263
                _create_local_python_repository(<1 more arguments>)
        File "E:/tensorflow/third_party/py/python_configure.bzl", line 209, in _create_local_python_repository
                _check_python_bin(<2 more arguments>)
        File "E:/tensorflow/third_party/py/python_configure.bzl", line 145, in _check_python_bin
                auto_config_fail(<1 more arguments>)
        File "E:/tensorflow/third_party/remote_config/common.bzl", line 12, in auto_config_fail
                fail(<1 more arguments>)
Configuration Error: --define PYTHON_BIN_PATH='D:\Anaconda3\envs\tf2.0\python.exe
D:\Anaconda3\python.exe
C:\Users\ChenHao\AppData\Local\Microsoft\WindowsApps\python.exe' is not executable. Is it the python binary?
INFO: Call stack for the definition of repository 'rules_java' which is a http_archive (rule definition at C:/users/chenhao/_bazel_chenhao/3rb265pl/external/bazel_tools/tools/build_defs/repo/http.bzl:292:16):
 - C:/users/chenhao/_bazel_chenhao/3rb265pl/external/bazel_tools/tools/build_defs/repo/utils.bzl:205:9
 - /DEFAULT.WORKSPACE.SUFFIX:290:1
ERROR: While resolving toolchains for target //third_party/flatbuffers:flatbuffers: invalid registered toolchain '@local_config_python//:py_toolchain': no such package '@local_config_python//': Traceback (most recent call last):
        File "E:/tensorflow/third_party/py/python_configure.bzl", line 263
                _create_local_python_repository(<1 more arguments>)
        File "E:/tensorflow/third_party/py/python_configure.bzl", line 209, in _create_local_python_repository
                _check_python_bin(<2 more arguments>)
        File "E:/tensorflow/third_party/py/python_configure.bzl", line 145, in _check_python_bin
                auto_config_fail(<1 more arguments>)
        File "E:/tensorflow/third_party/remote_config/common.bzl", line 12, in auto_config_fail
                fail(<1 more arguments>)
Configuration Error: --define PYTHON_BIN_PATH='D:\Anaconda3\envs\tf2.0\python.exe
D:\Anaconda3\python.exe
C:\Users\ChenHao\AppData\Local\Microsoft\WindowsApps\python.exe' is not executable. Is it the python binary?
ERROR: Analysis of target '//third_party/flatbuffers:flatbuffers' failed; build aborted: invalid registered toolchain '@local_config_python//:py_toolchain': no such package '@local_config_python//': Traceback (most recent call last):
        File "E:/tensorflow/third_party/py/python_configure.bzl", line 263
                _create_local_python_repository(<1 more arguments>)
        File "E:/tensorflow/third_party/py/python_configure.bzl", line 209, in _create_local_python_repository
                _check_python_bin(<2 more arguments>)
        File "E:/tensorflow/third_party/py/python_configure.bzl", line 145, in _check_python_bin
                auto_config_fail(<1 more arguments>)
        File "E:/tensorflow/third_party/remote_config/common.bzl", line 12, in auto_config_fail
                fail(<1 more arguments>)
Configuration Error: --define PYTHON_BIN_PATH='D:\Anaconda3\envs\tf2.0\python.exe
D:\Anaconda3\python.exe
C:\Users\ChenHao\AppData\Local\Microsoft\WindowsApps\python.exe' is not executable. Is it the python binary?
INFO: Elapsed time: 20.577s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
    currently loading: @bazel_tools//tools/jdk

```
Why is there an Error about "**PYTHON_BIN_PATH** which is the right path in the output. 

How can I build the example right?

**Comment by thaink** [comment]
@ChenHaoHere
The tflite micro is designed to run on micro controller.
You are building it for PC which is not the appropriate way to use that example.
Could you refer to the README.md file inside tensorflow\lite\micro\examples\hello_world to try it?

**Comment by advaitjain** [comment]
Could you try again? I'm not sure if this issue is specific to the hello_world example.

The following commands worked for me on linux from the root of the tensorflow tree:
```
bazel clean
bazel test tensorflow/lite/micro/examples/hello_world:hello_world_test
```
