### ISSUE TITLE
NotFoundError: Op type not registered 'SentencepieceOp' in binary

### ISSUE THREAD

**Issue by karansaxena** [tensorflow/tensorflow#38597]
**System information** 
- OS Platform and Distribution: Ubuntu 18.04.2 LTS
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.1.0
- Python version: 3.6.10
- CUDA/cuDNN version: CUDA 10.2 
- GPU model and memory: Tesla V100-SXM2-32GB 

**Describe the current behavior**
NotFoundError: Op type not registered 'SentencepieceOp' in binary running on 42c9348a7da5. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.

**Standalone code to reproduce the issue** 
https://tfhub.dev/google/universal-sentence-encoder-multilingual-large/3

**Other info / logs**

Traceback (most recent call last):
  File "/home//anaconda3/envs/tf-test/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3708, in _get_op_def
    return self._op_def_cache[type]
KeyError: 'SentencepieceOp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "create_sentence_embeddings.py", line 19, in <module>
    embed = hub.load("https://tfhub.dev/google/universal-sentence-encoder-multilingual-large/3")
  File "/home//.local/lib/python3.6/site-packages/tensorflow_hub/module_v2.py", line 102, in load
    obj = tf_v1.saved_model.load_v2(module_path, tags=tags)
  File "/home//anaconda3/envs/tf-test/lib/python3.6/site-packages/tensorflow_core/python/saved_model/load.py", line 528, in load
    return load_internal(export_dir, tags)
  File "/home//anaconda3/envs/tf-test/lib/python3.6/site-packages/tensorflow_core/python/saved_model/load.py", line 552, in load_internal
    export_dir)
  File "/home//anaconda3/envs/tf-test/lib/python3.6/site-packages/tensorflow_core/python/saved_model/load.py", line 114, in __init__
    meta_graph.graph_def.library))
  File "/home//anaconda3/envs/tf-test/lib/python3.6/site-packages/tensorflow_core/python/saved_model/function_deserialization.py", line 312, in load_function_def_library
    func_graph = function_def_lib.function_def_to_graph(copy)
  File "/home//anaconda3/envs/tf-test/lib/python3.6/site-packages/tensorflow_core/python/framework/function_def_to_graph.py", line 59, in function_def_to_graph
    fdef, input_shapes)
  File "/home//anaconda3/envs/tf-test/lib/python3.6/site-packages/tensorflow_core/python/framework/function_def_to_graph.py", line 218, in function_def_to_graph_def
    op_def = default_graph._get_op_def(node_def.op)  # pylint: disable=protected-access
  File "/home//anaconda3/envs/tf-test/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3712, in _get_op_def
    c_api.TF_GraphGetOpDef(self._c_graph, compat.as_bytes(type), buf)
tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'SentencepieceOp' in binary running on 3dad5b69905940a4b13b587d16329be5-master-0. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.

**Comment by Saduf2019** [comment]
@karansaxena 
This issue is more suitable for TensorFlow Hub repo. Please post it on [TF Hub repo from here](https://github.com/tensorflow/hub/issues). Thanks!

**Comment by MartinoMensio** [comment]
I had the same issue

As said here https://github.com/tensorflow/hub/issues/463 , installing the `tensorflow_text` dependency solves the issue.

**Comment by Saduf2019** [comment]
@karansaxena 
could you please follow the above mentioned resolution and follow up on hub in case of any issues.
we are proceeding to move this to closed status as its a tensorflow hub issue

**Comment by alexcombessie** [comment]
Solved with
```
!pip install tensorflow_text
import tensorflow_text
```
It's required to import as well for the fix to work

**Comment by NeyoxDrago** [comment]
> Solved with
> 
> ```
> !pip install tensorflow_text
> import tensorflow_text
> ```
> 
> It's required to import as well for the fix to work

This works. Thanks
