### ISSUE TITLE
Not able to import tensorflow

### ISSUE THREAD

**Issue by MaximusFred** [tensorflow/tensorflow#38615]
**System information**
- OS Platform: Windows10
- TensorFlow installed from (source or binary): Installed tensorflow with Python's pip package manager
- TensorFlow version: tensorflow 2
- Python version: Python 3.7.4
- Installed using virtualenv? pip? conda?: pip 20.0.2
- Bazel version (if compiling from source): No
- GCC/Compiler version (if compiling from source): No
- CUDA/cuDNN version: No
- GPU model and memory:

**Describe the problem**
I am not able to import tensorflow after installing it using pip.
I get: ImportError: DLL load failed: The specified module could not be found.
Microsoft Visual C++ Redistributable for Visual Studio 2015 is installed.
Desperate for help.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

```
>>> import tensorflow
Traceback (most recent call last):
  File "C:\Users\A492267\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\A492267\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\A492267\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\A492267\AppData\Local\Continuum\anaconda3\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\A492267\AppData\Local\Continuum\anaconda3\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\A492267\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\__init__.py", line 101, in <module>
    from tensorflow_core import *
  File "C:\Users\A492267\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\A492267\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\Users\A492267\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "C:\Users\A492267\AppData\Local\Continuum\anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\A492267\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\A492267\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\A492267\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\A492267\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\A492267\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\A492267\AppData\Local\Continuum\anaconda3\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\A492267\AppData\Local\Continuum\anaconda3\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

```

**Comment by khimraj** [comment]
@MaximusFred, one solution is downloading and installing visual studio 2015-2019 x86 and x64 from here:[https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads)
Other solution is downgrading tensorflow to 2.0:
`pip install tensorflow==2.0`

**Comment by ravikyram** [comment]
@MaximusFred 

What is make/model of your cpu?
I suspect your cpu model does not support AVX instructions sets.See [hardware requirements](https://www.tensorflow.org/install/pip?lang=python3#hardware-requirements)
Make sure to download [the latest microsoft visual c++ redistributable from here.](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads)
.Also, please follow the instructions from to install from [Tensorflow website](https://www.tensorflow.org/install/source_windows).

Please, check Your CPU/Python is on 32 bits?Please, refer #36167 and see if it helps you.
Also, refer similar issues.
#36167 #36151 #36138 #36054 #36045 #36020 #36003 #35988 #35903 #35880 #35865 #35805 #35789 #35773 #35772 #35767 #35766 #35749 #35721 #35618 #35204
Thanks!

**Comment by MaximusFred** [comment]
Hi,

Thanks for your help.
I did have Visual C++ x64 installed but not x86.
After installation of Visual C++ x86, I could import tensorflow.

Big thank you!
Fredrik

Den fre 17 apr. 2020 kl 05:39 skrev Khimraj <notifications@github.com>:

**Comment by MaximusFred** [comment]
> @MaximusFred
> 
> What is make/model of your cpu?
> I suspect your cpu model does not support AVX instructions sets.See [hardware requirements](https://www.tensorflow.org/install/pip?lang=python3#hardware-requirements)
> Make sure to download [the latest microsoft visual c++ redistributable from here.](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads)
> .Also, please follow the instructions from to install from [Tensorflow website](https://www.tensorflow.org/install/source_windows).
> 
> Please, check Your CPU/Python is on 32 bits?Please, refer #36167 and see if it helps you.
> Also, refer similar issues.
> #36167 #36151 #36138 #36054 #36045 #36020 #36003 #35988 #35903 #35880 #35865 #35805 #35789 #35773 #35772 #35767 #35766 #35749 #35721 #35618 #35204
> Thanks!

Thank's for your help.
It was solved by installing both x64 and x86 of Visual C++. Earlier I had only x64.
//Fredrik

**Comment by mihaimaruseac** [comment]
You need MSVC 2019 redistributable, not the 2015 one.

**Comment by MaximusFred** [comment]
Thanks Mihai!

Yes, I also realized when installing MSVC 2019 also recommended and linked
earlier in this thread then it worked to import tensorflow.

Have a nice weekend!
Fredrik

Den fre 17 apr. 2020 kl 18:38 skrev Mihai Maruseac <notifications@github.com

**Comment by mihaimaruseac** [comment]
Awesome. Closing the issue as it has been resolved.

Also, thanks for the additional data point: we need to tell people to also make sure they install both x64 and x86 versions of Visual C++

**Comment by MaximusFred** [comment]
Hi, Yes this solved the problem with importing tensorflow.

Thanks
Fredrik

Den fre 17 apr. 2020 kl 19:51 skrev Mihai Maruseac <notifications@github.com
