### ISSUE TITLE
ImportError: DLL load failed

### ISSUE THREAD

**Issue by DominikManiak** [tensorflow/tensorflow#38636]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): pip install tensorflow
- TensorFlow version: 2.1
- Python version: 3.7.7 64-bit
- Installed using virtualenv? pip? conda?: no
- CUDA/cuDNN version: 10.1/  v7.6.5 (November 5th, 2019), for CUDA 10.1
- GPU model and memory: GTX 1070 Nividia 8GB
- GPU driver 445.75
- CPU Intel Celeron G3900 2,8 GHz

**Describe the problem**
while trying import tensorflow i got such error below. i used Visual Studio Code, i have tried different versions of tensorflow 2.0, 2.1 ang GPU version - still this problem :(

I have installed newest VC_redist.x64, i have also in my system env variables path to:
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\libnvvp
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\extras\CUPTI\lib64
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include
C:\tools\cuda\bin
C:\tools\cuda\include
C:\tools\cuda\lib\x64

I have tried every solution which a found on Github but nothing works form me, and please help me with it.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
import tensorflow 

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

Traceback (most recent call last):
  File "C:\Users\Dominik\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Dominik\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Dominik\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Dominik\AppData\Local\Programs\Python\Python37\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Dominik\AppData\Local\Programs\Python\Python37\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: Procedura inicjowania biblioteki do\u0142\u0105czanej dynamicznie (DLL) nie powiod\u0142a si\u0119.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Dominik\Documents\Python Scripts\NLP\06-Deep-Learning\import tensorflow.py", line 1, in <module>
    import tensorflow
  File "C:\Users\Dominik\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\__init__.py", line 101, in <module>
    from tensorflow_core import *
  File "C:\Users\Dominik\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\Dominik\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\Users\Dominik\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "C:\Users\Dominik\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\Dominik\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Dominik\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Dominik\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Dominik\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Dominik\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Dominik\AppData\Local\Programs\Python\Python37\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Dominik\AppData\Local\Programs\Python\Python37\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: Procedura inicjowania biblioteki do\u0142\u0105czanej dynamicznie (DLL) nie powiod\u0142a si\u0119.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by khimraj** [comment]
@DominikManiak, one solution is downloading and installing visual studio 2015-2019 x86 and x64 from here:[https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads)
Other solution is downgrading tensorflow to 2.0:
`pip install tensorflow==2.0`

**Comment by DominikManiak** [comment]
> @DominikManiak, one solution is downloading and installing visual studio 2015-2019 x86 and x64 from here:https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads
> Other solution is downgrading tensorflow to 2.0:
> `pip install tensorflow==2.0`

Thank you khimraj!

But... as i described i did both solutions and it did help me! :( Any other ideas?

**Comment by khimraj** [comment]
@DominikManiak, refer issue [#38636](https://github.com/tensorflow/tensorflow/issues/38636).

**Comment by khimraj** [comment]
@ refer issue [#38636](https://github.com/tensorflow/tensorflow/issues/38636).

**Comment by Saduf2019** [comment]
@DominikManiak 
Is your python 64 bits? Your CPU does not support AVX2 instructions?

please refer to below issues.
#36167 (comment)

#36167 #36151 #36138 #36054 #36045 #36020 #36003 #35988 #35903 #35880 #35865 #35805 #35789 #35773 #35772 #35767 #35766 #35749 #35721 #35618 #35204

**Comment by mihaimaruseac** [comment]
Closing as duplicate.

https://github.com/tensorflow/tensorflow/issues/36167#issuecomment-577886156

#36167 #36151 #36138 #36054 #36045 #36020 #36003 #35988 #35903 #35880 #35865 #35805 #35789 #35773 #35772 #35767 #35766 #35749 #35721 #35618 #35204
