### ISSUE TITLE
tf2+yolov3 Convert to tflite quession

### ISSUE THREAD

**Issue by pengshichang** [tensorflow/tensorflow#38659]
o use: AVX2
Model: "yolov3"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to
==================================================================================================
input (InputLayer)              [(None, None, None,  0
__________________________________________________________________________________________________
yolo_darknet (Model)            ((None, None, None,  40620640    input[0][0]
__________________________________________________________________________________________________
yolo_conv_0 (Model)             (None, None, None, 5 11024384    yolo_darknet[1][2]
__________________________________________________________________________________________________
yolo_conv_1 (Model)             (None, None, None, 2 2957312     yolo_conv_0[1][0]
                                                                 yolo_darknet[1][1]
__________________________________________________________________________________________________
yolo_conv_2 (Model)             (None, None, None, 1 741376      yolo_conv_1[1][0]
                                                                 yolo_darknet[1][0]
__________________________________________________________________________________________________
yolo_output_0 (Model)           (None, None, None, 3 4984063     yolo_conv_0[1][0]
__________________________________________________________________________________________________
yolo_output_1 (Model)           (None, None, None, 3 1312511     yolo_conv_1[1][0]
__________________________________________________________________________________________________
yolo_output_2 (Model)           (None, None, None, 3 361471      yolo_conv_2[1][0]
__________________________________________________________________________________________________
yolo_boxes_0 (Lambda)           ((None, None, None,  0           yolo_output_0[1][0]
__________________________________________________________________________________________________
yolo_boxes_1 (Lambda)           ((None, None, None,  0           yolo_output_1[1][0]
__________________________________________________________________________________________________
yolo_boxes_2 (Lambda)           ((None, None, None,  0           yolo_output_2[1][0]
__________________________________________________________________________________________________
yolo_nms (Lambda)               ((None, 100, 4), (No 0           yolo_boxes_0[0][0]
                                                                 yolo_boxes_0[0][1]
                                                                 yolo_boxes_0[0][2]
                                                                 yolo_boxes_1[0][0]
                                                                 yolo_boxes_1[0][1]
                                                                 yolo_boxes_1[0][2]
                                                                 yolo_boxes_2[0][0]
                                                                 yolo_boxes_2[0][1]
                                                                 yolo_boxes_2[0][2]
==================================================================================================
Total params: 62,001,757
Trainable params: 61,949,149
Non-trainable params: 52,608
__________________________________________________________________________________________________
I0418 07:57:30.913888 54352 convert.py:19] model created
I0418 07:57:30.922950 54352 utils.py:45] yolo_darknet/conv2d bn
I0418 07:57:30.924918 54352 utils.py:45] yolo_darknet/conv2d_1 bn
I0418 07:57:30.926922 54352 utils.py:45] yolo_darknet/conv2d_2 bn
I0418 07:57:30.928931 54352 utils.py:45] yolo_darknet/conv2d_3 bn
I0418 07:57:30.933943 54352 utils.py:45] yolo_darknet/conv2d_4 bn
I0418 07:57:30.936951 54352 utils.py:45] yolo_darknet/conv2d_5 bn
I0418 07:57:30.939996 54352 utils.py:45] yolo_darknet/conv2d_6 bn
I0418 07:57:30.944971 54352 utils.py:45] yolo_darknet/conv2d_7 bn
I0418 07:57:30.947012 54352 utils.py:45] yolo_darknet/conv2d_8 bn
I0418 07:57:30.948982 54352 utils.py:45] yolo_darknet/conv2d_9 bn
I0418 07:57:30.956000 54352 utils.py:45] yolo_darknet/conv2d_10 bn
I0418 07:57:30.960010 54352 utils.py:45] yolo_darknet/conv2d_11 bn
I0418 07:57:30.966026 54352 utils.py:45] yolo_darknet/conv2d_12 bn
I0418 07:57:30.970039 54352 utils.py:45] yolo_darknet/conv2d_13 bn
I0418 07:57:30.973078 54352 utils.py:45] yolo_darknet/conv2d_14 bn
I0418 07:57:30.976053 54352 utils.py:45] yolo_darknet/conv2d_15 bn
I0418 07:57:30.981098 54352 utils.py:45] yolo_darknet/conv2d_16 bn
I0418 07:57:30.983071 54352 utils.py:45] yolo_darknet/conv2d_17 bn
I0418 07:57:30.989118 54352 utils.py:45] yolo_darknet/conv2d_18 bn
I0418 07:57:30.991132 54352 utils.py:45] yolo_darknet/conv2d_19 bn
I0418 07:57:30.996108 54352 utils.py:45] yolo_darknet/conv2d_20 bn
I0418 07:57:30.998111 54352 utils.py:45] yolo_darknet/conv2d_21 bn
I0418 07:57:31.002122 54352 utils.py:45] yolo_darknet/conv2d_22 bn
I0418 07:57:31.004158 54352 utils.py:45] yolo_darknet/conv2d_23 bn
I0418 07:57:31.007134 54352 utils.py:45] yolo_darknet/conv2d_24 bn
I0418 07:57:31.010144 54352 utils.py:45] yolo_darknet/conv2d_25 bn
I0418 07:57:31.014154 54352 utils.py:45] yolo_darknet/conv2d_26 bn
I0418 07:57:31.026219 54352 utils.py:45] yolo_darknet/conv2d_27 bn
I0418 07:57:31.029193 54352 utils.py:45] yolo_darknet/conv2d_28 bn
I0418 07:57:31.041259 54352 utils.py:45] yolo_darknet/conv2d_29 bn
I0418 07:57:31.044235 54352 utils.py:45] yolo_darknet/conv2d_30 bn
I0418 07:57:31.055304 54352 utils.py:45] yolo_darknet/conv2d_31 bn
I0418 07:57:31.058273 54352 utils.py:45] yolo_darknet/conv2d_32 bn
I0418 07:57:31.068298 54352 utils.py:45] yolo_darknet/conv2d_33 bn
I0418 07:57:31.071306 54352 utils.py:45] yolo_darknet/conv2d_34 bn
I0418 07:57:31.085376 54352 utils.py:45] yolo_darknet/conv2d_35 bn
I0418 07:57:31.088377 54352 utils.py:45] yolo_darknet/conv2d_36 bn
I0418 07:57:31.100429 54352 utils.py:45] yolo_darknet/conv2d_37 bn
I0418 07:57:31.103426 54352 utils.py:45] yolo_darknet/conv2d_38 bn
I0418 07:57:31.116426 54352 utils.py:45] yolo_darknet/conv2d_39 bn
I0418 07:57:31.119471 54352 utils.py:45] yolo_darknet/conv2d_40 bn
I0418 07:57:31.130496 54352 utils.py:45] yolo_darknet/conv2d_41 bn
I0418 07:57:31.133472 54352 utils.py:45] yolo_darknet/conv2d_42 bn
I0418 07:57:31.147543 54352 utils.py:45] yolo_darknet/conv2d_43 bn
I0418 07:57:31.193630 54352 utils.py:45] yolo_darknet/conv2d_44 bn
I0418 07:57:31.200688 54352 utils.py:45] yolo_darknet/conv2d_45 bn
I0418 07:57:31.245767 54352 utils.py:45] yolo_darknet/conv2d_46 bn
I0418 07:57:31.252820 54352 utils.py:45] yolo_darknet/conv2d_47 bn
I0418 07:57:31.299911 54352 utils.py:45] yolo_darknet/conv2d_48 bn
I0418 07:57:31.307933 54352 utils.py:45] yolo_darknet/conv2d_49 bn
I0418 07:57:31.353052 54352 utils.py:45] yolo_darknet/conv2d_50 bn
I0418 07:57:31.361075 54352 utils.py:45] yolo_darknet/conv2d_51 bn
I0418 07:57:31.404188 54352 utils.py:45] yolo_conv_0/conv2d_52 bn
I0418 07:57:31.411207 54352 utils.py:45] yolo_conv_0/conv2d_53 bn
I0418 07:57:31.459374 54352 utils.py:45] yolo_conv_0/conv2d_54 bn
I0418 07:57:31.466355 54352 utils.py:45] yolo_conv_0/conv2d_55 bn
I0418 07:57:31.511475 54352 utils.py:45] yolo_conv_0/conv2d_56 bn
I0418 07:57:31.518527 54352 utils.py:45] yolo_output_0/conv2d_57 bn
I0418 07:57:31.562608 54352 utils.py:45] yolo_output_0/conv2d_58 bias
I0418 07:57:31.566619 54352 utils.py:45] yolo_conv_1/conv2d_59 bn
I0418 07:57:31.568628 54352 utils.py:45] yolo_conv_1/conv2d_60 bn
I0418 07:57:31.570631 54352 utils.py:45] yolo_conv_1/conv2d_61 bn
I0418 07:57:31.579694 54352 utils.py:45] yolo_conv_1/conv2d_62 bn
I0418 07:57:31.582699 54352 utils.py:45] yolo_conv_1/conv2d_63 bn
I0418 07:57:31.591723 54352 utils.py:45] yolo_conv_1/conv2d_64 bn
I0418 07:57:31.593731 54352 utils.py:45] yolo_output_1/conv2d_65 bn
I0418 07:57:31.602754 54352 utils.py:45] yolo_output_1/conv2d_66 bias
I0418 07:57:31.604759 54352 utils.py:45] yolo_conv_2/conv2d_67 bn
I0418 07:57:31.605724 54352 utils.py:45] yolo_conv_2/conv2d_68 bn
I0418 07:57:31.606727 54352 utils.py:45] yolo_conv_2/conv2d_69 bn
I0418 07:57:31.609774 54352 utils.py:45] yolo_conv_2/conv2d_70 bn
I0418 07:57:31.610738 54352 utils.py:45] yolo_conv_2/conv2d_71 bn
I0418 07:57:31.613745 54352 utils.py:45] yolo_conv_2/conv2d_72 bn
I0418 07:57:31.614750 54352 utils.py:45] yolo_output_2/conv2d_73 bn
I0418 07:57:31.617794 54352 utils.py:45] yolo_output_2/conv2d_74 bias
I0418 07:57:31.618758 54352 convert.py:22] weights loaded
I0418 07:57:32.081988 54352 convert.py:26] sanity check passed
I0418 07:57:32.725983 54352 convert.py:29] weights saved

(yolov3-tf2-cpu) C:\Users\EZSHIPE\Downloads\yolov3-tf2-peng\yolov3-tf2-master>
(yolov3-tf2-cpu) C:\Users\EZSHIPE\Downloads\yolov3-tf2-peng\yolov3-tf2-master>python tools/export_tflite.py
2020-04-18 07:58:00.586491: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not fo
und
2020-04-18 07:58:00.591208: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2020-04-18 07:58:08.994699: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'nvcuda.dll'; dlerror: nvcuda.dll not found
2020-04-18 07:58:08.999120: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: UNKNOWN ERROR (303)
2020-04-18 07:58:09.008186: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: CN-00012968
2020-04-18 07:58:09.012520: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: CN-00012968
2020-04-18 07:58:09.015456: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
I0418 07:58:14.900625 14620 export_tflite.py:34] weights loaded
2020-04-18 07:58:15.624135: I tensorflow/core/grappler/devices.cc:55] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2020-04-18 07:58:15.628949: I tensorflow/core/grappler/clusters/single2020-04-18 07:58:15.676348: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:814] Optimization res
ults for grappler item: graph_to_optimize
2020-04-18 07:58:15.680926: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   function_optimizer: function_optimizer did nothing. time = 0.005ms.
2020-04-18 07:58:15.685573: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   function_optimizer: function_optimizer did nothing. time = 0ms.
2020-04-18 07:58:22.022971: I tensorflow/core/grappler/devices.cc:55] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2020-04-18 07:58:22.027511: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2020-04-18 07:58:26.747778: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:814] Optimization results for grappler item: graph_to_optimize
2020-04-18 07:58:26.751954: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   constant_folding: Graph size after: 993 nodes (-366), 2545 edges (-366), time = 3012
.25903ms.
2020-04-18 07:58:26.755753: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   constant_folding: Graph size after: 993 nodes (0), 2545 edges (0), time = 833.124ms.

Traceback (most recent call last):
  File "tools/export_tflite.py", line 65, in <module>
    app.run(main)
  File "C:\Users\EZSHIPE\.conda\envs\yolov3-tf2-cpu\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "C:\Users\EZSHIPE\.conda\envs\yolov3-tf2-cpu\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "tools/export_tflite.py", line 37, in main
    tflite_model = converter.convert()
  File "C:\Users\EZSHIPE\.conda\envs\yolov3-tf2-cpu\lib\site-packages\tensorflow_core\lite\python\lite.py", line 464, in convert
    **converter_kwargs)
  File "C:\Users\EZSHIPE\.conda\envs\yolov3-tf2-cpu\lib\site-packages\tensorflow_core\lite\python\convert.py", line 457, in toco_convert_impl
    enable_mlir_converter=enable_mlir_converter)
  File "C:\Users\EZSHIPE\.conda\envs\yolov3-tf2-cpu\lib\site-packages\tensorflow_core\lite\python\convert.py", line 203, in toco_convert_protos
    raise ConverterError("See console for info.\n%s\n%s\n" % (stdout, stderr))
tensorflow.lite.python.convert.ConverterError: See console for info.
2020-04-18 07:58:29.920472: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not fo
und
2020-04-18 07:58:29.920864: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2020-04-18 07:58:39.215598: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Size
2020-04-18 07:58:39.215864: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Size
2020-04-18 07:58:39.216436: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Size
2020-04-18 07:58:39.216683: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Size
2020-04-18 07:58:39.217119: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Size
2020-04-18 07:58:39.217325: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: Size
2020-04-18 07:58:39.217665: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: CombinedNonMaxSuppression
2020-04-18 07:58:39.276378: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 735 operators, 1368 arrays (0 quantized)
2020-04-18 07:58:39.295435: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 735 operators, 1368 arrays (0 quant
ized)
2020-04-18 07:58:39.987076: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 1: 284 operators, 533 arrays (0
quantized)
2020-04-18 07:58:39.993843: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 2: 284 operators, 533 arrays (0
quantized)
2020-04-18 07:58:40.000453: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Group bidirectional sequence lstm/rnn: 284 operators, 533 arrays (
0 quantized)
2020-04-18 07:58:40.005543: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before dequantization graph transformations: 284 operators, 533 arrays (0
 quantized)
2020-04-18 07:58:40.009657: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Identify nearest upsample.: 284 operators, 533 arrays (0 quantized
)
2020-04-18 07:58:40.020140: I tensorflow/lite/toco/allocate_transient_arrays.cc:345] Total transient array allocated size: 66560128 bytes, theoretical optimal value: 44408960
bytes.
2020-04-18 07:58:40.021499: I tensorflow/lite/toco/toco_tooling.cc:471] Number of parameters: 61923215
2020-04-18 07:58:40.029275: E tensorflow/lite/toco/toco_tooling.cc:498] We are continually in the process of adding support to TensorFlow Lite for more ops. It would be helpfu
l if you could inform us of how this conversion went by opening a github issue at https://github.com/tensorflow/tensorflow/issues/new?template=40-tflite-op-request.md
 and pasting the following:

Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended r
untime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implem
entation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin ope
rators you are using: ADD, CAST, CONCATENATION, CONV_2D, DIV, EXP, EXPAND_DIMS, FILL, LEAKY_RELU, LOGISTIC, MUL, PACK, PAD, RESHAPE, RESIZE_NEAREST_NEIGHBOR, SHAPE, SPLIT_V, S
TRIDED_SLICE, SUB. Here is a list of operators for which you will need custom implementations: CombinedNonMaxSuppression, Size.
Traceback (most recent call last):
  File "c:\users\ezshipe\.conda\envs\yolov3-tf2-cpu\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\ezshipe\.conda\envs\yolov3-tf2-cpu\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\EZSHIPE\.conda\envs\yolov3-tf2-cpu\Scripts\toco_from_protos.exe\__main__.py", line 7, in <module>
  File "c:\users\ezshipe\.conda\envs\yolov3-tf2-cpu\lib\site-packages\tensorflow_core\lite\toco\python\toco_from_protos.py", line 93, in main
    app.run(main=execute, argv=[sys.argv[0]] + unparsed)
  File "c:\users\ezshipe\.conda\envs\yolov3-tf2-cpu\lib\site-packages\tensorflow_core\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "c:\users\ezshipe\.conda\envs\yolov3-tf2-cpu\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "c:\users\ezshipe\.conda\envs\yolov3-tf2-cpu\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "c:\users\ezshipe\.conda\envs\yolov3-tf2-cpu\lib\site-packages\tensorflow_core\lite\toco\python\toco_from_protos.py", line 56, in execute
    enable_mlir_converter)
Exception: We are continually in the process of adding support to TensorFlow Lite for more ops. It would be helpful if you could inform us of how this conversion went by openi
ng a github issue at https://github.com/tensorflow/tensorflow/issues/new?template=40-tflite-op-request.md
 and pasting the following:

Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended r
untime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implem
entation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin ope
rators you are using: ADD, CAST, CONCATENATION, CONV_2D, DIV, EXP, EXPAND_DIMS, FILL, LEAKY_RELU, LOGISTIC, MUL, PACK, PAD, RESHAPE, RESIZE_NEAREST_NEIGHBOR, SHAPE, SPLIT_V, S
TRIDED_SLICE, SUB. Here is a list of operators for which you will need custom implementations: CombinedNonMaxSuppression, Size.

**Comment by ravikyram** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version.Please, fill [issue template.](https://github.com/tensorflow/tensorflow/issues/new/choose).Make sure you also include the code snippet to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by thaink** [comment]
@teijeong 
Can you link to the tflite-supported yolo model?

**Comment by teijeong** [comment]
I don't have model file available for now - I've fixed 5D tensor usage in the model (https://github.com/YunYang1994/tensorflow-yolov3/pull/312), but it seems the problem here is some unsupported ops:
"CombinedNonMaxSuppression, Size"

**Comment by ymodak** [comment]
I think this was resolved with the above comment. Please test with latest stable TF 2.6 version and open a new issue if problem still persists. Thanks!
