### ISSUE TITLE
Build from sources: An error occurred during the fetch of repository 'local_config_cuda'

### ISSUE THREAD

**Issue by AndreyM0** [tensorflow/tensorflow#38660]
**System information**
- OS Platform and Distribution: Linux Ubuntu 18.04
- TensorFlow installed from: source
- TensorFlow version: 3.0.0 
- Python version: 3.6.9
- Bazel version (if compiling from source): 2.1.0
- GCC/Compiler version (if compiling from source):7.5.0
- CUDA/cuDNN version: 10.2
- GPU model and memory: NVIDIA QUADRO K600

**Problem**
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd1 in position 70: ordinal not in range(128)

**Sequence of commands**
bazel build  //tensorflow/tools/pip_package:build_pip_packageDD

**logs**

ERROR: An error occurred during the fetch of repository 'local_config_cuda':
   Traceback (most recent call last):
	File "/home/andrey/tensorflow/third_party/gpus/cuda_configure.bzl", line 1213
		_create_local_cuda_repository(<1 more arguments>)
	File "/home/andrey/tensorflow/third_party/gpus/cuda_configure.bzl", line 935, in _create_local_cuda_repository
		_find_libs(repository_ctx, <2 more arguments>)
	File "/home/andrey/tensorflow/third_party/gpus/cuda_configure.bzl", line 578, in _find_libs
		_check_cuda_libs(repository_ctx, <2 more arguments>)
	File "/home/andrey/tensorflow/third_party/gpus/cuda_configure.bzl", line 480, in _check_cuda_libs
		execute(repository_ctx, <1 more arguments>)
	File "/home/andrey/tensorflow/third_party/remote_config/common.bzl", line 208, in execute
		fail(<1 more arguments>)
Repository command failed
Traceback (most recent call last):
  File "script.py", line 88, in <module>
    main()
  File "script.py", line 77, in main
    check_cuda_lib(path, check_soname=args[i + 1] == "True")
  File "script.py", line 62, in check_cuda_lib
    output = subprocess.check_output([objdump, "-p", path]).decode("ascii")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd1 in position 70: ordinal not in range(128)
ERROR: Skipping '//tensorflow/tools/pip_package:build_pip_package': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
	File "/home/andrey/tensorflow/third_party/gpus/cuda_configure.bzl", line 1213
		_create_local_cuda_repository(<1 more arguments>)
	File "/home/andrey/tensorflow/third_party/gpus/cuda_configure.bzl", line 935, in _create_local_cuda_repository
		_find_libs(repository_ctx, <2 more arguments>)
	File "/home/andrey/tensorflow/third_party/gpus/cuda_configure.bzl", line 578, in _find_libs
		_check_cuda_libs(repository_ctx, <2 more arguments>)
	File "/home/andrey/tensorflow/third_party/gpus/cuda_configure.bzl", line 480, in _check_cuda_libs
		execute(repository_ctx, <1 more arguments>)
	File "/home/andrey/tensorflow/third_party/remote_config/common.bzl", line 208, in execute
		fail(<1 more arguments>)
Repository command failed
Traceback (most recent call last):
  File "script.py", line 88, in <module>
    main()
  File "script.py", line 77, in main
    check_cuda_lib(path, check_soname=args[i + 1] == "True")
  File "script.py", line 62, in check_cuda_lib
    output = subprocess.check_output([objdump, "-p", path]).decode("ascii")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd1 in position 70: ordinal not in range(128)
WARNING: Target pattern parsing failed.
ERROR: no such package '@local_config_cuda//cuda': Traceback (most recent call last):
	File "/home/andrey/tensorflow/third_party/gpus/cuda_configure.bzl", line 1213
		_create_local_cuda_repository(<1 more arguments>)
	File "/home/andrey/tensorflow/third_party/gpus/cuda_configure.bzl", line 935, in _create_local_cuda_repository
		_find_libs(repository_ctx, <2 more arguments>)
	File "/home/andrey/tensorflow/third_party/gpus/cuda_configure.bzl", line 578, in _find_libs
		_check_cuda_libs(repository_ctx, <2 more arguments>)
	File "/home/andrey/tensorflow/third_party/gpus/cuda_configure.bzl", line 480, in _check_cuda_libs
		execute(repository_ctx, <1 more arguments>)
	File "/home/andrey/tensorflow/third_party/remote_config/common.bzl", line 208, in execute
		fail(<1 more arguments>)
Repository command failed
Traceback (most recent call last):
  File "script.py", line 88, in <module>
    main()
  File "script.py", line 77, in main
    check_cuda_lib(path, check_soname=args[i + 1] == "True")
  File "script.py", line 62, in check_cuda_lib
    output = subprocess.check_output([objdump, "-p", path]).decode("ascii")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd1 in position 70: ordinal not in range(128)
INFO: Elapsed time: 9.036s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: tensorflow/tools/pip_package

**Comment by Saduf2019** [comment]
@AndreyM0 
please refer to these issues with similar error and let us know if it helps:

#37748 #37995 #34552 #33879 #36132 #32363 #34146

**Comment by kay0u** [comment]
This small patch fix the issue on my side: #38940

**Comment by Saduf2019** [comment]
@AndreyM0
please update as per above comment

**Comment by AndreyM0** [comment]
This small patch work.
But when I compile
bazel build //tensorflow/tools/pip_package:build_pip_package --jobs=1
...
[14,447 / 15,968] Comiling .../core/kernels/pad_op_gpu.cu.cc; 10s local
computer freezes

**Comment by lijiansong** [comment]
> File "script.py", line 88, in

all not work for me
