### ISSUE TITLE
TFLiteConverter ConverterError with tf.float16 layers

### ISSUE THREAD

**Issue by HauserA** [tensorflow/tensorflow#38662]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): colab
- TensorFlow installed from (source or binary): colab
- TensorFlow version (or github SHA if from source): 2.2.0-rc3

**Command used to run the converter or code if you’re using the Python API**

Colab:
https://colab.research.google.com/drive/1yLEzIz2O1opjQDHUTaZJGRSgg8DKHfeW

To get Error1:
```
import tensorflow as tf

input_layer = tf.keras.layers.Input(shape=(224,224,3), dtype=tf.float16)
final = tf.keras.layers.Dense(10, dtype=tf.float32)(input_layer)
model = tf.keras.models.Model(input_layer, final)

converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]

quantized_tflite_model = converter.convert()
```

To get Error2:
```
import tensorflow as tf

input_layer = tf.keras.layers.Input(shape=(224,224,3))
final = tf.keras.layers.Dense(10, dtype=tf.float16)(input_layer)
model = tf.keras.models.Model(input_layer, final)

converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]

quantized_tflite_model = converter.convert()
```

**The output from the converter invocation**

Error1:
```
---------------------------------------------------------------------------
ConverterError                            Traceback (most recent call last)
<ipython-input-3-cfb1369fd448> in <module>()
      2 converter.optimizations = [tf.lite.Optimize.DEFAULT]
      3 
----> 4 quantized_tflite_model = converter.convert()

2 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/convert.py in toco_convert_protos(model_flags_str, toco_flags_str, input_data_str, debug_info_str, enable_mlir_converter)
    225       stdout = _try_convert_to_unicode(stdout)
    226       stderr = _try_convert_to_unicode(stderr)
--> 227       raise ConverterError("See console for info.\n%s\n%s\n" % (stdout, stderr))
    228   finally:
    229     # Must manually cleanup files.

ConverterError: See console for info.
Traceback (most recent call last):
  File "/usr/local/bin/toco_from_protos", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 93, in main
    app.run(main=execute, argv=[sys.argv[0]] + unparsed)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 56, in execute
    enable_mlir_converter)
Exception: Use '' if want to use the type from graph.

```

Error2:
```

---------------------------------------------------------------------------
ConverterError                            Traceback (most recent call last)
<ipython-input-5-cfb1369fd448> in <module>()
      2 converter.optimizations = [tf.lite.Optimize.DEFAULT]
      3 
----> 4 quantized_tflite_model = converter.convert()

2 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/convert.py in toco_convert_protos(model_flags_str, toco_flags_str, input_data_str, debug_info_str, enable_mlir_converter)
    225       stdout = _try_convert_to_unicode(stdout)
    226       stderr = _try_convert_to_unicode(stderr)
--> 227       raise ConverterError("See console for info.\n%s\n%s\n" % (stdout, stderr))
    228   finally:
    229     # Must manually cleanup files.

ConverterError: See console for info.
2020-04-18 02:25:05.438485: W tensorflow/compiler/mlir/lite/python/graphdef_to_tfl_flatbuffer.cc:89] Ignored output_format.
2020-04-18 02:25:05.438531: W tensorflow/compiler/mlir/lite/python/graphdef_to_tfl_flatbuffer.cc:95] Ignored drop_control_dependency.
2020-04-18 02:25:05.460283: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
loc(callsite("model_1/dense_1/Cast"("/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py":865:0) at callsite("/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py":959:0 at callsite("/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/lite.py":435:0 at callsite("<ipython-input-5-cfb1369fd448>":1:0 at callsite("/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py":2882:0 at callsite("/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py":2822:0 at callsite("/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py":2718:0 at callsite("/usr/local/lib/python3.6/dist-packages/ipykernel/zmqshell.py":537:0 at callsite("/usr/local/lib/python3.6/dist-packages/ipykernel/ipkernel.py":208:0 at "/usr/local/lib/python3.6/dist-packages/ipykernel/kernelbase.py":399:0)))))))))): error: 'tfl.cast' op result #0 must be tensor of 32-bit float or 1-bit integer or 32-bit integer or 64-bit integer values, but got 'tensor<1x224x224x3xf16>'
Traceback (most recent call last):
  File "/usr/local/bin/toco_from_protos", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 93, in main
    app.run(main=execute, argv=[sys.argv[0]] + unparsed)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 56, in execute
    enable_mlir_converter)
Exception: /usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py:865:9: error: 'tfl.cast' op result #0 must be tensor of 32-bit float or 1-bit integer or 32-bit integer or 64-bit integer values, but got 'tensor<1x224x224x3xf16>'
        self._initialize(args, kwargs, add_initializers_to=initializers)
        ^
/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py:959:5: note: called from
    concrete = self._get_concrete_function_garbage_collected(*args, **kwargs)
    ^
/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/lite.py:435:5: note: called from
    concrete_func = func.get_concrete_function()
    ^
<ipython-input-5-cfb1369fd448>: note: called from
/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2882:17: note: called from
                exec(code_obj, self.user_global_ns, self.user_ns)
                ^
/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2822:17: note: called from
                if self.run_code(code, result):
                ^
/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718:20: note: called from
                   interactivity=interactivity, compiler=compiler, result=result)
                   ^
/usr/local/lib/python3.6/dist-packages/ipykernel/zmqshell.py:537:9: note: called from
        return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
        ^
/usr/local/lib/python3.6/dist-packages/ipykernel/ipkernel.py:208:13: note: called from
            res = shell.run_cell(code, store_history=store_history, silent=silent)
            ^
/usr/local/lib/python3.6/dist-packages/ipykernel/kernelbase.py:399:41: note: called from
                                        user_expressions, allow_stdin)
                                        ^




```

**Failure details**
TFLiteConverter throws a ConverterError if a layer is build with dtype=tf.float16

**Comment by amahendrakar** [comment]
@HauserA,
I was able to reproduce the issue with [TF v2.2.0-rc3](https://colab.research.google.com/gist/amahendrakar/f224587803b856ee70613173638b04f1/38662.ipynb#scrollTo=6MVh8zlXA2DX). However, running the code with [TF-nightly](https://colab.research.google.com/gist/amahendrakar/92107cf4dac1453d9c630b7d2e878788/38662-tf-nightly.ipynb) and adding the below two lines of code seems to work.

```
converter.experimental_new_converter = True
converter.target_spec.supported_ops =[tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS] 
```

Please find the attached gist. Thanks!

**Comment by HauserA** [comment]
Thank you. I will use tf-nightly.
