### ISSUE TITLE
Failed to load the native TensorFlow runtime.

### ISSUE THREAD

**Issue by Wolverinne** [tensorflow/tensorflow#38677]
hi, installed tensorflow version 2.1 using pip command anaconda with windows 10 64 bit python 3.6 and getting this issue ,cant find any solution  to this anywhere  ,any help would be appreciated .
i am installing it for cpu not gpu .
![Screenshot (17)](https://user-images.githubusercontent.com/49184195/79679691-bcbb1700-8225-11ea-8ebe-9aadaeb24d61.png)

Traceback (most recent call last):
  File "C:\Users\yadav\Anaconda3\envs\tensor\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\yadav\Anaconda3\envs\tensor\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\yadav\Anaconda3\envs\tensor\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\yadav\Anaconda3\envs\tensor\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\yadav\Anaconda3\envs\tensor\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/yadav/PycharmProjects/tensor/tensor.py", line 1, in <module>
    import tensorflow
  File "C:\Users\yadav\Anaconda3\envs\tensor\lib\site-packages\tensorflow\__init__.py", line 101, in <module>
    from tensorflow_core import *
  File "C:\Users\yadav\Anaconda3\envs\tensor\lib\site-packages\tensorflow_core\__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\yadav\Anaconda3\envs\tensor\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\Users\yadav\Anaconda3\envs\tensor\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "C:\Users\yadav\Anaconda3\envs\tensor\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\yadav\Anaconda3\envs\tensor\lib\site-packages\tensorflow_core\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\yadav\Anaconda3\envs\tensor\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\yadav\Anaconda3\envs\tensor\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\yadav\Anaconda3\envs\tensor\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\yadav\Anaconda3\envs\tensor\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\yadav\Anaconda3\envs\tensor\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\yadav\Anaconda3\envs\tensor\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

**Comment by Wolverinne** [comment]
in response to the automated reply , my cpu does support avx instruction set  as i use intel i7 6th gen 
attaching the details
![Screenshot (19)](https://user-images.githubusercontent.com/49184195/79679841-048e6e00-8227-11ea-95da-bb4523fe9c4c.png)

**Comment by Saduf2019** [comment]
@Wolverinne 
Is your python 64 bits? 

please refer to below issues.
#36167 (comment)

#36167 #36151 #36138 #36054 #36045 #36020 #36003 #35988 #35903 #35880 #35865 #35805 #35789 #35773 #35772 #35767 #35766 #35749 #35721 #35618 #35204

**Comment by Wolverinne** [comment]
thanks @Saduf2019 after reading comments i downgraded from tensorflow 2.1 to 2.0 and the issue is resolved.
if anyone else finds same error try-
pip install tensorflow=2.0.0
