### ISSUE TITLE
Tensorflow hangs, requires reboot

### ISSUE THREAD

**Issue by jostheim** [tensorflow/tensorflow#38699]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):

Yes

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):

Linux Ubuntu 18.04

- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:

N/A

- TensorFlow installed from (source or binary):

binary

- TensorFlow version (use command below):

v2.1.0-rc2-17-ge5bf8de 
2.1.0

- Python version:

3.7.7

- Bazel version (if compiling from source):

N/A

- GCC/Compiler version (if compiling from source):

N/A

- CUDA/cuDNN version:

10.1

- GPU model and memory:

GTX 1080ti 11GB

**Describe the current behavior**

Using TF dataset after ~1000 batches TF hangs, nvidia-smi reports 100% usage (but fan is at 0% so that is bogus).  After I kill the process I get an XLI warning in nvidia-smi and have to reboot to try again.  

I have the same version of this code running with a Keras sequence and multiprocessing and it runs fine.  It is actually faster than the TF dataset code, keeping my GPU pegged at 60% where the TF dataset only does around 50% (while it is running but it hangs pretty fast).  

I have the GUI turned off for Ubuntu and TF is the only process on my GPU and it is set to keep all the memory.  There are no other signficant processes on the machine.  The machine is brand new with 128GB of RAM, NVM hard drives and 12 core AMD Ryzen (so speed should not be an issue).

**Describe the expected behavior**

TF not to hang and force me to reboot, as well as TF dataset to be faster than a keras sequence with multiprocessing.

**Standalone code to reproduce the issue**

This is really hard to do, I have thousands of lines of code that go into running this, plus 400 GB of data.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

GDB output below, when it hangs out, I ctrl-c and bt to get this.  If there is a better way to get a stacktrace where it hangs let me know and I'll do it.

```
(gdb) bt
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00007fff7f9d5b1b in nsync::nsync_mu_semaphore_p_with_deadline(nsync::nsync_semaphore_s_*, timespec) ()
   from /home/jostheim/virtualenvs/data_science/lib/python3.7/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so
#2  0x00007fff7f9d5139 in nsync::nsync_sem_wait_with_cancel_(nsync::waiter*, timespec, nsync::nsync_note_s_*) ()
   from /home/jostheim/virtualenvs/data_science/lib/python3.7/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so
#3  0x00007fff7f9d26fb in nsync::nsync_cv_wait_with_deadline_generic(nsync::nsync_cv_s_*, void*, void (*)(void*), void (*)(void*), timespec, nsync::nsync_note_s_*) ()
   from /home/jostheim/virtualenvs/data_science/lib/python3.7/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so
#4  0x00007fff7f9d2bd3 in nsync::nsync_cv_wait_with_deadline(nsync::nsync_cv_s_*, nsync::nsync_mu_s_*, timespec, nsync::nsync_note_s_*) ()
   from /home/jostheim/virtualenvs/data_science/lib/python3.7/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so
#5  0x00007fff77ab888c in tensorflow::KernelAndDeviceFunc::Run(tensorflow::ScopedStepContainer*, tensorflow::EagerKernelArgs const&, std::vector<tensorflow::Tensor, std::allocator<tensorflow::Tensor> >*, tensorflow::CancellationManager*, absl::optional<tensorflow::EagerRemoteFunctionParams> const&) () from /home/jostheim/virtualenvs/data_science/lib/python3.7/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so
#6  0x00007fff77ab8ce9 in tensorflow::KernelAndDeviceFunc::Run(tensorflow::EagerKernelArgs const&, std::vector<tensorflow::Tensor, std::allocator<tensorflow::Tensor> >*, tensorflow::CancellationManager*, absl::optional<tensorflow::EagerRemoteFunctionParams> const&) () from /home/jostheim/virtualenvs/data_science/lib/python3.7/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so
#7  0x00007fff77a95b38 in tensorflow::EagerKernelExecute(tensorflow::EagerContext*, absl::InlinedVector<tensorflow::TensorHandle*, 4ul, std::allocator<tensorflow::TensorHandle*> > const&, absl::optional<tensorflow::EagerRemoteFunctionParams> const&, std::unique_ptr<tensorflow::KernelAndDevice, tensorflow::core::RefCountDeleter> const&, tensorflow::GraphCollector*, tensorflow::CancellationManager*, absl::Span<tensorflow::TensorHandle*>) () from /home/jostheim/virtualenvs/data_science/lib/python3.7/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so
#8  0x00007fff77a9612d in tensorflow::ExecuteNode::Run() () from /home/jostheim/virtualenvs/data_science/lib/python3.7/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so
#9  0x00007fff77ad6cf5 in tensorflow::EagerExecutor::RunItem(std::unique_ptr<tensorflow::EagerExecutor::NodeItem, tensorflow::core::RefCountDeleter>) ()
   from /home/jostheim/virtualenvs/data_science/lib/python3.7/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so
#10 0x00007fff77ad744b in tensorflow::EagerExecutor::AddOrExecute(std::unique_ptr<tensorflow::EagerNode, std::default_delete<tensorflow::EagerNode> >) ()
   from /home/jostheim/virtualenvs/data_science/lib/python3.7/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so
#11 0x00007fff77a9078e in tensorflow::(anonymous namespace)::EagerLocalExecute(tensorflow::EagerOperation*, tensorflow::TensorHandle**, int*) ()
   from /home/jostheim/virtualenvs/data_science/lib/python3.7/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so
#12 0x00007fff77a93d60 in tensorflow::EagerExecute(tensorflow::EagerOperation*, tensorflow::TensorHandle**, int*) ()
---Type <return> to continue, or q <return> to quit---
   from /home/jostheim/virtualenvs/data_science/lib/python3.7/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so
#13 0x00007fff7792219d in TFE_Execute () from /home/jostheim/virtualenvs/data_science/lib/python3.7/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so
#14 0x00007fff778a8844 in TFE_Py_ExecuteCancelable(TFE_Context*, char const*, char const*, absl::InlinedVector<TFE_TensorHandle*, 4ul, std::allocator<TFE_TensorHandle*> >*, _object*, TFE_CancellationManager*, absl::InlinedVector<TFE_TensorHandle*, 2ul, std::allocator<TFE_TensorHandle*> >*, TF_Status*) () from /home/jostheim/virtualenvs/data_science/lib/python3.7/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so
#15 0x00007fff778a8d81 in TFE_Py_Execute(TFE_Context*, char const*, char const*, absl::InlinedVector<TFE_TensorHandle*, 4ul, std::allocator<TFE_TensorHandle*> >*, _object*, absl::InlinedVector<TFE_TensorHandle*, 2ul, std::allocator<TFE_TensorHandle*> >*, TF_Status*) () from /home/jostheim/virtualenvs/data_science/lib/python3.7/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so
#16 0x00007fff76f1940a in _wrap_TFE_Py_Execute () from /home/jostheim/virtualenvs/data_science/lib/python3.7/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so
#17 0x0000555555684f77 in _PyMethodDef_RawFastCallKeywords ()
#18 0x0000555555684d80 in _PyCFunction_FastCallKeywords ()
#19 0x00005555556f7de5 in _PyEval_EvalFrameDefault ()
#20 0x00005555556f2715 in _PyEval_EvalCodeWithName ()
#21 0x000055555568671a in _PyFunction_FastCallKeywords ()
#22 0x00005555556f4406 in _PyEval_EvalFrameDefault ()
#23 0x00005555556f2715 in _PyEval_EvalCodeWithName ()
#24 0x000055555568671a in _PyFunction_FastCallKeywords ()
#25 0x00005555556f4406 in _PyEval_EvalFrameDefault ()
#26 0x00005555556f2715 in _PyEval_EvalCodeWithName ()
#27 0x000055555568671a in _PyFunction_FastCallKeywords ()
#28 0x00005555556f3840 in _PyEval_EvalFrameDefault ()
#29 0x000055555568663a in _PyFunction_FastCallKeywords ()
#30 0x00005555556f3840 in _PyEval_EvalFrameDefault ()
#31 0x00005555556f2715 in _PyEval_EvalCodeWithName ()
#32 0x0000555555686db1 in _PyObject_Call_Prepend ()
#33 0x00005555556c9319 in ?? ()
---Type <return> to continue, or q <return> to quit---
#34 0x00005555556871d1 in PyObject_Call ()
#35 0x00005555556f4d75 in _PyEval_EvalFrameDefault ()
#36 0x00005555556f2d15 in _PyEval_EvalCodeWithName ()
#37 0x0000555555686db1 in _PyObject_Call_Prepend ()
#38 0x00005555556871d1 in PyObject_Call ()
#39 0x00005555556f4d75 in _PyEval_EvalFrameDefault ()
#40 0x00005555556f2715 in _PyEval_EvalCodeWithName ()
#41 0x0000555555686db1 in _PyObject_Call_Prepend ()
#42 0x00005555556c9319 in ?? ()
#43 0x0000555555685792 in _PyObject_FastCallKeywords ()
#44 0x00005555556f790d in _PyEval_EvalFrameDefault ()
#45 0x00005555556f28ac in _PyEval_EvalCodeWithName ()
#46 0x000055555568671a in _PyFunction_FastCallKeywords ()
#47 0x00005555556f35e6 in _PyEval_EvalFrameDefault ()
#48 0x00005555556f2715 in _PyEval_EvalCodeWithName ()
#49 0x000055555568671a in _PyFunction_FastCallKeywords ()
#50 0x00005555556f4406 in _PyEval_EvalFrameDefault ()
#51 0x00005555556f2715 in _PyEval_EvalCodeWithName ()
#52 0x000055555568671a in _PyFunction_FastCallKeywords ()
#53 0x00005555556f4406 in _PyEval_EvalFrameDefault ()
#54 0x00005555556f2715 in _PyEval_EvalCodeWithName ()
#55 0x000055555568671a in _PyFunction_FastCallKeywords ()
#56 0x00005555556f4406 in _PyEval_EvalFrameDefault ()
#57 0x00005555556f2715 in _PyEval_EvalCodeWithName ()
---Type <return> to continue, or q <return> to quit---
#58 0x000055555568671a in _PyFunction_FastCallKeywords ()
#59 0x00005555556f4406 in _PyEval_EvalFrameDefault ()
#60 0x000055555568663a in _PyFunction_FastCallKeywords ()
#61 0x00005555556f35e6 in _PyEval_EvalFrameDefault ()
#62 0x00005555556f2715 in _PyEval_EvalCodeWithName ()
#63 0x00005555556f2413 in PyEval_EvalCode ()
#64 0x00005555557bc802 in ?? ()
#65 0x00005555557bcb7d in PyRun_FileExFlags ()
#66 0x00005555557bca26 in PyRun_SimpleFileExFlags ()
#67 0x0000555555794203 in ?? ()
#68 0x0000555555793eac in _Py_UnixMain ()
#69 0x00007ffff6bf2b97 in __libc_start_main (main=0x5555556818a0 <main>, argc=3, argv=0x7fffffffe058, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffe048)
    at ../csu/libc-start.c:310
#70 0x0000555555793d8a in _start ()```

**Comment by jostheim** [comment]
The XID error is:

```GPU 00000000:0B:00.0: Detected Critical Xid Error```

**Comment by ravikyram** [comment]
@jostheim 

Will it be possible to share colab link or simple standalone code with supporting files to reproduce the issue reported here. It helps us in localizing the issue faster. Thanks!

**Comment by jostheim** [comment]
It is pretty hard to do that, as it involves interleaved TFrecord files totaling around 400GB, I am not sure where I would put that much data (or even a subset), it would also be a significant amount of code to put somewhere, I could probably eventually get the code in a notebook with some significant effort.  Is there anything I can do to help debug on my end?

**Comment by jostheim** [comment]
BTW since the use of a Keras sequence runs fine, I can’t rule out some interplay between tf datasets and the issues I am seeing, so I can’t really simplify too much...

**Comment by rthadur** [comment]
@jostheim could you please verify this in latest versions ?
