### ISSUE TITLE
Tensorflow failed to load model

### ISSUE THREAD

**Issue by navalta3030** [tensorflow/tensorflow#38726]
The main model was trained on my local machine with a GTX 1050 Ti GPU.  The error below is from the docker container being deployed in a VM in the Digital Ocean, and I've also tried it again on my local machine and works perfectly. 

**Dockerfile config:**
```
FROM  tensorflow/tensorflow:latest-py3
RUN apt update

COPY requirements.txt /requirements.txt
RUN python3 -m pip install -r requirements.txt && mkdir /app

COPY . /app
WORKDIR /app

ENTRYPOINT ["python3", "app.py"]
```

Error within the VM, where CPU is already being forced to be used via "tf.config.set_visible_devices([], 'GPU')"
```
2020-04-20 23:02:03.505874: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory
2020-04-20 23:02:03.505973: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory
2020-04-20 23:02:03.505983: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2020-04-20 23:02:04.285763: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2020-04-20 23:02:04.285824: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: UNKNOWN ERROR (303)
2020-04-20 23:02:04.285854: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (sanic-server-5f779b76c9-xth26): /proc/driver/nvidia/version does not exist
2020-04-20 23:02:04.920805: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2020-04-20 23:02:04.928642: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2294605000 Hz
2020-04-20 23:02:04.929167: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x41ce6a0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-04-20 23:02:04.929206: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/py_checkpoint_reader.py", line 70, in get_tensor
    self, compat.as_bytes(tensor_str))
RuntimeError: The length checksum does not match: expected 1137107832 but actual is 432382948

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app.py", line 17, in <module>
    TF = TensorflowImg()
  File "/app/ml_modules/tensorflow_img.py", line 28, in __init__
    self.model = self.__load_model()
  File "/app/ml_modules/tensorflow_img.py", line 48, in __load_model
    "KerasLayer": hub.KerasLayer})
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/saving/save.py", line 150, in load_model
    return saved_model_load.load(filepath, compile)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/saving/saved_model/load.py", line 89, in load
    model = tf_load.load_internal(path, loader_cls=KerasObjectLoader)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/saved_model/load.py", line 552, in load_internal
    export_dir)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/saving/saved_model/load.py", line 118, in __init__
    super(KerasObjectLoader, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/saved_model/load.py", line 128, in __init__
    self._restore_checkpoint()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/saved_model/load.py", line 280, in _restore_checkpoint
    load_status = saver.restore(variables_path)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/tracking/util.py", line 1248, in restore
    object_graph_string = reader.get_tensor(base.OBJECT_GRAPH_PROTO_KEY)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/py_checkpoint_reader.py", line 74, in get_tensor
    error_translator(e)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/py_checkpoint_reader.py", line 48, in error_translator
    raise errors_impl.OpError(None, None, error_message, errors_impl.UNKNOWN)
tensorflow.python.framework.errors_impl.OpError: The length checksum does not match: expected 1137107832 but actual is 432382948
```

Here a successful one from my local-machine
```
2020-04-21 01:55:36.154300: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory
2020-04-21 01:55:36.156770: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory  
2020-04-21 01:55:36.157413: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2020-04-21 01:55:37.103847: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2020-04-21 01:55:37.105032: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: UNKNOWN ERROR (303)
2020-04-21 01:55:37.105865: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (332fc060f5f6): /proc/driver/nvidia/version does not exist
2020-04-21 01:55:37.703255: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-04-21 01:55:37.722212: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2495995000 Hz
2020-04-21 01:55:37.724314: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x4d226c0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-04-21 01:55:37.724943: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
[2020-04-21 01:55:41 +0000] [1] [INFO] Starting localhost development
[2020-04-21 01:55:41 +0000] [1] [DEBUG]

                 Sanic
         Build Fast. Run Fast.


[2020-04-21 01:55:41 +0000] [1] [INFO] Goin' Fast @ http://0.0.0.0:8000
2020-04-21 01:55:42.388099: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory
2020-04-21 01:55:42.389311: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory  
2020-04-21 01:55:42.390228: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2020-04-21 01:55:43.083080: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2020-04-21 01:55:43.083171: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: UNKNOWN ERROR (303)
2020-04-21 01:55:43.083197: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (332fc060f5f6): /proc/driver/nvidia/version does not exist
2020-04-21 01:55:43.682208: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-04-21 01:55:43.690862: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2495995000 Hz
2020-04-21 01:55:43.692032: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x3a17d60 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-04-21 01:55:43.692692: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
[2020-04-21 01:55:47 +0000] [964] [INFO] Starting localhost development
[2020-04-21 01:55:47 +0000] [964] [INFO] Starting worker [964]
^CProcess Process-1:
[2020-04-21 01:56:43 +0000] [964] [INFO] Stopping worker [964]
[2020-04-21 01:56:43 +0000] [964] [INFO] Server Stopped
```

**Comment by ravikyram** [comment]
@navalta3030 

Please, let us know which TensorFlow version you are using? Request you to provide colab link or simple standalone code to reproduce the issue in our environment. then it is easy for localizing the issue faster. Thanks !

**Comment by navalta3030** [comment]
@ravikyram Hi, 

- Tensorflow version = 2.1.0

# Steps to reproduce
- git clone https://github.com/navalta3030/sanic_server.git
- git checkout --track origin/no_issue
- python3 -m venv .env
- source .env/Scripts/activate
- pip install -r requirements.txt
- python app.py

The part where it fails is [Here](https://github.com/navalta3030/sanic_server/blob/no_issue/ml_modules/tensorflow_img.py#L34)

The saved model is located [Here](https://github.com/navalta3030/sanic_server/tree/no_issue/ml_modules/models/effusion.tf)

**Comment by navalta3030** [comment]
Closing this one. 

The issue was on github action, the compilation was done over there and there is a bit of disallignment on their build-machine.
