### ISSUE TITLE
TensorRT Converter could not work well with Bert model

### ISSUE THREAD

**Issue by feihugis** [tensorflow/tensorflow#38722]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Centos 7
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): tf-nightly(2.2.0-dev20200420)
- Python version: 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.1
- GPU model and memory: P100

**Describe the current behavior**

I tried to run the Bert-NER inference using TensorRT. I converted the model using the below code:
```python
def convert(input_saved_model_dir, output_saved_model_dir):
    params = DEFAULT_TRT_CONVERSION_PARAMS._replace(
        max_batch_size=512,
        maximum_cached_engines=16)
    converter = tf.experimental.tensorrt.Converter(
        input_saved_model_dir=input_saved_model_dir, conversion_params=params)
    converter.convert()

    def input_fn():
        for _ in range(100):
            yield np.ones(shape=[32, 128], dtype=np.int32), \
                  np.ones(shape=[32, 128], dtype=np.int32), \
                  np.ones(shape=[32, 128], dtype=np.int32)
    converter.build(input_fn=input_fn)
    converter.save(output_saved_model_dir)
```
However, I met a few issues:
1. The shape for the batch dimension is not correct in the converted model; The original model could work with the same input data; The error log is in below:
```
2020-04-20 15:18:03.775850: W tensorflow/core/framework/op_kernel.cc:1751] OP_REQUIRES failed at trt_engine_op.cc:572 : Invalid argument: Input shapes are inconsistent on the batch dimension, for StatefulPartitionedCall/model_1/bert_model/embedding_postprocessor/TRTEngineOp_0_0: [[32,128,768], [32,128,768], [1,128,768]]
Traceback (most recent call last):
  File "/home/feihu/miniconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/feihu/miniconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/feihu/.vscode-server/extensions/ms-python.python-2020.3.71659/pythonFiles/lib/python/debugpy/no_wheels/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/home/feihu/.vscode-server/extensions/ms-python.python-2020.3.71659/pythonFiles/lib/python/debugpy/no_wheels/debugpy/../debugpy/server/cli.py", line 429, in main
    run()
  File "/home/feihu/.vscode-server/extensions/ms-python.python-2020.3.71659/pythonFiles/lib/python/debugpy/no_wheels/debugpy/../debugpy/server/cli.py", line 266, in run_file
    runpy.run_path(options.target, run_name=compat.force_str("__main__"))
  File "/home/feihu/miniconda3/lib/python3.6/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/home/feihu/miniconda3/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/home/feihu/miniconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/feihu/github_projects/Named-Entity-Recognition/src/trt/trt_savedmodel_convert.py", line 28, in <module>
    convert(input_saved_model_dir, output_saved_model_dir)
  File "/home/feihu/github_projects/Named-Entity-Recognition/src/trt/trt_savedmodel_convert.py", line 21, in convert
    converter.build(input_fn=input_fn)
  File "/home/feihu/py-virtualenv/bert-compression-ner/lib/python3.6/site-packages/tensorflow/python/compiler/tensorrt/trt_convert.py", line 1174, in build
    func(*map(ops.convert_to_tensor, inp))
  File "/home/feihu/py-virtualenv/bert-compression-ner/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 1612, in __call__
    return self._call_impl(args, kwargs)
  File "/home/feihu/py-virtualenv/bert-compression-ner/lib/python3.6/site-packages/tensorflow/python/eager/wrap_function.py", line 247, in _call_impl
    args, kwargs, cancellation_manager)
  File "/home/feihu/py-virtualenv/bert-compression-ner/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 1649, in _call_impl
    return self._call_flat(args, self.captured_inputs, cancellation_manager)
  File "/home/feihu/py-virtualenv/bert-compression-ner/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 1746, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/home/feihu/py-virtualenv/bert-compression-ner/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 609, in call
    ctx=ctx)
  File "/home/feihu/py-virtualenv/bert-compression-ner/lib/python3.6/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InvalidArgumentError:  Input shapes are inconsistent on the batch dimension, for StatefulPartitionedCall/model_1/bert_model/embedding_postprocessor/TRTEngineOp_0_0: [[32,128,768], [32,128,768], [1,128,768]]
         [[node StatefulPartitionedCall/model_1/bert_model/embedding_postprocessor/TRTEngineOp_0_0 (defined at /github_projects/Named-Entity-Recognition/src/trt/trt_savedmodel_convert.py:14) ]] [Op:__inference_pruned_26783]
```
2. The saved model could not be larger than 2GB; Otherwise, there will be an error from protobuf about `GraphDef object could not exceed the size of 2GB`; 

3. The converted model could not work under the distributed strategy.

**Comment by ravikyram** [comment]
@feihugis 

Request you to share colab link or simple standalone code with supporting files to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by Pekary** [comment]
hi, @feihugis , my bert model has the same problem, did you solve it?

**Comment by feihugis** [comment]
@Pekary  No, I did not at that time. Maybe you can try to convert the model to ONNX format and use ONNXRuntime with TensorRT ExecutionProvider.
