### ISSUE TITLE
ModuleNotFoundError : from tensorflow.compat.v1 import *

### ISSUE THREAD

**Issue by ajay-sreeram** [tensorflow/tensorflow#38800]
ModuleNotFoundError: No module named `tensorflow.compat.v1` in **tensorflow==2.2.0-rc3**

**python == 3.6.8** in MacBook Pro

**Comment by oke-aditya** [comment]
- Can you please share more details. I am able to run [this](https://colab.research.google.com/gist/oke-aditya/33f2a02b7d1ffae5f3b60127d4421cdb/test.ipynb)

**Comment by ajay-sreeram** [comment]
Hi Aditya,

Thanks for the response, yes I am also able to run it in colab but not in mac book. 

In colab it is using python 3.6.9.

but in python website, python 3.6.9 build is not there for mac so i am using python 3.6.8 and tensorflow==2.2.0-rc3 as it is the same tensorflow version in colab. 

Now I am facing ModuleNotFoundError in macbook but not in colab.

**Comment by oke-aditya** [comment]
@ajay-sreeram are other functionalities of TensorFlow working fine? like are you able to
```
import tensorflow as tf
print(tf.__version__)
```
- Is the issue only with `tensorflow.compat.v1 import *` or with other stuff in the package as well?

**Comment by ajay-sreeram** [comment]
Yes I am able to import tensorflow and all the other functionalities are working fine and I see only .compat.v1 issue for now.

**Comment by oke-aditya** [comment]
If the issue is Mac specific. I am unsure of Mac Platform as I haven't used it. Hope someone helps here @ravikyram

**Comment by ravikyram** [comment]
I am seeing no issues with linux platform and colab.
@ymodak can you please look into this issue.Thanks!

**Comment by oke-aditya** [comment]
I am seeing no issues with Windows 7 as well. 
![image](https://user-images.githubusercontent.com/47158509/80073358-4ab83a00-8565-11ea-91a8-ce8bbf21400d.png)

**Comment by ymodak** [comment]
I could successfully import the compat.v1 module in macOS with Python 3.7 and TF 2.2.0-rc3.
Also I found the [python 3.6.9 version](https://www.python.org/downloads/mac-osx/) you were looking for.
However  I doubt that is a reason for failure. May be you can try setting virtual env before importing the modules or use an IDE.
Thanks!

**Comment by ajay-sreeram** [comment]
> I could successfully import the compat.v1 module in macOS with Python 3.7 and TF 2.2.0-rc3.
> Also I found the [python 3.6.9 version](https://www.python.org/downloads/mac-osx/) you were looking for.
> However  I doubt that is a reason for failure. May be you can try setting virtual env before importing the modules or use an IDE.
> Thanks!

Thankyou Yasir, I will try with python 3.7 then.

**Comment by ajay-sreeram** [comment]
closing the issue as it worked with python 3.6.9 version

**Comment by satish1901** [comment]
Hi
I am using python 3.6
cuda : 10.1
tensorflow-gpu==2.2.0

i am getting this error : 
>>> import tensorflow.compat.v1 as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'tensorflow.compat.v1'
>>> 

Can anyone please suggest some work around or solution?

**Comment by ajay-sreeram** [comment]
> Hi
> I am using python 3.6
> cuda : 10.1
> tensorflow-gpu==2.2.0
> Ubuntu = 18.04
> 
> i am getting this error : 
> >>> import tensorflow.compat.v1 as tf
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> ModuleNotFoundError: No module named 'tensorflow.compat.v1'
> >>> 
> 
> Can anyone please suggest some work around or solution?

Try with python 3.7 Satish, it might work.

**Comment by kevencarneiro** [comment]
> Hi
> I am using python 3.6
> cuda : 10.1
> tensorflow-gpu==2.2.0
> Ubuntu = 18.04
> 
> i am getting this error :
> 
> > > > import tensorflow.compat.v1 as tf
> > > > Traceback (most recent call last):
> > > > File "", line 1, in 
> > > > ModuleNotFoundError: No module named 'tensorflow.compat.v1'
> 
> Can anyone please suggest some work around or solution?

If you are running Tensorflow v2.2 and Python 3.6, you can try this workaround:
```python
import tensorflow._api.v2.compat.v1 as tf
```

**Comment by danielivan09** [comment]
Traceback (most recent call last):
  File "generate_tfrecord.py", line 108, in <module>
    tf.compat.v1.app.run()
  File "C:\Users\ivand\anaconda3\envs\tensorflow2\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Users\ivand\anaconda3\envs\tensorflow2\lib\site-packages\absl\app.py", line 303, in run
    _run_main(main, args)
  File "C:\Users\ivand\anaconda3\envs\tensorflow2\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "generate_tfrecord.py", line 94, in main
    writer = tf.io.TFRecordWriter(FLAGS.output_path)
  File "C:\Users\ivand\anaconda3\envs\tensorflow2\lib\site-packages\tensorflow\python\lib\io\tf_record.py", line 218, in __init__
    compat.as_bytes(path), options._as_record_writer_options(), status)
  File "C:\Users\ivand\anaconda3\envs\tensorflow2\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 548, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: Failed to create a NewWriteableFile:  : The system cannot find the path specified.
; No such process



i have an error like this, please help me sir

**Comment by sahasraa** [comment]
i am having this issue please help
Traceback (most recent call last):
  File "/home/sahasra/jukshio/object_det_rec/TensorFlow/models/research/seq_flow_lite/export_to_tflite.py", line 24, in <module>
    import tensorflow.compat.v2 as tf
ModuleNotFoundError: No module named 'tensorflow.compat'

im using tensorflow : 2.5.0
                  python : 3.9.6

**Comment by aziyatali** [comment]
I think problem is the version specific.

**Comment by saddamsaed** [comment]
Hi
I am using:
 python 3.6
tensorflow==1.5
i am getting this error :
  File "C:\Users\User\miniconda3\envs\bot\lib\site-packages\tflearn\__init__.py", line 4, in <module>
    import tensorflow.compat.v1 as tf
ModuleNotFoundError: No module named 'tensorflow.compat

**Comment by xuyao91** [comment]
Hi
same issue
python 3.10.7
tensorflow 2.9.2
Mac pro 11.6
error:
`Traceback (most recent call last):
  File "/Users/xuyao/Workspaces/ai/tensorflow/models/research/object_detection/builders/model_builder_tf2_test.py", line 21, in <module>
    import tensorflow.compat.v1 as tf
ModuleNotFoundError: No module named 'tensorflow.compat'
`

**Comment by opticSquid** [comment]
Hi same issue,
OS: Ubuntu 22.04
Python version: 3.10.6
Tensorflow version: 2.11
```sh
lTraceback (most recent call last):
  File "[/pythonAI/Tensorflow/models/research/object_detection/builders/model_builder_tf2_test.py](https://file+.vscode-resource.vscode-cdn.net/Storage/pythonAI/Tensorflow/models/research/object_detection/builders/model_builder_tf2_test.py)", line 21, in <module>
    import tensorflow._api.v2.compat.v1 as tf
  File "[/anprsys/lib/python3.10/site-packages/tensorflow/__init__.py](https://file+.vscode-resource.vscode-cdn.net/anprsys/lib/python3.10/site-packages/tensorflow/__init__.py)", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "[/anprsys/lib/python3.10/site-packages/tensorflow/python/__init__.py](https://file+.vscode-resource.vscode-cdn.net/media/soumalya/Storage/pythonAI/anprsys/lib/python3.10/site-packages/tensorflow/python/__init__.py)", line 36, in <module>
    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow
  File "[/anprsys/lib/python3.10/site-packages/tensorflow/python/pywrap_tensorflow.py](https://file+.vscode-resource.vscode-cdn.net/media/soumalya/Storage/pythonAI/anprsys/lib/python3.10/site-packages/tensorflow/python/pywrap_tensorflow.py)", line 26, in <module>
    self_check.preload_check()
  File "[/anprsys/lib/python3.10/site-packages/tensorflow/python/platform/self_check.py](https://file+.vscode-resource.vscode-cdn.net/anprsys/lib/python3.10/site-packages/tensorflow/python/platform/self_check.py)", line 63, in preload_check
    from tensorflow.python.platform import _pywrap_cpu_feature_guard
ImportError: libhsa-runtime64.so.1: cannot open shared object file: No such file or directory
```
Please reopen this issue

**Comment by Japheth001** [comment]
Hi Same Isse
"    import tensorflow.compat.v1 as tf
ModuleNotFoundError: No module named 'tensorflow.compat'"
Python 3.7.16
Tensorflow 2.2.0
