### ISSUE TITLE
EagerTensor - Tensorboard & Projector.

### ISSUE THREAD

**Issue by d3pr3553d** [tensorflow/tensorflow#38814]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- I have used a combination of some custom code with tensorflow provided scripts. 
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): OSX 10.15.4
- TensorFlow installed from (source or binary): pip 
- TensorFlow version (use command below): >>> '2.1.0'
- Python version: 3.7.7
- GPU model and memory: Radeon Pro 560X 4GB

**Describe the current behavior**
I recieve an error of trying to capture EagerTensor.

:168] XLA service 0x7fd4c0649fd0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-04-22 13:05:21.461935: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Traceback (most recent call last):
  File "unstructuredData.py", line 32, in <module>
    saver = tf.compat.v1.train.Saver([tf_data])
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 828, in __init__
    self.build()
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 840, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 878, in _build
    build_restore=build_restore)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 505, in _build_internal
    save_tensor = self._AddSaveOps(filename_tensor, saveables)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 206, in _AddSaveOps
    save = self.save_op(filename_tensor, saveables)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 110, in save_op
    tensors.append(spec.tensor)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/training/saving/saveable_object.py", line 52, in tensor
    return self._tensor() if callable(self._tensor) else self._tensor
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/training/saving/saveable_object_util.py", line 91, in f
    x = v.read_value()
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/ops/resource_variable_ops.py", line 635, in read_value
    value = self._read_variable_op()
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/ops/resource_variable_ops.py", line 613, in _read_variable_op
    self._dtype)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_resource_variable_ops.py", line 483, in read_variable_op
    "ReadVariableOp", resource=resource, dtype=dtype, name=name)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/framework/op_def_library.py", line 468, in _apply_op_helper
    preferred_dtype=default_dtype)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 1280, in convert_to_tensor
    raise RuntimeError("Attempting to capture an EagerTensor without "
RuntimeError: Attempting to capture an EagerTensor without building a function.

**Describe the expected behavior**
Tensorflow runs and saves the logs so tensorboard may render the results.

 
**Standalone code to reproduce the issue**
```
import os
import tensorflow as tf
import numpy as np 
import pandas as pd 
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA


##Global Varables 
PATH = os.getcwd()

##Log path for embedding
LOG_DIR = PATH + '/project-tensorboard/log-1/'

##load Data
df = pd.read_csv("us.csv", index_col=0)

#Load the metadata
metadata = os.path.join(LOG_DIR, 'df_labels.tsv')

#Generating PCA
pca = PCA(n_components=2, random_state=123, svd_solver='auto')

df_pca = pd.DataFrame(pca.fit_transform(df))
df_pca = df_pca.values

#Tensorflow from data
tf_data = tf.Variable(df_pca)

with  tf.compat.v1.Session() as sess:
    tf.executing_eagerly()
    saver = tf.compat.v1.train.Saver([tf_data])
    sess.run(tf_data.initializer)
    saver.save(sess, os.path.join(LOG_DIR, 'tf_data.ckpt'))
    config = projector.ProjectorConfig()

    embedding = config.embeddings.add()
    embedding.tensor_name = tf_data.tensor_name

    embedding.metadata_path = metadata

    projector.visualize_embeddings(tf.summary.FileWriter(LOG_DIR), config)
```

Provide a reproducible test case that is the bare minimum necessary to generate the problem.

Grab any COVID-19 data in a CSV format. Store it in the root directory. Run tensorboard. Run script. View EagerTensor error.

**Other info / logs** 
I have tried v1 imports. I have tried Tensorflow GPU. I have removed and added the tf.executing_eagerly(). I am trying to build the embedding projector locally however, the EagerTensor error has no solution.

**Comment by amahendrakar** [comment]
@d3pr3553d,
In order to expedite the trouble-shooting process, could you please share all the files you are using in your code.

Also, please add ``` (i.e. three back ticks) before and after your code to preserve the indentation and formatting. Thanks!

**Comment by amahendrakar** [comment]
> In order to expedite the trouble-shooting process, could you please share all the files you are using in your code.
> 
> Also, please add ``` (i.e. three back ticks) before and after your code to preserve the indentation and formatting. Thanks!

@d3pr3553d 
Any updates regarding this issue? Thanks!

**Comment by d3pr3553d** [comment]
The data came from this repository. You can clone it and use it freely.
https://github.com/nytimes/covid-19-data

**Comment by amahendrakar** [comment]
@d3pr3553d,
As per [this comment](https://github.com/tensorflow/tensorflow/issues/35785#issuecomment-573547196) from a similar issue, adding the line `tf.compat.v1.disable_eager_execution()` did resolve the error.

Now, I am facing a different error stating `AttributeError: 'ResourceVariable' object has no attribute 'tensor_name'`. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/50786f8c93e007888c2cc9d4bed75177/38814.ipynb#scrollTo=wDD4uCwDnXtc). Thanks!
