### ISSUE TITLE
Could not import Tensorflow?

### ISSUE THREAD

**Issue by ibrahimLearning** [tensorflow/tensorflow#38823]
In my machine Tensorflow 2.1.0 is OK. The tensorflow 2.1.0 was installed using pip.
But Tensorflow 1.3.0 is not working after installing using pip in different environment.
It gives the following error: 
```
Traceback (most recent call last):
  File "C:\Users\Ibrahim Khalilullah\.conda\envs\MaskrcnnTF1point3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Users\Ibrahim Khalilullah\.conda\envs\MaskrcnnTF1point3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Ibrahim Khalilullah\.conda\envs\MaskrcnnTF1point3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Ibrahim Khalilullah\.conda\envs\MaskrcnnTF1point3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 21, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Ibrahim Khalilullah\.conda\envs\MaskrcnnTF1point3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 20, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow_internal')
  File "C:\Users\Ibrahim Khalilullah\.conda\envs\MaskrcnnTF1point3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Ibrahim Khalilullah\.conda\envs\MaskrcnnTF1point3\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "C:\Users\Ibrahim Khalilullah\.conda\envs\MaskrcnnTF1point3\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Ibrahim Khalilullah\.conda\envs\MaskrcnnTF1point3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 52, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Ibrahim Khalilullah\.conda\envs\MaskrcnnTF1point3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Users\Ibrahim Khalilullah\.conda\envs\MaskrcnnTF1point3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Ibrahim Khalilullah\.conda\envs\MaskrcnnTF1point3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Ibrahim Khalilullah\.conda\envs\MaskrcnnTF1point3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 21, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Ibrahim Khalilullah\.conda\envs\MaskrcnnTF1point3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 20, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow_internal')
  File "C:\Users\Ibrahim Khalilullah\.conda\envs\MaskrcnnTF1point3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
>>>

```
Previously I can run both of them (Tensorflow 2.1.0 and Tensorflow 1.3.0). However, I changed some software (reinstalling anaconda and some packages with different environments).
I want to use both of them (Tensorflow 2.1.0 and Tensorflow 1.3.0).
Is there any solution please?

My working platform:
Windows 10
Anaconda 3
python 3.6
Microsoft Visual C++ Redistributable for Visual Studio 2015-2019

**Comment by ravikyram** [comment]
@ibrahimLearning 

Starting with TensorFlow 1.6, binaries use AVX instructions which may not run on older CPUs.
I suspect your cpu model does not support AVX instructions sets.See [hardware requirements](https://www.tensorflow.org/install/pip?lang=python3#hardware-requirements)

please refer to these existing issues on the same error faced

#36167 (comment)

#36167 #36151 #36138 #36054 #36045 #36020 #36003 #35988 #35903 #35880 #35865 #35805 #35789 #35773 #35772 #35767 #35766 #35749 #35721 #35618 #35204.

Thanks!

**Comment by mihaimaruseac** [comment]
TensorFlow 1.3? That is very old and not supported.

I see you were able to install 2.1

**Comment by ibrahimLearning** [comment]
@ravikyram 
But I used Tensorflow 1.3 on this machine before!!!

**Comment by ibrahimLearning** [comment]
> 
> 
> TensorFlow 1.3? That is very old and not supported.
> 
> I see you were able to install 2.1

Thanks for your comment. I developed several projects on Tensorflow 1.3. What Will I do now?

**Comment by mihaimaruseac** [comment]
You should be able to update. There is a script that helps in upgrading to TF2.0 APIs too.https://www.tensorflow.org/guide/migrate

**Comment by wookayin** [comment]
@ibrahimLearning Clean up (`.conda\envs\MaskrcnnTF1point3\lib\site-packages\tensorflow`) and force-reinstall it: e.g. `pip install -I tensorflow-gpu==1.3`. If you want to use different versions, you should use different anaconda environments.

**Comment by ravikyram** [comment]
@ibrahimLearning 

Is this still an issue? Was this resolved by following @wookayin  suggestion? Please close the issue if it was resolved already. Thanks!

**Comment by ibrahimLearning** [comment]
> @ibrahimLearning
> 
> Is this still an issue? Was this resolved by following @wookayin suggestion? Please close the issue if it was resolved already. Thanks!

Not yet resolved after following @wookayin  suggestion. However I will try later by following @mihaimaruseac suggestion.

**Comment by ibrahimLearning** [comment]
> Are you satisfied with the resolution of your issue?
> [Yes](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=Yes&entry.2137816233=https://github.com/tensorflow/tensorflow/issues/38823)
> [No](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=No&entry.2137816233=https://github.com/tensorflow/tensorflow/issues/38823)

It will be helpful if I can run Tensorflow 1.3 on my machine in different anaconda environment.
