### ISSUE TITLE
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: The specified module could not be found.

### ISSUE THREAD

**Issue by dhruv-colosus** [tensorflow/tensorflow#38856]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):-Windows 10
- TensorFlow installed from (source or binary): Pip Install Tensorflow
- TensorFlow version:2.2.0
- Python version:3.8.2 64 bit
- Installed using virtualenv? pip? conda?: PIP
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: i=I don't have Nvidia Graphic Card
- GPU model and memory: Intel R HD family (2160 MB)
-Laptop- Hp EliteBook 8 GB ram ; core i5

**Describe the problem**
I am having a problem as Import error. Here is the stack code.

Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\HP\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\HP\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python38\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python38\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "f:/MACHINE LEARNING/chatbot/main.py", line 9, in <module>
    import tensorflow
  File "C:\Users\HP\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\HP\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\__init__.py", line 50, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\HP\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 69, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\HP\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\HP\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python38\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python38\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: The specified module could not be found.

It happened only after I just imported TensorFlow. Is it because I don't have a graphic card?

Please Help.

**Comment by amahendrakar** [comment]
@dhruv-colosus,
Could you please check [this comment](https://github.com/tensorflow/tensorflow/issues/36167#issuecomment-577886156) on a similar issue and let us know if it helps. Thanks!

**Comment by dhruv-colosus** [comment]
> @dhruv-colosus,
> Could you please check [this comment](https://github.com/tensorflow/tensorflow/issues/36167#issuecomment-577886156) on a similar issue and let us know if it helps. Thanks!

Ok, I have avx2 SUPPORT. I already have MSVC 2017 installed. Python is 64 BIT. ALL libraries are on the same location. I think the problem is with the 2017 version instead of 2019.

**Comment by dhruv-colosus** [comment]
I solved my issue by upgrading it to 2019. Thank You.Closing The Issue
