### ISSUE TITLE
ImportError: DLL load failed: The specified procedure could not be found.

### ISSUE THREAD

**Issue by priyankkumar218** [tensorflow/tensorflow#38886]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 Home Single Language
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): 
- TensorFlow version: 2.0
- Python version: 3.6
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: None

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**
I am trying to build an application and this error seems to stay even after I downgraded my tensor flow version from 2.1 to 2.0.

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

C:\Users\Dell\AppData\Local\Programs\Python\Python36\python.exe C:/Users/Dell/PycharmProjects/MajorProject017/ChatBot.py
Traceback (most recent call last):
  File "C:/Users/Dell/PycharmProjects/MajorProject017/ChatBot.py", line 2, in <module>
    import tensorflow
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\__init__.py", line 98, in <module>
    from tensorflow_core import *
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_core\__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_core\python\__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_core\core\framework\graph_pb2.py", line 7, in <module>
    from google.protobuf import descriptor as _descriptor
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python36\lib\site-packages\google\protobuf\descriptor.py", line 47, in <module>
    from google.protobuf.pyext import _message
ImportError: DLL load failed: The specified procedure could not be found.

Process finished with exit code 1

**Comment by amahendrakar** [comment]
@priyankkumar218,
Could you please check [this comment](https://github.com/tensorflow/tensorflow/issues/36167#issuecomment-577886156) on a similar issue and let us know if it helps. Thanks!

**Comment by amahendrakar** [comment]
> Could you please check [this comment](https://github.com/tensorflow/tensorflow/issues/36167#issuecomment-577886156) on a similar issue and let us know if it helps. Thanks!

Any updates regarding this issue? Thanks!

**Comment by mihaimaruseac** [comment]
If you donwgraded, you probably also need to downgrade the MSVC redistributable

**Comment by priyankkumar218** [comment]
> @priyankkumar218,
> Could you please check [this comment](https://github.com/tensorflow/tensorflow/issues/36167#issuecomment-577886156) on a similar issue and let us know if it helps. Thanks!

This didn't help either.

**Comment by amahendrakar** [comment]
@priyankkumar218,
Could you please share the make and model of your CPU and also check if you are using 64-bit Python. Thanks!
