### ISSUE TITLE
Internal tensorflow-keras error loading hd5 model

### ISSUE THREAD

**Issue by elvis1020** [tensorflow/tensorflow#38892]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
pip
- TensorFlow version (use command below):
2.0.0b1
- Python version:
3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
not using cuda
- GPU model and memory:
N/A

I'm trying to load a trained model in an aws EC2 machine and I get the following:

```
Traceback (most recent call last):
  File "/home/ubuntu/kraken/krk_modeling/src/services/logger.py", line 51, in wrapper
    return function(*args, **kwargs)
  File "src/wrapper.py", line 81, in execute_pipeline
    conv.build(wkobflow, wkobwthr, wkfcwthr, LOG)
  File "/home/ubuntu/kraken/krk_modeling/src/models/neuralnet.py", line 41, in build
    self.models[s] = load_model(self.PATH + self.FORMAT(s))
  File "/home/ubuntu/kraken/venv/lib/python3.7/site-packages/tensorflow/python/keras/saving/save.py", line 137, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
  File "/home/ubuntu/kraken/venv/lib/python3.7/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 162, in load_model_from_hdf5
    custom_objects=custom_objects)
  File "/home/ubuntu/kraken/venv/lib/python3.7/site-packages/tensorflow/python/keras/saving/model_config.py", line 55, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/home/ubuntu/kraken/venv/lib/python3.7/site-packages/tensorflow/python/keras/layers/serialization.py", line 90, in deserialize
    printable_module_name='layer')
  File "/home/ubuntu/kraken/venv/lib/python3.7/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 192, in deserialize_keras_object
    list(custom_objects.items())))
  File "/home/ubuntu/kraken/venv/lib/python3.7/site-packages/tensorflow/python/keras/engine/network.py", line 1123, in from_config
    process_layer(layer_data)
  File "/home/ubuntu/kraken/venv/lib/python3.7/site-packages/tensorflow/python/keras/engine/network.py", line 1107, in process_layer
    layer = deserialize_layer(layer_data, custom_objects=custom_objects)
  File "/home/ubuntu/kraken/venv/lib/python3.7/site-packages/tensorflow/python/keras/layers/serialization.py", line 90, in deserialize
    printable_module_name='layer')
  File "/home/ubuntu/kraken/venv/lib/python3.7/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 194, in deserialize_keras_object
    return cls.from_config(cls_config)
  File "/home/ubuntu/kraken/venv/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 451, in from_config
    return cls(**config)
  File "/home/ubuntu/kraken/venv/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 2417, in __init__
    self.node_def = node_def_pb2.NodeDef.FromString(node_def)
TypeError: a bytes-like object is required, not 'dict'
```

I am running the same code in my machine normally, the models load and run. on EC2 I'm using tensorflow 2.0.0b1, same version used in training. Also, the model is in production in another machine and loading normally too. I tried to re-install hdf5 and re-install tensorflow after that, and still getting the error. Please help =]

the problem is generated only by loading the model. no code is required, since the problem is originated from tensorflow.keras.models.load_model.

**Comment by Saduf2019** [comment]
@elvis1020 
please share simple stand alone code for us to replicate the issue faced.

**Comment by elvis1020** [comment]
`from tensorflow.keras.models import load_model
model = load_model('<file_path>')`

**Comment by elvis1020** [comment]
I've uploaded one of the models. maybe it would be easier.
But it must be loaded on an aws EC2 instance, because that's the issue. On my computer, the models load normally, and the tensorflow version is the same.
https://drive.google.com/open?id=1kzyzAuNHTlCHc4Nx-JUhczCB7aTDMxp6

**Comment by gowthamkpr** [comment]
@elvis1020 Yes I was able to reproduce the bug in tensorflow 2.0.0b1. Please try using tensorflow 2.0 or 2.1 or 2.2 versions as this bug has been fixed. Thanks!

**Comment by gowthamkpr** [comment]
Closing this issue as it has been inactive for more than 3 weeks. Please add additional comments for us to open this issue again. Thanks!
