### ISSUE TITLE
[RNN] Bidirectional LSTM conversion fail

### ISSUE THREAD

**Issue by limjq45** [tensorflow/tensorflow#38935]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 64-bit
- TensorFlow installed from (source or binary): 
- TensorFlow version (or github SHA if from source): 2.2.0-dev20200422

**Command used to run the converter or code if you’re using the Python API**
If possible, please share a link to Colab/Jupyter/any notebook.

```
converter = tf.lite.TFLiteConverter.from_keras_model_file(
    'model.h5',
    input_shapes={'embedding_input': (128,1900)}
)

# converter = tf.lite.TFLiteConverter.from_keras_model(loaded_model) 
converter.experimental_new_converter = True
# # converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,
# #                                        tf.lite.OpsSet.SELECT_TF_OPS]
tfmodel = converter.convert() 
open ('model.tflite' , "wb") .write(tfmodel)
```

**The output from the converter invocation**

```
Traceback (most recent call last):
  File "convert.py", line 25, in <module>
    tfmodel = converter.convert()
  File "C:\Users\jing_\anaconda3\envs\tf2-gpu\lib\site-packages\tensorflow\lite\python\lite.py", line 1326, in convert
    **converter_kwargs)
  File "C:\Users\jing_\anaconda3\envs\tf2-gpu\lib\site-packages\tensorflow\lite\python\convert.py", line 536, in toco_convert_impl
    enable_mlir_converter=enable_mlir_converter)
  File "C:\Users\jing_\anaconda3\envs\tf2-gpu\lib\site-packages\tensorflow\lite\python\convert.py", line 241, in toco_convert_protos
    raise ConverterError("See console for info.\n%s\n%s\n" % (stdout, stderr))
tensorflow.lite.python.convert.ConverterError: See console for info.
2020-04-27 15:43:22.425922: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:307] Ignored output_format.
2020-04-27 15:43:22.426100: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:310] Ignored drop_control_dependency.
2020-04-27 15:43:22.443931: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with Intel(R) MKL-DNN to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-04-27 15:43:22.449382: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x27c7543e550 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-04-27 15:43:22.449555: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
loc(callsite("sequential/bidirectional/backward_lstm/PartitionedCall/while"("C:\Users\jing_\anaconda3\envs\tf2-gpu\lib\site-packages\tensorflow\python\framework\convert_to_constants.py":406:0) at callsite("C:\Users\jing_\anaconda3\envs\tf2-gpu\lib\site-packages\tensorflow\python\framework\convert_to_constants.py":680:0 at callsite("C:\Users\jing_\anaconda3\envs\tf2-gpu\lib\site-packages\tensorflow\lite\python\lite.py":1086:0 at "convert.py":13:0)))): error: body function result type tensor<?x128x128xf32> is incompatible with result type tensor<1900x1x128xf32> at index 3
Traceback (most recent call last):
  File "c:\users\jing_\anaconda3\envs\tf2-gpu\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\jing_\anaconda3\envs\tf2-gpu\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\jing_\anaconda3\envs\tf2-gpu\Scripts\toco_from_protos.exe\__main__.py", line 7, in <module>
  File "c:\users\jing_\anaconda3\envs\tf2-gpu\lib\site-packages\tensorflow\lite\toco\python\toco_from_protos.py", line 93, in main
    app.run(main=execute, argv=[sys.argv[0]] + unparsed)
  File "c:\users\jing_\anaconda3\envs\tf2-gpu\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "c:\users\jing_\anaconda3\envs\tf2-gpu\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "c:\users\jing_\anaconda3\envs\tf2-gpu\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "c:\users\jing_\anaconda3\envs\tf2-gpu\lib\site-packages\tensorflow\lite\toco\python\toco_from_protos.py", line 56, in execute
    enable_mlir_converter)
Exception: C:\Users\jing_\anaconda3\envs\tf2-gpu\lib\site-packages\tensorflow\python\framework\convert_to_constants.py:406:52: error: body function result type tensor<?x128x128xf32> is incompatible with result type tensor<1900x1x128xf32> at index 3
                                                   new_output_names)
                                                   ^
C:\Users\jing_\anaconda3\envs\tf2-gpu\lib\site-packages\tensorflow\python\framework\convert_to_constants.py:680:3: note: called from
  return _construct_concrete_function(func, output_graph_def, converted_inputs)
  ^
C:\Users\jing_\anaconda3\envs\tf2-gpu\lib\site-packages\tensorflow\lite\python\lite.py:1086:11: note: called from
          concrete_func, lower_control_flow=False)
          ^
convert.py:13:5: note: called from
    input_shapes={'embedding_input': (128,1900)}
    ^
C:\Users\jing_\anaconda3\envs\tf2-gpu\lib\site-packages\tensorflow\python\framework\convert_to_constants.py:406:52: note: see current operation: %75:11 = "tf.While"(%6, %17, %6, %0, %73, %74, %5, %70, %43, %46, %49) {_lower_using_switch_merge = false, _num_original_outputs = 11 : i64, _read_only_resource_inputs = [], body = @while_body_3631_frozen0, cond = @while_cond_3630_frozen0, device = "", is_stateless = true, output_shapes = ["tfshape$", "tfshape$", "tfshape$", "tfshape$", "tfshape$dim { size: -1 } dim { size: 128 }", "tfshape$dim { size: -1 } dim { size: 128 }", "tfshape$", "tfshape$", "tfshape$dim { size: 128 } dim { size: 512 }", "tfshape$dim { size: 128 } dim { size: 512 }", "tfshape$dim { size: 512 }"], parallel_iterations = 32 : i64} : (tensor<i32>, tensor<i32>, tensor<i32>, tensor<1900x1x128xf32>, tensor<128x128xf32>, tensor<128x128xf32>, tensor<i32>, tensor<1900x128x128xf32>, tensor<128x512xf32>, tensor<128x512xf32>, tensor<512xf32>) -> (tensor<i32>, tensor<i32>, tensor<i32>, tensor<1900x1x128xf32>, tensor<128x128xf32>, tensor<128x128xf32>, tensor<i32>, tensor<1900x128x128xf32>, tensor<128x512xf32>, tensor<128x512xf32>, tensor<512xf32>)
                                                   new_output_names)
                                                   ^
```

**Failure details**

I am trying to utilize GPU delegate on the Android platform. When I use the normal way of converting i.e converter = tf.lite.TFLiteConverter.from_keras_model(loaded_model) without enabling GPU delegate, everything works fine, just that the inference time cost is a bit high. So I want to enable GPU delegate to see if it improves the time cost. However, GPU delegate doesn't allow dynamic-sized tensors, thus, when converting, I need to set the size of my input layer, which I did in the above code, but I couldn't get the model to convert after that.
Summary of my model is as follows:
```
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
embedding (Embedding)        (None, 1900, 128)         377600
_________________________________________________________________
bidirectional (Bidirectional (None, 1900, 256)         263168
_________________________________________________________________
batch_normalization (BatchNo (None, 1900, 256)         1024
_________________________________________________________________
global_max_pooling1d (Global (None, 256)               0
_________________________________________________________________
dense (Dense)                (None, 64)                16448
_________________________________________________________________
dense_1 (Dense)              (None, 32)                2080
_________________________________________________________________
dense_2 (Dense)              (None, 2)                 66
=================================================================
Total params: 660,386
Trainable params: 659,874
Non-trainable params: 512
```

**Comment by ravikyram** [comment]
@limjq45 

Can you try with this code. Will it be possible to share model.h5 file to reproduce the issue in our environment.

```
converter = tf.lite.TFLiteConverter.from_keras_model_file(
    'model.h5',
    input_shapes={'embedding_input': (128,1900)}
)

converter = tf.lite.TFLiteConverter.from_keras_model(loaded_model) 
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,
                                       tf.lite.OpsSet.SELECT_TF_OPS]
converter.allow_custom_ops=True
converter.experimental_new_converter =True
tfmodel = converter.convert() 
open ('model.tflite' , "wb") .write(tfmodel)
```
Thanks!

**Comment by limjq45** [comment]
> @limjq45
> 
> Can you try with this code. Will it be possible to share model.h5 file to reproduce the issue in our environment.
> 
> ```
> converter = tf.lite.TFLiteConverter.from_keras_model_file(
>     'model.h5',
>     input_shapes={'embedding_input': (128,1900)}
> )
> 
> converter = tf.lite.TFLiteConverter.from_keras_model(loaded_model) 
> converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,
>                                        tf.lite.OpsSet.SELECT_TF_OPS]
> converter.allow_custom_ops=True
> converter.experimental_new_converter =True
> tfmodel = converter.convert() 
> open ('model.tflite' , "wb") .write(tfmodel)
> ```
> 
> Thanks!

Hi , I did try the above code too, it is able to convert but when I load it into the device, it throws this error
```
Internal error: Failed to apply delegate: Encountered unresolved custom op: TensorListReserve.
```

Here's a copy of the model.h5 [https://drive.google.com/open?id=1vj8Ini-XhX57obGUNTdCNBwbkigWyFOx](url)
The embedding input shape is (128,300), still the same structure, just that the max_length is changed.

P/s: anyway I tried to do a simple Embedding -> LSTM(unroll=True) -> Dense(softmax), somehow when unroll=true on LSTM, it allows me to delegate GPU on Android with the code I posted, but when I run it, it just throws this error on Android 
```
A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
```

**Comment by jvishnuvardhan** [comment]
@limjq45 Which tflite application you are trying implement? I would like to reproduce the error on my device and see what is root-cause. Thanks!

**Comment by limjq45** [comment]
> @limjq45 Which tflite application you are trying implement? I would like to reproduce the error on my device and see what is root-cause. Thanks!

@jvishnuvardhan I am basically trying to build a Bidirectional LSTM text classifier. I used this code as my template:[https://github.com/tensorflow/examples/tree/master/lite/examples/text_classification/android](url).

Given the network configuration in the first post, I am able to train out a model, convert it to tflite, and classify text successfully on my device.

The code I used to convert is as follows:
```
loaded_model = tf.keras.models.load_model('model.h5')
converter = tf.lite.TFLiteConverter.from_keras_model(loaded_model) 
tfmodel = converter.convert() 
open ('model.tflite' , "wb") .write(tfmodel)
```

The problem is, the inference time is too long and I would like to try enabling GPU delegate on my device, however, the current model will not work as it has dynamic-sized tensors.

I've googled and they mentioned to make it static-sized, I will need to specify the input shape during conversion, so I tried the following code:

``` 
converter = tf.compat.v1.lite.TFLiteConverter.from_keras_model_file(
    'model.h5',
    input_shapes={'embedding_input': (128,1900)}
)
tfmodel = converter.convert() 
open ('model.tflite' , "wb") .write(tfmodel)
```
I did try with the experimental flag too, but it doesn't allow me to convert successfully.

The only time I am able to convert successfully with the above code is when the unroll flag in LSTM layer is set to True. I am also able to add GPU delegate successfully with the converted model, however, when I tried to classify a string of text, it just crashes with this error.

```
A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
```

**Comment by limjq45** [comment]
@jvishnuvardhan were you able to reproduce the error? If not I can create a colab notebook for you

**Comment by ashwinmurthy** [comment]
@limjq45

**Comment by limjq45** [comment]
@ashwinmurthy hi, the link you provided is not working.

**Comment by limjq45** [comment]
I will close this issue and open another one
