### ISSUE TITLE
MultiRNNCell with state_is_tuple=True got Error!

### ISSUE THREAD

**Issue by xinyuwuhenZZ** [tensorflow/tensorflow#3895]
Running MultiRNN, when I set 
```
cell = tf.nn.rnn_cell.LSTMCell(state_size, state_is_tuple=True)
cell = tf.nn.rnn_cell.MultiRNNCell([cell] * num_layers, state_is_tuple=True)
```
got following error:
```
Traceback (most recent call last):
  File "/Users/nali/Workspace/tensorflow_example/search_click/RNN/lstm.py", line 175, in <module>
    train_network(g, 3)
  File "/Users/nali/Workspace/tensorflow_example/search_click/RNN/lstm.py", line 140, in train_network
    [g['total_loss'], g['final_state'], g['train_step']], feed_dict)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 372, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 584, in _run
    processed_fetches = self._process_fetches(fetches)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 540, in _process_fetches
    % (subfetch, fetch, type(subfetch), str(e)))
TypeError: Fetch argument (LSTMStateTuple(c=<tf.Tensor 'RNN/while/Exit_2:0' shape=(32, 100) dtype=float32>, h=<tf.Tensor 'RNN/while/Exit_3:0' shape=(32, 100) dtype=float32>), LSTMStateTuple(c=<tf.Tensor 'RNN/while/Exit_4:0' shape=(32, 100) dtype=float32>, h=<tf.Tensor 'RNN/while/Exit_5:0' shape=(32, 100) dtype=float32>), LSTMStateTuple(c=<tf.Tensor 'RNN/while/Exit_6:0' shape=(32, 100) dtype=float32>, h=<tf.Tensor 'RNN/while/Exit_7:0' shape=(32, 100) dtype=float32>)) of (LSTMStateTuple(c=<tf.Tensor 'RNN/while/Exit_2:0' shape=(32, 100) dtype=float32>, h=<tf.Tensor 'RNN/while/Exit_3:0' shape=(32, 100) dtype=float32>), LSTMStateTuple(c=<tf.Tensor 'RNN/while/Exit_4:0' shape=(32, 100) dtype=float32>, h=<tf.Tensor 'RNN/while/Exit_5:0' shape=(32, 100) dtype=float32>), LSTMStateTuple(c=<tf.Tensor 'RNN/while/Exit_6:0' shape=(32, 100) dtype=float32>, h=<tf.Tensor 'RNN/while/Exit_7:0' shape=(32, 100) dtype=float32>)) has invalid type <type 'tuple'>, must be a string or Tensor. (Can not convert a tuple into a Tensor or Operation.)
```
But when I set state_is_tuple=False(Default), it works fine.
However, state_is_tuple=True is recommended to faster LSTM states.

**Comment by prb12** [comment]
Please can you provide full details of Tnesorflow version and steps to reproduce, as requested in the issues reporting template we provided.

**Comment by xinyuwuhenZZ** [comment]
Thanks for your help in advance.

Tensorflow version is v0.9,  the running code as follows:

```
def build_multilayer_lstm_graph_with_dynamic_rnn(state_size=100, num_classes=vocab_size, batch_size=32,
                                                 num_steps=200, num_layers=3, learning_rate=1e-4):
    reset_graph()

    x = tf.placeholder(tf.int32, [batch_size, num_steps], name='input_placeholder')
    y = tf.placeholder(tf.int32, [batch_size, num_steps], name='labels_placeholder')

    embeddings = tf.get_variable('embedding_matrix', [num_classes, state_size])

    # Note that our inputs are no longer a list, but a tensor of dims batch_size x num_steps x state_size
    rnn_inputs = tf.nn.embedding_lookup(embeddings, x)

    cell = tf.nn.rnn_cell.LSTMCell(state_size, state_is_tuple=True)
    cell = tf.nn.rnn_cell.MultiRNNCell([cell] * num_layers, state_is_tuple=True)
    init_state = cell.zero_state(batch_size, tf.float32)
    rnn_outputs, final_state = tf.nn.dynamic_rnn(cell, rnn_inputs, initial_state=init_state)

    with tf.variable_scope('softmax'):
        W = tf.get_variable('W', [state_size, num_classes])
        b = tf.get_variable('b', [num_classes], initializer=tf.constant_initializer(0.0))

    # reshape rnn_outputs and y so we can get the logits in a single matmul
    rnn_outputs = tf.reshape(rnn_outputs, [-1, state_size])
    y_reshaped = tf.reshape(y, [-1])
    logits = tf.matmul(rnn_outputs, W) + b
    total_loss = tf.reduce_mean(tf.nn.sparse_softmax_cross_entropy_with_logits(logits, y_reshaped))
    train_step = tf.train.AdamOptimizer(learning_rate).minimize(total_loss)
    return dict(x=x, y=y, init_state=init_state, final_state=final_state, total_loss=total_loss, train_step=train_step)
```

The problem happens when I set  state_is_tuple=True.

**Comment by ebrevdo** [comment]
Try Tf 0.10 or newer. Do you still get the error?

**Comment by xinyuwuhenZZ** [comment]
Error solved!

Thanks for your response.
