### ISSUE TITLE
image.image_gradients error "Duplicate node name in graph: 'stack'"

### ISSUE THREAD

**Issue by emiliocoutinho** [tensorflow/tensorflow#38963]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10.0.17134
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: v2.0.0-rc2-26-g64c3d382ca 2.0.0
- **Python version**: 3.7.7
- **CUDA/cuDNN version**: Running on CPU
- **GPU model and memory**:
- **Exact command to reproduce**:

### Describe the problem
When trying to use tf.image.image_gradients, get an error: "ValueError: Duplicate node name in graph: 'stack'", when trying to predict the model.

### Source code / logs
The source code can be found below:

```
from tensorflow import image
from tensorflow.keras import layers, Model
import tensorflow as tf
from tensorflow.keras import backend as K
import numpy as np

myInput = layers.Input(shape=(4, 4, 1))

[deltaP_t_i, deltaP_t_j] = image.image_gradients(myInput[:, :, :, 0:1])
loss_grad = tf.norm(deltaP_t_i, axis=(1, 2)) + tf.norm(deltaP_t_i, axis=(1, 2))
loss_grad = K.mean(loss_grad, axis=-1)

myModel = Model(inputs=[myInput], outputs=[loss_grad])

x = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8.1],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

x = np.reshape(x, (1, 4, 4, 1))

out1 = myModel.predict([x])
```

and the output is below:

``` 
2020-04-27 18:50:11.221070: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Traceback (most recent call last):
  File "C:\Users\emiliocoutinho\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1610, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Duplicate node name in graph: 'stack'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/test/TestPhysicalLossToReport.py", line 9, in <module>
    [deltaP_t_i, deltaP_t_j] = image.image_gradients(myInput[:, :, :, 0:1])
  File "C:\Users\emiliocoutinho\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\ops\image_ops_impl.py", line 3456, in image_gradients
    shape = array_ops.stack([batch_size, height, 1, depth])
  File "C:\Users\emiliocoutinho\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\util\dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "C:\Users\emiliocoutinho\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\ops\array_ops.py", line 1165, in stack
    return gen_array_ops.pack(values, axis=axis, name=name)
  File "C:\Users\emiliocoutinho\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\ops\gen_array_ops.py", line 6303, in pack
    "Pack", values=values, axis=axis, name=name)
  File "C:\Users\emiliocoutinho\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\framework\op_def_library.py", line 793, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\emiliocoutinho\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\framework\func_graph.py", line 548, in create_op
    compute_device)
  File "C:\Users\emiliocoutinho\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3429, in _create_op_internal
    op_def=op_def)
  File "C:\Users\emiliocoutinho\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1773, in __init__
    control_input_ops)
  File "C:\Users\emiliocoutinho\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1613, in _create_c_op
    raise ValueError(str(e))
ValueError: Duplicate node name in graph: 'stack'

Process finished with exit code 1
```

**Comment by Saduf2019** [comment]
@emiliocoutinho 
i ran the code shared by you and there is no error faced, please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/285fc09d4c59bcd4c4181edade91bdf5/untitled160.ipynb)

please refer to these links with similar error:
[link1](https://github.com/tensorflow/tensorflow/issues/36509#issuecomment-583247460)
[link2](https://github.com/tensorflow/tensorflow/issues/20997)
[link3](https://stackoverflow.com/questions/53172215/duplicate-node-name-in-graph-conv2d-0-kernel-adam)

**Comment by emiliocoutinho** [comment]
@Saduf2019, thanks for this feedback. Using the tf-nightly version works fine. I was previously using TensorFlow 2.0.0. This problem also happens with version 2.1. With the nightly version, works.
