### ISSUE TITLE
Build won't start.

### ISSUE THREAD

**Issue by zenboooooon** [tensorflow/tensorflow#38981]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):MacOS 10.13.6(17g65)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):source
- TensorFlow version:1.14
- Python version:3.6.5
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):0.24.1
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:10
- GPU model and memory:GTX GeForce 1080ti

**Describe the problem**
I want to build tensorflow 1.14, but I get an error like this and I can't start it.
Please tell why it is

`ERROR: Skipping '//tensorflow/tools/pip_package:build_pip_package': error loading package 'tensorflow/tools/pip_package': Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
	File "/Users/zen/tensorflow/third_party/gpus/cuda_configure.bzl", line 1266
		_create_local_cuda_repository(repository_ctx)
	File "/Users/zen/tensorflow/third_party/gpus/cuda_configure.bzl", line 1033, in _create_local_cuda_repository
		_find_libs(repository_ctx, cuda_config)
	File "/Users/zen/tensorflow/third_party/gpus/cuda_configure.bzl", line 607, in _find_libs
		_find_cuda_lib("cuda", repository_ctx, cpu_value, (cu...), ...)
	File "/Users/zen/tensorflow/third_party/gpus/cuda_configure.bzl", line 588, in _find_cuda_lib
		find_lib(repository_ctx, [("%s/%s" % (based...))], ...)))
	File "/Users/zen/tensorflow/third_party/gpus/cuda_configure.bzl", line 565, in find_lib
		auto_configure_fail(("No library found under: " + ",...)))
	File "/Users/zen/tensorflow/third_party/gpus/cuda_configure.bzl", line 324, in auto_configure_fail
		fail(("\n%sCuda Configuration Error:%...)))

Cuda Configuration Error: No library found under: /usr/local/cuda/lib/stubs/libcuda.dylib
WARNING: Target pattern parsing failed.
ERROR: error loading package 'tensorflow/tools/pip_package': Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
	File "/Users/zen/tensorflow/third_party/gpus/cuda_configure.bzl", line 1266
		_create_local_cuda_repository(repository_ctx)
	File "/Users/zen/tensorflow/third_party/gpus/cuda_configure.bzl", line 1033, in _create_local_cuda_repository
		_find_libs(repository_ctx, cuda_config)
	File "/Users/zen/tensorflow/third_party/gpus/cuda_configure.bzl", line 607, in _find_libs
		_find_cuda_lib("cuda", repository_ctx, cpu_value, (cu...), ...)
	File "/Users/zen/tensorflow/third_party/gpus/cuda_configure.bzl", line 588, in _find_cuda_lib
		find_lib(repository_ctx, [("%s/%s" % (based...))], ...)))
	File "/Users/zen/tensorflow/third_party/gpus/cuda_configure.bzl", line 565, in find_lib
		auto_configure_fail(("No library found under: " + ",...)))
	File "/Users/zen/tensorflow/third_party/gpus/cuda_configure.bzl", line 324, in auto_configure_fail
		fail(("\n%sCuda Configuration Error:%...)))

Cuda Configuration Error: No library found under: /usr/local/cuda/lib/stubs/libcuda.dylib
`

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ravikyram** [comment]
@zenboooooon 

Provide the exact sequence of commands / steps that you executed before running into the problem.Thanks!
