### ISSUE TITLE
Sigmoid returns negative values

### ISSUE THREAD

**Issue by julie-jiang** [tensorflow/tensorflow#38987]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
CentOs Linux 7 (Core)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
pip3 installed tensorflow-gpu
- TensorFlow version (use command below):
2.1.0
- Python version:
3.6.0
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
cuda 10.1 cudnn 7.6.4
- GPU model and memory:
Tesla P100 75GB

**Describe the current behavior**
The last output layer is a sigmoid function, but the AUC metric says output is not >= 0 element-wise. I've also tried this using `activation='sigmoid'` in the output layer directly, which also results in the same error.

I've verified that after removing AUC as a metric,  the code works but the min output value becomes negative after a few epochs. 

**Describe the expected behavior**
Sigmoid output should be 0-1

**Last part of the code **

```
    ypred = tf.keras.layers.Dense(                                              
            1, name="%s_out" % target_variable,                                 
            kernel_regularizer=tf.keras.regularizers.l2(beta))(x)               
                                                                    
    ypred = tf.nn.sigmoid(ypred)                                            

                                                                                
    model = tf.keras.models.Model(inputs=inputs, outputs=ypred)                 
    optimizer = tf.keras.optimizers.Adam(lr)                                    
    model.compile(optimizer=optimizer,                                          
                  loss='binary_crossentropy',                                   
                  metrics=['accuracy', 'AUC', 'mse'])             
                                                                                                                                        
    early_stopping = tf.keras.callbacks.EarlyStopping(patience=100)             
                  
    callbacks = [early_stopping]                                                
                                                                                
    model_start_time = time.time()                                              
   
    model.evaluate(test_ds, verbose=2)                                      
                                                                                
    history = model.fit(                                                        
            train_ds, validation_data=(test_ds), epochs=num_epochs,             
            verbose=2, callbacks=callbacks)
```
**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

```
Traceback (most recent call last):
  File "lol_embed_ntf_champs.py", line 162, in <module>
    save_results=args.save_results, **datum)
  File "/auto/rcf-40/yioujian/ntf-embed/lol_embedding_ntf_champs.py", line 160, in run_embed_ntf
    verbose=2, callbacks=callbacks)
  File "/home/rcf-proj2/ef/yioujian/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py", line 819, in fit
    use_multiprocessing=use_multiprocessing)
  File "/home/rcf-proj2/ef/yioujian/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 342, in fit
    total_epochs=epochs)
  File "/home/rcf-proj2/ef/yioujian/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 128, in run_one_epoch
    batch_outs = execution_function(iterator)
  File "/home/rcf-proj2/ef/yioujian/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 98, in execution_function
    distributed_function(input_fn))
  File "/home/rcf-proj2/ef/yioujian/.local/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 568, in __call__
    result = self._call(*args, **kwds)
  File "/home/rcf-proj2/ef/yioujian/.local/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 599, in _call
    return self._stateless_fn(*args, **kwds)  # pylint: disable=not-callable
  File "/home/rcf-proj2/ef/yioujian/.local/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2363, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/home/rcf-proj2/ef/yioujian/.local/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1611, in _filtered_call
    self.captured_inputs)
  File "/home/rcf-proj2/ef/yioujian/.local/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1692, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/home/rcf-proj2/ef/yioujian/.local/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 545, in call
    ctx=ctx)
  File "/home/rcf-proj2/ef/yioujian/.local/lib/python3.6/site-packages/tensorflow_core/python/eager/execute.py", line 67, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument:  assertion failed: [predictions must be >= 0] [Condition x >= y did not hold element-wise:] [x (model/tf_op_layer_Sigmoid/Sigmoid:0) = ] [[0.323994398][0.177097648][0.000274539]...] [y (metrics/AUC/Cast_1/x:0) = ] [0]
	 [[{{node metrics/AUC/assert_greater_equal/Assert/AssertGuard/else/_1/Assert}}]]
	 [[metrics/AUC/assert_less_equal/Assert/AssertGuard/pivot_f/_13/_39]]
  (1) Invalid argument:  assertion failed: [predictions must be >= 0] [Condition x >= y did not hold element-wise:] [x (model/tf_op_layer_Sigmoid/Sigmoid:0) = ] [[0.323994398][0.177097648][0.000274539]...] [y (metrics/AUC/Cast_1/x:0) = ] [0]
	 [[{{node metrics/AUC/assert_greater_equal/Assert/AssertGuard/else/_1/Assert}}]]
0 successful operations.
0 derived errors ignored. [Op:__inference_distributed_function_4015]

Function call stack:
distributed_function -> distributed_function
```

**Comment by julie-jiang** [comment]
Update: it seems that the issue might be related to AUC and not sigmoid, because after removing AUC there were no negative outputs. However, I also realized the result is not deterministic (even though I've seeded everything, I don't know why)

I did manage to fix the problem by manually clipping the value to be between 0 and 1, however.

**Comment by ravikyram** [comment]
@julie-jiang 

Please, let us know   is this still an issue. Please, close this thread if your issue was resolved.

If the issue was not resolved request you to share colab link or simple standalone to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by Namzakku** [comment]
@julie-jiang I'm running into the same issue. Can you share how you clip the value to be between 0 and 1?

**Comment by julie-jiang** [comment]
@Namzakku You can either use [tf.clip_by_value](https://www.tensorflow.org/api_docs/python/tf/clip_by_value) or [tf.clip_by_norm](https://www.tensorflow.org/api_docs/python/tf/clip_by_norm). Here's a complete [example](https://stackoverflow.com/questions/36498127/how-to-apply-gradient-clipping-in-tensorflow)
