### ISSUE TITLE
Inception model error on upgrading Tensorflow

### ISSUE THREAD

**Issue by eldor4do** [tensorflow/tensorflow#3898]
I am loading the Inception model as,

```
def load_network(png=False):
        with gfile.FastGFile(CONFIG_PATH + '/data/network.pb', 'rb') as f:
            graph_def = tf.GraphDef()
            data = f.read()
            graph_def.ParseFromString(data)
            if png:
                png_data = tf.placeholder(tf.string, shape=[])
                decoded_png = tf.image.decode_png(png_data, channels=3)
                _ = tf.import_graph_def(graph_def, name='', input_map={'DecodeJpeg': decoded_png})
                return png_data
            else:
                _ = tf.import_graph_def(graph_def, name='')
```

However, after upgrading from Tensorflow 0.8 to 0.10, this is giving an error,
```
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/importer.py", line 241, in import_graph_def
    raise ValueError('tf.import_graph_def() requires a non-empty `name` '
ValueError: tf.import_graph_def() requires a non-empty `name` if `input_map` is used.
```

I then removed the ` name=''` part as,
```
                _ = tf.import_graph_def(graph_def, input_map={'DecodeJpeg': decoded_png})
                return png_data
            else:
                _ = tf.import_graph_def(graph_def)

```

This part then runs fine, however later on in my code when I am trying to get the pool3 layer's output I get the following error,

```
    pool3 = sess.graph.get_tensor_by_name('pool_3:0')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2531, in get_tensor_by_name
    return self.as_graph_element(name, allow_tensor=True, allow_operation=False)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2385, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2427, in _as_graph_element_locked
    "graph." % (repr(name), repr(op_name)))
KeyError: "The name 'pool_3:0' refers to a Tensor which does not exist. The operation, 'pool_3', does not exist in the graph."
```
What could be the problem?

**Comment by suiyuan2009** [comment]
according to the doc, [import_graph_def](https://www.tensorflow.org/versions/r0.10/api_docs/python/framework.html#import_graph_def), the default value of `name` is `import`, and it says `A prefix that will be prepended to the names in graph_def`.

**Comment by eldor4do** [comment]
@suiyuan2009 Yes, but that does not solve my problem?

**Comment by suiyuan2009** [comment]
in my understanding, all tensor name's prefix will be `name`, if you don't set, it will be `import`

**Comment by eldor4do** [comment]
So you're saying that the 'pool_3:0' layer I am after is actually 'importpool_3;0'?

**Comment by suiyuan2009** [comment]
maybe import/pool_3:0, actually you can use tensorboard to see the graph, every tensor and op's information will show on tensorboard.

**Comment by eldor4do** [comment]
Yes, thanks, this works!

**Comment by sumit1212** [comment]
> I have same issue...
> I have doing real time face recognition using tensorflow.
>  I'm follow this link "https://github.com/btwardow/tf-face-recognition"
> When I'm download clone repo it work in one system but try to run another one this show me error.
Please help me out.

`Traceback (most recent call last):
  File "server.py", line 49, in detect
    faces = recognize(detection.get_faces(image, threshold))
  File "/home/bigblue/Music/Test/tf-face-recognition-master/tensorface/recognition.py", line 19, in recognize
    X[i, :] = embedding(img_to_np(img))
  File "/home/bigblue/Music/Test/tf-face-recognition-master/tensorface/embedding.py", line 43, in embedding
    images_placeholder = tf.get_default_graph().get_tensor_by_name("input:0")
  File "/home/bigblue/anaconda3/envs/my_env/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3666, in get_tensor_by_name
    return self.as_graph_element(name, allow_tensor=True, allow_operation=False)
  File "/home/bigblue/anaconda3/envs/my_env/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3490, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/home/bigblue/anaconda3/envs/my_env/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3532, in _as_graph_element_locked
    "graph." % (repr(name), repr(op_name)))
**KeyError: "The name 'input:0' refers to a Tensor which does not exist. The operation, 'input', does not exist in the graph."**
[2019-02-26 11:28:06,532] ERROR in app: Exception on /detect [POST]
Traceback (most recent call last):
  File "server.py", line 49, in detect
    faces = recognize(detection.get_faces(image, threshold))
  File "/home/bigblue/Music/Test/tf-face-recognition-master/tensorface/recognition.py", line 19, in recognize
    X[i, :] = embedding(img_to_np(img))
  File "/home/bigblue/Music/Test/tf-face-recognition-master/tensorface/embedding.py", line 43, in embedding
    images_placeholder = tf.get_default_graph().get_tensor_by_name("input:0")
  File "/home/bigblue/anaconda3/envs/my_env/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3666, in get_tensor_by_name
    return self.as_graph_element(name, allow_tensor=True, allow_operation=False)
  File "/home/bigblue/anaconda3/envs/my_env/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3490, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/home/bigblue/anaconda3/envs/my_env/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3532, in _as_graph_element_locked
    "graph." % (repr(name), repr(op_name)))
KeyError: "The name 'input:0' refers to a Tensor which does not exist. The operation, 'input', does not exist in the graph."

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bigblue/anaconda3/envs/my_env/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bigblue/anaconda3/envs/my_env/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bigblue/anaconda3/envs/my_env/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/bigblue/anaconda3/envs/my_env/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/bigblue/anaconda3/envs/my_env/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bigblue/anaconda3/envs/my_env/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "server.py", line 69, in detect
    print('POST /detect error: %e' % e)
TypeError: must be real number, not KeyError`
