### ISSUE TITLE
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: The specified module could not be found.

### ISSUE THREAD

**Issue by jlinxciv** [tensorflow/tensorflow#39007]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 64-bit
- TensorFlow installed from (source or binary): 
- TensorFlow version: 20.1
- Python version: Python 3.8 (64-bit)
- Installed using virtualenv? pip? conda?: pip
- GCC/Compiler version (if compiling from source): Jupyter
- CUDA/cuDNN version:
- GPU model and memory: Intel HD graphics 620 8239 MB
- CPU Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz 2.71 GHz

Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "C:\Users\linj\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\linj\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\linj\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\linj\AppData\Local\Programs\Python\Python38\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\linj\AppData\Local\Programs\Python\Python38\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\linj\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\linj\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\__init__.py", line 50, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\linj\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 69, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\linj\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\linj\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\linj\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\linj\AppData\Local\Programs\Python\Python38\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\linj\AppData\Local\Programs\Python\Python38\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: The specified module could not be found.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
>>>

**Comment by Saduf2019** [comment]
@jlinxciv 
Please refer to [this comment](https://github.com/tensorflow/tensorflow/issues/38916#issuecomment-619572753), also, refer similar issues:

#36167 #36151 #36138 #36054 #36045 #36020 #36003 #35988 #35903 #35880 #35865 #35805 #35789 #35773 #35772 #35767 #35766 #35749 #35721 #35618 #35204

if possible please upgrade your tensorflow to later version and let us know if that helps you resolve the issue.
Thanks!

**Comment by mihaimaruseac** [comment]
Closing as duplicate

**Comment by stutisehgal** [comment]
Traceback (most recent call last):
  File "C:\Users\LEGION\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed: The specified module could not be found.


Failed to load the native TensorFlow runtime. 

I have installed Anaconda inside my D drive and have made environment variable for C drive anaconda scripts
I have installed tensorflow in a separate tf environment in anaconda from where this error is coming in my spyder tf env file

**Comment by susingh95** [comment]
> Traceback (most recent call last):
> File "C:\Users\LEGION\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in
> from tensorflow.python._pywrap_tensorflow_internal import *
> ImportError: DLL load failed: The specified module could not be found.
> 
> Failed to load the native TensorFlow runtime.
> 
> I have installed Anaconda inside my D drive and have made environment variable for C drive anaconda scripts
> I have installed tensorflow in a separate tf environment in anaconda from where this error is coming in my spyder tf env file

![same for tensor 2 3   it is not suitable for python3 8](https://user-images.githubusercontent.com/66783491/89713740-5f56fb80-d9b7-11ea-93fa-d08acc298f9b.JPG)

**Comment by susingh95** [comment]
this issue is same for every python 3.8 version.

use google collab          or  convert your python version into lower one.

**Comment by mihaimaruseac** [comment]
Python 3.8 works in TF 2.2 and TF 2.3. You need to have a 64 bit Python. If on Windows, you need to ensure you have the latest MSVC redistributable and that the Python binary is installed from official sources, not from Windows marketplace

**Comment by sparachi1011** [comment]
> this issue is same for every python 3.8 version.
> 
> use google collab or convert your python version into lower one.

I tried with Python 3.6 and 3.7 but no luck still facing same issue

**Comment by abhaydesai76** [comment]
Hi, I am trying to install TensorFlow and getting below error:

ImportError: DLL load failed while importing _pywrap_tensorflow_internal: A dynamic link library (DLL) initialization routine failed.

I have tried with TF 2.3 as 2.2  and getting same error, Python 3.8.5.
