### ISSUE TITLE
"file not found" Error in generating tfrecords

### ISSUE THREAD

**Issue by Monster-Gaming-Studios** [tensorflow/tensorflow#39018]
Hello,
I am getting a error saying that the file or directory was not found while generating the tfrecords. I am running the code in Google Colaboratory.

- **Here is the command I am using:**

 ```command output
!cd '/content/kangaroo';python '/content/drive/My Drive/Colab Notebooks/n.py' --csv_input='/content/kangaroo/images/test_labels.csv' --image_dir='/content/kangaroo/test' --output_path='/content/kangaroo/test.record'
```

- **Here is the full traceback**
```
WARNING:tensorflow:From /content/drive/My Drive/Colab Notebooks/n.py:238: The name tf.app.run is deprecated. Please use tf.compat.v1.app.run instead.

WARNING:tensorflow:From /content/drive/My Drive/Colab Notebooks/n.py:223: The name tf.python_io.TFRecordWriter is deprecated. Please use tf.io.TFRecordWriter instead.

W0429 10:10:48.066490 139827938125696 module_wrapper.py:139] From /content/drive/My Drive/Colab Notebooks/n.py:223: The name tf.python_io.TFRecordWriter is deprecated. Please use tf.io.TFRecordWriter instead.

WARNING:tensorflow:From /content/drive/My Drive/Colab Notebooks/n.py:182: The name tf.gfile.GFile is deprecated. Please use tf.io.gfile.GFile instead.

W0429 10:10:48.075507 139827938125696 module_wrapper.py:139] From /content/drive/My Drive/Colab Notebooks/n.py:182: The name tf.gfile.GFile is deprecated. Please use tf.io.gfile.GFile instead.

Traceback (most recent call last):
  File "/content/drive/My Drive/Colab Notebooks/n.py", line 238, in <module>
    tf.app.run()
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/content/drive/My Drive/Colab Notebooks/n.py", line 228, in main
    tf_example = create_tf_example(group, path)
  File "/content/drive/My Drive/Colab Notebooks/n.py", line 183, in create_tf_example
    encoded_jpg = fid.read()
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/lib/io/file_io.py", line 122, in read
    self._preread_check()
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/lib/io/file_io.py", line 84, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512)
tensorflow.python.framework.errors_impl.NotFoundError: /content/kangaroo/test/0004.jpg; No such file or directory
```

- **Here is the code I am using to generate tfrecords**
```python
"""
Usage:
  # From tensorflow/models/
  # Create train data:
  python generate_tfrecord.py --csv_input=data/train_labels.csv  --output_path=train.record
  # Create test data:
  python generate_tfrecord.py --csv_input=data/test_labels.csv  --output_path=test.record
"""
from __future__ import division
from __future__ import print_function
from __future__ import absolute_import

import os
import io
import pandas as pd
import tensorflow as tf

from PIL import Image
from object_detection.utils import dataset_util
from collections import namedtuple, OrderedDict

flags = tf.app.flags
flags.DEFINE_string('csv_input', '', 'Path to the CSV input')
flags.DEFINE_string('output_path', '', 'Path to output TFRecord')
flags.DEFINE_string('image_dir', '', 'Path to images')
FLAGS = flags.FLAGS


# TO-DO replace this with label map
def class_text_to_int(row_label):
    if row_label == 'A':
        return 1
    elif row_label == 'B':
        return 2
    elif row_label == 'C':
        return 3
    elif row_label == 'D':
        return 4
    elif row_label == 'E':
        return 5
    elif row_label == 'F':
        return 6
    elif row_label == 'G':
        return 7
    elif row_label == 'H':
        return 8
    elif row_label == 'I':
        return 9
    else:
        None


def split(df, group):
    data = namedtuple('data', ['filename', 'object'])
    gb = df.groupby(group)
    return [data(filename, gb.get_group(x)) for filename, x in zip(gb.groups.keys(), gb.groups)]


def create_tf_example(group, path):
    with tf.gfile.GFile(os.path.join(path, '{}'.format(group.filename)), 'rb') as fid:
        encoded_jpg = fid.read()
    encoded_jpg_io = io.BytesIO(encoded_jpg)
    image = Image.open(encoded_jpg_io)
    width, height = image.size

    filename = group.filename.encode('utf8')
    image_format = b'jpg'
    xmins = []
    xmaxs = []
    ymins = []
    ymaxs = []
    classes_text = []
    classes = []

    for index, row in group.object.iterrows():
        xmins.append(row['xmin'] / width)
        xmaxs.append(row['xmax'] / width)
        ymins.append(row['ymin'] / height)
        ymaxs.append(row['ymax'] / height)
        classes_text.append(row['class'].encode('utf8'))
        classes.append(class_text_to_int(row['class']))

    tf_example = tf.train.Example(features=tf.train.Features(feature={
        'image/height': dataset_util.int64_feature(height),
        'image/width': dataset_util.int64_feature(width),
        'image/filename': dataset_util.bytes_feature(filename),
        'image/source_id': dataset_util.bytes_feature(filename),
        'image/encoded': dataset_util.bytes_feature(encoded_jpg),
        'image/format': dataset_util.bytes_feature(image_format),
        'image/object/bbox/xmin': dataset_util.float_list_feature(xmins),
        'image/object/bbox/xmax': dataset_util.float_list_feature(xmaxs),
        'image/object/bbox/ymin': dataset_util.float_list_feature(ymins),
        'image/object/bbox/ymax': dataset_util.float_list_feature(ymaxs),
        'image/object/class/text': dataset_util.bytes_list_feature(classes_text),
        'image/object/class/label': dataset_util.int64_list_feature(classes),
    }))
    return tf_example


def main(_):
    writer = tf.python_io.TFRecordWriter(FLAGS.output_path)
    path = os.path.join(FLAGS.image_dir)
    examples = pd.read_csv(FLAGS.csv_input)
    grouped = split(examples, 'filename')
    for group in grouped:
        tf_example = create_tf_example(group, path)
        writer.write(tf_example.SerializeToString())

    writer.close()
    output_path = os.path.join(os.getcwd(), FLAGS.output_path)
    print('Successfully created the TFRecords: {}'.format(output_path))



if __name__ == '__main__':
    tf.app.run()
```
- **My Directory stucture looks something like this**
![Directory Structure](https://raw.githubusercontent.com/Monster-Gaming-Studios/hello/master/Capture.JPG)

**P.S.:-** If you want some additional information like how I generated the csv files, ask me and I will be glad to provide

**Comment by Monster-Gaming-Studios** [comment]
**Update:** Please do not ask me to check on stackoverflow on some where else. I tried looking everywhere.

**Comment by Monster-Gaming-Studios** [comment]
I solved the issue. It was my own mistake. In the parameter `--image_dir`,  I had given wrong path. I apologize for the inconvenience caused and I am closing the issue.
