### ISSUE TITLE
OwnedMultiDeviceIterator can cause an error on TPU pods

### ISSUE THREAD

**Issue by goldiegadde** [tensorflow/tensorflow#39038]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.2.0-rc4
- Python version: 
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture

**Describe the current behavior**
OwnedMultiDeviceIterator can cause an error on TPU pods.

the resulting stack trace :

gc/0 E0428 07:24:15.171094 132699 main app.py:658 Top-level exception:  could not parse rpc response
	 [[{{node iterator_13/_89}}]] [Op:__inference_minimize_49326]
Function call stack:
minimize
gc/0 E0428 07:24:15.172459 132699 main app.py:659 Traceback (most recent call last):
  File "/launcher_root/google3/third_party/py/absl/app.py", line 463, in run
    _run_main(main, args)
  File "/launcher_root/google3/third_party/py/absl/app.py", line 392, in _run_main
    sys.exit(main(argv))
  File "/launcher_root/google3/experimental/users/wendyshang/smarl/football/football/vtrace_main.py", line 153, in main
    env.create_environment(0), create_agent, create_optimizer)
  File "/launcher_root/google3/experimental/users/wendyshang/smarl/football/football/learner_object.py", line 574, in learner_loop
    minimize(it)
  File "/launcher_root/google3/third_party/tensorflow/python/eager/def_function.py", line 695, in __call__
    result = self._call(*args, **kwds)
  File "/launcher_root/google3/third_party/tensorflow/python/eager/def_function.py", line 760, in _call
    return self._concrete_stateful_fn._filtered_call(canon_args, canon_kwds)  # pylint: disable=protected-access
  File "/launcher_root/google3/third_party/tensorflow/python/eager/function.py", line 1904, in _filtered_call
    cancellation_manager=cancellation_manager)
  File "/launcher_root/google3/third_party/tensorflow/python/eager/function.py", line 1981, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/launcher_root/google3/third_party/tensorflow/python/eager/function.py", line 615, in call
    ctx=ctx)
  File "/launcher_root/google3/third_party/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
google3.third_party.tensorflow.python.framework.errors_impl.InternalError:  could not parse rpc response
	 [[{{node iterator_13/_89}}]] [Op:__inference_minimize_49326]
Function call stack:
minimize
**Describe the expected behavior**

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by geetachavan1** [comment]
The issue was fixed the by this [commit](https://github.com/tensorflow/tensorflow/commit/54fa7e441969792fa03f897cbd1fdbaf2e4d18e4)
