### ISSUE TITLE
Segmentation fault when converting a ReLU6 op to TFlite

### ISSUE THREAD

**Issue by wuhy08** [tensorflow/tensorflow#39040]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac OS
- TensorFlow installed from (source or binary): binary
- TensorFlow version (or github SHA if from source):  2.1

**Command used to run the converter or code if you’re using the Python API**
If possible, please share a link to Colab/Jupyter/any notebook.

```
import tensorflow as tf
from tensorflow.keras.layers import Input, Activation, Conv2D
from tensorflow.keras import Model
from tensorflow import lite

def model_relu6_only():
    input_ = Input(shape=[50, 50, 3])
    output = Activation(lambda x: tf.nn.relu6(x + 3) * 0.16667)(input_)
    return Model(inputs=input_, outputs=output)

def model_conv_relu6():
    input_ = Input(shape=[50, 50, 3])
    output = Conv2D(3, 3)(input_)
    output = Activation(lambda x: tf.nn.relu6(x + 3) * 0.16667)(output)
    return Model(inputs=input_, outputs=output)

def tflite_model_conversion(model, filename):
    converter = lite.TFLiteConverter.from_keras_model(model)
    tflite_model = converter.convert()
    with open(filename, "wb+") as f:
        f.write(tflite_model)

if __name__ == '__main__':

    model = model_conv_relu6()
    tflite_model_conversion(model, "conv_relu6.tflite")

    model = model_relu6_only()
    tflite_model_conversion(model, "relu6_only.tflite")
```

**The output from the converter invocation**

```
/Users/hw1000254892/miniconda3/envs/tf-2.1/bin/python /Users/hw1000254892/PycharmProjects/wd_obj_det/wd_obj_det/sandbox/relu_only_fail.py
2020-04-29 14:25:02.594509: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-04-29 14:25:02.630218: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fa3a268ade0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-04-29 14:25:02.630237: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-04-29 14:25:02.665720: I tensorflow/core/grappler/devices.cc:60] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0 (Note: TensorFlow was not compiled with CUDA support)
2020-04-29 14:25:02.665825: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2020-04-29 14:25:02.677242: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:814] Optimization results for grappler item: graph_to_optimize
2020-04-29 14:25:02.677259: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   function_optimizer: function_optimizer did nothing. time = 0.414ms.
2020-04-29 14:25:02.677263: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   function_optimizer: function_optimizer did nothing. time = 0.002ms.
2020-04-29 14:25:02.692790: I tensorflow/core/grappler/devices.cc:60] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0 (Note: TensorFlow was not compiled with CUDA support)
2020-04-29 14:25:02.692847: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2020-04-29 14:25:02.702864: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:814] Optimization results for grappler item: graph_to_optimize
2020-04-29 14:25:02.702880: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   constant_folding: Graph size after: 11 nodes (-2), 12 edges (-2), time = 7.837ms.
2020-04-29 14:25:02.702883: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   constant_folding: Graph size after: 11 nodes (0), 12 edges (0), time = 0.287ms.
2020-04-29 14:25:05.324556: I tensorflow/core/grappler/devices.cc:60] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0 (Note: TensorFlow was not compiled with CUDA support)
2020-04-29 14:25:05.324658: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2020-04-29 14:25:05.325629: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:814] Optimization results for grappler item: graph_to_optimize
2020-04-29 14:25:05.325640: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   function_optimizer: function_optimizer did nothing. time = 0.002ms.
2020-04-29 14:25:05.325646: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   function_optimizer: function_optimizer did nothing. time = 0ms.
2020-04-29 14:25:05.335367: I tensorflow/core/grappler/devices.cc:60] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0 (Note: TensorFlow was not compiled with CUDA support)
2020-04-29 14:25:05.335431: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2020-04-29 14:25:05.337047: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:814] Optimization results for grappler item: graph_to_optimize
2020-04-29 14:25:05.337060: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   constant_folding: Graph size after: 7 nodes (0), 6 edges (0), time = 0.322ms.
2020-04-29 14:25:05.337064: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   constant_folding: Graph size after: 7 nodes (0), 6 edges (0), time = 0.198ms.
Traceback (most recent call last):
  File "/Users/hw1000254892/PycharmProjects/wd_obj_det/wd_obj_det/sandbox/relu_only_fail.py", line 29, in <module>
    tflite_model_conversion(model, "relu6_only.tflite")
  File "/Users/hw1000254892/PycharmProjects/wd_obj_det/wd_obj_det/sandbox/relu_only_fail.py", line 19, in tflite_model_conversion
    tflite_model = converter.convert()
  File "/Users/hw1000254892/miniconda3/envs/tf-2.1/lib/python3.7/site-packages/tensorflow_core/lite/python/lite.py", line 464, in convert
    **converter_kwargs)
  File "/Users/hw1000254892/miniconda3/envs/tf-2.1/lib/python3.7/site-packages/tensorflow_core/lite/python/convert.py", line 457, in toco_convert_impl
    enable_mlir_converter=enable_mlir_converter)
  File "/Users/hw1000254892/miniconda3/envs/tf-2.1/lib/python3.7/site-packages/tensorflow_core/lite/python/convert.py", line 203, in toco_convert_protos
    raise ConverterError("See console for info.\n%s\n%s\n" % (stdout, stderr))
tensorflow.lite.python.convert.ConverterError: See console for info.
2020-04-29 14:25:08.186306: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 4 operators, 7 arrays (0 quantized)
2020-04-29 14:25:08.186470: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 4 operators, 7 arrays (0 quantized)
2020-04-29 14:25:08.186628: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 1: 2 operators, 5 arrays (0 quantized)
Fatal Python error: Segmentation fault

Current thread 0x000000010c7e2dc0 (most recent call first):
  File "/Users/hw1000254892/miniconda3/envs/tf-2.1/lib/python3.7/site-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 56 in execute
  File "/Users/hw1000254892/miniconda3/envs/tf-2.1/lib/python3.7/site-packages/absl/app.py", line 250 in _run_main
  File "/Users/hw1000254892/miniconda3/envs/tf-2.1/lib/python3.7/site-packages/absl/app.py", line 299 in run
  File "/Users/hw1000254892/miniconda3/envs/tf-2.1/lib/python3.7/site-packages/tensorflow_core/python/platform/app.py", line 40 in run
  File "/Users/hw1000254892/miniconda3/envs/tf-2.1/lib/python3.7/site-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 93 in main
  File "/Users/hw1000254892/miniconda3/envs/tf-2.1/bin/toco_from_protos", line 8 in <module>




Process finished with exit code 1

```

**Also, please include a link to the saved model or GraphDef**

```
N/A
```

**Failure details**
If the conversion is successful, but the generated model is wrong,
state what is wrong:
- Producing wrong results and/or decrease in accuracy
- Producing correct results, but the model is slower than expected (model generated from old converter)

Conversion failed

**RNN conversion support**
If converting TF RNN to TFLite fused RNN ops, please prefix [RNN] in the title.

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by Saduf2019** [comment]
@wuhy08 
I ran the code shared by on 2.1 and face a different error,please find the [gist here.](https://colab.sandbox.google.com/gist/Saduf2019/a6af2d4e4439870329d492ef5f4de9bd/untitled162.ipynb)
Whereas in  nightly there is no error faced [it works fine] , please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/19f50a7c073ede328a71f531e85e0741/untitled163.ipynb).

**Comment by wuhy08** [comment]
Hi @Saduf2019 

Thank for for the reply. It seems nightly version resolve this issue, although another issue related to optimization appears. I will open another issue about that.

Thank you.
