### ISSUE TITLE
when using "tensorboard --logdir", reported "ImportError: No module named '_markerlib"

### ISSUE THREAD

**Issue by jz1998** [tensorflow/tensorflow#39046]
when run the code
`cd  E:\python3\tensorflow1\Flower\log`
`tensorboard --logdir`
report error:
`Traceback (most recent call last):
  File "d:\appdatas\anaconda3\envs\tensorflow\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\appdatas\anaconda3\envs\tensorflow\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\AppDatas\Anaconda3\envs\tensorflow\Scripts\tensorboard.exe\__main__.py", line 7, in <module>
  File "d:\appdatas\anaconda3\envs\tensorflow\lib\site-packages\tensorboard\main.py", line 58, in run_main
    default.get_plugins() + default.get_dynamic_plugins(),
  File "d:\appdatas\anaconda3\envs\tensorflow\lib\site-packages\tensorboard\default.py", line 110, in get_dynamic_plugins
    for entry_point in pkg_resources.iter_entry_points('tensorboard_plugins')
  File "d:\appdatas\anaconda3\envs\tensorflow\lib\site-packages\tensorboard\default.py", line 110, in <listcomp>
    for entry_point in pkg_resources.iter_entry_points('tensorboard_plugins')
  File "e:\python3\whls\distribute-0.7.3\pkg_resources.py", line 2241, in load
    if require: self.require(env, installer)
  File "e:\python3\whls\distribute-0.7.3\pkg_resources.py", line 2254, in require
    working_set.resolve(self.dist.requires(self.extras),env,installer)))
  File "e:\python3\whls\distribute-0.7.3\pkg_resources.py", line 2471, in requires
    dm = self._dep_map
  File "e:\python3\whls\distribute-0.7.3\pkg_resources.py", line 2682, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "e:\python3\whls\distribute-0.7.3\pkg_resources.py", line 2699, in _compute_dependencies
    from _markerlib import compile as compile_marker`
`ImportError: No module named '_markerlib'`
bg: tf-gpu 1.5 win10 X64 anaconda

**Comment by amahendrakar** [comment]
Also, please check [this StackOverflow comment](https://stackoverflow.com/a/41162847) on a similar issue and let us know if it helps. Thanks!

**Comment by jz1998** [comment]
i find other way to solve this problem.
the complete code... just i run my train.py and save the log.
then i cd..... to my project index 
`cd E:\python3\tensorflow1\Flower`
`tensorboard --logdir=log`

so reported those error.

but when i deactivate this environment and activate another 
still run the two line code.
successful! 

maybe the installation of tensorflow exist some wrong.

These operation conducted in anaconda powershell prompt.
THX!

**Comment by amahendrakar** [comment]
@jz1998,
Is this still an issue? Please feel free to close the issue if resolved. Thanks!
