### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by maxlooo** [tensorflow/tensorflow#39079]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):  No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Windows Version	10.0.18362 Build 18362

- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:  NA
- TensorFlow installed from (source or binary):  pip3 install keras and tensorflow, confirmed using Anaconda Navigator 1.9.12
- TensorFlow version (use command below):  2.1.0 based on Anaconda, commands below for TF 1.0 and 2.0 both failed with same error: ImportError: DLL load failed: The specified module could not be found.
- Python version:   Python 3.7.6
- Bazel version (if compiling from source):  NA
- GCC/Compiler version (if compiling from source):  NA
- CUDA/cuDNN version:  CUDAtoolkit 10.0.130 and cuDNN 7.6.5 were installed later, but did not resolve the issue/bug
- GPU model and memory:  Intel(R) HD Graphics 620 with 1 GB RAM

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
from keras.models import Sequential

python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"
OR
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

caused the same problems, but starting with:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  **File "C:\Users\Max\anaconda3\lib\site-packages\tensorflow\__init__.py", line 101, in <module>**
    from tensorflow_core import *

Line 101 shows up below as well, and the rest of the error continues similarly: lines 40, 50, 44, 127, 49, 74, 58, 28, 24, 242, 342

Using TensorFlow backend.
ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

Traceback (most recent call last):
  File "C:\Users\Max\anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Max\anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Max\anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Max\anaconda3\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Max\anaconda3\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Max\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-9c5e0a19b646>", line 1, in <module>
    from keras.models import Sequential
  File "C:\Users\Max\anaconda3\lib\site-packages\keras\__init__.py", line 3, in <module>
    from . import utils
  File "C:\Users\Max\anaconda3\lib\site-packages\keras\utils\__init__.py", line 6, in <module>
    from . import conv_utils
  File "C:\Users\Max\anaconda3\lib\site-packages\keras\utils\conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "C:\Users\Max\anaconda3\lib\site-packages\keras\backend\__init__.py", line 1, in <module>
    from .load_backend import epsilon
  File "C:\Users\Max\anaconda3\lib\site-packages\keras\backend\load_backend.py", line 90, in <module>
    from .tensorflow_backend import *
  File "C:\Users\Max\anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf
  **File "C:\Users\Max\anaconda3\lib\site-packages\tensorflow\__init__.py", line 101, in <module>**
    from tensorflow_core import *
  File "C:\Users\Max\anaconda3\lib\site-packages\tensorflow_core\__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\Max\anaconda3\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\Users\Max\anaconda3\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "C:\Users\Max\anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\Max\anaconda3\lib\site-packages\tensorflow_core\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Max\anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Max\anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Max\anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Max\anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Max\anaconda3\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Max\anaconda3\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Describe the expected behavior**

I'm not sure.  I'm new to Python using Keras and Tensorflow.  

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

from keras.models import Sequential
OR
python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"
OR
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

[Error messages - LSTM RNN, Keras Tensorflow.txt](https://github.com/tensorflow/tensorflow/files/4564109/Error.messages.-.LSTM.RNN.Keras.Tensorflow.txt)

**Comment by oke-aditya** [comment]
This error occurs to many Users 

This occurs because you may not have Visual C++ Redistributable for Windows. Please download it.

Refer [here](https://www.tensorflow.org/install/pip#windows) to check if you have installed properly

Also, refer similar issues.
#36167 #36151 #36138 #36054 #36045 #36020 #36003 #35988 #35903 #35880 #35865 #35805 #35789 #35773 #35772 #35767 #35766 #35749 #35721 #35618 #35204
Thanks!

Please, check Your CPU/Python is on 32 bits?

Please, refer #36167 #38615 and see if it helps you. 

Thanks!

**Comment by ravikyram** [comment]
@maxlooo 

Solution should be downloading and installing visual studio 2015-2019 x86 and x64 from here:https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads.Thanks!

**Comment by mihaimaruseac** [comment]
Closing as low effort duplicate
