### ISSUE TITLE
Inconsistent Result between CPU build and GPU build

### ISSUE THREAD

**Issue by zzj0402** [tensorflow/tensorflow#39097]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):macOS Catalina 10.15.2 / Linux Ubuntu 16
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: MacBook Air (Retina, 13-inch, 2019)
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): v2.1.0-rc2-17-ge5bf8de410 2.1.0
- Python version: 3.6.6
- Bazel version (if compiling from source): 
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:  10.1
- GPU model and memory: RTX 2080 ti 11GB x4

**Describe the current behavior**
Test runs on laptop, 
```
WARNING:tensorflow:From /Users/zijingzhang/Library/Python/3.6/lib/python/site-packages/tensorflow_core/python/ops/resource_variable_ops.py:1786: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
WARNING:tensorflow:From /Users/zijingzhang/Library/Python/3.6/lib/python/site-packages/tensorflow_core/python/ops/resource_variable_ops.py:1786: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
Train for 3 steps, validate for 3 steps

1/3 [=========>....................] - ETA: 4s - loss: 0.6949 - accuracy: 0.5000
3/3 [==============================] - 3s 961ms/step - loss: 0.6948 - accuracy: 0.5000 - val_loss: 0.6943 - val_accuracy: 0.5000
ok

----------------------------------------------------------------------
Ran 1 test in 282.183s

OK
```
but when deployed on server-GPU/CI, it shows error:
```
venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py:1657 _create_c_op
         raise ValueError(str(e))
     ValueError: slice index 0 of dimension 0 out of bounds. for '{{node strided_slice}} = StridedSlice[Index=DT_INT32, T=DT_INT32, begin_mask=0, ellipsis_mask=0, end_mask=0, new_axis_mask=0, shrink_axis_mask=1](Shape, strided_slice/stack, strided_slice/stack_1, strided_slice/stack_2)' with input shapes: [0], [1], [1], [1] and with computed input tensors: input[1] = <0>, input[2] = <1>, input[3] = <1>.
```
**Describe the expected behavior**
Consistent result between laptop and server.
**Standalone code to reproduce the issue**
### Setup
./data/sample.csv
```csv
id,comment_text,lang,toxic
0,"Este usuario ni siquiera llega al rango de    hereje   . Por lo tanto debería ser quemado en la barbacoa para purificar su alma y nuestro aparato digestivo mediante su ingestión.    Skipe linkin 22px   Honor, valor, leltad.      17:48 13 mar 2008 (UTC)",es,0
1,"Il testo di questa voce pare esser scopiazzato direttamente da qui. Immagino possano esserci problemi di copyright, nel fare cio .",it,0
2,"Vale. Sólo expongo mi pasado. Todo tiempo pasado fue mejor, ni mucho menos, yo no quisiera retroceder 31 años a nivel particular. Las volveria a pasar putas.Fernando ",es,1
3,"Bu maddenin alt başlığı olarak  uluslararası ilişkiler  ile konuyu sürdürmek ile ilgili tereddütlerim var.Önerim siyaset bilimi ana başlığından sonra siyasal yaşam ve toplum, siyasal güç, siyasal çatışma, siyasal gruplar, çağdaş ideolojiler, din, siyasal değişme, kamuoyu, propaganda ve siyasal katılma temelinde çoğulcu siyasal sistemler.Bu alt başlıkların daha anlamlı olacağı kanaatindeyim.",tr,0
4,"Belçika nın şehirlerinin yanında ilçe ve beldelerini yaparken sanırım Portekizi örnek alacaksın. Ben de uzak gelecekte(2-3 yıl) bu tip şeyler düşünüyorum. Tabii futbol maddelerinin hakkından geldikten sonra..    daha önce mesajlarınızı görmüştüm, hatta anon bölümünü bizzat kullanıyordum   sözünü anlamadım??  tanışmak bugüneymiş gibi bir şey eklemeyi düşündüm ama vazgeçtim. orayı da silmeyi unuttum. boşverin Kıdemli   +    ",tr,0
5,"güzel, zaten kaynaklandırması zor subjektif kategoriler bunlar. bazı maddelerden çıkartmak, kiminden çıkartıp kiminde bırakmak, çıkartılanları yerine iade etmek yerine Kategori:Milletlere karşı ırkçı duygular dakilerin tamamına el atmak gerekiyor.    kibele    ",tr,0
6,"No es mala idea. De hecho, yo estaba pensando descolgarme ya del reto mensual, pero esto vuelve a ilusionarme. El problema es que contabilizar los artículos a mano es muy tedioso, así que habría que disponer de una herramienta tipo escaladix que lo hiciera automáticamente. Y tampoco estaría mal disponer de resultados parciales cada tres meses o similar. Yo me apunto ) . Saludos de ",es,0
7,"Kod hatalarını düzeltmişsiniz,elinize sağlık çok teşekkürler.Önceki sürümleri araştırdım.13 Haziran 2010 da Kullanıcı:Türk Süvarisi nin yaptığı şu değişikliğe kadar 107 kaynak var ve benim görebildiğim kadarıyla kaynaklarda hata yok.Türk Süvarisi nin değişikliğinden sonra kaynak sayısı 111 e çıkıyor ve kaynak hataları oluşuyor.Bana Türk Süvarisi hatalı bir şekilde yeni kaynaklar eklemiş gibi geldi.Siz ne dersiniz?Yardımcı olursanız çok sevinirim.Bu arada İran ı KM adayı göstermeyi düşünüyorum ve bu nedenle maddeyi düzenlemeye çalışıyorum.Vikipedi:Madde incelemesi/İran/arşiv1 de siz de görüşlerinizi belirtirseniz maddenin gelişimi adına katkısı olur diye düşünüyorum.İngiltere Portalı nda sizin ve diğer vikipedistlerin bahsettiği yorumsal ifadeleri ve yazım hatalarını düzelttim.İsterseniz portala tekrar göz atın.Sevgiler, iyivikiler   Âkhilleus       mesaj    ",tr,0
```
#### requirements.txt
```txt
tensorflow-hub
tensorflow_text>=2.0.0rc0
```

#### USE.py
```
import tensorflow_hub as hub
import tensorflow_text

module_url = 'https://tfhub.dev/google/universal-sentence-encoder-multilingual/3'


def embed_text(input):
    model = hub.load(module_url)
    return model(input)

```

#### Model.py
```
import tensorflow as tf


def build():
    inputs = tf.keras.Input(shape=(512,), name="use_input")
    hl1 = tf.keras.layers.Dense(
        963, activation=tf.nn.relu, name='hidden_layer_1')(inputs)
    hl2 = tf.keras.layers.Dense(
        369, activation=tf.nn.relu,  name='hidden_layer_2')(hl1)
    hl3 = tf.keras.layers.Dense(
        69, activation=tf.nn.relu,  name='hidden_layer_3')(hl2)
    hl4 = tf.keras.layers.Dense(
        3, activation=tf.nn.relu,  name='hidden_layer_4')(hl3)
    outputs = tf.keras.layers.Dense(
        2, activation=tf.nn.softmax, name='prediction')(hl4)
    model = tf.keras.Model(inputs=inputs, outputs=outputs)
    return model

```
#### DataProcessing.py
```
import functools

import numpy as np
import tensorflow as tf
import USE

LABEL_COLUMN = 'toxic'
LABELS = [0, 1]


def get_dataset(file_path, batch_size=3, **kwargs):
    dataset = tf.data.experimental.make_csv_dataset(
        file_path,
        # Artificially small to make examples easier to show.
        batch_size=batch_size,
        label_name=LABEL_COLUMN,
        na_value="?",
        num_epochs=1,
        ignore_errors=True,
        **kwargs)
    return dataset


def show_batch(dataset):
    for batch, label in dataset.take(1):
        for key, value in batch.items():
            print(key)
            print(value)
            # print("{:20s}: {}".format(key, value.numpy()))
        print(label)


def embed_batch(dataset):
    embeddings = []
    for batch, label in dataset.take(1):
        for key, value in batch.items():
            # print(key)
            # print(value)
            for comment in value:
                # print(comment)
                emb = USE.embed_text(comment)
                emb = emb.numpy()
                # print(emb)
                embeddings.append(emb)

            # print("{:20s}: {}".format(key, value.numpy()))
        # print(label)
        # print(embeddings)
        # print(dataset)
        return embeddings, label

# show_batch(raw_train_data)
# print(filtered_dataset)
# show_batch(filtered_dataset)

```
#### Training.py

```python
import Model
import DataProcessing
import tensorflow as tf


def fit(training_file_path='./data/sample.csv', validation_file_path="./data/sample.csv", batch_size=3,
        SELECT_COLUMNS=['toxic', 'comment_text'], model_saved='test'):
    training_dataset = DataProcessing.get_dataset(
        training_file_path, select_columns=SELECT_COLUMNS, batch_size=batch_size)
    validation_dataset = DataProcessing.get_dataset(
        training_file_path, select_columns=SELECT_COLUMNS, batch_size=batch_size)
    useEmbedding, labels = DataProcessing.embed_batch(training_dataset)
    dataset = tf.data.Dataset.from_tensor_slices((useEmbedding, labels))
    useEmbedding, labels = DataProcessing.embed_batch(validation_dataset)
    validation = tf.data.Dataset.from_tensor_slices((useEmbedding, labels))
    model = Model.build()
    model.summary()
    model.compile(tf.keras.optimizers.Adam(lr=1e-5), loss='binary_crossentropy',
                  metrics=['accuracy'])
    model.save('./model/'+model_saved)
    return model.fit(dataset, validation_data=validation)

Training.fit()
```
#### Command
```
pip install -r requirements.txt && python Training.py
```
**Other info / logs** 

```
======================================================================
 ERROR: test_fit (test_training.TestTraining)
 ----------------------------------------------------------------------
 Traceback (most recent call last):
   File "/builds/zzj0402/project/test/test_training.py", line 8, in test_fit
     self.assertTrue(Training.fit(), "Training should run.")
   File "/builds/zzj0402/project/Training.py", line 21, in fit
     return model.fit(dataset, validation_data=validation)
   File "/builds/zzj0402/project/venv/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 66, in _method_wrapper
     return method(self, *args, **kwargs)
   File "/builds/zzj0402/project/venv/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 848, in fit
     tmp_logs = train_function(iterator)
   File "/builds/zzj0402/project/venv/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 580, in __call__
     result = self._call(*args, **kwds)
   File "/builds/zzj0402/project/venv/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 627, in _call
     self._initialize(args, kwds, add_initializers_to=initializers)
   File "/builds/zzj0402/project/venv/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 506, in _initialize
     *args, **kwds))
   File "/builds/zzj0402/project/venv/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 2446, in _get_concrete_function_internal_garbage_collected
     graph_function, _, _ = self._maybe_define_function(args, kwargs)
   File "/builds/zzj0402/project/venv/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 2777, in _maybe_define_function
     graph_function = self._create_graph_function(args, kwargs)
   File "/builds/zzj0402/project/venv/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 2667, in _create_graph_function
     capture_by_value=self._capture_by_value),
   File "/builds/zzj0402/project/venv/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py", line 981, in func_graph_from_py_func
     func_outputs = python_func(*func_args, **func_kwargs)
   File "/builds/zzj0402/project/venv/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 441, in wrapped_fn
     return weak_wrapped_fn().__wrapped__(*args, **kwds)
   File "/builds/zzj0402/project/venv/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py", line 968, in wrapper
     raise e.ag_error_metadata.to_exception(e)
 ValueError: in user code:
     /builds/zzj0402/project/venv/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py:571 train_function  *
         outputs = self.distribute_strategy.run(
     /builds/zzj0402/project/venv/lib/python3.6/site-packages/tensorflow/python/distribute/distribute_lib.py:951 run  **
         return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
     /builds/zzj0402/project/venv/lib/python3.6/site-packages/tensorflow/python/distribute/distribute_lib.py:2290 call_for_each_replica
         return self._call_for_each_replica(fn, args, kwargs)
     /builds/zzj0402/project/venv/lib/python3.6/site-packages/tensorflow/python/distribute/distribute_lib.py:2649 _call_for_each_replica
         return fn(*args, **kwargs)
     /builds/zzj0402/project/venv/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py:533 train_step  **
         y, y_pred, sample_weight, regularization_losses=self.losses)
     /builds/zzj0402/project/venv/lib/python3.6/site-packages/tensorflow/python/keras/engine/compile_utils.py:213 __call__
         batch_dim = array_ops.shape(y_t)[0]
     /builds/zzj0402/project/venv/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py:984 _slice_helper
         name=name)
     /builds/zzj0402/project/venv/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py:1150 strided_slice
         shrink_axis_mask=shrink_axis_mask)
     /builds/zzj0402/project/venv/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py:10179 strided_slice
         shrink_axis_mask=shrink_axis_mask, name=name)
     /builds/zzj0402/project/venv/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py:744 _apply_op_helper
         attrs=attr_protos, op_def=op_def)
     /builds/zzj0402/project/venv/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py:595 _create_op_internal
         compute_device)
     /builds/zzj0402/project/venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py:3327 _create_op_internal
         op_def=op_def)
     /builds/zzj0402/project/venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py:1817 __init__
         control_input_ops, op_def)
     /builds/zzj0402/project/venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py:1657 _create_c_op
         raise ValueError(str(e))
     ValueError: slice index 0 of dimension 0 out of bounds. for '{{node strided_slice}} = StridedSlice[Index=DT_INT32, T=DT_INT32, begin_mask=0, ellipsis_mask=0, end_mask=0, new_axis_mask=0, shrink_axis_mask=1](Shape, strided_slice/stack, strided_slice/stack_1, strided_slice/stack_2)' with input shapes: [0], [1], [1], [1] and with computed input tensors: input[1] = <0>, input[2] = <1>, input[3] = <1>.
```

**Comment by Saduf2019** [comment]
@zzj0402 
I ran the code shared it seems the code shared is incomplete, please find [the gist](https://colab.sandbox.google.com/gist/Saduf2019/f00c66cf7fd797ba9081670504f9b4c6/39052.ipynb) of errors faced.
Please let us know if this is a "hub" related issue,  if not please provide omplete code such that we could replicate the issue faced, if possible share a colab gist so we could analyse the error faced and help.Thanks!

**Comment by zzj0402** [comment]
> @zzj0402
> I ran the code shared it seems the code shared is incomplete, please find [the gist](https://colab.sandbox.google.com/gist/Saduf2019/f00c66cf7fd797ba9081670504f9b4c6/39052.ipynb) of errors faced.
> Please let us know if this is a "hub" related issue, if not please provide omplete code such that we could replicate the issue faced, if possible share a colab gist so we could analyse the error faced and help.Thanks!

The code is complete. You didn't install dependencies properly and you are supposed to run locally with separate .py files.

**Comment by gowthamkpr** [comment]
@zzj0402 Did you try with tensorflow 2.2.0-rc3? Are you facing the same issue?

**Comment by zzj0402** [comment]
> @zzj0402 Did you try with tensorflow 2.2.0-rc3? Are you facing the same issue?

I haven't tried. I used Kaggle kernels instead. I am going to close this issue since I don't need work on this locally anymore.
