### ISSUE TITLE
Tensorflow lite conversion problem. Zero dimensions output node after conversion

### ISSUE THREAD

**Issue by farmaker47** [tensorflow/tensorflow#39176]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colaboratory
- TensorFlow installed from (source or binary): Colaboratory default
- TensorFlow version (or github SHA if from source):  2.2.0-rc3, Keras version: 2.3.0-tf

**Command used to run the converter or code if you’re using the Python API**
If possible, please share a link to Colab/Jupyter/any notebook.

```
tflite_model = tf.keras.models.load_model('saved_model/my_model')
converter = tf.lite.TFLiteConverter.from_keras_model(tflite_model)
tflite_save = converter.convert()
open("greek_smart_reply_model.tflite", "wb").write(tflite_save)
```
**the output from keras model**

```
print(new_model.get_input_shape_at(0))
print(new_model)
for node in model.outputs:
  print(node)

(None, 40)
<tensorflow.python.keras.engine.sequential.Sequential object at 0x7f21efbcb240>
Tensor("dense/Identity:0", shape=(None, 3), dtype=float32)

```

**The output from the converter invocation**

```
interpreter = tf.lite.Interpreter('greek_smart_reply_model.tflite')
interpreter.allocate_tensors()
interpreter.get_tensor_details()

Output node:
{'dtype': numpy.float32,
  'index': 34,
  'name': 'Identity',
  'quantization': (0.0, 0),
  'quantization_parameters': {'quantized_dimension': 0,
   'scales': array([], dtype=float32),
   'zero_points': array([], dtype=int32)},
  'shape': array([], dtype=int32),
  'shape_signature': array([], dtype=int32),
  'sparsity_parameters': {}}

-----------Shape is empty array and should be [1,3]
```

**Also, please include a link to the saved model or GraphDef**

```
https://drive.google.com/open?id=1cAUPhmL4OsGUStsLcdFxYoX6c4L7u5aE
```

**Failure details**
If the conversion is successful, but the generated model is wrong,
state what is wrong:
- Producing wrong results: Despite the fact that keras model predicts fine in colaboratory and has exactly output [1,3] when I convert it in .tflite the output node has zero dimensions:

Output node:
'dtype': numpy.float32,
  'index': 34,
  'name': 'Identity',
  'quantization': (0.0, 0),
  'quantization_parameters': {'quantized_dimension': 0,
   'scales': array([], dtype=float32),
   'zero_points': array([], dtype=int32)},
  'shape': array([], dtype=int32),
  'shape_signature': array([], dtype=int32),
  'sparsity_parameters': {}}

AND the same is stated when I load it inside android application:
2020-05-05 09:45:16.036 28527-28748/com.george.fs_korinthias E/INPUT_TENSOR_WHOLE: [1, 40]
2020-05-05 09:45:16.036 28527-28748/com.george.fs_korinthias E/INPUT_DATA_TYPE: FLOAT32
2020-05-05 09:45:16.037 28527-28748/com.george.fs_korinthias E/OUTPUT_TENSOR_SHAPE: []
2020-05-05 09:45:16.037 28527-28748/com.george.fs_korinthias E/OUTPUT_DATA_TYPE: FLOAT32

When I state output of interpreter as [1,3] android gives:

2020-05-05 09:55:07.570 29331-29421/com.george.fs_korinthias E/INPUT_TENSOR_WHOLE: [1, 40]
2020-05-05 09:55:07.571 29331-29421/com.george.fs_korinthias E/INPUT_DATA_TYPE: FLOAT32
2020-05-05 09:55:07.571 29331-29421/com.george.fs_korinthias E/OUTPUT_TENSOR_SHAPE: []
2020-05-05 09:55:07.571 29331-29421/com.george.fs_korinthias E/OUTPUT_DATA_TYPE: FLOAT32
2020-05-05 09:55:07.571 29331-29421/com.george.fs_korinthias E/DigitClassifier: Initialized TFLite interpreter.
2020-05-05 09:55:07.989 29331-29331/com.george.fs_korinthias E/MainActivity_classifier: Error to setting up smart reply classifier.
    java.lang.IllegalArgumentException: Cannot copy between a TensorFlowLite tensor with shape [] and a Java object with shape [1, 3].

Thank you in advance!!!!!

**RNN conversion support**
If converting TF RNN to TFLite fused RNN ops, please prefix [RNN] in the title.

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.2.0-rc4 and TF-nightly. Please find the gist [here](https://colab.research.google.com/gist/amahendrakar/794a8c61cc7a4ea4a34fee5113a0c00b/39176.ipynb). Thanks!

**Comment by farmaker47** [comment]
Model summary:

```

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
embedding (Embedding)        (None, 40, 20)            245560    
_________________________________________________________________
lstm (LSTM)                  (None, 64)                21760     
_________________________________________________________________
dense (Dense)                (None, 3)                 195       
=================================================================
Total params: 267,515
Trainable params: 267,515
Non-trainable params: 0
_________________________________________________________________
None

```

**Comment by jvishnuvardhan** [comment]
@farmaker47 I think this was resolved in recent `tf-nightly`. It printed correct `input_details` and `output_details` as expected and are shown below. Please check [gist here](https://colab.research.google.com/gist/jvishnuvardhan/4a8cb8a660c7289ef6058e4a740694ff/39176.ipynb). 

### `input_details` from `input_details = interpreter.get_input_details()`
`[{'name': 'embedding_input', 'index': 0, 'shape': array([ 1, 40], dtype=int32), 'shape_signature': array([-1, 40], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}]`

### output_details` from `output_details = interpreter.get_output_details()`
`[{'name': 'Identity', 'index': 38, 'shape': array([1, 3], dtype=int32), 'shape_signature': array([-1,  3], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}]`

### output for `interpreter.get_tensor_details()` is as follows
```
[{'dtype': numpy.float32,
  'index': 0,
  'name': 'embedding_input',
  'quantization': (0.0, 0),
  'quantization_parameters': {'quantized_dimension': 0,
   'scales': array([], dtype=float32),
   'zero_points': array([], dtype=int32)},
  'shape': array([ 1, 40], dtype=int32),
  'shape_signature': array([-1, 40], dtype=int32),
  'sparsity_parameters': {}},
 {'dtype': numpy.float32,
  'index': 1,
  'name': 'sequential/dense/BiasAdd/ReadVariableOp/resource',
  'quantization': (0.0, 0),
  'quantization_parameters': {'quantized_dimension': 0,
   'scales': array([], dtype=float32),
   'zero_points': array([], dtype=int32)},
  'shape': array([3], dtype=int32),
  'shape_signature': array([3], dtype=int32),
  'sparsity_parameters': {}},
 {'dtype': numpy.float32,
  'index': 2,
  'name': 'sequential/embedding/embedding_lookup/7264',
  'quantization': (0.0, 0),
  'quantization_parameters': {'quantized_dimension': 0,
   'scales': array([], dtype=float32),
   'zero_points': array([], dtype=int32)},
  'shape': array([12278,    20], dtype=int32),
  'shape_signature': array([12278,    20], dtype=int32),
  'sparsity_parameters': {}},
 {'dtype': numpy.int32,
  'index': 3,
  'name': 'transpose/perm;sequential/lstm/PartitionedCall/transpose/perm',
  'quantization': (0.0, 0),
  'quantization_parameters': {'quantized_dimension': 0,
   'scales': array([], dtype=float32),
   'zero_points': array([], dtype=int32)},
  'shape': array([3], dtype=int32),
  'shape_signature': array([3], dtype=int32),
  'sparsity_parameters': {}},
 {'dtype': numpy.float32,
  'index': 4,
  'name': 'sequential/lstm/Read_2/ReadVariableOp/resource',
  'quantization': (0.0, 0),
  'quantization_parameters': {'quantized_dimension': 0,
   'scales': array([], dtype=float32),
   'zero_points': array([], dtype=int32)},
  'shape': array([256], dtype=int32),
  'shape_signature': array([256], dtype=int32),
  'sparsity_parameters': {}},
 {'dtype': numpy.int32,
  'index': 5,
  'name': 'sequential/lstm/zeros/packed/1',
  'quantization': (0.0, 0),
  'quantization_parameters': {'quantized_dimension': 0,
   'scales': array([], dtype=float32),
   'zero_points': array([], dtype=int32)},
  'shape': array([], dtype=int32),
  'shape_signature': array([], dtype=int32),
  'sparsity_parameters': {}},
 {'dtype': numpy.int32,
  'index': 6,
  'name': 'TensorArrayV2_1;sequential/lstm/PartitionedCall/TensorArrayV2_1',
  'quantization': (0.0, 0),
  'quantization_parameters': {'quantized_dimension': 0,
   'scales': array([], dtype=float32),
   'zero_points': array([], dtype=int32)},
  'shape': array([2], dtype=int32),
  'shape_signature': array([2], dtype=int32),
  'sparsity_parameters': {}},
 {'dtype': numpy.int32,
  'index': 7,
  'name': 'TensorArrayV2_1;sequential/lstm/PartitionedCall/TensorArrayV2_11',
  'quantization': (0.0, 0),
  'quantization_parameters': {'quantized_dimension': 0,
   'scales': array([], dtype=float32),
   'zero_points': array([], dtype=int32)},
  'shape': array([], dtype=int32),
  'shape_signature': array([], dtype=int32),
  'sparsity_parameters': {}},
 {'dtype': numpy.float32,
  'index': 8,
  'name': 'TensorArrayV2_1;sequential/lstm/PartitionedCall/TensorArrayV2_12',
  'quantization': (0.0, 0),
  'quantization_parameters': {'quantized_dimension': 0,
   'scales': array([], dtype=float32),
   'zero_points': array([], dtype=int32)},
  'shape': array([], dtype=int32),
  'shape_signature': array([], dtype=int32),
  'sparsity_parameters': {}},
 {'dtype': numpy.float32,
  'index': 9,
  'name': 'sequential/dense/MatMul',
  'quantization': (0.0, 0),
  'quantization_parameters': {'quantized_dimension': 0,
   'scales': array([], dtype=float32),
   'zero_points': array([], dtype=int32)},
  'shape': array([ 3, 64], dtype=int32),
  'shape_signature': array([ 3, 64], dtype=int32),
  'sparsity_parameters': {}},
 {'dtype': numpy.int32,
  'index': 10,
  'name': 'sequential/lstm/strided_slice',
  'quantization': (0.0, 0),
  'quantization_parameters': {'quantized_dimension': 0,
   'scales': array([], dtype=float32),
   'zero_points': array([], dtype=int32)},
  'shape': array([1], dtype=int32),
  'shape_signature': array([1], dtype=int32),
  'sparsity_parameters': {}},
 {'dtype': numpy.int32,
  'index': 11,
  'name': 'sequential/lstm/strided_slice1',
  'quantization': (0.0, 0),
  'quantization_parameters': {'quantized_dimension': 0,
   'scales': array([], dtype=float32),
   'zero_points': array([], dtype=int32)},
  'shape': array([1], dtype=int32),
  'shape_signature': array([1], dtype=int32),
  'sparsity_parameters': {}},
 {'dtype': numpy.int32,
  'index': 12,
  'name': 'strided_slice_2;sequential/lstm/PartitionedCall/strided_slice_2',
  'quantization': (0.0, 0),
  'quantization_parameters': {'quantized_dimension': 0,
   'scales': array([], dtype=float32),
   'zero_points': array([], dtype=int32)},
  'shape': array([3], dtype=int32),
  'shape_signature': array([3], dtype=int32),
  'sparsity_parameters': {}},
 {'dtype': numpy.int32,
  'index': 13,
  'name': 'strided_slice_2;sequential/lstm/PartitionedCall/strided_slice_21',
  'quantization': (0.0, 0),
  'quantization_parameters': {'quantized_dimension': 0,
   'scales': array([], dtype=float32),
   'zero_points': array([], dtype=int32)},
  'shape': array([3], dtype=int32),
  'shape_signature': array([3], dtype=int32),
  'sparsity_parameters': {}},
 {'dtype': numpy.int32,
  'index': 14,
  'name': 'strided_slice_2;sequential/lstm/PartitionedCall/strided_slice_22',
  'quantization': (0.0, 0),
  'quantization_parameters': {'quantized_dimension': 0,
   'scales': array([], dtype=float32),
   'zero_points': array([], dtype=int32)},
  'shape': array([3], dtype=int32),
  'shape_signature': array([3], dtype=int32),
  'sparsity_parameters': {}},
 {'dtype': numpy.int32,
  'index': 15,
  'name': 'sequential/embedding/Cast',
  'quantization': (0.0, 0),
  'quantization_parameters': {'quantized_dimension': 0,
   'scales': array([], dtype=float32),
   'zero_points': array([], dtype=int32)},
  'shape': array([ 1, 40], dtype=int32),
  'shape_signature': array([-1, 40], dtype=int32),
  'sparsity_parameters': {}},
 {'dtype': numpy.float32,
  'index': 16,
  'name': 'sequential/embedding/embedding_lookup;TensorArrayV2_1;sequential/lstm/PartitionedCall/TensorArrayV2_1',
  'quantization': (0.0, 0),
  'quantization_parameters': {'quantized_dimension': 0,
   'scales': array([], dtype=float32),
   'zero_points': array([], dtype=int32)},
  'shape': array([ 1, 40, 20], dtype=int32),
  'shape_signature': array([-1, 40, 20], dtype=int32),
  'sparsity_parameters': {}},
 {'dtype': numpy.int32,
  'index': 17,
  'name': 'sequential/lstm/Shape',
  'quantization': (0.0, 0),
  'quantization_parameters': {'quantized_dimension': 0,
   'scales': array([], dtype=float32),
   'zero_points': array([], dtype=int32)},
  'shape': array([3], dtype=int32),
  'shape_signature': array([3], dtype=int32),
  'sparsity_parameters': {}},
 {'dtype': numpy.float32,
  'index': 18,
  'name': 'transpose;sequential/lstm/PartitionedCall/transpose',
  'quantization': (0.0, 0),
  'quantization_parameters': {'quantized_dimension': 0,
   'scales': array([], dtype=float32),
   'zero_points': array([], dtype=int32)},
  'shape': array([40,  1, 20], dtype=int32),
  'shape_signature': array([40, -1, 20], dtype=int32),
  'sparsity_parameters': {}},
 {'dtype': numpy.int32,
  'index': 19,
  'name': 'Shape;sequential/lstm/PartitionedCall/Shape',
  'quantization': (0.0, 0),
  'quantization_parameters': {'quantized_dimension': 0,
   'scales': array([], dtype=float32),
   'zero_points': array([], dtype=int32)},
  'shape': array([3], dtype=int32),
  'shape_signature': array([3], dtype=int32),
  'sparsity_parameters': {}},
 {'dtype': numpy.int32,
  'index': 20,
  'name': 'strided_slice;sequential/lstm/PartitionedCall/strided_slice',
  'quantization': (0.0, 0),
  'quantization_parameters': {'quantized_dimension': 0,
   'scales': array([], dtype=float32),
   'zero_points': array([], dtype=int32)},
  'shape': array([], dtype=int32),
  'shape_signature': array([], dtype=int32),
  'sparsity_parameters': {}},
 {'dtype': numpy.int32,
  'index': 21,
  'name': 'TensorArrayV2_1;sequential/lstm/PartitionedCall/TensorArrayV2_13',
  'quantization': (0.0, 0),
  'quantization_parameters': {'quantized_dimension': 0,
   'scales': array([], dtype=float32),
   'zero_points': array([], dtype=int32)},
  'shape': array([1], dtype=int32),
  'shape_signature': array([1], dtype=int32),
  'sparsity_parameters': {}},
 {'dtype': numpy.int32,
  'index': 22,
  'name': 'TensorArrayV2_1;sequential/lstm/PartitionedCall/TensorArrayV2_14',
  'quantization': (0.0, 0),
  'quantization_parameters': {'quantized_dimension': 0,
   'scales': array([], dtype=float32),
   'zero_points': array([], dtype=int32)},
  'shape': array([3], dtype=int32),
  'shape_signature': array([3], dtype=int32),
  'sparsity_parameters': {}},
 {'dtype': numpy.float32,
  'index': 23,
  'name': 'TensorArrayV2_1;sequential/lstm/PartitionedCall/TensorArrayV2_15',
  'quantization': (0.0, 0),
  'quantization_parameters': {'quantized_dimension': 0,
   'scales': array([], dtype=float32),
   'zero_points': array([], dtype=int32)},
  'shape': array([1, 1, 1], dtype=int32),
  'shape_signature': array([-1, -1, -1], dtype=int32),
  'sparsity_parameters': {}},
 {'dtype': numpy.int32,
  'index': 24,
  'name': 'sequential/lstm/strided_slice2',
  'quantization': (0.0, 0),
  'quantization_parameters': {'quantized_dimension': 0,
   'scales': array([], dtype=float32),
   'zero_points': array([], dtype=int32)},
  'shape': array([], dtype=int32),
  'shape_signature': array([], dtype=int32),
  'sparsity_parameters': {}},
 {'dtype': numpy.int32,
  'index': 25,
  'name': 'sequential/lstm/zeros/packed',
  'quantization': (0.0, 0),
  'quantization_parameters': {'quantized_dimension': 0,
   'scales': array([], dtype=float32),
   'zero_points': array([], dtype=int32)},
  'shape': array([2], dtype=int32),
  'shape_signature': array([2], dtype=int32),
  'sparsity_parameters': {}},
 {'dtype': numpy.float32,
  'index': 26,
  'name': 'sequential/lstm/zeros',
  'quantization': (0.0, 0),
  'quantization_parameters': {'quantized_dimension': 0,
   'scales': array([], dtype=float32),
   'zero_points': array([], dtype=int32)},
  'shape': array([ 1, 64], dtype=int32),
  'shape_signature': array([-1, 64], dtype=int32),
  'sparsity_parameters': {}},
 {'dtype': numpy.int32,
  'index': 27,
  'name': 'while;sequential/lstm/PartitionedCall/while',
  'quantization': (0.0, 0),
  'quantization_parameters': {'quantized_dimension': 0,
   'scales': array([], dtype=float32),
   'zero_points': array([], dtype=int32)},
  'shape': array([], dtype=int32),
  'shape_signature': array([], dtype=int32),
  'sparsity_parameters': {}},
 {'dtype': numpy.int32,
  'index': 28,
  'name': 'while;sequential/lstm/PartitionedCall/while1',
  'quantization': (0.0, 0),
  'quantization_parameters': {'quantized_dimension': 0,
   'scales': array([], dtype=float32),
   'zero_points': array([], dtype=int32)},
  'shape': array([], dtype=int32),
  'shape_signature': array([], dtype=int32),
  'sparsity_parameters': {}},
 {'dtype': numpy.float32,
  'index': 29,
  'name': 'while;sequential/lstm/PartitionedCall/while2',
  'quantization': (0.0, 0),
  'quantization_parameters': {'quantized_dimension': 0,
   'scales': array([], dtype=float32),
   'zero_points': array([], dtype=int32)},
  'shape': array([1, 1, 1], dtype=int32),
  'shape_signature': array([-1, -1, -1], dtype=int32),
  'sparsity_parameters': {}},
 {'dtype': numpy.float32,
  'index': 30,
  'name': 'while;sequential/lstm/PartitionedCall/while3',
  'quantization': (0.0, 0),
  'quantization_parameters': {'quantized_dimension': 0,
   'scales': array([], dtype=float32),
   'zero_points': array([], dtype=int32)},
  'shape': array([ 1, 64], dtype=int32),
  'shape_signature': array([-1, 64], dtype=int32),
  'sparsity_parameters': {}},
 {'dtype': numpy.float32,
  'index': 31,
  'name': 'while;sequential/lstm/PartitionedCall/while4',
  'quantization': (0.0, 0),
  'quantization_parameters': {'quantized_dimension': 0,
   'scales': array([], dtype=float32),
   'zero_points': array([], dtype=int32)},
  'shape': array([ 1, 64], dtype=int32),
  'shape_signature': array([-1, 64], dtype=int32),
  'sparsity_parameters': {}},
 {'dtype': numpy.int32,
  'index': 32,
  'name': 'while;sequential/lstm/PartitionedCall/while5',
  'quantization': (0.0, 0),
  'quantization_parameters': {'quantized_dimension': 0,
   'scales': array([], dtype=float32),
   'zero_points': array([], dtype=int32)},
  'shape': array([], dtype=int32),
  'shape_signature': array([], dtype=int32),
  'sparsity_parameters': {}},
 {'dtype': numpy.float32,
  'index': 33,
  'name': 'while;sequential/lstm/PartitionedCall/while6',
  'quantization': (0.0, 0),
  'quantization_parameters': {'quantized_dimension': 0,
   'scales': array([], dtype=float32),
   'zero_points': array([], dtype=int32)},
  'shape': array([40,  1, 20], dtype=int32),
  'shape_signature': array([40, -1, 20], dtype=int32),
  'sparsity_parameters': {}},
 {'dtype': numpy.int32,
  'index': 34,
  'name': 'TensorArrayV2Stack/TensorListStack;sequential/lstm/PartitionedCall/TensorArrayV2Stack/TensorListStack',
  'quantization': (0.0, 0),
  'quantization_parameters': {'quantized_dimension': 0,
   'scales': array([], dtype=float32),
   'zero_points': array([], dtype=int32)},
  'shape': array([3], dtype=int32),
  'shape_signature': array([3], dtype=int32),
  'sparsity_parameters': {}},
 {'dtype': numpy.float32,
  'index': 35,
  'name': 'TensorArrayV2Stack/TensorListStack;sequential/lstm/PartitionedCall/TensorArrayV2Stack/TensorListStack1',
  'quantization': (0.0, 0),
  'quantization_parameters': {'quantized_dimension': 0,
   'scales': array([], dtype=float32),
   'zero_points': array([], dtype=int32)},
  'shape': array([1, 1, 1], dtype=int32),
  'shape_signature': array([-1, -1, -1], dtype=int32),
  'sparsity_parameters': {}},
 {'dtype': numpy.float32,
  'index': 36,
  'name': 'strided_slice_2;sequential/lstm/PartitionedCall/strided_slice_23',
  'quantization': (0.0, 0),
  'quantization_parameters': {'quantized_dimension': 0,
   'scales': array([], dtype=float32),
   'zero_points': array([], dtype=int32)},
  'shape': array([1, 1], dtype=int32),
  'shape_signature': array([-1, -1], dtype=int32),
  'sparsity_parameters': {}},
 {'dtype': numpy.float32,
  'index': 37,
  'name': 'sequential/dense/BiasAdd',
  'quantization': (0.0, 0),
  'quantization_parameters': {'quantized_dimension': 0,
   'scales': array([], dtype=float32),
   'zero_points': array([], dtype=int32)},
  'shape': array([1, 3], dtype=int32),
  'shape_signature': array([-1,  3], dtype=int32),
  'sparsity_parameters': {}},
 {'dtype': numpy.float32,
  'index': 38,
  'name': 'Identity',
  'quantization': (0.0, 0),
  'quantization_parameters': {'quantized_dimension': 0,
   'scales': array([], dtype=float32),
   'zero_points': array([], dtype=int32)},
  'shape': array([1, 3], dtype=int32),
  'shape_signature': array([-1,  3], dtype=int32),
  'sparsity_parameters': {}}]
```

Please close the issue if this was resolved for you. Thanks!

**Comment by farmaker47** [comment]
@jvishnuvardhan Yes! It works and prints correct output node shape.
I figured during notebook execution that with this tf-nightly it cannot load Tensorboard with the provided code snippet from official Tensorflow documentation

%load_ext tensorboard
%tensorboard --logdir logs/fit

It gives below error:

ERROR: Failed to launch TensorBoard (exited with 1).
Contents of stderr:
2020-05-06 04:51:39.908137: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
Traceback (most recent call last):
  File "/usr/local/bin/tensorboard", line 8, in <module>
    sys.exit(run_main())
  File "/usr/local/lib/python3.6/dist-packages/tensorboard/main.py", line 75, in run_main
    app.run(tensorboard.main, flags_parser=tensorboard.configure)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/usr/local/lib/python3.6/dist-packages/tensorboard/program.py", line 289, in main
    return runner(self.flags) or 0
  File "/usr/local/lib/python3.6/dist-packages/tensorboard/program.py", line 305, in _run_serve_subcommand
    server = self._make_server()
  File "/usr/local/lib/python3.6/dist-packages/tensorboard/program.py", line 409, in _make_server
    self.flags, self.plugin_loaders, self.assets_zip_provider
  File "/usr/local/lib/python3.6/dist-packages/tensorboard/backend/application.py", line 157, in standard_tensorboard_wsgi
    flags, plugin_loaders, data_provider, assets_zip_provider, multiplexer
  File "/usr/local/lib/python3.6/dist-packages/tensorboard/backend/application.py", line 236, in TensorBoardWSGIApp
    tbplugins, flags.path_prefix, data_provider, experimental_plugins
  File "/usr/local/lib/python3.6/dist-packages/tensorboard/backend/application.py", line 309, in __init__
    "Duplicate plugins for name %s" % plugin.plugin_name
ValueError: Duplicate plugins for name projector


But I don't know if this is your responsibility..

Thank you for your time!!

**Comment by farmaker47** [comment]
I changed uninstall tensorflow to below code and Tensorboard shows graph correctly:

!pip uninstall tensorflow tensorboard
!pip install tf-nightly

Thanks again for your time!
Closing issue!
