### ISSUE TITLE
[tf-dbg] source_utils_test fails in Python 3.8

### ISSUE THREAD

**Issue by byronyi** [tensorflow/tensorflow#39210]
TF version hash: 47ee0d08b22e79b84eb442ccb75ef8e4ccd5ec07

See the following test log:
```
Test output for //tensorflow/python/debug:source_utils_test:
/bazel-buildfarm/default/operations/cf843b16-8c97-4552-8d55-fd16fe09d4f4/bazel-out/k8-opt/bin/tensorflow/python/debug/source_utils_test.runfiles/org_tensorflow/tensorflow/python/ops/random_ops.py:287: SyntaxWarning: "is" with a literal. Did you mean "=="?
  minval_is_zero = minval is 0  # pylint: disable=literal-comparison
/bazel-buildfarm/default/operations/cf843b16-8c97-4552-8d55-fd16fe09d4f4/bazel-out/k8-opt/bin/tensorflow/python/debug/source_utils_test.runfiles/org_tensorflow/tensorflow/python/ops/random_ops.py:288: SyntaxWarning: "is" with a literal. Did you mean "=="?
  maxval_is_one = maxval is 1  # pylint: disable=literal-comparison
/bazel-buildfarm/default/operations/cf843b16-8c97-4552-8d55-fd16fe09d4f4/bazel-out/k8-opt/bin/tensorflow/python/debug/source_utils_test.runfiles/org_tensorflow/tensorflow/python/ops/ragged/ragged_batch_gather_with_default_op.py:84: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if (default_value.shape.ndims is not 0
/bazel-buildfarm/default/operations/cf843b16-8c97-4552-8d55-fd16fe09d4f4/bazel-out/k8-opt/bin/tensorflow/python/debug/source_utils_test.runfiles/org_tensorflow/tensorflow/python/ops/ragged/ragged_batch_gather_with_default_op.py:85: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  and default_value.shape.ndims is not 1):
Running tests under Python 3.8.2: /usr/bin/python3.8
[ RUN      ] GuessIsTensorFlowLibraryTest.testDebuggerExampleFilePathReturnsFalse
[       OK ] GuessIsTensorFlowLibraryTest.testDebuggerExampleFilePathReturnsFalse
[ RUN      ] GuessIsTensorFlowLibraryTest.testFileInPythonKernelsPathReturnsTrue
[       OK ] GuessIsTensorFlowLibraryTest.testFileInPythonKernelsPathReturnsTrue
[ RUN      ] GuessIsTensorFlowLibraryTest.testGuessedBaseDirIsProbablyCorrect
[       OK ] GuessIsTensorFlowLibraryTest.testGuessedBaseDirIsProbablyCorrect
[ RUN      ] GuessIsTensorFlowLibraryTest.testNonPythonFileRaisesException
[       OK ] GuessIsTensorFlowLibraryTest.testNonPythonFileRaisesException
[ RUN      ] GuessIsTensorFlowLibraryTest.testSourceUtilModuleReturnsTrue
[       OK ] GuessIsTensorFlowLibraryTest.testSourceUtilModuleReturnsTrue
[ RUN      ] GuessIsTensorFlowLibraryTest.testUnitTestFileReturnsFalse
[       OK ] GuessIsTensorFlowLibraryTest.testUnitTestFileReturnsFalse
[ RUN      ] GuessIsTensorFlowLibraryTest.test_session
WARNING:tensorflow:From /usr/lib/python3.8/contextlib.py:83: TensorFlowTestCase.test_session (from tensorflow.python.framework.test_util) is deprecated and will be removed in a future version.
Instructions for updating:
Use `self.session()` or `self.cached_session()` instead.
W0506 00:11:11.384973 140211243161344 deprecation.py:317] From /usr/lib/python3.8/contextlib.py:83: TensorFlowTestCase.test_session (from tensorflow.python.framework.test_util) is deprecated and will be removed in a future version.
Instructions for updating:
Use `self.session()` or `self.cached_session()` instead.
[       OK ] GuessIsTensorFlowLibraryTest.test_session
[ RUN      ] ListSourceAgainstDumpTest.testGenerateSourceList
[  SKIPPED ] ListSourceAgainstDumpTest.testGenerateSourceList
[ RUN      ] ListSourceAgainstDumpTest.testGenerateSourceListWithNodeNameFilter
[  SKIPPED ] ListSourceAgainstDumpTest.testGenerateSourceListWithNodeNameFilter
[ RUN      ] ListSourceAgainstDumpTest.testGenerateSourceListWithPathRegexFilter
[  SKIPPED ] ListSourceAgainstDumpTest.testGenerateSourceListWithPathRegexFilter
[ RUN      ] ListSourceAgainstDumpTest.test_session
[  SKIPPED ] ListSourceAgainstDumpTest.test_session
[ RUN      ] SourceHelperTest.testAnnotateDumpedTensorsGivesCorrectResult
2020-05-06 00:11:11.473613: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with Intel(R) MKL-DNN to use the following CPU instructions in performance-critical operations:  AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-05-06 00:11:11.489470: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 2500005000 Hz
2020-05-06 00:11:11.497351: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x28121b0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-05-06 00:11:11.497393: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
/bazel-buildfarm/default/operations/cf843b16-8c97-4552-8d55-fd16fe09d4f4/bazel-out/k8-opt/bin/tensorflow/python/debug/source_utils_test.runfiles/org_tensorflow/tensorflow/python/autograph/utils/testing.py:21: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
[       OK ] SourceHelperTest.testAnnotateDumpedTensorsGivesCorrectResult
[ RUN      ] SourceHelperTest.testAnnotateSubsetOfLinesGivesCorrectResult
[       OK ] SourceHelperTest.testAnnotateSubsetOfLinesGivesCorrectResult
[ RUN      ] SourceHelperTest.testAnnotateWholeValidSourceFileGivesCorrectResult
[  FAILED  ] SourceHelperTest.testAnnotateWholeValidSourceFileGivesCorrectResult
[ RUN      ] SourceHelperTest.testAnnotateWithStackTopGivesCorrectResult
[  FAILED  ] SourceHelperTest.testAnnotateWithStackTopGivesCorrectResult
[ RUN      ] SourceHelperTest.testCallingAnnotateSourceOnUnrelatedSourceFileDoesNotError
[       OK ] SourceHelperTest.testCallingAnnotateSourceOnUnrelatedSourceFileDoesNotError
[ RUN      ] SourceHelperTest.testCallingAnnotateSourceWithoutPythonGraphRaisesException
[       OK ] SourceHelperTest.testCallingAnnotateSourceWithoutPythonGraphRaisesException
[ RUN      ] SourceHelperTest.testLoadNonexistentNonParPathFailsWithIOError
[       OK ] SourceHelperTest.testLoadNonexistentNonParPathFailsWithIOError
[ RUN      ] SourceHelperTest.testLoadingPythonSourceFileInParFileFailsRaisingIOError
[       OK ] SourceHelperTest.testLoadingPythonSourceFileInParFileFailsRaisingIOError
[ RUN      ] SourceHelperTest.testLoadingPythonSourceFileInParFileSucceeds
[       OK ] SourceHelperTest.testLoadingPythonSourceFileInParFileSucceeds
[ RUN      ] SourceHelperTest.testLoadingPythonSourceFileWithNonAsciiChars
[       OK ] SourceHelperTest.testLoadingPythonSourceFileWithNonAsciiChars
[ RUN      ] SourceHelperTest.test_session
[       OK ] SourceHelperTest.test_session
======================================================================
ERROR: testAnnotateWholeValidSourceFileGivesCorrectResult (__main__.SourceHelperTest)
testAnnotateWholeValidSourceFileGivesCorrectResult (__main__.SourceHelperTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/bazel-buildfarm/default/operations/cf843b16-8c97-4552-8d55-fd16fe09d4f4/bazel-out/k8-opt/bin/tensorflow/python/debug/source_utils_test.runfiles/org_tensorflow/tensorflow/python/debug/lib/source_utils_test.py", line 159, in testAnnotateWholeValidSourceFileGivesCorrectResult
    source_annotation[self.u_init_line_number])
KeyError: 116

======================================================================
ERROR: testAnnotateWithStackTopGivesCorrectResult (__main__.SourceHelperTest)
testAnnotateWithStackTopGivesCorrectResult (__main__.SourceHelperTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/bazel-buildfarm/default/operations/cf843b16-8c97-4552-8d55-fd16fe09d4f4/bazel-out/k8-opt/bin/tensorflow/python/debug/source_utils_test.runfiles/org_tensorflow/tensorflow/python/debug/lib/source_utils_test.py", line 181, in testAnnotateWithStackTopGivesCorrectResult
    source_annotation[self.u_init_line_number])
KeyError: 116

----------------------------------------------------------------------
Ran 22 tests in 1.288s

FAILED (errors=2, skipped=4)
```

cc @caisq

**Comment by byronyi** [comment]
Local test results:

```
Executing tests from //tensorflow/python/debug:source_utils_test
-----------------------------------------------------------------------------
/home/byronyi/.cache/bazel/_bazel_byronyi/53d6946ea85fa3b31de84f256c98e548/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/debug/source_utils_test.runfiles/org_tensorflow/tensorflow/python/ops/random_ops.py:287: SyntaxWarning: "is" with a literal. Did you mean "=="?
  minval_is_zero = minval is 0  # pylint: disable=literal-comparison
/home/byronyi/.cache/bazel/_bazel_byronyi/53d6946ea85fa3b31de84f256c98e548/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/debug/source_utils_test.runfiles/org_tensorflow/tensorflow/python/ops/random_ops.py:288: SyntaxWarning: "is" with a literal. Did you mean "=="?
  maxval_is_one = maxval is 1  # pylint: disable=literal-comparison
/home/byronyi/.cache/bazel/_bazel_byronyi/53d6946ea85fa3b31de84f256c98e548/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/debug/source_utils_test.runfiles/org_tensorflow/tensorflow/python/ops/ragged/ragged_batch_gather_with_default_op.py:84: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if (default_value.shape.ndims is not 0
/home/byronyi/.cache/bazel/_bazel_byronyi/53d6946ea85fa3b31de84f256c98e548/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/debug/source_utils_test.runfiles/org_tensorflow/tensorflow/python/ops/ragged/ragged_batch_gather_with_default_op.py:85: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  and default_value.shape.ndims is not 1):
Running tests under Python 3.8.2: /usr/bin/python3.8
[ RUN      ] GuessIsTensorFlowLibraryTest.testDebuggerExampleFilePathReturnsFalse
[       OK ] GuessIsTensorFlowLibraryTest.testDebuggerExampleFilePathReturnsFalse
[ RUN      ] GuessIsTensorFlowLibraryTest.testFileInPythonKernelsPathReturnsTrue
[       OK ] GuessIsTensorFlowLibraryTest.testFileInPythonKernelsPathReturnsTrue
[ RUN      ] GuessIsTensorFlowLibraryTest.testGuessedBaseDirIsProbablyCorrect
[       OK ] GuessIsTensorFlowLibraryTest.testGuessedBaseDirIsProbablyCorrect
[ RUN      ] GuessIsTensorFlowLibraryTest.testNonPythonFileRaisesException
[       OK ] GuessIsTensorFlowLibraryTest.testNonPythonFileRaisesException
[ RUN      ] GuessIsTensorFlowLibraryTest.testSourceUtilModuleReturnsTrue
[       OK ] GuessIsTensorFlowLibraryTest.testSourceUtilModuleReturnsTrue
[ RUN      ] GuessIsTensorFlowLibraryTest.testUnitTestFileReturnsFalse
[       OK ] GuessIsTensorFlowLibraryTest.testUnitTestFileReturnsFalse
[ RUN      ] GuessIsTensorFlowLibraryTest.test_session
WARNING:tensorflow:From /usr/lib/python3.8/contextlib.py:83: TensorFlowTestCase.test_session (from tensorflow.python.framework.test_util) is deprecated and will be removed in a future version.
Instructions for updating:
Use `self.session()` or `self.cached_session()` instead.
W0506 05:14:47.790310 139630758512448 deprecation.py:317] From /usr/lib/python3.8/contextlib.py:83: TensorFlowTestCase.test_session (from tensorflow.python.framework.test_util) is deprecated and will be removed in a future version.
Instructions for updating:
Use `self.session()` or `self.cached_session()` instead.
[       OK ] GuessIsTensorFlowLibraryTest.test_session
[ RUN      ] ListSourceAgainstDumpTest.testGenerateSourceList
[  SKIPPED ] ListSourceAgainstDumpTest.testGenerateSourceList
[ RUN      ] ListSourceAgainstDumpTest.testGenerateSourceListWithNodeNameFilter
[  SKIPPED ] ListSourceAgainstDumpTest.testGenerateSourceListWithNodeNameFilter
[ RUN      ] ListSourceAgainstDumpTest.testGenerateSourceListWithPathRegexFilter
[  SKIPPED ] ListSourceAgainstDumpTest.testGenerateSourceListWithPathRegexFilter
[ RUN      ] ListSourceAgainstDumpTest.test_session
[  SKIPPED ] ListSourceAgainstDumpTest.test_session
[ RUN      ] SourceHelperTest.testAnnotateDumpedTensorsGivesCorrectResult
2020-05-06 05:14:47.850294: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with Intel(R) MKL-DNN to use the following CPU instructions in performance-critical operations:  SSE3 SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
/home/byronyi/.cache/bazel/_bazel_byronyi/53d6946ea85fa3b31de84f256c98e548/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/debug/source_utils_test.runfiles/org_tensorflow/tensorflow/python/autograph/utils/testing.py:21: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
[       OK ] SourceHelperTest.testAnnotateDumpedTensorsGivesCorrectResult
[ RUN      ] SourceHelperTest.testAnnotateSubsetOfLinesGivesCorrectResult
[       OK ] SourceHelperTest.testAnnotateSubsetOfLinesGivesCorrectResult
[ RUN      ] SourceHelperTest.testAnnotateWholeValidSourceFileGivesCorrectResult
[  FAILED  ] SourceHelperTest.testAnnotateWholeValidSourceFileGivesCorrectResult
[ RUN      ] SourceHelperTest.testAnnotateWithStackTopGivesCorrectResult
[  FAILED  ] SourceHelperTest.testAnnotateWithStackTopGivesCorrectResult
[ RUN      ] SourceHelperTest.testCallingAnnotateSourceOnUnrelatedSourceFileDoesNotError
[       OK ] SourceHelperTest.testCallingAnnotateSourceOnUnrelatedSourceFileDoesNotError
[ RUN      ] SourceHelperTest.testCallingAnnotateSourceWithoutPythonGraphRaisesException
[       OK ] SourceHelperTest.testCallingAnnotateSourceWithoutPythonGraphRaisesException
[ RUN      ] SourceHelperTest.testLoadNonexistentNonParPathFailsWithIOError
[       OK ] SourceHelperTest.testLoadNonexistentNonParPathFailsWithIOError
[ RUN      ] SourceHelperTest.testLoadingPythonSourceFileInParFileFailsRaisingIOError
[       OK ] SourceHelperTest.testLoadingPythonSourceFileInParFileFailsRaisingIOError
[ RUN      ] SourceHelperTest.testLoadingPythonSourceFileInParFileSucceeds
[       OK ] SourceHelperTest.testLoadingPythonSourceFileInParFileSucceeds
[ RUN      ] SourceHelperTest.testLoadingPythonSourceFileWithNonAsciiChars
[       OK ] SourceHelperTest.testLoadingPythonSourceFileWithNonAsciiChars
[ RUN      ] SourceHelperTest.test_session
[       OK ] SourceHelperTest.test_session
======================================================================
ERROR: testAnnotateWholeValidSourceFileGivesCorrectResult (__main__.SourceHelperTest)
testAnnotateWholeValidSourceFileGivesCorrectResult (__main__.SourceHelperTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/byronyi/.cache/bazel/_bazel_byronyi/53d6946ea85fa3b31de84f256c98e548/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/debug/source_utils_test.runfiles/org_tensorflow/tensorflow/python/debug/lib/source_utils_test.py", line 159, in testAnnotateWholeValidSourceFileGivesCorrectResult
    source_annotation[self.u_init_line_number])
KeyError: 116

======================================================================
ERROR: testAnnotateWithStackTopGivesCorrectResult (__main__.SourceHelperTest)
testAnnotateWithStackTopGivesCorrectResult (__main__.SourceHelperTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/byronyi/.cache/bazel/_bazel_byronyi/53d6946ea85fa3b31de84f256c98e548/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/debug/source_utils_test.runfiles/org_tensorflow/tensorflow/python/debug/lib/source_utils_test.py", line 181, in testAnnotateWithStackTopGivesCorrectResult
    source_annotation[self.u_init_line_number])
KeyError: 116

----------------------------------------------------------------------
Ran 22 tests in 0.833s

FAILED (errors=2, skipped=4)
```

**Comment by byronyi** [comment]
Just found out that this is a known issue. I added test tag filters to workaround this.

**Comment by caisq** [comment]
This should have been taken care of by the recently merged https://github.com/tensorflow/tensorflow/commit/fb416f16e2b01252326816bb311c3e6165d13bcf
