### ISSUE TITLE
Im triying to use rasa inside Anaconda and using "rasa init" command to create a rasa project I get errors!

### ISSUE THREAD

**Issue by carlomcz** [tensorflow/tensorflow#39261]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Im triying to use rasa inside Anaconda and using "rasa init" command to create a rasa project I get errors
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): windows 10 home with Anaconda
 
- TensorFlow version (use command below): tensorflow-estimator==2.1.0 (Anaconda virtualenv)
- Python version: python-3.6.10
- GPU model and memory: dell x-64, 4GB, i3

**(rasa) C:\Users\carlo>rasa init**

Traceback (most recent call last):
  File "c:\users\carlo\anaconda3\envs\rasa\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "c:\users\carlo\anaconda3\envs\rasa\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "c:\users\carlo\anaconda3\envs\rasa\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "c:\users\carlo\anaconda3\envs\rasa\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "c:\users\carlo\anaconda3\envs\rasa\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: Uma rotina de inicialização da biblioteca de vínculo dinâmico (DLL) falhou.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\carlo\anaconda3\envs\rasa\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\carlo\anaconda3\envs\rasa\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\carlo\anaconda3\envs\rasa\Scripts\rasa.exe\__main__.py", line 7, in <module>
  File "c:\users\carlo\anaconda3\envs\rasa\lib\site-packages\rasa\__main__.py", line 82, in main
    set_log_level(log_level)
  File "c:\users\carlo\anaconda3\envs\rasa\lib\site-packages\rasa\utils\common.py", line 71, in set_log_level
    update_tensorflow_log_level()
  File "c:\users\carlo\anaconda3\envs\rasa\lib\site-packages\rasa\utils\common.py", line 112, in update_tensorflow_log_level
    import tensorflow as tf
  File "c:\users\carlo\anaconda3\envs\rasa\lib\site-packages\tensorflow\__init__.py", line 101, in <module>
    from tensorflow_core import *
  File "c:\users\carlo\anaconda3\envs\rasa\lib\site-packages\tensorflow_core\__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "c:\users\carlo\anaconda3\envs\rasa\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "c:\users\carlo\anaconda3\envs\rasa\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "c:\users\carlo\anaconda3\envs\rasa\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "c:\users\carlo\anaconda3\envs\rasa\lib\site-packages\tensorflow_core\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "c:\users\carlo\anaconda3\envs\rasa\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "c:\users\carlo\anaconda3\envs\rasa\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "c:\users\carlo\anaconda3\envs\rasa\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "c:\users\carlo\anaconda3\envs\rasa\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "c:\users\carlo\anaconda3\envs\rasa\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "c:\users\carlo\anaconda3\envs\rasa\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: Uma rotina de inicialização da biblioteca de vínculo dinâmico (DLL) falhou.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by ravikyram** [comment]
@carlomcz 

For Anconda related issues, please open an issue in [Anaconda repo.](https://github.com/ContinuumIO/anaconda-issues/issues) for faster resolution.We can close the issue here and we can track the issue in Anaconda repo. Please, confirm.Thanks!

**Comment by ravikyram** [comment]
@carlomcz 

It may occur because you may not have Visual C++ Redistributable for Windows. Please download it from [here](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads).Please, check Your CPU/Python is on 32 bits?Please, refer #36167 .Thanks!
