### ISSUE TITLE
Bazel build fails on MacOS Catalina - Unable to find numpy package despite PYTHON_LIB_PATH set to the directory containing the numpy package

### ISSUE THREAD

**Issue by dcs3spp** [tensorflow/tensorflow#39309]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS Catalina 10.15.4
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): Source
- TensorFlow version: RELEASE.md => Release 2.0.1 building from source
- Python version: 3.6.6
- Installed using virtualenv? pip? conda?: pyenv
- Bazel version (if compiling from source): 3.0.0
- GCC/Compiler version (if compiling from source): 4.2.1 (Apple clang version 11.0.3 (clang-1103.0.32.59))
- CUDA/cuDNN version: N/A
- GPU model and memory: AMD Radeon R9 M295X 4 GB graphics

**Describe the problem**
Trying to build from source as documented [here](https://www.tensorflow.org/install/source) fails for me on MacOS Cataline 10.15.4...the bazel build process cannot find numpy package even though a listing of the PYTHON_LIB_PATH shows the numpy package is present:

``` bash
$ ls /Users/simon/Library/Python/3.6/lib/python/site-packages

Keras_Applications-1.0.8.dist-info/  easy_install.py                      keras_applications/                  libpasteurize/                       numpy/                               pkg_resources/                       six-1.14.0.dist-info/                wheel-0.34.2.dist-info/
Keras_Preprocessing-1.1.0.dist-info/ future/                              keras_preprocessing/                 mock/                                numpy-1.18.4.dist-info/              setuptools/                          six.py
__pycache__/                         future-0.18.2.dist-info/             libfuturize/                         mock-4.0.2.dist-info/                past/                                setuptools-46.1.3.dist-info/         wheel/
```
I am using Python 3.6.6 via pyenv.

Salient output from bazel build process included below. Full error log from build process included at the the end of report.

``` bash
ERROR: An error occurred during the fetch of repository 'local_execution_config_python':
   Traceback (most recent call last):
	File "/Users/simon/src/libs/third-party/tensorflow/third_party/py/python_configure.bzl", line 213
		_get_numpy_include(<2 more arguments>)
	File "/Users/simon/src/libs/third-party/tensorflow/third_party/py/python_configure.bzl", line 187, in _get_numpy_include
		execute(repository_ctx, <3 more arguments>)
	File "/Users/simon/src/libs/third-party/tensorflow/third_party/remote_config/common.bzl", line 208, in execute
		fail(<1 more arguments>)
Problem getting numpy include path.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'numpy'
Is numpy installed?

PYTHON_BIN_PATH=/Users/simon/.pyenv/versions/3.6.6/bin/python3 --action_env

PYTHON_LIB_PATH=/Users/simon/Library/Python/3.6/lib/python/site-packages
```

**Provide the exact sequence of commands / steps that you executed before running into the problem**
$ pyenv version system
3.6.6 (set by /Users/simon/.pyenv/version)

$ pip install -U --user pip six numpy wheel setuptools mock 'future>=0.17.1'
$ pip install -U --user keras_applications --no-deps
$ pip install -U --user keras_preprocessing --no-deps

# required python packages exist as shown in stdout log from pip install
Requirement already up-to-date: pip in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (20.1)
Requirement already up-to-date: six in /Users/simon/Library/Python/3.6/lib/python/site-packages (1.14.0)
Requirement already up-to-date: numpy in /Users/simon/Library/Python/3.6/lib/python/site-packages (1.18.4)
Requirement already up-to-date: wheel in /Users/simon/Library/Python/3.6/lib/python/site-packages (0.34.2)
Requirement already up-to-date: setuptools in /Users/simon/Library/Python/3.6/lib/python/site-packages (46.1.3)
Requirement already up-to-date: mock in /Users/simon/Library/Python/3.6/lib/python/site-packages (4.0.2)
Requirement already up-to-date: future>=0.17.1 in /Users/simon/Library/Python/3.6/lib/python/site-packages (0.18.2)
Requirement already up-to-date: keras_applications in /Users/simon/Library/Python/3.6/lib/python/site-packages (1.0.8)
Requirement already up-to-date: keras_preprocessing in /Users/simon/Library/Python/3.6/lib/python/site-packages (1.1.0)

$ ./configure
Please specify the location of python. [Default is /Users/simon/.pyenv/versions/3.6.6/bin/python3]:  /Users/simon/.pyenv/versions/3.6.6/bin/python3 
Please input the desired Python library path to use.  Default is [/Users/simon/.pyenv/versions/3.6.6/lib/python3.6/site-packages] /Users/simon/Library/Python/3.6/lib/python/site-packages
Do you wish to build TensorFlow with OpenCL SYCL support? [y/N]: n
Do you wish to build TensorFlow with ROCm support? [y/N]: n
Do you wish to build TensorFlow with CUDA support? [y/N]: n
Do you wish to download a fresh release of clang? (Experimental) [y/N]: n
Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native -Wno-sign-compare]: -march=core2 -Wno-sign-compare
Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]: n
Do you wish to build TensorFlow with iOS support? [y/N]: n

$  bazel build --config=opt --config=monolithic --config=noaws --config=nogcp --config=nohdfs --config=nonccl //tensorflow/tools/lib_package:libtensorflow

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

When run the above build steps, error message displayed because numpy package was not found.

``` bash
bazel build --config=opt --config=monolithic --config=noaws --config=nogcp --config=nohdfs --config=nonccl //tensorflow/tools/lib_package:libtensorflow
Starting local Bazel server and connecting to it...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=298
INFO: Reading rc options for 'build' from /Users/simon/src/libs/third-party/tensorflow/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /Users/simon/src/libs/third-party/tensorflow/.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --java_toolchain=//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=//third_party/toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --enable_platform_specific_config --config=v2
INFO: Reading rc options for 'build' from /Users/simon/src/libs/third-party/tensorflow/.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=/Users/simon/.pyenv/versions/3.6.6/bin/python3 --action_env PYTHON_LIB_PATH=/Users/simon/Library/Python/3.6/lib/python/site-packages --python_path=/Users/simon/.pyenv/versions/3.6.6/bin/python3 --config=xla --action_env TF_CONFIGURE_IOS=0
INFO: Found applicable config definition build:v2 in file /Users/simon/src/libs/third-party/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:xla in file /Users/simon/src/libs/third-party/tensorflow/.bazelrc: --action_env=TF_ENABLE_XLA=1 --define=with_xla_support=true
INFO: Found applicable config definition build:opt in file /Users/simon/src/libs/third-party/tensorflow/.tf_configure.bazelrc: --copt=-march=core2 --copt=-Wno-sign-compare --host_copt=-march=native --define with_default_optimizations=true
INFO: Found applicable config definition build:monolithic in file /Users/simon/src/libs/third-party/tensorflow/.bazelrc: --define framework_shared_object=false
INFO: Found applicable config definition build:noaws in file /Users/simon/src/libs/third-party/tensorflow/.bazelrc: --define=no_aws_support=true
INFO: Found applicable config definition build:nogcp in file /Users/simon/src/libs/third-party/tensorflow/.bazelrc: --define=no_gcp_support=true
INFO: Found applicable config definition build:nohdfs in file /Users/simon/src/libs/third-party/tensorflow/.bazelrc: --define=no_hdfs_support=true
INFO: Found applicable config definition build:nonccl in file /Users/simon/src/libs/third-party/tensorflow/.bazelrc: --define=no_nccl_support=true
INFO: Found applicable config definition build:macos in file /Users/simon/src/libs/third-party/tensorflow/.bazelrc: --copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --cxxopt=-std=c++14 --host_cxxopt=-std=c++14
INFO: Call stack for the definition of repository 'local_config_python' which is a python_configure (rule definition at /Users/simon/src/libs/third-party/tensorflow/third_party/py/python_configure.bzl:294:20):
 - <builtin>
 - /Users/simon/src/libs/third-party/tensorflow/tensorflow/workspace.bzl:104:5
 - /Users/simon/src/libs/third-party/tensorflow/WORKSPACE:19:1
INFO: Call stack for the definition of repository 'local_execution_config_python' which is a local_python_configure (rule definition at /Users/simon/src/libs/third-party/tensorflow/third_party/py/python_configure.bzl:275:26):
 - <builtin>
 - /Users/simon/src/libs/third-party/tensorflow/third_party/toolchains/remote_config/rbe_config.bzl:158:5
 - /Users/simon/src/libs/third-party/tensorflow/third_party/toolchains/remote_config/configs.bzl:6:5
 - /Users/simon/src/libs/third-party/tensorflow/tensorflow/workspace.bzl:93:5
 - /Users/simon/src/libs/third-party/tensorflow/WORKSPACE:19:1
ERROR: An error occurred during the fetch of repository 'local_execution_config_python':
   Traceback (most recent call last):
	File "/Users/simon/src/libs/third-party/tensorflow/third_party/py/python_configure.bzl", line 213
		_get_numpy_include(<2 more arguments>)
	File "/Users/simon/src/libs/third-party/tensorflow/third_party/py/python_configure.bzl", line 187, in _get_numpy_include
		execute(repository_ctx, <3 more arguments>)
	File "/Users/simon/src/libs/third-party/tensorflow/third_party/remote_config/common.bzl", line 208, in execute
		fail(<1 more arguments>)
Problem getting numpy include path.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'numpy'
Is numpy installed?
INFO: Call stack for the definition of repository 'com_google_protobuf' which is a tf_http_archive (rule definition at /Users/simon/src/libs/third-party/tensorflow/third_party/repo.bzl:134:19):
 - <builtin>
 - /Users/simon/src/libs/third-party/tensorflow/tensorflow/workspace.bzl:559:5
 - /Users/simon/src/libs/third-party/tensorflow/WORKSPACE:19:1
Internal error thrown during build. Printing stack trace: java.lang.NullPointerException: //tensorflow/tools/lib_package:libtensorflow BuildConfigurationValue.Key[e4e94f4998e8c26abbc5eb2bf9d33e94aa6f63e0a9af8b8373f7ec758ef26105] false
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:895)
	at com.google.devtools.build.skyframe.DelegatingWalkableGraph.getDirectDeps(DelegatingWalkableGraph.java:121)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.assertSaneAnalysisError(SkyframeBuildView.java:773)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.processErrors(SkyframeBuildView.java:616)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.configureTargets(SkyframeBuildView.java:454)
	at com.google.devtools.build.lib.analysis.BuildView.update(BuildView.java:404)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.runAnalysisPhase(AnalysisPhaseRunner.java:213)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.execute(AnalysisPhaseRunner.java:124)
	at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:145)
	at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:290)
	at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:95)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:564)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:208)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:603)
	at com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$2(GrpcServerImpl.java:659)
	at io.grpc.Context$1.run(Context.java:595)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

INFO: Elapsed time: 3.854s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (16 packages loaded, 36 targets configured)
    currently loading: tensorflow ... (3 packages)
    Fetching @local_config_cc_toolchains; fetching
Internal error thrown during build. Printing stack trace: java.lang.NullPointerException: //tensorflow/tools/lib_package:libtensorflow BuildConfigurationValue.Key[e4e94f4998e8c26abbc5eb2bf9d33e94aa6f63e0a9af8b8373f7ec758ef26105] false
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:895)
	at com.google.devtools.build.skyframe.DelegatingWalkableGraph.getDirectDeps(DelegatingWalkableGraph.java:121)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.assertSaneAnalysisError(SkyframeBuildView.java:773)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.processErrors(SkyframeBuildView.java:616)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.configureTargets(SkyframeBuildView.java:454)
	at com.google.devtools.build.lib.analysis.BuildView.update(BuildView.java:404)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.runAnalysisPhase(AnalysisPhaseRunner.java:213)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.execute(AnalysisPhaseRunner.java:124)
	at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:145)
	at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:290)
	at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:95)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:564)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:208)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:603)
	at com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$2(GrpcServerImpl.java:659)
	at io.grpc.Context$1.run(Context.java:595)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
java.lang.NullPointerException: //tensorflow/tools/lib_package:libtensorflow BuildConfigurationValue.Key[e4e94f4998e8c26abbc5eb2bf9d33e94aa6f63e0a9af8b8373f7ec758ef26105] false
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:895)
	at com.google.devtools.build.skyframe.DelegatingWalkableGraph.getDirectDeps(DelegatingWalkableGraph.java:121)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.assertSaneAnalysisError(SkyframeBuildView.java:773)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.processErrors(SkyframeBuildView.java:616)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.configureTargets(SkyframeBuildView.java:454)
	at com.google.devtools.build.lib.analysis.BuildView.update(BuildView.java:404)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.runAnalysisPhase(AnalysisPhaseRunner.java:213)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.execute(AnalysisPhaseRunner.java:124)
	at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:145)
	at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:290)
	at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:95)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:564)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:208)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:603)
	at com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$2(GrpcServerImpl.java:659)
	at io.grpc.Context$1.run(Context.java:595)
FAILED: Build did NOT complete successfully (16 packages loaded, 36 targets configured)
    currently loading: tensorflow ... (3 packages)
    Fetching @local_config_cc_toolchains; fetching
```

**Comment by dcs3spp** [comment]
Solved by running eval $(pyenv init -) before running ./configure
