### ISSUE TITLE
InaccessibleTensorError: The tensor 'Tensor("Tile:0", shape=(None, 3), dtype=float32)' cannot be accessed here: it is defined in another function or code block.

### ISSUE THREAD

**Issue by cfrancesco** [tensorflow/tensorflow#39323]
**System information**
- Have I written custom code: Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS
- Mobile device: No
- TensorFlow installed from: binary
- TensorFlow version: 2.1.0
- Python version: 3.6.9
- CUDA/cuDNN version: None
- GPU model and memory: None

**Describe the current behavior**
Throws the error.
**Describe the expected behavior**
Returns a tensor of shape (2, 6, 3), e.g.
```
tf.Tensor(
[[[0.4200933  0.51168334 0.13771784]
  [0.4200933  0.51168334 0.13771784]
  [0.4200933  0.51168334 0.13771784]
  [0.31555724 0.80608404 0.38079023]
  [0.31555724 0.80608404 0.38079023]
  [0.22353566 0.7539935  0.28550136]]

 [[0.3753245  0.10351241 0.61035573]
  [0.51126313 0.4842764  0.5390732 ]
  [0.1071049  0.8601215  0.69413567]
  [0.1071049  0.8601215  0.69413567]
  [0.         0.         0.        ]
  [0.         0.         0.        ]]], shape=(2, 6, 3), dtype=float32)
```
**Standalone code to reproduce the issue**
```
import tensorflow as tf
@tf.function(input_signature=[
        tf.TensorSpec(shape=(None, None, 3), dtype=tf.float32),
        tf.TensorSpec(shape=(None, None, 1), dtype=tf.int32),
    ])
def some_fz(x, dims):
    batch_size = tf.shape(x)[0]
    seq_len = tf.shape(x)[1]
    dims = tf.cast(tf.math.round(dims), tf.int32)
    new_lengths = tf.reduce_sum(dims, axis=1)
    max_dim = tf.math.reduce_max(new_lengths)
    pad_sizes = max_dim - new_lengths
    new_batch = []
    x = tf.expand_dims(x, axis=-2)
    for i in tf.range(batch_size):
        tensor_list = []
        for j in tf.range(seq_len):
            tiled = tf.tile(x[i][j], [dims[i][j][0], 1])
            tensor_list.append(tiled)
        new_tensor = tf.concat(tensor_list, axis=0)  # breaks here
        new_tensor = tf.pad(new_tensor, [[0,pad_sizes[i][0]], [0,0]])
        new_batch.append(new_tensor)
    return tf.stack(new_batch)

if __name__ == '__main__':
    random = tf.random.uniform([2, 3, 3])
    vector = tf.constant([[[3], [2], [1]], [[1], [1], [2]]])
    out = some_fz(random, vector)
```

**Other info / logs** 
```
Traceback (most recent call last):
  File "/Users/fcardina/Library/Preferences/PyCharmCE2019.2/scratches/scratch_2.py", line 58, in <module>
    out = some_fz(random, new_dimension)
  File "/Users/fcardina/anaconda3/envs/ttsTF/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 568, in __call__
    result = self._call(*args, **kwds)
  File "/Users/fcardina/anaconda3/envs/ttsTF/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 615, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/Users/fcardina/anaconda3/envs/ttsTF/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 497, in _initialize
    *args, **kwds))
  File "/Users/fcardina/anaconda3/envs/ttsTF/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2389, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/Users/fcardina/anaconda3/envs/ttsTF/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2703, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/Users/fcardina/anaconda3/envs/ttsTF/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2593, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/Users/fcardina/anaconda3/envs/ttsTF/lib/python3.6/site-packages/tensorflow_core/python/framework/func_graph.py", line 978, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/Users/fcardina/anaconda3/envs/ttsTF/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 439, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/Users/fcardina/anaconda3/envs/ttsTF/lib/python3.6/site-packages/tensorflow_core/python/framework/func_graph.py", line 968, in wrapper
    raise e.ag_error_metadata.to_exception(e)
tensorflow.python.framework.errors_impl.InaccessibleTensorError: in converted code:

    /Users/fcardina/Library/Preferences/PyCharmCE2019.2/scratches/scratch_2.py:47 some_fz  *
        new_tensor = tf.concat(tensor_list, axis=0)
    /Users/fcardina/anaconda3/envs/ttsTF/lib/python3.6/site-packages/tensorflow_core/python/util/dispatch.py:180 wrapper
        return target(*args, **kwargs)
    /Users/fcardina/anaconda3/envs/ttsTF/lib/python3.6/site-packages/tensorflow_core/python/ops/array_ops.py:1516 concat
        return identity(values[0], name=name)
    /Users/fcardina/anaconda3/envs/ttsTF/lib/python3.6/site-packages/tensorflow_core/python/util/dispatch.py:180 wrapper
        return target(*args, **kwargs)
    /Users/fcardina/anaconda3/envs/ttsTF/lib/python3.6/site-packages/tensorflow_core/python/ops/array_ops.py:267 identity
        ret = gen_array_ops.identity(input, name=name)
    /Users/fcardina/anaconda3/envs/ttsTF/lib/python3.6/site-packages/tensorflow_core/python/ops/gen_array_ops.py:3829 identity
        "Identity", input=input, name=name)
    /Users/fcardina/anaconda3/envs/ttsTF/lib/python3.6/site-packages/tensorflow_core/python/framework/op_def_library.py:742 _apply_op_helper
        attrs=attr_protos, op_def=op_def)
    /Users/fcardina/anaconda3/envs/ttsTF/lib/python3.6/site-packages/tensorflow_core/python/framework/func_graph.py:591 _create_op_internal
        inp = self.capture(inp)
    /Users/fcardina/anaconda3/envs/ttsTF/lib/python3.6/site-packages/tensorflow_core/python/framework/func_graph.py:641 capture
        % (tensor, tensor.graph, self))

    InaccessibleTensorError: The tensor 'Tensor("Tile:0", shape=(None, 3), dtype=float32)' cannot be accessed here: it is defined in another function or code block. Use return values, explicit Python locals or TensorFlow collections to access it. Defined in: FuncGraph(name=while_body_59, id=5613077840); accessed from: FuncGraph(name=while_body_37, id=5612708472).
```

I tried to declare the list outside of the first loop, but it won't access the elements then. Doing tensor_list[i] would throw 
```
TypeError: list indices must be integers or slices, not Tensor
```

I tried what is suggested here:
https://github.com/tensorflow/tensorflow/issues/37512#issuecomment-600776581
But neither solution works. The first needs the lists to have the same size. The second complains that tf.autograph.experimental.set_loop_options has no shape_invariants argument.

**Comment by amahendrakar** [comment]
Was able to reproduce the error with [TF v2.2](https://colab.research.google.com/gist/amahendrakar/8ebb8811ad21605d6c6d72d4ca175112/39323.ipynb#scrollTo=nSaL3BWd4EDp) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/f88fbd4b54b97427eb05a379c64dbf32/39323-tf-nightly.ipynb). Please find the attached gist. Thanks!

**Comment by mdanatg** [comment]
I'm hoping that in a future version we'll support the plain list version, because right now things are a bit clunky to use.

For the first solution, the trouble in this case seems to be that TensorArray only supports elements of the same shape. But I think we can make it work by tiling inside the array and avoiding the `tf.tile`. I'm not sure this does exactly what you need, but here's a version that produces results:

```
    new_batch = tf.TensorArray(tf.float32, size=batch_size)
    x = tf.expand_dims(x, axis=-2)
    for i in tf.range(batch_size):
        tensor_list = tf.TensorArray(tf.float32, size=0, dynamic_size=True)
        for j in tf.range(seq_len):
            # tiled = tf.tile(x[i][j], [dims[i][j][0], 1])
            for k in tf.range(dims[i][j][0]):
              tensor_list = tensor_list.write(tensor_list.size(), x[i][j])
        new_tensor = tensor_list.stack()
        new_tensor = tf.pad(new_tensor, [[0,pad_sizes[i][0]], [0,0], [0, 0]])
        new_batch = new_batch.write(i, new_tensor)
    return new_batch.stack()
```

The second solution only works in TF 2.2 (that's when `set_loop_options` was added). I fudged the example by hardcoding some shapes, you'd need to use the proper ones in those `tf.zeros` and `shape_invariants`:

```
    new_batch = tf.zeros([0, 6, 3])
    x = tf.expand_dims(x, axis=-2)
    for i in tf.range(batch_size):
        tf.autograph.experimental.set_loop_options(
            shape_invariants=[(new_batch, tf.TensorShape([None, 6, 3]))]
        )
        tensor_list = tf.zeros([0, 3])
        for j in tf.range(seq_len):
            tf.autograph.experimental.set_loop_options(
                shape_invariants=[(tensor_list, tf.TensorShape([None, 3]))]
            )
            tiled = tf.tile(x[i][j], [dims[i][j][0], 1])
            tensor_list = tf.concat([tensor_list, tiled], axis=0)
        new_tensor = tf.pad(tensor_list, [[0,pad_sizes[i][0]], [0,0]])
        new_tensor = tf.expand_dims(new_tensor, 0)
        new_batch = tf.concat([new_batch, new_tensor], axis=0)
    return new_batch
```

**Comment by cfrancesco** [comment]
Hi,
thanks, that works. Quite clunky indeed. 

I did not realize that one of the issues was with the variable that defines the (outer) loop.
Here are some examples of what work and what doesn't (counter intuitively, I' say)

This does NOT work
```
@tf.function(input_signature=[
    tf.TensorSpec(shape=(None), dtype=tf.int32),
    tf.TensorSpec(shape=(None), dtype=tf.int32),
])
def foo(variable, loop_constant):
    a_list = []
    some_constant = 4
    the_tensor = tf.ones(some_constant)
    for i in range(loop_constant):
        t = tf.random.shuffle(the_tensor)
        a_list.append(t)
    return a_list
```

This DOES work, but it's obviously not acceptable
```
@tf.function(input_signature=[
    tf.TensorSpec(shape=(None), dtype=tf.int32),
    tf.TensorSpec(shape=(None), dtype=tf.int32),
])
def foo(variable):
    a_list = []
    some_constant = 4
    loop_constant = 5
    the_tensor = tf.ones(some_constant)
    for i in range(loop_constant):
        t = tf.random.shuffle(the_tensor)
        a_list.append(t)
    return a_list
```
This works and it's acceptable. Interestingly everything is defined within the same scope as the first example. I hope this becomes more pythonic in the future.
```
@tf.function(input_signature=[
    tf.TensorSpec(shape=(None), dtype=tf.int32),
    tf.TensorSpec(shape=(None), dtype=tf.int32),
])
def foo(variable, loop_constant):
    a_list = tf.TensorArray(tf.float32, size=loop_constant)
    some_constant = 4
    the_tensor = tf.ones(some_constant)
    for i in range(loop_constant):
        t = tf.random.shuffle(the_tensor)
        a_list = a_list.write(i, t)
    return a_list.stack()
```
Regarding the original question:
I ended up using this, in case someone has the same issue and looks for an alternative.
```
    def call(self, x, dimensions):
        dimensions = tf.squeeze(dimensions)
        dimensions = tf.cast(tf.math.round(dimensions), tf.int32)
        seq_len = tf.shape(x)[1]
        batch_size = tf.shape(x)[0]
        # build masks from dimensions
        max_dim = tf.math.reduce_max(dimensions)
        tot_dim = tf.math.reduce_sum(dimensions)
        index_masks = tf.RaggedTensor.from_row_lengths(tf.ones(tot_dim), tf.reshape(dimensions, [-1])).to_tensor()
        index_masks = tf.cast(tf.reshape(index_masks, (batch_size, seq_len * max_dim)), tf.float32)
        non_zeros = seq_len * max_dim - tf.reduce_sum(max_dim - dimensions, axis=1)
        # stack and mask
        tiled = tf.tile(x, [1, 1, max_dim])
        reshaped = tf.reshape(tiled, (batch_size, seq_len * max_dim, self.model_dimension))
        mask_reshape = tf.multiply(reshaped, index_masks[:, :, tf.newaxis])
        ragged = tf.RaggedTensor.from_row_lengths(mask_reshape[index_masks > 0], non_zeros)
        return ragged.to_tensor()
```

**Comment by saikumarchalla** [comment]
was able to reproduce the issue in TF 2.5 and Nightly versions. Please find the gist [here](https://colab.research.google.com/gist/saikumarchalla/d7435fc6378bc8e837b47d48e4cc7c30/untitled79.ipynb).Thanks!

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
