### ISSUE TITLE
interpreter.allocate_tensors() Failing for MNIST model with LocallyConnected2D layer

### ISSUE THREAD

**Issue by i2infinity** [tensorflow/tensorflow#39365]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **macOS 10.15.4**
- TensorFlow installed from (source or binary): **from pip**
- TensorFlow version (or GitHub SHA if from source): **2.2.0-rc4**

**Command used to run the converter or code if you’re using the Python API**
[colab.research.google.com](https://colab.research.google.com/drive/1GFvL0LrCYEwsLVBxjxF3hVeraGDZgJ41?usp=sharing) **_WORKS FINE ON COLAB BUT BREAKS ON MY MACHINE_**

```
def convert_keras_to_tflite_and_verify(keras_model):
  converter = tf.lite.TFLiteConverter.from_keras_model(keras_model)
  tflite_model = converter.convert()
  interpreter = tf.lite.Interpreter(model_content=tflite_model)
  interpreter.allocate_tensors()  # ERRORS OUT
```

**The output from the converter invocation**

```
2020-05-09 22:05:21.516092: I tensorflow/core/grappler/devices.cc:60] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0 (Note: TensorFlow was not compiled with CUDA support)
2020-05-09 22:05:21.516150: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2020-05-09 22:05:21.580927: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:797] Optimization results for grappler item: graph_to_optimize
2020-05-09 22:05:21.580949: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:799]   function_optimizer: function_optimizer did nothing. time = 0.001ms.
2020-05-09 22:05:21.580954: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:799]   function_optimizer: function_optimizer did nothing. time = 0ms.
2020-05-09 22:05:23.603879: I tensorflow/core/grappler/devices.cc:60] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0 (Note: TensorFlow was not compiled with CUDA support)
2020-05-09 22:05:23.603950: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2020-05-09 22:05:23.856983: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:797] Optimization results for grappler item: graph_to_optimize
2020-05-09 22:05:23.857001: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:799]   constant_folding: Graph size after: 3693 nodes (-25), 4297 edges (-25), time = 124.184ms.
2020-05-09 22:05:23.857005: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:799]   constant_folding: Graph size after: 3693 nodes (0), 4297 edges (0), time = 67.772ms.
Allocating tensors
Traceback (most recent call last):
  File "main.py", line 122, in <module>
    convert_keras_to_tflite_and_verify(mnist_model)
  File "main.py", line 68, in convert_keras_to_tflite_and_verify
    interpreter.allocate_tensors()
  File "/Users/xx/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/lite/python/interpreter.py", line 242, in allocate_tensors
    return self._interpreter.AllocateTensors()
  File "/Users/xx/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/lite/python/interpreter_wrapper/tensorflow_wrap_interpreter_wrapper.py", line 110, in AllocateTensors
    return _tensorflow_wrap_interpreter_wrapper.InterpreterWrapper_AllocateTensors(self)
RuntimeError: tensorflow/lite/kernels/reshape.cc:66 num_input_elements != num_output_elements (1331 != 121)Node number 3040 (RESHAPE) failed to prepare.
```

**Also, please include a link to the saved model or GraphDef**

The model can be found here [colab.research.google.com](https://colab.research.google.com/drive/1GFvL0LrCYEwsLVBxjxF3hVeraGDZgJ41?usp=sharing)

**Failure details**
The `interpreter.allocate_tensors()` method works fine on the colab notebook but fails for me locally on my machine for the exact same model

Background - I am trying to add a basic attention branch to a CNN model from https://keras.io/examples/mnist_cnn/. 
Replacing the `LocallyConnected2D` layer from the attention branch with `Conv2D` makes everything work fine.

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by Saduf2019** [comment]
@i2infinity 
As reported it works fine on calab, please find [gist here](https://colab.sandbox.google.com/gist/Saduf2019/a5ea2d4458d4da4ef64c5b3f4c8f5f60/untitled178.ipynb)
Could you please try the same on virtual environment and let us know.

**Comment by daverim** [comment]
Also to add, @i2infinity, I tried your code using  Tensorflow version 2.2.0-dev20200508 (pip install tf-nightly==2.2.0.dev20200508) and it works, but using tensorflow-2.2.0 has the error you mentioned. I think the tensorflow version installed in the colab must be higher. Try upgrading tensorflow to the nightly version and see if it works for you.

**Comment by Saduf2019** [comment]
@i2infinity 
Please update as per above comment

**Comment by i2infinity** [comment]
Hi @Saduf2019 @daverim - I will try this within the next couple of days and get back. Thanks for the suggestions

**Comment by i2infinity** [comment]
I think it is ok to close this one out as you have a fix that works on your end. I can re-open if needed
