### ISSUE TITLE
How the fuck do i use this thing 

### ISSUE THREAD

**Issue by Ihatetensorflow** [tensorflow/tensorflow#39389]
import tensorflow
from tensorflow import keras
import numpy as np
import matplotlib.pyplot as plt

print(tensorflow.__version__)

thats ALL my code
Traceback (most recent call last):
  File "C:/Users/Anon/PycharmProjects/Imgrecn1/img.py", line 1, in <module>
    import tensorflow
  File "C:\Users\Anon\AppData\Local\Programs\Python\Python38-32\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\Anon\AppData\Local\Programs\Python\Python38-32\lib\site-packages\tensorflow\python\__init__.py", line 63, in <module>
    from tensorflow.python.framework.framework_lib import *  # pylint: disable=redefined-builtin
  File "C:\Users\Anon\AppData\Local\Programs\Python\Python38-32\lib\site-packages\tensorflow\python\framework\framework_lib.py", line 77, in <module>
    from tensorflow.python.framework.ops import Graph
  File "C:\Users\Anon\AppData\Local\Programs\Python\Python38-32\lib\site-packages\tensorflow\python\framework\ops.py", line 42, in <module>
    from tensorflow.python.eager import context
  File "C:\Users\Anon\AppData\Local\Programs\Python\Python38-32\lib\site-packages\tensorflow\python\eager\context.py", line 50, in <module>
    DEVICE_PLACEMENT_EXPLICIT = pywrap_tensorflow.TFE_DEVICE_PLACEMENT_EXPLICIT
AttributeError: module 'tensorflow.python.pywrap_tensorflow' has no attribute 'TFE_DEVICE_PLACEMENT_EXPLICIT'

 these are all the errors. i honestly despise who ever made tensorflow

**Comment by Ihatetensorflow** [comment]
thanks to anyone that can help

**Comment by mherkazandjian** [comment]
how about you try

````python
import tensorflow
from tensorflow import keras
import numpy as np
import matplotlib.pyplot as plt

print(tensorflow.__version__)
````

here is a snippet

````python
>>> import tensorflow
>>> print(tensorflow.__version__)
2.2.0
````

**Comment by amahendrakar** [comment]
@Ihatetensorflow,
TensorFlow is supported only on 64-bit systems. Could you please check if you have 64-bit Python installed on your computer.

With 64-bit Python installed, run the below commands to install the latest version of TensorFlow 
```
pip install --upgrade pip
pip install tensorflow==2.2.0
```

For more information, please check this official [installation guide](https://www.tensorflow.org/install#download-a-package) from TensorFlow. Thanks!

**Comment by mihaimaruseac** [comment]
This is likely #32315. We don't support 32 bits Python builds.

Finally, please follow guidance listed in [code of conduct](https://github.com/tensorflow/tensorflow/blob/master/CODE_OF_CONDUCT.md)

**Comment by OzanKurt** [comment]
This is the most useless and undocumented open source package of all time!
