### ISSUE TITLE
the error in multiprocessing 

### ISSUE THREAD

**Issue by ucasiggcas** [tensorflow/tensorflow#39436]
hi,dear,
I have the problem in multiprocessing ,codes
```

from multiprocessing.pool import ThreadPool
modelV3=tf.keras.applications.InceptionV3(include_top=False, pooling='avg')

def process(inputs):
    x_pred=modelV3.predict(inputs)
    return x_pred

x=np.random.randn(1,299,299,3)
y=np.random.randn(1,299,299,3)
z=np.random.randn(1,299,299,3)

pool=ThreadPool(2)
pool.map(process,[x,y,z])
```
Error:

```
Traceback (most recent call last):
  File "D:\python36\new\xception_load_.py", line 26, in <module>
    pool.map(process,[x,y,z])
  File "D:\python36\lib\multiprocessing\pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "D:\python36\lib\multiprocessing\pool.py", line 644, in get
    raise self._value
  File "D:\python36\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "D:\python36\lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "D:\python36\new\xception_load_.py", line 18, in process
    x_pred=modelV3.predict(inputs)
  File "D:\python36\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 908, in predict
    use_multiprocessing=use_multiprocessing)
  File "D:\python36\lib\site-packages\tensorflow_core\python\keras\engine\training_arrays.py", line 723, in predict
    callbacks=callbacks)
  File "D:\python36\lib\site-packages\tensorflow_core\python\keras\engine\training_arrays.py", line 189, in model_iteration
    f = _make_execution_function(model, mode)
  File "D:\python36\lib\site-packages\tensorflow_core\python\keras\engine\training_arrays.py", line 566, in _make_execution_function
    return model._make_execution_function(mode)
  File "D:\python36\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 2189, in _make_execution_function
    self._make_predict_function()
  File "D:\python36\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 2179, in _make_predict_function
    **kwargs)
  File "D:\python36\lib\site-packages\tensorflow_core\python\keras\backend.py", line 3678, in function
    return GraphExecutionFunction(inputs, outputs, updates=updates, **kwargs)
  File "D:\python36\lib\site-packages\tensorflow_core\python\keras\backend.py", line 3330, in __init__
    with ops.control_dependencies([self.outputs[0]]):
  File "D:\python36\lib\site-packages\tensorflow_core\python\framework\ops.py", line 5254, in control_dependencies
    return get_default_graph().control_dependencies(control_inputs)
  File "D:\python36\lib\site-packages\tensorflow_core\python\framework\ops.py", line 4688, in control_dependencies
    c = self.as_graph_element(c)
  File "D:\python36\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3607, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "D:\python36\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3686, in _as_graph_element_locked
    raise ValueError("Tensor %s is not an element of this graph." % obj)
ValueError: Tensor Tensor("global_average_pooling2d_1/Mean:0", shape=(?, 2048), dtype=float32) is not an element of this graph.
```
System information

Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
OS Platform and Distribution (e.g., Linux Ubuntu 16.04):win10 64
TensorFlow installed from (source or binary):pip
TensorFlow version (use command below):1.14
Python version: 3.6.8
CUDA/cuDNN version: NO
GPU model and memory: No GPU
Could you pls help me ?
thx

**Comment by Saduf2019** [comment]
@ucasiggcas 
I ran the above code on 1.15 and 1.14, i do not face any errors as reported above. Please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/347f91e4692c022ab6be5d59ba7cadf6/untitled179.ipynb).
Is there any particular reason ti use old version of tf, can you please upgrade to a later version and see if that helps.

**Comment by ucasiggcas** [comment]
hi,dear
I have tried again the 1.15 version
also has the same problem

**Comment by ucasiggcas** [comment]
and the 1.14 version either
Cuda 10.1
GPU 2080Ti
python 3.7.7

**Comment by Saduf2019** [comment]
I am able to replicate the issue, please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/45d21ec0a96503951934466ee257e8e5/untitled178.ipynb)

**Comment by ymodak** [comment]
This works successfully with TF 2.X
Unfortunately we are not accepting any changes with TF 1.X versions unless it calls for security issues.

**Comment by ucasiggcas** [comment]
it's a big pitty.

**Comment by ymodak** [comment]
Closing this issue now. Thanks!
