### ISSUE TITLE
Error after running the program

### ISSUE THREAD

**Issue by Monsieurvishal** [tensorflow/tensorflow#39499]
I ran this program to check if  Tensorflow is installed or not in jupyter notebook. And Got the following error.

import tensorflow as tf
hello = tf.constant('Hello, TensorFlow!')
sess = tf.Session()
print(sess.run(hello))

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

Traceback (most recent call last):
  File "C:\Users\Vishal\Anaconda3\New\lib\site-packages\IPython\core\interactiveshell.py", line 3325, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-8-25b92e4d5dec>", line 2, in <module>
    hello = tf.constant('Hello, TensorFlow!')
AttributeError: module 'tensorflow' has no attribute 'constant'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Vishal\Anaconda3\New\lib\site-packages\IPython\core\interactiveshell.py", line 2039, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'AttributeError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Vishal\Anaconda3\New\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Vishal\Anaconda3\New\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 2453, in <module>
    from tensorflow.python.util import deprecation
  File "C:\Users\Vishal\Anaconda3\New\lib\site-packages\tensorflow_core\python\util\deprecation.py", line 25, in <module>
    from tensorflow.python.platform import tf_logging as logging
ImportError: cannot import name 'tf_logging' from 'tensorflow.python.platform' (C:\Users\Vishal\Anaconda3\New\lib\site-packages\tensorflow\python\platform\__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Vishal\Anaconda3\New\lib\site-packages\IPython\core\ultratb.py", line 1101, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "C:\Users\Vishal\Anaconda3\New\lib\site-packages\IPython\core\ultratb.py", line 319, in wrapped
    return f(*args, **kwargs)
  File "C:\Users\Vishal\Anaconda3\New\lib\site-packages\IPython\core\ultratb.py", line 353, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "C:\Users\Vishal\Anaconda3\New\lib\inspect.py", line 1502, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
  File "C:\Users\Vishal\Anaconda3\New\lib\inspect.py", line 1460, in getframeinfo
    filename = getsourcefile(frame) or getfile(frame)
  File "C:\Users\Vishal\Anaconda3\New\lib\inspect.py", line 696, in getsourcefile
    if getattr(getmodule(object, filename), '__loader__', None) is not None:
  File "C:\Users\Vishal\Anaconda3\New\lib\inspect.py", line 733, in getmodule
    if ismodule(module) and hasattr(module, '__file__'):
  File "C:\Users\Vishal\Anaconda3\New\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\Users\Vishal\Anaconda3\New\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "C:\Users\Vishal\Anaconda3\New\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Vishal\Anaconda3\New\lib\site-packages\tensorflow_core\__init__.py", line 42, in <module>
    from . _api.v2 import audio
  File "C:\Users\Vishal\Anaconda3\New\lib\site-packages\tensorflow_core\_api\v2\audio\__init__.py", line 10, in <module>
    from tensorflow.python.ops.gen_audio_ops import decode_wav
  File "C:\Users\Vishal\Anaconda3\New\lib\site-packages\tensorflow_core\python\ops\gen_audio_ops.py", line 9, in <module>
    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow
  File "C:\Users\Vishal\Anaconda3\New\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\Users\Vishal\Anaconda3\New\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "C:\Users\Vishal\Anaconda3\New\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\Vishal\Anaconda3\New\lib\site-packages\tensorflow_core\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Vishal\Anaconda3\New\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Vishal\Anaconda3\New\lib\site-packages\IPython\core\interactiveshell.py", line 3325, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-8-25b92e4d5dec>", line 2, in <module>
    hello = tf.constant('Hello, TensorFlow!')
AttributeError: module 'tensorflow' has no attribute 'constant'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Vishal\Anaconda3\New\lib\site-packages\IPython\core\interactiveshell.py", line 2039, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'AttributeError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Vishal\Anaconda3\New\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Vishal\Anaconda3\New\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 2453, in <module>
    from tensorflow.python.util import deprecation
  File "C:\Users\Vishal\Anaconda3\New\lib\site-packages\tensorflow_core\python\util\deprecation.py", line 25, in <module>
    from tensorflow.python.platform import tf_logging as logging
ImportError: cannot import name 'tf_logging' from 'tensorflow.python.platform' (C:\Users\Vishal\Anaconda3\New\lib\site-packages\tensorflow\python\platform\__init__.py)

Failed to load the native TensorFlow runtime.

**Comment by Saduf2019** [comment]
@Monsieurvishal 

Please refer to [link](https://stackoverflow.com/questions/51585095/module-tensorflow-has-no-attribute-constant), [link1](https://github.com/tensorflow/tensorflow/issues/3369#issuecomment-240217811), [link2](https://www.edureka.co/community/67232/attributeerror-module-tensorflow-has-attribute-constant), [link3](https://python-forum.io/Thread-Attribute-Error-while-using-tensor-flow)
#36167 (comment) [link4](https://www.itread01.com/content/1543048209.html) and let us know if this helps resolve yoir issue.

#36167 #36151 #36138 #36054 #36045 #36020 #36003 #35988 #35903 #35880 #35865 #35805 #35789 #35773 #35772 #35767 #35766 #35749 #35721 #35618 #35204


Also:
Workaround:
1.)Uninstall tensorflow from pip and pip3
sudo pip uninstall tensorflow
sudo pip3 uninstall tensorflow

2.)Uninstall python & python3 
sudo apt-get remove python-dev python3-dev python-pip python3-pip

3.)Install only a single version of  python(I used python 3)
sudo apt-get install python3-dev python3-pip

4.)Install tensorflow to python3
sudo pip3 install --upgrade pip

for non GPU tensorflow, run this command 

sudo pip3 install --upgrade tensorflow

for GPU tensorflow, run below command
sudo pip3 install --upgrade tensorflow-gpu

**Comment by Saduf2019** [comment]
what is the version of tensor flow you are trying to work with

**Comment by Monsieurvishal** [comment]
Today I downloaded latest version of TF , and I downgraded it to version 2  to check if problem persists

**Comment by Monsieurvishal** [comment]
Its very much confusing to install TF in my machine. Does Google collab has all feature so that i can learn  TF in Google collab?
