### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by Monsieurvishal** [tensorflow/tensorflow#39531]
import tensorflow as tf
tf.add(1, 2).numpy()

I ran the above code for non GPU version and got the following error.

ImportError                               Traceback (most recent call last)
~\Anaconda3\New\lib\site-packages\tensorflow\python\pywrap_tensorflow.py in <module>
     57 
---> 58   from tensorflow.python.pywrap_tensorflow_internal import *
     59 

~\Anaconda3\New\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py in <module>
     27             return _mod
---> 28     _pywrap_tensorflow_internal = swig_import_helper()
     29     del swig_import_helper

~\Anaconda3\New\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py in swig_import_helper()
     23             try:
---> 24                 _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
     25             finally:

~\Anaconda3\New\lib\imp.py in load_module(name, file, filename, details)
    241         else:
--> 242             return load_dynamic(name, filename, file)
    243     elif type_ == PKG_DIRECTORY:

~\Anaconda3\New\lib\imp.py in load_dynamic(name, path, file)
    341             name=name, loader=loader, origin=path)
--> 342         return _load(spec)
    343 

ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-4-79ec058b6a86> in <module>
----> 1 import tensorflow as tf
      2 tf.add(1, 2).numpy()

~\Anaconda3\New\lib\site-packages\tensorflow\__init__.py in <module>
     39 import sys as _sys
     40 
---> 41 from tensorflow.python.tools import module_util as _module_util
     42 from tensorflow.python.util.lazy_loader import LazyLoader as _LazyLoader
     43 

~\Anaconda3\New\lib\site-packages\tensorflow\python\__init__.py in <module>
     48 import numpy as np
     49 
---> 50 from tensorflow.python import pywrap_tensorflow
     51 
     52 # Protocol buffers

~\Anaconda3\New\lib\site-packages\tensorflow\python\pywrap_tensorflow.py in <module>
     67 for some common reasons and solutions.  Include the entire stack trace
     68 above this error message when asking for help.""" % traceback.format_exc()
---> 69   raise ImportError(msg)
     70 
     71 # pylint: enable=wildcard-import,g-import-not-at-top,unused-import,line-too-long

ImportError: Traceback (most recent call last):
  File "C:\Users\Vishal\Anaconda3\New\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Vishal\Anaconda3\New\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Vishal\Anaconda3\New\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Vishal\Anaconda3\New\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Vishal\Anaconda3\New\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

Failed to load the native TensorFlow runtime.

I upgraded it

(base) C:\Users\Vishal>pip install --upgrade tensorflow
Collecting tensorflow
  Using cached https://files.pythonhosted.org/packages/af/50/d7da24189d95e2084bb1cc350a8e4acdf1b0c9b3d57def7a348f0d9cb062/tensorflow-2.2.0-cp37-cp37m-win_amd64.whl
Requirement already satisfied, skipping upgrade: grpcio>=1.8.6 in c:\users\vishal\anaconda3\new\lib\site-packages (from tensorflow) (1.28.1)
Requirement already satisfied, skipping upgrade: keras-preprocessing>=1.1.0 in c:\users\vishal\anaconda3\new\lib\site-packages (from tensorflow) (1.1.0)
Requirement already satisfied, skipping upgrade: termcolor>=1.1.0 in c:\users\vishal\anaconda3\new\lib\site-packages (from tensorflow) (1.1.0)
Requirement already satisfied, skipping upgrade: wheel>=0.26; python_version >= "3" in c:\users\vishal\anaconda3\new\lib\site-packages (from tensorflow) (0.33.4)
Requirement already satisfied, skipping upgrade: astunparse==1.6.3 in c:\users\vishal\anaconda3\new\lib\site-packages (from tensorflow) (1.6.3)
Requirement already satisfied, skipping upgrade: google-pasta>=0.1.8 in c:\users\vishal\anaconda3\new\lib\site-packages (from tensorflow) (0.2.0)
Requirement already satisfied, skipping upgrade: h5py<2.11.0,>=2.10.0 in c:\users\vishal\anaconda3\new\lib\site-packages (from tensorflow) (2.10.0)
Requirement already satisfied, skipping upgrade: protobuf>=3.8.0 in c:\users\vishal\anaconda3\new\lib\site-packages (from tensorflow) (3.11.3)
Requirement already satisfied, skipping upgrade: six>=1.12.0 in c:\users\vishal\anaconda3\new\lib\site-packages (from tensorflow) (1.12.0)
Requirement already satisfied, skipping upgrade: wrapt>=1.11.1 in c:\users\vishal\anaconda3\new\lib\site-packages (from tensorflow) (1.11.2)
Requirement already satisfied, skipping upgrade: gast==0.3.3 in c:\users\vishal\anaconda3\new\lib\site-packages (from tensorflow) (0.3.3)
Requirement already satisfied, skipping upgrade: absl-py>=0.7.0 in c:\users\vishal\anaconda3\new\lib\site-packages (from tensorflow) (0.9.0)
Requirement already satisfied, skipping upgrade: tensorflow-estimator<2.3.0,>=2.2.0 in c:\users\vishal\anaconda3\new\lib\site-packages (from tensorflow) (2.2.0)
Requirement already satisfied, skipping upgrade: opt-einsum>=2.3.2 in c:\users\vishal\anaconda3\new\lib\site-packages (from tensorflow) (3.2.1)
Requirement already satisfied, skipping upgrade: numpy<2.0,>=1.16.0 in c:\users\vishal\anaconda3\new\lib\site-packages (from tensorflow) (1.16.4)
Requirement already satisfied, skipping upgrade: scipy==1.4.1; python_version >= "3" in c:\users\vishal\anaconda3\new\lib\site-packages (from tensorflow) (1.4.1)
Requirement already satisfied, skipping upgrade: tensorboard<2.3.0,>=2.2.0 in c:\users\vishal\anaconda3\new\lib\site-packages (from tensorflow) (2.2.1)
Requirement already satisfied, skipping upgrade: setuptools in c:\users\vishal\anaconda3\new\lib\site-packages (from protobuf>=3.8.0->tensorflow) (41.0.1)
Requirement already satisfied, skipping upgrade: google-auth<2,>=1.6.3 in c:\users\vishal\anaconda3\new\lib\site-packages (from tensorboard<2.3.0,>=2.2.0->tensorflow) (1.14.3)
Requirement already satisfied, skipping upgrade: google-auth-oauthlib<0.5,>=0.4.1 in c:\users\vishal\anaconda3\new\lib\site-packages (from tensorboard<2.3.0,>=2.2.0->tensorflow) (0.4.1)
Requirement already satisfied, skipping upgrade: werkzeug>=0.11.15 in c:\users\vishal\anaconda3\new\lib\site-packages (from tensorboard<2.3.0,>=2.2.0->tensorflow) (0.15.4)
Requirement already satisfied, skipping upgrade: tensorboard-plugin-wit>=1.6.0 in c:\users\vishal\anaconda3\new\lib\site-packages (from tensorboard<2.3.0,>=2.2.0->tensorflow) (1.6.0.post3)
Requirement already satisfied, skipping upgrade: markdown>=2.6.8 in c:\users\vishal\anaconda3\new\lib\site-packages (from tensorboard<2.3.0,>=2.2.0->tensorflow) (3.2.2)
Requirement already satisfied, skipping upgrade: requests<3,>=2.21.0 in c:\users\vishal\anaconda3\new\lib\site-packages (from tensorboard<2.3.0,>=2.2.0->tensorflow) (2.22.0)
Requirement already satisfied, skipping upgrade: pyasn1-modules>=0.2.1 in c:\users\vishal\anaconda3\new\lib\site-packages (from google-auth<2,>=1.6.3->tensorboard<2.3.0,>=2.2.0->tensorflow) (0.2.8)
Requirement already satisfied, skipping upgrade: rsa<4.1,>=3.1.4 in c:\users\vishal\anaconda3\new\lib\site-packages (from google-auth<2,>=1.6.3->tensorboard<2.3.0,>=2.2.0->tensorflow) (4.0)
Requirement already satisfied, skipping upgrade: cachetools<5.0,>=2.0.0 in c:\users\vishal\anaconda3\new\lib\site-packages (from google-auth<2,>=1.6.3->tensorboard<2.3.0,>=2.2.0->tensorflow) (4.1.0)
Requirement already satisfied, skipping upgrade: requests-oauthlib>=0.7.0 in c:\users\vishal\anaconda3\new\lib\site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.3.0,>=2.2.0->tensorflow) (1.3.0)
Requirement already satisfied, skipping upgrade: importlib-metadata; python_version < "3.8" in c:\users\vishal\anaconda3\new\lib\site-packages (from markdown>=2.6.8->tensorboard<2.3.0,>=2.2.0->tensorflow) (0.17)
Requirement already satisfied, skipping upgrade: chardet<3.1.0,>=3.0.2 in c:\users\vishal\anaconda3\new\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.3.0,>=2.2.0->tensorflow) (3.0.4)
Requirement already satisfied, skipping upgrade: idna<2.9,>=2.5 in c:\users\vishal\anaconda3\new\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.3.0,>=2.2.0->tensorflow) (2.8)
Requirement already satisfied, skipping upgrade: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\vishal\anaconda3\new\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.3.0,>=2.2.0->tensorflow) (1.24.2)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in c:\users\vishal\anaconda3\new\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.3.0,>=2.2.0->tensorflow) (2019.6.16)
Requirement already satisfied, skipping upgrade: pyasn1<0.5.0,>=0.4.6 in c:\users\vishal\anaconda3\new\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth<2,>=1.6.3->tensorboard<2.3.0,>=2.2.0->tensorflow) (0.4.8)
Requirement already satisfied, skipping upgrade: oauthlib>=3.0.0 in c:\users\vishal\anaconda3\new\lib\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.3.0,>=2.2.0->tensorflow) (3.1.0)
Requirement already satisfied, skipping upgrade: zipp>=0.5 in c:\users\vishal\anaconda3\new\lib\site-packages (from importlib-metadata; python_version < "3.8"->markdown>=2.6.8->tensorboard<2.3.0,>=2.2.0->tensorflow) (0.5.1)
Installing collected packages: tensorflow
  Found existing installation: tensorflow 2.0.0
    Uninstalling tensorflow-2.0.0:
      Successfully uninstalled tensorflow-2.0.0
Successfully installed tensorflow-2.2.0

(base) C:\Users\Vishal>

**Comment by Monsieurvishal** [comment]
I started using google colab which is great.
Thank you
