### ISSUE TITLE
Tensorflow 2.1.0 on Windows: No OpKernel was registered to support Op 'SparseMatMul'

### ISSUE THREAD

**Issue by zhuo931077127** [tensorflow/tensorflow#39533]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): 
- TensorFlow version: 2.1.0
- Python version: 3.6.0
- Installed using virtualenv? pip? conda?: conda
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 
- GPU model and memory: 

**Describe the problem**

When I run the following codes: 

```
    def _call(self, inputs):
        x = inputs

        # dropout
        if self.sparse_inputs:
            x = sparse_dropout(x, 1 - self.dropout, self.num_features_nonzero)
        else:
            x = tf.nn.dropout(x, 1 - self.dropout)

        # convolve
        supports = tf.matmul(tf.sparse_tensor_to_dense(self.support[0]), tf.diag(self.vars['kernel']), a_is_sparse=True,
                             b_is_sparse=True)
        supports = tf.matmul(supports, tf.sparse_tensor_to_dense(self.support[1]), a_is_sparse=True, b_is_sparse=True)
        pre_sup = dot(x, self.vars['weights_' + str(0)], sparse=self.sparse_inputs)
        output = dot(supports, pre_sup)

        if self.bias:
            output += self.vars['bias']

        return self.act(output)
```

The following error:
```
Traceback (most recent call last):
  File "C:\Users\zhuowei\Anaconda3\lib\site-packages\tensorflow_core\python\client\session.py", line 1367, in _do_call
    return fn(*args)
  File "C:\Users\zhuowei\Anaconda3\lib\site-packages\tensorflow_core\python\client\session.py", line 1350, in _run_fn
    self._extend_graph()
  File "C:\Users\zhuowei\Anaconda3\lib\site-packages\tensorflow_core\python\client\session.py", line 1390, in _extend_graph
    tf_session.ExtendSession(self._session)
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'SparseMatMul' used by {{node wavelet_convolution_1/MatMul}}with these attrs: [transpose_b=false, Ta=DT_FLOAT, Tb=DT_FLOAT, b_is_sparse=true, a_is_sparse=true, transpose_a=false]
Registered devices: [CPU, GPU]
Registered kernels:
  <no registered kernels>

	 [[wavelet_convolution_1/MatMul]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/zhuowei/Desktop/GAdv/GWNN-master/GraphWaveletNetwork/train.py", line 128, in <module>
    sess.run(tf.global_variables_initializer())
  File "C:\Users\zhuowei\Anaconda3\lib\site-packages\tensorflow_core\python\client\session.py", line 960, in run
    run_metadata_ptr)
  File "C:\Users\zhuowei\Anaconda3\lib\site-packages\tensorflow_core\python\client\session.py", line 1183, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\zhuowei\Anaconda3\lib\site-packages\tensorflow_core\python\client\session.py", line 1361, in _do_run
    run_metadata)
  File "C:\Users\zhuowei\Anaconda3\lib\site-packages\tensorflow_core\python\client\session.py", line 1386, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'SparseMatMul' used by node wavelet_convolution_1/MatMul (defined at \Users\zhuowei\Desktop\GAdv\GWNN-master\GraphWaveletNetwork\layers.py:320) with these attrs: [transpose_b=false, Ta=DT_FLOAT, Tb=DT_FLOAT, b_is_sparse=true, a_is_sparse=true, transpose_a=false]
Registered devices: [CPU, GPU]
Registered kernels:
  <no registered kernels>

	 [[wavelet_convolution_1/MatMul]]

Process finished with exit code 1
```

`SparseMatMul ` op is unavailable on GPU?

**Comment by Saduf2019** [comment]
@zhuo931077127 
Can you please check if you have compatibility issues with tensorflow as per [this comment](https://github.com/sampepose/flownet2-tf/issues/17#issuecomment-350424046) and [this comment](https://github.com/tensorflow/tensorflow/issues/22699#issuecomment-431107100), also please refer to this [link](https://stackoverflow.com/questions/47040860/cannot-run-tensorflow-on-gpu)
AS i ran the code shared by you on tf 2.1 and do not face any error, please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/38edcfdaf01b97765221b03504a87901/39533.ipynb)

**Comment by zhuo931077127** [comment]
@Saduf2019 I ran the code on tf1.10, and this error disappeared.
