### ISSUE TITLE
Getting error saved model to tflite - Float 64 error

### ISSUE THREAD

**Issue by vissood** [tensorflow/tensorflow#39604]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac OS
- TensorFlow installed from (source or binary): binary
- TensorFlow version (or github SHA if from source): 2.2.0

**Command used to run the converter or code if you’re using the Python API**
If possible, please share a link to Colab/Jupyter/any notebook.

```
# Copy and paste here the exact command
converter = tf.lite.TFLiteConverter.from_saved_model(model_file_pb)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
tflite_model = converter.convert()

```
**The output from the converter invocation**
ERROR
``` 
# Copy and paste the output here.

To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-05-16 20:04:12.645740: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7f98f6906430 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-05-16 20:04:12.645752: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-05-16 20:04:12.885160: I tensorflow/cc/saved_model/loader.cc:234] Restoring SavedModel bundle.
2020-05-16 20:04:13.539394: I tensorflow/cc/saved_model/loader.cc:183] Running initialization op on SavedModel bundle at path: MODEL/PB/64/tf_i11_v210/
2020-05-16 20:04:13.765676: I tensorflow/cc/saved_model/loader.cc:364] SavedModel load for tags { serve }; Status: success: OK. Took 1183597 microseconds.
error: type of return operand 2 ('tensor<?x400xf32>') doesn't match function result type ('tensor<?x400xf64>')
Traceback (most recent call last):
  File "/Users/visood/opt/anaconda3/bin/toco_from_protos", line 8, in <module>
    sys.exit(main())
  File "/Users/visood/opt/anaconda3/lib/python3.7/site-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 93, in main
    app.run(main=execute, argv=[sys.argv[0]] + unparsed)
  File "/Users/visood/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/Users/visood/opt/anaconda3/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/Users/visood/opt/anaconda3/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/Users/visood/opt/anaconda3/lib/python3.7/site-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 56, in execute
    enable_mlir_converter)
Exception: <unknown>:0: error: type of return operand 2 ('tensor<?x400xf32>') doesn't match function result type ('tensor<?x400xf64>')
<unknown>:0: note: see current operation: "std.return"(%12, %11, %13, %14, %15) : (tensor<?x400xf64>, tensor<?x1x400xf64>, tensor<?x400xf32>, tensor<?x400xf32>, tensor<f32>) -> ()
```
**Also, please include a link to the saved model or GraphDef**
https://github.com/vissood/resources/tree/master/TFLITE_ISSUE
```
# Put link here or attach to the issue.
```

**Failure details**
If the conversion is successful, but the generated model is wrong,
state what is wrong:
- Producing wrong results and/or decrease in accuracy
- Producing correct results, but the model is slower than expected (model generated from old converter)

**RNN conversion support**
If converting TF RNN to TFLite fused RNN ops, please prefix [RNN] in the title.

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by daverim** [comment]
Hi @vissood,
Many TFLite builtin ops don't support float64  as an input type. This is on the map however, @abattery  might be able to give more of an update.

**Comment by amahendrakar** [comment]
@vissood,
I am facing an error stating `ValueError: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /content/saved_model/1/variables/variables: Not found: /content/saved_model/1/variables; No such file or directory` on running the code. 
Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/efc55572411528527be94efaddb5c4c1/39604.ipynb).

In order to expedite the trouble-shooting process, could you please share all the files in the saved model folder. Thanks!
