### ISSUE TITLE
Unable to import Tensor Flow - Windows10

### ISSUE THREAD

**Issue by nikhilg108** [tensorflow/tensorflow#39685]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): binary
- TensorFlow version:Tensor flow 2.1
- Python version:Python 3.7.7
- Installed using virtualenv? pip? conda?: virtualenv
- Bazel version (if compiling from source):NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version:Cuda 10.2.89
- GPU model and memory:NVidia GE Force GTX1050

**Describe the problem**
I have tried installing tensor flow from both conda as well pip and also tried creating venv.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
Typed std command: 
python -c "import tensorflow as tf;print(tf.reduce_sum(tf.random.normal([1000, 1000])))

**Any other info / logs**
(venv) C:\Users\Shree>python -c "import tensorflow as tf;print(tf.reduce_sum(tf.random.normal([1000, 1000])))
Traceback (most recent call last):
  File "C:\Users\Shree\anaconda3\envs\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Shree\anaconda3\envs\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Shree\anaconda3\envs\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Shree\anaconda3\envs\venv\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Shree\anaconda3\envs\venv\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Shree\anaconda3\envs\venv\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\Shree\anaconda3\envs\venv\lib\site-packages\tensorflow\python\__init__.py", line 50, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Shree\anaconda3\envs\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 69, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Shree\anaconda3\envs\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Shree\anaconda3\envs\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Shree\anaconda3\envs\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Shree\anaconda3\envs\venv\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Shree\anaconda3\envs\venv\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

Failed to load the native TensorFlow runtime.

Please help me in resolving issue.

**Comment by amahendrakar** [comment]
@nikhilg108,
Please take a look at [this comment](https://github.com/tensorflow/tensorflow/issues/36167#issuecomment-577886156) from a similar issue and let us know if it helps. Thanks!

**Comment by mihaimaruseac** [comment]
Closing as duplicate.

https://github.com/tensorflow/tensorflow/issues/36167#issuecomment-577886156

Just to sample over 100 similar issues: #36167 #36151 #36138 #36054 #36045 #36020 #36003 #35988 #35903 #35880 #35865 #35805 #35789 #35773 #35772 #35767 #35766 #35749 #35721 #35618 #35204

Please make sure you do a search in the future.
