### ISSUE TITLE
Trying to run l08c09_forecasting_with_cnn.ipynb on spyder: "WARNING:tensorflow:AutoGraph could not transform <function seq2seq_window_dataset.<locals>.<lambda> at 0x0000024D6C641D38> and will run it as-is."

### ISSUE THREAD

**Issue by pedromspereira** [tensorflow/tensorflow#39693]
**System information**
- I am using a stock example script provided in Google Colab
https://colab.research.google.com/github/tensorflow/examples/blob/master/courses/udacity_intro_to_tensorflow_for_deep_learning/l08c09_forecasting_with_cnn.ipynb#scrollTo=PgYwn9VM8OJi

- OS Platform and Distribution: Windows 10

- TensorFlow installed from (source or binary): installed using pip
- TensorFlow version (use command below): tf-nightly
- Python version: 3.7.6
- GPU model and memory: GTX-1060

**Describe the current behavior**

Trying to reproduce script from google colab in my PC using Spyder 4.

**Describe the expected behavior**

WARNING: AutoGraph could not transform <function seq2seq_window_dataset.<locals>.<lambda> at 0x0000024D6A385EE8> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 
Traceback (most recent call last):

  File "C:\Users\pedro\OneDrive\Área de Trabalho\keras_BTC_cnn.py", line 131, in <module>
    callbacks=[early_stopping, model_checkpoint])

  File "C:\Anaconda3\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 819, in fit
    use_multiprocessing=use_multiprocessing)

  File "C:\Anaconda3\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py", line 235, in fit
    use_multiprocessing=use_multiprocessing)

  File "C:\Anaconda3\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py", line 614, in _process_training_inputs
    distribution_strategy=distribution_strategy)

  File "C:\Anaconda3\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py", line 706, in _process_inputs
    use_multiprocessing=use_multiprocessing)

  File "C:\Anaconda3\lib\site-packages\tensorflow_core\python\keras\engine\data_adapter.py", line 702, in __init__
    x = standardize_function(x)

  File "C:\Anaconda3\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py", line 684, in standardize_function
    return dataset.map(map_fn, num_parallel_calls=dataset_ops.AUTOTUNE)

  File "C:\Anaconda3\lib\site-packages\tensorflow_core\python\data\ops\dataset_ops.py", line 1591, in map
    self, map_func, num_parallel_calls, preserve_cardinality=True)

  File "C:\Anaconda3\lib\site-packages\tensorflow_core\python\data\ops\dataset_ops.py", line 3926, in __init__
    use_legacy_function=use_legacy_function)

  File "C:\Anaconda3\lib\site-packages\tensorflow_core\python\data\ops\dataset_ops.py", line 3147, in __init__
    self._function = wrapper_fn._get_concrete_function_internal()

  File "C:\Anaconda3\lib\site-packages\tensorflow_core\python\eager\function.py", line 2395, in _get_concrete_function_internal
    *args, **kwargs)

  File "C:\Anaconda3\lib\site-packages\tensorflow_core\python\eager\function.py", line 2389, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)

  File "C:\Anaconda3\lib\site-packages\tensorflow_core\python\eager\function.py", line 2703, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)

  File "C:\Anaconda3\lib\site-packages\tensorflow_core\python\eager\function.py", line 2593, in _create_graph_function
    capture_by_value=self._capture_by_value),

  File "C:\Anaconda3\lib\site-packages\tensorflow_core\python\framework\func_graph.py", line 978, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)

  File "C:\Anaconda3\lib\site-packages\tensorflow_core\python\data\ops\dataset_ops.py", line 3140, in wrapper_fn
    ret = _wrapper_helper(*args)

  File "C:\Anaconda3\lib\site-packages\tensorflow_core\python\data\ops\dataset_ops.py", line 3082, in _wrapper_helper
    ret = autograph.tf_convert(func, ag_ctx)(*nested_args)

  File "C:\Anaconda3\lib\site-packages\tensorflow_core\python\autograph\impl\api.py", line 237, in wrapper
    raise e.ag_error_metadata.to_exception(e)

ValueError: in converted code:

    C:\Anaconda3\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py:677 map_fn
        batch_size=None)
    C:\Anaconda3\lib\site-packages\tensorflow_core\python\keras\engine\training.py:2410 _standardize_tensors
        exception_prefix='input')
    C:\Anaconda3\lib\site-packages\tensorflow_core\python\keras\engine\training_utils.py:573 standardize_input_data
        'with shape ' + str(data_shape))

    ValueError: Error when checking input: expected input_1 to have 3 dimensions, but got array with shape (None, None)

**Standalone code to reproduce the issue**
Link above

**Comment by amahendrakar** [comment]
@pedromspereira,
I was able to run the code without any issues with the stable version TF v2.2. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/1806d4cb11f6389cbc963a2aae4df1f9/39693.ipynb).

Could you please check if you are able to run the code with TF v2.2. Thanks!

**Comment by pedromspereira** [comment]
Tf 2.2 gives me the same problem as ticket https://github.com/tensorflow/tensorflow/issues/22512

had to move back to tf 2.0

now when running this part of the code:

history = model.fit(train_set, epochs=500,
                    validation_data=valid_set,
                    callbacks=[early_stopping, model_checkpoint])

I get the following error:

Epoch 1/500
      1/Unknown - 0s 7ms/stepWARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: 
WARNING:tensorflow:Can save best model only with val_loss available, skipping.
      1/Unknown - 0s 9ms/stepTraceback (most recent call last):

  File "<ipython-input-17-aa1ecd95da91>", line 3, in <module>
    callbacks=[early_stopping, model_checkpoint])

  File "C:\Anaconda3\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 728, in fit
    use_multiprocessing=use_multiprocessing)

  File "C:\Anaconda3\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py", line 324, in fit
    total_epochs=epochs)

  File "C:\Anaconda3\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py", line 123, in run_one_epoch
    batch_outs = execution_function(iterator)

  File "C:\Anaconda3\lib\site-packages\tensorflow_core\python\keras\engine\training_v2_utils.py", line 86, in execution_function
    distributed_function(input_fn))

  File "C:\Anaconda3\lib\site-packages\tensorflow_core\python\eager\def_function.py", line 457, in __call__
    result = self._call(*args, **kwds)

  File "C:\Anaconda3\lib\site-packages\tensorflow_core\python\eager\def_function.py", line 487, in _call
    return self._stateless_fn(*args, **kwds)  # pylint: disable=not-callable

  File "C:\Anaconda3\lib\site-packages\tensorflow_core\python\eager\function.py", line 1823, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access

  File "C:\Anaconda3\lib\site-packages\tensorflow_core\python\eager\function.py", line 1141, in _filtered_call
    self.captured_inputs)

  File "C:\Anaconda3\lib\site-packages\tensorflow_core\python\eager\function.py", line 1224, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager)

  File "C:\Anaconda3\lib\site-packages\tensorflow_core\python\eager\function.py", line 511, in call
    ctx=ctx)

  File "C:\Anaconda3\lib\site-packages\tensorflow_core\python\eager\execute.py", line 76, in quick_execute
    raise e

  File "C:\Anaconda3\lib\site-packages\tensorflow_core\python\eager\execute.py", line 61, in quick_execute
    num_outputs)

TypeError: An op outside of the function building code is being passed
a "Graph" tensor. It is possible to have Graph tensors
leak out of the function building context by including a
tf.init_scope in your function building code.
For example, the following function will fail:
  @tf.function
  def has_init_scope():
    my_constant = tf.constant(1.)
    with tf.init_scope():
      added = my_constant * 2
The graph tensor has name: ^sequential/conv1d/BiasAdd/ReadVariableOp:0

**Comment by amahendrakar** [comment]
> * I am using a stock example script provided in Google Colab
>   https://colab.research.google.com/github/tensorflow/examples/blob/master/courses/udacity_intro_to_tensorflow_for_deep_learning/l08c09_forecasting_with_cnn.ipynb#scrollTo=PgYwn9VM8OJi

@pedromspereira,
Please try running this code in a virtual environment with TF v2.2 and let us know if you are facing the same issue. Thanks!

**Comment by pedromspereira** [comment]
now it worked, many thanks
