### ISSUE TITLE
tf.contrib.metrics.streaming_auc evaluation exception

### ISSUE THREAD

**Issue by xinyuwuhenZZ** [tensorflow/tensorflow#3971]
I used `tf.contrib.metrics.streaming_auc` to evaluate DNN rank model, 

```
auc,  opts = tf.contrib.metrics.streaming_auc(logits, labels)
```

`logits` are my predicted results, `labels` are true labels, they have format:

```
Tensor("Sigmoid:0", shape=(100, 1), dtype=float32)
Tensor("labels_placeholder:0", shape=(100, ?), dtype=float32)
```

Errors as following:
```
Traceback (most recent call last):
  File "/Users/nali/Workspace/tensorflow_example/search_click/MLP.py", line 200, in <module>
    dnn.run(training_data=[x, y], epochs=10)
  File "/Users/nali/Workspace/tensorflow_example/search_click/MLP.py", line 135, in run
    feed_dict={self.x: x[samples], self.y: y[samples]})
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 372, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 636, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 708, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 728, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors.FailedPreconditionError: Attempting to use uninitialized value auc/true_positives
	 [[Node: auc/true_positives/read = Identity[T=DT_FLOAT, _class=["loc:@auc/true_positives"], _device="/job:localhost/replica:0/task:0/cpu:0"](auc/true_positives)]]
Caused by op u'auc/true_positives/read', defined at:
  File "/Users/nali/Workspace/tensorflow_example/search_click/MLP.py", line 200, in <module>
    dnn.run(training_data=[x, y], epochs=10)
  File "/Users/nali/Workspace/tensorflow_example/search_click/MLP.py", line 126, in run
    cross_entropy, accuracy, logits = self.training()
  File "/Users/nali/Workspace/tensorflow_example/search_click/MLP.py", line 100, in training
    accuracy = self.evaluation(logits, self.y)
  File "/Users/nali/Workspace/tensorflow_example/search_click/MLP.py", line 146, in evaluation
    auc, opt = tf.contrib.metrics.streaming_auc(logits, labels)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/contrib/metrics/python/ops/metric_ops.py", line 718, in streaming_auc
    predictions, labels, thresholds, ignore_mask)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/contrib/metrics/python/ops/metric_ops.py", line 600, in _tp_fn_tn_fp
    true_positives = _create_local('true_positives', shape=[num_thresholds])
  File "/usr/local/lib/python2.7/site-packages/tensorflow/contrib/metrics/python/ops/metric_ops.py", line 75, in _create_local
    collections=collections)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/variables.py", line 211, in __init__
    dtype=dtype)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/variables.py", line 319, in _init_from_args
    self._snapshot = array_ops.identity(self._variable, name="read")
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 831, in identity
    result = _op_def_lib.apply_op("Identity", input=input, name=name)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/op_def_library.py", line 704, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2260, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1230, in __init__
    self._traceback = _extract_stack()
```

Thanks in advance.

**Comment by prb12** [comment]
This looks like you failed to initialize some of the variables in your model?

It seems like the uninitialized variable is a LOCAL_VARIABLE created [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/metrics/python/ops/metric_ops.py#L708)

I think this requires you to call tf.initialize_all_variables() and tf.initialize_local_variables()   (see #1045)

**Comment by martinwicke** [comment]
@prb12 is correct, you have to call tf.initialize_local_variables(), since local variables are not part of all variables. Yes, we know how silly that sounds, and we're working on it.

If you use an Estimator, the initialization should be taken care of for you.

**Comment by isaacgerg** [comment]
@martinwicke So what exactly is the fix for this?  Do i call tf.initialize_local_variables() before calling auc,  opts = tf.contrib.metrics.streaming_auc(logits, labels)?

**Comment by martinwicke** [comment]
You have to call tf.initialize_local_variables().eval() once before you start calling streaming_auc. Every time you call initialize_local_variables().eval() it will reset your auc.

**Comment by isaacgerg** [comment]
Python is telling me Operation object has no attribute eval for 
tf.initialize_local_variables().eval()

**Comment by martinwicke** [comment]
sorry, .run()​

**Comment by isaacgerg** [comment]
K.get_session().run(tf.initialize_local_variables().run())

Gives me
builtins.ValueError: Cannot execute operation using `run()`: No default session is registered. Use `with sess.as_default():` or pass an explicit session to `run(session=sess)`

**Comment by martinwicke** [comment]
I don't know what K.get_session() does, but have you tried making and
passing a session (or using a with statement) as suggested?

**Comment by marimarimarimari** [comment]
You may try the following hack:

1. Define a `callback` which runs `keras.backend.get_session().run(tf.initialize_local_variables())` on each epoch begin.:

       class ResetLocalVariables(keras.callbacks.Callback):
            def on_epoch_begin(self, logs={}):
                keras.backend.get_session().run(tf.initialize_local_variables())

2. Add it to your loss function:

        model.fit(..., callbacks=[.... , ResetLocalVariables()], ...)

**Comment by isaacgerg** [comment]
thanks.  Can someone close?

**Comment by isaacgerg** [comment]
@marimarimarimari I dont think this will work because update_op does the accumalation step and there's no way to get that into the metrics function in keras because y_pred and y_true are not given to you before execution.

**Comment by sobhannp** [comment]
You need to call tf.initialize_local_variables().run() AFTER you call tf.contrib.metrics.streaming_auc() and BEFORE you call a session.run().

I hope it helps.
