### ISSUE TITLE
SciSharp.TensorFlow.Redist-Windows-GPU missing for tf.net 0.20.0-alpha

### ISSUE THREAD

**Issue by SuneGram** [tensorflow/tensorflow#39710]
**Problem**

Is there a SciSharp.TensorFlow.Redist-Windows-GPU (tensorflow.dll) distribution available for Tensorflow.NET 0.20.0-alpha?

The most resent NuGet package available seems to be v. 1.15.1, which does not seem to be compatible with Tensorflow.NET 0.20.0-alpha.

When could a working redistributable be expected?
Is it possible to download it or build it manually? (please provide steps)

**Any other info / logs**
The following exception is thrown when trying to use SciSharp.TensorFlow.Redist-Windows-GPU version v. 1.15.1 with Tensorflow.NET 0.20.0-alpha:

System.TypeInitializationException: The type initializer for 'Tensorflow.Binding' threw an exception. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.EntryPointNotFoundException: Unable to find an entry point named 'VSpace_Handle' in DLL 'tensorflow'.
    at Tensorflow.c_api.VSpace_Handle(VSpace_callback_Ones ones, VSpace_callback_AggregateGrads aggregate_grads)
   at Tensorflow.tensorflow.InitGradientEnvironment()
--- End of inner exception stack trace ---
    at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance[T]()
   at Tensorflow.Binding.New[T]()
   at Tensorflow.Binding..cctor()
--- End of inner exception stack trace ---
    at Tensorflow.Binding.get_tf()

**Comment by GeorgeS2019** [comment]
@SG-AI Latest [tensorflow.dll ](https://github.com/tensorflow/tensorflow/issues/35405#issuecomment-653621878)for c# api
