### ISSUE TITLE
tf.keras.layers.Embedding convert error

### ISSUE THREAD

**Issue by adonisues** [tensorflow/tensorflow#39739]
**System information**
- Linux Ubuntu 16.04):
- tf-nightly

Hello, 
I have problem when converting "tf.keras.layers.Embedding".
"from_keras_model" works well but   "from_saved_model" doesn't. 

**Code**
```
embed_model = tf.keras.models.Sequential([ 
    tf.keras.layers.Embedding(10, 10)
])
dinput1 = np.random.randint([1],10)
out=embed_model(dinput1)

MODEL_DIR = "embed_model"
embed_model.save(MODEL_DIR, save_format="tf" )
converter = tf.lite.TFLiteConverter.from_saved_model(MODEL_DIR) 
#converter = tf.lite.TFLiteConverter.from_keras_model(embed_model)

converter.experimental_new_converter = True
tflite_embed_model = converter.convert()

open("dec_model.tflite", "wb").write(tflite_embed_model)
```

**Error Log**
Traceback (most recent call last):
  File "/local1/sshwang/virtual_envs/pytorch_1/lib/python3.5/site-packages/tensorflow/lite/python/convert.py", line 180, in toco_convert_protos
    enable_mlir_converter)
  File "/local1/sshwang/virtual_envs/pytorch_1/lib/python3.5/site-packages/tensorflow/lite/python/wrap_toco.py", line 38, in wrapped_toco_convert
    enable_mlir_converter)
Exception: Failed to find function '__inference__wrapped_model_251'. The imported TensorFlow GraphDef is ill-formed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "embedding_model.py", line 21, in <module>
    tflite_embed_model = converter.convert()
  File "/local1/sshwang/virtual_envs/pytorch_1/lib/python3.5/site-packages/tensorflow/lite/python/lite.py", line 920, in convert
    return super(TFLiteConverterV2, self).convert()
  File "/local1/sshwang/virtual_envs/pytorch_1/lib/python3.5/site-packages/tensorflow/lite/python/lite.py", line 752, in convert
    self).convert(graph_def, input_tensors, output_tensors)
  File "/local1/sshwang/virtual_envs/pytorch_1/lib/python3.5/site-packages/tensorflow/lite/python/lite.py", line 498, in convert
    **converter_kwargs)
  File "/local1/sshwang/virtual_envs/pytorch_1/lib/python3.5/site-packages/tensorflow/lite/python/convert.py", line 555, in toco_convert_impl
    enable_mlir_converter=enable_mlir_converter)
  File "/local1/sshwang/virtual_envs/pytorch_1/lib/python3.5/site-packages/tensorflow/lite/python/convert.py", line 183, in toco_convert_protos
    raise ConverterError(str(e))
tensorflow.lite.python.convert.ConverterError: Failed to find function '__inference__wrapped_model_251'. The imported TensorFlow GraphDef is ill-formed.

**Comment by amahendrakar** [comment]
@adonisues,
I am facing a different error stating `ValueError: None is only supported in the 1st dimension. Tensor 'embedding_1_input' has invalid shape '[None, None]'.` Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/68f00eb3ba79b4a412d66794777ca9b0/39739.ipynb#scrollTo=43DsjLFZ5y2Y).

Could you please provide the complete code to reproduce the issue reported here. Thanks!

**Comment by jvishnuvardhan** [comment]
@adonisues As you are using `model.save`, you need to use `from_keras_model`. Once you update that part of code, then everything works as expected. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/958ea1a4e069c7221b1c4e6da1a33ffe/39739.ipynb). 

Please verify once and close the issue if this was resolved for you. Thanks!
