### ISSUE TITLE
applications_load_weight_test testcases fail on s390x architecture

### ISSUE THREAD

**Issue by rposts** [tensorflow/tensorflow#39754]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution: Ubuntu 18.04 on s390x architecture
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): v2.2.0-0-g2b96f3662b 2.2.0
- Python version: Python 3.6.9
- Bazel version (if compiling from source): bazel 2.0.0- (@non-git)
- GCC/Compiler version (if compiling from source):  gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
`applications_load_weight_test` testcases fail on s390x architecture due to incompatible Keras applications models.  It appears that `h5py` fails to find `Conversion function` for `CSET H5T_CSET_ASCII` data types.  Error in the logs take the form of:
```
[  SKIPPED ] ApplicationsLoadWeightTest.test_session
======================================================================
ERROR: test_application_pretrained_weights_loading (__main__.ApplicationsLoadWeightTest)
test_application_pretrained_weights_loading (__main__.ApplicationsLoadWeightTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/334416e3a0381b53511e68de49f4ac07/execroot/org_tensorflow/bazel-out/s390x-opt/bin/tensorflow/python/keras/applications/applications_load_weight_test_resnet_v2.runfiles/org_tensorflow/tensorflow/python/keras/applications/applications_load_weight_test.py", line 104, in test_application_pretrained_weights_loading
    model = app(weights='imagenet')
  File "/root/.cache/bazel/_bazel_root/334416e3a0381b53511e68de49f4ac07/execroot/org_tensorflow/bazel-out/s390x-opt/bin/tensorflow/python/keras/applications/applications_load_weight_test_resnet_v2.runfiles/org_tensorflow/tensorflow/python/keras/applications/resnet_v2.py", line 55, in ResNet50V2
    classifier_activation=classifier_activation,
  File "/root/.cache/bazel/_bazel_root/334416e3a0381b53511e68de49f4ac07/execroot/org_tensorflow/bazel-out/s390x-opt/bin/tensorflow/python/keras/applications/applications_load_weight_test_resnet_v2.runfiles/org_tensorflow/tensorflow/python/keras/applications/resnet.py", line 210, in ResNet
    model.load_weights(weights_path)
  File "/root/.cache/bazel/_bazel_root/334416e3a0381b53511e68de49f4ac07/execroot/org_tensorflow/bazel-out/s390x-opt/bin/tensorflow/python/keras/applications/applications_load_weight_test_resnet_v2.runfiles/org_tensorflow/tensorflow/python/keras/engine/training.py", line 250, in load_weights
    return super(Model, self).load_weights(filepath, by_name, skip_mismatch)
  File "/root/.cache/bazel/_bazel_root/334416e3a0381b53511e68de49f4ac07/execroot/org_tensorflow/bazel-out/s390x-opt/bin/tensorflow/python/keras/applications/applications_load_weight_test_resnet_v2.runfiles/org_tensorflow/tensorflow/python/keras/engine/network.py", line 1266, in load_weights
    hdf5_format.load_weights_from_hdf5_group(f, self.layers)
  File "/root/.cache/bazel/_bazel_root/334416e3a0381b53511e68de49f4ac07/execroot/org_tensorflow/bazel-out/s390x-opt/bin/tensorflow/python/keras/applications/applications_load_weight_test_resnet_v2.runfiles/org_tensorflow/tensorflow/python/keras/saving/hdf5_format.py", line 659, in load_weights_from_hdf5_group
    original_keras_version = f.attrs['keras_version'].decode('utf8')
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/usr/local/lib/python3.6/dist-packages/h5py/_hl/attrs.py", line 81, in __getitem__
    attr.read(arr, mtype=htype)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5a.pyx", line 355, in h5py.h5a.AttrID.read
  File "h5py/_proxy.pyx", line 50, in h5py._proxy.attr_rw
  File "h5py/_proxy.pyx", line 319, in h5py._proxy.needs_bkg_buffer
  File "h5py/_proxy.pyx", line 316, in h5py._proxy.needs_bkg_buffer
KeyError: 'Conversion function not found (no appropriate function for conversion path)'

----------------------------------------------------------------------
Ran 2 tests in 1.612s

FAILED (errors=1, skipped=1)
Failed to find converter for 8 -> b'PYTHON:OBJECT'

```

**Describe the expected behavior**

These testcases should pass on s390x architecture.

**Standalone code to reproduce the issue**
```
bazel --host_jvm_args="-Xms1024m" --host_jvm_args="-Xmx2048m" test  //tensorflow/python/keras/applications:applications_load_weight_test_resnet_v2
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

The problem appears when `h5py` tries to process keras application models downloaded to `~.keras/models/resnet50v2_weights_tf_dim_ordering_tf_kernels.h5`.  These models seem to be generated on x86 architecture and they fail to get past `h5py` process.  In particular, `original_keras_version = h5_file.file.attrs['keras_version'].decode('utf8')` [line ](https://github.com/tensorflow/tensorflow/blob/52fd23939e65699f8c7d53850a17daab7cc83177/tensorflow/python/keras/saving/hdf5_format.py#L659)fails with the following error:
```
  File "/root/.cache/bazel/_bazel_root/334416e3a0381b53511e68de49f4ac07/execroot/org_tensorflow/bazel-out/s390x-opt/bin/tensorflow/python/keras/applications/applications_load_weight_test_resnet_v2.runfiles/org_tensorflow/tensorflow/python/keras/saving/hdf5_format.py", line 659, in load_weights_from_hdf5_group
    original_keras_version = f.attrs['keras_version'].decode('utf8')
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/usr/local/lib/python3.6/dist-packages/h5py/_hl/attrs.py", line 81, in __getitem__
    attr.read(arr, mtype=htype)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5a.pyx", line 355, in h5py.h5a.AttrID.read
  File "h5py/_proxy.pyx", line 50, in h5py._proxy.attr_rw
  File "h5py/_proxy.pyx", line 319, in h5py._proxy.needs_bkg_buffer
  File "h5py/_proxy.pyx", line 316, in h5py._proxy.needs_bkg_buffer
KeyError: 'Conversion function not found (no appropriate function for conversion path)'
```
I suspect `keras_version` attribute has `CSET H5T_CSET_ASCII;` which `h5py` fails to convert to `UTF8` when architectures are different.

If  `h5py` is indeed the cause of these failures (which I suspect), then these testcases can be disabled on non-x86 archs or compatible Keras application models be used.

**Comment by rposts** [comment]
I notice that these test cases have `"no_oss"` defined in the BUILD file.  Perhaps not applicable on s390x?

**Comment by rposts** [comment]
Closing as per `no_oss`.

**Comment by mihaimaruseac** [comment]
`no_oss` means that the test was broken in OSS at some point.
