### ISSUE TITLE
Keras List index is out of range!

### ISSUE THREAD

**Issue by neel04** [tensorflow/tensorflow#39789]
Hey all!
I am getting this obscure error for which I could find no solution online. I am trying to make this piece of code that finds the relation between two numbers. For testing purposes, I am using simple data where the relation is to simply add 5. Here is how my training data looks like:-
`0,5`
`1,6`
`2,7`
`3,8`
`4,9`
`...`
Now, I am trying to sketch out a simple model that accomplishes what I want to do. However, It does not even get to the training part of the code and simply _terminates_ with this obscure error:-

```
2020-05-22 20:00:25.521151: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-05-22 20:00:25.523749: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-05-22 20:00:25.523805: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      
Traceback (most recent call last):
  File "main.py", line 34, in <module>
    history = model.fit(train_data, epochs=100, verbose=1)
  File "/home/awesome_ruler/.local/lib/python3.7/site-packages/keras/engine/training.py", line 1239, in fit
    validation_freq=validation_freq)
  File "/home/awesome_ruler/.local/lib/python3.7/site-packages/keras/engine/training_arrays.py", line 141, in fit_loop
    if issparse(fit_inputs[i]) and not K.is_sparse(feed[i]):
IndexError: list index out of range

```
I am not understanding the source of this error as the iterator that `model.fit` is using was not written by me but is being used from the libraries themselves. For reference, here is my code:-
```
# -*- coding: utf-8 -*-
# @author = Neel Gupta

import numpy as np
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD
import matplotlib.pyplot as pyplot
import csv

def csv_arr(csv_f):
    results = []
    # the loop..
    with open(csv_f) as csvfile:
        reader = csv.reader(csvfile, quoting=csv.QUOTE_NONNUMERIC)  # change contents to floats
        for row in reader:  # each row is a list
            results.append(row)
    # returning the output
    return np.asarray(results)

train_data = np.reshape(csv_arr("train.csv"), (15,2))
test_data = csv_arr("test.csv")

x_data = tf.keras.Input(shape=(15,2))

model = Sequential()
model.add(Dense(4, input_dim=2, activation='relu', kernel_initializer='glorot_uniform'))
model.add(Dense(1, activation='linear'))
opt = SGD(lr=0.01, momentum=0.9)
model.compile(loss='mean_squared_error', optimizer=opt, )

# fit model
history = model.fit(train_data, epochs=100, verbose=1)

# getting model's summary
model.summary()

# plot loss during training
pyplot.title('Loss / Mean Squared Error')
pyplot.plot(history.history['loss'], label='train')
pyplot.plot(history.history['val_loss'], label='test')
pyplot.legend()
pyplot.show()

```
I am using Tensorflow GPU, which is right now not using the acceleration due to some missing/broken libs. I am using TensorFlow version `2.2.0` and keras version `2.3`. Additionally, I am trying to use CUDA `10.1`. I do not know what other cause there is to my error. Can someone shed any light on this

**Comment by Saduf2019** [comment]
@neel04 
I ran the code shared by you and face an error, please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/e87851087ec8c4731be5336dc55b6e4e/untitled197.ipynb), please share all dependencies.

**Comment by neel04** [comment]
@Saduf2019 As discussed in my question above, the training data looks something like this:-
`0,5`
`1,6`
`2,7`
`3,8`
`4,9`
Where 5 is added to each number. So, you can simply create a file named `train.csv` and modify it's path in the Colab notebook. The `csv` file would contain data in the given format. My function will then convert this to an array automatically upon running the code. 

Regards,
Neel Gupta

**Comment by Saduf2019** [comment]
@neel04 
I ran the code with the csv and face [this error](https://colab.sandbox.google.com/gist/Saduf2019/f78fcad22fee1d84c8cb91d8b637fd09/untitled197.ipynb), can you please share a colab gist with the error for us to analyse it.

**Comment by neel04** [comment]
@Saduf2019 I think that the problem is arising due to the incorrect length of training data. You can copy/paste this exact sequence in the `train.csv` for further use.

`0,5`
`1,6`
`2,7`
`3,8`
`4,9`
`5,10`
`6,11`
`7,12`
`8,13`
`9,14`
`10,15`
`11,16`
`12,17`
`13,18`
`14,19`

**Comment by Saduf2019** [comment]
I am able to replicate the issue reported, please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/42189e7e4645183431851f04b22028ea/untitled204.ipynb) Thanks!

**Comment by jvishnuvardhan** [comment]
@neel04 I am seeing different error when I ran with `tf-nightly`.  Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/d8e56e50e614a4ae2d13a60cc9fbb2ca/untitled204.ipynb). Thanks!

```
Epoch 1/100
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-7-ccc2488cdec7> in <module>()
     30 
     31 # fit model
---> 32 history = model.fit(train_data, epochs=100, verbose=1)
     33 
     34 # getting model's summary

10 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/func_graph.py in wrapper(*args, **kwargs)
    966           except Exception as e:  # pylint:disable=broad-except
    967             if hasattr(e, "ag_error_metadata"):
--> 968               raise e.ag_error_metadata.to_exception(e)
    969             else:
    970               raise

ValueError: in user code:

    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py:802 train_function  *
        return step_function(self, iterator)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py:792 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/distribute_lib.py:968 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/distribute_lib.py:2351 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/distribute_lib.py:2710 _call_for_each_replica
        return fn(*args, **kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py:785 run_step  **
        outputs = model.train_step(data)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py:753 train_step
        self.trainable_variables)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py:2685 _minimize
        trainable_variables))
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py:562 _aggregate_gradients
        filtered_grads_and_vars = _filter_grads(grads_and_vars)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py:1271 _filter_grads
        ([v.name for _, v in grads_and_vars],))

    ValueError: No gradients provided for any variable: ['dense_2/kernel:0', 'dense_2/bias:0', 'dense_3/kernel:0', 'dense_3/bias:0'].
```
