### ISSUE TITLE
Unable to log scalar summaries in XLA

### ISSUE THREAD

**Issue by sumanthratna** [tensorflow/tensorflow#39798]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS 10.15.5 Beta
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.2.0
- Python version: 3.8.2
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

**Describe the current behavior**
Forcing XLA compilation via `experimental_compile=True` in a `tf.function` raises `tensorflow.python.framework.errors_impl.InvalidArgumentError` when the function contains `tf.summary.scalar` (I haven't tried other summaries). 

**Describe the expected behavior**
Passing `experimental_compile=True` should log the scalar without raising any errors. 

**Standalone code to reproduce the issue**
```python
import tensorflow as tf


@tf.function(
    experimental_compile=True,
)
def test_summaries():
    tf.summary.scalar('testing', 12.3)

with tf.summary.create_file_writer('./logs').as_default():
    tf.summary.experimental.set_step(0)
    test_summaries()
```

**Other info / logs**
```
2020-05-22 22:30:57.072264: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-05-22 22:30:57.091548: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7f99eef80060 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-05-22 22:30:57.091590: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Traceback (most recent call last):
  File "testsum.py", line 12, in <module>
    test_summaries()
  File "/private/tmp/venv/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 576, in __call__
    result = self._call(*args, **kwds)
  File "/private/tmp/venv/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 650, in _call
    return self._concrete_stateful_fn._filtered_call(canon_args, canon_kwds)  # pylint: disable=protected-access
  File "/private/tmp/venv/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1661, in _filtered_call
    return self._call_flat(
  File "/private/tmp/venv/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1745, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "/private/tmp/venv/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 593, in call
    outputs = execute.execute(
  File "/private/tmp/venv/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: Function invoked by the following node is not compilable: {{node __inference_test_summaries_22}} = __inference_test_summaries_22[_XlaMustCompile=true, config_proto="\n\007\n\003GPU\020\000\n\007\n\003CPU\020\0012\002J\0008\001", executor_type=""](dummy_input).
Uncompilable nodes:
testing/write_summary/tag: unsupported op: Const op with type DT_STRING is not supported by XLA.
	Stacktrace:
		Node: __inference_test_summaries_22, function: 
		Node: testing/write_summary/tag, function: __inference_test_summaries_22

testing/write_summary/summary_metadata: unsupported op: Const op with type DT_STRING is not supported by XLA.
	Stacktrace:
		Node: __inference_test_summaries_22, function: 
		Node: testing/write_summary/summary_metadata, function: __inference_test_summaries_22

testing/write_summary: unsupported op: No registered 'WriteSummary' OpKernel for XLA_CPU_JIT devices compatible with node {{node testing/write_summary}}
	Stacktrace:
		Node: __inference_test_summaries_22, function: 
		Node: testing/write_summary, function: __inference_test_summaries_22
 [Op:__inference_test_summaries_22]
```

**Comment by ravikyram** [comment]
@sumanthratna 

I have tried in colab with TF version 2.2.0 , nightly version and was able to reproduce the issue.Please, find the gist here.If we comment `@tf.function ` or if we give compile `experimental_compile=False` then i am not seeing any issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/ef8795cbdefbf1b9c52caec7cb0e7474/untitled32.ipynb).Thanks!

**Comment by sushreebarsa** [comment]
Was able to replicate the issue in TF v2.5,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/98cbf0f8469f3119a123a2129985fd08/untitled321.ipynb#scrollTo=QrtlWMG9cneJ)..Thanks!

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.

**Comment by sumanthratna** [comment]
I re-ran my minimal reproduction sample and this issue still exist on the latest stable TensorFlow. This was the traceback

```
WARNING:tensorflow:From /private/tmp/hey.py:4: calling function (from tensorflow.python.eager.polymorphic_function.polymorphic_function) with experimental_compile is deprecated and will be removed in a future version.
Instructions for updating:
experimental_compile is deprecated, use jit_compile instead
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1722456982.180267  327585 service.cc:146] XLA service 0x600002aee700 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
I0000 00:00:1722456982.181754  327585 service.cc:154]   StreamExecutor device (0): Host, Default Version
2024-07-31 13:16:22.187826: W tensorflow/core/framework/op_kernel.cc:1840] OP_REQUIRES failed at xla_ops.cc:577 : INVALID_ARGUMENT: Detected unsupported operations when trying to compile graph __inference_test_summaries_18[_XlaMustCompile=true,config_proto=3175580994766145631,executor_type=11160318154034397263] on XLA_CPU_JIT: WriteSummary (No registered 'WriteSummary' OpKernel for XLA_CPU_JIT devices compatible with node {{node testing/write_summary}}){{node testing/write_summary}}
The op is created at: 
File "hey.py", line 12, in <module>
File "hey.py", line 8, in test_summaries
File "venv/lib/python3.11/site-packages/tensorboard/plugins/scalar/summary_v2.py", line 89, in scalar
	tf2xla conversion failed while converting __inference_test_summaries_18[_XlaMustCompile=true,config_proto=3175580994766145631,executor_type=11160318154034397263]. Run with TF_DUMP_GRAPH_PREFIX=/path/to/dump/dir and --vmodule=xla_compiler=2 to obtain a dump of the compiled functions.
Traceback (most recent call last):
  File "/private/tmp/hey.py", line 12, in <module>
    test_summaries()
  File "/private/tmp/venv/lib/python3.11/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/private/tmp/venv/lib/python3.11/site-packages/tensorflow/python/eager/execute.py", line 53, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tensorflow.python.framework.errors_impl.InvalidArgumentError: Detected unsupported operations when trying to compile graph __inference_test_summaries_18[_XlaMustCompile=true,config_proto=3175580994766145631,executor_type=11160318154034397263] on XLA_CPU_JIT: WriteSummary (No registered 'WriteSummary' OpKernel for XLA_CPU_JIT devices compatible with node {{node testing/write_summary}}){{node testing/write_summary}}
The op is created at: 
File "hey.py", line 12, in <module>
File "hey.py", line 8, in test_summaries
File "venv/lib/python3.11/site-packages/tensorboard/plugins/scalar/summary_v2.py", line 89, in scalar
	tf2xla conversion failed while converting __inference_test_summaries_18[_XlaMustCompile=true,config_proto=3175580994766145631,executor_type=11160318154034397263]. Run with TF_DUMP_GRAPH_PREFIX=/path/to/dump/dir and --vmodule=xla_compiler=2 to obtain a dump of the compiled functions. [Op:__inference_test_summaries_18]
```

**Comment by Venkat6871** [comment]
Hi @sumanthratna ,
Thank you so much for filing this bug request! We truly appreciate your support. At the moment, this request is not prioritized and mark it for community contributions. If you would like to contribute on a fix, please feel free to fork the repository and submit a pull request in accordance with the TensorFlow [CONTRIBUTION GUIDELINES](https://www.tensorflow.org/community/contribute/code) and link this issue in your PR to ensure the maintainers can easily review and collaborate.To avoid duplicate work, please leave a comment here if you decide to take it on!
Thank you again for your interest and we look forward to seeing your contributions!
