### ISSUE TITLE
XLA compilation not working in Windows 10 Pro

### ISSUE THREAD

**Issue by alvarobasi** [tensorflow/tensorflow#39854]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 Pro
- TensorFlow installed from (source or binary): pip install tensorflow-gpu
- TensorFlow version (use command below): 2.2.0
- Python version: 3.7
- CUDA/cuDNN version: 7.6.5
- GPU model and memory: RTX 2080 8GB

**Describe the current behavior**
XLA compilation in Windows doesn't seem to work even if in the changelog of TF 2.2.0 says XLA is now possible with Windows systems. Here is the output of the error:
`2020-05-25 17:03:22.775625: W tensorflow/compiler/xla/service/gpu/buffer_comparator.cc:592] Internal: Invoking GPU asm compilation is supported on Cuda non-Windows platforms only
Relying on driver to perform ptx compilation. 
Setting XLA_FLAGS=--xla_gpu_cuda_data_dir=/path/to/cuda  or modifying $PATH can be used to set the location of ptxas
This message will only be logged once.
2020-05-25 17:03:23.131452: W tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:70] Can't find libdevice directory ${CUDA_DIR}/nvvm/libdevice. This may result in compilation or runtime failures, if the program we try to run uses routines from libdevice.
2020-05-25 17:03:23.131584: W tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:71] Searched for CUDA in the following directories:
2020-05-25 17:03:23.131652: W tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:74]   ./cuda_sdk_lib
2020-05-25 17:03:23.131702: W tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:74]   C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1
2020-05-25 17:03:23.131769: W tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:74]   .
2020-05-25 17:03:23.131814: W tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:76] You can choose the search directory by setting xla_gpu_cuda_data_dir in HloModule's DebugOptions.  For most apps, setting the environment variable XLA_FLAGS=--xla_gpu_cuda_data_dir=/path/to/cuda will work.
2020-05-25 17:03:23.132862: W tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc:305] libdevice is required by this HLO module but was not found at ./libdevice.10.bc
2020-05-25 17:03:23.139801: I tensorflow/compiler/jit/xla_compilation_cache.cc:241] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.
2020-05-25 17:03:23.141241: W tensorflow/core/framework/op_kernel.cc:1753] OP_REQUIRES failed at xla_ops.cc:520 : Internal: libdevice not found at ./libdevice.10.bc
Traceback (most recent call last):
  File "D:/Users/Alvaro/Documents/TFM/Project/eyesrgan/Resnet_MSE.py", line 142, in <module>
    callbacks=callbacks)
  File "D:\Development\Anaconda3\envs\TFM\lib\site-packages\tensorflow\python\keras\engine\training.py", line 66, in _method_wrapper
    return method(self, *args, **kwargs)
  File "D:\Development\Anaconda3\envs\TFM\lib\site-packages\tensorflow\python\keras\engine\training.py", line 848, in fit
    tmp_logs = train_function(iterator)
  File "D:\Development\Anaconda3\envs\TFM\lib\site-packages\tensorflow\python\eager\def_function.py", line 580, in __call__
    result = self._call(*args, **kwds)
  File "D:\Development\Anaconda3\envs\TFM\lib\site-packages\tensorflow\python\eager\def_function.py", line 644, in _call
    return self._stateless_fn(*args, **kwds)
  File "D:\Development\Anaconda3\envs\TFM\lib\site-packages\tensorflow\python\eager\function.py", line 2420, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "D:\Development\Anaconda3\envs\TFM\lib\site-packages\tensorflow\python\eager\function.py", line 1665, in _filtered_call
    self.captured_inputs)
  File "D:\Development\Anaconda3\envs\TFM\lib\site-packages\tensorflow\python\eager\function.py", line 1746, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "D:\Development\Anaconda3\envs\TFM\lib\site-packages\tensorflow\python\eager\function.py", line 598, in call
    ctx=ctx)
  File "D:\Development\Anaconda3\envs\TFM\lib\site-packages\tensorflow\python\eager\execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InternalError:  libdevice not found at ./libdevice.10.bc
	 [[{{node cluster_4_1/xla_compile}}]] [Op:__inference_train_function_12671]

Function call stack:
train_function

Process finished with exit code 1`

I already tried to add the XLA_FLAGS environment variable, as well as CUDA_DIR environ, both with any success.

**Describe the expected behavior**
XLA should work with its implicit gain in performance.

**Standalone code to reproduce the issue**
The source code can be found in this [colab](https://drive.google.com/open?id=12sx2GQN5kwRke7fPkj5TkgtugN5y1X44).

**Comment by ravikyram** [comment]
I have tried in colab with TF 2.2  and i am seeing the below error message `NonMatchingChecksumError:`.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/ff4a1e3d9ede6f0ce3497b6faa0444fb/untitled42.ipynb).Thanks!

**Comment by sushreebarsa** [comment]
@alvarobasi It looks like you are using an older Version of Tensorflow . Many bugs have been fixed in the latest version. Could you please execute your code using Latest Version 2.4.1 or 2.5 and let us know if the issue still persists? Thanks!
