### ISSUE TITLE
asserterror when using tf.cond

### ISSUE THREAD

**Issue by AngelPone** [tensorflow/tensorflow#39874]
Assert error when using tf.cond, 
Here is the code stucture, it works fine when I run it eagerly, but get errors when build graph.

```python
    def kf():
     # some compute
        for t in range(N):
            a, p, pinf = tf.cond(tf.reduce_max(pinf) > tf.constant(1e-8, tf.float64),
                                 lambda: self.kf_init_step(self.data[t], a, p, pinf, self.H[t], self.Q[t]),
                                 lambda: self.kf_step(self.data[t], a, p, pinf, self.H[t], self.Q[t]))
            a_list.append(a)
            p_list.append(p)
            pinf_list.append(pinf)


    def kf_init_step(self, y, a, p, pinf, H, Q):
        # some compute
        return a_new, p_new, pinf_new

    def kf_step(self, y, a, p, pinf, H, Q):
        # some compute
        return a_new, p_new, pinf
```
Trackback:

```python
Traceback (most recent call last):
  File "/Users/mac/Documents/bishe/DeepStateCount/DCSSM/run.py", line 50, in <module>
    dssm.fit(train_ds, epochs=10, callbacks=[checkpoint])
  File "/Users/mac/.pyenv/versions/3.6.5/envs/tensorflow/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py", line 819, in fit
    use_multiprocessing=use_multiprocessing)
  File "/Users/mac/.pyenv/versions/3.6.5/envs/tensorflow/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 235, in fit
    use_multiprocessing=use_multiprocessing)
  File "/Users/mac/.pyenv/versions/3.6.5/envs/tensorflow/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 593, in _process_training_inputs
    use_multiprocessing=use_multiprocessing)
  File "/Users/mac/.pyenv/versions/3.6.5/envs/tensorflow/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 706, in _process_inputs
    use_multiprocessing=use_multiprocessing)
  File "/Users/mac/.pyenv/versions/3.6.5/envs/tensorflow/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/data_adapter.py", line 702, in __init__
    x = standardize_function(x)
  File "/Users/mac/.pyenv/versions/3.6.5/envs/tensorflow/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 660, in standardize_function
    standardize(dataset, extract_tensors_from_dataset=False)
  File "/Users/mac/.pyenv/versions/3.6.5/envs/tensorflow/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py", line 2346, in _standardize_user_data
    all_inputs, y_input, dict_inputs = self._build_model_with_inputs(x, y)
  File "/Users/mac/.pyenv/versions/3.6.5/envs/tensorflow/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py", line 2572, in _build_model_with_inputs
    self._set_inputs(cast_inputs)
  File "/Users/mac/.pyenv/versions/3.6.5/envs/tensorflow/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py", line 2659, in _set_inputs
    outputs = self(inputs, **kwargs)
  File "/Users/mac/.pyenv/versions/3.6.5/envs/tensorflow/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 773, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "/Users/mac/.pyenv/versions/3.6.5/envs/tensorflow/lib/python3.6/site-packages/tensorflow_core/python/autograph/impl/api.py", line 237, in wrapper
    raise e.ag_error_metadata.to_exception(e)
AssertionError: in converted code:

    /Users/mac/Documents/bishe/DeepStateCount/DCSSM/DSSM.py:85 call  *
        loglikes = tf.map_fn(lambda x: self.linearloglike(x[0], x[1], x[2]),
    /Users/mac/.pyenv/versions/3.6.5/envs/tensorflow/lib/python3.6/site-packages/tensorflow_core/python/ops/map_fn.py:268 map_fn
        maximum_iterations=n)
    /Users/mac/Documents/bishe/DeepStateCount/DCSSM/DSSM.py:127 linearloglike  *
        return linearssm.loglikelihood()
    /Users/mac/Documents/bishe/DeepStateCount/DCSSM/LinearSSM.py:92 loglikelihood  *
        filtered = self.kalman_filter()
    /Users/mac/Documents/bishe/DeepStateCount/DCSSM/LinearSSM.py:48 kalman_filter  *
        res = tf.cond(tf.reduce_max(pinf) > tf.constant(1e-8, dtype=tf.float64),
    /Users/mac/.pyenv/versions/3.6.5/envs/tensorflow/lib/python3.6/site-packages/tensorflow_core/python/ops/control_flow_ops.py:1389 cond_for_tf_v2
        return cond(pred, true_fn=true_fn, false_fn=false_fn, strict=True, name=name)
    /Users/mac/.pyenv/versions/3.6.5/envs/tensorflow/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py:507 new_func
        return func(*args, **kwargs)
    /Users/mac/.pyenv/versions/3.6.5/envs/tensorflow/lib/python3.6/site-packages/tensorflow_core/python/ops/control_flow_ops.py:1174 cond
        return cond_v2.cond_v2(pred, true_fn, false_fn, name)
    /Users/mac/.pyenv/versions/3.6.5/envs/tensorflow/lib/python3.6/site-packages/tensorflow_core/python/ops/cond_v2.py:100 cond_v2
        name=scope)
    /Users/mac/.pyenv/versions/3.6.5/envs/tensorflow/lib/python3.6/site-packages/tensorflow_core/python/ops/cond_v2.py:219 _build_cond
        _make_indexed_slices_indices_types_match(_COND, [true_graph, false_graph])
    /Users/mac/.pyenv/versions/3.6.5/envs/tensorflow/lib/python3.6/site-packages/tensorflow_core/python/ops/cond_v2.py:627 _make_indexed_slices_indices_types_match
        assert len(set(outs_per_branch)) == 1, outs_per_branch

    AssertionError: [1, 3]
```

**Comment by mihaimaruseac** [comment]
Please fill in issue template. Also, please post output of `pip list`

**Comment by AngelPone** [comment]
**Have I written custom code** : true
**OS Platform and Distribution**  MacOS Catalina 10.15.4
**TensorFlow installed from** : pip
**TensorFlow version** : v2.1.0
**Describe the current behavior**
Assert error when using tf.cond

**Describe the expected behavior**
It should work.


pip  list output

```
Package                Version
---------------------- ------------
absl-py                0.8.0
appnope                0.1.0
astor                  0.8.0
attrs                  19.1.0
backcall               0.1.0
bleach                 3.1.0
cachetools             4.0.0
certifi                2019.11.28
chardet                3.0.4
cloudpickle            1.3.0
cycler                 0.10.0
decorator              4.4.0
defusedxml             0.6.0
entrypoints            0.3
gast                   0.2.2
google-auth            1.12.0
google-auth-oauthlib   0.4.1
google-pasta           0.1.7
grpcio                 1.28.1
h5py                   2.10.0
idna                   2.9
ipykernel              5.1.2
ipython                7.8.0
ipython-genutils       0.2.0
ipywidgets             7.5.1
jedi                   0.15.1
Jinja2                 2.10.1
joblib                 0.14.1
json5                  0.9.4
jsonschema             3.0.2
jupyter                1.0.0
jupyter-client         5.3.3
jupyter-console        6.0.0
jupyter-core           4.5.0
jupyterlab             2.1.0
jupyterlab-server      1.1.1
Keras-Applications     1.0.8
Keras-Preprocessing    1.1.0
kiwisolver             1.1.0
lightgbm               2.3.1
Markdown               3.1.1
MarkupSafe             1.1.1
matplotlib             3.1.3
mistune                0.8.4
nbconvert              5.6.0
nbformat               4.4.0
notebook               6.0.1
numpy                  1.17.2
oauthlib               3.1.0
opt-einsum             3.2.0
pandas                 0.25.1
pandocfilters          1.4.2
parso                  0.5.1
patsy                  0.5.1
pexpect                4.7.0
pickleshare            0.7.5
pip                    20.0.2
prometheus-client      0.7.1
prompt-toolkit         2.0.9
protobuf               3.9.2
ptyprocess             0.6.0
pyasn1                 0.4.8
pyasn1-modules         0.2.8
Pygments               2.4.2
pyparsing              2.4.6
pyrsistent             0.15.4
python-dateutil        2.8.0
pytz                   2019.3
pyzmq                  18.1.0
qtconsole              4.5.5
requests               2.23.0
requests-oauthlib      1.3.0
rsa                    4.0
scikit-learn           0.22.2.post1
scipy                  1.4.1
Send2Trash             1.5.0
setuptools             46.1.3
six                    1.12.0
sklearn                0.0
statsmodels            0.11.1
tensorboard            2.1.1
tensorflow             2.1.0
tensorflow-estimator   2.1.0
tensorflow-probability 0.9.0
termcolor              1.1.0
terminado              0.8.2
testpath               0.4.2
torch                  1.2.0
tornado                6.0.3
traitlets              4.3.2
urllib3                1.25.8
wcwidth                0.1.7
webencodings           0.5.1
Werkzeug               0.16.0
wheel                  0.33.6
widgetsnbextension     3.5.1
wrapt                  1.11.2
WARNING: You are using pip version 20.0.2; however, version 20.1.1 is available.
You should consider upgrading via the '/Users/mac/.pyenv/versions/3.6.5/envs/tensorflow/bin/python3.6 -m pip install --upgrade pip' command.
```

**Comment by ravikyram** [comment]
@AngelPone 

Can you share colab link or simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!
