### ISSUE TITLE
KeyError: 'acc' in multi_worker_fault_tolerance_test

### ISSUE THREAD

**Issue by rposts** [tensorflow/tensorflow#39880]
In TF 2.2.0, it appears that `Key` name has been changed to `accuracy` from `acc` recently which is causing this testcase to fail.

```
======================================================================
ERROR: testFaultToleranceInSyncStrategy_test_fileformat_h5_loadweightsonrestart_False_mode_graph_preemptioncallback_classmainKerasMultiWorkerFaultToleranceTestPreemptionAtBatchBoundarySimulatingCallback_requiredgpus_0_saveweightsonly_False_strategycls_classtensorflowpythondistributecollectiveallreducestrategyCollectiveAllReduceStrategy (__main__.KerasMultiWorkerFaultToleranceTest)
testFaultToleranceInSyncStrategy_test_fileformat_h5_loadweightsonrestart_False_mode_graph_preemptioncallback_classmainKerasMultiWorkerFaultToleranceTestPreemptionAtBatchBoundarySimulatingCallback_requiredgpus_0_saveweightsonly_False_strategycls_classtensorflowpythondistributecollectiveallreducestrategyCollectiveAllReduceStrategy (__main__.KerasMultiWorkerFaultToleranceTest)
testFaultToleranceInSyncStrategy_test_fileformat_h5_loadweightsonrestart_False_mode_graph_preemptioncallback_classmainKerasMultiWorkerFaultToleranceTestPreemptionAtBatchBoundarySimulatingCallback_requiredgpus_0_saveweightsonly_False_strategycls_classtensorflowpythondistributecollectiveallreducestrategyCollectiveAllReduceStrategy(file_format='h5', load_weights_on_restart=False, mode='graph', preemption_callback=<class '__main__.KerasMultiWorkerFaultToleranceTest.PreemptionAtBatchBoundarySimulatingCallback'>, required_gpus=0, save_weights_only=False, strategy_cls=<class 'tensorflow.python.distribute.collective_all_reduce_strategy.CollectiveAllReduceStrategy'>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/absl/testing/parameterized.py", line 263, in bound_param_test
    test_method(self, **testcase_params)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/test_combinations.py", line 314, in decorated
    execute_test_method()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/test_combinations.py", line 297, in execute_test_method
    test_method(**kwargs_to_pass)
  File "tensorflow/python/keras/distribute/multi_worker_fault_tolerance_test.py", line 331, in testFaultToleranceInSyncStrategy
    [history['acc'][-1] for history in self._histories])
  File "tensorflow/python/keras/distribute/multi_worker_fault_tolerance_test.py", line 331, in <listcomp>
    [history['acc'][-1] for history in self._histories])
KeyError: 'acc'

```
https://github.com/tensorflow/tensorflow/blob/509325e1b12df34e5d06117ac58242de58bd7798/tensorflow/python/keras/distribute/multi_worker_fault_tolerance_test.py#L331

On my system here are the `self._histories` contains:
```
-> [history['acc'][-1] for history in self._histories])
(Pdb) pp self._histories
[{'accuracy': [1.0, 1.0, 1.0],
  'loss': [2.2476557890574136, 2.1090187231699624, 1.9728290637334187]},
 {'accuracy': [1.0, 1.0, 1.0],
  'loss': [2.2476557890574136, 2.1090187231699624, 1.9728290637334187]},
 {'accuracy': [1.0, 1.0], 'loss': [2.1090187231699624, 1.9728290637334187]},
 {'accuracy': [1.0, 1.0], 'loss': [2.1090187231699624, 1.9728290637334187]}]
(Pdb)
```
Following change fixes this error:

```
diff --git a/tensorflow/python/keras/distribute/multi_worker_fault_tolerance_test.py b/tensorflow/python/keras/distribute/multi_worker_fault_tolerance_test.py
index fa58d2479a..f026ed1cae 100644
--- a/tensorflow/python/keras/distribute/multi_worker_fault_tolerance_test.py
+++ b/tensorflow/python/keras/distribute/multi_worker_fault_tolerance_test.py
@@ -328,17 +328,17 @@ class KerasMultiWorkerFaultToleranceTest(test_base.IndependentWorkerTestBase,
     # Important: the results from preemption interrupted and non-interrupted
     # cases should give the same final results.
     assert_all_elements_are_identical(
-        [history['acc'][-1] for history in self._histories])
+        [history['accuracy'][-1] for history in self._histories])
     assert_all_elements_are_identical(
         [history['loss'][-1] for history in self._histories])
     # The length of `self._histories` would be num_workers * num_runs (3).
     self.assertLen(self._histories, 4)

     # Results from case 1 should have 3 full epochs.
-    self.assertLen(self._histories[0]['acc'], 3)
+    self.assertLen(self._histories[0]['accuracy'], 3)
     # Results from case 2 should only have 2 full epochs because it restarted at
     # epoch 1.
-    self.assertLen(self._histories[-1]['acc'], 2)
+    self.assertLen(self._histories[-1]['accuracy'], 2)


 if __name__ == '__main__':
```
Please let me know if this is an acceptable fix.

Thanks.

**Comment by jvishnuvardhan** [comment]
@rposts Yes. Recently metric was changed from 'acc' to 'accuracy'. Can you please create a Pull-Request (PR) to update the code? Thanks!

Please close this issue. Thanks!

**Comment by rposts** [comment]
@jvishnuvardhan - it seems like this testcase is withdrawn from master.  Would you know if there is a corresponding replacement where this patch might apply?

**Comment by rposts** [comment]
Closing.  I cannot find this test case on master branch.
