### ISSUE TITLE
TF2.2 ImportError: cannot import name 'dense_features'

### ISSUE THREAD

**Issue by jojivk73** [tensorflow/tensorflow#39891]
When importing hooks_helper from official, see the following issue pop up.

Traceback (most recent call last):
  File "inference/fp32/wide_deep_inference.py", line 46, in <module>
    from official.utils.logs import hooks_helper
  File "/nfs/site/home/jojimonv/CIMonitor/Models/new/models/official/utils/logs/hooks_helper.py", line 29, in <module>
    from official.utils.logs import hooks
  File "/nfs/site/home/jojimonv/CIMonitor/Models/new/models/official/utils/logs/hooks.py", line 26, in <module>
    class ExamplesPerSecondHook(tf.estimator.SessionRunHook):
  File "/ec/pdx/disks/aipg_lab_home_pool_02/jojimonv/tfv2_new/lib/python3.6/site-packages/tensorflow/python/util/lazy_loader.py", line 62, in __getattr__
    module = self._load()
  File "/ec/pdx/disks/aipg_lab_home_pool_02/jojimonv/tfv2_new/lib/python3.6/site-packages/tensorflow/python/util/lazy_loader.py", line 45, in _load
    module = importlib.import_module(self.__name__)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/ec/pdx/disks/aipg_lab_home_pool_02/jojimonv/tfv2_new/lib/python3.6/site-packages/tensorflow_estimator/__init__.py", line 10, in <module>
    from tensorflow_estimator._api.v1 import estimator
  File "/ec/pdx/disks/aipg_lab_home_pool_02/jojimonv/tfv2_new/lib/python3.6/site-packages/tensorflow_estimator/_api/v1/estimator/__init__.py", line 10, in <module>
    from tensorflow_estimator._api.v1.estimator import experimental
  File "/ec/pdx/disks/aipg_lab_home_pool_02/jojimonv/tfv2_new/lib/python3.6/site-packages/tensorflow_estimator/_api/v1/estimator/experimental/__init__.py", line 10, in <module>
    from tensorflow_estimator.python.estimator.canned.dnn import dnn_logit_fn_builder
  File "/ec/pdx/disks/aipg_lab_home_pool_02/jojimonv/tfv2_new/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/canned/dnn.py", line 23, in <module>
    from tensorflow.python.feature_column import dense_features
ImportError: cannot import name 'dense_features'
Running Wide_Deep model Inference in Latency mode

**Comment by jojivk73** [comment]
Issue is resolved with installing tf-nightly-estimator
