### ISSUE TITLE
TypeError: evaluate() got an unexpected keyword argument 'batch_size'

### ISSUE THREAD

**Issue by ky-xt** [tensorflow/tensorflow#3990]
ok，When I run this code as follow, I have some error.
**Code:**
This code is from https://github.com/mouradmourafiq/tensorflow-lstm-regression ,
I found  the error may be result from some code:
_validation_monitor = learn.monitors.ValidationMonitor(X['val'], y['val'],
                                                      every_n_steps=PRINT_STEPS,
                                                      early_stopping_rounds=1000)
regressor.fit(X['train'], y['train'], monitors=[validation_monitor], logdir=LOG_DIR)_

**Then, here is the error message:**
INFO:tensorflow:Error reported to Coordinator: <type 'exceptions.TypeError'>, evaluate() got an unexpected keyword argument 'batch_size'
INFO:tensorflow:Error reported to Coordinator: <type 'exceptions.TypeError'>, evaluate() got an unexpected keyword argument 'batch_size'
Traceback (most recent call last):
  File "model.py", line 178, in <module>
    regressor.fit(X['train'], y['train'],monitors=[validation_monitor], logdir=LOG_DIR)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/base.py", line 166, in fit
    monitors=monitors)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 578, in _train_model
    max_steps=max_steps)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/graph_actions.py", line 280, in _supervised_train
    None)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/supervised_session.py", line 270, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/recoverable_session.py", line 54, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/coordinated_session.py", line 70, in run
    self._coord.join(self._coordinated_threads_to_join)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/coordinator.py", line 357, in join
    six.reraise(*self._exc_info_to_raise)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/coordinated_session.py", line 66, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/monitored_session.py", line 107, in run
    induce_stop = monitor.step_end(monitors_step, monitor_outputs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/monitors.py", line 396, in step_end
    return self.every_n_step_end(step, output)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/monitors.py", line 687, in every_n_step_end
    steps=self.eval_steps, metrics=self.metrics, name=self.name)
TypeError: evaluate() got an unexpected keyword argument 'batch_size'
@mouradmourafiq  

### Environment info
Operating System: 
ubuntu14.04 python2.7 tensorflow with only CPU

**Comment by prb12** [comment]
This code is not part of the tensorflow project.  Please consider asking the author of that code, or post your request for assistance on StackOveflow.

**Comment by devanshdalal** [comment]
Did you solve the problem ?

**Comment by lentebloem** [comment]
I met the exact same issue when using tflearn. Has anybody been able to fix it?

**Comment by ad34** [comment]
i guess the tensorflow api has changed and that s why you get this error.
