### ISSUE TITLE
    TfLiteGpuDelegate Init: Tensor "model/tf_op_layer_Reshape/Reshape" has bad input dims size: 5.

### ISSUE THREAD

**Issue by abdalkhalik** [tensorflow/tensorflow#39920]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Android**
- TensorFlow version (use command below): **org.tensorflow:tensorflow-lite:0.0.0-nightly / org.tensorflow:tensorflow-lite-gpu:0.0.0-nightly**
- GPU model and memory: **Hawaii Nova3 built in GPU** 

I am Trying to the run this example https://github.com/tensorflow/examples/tree/master/lite/examples/object_detection/android with Yolov4 converted model (.weight -> .tflite). It worked fine on the CPU, however when enabling the **GPU** and the following error happens:

     **Caused by: java.lang.IllegalArgumentException: Internal error: Failed to apply delegate: Following operations are not supported by GPU delegate:
    EXP: Operation is not supported.
    SPLIT_V: Operation is not supported.
    88 operations will run on the GPU, and the remaining 477 operations will run on the CPU.
    TfLiteGpuDelegate Init: Tensor "model/tf_op_layer_Reshape/Reshape" has bad input dims size: 5.
    TfLiteGpuDelegate Prepare: delegate is not initialized
    Node number 565 (TfLiteGpuDelegateV2) failed to prepare.
    
    Restored original execution plan after delegat
        at org.tensorflow.lite.NativeInterpreterWrapper.applyDelegate(Native Method)
        at org.tensorflow.lite.NativeInterpreterWrapper.applyDelegates(NativeInterpreterWrapper.java:347)
        at org.tensorflow.lite.NativeInterpreterWrapper.init(NativeInterpreterWrapper.java:82)
        at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:63)
        at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:237)
        at org.tensorflow.lite.examples.detection.tflite.YoloV4Classifier.create(YoloV4Classifier.java:115)
        	... 17 more**

I think this is the model part causeing this error
![image](https://user-images.githubusercontent.com/4397109/83063715-3fc35e80-a069-11ea-9965-d948804a98ea.png)

Any idea how i can overcome this issue?

**Comment by abdalkhalik** [comment]
The problem is resolved by using tensorflow/tensorflow-gpu **v2.1** instead of **nightly**
