### ISSUE TITLE
No module named 'tensorflow.contrib'

### ISSUE THREAD

**Issue by Brandonli-13** [tensorflow/tensorflow#39937]
I'm using tensorflow with python3.8, but when I run the code, the output shows: `No module named 'tensorflow.contrib'`
Detailed:
`Traceback (most recent call last):
  File "/Users/brandonli/PycharmProjects/untitled/main.py", line 7, in <module>
    import tflearn
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tflearn/__init__.py", line 4, in <module>
    from . import config
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tflearn/config.py", line 5, in <module>
    from .variables import variable
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tflearn/variables.py", line 7, in <module>
    from tensorflow.contrib.framework.python.ops import add_arg_scope as contrib_add_arg_scope
ModuleNotFoundError: No module named 'tensorflow.contrib'`
I'm running tensorflow 2.2.0
Some people say that running 1.14 could solve the problem, so I run 
`sudo pip3 install tensorflow==1.14.0` in the Terminal
but I found out that I could only install 2.2.0
Any way to solve this problem?
Running macOS Catalina
Python3.8
also working with tflearn in my code

**Comment by amahendrakar** [comment]
@Brandonli-13,
- `tensorflow.contrib` does not exist in TF 2.x. You'll have to use TF 1.x to use `tensorflow.contrib`

- The reason you are unable to install TF 1.x is due to the Python version incompatibility. Please check the tested build configurations [here](https://www.tensorflow.org/install/source#linux).

- In this case, I'd suggest you to migrate your code to TF 2.x. You can also switch to Python 3.7 with TF 1.x, but it is not recommended as TF 1.x is not actively supported.

Thanks!
