### ISSUE TITLE
Missing positional argument error when deepcopy a LSTMCell

### ISSUE THREAD

**Issue by guillaumekln** [tensorflow/tensorflow#39978]
**System information**
- Have I written custom code: Yes
- OS Platform and Distribution: Ubuntu 16.04
- TensorFlow installed from: binary
- TensorFlow version: 2.2.0
- Python version: 3.5 & 3.6

**Describe the current behavior**

An exception is raised when calling `copy.deepcopy` on a `tf.keras.layers.LSTMCell`.

**Describe the expected behavior**

Keras layers should support `copy.deepcopy` without error since https://github.com/tensorflow/tensorflow/commit/4fd10c487c7e287f99b9a1831316add453dcba04. The same code worked in TensorFlow 2.1.

**Standalone code to reproduce the issue**

```python
import copy
import tensorflow as tf

cell = tf.keras.layers.LSTMCell(512)
cell = copy.deepcopy(cell)
```

**Other info / logs**

```text
Traceback (most recent call last):
  File "test/deepcopy.py", line 5, in <module>
    cell = copy.deepcopy(cell)
  File "<env_dir>/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "<env_dir>/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "<env_dir>/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "<env_dir>/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "<env_dir>/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "<env_dir>/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "<env_dir>/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "<env_dir>/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "<env_dir>/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "<env_dir>/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "<env_dir>/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "<env_dir>/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "<env_dir>/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "<env_dir>/lib/python3.6/copy.py", line 220, in _deepcopy_tuple
    y = [deepcopy(a, memo) for a in x]
  File "<env_dir>/lib/python3.6/copy.py", line 220, in <listcomp>
    y = [deepcopy(a, memo) for a in x]
  File "<env_dir>/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "<env_dir>/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "<env_dir>/lib/python3.6/copy.py", line 161, in deepcopy
    y = copier(memo)
  File "<env_dir>/lib/python3.6/weakref.py", line 421, in __deepcopy__
    new = self.__class__()
TypeError: __init__() missing 1 required positional argument: 'default_factory'
```

**Comment by Saduf2019** [comment]
i am able to replicate this error on tensorflow 2.0, 2.1 and nightly as well, please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/1f2bb8b9b9a9c37f6888e3425b92f141/untitled199.ipynb)

**Comment by qlzh727** [comment]
Thanks for reporting the issue. Will send a fix very soon.

**Comment by guillaumekln** [comment]
As this bug is a regression, will the commit get backported in a patch release?
