### ISSUE TITLE
Is there a way to train large amount of variable size data in TF

### ISSUE THREAD

**Issue by sun-peach** [tensorflow/tensorflow#40007]
Hi, I am working on a model (structure shown below). I have 9 inputs, 8 is images whose size is (224,224,3) and the other is audio whose size is (1, 96, 1366). I use tf.keras to construct model following: `model = Model([image_1...image_8, audio_input], output)`
![image](https://user-images.githubusercontent.com/14579257/83305598-ed438880-a1b5-11ea-81ec-626acff96b11.png)

Since my data is too large, I use the `fit_generator` to train it (I know it is `fit` now, I use the old name for distinguishing from each other). 

Firstly I tried tensorflow dataset following below:
```
class BasicDatasetLight(object):
    def __init__(self, run_data, batch_size):
        """
        :param run_data: a dictionary storing the data info
        :param batch_size:
        """
        from os.path import splitext
        data_array = np.load(run_data["data_file"], allow_pickle=True)
        self.run_info = run_data
        self.x, self.y = data_array[:,:-1], data_array[:,-1].astype(dtype=int)
        self.img_num = len(data_array[0][0])        # input image number
        _, self.image_type = splitext(data_array[0][0][0])      # input image type
        self.model_input_num = run_data["input_num"]
        self.gen_out_type = self.__gen_out_type_shape()[0]     # get output type tuple
        self.gen_out_shape = self.__gen_out_type_shape()[1]     # get output shape tuple
        self.batch_size = batch_size

    def __len__(self):
        """
        generate batch number
        :return:
        """
        return len(self.x) // self.batch_size

    def __gen_out_type_shape(self):
        """
        generate output type tuple according the input
        :return:
        """
        peep_file = self.x[:,0][0][0]
        peep_shape = self.run_info["image_shape"]
        peep_image = _tf_load_img(peep_file, peep_shape[0], decode_image=self.image_type)
        out_type = peep_image.dtype
        # type list [type] * image_input_num + [audio type]
        type_list = [out_type] * (len(peep_shape)*self.img_num) + [out_type]
        # shape list [shape] * image_input_num + [audio shape]
        shape_list = [peep_shape[0]]*(len(peep_shape)*self.img_num) + [self.run_info["audio_shape"]]
        gen_out_shape = fake_gen_shape(shape_list)
        assert len(type_list)==self.model_input_num,"wrong input number"
        return (tuple(type_list),tf.int8), (gen_out_shape, tf.TensorShape(1,))

    def give_dataset(self):
        """
        serve the dataset to model
        :return:
        """
        ds = tf.data.Dataset.from_generator(
            lambda: _get_generator_light(self.x, self.y, self.run_info,self.image_type),
             output_types=self.gen_out_type,
             output_shapes=self.gen_out_shape)
        ds = ds.repeat()
        ds = ds.batch(self.batch_size, drop_remainder=True)
        ds = ds.prefetch(buffer_size=tf.data.experimental.AUTOTUNE)
        return ds
```
The the methods starting with "__" are all internal functions. The `give_dataset` is the method serving dataset. It calls the `_get_generator_light` to form dataset from generator. The function is listed below:
```
def _tf_load_img(img_file, target_shape, decode_image=".jpg"):
    """
    tensorflow load image
    :param img_file:
    :param target_shape: (H x W x C) channel last
    :param decode_image: image extension for decoding mode
    :return:
    """
    image = tf.io.read_file(img_file)
    # image shape channel last
    if "png" in decode_image: image = tf.image.decode_png(image, channels=target_shape[-1])
    else: image = tf.image.decode_jpeg(image, channels=target_shape[-1])
    image = tf.cast(image, tf.float32)
    image = (image/127.5) - 1
    image = tf.image.resize(image, (target_shape[0], target_shape[1]))
    return image


def _get_generator_light(x, y, run_info, image_type=".jpg"):
    """
    a generator function for tensorflow dataset
    :param x:   input data
    :param y:   label
    :param run_info:    run information dictionary
    :param image_type:  image type for identifying decoding mode
    :return: ([input list], output)
    """
    # images number x copies (models may need different inputs) + audio input
    image_in,audio_in,y = x[:,0],x[:,1],y
    image_shape = run_info["image_shape"]
    image_num = len(image_in[0])
    decode_image = image_type
    buff_size = len(image_shape)*image_num + 1
    for data_read_index in range(len(x)):
        # data_buff = np.empty(buff_size, dtype=object)
        data_buff = [None] * buff_size
        buff_index = 0
        for ii in range(image_num):
            for neti in range(len(image_shape)):
                image = _tf_load_img(image_in[data_read_index][ii],
                                     image_shape[neti],
                                     decode_image=decode_image)
                data_buff[buff_index] = image
                buff_index += 1
        data_buff[buff_index] = np.expand_dims(audio_in[data_read_index],axis=0)
        label = y[data_read_index]
        assert buff_index==buff_size-1, "wrong data buff size"
        yield data_buff, label
```
NOTICE: `_get_generator_light` calls `_tf_load_img`, which is also listed. 
However, it shows the error:
```
Traceback (most recent call last):

  File "/opt/anaconda3/envs/mau/lib/python3.7/site-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 795, in generator_py_func
    flattened_values = nest.flatten_up_to(output_types, values)

  File "/opt/anaconda3/envs/mau/lib/python3.7/site-packages/tensorflow_core/python/data/util/nest.py", line 396, in flatten_up_to
    assert_shallow_structure(shallow_tree, input_tree)

  File "/opt/anaconda3/envs/mau/lib/python3.7/site-packages/tensorflow_core/python/data/util/nest.py", line 324, in assert_shallow_structure
    check_types=check_types)

  File "/opt/anaconda3/envs/mau/lib/python3.7/site-packages/tensorflow_core/python/data/util/nest.py", line 299, in assert_shallow_structure
    "Input has type: %s." % type(input_tree))

TypeError: If shallow structure is a sequence, input must also be a sequence. Input has type: <class 'list'>.
```

Then I tried to use python generator:
```
class BasicGeneratorLight(tf.keras.utils.Sequence):
    def __init__(self, run_data, batch_size):
        """
        :param run_data: a dictionary storing the data info
        :param batch_size:
        """
        from os.path import splitext
        data_array = np.load(run_data["data_file"], allow_pickle=True)
        self.run_info = run_data
        self.x, self.y = data_array[:,:-1], data_array[:,-1].astype(dtype=int)
        self.img_num = len(data_array[0][0])        # input image number
        _, self.image_type = splitext(data_array[0][0][0])      # input image type
        self.model_input_num = run_data["input_num"]
        self.batch_size = batch_size

    def __len__(self):
        return len(self.x) // self.batch_size

    def __getitem__(self, idx):
        batch_x = self.x[idx * self.batch_size:(idx + 1) * self.batch_size]
        batch_y = self.y[idx * self.batch_size:(idx + 1) * self.batch_size]
        img_num = self.img_num    # check how many images we have
        imagenet_shapes = self.run_info["image_shape"]      #  input shape for each image net (ORDER MATTERS!)
        imgnet_num = len(imagenet_shapes)
        input_num = img_num*imgnet_num+1
        model_data = np.empty(input_num,dtype=object)     # data buffer
        model_data_index = 0
        audio_buff = np.empty([self.batch_size] + list(self.run_info["audio_shape"]), dtype=float)
        audio_read = True
        for ii in range(img_num):   # read every image
            for neti in range(imgnet_num):  # prepare for each image model
                image_buff = np.empty([self.batch_size] + list(imagenet_shapes[neti]), dtype=float)
                # load data per img
                for di in range(self.batch_size):
                    curr_imgfile = batch_x[di, 0][ii]
                    #image_buff[di, :, :, :] = _tf_load_img(curr_imgfile,
                    #                                       imagenet_shapes[neti], self.image_type)
                    image_buff[di, :, :, :] = _keras_load_img(curr_imgfile,
                                                              imagenet_shapes[neti],'vgg')  # use 'vgg' for all
                    if audio_read:
                        aud_len = batch_x[di, 1].shape[-1]
                        audio_buff[di, 0, :, :aud_len] = batch_x[di, 1]  # set channle axis to 0 as only mono channel
                audio_read = False  # disable audio_read after reading audio one time
                model_data[model_data_index] = image_buff
                model_data_index += 1
        model_data[model_data_index] = audio_buff  # append audio data to the end
        assert model_data_index==input_num-1, "input number wrong"
        return list(model_data), batch_y
```
It finally can run the experiment, however, it gives the error:
```
2020-05-30 04:14:00.228692: W tensorflow/core/kernels/data/generator_dataset_op.cc:103] Error occurred when finalizing GeneratorDataset iterator: Cancelled: Operation was cancelled
2020-05-30 04:14:00.232101: W tensorflow/core/kernels/data/generator_dataset_op.cc:103] Error occurred when finalizing GeneratorDataset iterator: Cancelled: Operation was cancelled
2020-05-30 04:14:00.235563: W tensorflow/core/kernels/data/generator_dataset_op.cc:103] Error occurred when finalizing GeneratorDataset iterator: Cancelled: Operation was cancelled
2020-05-30 04:14:00.238860: W tensorflow/core/kernels/data/generator_dataset_op.cc:103] Error occurred when finalizing GeneratorDataset iterator: Cancelled: Operation was cancelled
```
I use 32 workers and max_queue_size 32. Though the experiment is running without stop, the error seems something wrong to me.

Without the generator way and tf.data way, how can I train my model?

**Comment by sun-peach** [comment]
Does anyone have the same problem? It seems a dead end for me to use TF to train my system.

**Comment by ravikyram** [comment]
@sun-peach 

Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version.

Request you to share colab link or simple standalone code with supporting files to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by sun-peach** [comment]
I use Ubuntu 16.04, TF 2.1.0. The whole program is too large to share. I past the key parts in the original post. Thank you.

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
Thanks!
