### ISSUE TITLE
Training error on Cloud TPUs

### ISSUE THREAD

**Issue by caffeine-lab** [tensorflow/tensorflow#40035]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian OS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.2.0
- Python version: 3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I am using a custom-modified code which works well on CPUs to train on TPUs and I am getting the error below
```
2020-05-31 22:06:00.162510: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2020-05-31 22:06:00.169480: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 2000179999 Hz
2020-05-31 22:06:00.170574: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x41a8240 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-05-31 22:06:00.170610: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-05-31 22:06:00.180728: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:301] Initialize GrpcChannelCache for job worker -> {0 -> 10.240.1.2:8470}
2020-05-31 22:06:00.180770: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:301] Initialize GrpcChannelCache for job localhost -> {0 -> localhost:56139}
2020-05-31 22:06:00.195639: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:301] Initialize GrpcChannelCache for job worker -> {0 -> 10.240.1.2:8470}
2020-05-31 22:06:00.195683: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:301] Initialize GrpcChannelCache for job localhost -> {0 -> localhost:56139}
2020-05-31 22:06:00.196179: I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:390] Started server with target: grpc://localhost:56139
All devices:  [LogicalDevice(name='/job:worker/replica:0/task:0/device:TPU:7', device_type='TPU'), LogicalDevice(name='/job:worker/replica:0/task:0/device:TPU:6', device_type='TPU'), LogicalDevice(name='/job:worker/replica:0/task:0/device:TPU:5', device_type='TPU'), LogicalDevice(name='/job:worker/replica:0/task:0/device:TPU:4', device_type='TPU'), LogicalDevice(name='/job:worker/replica:0/task:0/device:TPU:0', device_type='TPU'), LogicalDevice(name='/job:worker/replica:0/task:0/device:TPU:1', device_type='TPU'), LogicalDevice(name='/job:worker/replica:0/task:0/device:TPU:2', device_type='TPU'), LogicalDevice(name='/job:worker/replica:0/task:0/device:TPU:3', device_type='TPU')]
2020/05/31 22:06:05 Network Started
Number of devices: 8
Traceback (most recent call last):
  File "check_tpu_distribute_strategy_trainer.py", line 166, in <module>
    for x in train_dist_dataset:
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/distribute/input_lib.py", line 296, in __next__
    return self.get_next()
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/distribute/input_lib.py", line 328, in get_next
    global_has_value, replicas = _get_next_as_optional(self, self._strategy)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/distribute/input_lib.py", line 192, in _get_next_as_optional
    iterator._iterators[i].get_next_as_list(new_name))  # pylint: disable=protected-access
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/distribute/input_lib.py", line 1150, in get_next_as_list
    strict=True,
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 1204, in cond
    if pred:
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py", line 884, in __bool__
    return bool(self._numpy())
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py", line 929, in _numpy
    six.raise_from(core._status_to_exception(e.code, e.message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.UnavailableError: failed to connect to all addresses
Additional GRPC error information:
{"created":"@1590962770.862373470","description":"Failed to pick subchannel","file":"third_party/grpc/src/core/ext/filters/client_channel/client_channel.cc","file_line":3959,"referenced_errors":[{"created":"@1590962770.862371521","description":"failed to connect to all addresses","file":"third_party/grpc/src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":394,"grpc_status":14}]}
	 [[{{node MultiDeviceIteratorGetNextFromShard}}]]
	 [[RemoteCall]]
2020-05-31 22:06:10.972287: W tensorflow/core/distributed_runtime/eager/remote_tensor_handle_data.cc:76] Unable to destroy remote tensor handles. If you are running a tf.function, it usually indicates some op in the graph gets an error: failed to connect to all addresses
Additional GRPC error information:
{"created":"@1590962770.862373470","description":"Failed to pick subchannel","file":"third_party/grpc/src/core/ext/filters/client_channel/client_channel.cc","file_line":3959,"referenced_errors":[{"created":"@1590962770.862371521","description":"failed to connect to all addresses","file":"third_party/grpc/src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":394,"grpc_status":14}]}
	 [[{{node MultiDeviceIteratorGetNextFromShard}}]]
	 [[RemoteCall]]
```
**Describe the expected behavior**
The code works without any problem with CPUs. The data is stored on the VM not on the GCS bucket.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by ravikyram** [comment]
@caffeine-lab 

Request you to share colab link or simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by caffeine-lab** [comment]
My code is based on. : https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/text/image_captioning.ipynb

code snippet which remodified

```

resolver = tf.distribute.cluster_resolver.TPUClusterResolver(tpu='tpu-node1')
tf.config.experimental_connect_to_cluster(resolver)
tf.tpu.experimental.initialize_tpu_system(resolver)
print("All devices: ", tf.config.list_logical_devices('TPU'))

PATH = "Train_Images/"

img_train,cap_train = I2S_Data.data_loader(PATH)

strategy = tf.distribute.experimental.TPUStrategy(resolver)

with strategy.scope():
	# loading the numpy files
	def map_func(img_name, cap):
		img_tensor = np.load(img_name.decode('utf-8')+'.npy')
		return img_tensor, cap
	def get_dataset(batch_size,img_name_train,cap_train):
		dataset = tf.data.Dataset.from_tensor_slices((img_name_train, cap_train))

		# using map to load the numpy files in parallel
		dataset = dataset.map(lambda item1, item2: tf.numpy_function(map_func, [item1, item2], [tf.float32, tf.int32]),num_parallel_calls=tf.data.experimental.AUTOTUNE)

		# shuffling and batching
		dataset = dataset.shuffle(BUFFER_SIZE)
		dataset = dataset.batch(batch_size)

		return dataset
	#dataset = dataset.prefetch(buffer_size=tf.data.experimental.AUTOTUNE)

	train_dist_dataset = strategy.experimental_distribute_datasets_from_function(
    lambda _: get_dataset(BATCH_SIZE_PER_REPLICA, img_name_train,cap_train))

checkpoint_path = "./checkpoints/"
	#Network Parameters
	optimizer = tf.keras.optimizers.Adam(learning_rate=0.0005)
	loss_object = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True, reduction=tf.keras.losses.Reduction.NONE)

	def loss_function(real, pred):
		mask = tf.math.logical_not(tf.math.equal(real, 0))
		loss_ = loss_object(real, pred)

		mask = tf.cast(mask, dtype=loss_.dtype)
		loss_ *= mask

		return tf.reduce_mean(loss_)
	encoder = I2S_Model.CNN_Encoder(embedding_dim)
	decoder = I2S_Model.RNN_Decoder(embedding_dim, units, vocab_size)
	ckpt = tf.train.Checkpoint(encoder=encoder,decoder=decoder,optimizer = optimizer)
	ckpt_manager = tf.train.CheckpointManager(ckpt, checkpoint_path, max_to_keep=50)
	start_epoch = 0
	if ckpt_manager.latest_checkpoint:
		ckpt.restore(tf.train.latest_checkpoint(checkpoint_path))
		start_epoch = int(ckpt_manager.latest_checkpoint.split('-')[-1])

	#the loss_plot array will be reset many times
	loss_plot = []

	@tf.function
	def train_step(dist_inputs):
		def step_fn(inputs):
			img_tensor, target = inputs
			print(target.shape[0])
			loss = 0

			# initializing the hidden state for each batch because the captions are not related from image to image
			hidden = decoder.reset_state(batch_size=target.shape[0])

			dec_input = tf.expand_dims([tokenizer.word_index['<start>']] * target.shape[0], 1)

			with tf.GradientTape() as tape:
				features = encoder(img_tensor)

				for i in range(1, target.shape[1]):
					# passing the features through the decoder
					predictions, hidden, _ = decoder(dec_input, features, hidden)

					loss += loss_function(target[:, i], predictions)

					# using teacher forcing
					dec_input = tf.expand_dims(target[:, i], 1)

			total_loss = (loss / int(target.shape[1]))

			trainable_variables = encoder.trainable_variables + decoder.trainable_variables

			gradients = tape.gradient(loss, trainable_variables)

			optimizer.apply_gradients(zip(gradients, trainable_variables))

			
			return loss, total_loss

		per_replica_losses, l_loss = strategy.run(step_fn, args=(dist_inputs,))
		return strategy.reduce(tf.distribute.ReduceOp.MEAN, per_replica_losses,axis=None),strategy.reduce(tf.distribute.ReduceOp.MEAN, l_loss,axis=None)


	for epoch in range(start_epoch, EPOCHS):
		start = time.time()
		total_loss = 0.0
		batch = 0
		for x in train_dist_dataset:
			batch_loss, t_loss = train_step(x)
			total_loss += t_loss
			batch +=1

			if batch % 100 == 0:
				print ('Epoch {} Batch {} Loss {:.4f}'.format(epoch + 1, batch, batch_loss.numpy() / BATCH_SIZE), flush=True)
		train_loss = total_loss / batch
		print("Total Batches: ",batch)
		# storing the epoch end loss value to plot later
		loss_plot.append(total_loss / num_steps)
		
		if epoch % 1 == 0:
			ckpt_manager.save()

		print ('Epoch {} Loss {:.6f} Train Loss {:.6f}'.format(epoch + 1,total_loss/num_steps,train_loss), flush=True)
		print (datetime.now().strftime('%Y/%m/%d %H:%M:%S'),'Time taken for 1 epoch {} sec\n'.format(time.time() - start), flush=True)
```

Rest of the code remains the same as in the notebook

**Comment by caffeine-lab** [comment]
@gowthamkpr 

https://gist.github.com/caffeine-lab/bd623547b086322aa82832ce915931cf

You can find the edited gist on above link

**Comment by jplu** [comment]
Hello!

I'm going through the same issue and I wanted to know if there was any update on this? Will it be fixed in the forthcoming 2.3 release?

**Comment by jhseu** [comment]
We don't currently support loading local files this way, although it'll work at some point in the near future. For now, you can load them outside of tf.data as numpy arrays and feed them instead.

**Comment by sushreebarsa** [comment]
@caffeine-lab Could you please try on latest stable version of tf 2.5 or 2.4.1 and let us know if this is still an issue.Thanks!
