### ISSUE TITLE
Test case //tensorflow/python/eager:def_function_test_cpu_only fails on TF2.2 due to inconsistent XLA flag.

### ISSUE THREAD

**Issue by Sidong-Wei** [tensorflow/tensorflow#40048]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): N/A
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.2.0
- Python version: 3.8.2
- Bazel version (if compiling from source): 2.0.0
- GCC/Compiler version (if compiling from source): gcc (Ubuntu 9.3.0-10ubuntu2) 9.3.0
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
The test case `//tensorflow/python/eager:def_function_test_cpu_only` fails with the following error log:
```
======================================================================
ERROR: testExperimentalCompileRaisesExceptionWhenXlaIsUnsupported (__main__.DefFunctionCpuOnlyTest)
testExperimentalCompileRaisesExceptionWhenXlaIsUnsupported (__main__.DefFunctionCpuOnlyTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sidong/.cache/bazel/_bazel_sidong/9ef871a29c692fc6a18121463529e145/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/eager/def_function_test_cpu_only.runfiles/org_tensorflow/tensorflow/python/eager/def_function_test_cpu_only.py", line 46, in testExperimentalCompileRaisesExceptionWhenXlaIsUnsupported
    fn([1, 1, 2, 3])
  File "/home/sidong/.cache/bazel/_bazel_sidong/9ef871a29c692fc6a18121463529e145/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/eager/def_function_test_cpu_only.runfiles/org_tensorflow/tensorflow/python/eager/def_function.py", line 576, in __call__
    result = self._call(*args, **kwds)
  File "/home/sidong/.cache/bazel/_bazel_sidong/9ef871a29c692fc6a18121463529e145/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/eager/def_function_test_cpu_only.runfiles/org_tensorflow/tensorflow/python/eager/def_function.py", line 650, in _call
    return self._concrete_stateful_fn._filtered_call(canon_args, canon_kwds)  # pylint: disable=protected-access
  File "/home/sidong/.cache/bazel/_bazel_sidong/9ef871a29c692fc6a18121463529e145/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/eager/def_function_test_cpu_only.runfiles/org_tensorflow/tensorflow/python/eager/function.py", line 1661, in _filtered_call
    return self._call_flat(
  File "/home/sidong/.cache/bazel/_bazel_sidong/9ef871a29c692fc6a18121463529e145/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/eager/def_function_test_cpu_only.runfiles/org_tensorflow/tensorflow/python/eager/function.py", line 1745, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "/home/sidong/.cache/bazel/_bazel_sidong/9ef871a29c692fc6a18121463529e145/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/eager/def_function_test_cpu_only.runfiles/org_tensorflow/tensorflow/python/eager/function.py", line 593, in call
    outputs = execute.execute(
  File "/home/sidong/.cache/bazel/_bazel_sidong/9ef871a29c692fc6a18121463529e145/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/eager/def_function_test_cpu_only.runfiles/org_tensorflow/tensorflow/python/eager/execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: Function invoked by the following node is not compilable: {{node __inference_fn_7}} = __inference_fn_7[_XlaMustCompile=true, config_proto="\n\007\n\003CPU\020\001\n\007\n\003GPU\020\0002\002J\0008\001", executor_type=""]().
Uncompilable nodes:
Unique: unsupported op: No registered 'Unique' OpKernel for XLA_CPU_JIT devices compatible with node {{node Unique}}
        Stacktrace:
                Node: __inference_fn_7, function:
                Node: Unique, function: __inference_fn_7
 [Op:__inference_fn_7]

----------------------------------------------------------------------
Ran 2 tests in 0.318s

FAILED (errors=1, skipped=1)
```
**Describe the expected behavior**
The test case should raise a ValueError "Attempting to use experimental_compile, but XLA support is not linked in. Rebuild with --define=with_xla_support=true.", and captured by `self.assertRaisesRegexp()`
The test case should pass.

**Standalone code to reproduce the issue**
I modified the test case a little bit, and it could be reproduced from this [gist](https://colab.research.google.com/drive/1qweKRl1ZxEPWtN-qlz6DsNCVR0J8M8fg?usp=sharing)

**Other info / logs** 
I looked into this issue, it seems that it is caused by inconsistent internal APIs. When debugging this test file, I get the following results:
```
> /home/sidong/.cache/bazel/_bazel_sidong/338a466d2403fbfe3413e7ca6003e4cf/execroot/org_tensorflow/bazel-out/s390x-opt/bin/tensorflow/python/eager/def_function_test_cpu_only.runfiles/org_tensorflow/tensorflow/python/eager/def_function_test_cpu_only.py(47)testExperimentalCompileRaisesExceptionWhenXlaIsUnsupported()
-> fn([1, 1, 2, 3])
(Pdb) p test_util.is_xla_enabled()
False
(Pdb) p pywrap_tfe.TF_IsXlaEnabled()
True
```
Basically, the test proceeds if `test_util.is_xla_enabled()` is false, and it will raise the exception as intended when `pywrap_tfe.TF_IsXlaEnabled()` is false. The inconsistency caused the exception not correctly raised.
One way to fix it is to discard `test_util.is_xla_enabled()` and only use `pywrap_tfe.TF_IsXlaEnabled()`, but I think maybe it's better to solve this inconsistency issue. I noticed that the `pywrap_tfe.TF_IsXlaEnabled()` API and this test case was added from the same [commit](https://github.com/tensorflow/tensorflow/commit/96e0b87d1e23ac1dd7a7aa984e3f479647267b32), and I assume the cause of inconsistency is that the function `SetXlaIsEnabled()` was called incorrectly. Could you look into this issue and check why the function was called when xla was not enabled? Thanks.

Sidong

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with [TF v2.2](https://colab.research.google.com/gist/amahendrakar/8434fed6f34cd6ea642fbba585c8ba4c/40048.ipynb) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/8ffb1016c0291672d7b9d0508874e083/40048-tf-nightly.ipynb). Please find the attached gist. Thanks!

**Comment by Sidong-Wei** [comment]
Hi @cheshire , I noticed that you contributed to this part of xla code and specifically the `pywrap_tfe.TF_IsXlaEnabled()` flag, could you take a look into this issue and provides some insights? Thank you.

**Comment by cheshire** [comment]
@Sidong-Wei looks like a bug, thanks, I wonder why it passes internally on our CI.

**Comment by Sidong-Wei** [comment]
Looks like it has been fixed by this [commit](https://github.com/tensorflow/tensorflow/commit/c90cf2e18f808f93d315ba35e6f9103065cd0384), close for now.
