### ISSUE TITLE
TFLiteConverter: Exception: Merge of two inputs that differ on more than one predicate

### ISSUE THREAD

**Issue by aselva-eb** [tensorflow/tensorflow#40059]
**System information**
Mac OSX
TF 2.1.0rc1

**Command used to run the converter or code if you’re using the Python API**
If possible, please share a link to Colab/Jupyter/any notebook.

```
    model = tf.saved_model.load(curr_dir + "saved_model")
    concrete_func = model.signatures[
    tf.saved_model.DEFAULT_SERVING_SIGNATURE_DEF_KEY]
    concrete_func.inputs[0].set_shape([1, 256, 256, 3])

    converter = tf.lite.TFLiteConverter.from_concrete_functions([concrete_func])
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]

    tflite_model = converter.convert()

```

**The output from the converter invocation**

```
2020-06-01 14:47:13.833020: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-06-01 14:47:13.844343: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7f9c3ef017f0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-06-01 14:47:13.844362: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-06-01 14:47:17.869419: I tensorflow/core/grappler/devices.cc:60] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0 (Note: TensorFlow was not compiled with CUDA support)
2020-06-01 14:47:17.869495: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2020-06-01 14:47:18.085471: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:797] Optimization results for grappler item: graph_to_optimize
2020-06-01 14:47:18.085496: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:799]   function_optimizer: function_optimizer did nothing. time = 0.002ms.
2020-06-01 14:47:18.085502: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:799]   function_optimizer: function_optimizer did nothing. time = 0ms.
2020-06-01 14:47:24.250143: I tensorflow/core/grappler/devices.cc:60] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0 (Note: TensorFlow was not compiled with CUDA support)
2020-06-01 14:47:24.250232: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2020-06-01 14:47:25.306823: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:797] Optimization results for grappler item: graph_to_optimize
2020-06-01 14:47:25.306844: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:799]   constant_folding: Graph size after: 6392 nodes (-2001), 10177 edges (-2235), time = 673.165ms.
2020-06-01 14:47:25.306853: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:799]   constant_folding: Graph size after: 6392 nodes (0), 10177 edges (0), time = 172.856ms.
Traceback (most recent call last):
  File "/Users/me/object_detection/ssdlite_mobilenetv2/ssdlite_mobilenet_v2_coco_2018_05_09/convert.py", line 33, in <module>
    main()
  File "/Users/me/object_detection/ssdlite_mobilenetv2/ssdlite_mobilenet_v2_coco_2018_05_09/convert.py", line 26, in main
    tflite_model = converter.convert()
  File "/Users/me/miniconda3/envs/tf_lite/lib/python3.7/site-packages/tensorflow/lite/python/lite.py", line 518, in convert
    **converter_kwargs)
  File "/Users/me/miniconda3/envs/tf_lite/lib/python3.7/site-packages/tensorflow/lite/python/convert.py", line 496, in toco_convert_impl
    enable_mlir_converter=enable_mlir_converter)
  File "/Users/me/miniconda3/envs/tf_lite/lib/python3.7/site-packages/tensorflow/lite/python/convert.py", line 227, in toco_convert_protos
    raise ConverterError("See console for info.\n%s\n%s\n" % (stdout, stderr))
tensorflow.lite.python.convert.ConverterError: See console for info.
2020-06-01 14:47:29.716790: W tensorflow/compiler/mlir/lite/python/graphdef_to_tfl_flatbuffer.cc:144] Ignored output_format.
2020-06-01 14:47:29.716811: W tensorflow/compiler/mlir/lite/python/graphdef_to_tfl_flatbuffer.cc:147] Ignored drop_control_dependency.
Traceback (most recent call last):
  File "/Users/me/miniconda3/envs/tf_lite/bin/toco_from_protos", line 8, in <module>
    sys.exit(main())
  File "/Users/me/miniconda3/envs/tf_lite/lib/python3.7/site-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 93, in main
    app.run(main=execute, argv=[sys.argv[0]] + unparsed)
  File "/Users/me/miniconda3/envs/tf_lite/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/Users/me/miniconda3/envs/tf_lite/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/Users/me/miniconda3/envs/tf_lite/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/Users/me/miniconda3/envs/tf_lite/lib/python3.7/site-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 56, in execute
    enable_mlir_converter)
**Exception: Merge of two inputs that differ on more than one predicate** {s(Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/Greater:0,else), s(Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/cond/cond/pred_id:0,then)} and {s(Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/Greater:0,else), s(Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/cond/cond/pred_id:0,else), s(Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/cond/Greater:0,else)}
        for node {{node Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/cond/cond/Merge}}

```

Model obtained from Model Zoo
http://download.tensorflow.org/models/object_detection/ssdlite_mobilenet_v2_coco_2018_05_09.tar.gz

**Any other info / logs**

I'm trying to convert the `ssdlite_mobilenet_v2_coco` pre-trained model from the TF Model Zoo to TFLite. I understand that those models were made on TF1.2, so I was using the saved_model to generate a concrete function (because TFLite doesn't like dynamic input shapes), and from there convert to TFLite. 

Running into conversion errors on a Merge (please see output log above)

I came across this page https://www.tensorflow.org/lite/guide/ops_select outlining that control ops (such as merge) are unsupported, to specify to use TF ops whenever required. But still no luck.

Is there anything strikingly wrong with my process?

**Comment by amahendrakar** [comment]
@aselva-eb,
I was able to reproduce the error with [TF v2.2](https://colab.research.google.com/gist/amahendrakar/ba23d7511c74ab701344158d9c6b80da/40059.ipynb). However, the issue seems to be fixed in the latest [TF-nightly](https://colab.research.google.com/gist/amahendrakar/6982b57d12597e9bbd82af2fa5d8bf12/40059-tf-nightly.ipynb). 
I was able to run the code without any issues. Please find the attached gist. Thanks!

**Comment by aselva-eb** [comment]
@amahendrakar 
Thanks for reproducing and pointing me to a fixed version. Appreciate it! tf-nightly did also solve the issue for me.

However, I noticed that the relative file size of the quantized model is still quite large and comparable to the original pb. Inspecting the weights, they all seem to be float32 types

So I modified my conversion code above to avoid use of the experimental flags:
`converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]` 

replacing it with a stable-version documented configuration:  
`converter.optimizations = [tf.lite.Optimize.DEFAULT]`

In this case the conversion fails again at:

```
error: 'tf.TensorArrayWriteV3' op is neither a custom op nor a flex op
error: failed while converting: 'main': Ops that can be supported by the flex runtime (enabled via setting the -emit-select-tf-ops flag):
        tf.NonMaxSuppressionV2 {T = f32, T_threshold = f32, device = ""}
        tf.Size {device = ""}
        tf.TensorArrayGatherV3 {device = "", element_shape = #tf.shape<100>}
        tf.TensorArrayGatherV3 {device = "", element_shape = #tf.shape<100x4>}
        tf.TensorArrayGatherV3 {device = "", element_shape = #tf.shape<300x300x3>}
        tf.TensorArrayGatherV3 {device = "", element_shape = #tf.shape<3>}
        tf.TensorArrayGatherV3 {device = "", element_shape = #tf.shape<>}
        tf.TensorArrayReadV3 {device = ""}
        tf.TensorArrayScatterV3 {device = ""}
        tf.TensorArraySizeV3 {device = ""}
        tf.TensorArrayV3 {clear_after_read = true, device = "", dtype = f32, dynamic_size = false, element_shape = #tf.shape<*>, identical_element_shapes = false, tensor_array_name = ""}
        tf.TensorArrayV3 {clear_after_read = true, device = "", dtype = i32, dynamic_size = false, element_shape = #tf.shape<*>, identical_element_shapes = false, tensor_array_name = ""}
        tf.TensorArrayWriteV3 {device = ""}
```

**Comment by aselva-eb** [comment]
closing this particular issue as the first issue has been resolved. Thanks @amahendrakar. 

I created a new one for the followup inquiry:
https://github.com/tensorflow/tensorflow/issues/40129
