### ISSUE TITLE
AttributeError: module 'tensorflow.python.framework.ops' has no attribute '_set_call_cpp_shape_fn'

### ISSUE THREAD

**Issue by ollieyeahlong** [tensorflow/tensorflow#40053]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Installed using anaconda and though conda install -c anaconda keras
- TensorFlow version: 1.14.0
- Python version:
- Installed using virtualenv? pip? conda?: condo AND tried using pip with a fresh install
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source): Not sure
- CUDA/cuDNN version: Not using gpu
- GPU model and memory:

**Describe the problem**
I am trying to run a .py program from the anaconda prompt. The program is using tensorflow and keras. I have set up a new condo environment and tried to install tensorflow and keras using both pip and conda. Once in this environment I try to run the code and it produces the error message:
AttributeError: module 'tensorflow.python.framework.ops' has no attribute '_set_call_cpp_shape_fn'

**Provide the exact sequence of commands / steps that you executed before running into the problem**
I activate my new environment, change to the directory of my code, the call python vad.py.

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
(PythonCPU) C:\Users\User\Documents\SpeechRecognition\task4>python vad.py
C:\Users\User\anaconda3\envs\PythonCPU\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\User\anaconda3\envs\PythonCPU\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\User\anaconda3\envs\PythonCPU\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\User\anaconda3\envs\PythonCPU\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Users\User\anaconda3\envs\PythonCPU\lib\site-packages\tensorflow\python\framework\dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Users\User\anaconda3\envs\PythonCPU\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Using TensorFlow backend.
Traceback (most recent call last):
  File "vad.py", line 3, in <module>
    import tensorflow as tf
  File "C:\Users\User\anaconda3\envs\PythonCPU\lib\site-packages\tensorflow\__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\User\anaconda3\envs\PythonCPU\lib\site-packages\tensorflow\python\__init__.py", line 63, in <module>
    from tensorflow.python.framework.framework_lib import *  # pylint: disable=redefined-builtin
  File "C:\Users\User\anaconda3\envs\PythonCPU\lib\site-packages\tensorflow\python\framework\framework_lib.py", line 25, in <module>
    from tensorflow.python.framework.ops import Graph
  File "C:\Users\User\anaconda3\envs\PythonCPU\lib\site-packages\tensorflow\python\framework\ops.py", line 54, in <module>
    from tensorflow.python.platform import app
  File "C:\Users\User\anaconda3\envs\PythonCPU\lib\site-packages\tensorflow\python\platform\app.py", line 23, in <module>
    from absl.app import run as _run
  File "C:\Users\User\anaconda3\envs\PythonCPU\lib\site-packages\absl\app.py", line 35, in <module>
    import pdb
  File "C:\Users\User\anaconda3\envs\PythonCPU\lib\pdb.py", line 76, in <module>
    import code
  File "C:\Users\User\Documents\SpeechRecognition\task4\code.py", line 4, in <module>
    import keras
  File "C:\Users\User\anaconda3\envs\PythonCPU\lib\site-packages\keras\__init__.py", line 3, in <module>
    from . import utils
  File "C:\Users\User\anaconda3\envs\PythonCPU\lib\site-packages\keras\utils\__init__.py", line 6, in <module>
    from . import conv_utils
  File "C:\Users\User\anaconda3\envs\PythonCPU\lib\site-packages\keras\utils\conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "C:\Users\User\anaconda3\envs\PythonCPU\lib\site-packages\keras\backend\__init__.py", line 1, in <module>
    from .load_backend import epsilon
  File "C:\Users\User\anaconda3\envs\PythonCPU\lib\site-packages\keras\backend\load_backend.py", line 90, in <module>
    from .tensorflow_backend import *
  File "C:\Users\User\anaconda3\envs\PythonCPU\lib\site-packages\keras\backend\tensorflow_backend.py", line 9, in <module>
    from tensorflow.python.ops import image_ops as tf_image_ops
  File "C:\Users\User\anaconda3\envs\PythonCPU\lib\site-packages\tensorflow\python\ops\image_ops.py", line 28, in <module>
    from tensorflow.python.ops.gen_image_ops import *
  File "C:\Users\User\anaconda3\envs\PythonCPU\lib\site-packages\tensorflow\python\ops\gen_image_ops.py", line 19, in <module>
    from tensorflow.python.framework import common_shapes as _common_shapes
  File "C:\Users\User\anaconda3\envs\PythonCPU\lib\site-packages\tensorflow\python\framework\common_shapes.py", line 729, in <module>
    ops._set_call_cpp_shape_fn(call_cpp_shape_fn)
AttributeError: module 'tensorflow.python.framework.ops' has no attribute '_set_call_cpp_shape_fn'

**Comment by ollieyeahlong** [comment]
python version is 3.6 sorry forgot to add

**Comment by Saduf2019** [comment]
@ollieyeahlong 
Please refer to these [links](https://stackoverflow.com/questions/40046619/keras-tensorflow-gives-the-error-no-attribute-control-flow-ops) , [link1](https://github.com/tensorflow/models/issues/6177#issuecomment-639569604) let us know if it helps.
Also is there any particular reason for using an old version of tensorflow, would you like to upgrade to later versions and let us know if the issue exist.
