### ISSUE TITLE
Initialize layers.convolution2d from numpy array

### ISSUE THREAD

**Issue by ivankreso** [tensorflow/tensorflow#4016]
I can't find a way to pass a numpy tensor to layers.convolution2d weights/bias initialization arguments.
I added support for this by modifying convolution2d, code is below. I need this feature in order  If you like this solution I can add this feature to other ops also and create a pull request.

First I tried this:
```
import tensorflow as tf
import tensorflow.contrib.layers as layers
import numpy as np

conv1_1 = np.random.rand(3, 3, 3, 64).astype(dtype=np.float32)
inputs = tf.placeholder(tf.float32, shape=(32, 96, 96, 3))
net = layers.convolution2d(inputs, 64, 3, weights_initializer=conv1_1, scope='conv1_1')
```
but get_variable method doesn't allow redundant shape argument when initializing from constant.
```
Traceback (most recent call last):
  File "tf1.py", line 16, in <module>
    net = layers.convolution2d(inputs, 64, 3, weights_initializer=conv1_1, scope='conv1_1')
  File "/usr/lib/python3.5/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 171, in func_with_args
    return func(*args, **current_args)
  File "/usr/lib/python3.5/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 406, in convolution2d
    trainable=trainable)
  File "/usr/lib/python3.5/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 171, in func_with_args
    return func(*args, **current_args)
  File "/usr/lib/python3.5/site-packages/tensorflow/contrib/framework/python/ops/variables.py", line 266, in model_variable
    caching_device=caching_device, device=device)
  File "/usr/lib/python3.5/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 171, in func_with_args
    return func(*args, **current_args)
  File "/usr/lib/python3.5/site-packages/tensorflow/contrib/framework/python/ops/variables.py", line 230, in variable
    caching_device=caching_device)
  File "/usr/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 873, in get_variable
    custom_getter=custom_getter)
  File "/usr/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 700, in get_variable
    custom_getter=custom_getter)
  File "/usr/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 217, in get_variable
    validate_shape=validate_shape)
  File "/usr/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 202, in _true_getter
    caching_device=caching_device, validate_shape=validate_shape)
  File "/usr/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 479, in _get_single_variable
    raise ValueError("If initializer is a constant, do not specify shape.")
ValueError: If initializer is a constant, do not specify shape.
```

I removed redundant arguments but then convolution2d doesn't have default value for them. 
```
net = layers.convolution2d(inputs, weights_initializer=conv1_1, scope='conv1_1')
```

```
Traceback (most recent call last):
  File "tf1.py", line 14, in <module>
    net = layers.convolution2d(inputs, weights_initializer=conv1_1, scope='conv1_1')
  File "/usr/lib/python3.5/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 171, in func_with_args
    return func(*args, **current_args)
TypeError: convolution2d() missing 2 required positional arguments: 'num_outputs' and 'kernel_size'
```

I fixed the problem by adding support inside convolution2d code here:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/layers/python/layers/layers.py#L322
It works now and I don't have to pass redundant arguments.
```
@add_arg_scope
def convolution2d(inputs,
                  num_outputs=None,
                  kernel_size=None,
                  stride=1,
                  padding='SAME',
                  rate=1,
                  activation_fn=nn.relu,
                  normalizer_fn=None,
                  normalizer_params=None,
                  weights_initializer=initializers.xavier_initializer(),
                  weights_regularizer=None,
                  biases_initializer=init_ops.zeros_initializer,
                  biases_regularizer=None,
                  reuse=None,
                  variables_collections=None,
                  outputs_collections=None,
                  trainable=True,
                  scope=None):
  with variable_scope.variable_op_scope([inputs],
                                        scope, 'Conv', reuse=reuse) as sc:
    inputs = ops.convert_to_tensor(inputs)
    dtype = inputs.dtype.base_dtype
    stride_h, stride_w = utils.two_element_tuple(stride)
    if rate > 1 and (stride_h > 1 or stride_w > 1):
      raise ValueError('Only one of rate or stride can be larger than one')
    num_filters_in = utils.last_dimension(inputs.get_shape(), min_rank=4)

    initializing_from_value = False
    if weights_initializer is not None and not callable(weights_initializer):
      initializing_from_value = True
      weights_shape = None
    else:
      if kernel_size == None or num_outputs == None:
        raise ValueError('Kernel size and number of outputs must be defined')
      kernel_h, kernel_w = utils.two_element_tuple(kernel_size)
      weights_shape = [kernel_h, kernel_w,
                       num_filters_in, num_outputs]
    if biases_initializer is not None and not callable(biases_initializer):
      bias_shape = None
    else:
      if num_outputs == None:
        raise ValueError('Number of outputs must be defined')
      bias_shape = [num_outputs]

    weights_collections = utils.get_variable_collections(
        variables_collections, 'weights')
    weights = variables.model_variable('weights',
                                       shape=weights_shape,
                                       dtype=dtype,
                                       initializer=weights_initializer,
                                       regularizer=weights_regularizer,
                                       collections=weights_collections,
                                       trainable=trainable)
    if rate > 1:
      outputs = nn.atrous_conv2d(inputs, weights, rate, padding=padding)
    else:
      outputs = nn.conv2d(inputs, weights, [1, stride_h, stride_w, 1],
                          padding=padding)
    if normalizer_fn:
      normalizer_params = normalizer_params or {}
      outputs = normalizer_fn(outputs, **normalizer_params)
    else:
      if biases_initializer is not None:
        biases_collections = utils.get_variable_collections(
            variables_collections, 'biases')
        biases = variables.model_variable('biases',
                                          shape=bias_shape,
                                          dtype=dtype,
                                          initializer=biases_initializer,
                                          regularizer=biases_regularizer,
                                          collections=biases_collections,
                                          trainable=trainable)
        outputs = nn.bias_add(outputs, biases)
    if activation_fn:
      outputs = activation_fn(outputs)
    return utils.collect_named_outputs(outputs_collections, sc.name, outputs)
```

**Comment by sguada** [comment]
Try passing a lambda function instead.

```
conv1_1 = np.random.rand(3, 3, 3, 64).astype(dtype=np.float32)
inputs = tf.placeholder(tf.float32, shape=(32, 96, 96, 3))
net = layers.convolution2d(inputs, 64, 3, weights_initializer=lambda x: conv1_1, scope='conv1_1')
```

The solution would be to change [variables.variable](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/framework/python/ops/variables.py#L197)  to use shape to validate the initial_value instead of passing it to get_variable()

**Comment by ivankreso** [comment]
With lambda function initializing_from_value flag will stay false in _get_single_variable():
```
Traceback (most recent call last):
...
  File "/usr/lib/python3.5/site-packages/tensorflow/python/ops/variables.py", line 281, in _init_from_args
    self._initial_value = ops.convert_to_tensor(initial_value(),
  File "/usr/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 526, in <lambda>
    init_val = lambda: initializer(shape.as_list(), dtype=dtype)
TypeError: <lambda>() got an unexpected keyword argument 'dtype'
```

I did what you suggested. variables.variable() is a better place for a fix. Below is the code which works for me. Is that ok, should I create a pull request for this?
```
@contrib_add_arg_scope
def variable(name, shape=None, dtype=dtypes.float32, initializer=None,
             regularizer=None, trainable=True, collections=None,
             caching_device=None, device=None):
  # Remove duplicates
  collections = set(collections)
  with ops.device(device or ''):
    # If initializing from constant don't pass shape to get_variable()
    if initializer is not None and not callable(initializer):
      if shape != list(initializer.shape):
          raise ValueError("Shape doesn't match initializer shape: %s != %s."
                           % (shape, list(initializer.shape)))
      shape = None
    return variable_scope.get_variable(name, shape=shape, dtype=dtype,
                                       initializer=initializer,
                                       regularizer=regularizer,
                                       trainable=trainable,
                                       collections=collections,
                                       caching_device=caching_device)
```

**Comment by sguada** [comment]
For small variables initializing them from a value makes sense, however you should know that those values becomes constants in the graph and make the graph bigger, specially if the variables are big.

You can also look at [assign_from_values_fn](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/framework/python/ops/variables.py#L467) which allows you assign values to variables without including them in the graph.

A change in variables.variable would require extra checks and verifications.

**Comment by ivankreso** [comment]
Ok thanks a lot. I did not know that TF keeps a copy of the init values as a constant in the graph and I was not aware of assign_from_values as it is not in the docs yet. From now on I will use assign_from_values and save some memory.

**Comment by geyuxiao** [comment]
@ivankreso  how did you solve it? I faced it again. thks lot about you solvement!
