### ISSUE TITLE
Always exceeds 10% of free system memory.

### ISSUE THREAD

**Issue by fzyai** [tensorflow/tensorflow#40178]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
ubuntu 16.04 LTS
- TensorFlow installed from (source or binary):
conda 4.8.3
- TensorFlow version (use command below):
tensorflow-gpu v2.2.0
- Python version:
python 3.7.7
- GCC/Compiler version (if compiling from source):
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
- CUDA/cuDNN version:
CUDA Version 10.1.168
- GPU model and memory:
2 * GeForce RTX 2080 Ti 11GB

**Describe the current behavior**
I can use the same input data and run the same model correctly on the tensorflow-gpu-v1.14, but it doesn't work when I use the tensorflow-gpu-v2.0 or tensorflow-gpu-v2.2.

After excute the fit function, it will raise an error:
tensorflow.python.framework.errors_impl.InternalError: Failed copying input tensor from /job:localhost/replica:0/task:0/device:CPU:0 to /job:localhost/replica:0/task:0/device:GPU:0 in order to run GatherV2: Dst tensor is not initialized. [Op:GatherV2]

Also, when I change the enviroment to tensorflow-cpu-v2.0 or v2.2, it will work correctly but using CPU, that will be very slow.

**Describe the expected behavior**
It should run as well as when I used tensorflow-gpu-v1.14.
I'm sure the memory of GPU and CPU is enough. I tried many ways to solve it but not worked:
- `
gpus = tf.config.experimental.list_physical_devices('GPU')`
`tf.config.experimental.set_memory_growth(gpus[0], True)`
`tf.config.experimental.set_memory_growth(gpus[1], True)
`
- `os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'`
it will just hide the error message and not help.
- decrease the batch_size for fit, but it still invalid.
- reboot my computer, still not work.
- remove the enviroment and install again, still not work.

Is there anything wrong?

**Standalone code to reproduce the issue**
- x_train.shape: (1254521, 56, 40)
- y_train.shape: (1254521, 2)

My simple train function:
```
import numpy as np
import tensorflow as tf


def train(file_path):
    print('Loading data ...')
    x_train = np.float32(np.random.randint(-8, 8, size=[1254521, 56, 40]))
    y_train = [[1, 0] for _ in range(x_train.shape[0])]
    y_train = np.float32(y_train)

    print(x_train.shape, y_train.shape)

    print('Create model ...')
    data = tf.keras.Input(shape=[56, 40])
    x = tf.keras.layers.Reshape([56, 40, 1])(data)

    cnn_out = tf.keras.layers.Conv2D(8, (20, 5), strides=(1, 2))(x)
    cnn_output = tf.keras.layers.Reshape([37, 18 * 8])(cnn_out)

    gru_out = tf.keras.layers.GRU(20)(cnn_output)

    outputs = tf.keras.layers.Dense(2)(gru_out)

    my_model = tf.keras.Model(inputs=data, outputs=outputs)

    my_model.compile()

    print(my_model.summary())

    my_model.fit(x_train, y_train, epochs=100, batch_size=1024, validation_split=0.1)
    my_model.save(file_path)


if __name__ == '__main__':
    train("test.h5")

```

**Other info / logs** Include any logs or source code that would be helpful to
Full traceback of error:

```
Loading data ...
(1254521, 56, 40) (1254521, 2)
Create model ...
2020-06-05 16:26:08.953877: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-06-05 16:26:08.997184: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-06-05 16:26:08.997775: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce RTX 2080 Ti computeCapability: 7.5
coreClock: 1.635GHz coreCount: 68 deviceMemorySize: 10.76GiB deviceMemoryBandwidth: 573.69GiB/s
2020-06-05 16:26:08.997841: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-06-05 16:26:08.998395: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 1 with properties: 
pciBusID: 0000:08:00.0 name: GeForce RTX 2080 Ti computeCapability: 7.5
coreClock: 1.635GHz coreCount: 68 deviceMemorySize: 10.76GiB deviceMemoryBandwidth: 573.69GiB/s
2020-06-05 16:26:08.998559: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-06-05 16:26:08.999723: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-06-05 16:26:09.000912: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-06-05 16:26:09.001118: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-06-05 16:26:09.002557: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-06-05 16:26:09.003395: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-06-05 16:26:09.006865: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-06-05 16:26:09.007010: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-06-05 16:26:09.007707: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-06-05 16:26:09.008324: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-06-05 16:26:09.008891: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-06-05 16:26:09.009430: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0, 1
2020-06-05 16:26:09.009771: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2020-06-05 16:26:09.042664: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 3192000000 Hz
2020-06-05 16:26:09.043165: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5615ceb22100 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-06-05 16:26:09.043193: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-06-05 16:26:09.182570: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-06-05 16:26:09.182998: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce RTX 2080 Ti computeCapability: 7.5
coreClock: 1.635GHz coreCount: 68 deviceMemorySize: 10.76GiB deviceMemoryBandwidth: 573.69GiB/s
2020-06-05 16:26:09.183062: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-06-05 16:26:09.183455: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 1 with properties: 
pciBusID: 0000:08:00.0 name: GeForce RTX 2080 Ti computeCapability: 7.5
coreClock: 1.635GHz coreCount: 68 deviceMemorySize: 10.76GiB deviceMemoryBandwidth: 573.69GiB/s
2020-06-05 16:26:09.183493: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-06-05 16:26:09.183504: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-06-05 16:26:09.183513: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-06-05 16:26:09.183523: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-06-05 16:26:09.183532: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-06-05 16:26:09.183541: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-06-05 16:26:09.183551: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-06-05 16:26:09.183586: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-06-05 16:26:09.184053: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-06-05 16:26:09.184672: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-06-05 16:26:09.185309: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-06-05 16:26:09.185863: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0, 1
2020-06-05 16:26:09.185958: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-06-05 16:26:09.187361: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-06-05 16:26:09.187379: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      0 1 
2020-06-05 16:26:09.187385: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 0:   N N 
2020-06-05 16:26:09.187389: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 1:   N N 
2020-06-05 16:26:09.187506: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-06-05 16:26:09.187922: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-06-05 16:26:09.188338: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-06-05 16:26:09.188891: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-06-05 16:26:09.189454: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 9860 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:01:00.0, compute capability: 7.5)
2020-06-05 16:26:09.189759: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-06-05 16:26:09.190357: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-06-05 16:26:09.190762: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 10203 MB memory) -> physical GPU (device: 1, name: GeForce RTX 2080 Ti, pci bus id: 0000:08:00.0, compute capability: 7.5)
2020-06-05 16:26:09.192135: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5615cfe5f110 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-06-05 16:26:09.192150: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce RTX 2080 Ti, Compute Capability 7.5
2020-06-05 16:26:09.192155: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (1): GeForce RTX 2080 Ti, Compute Capability 7.5
Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_1 (InputLayer)         [(None, 56, 40)]          0         
_________________________________________________________________
reshape (Reshape)            (None, 56, 40, 1)         0         
_________________________________________________________________
conv2d (Conv2D)              (None, 37, 18, 8)         808       
_________________________________________________________________
reshape_1 (Reshape)          (None, 37, 144)           0         
_________________________________________________________________
gru (GRU)                    (None, 20)                9960      
_________________________________________________________________
dense (Dense)                (None, 2)                 42        
=================================================================
Total params: 10,810
Trainable params: 10,810
Non-trainable params: 0
_________________________________________________________________
None
2020-06-05 16:26:10.028753: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 11240508160 exceeds 10% of free system memory.
2020-06-05 16:26:24.748619: W tensorflow/core/common_runtime/bfc_allocator.cc:434] Allocator (GPU_0_bfc) ran out of memory trying to allocate 10.47GiB (rounded to 11240508160)
Current allocation summary follows.
2020-06-05 16:26:24.748646: I tensorflow/core/common_runtime/bfc_allocator.cc:934] BFCAllocator dump for GPU_0_bfc
2020-06-05 16:26:24.748653: I tensorflow/core/common_runtime/bfc_allocator.cc:941] Bin (256):   Total Chunks: 15, Chunks in use: 15. 3.8KiB allocated for chunks. 3.8KiB in use in bin. 248B client-requested in use in bin.
2020-06-05 16:26:24.748658: I tensorflow/core/common_runtime/bfc_allocator.cc:941] Bin (512):   Total Chunks: 1, Chunks in use: 1. 512B allocated for chunks. 512B in use in bin. 480B client-requested in use in bin.
2020-06-05 16:26:24.748663: I tensorflow/core/common_runtime/bfc_allocator.cc:941] Bin (1024):  Total Chunks: 1, Chunks in use: 1. 1.2KiB allocated for chunks. 1.2KiB in use in bin. 1.0KiB client-requested in use in bin.
2020-06-05 16:26:24.748668: I tensorflow/core/common_runtime/bfc_allocator.cc:941] Bin (2048):  Total Chunks: 2, Chunks in use: 1. 6.2KiB allocated for chunks. 3.2KiB in use in bin. 3.1KiB client-requested in use in bin.
2020-06-05 16:26:24.748675: I tensorflow/core/common_runtime/bfc_allocator.cc:941] Bin (4096):  Total Chunks: 2, Chunks in use: 1. 9.5KiB allocated for chunks. 4.8KiB in use in bin. 4.7KiB client-requested in use in bin.
2020-06-05 16:26:24.748680: I tensorflow/core/common_runtime/bfc_allocator.cc:941] Bin (8192):  Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2020-06-05 16:26:24.748685: I tensorflow/core/common_runtime/bfc_allocator.cc:941] Bin (16384):         Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2020-06-05 16:26:24.748691: I tensorflow/core/common_runtime/bfc_allocator.cc:941] Bin (32768):         Total Chunks: 2, Chunks in use: 1. 91.8KiB allocated for chunks. 33.8KiB in use in bin. 33.8KiB client-requested in use in bin.
2020-06-05 16:26:24.748695: I tensorflow/core/common_runtime/bfc_allocator.cc:941] Bin (65536):         Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2020-06-05 16:26:24.748700: I tensorflow/core/common_runtime/bfc_allocator.cc:941] Bin (131072):        Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2020-06-05 16:26:24.748705: I tensorflow/core/common_runtime/bfc_allocator.cc:941] Bin (262144):        Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2020-06-05 16:26:24.748710: I tensorflow/core/common_runtime/bfc_allocator.cc:941] Bin (524288):        Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2020-06-05 16:26:24.748716: I tensorflow/core/common_runtime/bfc_allocator.cc:941] Bin (1048576):       Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2020-06-05 16:26:24.748721: I tensorflow/core/common_runtime/bfc_allocator.cc:941] Bin (2097152):       Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2020-06-05 16:26:24.748726: I tensorflow/core/common_runtime/bfc_allocator.cc:941] Bin (4194304):       Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2020-06-05 16:26:24.748731: I tensorflow/core/common_runtime/bfc_allocator.cc:941] Bin (8388608):       Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2020-06-05 16:26:24.748736: I tensorflow/core/common_runtime/bfc_allocator.cc:941] Bin (16777216):      Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2020-06-05 16:26:24.748741: I tensorflow/core/common_runtime/bfc_allocator.cc:941] Bin (33554432):      Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2020-06-05 16:26:24.748746: I tensorflow/core/common_runtime/bfc_allocator.cc:941] Bin (67108864):      Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2020-06-05 16:26:24.748751: I tensorflow/core/common_runtime/bfc_allocator.cc:941] Bin (134217728):     Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2020-06-05 16:26:24.748756: I tensorflow/core/common_runtime/bfc_allocator.cc:941] Bin (268435456):     Total Chunks: 1, Chunks in use: 0. 9.63GiB allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2020-06-05 16:26:24.748761: I tensorflow/core/common_runtime/bfc_allocator.cc:957] Bin for 10.47GiB was 256.00MiB, Chunk State: 
2020-06-05 16:26:24.748768: I tensorflow/core/common_runtime/bfc_allocator.cc:963]   Size: 9.63GiB | Requested Size: 0B | in_use: 0 | bin_num: 20, prev:   Size: 33.8KiB | Requested Size: 33.8KiB | in_use: 1 | bin_num: -1
2020-06-05 16:26:24.748773: I tensorflow/core/common_runtime/bfc_allocator.cc:970] Next region of size 10339342080
2020-06-05 16:26:24.748780: I tensorflow/core/common_runtime/bfc_allocator.cc:990] InUse at 7f2a7e000000 of size 1280 next 1
2020-06-05 16:26:24.748784: I tensorflow/core/common_runtime/bfc_allocator.cc:990] InUse at 7f2a7e000500 of size 256 next 5
2020-06-05 16:26:24.748789: I tensorflow/core/common_runtime/bfc_allocator.cc:990] InUse at 7f2a7e000600 of size 256 next 8
2020-06-05 16:26:24.748793: I tensorflow/core/common_runtime/bfc_allocator.cc:990] InUse at 7f2a7e000700 of size 256 next 10
2020-06-05 16:26:24.748797: I tensorflow/core/common_runtime/bfc_allocator.cc:990] InUse at 7f2a7e000800 of size 256 next 11
2020-06-05 16:26:24.748802: I tensorflow/core/common_runtime/bfc_allocator.cc:990] InUse at 7f2a7e000900 of size 256 next 14
2020-06-05 16:26:24.748806: I tensorflow/core/common_runtime/bfc_allocator.cc:990] InUse at 7f2a7e000a00 of size 256 next 16
2020-06-05 16:26:24.748811: I tensorflow/core/common_runtime/bfc_allocator.cc:990] InUse at 7f2a7e000b00 of size 512 next 17
2020-06-05 16:26:24.748815: I tensorflow/core/common_runtime/bfc_allocator.cc:990] InUse at 7f2a7e000d00 of size 256 next 20
2020-06-05 16:26:24.748820: I tensorflow/core/common_runtime/bfc_allocator.cc:990] InUse at 7f2a7e000e00 of size 256 next 21
2020-06-05 16:26:24.748824: I tensorflow/core/common_runtime/bfc_allocator.cc:990] InUse at 7f2a7e000f00 of size 256 next 22
2020-06-05 16:26:24.748828: I tensorflow/core/common_runtime/bfc_allocator.cc:990] InUse at 7f2a7e001000 of size 256 next 23
2020-06-05 16:26:24.748833: I tensorflow/core/common_runtime/bfc_allocator.cc:990] InUse at 7f2a7e001100 of size 256 next 2
2020-06-05 16:26:24.748837: I tensorflow/core/common_runtime/bfc_allocator.cc:990] InUse at 7f2a7e001200 of size 256 next 3
2020-06-05 16:26:24.748841: I tensorflow/core/common_runtime/bfc_allocator.cc:990] InUse at 7f2a7e001300 of size 256 next 4
2020-06-05 16:26:24.748845: I tensorflow/core/common_runtime/bfc_allocator.cc:990] InUse at 7f2a7e001400 of size 256 next 9
2020-06-05 16:26:24.748850: I tensorflow/core/common_runtime/bfc_allocator.cc:990] InUse at 7f2a7e001500 of size 256 next 18
2020-06-05 16:26:24.748854: I tensorflow/core/common_runtime/bfc_allocator.cc:990] Free  at 7f2a7e001600 of size 3072 next 6
2020-06-05 16:26:24.748858: I tensorflow/core/common_runtime/bfc_allocator.cc:990] InUse at 7f2a7e002200 of size 3328 next 7
2020-06-05 16:26:24.748863: I tensorflow/core/common_runtime/bfc_allocator.cc:990] Free  at 7f2a7e002f00 of size 4864 next 19
2020-06-05 16:26:24.748867: I tensorflow/core/common_runtime/bfc_allocator.cc:990] InUse at 7f2a7e004200 of size 4864 next 15
2020-06-05 16:26:24.748872: I tensorflow/core/common_runtime/bfc_allocator.cc:990] Free  at 7f2a7e005500 of size 59392 next 13
2020-06-05 16:26:24.748876: I tensorflow/core/common_runtime/bfc_allocator.cc:990] InUse at 7f2a7e013d00 of size 34560 next 12
2020-06-05 16:26:24.748881: I tensorflow/core/common_runtime/bfc_allocator.cc:990] Free  at 7f2a7e01c400 of size 10339226368 next 18446744073709551615
2020-06-05 16:26:24.748885: I tensorflow/core/common_runtime/bfc_allocator.cc:995]      Summary of in-use Chunks by size: 
2020-06-05 16:26:24.748891: I tensorflow/core/common_runtime/bfc_allocator.cc:998] 15 Chunks of size 256 totalling 3.8KiB
2020-06-05 16:26:24.748895: I tensorflow/core/common_runtime/bfc_allocator.cc:998] 1 Chunks of size 512 totalling 512B
2020-06-05 16:26:24.748900: I tensorflow/core/common_runtime/bfc_allocator.cc:998] 1 Chunks of size 1280 totalling 1.2KiB
2020-06-05 16:26:24.748905: I tensorflow/core/common_runtime/bfc_allocator.cc:998] 1 Chunks of size 3328 totalling 3.2KiB
2020-06-05 16:26:24.748909: I tensorflow/core/common_runtime/bfc_allocator.cc:998] 1 Chunks of size 4864 totalling 4.8KiB
2020-06-05 16:26:24.748914: I tensorflow/core/common_runtime/bfc_allocator.cc:998] 1 Chunks of size 34560 totalling 33.8KiB
2020-06-05 16:26:24.748918: I tensorflow/core/common_runtime/bfc_allocator.cc:1002] Sum Total of in-use chunks: 47.2KiB
2020-06-05 16:26:24.748923: I tensorflow/core/common_runtime/bfc_allocator.cc:1004] total_region_allocated_bytes_: 10339342080 memory_limit_: 10339342080 available bytes: 0 curr_region_allocation_bytes_: 20678684160
2020-06-05 16:26:24.748929: I tensorflow/core/common_runtime/bfc_allocator.cc:1010] Stats: 
Limit:                 10339342080
InUse:                       48384
MaxInUse:                   109824
NumAllocs:                      56
MaxAllocSize:                34560

2020-06-05 16:26:24.748939: W tensorflow/core/common_runtime/bfc_allocator.cc:439] *___________________________________________________________________________________________________
Traceback (most recent call last):
  File "question.py", line 35, in <module>
    train("test.h5")
  File "question.py", line 30, in train
    my_model.fit(x_train, y_train, epochs=100, batch_size=1024, validation_split=0.1)
  File "/home/fzy/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 66, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/home/fzy/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 797, in fit
    shuffle=False))
  File "/home/fzy/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/keras/engine/data_adapter.py", line 1338, in train_validation_split
    functools.partial(_split, indices=train_indices), arrays)
  File "/home/fzy/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/util/nest.py", line 617, in map_structure
    structure[0], [func(*x) for x in entries],
  File "/home/fzy/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/util/nest.py", line 617, in <listcomp>
    structure[0], [func(*x) for x in entries],
  File "/home/fzy/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/keras/engine/data_adapter.py", line 1335, in _split
    return array_ops.gather_v2(t, indices)
  File "/home/fzy/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "/home/fzy/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py", line 4541, in gather_v2
    batch_dims=batch_dims)
  File "/home/fzy/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "/home/fzy/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py", line 4524, in gather
    return gen_array_ops.gather_v2(params, indices, axis, name=name)
  File "/home/fzy/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3755, in gather_v2
    _ops.raise_from_not_ok_status(e, name)
  File "/home/fzy/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 6653, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InternalError: Failed copying input tensor from /job:localhost/replica:0/task:0/device:CPU:0 to /job:localhost/replica:0/task:0/device:GPU:0 in order to run GatherV2: Dst tensor is not initialized. [Op:GatherV2]


```

**Comment by ravikyram** [comment]
@hdu-fzy 

Can you Please modify the code on colab and share the gist. Also, request you provide supporting files to eproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by hdu-fzy** [comment]
I think my problems are consistent with [this](https://github.com/tensorflow/tensorflow/issues/39574).

**Comment by sushreebarsa** [comment]
@fzyai  Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)
To know more see;
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999)

**Comment by Kamlesh364** [comment]
Does anyone has the solution to this issue? I'm facing this issue with the configuration below:
OS: ubuntu20.04.03
TF version: 2.4.0

**Comment by raajuss** [comment]
I got it working by setting up swap memory in my linux.
