### ISSUE TITLE
./configure cannot find Python libraries

### ISSUE THREAD

**Issue by Dapid** [tensorflow/tensorflow#4019]
I can't get the configure step to work:

```
(py35) [david@SQUIDS tensorflow]$ ./configure 
Please specify the location of python. [Default is /home/david/.virtualenvs/py35/bin/python]: 
Do you wish to build TensorFlow with Google Cloud Platform support? [y/N] n
No Google Cloud Platform support will be enabled for TensorFlow
Traceback (most recent call last):
  File "<stdin>", line 14, in <module>
AttributeError: module 'site' has no attribute 'getsitepackages'
Found possible Python library paths:
Please input the desired Python library path to use.  Default is []


ln: failed to create symbolic link 'util/python/python_lib' -> '': No such file or directory
(py35) [david@SQUIDS tensorflow]$ ./configure 
Please specify the location of python. [Default is /home/david/.virtualenvs/py35/bin/python]: 
Do you wish to build TensorFlow with Google Cloud Platform support? [y/N] y
Google Cloud Platform support will be enabled for TensorFlow
Traceback (most recent call last):
  File "<stdin>", line 14, in <module>
AttributeError: module 'site' has no attribute 'getsitepackages'
Found possible Python library paths:
Please input the desired Python library path to use.  Default is []


ln: failed to create symbolic link 'util/python/python_lib' -> '': No such file or directory
```
The repo is clean, at this exact commt:
```
(py35) [david@SQUIDS tensorflow]$ git status 
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
(py35) [david@SQUIDS tensorflow]$ git log | head
commit 8a3107801d15bf8af36221ff5bca0b94bf44d6d3
Author: Derek Murray <derek.murray@gmail.com>
Date:   Tue Aug 23 21:58:57 2016 -0700

    Disable tf_stream_executor in the CMake build. (#4000)
    
    Temporary workaround for issue #3996.

commit cc3153a7a0a23533d14ead34db37e4ccd7892079
Author: Egor-Krivov <egor.krivov@frtk.ru>

```

The system is Fedora Linux with Python 3.5 installed in a virtualenv. Giving it
`/home/david/.virtualenvs/py35/lib64/python3.5` seems to work, but I can't be sure (it is stuck trying to download http://pilotfiber.dl.sourceforge.net/project/boost/boost/1.61.0/boost_1_61_0.tar.gz, but with Firefox I can get it in 5 s).

**Comment by prb12** [comment]
This is not an officially supported configuration.  Please could you direct your question to StackOverflow.

**Comment by Dapid** [comment]
Sorry, what exactly is not supported? The documentation recommends using a virtualenv and Python > 3.3.

**Comment by prb12** [comment]
We only officially support the following:
Operating systems: Ubuntu Linux 14 LTE to 16. Mac OS X El Capitan. CentOS 7 and above
CUDA: 7.0 - 7.5  (soon 8.0)

From the error messages like
```ln: failed to create symbolic link 'util/python/python_lib' -> '': No such file or directory```
it looks like python_config.sh doesn't understand your system.

This is possibly related to #3933 ?
