### ISSUE TITLE
CUDA Toolkit 11.0 RC

### ISSUE THREAD

**Issue by vinhdiesal** [tensorflow/tensorflow#40227]
NVIDIA released their `CUDA 11.0 RC Toolkit`, and was wondering if there is an existing tensorflow-nightly build that can pull it or do I have to build from source which takes around 7 hours?

**Comment by 2er0** [comment]
I tried to build the `master` branch but got and patch issue.

Setup:
* Fedora 32
* Nvidia GTX 1080 Ti
* Cuda 11 + Cudnn 8
* Bazelisk + gcc 10.1.1

```
$ bazel version                                                                                                        
Bazelisk version: v1.5.0
Build label: 3.1.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Apr 22 10:32:27 2020 (1587551547)
Build timestamp: 1587551547
Build timestamp as int: 1587551547
```

Main issue for building TensorFlow manually is that I'm unable to install any of those Cuda versions 10.1/10.2. [forums.developer.nvidia.com](https://forums.developer.nvidia.com/t/cuda-10-1-243-10-1-update-2-ppc64le-run-file-installation-issue/82433/13?u=david.baumgartner)

```
INFO: Repository com_google_protobuf instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule tf_http_archive defined at:
  /…/tensorflow/third_party/repo.bzl:134:19: in <toplevel>
INFO: Repository 'com_google_protobuf' used the following cache hits instead of downloading the corresponding file.
 * Hash 'cfcba2df10feec52a84208693937c17a4b5df7775e1635c1e3baffc487b24c9b' for https://storage.googleapis.com/mirror.tensorflow.org/github.com/protocolbuffers/protobuf/archive/v3.9.2.zip
If the definition of 'com_google_protobuf' was updated, verify that the hashes were also updated.
ERROR: An error occurred during the fetch of repository 'com_google_protobuf':
   Traceback (most recent call last):
        File "/…/tensorflow/third_party/repo.bzl", line 110
                _apply_patch(ctx, <1 more arguments>)
        File "/…/tensorflow/third_party/repo.bzl", line 68, in _apply_patch
                _execute_and_check_ret_code(ctx, <1 more arguments>)
        File "/…/tensorflow/third_party/repo.bzl", line 52, in _execute_and_check_ret_code
                fail(<1 more arguments>)
Non-zero return code(1) when executing 'patch -p1 -d /HOME/.cache/bazel/_bazel_fife/0e7cc962cbb913e6cc324ac59e6b080c/external/com_google_protobuf -i /…/tensorflow/third_party/protobuf/protobuf.patch':
Stdout: 
Stderr: src/main/tools/process-wrapper-legacy.cc:58: "execvp(patch, ...)": No such file or directory
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: no such package '@com_google_protobuf//': Traceback (most recent call last):
        File "/…/tensorflow/third_party/repo.bzl", line 110
                _apply_patch(ctx, <1 more arguments>)
        File "/…/tensorflow/third_party/repo.bzl", line 68, in _apply_patch
                _execute_and_check_ret_code(ctx, <1 more arguments>)
        File "/…/tensorflow/third_party/repo.bzl", line 52, in _execute_and_check_ret_code
                fail(<1 more arguments>)
Non-zero return code(1) when executing 'patch -p1 -d /HOME/.cache/bazel/_bazel_fife/0e7cc962cbb913e6cc324ac59e6b080c/external/com_google_protobuf -i /…/tensorflow/third_party/protobuf/protobuf.patch':
Stdout: 
Stderr: src/main/tools/process-wrapper-legacy.cc:58: "execvp(patch, ...)": No such file or directory
```

**Comment by alanpurple** [comment]
@mihaimaruseac 

does 2.3.0-rc.0 support CUDA 11RC ?

**Comment by mihaimaruseac** [comment]
No, it's being slated for 2.4

**Comment by vinhdiesal** [comment]
We will wait until 2.4 hopefully nvidia won't comeout with CUDA 12 by then.

**Comment by mihaimaruseac** [comment]
Unfortunately we cannot simply support all versions of CUDA. Our CI runs on a specific architecture which is shared by other projects at Google too.

However, TensorFlow is a community product and we welcome any PR which moves us towards newer CUDA toolkits, adds new CI (to run on external host, see SIG Build), while still maintaining compatibility with the internal requirements (which in this case are support for CUDA 10.1).

**Comment by Disfractal** [comment]
+1 for a “prerelease” build with CUDA 11 + CUDNN 8 Support

**Comment by iswarup** [comment]
Surprise Surprise!
[tf-nightly-gpu](https://pypi.org/project/tf-nightly-gpu/) released an hour ago!
![Screenshot from 2020-08-20 23-01-57](https://user-images.githubusercontent.com/10144957/90805568-6b3ca900-e339-11ea-8ed4-94d4a34dfc67.png)
