### ISSUE TITLE
Tensorflow Lite Converter Raise Issue

### ISSUE THREAD

**Issue by sasansharifipour** [tensorflow/tensorflow#40239]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): binary
- TensorFlow version (or github SHA if from source): 2.2.0

**Failure details**
I try to convert TF model to TFlite but converter raise ERROR
 Here is my code :

model = tf.keras.models.load_model(load_path, custom_objects={'loss_dice_coefficient_error': loss_dice_coefficient_error,
                                             'dice_coefficient': dice_coefficient,
                                             'jaccard_coef': jaccard_coef})
    
    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    converter.experimental_new_converter = True
    converter.allow_custom_ops = True
    
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,
                                       tf.lite.OpsSet.SELECT_TF_OPS]
        
    tflite_model = converter.convert()

**Any other info / logs**
Traceback (most recent call last):
  File "G:\AI_library_3\Create_Lite_Model.py", line 89, in <module>
    load_all_models()
  File "G:\AI_library_3\Create_Lite_Model.py", line 81, in load_all_models
    load_model_from_path_convert_to_lite(models_root, "LV_ED", lite_models_root)
  File "G:\AI_library_3\Create_Lite_Model.py", line 73, in load_model_from_path_convert_to_lite
    tflite_model = converter.convert()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\lite\python\lite.py", line 518, in convert
    **converter_kwargs)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\lite\python\convert.py", line 496, in toco_convert_impl
    enable_mlir_converter=enable_mlir_converter)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\lite\python\convert.py", line 227, in toco_convert_protos
    raise ConverterError("See console for info.\n%s\n%s\n" % (stdout, stderr))
tensorflow.lite.python.convert.ConverterError: See console for info.
2020-06-07 17:30:36.154029: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-06-07 17:30:36.154352: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2020-06-07 17:30:40.516629: W tensorflow/compiler/mlir/lite/python/graphdef_to_tfl_flatbuffer.cc:144] Ignored output_format.
2020-06-07 17:30:40.516872: W tensorflow/compiler/mlir/lite/python/graphdef_to_tfl_flatbuffer.cc:147] Ignored drop_control_dependency.
2020-06-07 17:30:40.566746: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2020-06-07 17:30:40.628297: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x1b479ed4240 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-06-07 17:30:40.628652: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-06-07 17:30:40.642470: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2020-06-07 17:30:40.691199: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce GT 610 computeCapability: 2.1
coreClock: 1.62GHz coreCount: 1 deviceMemorySize: 2.00GiB deviceMemoryBandwidth: 9.94GiB/s
2020-06-07 17:30:40.692419: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-06-07 17:30:40.693284: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cublas64_10.dll'; dlerror: cublas64_10.dll not found
2020-06-07 17:30:40.694129: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cufft64_10.dll'; dlerror: cufft64_10.dll not found
2020-06-07 17:30:40.694962: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'curand64_10.dll'; dlerror: curand64_10.dll not found
2020-06-07 17:30:40.695842: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cusolver64_10.dll'; dlerror: cusolver64_10.dll not found
2020-06-07 17:30:40.696682: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cusparse64_10.dll'; dlerror: cusparse64_10.dll not found
2020-06-07 17:30:40.697563: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudnn64_7.dll'; dlerror: cudnn64_7.dll not found
2020-06-07 17:30:40.697849: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1598] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2020-06-07 17:30:40.744757: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-06-07 17:30:40.745082: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      0 
2020-06-07 17:30:40.745282: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 0:   N 
2020-06-07 17:30:40.756749: I tensorflow/compiler/xla/service/platform_util.cc:139] StreamExecutor cuda device (0) is of insufficient compute capability: 3.5 required, device is 2.1
2020-06-07 17:30:40.757309: I tensorflow/compiler/jit/xla_gpu_device.cc:161] Ignoring visible XLA_GPU_JIT device. Device number is 0, reason: Internal: no supported devices found for platform CUDA
loc(callsite("model_1/conv2d_transpose_1/atrous_conv2d_transpose/Conv2DBackpropInput"("C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\eager\def_function.py":865:0) at callsite("C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\eager\def_function.py":959:0 at callsite("C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\lite\python\lite.py":435:0 at callsite("G:\AI_library_3\Create_Lite_Model.py":66:0 at callsite("G:\AI_library_3\Create_Lite_Model.py":81:0 at callsite("G:\AI_library_3\Create_Lite_Model.py":89:0 at callsite("C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\idlelib\run.py":474:0 at callsite("C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\idlelib\run.py":144:0 at "<string>":1:0))))))))): **error: 'tfl.transpose_conv' op expect output type tensor<9x29x38x64xf32>, got tensor<?x?x?x?xf32>**
Traceback (most recent call last):

  File "c:\users\admin\appdata\local\programs\python\python36\lib\runpy.py", line 193, in _run_module_as_main

    "__main__", mod_spec)

  File "c:\users\admin\appdata\local\programs\python\python36\lib\runpy.py", line 85, in _run_code

    exec(code, run_globals)

  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\Scripts\toco_from_protos.exe\__main__.py", line 9, in <module>

  File "c:\users\admin\appdata\local\programs\python\python36\lib\site-packages\tensorflow\lite\toco\python\toco_from_protos.py", line 93, in main

    app.run(main=execute, argv=[sys.argv[0]] + unparsed)

  File "c:\users\admin\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run

    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)

  File "c:\users\admin\appdata\local\programs\python\python36\lib\site-packages\absl\app.py", line 299, in run

    _run_main(main, args)

  File "c:\users\admin\appdata\local\programs\python\python36\lib\site-packages\absl\app.py", line 250, in _run_main

    sys.exit(main(argv))

  File "c:\users\admin\appdata\local\programs\python\python36\lib\site-packages\tensorflow\lite\toco\python\toco_from_protos.py", line 56, in execute

    enable_mlir_converter)

Exception: C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\eager\def_function.py:865:9: error: 'tfl.transpose_conv' op expect output type tensor<9x29x38x64xf32>, got tensor<?x?x?x?xf32>

        self._initialize(args, kwargs, add_initializers_to=initializers)

        ^

C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\eager\def_function.py:959:5: note: called from

    concrete = self._get_concrete_function_garbage_collected(*args, **kwargs)

    ^

C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\lite\python\lite.py:435:5: note: called from

    concrete_func = func.get_concrete_function()

    ^

G:\AI_library_3\Create_Lite_Model.py:66:5: note: called from

    converter = tf.lite.TFLiteConverter.from_keras_model(model)

    ^

G:\AI_library_3\Create_Lite_Model.py:81:5: note: called from

    load_model_from_path_convert_to_lite(models_root, "LV_ED", lite_models_root)

    ^

G:\AI_library_3\Create_Lite_Model.py:89:1: note: called from

load_all_models()    

^

C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\idlelib\run.py:474:17: note: called from

                exec(code, self.locals)

                ^

C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\idlelib\run.py:144:17: note: called from

                ret = method(*args, **kwargs)

                ^

<string>: note: called from

**Comment by abattery** [comment]
I submitted a fix. Could you try the conversion with the next day of tf-nightly ?

**Comment by sasansharifipour** [comment]
Dear @abattery 
I update tf-nightly to version 2.3.0.dev20200607 and it was fixed.

Thank you so much
