### ISSUE TITLE
`from tensorflow import keras` errors if it's in a file named `code.py`

### ISSUE THREAD

**Issue by fredo838** [tensorflow/tensorflow#40265]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ubuntu:18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): v2.2.0-rc4-8-g2b96f3662b 2.2.0 
- Python version: Python 3.8.3
- Bazel version (if compiling from source): N+A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
If you have a single line with `from tensorflow import keras` in a file called `code.py` and run `python3 code.py` you get following error: 
```
Traceback (most recent call last):
  File "code.py", line 1, in <module>
    from tensorflow import keras
  File "/usr/local/lib/python3.8/site-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/usr/local/lib/python3.8/site-packages/tensorflow/python/__init__.py", line 64, in <module>
    from tensorflow.python.framework.framework_lib import *  # pylint: disable=redefined-builtin
  File "/usr/local/lib/python3.8/site-packages/tensorflow/python/framework/framework_lib.py", line 25, in <module>
    from tensorflow.python.framework.ops import Graph
  File "/usr/local/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 64, in <module>
    from tensorflow.python.platform import app
  File "/usr/local/lib/python3.8/site-packages/tensorflow/python/platform/app.py", line 23, in <module>
    from absl.app import run as _run
  File "/usr/local/lib/python3.8/site-packages/absl/app.py", line 35, in <module>
    import pdb
  File "/usr/local/lib/python3.8/pdb.py", line 77, in <module>
    import code
  File "/code.py", line 1, in <module>
    from tensorflow import keras
  File "/usr/local/lib/python3.8/site-packages/tensorflow/keras/__init__.py", line 14, in <module>
    from . import activations
  File "/usr/local/lib/python3.8/site-packages/tensorflow/keras/activations/__init__.py", line 10, in <module>
    from tensorflow.python.keras.activations import deserialize
  File "/usr/local/lib/python3.8/site-packages/tensorflow/python/keras/__init__.py", line 27, in <module>
    from tensorflow.python.keras import models
  File "/usr/local/lib/python3.8/site-packages/tensorflow/python/keras/models.py", line 23, in <module>
    from tensorflow.python.keras import backend as K
  File "/usr/local/lib/python3.8/site-packages/tensorflow/python/keras/backend.py", line 36, in <module>
    from tensorflow.python.client import session as session_module
  File "/usr/local/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 38, in <module>
    from tensorflow.python.framework import sparse_tensor
  File "/usr/local/lib/python3.8/site-packages/tensorflow/python/framework/sparse_tensor.py", line 29, in <module>
    from tensorflow.python.framework import constant_op
  File "/usr/local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py", line 324, in <module>
    ops.register_tensor_conversion_function(
AttributeError: partially initialized module 'tensorflow.python.framework.ops' has no attribute 'register_tensor_conversion_function' (most likely due to a circular import)
```
This does *not* happen when the file is not called exactly `code.py`. 

**Describe the expected behavior**
You can just import the code, no error. 

**Standalone code to reproduce the issue**
`docker run -it --rm python:3 bash`
then 
```
python3 -m pip install -y tensorflow 
echo "from tensorflow import keras" > code.py
python3 code.py # ==> error happens
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
Linked Stackoverflow issue, proving at least 2 people had this issue: 
https://stackoverflow.com/questions/62165354/cannot-import-keras-from-tensorflow-depending-on-if-there-exists-a-file-in-the-c/62243098?noredirect=1#comment110099265_62243098

**Comment by albertz** [comment]
This is not TensorFlow related. In your stack trace, you see:
```
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pdb.py", line 76, in <module>
    import code
```
I.e. the official Python `pdb` package does `import code`, i.e. it loads the [official `code` module](https://docs.python.org/3/library/code.html).

When you start some Python script, it will add the current path to `sys.path` at the very first position. Because of that, you can also not name your script `sys.py`, `os.py`, or the name of any other official Python module.

**Comment by Saduf2019** [comment]
@fredo838 
Please refer to above comment and confirm if we may close this issue
