### ISSUE TITLE
AutoGraph saved model with uint8 input will not convert to tflite

### ISSUE THREAD

**Issue by hegman12** [tensorflow/tensorflow#40268]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Both Windows and Linux
- TensorFlow installed from (source or binary):
From binary with pip and preinstalled on colab

- TensorFlow version (or github SHA if from source):
'2.2.0'

**Command used to run the converter or code if you’re using the Python API**
If possible, please share a link to Colab/Jupyter/any notebook.
https://colab.research.google.com/drive/1cnxZOljJUz_Z-q4MNvvm4nQaRQL5C6Pf#scrollTo=h_QP1TGd3sRa
```
class Net(tf.Module):
    @tf.function(input_signature=[tf.TensorSpec(shape=(1,1,3),dtype=tf.uint8)])
    def process(self,image):
        return image

test_exp=Net()

tf.saved_model.save(test_exp,"saved_model")

converter_tlite=tf.lite.TFLiteConverter.from_saved_model("saved_model")

converter_tlite.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS]

converter_tlite.inference_input_type=tf.uint8
converter_tlite.inference_output_type=tf.uint8

test_tflite=converter_tlite.convert()
```

**The output from the converter invocation**

```
ConverterError: See console for info.
2020-06-08 08:52:53.152754: W tensorflow/compiler/mlir/lite/python/graphdef_to_tfl_flatbuffer.cc:89] Ignored output_format.
2020-06-08 08:52:53.152800: W tensorflow/compiler/mlir/lite/python/graphdef_to_tfl_flatbuffer.cc:95] Ignored drop_control_dependency.
loc("Func/PartitionedCall/input/_0"): error: requires all operands to be either same as or ref type of results
Traceback (most recent call last):
  File "/usr/local/bin/toco_from_protos", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 93, in main
    app.run(main=execute, argv=[sys.argv[0]] + unparsed)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/lite/toco/python/toco_from_protos.py", line 56, in execute
    enable_mlir_converter)
Exception: <unknown>:0: error: loc("Func/PartitionedCall/input/_0"): requires all operands to be either same as or ref type of results
```

**Failure details**
The graph will not convert to tflite. See error above

**Any other info / logs**

Reproducible in Colab. Graph with float32 input works fine

**Comment by Saduf2019** [comment]
I am able to replicate this issue, please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/f11a683353239f85a7b33e98b8d9a7ee/untitled216.ipynb)

**Comment by ethanyanjiali** [comment]
Seeing same error, with tf-nightly 2.3.0.dev20200613, it says:
```
see current operation: %1 = "tf.Identity"(%arg0) {device = ""} : (tensor<?x?x?x3x!tf.quint8>) -> tensor<?x?x?x3xui8>
```

**Comment by mehdi-salehi** [comment]
SAME as above:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\lite-con.py", line 8, in <module>
    tflite_model = converter.convert()
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\lite\python\lite.py", line 1076, in convert
    return super(TFLiteConverterV2, self).convert()
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\lite\python\lite.py", line 899, in convert
    return super(TFLiteFrozenGraphConverterV2,
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\lite\python\lite.py", line 629, in convert
    result = _toco_convert_impl(
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\lite\python\convert.py", line 569, in toco_convert_impl
    data = toco_convert_protos(
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\lite\python\convert.py", line 202, in toco_convert_protos
    raise ConverterError(str(e))
tensorflow.lite.python.convert.ConverterError: <unknown>:0: error: loc("Func/StatefulPartitionedCall/input/_0"): requires all operands and results to have compatible element types
<unknown>:0: note: loc("Func/StatefulPartitionedCall/input/_0"): see current operation: %1 = "tf.Identity"(%arg0) {device = ""} : (tensor<1x?x?x3x!tf.quint8>) -> tensor<1x?x?x3xui8>

**Comment by saikumarchalla** [comment]
Was able to reproduce the error with `dtype = tf.uint8 `but when I changed to` tf.float32` I am not facing issue in TF 2.5 and TF-Nightly versions. Please find the gist [here](https://colab.research.google.com/gist/saikumarchalla/ec471be820d0aa6867c33f484422c053/untitled82.ipynb).Thanks!

**Comment by mohantym** [comment]
Hi @hegman12 ! I used a representative dataset and changed signature type to uint8 to resolve the issue. Attaching[ gist](https://colab.sandbox.google.com/gist/mohantym/1323c3e138ab62713a4b05d1e5827255/untitled82.ipynb#scrollTo=yjiYrreF5Kt6) for [reference](https://www.tensorflow.org/lite/performance/post_training_integer_quant#convert_using_integer-only_quantization).
