### ISSUE TITLE
not tensorflow-GPU "ImportError: DLL load failed: The specified module could not be found." inside Conda / Win10

### ISSUE THREAD

**Issue by manuelvalera** [tensorflow/tensorflow#40295]
**System information**
- OS Platform and Distribution: Windows 10
- Mobile device : none
- TensorFlow installed from (source or binary): pip install tensorflow from conda terminal
- TensorFlow version: not known
- Python version: 3.7.6
- Installed using : pip install tensorflow from conda terminal
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

*not using tensorflow-gpu* 
executing:
import tensorflow

I get the following error:

Traceback (most recent call last):
  File "D:\Programs\Anaconda3\envs\MLKeras\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "D:\Programs\Anaconda3\envs\MLKeras\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "D:\Programs\Anaconda3\envs\MLKeras\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "D:\Programs\Anaconda3\envs\MLKeras\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "D:\Programs\Anaconda3\envs\MLKeras\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "deep_versions.py", line 5, in <module>
    import tensorflow
  File "D:\Programs\Anaconda3\envs\MLKeras\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "D:\Programs\Anaconda3\envs\MLKeras\lib\site-packages\tensorflow\python\__init__.py", line 50, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "D:\Programs\Anaconda3\envs\MLKeras\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 69, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "D:\Programs\Anaconda3\envs\MLKeras\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "D:\Programs\Anaconda3\envs\MLKeras\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "D:\Programs\Anaconda3\envs\MLKeras\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "D:\Programs\Anaconda3\envs\MLKeras\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "D:\Programs\Anaconda3\envs\MLKeras\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by ravikyram** [comment]
@manuelvalera 

What is make/model of your cpu?
I suspect your cpu model does not support AVX instructions sets.See [hardware requirements](https://www.tensorflow.org/install/pip?lang=python3#hardware-requirements)
Make sure to download the [latest microsoft visual c++ redistributable from here.](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads)
.Also, please follow the instructions from to install from [Tensorflow website](https://www.tensorflow.org/install/source_windows).

Please, check Your CPU/Python is on 32 bits?Please, refer #36167 and see if it helps you.Please, refer similar issue #36167 #36151 #36138 #36054 #36045 #36020 #36003 #35988 #35903 #35880 #35865 #35805 #35789 #35773 #35772 #35767 #35766 #35749 #35721 #35618 #35204
Thanks!

**Comment by manuelvalera** [comment]
Hello, thanks for answering,

My processor is not that old and it does comply with the hardware
requirements, make/model is:

Intel i7-670HQ @2.6Ghz, 2592 Mhz, 4 cores, 8 logical processors
x64-based PC

I will take a look to the previous tickets, but any ideas would be
appreciated

**Comment by ravikyram** [comment]
@manuelvalera 

I suspect It may occur because you may not have [Visual C++ Redistributable for Windows.](url)Please, install Installing C++ redistributables and see if it resolve your issue.Thanks!
