### ISSUE TITLE
Custom keras model  train success,but save error

### ISSUE THREAD

**Issue by jifei** [tensorflow/tensorflow#40315]
SRGNNModel train sucess,but when I use tf.saved_model.save to save it, it crashed.
Is it cased by tf.compat.v1.nn.dynamic_rnn ? How can I change it？

-TensorFlow2.2

**Complete Code**

```
# coding=utf-8
"""
 @date  :2020-06-05 17:31
"""
from __future__ import absolute_import, division, print_function, unicode_literals
import tensorflow as tf
import argparse
import csv
import numpy as np
import time
from functools import partial
from tensorflow.keras.layers import Dense, Flatten, Conv2D
from tensorflow.keras import Model
import numpy as np
import csv
import math


class SRGNNModel(Model):
    def __init__(self, n_node, l2, step, lr, decay, lr_dc, batch_size=100, hidden_size=100, out_size=100):
        super(SRGNNModel, self).__init__()
        self.batch_size_num = batch_size
        self.hidden_size = hidden_size
        self.out_size = out_size
        self.n_node = n_node
        self.L2 = l2
        self.step = step
        self.stdv = 1.0 / math.sqrt(self.hidden_size)
        self.nasr_w1 = tf.Varnasr_w1 = tf.Variable(
            tf.random.uniform((self.out_size, self.out_size), -self.stdv, self.stdv), name='nasr_w1', dtype=tf.float32)
        self.nasr_w2 = tf.Variable(tf.random.uniform((self.out_size, self.out_size), -self.stdv, self.stdv),
                                   name='nasr_w2', dtype=tf.float32)
        self.nasr_v = tf.Variable(tf.random.uniform((1, self.out_size), -self.stdv, self.stdv), name='nasrv',
                                  dtype=tf.float32)
        self.nasr_b = tf.Variable(tf.zeros((self.out_size,)), name='nasr_b', dtype=tf.float32)

        self.embedding = tf.Variable(tf.random.uniform((self.n_node, self.hidden_size), -self.stdv, self.stdv),
                                     name='embedding', dtype=tf.float32)
        self.W_in = tf.Variable(tf.random.uniform((self.out_size, self.out_size), -self.stdv, self.stdv), name='W_in',
                                dtype=tf.float32)
        self.b_in = tf.Variable(tf.random.uniform((self.out_size,), -self.stdv, self.stdv), name='b_in',
                                dtype=tf.float32)
        self.W_out = tf.Variable(tf.random.uniform((self.out_size, self.out_size), -self.stdv, self.stdv), name='W_out',
                                 dtype=tf.float32)
        self.b_out = tf.Variable(tf.random.uniform((self.out_size,), -self.stdv, self.stdv), name='b_out',
                                 dtype=tf.float32)
        self.B = tf.Variable(tf.random.uniform((2 * self.out_size, self.out_size), -self.stdv, self.stdv), name='B',
                             dtype=tf.float32)
        self.learning_rate = tf.optimizers.schedules.ExponentialDecay(lr, decay, decay_rate=lr_dc, staircase=True)
        self.opt = tf.optimizers.Adam(self.learning_rate)

    def call(self, x):
        (adj_in, adj_out, alias, item, mask) = x
        self.batch_size = tf.shape(item)[0]
        fin_state = tf.nn.embedding_lookup(self.embedding, item)
        cell = tf.keras.layers.GRUCell(self.out_size)

        adj_in = tf.cast(adj_in, tf.float32)
        adj_out = tf.cast(adj_out, tf.float32)
        mask = tf.cast(mask, tf.float32)
        for i in range(self.step):
            fin_state = tf.reshape(fin_state, [self.batch_size, -1, self.out_size])
            fin_state_in = tf.reshape(tf.matmul(tf.reshape(fin_state, [-1, self.out_size]), self.W_in) + self.b_in,
                                      [self.batch_size, -1, self.out_size])
            fin_state_out = tf.reshape(tf.matmul(tf.reshape(fin_state, [-1, self.out_size]), self.W_out) + self.b_out,
                                       [self.batch_size, -1, self.out_size])

            av = tf.concat([tf.matmul(adj_in, fin_state_in), tf.matmul(adj_out, fin_state_out)], axis=-1)
            init_state = tf.reshape(fin_state, [-1, self.out_size])
            state_output, fin_state = tf.compat.v1.nn.dynamic_rnn(cell=cell,
                                                                  inputs=tf.expand_dims(
                                                                      tf.reshape(av, [-1, 2 * self.out_size]), axis=1),
                                                                  initial_state=init_state
                                                                  )
        re_embedding = tf.reshape(fin_state, [self.batch_size, -1, self.out_size])
        rm = tf.reduce_sum(mask, 1)
        last_id = tf.gather_nd(alias, tf.stack([tf.range(self.batch_size), tf.cast(rm, tf.int32) - 1], axis=1))

        last_h = tf.gather_nd(re_embedding, tf.stack([tf.range(self.batch_size), last_id], axis=1))

        seq_h = tf.stack([tf.nn.embedding_lookup(re_embedding[i], alias[i]) for i in range(self.batch_size_num)],
                         axis=0)
        last = tf.matmul(last_h, self.nasr_w1)
        seq = tf.matmul(tf.reshape(seq_h, [-1, self.out_size]), self.nasr_w2)
        last = tf.reshape(last, [self.batch_size, 1, -1])
        m = tf.nn.sigmoid(last + tf.reshape(seq, [self.batch_size, -1, self.out_size]) + self.nasr_b)
        coef = tf.matmul(tf.reshape(m, [-1, self.out_size]), self.nasr_v, transpose_b=True) * tf.reshape(mask, [-1, 1])
        b = self.embedding[1:]
        ma = tf.concat([tf.reduce_sum(tf.reshape(coef, [self.batch_size, -1, 1]) * seq_h, 1),
                        tf.reshape(last, [-1, self.out_size])], -1)
        y1 = tf.matmul(ma, self.B)
        logits = tf.matmul(y1, b, transpose_b=True)
        return logits


def data_generator(data):
    for example in data:
        yield example


def process_data(row):
    features = row[:-1]
    labels = row[-1]
    items, alias_inputs = tf.unique(features)  # value,index

    vector_length = tf.shape(features)[0]
    n_nodes = tf.shape(items)[0]
    indices = tf.gather(alias_inputs, tf.stack([tf.range(vector_length - 1), tf.range(vector_length - 1) + 1],
                                               axis=0))  # Stack and stagger values
    unique_indices, _ = tf.unique(indices[0] * (vector_length + 1) + indices[1])  # unique(a*x + b)
    unique_indices = tf.sort(unique_indices)  # Sort ascending
    unique_indices = tf.stack(
        [tf.math.floordiv(unique_indices, (vector_length + 1)), tf.math.floormod(unique_indices, (vector_length + 1))],
        axis=1)  # Ungroup and stack
    unique_indices = tf.cast(unique_indices, tf.int64)

    values = tf.ones(tf.shape(unique_indices, out_type=tf.int64)[0], dtype=tf.int64)
    dense_shape = tf.cast([n_nodes, n_nodes], tf.int64)

    adj = tf.SparseTensor(indices=unique_indices, values=values, dense_shape=dense_shape)
    adj = tf.sparse.to_dense(adj)

    u_sum_in_tf = tf.math.reduce_sum(adj, 0)
    u_sum_in_tf = tf.clip_by_value(u_sum_in_tf, 1, tf.reduce_max(u_sum_in_tf))
    A_in = tf.math.divide(adj, u_sum_in_tf)

    u_sum_out_tf = tf.math.reduce_sum(adj, 1)
    u_sum_out_tf = tf.clip_by_value(u_sum_out_tf, 1, tf.reduce_max(u_sum_out_tf))
    A_out = tf.math.divide(tf.transpose(adj), u_sum_out_tf)

    mask = tf.fill(tf.shape(features), 1)

    return A_in, A_out, alias_inputs, items, mask, labels


def input_fn(data, batch_size, max_seq, max_n_node):
    dataset = tf.data.Dataset.from_generator(partial(data_generator, data), output_types=(tf.int32))
    dataset = dataset.map(process_data, num_parallel_calls=tf.data.experimental.AUTOTUNE)
    dataset = dataset.padded_batch(batch_size=batch_size, padded_shapes=(
        [max_n_node, max_n_node],
        [max_n_node, max_n_node],
        [max_seq],
        [max_n_node],
        [max_seq],
        []))

    dataset = dataset.prefetch(buffer_size=tf.data.experimental.AUTOTUNE)
    return dataset


def loss_fn(logits, labels):
    softmax = tf.nn.sparse_softmax_cross_entropy_with_logits(labels=labels - 1, logits=logits)
    loss = tf.reduce_mean(softmax)
    return loss


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--model_path', default='saved_model_test', help='model path')
    parser.add_argument('--method', type=str, default='ggnn', help='ggnn/gat/gcn')
    parser.add_argument('--validation', action='store_true', help='validation')
    parser.add_argument('--epoch', type=int, default=2, help='number of epochs to train for')
    parser.add_argument('--batch_size', type=int, default=10, help='input batch size')
    parser.add_argument('--hidden_size', type=int, default=100, help='hidden state size')
    parser.add_argument('--l2', type=float, default=1e-5, help='l2 penalty')
    parser.add_argument('--lr', type=float, default=0.001, help='learning rate')
    parser.add_argument('--step', type=int, default=1, help='gnn propogation steps')
    parser.add_argument('--nonhybrid', action='store_true', help='global preference')
    parser.add_argument('--lr_dc', type=float, default=0.1, help='learning rate decay rate')
    parser.add_argument('--lr_dc_step', type=int, default=3,
                        help='the number of steps after which the learning rate decay')
    opt = parser.parse_args()
    n_node = 0
    max_seq = 0
    max_n_node = 0
    origin_train_data = np.random.randint(1,50,size=[1000,10]).tolist()
    n_node = max(n_node, np.amax([np.amax(z) for z in origin_train_data]) + 1)
    max_seq = max(max_seq, len(max(origin_train_data, key=len)))
    max_n_node = max(max_n_node, len(max([np.unique(i) for i in origin_train_data], key=len)))
    train_dataset_size = len(origin_train_data)
    print(n_node, max_seq, max_n_node)

    origin_test_data = np.random.randint(1,50,size=[500,10]).tolist()
    n_node = max(n_node, np.amax([np.amax(z) for z in origin_test_data]) + 1)
    max_seq = max(max_seq, len(max(origin_test_data, key=len)))
    max_n_node = max(max_n_node, len(max([np.unique(i) for i in origin_test_data], key=len)))
    test_dataset_size = len(origin_test_data)

    print("n_node:", n_node)
    print("max_seq:", max_seq)
    print("max_n_node:", max_n_node)
    print("train_dataset_size:", train_dataset_size)
    print("test_dataset_size:", test_dataset_size)

    train_loss = tf.keras.metrics.Mean(name='train_loss')

    train_accuracy = tf.keras.metrics.SparseTopKCategoricalAccuracy(k=20)

    test_loss = tf.keras.metrics.Mean(name='test_loss')
    test_accuracy = tf.keras.metrics.SparseTopKCategoricalAccuracy(k=20)

    optimizer = tf.keras.optimizers.Adam()
    train_data = input_fn(origin_train_data, opt.batch_size, max_seq, max_n_node)
    test_data = input_fn(origin_test_data, opt.batch_size, max_seq, max_n_node)

    model = SRGNNModel(n_node=n_node,
                       l2=opt.l2,
                       step=opt.step,
                       lr=opt.lr,
                       decay=opt.lr_dc_step * train_dataset_size / opt.batch_size,
                       lr_dc=opt.lr_dc,
                       batch_size=opt.batch_size,
                       hidden_size=opt.hidden_size,
                       out_size=opt.hidden_size)


    def train_step(inputs, labels):
        with tf.GradientTape() as tape:
            predictions = model(inputs)
            loss = loss_fn(predictions, labels)
        gradients = tape.gradient(loss, model.trainable_variables)
        optimizer.apply_gradients(zip(gradients, model.trainable_variables))
        train_loss(loss)
        train_accuracy(labels - 1, predictions)


    def test_step(inputs, labels):
        predictions = model(inputs)
        loss = loss_fn(predictions, labels)
        test_loss(loss)
        test_accuracy(labels - 1, predictions)


    num = 0
    for epoch in range(opt.epoch):
        train_loss.reset_states()
        train_accuracy.reset_states()
        test_loss.reset_states()
        test_accuracy.reset_states()
        step_template = 'Epoch {},Global step {}, Loss: {}, Recall@20: {}'

        for A_in, A_out, alias_inputs, items, mask, labels in train_data:
            train_step((A_in, A_out, alias_inputs, items, mask), labels)
            num = num + 1

            if num % 10 == 0:
                print(time.strftime('%Y-%m-%d %H:%M:%S ', time.localtime(time.time())) +
                      step_template.format(epoch + 1, num * opt.batch_size, train_loss.result(),
                                           train_accuracy.result() * 100))

        for A_in, A_out, alias_inputs, items, mask, labels in test_data:
            test_step((A_in, A_out, alias_inputs, items, mask), labels)
        template = 'Epoch {}, Loss: {}, Recall@20: {}, Test Loss: {}, Test Recall@20: {}'
        print(time.strftime('%Y-%m-%d %H:%M:%S ', time.localtime(time.time())) +
              template.format(epoch + 1, train_loss.result(), train_accuracy.result() * 100, test_loss.result(),
                              test_accuracy.result() * 100))
    tf.saved_model.save(model, opt.model_path)
```

**Error Messgae**
```
Traceback (most recent call last):
  File "ttt.py", line 257, in <module>
    tf.saved_model.save(model, opt.model_path)
  File "/media/vdb1/application/anaconda3/lib/python3.7/site-packages/tensorflow/python/saved_model/save.py", line 951, in save
    obj, export_dir, signatures, options, meta_graph_def)
  File "/media/vdb1/application/anaconda3/lib/python3.7/site-packages/tensorflow/python/saved_model/save.py", line 1008, in _build_meta_graph
    checkpoint_graph_view)
  File "/media/vdb1/application/anaconda3/lib/python3.7/site-packages/tensorflow/python/saved_model/signature_serialization.py", line 75, in find_function_to_export
    functions = saveable_view.list_functions(saveable_view.root)
  File "/media/vdb1/application/anaconda3/lib/python3.7/site-packages/tensorflow/python/saved_model/save.py", line 143, in list_functions
    self._serialization_cache)
  File "/media/vdb1/application/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 1656, in _list_functions_for_serialization
    Model, self)._list_functions_for_serialization(serialization_cache)
  File "/media/vdb1/application/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 2750, in _list_functions_for_serialization
    .list_functions_for_serialization(serialization_cache))
  File "/media/vdb1/application/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/base_serialization.py", line 87, in list_functions_for_serialization
    fns = self.functions_to_serialize(serialization_cache)
  File "/media/vdb1/application/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/layer_serialization.py", line 77, in functions_to_serialize
    serialization_cache).functions_to_serialize)
  File "/media/vdb1/application/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/layer_serialization.py", line 92, in _get_serialized_attributes
    serialization_cache)
  File "/media/vdb1/application/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/model_serialization.py", line 47, in _get_serialized_attributes_internal
    default_signature = save_impl.default_save_signature(self.obj)
  File "/media/vdb1/application/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/save_impl.py", line 203, in default_save_signature
    fn.get_concrete_function()
  File "/media/vdb1/application/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 959, in get_concrete_function
    concrete = self._get_concrete_function_garbage_collected(*args, **kwargs)
  File "/media/vdb1/application/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 872, in _get_concrete_function_garbage_collected
    *args, **kwargs)
  File "/media/vdb1/application/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2496, in _get_concrete_function_garbage_collected
    graph_function, args, kwargs = self._maybe_define_function(args, kwargs)
  File "/media/vdb1/application/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2777, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/media/vdb1/application/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2667, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/media/vdb1/application/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 981, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/media/vdb1/application/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 441, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/media/vdb1/application/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/saving/saving_utils.py", line 132, in _wrapped_model
    outputs = model(inputs, training=False)
  File "/media/vdb1/application/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 927, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "/media/vdb1/application/anaconda3/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py", line 309, in wrapper
    return func(*args, **kwargs)
  File "ttt.py", line 73, in call
    initial_state=init_state
  File "/media/vdb1/application/anaconda3/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/media/vdb1/application/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/rnn.py", line 707, in dynamic_rnn
    dtype=dtype)
  File "/media/vdb1/application/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/rnn.py", line 916, in _dynamic_rnn_loop
    swap_memory=swap_memory)
  File "/media/vdb1/application/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2688, in while_loop
    back_prop=back_prop)
  File "/media/vdb1/application/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/while_v2.py", line 196, in while_loop
    add_control_dependencies=add_control_dependencies)
  File "/media/vdb1/application/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 981, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/media/vdb1/application/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/while_v2.py", line 174, in wrapped_body
    outputs = body(*_pack_sequence_as(orig_loop_vars, args))
  File "/media/vdb1/application/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/rnn.py", line 884, in _time_step
    (output, new_state) = call_cell()
  File "/media/vdb1/application/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/rnn.py", line 870, in <lambda>
    call_cell = lambda: cell(input_t, state)
  File "/media/vdb1/application/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 897, in __call__
    self._maybe_build(inputs)
  File "/media/vdb1/application/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 2416, in _maybe_build
    self.build(input_shapes)  # pylint:disable=not-callable
  File "/media/vdb1/application/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/utils/tf_utils.py", line 316, in wrapper
    output_shape = fn(instance, input_shape)
  File "/media/vdb1/application/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/layers/recurrent.py", line 1752, in build
    caching_device=default_caching_device)
  File "/media/vdb1/application/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 577, in add_weight
    caching_device=caching_device)
  File "/media/vdb1/application/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py", line 743, in _add_variable_with_custom_getter
    **kwargs_for_getter)
  File "/media/vdb1/application/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer_utils.py", line 141, in make_variable
    shape=variable_shape if variable_shape else None)
  File "/media/vdb1/application/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/variables.py", line 259, in __call__
    return cls._variable_v1_call(*args, **kwargs)
  File "/media/vdb1/application/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/variables.py", line 220, in _variable_v1_call
    shape=shape)
  File "/media/vdb1/application/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/variables.py", line 66, in getter
    return captured_getter(captured_previous, **kwargs)
  File "/media/vdb1/application/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 511, in invalid_creator_scope
    "tf.function-decorated function tried to create "
ValueError: tf.function-decorated function tried to create variables on non-first call.
```

**Comment by amahendrakar** [comment]
@jifei,
On running the code I'm facing an error stating `NameError: name 'Model' is not defined`. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/b494cba70200dfac4ccac5dfaef0c017/40315.ipynb). 

In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here. Thanks!

**Comment by amahendrakar** [comment]
Also, please add ``` (i.e. three back ticks) before and after your code to preserve the indentation and formatting. Thanks!

**Comment by jifei** [comment]
> Also, please add ``` (i.e. three back ticks) before and after your code to preserve the indentation and formatting. Thanks!

Tanks，I update the code.

**Comment by amahendrakar** [comment]
@jifei,
Please take a look at [this solution](https://github.com/tensorflow/tensorflow/issues/27120#issuecomment-540071844) from a similar issue and let us know if it helps. Thanks!

**Comment by guohuiGH** [comment]
I met the same problem (train process ok, not the save).  Do you know how to solve it?

**Comment by amahendrakar** [comment]
@guohuiGH,
Please submit a new issue from [this link](https://github.com/tensorflow/tensorflow/issues/new/choose) and fill in the template, so that we can track the issue there. Thanks!
