### ISSUE TITLE
Tensorflow not working after installing tensorflow-gpu

### ISSUE THREAD

**Issue by busssard** [tensorflow/tensorflow#40409]
### System information

-   i used a stock example
-   OS Platform and Distribution: Windows 8, with JetBrains Pycharm
-   **TensorFlow installed from (source or binary)**: pip
-   **TensorFlow version: 2.0 upgraded to 2.2
-   **Python version**: 3.6
-   **CUDA/cuDNN version**: 11
-   **GPU model and memory**: NVIDIA Geforce 970
-   **Exact command to reproduce**:
```
from keras import backend as K
print(K.tensorflow_backend._get_available_gpus())
```

### Describe the problem
I wanted to start using Keras on my GPU as so far i only used the CPU, and it is rather slow.
However once i downloaded the tensorflow-gpu package the simple 
```
from keras import backend as K
```
produces the following error messages.
I tried upgrading my tensorflow installation from 2.0 to 2.2 but it did not help.
I am a bit helpless and would love to know how to continue.
I have CUDA installed.
Before i installed the tensorflow-gpu package, 
`from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())
`
printed my CPU correctly as a device. NOw it gives the same error message.
So i am assuming the problem is in the installatiuon of tensorflow.
Thank you so musch for your help!

### Source code / logs
`C:\Users\OM\PycharmProjects\intromljolo\venv\Scripts\python.exe C:/Users/OM/AppData/Roaming/JetBrains/PyCharmCE2020.1/scratches/scratch.py
Using TensorFlow backend.
Traceback (most recent call last):
  File "C:\Users\OM\PycharmProjects\intromljolo\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\OM\PycharmProjects\intromljolo\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\OM\PycharmProjects\intromljolo\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/OM/AppData/Roaming/JetBrains/PyCharmCE2020.1/scratches/scratch.py", line 1, in <module>
    from keras import backend as K
  File "C:\Users\OM\PycharmProjects\intromljolo\venv\lib\site-packages\keras\__init__.py", line 3, in <module>
    from . import utils
  File "C:\Users\OM\PycharmProjects\intromljolo\venv\lib\site-packages\keras\utils\__init__.py", line 6, in <module>
    from . import conv_utils
  File "C:\Users\OM\PycharmProjects\intromljolo\venv\lib\site-packages\keras\utils\conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "C:\Users\OM\PycharmProjects\intromljolo\venv\lib\site-packages\keras\backend\__init__.py", line 1, in <module>
    from .load_backend import epsilon
  File "C:\Users\OM\PycharmProjects\intromljolo\venv\lib\site-packages\keras\backend\load_backend.py", line 90, in <module>
    from .tensorflow_backend import *
  File "C:\Users\OM\PycharmProjects\intromljolo\venv\lib\site-packages\keras\backend\tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf
  File "C:\Users\OM\PycharmProjects\intromljolo\venv\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\OM\PycharmProjects\intromljolo\venv\lib\site-packages\tensorflow\python\__init__.py", line 50, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\OM\PycharmProjects\intromljolo\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 69, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\OM\PycharmProjects\intromljolo\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\OM\PycharmProjects\intromljolo\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\OM\PycharmProjects\intromljolo\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

Process finished with exit code 1
`

**Comment by amahendrakar** [comment]
@busssard,
Please take a look at [this comment](https://github.com/tensorflow/tensorflow/issues/36167#issuecomment-577886156) from a similar issue and let us know if it helps. Thanks!

**Comment by busssard** [comment]
@amahendrakar i know that my CPU does not support AVX2 
something python mentioned to me every time i let it run.
But as it was still running on my CPU i did not even consider that it would not be possible to use my GPU..
Is there a workaround? Or is my PC only able to use the CPU :( 
Should i deinstall the tensorflow-gpu package and give up?

**Comment by busssard** [comment]
the answer:

- deinstall all of tensorflow
- instsll tensorflow-gpu 2.0 (2.2 doesnt work maybe a windows 8 bug?)
- install cuda 10 (cuda 11 has no support yet)
- install CuDNN 7.6 (CuDNN 8 has no support yet)
- Set environment variable CUDA_PATH to path of the v10 folder of the CUDA installation
- restart the computer
- magic
