### ISSUE TITLE
GPU sudden explosion during training.

### ISSUE THREAD

**Issue by Frank-Dz** [tensorflow/tensorflow#40413]
**System information**
- OS Platform and Distribution: Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 1.13.1
- Python version: 3.7
- CUDA/cuDNN version: 10.0
- GPU model and memory: Nvidia 2080 8G

When I train the network,  for the first 25 samples of training, usage of memory and GPU were unchanged: 
![image](https://user-images.githubusercontent.com/55009565/84515230-c3827980-acfe-11ea-8241-9c96c3108e7e.png)
![image](https://user-images.githubusercontent.com/55009565/84515258-cd0be180-acfe-11ea-9fa0-400001686f1a.png)

But when it comes to 46-th sample, I got:
![image](https://user-images.githubusercontent.com/55009565/84515433-0b090580-acff-11ea-9edc-d93fc2398526.png)
And the usage of GPU and memory added:
![image](https://user-images.githubusercontent.com/55009565/84515495-1eb46c00-acff-11ea-9780-9413a69546dc.png)
![image](https://user-images.githubusercontent.com/55009565/84515535-31c73c00-acff-11ea-91a2-f207d6f6e472.png)

And when to comes to 96-th sample.

```
Limit:                  7012814029
InUse:                  4755516416
MaxInUse:               5347089664
NumAllocs:                  624595
MaxAllocSize:           2055250688

2020-06-12 22:52:55.958865: W tensorflow/core/common_runtime/bfc_allocator.cc:271] ****************__********************************************************************___***********
2020-06-12 22:52:55.959733: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at aggregate_ops.cc:70 : Resource exhausted: OOM when allocating tensor with shape[129675,512] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
Traceback (most recent call last):
  File "/home/frank/anaconda3/envs/smpl/lib/python3.7/site-packages/tensorflow/python/eager/backprop.py", line 553, in _aggregate_grads
    return gen_math_ops.add_n(gradients)
  File "/home/frank/anaconda3/envs/smpl/lib/python3.7/site-packages/tensorflow/python/ops/gen_math_ops.py", line 428, in add_n
    _six.raise_from(_core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[129675,512] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:AddN]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/frank/PycharmProjects/reconstruction_NN/reconstruction_test.py", line 634, in <module>
    train_model()
  File "/home/frank/PycharmProjects/reconstruction_NN/reconstruction_test.py", line 538, in train_model
    lo = m.train(train_dat, gt_dat, loss_dict)
  File "/home/frank/PycharmProjects/reconstruction_NN/reconstruction_NN.py", line 498, in train
    grad = gtape.gradient(loss_, self.trainable_variables)
  File "/home/frank/anaconda3/envs/smpl/lib/python3.7/site-packages/tensorflow/python/eager/backprop.py", line 946, in gradient
    unconnected_gradients=unconnected_gradients)
  File "/home/frank/anaconda3/envs/smpl/lib/python3.7/site-packages/tensorflow/python/eager/imperative_grad.py", line 72, in imperative_grad
    compat.as_str(unconnected_gradients.value))
  File "/home/frank/anaconda3/envs/smpl/lib/python3.7/site-packages/tensorflow/python/eager/backprop.py", line 126, in _gradient_function
    mock_op = _MockOp(attr_tuple, inputs, outputs, op_name)
SystemError: <class 'tensorflow.python.eager.backprop._MockOp'> returned a result with an error set

Process finished with exit code 1

```

It seems like something wrong with
![image](https://user-images.githubusercontent.com/55009565/84515981-c2058100-acff-11ea-98e6-4da5084f951a.png)

Anyone can help?
Thanks!

Best,
Frank

**Comment by Frank-Dz** [comment]
And when I switch to tf1.15.2, the GPU memory **suddenly** explode at the 68th sample.
```
...

2020-06-12 23:25:31.318690: W tensorflow/core/common_runtime/bfc_allocator.cc:424] ***************_***************************___*****_********___*************************************
2020-06-12 23:25:31.319571: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at aggregate_ops.cc:70 : Resource exhausted: OOM when allocating tensor with shape[129675,512] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
Traceback (most recent call last):
  File "reconstruction_test.py", line 634, in <module>
    train_model()
  File "reconstruction_test.py", line 538, in train_model
    lo = m.train(train_dat, gt_dat, loss_dict)
  File "/home/frank/PycharmProjects/reconstruction_NN/reconstruction_NN.py", line 493, in train
    grad = gtape.gradient(loss_, self.trainable_variables)
  File "/home/frank/anaconda3/envs/smpl/lib/python3.7/site-packages/tensorflow_core/python/eager/backprop.py", line 1015, in gradient
    unconnected_gradients=unconnected_gradients)
  File "/home/frank/anaconda3/envs/smpl/lib/python3.7/site-packages/tensorflow_core/python/eager/imperative_grad.py", line 76, in imperative_grad
    compat.as_str(unconnected_gradients.value))
  File "/home/frank/anaconda3/envs/smpl/lib/python3.7/site-packages/tensorflow_core/python/eager/backprop.py", line 601, in _aggregate_grads
    return gen_math_ops.add_n(gradients)
  File "/home/frank/anaconda3/envs/smpl/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_math_ops.py", line 469, in add_n
    _six.raise_from(_core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[129675,512] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:AddN]
```

**Comment by amahendrakar** [comment]
@Frank-Dz,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here.

Also, please take a look at [this similar](https://stackoverflow.com/a/46067469) StackOverflow issue and let us know if it helps. Thanks!
