### ISSUE TITLE
Please somebody help me......

### ISSUE THREAD

**Issue by LeeJongAnn** [tensorflow/tensorflow#40433]
I tried MUNIT-Tensorflow and I have this problem 

somebody help me please, 

environment = python 3.7 
tensorflow version = 1.4 

WARNING:tensorflow:From main.py:91: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

WARNING:tensorflow:From main.py:94: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

2020-06-13 21:57:38.695873: I tensorflow/core/platform/cpu_feature_guard.cc:145] This TensorFlow binary is optimized with Intel(R) MKL-DNN to use the following CPU instructions in performance critical operations:  AVX AVX2
To enable them in non-MKL-DNN operations, rebuild TensorFlow with the appropriate compiler flags.
2020-06-13 21:57:38.711357: I tensorflow/core/common_runtime/process_util.cc:115] Creating new thread pool with default inter op setting: 8. Tune using inter_op_parallelism_threads for best performance.
##### Information #####
 gan type :  lsgan
 dataset :  summer2winter
 max dataset number :  0
 batch_size :  1
 epoch :  10
 iteration per epoch :  100000
 style in test phase :  3

##### Generator #####
residual blocks :  4
 Style dimension :  8
 MLP dimension :  256
 Down sample :  2
 Up sample :  2

##### Discriminator #####
 Discriminator layer :  4
 Multi-scale Dis :  3
WARNING:tensorflow:From C:\Users\Lee Jong Ann\Desktop\study\Machine Learning\MUNIT-Tensorflow-master\MUNIT-Tensorflow-master\MUNIT.py:236: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING:tensorflow:From C:\Users\Lee Jong Ann\Desktop\study\Machine Learning\MUNIT-Tensorflow-master\MUNIT-Tensorflow-master\utils.py:19: The name tf.read_file is deprecated. Please use tf.io.read_file instead.

Traceback (most recent call last):
  File "C:\Users\Lee Jong Ann\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 527, in _apply_op_helper
    preferred_dtype=default_dtype)
  File "C:\Users\Lee Jong Ann\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1224, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "C:\Users\Lee Jong Ann\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1018, in _TensorTensorConversionFunction
    (dtype.name, t.dtype.name, str(t)))
ValueError: Tensor conversion requested dtype string for Tensor with dtype float32: 'Tensor("args_0:0", shape=(), dtype=float32)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 138, in <module>
    main()
  File "main.py", line 98, in main
    gan.build_model()
  File "C:\Users\Lee Jong Ann\Desktop\study\Machine Learning\MUNIT-Tensorflow-master\MUNIT-Tensorflow-master\MUNIT.py", line 244, in build_model
    trainA = trainA.prefetch(self.batch_size).shuffle(self.dataset_num).map(Image_Data_Class.image_processing, num_parallel_calls=8).apply(batch_and_drop_remainder(self.batch_size)).repeat()
  File "C:\Users\Lee Jong Ann\Anaconda3\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 1776, in map
    self, map_func, num_parallel_calls, preserve_cardinality=False))
  File "C:\Users\Lee Jong Ann\Anaconda3\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 3228, in __init__
    use_legacy_function=use_legacy_function)
  File "C:\Users\Lee Jong Ann\Anaconda3\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 2555, in __init__
    self._function = wrapper_fn._get_concrete_function_internal()
  File "C:\Users\Lee Jong Ann\Anaconda3\lib\site-packages\tensorflow\python\eager\function.py", line 1355, in _get_concrete_function_internal
    *args, **kwargs)
  File "C:\Users\Lee Jong Ann\Anaconda3\lib\site-packages\tensorflow\python\eager\function.py", line 1349, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "C:\Users\Lee Jong Ann\Anaconda3\lib\site-packages\tensorflow\python\eager\function.py", line 1652, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "C:\Users\Lee Jong Ann\Anaconda3\lib\site-packages\tensorflow\python\eager\function.py", line 1545, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "C:\Users\Lee Jong Ann\Anaconda3\lib\site-packages\tensorflow\python\framework\func_graph.py", line 715, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "C:\Users\Lee Jong Ann\Anaconda3\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 2549, in wrapper_fn
    ret = _wrapper_helper(*args)
  File "C:\Users\Lee Jong Ann\Anaconda3\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 2489, in _wrapper_helper
    ret = func(*nested_args)
  File "C:\Users\Lee Jong Ann\Desktop\study\Machine Learning\MUNIT-Tensorflow-master\MUNIT-Tensorflow-master\utils.py", line 19, in image_processing
    x = tf.read_file(filename)
  File "C:\Users\Lee Jong Ann\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_io_ops.py", line 625, in read_file
    "ReadFile", filename=filename, name=name)
  File "C:\Users\Lee Jong Ann\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 550, in _apply_op_helper
    (prefix, dtypes.as_dtype(input_arg.type).name))
TypeError: Input 'filename' of 'ReadFile' Op has type float32 that does not match expected type of string.

**Comment by Saduf2019** [comment]
@LeeJongAnn 
Please refer to issues with similar error:
#36456 #30748 #31102 [link](https://stackoverflow.com/questions/56820327/the-name-tf-session-is-deprecated-please-use-tf-compat-v1-session-instead)  [link1](https://github.com/ipazc/mtcnn/issues/40) [Link2](https://github.com/tensorflow/tensorflow/issues/35550)
Can you please upgrade to later version of tensor flow and let us know if you are facing any issues.

**Comment by LeeJongAnn** [comment]
Thank you , Originally version 2.0 was used , but It doesn't work.. ㅠㅠ

**Comment by LeeJongAnn** [comment]
> Can you please upgrade to later version of tensor flow and let us know if you are facing any issues.

Thank you , Originally version 2.0 was used , but It doesn't work.. ㅠㅠ

**Comment by Saduf2019** [comment]
@LeeJongAnn
Please let us know if you have referred the links shared and was it helpful.

**Comment by LeeJongAnn** [comment]
> @LeeJongAnn
> Please let us know if you have referred the links shared and was it helpful.

Thanks for trying to help ,I am student and It's final exam period (June 18~ 24) so , 
I'll definitely try and let you know

**Comment by LeeJongAnn** [comment]
> @LeeJongAnn
> Please let us know if you have referred the links shared and was it helpful.

I gave up because I couldn't. I'm going to erase it and try it again.

Thank you for trying to help me

**Comment by LeeJongAnn** [comment]
> @LeeJongAnn
> Please let us know if you have referred the links shared and was it helpful.

I gave up because I couldn't. I'm going to erase it and try it again.

Thank you for trying to help me
