### ISSUE TITLE
 _load(spec) ImportError: DLL load failed while importing _pywrap_tensorflow_internal

### ISSUE THREAD

**Issue by pndiaye** [tensorflow/tensorflow#40446]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): calling HMR
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): https://files.pythonhosted.org/packages/af/50/d7da24189d95e2084bb1cc350a8e4acdf1b0c9b3d57def7a348f0d9cb062/tensorflow-2.2.0-cp37-cp37m-win_amd64.whl
- Python version: 3.7
- CUDA/cuDNN version: 10.1
- GPU model and memory: nvidia quadro fx 570
- CPU: Intel Xeon x5450

**Describe the current behavior**
"import tensorflow as tf" fails 
**Describe the expected behavior**
"import tensorflow as tf" doesn't fail 
**Standalone code to reproduce the issue**

**Other info / logs** 
$ python -m export --img_dir C:\Users\dell\Videos\temp\images_data --json_dir C:\Users\dell\Videos\temp\openpose_data --log_dir C:\Users\dell\Videos --output_path C:\Users\dell\Videos\temp\hmr_data.json
Traceback (most recent call last):
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: Une routine d▒initialisation d▒une biblioth▒que de liens dynamiques (DLL) a ▒chou▒.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\DEV\video2mocap\3rdparty\hmr\export.py", line 32, in <module>
    import tensorflow as tf
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\__init__.py", line 50, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 69, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: Une routine d▒initialisation d▒une biblioth▒que de liens dynamiques (DLL) a ▒chou▒.

Failed to load the native TensorFlow runtime.

**Comment by amahendrakar** [comment]
@pndiaye,
Please take a look at [this comment](https://github.com/tensorflow/tensorflow/issues/36167#issuecomment-577886156) from a similar issue and let us know if it helps. Thanks!

**Comment by pndiaye** [comment]
Hi @amahendrakar I have indeed insalled vc_redist and can find msvc140_1.dll and my cpu does support AVX. my version of python 3.7 is 64 bits too.
I have looked in the "C:\Users\dell\AppData\Local\Programs\Python\Python37\Lib\site-packages\tensorflow\python" directory and found "_pywrap_tensorflow_internal.lib" from the error it seems a "dll" is expected?!
thanks for your help

**Comment by pndiaye** [comment]
ps: I can reproduce this issue with tensorflow cpu 1.13.1  and 2.1.0

**Comment by mihaimaruseac** [comment]
TF 1.13 is not supported anymore

**Comment by ymodak** [comment]
@pndiaye Looks like your cpu make does not support AVX instruction set.
See https://ark.intel.com/content/www/us/en/ark/products/34446/intel-xeon-processor-x5450-12m-cache-3-00-ghz-1333-mhz-fsb.html

Also I recommend step 2. Installing TensorFlow (TF) CPU prebuilt binaries from comments upstream.
Thanks!
