### ISSUE TITLE
ImportError: No module named '_pywrap_tensorflow_internal'

### ISSUE THREAD

**Issue by Fennecai** [tensorflow/tensorflow#40459]
**System information**
- OS Platform and Distribution: Windows 10
- TensorFlow installed from (source or binary): i don't know which one; I'm fairly new to this. i installed via the command `pip install --user --upgrade tensorflow` iirc
- TensorFlow version: I am not sure; but its the version that pip currently installs i guess.
- Python version: 3.8.3
- Installed using virtualenv? pip? conda?: pip, as stated above.
- CUDA/cuDNN version: unsure how to find this.
- GPU model and memory: Nvidia GeForce gtx970, 3.5gb (if I'm not mistaken)

**Describe the problem**

I downloaded this repo and attempted to run "test.py" after installing all requirements successfully:
https://github.com/ialhashim/DenseDepth

i get an error message:
`ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'`

**Any other info / logs**
please see test.py from the above repository:
https://github.com/ialhashim/DenseDepth/blob/master/test.py

***here is my stack trace:***

Traceback (most recent call last):
  File "C:\Users\aekna\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tensorflow_internal', [dirname(__file__)])
  File "C:\Program Files (x86)\Python38-32\lib\imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\aekna\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\aekna\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\aekna\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 20, in swig_import_helper
    import _pywrap_tensorflow_internal
ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 8, in <module>
    from keras.models import load_model
  File "C:\Users\aekna\AppData\Roaming\Python\Python38\site-packages\keras\__init__.py", line 3, in <module>
    from . import utils
  File "C:\Users\aekna\AppData\Roaming\Python\Python38\site-packages\keras\utils\__init__.py", line 6, in <module>
    from . import conv_utils
  File "C:\Users\aekna\AppData\Roaming\Python\Python38\site-packages\keras\utils\conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "C:\Users\aekna\AppData\Roaming\Python\Python38\site-packages\keras\backend\__init__.py", line 1, in <module>
    from .load_backend import epsilon
  File "C:\Users\aekna\AppData\Roaming\Python\Python38\site-packages\keras\backend\load_backend.py", line 90, in <module>
    from .tensorflow_backend import *
  File "C:\Users\aekna\AppData\Roaming\Python\Python38\site-packages\keras\backend\tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf
  File "C:\Users\aekna\AppData\Roaming\Python\Python38\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\aekna\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\aekna\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\aekna\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tensorflow_internal', [dirname(__file__)])
  File "C:\Program Files (x86)\Python38-32\lib\imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\aekna\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\aekna\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\aekna\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 20, in swig_import_helper
    import _pywrap_tensorflow_internal
ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'

Failed to load the native TensorFlow runtime.

**Comment by amahendrakar** [comment]
@Fennecai,
The GitHub repo you have linked was tested with TF 1.x. I was able to run the `test.py` file on TF v1.15 without any issues. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/612b9aa8e1daeb46b7f99a94f9840ca5/40459.ipynb). Thanks!

**Comment by basheerghub** [comment]
A similar problem is raised for me. If you can help it will be greatful
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
~\.anaconda\anaconda1\envs\deeplearning\lib\site-packages\tensorflow\python\pywrap_tensorflow.py in <module>
     57 
---> 58   from tensorflow.python.pywrap_tensorflow_internal import *
     59 

~\.anaconda\anaconda1\envs\deeplearning\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py in <module>
     27             return _mod
---> 28     _pywrap_tensorflow_internal = swig_import_helper()
     29     del swig_import_helper

~\.anaconda\anaconda1\envs\deeplearning\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py in swig_import_helper()
     23             try:
---> 24                 _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
     25             finally:

~\.anaconda\anaconda1\envs\deeplearning\lib\imp.py in load_module(name, file, filename, details)
    241         else:
--> 242             return load_dynamic(name, filename, file)
    243     elif type_ == PKG_DIRECTORY:

~\.anaconda\anaconda1\envs\deeplearning\lib\imp.py in load_dynamic(name, path, file)
    341             name=name, loader=loader, origin=path)
--> 342         return _load(spec)
    343 

ImportError: DLL load failed while importing _pywrap_tensorflow_internal: The specified module could not be found.

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-2-027d7fb732fd> in <module>
----> 1 from keras.layers import Convolution2D

~\.anaconda\anaconda1\envs\deeplearning\lib\site-packages\keras\__init__.py in <module>
      1 from __future__ import absolute_import
      2 
----> 3 from . import utils
      4 from . import activations
      5 from . import applications

~\.anaconda\anaconda1\envs\deeplearning\lib\site-packages\keras\utils\__init__.py in <module>
      4 from . import data_utils
      5 from . import io_utils
----> 6 from . import conv_utils
      7 from . import losses_utils
      8 from . import metrics_utils

~\.anaconda\anaconda1\envs\deeplearning\lib\site-packages\keras\utils\conv_utils.py in <module>
      7 from six.moves import range
      8 import numpy as np
----> 9 from .. import backend as K
     10 
     11 

~\.anaconda\anaconda1\envs\deeplearning\lib\site-packages\keras\backend\__init__.py in <module>
----> 1 from .load_backend import epsilon
      2 from .load_backend import set_epsilon
      3 from .load_backend import floatx
      4 from .load_backend import set_floatx
      5 from .load_backend import cast_to_floatx

~\.anaconda\anaconda1\envs\deeplearning\lib\site-packages\keras\backend\load_backend.py in <module>
     88 elif _BACKEND == 'tensorflow':
     89     sys.stderr.write('Using TensorFlow backend.\n')
---> 90     from .tensorflow_backend import *
     91 else:
     92     # Try and load external backend.

~\.anaconda\anaconda1\envs\deeplearning\lib\site-packages\keras\backend\tensorflow_backend.py in <module>
      3 from __future__ import print_function
      4 
----> 5 import tensorflow as tf
      6 from tensorflow.python.eager import context
      7 from tensorflow.python.framework import device as tfdev

~\.anaconda\anaconda1\envs\deeplearning\lib\site-packages\tensorflow\__init__.py in <module>
     39 import sys as _sys
     40 
---> 41 from tensorflow.python.tools import module_util as _module_util
     42 from tensorflow.python.util.lazy_loader import LazyLoader as _LazyLoader
     43 

~\.anaconda\anaconda1\envs\deeplearning\lib\site-packages\tensorflow\python\__init__.py in <module>
     48 import numpy as np
     49 
---> 50 from tensorflow.python import pywrap_tensorflow
     51 
     52 # Protocol buffers

~\.anaconda\anaconda1\envs\deeplearning\lib\site-packages\tensorflow\python\pywrap_tensorflow.py in <module>
     67 for some common reasons and solutions.  Include the entire stack trace
     68 above this error message when asking for help.""" % traceback.format_exc()
---> 69   raise ImportError(msg)
     70 
     71 # pylint: enable=wildcard-import,g-import-not-at-top,unused-import,line-too-long

ImportError: Traceback (most recent call last):
  File "C:\Users\BASHEER\.anaconda\anaconda1\envs\deeplearning\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\BASHEER\.anaconda\anaconda1\envs\deeplearning\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\BASHEER\.anaconda\anaconda1\envs\deeplearning\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\BASHEER\.anaconda\anaconda1\envs\deeplearning\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\BASHEER\.anaconda\anaconda1\envs\deeplearning\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: The specified module could not be found.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help

**Comment by amahendrakar** [comment]
@basheerghub,
[This](https://github.com/tensorflow/tensorflow/issues/36167#issuecomment-577886156) solution from a similar issue should fix the `ImportError`. 

If you still need further help, please submit a new issue from [this link](https://github.com/tensorflow/tensorflow/issues/new/choose) and fill in the template, so that we can track the issue there. Thanks!

**Comment by Myriamesf75** [comment]
It worked for me after doing this command : 

```
pip install tensorflow-gpu == 1.15.5 
```

I was previously with tensorflow-gpu 1.15.0 when it was showing the error
