### ISSUE TITLE
Model trained and saved on GPU fails at model open on CPU 

### ISSUE THREAD

**Issue by margaritageleta** [tensorflow/tensorflow#40456]
Hi, this does not seem right. I have been training some models on TS-877 Ryzen-based NAS with 8 cores and 16 threads, and a GeForce GTX 1060 6GB graphics card, in a gpu-docker container Tensorflow:2.1.1-gpu-notebook (with CUDA version V10.1.243); then I have saved them as usual with `model.save()`. When I open them inside the container, everything works fine:

```
new_model.summary()
Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_word_ids (InputLayer)  [(None, 192)]             0         
_________________________________________________________________
tf_distil_bert_model (TFDist multiple                  134734080 
_________________________________________________________________
tf_op_layer_strided_slice (T multiple                  0         
_________________________________________________________________
dense (Dense)                multiple                  769       
=================================================================
Total params: 134,734,849
Trainable params: 134,734,849
Non-trainable params: 0
_________________________________________________________________
```

**Describe the current behavior**
However, when I try to open this model in my computer, it fails tremendously, the summary shows all empty:
```
2020-06-14 21:38:07.495770: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-06-14 21:38:07.509869: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fb6ff0417a0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-06-14 21:38:07.509888: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________
```

And trying to get any prediction yields all this:
```
2020-06-14 21:38:50.852268: W tensorflow/python/util/util.cc:329] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
Traceback (most recent call last):
  File "open-model.py", line 16, in <module>
    model.save(f'models/CPU_distilbert_batch16_epochs3_maxlen192') 
  File "/Users/Margi7/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 1052, in save
    signatures, options)
  File "/Users/Margi7/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/saving/save.py", line 138, in save_model
    signatures, options)
  File "/Users/Margi7/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/save.py", line 78, in save
    save_lib.save(model, filepath, signatures, options)
  File "/Users/Margi7/anaconda3/lib/python3.6/site-packages/tensorflow/python/saved_model/save.py", line 951, in save
    obj, export_dir, signatures, options, meta_graph_def)
  File "/Users/Margi7/anaconda3/lib/python3.6/site-packages/tensorflow/python/saved_model/save.py", line 1027, in _build_meta_graph
    options.namespace_whitelist)
  File "/Users/Margi7/anaconda3/lib/python3.6/site-packages/tensorflow/python/saved_model/save.py", line 629, in _fill_meta_graph_def
    signatures = _generate_signatures(signature_functions, resource_map)
  File "/Users/Margi7/anaconda3/lib/python3.6/site-packages/tensorflow/python/saved_model/save.py", line 497, in _generate_signatures
    function, mapped_inputs, resource_map)
  File "/Users/Margi7/anaconda3/lib/python3.6/site-packages/tensorflow/python/saved_model/save.py", line 449, in _call_function_with_mapped_captures
    resource_map)
  File "/Users/Margi7/anaconda3/lib/python3.6/site-packages/tensorflow/python/saved_model/save.py", line 372, in _map_captures_to_created_tensors
    ).format(interior))
AssertionError: Tried to export a function which references untracked object Tensor("26682:0", shape=(), dtype=resource).TensorFlow objects (e.g. tf.Variable) captured by functions must be tracked by assigning them to an attribute of a tracked object or assigned to an attribute of the main object directly.
```
Which is really odd. How can I load and do inference, predictions on a CPU machine with a model trained on GPU on another machine?

**Describe the expected behavior**
I expected to be able to open the trained model and make predictions.

**System information where I try to OPEN the model**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No, I followed the examples of Tensorflow docs.
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS Catalina 10.15.5 
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.2.0-rc4-8-g2b96f3662b 2.2.0
- Python version: Python 3.6.4
- CUDA/cuDNN version: no
- GPU model and memory: AMD Radeon Pro 580 (but not used)

**Standalone code to reproduce the issue**
```
import os
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.models import Model
from tensorflow.keras.callbacks import ModelCheckpoint

print(tf.version.VERSION)
print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')))

model = tf.keras.models.load_model(f'models/distilbert_batch16_epochs3_maxlen192')
print(model.summary())

with tf.device('cpu:0'):
    model.save(f'models/CPU_distilbert_batch16_epochs3_maxlen192') 

with tf.device('cpu:0'):
    new_model = tf.keras.models.load_model(f'models/CPU_distilbert_batch16_epochs3_maxlen192')
print(new_model.summary())
```

I cannot upload the model itself because its more than 1 GB, but the summary is shown above.

**Comment by amahendrakar** [comment]
@margaritageleta,
In order to expedite the trouble-shooting process, could you please provide the complete code to generate the model or upload the files to Google Drive and share the link with us. Thanks!

**Comment by margaritageleta** [comment]
Yesterday I had a crazy night trying to figure out what was going on. And I found it. @amahendrakar the versions of tensorflow in the machine were I trained the model and were I tried to retrieve the model were diferent, I switched to an older version (2.1.0) and it worked, yet it was really weird.
