### ISSUE TITLE
Can't load tf 2.1 model trained on ai platform

### ISSUE THREAD

**Issue by fjp** [tensorflow/tensorflow#40527]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution: Ubuntu 18.04 and MacOSX 10.15.5
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 2.1.0 and 2.2.0
- Python version: 3.7 and 3.6

**Describe the current behavior**
Can't load a model locally with tensorflow version 2.1. The model was trained on ai platform with [runtime version 2.1](https://cloud.google.com/ai-platform/training/docs/runtime-version-list#2.1) and saved using `tf.keras.callbacks.ModelCheckpoint(..., save_weights_only=False)`. It is possible to load the model locally with tensorflow version 2.2.
It is also possible to build the model locally and use `load_weights`.

```python
>>> import tensorflow as tf
>>> print(tf.__version__)
2.2.0
>>> tf.keras.models.load_model('/Users/fjp/projects/keras-job-dir/model_checkpoint/model.32-0.00/')
2020-06-17 00:59:39.651511: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-06-17 00:59:39.699145: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7faa9f631160 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-06-17 00:59:39.699171: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
<tensorflow.python.keras.engine.training.Model object at 0x12e9ceb10>
```

Using tf version 2.1 results in `KeyError: 0`:

```python
>>> import tensorflow as tf
>>> print(tf.__version__)
2.1.0
>>> tf.keras.models.load_model('/Users/fjp/projects/keras-job-dir/model_checkpoint/model.32-0.00/')
2020-06-17 01:30:15.614749: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-06-17 01:30:15.628231: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fc502c878b0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-06-17 01:30:15.628254: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/fjp/projects/venvtf/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/save.py", line 150, in load_model
    return saved_model_load.load(filepath, compile)
  File "/Users/fjp/projects/venvtf/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/saved_model/load.py", line 89, in load
    model = tf_load.load_internal(path, loader_cls=KerasObjectLoader)
  File "/Users/fjp/projects/venvtf/lib/python3.7/site-packages/tensorflow_core/python/saved_model/load.py", line 552, in load_internal
    export_dir)
  File "/Users/fjp/projects/venvtf/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/saved_model/load.py", line 118, in __init__
    super(KerasObjectLoader, self).__init__(*args, **kwargs)
  File "/Users/fjp/projects/venvtf/lib/python3.7/site-packages/tensorflow_core/python/saved_model/load.py", line 121, in __init__
    self._load_all()
  File "/Users/fjp/projects/venvtf/lib/python3.7/site-packages/tensorflow_core/python/saved_model/load.py", line 239, in _load_all
    node, setter = self._recreate(proto)
  File "/Users/fjp/projects/venvtf/lib/python3.7/site-packages/tensorflow_core/python/saved_model/load.py", line 322, in _recreate
    return factory[kind]()
  File "/Users/fjp/projects/venvtf/lib/python3.7/site-packages/tensorflow_core/python/saved_model/load.py", line 309, in <lambda>
    "user_object": lambda: self._recreate_user_object(proto.user_object),
  File "/Users/fjp/projects/venvtf/lib/python3.7/site-packages/tensorflow_core/python/saved_model/load.py", line 328, in _recreate_user_object
    return self._recreate_base_user_object(proto)
  File "/Users/fjp/projects/venvtf/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/saved_model/load.py", line 216, in _recreate_base_user_object
    return revived_cls._init_from_metadata(metadata)  # pylint: disable=protected-access
  File "/Users/fjp/projects/venvtf/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/saved_model/load.py", line 297, in _init_from_metadata
    revived_obj = cls(**init_args)
  File "/Users/fjp/projects/venvtf/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/input_layer.py", line 86, in __init__
    batch_size = batch_input_shape[0]
KeyError: 0
```

**Describe the expected behavior**
Loading a model trained on ai platform with runtime version 2.1 should be possible to load locally with tensorflow version 2.1 and its corresponding tf.keras version. tf version 2.2 shouldn't be required to load the model.

**Other info / logs** Include any logs or source code that would be helpful to
Here is the [link](https://drive.google.com/drive/folders/1CZwwfUV0uI3bGqi2b5NAUw5RlUoA_ZLV?usp=sharing) to the model trained on ai platform (runtime version 2.1). For me it is possible to load it locally with tensorflow 2.2 but not with 2.1.

**Comment by Saduf2019** [comment]
@fjp 
Please provide with complete code for us to replicate the issue faced or if possible share a colab gist for us to analyse.

**Comment by fjp** [comment]
@Saduf2019 thanks looking into this. I've created a [Colab notebook](https://colab.research.google.com/drive/1nG5ziQ-bDF35CCrguzFFkRKvXr257z2k?usp=sharing) where you can see that loading the model works with tf 2.2 but not with 2.1 (`KeyError: 0`). 

Please remember that the model was trained on and downloaded from google cloud ai platform which currently supports only [tensorflow 2.1 runtime version](https://cloud.google.com/ai-platform/training/docs/runtime-version-list#2.1).

**Comment by fjp** [comment]
I have a guess why loading the model is only possible with tf 2.2 and not 2.1: From the job log on AI Platform it seems that another package (provided with `--packages` option), which depends on `tensorflow==2.2.0` (not `tensorflow-gpu`), triggered the installation. According to the logs the package was first installed with `pip3 --no-deps` but then again without `--no-deps` which installed tf 2.2. 

I wasn't aware that [newer versions of tensorflow, other than the runtime versions](https://cloud.google.com/ai-platform/training/docs/versioning#custom-tf-versions), could be installed and that this can be done with a package dependency. 

However, also the GPU was used while training. Shouldn't this only be possible when `tensorflow-gpu` is installed? And is it possible to inspect a SavedModel to see which version of tensorflow was used while saving it?

**Comment by ymodak** [comment]
Thanks for sharing your investigation. Version dependency is causing the issue.
`tensorflow==2.2.0` installs both cpu and gpu packages starting TF2.
Also there is no way to identify tensorflow version from the SavedModel.

**Comment by fjp** [comment]
Thanks for your help and the clarification.
