### ISSUE TITLE
The GPUs hang when split a log_prob and gradient computation across a number of GPU devices

### ISSUE THREAD

**Issue by AngelBerihuete** [tensorflow/tensorflow#40571]
**System information**

- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Red Hat - Enterprise Linux Server 7.5 (Maipo)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): v2.2.0-0-g2b96f36 2.2.0
- Python version: 3.7.4
- Bazel version (if compiling from source): 2.0.0
- GCC/Compiler version (if compiling from source): 8.3.0
- CUDA/cuDNN version: 10.1/7.6.4
- GPU model and memory: 4 x GPU NVIDIA V100 (Volta) with 16GB HBM2.

**Describe the current behavior**

Trying to demonstrate how to split a log_prob and gradient computation across a number of GPU devices, the GPUs hang. 

**Describe the expected behavior**

Run inference as expected in multi-GPU environment.

**Standalone code to reproduce the issue**

The attached files are based on the [notebook](https://colab.research.google.com/github/tensorflow/probability/blob/master/discussion/examples/cross_gpu_logprob.ipynb#scrollTo=b4RG2YJQdHGA) shared by @brianwa84 We have not setup logical GPUs as he did, but we have tried to use the 4 physical GPUs in the machine.  

This file hangs

```python 
#!/apps/PYTHON/3.7.4_ML/bin/python 

import sys
import numpy as np
import tensorflow as tf
import tensorflow_probability as tfp


def main():
    tfb, tfd = tfp.bijectors, tfp.distributions

    physical_gpus = tf.config.experimental.list_physical_devices('GPU')
    print(physical_gpus)

#    tf.config.experimental.set_virtual_device_configuration(
#        physical_gpus[0],
#        [tf.config.experimental.VirtualDeviceConfiguration(memory_limit=7000)] * 2)
#    tf.config.experimental.set_virtual_device_configuration(
#        physical_gpus[1],
#        [tf.config.experimental.VirtualDeviceConfiguration(memory_limit=7000)] * 2)
#    gpus = tf.config.list_logical_devices('GPU')
#    print(gpus)

#st = tf.distribute.MirroredStrategy(devices=tf.config.list_logical_devices('GPU'))
    st = tf.distribute.MirroredStrategy()
    print(st.extended.worker_devices)
    ndim = 3
    
    def model():
      Root = tfd.JointDistributionCoroutine.Root
      loc = yield Root(tfb.Shift(.5)(tfd.MultivariateNormalDiag(loc=tf.zeros([ndim]))))
      scale_tril = yield Root(tfb.FillScaleTriL()(tfd.MultivariateNormalDiag(loc=tf.zeros([ndim * (ndim + 1) // 2]))))
      yield tfd.MultivariateNormalTriL(loc=loc, scale_tril=scale_tril)
    
    dist = tfd.JointDistributionCoroutine(model)
    tf.random.set_seed(1)
    loc, scale_tril, _ = dist.sample(seed=2)
    
    samples = dist.sample(value=([loc] * 1024, scale_tril, None), seed=3)[2]
    samples = tf.round(samples * 1000) / 1000
    for dim in reversed(range(ndim)):
      samples = tf.gather(samples, tf.argsort(samples[:,dim]))
    
    print(samples)
    
    def dataset_fn(ctx):
      batch_size = ctx.get_per_replica_batch_size(len(samples))
      d = tf.data.Dataset.from_tensor_slices(samples).batch(batch_size)
      return d.shard(ctx.num_input_pipelines, ctx.input_pipeline_id)
    
    ds = st.experimental_distribute_datasets_from_function(dataset_fn)
    
    observations = next(iter(ds))
    print(observations)

    def log_prob_and_grad(loc, scale_tril, observations):
      ctx = tf.distribute.get_replica_context()
      with tf.GradientTape() as tape:
        tape.watch((loc, scale_tril))
        lp = tf.reduce_sum(dist.log_prob(loc, scale_tril, observations)) / len(samples)
      grad = tape.gradient(lp, (loc, scale_tril))
      return ctx.all_reduce('sum', lp), [ctx.all_reduce('sum', g) for g in grad]
    
    @tf.custom_gradient
    def target_log_prob(loc, scale_tril):
      lp, grads = st.experimental_run_v2(log_prob_and_grad, (loc, scale_tril, observations))
      return lp.values[0], lambda grad_lp: [grad_lp * g.values[0] for g in grads]
    
    singleton_vals = tfp.math.value_and_gradient(target_log_prob, (loc, scale_tril))
    
    kernel = tfp.mcmc.HamiltonianMonteCarlo(target_log_prob, step_size=.35, num_leapfrog_steps=2)
    kernel = tfp.mcmc.TransformedTransitionKernel(kernel, bijector=[tfb.Identity(), tfb.FillScaleTriL()])
    
    @tf.function(autograph=False)
    def sample_chain():
      return tfp.mcmc.sample_chain(
          num_results=200, num_burnin_steps=100,
          current_state=[tf.ones_like(loc), tf.linalg.eye(scale_tril.shape[-1])], 
          kernel=kernel, trace_fn=lambda _, kr: kr.inner_results.is_accepted)
    samps, is_accepted = sample_chain()
    
    print(f'accept rate: {np.mean(is_accepted)}')
    print(f'ess: {tfp.mcmc.effective_sample_size(samps)}')
    
    print(tf.reduce_mean(samps[0], axis=0))

if __name__ == "__main__":
    sys.exit(main())
```

In order to run previous file in a machine with multiple GPUs we use the following batch job 

```
#!/bin/bash 
#SBATCH --job-name='test2_cross_gpu' 
#SBATCH --qos=debug
# 
#SBATCH --nodes=1 
#SBATCH --ntasks=1 
#SBATCH --cpus-per-task=80 
#SBATCH --gres=gpu:2 
#SBATCH --time=00:05:00 
#------- I/O ------- 
#SBATCH -D . 
#SBATCH --output=test2_cross_gpu_%j.out 
#SBATCH --error=test2_cross_gpu_%j.err 
#------- modules ------- 
module purge 
module load gcc/8.3.0 cuda/10.1 cudnn/7.6.4 nccl/2.4.8 tensorrt/6.0.1 openmpi/4.0.1 atlas/3.10.3 scalapack/2.0.2 fftw/3.3.8 szip/2.1.1 ffmpeg/4.2.1 opencv/4.1.1 python/3.7.4_ML 
echo "== Starting run at $(date)" 
echo "== Job ID: ${SLURM_JOBID}" 
echo "== Job NPROCS: ${SLURM_NPROCS}" 
echo "== Job NNODES: ${SLURM_NNODES}" 
echo "== Node list: ${SLURM_NODELIST}" 
echo "== Submit dir. : ${SLURM_SUBMIT_DIR}" 
#------- srun ------ 
srun ./testHangs.py

echo "Done"
```

This file works (second part of the notebook previously referred to)

```python
#!/apps/PYTHON/3.7.4_ML/bin/python 

import sys
import numpy as np
import tensorflow as tf
import tensorflow_probability as tfp


def main():
    tfb, tfd = tfp.bijectors, tfp.distributions

    physical_gpus = tf.config.experimental.list_physical_devices('GPU')
    print(physical_gpus)

#    tf.config.experimental.set_virtual_device_configuration(
#        physical_gpus[0],
#        [tf.config.experimental.VirtualDeviceConfiguration(memory_limit=7000)] * 2)
#    tf.config.experimental.set_virtual_device_configuration(
#        physical_gpus[1],
#        [tf.config.experimental.VirtualDeviceConfiguration(memory_limit=7000)] * 2)
#    gpus = tf.config.list_logical_devices('GPU')
#    print(gpus)

#st = tf.distribute.MirroredStrategy(devices=tf.config.list_logical_devices('GPU'))
    st = tf.distribute.MirroredStrategy()
    print(st.extended.worker_devices)
    ndim = 3
    
    def model():
      Root = tfd.JointDistributionCoroutine.Root
      loc = yield Root(tfb.Shift(.5)(tfd.MultivariateNormalDiag(loc=tf.zeros([ndim]))))
      scale_tril = yield Root(tfb.FillScaleTriL()(tfd.MultivariateNormalDiag(loc=tf.zeros([ndim * (ndim + 1) // 2]))))
      yield tfd.MultivariateNormalTriL(loc=loc, scale_tril=scale_tril)
    
    dist = tfd.JointDistributionCoroutine(model)
    tf.random.set_seed(1)
    loc, scale_tril, _ = dist.sample(seed=2)
    
    samples = dist.sample(value=([loc] * 1024, scale_tril, None), seed=3)[2]
    samples = tf.round(samples * 1000) / 1000
    for dim in reversed(range(ndim)):
      samples = tf.gather(samples, tf.argsort(samples[:,dim]))
    
    print(samples)
    
    batches_per_eval = 2
    
    def dataset_fn(ctx):
      batch_size = ctx.get_per_replica_batch_size(len(samples))
      d = tf.data.Dataset.from_tensor_slices(samples).batch(batch_size // batches_per_eval)
      return d.shard(ctx.num_input_pipelines, ctx.input_pipeline_id).prefetch(2)
    
    ds = st.experimental_distribute_datasets_from_function(dataset_fn)
    
    def log_prob_and_grad(loc, scale_tril, observations, prev_sum_lp, prev_sum_grads):
      with tf.GradientTape() as tape:
        tape.watch((loc, scale_tril))
        lp = tf.reduce_sum(dist.log_prob(loc, scale_tril, observations)) / len(samples)
      grad = tape.gradient(lp, (loc, scale_tril))
      return lp + prev_sum_lp, [g + pg for (g, pg) in zip(grad, prev_sum_grads)]

    @tf.custom_gradient
    def target_log_prob(loc, scale_tril):
      sum_lp = tf.zeros([])
      sum_grads = [tf.zeros_like(x) for x in (loc, scale_tril)]
      sum_lp, sum_grads = st.experimental_run_v2(
          lambda *x: tf.nest.map_structure(tf.identity, x), (sum_lp, sum_grads))
      def reduce_fn(state, observations):
        sum_lp, sum_grads = state
        return st.experimental_run_v2(
            log_prob_and_grad, (loc, scale_tril, observations, sum_lp, sum_grads))
      sum_lp, sum_grads = ds.reduce((sum_lp, sum_grads), reduce_fn)
      sum_lp = st.reduce('sum', sum_lp, None)
      sum_grads = [st.reduce('sum', sg, None) for sg in sum_grads]
      return sum_lp, lambda grad_lp: [grad_lp * sg for sg in sum_grads]
    
    multibatch_vals = tfp.math.value_and_gradient(target_log_prob, (loc, scale_tril))
    
    kernel = tfp.mcmc.HamiltonianMonteCarlo(target_log_prob, step_size=.35, num_leapfrog_steps=2)
    kernel = tfp.mcmc.TransformedTransitionKernel(kernel, bijector=[tfb.Identity(), tfb.FillScaleTriL()])
    
    @tf.function(autograph=False)
    def sample_chain():
      return tfp.mcmc.sample_chain(
          num_results=200, num_burnin_steps=100,
          current_state=[tf.ones_like(loc), tf.linalg.eye(scale_tril.shape[-1])], 
          kernel=kernel, trace_fn=lambda _, kr: kr.inner_results.is_accepted)
    samps, is_accepted = sample_chain()
    
    print(f'accept rate: {np.mean(is_accepted)}')
    print(f'ess: {tfp.mcmc.effective_sample_size(samps)}')
    
    print(tf.reduce_mean(samps[0], axis=0))

if __name__ == "__main__":
    sys.exit(main())
```
And the batch job 

```
#!/bin/bash 
#SBATCH --job-name='test2_cross_gpu' 
#SBATCH --qos=debug
# 
#SBATCH --nodes=1 
#SBATCH --ntasks=1 
#SBATCH --cpus-per-task=80 
#SBATCH --gres=gpu:2 
#SBATCH --time=00:05:00 
#------- I/O ------- 
#SBATCH -D . 
#SBATCH --output=test2_cross_gpu_%j.out 
#SBATCH --error=test2_cross_gpu_%j.err 
#------- modules ------- 
module purge 
module load gcc/8.3.0 cuda/10.1 cudnn/7.6.4 nccl/2.4.8 tensorrt/6.0.1 openmpi/4.0.1 atlas/3.10.3 scalapack/2.0.2 fftw/3.3.8 szip/2.1.1 ffmpeg/4.2.1 opencv/4.1.1 python/3.7.4_ML 
echo "== Starting run at $(date)" 
echo "== Job ID: ${SLURM_JOBID}" 
echo "== Job NPROCS: ${SLURM_NPROCS}" 
echo "== Job NNODES: ${SLURM_NNODES}" 
echo "== Node list: ${SLURM_NODELIST}" 
echo "== Submit dir. : ${SLURM_SUBMIT_DIR}" 
#------- srun ------ 
srun ./testWorks.py

echo "Done"
```

**Other info / logs**

Doing ```strace -F -p [PID]``` we obtain 

```futex(0x4a896234, FUTEX_WAIT_PRIVATE, 1, NULL <unfinished ...> ```

Then ```gdb -p [PID]```
```
#0  syscall () at ../sysdeps/unix/sysv/linux/powerpc/syscall.S:29
#1  0x00007fff63fed144 in nsync::nsync_mu_semaphore_p_with_deadline(nsync::nsync_semaphore_s_*, timespec) ()
   from /apps/PYTHON/3.7.4_ML/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#2  0x00007fff63febd08 in nsync::nsync_sem_wait_with_cancel_(nsync::waiter*, timespec, nsync::nsync_note_s_*) ()
   from /apps/PYTHON/3.7.4_ML/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#3  0x00007fff63fe7414 in nsync::nsync_cv_wait_with_deadline_generic(nsync::nsync_cv_s_*, void*, void (*)(void*), void (*)(void*), timespec, nsync::nsync_note_s_*) ()
   from /apps/PYTHON/3.7.4_ML/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#4  0x00007fff63fe7aec in nsync::nsync_cv_wait_with_deadline(nsync::nsync_cv_s_*, nsync::nsync_mu_s_*, timespec, nsync::nsync_note_s_*) ()
   from /apps/PYTHON/3.7.4_ML/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#5  0x00007fff63fe7b44 in nsync::nsync_cv_wait(nsync::nsync_cv_s_*, nsync::nsync_mu_s_*) ()
   from /apps/PYTHON/3.7.4_ML/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#6  0x00007fff63fe59c4 in tensorflow::condition_variable::wait(tensorflow::mutex_lock&) ()
   from /apps/PYTHON/3.7.4_ML/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#7  0x00007fff59ae1f88 in tensorflow::KernelAndDeviceFunc::Run(tensorflow::ScopedStepContainer*, tensorflow::EagerKernelArgs const&, std::vector<tensorflow::Tensor, std::allocator<tensorflow::Tensor> >*, tensorflow::CancellationManager*, absl::optional<tensorflow::EagerRemoteFunctionParams> const&) ()
   from /apps/PYTHON/3.7.4_ML/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#8  0x00007fff59ae242c in tensorflow::KernelAndDeviceFunc::Run(tensorflow::EagerKernelArgs const&, std::vector<tensorflow::Tensor, std::allocator<tensorflow::Tensor> >*, tensorflow::CancellationManager*, absl::optional<tensorflow::EagerRemoteFunctionParams> const&) ()
   from /apps/PYTHON/3.7.4_ML/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#9  0x00007fff59a9dcd4 in tensorflow::EagerKernelExecute(tensorflow::EagerContext*, absl::InlinedVector<tensorflow::TensorHandle*, 4ul, std::allocator<tensorflow::TensorHandle*> > const&, absl::optional<tensorflow::EagerRemoteFunctionParams> const&, std::unique_ptr<tensorflow::KernelAndDevice, tensorflow::core::RefCountDeleter> const&, tensorflow::GraphCollector*, tensorflow::CancellationManager*, absl::Span<tensorflow::TensorHandle*>) ()
   from /apps/PYTHON/3.7.4_ML/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#10 0x00007fff59a9ef40 in tensorflow::ExecuteNode::Run() ()
   from /apps/PYTHON/3.7.4_ML/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#11 0x00007fff59adb59c in tensorflow::EagerExecutor::SyncExecute(tensorflow::EagerNode*) ()
   from /apps/PYTHON/3.7.4_ML/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#12 0x00007fff59a96e34 in tensorflow::(anonymous namespace)::EagerLocalExecute(tensorflow::EagerOperation*, tensorflow::TensorHandle**, int*) ()
   from /apps/PYTHON/3.7.4_ML/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#13 0x00007fff59a9b4c8 in tensorflow::EagerExecute(tensorflow::EagerOperation*, tensorflow::TensorHandle**, int*) ()
   from /apps/PYTHON/3.7.4_ML/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
---Type <return> to continue, or q <return> to quit---
```

**Comment by AngelBerihuete** [comment]
Dear @sanjoy, Any clue about this issue?

**Comment by AngelBerihuete** [comment]
Dear @Flamefire  and @crccw , due your experience with Slurm, maybe you have a solution to resolve this issue.

**Comment by Flamefire** [comment]
I don't think this is Slurm related at all as there is only a single process on a single node being executed. I guess you can replicated this in an interactive job and maybe also locally or on Cloud resources.

**Comment by AngelBerihuete** [comment]
Thanks @Flamefire .

Yes It's possible to replicate it locally, and works perfectly, but not in Slurm. I've tested with different configurations (multiple nodes and MultiWorkerMirroredStrategy) but none has worked, that's the reason why I put in this issue the simplest one (single process on a single node). 

Remembering your [issue](https://github.com/tensorflow/tensorflow/issues/39417#start-of-content) I have tested also different configurations adding ```@tf.function``` on the code, but again, none progress.

**Comment by AngelBerihuete** [comment]
@Flamefire if it's not asking too much, please, could you test the code on your machines? I would be very grateful.

**Comment by sushreebarsa** [comment]
@AngelBerihuete It looks like you are using an older Version of Tensorflow . Many bugs have been fixed in the latest version. Could you please execute your code using Latest Version 2.4.1 or 2.5 and let us know if the issue still persists? Thanks!
