### ISSUE TITLE
bazel mirror tar gz 404 warning, and build fails

### ISSUE THREAD

**Issue by AmitMY** [tensorflow/tensorflow#40591]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): 
- TensorFlow version: 2.2.0, installed by mediapipe
- Python version: 3.8.3
- Installed using virtualenv? pip? conda?: conda
- Bazel version (if compiling from source): 3.3.0
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**

Trying to build a mediapipe target:
```bash
bazel run mediapipe/examples/desktop/multi_hand_tracking:multi_hand_tracking_cpu 
```

I get:

 ```
Loading: 
Loading: 0 packages loaded  
WARNING: Download from https://mirror.bazel.build/github.com/tensorflow/tensorflow/archive/7c09d15f9fcc14343343c247ebf5b8e0afe3e4aa.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found     
WARNING: Download from http://mirror.tensorflow.org/github.com/bazelbuild/rules_closure/archive/cf1e44edb908e9616030cc83d085989b8e6cd6df.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found   

Analyzing: target //mediapipe/examples/desktop/multi_hand_tracking:multi_hand_tracking_cpu (0 packages loaded, 0 targets configured)  
INFO: Repository local_execution_config_python instantiated at:  
no stack (--record_rule_instantiation_callstack not enabled)     
Repository rule local_python_configure defined at:        
C:/users/amit/_bazel_amit/j6xr7hh5/external/org_tensorflow/third_party/py/python_configure.bzl:275:41: in                                                                                                                                  
ERROR: An error occurred during the fetch of repository 'local_execution_config_python':          Traceback (most recent call last):                     
File "C:/users/amit/_bazel_amit/j6xr7hh5/external/org_tensorflow/third_party/py/python_configure.bzl", 
line 208                                                                                              
get_python_bin(repository_ctx)                                                              
File "C:/users/amit/_bazel_amit/j6xr7hh5/external/org_tensorflow/third_party/remote_config/common.bzl", line 44, in 
get_python_bin                                                                                                    
which(repository_ctx, "python")           
File "C:/users/amit/_bazel_amit/j6xr7hh5/external/org_tensorflow/third_party/remote_config/common.bzl", line 27, in which  execute(repository_ctx, <1 more arguments>)            
File "C:/users/amit/_bazel_amit/j6xr7hh5/external/org_tensorflow/third_party/remote_config/common.bzl", line 208, in execute 
                                  fail(<1 more arguments>)`
```

**Provide the exact sequence of commands / steps that you executed before running into the problem**
```
conda create --name=test python=3
conda activate test
git clone https://github.com/google/mediapipe.git
cd mediapipe
bazel run mediapipe/examples/desktop/multi_hand_tracking:multi_hand_tracking_cpu
```

**Comment by ravikyram** [comment]
@AmitMY 

Request you to fill [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).Please, let us know which TF version you are using?
Provide the exact sequence of commands / steps that you executed before running into the problem.Thanks!

**Comment by AmitMY** [comment]
Sorry, added the sequence of commands + tf version

**Comment by jvishnuvardhan** [comment]
@AmitMY Can you please post this issue in Mediapipe repo? Thanks!
