### ISSUE TITLE
RuntimeError: Mmap of '/home/pi/object-detector/model' failed.

### ISSUE THREAD

**Issue by MevadaRavikumar** [tensorflow/tensorflow#40616]
Hi, 
I am using Raspberry pi 4 Model B, armv7l, with Raspbian stretch. I am having one 'mobilenet_v2_1.0_224_quant_edgetpu.tflite' model which I want to run with the google coral edge TPU. When I am trying to run the model it fails. 
I have used 658 images of two classes. I have also used same images for the training and validation. 
What can be the reason (not enough memory, TPU is damaged, the model is not prepared properly )?  How can I get to know the edge TPU is working or not? How can I fix it? 

Her is the traceback call: 

     pi@raspberrypi:~/object-detector $ python3 detect_object_video_edge.py --model  
    /home/pi/object-mask-detector/model --labels /home/pi/object-detector/model/object_labels.txt
    [INFO] parsing class labels...
    [INFO] loading Coral model...
    Traceback (most recent call last):
      File "detect_object_video_edge.py", line 29, in <module>
        model = DetectionEngine(args["model"])
      File "/usr/lib/python3/dist-packages/edgetpu/detection/engine.py", line 73, in __init__
        super().__init__(model_path)
      File "/usr/lib/python3/dist-packages/edgetpu/basic/basic_engine.py", line 92, in __init__
        self._engine = BasicEnginePythonWrapper.CreateFromFile(model_path)
    RuntimeError: Mmap of '/home/pi/object-detector/model' failed.

**Comment by MevadaRavikumar** [comment]
It got solved by adding the explicit path of the model rather than the directory where the model got saved.
