### ISSUE TITLE
UnidentifiedImageError when I try to train my model

### ISSUE THREAD

**Issue by anis-agwan** [tensorflow/tensorflow#40637]
UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x63a807fb0>

Using Keras library
OS: macOS Catalina
Python version: 3.7.6
Pillow version: PIL 7.1.2
Keras version: 2.3.1

```
classifier.fit_generator(training_set,
steps_per_epoch = 914,
epochs = 25,
validation_data = test_set,
validation_steps = 237)
```
![83977734-8134f300-a920-11ea-980d-6309847697c8](https://user-images.githubusercontent.com/59297399/85206340-fea82c80-b33e-11ea-8277-6708e7f6b554.png)

**Comment by amahendrakar** [comment]
@anis-agwan,
In order to reproduce the issue reported here, could you please provide the complete code, the TensorFlow version and the dataset you are using. Thanks!

**Comment by anis-agwan** [comment]
I have used only Keras for the model training

**Comment by anis-agwan** [comment]
```
from keras.models import Sequential
from keras.layers import Convolution2D
from keras.layers import MaxPooling2D
from keras.layers import Flatten
from keras.layers import Dense
from keras.callbacks import ModelCheckpoint

classifier = Sequential()

classifier.add(Convolution2D(32, 3, 3, input_shape = (64, 64, 3), activation = 'relu'))
classifier.add(MaxPooling2D(pool_size = (2, 2)))

classifier.add(Convolution2D(32, 3, 3, activation = 'relu'))
classifier.add(MaxPooling2D(pool_size = (2, 2)))

classifier.add(Flatten())

classifier.add(Dense(output_dim = 128, activation = 'relu'))
classifier.add(Dense(output_dim = 1, activation = 'sigmoid'))

classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

from keras.preprocessing.image import ImageDataGenerator

train_datagen = ImageDataGenerator(
        rescale = 1./255,
        shear_range = 0.2,
        zoom_range = 0.2,
        horizontal_flip = True)

test_datagen = ImageDataGenerator(rescale=1./255)

training_set = train_datagen.flow_from_directory(
        'dataset/training_set',
        target_size=(64, 64),
        batch_size=32,
        class_mode='binary')

test_set = test_datagen.flow_from_directory(
        'dataset/test_set',
        target_size=(64, 64),
        batch_size=32,
        class_mode='binary') 

checkpoint = ModelCheckpoint("best_model.hdf5", monitor='loss', verbose=1,
    save_best_only=True, mode='auto', period=1)

classifier.fit_generator(
        training_set,
        steps_per_epoch=914,
        epochs=10,
        validation_data=test_set,
        validation_steps=239,
        callbacks=[checkpoint])



classifier.save("model2.h5")
```

**Comment by amahendrakar** [comment]
@anis-agwan,
I was able to run the code without any issues with a sample dataset. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/4640d6115e0e5f668852eff867e38a7c/40637.ipynb). 

Also, please make sure your folder are in the below structure. 
```
dataset    
│
└───training_set
│   └───abc
│   └───xyz
│   
└───test_set
    └───abc
    └───xyz
```

Thanks!

**Comment by anis-agwan** [comment]
@amahendrakar  Is it a possibility that my dataset is corrupted?

**Comment by amahendrakar** [comment]
>Is it a possibility that my dataset is corrupted?

@anis-agwan,
Seems like it. To confirm that it is not a TensorFlow issue, could you please check if you are able to run the code using a different dataset. Thanks!

**Comment by murdav** [comment]
I had a similar issue while I was using `model.predict` on 130,000 images. My script crashed after a few hours. 

```
test_datagen = ImageDataGenerator(rescale=1./255)
test_generator = test_datagen.flow_from_directory(
    dataset_path,
    classes=['test'],
    target_size=(528, 528),
    batch_size=BATCH_SIZE,
    # don't generate labels
    class_mode=None,
    # don't shuffle
    shuffle=False)
probabilities = model.predict(test_generator, steps=steps)
```

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/murarda/.vscode/extensions/ms-python.python-2020.11.371526539/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/home/murarda/.vscode/extensions/ms-python.python-2020.11.371526539/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/murarda/.vscode/extensions/ms-python.python-2020.11.371526539/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 267, in run_file
    runpy.run_path(options.target, run_name=compat.force_str("__main__"))
  File "/usr/lib/python3.6/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/usr/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/var/www/img4drm/src/scripts/test_fs.py", line 77, in <module>
    probabilities = model.predict(test_generator, steps=steps)
  File "/srv/virtualenvs/smfr/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 130, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/srv/virtualenvs/smfr/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1579, in predict
    steps_per_execution=self._steps_per_execution)
  File "/srv/virtualenvs/smfr/lib/python3.6/site-packages/tensorflow/python/keras/engine/data_adapter.py", line 1117, in __init__
    model=model)
  File "/srv/virtualenvs/smfr/lib/python3.6/site-packages/tensorflow/python/keras/engine/data_adapter.py", line 916, in __init__
    **kwargs)
  File "/srv/virtualenvs/smfr/lib/python3.6/site-packages/tensorflow/python/keras/engine/data_adapter.py", line 786, in __init__
    peek, x = self._peek_and_restore(x)
  File "/srv/virtualenvs/smfr/lib/python3.6/site-packages/tensorflow/python/keras/engine/data_adapter.py", line 920, in _peek_and_restore
    return x[0], x
  File "/srv/virtualenvs/smfr/lib/python3.6/site-packages/keras_preprocessing/image/iterator.py", line 65, in __getitem__
    return self._get_batches_of_transformed_samples(index_array)
  File "/srv/virtualenvs/smfr/lib/python3.6/site-packages/keras_preprocessing/image/iterator.py", line 230, in _get_batches_of_transformed_samples
    interpolation=self.interpolation)
  File "/srv/virtualenvs/smfr/lib/python3.6/site-packages/keras_preprocessing/image/utils.py", line 114, in load_img
    img = pil_image.open(io.BytesIO(f.read()))
  File "/srv/virtualenvs/smfr/lib/python3.6/site-packages/PIL/Image.py", line 2818, in open
    raise IOError("cannot identify image file %r" % (filename if filename else fp))
OSError: cannot identify image file <_io.BytesIO object at 0x7f80113590a0>
```

To reproduce it, just create a test.txt file with few lines then rename it as test.jpg.
It is PIL that raises the exception, but it would be great to get the wrong filename.

Thanks.

D
