### ISSUE TITLE
tf2.2-tensorrt error

### ISSUE THREAD

**Issue by niuyifeng1213** [tensorflow/tensorflow#40658]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- OS Platform and Distribution: DOCKER IMAGE:tensorflow/tensorflow:2.2.0-gpu
- GPU model and memory:Tesla K40m, 12GB

**Standalone code to reproduce the issue**
I want to use tensorrt api in tensorflow to speed up model inference.
## I simply created a model in savedmodel format with the following code
import tensorflow as tf
import numpy as np

model = tf.keras.applications.ResNet50(
    include_top=True,
    weights=None,
    input_shape=(300, 300, 3),
    classes=30
)

model.compile(optimizer='adam', loss=tf.keras.losses.categorical_crossentropy)

data = np.random.normal(size=(3, 300, 300,3)).astype(np.float32)

model.predict(data)

model.save('original_saved_model')

## I am going to use the following code for inferred acceleration
import numpy as np
import tensorflow as tf

from absl import app
from absl import flags

FLAGS = flags.FLAGS
flags.DEFINE_enum('mode', 'FP16', ['FP16', 'FP32'], 'FP16 or FP32')
flags.DEFINE_string('original_model_dir', None, 'Original saved model dir')
flags.DEFINE_string('output_dir', None, 'Output model dir')

flags.mark_flags_as_required(['mode', 'original_model_dir', 'output_dir'])

def my_input_fn():
    for _ in range(2):
        # input1 = tf.random.normal(shape=(3, 300, 300, 3))
        input1 = np.random.normal(size=(1, 3, 300, 300, 3)).astype(np.float32)
        yield input1

def main(argv):
    del argv
    params = tf.experimental.tensorrt.ConversionParams(
        precision_mode=FLAGS.mode,
        max_batch_size=10,
        maximum_cached_engines=16)
    converter = tf.experimental.tensorrt.Converter(
        input_saved_model_dir=FLAGS.original_model_dir, conversion_params=params)
    converter.convert()
    converter.build(input_fn=my_input_fn)
    converter.save(FLAGS.output_dir)

if __name__ == '__main__':
    app.run(main)

## The running log below
root@f973fbbb7e16:/niuyifeng/remote# python tensorrt_use_pre_engine.py --original_model_dir=original_saved_model/ --output_dir=use_pre_engine
/usr/local/lib/python3.6/dist-packages/absl/flags/_validators.py:359: UserWarning: Flag --mode has a non-None default value; therefore, mark_flag_as_required will pass even if flag is not specified in the command line!
  'command line!' % flag_name)
2020-06-22 08:41:09.212475: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer.so.6
INFO:tensorflow:Linked TensorRT version: (6, 0, 1)
I0622 08:41:09.212588 139998758545216 trt_convert.py:264] Linked TensorRT version: (6, 0, 1)
INFO:tensorflow:Loaded TensorRT version: (6, 0, 1)
I0622 08:41:09.212863 139998758545216 trt_convert.py:265] Loaded TensorRT version: (6, 0, 1)
2020-06-22 08:41:09.534433: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-06-22 08:41:09.541097: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:3b:00.0 name: Tesla K40m computeCapability: 3.5
coreClock: 0.745GHz coreCount: 15 deviceMemorySize: 11.17GiB deviceMemoryBandwidth: 268.58GiB/s
2020-06-22 08:41:09.541222: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-06-22 08:41:09.541262: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-06-22 08:41:09.543652: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-06-22 08:41:09.543997: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-06-22 08:41:09.546345: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-06-22 08:41:09.547615: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-06-22 08:41:09.547674: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-06-22 08:41:09.549420: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2020-06-22 08:41:09.549693: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2020-06-22 08:41:09.560237: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 2100000000 Hz
2020-06-22 08:41:09.563950: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7f5258000b20 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-06-22 08:41:09.563997: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-06-22 08:41:09.646046: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x8e78220 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-06-22 08:41:09.646096: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Tesla K40m, Compute Capability 3.5
2020-06-22 08:41:09.648938: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:3b:00.0 name: Tesla K40m computeCapability: 3.5
coreClock: 0.745GHz coreCount: 15 deviceMemorySize: 11.17GiB deviceMemoryBandwidth: 268.58GiB/s
2020-06-22 08:41:09.649015: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-06-22 08:41:09.649044: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-06-22 08:41:09.649082: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-06-22 08:41:09.649108: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-06-22 08:41:09.649134: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-06-22 08:41:09.649160: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-06-22 08:41:09.649185: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-06-22 08:41:09.653889: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2020-06-22 08:41:09.653937: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-06-22 08:41:09.946823: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-06-22 08:41:09.946877: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      0 
2020-06-22 08:41:09.946895: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 0:   N 
2020-06-22 08:41:09.953775: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10650 MB memory) -> physical GPU (device: 0, name: Tesla K40m, pci bus id: 0000:3b:00.0, compute capability: 3.5)
2020-06-22 08:41:17.862854: I tensorflow/core/grappler/devices.cc:55] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 1
2020-06-22 08:41:17.862987: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2020-06-22 08:41:17.865596: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:3b:00.0 name: Tesla K40m computeCapability: 3.5
coreClock: 0.745GHz coreCount: 15 deviceMemorySize: 11.17GiB deviceMemoryBandwidth: 268.58GiB/s
2020-06-22 08:41:17.865680: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-06-22 08:41:17.865701: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-06-22 08:41:17.865729: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-06-22 08:41:17.865760: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-06-22 08:41:17.865791: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-06-22 08:41:17.865906: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-06-22 08:41:17.865925: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-06-22 08:41:17.869346: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2020-06-22 08:41:17.869396: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-06-22 08:41:17.869412: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      0 
2020-06-22 08:41:17.869473: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 0:   N 
2020-06-22 08:41:17.874638: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10650 MB memory) -> physical GPU (device: 0, name: Tesla K40m, pci bus id: 0000:3b:00.0, compute capability: 3.5)
2020-06-22 08:41:17.938253: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:797] Optimization results for grappler item: graph_to_optimize
2020-06-22 08:41:17.938355: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:799]   function_optimizer: Graph size after: 1201 nodes (878), 1861 edges (1538), time = 32.534ms.
2020-06-22 08:41:17.938368: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:799]   function_optimizer: function_optimizer did nothing. time = 0.703ms.
2020-06-22 08:41:20.273359: I tensorflow/core/grappler/devices.cc:55] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 1
2020-06-22 08:41:20.273507: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2020-06-22 08:41:20.276428: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:3b:00.0 name: Tesla K40m computeCapability: 3.5
coreClock: 0.745GHz coreCount: 15 deviceMemorySize: 11.17GiB deviceMemoryBandwidth: 268.58GiB/s
2020-06-22 08:41:20.276638: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-06-22 08:41:20.276660: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-06-22 08:41:20.276682: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-06-22 08:41:20.276703: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-06-22 08:41:20.276848: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-06-22 08:41:20.276865: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-06-22 08:41:20.276880: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-06-22 08:41:20.281167: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2020-06-22 08:41:20.281210: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-06-22 08:41:20.281226: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      0 
2020-06-22 08:41:20.281256: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 0:   N 
2020-06-22 08:41:20.286624: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10650 MB memory) -> physical GPU (device: 0, name: Tesla K40m, pci bus id: 0000:3b:00.0, compute capability: 3.5)
2020-06-22 08:41:21.637672: I tensorflow/compiler/tf2tensorrt/segment/segment.cc:460] There are 6 ops of 3 different types in the graph that are not converted to TensorRT: Identity, NoOp, Placeholder, (For more information see https://docs.nvidia.com/deeplearning/frameworks/tf-trt-user-guide/index.html#supported-ops).
2020-06-22 08:41:21.720564: I tensorflow/compiler/tf2tensorrt/convert/convert_graph.cc:643] Number of TensorRT candidate segments: 1
2020-06-22 08:41:21.909022: I tensorflow/compiler/tf2tensorrt/convert/convert_graph.cc:745] Replaced segment 0 consisting of 505 nodes by TRTEngineOp_0.
2020-06-22 08:41:22.604272: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:797] Optimization results for grappler item: tf_graph
2020-06-22 08:41:22.604326: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:799]   constant_folding: Graph size after: 881 nodes (-320), 1221 edges (-640), time = 410.577ms.
2020-06-22 08:41:22.604400: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:799]   layout: Graph size after: 885 nodes (4), 1225 edges (4), time = 252.41ms.
2020-06-22 08:41:22.604411: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:799]   constant_folding: Graph size after: 883 nodes (-2), 1223 edges (-2), time = 124.309ms.
2020-06-22 08:41:22.604420: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:799]   TensorRTOptimizer: Graph size after: 379 nodes (-504), 380 edges (-843), time = 621.076ms.
2020-06-22 08:41:22.604445: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:799]   constant_folding: Graph size after: 325 nodes (-54), 326 edges (-54), time = 11.802ms.
2020-06-22 08:41:22.604474: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:797] Optimization results for grappler item: TRTEngineOp_0_native_segment
2020-06-22 08:41:22.604490: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:799]   constant_folding: Graph size after: 507 nodes (0), 522 edges (0), time = 75.445ms.
2020-06-22 08:41:22.604514: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:799]   layout: Graph size after: 507 nodes (0), 522 edges (0), time = 168.448ms.
2020-06-22 08:41:22.604546: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:799]   constant_folding: Graph size after: 507 nodes (0), 522 edges (0), time = 80.639ms.
2020-06-22 08:41:22.604560: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:799]   TensorRTOptimizer: Graph size after: 507 nodes (0), 522 edges (0), time = 22.492ms.
2020-06-22 08:41:22.604569: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:799]   constant_folding: Graph size after: 507 nodes (0), 522 edges (0), time = 77.95ms.
2020-06-22 08:41:25.885707: I tensorflow/compiler/tf2tensorrt/kernels/trt_engine_op.cc:982] Building a new TensorRT engine for TRTEngineOp_0 with input shapes: [[3,300,300,3]]
2020-06-22 08:41:25.885767: I tensorflow/compiler/tf2tensorrt/convert/convert_nodes.cc:1153] Linked TensorRT version: 6.0.1
2020-06-22 08:41:25.885966: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer.so.6
2020-06-22 08:41:25.885989: I tensorflow/compiler/tf2tensorrt/convert/convert_nodes.cc:1154] Loaded TensorRT version: 6.0.1
2020-06-22 08:41:25.888300: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer_plugin.so.6
2020-06-22 08:41:26.226543: W tensorflow/compiler/tf2tensorrt/utils/trt_logger.cc:38] DefaultLogger Calling isShapeTensor before the entire network is constructed may result in an inaccurate result.
2020-06-22 08:41:26.227079: W tensorflow/compiler/tf2tensorrt/utils/trt_logger.cc:38] DefaultLogger Half2 support requested on hardware without native FP16 support, performance will be negatively affected.
Traceback (most recent call last):
  File "tensorrt_use_pre_engine.py", line 48, in <module>
    app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "tensorrt_use_pre_engine.py", line 43, in main
    converter.build(input_fn=my_input_fn)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/compiler/tensorrt/trt_convert.py", line 1172, in build
    if not first_input:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.2 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/0a7b88d8611f8e19d23bde3a3e7156ce/40658.ipynb). Thanks!

**Comment by amahendrakar** [comment]
@niuyifeng1213,
Please take a look at [this similar](https://github.com/tensorflow/tensorflow/issues/32563) issue and let us know if it helps. Thanks!

**Comment by niuyifeng1213** [comment]
I changed the code to the following. It succeeded.Thank you very much

```
def my_input_fn():
    for _ in range(2):
        # input1 = tf.random.normal(shape=(3, 300, 300, 3))
        input1 = list(np.random.normal(size=(1, 3, 300, 300, 3)).astype(np.float32))
        yield input1
```
