### ISSUE TITLE
ImportError: No module named '_pywrap_tensorflow'

### ISSUE THREAD

**Issue by harshitpaliwal1011** [tensorflow/tensorflow#40668]
I installed tensorflow in VS Code on Python 3.7.7 (32-bit) using the code :
 ```pip3 install --upgrade https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.0.0-py3-none-any.whl```
It successfully got installed at first, but when i tried to run a small code to check if it works it gave me error. I have referred to the earlier mentions of this issue and i have Microsoft Visual C++ 2015 already installed. 
Here is the code i tried to run -
```#This file has been made to practice tensors/numpy/pandas
import tensorflow as tf
import numpy as np
r0t = tf.constant(4)
print(r0t)```

**Here the error i'm facing -**

```PS D:\programs\Python> python tensor.py
Traceback (most recent call last):
  File "C:\Users\Harshit Paliwal\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tensorflow', [dirname(__file__)])
  File "C:\Users\Harshit Paliwal\AppData\Local\Programs\Python\Python37-32\lib\imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tensorflow'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Harshit Paliwal\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tensorflow\python\__init__.py", line 66, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Harshit Paliwal\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "C:\Users\Harshit Paliwal\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 20, in swig_import_helper
    import _pywrap_tensorflow
ModuleNotFoundError: No module named '_pywrap_tensorflow'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tensor.py", line 2, in <module>
    import tensorflow as tf
  File "C:\Users\Harshit Paliwal\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "C:\Users\Harshit Paliwal\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tensorflow\python\__init__.py", line 72, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Harshit Paliwal\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tensorflow', [dirname(__file__)])
  File "C:\Users\Harshit Paliwal\AppData\Local\Programs\Python\Python37-32\lib\imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tensorflow'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Harshit Paliwal\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tensorflow\python\__init__.py", line 66, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Harshit Paliwal\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "C:\Users\Harshit Paliwal\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 20, in swig_import_helper
    import _pywrap_tensorflow
ModuleNotFoundError: No module named '_pywrap_tensorflow'


Failed to load the native TensorFlow runtime.

See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md#import_error

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
PS `D:\programs\Python>```
I also reffered to the GitHub link given in the last 4th line but the page is no more available.
Please provide me with a working solution to this problem.
Thanks

**Comment by ravikyram** [comment]
@harshitpaliwal1011 

Please, fill i[ssue template.](https://github.com/tensorflow/tensorflow/issues/new/choose).

Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version.

Provide the exact sequence of commands / steps that you executed before running into the problem.Thanks!

**Comment by harshitpaliwal1011** [comment]
Hey, @ravikyram 
I'm new to the platform, thanks for guiding me.

My system specifications are as follows:
* Operating System - Windows 10 Pro (x 64 bit architecture)
* Processor - Intel Core i3-2330M CPU @ 2.20GHz
* RAM - 8 GB
* Language - Python (Version 3.7.7) 32 bit architecture
* Editor Used - VS Code 
* Installed pip - Version 20.1.1
* Installed tensorflow - Version Unknown (Latest)

Here is the elaborated description of the problem i faced:
* I tried to upgrade my pip version in order to be able to install tensorflow
![image](https://user-images.githubusercontent.com/54016415/85295453-92a00280-b4bd-11ea-84d1-33bea77357a0.png)

* When i tried to install tensorflow with `pip install tensorflow` command, it didn't work out.
![image](https://user-images.githubusercontent.com/54016415/85295694-ea3e6e00-b4bd-11ea-93af-28e55d25ef2e.png)

* After trying some of the listed solutions to install tensorflow, i then switched to a virtual environment and updated pip to be able to install tensorflow
![image](https://user-images.githubusercontent.com/54016415/85296025-66d14c80-b4be-11ea-995e-0abc510be264.png)

* After all this i was finally able to install tensorflow with the help of this command
`pip3 install --upgrade https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.0.0-py3-none-any.whl`

* But now whenever i try to import tensorflow
  For example this code:
![image](https://user-images.githubusercontent.com/54016415/85296832-96348900-b4bf-11ea-9884-969bcdc104d5.png)

   It gives the above mentioned error.
![image](https://user-images.githubusercontent.com/54016415/85296632-52da1a80-b4bf-11ea-9bcf-dc6541f99c5e.png)
![image](https://user-images.githubusercontent.com/54016415/85296665-5ff70980-b4bf-11ea-9e4c-8f3a696455d8.png)

**Comment by ravikyram** [comment]
@harshitpaliwal1011 

Can you try with Windows 7 or later (64-bit) (Python 3 only)
Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019.

I don't think Tensorflow support 32 bit architecture.Please, refer the issue #32315

Please, follow the instructions from [here.](https://www.tensorflow.org/install/source_windows).Thanks!

**Comment by harshitpaliwal1011** [comment]
@ravikyram 
Thanks, I'll try installing python 64 bit and then tensorflow.

**Comment by harshitpaliwal1011** [comment]
@ravikyram 
Update, thanks for the help.
I successfully installed Python 3.7.8 (64 bit) and then installed tensorflow 
Imported tensorflow and ran a small code. It seems to be working fine now.
Here's the code snippet and the output.
* Code:
![image](https://user-images.githubusercontent.com/54016415/85425273-9a7fa580-b596-11ea-8f4c-2b2938b33ed8.png)

* Output:
![image](https://user-images.githubusercontent.com/54016415/85425349-b3885680-b596-11ea-89c3-95c3b832f70a.png)

**Comment by ravikyram** [comment]
@harshitpaliwal1011 

Please, close this thread , since your issue was resolved. Thanks!
