### ISSUE TITLE
Getting Error while tranning rasa model.(rasa train)

### ISSUE THREAD

**Issue by Akshusharma7** [tensorflow/tensorflow#40660]
Traceback (most recent call last):
  File "c:\users\akshu\anaconda3\envs\rasa\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "c:\users\akshu\anaconda3\envs\rasa\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "c:\users\akshu\anaconda3\envs\rasa\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "c:\users\akshu\anaconda3\envs\rasa\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "c:\users\akshu\anaconda3\envs\rasa\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\akshu\anaconda3\envs\rasa\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\akshu\anaconda3\envs\rasa\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\AKSHU\Anaconda3\envs\rasa\Scripts\rasa.exe\__main__.py", line 7, in <module>
  File "c:\users\akshu\anaconda3\envs\rasa\lib\site-packages\rasa\__main__.py", line 82, in main
    set_log_level(log_level)
  File "c:\users\akshu\anaconda3\envs\rasa\lib\site-packages\rasa\utils\common.py", line 71, in set_log_level
    update_tensorflow_log_level()
  File "c:\users\akshu\anaconda3\envs\rasa\lib\site-packages\rasa\utils\common.py", line 112, in update_tensorflow_log_level
    import tensorflow as tf
  File "c:\users\akshu\anaconda3\envs\rasa\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "c:\users\akshu\anaconda3\envs\rasa\lib\site-packages\tensorflow\python\__init__.py", line 50, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "c:\users\akshu\anaconda3\envs\rasa\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 69, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "c:\users\akshu\anaconda3\envs\rasa\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "c:\users\akshu\anaconda3\envs\rasa\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "c:\users\akshu\anaconda3\envs\rasa\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "c:\users\akshu\anaconda3\envs\rasa\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "c:\users\akshu\anaconda3\envs\rasa\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by Saduf2019** [comment]
@Akshusharma7

Please take a look at [this comment](https://github.com/tensorflow/tensorflow/issues/36167#issuecomment-577886156) from a similar issue and let us know if it helps. Thanks!

**Comment by Akshusharma7** [comment]
Hi @Saduf2019 yeah i have went through the comment and i have uninstalled tensorflow==2.2.0 and installed tensorflow== 2.0.0. So now i am getting below error:

rasa.core.policies.ensemble.InvalidPolicyConfig: Module for policy 'MemoizationPolicy' could not be loaded. Please make sure the name is a valid policy.
could you pls comment how to fixed it.

**Comment by Saduf2019** [comment]
@Akshusharma7 
Can you share the complete stand alone indented code such that we can replicate the issue faced or if possible share colab gist with the error for us to analyse.

a per the error can you refer to [this link](https://github.com/RasaHQ/rasa/issues/3021) and let us know if it helps resolve the issue
