### ISSUE TITLE
@Lu1352 Can you please open a new issue with a simple standalone code to reproduce the error? Thanks!

### ISSUE THREAD

**Issue by dan-weiner** [tensorflow/tensorflow#40673]
@Lu1352 Can you please open a new issue with a simple standalone code to reproduce the error? Thanks!

_Originally posted by @jvishnuvardhan in https://github.com/tensorflow/tensorflow/issues/35750#issuecomment-642966950_

Here you go:
```
#!/usr/bin/python3
import tensorflow as tf
import numpy as np
import os

(train_images, train_answers), (test_images, test_answers) = tf.keras.datasets.mnist.load_data()
train_images, test_images = train_images / 255.0, test_images / 255.0

modelfile="saved.model"
if os.path.exists(modelfile):
   model = tf.keras.models.load_model(modelfile)
else:
   model = tf.keras.models.Sequential([
     tf.keras.layers.Flatten(input_shape=(28, 28)),
     tf.keras.layers.Dense(128, activation='relu'),
     tf.keras.layers.Dropout(0.2),
     tf.keras.layers.Dense(10)
   ])
   loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
   model.compile(optimizer='adam', loss=loss_fn)
   model.fit(train_images, train_answers, epochs=1)
   model.save(modelfile)
model.summary()
```

Run it twice to reproduce the error:
```
Traceback (most recent call last):
  File "./bug.py", line 11, in <module>
    model = tf.keras.models.load_model(modelfile)
  File "/home/dbw/.local/lib/python3.7/site-packages/tensorflow/python/keras/saving/save.py", line 146, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
  File "/home/dbw/.local/lib/python3.7/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 244, in load_model_from_hdf5
    sample_weight_mode=sample_weight_mode)
  File "/home/dbw/.local/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/home/dbw/.local/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 300, in compile
    self.loss, self.output_names)
  File "/home/dbw/.local/lib/python3.7/site-packages/tensorflow/python/keras/engine/training_utils.py", line 1094, in prepare_loss_functions
    generic_utils.check_for_unexpected_keys('loss', loss, output_names)
  File "/home/dbw/.local/lib/python3.7/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 592, in check_for_unexpected_keys
    expected_values))
ValueError: Unknown entries in loss dictionary: ['class_name', 'config']. Only expected following keys: ['dense_1']
```

**Comment by dan-weiner** [comment]
Sorry.  I went back to check the tf version and found I was accidentally using 1.14.  This issue does not occur with tf 2.2.
