### ISSUE TITLE
Failed to get convolution algorithm. This is probably because cuDNN failed to initialize

### ISSUE THREAD

**Issue by Cillinc** [tensorflow/tensorflow#40750]
Tensorflow version 2.2.0
Tensorlow nightly installed
Tensorflow nighlty-gpu installed

conda list cudnn gives
version 7.6.5 build         cuda10.1_0

nvidia-smi reports 
driver version 446.14     cuda version 11.0

Nvidia 1660TI graphica card.  
Windows 10 Pro 64 bit.

the version numbers should be ok as per the Tensorflow webside https://www.tensorflow.org/install/gpu

Code to train model and use callbacks.  The error is much worse when i use verbose=1, so changed to verbose =10 as per suggestion from previous run error message.
```
log_dir = "logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M")
tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir=log_dir, 
                                                      histogram_freq=1,
                                                      write_images=True,
                                                      update_freq = 'batch')


print(datetime.datetime.now().strftime("%Y%m%d-%H:%M"))
history = model.fit(
        train_data_gen,
        batch_size = BATCH_SIZE,
        epochs=EPOCHS,
        verbose = 10,
        validation_data=val_data_gen,
        callbacks = tensorboard_callback)

print(datetime.datetime.now().strftime("%Y%m%d-%H:%M"))
```

ERROR Message
20200624-10:18
Epoch 1/25
Traceback (most recent call last):

  File "<ipython-input-9-127169b78b1e>", line 15, in <module>
    callbacks = tensorboard_callback)

  File "C:\Users\cilli\anaconda3\envs\project\lib\site-packages\tensorflow\python\keras\engine\training.py", line 66, in _method_wrapper
    return method(self, *args, **kwargs)

  File "C:\Users\cilli\anaconda3\envs\project\lib\site-packages\tensorflow\python\keras\engine\training.py", line 848, in fit
    tmp_logs = train_function(iterator)

  File "C:\Users\cilli\anaconda3\envs\project\lib\site-packages\tensorflow\python\eager\def_function.py", line 580, in __call__
    result = self._call(*args, **kwds)

  File "C:\Users\cilli\anaconda3\envs\project\lib\site-packages\tensorflow\python\eager\def_function.py", line 611, in _call
    return self._stateless_fn(*args, **kwds)  # pylint: disable=not-callable

  File "C:\Users\cilli\anaconda3\envs\project\lib\site-packages\tensorflow\python\eager\function.py", line 2420, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access

  File "C:\Users\cilli\anaconda3\envs\project\lib\site-packages\tensorflow\python\eager\function.py", line 1665, in _filtered_call
    self.captured_inputs)

  File "C:\Users\cilli\anaconda3\envs\project\lib\site-packages\tensorflow\python\eager\function.py", line 1746, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))

  File "C:\Users\cilli\anaconda3\envs\project\lib\site-packages\tensorflow\python\eager\function.py", line 598, in call
    ctx=ctx)

  File "C:\Users\cilli\anaconda3\envs\project\lib\site-packages\tensorflow\python\eager\execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)

UnknownError:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node resnet50/conv1_conv/Conv2D (defined at <ipython-input-3-0d7d4ce5ce9a>:8) ]] [Op:__inference_train_function_17457]

Function call stack:
train_function

**Comment by amahendrakar** [comment]
@Cillinc,
Please take a look at [this comment](https://github.com/tensorflow/tensorflow/issues/40646#issuecomment-647224203) from a similar issue and let us know if it works. Another possible duplicate [#24828](https://github.com/tensorflow/tensorflow/issues/24828#issuecomment-464910864)  

Thanks!

**Comment by Cillinc** [comment]
thanks - added as suggested.   Got a new error....

20200624-17:05
Epoch 1/25
WARNING:tensorflow:AutoGraph could not transform <function Model.make_train_function.<locals>.train_function at 0x0000020E10437D38> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: Bad argument number for Name: 4, expecting 3
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
WARNING: AutoGraph could not transform <function Model.make_train_function.<locals>.train_function at 0x0000020E10437D38> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: Bad argument number for Name: 4, expecting 3
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Traceback (most recent call last):

  File "<ipython-input-4-b9946ba10810>", line 8, in <module>
    callbacks = tensorboard_callback)

  File "C:\Users\cilli\anaconda3\envs\project\lib\site-packages\tensorflow\python\keras\engine\training.py", line 66, in _method_wrapper
    return method(self, *args, **kwargs)

  File "C:\Users\cilli\anaconda3\envs\project\lib\site-packages\tensorflow\python\keras\engine\training.py", line 848, in fit
    tmp_logs = train_function(iterator)

  File "C:\Users\cilli\anaconda3\envs\project\lib\site-packages\tensorflow\python\eager\def_function.py", line 580, in __call__
    result = self._call(*args, **kwds)

  File "C:\Users\cilli\anaconda3\envs\project\lib\site-packages\tensorflow\python\eager\def_function.py", line 644, in _call
    return self._stateless_fn(*args, **kwds)

  File "C:\Users\cilli\anaconda3\envs\project\lib\site-packages\tensorflow\python\eager\function.py", line 2420, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access

  File "C:\Users\cilli\anaconda3\envs\project\lib\site-packages\tensorflow\python\eager\function.py", line 1665, in _filtered_call
    self.captured_inputs)

  File "C:\Users\cilli\anaconda3\envs\project\lib\site-packages\tensorflow\python\eager\function.py", line 1746, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))

  File "C:\Users\cilli\anaconda3\envs\project\lib\site-packages\tensorflow\python\eager\function.py", line 598, in call
    ctx=ctx)

  File "C:\Users\cilli\anaconda3\envs\project\lib\site-packages\tensorflow\python\eager\execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)

InvalidArgumentError:  Incompatible shapes: [32,7,7] vs. [32,1]
	 [[node Equal (defined at <ipython-input-4-b9946ba10810>:8) ]] [Op:__inference_train_function_17457]

Function call stack:
train_function

**Comment by Cillinc** [comment]
changes the VERBOSE value in my call back as i think i had it wrong ...

print(datetime.datetime.now().strftime("%Y%m%d-%H:%M"))
history = model.fit(
        train_data_gen,
        batch_size = BATCH_SIZE,
        epochs=EPOCHS,
        verbose = 1,
        validation_data=val_data_gen,
        callbacks = tensorboard_callback)

print(datetime.datetime.now().strftime("%Y%m%d-%H:%M"))
20200624-17:08
Epoch 1/25
Traceback (most recent call last):

  File "<ipython-input-5-0d7d4ce5ce9a>", line 8, in <module>
    callbacks = tensorboard_callback)

  File "C:\Users\cilli\anaconda3\envs\project\lib\site-packages\tensorflow\python\keras\engine\training.py", line 66, in _method_wrapper
    return method(self, *args, **kwargs)

  File "C:\Users\cilli\anaconda3\envs\project\lib\site-packages\tensorflow\python\keras\engine\training.py", line 848, in fit
    tmp_logs = train_function(iterator)

  File "C:\Users\cilli\anaconda3\envs\project\lib\site-packages\tensorflow\python\eager\def_function.py", line 580, in __call__
    result = self._call(*args, **kwds)

  File "C:\Users\cilli\anaconda3\envs\project\lib\site-packages\tensorflow\python\eager\def_function.py", line 611, in _call
    return self._stateless_fn(*args, **kwds)  # pylint: disable=not-callable

  File "C:\Users\cilli\anaconda3\envs\project\lib\site-packages\tensorflow\python\eager\function.py", line 2420, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access

  File "C:\Users\cilli\anaconda3\envs\project\lib\site-packages\tensorflow\python\eager\function.py", line 1665, in _filtered_call
    self.captured_inputs)

  File "C:\Users\cilli\anaconda3\envs\project\lib\site-packages\tensorflow\python\eager\function.py", line 1746, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))

  File "C:\Users\cilli\anaconda3\envs\project\lib\site-packages\tensorflow\python\eager\function.py", line 598, in call
    ctx=ctx)

  File "C:\Users\cilli\anaconda3\envs\project\lib\site-packages\tensorflow\python\eager\execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)

InvalidArgumentError:  Incompatible shapes: [32,7,7] vs. [32,1]
	 [[node Equal (defined at <ipython-input-4-b9946ba10810>:8) ]] [Op:__inference_train_function_17457]

Function call stack:
train_function

**Comment by Cillinc** [comment]
it seems to be working after last nights updates.  However now i can't get Tensorboard to work....fix one break one....

**Comment by amahendrakar** [comment]
> it seems to be working after last nights updates. However now i can't get Tensorboard to work....fix one break one....

Could you please provide the complete code you're running along with the error log, so that we can look into it. Thanks!
