### ISSUE TITLE
Got OperatorNotAllowedInGraphError: iterating over `tf.Tensor` is not allowed in Graph execution. Use Eager execution or decorate this function with @tf.function when writing custom layer.

### ISSUE THREAD

**Issue by Brunnhild** [tensorflow/tensorflow#40768]
I wrote the following custom layer
```python
'''
Divide every 656 input vector into a group, get an output vector for each group
Input: 1) Output of sentence encoder (None, 152 * 656, 100)
       2) The concatenated user vector width dimension (100)
Output: Dimension (152, 100)
'''
class SentenceToDocument(Layer):

    def __init__(self, sentence_number, units=SENTENCE_MEM_DIM, **kwargs):
        super(SentenceToDocument, self).__init__(**kwargs)
        self.sentence_number = sentence_number
        self.units = units

    def build(self, input_shape):
        self.vw = self.add_weight(
            shape=(self.units, 1),
            initializer="random_normal",
            trainable=True
        )
        self.wh = self.add_weight(
            shape=(self.units, 100),
            initializer="random_normal",
            trainable=True
        )
        self.wu = self.add_weight(
            shape=(self.units, 100),
            initializer="random_normal",
            trainable=True
        )
        self.bw = self.add_weight(
            shape=(self.units, 1),
            initializer="random_normal",
            trainable=True
        )

    def call(self, inputs):
        res = tf.TensorArray(tf.float32, size=0, dynamic_size=True)
        for idx, v in inputs[0]:
            sentence_output = v
            user_vec = inputs[1][idx]
            section_size = inputs[0].shape[1] // self.sentence_number
            sentences = [sentence_output[i*section_size:(i+1)*section_size] for i in range(self.sentence_number)]
            res_per_sen = tf.TensorArray(tf.float32, size=0, dynamic_size=True)
            for sentence in sentences:
                e = []
                u = user_vec
                for word in sentence:
                    word = tf.reshape(word, (-1, 1))
                    u = tf.reshape(u, (-1, 1))
                    wh = tf.matmul(self.wh, word)
                    wu = tf.matmul(self.wu, u)
                    tan = tf.tanh(wh + wu + self.bw)
                    e.append(tf.matmul(tf.transpose(self.vw), tan))
                sum_e = sum([tf.exp(i) for i in e])
                alpha = [tf.exp(i) / sum_e for i in e]
                s = tf.TensorArray(tf.float32, size=0, dynamic_size=True)
                for i in sentence.shape[0]:
                    s.write(s.size(), alpha[i] * sentence[i])
                res_per_sen.write(res_per_sen.size(), s.stack())
            res.write(res.size(), res_per_sen)
        return res.stack()
```

I was using this layer in the middle of my model, it accepts two inputs, as described in the comment. For each data within the batch, it is supposed to first divide the data into several groups, then do some operations together with u with is another input, and the number of u is the same to the number of he groups. I thought it will output tensor with dimension (None, 152, 100), but I got the error below. I'm using tf-nightly and python 3.7.7 and Anaconda.

```
Traceback (most recent call last):
  File "C:\Users\*****\Anaconda3\envs\night\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 1107, in _functional_construction_call
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "C:\Users\*****\Anaconda3\envs\night\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 258, in wrapper
    raise e.ag_error_metadata.to_exception(e)
tensorflow.python.framework.errors_impl.OperatorNotAllowedInGraphError: in user code:

    main.py:132 call  *
        for idx, v in inputs[0]:
    C:\Users\*****\Anaconda3\envs\night\lib\site-packages\tensorflow\python\framework\ops.py:503 __iter__
        self._disallow_iteration()
    C:\Users\*****\Anaconda3\envs\night\lib\site-packages\tensorflow\python\framework\ops.py:499 _disallow_iteration
        self._disallow_in_graph_mode("iterating over `tf.Tensor`")
    C:\Users\*****\Anaconda3\envs\night\lib\site-packages\tensorflow\python\framework\ops.py:479 _disallow_in_graph_mode
        " this function with @tf.function.".format(task))

    OperatorNotAllowedInGraphError: iterating over `tf.Tensor` is not allowed in Graph execution. Use Eager execution or decorate this function with @tf.function.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 286, in <module>
    user_sentence_output = SentenceToDocument(max_sentence)([c1, con_user_vec])
  File "C:\Users\*****\Anaconda3\envs\night\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 926, in __call__
    input_list)
  File "C:\Users\*****\Anaconda3\envs\night\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 1114, in _functional_construction_call
    '\n"""')
TypeError: You are attempting to use Python control flow in a layer that was not declared to be dynamic. Pass `dynamic=True` to the class constructor.
Encountered error:
"""
in user code:

    main.py:132 call  *
        for idx, v in inputs[0]:
    C:\Users\*****\Anaconda3\envs\night\lib\site-packages\tensorflow\python\framework\ops.py:503 __iter__
        self._disallow_iteration()
    C:\Users\*****\Anaconda3\envs\night\lib\site-packages\tensorflow\python\framework\ops.py:499 _disallow_iteration
        self._disallow_in_graph_mode("iterating over `tf.Tensor`")
    C:\Users\*****\Anaconda3\envs\night\lib\site-packages\tensorflow\python\framework\ops.py:479 _disallow_in_graph_mode
        " this function with @tf.function.".format(task))

    OperatorNotAllowedInGraphError: iterating over `tf.Tensor` is not allowed in Graph execution. Use Eager execution or decorate this function with @tf.function.

"""
```

**Comment by amahendrakar** [comment]
@Brunnhild,
On running the code I am facing an error stating `NameError: name 'Layer' is not defined`. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/0aed57fe70b05aa31971d41467c283b7/40768.ipynb).

In order to reproduce the error, could you please share the complete code and the supporting files you are using. Thanks!

**Comment by Brunnhild** [comment]
I found that error was due to the iteration on input tensor, I tried to iterate the input tensor by index, that caused the error. I changed the code to below
```python
from data import get_train_input, get_vocabulary
from tensorflow.keras.models import Model
from tensorflow.keras.layers import *
from tensorflow.keras.utils import to_categorical
from tensorflow import keras
from collections import Counter
import numpy as np
import os
import pickle
import tensorflow as tf


class SentenceToDocument(Layer):

    def __init__(self, sentence_number, units=SENTENCE_MEM_DIM, **kwargs):
        super(SentenceToDocument, self).__init__(**kwargs)
        self.sentence_number = sentence_number
        self.units = units

    def build(self, input_shape):
        self.vw = self.add_weight(
            shape=(self.units, 1),
            initializer="random_normal",
            trainable=True
        )
        self.wh = self.add_weight(
            shape=(self.units, 2 * MIDDLE_OUTPUT),
            initializer="random_normal",
            trainable=True
        )
        self.wu = self.add_weight(
            shape=(self.units, 2 * USER_VEC_DIM),
            initializer="random_normal",
            trainable=True
        )
        self.bw = self.add_weight(
            shape=(self.units, 1),
            initializer="random_normal",
            trainable=True
        )

    def call(self, inputs):
        res = tf.TensorArray(tf.float32, size=0, dynamic_size=True)
        for con_input in inputs:
            sentence_output = con_input[:-1] 
            section_size = sentence_output.shape[0] // self.sentence_number
            user_vec = con_input[-1] # shape: (USER_VEC_DIM,)
            wpu = tf.matmul(self.wu, tf.reshape(user_vec, (-1, 1)))
            wub = tf.transpose(wpu + self.bw) # shape: (1, self.units)
            wub = tf.tile(wub, (section_size, 1)) # shape: (section_size, units)
            section_s = tf.TensorArray(tf.float32, size=self.sentence_number, dynamic_size=True)
            for i in range(self.sentence_number):
                h = sentence_output[i*section_size:(i+1)*section_size] # shape: (section_size, 2 * MIDDLE_OUTPUT)
                wph = tf.matmul(h, tf.transpose(self.wh)) # shape: (section_size, units)
                tanh = tf.tanh(wph + wub)
                e = tf.matmul(tanh, self.vw) # shape: (section_size, 1)
                alpha = tf.exp(e) / tf.reduce_sum(tf.exp(e)) # shape: (section_size, 1)
                s = tf.tile(alpha, (1, h.shape[1])) * h # shape: (section_size, 2 * MIDDLE_OUTPUT)
                s = tf.reduce_sum(s, axis=0) #shape: (2 * MIDDLE_OUTPUT,)
                section_s = section_s.write(i, s)
            section_s = section_s.stack() # shape: (self.sentence_number, 2 * MIDDLE_OUTPUT)
            res = res.write(res.size(), section_s)
        return res.stack()

    def compute_output_shape(self, input_shape):
        return (None, self.sentence_number, 2 * MIDDLE_OUTPUT)
```
And it works. Thanks for concerning.
