### ISSUE TITLE
ImportError: cannot import name device_spec

### ISSUE THREAD

**Issue by marynaggita** [tensorflow/tensorflow#40857]
Traceback (most recent call last):
  File "object_detection/builders/model_builder_tf1_test.py", line 21, in <module>
    from object_detection.builders import model_builder
  File "/home/magdalena/models/research/object_detection/builders/model_builder.py", line 19, in <module>
    from object_detection.builders import anchor_generator_builder
  File "/home/magdalena/models/research/object_detection/builders/anchor_generator_builder.py", line 23, in <module>
    from object_detection.anchor_generators import flexible_grid_anchor_generator
  File "/home/magdalena/models/research/object_detection/anchor_generators/flexible_grid_anchor_generator.py", line 19, in <module>
    from object_detection.anchor_generators import grid_anchor_generator
  File "/home/magdalena/models/research/object_detection/anchor_generators/grid_anchor_generator.py", line 27, in <module>
    from object_detection.utils import ops
  File "/home/magdalena/models/research/object_detection/utils/ops.py", line 28, in <module>
    import tf_slim as slim
  File "/home/magdalena/.local/lib/python2.7/site-packages/tf_slim/__init__.py", line 25, in <module>
    from tf_slim.layers import *
  File "/home/magdalena/.local/lib/python2.7/site-packages/tf_slim/layers/__init__.py", line 25, in <module>
    from tf_slim.layers.layers import *
  File "/home/magdalena/.local/lib/python2.7/site-packages/tf_slim/layers/layers.py", line 30, in <module>
    from tf_slim.ops import variables
  File "/home/magdalena/.local/lib/python2.7/site-packages/tf_slim/ops/variables.py", line 27, in <module>
    from tensorflow.python.framework import device_spec as tf_device
ImportError: cannot import name device_spec

Python = 2.7
Tensorflow = 1.13.1
Ubuntu 18.04.4

What could be the problem and how can i solve this issue?

**Comment by Saduf2019** [comment]
@marynaggita 

Is there any particular reason for using older version of tf when there are later versions, can you upgrade to later versions to see if it helps resolve the issue.
Also refer to similar [issue here](https://github.com/tensorflow/tensorflow/issues/40182#issuecomment-641810207).

**Comment by ymodak** [comment]
@marynaggita I believe you are trying to execute [TensorFlow Object Detection API](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md)
It's installation guide states that you require TF 1.15 Version as a prerequisite.
Following import is successful in TF 1.15
```python
from tensorflow.python.framework import device_spec as tf_device
```
Please upgrade your TF version to 1.15
Thanks!

**Comment by marynaggita** [comment]
Thank you. It worked out after upgrading
