### ISSUE TITLE
tf.GradientTape.batch_jacobian fails on compiled tf.function due to assert op

### ISSUE THREAD

**Issue by aroig** [tensorflow/tensorflow#40885]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: no
- TensorFlow installed from (source or binary): pip tf-nightly
- TensorFlow version (use command below): v1.12.1-35353-gcbb94efa58 2.5.0-dev20200628
- Python version: 3.7.6
- Bazel version (if compiling from source): -
- GCC/Compiler version (if compiling from source): -
- CUDA/cuDNN version: 10.1
- GPU model and memory: GeForce GTX 1050 Ti with Max-Q Design 4 Gb

**Describe the current behavior**

tf.GradientTape.batch_jacobian fails to run on compiled tf.function due to an unsupported graph assert.

**Describe the expected behavior**
I would expect batch_jacobian to work the same in compiled or uncompiled tf.function

**Standalone code to reproduce the issue**

```python
import tensorflow as tf

@tf.function(experimental_compile=True)
def func(x):
    with tf.GradientTape() as tape:
        tape.watch(x)
        y = tf.square(x)

    jac = tape.batch_jacobian(y, x)

    return jac

x = tf.zeros(shape=(2, 2), dtype=tf.float32)
jac = func(x)
```
fails with this error
```
Traceback (most recent call last):
  File "bugreport.py", line 14, in <module>
    jac = func(x)
  File "/home/abdo/tmp/venv/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 775, in __call__
    result = self._call(*args, **kwds)
  File "/home/abdo/tmp/venv/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 846, in _call
    return self._concrete_stateful_fn._filtered_call(canon_args, canon_kwds)  # pylint: disable=protected-access
  File "/home/abdo/tmp/venv/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 1847, in _filtered_call
    cancellation_manager=cancellation_manager)
  File "/home/abdo/tmp/venv/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 1923, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/home/abdo/tmp/venv/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 550, in call
    ctx=ctx)
  File "/home/abdo/tmp/venv/lib/python3.6/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Function invoked by the following node is not compilable: {{node __inference_func_203}} = __inference_func_203[_XlaMustCompile=true, config_proto="\n\007\n\003CPU\020\001\n\007\n\003GPU\020\0012\005*\0010J\0008\001\202\001\000", executor_type=""](dummy_input).
Uncompilable nodes:
assert_equal_1/Assert/Const: unsupported op: Const op with type DT_STRING is not supported by XLA.
	Stacktrace:
		Node: __inference_func_203, function: 
		Node: assert_equal_1/Assert/Const, function: __inference_func_203

assert_equal_1/Assert/Const_1: unsupported op: Const op with type DT_STRING is not supported by XLA.
	Stacktrace:
		Node: __inference_func_203, function: 
		Node: assert_equal_1/Assert/Const_1, function: __inference_func_203

assert_equal_1/Assert/Const_2: unsupported op: Const op with type DT_STRING is not supported by XLA.
	Stacktrace:
		Node: __inference_func_203, function: 
		Node: assert_equal_1/Assert/Const_2, function: __inference_func_203

assert_equal_1/Assert/Assert/data_0: unsupported op: Const op with type DT_STRING is not supported by XLA.
	Stacktrace:
		Node: __inference_func_203, function: 
		Node: assert_equal_1/Assert/Assert/data_0, function: __inference_func_203

assert_equal_1/Assert/Assert/data_1: unsupported op: Const op with type DT_STRING is not supported by XLA.
	Stacktrace:
		Node: __inference_func_203, function: 
		Node: assert_equal_1/Assert/Assert/data_1, function: __inference_func_203

assert_equal_1/Assert/Assert/data_3: unsupported op: Const op with type DT_STRING is not supported by XLA.
	Stacktrace:
		Node: __inference_func_203, function: 
		Node: assert_equal_1/Assert/Assert/data_3, function: __inference_func_203
 [Op:__inference_func_203]

```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

The problem vanishes if I remove the assert_equal on line 1276 in `tensorflow/python/eager/backprop.py`

```python
    ...
    with ops.control_dependencies(
        [check_ops.assert_equal(batch_size, source_shape[0])]):
      target = array_ops.reshape(target, [batch_size, target_row_size])
    ...

```
I'd be happy to submit a PR, however I am not sure how to replace the assert with a compile-friendly version.

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.2 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/956165732b72253d3af339c97f58fad1/40885.ipynb). Thanks!
