### ISSUE TITLE
Cannot save Model with Custom Layer : tensorflow.python.framework.errors_impl.InvalidArgumentError: 'func' argument to TF_GraphCopyFunction cannot be null

### ISSUE THREAD

**Issue by mNemlaghi** [tensorflow/tensorflow#40909]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ubuntu
- TensorFlow installed from: pip
- TensorFlow version: 
Git version : v2.2.0-rc4-8-g2b96f3662b 
Tensorflow version: 2.2.0
- Python version: 3.7

**Describe the current behavior**
For an NLP project, in order to directly preprocess data in a model , I have implemented a custom tokenization layer with a StaticHashTable (see below). Afterwards, I prepend this layer to a base model. Everything seems working fine, I even can make computations with the model.

**Describe the expected behavior**

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

```python
import pickle
import tensorflow as tf

tokenizer = pickle.load(tokenizer_path) ##pickled tf.keras tokenizer

class OwnPadder(tf.keras.layers.Layer):
    def __init__(self, **kwargs):
        super(OwnPadder, self).__init__(name = "padder", trainable = False, **kwargs)
        self.tokenizer_keys = tf.constant(list(tokenizer.word_index.keys()), dtype = tf.string)
        self.tokenizer_values = tf.constant(list(tokenizer.word_index.values()), dtype = tf.int32)
        self.initializer = tf.lookup.KeyValueTensorInitializer(keys = self.tokenizer_keys,
                 values= self.tokenizer_values, key_dtype = tf.string, value_dtype = tf.int32)
        self.table = tf.lookup.StaticHashTable(self.initializer, default_value=tf.constant(-1), name = "static_hash")

    def call(self, inputs, **kwargs):
        pipe = tf.strings.split(inputs)
        pipe = pipe.to_tensor(shape = pipe.bounding_shape(), name = "uniform_tensor")[:,0,:]
        tokenized = self.table.lookup(pipe, name = "tokenize")
        masked = tf.ragged.boolean_mask(tokenized, tokenized>0)
        res = masked.to_tensor(shape = [None, 100], name ="oad")
        return res

    def get_config(self):
        config = super(OwnPadder, self).get_config()
        return config

[...]

base_model = tf.keras.models.load_model(base_model_path)
base_model.trainable = False
input_text = tf.keras.layers.Input(shape=(1,), dtype=tf.string, name = "input")
 x = OwnPadder()(input_text)
 for layers in base_model.layers:
     x = layers(x)

holistic_model = tf.keras.models.Model(inputs = input_text, outputs = x)
holistic_model.compile()
final_model_path
holistic_model.save(final_model_path, save_format = "tf")

```
So, no bug here, everything seems fine until I try to serve with TensorflowServing, where the serving made a segmentation fault...
I tried to make a diagnostic with `saved_model_cli` shell command with the newly saved model, which gave me expected inputs/outputs signatures, but ended with a weird TF Error.

```python
WARNING:tensorflow:From $conda_envlib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py:1817: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
2020-06-29 06:24:26.528835: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2020-06-29 06:24:26.528907: E tensorflow/stream_executor/cuda/cuda_driver.cc:313] failed call to cuInit: UNKNOWN ERROR (303)
2020-06-29 06:24:26.528947: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (nlp-compute-2.sesamm.com): /proc/driver/nvidia/version does not exist
2020-06-29 06:24:26.529160: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-06-29 06:24:26.566924: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 2397160000 Hz
2020-06-29 06:24:26.574709: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7f85f0000b20 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-06-29 06:24:26.574758: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Exception ignored in: <function CapturableResourceDeleter.__del__ at 0x7f86ba4de8c8>
Traceback (most recent call last):
  File "$conda_env/python3.7/site-packages/tensorflow/python/training/tracking/tracking.py", line 191, in __del__
    self._destroy_resource()
  File "$conda_env/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 580, in __call__
    result = self._call(*args, **kwds)
  File "$conda_env/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 627, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "$conda_env/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 506, in _initialize
    *args, **kwds))
  File "$conda_env/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2446, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "$conda_env/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2777, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "$conda_env/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2667, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "$conda_env/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 981, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "$conda_env/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 441, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "$conda_env/lib/python3.7/site-packages/tensorflow/python/saved_model/function_deserialization.py", line 241, in restored_function_body
    return _call_concrete_function(function, inputs)
  File "$conda_envlib/python3.7/site-packages/tensorflow/python/saved_model/function_deserialization.py", line 72, in _call_concrete_function
    result = function._call_flat(tensor_inputs, function._captured_inputs)  # pylint: disable=protected-access
  File "$conda_env/lib/python3.7/site-packages/tensorflow/python/saved_model/load.py", line 101, in _call_flat
    cancellation_manager)
  File "$conda_env/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1760, in _call_flat
    flat_outputs = forward_function.call(ctx, args_with_tangents)
  File "$conda_envlib/python3.7/site-packages/tensorflow/python/eager/function.py", line 627, in call
    executor_type=executor_type)
  File "$conda_envlib/python3.7/site-packages/tensorflow/python/ops/functional_ops.py", line 1165, in partitioned_call
    f.add_to_graph(graph)
  File "$conda_envlib/python3.7/site-packages/tensorflow/python/eager/function.py", line 543, in add_to_graph
    g._add_function(self)
  File "$conda_env/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3187, in _add_function
    gradient)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 'func' argument to TF_GraphCopyFunction cannot be null
```
Please notice that the base model (without preprocessing layer) doesn't give this issue, and can be perfectly served via TensorflowServing. So I assume this is a matter of serialization of the new layer. Moreover, I tried to fit the new model from scratch (by fitting with raw data, compiling and saving preprocessed), and it also gave me an error. 

Do you have any hint how to fix this ? What am I doing wrong here ? Many thanks in advance !

**Comment by amahendrakar** [comment]
@mNemlaghi,
Issues related to TensorFlow Serving are handled in the Serving repo. 

Could you please submit a new issue from [this link](https://github.com/tensorflow/serving/issues/new) and fill in the template so that we can track the issue there. Thanks!
