### ISSUE TITLE
`tf.Tensor` as a Python `bool` is not allowed in Graph execution. Use Eager execution or decorate this function with @tf.function

### ISSUE THREAD

**Issue by Tyson-Stur** [tensorflow/tensorflow#40916]
Hi, I am a beginner. Could anyone explain me this error please?

- Error is:

    OperatorNotAllowedInGraphError Traceback (most recent call last) in 1 data = scaled_close 2 ----> 3 lstm = RNN_LSTM(input_dim = 28, seq_size = 28) 4 lstm.train(data) 5 lstm.test(data)
    
    in init(self, input_dim, seq_size, hidden_dim, learning_rate, batch_size, epochs, keep_prob) 42 # Loss function and optimizer 43 ---> 44 self.cost = tf.nn.l2_loss(self.output, self.Y) 45 self.optimizer = tf.train.AdamOptimizer(self.learning_rate).minimize(self.cost) 46
    
     in l2_loss(t, name) 4737 try: 4738 _, _, _op, _outputs = _op_def_library._apply_op_helper( -> 4739 "L2Loss", t=t, name=name) 4740 except (TypeError, ValueError): 4741 result = _dispatch.dispatch(
    
     in _apply_op_helper(op_type_name, name, **keywords) 351 inputs = [] 352 input_types = [] --> 353 with g.as_default(), ops.name_scope(name) as scope: 354 355 # Perform input type inference
    
     in enter(self) 6294 try: 6295 self._name_scope = g.name_scope(self._name) -> 6296 return self._name_scope.enter() 6297 except: 6298 if self._g_manager is not None:
    
     in enter(self) 110 del self.args, self.kwds, self.func 111 try: --> 112 return next(self.gen) 113 except StopIteration: 114 raise RuntimeError("generator didn't yield") from None
    
     in name_scope(self, name) 4016 above. 4017 """ -> 4018 if name: 4019 if isinstance(name, compat.bytes_or_text_types): 4020 name = compat.as_str(name)
    
     in bool(self) 776  TypeError. 777 """ --> 778 self._disallow_bool_casting() 779 780 def nonzero(self):
    
     in _disallow_bool_casting(self) 546 else: 547 # Default: V1-style Graph execution. --> 548 self._disallow_in_graph_mode("using a tf.Tensor as a Python bool") 549 550 def _disallow_iteration(self):
    
     in _disallow_in_graph_mode(self, task) 535 raise errors.OperatorNotAllowedInGraphError( 536 "{} is not allowed in Graph execution. Use Eager execution or decorate" --> 537 " this function with @tf.function.".format(task)) 538 539 def _disallow_bool_casting(self):
    
    OperatorNotAllowedInGraphError: using a tf.Tensor as a Python bool is not allowed in Graph execution. Use Eager execution or decorate this function with @tf.function.

- The code is:

class RNN_LSTM:
    
    def __init__(self, input_dim, seq_size, hidden_dim = 128, learning_rate = 0.01, batch_size = 128, epochs = 1, keep_prob = 1.0):
    
        # Hyperparameters
        
        self.input_dim = input_dim
        self.seq_size = seq_size
        self.hidden_dim = hidden_dim
        self.learning_rate = learning_rate
        self.batch_size = batch_size
        self.epochs = epochs
        self.keep_prob = keep_prob
    
        # Input and target placeholders ###
        
        X = tf.placeholder("float", [None, self.seq_size, self.input_dim])
        Y = tf.placeholder("float", [None, 1])
    
        # Weights & biases ###
        
        weights = tf.Variable(tf.random_normal([self.hidden_dim, 1]), name='weights')
        biases =  tf.Variable(tf.random_normal([1]), name='b')
                
        self.X = X
        self.Y = Y
        self.weights = weights
        self.biases = biases
        self.output = self.lstm()                
    
        # Loss function and optimizer
        
        self.cost = tf.nn.l2_loss(self.output, self.Y)
        self.optimizer = tf.train.AdamOptimizer(self.learning_rate).minimize(self.cost)
    
        self.accuracy = 1. - (tf.reduce_mean(tf.abs((self.output - self.Y)/self.Y )))
         
        # Needed to save the session
        
        self.saver = tf.train.Saver()
    
    def lstm(self):
        '''
        Prepare the input shape for the lstm. Actual shape is (batch_size, seq_size, input_dim),
        the required shape is 'seq_size' tensors list of shape (batch_size, n_input)
        
        '''
        
        X = self.X
        # Permuting batch_size and seq_size
        X = tf.transpose(X, [1, 0, 2])
        
        # Reshaping to (seq_size*batch_size, input_dim)
        X = tf.reshape(X, [-1, self.input_dim])
        
        # Split to get a list of 'seq_size' tensors of shape (batch_size, input_dim)
        X = tf.split(X, self.seq_size, 0)
                
        # Create lstm and add the dropout
        
        lstm_cell = rnn_cell.LSTMCell(self.hidden_dim, use_peepholes=True)
        lstm_cell = rnn_cell.DropoutWrapper(lstm_cell, input_keep_prob=self.keep_prob, output_keep_prob=self.keep_prob)
        outputs, states = rnn.static_rnn(lstm_cell, X, dtype=tf.float32)
        
        output = tf.matmul(outputs[-1], self.weights) + self.biases
        
        return output
    
    
    def train(self, data, target):
    
        with tf.Session() as sess:
            sess.run(tf.initialize_all_variables())
    
            for epoch in range(self.epochs):
                epoch_loss = 0
                i = 0
    
                Y = tf.placeholder("float", [None, 1])
    
                while i < int(len(data)/self.batch_size):
    
                    start = i * self.batch_size
                    end = (i+1) * self.batch_size
    
                    batch_x = np.array(data[start:end])
                    batch_y = np.array(target[start:end])
                    #print(i, batch_y.shape)
                    batch_x = np.reshape(batch_x, (self.batch_size, self.seq_size, self.input_dim))
                    batch_y = np.reshape(batch_y, (self.batch_size, 1))
    
                    #print(batch_x, '\n \n \n', batch_y)
    
                    _, c = sess.run([self.optimizer, self.cost], feed_dict={self.X: batch_x, self.Y: batch_y})
                    epoch_loss += c
                    i += 1
    
                if (epoch+1) % 100 == 0:
                    print('Epoch', epoch + 1, 'completed out of', self.epochs, ', train loss:', epoch_loss)
    
            save_path = self.saver.save(sess, './LSTM.ckpt')
            print('Accuracy', self.accuracy.eval({self.X: data.reshape((-1, self.seq_size, self.input_dim)),
                                                  self.Y: target.reshape(-1, 1)}))
    
    def test(self, data, target):
    
        with tf.Session() as sess:
            self.saver.restore(sess, './LSTM.ckpt')
            prediction = sess.run(self.output, feed_dict={self.X: data.reshape((-1, self.seq_size, self.input_dim))})
            target.reshape((-1, 1))
    
            for i in range(10):
    
                print('prediction: ', prediction[i], 'target: ', target[i])
    
            print('Accuracy', self.accuracy.eval({self.X: data.reshape((-1, self.seq_size, self.input_dim)),
                                                  self.Y: target.reshape(-1, 1)}))
            plt.plot(prediction, linewidth=0.3, color='r', label='Predicted values')
            plt.plot(target, linewidth=0.3, color='g', label='Target values')
            plt.legend()
            plt.show()
    
Thank you!

**Comment by Saduf2019** [comment]
@Tyson-Stur 
Can you please the tensorflow version on which this error is faced and refer to below issues with similar error:
#35403 #40768 

Also i ran the above code in 2,2 and do not face any error, please find the [gist here](https://colab.research.google.com/drive/1OQcNWScFS_ZyVE14AMDUl2kv6Cx2ZLY1#scrollTo=rcO9n-gP03ZT).

**Comment by Tyson-Stur** [comment]
@Saduf2019 
Thank you for your response. I am trying to access the gist but I get the error 'couldn't send request'

**Comment by Tyson-Stur** [comment]
@Saduf2019  I am using tensorflow 2.2.

I still get the error when I call it:

lstm = RNN_LSTM(input_dim, seq_size)
lstm.train(data)
lstm.test(data)

**Comment by Tyson-Stur** [comment]
@Saduf2019  
I have also tried with !pip install tensorflow-gpu==2.1-rc2 as proposed in #35403 but did not solve the problem :(

**Comment by Tyson-Stur** [comment]
@Saduf2019  I have sent the request to access the gist. Thank you

**Comment by Saduf2019** [comment]
@Tyson-Stur 
I ran the code on nightly as well, please check [this gist](https://colab.research.google.com/gist/Saduf2019/e6d3ea596b02652217730030fc862aae/untitled246.ipynb)

**Comment by Tyson-Stur** [comment]
@Saduf2019 

Could you please check the full code --> https://colab.research.google.com/drive/1NE0YBTkU_43hzeQKRwzlAOwq4S9eE7S-?usp=sharing

Perhaps I am not correctly implementing the dataset/feeding the data into the model? 

Because it worked when I used the MINST data (data = input_data.read_data_sets("mnist_data/", one_hot=true).
But now that I am using different data, I can not make it work. 

Thank you for your help. Very appreciated.

**Comment by mtdot** [comment]
Hello, same issue with the code bellow:
```
import tensorflow as tf
from tensorflow.keras import datasets, layers, models

import os

os.chdir(r"F:\My\ML\eat_tensorflow2_in_30_days-master\eat")

BATCH_SIZE = 100


def load_image(img_path, size=(32, 32)):
    label = tf.constant(1, tf.int8) if tf.strings.regex_full_match(img_path, ".*automobile.*") \
        else tf.constant(0, tf.int8)
    img = tf.io.read_file(img_path)
    img = tf.image.decode_jpeg(img)  # In jpeg format
    img = tf.image.resize(img, size) / 255.0
    return img, label


# Parallel pre-processing using num_parallel_calls and caching data with prefetch function to improve the performance
ds_train = tf.data.Dataset.list_files("../data/cifar2/train/*/*.jpg") \
    .map(load_image, num_parallel_calls=tf.data.experimental.AUTOTUNE) \
    .shuffle(buffer_size=1000).batch(BATCH_SIZE) \
    .prefetch(tf.data.experimental.AUTOTUNE)

ds_test = tf.data.Dataset.list_files("../data/cifar2/test/*/*.jpg") \
    .map(load_image) \
    .batch(BATCH_SIZE) \
    .prefetch(tf.data.experimental.AUTOTUNE)
```

And output log here:
```
2020-07-09 13:42:00.646011: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
2020-07-09 13:42:04.452970: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2020-07-09 13:42:04.911156: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce 920MX computeCapability: 5.0
coreClock: 0.993GHz coreCount: 2 deviceMemorySize: 2.00GiB deviceMemoryBandwidth: 14.92GiB/s
2020-07-09 13:42:04.912080: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
2020-07-09 13:42:04.921193: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_10.dll
2020-07-09 13:42:04.927787: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_10.dll
2020-07-09 13:42:04.930632: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_10.dll
2020-07-09 13:42:04.939863: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_10.dll
2020-07-09 13:42:04.944908: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_10.dll
2020-07-09 13:42:04.961323: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-07-09 13:42:04.963108: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2020-07-09 13:42:04.964143: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2020-07-09 13:42:04.974839: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x1ce4df00990 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-07-09 13:42:04.975634: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-07-09 13:42:04.976878: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce 920MX computeCapability: 5.0
coreClock: 0.993GHz coreCount: 2 deviceMemorySize: 2.00GiB deviceMemoryBandwidth: 14.92GiB/s
2020-07-09 13:42:04.977701: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
2020-07-09 13:42:04.978163: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_10.dll
2020-07-09 13:42:04.978584: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_10.dll
2020-07-09 13:42:04.978958: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_10.dll
2020-07-09 13:42:04.979366: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_10.dll
2020-07-09 13:42:04.979763: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_10.dll
2020-07-09 13:42:04.980200: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-07-09 13:42:04.981715: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2020-07-09 13:42:07.499422: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-07-09 13:42:07.499914: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      0 
2020-07-09 13:42:07.500107: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 0:   N 
2020-07-09 13:42:07.501540: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 1378 MB memory) -> physical GPU (device: 0, name: GeForce 920MX, pci bus id: 0000:01:00.0, compute capability: 5.0)
2020-07-09 13:42:07.506681: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x1ce7218d330 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-07-09 13:42:07.507455: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce 920MX, Compute Capability 5.0
WARNING:tensorflow:AutoGraph could not transform <function load_image at 0x000001CE42F78DC8> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: Unable to locate the source code of <function load_image at 0x000001CE42F78DC8>. Note that functions defined in certain environments, like the interactive Python shell do not expose their source code. If that is the case, you should to define them in a .py source file. If you are certain the code is graph-compatible, wrap the call using @tf.autograph.do_not_convert. Original error: could not get source code
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Traceback (most recent call last):
  File "C:\SCS\Python\venvs\eat_tensorflow2_in_30_days-master\lib\site-packages\tensorflow\python\autograph\pyct\parser.py", line 196, in parse_entity
    original_source = inspect_utils.getimmediatesource(entity)
  File "C:\SCS\Python\venvs\eat_tensorflow2_in_30_days-master\lib\site-packages\tensorflow\python\autograph\pyct\inspect_utils.py", line 147, in getimmediatesource
    lines, lnum = inspect.findsource(obj)
  File "C:\SCS\anaconda3\lib\inspect.py", line 786, in findsource
    raise OSError('could not get source code')
OSError: could not get source code
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\SCS\Python\venvs\eat_tensorflow2_in_30_days-master\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 538, in converted_call
    converted_f = conversion.convert(target_entity, program_ctx)
  File "C:\SCS\Python\venvs\eat_tensorflow2_in_30_days-master\lib\site-packages\tensorflow\python\autograph\impl\conversion.py", line 360, in convert
    free_nonglobal_var_names)
  File "C:\SCS\Python\venvs\eat_tensorflow2_in_30_days-master\lib\site-packages\tensorflow\python\autograph\impl\conversion.py", line 275, in _convert_with_cache
    entity, program_ctx)
  File "C:\SCS\Python\venvs\eat_tensorflow2_in_30_days-master\lib\site-packages\tensorflow\python\autograph\impl\conversion.py", line 511, in convert_entity_to_ast
    nodes, name, entity_info = convert_func_to_ast(o, program_ctx)
  File "C:\SCS\Python\venvs\eat_tensorflow2_in_30_days-master\lib\site-packages\tensorflow\python\autograph\impl\conversion.py", line 673, in convert_func_to_ast
    node, source = parser.parse_entity(f, future_features=future_features)
  File "C:\SCS\Python\venvs\eat_tensorflow2_in_30_days-master\lib\site-packages\tensorflow\python\autograph\pyct\parser.py", line 204, in parse_entity
    ' @tf.autograph.do_not_convert. Original error: {}'.format(entity, e))
ValueError: Unable to locate the source code of <function load_image at 0x000001CE42F78DC8>. Note that functions defined in certain environments, like the interactive Python shell do not expose their source code. If that is the case, you should to define them in a .py source file. If you are certain the code is graph-compatible, wrap the call using @tf.autograph.do_not_convert. Original error: could not get source code
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<input>", line 22, in <module>
  File "C:\SCS\Python\venvs\eat_tensorflow2_in_30_days-master\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 1628, in map
    preserve_cardinality=True)
  File "C:\SCS\Python\venvs\eat_tensorflow2_in_30_days-master\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 4020, in __init__
    use_legacy_function=use_legacy_function)
  File "C:\SCS\Python\venvs\eat_tensorflow2_in_30_days-master\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 3221, in __init__
    self._function = wrapper_fn.get_concrete_function()
  File "C:\SCS\Python\venvs\eat_tensorflow2_in_30_days-master\lib\site-packages\tensorflow\python\eager\function.py", line 2532, in get_concrete_function
    *args, **kwargs)
  File "C:\SCS\Python\venvs\eat_tensorflow2_in_30_days-master\lib\site-packages\tensorflow\python\eager\function.py", line 2496, in _get_concrete_function_garbage_collected
    graph_function, args, kwargs = self._maybe_define_function(args, kwargs)
  File "C:\SCS\Python\venvs\eat_tensorflow2_in_30_days-master\lib\site-packages\tensorflow\python\eager\function.py", line 2777, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "C:\SCS\Python\venvs\eat_tensorflow2_in_30_days-master\lib\site-packages\tensorflow\python\eager\function.py", line 2667, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "C:\SCS\Python\venvs\eat_tensorflow2_in_30_days-master\lib\site-packages\tensorflow\python\framework\func_graph.py", line 981, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "C:\SCS\Python\venvs\eat_tensorflow2_in_30_days-master\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 3214, in wrapper_fn
    ret = _wrapper_helper(*args)
  File "C:\SCS\Python\venvs\eat_tensorflow2_in_30_days-master\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 3156, in _wrapper_helper
    ret = autograph.tf_convert(func, ag_ctx)(*nested_args)
  File "C:\SCS\Python\venvs\eat_tensorflow2_in_30_days-master\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 262, in wrapper
    return converted_call(f, args, kwargs, options=options)
  File "C:\SCS\Python\venvs\eat_tensorflow2_in_30_days-master\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 580, in converted_call
    return _call_unconverted(f, args, kwargs, options)
  File "C:\SCS\Python\venvs\eat_tensorflow2_in_30_days-master\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 346, in _call_unconverted
    return f(*args, **kwargs)
  File "<input>", line 12, in load_image
  File "C:\SCS\Python\venvs\eat_tensorflow2_in_30_days-master\lib\site-packages\tensorflow\python\framework\ops.py", line 778, in __bool__
    self._disallow_bool_casting()
  File "C:\SCS\Python\venvs\eat_tensorflow2_in_30_days-master\lib\site-packages\tensorflow\python\framework\ops.py", line 548, in _disallow_bool_casting
    self._disallow_in_graph_mode("using a `tf.Tensor` as a Python `bool`")
  File "C:\SCS\Python\venvs\eat_tensorflow2_in_30_days-master\lib\site-packages\tensorflow\python\framework\ops.py", line 537, in _disallow_in_graph_mode
    " this function with @tf.function.".format(task))
tensorflow.python.framework.errors_impl.OperatorNotAllowedInGraphError: using a `tf.Tensor` as a Python `bool` is not allowed in Graph execution. Use Eager execution or decorate this function with @tf.function.
```

**Comment by jvishnuvardhan** [comment]
@mtdot Can you please share a standalone code to reproduce the issue? Thanks!

**Comment by mtdot** [comment]
@jvishnuvardhan i'm practicing with code from [here](https://github.com/lyhue1991/eat_tensorflow2_in_30_days/blob/master/english/Chapter1-3.md)

**Comment by jvishnuvardhan** [comment]
@mtdot @Tyson-Stur Can you please share a simple standalone code to reproduce the issue? It is difficult to follow long codes and I guess Stackoverflow would be better place as there is a big community to support learn from each other. GitHub is mainly for bugs and performance related issues. Thanks!

**Comment by mtdot** [comment]
After some google, i resolved that issue by replace the code bellow:
```
label = tf.constant(1, tf.int8) if tf.strings.regex_full_match(img_path, ".*automobile.*") \
        else tf.constant(0, tf.int8)
```
with
```
label = tf.cond(tf.equal(tf.strings.regex_full_match(img_path, ".*automobile.*"), tf.constant(True)), lambda: tf.constant(1, tf.int8),
                    lambda: tf.constant(0, tf.int8))
```

**Comment by nikitamaia** [comment]
Hi @mtdot, there is a library in tensorflow called AutoGraph, which transforms a subset of Python eager code into graph-compatible TensorFlow ops. This includes control flow like if, for, while. If you use AutoGraph, then you should be able to use if statements and not have to worry about replacing them with tf.cond like you have shown in the above example. AutoGraph will take care of transforming your python if statement into tf.cond.

The easiest way to use autograph is to [wrap your code in @tf.function](https://www.tensorflow.org/guide/function#setup), which makes graphs out of your programs and has [autograph turned on by default](https://www.tensorflow.org/guide/function#autograph_transformations). And you'll notice that the error message you have posted says to `Use Eager execution or decorate this function with @tf.function.` The guides I have linked to should clear up any confusion. However, if you share a standalone example that reproduces the error and can be run in colab, then I'd be happy to provide further help if needed.

**Comment by LukeLIN-web** [comment]
For me this is because `torch.zeros((all_actions_mask.shape[0], 1)).bool().to(device_id)`
