### ISSUE TITLE
tf.lite.TFLiteConverter.from_keras_model().convert() raise error with tf.keras.mixed_precision.experimental.Policy()

### ISSUE THREAD

**Issue by mdejeans** [tensorflow/tensorflow#40930]
### System information

-   **Have I written custom code (as opposed to using a stock example script
    provided in TensorFlow)**: yes
-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
-   **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue
    happens on a mobile device**:
-   **TensorFlow installed from (source or binary)**: binary
-   **TensorFlow version (use command below)**: v2.2.0-rc4-8-g2b96f3662b 2.2.0
-   **Python version**: 3.8.2
-   **Bazel version (if compiling from source)**:
-   **GCC/Compiler version (if compiling from source)**:
-   **CUDA/cuDNN version**: CUDA 10.1 / cuDNN 7.6.5
-   **GPU model and memory**:  NVIDIA GeForce GTX 970 / 4 Go
-   **Exact command to reproduce**:

### Describe the problem
Steps to reproduce the bug: execute the code provided with 'mixed_float16' mixed_precision policy.

In this situation we want to build a tflite model of an already quantitized model using  `tf.keras.mixed_precision.experimental.Policy("mixed_float16")`

But when executing the following, Tensorflow will crash and raise an "error: non-broadcastable operands" with some memory error.
```
converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()
```
If we pass mixed_precision_policy_arg to None and thus deactivate mixed_precision policy, everything goes fine.

Thanks you and have a good day!

### Source code / logs
Source code:
```
import tensorflow as tf
from tensorflow.keras.layers import Input, Lambda, Dense, Dropout
from tensorflow.keras.optimizers import Optimizer
from tensorflow.keras import backend as K
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.models import Model

# Activate mixed precision policy
mixed_precision_policy_arg: str = "mixed_float16"
if mixed_precision_policy_arg is not None:
    mixed_precision_policy = tf.keras.mixed_precision.experimental.Policy(
        mixed_precision_policy_arg)
    tf.keras.mixed_precision.experimental.set_policy(
        mixed_precision_policy)

# Size parameters for the model
img_height, img_width, img_depth = 224, 224, 3

# Model definition
inp = Input(shape=(int(img_height), int(img_width),
                    int(img_depth)))
mobilenet_model = MobileNetV2(input_shape=(int(img_height),
                                            int(img_width),
                                            int(img_depth)),
                                alpha=0.35,
                                include_top=False,
                                weights='imagenet',
                                input_tensor=inp,
                                pooling='avg')
out = Dense(1, activation='tanh')(mobilenet_model.output)

# Build the whole model.
model = Model(inputs=inp, outputs=out)

#Convert to tflite
converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()
# Save the TF Lite model.
with tf.io.gfile.GFile('./model.tflite', 'wb') as f:
    f.write(tflite_model)

```

Output logs:

```
2020-06-30 08:37:15.257384: I tensorflow/core/grappler/devices.cc:55] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 1
2020-06-30 08:37:15.262414: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2020-06-30 08:37:15.267142: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties:
pciBusID: 0000:08:00.0 name: GeForce GTX 970 computeCapability: 5.2
coreClock: 1.253GHz coreCount: 13 deviceMemorySize: 4.00GiB deviceMemoryBandwidth: 208.91GiB/s
2020-06-30 08:37:15.276114: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
2020-06-30 08:37:15.287313: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_10.dll
2020-06-30 08:37:15.292024: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_10.dll
2020-06-30 08:37:15.305367: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_10.dll
2020-06-30 08:37:15.310125: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_10.dll
2020-06-30 08:37:15.325054: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_10.dll
2020-06-30 08:37:15.338802: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-06-30 08:37:15.343460: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2020-06-30 08:37:15.356369: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-06-30 08:37:15.361262: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      0
2020-06-30 08:37:15.374944: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 0:   N 
2020-06-30 08:37:15.378461: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 2991 MB memory) -> physical GPU (device: 0, name: GeForce GTX 970, pci bus id: 0000:08:00.0, compute capability: 5.2)
2020-06-30 08:37:15.525109: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:797] Optimization results for grappler item: graph_to_optimize
2020-06-30 08:37:15.530484: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:799]   function_optimizer: function_optimizer did nothing. time = 0.003ms.
2020-06-30 08:37:15.536242: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:799]   function_optimizer: function_optimizer did nothing. time = 0ms.
2020-06-30 08:37:17.175576: I tensorflow/core/grappler/devices.cc:55] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 1
2020-06-30 08:37:17.180393: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2020-06-30 08:37:17.184777: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:08:00.0 name: GeForce GTX 970 computeCapability: 5.2
coreClock: 1.253GHz coreCount: 13 deviceMemorySize: 4.00GiB deviceMemoryBandwidth: 208.91GiB/s
2020-06-30 08:37:17.193569: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
2020-06-30 08:37:17.207166: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_10.dll
2020-06-30 08:37:17.211906: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_10.dll
2020-06-30 08:37:17.224565: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_10.dll
2020-06-30 08:37:17.240773: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_10.dll
2020-06-30 08:37:17.245702: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_10.dll
2020-06-30 08:37:17.260413: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-06-30 08:37:17.274603: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2020-06-30 08:37:17.278648: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-06-30 08:37:17.292135: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      0
2020-06-30 08:37:17.295110: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 0:   N
2020-06-30 08:37:17.308571: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 2991 MB memory) -> physical GPU (device: 0, name: GeForce GTX 970, pci bus id: 0000:08:00.0, compute capability: 5.2)
2020-06-30 08:37:17.530109: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:797] Optimization results for grappler item: graph_to_optimize
2020-06-30 08:37:17.535068: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:799]   constant_folding: Graph size after: 433 nodes (-350), 442 edges (-316), time = 31.294ms.
2020-06-30 08:37:17.540858: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:799]   constant_folding: Graph size after: 433 nodes (0), 442 edges (0), time = 7.549ms.
Traceback (most recent call last):
  File "c:\Users\Mathieu\Code\tfissue\tflite_issue.py", line 49, in <module>
    tflite_model = converter.convert()
  File "C:\Program Files\Python\lib\site-packages\tensorflow\lite\python\lite.py", line 514, in convert
    result = _toco_convert_impl(
  File "C:\Program Files\Python\lib\site-packages\tensorflow\lite\python\convert.py", line 491, in toco_convert_impl
    data = toco_convert_protos(
  File "C:\Program Files\Python\lib\site-packages\tensorflow\lite\python\convert.py", line 227, in toco_convert_protos
    raise ConverterError("See console for info.\n%s\n%s\n" % (stdout, stderr))
tensorflow.lite.python.convert.ConverterError: See console for info.
2020-06-30 08:37:18.218076: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
2020-06-30 08:37:20.341895: W tensorflow/compiler/mlir/lite/python/graphdef_to_tfl_flatbuffer.cc:144] Ignored output_format.
2020-06-30 08:37:20.342069: W tensorflow/compiler/mlir/lite/python/graphdef_to_tfl_flatbuffer.cc:147] Ignored drop_control_dependency.
2020-06-30 08:37:20.420203: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2020-06-30 08:37:20.428378: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x1803e4c72d0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:  
2020-06-30 08:37:20.428713: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-06-30 08:37:20.429873: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2020-06-30 08:37:20.453669: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties:
pciBusID: 0000:08:00.0 name: GeForce GTX 970 computeCapability: 5.2
coreClock: 1.253GHz coreCount: 13 deviceMemorySize: 4.00GiB deviceMemoryBandwidth: 208.91GiB/s
2020-06-30 08:37:20.454062: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
2020-06-30 08:37:20.457145: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_10.dll
2020-06-30 08:37:20.459818: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_10.dll
2020-06-30 08:37:20.460738: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_10.dll
2020-06-30 08:37:20.464328: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_10.dll
2020-06-30 08:37:20.466349: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_10.dll
2020-06-30 08:37:20.472167: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-06-30 08:37:20.472361: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2020-06-30 08:37:21.033060: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-06-30 08:37:21.033405: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      0
2020-06-30 08:37:21.033543: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 0:   N
2020-06-30 08:37:21.033777: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 2854 MB memory) -> physical GPU (device: 0, name: GeForce GTX 970, pci bus id: 0000:08:00.0, compute capability: 5.2)
2020-06-30 08:37:21.037082: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x1805bff0530 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:  
2020-06-30 08:37:21.037386: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce GTX 970, Compute Capability 5.2
loc(callsite("model/Conv_1_bn/FusedBatchNormV3"("C:\Program Files\Python\lib\site-packages\tensorflow\python\eager\def_function.py":865:0) at callsite("C:\Program Files\Python\lib\site-packages\tensorflow\python\eager\def_function.py":959:0 at callsite("C:\Program Files\Python\lib\site-packages\tensorflow\lite\python\lite.py":435:0 at "c:\Users\Mathieu\Code\tfissue\tflite_issue.py":48:0)))): error: non-broadcastable operands
Windows fatal exception: access violation

Current thread 0x00001e54 (most recent call first):
  File "c:\program files\python\lib\site-packages\tensorflow\lite\toco\python\toco_from_protos.py", line 50 in execute
  File "c:\program files\python\lib\site-packages\absl\app.py", line 250 in _run_main
  File "c:\program files\python\lib\site-packages\absl\app.py", line 299 in run
  File "c:\program files\python\lib\site-packages\tensorflow\python\platform\app.py", line 40 in run
  File "c:\program files\python\lib\site-packages\tensorflow\lite\toco\python\toco_from_protos.py", line 93 in main
  File "C:\Program Files\Python\Scripts\toco_from_protos.exe\__main__.py", line 7 in <module>
  File "c:\program files\python\lib\runpy.py", line 86 in _run_code
  File "c:\program files\python\lib\runpy.py", line 193 in _run_module_as_main
```

**Comment by abattery** [comment]
Could you try conversion with tf-nightly?

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.2 and TF-nightly. 

With both versions, session crashes on running the code, please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/a2acfda60b84684c3b6c430a71f7cd3b/40930.ipynb). Thanks!

**Comment by abattery** [comment]
Crashing is coming from MLIR converter.

**Comment by abattery** [comment]
Hi @mdejeans 

Sorry. Currently, TFLite does not support keras's mixed precision policy.

Please use the TensorFlow Model Optimization Toolkit instead.
https://www.tensorflow.org/lite/performance/model_optimization

**Comment by mdejeans** [comment]
Thanks @abattery to have looked into it.

I hope it will be supported in further realese to unify the experience accross keras/tensorflow. 
Maybe something could be added to the docs to warn that it's not yet supported ? I've spent a certain amount of time to understand where it was comming from ! ;-)

**Comment by abattery** [comment]
@mdejeans Thanks for taking your time to look at this issue. Nice suggestion! TFLite converter should warn the users before crashing as you suggested.

**Comment by GPhilo** [comment]
@abattery Is TFLite still not supporting keras' mixed precision policies? I can't find any information about this in Tensorflow's or TFLite's documentation.
