### ISSUE TITLE
ValueError: Unrolling requires a fixed number of timesteps.

### ISSUE THREAD

**Issue by vyshnavigutta369** [tensorflow/tensorflow#40985]
Hi, I am trying to build a model with tensorflow 2.1.0. I was getting this error in model.fit. Can anyone please let me know how this can be resolved? 

checkpoint = ModelCheckpoint('test/checkpointv7', monitor='acc', verbose=1, save_best_only=True, mode='max')
callbacks_list = [checkpoint]
model.fit(input_data, output_data,batch_size=2, epochs=20, callbacks=callbacks_list)

Epoch 1/20
 8/10 [=======================>......] - ETA: 1s - loss: 1.9467 - acc: 0.1915     
Epoch 00001: acc improved from -inf to 0.21429, saving model to test/checkpointv7
Traceback (most recent call last):
  File "MLtxt2txtv7.py", line 633, in <module>
    model.fit(input_data, output_data,batch_size=2, epochs=20, callbacks=callbacks_list)
  File "/home/iiit/revanth.parvathaneni/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py", line 819, in fit
    use_multiprocessing=use_multiprocessing)
  File "/home/iiit/revanth.parvathaneni/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 397, in fit
    prefix='val_')
  File "/usr/lib64/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/home/iiit/revanth.parvathaneni/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 771, in on_epoch
    self.callbacks.on_epoch_end(epoch, epoch_logs)
  File "/home/iiit/revanth.parvathaneni/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/callbacks.py", line 302, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/home/iiit/revanth.parvathaneni/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/callbacks.py", line 992, in on_epoch_end
    self._save_model(epoch=epoch, logs=logs)
  File "/home/iiit/revanth.parvathaneni/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/callbacks.py", line 1029, in _save_model
    self.model.save(filepath, overwrite=True)
  File "/home/iiit/revanth.parvathaneni/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/network.py", line 1008, in save
    signatures, options)
  File "/home/iiit/revanth.parvathaneni/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/saving/save.py", line 115, in save_model
    signatures, options)
  File "/home/iiit/revanth.parvathaneni/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/saving/saved_model/save.py", line 78, in save
    save_lib.save(model, filepath, signatures, options)
  File "/home/iiit/revanth.parvathaneni/.local/lib/python3.6/site-packages/tensorflow_core/python/saved_model/save.py", line 886, in save
    checkpoint_graph_view)
  File "/home/iiit/revanth.parvathaneni/.local/lib/python3.6/site-packages/tensorflow_core/python/saved_model/signature_serialization.py", line 74, in find_function_to_export
    functions = saveable_view.list_functions(saveable_view.root)
  File "/home/iiit/revanth.parvathaneni/.local/lib/python3.6/site-packages/tensorflow_core/python/saved_model/save.py", line 142, in list_functions
    self._serialization_cache)
  File "/home/iiit/revanth.parvathaneni/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 2420, in _list_functions_for_serialization
    .list_functions_for_serialization(serialization_cache))
  File "/home/iiit/revanth.parvathaneni/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/saving/saved_model/base_serialization.py", line 91, in list_functions_for_serialization
    fns = self.functions_to_serialize(serialization_cache)
  File "/home/iiit/revanth.parvathaneni/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/saving/saved_model/layer_serialization.py", line 80, in functions_to_serialize
    serialization_cache).functions_to_serialize)
  File "/home/iiit/revanth.parvathaneni/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/saving/saved_model/layer_serialization.py", line 95, in _get_serialized_attributes
    serialization_cache)
  File "/home/iiit/revanth.parvathaneni/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/saving/saved_model/model_serialization.py", line 53, in _get_serialized_attributes_internal
    serialization_cache))
  File "/home/iiit/revanth.parvathaneni/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/saving/saved_model/layer_serialization.py", line 104, in _get_serialized_attributes_internal
    functions = save_impl.wrap_layer_functions(self.obj, serialization_cache)
  File "/home/iiit/revanth.parvathaneni/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/saving/saved_model/save_impl.py", line 162, in wrap_layer_functions
    original_fns = _replace_child_layer_functions(layer, serialization_cache)
  File "/home/iiit/revanth.parvathaneni/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/saving/saved_model/save_impl.py", line 258, in _replace_child_layer_functions
    serialization_cache).functions)
  File "/home/iiit/revanth.parvathaneni/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/saving/saved_model/layer_serialization.py", line 95, in _get_serialized_attributes
    serialization_cache)
  File "/home/iiit/revanth.parvathaneni/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/saving/saved_model/layer_serialization.py", line 104, in _get_serialized_attributes_internal
    functions = save_impl.wrap_layer_functions(self.obj, serialization_cache)
  File "/home/iiit/revanth.parvathaneni/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/saving/saved_model/save_impl.py", line 162, in wrap_layer_functions
    original_fns = _replace_child_layer_functions(layer, serialization_cache)
  File "/home/iiit/revanth.parvathaneni/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/saving/saved_model/save_impl.py", line 258, in _replace_child_layer_functions
    serialization_cache).functions)
  File "/home/iiit/revanth.parvathaneni/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/saving/saved_model/layer_serialization.py", line 95, in _get_serialized_attributes
    serialization_cache)
  File "/home/iiit/revanth.parvathaneni/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/saving/saved_model/layer_serialization.py", line 104, in _get_serialized_attributes_internal
    functions = save_impl.wrap_layer_functions(self.obj, serialization_cache)
  File "/home/iiit/revanth.parvathaneni/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/saving/saved_model/save_impl.py", line 172, in wrap_layer_functions
    '{}_layer_call_and_return_conditional_losses'.format(layer.name))
  File "/home/iiit/revanth.parvathaneni/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/saving/saved_model/save_impl.py", line 513, in add_function
    self.add_trace(*self._input_signature)
  File "/home/iiit/revanth.parvathaneni/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/saving/saved_model/save_impl.py", line 428, in add_trace
    trace_with_training(True)
  File "/home/iiit/revanth.parvathaneni/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/saving/saved_model/save_impl.py", line 426, in trace_with_training
    fn.get_concrete_function(*args, **kwargs)
  File "/home/iiit/revanth.parvathaneni/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/saving/saved_model/save_impl.py", line 557, in get_concrete_function
    return super(LayerCall, self).get_concrete_function(*args, **kwargs)
  File "/home/iiit/revanth.parvathaneni/.local/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 909, in get_concrete_function
    self._initialize(args, kwargs, add_initializers_to=initializers)
  File "/home/iiit/revanth.parvathaneni/.local/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 497, in _initialize
    *args, **kwds))
  File "/home/iiit/revanth.parvathaneni/.local/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2389, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/home/iiit/revanth.parvathaneni/.local/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2703, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/home/iiit/revanth.parvathaneni/.local/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2593, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/home/iiit/revanth.parvathaneni/.local/lib/python3.6/site-packages/tensorflow_core/python/framework/func_graph.py", line 978, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/iiit/revanth.parvathaneni/.local/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 439, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/home/iiit/revanth.parvathaneni/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/saving/saved_model/save_impl.py", line 534, in wrapper
    ret = method(*args, **kwargs)
  File "/home/iiit/revanth.parvathaneni/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/saving/saved_model/utils.py", line 113, in wrap_with_training_arg
    lambda: replace_training_and_call(False))
  File "/home/iiit/revanth.parvathaneni/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/utils/tf_utils.py", line 59, in smart_cond
    pred, true_fn=true_fn, false_fn=false_fn, name=name)
  File "/home/iiit/revanth.parvathaneni/.local/lib/python3.6/site-packages/tensorflow_core/python/framework/smart_cond.py", line 54, in smart_cond
    return true_fn()
  File "/home/iiit/revanth.parvathaneni/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/saving/saved_model/utils.py", line 112, in <lambda>
    lambda: replace_training_and_call(True),
  File "/home/iiit/revanth.parvathaneni/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/saving/saved_model/utils.py", line 108, in replace_training_and_call
    return wrapped_call(*args, **kwargs)
  File "/home/iiit/revanth.parvathaneni/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/saving/saved_model/save_impl.py", line 576, in call_and_return_conditional_losses
    return layer_call(inputs, *args, **kwargs), layer.get_losses_for(inputs)
  File "/home/iiit/revanth.parvathaneni/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/layers/recurrent_v2.py", line 417, in call
    zero_output_for_mask=self.zero_output_for_mask)
  File "/home/iiit/revanth.parvathaneni/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/backend.py", line 3926, in rnn
    raise ValueError('Unrolling requires a fixed number of timesteps.')
ValueError: Unrolling requires a fixed number of timesteps.

**Comment by ravikyram** [comment]
@vyshnavigutta369 

Request you to share colab link or simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by gowthamkpr** [comment]
@vyshnavigutta369 As per the error message and the documentation [here](https://www.tensorflow.org/api_docs/python/tf/keras/backend/rnn), you will only encounter this error if in `tf.keras.backend.rnn` the argument `unroll` is True but input timestep is not a fixed number. So make your timestep a fixed number and the issue should be resolved.

Also I am closing this issue as it has been inactive for more than 2 weeks. Please add additional comments for us to open this issue again. Thanks!
