### ISSUE TITLE
tflite RuntimeError: Encountered unresolved custom op: CombinedNonMaxSuppression.Node number 148 (CombinedNonMaxSuppression) failed to prepare.

### ISSUE THREAD

**Issue by aselva-eb** [tensorflow/tensorflow#41012]
**System information**
- Linux 
- TF 2.5.0-dev20200629

**Command used to run the converter or code if you’re using the Python API**

Converter:

```
    converter = tf.lite.TFLiteConverter.from_saved_model(curr_dir + "saved_model_2")
    converter.experimental_new_converter = True
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,
                                           tf.lite.OpsSet.SELECT_TF_OPS]
    converter.allow_custom_ops = True

    tflite_model = converter.convert()
```

Inference:

```
# Load the TFLite model and allocate tensors.
interpreter = tf.lite.Interpreter(model_path="./model.tflite")
interpreter.allocate_tensors()
print("all ok")

# # Get input and output tensors.
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

# # Test the model on random input data.
input_shape = input_details[0]['shape']
input_data = np.array(np.random.random_sample(input_shape), dtype=np.float32)
interpreter.set_tensor(input_details[0]['index'], input_data)

interpreter.invoke()

# # The function `get_tensor()` returns a copy of the tensor data.
# # Use `tensor()` in order to get a pointer to the tensor.
output_data = interpreter.get_tensor(output_details[0]['index'])
print(output_data)
```

**The output from the converter invocation**

```
  File "inference.py", line 19, in <module>
    interpreter.invoke()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/interpreter.py", line 524, in invoke
    self._interpreter.Invoke()
RuntimeError: Encountered unresolved custom op: CombinedNonMaxSuppression.Node number 148 (CombinedNonMaxSuppression) failed to prepare.
```

I'm wondering why the flex delegate couldn't prepare the CombinedNonMaxSuppression function, even though I have the `SELECT_TF_OPS` flag enabled?

**Comment by abattery** [comment]
Thai, could you help me adding CombinedNonMaxSuppression op to flex?

**Comment by thaink** [comment]
OK. Let me add it.

**Comment by aselva-eb** [comment]
Hi @thaink 
Is this a matter of adding CombinedNonMaxSuppression to 
//tensorflow/lite/delegates/flex/whitelisted_flex_ops.cc ?

**Comment by thaink** [comment]
@aselva-eb Right. A PR is on the way to add it.

**Comment by aselva-eb** [comment]
Thank you @thaink!

**Comment by aselva-eb** [comment]
> @aselva-eb Right. A PR is on the way to add it.

Hi @thaink, Is there an approx ETA?

**Comment by thaink** [comment]
I think it will be supported within this week. Thanks.

**Comment by thaink** [comment]
CombinedNonMaxSuppression is added at master. Please check it.

**Comment by aselva-eb** [comment]
> CombinedNonMaxSuppression is added at master. Please check it.

Did it make it into `2.4.0.dev20200714` release ?

Running that version of tf_nightly but have issues importing tensorflow. This is within the tensorflow/tensorflow docker container. Tried a fresh docker too. This doesn't happen on MacOS but I can't test on it because as mentioned above, FlexOps aren't supported on MacOS yet

```
>>> import tensorflow as tf
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: libcudart.so.10.1: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/__init__.py", line 40, in <module>
    from tensorflow.python.eager import context
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/context.py", line 35, in <module>
    from tensorflow.python import pywrap_tfe
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tfe.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 83, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: libcudart.so.10.1: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

**Comment by thaink** [comment]
No, it should be in the nightly tomorrow.

**Comment by aselva-eb** [comment]
@thaink 
Thanks for adding it to flex ops. Invoking the model passes now, however, my output is suspiciously all 0s on a random input. Will need to dig into this a bit more.

**Comment by Saduf2019** [comment]
@aselva-eb
please let us know if this is still an issue else please move the issue to closed status.

**Comment by aselva-eb** [comment]
> @aselva-eb
> please let us know if this is still an issue else please move the issue to closed status.

We can close this ticket. I believe it is resolved. Thanks!
