### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow.compiler.tf2tensorrt'

### ISSUE THREAD

**Issue by LumaRay** [tensorflow/tensorflow#41022]
Hello.

I have created a small python application using tensorflow 2.2.0 and can run it with no problem using python 3.7.4
Then I use pyinstaller to make a package of my project. 
But when I try to run pyinstaller compiled version, I get this error (line 14 is "import tensorflow as tf").

```
Traceback (most recent call last):
  File "test_wx1.py", line 14, in <module>
  File "/usr/local/lib/python3.7/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "tensorflow/__init__.py", line 41, in <module>
  File "/usr/local/lib/python3.7/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "tensorflow/python/__init__.py", line 74, in <module>
  File "/usr/local/lib/python3.7/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "tensorflow/python/ops/standard_ops.py", line 117, in <module>
  File "/usr/local/lib/python3.7/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "tensorflow/python/compiler/tensorrt/__init__.py", line 22, in <module>
  File "/usr/local/lib/python3.7/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "tensorflow/python/compiler/tensorrt/trt_convert.py", line 79, in <module>
  File "tensorflow/python/util/lazy_loader.py", line 62, in __getattr__
  File "tensorflow/python/util/lazy_loader.py", line 45, in _load
  File "importlib/__init__.py", line 127, in import_module
ModuleNotFoundError: No module named 'tensorflow.compiler.tf2tensorrt'
```

I cannot find any information Googling, so maybe you could help? 
Or maybe this is solely pyinstaller's responsibility and I should ask them?

**Comment by amahendrakar** [comment]
@LumaRay,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here.

Also, please check [this thread](https://github.com/pyinstaller/pyinstaller/issues/4400) and let us know if it helps. Thanks!

**Comment by LumaRay** [comment]
@amahendrakar,
Well, I tried narrowing down my code and came to a conclusion that in order to reproduce you need just to create any python file and put a single line in it:

`import tensorflow as tf`

Sorry, I could not make any use of the link you gave me.

I use PyInstaller 3.6 and setuptools 44.1.1

**Comment by jacqueskang** [comment]
I'm having the same issue using PyInstaller 3.6 and setuptools 49.2.0

**Comment by br13patel** [comment]
In my case, I am abel to make it work by creating custom hook file for tensorflow as below:

test.py -> [test.zip](https://github.com/tensorflow/tensorflow/files/4987535/test.zip)
hook-tensorflow.py -> [hook-tensorflow.zip](https://github.com/tensorflow/tensorflow/files/4987536/hook-tensorflow.zip)

# Copy **hook-tensorflow.py** to **./hooks/**
# pyinstaller test.py --additional-hooks-dir ./hooks/

**Comment by bpops** [comment]
> In my case, I am able to make it work by creating custom hook file for tensorflow as below:
> 
> test.py -> [test.zip](https://github.com/tensorflow/tensorflow/files/4987535/test.zip)
> hook-tensorflow.py -> [hook-tensorflow.zip](https://github.com/tensorflow/tensorflow/files/4987536/hook-tensorflow.zip)
> 
> * Copy hook-tensorflow.py to ./hooks/
> * pyinstaller test.py --additional-hooks-dir ./hooks/

Thank you so much for this. In my particular case, your hook fixed my issue!

**Comment by HSV2PVG** [comment]
I had the same problem on CentOS 7 where line 12 in pfexplorer.py  is "import tensorflow as tf".
Tensorflow 2.3.0 (CPU & GPU)
Python 3.6.9
CUDA10.1
TensorRT6.0.1.5


```
/usr/local/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py:493: MatplotlibDeprecationWarning: 
The MATPLOTLIBDATA environment variable was deprecated in Matplotlib 3.1 and will be removed in 3.3.
  exec(bytecode, module.__dict__)
2020-10-21 15:10:35.535785: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
Traceback (most recent call last):
  File "test.py", line 3, in <module>
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "src/launcher.py", line 23, in <module>
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "src/pfexplorer.py", line 12, in <module>
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "tensorflow/__init__.py", line 41, in <module>
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "tensorflow/python/__init__.py", line 47, in <module>
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "tensorflow/python/keras/__init__.py", line 27, in <module>
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "tensorflow/python/keras/models.py", line 27, in <module>
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "tensorflow/python/keras/engine/sequential.py", line 27, in <module>
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "tensorflow/python/keras/layers/__init__.py", line 122, in <module>
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "tensorflow/python/keras/layers/core.py", line 45, in <module>
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "tensorflow/python/keras/layers/ops/core.py", line 26, in <module>
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "tensorflow/python/ops/standard_ops.py", line 117, in <module>
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "tensorflow/python/compiler/tensorrt/__init__.py", line 22, in <module>
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "tensorflow/python/compiler/tensorrt/trt_convert.py", line 79, in <module>
  File "tensorflow/python/util/lazy_loader.py", line 62, in __getattr__
  File "tensorflow/python/util/lazy_loader.py", line 45, in _load
  File "importlib/__init__.py", line 126, in import_module
ModuleNotFoundError: No module named 'tensorflow.compiler.tf2tensorrt'
[393] Failed to execute script test


```

**Comment by HSV2PVG** [comment]
> In my case, I am able to make it work by creating custom hook file for tensorflow as below:
> 
> test.py -> [test.zip](https://github.com/tensorflow/tensorflow/files/4987535/test.zip)
> hook-tensorflow.py -> [hook-tensorflow.zip](https://github.com/tensorflow/tensorflow/files/4987536/hook-tensorflow.zip)
> 
> * Copy hook-tensorflow.py to ./hooks/
> * pyinstaller test.py --additional-hooks-dir ./hooks/

Could you explain a little more on the hook file? I dont have much experience with that.  Thank you so much.

**Comment by sushreebarsa** [comment]
@LumaRay 
Is this still an issue ? It looks like you are using an older Version of Tensorflow . Can you please try to  use Latest Version 2.7.0 and let us know if it helps? Thanks!
