### ISSUE TITLE
[RNN] Loading quantized LSTM model with state handling into TF Lite interpreter fails.

### ISSUE THREAD

**Issue by breizhn** [tensorflow/tensorflow#41023]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOs / Ubuntu 18.04
- TensorFlow installed from (source or binary): binary / pip
- TensorFlow version (or github SHA if from source): 2.3.0rc0

**Command used to run the converter or code if you’re using the Python API**
If possible, please share a link to Colab/Jupyter/any notebook.

```python
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import  LSTM, Input


in_dat = Input(batch_shape=(1,1,128))
in_states = Input(batch_shape=(1,1,128,2))


in_state = [in_states[:,0,:,0], in_states[:,0,:,1]]
out_dat, state_h, state_c = LSTM(128, 
                                 return_sequences=True, 
                                 return_state=True)(in_dat, initial_state=in_state)

out_states = tf.stack([state_h, state_c],axis=-1)

model = Model(inputs=[in_dat, in_states], 
                           outputs=[out_dat, out_states])


converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
tflite_model = converter.convert()
with tf.io.gfile.GFile('test_model.tflite', 'wb') as f:
      f.write(tflite_model)

interpreter = tf.lite.Interpreter(model_path='./test_model.tflite')
```

**The output from the converter invocation**
Conversion works fine, the interpreter can not load the model:
```
2020-07-02 10:58:39.439478: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fd0c32e2e10 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-07-02 10:58:39.439818: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
WARNING:tensorflow:From /Applications/anaconda3/envs/tf23env/lib/python3.7/site-packages/tensorflow/python/training/tracking/tracking.py:111: Model.state_updates (from tensorflow.python.keras.engine.training) is deprecated and will be removed in a future version.
Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.
2020-07-02 10:58:41.751516: W tensorflow/python/util/util.cc:348] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
WARNING:tensorflow:From /Applications/anaconda3/envs/tf23env/lib/python3.7/site-packages/tensorflow/python/training/tracking/tracking.py:111: Layer.updates (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.
2020-07-02 10:58:48.388047: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:313] Ignored output_format.
2020-07-02 10:58:48.388077: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:316] Ignored drop_control_dependency.
2020-07-02 10:58:48.395287: I tensorflow/cc/saved_model/reader.cc:31] Reading SavedModel from: /var/folders/p4/yptj61953073c48n66hnlr100000gp/T/tmpu_2uf65d
2020-07-02 10:58:48.419914: I tensorflow/cc/saved_model/reader.cc:54] Reading meta graph with tags { serve }
2020-07-02 10:58:48.419953: I tensorflow/cc/saved_model/loader.cc:234] Reading SavedModel debug info (if present) from: /var/folders/p4/yptj61953073c48n66hnlr100000gp/T/tmpu_2uf65d
2020-07-02 10:58:48.509456: I tensorflow/cc/saved_model/loader.cc:199] Restoring SavedModel bundle.
2020-07-02 10:58:48.669926: I tensorflow/cc/saved_model/loader.cc:183] Running initialization op on SavedModel bundle at path: /var/folders/p4/yptj61953073c48n66hnlr100000gp/T/tmpu_2uf65d
2020-07-02 10:58:48.753087: I tensorflow/cc/saved_model/loader.cc:303] SavedModel load for tags { serve }; Status: success: OK. Took 358438 microseconds.
2020-07-02 10:58:49.363263: I tensorflow/lite/tools/optimize/quantize_weights.cc:211] Skipping quantization of tensor arg5 because it has fewer than 1024 elements (128).
Traceback (most recent call last):
  File "test_tf_lite.py", line 41, in <module>
    interpreter_1 = tf.lite.Interpreter(model_path='./test_model.tflite')
  File "/Applications/anaconda3/envs/tf23env/lib/python3.7/site-packages/tensorflow/lite/python/interpreter.py", line 198, in __init__
    model_path, self._custom_op_registerers))
ValueError: Did not get operators, tensors, or buffers in subgraph 1.
```

**Also, please include a link to the saved model or GraphDef**

[test_model.tflite.zip](https://github.com/tensorflow/tensorflow/files/4863193/test_model.tflite.zip)

**Failure details**
If the conversion is successful, but the generated model is wrong,
state what is wrong:
- Model can not be loaded by the interpreter
- Without quantization, conversion, loading and invoke works fine.
- Worked before with a tf-nightly, but I don't know anymore which one.
- Same behaviour on MacOs and Linux
- Same behaviour when converting from SavedModel format
- Same behaviour with tf-lite runtime

**RNN conversion support**
If converting TF RNN to TFLite fused RNN ops, please prefix [RNN] in the title.

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by breizhn** [comment]
I also tried this code for conversion, I found in another issue, but with the same result:
```python
@tf.function
def call(x, states):
    x, states = model([x,states])
    return x, states

batch_size = 1
concrete_func = call.get_concrete_function(
    x = tf.TensorSpec(shape=[batch_size,1,128], dtype=tf.float32), 
    states = tf.TensorSpec(shape=[batch_size,1,128, 2], dtype=tf.float32))
export_dir = '/tmp/saved_model'
model.save(export_dir, save_format="tf", signatures=concrete_func)

converter = tf.lite.TFLiteConverter.from_saved_model(export_dir)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
tflite_model = converter.convert()
```

**Comment by breizhn** [comment]
With adding ```unroll=True``` for the LSTM the interpreter is returning. But what is the reason?

**Comment by abattery** [comment]
It seems that an empty session initializer is being carried to TFLite converter. Will fix this problem soon.

**Comment by abattery** [comment]
@breizhn could you try the conversion with tomorrow's tf-nightly?

**Comment by arcral** [comment]
@breizhn i have met the same problem. do u solve it?

**Comment by breizhn** [comment]
@abattery I will try it tomorrow!

@arcral, with ```unroll=True``` it works fine for me.

**Comment by breizhn** [comment]
@abattery: With `tf-nightly-cpu==2.4.0-dev20200703`it works without `unroll=True`.

Another thing, I noticed, that the current version of the tf-lite runtime does not support converted Dense layers from conversion with tf-nightly. But loading with the builtin Interpreter works. 
The error message with the current runtime is following:
```
Traceback (most recent call last):
  File "test_tf_lite.py", line 113, in <module>
    interpreter = tflite.Interpreter(model_path='./test_model.tflite')
  File "/Applications/anaconda3/envs/tfnightlyenv/lib/python3.7/site-packages/tflite_runtime/interpreter.py", line 204, in __init__
    model_path, self._custom_op_registerers))
ValueError: Didn't find op for builtin opcode 'FULLY_CONNECTED' version '9'
Registration failed.
```

For me it looks like a version mismatch. Will the runtime be updated soon? Or is there a flag for downwards compatibility? Maybe this is another issue.

**Comment by abattery** [comment]
If you use the conversion with tf-nightly, the runtime version should be matched with the converter version to align operation versions. Could you use the interpreter of the same version with the converter?

**Comment by breizhn** [comment]
Where can I download a more current version of the TF-lite runtime. At [https://www.tensorflow.org/lite/guide/python](https://www.tensorflow.org/lite/guide/python) there is only a 2.1 version. 

The Interpreter from the tf-nightly package is working.
