### ISSUE TITLE
 error: 'tfl.concatenation'

### ISSUE THREAD

**Issue by karanjakhar** [tensorflow/tensorflow#41036]
```
ConverterError                            Traceback (most recent call last)
<ipython-input-162-bce3c984534c> in <module>
      6 )
      7 converter.optimizations = [tf.lite.Optimize.DEFAULT]
----> 8 tflite_model = converter.convert()
      9 with tf.io.gfile.GFile('model.tflite', 'wb') as f:
     10   f.write(tflite_model)

~/anaconda3/lib/python3.7/site-packages/tensorflow/lite/python/lite.py in convert(self)
   1082           input_tensors=self._input_tensors,
   1083           output_tensors=self._output_tensors,
-> 1084           **converter_kwargs)
   1085     else:
   1086       result = _toco_convert_graph_def(

~/anaconda3/lib/python3.7/site-packages/tensorflow/lite/python/convert.py in toco_convert_impl(input_data, input_tensors, output_tensors, enable_mlir_converter, *args, **kwargs)
    494       input_data.SerializeToString(),
    495       debug_info_str=debug_info_str,
--> 496       enable_mlir_converter=enable_mlir_converter)
    497   return data
    498 

~/anaconda3/lib/python3.7/site-packages/tensorflow/lite/python/convert.py in toco_convert_protos(model_flags_str, toco_flags_str, input_data_str, debug_info_str, enable_mlir_converter)
    225       stdout = _try_convert_to_unicode(stdout)
    226       stderr = _try_convert_to_unicode(stderr)
--> 227       raise ConverterError("See console for info.\n%s\n%s\n" % (stdout, stderr))
    228   finally:
    229     # Must manually cleanup files.

ConverterError: See console for info.
loc("Concat_165"): error: 'tfl.concatenation' op dimension size of dimension #3 of operand #0 must be equal to dimension size of dimension #3 of output, expected 40, got 20
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/bin/toco_from_protos", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 93, in main
    app.run(main=execute, argv=[sys.argv[0]] + unparsed)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 56, in execute
    enable_mlir_converter)
Exception: <unknown>:0: error: loc("Concat_165"): 'tfl.concatenation' op dimension size of dimension #3 of operand #0 must be equal to dimension size of dimension #3 of output, expected 40, got 20
```
I am converting a fronzen graph (.pb) to tflite and encountered this error. I have no idea why this is happen. Please help me.
Using below code for conversion.

```
import tensorflow as tf
converter = tf.compat.v1.lite.TFLiteConverter.from_frozen_graph(
    graph_def_file = 'weights/yolov5s_v1.pb', 
    input_arrays = ['images'],
    output_arrays = ['output','463','482'] 
)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
tflite_model = converter.convert()
with tf.io.gfile.GFile('model.tflite', 'wb') as f:
  f.write(tflite_model)

```

**Comment by abattery** [comment]
@karanjakhar can you provide the pb file or a minimal step to reproduce the problem?

**Comment by karanjakhar** [comment]
https://drive.google.com/file/d/1fuVQiQ53G1DZmDELm0WkIchCcvMHOg7a/view?usp=sharing

**Comment by abattery** [comment]
Thanks @karanjakhar I can reproduce with your model. Team will take a look.

**Comment by smit-hinsu** [comment]
I looked into this and found that the input model has invalid shapes.

Here, two operands of the concat operation don't have compatible shapes. Operands should have same dimensions except the axis dimension. Here, the dimensions are [1, 256, 40, 20] and [1, 256, 40, 40].

The first operand is coming from this function.
https://gist.github.com/smit-hinsu/95150cb40a523f0d892fe32d1cd03009

Let us know if this doesn't help you fix the dimensions in the model and need further assistance. If you can generate some sample data, you can try running the model with a sample input before conversion to identify source of the issue.
