### ISSUE TITLE
 While training first TensorFlow neural net model

### ISSUE THREAD

**Issue by aguilarandres** [tensorflow/tensorflow#4107]
I build tensorflow for Mac OSX from sources following the Download and Setup guide from tensorflow.org. 

```
$ which python
/usr/local/bin/python
$ pip --version
pip 8.1.2 from /usr/local/lib/python2.7/site-packages (python 2.7)
```

Created the pip package and installed it with NO GPU support. 

```
$ bazel build -c opt //tensorflow/tools/pip_package:build_pip_package

$ bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg

# The name of the .whl file will depend on your platform.
$ sudo pip install /tmp/tensorflow_pkg/tensorflow-0.10.0rc0-py2-none-any.whl
```

When attempting to Train first neural net model from the root of the source tree:

```
$ cd tensorflow/models/image/mnist
$ python convolutional.py

Extracting data/train-images-idx3-ubyte.gz
Extracting data/train-labels-idx1-ubyte.gz
Extracting data/t10k-images-idx3-ubyte.gz
Extracting data/t10k-labels-idx1-ubyte.gz

Traceback (most recent call last):
  File "convolutional.py", line 326, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/platform/default/_app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "convolutional.py", line 243, in main
    batch = tf.Variable(0, dtype=data_type())

TypeError: __init__() got an unexpected keyword argument 'dtype'
```

**Comment by mrry** [comment]
This keyword argument has been available since https://github.com/tensorflow/tensorflow/commit/60dfe8852cfd9565e622e423098bdad746dc3aee, which includes TensorFlow versions 0.8 and later.

Can you try the following at a Python shell and report the results?

* `import tensorflow as tf; print tf.__version__`
* `help(tf.Variable)`

**Comment by aguilarandres** [comment]
```
>>> import tensorflow as tf; print tf.__version__
0.7.1
```

**Comment by vrv** [comment]
You'll need to upgrade your version of tensorflow to 0.8+, or check out the source code at the 0.7.1 tree, not master.
