### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by adamczykp** [tensorflow/tensorflow#41099]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: -
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 2.2.0
- Python version: 3.6 / 3.8
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): - 
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: -
- GPU model and memory: NVIDIA GeForce GTX 960 6,0 GB

**Describe the problem**
While having installed the Tensorflow package via Pycharm Keras does not work. It does not want to import the Sequential Model from Keras. We want to run a unit test on a Keras-based neural network an it is not working. Here is my error message:

Error
Traceback (most recent call last):
  File "C:\Users\Philip\AppData\Local\Programs\Python\Python36\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "C:\Users\Philip\AppData\Local\Programs\Python\Python36\lib\unittest\case.py", line 601, in run
    testMethod()
  File "C:\Users\Philip\AppData\Local\Programs\Python\Python36\lib\unittest\loader.py", line 34, in testFailure
    raise self._exception
ImportError: Failed to import test module: test_neural_network
Traceback (most recent call last):
  File "D:\Uni\SS 20\Computerlinguistische Anwendungen\jophya\src\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "D:\Uni\SS 20\Computerlinguistische Anwendungen\jophya\src\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "D:\Uni\SS 20\Computerlinguistische Anwendungen\jophya\src\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Philip\AppData\Local\Programs\Python\Python36\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Philip\AppData\Local\Programs\Python\Python36\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Uni\SS 20\Computerlinguistische Anwendungen\jophya\src\venv\lib\site-packages\keras\__init__.py", line 3, in <module>
    from tensorflow.keras.layers.experimental.preprocessing import RandomRotation
  File "D:\Uni\SS 20\Computerlinguistische Anwendungen\jophya\src\venv\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "D:\Uni\SS 20\Computerlinguistische Anwendungen\jophya\src\venv\lib\site-packages\tensorflow\python\__init__.py", line 50, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "D:\Uni\SS 20\Computerlinguistische Anwendungen\jophya\src\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 69, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "D:\Uni\SS 20\Computerlinguistische Anwendungen\jophya\src\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "D:\Uni\SS 20\Computerlinguistische Anwendungen\jophya\src\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "D:\Uni\SS 20\Computerlinguistische Anwendungen\jophya\src\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Philip\AppData\Local\Programs\Python\Python36\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Philip\AppData\Local\Programs\Python\Python36\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Philip\AppData\Local\Programs\Python\Python36\lib\unittest\loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "D:\Uni\SS 20\Computerlinguistische Anwendungen\jophya\src\hw08_neural_networks\test_neural_network.py", line 2, in <module>
    from hw08_neural_networks import get_data, lstm, cnn
  File "D:\Uni\SS 20\Computerlinguistische Anwendungen\jophya\src\hw08_neural_networks\lstm.py", line 2, in <module>
    from keras.models import Sequential
  File "D:\Uni\SS 20\Computerlinguistische Anwendungen\jophya\src\venv\lib\site-packages\keras\__init__.py", line 6, in <module>
    'Keras requires TensorFlow 2.2 or higher. '
ImportError: Keras requires TensorFlow 2.2 or higher. Install TensorFlow via `pip install tensorflow`

Assertion failed

Assertion failed

Ran 1 test in 0.050s

FAILED (errors=1)

Process finished with exit code 1

Assertion failed

Assertion failed

Has anybody any advise?
Thank you in advance
**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by amitpsingh1** [comment]
Please close all sessions of Jupyter Notebook and relaunch. Try to import again as a first step and it should work fine.

**Comment by amahendrakar** [comment]
@adamczykp,
Please check [this comment](https://github.com/tensorflow/tensorflow/issues/36167#issuecomment-577886156) from a similar issue and let us know if it works. Thanks!
