### ISSUE TITLE
get error when runing python captcha_train.py

### ISSUE THREAD

**Issue by mahdieight** [tensorflow/tensorflow#41103]
hi
Time to run the following code : 
`python captcha_train.py`
im using the flow library:
https://github.com/PatrickLib/captcha_recognize
im installation : 

- python 2.7
- Anaconda2 4.3.1
- TensorFlow 1.1

get this erros :((

`Traceback (most recent call last):
  File "captcha_train.py", line 89, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "captcha_train.py", line 65, in main
    run_train()
  File "captcha_train.py", line 57, in run_train
    coord.join(threads)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/queue_runner_impl.py", line 234, in _run
    sess.run(enqueue_op)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 778, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 982, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1032, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1052, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: ./data/train.tfrecords
         [[Node: input/ReaderReadV2 = ReaderReadV2[_device="/job:localhost/replica:0/task:0/cpu:0"](input/TFRecordReaderV2, input/input_producer)]]`
`Caused by op u'input/ReaderReadV2', defined at:
  File "captcha_train.py", line 89, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "captcha_train.py", line 65, in main
    run_train()
  File "captcha_train.py", line 19, in run_train
    images, labels = captcha.inputs(train=True, batch_size=FLAGS.batch_size)
  File "/app/captcha/captcha_model.py", line 15, in inputs
    return captcha_input.inputs(train, batch_size=batch_size)
  File "/app/captcha/captcha_input.py", line 44, in inputs
    image, label = read_and_decode(filename_queue)
  File "/app/captcha/captcha_input.py", line 21, in read_and_decode
    _, serialized_example = reader.read(filename_queue)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/io_ops.py", line 193, in read
    return gen_io_ops._reader_read_v2(self._reader_ref, queue_ref, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_io_ops.py", line 411, in _reader_read_v2
    queue_handle=queue_handle, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2336, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1228, in init
    self._traceback = _extract_stack()`
`NotFoundError (see above for traceback): ./data/train.tfrecords
         [[Node: input/ReaderReadV2 = ReaderReadV2[_device="/job:localhost/replica:0/task:0/cpu:0"](input/TFRecordReaderV2, input/input_producer)]]
2020-07-02 07:33:55.821848: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2020-07-02 07:33:55.822614: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2020-07-02 07:33:55.823256: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2020-07-02 07:33:55.823711: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.`

please help me

**Comment by ravikyram** [comment]
TF 1.1 is very old version .Request you try with latest TF versions such as 1.15 or 2.3-rc0 and let me know if the issue still persists.
Please, provide the exact sequence of commands / steps that you executed before running into the problem.Thanks!
