### ISSUE TITLE
Error with instalation of Tensorflow

### ISSUE THREAD

**Issue by jbenes1** [tensorflow/tensorflow#41134]
**System information**
- OS Platform and Distribution : Ubuntu 20.04
- TensorFlow version: 1.15.0
- Python version: 3.7.0
- Installed using : pip
- CUDA/cuDNN version: None
- GPU model and memory: CPU

**Describe the problem**
   I am trying to install tensorflow via terminal in PyCharm, cant really use any other version of python or tensorflow cause my old  CPU. This is my last resort any newer version of tensorflow crashes immediately. 

**Provide the exact sequence of commands / steps that you executed before running into the problem**

        pip3 install tensorflow==1.15.0

**Any other info / logs**
 ```
pip3 install tensorflow==1.15.0
Defaulting to user installation because normal site-packages is not writeable
Collecting tensorflow==1.15.0
  Downloading tensorflow-1.15.0-cp37-cp37m-manylinux2010_x86_64.whl (412.3 MB)
     |████████████████████████████████| 412.3 MB 21 kB/s 
Collecting six>=1.10.0
  Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting wrapt>=1.11.1
  Downloading wrapt-1.12.1.tar.gz (27 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-v5_uvp33/wrapt/setup.py'"'"'; __file__='"'"'/tmp/pip-install-v5_uvp33/wrapt/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-gahhrkjb
         cwd: /tmp/pip-install-v5_uvp33/wrapt/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/local/lib/python3.7/site-packages/setuptools/__init__.py", line 23, in <module>
        from setuptools.dist import Distribution
      File "/usr/local/lib/python3.7/site-packages/setuptools/dist.py", line 34, in <module>
        from setuptools import windows_support
      File "/usr/local/lib/python3.7/site-packages/setuptools/windows_support.py", line 2, in <module>
        import ctypes
      File "/usr/local/lib/python3.7/ctypes/__init__.py", line 7, in <module>
        from _ctypes import Union, Structure, Array
    ModuleNotFoundError: No module named '_ctypes'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

```

**Comment by jbenes1** [comment]
So the problem is with the wrapt package, still dont know how to fix that.

**Comment by mihaimaruseac** [comment]
This is not a TF issue, recommend asking on StackOverflow.

You can try pinning down the dependency of `wrapt` you are installing (`pip install wrapt=... tensorflow=..`)
