### ISSUE TITLE
mlagents-learn is not responding: Please help me, am new on learn ml agents in unity

### ISSUE THREAD

**Issue by Kumah1** [tensorflow/tensorflow#41171]
(base) D:\PROGRAMMING\UNITY\AI\ml-agents-release_3>mlagent-learn
'mlagent-learn' is not recognized as an internal or external command,
operable program or batch file.

(base) D:\PROGRAMMING\UNITY\AI\ml-agents-release_3>conda activate unity_rl

(unity_rl) D:\PROGRAMMING\UNITY\AI\ml-agents-release_3>mlagents-learn
Traceback (most recent call last):
  File "C:\Users\Kumah\.conda\envs\unity_rl\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Kumah\.conda\envs\unity_rl\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Kumah\.conda\envs\unity_rl\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Kumah\.conda\envs\unity_rl\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Kumah\.conda\envs\unity_rl\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Kumah\.conda\envs\unity_rl\Scripts\mlagents-learn-script.py", line 33, in <module>
    sys.exit(load_entry_point('mlagents', 'console_scripts', 'mlagents-learn')())
  File "C:\Users\Kumah\.conda\envs\unity_rl\Scripts\mlagents-learn-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "C:\Users\Kumah\.conda\envs\unity_rl\lib\site-packages\importlib_metadata\__init__.py", line 105, in load
    module = import_module(match.group('module'))
  File "C:\Users\Kumah\.conda\envs\unity_rl\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "d:\programming\unity\ai\ml-agents-release_3\ml-agents\mlagents\trainers\learn.py", line 12, in <module>
    from mlagents import tf_utils
  File "d:\programming\unity\ai\ml-agents-release_3\ml-agents\mlagents\tf_utils\__init__.py", line 1, in <module>
    from mlagents.tf_utils.tf import tf as tf  # noqa
  File "d:\programming\unity\ai\ml-agents-release_3\ml-agents\mlagents\tf_utils\tf.py", line 3, in <module>
    import tensorflow as tf  # noqa I201
  File "C:\Users\Kumah\.conda\envs\unity_rl\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\Kumah\.conda\envs\unity_rl\lib\site-packages\tensorflow\python\__init__.py", line 50, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Kumah\.conda\envs\unity_rl\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 69, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Kumah\.conda\envs\unity_rl\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Kumah\.conda\envs\unity_rl\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Kumah\.conda\envs\unity_rl\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Kumah\.conda\envs\unity_rl\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Kumah\.conda\envs\unity_rl\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

(unity_rl) D:\PROGRAMMING\UNITY\AI\ml-agents-release_3>mlagent-learn
'mlagent-learn' is not recognized as an internal or external command,
operable program or batch file.

(unity_rl) D:\PROGRAMMING\UNITY\AI\ml-agents-release_3>

**Comment by Saduf2019** [comment]
@Kumah1 
Please check [this comment](https://github.com/tensorflow/tensorflow/issues/36167#issuecomment-577886156) thread from a similar issue and let us know if it helps. 

Please verify the below for this commonly occurring issue: 

What is make/model of your cpu?
I suspect your cpu model does not support AVX instructions sets.See [hardware requirements](https://www.tensorflow.org/install/pip?lang=python3#hardware-requirements)
Make sure to download the latest [microsoft visual c++ redistributable from here](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads).
.Also, please follow the instructions from to install from [Tensorflow website](https://www.tensorflow.org/install/source_windows).

Please, check Your CPU/Python is on 32 bits?Please, refer #36167 and see if it helps you.Please, refer similar issue #36167 #36151 #36138 #36054 #36045 #36020 #36003 #35988 #35903 #35880 #35865 #35805 #35789 #35773 #35772 #35767 #35766 #35749 #35721 #35618 #35204
Thanks!

**Comment by Kumah1** [comment]
It's because my CPU doesn't support avx.
Is there a way to train ml agents on my machine without avx?.

 Thank you very much

**Comment by Saduf2019** [comment]
@Kumah1 
Please refer to [this comment](https://github.com/tensorflow/tensorflow/issues/40978#issuecomment-652454678) to resolve your issue.
