### ISSUE TITLE
MLIR Converter crashes because "tf.DecodeJpeg is not an op"

### ISSUE THREAD

**Issue by rajansaini691** [tensorflow/tensorflow#41255]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04
- TensorFlow installed from (source or binary): Source
- TensorFlow version (or github SHA if from source): 2.4.0-dev20200709

**Command used to run the converter or code if you’re using the Python API**

```
# Convert to tflite
mkdir -p tflite
SAVED_MODEL_DIR="$REPO_PATH/tmp"
OUTPUT_DIR="$REPO_PATH/tflite"
python $TPU_REPO_PATH/models/official/detection/export_tflite_model.py \
  --saved_model_dir="${SAVED_MODEL_DIR?}" \
  --output_dir="${OUTPUT_DIR?}"
```

**The output from the converter invocation**

```
loc(callsite("DecodeJpeg"("/home/rsaini/.pyenv/versions/edge/lib/python3.7/site-packages/tensorflow/python/saved_model/loader_impl.py":299:0) at callsite("/home/rsaini/.pyenv/versions/edge/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py":324:0 at callsite("/home/rsaini/.pyenv/versions/edge/lib/python3.7/site-packages/tensorflow/lite/python/convert_saved_model.py":198:0 at callsite("/home/rsaini/.pyenv/versions/edge/lib/python3.7/site-packages/tensorflow/lite/python/lite.py":1923:0 at callsite("/home/rsaini/repos/applications/tpu/models/official/detection/export_tflite_model.py":35:0 at callsite("/home/rsaini/repos/applications/tpu/models/official/detection/export_tflite_model.py":49:0 at callsite("/home/rsaini/.pyenv/versions/edge/lib/python3.7/site-packages/absl/app.py":250:0 at callsite("/home/rsaini/.pyenv/versions/edge/lib/python3.7/site-packages/absl/app.py":299:0 at callsite("/home/rsaini/.pyenv/versions/edge/lib/python3.7/site-packages/tensorflow/python/platform/app.py":40:0 at "/home/rsaini/repos/applications/tpu/models/official/detection/export_tflite_model.py":55:0)))))))))): error: 'tf.DecodeJpeg' op is neither a custom op nor a flex op
error: failed while converting: 'main': Ops that need custom implementation (enabled via setting the -emit-custom-ops flag):
	tf.DecodeJpeg {acceptable_fraction = 1.000000e+00 : f32, channels = 0 : i64, dct_method = "", device = "", fancy_upscaling = true, ratio = 1 : i64, try_recover_truncated = false}
Traceback (most recent call last):
  File "/home/rsaini/.pyenv/versions/edge/lib/python3.7/site-packages/tensorflow/lite/python/convert.py", line 199, in toco_convert_protos
    enable_mlir_converter)
  File "/home/rsaini/.pyenv/versions/edge/lib/python3.7/site-packages/tensorflow/lite/python/wrap_toco.py", line 38, in wrapped_toco_convert
    enable_mlir_converter)
 %cst_9 = "std.constant"() {value = dense<"0x0000024200000242000002420000024200000242000002420000024200000242000002420000C1420200C1420100C1420000C1420000C1420000C142FEFFC0420000C1420000C142008020430180204300802043008020430080204300802043FF7F20430080204300802043008060430180604300806043008060430080604300806043FF7F604300806043008060430040904300409043004090430040904300409043004090430040904300409043004090430040B0430040B0430040B0430040B0430040B0430040B0430040B0430040B0430040B0430040D0430040D0430040D0430040D0430040D0430040D0430040D0430040D0430040D0430040F0430040F0430040F0430040F0430040F0430040F0430040F0430040F0430040F0430020084400200844002008440020084400200844002008440020084400200844002008440020184400201844002018440020184400201844002018440020184400201844002018440000024200000242000002420000024200000242000002420000024200000242000002420000C1420200C1420100C1420000C1420000C1420000C142FEFFC0420000C1420000C142008020430180204300802043008020430080204300802043FF7F20430080204300802043008060430180604300806043008060430080604300806043FF7F604300806043008060430040904300409043004090430040904300409043004090430040904300409043004090430040B0430040B0430040B0430040B0430040B0430040B0430040B0430040B0430040B0430040D0430040D0430040D0430040D0430040D0430040D0430040D0430040D0430040D0430040F0430040F0430040F0430040F0430040F0430040F0430040F0430040F0430040F0430020084400200844002008440020084400200844002008440020084400200844002008440020184400201844002018440020184400201844002018440020184400201844002018440000024200000242000002420000024200000242000002420000024200000242000002420000C1420200C1420100C1420000C1420000C1420000C142FEFFC0420000C1420000C142008020430180204300802043008020430080204300802043FF7F20430080204300802043008060430180604300806043008060430080604300806043FF7F604300806043008060430040904300409043004090430040904300409043004090430040904300409043004090430040B0430040B0430040B0430040B0430040B0430040B0430040B0430040B0430040B0430040D0430040D0430040D0430040D0430040D0430040D0430040D0430040D0430040D0430040F0430040F0430040F0430040F0430040F0430040F0430040F0430040F0430040F0430020084400200844002008440020084400200844002008440020084400200844002008440020184400201844002018440020184400201844002018440020184400201844002018440000024200000242000002420000024200000242000002420000024200000242000002420000C1420200C1420100C1420000C1420000C1420000C142FEFFC0420000C1420000C142008020430180204300802043008020430080204300802043FF7F20430080204300802043008060430180604300806043008060430080604300806043FF7F604300806043008060430040904300409043004090430040904300409043004090430040904300409043004090430040B0430040B0430040B0430040B0430040B0430040B0430040B0430040B0430040B0430040D0430040D0430040D0430040D0430040D0430040D0430040D0430040D0430040D0430040F0430040F0430040F0430040F0430040F0430040F0430040F0430040F0430040F0430020084400200844002008440020084400200844002008440020084400200844002008440020184400201844002018440020184400201844002018440020184400201844002018440000024200000242000002420000024200000242000002420000024200000242000002420000C1420200C1420100C1420000C1420000C1420000C142FEFFC0420000C1420000C142008020430180204300802043008020430080204300802043FF7F20430080204300802043008060430180604300806043008060430080604300806043FF7F604300806043008060430040904300409043004090430040904300409043004090430040904300409043004090430040B0430040B0430040B0430040B0430040B0430040B0430040B0430040B0430040B0430040D0430040D0430040D0430040D0430040D0430040D0430040D0430040D0430040D0430040F0430040F0430040F0430040F0430040F0430040F0430040F0430040F0430040F0430020084400200844002008440020084400200844002008440020084400200844002008440020184400201844002018440020184400201844002018440020184400201844002018440000024200000242000002420000024200000242000002420000024200000242000002420000C1420200C1420100C1420000C1420000C1420000C142FEFFC0420000C1420000C142008020430180204300802043008020430080204300802043FF7F20430080204300802043008060430180604300806043008060430080604300806043FF7F604300806043008060430040904300409043004090430040904300409043004090430040904300409043004090430040B0430040B0430040B0430040B0430040B0430040B0430040B0430040B0430040B0430040D0430040D0430040D0430040D0430040D0430040D0430040D0430040D0430040D0430040F0430040F0430040F0430040F0430040F0430040F0430040F0430040F0430040F0430020084400200844002008440020084400200844002008440020084400200844002008440020184400201844002018440020184400201844002018440020184400201844002018440000024200000242000002420000024200000242000002420000024200000242000002420000C1420200C1420100C1420000C1420000C1420000C142FEFFC0420000C1420000C142008020430180204300802043008020430080204300802043FF7F20430080204300802043008060430180604300806043008060430080604300806043FF7F604300806043008060430040904300409043004090430040904300409043004090430040904300409043004090430040B0430040B0430040B0430040B0430040B0430040B0430040B0430040B0430040B0430040D0430040D0430040D0430040D0430040D0430040D0430040D0430040D0430040D0430040F0430040F0430040F0430040F0430040F0430040F0430040F0430040F0430040F0430020084400200844002008440020084400200844002008440020084400200844002008440020184400201844002018440020184400201844002018440020184400201844002018440000024200000242000002420000024200000242000002420000024200000242000002420000C1420200C1420100C1420000C1420000C1420000C142FEFFC0420000C1420000C142008020430180204300802043008020430080204300802043FF7F20430080204300802043008060430180604300806043008060430080604300806043FF7F604300806043008060430040904300409043004090430040904300409043004090430040904300409043004090430040B0430040B0430040B0430040B0430040B0430040B0430040B0430040B0430040B0430040D0430040D0430040D0430040D0430040D0430040D0430040D0430040D0430040D0430040F0430040F0430040F0430040F0430040F0430040F0430040F0430040F0430040F0430020084400200844002008440020084400200844002008440020084400200844002008440020184400201844002018440020184400201844002018440020184400201844002018440000024200000242000002420000024200000242000002420000024200000242000002420000C1420200C1420100C1420000C1420000C1420000C142FEFFC0420000C1420000C142008020430180204300802043008020430080204300802043FF7F20430080204300802043008060430180604300806043008060430080604300806043FF7F604300806043008060430040904300409043004090430040904300409043004090430040904300409043004090430040B0430040B0430040B0430040B0430040B0430040B0430040B0430040B0430040B0430040D0430040D0430040D0430040D0430040D0430040D0430040D0430040D0430040D0430040F0430040F0430040F0430040F0430040F0430040F0430040F0430040F0430040F0430020084400200844002008440020084400200844002008440020084400200844002008440020184400201844002018440020184400201844002018440020184400201844002018440000024200000242000002420000024200000242000002420000024200000242000002420000C1420200C1420100C1420000C1420000C1420000C142FEFFC0420000C1420000C142008020430180204300802043008020430080204300802043FF7F20430080204300802043008060430180604300806043008060430080604300806043FF7F604300806043008060430040904300409043004090430040904300409043004090430040904300409043004090430040B0430040B0430040B0430040B0430040B0430040B0430040B0430040B0430040B0430040D0430040D0430040D0430040D0430040D0430040D0430040D0430040D0430040D0430040F0430040F0430040F0430040F0430040F0430040F0430040F0430040F0430040F043002008440020084400200844002008440020084400200844002008440020084400200844002018440020184400201844002018440020184400201844002018440020184400201844
```

Note: The output was an endless string of random hex characters. Unfortunately, I missed the last few stack frames as I was unable to perfectly time pausing the process (the hex characters filled the terminal's buffer more quickly than I could react :) ). 

**Also, please include a link to the saved model or GraphDef**
[model.zip](https://github.com/tensorflow/tensorflow/files/4900048/model.zip)

**Failure details**

No model is produced

**Comment by bhack** [comment]
Is this a dup of https://github.com/tensorflow/tensorflow/issues/40370?

**Comment by thaink** [comment]
Right. This is duplicated. Please see the discussion in #40370
