### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow.python.util'

### ISSUE THREAD

**Issue by 1340896123** [tensorflow/tensorflow#41375]
import tensorflow as tf
2020-07-14 21:15:42.824490: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-07-14 21:15:42.827687: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\廖宇杰\AppData\Roaming\Python\Python37\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\廖宇杰\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\__init__.py", line 64, in <module>
    from tensorflow.python.framework.framework_lib import *  # pylint: disable=redefined-builtin
  File "C:\Users\廖宇杰\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\framework\framework_lib.py", line 24, in <module>
    from tensorflow.python.framework.device import DeviceSpec
  File "C:\Users\廖宇杰\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\framework\device.py", line 24, in <module>
    from tensorflow.python.framework import device_spec
  File "C:\Users\廖宇杰\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\framework\device_spec.py", line 21, in <module>
    from tensorflow.python.util.tf_export import tf_export
ModuleNotFoundError: No module named 'tensorflow.python.util'

**Comment by gowthamkpr** [comment]
@1340896123 I think pip is installing it for python 2 and then you are running in python 3. Use pip3 while installing tensorflow.

Also, if the above solution doesn't work, Please go through these [solutions](https://stackoverflow.com/questions/41415629/importerror-no-module-named-tensorflow-python)
