### ISSUE TITLE
2020-07-14 nightlies cannot import `tensorflow`

### ISSUE THREAD

**Issue by wchargin** [tensorflow/tensorflow#41388]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): gLinux (like Debian)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version: pip install tf-nightly==2.4.0.dev20200714
- Python version: Python 3.7.7
- Installed using virtualenv? pip? conda?: virtualenv
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the problem**

`import tensorflow` fails.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

```
$ cd "$(mktemp -d)"
$ virtualenv -q -p python3.7 ./ve
$ . ./ve/bin/activate
(ve) $ pip install tf-nightly
Collecting tf-nightly
  Using cached tf_nightly-2.4.0.dev20200714-cp37-cp37m-manylinux2010_x86_64.whl (142.9 MB)
Requirement already satisfied: six>=1.12.0 in ./ve/lib/python3.7/site-packages (from tf-nightly) (1.14.0)
Collecting h5py<2.11.0,>=2.10.0
  Using cached h5py-2.10.0-cp37-cp37m-manylinux1_x86_64.whl (2.9 MB)
Processing /HOMEDIR/.cache/pip/wheels/3f/e3/ec/8a8336ff196023622fbcb36de0c5a5c218cbb24111d1d4c7f2/termcolor-1.1.0-py3-none-any.whl
Collecting google-pasta>=0.1.8
  Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
Requirement already satisfied: wheel>=0.26 in ./ve/lib/python3.7/site-packages (from tf-nightly) (0.34.2)
Collecting grpcio>=1.8.6
  Using cached grpcio-1.30.0-cp37-cp37m-manylinux2010_x86_64.whl (3.0 MB)
Collecting gast==0.3.3
  Using cached gast-0.3.3-py2.py3-none-any.whl (9.7 kB)
Collecting tf-estimator-nightly
  Using cached tf_estimator_nightly-2.4.0.dev2020071401-py2.py3-none-any.whl (459 kB)
Collecting opt-einsum>=2.3.2
  Using cached opt_einsum-3.2.1-py3-none-any.whl (63 kB)
Collecting tb-nightly<2.4.0a0,>=2.3.0a0
  Using cached tb_nightly-2.3.0a20200713-py3-none-any.whl (6.8 MB)
Collecting protobuf>=3.9.2
  Using cached protobuf-3.12.2-cp37-cp37m-manylinux1_x86_64.whl (1.3 MB)
Processing /HOMEDIR/.cache/pip/wheels/62/76/4c/aa25851149f3f6d9785f6c869387ad82b3fd37582fa8147ac6/wrapt-1.12.1-cp37-cp37m-linux_x86_64.whl
Collecting keras-preprocessing<1.2,>=1.1.1
  Using cached Keras_Preprocessing-1.1.2-py2.py3-none-any.whl (42 kB)
Processing /HOMEDIR/.cache/pip/wheels/cc/af/1a/498a24d0730ef484019e007bb9e8cef3ac00311a672c049a3e/absl_py-0.9.0-py3-none-any.whl
Collecting numpy<1.19.0,>=1.16.0
  Using cached numpy-1.18.5-cp37-cp37m-manylinux1_x86_64.whl (20.1 MB)
Collecting astunparse==1.6.3
  Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
Collecting werkzeug>=0.11.15
  Using cached Werkzeug-1.0.1-py2.py3-none-any.whl (298 kB)
Collecting tensorboard-plugin-wit>=1.6.0
  Using cached tensorboard_plugin_wit-1.7.0-py3-none-any.whl (779 kB)
Requirement already satisfied: setuptools>=41.0.0 in ./ve/lib/python3.7/site-packages (from tb-nightly<2.4.0a0,>=2.3.0a0->tf-nightly) (44.0.0)
Collecting google-auth<2,>=1.6.3
  Using cached google_auth-1.19.0-py2.py3-none-any.whl (91 kB)
Collecting google-auth-oauthlib<0.5,>=0.4.1
  Using cached google_auth_oauthlib-0.4.1-py2.py3-none-any.whl (18 kB)
Requirement already satisfied: requests<3,>=2.21.0 in ./ve/lib/python3.7/site-packages (from tb-nightly<2.4.0a0,>=2.3.0a0->tf-nightly) (2.23.0)
Collecting markdown>=2.6.8
  Using cached Markdown-3.2.2-py3-none-any.whl (88 kB)
Collecting cachetools<5.0,>=2.0.0
  Using cached cachetools-4.1.1-py3-none-any.whl (10 kB)
Collecting rsa<5,>=3.1.4; python_version >= "3"
  Using cached rsa-4.6-py3-none-any.whl (47 kB)
Collecting pyasn1-modules>=0.2.1
  Using cached pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)
Collecting requests-oauthlib>=0.7.0
  Using cached requests_oauthlib-1.3.0-py2.py3-none-any.whl (23 kB)
Collecting importlib-metadata; python_version < "3.8"
  Using cached importlib_metadata-1.7.0-py2.py3-none-any.whl (31 kB)
Collecting pyasn1>=0.1.3
  Using cached pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
Collecting oauthlib>=3.0.0
  Using cached oauthlib-3.1.0-py2.py3-none-any.whl (147 kB)
Collecting zipp>=0.5
  Using cached zipp-3.1.0-py3-none-any.whl (4.9 kB)
Installing collected packages: numpy, h5py, termcolor, google-pasta, grpcio, gast, tf-estimator-nightly, opt-einsum, werkzeug, tensorboard-plugin-wit, absl-py, cachetools, pyasn1, rsa, pyasn1-modules, google-auth, protobuf, oauthlib, requests-oauthlib, google-auth-oauthlib, zipp, importlib-metadata, markdown, tb-nightly, wrapt, keras-preprocessing, astunparse, tf-nightly
Successfully installed absl-py-0.9.0 astunparse-1.6.3 cachetools-4.1.1 gast-0.3.3 google-auth-1.19.0 google-auth-oauthlib-0.4.1 google-pasta-0.2.0 grpcio-1.30.0 h5py-2.10.0 importlib-metadata-1.7.0 keras-preprocessing-1.1.2 markdown-3.2.2 numpy-1.18.5 oauthlib-3.1.0 opt-einsum-3.2.1 protobuf-3.12.2 pyasn1-0.4.8 pyasn1-modules-0.2.8 requests-oauthlib-1.3.0 rsa-4.6 tb-nightly-2.3.0a20200713 tensorboard-plugin-wit-1.7.0 termcolor-1.1.0 tf-estimator-nightly-2.4.0.dev2020071401 tf-nightly-2.4.0.dev20200714 werkzeug-1.0.1 wrapt-1.12.1 zipp-3.1.0
(ve) $ python -c 'import tensorflow'
Traceback (most recent call last):
  File "/tmp/tmp.VuldV9r4ny/ve/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: libcudart.so.10.1: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/tmp.VuldV9r4ny/ve/lib/python3.7/site-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/tmp/tmp.VuldV9r4ny/ve/lib/python3.7/site-packages/tensorflow/python/__init__.py", line 40, in <module>
    from tensorflow.python.eager import context
  File "/tmp/tmp.VuldV9r4ny/ve/lib/python3.7/site-packages/tensorflow/python/eager/context.py", line 35, in <module>
    from tensorflow.python import pywrap_tfe
  File "/tmp/tmp.VuldV9r4ny/ve/lib/python3.7/site-packages/tensorflow/python/pywrap_tfe.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/tmp/tmp.VuldV9r4ny/ve/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 83, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/tmp/tmp.VuldV9r4ny/ve/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: libcudart.so.10.1: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
(ve) $ 
```

**Any other info / logs**

Nope.

**Comment by tgaddair** [comment]
I'm seeing the same error, seems `tf-nightly` is requiring GPU support.

Looks like there were some changes to nightly release scripts yesterday that may have something to do with this: https://github.com/tensorflow/tensorflow/commit/4e7eb7f5ab6fb39b0804539f960c8bad12d7d106.

**Comment by av8ramit** [comment]
Sorry for the breakage. I've deleted 07/14 builds across all packages and will roll back the config changes.

**Comment by av8ramit** [comment]
We normally have a smoke test that is run before we upload. For some reason I'm unable to repro this breakage:

```
$ python --version
Python 3.7.7
(venv37) $ python
Python 3.7.7 (default, Mar 10 2020, 17:25:08) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> tf.__version__
'2.4.0-dev20200714'
>>> from tensorflow.python._pywrap_tensorflow_internal import *
>>>
```

If you have some repro steps please let me know.

**Comment by tgaddair** [comment]
Hey @av8ramit, is it possible that your machine has CUDA available?  In my case, we were using a Docker image derived from `ubuntu:18.04`, just ran `pip install tf-nightly`, and `python -c import tensorflow` would reveal the error.

**Comment by av8ramit** [comment]
@tgaddair yes my machine had CUDA available. Is there any way it would be possible for you to test a new tf-nightly image in your environment from this [link](https://storage.googleapis.com/tensorflow-nightly/prod/tensorflow/release/ubuntu_16/gpu_py36_full/nightly_release/331/20200715-134916/github/tensorflow/pip_pkg/tf_nightly-2.4.0.dev20200715-cp36-cp36m-manylinux2010_x86_64.whl)?

I've renovated the release config but haven't published it out of fear that this bug still exists.  This is a Python3.6 version, but if you can confirm installing this whl works for you I can push the updates to pypi.

**Comment by av8ramit** [comment]
I was able to repro and can confirm the new config fixes the issue.

**Comment by wchargin** [comment]
@av8ramit: Nightlies from yesterday and today work fine on my machine,
but from your comment it sounds like we’re not sure whether everything’s
fixed yet. Should I hold off on unpinning our CI (i.e., reverting
<https://github.com/tensorflow/tensorboard/pull/3839>)?

**Comment by wchargin** [comment]
Ah, race condition. :-) Sounds good, thanks!

**Comment by av8ramit** [comment]
So I had reverted my config change on 07/14, so if you want to be safe it may be worth pinning to 07/15 or trying this [custom whl](https://storage.googleapis.com/tensorflow-nightly/prod/tensorflow/release/ubuntu_16/gpu_py36_full/nightly_release/331/20200715-134916/github/tensorflow/pip_pkg/tf_nightly-2.4.0.dev20200715-cp36-cp36m-manylinux2010_x86_64.whl) (it was not uploaded to pypi) I've created with my config change and fix to the cuda issue. I've resubmitted my config change today after testing.

**Comment by manivaradarajan** [comment]
Looks like we can close this?

**Comment by tgaddair** [comment]
Yes, this is working again in latest nightlies.
