### ISSUE TITLE
TypeError: Unsupported return value from function passed to Dataset.map(): OrderedDict in TFF (multiple feature inputs)

### ISSUE THREAD

**Issue by ymsaputra** [tensorflow/tensorflow#41440]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Red Hat 7.7
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): TF 2.2
- Python version: 3.7

For high-level discussions about TensorFlow, please post to discuss@tensorflow.org, for questions about the development or internal workings of TensorFlow, or if you would like to know how to contribute to TensorFlow, please post to developers@tensorflow.org.

I use TFF and want to create an element_spec as follows:
```
OrderedDict([('x', OrderedDict([
('a', TensorSpec(shape=(None,), dtype=tf.int64, name=None)), 
('b', TensorSpec(shape=(None,), dtype=tf.int64, name=None)), 
('c', TensorSpec(shape=(None,), dtype=tf.int64, name=None)), 
('d', TensorSpec(shape=(None,), dtype=tf.int64, name=None)), 
('e', TensorSpec(shape=(None,), dtype=tf.int64, name=None)), 
('f', TensorSpec(shape=(None,), dtype=tf.int64, name=None)), 
('g', TensorSpec(shape=(None,), dtype=tf.int64, name=None))])), 
('y', TensorSpec(shape=(None,), dtype=tf.int64, name=None))])
```
To this end, I create a preprocess function below:
```
def preprocess(dataset):

  def batch_format_fn(self):

    return collections.OrderedDict(
        x=collections.OrderedDict(
	    a=tf.TensorSpec(shape=[None,], dtype=tf.int64),
	    b=tf.TensorSpec(shape=[None,], dtype=tf.int64),
            c=tf.TensorSpec(shape=[None,], dtype=tf.int64),
            d=tf.TensorSpec(shape=[None,], dtype=tf.int64),
            e=tf.TensorSpec(shape=[None,], dtype=tf.int64),
            f=tf.TensorSpec(shape=[None,], dtype=tf.int64)),
        y=tf.TensorSpec(shape=[None,], dtype=tf.int64))
  
  return dataset.repeat(NUM_EPOCHS).shuffle(SHUFFLE_BUFFER).batch(BATCH_SIZE).map(batch_format_fn)
```
And I call this function as follows:
```
sample_dataset = train_dataset.create_tf_dataset_for_client(train_dataset.client_ids[0])
preprocessed_sample_dataset = preprocess(sample_dataset)
```

However, when I run the program, it gives me an error:
```
Traceback (most recent call last):
  File "/home/anaconda3/envs/env1_TF2.1/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 3171, in _wrapper_helper
    self._output_structure = structure.type_spec_from_value(ret)
  File "/home/anaconda3/envs/env1_TF2.1/lib/python3.7/site-packages/tensorflow/python/data/util/structure.py", line 439, in type_spec_from_value
    return ctor([(k, type_spec_from_value(v)) for k, v in element.items()])
  File "/home/anaconda3/envs/env1_TF2.1/lib/python3.7/site-packages/tensorflow/python/data/util/structure.py", line 439, in <listcomp>
    return ctor([(k, type_spec_from_value(v)) for k, v in element.items()])
  File "/home/anaconda3/envs/env1_TF2.1/lib/python3.7/site-packages/tensorflow/python/data/util/structure.py", line 439, in type_spec_from_value
    return ctor([(k, type_spec_from_value(v)) for k, v in element.items()])
  File "/home/anaconda3/envs/env1_TF2.1/lib/python3.7/site-packages/tensorflow/python/data/util/structure.py", line 439, in <listcomp>
    return ctor([(k, type_spec_from_value(v)) for k, v in element.items()])
  File "/home/anaconda3/envs/env1_TF2.1/lib/python3.7/site-packages/tensorflow/python/data/util/structure.py", line 466, in type_spec_from_value
    (element, type(element).__name__))
TypeError: Could not build a TypeSpec for TensorSpec(shape=(None,), dtype=tf.int64, name=None) with type TensorSpec

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "accident_modify_uk_final3b.py", line 269, in <module>
    preprocessed_sample_dataset = preprocess(sample_dataset)
  File "accident_modify_uk_final3b.py", line 267, in preprocess
    return dataset.repeat(NUM_EPOCHS).shuffle(SHUFFLE_BUFFER).batch(BATCH_SIZE).map(batch_format_fn)
  File "/home/anaconda3/envs/env1_TF2.1/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1621, in map
    return MapDataset(self, map_func, preserve_cardinality=True)
  File "/homeanaconda3/envs/env1_TF2.1/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 3981, in __init__
    use_legacy_function=use_legacy_function)
  File "/home/anaconda3/envs/env1_TF2.1/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 3221, in __init__
    self._function = wrapper_fn.get_concrete_function()
  File "/homeanaconda3/envs/env1_TF2.1/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2532, in get_concrete_function
    *args, **kwargs)
  File "/home/anaconda3/envs/env1_TF2.1/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2496, in _get_concrete_function_garbage_collected
    graph_function, args, kwargs = self._maybe_define_function(args, kwargs)
  File "/home/anaconda3/envs/env1_TF2.1/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2777, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/home/anaconda3/envs/env1_TF2.1/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2667, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/home/anaconda3/envs/env1_TF2.1/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 981, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/anaconda3/envs/env1_TF2.1/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 3214, in wrapper_fn
    ret = _wrapper_helper(*args)
  File "/home/anaconda3/envs/env1_TF2.1/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 3177, in _wrapper_helper
    sys.exc_info()[2])
  File "/home/anaconda3/envs/env1_TF2.1/lib/python3.7/site-packages/six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "/home/anaconda3/envs/env1_TF2.1/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 3171, in _wrapper_helper
    self._output_structure = structure.type_spec_from_value(ret)
  File "/home/anaconda3/envs/env1_TF2.1/lib/python3.7/site-packages/tensorflow/python/data/util/structure.py", line 439, in type_spec_from_value
    return ctor([(k, type_spec_from_value(v)) for k, v in element.items()])
  File "/home/anaconda3/envs/env1_TF2.1/lib/python3.7/site-packages/tensorflow/python/data/util/structure.py", line 439, in <listcomp>
    return ctor([(k, type_spec_from_value(v)) for k, v in element.items()])
  File "/home/anaconda3/envs/env1_TF2.1/lib/python3.7/site-packages/tensorflow/python/data/util/structure.py", line 439, in type_spec_from_value
    return ctor([(k, type_spec_from_value(v)) for k, v in element.items()])
  File "/home/anaconda3/envs/env1_TF2.1/lib/python3.7/site-packages/tensorflow/python/data/util/structure.py", line 439, in <listcomp>
    return ctor([(k, type_spec_from_value(v)) for k, v in element.items()])
  File "/home/anaconda3/envs/env1_TF2.1/lib/python3.7/site-packages/tensorflow/python/data/util/structure.py", line 466, in type_spec_from_value
    (element, type(element).__name__))
TypeError: Unsupported return value from function passed to Dataset.map(): OrderedDict([('x', OrderedDict([('a', TensorSpec(shape=(None,), dtype=tf.int64, name=None)), ('b', TensorSpec(shape=(None,), dtype=tf.int64, name=None)), ('c', TensorSpec(shape=(None,), dtype=tf.int64, name=None)), ('d', TensorSpec(shape=(None,), dtype=tf.int64, name=None)), ('e', TensorSpec(shape=(None,), dtype=tf.int64, name=None)), ('f', TensorSpec(shape=(None,), dtype=tf.int64, name=None))])), ('y', TensorSpec(shape=(None,), dtype=tf.int64, name=None))]).
(env1_TF2.1) [@phoenix9 accidents UK]$ 
```
What is wrong inside the preprocess function()?

**Comment by ravikyram** [comment]
@ymsaputra 

Request you to fill[ issue template.](https://github.com/tensorflow/tensorflow/issues/new/choose)

Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version.

Request you to share colab link or simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by ymsaputra** [comment]
I have updated the platform information. I think the problem happens when calling dataset.map(batch_format_fn) using that OrderedDict return.

**Comment by ymsaputra** [comment]
I got this answer here: https://stackoverflow.com/questions/62893523/how-to-build-a-model-using-multiple-features-in-tensorflow-federated
