### ISSUE TITLE
I'm trying to convert a custom model on inception V3 + SSD and running into the same issue. Any workarounds to get the model to tflite format until this is officially fixed?

### ISSUE THREAD

**Issue by IvanChavR** [tensorflow/tensorflow#41455]
I'm trying to convert a custom model on inception V3 + SSD and running into the same issue. Any workarounds to get the model to tflite format until this is officially fixed?

_Originally posted by @divSivasankaran in https://github.com/tensorflow/tensorflow/issues/18731#issuecomment-398985955_

Has someone resolved this issue?, I want to convert ssd_inception_v2_coco and  throws  the OperatorType::kMerge Found StridedSlice as non-selected output from Switch, but only Merge supported.

**Comment by abattery** [comment]
The original issue is a too old issue. We have changed our converter's gear from TOCO to MLIR converter. Could you try the conversion again with the recent version? 

Before trying conversion, you need to create a model in Python after inserting the code at the beginning in order to upgrade legacy Switch and Merge nodes to V2 control flow ops.
tf.compat.v1.enable_control_flow_v2()
https://www.tensorflow.org/api_docs/python/tf/compat/v1/enable_control_flow_v2

Or you can find alternatives in the here as well:
https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md
https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf1_detection_zoo.md

Some of the above model zip file links contain the converted tflite files.

**Comment by ravikyram** [comment]
@IvanChavR 

Can you please confirm if @abattery's workaround is working for you.Thanks!

**Comment by IvanChavR** [comment]
Hi, I have just used these sentences wit TF 2:

`input_arrays = ["image_tensor"]
output_arrays = ["detection_classes","detection_boxes","detection_scores", "num_detections"]
converter = tf.compat.v1.lite.TFLiteConverter.from_frozen_graph(PATH_TO_FROZEN_GRAPH, input_arrays,output_arrays, 
                                                                                                        input_shapes={"image_tensor":[1,300,300,3]})
    
tf.compat.v1.enable_control_flow_v2()
converter.experimental_new_converter = True
#converter.post_training_quantize = True
#converter.allow_custom_ops=True
tflite_model = converter.convert()
open("converted_model.tflite", "wb").write(tflite_model)`

And the result is the next:

> Traceback (most recent call last):
  File "convertion_resnet.py", line 80, in <module>
    convertv2()
  File "convertion_resnet.py", line 75, in convertv2
    tflite_model = converter.convert()
  File "/home/ivan/anaconda3/envs/tensor2/lib/python3.6/site-packages/tensorflow/lite/python/lite.py", line 1084, in convert
    **converter_kwargs)
  File "/home/ivan/anaconda3/envs/tensor2/lib/python3.6/site-packages/tensorflow/lite/python/convert.py", line 496, in toco_convert_impl
    enable_mlir_converter=enable_mlir_converter)
  File "/home/ivan/anaconda3/envs/tensor2/lib/python3.6/site-packages/tensorflow/lite/python/convert.py", line 227, in toco_convert_protos
    raise ConverterError("See console for info.\n%s\n%s\n" % (stdout, stderr))
tensorflow.lite.python.convert.ConverterError: See console for info.
2020-07-25 10:21:33.757076: W tensorflow/compiler/mlir/lite/python/graphdef_to_tfl_flatbuffer.cc:144] Ignored output_format.
2020-07-25 10:21:33.757102: W tensorflow/compiler/mlir/lite/python/graphdef_to_tfl_flatbuffer.cc:147] Ignored drop_control_dependency.
Traceback (most recent call last):
  File "/home/ivan/anaconda3/envs/tensor2/bin/toco_from_protos", line 11, in <module>
    sys.exit(main())
  File "/home/ivan/anaconda3/envs/tensor2/lib/python3.6/site-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 93, in main
    app.run(main=execute, argv=[sys.argv[0]] + unparsed)
  File "/home/ivan/anaconda3/envs/tensor2/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/ivan/anaconda3/envs/tensor2/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/ivan/anaconda3/envs/tensor2/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/home/ivan/anaconda3/envs/tensor2/lib/python3.6/site-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 56, in execute
    enable_mlir_converter)
Exception: Merge of two inputs that differ on more than one predicate {s(Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/Greater:0,else), s(Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/cond/cond/pred_id/_304__cf__307:0,then), s(Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/cond/Greater/_303__cf__306:0,then)} and {s(Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/Greater:0,else), s(Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/cond/cond/pred_id/_304__cf__307:0,else), s(Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/cond/Greater/_303__cf__306:0,else)}
	for node {{node Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/cond/cond/Merge}}

**Comment by sachinprasadhs** [comment]
Hi, Is this still an issue? Could you please try in the latest Tensorflow Version and let us know. Thanks
