### ISSUE TITLE
InvalidArgumentError: Only ranks up to 5 supported

### ISSUE THREAD

**Issue by danielfllaneza** [tensorflow/tensorflow#41452]
Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS inux release 7.6.1810
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
TensorFlow installed from (source or binary): binary
TensorFlow version (use command below): 1.14.0
Python version: 3.7.6
Bazel version (if compiling from source):
GCC/Compiler version (if compiling from source):
CUDA/cuDNN version: V9.1.85
GPU model and memory: Tesla K80 24C

I am working with Keras to build the following (simplified) model:
```
class MyModel():
   def __init__(self):
       pass
   
   def build_model(self):
       inp = Input(shape = self.outputs.shape)
        
       x = Dense(128, activation = 'elu')(inp) # We'll start exploring with one hidden layer
       outp = Dense(1, activation = 'elu')(x)
        
       self.model = Model(inputs = inp, outputs = outp)

       self.model.compile(loss = dice_loss,
                            optimizer = Adam(),
                            metrics = [dice_coef])

   def run_model(self):
      # For the sake of simplicity
      self.outputs = np.random.rand(8,64,12,86,98,1)      

      # labels shape = (64, 12, 86, 98) to get (1,64,12,86,98)
      self.labels = np.expand_dims(self.labels, axis = (0,-1))
      # outputs shape (8,64,12,86,98,1) to -> (1,64,12,86,98,8)
      self.outputs = np.swapaxes(self.outputs, 0,-1)
      
      self.build_model()

      self.model.fit([self.outputs, self.labels],
                                batch_size = 1,
                                epochs = 200)
```
However, upon trying to fit the model, as:
```
model = MyModel()
model.run_model()
```
The following error appears:
```
  File "/home/kdqm927/miniconda3/envs/segment/lib/python3.7/site-packages/tensorflow/python/keras/engine/training_v1.py", line 785, in fit
    use_multiprocessing=use_multiprocessing)
  File "/home/kdqm927/miniconda3/envs/segment/lib/python3.7/site-packages/tensorflow/python/keras/engine/training_arrays.py", line 634, in fit
    shuffle=shuffle)
  File "/home/kdqm927/miniconda3/envs/segment/lib/python3.7/site-packages/tensorflow/python/keras/engine/training_v1.py", line 2308, in _standardize_user_data
    batch_size=batch_size)
  File "/home/kdqm927/miniconda3/envs/segment/lib/python3.7/site-packages/tensorflow/python/keras/engine/training_v1.py", line 2335, in _standardize_tensors
    exception_prefix='input')
  File "/home/kdqm927/miniconda3/envs/segment/lib/python3.7/site-packages/tensorflow/python/keras/engine/training_utils.py", line 573, in standardize_input_data
    'with shape ' + str(data_shape))
ValueError: Error when checking input: expected input_1 to have 7 dimensions, but got array with shape (1, 64, 12, 86, 98, 8)
```
If I tweak the code by adding another dimension to self.outputs, following the exception from the previous error:
```
self.model.fit([np.expand_dims(self.outputs, axis = 0), self.labels],
                                batch_size = 1,
                                epochs = 200)
```
The error I get is: 
```
Traceback (most recent call last):
  File "./file.py", line 257, in <module>
    s.fit_metamodel('outputs_validation_arr')
  File "./file.py", line 157, in fit_metamodel
    callbacks = callbacks)
  File "/home/.../miniconda3/envs/segment/lib/python3.7/site-packages/tensorflow/python/keras/engine/training_v1.py", line 785, in fit
    use_multiprocessing=use_multiprocessing)
  File "/home/.../miniconda3/envs/segment/lib/python3.7/site-packages/tensorflow/python/keras/engine/training_arrays.py", line 666, in fit
    steps_name='steps_per_epoch')
  File "/home/.../miniconda3/envs/segment/lib/python3.7/site-packages/tensorflow/python/keras/engine/training_arrays.py", line 386, in model_iteration
    batch_outs = f(ins_batch)
  File "/home/.../miniconda3/envs/segment/lib/python3.7/site-packages/tensorflow/python/keras/backend.py", line 3632, in __call__
    run_metadata=self.run_metadata)
  File "/home/.../miniconda3/envs/segment/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1472, in __call__
    run_metadata_ptr)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Only ranks up to 5 supported: [1,1,64,12,86,98,128]
	 [[{{node dense/BiasAdd}}]]
```
**EDIT**
TensorFlow version (use command below): 2.2.0
****

**Comment by Saduf2019** [comment]
@danielfllaneza 
I ran the code shared by you, itseems incomplete, please find the error faced in [gist here](https://colab.research.google.com/gist/Saduf2019/756f1fd9af25d0aa7a1994bad8e34818/untitled282.ipynb).

Meanwhile as suggested in the [link](https://github.com/keras-team/keras/issues/10053#issuecomment-424091976) can you try to reshape
[link](https://stackoverflow.com/questions/41563720/error-when-checking-model-input-expected-convolution2d-input-1-to-have-4-dimens) [link1](https://datascience.stackexchange.com/questions/55975/valueerror-error-when-checking-input-expected-input-1-to-have-4-dimensions-bu) [link2](https://github.com/tensorflow/tensorflow/issues/33074#issuecomment-541574596)

**Comment by danielfllaneza** [comment]
Oh, I forgot mocking labels, for the sake of simplicity we can create self.labels too, so the code would be:
```
class Model():
   def __init__(self):
       pass
   
   def build_model(self):
       inp = Input(shape = self.outputs.shape)
        
       x = Dense(128, activation = 'elu')(inp) # We'll start exploring with one hidden layer
       outp = Dense(1, activation = 'elu')(x)
        
       self.model = Model(inputs = inp, outputs = outp)

       self.model.compile(loss = dice_loss,
                            optimizer = Adam(),
                            metrics = [dice_coef])

   def run_model(self):
      # For the sake of simplicity
      self.outputs = np.random.rand(8,64,12,86,98,1)    
      self.labels = np.random.rand(64, 12, 86, 98)

      # labels shape = (64, 12, 86, 98) to get (1,64,12,86,98)
      self.labels = np.expand_dims(self.labels, axis = (0,-1))
      # outputs shape (8,64,12,86,98,1) to -> (1,64,12,86,98,8)
      self.outputs = np.swapaxes(self.outputs, 0,-1)
      
      self.build_model()

      self.model.fit([self.outputs, self.labels],
                                batch_size = 1,
                                epochs = 200)
```

**Comment by Dynmi** [comment]
That's not a bug, but an error in your code. 
The input_shape of your model is (None,1,64,12,86,98,8), but the shape of x data you feed into it is (1,64,12,86,98,8). They don't match.

In Tensorflow2+ or keras, all the model will leave the first dimension of data's shape for batch-size, for example, one single sample of X has a shape (8,8),  corresponding, the input-shape of model will be (None, 8, 8), where "None" stands for "batch-size" .

**Comment by Saduf2019** [comment]
@danielfllaneza 
Can you please follow the links shared, the issue reported is due to error in your code.

**Comment by danielfllaneza** [comment]
Thanks for your replies.
I have tried the following:
1) [#10053](https://github.com/keras-team/keras/issues/10053)
```
# method def run_model
(...)
self.labels = self.labels.reshape([-1,1,64,12,86,98])
(...)
```
